### ISSUE TITLE
Multi word matcher and NER.

### ISSUE THREAD

**Issue by irfan-zoefit** [explosion/spaCy#1000]
I've trained NER and the training data looks like this.
`('For lunch today I had three Morton fish sticks a small order of French fries and a root beer', [(4, 9, 'MEAL'), (22, 27, 'QUANTITY'), (28, 34, 'BRAND'), (35, 46, 'FOOD'), (47, 48, 'QUANTITY'), (49, 60, 'UNIT'), (64, 76, 'FOOD'), (81, 82, 'QUANTITY'), (83, 92, 'FOOD')])`

My model identifies the food items or multi-word entity as a separate token like this.

```shell
For  ->>   IN  For
lunch  ->>  MEAL NN  lunch
today  ->>   NN  today
I  ->>   PRP  I
had  ->>   VBD  had
three  ->>  QUANTITY CD  three
Morton  ->>  BRAND NNP  Morton
fish  ->>  FOOD NN  fish
sticks  ->>  FOOD VBZ  sticks
a  ->>  QUANTITY DT  a
small  ->>  UNIT JJ  small
order  ->>  UNIT NN  order
of  ->>   IN  of
French  ->>  FOOD JJ  French
fries  ->>  FOOD NNS  fries
and  ->>   CC  and
a  ->>  QUANTITY DT  a
root  ->>  FOOD NN  root
beer  ->>  FOOD NN  beer
```

It should say
```shell
root beer ->> FOOD ... 
```
instead of
```shell
root  ->>  FOOD NN  root
beer  ->>  FOOD NN  beer
```

What if I want to train the NER with Multiword matcher? I did not find any example for identifying the multi-word entity and adding it to NER.

For example, I want a multi-word matcher for FOOD entity. Can you give me the examples of setting a multi-word matcher as I have seen the example **multi_word_matches.py** and it only shows to load the pattern.
## Info about spaCy

* **spaCy version:** 1.8.0
* **Installed models:** en, en_default
* **Platform:** Linux-4.4.0-72-generic-x86_64-with-Ubuntu-16.04-xenial
* **Python version:** 3.5.1+

**Comment by thomasopsomer** [comment]
After applying the model, you just need to merge entities (which are spans) into tokens, with this function for instance:

```python
def merge_ents(doc):
    """ Merge entities in the doc to appear as one token
    """
    for ent in doc.ents:
        ent.merge(ent.root.tag_, ent.text, ent.root.ent_type_)
```

**Comment by irfan-zoefit** [comment]
@thomasopsomer The issue is how to train NER about the multi-words entities.
