### ISSUE TITLE
Error in nlp object

### ISSUE THREAD

**Issue by jorgemzv7** [explosion/spaCy#10004]
Hi guys, I am new to nlp and I was prepairing my training data to the spacy format using the code sample which is given in the documentation [https://spacy.io/usage/training#training-data](url). I would appreciate some help. 

Firstly I converted my data to the format [(text1, [(startPos1, endPos1, LABEL), (starPos2, ...)]),(text2...)]

Now I am trying to execute this code:

`f = open(path1, "r", encoding="UTF-8")
    print("Charging file...")
    training_data = eval(f.read())
    f.close()
    from spacy.tokens import DocBin

    nlp = spacy.blank("es")
    # the DocBin will store the example documents
    db = DocBin()
    for text, annotations in training_data:
        doc = nlp(text)
        ents = []
        for start, end, label in annotations:
            span = doc.char_span(int(start), int(end), label=label)
            ents.append(span)
        doc.ents = ents
        db.add(doc)
    db.to_disk(f"venv\\Spacy-folder\\Datasets\\DOC{ttype}.spacy")`

But it is throwing me this error:
_Traceback (most recent call last):
  File "C:\Users\Jorge\PycharmProjects\TFG\main.py", line 295, in <module>
    preprocess("training")
  File "C:\Users\Jorge\PycharmProjects\TFG\main.py", line 223, in preprocess
    doc.ents = ents
  File "spacy\tokens\doc.pyx", line 743, in spacy.tokens.doc.Doc.ents.__set__
  File "spacy\tokens\doc.pyx", line 1753, in spacy.tokens.doc.get_entity_info
TypeError: object of type 'NoneType' has no len()

Process finished with exit code 1_

## My Environment
- **spaCy version:** 3.2.1
- **Platform:** Windows-10-10.0.19043-SP0
- **Python version:** 3.9.7
- **Pipelines:** es_core_news_lg (3.2.0), es_dep_news_trf (3.2.0)

**Comment by polm** [comment]
I assume you figured this out, but if not please feel free to follow up. Note that since this is a question and not a bug report it should go in Discussions.
