### ISSUE TITLE
displacy DEFAULT_LABEL_COLORS schema mismatch en_core_web_trf

### ISSUE THREAD

**Issue by davidberenstein1957** [explosion/spaCy#10042]
## How to reproduce the behaviour
from spacy.displacy.render import DEFAULT_ENTITY_COLOR, DEFAULT_LABEL_COLORS}
does not align with 
https://spacy.io/models/en#en_core_web_trf

## Your Environment
N.A
* Operating System:
* Python Version Used: 3.8.10
* spaCy Version Used: 3.2.0
* Environment Information: Windows 11

**Comment by polm** [comment]
What do you mean exactly? 

Looking at the list of entities there and the list in the displacy colors, I see that the model has `FAC` and displacy has `FACILITY`. But that's the same for all the English models.
