### ISSUE TITLE
TypeError: can not serialize 'cupy._core.core.ndarray' object

### ISSUE THREAD

**Issue by jayshow03** [explosion/spaCy#10066]
TypeError: can not serialize 'cupy._core.core.ndarray' object
Did anyone get this question when training a Spacy model using GPU?

**Comment by polm** [comment]
Can you give more details? What exactly did you do that caused this to happen? What is your version of spaCy (output of `spacy info`), CUDA related packages, the full stack trace, etc.

**Comment by jayshow03** [comment]
You can see the details here: https://support.prodi.gy/t/typeerror-can-not-serialize-cupy-core-core-ndarray-object/5191
I appreciate any suggestions!

**Comment by polm** [comment]
Since we are following up on this at the Prodigy forums I'm going to close this. It's not clear there's a bug here, but if it turns out there is one we can open a new issue and refer to this later.
