### ISSUE TITLE
Please add the Per-class Metrics for en_core_web_trf on NER-Task

### ISSUE THREAD

**Issue by maximilianreimer** [explosion/spaCy#10076]
It would be very helpful to have the per-token f1-scores, precision, and recall for each NER-Tag in the [Metrics section](https://spacy.io/models/en#en_core_web_trf
) too. Since the dataset (OntoNotes) is not publicly available it is not trivia to add it for others. 

## Which page or section is this issue related to?
[Doc of en_core_web_trf](https://spacy.io/models/en#en_core_web_trf)
[Readme of en_core_web_trf ](https://github.com/explosion/spacy-models/releases/tag/en_core_web_trf-3.2.0)

**Comment by honnibal** [comment]
Just to clarify, you want the per class breakdown (like the P/R/F for ORG, PERSON etc) right? I don't think per-token accuracies should be reported as the task is per span.

**Comment by adrianeboyd** [comment]
The span PRF per type scores are available in `meta.json` in the saved model package/directory or in a loaded model in `nlp.meta` under `nlp.meta["performance"]["ents_per_type"]`.
