### ISSUE TITLE
How to add custom features on token for EntityRecognizer model

### ISSUE THREAD

**Issue by damianoporta** [explosion/spaCy#1007]
Hello,
i need to add custom features on token to improve the accuracy of my model.
Is there no direct api to add these custom features?

Thank yoi

**Comment by honnibal** [comment]
What features are you trying to add? Currently you have to write these in Cython, because it's otherwise quite difficult to make the feature extraction code efficient. It's really not so difficult --- I can help you if you describe what's needed.

**Comment by damianoporta** [comment]
Hi @honnibal thank you so much for your fast reply. 
Yes i can learn cython no problem for that, but i should understand how to implement it.
For example:

1. At the moment i am using an italian stemmer and i would like to add this feature too, like: **stem=abc** 

2. Another feature i need is passing a specific character (lets suppose an hiphen) and set something like:

s=False # Token does not not have an hiphen as the first character
c=True # Token contains the hiphen
e=False # Token ends with an hiphen

**Comment by honnibal** [comment]
For 1, you could hijack the `.lemma` attribute. This is already extracted as a token feature, so you won't have to do anything. For 2, I suspect the default features will actually cover this well. The word shape feature describes this sort of thing.
