### ISSUE TITLE
Contractions incorrectly tokenized when part of an infix substring

### ISSUE THREAD

**Issue by johnmccain** [explosion/spaCy#10086]
Contractions and other special tokenization rules are not correctly applied when they are part of an infix substring such as words separated by a hyphen or em dash.

## How to reproduce the behaviour
```
import spacy
nlp = spacy.load('en_core_web_sm')

print(list(nlp.tokenizer("don't look--don't see")))
# [do, n't, look, --, don't, see]

print(list(nlp.tokenizer.explain("don't look--don't see")))
# [('SPECIAL-1', 'do'), ('SPECIAL-2', "n't"), ('TOKEN', 'look'), ('INFIX', '--'), ('TOKEN', "don't"), ('TOKEN', 'see')]
```

## Your Environment

- **spaCy version:** 3.2.1
- **Platform:** macOS-11.6.1-x86_64-i386-64bit
- **Python version:** 3.9.9
- **Pipelines:** en_core_web_sm (3.2.0), en_core_web_lg (3.2.0)

## Cause

Based on my reading of the [`explain`](https://github.com/explosion/spaCy/blob/master/spacy/tokenizer.pyx#L613) tokenizer method, it looks like special tokenization rules are meant to be applied on a second pass after separating an infix substring into separate tokens. It does this by using a `PhraseMatcher` looking for the special tokens, but the rules for some special cases like `don't` are not being correctly added to the `PhraseMatcher`.
I believe [tokenizer.pyx:605](https://github.com/explosion/spaCy/blob/ac45ae3779f9b021ebc2227ae6b3104811132979/spacy/tokenizer.pyx#L605) is the culprit. Before adding the PhraseMatcher rule, there is a condition checking if the special case's string contains a prefix, suffix, infix, or space character. If the special case doesn't meet this condition, then the rule will never be added and we get the behavior seen above. When I removed this line and rebuilt spaCy I got the expected output.

Output after removing the condition on line 605:
```
import spacy
nlp = spacy.load('en_core_web_sm')

print(list(nlp.tokenizer("don't look--don't see")))
# [do, n't, look, --, do, n't, see]

print(list(nlp.tokenizer.explain("don't look--don't see")))
# [('SPECIAL-1', 'do'), ('SPECIAL-2', "n't"), ('TOKEN', 'look'), ('INFIX', '--'), ('SPECIAL-1', 'do'), ('SPECIAL-2', "n't"), ('TOKEN', 'see')]
```

I'm not sure of the broader repercussions of removing this condition, so I'll leave it for someone with more experience in the spaCy codebase to determine the appropriate fix.

**Comment by polm** [comment]
This might be the same as #5598?

**Comment by johnmccain** [comment]
I went ahead and opened a PR with the changes corrected this issue for me. https://github.com/explosion/spaCy/pull/10090

**Comment by johnmccain** [comment]
Are there any updates on this? It sounded like there may be performance implications to the changes in my PR, does this need a more involved fix? Thanks!

**Comment by svlandeg** [comment]
Hi! I've left you a comment on the [PR](https://github.com/explosion/spaCy/pull/10090) :-)
