### ISSUE TITLE
Inconsistency between span.sent and span.ents when span crosses sentence boundary

### ISSUE THREAD

**Issue by nrodnova** [explosion/spaCy#10135]
## How to reproduce the behaviour

When a span crosses sentence boundary, that span is not in it's own sentence entity list, which doesn't make sense,

This is because `Span.sent` returns the first sentence, if the span belongs to multiple ones. However, `Span.ents` does not include partial entities.

To make it consistent, `Span.ents` should include a partial entity at the end of the span (not at the beginning, otherwise it will be inconsistent again).

I can make the change, just let me know if you are fine with the logic. Or suggest an alternative :)

The code below demonstrates the problem:

```
import spacy
from spacy.tokens import Span

nlp = spacy.load('en_core_web_sm')
text = "First sentence. Second sentence"
doc = nlp(text)

entity = Span(doc, 2, 4, label = 'LABEL')
print("Entity:", entity)
sentence = entity.sent
print("Entity's sentence:", sentence)

print("Entity belongs to its sentence:",  entity in entity.sent.ents)
```

## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by adrianeboyd** [comment]
I think our answer is going to be that the current behavior seems like the least bad option. Partial entity spans would be problematic because they often aren't entities or aren't the same type of entity. We can definitely improve the docs for `Span.ents` to clarify that it only includes the entities that fall completely within the span.

In general, spacy assumes that entities won't cross sentence boundaries. The `ner` component won't predict entities across sentence boundaries, for instance.

**Comment by nrodnova** [comment]
Sorry, I think my wording was confusing. I don't mean including a part of an entity, I meant, include the whole entity that overlaps with the sentence end. This will ensure that an entity is always contained in it's own sentence. From the example above:
```
text = "First sentence. Second sentence"
entities = ["First", "sentence", ". Second", "sentence"]
sentence_1.ents will contain  ["First", "sentence", ". Second"]
sentence_2.ents will contain ["sentence"]

and assert * entity in entity.sent.ents * will always hold
```

**Comment by adrianeboyd** [comment]
I think it's going to be unexpected to get spans from `Span.ents` that include tokens outside of the original span. We discussed this internally and would prefer leave the current behavior as it is. Doc clarifications should be coming soon...
