### ISSUE TITLE
Question concerning the JSON input format for training

### ISSUE THREAD

**Issue by kimeaa** [explosion/spaCy#1013]
I have a question concerning the [JSON input format for training](https://spacy.io/docs/api/annotation#json-input). I want to train the NER only using the spaCy CLI (`python -m spacy train ... --no_tagger --no_parser `). I have a dataset with words and their respective entities separated by a whitespace. How would the JSON  input format look like, given this file and the fact I want to train the NER only?

Based on your answer, I could create a new converter for the spaCy [convert](https://spacy.io/docs/usage/cli#convert) CLI command.

**Comment by ines** [comment]
Sorry about the late reply – merging this with #1291. For v2.0, we're working on updating the JSON format on the website and the documentation around it!
