### ISSUE TITLE
Wrong Part-of-Speech tag for small English model

### ISSUE THREAD

**Issue by XsongyangX** [explosion/spaCy#10151]
## How to reproduce the behaviour

The sentence `Workflow State Class, collaborates with WorkflowProcessActivity` has its root word `collaborates`'s POS misidentified by Spacy's `en_core_web_sm` model.

```py
import spacy
nlp = load("en_core_web_sm")
doc = nlp("Workflow State Class, collaborates with WorkflowProcessActivity")
print(doc[4].pos_) # you get NOUN, it should be a verb
```

## Your Environment

- **spaCy version:** 3.2.1
- **Platform:** Windows-10-10.0.22000-SP0
- **Python version:** 3.10.1
- **Pipelines:** en_core_web_sm (3.2.0)

**Comment by polm** [comment]
Please see #3052 - while we appreciate the attention to detail, there's no way for us to address reports of isolated errors.
