### ISSUE TITLE
why no result in this example?

### ISSUE THREAD

**Issue by hoyeunglee** [explosion/spaCy#1016]
https://www.oreilly.com/learning/how-do-you-find-the-parts-of-speech-in-a-sentence-using-python

import spacy
from spacy.en import English
parser = English()

def show_dep(text):
    tokens = parser(text)
    for token in tokens:
        print(" {:<8} : {:<5} : {:<7} : {}".format(token.orth_,token.pos_,token.dep_,token.head))

print(" {:<8} : {:<5} : {:<7} : {}".format("token","POS","dep.","head"))
print("------------------------------------")
show_dep("I drove home with joy.".decode('utf-8',errors='ignore'))

![noresult](https://cloud.githubusercontent.com/assets/5094741/25341090/4c9a27e6-293a-11e7-858a-a461a4850cc8.png)

**Comment by honnibal** [comment]
I think you probably need to install the model

```
python -m spacy download en
```

**Comment by hoyeunglee** [comment]
i had already installed with "python -m spacy download en"

**Comment by hoyeunglee** [comment]
>>> nlp = spacy.load('en')

[93m    Warning: no model found for 'en'[0m

    Only loading the 'en' tokenizer.


then search in google , it said solved by

from spacy.en import English

but i had already imported directly

**Comment by ines** [comment]
The above error definitely means the model can't be found by spaCy. `from spacy.en import English` won't help here, as this only loads the tokenizer. I just had a look at the tutorial you linked and the explanation there doesn't seem to be ideal – it doesn't mention the models, which are definitely needed if you want part-of-speech tags.

Are you using a `virtualenv` and if so, did you install the model in the same environment? spaCy uses pip to install the model, so it should also show up in your installed packages. If you run the following command, does it show `en-core-web-sm`?

```bash 
pip list
```

If not, try running the download command again, or download and link the model to the shortcut `'en'` manually:

```bash
pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-1.2.0/en_core_web_sm-1.2.0.tar.gz
python -m spacy link en_core_web_sm en
```

You should now be able to load the model via `spacy.load('en')`, or simply import it as a Python module and call its `load()` method:

```python
import en_core_web_sm
nlp = en_core_web_sm.load()
doc = nlp(u'This is a sentence.')
```

There's also more info on this available in the [models documentation](https://spacy.io/docs/usage/models#download).

**Comment by hoyeunglee** [comment]
I had not run virtualenv command
After pip install spacy and then install en in window cmd

**Comment by honnibal** [comment]
Thanks for updating, glad this is fixed!

**Comment by eleijonmarck** [comment]
python -m spacy download en

Solved the problem for me
