### ISSUE TITLE
Model interfere with lemmatization given by tokenization_exception.py

### ISSUE THREAD

**Issue by Gregory-Howard** [explosion/spaCy#1017]
Having a model (in french) prevent tokenizer_exception.py to work properly.

Exemple of rule https://github.com/explosion/spaCy/blob/master/spacy/fr/tokenizer_exceptions.py#L117 :
(It's the same problem for every rule)
(You need to download the french model before : https://github.com/pagesjaunes/spacy-french-models )
```
import spacy
nlp = spacy.load("fr")
doc = nlp("est-t-elle là?")
print(doc[0].lemma_) # être (right)

nlp = spacy.load("fr_default")
doc = nlp("est-t-elle là?")
print(doc[0].lemma_) # est (wrong)
```

I tested with an another model (trained by myself but still in french)

Actually it's the same in english.
If you modify https://github.com/explosion/spaCy/blob/master/spacy/en/tokenizer_exceptions.py#L105
with 
```
{ORTH: "'re", LEMMA: "bee", NORM: "are"}
```
With a model(en) : 
```
import spacy
nlp = spacy.load("en")
doc = nlp("You're here ?")
print(doc[1].lemma_) # be
```
without (just rename spacy/data/en to spacy/data/en_: 
```
import spacy
nlp = spacy.load("en")
doc = nlp("You're here ?")
print(doc[1].lemma_) # bee
```

## Info about spaCy
* **Installed models:** fr_default
* **Platform:** Windows-7-6.1.7601-SP1
* **spaCy version:** 1.8.1
* **Python version:** 3.5.2

**Comment by honnibal** [comment]
The behaviour's a bit unintuitive here sorry. Here's `Tagger.__call__`:

```
        if tokens.length == 0:
            return 0

        cdef Pool mem = Pool()

        cdef int i, tag
        cdef Example eg = Example(nr_atom=N_CONTEXT_FIELDS,
                                  nr_class=self.vocab.morphology.n_tags,
                                  nr_feat=self.model.nr_feat)
        for i in range(tokens.length):
            if tokens.c[i].pos == 0:
                self.model.set_featuresC(&eg.c, tokens.c, i)
                self.model.set_scoresC(eg.c.scores,
                    eg.c.features, eg.c.nr_feat)
                guess = VecVec.arg_max_if_true(eg.c.scores, eg.c.is_valid, eg.c.nr_class)
                self.vocab.morphology.assign_tag_id(&tokens.c[i], guess)
                eg.fill_scores(0, eg.c.nr_class)
        tokens.is_tagged = True
        tokens._py_tokens = [None] * tokens.length
```

The key line is `if tokens.c[i].pos == 0:` --- if you set the `.pos` attribute, your lemma won't be clobbered by the model.

Which docs page would it be most useful to write this? I suppose `Tagger.__call__` in the API docs. Is there a usage page you've been consulting as well?

**Comment by Gregory-Howard** [comment]
Okay ! Thanks for the answer. Just verified, I will probably make some pull request today.
I think it will be more usefull to add this problem in https://spacy.io/docs/usage/customizing-tokenizer#special-cases
I think (for the moment)  most people look this page.


Actually a lot of rules in other languages have no POS tag. (https://github.com/explosion/spaCy/blob/master/spacy/en/tokenizer_exceptions.py#L510)
So the lemmatisation does'nt works
```
import spacy
nlp = spacy.load("en")
doc = nlp("Mt. Rainer is beautiful.")
print(doc[0].lemma_) #mt.
```
