### ISSUE TITLE
How can I obtain similiar words using spacy Word2Vec (sense2vec) representation?

### ISSUE THREAD

**Issue by mzafzal** [explosion/spaCy#1018]
Hi

There was an answer for synonyms using vocab (the following link)
https://github.com/explosion/spaCy/issues/276

I ma wondering how we could use sense2vec for obtaining these results.
Its simple in gensim calling the method most_similar().
Any help would be great!

Thanks

Shan

**Comment by honnibal** [comment]
You should continue using Gensim for doing `most_similar()` queries. Now the vector table is stored as a single numpy array, you can use the same vectors table in both spaCy and Gensim. Gensim has put a fair bit of thought into providing approximate nearest neighbour search etc for `most_similar()`, so I don't think we need to duplicate the functionality.
