### ISSUE TITLE
TypeError: unhashable type: 'spacy.tokens.span.Span'

### ISSUE THREAD

**Issue by avissens** [explosion/spaCy#1019]
TypeError: unhashable type: 'spacy.tokens.span.Span'

I use nlp(text) to get human names from news articles. I gather all PERSON ents into a list but when I try to manipulate the list I get this error: TypeError: unhashable type: 'spacy.tokens.span.Span'

My code:

```
text='James Harding, professor at the UCL, and Lucy Smith, a student.'
text=u"{}".format(text)
all_tags = nlp(text)
names=[]
for ent in all_tags.ents:
    if ent.label_=="PERSON":
        names.append(ent)
print names
print type(names)
myset = list(set(names)) #remove duplicates
print(myset)
mynewlist = [ x for x in myset if " " in x ] # remove lonely names
print(mynewlist)

```
Output:

[James Harding, Lucy Smith]
<type 'list'>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-157-1ecc20e5c9ea> in <module>()
      8 print names
      9 print type(names)
---> 10 myset = list(set(names)) #remove duplicates
     11 print(myset)
     12 mynewlist = [ x for x in myset if " " in x ] # remove lonely names

TypeError: unhashable type: 'spacy.tokens.span.Span'

## Info about spaCy

* **Python version:** 2.7.13
* **Platform:** Darwin-16.4.0-x86_64-i386-64bit
* **spaCy version:** 1.8.1
* **Installed models:** en

**Comment by honnibal** [comment]
Added, thanks!

**Comment by avissens** [comment]
I uninstall and install the package again but I get the same error...
