### ISSUE TITLE
Allow pydantic v1.9.0 as dependency

### ISSUE THREAD

**Issue by syonekura** [explosion/spaCy#10203]
## How to reproduce the behaviour
Due to security reasons after https://github.com/explosion/spaCy/pull/8127 pydantic dependencies were tighten for good measure. A few weeks ago a new version of pydantic was released (1.9.0), that is currently not allowed for this project.

By disallowing the usage of 1.9.0, we can't use some of the [new features](https://pydantic-docs.helpmanual.io/changelog/#v190-2021-12-31) of that library along with spacy. Please consider:
- Removing the upper bound `<1.9.0`
- Increment the upper bound, ie `<2.0.0`

btw, this also hits https://github.com/explosion/thinc

## Your Environment

* Operating System: Linux
* Python Version Used: 3.7
* spaCy Version Used: a2f27ff83aec1aac8c1798efdf75519c9e49cdde
* Environment Information:

**Comment by adrianeboyd** [comment]
Please see: https://github.com/explosion/spaCy/discussions/10142

**Comment by theY4Kman** [comment]
There appears to be a PR in the works: https://github.com/explosion/spaCy/pull/10384

**Comment by vmstarchenko** [comment]
Any updates here?
Looks like the issue with thinc is already closed and it supports pydantic==1.9 now:
https://github.com/explosion/thinc/blob/master/setup.cfg#L51

**Comment by erikjar** [comment]
@adrianeboyd Any updates here? As per the above comment thinc should now support pydantic 1.9.

**Comment by adrianeboyd** [comment]
The pydantic updates have been merged in #10786 and will be in the upcoming spacy v3.4 release.

**Comment by xkortex** [comment]
I understand where this is coming from: 
https://github.com/explosion/spaCy/issues/8428#issuecomment-863789695

however, Pydantic is quite stable at this point, and given its wide use, pinning a tight upper bound leads to a lot of brittleness. Has Pydantic minor version bumping actually caused issues in the past?

**Comment by adrianeboyd** [comment]
The updates for the newer releases of `pydantic`+`mypy` turned out to be very involved: https://github.com/explosion/thinc/pull/599

Even in some cases where we have our own libraries as dependencies, I've run into cases often enough where I regretted having upper pins that were too wide (a recent example: https://github.com/explosion/thinc-apple-ops/pull/15), and the problem is only worse for third-party libraries.

**Comment by vmstarchenko** [comment]
> The pydantic updates have been merged in #10786 and will be in the upcoming spacy v3.4 release.

Do you have any predictions when spacy v3.4 would be released? 😃
