### ISSUE TITLE
POS Tagging example error?

### ISSUE THREAD

**Issue by SwedishBotMafia** [explosion/spaCy#1020]
Bug:
https://spacy.io/docs/usage/pos-tagging

The example code results in the word 'duck' being classified as a Noun when it's a Verb in that context

## Your Environment
* **Python version:** 2.7.12
* **Platform:** Linux-4.7.2-040702-generic-x86_64-with-Ubuntu-16.04-xenial
* **spaCy version:** 1.8.1
* **Installed models:** en

![spacy](https://cloud.githubusercontent.com/assets/5893559/25441494/01d98452-2a68-11e7-99ac-23fb91332a72.png)

**Comment by honnibal** [comment]
That's a bit annoying, thanks! I guess the small model performs worse on that one. I'll think about writing a better example.

**Comment by SwedishBotMafia** [comment]
Just wanted to let you know, Great tool. I'm really enjoying using it.
