### ISSUE TITLE
Dependency parser/tagger misidentifies a verb as a noun

### ISSUE THREAD

**Issue by notnami** [explosion/spaCy#1021]
Here is an example input

```import spacy

nlp = spacy.load('en_depent_web_md')
doc = nlp("Does this phone work?")

for token in doc:
    print(token, token.pos_, token.tag_, token.dep_, token.head)
    print()
```

Here is the output:

```
Does VERB VBZ ROOT Does

this DET DT det work

phone NOUN NN compound work

work NOUN NN dobj Does

? PUNCT . punct Does
```

As you can see, spaCy incorrectly classifies _work_ as a noun, which (I assume) leads to the dependency parser failing to label it as the root, and thus misidentifying the root as `Does`.

You can play with variations of the above input, such as "Will this phone work?" or "Would this phone work?" In all of the above cases, spaCy fails to pull out "work" as the root.

This would be a minor annoyance, but I rely on the dependency parse for a lot of my downstream tasks, and the "{does/will/would} this work" pattern is common for my data. (I can only think of one example where labelling *work* as a noun would be correct, such as "I did some work on this phone", but that strikes me as a rarer case than the one I have encountered, and that doesn't explain the case of a sentence starting with {would/will}.)

I don't know if this problem lies with the part of speech tagger, which assigns an erroneous tag to _work_, and thus messes up the dependency parser, or if it's something else. 

Would you have any idea about what is causing this? If so, is there a way to fix it without re-training the whole model?

Thanks!

## Info about spaCy

* **spaCy version:** 1.8.2
* **Platform:** Linux-4.4.0-43-Microsoft-x86_64-with-Ubuntu-16.04-xenial
* **Python version:** 3.6.1
* **Installed models:** __cache__, en, en-1.1.0, en_core_web_md, en_default, en_depent_web_md

**Comment by notnami** [comment]
Could be related to #1015.

How many examples would one need to correctly update the pre-trained model?

**Comment by notnami** [comment]
```
I tried the following code, based on the one from #1015, but even after 100,000 iterations I had no luck making it recognise work as a verb:

training_data = [
    ('Will this phone work?', 'MD DT NN VB .'),
    ('Would this phone work?', 'MD DT NN VB .'),
    ('Does this car work?', 'VBZ DT NN VB .'),
    ('This does work', 'DT VBZ VB'),
    ('Can this work?', 'MD DT VB .'),
    ('work', 'VB')
]

def update_tagger(tagger, example):
    orth_text, label_text = example
    doc = nlp.tokenizer(orth_text)
    tags = label_text.split()
    assert len(doc) == len(tags), 'Tokenisation does not match tags for {}'.format(orth_text)
    gold = spacy.gold.GoldParse(doc, tags=tags)
    tagger.update(doc, gold)

def train_tagger(tagger, examples):
    for i in range(100000):
        for example in examples:
            update_tagger(tagger, example)
    tagger.model.end_training()

train_tagger(nlp.tagger, training_data)
```

At this point, I would prefer it to err on the side of work always being a verb rather than a noun (I understand that such behaviour might be desired in the general case, but it would _work_ for my data).

In the meantime, I've found that if I replace _work_ with some other verb that I'm not likely to see in my data set, like "hasten", I would get the correct dependency parse. But that feels like a very silly workaround.

**Comment by ines** [comment]
Closing this and making #1057 the master issue – work in progress for spaCy v2.0!
