### ISSUE TITLE
phrasematcher.pyi has the wrong type annotation for `docs` parameter in `add`

### ISSUE THREAD

**Issue by ramonziai** [explosion/spaCy#10234]
## How to reproduce the behaviour

Typecheck any (type-annotated) code that uses `PhraseMatcher.add()` with mypy. You'll get something like:

`error: List comprehension has incompatible type List[Doc]; expected List[List[Dict[str, Any]]]`

mypy is correct because line 17 of phrasematcher.pyi actually reads `docs: List[List[Dict[str, Any]]],`, but it should probably be `docs: List[Doc]` according to https://spacy.io/api/phrasematcher#add.

## Your Environment

* Operating System: Ubuntu 20.04 (on GitHub Actions)
* Python Version Used: 3.8
* spaCy Version Used: >= 3.1.4

**Comment by adrianeboyd** [comment]
Hi Ramon! I'd come across this too and have a fix in an adjacent PR (#9880), but it's not clear when that will be merged, so we can fix this separately for the next patch release instead. If you'd like to submit a PR you are welcome to, but I can also do it if you'd prefer.

**Comment by ramonziai** [comment]
Hey Adriane :smile: Ok sure, I'm happy to submit a PR. The guidelines say I should write a failing test for the bug first, can I skip that since it's more of a "meta problem"?

**Comment by adrianeboyd** [comment]
Yeah, the types aren't checked directly by the unit tests anyway, so you can skip writing a test for this.

**Comment by ramonziai** [comment]
See https://github.com/explosion/spaCy/pull/10235.
