### ISSUE TITLE
Impossible to install a model with Poetry

### ISSUE THREAD

**Issue by LifeIsStrange** [explosion/spaCy#10269]
poetry add spacy works
it resolves to 
setuptools = "^60.8.2"
wheel = "^0.37.1"
spacy = "^3.2.2" in my pyproject.toml however
en_core_web_trf = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.2.0/en_core_web_trf-3.2.0-py3-none-any.whl" }
or poetry add https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.2.0/en_core_web_trf-3.2.0-py3-none-any.whl
leads to the following error:
```Unable to find installation candidates for torch (1.10.2)```

I don't know what to do, it worked on older versions. Spacy **should** work with Poetry, I have lost a day already with this.
On a fresh virtual env, with python 3.10
@adrianeboyd friendly ping help plz

**Comment by LifeIsStrange** [comment]
https://stackoverflow.com/questions/56239310/could-not-find-a-version-that-satisfies-the-requirement-torch-1-0-0
so spacy would silently include pytorch 1.10.2 which does not support python past 3.7.9? ...

**Comment by polm** [comment]
Moving to Discussions since this is install-related.

Also please do not ping individual maintainers, it disrupts notifications.
