### ISSUE TITLE
how to install spacy in window

### ISSUE THREAD

**Issue by hoyeunglee** [explosion/spaCy#1030]
this time i install virtualenv, but still have error about no package

python -m pip install -U pip virtualenv
git clone https://github.com/explosion/spaCy
cd spaCy

virtualenv .env

do not have this command in window , source .env/bin/activate

pip install -r requirements.txt
pip install -e .

python -m spacy download en

python -m pip install -U pip virtualenv
git clone https://github.com/explosion/spaCy
cd spaCy

virtualenv .env

do not have this command in window , source .env/bin/activate

pip install -r requirements.txt
pip install -e .

python -m spacy download en

**Comment by ines** [comment]
Hey! Just to make sure I understand correctly: Are you trying to *compile* spaCy from source, or do you want to *install and run* spaCy?

If you only want to install spaCy in a `virtualenv`, this is the easiest way:

```bash
virtualenv .env
source .env/bin/activate
pip install spacy
python -m spacy download en
```

This will create a new, "isolated" `virtualenv` in the current directory and activate it. It then downloads and installs the spaCy package and the English model in that environment. To use spaCy, you just need to make sure your `virtualenv` is activated.

If the `source .env/bin/activate` command still fails, could you post the full error message here?

**Comment by hoyeunglee** [comment]
I install from source code but window cmd do not have source command

**Comment by beneyal** [comment]
Windows doesn't have the `source` command.

After running `virtualenv .env`, run `.env\Scripts\activate`. To deactivate the environment, run `deactivate`.

**Comment by ines** [comment]
Sorry, I think I misunderstood the question – thanks @beneyal!

We should probably add a note about this somewhere in the docs or troubleshooting guide, or at least link to the virtualenv docs.

**Comment by abhinaysurya** [comment]
hi friends! I am trying to install spacy using venv. I am getting the following message after pip installing spacy. please help me resolving this issue
........................................................................................
(.env) C:\Users\Abhinay\AppData\Local\Programs\Python\Python36-32\Scripts>pip3 install spacy
Collecting spacy
  Using cached spacy-1.9.0.tar.gz
Requirement already satisfied: numpy>=1.7 in c:\users\abhinay\appdata\local\programs\python\python36-32\lib\site-packages (from spacy)
Collecting murmurhash<0.27,>=0.26 (from spacy)
  Using cached murmurhash-0.26.4.tar.gz
Collecting cymem<1.32,>=1.30 (from spacy)
  Using cached cymem-1.31.2.tar.gz
Collecting preshed<2.0.0,>=1.0.0 (from spacy)
  Using cached preshed-1.0.0.tar.gz
Collecting thinc<6.6.0,>=6.5.0 (from spacy)
  Using cached thinc-6.5.2.tar.gz
Collecting plac<1.0.0,>=0.9.6 (from spacy)
  Using cached plac-0.9.6-py2.py3-none-any.whl
Requirement already satisfied: pip<10.0.0,>=9.0.0 in c:\users\abhinay\appdata\local\programs\python\python36-32\lib\site-packages (from spacy)
Requirement already satisfied: six in c:\users\abhinay\appdata\local\programs\python\python36-32\lib\site-packages (from spacy)
Collecting pathlib (from spacy)
Collecting ujson>=1.35 (from spacy)
  Using cached ujson-1.35.tar.gz
Collecting dill<0.3,>=0.2 (from spacy)
Collecting requests<3.0.0,>=2.13.0 (from spacy)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting regex<2017.12.1,>=2017.4.1 (from spacy)
  Using cached regex-2017.09.23-cp36-none-win32.whl
Collecting ftfy<5.0.0,>=4.4.2 (from spacy)
Collecting wrapt (from thinc<6.6.0,>=6.5.0->spacy)
Collecting tqdm<5.0.0,>=4.10.0 (from thinc<6.6.0,>=6.5.0->spacy)
  Using cached tqdm-4.19.1.post1-py2.py3-none-any.whl
Collecting cytoolz<0.9,>=0.8 (from thinc<6.6.0,>=6.5.0->spacy)
  Using cached cytoolz-0.8.2.tar.gz
Collecting termcolor (from thinc<6.6.0,>=6.5.0->spacy)
Collecting pyreadline>=1.7.1 (from dill<0.3,>=0.2->spacy)
Collecting chardet<3.1.0,>=3.0.2 (from requests<3.0.0,>=2.13.0->spacy)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests<3.0.0,>=2.13.0->spacy)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests<3.0.0,>=2.13.0->spacy)
  Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests<3.0.0,>=2.13.0->spacy)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting html5lib (from ftfy<5.0.0,>=4.4.2->spacy)
  Using cached html5lib-0.999999999-py2.py3-none-any.whl
Requirement already satisfied: wcwidth in c:\users\abhinay\appdata\local\programs\python\python36-32\lib\site-packages (from ftfy<5.0.0,>=4.4.2->spacy)
Collecting toolz>=0.8.0 (from cytoolz<0.9,>=0.8->thinc<6.6.0,>=6.5.0->spacy)
Requirement already satisfied: setuptools>=18.5 in c:\users\abhinay\appdata\local\programs\python\python36-32\lib\site-packages (from html5lib->ftfy<5.0.0,>=4.4.2->spacy)
Collecting webencodings (from html5lib->ftfy<5.0.0,>=4.4.2->spacy)
  Using cached webencodings-0.5.1-py2.py3-none-any.whl
Installing collected packages: murmurhash, cymem, preshed, wrapt, tqdm, toolz, cytoolz, plac, pyreadline, dill, termcolor, pathlib, thinc, ujson, chardet, idna, certifi, urllib3, requests, regex, webencodings, html5lib, ftfy, spacy
  Running setup.py install for murmurhash ... error
    Complete output from command c:\users\abhinay\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Abhinay\\AppData\\Local\\Temp\\pip-build-zb_kkqe3\\murmurhash\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Abhinay\AppData\Local\Temp\pip-d3hzpyrn-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.6
    creating build\lib.win32-3.6\murmurhash
    copying murmurhash\about.py -> build\lib.win32-3.6\murmurhash
    copying murmurhash\__init__.py -> build\lib.win32-3.6\murmurhash
    creating build\lib.win32-3.6\murmurhash\tests
    copying murmurhash\tests\test_import.py -> build\lib.win32-3.6\murmurhash\tests
    copying murmurhash\tests\__init__.py -> build\lib.win32-3.6\murmurhash\tests
    copying murmurhash\mrmr.pyx -> build\lib.win32-3.6\murmurhash
    copying murmurhash\mrmr.pxd -> build\lib.win32-3.6\murmurhash
    copying murmurhash\__init__.pxd -> build\lib.win32-3.6\murmurhash
    creating build\lib.win32-3.6\murmurhash\include
    creating build\lib.win32-3.6\murmurhash\include\murmurhash
    copying murmurhash\include\murmurhash\MurmurHash2.h -> build\lib.win32-3.6\murmurhash\include\murmurhash
    copying murmurhash\include\murmurhash\MurmurHash3.h -> build\lib.win32-3.6\murmurhash\include\murmurhash
    running build_ext
    building 'murmurhash.mrmr' extension
    creating build\temp.win32-3.6
    creating build\temp.win32-3.6\Release
    creating build\temp.win32-3.6\Release\murmurhash
    cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\abhinay\appdata\local\programs\python\python36-32\include -IC:\Users\Abhinay\AppData\Local\Temp\pip-build-zb_kkqe3\murmurhash\murmurhash\include -Ic:\users\abhinay\appdata\local\programs\python\python36-32\include -Ic:\users\abhinay\appdata\local\programs\python\python36-32\include /EHsc /Tpmurmurhash/mrmr.cpp /Fobuild\temp.win32-3.6\Release\murmurhash/mrmr.obj /Ox /EHsc
    error: command 'cl.exe' failed: No such file or directory

    ----------------------------------------
Command "c:\users\abhinay\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Abhinay\\AppData\\Local\\Temp\\pip-build-zb_kkqe3\\murmurhash\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Abhinay\AppData\Local\Temp\pip-d3hzpyrn-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Abhinay\AppData\Local\Temp\pip-build-zb_kkqe3\murmurhash\

**Comment by AnneshaChowdhury** [comment]
Hello abhinay, I am having the same error. Were you able to fix it?
