### ISSUE TITLE
ValueError: [E977] when comparing MorphAnalysis with a string object

### ISSUE THREAD

**Issue by martinabarletta** [explosion/spaCy#10303]
## How to reproduce the behaviour

I am trying to create a full analysis filling the empty spaces in order to get a well formed data frame after the analysis step and I encountered the following bug : 

```
    if x == '':

  File "spacy\tokens\morphanalysis.pyx", line 55, in spacy.tokens.morphanalysis.MorphAnalysis.__eq__

ValueError: [E977] Can not compare a MorphAnalysis with a string object. This is likely a bug in spaCy, so feel free to open an issue: https://github.com/explosion/spaCy/issues
```
Here the code needed to reproduce the bug:

```
import spacy
spacy_nlp = spacy.load('fr_core_news_lg')

content = "Il était une fois un loup et son fidèle serviteur le robot."

docs = spacy_nlp(content)
sentence=[]

for token in docs : 
    analyse = [token.text, token.lemma_, token.pos_, token.morph, token.dep_, token.head.text, token.head.pos_, [child for child in token.children]]
    sentence.append(analyse)
print(sentence)

for sent in sentence:
    for x in sent:
        if x == '':
            sent.replace('', None)

```
## Your Environment

- **spaCy version:** 3.2.1
- **Platform:** Windows-10-10.0.19044-SP0
- **Python version:** 3.9.7
- **Pipelines:** fr_core_news_lg (3.2.0)

**Comment by adrianeboyd** [comment]
Sorry, this error message is confusing here, and we should modify it.

`token.morph` returns a `MorphAnalysis` object. If you want the string version in CoNLL-U FEATS format, use `str(token.morph)` instead..

**Comment by martibbi** [comment]
Not a problem, I thought it was best to open the issue just in case it was a real bug.
Thanks for the suggestion, I encountered the same problems another time today and was able to solve it in this way.
Thanks again!
