### ISSUE TITLE
Pre-tokenized text still gets sentence segmented

### ISSUE THREAD

**Issue by shyamupa** [explosion/spaCy#1032]
I am trying to get dep. parses for pre-tokenized text. I have sentences and some tags (say NER) and I simply want the spacy dep.parser to run on it. However, when I provide pre-tokenized as described in #335, I still get output which segments my sentences. How to turn sentence segmentation off?

```python
nlp = spacy.load('en', vectors=False)
def write_tokenized_sent(sentence_tokens,tags):
    doc = nlp.tokenizer.tokens_from_list(sentence_tokens)
    nlp.tagger(doc)
    nlp.parser(doc)
    for sent in doc.sents:
        if len(sent)!=len(tags):  # this means sentence got segmented!
            for sent in doc.sents:
                print(sent)
            print(sentence_tokens)
            print(tags)
        return

toks = [u'okay', u'all', u'right', u'do', u'you', u'have', u'a', u'flight', u'on', u'united', u'airlines', u'from', u'atlanta', u'to', u'washington']
labs = len(toks)*["O"] # does not really matter
write_tokenized_sent(toks,labs)

```

The output I get is 

```
okay all right  # spacy sees this as first sentence ...
do you have a flight on united airlines from atlanta to washington  # and this as second!
[u'okay', u'all', u'right', u'do', u'you', u'have', u'a', u'flight', u'on', u'united', u'airlines', u'from', u'atlanta', u'to', u'washington']
[u'O', u'O', u'O', u'O', u'O', u'O', u'O', u'O', u'O', u'O', u'O', u'O', u'O', u'O', u'O']
```

## Info about spaCy
* **Python version:** 2.7.13
* **Platform:** Linux-4.4.0-75-generic-x86_64-with-debian-stretch-sid
* **spaCy version:** 1.8.2
* **Installed models:** __cache__, en-1.1.0, en_glove_cc_300_1m_vectors-1.0.0, en

**Comment by honnibal** [comment]
Unfortunately there's currently no way to do this :(.The parser is trained to do joint segmentation and parsing, and there's currently no API to disable the `Break` transitions.

Here's a quick and dirty solution:

* Clone the repo
* Build from source, test etc
* Modify `spacy/syntax/arc_eager.pyx` such that the `Break.is_valid` function always returns `False`

For a solution which doesn't require rebuilding the project: the `Break.is_valid` function is accessed through a function pointer, stored in `nlp.parser.moves.c[i].is_valid`. You'll need to find the index `i` of the `Break` transition. You could then set a pointer to a different function, which always returns `False`. You'll need to do this from a Cython module.

**Comment by honnibal** [comment]
In spaCy 2 the parser now respects the `token.is_sent_start` attribute, which can be set to a value in `(True, False, None)`.

In the following example, a pipeline component that sets `token.is_sent_start` is set to `False` is inserted before the parser. This is the right approach if you know there's exactly one sentence in each of your `Doc` objects.

```python

def prevent_sentence_boundary_detection(doc):
    for token in doc:
        # This will entirely disable spaCy's sentence detection
        token.is_sent_start = False
    return doc

nlp.add_pipe(prevent_sentence_segmentation, name='prevent-sbd', before='parser')
```
