### ISSUE TITLE
Similarly to #267, OpenMP building fails on OSX

### ISSUE THREAD

**Issue by tnarik** [explosion/spaCy#1033]
The patch described in #267 seems to be "wrong" (maybe I'm missing something, therefore the quotes).

Currently, the building/installation process fails with the following error:

```
Obtaining file:///private/tmp/spaCy
    Complete output from command python setup.py egg_info:
    warning: ner.pyx:131:29: Not all members given for struct 'Transition'
    warning: ner.pyx:131:29: Not all members given for struct 'Transition'
    Processing attrs.pyx
    Processing cfile.pyx
    Processing gold.pyx
    Processing lexeme.pyx
    Processing matcher.pyx
    Processing morphology.pyx
    Processing orth.pyx
    Processing parts_of_speech.pyx
    Processing pipeline.pyx
    Processing strings.pyx
    Processing symbols.pyx
    Processing tagger.pyx
    Processing tokenizer.pyx
    Processing typedefs.pyx
    Processing vocab.pyx
    Processing bits.pyx
    Processing huffman.pyx
    Processing packer.pyx
    Processing _parse_features.pyx
    Processing _state.pyx
    Processing arc_eager.pyx
    Processing beam_parser.pyx
    Processing iterators.pyx
    Processing ner.pyx
    Processing nonproj.pyx
    Processing parser.pyx
    Processing stateclass.pyx
    Processing transition_system.pyx
    Processing doc.pyx
    Processing span.pyx
    Processing token.pyx
    Cythonizing sources
    running egg_info
    writing spacy.egg-info/PKG-INFO
    writing dependency_links to spacy.egg-info/dependency_links.txt
    writing requirements to spacy.egg-info/requires.txt
    writing top-level names to spacy.egg-info/top_level.txt
    error: package directory 'spacy/platform/darwin/lib' does not exist
```

Removing the `PACKAGES.append` line from the `setup.py` file allows building, installation and use (by specifying a number of threads equal of less than the number of cores).

## Your Environment

* Operating System: Sierra
* Python Version Used: 3.6
* spaCy Version Used: HEAD
* Environment Information: tested with GCC and LLVM

**Comment by tnarik** [comment]
I just tried the whole process again (cloning the repo and building from virtualenv via a subprocess and everything is ok now). It must have been an issue with the first cloned repo I got. Apologies for that.

**Comment by ines** [comment]
No worries and thanks for the update! (We were slightly worried about this one – debugging the `setup.py` is always painful. So it's good to hear that the code seems to be okay after all!)
