### ISSUE TITLE
OOM Possible Leak

### ISSUE THREAD

**Issue by jacquesg** [explosion/spaCy#10341]
## How to reproduce the behaviour

I have inexplicable OOM when running `spacy project run evaluate`.

```
RuntimeError: CUDA out of memory. Tried to allocate 92.00 MiB (GPU 0; 23.70 GiB total capacity; 9.63 GiB already allocated; 128.88 MiB free; 10.85 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
The strange thing for me here is that 23.7GB of GPU RAM is available, but it seems like when it runs out of memory, it only knows about 10.85GB. I've tried to tweak a number of parameters to see if it makes a difference, but as far as I can tell none of them make any significant difference.

The `dev` dataset is tiny, it only has 1000 samples, on average I would guess each being 500 or so words.

![image](https://user-images.githubusercontent.com/3534453/154947725-220729dd-7b61-4076-b0b7-0d74c8aa5855.png)

## Your Environment

* Operating System: Linux (Ubuntu 20.04)
* Python Version Used: 3.8.12
* spaCy Version Used: 3.2.2
* Environment Information: NVIDIA Driver 510.47.03

**Comment by jacquesg** [comment]
Additional information: I'm using `torch 1.10.2`, but the same thing happens with `torch 1.10.1`.  I installed these by running:

```
pip install torch==1.10.2+cu113 torchvision==0.11.3+cu113 torchaudio==0.10.2+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
```

**Comment by adrianeboyd** [comment]
My first guess is that it's related to the `gpu_allocator` setting, which is set by `spacy train` but isn't currently configurable through `spacy evaluate`. Here's a related thread with some background: #8984

Can you see if it makes a difference if you add `set_gpu_allocator("pytorch")` right after `setup_gpu` in `spacy/cli/evaluate.py`?

**Comment by jacquesg** [comment]
That does indeed fix it. Thank you!

No idea around the scope of the changes, and actually haven't read the whole of #8984, but is this trivially fixable? Put differently, a work-around would be useful, patching `spacy` isn't something I'd like to do or maintain myself :smile: 

![image](https://user-images.githubusercontent.com/3534453/154954289-3f486da5-c71b-45e1-856f-722f998828ac.png)

**Comment by adrianeboyd** [comment]
It's on our medium-priority to-do list, but it's a bit more involved to only set it when a model that uses torch is loaded vs. setting it when the user has `torch` installed in their venv. (I implemented the rejected second option in #9539.)

I think the plan was only to warn rather than to automatically set it for users, but you can do this for `spacy evaluate` by putting it in custom code that's loaded with `--code`, no hacking required, which is what I should have suggested in the first place.

**Comment by jacquesg** [comment]
Ah, I'm already using the `--code` option, is there a specific hook point, or is it fine as long as it runs as part of loading the file?

**Comment by adrianeboyd** [comment]
It should be fine as long as it's at the top level in the code somewhere.

**Comment by adrianeboyd** [comment]
It's documented here, although I can see that the details might not jump out at you when you're searching the docs: https://spacy.io/usage/embeddings-transformers#transformers-runtime

We should add a pointer to our FAQ discussion post: #8226
