### ISSUE TITLE
Possible bug about code in examples/keras_parikh_entailment/keras_decomposable_attention.py

### ISSUE THREAD

**Issue by akYoung** [explosion/spaCy#1038]
I suppose `train_X = _generate_X(20, shape[0], vectors.shape[1])` in `test_fit_model()`
 should be `train_X = _generate_X(20, shape[0], vectors.shape[0])`  since the parameter `nr_vector` should be limited to the number of words in vocab instead of the dimension of word embeddings.

## Your Environment

* Operating System: 
* Python Version Used: 
* spaCy Version Used: 
* Environment Information:

**Comment by honnibal** [comment]
I think you're right, thanks! Do you want to make a pull request, or shall I just fix it in-place?

**Comment by akYoung** [comment]
@honnibal  I tried to make a pull request. Could you please help see if I did it right? Thanks a lot!

**Comment by honnibal** [comment]
Merged, thanks!
