### ISSUE TITLE
Differences between the English and German models

### ISSUE THREAD

**Issue by vaulttech** [explosion/spaCy#1040]
Hi,

I was playing with sentences that have "and" and "und" in English and German (respectively) and I noticed that the dependency conventions used by the models of the different languages are different. I thought some comment about this could probably be added (somewhere? No idea where) to some documentation (I was going to create some documentation file and a pull request, but couldn't figure out where to put it =P). Knowing about these kinds of differences (which can actually be many!) may help a lot people trying to simply use the parses generated by spaCy (without caring much about what it is doing).

For example:

  (1) the crazy and strange and awesome mother
![issue_displacy](https://cloud.githubusercontent.com/assets/419907/25668404/dda64fd8-3026-11e7-95c4-140a1ecd90f8.png)

 (2) die schöne und nette und tolle Mutter
![issue_displacy2](https://cloud.githubusercontent.com/assets/419907/25668456/ff241c62-3026-11e7-82a4-b29713a9d4da.png)

In English, both the "and" and the word being connected by it are dependents of the preceding word. I.e., in the example, both "and" and "strange" are dependent of "crazy", and similarly both "and" and "awesome" are dependent of "strange".

In German, however, the word following "und" is dependent of "und" (and not of the word preceding "und", as it would be in English).

**Comment by ines** [comment]
Closing this and making #1057 the master issue – work in progress for spaCy v2.0!
