### ISSUE TITLE
Lemma of "hated" is "hat"

### ISSUE THREAD

**Issue by lvilnis** [explosion/spaCy#1041]
Pretty much what it says in the title. Is there an easy way to set custom rules for the lemmatizer?

## Your Environment
Using spaCy on OSX

* **Python version:** 2.7.13
* **Platform:** Darwin-16.5.0-x86_64-i386-64bit
* **spaCy version:** 1.8.2
* **Installed models:** en

**Comment by honnibal** [comment]
There's a couple of ways to solve this. You can patch the lemmatizer rules before loading the model -- this should give you the updated rule.

You can also tell the tokenizer to always analyse some whitespace-delimited chunk the same way, including with attributes. See here: https://spacy.io/docs/usage/customizing-tokenizer#special-cases

Thanks for reporting this case though. Will fix.

**Comment by lvilnis** [comment]
Thanks for the quick response!

**Comment by ines** [comment]
Merging this with #1106!
