### ISSUE TITLE
Incorrect tokenization on "May." in English md model

### ISSUE THREAD

**Issue by mapadofu** [explosion/spaCy#10428]
This is a pretty extreme edge case, but has occurred to me:

## How to reproduce the behaviour
```
In [2]: nlp = spacy.load('en_core_web_md')

In [20]: text = "John's birthday is 9 May.  He'll turn 21 then."

In [21]: doc = nlp(text)

In [22]: print(' '.join( f'[{t.text}]' for t in doc))
[John] ['s] [birthday] [is] [9] [May.] [ ] [He] ['ll] [turn] [21] [then] [.]
```

## Your Environment

Linux (Ubuntu 20.04)

## Info about spaCy

- **spaCy version:** 3.2.2
- **Platform:** Linux-5.4.0-100-generic-x86_64-with-glibc2.29
- **Python version:** 3.8.10
- **Pipelines:** en_core_web_md (3.2.0)

**Comment by adrianeboyd** [comment]
Thanks for the report, that looks it's a very old mistake in the tokenizer exceptions:

https://github.com/explosion/spaCy/blob/b2bbefd0b542fcad527b9badf97fd1c3c69a7bbf/spacy/lang/en/tokenizer_exceptions.py#L450

If you want to fix in it in an existing model, you can remove a tokenizer exception like this: https://github.com/explosion/spaCy/discussions/8218#discussioncomment-838238
