### ISSUE TITLE
Release Linux aarch64 wheels in PyPI

### ISSUE THREAD

**Issue by odidev** [explosion/spaCy#10433]
In reference to https://github.com/explosion/spaCy/issues/6533

As per the [comment](https://github.com/explosion/spaCy/issues/6533#issuecomment-742143784) team was working on adding wheel support for more platforms. However, I can see that Linux aarch64 wheels are not available in [PyPI](https://pypi.org/project/spacy/#files) yet. 

Can you please let me know if you have any plan for releasing Linux aarch64 wheel on PyPI. Please let me know if you need any help from my side. I can contribute.

**Comment by adrianeboyd** [comment]
This remains an internal infrastructure issue. We currently build wheels for pypi on microsoft-hosted azure pipelines agents and there are only x86_64 agents as far as I'm aware. We may look into self-hosted agents or other alternatives in the future, but it's not something that users can easily contribute to, sorry.

**Comment by reisub** [comment]
It looks like Azure recently got support for ARM runners in preview:
https://azure.microsoft.com/en-us/blog/now-in-preview-azure-virtual-machines-with-ampere-altra-armbased-processors/

Hopefully that enables building aarch64 wheels for spacy :)

**Comment by adrianeboyd** [comment]
We just published aarch64 wheels for the current versions of all of our packages. If you run into any problems with wheel packages, please let us know!
