### ISSUE TITLE
Memory Leak when using spacy FASTAPI

### ISSUE THREAD

**Issue by MariamRiaz** [explosion/spaCy#10497]
### Discussed in https://github.com/explosion/spaCy/discussions/10496

<div type='discussions-op-text'>

<sup>Originally posted by **MariamRiaz** March 15, 2022</sup>
Hi All, 

I am utilizing fastapi to serve two of spacy models as RESTAPI, ""en_core_web_lg" and "de_core_news_lg". We send our text data to this RESTAPI to get dependency information from the models. As we were testing our large dataset we experienced a memory leak on this process when the data reached to a million data points. (Keep in mind that the length of our text is around 30-60 token in average and not a lengthy text). Upon further investigation it seems that the process memory consumption is increasing gradually as the data points it processes increases. If you can help us in resolving this issue it would be very helpful.</div>

**Comment by polm** [comment]
You don't need to open a Discussion and an issue. I'll close this and we'll follow up in the Discussion.
