### ISSUE TITLE
`spacy-experimental` 0.3.0 is not released to PyPI

### ISSUE THREAD

**Issue by oroszgy** [explosion/spaCy#10503]
`spacy-experimental` v0.3.0 is tagged but not released to PyPI which practically prevents the usage of the new parser in spacy projects.

## How to reproduce the behaviour
`$ pip install spacy-experimental==0.3.0`

**Comment by adrianeboyd** [comment]
Hmm, it looks like we had this 90% prepared but didn't do the final release. The edit tree lemmatizer is going to move into the core library soon, but we can go ahead and do this release.

**Comment by adrianeboyd** [comment]
There was one additional performance improvement, so I just tagged and released v0.4.0 instead. Thanks for the note!

**Comment by oroszgy** [comment]
Thanks for the quick resolution!
