### ISSUE TITLE
Misleading message trying to download non-existing model

### ISSUE THREAD

**Issue by serrodcal** [explosion/spaCy#1051]
I get a misleading error executing the following script code:

```
from spacy.es import Spanish

nlp = Spanish(path=None)

doc = nlp(u'Hola esto es una prueba de la librería Spacy en Español.')
sentence = next(doc.sents)
```

After that, the error tells me to download a non-existing model, as it is shown below:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "spacy/tokens/doc.pyx", line 434, in __get__ (spacy/tokens/doc.cpp:9664)
ValueError: sentence boundary detection requires the dependency parse, which requires data to be installed. If you haven't done so, run: 
python -m spacy download es
to install the data
```

Running `python -m spacy download es` in command line the message tell me 
`es` does not existing as model:

```
$ python -m spacy download es

    Compatibility error

    No compatible model found for 'es' (spaCy v1.8.2).
```

SpaCy should have checked for available models, or simply pointed to the models documentation instead.

## My Environment

* **Python version:** 2.7.13
* **Platform:** Darwin-16.5.0-x86_64-i386-64bit
* **spaCy version:** 1.8.2
* **Installed models:**

**Comment by ines** [comment]
Thanks for the report – this will definitely be fixed in the next version! 👍

(Also, as I mentioned on [StackOverflow](http://stackoverflow.com/questions/43918886/error-downloading-spanish-model-in-spacy/43922477#comment74896955_43922477), the [language models docs](https://spacy.io/docs/api/language-models) should probably be more explicit about what "alpha support" really means, i.e. that it refers to the tokenizer and `Language` class and not to alpha models etc. I think even renaming the section to "Languages" and adding a note to the alpha section will help here. Will update this as well!)

**Comment by DeepthiKarnam** [comment]
even while downloading language models for english language I get the same error

>python -m spacy download 'en_depent_web_md'

    Compatibility error

    No compatible model found for ''en_depent_web_md'' (spaCy v1.9.0).

**Comment by colingoldberg** [comment]
Has this been fixed in spaCy 1.9.0? I just got this error:
$ python -m spacy download en_vectors_web_lg

    Compatibility error

    No compatible model found for 'en_vectors_web_lg' (spaCy v1.9.0).

Not sure where the compatibility applies - where do I look?

**Comment by ines** [comment]
@colingoldberg spaCy's `download` command fetches the compatibility table from [`spacy-models/compatibility.json`](https://github.com/explosion/spacy-models/blob/master/compatibility.json). It seems like the model you're looking for is `en_vectors_glove_md` (which was renamed to `en_vectors_web_lg` in v2.0+ for consistency).

**Comment by colingoldberg** [comment]
Thanks for your response. I have upgraded to the latest spaCy version, and with a 'python -m spacy download en' it seems to be ok.
