### ISSUE TITLE
Exclude and enable options for spacy.load do not seem to be working

### ISSUE THREAD

**Issue by koreyou** [explosion/spaCy#10515]
According to [the documentation on disabling pipeline components](https://spacy.io/usage/processing-pipelines#disabling) you should be able to (a) exclude a component from being loaded altogether with `exclude=` option, and (b) exclude all but required components with `enable=` option.
However, it seems they are not working as described in the documentation:

## How to reproduce the behaviour

```python
import spacy
nlp = spacy.load("en_core_web_sm", disable=["ner"])                
doc = nlp("Apple is looking at buying U.K. startup for $1 billion")
# works as expected 
print('disable', doc.ents)

nlp = spacy.load("en_core_web_sm", exclude=["ner"])
doc = nlp("Apple is looking at buying U.K. startup for $1 billion")
# should not print anything, but it does 
print('exclude', doc.ents)

nlp = spacy.load("en_core_web_sm", enable="tokenizer")
doc = nlp("Apple is looking at buying U.K. startup for $1 billion")
# should not print anything, but it does 
print('enable', doc.ents)
```

## Your Environment

* **spaCy version:** 2.3.2
* **Platform:** macOS-10.16-x86_64-i386-64bit
* **Python version:** 3.8.5

**Comment by polm** [comment]
The documentation you link to is for v3, the current version. v2 only supported the `disable` option, as described in the [v2 docs](https://v2.spacy.io/api/top-level#_title).

**Comment by koreyou** [comment]
Understood. It might better off be raising an error instead of silently gobbling the options.

**Comment by polm** [comment]
v2 allowed passing arbitrary keyword arguments to the underlying class, which could a user-defined class. 

In v3 extra options are treated as config options, so unsupported arguments will raise an error.

**Comment by koreyou** [comment]
Understood. Thank you for the clarification.
