### ISSUE TITLE
NORM missing in matcher pattern attributes

### ISSUE THREAD

**Issue by mr-bjerre** [explosion/spaCy#10530]
## Which page or section is this issue related to?

https://spacy.io/api/matcher#patterns

AFAIK it is possible to match on a [token `norm_` attribute](https://spacy.io/api/token#attributes). But it looks like it is missing in the [matcher API docs](https://spacy.io/api/matcher#patterns). I guess that's a mistake?

**Comment by adrianeboyd** [comment]
Thanks for the report, I think that's just an oversight in the docs.
