### ISSUE TITLE
Missing sentences after sentence splitting on german texts

### ISSUE THREAD

**Issue by marchbnr** [explosion/spaCy#1053]
When I do sentence splits on german text with the german language model, for some documents, the first sentence does not start at index 0 and for some documents no sentences are returned at all.

My code is really simple:
```
import spacy
nlp = spacy.load('de')
doc = nlp("some text")
for sent in doc.sents:
    print("first char: ", sent.start_char)
```

## Info about spaCy

* **Platform:** Linux-4.4.0-62-generic-x86_64-with-Ubuntu-16.04-xenial
* **Installed models:** de
* **Python version:** 3.5.2
* **spaCy version:** 1.8.2

**Comment by honnibal** [comment]
This really sounds like it might be a bug, but I can't currently reproduce it. If you can give an example that demonstrates this on v2, please do open a new issue. Thanks!
