### ISSUE TITLE
Start/end of matches inconsistent between PhraseMatcher and Matcher when run on Spans

### ISSUE THREAD

**Issue by p-baumann** [explosion/spaCy#10553]
When run on Spans, the the `start` and `end` values of matches returned by PhraseMatcher and Matcher are inconsistent:
- for PhraseMatcher, `start` and `end` of the match are relative to the underlying Doc
- for Matcher, `start` and `end` of the match are relative to the input Span 

The two matchers are consistent when called with `as_spans=True`.

## How to reproduce the behavior

```python
from spacy.matcher import Matcher, PhraseMatcher
import en_core_web_sm
nlp = en_core_web_sm.load()

text = 'It was a sunny day. Suddenly, a storm came up.'
phrase = 'a storm'
pattern = [
    {'TEXT': 'a'},
    {'TEXT': 'storm'}
]

doc = nlp(text)
matcher = Matcher(nlp.vocab)
pmatcher = PhraseMatcher(nlp.vocab)

matcher.add('STORM', [pattern])
pmatcher.add('STORM', [nlp(phrase)])

print('Doc: PhraseMatcher vs. Matcher')
print(pmatcher(doc, as_spans=True), pmatcher(doc))
print(matcher(doc, as_spans=True), matcher(doc))

print('\nSent span: PhraseMatcher vs. Matcher')
sent = list(doc.sents)[1]
print(pmatcher(sent, as_spans=True), pmatcher(sent))
print(matcher(sent, as_spans=True), matcher(sent))
```

This outputs
```
Doc: PhraseMatcher vs. Matcher
[a storm] [(2426368638871999092, 8, 10)]
[a storm] [(2426368638871999092, 8, 10)]

Sent span: PhraseMatcher vs. Matcher
[a storm] [(2426368638871999092, 8, 10)]
[a storm] [(2426368638871999092, 2, 4)]
```

When called on the Doc, the two matchers return the same matches.   
But when called on the second sentence as a Span, the matches of PhraseMatcher are relative to the underlying Doc, while matches of Matcher are relative to the input Span.   
When called with `as_spans=True`, all matches are consistent.

### DependencyMatcher

For completeness, the DependencyMatcher patterns with Matcher:

```python

dmatcher = DependencyMatcher(nlp.vocab)
dpattern = [
    {
        'RIGHT_ID': 'storm',
        'RIGHT_ATTRS': {'TEXT': 'storm'}
     },
    {
        'LEFT_ID': 'storm',
        'RIGHT_ID': '',
        'REL_OP': '>',
        'RIGHT_ATTRS': {'TEXT': 'a'}
    },
]
dmatcher.add('STORM', [dpattern])
print('Sent span: DependencyMatcher')
print(dmatcher(sent))
```

This outputs
```
Sent span: DependencyMatcher
[(2426368638871999092, [3, 2])]
```

## Your Environment

- **spaCy version:** 3.2.2
- **Platform:** macOS-10.14.6-x86_64-i386-64bit
- **Python version:** 3.9.9
- **Pipelines:** en_core_web_sm (3.2.0)

**Comment by polm** [comment]
Thanks for the report, that sounds like a bug! 

Out of curiosity, can you explain how you ran into this? Knowing how this came up in practice would be a helpful reference for us when working on the implementation.

**Comment by adrianeboyd** [comment]
Not sure why the linked PR didn't changed the status here. Since modifying the return offsets for spans may break people's code, we'd only want to make this change on a major version release, so we've merged the PR into a relatively new very-much-under-development branch for spacy v4.
