### ISSUE TITLE
similarity is not giving correct value

### ISSUE THREAD

**Issue by Praveena0989** [explosion/spaCy#1056]
I was trying out similarity example mentioned in the sapcy tutorial and I am not getting the values mentioned as per doc.
```
import spacy
nlp = spacy.load('en')
import numpy

apples, and_, oranges = nlp(u'apples and oranges')
print(apples.vector.shape)
print(apples.similarity(oranges))
```
This  is printing
```
(300,)
0.0
```

## Your Environment
* **spaCy version:** 1.8.2
* **Platform:** Darwin-16.0.0-x86_64-i386-64bit
* **Python version:** 3.6.0
* **Installed models:** en

**Comment by slavaGanzin** [comment]
@Praveena0989 

What I found:
- If you use en_core_web_md it will work: 
```
nlp = spacy.load('en_core_web_md')
...
print(apples.similarity(oranges)) #0.77809414836
```
- if you change your query to 'apple and orange' it will work too:
```
apples, and_, oranges = nlp(u'apple and orange')
print(apples.similarity(oranges)) #0.56189174621
```
nlp(u'oranges')[0].vector # zero matrix
nlp(u'orange')[0].vector # non-zero matrix
```

Before training Glove vectors wasn't tokenized and so "orange" and "oranges" are far from each other and has different "meanings":
```
nlp = spacy.load('en_core_web_md')
orange, and_, oranges = nlp(u'orange and oranges')
print(apples.similarity(oranges)) #0.633781034519
```

**Comment by honnibal** [comment]
Thanks @slavaGanzin . Agree that for some use-cases vectors keyed by lemma are better.

In summary:

* Model needs to be installed
* `en_core_web_sm` has fewer vectors -- 5k if I recall correctly
* Some tasks benefit from vectors trained on lemmas. We'll have more variety along these lines in future.

**Comment by Praveena0989** [comment]
Thank you, Guys. It works now after downloading  `en_core_web_md`
