### ISSUE TITLE
 ImportError: cannot import name 'get_terminal_size' from 'click.termui'

### ISSUE THREAD

**Issue by rrpelgrim** [explosion/spaCy#10599]
Importing spacy fails. From [this similar issue](https://github.com/tiangolo/typer/issues/377) it seems like it has to do with a recent upgrade to the `click` dependency.

EDIT: can confirm that downgrading to `click==8.0.0` solves the problem.

## How to reproduce the behaviour
```import spacy```

## Your Environment
* Operating System: MacOS 11.3.1
* Python Version Used: 3.9.10
* spaCy Version Used: 3.2.0
* Environment Information: conda environment
* Click version: 8.1.0

**Comment by adrianeboyd** [comment]
Please see #10564. You should be able to resolve this problem by upgrading to typer v0.4.1.
