### ISSUE TITLE
CRF for NER

### ISSUE THREAD

**Issue by pm3310** [explosion/spaCy#1059]
I'd like to ask if you support CRF for training a custom NER model?

**Comment by znat** [comment]
Have you considered using rasa.ai (based on Spacy) ?

**Comment by pm3310** [comment]
I want to train my own CRF model

**Comment by znat** [comment]
I don't think you can train your own intent and entities in Spacy and that's exactly the purpose of Rasa. It's an open source lib to train NER models and it uses a CRF extractor. it's based on spacy and its language models. https://github.com/golastmile/rasa_nlu/

**Comment by pm3310** [comment]
@znat Nice! Thanks a lot :-) You made my day!

**Comment by honnibal** [comment]
You can train spaCy's NER model, which isn't exactly a CRF. The API has been a bit unstable in the 1.x branch. This will be resolved soon once the neural network model is complete.

If you want to write your own model, you can set it into the spaCy pipeline as follows: `nlp.pipeline.append(entity_recognizer)`. Your function needs to be a callable that takes a `doc` object as its argument, and sets the entities in-place. You can set the entities by writing to `doc.ents` -- you'll need a sequence of `(start, end, label)` tuples.
