### ISSUE TITLE
spaCy does not parse the entity recognition sample text

### ISSUE THREAD

**Issue by androm3da** [explosion/spaCy#1060]
I've installed spaCy but the Entity Recognition tutorial seems to fail to parse.  AFAICT I downloaded and ran the steps per the instructions.  I've not yet tried parsing anything, this is pretty much my first foray into spacy.

```
$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
nlp = spacy.load('en')
>>> nlp = spacy.load('en')
doc = nlp.make_doc(u'London is a big city in the United Kingdom.')
>>> doc = nlp.make_doc(u'London is a big city in the United Kingdom.')
>>> doc.is_parsed
False
>>> doc.is_tagged
False
```

## Info about spaCy

* **Python version:** 2.7.6
* **Platform:** Linux-3.13.0-106-generic-x86_64-with-Ubuntu-14.04-trusty
* **spaCy version:** 1.8.2
* **Installed models:** en

**Comment by androm3da** [comment]
Note that the real failure that I encounter is when I try to get the entities or noun_chunks later.

**Comment by androm3da** [comment]
Same failures occurred w/`1.8.0` and `1.7`.  I must have missed an installation step or this is something unique to my environment.

**Comment by androm3da** [comment]
Also worth noting that all of the tests passed for `1.7`.

> cd /local/mnt/workspace/brow/brow_env/local/lib/python2.7/site-packages/spacy
> $ python -m pytest $PWD --vectors --models --slow
> ...
> 2903 passed, 27 xfailed in 832.96 seconds

**Comment by slavaGanzin** [comment]
```python3
doc = nlp.make_doc(u'London is a big city in the United Kingdom.')
doc.is_parsed
False
doc = nlp(u'London is a big city in the United Kingdom.')
doc.is_parsed #True
```

**Comment by androm3da** [comment]
Ugh, thanks for the sanity check.  I obviously did not follow the documentation directly and conflated two different examples.

**Comment by slavaGanzin** [comment]
You're welcome
