### ISSUE TITLE
Wrong outputs from ru_core_news_sm model with hyphened words

### ISSUE THREAD

**Issue by riZZZhik** [explosion/spaCy#10618]
## Bug
Why the word 'любому' in second test lemmatized as 'любой' - what is correct, but in first as 'любому'?

## How to reproduce the behaviour
Initialization:
```python
import spacy
nlp = spacy.load('ru_core_news_sm')
```

Test 1:
```python
print([(x.lemma, x.lemma_) for x in nlp('по-любому')]
```
Output: `[(12047934663327436226, 'по'), (9153284864653046197, '-'), (1520167342668405783, 'любому')]`

Test 2:
```python
print([(x.lemma, x.lemma_) for x in nlp('любому')]
```
Output: `[(11783268970549905777, 'любой')]`

## Your Environment
Using docker
- **spaCy version:** 3.2.4
- **Platform:** Linux-5.10.104-linuxkit-x86_64-with-glibc2.31
- **Python version:** 3.10.4
- **Pipelines:** ru_core_news_sm (3.2.0)

**Comment by adrianeboyd** [comment]
Please do not open duplicate issues or discussion threads.

Link to original discussion: https://github.com/explosion/spaCy/discussions/10605

**Comment by riZZZhik** [comment]
> Please do not open duplicate issues or discussion threads.
> 
> Link to original discussion: #10605

I tried to move thread from discussion to issue
