### ISSUE TITLE
Exception is raised when using Japanese tokenizer with multithreading

### ISSUE THREAD

**Issue by WinField95** [explosion/spaCy#10649]
spaCy looks like support multithreading (https://github.com/explosion/spaCy/issues/172) but, exception is raised when using Japanese tokenizer with multithreading. Is the following usage something wrong? Or is this a bug?

JapaneseTokenizer uses Sudachi and tokenizer of Sudachi is not thread safe. (https://github.com/WorksApplications/Sudachi/issues/38)

## How to reproduce the behaviour

Example

```
import spacy
import threading


def run(name, nlp):
    while True:
        print(f'{name} : start')
        nlp("吾輩は猫である")
        print(f'{name} : end')


nlp = spacy.Language = spacy.load('ja_ginza')
t1 = threading.Thread(target=run, args=("t1", nlp))
t2 = threading.Thread(target=run, args=("t2", nlp))
t1.start()
t2.start()
```

Running and wait some time, execution is crushed.

```
t1 : end
t1 : start
t2 : end
t2 : start
t2 : end
t2 : start
t1 : end
t1 : start
IndexError: list index out of range
Exception ignored in: 'sudachipy.lattice.Lattice.connect_node'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/spacy/lang/ja/__init__.py", line 47, in __call__
    sudachipy_tokens = self.tokenizer.tokenize(text)
IndexError: list index out of range
zsh: bus error  python3 script.py
```

## Your Environment

* Operating System: macOS 11.6
* Python Version Used: 3.9.7
* spaCy Version Used: 3.1.2

**Comment by polm** [comment]
Sorry you're having trouble with this. 

First, I cannot reproduce the issue - your example code ran for several minutes without issue for me. Did you have to run it longer before it crashed? Please clarify what version of the relevant packages you are using, at a minimum ginza, ja_ginza, and sudachipy. 

Note that we are not the developers of Ginza - while based on spaCy, it's a separate project, and tokenizer details may be different from our built-in Japanese support. In general you should report issues with Ginza there unless it's clear they're general spaCy issues.

https://github.com/megagonlabs/ginza

Also note that the issue you linked to is for the original Sudachi, which is in Java and never used in spaCy or Ginza. While the design is basically the same in the ported versions, detailed issues like that are not directly relevant to SudachiPy. 

Your error looks like it's coming from the Python/Cython SudachiPy, which was replaced by a Rust implementation last year. I'm not sure but maybe the Rust version resolved any multithreading issues, you might want to try upgrading.

Also, the thread about multithreading you linked is six years old, and from two major versions ago. While I think multithreading still works, for parallelism it may be better to use our built-in [multiprocessing support](https://spacy.io/usage/processing-pipelines#multiprocessing).

**Comment by WinField95** [comment]
I apologize for the inconvenience.
And, thank you some advices.

Environment below is my machine, but this is poor reproducibility.

```
sudachipy 0.5.2

============================== Info about spaCy ==============================

spaCy version    3.1.2                         
Location         /usr/local/lib/python3.9/site-packages/spacy
Platform         macOS-11.6-x86_64-i386-64bit  
Python version   3.9.7                         
Pipelines        en_core_web_sm (3.1.0), ja_ginza (5.0.0), ja_ginza_electra (5.0.0)
```

I prepared another docker based example.
I checked execution in two different machines so, I think this is reproducible.
The crash occurred within 60 seconds in my machines.

Platform : macOS-11.6-x86_64-i386-64bit, Docker Desktop

Docker Desktop Preferences
```
CPUs: 6
Memory: 8.00GB
Swap: 2GB
```

Dockerfile
```
FROM python:3.9
RUN pip3 install spacy==3.1.2
RUN pip3 install ja-ginza==5.0.0
COPY script.py .
CMD ["python3", "script.py"]
```

script.py
```
import spacy
import threading


def run(name, nlp):
    while True:
        print(f'{name} : start')
        nlp("吾輩は猫である")
        print(f'{name} : end')


nlp = spacy.Language = spacy.load('ja_ginza')
t1 = threading.Thread(target=run, args=("t1", nlp))
t2 = threading.Thread(target=run, args=("t2", nlp))
t1.start()
t2.start()
```

Command
```
docker build -t reproduction .
docker run -it reproduction
```

Execution
Thread-1 is crushed in this execution.
```
t1 : start
t2 : end
t2 : start
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "//script.py", line 8, in run
    nlp("吾輩は猫である")
  File "/usr/local/lib/python3.9/site-packages/spacy/language.py", line 988, in __call__
    doc = self.make_doc(text)
  File "/usr/local/lib/python3.9/site-packages/spacy/language.py", line 1070, in make_doc
    return self.tokenizer(text)
  File "/usr/local/lib/python3.9/site-packages/spacy/lang/ja/__init__.py", line 49, in __call__
    dtokens, spaces = get_dtokens_and_spaces(dtokens, text)
  File "/usr/local/lib/python3.9/site-packages/spacy/lang/ja/__init__.py", line 247, in get_dtokens_and_spaces
    raise ValueError(Errors.E194.format(text=text, words=words))
ValueError: [E194] Unable to aligned mismatched text '吾輩は猫である' and words '[]'.
t2 : end
t2 : start
t2 : end
t2 : start
t2 : end
t2 : start
t2 : end
```

Environment below is docker based example.

```
sudachipy 0.5.4
============================== Info about spaCy ==============================

spaCy version    3.1.2                         
Location         /usr/local/lib/python3.9/site-packages/spacy
Platform         Linux-5.10.47-linuxkit-x86_64-with-glibc2.31
Python version   3.9.12                        
Pipelines        ja_ginza (5.0.0)

sudachipy --version
```


> In general you should report issues with Ginza there unless it's clear they're general spaCy issues.

OK.
I don't know this crush is spaCy problem or other library yet.
If I find out, I will report this issue there.

**Comment by polm** [comment]
Thanks for the extra information. 

To clarify, does the error go away if you upgrade SudachiPy to the latest version? The version of Ginza you are using is also slightly old - Ginza was updated to use the Rust SudachiPy in December.

**Comment by WinField95** [comment]
I used ja_ginza (5.1.0) and tried again.
I confirmed execution was stable for 30 minutes and error was not occurred.
Thank you some advices. I'll use this version.


Environment
```
sudachipy 0.6.3

============================== Info about spaCy ==============================

spaCy version    3.2.4                         
Location         /usr/local/lib/python3.9/site-packages/spacy
Platform         Linux-5.10.47-linuxkit-x86_64-with-glibc2.31
Python version   3.9.12                        
Pipelines        ja_ginza (5.1.0)
```

I checked sudachipy 0.6.3 is latest and implemented by Rust.
https://github.com/WorksApplications/SudachiPy
https://github.com/WorksApplications/sudachi.rs

**Comment by WinField95** [comment]
I close this issue. Thank you.

**Comment by polm** [comment]
Glad that solved your issue! Let us know if you have any other trouble.
