### ISSUE TITLE
spacy-1.8.2: add pip as a required dependency

### ISSUE THREAD

**Issue by sdll** [explosion/spaCy#1064]
In [NixOS](https://nixos.org/), all the dependencies are listed in the recipe for a package, similar to PyPi `requirements.txt`, after which the building schemes for the dependencies are looked up in the corresponding nix recipes. If another package is needed to make the installed package work, then this fact is explicitly stated in the recipy.

Judging from the current **spaCy** `setup.py`, it is not evident that `pip` is required for the correct functioning of the module. In particular, `download` would not work without it.

Could you please identify somewhere that `pip` is a required dependency?

## Your Environment

* **Operating System**: https://github.com/NixOS/nixpkgs/pull/25791
* **spaCy version:** 1.8.2
* **Python version:** 3.5.3
* **Installed models:** 
* **Platform:** Linux-4.9.27-x86_64-with-glibc2.3.4

**Comment by ines** [comment]
Ah, damn, I guess we didn't think about this problem. Will add `pip` to the requirements.txt and setup.py!
