### ISSUE TITLE
Tokenizer special rules and phrase matcher

### ISSUE THREAD

**Issue by rafelafrance** [explosion/spaCy#10666]
## Info about spaCy

- **spaCy version:** 3.2.4
- **Platform:** Linux-5.16.15-76051615-generic-x86_64-with-glibc2.34
- **Python version:** 3.9.7
- **Pipelines:** en_core_web_md (3.2.0), en_core_web_sm (3.2.0)

Should tokens generated by the tokenizer's special rules behave just like any other token when matching. This does not seem to be the case.

### Actual behavior

```python
import spacy
from spacy.matcher import PhraseMatcher

nlp = spacy.load("en_core_web_sm")

special = [r for r in nlp.tokenizer.rules if r == 'Ark.']
print(special)
```
` ['Ark.']`

```python
doc = nlp(' ark. Ark. ARK. ')

matcher1 = PhraseMatcher(nlp.vocab, attr='LOWER')
patterns = [nlp.make_doc(t) for t in ['ark.']]
matcher1.add('test', patterns)

for _, start, end in matcher1(doc):
    print(doc[start:end])
```
 `ark.`
 `ARK.`

```python
matcher2 = PhraseMatcher(nlp.vocab, attr='ORTH')
patterns = [nlp.make_doc(t) for t in ['Ark.']]
matcher2.add('test', patterns)

for _, start, end in matcher2(doc):
    print(doc[start:end])
```
 `Ark.`

### Expected:
matcher1 output
`ark.`
`Ark.`
`ARK.`

matcher2 is correct.

### Workarounds:
- remove the blocking rule from the tokenizer
- add an "orth" matcher rule to the phrase matcher

**Comment by adrianeboyd** [comment]
The phrase matcher patterns are stored with the exact tokenization provided when the pattern was added, so if you do any retokenization it will definitely interact with how the patterns match. If you're doing a ton of retokenization at various points, the phrase matcher might not be the best tool here.

**Comment by rafelafrance** [comment]
Not that it matters, but I retokenize rarely and completely unrelated to this conversation, I merge spans a lot all over the place.

This has been most helpful. Thank you again.
