### ISSUE TITLE
SpanGroup()s of a SpanGroups() are lost upon de/serialization--if having the same .name

### ISSUE THREAD

**Issue by single-fingal** [explosion/spaCy#10685]
## Problem:

If a `SpanGroup.name` conflicts with another SpanGroup.name in a `SpanGroups` object--but the `SpanGroup`s are values of different keys of the SpanGroups object--then when the SpanGroups object is serialized and then deserialized, only 1 of the `SpanGroup`s will be present in the `SpanGroups` object.

This occurs when e.g. serializing/deserializing `Doc`s via `DocBin`--whether using DocBin's `get_docs()` or `to_bytes()`/`from_bytes()`.

A Doc's `SpanGroups` might be in such a state when (at least):
* a user creates a `SpanGroup` object and sets the `.name` attribute to the name of another SpanGroup within the Doc's `SpanGroups`; or
* a user changes an existing `SpanGroup`'s `.name` to the name of another SpanGroup within the Doc's `SpanGroups`.

### How to reproduce the behaviour:

(Executed with:)
* **spaCy version:** 3.2.4
* **Platform:** Linux-5.17.3-x86_64-with-glibc2.35
* **Python version:** 3.10.4

For example:

```python
import spacy
from spacy.tokens import SpanGroup, DocBin
nlp = spacy.blank("en")

doc = nlp("Will it blend?")
doc.spans['test'] = [doc[0:1]]
... # perhaps at some other point in code:
spangroup = SpanGroup(doc, name='test', spans=[doc[1:2]])
doc.spans['test2'] = spangroup

# Now choose your own adventure:
# ***A:
>>> doc.spans
{'test': [Will], 'test2': [it]}
>>> doc.spans.from_bytes(doc.spans.to_bytes())
{'test': [it]}

# ***B:
# (`doc.spans` is defined as it was prior to adventure "A":)
>>> db = DocBin(docs=[doc])
>>> redocs = list(db.get_docs(nlp.vocab))
>>> redocs[0].spans
{'test': [it]}

# and consequently:
>>> redb = db.from_bytes(db.to_bytes())
>>> redoc = list(redb.get_docs(nlp.vocab))[0]
>>> redoc.spans
{'test': [it]}

# which similarly occurs for `DocBin`'s `to_disk` and `from_disk`.
```

And it's also problematic if e.g. (as a special case):
```python
doc.spans['bad']  = SpanGroup(doc, spans=[doc[0:1]])
doc.spans['user'] = SpanGroup(doc, spans=[doc[1:2]])
```
since `SpanGroup`s without a given 'name' all default to the name "", and if/when they're set as values in a Doc's `SpanGroups`, only 1 will be loaded/set upon deserialization.

While I wouldn't expect most users to write code exactly like the simple/direct examples above, they do have the power to create "naked" `SpanGroup` objects (i.e. via `SpanGroup()`--outside of a `doc.spans`) and use/modify/assign them (to a `doc.spans`) as desired.

## Cause:

`SpanGroups.to_bytes` serializes its `SpanGroup`s as a list, and doesn't include their corresponding keys (in the `SpanGroups` container). When deserializing a `SpanGroups` object, each `SpanGroup` in the list is assigned as the value of the key corresponding to its `.name`. When multiple `SpanGroup`s have the same `.name`, only the last `SpanGroup` with that `.name` will be present in the `SpanGroups` object.

`DocBin.add()` serializes `SpanGroups` using their `.to_bytes()`, so de/serialization of `Doc`s this way inherits this behavior.

## Solution:

Checks are already in place for ensuring agreement between a `SpanGroup`'s `Doc` and a `SpanGroups`' `Doc`.
To prevent the above issues, we may want to at least have:
1. (both of the following:)
    1. `SpanGroups` ensure that no added `SpanGroup` has the same name as another SpanGroup in the SpanGroups object. This could be done by e.g.:
        1. iterate over the `SpanGroup`s, or cache their names (probably: neither of which you want to do); or:
        2. require that a `SpanGroup.name` matches the key it is the value of in `SpanGroups`; in other words, maintaining the invariant:
            ```python
            for name, span_group in doc.spans.items():
                assert span_group.name == name
            ```
    2. `SpanGroup`s prevent changing their `.name` (e.g. via attribute assignment)--*if the `SpanGroup` object is a value of its `Doc`'s `SpanGroups` object* (which `SpanGroup`s currently don't have to be)--:
        1. to a name of another SpanGroup in its same `SpanGroups` object; or:
        2. (if we required bullet "1.i.b" (noted above):) to any name other than the key it is the value of in its `Doc`'s `.spans`.
2. (or:) Change how `SpanGroups` are serialized/deserialized:
    * Include the key names.
    * though this will still allow multiple SpanGroup()s within a `SpanGroups` to have the same `.name`. (This may not be a problem, but I haven't done an exhaustive search of the codebase to see how `SpanGroup.name`s are used--other than for de/serialization.)

Those are the two general approaches that came to mind to address this, but let me know what you think.
I'm leaning towards option 2, because it's both simpler and I think more in line with how you're treating `SpanGroup`s currently. I don't think I'd have a problem implementing that solution, if you want to go forward with it or something like it.

**Comment by adrianeboyd** [comment]
Thanks for the report, that does look like a bug. We'll look into it!
