### ISSUE TITLE
Using spaCy for voice assistant commands

### ISSUE THREAD

**Issue by YaCnDehfuli** [explosion/spaCy#10697]
### Discussed in https://github.com/explosion/spaCy/discussions/10690

<div type='discussions-op-text'>

<sup>Originally posted by **YaCnDehfuli** April 22, 2022</sup>
I am using spaCy with VOSK for a smart home voice assistant project. So I get some compound commands like "Turn on the bedroom lights at noon and play some pop music now". I want to extract some basic elements of the sentence to come up with a clear command for the hardware part of the system. (like "what to do", "Where", "When", and "what are the objects to do the verbs on"). 

I am familiar with token.dep and token.pos for identifying verbs and objects but in a compound sentence there are two "pobj"s and I don't know how to identify each "pobj" verb. for example in the sentence above, "lights" and "music" both have the token.dep of "pobj" and this makes it hard to distinguish their verbs which are "turn on" and "play" respectively. 

Furthermore, spaCy identifies "at noon" as an adverb (which it is) and this can be misjudged with words like "quickly" which are also adverbs. Also, it has some problems with identifying phrasal verbs. It does not identify "Turn on" as a verb, But it identifies "Turn" as a verb. So what do you think that I can do to get meaningful commands from these sentences.
[test.txt](https://github.com/explosion/spaCy/files/8540230/test.txt)
</div>

**Comment by adrianeboyd** [comment]
This is a usage question and not a bug, so the discussion board was the right place to post this. Please don't open duplicate issues or threads.
