### ISSUE TITLE
Tokenization issue: theses

### ISSUE THREAD

**Issue by dsenkyr** [explosion/spaCy#10699]
## How to reproduce the behaviour
```
doc = nlp("Teachers supervise theses.")
tokens = list(doc)        
```

Current tokens: `Teachers`, `supervise`, `these`, `s.`
Expected tokens: `Teachers`, `supervise`, `theses`, `.`

## Your Environment
- **spaCy version:** 3.2.4
- **Platform:** Windows-10-10.0.19044-SP0
- **Python version:** 3.9.12
- **Pipelines:** en_core_web_trf (3.2.0)

**Comment by adrianeboyd** [comment]
Thanks for the report! That looks like a mistake in the English tokenizer defaults, which try to support both `'s` and `s` in lots of cases like `where's` and the less forma `wheres`, and this got extended to `these` and `those` by mistake.

You can remove an exception like this:

```python
nlp.tokenizer.rules = {key: value for key, value in nlp.tokenizer.rules.items() if key != "theses"}
```
