### ISSUE TITLE
doc.text doesn't match the original provided

### ISSUE THREAD

**Issue by sadovnychyi** [explosion/spaCy#1071]
```python
import spacy
nlp = spacy.load('en_core_web_sm')
text = 'whereve'
print(nlp('whereve').text)
assert nlp('whereve').text == text
```
```
where've
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError
```

Seems to be a bug, since I'm expecting the documents to match exactly to retrieve the metadata for each of them after they are parsed.
Happens with both en_core_web_sm@1.2.0 and en_core_web_md@1.2.1.

## Info about spaCy

* **spaCy version:** 1.8.2
* **Platform:** Darwin-16.6.0-x86_64-i386-64bit
* **Python version:** 3.6.1
* **Installed models:** en_core_web_md, en_core_web_sm, en_depent_web_md

**Comment by honnibal** [comment]
Thanks!

This will be a problem somewhere in the `TOKENIZER_EXCEPTIONS`. You can patch this at run-time to workaround the issue until we get it fixed in the next release.

**Comment by ines** [comment]
Thanks – this was indeed a typo, damn. Just fixed it!
