### ISSUE TITLE
Vector representation of train data for neural network(RNN, LSTM) training

### ISSUE THREAD

**Issue by irfan-zoefit** [explosion/spaCy#1072]
My first question is how to convert the train data into vectors to train the neural network i.e. LSTM for NER in Tensorflow or Keras? I did not find anything related to it on the internet yet.

My Second question is how to save the trained model of LSTM so that it can be used in Spacy? As I think the model structure will be different from Spacy model.

**Comment by ericzhao28** [comment]
[https://github.com/explosion/spaCy/tree/master/examples/keras_parikh_entailment](url) might be a helpful example. Tl;dr you can use Keras' embedding layer to create a static embedding layer which you can use to preprocess text inputs into a sequence of word embeddings (see the link for the code). See the spacy_hook.py for an example of how to integrate a keras model into spacy itself.

**Comment by irfan-zoefit** [comment]
I already have read this example. It only uses the vocabulary and word lex for similarity. This can't be used in LSTM.

**Comment by ericzhao28** [comment]
The model itself contains LSTM/RNN layers for GRU encoding.

**Comment by irfan-zoefit** [comment]
Two things here,

- Data representation is different of [snli](https://nlp.stanford.edu/projects/snli/) from what I have commented above.
- 2nd is the problem is not similar to what the example is all about. 

train data uses this labeling scheme for similarity and then converts this to binary.

```python
LABELS = {'entailment': 0, 'contradiction': 1, 'neutral': 2}
```
The conversion of the script to NER is much difficult.
