### ISSUE TITLE
Transformer model fails to recognize simple dates.

### ISSUE THREAD

**Issue by IavTavares** [explosion/spaCy#10733]
### Discussed in https://github.com/explosion/spaCy/discussions/10730

<div type='discussions-op-text'>

<sup>Originally posted by **IavTavares** April 29, 2022</sup>
```
import spacy
nlp = spacy.load("en_core_web_trf")
string = 'POLICY DETAILS Penod of Cover Your Policy gives you 18/11/21 (Noor) 18/11/22 Comprehensive Sections AB,C,'
doc = nlp(string)
[ent for ent in doc.ents if ent.label_ == "DATE"]
```

Running the code above will result an empty list, at least on my pc.
Why is that? I have a hard time believing that the transformer model cannot recognize dates in the this simple string...</div>

**Comment by polm** [comment]
Closing for the same reason as #10731 - this is a duplicate.

If you open two things, and we close one, the intent is that discussion continues in the one we did not close. Please do not open further duplicates. If you are not sure where to post, please post in one place and we will sort it out for you.
