### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'text'

### ISSUE THREAD

**Issue by gp406** [explosion/spaCy#10756]
we started getting below error starting from 04/23 when we are Annotating the documents using below. 
The below worked prior to 04/23 and any help is appreciated.

**annotated_docs = tagger.annotate(documents)**

Error Message:

TypeError                                 Traceback (most recent call last)
<command-1910247067386461> in <module>
     25 
     26 # Annotate your documents
---> 27 annotated_docs = tagger.annotate(documents)
     28 
     29 # Mask all the annotated documents and add them to a Spark DataFrame

/databricks/python/lib/python3.8/site-packages/deidentify/taggers/flair_tagger.py in annotate(self, documents)
     23 
     24     def annotate(self, documents: List[Document]) -> List[Document]:
---> 25         flair_sents, parsed_docs = flair_utils.standoff_to_flair_sents(
     26             docs=documents,
     27             tokenizer=self.tokenizer,

/databricks/python/lib/python3.8/site-packages/deidentify/methods/bilstmcrf/flair_utils.py in standoff_to_flair_sents(docs, tokenizer, verbose)
     59     flair_sents = []
     60     for sent in sents:
---> 61         flair_sent = Sentence()
     62         for token in sent:
     63             if token.text.isspace():

TypeError: __init__() missing 1 required positional argument: 'text'

**Comment by adrianeboyd** [comment]
Hi, from the traceback this doesn't look like a problem with `spacy`, but with `deidentify`. See: https://github.com/nedap/deidentify/issues/64
