### ISSUE TITLE
Where are the new word vectors from?

### ISSUE THREAD

**Issue by fractalego** [explosion/spaCy#1075]
I was training a proprietary NER using the Glove word vectors in Spacy 1.3.0 (I started the project last December and kept the same version of Spacy). I updated to the new version and noticed some decay in the F1 score (recall is much lower). Where are the new vectors from? 

This is not technically a bug, I am just curious about explaining the decay in recall.

**Comment by honnibal** [comment]
Are you using the `en_core_web_sm` (default) model? The default model simply takes the GloVe vectors and clips to the most common 5000 words --- to make the download small and simple (50mb).

You can get the full vectors by doing:

 ```
python -m spacy download en_core_web_md
python -m spacy link en_core_web_md en
```

The `md` model's vectors should be exactly the same as the ones you were using before. Incidentally, these are also vocabulary-capped -- to 1 million entries. Some applications can benefit from using the full vectors (which are a few gb in size).

**Comment by fractalego** [comment]
Thank you for your quick reply! Yes, I am using the default model and your explanation makes perfect sense. I'll re-train the model and check the new score.
