### ISSUE TITLE
Overriding `name` argument of Pipe via config has inconsistent behavior once model is serialized and loaded back.

### ISSUE THREAD

**Issue by narayanacharya6** [explosion/spaCy#10766]
The `name` parameter of a `Pipe` is different once model is serialized to disk and loaded back if overridden via the config. While it is useless in most use case to specify a name for a pipe and then override it via the config as well but I believe the name should remain the same when a model is built and when it is loaded from disk using the config. 

(This is a weird one and probably not something that deserves attention but raising an issue in any case)

## How to reproduce the behaviour
```
import spacy
from spacy.language import Language
@Language.factory("example.Factory.v1")
class ExampleFactory:
    def __init__(self, nlp, name):
        self.nlp =  nlp
        self.name = name
        
    def __call__(self, doc):
        print(self.name)
        return doc
    
nlp = spacy.blank("en")
pipe = nlp.add_pipe("example.Factory.v1", name="arg_name", config={"name": "config_arg_name"})
content = "This is an example sentence!"
doc = nlp(content) # <-- Prints config_arg_name
nlp.to_disk("/tmp/example_model/")
loaded_nlp = spacy.load("/tmp/example_model/")
loaded_doc = loaded_nlp(content) # <-- Prints arg_name, I would expect it to be same as config_arg_name
```

## Info about spaCy

- **spaCy version:** 3.0.6
- **Platform:** macOS-10.16-x86_64-i386-64bit
- **Python version:** 3.8.8
- **Pipelines:** en_core_web_lg (3.0.0), en_ud_model_trf (2.0.0), en_ud_model_lg (2.0.0), en_ud_model_sm (2.0.0), en_ud_model_md (2.0.0), en_core_web_md (3.0.0), en_core_web_sm (3.0.0), en_core_web_trf (3.0.0)

**Comment by rmitsch** [comment]
Thanks for reporting this, @narayanacharya6! Looks like a bug indeed (also in the current v3.3). We'll look into it.
