### ISSUE TITLE
Russian Tokenizer not splitting off suffixes like dots from tokens after combining accent marks

### ISSUE THREAD

**Issue by Vuizur** [explosion/spaCy#10776]
## How to reproduce the behaviour

The problem occurs with this example code:

```
import spacy
nlp = spacy.load("ru_core_news_sm")
text1 = " рекоменду́я подда́ть жару́. Самого́ Баргамота"
text2 = " рекоменду́я подда́ть жа́ру. Самого́ Баргамо́та"

tok_exp = ts._nlp.tokenizer.explain(text2)
for t in tok_exp:
    print(t[1], "\t", t[0])
```
When you take the first text, which contains the word жару́, you get this output:
```
рекоменду́я      TOKEN
подда́ть         TOKEN
жару́.   TOKEN
Самого́          TOKEN
Баргамота        TOKEN
```
However, if you take the second text, which instead uses the word жа́ру, you get the (better) output:
```
рекоменду́я      TOKEN
подда́ть         TOKEN
жа́ру    TOKEN
.        SUFFIX
Самого́          TOKEN
Баргамо́та       TOKEN
```
Here the dot is split off properly. The reason why it does not work in the first text is the acute accent, `'\u0301'`, which follows directly after the у of the жару. However, a more desirable behaviour would be to consider it as a "fixed" part of the word, so that the tokenization in text 1 is the same as in text 2, because acute accents do not affect the meaning in any way. Affected is not only the dot, but also characters like the minus (I think). 

For other languages it would be possible to perform a unicode normalization to merge everything into "one letter", however for cyrillic no precomposed characters with acute accents exist unfortunately. (Probably because they are only used in texts for children, learners, or to disambiguate two words in books for natives.)

## Your Environment

* Operating System: Windows
* Python Version Used: 3.1.9
* spaCy Version Used: 3.3.0

**Comment by polm** [comment]
Thanks for reporting this, that does look weird! We'll take a look at fixing it.
