### ISSUE TITLE
Wrong pos tag from Spanish es_dep_news_trf model (```VERB``` and ```AUX```)

### ISSUE THREAD

**Issue by JuanFF** [explosion/spaCy#10785]
Hello,

The verb _saber_ (to know) in Spanish should be tagged as `VERB` and not `AUX`. In the same context, however, _preguntar_ (to ask) is correctly tagged as `VERB`. 

I'm using the dependency parser of the `es_dep_news_trf` pre-trained model. I wonder if I can manually fix the token's pos tag and process the text again with the same model. Similarly, is it possible to fix dependency tags (`.dep_`) without training anything?

Thanks!

## How to reproduce the behaviour
```
nlp = spacy.load("es_dep_news_trf")
doc = nlp("quería saber cuándo caduca en las condiciones del seguro")
doc[1].pos_ --> AUX
doc = nlp("quería preguntar cuándo caduca en las condiciones del seguro")
doc[1].pos_ --> VERB

```
## Your Environment
* Operating System: Mac OS
* Python Version Used: 3.6.8
* spaCy Version Used: 3.2.0

**Comment by polm** [comment]
Thanks for the report, but please note that issues of this kind belong in #3052. Also see the notes there about when we can and can't address this kind of issue.
