### ISSUE TITLE
ARM + Apple GPU documentation issues

### ISSUE THREAD

**Issue by hotzjacobb** [explosion/spaCy#10783]
Hi,

I was unsure whether to open this as an issue or open a discussion so feel free to close this if a discussion would be a better fit, thanks. I eventually was able to get spaCy to utilize the GPU on a MacBook Pro M1 Pro 2021, but spent some effort figuring this out.

TL;DR: An experienced user may be able to draw conclusions and surpass these, but I personally think more forgiving, detailed documentation would be beneficial. Some opinions here. The documentation style is really nice in general!

### **spaCy usage page gives CUDA installation as pip command:**
A user might recognize that CUDA is inappropriate for an on-chip Apple GPU, but if they don't and they select "GPU" with "ARM/M1" then I think that they will face an unending installation as the Cuda and Apple options are irreconciliable and the command will try to compile the latest version, fail, move to the one before, fail, etc. in my experience. Having the combo "osX + ARM/M1 + GPU" prevent the CUDA suggestion from showing up and instead displaying `pip install -U 'spacy[apple]'` could save less experienced users here.
https://spacy.io/usage (in the initial Install spaCy CLI pane at the top of the page)

### **No binary option must be used with pip if spaCy has been previously downloaded without Xcode and CLI tools previously installed** 
(clearing cache was not sufficient for me, which surprised me). This could be noted on the usage page and would help less experienced users who might not understand why they still cannot take advantage of the GPU after reinstalling spaCy after getting Xcode + CLI tools.
https://spacy.io/usage (in the "How to install compilers and related build tools:" section I think putting this in the macOS / OS X would be good)

### **spacy.require_gpu() and spacy.prefer_gpu() did not work for me with Apple GPU's**: 
I could only tell that the GPU was being utilized because of logging performance. I appreciate that this might be non-trivial effort, but I think certainly prefer_gpu() would be nice and—unfamiliar with the internals here—but maybe can be implemented with a check to see if thinc-apple-ops exists? Alternatively, noting that it doesn't work here [here](https://spacy.io/usage#gpu) would be good.

### **Note about Conda**: 
Having a note helping less experienced users realize that `conda install` will not compile source code and thus cannot take advantage of Apple GPU's would be helpful I think. https://spacy.io/usage (in the "How to install compilers and related build tools:" section I think putting this in the macOS / OS X would be good)

Thank you (:

**Comment by adrianeboyd** [comment]
Thanks for the report! I didn't realize that the backoff/failure here was so confusing for the invalid extras.

This does what I expect (immediate failure):

```shell
pip install cupy-cuda113
```

But this does not:

```shell
pip install spacy[cuda113]
```

For now the linked PR removes the CUDA extras for non-linux ARM and clarifies CUDA in the GPU install section.

**Comment by danieldk** [comment]
> I eventually was able to get spaCy to utilize the GPU on a MacBook Pro M1 Pro 2021, but spent some effort figuring this out.

Just an additional note: spaCy cannot currently use the GPU on M1 Macs. `thinc-apple-ops` uses the AMX matrix co-processor through Apple's Accelerate, but not the GPU. We might support M1 GPUs for the transformers in the future, since PyTorch has recently added support for Metal Performance Shaders.
