### ISSUE TITLE
ValueError: [E949] Unable to align tokens for the predicted and reference docs. But they look 100% equal

### ISSUE THREAD

**Issue by mr-bjerre** [explosion/spaCy#10822]
I have a project where I need to train a `textcat_multilabel` model on HTML. So it's a standard model except for a custom tokenizer in place. I've written about it in this [thread](https://github.com/pmbaumgartner/spacy-html-tokenizer/issues/2). I've made a small repo that mimicks what I'm doing in my repo where I actually see the issue (unfortunately I can't share that). It can be seen [here](https://github.com/mr-bjerre/spacy-custom-tokenizer-issue) (note the trick of `apply_before_init` in `convert.py` - not sure if this is best practice but I couldn't find any documentation other than [this](https://spacy.io/usage/training#custom-tokenizer) which doesn't talk about the convert step).

The training in my shared repo runs fine but not in my actual repo where I get the following error

> ValueError: [E949] Unable to align tokens for the predicted and reference docs. It is only possible to align the docs when both texts are the same except for whitespace and capitalization. The predicted tokens start with: ['Production', 'update', 'September', '2015', 'Tethys', "'", 'share', 'of', 'the', 'production']. The reference tokens start with: ['Production', 'update', 'September', '2015', 'Tethys', "'", 'share', 'of', 'the', 'production']

That looks like a bug to me since the tokens are exactly the same?

## Your Environment

- **spaCy version:** 3.3.0
- **Platform:** macOS-12.3.1-arm64-arm-64bit
- **Python version:** 3.9.9

**Comment by mr-bjerre** [comment]
Currently my only workaround is to apply the before init (changing the HTML tokenizer) before `nlp.make_doc`, i.e. during the convert step. And then remove the callback before training (disable the HTML tokenizer since it has already been used)

**Comment by mr-bjerre** [comment]
I think I know the issue. `nlp.make_doc(text)` is not necessarily equal to `nlp.make_doc(nlp.make_doc(text).text)` (they can disagree about `token.is_sent_start` - see [implementation of HTML tokenizer](https://github.com/pmbaumgartner/spacy-html-tokenizer/blob/5a544a0b5e1758eff3c8902df2763ced463b005c/src/spacy_html_tokenizer/html_tokenizer.py#L27))

Never the less - the error message seems a bit weird to me?

**Comment by adrianeboyd** [comment]
Nothing prevents `make_doc` from changing the text if this is something you want to do for some reason (we just generally don't recommend it and we're careful that none of our standard tokenizers do).

Can you provide a full example of the texts/tokens that can't be aligned? Because the docs don't have IDs to refer to, the initial tokens are provided in the error message to make it easier to debug, but the actual misalignment might be further down in the docs.

**Comment by mr-bjerre** [comment]
Can I add ID's to the docs so I can find the specific example giving me the error?

**Comment by adrianeboyd** [comment]
No, unfortunately a `Doc` doesn't have any kind of ID, which is why it's hard to have really specific (concise) error messages so providing the first N tokens is a bit of a hack.

**Comment by mr-bjerre** [comment]
I've been diving the data and I notice one difference `Mitsui E&amp;P Middle` (first run) vs `Mitsui E&P Middle` (second run). I'll close it here and continue the discussion in [`spacy-html-tokenizer`](https://github.com/pmbaumgartner/spacy-html-tokenizer/issues/2).
