### ISSUE TITLE
Doc.ents not working correctly in ver3.3.0

### ISSUE THREAD

**Issue by masoodimran** [explosion/spaCy#10851]
## How to reproduce the behaviour

doc = nlp("President Trump visited Mexico City.")
doc.ents
displacy.render(doc, style='ent')

![image](https://user-images.githubusercontent.com/30685384/170304248-58e9181a-b623-4d61-b4f2-eea24dcca32e.png)
![image](https://user-images.githubusercontent.com/30685384/170304903-2dfcefae-59ef-45aa-a4b6-d98eeea8c41a.png)

## Info about spaCy

- **spaCy version:** 3.3.0
- **Platform:** macOS-10.16-x86_64-i386-64bit
- **Python version:** 3.8.13
- **Pipelines:** en_core_web_md (3.3.0)

**Comment by polm** [comment]
This is not a bug, the model makes mistakes sometimes, see #3052. 

Note that the training data for the model includes a lot of newspaper texts, but it predates the Trump presidency, so it will not be very sensitive to his name.

**Comment by masoodimran** [comment]
@polm Thanks for the response. I agree to your point regarding the first example in my comment. But, the second one is from the Spacy documentation. How can this not work?

![image](https://user-images.githubusercontent.com/30685384/170412219-36790a03-4971-4a7e-a4f2-e1af19408828.png)

**Comment by masoodimran** [comment]
@polm Also, why does it work in this version of Spacy?

![image](https://user-images.githubusercontent.com/30685384/170413973-87b0c98a-a324-45cf-9015-b63f76e26f41.png)

**Comment by polm** [comment]
Moving to Discussions because this is not a bug report...
