### ISSUE TITLE
Unexpected Behavior when using nlp.pipe generator in for loop or list comprehension

### ISSUE THREAD

**Issue by premsa** [explosion/spaCy#10865]
## How to reproduce the behaviour

I reduced the problem to a basic representation as follows:

```
import spacy

nlp = spacy.load('en_core_web_sm')
```

Loading some data with the pipe functionality in a first cell in a jupyter notebook
```
docs = nlp.pipe(["German universities should on no account charge tuition fees.",
                "One could argue that an increase in tuition fees would allow institutions to be better equipped."])
```
Running a for-loop or list comprehension that uses `docs` in a second cell:

```
for doc in docs:
    print(doc)
```

Then running the exact same cell or a third cell again either as for-loop or list comprehension:

```
[print(doc) for doc in docs]
>> []
```
Which shows that the generator object does not produce any outputs anymore. Thus, the output is empty until I reload the first cell as defined above.

Any Idea how to debug this?
Best Regards
Premtim

## Environment
- **spaCy version:** 3.3.0
- **Platform:** Linux-4.15.0-135-generic-x86_64-with-glibc2.29
- **Python version:** 3.8.10
- **Pipelines:** en_core_web_sm (3.3.0), en_core_web_trf (3.3.0)
- **Usage**: Jupyter Notebook inside a docker container on a multi-gpu server running ubuntu20.04

**Comment by premsa** [comment]
Apparently, that's how generators work.

**Comment by polm** [comment]
Yes, generators are consumed / used up after iterating. 

You also have another issue, which is that `print` returns `None`.
