### ISSUE TITLE
Sorry to mistakenly sent out Jira invitations

### ISSUE THREAD

**Issue by karst10607** [explosion/spaCy#1087]
Hi, people in Spacy project. 
This is Howard Wu, who mistakenly sent out jira invitation to people who ever commented in the github project. 

I checked and can not find a place to post my message.
A day ago, I imported a forked spacy project from my github account into jira, and without any notice, it sent many invitations to people in the original spacy project.
A kind hearted person wrote me so I figured out the fuss I caused.
Apology for your confusion. 

I am a TESOL graduate student whose work is related to NLP, making research related to syntax teaching and the way to quantify the result. It's an app that works both on smartphone and pc browsers to track the performance of users' response time to choose correct verb tenses and plural forms. 
I need a lot of lemma data, integrated syntax checker/timer, and practical method to generate sentence for users to play the game.
I named it SyntaxEd because it's about the verb tense (V-ed) and Education. I am still far from completing it but it's on the way. 

Apologies again for such strange jira invitation sent to your inboxes. 
If Spacy project needs anything, I am willing to do more. I am also a full-time technical writer in a Taiwanese software company. That means I can produce user manuals and docs --- even when I am not a CS graduate.

**Comment by ines** [comment]
No worries – thanks for updating and letting people know! Maybe our [Gitter channel](https://gitter.im/explosion/spaCy) would also be a good place to post this, since a lot of our community members are active on there.

> If Spacy project needs anything, I am willing to do more. I am also a full-time technical writer in a Taiwanese software company. That means I can produce user manuals and docs --- even when I am not a CS graduate.

This is actually very interesting and a nice coincidence – just the other day, @honnibal and I were talking about maybe reaching out to the community to see if we have any users who speak/write Chinese and who'd be interested in helping us with a small project.

Specifically, spaCy documentation and tutorials in Chinese and guides on how to use spaCy on Chinese text. We've been seeing an increase in traffic and interest from Chinese developers, and we'd love to be able to provide more resources. So if you're interested, it'd be great to connect and talk about this more – feel free to email us at contact@explosion.ai!

**Comment by karst10607** [comment]
OK, thank you ines.
I am willing to help with the task.
I am removing and deactivating those users in my jira. I just found out if they keep registering in my project, I would have to pay up to 500 usd next month!

**Comment by ines** [comment]
@karst10607 Great – just send us a quick email so we can move the conversation there :)

And wow, this is pretty bad – have you emailed Jira about this? This sounds like pretty bad user experience. I mean, sure, you did send the invites by accident –  but it shouldn't have been THIS easy to invite ALL users of a random GitHub project, and especially not if it COSTS you money. Wtf.

**Comment by karst10607** [comment]
You're damn right, the funny thing is I found they do not have a good bulk edit for the user list --- not at all. Probably the core philosophy for JIRA is a small, active, strongly-connected team would not exceeded a certain number of users. 
I have been using their product Confluence for an year, but the bug fix and customer service of Atlassian products is weak and not very timely --- I understand time schedule issue, but there have been some emergencies for the months and I figured out they could not really fix many of the issues in time (DDoS, out of service, critical bug, bad design for certain features, etc)
Before they could solve this, I better spend hours to manually deactivate and delete the users one by one. Because I knew the customer support is sometimes a talking parrot, they couldn't really ask for the dev team to fix bugs within a few days or a week, even when they had located the problem or received the bug report 4 years ago!

**Comment by karst10607** [comment]
I just wrote them email. Yes, this is really an unbelievably bad user experience. 
I wish they could fix the bug for importing projects by adding check boxes and import options. There's no such user management options and limitation at all. 
No one would expect jira would send invitations like these, damn stupid. 
I might be the first to report such a bug, that's what happening all the time according to the customer service.  
I'd write to you about the Spacy doc or Chinese Spacy user manual project soon.
Thanks.
