### ISSUE TITLE
Training french NER : problems with some chars

### ISSUE THREAD

**Issue by GregoireMialon** [explosion/spaCy#1090]
Hi spaCy,

Thank you for this wonderful library. 

I'm currently trying to train the NER in french, using Europeana Newspaper ner dataset (https://github.com/EuropeanaNewspapers/ner-corpora/blob/master/enp_FR.bnf.bio/enp_FR.bnf.bio).

However, it seems that the tokenizer identifies some deprecated words of the dataset (e.g '•»') as two different tokens (i.e '•' and '»'). As a consequence, the array of inputs becomes longer than the array of labels, and, of course, the training fails.

Any idea to avoid this except detecting those annoying chars and add an exception for each one ? Given that each word is delimited in the dataset, is it possible to bypass the tokenizer ?

## Your Environment

* Operating System: windows 10
* Python Version Used:  3.5.2
* spaCy Version Used: 1.8.2

**Comment by honnibal** [comment]
Hi,

Sorry about the delay getting to this -- the solution is pretty simple. You want to set `doc = Doc(vocab, words=words)` to create a document without the tokenizer.

If you check back next week, you might also try using the develop branch, to try the new neural network model. You'll be able to use the convert and train scripts:

```
python -m spacy convert $train_file $json_dir -n 10
python -m spacy convert $dev_file $json_dir -n 10
python -m spacy train fr $model_dir/ $json_dir/train.json $json_dir/dev.json -P -T 
```

This will convert the `.iob` document into our JSON format, concatenating groups of 10 sentences into single paragraphs. This way, the NER becomes more suitable to real-world text, which you probably won't be feeding sentence-by-sentence.

We expected to have the alpha for v2 up this week, but serialising the models across CPU, GPU and Python 2, Python 3 has been tricky. The major features are all in-place though, and you should see better accuracy and smaller models than the linear model.

**Comment by ines** [comment]
See the [v2.0.0 alpha release](https://github.com/explosion/spaCy/releases/tag/v2.0.0-alpha) notes and #1105 🎉

(There's no French model available for v2.0.0 alpha yet, but we're working on that!)

**Comment by GregoireMialon** [comment]
Thank you all guys !

**Comment by kfrancoi** [comment]
Hi everyone,

Any success in the training of a french NER model into spaCy ?  I'm happy to help if I can contribute in anyway to this.

Thanks!
