### ISSUE TITLE
MLflow logger not working with textcat

### ISSUE THREAD

**Issue by raoulfasel93** [explosion/spaCy#10907]
New functionality was recently merged to https://github.com/explosion/spacy-loggers that allows easy loggint to MLflow. I quickly tried it out but it does not work. See the outptut:
[output.txt](https://github.com/explosion/spaCy/files/8830390/output.txt)
I think one of the metrics is in a string format while the plugin expects only floats.

## How to reproduce the behaviour
Start training the following pipeline using a binary label.
spacy pipeline config:
[config.txt](https://github.com/explosion/spaCy/files/8830364/config.txt)

## Info about spaCy

- **spaCy version:** 3.3.0
- **Platform:** Linux-5.15.0-33-generic-x86_64-with-glibc2.35
- **Python version:** 3.9.12
- **Pipelines:** nl_core_news_sm (3.3.0), en_core_web_sm (3.3.0)

I am using spacy-logger==1.0.2 

Thanks in advance!

**Comment by svlandeg** [comment]
Thanks for the report, we'll look into it!

**Comment by kromme** [comment]
Are there any updates on this one?

**Comment by rmitsch** [comment]
Fixed in https://github.com/explosion/spacy-loggers/pull/10. If you still observe this problem, feel free to reopen.
