### ISSUE TITLE
Error when installing spacy with cupy

### ISSUE THREAD

**Issue by sunhaozhepy** [explosion/spaCy#10918]
Hi,

This is a bug report concerning using GPU with spaCy and Anaconda.
I'm new to spaCy and I tried to follow the documentation to install it. More specificially, I used:
```
conda create --name spacy
conda activate spacy
conda install -c conda-forge spacy
conda install -c conda-forge cupy
python -m spacy download en_core_web_trf
python -m spacy download en_core_web_sm
```
when I opened Python in this environment, I saw:
```
C:\Users\Sun\anaconda3\envs\spacy\lib\site-packages\cupy\_environment.py:213: UserWarning: CUDA path could not be detected. Set CUDA_PATH environment variable if CuPy fails to load.
  warnings.warn(
```
and then I tried to use GPU by typing `spacy.prefer_gpu(),` and:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Sun\anaconda3\envs\spacy\lib\site-packages\thinc\util.py", line 204, in prefer_gpu
    require_gpu(gpu_id=gpu_id)
  File "C:\Users\Sun\anaconda3\envs\spacy\lib\site-packages\thinc\util.py", line 214, in require_gpu
    set_current_ops(CupyOps())
  File "C:\Users\Sun\anaconda3\envs\spacy\lib\site-packages\thinc\backends\__init__.py", line 140, in set_current_ops
    set_torch_tensor_type_for_ops(ops)
  File "C:\Users\Sun\anaconda3\envs\spacy\lib\site-packages\thinc\util.py", line 548, in set_torch_tensor_type_for_ops
    torch.set_default_tensor_type("torch.cuda.FloatTensor")
  File "C:\Users\Sun\anaconda3\envs\spacy\lib\site-packages\torch\__init__.py", line 323, in set_default_tensor_type
    _C._set_default_tensor_type(t)
TypeError: type torch.cuda.FloatTensor not available. Torch not compiled with CUDA enabled.
```
* Operating System: Windows 10
* Python Version Used: 3.10.4 (which comes with spacy when installing)
* spaCy Version Used: 3.3.0
* Environment Information: It is a an empty environment when I installed spaCy.

**Comment by sunhaozhepy** [comment]
I noticed this when installing, if this helps:
1. cupy comes with cudatoolkit=11.7 (as the environment was empty);
2. PyTorch was installed when trying to install en_core_web_trf.

**Comment by sunhaozhepy** [comment]
I think I got it. Apparently both CuPy and PyTorch come with an abridged CUDA Toolkit, but they are not enough for spaCy to use. One must install the standalone CUDA Toolkit on NVIDIA website.

**Comment by sunhaozhepy** [comment]
I installed CUDA Toolkit and it didn't work. Guess I'll have to install it first before installing CuPy...

**Comment by sunhaozhepy** [comment]
The first issue is understandable: spaCy and CuPy uses the smaller CUDA Toolkit and creates a "sandbox" so as to isolate their runtime from the global CUDA. However, the second issue is not clear for me: it seems that I can't use `en_core_web_trf` anyway.

**Comment by polm** [comment]
Sorry you're having trouble with this. 

Note that as an install-related issue, this belongs in Discussions. I'll move the thread and follow up with you there.
