### ISSUE TITLE
token.vector is calculated as all-0s creating problems with token.similarity() 

### ISSUE THREAD

**Issue by mraduldubey** [explosion/spaCy#1092]
Well, the code below explains that why the similarity is calculated incorrectly. **It is due to incorrect vector calculations:**

```
doc = nlp(u'apples is apple. orange is not. oranges is nothing')
def dot_prd(a, b):
    ans = 0
    sa, sb = 0, 0
    for i in range(len(a)):
        ans += a[i]*b[i]
        sa += a[i]*a[i]
        sb += b[i]*b[i]
    sa = sa**0.5
    sb = sb**0.5
    return ans/(sa*sb)

print doc[0], doc[2], doc[4], doc[8]

print dot_prd(doc[0].vector, doc[2].vector), dot_prd(doc[0].vector, doc[4].vector), dot_prd(doc[0].vector,doc[8].vector), dot_prd(doc[4].vector, doc[8].vector)

print doc[0].similarity(doc[2]), doc[0].similarity(doc[4]), doc[0].similarity(doc[8]), doc[4].similarity(doc[8])
```

Output:
```
apples apple orange oranges
0.750411317806 0.51238496547 nan nan   #Resuults of cosine-simlarity
0.750411349583 0.512384940626 0.0 0.0  #token.simlarity()
```
The ```doc[8].vector``` is all zeroes. So, why is the vector for 'oranges' token calculated as all-0s? 
The vector for 'orange' & 'apple' is calculated correctly. More importantly, the vector for 'apples' is also calculated correctly.  So, why is 'oranges' a problem? Is this a problem with the model ?

**Comment by mraduldubey** [comment]
@ines Devs please have a look.

**Comment by wimurr** [comment]
I don't know if this is related but I was getting puzzling results, too, when comparing cosine similarity for words that should be at least somewhat related, such as 'sociology' and 'biology'. Some reasonably common words such as 'sociology' are showing up as having empty vectors. Any idea why this is occurring or how to fix this? A colleague has an earlier version of spaCy that does not have this empty vector problem. I checked the GloVe vectors and they certainly have a non-empty vector for 'sociology', as you would expect.

![image](https://cloud.githubusercontent.com/assets/29132288/26703016/d6935630-46e4-11e7-9be9-d877bf607239.png)

**Comment by mraduldubey** [comment]
@wimurr Can you confirm which version of spacy was working correctly? Secondly, if GloVe vectors don't have this problem it is probably a bug indeed. Thanks for posting.

**Comment by wimurr** [comment]
Yes, I'm in version 1.8.2. My colleague, who was using version 0.101.0, seemed to have a normal result for the word embedding vector. Thanks for checking this.
![image](https://cloud.githubusercontent.com/assets/29132288/26705908/8444af16-46f6-11e7-9a90-38298263be3e.png)

**Comment by honnibal** [comment]
@wimurr You're likely using the `sm` model, which wasn't available in `0.101.0`. The `sm` model is only 50mb --- it includes only the vectors for the 5000 most common words. You can fix this by downloading `en_core_web_md`:

`python -m spacy download en_core_web_md`

**Comment by mraduldubey** [comment]
@honnibal The best solution would be to make the limitation of sm model more apparent in the documentation. Specifically the part of all-0s vectors for unknown words.

**Comment by wimurr** [comment]
Hi, thanks so much for the diagnosis, I would never have found that. I downloaded the larger model but I'm still having problems getting the new vectors to take effect. I've also tried manually loading the GloVe vectors I downloaded previously, but that seems to fail as well as trying to directly set the word embedding vectors for a word. Any help appreciated, am I doing something wrong loading the model?
![image](https://cloud.githubusercontent.com/assets/29132288/26740219/e6c0a118-4791-11e7-9663-40a047888bc7.png)

**Comment by wimurr** [comment]
Thanks so much for your help with this. It works now, although I don't seem to be able to load GloVe vectors with Vocab.load_vectors, nor can I directly set word embedding properties. Any advice on what's going on there appreciated, but the key point is I have all the vectors I need.
![image](https://cloud.githubusercontent.com/assets/29132288/26749024/20a0fa5c-47c1-11e7-858d-632d33912e62.png)

**Comment by wimurr** [comment]
I agree with the suggestion to update the documentation, especially this part, which seems to imply that all the vectors are there by default.
![image](https://cloud.githubusercontent.com/assets/29132288/26749043/6000f09e-47c1-11e7-90b7-ae85ecd16737.png)

**Comment by ines** [comment]
Thanks – I agree, we'll definitely fix this in the docs.

spaCy v2.0 will also feature natural handling of unknown words, as it can assign vectors based on context. See here for more info: https://alpha.spacy.io/docs/usage/word-vectors-similarities#similarity-context

**Comment by wimurr** [comment]
Thanks! Any pointers or tutorials to loading your own word embedding vectors would also be helpful. I'm most likely making some simple mistakes above that a tutorial example would clear up. If there isn't one available now, it would be nice to add for the next spaCy version. Looks like there used to be a tutorial, but it's gone away, as the page mentioned below no longer exists.
![image](https://user-images.githubusercontent.com/29132288/26856311-251ea792-4ae0-11e7-82ab-90cf12852f07.png)

**Comment by mraduldubey** [comment]
@wimurr You are right. I noticed that too.

**Comment by ines** [comment]
Sorry for only getting to this now - copying over my reply from #1012:

> We've since improved the vector loading and GloVe vectors support in spaCy v2.0, currently in alpha. You can test the new version by running `pip install spacy-nightly`.

> The new version also comes with re-written and restructured docs, including a new section on word vectors: https://alpha.spacy.io/usage/vectors-similarity

> See here for the relevant section on loading GloVe vectors:
https://alpha.spacy.io/usage/vectors-similarity#custom-loading-glove

I hope this helps with the question around loading vectors into spaCy. 

We'll also think about a better way to make the vectors included in the models more explicit in the docs – especially in the new [models directory](https://alpha.spacy.io/models/en) in v2.0. The model directory requests each individual model's `meta.json` and displays the model information. Having another key in the model meta that describes the vectors would probably make a big difference already. For example:

```json
{
    "lang": "en",
    "name": "core_web_sm",
    "version": "2.0.0",
    "pipeline": ["tagger", "parser", "ner"],
    "vectors": {
        "width": 300,
        "entries": 5000
    }
}
```

This info could be read off the model automatically after training. This would also mean that when you train and package your own model using `spacy train` and `spacy package`, this information will be included automatically.
