### ISSUE TITLE
ValueError: [E002] Can't find factory for 'transformer' for language Italian (it)

### ISSUE THREAD

**Issue by Panzerotto93** [explosion/spaCy#10971]
## How to reproduce the behaviour
Create docker image with:
- spacy==3.2.4
- spacy[transformers]==3.2.4
- transformers==4.17.0
- tokenizers==0.12.1
In requirements. I downloaded the model files and put them in a folder inside the docker image.
Calling spacy.load(path/to/model/it_nerIta_trf), will raise the error in the title.

## Your Environment

- **spaCy version:** 3.2.4
- **Platform:** Windows-10-10.0.19044-SP0
- **Python version:** 3.9.7
- **Pipelines:** it_nerIta_trf (0.0.0)

How do I solve this? I have no problems running the code locally on Windows, but the error is raised in a Linux Docker container. Thanks!

**Comment by polm** [comment]
Because this is installation related I'll move it to a discussion.
