### ISSUE TITLE
error on running the example keras_parikh_entailment

### ISSUE THREAD

**Issue by csxht** [explosion/spaCy#1098]
when I run a small preliminary test of the Keras model:
py.test keras_parikh_entailment/keras_decomposable_attention.py
-----------------------------------------------------------------------
TypeError: call() got an unexpected keyword argument 'mask'
/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py:596: TypeError
------------------------------------------------------------------------

## Your Environment

* Operating System: Ubuntu 14.04.2 LTS
* Python Version Used: python2.7
* spaCy Version Used: 1.8.2
* Environment Information: keras 2.0.4

**Comment by crazyofapple** [comment]
I also have this problem, do you fix it?

**Comment by ines** [comment]
Merging this with #1445!
