### ISSUE TITLE
token prob attribute is giving -20.0 for every word / spacy 2.3.7

### ISSUE THREAD

**Issue by tilusnet** [explosion/spaCy#11025]
This is a replica of https://github.com/explosion/spaCy/issues/1659, but with language model `en_core_web_md`.

## How to reproduce the behaviour
I am following your [SpaCy 2.3 Migration Guide](https://spacy.io/usage/v2-3), -- sadly you have no permalinks in your documentation sections, so I am illustrating with a screenshot (tip: please add permalinks to your docs):
![Screenshot from 2022-06-24 15-16-07](https://user-images.githubusercontent.com/705606/175554772-3f1ff755-4025-4430-bf37-d409265962ba.png)

This does not work in my environment. All `.prob` values are -20.0

## Your Environment

* Operating System: Linux Ubuntu 20.04
* Python Version Used: 3.9.13
* spaCy Version Used: 2.3.7
* spaCy models: 
  * en_core_web_md 2.3.1
  * spacy-lookups-data 1.0.3

**Comment by tilusnet** [comment]
fyi, spacy model `en_core_web_lg-2.3.1` has the same problem as `en_core_web_md-2.3.1`.

**Comment by polm** [comment]
The way spacy-lookups-data works changed slightly in 1.0, and for the v2 functionality described in the release notes you should use 0.3.2, the last version before 1.0. This is described in `setup.cfg`, so it would be automatic if you did `pip install spacy[lookups]==2.3.7`, but there's no way to get pip to check that if you do `pip install spacy-lookups-data` unfortunately. 

> sadly you have no permalinks in your documentation sections, so I am illustrating with a screenshot (tip: please add permalinks to your docs):

We have anchor links in our documentation, just not for every level of headers. You can state the section name if you need to, the screenshot doesn't really help...

**Comment by tilusnet** [comment]
@polm your answer is spot on, thank you!
