### ISSUE TITLE
Duplicate in Dutch sources

### ISSUE THREAD

**Issue by BramVanroy** [explosion/spaCy#11032]
On this [release page](https://github.com/explosion/spacy-models/releases/tag/nl_core_news_sm-3.3.0) and the [model overview](https://spacy.io/models/nl), the sources of all models have `UD Dutch LassySmall v2.8 (Bouma, Gosse; van Noord, Gertjan)` twice.

I couldn't find the source for this information so I wasn't able to do a PR.

**Comment by polm** [comment]
Thanks for the report, that does look like a mistake. The file that controls that is [here](https://github.com/explosion/spacy-models/blob/b3ca97a7cbd6806d374c32d1133b6c3c4313a03d/meta/nl_core_news_sm-3.0.0.json), in the `spacy-models` repo.

**Comment by adrianeboyd** [comment]
The website list is generated from the file Paul linked, but the underlying data/scripts are in a private training data repo, so there isn't a way for you to do a PR.

I've added deduplication here that should be applied in the next round of model training.
