### ISSUE TITLE
Invalid link for spacy entity linker knowledge base

### ISSUE THREAD

**Issue by Shengyu-Feng** [explosion/spaCy#11037]
Hi, I find that `python -m spacy_entity_linker "download_knowledge_base"` gives HTTP 403 Forbidden error. I think the link is broken, could you fix that?

**Comment by ljvmiranda921** [comment]
Hi @Shengyu-Feng , curious where you found that line of code? Can you link it here?
Also, it seems that the line itself is not a valid spaCy command, unless you're using some third-party library from the [spaCy universe](https://spacy.io/universe)?

**Comment by ljvmiranda921** [comment]
Ah, it seems to be related to https://github.com/egerber/spaCy-entity-linker/issues/11. Note that `spacy-entity-linker` is a third-party library not developed by us, so we have no control over fixing the connectivity issue. Although we have control of the Universe entry, the library itself is updated by the library maintainers. Unfortunately, the upstream library's latest commit was a year ago; I'm afraid it might be abandoned (it seems likely we'll remove it). As a possible step, you may be able to replicate the data by following the [maintainer's notes](https://github.com/egerber/spaCy-entity-linker#data).
