### ISSUE TITLE
displayCy render for style=span doesn't work in Jupyter

### ISSUE THREAD

**Issue by ceesroele** [explosion/spaCy#11040]
## How to reproduce the behaviour

In a Jupyter cell:

```
import spacy
from spacy import displacy
from spacy.tokens import Span

text = "Welcome to the Bank of China."

nlp = spacy.blank("en")
doc = nlp(text)

doc.spans["sc"] = [
    Span(doc, 3, 6, "ORG"), 
    Span(doc, 5, 6, "GPE"),
]

displacy.render(doc, style="span", jupyter=True)

```

The result will display the `text` with **Bank of China** in bold face.

When replacing the last line with the rendering command with:

```
displacy.serve(doc, style="span")
```
The expected visualization with `ORG` and `GPE` marking is displayed as a result - plus a warning as `displaycy.serve` should not be called from a Jupyter notebook.

## Your Environment

- **spaCy version:** 3.3.1
- **Platform:** macOS-10.16-x86_64-i386-64bit
- **Python version:** 3.10.4
- **Pipelines:** en_core_web_lg (3.3.0), en_core_web_sm (3.3.0)

**Comment by ljvmiranda921** [comment]
Hi @ceesroele 

I can't seem to replicate this problem. I'm curious which Jupyter lab / notebook version are you using? You can know by typing `jupyter --version` in your console. Also, just to cover all bases, note that sometimes, the spans themselves get hidden by Jupyter's scrollbar (see attached GIF). 

## jupyter lab 
![spancat_displacy](https://user-images.githubusercontent.com/12949683/176108893-8920c2e8-f3b5-4232-9ebb-4f90afbf93e6.gif)

## jupyter notebook
 
![spancat_displacy_2](https://user-images.githubusercontent.com/12949683/176109156-04705687-a8fc-4484-bbc0-c860fce03fbe.gif)

Here is my environment information:

```
λ: jupyter --version
Selected Jupyter core packages...
IPython          : 8.2.0
ipykernel        : 6.4.1
ipywidgets       : not installed
jupyter_client   : 7.0.6
jupyter_core     : 4.8.1
jupyter_server   : 1.11.1
jupyterlab       : 3.1.18
nbclient         : 0.5.4
nbconvert        : 6.2.0
nbformat         : 5.1.3
notebook         : 6.4.4
qtconsole        : not installed
traitlets        : 5.1.0
```

**Comment by ceesroele** [comment]
Aha, scrolling is indeed possible. Thank you! Yet, the controls for scrolling become visible only when the contents are actually scrolled by dragging it.

This means that the span information is actually present on the page, but not visible. When the span information is made visible through scrolling, the text is scrolled away and hence it disappears. This is the behaviour seen in the animated GIF above.

Thus:
- We can't see text and span information at the same time
- There is no indication in or around the notebook cell that scrolling is possible

Moreover, when we use the .serve method instead of the .render method, we *do* see the information presented completely.

I think not seeing text and spans straight away is unwanted behaviour of the .render method for spans.

**Comment by pmbaumgartner** [comment]
Hey @ceesroele - thanks for this issue. 

We actually have an open PR (https://github.com/explosion/spaCy/pull/10994) that fixes this issue as a byproduct of fixing another issue. I ran this code in a notebook after installing that PR branch. 

<img width="509" alt="image" src="https://user-images.githubusercontent.com/5107405/176218400-c610c7de-5705-454e-baac-c89460cd5f10.png">

If you need this functionality urgently, you could install spaCy from that branch with `!pip install -U git+https://github.com/pmbaumgartner/spaCy@displacy-spans-fix`, but you won't be using an official release so you may encounter issues with other spaCy code you have.
