### ISSUE TITLE
Unclear in documentation how to use "quantifiers"

### ISSUE THREAD

**Issue by kootenpv** [explosion/spaCy#1104]
See here https://spacy.io/docs/usage/rule-based-matching#quantifiers

Related doc line:
https://github.com/explosion/spacy/blob/master/website/docs/usage/rule-based-matching.jade#L60

**Comment by ines** [comment]
Agreed – on top of this, there are still some unresolved bugs in the `Matcher` and quantifiers, which we'll hopefully fix for the official v2.0.0 launch.

For reference, here are the v2 alpha docs on the new `Matcher` API that describe how it's *supposed to* work: http://alpha.spacy.io/docs/usage/rule-based-matching

**Comment by jnothman** [comment]
The docs should at least say that the quantifier is to be keyed by "OP". That seems a small fix of great value, even if it's buggy.
