### ISSUE TITLE
pySBD - python Sentence Boundary Disambiguation: Example no longer runs

### ISSUE THREAD

**Issue by gserapio** [explosion/spaCy#11045]
The documentation example for pySBD no longer runs. See https://github.com/nipunsadvilkar/pySBD/issues/101

## Which page or section is this issue related to?

https://spacy.io/universe/project/python-sentence-boundary-disambiguation

**Comment by rmitsch** [comment]
Thanks for the hint! The spaCy universe projects are usually not maintained by us. In this asked we dropped the maintainer a line, they'll take a look at the issue.

**Comment by polm** [comment]
The Universe entry has been updated to clarify that this only works with spaCy v2.
