### ISSUE TITLE
💫 Fix English lemmatizer data 

### ISSUE THREAD

**Issue by ines** [explosion/spaCy#1106]
There are still various issues around the hard-coded lemmatizer data, especially in English. This needs to be before the official v2.0 launch. The English lemmatizer data is now located in [`spacy/lang/en/lemmatizer`](https://github.com/explosion/spaCy/tree/develop/spacy/lang/en/lemmatizer).

### Related issues

* #1041: Lemma of "hated" is "hat"
* #1048: Unwanted result while getting lemma_ of token "need"
* #1049: Wrong lemmatisation of the verb 'Hope'

**Comment by kootenpv** [comment]
I noticed "need" as well, but do note that it was working in the larger model, it is only in the small model I believe that the lemma was "ne".

**Comment by ibrahimsharaf** [comment]
Hi @ines @kootenpv, how can I start working on this issue?

**Comment by honnibal** [comment]
I think this is fixed now. See https://github.com/explosion/spaCy/pull/1389

Thanks all!
