### ISSUE TITLE
Displacy style=span doesn't display span in correct vertical position when span longer than overlapping previous span

### ISSUE THREAD

**Issue by ceesroele** [explosion/spaCy#11084]
The red arrows in the image below indicate the broken vertical position for spans with label `NameCall` and `Smears`. These spans are longer than previous spans which they overlap
![image](https://user-images.githubusercontent.com/739116/177333407-454bf41a-e22f-4c8f-96fb-97a9a51edd25.png)

(Bonus question: is an extra space between '"' and a quoted term desired behaviour? `"dumbest"` becomes `" dumbest "`) 

## How to reproduce the behaviour

```python
import spacy
from spacy.displacy.render import DEFAULT_LABEL_COLORS
from spacy import displacy

d = {'id': '691_batch_2',
 'text': 'Sen. Mazie Hirono, D-Hawaii, the dumbest person in the U.S. Capitol*, \
questions Judge Amy Coney Barrett, the smartest person, \
during Confirmation hearings this week.\n\n* Normally, \
the "dumbest" designation goes to Rep. Maxine Waters, \
D-Calif., but Ms. Waters was not present in the building.\n',
 'labels': [
    {'start': 0, 'end': 67, 'technique': 'Smears',
        'text_fragment': 'Sen. Mazie Hirono, D-Hawaii, the dumbest person in the U.S. Capitol'},
     {'start': 29, 'end': 47, 'technique': 'Loaded',
        'text_fragment': 'the dumbest person'},
     {'start': 29, 'end': 47, 'technique': 'ExMin',
        'text_fragment': 'the dumbest person'},
    # The next entry defines a span that becomes broken by displacy:
     {'start': 29, 'end': 67, 'technique': 'NameCall',
        'text_fragment': 'the dumbest person in the U.S. Capitol'},
     {'start': 80, 'end': 124, 'technique': 'Virtue',
        'text_fragment': 'Judge Amy Coney Barrett, the smartest person'},
     {'start': 105, 'end': 124, 'technique': 'NameCall',
        'text_fragment': 'the smartest person'},
     {'start': 105, 'end': 124, 'technique': 'ExMin',
        'text_fragment': 'the smartest person'},
     {'start': 179, 'end': 204, 'technique': 'ExMin',
        'text_fragment': 'the "dumbest" designation'},
    # The next entry defines a span that becomes broken by displacy:
     {'start': 179, 'end': 241, 'technique': 'Smears',
        'text_fragment': 'the "dumbest" designation goes to Rep. Maxine Waters, D-Calif.'},
    {'start': 183, 'end': 192, 'technique': 'Loaded',
        'text_fragment': '"dumbest"'}
    ]
}


def span_encode(nlp, d, spans_key='sc'):
    """Create a `Doc` object with spans from data"""
    text = d['text']
    doc = nlp(text)
    span_list = []
    for l in d['labels']:
        start = l['start']
        end = l['end']
        label = l['technique']
        span = doc.char_span(start, end, label=label)
        span_list.append(span)
    doc.spans[spans_key] = span_list
    return doc


def main():
    spans_key = 'mnp'
    nlp = spacy.load('en_core_web_sm')

    doc = span_encode(nlp, d, spans_key=spans_key)

    techniques = [
        'Smears',
        'Loaded',
        'ExMin',
        'Virtue',
        'NameCall'
    ]

    # We take the default label colours and attribute them to our labels
    colours = list(DEFAULT_LABEL_COLORS.values())
    colour_dict = {}
    for i, t in enumerate(techniques):
        colour_dict[t] = colours[i]

    options = {
        'spans_key': spans_key,
        'colors': colour_dict
    }

    displacy.serve(doc, style='span', options=options)


if __name__ == '__main__':
    main()
```

## Your Environment

Using spaCy with PR #10994 by @pmbaumgartner
`pip install -U git+https://github.com/pmbaumgartner/spaCy@displacy-spans-fix`

- **spaCy version:** 3.3.0
- **Platform:** macOS-10.16-x86_64-i386-64bit
- **Python version:** 3.10.4
- **Pipelines:** en_core_web_lg (3.3.0), en_core_web_sm (3.3.0)

**Comment by pmbaumgartner** [comment]
Hey @ceesroele - thanks for opening the issue. We'll take a look.

For your question about quotes - that's happening because the quotes are individual tokens, and the span highlight gets applied to each token. I think this logic is also the source of this issue, because we're never "looking ahead" when a span highlight gets created to understand that we need to extend the current horizontal alignment to the next token - we're just adding up the total number of highlights per token.

**Comment by pmbaumgartner** [comment]
It took me a bit of time to figure out the logic for this one, but I've got something working that fixes this issue. I want to run some more examples and possibly refactor a bit more of this code to make it more clear what's going on, but I'll have a PR for this sometime soon-ish.

<img width="968" alt="image" src="https://user-images.githubusercontent.com/5107405/177598800-101ac2b6-510a-432e-8f28-4c56198cb10f.png">

@ceesroele Your example was really helpful in giving me something to check against. Do you happen to have any more examples you know have this issue that I can use for testing?

**Comment by ceesroele** [comment]
Hi @pmbaumgartner , 

I created a `spacy` file including twenty documents with multiple spans. Just the first twenty out of the dataset I use and I didn't try to filter out those *not* exhibiting the displacy broken line behaviour.

```python
import json
import spacy
from spacy import displacy
from spacy.tokens import DocBin

from spacy.displacy.render import DEFAULT_LABEL_COLORS

def displacy_example(spans_key='sc'):
    print(f'spaCy version: {spacy.__version__}')

    nlp = spacy.load('en_core_web_sm')

    docbin = DocBin().from_disk('span_examples.spacy')
    docs = list(docbin.get_docs(nlp.vocab))

    # We take the default label colours and attribute them to our labels
    labels = set()
    for d in docs:
        for s in d.spans[spans_key]:
            labels.add(s.label_)

    colour_dict = {}
    colours = list(DEFAULT_LABEL_COLORS.values())
    for i, t in enumerate(labels):
        colour_dict[t] = colours[i]

    options2 = {
        'spans_key': spans_key,
        'colors': colour_dict
    }

    print("Number of documents = ", len(docs))

    displacy.serve(docs, style='span', options=options2)


if __name__ == '__main__':
    displacy_example(spans_key='mnp')
```
Note: the used dataset comes from SemEval 2021 and I applied the spaCy `SpanCategorizer` on it in [Detecting Persuasion with spaCy](https://medium.com/p/6b6beba51076). I look forward updating the article by calling `displacy` to illustrate the overlapping spans in the examples, rather than my own drawings :-)

If you want more examples - full of overlapping spans - you can clone the github repository associated with the article to load the assets and use the attached `generate_examples.py` script with `MAX_ITEMS` set to your convenience to generate a DocBin file for the above script. (The script is a bit messy as I used it for another purpose.)

[span_examples.spacy.zip](https://github.com/explosion/spaCy/files/9060466/span_examples.spacy.zip)

[generate_examples.py.zip](https://github.com/explosion/spaCy/files/9060473/generate_examples.py.zip)

**Comment by ceesroele** [comment]
P.S. You might want to check out also the following example, as here two lines are "interrupted" by a new span. The interrupted spans move down, rather than up as in the previous example.
<img width="1095" alt="Screenshot 2022-07-07 at 08 14 14" src="https://user-images.githubusercontent.com/739116/177697163-bfa9460b-6c9f-4c9e-87af-0a5bf7387da8.png">

**Comment by pmbaumgartner** [comment]
Thanks for the additional examples @ceesroele.

Here's what the last example looks like under the fix: 
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/5107405/177789856-ee10d3b4-43b0-49f7-9ab8-7abf0933bd0c.png">

Your other examples were also helpful, they surfaced an issue with whitespace I'm currently working on, e.g.

<img width="694" alt="image" src="https://user-images.githubusercontent.com/5107405/177790313-7d2d6bf2-ea13-4dd4-a2ca-2982340748b6.png">

**Comment by pmbaumgartner** [comment]
Alright, finally got a working solution that eliminates the whitespace issue and the odd overlapping behavior seen in the previous image.

<img width="835" alt="image" src="https://user-images.githubusercontent.com/5107405/177856153-bb9d4815-9d2f-4958-8b9a-9ff8dced6e27.png">
