### ISSUE TITLE
ImportError: libgomp.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ajayrfhp** [explosion/spaCy#1110]
Installed spacy through conda and installation was successful. On doing import spacy, got this error. 

> 'ImportError: libgomp.so.1: cannot open shared object file: No such file or directory'

**Comment by ines** [comment]
Try this:

```bash
sudo apt-get install libgomp1
```

If you're on Ubuntu 14.04+, this should fix it. Just did a quick search and apparently `libgomp1` is not installed by default anymore on Ubuntu 14.04 or later. (If this still doesn't work, you can always [build spaCy from source](https://spacy.io/docs/usage/#source) instead – although I don't think this will be necessary in this case.)

**Comment by ajayrfhp** [comment]
Worked, thanks.

**Comment by jnothman** [comment]
But shouldn't the conda packaging handle this?

**Comment by jnothman** [comment]
Btw, this is [fixed in conda-forge](https://github.com/conda-forge/spacy-feedstock/issues/16), but not in anaconda's main channel.
