### ISSUE TITLE
Spacy Parser Returning Blank Columns with Pandas & Multiprocessing

### ISSUE THREAD

**Issue by MaxPowerWasTaken** [explosion/spaCy#1111]
Question posted yesterday with fully reproduceable code example at https://stackoverflow.com/questions/44395656/applying-spacy-parser-to-pandas-dataframe-w-multiprocessing

Summary:
I have a short python wrapper function which accepts a  `pandas dataframe` & a `function`, and applies the `function` to the `dataframe` in parallel. If I parse a text with Spacy (using `my_pandas_series.apply(nlp)`) without parallelizing, I get expected results. When I do it using the `multiprocessing` wrapper function, I get back a blank column.

Is this expected behavior?

## Your Environment

* Operating System: Linux Mint 18 Sarah
* Python Version Used: 3.5
* spaCy Version Used: 1.8.2
* Environment Information:

**Comment by honnibal** [comment]
Thanks for the detailed report.

I haven't dug into this properly, but at a glance I suspect that the `multiprocessing` code is expecting to pickle/unpickle the spaCy `nlp` object. One of the major features of spaCy 2 is improved serialization, including full support for the Pickle protocol. But in spaCy 1.x, Pickle isn't expected to work.

What's interesting is that there's no error -- so maybe my analysis is wrong, and a different problem is being encountered? If so, I still think the lack of pickle support will block what you're trying to do here.

**Comment by MaxPowerWasTaken** [comment]
Thanks for the reply Honnibal. I just tried the same code example in a new environment with `Spacy 2` and `en_core_web_sm-2.0.0-alpha` and got the same result, in case that's helpful to understanding this.

Also, in case it means anything, after running my dataframe through the multiprocessing-wrapped-function to add a parsed column, not just the new parsed column is blank, but also the old previously-parsed column becomes newly blank after being run through multiprocessing.	

And of course, thanks a ton for such an awesome library!

**Comment by MaxPowerWasTaken** [comment]
Hey Honnibal, I have some availability to look into this this week if that would be helpful. I'm not very familiar with spacy's code base though, would you have a hunch on where I might start looking?

**Comment by honnibal** [comment]
Pickle is now fixed on develop, for both the `Language` class and the `Doc`. :tada:

Pickling should be quite fast, with no redundant copies of the `Vocab` --- so you can pickle a list of `Doc` objects, and it'll do the right thing and only have one copy of all the shared data.

**Comment by nitin608** [comment]
@honnibal Is this issue fixed in master as well or do I have to build the library from develop?
I am on spacy version 2.0.11
