### ISSUE TITLE
Demo docker for catalan models not working

### ISSUE THREAD

**Issue by cayorodriguez** [explosion/spaCy#11117]
## How to reproduce the behaviour

When trying out the catalan models in

https://spacy.io/models/ca

We get the following errors:

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/tmp/ipykernel_42/3582604829.py in <module>
      2 from spacy.lang.ca.examples import sentences
      3 
----> 4 nlp = spacy.load("ca_core_news_sm")
      5 doc = nlp(sentences[0])
      6 print(doc.text)

/srv/conda/envs/notebook/lib/python3.7/site-packages/spacy/__init__.py in load(name, vocab, disable, exclude, config)
     49     """
     50     return util.load_model(
---> 51         name, vocab=vocab, disable=disable, exclude=exclude, config=config
     52     )
     53 

/srv/conda/envs/notebook/lib/python3.7/site-packages/spacy/util.py in load_model(name, vocab, disable, exclude, config)
    329     if name in OLD_MODEL_SHORTCUTS:
    330         raise IOError(Errors.E941.format(name=name, full=OLD_MODEL_SHORTCUTS[name]))
--> 331     raise IOError(Errors.E050.format(name=name))
    332 
    333 

OSError: [E050] Can't find model 'ca_core_news_sm'. It doesn't seem to be a Python package or a valid path to a data directory.
## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

Not rellevant, since this is a issue on your side

**Comment by adrianeboyd** [comment]
Thanks for the note, we'll take a look!

**Comment by adrianeboyd** [comment]
This should be updated now.
