### ISSUE TITLE
Span.id_ and Span.id missing from Span typings

### ISSUE THREAD

**Issue by mr-bjerre** [explosion/spaCy#11118]
`Span` is missing `id` and `id_` attribute in [`span.pyi`](https://github.com/explosion/spaCy/blob/master/spacy/tokens/span.pyi#L120) typings

## Info about spaCy

- **spaCy version:** 3.3.1
- **Platform:** macOS-12.4-arm64-arm-64bit
- **Python version:** 3.9.9

**Comment by rmitsch** [comment]
Thanks for reporting this! Your PR has been merged.
