### ISSUE TITLE
Spacy custom training on apple m1 Mac using GPU : not working

### ISSUE THREAD

**Issue by Anand195** [explosion/spaCy#11146]
## How to reproduce the behaviour
install space for apple , select model training option and follow the on screen instructions.

generate config files for model training.

Declare your training and testing corpus in base_config file then auto fill the to generate the final config file.

python -m spacy init fill-config base_config.cfg  config.cfg

python -m spacy train config/config.cfg -g 0 --output trf_model-2

## Your Environment

* Operating System: MacOS 12.4
* Python Version Used: 3.10
* spaCy Version Used: 3.4.0
* Environment Information: -

- **spaCy version:** 3.4.0
- **Platform:** macOS-12.4-arm64-arm-64bit
- **Python version:** 3.10.5
- **Pipelines:** en_core_web_trf (3.4.0)

While I'm trying to train the model using gpu on m1 Mac got this error

RuntimeError: invalid gradient at index 0 - expected device cpu but got mps:0

**Comment by polm** [comment]
Mac GPUs are not supported right now, please see #10783.

**Comment by Anand195** [comment]
OK, Thanks!
