### ISSUE TITLE
is_stop function returns False for all values under en_core_web_md model

### ISSUE THREAD

**Issue by JherezTaylor** [explosion/spaCy#1121]
model name: core_web_md    
model version: 1.2.1
```
nlp = spacy.load('en_core_web_md')
nlp.vocab[u'is'].is_stop
False
```
The `en_core_web_md` throws `False` for all stop words that I test with. However, loading the `en` model as follows gives the correct result.
```
nlp = spacy.load('en')
nlp.vocab[u'is'].is_stop
True
```

## Your Environment
* **spaCy version:** 1.8.2
* **Installed models:** en_vectors_glove_md, en, en_core_web_md
* **Python version:** 3.5.3
* **Platform:** Linux-4.10.1-041001-generic-x86_64-with-Ubuntu-17.04-zesty

**Comment by sadovnychyi** [comment]
https://github.com/explosion/spaCy/issues/922 – there's a workaround for that.

**Comment by JherezTaylor** [comment]
Closing as per #922
