### ISSUE TITLE
Displacy arrows not pointing to the right part of words

### ISSUE THREAD

**Issue by SecroLoL** [explosion/spaCy#11217]
Currently visualizing dependencies in several languages for Stanford's NLP Lab and I'm running into a few instances of unexpected behavior when it comes to rendering the visualizations inside of Jupyter notebooks. The arrows on the dependency visualizations often point to the sides of words rather than the middle of the words as intended. Is this a consequence of custom visualization options (included below)? Secondly, the dependencies themselves are often getting cut off by the arrows and are unreadable in other cases. Please let me know if these are intended, or how to fix.

## How to reproduce the behaviour

`visualization_options = {"compact": True, "bg": "#09a3d5", "color": "white", "distance": 90,
                             "font": "Source Sans Pro", "arrow_spacing": 25}`

This is the visualization option setting that I use for visualizations. I am using custom dependency relationships, but the issue is with the visualization. To reproduce the behavior, it should be sufficient to load with spacy's own dependencies; such as 

```
import spacy 
from spacy import displacy

visualization_options = {"compact": True, "bg": "#09a3d5", "color": "white", "distance": 90,
                             "font": "Source Sans Pro", "arrow_spacing": 25}

nlp = spacy.load('en_core_web_sm')
doc = nlp("He is wearing a red shirt")
displacy.render(doc, style='dep', options=visualization_options) 
```

Pictures included below.
![image](https://user-images.githubusercontent.com/33791574/181127060-eca11ee2-6421-4de1-8882-7ead9546427b.png)
![image](https://user-images.githubusercontent.com/33791574/181127111-d66aa67f-8d4f-4bd3-a556-a048b8987247.png)
As seen, the arrows often point to the right of the words, and the dependency relationships can be cut off by arrows, or wrap the text around them.

## Your Environment
- **spaCy version:** 3.3.1
- **Platform:** Windows-10-10.0.19044-SP0
- **Python version:** 3.9.7
- **Pipelines:** en_core_web_sm (3.3.0)

**Comment by polm** [comment]
That's weird output, sorry you're having trouble with that. Can you tell us what browser you're using? Does it look OK with default options?

**Comment by polm** [comment]
After trying this with the default options and your options, and modifying the values, it looks like this is just the intended result of the values you gave for `distance` and `arrow_spacing`. Is there any particular reason you're using those values?

Those options are provided to tune the output, but there's no guarantee any value will result in reasonable output. For example you can put `distance` to 10 and it's not an error, but the output won't be useful.
