### ISSUE TITLE
Pre-assign POS to tokens

### ISSUE THREAD

**Issue by dhruvg** [explosion/spaCy#1122]
I am experimenting with the POS tagger in spaCy. Is it possible to pre-assign the POS to certain tokens before running the POS tagger? My specific use case is tweets. I want to pre-assign all the twitter handles in a piece of text as PROPN. I assume this will effect how the rest of the words are tagged. Is there a way to do this in a non-hacky way and not specifically special casing each one?

## Info about spaCy

* **Platform:** Darwin-14.3.0-x86_64-i386-64bit
* **spaCy version:** 1.8.2
* **Python version:** 3.5.0
* **Installed models:** en

**Comment by honnibal** [comment]
If you assign to `token.tag` or `token.tag_` before the tagger runs, this should just work. You can do this by assigning a processing function into the `nlp.pipeline` list.

The tagger checks that the word doesn't have a pre-specified POS tag (this is how the exceptions are preserved). If it does, it leaves it alone. And yes, the preset tags will be used as features by the tagger.
