### ISSUE TITLE
spacy matcher demo not working

### ISSUE THREAD

**Issue by vijayendrams** [explosion/spaCy#11245]
## How to reproduce the behaviour
The online matcher demo (https://explosion.ai/demos/matcher) is not working. 

## Your Environment

* Operating System: MacOS BigSur Version 11.6
* Python Version Used: n/a
* spaCy Version Used:n/a
* Environment Information: chrome version 103.0.5060.134 (Official Build) (x86_64)

In the example below, a simple number match should have worked.

<img width="1524" alt="Screenshot 2022-07-29 at 12 19 37 PM" src="https://user-images.githubusercontent.com/5878358/181703554-18e2230e-1d8f-44d0-9586-c38f0a6c9dea.png">

Similarly, in the second case below a simple Title case match is not showing the highlighted matching tokens. The "Display Tokens" feature seems to be broken too..

<img width="1489" alt="Screenshot 2022-07-29 at 12 42 52 PM" src="https://user-images.githubusercontent.com/5878358/181703909-1f506909-5948-4426-b8f4-bd8c347c610d.png">

**Comment by koaning** [comment]
Looking at devtools it seems that we're getting 422 requests on this endpoint: 

```
POST https://matcher.prod.demos.explosion.services/match
```

@nipunsadvilkar figured I'd send a ping so it's on your radar.

**Comment by nipunsadvilkar** [comment]
Thanks @koaning for sending it my way.

@vijayendrams We have identified the cause and the issue will be resolved soon (most likely this week)
