### ISSUE TITLE
Citing Spacy spcific models and version in a paper

### ISSUE THREAD

**Issue by zarakolagar120** [explosion/spaCy#11274]
Hi, 
I have used the German Spacy model [de_core_news_sm](https://spacy.io/models/de#de_core_news_sm) version 3.3.0 to lemmatize my dataset and has reported the result in my paper and now I would like to cite that inside the text and also in the reference section in my paper, but I am not sure what information to include and how the biblatex should look like.

**Comment by adrianeboyd** [comment]
There's a bibtex citation for spacy under "Cite this repository" in the right-hand bar on the main github repo page.

For the model I think that the model name + exact version number should be sufficient. You can use the release notes as a permanent URL to cite: https://github.com/explosion/spacy-models/releases/tag/de_core_news_sm-3.3.0
