### ISSUE TITLE
Specify model in requirements.txt

### ISSUE THREAD

**Issue by anton164** [explosion/spaCy#1129]
Hey,

I've been trying to add "en_vectors_glove_md" in the requirements.txt to deploy a process on Heroku, like so:
`
-e git://github.com/explosion/spacy-models.git@en_vectors_glove_md-1.0.0#egg=en_vectors_glove_md`
but I'm getting the following error:
```
Obtaining en_vectors_glove_md from git+git://github.com/explosion/spacy-models.git@en_vectors_glove_md-1.0.0#egg=en_vectors_glove_md (from -r requirements.txt (line 7))
  Updating ./venv/src/en-vectors-glove-md clone (to en_vectors_glove_md-1.0.0)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/Users/anton164/git/quiki-analysis/fierce-figaro/venv/src/en-vectors-glove-md/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/anton164/git/quiki-analysis/fierce-figaro/venv/src/en-vectors-glove-md/
```

Earlier I did try simply by specifying `en-vectors-glove-md==1.0.0` in requirements.txt, but it led to the following when pushing to heroku (as it couldnt find the dependency):
```
remote:        Collecting en-vectors-glove-md==1.0.0 (from -r /tmp/build_3035bb216d2e650e1a2ff516af335a81/requirements.txt (line 7))
remote:          Could not find a version that satisfies the requirement en-vectors-glove-md==1.0.0 (from -r /tmp/build_3035bb216d2e650e1a2ff516af335a81/requirements.txt (line 7)) (from versions: )
remote:        No matching distribution found for en-vectors-glove-md==1.0.0 (from -r /tmp/build_3035bb216d2e650e1a2ff516af335a81/requirements.txt (line 7))
```

Any tips on how to install the vectors model via pip requirements.txt?

**Comment by anton164** [comment]
Daamn, it looks like all I had to do was simply list it as 
`https://github.com/explosion/spacy-models/releases/download/en_vectors_glove_md-1.0.0/en_vectors_glove_md-1.0.0.tar.gz` 😞

**Comment by ines** [comment]
Thanks for updating with your solution!

Sorry this is currently not very clear in the 1.x docs – we've added some [more info on this](http://alpha.spacy.io/docs/usage/production-use#models-download) for v2 alpha – for some background, see #1099.
