### ISSUE TITLE
 AttributeError: module 'collections' has no attribute 'MutableMapping' in python3.10

### ISSUE THREAD

**Issue by DSLituiev** [explosion/spaCy#11339]
## How to reproduce the behaviour

`import spacy` in a fresh installation returns

`AttributeError: module 'collections' has no attribute 'MutableMapping'`

This seems to be related to be a compatibility issue: 
https://stackoverflow.com/questions/70943244/attributeerror-module-collections-has-no-attribute-mutablemapping

## Your Environment
`python -m spacy info --markdown` fails with the error above

* Operating System: M1 Mac
* Python Version Used: python3.10
* spaCy Version Used: 3.2.4
* Environment Information: conda

**Comment by DSLituiev** [comment]
this seems to be a non-spacy issue, but it is aggravated by `medspacy`'s dependency on an earlier `requests`

**Comment by polm** [comment]
Thanks for the report! Even if this wasn't caused by spaCy I can see why it would look like that. Hopefully if it happens to anyone else they'll see this issue.
