### ISSUE TITLE
Comparing clusters of two tokens

### ISSUE THREAD

**Issue by anton164** [explosion/spaCy#1134]
## Your Environment

* Operating System: OS X
* Python Version Used: 2.7
* spaCy Version Used: 1.8.2
* Environment Information: ..

Hey! Im trying to look at the similarity between the brown clusters of two tokens (in broader terms my problem is to cluster similar phrases), but for "shipment" and "shipping" the similarity is unexpectedly 0.

Here's my code:
```python
import spacy
import en_vectors_glove_md

nlp = en_vectors_glove_md.load()

cluster_a = nlp.vocab[nlp(u"shipment")[0].cluster]
cluster_b = nlp.vocab[nlp(u"shipping")[0].cluster]

print (cluster_a.vector)
print (cluster_a.similarity(cluster_b))
```

Printing the cluster vector of "shipment" shows that the vector is empty, so I guess I'm approaching this in the wrong way - any tips on how I can work with the brown clusters in spacy? (I was inspired to look at clusters for this problem by https://github.com/explosion/spaCy/issues/276)

**Comment by honnibal** [comment]
The `.similarity()` method defaults to using the word vectors, which are not precisely the same as the  clusters. You can always rebind the cluster IDs to your own clustering, customize the `similarity` method, or set further attributes using the `Underscore` system. Details here: https://spacy.io/usage/vectors-similarity
