### ISSUE TITLE
Missing sentence-terminal punctuation in the default punctuation list of sentencizer

### ISSUE THREAD

**Issue by BLKSerene** [explosion/spaCy#11348]
As previously reported in #4269, the default punctuation list of sentencizer was updated in #4290 (126 code points) and two Chinese full stops were added in #5263 (128 code points).

But it seem that some sentence-terminal punctuations are still missing from the list (now in [spacy.pipeline.sentencizer](https://github.com/explosion/spaCy/blob/3e4cf1bbe1745a55ede0dece31353aebc3f82729/spacy/pipeline/sentencizer.pyx#L38)). I used Unicode Utilities: UnicodeSet and got [a list of 152 code points](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%5B%3ATerminal_Punctuation%3DYes%3A%5D%26%5B%3ASentence_Break%3D%2F%5BAS%5DTerm%2F%3A%5D%5D&g=&i=) in total. Not sure whether updating the default punctuation list would improve the performance of sentencizer or not.

## Expected Output
`default_punct_chars = ['\u0021', '\u002E', '\u003F', '\u0589', '\u061D', '\u061E', '\u061F', '\u06D4', '\u0700', '\u0701', '\u0702', '\u07F9', '\u0837', '\u0839', '\u083D', '\u083E', '\u0964', '\u0965', '\u104A', '\u104B', '\u1362', '\u1367', '\u1368', '\u166E', '\u1735', '\u1736', '\u1803', '\u1809', '\u1944', '\u1945', '\u1AA8', '\u1AA9', '\u1AAA', '\u1AAB', '\u1B5A', '\u1B5B', '\u1B5E', '\u1B5F', '\u1B7D', '\u1B7E', '\u1C3B', '\u1C3C', '\u1C7E', '\u1C7F', '\u203C', '\u2047', '\u2048', '\u2049', '\u203D', '\u2E2E', '\u2E53', '\u2E54', '\u2E3C', '\u3002', '\uA4FF', '\uA60E', '\uA60F', '\uA6F3', '\uA6F7', '\uA876', '\uA877', '\uA8CE', '\uA8CF', '\uA92F', '\uA9C8', '\uA9C9', '\uAA5D', '\uAA5E', '\uAA5F', '\uAAF0', '\uAAF1', '\uABEB', '\uFE52', '\uFE56', '\uFE57', '\uFF01', '\uFF0E', '\uFF1F', '\uFF61', '\U00010A56', '\U00010A57', '\U00010F55', '\U00010F56', '\U00010F57', '\U00010F58', '\U00010F59', '\U00010F86', '\U00010F87', '\U00010F88', '\U00010F89', '\U00011047', '\U00011048', '\U000110BE', '\U000110BF', '\U000110C0', '\U000110C1', '\U00011141', '\U00011142', '\U00011143', '\U000111C5', '\U000111C6', '\U000111CD', '\U000111DE', '\U000111DF', '\U00011238', '\U00011239', '\U0001123B', '\U0001123C', '\U000112A9', '\U0001144B', '\U0001144C', '\U000115C2', '\U000115C3', '\U000115C9', '\U000115CA', '\U000115CB', '\U000115CC', '\U000115CD', '\U000115CE', '\U000115CF', '\U000115D0', '\U000115D1', '\U000115D2', '\U000115D3', '\U000115D4', '\U000115D5', '\U000115D6', '\U000115D7', '\U00011641', '\U00011642', '\U0001173C', '\U0001173D', '\U0001173E', '\U00011944', '\U00011946', '\U00011A42', '\U00011A43', '\U00011A9B', '\U00011A9C', '\U00011C41', '\U00011C42', '\U00011EF7', '\U00011EF8', '\U00016A6E', '\U00016A6F', '\U00016AF5', '\U00016B37', '\U00016B38', '\U00016B44', '\U00016E98', '\U0001BC9F', '\U0001DA88']`

## Your Environment
* Operating System: Windows 10 x64
* Python Version Used: 3.8.10 x64
* spaCy Version Used: 3.2.3

**Comment by adrianeboyd** [comment]
I haven't tested it, but I suspect that the additional symbols are rare enough that they won't make much difference for the languages currently supported by spacy, and the current tokenizer defaults may not treat these symbols as separate affixes, which means that they wouldn't be matched by the sentencizer.

You can always initialize a sentencizer with the exact set of punctuation tokens that you need for a particular language.
