### ISSUE TITLE
Pinning cython version prevents building on PyPy

### ISSUE THREAD

**Issue by mattip** [explosion/spaCy#1136]
Is there a reason you pin cython in requirements.txt to <0.24? This prevents building spaCy on PyPy. The last 0.23 version was 0.23.5 released in March 2016, over a year ago and is missing the goodness of 5 new releases

**Comment by honnibal** [comment]
There was a bug in the way `cpdef enum` declarations worked. It's probably fixed. Would you mind testing the build with latest Cython? I agree I'd like to upgrade.

**Comment by mattip** [comment]
Running
```
pip install -r requirements.txt  
python setup.py build_ext --inplace  
python -mpytest --doctest-modules spacy
```
 like this in a clean virtualenv, on HEAD, on a Ubuntu 16.04 x86_64 machine with no CUDA using stock python 2.7.12, gave me
```
2 failed, 1217 passed, 2484 skipped, 10 xfailed in 171.54 seconds
```
where the failures were
```
[doctest] spacy.language.Language.__call__
[doctest] spacy.tokens.printers.parse_tree
```

After changing requirments.txt to read `cython>=0.25.2`, executing `git clean -x` and then redoing the above, I get exactly the same pytest output.

**Comment by honnibal** [comment]
This is fixed now, thanks!
