### ISSUE TITLE
requests>=2.13 requirements 

### ISSUE THREAD

**Issue by NicolasEhrhardt** [explosion/spaCy#1137]
Hi!

Is there a reason why the ``requests`` package min version ``>=2.13``?
I am asking this because a decent amount of large projects have ranges with a max version lower than 2.13 (``docker-compose`` for instance).

Given that requests is only used for downloading models on github, it is probably ok to drop the min version much below the current version. This change would allow much easier integration with any large project that are usually lacking a little behind with package versions.

Thanks,
-Nicolas

**Comment by ines** [comment]
Ah okay, that's good to know. To be honest, when we add new dependencies, we usually just take the latest(ish) version, i.e. the one we can confirm is definitely compatible, and then use the next major release as the max version.

Considering `requests` is a very standard dependency, and really only used by spaCy's CLI, it should be absolutely no problem to change that. From your perspective, what would be a good version range to ensure compatibility with the projects you're using?

**Comment by NicolasEhrhardt** [comment]
It seems like the ``docker-compose`` folks settled on 2.11.1 as lowest safest. Therefore I am going to suggest this version, which should enable folks to integrate spaCy more easily into their stacks.
