### ISSUE TITLE
Splitting parenthesis or brackets immediately behind/in front of an alphanumeric character

### ISSUE THREAD

**Issue by Gandor26** [explosion/spaCy#1144]
It seems spacy.lang.en cannot split a bracket surrounded by alphanumeric characters or some punctuations.

```
import nltk
import spacy
nlp = spacy.load('en')
pt = nltk.tokenize.TreebankWordTokenizer()
print('  '.join([w.text for w in nlp('descent.[citation needed]fault')]))
print('  '.join([w.text for w in nlp('finished.[citation needed].fault')]))
print('-'*100)
print('  '.join(pt.tokenize('descent.[citation needed]fault')))
print('  '.join(pt.tokenize('finished.[citation needed].fault')))


Out[4]:
descent.[citation  needed]fault
finished.[citation  needed].fault
 -------------------------------------------------------- 
descent.  [  citation  needed  ]  fault
finished.  [  citation  needed  ]  .fault
```
Are there any methods to get brackets out in these cases?

## Your Environment

* Operating System: macOS Sierra 10.12.5
* Python Version Used: 3.6.0
* spaCy Version Used: 1.8.2
* Environment Information:

**Comment by honnibal** [comment]
Interesting!

Probably the best way to fix this would be the `infix_finditer` function in the tokenizer. You can customise this yourself at runtime. The best overview of the tokenizer is here: http://alpha.spacy.io/docs/usage/customizing-tokenizer . If you compile a regex and pass its `.finditer` function to the tokenizer, you should be able to get the case you're working on split correctly.
