### ISSUE TITLE
EN download model is failing due to bad SSL cert for Spacy 1.4 - 1.6

### ISSUE THREAD

**Issue by jstenhouse** [explosion/spaCy#1145]
Spacy versions 1.4 - 1.6 download the english model from https://index.spacy.io/models which currently has a bad SSL cert. Chrome says `NET::ERR_CERT_DATE_INVALID`.

Can the SSL cert be updated? Thanks!

## Your Environment
* Python Version Used: 2.7
* spaCy Version Used: 1.4

**Comment by ines** [comment]
Ah, weird – I feel like we _just_ renewed that. Will have a look at this!

In the meantime, you can always download the old models manually from here: https://github.com/explosion/spacy/releases/tag/v1.6.0

**Comment by ines** [comment]
Can you try again now? Should be fixed!
