### ISSUE TITLE
You can access the NER tags via the `label_` property - see also the [spaCy docs on Named Entity Recognition](https://spacy.io/usage/linguistic-features#named-entities). For more information on the `.spacy` file I recommend the docs on the [Binary Training Format](https://spacy.io/api/data-formats#binary-training) and [`DocBin`](https://spacy.io/api/docbin).

### ISSUE THREAD

**Issue by fariiaakh** [explosion/spaCy#11495]
You can access the NER tags via the `label_` property - see also the [spaCy docs on Named Entity Recognition](https://spacy.io/usage/linguistic-features#named-entities). For more information on the `.spacy` file I recommend the docs on the [Binary Training Format](https://spacy.io/api/data-formats#binary-training) and [`DocBin`](https://spacy.io/api/docbin).

_Originally posted by @rmitsch in https://github.com/explosion/spaCy/discussions/11391#discussioncomment-3606010_

**Comment by polm** [comment]
It looks like maybe this was opened by mistake? If you have questions about the thread you can follow up there.
