### ISSUE TITLE
PROPN (such as John) as the first word of a sentence, with another PROPN in the sentence, does not have an entity type

### ISSUE THREAD

**Issue by AndreaWesterinen** [explosion/spaCy#11523]
## How to reproduce the behaviour
sent1 = "John gave Susan a raise."
sent2 = "John helped Susan to raise money."
sent3 = "John raised money."

Processing:
nlp_sentence = nlp(sent#)
for token in nlp_sentence:
    print(token.morph, token.dep_, token.pos_, token.lemma_, token.ent_type_)

Results for John and Susan:
sent1 => Number=Sing nsubj PROPN John 
                Number=Sing dative PROPN Susan PERSON
sent2 => Number=Sing nsubj PROPN John 
                Number=Sing dobj PROPN Susan PERSON
sent3 => Number=Sing nsubj PROPN John PERSON

## Your Environment
* Operating System:  MacOS Monterey 12.6
* Python Version Used:   3.8
* spaCy Version Used:   3.4.1
* Environment Information:   Transformer model ('en_core_web_trf')

**Comment by adrianeboyd** [comment]
Thanks for the report, a few users have noticed similar issues with first names in v3 models, e.g.: https://github.com/explosion/spaCy/issues/7493#issuecomment-832660445. In the examples I've seen, isolated first names at the beginning of a text are the most likely to be missed, but there are also many example texts where the performance is fine. In general, the points in #3052 about performance of statistical models are good to keep in mind.

The NER architecture has not changed much over the years and the overall NER model performance has also stayed stable, so at this point we're not sure if cases like these are just flukes or if there is a systematic error, possibly introduced in v3 or related to some of the data augmentation.

**Comment by adrianeboyd** [comment]
Wait, it's good I looked at this again. I do think it's an error related to the data augmentation and missing annotation for Biblical names in OntoNotes, where it looks like the missing annotation may not be preserved correctly during augmentation.

Let me take a closer look at the details...

**Comment by adrianeboyd** [comment]
I hope that this issue is resolved by the new English pipelines with version v3.4.1. You can update your pipelines with `spacy download`. In particular Biblical names like "John" and "David" should be annotated more consistently.
