### ISSUE TITLE
How to use Lemmatizer

### ISSUE THREAD

**Issue by oximer** [explosion/spaCy#1154]
I'm currently using the Spacy 2.0 nigthly version.

```
import spacy

pt = spacy.util.get_lang_class('en')
nlp = pt()

print(spacy.__version__)

pt_doc = nlp(u'Dra. deu um presente aos pais de Maria')

for token in pt_doc:
    print(token)

for token in pt_doc:
    print(token.text, token.lemma_, token.pos_, token.tag_, token.dep_,
          token.shape_, token.is_alpha, token.is_stop)
```

```
2.0.0a0
Dra
.
deu
um
presente
aos
pais
de
Maria
(u'Dra', u'', u'', u'', u'', u'Xxx', True, False)
(u'.', u'', u'', u'', u'', u'.', False, False)
(u'deu', u'', u'', u'', u'', u'xxx', True, False)
(u'um', u'', u'', u'', u'', u'xx', True, False)
(u'presente', u'', u'', u'', u'', u'xxxx', True, False)
(u'aos', u'', u'', u'', u'', u'xxx', True, False)
(u'pais', u'', u'', u'', u'', u'xxxx', True, False)
(u'de', u'', u'', u'', u'', u'xx', True, False)
(u'Maria', u'', u'', u'', u'', u'Xxxxx', True, False)
```

The [Documentation](https://alpha.spacy.io/docs/usage/spacy-101) describes that Lemmatization requires a model. In my code, I'm only loading a Language, since there is no Model for Portuguese.

However, when I inspect spaCy/spacy/lang/pt, I can see a Lemmatizer class. 
How can I use it? So, that  token.lemma_ filled.

I couldn't find any example about how to use Spacy without loading a Model. Most of the examples starts with Spacy.load('some_model')

**Comment by vinistig** [comment]
Have the same issue here.

**Comment by ines** [comment]
To explain what's going on here: the lemmatizer is currently run as part of the morphological analysis, which is triggered by the part-of-speech tagger. This is why lemmatization is listed as "requires model".

spaCy v2.0 also supports lookup-based lemmatization via a simple table ([see here for Portuguese](https://github.com/explosion/spaCy/blob/develop/spacy/lang/pt/lemmatizer.py)). But even at the moment, this function is only executed as part of the standard processing pipeline, i.e. only run if there's a model.

**Considering we have the lemmatizer data, this should definitely be implemented as a separate pipeline component for the stable v2.0 release. This way, even if there's no model, the lemma can still be determined if it's found in the lookup table. (I'll tag this issue as enhancement for v2!)**

The simplest (but a pretty hacky) workaround for now would be to just write your own function and use the lookup table to get the lemma for a token's lowercase form, if it's found in the table:

```python
from spacy.lang.pt import Portuguese
from spacy.lang.pt.lemmatizer import LOOKUP

def get_lemma(text):
    return LOOKUP.get(text, text) # if no lemma found, return original text

nlp = Portuguese()
doc = nlp(u'Dra. deu um presente aos pais de Maria')
for token in doc:
    lemma = get_lemma(token.lower_)
    print(lemma)
```

Of course, the above function is a little inconvenient – so instead, you can also wrap it as a [pipeline component](https://alpha.spacy.io/docs/usage/language-processing-pipeline#creating-component) that writes to the token's `lemma_`:

```python
def pt_lemmatizer(doc):
    for token in doc:
        token.lemma_ = LOOKUP.get(token.lower_, token.lower_)

nlp.pipeline.append(pt_lemmatizer) # append component to the pipeline
doc = nlp(u'Dra. deu um presente aos pais de Maria')
```

> I couldn't find any example about how to use Spacy without loading a Model. Most of the examples starts with Spacy.load('some_model')

In spaCy v2.0, `spacy.load` is only for models. To use the language data, you can simply import the `Language` class and initialise it:

```python
from spacy.lang.pt import Portuguese
nlp = Portuguese()
```

**Comment by oximer** [comment]
Ines,

Thank you for your explanation. Now everything make much more sense to me.
I was wondering why I could not use the lemmatizer, but now I understand the pipeline issues.
