### ISSUE TITLE
Access Violation

### ISSUE THREAD

**Issue by blackburn32** [explosion/spaCy#1158]
Hi, I'm trying to train a NER model to pick out new entities (Diagnoses and treatments) using train_new_entity_type.py. I've got a corpus of about 4000 annotated sentences but when I run my data, Python crashes due to an "Access Violation". I'm a bit confused, because this only seems to be happening consistently when I try to train on a large set of data, but when I train on just a few sentences (around 20) the exception is thrown only about half of the time, and the other half of the time the program completes successfully. Have you seen Access Violation exceptions thrown by entity.update before?

Here is the actual exception message I get when Python crashes:
Unhandled exception at 0x00007FF9C25382E9 (ner.cp35-win_amd64.pyd) in python.exe: 0xC0000005: Access violation reading location 0x000001A9B7AFF014.

## Environment
* **Platform:** Windows-10-10.0.14393-SP0
* **spaCy version:** 1.8.2
* **Installed models:** en
* **Python version:** 3.5.2

**Comment by CYUlysses** [comment]
Almost exact same problem encountered here. Difference in versions:

spaCy: 1.9.0
Installed models: en, es
Python version: 3.6.2

**Comment by honnibal** [comment]
This should now be resolved in v2. I expect a release candidate for 2.0.0 should be available this week. In the meantime, you can get the current version from `pip install spacy-nightly`.
