### ISSUE TITLE
Spacy memory leaks

### ISSUE THREAD

**Issue by kaliaanup** [explosion/spaCy#11596]
## How to reproduce the behaviour

self.nlp = spacy.load("en_core_web_sm", disable = ['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner'])
self.nlp.add_pipe('sentencizer')
self.nlp.add_pipe("spacytextblob")

...

subdoc = nlp(sent.text)

The code is running on a streaming platform with a GPU cluster. Thus, Spacy  model gets like 300 millions messages per day to parse through. This is leading to a sharp rise in memory. I read few blogs where Spacy Vocab has been stated as the main culprit. Is there way to provide a parameter to prevent the Spacy Vocab from growing. As of now we are support hard memory limits on containers to restart. I know I can write a code snippet to restart Spacy object but I wish there is a better solution to this.

## Your Environment

* Operating System: AWS GPU Instance
* Python Version Used: 3.7.10
* spaCy Version Used:3.4.0
* Environment Information:

**Comment by adrianeboyd** [comment]
Is the problem CPU memory or GPU memory?

**Comment by kaliaanup** [comment]
The problem is related to the CPU memory. We have a ML model that uses Spacy's input. The model is deployed using a GPU however I am using the CPU version of Spacy. Hence, what we are observing that the GPU memory is constant whereas the CPU memory is slowly increasing. Given the volume, I am running this model and now I see 55% memory has been occupied so far in case of CPU.

**Comment by adrianeboyd** [comment]
Okay, just double-checking that it is likely the vocab issue. The only good option right now is to periodically reload the model. This comment is still up-to-date: https://github.com/explosion/spaCy/issues/10012#issuecomment-1008785462

**Comment by kaliaanup** [comment]
Thanks.  I will continue on reloading aspect and I have questions on that as well.
