### ISSUE TITLE
setting `pymorphy2_lemmatize` vs `pymorphy2_lookup_lemmatize` in UkrainianLemmatizer

### ISSUE THREAD

**Issue by adrianeboyd** [explosion/spaCy#11620]
### Discussed in https://github.com/explosion/spaCy/discussions/11609

<div type='discussions-op-text'>

<sup>Originally posted by **DSLituiev** October 11, 2022</sup>
I would like to run `UkrainianLemmatizer().pymorphy2_lookup_lemmatize()` instead of `UkrainianLemmatizer().pymorphy2_lemmatize()` , as the latter mis-handles lemmatization of certain pronouns.  

I can't quite find where it is called. I cannot see `pymorphy2_lemmatize` mentioned in the config (in `"uk_core_news_lg"`  model), or being called in either `UkrainianLemmatizer` or `RussianLemmatizer`, but assume it can be changed by re-setting the config `"lemmatizer": {'mode': 'pymorphy2', ...}` to  `"lemmatizer": {'mode': 'pymorphy2_lookup',}`.

Here is my attempt that fails:

```python
nlp = spacy.load("uk_core_news_lg")

nlp("якусь")[0].lemma_
# "якусь"

dict(nlp.pipeline)["lemmatizer"].pymorphy2_lemmatize(nlp("якусь")[0])
#  ['якусь']

dict(nlp.pipeline)["lemmatizer"].pymorphy2_lookup_lemmatize(nlp("якусь")[0])
# ['якийсь']

# remove un-used pipeline
nlp.remove_pipe("ner")

old_lemmatizer = nlp.remove_pipe("lemmatizer")

lemmatizer = nlp.add_pipe("lemmatizer", config=
{ #'factory': 'lemmatizer',
 'mode': 'pymorphy2_lookup',
 'model': None,
 'overwrite': True,
  # 'scorer': {'@scorers': 'spacy.lemmatizer_scorer.v1'}
 })


nlp("якусь")[0].lemma_
```

```
  File "/opt/anaconda3/envs/asr/lib/python3.10/site-packages/spacy/lang/ru/lemmatizer.py", line 102, in pymorphy2_lookup_lemmatize
    analyses = self._morph.parse(string)

AttributeError: 'UkrainianLemmatizer' object has no attribute '_morph'

```

I tried adding `nlp.initialize()` but that does not seem to help.

This also does not seem to help `lemmatizer._morph = old_lemmatizer[1]._morph` as it returns empty lemmas: `nlp("якусь")[0].lemma_`

This may relate to a complexity of the [RussianLemmatizer initalization](https://github.com/explosion/spaCy/issues/7124)

Would you advise how to initialize it properly in this setting?</div>

**Comment by DSLituiev** [comment]
per @adrianeboyd : 
> I think the problem is that the pymorphy2_lookup mode isn't accounted for in __init__ in either lemmatizer.

Additional investigation:
Looking at the Lemmatizer call implementation [here](https://github.com/explosion/spaCy/blob/master/spacy/pipeline/lemmatizer.py#L121)

```python
lemmatizer.mode
#  'pymorphy2_lookup'

lemmatizer.lemmatize
#  <bound method RussianLemmatizer.pymorphy2_lookup_lemmatize of <spacy.lang.uk.lemmatizer.UkrainianLemmatizer object at 0x7fa03dc23e40>>

```

The issue seem to be that the wrapper of the pymorphy2 lemmatizer only have a branch for 
[`mode == "pymorphy2"`](https://github.com/explosion/spaCy/blob/master/spacy/lang/uk/lemmatizer.py#L21) but not `"pymorphy2_lookup"`. Changing L21 to following

```python
        if mode in {"pymorphy2", "pymorphy2_lookup"}:
```

does the trick. A related issue is that currently this needs to be done for both `uk` and `ru` to fix it completely. Would it be more elegant to have a generic `pymorphy2` wrapper defined separately with `uk` and `ru` instances?

**Comment by DSLituiev** [comment]
Suggestion would be to place the `PyMorphy2Lemmatizer` in [spacy/pipeline/lemmatizer.py](https://github.com/explosion/spaCy/blob/master/spacy/pipeline/lemmatizer.py#L121) and call it from `ru` and `uk`
