### ISSUE TITLE
Incorrect parsing of conjunction within noun phrases

### ISSUE THREAD

**Issue by chrishmorris** [explosion/spaCy#11634]
The sentence "I buy hamster and gerbil food" is parsed as shown below. Actually food is the correct direct object. Instead, the conj link should connect gerbil to its correct parent hamster, and hamster should have an amod link to food. 

It is hard to assign conjunction correctly. But maybe it is useful to upscore the options where the two co-ordinated terms are of similar weight. It seems possible to recognise that "hamster and gerbil" is more likely than "hamster and [gerbil food]"

![image](https://user-images.githubusercontent.com/8377815/195357540-86ef1f3e-38f7-468d-ba97-1b09b415163f.png)

Spacy is amazing, and gets the correct parsing with impressive frequency. This case is one of the more common errors I encounter. I am parsing biomedical text, and such constructions are common in the corpus.

## Your Environment
- **spaCy version:** 3.0.7
- **Platform:** Linux-5.15.0-48-generic-x86_64-with-glibc2.31
- **Python version:** 3.9.5
- **Pipelines:** en_core_sci_sm (0.4.0)

**Comment by richardpaulhudson** [comment]
Unfortunately such things are a fact of machine-learning life: with unlimited training data, the parser would get this right, but in reality training data is always limited. 
 
The behaviour of the parser is dependent on the model being used. In this case, the model `en_core_sci_sm` is not published by Explosion, but by [allenai](https://allenai.github.io/scispacy/). So I'm closing this issue and would ask you to consider raising an issue with them.
 
One important general tip, though, is to use the largest model available to you if your main concern is accuracy. In this case there is also an `en_core_sci_md` published. It may or may not share this specific behaviour, but should produce fewer errors overall.

**Comment by polm** [comment]
Also just let me link #3052, which is about mistakes like this in general.
