### ISSUE TITLE
Extract noun without possession

### ISSUE THREAD

**Issue by joeyism** [explosion/spaCy#1166]
Hi,

I'm trying to extract nouns without possession. My code is as follows

```python
import spacy
nlp = spacy.load("en")
sample_text = "John's company Label, Inc. is about to file for bankrupcy"
doc= nlp(unicode(sample_text))
for noun in doc.noun_chunks:
    print noun
```

And the result is

```
John's company Label
Inc.
bankrupcy
```

I was wonder what I need to do to get `John` and `company` into their own noun chunk, and have `Label, Inc.` as a noun chunk

**Comment by honnibal** [comment]
You can customize the noun chunks behaviour by writing to the `noun_chunks_iterator` attribute of the `Doc` object. Your function will then by called by `doc.noun_chunks`. You'll want to add a function that sets the iterator to the pipeline, to run after the parser. The following should work:

```python

def my_noun_chunks(doc):
    # Your logic here
    yield span

def customize_noun_chunks(doc):
    doc.noun_chunks_iterator = my_noun_chunks
    return doc

nlp.add_pipe(customize_noun_chunks, after='parser')
```
