### ISSUE TITLE
Creating my own model

### ISSUE THREAD

**Issue by oximer** [explosion/spaCy#1169]
Hey guys,

I'm trying to create new on Model and I'm having some trouble.

I'm basically trying to follow this [link](https://spacy.io/docs/usage/adding-languages#model-directory) and i'm using this [repo](https://github.com/explosion/spacy-dev-resources/blob/master/training)

`
python -m spacy model pt myModel portuguese/word_freq '' portuguese/word_vector.bz2
`

however I'm having trouble to generate vector.bin

>  File "/Users/urbano/Documents/fontes/spacy_18/spaCy/.env/lib/python2.7/site-packages/spacy-1.8.2-py2.7-macosx-10.11-x86_64.egg/spacy/cli/model.py", line 47, in create_model
>     write_binary_vectors(vectors_path.as_posix(), vectors_dest.as_posix())
>   File "spacy/vocab.pyx", line 672, in spacy.vocab.write_binary_vectors (spacy/vocab.cpp:14452)
>   File "spacy/vocab.pyx", line 681, in spacy.vocab.write_binary_vectors (spacy/vocab.cpp:14319)
> ValueError: could not convert string to float: train_countqKU

Here it is my files. One mini sample data, the word frequency that I generated and a word vector that I did using this [code](https://github.com/explosion/spacy-dev-resources/blob/master/training/word_vectors.py)

Files used to reproduce this error
[sample.zip](https://github.com/explosion/spaCy/files/1118139/sample.zip)

**Comment by vinistig** [comment]
Trying to create a model here model.

**Comment by honnibal** [comment]
I think this is a quirk in the Gensim format --- it adds a header to the word vectors file that has to be removed. You could do this in a text editor, or I think someone has a script?

**Comment by mraduldubey** [comment]
`tail -n +2 vector_filename_generated_by_gensim.txt > vector_filename_generated_by_gensim.new && mv -f vector_filename_generated_by_gensim.new vector_filename_generated_by_gensim.txt`
 will remove the header added to these files by gensim. 
I would advise against using text editors to edit these files because when files are large they can take considerable time and may even hang the system.

**Comment by ines** [comment]
Update: spaCy v2.0 comes with a lot of improvements around storing, managing and customising word vectors, including a new `Vectors` class. See this page for more details: https://spacy.io/usage/vectors-similarity#custom

There's also a new [`vocab` command](https://spacy.io/api/cli#vocab) to help you compile a vocabulary from a JSON-formatted lexicon file.
