### ISSUE TITLE
The floret demo projects fail 

### ISSUE THREAD

**Issue by mbrunecky** [explosion/spaCy#11691]
## How to reproduce the behaviour
clone the floret_vectors_demo (or the floret_fi_core_demo)
run the project

Spacy3\floret_vectors_demo>py -m spacy project run tokenize-oscar

```
=============================== tokenize-oscar ===============================
Running command: 'L:\Work_L\ML\Spacy3\Scripts\python.exe' scripts/tokenize_dataset.py en unshuffled_deduplicated_en 1000 corpus/unshuffled_deduplicated_en.1000.tok.txt --n-process=8
Traceback (most recent call last):
  ...
  File "L:\Work_L\ML\Spacy3\floret_vectors_demo\scripts\tokenize_dataset.py", line 38, in main
    output_fileh.write(" ".join([t.text for t in sent]) + "\n")
  File "C:\Users\mbrunecky\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-9: character maps to <undefined>
```

For the floret_fi_core_demo, the error is similar, except that it reports the Unicode character in question: U+FEFF (zero-width-non-breaking-space).

spaCy version    3.4.1
Location         L:\Work_L\ML\Spacy3\lib\site-packages\spacy
Platform         Windows-10-10.0.19042-SP0
Python version   3.9.7
Pipelines        en_core_web_lg (3.4.0), en_core_web_md (3.4.0), en_core_web_sm (3.4.0), en_core_web_trf (3.4.0), en_vectors_fasttext_lg (0.0.1), en_vectors_floret_lg (0.0.1), en_vectors_floret_md (0.0.1)

**Comment by adrianeboyd** [comment]
Ah, windows default encodings.

You can fix this by specifying the output file encoding in the script:

```diff
- open(output_file, "w")
+ open(output_file, "w", encoding="utf-8")
```

We will have a look at getting the projects updated.

**Comment by mbrunecky** [comment]
Defaults are difficult to change. And this (opening for write using platform default encoding) must have been there since Python day one. Mark Lutz was on  my team when he was writing the very first book on Python programming, and that was before the "dot-com-crash" (our startup failed quite hard then).

**Comment by adrianeboyd** [comment]
Resolved by: https://github.com/explosion/projects/pull/143
