### ISSUE TITLE
(German) What about using TextBlob lemmatizer in spaCy?

### ISSUE THREAD

**Issue by vaulttech** [explosion/spaCy#1170]
I have seen the code in: (along with the entire thread, on adding a custom lemmatizer)
https://github.com/explosion/spaCy/issues/1085#issuecomment-305178223

and it got me thinking: I actually could adapt the [TextBlob-de](https://github.com/markuskiller/textblob-de/blob/dev/textblob_de/lemmatizers.py) lemmatizer to be used in spaCy, using that code, couldn't I? The problem with the TextBlob-de lemmatizer seems to be that the PoS tagger is not great and often tags the words wrongly (and then the lemmatizer ends up lemmatizing wrong). If I could only take the lemmatization part and ignore the rest, this would work perfectly.

The licences of the both spaCy and TextBlob-de are the same (MIT). The only part where I am not sure is that the code there seems to depend on another library called "pattern" (that seems to be able to make a lot of nice things with German), whose License is BSD (and I am not sure how conflicting the two licences are).

[I am just throwing the idea here to know if there are comments on the topic; but I'll only be able (probably) to try this out on Tuesday/Wednesday]

**Comment by raphael0202** [comment]
Just here to let you know that MIT and BSD licences are compatible ;)

**Comment by aflueckiger** [comment]
You might want to consider this implementation:
https://github.com/WZBSocialScienceCenter/germalemma
It builds also on the pattern package and makes its functionality available for Python 3. Even though it was published only recently, it looks quite promising. I will use it for my own work until a better solution is in sight.

**Comment by ines** [comment]
@vaulttech @aflueckiger 

Quick update: There has been a lot of progress on #1085, including an update to spaCy v2.0 that makes it easy to create custom pipeline components and add your own attributes to the `Doc`, `Token` and `Span`. More details:
* Introducing custom pipelines and extensions for spaCy v2.0 https://explosion.ai/blog/spacy-v2-pipelines-extensions
* Processing pipelines usage guide: https://alpha.spacy.io/usage/processing-pipelines

I've also explained some more [in this comment](https://github.com/explosion/spaCy/issues/1085#issuecomment-335868963), including a suggestion of how a custom lemmatizer could look
