### ISSUE TITLE
UserWarning W123 printed on console after upgrading to 3.4.2

### ISSUE THREAD

**Issue by asquare** [explosion/spaCy#11706]
After upgrading to `3.4.2` I see this warning on the console when a model is loaded. How to fix or silence this?

> spacy/language.py:1895: UserWarning: [W123] Argument disable with value [] is used instead of ['senter'] as specified in the config. Be aware that this might affect other components in your pipeline.

## How to reproduce the behaviour
```python
import en_core_web_sm
lang_model = en_core_web_sm.load()
```

## Your Environment

- **spaCy version:** 3.4.2
- **Platform:** macOS-13.0-arm64-arm-64bit
- **Python version:** 3.10.6
- **Pipelines:** en_core_web_md (3.4.1), en_core_web_sm (3.4.1), en_core_web_lg (3.4.1)

**Comment by polm** [comment]
Thanks for the heads-up, I confirmed this behavior. It's probably related to #11459. 

This only happens for me when using the `en_core_web_sm.load()` style of loading - there's no warning with `spacy.load()`. 

We'll take a look at this, but it should be safe to ignore if the behavior it warns about is what you want. You can silence this the same was as any Python warning, like so:

```
import warnings
# message is a prefix of the actual warning string
warnings.filterwarnings("ignore", message="[W123]")
```

**Comment by loctimize** [comment]
When disabling a component with 
`nlp = spacy.load('en_core_web_sm', disable=['ner'])`
the same error is triggered. Is this issue related?

I tried the fix suggest above with:
```import spacy
import warnings

warnings.filterwarnings("ignore", message="[W123]")

nlp = spacy.load('en_core_web_sm', disable=['ner'])
```

but it did not work. 
I am still getting this warning:


```/somepath/test/spacy/load_model_error_W123.py 
/Users/x/environments/python3.10.8/lib/python3.10/site-packages/spacy/language.py:1895: UserWarning: [W123] Argument disable with value ['ner'] is used instead of ['senter'] as specified in the config. Be aware that this might affect other components in your pipeline.
  warnings.warn(```

Any hint?

**Comment by adrianeboyd** [comment]
#11713 fixed the warning for `en_core_web_sm.load()` but there are still some bugs related to the behavior of `en_core_web_sm.load(disable=["ner"])` in v3.4.2.

**Comment by adrianeboyd** [comment]
To explain a bit more for anyone who comes across this issue, in v3.4.2 `spacy.load("en_core_web_sm", disable=["ner"])` is doing two things:

1. disables `ner`
1. enables `senter`, which is otherwise disabled by default

In spacy v3.4.1 and earlier, the same command only did (1) and not (2). Enabling `senter` as a side effect is a bug, and we are working on addressing this for v3.4.3.
