### ISSUE TITLE
Is it possible to loosen the upper-bound constraint on Typer?

### ISSUE THREAD

**Issue by amitkparekh** [explosion/spaCy#11708]
Hi! I'd like to use spaCy in a project where I already used Typer v0.6.2. 

I cannot install spaCy because spaCy forces all Typer versions to be the following: 
https://github.com/explosion/spaCy/blob/865691d169c3be413007f0d7324e03a7aac3b3cb/requirements.txt#L12

I use Poetry as my dependency manager, which means that it will not allow the inclusion of spaCy as a dependency with the constraint, even if I do not want to use the CLI aspect of spaCy. 

Is there a reason for limiting Typer to <0.5.0, and is it possible to loosen this constraint? 

Thank you!

**Comment by polm** [comment]
Thanks for the note! I am not aware of a specific reason for this, but in general we try to avoid overly open version specifications, and we've had some version-related issues with Typer in the past. 

We'll look into increasing this, but it might take a bit.
