### ISSUE TITLE
spaCy 3.4.2 broken on MacBook Pro with M1 running MacOS Ventura

### ISSUE THREAD

**Issue by asquare** [explosion/spaCy#11704]
I upgraded a MacBook Pro with M1 to MacOS Ventura, tried to reinstall spaCy with `pip install -U 'spacy[apple]'` but running into problems, with the error below. `python -m spacy info --markdown` also prints the same error, from `spacy -> thinc -> tensorflow`.

`python --version`
```
Python 3.10.6
```
`pip list --version |grep spacy`
```
spacy                   3.4.2
spacy-legacy            3.0.10
spacy-loggers           1.0.3
```

`spacy --version`
```
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
...
    from tensorflow.python.framework import dtypes
  File "/opt/homebrew/Caskroom/miniforge/base/envs/.../lib/python3.10/site-packages/tensorflow/python/framework/dtypes.py", line 34, in <module>
    _np_bfloat16 = _pywrap_bfloat16.TF_bfloat16_type()
TypeError: Unable to convert function return value to a Python type! The signature was
	() -> handle
```

**Comment by asquare** [comment]
Retired with a clean conda env and this time it succeeded. Looks like the problem was caused by previously installed versions of `tensorflow-deps` and `tensorflow-macos`.

**Comment by polm** [comment]
Thanks for letting us know how you fixed it!
