### ISSUE TITLE
Possible bug: Spacy does not find subject ('nsubj' relation) for such a sentence 

### ISSUE THREAD

**Issue by pbms** [explosion/spaCy#1176]
For such a sentence: "In no other historical sighting did Halley's comet cause such a worldwide sensation as in its return of 1910-1911."

The ROOT of this sentence is "cause", but when I try to print root_token.children, the subject "Halley's comet " can not be found . The relation between "Halley's comet " and "cause" should be 'nsubj', but it can not be found in the doc.

Surprisingly, when the sentence is tested in displaCy,  there is indeed the relation of 'nsubj' between "Halley's comet " and "cause".

What happened? What causes the difference?
----------------------------------- 
## My Environment
* Operating System: Windows 7
* Python Version Used: 3.6.1
* spaCy Version Used: 1.8.2
* Installed models: en

**Comment by honnibal** [comment]
The model hosted on displacy is a bit old. On some sentences it performs better, but on others it performs worse. The visualiser will be updated soon to use the v2 models -- but currently it's difficult to host versions which require different versions of the library on the same instance.

**Comment by honnibal** [comment]
v2 is released, and models on displaCy are updated accordingly.
