### ISSUE TITLE
spacy.util.fix_random_seed() doesn't work

### ISSUE THREAD

**Issue by marimeireles** [explosion/spaCy#11788]
## How to reproduce the behaviour
1. Try to set a fixed seed.
2. Get randomized results.

Related to https://github.com/explosion/spaCy/issues/3870 that was closed but not solved.

## Your Environment

* Operating System: OSX Monterey
* Python Version Used: 3.11
* spaCy Version Used: 3.3.0
* Environment Information: a mix of conda + pip

Thanks for your work here! :)

**Comment by polm** [comment]
Please provide more details about what you mean by "randomized results" and provide an example of code. Are you training, doing inference, what model...? Without more details there's not much we can do with your report.

Note that if you're using a GPU, some GPU math is not deterministic. See #11169.

**Comment by marimeireles** [comment]
Sorry, well this is a snippet of my code:

```
    fix_random_seed()

    # train the model
    for i in range(20):
        random.shuffle(train_examples)
        for batch in minibatch(train_examples, size=8):
            losses = {}
            nlp.update(batch, sgd=optimizer, losses=losses)

#[...]

train_data_single_label = import_data_for_training()
nlp = create_trained_model(train_data_single_label)
```

If I then proceed to print the predictions of my model `nlp` they will vary by each time I run my program.

**Comment by marimeireles** [comment]
It seems like it's a [long lasting](https://support.prodi.gy/t/training-baseline-scores-vary-despite-random-seed-fixed/2984) issue?

**Comment by polm** [comment]
Thanks for following up. Unfortunately it's still not clear what's going on.

1. Are you using a GPU in the training or inference of your model? (This could be a non-bug source of randomness.)
2. What components are in your pipeline? What are the predictions that are changing? (If it is a bug, we need to know what code it affects.)

We have had issues with reproducibility in the past, but it's not clear that any of the issues you've linked to are related to your current problem. For example, the Prodigy issue you link to was followed up on in #5551 and fixed two years ago.

**Comment by marimeireles** [comment]
Sorry I'm distracted.

>Are you using a GPU in the training or inference of your model? (This could be a non-bug source of randomness.)

No! I'm using CPU here :)

>What components are in your pipeline? What are the predictions that are changing? (If it is a bug, we need to know what code it affects.)

It's a very simple use case, basically a minimal reproducible example.
What I'm trying to do is predict if a sentence belongs to a category. My understanding of setting `fix_random_seed()` is that the prediction for each sentence => category should be the same, but they are not.
For example in one interaction once sentence might be classified as category A with 90% certainty, and in the next iteration 80%.

**Comment by polm** [comment]
Are you using textcat? Can you share your config?

**Comment by marimeireles** [comment]
Yes, I'm using textcat. Sorry, should I have a configuration? 😅
I'm just adding the pipe `    nlp.add_pipe('textcat')`

**Comment by marimeireles** [comment]
Cool!
[Here](https://pastebin.com/rR68xwW7) it is.
Thanks for taking the time to debug this with me.

**Comment by polm** [comment]
Thank you, that gives us a lot of information to work with. I will run some pipelines here to see if we can reproduce the issue.

To clarify a few more things:

- you're loading `en_core_web_sm` or another pipeline to use as a base?
- is inference run in the same process as training, or a separate one?

It's not strictly necessary, but if you could provide a self-contained example of code we could run here to reproduce your issue, that would be helpful.

**Comment by marimeireles** [comment]
I can, but I'd have to anonymize the data first, I could do it later tonight. (I suppose it can be just one string, or so)

I'm using the `en_core_web_lg` model.

>is inference run in the same process as training, or a separate one?

I don't understand what you mean with process... I first train the model and then I use it in real data. This is sequential.

**Comment by polm** [comment]
Running this with our sample projects, with 3.3.0 and 3.4.2, I verified that everything works reproducibly, as expected. 

There are a few other things we can check here, but since this doesn't seem to be a general error, it would help to have a reproducible example. I would expect that this wouldn't be data dependent and you could use any made up data; the main thing would be your training loop and an example of inference. If you can cut out most of the details so they still run and see if there's an issue that might be a good starting point.

> I don't understand what you mean with process... I first train the model and then I use it in real data. This is sequential.

By "process" I mean "operating system process" - for example, do you train a model and then use it in the same Python script, or do you have a separate server?
