### ISSUE TITLE
https://spacy.io/api/annotation redirects to https://spacy.io/api/data-formats

### ISSUE THREAD

**Issue by egbakou** [explosion/spaCy#11785]
## Which page or section is this issue related to?

https://spacy.io/api/annotation
It seems like the page is removed from the doc.

This page was very useful to view the list of NER, POS with its description.

**Comment by adrianeboyd** [comment]
Please don't open duplicate issues. Link to discussion thread: #11784

**Comment by egbakou** [comment]
Thanks !
