### ISSUE TITLE
Low accuracy when training english PoS

### ISSUE THREAD

**Issue by kamac** [explosion/spaCy#1179]
There was an issue on this, but it's been [closed](https://github.com/explosion/spaCy/issues/827).

The problem is that when I'm training an english PoS myself on the UD dataset, the accuracy floats around 33%.

Previous issue suggested populating the vocabulary prior to training, but it doesn't seem to change anything.

My code: https://gist.github.com/kamac/a7bc139f62488839a8118214a4d932f2

## Your Environment

* **spaCy version:** 1.8.2
* **Installed models:**
* **Platform:** Windows-10-10.0.15063-SP0
* **Python version:** 3.5.3

**Comment by honnibal** [comment]
Thanks for the complete example. It looked correct to me, so I actually had to run it and think for a bit. Sorry for the late reply -- I know it's hard to make progress if you have to wait two weeks for answers.

The missing part:

    LEX_ATTR_GETTERS = {
        attrs.LOWER: lambda string: string.lower(),
        attrs.NORM: lambda string: string,
        attrs.SHAPE: orth.word_shape,
        attrs.PREFIX: lambda string: string[0],
        attrs.SUFFIX: lambda string: string[-3:],
        attrs.CLUSTER: lambda string: 0,
        attrs.IS_ALPHA: orth.is_alpha,
        attrs.IS_ASCII: orth.is_ascii,
        attrs.IS_DIGIT: lambda string: string.isdigit(),
        attrs.IS_LOWER: orth.is_lower,
        attrs.IS_PUNCT: orth.is_punct,
        attrs.IS_SPACE: lambda string: string.isspace(),
        attrs.IS_TITLE: orth.is_title,
        attrs.IS_UPPER: orth.is_upper,
        attrs.IS_BRACKET: orth.is_bracket,
        attrs.IS_QUOTE: orth.is_quote,
        attrs.IS_LEFT_PUNCT: orth.is_left_punct,
        attrs.IS_RIGHT_PUNCT: orth.is_right_punct,
        attrs.LIKE_URL: orth.like_url,
        attrs.LIKE_NUM: orth.like_number,
        attrs.LIKE_EMAIL: orth.like_email,
        attrs.IS_STOP: lambda string: False,
        attrs.IS_OOV: lambda string: True
    }
    vocab = Vocab(tag_map=TAG_MAP, lex_attr_getters=LEX_ATTR_GETTERS)

You can see in spacy/tagger.pyx how the tagger gets features for each token:

```python

cdef inline void _fill_from_token(atom_t* context, const TokenC* t) nogil:
    context[0] = t.lex.lower
    context[1] = t.lex.cluster
    context[2] = t.lex.shape
    context[3] = t.lex.prefix
    context[4] = t.lex.suffix
    context[5] = t.tag
    context[6] = t.lemma
    if t.lex.flags & (1 << IS_ALPHA):
        context[7] = 1
    elif t.lex.flags & (1 << IS_PUNCT):
        context[7] = 2
    elif t.lex.flags & (1 << LIKE_URL):
        context[7] = 3
    elif t.lex.flags & (1 << LIKE_NUM):
        context[7] = 4
    else:
        context[7] = 0
```

The crucial thing here is that the word feature is drawn from `t.lex.lower`, i.e. the lower-cased form of the word. This and other static features are cached for each word in the vocabulary, using the `lex_attr_getters` functions. These functions can vary from language-to-language, so the `Vocab` defaults to an empty dict. So, without specifying the `lex_attr_getters`, almost no relevant features are available for the words, giving the low accuracy. This is obviously a bad default, but when the interface was designed, I didn't expect this would become a common entry-point to the library. 

For best accuracy you'll want to have the `cluster` feature available. Training the Brown clusters is a bit of a pain --- the clustering program takes a long time to run.

**Comment by honnibal** [comment]
Updated example here: https://github.com/explosion/spaCy/blob/master/examples/training/train_tagger_standalone_ud.py
