### ISSUE TITLE
Portuguese pull request coming up

### ISSUE THREAD

**Issue by rpietro** [explosion/spaCy#1180]
Hey @ines , my group just finished compiling a 1500+ collection of stop words in Portuguese, and we're now beginning to format the list to comply with what you have at  <https://github.com/explosion/spaCy/tree/master/spacy/pt> . Any specific recommendations before we send you the pull request?

We also plan on tackling the contractions and abbreviations down the road. Just note that we're doing this for Brazilian Portuguese, and so there might be some important differences if you try to use the list for Continental Portuguese.

Besides stop words, contractions, and abbreviations, what else would be required to bring the Portuguese support to the level where you currently have German, Spanish and French?

PS - I just found <https://github.com/explosion/spaCy/blob/master/CONTRIBUTING.md> - will check it out

**Comment by ines** [comment]
Thanks – this is exciting news! 😀 The contributing guide is definitely a good start – if you're making a substantial pull request, don't forget to include the contributor agreement as well.

If you haven't done so already, I'd also recommend checking out [spaCy v2.0 alpha](https://alpha.spacy.io) and maybe even considering making a pull request to the [`develop`](https://github.com/explosion/spacy/tree/develop) branch straight away. This way, we can make sure to include your contribution in the next v2 release.

Some new features in v2 that might be relevant to you and for Portuguese in general:

* **Norm exceptions:** Similar to the tokenizer exceptions, the [norm exceptions](https://alpha.spacy.io/docs/usage/adding-languages#norm-exceptions) let you define alternative spelling etc., which will be set as a token's `NORM` attribute. This ensures that similar words receive similar representations – even if they were not present in the training data. (An example of this would be British vs. American spelling or currency symbols.) This might actually be pretty useful for Brazilian vs. Continental Portuguese.

* **Lexical attributes:** v2 also makes it easier to overwrite [language-specific functions for getting token attributes](https://alpha.spacy.io/docs/usage/adding-languages#lex-attrs), like `like_num` (in v1.x, languages did specify number words, but the data is currently only used in English). This will let you implement those functions for Portuguese as well.

* **Syntax iterators:** [Syntax iterators](https://alpha.spacy.io/docs/usage/adding-languages#syntax-iterators) have been moved to the language data and can now be plugged in via the `Language` subclass. Currently only supports `noun_chunks`, but will be extended in the future. For inspiration, see the [Spanish noun chunks iterator](https://github.com/explosion/spaCy/blob/develop/spacy/lang/es/syntax_iterators.py).

* **Lookup-based lemmatization:** Still needs to be fully implemented as the default lemmatization solution in v2 alpha, but the lookup-tables are already there. [See here](https://github.com/explosion/spaCy/blob/develop/spacy/lang/pt/lemmatizer.py) for the Portuguese one. I'm sure there's also a lot of room for improvement here.

We also always appreciate [language-specific tests](https://alpha.spacy.io/docs/usage/adding-languages#testing-custom) – especially more complex examples. Even if spaCy currently fails on them, having good test coverage for what *should* work is incredibly valuable (for stuff that currently fails but should work, just add a `@pytest.mark.xfail` decorator).

**Comment by rpietro** [comment]
@ines thanks for the info. I went through a good chunk of the documentation, but am unsure how to proceed from here. specifically:

1. the v2.0.0 alpha documentation has an interesting architecture, but as you guys state "the docs reflect the library's intended state on release, not the current state of the implementation." for example, what is described under https://alpha.spacy.io/docs/usage/adding-languages#101 is cool, but it's currently not in the dev branch. I tried to find the implementation for German so that we could emulate it, but I guess it's not there either. which leads to the question: We already got a file with stop words in pt-br, but where/how would you like us to send this to you so that you can incorporate under the alpha release? Or should we submit it to the master branch so that it can be immediately tested and made available to end users? The structure required for the master branch is pretty clear, although as I said it might be best to split pt and pt-br as there are a number of differences even within the limited number of instances you currently have there (they seem to be pt rather than pt-br)
2. out of the complete list of components for the individual language data (tokenizer exceptions, norm exceptions, punctuation rules, character classes, lexical attributes, syntax iterators, lemmatizer, tag map, and morph rules), what else do you need for pt-br? All of it? Asking since we intend to provide you with additional contributions over time.
3. last, by contributor agreement do you mean https://github.com/explosion/spaCy/blob/master/.github/CONTRIBUTOR_AGREEMENT.md ?

thanks

**Comment by victorhos** [comment]
Hi @rpietro, do you continue with the project of adding support for pt-br?

**Comment by ines** [comment]
@rpietro So sorry, I must have missed you comment!

Copying over my comment from #994:
> Update: spaCy v2.0 now has a Portuguese model! 🎉 https://spacy.io/models/pt
> Would be cool to hear some feedback on how it performs on your data. We've also updated the documentation:
> * [Training and updating models](https://spacy.io/usage/training) – if you want to improve and update the `pt` model
> * [Adding languages and language data](https://spacy.io/usage/adding-languages) - if you'd like to contribute to the language data

Will merge this issue with #994 to keep things in one place. Regarding the `pt-br` and `pt-pt` distinction, there's a discussion on this and "sister languages" more generally in #1308.
