### ISSUE TITLE
V2: Adding new entity NER

### ISSUE THREAD

**Issue by ankesh-pandey** [explosion/spaCy#1183]
Hi,
I want to train spacy's NER to detect companies and i have a dataset of 10,000 companies. should my training data be just these company names or should i surround them with artificial sentences? I wanted to ask how spacy's NER model (V2) will react to both of these situations?
is it possible to generate training data for NER if we just have the entities without any running text?

Thanks

**Comment by oxymor0n** [comment]
from what I understand, spacy's NER learns to recognize entities from a whole sequence of tokens and tags. If you have an exhaustive list of company names, maybe [Matcher](https://spacy.io/docs/api/matcher) would be a more straight-forward solution?

**Comment by ankesh-pandey** [comment]
Hi,
Thanks for a reply. I am aware of a Matcher-based solution but it would not be scalable. I was just wondering whether it is possible to generate custom data to train NER model or we have to depend on OntoNotes Release 5.0 like datasets only.
