### ISSUE TITLE
Can not serialize and deserialize Doc

### ISSUE THREAD

**Issue by oliverdain** [explosion/spaCy#1187]
to_bytes and from_bytes does not appear to work correctly:

```
In [310]: type(d)
Out[310]: spacy.tokens.doc.Doc

In [311]: d
Out[311]: Mis amigas y yo necesito ayudar.

In [312]: d[0].tag_
Out[312]: 'DET__Number=Plur|Number[psor]=Sing|Person=1|Poss=Yes|PronType=Prs'

In [313]: b = d.to_bytes()

In [314]: b
Out[314]: b'\x0f\x00\x00\x00\x07\x00\x00\x00\xb5lq\xcfy\xe1\x85\xde\xd8g?'

In [315]: type(nlp)
Out[315]: spacy.es.Spanish

In [316]: type(nlp.vocab)
Out[316]: spacy.vocab.Vocab

In [317]: len(nlp.vocab)
Out[317]: 1230023

In [318]: d2 = Doc(nlp.vocab)

In [319]: d2.from_bytes(b)
Out[319]: Mis amigas y yo necesito ayudar.

In [320]: d2
Out[320]: Mis amigas y yo necesito ayudar.

In [321]: d2[0]
Out[321]: Mis

In [322]: d2[0].text
Out[322]: 'Mis'

In [323]: d2[0].tag_
Out[323]: ''

In [324]: d2[0].tag
Out[324]: 0
```

Note that I get the document and tokens back after `from_bytes` but the tags are missing. I get the same result via pickle.

The following is the output of `python -m spacy info --markdown`. However, the installed models bit is incorrect. I installed `es_core_web_md-1.0.0.tar.gz` via pip and it works fine.

## Info about spaCy

* **Python version:** 3.5.2
* **Installed models:**
* **Platform:** Darwin-15.6.0-x86_64-i386-64bit
* **spaCy version:** 1.8.2

**Comment by honnibal** [comment]
Pickle is now fixed on develop, for both the `Language` class and the `Doc`. :tada:

Pickling should be quite fast, with no redundant copies of the `Vocab` --- so you can pickle a list of `Doc` objects, and it'll do the right thing and only have one copy of all the shared data.
