### ISSUE TITLE
Would there be any interest in an scikit-learn wrapper for spacy?

### ISSUE THREAD

**Issue by oxymor0n** [explosion/spaCy#1188]
Hi all,

I work for @pagerinc and we love spacy! We use it to generate the NLP features for a lot of our scikit-learn pipelines, so for our convenience we have created a wrapper for spacy that can be used seamlessly as part of any scikit-learn Pipeline or FeatureUnion. 

We'd like to contribute this small piece of code back upstream, so do you think this would be the best place for it?

Best,
William

**Comment by honnibal** [comment]
Thanks! That sounds good. I think this is an example of a workflow we haven't been using ourselves, but is probably relevant to lots of others. Do you want to open a PR so I can take a look, and we can discuss further?

**Comment by ines** [comment]
Quick update: We've thought a lot about how to best provide wrappers for other libraries, and we've decided on implementing them as wrapper classes in Thinc. The wrappers will "translate" PyTorch, TensorFlow or scikit-learn models to Thinc's API so they can be plugged into spaCy. There's more discussion on this on the CoNLL thread #2011 ([relevant comment](https://github.com/explosion/spaCy/issues/2011#issuecomment-376482813)).
