### ISSUE TITLE
nlp.pipe returning slightly modified word tags

### ISSUE THREAD

**Issue by morelandjs** [explosion/spaCy#1189]
## The Bug
I'm encountering a bug where nlp.pipe behaves differently on subsequent passes through the same text generator. The tag discrepancies appear to be rare, but nevertheless are there. 

## Info about spaCy

* **spaCy version:** 1.8.2
* **Platform:** Linux-4.11.9-1-ARCH-x86_64-with-arch
* **Python version:** 3.6.1
* **Installed models:** 

## Code which reproduces the bug
```
#!/usr/bin/env python3

import pickle
from pathlib import Path

import en_core_web_sm as en

nlp = en.load()


class ReadText:
    def __init__(self):
        self.file_paths = Path(
                '/home/moreland/AI/wikicorpus-small/'
                ).glob('*.p')

    def __iter__(self):
        for filename in sorted(self.file_paths):
            print('Reading: {}'.format(filename))
            with open(filename, 'rb') as f:
                for article in pickle.load(f):
                    yield article


class Corpus:
    def __iter__(self):
        for article in nlp.pipe(
                ReadText(),
                batch_size=1000,
                n_threads=4):

            yield article
```

First let's test the text generator to make sure we can loop through it multiple times and retrieve the same object. This test passes without any problems.
```
gen_first = [text for text in ReadText()]
gen_second = [text for text in ReadText()]

# this passes (text generator can be repeated)
assert gen_first == gen_second
```

Next let's test that nlp.pipe is deterministic, i.e., that it produces the same object given the same inputs. First we test that it contains the same text (this passes). Then we can check that it produces the same part-of-speech tags (this fails).
```
doc_first = [d for d in Corpus()]
doc_second = [d for d in Corpus()]

# This passes (document text is the same)
assert str(doc_first) == str(doc_second)

tags_first = []
for article in doc_first:
    for sentence in article.sents:
        tags_first.extend([w.tag_ for w in sentence])

tags_second= []
for article in doc_second:
    for sentence in article.sents:
        tags_second.extend([w.tag_ for w in sentence])

# This DOES NOT pass. Some tags change on the second pass?
assert tags_first == tags_second
```

## What's broken
**Unfortunately, `tags_first != tags_second` although they should be the same!**

The tag which flipped was `word.tag_ = 'MD'` on the first pass and `word.tag_ = 'UH'` on the second pass.

**Comment by honnibal** [comment]
Interesting bug! The `Tagger` should always respect preset tags, see here: https://github.com/explosion/spaCy/blob/v1.8.2/spacy/tagger.pyx#L207

So I'm not sure what's happening. My best guess is that somehow the first pass has the tag set but not the `.pos` attribute. Perhaps the tag is set by a special case rule, or something? Then in the second pass, the tagger somehow conditions on different information, flipping the decision.

**Comment by honnibal** [comment]
This should be fixed in recent versions. The problem was that some of the special-case rules assigned only `.pos` and `.lemma` attributes, but not `.tag`. This has been corrected.
