### ISSUE TITLE
Wrong Results of Dependency Parsing.

### ISSUE THREAD

**Issue by accenture-ops-ai-tsunghan** [explosion/spaCy#1190]
Here is my input sentence:
Spicy has average $5,430 of average inventory and cost_of_sales of $32,100.

Below is my code:
```
import spacy
nlp = spacy.load('en')
sen = nlp(u'Spicy has average $5,430 of average inventory and cost_of_sales of $32,100.')
print([(w, w.head) for w in sen])
```
Below is the output:
[(Spicy, has), (has, has), (average, 5,430), ($, 5,430), (5,430, has), (of, 5,430), (average, inventory), (inventory, of), (and, inventory), (cost_of_sales, inventory), **(of, inventory)**, ($, 32,100), (32,100, of), (., has)]

According to the dependency parsing rules, the head of the second 'of' should be 'cost_of_sales.' But in this case, the output showed that the head of the token 'of' became 'inventory,' which is incorrect. I also check the parsing result on displaCy Dependency Visualizer, the result there is correct. So, I don't know why the  result got from the program is inconsistent with the result generated by online Visualizer as well.

Is there any possibility to fix the incorrect parsing results?
Thanks a lot in advance.

## Your Environment

* Operating System: Ubuntu 14.04
* Python Version Used: 2.7.13
* spaCy Version Used: 1.8.2
* Environment Information: anaconda2

**Comment by honnibal** [comment]
Apologies for letting this go unanswered.

The visualiser is now up-to-date with the new v2 release, which gets the sentence correct: https://demos.explosion.ai/displacy/?text=Spicy%20has%20average%20%245%2C430%20of%20average%20inventory%20and%20cost_of_sales%20of%20%2432%2C100.&model=en&cpu=1&cph=1
