### ISSUE TITLE
Incorrect POS tagging, and Incorrect Dependency Parsing as a Result

### ISSUE THREAD

**Issue by AnubisSQLi** [explosion/spaCy#1192]
Incorrect POS tagging, and Incorrect Dependency Parsing as a Result
--Code--
```
from spacy.en import *
nlp = English()
doc = nlp(u'is art real')
for z in doc:
    print(z.orth_ + " | " + z.tag_ + " | " + z.dep_)
```
--Output--
```
is | VBZ | aux
art | NN | ROOT
real | RB | dobj
```
--Expected Output--
```
is | VBZ | ROOT
art | NN | compound
real | JJ | acomp
```

Why is this happening?

## Your Environment

* Operating System: Linux Redhat
* Python Version Used: 2.7
* spaCy Version Used: Most Recent

**Comment by honnibal** [comment]
The v2 parser no longer relies on the POS tagger, and gets this sentence correct: https://demos.explosion.ai/displacy/?text=is%20art%20real&model=en&cpu=1&cph=1
