### ISSUE TITLE
Improve UX around changing displacy's default port

### ISSUE THREAD

**Issue by svlandeg** [explosion/spaCy#11920]
The default port of `displacy.serve` is 5000, which sometimes causes conflicts as described in https://github.com/explosion/spaCy/pull/11793.

`displacy.serve` already has a port keyword arg, but perhaps adding a global setting/env var would be good, too. Additionally then, it would be nice to try and catch port conflicts and throw a custom spaCy error that tells users how to change the port.

**Comment by zhiiw** [comment]
done

**Comment by polm** [comment]
Thanks for the reminder, I'll close this.
