### ISSUE TITLE
Consider moving from pathlib to pathlib2 (or use one in standard library)

### ISSUE THREAD

**Issue by sginn** [explosion/spaCy#1193]
pip install spacy
pip freeze

pathlib==1.0.1 

ends up in the output.

Would be better to use pathlib2 for standard library compatibility

**Comment by honnibal** [comment]
Looks promising. For now we'll stick to the `pathlib` module, because there's an open issue about failing tests on `pathlib2` that seems to come down to system encodings. If there's no current problem with pathlib, I'd rather wait to switch.
