### ISSUE TITLE
Various incorrect type stubs / annotations

### ISSUE THREAD

**Issue by itssimon** [explosion/spaCy#11975]
Working with spaCy in a type-checked project has uncovered a few wrong type annotations tripping up mypy:

`spacy/tokens/span_group.pyi > SpanGroup`:
- missing `__iter__` method, so `list(span_group)` fails type check but works
- `SpanGroup` should inherit from `Iterable[Span]`, e.g. to allow it to be passed into `filter_spans()`

`spacy/tokens/span.pyi > Span.char_span()`:
- arguments `label` and `kb_id` have type `int` but should be `Union[int, str]` according to documentation

## Your Environment
- **spaCy version:** 3.4.2
- **Platform:** Linux-5.4.204-113.362.amzn2.x86_64-x86_64-with-glibc2.35
- **Python version:** 3.10.6
- **Pipelines:** en_core_web_lg (3.4.0), en_core_sci_md (0.5.1), en_core_sci_sm (0.5.1), en_coreference_web_trf (3.4.0a0), en_core_web_trf (3.4.1), en_core_web_md (3.4.1)

**Comment by polm** [comment]
Thanks for bringing that to our attention, those all sound like annotations we could improve. 

For reference, what version of mypy are you using? I have 0.991 and running it on the source gives no errors on the current master branch.

**Comment by itssimon** [comment]
We're also using mypy 0.991. I guess there's a difference between running mypy on the spaCy codebase and using spaCy in a separate type-checked project.

**Comment by rmitsch** [comment]
Thanks for bringing this up! To clarify:
> missing generic annotation that makes SpanGroup compatible with Iterable[Span]

With "generic annotation" you mean inheriting from `Iterable[Span]`?

**Comment by itssimon** [comment]
> With "generic annotation" you mean inheriting from Iterable[Span]?

Yes, exactly. I've updated the issue description accordingly.

**Comment by rmitsch** [comment]
I see, thanks for the confirmation. This is unfortunately tricky, since `SpanGroup` is a Cython extension type and thus cannot inherit from `Iterable`. We are still thinking about how to best approach this. 

The other issues (missing `__iter__()`, incomplete types for `Span.label`, `Span.kb_id`) are straightforward.
