### ISSUE TITLE
ENTITY recognition skips closing bracket )

### ISSUE THREAD

**Issue by Berowne** [explosion/spaCy#11993]
## How to reproduce the behaviour
#%pip install en_core_web_lg
import spacy
from spacy import displacy
nlp = spacy.load('en_core_web_lg') 
doc = nlp("Find the entity with closing bracket. HyperTree Proof Search (HTPS) able to solve International Math Olympiad (IMO) problems" )
displacy.render(doc, style="ent", jupyter=True)
print( [e.text for e in doc.ents])

>>> ['HyperTree Proof Search (', 'International Math Olympiad (']

SHOULD BE

.>>> ['HyperTree Proof Search', 'International Math Olympiad']

## Your Environment
* Operating System: AWS LINUX
* Python Version Used: 3.8
* spaCy Version Used: 3.0.6

**Comment by Berowne** [comment]
or falsely includes first bracket actually...

**Comment by adrianeboyd** [comment]
For expectations related to statistical models and mistakes, see the top post in #3052 for a general discussion.
