### ISSUE TITLE
spacy-clausie problem

### ISSUE THREAD

**Issue by Abelcanc3rhack3r** [explosion/spaCy#11992]
### Discussed in https://github.com/explosion/spaCy/discussions/11991

<div type='discussions-op-text'>

<sup>Originally posted by **Abelcanc3rhack3r** December 19, 2022</sup>
Hi,
I have a problem running spacy-clausie:
https://spacy.io/universe/project/spacy-clausie

I installed spacy-clausie by running: `python -m pip install git+https://github.com/mmxgn/spacy-clausie.git`
Then I ran the code in the example:
```
import spacy
import claucy

nlp = spacy.load("en_core_web_sm")
claucy.add_to_pipe(nlp)

doc = nlp("AE died in Princeton in 1955.")

print(doc._.clauses)
```

I got the error:
Traceback (most recent call last):
  File "/home/yichen/PycharmProjects/openai_codex/NLP_labelling/dependency_rel/claucy.py", line 2, in <module>
    import claucy
  File "/home/yichen/PycharmProjects/openai_codex/NLP_labelling/dependency_rel/claucy.py", line 5, in <module>
    claucy.add_to_pipe(nlp)
AttributeError: partially initialized module 'claucy' has no attribute 'add_to_pipe' (most likely due to a circular import)

How do I solve this problem?

Thanks
</div>

**Comment by polm** [comment]
Please don't open duplicates, we can discuss this in #11991.
