### ISSUE TITLE
[Documentation Request] Increasing Named-Entity Specificity 

### ISSUE THREAD

**Issue by emcenrue** [explosion/spaCy#120]
I'm attempting to extract all named-entities from the document's I am parsing. However, there have been some errors that seem like they could be decreased with a bit of logic on my side. For example, 'Bush' comes back as a type 'PERSON' when it's part of a location, 'Bush International Airport'. Could you please suggest a method for accomplishing this? Thank you!

**Comment by honnibal** [comment]
https://github.com/honnibal/spaCy/blob/master/examples/matcher_example.py
https://github.com/honnibal/spaCy/blob/master/lang_data/en/gazetteer.json

This needs to hit the main documentation, we know --- we'll get there.

**Comment by rw** [comment]
While we're talking about it, how can I make the NER disambiguate between Amazon (the company) and Amazon (the rainforest)? They are both NNP.

(Maybe I should open a separate issue for this.)
