### ISSUE TITLE
Wrong sentence segmentation

### ISSUE THREAD

**Issue by jofatmofn** [explosion/spaCy#1201]
Looks like a bug. Consider the text
`This is obviously a bug. I think this needs to be fixed.`
With the code
```
nlp = spacy.load('en')
document = nlp(input_text)
```
I am getting a single sentence (expected 2 sentences). Same is the case with
`This is a little tricky. I think the problem is bigger than what we think.`

I tried identifying a pattern like POS 'JJ' or 'NN' followed by '.' followed by 'PRP', so that I can preprocess before the parser, but I am not successful. Also, it is taking time. Could you please have a look and suggest.

* **Python version:** 2.7.12
* **Platform:** Linux-4.4.0-83-generic-x86_64-with-Ubuntu-16.04-xenial
* **spaCy version:** 1.8.2
* **Installed models:** en

**Comment by jofatmofn** [comment]
Yes, that is the expectation. However, I am getting:
This is not a bug. I think this needs to be fixed.

**Comment by jofatmofn** [comment]
I had been using en_core_web_**sm**-1.2.0 so far. Today I tried en_core_web_**md**-1.2.0 and the segmentation is proper.

**Comment by aurelien-clu** [comment]
I also found a sentence segmentation issue using fr_depvec_web_lg (en_core_web_md works):
```
import fr_depvec_web_lg
import en_core_web_md

fr_nlp = fr_depvec_web_lg.load()
en_nlp = en_core_web_md.load()

# translation: 'Here is a sentence. Here is another one.' (note: in French the verb is omitted)
text = u'Ceci est une phrase. En voila une autre.'
fr_doc = fr_nlp(text)
en_doc = en_nlp(text)

# here sentences are not split
print("FR - incorrect")
for sentence in fr_doc.sents:
    print("\t" + str(sentence.text))

print("\nENG - correct")
# here sentences are split
for sentence in en_doc.sents:
    print("\t" + str(sentence.text))
```

```
FR - incorrect
	Ceci est une phrase. En voila une autre.

ENG - correct
	Ceci est une phrase.
	En voila une autre.
```

**Comment by honnibal** [comment]
Fixed in v2

https://demos.explosion.ai/displacy/?text=This%20is%20obviously%20a%20bug.%20I%20think%20this%20needs%20to%20be%20fixed.&model=en&cpu=1&cph=1

https://demos.explosion.ai/displacy/?text=Ceci%20est%20une%20phrase.%20En%20voila%20une%20autre.&model=fr_core_news_sm&cpu=1&cph=1
