### ISSUE TITLE
Sentencizer fails to set is_sent_start on the correct token

### ISSUE THREAD

**Issue by NixBiks** [explosion/spaCy#12022]
I have found a bug where the sentencizer sets `token.is_sent_start` to `True` on the second token compared to where it should be.

## How to reproduce the behaviour

Create a blank model, add the `Sentencizer` and add new sentences on `;`. In the following example I'd expect `The` and `(` to be the start of the two sentences but instead I get `The` and `b`. Isn't that a bug or do I miss something?

```py
import spacy


nlp = spacy.load("blank:en")
nlp.add_pipe("sentencizer", config={"punct_chars": [";"]})
text = "The Company's working capital needs; (b) EBITDA"

start_token_for_each_sentence = [t.text for t in nlp(text) if t.is_sent_start]
print(start_token_for_each_sentence)
> ['The', 'b']
```

I have checked the tokenization which is (so that should be fine)
```py
['The', 'Company', "'s", 'working', 'capital', 'needs', ';', '(', 'b', ')', 'EBITDA']
```

## Info about spaCy

- **spaCy version:** 3.4.4
- **Platform:** macOS-13.0.1-arm64-arm-64bit
- **Python version:** 3.10.6

**Comment by NixBiks** [comment]
I guess the issue is due to [this line](https://github.com/explosion/spaCy/blob/90896504a5dba1babac04a2b88662179409ae006/spacy/pipeline/sentencizer.pyx#L110) where `not token.is_punct` is required in order to set `token.is_sent_start = True`. I see why you would require that but it still feels like a wrong output here?

**Comment by polm** [comment]
Thanks for bringing this up, that does look weird, and it felt like it might be wrong to me. However, I tried changing the code and that caused [one test](https://github.com/explosion/spaCy/blob/f3a928cb4b8967a0077c1762eced7932c5be1c3d/spacy/tests/pipeline/test_sentencizer.py#L72) to fail, which brought up this case:

> "Nice!" I am happy.

The comments make it clear that's the reason for the `is_punct` check. In this case, the intent is that while the quote isn't a sentence-ending piece of punctuation, it should go with the preceeding sentence. 

It's good to have a counter-example to this behaviour - it may be that we really just want to check for quotes or something here. 

As a short-term workaround, some things you might try:

1. Manually adjust sentence start positions with parentheses like this in a special component for that purpose.
2. Change parentheses to not be punctuation. You can do this by redefining `is_punct` in the `lex_attrs` using a [custom language](https://spacy.io/usage/linguistic-features/#language-subclass).

**Comment by polm** [comment]
Thanks again for bringing this to our attention. After taking a look at it again, for now we want to stick with the current behavior. 

The main consideration here is that however we define the logic here, it won't work for someone, and writing a custom component to get full control isn't that hard. While we could change this to add a flag, we generally try to avoid that, as flags themselves can be confusing and brittle, while still failing to cover all possible use cases.

**Comment by NixBiks** [comment]
I agree. Thanks for the update and have a great day
