### ISSUE TITLE
Can't load spaCy transformer models on K8s, hangs indefinitely

### ISSUE THREAD

**Issue by mikeburnssh** [explosion/spaCy#12052]
Hello, we're trying to run spaCy transformer models (trf) on K8s but upon trying to load the model it hangs indefinitely. The code + models run fine locally, it's just on K8s that they won't load up. Standard models (ie: lg, sm) load up fine on K8s. The intent is to query them via a FastAPI service.

## How to reproduce the behaviour
```
import spacy
from spacy.cli import download
import torch

download("en_core_web_trf")
torch.set_num_threads(1)
print("Starting model load")
nlp = spacy.load("en_core_web_trf")
print("All done!")
```
On K8s, this code prints "Starting model load" and then never prints "All done" nor exits, throws exceptions, etc. 

`torch.set_num_threads(1)` is used to try to mitigate any issues with OpenMP as per [this thread](https://github.com/explosion/spaCy/issues/8554#issuecomment-872458274) but to no avail. That issue seemed different in that problems occurred at query time, not load time. This issue occurs regardless of this piece of code.

## Your Environment

* Operating System: Linux Ubuntu on AWS EC2
* Python Version Used: 3.9.6
* spaCy Version Used: 3.4.4
* Environment Information: K8s is running 8Gb memory + 2 CPU cores per pod
* spacy-transformers==1.1.9
* transformers[torch]==4.25.1
* torch==1.13.1
* fastapi==0.75.0

The memory usage on the pod initially spikes and then rolls back to around 30mb where it hangs. It does not appear to be an OOM issue since there's 8gb of overhead that is never being reached. I suspected it was something to do with OpenMP based on other issues I'd seen here but those seemed to regard query time and were resolved with `torch.set_num_threads(1)`, which this is not. Let me know if there's any other information that I can provide.

**Comment by polm** [comment]
Sorry you're having trouble with this. Given that it's hanging it's kind of hard to be sure exactly what's going wrong, but a couple of things come to mind.

Generally we don't recommend downloading and pretrained pipelines and then loading them in the same process. Our pipelines rely on entry points in several places, and the way those work when they're modified in-process is kind of wonky. For example, if you run `spacy download` and you're missing any dependencies (like `spacy-transformers`), those will be installed at that point, but the way that works in a single process is unreliable. 

To rule out any errors related to that, is it possible for you to download/install the pipeline in another process first?

**Comment by mikeburnssh** [comment]
Hey @polm, thanks for the quick response. I removed the spacy.cli download calls out into separate install commands prior to this script per your recommendation but unfortunately the issue remains as before. That is good context to know though.

I'm playing with Docker now try see if there are any parameters that I can change to affect the outcome but let me know if there are any other thoughts you have or information I can provide that would help debug.

**Comment by polm** [comment]
Well, glad we were able to rule out the download / install issue at least.

If it's hanging, the best thing to do would be to kill it while hung to get a stack trace - that would show us where it's hanging, which would help investigating. I'm not sure how easy that is to do in K8S, so the easiest alternative would be to add debugging statements to spacy-transformers, specifically in the component code [here](https://github.com/explosion/spacy-transformers/blob/cdf122ed8064e4f5062c5971df4949e34f209011/spacy_transformers/pipeline_component.py#L107). The first thing to check would be if `__init__` and `from_disk` are working OK, though I don't see anything in them that looks like it would cause a hang. 

spacy-transformers has some Cython, but if you find it difficult to build for any reason you can modify the pure-python files (like the linked component code) in-place.

**Comment by polm** [comment]
Going to close this since we don't have enough information to debug it at the moment, but if you have a stack trace or more info, feel free to follow up here or open a new issue.

**Comment by polm** [comment]
Thanks for the update, glad to hear you figured it out!
