### ISSUE TITLE
Retraining Spacy Word Vector Model / Spacy word vectors in word2vec format

### ISSUE THREAD

**Issue by anton164** [explosion/spaCy#1208]
Hey, loving Spacy so far! 😄 

For my use case, we don't have enough data to train our own word embeddings, so we'd like to retrain the spacy word vectors on our corpus. Are your vectors available in word2vec format?

Otherwise, could you perhaps share how you trained the word vectors so that we could re-do that? In the docs it says that you've used the Glove vectors, but I've downloaded those locally (Glove 6B 300d) and they don't look to be the same, as they are all lower-cased (while spacy word embeddings contain uppercased words).

**Comment by honnibal** [comment]
There are several GloVe vector models available from the GloVe site --- you want the large common crawl vectors, which aren't case sensitive.

I'm not sure how well resuming training on pre-trained word vectors works though? That's an interesting idea, but it'll likely take some experimentation to get it right.

**Comment by mraduldubey** [comment]
@honnibal  Retraining pre-trained vectors works well enough, however the result depends upon the source. And it is not a new idea either, `gensim` module allows retraining of pre-trained vector via `word2vec`.
