### ISSUE TITLE
Support for numpy.unicode_ type

### ISSUE THREAD

**Issue by r-wheeler** [explosion/spaCy#1211]
According to the numpy dtype docs, numpy.unicode_ is equivalent to pythons built in unicode type (https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html) , however when trying to do something like the following

```
c = np.atleast_1d(u'this test')
[d for d in parser.pipe(c)]
```
Results in:

TypeError: Argument 'string' has incorrect type (expected unicode, got numpy.unicode_)

If you're looking for help with your code, consider posting a question on StackOverflow instead:
http://stackoverflow.com/questions/tagged/spacy -->

## Your Environment

* **Python version:** 2.7.13
* **Platform:** Darwin-16.6.0-x86_64-i386-64bit
* **spaCy version:** 1.8.2
* **Installed models:** en

**Comment by honnibal** [comment]
Hmm, I'd hoped to make this work with a Cython fused type, but it seems numpy doesn't offer a type definition for its unicode_ type. I could add a type conversion on the API boundary, for pipe, `__call__`, etc. I'm not sure this is a great solution.

Can you just call `unicode` on the text before passing it to spaCy?

**Comment by r-wheeler** [comment]
The text is already unicode. It looks like the real issue is np.array can not be used as a drop in container for list ie

parser.pipe[np.array(["test this"]) 

Solution was to just call .tolist on the ndarray
