### ISSUE TITLE
ro_core_news_lg missing 

### ISSUE THREAD

**Issue by TigranI** [explosion/spaCy#12140]
## How to reproduce the behaviour

Click on 
https://spacy.io/models/ro#ro_core_news_lg

or try

python -m spacy [download](https://spacy.io/api/cli#download) ro_core_news_lg

## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by polm** [comment]
Thanks for letting us know, and sorry about that - this looks like an issue with the wheel build. As a workaround you can use the `.tar.gz` file on [the release page](https://github.com/explosion/spacy-models/releases/tag/ro_core_news_lg-3.5.0). 

We'll work on getting the wheel fixed!

**Comment by adrianeboyd** [comment]
Thanks for the note! I just redid the release steps for `ro_core_news_lg` and it looks like everything was uploaded correctly now. Please let us know if you're still having problems!
