### ISSUE TITLE
Assertion error on French model

### ISSUE THREAD

**Issue by DiegoAgher** [explosion/spaCy#1216]
## Your Environment

* Operating System: 
Debian 4.9.30-2+deb9u2 
* Python Version Used: 
Python 3.5.3
* spaCy Version Used: 
2.0.0a0
* Environment Information: 

## Example with minimal replicable code
```
import spacy 
fr_nlp = spacy.util.get_lang_class('fr')()
fr_nlp('Les amendements acceptables complètement sont les N° 3, 4, 10 et 17.')
```
This results in AssertionError
However, if I delete the degrees character from the string:
```
fr_nlp('Les amendements acceptables complètement sont les N 3, 4, 10 et 17.')
```
...seems like there is no issues.

**Comment by ines** [comment]
Should be fixed in the new French models: https://spacy.io/models/fr
