### ISSUE TITLE
Displacy RTL Support

### ISSUE THREAD

**Issue by SoftFeta** [explosion/spaCy#12195]
Related: #4854

## How to reproduce the behaviour
Use `displacy` to visualise NEL.

![image](https://user-images.githubusercontent.com/9071916/215049898-a3a8a909-5e36-445b-8603-dee5a8cd80cf.png)
The badges are chopped into two, and English help texts inside the badges are occluded by Arabic texts

## Your Environment

- **spaCy version:** 3.4.4
- **Platform:** Windows-10-10.0.25284-SP0
- **Python version:** 3.9.10
- **Pipelines:** en_core_web_lg (3.4.1), es_core_news_lg (3.4.0), es_dep_news_trf (3.4.0), ja_core_news_trf (3.4.0), ko_core_news_lg (3.4.0), pl_core_news_lg (3.4.0), ru_core_news_lg (3.4.0), uk_core_news_trf (3.4.0), xx_ent_wiki_sm (3.4.0), zh_core_web_lg (3.4.0)

**Comment by SoftFeta** [comment]
Also, the whole text is not right-aligned.

**Comment by polm** [comment]
Thanks for the report and screenshot, that does look like a bug. Can you share the code and text you used to create it so we can reproduce it locally?
