### ISSUE TITLE
English stopwords missing the word "seven" 

### ISSUE THREAD

**Issue by ChatBotMatt** [explosion/spaCy#12203]
## How to reproduce the behaviour

Inspect the English stopwords set at https://github.com/explosion/spaCy/blob/master/spacy/lang/en/stop_words.py

## Your Environment
N / A

The English stopwords set contains many numbers, including all the numbers 1-10 (in the form "one", "two", etc.) except for "seven". This seems like an oversight. 

Similarly, it has numbers like "fifty", "ninety", and "hundred", but not "seventy" or "eighty". 

Naturally I don't think all of the numbers should be in it, but presumably sets of the numbers 1-10 and the multiples of 10 up to "hundred" shouldn't be there only partially.

**Comment by adrianeboyd** [comment]
Thanks for the report, that is unexpected. We're planning to remove the default stop word lists in spacy v4, so at this point I think we won't plan any more changes to the current English list.

We feel that it's better for users to maintain stop word lists that are suitable for their particular tasks than for us to try to provide general-purpose lists. These lists are difficult for us to maintain well, and even more so for languages the maintainers are less familiar with than English.

If you need to, you can customize stop words like this:

* custom language: https://spacy.io/usage/linguistic-features#language-subclass
* custom training/package: https://spacy.io/usage/training#custom-code-nlp-callbacks
