### ISSUE TITLE
RuntimeError: from_dlpack received an invalid capsule.

### ISSUE THREAD

**Issue by tassosblackg** [explosion/spaCy#12221]
## How to reproduce the behaviour
```
 import spacy
 nlp = spacy.load('en_core_web_trf')
 tokens1 = nlp("My string")
```

## Your Environment

* Operating System: Ubuntu 20.04 LTS
* Python Version Used: Python 3.8.10
* spaCy Version Used: 3.5.0
* Environment Information:

Full Error:
>RuntimeError: from_dlpack received an invalid capsule. Note that DLTensor capsules can be consumed only once, so you might have already constructed a tensor from it once.

**Comment by adrianeboyd** [comment]
Some combinations of torch and numpy don't work correctly together when the torch release is much older than the numpy release, see: https://github.com/explosion/thinc/issues/741
