### ISSUE TITLE
Unable to load spacy model linked by a path

### ISSUE THREAD

**Issue by bdewilde** [explosion/spaCy#1223]
I've downloaded spacy model files manually and would like to link them to convenient shortcuts. Despite a message affirming that all is well, I am not able to successfully load the model.

```
$ python -m spacy link /Users/burtondewilde/Downloads/en_core_web_sm-1.2.0.tar.gz en --force

    Linking successful

    /Users/burtondewilde/Downloads/en_core_web_sm-1.2.0.tar.gz -->
    /Users/burtondewilde/.pyenv/versions/spacy-test/lib/python2.7/site-packages/spacy/data/en

    You can now load the model via spacy.load('en')

$ ipython
Python 2.7.10 (default, Sep 20 2015, 19:14:00)
Type "copyright", "credits" or "license" for more information.

IPython 5.4.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import spacy

In [2]: spacy.load('en')
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-9b76cafeffa1> in <module>()
----> 1 spacy.load('en')

/Users/burtondewilde/.pyenv/versions/2.7.10/envs/spacy-test/lib/python2.7/site-packages/spacy/__init__.pyc in load(name, **overrides)
     35         data_path = model_path.parent
     36         model_name = ''
---> 37     meta = util.parse_package_meta(data_path, model_name, require=False)
     38     lang = meta['lang'] if meta and 'lang' in meta else name
     39     cls = util.get_lang_class(lang)

/Users/burtondewilde/.pyenv/versions/2.7.10/envs/spacy-test/lib/python2.7/site-packages/spacy/util.pyc in parse_package_meta(package_path, package, require)
    116     # empty string in spacy.load() if user supplies full model path.
    117     location = package_path / package / 'meta.json'
--> 118     if location.is_file():
    119         return read_json(location)
    120     elif require:

/Users/burtondewilde/.pyenv/versions/2.7.10/envs/spacy-test/lib/python2.7/site-packages/pathlib.pyc in is_file(self)
   1200         """
   1201         try:
-> 1202             return S_ISREG(self.stat().st_mode)
   1203         except OSError as e:
   1204             if e.errno != ENOENT:

/Users/burtondewilde/.pyenv/versions/2.7.10/envs/spacy-test/lib/python2.7/site-packages/pathlib.pyc in stat(self)
   1049         os.stat() does.
   1050         """
-> 1051         return self._accessor.stat(self)
   1052
   1053     def owner(self):

/Users/burtondewilde/.pyenv/versions/2.7.10/envs/spacy-test/lib/python2.7/site-packages/pathlib.pyc in wrapped(pathobj, *args)
    344         @functools.wraps(strfunc)
    345         def wrapped(pathobj, *args):
--> 346             return strfunc(str(pathobj), *args)
    347         return staticmethod(wrapped)
    348

OSError: [Errno 20] Not a directory: '/Users/burtondewilde/.pyenv/versions/2.7.10/envs/spacy-test/lib/python2.7/site-packages/spacy/data/en/meta.json'
```

The model I linked also does not show up as an installed models in the `spacy info` blurb (see below). I've tried to follow along with [the docs](https://spacy.io/docs/usage/models#download-manual), but apparently have messed it up somehow. Thanks in advance for your help.

## Your Environment

* **Python version:** 2.7.10
* **Platform:** Darwin-16.6.0-x86_64-i386-64bit
* **spaCy version:** 1.9.0
* **Installed models:**

**Comment by ines** [comment]
Ah, I think the problem is that you're trying to link a `.tar.gz` archive:
```
/Users/burtondewilde/Downloads/en_core_web_sm-1.2.0.tar.gz
```

spaCy expects a directory containing the model data, so you'll need to unzip the archive first and then use the path of the data directory (the last one in the list [here](https://spacy.io/docs/usage/models#download-manual)). Now that I read the docs again, this should have probably been pointed out more clearly!

P.S.: In v2.x, this behaviour will change slightly and the `link` command will expect a valid Python package instead (i.e. one level up in the tree). We want to have a clearer separation between "loading raw model data from disk" and "loading a model package" (including meta and pre-defined pipelines). The CLI commands and `spacy.load` will be for model packages, while `.from_disk()` can be used to explicitly load data.

**Comment by bdewilde** [comment]
Aha! I wondered if that might be the case, and probably should've tested it before posting. (My bad.) As a user, I'll say that this requirement was not clear from the usage instructions, although upon a very careful read, I can see how someone could've interpreted them correctly. Sorry to bug you. _Extremely_ excited for v2!
