### ISSUE TITLE
Differences between Spacy3 and Spacy2 in NER

### ISSUE THREAD

**Issue by ambuje** [explosion/spaCy#12249]
### Discussed in https://github.com/explosion/spaCy/discussions/12246

<div type='discussions-op-text'>

<sup>Originally posted by **ambuje** February  7, 2023</sup>
Hi, 

I saw a large improvement in the spacy3 models compared to the spacy2 model. 

I am using the same default model (eg ja_core_news_lg) and observing that I am getting an accuracy of around 98 in spacy 3 (training using config) and was getting an accuracy of less than 90 in spacy 2 (training using python code)

I have trained a lot of languages and have observed the same that spacy3 is giving f1 about 95. 

Seeing these extraordinary results, I just want to confirm if I am missing something or if anything major has been changed from spacy2 to spacy3.3 in terms of architecture. Or you could help me with the reasons for getting so much better accuracy from spacy3

Thank you,
Ambuje</div>

**Comment by rmitsch** [comment]
Hi @ambuje, please don't open duplicate issues/discussions. Let's continue this conversation in https://github.com/explosion/spaCy/discussions/12246.
