### ISSUE TITLE
Documentation Update - Fix incorrect filename found in Entity Ruler usage page

### ISSUE THREAD

**Issue by SethDocherty** [explosion/spaCy#12259]
Filename mentioned in documentation is not correctly.

## Which page or section is this issue related to?

In the last paragraph for the section [Using Pattern files](https://spacy.io/usage/rule-based-matching#entityruler-files), the documentation [mentions](https://spacy.io/usage/rule-based-matching#entityruler-files:~:text=the%20pipeline%20directory%20contains%20a%20file%20entityruler.jsonl) that the file saved in the `entity_ruler` folder is `entityruler.jsonl` when it should be `patterns.jsonl`

**Comment by rmitsch** [comment]
Thanks for spotting this, @SethDocherty! https://github.com/explosion/spaCy/pull/12262 fixes this.
