### ISSUE TITLE
Matcher on regex gives different results than re.findall

### ISSUE THREAD

**Issue by RichardSieg** [explosion/spaCy#12263]
I want to write a regex pattern matching that detects all acronyms which are not followed by parentheses (with whitespace between the acronym and the parentheses).
I came up with the following regex:
```
regex = r'\b[A-Z]{2,}(?:\.[A-Z])*s?\b(?!\s*\()'
```
My example text:
```
text = "Use the FLAIRs before putting it into the OMU (Original Mount Unit) and F.S. (Free Speech) and clear it with an grt."
```
My matcher
```
nlp = spacy.load("en_core_web_sm")
matcher = Matcher(nlp.vocab)
pattern = [{"TEXT": {"REGEX":regex}}]
matcher.add("Acronym", [pattern])
```
The matcher returns `FLAIRs` and `OMU` (<- this is wrong) as a result. Calling `re.findall(regex, text)` gives the correct result (namely only `FLAIR`).

## Info about spaCy

- **spaCy version:** 3.5.0
- **Platform:** macOS-12.5-arm64-arm-64bit
- **Python version:** 3.9.16
- **Pipelines:** en_core_web_sm (3.5.0)

**Comment by RichardSieg** [comment]
Okay I solved this via 
```
pattern = [{"TEXT": {"REGEX": r'\b[A-Z]{2,}(?:\.[A-Z])*s?\b'}}, {"TEXT": {"REGEX": r'\s*\('}, "OP": "!"}]
```
It would still be interesting to know why the matcher behaves that way.

**Comment by rmitsch** [comment]
Hi @RichardSieg, thanks for documenting this & posting a workaround! spaCy's matcher evaluates regular expressions against the recognized tokens, not against the raw string. Your regex contains whitespace symbols, which are the likely culprit here. We will document this better.
