### ISSUE TITLE
Include appositional modifiers in english_noun_chunks

### ISSUE THREAD

**Issue by IamJeffG** [explosion/spaCy#1226]
I noticed in some parses that appositional modifiers (`tok.dep_ == 'appos'`) are excluded from `spacy.syntax.iterators.english_noun_chunks` (and therefore `Span.noun_chunks`, `Doc.noun_chunks`).  The description of these terms in https://nlp.stanford.edu/software/dependencies_manual.pdf says they are NPs, and so I think should therefore be included as noun_chunks.

This could be accomplished easily by adding `'appos'` to the `labels` list at https://github.com/explosion/spaCy/blob/master/spacy/syntax/iterators.pyx#L13  (I'd offer a P.R. but haven't yet set up a spacy build/test environment locally.)

Examples before and after:

    >>> [_ for _ in nlp(u'Sam, my brother, arrived to the house.').noun_chunks]
    # Currently
    [Sam, the house]
    # After adding appos
    [Sam, my brother, the house]

    >>> [_ for _ in nlp(u'Whisk together the cumin, chili powder, and salt.').noun_chunks]
    # Currently
    [Whisk]
    # After adding appos
    [Whisk, the cumin, chili powder, salt]

**Comment by honnibal** [comment]
Big thumbs up to this! Appositional phrases are very important for relation extraction and coreference resolution, and syntactically they're certainly NPs.

It would be nice to look through the Stanford dependency labelling rules to see if there are other cases we're missing. Anything that was an NP node in the PTB annotation is a likely candidate for the noun chunks iterator. I wonder whether the rules could be tweaked to prevent the false-positive in that imperative ("Whisk") --- but in general it's okay that if the parse tree is wrong, the noun chunks are wrong.

**Comment by IamJeffG** [comment]
Great idea. At your suggestion I browsed through the dependencies manual PDF linked in the issue description. Here are some more ideas for your consideration. I am hardly a linguist so not 100% sure on all of these...

_iobj_: indirect object (spacy calls it _dative_)
* `spacy.syntax.iterators.english_noun_chunks(nlp(u'She gave Bob a raise'))` currently misses `Bob`

_agent_: agent
* maybe not exposed in spacy: "This relation only appears in the collapsed dependencies, where it can replace _prep_by_, where appropriate. It does not appear in basic dependencies output."
* In "The man has been killed by the police.", spacy labels "police" with `pobj` and therefore successfully captures the noun phrase.

_xsubj_: controlling subject
* again maybe not exposed in spacy: "This is an additional dependency, not a basic dependency."
* In "Tom likes to eat fish.", spacy labels "fish" with `dobj` and therefore successfully captures the noun phrase.

Based on this, my non-expert opinion is we should add `iobj` and `appos` to the list.
