### ISSUE TITLE
spaCy document object splitting tokens incorrectly

### ISSUE THREAD

**Issue by davesuketu215** [explosion/spaCy#12286]
### Code Snippet
```
import spacy
nlp = spacy.load('en_core_web_sm')
text = "text = "the target id is aee2a311edca2ad82b8edf08c9d_tm""
text_doc = nlp(text)
for tok in text_doc:
     print(tok)
```
### Output:
```
the
target
i
d
is
aee2a311edca2ad82b8edf08c9d_tm
```
**Issue: Here you see the word "id" is being incorrectly split to "i" and "d"**

## My Environment - Info about spaCy

- **spaCy version:** 3.5.0
- **Platform:** macOS-10.16-x86_64-i386-64bit
- **Python version:** 3.9.6
- **Pipelines:** en_core_web_sm (3.0.0)

**Comment by kadarakos** [comment]
Hey,

This issue/discussion has come up before. Please checkout https://github.com/explosion/spaCy/discussions/10570.

**Comment by davesuketu215** [comment]
Thanks @kadarakos 
While, this is still a mystery why spaCy by default does it that way. The solution is short, sweet and doable.
Thank You for your response! :) 👍
