### ISSUE TITLE
Memory leak with GPU

### ISSUE THREAD

**Issue by hugoobauer** [explosion/spaCy#12294]
I have a memory leak (CPU memory, NOT GPU) with the most minimal configuration possible.
It's not a vocab issue since I'm sending the same text and it doesn't get bigger.

## How to reproduce the behaviour
Python code:
```python
import itertools
import spacy

def text_sequence():
    counter_id = itertools.count(start=1)
    while True:
        yield 'Hello, my name is Hugo. How are you ?'*10, next(counter_id)

spacy.prefer_gpu()  # return True
nlp_pipeline = spacy.load("en_core_web_trf")
running_pipe = nlp_pipeline.pipe(
    text_sequence(),
    n_process=1,
    batch_size=1,
    as_tuples=True,
)
for doc, _id in running_pipe:
    print(_id, len(doc))
    if _id % 200 == 0:
        print("------------")
        print("running_pipe.vocab.strings", len(nlp_pipeline.vocab.strings))
        print("------------")

```
Important : the issue occurs also without n_process, batch_size and as_tuples params.

Dockerimage:
```
FROM nvidia/cuda:11.0.3-runtime-ubuntu20.04 as intermediate

FROM python:3.10

COPY --from=intermediate /usr/local/cuda-11.0 /usr/local/cuda-11.0
COPY --from=intermediate /usr/local/cuda /usr/local/cuda
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/nvidia/lib64:/usr/local/cuda/lib64

RUN pip install -U pip setuptools wheel
RUN pip install -U 'spacy[cuda110]'
RUN python -m spacy download en_core_web_trf
```

On the documentation it says for cuda 11+ to use `pip install -U 'spacy[cuda-autodetect]'` but it doesn't work since no GPU is available at build time.
I have also tried to install spacy with `spacy[cuda-autodetect]` directly on the running container on kubernetes, it worked but didn't change anything for the memory leak issue.

`nvidia-smi` output :
```
Fri Feb 17 11:11:26 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   77C    P0    70W /  70W |   1530MiB / 15109MiB |     81%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

GPU drivers are installed from the DaemongSet : 
`https://raw.githubusercontent.com/GoogleCloudPlatform/container-engine-accelerators/master/nvidia-driver-installer/cos/daemonset-preloaded.yaml`

`ls /usr/local/nvidia`
```
NVIDIA-Linux-x86_64-470.141.03_97-16919-189-12.cos  bin  bin-workdir  drivers  drivers-workdir	firmware  lib64  lib64-workdir	nvidia-installer.log  pubkey.der  share  vulkan
```
`ls /usr/local/cuda/lib64`
```
libcublas.so.11		   libcufftw.so.10		libcusparse.so.11	   libnppidei.so.11	     libnppist.so.11	      libnvToolsExt.so	       libnvrtc-builtins.so.11.0
libcublas.so.11.2.0.252    libcufftw.so.10.2.1.245	libcusparse.so.11.1.1.245  libnppidei.so.11.1.0.245  libnppist.so.11.1.0.245  libnvToolsExt.so.1       libnvrtc-builtins.so.11.0.221
libcublasLt.so.11	   libcurand.so.10		libnppc.so.11		   libnppif.so.11	     libnppisu.so.11	      libnvToolsExt.so.1.0.0   libnvrtc.so.11.0
libcublasLt.so.11.2.0.252  libcurand.so.10.2.1.245	libnppc.so.11.1.0.245	   libnppif.so.11.1.0.245    libnppisu.so.11.1.0.245  libnvblas.so.11	       libnvrtc.so.11.0.221
libcudart.so.11.0	   libcusolver.so.10		libnppial.so.11		   libnppig.so.11	     libnppitc.so.11	      libnvblas.so.11.2.0.252
libcudart.so.11.0.221	   libcusolver.so.10.6.0.245	libnppial.so.11.1.0.245    libnppig.so.11.1.0.245    libnppitc.so.11.1.0.245  libnvjpeg.so.11
libcufft.so.10		   libcusolverMg.so.10		libnppicc.so.11		   libnppim.so.11	     libnpps.so.11	      libnvjpeg.so.11.1.1.245
libcufft.so.10.2.1.245	   libcusolverMg.so.10.6.0.245	libnppicc.so.11.1.0.245    libnppim.so.11.1.0.245    libnpps.so.11.1.0.245    libnvrtc-builtins.so
```

Result:
![image](https://user-images.githubusercontent.com/46481101/219635272-d2814e27-9c98-4e6c-b5f9-cd26717640b4.png)

I have also tried with CUDA 11.6 (`nvidia/cuda:11.6.2-runtime-ubuntu20.04` & `spacy[cuda116]`, but it doesn't improve anything.

## Info about spaCy

- **spaCy version:** 3.5.0
- **Platform:** Linux-5.10.147+-x86_64-with-glibc2.31
- **Python version:** 3.10.10
- **Pipelines:** en_core_web_trf (3.5.0)
- Environment Information: Docker/Kubernetes/GKE 1.24
- GPU : NVIDIA T4 ([time sharing GPU](https://cloud.google.com/kubernetes-engine/docs/how-to/timesharing-gpus))

**Comment by rmitsch** [comment]
Hi @hugoobauer, thanks for the report! Are you experiencing the same issue with `as_tuples=False`?

**Comment by adrianeboyd** [comment]
Ah, sorry, `as_tuples` was my first guess, but it looks like it's actually a memory leak in the new alignment code for fast tokenizers in `spacy-transformers`. We will take a look!

**Comment by hugoobauer** [comment]
Hi to you both, yes I tried without as_tuples but didn't make any difference.
Some update after more tests :
The issue is also occurring without the GPU enable (without `spacy.prefer_gpu()`)
(starting at ~13:30)
![image](https://user-images.githubusercontent.com/46481101/219656884-ded2458b-cdca-445b-8bf7-74236294cfc9.png)
So after this discovery, I landed on this issue : https://github.com/explosion/spaCy/issues/8554
I tried [your comment](https://github.com/explosion/spaCy/issues/8554#issuecomment-871486615) @adrianeboyd, but it didn't solve the problem on my side.
![image](https://user-images.githubusercontent.com/46481101/219695086-ce19144e-d20f-45b5-ba6f-17a4f822932b.png)
(Starting at ~14:15 : we notice that the increase is more hazardous and less linear than with the GPU, I don't know if this can put you on a lead.)

**Comment by adrianeboyd** [comment]
I tracked it down (with valgrind): https://github.com/explosion/spacy-transformers/pull/373

I will try to publish a release of `spacy-transformers` with the fix soon.

**Comment by hugoobauer** [comment]
Hey @adrianeboyd, I don't know if your fix is finished, but I tried it on my side (with GPU, and also tried it with `torch.set_num_threads(1)`) and it didn't make any difference. Don't hesitate if I can help.

**Comment by adrianeboyd** [comment]
I don't think this is related to any torch or GPU details.

The fix above resolved the memory leaks on my end in valgrind and in your example. This is always a frustrating aspect of debugging this kind of thing: but double-check that the old version was completely uninstalled before compiling and installing the new version?

**Comment by adrianeboyd** [comment]
Ah, I should add that I was testing without GPU for this.

**Comment by hugoobauer** [comment]
I will try without GPU and come back to you. But for my test, I directly edited the file in site-packages and ran my test. Is this the correct approach?
`sed '235,239!d' /usr/local/lib/python3.10/site-packages/spacy_transformers/align.pyx`
```
            result[-1].append(deref(it_s))
            preinc(it_s)
        del s
        preinc(it_v)
    return result
```

**Comment by adrianeboyd** [comment]
Just editing `align.pyx` doesn't work because the module needs to be recompiled. Try this instead:

```bash
python -m pip uninstall -y spacy-transformers
python -m pip install https://github.com/explosion/spacy-transformers/archive/43c06fa1e23c56aaa63effbf79f9432a1d945fde.zip
```

**Comment by hugoobauer** [comment]
Its fixed! Well done and thanks a lot for delivering a fix so quickly ❤️

**Comment by svlandeg** [comment]
Thanks for reporting back that it works! I'll go ahead and close this :-)
