### ISSUE TITLE
UnicodeDecodeError encounted when load the  spacy model

### ISSUE THREAD

**Issue by personyeah** [explosion/spaCy#1230]
Yesterday , I tried to install the latest model ' en_core_web_sm 2.0.0-alpha ' but failed. Then I found I couldn't load  the models I had installed any more. It  was just ok before I tried to install the latest model.
So I uninstalled the spacy and reinstalled it and some models again , but it didn`t work. Now I still can't load the model. Once loading model , a UnicodeDecodeError will be raised. 
Could you help me to fix this bug? Thank you very much!

Some details was show as below. I use pyCharm, the spacy version is 1.9.0, but other version also have this issue. 
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32

>>> spacy.load('en_md')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\Python27\lib\site-packages\spacy\__init__.py", line 42, in load
    return cls(**overrides)
  File "D:\Python27\lib\site-packages\spacy\en\__init__.py", line 33, in __init__
    overrides = fix_glove_vectors_loading(overrides)
  File "D:\Python27\lib\site-packages\spacy\deprecated.py", line 99, in fix_glove_vectors_loading
    vec_path = match_best_version('en_glove_cc_300_1m_vectors', None, data_path)
  File "D:\Python27\lib\site-packages\spacy\deprecated.py", line 65, in match_best_version
    name, version = split_data_name(data_name.parts[-1])
  File "D:\Python27\lib\site-packages\spacy\deprecated.py", line 75, in split_data_name
    return name.split('-', 1) if '-' in name else (name, '')
**UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 0: ordinal not in range(128)**

**Comment by ines** [comment]
Which version of spaCy are you using, and which model are you trying to load when you encounter the error? Could you post the output of `python -m spacy info --markdown`?

And does loading models via the native `import` work for you?
```python
import en_core_web_md  # or whichever model you want to load
nlp = en_core_web_md.load()
```

Btw, just so you know, the new alpha model is not compatible with spaCy v1.x and requires the new [v2.0.0 alpha](https://github.com/explosion/spaCy/releases/tag/v2.0.0-alpha). (From your issue, it wasn't fully clear how you were installing the new alpha model and why it failed, so I just thought I'd mention it.)

**Comment by ines** [comment]
Could you try again using the new version, v2.0 and the new models? If the problem still persists, feel free to reopen.
