### ISSUE TITLE
EntityRecognizer.load()

### ISSUE THREAD

**Issue by vascobailao** [explosion/spaCy#1231]
Hi!

After many days around this issue, I think its time to post here what is going on. I have two scripts right now: the first where I create the model, and a second script, where I add a new entity. So far so good, right?

In the second script, an error occurs when python goes through this lines:

```
 ner = None
    print(type(os.path.realpath("ner")))
    print(type(nlp.vocab))
    ner = EntityRecognizer.load(os.path.realpath("ner"), nlp.vocab)
```

The error return is as follows: 

```
<type 'str'>
<type 'spacy.vocab.Vocab'>
Traceback (most recent call last):
  File "trai_NER_entity.py", line 97, in <module>
    ner = EntityRecognizer.load(os.path.realpath("ner"), nlp.vocab)
  File "spacy\syntax\parser.pyx", line 145, in spacy.syntax.parser.Parser.load (spacy/syntax/parser.cpp:7202)
TypeError: unsupported operand type(s) for /: 'str' and 'unicode'
```

Does anyone has a clue what is going on here? I checked in [this](https://spacy.io/docs/api/entityrecognizer) webpage if anything was wrong, but as you can see, the types are clearly in order.

Any help would be much appreciated.

## Your Environment
* Operating System: Windows 10
* Python Version Used:  Python 2.7.13 64 bit
* spaCy Version Used:  1.9.0
* Environment Information:

**Comment by f11r** [comment]
Looks to me like the problem is that `os.path.realpath` returns a string, while `EntityRecognizer.load` expects a `pathlib.Path`. 

~~~
from pathlib import Path
EntityRecognizer.load(Path(os.path.realpath("ner")), nlp.vocab)
~~~
 should work.

**Comment by vascobailao** [comment]
Thank you for your reply. 

But the pathlib module is python 3 exclusive, right? Im using python 2.7....

**Comment by f11r** [comment]
You should be able to use `pip install pathlib` (this is what the spacy requirements.txt does, but pathlib is not maintained anymore) or `pip install pathlib2` (backport of python3 standard library pathlib to python2). Theres an issue about spacy switching to pathlib2 in #1193.

**Comment by vascobailao** [comment]
Its working! Thank you!

**Comment by ines** [comment]
Thanks for updating with the solution! 👍
