### ISSUE TITLE
The kernel appears to have died. It will restart automatically.

### ISSUE THREAD

**Issue by bobiq11** [explosion/spaCy#12316]
## How to reproduce the behaviour

import spacy
## Your Environment

* Operating System: macOS 13.2.1 (22D68) 
* Python Version Used:
Python 3.9.12
* spaCy Version Used: 
spacy                         3.5.0
spacy-legacy                  3.0.12
spacy-loggers                 1.0.4
* Environment Information:
Jupyter Notebook 6.4.8
on Anaconda Navigator 2.3.2
M1 2020 on MacBook Air

**Comment by svlandeg** [comment]
Hi! Can you provide more details on how you installed spaCy, and can you paste the error stack?

**Comment by svlandeg** [comment]
Closing in favour of https://github.com/explosion/spaCy/discussions/7909 which has more information on this topic.
