### ISSUE TITLE
Conflicting dependecy requirement bettween spacy(v3.4.4) and spacy-transformer(v1.2.0)

### ISSUE THREAD

**Issue by bkp4113** [explosion/spaCy#12331]
### Discussed in https://github.com/explosion/spaCy/discussions/12330

<div type='discussions-op-text'>

<sup>Originally posted by **bkp4113** February 24, 2023</sup>
We use spacy v3.4.4 with transformer as an extra and have part of custom install using pip with spacy-transformer(v1.2.0) on our sage instance. However when using the pipenv, We can't resolve the dependency since the spacy(v3.4.4) limits the spacy-transformers dependency to <1.2.0. Only spacy(v3.5.0) allows/opens up spacy_transformers to >=1.1.2,<1.3.0. (Our models are trained with spacy v3.4 and spacy-transformer v1.2.0). I am not sure if this purposely or just missed out. Please advise.

Please also advise if we can we use spacy v3.4.4 and spacy-transformers v1.2.0 ?

Note below setup file conflicts
- spacy (3.4.4) [setup.cfg](https://github.com/explosion/spaCy/blob/77833bfef9d96fc49e98b9ccaf67e5c726aec75d/setup.cfg#L76)
- spacy-transformers (1.2.0) [setup.cfg](https://github.com/explosion/spacy-transformers/blob/8b587a4c68a26436fdc8ee1b1a4b48852bfbc8e6/setup.cfg#L34)</div>

**Comment by adrianeboyd** [comment]
Please don't open duplicate issues. We'll follow up in the discussion thread.
