### ISSUE TITLE
Deleting links

### ISSUE THREAD

**Issue by ericmarkmartin** [explosion/spaCy#1233]
After creating a shortcut link using `python -m spacy link origin link_name`, how do you delete it? There doesn't seem to be any way to delete a link listed in `python -m spacy link -h`.

**Comment by ines** [comment]
Model shortcuts are created as symlinks in `spacy/data`. The exact path of your spaCy directory will be listed as "Location" when you run `python -m spacy info`. So the easiest way to delete a link would be to navigate to the directory and remove it from there. You can also overwrite existing links by using the `--force` flag.

Maybe we should introduce an `unlink` command or something similar that makes this a little easier. However, we usually want to avoid messing too much with the user's file system wherever possible (the link command is already pretty borderline, but it was the best and simplest option).
