### ISSUE TITLE
Docker containers on spaCy website are not working

### ISSUE THREAD

**Issue by andyjessen** [explosion/spaCy#12333]
## How to reproduce the behaviour
1. Go to "https://spacy.io/usage/rule-based-matching"
2. Go to "Editable Code" block
3. Select "Run" button

Returns: "Connecting failed. Please reload and try again."

## Your Environment

* Operating System: 
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by adrianeboyd** [comment]
Thanks for the report, we appreciate this kind of note! This seems to be working again now, so it may just have been a temporary outage on mybinder.org.

**Comment by IliasAarab** [comment]
Currently going through the [spaCy tutorial](https://course.spacy.io/en/chapter1), seems to be down again. Getting `Connecting failed. Please reload and try again.
` when trying to run some code.

**Comment by adrianeboyd** [comment]
As a note, in most cases I've been able to do a hard refresh of the page and then it started working again.

**Comment by robertoschiavone** [comment]
This still happens and refreshing the page doesn't fix it for me.

**Comment by svlandeg** [comment]
It's odd because it is working for me... :| Could you try again?

**Comment by andyjessen** [comment]
I cleared my cache and cookies. It works now for me.

**Comment by felubra** [comment]
Hey, this seems to be a rate limit issue:

![image](https://user-images.githubusercontent.com/25326257/233668463-f9d1ac50-b52a-4b48-b6de-7fa3100faa74.png)


```
{"phase": "failed", "status_code": 429, "message": "Rate limit exceeded. Try again in 3600 seconds.\n"}
```

**Comment by rmitsch** [comment]
Thanks for investigating this, @felubra! Yeah, this looks like a rate limit issue we running into with MyBinder. It's a free service that we use, we don't run the code snippets ourselves. So we don't have any influence on the hosting infrastructure. We also take measures to avoid overloading their servers, but it might still happen from time to time.

So for anyone running into this issue: please try again after a while if a hard refresh doesn't work for you!
