### ISSUE TITLE
Feed model with data

### ISSUE THREAD

**Issue by vascobailao** [explosion/spaCy#1238]
Hello again,

I'm new to the NLP world and have been playing with spacy. Right now, I have 3 python scripts:
1. train_NER.py
2. train_new_entity_NER.py

Both are similar to the examples in the github page. I have also built a parser (data cleaning and validation piece), that grabs pdfs from a directory, converts them to txt and then parses the document by full-stop ('.'). After this, this script creates a list that with the same structure as the train_data list on the examples. So far so good right? 

The next step is to feed the model (that I created and save in a folder) with this list. When I try to do this, a error is returned:

`Process finished with exit code -1073741819 (0xC0000005)`

I'm 100% sure that the data is structured the right way. The way that I'm feeding the model with this data goes like this:

`try:
    train_data = main()
    ner.main(model_dir="C:\\Users\\ps786qu\\PycharmProjects\\teste\\ner")
    add_entity_training = threading.Thread(target=new_entity.main(train_data=train_data))
    add_entity_training.start()`

The strangest thing is that I wrote 8 entries one by one, and with that entries, the model works fine:

`    train_data += [
        ("fundname1 ", [(0, 50, 'FUNDNAME')]),
        ("fundname2 ", [(0, 30, 'FUNDNAME')]),
        ("fundname3 ", [(0, 39, 'FUNDNAME')]),
        ("fundname4 ", [(0, 38, 'FUNDNAME')]),
        ("fundname5 ", [(0, 34, 'FUNDNAME')]),
        ("The Base Currency of fundname6 is US Dollar (US$), and the Fund will not undertake any exposure to currencies other than the US Dollar, except in the efficient portfolio management of changes to the Benchmark Index of the Fund and in the management of any future Share Classes of the Fund which may be denominated in a currency other than US Dollar. ", [(21, 51, 'FUNDNAME')]),
        ("The  Base  Currency  of fundname9 is  US  Dollar  (US$)  and  the  Fund  will  not undertake  any  exposure  to  currencies  other  than  US  Dollar  except  in  the  efficient  portfolio  management  of  changes in its Benchmark Index and in the management of any future Share classes of the Fund which may be ", [(24, 70, 'FUNDNAME')]),
        ("The Base Currency of fundname10 is Sterling (Stg).  ", [(20, 54, 'FUNDNAME')])
    ]
`
This data + the first entry of the data gathered from the txt file looks like this:
`[(u"ANNUAL REPORT AND AUDITED \nFINANCIAL STATEMENTS\niSHARES  PLC\n\nFOR THE YEAR ENDED\n29 FEBRUARY 2016\n\niSHARES PLC \n \n\nContents \n\nGeneral information \n\nBackground \n\nInvestment Managers report \n\nChairmans Statement \n\nBoard of Directors \n\nCorporate Governance Statement \n\nAudit Committee Report \n\nStatement of Directors Responsibilities \n\nDirectors Report \n\nStatement of the Custodian's Responsibilities \n\nCustodians report to the shareholders \n\nIndependent Auditors report \n\n \nFinancial Statements  \n\nFinancial statements of the Company \n\nBasis of preparat....", [(998, 1052, 'FUNDNAME')]), (u'fundanem4 ', [(0, 50, u'FUNDNAME')]), (u'fundname6 ', [(0, 30, u'FUNDNAME')]), (u'fundname5 ', [(0, 39, u'FUNDNAME')]), (u'fundname4 ', [(0, 38, u'FUNDNAME')]), (u'fundname3 ', [(0, 34, u'FUNDNAME')]), (u'The Base Currency of fundname3 is US Dollar (US$), and the Fund will not undertake any exposure to currencies other than the US Dollar, except in the efficient portfolio management of changes to the Benchmark Index of the Fund and in the management of any future Share Classes of the Fund which may be denominated in a currency other than US Dollar. ', [(21, 51, u'FUNDNAME')]), (u'The  Base  Currency  of fundname2  is  US  Dollar  (US$)  and  the  Fund  will  not undertake  any  exposure  to  currencies  other  than  US  Dollar  except  in  the  efficient  portfolio  management  of  changes in its Benchmark Index and in the management of any future Share classes of the Fund which may be ', [(24, 70, u'FUNDNAME')]), (u'The Base Currency of Fundname1 is Sterling (Stg).  ', [(20, 54, u'FUNDNAME')])]
`

I checked the data types of one of the strings and the other string and this came back:

`print(type(u"ANNUAL REPORT AND AUDITED \nFINANCIAL STATEMENTS\niSHARES  PLC\n\nFOR THE YEAR ENDED\n29 FEBRUARY 2016\n\niSHARES PLC \n \n\nContents \n\nGeneral information \n\nBackground \n\nInvestment Managers report \n\nChairmans Statement \n\nBoard of Directors \n\nCorporate Governance Statement \n\nAudit Committee Report \n\nStatement of Directors Responsibilities \n\nDirectors Report \n\nStatement of the Custodian's Responsibilities \n\nCustodians report to the shareholders \n\nIndependent..."))
<type 'unicode'>
print(type("fundname1 "))
<type 'str'>
`
If I try to change the data type from unicode to str, the following error is produced:

`TypeError("Argument 'string' has incorrect type (expected unicode, got str)",)
Argument 'string' has incorrect type (expected unicode, got str)`

Any help would immensly appreciated

Thank you

## Info about spaCy

* **Python version:** 2.7.13
* **Platform:** Windows-10-10.0.10586
* **spaCy version:** 1.9.0
* **Installed models:** en, en_core_web_sm-1.2.0

**Comment by honnibal** [comment]
Please see here --- the training is much improved in v2, and we've tried to give a lot more guidance about how to make good use of it: https://spacy.io/usage/training
