### ISSUE TITLE
Unresolved external symbol when installing spaCy 2.0.0

### ISSUE THREAD

**Issue by Valedix** [explosion/spaCy#1239]
Hello, this is the first time I'm using spaCy and I started by installing the nightly version 2.0.0. I actually had to try a few times and every time a problem popped up that I had to fix, this one I've been unable to.

During the installation an error message pops up:

gpu_ops.obj : error LNK2001: unresolved external symbol "void __cdecl gpu_max_pool(float *,int *,float const *,int const *,int,int,int)" (?gpu_max_pool@@YAXPAMPAHPBMPBHHHH@Z)

Searching for this one it appears to be a C++ linking error. A few more similar to this one pop up then the installation quits with these messages:

build\lib.win32-3.5\thinc\neural\gpu_ops.cp35-win32.pyd : fatal error LNK1120: 7 unresolved externals
error: command 'C:\\Program Files\\Microsoft Visual Studio 14.0\\VC\\BIN\\link.exe' failed with exit status 1120

After spending way too long checking my Python install, MVS install, environment settings, vcvarsall.bat, distutils, crying, and managing not to fix the problem I decided to install spaCy 1.9.0 and it worked on the first try.

I'm attaching the full log if anyone has any interest reading it.
[log.txt](https://github.com/explosion/spaCy/files/1188919/log.txt)

## Your Environment

* **Platform:** Windows-7-6.1.7601-SP1 (32 bits)
* **Python version:** 3.5.2
* **spaCy version:** 2.0.0
* **Installed models:** none
* **C++ compiler:** Microsoft Visual Studio 14.0

Note: The above snippet was obtained using the `python -m spacy info --markdown` command with spaCy 1.9.0 installed (and no models installed yet), I modified the spaCy version to reflect the one I'm unable to install.

**Comment by honnibal** [comment]
GPU support on Windows hasn't been tested. Can you check whether you can get the `cupy` library working on GPU? This is a component of Chainer, that we use as the GPU interface.

I suspect the issues comes down to setting the `CUDA_HOME` environment variable correctly, so that the `nvcc` compiler and CUDA shared libraries can be found.
