### ISSUE TITLE
blis.cy does not export expected C function sgemm

### ISSUE THREAD

**Issue by jedionmelbin** [explosion/spaCy#12402]
## Your Environment

* Operating System: Windows 11
* Python Version Used: 3.10
* spaCy Version Used: 3.5.1
* Environment Information:  Conda

I have this error 

ImportError: blis.cy does not export expected C function sgemm

ImportError                               Traceback (most recent call last)
Cell In [27], line 1
----> 1 import spacy
      2 from spacy import displacy
      3 nlp = spacy.load('es_core_news_sm')

File ~\.conda\envs\deeplearnig-cognitive\lib\site-packages\spacy\__init__.py:14
     11 from thinc.api import prefer_gpu, require_gpu, require_cpu  # noqa: F401
     12 from thinc.api import Config
---> 14 from . import pipeline  # noqa: F401
     15 from .cli.info import info  # noqa: F401
     16 from .glossary import explain  # noqa: F401

File ~\.conda\envs\deeplearnig-cognitive\lib\site-packages\spacy\pipeline\__init__.py:2
      1 from .attributeruler import AttributeRuler
----> 2 from .dep_parser import DependencyParser
      3 from .edit_tree_lemmatizer import EditTreeLemmatizer
      4 from .entity_linker import EntityLinker

**Comment by danieldk** [comment]
This usually issue usually occurs when the installed version of BLIS is too old. Could you give the output of `conda list` and check that there are no broken requirements with `pip check`?
