### ISSUE TITLE
Span Merge with keyword arguments

### ISSUE THREAD

**Issue by daniter-cu** [explosion/spaCy#1240]
Merging spans with keyword arguments does not work. 

Looking at https://github.com/explosion/spaCy/blob/6c15cf4193c1d00f2bfcd180eedd2c5d3894b161/spacy/tokens/doc.pyx#L622
if you want to use a keyword argument to set the lemma, you have to use the key attrs.LEMMA. However, the value of that is 73. Python does not allow numeric keys and putting the key into a dict and using the ** operator (eg myspan.merge(**{spacy.attrs.LEMMA:"new_lemma"}) throws a type error.

## Your Environment
* **Python version:** 2.7.10
* **Platform:** Darwin-16.6.0-x86_64-i386-64bit
* **spaCy version:** 1.8.2
* **Installed models:** en, en_core_web_md

**Comment by honnibal** [comment]
This is fixed in 2.0 (on develop branch). If you want you could port the fix over? It doesn't rely on other changes.

**Comment by daniter-cu** [comment]
Thanks for the quick response! It's not a big issue so I won't bother porting the fix. Using the three parameters interface (which I guess will be deprecated soon) is a workaround for now. I can switch to keyword args when I update to 2.0.

**Comment by honnibal** [comment]
Okay cool. Thanks, and please keep reporting! :)
