### ISSUE TITLE
Wrong `pos_` for "BATATA"

### ISSUE THREAD

**Issue by mbyalsky-r7** [explosion/spaCy#12404]
## How to reproduce the behaviour
Wrong `pos_` for batata, get `ADJ` should be `PROPN`

```
In [21]: english_nlp = spacy.load("en_core_web_md")

In [22]: text_nlp = english_nlp("I want BATATA! He pleaded.")

In [23]: batata_nlp = text_nlp[2]

In [24]: batata_nlp.pos_
Out[24]: 'ADJ'

In [25]: batata_nlp
Out[25]: BATATA
```

## Your Environment
* Operating System: macOS-13.2
* Python Version Used: 3.10.9
* spaCy Version Used: 3.5.1
* Environment Information: poetry

**Comment by danieldk** [comment]
I will convert this to a discussion, since this is not a general issue with spaCy.
