### ISSUE TITLE
Efficiently use NVIDIA gpu for model inference or prediction task

### ISSUE THREAD

**Issue by Anand195** [explosion/spaCy#12415]
I have trained spacy model with custom dataset and it's working fine for inference (or prediction task) on CPU.

Now I 'm looking to upgrade to GPU, Here I'm facing an issue related to GPU memory overload.

I have created a django project in which I use this spacy model, and deployed the Django project using gunicorn and nginx 

here is my gunicorn config 

```
[Unit]
Description=gunicorn daemon
After=network.target

[Service]
User=superadmin
Group=superadmin

WorkingDirectory=/home/superadmin/objDtct
ExecStart=/home/superadmin/objDtct/bin/gunicorn --workers 12 --thread 4 --bind 192.168.1.232:5000 --timeout 300 --preload cv_parser_api.wsgi:application
Restart=on-failure
[Install]
WantedBy=multi-user.target
```

For every new request on server the model loads in Gpu and it's memory consumption increases till it's get overloaded.

How can I overcome this issue??

_Originally posted by @Anand195 in https://github.com/explosion/spaCy/discussions/12414_

**Comment by adrianeboyd** [comment]
Please don't open duplicate issues/threads.
