### ISSUE TITLE
Creating a tagger using short commands

### ISSUE THREAD

**Issue by NiallRooney** [explosion/spaCy#1241]
I am creating my own Spacy based tagger using 4600 short text commands where each command is a short excerpt of text e.g. "show me the menu". I am doing this to correct for the fact that original tagged output did not always corectly identify that the first word  in the command is a verb, which  predominantly it is in my data.  So my training data corrects for this issue.

I work only with the Universal tag set.

The output from my tagger  is bit off:

e.g.
show the sports news    show (VERB, VERB) the (PRON, PRON) sports (NOUN, NOUN) news (NOUN, NOUN)
view live scores        view (VERB, VERB) live (VERB, VERB) scores (NOUN, NOUN)

Maybe I have insufficient training data or learning to tag short commands does not benefit from the training data containing only short commands?

Ubuntu 16.04.2
Python: 2.7.12
spacy version: 1.8.2

**Comment by honnibal** [comment]
What's wrong with the first example?

The second example looks like a tough case, especially when you don't have many examples. You should set aside 1000 words of your data for evaluation, to see how accurate the model actually is. It's hard to make progress by just inspecting the output.

Try running the default model over more text, and using that as part of your training data. This might help.

Overall it's hard to give firm advice --- you have to try things out and see what works on your data. At first glance it looks like the software is working as expected.

**Comment by NiallRooney** [comment]
In the first example, 'the' is identified as a PRON. I will try using larger data sets. Thanks.
