### ISSUE TITLE
Allow passing a span instead of doc to spacy.displacy.parse_deps

### ISSUE THREAD

**Issue by BLKSerene** [explosion/spaCy#12433]
Basically not a bug, just an enhancement proposal?

When I'm trying to solve #12432, I found `spacy.displacy.parse_deps`, but I was passing a span (one sentence in doc) instead of doc to it, so the error: AttributeError: 'spacy.tokens.span.Span' object has no attribute 'to_bytes'.

Then when searching for the solution, I found #2477. As `spacy.displacy.render` accepts spans, I suppose that `spacy.displacy.parse_deps` should be the same?

## How to reproduce the behaviour
```
import spacy

nlp = spacy.load('en_core_web_sm')
doc = nlp('This is a sentence for testing.')

for sentence in doc.sents:
	spacy.displacy.parse_deps(sentence) # Should replace "sentence" with "sentence.as_doc()"
```

## Your Environment

* Operating System: Windows 11 x64
* Python Version Used: 3.9.16
* spaCy Version Used: 3.5.0

**Comment by kadarakos** [comment]
Hey BLKSerene,

Thank you for the observation! Not sure yet if it would be useful, because as you say users can just call `Span.as_doc()` for the conversion. But you are right that its probably more intuitive to accept `Span`s too.

**Comment by BLKSerene** [comment]
@kadarakos Opened #12477. Not sure if got those type hints right...
