### ISSUE TITLE
How to reach a new entity-fish server?

### ISSUE THREAD

**Issue by ndenStanford** [explosion/spaCy#12443]
I am following the approach on the [readme](https://github.com/Lucaterre/spacyfishing) trying to run a simple entity linking sample below 

```
import spacy

text_en = "Victor Hugo and Honoré de Balzac are French writers who lived in Paris."

nlp_model_en = spacy.load("en_core_web_sm")

nlp_model_en.add_pipe("entityfishing")

doc_en = nlp_model_en(text_en)

for ent in doc_en.ents:
        print((ent.text, ent.label_, ent._.kb_qid, ent._.url_wikidata, ent._.nerd_score))
```

but receiving the response containing no information related to entity linking 

```
('Victor Hugo', 'PERSON', None, None, None)
('Honoré de Balzac', 'PERSON', None, None, None)
('French', 'NORP', None, None, None)
('Paris', 'GPE', None, None, None)
```

Upon further inspection, I found that the API that will be called as shown in the [page](https://nerd.readthedocs.io/en/latest/restAPI.html) no longer works. 

Calling the API directly 

```
curl 'http://cloud.science-miner.com/nerd/service/disambiguate' -X POST -F "query={ 'text': 'The army, led by general Paul von Hindenburg defeated Russia in a series of battles collectively known as the First Battle of Tannenberg. But the failed Russian invasion, causing the fresh German troops to move to the east, allowed the tactical Allied victory at the First Battle of the Marne.', 'processSentence': [ 1 ], 'sentences': [ { 'offsetStart': 0, 'offsetEnd': 138 }, { 'offsetStart': 138, 'offsetEnd': 293 } ], 'entities': [ { 'rawName': 'Russian', 'type': 'NATIONAL', 'offsetStart': 153, 'offsetEnd': 160 } ] }"
```

Has indicated that the server has been moved.

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://cloud.science-miner.com/nerd/service/disambiguate">here</a>.</p>
<hr>
<address>Apache/2.4.41 (Ubuntu) Server at cloud.science-miner.com Port 80</address>
</body></html>
```

Would you mind letting me know if the server is still on? If so, how should I reach it? Appreciate your attention to this matter.

**Comment by kadarakos** [comment]
Hey ndenStanford,

The [`spacyfishing`](https://github.com/Lucaterre/spacyfishing) is a third party library that we do not maintain and so unfortunately we don't know about the serves. I see that you've created the issue on the repo already https://github.com/Lucaterre/spacyfishing/issues/22 so hopefully they'll come back to you soon.

**Comment by ndenStanford** [comment]
Thanks for the clarification!
