### ISSUE TITLE
missing documentation for util.decaying

### ISSUE THREAD

**Issue by mevol** [explosion/spaCy#12487]
I am able to import util.decaying:
from spacy.util import decaying

and even run it:
dropout_rates = decaying(0.2, 0.005)

But I only found out about that I need two not three parameters, as stated here https://www.tutorialspoint.com/spacy/spacy_util_decaying.htm, through trial-and-error and by getting error messages when executing.

I was not able to find any documentation for this method in your SpaCy documentation.

## Which page or section is this issue related to?
 https://spacy.io/api/top-level#util

**Comment by adrianeboyd** [comment]
It sounds like you might be looking at spacy v2 code? Here are the v2 docs: https://v2.spacy.io/api/top-level#util.decaying

For spacy v3 these methods were moved to Thinc: https://thinc.ai/docs/api-schedules#decaying

It looks like `spacy.util.decaying` was kept in v3 for backwards compatibility, but given the different implementations it's ended up being more confusing than helpful.

First clarify whether your script is for spacy v2 or v3, and then check out the corresponding official docs. There weren't good Thinc docs related to spacy v2, so either:

* spacy v2: https://v2.spacy.io
* spacy v3: https://spacy.io, https://thinc.ai

**Comment by mevol** [comment]
I am using spacy 3.4.4

**Comment by adrianeboyd** [comment]
If you're using spacy v3, then refer to the Thinc API docs and don't import `decaying` from `spacy.util` but instead from `thinc.api`.
