### ISSUE TITLE
Documentation request: describe how to get a Doc object

### ISSUE THREAD

**Issue by trivedigaurav** [explosion/spaCy#1249]
Documentation on [Processing-text](/explosion/spacy/blob/master/website/docs/usage/processing-text.jade) workflow doesn't show how to access a Doc object but goes on to use it in the example code. It would be helpful to include that.

* **Python version:** 2.7.9
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **spaCy version:** 1.8.0
* **Installed models:** en

**Comment by ines** [comment]
Thanks and I agree – the current docs are definitely not as detailed as we'd like them to be. For v2, we've been re-writing a bunch of the old documentation – you can see the current progress in the [v2 alpha docs](https://alpha.spacy.io/docs/usage/v2). Here are some new and re-worked pages that might be relevant to you:

* [spaCy 101](https://alpha.spacy.io/docs/usage/spacy-101): Overview of all the important concepts, explained in simple terms, with examples and illustrations.
* Improved [`Doc` object API reference](https://alpha.spacy.io/docs/api/doc) with examples for each available method
* Improved [lightning tour](https://alpha.spacy.io/docs/usage/lightning-tour) with better and more representative examples
* [Processing pipelines](https://alpha.spacy.io/docs/usage/language-processing-pipeline) with more in-depth details on how spaCy processes text, and how to customise it 

Some of the behaviour described here is specific to v2 – those API methods and attributes are usually marked with a "v2" tag. Most of the changes are related to saving and loading, and new features, though, and none of the underlying architecture is going to change.

**Comment by trivedigaurav** [comment]
Thanks. You may close this request in that case.
