### ISSUE TITLE
ConsoleLogger.v3 docs example has an invalid example config `progress_bar = "all_steps"`

### ISSUE THREAD

**Issue by willfrey** [explosion/spaCy#12496]
https://github.com/explosion/spaCy/blob/de32011e4c3165119ac2690ae08f56cc1d578327/website/docs/api/top-level.mdx?plain=1#L580

The default config here provides an invalid value for `progress_bar`, both according to the document immediately to its left and when you try to use `"all_steps"` when training. In the case of the latter, you (unsurprisingly) get `ValueError: [E1048] Got 'all_steps' as console progress bar type, but expected one of the following: ('train', 'eval')` as a raised exception.

Unsure of what you'd prefer to use as a default value in the docs here, otherwise I'd just have submitted a one-change typo-fix pull request.

Thanks!

**Comment by shadeMe** [comment]
Thanks for spotting this! `ConsoleLogger.v1` and `v2` display the progress till the next evaluation epoch, so it'd make sense to correct that value to `eval`.

Feel free to open a PR :)

**Comment by svlandeg** [comment]
PR merged and updated website now live: https://spacy.io/api/top-level#ConsoleLogger ✨
