### ISSUE TITLE
Question about how to extract the exact place that the specific person would go (or something synonym verb like visit, meet, travel)

### ISSUE THREAD

**Issue by icmpnorequest** [explosion/spaCy#12503]
### Discussed in https://github.com/explosion/spaCy/discussions/12502

<div type='discussions-op-text'>

<sup>Originally posted by **icmpnorequest** April  6, 2023</sup>
Hi,

I tried to extract the place that a specific person would go from a document. I could extract the location entity with Entity Recognition, but couldn't distinguish whether it is the exact place that she/he would go or just mentioned in the text. I was wondering how I could do that?

My opinion is as following:
- Step1: Person entity recognition to recognize the specific person;
- Step2: Dependency parser?</div>

**Comment by shadeMe** [comment]
Let's use the discussion forum topic instead.
