### ISSUE TITLE
Spacy 2.0 fails to label plural proper nouns as NNPS

### ISSUE THREAD

**Issue by notnami** [explosion/spaCy#1254]
Sample input:

```
>>> doc = "Would this work with 5 iPhones?"
>>> doc[5].tag_ # expected NNPS
NNP
```
This occurs with every other proper noun I have tested. Spacy 1.9 correctly tags "iPhones" as NNPS.

## Info about spaCy

* **spaCy version:** 2.0.0a7
* **Platform:** Linux-4.4.0-43-Microsoft-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.1
* **Models:** en_core_web_sm, en_default

**Comment by ines** [comment]
Thanks for the report! Just tested it with the latest `en_core_web_sm` with the version currently on `develop`, and I'm getting `NNS` – still wrong, but this time in the other direction.

We're about to push some changes to the parser and are currently training new models, so once they're ready, I'll check again and see how they perform on your example.

**Comment by ines** [comment]
Update: tried it with the new models and `v2.0.0a18` and still getting `NNS` for your example.

However, for the latest version, we've also updated the training process and the examples, so you might be able to achieve pretty good results by updating the tagger with a few correct `NNPS ` examples.  See here for the example code: https://github.com/explosion/spaCy/blob/develop/examples/training/train_tagger.py

**Comment by ines** [comment]
Merging this with #3052. We've now added a master thread for incorrect predictions and related reports – see the issue for more details.
