### ISSUE TITLE
Missing Person entities

### ISSUE THREAD

**Issue by avissens** [explosion/spaCy#1255]
I have some issues with spaCy missing Person entities and I cannot really figure out why. Below are some examples when it seems like spaCy prefers certain surnames and dismisses others. Another example is linked to syntaxis. I included just one for " in particular.

```
import spacy
from spacy.en import English
nlp_toolkit = English()
nlp = spacy.load('en')

def get_person(all_tags):
    person_list=[]
    for ent in all_tags.ents:
        if ent.label_=="PERSON":
            person_list.append(str(ent))
    return person_list

#issue with certain names...
text = u'This is some text. Sgt Mat Knowles said: And this is some text.' #no
#text = u'This is some text. Sgt Mat Smith said: And this is some text.' #yes
#text = u'Sgt Mat Knowles said: And this is some text.' #yes

#issue with " before the name
#text = u'"This is a quote," Belinda Wright, told...' #no
#text = u'This is a quote, Belinda Wright, told...' #yes

all_tags = nlp(text)
names = get_person(all_tags)
print names

```

* macOS Sierra (10.12.3)
* Python 2.7
* spaCy-1.8.2
* Jupiter notebook

**Comment by honnibal** [comment]
Fixed now: https://demos.explosion.ai/displacy-ent/?text=This%20is%20some%20text.%20Sgt%20Mat%20Knowles%20said%3A%20And%20this%20is%20some%20text.&ents=person%2Corg%2Cgpe%2Cloc%2Cproduct%2Cdate%2Ctime&model=en

https://demos.explosion.ai/displacy-ent/?text=This%20is%20a%20quote%2C%22%20Belinda%20Wright%2C%20told...&ents=person%2Corg%2Cgpe%2Cloc%2Cproduct%2Cdate%2Ctime&model=en
