### ISSUE TITLE
Compare operator (==) behaves unexpectedly on spacy tokens

### ISSUE THREAD

**Issue by ank-26** [explosion/spaCy#1257]
```
nlp = spacy.load("en")
doc1 = nlp(u"I am here")
doc2 = nlp(u"Hello")

doc1[0] == doc2[0]
True
```
In the above snippet, spacy is treating 1st token of both the docs as equal. So, in the below source code the __richcmp__ method it is using index to compare.
```
def __richcmp__(self, Token other, int op):
        # http://cython.readthedocs.io/en/latest/src/userguide/special_methods.html
        my = self.idx
        their = other.idx if other is not None else None
``` 

## Environment
* **Python version:** 2.7.10
* **Platform:** Darwin-16.0.0-x86_64-i386-64bit
* **spaCy version:** 1.9.0
* **Installed models:** en

**Comment by honnibal** [comment]
Thanks, this must've been in there a long time. If you want to fix it, the best solution would be to check that `other.doc is self`

**Comment by honnibal** [comment]
Fixed :)
