### ISSUE TITLE
Pickle spacy object in spaCy 2

### ISSUE THREAD

**Issue by vctrferreira** [explosion/spaCy#1258]
My code:
````
class RasaServer(object):
    def start_interpreter(self, path):
        metadata = Metadata.load(path)
        return pickle.dumps(Interpreter.load(metadata, RasaNLUConfig(OS_PATH+"/config-rasa.json")))

    def interpretator(self, msg, interpreter):
        return pickle.loads(interpreter).parse(unicode(msg))
````
Returns:
`_pickle.PicklingError: Can't pickle <function BaseDefaults.<lambda> at 0x105a8c950>: attribute lookup BaseDefaults.<lambda> on spacy.language failed
`
Why this error? this is a bug?

## Your Environment

* **spaCy version:** 1.9.0
* **Platform:** Darwin-16.6.0-x86_64-i386-64bit
* **Python version:** 3.6.1
* **Installed models:** en

**Comment by honnibal** [comment]
spaCy 2 supports pickling of objects, using the `dill` library. `rasa` will likely add support as soon as it's out of alpha. You can get the current state of spaCy 2 by doing `pip install spacy-nightly`.

**Comment by vctrferreira** [comment]
thanks, i will try use rasa with spaCy 2

**Comment by vctrferreira** [comment]
I adapted rasa to get spacy 2 and when I tried this is my returns


`Traceback (most recent call last):
  File "test_spacy2_with_pickle.py", line 19, in <module>
    a = start_interpreter(OS_PATH + "/models/model_20170816-175043")
  File "aa.py", line 14, in start_interpreter
    return pickle.dumps(interpreter)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x108a4a598>: attribute lookup <lambda> on spacy.lang.lex_attrs failed`

this is my code now: 

```
from rasa_nlu.model import Metadata, Interpreter
from rasa_nlu.config import RasaNLUConfig

import os
import dill
import pickle

OS_PATH = os.path.dirname(os.path.abspath(__file__))


def start_interpreter(model_path):
    metadata = Metadata.load(model_path)
    interpreter = Interpreter.load(metadata, RasaNLUConfig(OS_PATH+"/config-rasa.json"))
    return pickle.dumps(interpreter)

def interpretator(msg, interpreter):
    return pickle.loads(interpreter.parse(msg))

a = start_interpreter(OS_PATH + "/models/model_20170816-175043")

b = interpretator("i want food", a)

print(b)
```

## Info about spaCy

* **spaCy version:** 2.0.0a9
* **Platform:** Darwin-16.6.0-x86_64-i386-64bit
* **Python version:** 3.6.1
* **Models:** en

**Comment by vctrferreira** [comment]
I adapted rasa to get spacy 2 and when I tried this is my returns


`Traceback (most recent call last):
  File "test_spacy2_with_pickle.py", line 19, in <module>
    a = start_interpreter(OS_PATH + "/models/model_20170816-175043")
  File "aa.py", line 14, in start_interpreter
    return pickle.dumps(interpreter)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x108a4a598>: attribute lookup <lambda> on spacy.lang.lex_attrs failed`

this is my code now: 

```
from rasa_nlu.model import Metadata, Interpreter
from rasa_nlu.config import RasaNLUConfig

import os
import dill
import pickle

OS_PATH = os.path.dirname(os.path.abspath(__file__))


def start_interpreter(model_path):
    metadata = Metadata.load(model_path)
    interpreter = Interpreter.load(metadata, RasaNLUConfig(OS_PATH+"/config-rasa.json"))
    return pickle.dumps(interpreter)

def interpretator(msg, interpreter):
    return pickle.loads(interpreter.parse(msg))

a = start_interpreter(OS_PATH + "/models/model_20170816-175043")

b = interpretator("i want food", a)

print(b)
```

## Info about spaCy

* **spaCy version:** 2.0.0a9
* **Platform:** Darwin-16.6.0-x86_64-i386-64bit
* **Python version:** 3.6.1
* **Models:** en

**Comment by vctrferreira** [comment]
```
import spacy
import pickle
import dill

s = spacy.load("en_core_web_sm", parse=False)

k = pickle.dumps(s)
```

`_pickle.PicklingError: Can't pickle <function <lambda> at 0x107027158>: attribute lookup <lambda> on spacy.lang.lex_attrs failed`


Another test direct with spacy 2

## Info about spaCy

* **spaCy version:** 2.0.0a9
* **Platform:** Darwin-16.6.0-x86_64-i386-64bit
* **Python version:** 3.6.1

**Comment by vctrferreira** [comment]
@honnibal Did you say that pickle work's in spacy 2 need another params? or this is a bug?

**Comment by honnibal** [comment]
@vctrferreira It was a bug.

Pickle is now fixed on develop, for both the `Language` class and the `Doc`. :tada:

Pickling should be quite fast, with no redundant copies of the `Vocab` --- so you can pickle a list of `Doc` objects, and it'll do the right thing and only have one copy of all the shared data.

**Comment by DiplEng** [comment]
Hi,

I recently attempted pickling a language model, and....

```
import pickle
nlp = spacy.load("de", tagger=False, entity=False, matcher=False, parser=False)
pickle.dumps(nlp)
```

**Comment by aCampello** [comment]
I have the same issue. Any hints?
