### ISSUE TITLE
Lisbon isn't a place anymore (NER and NER training)

### ISSUE THREAD

**Issue by betatim** [explosion/spaCy#1261]
We noticed that after upgrading to spacy v2 "Lisbon" is not recognise as a place anymore. Not sure if this is a bug or a feature/side effect, but maybe you find this useful.

```python
In [4]: d = nlp(u"Lisbon is great.")

In [5]: for e in d.ents:
   ...:     print(e.label_, e.lemma_)
   ...:     
(u'PERSON', u'lisbon')

In [6]: d = nlp(u"Lisbon is a great city.")

In [7]: for e in d.ents:
   ...:     print(e.label_, e.lemma_)
   ...:     
(u'ORG', u'lisbon')
```

Then tried to [(re)train](https://github.com/explosion/spaCy/blob/master/examples/training/train_new_entity_type.py) the NER but that raises an exception:

```python
from spacy.gold import GoldParse
import en_core_web_sm
nlp = en_core_web_sm.load()
train_data = [(u"Lisbon is a great city", [(0,6, u'GPE')]),]

for text, offsets in train_data:
     doc = nlp.make_doc(text)
     gold = GoldParse(doc, entities=offsets)
     nlp.entity.update(doc, gold, drop=0.9)
```
traceback: https://gist.github.com/betatim/f3e0ae680f02fb0864991e504a6105a5

Seems pretty basic so I'm wondering what I missed?

## Info about spaCy
* **Python version:** 2.7.13
* **Platform:** Linux-4.11.3-1-ARCH-x86_64-with-glibc2.2.5
* **spaCy version:** 2.0.0a9
* **Model:** en_core_web_sm 2.0.0a0

/cc @joaobarcia

**Comment by honnibal** [comment]
spaCy v2.0.0a11 made some improvements to the NER --- so, you might try updating and re-downloading the model. That should also fix the update error (I think?).

**Comment by betatim** [comment]
It fixed the "Lisbon" issue, haven't tried this specific retraining example yet. I think I saw something related to the new release and tried that which worked. So closing for now.
