### ISSUE TITLE
Kyrgyz language stopwords

### ISSUE THREAD

**Issue by GrossmanLess** [explosion/spaCy#12632]
I'm from Kyrgyzstan, work on an article about Kyrgyz language stopwords. I'd like to change the list of Kyrgyz stopwords in SpyCy lib. I'm a beginner in contributing to GitHub. What should I do to complete my contribution? 
## Which page or section is this issue related to?

https://github.com/explosion/spaCy/blob/master/spacy/lang/ky/stop_words.py

**Comment by adrianeboyd** [comment]
Hi, we're planning to remove default stop word lists from spacy in the near future, so we're not currently accepting any PRs that modify stop word lists.

Stop word lists are task-specific and we've realized that it's not possible for us to maintain stop word lists in a sensible way for such a wide range of languages. Stop words will still be supported in general by spacy and you'll still be able to add custom stop words to your own pipeline, but spacy's default lists would be empty.

Here's how to customize stop words for your own pipeline in spacy v3: https://spacy.io/usage/linguistic-features#language-subclass
