### ISSUE TITLE
Latest version of Numpy doesn't have TypeDict. Whereas Spacy still using it wihch cause issue during import.

### ISSUE THREAD

**Issue by Deepikakolandasamy** [explosion/spaCy#12635]
## Error 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-afbeceda568c> in <module>
      1 import warnings
      2 warnings.filterwarnings("ignore", category=ImportWarning)
----> 3 import spacy
      4 
      5 

~\AppData\Roaming\Python\Python38\site-packages\spacy\__init__.py in <module>
      4 
      5 # set library-specific custom warning handling before doing anything else
----> 6 from .errors import setup_default_warnings
      7 
      8 setup_default_warnings()  # noqa: E402

~\AppData\Roaming\Python\Python38\site-packages\spacy\errors.py in <module>
      1 import warnings
----> 2 from .compat import Literal
      3 
      4 
      5 class ErrorsWithCodes(type):

~\AppData\Roaming\Python\Python38\site-packages\spacy\compat.py in <module>
      1 """Helpers for Python and platform compatibility."""
      2 import sys
----> 3 from thinc.util import copy_array
      4 
      5 try:

~\AppData\Roaming\Python\Python38\site-packages\thinc\__init__.py in <module>
      3 
      4 from .about import __version__
----> 5 from .config import registry
      6 
      7 

~\AppData\Roaming\Python\Python38\site-packages\thinc\config.py in <module>
      2 import confection
      3 from confection import Config, ConfigValidationError, Promise, VARIABLE_RE
----> 4 from .types import Decorator
      5 
      6 

~\AppData\Roaming\Python\Python38\site-packages\thinc\types.py in <module>
      6 import numpy
      7 import sys
----> 8 from .compat import has_cupy, cupy
      9 
     10 if has_cupy:

~\AppData\Roaming\Python\Python38\site-packages\thinc\compat.py in <module>
     72 
     73 try:
---> 74     import h5py
     75 except ImportError:  # pragma: no cover
     76     h5py = None

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py in <module>
     44 _errors.silence_errors()
     45 
---> 46 from ._conv import register_converters as _register_converters
     47 _register_converters()
     48 

h5py\h5t.pxd in init h5py._conv()

h5py\h5t.pyx in init h5py.h5t()

~\AppData\Roaming\Python\Python38\site-packages\numpy\__init__.py in __getattr__(attr)
    318             return Tester
    319 
--> 320         raise AttributeError("module {!r} has no attribute "
    321                              "{!r}".format(__name__, attr))
    322 

AttributeError: module 'numpy' has no attribute 'typeDict'

## Your Environment

* Operating System: Windows
* Python Version Used: 3.8
* spaCy Version Used: 3.5.2
* Numpy version Used: 1.24.2
* Environment Information: Jupyter notebook used to install

**Comment by Deepikakolandasamy** [comment]
Even the upcoming dev package also doesn't upgraded with this issue. 
Version: spacy-3.6.0.dev0

**Comment by danieldk** [comment]
Thanks for reporting this issue! The exception seems to occur in the `h5py` package, not spaCy or Thinc. Could you give me the output of `pip freeze` so that I can try to reproduce this locally?

Alternatively, you could try to `pip install --upgrade h5py` to see if upgrading to the latest `h5py` solves this issue (I don't run into this error with `h5py==3.8.0`. From a [PR against h5py](https://github.com/h5py/h5py/pull/1931) it seems that this should have been fixed in h5py 3.5.

**Comment by Deepikakolandasamy** [comment]
Thank you for the solution. Now its working.
