### ISSUE TITLE
Argument 'string' has incorrect type (expected unicode, got str) when reading csv

### ISSUE THREAD

**Issue by Rahulvks** [explosion/spaCy#1263]
Hi 

Am trying to extract entities from csv using spacy, but am getting errors Argument 'string' has incorrect type (expected unicode, got str). Kindly some one help me to get fixed in terms of in pandas and csv dataset

`from __future__ import unicode_literals`
`import pandas as pd`
`import nltk`
`import spacy`
`nlp = spacy.load('en')`
`from spacy.en import English`
`Parser = English()`
`data = pd.read_csv("/Mac_Data/Dataset/Ques_for_testing.csv")`
`from spacy.gold import GoldParse`
`nlp = spacy.load('en')`
```
for parsed_doc in nlp.pipe(iter(data['Question']), batch_size=1, n_threads=4):
 print (parsed_doc.ents)
```

## Your Environment

* Operating System: Mac Sierra
* Python Version Used: 2.7
* spaCy Version Used: v1.7
* Environment Information: Anaconda 

Thanks in advance

**Comment by f11r** [comment]
This should work (notice the `astype(unicode)`).

~~~
for parsed_doc in nlp.pipe(iter(data['Question'].astype(unicode)), batch_size=1, n_threads=4):
    print (parsed_doc.ents)
~~~
