### ISSUE TITLE
ValueError: No GPU devices detected

### ISSUE THREAD

**Issue by skaistt** [explosion/spaCy#12641]
Hi,

I have an issue with GPU - it seems like SpaCy does not detect any GPUs.

This gives me True:
```
import torch
torch.cuda.is_available()

True
```

but this gives me False:

```
import spacy
spacy.prefer_gpu(0)

False
```

Why torch detects GPU but SpaCy does not?
nvidia-smi works fine and lists all available GPUs. SpaCy transformers are also installed.

None of the solutions found on the Internet helped me: already tried to re-install cupy many times, downgraded the version of spacy - did not solve my issue.

Maybe there is something I am missing?

OS: Linux
Python: 3.10.6
spaCy: 3.5.1
cuda: cupy-cuda117

```
{'spacy_version': '3.5.1',
 'location': '/opt/pypoetry/virtualenvs/code-MATOk_fk-py3.10/lib/python3.10/site-packages/spacy',
 'platform': 'Linux-4.14.314-1684020202-x86_64-with-glibc2.35',
 'python_version': '3.10.6',
 'pipelines': {'de_dep_news_trf': '3.5.0'}}
```

This refers to my issue, but there is no answer yet: 
https://stackoverflow.com/questions/74940085/gpu-is-not-detected-by-pytorch-for-spacy-ner

**Comment by danieldk** [comment]
Let's discuss this here until we find this is a bug in spaCy or Thinc:

https://github.com/explosion/spaCy/discussions/12640
