### ISSUE TITLE
Incorrect code in spacy/training/iob_utils.py

### ISSUE THREAD

**Issue by rkatriel** [explosion/spaCy#12649]
It looks like the following code section in spacy/training/iob_utils.py (lines 141-146) is incorrect

```
    for token in doc:
        for i in range(token.idx, token.idx + len(token)):
            if i in entity_chars:
                break
        else:
            biluo[token.i] = missing
```

The "else" clause is not indented properly (it's aligned with the "for" loop rather than the "if" clause).

## How to reproduce the behaviour

I came across this by chance while debugging a warning (W030) issued from offsets_to_biluo_tags

`UserWarning: [W030] Some entities could not be aligned in the text "['Dengue-suspected patients living in the interven..." with entities "[(2, 8, ['Disease or Syndrome']), (8, 9, ['Finding...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.`

It's not clear my problem is related but the code should be fixed if indeed my observation is correct.

## Your Environment

* Operating System: MacOS 12.5.1
* Python Version Used: 3.9
* spaCy Version Used: 3.4.3
* Environment Information: PyCharm IDE

**Comment by adrianeboyd** [comment]
This is a relatively unusual construction, but not invalid python or a bug in spacy: https://docs.python.org/3/tutorial/controlflow.html#break-and-continue-statements-and-else-clauses-on-loops

Your problem is likely related to the default tokenization of your text. You can find related threads in the discussion board by searching for the warning code W030.

**Comment by rkatriel** [comment]
Hi Adriane,

Thanks for the quick response. That is a feature of python that I was not familiar with so good to know.

Regarding the W030 error, it was caused by the PhraseMatcher matching on substrings of tokens (e.g., matching "T1" on "T1DM"). I got around it by suppressing span matches for which the following is true

`doc.char_span(span.start_char, span.end_char) == None`

Best,
Ron
