### ISSUE TITLE
Sentence segmentation fails when ending in "I.\n" or "I.  " but not "I. "

### ISSUE THREAD

**Issue by christian-storm** [explosion/spaCy#1266]
Looks like a couple issues here.  Tokenization of "I." in all cases fails to separate end punctuation from I.  However, sentence segmentation works when period is followed by single space but not double space or newline, e.g., newline segmented sentences.
```
import spacy

nlp = spacy.load('en_depent_web_md')

text1 = "He gave the ball to I. Do you want to go to the movies with I?"
text2 = "He gave the ball to I.  Do you want to go to the movies with I?"
text3 = "He gave the ball to I.\nDo you want to go to the movies with I?"
t1 = nlp(text1)
t2 = nlp(text2)
t3 = nlp(text3)

assert t1[5].text == 'I'
assert t2[5].text == 'I'
assert t3[5].text == 'I'

assert len([sent for sent in t1.sents]) == 2
assert len([sent for sent in t2.sents]) == 2
assert len([sent for sent in t3.sents]) == 2
```

## Info about spaCy

* **spaCy version:** 1.9.0
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **Python version:** 3.6.0
* **Installed models:** en_depent_web_md

**Comment by honnibal** [comment]
Seems better: https://demos.explosion.ai/displacy/?text=He%20gave%20the%20ball%20to%20I.%20Do%20you%20want%20to%20go%20to%20the%20movies%20with%20I%3F&model=en_core_web_sm&cpu=1&cph=1
