### ISSUE TITLE
Word vector similarity difference from spaCy lexeme and doc

### ISSUE THREAD

**Issue by emadg** [explosion/spaCy#1267]
## Info about spaCy
* **spaCy version:** 1.8.2
* **Platform:** Darwin-15.6.0-x86_64-i386-64bit
* **Python version:** 3.6.1
* **Installed models:** en_core_web_sm

First, I should thank you for all the effort you put in this library. It is a really awesome library for doing NLP processing.

I noticed an issue with the word vector similarities. Can you please let me know which method of getting the similarity is advised for similarity of single words and Span/Docs. Thanks!
(I am using spaCy 1.8.2 and the en_core_web_sm model's vectors.)

The cosine similarity of vectors should be in 0<=sim<=1 range. However, it returns values not in this range sometimes.
For example:
- 'duck', 'duck'=1.0000000267444185
- 'geese', 'goose'=1.0000000175639077
- 'wear', 'tread'=-0.050412108052938415
Is this issue related to the insufficient accuracy of calculation in dot product or vector norms?

Also this is strange I think:
- 'duck','ducks'=0.0038021173928484597
- 'duck','goose'=0.0038021173928484597

PS. I know that the vectors should not make sense for all words but this is a strange result I think. I might need to try other vector models for more accurate results.

- Also I get different numbers if I use:
```
nlp = spacy.load('en_model')
# doc vector similarities
nlp('word1').similarity(nlp('word2'))
# lexeme vector similarities
nlp.vocab['word1'].similarity(nlp.vocab['word2'])
```
I could not understand what is causing the difference even by looking at the similarity() function implementation for Lexeme and for Doc objects.

Final question: I want to measure similarity of multi-word phrases with word vectors. Do you have suggestion for more effective method than cosine similarity of average of word vectors in the phrase? 
I think there is new features in version 2.0 for learning representations of document and phrases. I think that might be a better solution to get vectors for phrases.

**Comment by honnibal** [comment]
The 1.x `en_core_web_sm` model has only 5000 vectors, so I wonder whether you're seeing a case where one or both of the words doesn't have a vector set. If so, you'll see very low similarity.

I think I added an epsilon constant in multiple places, and it throws off the similarity calculations slightly. It'd be good if you could verify the cosine calculations for other things you think seem suspicious, to check.

About similarities of longer phrases: there's now a class for learning supervised similarities, although it's still quite bleeding edge functionality. I would suggest you try the word mover's distance algorithm, which is in Gensim and elsewhere. Reportedly that's quite good.

If you calculate a pairwise similarity matrix between the words in the two documents, there are a lot of things you can try that might outperform the cosine of averages. You might also try excluding stopwords.
