### ISSUE TITLE
Incorrect lemmatization for spanish tokens,even if they are present in es_lemma_lookup.json

### ISSUE THREAD

**Issue by torce** [explosion/spaCy#12688]
## How to reproduce the behaviour

```python
import spacy

nlp = spacy.load('es_core_news_lg')

examples = [
    'oído',
    'engrandece',
    'detecté',
    'detectársele',
    'mostrárselo',
    'decírselo',
]

for example in examples:
    doc = nlp(example)
    for token in doc:
        print(token.lemma_)

# Output:
# oer
# engrandecir
# detecté
# detectársele
# mostrárselo
# decir él él
```

The forms `oído`, `engrandece` and `detecté` are present in the [es_lemma_lookup.json](https://raw.githubusercontent.com/explosion/spacy-lookups-data/master/spacy_lookups_data/data/es_lemma_lookup.json) file, but those values are not the ones in the output.

In the case of `detectársele` and `mostrárselo` they are not lemmatized, but `decírselo` is. I will open a separated issue for this case if you prefer.

## Your Environment

* Operating System: Linux desktop 5.19.0-42-generic 43~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Apr 21 16:51:08 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
* Python Version Used: Python 3.10.6
* spaCy Version Used: spaCy version    3.5.3 
* Environment Information:

**Comment by shadeMe** [comment]
Could you inspect the `mode` and `lookups` attributes of the lemmatizer? It could be the case that the lookup table isn't being used.

**Comment by shadeMe** [comment]
Behaviour of the non-trainable lemmatizers can differ between languages. While the default Spanish lemmatizter exclusively uses a rule-based backend, the [French lemmatizer](https://github.com/shadeMe/spaCy/blob/dba4e7becedeeca9d920439e271702680d7e7122/spacy/lang/fr/lemmatizer.py#L7) uses a lookup table as a backoff option. 

You can try using just the [lookup lemmatizer](https://spacy.io/models#design-modify) (section _Switch from rule-based to lookup lemmatization_) to see if it works well enough for your purposes. If not, you could write a custom lemmatizer that uses the lookup table as a backoff.

**Comment by torce** [comment]
Thanks! Seems that the lookup table works well for some lemmas, but fails for others where the rule based one works pretty well. I will try to write a Spanish lemmatizer using the French one as inspiration to see if it works.
