### ISSUE TITLE
Verb get does not lemmatize correctly when it is AUX

### ISSUE THREAD

**Issue by gamendez98** [explosion/spaCy#12690]
## How to reproduce the behaviour
```python
import spacy
nlp = spacy.load('en_core_web_trf')
doc = nlp("It gets done when the code is right.")
print(doc[1].lemma_)
```

## Your Environment

* Operating System: Manjaro 22.1.3 Talos
* Python Version Used: 3.10.10
* spaCy Version Used: 3.4.1
* Environment Information: pip/venv

**Comment by adrianeboyd** [comment]
Thanks for the report! The current `en` pipelines use rules in the `attribute_ruler` component to lemmatize `AUX` forms of be/do/have, but the less standard "get" aux isn't currently included.

The English lemmatizer rules don't currently include any rules or exceptions for `AUX` (there are so few possible forms total), but we can see if it makes sense to extend the attribute ruler exceptions in future version of the `en` pipelines.

If you'd like to extend the existing pipelines to cover this, I think the easiest solution would be to add a rule or two to the attribute ruler. A rule could look similar to the current rule for "does":

```
  {
    "patterns":[
      [
        {
          "TAG":"VBZ",
          "LOWER":"does"
        }
      ]
    ],
    "attrs":{
      "LEMMA":"do",
      "POS":"AUX",
      "MORPH":"Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin"
    },
    "index":0
  },
```

**Comment by adrianeboyd** [comment]
Just a note, we're adding rules for "get" passive lemmas in the upcoming v3.6.0 English pipelines.
