### ISSUE TITLE
Too much memory usage

### ISSUE THREAD

**Issue by VanyaBK** [explosion/spaCy#12728]
![spacy_memory](https://github.com/explosion/spaCy/assets/37258663/03526cc7-ccff-4ff7-933e-d389530ddb5f)
Can you please explain why the spacy package is using 7GB of memory. For context I am using the spacy 3.4.0 version and I want to know how I could minimise the memory usage by spacy?

Code :
`parser_lib_dict = {'es': 'es_core_news_md', 'pt': 'pt_core_news_md'}`
`self.nlp = spacy.load(parser_lib_dict.get(language, 'es_core_news_md'))`

**Comment by kadarakos** [comment]
Hey VanyaBK,

From this information its hard to tell what the issue is and I can only imagine that the text that you are running on is very long.
