### ISSUE TITLE
Custom spaCy NER model not making expected predictions

### ISSUE THREAD

**Issue by MisbahKhan789** [explosion/spaCy#12738]
## Issue

A custom NER model (trained to identify certain code numbers) does not produce predictions in certain documents. 
The tables below show text snippets of pairs of two documents in row#1 and row#2 respectively, where row#1 represents text on which model returns correct prediction and row#2 represents another text on which model does not return correct prediction, despite text1 and text2 being very similar. 

I have tried multiple variations of these texts from row#3 onwards, in an attempt to pinpoint what piece of text is causing differences in predictions. The issue here is- if the model recognizes a given code as the correct inference in one document, why is it not able to identify another similar looking code number as the correct inference, in another similar document.

### Model Inputs and Corresponding Outputs
Example1:
<img width="1162" alt="PC spaCy model input and output" src="https://github.com/explosion/spaCy/assets/15351802/8755fdd3-2c92-45cf-b4f2-203aca4e0c6d">

Example2:
<img width="1193" alt="Screenshot 2023-06-18 at 6 59 41 PM" src="https://github.com/explosion/spaCy/assets/15351802/8b5220dd-7a7a-45f2-b156-57595519d346">

## Environment
* spaCy version: 3.0.6
* Platform: Linux-5.10.178-162.673.amzn2.x86_64-x86_64-with-glibc2.26
* Python version: 3.10.10

**Comment by kadarakos** [comment]
Hey MisbahKhan789,

Thank you for your question. This does not seem to be an Issue like a bug or unexpected behavior of spaCy itself, rather it appears to me like a Discussion about your specific usecase. May I ask you to first checkout the [FAQ](https://github.com/explosion/spaCy/discussions/8226) and then if you do not find answers open a discussion instead? https://github.com/explosion/spaCy/discussions

**Comment by MisbahKhan789** [comment]
Alright, Thanks.
I've opened a discussion here: https://github.com/explosion/spaCy/discussions/12739
