### ISSUE TITLE
Different lemmatization between en_web_md and en_web_sm

### ISSUE THREAD

**Issue by jlandesman** [explosion/spaCy#1273]
Hello, 

I notice a difference between **en_core_web_md** and **en_core_web_sm** lemmatization functions.  For some reason the lemmatization function on *_web_md does not seem to be working.  

I manually downloaded both tar files and uniziped them to separate folders within site-packages/spacy/data

Each folder contains [deps, ner, pos, vocab]

```
nlp = spacy.load('en_core_web_sm') 
text = nlp(u'considering')
[t.lemma_ for t in text]
## ['consider']

nlp = spacy.load('en_core_web_md')
text = nlp(u'considering')
[t.lemma_ for t in text]
## ['considering']
```

Thank you for your help.

**Comment by jlandesman** [comment]
Didn't paste in version info - please see below: 

Info about spaCy

> spaCy version      1.9.0          
>     Location           C:\Anaconda3\lib\site-packages\spacy
>     Platform           Windows-7-6.1.7601-SP1
>     Python version     3.6.1          
>     Installed models    en_core_web_sm, en_core_web_md

**Comment by honnibal** [comment]
This is expected behaviour. The lemma depends partially on the part-of-speech tag, which can differ when different statistical models are used.
