### ISSUE TITLE
doc from_bytes takes unpredictable amount of time.

### ISSUE THREAD

**Issue by rajhans** [explosion/spaCy#1274]
I am storing serialized spacy analysis of docs to save time, and am finding that deserializing can take an unpredictable amount of time.
E.g. consider this code

```
from spacy.tokens.doc import Doc
import spacy
import base64
import time

nlp=spacy.load('en')

def decode(binary_string):
   decoded = base64.b64decode(binary_string)
   start=time.time()
   d = Doc(nlp.vocab)
   d.from_bytes(decoded)
   end = time.time()
   print(end-start)

decode(b'JgAAAAcAAACML7fds3SSuPTHv5/+oYvAReAicBG4CFwELgIAAOCPiIiI')
```

It can take somewhere between 0.001 seconds to 2.53 seconds. Why is this and how can I avoid it taking too long?

## Your Environment
* Operating System: 
Mac OsX
* Python Version Used: 
3.4.3
* spaCy Version Used: 
1.1.2
* Environment Information:

**Comment by honnibal** [comment]
Hey,

Both your spaCy and your Python versions are pretty old. There could be a range of weirdnesses going on here. The serialisation code has been entirely rewritten for Python 2, but it stayed a bit flakey through the 1.x series, as it was based on an over-complicated solution.

If I had to guess, though, I would say the unpredictability had more to do with your system than spaCy. My hunch is that there's a memory usage spike somewhere, and sometimes this causes your system to swap, and other times it doesn't.

**Comment by rajhans** [comment]
I see -- will look more into the system memory usage. Which spacy version (1.8+ or 2.0+) has a better deserialization? We are thinking of migrating to newer spacy but waiting for spacy 2.0.0 to come out of alpha.

**Comment by honnibal** [comment]
spaCy 2 has better serialisation. I understand wanting it's a tough call until spaCy 2 stable is released. We'll keep working on it :)

**Comment by rajhans** [comment]
Thanks -- closing this for now. Shall keep you posted in case something of interest transpires.
