### ISSUE TITLE
Persisting spaCy import error: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+

### ISSUE THREAD

**Issue by vrunm** [explosion/spaCy#12740]
I realize this is a recently common error, but none of the solutions I have found online helped me. I am trying to work with spaCy in Jupyter notebook and VScode on a Mac OS , but every time I try to import spacy, I get the following error:

```
NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
```

I tried

`brew install openssl@1.1`

This didn't work so I then tried to downgrade urllib3 using

`pip install urllib3==1.26.6 `

Didn't work either. I tried using a virtual environment, also didn't work. I've been scouring the web trying to find a solution but nothing seems to work.

**Comment by adrianeboyd** [comment]
See: https://github.com/explosion/spaCy/discussions/12750
