### ISSUE TITLE
Documentation on custom lemmatization

### ISSUE THREAD

**Issue by nkruglikov** [explosion/spaCy#1275]
Hi, I am trying to implement Russian support for spaCy. Russian is a highly inflectional language, which makes lemmatization a very important part in language processing pipeline. I think that before training any Brown clusters or word vectors I need to add a decent lemmatizer in the Tokenizer. I discovered the base class Lemmatizer in spacy/lemmatizer.py, but I am not sure what part of its interface I need to reimplement. There are also some hints that lemmatizer should also do POS tagging, is it true?

**Comment by nkruglikov** [comment]
I discovered that some information on lemmatization and morphology could be found at the [page about POS tagging](https://spacy.io/docs/usage/pos-tagging). This is not very intuitive :)

**Comment by GruffPrys** [comment]
@nkruglikov Make sure you're looking at the Alpha docs for the latest documentation going forwards, for instance: https://alpha.spacy.io/docs/usage/pos-tagging (note the 'alpha' subdomain)

Many of the new language additions to spaCy are using a lookup lemmatization table (see here: https://alpha.spacy.io/docs/usage/adding-languages#lemmatizer ).

I'm hoping that this represents the beginning of a more advanced lemmatization feature as currently it doesn't look like it can deal with the inherent ambiguity in some of the more frequently occurring tokens in my language.    

From what I can tell, the intention is to use a language model to select the appropriate tag:

> To boost the representation, the tagger actually predicts a "super tag" with POS, morphology and dependency label.
https://github.com/explosion/spaCy/issues/1057

Unfortunately (and I'd love to be wrong), it seems I'd need an annotated corpus many times larger than I currently have for a statistical parser to be able to match the performance of a rule based tagger in many of the ambiguous cases I need to overcome. This is especially if the required morphological info for disambiguating lemmas is not part of the Universal Dependencies spec.

I'd love some feedback on this issue too :smiley:

**Comment by ines** [comment]
Happy to share an update on this: lookup lemmatization has now been properly implemented for spaCy v2.0 – see #1413 🎉 The [lemmatizer docs](https://alpha.spacy.io/usage/adding-languages#lemmatizer) have been updated accordingly. For examples, see the languages using the lookup lemmatizer in [`spacy/lang`](https://github.com/explosion/spacy/tree/develop/spacy/lang).

You might also want to check out the discussion in #1085, starting with [this comment](https://github.com/explosion/spaCy/issues/1085#issuecomment-335787241) – it's about how to implement a custom lemmatization solution using pipeline components and extension attributes. This was all recently added to spaCy v2.0 alpha – we also just published a blog post that explains the new features in more detail: https://explosion.ai/blog/spacy-v2-pipelines-extensions
