### ISSUE TITLE
Training NER models on multiple GPUs

### ISSUE THREAD

**Issue by rs-pawanmethre** [explosion/spaCy#12765]
i am training spacy ner model on single gpu using this command : python3 -m spacy train config.cfg  --output output --paths.train train_data.spacy --paths.dev test_data.spacy --gpu-id 0.

How to train model on multiple gpu so that i can give more data fro training, i have 4 gpus of 16GB each.

please somebody kindly help me.

**Comment by danieldk** [comment]
Closing this, let's continue discussion here:

https://github.com/explosion/spaCy/discussions/12764

Also, it would be nice not to post the same question in multiple places. It is more work for us and for you.
