### ISSUE TITLE
Is sense2vec (+model) available for spacy 1.9?

### ISSUE THREAD

**Issue by viksit** [explosion/spaCy#1278]
It appears that the github repo may have become incompatible with the latest versions of spacy. The index.spacy.io link also seems to have been deprecated to download the reddit model.

**Comment by honnibal** [comment]
We're going to be revising sense2vec as a pretty lightweight spaCy extension --- it would now just be a pipeline component that retokenized the text, and a hook to replace the `.vector` attribute. We'll also be retraining sense2vec models -- but not for 1.9 :).
