### ISSUE TITLE
negative contractions ("not") in English 

### ISSUE THREAD

**Issue by fakesecret** [explosion/spaCy#1281]
I think it may be a bug that **"hasn't", "haven't" and "daren't" cannot be tokenized correctly** while the other phrases concerning the "not" contractions can. I only tested often-used cases:

[She, **hasn't**, done, the, housework, .]
[I, **haven't**, done, it, before, .]
[you, **daren't**, do, that]

[We, had, n't, done, that, .]
[We, are, n't, friends, anymore, .]
[It, is, n't, the, truth, .]
[I, do, n't, care]
[It, should, n't, be, .]
[I, must, n't, have, done, that, .]
[It, ca, n't, be, .]
[you, need, n't, do, that]
[You, could, n't, lie, to, me]
[You, were, n't, there]
[She, was, n't, good, at, math, .]
[It, wo, n't, help, .]
[we, sha, n't, make, it]
[I, ai, n't, your, mama]

PS: "hasn't" and "haven't" work well on your displacy page, while "daren't" does not

## Your Environment

* **Python version:** 2.7.12
* **Platform:** Linux-4.4.0-66-generic-x86_64-with-LinuxMint-18.1-serena
* **spaCy version:** 1.9.0
* **Installed models:** en

**Comment by ines** [comment]
Fixed, thanks! Also added a test for this (can't believe we didn't have one before, this was bad).
