### ISSUE TITLE
Parsing problem

### ISSUE THREAD

**Issue by fakesecret** [explosion/spaCy#1282]
**Performance**
Is it normal that the first noun is interpreted as root? The only differerence between two sentences shown below is the case of the first letter, resulting in a parsing tree totally different. While I tested dispacy online, the two trees are the same and correct (like the second one shown below).

**token[token.dep_]**:
tom[ROOT]  and[cc]  his[poss]  friends[nsubj]  are[aux]  visiting[conj]  Paris[dobj]  .[punct]  
Tom[nsubj]  and[cc]  his[poss]  friends[conj]  are[aux]  visiting[ROOT]  Paris[dobj]  .[punct]  

## Your Environment
* **Python version:** 2.7.12
* **Platform:** Linux-4.4.0-66-generic-x86_64-with-LinuxMint-18.1-serena
* **spaCy version:** 1.9.0
* **Installed models:** en

**Comment by honnibal** [comment]
The v2 model is now less case sensitive

https://demos.explosion.ai/displacy/?text=tom%20and%20his%20friends%20are%20visiting%20Paris&model=en_core_web_sm&cpu=1&cph=1
