### ISSUE TITLE
Install Error :ModuleNotFoundError: No module named 'spacy.symbols'

### ISSUE THREAD

**Issue by lvhyml** [explosion/spaCy#12847]
## How to reproduce the behaviour
Follow the installation guide on Github README

* Operating System: Windows 11, WSL 2 Ubuntu 20.04
* Python Version Used: 3.8
* spaCy Version Used: 3.5 
* Environment Information: virtualenv

**Comment by rmitsch** [comment]
Hi @lvhyml, did you install spaCy in a new venv?

**Comment by lvhyml** [comment]
> Hi @lvhyml, did you install spaCy in a new venv?
Yes

**Comment by rmitsch** [comment]
Does this error occur on `import spacy`?

**Comment by lvhyml** [comment]
> Does this error occur on `import spacy`?

No, I got the error from this command: 
python -m spacy download en_core_web_sm

**Comment by rmitsch** [comment]
Could you provide the full stack trace you obtain when running `python -m spacy download en_core_web_sm`? Also, please check whether `python -c "import spacy"` works - and share the stack trace if that fails.
