### ISSUE TITLE
Warning on spaCy versions is confusing for patch version differences

### ISSUE THREAD

**Issue by kinghuang** [explosion/spaCy#12855]
I opened a custom model built on spaCy 3.5.3 in a container with spaCy 3.5.0 installed. This triggers a warning message about potentially incompatible versions. However, the message is confusing when there is a difference in the patch version only (3 vs 0) because the messages only gives up to the minor version of spaCy that was used to train a model (the `lower_version` variable passed as version to the warning).

The following message states that spaCy v3.5 may not be compatible with 3.5.0. At a glance, this looks like the same version. The model's full spaCy version was 3.5.3.

> UserWarning: [W095] Model 'en_tsds_loc_fac' (0.0.0) was trained with spaCy v3.5 and may not be 100% compatible with the current version (3.5.0).

https://github.com/explosion/spaCy/blob/f8f489bcd665719357d13a66d4da7584581c7e2e/spacy/util.py#L896-L910

https://github.com/explosion/spaCy/blob/f8f489bcd665719357d13a66d4da7584581c7e2e/spacy/errors.py#L153-L158

**Comment by shadeMe** [comment]
Thanks for bringing this up! That warning is indeed confusing - we'll modify it to show the patch version as well when it differs between the model's version and the installed one.
