### ISSUE TITLE
Sentence segmentation fails if sentence starts with quotes

### ISSUE THREAD

**Issue by bmurauer** [explosion/spaCy#1285]
The following code splits the sentences right after the first double quote, leading to the two sentences `This is a sentence. "` and `Dont worry!", he said.`. I was expecting the two sentences `This is a sentence.` and `"Dont worry!", he said.`. 

    import spacy
    nlp = spacy.load('en')
    text = 'This is a sentence. "Dont worry!", he said.'
    document = nlp(text)
    print(list(document.sents))

 ## Info about spaCy

* **spaCy version:** 1.9.0
* **Platform:** Linux-4.12.8-2-ARCH-x86_64-with-arch
* **Python version:** 3.6.2
* **Installed models:** en

**Comment by honnibal** [comment]
You're right that this example is incorrect, but this type of input can be tricky to segment. I've been improving the sentence detection in spaCy 2, so this type of error should be a bit rarer.

**Comment by honnibal** [comment]
Interestingly, still broken in v2: https://demos.explosion.ai/displacy/?text=This%20is%20a%20sentence.%20%22Dont%20worry!%22%2C%20he%20said.&model=en_core_web_sm&cpu=1&cph=1

**Comment by rlpatsh** [comment]
May be this is a different issue or topic. Any thoughts on the below question: 

I am trying to segment a sentence logically, so that I can process each part separately. e.g;

`"If the country selected is 'US', then the zip code should be numeric"
`This needs to be broken into :

```
If the country selected is 'US',
then the zip code should be numeric
```
Another sentence with comas should not be broken:
`
The allowed states are NY, NJ and CT`
Any ideas, thoughts how to do this in spacy ?

**Comment by justinas-vd** [comment]
Consider this simple example:

1. First sentence?What is the second one?
2. First sentence!What is the second one?

Missing whitespace (arguably a popular kind of mistype) breaks sentence segmentation and pos tagging in amusing ways (see the output from displaCy).

**Comment by ines** [comment]
We've now added a sentence segmentation section to the docs that explains the different options for customising spaCy's default segmentation strategy:
https://spacy.io/usage/linguistic-features#sbd

We're also hoping that the new models for v2.1.x will do slightly better at this (i.e. produce more accurate parsing results) 👍
