### ISSUE TITLE
Support Pydantic v2

### ISSUE THREAD

**Issue by srhinos** [explosion/spaCy#12863]
[Pydantic has gone live with their new version](https://docs.pydantic.dev/2.0/blog/pydantic-v2-final/)

Being that its production ready and as suggested by Pydantic's [README](https://github.com/pydantic/pydantic):

> Pydantic V2 also ships with the latest version of Pydantic V1 built in so that you can incrementally upgrade your code base and projects: from pydantic import v1 as pydantic_v1.

It should be safe to upgrade and allow folks using poetry (like me) to resolve dependancies in a way that unblocks upgrading to Pydantic v2, FastAPI v0.100.0, etc

**Comment by shadeMe** [comment]
Thanks for bringing this to our attention - We'll look into it. Upgrading to Pydantic v2 will require non-trivial changes to the codebase (across multiple packages) due to the former only supporting Python 3.7+, so we'll have to figure out what the best upgrade path would be.

**Comment by shadeMe** [comment]
Let's use [this issue](https://github.com/explosion/spaCy/issues/12611) to track this discussion.
