### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 335: ordinal not in range(128)

### ISSUE THREAD

**Issue by miguelwon** [explosion/spaCy#12872]
I'm having  this very odd error. It occurs when I open a file and turn on  `spacy.prefer_gpu()`:

```
import spacy
from tqdm import tqdm

spacy.prefer_gpu()
nlp = spacy.load("models/model-best")
    
with open('data/dgsi_chunks.jsonl','r') as f_in:
    for line in tqdm(f_in,total = 4317064):
        continue
```

This is the error I'm getting:

```
/notebooks/env/lib/python3.9/site-packages/spacy/util.py:865: UserWarning: [W095] Model 'pt_pipeline' (0.0.0) was trained with spaCy v3.4 and may not be 100% compatible with the current version (3.4.0). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
  0%|                                                                                                                            | 0/4317064 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/notebooks/teste_error_spacy.py", line 9, in <module>
    for line in tqdm(f_in,total = 4317064):
  File "/notebooks/env/lib/python3.9/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.9/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 335: ordinal not in range(128)
```

If I comment `spacy.prefer_gpu()` it starts working. 

## Info about spaCy

- **spaCy version:** 3.4.0
- **Platform:** Linux-5.19.0-45-generic-x86_64-with-glibc2.31
- **Python version:** 3.9.16

**Comment by adrianeboyd** [comment]
This is indeed a bizarre kind of error, but we have seen similar reports before: #11909. It seems to be a bug in an nvidia driver, and I don't know what the current upstream status is (you'd have to log in with a certain kind of developer account to see the bug report). It possible upgrading to newer version of the nvidia drivers or CUDA could help, but I don't know for sure.

For this example, you can probably explicitly set the encoding on `open` as a workaround, but it's obviously not a general solution.

**Comment by miguelwon** [comment]
Thanks @adrianeboyd! 
This was indeed something related with CUDA. Did `export LC_ALL="POSIX"`as suggested [here](https://github.com/NVIDIA/cuda-python/issues/29#issuecomment-1293648955) and is now working.

**Comment by adrianeboyd** [comment]
Glad to hear it's working!
