### ISSUE TITLE
Transformer NER training and Loading 

### ISSUE THREAD

**Issue by Oumayma68** [explosion/spaCy#12900]
Hey , I am training a NER on my own data on a GPU, using your transformer model.
I have installed Spacy and generated my config.cfg 
I trained the model and I save it under the name best model, I am trying to load it in order to use it but it shows an error : 
Irun this command : nlp_ner = spacy.load("/content/model-best") 
it gives me : RuntimeError: Error(s) in loading state_dict for RobertaModel:
	Missing key(s) in state_dict: "embeddings.position_ids". 

(config.cfg)
 [paths]
train = null
dev = null
vectors = null
init_tok2vec = null

[system]
gpu_allocator = "pytorch"
seed = 0

[nlp]
lang = "en"
pipeline = ["transformer","ner"]
batch_size = 128
disabled = []
before_creation = null
after_creation = null
after_pipeline_creation = null
tokenizer = {"@tokenizers":"spacy.Tokenizer.v1"}

[components]

[components.ner]
factory = "ner"
incorrect_spans_key = null
moves = null
scorer = {"@scorers":"spacy.ner_scorer.v1"}
update_with_oracle_cut_size = 100

[components.ner.model]
@architectures = "spacy.TransitionBasedParser.v2"
state_type = "ner"
extra_state_tokens = false
hidden_width = 64
maxout_pieces = 2
use_upper = false
nO = null

[components.ner.model.tok2vec]
@architectures = "spacy-transformers.TransformerListener.v1"
grad_factor = 1.0
pooling = {"@layers":"reduce_mean.v1"}
upstream = "*"

[components.transformer]
factory = "transformer"
max_batch_items = 4096
set_extra_annotations = {"@annotation_setters":"spacy-transformers.null_annotation_setter.v1"}

[components.transformer.model]
@architectures = "spacy-transformers.TransformerModel.v3"
name = "roberta-base"
mixed_precision = false

[components.transformer.model.get_spans]
@span_getters = "spacy-transformers.strided_spans.v1"
window = 128
stride = 96

[components.transformer.model.grad_scaler_config]

[components.transformer.model.tokenizer_config]
use_fast = true

[components.transformer.model.transformer_config]

[corpora]

[corpora.dev]
@readers = "spacy.Corpus.v1"
path = ${paths.dev}
max_length = 0
gold_preproc = false
limit = 0
augmenter = null

[corpora.train]
@readers = "spacy.Corpus.v1"
path = ${paths.train}
max_length = 0
gold_preproc = false
limit = 0
augmenter = null

[training]
accumulate_gradient = 3
dev_corpus = "corpora.dev"
train_corpus = "corpora.train"
seed = ${system.seed}
gpu_allocator = ${system.gpu_allocator}
dropout = 0.1
patience = 1600
max_epochs = 0
max_steps = 20000
eval_frequency = 200
frozen_components = []
annotating_components = []
before_to_disk = null
before_update = null

[training.batcher]
@batchers = "spacy.batch_by_padded.v1"
discard_oversize = true
size = 2000
buffer = 256
get_length = null

[training.logger]
@loggers = "spacy.ConsoleLogger.v1"
progress_bar = false

[training.optimizer]
@optimizers = "Adam.v1"
beta1 = 0.9
beta2 = 0.999
L2_is_weight_decay = true
L2 = 0.01
grad_clip = 1.0
use_averages = false
eps = 0.00000001

[training.optimizer.learn_rate]
@schedules = "warmup_linear.v1"
warmup_steps = 250
total_steps = 20000
initial_rate = 0.00005

[training.score_weights]
ents_f = 1.0
ents_p = 0.0
ents_r = 0.0
ents_per_type = null

[pretraining]

[initialize]
vectors = ${paths.vectors}
init_tok2vec = ${paths.init_tok2vec}
vocab_data = null
lookups = null
before_init = null
after_init = null

[initialize.components]

[initialize.tokenizer]

**Comment by adrianeboyd** [comment]
Hi, thanks for the report! We are aware that there are going be incompatibilities with certain types of `transformer` models saved with `transformers` 4.30 or earlier and then loaded with `transformers` 4.31+.

We're trying to allow newer versions of `transformers` in a way that doesn't cause too many issues for users, but as far as we can tell there's not going to be a good way to avoid them completely.

To try to see what's going on and how we can help users more in the future, can I ask some questions?

1. How did you install `spacy-transformers`?

   Did you run `pip install spacy-transformers` or `pip install spacy[transformers]`? Were you following directions from a quickstart or tutorial?

1. What versions of `transformers` and `spacy-transformers` do you have installed? (Check with `pip list` or `pip freeze`.)

1. If you run `pip check`, is there an error or warning that `transformers` is not compatible with `spacy-transformers`? It might look like this:

   ```
   spacy-transformers 1.2.5 has requirement transformers<4.31.0,>=3.4.0, but you have transformers 4.31.0.
   ```

1. Do you know whether you upgraded `transformers` or `spacy-transformers` after training the model or were you trying to load it in a new venv?

1. If you scroll up in the error message, is there a warning that looks like this?

   ```
   UserWarning: Error loading saved torch model. If the error is related to unexpected key(s) 
   in state_dict, a possible workaround is to load this model with 'transformers<4.31'. 
   Alternatively, download a newer compatible model or retrain your custom model with the 
   current transformers and spacy-transformers versions. For more details and available 
   updates, run: python -m spacy validate
   ```

**Comment by Oumayma68** [comment]
1/ I use pip install spacy-transformers 
2/ version of spacy-transformers: 1.3.0  , version of transformers: 4.31.0
3/when I run pip check, there aren't any errors o warnings,the output of the command is:                                                            ipython 7.34.0 requires jedi, which is not installed.
pygobject 3.42.1 requires pycairo, which is not installed.
4/ I trained the model on google colab 
5/ There isn't an error like the one you show it

**Comment by adrianeboyd** [comment]
So you are training and loading in the exact same colab session?

Can you copy and paste the whole traceback from `spacy.load`?

Here's what it looks like when I try to train and load a transfomer+NER model in colab:

https://colab.research.google.com/drive/1R7Gt5CdPx7HCYGpUrSMKN7efta6fHHJl?usp=sharing

I could only replicate the error if I downgraded `transformers` after training the model, and the warning was present (although you have to scroll to the right a lot to read it).

```
/usr/local/lib/python3.10/dist-packages/spacy_transformers/layers/hf_shim.py:136: UserWarning: Error loading saved torch model. If the error is related to unexpected key(s) in state_dict, a possible workaround is to load this model with 'transformers<4.31'. Alternatively, download a newer compatible model or retrain your custom model with the current transformers and spacy-transformers versions. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-1-0026e924894a>](https://localhost:8080/#) in <cell line: 4>()
      2 get_ipython().run_line_magic('cd', 'ner_demo')
      3 import spacy
----> 4 nlp = spacy.load("output/model-best")

13 frames
[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in load_state_dict(self, state_dict, strict)
   2039 
   2040         if len(error_msgs) > 0:
-> 2041             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
   2042                                self.__class__.__name__, "\n\t".join(error_msgs)))
   2043         return _IncompatibleKeys(missing_keys, unexpected_keys)

RuntimeError: Error(s) in loading state_dict for RobertaModel:
	Missing key(s) in state_dict: "embeddings.position_ids".
```

**Comment by Oumayma68** [comment]
yes I am training and loading the moddel in the same colab session . 
I rerun the code and it gives me another error: 
ValueError                                Traceback (most recent call last)
[<ipython-input-21-3ba03ffc5e2f>](https://localhost:8080/#) in <cell line: 1>()
----> 1 nlp_ner = spacy.load("/content/model-best")

6 frames
[/usr/local/lib/python3.10/dist-packages/spacy/language.py](https://localhost:8080/#) in create_pipe(self, factory_name, name, config, raw_config, validate)
    658         name (Optional[str]): Optional name to assign to component instance.
    659             Defaults to factory name if not set.
--> 660         config (Dict[str, Any]): Config parameters to use for this component.
    661             Will be merged with default config, if available.
    662         raw_config (Optional[Config]): Internals: the non-interpolated config.

ValueError: [E002] Can't find factory for 'transformer' for language English (en). This usually happens when spaCy calls `nlp.create_pipe` with a custom component name that's not registered on the current language class. If you're using a Transformer, make sure to install 'spacy-transformers'. If you're using a custom component, make sure you've added the decorator `@Language.component` (for function components) or `@Language.factory` (for class components).

Available factories: attribute_ruler, tok2vec, merge_noun_chunks, merge_entities, merge_subtokens, token_splitter, doc_cleaner, parser, beam_parser, lemmatizer, trainable_lemmatizer, entity_linker, ner, beam_ner, entity_ruler, tagger, morphologizer, senter, sentencizer, textcat, spancat, spancat_singlelabel, future_entity_ruler, span_ruler, textcat_multilabel, en.lemmatizer

**Comment by adrianeboyd** [comment]
Hmm, sorry, that wasn't the easiest demo example to run. Having to restart the runtime in the middle to test with two different versions makes things difficult. I'll delete it and the link above because I think it was more confusing than helpful.

After looking at the incompatibilities and difficulties a bit more, I think we will yank `spacy-transformers` v1.3.0 from pypi while we decide how to proceed.

For your project, please uninstall `spacy-transformers` and reinstall with `pip install spacy[transformers]` to get an older version. Unfortunately you'll need to retrain your NER model with your updated venv.

**Comment by YusufCandraArif** [comment]
@adrianeboyd Hello, Sir. Has this issue been resolved? I also encountered the same problem. "RuntimeError: Error(s) in loading state_dict for BertModel: Missing key(s) in state_dict: "embeddings.position_ids".
python3.7
spacy-transformers ==1.2.5

thank you..

**Comment by rmitsch** [comment]
> Hello, Sir. Has this issue been resolved? I also encountered the same problem. "RuntimeError: Error(s) in loading state_dict for BertModel: Missing key(s) in state_dict: "embeddings.position_ids".

Please don't @ the maintainers - we see your post without that and will respond it. This hasn't been resolved yet, so try the recommended workaround:
> For your project, please uninstall spacy-transformers and reinstall with pip install spacy[transformers] to get an older version. Unfortunately you'll need to retrain your NER model with your updated venv.
