### ISSUE TITLE
How to load Data Frame or csv file in spacy pipeline nlp?

### ISSUE THREAD

**Issue by Rahulvks** [explosion/spaCy#1290]
I am trying to load data frame csv into spacy pipeline. I am getting argument string error here is my code

`from __future__ import unicode_literals
nlp = spacy.load('en')

data = pd.read_csv("sometextdata.csv")
text = []
for line in data.Line:
    text.append(clean_text(line))
     text_spacy = nlp(data['Line'])
    data['Line'].apply(nlp)
    document = nlp(text)
TypeError: Argument 'string' has incorrect type (expected unicode, got str)``

I tried to load in different ways i got same error.

## Your Environment

* Operating System: Mac os
* Python Version Used: 2.7

**Comment by honnibal** [comment]
spaCy requires unicode inputs --- you've provided binary strings. I'm not sure what the correct pandas usage is; if you had a list the likely solution would be `unicode_strings = [s.decode('utf8') for s in byte_strings]`

**Comment by brickpattern** [comment]
if Pandas is not a absolute requirement, one could as well use the standard Python "open" command. 
`my_text = open(path_to_file).read()` 
`nlp=spacy.en.load()`
`doc=nlp(text)`
