### ISSUE TITLE
LOWER does not always work when presented with random casing

### ISSUE THREAD

**Issue by mjsonofharry** [explosion/spaCy#12906]
## How to reproduce the behavior

Create a matcher with the following pattern:
```
[{'LOWER': 'git'}]
```
Then match on this sentence:

```
GitHub is a platform and cloud-based service for software development and version control using gIT.
```

Observe that "gIT" is correctly matched. Then try matching on this sentence:

```
GitHub is a platform and cloud-based service for software development and version control using giT.
```

This time, observe that "giT" is not matched.

[Here's a demo of the problem](https://demos.explosion.ai/matcher?text=GitHub%20is%20a%20platform%20and%20cloud-based%20service%20for%20software%20development%20and%20version%20control%20using%20giT.%0A%0AGitHub%20is%20a%20platform%20and%20cloud-based%20service%20for%20software%20development%20and%20version%20control%20using%20gIT.%0A&model=en_core_web_sm&pattern=%5B%7B%22id%22%3A0%2C%22attrs%22%3A%5B%7B%22name%22%3A%22LOWER%22%2C%22value%22%3A%22git%22%7D%5D%7D%5D) I made using the online rule-based matcher explorer.

Alternatively, here's a code snippet:

```python
from spacy.matcher import Matcher
import spacy

spacy.cli.download('en_core_web_sm')
model = spacy.load('en_core_web_sm')

matcher = Matcher(model.vocab)
matcher.add(key=0, patterns=[[{'LOWER': 'git'}]])

sentence1 = "GitHub is a platform and cloud-based service for software development and version control using gIT."
sentence2 = "GitHub is a platform and cloud-based service for software development and version control using giT."

doc1 = model(sentence1)
matches1 = matcher(doc1, as_spans=True)
print(f"{sentence1} {matches1}")

doc2 = model(sentence2)
matches2 = matcher(doc2, as_spans=True)
print(f"{sentence2} {matches2}")
```

Punctuation seems to play a role, but I'm not sure how. If you remove the period from the end of the failing sentence, the matcher works.

## Your Environment

- **spaCy version:** 3.6.1
- **Platform:** macOS-13.5-arm64-arm-64bit
- **Python version:** 3.9.17
- **Pipelines:** en_core_web_sm (3.6.0)

**Comment by rmitsch** [comment]
Thanks for raising this issue, @mjsonofharry. We'll look into it and update here.

**Comment by rmitsch** [comment]
So this is related to incorrect tokenization. The matcher works as intended, but in the second sentence, the dot is added to the word. To check, run this:

```python
for token in doc1:
    print(token)
for token in doc2:
    print(token)
```

You'll notice that for `doc2` the last token is "gIT.", which is why this token doesn't match the `[{'LOWER': 'git'}]` rule. To circumvent this, you might want to add a [special tokenization rule](https://spacy.io/usage/linguistic-features#special-cases).
