### ISSUE TITLE
Annotation format in documentation does not match real format

### ISSUE THREAD

**Issue by nkruglikov** [explosion/spaCy#1291]
In the [training section](https://spacy.io/docs/usage/adding-languages#train-tagger-parser) of Adding Languages tutorial there are reference to the [annotation format](https://spacy.io/docs/api/annotation#json-input) for training. It seems to disagree with the code for JSON annotation reading ([`gold.pyx`](https://github.com/explosion/spaCy/blob/master/spacy/gold.pyx#L153)):
```python
...
for paragraph in doc['paragraphs']:
    sents = []
    for sent in paragraph['sentences']:
...
```
In the description of the format, section `paragraph` contains section `sents`, but in the code `sentences` are expected. Moreover, the JSON is expected to be a list of documents, which is not described in documentation. Finally, by the code, `tokens` should be the child of `sentences`, not sibling, and format of `tokens` is completely different. I suspect that documentation on that matter is outdated significantly.

**Comment by honnibal** [comment]
Thanks, will fix.
