### ISSUE TITLE
EntityRuler match order is dependent on Python's set implementation

### ISSUE THREAD

**Issue by nrodnova** [explosion/spaCy#12919]
This is not necessarily a bug, and I am not sure there's any elegant solution to the problem, but please hear me out. I was migrating my model from python 3.7 to 3.10, and I got some seemingly random differences. I drilled it down to `EntityRuler` behavior when different rules match the same span. I am still on spaCy `v3.1`, but I looked in the code, the same behavior exists in `v3.6`. It all drills down to this in `entityruler.py` (master branch, line 175, `match` method):
```
final_matches = set(
            [(m_id, start, end) for m_id, start, end in matches if start != end]
        )
```
Until this point, the match order is predictable (the order in which patterns were added). However, when a set is created, the order changes to whatever the `set` implementation dictates. Apparently, somewhere between python 3.7 and 3.10, that implementation has changed, and thus the order in which the matches are returned changed as well.

I was wondering what you guys/gals think about predictability of the returned matches here (and named entities as a result), and its dependency on `set` implementation in Python.

## How to reproduce the behaviour

```
from spacy import load as load_spacy
from spacy.pipeline import EntityRuler

nlp = load_spacy('en_core_web_sm')

# 2 patterns matching the same word, with 2 different ent_ids_ specified
pattern_1 = {'label': 'DEVICE', 'pattern': [{'LOWER': {'IN': ['bypass',  'stent']}}], 'id': 'stent'}
pattern_2 = {'label': 'DEVICE', 'pattern': [{'LOWER': {'IN': ['bypass',  ]}}], 'id': 'repair'}

ruler = EntityRuler(nlp, validate=True, overwrite_ents=True)
ruler.add_patterns([pattern_1, pattern_2])
doc = nlp.tokenizer('Severe coronary atherosclerotic disease with prior bypass surgery.')
ruler(doc)

entity = doc.ents[0]
print("entity: %s, label: %s, ent_id: %s" % (entity, entity.label_,  entity.ent_id_))
```
Output:
```
Python 3.7:
entity: bypass, label: DEVICE, ent_id: repair

Python 3.10:
entity: bypass, label: DEVICE, ent_id: stent

```
Code from `entityruler.py`:
```
matches = list(ruler.matcher(doc)) + list(ruler.phrase_matcher(doc))
print("Matcher:", matches)

final_matches = set([(m_id, start, end) for m_id, start, end in matches if start != end])
print("Set:    ", list(final_matches))

get_sort_key = lambda m: (m[2] - m[1], -m[1])
final_matches = sorted(final_matches, key=get_sort_key, reverse=True)
print("Sorted: ", final_matches)
```
Output:
```
Python 3.7:
Matcher: [(11861990552470164073, 6, 7), (9586214660192362110, 6, 7)]
Set:     [(9586214660192362110, 6, 7), (11861990552470164073, 6, 7)]
Sorted:  [(9586214660192362110, 6, 7), (11861990552470164073, 6, 7)]

Python 3.10:
Matcher: [(11861990552470164073, 6, 7), (9586214660192362110, 6, 7)]
Set:     [(11861990552470164073, 6, 7), (9586214660192362110, 6, 7)]
Sorted:  [(11861990552470164073, 6, 7), (9586214660192362110, 6, 7)]
```
Code demonstrating implementation change in Python's `set`:
```
x = {(5, 1, 2),(4, 1, 2), (3, 1, 2), (2, 1, 2), (1, 1, 2)}
sorted(x, key=get_sort_key, reverse=True)
```
Output:
```
Python 3.7:
[(5, 1, 2), (1, 1, 2), (2, 1, 2), (4, 1, 2), (3, 1, 2)]

Python 3.10:
[(2, 1, 2), (3, 1, 2), (5, 1, 2), (4, 1, 2), (1, 1, 2)]
```
## Info about spaCy (python3.7)

- **spaCy version:** 3.1.0
- **Platform:** Darwin-21.5.0-x86_64-i386-64bit
- **Python version:** 3.7.9
- **Pipelines:** en_core_web_trf (3.1.0), en_core_web_sm (3.1.0), en_core_web_md (3.1.0), en_core_web_lg (3.1.0), eon_actionable_findings_core_web_sm (1.0.0)

## Info about spaCy (python3.10)

- **spaCy version:** 3.1.7
- **Platform:** macOS-12.4-x86_64-i386-64bit
- **Python version:** 3.10.11
- **Pipelines:** en_core_web_sm (3.1.0)

**Comment by rmitsch** [comment]
Hi @nrodnova, thanks for reporting this. As this is, as you noted, a Python implementation detail, I'm not sure whether we want to do this differently. Is this behavior affecting you negatively?

**Comment by nrodnova** [comment]
@rmitsch Not necessarily. At this point it helped to find unwanted duplicated rules after the python version switch. But in general, I question something that should have predicted order (ideally) being dependent on a python implementation detail that can change.

**Comment by rmitsch** [comment]
That's a fair point. We will discuss this internally. Thanks for bringing it up!

**Comment by rmitsch** [comment]
After talking this through internally we decided not to change the current behavior, as we don't guarantee or document a fixed order. Thanks again!
