### ISSUE TITLE
Dependency on protobuf of French and Ukrainian transformer model

### ISSUE THREAD

**Issue by BLKSerene** [explosion/spaCy#12925]
When installing the French and Ukrainian transformer model (`fr-dep-news-trf` and `uk-core-news-trf`), it requires `protobuf` < 3.21.0, but the latest version is `protobuf` 4.24.1. I'm wondering whether it is possible the unpin the dependency version on `protobuf`?

## Your Environment

* Operating System: Windows 11 x64
* Python Version Used: 3.10.12
* spaCy Version Used: 3.6.1

**Comment by svlandeg** [comment]
Hi! Are you using the French, or the Ukrainian model (or both)? Because AFAIR, the Ukrainian transformer model doesn't actually work with `protobuf` v4, hence the upper pin. I think we could potentially expand the range for the French one, though.

**Comment by BLKSerene** [comment]
I use `spaCy` in my multilingual corpus tool project and models would be automatically downloaded when needed and used by my users working with corpora in different languages (including both French and Ukrainian).
