### ISSUE TITLE
[Request] Remove/refactor the logic requiring "import pip" in spacy.cli.link module

### ISSUE THREAD

**Issue by tokenmathguy** [explosion/spaCy#1293]
Love the spaCy project. Thanks for your hard work!

Coupling of package manager/installer in the spacy library as a runtime dependency results in issues for build systems without pip. Excising pip.get_installed_distributions() would remove the need for pip as a runtime dependency. This could likely get replaced by using pkg_resources (since get_installed_distributions is really just a thin shim on pkg_resources.working_set).

## Your Environment
* Operating System: AmazonLinux 2012
* Python Version Used: 2.7
* spaCy Version Used: 1.8.2
* Environment Information:

**Comment by honnibal** [comment]
We'd like to consider switching to `entry_points` instead of this, but I'm aware that this can have its own issues. I thought `pip` was in the Python standard library though --- could you elaborate on what systems can be expected to not have `pip`?

**Comment by tokenmathguy** [comment]
pip is not a part the standard library:

> ...reflects the fact that pip is an independent project with its own release cycle...

The standard library makes it easy to bootstrap pip, however, and is bootstrapped by default in python installs:

https://docs.python.org/2/library/ensurepip.html
https://docs.python.org/3/library/ensurepip.html

Agreed, this is not a common use case, but one that occurs in environments that have historical build systems that enforce tighter licensing and security constraints on packages available for large teams of engineers.

But I would argue that it is the philosophical reasons to not require pip as a "runtime" dependency of a machine learning library that would drive excising importing pip in the library itself. Yes, it is important for installation and bootstrapping, but pip should not be required for the actual text processing and utilization of the library.

**Comment by ines** [comment]
Thanks for the details on this 👍  This makes sense, and we'd be happy to drop the pip dependency and replace it with `pkg_resources.working_set.by_key`. Will test this on `develop`! (The only other place where pip is used / required is in the model downloads – but here it's only called as a subprocess, so this is no problem.)

**Comment by tokenmathguy** [comment]
Awesome work. Thanks!
