### ISSUE TITLE
Wrong lemmatization of words with -ed ending in basic form

### ISSUE THREAD

**Issue by bartonaz** [explosion/spaCy#1296]
Lemmatization in the english model of Spacy wrongly removes **ed** ending from words that have it in their basic form:
   * _need_ > _ne_
   * _feed_ > _fee_
   * _bleed_ > _ble_

It would be nice if such words were properly taken into account by the lemmatizer.

**Comment by honnibal** [comment]
Thanks, I'm not sure when this regression was introduced. I could've sworn we had tests for this.

**Comment by honnibal** [comment]
Should be fixed now :)
