### ISSUE TITLE
dates not getting extracted

### ISSUE THREAD

**Issue by ankitarath2011** [explosion/spaCy#1299]
* **Python version:** 2.7.13  (64 bit)
* **Platform:** Windows-10-10.0.14393
* **spaCy version:** 1.9.0
* **Installed models:** en

Issue: - I am using spacy to extract named entities. But sometimes it is not extracting entities properly.

e.g. mystr = "had booked a ticket for 23rd Dec"   for this one it is giving 23rd as ordinal. I want 23rd Dec as a DATE.

Please tell me how to fix these things.

Moreover when I am giving location names in small case it is not  capturing. Please suggest on this too as in my case string will always be in small case.

**Comment by honnibal** [comment]
You might find the spaCy 2 models more accurate for your use-case. You can download it with `pip install spacy-nightly`. You can also update the models, training them to be less case-sensitive: http://alpha.spacy.io/docs/usage/training.

This post provides some useful information about this: https://explosion.ai/blog/pseudo-rehearsal-catastrophic-forgetting

**Comment by ankitarath2011** [comment]
Thanks for the reply. I will try spacy-nightly.
I was just trying the training thing. 
In my training data I have multi-word entities as well. But I am getting issues with this.
e.g. In training data I have following sentence.
sent = "get me some information on asian fusion" 
entity music = "asian fusion"

But when in test data when I am giving "searching for asian food"
here "asian food" is getting extracted as entity "music"

Can you please give some suggestions on this as well.

**Comment by honnibal** [comment]
Well...You might need to have more data. Or different data. Or different settings. I tried to explain some of the considerations in that blog post. Past that, it's hard to advise.

**Comment by ankitarath2011** [comment]
Thanks @honnibal Will try doing it.
