### ISSUE TITLE
Segmentation fault (core dumped) when using spacy installation with GPU

### ISSUE THREAD

**Issue by kormilitzin** [explosion/spaCy#13033]
This is a **new** behaviour I noticed since spaCy > 3.5 (never had it before 3.5 version).

## How to reproduce the behaviour

I have CUDA 9.1:

> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2017 NVIDIA Corporation
> Built on Fri_Nov__3_21:07:56_CDT_2017
> Cuda compilation tools, release 9.1, V9.1.85

To install, I am using the standard approach:

```
python -m venv .env
source .env/bin/activate
pip install -U pip setuptools wheel
pip install -U 'spacy[cuda91,transformers,lookups]'
python -m spacy download en_core_web_trf
```

when I run python and load spaCy models (even the simplest one), I get the segfault:

```
Python 3.8.0 (default, Dec  9 2021, 17:53:27)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> spacy.prefer_gpu()
False
>>> nlp = spacy.load('en_core_web_sm')
Segmentation fault (core dumped)
```

Perhaps, there is some incompatibility with my CUDA, as after the installation spaCy doesn't detect it and causes segfault.

Interestingly, when I run 

> spacy.require_gpu()

 it gives the following error:

> >>> spacy.require_gpu()
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/mnt/sde/andrey/venvs/nlp/lib/python3.8/site-packages/thinc/util.py", line 230, in require_gpu
>     raise ValueError("Cannot use GPU, CuPy is not installed")
> ValueError: Cannot use GPU, CuPy is not installed

which is strange, as I do have `cupy` installed (please see below under the list of installed packages).

HOWEVER, **without** GPU, it works fine:

```
> Python 3.8.0 (default, Dec  9 2021, 17:53:27)
> [GCC 8.4.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import spacy
> >>> spacy.__version__
> '3.6.1'
> >>> nlp = spacy.load('en_core_web_sm')
> >>> nlp = spacy.load('en_core_web_trf')
> >>> spacy.prefer_gpu()
> False
> >>>
```

I am wondering if anyone has experienced a similar behaviour and may point me where to look at to fix it?

## Info about spaCy

- **spaCy version:** 3.6.1
- **Platform:** Linux-5.4.0-150-generic-x86_64-with-glibc2.27
- **Python version:** 3.8.0
- **Pipelines:** en_core_web_sm (3.6.0), en_core_web_trf (3.6.1)

`pip freeze`

```
annotated-types==0.5.0
blis==0.7.11
catalogue==2.0.10
certifi==2023.7.22
charset-normalizer==3.3.0
click==8.1.7
cmake==3.27.5
confection==0.1.3
cupy-cuda91==7.8.0
cymem==2.0.8
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.6.0/en_core_web_sm-3.6.0-py3-none-any.whl#sha256=83276fc78a70045627144786b52e1f2728ad5e29e5e43916ec37ea9c26a11212
fastrlock==0.8.2
filelock==3.12.4
fsspec==2023.9.2
huggingface-hub==0.17.3
idna==3.4
Jinja2==3.1.2
langcodes==3.3.0
lit==17.0.1
MarkupSafe==2.1.3
mpmath==1.3.0
murmurhash==1.0.10
networkx==3.1
numpy==1.24.4
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
packaging==23.1
pathy==0.10.2
pkg_resources==0.0.0
preshed==3.0.9
pydantic==2.4.2
pydantic_core==2.10.1
PyYAML==6.0.1
regex==2023.8.8
requests==2.31.0
safetensors==0.3.3
six==1.16.0
smart-open==6.4.0
spacy==3.6.1
spacy-alignments==0.9.1
spacy-legacy==3.0.12
spacy-loggers==1.0.5
spacy-lookups-data==1.0.5
spacy-transformers==1.2.5
srsly==2.4.8
sympy==1.12
thinc==8.1.12
tokenizers==0.13.3
torch==2.0.1
tqdm==4.66.1
transformers==4.30.2
triton==2.0.0
typer==0.9.0
typing_extensions==4.8.0
urllib3==2.0.5
wasabi==1.1.2
```

**Comment by kormilitzin** [comment]
So, I found a solution. Obviously, the problem was with CUDA and its version, so I tried literally every single option (as well as completely deleting my virtual environment and starting from scratch):

```
pip install -U 'spacy[cuda91,transformers,lookups]'
...
pip install -U 'spacy[cuda92,transformers,lookups]'
...
pip install -U 'spacy[cuda100,transformers,lookups]'
...
pip install -U 'spacy[cuda101,transformers,lookups]'
...
pip install -U 'spacy[cuda102,transformers,lookups]'
...
etc
```
 and one them worked for me as a charm

Interestingly, the `spacy[cuda-autodetect]` option was not very helpful.

Clearly, trying one by one is by far not the most optimal way to install spaCy with GPU and to troubleshoot the problem, however, it did the job. I hope this hacky solution may be helpful to others who had a similar issue.

I am closing this issue as resolved.

**Comment by adrianeboyd** [comment]
As a note, the cupy developers have run into complicated pip/setup problems with `cupy-wheel`, the package used by `cuda-autodetect`, and they're discontinuing `cupy-wheel` for cupy v13+.

As of spacy v3.7, we no longer recommend the extra `cuda-autodetect` in the install quickstart. Instead most users would use `cuda11x` or `cuda12x` for support for newer CUDA releases.

**Comment by kormilitzin** [comment]
Thank you @adrianeboyd, this is helpful. I have a few platforms where I use spaCy and previously `cuda-autodetect` was saving me time. I will adapt my installation routine following your advice.

**Comment by adrianeboyd** [comment]
I also had high hopes for `cupy-wheel` to make things easier for our users, but it's just not really possible with `pip` right now.
