### ISSUE TITLE
Extracting universal features

### ISSUE THREAD

**Issue by knyghty** [explosion/spaCy#1304]
I'm wondering if there's a way to extract universal features from text. Currently it's easy to get the universal tags out, but for more specific cases where I want to extract just articles, not all determiners, or negations or (non-numeric) quantifiers, I can't seem to find a way to do this.

It seems like I can get negations with `token.dep_ == 'neg'` but I'm not sure how reliable it is.

**Comment by honnibal** [comment]
Currently we don't have a good API set up for getting morphological features. However, you can always access a fine-grained tag at `token.tag_`, and look this up in the tag map using `nlp.vocab.morphology.tag_map`. This should provide you with additional information.

**Comment by honnibal** [comment]
Finally implemented in #2807 🎉
