### ISSUE TITLE
[2.0] [English] Third person verbs don't get lemmatised correctly

### ISSUE THREAD

**Issue by notnami** [explosion/spaCy#1305]
Minimal example:
```

doc = nlp('This app works well')


for token in doc:
    print(token, token.lemma_)
```
    
Output:

```
This this
app app
works works  # this should be "work"
well well
```

## Info about spaCy

* **spaCy version:** 2.0.0a13
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **Python version:** 3.6.2
* **Models:** en_core_web_sm, en_default, en_vectors_web_lg

**Comment by honnibal** [comment]
Thanks! I see where this went wrong.

**Comment by honnibal** [comment]
Fixed on develop :)
