### ISSUE TITLE
Custom tokenizer needs every arg to init (bug or doc :)

### ISSUE THREAD

**Issue by thomasopsomer** [explosion/spaCy#1309]
Hi,
I'm using spacy 2.0.0a13 and I tried to customize the tokenizer following the [example in the doc](https://alpha.spacy.io/docs/usage/customizing-tokenizer#native-tokenizers). But it raises
```
  File "<stdin>", line 3, in custom_tokenizer
  File "spacy/tokenizer.pyx", line 23, in spacy.tokenizer.Tokenizer.__init__ (spacy/tokenizer.cpp:3137)
    def __init__(self, Vocab vocab, rules, prefix_search, suffix_search, infix_finditer, token_match=None):
TypeError: __init__() takes at least 5 positional arguments (1 given)
```

In order to make it work one need to give the `Tokenizer` all args
```python
cutsom_tokenizer = Tokenizer(vocab=nlp.vocab, rules=tokenizer_exceptions,
                             prefix_search=prefix_search,
                             suffix_search=suffixes_search,
                             infix_finditer=infix_re.finditer)
```

I'm not sure if it's intended. The more practical would be that non provided args are by default equal to the default tokenizer args, however it depends on the language... Otherwise maybe show in the doc where to find the default values, for instance for english:
```python
from spacy.lang.punctuation import (
    TOKENIZER_PREFIXES, TOKENIZER_SUFFIXES, TOKENIZER_INFIXES
)
from spacy.lang.tokenizer_exceptions import BASE_EXCEPTIONS
from spacy.lang.en.tokenizer_exceptions import TOKENIZER_EXCEPTIONS
from spacy.util import update_exc

tokenizer_exceptions = update_exc(BASE_EXCEPTIONS, TOKENIZER_EXCEPTIONS)
...
```

## Your Environment

* Operating System: macOs
* Python Version Used: 2.7.12 
* spaCy Version Used: 2.0.0a13
* Environment Information:

**Comment by ines** [comment]
Fixed in b0f6fd3f1db76131c230b317caba946ce516a193!
