### ISSUE TITLE
Update PhraseMatcher in spacy 2.0

### ISSUE THREAD

**Issue by thomasopsomer** [explosion/spaCy#1311]
Hey, last issue for the day :)

I've been testing spacy 2.0, and it seems that the PhraseMatcher didn't get refreshed :) The matcher object changed a bit, which causes some issue in the initialization of the PhraseMatcher object. (now the `Matcher` takes only one arg `vocab` and the call to `matcher.add` need to be changed)

Actually I started fixing it, but I noticed that the `Matcher` do not use `_acceptors` anymore, and the PhraseMatcher used an acceptor fct `accept_match`. It's still working without it, but I guess it wasn't here for nothing... :)

Any insight, advice for fixing / using the PhraseMatcher in v2 ?

**Comment by ines** [comment]
Sorry, this should have probably been mentioned more explicitly in the v2.0 alpha release notes: The `PhraseMatcher` still isn't 100% implemented, but will definitely be there for the stable release.

**Comment by honnibal** [comment]
See https://github.com/explosion/spaCy/pull/1343 :)
