### ISSUE TITLE
The en_core_web_trf model results in zero output

### ISSUE THREAD

**Issue by HarounAbdelsamad** [explosion/spaCy#13147]
### Discussed in https://github.com/explosion/spaCy/discussions/13145

<div type='discussions-op-text'>

<sup>Originally posted by **HarounAbdelsamad** November 22, 2023</sup>
I tried training the en_core_web_trf model based on datasets i have but after training and evaluation the fscore, recall and precision are all zero. I tried using the small model works fine. I changed the code so that the transformer component is added to the pipe and also use another config file for this. Here is my code for reference:
Could anybody help me or direct me towards the issue?
[code.txt](https://github.com/explosion/spaCy/files/13442430/code.txt)

</div>

**Comment by rmitsch** [comment]
Please don't open duplicate tickets. Continuing the discussion in https://github.com/explosion/spaCy/discussions/13145.
