### ISSUE TITLE
tokens_from_list breaking in V2 when running individual pipeline components

### ISSUE THREAD

**Issue by christian-storm** [explosion/spaCy#1314]
https://github.com/explosion/spaCy/blob/456bb8a74c384bcef58d562525c5ce914b0bed76/spacy/tokenizer.pyx#L64

For v2 shouldn't this be
`return Doc(self.vocab, words=strings, spaces=[True] * len(strings))
`

I was getting an error in the parser when running this code:
```
sent = 'I tried to be good ."
sent = nlp.tokenizer.tokens_from_list(sent.split())
nlp.tagger(sent)
nlp.parser(sent)
```

I was able to make it work by using your [recipe](https://alpha.spacy.io/docs/usage/customizing-tokenizer#custom-tokenizer-example) for whitespace tokenization instead of using tokens_from_list.  This recipe includes spaces.  Surprisingly, if not set it is set to None which may no longer be valid in V2?

## Info about spaCy

* **spaCy version:** 2.0.0a13
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **Python version:** 3.6.0
* **Models:** en_core_web_sm

Error:
<details>
    nlp.tagger(sent)
  File "spacy/pipeline.pyx", line 301, in spacy.pipeline.NeuralTagger.__call__ (spacy/pipeline.cpp:14086)

  File "spacy/pipeline.pyx", line 314, in spacy.pipeline.NeuralTagger.predict (spacy/pipeline.cpp:14745)

  File "thinc/neural/_classes/model.py", line 161, in __call__
    return self.predict(x)

  File "thinc/neural/_classes/model.py", line 125, in predict
    y, _ = self.begin_update(X)

  File "thinc/neural/_classes/feed_forward.py", line 36, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)

  File "spacy/_ml.py", line 380, in fine_tune_fwd
    (model.mix[0] * flat_tokvecs + model.mix[1] * flat_vecs), lengths)

ValueError: operands could not be broadcast together with shapes (0,) (14,128) 
</details>

**Comment by honnibal** [comment]
`tokens_from_list` is deprecated, but I think the behaviour of `Doc.__init__` is a bug here, thanks!

**Comment by honnibal** [comment]
Should be fixed in v2.
