### ISSUE TITLE
[Proposal] Add a proxy for Doc.user_data on the Span

### ISSUE THREAD

**Issue by notnami** [explosion/spaCy#1317]
In my workflow, I frequently pass `Docs` and `Spans` to functions interchangeably, because in many ways they are interchangeable if you treat them just as collections of related `Tokens`. But there is one place where my workflow runs into a problem of `Docs` and `Spans` *not* being interchangeable: the `Doc` class has an attribute for `user_data`, while the `Span` does not. This makes it necessary for me to use wrapping functions with `isinstance` or `try ... except` blocks to actually get the `user_data` regardless of whether I have a `Doc` or a `Span`, which feels bulky and inelegant.

Would it be possible to add the `user_data` attribute on the `Span`, which would simply point to the respective attribute on the `Doc`?

**Comment by honnibal** [comment]
In general we do want to harmonise the `Doc`, `Span` and `Token` interfaces. So, maybe. For a more immediate solution, you could write use `thing.doc.user_data`. The `Doc` object has a property `.doc`, which returns `self`, for exactly this harmonisation reason. This means that writing `span.doc.user_data` will get the same object as `doc.doc.user_data`.

**Comment by notnami** [comment]
Great, thanks. I must've missed "doc" being an attribute on the doc itself.
