### ISSUE TITLE
Spacy Incremental Learning for NER 

### ISSUE THREAD

**Issue by Parvez-Khan-1** [explosion/spaCy#1318]
## Your Environment

* Operating System: Ubuntu 16.04
* Python Version Used: 3.5.2
* spaCy Version Used: 1.9.0
* Environment Information: Using spacy in pycharm IDE for training customized NER model

I am facing issue with training customized NER model.I want to train NER in incremental way means I can append new data to existing model and i am done with this using spacy but the issue is , lets understand using example :  
I trained a xyz model by extending to 'en' model of spacy.after that i again added new data and trained the model again.when i am using this model it just detecting things related to recently appended data only , its now detecting previously added tags.

I followed these guidelines : https://spacy.io/docs/usage/training-ner

Please help....

Thanks

**Comment by honnibal** [comment]
I wrote this recently to try to help with this type of problem: https://explosion.ai/blog/pseudo-rehearsal-catastrophic-forgetting

Hope it helps!

**Comment by Parvez-Khan-1** [comment]
Hi Matthew ,
I am surprised i got such quick reply thanks and keep it up.

Your reply basically saying : Whenever we are adding new entities to existing model so at that we have to add some previous entities also with new ones.so that the weights of the CNN nodes will be get managed is that correct?

**Comment by honnibal** [comment]
That's essentially correct yes. Pre-label some text, and mix it with the new text in your updates. Hope it helps!

**Comment by tantrantp7** [comment]
Hi Matthew,

But I wonder how can we evaluate the new model if we just mix some pre-label texts, will the model be good as before ?
