### ISSUE TITLE
Question - adding the letters of the alphabet to the model

### ISSUE THREAD

**Issue by openfrdb** [explosion/spaCy#1319]
I am comparing nlp(u'a').similarity(nlp(u'a')) and am getting 0.0 when it should be 1.0.

My thought is that the letters of the english alphabet need to be added to the English model. 

Please let me know how best to do this or get this done.  Thanks for your hard work!

Best,
Dave

## Your Environment
* Operating System: Ubuntu 16
* Python Version Used: 2.7
* spaCy Version Used: 2.0 latest nightly from last night 
* Environment Information:

**Comment by honnibal** [comment]
Hmm. Is the model installed? I can't see why that result would be coming up with spaCy 2.

**Comment by openfrdb** [comment]
I think it is.  Apple and apple worked, and apple and bananna worked as expected. Im not able to test right now but had it going last night late. Will test again later. Thanks for the response!

**Comment by openfrdb** [comment]
Figured it out!  It has to do with the input methodology of the parser.  See below:

>>> a = nlp(u'a')
>>> b = nlp(u'b')
>>> a.similarity(a)
0.0
>>> a.similarity(b)
0.0
>>> a = nlp(unicode('a'))
>>> b = nlp(unicode('b'))
>>> a.similarity(a)
0.0
>>> a.similarity(b)
0.0
>>> a,b = nlp(u'a b')
>>> a.similarity(a)
1.0000001
>>> a.similarity(b)
0.25780252

Not sure where the bug is, maybe it's PEBKAC and I am doing it wrong! :)  Let me know if you need anything.

Best,
Dave

**Comment by openfrdb** [comment]
also:

>>> a,b = nlp(u'david david')
>>> a.similarity(a)
1.0
>>> a.similarity(b)
0.39735278
>>> a
david
>>> b
david
>>> b.similarity(a)
0.39735278
>>> b.similarity(b)
1.0000001
>>> 

Just seems weird to me.  seems to be taking into account context.  "david" followed by "david", rather than:  "david", "david" as two individual entities, contextless.  

I could be getting the intention of the code wrong but my understanding is simplistic in that the word parser should create a vector for each word and the vector relates to the position/context in the training data, not that the input form has something to do with the vector that gets created. 

That's cool though if that was the intent!  Could be very useful.

Let me know what you think!

Best,
Dave

**Comment by honnibal** [comment]
When using a model without vectors, the `.similarity()` method backs-off to the token representation used by the tagger, parser and entity recogniser. I agree this is a bit confusing. Details here: https://spacy.io/usage/vectors-similarity
