### ISSUE TITLE
Spacy high memory consumption issue

### ISSUE THREAD

**Issue by nikhilcms** [explosion/spaCy#13190]
Hello,
I am running spacy model with english medium weights inside kubernetes pod.

As I am observing after loading spacy model, it's taking around 500mb space and while after every prediction it keeps increasing.

I am wondering even after deleting spacy object then also it's not releasing memory.

I have allotted around 1GB memory resources to my pod, but after few hours it consume complete memory and stuck pod.

Could you please provide solutions how to release memory and ensure memory should not increase with number of predictions

**Comment by adrianeboyd** [comment]
Here's a thread that covers the memory usage related to the vocab: https://github.com/explosion/spaCy/discussions/10015

If you're only using a `md` model which doesn't use pytorch, you might be able to reduce the memory usage on load by removing `torch` from your venv. The `torch` module is automatically loaded if it's available by `thinc`, and if RAM is very limited skipping `torch` could help?
