### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by chenk17** [explosion/spaCy#1320]
Hey,

Im have problems using spacy with pyinstaller.

`Traceback (most recent call last):
  File "test.py", line 12, in <module>
  File "site-packages\spacy\__init__.py", line 26, in load
TypeError: unsupported operand type(s) for /: 'NoneType' and 'str'
[5432] Failed to execute script test`

I created a simlink and it works all fine the script. But it seems that it is unable to find the path of the model. Since it returns Null in the util.get_path function.

I am also wondering whta the correct folder structure for the data folder should be.

My look like:

```
spacy:
------- data
          - __init__.py
          -meta.json
          -en_core_web_sm
------------------------
                                    -deps
                                    -en_core_web_sm
                                    -ner
                                    -pos
                                    -vocab
                                    -__init__.py
                                    -meta.json
```

Using python 2.7.13
in a virtual environmet

**Comment by chenk17** [comment]
So it seems I found the solution. Since I used pyinstaller. The exe looked in the bundled package for spacy. One need the proper folder structure of spacy inside the pyinstaller bundle...

**Comment by ines** [comment]
Thanks for updating with your solution! If `util.get_data_path()` returns `None` in your configuration, you could also use [`util.set_data_path()`](https://github.com/explosion/spaCy/blob/master/spacy/util.py#L38) to tell spaCy explicitly where to look for the data.
