### ISSUE TITLE
Verb characterized as noun in English text

### ISSUE THREAD

**Issue by dglynos** [explosion/spaCy#13232]
Hello, I've noticed that there are cases where spacy recognizes the root verb correctly in a sentence, but characterizes the verb's token as a noun. Here is an example where the root verb happens to also be a valid noun (of type NNS) in the English language. I've tested and this works in the same way on the _sm, _md and _lg models.

## How to reproduce the behaviour
```
$ cat a.py 
import spacy
nlp = spacy.load('en_core_web_sm')
doc = nlp("The API call places in the response body today's date.")
verb = list(doc.sents)[0].root
print(verb, verb.tag_)
$ python a.py
places NNS
```

## Environment
```
Python version used: 3.9.2
spacy version: 3.7.2
pip installed packages:
Package            Version
------------------ ----------
annotated-types    0.6.0
blis               0.7.11
catalogue          2.0.10
certifi            2023.11.17
charset-normalizer 3.3.2
click              8.1.7
cloudpathlib       0.16.0
confection         0.1.4
cymem              2.0.8
en-core-web-sm     3.7.1
idna               3.6
Jinja2             3.1.3
langcodes          3.3.0
MarkupSafe         2.1.3
murmurhash         1.0.10
numpy              1.26.3
packaging          23.2
pip                20.3.4
pkg-resources      0.0.0
preshed            3.0.9
pydantic           2.5.3
pydantic-core      2.14.6
requests           2.31.0
setuptools         44.1.1
smart-open         6.4.0
spacy              3.7.2
spacy-legacy       3.0.12
spacy-loggers      1.0.5
srsly              2.4.8
thinc              8.2.2
tqdm               4.66.1
typer              0.9.0
typing-extensions  4.9.0
urllib3            2.1.0
wasabi             1.1.2
weasel             0.3.4
```

**Comment by svlandeg** [comment]
Hi!

I'm not a native English speaker, but to me this example sentence sounds a bit odd, and I would personally rephrase it as "The API call places today's date in the response body.". In this case, the verb `"places"` is correctly classified as `VBZ`.

Either way - some mistakes are always possible. In the future, feel free to report these directly in the main thread: https://github.com/explosion/spaCy/issues/3052

Closing this thread to merge it with #3052.
