### ISSUE TITLE
Incorrect lemmatization

### ISSUE THREAD

**Issue by msal4** [explosion/spaCy#13231]
I was running the sentence `"Folgst du der Weser weiter, fährst du durch das Oldenburger Land, wo du eindrucksvolle Naturschutzgebiete, Wälder und Moore erlebst, bis du nach Nordenham gelangst."` through spacy and noticed that `"fährst"` has the  incorrect lemmatization of `"fähren"` instead of `"fahren"`
## How to reproduce the behaviour

I tried a simpler sentences and got the same result:
`"Fährst du Auto?"` this time I get `"Fährst"` as the lemma
`"isst du Auto?"` -> `"issen"` instead of `"essen"`
and other verbs
I used `de_core_news_lg`
## Your Environment

- **spaCy version:** 3.7.2
- **Platform:** macOS-14.2.1-arm64-arm-64bit
- **Python version:** 3.11.7
- **Pipelines:** de_core_news_lg (3.7.0)

**Comment by svlandeg** [comment]
Hi! Thanks for the report - I'll go ahead and merge this with the master thread https://github.com/explosion/spaCy/issues/3052.
