### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by psmoros** [explosion/spaCy#13234]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@mvlttt) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by svlandeg** [comment]
Hi, thanks for the suggestion! We'll consider making a separate `SECURITY.md` file. In the meantime, you can contact us through our usual [contact](mailto:contact@explosion.ai) email address.
