### ISSUE TITLE
'POS tagging' output is not correct

### ISSUE THREAD

**Issue by adityakadrekar16** [explosion/spaCy#13241]
## How to reproduce the behaviour

Hi, I tried the 4 english pipelines (en_core_web - md, sm, lg, trf) for POS tagging. I know that spacy is case sensitive but how are words like 'Water', 'Wheat', 'Cereal', 'Dry', 'Information', 'Research', etc tagged as Proper Noun (NNP, PROPN)?
These words are title case.  Even lowercase words like oil, dry, nutritional, law, express are tagged as NNP.

I thought maybe 'md' model is not large enough to recognize it but even large models like 'lg' and 'trf' are giving poor results. Am I doing something wrong? Can you please help me?

import spacy
nlp_trf = spacy.load("en_core_web_trf")
doc = nlp_trf(text)
for token in doc:
    print(token.text, token.lemma_, token.tag_, token.pos_)

Thanks,
Aditya

## Your Environment

* Operating System: Mac M1 Pro Venture 13.6
* Python Version Used: 3.10.13
* spaCy Version Used: 3.6.1
* Environment Information:

**Comment by adityakadrekar16** [comment]
Hi @svlandeg, can you help me out here?

**Comment by svlandeg** [comment]
Hi! Please avoid tagging individual maintainers. 

Let me transfer this to the discussion forum and follow up there.
