### ISSUE TITLE
tokenization of "haven't" does *not* split contraction

### ISSUE THREAD

**Issue by michaelcapizzi** [explosion/spaCy#1324]
It's surprising to me that `haven't` is `tokenized` as only one word:

```
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> nlp = spacy.load("en_core_web_sm")
>>> doc = nlp("i haven't slept in days. i can't figure out why.")
>>> [t.orth_ for t in doc]
['i', "haven't", 'slept', 'in', 'days', '.', 'i', 'ca', "n't", 'figure', 'out', 'why', '.']
```

As far as I can tell, this is the *only* case where the contraction isn't tokenized.  

Any ideas why?

## My `spaCy`
* **Installed models:** en_core_web_sm, __cache__, __pycache__, en_glove_cc_300_1m_vectors-1.0.0, en-1.1.0, en
* **Platform:** Linux-4.4.0-93-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.5.2
* **spaCy version:** 1.7.0

**Comment by ines** [comment]
Thanks! This was a bug in the tokenizer exceptions and has already been fixed on `master` and `develop` – see #1281. The update will be included in the next release.
