### ISSUE TITLE
Spacy NER custom trained model doesn't recognize any entities

### ISSUE THREAD

**Issue by socialglass** [explosion/spaCy#1327]
Using spacy 1.9 and en_core_web_md 1.2.1, I trained the model exactly as documented here - https://spacy.io/docs/usage/training-ner to recognize horses. Saved the model to a directory and ran

`python -m spacy link <path/to/model> en_my_model`

Now I do this

```
import spacy
nlp_original = spacy.load("en")
nlp_mine = spacy.load("en_my_model")
doc1 = nlp_original(u"John Smith plays polo.")
doc2 = nlp_mine(u"John Smith plays polo.")
[doc1.ents, doc2.ents]
```

doc1.ents gives me back (John Smith,) but doc2.ents is empty. What did I miss?

Also loading my model with spacy.load() takes a very long time ~15 mins, compared to default en model taking ~10 secs. I didn't train beyond what the spacy example says.

Due to certain technical restrictions on my end, I cannot do
`python -m spacy package ....`
for my custom model. So I manually created the package and the directory looks like this -

```
en_mymodel
|-- MANIFEST.in
|-- meta.json
|-- en_mymodel
     |-- __init__.py
     |-- meta.json
     |-- en_mymodel-1.0.0
          |-- meta.json
          |-- deps
          |-- ner
          |-- pos
          |-- vocab
```

and I did the symlink like this
`python -m spacy en_mymodel/en_mymodel/en_mymodel-1.0.0 en_my_model`

Why doesn't NER work?

**Comment by ines** [comment]
Sorry for the late reply – I just left a comment with more details on #1337, which seems to be a very similar issue. So merging those two issues!
