### ISSUE TITLE
Missing return in Doc().from_disk()

### ISSUE THREAD

**Issue by benhachey** [explosion/spaCy#1330]
Maybe by design, but it breaks the examples at https://alpha.spacy.io/docs/usage/saving-loading

https://github.com/explosion/spaCy/blob/c013e5996f3aec8fe6813f1af4386637c29114ec/spacy/tokens/doc.pyx#L663

**Comment by ines** [comment]
Thanks, well spotted! This is definitely a typo. Fixing!
