### ISSUE TITLE
assertion error

### ISSUE THREAD

**Issue by akshay-1993** [explosion/spaCy#1331]
#assertion error in spacy

import spacy
nlp = spacy.load('en')
#Load resources and process text
en_nlp = spacy.load('en')
de_nlp = spacy.load('de')
en_doc = en_nlp(u'Hello, world. Here are two sentences.')
de_doc = de_nlp(u'ich bin ein Berliner.')
#Multi-threaded generator
texts = [u'One document.', u'...', u'Lots of documents']
# .pipe streams input, and produces streaming output
iter_texts = (texts[i % 3] for i in xrange(100000000))
for i, doc in enumerate(nlp.pipe(iter_texts, batch_size=50, n_threads=4)):
    assert doc.is_parsed
    if i == 100:
        break
#Get tokens and sentences    
token = doc[0]
sentence = next(doc.sents)
assert token is sentence[0]
assert sentence.text == 'Hello, world.'

Traceback (most recent call last):

  File "<ipython-input-29-5a6156231135>", line 1, in <module>
    runfile('C:/Users/AkshayC/spacy.py', wdir='C:/Users/AkshayC')

  File "C:\Program Files\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Program Files\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/AkshayC/spacy.py", line 37, in <module>
    assert sentence.text == 'Hello, world.'

AssertionError

## Your Environment

* Operating System: 
* Python Version Used: 
* spaCy Version Used: 
* Environment Information:

**Comment by honnibal** [comment]
It's usually not a good idea to name your python script the same as a module --- so if you're using "pandas", don't name it "pandas.py". If you rename your file from `spacy.py` to something else, do you get the same error?

**Comment by akshay-1993** [comment]
Yes

**Comment by akshay-1993** [comment]
I'm practicing using d code on the official website, but not able to run it

**Comment by akshay-1993** [comment]
thanks for the response the error is solved
