### ISSUE TITLE
Remove a pre-defined entity. 

### ISSUE THREAD

**Issue by Rahul6818** [explosion/spaCy#1332]
If I don't want to extract a particular entity type. How should I do that. 
For example I don't want to extract DATE. 

## Your Environment

* Operating System:  Ubuntu 14
* Python Version Used: 2.7
* spaCy Version Used: 
* Environment Information:

**Comment by ines** [comment]
What exactly are you trying to do? In most cases, it should be enough to simply filter out the entity types, for example:

```python
doc = nlp(SOME_LONG_TEXT_HERE)
ents = [ent for ent in list(doc.ents) if ent.label_ != 'DATE']
```

Of course, there's *technically* the possibility to completely remove an entity label from the model, or retrain it without the label – but I can't think of many use cases where this would actually be an advantage over simply filtering the entities.

**Comment by Rahul6818** [comment]
Thank you @ines 
I want to remove this because when I retrain the spacy model with Domain Specific entity(other than spacy defined entities) it doesn't give the correct results for spacy defined entities. 
And I can extract some of those entities with regex(like date, time).

**Comment by jacinto123** [comment]
I am also having this problem.

**Comment by m0rth1um** [comment]
Is there also a way to completely remove one or more entities from a language model? I only want to find the entities that I trained the model on.
Right now I receive false positives where something get detected as an ORG where in reality it's something else.

**Comment by Parvez-Khan-1** [comment]
I am having the same issue and i agreed with ines solution , but what if i want to delete it from root.checking in the if condition is just a temporary solution , i am looking for the way to delete it from root.

**Comment by MarieCo** [comment]
I am also having that issue (wanting to remove completely some entities from a model), has anyone found a solution yet?

**Comment by honnibal** [comment]
Hopefully retraining the entity recognizer produces more stable results in v2, making this less necessary. But I've also made a branch to explore solutions to this: https://github.com/explosion/spaCy/tree/feature/prohibit-entities

The solution I've pushed at the moment is a bit messy. It would let you replace the `is_valid` function bound to an action on the entity recognizer or parser with a new function that always return `False`. Example:

```python

>>> import spacy
>>> nlp = spacy.load('en_core_web_sm')
>>> nlp(u'1998').ents[0].label_
'DATE'
>>> nlp.get_pipe('ner').moves.prohibit_action(u'U-DATE')
>>> nlp(u'1998').ents[0].label_
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: tuple index out of range
```

I think it's much nicer to write directly to the `is_valid` function pointer, held by the `Transition` structs. The example of replacing this function can be found here: https://github.com/explosion/spaCy/commit/179bc93f154fd002cea44c47d01e38502bc1f0f2

I know folks aren't excited about having to interact with spaCy via Cython...But sometimes it's really the cleanest solution.

**Comment by Huzefa-Lw** [comment]
I hope this can help.
I used this function by using 'apply' function in pandas.

`stop_words= set(stopwords.words('english'))

def createData(x):
    x_spc= nlp(x)
    x_return= ''
    if len(x_spc.ents)== 0:
        x_return= re.sub('[^\sa-z]', '', x.lower())
        x_return= ' '.join([x for x in x_return.split(' ') if (x not in stop_words) and (len(x)> 2)])
        return x.lower()
    idx= 0
    idx_last_ent= 0
    len_last_ent= 0
    
    for i, ent in enumerate(x_spc.ents):
        idx= x.find(ent.text)
        if i== 0:
            x_return= x[0: idx]
        else:
            x_return= x_return+ x[idx_last_ent+ len_last_ent: idx]
            
        if ent.label_ not in ['PERSON', 'ORG', 'DATE', 'GPE', 'CARDINAL', 'ORDINAL']:
            x_return= x_return+ ent.text
            
        if i== len(x_spc.ents)-1:
                x_return= x_return+ x[idx+len(ent.text): ]
        
        len_last_ent= len(ent.text)
        idx_last_ent= idx
    
    x_return= x_return.lower()
    
    x_return= re.sub('[^\sa-z]', '', x_return)

    x_return= ' '.join([x for x in x_return.split(' ') if (x not in stop_words) and (len(x)> 2)])
    
#     displacy.render(x_spc, style= 'ent', jupyter= True)
    
    return x_return`

**Comment by Huzefa-Lw** [comment]
`stop_words= set(stopwords.words('english'))

def createData(x):
    x_spc= nlp(x)
    x_return= ''
    if len(x_spc.ents)== 0:
        x_return= re.sub('[^\sa-z]', '', x.lower())
        x_return= ' '.join([x for x in x_return.split(' ') if (x not in stop_words) and (len(x)> 2)])
        return x.lower()
    idx= 0
    idx_last_ent= 0
    len_last_ent= 0
    
    for i, ent in enumerate(x_spc.ents):
        idx= x.find(ent.text)
        if i== 0:
            x_return= x[0: idx]
        else:
            x_return= x_return+ x[idx_last_ent+ len_last_ent: idx]
            
        if ent.label_ not in ['PERSON', 'ORG', 'DATE', 'GPE', 'CARDINAL', 'ORDINAL']:
            x_return= x_return+ ent.text
            
        if i== len(x_spc.ents)-1:
                x_return= x_return+ x[idx+len(ent.text): ]
        
        len_last_ent= len(ent.text)
        idx_last_ent= idx
    
    x_return= x_return.lower()
    
    x_return= re.sub('[^\sa-z]', '', x_return)

    x_return= ' '.join([x for x in x_return.split(' ') if (x not in stop_words) and (len(x)> 2)])

    displacy.render(x_spc, style= 'ent', jupyter= True)

    return x_return`

**Comment by Huzefa-Lw** [comment]
`
stop_words= set(stopwords.words('english'))

def createData(x):
    x_spc= nlp(x)
    x_return= ''
    if len(x_spc.ents)== 0:
        x_return= re.sub('[^\sa-z]', '', x.lower())
        x_return= ' '.join([x for x in x_return.split(' ') if (x not in stop_words) and (len(x)> 2)])
        return x.lower()
    idx= 0
    idx_last_ent= 0
    len_last_ent= 0
    
    for i, ent in enumerate(x_spc.ents):
        idx= x.find(ent.text)
        if i== 0:
            x_return= x[0: idx]
        else:
            x_return= x_return+ x[idx_last_ent+ len_last_ent: idx]
            
        if ent.label_ not in ['PERSON', 'ORG', 'DATE', 'GPE', 'CARDINAL', 'ORDINAL']:
            x_return= x_return+ ent.text
            
        if i== len(x_spc.ents)-1:
                x_return= x_return+ x[idx+len(ent.text): ]
        
        len_last_ent= len(ent.text)
        idx_last_ent= idx
    
    x_return= x_return.lower()
    
    x_return= re.sub('[^\sa-z]', '', x_return)

    x_return= ' '.join([x for x in x_return.split(' ') if (x not in stop_words) and (len(x)> 2)])
    
#     displacy.render(x_spc, style= 'ent', jupyter= True)
    
    return x_return
`

**Comment by Huzefa-Lw** [comment]
I hope this can help. I used this function along with 'apply' function in pandas.

'''
stop_words= set(stopwords.words('english'))

def createData(x):
    x_spc= nlp(x)
    x_return= ''
    if len(x_spc.ents)== 0:
        x_return= re.sub('[^\sa-z]', '', x.lower())
        x_return= ' '.join([x for x in x_return.split(' ') if (x not in stop_words) and (len(x)> 2)])
        return x.lower()
    idx= 0
    idx_last_ent= 0
    len_last_ent= 0
    
    for i, ent in enumerate(x_spc.ents):
        idx= x.find(ent.text)
        if i== 0:
            x_return= x[0: idx]
        else:
            x_return= x_return+ x[idx_last_ent+ len_last_ent: idx]
            
        if ent.label_ not in ['PERSON', 'ORG', 'DATE', 'GPE', 'CARDINAL', 'ORDINAL']:
            x_return= x_return+ ent.text
            
        if i== len(x_spc.ents)-1:
                x_return= x_return+ x[idx+len(ent.text): ]
        
        len_last_ent= len(ent.text)
        idx_last_ent= idx
    
    x_return= x_return.lower()
    
    x_return= re.sub('[^\sa-z]', '', x_return)

    x_return= ' '.join([x for x in x_return.split(' ') if (x not in stop_words) and (len(x)> 2)])
    
#     displacy.render(x_spc, style= 'ent', jupyter= True)
    
    return x_return
'''

**Comment by Huzefa-Lw** [comment]
I hope this code can help. I used this function with 'apply' function in pandas.

```
def remove_unwanted_tags(x):
    x_spc= nlp(x)
    x_return= ''
    if len(x_spc.ents)== 0:
        x_return= re.sub('[^\sa-z]', '', x.lower())
        x_return= ' '.join([x for x in x_return.split(' ') if (x not in stop_words) and (len(x)> 2)])
        return x.lower()
    idx= 0
    idx_last_ent= 0
    len_last_ent= 0
    
    for i, ent in enumerate(x_spc.ents):
        idx= x.find(ent.text)
        if i== 0:
            x_return= x[0: idx]
        else:
            x_return= x_return+ x[idx_last_ent+ len_last_ent: idx]
            
        if ent.label_ not in ['PERSON', 'ORG', 'DATE', 'GPE', 'CARDINAL', 'ORDINAL']:
            x_return= x_return+ ent.text
            
        if i== len(x_spc.ents)-1:
                x_return= x_return+ x[idx+len(ent.text): ]
        
        len_last_ent= len(ent.text)
        idx_last_ent= idx
    
    x_return= x_return.lower()
    
    x_return= re.sub('[^\sa-z]', '', x_return)

    x_return= ' '.join([x for x in x_return.split(' ') if (x not in stop_words) and (len(x)> 2)])
    
    displacy.render(x_spc, style= 'ent', jupyter= True)
    
    return x_return
```
