### ISSUE TITLE
is there any option of composite entity

### ISSUE THREAD

**Issue by ankitarath2011** [explosion/spaCy#1334]
## Info about spaCy

* **Python version:** 2.7.13
* **Platform:** Windows-10-10.0.14393
* **spaCy version:** 1.9.0
* **Installed models:** en

1. Is there any thing composite entity in spacy.  If yes how can I do that.
2. How can I get from city and to city separately instead of single location

Thanks.

**Comment by honnibal** [comment]
What do you mean by a composite entity?

**Comment by ankitarath2011** [comment]
composite entity means nested entity type, an entity having another entity inside it. 
e.g.  "from [location]" will be one entity that contains another entity location in it

**Comment by fucking-signup** [comment]
Sounds like a good feature. I've just encountered a somewhat similar case when nested entities could gladly help.

**Comment by thedataist** [comment]
I'm just looking at how to implement this and considering using spaCy. I'll likely train the NER on all the base entities and then use custom code to identify the hierarchies and then merge the span, e.g.
starting with base entities:
I'm at Starbucks **ORG** 789 **CARDINAL** Mission **ST_NAME** St **ST_TYPE** San Fran **CITY**
:arrow_down:
Starbucks **ORG** 789 **CARDINAL** [Mission St] **ST_NAMED* San Fran **CITY**
:arrow_down:
[Starbucks 789 Mission St] **ST_ADDRESS**  San Fran **CITY**
:arrow_down:
[Starbucks 789 Mission St San Fran] **GEO_ADDRESS**

Then just use the merged span for further processing (e.g. dependencies). It would be helpful if there was some sort of templating annotation system to do this within spaCy.

Anybody else working on something like this?

**Comment by teddius** [comment]
Has this been implemented somewhere already? Any solution yet?

**Comment by AndriyMulyar** [comment]
I appears nested (or overlapping) entities were disallowed in spacy via #2880 .

I have several qualms with this:
1) This limits named entity recognition to be a multi-class classification problem as opposed to the more general multi-label classification problem - dependency information between entities (labels) is lost if entities of interest naturally occur inside one another or overlap.
2) This commit has limited the capabilities of using Matcher with entities. For instance, I have an entity **mass_unit** that I would like to use as part of a pattern for matching a number followed by a unit like so:
```python
[{'LIKE_NUM': True}, {'ENT_TYPE': 'mass_unit'}],
```
If I wanted to label all Spans that match this pattern as a new entity - I can no longer do this as the new entity will overlap with the existing entity **mass_unit** thus raising an error.

3) Nested entities arise in many NER applications - implicitly disallowing them limits the capabilities of the package. I have had to write a fair amount of code to 


From my readings of issue discussions, it appears this functionality was implemented in-part to solve rendering issues with displaCy alongside address.
Related issues:  #2550 

@honnibal What are your thoughts?

**Comment by rbhambriiit** [comment]
I am not very sure if overlap is really getting blocked. 

Using v2.0.18 I am able to get tags without errors for overlapping scenarios:
    # something here should fail. does not fail at all!
    overlap1 = (u"Uber blew through $1 million a week", {'entities':[(0, 4, 'ORG'), (0, 4, 'overlap1')]})
    train_data.append(overlap1)
    
    overlap2 = (u"Uber blew through $1 million a week", {'entities':[(0, 4, 'ORG'), (0, 9, 'overlap2')]})
    train_data.append(overlap2)
    
    overlap3 = (u"Uber blew through $1 million a week", {'entities':[(0, 9, 'overlap3'), (0, 4, 'ORG')]})
    train_data.append(overlap3)


Infact I want these examples to fail and throw exceptions..


 Info about spaCy

    Python version     2.7.15         
    Platform           Linux-4.14.72-68.55.amzn1.x86_64-x86_64-with-glibc2.2.5
    spaCy version      2.0.18         
    Location           /usr/local/lib64/python2.7/site-packages/spacy
    Models             en

**Comment by datascienceteam01** [comment]
What is the status here? Was there any response pertaining nested entities (please no hacks!). It's a very important factor to train models into understanding context.

**Comment by honnibal** [comment]
@AndriyMulyar I'm confused as to how this ever worked. The entities have always been stored on the tokens using two attributes: `ent_iob` and `ent_type`. Each token can only receive one `ent_iob` value, indicating whether an entity starts, ends, or is internal to an entity, and indicating the type. So the implementation has never had a way of storing nested named entities.

What you should do if you need nested named entities is add a custom attribute, and store them there. In v2.1 you'll also be able to use the `Matcher` over the values in extension attributes as well.

I'm really not sure how your code is working in v2.0.12.

**Comment by AndriyMulyar** [comment]
@honnibal The merge I referenced above implemented the throwing of a hard error when attempting to set an entity tag onto a token that already had an entity tag. It appears that what was actually happening was that the entity tag was being overridden (which happened to be the behavior desired) - not that multiple entity tags were being set for a given token.

The referenced improved functionality in v2.1 for `Matcher` seems like will provide a sufficient solution to this use case. This thread can probably be closed.

**Comment by syllog1sm** [comment]
@andriymulyar if you just want to overwrite the entity tag, you can just reconcile the entities as you want them before assigning to doc.ents? If you don't need actual overlap or nesting there should be no problem.
