### ISSUE TITLE
Version incompatibility between Spacy, Cuda, Pytorch and Python

### ISSUE THREAD

**Issue by Project-NSE** [explosion/spaCy#13364]
### Discussed in https://github.com/explosion/spaCy/discussions/13362

<div type='discussions-op-text'>

<sup>Originally posted by **Project-NSE** February 29, 2024</sup>
I want run spacy in GPu. The configuration that I installed for the Spacy is defined below
**Name: spacy
Version: 3.7.4**

The Cuda configuration that have in my Ubuntu 20.04.1 LTS based machine is

**nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243**

I have a restriction to upgrade the Cuda. The PyTorch version that I have installed on the machine is **"2.2.1+cu121"** which have no support for the  Cuda version I have.

I tried to downgrade the Pytorch and found that I need to downgrade the Python version as well.

My current python version is Python **3.12.2.** If I go for a compatible Python version for pytorch that should be >=3.6,<3.7.0 for pytorch 1.4.0.

If I downgrade both Pytorch and Python that is not compatible with Spacy version.

I need to do a transformer-based NER task in Spacy. Therefore I am not sure what is the minimum requirement of spacy.

How can I handle this version incompatibility?
</div>

**Comment by Project-NSE** [comment]
Please help me to resolve this issue. I can not go further in my project without resolving this issue.

**Comment by svlandeg** [comment]
Hi!

Please don't open duplicate issues in the discussion forum and on the issue tracker. As this is an installation question, I'll close this thread and I'll follow up with you on the discussion forum.
