### ISSUE TITLE
Custom NER model doesn't recognize any entities

### ISSUE THREAD

**Issue by gurunathpr** [explosion/spaCy#1337]
Issue:
I have been trying to use a custom NER model for spacy-services with the name 'endec'.When I try to use it directly by loading it in displacy/app.py, I get the following error:
`Traceback (most recent call last): File "app.py", line 4, in <module> get_model('endec') File "/home/prgs/spacy-services/displacy/displacy_service/server.py", line 36, in get_model _models[model_name] = spacy.load(model_name) File "/usr/local/lib/python2.7/dist-packages/spacy/__init__.py", line 28, in load lang_name = util.get_lang_class(name).lang File "/usr/local/lib/python2.7/dist-packages/spacy/util.py", line 27, in get_lang_class raise RuntimeError('Language not supported: %s' % name) RuntimeError: Language not supported: endec`

Is the model being loaded as a language in server.py?
So , I tried to work around it by loading the model directly in the get_model() function in the server.py script as follows:
`def get_model(model_name): if model_name not in _models: import en_endec _models[model_name] = en_endec.load() return _models[model_name]`

But when try to get the entities using my custom NER model named 'en_endec', it just returns an empty list.Is there anything apart from the above steps that I should modify/configure?
Thanks!

Environment info : 
Python version: 2.7.12
Platform:Linux-4.10.0-33-generic-x86_64-with-Ubuntu-16.04-xenial
spaCy version: 1.9.0
Installed models: endecmodel, en-1.1.0, __cache__, en

**Comment by ines** [comment]
Thanks for the report! Just to make sure – if you're loading your model via `spacy.load()` or native `imports`, it all works as expected, and the error only occurs when using the service?

The way the model loading works in spacy-services is probably not ideal, and there's a chance that it contains a bug or an incompatibility with the latest version(s) of spaCy.

In the meantime, if your main goal is to use displaCy ENT, you can also check out [v2.0.0 alpha](), which comes with [built-in](http://alpha.spacy.io/docs/usage/visualizers) visualizers. Using displaCy ENT from within spaCy v2.0 is as simple as:

```python
nlp = spacy.load('some_model_here')
doc = nlp("Some text with entities")
displacy.serve(doc, style='ent')
```

Keep in mind that you'll have to re-train your custom model with the new version in order to load and use it with v2.0 alpha.

**Comment by voxlogic** [comment]
Thanks for following up. We are having this issue even in spacy.load() or while loading natively via imports (as mentioned above, we are using Spacy 1.9). Everything works as expected with the default 'en' model. However, when the custom model is loaded using either method, no entities are returned.

**Comment by gurunathpr** [comment]
@ines When I load the custom NER model directly in Spacy,it still shows up "No model found.Default 'en' tokenizer loaded".It seems to be a problem with loading my Custom NER model.It just doesn't retuen any entities.

- Is there something I am missing in my Custom NER after packaging and sym linking it?
- Is there any way to check if my custom NER model is properly trained?
I did `import spacy
nlp = spacy.load('en_custom_model')
doc = nlp(u'<sentence>')
for ent in doc.ents:
    print(ent.label_, ent.text)`
But it doesn't seem to return any entities.

**Comment by ines** [comment]
Sorry for the late reply – I missed your comment on this!

It's hard to debug this from afar, but here are some ideas:

* Check the model data directory and make sure it contains a directory `ner` – and compare that to the `en_core_web_sm` model and check it it all looks reasonable. If not, there might have been an issue with saving out the trained model.
* See #1318 and [this blog post on the "catastrophic forgetting" problem](https://explosion.ai/blog/pseudo-rehearsal-catastrophic-forgetting). If your training data only contained new entities and you didn't mix in any examples the model previously recognised, this might have caused the model to "forget" what it had previously learned. The solution to this would be to pre-label some text, and mix it with the new text in your updates.
* If you like and have time, try [spaCy v2.0.0 alpha](https://alpha.spacy.io/usage/v2) and compare the results. The new `spacy train` command gives you more control over the hyperparameters, which can lead to better results.

**Comment by prashant334** [comment]
actually I am trying to detect **"city+ police"** as a entity tag **"senthaspolice"** means **'sentence has police location'**. so for that I am training my customized ner with below training sentences...and expecting that it can detect other "city + police " where city name is not mentioned in training data..but similar semantics are applied.

below is my training data 

train_data = [
        (
            "Saibaba and his associates were arrested by Aheri Police in Naxal affected area in 2013 under sections of UAPA.",
            [(44, 56, 'Police')]
        ),
        (
            "The incident is being jointly-investigated by the Kent Police and the Federal Bureau of Investigation as a hate crime.",
            [(50, 61, 'Police')]
        ),
        (
            "\"The account provided by the victim suggests that he was targeted because of his ethnic origin,\" Kent Police chief Ken Thomas told reporters yesterday, adding \"Hateful acts are not acceptable.\"",
            [(97, 107,'Police')]
        ),
        (
            "The Kent Police Department is concerned about any act of violence in our community.",
            [(4, 14, 'Police')]
        ),
        (
            "Delhi Police's Crime Branch, which is probing the clashes at Ramjas College, has recorded the statements of 2 St Stephen's College students who were allegedly beaten up by supporters of ABVP.",
            [(0, 12, 'Police')]
        ),
        (
            "Three of the 18 persons arrested from across Goa police and Maharashtra in connection with the army exam paper leak were picked up from a bar in North Goa's Anjuna village, police said on Sunday. ",
            [(45, 55, 'Police')]
        ),
            (
            "The trio was arrested by officials of the Crime Branch of Thane police, alongwith personnel attached to the Anjuna police station.",
            [(58, 70, 'Police')]
            ),
        (
            "Speaking to reporters late on Sunday, Director General of Police Muktesh Chander said the local police only provided logistical support to the Thane Crime Branch, which conducted the raids.",
            [(97, 107, 'Police')]
        ),
        (
            "The incident occurred last morning in Urga police station area, around 15 kms away from Korba, when Ramesh Patel (25), a cousin of the victim's husband, tried to force himself upon her when nobody was present at home, said the Urga police station SHO MM Minj.",
            [(38, 57, 'Police')]
        ),
        (
            "It was a tragic and senseless act of violence, Olathe police chief Steven Menke told reporters.",
            [(47, 60, 'Police')]
        )

    ]


and below is my test data:


doc = nlp('They were arrested by Ahmedabad Police')
    print("Ents in 'They were arrested by Ahmedabad Police':")
    for ent in doc.ents:
        print(ent.label_, ent.text)

but in output it does not show any result..

where expected result should be ent.label = Police and ent.text=Ahmedabad Police

similarly for any other city + police combination it should give correct answer.

help me for this

**Comment by honnibal** [comment]
Please see here --- the training is much improved in v2, and we've tried to give a lot more guidance about how to make good use of it: https://spacy.io/usage/training

**Comment by Rahul6818** [comment]
In v2 also it is returning nothing. I am training on custom entity - 'ponumber' which is a number. and I am training it on around 70 examples. But when i test it, it always return empty list.
