### ISSUE TITLE
Similarity scores don't discriminate well in v1

### ISSUE THREAD

**Issue by nishkalavallabhi** [explosion/spaCy#1338]
Is .similarity function meant to be used only with words or very small sentences which are similar anyway? Is there an example where I can see low similarity scores? I just had a bizarre experience while trying to test spacy for the first time:

See the following output in : sentence 1     sentence 2 and the similarity score between them (sentence1.similarity(sentence2)) in the next line:
***
All are native English speakers. 	 It is possible that this approach could be used to decode information about what words a person is hearing, reading or possibly even thinking, said Alexander Huth, the main author of the study.
0.707323450853
***
All are native English speakers. 	 One possible use would be a language decoder that could allow people who cant talk, because they have a serious illness, to speak through a computer.
0.753100826756
***
All are native English speakers. 	 To create the atlas, the scientists recorded peoples brain activity while they listened to stories.
0.730391999589
***
All are native English speakers. 	 Then, they matched the transcripts of the stories with the brain activity data to show how groups of related words produced brain responses in 50,000 to 80,000 pea-sized spots all over the cerebral cortex.
0.724746394961
***
All are native English speakers. 	 All light up their own networks.
0.710039109916
***

- None of these sentences are in anyway (surface or semantic) similar to the sentence 1. 

* **spaCy version:** 1.9.0
* **Python version:** 3.5.1
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **Installed models:** en

**Comment by honnibal** [comment]
The similarity in v1.9.0 is just the average of the word vectors. This can often discriminate very similar outputs from dissimilar outputs, but it doesn't do very well at discriminating sort-of-similar from not-very-similar. I suspect you're probably using the `en_core_web_sm` model, too --- that model only has vectors for the 5000 most frequent words, so most of the terms you're testing for won't have vectors.

In spaCy 2, documents are assigned context-sensitive tensors by the CNN, used as input to the parser, entity recogniser and part-of-speech tagger. The vectors don't have very much lexical semantic knowledge, but on some tasks they do. On your samples the results look much better:

```python

# pip install spacy-nightly
# spacy download en_core_web_sm
>>> import spacy
>>> def cosine(v1, v2):
...   return v1.dot(v2) / (((v1**2).sum()**0.5) * ((v2**2).sum()**0.5))
>>> nlp = spacy.load('en_core_web_sm')
>>> doc1 = nlp(u'All are native English speakers.')
>>> # Replace default similarity with cosine of tensor averages.
>>> doc1.user_hooks['similarity'] = lambda d1, d2: cosine(d1.tensor.mean(axis=0), d2.tensor.mean(axis=0))
>>> doc2 = nlp(u'It is possible that this approach could be used to decode information about what words a person is hearing, reading or possibly even thinking, said Alexander Huth, the main author of the study.')
>>> doc1.similarity(doc2)
0.14879898324571239
>>> doc2 = nlp(u'Then, they matched the transcripts of the stories with the brain activity data to show how groups of related words produced brain responses in 50,000 to 80,000 pea-sized spots all over the cerebral cortex.')
>>> doc1.similarity(doc2)
-0.054542541058340673
>>> doc2 = nlp(u'To create the atlas, the scientists recorded peoples brain activity while they listened to stories.')
>>> doc1.similarity(doc2)
0.20494836325515106
>>> doc2 = nlp(u'Then, they matched the transcripts of the stories with the brain activity data to show how groups of related words produced brain responses in 50,000 to 80,000 pea-sized spots all over the cerebral cortex.')
>>> doc1.similarity(doc2)
0.15647311755088164
>>> doc2 = nlp(u'All light up their own networks.')
>>> doc1.similarity(doc2)
0.4313985363326252
>>> doc2 = nlp(u'Everyone spoke English.')
>>> doc1.similarity(doc2)
0.48939216112750217
>>> doc2 = nlp(u'All are American or British.')
>>> doc1.similarity(doc2)
0.50352318659987494
```

**Comment by honnibal** [comment]
See here for more details: http://alpha.spacy.io/docs/usage/word-vectors-similarities
