### ISSUE TITLE
Is there any interest in adding new languages?

### ISSUE THREAD

**Issue by rcalsaverini** [explosion/spaCy#134]
Hi, 
there's a lack of good NLP tools for Portuguese. I am very much interested in porting some of the functionality of spaCy for Portuguese for my own needs (specially the pos-tagger).

So, my questions is: is there interest in providing the same API that the class English implements for a new Portuguese class? Are the maintainers looking for people who would like to contribute with new languages or it isn't the right moment yet?

Thanks for your time.

**Comment by honnibal** [comment]
Hi,

Yes, we're very interested. New languages is one of the two focus features at the moment.

Can you have a look at the notes here: https://github.com/honnibal/spaCy/issues/124 and some of the links, and let me know whether you understand the idea of this morphology table?

It's relatively easy to just train a tagger on some treebank text. But to have it really work, we need to go from the ground up and get the tokenization, morphological analysis and lemmatization right.

**Comment by rcalsaverini** [comment]
Nice.
I'll have to take a good read on the Universal Dependencies. I'm not familiar with it. But count on me for any grunt work that doesn't require a deep knowledge of it in the mean time. If there's anything on your hand that might need contribution, I can help.

**Comment by honnibal** [comment]
Could you have a look here: http://linguateca.dei.uc.pt/Floresta/DocumentacaoFloresta.html and let me know what the licensing options are for the data?

Apart from that, another question is whether Portuguese will have any difficult tokenization rules. For instance, in English we tokenize "can't" into "ca", "n't", and in Italian we want to tokenize "dalla" into "dal", "la". But Italian also seems to have a productive, open-class process that allows arbitrary verbs to fuse with pronouns. This makes enumerating a set for special-case tokenization difficult.

If we can get the tokenization sorted out, we can provide word vectors and simple rule-based sentence boundary detection. We can also provide named entity recognition, trained from Wikipedia.

**Comment by rcalsaverini** [comment]
According to the Linguateca website the Floresta Sinta(c)tica dataset is publicly available. I believe no licensing issues are involved in using the dataset. 

I'm revising some resources on portuguese tokenization rules and will provide a set of rules in short notice.

**Comment by rcalsaverini** [comment]
There might also be a problem regarding epoch. As an example, the contraction of the clitics "me + as" -> "mas" is very old fashioned in Brazilian Portuguese, where virtually all occurrences of  "mas" in modern texts refer to the conjunction "mas" (meaning "but"). But in older (XIX and early XX century) texts it can be the former "me + as".
