### ISSUE TITLE
SpaCy is not building today

### ISSUE THREAD

**Issue by lovellbrian** [explosion/spaCy#13449]
## How to reproduce the behaviour

I am building the devcontainer for https://github.com/lovellbrian/cpu  and spaCy is not building.  may be due to cpdef instead of cdef usage.

## Your Environment

* Operating System: Ubuntu 22.04
* Python Version Used: 3.10
* spaCy Version Used: spacy-3.0.6.tar.gz
* Environment Information:
* Downloading spacy-3.0.6.tar.gz (7.1 MB)
1055.3      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 6.2 MB/s eta 0:00:00
1056.4   Installing build dependencies: started
1074.9   Installing build dependencies: finished with status 'done'
1074.9   Getting requirements to build wheel: started
1079.7   Getting requirements to build wheel: finished with status 'error'
1079.8   error: subprocess-exited-with-error
1079.8   
1079.8   × Getting requirements to build wheel did not run successfully.
1079.8   │ exit code: 1
1079.8   ╰─> [164 lines of output]
1079.8       
1079.8       Error compiling Cython file:
1079.8       ------------------------------------------------------------
1079.8       ...
1079.8           int length
1079.8       
1079.8       
1079.8       cdef class Vocab:
1079.8           cdef Pool mem
1079.8           cpdef readonly StringStore strings
1079.8                 ^
1079.8       ------------------------------------------------------------
1079.8       
1079.8       spacy/vocab.pxd:28:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.
1079.8       
1079.8       Error compiling Cython file:
1079.8       ------------------------------------------------------------

**Comment by mirekphd** [comment]
I confirm this. See in my Jenkins build log below how far into the releases history did `pip` have to go searching for a `spacy` version compatible with the other packages in our containers: to start building it went down from a "recent" version 3.7.2 (from October 2023) all the way down to 3.0.6 (From April 2021). And this was your version too @lovellbrian, which I don't believe to be a coincidence. I suspect the dreaded `<` versions pins (which are second gate of "DLL hell", the first one [being the pinning itself](https://stackoverflow.com/a/43421973/9962007)) in `spacy`'s [`requirements.txt`](https://github.com/explosion/spaCy/blob/master/requirements.txt) prevent builds of the more recent versions and force `pip` to attempt a build of an obsolete version from 2021.

**Comment by wzjin2017** [comment]
Encountered the same issue. Downgrading Cython does not seem to work as [this link](https://github.com/explosion/spaCy/discussions/12941) suggested. Any updates?

**Comment by C-monC** [comment]
Same issue here

**Comment by wfowlks** [comment]
I am encountering this issue as well trying to build Autogluon. It is downgrading to spaCy 3.0.6 and then failing to compile. I have also tried changing the version of Cython to unsuccessful results.

**Comment by wzjin2017** [comment]
> Encountered the same issue. Downgrading Cython does not seem to work as [this link](https://github.com/explosion/spaCy/discussions/12941) suggested. Any updates?

In my case, a solution that works for now is by specifying `fastapi==0.110` when installing. I am guessing there are some package version conflicts under the hood.

**Comment by honnibal** [comment]
Apologies that this slipped through for a while. We're working on it.

**Comment by wfowlks** [comment]
> > Encountered the same issue. Downgrading Cython does not seem to work as [this link](https://github.com/explosion/spaCy/discussions/12941) suggested. Any updates?
> 
> In my case, a solution that works for now is by specifying `fastapi==0.110` when installing. I am guessing there are some package version conflicts under the hood.

This worked for me as well, thank you!

**Comment by C-monC** [comment]
> > Encountered the same issue. Downgrading Cython does not seem to work as [this link](https://github.com/explosion/spaCy/discussions/12941) suggested. Any updates?
> 
> In my case, a solution that works for now is by specifying `fastapi==0.110` when installing. I am guessing there are some package version conflicts under the hood.

This also worked for me

**Comment by chris-araki** [comment]
> > Encountered the same issue. Downgrading Cython does not seem to work as [this link](https://github.com/explosion/spaCy/discussions/12941) suggested. Any updates?
> 
> In my case, a solution that works for now is by specifying `fastapi==0.110` when installing. I am guessing there are some package version conflicts under the hood.

This also worked for me! Thank you!!

**Comment by joaolovatti** [comment]
> > Encountered the same issue. Downgrading Cython does not seem to work as [this link](https://github.com/explosion/spaCy/discussions/12941) suggested. Any updates?
> 
> In my case, a solution that works for now is by specifying `fastapi==0.110` when installing. I am guessing there are some package version conflicts under the hood.

Tu es un génie!

**Comment by Hoshock** [comment]
> In my case, a solution that works for now is by specifying `fastapi==0.110` when installing. I am guessing there are some package version conflicts under the hood.

Worked!!! Super thanks!!!!!!

**Comment by avanishshah03** [comment]
what command did you use exactly?
pip install fastapi==0.110 spacy==3.0.6                   
This did not work for me.

**Comment by sahirmpatel** [comment]
> what command did you use exactly? pip install fastapi==0.110 spacy==3.0.6 This did not work for me.

run 
spacy
fastapi==0.110

**Comment by svlandeg** [comment]
Hi! Sorry for the inconvenience here. This issue should be fixed with the latest spaCy v3.7.5. I'll go ahead and close this for now, but let us know if you do still run into issues with this.

**Comment by C-monC** [comment]
@svlandeg Can confirm it is working now. 
Thank you!

**Comment by svlandeg** [comment]
Great, thanks for the confirmation!
