### ISSUE TITLE
Different entity recognition result with long and short text

### ISSUE THREAD

**Issue by Zhenshan-Jin** [explosion/spaCy#1344]
Hi,

Thanks for building such a great tool and I'm looking forward to the great features in spaCy 2.0!

I had an observation regarding the result of spaCy ER in a long and short text which seems like contradictory with what document says:  

**Message from document**: [The library should perform equally well with short or long documents.](https://spacy.io/docs/usage/processing-text)  

**My observation**  
The number entities recognized from a long text, like a paper, would be dramatically less than the ones that you get by splitting the same long text into short sentences and passing them to the same NER model one by one. For example:  
[Source text](https://www.researchgate.net/publication/222139279_Gravitational_collapse_and_Neogene_sediment_transfer_across_the_western_margin_of_the_Gulf_of_Mexico_Insights_from_numerical_models)  
For this paper, if I pass all the text inside it as a whole into default `en` spacy model I'll get only 26 entities recognized. However, if I manually separate all the sentences inside the paper and pass them to ER model one by one and accumulate all the entities that I get, finally I get 426 entities recognized from the whole paper. I'm wondering whether I have some misunderstanding of the message from [spaCy document](https://spacy.io/docs/usage/processing-text)

**Followup questions**
If there is a difference between the behavior of long and short text in entity recognizing step. I'm wondering the influence of this long/short text difference in the training step. For example:  
training text: `I love apple. I eat one banana a day.`  
two ways to pass this training data to spaCy model:
1.   
["I love apple.", [[7, 12, "FRUIT"]]  
["I eat one banana a day." [[10, 16, "FRUIT"]]]  
2.  
["I love apple. I eat one banana a day.", [[7, 12, "FRUIT"],[24, 30, "FRUIT"]]]

**Thank you!**
## Your Environment

* Operating System: Ubuntu 16.04
* Python Version Used: 3.6
* spaCy Version Used: 1.9

**Comment by honnibal** [comment]
That's very interesting. I made some bug fixes to the entity recognition in spaCy 2, that affected the interaction with the sentence boundary detection. I wouldn't have thought there would be anything so drastic, however.

Could you attach the extracted text for the article? I'd like to check whether the same is true in spaCy 2, and what the problem might be.

To answer your question: The model is trained on whole documents where possible. Not all of the training examples come with raw text, however -- so sometimes we train on the split sentences.

**Comment by Shawn-Zhenshan-Jin** [comment]
Hi @honnibal ,

So excited to receive your reply! [here](https://github.com/Shawn-Zhenshan-Jin/Grocery/blob/master/extracted_text.txt) is the extracted text.

For your reference, the following is the code that I used to get sentences from the extracted text. 
`   

    from spacy.en import English
 
    nlp = English()
    
    parsedData = nlp(_text)
    
    sents = []
    for span in parsedData.sents:
        sent = ''.join(parsedData[i].string for i in range(span.start, span.end)).strip()
        sents.append(sent)
    
    sents = sents_pre_process(sents) # pre-process: combine some sub-sentences into one sentence`
sents_pre_process:
`   

    def sents_pre_process(sents):
        # sentence starting with abnormal puncionation
        sents_new1 = []
        abnormal_start = [",", ".", ";"]
        sent_corrected = ""
        corrected = False
        for idx, sent in enumerate(sents):
            if any([sent.startswith(ch) for ch in abnormal_start]):
                sent_corrected += sent
                corrected = True
            else:
                if corrected:
                    sents_new1.append(sent_corrected)
                    corrected = False
                if idx == len(sents) - 1: # last elements
                    sents_new1.append(sent)
                else:
                    if not any([sents[idx + 1].startswith(ch) for ch in abnormal_start]):# don't output if next element is abnormal start
                        sents_new1.append(sent)
                sent_corrected = sent
    
        # sentence end with abnormal puncionation
        sents_new2 = []
        abnormal_end = [";", ","]
        sent_corrected = ""
        corrected = False
        for idx, sent in enumerate(sents_new1):
            if any([sent.endswith(ch) for ch in abnormal_end]) and (idx != len(sents_new1) - 1):
                if not corrected:
                    sent_corrected = sent + sents_new1[idx + 1]
                else:
                    sent_corrected = sent_corrected + sents_new1[idx + 1]
                corrected = True
            else:
                if corrected:
                    sents_new2.append(sent_corrected)
                    corrected = False
                else:
                    sents_new2.append(sent)
            
        return sents_new2`

**Comment by honnibal** [comment]
Hm. Are you just doing:

```python

import spacy

nlp = spacy.load('en')
doc = nlp(text)
len(doc.ents)
```

I get 827 entities with 1.9 and `en_core_web_sm`. Many are numbers etc, so are you counting differently?

**Comment by Shawn-Zhenshan-Jin** [comment]
@honnibal Thanks for your help! I figured it out that I forget there is some screening mechanism in my code. And Finally, I get the same kind of result as yours. by passing the whole paper extracted text,  I get 826 entities and by passing sentences, I get 814 entities. The following is the entity portfolio for the two ways to pass text: 
**By whole text**
![by_text](https://user-images.githubusercontent.com/14370804/30707359-dfb06b98-9ec0-11e7-901d-28b63b80ceae.png)  
**By sentences**
![by_sentence](https://user-images.githubusercontent.com/14370804/30707369-e3af903e-9ec0-11e7-85f9-210398d03075.png)  
The result is pretty much the same for long and short text. Again, thanks for your great work!

**BTW**: it seems like the documents for [Built-in entity types](https://spacy.io/docs/usage/entity-recognition) is out-dated. for example, FACILITY -> FAC(I guess) and LAW haven't been documented. I'm wondering is there a way to get the most updated list of built-in entity types on the fly?
