### ISSUE TITLE
Tokenizer special case doesn't apply

### ISSUE THREAD

**Issue by kernelmachine** [explosion/spaCy#1345]
The tokenizer doesn't seem to use my special case, which prevents splitting a specific substring (in this case, a name) during tokenization.

```
import spacy
from spacy.symbols import ORTH
model = spacy.load('en')
model.tokenizer.add_special_case("James Bond", [{ORTH: "James Bond"}])
doc = model("My name is James Bond")
for token in doc:
    print('token.i: {2}\ttoken.idx: {0}\ttoken.pos: {3:10}token.text: {1}'.
      format(token.idx, token.text,token.i,token.pos_))
```

prints:

```
token.i: 0      token.idx: 0    token.pos: ADJ       token.text: My                                   
token.i: 1      token.idx: 3    token.pos: NOUN      token.text: name                                 
token.i: 2      token.idx: 8    token.pos: VERB      token.text: is                                   
token.i: 3      token.idx: 11   token.pos: PROPN     token.text: James                                
token.i: 4      token.idx: 17   token.pos: PROPN     token.text: Bond  
```

"James Bond" should be one token after application of special case.

## Your Environment
* Operating System: Mac OS X
* Python Version Used: 3.6.2
* spaCy Version Used: 1.9
* Environment Information: venv

**Comment by honnibal** [comment]
The one thing that's hard-coded into the tokenizer is splitting on the space character (`' '`). You can't use special-case rules to get around this. We should check for spaces in the rules though!

The solution is to use the rule-based matcher, with the `merge_phrases` callback. See here: https://spacy.io/docs/usage/rule-based-matching

**Comment by lesley2958** [comment]
Is this something that we want to change about the API?

**Comment by honnibal** [comment]
@lesley2958 It's not perfect, but I don't now how to make it overall better. Splitting on custom characters is likely to slow down the tokenizer a lot.
