### ISSUE TITLE
ValueError: String is too long: 1796416880 characters. Max is 2**30.

### ISSUE THREAD

**Issue by zotroneneis** [explosion/spaCy#1347]
I am trying to parse a large text file, using

from spacy.de import German
parsed = nlp(file)

which causes the error

Traceback (most recent call last):
  File "./test.py", line 17, in <module>
    parsed = nlp(all_tokens)
  File "/home/aydin/.local/lib/python3.5/site-packages/spacy/language.py", line 320, in __call__
    doc = self.make_doc(text)
  File "/home/aydin/.local/lib/python3.5/site-packages/spacy/language.py", line 293, in <lambda>
    self.make_doc = lambda text: self.tokenizer(text)
  File "spacy/tokenizer.pyx", line 125, in spacy.tokenizer.Tokenizer.__call__ (spacy/tokenizer.cpp:5129)
ValueError: String is too long: 1796416880 characters. Max is 2**30.

Is there any workaround for this? I cannot split the file in half as this is likely to split a word or sentence.

## Your Environment
* **Python version:** 3.5.2
* **Installed models:** de_DE,
* **spaCy version:** 1.9.0
* **Platform:** Linux-4.4.0-93-generic-x86_64-with-Ubuntu-16.04-xenial

**Comment by honnibal** [comment]
If the text file is that large, surely you can find some way to identify section boundaries?

**Comment by zotroneneis** [comment]
The document doesn't contain clear section boundaries. Right now I am searching for the last occurrence of "." in the first half of the document and then splitting the document using that index (hoping that this won't split a sentence or word). However, a full stop doesn't always correspond to the end of a sentence so I was wondering whether a different solution exists.

**Comment by Liebeck** [comment]
@zotroneneis Are there any other characters that indicate paragraphs, for instance line breaks?

**Comment by zotroneneis** [comment]
Not in the version that I have. But they might have been removed in some of the preprocessings step. I will check, thanks for the idea!
