### ISSUE TITLE
Running setup.py bdist_wheel for thinc ... error

### ISSUE THREAD

**Issue by dtsukiyama** [explosion/spaCy#1348]
Hi,

Spacy-nightly fails to install in virtualenv. It's odd because 10 days ago I did not encounter this problem (And I have not really been using my laptop much in those intervening 10 days because of jury duty). All my other environments spacy-nightly and thinc are installed, the latest being 10 days ago. I have tried updating gcc, it still fails to install.  It fails regardless of the Python version. 

```
Building wheels for collected packages: thinc
  Running setup.py bdist_wheel for thinc ... error
  Complete output from command /home/env_gpu/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mmMcs9/thinc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmptHVg5dpip-wheel- --python-tag cp27:
```

Ending with:

```
    x86_64-linux-gnu-gcc: error: thinc/linalg.cpp: No such file or directory
    x86_64-linux-gnu-gcc: fatal error: no input files
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
and:

```
    ----------------------------------------
Command "/home/env_gpu/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mmMcs9/thinc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-CqE8eO-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/env_gpu/include/site/python2.7/thinc" failed with error code 1 in /tmp/pip-build-mmMcs9/thinc/
```

## Your Environment

* Operating System: Ubuntu 16.04
* Python Version Used: 2.7, 3.5
* spaCy Version Used: 2.0.0a9, 2.0.0a13, 2.0.0a14

**Comment by honnibal** [comment]
Hm, strange.

What happens if you do `pip install --no-cache-dir thinc` directly?

**Comment by dtsukiyama** [comment]
If I do ```pip install --no-cache-dir thinc``` I now get an error on murmurhash:

`Running setup.py install for murmurhash ... error
    Complete output from command /home/env_gpu/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lNRDPA/murmurhash/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-eBmS8F-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/env_gpu/include/site/python2.7/murmurhash:`

**Comment by dtsukiyama** [comment]
Do you mean ```pip install --no-cache-dir murmurhash``` or just ```pip install murmurhash```?

```pip install murmurhash``` works but thinc still fails.  ```pip install --no-cache-dir murmurhash``` fails.

**Comment by dtsukiyama** [comment]
I also attempted to install spacy-nightly on one of my Google Cloud Platform VMs, it also failed there.

**Comment by honnibal** [comment]
I suspect you're probably missing a system package. Perhaps `python-dev`?

Here's how I provision a 17.04 image on GCE to install spacy-nightly on Python 3:

    sudo apt-get update
    sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
        libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
        xz-utils tk-dev python3.6 python3.6-venv python3.6-dev

If you're using Python 2.7, you'll want to install `python-virtualenv` and `python-dev`.

**Comment by ines** [comment]
Could you try again with the new version, v2.0 and the solution mentioned by @honnibal? If the problem sill persists, feel free to reopen.

**Comment by tarsisazevedo** [comment]
I did everything here and I'm got a new error! \o/
`x86_64-linux-gnu-gcc: error: unrecognized command line option ‘-Qunused-arguments’; did you mean ‘-Wunused-parameter’?`

System: Ubuntu 17.10
Python: 3.6
gcc: 7.2
Spacy: 2.0.3
