### ISSUE TITLE
phrasematcher attr='LOWER' fails initialization when used in a pipeline

### ISSUE THREAD

**Issue by larrymccutchan** [explosion/spaCy#13489]
## How to reproduce the behaviour
Using the example provided in https://spacy.io/usage/processing-pipelines#custom-components-attributes for RESCountriesComponents. 

Update the matcher to the following:
self.matcher = PhraseMatcher(nlp.vocab, attr="LOWER") # set the LOWER attrib instead of ORTH

The failure is the following:
ValueError: [[E109](https://docs.databricks.com/error-messages/error-classes.html#e109)] Component 'rest_countries' could not be run. Did you forget to call `initialize()`?
File /databricks/python/lib/python3.10/site-packages/spacy/language.py:1049, in Language.__call__(self, text, disable, component_cfg)
   1048 try:
-> 1049     doc = proc(doc, **component_cfg.get(name, {}))  # type: ignore[call-arg]
   1050 except KeyError as e:
   1051     # This typically happens if a component is not initialized
File /databricks/python/lib/python3.10/site-packages/spacy/language.py:1052, in Language.__call__(self, text, disable, component_cfg)
   1049     doc = proc(doc, **component_cfg.get(name, {}))  # type: ignore[call-arg]
   1050 except KeyError as e:
   1051     # This typically happens if a component is not initialized
-> 1052     raise ValueError(Errors.E109.format(name=name)) from e
   1053 except Exception as e:
   1054     error_handler(name, proc, [doc], e)

## Your Environment

**spaCy version:** 3.7.2
- **Platform:** Linux-5.15.0-1058-aws-x86_64-with-glibc2.35
- **Python version:** 3.10.12

**Comment by larrymccutchan** [comment]
Please close this. I figured out the problem and it was NOT concerning the attr="LOWER" but was another bug in the code I was using.

**Comment by svlandeg** [comment]
Thanks for reporting back! I'll go ahead and close this 🙏
