### ISSUE TITLE
How to train the sentence segmenter

### ISSUE THREAD

**Issue by adelevie** [explosion/spaCy#1349]
This is a documentation request.

This page https://spacy.io/docs/usage/training has examples for training spaCy for parts of speech and named entities, for example, but there isn't anything shown for training for sentence segmentation. Is this something that can be done with spaCy? NLTK, for example, allows training data to be loaded (line-delimited sentences and known abbreviations). I've found such features to be helpful to train models for some specific domains, and would love to try that out with spaCy.

## Your Environment

n/a, for now.

**Comment by honnibal** [comment]
The default sentence segmentation is derived from the dependency parse, making it complicated to retrain. spaCy 2 adds a new sentence boundary detection component, see here: https://github.com/explosion/spaCy/blob/develop/spacy/pipeline.pyx#L49

You could pass in a `strategy` function that used `nltk`'s punkt algorithm, for instance.
