### ISSUE TITLE
3.7.5 needs to be released soon

### ISSUE THREAD

**Issue by stevereiner** [explosion/spaCy#13518]
It looks like 3.7.5 would fix the issue with 3.7.4 
3.7.4 spacy requires an older version of typer, older version of weasel
Fastapi (fastapi-cli) requires newer version of typer and installs 0.12 typer
older weasel requires older typer

## How to reproduce the behaviour
pip install -U fastapi
pip install -U spacy
ERROR: .... fastapi-cli 0.0.4 requires typer>=0.12.3, but you have typer 0.9.4 which is incompatible.

- **spaCy version:** 3.7.4
- **Platform:** Windows-11-10.0.22631-SP0
- **Python version:** 3.12.3
- **Pipelines:** en_core_web_lg (3.7.1), en_core_web_md (3.7.1), en_core_web_sm (3.7.1), en_core_web_trf (3.7.3)

**Comment by svlandeg** [comment]
Hi! Yes - we're very much aware of this. We hit an issue while building the wheels and we're working on getting this fixed ASAP.

**Comment by svlandeg** [comment]
The combination of the following releases should fix these issues:
- https://pypi.org/project/spacy/3.7.5/
- https://pypi.org/project/thinc/8.2.4/
- https://pypi.org/project/weasel/0.4.1/
- https://pypi.org/project/confection/0.1.5/
- https://pypi.org/project/wasabi/1.1.3/
