### ISSUE TITLE
Saving NER Model

### ISSUE THREAD

**Issue by Rahul6818** [explosion/spaCy#1353]
I want to save the entity recognition model so that i don't have to train it again and again. 
My question is do we have to save entire nlp or ner=nlp.entity (which is EntityRecognizer) will be sufficient.

**Comment by honnibal** [comment]
In spaCy 1 the NER model, depends on the vocab, string store, POS tagger and parser. The vocab and string store are modified during the NER training, so you have to make sure those components are persisted and loaded along with the trained NER model. The simplest solution is to persist the entire `nlp` object, which you can then package with `spacy package` and load as a module.

In spaCy 2 the NER doesn't depend on the vocab or tagger, but it *does* depend on the tensorizer. So the recommendation's really the same: it's best to save out the whole pipeline, to avoid fiddling with the internals too much.
