### ISSUE TITLE
Key error when using Doc.to_bytes()

### ISSUE THREAD

**Issue by arnosimons** [explosion/spaCy#1354]
I followed the instructions on how to save a Spacy-Doc as .bin file by copy-pasting the code from https://spacy.io/docs/api/doc, but I got a KeyError Message. 

Code:
```
import spacy
nlp = spacy.load('en')
from spacy.tokens.doc import Doc
loc = 'test_serialize.bin'
with open(loc, 'wb') as file_:
    file_.write(nlp(u'This is a document.').to_bytes())
```
Outputs:
```
Traceback (most recent call last):
  File "/Users/arnosimons/Projects/rdatools/rdatools/tests/savedocs.py", line 7, in <module>
    file_.write(nlp(u'This is a document.').to_bytes())
  File "spacy/tokens/doc.pyx", line 621, in spacy.tokens.doc.Doc.to_bytes (spacy/tokens/doc.cpp:12188)
  File "spacy/serialize/packer.pyx", line 112, in spacy.serialize.packer.Packer.pack (spacy/serialize/packer.cpp:5770)
  File "spacy/serialize/huffman.pyx", line 63, in spacy.serialize.huffman.HuffmanCodec.encode (spacy/serialize/huffman.cpp:2554)
KeyError: 512817

```
Can anyone help me out here? I have no clue what is going on. I am new to Spacy and I am actually using it through [textacy](https://github.com/chartbeat-labs/textacy). But since this seems to be a Spacy related issue, I post it here.

I browsed the existing issues related to the to_bytes method but could not find anything useful. Instead, I found that I even get the same KeyError when trying to reproduce code snippets of other users that reportedly worked fine. E.g. when I run the following snippet from [here](https://github.com/explosion/spaCy/issues/728), which the user said worked fine for him (his issue came later when trying to desserialize), it also crashes with above KeyError on my computer:

```
from spacy.tokens.doc import Doc
import spacy
nlp = spacy.load("en")
text = u"Hello world."

# Parse it. Works.
doc = nlp(text)
print len(set([o for o in doc]))

# Save a serialized copy
with open("out",'w') as f:
    f.write(str(doc.to_bytes()))
...
```

* Operating System: MacOS Sierra 10.12.4
* Python Version Used: 2.7.11
* spaCy Version Used: 1.9.0

**Comment by honnibal** [comment]
Could you check that the model is installed? `python -m spacy info en` should do it.

My hunch is that the model isn't installed, and that's causing the serialisation failure (it shouldn't, but...well, that doesn't mean it isn't).

I took great joy in finally deleting that serialization code for spaCy 2 :p. `spacy.load()` raises an error when models aren't found in spaCy 2, also. You can try the new version with `pip install spacy-nightly`. Docs at https://alpha.spacy.io

**Comment by arnosimons** [comment]
Many thanks for your quick reply and the hint! I solved it.

The issue was not, however, that the model was not installed, but probably that it was an older version. At least, this was the output before reinstalling the model...
```
... $ python -m spacy info

    Info about spaCy

    Python version     2.7.11         
    Platform           Darwin-16.5.0-x86_64-i386-64bit
    spaCy version      1.9.0          
    Installed models    __cache__, en, en_default, en_default-1.0.8
    Location           /usr/local/lib/python2.7/site-packages/spacy
```
Now after reinstalling via ``python -m spacy download en`` everything works fine!!! Yeaa :-) Running this version now:  en_core_web_sm-1.2.0 model (not sure which one I had installed before).

**Comment by ines** [comment]
Glad you got it working – thanks for updating with the solution!
