### ISSUE TITLE
spacy.set_factory is not defined in V2

### ISSUE THREAD

**Issue by christian-storm** [explosion/spaCy#1357]
In researching/writing a response to #1105 I was trying to get factory components working but haven't been able to.  To that end I don't see any mention of set_factory in the code base.  Has it be implemented yet?

## Your Environment
* **spaCy version:** 2.0.0a13
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **Python version:** 3.6.0
* **Models:** en, en_core_web_sm

**Comment by honnibal** [comment]
I'm still not thrilled about the factory stuff.

Maybe we should just accept having pipeline-specific `load()` functions? Then we could move the pipeline assembly out of the `Language.__init__` altogether.

**Comment by honnibal** [comment]
See https://github.com/explosion/spaCy/pull/1396
