### ISSUE TITLE
ValueError while importing spacy module related to thinc (?)

### ISSUE THREAD

**Issue by alexcorral** [explosion/spaCy#13628]
This is the description of the error: "ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject"

![image](https://github.com/user-attachments/assets/6976731b-630e-4a97-bcbd-39e0f47edb0a)

## Your Environment
* Operating System: Windows
* Python Version Used: 3.9.18
* spaCy Version Used: 3.7.6
* Environment Information: Enterprise codespace

I encounter the error below when importing spacy module. It happens sometimes:

![image](https://github.com/user-attachments/assets/ab7bc2e1-e3ea-4a9e-a5b0-d9c7d471a15f)

**Comment by honnibal** [comment]
New release v3.8 is up, which should fix the problem. Please reopen or re-report if it didn't.

Sorry about the disruption with this. It was tricky to track down all the changes needed for the numpy compatibility across our dependency tree.
