### ISSUE TITLE
spacy[cuda12x] not work with windows 11 torch 2.3.1 cu 12.1 WinError 127 cufftw64_11.dll

### ISSUE THREAD

**Issue by lrzjason** [explosion/spaCy#13648]
## How to reproduce the behaviour

When I tried to use spacy with torch 2.3.1 cu12.1, I have the following error with whatever version of spacy. (Tried 3.8, 3.7.5, 3.6.1)
![{$F {7_524%D9H~JKQ}HSG8](https://github.com/user-attachments/assets/977a1540-cb78-419b-925c-a15f1193281d)
I tried to install cuda 11.8 and torch 2.3.1 cu118 and solved the issue.

## Your Environment

* Operating System: Windows 11
* Python Version Used: 3.10
* spaCy Version Used: 3.7.5
* Environment Information: Torch 2.3.1 cu12.1

**Comment by honnibal** [comment]
It looks like `import torch` fails. If you make a script that just imports PyTorch, does that work?

**Comment by lrzjason** [comment]
Thanks for advice. Seems it is due to another environment problem. I reinstalled the whole cuda enviroment and visual studio 2019(Original using 2022 17.11, now 2019 16.11). The problem solved. Now, it is able to use torch 2.3.1 cu12.1 with spacy 3.7.5.
