### ISSUE TITLE
spacy.load of a custom language, using linked model, does not return the custom language

### ISSUE THREAD

**Issue by IamJeffG** [explosion/spaCy#1366]
I am using SpaCy for NLP tasks on English text from a unique subject domain. I'd like to make gradual improvements to SpaCy's extant English model (specifically I'm starting from `'en_core_web_md'`), and package them for easy re-use by my colleagues.

```bash
# for now, reuse English model as-is.
$ python -m spacy link en_core_web_md en_mydomain
# Linking successful
# You can now load the model via spacy.load('en_mydomain').
```

```python
class DomainSpecificEnglish(English):
    """Domain-specific language with custom tokenizer"""
    lang = 'en_mydomain'

    class Defaults(English.Defaults):
        _number_then_alpha_re = u'''(?<=[0-9])(?=[A-Za-z])'''
        infixes = English.Defaults.infixes + (_number_then_alpha_re, )


spacy.util.set_lang_class(DomainSpecificEnglish.lang, DomainSpecificEnglish)
```

This seems like it will work fine:

```python
>>> DomainSpecificEnglish().tokenizer.find_infix(u'123abcd 99zz')
[<regex.Match object; span=(3, 3), match=u''>,
 <regex.Match object; span=(10, 10), match=u''>]

>>> spacy.util.get_lang_class('en_mydomain')
__main__.DomainSpecificEnglish
```

However, there's a problem. When I try to load the language in the traditional way, I am not getting my custom language object back:

```python
>>> nlp = spacy.load('en_mydomain')
>>> type(nlp)
spacy.en.English    # I would expect DomainSpecificEnglish
```
and along with that unexpected type, this `nlp` object (unsurprisingly) does not include my custom changes to the tokenizer.

Now, if I _do not_ point it to the English language model directory (either by never creating the symlink or by changing the `lang` string to gobbledygook, then `spacy.load` does return the correct class, and the custom tokenizer works.  So there's some interaction between the model directory and the class that `spacy.load` returns that is unexpected.  I think this is a bug: please let me know if my expectations are reasonable!

## Your Environment
* **Python version:** 2.7.12
* **Platform:** Linux-4.4.70+-x86_64-with-Ubuntu-16.04-xenial
* **spaCy version:** 1.9.0
* **Installed models:** en_mydomain, en

**Comment by honnibal** [comment]
Could it be that when you're loading it back, you no longer have the language class associated?

If you've used `spacy package` to get a pip package around your model, the following should work more reliably:


```python

import en_mydomain

nlp = en_mydomain.load()
```

This also gives you a bit more flexibility for shipping out code to your colleagues --- you can put the code in the `__init__.py` etc.

**Comment by IamJeffG** [comment]
Would you recommend against using `spacy package` over an input directory that I'd created using `spacy link`? (If one does that, the new package takes the same name of the link destination, not the link name).

Instead of `spacy link` I _can_ get results by fully copying the `en_core_web_md` directory as a new real directory `en_mydomain`, and then `spacy package /path/to/en_mydomain --create-meta`.

> you can put the code in the `__init__.py` etc.

Do you mean I copy my `DomainSpecificEnglish` class definition into the `__init__.py` that's been created by `spacy package`?

**Comment by ines** [comment]
@IamJeffG I'm not sure I understand your question correctly – but when you use `spacy package` and the directory contains a `meta.json`, spaCy will use this data to set up the model meta. (Unless you set `--create-meta`, in which case you can overwrite it.) In theory, the symlinks created via `link` shouldn't make a difference here – however, I guess it's always cleaner and less confusing to work with the real paths of the destination.

> Do you mean I copy my `DomainSpecificEnglish` class definition into the `__init__.py` that's been created by `spacy package`?

Yes! This was part of the concept when we introduced models as Python packages. It gives you the opportunity to ship any custom code with your model – for example, modifications to the `Language` class, or going forward, also custom, model-specific [pipeline components](https://alpha.spacy.io/usage/processing-pipelines#custom-components). 

When you load a model, all spaCy does is create an instance of `Language` using the language specified by the model meta. So if your model sets `"lang": "en"`, spaCy will call `util.get_lang_class('en')`. It then sets the pipeline and loads in the binary data using `Language.from_disk()`. [See here](https://alpha.spacy.io/api/top-level#util.load_model_from_path) for the API of the util functions that handle this, and [here](https://github.com/explosion/spaCy/blob/develop/spacy/util.py#L133) for the code.

**Comment by IamJeffG** [comment]
This was an excellent summary.  All is working now, thanks!  I think symlinking without replacing `meta.json` was my problem.  Closing.
