### ISSUE TITLE
Issue with detecting "être" in verb lemmatization using SpaCy

### ISSUE THREAD

**Issue by souksili** [explosion/spaCy#13672]
**Description of the problem:**

I am encountering an issue with lemmatizing verbs using SpaCy. My goal is to convert all conjugated verbs to their infinitive forms. However, when analyzing sentences containing the verb "être," such as "Je suis en train de manger," the conjugated verb "suis" is not detected as a verb. Only the infinitive form of "manger" is identified.

**Code snippet:**

```python
import spacy

# Load the French model from SpaCy
nlp = spacy.load("fr_core_news_md")

def find_conjugated_verbs_and_infinitives(phrase):
    doc = nlp(phrase)  # Analyze the phrase with SpaCy
    conjugated_verbs = [token.text for token in doc if token.pos_ == "VERB"]
    infinitives = [token.lemma_ for token in doc if token.pos_ == "VERB"]
    return conjugated_verbs, infinitives

# Phrase to analyze
phrase = "Je suis en train de manger"
conjugated_verbs, infinitives = find_conjugated_verbs_and_infinitives(phrase)
print("Conjugated verbs found:", conjugated_verbs)
print("Infinitives found:", infinitives)
```

**Obtained result:**
Conjugated verbs found: ['manger']
Infinitives found: ['manger']

**Expected result:**
Conjugated verbs found: ['suis', 'manger']
Infinitives found: ['être', 'manger']

**Comment by lsmith77** [comment]
@souksili why did you close the issue?
