### ISSUE TITLE
spaCy v2.0.0a14 commit

### ISSUE THREAD

**Issue by johncordeiro** [explosion/spaCy#1369]
I'm trying to figure out how to get the specific point in git repository history which version 2.0.0a14 was generated from. It's supposed to be a tag, but it's not. Is there any way to discover which commit was?

**Comment by honnibal** [comment]
Regretably we haven't been making tags for the `spacy-nightly` releases. This is dumb and it's inconvenienced us too.

PyPi says the build was uploaded September 19. This one looks likely: https://github.com/explosion/spaCy/commit/217e7891cdc104c6a137a7729a9c8022c508ce90

Sorry this is so messy!
