### ISSUE TITLE
Is it possible to retrieve the training data from the trained spaCy NER model

### ISSUE THREAD

**Issue by Zhenshan-Jin** [explosion/spaCy#1372]
I'm thinking that all the data should be inside `vocab` with `lexemes.bin` and `strings.json`, so it should be possible to do some reverse engineering.

If that is impossible, is that feasible to get all the training data for the default `en_core_web_sm` model? My goal is to mixed the `en_core_web_sm` training data with my training data to avoid forgetting catastrophic mentioned in [this article](https://explosion.ai/blog/pseudo-rehearsal-catastrophic-forgetting) by @honnibal 

Thanks!

## Your Environment

* Operating System: Ubuntu 16.04
* Python Version Used: 3.6
* spaCy Version Used: 1.9

**Comment by honnibal** [comment]
The NER is trained on OntoNotes 5, which we're not licensed to distribute.

**Comment by Zhenshan-Jin** [comment]
Thanks!
