### ISSUE TITLE
python -m spacy download should not overwrite an existing model of the same name

### ISSUE THREAD

**Issue by jnothman** [explosion/spaCy#1373]
`python -m spacy download` should, in my opinion, not download when doing so would overwrite an existing model. This would primarily be to allow downloading to be lazy, but would also mean that one can use `python -m spacy download en` to either check the model exists or upgrade/install.

## Info about spaCy

* **spaCy version:** 1.9.0
* **Platform:** Linux-2.6.32-696.6.3.el6.x86_64-x86_64-with-redhat-6.9-Santiago
* **Python version:** 3.6.0
* **Installed models:** en

**Comment by honnibal** [comment]
Agreed, this has been bothering me lately too, especially with large models.

Are you likely to have time to submit a patch? It would be good to have the conservative behaviour on a flag to start with, and then we can switch the default semantics for v2.

**Comment by jnothman** [comment]
sorry, Matt, it's a good one for you to get new contributors to attack, but
I've got my hands pretty full

**Comment by ines** [comment]
Good point! 👍 

I think the solution should be as simple as appending the model name and version to the file URL in `cli.download`, e.g. `#egg=en_core_web_sm-2.0.0a0` ([see here](https://github.com/explosion/spaCy/issues/1143)). This should tell pip which package and version you're trying to download and make it behave like it does when you're downloading packages from PyPi.

Will test this!

**Comment by jnothman** [comment]
+ "help wanted" label?

**Comment by ines** [comment]
@jnothman 
@honnibal just created a master issue for some other download-related enhancements and I've updated it to include this issue as well. Since we'll likely be introducing changes to the `download` API anyways, it probably makes sense to tackle all of these issues at the same time. So I'm merging this one with #1456.
