### ISSUE TITLE
nbor method for Token class does not raise error when an out-of-bounds index is asked for

### ISSUE THREAD

**Issue by jrnold** [explosion/spaCy#1375]
The `nbor` method for `Token` objects does not raise an `IndexError` when asked for an index before the document starts. The example below shows that asking for the previous token for the first token of the document, `doc[0].nbor(-1)`, returns the *last* token in the document rather than returning `None` or raising and `IndexError` (either of which seems reasonable to me). The method works fine when asked for a token after the document, e.g. `doc[len(doc) - 1].nbor(1)`. 

```
In [1]: import spacy

In [2]: spacy.__version__
Out[2]: '1.9.0'

In [3]: nlp = spacy.load("en")

In [4]: doc = nlp("The quick brown fox jumped over the lazy dog.")

In [5]: n = len(doc)

In [6]: doc[0].nbor(-1)
Out[6]: .

In [7]: doc[0].nbor(-2)
Out[7]: dog

In [8]: doc[n - 1].nbor(1)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-8-000c364ca9e7> in <module>()
----> 1 doc[n - 1].nbor(1)

~/anaconda3/lib/python3.6/site-packages/spacy/tokens/token.pyx in spacy.tokens.token.Token.nbor (spacy/tokens/token.cpp:5055)()

~/anaconda3/lib/python3.6/site-packages/spacy/tokens/doc.pyx in spacy.tokens.doc.Doc.__getitem__ (spacy/tokens/doc.cpp:5564)()

IndexError: list index out of range
If you're looking for help with your code, consider posting a question on StackOverflow instead:
http://stackoverflow.com/questions/tagged/spacy -->
```

## Your Environment

* **spaCy version:** 1.9.0
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **Python version:** 3.6.2
* **Installed models:** en, en_core_web_md

**Comment by honnibal** [comment]
This bug has been present from day 1, making this the current champion for "longest-standing error". Thanks!
