### ISSUE TITLE
TypeError: function() got multiple values for keyword argument 'pretrained_dims'

### ISSUE THREAD

**Issue by spate141** [explosion/spaCy#1379]
I am trying to run [train_ner](https://github.com/explosion/spaCy/blob/develop/examples/training/train_ner.py) and getting this error message! Any help?

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-1beb7db6cbbd> in <module>()
     40     # Khan "" PERSON 1
     41     # ? "" 2
---> 42     main()

<ipython-input-3-1beb7db6cbbd> in main(model_dir)
     13     nlp = English(pipeline=['tensorizer', 'ner'])
     14     get_data = lambda: reformat_train_data(nlp.tokenizer, train_data)
---> 15     optimizer = nlp.begin_training(get_data)
     16 
     17     for itn in range(100):

/root/anaconda2/lib/python2.7/site-packages/spacy/language.pyc in begin_training(self, get_gold_tuples, **cfg)
    373             if hasattr(proc, 'begin_training'):
    374                 context = proc.begin_training(get_gold_tuples(),
--> 375                                               pipeline=self.pipeline)
    376                 contexts.append(context)
    377         learn_rate = util.env_opt('learn_rate', 0.001)

pipeline.pyx in spacy.pipeline.TokenVectorEncoder.begin_training()

TypeError: function() got multiple values for keyword argument 'pretrained_dims'
```

### Info about spaCy

* **Python version:** 2.7.13
* **Platform:** Linux-4.4.0-1026-aws-x86_64-with-debian-stretch-sid
* **spaCy version:** 2.0.0a14
* **Models:** en_core_web_sm

**Comment by tony** [comment]
I get this one when following the docs at: http://alpha.spacy.io/docs/usage/training-ner / https://github.com/explosion/spaCy/blob/develop/examples/training/train_ner.py

    Info about spaCy

    spaCy version      2.0.0a14
    Location           /Users/me/work/develtech/.venv/lib/python3.6/site-packages/spacy
    Platform           Darwin-16.7.0-x86_64-i386-64bit
    Python version     3.6.2
    Models             en, en_core_web_md

**Comment by spate141** [comment]
@tony I am following the exact same script and getting same `TypeError: function() got multiple values for keyword argument 'pretrained_dims'` error!

**Comment by honnibal** [comment]
Try again with `spacy-nightly-2.0.0a16`. You should redownload the models, with `spacy download en_core_web_sm` and `spacy download en_core_web_lg`.
