### ISSUE TITLE
How to lemmatize a certain word.

### ISSUE THREAD

**Issue by ryohei1540** [explosion/spaCy#1383]
When I tried to lemmatize a sentence "I need you.", it seems like not right which is "need".

Here is the code.
```
aaa = nlp("I need you.")

for a in aaa:
    print(a.lemma_)
```

Here is the output.
```
-PRON-
ne
-PRON-
.
```
How can I get the right result about "need"?

**Comment by honnibal** [comment]
This is a bug in the lemmatizer, that's been fixed. You should be able to fix it in your local version with:

```python

nlp.vocab.morphology.add_special_case('VBP', 'need', {'LEMMA': 'need'})
```

I *think* that's right -- I can't try it just now.

**Comment by ryohei1540** [comment]
Thank you so much for your comment!
