### ISSUE TITLE
"open account" why open is not a verb

### ISSUE THREAD

**Issue by hoyeunglee** [explosion/spaCy#1388]
https://gist.github.com/hoyeunglee/f8dad72794041d2b104e384da7573217

this part, after input "open account", open is not a VERB

```
    for ii in getlist(mm,"VERB"):
            print "find verb " + ii
            if ("open" in talksentence or "create" in talksentence ) and "account" in talksentence:

```

**Comment by honnibal** [comment]
Well...The model you're using isn't specifically for bots. It's for English in general --- so how's it supposed to know that the intended reading is 'VERB NOUN' and not 'ADJ NOUN'?

You could set the `token.tag_` to `VB` based on some rules you have. The rest of the pipeline will then process the text with that tag in place.

**Comment by hoyeunglee** [comment]
thank you, i find it as ADJ
