### ISSUE TITLE
Unable to install english model using older version - "urllib2.URLError: <urlopen error [Errno 110] Connection timed out>"

### ISSUE THREAD

**Issue by amir-barkal** [explosion/spaCy#1398]
We're getting a timeout error when executing:

`/usr/local/miniconda/bin/python -m spacy.en.download --force`

Using spacy version `spacy=0.101.0` with latest miniconda (`./Miniconda2-latest-Linux-x86_64.sh`)
We traced the repository to this IP address which seems to be non-responsive: `5.9.60.203`

Thanks!

**Comment by lexotero** [comment]
I have the same problem with `spacy==1.6.0` using command `python -m spacy.en.download`. Is the old download version already unsupported?

**Comment by ines** [comment]
I think there was a minor server outage earlier, but the model's server should be back online now. The models are also available as direct downloads, [attached to the v1.6.0 release](https://github.com/explosion/spaCy/releases/tag/v1.6.0).

We'll still keep the download server running, just to make things easier for users and CI workflows that depend on spaCy <=v1.6.0. However, if you are able to upgrade, we highly recommend doing so – especially going forward, once spaCy v2.0 is released. The new version comes with [neural network models](https://alpha.spacy.io/models) that are much smaller and more accurate overall and lots of improvements to the training and updating process etc.
