### ISSUE TITLE
http://index.spacy.io/ is in 502

### ISSUE THREAD

**Issue by LuisBL** [explosion/spaCy#1405]
http://index.spacy.io/ is in 502
```

$ curl -g http://index.spacy.io/ 
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
```

**Comment by honnibal** [comment]
Thanks, should be fixed now. For future reference, the models are available for direct download at https://github.com/explosion/spacy-models . You might also try upgrading, especially once the stable v2 is ready.

**Comment by rlvoyer** [comment]
This is happening to me, too. I'm using `spacy==0.101.0` and I'm getting a 502 when downloading models via `python -m spacy.en.download`.

**Comment by discordianfish** [comment]
Yes, seems like it's down again. Is there a built-in way to download the models from github instead?

**Comment by rlvoyer** [comment]
@honnibal I experience the same issue when using spacy==1.0.1.

**Comment by rlvoyer** [comment]
Seems to be working again. ¯\_(ツ)_/¯

**Comment by discordianfish** [comment]
Yes, I've upgraded spacy to 1.7.5 in the meanwhile though, which uses a new download mechanism which hopefully is more reliable.
