### ISSUE TITLE
pypi README malformed (possible error in RST)

### ISSUE THREAD

**Issue by tony** [explosion/spaCy#1412]
On https://pypi.python.org/pypi/spacy (since at least [1.9.0](https://pypi.python.org/pypi/spacy/1.9.0) package)

<img width="1171" alt="screen shot 2017-10-11 at 5 04 14 am" src="https://user-images.githubusercontent.com/26336/31434325-a7fcb3f6-ae41-11e7-9bc5-fa70877af065.png">

[1.8.0](https://pypi.python.org/pypi/spacy/1.8.0)-[1.8.2](https://pypi.python.org/pypi/spacy/1.8.2) shows fine.

This is likely due to an error in RST

**Comment by tony** [comment]
rst2html isn't showing any errors with docutils 0.14

<img width="906" alt="screen shot 2017-10-11 at 5 01 48 am" src="https://user-images.githubusercontent.com/26336/31434214-5938f608-ae41-11e7-8115-4ff45206d8fa.png">

**Comment by ines** [comment]
Thanks for the report – I noticed that, too and already validated the RST. I usually pay *very* close attention to the RST formatting (haha), so this was very confusing... [`spacy-nightly`](https://pypi.python.org/pypi/spacy-nightly),
 which is pretty much identical, looks fine btw.

We might try re-uploading the data (I think that's possible now on PiPy?) or just wait for `v1.10.0` and see if it fixes itself.

**Comment by tony** [comment]
I can't figure out what it is. If I remember correctly,  I think you can login to pypi and try re-saving the README file to retrigger it and see if it helps.

Aside from that, it's not a top priority. Google probably would like it since the pypi is on the front page for "spacy".

**Comment by ines** [comment]
Just pushed a new release and it's good again now: https://pypi.python.org/pypi/spacy-nightly 🎉

**Comment by ines** [comment]
All good now – no idea what went wrong there! https://pypi.python.org/pypi/spacy
