### ISSUE TITLE
GPU usage spaCy 2.0 

### ISSUE THREAD

**Issue by Zhenshan-Jin** [explosion/spaCy#1419]
## **Bug report**:     
There seems like some bugs for the newest version `spaCy-2.0.0a17`. When I'm trying to run with GPU it'll report the following error(I haven't tried with CPU, it is a bug in both CPU and GPU)
![image](https://user-images.githubusercontent.com/14370804/31577758-2035c354-b0da-11e7-8f28-4740e8bcea5b.png)  

## **Some personal experience about how to use GPU in spaCy 2.0**
Besides the instructions [here](https://alpha.spacy.io/usage/#gpu), I also need to do the following things which are from @honnibal 's instruction in other issue and my self-exploration: 
```
pip uninstall thinc
git clone https://github.com/explosion/thinc.git
cd thinc && python setup.py install
pip install cupy
```
specify begin_training as follow: `optimizer = nlp.begin_training(lambda: [], use_gpu = True, device = 0)`
The above steps works for `spaCy-2.0.0a16`  in my Ubuntu 16.04 and CUDA 8.0

## **Speed comparison**:
Currently, I'm using `spaCy-2.0.0a16` and everything works just fine. Thanks for the great work! GPU helps to accelerate the overall speed by 65%, which is awesome. 

## Question about how to use GPU and CPU:
1. I'm wondering if there is any way to fully cultivate the GPU since with `batch size = 200`, it only takes 15% of my `8G GeForce GTX 1060`. Any tutorial would be appreciated. 
2. When I'm using GPU, spaCy will take all my 16GB CPU. That's annoying. Is there any way to configure it? 

## Your Environment
* Operating System: Ubuntu 16.04
* Python Version Used: 3.6
* spaCy Version Used: spaCy-2.0.0a16
* Environment Information:

**Comment by honnibal** [comment]
I suspect you need to update the model for v2.0.0a17 -- it shouldn't have the tensorizer.

As far as GPU efficiency and memory usage goes, there's not really a simple setting at the moment. I've been working on making the CPU portions faster, so that the GPU doesn't starve. I've just released https://github.com/explosion/cython-blis which should help. In my Thinc branch that uses this, I'm getting 70% CPU speedups from this.

**Comment by Zhenshan-Jin** [comment]
Thanks!
