### ISSUE TITLE
Vector vocabulary not saved

### ISSUE THREAD

**Issue by lioryaffe** [explosion/spaCy#1431]
I'm trying to use spaCy to train new entity.
I downloaded the en_core_web_sm model, and i trained it on my new entity.
finally, I saved the model to a directory.

When i'm looking right now on the model in the code, I see there is the 300-dimension vector, but when i'm loading the saved model with spacy.load(model_name), I see it's empty.
is there a way to save the trained model with the vector?

after calling the
animal = nlp(text), on the vector field i'm getting:
word vectors set to length 0. This may be because you don't have a model installed or loaded, or because your model doesn't include word vectors. For more info, see the documentation: 
https://spacy.io/docs/usage

I'm using version 1.9

**Comment by honnibal** [comment]
Please see here --- the training is much improved in v2, and we've tried to give a lot more guidance about how to make good use of it: https://spacy.io/usage/training
