### ISSUE TITLE
Pattern does not match if text is shorter

### ISSUE THREAD

**Issue by emste** [explosion/spaCy#1434]
If the text that I'm passing to nlp() is shorter than the pattern I'm providing it won't match. That's ok until quantifiers come into play. I would expect that if the last token pattern I provide has an optional quantifier (like '?'), it should still match a text that is shorter than the pattern.

Example:
```
import spacy

from spacy.matcher import Matcher

nlp = spacy.load('en_core_web_sm')

def on_match(matcher, doc, i, matches):
    match_id, start, end = matches[i]
    match = doc[start : end].text
    print(f"on_match: {match}")

matcher = Matcher(nlp.vocab)
matcher.add('MyMatcher', on_match,  [ {'ORTH': 'Hello' }, {'IS_ALPHA': True, 'OP': '?'} ])

doc1 = nlp('Hello World')
doc2 = nlp('Hello')
matches1 = matcher(doc1)
matches2 = matcher(doc2)
print(matches1)
print(matches2)

# Output:
# on_match: Hello World
# [(12700758319762810043, 0, 2)]
# []
```

I expect it to match both 'Hello World' and 'Hello', but it only matches 'Hello World'.

## Info about spaCy
* **spaCy version:** 2.0.0a17
* **Platform:** Linux-4.9.49-moby-x86_64-with-debian-8.9
* **Python version:** 3.6.3
* **Models:** en_core_web_sm, xx_ent_wiki_sm

**Comment by honnibal** [comment]
Thanks!

**Comment by honnibal** [comment]
Turns out I thought of this case in general --- but missed it exactly on the `?` quantifier!

I doubt this will be the last `Matcher` bug you come across. Please keep reporting :)

**Comment by emste** [comment]
Thank you for the quick fix! I really appreciate your work, keep it up.
