### ISSUE TITLE
AttributeError's during pytest run; 

### ISSUE THREAD

**Issue by savkov** [explosion/spaCy#1436]
## Info about spaCy

* **spaCy version:** 1.9.0
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **Python version:** 3.6.2
* **Installed models:** en

I downloaded and compiled from source spaCy on MacOS, python3.6.2. The following stack trace is from an error that occurs when I run pytest in the spacy directory. Many tests fail apart from this one with the same/similar error.
<details>
________________________________________________________________________________ ERROR at setup of test_tokenizer_handles_two_suffix_url[Norwegian-http://foo.com/blah_(wikipedia)#cite-1->->] _________________________________________________________________________________

self = <_pytest.config.Config object at 0x10141b2b0>, name = 'slow', default = <NOTSET>, skip = False

    def getoption(self, name, default=notset, skip=False):
        """ return command line option value.
    
            :arg name: name of the option.  You may also specify
                the literal ``--OPT`` option instead of the "dest" option name.
            :arg default: default value if no option of that name exists.
            :arg skip: if True raise pytest.skip if option does not exists
                or has a None value.
            """
        name = self._opt2dest.get(name, name)
        try:
>           val = getattr(self.option, name)
E           AttributeError: 'CmdOptions' object has no attribute 'slow'

../../anaconda/envs/cython/lib/python3.6/site-packages/_pytest/config.py:1228: AttributeError
</details>

I am using MacOS with Conda virtual environment. I tried updating `pip` and `pytest`. I made sure I am calling the correct `pytest`. It is currently version `3.2.3`

Additionally to the error above, `pytest` does not accept extra arguments as the instructions suggest.

```
$ python -m pytest /Users/sasho.savkov/code/spaCy/ --vectors --models --slow
usage: pytest.py [options] [file_or_dir] [file_or_dir] [...]
pytest.py: error: unrecognized arguments: --vectors --models --slow
  inifile: None
  rootdir: /Users/sasho.savkov/code/spaCy
```

It looks like I have some wrong dependency, I don't know which one it is though.

**Comment by honnibal** [comment]
This means pytest isn't picking up the settings in the `conftest.py`. I normally run the tests from within the spaCy directory, with the current working dir on my pythonpath. I'm not 100% sure what's necessary --- pytest is mysterious to me :(

**Comment by savkov** [comment]
Apologies, I thought "the spaCy directory" means the project's directory, not the source directory. It all works when running in `<spacy_project_dir>/spacy/`.
