### ISSUE TITLE
One-off error with end index, when OP "*" ends the pattern

### ISSUE THREAD

**Issue by jofatmofn** [explosion/spaCy#1450]
#1148
* **Python version:** 2.7.12
* **Platform:** Linux-4.4.0-91-generic-x86_64-with-Ubuntu-16.04-xenial
* **spaCy version:** 2.0.0a17
* **Models:** en_core_web_sm-2.0.0a7

Tried the following code
```
import spacy
from spacy.matcher import Matcher
from spacy.attrs import *

def on_match_1(matcher, doc, id, matches):
        label, start, end = matches[id]
        print(label, start, end, doc[start:end])

nlp = spacy.load('en_core_web_sm')
matcher = Matcher(nlp.vocab)
matcher.add(
        "TSTEND",
        on_match_1,
        [
                {TAG: "JJ", LOWER: "new"},
                {TAG: "NN", 'OP': "*"}
        ]
)
document = nlp(u'Could you create a new ticket for me?')
matches = matcher(document)

```
and got the following output
`(8454456681159448349L, 4, 7, new ticket for)`

Expected value of end is 6.

**Comment by honnibal** [comment]
Sorry for closing the previous ticket prematurely, and thanks for following up.

The patch includes better tests. I doubt we've hit the last matcher bug, but it's definitely getting better. Please keep reporting :)
