### ISSUE TITLE
can we load spacy english model once in gearman worker init and can we return spacy object (parsed sentence) from gearman worker

### ISSUE THREAD

**Issue by prash1912** [explosion/spaCy#1455]
import gearman
import json
import spacy
import traceback
import dill
import cPickle

class SpacyWorker(object):

    def __init__(self):
        print "\n Loading spacy...."
        self.gearman_worker = gearman.GearmanWorker(["localhost:4730"])
        self.nlp = spacy.load('en')
        self.gearman_worker.register_task("spacy_worker", self.main)

    def main(self, job, gearman_job):
        try:
            flag = 1
            print "\n inside spacy worker"
            query = ""
            json_data = json.loads(gearman_job.data)
            query = json_data['query'].lower().strip()
            doc = self.nlp(query)
            data = {"spacy_obj" : doc}
            print "\n spacy object --------", json.dumps(data)    #raising an error doc object is not json serializable
        except Exception as e:
            flag = 0
            print "\n Error in getSpacyObj : ", e
        return json.dumps(data)

if __name__ == "__main__":
    print type(SpacyWorker())
    SpacyWorker().gearman_worker.work()

## Your Environment

* Operating System: ubuntu 16.04
* Python Version Used: 2.7.12
* spaCy Version Used:  1.8.1 , installed models (en_md, en )
* Environment Information:

**Comment by honnibal** [comment]
Overall this was a pretty big problem in v1, that we've fixed in v2.

v1 doesn't support the pickle protocol, and models take a while to load. This really makes parallelisation tricky. The v2 code for this is still fairly young, but there are no known bugs. You can try it at `pip install spacy-nightly`.

**Comment by honnibal** [comment]
v2 is now released, providing proper pickle support.
