### ISSUE TITLE
KeyError in customized NER for crime location tagging

### ISSUE THREAD

**Issue by prashant334** [explosion/spaCy#1459]
If you're looking for help with your code, consider posting a question on StackOverflow instead:
http://stackoverflow.com/questions/tagged/spacy
**Python version:** 2.7.6
* **Platform:** Linux-3.16.0-30-generic-x86_64-with-Ubuntu-14.04-trusty
* **spaCy version:** 2.0.0a17
* **Models:** en_core_web_sm, xx_ent_wiki_sm

**Comment by prashant334** [comment]
from __future__ import unicode_literals, print_function

import random
from pathlib import Path
import random

import spacy
from spacy.gold import GoldParse, minibatch
from spacy.pipeline import NeuralEntityRecognizer
from spacy.pipeline import TokenVectorEncoder


def get_gold_parses(tokenizer, train_data):
    '''Shuffle and create GoldParse objects'''
    random.shuffle(train_data)
    for raw_text, entity_offsets in train_data:
        doc = tokenizer(raw_text)
        gold = GoldParse(doc, entities=entity_offsets)
        yield doc, gold


def train_ner(nlp, train_data, output_dir):
    random.seed(0)
    optimizer = nlp.begin_training(lambda: [])
    nlp.meta['name'] = 'en_ent_animal'
    for itn in range(50):
        losses = {}
        for batch in minibatch(get_gold_parses(nlp.make_doc, train_data), size=3):
            docs, golds = zip(*batch)
            nlp.update(docs, golds, losses=losses, sgd=optimizer,
                       drop=0.35)
        print(losses)
    if not output_dir:
        return
    elif not output_dir.exists():
        output_dir.mkdir()
    nlp.to_disk(output_dir)


def main(model_name, output_directory=None):
    print("Creating initial model", model_name)
    nlp = spacy.blank(model_name)
    if output_directory is not None:
        output_directory = Path(output_directory)

    train_data = [
        (
            "Two persons who stole two luxury buses, worth about Rs 2 crore, in Haryana's Sohna and Mewat were arrested by the Crime Branch, police said on Friday.",
            [(67, 92, 'CRIME LOCATION')]
        ),
        (
            "Two days after a 16-year-old girl was found dumped in an empty well after allegedly being raped and shot at in Greater Noida, three men were detained on Monday for their suspected role in the crime.",
            [(111, 124, 'CRIME LOCATION')]
        ),
        (
            "Gang of Human Traffickers Busted, 3 Held in Muzaffarnagar",
            [(44, 57, 'CRIME LOCATION')]
        ),
        (
            "Amrik Singh Bal was allegedly attacked on Saturday morning in California's Fresno area, a report in the Fresno Bee said.",
            [(62, 86, 'CRIME LOCATION')]
        ),
        (
            "Two persons, including a senior citizen, were allegedly shot at before being robbed of cash in two separate incidents which took place within two hours in northeast Delhi on Monday.",
            [(155, 170, 'CRIME LOCATION')]
        ),
        (
            "Ankit Jha was working as a quality engineer with Reliance Telecom. His body was found on Monday morning with his throat slit in Vaishali district, 60 km from capital Patna. ",
            [(128, 145, 'CRIME LOCATION')]
        ),
        (
            "Woman Allegedly Raped, Filmed At Infosys Campus In Pune",
            [(33, 55, 'CRIME LOCATION')]
        ),
        (
            "A 68-year-old Sikh man was stabbed to death in California's Fresno city on January 1, prompting police to launch a hate crime probe into the city's first homicide.",
            [(47, 71, 'CRIME LOCATION')]
        ),
        (
            "The doctors took the girl into confidence and probed further when it was revealed that she was allegedly raped by a 23-year-old Mehboob Sayeed, who used to target her at the Indira Nagar footpath, police said.",
            [(174, 195, 'CRIME LOCATION')]
        ),
        (
            "2 Arrested For Stealing Luxury Buses In Haryana",
            [(40, 47, 'CRIME LOCATION')]
        ),
            (
            "A Delhi Police sub-inspector allegedly shot dead a 28-year-old woman and then shot himself at a park in southwest Delhi's Dwarka this morning.",
            [(104, 128, 'CRIME LOCATION')]
        ),
        (
            "Mr Dey, a veteran crime reporter, was shot dead in suburban Powai by motor-cycle borne shooters on June 11, 2011 allegedly at the behest of Rajan.",
            [(60, 65, 'CRIME LOCATION')]
        ),
        (
            "A man was arrested for allegedly stealing confidential information of a UK-based client from a company where he was earlier employed, Bidhannagar Police said today.",
            [(134, 145, 'CRIME LOCATION')]
        ),
        (
            "Elderly Man, Daughter Found Dead In Delhi's Sarai Rohilla Area",
            [(36, 62, 'CRIME LOCATION')]
        ),
        (
            "A minor girl from Nalanda has said in her police complaint that she was raped by the MLA at his house in the presence of a woman who had also forced her to have liquor.",
            [(18, 25, 'CRIME LOCATION')]
        ),
        (
            "A class 12 student, who had gone missing a few days ago in Lucknow, was found dead on Monday about half a kilometre from Chief Minister Akhilesh Yadav's residence.",
            [(59, 66, 'CRIME LOCATION')]
        ),
        (
            "A woman was allegedly gang-raped by four men inside a moving car on Friday night in east Delhi's Anand Vihar.",
            [(85, 105, 'CRIME LOCATION')]
        ),
        (
            "Authorities in Los Angeles have filed hate crime charges against a man who brutally assaulted a Sikh bus driver and called him a terrorist and suicide bomber during the attack last November",
            [(15, 26, 'CRIME LOCATION')]
        ),
        (
            "Maharashtra police have arrested four people for hijacking a luxury bus travelling from Pune to Indore.",
            [(88, 92, 'CRIME LOCATION')]
        ),
        (
            "With the arrest of three robbers, who allegedly used to commit the crime in posh areas in the national capital, the Delhi police has solved five cases of burglary.",
            [(90, 110, 'CRIME LOCATION')]
        ),
        (
            "Veteran actor Mukesh Rawal, known for his role of 'Vibhishan' in serial 'Ramayana', was found dead on railway tracks in Mumbai suburb Kandivali, railway police said today.",
            [(120, 143, 'CRIME LOCATION')]
        ),
        (
            "Rs 1.11 Crore-Worth Defunct Notes Seized From Property Broker In Pune",
            [(65, 69, 'CRIME LOCATION')]
        ),
        (
            "A 37-year-old man, who cheated a woman by marrying her and taking lakhs of rupees from her after claiming to be a software professional was arrested today, Cyberabad police said.",
            [(156, 165, 'CRIME LOCATION')]
        ),
        (
            "A 28-year-old Sanskrit lecturer was brutally killed, allegedly by his younger brother in north Delhi's Burari area after a heated argument, police said today.",
            [(89, 114, 'CRIME LOCATION')]
        ),
        (
            "Delhi Police is in touch with a US woman who was allegedly raped by a group of men at a five-star hotel in Delhi in April and she may come to India to join the probe.",
            [(107, 112, 'CRIME LOCATION')]
        ),
        (
            "Guard Hacked To Death In Attempted Loot At ATM In Patna.",
            [(50, 55, 'CRIME LOCATION')]
        ),
        (
            "A plumber who allegedly kidnapped a 16-year-old girl, promising to marry her has been arrested by the crime branch from Noida in Uttar Pradesh, police said.",
            [(120, 125, 'CRIME LOCATION')]
        ),
        (
            "Goa police on Saturday arrested three persons hailing from Uttar Pradesh who allegedly installed card-reading devices in point of sale (POS) machines at Calangute beach village.",
            [(153, 176, 'CRIME LOCATION')]
        ),
        (
            "Police said that the woman's husband, Afzal Ansari, and his friends raped her at gun point at Rahaiya village in Palamau district.",
            [(94, 129, 'CRIME LOCATION')]
        )
    ]
    #nlp.pipeline.append(TokenVectorEncoder(nlp.vocab))
    #nlp.pipeline.append(NeuralEntityRecognizer(nlp.vocab))
    nlp.add_pipe(NeuralEntityRecognizer(nlp.vocab))
    nlp.pipeline[nlp.pipe_names.index('ner')][1].add_label('POLICE')
    #nlp.pipeline[-1].add_label('POLICE')
    #nlp.pipeline[nlp.pipe_names.index('ner')][1].add_label('POLICE')
    #ner = NeuralEntityRecognizer(nlp.vocab)
    #ner.add_label('POLICE')
    #nlp.add_pipe(ner)
    train_ner(nlp, train_data, output_directory)

    # Test that the entity is recognized
    text = 'Man Stabbed To Death In Delhi; Whole Family Owns Up To Crime'
    print("Man Stabbed To Death In Delhi; Whole Family Owns Up To Crime':")
    doc = nlp(text)
    for ent in doc.ents:
        print(ent.label_, ent.text)
    if output_directory:
        print("Loading from", output_directory)
        nlp2 = spacy.load(output_directory)
        doc2 = nlp2('Do you like horses?')
        for ent in doc2.ents:
            print(ent.label_, ent.text)


main('en')


Errors:
Traceback (most recent call last):
  File "/home/student/PycharmProjects/nlp/crime_location.py", line 189, in <module>
    main('en')
  File "/home/student/PycharmProjects/nlp/crime_location.py", line 173, in main
    train_ner(nlp, train_data, output_directory)
  File "/home/student/PycharmProjects/nlp/crime_location.py", line 31, in train_ner
    drop=0.35)
  File "/usr/local/lib/python2.7/dist-packages/spacy/language.py", line 350, in update
    proc.update(docs, golds, drop=drop, sgd=get_grads, losses=losses)
  File "nn_parser.pyx", line 566, in spacy.syntax.nn_parser.Parser.update
  File "nn_parser.pyx", line 678, in spacy.syntax.nn_parser.Parser._init_gold_batch
  File "ner.pyx", line 125, in spacy.syntax.ner.BiluoPushDown.preprocess_gold
  File "ner.pyx", line 184, in spacy.syntax.ner.BiluoPushDown.lookup_transition
KeyError: u'B-CRIME LOCATION'

**Comment by ines** [comment]
Just had a quick look at your example and the main error is a `KeyError` – it looks like you haven't actually added the `CRIME LOCATION` label to the entity recognizer, and only the label `POLICE`. So spaCy doesn't know what to do with `CRIME LOCATION`.

See the [updated `train_new_entity_type.py` example](https://github.com/explosion/spaCy/blob/develop/examples/training/train_new_entity_type.py) for a slightly cleaner way of adding the entity recognizer to the pipeline, and add the correct label. I'd also recommend not using whitespace in your entity labels, because this might cause problems later on. So `CRIME LOCATION` &rarr; `CRIME_LOCATION`.

```python
ner = NeuralEntityRecognizer(nlp.vocab)
ner.add_label('CRIME_LOCATION')
nlp.add_pipe(ner)
```

I hope this helps!

**Comment by ines** [comment]
Quick update: I spent the past few days going over all examples, cleaning them up and adding more documentation. Here's the new training examples directory: 
https://github.com/explosion/spaCy/tree/develop/examples/training

Note that the current state **only works with the spaCy version on `develop`** – which will be released as soon as the new models are done training. The new docs are already in the `website` directory on `develop`, but not live yet, since we want to push the new version first.

I hope my suggestion above fixed your problem. If not, feel free to reopen!

**Comment by prashant334** [comment]
okay.
Thanks a lot.
