### ISSUE TITLE
sentence tokenization error

### ISSUE THREAD

**Issue by SK-EI** [explosion/spaCy#1469]
I am using the model "en_core_web_md". I have the following sentence, which gets broken up into two sentences by the parser. 

"For specific advice on goals and management, see published guidelines, such as those of the National High Blood Pressure Education Program’s Joint National Committee on Prevention, Detection, Evaluation, and Treatment of High Blood Pressure (JNC)."

The first sentence is "For specific advice on goals and management, see published guidelines, such as those of the"
The second sentence is "National High Blood Pressure Education Program’s Joint National Committee on Prevention, Detection, Evaluation, and Treatment of High Blood Pressure (JNC)."

I tried using lower case, which does not break up the sentence. However, this is not a good solution for me, because the lower-cased input does not yield the right noun-chunks that I require later on.
 
Please note that this error in splitting the sentence happened when the sentence was in a paragraph. The other sentences in the paragraph were identified correctly. The complete paragraph was:
"Control of high blood pressure should be part of comprehensive cardiovascular risk management, including, as appropriate, lipid control, diabetes management, antithrombotic therapy, smoking cessation, exercise, and limited sodium intake. Many patients will require more than 1 drug to achieve blood pressure goals. For specific advice on goals and management, see published guidelines, such as those of the National High Blood Pressure Education Program’s Joint National Committee on Prevention, Detection, Evaluation, and Treatment of High Blood Pressure (JNC)."

Environment Info:
* **Platform:** Linux-4.10.0-37-generic-x86_64-with-Ubuntu-16.04-xenial
* **Installed models:** en_vectors_glove_md, en, en_core_web_md
* **Python version:** 3.5.2
* **spaCy version:** 1.9.0

**Comment by SK-EI** [comment]
Please note that this error in splitting the sentence happened when the sentence was in a paragraph. The other sentences in the paragraph were identified correctly.

**Comment by honnibal** [comment]
Now correct in v2: https://demos.explosion.ai/displacy/?text=For%20specific%20advice%20on%20goals%20and%20management%2C%20see%20published%20guidelines%2C%20such%20as%20those%20of%20the%20National%20High%20Blood%20Pressure%20Education%20Program%E2%80%99s%20Joint%20National%20Committee%20on%20Prevention%2C%20Detection%2C%20Evaluation%2C%20and%20Treatment%20of%20High%20Blood%20Pressure%20(JNC).&model=en_core_web_sm&cpu=1&cph=1

spaCy 2 now also allows finer-grained control of the sentence boundary detection, by allowing you to set `token.is_sent_start` to a value in `(True, False, None)`. Values of `True` or `False` will be respected by the parser. You may want to add a pipeline component to set these values using custom logic. You can do that by calling `nlp.add_pipe(my_custom_sentence_logic, before='parser')`
