### ISSUE TITLE
does spacy supports python 2.6 on rhel 6.9 

### ISSUE THREAD

**Issue by tiru1930** [explosion/spaCy#1470]
I am trying to install spacy 1.7.0 on rhel 6.9 which has python 2.6 , i cant upgrade  python and also i need install with out internet  so i am doing it from source installation. facing lot if issue, like counter etc which i am able to fix, but 
errors like below not able fix 
    TOKEN_MATCH = re.compile('|'.join('(?:{})'.format(m) for m in REGULAR_EXP), re.IGNORECASE).match
ValueError: zero length field name in format

some times it is giving 
 from . import en
ImportError: cannot import name en

each time different issue i am seeing when i am trying to python setup install then import spacy

## Your Environment

* Operating System: 
* Python Version Used: 
* spaCy Version Used: 
* Environment Information:

**Comment by honnibal** [comment]
We haven't had tests running for Python 2.6 for some time --- so I'm not sure what should work there and what shouldn't.

Can't you do source installation of another Python version, and then install spaCy with that?

**Comment by honnibal** [comment]
This is an old script I used when I had a user account on a university server, and couldn't update system Python:

```
HERE=`pwd`
cd /tmp
wget http://www.python.org/ftp/python/2.7.5/Python-2.7.5.tgz /tmp
tar -zxvf Python-2.7.5.tgz
cd Python-2.7.5
mkdir $HERE/.python
./configure --prefix=$HERE/.python
make
make install
cd /tmp
wget --no-check-certificate https://pypi.python.org/packages/source/v/virtualenv/virtualenv-1.11.6.tar.gz
tar -zxvf virtualenv-1.11.6.tar.gz
cd virtualenv-1.11.6/
$HERE/.python/bin/python setup.py install
cd $HERE
$HERE/.python/bin/python /tmp/virtualenv-1.11.6/virtualenv.py .env -p $HERE/.python/bin/python2.7
```

**Comment by tiru1930** [comment]
Some i am able to install,in python 2.6 but got few errors which i have
fixed  with my use case
example format where in python 2.6 we need specify positional indexes

**Comment by honnibal** [comment]
I think you'll be best off upgrading Python --- 2.6 is very old, so all the rest of your libraries will have problems too.

Good luck!
