### ISSUE TITLE
Loading a trained NER model with spaCy 1.9

### ISSUE THREAD

**Issue by KMohaghegh** [explosion/spaCy#1472]
I trained my NER in spaCy 1.9 by 

gold = GoldParse(doc1, entities=[u'O', u'O', u'O',u'U-MVE', u'U-MVE', u'U-MVE',...])

for large doc1 file with almost 2500 sentences where just add one entity called "nlp.entity.add_label('MVE')" to the model. I check the entities afterwards with:
nlp.entity.update(doc1, gold)
nlp.entity(doc1)
for ent in doc1.ents:
    print(ent.text,  ent.label_)
and everything is fine and  around 1000 MVE in the model plus the existing one from spacy itself, 
a part of the output is like:

(u'corporate property vehicles', u'MWE')
(u'direct property investments', u'MWE')
(u'2002', u'DATE')
(u'Europe', u'LOC')
(u'5 percent', u'PERCENT')
(u'high yielding asset', u'MWE')
(u'powerful driver', u'MWE')
(u'very low', u'MWE')
(u'interest rate environment', u'MWE')

THAN I SAVE THE MODEL BY: nlp.save_to_directory('/Users/kasra/Desktop/Spacy/final_model')
When I load it, it does not recognise the entity which I trained for (even with the same training data only the spaCy entity trained was found not the one I add). The code for loading is bellow:
nlp = spacy.load('en', parser=False, entity=False, add_vectors=False)
vocab_dir = pathlib.Path('/Users/kasra/Desktop/Spacy/final_model/vocab')
with (vocab_dir / 'strings.json').open('r', encoding='utf8') as file_:
    nlp.vocab.strings.load(file_)
nlp.vocab.load_lexemes(vocab_dir / 'lexemes.bin')
ner = EntityRecognizer.load(pathlib.Path("/Users/kasra/Desktop/Spacy/final_model/ner"), nlp.vocab, require=True)
textnew = ('some text')
doc57 = nlp(unicode(textnew))
print doc57
print nlp.tagger(doc57)
print ner(doc57)
ner(doc57)
for ent in doc57.ents:
   print(ent.text,  ent.label_)

here no error but only the spaCy entities like 'DATE' and 'LOC' ... are found nothing from the 'MVE'! which I trained for.
## Your Environment

* Operating System: Mac sierra
* Python Version Used: 2.7.13
* spaCy Version Used: 1.9
* Environment Information:

**Comment by honnibal** [comment]
Please see here --- the training is much improved in v2, and we've tried to give a lot more guidance about how to make good use of it: https://spacy.io/usage/training
