### ISSUE TITLE
[Feature Request] Adding 'AND' and 'OR' type pattern matching operations.

### ISSUE THREAD

**Issue by Navdevl** [explosion/spaCy#1484]
Given the following sentences:
**Find me 5 houses of 1000 sqft**
**Find me 3 something of 1000 square ft**
**Find me 4 grounds of 1000 sq ft**
**Find me 8 places of 1000 square feet**

I was trying to extract the value of number of entity, which on the above examples is 5, 3, 4, 8 respectively. 

My current situation is to capture the numbered value except the numbered value that is suffixed with sqft, sq ft, square ft, and square feet.

I was trying this below code., but it is also capturing the sqft values too. I guess it would be helpful if there is a way to LOGICAL ADD OR the patterns. 

`
import spacy
from  spacy.attrs import *
from spacy.matcher import Matcher

nlp = spacy.load("en")
doc = nlp(u"Find me 5 houses of 1000 sqft")

pattern =[
          {"IS_DIGIT": True },
          {"LOWER": [ "sq", "sqft" ], "OP": "!"},
          {"LOWER": "sqft", "OP": "!"},
          {"LOWER": "square", "OP": "!"}
        ]
matcher = Matcher(nlp.vocab)
matcher.add_pattern("count", pattern)
matcher(doc)
`

## Info about spaCy

* **Python version:** 2.7.10
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **spaCy version:** 1.9.0
* **Installed models:** en
* **Operating System: Mac

**Comment by ines** [comment]
Thanks – that's a good point! The matcher operators are already quite tricky, so adding additional logical operators might not be so easy. A better and probably more elegant solution would be to define your own custom flag, and then write a match pattern that matches against your custom flag. This would also let you avoid operators all together:

```python
# add a custom flag that returns True if token text matches the suffix (returns an ID)
IS_SQFT = nlp.vocab.add_flag(lambda text: text in ['sqft', 'sq'])

# only match patterns of digit plus non-sqft – make sure to use the ID as the key, not the string!
pattern =[{'IS_DIGIT': True }, {IS_SQFT: False}]
```

Of course, this doesn't work if the suffix consists of multiple tokens, e.g. "square foot". In this case, you'd have to match those first and merge the `Span`s into one token. You can then also have your flag check for `'square ft'`.

Something like this could also be a good example to add to the docs – will work on that! 😊

P.S.: If you haven't already, also check out v2.0 and the new [custom pipeline components](https://alpha.spacy.io/usage/processing-pipelines#custom-components) ([blog post here](https://explosion.ai/blog/spacy-v2-pipelines-extensions)). Depending on what else you need to do, you could wrap all of the above logic in its own pipeline component, which is applied automatically when you call `nlp` on your text. Your use case is actually very similar to the emoji example I've used in the blog post and in [`spacymoji`](https://github.com/ines/spacymoji). For example, you can now do stuff like:

```python
# set custom extension my_number on the token, so you can write to token._.my_number
Token.set_extension('my_number', default=False)

def match_stuff(doc):
     # match or extract stuff and set token._.my_number = True if needed
    return doc

# add custom component last in the pipeline
nlp.add_pipe(match_stuff, last=True)
```

Now, when you call `nlp("some text")`, the `match_stuff` function is applied after all other components and the `Doc` object you get back has your custom attribute `._.my_number` set on its tokens.
