### ISSUE TITLE
WHAT EXCATLY LAMBDA DOES IN " get_gold_tuples = lambda: [] "

### ISSUE THREAD

**Issue by prashant334** [explosion/spaCy#1489]
* **Python version:** 2.7.6
* **Platform:** Linux-3.16.0-77-generic-x86_64-with-Ubuntu-14.04-trusty
* **spaCy version:** 2.0.0a17
* **Models:** en, en_core_web_sm, xx_ent_wiki_sm
I AM NOT GETTING WHAT  IS THE CONTENT OF LAMBDA? @ines 

   if get_gold_tuples is None:
get_gold_tuples = lambda: []

**Comment by ines** [comment]
See #1482.
