### ISSUE TITLE
How weights and bias are getting learned for customized NER.? 

### ISSUE THREAD

**Issue by prashant334** [explosion/spaCy#1495]
Python version: 2.7.6

Platform: Linux-3.16.0-77-generic-x86_64-with-Ubuntu-14.04-trusty

spaCy version: 2.0.0a17

Models: en, en_core_web_sm, xx_ent_wiki_sm

hi @honnibal ,@ines 

   I have gone through "https://alpha.spacy.io/usage/training#ner" for "Training an additional entity type"  . But I didn't get enough insight to get information about how neural network is exactly getting trained  from training data . What kind of neural network is actually used and how weight and biases are updated. 

Thanks

**Comment by ines** [comment]
Hi, here are some links that should be helpful:

* [Details of the neural network model architecture](https://alpha.spacy.io/api/#nn-model) (spaCy docs)
* The implementation at [`spacy/syntax/nn_parser.pyx`](https://github.com/explosion/spaCy/blob/develop/spacy/syntax/nn_parser.pyx)
* [Thinc](https://github.com/explosion/thinc), spaCy's machine learning library used for implementing the models

We also just published the slides of a talk Matt gave the other day, titled ["Practical and Effective Neural Entity Recognition in spaCy v2.0 and beyond"](https://github.com/explosion/talks/blob/master/2017-11-02___Practical-and-Effective-Neural-NER.pdf), which goes into some more details on how the NER model works in v2.0 (hopefully, there'll also be a video soon).
