### ISSUE TITLE
Backward compatibility - stop_words between v1.9 and v2.0

### ISSUE THREAD

**Issue by RushiLuhar** [explosion/spaCy#1512]
Minor backward compatibility issue. In spacy v1.9, the list of english stop words (set STOP_WORDS) was in spacy.en.word_sets. In spacy v2.0, the stop words have moved to spacy.lang.en.stop_words. 
The move from spacy.en to spacy.lang.en has been mentioned in documents already, so this is a very minor issue.

## Info about spaCy
* **spaCy version:** 2.0.1
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **Python version:** 3.6.2
* **Models:** en, en_core_web_lg

**Comment by ines** [comment]
Thanks – I think we forgot about that one. Will include this, just in case users were importing this file directly etc. 👍
