### ISSUE TITLE
Is this train count correct?

### ISSUE THREAD

**Issue by trivedigaurav** [explosion/spaCy#1515]
n_train = 2000 but len(train_texts) = 1600. This print statements seems to be in-accurate:

https://github.com/explosion/spaCy/blob/be276bbd670659956a482d2dcd39cea99fd44d2e/examples/training/train_textcat.py#L51-L52

**Comment by ines** [comment]
Thanks! You're right, this should print `len(train_texts)`, not `n_texts`, which is the total texts loaded from the dataset, including the evaluation examples. This might actually be nice to add as well, just to make it clear what's going on here.

Fixing!
