### ISSUE TITLE
'spacy.vocab.Vocab' object has no attribute 'clear_vectors'

### ISSUE THREAD

**Issue by danielhers** [explosion/spaCy#1516]
Steps leading to the issue:

    python -m spacy download en_core_web_md

And then in Python:

    >>> import spacy
    >>> nlp = spacy.load("en_core_web_md")
    >>> nlp.vocab.clear_vectors()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: 'spacy.vocab.Vocab' object has no attribute 'clear_vectors'

## Info about spaCy

* **spaCy version:** 2.0.1
* **Platform:** Linux-4.8.4-aufs-1-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.3
* **Models:** en_core_web_md, en_core_web_lg, en, de_core_news_sm, fr_core_news_md, fr_core_news_sm

**Comment by honnibal** [comment]
Thanks! We renamed this to `.reset_vectors()`, which I see hasn't been updated in the docs and examples yet.

```python

    def reset_vectors(self, *, width=None, shape=None):
        """Drop the current vector table. Because all vectors must be the same
        width, you have to call this to change the size of the vectors.
        """
        if width is not None and shape is not None:
            raise ValueError("Only one of width and shape can be specified")
        elif shape is not None:
            self.vectors = Vectors(shape=shape)
        else:
            width = width if width is not None else self.vectors.data.shape[1]
            self.vectors = Vectors(shape=(self.vectors.shape[0], width))
```

**Comment by ines** [comment]
Fixed! https://spacy.io/api/vocab#reset_vectors

**Comment by danielhers** [comment]
Nice, thanks!
