### ISSUE TITLE
nlp.vocab.vectors.resize gives 'numpy.uint64' object is not iterable

### ISSUE THREAD

**Issue by danielhers** [explosion/spaCy#1518]
Steps to reproduce:

    >>> import spacy
    >>> nlp = spacy.load("en_core_web_md")
    >>> nlp.vocab.vectors.resize((100,80))
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "vectors.pyx", line 153, in spacy.vectors.Vectors.resize
    TypeError: 'numpy.uint64' object is not iterable

## Info about spaCy

* **spaCy version:** 2.0.1
* **Platform:** Linux-4.10.0-38-generic-x86_64-with-Ubuntu-17.04-zesty
* **Python version:** 3.5.3
* **Models:** en, en_core_web_md

**Comment by honnibal** [comment]
Thanks! Tested and fixed.

**Comment by danielhers** [comment]
Thanks! And even a release so I can use it already! Amazing.

**Comment by danielhers** [comment]
@honnibal Spoke too soon :(
Running the same example in 2.0.2 now gives

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "vectors.pyx", line 153, in spacy.vectors.Vectors.resize
    RuntimeError: dictionary changed size during iteration

**Comment by danielhers** [comment]
Opened new issue #1539
