### ISSUE TITLE
`spacy download es` does not find default spanish model

### ISSUE THREAD

**Issue by bdewilde** [explosion/spaCy#1522]
Running the `spacy download es` command fails with

```
Compatibility error
No compatible model found for 'es_core_web_sm' (spaCy v2.0.2).
```

The docs claim that `es_core_news_sm` is the default spacy v2.0 model, so this was a surprise. I _can_ install that specifically, then follow it up with `spacy link es_core_news_sm es`, so this isn't a blocker or anything. Other languages (en, de) download and link the default models, as expected.

## Your Environment

* **spaCy version:** 2.0.2
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **Python version:** 3.6.0
* **Models:** de, de_core_news_sm, en, en_core_web_md, en_core_web_sm, en_md, xx, xx_ent_wiki_sm

**Comment by ines** [comment]
Thanks! Just checked and turns out there was a [typo in the model shortcuts](https://github.com/explosion/spacy-models/blob/f7e6e24eef8c816501d553816501558a529a59a2/shortcuts-v2.json#L4) – just fixed that, so it should all work fine in a few minutes 😊
