### ISSUE TITLE
how to use chinese model

### ISSUE THREAD

**Issue by xiaochen-liu** [explosion/spaCy#1523]
i see the spacy have support chinese by using jieba . but when i try it , it can not work spacy 2.0.0

1. download the jieba:
  pip install jieba

2 make the shorcur to zh：
 python -m spacy link jieba zh

3. the test code:
import spacy;
from spacy import displacy
nlp = spacy.load('zh')
test_doc = nlp("测试一下分词")
print(test_doc)
#displacy.serve(doc, style='dep')
displacy.serve(doc, style='ent')

4. run the test, get the error:
(mm-env) matterbot@SZX1000338325:~/bot/spacy-test$ python test_zh.py
Traceback (most recent call last):
  File "test_zh.py", line 5, in <module>
    nlp = spacy.load('zh')
  File "/home/matterbot/mm-env/lib/python3.6/site-packages/spacy/__init__.py", line 19, in load
    return util.load_model(name, **overrides)
  File "/home/matterbot/mm-env/lib/python3.6/site-packages/spacy/util.py", line 111, in load_model
    return load_model_from_link(name, **overrides)
  File "/home/matterbot/mm-env/lib/python3.6/site-packages/spacy/util.py", line 125, in load_model_from_link
    cls = import_file(name, path)
  File "/home/matterbot/mm-env/lib/python3.6/site-packages/spacy/compat.py", line 119, in import_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/matterbot/mm-env/lib/python3.6/site-packages/spacy/data/zh/__init__.py", line 15, in <module>
    from ._compat import *
ModuleNotFoundError: No module named 'zh'

i have try the en model, it works. how can i use chinese?

If you're looking for help with your code, consider posting a question on StackOverflow instead:
http://stackoverflow.com/questions/tagged/spacy -->

## Your Environment

    spaCy version      2.0.1
    Location           /home/matterbot/mm-env/lib/python3.6/site-packages/spacy
    Platform           Linux-4.2.0-27-generic-x86_64-with-debian-jessie-sid
    Python version     3.6.3
    Models             spacy.en, en_default, en_lg, en, zh

**Comment by ines** [comment]
Hi! There's currently no Chinese model – spaCy only supports tokenization, which uses the `jieba` library. See this page for an overview of the supported models, and supported tokenization: https://spacy.io/usage/models#languages

So in your example, you've actually linked the jieba library to a model shortcut, which won't work – spaCy models need to be binary model data packages you've downloaded (for example, `en_core_web_sm`).

If you just want to use Chinese **tokenization**, all you need to do is install `jieba` (which you've already done) and then use the language class directly:

```python
from spacy.lang.zh import Chinese

nlp = Chinese()
doc = nlp(u"蘋果公司正考量用一億元買下英國的新創公司")
```

We're hoping to train a Chinese model in the future! Once there's a model, you'll also be able to use spaCy for Chinese part-of-speech tags, dependencies, named entities and semantic similarity. It'll also do statistical segmentation based on the dependency parse – a little like how the noun chunks are calculated in the English model.
