### ISSUE TITLE
doc.to_array / doc.from_array has unexpected behaviour

### ISSUE THREAD

**Issue by davidgengenbach** [explosion/spaCy#1527]
The `doc_array = doc.to_array(ATTRS)` and `doc2.from_array(ATTRS, doc_array)` approach seems to have an unexpected behaviour. When using the [minimal example from the documentation](https://spacy.io/api/doc#from_array), the assertion fails:
```python
from spacy.attrs import LOWER, POS, ENT_TYPE, IS_ALPHA
from spacy.tokens import Doc

text = 'Some text'
doc = nlp(text)
np_array = doc.to_array([LOWER, POS, ENT_TYPE, IS_ALPHA])
doc2 = Doc(doc.vocab)
doc2.from_array([LOWER, POS, ENT_TYPE, IS_ALPHA], np_array)
assert doc.text == doc2.text
```

````
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-64-d4788c82115f> in <module>()
      7 doc2 = Doc(doc.vocab)
      8 doc2.from_array([LOWER, POS, ENT_TYPE, IS_ALPHA], np_array)
----> 9 assert doc.text == doc2.text

AssertionError: 
````

## Your Environment

* **spaCy version:** 2.0.2
* **Platform:** Darwin-17.0.0-x86_64-i386-64bit (macOS 10.13)
* **Python version:** 3.6.2
* **Models:** en

**Comment by honnibal** [comment]
@davidgengenbach Thanks, this is a problem with the example. We need to specify `ORTH` in the exported array for that to work. Otherwise we won't have the original text content.

**Comment by davidgengenbach** [comment]
@honnibal Thanks a lot for answering! Unfortunately adding the `ORTH` attribute also does not seem work. I added all other attributes as well, but its still not working. [Here is a minimal example](https://gist.github.com/davidgengenbach/01ba876c2892d8894ad27f21625e06a8).

**Comment by ines** [comment]
Just updated the example to make it work. Here, we're passing in the initial `Doc`'s tokens as the `words` keyword argument on the new `Doc`. To make sure the attributes are set, we just check for the part-of-speech tag instead:

```python
from spacy.attrs import LOWER, POS, ENT_TYPE, IS_ALPHA
from spacy.tokens import Doc

doc = nlp("Hello world!")
np_array = doc.to_array([LOWER, POS, ENT_TYPE, IS_ALPHA])
doc2 = Doc(doc.vocab, words=[t.text for t in doc])
doc2.from_array([LOWER, POS, ENT_TYPE, IS_ALPHA], np_array)
assert doc[0].pos_ == doc2[0].pos_
```

I can confirm that just adding `ORTH` didn't work – not sure if it's supposed to, though? (@honnibal)
