### ISSUE TITLE
Space-sensitive tokenisation

### ISSUE THREAD

**Issue by MashaNaslidnyk** [explosion/spaCy#1528]
If input sentence contains a double space, spacy linguistic feature extractor treats one of the spaces as a token. Reporting in case this is not expected behaviour.

>>> import spacy
>>> nlp = spacy.load('en')
>>> doc = nlp(u'The cat  sat on the mat')
>>> for token in doc:
...     print(token.text, token.lemma_, token.pos_, token.tag_, token.dep_,
...           token.shape_, token.is_alpha, token.is_stop)
... 
(u'The', u'the', u'DET', u'DT', u'det', u'Xxx', True, True)
(u'cat', u'cat', u'NOUN', u'NN', u'nsubj', u'xxx', True, False)
(u' ', u' ', u'SPACE', u'SP', u'', u' ', False, False)
(u'sat', u'sit', u'VERB', u'VBD', u'ROOT', u'xxx', True, False)
(u'on', u'on', u'ADP', u'IN', u'prep', u'xx', True, True)
(u'the', u'the', u'DET', u'DT', u'det', u'xxx', True, True)
(u'mat', u'mat', u'NOUN', u'NN', u'pobj', u'xxx', True, False)

## Your Environment
* **Python version:** 2.7.13
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **spaCy version:** 1.7.3
* **Installed models:** en

**Comment by ines** [comment]
Thanks for the report – this is in fact expected behaviour. See #1370:

> spaCy preserves all characters of the input in the `Doc` object. The original string is actually not stored anywhere. When you call `doc.text`, what you're getting is `[(w.text + w.whitespace_) for w in doc]`

> I often trim whitespace as a preprocess on the raw string, using a simple regex. If you know you don't want these characters, I would recommend that.
