### ISSUE TITLE
[Question] Understand customizing Tokenizer 

### ISSUE THREAD

**Issue by k0pernicus** [explosion/spaCy#1531]
Hello, this is just a question in order to understand the example below:

```
import regex as re
from spacy.tokenizer import Tokenizer

prefix_re = re.compile(r'''^[\[\("']''')
suffix_re = re.compile(r'''[\]\)"']$''')
infix_re = re.compile(r'''[-~]''')
simple_url_re = re.compile(r'''^https?://''')

def custom_tokenizer(nlp):
    return Tokenizer(nlp.vocab, prefix_search=prefix_re.search,
                                suffix_search=suffix_re.search,
                                infix_finditer=infix_re.finditer,
                                token_match=simple_url_re.match)

nlp = spacy.load('en')
nlp.tokenizer = custom_tokenizer(nlp)
```

Actually, there is no sentence example just in order to understand well the customization, and I really don't understand how useful this customization is :-(

I read carefuly the documentation, and I tried with a simple example.  
Imagine I want to tokenize my sentence with "bullet points" like (i), (ii) or (iii).

I wrote this code:
```
import spacy
import regex as re
from spacy.tokenizer import Tokenizer

# Check if an opened parenthesis
prefix_re = re.compile(r'''^\(''')
# Check if a closed parenthesis
suffix_re = re.compile(r'''\)$''')
# Match i, ii or iii
simple_re_matcher = re.compile(r'''(?:i|(?:ii)|(?:iii))''')

def custom_tokenizer(nlp):
    return Tokenizer(nlp.vocab, token_match=simple_re_matcher.match)

nlp = spacy.load('en')
nlp.tokenizer = custom_tokenizer(nlp)

doc = nlp(u'''This is a list: (i) First item, (ii) Second item, (iii) Third item, (iv) Fourth item''')

sentences = [sent.string.strip() for sent in doc.sents]
print(sentences)
```

The output is:
`['This is a list: (i) First item,', '(ii)', 'Second item,', '(iii)', 'Third item, (iv) Fourth item']`,
but I thought the output will be:
`['This is a list:','(i)','First item,', '(ii)', 'Second item,', '(iii)', 'Third item, (iv) Fourth item']`.

Is another example in the doc can be provided please, just to understand how works this customization via copy/pasting?

Thanks in advance

**Comment by siddsach** [comment]
@honnibal @ines any update on this?

**Comment by honnibal** [comment]
Well the tokenizer changes the tokens, not necessarily the sentences...So you should be checking the value of `list(doc)`. It could be that the tokenization is right -- it's hard to tell from your output. Of course, the regular expressions could also have a problem, I haven't checked.
