### ISSUE TITLE
Change window size of a NER model

### ISSUE THREAD

**Issue by damianoporta** [explosion/spaCy#1532]
Hello,
Can we change the window size during the training of a ner model? If i remember correctly spacy takes the previous 2 tokens and the next 2 tokens as context. I would try a bigger window. Is it possible somehow?

**Comment by honnibal** [comment]
There's two places you could change this. One is the window size in the entity recognizer's CNN: https://github.com/explosion/spaCy/blob/master/spacy/_ml.py#L242 . The default setting is depth 4, which means the token's vector is sensitive to information from 4 words on either side.

The other place to change this is in the extraction of state tokens. I'm preparing something that explains this part of the procedure better. Implementation: https://github.com/explosion/spaCy/blob/master/spacy/syntax/_state.pxd#L130

This is not a part of the implementation I'm proud of... The entity recognizer uses the "6' case. You'll need to change the `nr_features` constant in `EntityRecognizer` within `pipeline.pyx` if you add more features (yeah, I know...). The features themselves aren't that satisfying for the entity recognizer. It feels like we should be able to make better use of the entity history.

**Comment by damianoporta** [comment]
@honnibal thanks! can i change the tok2vec option through `begin_training()` ?

**Comment by ankit814** [comment]
Hi! @honnibal 
I want to train an NER on a window size of 8. But the change required in __state.pxd_ is not clear to me.
What should be the change in [https://github.com/explosion/spaCy/blob/master/spacy/syntax/_state.pxd#L130](url) for this window size?

Also, is it sufficient to change **4 to 8** here [https://github.com/explosion/spaCy/blob/master/spacy/_ml.py#L291](url)? {Replacing  `>> convolution ** 4, pad=4` with `>> convolution ** 8, pad=8`}
and **6 to 8** here [https://github.com/explosion/spaCy/blob/master/spacy/pipeline.pyx#L905](url) {Replacing `nr_feature = 6` with `nr_feature = 8`}?

Thanks!

**Comment by honnibal** [comment]
@ankit814 You should just change the 4 to 8 in `_ml.py`. Changing the `nr_feature` value does something fairly different --- it changes the features used in the parser or entity recognizer. I think the convolution depth is what you want here.

I would be surprised if setting the window size that high helps, though.
