### ISSUE TITLE
pip install of spacy 2.0 fails to build thinc

### ISSUE THREAD

**Issue by bstrand** [explosion/spaCy#1535]
pip install of spacy 2.0.2 into an Anaconda env fails on failure to build thinc. Conda env named 'spacy2' here, g++ fails with unrecognized cmd line option '-R':

>   g++ -pthread -shared -B /somepath/anaconda3/envs/spacy2/compiler_compat -L/somepath/anaconda3/envs/spacy2/lib -Wl,-rpath=/somepath/anaconda3/envs/spacy2/lib,--no-as-needed build/temp.linux-x86_64-3.6/thinc/neural/gpu_ops.o build/temp.linux-x86_64-3.6/include/_cuda_shim.o -L/usr/local/cuda/lib64 -L/somepath/anaconda3/envs/spacy2/lib -R/usr/local/cuda/lib64 -lcudart -lpython3.6m -o build/lib.linux-x86_64-3.6/thinc/neural/gpu_ops.cpython-36m-x86_64-linux-gnu.so
  g++: error: unrecognized command line option ‘-R’
  **error: command 'g++' failed with exit status 1**
>
>  ----------------------------------------
>  Failed building wheel for thinc

## Environment
* Operating System: Ubuntu 16.04.3 / Linux-4.4.0-1039-aws-x86_64-with-debian-stretch-sid
* Python Version Used: Anaconda 3.6.2
* spaCy Version Used: 2.0.2
* Environment Information: conda v4.3.30, pip v9.0.1

**Comment by bstrand** [comment]
Upgrading Anaconda resolved the thinc build failure, spacy 2.0.2 installs successfully.

Ref this similar issue, [cupy #599](https://github.com/cupy/cupy/issues/599). Suggestion therein is upgrading Anaconda Python from 3.6.2 to 3.6.3 is the resolution, but I did not isolate the upgrades to verify. Package update list below.

Perhaps worthy of a warning/note in install guide? 

>  anaconda:           5.0.0.1-py36hfb0b618_1 --> 5.0.1-py36hd30a520_1
    anaconda-navigator: 1.6.8-py36h672ccc7_0   --> 1.6.9-py36h11ddaaa_0
    bokeh:              0.12.7-py36h169c5fd_1  --> 0.12.10-py36hbb0e44a_0
    cairo:              1.14.10-h58b644b_4     --> 1.14.10-haa5651f_5
    dask:               0.15.2-py36h9b48dc4_0  --> 0.15.3-py36hdc2c8aa_0
    dask-core:          0.15.2-py36h0f988a8_0  --> 0.15.3-py36h10e6167_0
    distributed:        1.18.3-py36h73cd4ae_0  --> 1.19.1-py36h25f3894_0
    libgcc-ng:          7.2.0-hcbc56d2_1       --> 7.2.0-h7cc24e2_2
    libgfortran-ng:     7.2.0-h6fcbd8e_1       --> 7.2.0-h9f7466a_2
    libstdcxx-ng:       7.2.0-h24385c6_1       --> 7.2.0-h7a57d05_2
    libxcb:             1.12-he6ee5dd_2        --> 1.12-h84ff03f_3
    lxml:               3.8.0-py36h6c6e760_0   --> 4.1.0-py36h5b66e50_0
    lzo:                2.10-hc0eb8fc_0        --> 2.10-h1bfc0ba_1
    matplotlib:         2.0.2-py36h2acb4ad_1   --> 2.1.0-py36hba5de38_0
    networkx:           1.11-py36hfb3574a_0    --> 2.0-py36h7e96fb8_0
    numpy:              1.13.1-py36h5bc529a_2  --> 1.13.3-py36ha12f23b_0
    openssl:            1.0.2l-h9d1a558_3      --> 1.0.2l-h077ae2c_5
    pango:              1.40.11-hedb6d6b_0     --> 1.40.11-h8191d47_0
    pip:                9.0.1-py36h30f8307_2   --> 9.0.1-py36h8ec8b28_3
    pixman:             0.34.0-ha72d70b_1      --> 0.34.0-h83dc358_2
    psutil:             5.2.2-py36h74c8701_0   --> 5.4.0-py36h84c53db_0
    pyflakes:           1.5.0-py36h5510808_1   --> 1.6.0-py36h7bd6a15_0
    pylint:             1.7.2-py36h484ab97_0   --> 1.7.4-py36hb9d4533_0
    pytables:           3.4.2-py36hdce54c9_1   --> 3.4.2-py36h3b5282a_2
    python:             3.6.2-hdfe5801_15      --> 3.6.3-hc9025b9_1
    scikit-learn:       0.19.0-py36h97ac459_2  --> 0.19.1-py36h7aa7ec6_0
    six:                1.10.0-py36hcac75e4_1  --> 1.11.0-py36h372c433_1
    spyder:             3.2.3-py36he38cbf7_1   --> 3.2.4-py36hbe6152b_0
    xlsxwriter:         0.9.8-py36hf41c223_0   --> 1.0.2-py36h3de1aca_0
    zict:               0.1.2-py36ha0d441b_0   --> 0.1.3-py36h3a3bf81_0

**Comment by honnibal** [comment]
Thanks!

Btw if you're using conda, you'll probably want to do `conda install numpy` before doing `pip install spacy`. This will give you numpy linked against MKL, which is a fair bit faster on my machines.

We have Thinc up on conda now, but we've been waiting *days* for the conda-forge build system to put up spaCy, because Travis CI's OSX builds are down :(
