### ISSUE TITLE
Does Language.update() need more iterations with batch size > 1 ?

### ISSUE THREAD

**Issue by damianoporta** [explosion/spaCy#1538]
Hello,
maybe a dump question, but i am training a NER model with 10k labelled docs.
I am following the NER example:

```
    for itn in range(n_iter):
        random.shuffle(TRAIN_DATA)
        losses = {}

        for t, a in TRAIN_DATA:
            nlp_train.update(
                [t],  # batch of texts
                [a],  # batch of annotations
                drop=0.5,  # dropout - make it harder to memorise data
                sgd=optimizer,  # callable to update weights
                losses=losses) 
```
in this case we are updating the model by feeding one doc per time. I did a test passing a list of texts and annotations (100 docs each `update()`) and i noticed a huge performance decreasing if i compare the results with batch=100 and batch=1.

I was trying with bigger batch to speed up the training, it is faster but it has poor performance. 

The questions are:

1. Should i decrease the `drop` with bigger batch size?
2. Should i increase the number of iterations with bigger batch size?

Thanks!

**Comment by honnibal** [comment]
See here for my thoughts on these parameters: https://spacy.io/usage/training#tips

Ultimately the hyper-parameters are difficult to tune because they all interact in tricky ways.
