### ISSUE TITLE
nlp.vocab.vectors.resize: dictionary changed size during iteration

### ISSUE THREAD

**Issue by danielhers** [explosion/spaCy#1539]
Steps to reproduce:

    >>> import spacy
    >>> nlp = spacy.load("en_core_web_md")
    >>> nlp.vocab.vectors.resize((100,80))
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "vectors.pyx", line 153, in spacy.vectors.Vectors.resize
    RuntimeError: dictionary changed size during iteration

## Info about spaCy

* **spaCy version:** 2.0.2
* **Platform:** Linux-4.10.0-38-generic-x86_64-with-Ubuntu-17.04-zesty
* **Python version:** 3.5.3
* **Models:** en, en_core_web_md

**Comment by honnibal** [comment]
Fixed, thanks for the report!
