### ISSUE TITLE
Feature Request - Paragraph Vectors

### ISSUE THREAD

**Issue by AI-Guru** [explosion/spaCy#1540]
Namaste!

I really love spaCy! I am currently studying its features and I am amazed.

One feature request: Currently spaCy can generate word-vectors from sentences by averaging the word-vectors of the individual tokens. What about introducing paragraph vectors as in http://cs.stanford.edu/~quocle/paragraph_vector.pdf?

Best,
Tristan

**Comment by honnibal** [comment]
Thanks!

About doc2vec / paragraph2vec: I think we don't need to implement that, for a couple of reasons.

1. There's an implementation in Gensim of that algorithm that I have nothing to add to. You can use the Gensim version in spaCy by setting the vector hooks or similarity hooks.

2. That paper is fairly old now. It's one specific recipe for constructing a document vector. You can plug together NN components in all sorts of other ways. See https://explosion.ai/blog/deep-learning-formula-nlp

**Comment by AI-Guru** [comment]
Thanks! About embed, encode, attend, predict. The article great! It is now a year old! Does it still stand as it is, our are any revisions necessary?

**Comment by honnibal** [comment]
I think the points still stand. It's really about the information flow, so it hasn't gone out of date so quickly.
