### ISSUE TITLE
Minor documentation issue - Text classification link is broken in example

### ISSUE THREAD

**Issue by RushiLuhar** [explosion/spaCy#1541]
The link: https://spacy.io/usage/text-classification doesn't exist. It is referred to in the comment here: https://github.com/explosion/spacy/blob/master/examples/training/train_textcat.py

I am very excited about training and using the text categorization function as part of the pipeline. It would be awesome to have some more documentation.

**Comment by ines** [comment]
Oops, sorry – I think we moved things around and forgot to update this one. There will definitely be more text classification details in the future!
