### ISSUE TITLE
spacy.tokens.doc.Doc.ents.__get__  AssertionError

### ISSUE THREAD

**Issue by Manslow** [explosion/spaCy#1547]
Using Spacy 2.0, Python 3.6.3 on MacOS 10.11.6  I'm getting: 

> Traceback (most recent call last):
>   File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1599, in <module>
>     globals = debugger.run(setup['file'], None, None, is_module)
>   File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1026, in run
>     pydev_imports.execfile(file, globals, locals)  # execute the script
>   File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
>     exec(compile(contents+"\n", file, 'exec'), glob, loc)
>   File "myuserpath/tokenize.py", line 54, in <module>
>     pipeline_args=pipe_line_arguments))
>   File "myuserpath/text_processing_pipeline.py", line 385, in text_pipeline
>     doc = pipeline(doc, token_pipeline_funcs, nlp, pipeline_args)
>   File "myuserpath/text_processing_pipeline.py", line 409, in pipeline
>     doc = pipeline_function(doc, nlp, pipeline_args)
>   File "myuserpath/text_processing_pipeline.py", line 203, in chunk_named_entities
>     for ent in doc.ents:
>   File "doc.pyx", line 412, in spacy.tokens.doc.Doc.ents.__get__
> AssertionError

when merging entity spans after merging noun chunk spans but not vice versa. 

I have a list of texts I'm creating document objects from that are used for merging spans and it fails on the same text each time. However, when just trying it on that single text it works fine so I haven't been able to replicate a self contained example here. Also, this happens with small, medium and large Engish models but the error is raised on a different text input in the sequence by each model but the same one each time.

Finally if I look at the debugger in PyCharm to see what ents is assigned to when the assertion is thrown, it is a string with the traceback call pasted above.

**Comment by Manslow** [comment]
Ok I've managed to come up with a minimal example. The previous hunch that a sequence was important doesn't seem to matter:

```
import spacy

text = """
Which is why one of the proposed actions is to plant more trees.
Also, we carried out a complex experiment - Biosphere 2 - in 1991 in Arizona. 
"""

model = spacy.load('en_core_web_sm')
doc = model(text)

for chunk in doc.noun_chunks:
    chunk.merge()

for ent in doc.ents:
    ent.merge()
```
This results in:

> Traceback (most recent call last):
  File "path_to_script/example.py", line 14, in <module>
    for ent in doc.ents:
  File "doc.pyx", line 412, in spacy.tokens.doc.Doc.ents.__get__
AssertionError

**Comment by ines** [comment]
Thanks for the detailed report and the example!

To get a better idea for what's going on, I slightly reformatted the input text to make the whitespace visible and printed the  `ent_iob` values. It looks like the noun chunks and entities are overlapping and after merging the start token of the entity ("Biosphere") with the preceding token, the second token inside the entity ("-"), which is set to `I`, causes the assertion error here:

https://github.com/explosion/spaCy/blob/35653bef3acc28f63391a87bc6e5edd37430da5f/spacy/tokens/doc.pyx#L409-L412

So basically, spaCy complains, because the document contains an isolated entity token that's supposed to be *inside* an entity – but it's invalid, because it's not actually following a token that's inside an entity (`I`) or the beginning of an entity (`B`):

```python
doc = nlp('\nworda.\nwordb - Biosphere 2 -  \n')

[(t.text, t.ent_iob, t.ent_iob_) for t in doc]
# [('\n', 3, 'B'), ('worda', 2, 'O'), ('.', 2, 'O'), ('\n', 3, 'B'), ('wordb', 2, 'O'), 
#  ('-', 2, 'O'), ('Biosphere', 3, 'B'), ('2', 1, 'I'), ('-', 2, 'O'), (' \n', 2, 'O')]

for chunk in doc.noun_chunks:
    chunk.merge()

[chunk.text for chunk in doc.noun_chunks]
# ['wordb', '- Biosphere']

[(t.text, t.ent_iob, t.ent_iob_) for t in doc]
# [('\n', 3, 'B'), ('worda', 2, 'O'), ('.', 2, 'O'), ('\n', 3, 'B'), ('wordb', 2, 'O'), 
#  ('- Biosphere', 2, 'O'), ('2', 1, 'I'), ('-', 2, 'O'), (' \n', 2, 'O')]

[ent.text for ent in doc.ents]
# AssertionError
```

**Comment by honnibal** [comment]
Merging discussion to #1474 , as the underlying problem is the same.
