### ISSUE TITLE
Citing spaCy v2

### ISSUE THREAD

**Issue by danielhers** [explosion/spaCy#1555]
This has been asked previously about v1 (#272), but I think the parser implementation as well as underlying algorithms have changed in v2.
What is the preferred way to cite the algorithms used in the tagger, parser and named entity recognizer used in spaCy (in addition to referring to spacy.io in a footnote)?

**Comment by honnibal** [comment]
Probably the best solution is to just make a forward citation to a publication that doesn't exist yet. Something like this:

```
@ARTICLE{BM:1999,
   AUTHOR  = {Honnibal, Matthew AND Montani, Ines},
   TITLE   = {spaCy 2: Natural language understanding with Bloom embeddings, convolutional neural networks and incremental parsing},
   YEAR    = {2017},
   JOURNAL = {To appear}
}
```

**Comment by danielhers** [comment]
Thanks, I'll do that.

**Comment by Liebeck** [comment]
@honnibal I'm looking forward to reading the paper ;-) If you want some feedback before submitting / uploading the paper, contact me =)
