### ISSUE TITLE
Documentation bug - Example about adding a component to the pipeline

### ISSUE THREAD

**Issue by ruiEnca** [explosion/spaCy#1556]
The guide about Custom Components has a small error in the example about adding a pipeline component:
```
nlp = spacy.load('en')
nlp.pipeline.add_pipe(my_component, name='print_info', first=True)
print(nlp.pipe_names) # ['print_info', 'tagger', 'parser', 'ner']
doc = nlp(u"This is a sentence.")
```

This code cause an AtributeError in the 2nd line since the pipeline is a list and has no attribute 'add_pipe'.
The second line should be:
`nlp.add_pipe(my_component, name='print_info', first=True)`

Thanks for the great work!
Rui Encarnação

**Comment by ines** [comment]
Ahhh, stupid typo – thanks a lot for spotting and reporting this! 👍 Fixing!
