### ISSUE TITLE
Getting attribute error while adding a custom pipe in the current pipeline

### ISSUE THREAD

**Issue by Gauravtolani** [explosion/spaCy#1558]
```
def my_component(doc):
    print("After tokenization, this doc has %s tokens." % len(doc))
    if len(doc) < 10:
        print("This is a pretty short document.")
    return doc

nlp = spacy.load('en')
nlp.pipeline.add_pipe(my_component, name='print_info', first=True)


```
This code snippet is giving an error : 
`AttributeError: 'list' object has no attribute 'add_pipe'
`

Is it an import error or I am missing out on something?

System Details : 
* **Python version:** 2.7.12
* **Platform:** Linux-4.10.0-38-generic-x86_64-with-Ubuntu-16.04-xenial
* **spaCy version:** 2.0.0rc2
* **Models:** en

**Comment by ines** [comment]
Sorry about this – this was a stupid typo! Already fixed it (see #1556) 😊
