### ISSUE TITLE
Is Lexeme.similarity() broken?

### ISSUE THREAD

**Issue by damianoporta** [explosion/spaCy#1560]
## Your Environment
```
    spaCy version      2.0.2
    Platform           Linux-4.4.0-98-generic-x86_64-with-Ubuntu-16.04-xenial
    Location           /home/damiano/lavoro/python/nlp/spacy
    Python version     3.5.2          
    Models             en, it
```

Hello, 
i did a simple test with this code:

```
import spacy
nlp = spacy.load('en')
doc = nlp("apple is a fruit")
print(doc[0].similarity(doc[3]))
print(nlp.vocab['apple'].similarity(nlp.vocab['fruit']))
```
output:
```
0.339505
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lexeme.pyx", line 110, in spacy.lexeme.Lexeme.similarity
  File "lexeme.pyx", line 147, in spacy.lexeme.Lexeme.vector_norm.__get__
  File "lexeme.pyx", line 159, in spacy.lexeme.Lexeme.vector.__get__
ValueError: Word vectors set to length 0. This may be because you don't have a model installed or loaded, or because your model doesn't include word vectors. For more info, see the documentation: 
https://spacy.io/usage/models
```
As you can see I can get the similarity of apple/fruit via Token but NOT via Lexeme. 

I found this problem trying the code https://github.com/explosion/spaCy/issues/276, basically i would like to loop over all the vocabs to find the top 10 similar words giving a `Lexeme`.

**Comment by SandraReal** [comment]
Hi,
I was having the same problem but in that case I think it is solved using a language with vectors, I tried with en_core_web_lg.

Code:
`import spacy
nlp = spacy.load('en_core_web_lg')
doc = nlp("apple is a fruit")
print(doc[0].similarity(doc[3]))
print(nlp.vocab['apple'].similarity(nlp.vocab['fruit']))`

Output:
`0.6306183
0.6306183`

I hope that helps.
