### ISSUE TITLE
Working with Word-Vectors

### ISSUE THREAD

**Issue by AI-Guru** [explosion/spaCy#1561]
Namaste!

Given an arbitrary word-vector as a numpy-array of floats... What is the best way to get the words most similar to that vector?

**Comment by RushiLuhar** [comment]
Hello,

There are a number of similarity measures that can be used to find similar vectors. These include cosine similarity, etc. Relevant documentation for Spacy is [here](https://spacy.io/usage/vectors-similarity). The library itself provides a similarity method to compare Doc, Span and Token objects.

HTH.

Rushi

**Comment by bheinzerling** [comment]
There is no single best" way to find the most similar vectors in a high-dimensional vector space, just different methods with different trade-offs.

Probably the most simple way is a naive search over all vectors. That is, you compute the distance between your arbitrary word vector and all word vectors. In numpy this looks something like this:

```Python
import numpy as np

vocab_size = 1000
embedding_dim = 100
vecs = np.random.randn(vocab_size, embedding_dim)  # random embeddings as an example
word = np.random.randn(embedding_dim)  # our arbitrary word vector
distances = np.linalg.norm(word - vecs, dim=1)  # compute Euclidean distance between word and all vectors
most_similar_word_index = distances.argmin()
```

This works well for small vocabularies, but gets slow for larger ones or if you need to do many searches.
There are many specialized libraries to do what you want to do. Some search terms are "efficient similarity search" or "approximate nearest neighbor search". One of the more popular libraries is https://github.com/facebookresearch/faiss

**Comment by AI-Guru** [comment]
Nice! Thanks!

The question is more like, how to do these things in spaCy? Is there something built-in?

 I would love to map a word-embedding to a string. Preferably to the word that is the most similar/cos-closest to the vector.

**Comment by bheinzerling** [comment]
There is this method, which seems to be doing what you want, although for some reason it doesn't appear to be in the docs:

https://github.com/explosion/spaCy/blob/master/spacy/vectors.pyx#L249

**Comment by ines** [comment]
> There is this method, which seems to be doing what you want, although for some reason it doesn't appear to be in the docs:
https://github.com/explosion/spaCy/blob/master/spacy/vectors.pyx#L249

Ah yes – we decided not to document it for now, because the API is still a bit rough and might change in the future. But it should work – so feel free to play around with it, and let us know if you have any suggestions.

**Comment by AI-Guru** [comment]
This looks very promising! Thanks!

About usage... I tried this, but I had no success:

`
import spacy

nlp = spacy.load('de')

vector1 = nlp("Queen")[0].vector
vector2 = nlp("King")[0].vector
vector3 = vector1 - vector2

result = nlp.vocab.vectors.most_similar(vector1)
result = nlp.vocab.vectors.most_similar(vector2)
result = nlp.vocab.vectors.most_similar(vector3)
`

Traceback:
`
File "vectors.pyx", line 272, in spacy.vectors.Vectors.most_similar
  File "/Users/tbehrens/Development/DeepLearning/venv-3.5/lib/python3.5/site-packages/numpy/linalg/linalg.py", line 2198, in norm
    return sqrt(add.reduce(s, axis=axis, keepdims=keepdims))
numpy.core._internal.AxisError: axis 1 is out of bounds for array of dimension 1
`

**Comment by ines** [comment]
> `nlp = spacy.load('de')`

The problem with using the `de_core_news_sm` model is that the `sm` models only come with context-sensitive token vectors, which are shared by the tagger, parser and entity recognizer – but not word vectors. This means you can still use the `.similarity()` methods (which is pretty nice), but there are still no *actual* word vectors included, so `.vector` will be empty. See #1520 for more details on this.

Unfortunately, we currently don't have a larger German model that comes with word vectors at the moment (we do, however, have options for English, Spanish and French). If you want to use vectors in German, you'd have to load in your own for now (for example, [from fastText](https://spacy.io/usage/vectors-similarity#custom-loading-other)), until we have `de_core_news_md` ready.

**Comment by danielhers** [comment]
Joining the question about `de_core_news_md` - any estimate for when it will be ready? Thanks!

**Comment by ines** [comment]
@AI-Guru @danielhers Sorry for the late reply, only saw this now. I really don't want to promise too much or give you a time estimate that we might not be able to meet. 

We definitely want to add it to the list of models when we train new versions of the current "model family".  There are also some bugs and inconsistencies we want to fix before we retrain the models – including some data augmentation to make the German model less sensitive to captialisation (see #1922).
