### ISSUE TITLE
Issue with training multi label TextCategorizer

### ISSUE THREAD

**Issue by RushiLuhar** [explosion/spaCy#1562]
Hello,

I have been attempting to extend the TextCategorization example [here](https://github.com/explosion/spacy/blob/master/examples/training/train_textcat.py) to support a 3 label classifier. My code is [here](https://gist.github.com/RushiLuhar/e421113cd8113fe64758292eb4fd6827).  

I modified the` load_data() ` method to load examples from a file, and added the three labels to the textcat pipe. The data loads but I end up with a numpy error (See [Gist](https://gist.github.com/RushiLuhar/e421113cd8113fe64758292eb4fd6827)) when attempting to train the classifier. 

>   File "linear.pyx", line 43, in thinc.linear.linear.LinearModel.begin_update
> ValueError: Buffer and memoryview are not contiguous in the same dimension.
> 

Each mini batch entry looks like:

> <class 'tuple'>: ("The home insurance was taken out online and couldn't have been easier. \n", {'cats': {'__label__neg': False, '__label__neu': False, '__label__pos': True}})

So we have some text, and the gold labels include values for each label. I am not sure if this is an issue with the way I am specifying the training data or with something else. 

## Info about spaCy
* **spaCy version:** 2.0.2
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **Python version:** 3.6.3
* **Models:** en_core_web_lg

**Comment by honnibal** [comment]
Could you check that your data doesn't introduce new labels, that you haven't specified at the beginning of training?

That should work --- but it's the part that's most likely to fail here, from what I can see.

**Comment by RushiLuhar** [comment]
Hi @honnibal ,

Sorry for the late reply. I just checked again and can confirm that no new labels are added during training that weren't specified to the categorizer pipeline before training. 

The data passed to the `nlp.update(..)`method are a tuple of sentences called 'texts' and a tuple of categories called 'annotations'.  Each annotation looks like: `{'cats': {'__label__neg': False, '__label__pos': True, '__label__neu': False}}`

```
for batch in batches:
                texts, annotations = zip(*batch)
                nlp.update(texts, annotations, sgd=optimizer, drop=0.2,
                           losses=losses)
```

The code fails at the very first call to nlp.update (snippet above). I am wondering if the annotations are in the correct format. The code is pretty much identical to the categorization example with only modifications made for multi-label categorization.

**Comment by honnibal** [comment]
@RushiLuhar Hm. I don't know why it would matter, but try setting 1.0 and 0.0 instead of True and False?

You can also omit a category from a training example, to indicate unknown values.

**Comment by RushiLuhar** [comment]
@honnibal  - this was a bug in my code. As you mentioned earlier, the issue seemed to be around adding all labels to the text categorizer. I will close this issue. Thanks for taking the time to look into it.

**Comment by davinnovation** [comment]
I have the same problem @RushiLuhar . Can you share working load_data?

**Comment by sammous** [comment]
Hello,

I have the same issue @RushiLuhar. Can you tell how you fixed it please?
In `nlp.update`, I feed 5 labels for `cats` where 
```
cats = { 'label1': True,
'label1': True,


```

**Comment by zihaolucky** [comment]
@RushiLuhar have you try change the order to add labels in `textcat.add_label(xxx)`? I met some weird problems. #1763
