### ISSUE TITLE
Performance: spacy 2.0.1 failed as API service

### ISSUE THREAD

**Issue by sathik11** [explosion/spaCy#1571]
## Your Environment
* Operating System: AWS Linux AMI (Red Hat 4.8.5-11)] on linux
* Python Version Used: python 3.5
* spaCy Version Used: 2.0.1

I use spacy as a microservice using flask /wsgi/apache2.4 in an AWS EC2 instance .
I recently upgraded it to `spacy 2.0.1(en_core_web_md-2.0.0)`- 
But when i try to call the microservice through API (http) calls , after waiting for few mins ,there is no response . At times i get this error ` End of script output before headers: deploy.wsgi` . 
When i restart the httpd service , i get a successful response for first api call , subsequent calls fail . 
All other python packages works just fine.(e.g NLTK) . is it some sort for GIL issue ?

With the same settings , i downgraded spacy to 1.9.0 and now is works fine. 
I have been using spacy 1.9.0 for a while with ` en_core__web_md-1.2.1` model

It happened with spacy 2.0.1

**Comment by honnibal** [comment]
Thanks for reporting. Possibly related to #1572 ?

**Comment by Bri-Will** [comment]
I am seeing this exact same behavior...on Azure but also with a Flask app and Apache via mod_wsgi....it also shows up if I use the Flask server stand-alone.

If I repeatedly send requests through, some of them will be returned but many will not be. I can't find a pattern on subsequent requests, but likethe OP I also see the initial request go through and the first request "hang" after the server has been restarted.

This is with Python 2.7 and Spacy 2.0...I'm going to try downgrading to Spacy 1.9.0.

**Comment by Bri-Will** [comment]
Downgrading to Spacy v1.9.0 does seem to have fixed the problem, but it has broken other Matcher-related code in my app. I made what I thought would be a few simple changes to go back to the old style of using the Matcher, but there is apparently more to it than I expected.

Any progress on this?

**Comment by Bri-Will** [comment]
One more update:

On Windows, with Spacy v2.0.0 I am seeing the same issue if I run my app through the Flask stand-alone app.

However, using FastCGI and IIS, everything works smoothly with v2.0.0. Weird...

**Comment by honnibal** [comment]
I believe this is down to #1572 , so closing this as there's more detail there.
