### ISSUE TITLE
what is dev_data in spacy train?

### ISSUE THREAD

**Issue by damianoporta** [explosion/spaCy#1578]
Hello, (i am using spacy 2x)

the command **spacy train -h** says `dev_data` parameter is optional, but it is not correct

**spacy train en /home/damiano/spacy/ /home/damiano/test.json**
```
usage: spacy train [-h] [-n 30] [-ns 0] [-g -1] [-v None] [-T] [-P] [-N] [-G]
                   [-V 0.0.0] [-m None]
                   cmd lang output_dir train_data dev_data
spacy train: error: the following arguments are required: dev_data
```

What should i pass to this parameter? Thanks.

**Comment by ines** [comment]
The `dev_data` is your development data, i.e. the evaluation data. It's usually a representative portion of your data that you split off before training, and use to evaluate how your model is performing on unseen examples. As you train the model, the development data is used to show an accuracy evaluation.

For example, if you're training a model on a [Universal Dependencies corpus](https://github.com/UniversalDependencies/UD_English), you'd use the converted version of the `xxx-train.conllu` as the `train_data`, and the converted `xxx-dev.conllu` as the `dev_data`.

I just noticed that this is a mistake in the docs – the `dev_data` is required, not optional. Without development data, the training is pretty useless, as you won't be able to see any updates or results. Will fix this in the docs!
