### ISSUE TITLE
 nvcc fatal   : Value 'sm_20' is not defined for option 'gpu-architecture'

### ISSUE THREAD

**Issue by awhan** [explosion/spaCy#1580]
Spacy fails to install on archlinux distro due to error in installation of thinc. 

I used the following to install `pip install --user spacy`. Error that I could glean from the log file is 

> nvcc fatal   : Value 'sm_20' is not defined for option 'gpu-architecture'

while the following message is what I noted in the terminal

> Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mqkbeylk/thinc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-s1ppwpnp-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-mqkbeylk/thinc/

output of `nvcc --version` is

> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2017 NVIDIA Corporation
> Built on Fri_Sep__1_21:08:03_CDT_2017
> Cuda compilation tools, release 9.0, V9.0.176

pip install log is [here](https://drive.google.com/file/d/1Z3iAxumTrMf0j-P8fQI_eypLGxvxwHGg/view)

## Your Environment

* Operating System: `uname -a` is Linux zero 4.13.12-1-ARCH #1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux
* Python Version Used: Python 3.6.3
* spaCy Version Used: could not install (attempted to install 2.0.2)
* Environment Information: don't know how to generate without spacy installed

**Comment by honnibal** [comment]
Fixing this in Thinc, thans.

**Comment by honnibal** [comment]
Should now be fixed in Thinc.
