### ISSUE TITLE
High disparity on similarity with plural - French language

### ISSUE THREAD

**Issue by pavillet** [explosion/spaCy#1593]
## Your Environment
* **spaCy version:** 2.0.3
* **Platform:** Darwin-16.6.0-x86_64-i386-64bit
* **Python version:** 3.6.1
* **Models:** fr, fr_core_news_md

Hi there, I'm not sure how to label this but I'm having trouble understanding similarity since scores seems to diverge way too much in my following exemple.

The sentences are in french, but all you need to understand is that it's somewhat  from plural to singular

```
import spacy

nlp = spacy.load('fr_core_news_md')

print("Comparing 'Comment prendre des congés' and 'Comment poser un congé ?'")
print(nlp("Comment prendre des congés").similarity(nlp("Comment poser un congé ?")))

print("Comparing 'Comment prendre des congé' and 'Comment poser un congé ?'")
print(nlp("Comment prendre des congé").similarity(nlp("Comment poser un congé ?")))

print("Comparing 'Comment prendre un congés' and 'Comment poser un congé ?'")
print(nlp("Comment prendre un congés").similarity(nlp("Comment poser un congé ?")))

print("Comparing 'Comment prendre un congé' and 'Comment poser un congé ?'")
print(nlp("Comment prendre un congé").similarity(nlp("Comment poser un congé ?")))
```

Which give the following 

```
Comparing 'Comment prendre des congés' and 'Comment poser un congé ?'
0.407196907018
Comparing 'Comment prendre des congé' and 'Comment poser un congé ?'
0.731839520601
Comparing 'Comment prendre un congés' and 'Comment poser un congé ?'
0.526540901522
Comparing 'Comment prendre un congé' and 'Comment poser un congé ?'
0.817495327218
```
As you can see the scores range from 0.4 to 0.81, with only "minor" changes ( plural )

Am I missing something or should I format my text before trying to compare it ? Is that a bug due to the french language used ?

To broaden the question, the goal is to find the most relevant sentence from a query, would that be the best method?

Thanks for any help

**Comment by honnibal** [comment]
Merging with #3052 , the inaccurate predictions master thread.
