### ISSUE TITLE
Rule-based matching operators and quantifiers not working as expected

### ISSUE THREAD

**Issue by RqS** [explosion/spaCy#1595]
You have the following quantifiers
```
! | Negate the pattern, by requiring it to match exactly 0 times.
* | Make the pattern optional, by allowing it to match 0 or 1 times.
+ | Require the pattern to match 1 or more times.
? | Allow the pattern to zero or more times.
```
With your example of rule-based matching
I have create the following pattern for match
```
doc1 = nlp(u'Facebook is very very very very annoying')
pattern = [{'LOWER': 'facebook'}, {'LEMMA': 'be'}, {'POS': 'ADV', 'OP': '*'}, {'POS': 'ADJ'}]
matcher.add('FacebookIs', None, pattern)
matches = matcher(doc1)
```
It returns
```
>>> matches
[(8873751423615342821L, 0, 7)]
```
Which should be the output of using "?". I guess you made a typo in your documents. 
https://spacy.io/usage/linguistic-features#section-rule-based-matching

However, '!' is not working as expected.
```
pattern =  [{'LOWER': 'facebook'}, {'LEMMA': 'be'}, {"LOWER": 'very', 'OP': '!'}, {"ORTH": "annoying"}]
matcher.add('FacebookIs', None, pattern)
matches = matcher(nlp(u'facebook is annoying'))
```
I suppose it should return me a match, but it gives me no result.
```
>>> matches
[]
```

## My Environment

* Operating System: macOS Sierra 10.12.4
* Python Version Used: 2.7.10
* spaCy Version Used: 2.0.3

**Comment by ines** [comment]
Fixed in 65babd9e2ec27ffb0075a44077a0b760937aa33a, sorry about that!
