### ISSUE TITLE
typo on docs

### ISSUE THREAD

**Issue by MartinoMensio** [explosion/spaCy#1599]
`Dependcy` --> `Dependency`
https://github.com/explosion/spaCy/blob/75d2a05c2938f412f0fae44748374e4de19cc2be/website/usage/_linguistic-features/_dependency-parse.jade#L32

**Comment by ines** [comment]
Thanks! 👍 Do you wanna submit a quick PR? If not, I'm also happy to fix it later.

**Comment by MartinoMensio** [comment]
Yes sure! Will do that soon

**Comment by MartinoMensio** [comment]
https://github.com/explosion/spaCy/pull/1602
