### ISSUE TITLE
LIKE_URL property is not working correctly

### ISSUE THREAD

**Issue by damianoporta** [explosion/spaCy#1606]
## Your Environment
    Location           /home/damiano/lavoro/python/testing/spacy
    Python version     3.5.2          
    Models             en, it         
    spaCy version      2.0.0          
    Platform           Linux-4.4.0-98-generic-x86_64-with-Ubuntu-16.04-xenial

Hello,
LIKE_URL property is not working correctly. It returns `True` passing an email address.

```
import spacy
nlp = spacy.load('en')
doc = nlp("test@test.com")
print(doc[0].like_url)
True
```

**Comment by ines** [comment]
Merging this with #1698!
