### ISSUE TITLE
Error when trying to build Japanese TAGGER model

### ISSUE THREAD

**Issue by buivietan** [explosion/spaCy#1613]
I got this error 
  "File "gold.pyx", line 454, in spacy.gold.GoldParse.__init__
    IndexError: list index out of range" 
when trying to build Japanese TAGGER model based on https://github.com/explosion/spacy/blob/master/examples/training/train_tagger.py 
I used Japanese nlp:  
   from spacy.lang.ja import Japanese
    nlp = Japanese()
Could you please help me out of this issue. Thanks so much!

## Environment
* Operating System:  Win 10 Pro
* Python Version Used: 3.6.3
* spaCy Version Used: 2.0.2

**Comment by ines** [comment]
Hi! There might be a simple explanation for this: Can you check that the length of the tags you pass in always matches the length of the tokens spaCy segments the text into? If spaCy's actual tokenization is different from what you expect, the tags don't match, and this might cause an error like this.

You can also work around this by setting an additional `words` key on the annotations you pass in, which specifies the gold-standard tokenization. For example:

```python
TRAIN_DATA = [
    ("I like greeneggs", {'words': ['I', 'like', 'green', 'eggs'], 'tags': ['N', 'V', 'J', 'N']})
]
```

**Comment by buivietan** [comment]
@ines: Thanks for your quick reply, I'll try and give you my feedback :)
