### ISSUE TITLE
SpaCy hangs after fork

### ISSUE THREAD

**Issue by pokey** [explosion/spaCy#1615]
## Info about spaCy

* **spaCy version:** 2.0.3
* **Platform:** Darwin-16.6.0-x86_64-i386-64bit
* **Python version:** 3.6.0
* **Models:** en_core_web_sm-2.0.0

## The problem

SpaCy now hangs if I try to run it after forking a process on MacOS.  This worked prior to SpaCy 2.0.0.  Here's code to reproduce the issue:

```py
import multiprocessing

import spacy


nlp = None

text_list = [
    'I love SpaCy.'
]


def process_text(text):
    return list(nlp(text))


def init_globals(_nlp):
    # These are attrs that subprocesses need copies of.  Note that we are
    # relying on Unix fork semantics to ensure that children can access these
    # variables
    global nlp

    nlp = _nlp


def run():
    nlp = spacy.load('en')
    init_globals(nlp)
    with multiprocessing.Pool(1) as pool:
        for out in pool.imap(process_text, text_list):
            print(out)


run()
```

**Comment by honnibal** [comment]
I think this is the problem: https://github.com/numpy/numpy/issues/5752

**Comment by pokey** [comment]
Interesting.  Any idea why that would have become a problem in 2.0.0?  Using numpy differently I guess?

**Comment by honnibal** [comment]
Yes, 1.x didn't use numpy at all during calls to the nlp pipeline.

Merging this with #1572
