### ISSUE TITLE
Drop support for Python versions that are EOL?

### ISSUE THREAD

**Issue by cclauss** [explosion/spaCy#1618]
[Python 2.6 and 3.3 have already reached End of Life.](https://docs.python.org/devguide/index.html#branchstatus)  Is it useful to continue supporting these legacy versions of Python?

https://github.com/explosion/spaCy/blob/master/setup.py#L214-L216

**Comment by honnibal** [comment]
Thank, I think the classifier in the setup is actually wrong. I suspect py2.6 has been broken for some time. py3.3 was horrible and nobody used it.
