### ISSUE TITLE
Loading a spacy language breaks the regex module?

### ISSUE THREAD

**Issue by lschmelzeisen** [explosion/spaCy#1623]
Consider the following program:

```python
#!/usr/bin/env python3

import regex as re
import spacy

re.compile(r'(\[)([^][]*)(\])')

spacy.load('en') # or alternatively spacy.blank('en')

re.compile(r'(\[)([^][]*)(\])')
```

On two of my machines the regex module throws an error on the last line!

```
Traceback (most recent call last):
  File "./test.py", line 10, in <module>
    re.compile(r'(\[)([^][]*)(\])')
  File "/home/lukas/anaconda3/envs/Research/lib/python3.6/site-packages/regex.py", line 345, in compile
    return _compile(pattern, flags, kwargs)
  File "/home/lukas/anaconda3/envs/Research/lib/python3.6/site-packages/regex.py", line 501, in _compile
    caught_exception.pos)
_regex_core.error: unterminated character set at position 16
```

The behavior is also reproducible if one substitutes `spacy.load('en')` with `spacy.blank('en')` or changes the language code. If one comments that line out the program runs without error.

I therefore believe that spacy somehow modifies the regex module, however I could not find any offending code.

## Info about spaCy (Machine 1)

* **regex version:** 2017.4.5
* **spaCy version:** 2.0.3
* **Platform:** Linux-4.9.61-3-MANJARO-x86_64-with-glibc2.9
* **Python version:** 3.6.3
* **Models:** en_vectors_web_lg, en, en_core_web_sm, en_core_web_lg, de, de_core_news_sm, en_core_web_md

## Info about spaCy (Machine 2)

* **regex version:** 2017.4.5
* **spaCy version:** 2.0.3
* **Platform:** Linux-4.4.0-98-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.2
* **Models:** en_core_web_lg, en_core_web_md, en_vectors_web_lg, de_core_news_sm, en_core_web_sm

**Comment by ines** [comment]
Thanks for the report – it might be related to the regex customisations in `spacy/lang/char_classes.py`:

https://github.com/explosion/spaCy/blob/ab2342a10e6a94e42682ebe2f1f9c607131c6569/spacy/lang/char_classes.py#L4-L7

The regex stuff in the language data has always been a little tricky... If I remember correctly, the modifications were needed to work around some issues with the `regex` module, which again is needed to work around issues with the standard `re` module.

But we might be able to add some workaround here? If you have any ideas or suggestions, we'd definitely appreciate it.

**Comment by lschmelzeisen** [comment]
Yes, that is definitely the relevant line. Since the following throws the same error:

```python
re.DEFAULT_VERSION = re.VERSION1
re.compile(r'(\[)([^][]*)(\])')
```

I'm not too familiar with the regex module, but I'll get back to you if I find some way to isolate such state change.

**Comment by lschmelzeisen** [comment]
The [regex module documentation](https://pypi.python.org/pypi/regex/) states

> * Version 0 behaviour (old behaviour, compatible with the current re module):
>   *  Indicated by the VERSION0 or V0 flag, or (?V0) in the pattern.
> ...
> * Version 1 behaviour (new behaviour, different from the current re module):
>   * Indicated by the VERSION1 or V1 flag, or (?V1) in the pattern.
> ...
> 
> If no version is specified, the regex module will default to regex.DEFAULT_VERSION.

Since overwriting `re.DEFAULT_VERSION` clearly breaks code in other modules, the following options remain: for example, code compiling a pattern a la `re.compile(r'<pattern>')` needs to be changed to either
* using a flag in the function call: `re.compile(r'<pattern>', flags=re.VERSION1)`, or
* using a modifier inside the pattern: `re.compile(r'(?V1)<pattern>')`

**Comment by ines** [comment]
Thanks for looking into this!

> using a flag in the function call: `re.compile(r'<pattern>', flags=re.VERSION1)`

This sounds like the best and most readable option to me – and it's also much better than defining random defaults in the top-level scope (especially considering the pretty bad side effects).

If I remember correctly, the version setting was only really necessary for the `char_classes`, so it'll only have to be added there. Considering the bad side-effects of setting it globally, I wonder if it might have also caused some of the other issues around the tokenization speed (parts of which we've tracked down to the prefix/suffix/infix rules).

**Comment by ines** [comment]
Merging this with #1642!
