### ISSUE TITLE
stopwords missing from en_core_web_lg

### ISSUE THREAD

**Issue by r-wheeler** [explosion/spaCy#1625]
Stopwords are all false for `en_core_web_lg`

```python
nlp = spacy.load("en_core_web_sm")
nlp2 = spacy.load("en_core_web_lg")
```

```python
[(w.orth_, w.is_stop) for w in nlp("is it true stopwords are not working for me")]
```

[('is', True),
 ('it', True),
 ('true', False),
 ('stopwords', False),
 ('are', True),
 ('not', True),
 ('working', False),
 ('for', True),
 ('me', True)]

```python
#en_core_web_lg
[(w.orth_, w.is_stop) for w in nlp2("is it true stopwords are not working for me")]
```
[('is', False),
 ('it', False),
 ('true', False),
 ('stopwords', False),
 ('are', False),
 ('not', False),
 ('working', False),
 ('for', False),
 ('me', False)]

## Info about spaCy

* **spaCy version:** 2.0.2
* **Platform:** Darwin-16.6.0-x86_64-i386-64bit
* **Python version:** 3.6.2
* **Models:** en_core_web_lg, en_core_web_sm

**Comment by ines** [comment]
Thanks for the report and sorry about that – this should be fixed in the next update to the models.

In the meantime, here's a workaround:

```python
nlp = spacy.load('en_core_web_lg')

for word in nlp.Defaults.stop_words:
    lex = nlp.vocab[word]
    lex.is_stop = True
```

(Will merge this with issue #1574 to keep things in one place!)
