### ISSUE TITLE
embarrassing KeyError on some string

### ISSUE THREAD

**Issue by caprone** [explosion/spaCy#1629]
"""loading model"""
`nlp = spacy.load('en_core_web_sm')`
then if we call nlp on a string like 'LE'  --> KeyError raise...   
`nlp('LE') `
another example :  
` nlp('Ag?')`

EDIT: also large model raise same issue on different strings
`nlp = spacy.load('en_core_web_lg')` # same issue on some different string

Environment

 windows 10 64 bit
Python Version Used:  Python 3.6.3 /Anaconda
spaCy Version Used:  2.02

**Comment by honnibal** [comment]
I believe this is fixed in v2.0.3

**Comment by caprone** [comment]
ok, thanks
