### ISSUE TITLE
examples/training/train_new_entity_type.py is not create any entity in test

### ISSUE THREAD

**Issue by rubiagatra** [explosion/spaCy#1632]
Hello, I just tried two examples.
1. train_ner.py (It worked well and created test result)
`python train_ner.py
Created blank 'en' model
{'ner': 11.274315223987287}
{'ner': 10.197453218953342}
{'ner': 11.592785060405731}
{'ner': 8.2308950674146217}
{'ner': 8.7559898609024636}
{'ner': 9.1455809843917546}
{'ner': 11.139080975126717}
{'ner': 8.3913978379017635}
{'ner': 7.6499104719842324}
{'ner': 8.4448880302941767}
{'ner': 3.973548353818138}
{'ner': 7.5009712328580029}
{'ner': 5.8130327018579893}
{'ner': 4.9309236148492248}
{'ner': 3.3177045584921179}
{'ner': 4.2690002110310861}
{'ner': 0.0076084520761010395}
{'ner': 4.3050689516198464}
{'ner': 3.8224483538595813}
{'ner': 1.8121708502904316e-05}
{'ner': 0.0011890729514645651}
{'ner': 0.066868622434461969}
{'ner': 4.4438820458640809e-05}
{'ner': 7.3022020161219802e-06}
{'ner': 7.0510136823028376e-10}
{'ner': 1.4822434734901406}
{'ner': 4.7790905833245709}
{'ner': 4.2394208736151774e-06}
{'ner': 2.0489134597389848e-06}
{'ner': 1.9843188583179341}
{'ner': 3.9470151125213366}
{'ner': 0.0004515489563961846}
{'ner': 2.2734703756372849e-14}
{'ner': 8.5761814270539079e-05}
{'ner': 2.4066854321493115e-08}
{'ner': 3.1593860049551433e-19}
{'ner': 1.6355773971817056e-15}
{'ner': 3.3637201097220958e-09}
{'ner': 1.2188783318586303e-10}
{'ner': 2.1522544557301282e-05}
{'ner': 1.285557772145931e-06}
{'ner': 3.8343978308883191e-06}
{'ner': 6.487179681277572e-15}
{'ner': 5.797853433656586e-14}
{'ner': 2.0891087173822102e-14}
{'ner': 3.9625700024362219e-16}
{'ner': 8.1206429999888447e-07}
{'ner': 2.9454501631064569e-16}
{'ner': 9.209153361850085e-12}
{'ner': 3.5905722942069958e-10}
{'ner': 1.3146889681918302e-18}
{'ner': 1.4413560503219247e-10}
{'ner': 0.00037235344884873549}
{'ner': 0.0002796603479970905}
{'ner': 5.5096438071362416e-19}
{'ner': 1.0037685605990319e-09}
{'ner': 7.1546007510680475e-13}
{'ner': 7.4013325956938779e-07}
{'ner': 3.3381066758759573e-11}
{'ner': 7.2541880368429144e-14}
{'ner': 1.7728516003355989e-16}
{'ner': 1.3495918301299001e-10}
{'ner': 4.5684653188962346e-16}
{'ner': 1.023885727016755}
{'ner': 4.2747549078078985e-14}
{'ner': 1.430010792208147e-12}
{'ner': 1.1650906644643979e-21}
{'ner': 1.9778633184133108e-15}
{'ner': 2.0699958460585779e-08}
{'ner': 1.9759548902511597}
{'ner': 2.7545946751074344e-18}
{'ner': 5.1902577979538489e-05}
{'ner': 3.7658004419577776e-20}
{'ner': 1.4140697828522196e-15}
{'ner': 1.7745880387937848e-08}
{'ner': 5.5657608543612242e-16}
{'ner': 9.7699830803360892e-07}
{'ner': 1.9077605812524394e-18}
{'ner': 2.9679691807353523e-06}
{'ner': 6.2105086258061961e-10}
{'ner': 2.19686839386668e-07}
{'ner': 7.8672485193234113e-11}
{'ner': 6.3972405561084984e-16}
{'ner': 0.00024963624337273794}
{'ner': 2.7295081110068877e-21}
{'ner': 2.0235655626745925e-23}
{'ner': 9.4191124373372524e-26}
{'ner': 8.1681708409536911e-20}
{'ner': 7.0650854599225661e-10}
{'ner': 4.3539730438847247e-23}
{'ner': 6.8670423689815933e-20}
{'ner': 3.2179581653091597e-27}
{'ner': 4.0213263274858181e-10}
{'ner': 2.9000876434647691e-18}
{'ner': 1.5973741773755989e-10}
{'ner': 1.7695267791912876e-16}
{'ner': 4.600333769823724e-15}
{'ner': 3.6369809931956473e-17}
{'ner': 9.4634927644470541e-17}
{'ner': 8.6575228849781086e-21}
Entities [('Shaka Khan', 'PERSON')]
Tokens [('Who', '', 2), ('is', '', 2), ('Shaka', 'PERSON', 3), ('Khan', 'PERSON', 1), ('?', '', 2)]
Entities [('London', 'LOC'), ('Berlin', 'LOC')]
Tokens [('I', '', 2), ('like', '', 2), ('London', 'LOC', 3), ('and', '', 2), ('Berlin', 'LOC', 3), ('.', '', 2)]`

2. train_new_entity_type.py (There was no result)
`python train_new_entity_type.py
Created blank 'en' model
{'ner': 30.330521366890046}
{'ner': 14.973980872843425}
{'ner': 10.130020611874365}
{'ner': 2.0015162951662724}
{'ner': 2.1969848959269309}
{'ner': 3.0810486665146142}
{'ner': 0.11251135139648261}
{'ner': 3.7693287325099097e-05}
{'ner': 3.9300847041517299e-07}
{'ner': 1.984352350948333}
{'ner': 0.0021053762281392375}
{'ner': 3.1440182982223383e-08}
{'ner': 0.15083304047671223}
{'ner': 2.5529546369721052e-07}
{'ner': 1.9980669021606445}
{'ner': 2.5818494021240788e-07}
{'ner': 1.2071736017242398e-11}
{'ner': 3.4315147056738234e-10}
{'ner': 3.2141549461524832e-10}
{'ner': 1.1837019576455171e-08}
{'ner': 2.2304603688182124e-05}
{'ner': 8.5437362740193825e-10}
{'ner': 3.4989218319508572e-17}
{'ner': 1.6503252277801367e-17}
{'ner': 1.2060444925772807e-18}
{'ner': 9.2172231262031348e-20}
{'ner': 0.37061619758606001}
{'ner': 1.7372203607592502e-16}
{'ner': 4.5384446446829058e-08}
{'ner': 8.7643312709184798e-17}
{'ner': 0.0010351513022207994}
{'ner': 6.9860339457134269e-22}
{'ner': 5.4095994873327469e-13}
{'ner': 7.7269194707814991e-16}
{'ner': 5.5386997266629557e-10}
{'ner': 3.5182963969434239e-22}
{'ner': 2.3759682385422849e-18}
{'ner': 5.6084424318602521e-22}
{'ner': 2.476961655337516e-20}
{'ner': 2.57340011252716e-19}
{'ner': 9.5794310255667833e-15}
{'ner': 1.3646837600009175e-16}
{'ner': 9.956593601349449e-19}
{'ner': 4.5992676355074376e-17}
{'ner': 4.3164396670457313e-15}
{'ner': 2.6378411470616622e-09}
{'ner': 3.0487772015461557e-19}
{'ner': 1.96832184676749e-24}
{'ner': 2.1762027736267115e-09}
{'ner': 7.6282972863961115e-23}
Entities in 'Do you like horses?''`

## Your Environment

* Operating System: Ubuntu 16.04
* Python Version Used: 3.6.3
* spaCy Version Used: 2.0.3
* Environment Information:

**Comment by ines** [comment]
Thanks – just tested it and while it works as expected with an input model like `en_core_web_sm`, using a blank model also didn't turn up any entities for me.

It looks like we were using too many iterations by default and overfitting the data – changing `n_iter=20` (or running the script with `-n 20`) fixed it for me. Will adjust this in the example!
