### ISSUE TITLE
'spacy.tokens.span.Span' has no attribute 'vocab'

### ISSUE THREAD

**Issue by griffonn** [explosion/spaCy#1633]
When trying to get sentence vector using 
```
for sent in doc.sents:
    if sent.has_vector:
        ...
```

I get the following exception:
```
  File "span.pyx", line 286, in spacy.tokens.span.Span.has_vector.__get__
AttributeError: 'spacy.tokens.span.Span' object has no attribute 'vocab'
```

## Your Environment

* Operating System: Ubuntu Linux 16.04 64-bit
* Python Version Used: 3.5.2
* spaCy Version Used: 2.0.2
* Environment Information:

**Comment by honnibal** [comment]
Thanks. Workaround: Use `span.doc.has_vector`
