### ISSUE TITLE
Memory error when using parser `nlp(sentences)` with spacy 2.0

### ISSUE THREAD

**Issue by zotroneneis** [explosion/spaCy#1636]
I'm getting a memory error when calling `parsed = nlp(sentences)`

MemoryError: Error assigning 18446744072562989824 bytesError assigning 18446744072562989824 bytesError assigning 18446744072562989824 bytesError assigning 18446744072562989824 bytes

Although the file has 339MB, I had no problems parsing it a few weeks ago (I was still working with the previous spacy version at that point). 

* **Platform:** Linux-4.8.4-kd-cluster-x86_64-with-debian-8.9
* **Python version:** 3.5.4
* **Models:** de
* **spaCy version:** 2.0.3

RAM: 60GB

Any ideas where this problem is coming from? 

Update: this might be related to the problem discussed in issue #1600

**Comment by honnibal** [comment]
There's currently a problem on large documents for v2. It'll be difficult to solve so for now you should cut up your text file.

The problem is that the v2 modeluses a neural network, which allocates various working spaces for each word of the document. Usually this is no problem, but for large documents we run into trouble.

**Comment by zotroneneis** [comment]
Is it possible to convert back to the previous spacy version to use the old parser?
I am using `nlp(sentences)` for breaking up files of German text into sentences. That's all I need so far. So if that functionality hasn't changed too much I would use the previous spacy version. I have about 100 files of that size so cutting up each into lots of small parts would become ugly

**Comment by honnibal** [comment]
You should be able to do:

```
nlp = spacy.blank('de')
nlp.add_pipe(nlp.create_pipe('sentencizer'))
```

The sentence boundary detection logic is simpler because it doesn't use the statistical model, but it should be faster.

If you do need to downgrade, you can do that with:

```pip install spacy<2.0```

**Comment by honnibal** [comment]
`spacy-nightly` now checks document lengths and raises an error on very large documents. Memory usage should also be somewhat better overall.
