### ISSUE TITLE
Installing Spacy fails with Ubuntu 16, Python3.5 in Amazon Lightsail server

### ISSUE THREAD

**Issue by anandselva** [explosion/spaCy#1648]
I have tried installing spacy using the source and pip, both of them failed and returns the same error. 
Please find below the error I am getting, the full report is down below.

`Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3e25iqit/spacy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-myh5w_vy-record/install-record.txt --single-version-externally-managed --compile" failed with error code -9 in /tmp/pip-build-3e25iqit/spacy/`

Any help really appreciated. Thank you!

## My Environment

* Operating System: Ubuntu 16.04.2 LTS
* Python Version Used: Python 3.5.2
* spaCy Version Used: pip3 install -U spacy (latest version)
* Environment Information: both in Virtualenv and normal

scrapy version -v

Scrapy    : 1.4.0
lxml      : 4.1.1.0
libxml2   : 2.9.7
cssselect : 1.0.1
parsel    : 1.2.0
w3lib     : 1.18.0
Twisted   : 17.9.0
Python    : 3.5.2 (default, Sep 14 2017, 22:51:06) - [GCC 5.4.0 20160609]
pyOpenSSL : 17.4.0 (OpenSSL 1.1.0g  2 Nov 2017)
Platform  : Linux-4.4.0-1013-aws-x86_64-with-Ubuntu-16.04-xenial

## Full report

Please take a look at full report in [here](https://gist.github.com/anandselva/34b65657b6a77fd26e250452057b45f6)

**Comment by riemannzeta1191** [comment]
Facing similar issue.Installation is failing at lemmatizer.py.
https://github.com/explosion/spaCy/issues/1656

**Comment by honnibal** [comment]
Maybe try `sudo apt-get install build-essential python3-dev`?

It looks like it fails to compile. These missing system dependencies would be the most likely explanation.

**Comment by anandselva** [comment]
Hi @honnibal,

Thank you for your response but I have already installed some dependencies then tried to install Spacy, still same issue.

FYI:
`sudo apt-get install build-essential python3-pip libssl-dev libffi-dev libxml2-dev libxslt1-dev zlib1g-dev`

**Comment by javier-igneoma** [comment]
Any update on this? @anandselva Did you finally installed spaCy?

**Comment by anandselva** [comment]
Thank you! @javier-igneoma, No I didn't find out a solution for that error. However, I will check with Medium EC2 instance.

FYI: I've done whatever I was planned to do with spaCy with another library.

Closing this issue.
