### ISSUE TITLE
zero vocab.vectors_length and lex.has_vector for English vocab 

### ISSUE THREAD

**Issue by tiru1930** [explosion/spaCy#1651]
I am trying to get embedding vectors for English model, but not able to get it 

    import spacy
    nlp=spacy.load('en')
   vocab= nlp.vocab 
   nr_unk=100
    nr_vector = max(lex.rank for lex in vocab) + 1
    print(nr_vector) = lex.rang
    print(vocab.vectors_length)
    vectors = numpy.zeros((nr_vector+nr_unk+2, vocab.vectors_length), dtype='float32')
    for lex in vocab:
        if lex.has_vector:
            vectors[lex.rank+1] = lex.vector / lex.vector_norm
    print(vectors.shape)

>>> vocab=nlp.vocab
>>> len(vocab)
57840
>>> max(lex.rank for lex in vocab)
0
>>> vocab.vectors_length
0
>>> vocab[0].has_vector
False

## Info about spaCy

* **Python version:** 3.5.2
* **spaCy version:** 2.0.2
* **Models:** en
* **Platform:** Linux-4.10.0-38-generic-x86_64-with-Ubuntu-16.04-xenial

**Comment by honnibal** [comment]
The `en_core_web_sm` model doesn't include word vectors. You can download the `en_core_web_md` or `en_core_web_lg` models instead, which do.
