### ISSUE TITLE
wrong import for thinc

### ISSUE THREAD

**Issue by lynochka** [explosion/spaCy#1652]
Hey, it looks like for conda on windows with  thinc 6.10.*

python -c "import thinc.neural.gpu_ops"  

does not work...

**Comment by lynochka** [comment]
For all I know,  thinc.neural.gpu_ops does not exist :)

**Comment by honnibal** [comment]
If the gpu support is built correctly, there should be a module `thinc.neural.gpu_ops`. If there's not, that means the GPU support was not built.
