### ISSUE TITLE
Adding custom items to nlp pipeline does not insert them in the correct order

### ISSUE THREAD

**Issue by demongolem** [explosion/spaCy#1654]
Using v 2.0 of spaCy with Python 2.7 on Ubuntu 14.03.  I attempt to add 2 customer annotators to the pipeline using `after`.  They do not end up in the position I would expect after the complete pipeline has been constructed.

I do as such:
```
nlp = spacy.load('en')

# Hook in your own deep learning models
print nlp.pipeline
nlp.add_pipe(first_regex, name='regex1', after='ner')
print nlp.pipeline
nlp.add_pipe(custom_model_trivial, name='useless', after='regex1')
print nlp.pipeline
```

The order goes from 

> tagger, parser, ner

to 

> tagger, parser, regex1, ner

to 

> tagger, parser, useless, regex1, ner

I would expect the order to be

> tagger, parser, ner, regex1, useless

**Comment by honnibal** [comment]
Thanks, I thought we tested this! I think the problem is almost surely when we do `after` and the referenced item is at the end. I think we probably need to trigger an `append` here instead of an `insert`.
