### ISSUE TITLE
context vector size (384) different from GloVe vectors (300)

### ISSUE THREAD

**Issue by MartinoMensio** [explosion/spaCy#1657]
I am experimenting with the different english models available for spaCy v2. I read the stuff about how OOV vectors are computed, and wondered when I discovered that the size of the context vector size on the `en_core_web_sm` appear to be of size 384, while other models (`en_core_web_md`, `en_core_web_lg`, `en_vectors_web_lg`) have vectors of size 300.

Is there any method on the spaCy classes to discover the vector size of the model, without doing a `len(span.vector)` on a parsed Span?

Example code with output to show the vector size:
```
>>> import spacy
>>> nlp = spacy.load('en_core_web_lg')
>>> 
>>> doc = nlp('I am alive')
>>> for w in doc:
...      print(w, w.is_oov, w.has_vector, len(w.vector))
... 
I False True 300
am False True 300
alive False True 300
>>> nlp = spacy.load('en_core_web_sm')
>>> 
>>> doc = nlp('I am alive')
>>> for w in doc:
...      print(w, w.is_oov, w.has_vector, len(w.vector))
... 
I True True 384
am True True 384
alive True True 384
```

## My Environment
I have spacy 2.0.3 installed, with models version 2.0.0
```
spacy validate

    Installed models (spaCy v2.0.3)
    /home/botcycle/spacy_experiment/venv/lib/python3.5/site-packages/spacy

    TYPE        NAME                  MODEL                 VERSION                                   
    package     en-core-web-lg        en_core_web_lg        2.0.0    ✔      
    package     en-core-web-sm        en_core_web_sm        2.0.0    ✔      
    package     en-vectors-web-lg     en_vectors_web_lg     2.0.0    ✔      
    link        en                    en_core_web_sm        2.0.0    ✔      
    link        en_vectors_web_lg     en_vectors_web_lg     2.0.0    ✔      
    link        en_core_web_lg        en_core_web_lg        2.0.0    ✔ 
```

**Comment by honnibal** [comment]
I'm not very happy with the API around this stuff at the moment. It's very tricky to give people access to the context vectors *and* the word vectors in a way that's not confusing, so if you have suggestions, they'd be welcome.

The least computationally expensive way to discover the dimensionality of the context vectors is `doc.tensor.shape[1]`, or `span.doc.tensor.shape[1]` if you're holding a span.

**Comment by MartinoMensio** [comment]
Thanks very much for the answer.
My only suggestion would be to possibly have the dimensionality to be exposed inside the Language.meta['vectors'], but don't know if this is feasible.

**Comment by MartinoMensio** [comment]
Always about those context vectors, is it possible to get one of them for a OOV word when the used model is not a `_sm` one?

As I can see, only `_sm` models use context vectors, while other models use precomputed GloVe vectors but are not able to return values>0 for OOV words.

Thanks in advance, I didn't find those details in the docs.

**Comment by enerrio** [comment]
I also noticed that when you feed texts to a pipeline then the vectors attribute comes out as (128,) for some reason. Instead of (384,).

```python
nlp = spacy.load('en_core_web_sm')

test = nlp(text_list[0])
print(test.vector.shape)  # Output is (384,)

for doc in nlp.pipe(text_list[:100]):
    print(doc.vector.shape)    # Output for each doc is (128,)
```

**Comment by honnibal** [comment]
You can access the context vector through the `doc.tensor` attribute. I'm not really happy with the current state of this though --- I'm not sure it's useful, so it will probably change in future versions.
