### ISSUE TITLE
error with spacy.tokens.span.Span'

### ISSUE THREAD

**Issue by tamerahsgs** [explosion/spaCy#1658]
I have started using spacy recently and i am getting this line of error that object has no attribute get_dependants? Is there a way to fix this?

in opinion_extractor(aspect_token, parsed_sentence)
11
12 #Check for Negative Opinions
---> 13 for negation in parsed_sentence.get_dependants(aspect_token):
14 if negation.deprel == "neg":
15 negation_check = True

AttributeError: 'spacy.tokens.span.Span' object has no attribute 'get_dependants'

* Operating System: MacBook Pro version 10.13.1
* Python Version Used: notebook 5.0.0
* spaCy Version Used: spacy 1.9.0
* Environment Information:

**Comment by honnibal** [comment]
Is that your own code? I don't think we've ever had a method named that on the `doc`, `span` or `token` objects, o I think the problem probably isn't within spaCy.
