### ISSUE TITLE
error with spacy.tokens.span.Span

### ISSUE THREAD

**Issue by tamerahsgs** [explosion/spaCy#1662]
I have started using spacy recently and i am getting this line of error that object has no attribute for most of my code when creating an opinion extractor? Is there a way to fix this?

def opinion_extractor(aspect_token, parsed_sentence):

    opinions = []
     #initiating global use for opinions
    n_check = False
    a_check = True
    amod_token = None
    neg_check = False
    negation_check = False
    n_check2 = False
    
    #Check for Negative Opinions
    for negation in parsed_sentence.get_dependants(aspect_token):
        if negation.deprel == "neg":
            negation_check = True
            #checks if the dependant relation has a 'neg' PoS (Part of Speech) tag
            # If it does, the check becomes True.
    if negation_check:
        for d in parsed_sentence.get_dependants(aspect_token):
            if d.deprel == "amod": 
                amod_token = d 
                #Eliminated opinion based on negation
                opinions.append("not-" + amod_token.form)
    if negation_check == False:
        for d in parsed_sentence.get_dependants(aspect_token):
            if d.deprel == "amod":
                amod_token = d
                opinions.append(amod_token.form)
            
    head_token = parsed_sentence.get_head(aspect_token)
    if head_token.pos == "JJ":
        #head token PoS is equal to "JJ"
        JJ_deps = parsed_sentence.get_dependants(head_token)
        for negs in JJ_deps:
            if negs.deprel == "neg":
                n_check = True
                #Eliminated opinion in head token based on negation check
        if n_check:
            opinions.append("not-" + head_token.form)
        if n_check == False:
            opinions.append(head_token.form)
    
    h_token = parsed_sentence.get_head(aspect_token)
    if h_token.pos == "JJ":
        JJ_deps2 = parsed_sentence.get_dependants(h_token)
        for n_dep in JJ_deps2:
            if n_dep.deprel == "neg":
                neg_check = True
        if neg_check:
            for dep in JJ_deps2:
                if dep.deprel == "advmod":
                    for o in opinions:
                        if o == head_token.form or o == "not-" + head_token.form:
                            opinions.remove(o)
                    opinions.append("not-" + dep.form + "-" + h_token.form)
        if neg_check == False:
            for dep in JJ_deps2:
                if dep.deprel == "advmod":
                    for o in opinions:
                        if o == head_token.form:
                            #Removing eliminated opinions on identification of negation keyword
                            opinions.remove(o)
                    opinions.append(dep.form + "-" + h_token.form)
    
    dep_tokens = parsed_sentence.get_dependants(aspect_token)
    for n_token in dep_tokens:
        if n_token.deprel == "neg":
            n_check2 = True
    for dep_token in dep_tokens:
        if dep_token.pos == "JJ":
            for deps in parsed_sentence.get_dependants(dep_token):
                if deps.deprel =="advmod":
                    if amod_token != None:
                        for o in opinions:
                            if o == amod_token.form:
                                opinions.remove(o)
                    if n_check2:
                        opinions.append("not-" + deps.form + "-" + dep_token.form)
                    if n_check2 == False:
                        opinions.append(deps.form + "-" + dep_token.form)
    
    conj = parsed_sentence.get_head(aspect_token)
    conjs = parsed_sentence.get_dependants(conj)
    ct = None
    nc_check = False
    for c in conjs:
        if c.deprel == "neg":
            nc_check = True
    if nc_check:
        for conj_t in conjs:
            if conj_t.deprel == "conj" and conj_t.form != aspect_token.form:
                ct = conj_t
                opinions.append("not-" + ct.form)
    if nc_check == False:
        for conj_t in conjs:
            if conj_t.deprel == "conj"and conj_t.form != aspect_token.form:
                ct = conj_t
                opinions.append(ct)
        
            
    nc_check2 = False
    t_conj = parsed_sentence.get_head(aspect_token)
    conj_tokens = parsed_sentence.get_dependants(t_conj)
    for conj_token in conj_tokens:
        if conj_token.deprel == "conj":
            #checks if the dependant relation has a conjunction PoS
            for nc_token in parsed_sentence.get_dependants(conj_token):
                    if nc_token.deprel == "neg":
                        nc_check2 = True
                        #checks if the dependant relation has a 'neg' PoS (Part of Speech) tag
                        ## If it does, the check2 becomes True.
            for c_token in parsed_sentence.get_dependants(conj_token):
                if c_token.deprel == "advmod":
                    #checks if there is a "advmod" that has a dependant realtion with the token
                    if ct != None:
                        for o in opinions:
                            if o == ct.form:
                                opinions.remove(o)
                    if nc_check2:
                        opinions.append("not-" + c_token.form + "-" + conj_token.form)
                    if nc_check2 == False:
                        opinions.append(c_token.form + "-" + conj_token.form)

    return opinions

<ipython-input-6-b06804e3c43a> in opinion_extractor(aspect_token, parsed_sentence)
     11 
     12     #Check for Negative Opinions
---> 13     for negation in parsed_sentence.get_dependants(aspect_token):
     14         if negation.deprel == "neg":
     15             negation_check = True

AttributeError: 'spacy.tokens.span.Span' object has no attribute 'get_dependants'

Operating System: MacBook Pro version 10.13.1
Python Version Used: notebook 5.0.0
spaCy Version Used: spacy 1.9.0

**Comment by cmward** [comment]
This was answered for you: https://github.com/explosion/spaCy/issues/1658

There is no `get_dependants` method on spans, so the way you fix it is to write that method. If you want the dependents for a token, you can just use `list(token.children)`.
