### ISSUE TITLE
tagger.tag_names attribute in Spacy 2.0.3

### ISSUE THREAD

**Issue by mojesty** [explosion/spaCy#1666]
I have the following problem: after running the code that required `Spacy 1.x` (the author didn't provide the exact version in the repo where I cloned this) with `Spacy 2.0.3` (`Python 3.5.2`) I received the following error message:
```
Traceback (most recent call last):
  File "prepro.py", line 243, in <module>
    vocab_tag = list(nlp.tagger.tag_names)
AttributeError: 'Tagger' object has no attribute 'tag_names'
```
Either Spacy's docs or the introspection via `dir` didn't help me to find how to fix it for my version of Spacy. Is there an opportunity to run my code w/o downgrading?

**Comment by honnibal** [comment]
Try `nlp.tagger.labels`?
