### ISSUE TITLE
Spacy Dependency parsing for "His"word

### ISSUE THREAD

**Issue by hemanth1991** [explosion/spaCy#1675]
How would i differentiate "His" word in any sentence as a Determiner or as a Pronoun in Spacy, because if i give word.dep_ for "his" word it will give as poss (possession modifier) in both cases.

for Example:
u"Ronaldo was diagnosed with a deadly disease. His disease only came to public when he was at the age of 19"  here His is Pronoun
u"Hemanth and his friends went to Coorg"  here his is a Determiner

Kindly Help

**Comment by honnibal** [comment]
You can always walk up the tree and check the dependency of the head, e.g. `word.head.dep_`

As a point of detail, the grammar schemes I've worked with would assign the same lexical category to both those uses of `his`. Why distinguish these? Seems quite useless to me.
