### ISSUE TITLE
What is good tagging practice regarding training spaCy NER model? With specific scenario questions

### ISSUE THREAD

**Issue by Zhenshan-Jin** [explosion/spaCy#1679]
Hi Matthew/Ines,  

Thanks for building such a great NLP package and putting all these NLP functionalities together, following the 500 training size rule I have already get some workable model, which is so exciting! :)

When I'm trying to gather more training data for the NER model, I meet some confusion regarding what is the best practice to follow in order to get data and let my model learn how to retrieve the information that I want from the text. Here is the scenario:  
#### Example:   
`Jack has lived in China, France, and U.S.`. Our goal is to get all the places that Jack has lived.   
#### Ways to tag:
 - Taking each of the countries in `China, France, and U.S` as separate entities, e.i.  
 `China[Lived_by_Tome]`, `France[Lived_by_Tom]`, `U.S.[Lived_by_Tome]`   
 -  Taking them as a whole, say `China, France, and U.S.[Lived_by_Tom]`    

My understanding is that in the first tagging manner, by being more specific, we can get more training data and flexibility, since `China, France, and U.S.` is too strict phrases. Is there also some advantage regarding the NLP algorithm? like spaCy will tend to take `China`, `France`, `U.S.` as separate word trunk instead of taking them as one.

#### Example:   
`Tom lived in Kempten, southern Germany`. If we want to retrieve both `Kempten` as a location entity and also `southern Germany` which is critical information to locate `Kempten` if it is not a famous place. What should we do with it?   
#### Ways to tag: 
- `Kempten, southern Germany[LOC]`  
- `Kempten[LOC]`  
If in a second way, do you have any good suggestion about retrieving the lost information within `southern Germany`? 

#### Example:   
`Kentucky Fried Chicken(KFC) is one of the most famous fried chicken restaurant`. If we want to get the restaurant name `Kentucky Fried Chicken` and also `KFC`, since we know that in the following article, it's almost sure that `KFC` will be used to refer the restaurant instead of the full name `Kentucky Fried Chicken`.   
#### which way is preferred by spaCy?   
 - `Kentucky Fried Chicken(KFC)[Restaurant]`
 - `Kentucky Fried Chicken[Restaurant]` `(KFC)[Restaurant Abbreviation]`  

I'm a newbie in NLP domain, any suggestions about how to design tagging rules to 
- better fit for spaCy NER training algorithm
- retrieve information inside unstructured text data
would be appreciated!

Sorry for the length of the problem. Want to learn real NLP from your guys :P

Cheers,
Zhenshan

## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used: 2.0.3
* Environment Information:

**Comment by ahalterman** [comment]
My hunch (and correct me if I'm wrong!) is that it's probably better to separate out the NER step and the binary relation step. That lets you use out of the box NER models, perhaps with some minor tweaking, and then build a wholly custom model for relation extraction. The new 2.0 model uses the word embeddings of the sentence, but I don't think uses any sort of parse information (https://www.youtube.com/watch?v=sqDHBH9IjRU). The models like the ones you're talking about will almost certainly need some more grammar and dependency-type features, which will probably be easier in a separate model.

Specifically on the location lookup question, I think it's better to get locations separately and then model the relationship between them. Once you go to look them up in a gazetteer you'll need them to be separate anyway, so better to keep the NER as-is and learn a separate "comma group" detector that tells you which LOC/GPE is located within a larger LOC/GPE. I'm working on exactly this task and I think it's pretty doable with enough data.

And I've had the same question, too, on "Kentucky Fried Chicken (KFC)", though again, I think better to separate and model the relationship. 

Someone chime in if this isn't good advice...

**Comment by Zhenshan-Jin** [comment]
@ahalterman 
Thank you so much for sharing the idea about how to tackle the problem.
The modeling strategy mentioned in the video is really helped in designing the

**Comment by Zhenshan-Jin** [comment]
@ahalterman 
Thank you so much for sharing the idea about how to tackle the problem and the video.
The model insight in the video is very helpful to make the final decision about how to solve this "Incomplete entity" problem.   

Finally, I decided to try both ways:   
1. Treating "China, France, and U.S." as one entity like Countries group  
2. Treating "China", "France" and "U.S." separately.   

The 2nd strategy works here, but in another example "Eiffel, Trump and Pisa Learning Tower", if we treat Eiffel, Trump, and Pisa Learning separately, I'm not sure whether NER will still recognize Trump as a tower or a president. And this problem can be solved the first strategy and then split them into 3 sub-entities. The reason that I think probably it'll work is that from the video, Hannibal said that the NER model is a transition model which built on the information from the 4 words in each side, which means that the NER model gets the potential ability to learn this kind of group entities.   What do you think?
I'm not sure, still, some experiments need to do. Will updates when getting some more interesting ideas
