### ISSUE TITLE
shutil.Error when loading new entity

### ISSUE THREAD

**Issue by akshay-1993** [explosion/spaCy#1681]
python -m spacy package /newModel /newModel/Model

    Loaded meta.json from file
    \newModel\meta.json

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\lib\site-packages\spacy\__main__.py", line 30, in <module>
    plac.call(commands[command])
  File "C:\Program Files\Python36\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "C:\Program Files\Python36\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\spacy\cli\package.py", line 55, in package
    path2str(package_path / model_name_v))
  File "C:\Program Files\Python36\lib\shutil.py", line 359, in copytree
    raise Error(errors)
shutil.Error: [('\\newModel\\Model\\en_ANATOMY-2.0.0\\en_ANATOMY\\en_ANATOMY-2.0.0\\Model\\en_ANATOMY-2.0.0\\en_ANATOMY\\en_ANATOMY-2.0.0\\Model\\en_ANATOMY-2.0.0\\en_ANATOMY\\en_ANATOMY-2.0.0\\Model\\en_ANATOMY-2.0.0\\en_ANATOMY', '\\newModel\\Model\\en_ANATOMY-2.0.0\\en_ANATOMY\\en_ANATOMY-2.0.0\\Model\\en_ANATOMY-2.0.0\\en_ANATOMY\\en_ANATOMY-2.0.0\\Model\\en_ANATOMY-2.0.0\\en_ANATOMY\\en_ANATOMY-2.0.0\\Model\\en_ANATOMY-2.0.0\\en_ANATOMY\\en_ANATOMY-2.0.0\\Model\\en_ANATOMY-2.0.0\\en_ANATOMY', "[WinError 206] The filename or extension is too long: '\\\\newModel\\\\Model\\\\en_ANATOMY-2.0.0\\\\en_ANATOMY\\\\en_ANATOMY-2.0.0\\\\Model\\\\en_ANATOMY-2.0.0\\\\en_ANATOMY\\\\en_ANATOMY-2.0.0\\\\Model\\\\en_ANATOMY-2.0.0\\\\en_ANATOMY\\\\en_ANATOMY-2.0.0\\\\Model\\\\en_ANATOMY-2.0.0\\\\en_ANATOMY\\\\en_ANATOMY-2.0.0\\\\Model\\\\en_ANATOMY-2.0.0\\\\en_ANATOMY'")]

## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.6.2
* spaCy Version Used: 2.0.0
* Environment Information:

**Comment by ines** [comment]
I think the problem here is that you end up with a recursion because your output directory is *within* your input directory. The `package` command copies the files from the input directory to the output directory, adds all required Python files and then packages it. But because it's copying *into* the directory it's copying *from*, it never stops.

So just choose a different output path, for example:

```bash
python -m spacy package /newModel /newModelPackage
```
