### ISSUE TITLE
Which dependency labels are used by which models?

### ISSUE THREAD

**Issue by mkdynamic** [explosion/spaCy#1682]
Specifically, I'm wondering which dependency label set are used by the EN models. I suspect I am missing it, but I've read https://spacy.io/api/annotation#section-dependency-parsing and https://spacy.io/models/en and it's unclear. Is there a reference for which set of dependency labels are used by which of the EN models?

**Comment by ines** [comment]
The English models are trained on the the OntoNotes 5 corpus and all use the CLEAR style for dependency labels. You can see the full list of labels here: https://spacy.io/api/annotation#dependency-parsing-english (You should be able to click on "English" and expand the section to show the full table).

I just saw you also submitted the PR fixing the PDF link (thanks btw!) so I assume you've found the solution. Closing this, but feel free to update/reopen if there's anything else that's still unclear 😊

**Comment by mkdynamic** [comment]
Thanks @ines! I was unsure whether the EN models used the Universal Dependency Labels, but it all makes sense now :)
