### ISSUE TITLE
Can't load the new french model : OverflowError

### ISSUE THREAD

**Issue by frankl1** [explosion/spaCy#1685]
Hi
I'm new to spacy and I'm facing some issues with the latest french model

First of all the model failed loading after installation giving me a file not found exception, here is my trace

> ---------------------------------------------------------------------------
> FileNotFoundError                         Traceback (most recent call last)
> <ipython-input-98-2eac0ea8c9b6> in <module>()
>       1 import spacy
>       2 
> ----> 3 nlp = spacy.load('fr_core_news_sm')
> 
> /usr/local/lib/python3.5/dist-packages/spacy/__init__.py in load(name, **overrides)
> 
> /usr/local/lib/python3.5/dist-packages/spacy/language.py in __init__(self, **overrides)
>     263             self.pipeline.insert(self.pipe_names.index(after), pipe)
>     264         else:
> --> 265             msg = "Can't find '{}' in pipeline. Available names: {}"
>     266             unfound = before or after
>     267             raise ValueError(msg.format(unfound, self.pipe_names))
> 
> /usr/local/lib/python3.5/dist-packages/spacy/language.py in create_vocab(cls, nlp)
>      40     @classmethod
>      41     def create_vocab(cls, nlp=None):
> ---> 42         lemmatizer = cls.create_lemmatizer(nlp)
>      43         lex_attr_getters = dict(cls.lex_attr_getters)
>      44         # This is messy, but it's the minimal working fix to Issue #639.
> 
> /usr/local/lib/python3.5/dist-packages/spacy/vocab.pyx in spacy.vocab.Vocab.load (spacy/vocab.cpp:4742)()
> 
> /usr/lib/python3.5/pathlib.py in open(self, mode, buffering, encoding, errors, newline)
>    1149             self._raise_closed()
>    1150         return io.open(str(self), mode, buffering, encoding, errors, newline,
> -> 1151                        opener=self._opener)
>    1152 
>    1153     def read_bytes(self):
> 
> /usr/lib/python3.5/pathlib.py in _opener(self, name, flags, mode)
>    1003     def _opener(self, name, flags, mode=0o666):
>    1004         # A stub for the opener argument to built-in open()
> -> 1005         return self._accessor.open(self, flags, mode)
>    1006 
>    1007     def _raw_open(self, flags, mode=0o777):
> 
> /usr/lib/python3.5/pathlib.py in wrapped(pathobj, *args)
>     369         @functools.wraps(strfunc)
>     370         def wrapped(pathobj, *args):
> --> 371             return strfunc(str(pathobj), *args)
>     372         return staticmethod(wrapped)
>     373 
> 
> FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/dist-packages/spacy/data/fr_core_news_sm/vocab/strings.json'

I correct that error by make the symbolic point on **/usr/local/lib/python3.5/dist-packages/spacy/data/fr_core_news_sm/fr_core_news_sm-2.0.0** instead of **/usr/local/lib/python3.5/dist-packages/spacy/data/fr_core_news_sm**

After that an overflow exception occured and here is the trace

> ---------------------------------------------------------------------------
> OverflowError                             Traceback (most recent call last)
> <ipython-input-99-d26115b40010> in <module>()
>       1 import spacy
>       2 
> ----> 3 nlp = spacy.load('fr_core_news_sm')
> 
> /usr/local/lib/python3.5/dist-packages/spacy/__init__.py in load(name, **overrides)
> 
> /usr/local/lib/python3.5/dist-packages/spacy/language.py in __init__(self, **overrides)
>     263             self.pipeline.insert(self.pipe_names.index(after), pipe)
>     264         else:
> --> 265             msg = "Can't find '{}' in pipeline. Available names: {}"
>     266             unfound = before or after
>     267             raise ValueError(msg.format(unfound, self.pipe_names))
> 
> /usr/local/lib/python3.5/dist-packages/spacy/language.py in create_vocab(cls, nlp)
>      40     @classmethod
>      41     def create_vocab(cls, nlp=None):
> ---> 42         lemmatizer = cls.create_lemmatizer(nlp)
>      43         lex_attr_getters = dict(cls.lex_attr_getters)
>      44         # This is messy, but it's the minimal working fix to Issue #639.
> 
> /usr/local/lib/python3.5/dist-packages/spacy/vocab.pyx in spacy.vocab.Vocab.load (spacy/vocab.cpp:4974)()
> 
> /usr/local/lib/python3.5/dist-packages/spacy/vocab.pyx in spacy.vocab.Vocab.load_lexemes (spacy/vocab.cpp:9653)()
> 
> /usr/local/lib/python3.5/dist-packages/spacy/strings.pyx in spacy.strings.StringStore.__getitem__ (spacy/strings.cpp:2470)()
> 
> OverflowError: can't convert negative value to uint64_t

## Your Environment

* Operating System: Ubuntu 16.04
* Python Version Used: 3.5
* spaCy Version Used: 2.0.3

**Comment by honnibal** [comment]
Should be fixed now. Try again with the latest `spacy-nightly`.
