### ISSUE TITLE
SyntaxError: (unicode error) 'rawunicodeescape' codec can't decode bytes in position 2-3: truncated \uXXXX

### ISSUE THREAD

**Issue by hoyeunglee** [explosion/spaCy#1690]
>>> nlp.to_disk(r'C:\Users\martlee2\Documents\model')
  File "<stdin>", line 1
SyntaxError: (unicode error) 'rawunicodeescape' codec can't decode bytes in position 2-3: truncated \uXXXX

how to save result?

**Comment by honnibal** [comment]
I think this is a problem with the way you've written the path. I'm not 100% sure of what the right way to do this is on Windows, but the combination of the r before the string and the way you've got the backslashes is definitely wrong.
