### ISSUE TITLE
English models (1.2) give different outputs for the same input

### ISSUE THREAD

**Issue by hitvoice** [explosion/spaCy#1693]
Code to reproduce the issue:
```python
import spacy
from collections import Counter
text = '''Paul VI was concerned but not surprised by the negative reaction in Western Europe and the United States. He fully anticipated this reaction to be a temporary one: "Don't be afraid", he reportedly told Edouard Gagnon on the eve of the encyclical, "in twenty years time they'll call me a prophet." His biography on the Vatican's website notes of his reaffirmations of priestly celibacy and the traditional teaching on contraception that "[t]he controversies over these two pronouncements tended to overshadow the last years of his pontificate". Pope John Paul II later reaffirmed and expanded upon Humanae vitae with the encyclical Evangelium vitae.'''
nlp = spacy.load('en') # or 'en-md' 
lemma = []
for _ in range(10):
    doc = nlp(text)
    lemma.append(doc[32].lemma_)
print(Counter(lemma))
```
The result is:
```
Counter({"n't": 9, 'not': 1})
```

## Info about spaCy
* **spaCy version:** 1.10.0
* **Platform:** Linux-4.10.0-41-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.1
* **Installed models:** en, en-md

## Info about model en

* **name:** core_web_sm
* **lang:** en
* **version:** 1.2.0
* **spacy_version:** >=1.7.0,<2.0.0
* **description:** Small English model for spaCy. Includes vocabulary, syntax, entities and word vectors (GloVe).
* **author:** Explosion AI
* **email:** contact@explosion.ai
* **url:** https://explosion.ai
* **license:** CC BY-SA 3.0
* **source:** /home/rqyang/anaconda3/lib/python3.6/site-packages/en_core_web_sm/en_core_web_sm-1.2.0

## Info about model en-md

* **lang:** en
* **name:** core_web_md
* **license:** CC BY-SA 3.0
* **author:** Explosion AI
* **url:** https://explosion.ai
* **version:** 1.2.1
* **spacy_version:** >=1.7.0,<2.0.0
* **email:** contact@explosion.ai
* **description:** General-purpose English model, with tagging, parsing, entities and word vectors
* **source:** /home/rqyang/anaconda3/lib/python3.6/site-packages/en_core_web_md/en_core_web_md-1.2.1

In spaCy 2.0 this problem does not occur. Currently models in spaCy 2.0 are much slower than 1.x models, so many people may still rely on the latter.

**Comment by ines** [comment]
Merging this with #2493!
