### ISSUE TITLE
Lemmatization question

### ISSUE THREAD

**Issue by danielhers** [explosion/spaCy#1696]
I'm not sure if this is a bug or not, but starting with the latest spaCy version, it's not lemmatizing some words I expect it to.
For example:

    import spacy
    nlp = spacy.load("en")
    nlp("Mr. Vinken is chairman of Elsevier N.V. , the Dutch publishing group .")[-3].lemma_
    >> 'publishing'
    nlp("Mr. Vinken is chairman of Elsevier N.V. , the Dutch eating group .")[-3].lemma_
    >> 'eat'
    nlp("publishing")[0].lemma_
    >> 'publish'

The last two results are as I would expect, but for the first one I would expect to get 'publish', and this is what older spaCy versions returned.
Is this just some black box NN change, or can it be explained?

## Info about spaCy

* **Platform:** Linux-4.8.4-aufs-1-x86_64-with-debian-stretch-sid
* **spaCy version:** 2.0.5
* **Python version:** 3.5.2+
* **Models:** en_core_web_sm, en_core_web_lg, fr_core_news_md, en_core_web_md, en, de_core_news_sm, de

**Comment by honnibal** [comment]
Sorry for not getting to this sooner.

I think this is ultimately a part-of-speech tagging error. If `publishing` is tagged as a noun or adjective, the lemmatizer won't be applied to it, because the `-ing` rule only applies to verbs.
