### ISSUE TITLE
Unexpected behavior of tensor and token vectors under save/restore.

### ISSUE THREAD

**Issue by cbrew** [explosion/spaCy#1699]
Is this a bug or feature request? If a bug, include all the steps that led to the issue.

Probably a bug. The behavior I got was unexpected.

It looks to me as if when you save and restore a document, the tensor gets saved
correctly, but the token vectors in the saved document are not passed through.
Instead, the token vectors in the stored document appear to be slices of the tensor.
See script below.

```
import numpy as np
import spacy
nlp = spacy.load('en_core_web_lg')

def tokvec(doc):
    return np.vstack([tok.vector for tok in doc])

print("spacy version:",spacy.__version__)
doc = nlp('mary likes relative pronouns')
tv = tokvec(doc)
doc.to_disk('mary.dat')
doc = Doc(Vocab()).from_disk('mary.dat')
tv2 = tokvec(doc)
for x,y,z in zip(doc.tensor.mean(axis=0),tv.mean(axis=0),tv2.mean(axis=0)):
    print(x, y, z)
```

## Info about spaCy

* **spaCy version:** 2.0.4
* **Platform:** Linux-4.10.0-40-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.3
* **Models:** en_core_web_lg, en, en_core_web_sm

**Comment by honnibal** [comment]
When you're resuming, the vocab you're creating doesn't have the word vectors. Without the word vectors, `token.vector` is fulfilled via the tensor.

I'm not very happy with this, but I've struggled to come up with a design for the tensor and the word vectors that is maximally useful and minimally confusing.

**Comment by honnibal** [comment]
Further discussion in #1701
