### ISSUE TITLE
em-dash receives empty POS tag with 'en' models

### ISSUE THREAD

**Issue by rgabbard** [explosion/spaCy#1700]
The `EM DASH` character receives an empty POS tags, both coarse and fine, in the 'en' models for spacy 2.0.3:

In 2.0.3:
```
>>> import spacy
>>> nlp = spacy.load('en')
>>> x = nlp('hello — world')
>>> x.print_tree()
[{'word': 'hello', 'lemma': 'hello', 'NE': '', 'POS_fine': 'UH', 'POS_coarse': 'INTJ', 'arc': 'ROOT', 'modifiers': [{'word': '—', 'lemma': '—', 'NE': '', 'POS_fine': '', 'POS_coarse': '', 'arc': 'punct', 'modifiers': []}, {'word': 'world', 'lemma': 'world', 'NE': '', 'POS_fine': 'NN', 'POS_coarse': 'NOUN', 'arc': 'npadvmod', 'modifiers': []}]}]
```

But in 1.9.0:

```
>>> import spacy
>>> nlp = spacy.load('en')
>>> x = nlp('hello — world')
>>> x.print_tree()
[{'word': 'hello', 'lemma': 'hello', 'NE': '', 'POS_fine': 'UH', 'POS_coarse': 'INTJ', 'arc': 'ROOT', 'modifiers': [{'word': '—', 'lemma': '—', 'NE': '', 'POS_fine': ':', 'POS_coarse': 'PUNCT', 'arc': 'punct', 'modifiers': []}, {'word': 'world', 'lemma': 'world', 'NE': '', 'POS_fine': 'NN', 'POS_coarse': 'NOUN', 'arc': 'appos', 'modifiers': []}]}]
```

## Info about spaCy

* **spaCy version:** 2.0.3
* **Platform:** Darwin-17.2.0-x86_64-i386-64bit
* **Python version:** 3.6.3
* **Models:** en

**Comment by rgabbard** [comment]
hmm - it's actually a little more complicated. If we take the 2.03 example above and then do:

```
>> for word in x:
...     print(word)
...     print(word.pos)
...     print(word.pos_)
...     print(word.tag)
...     print(word.tag_)
...
hello
90
INTJ
3252815442139690129
UH
—
96
PUNCT
0

world
91
NOUN
15308085513773655218
NN
```

So `pos_` is correctly `PUNCT` but `tag_` is still empty.

**Comment by adrianeboyd** [comment]
This problem doesn't seem to be English-specific. I've also tried several other languages (German, Spanish, Portuguese) and the tags for em dash are all empty.

**Comment by IsabelMeraner** [comment]
I have the same problem with empty tags for German:

```
import spacy
nlp = spacy.load('de_core_news_sm')
doc = nlp(sentence_string)
print(doc)

for token in doc:
        print(token.text, token.lemma_, token.pos_, token.tag_, token.dep_, token.shape_, token.is_alpha, token.is_stop)
```


results in:

```
Der nach aussen und abwärts kippende Baum traf haargenau auf eine nahe Tanne , konnte nicht weiter fallen , sondern verklemmte sich so , dass auch der ganze Wurzelkuchen haltmachte .


Der     Xxx True True
nach     xxxx True True
aussen     xxxx True False
und     xxx True True
abwärts     xxxx True False
kippende     xxxx True False
Baum     Xxxx True False
traf     xxxx True False
haargenau     xxxx True False
auf     xxx True True
eine     xxxx True True
nahe     xxxx True False
Tanne     Xxxxx True False

```
... which means that only token.shape_, token.is_alpha, token.is_stop have an actual return value, all the others seem to be empty strings.

Do you have any suggestions on how to fix this issue or is there another workaround?

Thank you so much.

**Comment by ines** [comment]
@IsabelMeraner

> ... which means that only token.shape_, token.is_alpha, token.is_stop have an actual return value, all the others seem to be empty strings.

That's strange and basically means that the model isn't predicting anything... 🤔 It makes sense that the lexical attributes all exist, because those aren't predicted by the model.

Could you run `python -m spacy validate` and check the output for the German model? Issues like this can potentially point to a version incompatibility.

**Comment by IsabelMeraner** [comment]
@ines 

> Could you run python -m spacy validate and check the output for the German model? Issues like this can potentially point to a version incompatibility.

I just upgraded to spacy version 2.0.12 in order to be able to run the validate option. That's what I get:

$ spacy --info

    Info about spaCy
    Models
    Python version     3.5.2
    spaCy version      2.0.12
    Location           /Users/isabelmeraner/anaconda/lib/python3.5/site-packages/spacy
    Platform           Darwin-17.7.0-x86_64-i386-64bit`

$ python -m spacy validate

    `Installed models (spaCy v2.0.12)
    /Users/isabelmeraner/anaconda/lib/python3.5/site-packages/spacy

    TYPE        NAME                  MODEL                 VERSION
    package     de-core-news-md       de_core_news_md       1.0.0    --> n/a
    package     en-core-web-sm        en_core_web_sm        1.2.0    --> 2.0.0

    Use the following commands to update the model packages:
    python -m spacy download en_core_web_sm

    Use the following commands to update the model packages:


It looks like spacy 2.0.12 is incompatible with the German model, the command to update the German model packages is empty (see above). If I try to download the model for German, I get a compatibility error:

$ python -m spacy download de-core-news-md
`
    Compatibility error
    No compatible model found for 'de-core-news-md' (spaCy v2.0.12).`

What would you suggest in order to use the German model for pos-tagging? Can you provide an updated version of "de-core-news-md" for the most recent version of spaCy v2.0.12?
Thank you so much!

**Comment by ines** [comment]
It looks like you don't actually have the `_md` model installed? In your `spacy-nightly` environment, try running `python -m spacy download de_core_news_md`!

**Comment by IsabelMeraner** [comment]
@ines Of course, it was only installed in the other environment. Now it works fine on the bigger dataset. Thanks again for your help!

**Comment by kuchenrolle** [comment]
I'm using spacy 2.0.13 and have the compatible model en_core_web_lg 2.0.0 installed, but I still get an empty tag for  "—" in the sentence: "11.00am — Tony has been given an appointment at the local hospital."

I'm running it on Python 3.6.2 with IPython 6.1.0. And I get the same behaviour from the _sm model (also 2.0.0).

**Comment by ines** [comment]
Merging this with #3052. We've now added a master thread for incorrect predictions and related reports – see the issue for more details.
