### ISSUE TITLE
displaCy - Fine-grained (.tag_) not coarse-grained (.pos_) POS tags in the tree

### ISSUE THREAD

**Issue by gppatt** [explosion/spaCy#1703]
Didn't the dependency tree used to show the fine-grained token part-of-speech tags?  Now, it only shows the basic POS tags. It would be terrific if we could see the fine-grained ones (in addition to, or replacing, the coarse-grained ones). Thanks...

**Comment by ines** [comment]
Yes, that's correct – the reason we had to switch this recently is that some of the new models use fine-grained part-of-speech tags that are composed of the morphological features. This makes them pretty difficult to visualise – at least, we couldn't yet think of a good solution for this.

Here's an example from the Italian thread #1006:
![](https://user-images.githubusercontent.com/11597393/32952025-2f2f2930-cbac-11e7-9c49-67d29fc66433.png)

If you're using the built-in `displacy` module, it's easy to change it though – see my commit here: 60b4915569c891675ed5dc86ff40a7a2587841d1 To be honest, I should have probably made this a setting in the displaCy options – it could use `.pos_` by default so users don't get too confused, but if you do want to see the fine-grained tags, you can set `fine_grained=True` or something like that. Will add this for the next release!

**Comment by gppatt** [comment]
Great - thanks for such a fast response, Ines. :)
