### ISSUE TITLE
Similarity between two same words is shown as 0.0

### ISSUE THREAD

**Issue by TrivedhK** [explosion/spaCy#1704]
Similarity between two same words is shown as 0.0 despite using the heavy model "en_core_web_lg"
![spacy](https://user-images.githubusercontent.com/14237706/33792102-ea5b8074-dcbd-11e7-85c2-eb1905c3b4bd.PNG)

```
import spacy
nlp = spacy.load('en_core_web_lg')
doc1=nlp(u'CDASH')
doc2=nlp(u'CDASH')
print(doc2.similarity(doc1))

```
Result: 0.0

* Operating System: Windows 10 Home
* Python Version Used: 3.6.3
* spaCy Version Used: 2.0
* Environment Information: Local

**Comment by mkrump** [comment]
Having a similar issue. Trying to repeat the example from the docs (https://spacy.io/usage/vectors-similarity) results in the output below.
```
import spacy
nlp = spacy.load('en_core_web_lg')
doc1 = nlp(u"Paris is the largest city in France.")
doc2 = nlp(u"Vilnius is the capital of Lithuania.")
doc3 = nlp(u"An emu is a large bird.")

for doc in [doc1, doc2, doc3]:
    for other_doc in [doc1, doc2, doc3]:
        print(doc.similarity(other_doc))
```

|                             |                             |                             |
| ------------- | ------------- | ------------- |
-0.0202081899334 | 0.0 |8.9066711848e-22
0.0 | 0.0164478826265 | 0.0
8.9066711848e-22 | 0.0 | -2.46412418442e+17

-----------------------------------------------------
    Info about spaCy

    spaCy version      2.0.3
    Platform           Darwin-17.2.0-x86_64-i386-64bit
    Python version     3.6.3
    Models             en_core_web_lg, en

**Comment by aneeshvartakavi** [comment]
I'm also seeing strange behavior for token similarity with three English models (sm,md and lg).

<img width="652" alt="screen shot 2018-01-09 at 3 32 51 pm" src="https://user-images.githubusercontent.com/4122476/34748700-a3bd2eee-f552-11e7-8737-878c2ac472e6.png">

```
    Info about spaCy

    spaCy version      2.0.5
    Platform           Darwin-17.3.0-x86_64-i386-64bit
    Python version     3.6.3
    Models             en_core_web_md, en_core_web_lg, en_core_web_sm

```

**Comment by honnibal** [comment]
Thanks for the report. Proposed patch: https://github.com/explosion/spaCy/pull/1845

**Comment by honnibal** [comment]
Merged.
