### ISSUE TITLE
is it possible to remove the hardcoded limit on doc lengths in the phrasematcher?

### ISSUE THREAD

**Issue by sulphide0** [explosion/spaCy#1711]
currently there is a hardcoded limit of 10 despite the presence of the max_length argument to the PhraseMatcher constructor. Is it possible to increase or remove the hardcoded limit and let us manage that limit ourselves?

the limit is imposed here:

https://github.com/explosion/spaCy/blob/1e61fffd0a3d9570a59930cd278954dea0c62b5f/spacy/matcher.pyx#L440

alternatively, is there another way to add entities to a document via pattern matching that would support longer phrases?

**Comment by honnibal** [comment]
It should be possible to do this. If you have a go, please update the thread.

**Comment by ines** [comment]
Merging this with the master issue #1971!

**Comment by rbhambriiit** [comment]
This is pretty awesome. Was really needed.
