### ISSUE TITLE
Attempting autocomplete on a token in repl spawns endless Deprecation Warnings

### ISSUE THREAD

**Issue by bsatts** [explosion/spaCy#1712]
Hitting tab in a Python REPL on a token to see the list of the attributes infinitely spawns the "Token.sent_start is now deprecated" warning. Issue seems to be because of the threading module as seen from the trace.

![deprecation_warning_loop](https://user-images.githubusercontent.com/4343985/33847731-8b2b79ca-de79-11e7-9488-a3396c6afd3c.png)

## Info about spaCy

* **spaCy version:** 2.0.5 (first noticed in 2.02 but persists after update)
* **Platform:** Linux-4.13.0-19-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.2
* **Models:** en_core_web_lg

**Comment by honnibal** [comment]
Fixed -- sorry this took so long! I was on holidays for most of December.
