### ISSUE TITLE
Potential bugs with the NER model

### ISSUE THREAD

**Issue by Zhenshan-Jin** [explosion/spaCy#1713]
1. Problem with the parenthesis dependency parsing:
The parsing result is different for different formatted input
```
Kentucky Fried Chicken (KFC) is one of the most famous fried chicken restaurant.
```
![image](https://user-images.githubusercontent.com/14370804/33855328-35bfcb1a-de8a-11e7-8259-6793323719e8.png)
```
Kentucky Fried Chicken(KFC) is one of the most famous fried chicken restaurant.
```
![image](https://user-images.githubusercontent.com/14370804/33855420-7a07a6f8-de8a-11e7-853b-af4001f07e51.png)
We can see that by removing the space between `Kentucky Fried Chicken` and `(KFC)` the parsing result is different, which, in my opinion, is not right, like `Kentucky Fried Chicken(` and `KFC)`. I guess it's probably the problem with the training data. But not sure.

2. Problem with the stability of the self-trained NER model:
I can't really show the model result here, sorry about that. The problem is that the model is unstable, like by adding some irrelevant words to the begging or the end of the paragraph, the entity being recognized by the self-trained model would be totally changed. And also the entities recognized based on paragraph and sentences is different, which should be the case based on the Transition model described by Hannibal. I'm wondering have that issue happens before. 

Thanks!

**Info about spaCy**
spaCy version: 2.0.3 
Python version: 3.6
pre-trained Models: en_core_web_md

**Comment by ines** [comment]
Merging this with #3052. We've now added a master thread for incorrect predictions and related reports – see the issue for more details.
