### ISSUE TITLE
Inconsistent parse result for sentences with double quotes between models

### ISSUE THREAD

**Issue by mehmetilker** [explosion/spaCy#1716]
Large model (en_core_web_lg) parse result gave me quote as "prep" but small model as "punct". (which is right I think.)

Sentence exampe : "Throughout our first week of basic training..."

en_core_web_sm
"    punct     Throughout 
Throughout   ROOT    Throughout 
....

en_core_web_lg
"   punct            .
Throughout --     prep --               " 

I have just found another case for a sentence contains number, different parse result between small model and large.
In the sentence "You know, I can get that for $1 across the street."
With small model I can get "get-prep-across" dependency.
But with large model I got "1 - prep - across".

Another one: One of our own's on the inside.
small model > One - prep - on
Large model > on - prep - 's 

In all cases small model wins. If it were opposite, it would be expected but this is wrong if I did not misunderstand the situation.

## Your Environment
* **spaCy version:** 2.0.5
* **Platform:** Windows-10-10.0.16299-SP0
* **Python version:** 3.6.3
* **Models:** en, en_core_web_lg

**Comment by ines** [comment]
Merging this with #3052. We've now added a master thread for incorrect predictions and related reports – see the issue for more details.
