### ISSUE TITLE
Problems with the Portuguese model

### ISSUE THREAD

**Issue by ruiEnca** [explosion/spaCy#1718]
I am a Portuguese (European) native speaker but I have been using Spacy mainly with English texts. Recently I started a project with Portuguese texts and I have been puzzled by the low quality of some tools of the Portuguese model.
The tokenizer seems ok, but the stopwords list and, mainly, the tokenizer have so many errors that is hard to believe they were built by a native speaker (even considering the differences between the Brazilian and the European Portuguese). It seems that these files were produced automatically by a faulty algorithm.
For instance, the stopwords list does not contain the singular forms of the definite article ("**a**" and "**o**" = "the") and the conjunction "**e**" (= "and") that are the most common stopwords. But there are some additional misses and many of the contained words are not stopwords (eg: "relação" (relation), "verdadeiro" (true), noite ("night"), "mês" (month), etc....
The lemmatizer has more than 820.000 words but many of them are not valid words are many of the lemmas are totally wrong! I used a spell checker and there are some thousand mistakes. For instance, the female forms of the indefinite articles "**uma**", "**umas**" (= "a" or "an") are converted to "**umar**" that is supposed to be a verb that does not exist!!
I tried with a dataset of small sentences and many of them are totally unusable and unrecognizable after preprocessing.
If the stopwords can be easily fixed or replaced the lemmatizer is harder. For now, I will try an external tool or use the terms as they appear in the original sentence.

I am available to help to fix the model, but I think there are other more experienced users that could do a better job.

## Your Environment
* **spaCy version:** 2.0.5
* **Platform:** Windows-10-10.0.17046-SP0
* **Python version:** 3.6.3
* **Models:** en, en_core_web_lg, en_core_web_md, es, pt

**Comment by fernandascovino** [comment]
I had the same problem with the Portuguese model... I´m Brazilian, and I need a good package to get the singular form of words, but I couldn´t find it yet.

**Comment by honnibal** [comment]
Merging with #3052 , the model inaccuracies master thread.

@fernandascovino Until we are able to provide better models (with full morphology support as well), if you don't need the system to be so fast, you might find the Stanford NLP models useful. We have a spaCy wrapper for them here: https://github.com/explosion/spacy-stanfordnlp
