### ISSUE TITLE
Usage text classifier with several topics

### ISSUE THREAD

**Issue by lynochka** [explosion/spaCy#1723]
Hei, could you please provide examples where classes are not boolean? 
I am trying to use spacy train_textcat script for a problem with data similar to:

```python
training_data = 
[
('Asking about a dog', {'cats': {'TOPIC': 'dog'}}),
('Asking here about a cat',  {'cats': {'TOPIC': 'cat'}}),
('Here asking about a rabbit',  {'cats': {'TOPIC': 'rabbit'}})
]
```

Traceback (most recent call last):
  File "my_train_textcat.py", line 186, in <module>
    plac.call(main)
  File "PATH_TO_LIB/lib/python3.5/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "PATH_TO_LIB/lib/python3.5/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "my_train_textcat.py", line 98, in main
    nlp.update(texts, annotations, sgd=optimizer, drop=0.2, losses=losses)
  File "PATH_TO_LIB/lib/python3.5/site-packages/spacy/language.py", line 407, in update
    proc.update(docs, golds, drop=drop, sgd=get_grads, losses=losses)
  File "pipeline.pyx", line 818, in spacy.pipeline.TextCategorizer.update
  File "pipeline.pyx", line 830, in spacy.pipeline.TextCategorizer.get_loss
ValueError: could not convert string to float: 'dog'

Does 'cats' allow non-bool labels? Could you please give me an advice on the error if so?

## Your Environment
* **Python version:** 3.5.3+
* **Platform:** Linux-4.4.0-43-Microsoft-x86_64-with-Ubuntu-16.04-xenial
* **Models:** en
* **spaCy version:** 2.0.3

**Comment by kbogas** [comment]
I am no expert with regards to the TextCategorizer but I suppose you could change your data to according to the [example ](https://spacy.io/usage/training#section-textcat).. Using your data:
```python
training_data = [
('Asking about a dog', {'cats': {'dog': True}}),
('Asking here about a cat',  {'cats': {'cat': True}}),
('Here asking about a rabbit',  {'cats': {'rabbit': True}}) 
]
```
maybe something like this could work?

**Comment by lynochka** [comment]
It was my backup plan : }

**Comment by zihaolucky** [comment]
@kbogas seems it violates the docs from https://spacy.io/api/doc#attributes, I've tried use the format you suggest but came out a very wired outputs.

**Comment by azarezade** [comment]
@kbogas, @zihaolucky Actually if the classes are mutually exclusive you should use:
```
training_data = [
('Asking about a dog', {'cats': {'dog': True, 'cat': False, 'rabbit': False}}),
('Asking here about a cat',  {'cats': {'dog': False, 'cat': True, 'rabbit': False}}),
('Here asking about a rabbit',  {'cats': {'dog': False, 'cat': False, 'rabbit': True}}) 
]
```
which is more painful for several topic as I mentioned in #1997.

**Comment by ines** [comment]
Merging this with #1997!
