### ISSUE TITLE
speed up spacy.load('en')

### ISSUE THREAD

**Issue by pengyu** [explosion/spaCy#1725]
`spacy.load('en')` takes a long time to load. Is there a way to speed up significantly (say in 1 second).

```
$ time ./main.py 

real	0m11.382s
user	0m6.881s
sys	0m1.540s
$ cat ./main.py 
#!/usr/bin/env python
# vim: set noexpandtab tabstop=2 shiftwidth=2 softtabstop=-1 fileencoding=utf-8:

import spacy
spacy.load('en')
```

**Comment by ttropmail** [comment]
If you don't need all of the pipeline components, you can disable them, and it will improve the loading speed. 
`"pipeline": ["tagger", "parser", "ner"]`
So for example, if you didn't need the parser or named entity recognition, you could use: 
`nlp = spacy.load('en', disable=['tagger', 'ner'])`
For a description of the pipeline components check this out: 
https://spacy.io/usage/processing-pipelines

**Comment by julien-c** [comment]
@ttropmail In your experience does disabling pipeline components make a significant difference in load time? With the `en_core_web_md` model I get a load time of `14 s` without the components vs. `15 s` with them.
