### ISSUE TITLE
error while creating a model for new language

### ISSUE THREAD

**Issue by rohithkodali** [explosion/spaCy#1726]
I have created everything needed for a language using spacy-dev-resources and everything worked well till creating brown vector files, the next command is to create a model out of what i have generated till now

here is the command
 python -m spacy init-model  lang ././data/model/lang/vocab ./data/model/lang/lang_wiki.freqs ./data/model/lang/brown/paths ./data/model/lang/lang_wiki.word2vec.bz2                                

But it throw the error as below,

  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/spacy/__main__.py", line 31, in <module>
    plac.call(commands[command])
  File "/usr/local/lib/python2.7/dist-packages/plac_core.py", line 324, in call
    parser = parser_from(obj)
  File "/usr/local/lib/python2.7/dist-packages/plac_core.py", line 133, in parser_from
    parser.populate_from(obj)
  File "/usr/local/lib/python2.7/dist-packages/plac_core.py", line 257, in populate_from
    a = Annotation.from_(ann)
  File "/usr/local/lib/python2.7/dist-packages/plac_core.py", line 91, in from_
    return cls(*obj)
  File "/usr/local/lib/python2.7/dist-packages/plac_core.py", line 78, in __init__
    assert abbrev is None, abbrev
AssertionError: f    

tried all possible options like setting up again on python3 and retrain the model but still the same issue

## My Environment

* **Python version:** 2.7.12
* **Platform:** Linux-4.4.0-103-generic-x86_64-with-Ubuntu-16.04-xenial
* **spaCy version:** 2.0.5
* **Models:** en-1.1.0, __cache__, en_glove_cc_300_1m_vectors-1.0.0

**Comment by ines** [comment]
Sorry about this – I think this is actually related to a bug in the command arguments (a mismatched abbreviation of the argument). The issue has already been fixed in #1710 and will be included in the next release. In the meantime, you can just make the same edit to `spacy/cli/init_model.py` and it should work.

**Comment by rohithkodali** [comment]
i made that change but this is the current issue

 python -m spacy init-model   lang ./data/model/lang/spacy_model ./data/model/lang/lang_wiki.freqs  -c ./data/model/lang/brown/paths -v ./data/model/lang/lang_wiki.word2vec.bz2

usage: spacy init-model [-h] [-c None] [-v None] [-V -1]
                        lang output_dir freqs_loc                                         


all files are in place, don't know what missing

**Comment by rohithkodali** [comment]
i made that change but this is the current issue

python -m spacy init-model lang ./data/model/lang/spacy_model ./data/model/lang/lang_wiki.freqs -c ./data/model/lang/brown/paths -v ./data/model/lang/lang_wiki.word2vec.bz2

usage: spacy init-model [-h] [-c None] [-v None] [-V -1]
lang output_dir freqs_loc

all files are in place, don't know what missing
