### ISSUE TITLE
Suggestion: use src-d/modelforge to load/store the models

### ISSUE THREAD

**Issue by vmarkovtsev** [explosion/spaCy#1730]
Hi! I have seen how spaCy stores models ATM:

```
$ ls /usr/local/lib/python3.5/dist-packages/en_vectors_web_lg/en_vectors_web_lg-2.0.0/vocab -lah
total 1,4G
drwxr-sr-x 2 root staff 4,0K дек 15 19:50 .
drwxr-sr-x 3 root staff 4,0K дек 15 19:50 ..
-rwxr-xr-x 1 root staff 8,2M ноя  7 20:33 keys
-rwxr-xr-x 1 root staff  99M ноя  7 20:33 lexemes.bin
-rwxr-xr-x 1 root staff  16M ноя  7 20:33 strings.json
-rwxr-xr-x 1 root staff 1,2G ноя  7 20:33 vectors
```

Every part is a separate file. I suggest to have a look at [src-d/modelforge](https://github.com/src-d/modelforge) - a nice lib to load and store models in the very cool ASDF format with the on-the-fly decompression capability. The backend system allows dropping models at any storage, though only GCS is implemented. Lazy loading, versioning, deriving, etc. The central registry can be organized the same way as Homebrew does - using git (not implemented yet, there is [a concept](https://github.com/src-d/models)).

Would be happy to collaborate.

**Comment by honnibal** [comment]
Thanks for the suggestion.

I think there's a big advantage to have fewer technologies in between people and what they're doing. Using modelforge would introduce two new technologies: this ASDF file format, and the modelforge library itself. I'm not sure that's a net win. How does the modelforge library make things better?

**Comment by vmarkovtsev** [comment]
This is a list of improvements as I see it:

1. ASDF `mmap()`-s large numpy arrays and transparently wraps them. Loading gigabytes -> caching, not storing in memory -> tiny RES.
2. ASDF is able to store the data in gzip, bz2 or lz4. In spaCy's case, things like text in `strings.json` are effectively compressed. Less data on disk..
3. ASDF is based on YAML with binary extensions, can handle arbitrary data and designed with numpy in mind. Much better than hdf5 and others IMHO. 1 file instead of N files.
4. Dumping a model, unified way to work with all the models. Self-descriptive.
5. modelforge already does 80% of what spaCy does. The goals are very similar. The other 20% can be easily added, reducing the efforts to develop and especially maintain in the future. Serving, catalogizing. The metadata layer is based on my 5 years of experience + validated with Uber examples. Apache license allows you to do everything you want.

At the end of the day, this boils down to the question: will we join our efforts? I cannot take spaCy's "modelforge" because it is nailed to spaCy and misses some of the critical features (yet has its own cool unique ones). IMHO we are doing so many things the same and duplicate and it makes me sad.

**Comment by honnibal** [comment]
Sorry for not really engaging with the above, but overall I think we do really value having the model definitions within our own technology, and not using a dependency for it. It's just much easier to control that side of things if we have to make changes.
