### ISSUE TITLE
German Named Entity Recognition Example doesn't work.

### ISSUE THREAD

**Issue by blatoo** [explosion/spaCy#1734]
I try to follow the example for german named entity recognition, actually I expect the result should be `Berliner` like in the example: https://explosion.ai/blog/german-model#run-spacy

    import spacy
    nlp = spacy.load('de') # use the  german model
    doc = nlp(u'Ich bin ein Berliner.')
    for ent in doc.ents:
        print(ent.text)
       
However, I got the following result instead of `Berliner`:

    >>> Ich bin ein Berliner

Did I do something wrong?

## Your Environment

* Operating System: Mac OS
* Python Version Used: 3.6.3
* spaCy Version Used: 2.0.2
* Environment Information: virtualenv

**Comment by redevries** [comment]
It works for me... Did you download the new models? Take a look here: https://spacy.io/usage/models

**Comment by blatoo** [comment]
Hi @redevries ,
Thanks for answer. I realized that, I should use `doc.noun_chunks` instead of `doc.ent`.
Do you know, what means `doc.ents`? I thought it should represent for named entities. How ever, there is no description about it.

**Comment by ines** [comment]
@blatoo Named entities are available as `doc.ents`, and base noun phrases as `doc.noun_chunks`.

The blog post you've linked is fairly old and refers to the linear German model for spaCy v1.x. (We should probably add a note about this to the blog post!) Results can vary between models, so I think the new neural network model for spaCy v2.x, which was trained on Wikipedia, predicts entities slightly differently.

```python
doc = nlp(u'Ich bin ein Berliner.')
for ent in doc.ents:
    print(ent.text, ent.label_)

# Ich bin ein Berliner MISC
```

Here, the model assigns the label `MISC` (miscellaneous) to the phrase "Ich bin ein Berliner". The reason for this might be that this specific (and fairly iconic) phrase is considered an entity in the Wikipedia data.

However, if you rephrase the sentence, "Berlin" is recognised as a location:

```python
doc = nlp(u'Ich wohne in Berlin.')
for ent in doc.ents:
    print(ent.text, ent.label_)

# Berlin LOC
```
