### ISSUE TITLE
unable load new language in spacy after installed te model and set up shortcut link to load installed package as "te"

### ISSUE THREAD

**Issue by mdp0999** [explosion/spaCy#1737]
Hi,
     I created telugu model after that I installed te_model-0.0.0.tar.gz via pip and set up shortcut link to load installed package as "te"....it created successfully and after that link created and it shows message "spacy.load("te")".........everything is fine but when i tried to execute the line nlp = spacy.load("te").......it gives following error:

>>> nlp = spacy.load('te')

Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    nlp = spacy.load('te')
  File "/usr/local/lib/python2.7/dist-packages/spacy/__init__.py", line 19, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python2.7/dist-packages/spacy/util.py", line 112, in load_model
    return load_model_from_link(name, **overrides)
  File "/usr/local/lib/python2.7/dist-packages/spacy/util.py", line 131, in load_model_from_link
    return cls.load(**overrides)
  File "/usr/local/lib/python2.7/dist-packages/spacy/data/te/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/usr/local/lib/python2.7/dist-packages/spacy/util.py", line 176, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/usr/local/lib/python2.7/dist-packages/spacy/util.py", line 145, in load_model_from_path
    cls = get_lang_class(meta['lang'])
  File "/usr/local/lib/python2.7/dist-packages/spacy/util.py", line 52, in get_lang_class
    raise ImportError(msg % lang)
ImportError: Can't import language te from spacy.lang.

I am little confused to solve this error because everything is fine. Please help me to solve this error.

**Comment by mdp0999** [comment]
What modifications I need to do for loading new model in spacy???

**Comment by ines** [comment]
I think what's happening here is that when you load your new model, the spaCy installation you're loading it with doesn't know your custom language class `te`. When you load in a model, spaCy will check the model meta's `"lang"` setting and then use `get_lang_class` to find the `Language` class associated with the language code.

Before you trained your model, did you add a `Telugu` class? If so, you'll have to make it available before loading the model, either by adding it to spaCy, or by using [`util.set_lang_class`](https://github.com/explosion/spaCy/blob/master/spacy/util.py#L57) (just noticed this isn't currently documented – will fix this!): `util.set_lang_class('te', Telugu)`. You can also do this in the model's `__init__.py` – see [this section in the docs for more info](https://spacy.io/usage/training#models-custom).

If you don't have a `Language` subclass for `Telugu`, you can [create one](https://spacy.io/usage/adding-languages) and add it. Alternatively, you can also set the `"lang": "xx"` to use the language-neutral class, which only contains the basic tokenization rules.

**Comment by mdp0999** [comment]
Hi ines,
          Thanks for your reply, I have gone through above process and i modified code in util.py ...but in spacy/ folder I didn't done any modifications in __init__.py. I didn't understand how to modify inside bcz we are getting the get language class in conftest.py file. I am little confused to add telugu class also....... In lang, I created one te folder in lang instead of modifying xx folder and I kept all created new langauge template files like __init__, tag_map, lex_attr..etc. and I create telugu get class and model in conftest.py also...........after I am getting below error:

>> spacy.load("te")

Traceback (most recent call last):
  File "<pyshell#21>", line 1, in <module>
    spacy.load("te")
  File "/usr/local/lib/python2.7/dist-packages/spacy/__init__.py", line 19, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python2.7/dist-packages/spacy/util.py", line 120, in load_model
    return load_model_from_link(name, **overrides)
  File "/usr/local/lib/python2.7/dist-packages/spacy/util.py", line 139, in load_model_from_link
    return cls.load(**overrides)
  File "/usr/local/lib/python2.7/dist-packages/spacy/data/te/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/usr/local/lib/python2.7/dist-packages/spacy/util.py", line 184, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/usr/local/lib/python2.7/dist-packages/spacy/util.py", line 153, in load_model_from_path
    cls = get_lang_class(meta['lang'])
  File "/usr/local/lib/python2.7/dist-packages/spacy/util.py", line 53, in get_lang_class
    LANGUAGES[lang] = getattr(module, module.__all__[0])
AttributeError: 'module' object has no attribute 'te'

and import te is working

**Comment by ines** [comment]
> Thanks for your reply, I have gone through above process and i modified code in util.py

I don't think you need to modify anything in the `util.py`. It looks like you've done everything correctly. You've created the `te` folder and made sure the class inside is called `Telugu`. Then all you need to do is this:

```python
from spacy import util
from spacy.lang.te import Telugu

util.set_lang_class('te', Telugu)
```

You can then check that it's working:

```python
cls = util.get_lang_class('te')  # <class 'spacy.lang.te.Telugu'> 
nlp = cls()                      # same as Telugu()
doc = nlp(u"Some text")
```

At a minimum, `spacy/lang/te/__init__.py` should look something like this:

```python
# coding: utf8
from __future__ import unicode_literals

from ...attrs import LANG
from ...language import Language


class TeluguDefaults(Language.Defaults):
    lex_attr_getters = dict(Language.Defaults.lex_attr_getters)
    lex_attr_getters[LANG] = lambda text: 'te'

class Telugu(Language):
    lang = 'te'
    Defaults = TeluguDefaults

__all__ = ['Telugu']
```

**Comment by mdp0999** [comment]
Thank you so much :)
