### ISSUE TITLE
Lemma for "need" or "needed" is not an English word.  bug language / English

### ISSUE THREAD

**Issue by helelily** [explosion/spaCy#1738]
I've tried spacy v. 1.9 with the en_core_web_md model 1.2, and also spacy v. 2.0 with the en_core_web_md 2.0 and had this same issue.

Both cases working with python 2.7

I noticed the lemma for "need" is strange, this is the output of the following:

```
test = nlp("I needed this.")
[w.lemma_ for w in test]
```
outputs: 

> ['-PRON-', 'ne', 'this']

when it used to be 

> ['I', 'need', this']

I know the '-PRON-' is intentional - but the 'need' seems like a bug to me because 'ne' is not an English word and would not link back to the WordNet library which I thought was the source of the lemmas.

**Comment by cmward** [comment]
Here's an issue with this question: https://github.com/explosion/spaCy/issues/1383

As suggested, you can try:
`nlp.vocab.morphology.add_special_case('VBP', 'need', {'LEMMA': 'need'})`
or:
`spacy.en.English.Defaults.lemma_rules['verb'].append([u'need', u'need'])`

**Comment by helelily** [comment]
Thanks!
