### ISSUE TITLE
Failed loading model (default or trained)  in Spacy 1.9 on IBM AIX 7.1

### ISSUE THREAD

**Issue by phani2410** [explosion/spaCy#1739]
I was trying to install and use Spacy on AIX 7.1 
1. Python 3.5.2 is installed using source code compilation.
2. Installation of Spacy was done using: python setup.py build and install
3. G++ compiler was used to compile the code, all the .cpp files were manually compiled using ld_so_aix commad.
Eg:
 /home/user2/app/python352/lib/python3.5/config/ld_so_aix g++ -fPIC -pthread -bI:/home/user2/app/python352/lib/python3.5/config/python.exp build/temp.aix-7.1-3.5/spacy/parts_of_speech.o -o build/lib.aix-7.1-3.5/spacy/parts_of_speech.so -fopenmp

4. Above approach lead to successful installation of Spacy. "import spacy" command works.
5. Models were also installed.
6. While initialising pipeline, following error occured

```
>>> nlp=en_test_Demo.load()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user2/app/python352/lib/python3.5/site-packages/en_test_Demo/__init__.py", line 17, in load
    return lang(path=Path(data_dir), **kwargs)
  File "/home/user2/app/python352/lib/python3.5/site-packages/spacy-1.9.0-py3.5-aix-7.1.egg/spacy/en/__init__.py", line 34, in __init__
    Language.__init__(self, **overrides)
  File "/home/user2/app/python352/lib/python3.5/site-packages/spacy-1.9.0-py3.5-aix-7.1.egg/spacy/language.py", line 265, in __init__
    if 'vocab' not in overrides \
  File "/home/user2/app/python352/lib/python3.5/site-packages/spacy-1.9.0-py3.5-aix-7.1.egg/spacy/language.py", line 42, in create_vocab
    tag_map=cls.tag_map, lemmatizer=lemmatizer)
  File "spacy/vocab.pyx", line 94, in spacy.vocab.Vocab.load (spacy/vocab.cpp:4974)
  File "spacy/vocab.pyx", line 435, in spacy.vocab.Vocab.load_lexemes (spacy/vocab.cpp:9653)
  File "spacy/strings.pyx", line 146, in spacy.strings.StringStore.__getitem__ (spacy/strings.cpp:2577)
IndexError: 1453852416
>>> 
```
   

## Your Environment

* Operating System: IBM  AIX 7.1
* Python Version Used: 3.5.2
* spaCy Version Used: 1.9
* Environment Information: GCC-6.3.0 and G++ 6..93  

@honnibal @ines Do you support AIX OS?

**Comment by honnibal** [comment]
The model deserialization here is not endian-safe:

https://github.com/explosion/spaCy/blob/v1.10.0/spacy/vocab.pyx#L417

The model was serialized on a little-endian platform, and the deserialization reads `float`, `uint64_t` and `int32_t` values as though they are atomic.

I think the best solution for you will be to write a model converter that fixes the endianness in the models. If the model is in big-endian format, you should be able to read it in successfully (I think?).

**Comment by phani2410** [comment]
Will it be sufficient if i just convert the lexemes.bin file to big-endian format? Do i need to change model files in ner folder too?

**Comment by honnibal** [comment]
Yes, you'll need to change the model files in the `ner` and `pos` folders, and if you want to use the parser (e.g. for sentence boundary detection), you'll need to change the files in the `dep` folder. Unfortunately the format of these model files isn't documented. The best I can do is point you to the code that reads and writes the model: https://github.com/explosion/thinc/blob/v6.1.3/thinc/linear/avgtron.pyx#L80 . The `load()` and `dump()` methods call into the `Reader` and `Writer` classes here: https://github.com/explosion/thinc/blob/v6.1.3/thinc/linear/serialize.pyx

If you want to use the word vectors, you might need to change the `vec.bin` file too. Does your machine store float32 values in a different format from x86 machines too?
