### ISSUE TITLE
en_vectors_web_lg and en_core_web_lg are not considering "meanings of words in context"

### ISSUE THREAD

**Issue by madhusudhannsn** [explosion/spaCy#1740]
I am using spacy word vectors for SVM text classification. I noticed that both en_vectors_web_lg and en_core_web_lg has good amount of word vectors but they are are not considering "meanings of words in context". Where as en_core_web_sm is using context sensitive tensors and good at considering the meaning for word vectors. But it does not come with lot of word vectors. For example,

```
import spacy
nlp = spacy.load('en_core_web_lg')
docs = [nlp(u"dog bites man"), nlp(u"man bites dog"),nlp(u"man dog bites"), nlp(u"dog man bites")]
for doc in docs:
    for other_doc in docs:
        print(doc.similarity(other_doc)) 

Output: 
0.999999972267
0.999999971159
0.999999972676
0.999999972676
0.999999971159
0.999999970051
0.999999971568
0.999999971568
0.999999972676
0.999999971568
0.999999898398
0.999999898398
0.999999972676
0.999999971568
0.999999898398
0.999999898398
```
```
import spacy
nlp = spacy.load('en_core_web_sm')
docs = [nlp(u"dog bites man"), nlp(u"man bites dog"),nlp(u"man dog bites"), nlp(u"dog man bites")]
for doc in docs:
    for other_doc in docs:
        print(doc.similarity(other_doc)) 

Output: 

0.999999950807
0.941871427629
0.906207995175
0.93288197779
0.941871427629
1.00000005181
0.910312731387
0.900524118384
0.906207995175
0.910312731387
0.999999977514
0.94835300894
0.93288197779
0.900524118384
0.94835300894
1.0000000088

```

I tried the different examples of "Similarities in context" section in https://spacy.io/usage/vectors-similarity#section-basics and I see same behaviour. 

For my use case I need a model which considers the meaning of the words in context and should have good amount of word vectors. I am confused about which model to pick.

@honnibal @ines Could you please help me on this.

**Comment by ines** [comment]
Sorry about the confusion around this – see my comment in #1791:

> Sorry about this – with the other changes and improvements coming in #2274, we've now decided to take this example out, because it's too misleading. The "context" here comes from the context-sensitive tensors that are available in the `sm` models, which don't come with word vectors. When we released the models for v2.0, we thought this might be cool – but the similarity in context feature turned out to be much less useful.
