### ISSUE TITLE
Is CPU load when train_ner SpaCy not 100 percent all the time?

### ISSUE THREAD

**Issue by rubiagatra** [explosion/spaCy#1743]
I am training ner using train_ner.py with GCP 16 cores CPU. In the first halfway CPU load always 100 percent which is good because it is fast, but the last half the CPU load is only 50 percent and slower. Is this a problem? or should I tweak some code in train_ner.py. Thank you

## Your Environment

* Operating System: ubuntu 16.04
* Python Version Used: 3.5.2
* spaCy Version Used: 2.0.5
* Environment Information:

**Comment by honnibal** [comment]
@rubiagatra Hard to guess what's going on here, or whether there's a problem.

It could be that the batch size gets bigger, and that's somehow bad on your machine? I'm not sure why that would make sense though. What's the memory usage like?

You can see where the time is being spent by running "perf top". This might give you some extra insight into what's being done differently at different points of the training.
