### ISSUE TITLE
Hindi example is broken

### ISSUE THREAD

**Issue by benjaminp** [explosion/spaCy#1750]
```
$ python3 spacy/lang/hi/examples.py
 File "spacy/lang/hi/examples.py", line 15
        "स्वायत्त कार निर्माताओं की ओर बीमा दायित्व रखती है",
      ^
SyntaxError: invalid character in identifier
```

This is because the whitespace contains U+00A0 (NO-BREAK SPACE) which Python does not understand.

**Comment by sirjan13** [comment]
I still get this error during installation:
 File "/usr/local/lib/python2.7/dist-packages/spacy/lang/hi/examples.py", line 15
             "स्वायत्त कार निर्माताओं की ओर बीमा दायित्व रखती है",
        ^
    SyntaxError: invalid syntax
