### ISSUE TITLE
Multiple NER models in one pipeline

### ISSUE THREAD

**Issue by tokestermw** [explosion/spaCy#1752]
Hi, so let's say I've trained 3 different NER models from scratch: `ner_A`, `ner_B`, `ner_C`.

I train using the `EntityRecognizer` pipeline with a different `.name` attribute.

Since `EntityRecognizer` adds the `.ents` attributes to each `Doc` object, it doesn't seem like it's possible to add all the new NER models in one pipeline.

A workaround is to save each NER model individually: `ner_A.to_disk('ner_A')`, `ner_B.to_disk('ner_B')`, `ner_C.to_disk('ner_C')`.

For production, we can load them back in individually: `ner_A.from_disk('ner_A', vocab=False)`, `ner_B.from_disk('ner_B', vocab=False)`, `ner_C.from_disk('ner_C', vocab=False)`.

Then we can load the default nlp model: `nlp = spacy.load('en_core_web_sm')`. Run the original pipeline `doc = nlp('how are you?')`, then run the new NERs individually: `ner_A(doc)`, `ner_B(doc)`, `ner_C(doc)`.

Then maybe add the results to custom attributes (e.g. `doc._.ner_A_ents`).

Would this be a valid way to add models? I like using the spaCy sequence models since it has all the transition magic.

Thanks!

## Your Environment

* **spaCy version:** 2.0.5
* **Platform:** Darwin-17.3.0-x86_64-i386-64bit
* **Python version:** 3.6.3
* **Models:** en_core_web_sm

**Comment by tokestermw** [comment]
Looks like this method doesn't work when there is more than one `ner` component in the pipeline (gives segfault as there is more than one `doc.ents`).

**Comment by honnibal** [comment]
@tokestermw Sorry I missed this before.

Is this still an issue? It seems like it shouldn't be --- I thought the entity recognizer respected the pre-set entities. If it doesn't we can definitely fix that.

**Comment by tokestermw** [comment]
To recreate:

1. Train the NER in examples, output to `here` directory.

```
python examples/training/train_ner.py -o here
```

2. Load this model and the original NLP pipeline that includes `ner`.

```
import spacy
new_nlp = spacy.load('here')
nlp = spacy.load('en_core_web_sm')
```

3. Add the new component to the nlp pipeline

```
nlp.add_pipe(new_nlp.pipeline[-1][-1], 'new_ner')
```

4. segfaults when the two NERs predicts on the same spans.

```
nlp("I am Barack Obama that is living in France.")  # SEGFAULT
```

--

But I have a workaround to load the component separately and attaching each new component to a custom attribute. So it's not a problem for me anymore.

**Comment by honnibal** [comment]
@tokestermw Pretty sure I've gotten to the bottom of this! In `Doc.ents.__set__`, we're not resetting the `.ent_iob` correctly. This means the `ent_iob` and `ent_type` values can be out-of-synch, which causes the error.

**Comment by sudodoki** [comment]
can anyone on the thread who managed to find a workaround share snippet, please?
I'm trying to use `en` model and `xx` for ner and running into similar issue:
- if I do
```
nlp = en_core_web_md.load()
ner = xx_ent_wiki_sm.load()
```
and then do `doc = nlp(sent); ners = ner(sent)` I get
```
/usr/local/lib/python3.6/site-packages/thinc/neural/_classes/static_vectors.py in begin_update(self, ids, drop)
     65                 sgd(self._mem.weights, self._mem.gradient, key=self.id)
     66             return None
---> 67         dotted = self.ops.batch_dot(vectors, self.W)
     68         mask = self.ops.get_dropout_mask((dotted.shape[1],), drop)
     69         if mask is not None:

ops.pyx in thinc.neural.ops.NumpyOps.batch_dot()

ValueError: shapes (15,0) and (300,128) not aligned: 0 (dim 1) != 300 (dim 0)
```
- if I do
```
nlp = spacy.load('en_core_web_md')
ner = spacy.load('xx', disable=['tokenizer', 'tagger', 'parser'])
nlp.replace_pipe('ner', ner.pipeline[0][1])
```
I get the same error as above
