### ISSUE TITLE
text classifier/categorizer needs a random seed argument

### ISSUE THREAD

**Issue by trent-b** [explosion/spaCy#1753]
The results of the text classifier/categorizer (for example, the results from running spaCy/examples/training/train_textcat.py) are not reproducible without the ability to set a random seed argument. There are multiple situations where it is important to be able to reproduce exact results by setting a random seed value. This issue will likely involve modifying code in the thinc repository as well.

Just executing random.seed(0) does not resolve the issue.

**Comment by honnibal** [comment]
Sorry for missing this; it's definitely true that random seeds are often important. Your code missed setting `numpy.random.seed` as well. We've had a helper in `spacy.util` called `fix_random_seed` for this purpose for some time now.
