### ISSUE TITLE
Is Spacy supported on Big Endian systems.

### ISSUE THREAD

**Issue by phani2410** [explosion/spaCy#1754]
I am able to run my models on Linux and Windows, but cannot do same on IBM AIX. 
Is spacy Endian neutral?

## Your Environment

* Operating System: IBM  AIX 7.1
* Python Version Used: 3.5.2
* spaCy Version Used: 1.9
* Environment Information: GCC-6.3.0 and G++ 6..93

**Comment by honnibal** [comment]
We don't have a big endian machine to test on, and can't easily add one to our continuous integration set up. Unfortunately this means the only defense we have against endian bugs is reasoning --- which isn't a wonderfully reliable defense.

Do the models crash, or do they just give you obviously incorrect results?

**Comment by honnibal** [comment]
Replied in #1739

**Comment by ines** [comment]
Merging this with #1739!
