### ISSUE TITLE
Documentation of dep_

### ISSUE THREAD

**Issue by pengyu** [explosion/spaCy#1755]
The values of `dep_` (e.g., `advmod`) can be found in `spacy.symbols`. But it is not clear where their official definition is. Are they from here?

http://universaldependencies.org/en/dep/

**Comment by ines** [comment]
The English dependency labels use the [CLEAR Style](http://www.mathcs.emory.edu/~choi/doc/cu-2012-choi.pdf) by [ClearNLP](https://github.com/clir/clearnlp).

You can find the full documentation of the dependency label schemes used by spaCy in the annotation scheme docs: http://spacy.io/api/annotation#section-dependency-parsing

**Comment by pengyu** [comment]
There seems to a number of alternative conventions for annotating dependencies. What is the advantage of CLEAR Style compared with other alternatives?
