### ISSUE TITLE
Best Method for making bag of words vectors now that lexeme IDs are hashes

### ISSUE THREAD

**Issue by ELind77** [explosion/spaCy#1759]
Now that `StringStore` uses hashes instead of integer IDs, what's the best way to quickly make a sparse BOW vector from a `Doc`?  I know that in theory, I could instantiate a scipy doc_matrix that is 2^64 x 2^64, but that seems like it might cause problems.

**Comment by bdewilde** [comment]
@ELind77 This may be helpful to you: https://github.com/chartbeat-labs/textacy/blob/master/textacy/vsm.py#L18

**Comment by honnibal** [comment]
This library might also be useful: https://github.com/RaRe-Technologies/bounter
