### ISSUE TITLE
Annotation Spec for PoS Tags has dead link.

### ISSUE THREAD

**Issue by thedansimonson** [explosion/spaCy#176]
From the "Annotation Specifications: Part-of-speech Tagging" section of [the docs page](http://spacy.io/docs/#spec), the link in "Details here" seems to be dead:
https://github.com/honnibal/spaCy/blob/master/spacy/en/pos.pyx#L124

I was wondering which attributes--`pos` or `tag`--on Token object instances use which tag set. Just eyeballing it, it looks like `tag` is OntoNotes PTB, but I wanted to double check.

**Comment by honnibal** [comment]
Hey,

Sorry for the delay getting back to you on this.

Yes, `.tag` uses the OntoNotes PTB tag set, and `.pos` is supposed to use the Stanford Universal tags, but are currently not quite correct --- right now they're sort of a cross between the Stanford Universal and the Google Universal tags.

**Comment by thedansimonson** [comment]
Thanks!

**Comment by bittlingmayer** [comment]
Any more or updated guidance on this? :-)
