### ISSUE TITLE
Model downloads are too unreliable

### ISSUE THREAD

**Issue by ajayrfhp** [explosion/spaCy#1760]
What is the best way to download spacy models ?
I find that `python -m spacy download` is too unreliable. It often leads to timeout errors, despite having a steady, fast internet connection ( > 10 Mbps)

**Comment by ines** [comment]
Yes, the `spacy download` command is mostly a convenience wrapper, which checks compatibility, fetches the model from the GitHub releases (where they are hosted) and downloads it via pip. It's generally not recommended to depend on it in production use and as part of an automated process (e.g. your CI workflow).

You can always download the models directly using their URL – see the [model releases](https://github.com/explosion/spacy-models/releases) for the links to the individual files. This also ensures that you're always downloading the intended version. There's also a ["Using models in production"](https://spacy.io/usage/models#production) section in the docs with more info, ideas and best practices.
