### ISSUE TITLE
install fails on windows

### ISSUE THREAD

**Issue by simonm3** [explosion/spaCy#1761]
I tried installing with conda but when I do spacy.load("en") it says OSError: Can't find model 'en'. Uninstalled and tried with pip and it gives permission error access is denied.

Is windows not supported?

**Comment by simonm3** [comment]
I installed language separately like this and now seems to work. Be useful to have clearer instructions or include this in the conda install.

pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz --no-deps

**Comment by celsopneto** [comment]
I was on my way to suggest you to do this:
https://github.com/explosion/spaCy#updating-spacy
or just asking if you did it
glad it worked

**Comment by ines** [comment]
Fixed in #1792!
