### ISSUE TITLE
TextCat become different when change the order we add labels

### ISSUE THREAD

**Issue by zihaolucky** [explosion/spaCy#1763]
Suppose I have several categories and `textcat` have to `add_label` first before train.

```
categories = [
    'a',
    'b',
    'c',
    'd',
    'e',
]

for label in categories:
    textcat.add_label(label)
```

I found that if we change the order of the `categories`, such as `b, a, c, d, e`, then the performance of the model changed rapidly. So weird.

## Your Environment

* Operating System: OSX. 10.12
* Python Version Used: 2.7
* spaCy Version Used: 2.0.5
* Environment Information:

**Comment by zihaolucky** [comment]
@honnibal

**Comment by honnibal** [comment]
I probably won't be able to resolve this until after the Christmas holidays. But just quickly:

If you're finding that the order with which you add the labels *before* training affects the results, yes that's weird. After loading a pre-trained model, it should have all the labels you need --- so `add_label` shouldn't do anything. Which are you trying to do?

**Comment by zihaolucky** [comment]
@honnibal Just try looking into this if you have time. I add these labels *before* training.

**Comment by honnibal** [comment]
@zihaolucky I've been unable to reproduce this. If you're still working with the text classifier and the problem is still there, would you be able to provide an example?
