### ISSUE TITLE
Documentation for linguistic feature operators in patterns is incorrect

### ISSUE THREAD

**Issue by hobson** [explosion/spaCy#1764]
The description of the behavior of {'OP': '*'} (0 or 1) and {'OP': '?'} (0 or more) are reversed here: https://spacy.io/usage/linguistic-features#quantifiers

In addition, the pattern {'OP': '*'} is a nonconsuming Kleine star operator that will match anything without including those matched tokens in the match span.

**Comment by ines** [comment]
Fixed in 65babd9e2ec27ffb0075a44077a0b760937aa33a!
