### ISSUE TITLE
nlp.pipe(docs, n_threads=1, batch_size=20) exited with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by dineshdharme** [explosion/spaCy#1766]
I was following the Jupyter notebook on AuthorTopic model by gensim. 
https://nbviewer.jupyter.org/github/rare-technologies/gensim/blob/develop/docs/notebooks/atmodel_tutorial.ipynb#Explore-author-topic-representation

I was able to get everything running for the dataset used in the notebook i.e. nips papers dataset.
I wanted to train the model on my own modest dataset of patents.
But the docs processing pipeline throws the below error. Also, on training the nips paper dataset, the memory usage stayed almost constant. But with patents dataset, the memory usage fluctuated widely and at one time, it consumed all of my 32 gb of ram and the error was thrown after that.

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

    print("Loading spacy english model")
    
    nlp = spacy.load('en')
    
    processed_docs = []
    
    print("NLP pipeline processing for the docs")
    
    for doc in nlp.pipe(docs, n_threads=1, batch_size=20):
        # Process document using Spacy NLP pipeline.
    
        ents = doc.ents  # Named entities.
    
        # Keep only words (no numbers, no punctuation).
        # Lemmatize tokens, remove punctuation and remove stopwords.
        doc = [token.lemma_ for token in doc if token.is_alpha and not token.is_stop]
    
        # Remove common words from a stopword list.
        # doc = [token for token in doc if token not in STOPWORDS]
    
        # Add named entities, but only if they are a compound of more than word.
        doc.extend([str(entity) for entity in ents if len(entity) > 1])
    
        processed_docs.append(doc)
    

I can provide the dataset used and the code to reproduce the error.

## Your Environment
* **spaCy version:** 2.0.5
* **Platform:** Linux-4.13.0-21-generic-x86_64-with-Ubuntu-17.10-artful
* **Python version:** 3.6.3
* **Models:** en

**Comment by ines** [comment]
Merging this with #1767!

**Comment by dineshdharme** [comment]
Even though the description of how I got the issues #1767 and #1766 are same. But these two are very different issues with different errors. Do you think they are caused by the same bug? One throws a C-level error while the other throws a python error.
