### ISSUE TITLE
MemoryError using nlp.pipe()

### ISSUE THREAD

**Issue by dineshdharme** [explosion/spaCy#1767]
I was following the Jupyter notebook on AuthorTopic model by gensim. 
https://nbviewer.jupyter.org/github/rare-technologies/gensim/blob/develop/docs/notebooks/atmodel_tutorial.ipynb#Explore-author-topic-representation

I was able to get everything running for the dataset used in the notebook i.e. nips papers dataset.
I wanted to train the model on my own modest dataset of patents.
But the docs processing pipeline throws the below error. The number of documents in docs is 101 while the batch_size used is 40. 40 doesn't cleanly divides 101 and hence the error is thrown. The same error is also thrown when number of documents is 100 and batch_size = 40 ( i.e. 100%40 != 0). This particular error is not thrown when number of documents is 100 and batch_size = 20. 

Traceback (most recent call last):
  File "/mnt/PythonLatest/Patents_atmodel.py", line 101, in <module>
    for doc in nlp.pipe(docs, n_threads=2, batch_size=40):
  File "/usr/local/lib/python3.6/dist-packages/spacy/language.py", line 555, in pipe
    for doc in docs:
  File "nn_parser.pyx", line 369, in pipe
  File "cytoolz/itertoolz.pyx", line 1046, in cytoolz.itertoolz.partition_all.__next__ (cytoolz/itertoolz.c:14538)
  File "nn_parser.pyx", line 376, in pipe
  File "nn_parser.pyx", line 403, in spacy.syntax.nn_parser.Parser.parse_batch
  File "nn_parser.pyx", line 725, in spacy.syntax.nn_parser.Parser.get_batch_model
  File "nn_parser.pyx", line 84, in spacy.syntax.nn_parser.precompute_hiddens.__init__
  File "/usr/local/lib/python3.6/dist-packages/spacy/_ml.py", line 150, in begin_update
    Yf = self._add_padding(Yf)
  File "/usr/local/lib/python3.6/dist-packages/spacy/_ml.py", line 179, in _add_padding
    Yf_padded = self.ops.xp.vstack((self.pad, Yf))
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/shape_base.py", line 237, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
MemoryError

The error is thrown at the nlp pipeline processing.

    print("Loading spacy english model")
    
    nlp = spacy.load('en')
    
    processed_docs = []
    
    print("NLP pipeline processing for the docs")
    
    for doc in nlp.pipe(docs, n_threads=2, batch_size=40):
        # Process document using Spacy NLP pipeline.
    
        ents = doc.ents  # Named entities.
    
        # Keep only words (no numbers, no punctuation).
        # Lemmatize tokens, remove punctuation and remove stopwords.
        doc = [token.lemma_ for token in doc if token.is_alpha and not token.is_stop]
    
        # Remove common words from a stopword list.
        # doc = [token for token in doc if token not in STOPWORDS]
    
        # Add named entities, but only if they are a compound of more than word.
        doc.extend([str(entity) for entity in ents if len(entity) > 1])
    
        processed_docs.append(doc)
    

I can provide the dataset used and the code to reproduce the error.

## Your Environment

* **spaCy version:** 2.0.5
* **Platform:** Linux-4.13.0-21-generic-x86_64-with-Ubuntu-17.10-artful
* **Python version:** 3.6.3
* **Models:** en

**Comment by honnibal** [comment]
I'm not sure the analysis is correct. If this were a problem, parsing any number of documents less than the batch size would also trigger an error. I suspect instead that you're running out of memory, due to a current memory inefficiency in the convolutional layers for large documents.

Could you try again setting the batch size down to say, 8, and watch the memory usage of your process? Thanks!

**Comment by dineshdharme** [comment]
I think you might be right. I checked the number of documents in the NIPS dataset and it was 1740. Clearly 1740%40 !=0 but still it works. As you recommended, I checked with 

`for doc in nlp.pipe(docs, n_threads=1, batch_size=8):`

but I got the following error.
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

I monitored the memory usage. It reaches a peak and consumes slightly less than 32gb ram  that I have and then throws this error. The graph might not be accurate but it might be the case full ram was used.
Currenlty, I am just setting batch_size and n_threads to 1 and it works.

Thanks,

**Comment by akanshajainn** [comment]
setting batch_size=1, n_threads=1 in nlp.pipe solves for me.

**Comment by tanthml** [comment]
I think this depends on the length of string text, I got error when input the whole pdf file to `pipe`, then my solution is do the sentence tokenize by the `nltk`, then put each sentences to `pipe`

**Comment by honnibal** [comment]
v2.1 should use less memory, and also implements a check for maximum document length. Please open a new issue if you have any problems with the new version. You can get it now with `pip install spacy-nightly`
