### ISSUE TITLE
training performance question

### ISSUE THREAD

**Issue by mrgonext** [explosion/spaCy#1771]
Firstly, thank you for your great work!
I try to get sample code to run
https://raw.githubusercontent.com/explosion/spaCy/master/examples/training/train_ner.py

I downloaded and adding my own training data (Vietnamese) please see my attached code. It worked fine with small data, however when I adding more about 6K row it runs very slowly, I'm waiting 6 hours but it still have not finished yet
I don't know if I done it wrong way? Please advise me!
thank again! 
[train_ner.zip](https://github.com/explosion/spaCy/files/1588505/train_ner.zip)

## Info about spaCy

* **spaCy version:** 2.0.5
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **Python version:** 3.6.0
* **Models:** en, xx
* Environment Information:

**Comment by mrgonext** [comment]
Hi Guys,

do you have any suggestions for this?

**Comment by ines** [comment]
Sorry for only getting to this now! You might want to check out #1805, which deals with a similar question. Copying over my response from there:

> The training examples in the `examples` directory are mostly intended to be self-contained scripts that you can run and test quickly. They're not really optimised to work with large datasets – for example, they don't use batching.

> So once you're getting "serious" about training your model, you might want to use the built-in `spacy train` command instead – [see here](http://spacy.io/api/cli#train) for the documentation. You can find the full implementation of `spacy train` here: https://github.com/explosion/spaCy/blob/master/spacy/cli/train.py
