### ISSUE TITLE
Wildcard token pattern with quantifier works unexpectedly

### ISSUE THREAD

**Issue by beowulfenator** [explosion/spaCy#1776]
If a wildcard token pattern is used with a quantifier (to match any token a certain number of times), the matcher returns all tokens up to the wildcard token, but not the rest.

```
nlp = spacy.load('en_core_web_sm')
doc = nlp("My big pencil is red. Your pencil is green.")
matcher = Matcher(nlp.vocab)
matcher.add("pencil", None, [
    {"LEMMA": "-PRON-"},
    {"OP": "*"},
    {"LEMMA": "pencil"},
])
matches = matcher(doc)
for (entity_key, start_token, end_token) in matches:
    print(start_token, end_token, doc[start_token:end_token])
```

Result:
```
0 1 My
6 7 Your
```

Adding some other constraint to the token fixes the problem:

```
matcher.add("pencil", None, [
    {"LEMMA": "-PRON-"},
    {"IS_ASCII": True, "OP": "*"},
    {"LEMMA": "pencil"},
])
```

Result:
```
0 3 My big pencil
6 8 Your pencil
```

## Info about spaCy

* **Models:** en_core_web_sm, en_core_web_md
* **spaCy version:** 2.0.5
* **Platform:** Linux-4.4.0-31-generic-x86_64-with-Ubuntu-16.04-xenial
* **Python version:** 3.5.2

**Comment by savkov** [comment]
The `?` and `*` operators have a weird behaviour when used without other parameters. Trying to figure out if it can be fixed right now :|

**Comment by honnibal** [comment]
Thanks for the report. I think this is the same issue as #1474 , so I'll close this to keep the discussion together.
