### ISSUE TITLE
Improve spacy model for MONEY entity recognition

### ISSUE THREAD

**Issue by bond-** [explosion/spaCy#1777]
## Issue
40 dollars and 30 cents should be classified as a single money entity instead of two.

Source code:
```
import spacy
nlp = spacy.load('en')
print(nlp('40 dollars and 30 cents').ents)
nlp = spacy.load('en_core_web_lg')
print(nlp('40 dollars and 30 cents').ents)
```
Results:
```
(40 dollars, 30 cents)
(40 dollars, 30 cents)
```

I tried training the model but failed to do so because, the results of the train are overwriting the base model.

> Can someone also let me know how I can improve the model locally?

## Your Environment

* **spaCy version:** 2.0.4
* **Platform:** Darwin-15.6.0-x86_64-i386-64bit
* **Python version:** 3.6.3
* **Models:** en, en_core_web_lg, en_core_web_md, en_core_web_sm, en_vectors_web_lg
* **Operating System:** MacOS

**Comment by exepaul** [comment]
I also want to know how to update already trained model without loosing previous knowledge of model.

**Comment by f11r** [comment]
Take a look here: https://explosion.ai/blog/pseudo-rehearsal-catastrophic-forgetting
