### ISSUE TITLE
How does spaCy handle NER?

### ISSUE THREAD

**Issue by pengyu** [explosion/spaCy#1778]
I am wondering how spaCy handles NER. As I don't find spaCy dependent on deep learning libraries like tensorflow or keras, does it mean that spaCy does not use deep learning for NER? Thanks.

**Comment by wejradford** [comment]
Hi @pengyu, [version 2 uses neural models for NER](https://spacy.io/usage/v2#features-models), just not tensorflow or keras. Hope this helps.

**Comment by ines** [comment]
There's also this video we've recorded, in which @honnibal goes through the NER model architecture step by step and shares a lot of background information and details:

https://www.youtube.com/watch?v=sqDHBH9IjRU [~55 minutes]

> As I don't find spaCy dependent on deep learning libraries like tensorflow or keras, does it mean that spaCy does not use deep learning for NER? 

spaCy uses its own machine learning library, [Thinc](https://github.com/explosion/thinc/), which was developed specifically for this purpose and for working with text. It's a practical implementation of the ["Embed, encode, attend, predict"](https://explosion.ai/blog/deep-learning-formula-nlp) achitecture. For more details, see the Thinc repo: https://github.com/explosion/thinc/
