### ISSUE TITLE
Running test suite requires `mock` package

### ISSUE THREAD

**Issue by drussellmrichie** [explosion/spaCy#1781]
Might want to put a note [here](https://spacy.io/usage/#tests) to `pip install mock` first? :-)

**Comment by ines** [comment]
Thanks! For running the tests, we currently assume that you've built spaCy from source and installed the dependencies from the [`requirements.txt`](https://github.com/explosion/spaCy/blob/master/requirements.txt), which includes development dependencies like Cython, as well as test utilities like `pytest` and `mock`.

We should probably add a note to this to that docs page you linked, thanks!
