### ISSUE TITLE
Independent clause boundary disambiguation

### ISSUE THREAD

**Issue by paigenestor** [explosion/spaCy#1783]
When parsing through a complex sentence that contains multiple independent clauses, spaCy does not correctly identify the various parts for each clause.

For example, look at the sentence: "The bathroom was dirty, my tray table was broken, and the wifi was not working." 

When you parse the sentence each of the three verbs are not connected to the correct nouns. Everything in the sentence is linking back to broken, even though the other two clauses are unrelated. 

You can see this visually with displaCy
![screen shot 2017-12-29 at 5 01 50 pm](https://user-images.githubusercontent.com/16904378/34450275-169c003a-ecba-11e7-923a-91883d5cd633.png)

When you input it into Stanford's parser at http://nlp.stanford.edu:8080/parser/ you can clearly see the three clauses separated.  

![screen shot 2017-12-29 at 5 03 18 pm](https://user-images.githubusercontent.com/16904378/34450286-381e4844-ecba-11e7-8fe4-2532b3ca6793.png)

## Your Environment

* Python Version Used: 2.7.13
* spaCy Version Used:  1.9.0

**Comment by ines** [comment]
Merging this with #3052. We've now added a master thread for incorrect predictions and related reports – see the issue for more details.
