### ISSUE TITLE
Noun chunks not present in .noun_chunks when nouns are properly tagged.

### ISSUE THREAD

**Issue by theSage21** [explosion/spaCy#1785]
This table quickly describes the problem.

Spacy Version  |  pos_  |  tag_ | dep_ | noun_chunks
-------|---|---|---|---
1.8.2 | NOUN VERB ADP PROPN ADP PROPN PUNCT | WP VBD IN NNP IN NNP . | nsubj ROOT prep pobj prep pobj punct | [What, F-22, Syria]
2.0.2 | NOUN VERB ADP PROPN ADP PROPN PUNCT | WP VBD IN NNP IN NNP . | nsubj ROOT prep punct punct pobj punct | [What, Syria]
2.0.5 | NOUN VERB ADP PROPN ADP PROPN PUNCT | WP VBD IN NNP IN NNP . | nsubj ROOT prep punct punct pobj punct | [What, Syria]

In the old spacy an adversarial sentence **"What happened for F-22 in Syria?"** has `.noun_chunks` attribute as `[what, F-22, Syria]` and the new one misses F-22. The pos and tags are the same in both versions. however the `dep_` is different. Would this difference reliably explain the difference in `noun_chunks`?

# Old environment
* **Python version:** 2.7.12
* **Platform:** Linux-4.4.0-1041-aws-x86_64-with-Ubuntu-16.04-xenial
* **spaCy version:** 1.8.2
* **Installed models:** en

# New environment
* **Platform:** Linux-4.10.0-42-generic-x86_64-with-Ubuntu-17.04-zesty
* **Models:** en_core_web_md, en
* **Python version:** 3.5.3
* **spaCy version:** 2.0.2

**Comment by ines** [comment]
Yes, the noun chunks depend on the part-of-speech tags *and* the dependency parse, so this issue likely comes down to the difference in predictions made by the parser.

I'm merging this with #3052. We've now added a master thread for incorrect predictions and related reports – see the issue for more details.
