### ISSUE TITLE
Deep Learning Example: Opening dataset encoding error on windows

### ISSUE THREAD

**Issue by DaveNW16HD** [explosion/spaCy#1786]
Hi

I'm trying to run the deep_learning_keras.py example but is running to an encoding issue. I suspect it might have something to do with me working on Windows 10  after digging around?

> 
> Using TensorFlow backend.
> 2018-01-02 13:53:40.126430: I C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
> Traceback (most recent call last):
>   File "D:/CodeDevelopments/PythonProjects/spacyExample/deep_learning_keras.py", line 225, in <module>
>     plac.call(main)
>   File "C:\Users\Dave\Anaconda3\lib\site-packages\plac_core.py", line 328, in call
>     cmd, result = parser.consume(arglist)
>   File "C:\Users\Dave\Anaconda3\lib\site-packages\plac_core.py", line 207, in consume
>     return cmd, self.func(*(args + varargs + extraopts), **kwargs)
>   File "D:/CodeDevelopments/PythonProjects/spacyExample/deep_learning_keras.py", line 191, in main
>     imdb_data = thinc.extra.datasets.imdb()
>   File "C:\Users\Dave\Anaconda3\lib\site-packages\thinc\extra\datasets.py", line 87, in imdb
>     return read_imdb(train_loc, limit=limit), read_imdb(test_loc, limit=limit)
>   File "C:\Users\Dave\Anaconda3\lib\site-packages\thinc\extra\datasets.py", line 110, in read_imdb
>     text = file_.read()
>   File "C:\Users\Dave\TF\lib\encodings\cp1252.py", line 23, in decode
>     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 803: character maps to <undefined>

These are my lib info

Using anaconda with python 3.6.3
spacy 2.0.5
keras 2.1.2
tensorflow 1.4.1

**Comment by ines** [comment]
Merging this with #1445!
