### ISSUE TITLE
Mismatches between word_freqs.py and init-model

### ISSUE THREAD

**Issue by sorenlind** [explosion/spaCy#1794]
There seems to a be few mismatches between the files written by `word_freqs.py` in the spacy-dev-resources repo and the files expected by spaCy's `init-model` command.

### File Type ###
The `init-model` command seems to expect a compressed JSON-file while `word_freqs.py` writes tab-separated text files. I would be happy to align this, but it's not completely clear to me whether `init-model` or `word_freqs.py` has the preferred behavior. What do you think?

### Quoted Words ###
The `init-model` command expects words to be quoted. However, `word_freqs.py` writes unquoted words. Again, I would be happy to fix this, but it not's clear to me which behavior is preferred.

### Related
* #1209
* #1744
* https://github.com/explosion/spacy-dev-resources/issues/23
* https://spacy.io/api/cli

## Your Environment

* **spaCy version:** 2.0.5
* **Platform:** Darwin-17.3.0-x86_64-i386-64bit
* **Python version:** 3.6.2

**Comment by ines** [comment]
Thanks, I didn't realise this – I thought the frequencies file was the same format for both. There also seems to be an inconsistency with the word vectors format, so if we could align those, that would be amazing and definitely appreciated.

I also wonder if we could manage to somehow combine those scripts with the `init-model` command... at least, it'd be nice if spaCy's CLI could handle all of those things, especially since it keeps coming up, and only having random scripts for this feels a little unsatisfying. We obviously don't want to make the commands *too* verbose, and we also don't want one command that does too many things and runs for hours. But maybe there could be a creative and user-friendly way to solve this?

**Comment by sorenlind** [comment]
Cool! I agree, and I'll be happy to look into this and try think of a user-friendly way to solve it. It's not completely obvious to me how to do it, though. 

On one hand, I think having the scripts in spacy-dev-resources, introduces a risk that the scripts become stale in the sense that they are not updated when `init-model` is changed. (I'm not implying this is what happened 🙂). On the other hand, moving the functionality to spaCy will introduce gensim as a dependency. What's your thoughts on that?

Even if moving functionality of the scripts to spaCy, there's the question of whether to include it in the `init-model` command or create separate commands. One argument for creating separate commands would be that building frequencies and word vectors can take quite some time and as such it would be useful to be able to re-run one of those separately.

Maybe we could try adding two commands, `frequencies` and `vectors`, and make sure their output file formats align with `init-model`? I suppose one argument against this is that the output of those two commands are only intermediate files that are not really useful in and of themselves. Let me know what you think 🙂.

**Comment by ines** [comment]
Thanks a lot!

> On one hand, I think having the scripts in spacy-dev-resources, introduces a risk that the scripts become stale in the sense that they are not updated when init-model is changed. 

Yes, I absolutely agree – this is also my main concern and why I think including it with the library makes sense here. In general, we want to be selective about what we ship with spaCy – many development scripts are much better suited for a separate repository. But the word frequencies and vectors scripts are very popular and users keep asking about them, so we want to make sure to keep them up to date, and make them more convenient to use.

> One argument for creating separate commands would be that building frequencies and word vectors can take quite some time and as such it would be useful to be able to re-run one of those separately.
> I suppose one argument against this is that the output of those two commands are only intermediate files that are not really useful in and of themselves. Let me know what you think 🙂.

I was thinking about this, too. The time argument is pretty important. (I don't have any numbers or rough processing times relative to corpora sizes – if anyone does, feel free to chime in!) And even if it didn't take *that* long, users also shouldn't lose their word frequencies if there's an issue with the vectors... So as nice as it would be to do it all in one, it's probably not a good idea...

So we could perhaps try an `init-frequencies` and `init-vectors` command? I'm a little worried about the verbosity, but I think we might be able to make them more compact by just rewriting them a little and getting rid of some clutter...

**Comment by sorenlind** [comment]
Thanks! I've been thinking a bit more on this, specifically how we could best write an `init-frequencies` and `init-vectors` command. I think this issue might be going a bit deeper than I had anticipated. Or maybe I'm over-complicating things. In any case, I'd like to hear you opinion. I've tried to sketch some of my thoughts below. Please let me know if it's unclear :)

My initial thought was that we should let the init-commands work with "raw text" in the sense that the user could download a large corpus text from the internet and then use that to build frequencies and train vectors. But as it turns out, this raises a lot of questions. 

### Raw Text? ###
First of all, what do we mean by *raw text*? Should we expect the user to have already done some cleaning and preprocessing? Lowercasing? Should we handle things like squashing multiple whitespaces? The `init-model` command runs `ftfy.fix_text` when reading clusters. Should we do something similar?

#### List of Files ####
I think we should also decide on how to specify the input files. Some of the existing scripts expect a file which contains file paths to the actual text files. I see a few pros and cons:
* Pro: Files can be stored across multiple folders and drives.
* Pro: It's easy to run on a subset of file just by editing the file containing the list of text files.
* Con: The user must create the the file containing the list of text files.
* Con: If one of the commands creates intermediate files mirroring the input files, it's not obvious how to mirror the directory structure.
* Con: The file list file could not easily be copied between platforms (fx if it's written by a Windows user it may reference drive names like `c:`).

#### Directory ####
Other existing scripts take an alternative approach: They expect a directory which will be traversed to find the actual text files. This comes with pros and cons as well:
* Con: All files have to be stored in the specified folder, meaning it's not easy to store files across multiple drives.
* Con: To run on a subset of files in a folder, user must remove all other files (or create a new folder with a copy of the subset)
* Con: Hidden files like `.DS_Store` need to be skipped.
* Pro: The user can just point to an existing directory of text files without having to build a file containing a list of them.
* Pro: When creating intermediate files, the structure of the input directory could be mirrored.


### Tokenization ###
The current `word_vectors.py` script uses spaCy's tokenizer when building a vocab to use with gensim. But spaCy is *not* used for tokenizing when passing the text to gensim for the actual training. I believe spaCy should handle tokenization in both cases, or am I missing something?

Further, the current vectors script does not appear to actually do tokenization at all when training (the Corpus class returns full documents when iterating over it). If I understand the gensim documentation correctly, the input for training should be a list of list of tokens, not a list of documents/sentences?

I've made a couple of experiments with different ways of tokenizing. When using spaCy, I get about 7,800 words/s on my MacBook Pro. Using a simple `str.split`, I get about 100,000 words/s. This leads me to think it could be worth writing intermediate files that have been tokenized using spaCy and written in such a way that a simple `str.split` could tokenize them properly. This, again, raises the question of whether to have a command (`tokenize`, `init-text` or similar) that can handle this tokenization. But, this would lead to even more steps to build the model:

1. Run new `tokenize` / `init-text` command to write "tokenized" files
2. Run `init-frequencies` on the "tokenized" files to count frequencies
3. Run `init-vectors` on the "tokenized" files to build word vectors
4. Run `init-model` on files written by step 2 and 3 to initialize the model

We would probably want to add a step for building the clusters as well?



### Word Frequency and Vocabulary ###
Currently, both the frequencies and the vectors script perform frequency counting. Maybe we could make the `init-vectors` command read and use the frequencies built by `init-frequencies`?  This would make `init-vectors` depend on having run `init-frequencies` which might be undesirable.


### Documents vs Sentences ###
Somewhat related, I think it's also worth being explicit and concious about the distinction between documents and sentences. The gensim documentation seems to mostly mention sentences, or one-sentence documents. For web-corpora, it does not seem likely that (a reliable) sentence segmentation has been applied, and we can't use spaCy since this would assume we already had the model we are about to build. So I think it would make sense to not speak of sentences but only of documents in this part of the code?

**Comment by sorenlind** [comment]
Thanks! I've been thinking a bit more on this, specifically how we could best write an `init-frequencies` and `init-vectors` command. I think this issue might be going a bit deeper than I had anticipated. Or maybe I'm over-complicating things. In any case, I'd like to hear your opinion. I've tried to sketch some of my thoughts below. Please let me know if it's unclear :)

My initial thought was that we should let the init-commands work with "raw text" in the sense that the user could download a large corpus text from the internet and then use that to build frequencies and train vectors. But as it turns out, this raises a lot of questions. 

### Raw Text? ###
First of all, what do we mean by *raw text*? Should we expect the user to have already done some cleaning and preprocessing? Lowercasing? Should we handle things like squashing multiple whitespaces? The `init-model` command runs `ftfy.fix_text` when reading clusters. Should we do something similar?

#### List of Files ####
I think we should also decide on how to specify the input files. Some of the existing scripts expect a file which contains file paths to the actual text files. I see a few pros and cons:
* Pro: Files can be stored across multiple folders and drives.
* Pro: It's easy to run on a subset of files just by editing the file containing the list of text files.
* Con: The user must create the the file containing the list of text files.
* Con: If one of the commands creates preprocessed copies of the the input files, it would be easy to grasp for the user if the original directory structure is mirrored. But it's not obvious how to do this if the input files are scattered over several folders and possibly drives.
* Con: The file list file could not easily be copied between platforms (fx if it's written by a Windows user it may reference drive names like `c:`).

#### Directory ####
Other existing scripts take an alternative approach: They expect a directory which will be traversed to find the actual text files. This comes with pros and cons as well:
* Con: All files have to be stored in the specified folder, meaning it's not easy to store files across multiple drives.
* Con: To run on a subset of files in a folder, user must remove all other files (or create a new folder with a copy of the subset)
* Con: Hidden files like `.DS_Store` need to be skipped.
* Pro: The user can just point to an existing directory of text files without having to build a file containing a list of them.
* Pro: When creating intermediate files, the structure of the input directory could be mirrored.


### Tokenization ###
The current `word_vectors.py` script uses spaCy's tokenizer when building a vocab to use with gensim. But spaCy is *not* used for tokenizing when passing the text to gensim for the actual training. I believe spaCy should handle tokenization in both cases, or am I missing something?

Further, the current vectors script does not appear to actually do tokenization at all when training (the Corpus class returns full documents when iterating over it). If I understand the gensim documentation correctly, the input for training should be a list of list of strings (tokens), not a list of strings (documents/sentences)?

I've made a couple of experiments with different ways of tokenizing. When using spaCy, I get about 7,800 words/s on my MacBook Pro. Using a simple `str.split`, I get about 100,000 words/s. This leads me to think it could be worth writing intermediate files that have been tokenized using spaCy and written in such a way that a simple `str.split` could tokenize them properly. This, again, raises the question of whether to have a command (`tokenize`, `init-text` or similar) that can handle this tokenization. But, this would lead to even more steps to build the model:

1. Run new `tokenize` / `init-text` command to write "tokenized" files
2. Run `init-frequencies` on the "tokenized" files to count frequencies
3. Run `init-vectors` on the "tokenized" files to build word vectors
4. Run `init-model` on files written by step 2 and 3 to initialize the model


### Word Frequency and Vocabulary ###
Currently, both the frequencies and the vectors script perform frequency counting. Maybe we could make the `init-vectors` command read and use the frequencies built by `init-frequencies`?  This would make `init-vectors` depend on having run `init-frequencies` which might be undesirable.

### Documents vs Sentences ###
Somewhat related, I think it's also worth being explicit and concious about the distinction between documents and sentences. The gensim documentation seems to mostly mention sentences, or one-sentence documents. For web-corpora, it does not seem likely that (a reliable) sentence segmentation has been applied, and we can't use spaCy since this would assume we already had the model we are about to build. So I think it would make sense to not speak of sentences but only of documents in this part of the code?

### Rough Idea ###
With the above in mind, I have tried to sketch a rough idea for what we could do. I'd really like to have your opinion.

First of all, I suggest we specify a *directory* as input (as opposed to file list). I think the pros with regards to mirroring directory and platform structure outweigh the cons.

* Make it the user's responsibility to do cleaning of text outside spaCy. This would include removal of unwanted characters, normalizing similar special characters such as quotes, squashing multiple whitespace.
* New command `tokenize` (suggestions for a better name?): This will take as input a directory containing text files and tokenize all of them using spaCy's tokenizer and then write them back to a new set of files, separating each token by a single space. This way the files can be read in again and tokenized using `str.split`.
* New command `init-frequences`: Read the files written by the `tokenize` command and count frequencies (in the same way as `word_freqs.py` currently does.
* New command `init-vectors`: Read the frequences written by `init-frequences` to quickly build a vocab. Then read files written by `tokenize` and build word vectors using gensim.

This is *a lot* of commands. I would love to find away to avoid that. But I think it's important to be able to run or re-run one part of the process without having to rerun everything. Unfortunately some parts depend on each other and the sketched setup does not support specifying any dependencies. On the other hand, I think the only commands that one would try running with different parameters would be the last steps. For example, you could experiment with varying the `dimension` parameter for `init-vectors`.

#### Brown Clusters ####
I do not have a good suggestion for how to fit Brown clusters into the above steps. I believe the spaCy documentation suggests using <https://github.com/percyliang/brown-cluster>. This takes as input a single text file. Further, it's not totally clear to me how the Brown clusters are used in spaCy 2.0? The documentation [briefly mentions Brown clusters](https://spacy.io/usage/adding-languages).

Again, I would be happy to implement this. Let me know what you think :)

**Comment by machakux** [comment]
Regarding initializing vectors (word2vec); may be in order to simplify the implementation the script or the new `init-vectors` command should not be concerned with word frequency counting, could let Gensim deal with it. I tried to do that, and it seems to work so far. What I did can be seen at https://gist.github.com/machakux/8814f9927498c34a08635820088fd55b#file-word_vectors-py . I used spaCy tokenizer, I didn't pay much attention to performance and I generated both binary and text vector files  ( I produced both files because it seems spaCy `init-model` accepts vectors in a text format while the current `word_vectors.py` produces vectors in binary format so I wanted to try both)

I also think although using text vectors is easier and doesn't require Gensim as a dependancy when using **text word2vec** there is a higher possibility of encountering various parsing errors compared to when using Gensim to load the **binary word2vec** directly.
I have encontered this issue multiple times with text vector files created using raw uncleaned text with Gensim. I tried modifying the init-model command to skip lines causing errors and it worked but the resulted accuracy was bad. I then tried loading binary vectors and the issues were resolved.

Would it will be better if the `init-model` command will include a simple option to use binary word2vec file from Gensim?
I mean to allow something like `spacy init-model xx xx_model_name word_freq -v word2vec-file.bin -b` where "-b" is option to indicate the vector is a binary file and not text.

**Comment by honnibal** [comment]
Thanks all for your attention to this, especially @sorenlind for your detailed thoughts.

I've gone back and forth on this problem for a while now. Here's my uncertainty. As @sorenlind notes, the requirements quickly get complicated, introducing the need for different scripts for each step of the process, each with different options etc. There's also no easy way to standardise the input.

I'm worried about making a complicated command line interface that basically needs to be stitched together in a shell script. Running a bunch of commands in a bash script is usually just worse than doing the same thing in a Python script, by using the normal API directly.

So I guess my question is: if the commands get complex enough, are we actually winning here? The libraries themselves (spaCy, Gensim, FastText) have pretty good APIs already. The one that's a real chore is the Brown clusters package, but we can't easily fix its problems by adding scripts.

I do think it's a problem that the current word vectors training script seems to not use spaCy's tokenizer when training Gensim. This definitely looks like a mistake!

Hopefully now that Gensim has memory-efficient frequency counting using count min sketch (its new "bounter" library), I'm optimistic about letting Gensim just do the frequency count, as @machakux suggests. This way we might be able to simplify things nicely.
