### ISSUE TITLE
Custom vectors and upper case 

### ISSUE THREAD

**Issue by ahalterman** [explosion/spaCy#1796]
I've successfully loaded custom vectors into spaCy using [vectors_fast_text.py](https://github.com/explosion/spaCy/blob/master/examples/vectors_fast_text.py) but I've noticed that the vectors for words with upper case letters are all 0. When I use `en_core_web_lg`, though, it has (identical) non-zero vectors for e.g. "green" and "Green". I assumed that spaCy was taking the lower case of a word to look up its vector, but that's not what seems to be happening. I'm trying to figure out the best way to get lower --> upper vector behavior and can think of three approaches:

1. make spaCy always check for an all-lower version of the word in the vector table if the original form doesn't have a vector
2. When adding the vectors, also add the upper case form by setting the `row` to the lowercase word [docs](https://spacy.io/api/vectors#add).
3. The hacky approach: in the `vectors_fast_text.py` code, double the rows and also add as a separate word the upper case version of the word with the same vector [here](https://github.com/explosion/spaCy/blob/master/examples/vectors_fast_text.py#L36). Then use `prune_vectors` with the original `nr_row` to trim back down to the original size.

Which of these do you think is the best way to go about it? Is this something that should be handled by spaCy or by the person loading in the vectors? Thanks in advance for any thoughts/guidance.

## Your Environment

* Operating System: Darwin-16.7.0-x86_64-i386-64bit
* Python Version Used: 3.6.3
* spaCy Version Used: 2.0.5

**Comment by honnibal** [comment]
I think option 2 is best. It's nice to have the option of adding separate upper and lower case entries, so I don't want to make the vector look-up case insensitive. This is just the sort of situation where the row aliasing works well. The row links store very little data --- it's just adding another `(key, offset)` pair; we don't have to store another vector.

**Comment by ahalterman** [comment]
Thanks! It took me a while to get the difference between what was going on in `Vectors` and in `Vocab`. I changed the fasttext example to add by row and clarified a bit in the API docs where a word's `row` is stored: https://github.com/explosion/spaCy/compare/master...ahalterman:master. If this is useful, I can make into a pull request.

And a question on the API docs. When it says ([link](https://spacy.io/api/vectors#add))

> If you need to manage the strings, you should use the Vectors via the Vocab  class 

just to confirm, the example on the side bar does this, right?

**Comment by honnibal** [comment]
The sidebar example *doesn't*, no. Let's say you want something like: associate the word "dog" with a vector, and then retrieve the vector by looking up "dog". Later, you want to get back the pair ("dog", vector). Internally, the `Vectors` class is hashing the string into a `uint64_t`, and throwing away the string. This is fine for retrieval, but you won't be able to iterate the strings, or figure out what the closest string to some vector is.

**Comment by ahalterman** [comment]
Ah, okay. But as long as I just want to save the model and then later look up the vector for "dog" vector, it's all good. 

Let me know if you want the modified example code in a PR, otherwise I think we can close.
