### ISSUE TITLE
The tokenizer return strange results.

### ISSUE THREAD

**Issue by oachan** [explosion/spaCy#1797]
When I only use the function of the broken tokenizer, it returns strange results.
Is this normal?

``` py
import spacy

nlp = spacy.load('en')
doc = nlp(u"d", disable=["tagger", "parser", "ner"])
print u" ".join(w.lemma_ for w in doc)

>> have
```

## Your Environment

* Operating System: 14.04.1-Ubuntu SMP Fri Jan 13 14:54:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Python Version Used: 2.7.12
* spaCy Version Used: 2.0.5

**Comment by honnibal** [comment]
I agree that this looks weird, but it's hard to solve. The `d` here is getting interpreted as the contracted form of "had", e.g. `"he'd"`. Is there another example where you're getting weird results?
