### ISSUE TITLE
Tokenization problem

### ISSUE THREAD

**Issue by supercoderhawk** [explosion/spaCy#1802]
* operation system: Ubuntu 16.04
* Spacy version: 2.0.4

Considering the following content:
* antacids;antihistamines;barbiturates;carbamazepine;
* [(14)C]-diethyl pyrocarbonate

The spacy tokenization result is:
* antacids;antihistamines;barbiturates;carbamazepine;
* [  (  14)C]-diethyl  pyrocarbonate

The first sentence can't be tokenized at all, and the result of second sentence is very strange.

**Comment by ines** [comment]
Merging this with the master issue in #1642!
