### ISSUE TITLE
English language model install fails on windows/ Anaconda

### ISSUE THREAD

**Issue by numericlee** [explosion/spaCy#1803]
Cannot get the lanaguge model to install

Running Python 3.5.4  Anaconda in an environment named MyEnvt on Windows10

**Method #1**
```
conda install -c conda-forge spacy
python -m spacy download en
```

**Result:**
`(MyEnvt) C:\Ajax>python -m spacy validate`

    Installed models (spaCy v2.0.4)
    C:\Ajax\Anaconda2\envs\MyEnvt\lib\site-packages\spacy

    No models found in your current environment.

> (MyEnvt) C:\Ajax>python -m spacy download en
> Traceback (most recent call last):
>   File "C:\Ajax\Anaconda2\envs\MyEnvt\lib\runpy.py", line 183, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "C:\Ajax\Anaconda2\envs\MyEnvt\lib\runpy.py", line 142, in _get_module_details
>     return _get_module_details(pkg_main_name, error)
>   File "C:\Ajax\Anaconda2\envs\MyEnvt\lib\runpy.py", line 109, in _get_module_details
>     __import__(pkg_name)
>   File "C:\Ajax\Anaconda2\envs\MyEnvt\lib\site-packages\pip\__init__.py", line 28, in <module>
>     from pip.vcs import git, mercurial, subversion, bazaar  # noqa
>   File "C:\Ajax\Anaconda2\envs\MyEnvt\lib\site-packages\pip\vcs\mercurial.py", line 9, in <module>
>     from pip.download import path_to_url
>   File "C:\Ajax\Anaconda2\envs\MyEnvt\lib\site-packages\pip\download.py", line 34, in <module>
>     from pip.utils.logging import indent_log
>   File "C:\Ajax\Anaconda2\envs\MyEnvt\lib\site-packages\pip\utils\logging.py", line 66, in <module>
>     class ColorizedStreamHandler(logging.StreamHandler):
>   File "C:\Ajax\Anaconda2\envs\MyEnvt\lib\site-packages\pip\utils\logging.py", line 72, in ColorizedStreamHandler
>     (logging.ERROR, _color_wrap(colorama.Fore.RED)),
> AttributeError: module 'pip._vendor.colorama' has no attribute 'Fore'

**Methods #2 and #3** brought identical error messages

`(MyEnvt) C:\Ajax>python -m spacy download en_core_web_lg`

`pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz`

**Method #4**
download the tarball  https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz  and extract to MyEnvt/Lib/SitePackages/Spacy

didnt help

**Method #5**
`(MyEnvt) C:\Ajax>python -m spacy.en.download all`

**Result:**
C:\Ajax\Anaconda2\envs\MyEnvt\python.exe: Error while finding module specification for 'spacy.en.download' (ImportError: No module named 'spacy.en')

**error In Python** 

```
import spacy as spc
nlp = spc.load('en')
```

> runfile('C:/Ajax/DS/nlp1.py', wdir='C:/Ajax/DS')
> Traceback (most recent call last):
>   File "<ipython-input-6-42bab7684506>", line 1, in <module>
>     runfile('C:/Ajax/DS/nlp1.py', wdir='C:/Ajax/DS')
>   File "C:\Ajax\Anaconda2\envs\MyEnvt\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
>     execfile(filename, namespace)
>   File "C:\Ajax\Anaconda2\envs\MyEnvt\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
>   File "C:/Ajax/DS/nlp1.py", line 11, in <module>
>     nlp = spc.load('en')
>   File "C:\Ajax\Anaconda2\envs\MyEnvt\lib\site-packages\spacy\__init__.py", line 19, in load
>     return util.load_model(name, **overrides)
>   File "C:\Ajax\Anaconda2\envs\MyEnvt\lib\site-packages\spacy\util.py", line 112, in load_model
>     return load_model_from_link(name, **overrides)
>   File "C:\Ajax\Anaconda2\envs\MyEnvt\lib\site-packages\spacy\util.py", line 131, in load_model_from_link
>     return cls.load(**overrides)
> AttributeError: module 'en' has no attribute 'load'

**Comment by ines** [comment]
Thanks for the report and sorry about that – looks like this is related to the same problem as #1780 and #1761, so I will merge it with those issues to keep things in one place.

I've already added a fix for this in PR #1792, so this should be included in the next release!
