### ISSUE TITLE
Lemmas of merged named entities tagged as ORG not updated ?

### ISSUE THREAD

**Issue by Imane0** [explosion/spaCy#1809]
This code: 

    import spacy
    nlp = spacy.load('en')
    string_doc = u'The New York Times is an American newspaper based in New York City.'
    doc = nlp(string_doc)
    for ent in doc.ents:
       if ent.label_ == 'ORG':
         ent.merge(ent.root.tag_, ent.text, ent.label_)

is supposed to collapse consecutive tokens tagged as ORG to one token. However, the *lemma* of the collapsed tokens seems not to be updated. Indeed, when I execute:

    for ent in doc.ents:
      print ent
      print ent.label_
      print ent.lemma_
      print
I get:

    The New York Times
    ORG
    the
    
    American
    NORP
    american
    
    New York City
    GPE
    new york city

whereas I expect something like

    The New York Times
    ORG
    the new york times
    
    American
    NORP
    american
    
    New York City
    GPE
    new york city

Why is the lemma wrong for **ORGs** ?

## Your Environment

* Operating System:  Fedora 26
* Python Version Used: 2.7
* spaCy Version Used: 2.0.4
* Environment Information:

**Comment by honnibal** [comment]
You should be able to set the lemma using the `lemma` keyword argument to `ent.merge()`. The code avoids trying to be "smart" and guess what the lemma will be, since the lemma of a concatenated token doesn't necessarily need to be the concatenation of those tokens.
