### ISSUE TITLE
global name 'ORTH' is not defined

### ISSUE THREAD

**Issue by moskalenko** [explosion/spaCy#1811]
Even though a spacy build on centos 6 (gcc5, python-2.7.10) completes without errors spacy is not immediately usable:

  File "/apps/gcc/5.2.0/python/2.7.10/lib/python2.7/site-packages/spacy-2.0.5-py2.7-linux-x86_64.egg/spacy/util.py", line 339, in <genexpr>
    for attr in token_attrs):
NameError: global name 'ORTH' is not defined

$ nm spacy-2.0.5-py2.7-linux-x86_64.egg/spacy/symbols.so  | grep ORTH
000000000001ae0f r _ZL12__pyx_k_ORTH
0000000000220598 b _ZL14__pyx_n_u_ORTH

## Info about spaCy

* **Python version:** 2.7.10
* **Platform:** Linux-2.6.32-642.6.2.el6.x86_64-x86_64-with-redhat-6.8-Santiago
* **spaCy version:** 2.0.5
* **Models:** en

**Comment by honnibal** [comment]
First guess: have you checked that the version of Python that's importing spaCy is the same one used by pip when installing?

**Comment by moskalenko** [comment]
Yes.

**Comment by honnibal** [comment]
Please try again with the latest version of spaCy -- I still suspect it's an issue of the wrong Python environment being used.
