### ISSUE TITLE
Question: Licenses for spaCy language models

### ISSUE THREAD

**Issue by lzhao7812** [explosion/spaCy#1812]
Is there any reasons why spaCy language models use different licenses such as CC BY-SA 3.0 from spaCy MIT license? CC BY-SA 3.0 license is strongly discouraged to use in our company since it has to be distributed as Separately Licensed Code.

**Comment by honnibal** [comment]
Thanks for bringing this up.

I've been reading more about the CC-BY-SA license and it's actually more restrictive than I thought, and I don't like how murky the definition of derivative works is. We're thinking about what to do.

The most obvious solution is to use the MIT license, but the models aren't really "software", they're data assets. So the terms don't seem to apply.

Thoughts on preferred license?

**Comment by lzhao7812** [comment]
Thanks for quick response!

I would think it makes more sense to have the same license as spaCy which is MIT, but you do have a point. 

The Creative Common has a public domain dedication (CC0 : https://creativecommons.org/publicdomain/zero/1.0/legalcode) seems to be a good candidate since it allows the datasets owner to dedicate the datasets to public domain under applicable laws. 

However, I am a developer, and know little about legal side of things... Please let you know your decision if the model license will be changed. Thanks!

**Comment by lzhao7812** [comment]
Hi,

I consulted with our legal for suggestions, and they suggested the simplest CC license which is called the Creative Commons Attribution license ("[CC-BY](https://creativecommons.org/licenses/by/4.0/legalcode)"). 

Please take a look at that. Thanks

Lin

**Comment by ines** [comment]
@lzhao7812 Thanks! This sounds reasonable – we'll think about the best strategy for changing the model licenses and get some advice as well.

**Comment by lzhao7812** [comment]
@ines / @honnibal Hi, just wondering if there are any updates on this topic? Thanks!

**Comment by lzhao7812** [comment]
Hi again, 

We have to decide if we can keep using Spacy as our NLP engine or not in our product. And this really depends on if the license of the language models can be changed. The engine fits our needs very well, but the license prevents us from using it. Please consider the alternatives for the model licenses if possible. 

Thanks

**Comment by honnibal** [comment]
@lzhao7812 Thanks for your patience on this.

We'll be changing our default policy from CC-BY-SA to CC-BY, starting with the v2.1.0 models. We should have the v2.1.0 models up within the next two weeks. We won't be able to make all models CC-BY though --- for instance, if we only have a CC-BY-NC license to the treebank, models have to be CC-BY-NC as well.

If you need more details about this, the quickest way would be to email me: matt@explosion.ai

**Comment by darkdreamingdan** [comment]
What does this mean for models with GPL source data, such as the Spanish Spacy 2.0 model?
