### ISSUE TITLE
Adding new Language class without modifying the core library code

### ISSUE THREAD

**Issue by machakux** [explosion/spaCy#1816]
Will it be better if spaCy will provide a more extensive support for Language classes defined outside the library source code?

According to the [documentation](http://spacy.io/usage/adding-languages) in order to add a new Language class properly you will need to **modify the library's code**. I think this reduces spaCy's flexibility/extensibility and adds some inconvenience in mantaining user defined Language classes.

Currently if a Language class is defined outside spaCy it will work in some cases but in some cases including some CLI commands and getting noun_chunks it will fail probably because of relying on `util.get_lang_class()` function which only checks for language data within the spaCy library.

In some cases like CLI commands it is not very difficult to create separate custom commands as a work-around but for core functionalities like noun_chunks generation ([_get_chunker](https://github.com/explosion/spaCy/blob/f29c3925eeba4b3720412f490bdd2b2991303b3c/spacy/tokens/doc.pyx#L71)) it seems there is no clear alternative.
Are there other alternative to allow getting noun_chunks when using Language class defined outside spacy directory?

Thank you very much for creating, sharing and mantaining spaCy.

## Info about spaCy

* **spaCy version:** 2.0.5
* **Platform:** Linux-4.4.0-93-generic-x86_64-with-Ubuntu-14.04-trusty
* **Python version:** 3.6.3

**Comment by honnibal** [comment]
This is now addressed by #2348, which adds entry-point hooks.

**Comment by honnibal** [comment]
And now done by #3080
