### ISSUE TITLE
Matcher is too slow processing text

### ISSUE THREAD

**Issue by sandeep118** [explosion/spaCy#1819]
I built a matcher & phrase matcher object which has 10 lakh patterns. For some reason Matcher is taking very long time to process a document ( > 5 mins for each doc) and phrase matcher is doing it in a second on the same data. 

I don't know if I am missing something here, but any help is much appreciated.

The reason I need to use Matcher instead of phrase matcher because:

Ex: I have a text file with many phrases such as "United State Of America"  
I built phrase matcher object using the above. In the test document if there is phrase 
"United State Of \n America" phrase matcher will not return a match because of the extra newline character. Whereas in Matcher I can customize the pattern by adding various things like {'ORTH':'\n','OP':'*'}.

## Your Environment

* **spaCy version:** 2.0.5
* **Platform:** Darwin-17.2.0-x86_64-i386-64bit
* **Python version:** 3.6.0
* **Models:** en_core_web_lg

**Comment by ines** [comment]
Merging this with the master issue #1971!
