### ISSUE TITLE
How to use spacy in large dataset with short sentences efficiently?

### ISSUE THREAD

**Issue by tonywangcn** [explosion/spaCy#1821]
https://stackoverflow.com/questions/48199353/how-to-use-spacy-in-large-dataset-with-short-sentences-efficiently

## Your Environment

* Operating System: 
* Python Version Used: 
* spaCy Version Used: 
* Environment Information: 

Info about spaCy

    spaCy version      2.0.5          
    Location           /opt/conda/lib/python3.6/site-packages/spacy
    Platform           Linux-4.4.0-103-generic-x86_64-with-debian-stretch-sid
    Python version     3.6.3          
    Models             en, en_default

**Comment by adam-ra** [comment]
If it's possible, use nlp.pipe to parralelise processing. If not, vote for https://github.com/explosion/spaCy/issues/1508 :)
