### ISSUE TITLE
is_oov returns True for common values of DEP, TAG, etc.

### ISSUE THREAD

**Issue by danielhers** [explosion/spaCy#1822]
The semantics of `is_oov` are not entirely clear to me. Is it supposed to return `True` only for out-of-vocabulary _words_? What about other vocabulary elements?
Example:

    >>> import spacy
    >>> nlp = spacy.load("en_core_web_lg")
    >>> doc = nlp("John loves Mary")
    >>> nlp.vocab[doc[0].dep].text
    'nsubj'
    >>> nlp.vocab[doc[0].dep].is_oov
    True
    >>> nlp.vocab[doc[1].dep].text
    'ROOT'
    >>> nlp.vocab[doc[1].dep].is_oov
    False

I suppose `'ROOT'` is not out-of-vocabulary because it's also a word, while `'nsubj'` isn't.

My use-case is that I use spaCy for feature extraction for my classifier, and then I save the extracted feature matrix (of numeric IDs) to a file so I can use it later in training without even having to `import spacy`. I'd like to treat out-of-vocabulary symbols as "unknown", so my classifier won't even have to allocate elements for them in the embeddings lookup table. However, it seems like I can't use this strategy since I certainly don't want to treat `'nsubj'` as "unknown". Should I just apply this rule only for `ORTH` and `LEMMA` features?

## Info about spaCy

* **Python version:** 3.5.2+
* **spaCy version:** 2.0.5
* **Platform:** Linux-4.8.4-aufs-1-x86_64-with-debian-stretch-sid
* **Models:** en_core_web_lg

**Comment by honnibal** [comment]
Thanks for the report.

Merging with #1574 as the underlying issue is the sme.
