### ISSUE TITLE
how to use the spacy trainned model with the restful service 

### ISSUE THREAD

**Issue by sahasrara62** [explosion/spaCy#1823]
i have  trained a  name entity model   . and now i want to use it via restful service( like deploy model on server and then make the restful service calls to the server then fetching the result ). i  have no experience of web and restful service now and less to little knowledge of restful api . 
help me how to make a wrapper outside the model to make the rest api call to model and get the result .  

## Info about spaCy

* **spaCy version:** 2.0.4
* **Models:** en, en_core_web_md, en_core_web_sm, en_core_web_lg
* **Platform:** Linux-4.10.0-42-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.5.4

**Comment by ines** [comment]
If you're completely new to REST APIs and developing web APIs in Python in general, I'd definitely recommend starting with this topic first. I know, this is not the most satisfying answer, but it'll make things a lot easier, and also help you debug your code if things go wrong. But I definitely believe in "learning by doing", so here are some resources to get you started.

[Flask](http://flask.pocoo.org/) is probably the most popular library for web APIs in Python. You'll find a lot of tutorials, example code and documentation online. I also highly recommend [Hug](https://github.com/timothycrosley/hug), which is a little more lightweight and simpler in my opinion. Hug is based on [Falcon](https://falconframework.org/), which you could also check out. Just try our different libraries and see which one you like best.

For example, let's say you want to load the small English model, and have an endpoint `/get_entities` that you can post a string of text to, and that will return a list of entities found in the text. When you start your service, you can create your `nlp` object and load the model. Your endpoint can then receive a text, process it and create a `Doc` object, extract the relevant annotations (part-of-speech tags, entities, etc.) and return them.

Using hug, your code could look something like this:

```python
import hug
import spacy

nlp = spacy.load('en_core_web_sm')

@hug.post('/get_entities')
def get_entities(text):
    doc = nlp(text)
    entities = [{'text': ent.text, 'label': ent.label} for ent in doc.ents]
    return {'entities': entities}
```

When you make a POST request to your `/get_entities` endpoint, you'll then receive a response like:

```json
{
    "entities": [
        {"text": "Facebook", "label": "ORG"},
        {"text": "Mark Zuckerberg", "label": "PERSON"}
    ]
}
```

If you want to use a library that was developed for use with spaCy, have a look at [`spacy_api`](https://github.com/kootenpv/spacy_api). It has a lot of nice features for loading models, and comes with a command line interface and caching solutions. It might be a little complex if you're only getting started, but you can bookmark it for later.

**Comment by sahasrara62** [comment]
@ines thanks for help
