### ISSUE TITLE
 Preshed build failure

### ISSUE THREAD

**Issue by sathik11** [explosion/spaCy#1824]
* Operating System: Linux
* Python Version Used: Python 3.5
* spaCy Version Used: 1.9.0
* Environment Information:  Amazon Linux AMI - ec2 instance

I tried to do spacy install on my new ec2 instance . but its unable to build the preshed package
check the error log

`Building wheels for collected packages: preshed
  Running setup.py bdist_wheel for preshed ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokeni                                                                                                                                                             ze;__file__='/tmp/pip-build-jt3d594f/preshed/setup.py';f=getattr(tokenize, 'open                                                                                                                                                             ', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(co                                                                                                                                                             de, __file__, 'exec'))" bdist_wheel -d /tmp/tmpl121y1lepip-wheel- --python-tag c                                                                                                                                                             p35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/preshed
  copying preshed/__init__.py -> build/lib.linux-x86_64-3.5/preshed
  copying preshed/about.py -> build/lib.linux-x86_64-3.5/preshed
  creating build/lib.linux-x86_64-3.5/preshed/tests
  copying preshed/tests/test_pop.py -> build/lib.linux-x86_64-3.5/preshed/tests
  copying preshed/tests/test_counter.py -> build/lib.linux-x86_64-3.5/preshed/te                                                                                                                                                     sts
  copying preshed/tests/__init__.py -> build/lib.linux-x86_64-3.5/preshed/tests
  copying preshed/tests/test_hashing.py -> build/lib.linux-x86_64-3.5/preshed/te                                                                                                                                                             sts
  copying preshed/maps.pyx -> build/lib.linux-x86_64-3.5/preshed
  copying preshed/counter.pyx -> build/lib.linux-x86_64-3.5/preshed
  copying preshed/__init__.pxd -> build/lib.linux-x86_64-3.5/preshed
  copying preshed/maps.pxd -> build/lib.linux-x86_64-3.5/preshed
  copying preshed/counter.pxd -> build/lib.linux-x86_64-3.5/preshed
  running build_ext
  building 'preshed.maps' extension
  creating build/temp.linux-x86_64-3.5
  creating build/temp.linux-x86_64-3.5/preshed
  gcc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DDYNAMIC_AN                                                                                                                                                             NOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexcept                                                                                                                                                             ions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOUR                                                                                                                                                             CE -fPIC -fwrapv -fPIC -I/usr/include/python3.5m -I/tmp/pip-build-jt3d594f/presh                                                                                                                                                             ed/include -I/usr/include/python3.5m -c preshed/maps.cpp -o build/temp.linux-x86                                                                                                                                                             _64-3.5/preshed/maps.o -O3 -Wno-strict-prototypes -Wno-unused-function
  gcc: error trying to exec 'cc1plus': execvp: No such file or directory
  error: command 'gcc' failed with exit status 1
`

I did a PIP install and also try to download the source from PyPI . both failed

Seems cannot compile maps c++ file. 
Is it due to gcc compiler version ? I installed gcc 6.4.1 (should this be downgraded to version 4?) 
I haven't faced such error earlier with other ec2 instances [gcc compiler were 4.8]

**Comment by honnibal** [comment]
Have you installed the `python-dev` package for the version of Python you're using? This might be either `python-dev`, `python3-dev`, python3.5-dev` or something similar, depending on the distribution.

Btw, check out either spaCy 1.10 or spaCy v2 when you're ready to upgrade :)

**Comment by sathik11** [comment]
I did install the python-dev packages ..But it doesnt help. 
I also tried for spaCy 1.10 - it too fails with same message

I already have reported an issue with spaCy v2 which stops me from installing it now .

**Comment by clicksprout** [comment]
Looks like the host is missing g++ package. Installing this did the trick for me.

# sudo yum install gcc-c++
