### ISSUE TITLE
Token stems available for Matcher via vocab or Token custom attributes

### ISSUE THREAD

**Issue by adam-ra** [explosion/spaCy#1825]
Matching based on stems seems to work better for my domain than when patterns are expressed using lemmas. I'm using a third party library for stemming.
So, I wanted to be able to write Matcher rules that would capture sequences of stems.
I've added a custom processing component to `nlp.pipeline` that would enrich each `Token` with a `stem` attribute/extension (using `_`). This way stems are already available for each parsed document.
This all looked good until I saw @ines explaining that custom attributes are not available for Matcher rules (https://github.com/explosion/spaCy/issues/1499).
Vocab-level variables could also be a viable solution if there was a string-type variant, not just Boolean flags.
Do you think it is even doable? It would be a huge advantage to be able to capture matches using derived features. Stems aren't the only possibility, the other useful idea is to generalise lemmas with a synonym dictionary (change to a preferred head word).

**Comment by honnibal** [comment]
The attribute needs to be stored in the C struct in order to use the pattern in the matcher, so we can't use the extension attributes. I think the C data should probably have a pointer to hold user-defined string features.

In the meantime, could you assign your stems to the `lemma` attribute? The lemma isn't used as a feature in the statistical models, so you can customise it if you like.

**Comment by adam-ra** [comment]
I didn't know token's `lemma` attribute was mutable :)
This hack will be instantly useful for abstracting from some safe synonyms, but, other than that, it's going to be somewhat cumbersome to get rid of lemmas entirely. Theoretically I could base everything on stems but stemmers are somewhat unpredictable and it would make maintenance harder. I need to analyse this. Thanks a lot for help!
