### ISSUE TITLE
Error in init_model cli command

### ISSUE THREAD

**Issue by jarozajac** [explosion/spaCy#1832]
the init_model command fails during the Creating model step with error

> Traceback (most recent call last):
>   File "/home/ec2-user/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/ec2-user/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/ec2-user/spaCy/spacy/__main__.py", line 31, in <module>
>     plac.call(commands[command], sys.argv[1:])
>   File "/home/ec2-user/anaconda3/lib/python3.6/site-packages/plac_core.py", line 328, in call
>     cmd, result = parser.consume(arglist)
>   File "/home/ec2-user/anaconda3/lib/python3.6/site-packages/plac_core.py", line 207, in consume
>     return cmd, self.func(*(args + varargs + extraopts), **kwargs)
>   File "/home/ec2-user/spaCy/spacy/cli/init_model.py", line 42, in init_model
>     nlp = create_model(lang, probs, oov_prob, clusters, vectors_data, vector_keys, prune_vectors)
>   File "/home/ec2-user/spaCy/spacy/cli/init_model.py", line 73, in create_model
>     nlp.vocab.vectors = Vectors(data=vectors_data, keys=vector_keys)
>   File "vectors.pyx", line 56, in spacy.vectors.Vectors.__init__
> AttributeError: 'tuple' object has no attribute 'shape'
> 

The problem is, that in init_model.py
> vectors_data, vector_keys = read_vectors(vectors_loc) if vectors_loc else None, None

returns vectors_data as a tuple instead of numpy array, it's caused by 1 of the latest merges adding the second "None" part in the if

The second error in init_model.py is caused by this line:

> if vectors_data:

It produces another exception:

> Traceback (most recent call last):
>   File "/home/ec2-user/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/ec2-user/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/ec2-user/spaCy/spacy/__main__.py", line 31, in <module>
>     plac.call(commands[command], sys.argv[1:])
>   File "/home/ec2-user/anaconda3/lib/python3.6/site-packages/plac_core.py", line 328, in call
>     cmd, result = parser.consume(arglist)
>   File "/home/ec2-user/anaconda3/lib/python3.6/site-packages/plac_core.py", line 207, in consume
>     return cmd, self.func(*(args + varargs + extraopts), **kwargs)
>   File "/home/ec2-user/spaCy/spacy/cli/init_model.py", line 42, in init_model
>     nlp = create_model(lang, probs, oov_prob, clusters, vectors_data, vector_keys, prune_vectors)
>   File "/home/ec2-user/spaCy/spacy/cli/init_model.py", line 72, in create_model
>     if vectors_data:
> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Both lines were changed in the same merge.

## Info about spaCy
* Operating System: Linux
* **spaCy version:** 2.0.5
* **Platform:** Linux-4.9.70-2.243.amzn2.x86_64-x86_64-with-glibc2.9
* **Python version:** 3.6.3

**Comment by ines** [comment]
Thanks and sorry about that. This has already been fixed in #1789 and will be included in the next release!

**Comment by jarozajac** [comment]
I had a problem with it with the the latest master branch I have downloaded today, are you sure it is fixed?
