### ISSUE TITLE
Sentences boundaries not serialized / deserialized with custom SBD component

### ISSUE THREAD

**Issue by thomasopsomer** [explosion/spaCy#1834]
Hi,

I'm using a SBD component to access sentences without parsing the document.
I just noticed that after serialization, and deserialization I lose the information about sentence boundaries. To reproduce:
```python
import spacy

nlp = spacy.load("en", disable=["parser"])
nlp.add_pipe(spacy.pipeline.SentenceSegmenter(nlp))
doc = nlp("First sentence. And a second sentence")

assert len(list(doc.sents)) > 1   # Success

new_doc = spacy.tokens.Doc(nlp.vocab).from_bytes(doc.to_bytes())
assert len(list(new_doc.sents)) > 1   # Fail

```
## Info about spaCy

* **spaCy version:** 2.0.5
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **Python version:** 3.6.2
* **Models:** en

**Comment by honnibal** [comment]
Thanks for the report and example code. I believe this is the same issue as #1799 , so I'll close this one (can't wait for 'merge issues' in Github...)

**Comment by honnibal** [comment]
Scratch that --- this is a different problem. Reopening.

**Comment by thomasopsomer** [comment]
I found a solution, also fixing related other bugs such as wrong `is_parsed`, `is_tagged` flag after deserialization. I'll submit soon

**Comment by honnibal** [comment]
Many thanks!
