### ISSUE TITLE
how to tweak hyper parameters like from "optimizer_B1" to " optimizer_B2" ?

### ISSUE THREAD

**Issue by prashant334** [explosion/spaCy#1838]
@ines @honnibal

    Python version: 2.7.6
    Platform: Linux-3.16.0-77-generic-x86_64-with-Ubuntu-14.04-trusty
    spaCy version: 2.0.0a17
    Models: en, en_core_web_sm, xx_ent_wiki_sm

**parser_hidden_depth=2 parser_maxout_pieces=1 train-parser** this command  is provided in documentation of API ,  but I am not getting where this command should be executed and what should be the syntax for changing optimizer b1 to b2 ?

**Comment by honnibal** [comment]
Those are environment variables, used when you're training spaCy via the command line commands.
