### ISSUE TITLE
Difference in results of dependency parsers of Spacy vs Stanford

### ISSUE THREAD

**Issue by rameshjesswani** [explosion/spaCy#1844]
I am trying to implement same code in Stanford as well as Spacy. I observed there is little difference in result of dependency parsers of Spacy and Stanford. Is it possible to get differences between relations? Like what relation in Stanford is named in Spacy? 

Thanks very much :)

**Comment by honnibal** [comment]
The answer will depend on which Stanford model you're using. If you're using UD dependencies in Stanford, unfortunately the mapping won't be one-to-one. You can find a description of the dependency conversion we're using here: https://spacy.io/api/annotation
