### ISSUE TITLE
Dependency parse training data (English and Arabic) in OntoNotes?

### ISSUE THREAD

**Issue by ahalterman** [explosion/spaCy#1846]
I've obtained OntoNotes as part of a project that's making a spaCy model for Arabic. We're focused on Arabic NER (#1277), but would also like to make a full Arabic spaCy model to contribute to the community.  When I look at the OntoNotes 5.0 release, though, I don't see any dependency parsed data for English or Arabic, only constituency parses. I noticed that the [old code](https://github.com/explosion/spaCy/blob/e140e03516845cd1bc507420c2bcbe1f3ae6571c/bin/prepare_treebank.py#L164) to convert OntoNotes into spaCy format is looking for `.parse.dep` files that I don't have. Is this a problem with the data I got from LDC? Or am I missing something here? Thanks for any advice you have.

**Comment by honnibal** [comment]
The files need to be converted to dependencies with a converter. It's a bit of a pain, because the converters require some language-specific rules.

I used the ClearNLP converter for the English model. I'm not sure whether it supports Arabic. I think CoreNLP does though.

**Comment by ahalterman** [comment]
Thanks! Glad to know I wasn't going crazy. I'll look into a converter for it. 

There's not very much natively dependency parsed Arabic data out there. As far as I can tell, it's just the Universal Dependencies Arabic/Prague/CoNLL [corpus](https://github.com/UniversalDependencies/UD_Arabic) and a small [corpus](https://www.cs.cmu.edu/~ark/ArabicDeps/) from Wikipedia.

There's another LDC [corpus](https://catalog.ldc.upenn.edu/LDC2016T18) that has Arabic dependency parses, but it's automatically converted from constituency parses.
