### ISSUE TITLE
Cannot process a txt file with spacy

### ISSUE THREAD

**Issue by revolucion09** [explosion/spaCy#1851]
Hi all,

I am trying to load an english text file but failing to do so, I am following spacy website 101 tutorial:
```
ff = io.open('moby_dick.txt', 'r', encoding='utf-8')
nlp(ff)
ff.close()
```
```
TypeError                                 Traceback (most recent call last)
<ipython-input-20-f474742159a7> in <module>()
      1 ff = io.open(files[7], 'r', encoding='utf-8')
----> 2 nlp(ff)
      3 ff.close()

~/.local/lib/python3.5/site-packages/spacy/language.py in __call__(self, text, disable)
    327             ('An', 'NN')
    328         """
--> 329         doc = self.make_doc(text)
    330         for name, proc in self.pipeline:
    331             if name in disable:

~/.local/lib/python3.5/site-packages/spacy/language.py in make_doc(self, text)
    355 
    356     def make_doc(self, text):
--> 357         return self.tokenizer(text)
    358 
    359     def update(self, docs, golds, drop=0., sgd=None, losses=None):

TypeError: Argument 'string' has incorrect type (expected str, got _io.TextIOWrapper)
```

## Your Environment

* **spaCy version:** 2.0.5
* **Platform:** Linux-4.13.0-26-generic-x86_64-with-LinuxMint-18.3-sylvia
* **Models:** en
* **Python version:** 3.5.2

**Comment by bwj-GitHub** [comment]
I wasn't aware that nlp could take a file; you should read the file first: `nlp(ff.read())`.

**Comment by revolucion09** [comment]
Oh. I see. I took the idea from the example in the serialization section.

https://spacy.io/usage/spacy-101#serialization

**Comment by ines** [comment]
Sorry – this is a mistake in the example, it's indeed missing the `.read()`. Fixing! We might also update the example to not use Moby Dick and a made-up filename instead (like `customer_feedback_627.txt`, which we use in the lightning tour example [on the homepage](https://spacy.io/)). Loading and parsing a large document like this in one is actually not the best strategy, especially in spaCy v2.0. For better performance, you'd usually want to split up the text and use `nlp.pipe`, which returns a generator.
