### ISSUE TITLE
For customized NER training , to train model does LSTM is used?

### ISSUE THREAD

**Issue by prashant334** [explosion/spaCy#1853]
@ines @honnibal    IN BELOW CODE FOR TRAINING CUSTOMIZED NER MODEL DOES LSTM NEURAL NETWORK IS USED?

  for batch in minibatch(get_gold_parses(nlp.make_doc, train_data), size=3):
            docs, golds = zip(*batch)
            nlp.update(docs, golds, losses=losses, sgd=optimizer,
                       drop=0.35)

**Comment by honnibal** [comment]
Please see https://github.com/explosion/spaCy/issues/1864
