### ISSUE TITLE
The * operator exhibits strange behavior

### ISSUE THREAD

**Issue by GregDubbin** [explosion/spaCy#1855]
## Your Environment

* **Python version:** 2.7.14
* **Platform:** Darwin-17.2.0-x86_64-i386-64bit
* **spaCy version:** 2.0.5
* **Models:** en_core_web_sm

The '+' and '*' operators are not behaving as expected.  For example
```python
doc = en_tokenizer("( A B B A A A A A B ) .")
matcher = Matcher(doc.vocab)
matcher.add('A+',None, [
        {
            'ORTH':u'A',
            'OP':'1'
        },
        {
            'ORTH':u'A',
            'OP':'*'
        }
    ])
print matcher(doc)
```
expected: 
```
[(16885048410399321887L, 1, 2), (16885048410399321887L, 4, 9)]
```
actual: 
```
[(16885048410399321887L, 1, 2),
 (16885048410399321887L, 4, 6),
 (16885048410399321887L, 5, 7),
 (16885048410399321887L, 6, 8),
 (16885048410399321887L, 7, 9),
 (16885048410399321887L, 8, 9)]
```

The matcher captures every pair of A's but fails to merge the contiguous block of A's.  Additionally, the matches are overlapping, which isn't consistent with the behavior of re.findall.

**Comment by GregDubbin** [comment]
I have created a fix for this bug in my own fork of spaCy with some additional enhancements to allow greedy matching on the '*' operator regardless of it's location in the pattern.  The fact that each spec in a pattern can only have one operator and patterns don't allow grouping means that this can be done without backtracking.

Let me know if you would like me to create a Pull Request

**Comment by honnibal** [comment]
@GregDubbin This would be hugely helpful! Further discussion of the current matcher problems can be found here: https://github.com/explosion/spaCy/issues/1503

**Comment by ines** [comment]
Merging this with #1503!
