### ISSUE TITLE
Applying spacy to pandas

### ISSUE THREAD

**Issue by jeweinberg** [explosion/spaCy#1858]
I was wondering what is the best way that is recommended to apply spacy nlp to a pandas dataframe that contains a doc in each row?

I am trying to apply a trained model to about 250,000 rows and it is taking a long time to process. Is there a better strategy to applying spacy to text rather than looping through the rows and calling nlp on each row separately?

example:

df.apply(lambda x: spacy.nlp(x['txt']))

**Comment by honnibal** [comment]
You want to be using the `nlp.pipe()` command, on a sequence of texts.

**Comment by jeweinberg** [comment]
Ah thank you! I missed that in your documentation.
