### ISSUE TITLE
How to change the vectors of an existing model?

### ISSUE THREAD

**Issue by znat** [explosion/spaCy#1859]
I want to use fast-text vectors. However, if I load the vectors [as described here](https://spacy.io/usage/vectors-similarity#custom-loading-other) and save them with `nlp.to_disk()`, the model will only have vectors, but not the POS or the tokenizer.
Is it possible to replace the vectors of an existing model?

**Comment by honnibal** [comment]
You should be able to customize the vectors of the `en_core_web_sm` model without interfering with the other components, as we didn't use pre-trained vectors on that model. However, be careful customising the vectors of the `en_core_web_lg` model. That model was trained with the GloVe vectors, so if you replace those features with different ones, the results will be bad.

There are a few more open issues with customising the word vectors currently, so it's possible you'll encounter some bugs. We're working to improve this, especially for FastText. We'd like to have the subword features from the FastText vectors as well. There's currently an open enhancement issue about this.
