### ISSUE TITLE
Extraction of main root from dependency parser

### ISSUE THREAD

**Issue by IrfanKhanTanoli** [explosion/spaCy#1860]
Hi guys,

This is my sentence:
"We collect the content and other information you provide when you use our Services"
i have this dependency parser: 
![tree_p1](https://user-images.githubusercontent.com/10742585/35107654-d26786ec-fc71-11e7-9274-ca4e0b076594.png)

1) I want only want to extract verb main root i.e. collect  not 'provide' and 'user'.
2) If i want to extract only provide, i have this code:

This is the code.
`1(` for possible_verb in doc:
    if possible_verb.head.pos == VERB and possible_verb.dep_==root:
        print("action is",possible_verb.head.lemma_ )

2) if possible_verb.head.pos == VERB and `possible_verb.head.dep==(relcl)`

There appear this error
Traceback (most recent call last):
possible_verb.head.dep==relcl:
NameError: name 'relcl' is not defined

Please suggest the ans
## Your Environment

* Operating System: Windows 10
* Python Version Used:  3.5
* spaCy Version Used: 2.0.5
* Environment Information:

**Comment by honnibal** [comment]
1. You should be able to check whether a word is its own head with `word.head == word` to see if a word is a root. Alternatively you can check the dependency label with `token.dep_`. If you have a `Span` object, you can also use the `span.root` property. For instance, you might get the root of all sentences with `[sent.root for sent in doc.sents]`.

2. You can either check the string content of the label with the `dep_` property, or you can import the `relcl` symbol from `spacy.symbols`.

**Comment by IrfanKhanTanoli** [comment]
Thanks for the reply. 
But when i import relcl it generates this error:
    from spacy.symbols import relcl
ImportError: cannot import name 'relcl'
