### ISSUE TITLE
spacy sometimes hangs when loading model

### ISSUE THREAD

**Issue by wkerzendorf** [explosion/spaCy#1863]
## Info about spaCy

* **spaCy version:** 2.0.4
* **Platform:** Linux-2.6.32-642.11.1.el6.x86_64-x86_64-with-redhat-6.7-Carbon
* **Python version:** 3.6.4
* **Models:** en_core_web_lg

Sometimes spacy loads the same model within a few tens of seconds - sometimes it seemingly hangs. See example

```
(deepthought3) [wkerzend@gilliam nb_process]$ python
Python 3.6.4 | packaged by conda-forge | (default, Dec 23 2017, 16:31:06) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> spacy.load('en_core_web_lg')
```

**Comment by honnibal** [comment]
Could there be an issue with your memory availability, or perhaps an issue with disk performance if you're using a VM?

It's difficult to debug a periodic problem like this. I can say that it hasn't been hanging indefinitely on any of my machines. You might try watching the process with `top` and `perf top` in another window to see what's going on.

**Comment by wkerzendorf** [comment]
It's a very big machine with 500 gigs of memory. And local disk. I was wondering if there are specific problems with loading the same time  in multiple python instances (that maybe something is written to the model)

**Comment by honnibal** [comment]
I can't think what could be causing that, as everything is just using normal Python file opens. If the problems persist with current versions, please reopen this.
