### ISSUE TITLE
spacy for comment classification into technical and generic categories

### ISSUE THREAD

**Issue by rajrocksdeworld** [explosion/spaCy#1873]
##comment classification
for comments classification, i wan to use spacy
can anyone guide me how to start

**Comment by honnibal** [comment]
The more general term that people use for the type of model you're interested in is "text classification". You can have a look at an example of using spaCy's built-in text classifier here: https://github.com/explosion/spaCy/blob/master/examples/training/train_textcat.py

For background information about how the solution is designed, you could read this blog post about solving NLP problems with neural networks: https://explosion.ai/blog/deep-learning-formula-nlp

If you don't have training data for your problem yet, you might try our new annotation tool: https://prodi.gy . We have an instruction video showing how to train a new model: https://www.youtube.com/watch?v=5di0KlKl0fE

If the models within spaCy don't work well for you, there are also good text classification algorithms implemented in scikit-learn. Facebook's FastText tool is also very popular.
