### ISSUE TITLE
Import error 'relcl'

### ISSUE THREAD

**Issue by IrfanKhanTanoli** [explosion/spaCy#1878]
Hi,
When i try to import relcl, it prompt the error.

from spacy.symbols import relcl
ImportError: cannot import name 'relcl'

## Your Environment

* Operating System: windows 10
* Python Version Used: 3.5
* spaCy Version Used:  2.0
* Environment Information:

**Comment by ines** [comment]
See #1903!

**Comment by ChangeMyName** [comment]
the symbols module still missing relcl. however the following works:
`            if (token.dep == 7972625988311165362):
                entities.append(token.head.text)`
