### ISSUE TITLE
Is that possible to modify the parsing result from dependency tree

### ISSUE THREAD

**Issue by Zhenshan-Jin** [explosion/spaCy#1880]
Hi spaCy team,

The problem is that some dependency parsing result from spaCy is not satisfying and I want to make some change to the dependency parsing result, e.g. modify tok.children list

I'm wondering if there is an API that could allow me to do that.

Thanks

## Your Environment

* Operating System: Ubuntu 16.04
* Python Version Used: 3.6
* spaCy Version Used: 2.0.5
* Environment Information:

**Comment by honnibal** [comment]
Sorry for missing this before.

The parse tree can't be set attribute-by-attribute, to avoid consistency problems. However, you can set the parse by using the method `doc.from_array([HEAD, DEP])` --- the argument `[HEAD, DEP]` indicates that your array of attributes will have two columns: the first for the head, the second for the dependency label. The head ID needs to be an offset relative to the token index. The root word will have offset 0. Offset 1 means the head is the following word. The values in the dep column should be hash IDs.
