### ISSUE TITLE
ValueError: shapes (7,0) and (300,128) not aligned: 0 (dim 1) != 300 (dim 0)

### ISSUE THREAD

**Issue by rsilveira79** [explosion/spaCy#1884]
Hello
I'm using new Spacy (2.0.5) for NER extraction. I'm testing NER using both 'en', 'en_core_web_md' and 'en_core_web_lg'.
For models 'en_core_web_md' and 'en_core_web_lg', I can run one time and load the models, but after some executions I started to have the error below.
Can you help me with this?
ops.pyx in thinc.neural.ops.NumpyOps.batch_dot()
ValueError: shapes (7,0) and (300,128) not aligned: 0 (dim 1) != 300 (dim 0)
## Your Environment ##
* **spaCy version:** 2.0.5
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **Python version:** 3.6.3
* **Models:** en, en-large, en-lg, en-md, en_core_web_md

**Comment by honnibal** [comment]
Thanks for the report. I think this is the same error as #1660 , so closing this to keep the discussion in one place.
