### ISSUE TITLE
Question regarding portuguese NER training corpus

### ISSUE THREAD

**Issue by pvcastro** [explosion/spaCy#1886]
Is it possible to have access to the training corpus that was used for training the models?

Specifically, I was looking for the "Universal Dependencies and WikiNER" corpus that was used for training the portuguese NER model. 

Is there any place I can find additional information regarding the training process, such as model architecture and parameters used. 

Thanks!

**Comment by ines** [comment]
Sure! Here are some links that should hopefully answer your questions:

* [Universal Dependencies Portuguese treebank](https://github.com/UniversalDependencies/UD_Portuguese) (CC BY-SA 4.0)
* WikiNER paper and data: [Learning multilingual named entity recognition from Wikipedia](https://figshare.com/articles/Learning_multilingual_named_entity_recognition_from_Wikipedia/5462500) (Nothman et al., 2013)
* spaCy docs: [Neural Network model architecture](https://spacy.io/api/#nn-model)
* spaCy docs: [Model optimization tops and advice](https://spacy.io/usage/training#tips)
* spaCy docs: [How we're training and packaging models for spaCy](https://spacy.io/usage/training#example-training-spacy)
* [`spacy convert` command](https://spacy.io/api/cli#convert) for converting `.conllu` files to spaCy's JSON format

You've probably seen the models directory and the [Portuguese model overview](https://spacy.io/models/pt) already, which includes more model details and accuracy scores – but I'm still adding it here for completeness.

**Comment by pvcastro** [comment]
Great, thank you @ines ! That's exactly what I asked for.
