### ISSUE TITLE
Spacy Semantic-Similarity

### ISSUE THREAD

**Issue by hassaanseeker** [explosion/spaCy#1888]
Currently i am trying to create an question answer system. Where answer from a person will be compared with the database.
My question is:
I am using spacy latest version with english model for semantic similarity score. And using that score as response. Is there anyway to retrain spacy model for more accurate results from semantic similarity.

* Operating System: Ubuntu
* Python Version Used: 3.5+
* spaCy Version Used: latest version

**Comment by ines** [comment]
Sorry for only getting to this now – but yes, that's possible. You can train and add your own vectors that are specific to your data. For more details, see the docs on custom vectors: https://spacy.io/usage/vectors-similarity#section-custom
