### ISSUE TITLE
Lot of false positives when using the NER model. in SPACY 2.0

### ISSUE THREAD

**Issue by aprasadcvlt** [explosion/spaCy#1892]
I have been trying to use SPACY 2.0 to detect entities. What I see is that there are many false positives reported by the model. II have coped one such file here. [log.txt](https://github.com/explosion/spaCy/files/1667831/log.txt)
[samplegithub.txt](https://github.com/explosion/spaCy/files/1667841/samplegithub.txt)

This is causing almost all the documents to be flagged causing a lot of issues. Is there a way I can reduce the false positives here? I have a feeling that we are doing some thing wrong in the way we are doing it. Can someone please guide us here?

## Your Environment

* Operating System: Windows 2012
* Python Version Used:  3.0
* spaCy Version Used: 2.0
* Environment Information:

**Comment by ines** [comment]
What do you mean by "flagged"? Which entity types are you looking to extract? Did you train your own model? And do you have examples of the false positives you're seeing?

The thing is, from the example text you've shared, it looks like you're trying to analyse résumé texts, which are very specific in terms of both syntax and terminology. spaCy's default models were trained on general web text, which means they perform well for general-purpose use cases. But the entities a model predicts strongly depend on the data it was trained on, so you'll almost **always** want to customise the model and post-train it on examples specific to your domain and use case.

The [usage guide on training models](https://spacy.io/usage/training) has a lot of additional info and code examples for improving and updating existing models. For example, a simple first step could be to extract all entity predictions on your data, select the incorrect predictions, correct them and add them to your training data. You should also make sure to include entities the model previously got correct, to avoid the "catastrophic forgetting" problem. [This section](https://spacy.io/usage/training#training-data) shows different strategies for creating training data – you might also want to check our annotation tool [Prodigy](https://prodi.gy), which we've developed for this exact purpose.

**Comment by aprasadcvlt** [comment]
understood. What i mean flagged is that incorrectly reported as entity.  Here is the sample. Words like Virtualization, web based app, test person are being detected as PERSON entities which is incorrect. My goal is to not detect them as entities. 

[https://demos.explosion.ai/displacy-ent/?text=%0AProficient%20QA%20professional%20with%20the%20strong%20technical%20skills%20with%20Storage%2C%20High%20Availability%2C%20Networking%2C%20Virtualization%2C%20UNIX%20and%20Cloud%20Domain%20knowledge.%20Have%20detailed%20expertise%20in%20Server%2FClient%20product%20testing%20with%20solid%20track%20record%20in%20delivering%20product%20within%20agile%20based%20methodologies.%20%0A%0ATotal%202%2B%20experience%20includes%20end-to-end%20Automated%20%2B%20Manual%20testing%20of%20HA-Software%20VCS%2C%20Web%20Based%20App%2C%20and%20Mobile-App%20product%20line%20ensuring%20delivery%20of%20good%20quality%20product%20release%20on%20time.%0A%09%0AAreas%20of%20Proficiency%20%0A%0AExperienced%20in%20working%20Enterprise%20Class%20Business%20critical%20product%20testing%20which%20involves%20thorough%20knowledge%20of%20OS%20Technologies%20as%20well%20as%20Testing%20skills.%0A%0A%E2%80%A2%09Currently%20Working%20on%20Infoscale%20Availability%2FVeritas%20Cluster%20Server%20(An%20Enterprise%20product%20which%20more%20than%2085%25%20Fortune%20500%20listed%20companies%20do%20use%20for%20Application%20Protection)%20in%20Veritas%20Technologies%20LLC%20as%20Assoc.%20Software%20Quality%20Analyst%20Engineer.%0A%0A%E2%80%A2%09Strong%20Automation%20Skills%20such%20as%20automating%20manual%20test%20cases%2C%20identifying%20and%20fixing%20test%20gaps%20and%20maintaining%20Python%2FPerl%2FShell%20Based%20test%20framework.%0A%0A%E2%80%A2%09Also%20has%20good%20manual%20execution%20hands-on%20experience%20in%20testing%20software%20based%20products%20against%20the%20quality%20defects.%20%0A%0A%E2%80%A2%09Well%20aware%20of%20Smoke%2FSanity%2C%20Regression%2C%20Negative%2C%20Upgrade%2C%20Longevity%2C%20Performance%2FScalability%2C%20Code%20Coverage%2C%20Memory%20Leak%20Testing%20scenarios.%0A%0A%E2%80%A2%09Familiar%20with%20QA%20processes%20such%20as%20Understanding%20Product%20Design%20Functional%20Design%20Requirements%2C%20followed%20by%20Test%20Plan%2C%20Test%20Case%20Development%2C%20Automating%20Test%20Cases%2C%20Adding%20Test%20Cases%20to%20the%20existing%20test%20gaps%20ensuring%20lesser%20defect%20escapes%20and%20reviewing%20product%20documentation.%20%0A%0A%E2%80%A2%09Solid%20hands-on%20experience%20on%20Linux%20(RHEL)%20and%20Solaris%20(11)%20OS%20Platform%20and%20Familiar%20with%20other%20Operating%20systems%20such%20as%20Windows%20and%20AIX%20etc.%0A%0A%E2%80%A2%09Good%20understanding%20of%20Virtualization%20and%20Cloud%20(On-Prem%2FOff-Prem)%20Technologies%20such%20as%20VMware%20vCenter%2FvSphere%2C%20KVM%2C%20Zones%2FLDOM%2C%20Openstack%2C%20AWS%2C%20Azure%20etc.%20%20%0A%0A%0A%0A%0ATechnical%20Skills%3A%0A%0A%0A%E2%80%A2%09Operating%20Systems%20and%20File%20Systems%20%3A%20Red%20Hat%20Enterprise%20Linux%206.x%2C%20Oracle%20Sun%20Solaris%2010%2F11%2C%20%20%20Windows%2C%20%20%20%20%20%20%20%20%20%20AIX%2C%20VMware%20Sphere%206.0%2C%20NFS%2C%20ZFS%2C%20Proc%20File%20system%0A%E2%80%A2%09Scripting%20Knowledge%3A%20Basic%20Python%2C%20Shell%20Scripting%20and%20%20PERL(novice)%2C%20Basic%20C%2C%20Java%0A%E2%80%A2%09Virtualization%20Technologies%3A%20Vmware%2C%20Ldoms%2C%20KVM%0A%E2%80%A2%09Tools%3A%201.%20Robot%20framework%20(Python%20Based)%20as%20well%20as%20SMTF%20(Perl%2Fshell%20Based)%0A2.%09Intermediate%20knowledge%20of%20automated%20testing%20tools%20such%20as%20Unified%20Functional%20Testing%20(UFT)%2C%20Application%20Lifecycle%20Management%20(ALM)%20and%20Load%20Runner%20(LR).%0A3.%09JIRA%20%2C%20Confluence%2C%20Etrack%20%2C%20TORO%2C%20CVS%2C%20Wireshark%2C%20gdb%2C%20rpm%2C%20yum%2C%20Bugzilla%2C%20Confluence%20%0A%E2%80%A2%09Databases%3A%20Basic%20knowledge%20of%20MySQL%2C%20Oracle%20and%20Basic%20Installation%20Sybase%2C%20DB2%0A%E2%80%A2%09Networking%3A%20Routers%2C%20Switches%2C%20Basic%20TCP%2FUDP%2C%20N%2Fw%20topologies%20and%20configurations%0A%E2%80%A2%09Other%20Skills%20and%20Technologies%3A%0A1.%09SharePoint%2C%20AJAX%2C%20Silver%20Light%2C%20JQUERY%0A2.%09VMware%20%E2%80%93%20VM%20creation%2C%20cloning%2C%20snapshot%2C%20Physical%20%E2%80%93%20Solaris%2FLinux%20OS%20Deployments.%20%0A3.%09Hands-on%20in%20UNIX%20and%20Strong%20Debugging%2Ftroubleshooting%20skills.%20Ex%3A%20Kdump%20crash%20analysis.%0A%0AProjects%20Undertaken%0A%0A%0ACurrent%20Assignments%3A%0AWorking%20as%20a%20QA%20on%20Veritas%20Cluster%20Server%3A%20(from%20December%2C%202015%20till%20date)%0A1.%09Writing%20test%20cases%20to%20test%20functionality%20of%20VCS%20in%20robot%20framework%20and%20Fixing%20of%20existing%20test%20cases%20(in%20Perl)%0A2.%09Responsible%20for%20execution%20and%20debugging%20of%20weekly%20smoke%20and%20sanity%20runs%0A3.%09Analyzing%20Failure%20and%20Reporting%2FNotification.%0A4.%09End%20to%20End%20testing%20of%20VCS%20on%20different%20Platforms%20along%20with%20testing%20of%20%20Enterprise%20agents%20such%20as%20Oracle%2C%20%20Sybase%2C%20DB2%20and%20their%20working%20with%20VCS%20%20%0A5.%09Virtualization%3A%20good%20knowledge%20of%20ESX6.0%2C%20VMware%2C%20KVM%2C%20Tested%20LDOM%20functioning%20on%20Solaris%20along-with%20and%20high%20availability%20of%20applications%20inside%20zones.%0A6.%09Basic%20vmcore%20debugging%20(using%20crash%20utility%20in%20Linux%20and%20mdb%20in%20Solaris)%0A%0AUnix%20Automation%20projects%0A%E2%80%A2%09Automation%20and%20testing%20of%20a%2010Gig%20Ethernet%20device%20driver%20using%20shell%20script%0A1.%09Wrote%20automation%20scripts%2C%20to%20test%20the%20latest%20(daily)%20version%20of%20the%20driver.%0A2.%09Wrote%20QA%20scripts%20to%20test%20the%20device%20driver%20for%20the%20functionality%2C%20data%20consistency%20and%20performance.%0A3.%09For%20performance%20testing%2C%20collected%20several%20stats%20like%20throughput%20in%20different%20modes%20using%20IPerf%20tool%2C%20and%20did%20the%20performance%20profiling.%0A%0A%E2%80%A2%09Reporting%20tool%20using%20%20Python%0AWrote%20a%20python%20script%20to%20find%20out%20status%20of%20passing%20and%20failing%20test%20cases%20and%20emailing%20the%20report%20and%20contributed%20in%20writing%20some%20keywords%20in%20python%20for%20robot%20framework%2C%20for%20VCS%20when%20writing%20new%20test%20cases.%0A%0A%E2%80%A2%09Earlier%20Professional%20Experience%20responsibilities%20(Sep%201%2C%202014%20to%20Nov%2030%2C%202015)%0AContributed%20in%20end-to-end%20testing%20of%20mobile%20Apps%20in%20Android%20and%20IOS%20mobile%20%20%20%20applications%20and%20Web%20Applications%20testing%20(Platform%3A%20PHP%20CI)%20as%20well%20as%20GUI%20testing%20on%20applications%20like%20following%3A%0A1.%09REM-FIT%0A2.%09Stop%20Attack%0A3.%09Courted%20Co%0A4.%09Time%20Boost%0A5.%09John%20Hopkins%0A%0AB.E%20Project%3A%20Employee%20Appraisal%20Portal%20Using%20Microsoft%20SharePoint%20Technology%0A%0A%0AAchievements%2C%20Certifications%20and%20Extra-curricular%20activities%0A%0A%0A%E2%80%A2%09Freelancing%20experience%20in%20automation%20under%20UNIX%20in%20Shell.%20%0A%E2%80%A2%09Completed%20SEED%20Certified%20Technology%20Specialist%20Course%20in%20testing%20with%2066.78%25.%20%0A%E2%80%A2%09Excellent%20knowledge%20of%20Manual%20Testing%20and%20basic%20selenium%20and%20(TOOLS%20--)%20HP%20automation%20tools.%0A%E2%80%A2%09Consistent%20good%20academic%20record%20with%20Excellent%20Verbal%20and%20Written%20communication%20skills.%20%0A%E2%80%A2%09Basic%20knowledge%20of%20programming%20languages%3A%20C%20and%20Java.%20(Certifications%20in%20advanced%20and%20core%20Java)%20%E2%80%93%20%0A%E2%80%A2%09Good%20knowledge%20of%20French%20language.%20Completed%20International%20DELF%20A1%20with%2086%25%20%0A%E2%80%A2%09Moving%20to%20new%20Test%20Framework%20%E2%80%93%20ROBOT%20and%20increasing%20automation%20to%20reduce%20test%20gaps.%0A%0A&ents=person%2Corg%2Cgpe%2Cloc%2Cproduct%2Cdate%2Ctime&model=en_core_web_sm](url)

**Comment by ines** [comment]
Yes, as you can see in the visualisation, a lot of the false positives are either very specific terms the model likely hasn't seen before, as well as capitalised multi-word phrases, which don't usually occur as frequently in regular web text – for example "Strong Automation Skills". Many of the bullet points and sentences are also pretty atypical – for example, "Total 2+ experience includes X, Y and Z". So in order to achieve good NER results, you need to customise the model and train in on your specific data. This is really the true power of NLP 😉

You might also want to consider [training additional entity types](https://spacy.io/usage/training#example-new-entity-type) that are more specific to what you're trying to extract. For example, if your résumé texts are mostly about tech jobs, you could add a `PROGRAMMING_LANGS` entity type. Or you could try training entity types like `SKILL`, `SOFTWARE` or `DEGREE`. This is all possible and not that difficult anymore using spaCy v2.0 – all you need is good ideas, labelled data and as many examples as possible.
