### ISSUE TITLE
Words written the same way, having different lemmas depending on PoS

### ISSUE THREAD

**Issue by lynochka** [explosion/spaCy#1898]
Hey! Could you please help with some advanced lemmatization? If I were to make rules depending on whether a word is a substantive or a verb, how should I proceed?

Example from Norwegian: 

adapter (subst) -> lemma =adapter
adapter (verb) -> lemma = adaptere

Thank you in advance!

## Your Environment
* **Platform:** Linux-4.4.0-43-Microsoft-x86_64-with-Ubuntu-16.04-xenial
* **spaCy version:** 2.0.5
* **Python version:** 3.5.3+

**Comment by honnibal** [comment]
You can probably use the `spacy.lemmatizer.Lemmatizer` class for this. The API docs are here: https://spacy.io/api/lemmatizer . The source code is here: https://github.com/explosion/spaCy/blob/master/spacy/lemmatizer.py

The documentation is fairly sparse, but the idea is quite simple: there are exception tables (keyed by the coarse-grained part-of-speech and the word form), and then a list of substitution rules that are applied sequentially to rewrite the word form. If the rewritten form is a known lemma, it's returned.

**Comment by lynochka** [comment]
I am still not sure how to apply it to the class. Could you please give any examples similar to my issue? Thank you!
