### ISSUE TITLE
Installation of Spacy in cmd without using internet connection

### ISSUE THREAD

**Issue by nagamayurin** [explosion/spaCy#1899]
Hi,

Please guide me to install spacy for python 3.5.2 version without using internet connection.Please help me with the name of the spacy version and the list of dependency files with versions specified to download and use those files for offline installation.

Thanks
Naga

## Your Environment

* Operating System: 
* Python Version Used: 
* spaCy Version Used: 
* Environment Information:

**Comment by ines** [comment]
You can find the requirements (including development dependencies like Cython) here:

https://github.com/explosion/spaCy/blob/cb7110c22e357d0ce11120abcf9fcf2042563237/requirements.txt#L1-L19

The latest version of spaCy is `v2.0.5`. If you have a machine that's connected to the internet, you could simply install spaCy and its dependencies into a virtual environment (e.g. using pip), zip the environment containing the installed packages and copy it over to your offline machine.

**Comment by nagamayurin** [comment]
Thank you very much for the reply!
I can be able to download the files  in my machine by going into websites directly but cannot be able to run commands like pip to access the URLs to download files/dependencies, that is the reason I cannot be able to download the dependencies by running PIP. But I can install offline.
Please provide the spacy version which can install on Python 3.5 and its dependencies to install spacy. Is all the files which mentioned in the requirements.txt need to be downloaded for installation offline?
Note: I tried downloaded Spacy v2.0.5 but iam getting error.

I installed Tensorflow offline successfully by pasting the required files in a file and executed the PIP command offline. I wanted to do it the same to install Spacy.

Thanks,
Naga
