### ISSUE TITLE
Spacy lemmatization keeps capitals when not using tagger

### ISSUE THREAD

**Issue by peterroelants** [explosion/spaCy#1901]
I'm wondering why the Spacy lemmatization behaves differently with respect to keeping capital letters when a tagger is loaded or not, and if this expected behaviour or not. For example when I run:

    print(spacy.about.__version__)
    s = u"The company Apple is looking at buying U.K. startups for $1 billion. I'm not."
    
    nlp = spacy.load('en', disable=['parser', 'ner'])
    doc = nlp(s)
    print('With tagger: ', [t.lemma_ for t in doc])  # Lemma's are lowercase
    
    nlp = spacy.load('en', disable=['tagger', 'parser', 'ner'])
    doc = nlp(s)
    print('Without tagger: ', [t.lemma_ for t in doc])  # Lemma's captial letters are kept

My output is the following:

    2.0.5
    With tagger:  ['the', 'company', 'apple', 'be', 'look', 'at', 'buy', 'u.k.', 'startup', 'for', '$', '1', 'billion', '.', '-PRON-', 'be', 'not', '.']
    Without tagger:  ['The', 'company', 'Apple', 'be', 'look', 'at', 'buy', 'U.K.', 'startups', 'for', '$', '1', 'billion', '.', '-PRON-', 'be', 'not', '.']

Notice that with the tagger active al token lemmas are converted to lowercase. This does not happen if the tagger is not used. I couldn't find anything in the documentation describing this behavior. Is this expected behavior?

## My Environment

* **spaCy version:** 2.0.5
* **Platform:** Darwin-17.4.0-x86_64-i386-64bit
* **Python version:** 3.6.4
* **Models:** en_core_web_sm, en
* Spacy installed via `conda install spacy` with conda version 4.4.7

**Comment by honnibal** [comment]
When no tagger is loaded, we fall-back to a lookup table. I think we should probably true-case the words (i.e. force to lower if start of sentence) when we do the lookup lemmatization. A pull request for this would be welcome.

The rule-based lemmatizer is actually a bit too aggressive in its re-casing. We do want proper nouns to retain their case. I have this change in the develop branch at the moment.
