### ISSUE TITLE
Parser training data format

### ISSUE THREAD

**Issue by kevinrosenberg21** [explosion/spaCy#1902]
## Info about spaCy

* **spaCy version:** 2.0.5
* **Models:** en, es
* **Platform:** Linux-4.13.0-31-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.5.2

Hi everyone,

I'm trying to train a parser model that would be executed after the ner model is, because the semantic relationships in the domain I'm working on apply only to entities.

According to https://spacy.io/api/goldparse#init I should feed the data as an array under the key 'deps' that has the word indicating which label the equivalent (index-wise) token has.

By https://spacy.io/usage/training#intent-parser the dependency parser would work better if the entities are a single token.

> To achieve even better accuracy, try merging multi-word tokens and entities specific to your domain into one token before parsing your text. You can do this by running the entity recognizer or rule-based matcher to find relevant spans, and merging them using Span.merge . You could even add your own custom pipeline component to do this automatically – just make sure to add it before='parser'.

When I create the deps array to pass for training, should I use the original tokenization (by spaces and symbols, with the configured exceptions) or the one that it should receive (which is the same but with the entities joined)? Would it be possible given the training data in the gold parse format to obtain the tokenized and entity-parsed (not the real entities that it would calculate but the annotated ones) version of the Doc object so that the GoldParse object is easier to create given my data?

Thank you, and regards

**Comment by honnibal** [comment]
> When I create the deps array to pass for training, should I use the original tokenization (by spaces and symbols, with the configured exceptions) or the one that it should receive (which is the same but with the entities joined)? 

The latter --- you'll want to make sure the tokenization matches how the `Doc` objects will be set up when you pass them in to `DependencyParser.update()`. The parser model is going to try to learn a sequence of decisions to create the parse, and it's going to learn that from the `Doc` and `GoldParse` pairs you provide. So you want those to match what you're going to be predicting over.

The `GoldParse` object does have a feature designed to help you: it tries to align the annotations you give it to the tokenization of the `Doc` object, and doesn't assume they always match up 100%. This allows training with tokenization errors. When the tokenization doesn't align correctly, the labels of the misaligned tokens are handled as unknown values.

In your case this could cause a tricky problem: if you pass `GoldParse` a `Doc` object that *does* have the merges, but the `deps` array *doesn't*, they'll be misaligned, and the model won't be able to learn much --- but everything would appear to work. So, watch out for that!

> Would it be possible given the training data in the gold parse format to obtain the tokenized and entity-parsed (not the real entities that it would calculate but the annotated ones) version of the Doc object so that the GoldParse object is easier to create given my data?

That's a very reasonable thing to want to do. I'd say there's a gap in the API here. You should be able to create the `Doc` object using the methods `doc.from_array()`, and creating the `Doc` object by passing in a list of words. However, I think there will be one or two annoying details. I don't think `doc.from_array()` will support missing values the same way `GoldParse` does, you'll have to make sure the heads are encoded the same way, etc.

If you write a utility for this that you think might be more generally useful, a pull request would be appreciated. Overall the workflow that you're following is a bit bleeding edge, so I'd be interested to hear how you go.

**Comment by kevinrosenberg21** [comment]
@honnibal thank you for your reply, I was able to get the tokenized doc from the training data. I'll clean up my code when I'm done prototyping everything so I can add it to the project. As I mentioned in my original post only entities should be tagged, so there'd be tokens in the text that don't have a label nor a head. As I understand I can just use any character for the label. But what should I use as their head? The root of the tree?
