### ISSUE TITLE
Dummy command argument wasn't removed from auto-link after download

### ISSUE THREAD

**Issue by Kimahriman** [explosion/spaCy#1904]
Auto-linking of downloaded languages was broken in https://github.com/explosion/spaCy/commit/7f0ab145e95036a55af4802184a4b1c496557d0a. The dummy argument wasn't removed from the `link` call at https://github.com/explosion/spaCy/blob/master/spacy/cli/download.py#L44. I can make a PR for the fix unless it's easier for a maintainer to just fix this quickly.

## Your Environment
* Operating System: Docker python:3.6
* Python Version Used: 3.6.2
* spaCy Version Used: Changes made since 2.0.5
* Environment Information: Docker python:3.6

**Comment by ines** [comment]
Thanks – I thought this was fixed in a second PR, but it might have been lost in an unclean merge in between, damn. If you could submit a quick PR, that would be great! 👍
