### ISSUE TITLE
Spacy installation issue

### ISSUE THREAD

**Issue by nagamayurin** [explosion/spaCy#1909]
Hi Team,

Iam unable to install Spacy in windows. iam trying to install offline after downloading the required files. But it is showing the below error. Please help !!!
![image](https://user-images.githubusercontent.com/24644803/35548017-c38e60e8-05a2-11e8-99dc-f3b18f9ba865.png)
Iam running the below command 
pip install spacy-2.0.5.tar.gz -f ./ --no-index

Thanks,
Naga
![error](https://user-images.githubusercontent.com/24644803/35548073-1291c180-05a3-11e8-895d-62dfaffc16da.png)

## Your Environment

* Operating System: 
* Python Version Used: 
* spaCy Version Used: 
* Environment Information:

**Comment by nagamayurin** [comment]
Hi Team,

Could you please guide me on the above issue. I tried multiple ways to install spacy offline. I downloaded all the files mentioned in the requirements.txt and tried to install offline but failed to do so. Please help me to install Spacy offline. Not sure why I am getting the above error.

Please guide !
Thanks.,
Naga

**Comment by ines** [comment]
@nagamayurin Hmm, it looks like there might be a problem with some of the dependencies of the dependencies. Maybe you could try the other approach I suggested in #1899: on your online machine, create a new virtual environment and install spaCy in there, including all its dependencies etc. 

For example:

```bash
python -m pip install -U venv
venv .env
.env\Scripts\activate
pip install -U spacy
```

If you're on Python 2, replace `venv` with `virtualenv`. The above commands will create a directory `.env` and install all dependencies and everything else you need in there. You can then copy this directory onto your offline machine and into the new working directory. And then activate the environment, which should give you access to spaCy:

```bash
.env\Scripts\activate
python -c "import spacy; print(spacy.__version__)"  # test that it's working
```
