### ISSUE TITLE
information of the ECCN number 

### ISSUE THREAD

**Issue by ShivaSSS** [explosion/spaCy#1912]
## ECCN – Export Control Classification Number
Could you also please provide us the ECCN number of the product?
If you do not have your software classified with an ECCN, please kindly answer the following questions so that we may self-assess:

  | NO | YES
-- | -- | --
Does   the Software perform any encryption or utilize any encryption processes? |   |  
If   the answer is YES to the above, please indicate if the encryption is coded   into the application or separately called (such as using SSL) |   |  
If   the answer is YES to the above, please indicate what function(s) the   cryptography/encryption serves |   |  
A,    Copyright protection purposes (Includes using a license key/code) |   |  
B,   User authentication purposes |   |  
C,   A core part of the functionality such as to encrypt databases       D,   To encrypt communications between the software and a host system |   |  

* Operating System: 
* Python Version Used: 
* spaCy Version Used: 2.0.5
* Environment Information: windows

**Comment by honnibal** [comment]
Hi,

We're not a US company, so ECCN isn't a process we've encountered before.

To answer your questions: 

> Does the Software perform any encryption or utilize any encryption processes?

Yes

> If the answer is YES to the above, please indicate if the encryption is coded into the application or separately called (such as using SSL)

Coded separately. Specifically, network requests using the HTTPS protocol may be made in order to download data. These requests are currently made using the dependency library `requests`.
