### ISSUE TITLE
More guidance needed re deep_learning_keras.py example

### ISSUE THREAD

**Issue by colingoldberg** [explosion/spaCy#1917]
More out of curiosity than knowledge - I am a novice here, I ran the deep_learning_keras.py example.

It ran for +/- an hour (on macosx High Sierra), producing the output below. Having done this, I was hoping to run a test or two after the training. But I see no files saved (where??), and it is not obvious how to proceed. Any help is appreciated.

# Output from training:
$ python deep_learning_keras.py 
/Users/colingoldberg/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
2018-01-31 09:26:24.138046: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
Downloading data from http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz
83886080/84125825 [============================>.] - ETA: 0sUntaring file...
Loading spaCy
WARNING:tensorflow:From /Users/colingoldberg/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:1238: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /Users/colingoldberg/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:1340: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Parsing texts...
/Users/colingoldberg/anaconda3/lib/python3.6/site-packages/keras/models.py:874: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '
Train on 310254 samples, validate on 304112 samples
Epoch 1/5
310254/310254 [==============================] - 1398s 5ms/step - loss: 0.5942 - acc: 0.6774 - val_loss: 0.5696 - val_acc: 0.6980
Epoch 2/5
310254/310254 [==============================] - 1338s 4ms/step - loss: 0.5695 - acc: 0.6995 - val_loss: 0.5634 - val_acc: 0.7055
Epoch 3/5
310254/310254 [==============================] - 1334s 4ms/step - loss: 0.5601 - acc: 0.7065 - val_loss: 0.5576 - val_acc: 0.7105
Epoch 4/5
310254/310254 [==============================] - 1240s 4ms/step - loss: 0.5538 - acc: 0.7111 - val_loss: 0.5487 - val_acc: 0.7142
Epoch 5/5
310254/310254 [==============================] - 1251s 4ms/step - loss: 0.5494 - acc: 0.7152 - val_loss: 0.5584 - val_acc: 0.7165

-----> End of training output

## Info about spaCy

* **spaCy version:** 2.0.5
* **Platform:** Darwin-17.3.0-x86_64-i386-64bit
* **Python version:** 3.6.4
* **Models:** en_vectors_web_lg
Macosx (High Sierra) 10.13.2

**Comment by colingoldberg** [comment]
After installing spaCy 2.0.5 so as to try this script - and running it, I got an error with an earlier script - at the nlp = spacy.load('en') statement.

Error: 
`
nlp = spacy.load('en')
  File "/Users/colingoldberg/anaconda3/lib/python3.6/site-packages/spacy/__init__.py", line 19, in load
    return util.load_model(name, **overrides)
  File "/Users/colingoldberg/anaconda3/lib/python3.6/site-packages/spacy/util.py", line 119, in load_model
    raise IOError("Can't find model '%s'" % name)
OSError: Can't find model 'en'
`
After doing a conda install spacy - which went back to spaCy 1.9.0,
and python -m spacy.en.download
I was able to run my older script.

**Comment by ines** [comment]
Merging this with #2758.

**Comment by free-variation** [comment]
@colingoldberg sorry this reply is coming so late.

To get the script to save models, you need to pass a `model_dir` directory to the script as a positional argument (the first one).
