### ISSUE TITLE
'before' and 'after' keywords do the same thing when adding custom pipeline components

### ISSUE THREAD

**Issue by jako218** [explosion/spaCy#1918]
I'm currently trying to build a custom spacy pipeline, but have run into an issue when trying to order the components. Given two custom components, `A` and `B` defined as classes with names `A` and `B` respectively, if I add them to the pipeline as follows

```
nlp.add_pipe(A(), after='ner')
nlp.add_pipe(B(), after='A')
```

and then print the pipe names using `print(nlp.pipe_names)`, the result I get is

```
['tagger', 'parser', 'B', 'A', 'ner']
```

However, if I change things so that `B` set its `before` keyword as `A` like below

```
nlp.add_pipe(A(), after='ner')
nlp.add_pipe(B(), after='A')
```

then I get the same output from `print(nlp.pipe_names)`, namely

```
['tagger', 'parser', 'B', 'A', 'ner']
```

again. I assume this isn't the intended behaviour?

## Your Environment
* Operating System: OSX
* Python Version Used: 3.6.3
* spaCy Version Used: 2.0.3

**Comment by ines** [comment]
Thanks for the report – I was kinda worried at first, but I noticed you're using spaCy v2.0.3. I'm pretty sure the issue you're experiencing is related to this bug: #1654 It has since been fixed, so you should be able to upgrade to the latest version (v2.0.6, which was just released yesterday).
