### ISSUE TITLE
Model training on 2.0.6 impossible

### ISSUE THREAD

**Issue by Tidaren** [explosion/spaCy#1919]
# Summary

It's not possible to train a model with the newest (2.0.6) version of spacy.
A `token_vector_width` KeyError is raised when calling `begin_training` on the language instance.

# Steps to reproduce

- Install Spacy 2.0.6
- Try the following:
```python
import spacy
model = spacy.load('en')
opt = model.begin_training()
```

# Environment

Using Spacy2.0.6 on two different environments:

- Docker with base image python:3.6-slim
- Windows 7 x64 with a python3.6 x64 virtualenv

# Notes

The problem does not happen on 2.0.5

**Comment by honnibal** [comment]
Thanks --- didn't have a test covering training...
