### ISSUE TITLE
how to better save nlp result to disk  ? 

### ISSUE THREAD

**Issue by meshiguge** [explosion/spaCy#1920]
hi, there is one large file containing more than **100M** lines texts, 
it should be run many **loops** over all lines for usage .  
So how to save the result of  nlp (text) to disk for reusing ?     
how about this naive code? is there any faster and smarter method ?  thanks all 

```python 
processed_list = []
for line in file : 
     processed_list.append( nlp(line.strip()))

with open("processed_list.pkl","wb") as handle:
     pickle.dump( processed_list   ,handle)
```

**Comment by honnibal** [comment]
Try:

```
lines = (line.strip() for line in file)
docs = nlp.pipe(lines) # Allows minibatching -- faster.
doc_bytes = [doc.to_bytes(tensor=False, user_data=False) for doc in docs]
vocab_bytes = nlp.vocab.to_bytes()

with open("processed_list.pickle","wb") as handle:
     pickle.dump( (doc_bytes, vocab_bytes)   ,handle)

# Load the data
with open("processed_list.pickle", "wb") as handle:
    doc_bytes, vocab_bytes = pickle.load(handle)
nlp.vocab.from_bytes(vocab_bytes)
docs = [Doc(nlp.vocab).from_bytes(b) for b in doc_bytes]
```

Serialisation is hard because we don't want to unexpectedly drop data, but you might only need a subset of the information on the `Doc`. If you don't need to save the user-data, it's best to use the bytes representation. You can also save some space and time by excluding the tensors from the `Doc` objects. Since all `Doc` objects should share a `Vocab` instance, you want to serialize the `vocab` object once, and load that back in separately. Then you can pass the object into `Doc.__init__()` when you deserialize.

Let me know how you go!

**Comment by meshiguge** [comment]
1 bug found : KeyError 
```python
docs = [Doc(nlp.vocab).from_bytes(b) for b in doc_bytes]
File "doc.pyx", line 815, in spacy.tokens.doc.Doc.from_bytes
KeyError: u'tensor
```
2 may I ask what is **_user_data_**? 

3 
```python 
 with open("processed_list.pickle", "**rb**") as handle:
    doc_bytes, vocab_bytes = pickle.load(handle)
```

**Comment by meshiguge** [comment]
may I ask why `list(docs) ` change the value of docs ? 
```python 
docs = nlp.pipe(lines) 
print type(docs )   # <type 'generator'>
print ( "docs after nlp.pipe : " , list ( docs) )  # print number of text lines 
print ( "docs after nlp.pipe : " , list ( docs) )  # print 0  
```

**Comment by honnibal** [comment]
`docs` is there a generator -- so if you do `list(docs)` in your first call, you're exhausting the generator and not saving the list. Then when you try to call `list()` again, the generator is empty.

**Comment by meshiguge** [comment]
and, the saved processed_list.pkl seems too big,  200 M(size) file result to 9G processed_list.pkl

**Comment by honnibal** [comment]
That does seem too big. How big is the pickle if you compress it? That should tell us something about the redundancy...

**Comment by meshiguge** [comment]
1  processed_list.pkl.gz will become  about 500M,      
2 may I ask why **KeyError: u'tensor**  happens when `tensor=False`

```python 
doc_bytes = [doc.to_bytes(tensor=False, user_data=False) for doc in docs]
docs = [Doc(nlp.vocab).from_bytes(b) for b in doc_bytes]
```
thanks
