### ISSUE TITLE
Shared vocab and excluding vocab from serialization

### ISSUE THREAD

**Issue by thomasopsomer** [explosion/spaCy#1921]
Hi,

Sorry not an issue, but more a 'how to' question, because I'm not getting how all internal things work.

When training several components, let's say a NER (a `EntityRecognizer` instance) and a text classifier (a `TextCategorizer` instance). Does the `Vocab` needs to be shared across all training task ? 
If so, what is the best way of handling the training of several component?

First I thought of training each components separately, saving them (the component instance such as `EntityRecognizer` not the language instance) and then finally combining all the component in a `language` instance but I don't understand what happens to each Vocab in this scenario... Plus it saves the vectors attached each time, so it doesn't seems to be the right way to do !

Is the correct workflow:
- Train a component
- Save the `language` instance
- Load the previously saved instance, add a new component and train it

I hope it's understandable... ^^

Thomas

**Comment by honnibal** [comment]
The `vocab` instance doesn't necessarily need to be shared during training in v2, although it does save memory.

I think the missing piece of the puzzle is that the pipeline components' `to_disk` and `to_bytes` methods let you exclude components from serialisation. Specifically you want something like:

```python
# Save the NER, without saving the vocab.
ner.to_disk(out_dir / 'ner', vocab=False)
```

Then you can save the vocab separately, in `out_dir / 'vocab'`.

**Comment by ines** [comment]
> ```python
> # Save the NER, without saving the vocab.
> ner.to_disk(out_dir / 'ner', vocab=False)
> ```

Just noticed that this is currently not documented – and the way it works is also pretty inconsistent and misleading. [`Pipe.to_disk`](https://github.com/explosion/spaCy/blob/master/spacy/pipeline.pyx#L189) currently takes spread `**exclude` arguments, which are then passed into [`util.to_disk`](https://github.com/explosion/spaCy/blob/master/spacy/util.py#L507) as the `exclude` argument (not spread). `util.to_disk` then checks `if key not in exclude`. This means that both `vocab=False` and `vocab=True` would lead to the vocab not being serialized.

I guess I'd even consider this a bug. Instead, I think a better and more consistent API would be to use a `disable` or `exclude` keyword argument that takes a list of strings, similar to how excluding components is handled in `spacy.load`.

```python
ner.to_disk(output_path, disable=['vocab'])
ner.to_disk(output_path, exclude=['vocab'])
```

**Comment by thomasopsomer** [comment]
hum alright I see ! Thanks !

I didn't notice the `exclude` parameter :/, so I thought that if the vocab was there it was because it's mandatory to keep it along.

The `exclude `parameter makes perfectly sens, and would certainly benefit from being documented and its mechanism refactored as @ines suggest :)

**Comment by ines** [comment]
Copying over my reply from #1701 – merging the two issues since they're both related to changes to the serialization API:

>> @ines Thoughts on what we should do here? If nothing else I guess we should at least document this clearly. Maybe we need that `Binder` class after all?

> I'll definitely add some notes about this to the docs – I think both the serialization section as well as the vectors section would make sense here.
> And this is a tricky question... I agree that it's weird to have the `Doc.to_bytes` behave inconsistently, but having spaCy save out the vectors and vocab for each `Doc` would be pretty unsatisfying, too. Introducing another keyword argument on `Doc.to_bytes()` would be okay in theory, since it's already inconsistent anyways – but we'll likely want to fix this more elegantly in the future and without breaking backwards compatibility of the `Doc` API.

**Comment by honnibal** [comment]
The `spacy-nightly` branch now has some relevant code for this: https://github.com/explosion/spaCy/blob/develop/spacy/tokens/_serialize.py . It's still beta functionality and the name will likely change, but it should already be useful.

**Comment by ines** [comment]
See #3385 – finally consistent 🎉
