### ISSUE TITLE
ImportError: cannot import name 'inputstream' while downloading the model.

### ISSUE THREAD

**Issue by sameerkumar16** [explosion/spaCy#1924]
Hi, I am a newbie here .I has already downloaded `en_core_web_sm` model sometimes back .I was trying to download large models to test .So I tried to download the larger one by typing this command in terminal.
                `python -m spacy download en_core_web_lg`

It threw the following error
                        `from . import inputstream`
              ` ImportError: cannot import name 'inputstream'`

So I tried to raise the issue here because I couldn't find a similar one here. In here there was this command to know the version of your environment.
 `python -m spacy info --markdown`

And guess what it also showed the same error. 

## Your Environment

* Operating System: `Ubuntu 14.04 LTS`
* Python Version Used: `Pythob 3.6`
* spaCy Version Used: `Spacy 2.0.5`
* Environment Information: Anaconda

**Comment by ines** [comment]
This is strange! spaCy doesn't make that call, but  after googling that error, I found some threads [related to `html5lib`](https://www.google.de/search?q=ImportError%3A+cannot+import+name+'inputstream'). So it looks like the problem might be related to #1126 and a common issue with the `six` library that depends on `html5lib`.  

Does installing `html5lib==1.0b8` manually help?

Just had a look and we do specify `html5lib` as a dev dependency in the `requirements.txt`, but not in `setup.py`, so it's not installed with spaCy. We should probably fix that, just to be safe!

**Comment by sameerkumar16** [comment]
Never mind .Just install the newer version of html5lib . "pip install html5lib==1.0b8" fixed it

**Comment by ines** [comment]
Thanks for updating with the solution! Will add `html5lib==1.0b8` to the `setup.py` to make sure it's installed correctly with spaCy.
