### ISSUE TITLE
TypeError: Argument 'string' has incorrect type (expected unicode, got str)

### ISSUE THREAD

**Issue by rbhambriiit** [explosion/spaCy#1927]
https://github.com/explosion/spaCy/blob/002ee80ddf1e3616e9d957abbdab76180d45aa27/examples/training/train_ner.py#L67

I am trying to run the example to train a ner system. This is a small bug where unicode is expected and 
str is provided with a 1-line fix - still I see the same behaviour at multiple occassions.

##  Is this a bug or feature request? If a bug, include all the steps that led to the issue.
Bug. Just ran the train_ner script.

## Info about spaCy

* **Python version:** 2.7.12
* **Platform:** Linux-4.9.75-25.55.amzn1.x86_64-x86_64-with-glibc2.2.5
* **spaCy version:** 2.0.7
* **Models:** en

## Fix:
 replace to : [unicode(text)],  # batch of texts

**Comment by ines** [comment]
Thanks for the report! Instead of modifying the training code, we should also be able to simply add a `u` before the texts [in the training data](https://github.com/explosion/spaCy/blob/002ee80ddf1e3616e9d957abbdab76180d45aa27/examples/training/train_ner.py#L21), e.g. `u'Who is Shaka Khan?'`.
