### ISSUE TITLE
transfer learing in spaCy

### ISSUE THREAD

**Issue by pengyu** [explosion/spaCy#1933]
I am wondering whether there is any support for transfer learning in spaCy. The parameters learned in previously trained models, for example, as in `spacy.load('en')`, may be useful for training toward other NLP tasks so that fewer training data will be needed.

To do so, some internals of these models need to be accessible outside. Is there any facility available for this goal of transfer learning?

**Comment by bjornamr** [comment]
I dont think it is possible for word2vec vectors,  I think different languages only saves the vectors for word2vec and not the weights for each layer in the neural networks. This means that it would be hard to continue training using only the results. What we learned previously is not saved and there is nothing to transfer other than the results.

To do this you could train your own word2vec classifier first on english and then continue on another language for example. You could use gensim for training word2vec vectors, which has support for loading vectors to continue training.

**Comment by honnibal** [comment]
@pengyu The results of the CNN can be accessed in `doc.tensor`. The tensor is extended for each component in the pipeline. In the default models, the first 128 dimensions are the tagger, then the parser, then the entity recogniser.

There are some other ways you might want to get at the intermediate representations. I gave an example of getting attention weights out of the text classifier on the Prodigy forum recently: https://support.prodi.gy/t/highlighting-the-matching-words-for-text-classfication/254/11

There's also an experimental API for adding multi-task objectives to the parser and NER training. See here: https://github.com/explosion/spaCy/blob/master/examples/training/ner_multitask_objective.py

While transfer learning is definitely a good approach, it's still not trivial to get good results --- so you'll likely have to do some experimentation. I would suggest running spaCy on a large batch of your text, and using the annotations as gold-standard to train spaCy. Then you can be training the pipeline alongside your other models.
