### ISSUE TITLE
doc.ents is returnning an empty list

### ISSUE THREAD

**Issue by ashwani010** [explosion/spaCy#1936]
The code snippet is : 

doc = nlp(u'Apple is looking at buying U.K. startup for $1 billion')

for ent in doc.ents:
    print(ent.text, ent.start_char, ent.end_char, ent.label_

I am running  spacy version 2.0.5 on Python3+

**Comment by ines** [comment]
Which model did you load into your `nlp` object? In order to detect entities, you need one of the [available statistical models](https://spacy.io/models), for example, the small English model `en_core_web_sm`.

```bash
python -m spacy download en
```

```python
import spacy

nlp = spacy.load('en')
doc = nlp(u'Apple is looking at buying U.K. startup for $1 billion')
```

`doc.ents` should now have 3 entities: "Apple", "U.K." and "$1 billion".
