### ISSUE TITLE
Sentence level EDA using spaCy matcher- discussion

### ISSUE THREAD

**Issue by rbhambriiit** [explosion/spaCy#1937]
I am given a bunch of sentences:
s = 'My name is Rahul. I dont know Steve. I know Rahul Dravid though'

What I want to do is to visualise all sentences which contain the word Rahul.
I am currently trying: 

```
s = 'My name is Rahul. I dont know Steve. I know Rahul Dravid though'

from spacy.matcher import Matcher
matcher = Matcher(nlp.vocab)

pattern = [{'LOWER': 'rahul'}]
matcher.add('Rahul_matcher', None, pattern)

doc = nlp(unicode(s))

for sent in doc.sents:
    doc_sentence = nlp(unicode(sent))
    matches = matcher(doc_sentence)
    if matches:
        print matches, doc_sentence, '\n'


```

Basically I convert each sentence span to a doc, since Matchers work upon doc and not on span.
Is there a better way of doing this?

My current output is:
[(17084977133614693193L, 3, 4)] My name is Rahul. 
[(17084977133614693193L, 2, 3)] I know Rahul Dravid though 

Also is there a way to get indices at char level, instead of word level.

Thanks,
Rahul

**Comment by honnibal** [comment]
I would first collect the start and end positions of the sentences, and then run the matcher over the doc once. This will allow you to divide the matches by sentence, without reparsing the `Doc` object. I did add a `span.as_doc()` function, but it is currently buggy, so I wouldn't recommend it.

For character indices, consider the `span.start_char` and `span.end_char` attributes. On the token level you can use `token.idx` and `len(token)`. Finally, you might later want to create a span by character offset. The `doc.char_span()` method lets you do that.

**Comment by rbhambriiit** [comment]
Can you be little more elaborate on case1 please. Is there an example/link that can help better.
"""
I would first collect the start and end positions of the sentences, and then run the matcher over the doc once.
"""

As for the character level, I think I got it. I see that one example on Netflix is available.
https://spacy.io/usage/linguistic-features#setting-entities
Was this recently added? 

Thanks!
