### ISSUE TITLE
Silent failures on pickling PhraseMatcher

### ISSUE THREAD

**Issue by mikeyshulman** [explosion/spaCy#1939]
(This is related to #930, but I think separate. Sorry if it belongs there instead. )

The `spacy.matching.PhraseMatcher` can be pickled and unpicked, but the object is not fully restored. The matcher needs to be rebuilt.
Potential solution- change `__reduce__` to  
 - raise `NotImplementedError`
 - warn about needing to rebuild the matcher
 -  properly serialize the needed information to not need to rebuild the matcher. 

```
import pickle
import spacy


tokens = u'hello there mister Smith is here'.split()
nlp = spacy.load('en_core_web_sm')
matcher = spacy.matcher.PhraseMatcher(nlp.vocab)
for token in tokens:
    matcher.add(token, None, nlp(token))
    
print len(matcher(nlp(u'who has seen mister Smith')))  # prints 2 

with open('matcherpickle.pkl', 'w') as fi:
    pickle.dump(matcher, fi)
```

restart python

```
import spacy
import pickle

nlp = spacy.load('en_core_web_sm')


with open('matcherpickle.pkl') as fi:
    matcher = pickle.load(fi)
    
matcher(nlp(u'who has seen mister Smith'))
import spacy


nlp = spacy.load('en_core_web_sm')


with open('matcherpickle.pkl') as fi:
    matcher = pickle.load(fi)
    
print len(matcher(nlp(u'who has seen mister Smith')))  # prints 0
```

## Info about spaCy

* **Python version:** 2.7.14
* **Platform:** Linux-4.13.0-31-generic-x86_64-with-Ubuntu-17.10-artful
* **spaCy version:** 2.0.7
* **Models:** en_core_web_sm

**Comment by thomasopsomer** [comment]
👍 I would also love to serialize the PhraseMatcher (takes too long to build :/)

**Comment by ines** [comment]
Merging this with the master issue #1971!
