### ISSUE TITLE
Bug with matcher. UPPER attribute.

### ISSUE THREAD

**Issue by hogowl** [explosion/spaCy#1949]
```python
import sys, traceback
matcher = Matcher(nlp.vocab)
pattern = [{'UPPER': 'HELLO'}, {'IS_PUNCT': True}, {'LOWER': 'world'}]
matcher.add('HELLOworld', None, pattern)
doc = nlp(u'hello, world!')
assert matcher.has_key('HELLOworld') == True
try: 
    matcher.remove('HELLOworld')
except Exception:
    traceback.print_exc(file=sys.stdout)
```
```bash
Traceback (most recent call last):
  File "<ipython-input-171-fc2c50b1236a>", line 8, in <module>
    matcher.remove('HELLOworld')
  File "matcher.pyx", line 317, in spacy.matcher.Matcher.remove
  File "matcher.pyx", line 137, in spacy.matcher.get_pattern_key
AssertionError
```
Seems we should add "UPPER" to IDS

## Your Environment

* **spaCy version:** 2.0.7
* **Platform:** Linux-4.13.0-32-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.4
* **Models:** en_vectors_web_lg, en_core_web_lg

**Comment by honnibal** [comment]
There's actually no `UPPER` within the C-level data attributes, so you have to write the pattern with `LOWER`. Apart from a few unicode edge-cases, this should be equivalent right?

**Comment by ines** [comment]
I also just noticed that `UPPER` is currently listed incorrectly in the docs – will fix this!
