### ISSUE TITLE
Can I train my model based on name of the entity and  not on starting & ending positions of entity??? 

### ISSUE THREAD

**Issue by UtkarshKhare** [explosion/spaCy#1952]
@honnibal @ines 
Hi all, 
I am trying to train my Spacy model on medicine related data. So my concern is, like what i saw on documentation i followed and entities are correctly identified as per my training data .

##Given approach is----
TRAIN_DATA = [
    ('Who is Shaka Khan?', {
        'entities': [(7, 17, 'PERSON')]
    }),
    ('I like London and Berlin.', {
        'entities': [(7, 13, 'LOC'), (18, 24, 'LOC')]
    })
]

**My requirement** 
Can we train --
TRAIN_DATA = [
    ('Who is Shaka Khan?', {
        'entities': [( Shaka Khan, 'PERSON')]
    }),
    ('I like London and Berlin.', {
        'entities': [(London, 'LOC'), (Berlin, 'LOC')]
    })
]

I am bit confused if we can train like this as it is not always possible to know start and end positions of each word.
Please help me on this.

Thanks

## Your Environment

* Python Version Used: python 3
* spaCy Version Used: Spacy  V2

**Comment by honnibal** [comment]
If you're looking to recognise terms from a list, you should have a look at the `Matcher` and `PhraseMatcher` classes. The named entity recogniser learns sequence annotations over the words in context, so it's essential that the annotations are provided on specific tokens.

If your terms are slightly ambiguous so you want to use the named entity recognizer, but you're starting with a terminology list, you can try matching the terms in text, and then marking whether each instance is a true example of a false example. Our annotation tool [Prodigy](https://prodi.gy) makes this quite easy.

**Comment by UtkarshKhare** [comment]
Thank you sir.
