### ISSUE TITLE
Cannot use custom vocab flags in Matcher

### ISSUE THREAD

**Issue by damianoporta** [explosion/spaCy#1954]
Hello,
i think i have found a bug in Matcher with custom vocab flags.

```
import spacy
from spacy.matcher import Matcher

nlp = spacy.load('it')

doc = nlp("Mi piace il numero 3") # I like the number 3

NUMBER_FROM_1_TO_10 = nlp.vocab.add_flag(lambda text: text in range(1, 10))

matcher = Matcher(nlp.vocab)
matcher.add('my_test', None, [{NUMBER_FROM_1_TO_10: True}])
matches = matcher(doc)

print(matches)
[]
```
I should match the 3, but there are no matches.

## Your Environment
    Models             en, it, en_core_web_md, en_core_web_sm
    spaCy version      2.0.6.dev0     
    Platform           Linux-4.4.0-112-generic-x86_64-with-Ubuntu-16.04-xenial
    Location           /home/damiano/lavoro/python/parser/.env/lib/python3.5/site-packages/spacy
    Python version     3.5.2

**Comment by ines** [comment]
I the problem here is that you're comparing the lexeme's text (a string) and an integer:

```python
lambda text: text in range(1, 10)
```

Because `u"3" in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]` is never `True`, the custom flag doesn't match. Does it work if you use a list of strings instead, e.g. `[str(num) for num in range(10)]`?

**Comment by damianoporta** [comment]
@ines Ohh, you are right, i just change it with 

`NUMBER_FROM_1_TO_10 = nlp.vocab.add_flag(lambda text: text in [str(num) for num in range(10)])`

and it works!

**Comment by damianoporta** [comment]
thank you @ines
