### ISSUE TITLE
Typo in the Glossary

### ISSUE THREAD

**Issue by SThomasP** [explosion/spaCy#1964]
https://github.com/explosion/spaCy/blob/b21a096528505bb3aeec8f0fc809c75f4028e4d0/spacy/glossary.py#L118

According to https://spacy.io/api/annotation#pos-tagging the tag for `preposition; circumposition left`  should be `APPR`, not `APRP`

**Comment by ines** [comment]
Thanks, well spotted! Fixing 👍
