### ISSUE TITLE
Entity types with dashes cause errors in ner.pyx

### ISSUE THREAD

**Issue by r-wheeler** [explosion/spaCy#1967]
When training NER task on entities that are in BILOU that also have a dash the line [here]( https://github.com/explosion/spaCy/blob/ab35ac4e6fc8c8e0d606e8eae95afbc182f8d90a/spacy/syntax/ner.pyx#L87) throws this error. Simple workaround was to replace the dash character in my entities in a preprocessing step. 

## Info about spaCy

* **spaCy version:** 2.0.5
* **Platform:** Linux-4.4.0-1049-aws-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.4
* **Models:** en_core_web_lg, en

**Comment by honnibal** [comment]
You mean entity labels with dash, right? Like if the label is `JOB-NAME`? Agree that we shouldn't have that restriction.

**Comment by r-wheeler** [comment]
Yeah just like that.
