### ISSUE TITLE
What can I do with this

### ISSUE THREAD

**Issue by Mring000** [explosion/spaCy#1970]
## Your Environment

* Operating System: 
* Python Version Used: 
* spaCy Version Used: 
* Environment Information:

**Comment by damianoporta** [comment]
not much :)

**Comment by ines** [comment]
Hi, I'm not sure what exactly you're interested in – but if you want to know more about spaCy, here are some good places to start:

* [spaCy 101 – Everything you need to know](https://spacy.io/usage/spacy-101)
* [spaCy Resources](https://spacy.io/usage/resources): applications, demos, books, courses and videos about spaCy
