### ISSUE TITLE
NER training is very slow

### ISSUE THREAD

**Issue by damianoporta** [explosion/spaCy#1973]
Hello,
i am training a new NER model with this code: https://github.com/explosion/spaCy/blob/master/examples/training/train_new_entity_type.py
i have noticed that the training is very very slow.
Doing a test with 2500 documents (500-800 tokens long) i only can see few iterations after 8 hours.

Ok, i am running it via CPU but my pc is good.
- Intel® Core™ i7-6700K CPU @ 4.00GHz × 8 
- GeForce GTX 1070/PCIe/SSE2
- 32 gb ram
- SSD
(i can try with GPU, is now possible to enable it?)
is really the training of a new model that slow? I have around 50k documents, it will took forever.
Can i optimize it somehow?

Thanks!

## Your Environment
    Platform           Linux-4.4.0-112-generic-x86_64-with-Ubuntu-16.04-xenial
    Models             en, it, en_core_web_md, en_core_web_sm
    spaCy version      2.0.6.dev0     
    Location           /home/damiano/lavoro/python/parser/.env/lib/python3.5/site-packages/spacy
    Python version     3.5.2

**Comment by r-wheeler** [comment]
Re: how to enable a gpu, previous thread [here](https://github.com/explosion/spaCy/issues/1530)

**Comment by honnibal** [comment]
That code doesn't use minibatching, in order to keep the example simple. For larger training tasks, try using the `spacy train` command.

**Comment by damianoporta** [comment]
@honnibal Ok, can I convert the [TRAIN_DATA](https://github.com/explosion/spaCy/blob/master/examples/training/train_new_entity_type.py#L44) in the spacy's json format somehow?

**Comment by honnibal** [comment]
The easiest way at the moment would be to put the data into BILUO format and use the `spacy convert` command.

**Comment by damianoporta** [comment]
@honnibal i am testing the same code with minibatches and it works good now (with CPU).

**Comment by honnibal** [comment]
Great!
