### ISSUE TITLE
The parser for custom semantics example does not work for multiple ATTRIBUTEs

### ISSUE THREAD

**Issue by top1select** [explosion/spaCy#1976]
Hello, 

Does the spaCy's parser for custom semantics (train_intent_parser.py) example work for multiple ATTRIBUTEs?

I modified below example to have two attributes, wifi and pool , and tried to train below two data sets, but the QUALITY(great) is only working for wifi, but not pool.

    ("find a hotel with great wifi and pool", {
        'heads': [0, 2, 0, 5, 5, 2, 2, 2],  
        'deps': ['ROOT', '-', 'PLACE', '-', 'QUALITY', 'ATTRIBUTE', '-', 'ATTRIBUTE']
    }),
    ("find a hotel with great wifi and pool", {
        'heads': [0, 2, 0, 7, 7, 2, 2, 2],  
        'deps': ['ROOT', '-', 'PLACE', '-', 'QUALITY', 'ATTRIBUTE', '-', 'ATTRIBUTE']
    })

What should be the right way to train this kind of custom semantics?

Thanks,
Will

Python version: 3.6.3
spaCy version: 2.0.5
Models: en, en_core_sm
Platform: Linux

**Comment by honnibal** [comment]
Sorry for not getting to this.

The example shows how you can adapt spaCy's syntactic parser to predict other types of tree structures. It only predicts trees though, not arbitrary DAG structures. One solution in your case would be to invert the relation, and have `great` by the head, and `wifi` and `pool` be the children. I do think you might be better off running the syntactic parser and post-processing the output, though.
