### ISSUE TITLE
Documentation for the german model

### ISSUE THREAD

**Issue by e-anima** [explosion/spaCy#1977]
Hello,

The german model documentation says it is trained with the TIGER CORPUS and WikiNER. It would be nice if the sources for the corpora woudl be included/mentioned in the docs.
I guess the Tiger corpus has beed taken from here : http://www.ims.uni-stuttgart.de/forschung/ressourcen/korpora/tiger.html

Whats the WikiNER source?

Doc page: https://spacy.io/models/de#de_core_news_sm

Thank you.

**Comment by ines** [comment]
Sure, here's the WikiNER paper and data: [Learning multilingual named entity recognition from Wikipedia](https://figshare.com/articles/Learning_multilingual_named_entity_recognition_from_Wikipedia/5462500) (Nothman et al., 2013).

The model sources listed in the docs are fetched from the [model's `meta.json`](https://github.com/explosion/spacy-models/blob/master/meta/de_core_news_sm-2.0.0.json) – but considering they're specified as a list, we could map each entry to a link when they're displayed on the site (like we do for the license types). Happy to implement that!

**Comment by e-anima** [comment]
Ok. Thank you very much.
