### ISSUE TITLE
optimizer = nlp.begin_training()

### ISSUE THREAD

**Issue by damianoporta** [explosion/spaCy#1978]
Hello,
pardon, a fast question. I read Spacy supports online training (awesome!), but, should i use `optimizer = nlp.begin_training()` at the beginning of each "training session" ? I mean...
after the first training should i load the model weights somehow or do i only need to call nlp.begin_training() again ?
Thanks!

**Comment by honnibal** [comment]
You want to avoid calling `begin_training()` if you've already loaded the model. `begin_training()` will reinitialize the weights, which isn't what you want.

You should be able to just make calls to `update()`, and it'll create the optimizer the first time, and save it in `nlp._optimizer`. Alternatively you can create an optimizer with one of the models you want to train, e.g. `nlp.parser.create_optimizer()`

**Comment by damianoporta** [comment]
it works perfectly! thank you @honnibal
