### ISSUE TITLE
Matcher not returning the correct ID of a match?

### ISSUE THREAD

**Issue by viksit** [explosion/spaCy#1989]
Issue type: possible bug

As per https://spacy.io/usage/linguistic-features#adding-patterns,

```
import spacy
from spacy.matcher import Matcher

nlp = spacy.load('en')
matcher = Matcher(nlp.vocab)
# add match ID "HelloWorld" with no callback and one pattern
pattern = [{'LOWER': 'hello'}, {'IS_PUNCT': True}, {'LOWER': 'world'}]
matcher.add('HelloWorld', None, pattern)

doc = nlp(u'Hello, world! Hello world!')
matches = matcher(doc)
```

(As per doc) > The matcher returns a list of (match_id, start, end) tuples – in this case, [('HelloWorld', 0, 2)], which maps to the span doc[0:2] of our original document.

However with the set up described below,

```
In [38]: import spacy
    ...: from spacy.matcher import Matcher
    ...:
    ...: nlp = spacy.load('en')
    ...: matcher = Matcher(nlp.vocab)
    ...: # add match ID "HelloWorld" with no callback and one pattern
    ...: pattern = [{'LOWER': 'hello'}, {'IS_PUNCT': True}, {'LOWER': 'world'}]
    ...: matcher.add('HelloWorld', None, pattern)
    ...:
    ...: doc = nlp(u'Hello, world! Hello world!')
    ...: matches = matcher(doc)
    ...:

In [39]: matches
Out[39]: [(15578876784678163569L, 0, 3)]

```
What am I missing? Is there an option to get "HelloWorld" back instead of this ID?

## Your Environment
* **Python version:** 2.7.13
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **spaCy version:** 2.0.7
* **Models:** en, en_core_web_lg, en_vectors_glove_md

**Comment by ines** [comment]
> What am I missing? Is there an option to get "HelloWorld" back instead of this ID?

Sorry, I think this is a mistake in the docs. Fixing!

By default, the `match_id` is an integer (hash value of the string), not the string itself. To get the string version, you can look up the ID in the `StringStore`, i.e.:

```python
for match_id, start, end in matches:
    string_id = nlp.vocab.strings[match_id]
    print(string_id)
```
