### ISSUE TITLE
Possibility to load a model from zip containing it and other packages

### ISSUE THREAD

**Issue by atomobianco** [explosion/spaCy#1991]
Seems more a feature request this one.
It appears that one can load a (custom trained) model in many ways but [from a zip](https://docs.python.org/3/library/zipimport.html).
Apparently `get_model_meta(path)` fails to retrieve the metadata because `not model_path.exists()` in 
[util.py](https://github.com/explosion/spaCy/blob/master/spacy/util.py)

**Comment by ines** [comment]
Sorry for only getting to this now – I actually answered a question on this [on StackOverflow](https://stackoverflow.com/questions/49274650/directly-load-spacy-model-from-packaged-tar-gz-file/49280552#49280552) the other day (maybe this was even yours). Here's the answer:

> No, that's currently not possible. The main purpose of the `.tar.gz` archives is to make them easy to install via `pip install`. However, you can always extract the model data from the archive, and then load it in from a path – [see here for more details](https://spacy.io/usage/models#download-manual).
> ```python
> nlp = spacy.load('/path/to/en_core_web_md')
> ```
> Using the [`spacy link` command](https://spacy.io/api/cli#link) you can also create "shortcut links" for your models, i.e. symlinks that let you load in models using a custom name instead of the full path or package name. This is especially useful if you're working with large models and multiple environments (and don't want to install the data in each of them).
> ```python
> python -m spacy link /path/to/model_data cool_model
> ```
> The above shortcut link would then let you load your model like this:
> ```python
> nlp = spacy.load('cool_model')
> ```
> Alternatively, if you *really* need to load models from an archive, you could always write a simple wrapper  for `spacy.load` that takes the file, extracts the contents, reads the [model meta](https://spacy.io/api/top-level#util.get_model_meta), gets the path to the data directory and then calls [`spacy.util.load_model_from_path`](https://spacy.io/api/top-level#util.load_model_from_path) on it and returns the `nlp` object.
