### ISSUE TITLE
Spacy 2.0.7 fails pip install

### ISSUE THREAD

**Issue by r-wheeler** [explosion/spaCy#1992]
In a new virtual env, I am unable to install spacy 2.0.7

```
 Failed building wheel for spacy
  Running setup.py clean for spacy
Failed to build spacy
Installing collected packages: thinc, spacy
  Running setup.py install for spacy ... error
    Complete output from command /home/ubuntu/va-ml/spacy_ner/.venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-cy5bm3d8/spacy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-pp5ihdno-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/ubuntu/va-ml/spacy_ner/.venv/include/site/python3.6/spacy:
    running install
    running build
    running build_py
    running build_ext
    building 'spacy.parts_of_speech' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/tmp/pip-build-cy5bm3d8/spacy/include -I/home/ubuntu/va-ml/spacy_ner/.venv/include -I/usr/include/python3.6m -c spacy/parts_of_speech.cpp -o build/temp.linux-x86_64-3.6/spacy/parts_of_speech.o -O2 -Wno-strict-prototypes -Wno-unused-function
    x86_64-linux-gnu-gcc: error: spacy/parts_of_speech.cpp: No such file or directory
    x86_64-linux-gnu-gcc: fatal error: no input files
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

`pip list` 
certifi (2018.1.18)
chardet (3.0.4)
cymem (1.31.2)
cytoolz (0.8.2)
dill (0.2.7.1)
ftfy (4.4.3)
html5lib (1.0.1)
idna (2.6)
msgpack-numpy (0.4.1)
msgpack-python (0.5.4)
murmurhash (0.28.0)
numpy (1.14.0)
pathlib (1.0.1)
pip (9.0.1)
pkg-resources (0.0.0)
plac (0.9.6)
preshed (1.0.0)
regex (2017.4.5)
requests (2.18.4)
setuptools (20.7.0)
six (1.11.0)
termcolor (1.1.0)
thinc (6.10.2)
toolz (0.9.0)
tqdm (4.19.5)
ujson (1.35)
urllib3 (1.22)
wcwidth (0.1.7)
webencodings (0.5.1)
wheel (0.30.0)
wrapt (1.10.11)

Directly install an older version works fine: 
`pip install spacy==2.0.5`

Installing collected packages: spacy
Successfully installed spacy-2.0.5

Pip version 

pip 9.0.1
## Your Environment
* **Platform:** Linux-4.4.0-1049-aws-x86_64-with-Ubuntu-16.04-xenial
* **Python version:** 3.6.3

**Comment by r-wheeler** [comment]
Something in this fixed the issue: 
```
sudo apt-get update
sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
    libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
    xz-utils tk-dev python3.6 python3.6-venv python3.6-dev
```

**Comment by Masum06** [comment]
@r-wheeler what would be the Windows equivalent to this?

**Comment by solababs** [comment]
@Masum06 

check this out 
https://stackoverflow.com/questions/43370851/failed-building-wheel-for-spacy?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
