### ISSUE TITLE
Not very clear how to specify heads when training for custom parsing 

### ISSUE THREAD

**Issue by iafilatov** [explosion/spaCy#1993]
Hi,

There's a great example in [training/train_intent_parser.py](https://github.com/explosion/spacy/blob/master/examples/training/train_intent_parser.py) but I still can't understand something.
```python
# training data: texts, heads and dependency labels
# for no relation, we simply chose an arbitrary dependency label, e.g. '-'
TRAIN_DATA = [
    ("find a cafe with great wifi", {
        'heads': [0, 2, 0, 5, 5, 2],  # index of token head
        'deps': ['ROOT', '-', 'PLACE', '-', 'QUALITY', 'ATTRIBUTE']
    }),
```
So I should use an arbitrary label for the relations I don't care about. But what about the heads? It looks like all heads are specified in a meaningful way, i.e. "a" is labeled "-" and the head is 2. Must "a" have a meaningful head? What about "with" and 5?

I have some training examples roughly 3 to 8 sentences long and I want to extract only a couple of "short" relations from each. Annotating just the relations I want is possible but doing this for every word would be an issue. In the example above I'd only care about "wifi" and "great" (or "bad", "awful", "absent"...). Is it possible to feed
```
"find a cafe with great wifi"
[0, 0, 0, 0, 0, 0]
['-', '-', '-', '-', 'QUALITY', 'ROOT']
```
for training? I mean, will it train for what I want? I don't want to relate every word to wifi (I don't really care what other words relate to), but I want it to find the quality that applies to wifi, not something else. For ex in `wow doge good wifi bad` I want only "bad" to relate to wifi, not "good" (let's say, I have a lot of dogespeak examples). I'm really new to this, so... 

## Info about spaCy

* **spaCy version:** 2.0.7
* **Platform:** Linux-4.13.0-31-generic-x86_64-with-Ubuntu-16.04-xenial
* **Python version:** 3.6.3

**Comment by iafilatov** [comment]
Thanks for your answer @honnibal 
Do you mean that I can just specify any heads (i.e. left-branch like `[1, 2, 3, ... N-1, N-1]`) as long as the tree spans the entire sentence, is connected and reflects my desired semantics in those few branches that I care for? Won't the parser train on the rest of the tree as well? I'm not sure I want it to because the 
heads I'd feed it would be random and not meaningful.
Would it make sense to prepend a dummy root node and make it the head for every node which I'm not going to supervise?

**Comment by iafilatov** [comment]
I tried building a left-branched tree and I've tried adding a dummy token and pointing all others at it but I'm always getting
```
# whitespace missing btw
ValueError: Could not find a gold-standard action to supervise thedependency parser. The GoldParse was projective. The transition system has 18 actions...
```
 Always on the same phrase. If I skip it, it starts failing on a different phrase.

**Comment by honnibal** [comment]
> Thanks for your answer @honnibal
> Do you mean that I can just specify any heads (i.e. left-branch like [1, 2, 3, ... N-1, N-1]) as long as the tree spans the entire sentence, is connected and reflects my desired semantics in those few branches that I care for? Won't the parser train on the rest of the tree as well? I'm not sure I want it to because the
heads I'd feed it would be random and not meaningful.

If the parts of the tree that you don't care about are specified in a trivial way (e.g. they always left-branch), then the decisions the parser will make will be very easy --- so the model won't have to devote much capacity to those parts of the sentence. This is the best you can do: the parser *must* connect all the words. You can either remove the irrelevant words, merge them into larger tokens, leave them entirely latent by setting them to `None`, or specify a trivial structure.

It might be best to read about how the parser works here: https://explosion.ai/blog/parsing-english-in-python

The error you're getting indicates that the tree you're providing is one the parser is unable to learn to produce. Perhaps you have a label that hasn't been added to the model?

**Comment by iafilatov** [comment]
Indeed, it was a missing label. Thanks for pointing in the right direction!

I've read the blog post and it was instructive. Perhaps, the part I'd been really looking for is where it discussed features used by the parser:
> we refer to the word-form, the part-of-speech tag, and the number of left and right children attached to the token

If spacy uses a similar set of features (does it?), does it mean that I need to have a tagger that works correctly with my examples before it makes sense to train the parser? Are there any other prerequisites?  The docs seem to imply that I can just take an empty language class and train only it's parser component.
