### ISSUE TITLE
Tokenization error

### ISSUE THREAD

**Issue by kevinrosenberg21** [explosion/spaCy#1994]
#### Info about spaCy

* **Models:** en, es
* **Python version:** 3.5.2
* **Platform:** Linux-4.13.0-32-generic-x86_64-with-debian-stretch-sid
* **spaCy version:** 2.0.5

Hi everyone,

I'm having issues with the Spanish tokenizer. Particularly it's overly joining characters into single tokens. When the characters that it joins belong to two different entities, it becomes an issue.

For example, the text 
>  elecciones departamentales(8 de mayo de 2005)

is tokenized into elecciones, departamentales(8, de, mayo, de and so on. My issue is that elecciones departamentales is one entity (which I later merge as a single token for dependency parser training purposes) and 8 de mayo de 2005 is another one.

I know the default behavior is to split on spaces and punctuation, so if it was tokenized as elecciones, departamentales,(, 8, de, mayo ..... it would actually work better for me.

I have two questions. The first one is if it's possible to disable any "special cases" tokenizer behavior  so that it simply splits on punctuation and spaces, and the second one is if this would impact negatively the results of the NER algorithm. 

Thank you

**Comment by kevinrosenberg21** [comment]
Hi,

I have found a second case in which the tokenizer is messing up the parser training. My main text contains the string "1995/2007" which represent two different dates, the year 1995 and the year 2007. The tokenizer merges them into a single token 1995/2007. Since the different dates have different positions in the tree, my heads and deps array gets a position behind, 'causing cycles and an incorrect final doc given to training.

Is there a way to have the tokenizer just split on spaces and punctuation?

Thank you

**Comment by ines** [comment]
The Spanish tokenizer currently uses the global punctuation rules, which are defined in [`lang/punctuation.py`](https://github.com/explosion/spaCy/blob/master/spacy/lang/punctuation.py). I think what happens in your case is that the infix rules are actually *not specific enough* – the tokenizer doesn't actually merge and only splits from left to right, taking exceptions and punctuation rules into account ([see the graphic here](https://spacy.io/usage/spacy-101#annotations-token) for some background on the algorithm).

So it looks like `/` and `(` aren't split as infixes here. You can always customise the tokenizer with your own rules, or edit the rules in the language data (either globally, or add custom rules to Spanish, similar to [Hungarian](https://github.com/explosion/spaCy/tree/master/spacy/lang/hu) handles it). 

If you do end up modifying the global rules to include more infixes, and all tests pass, we'd be happy to except a PR for this. In the long run, we want to switch to evaluating spaCy's tokenizer against the UD tokenization, which should hopefully make training easier.

**Comment by kevinrosenberg21** [comment]
@ines thank you, it looks like I was able to bypass it by 

`def compile_infix_regex():
    entries = (LIST_ELLIPSES + LIST_ICONS +
            [r'(?<=[0-9])[+\-\*^](?=[0-9-])',
            r'(?<=[{}])\.(?=[{}])'.format(ALPHA_LOWER, ALPHA_UPPER),
            r'(?<=[{a}]),(?=[{a}])'.format(a=ALPHA),
            r'(?<=[{a}])[?";:=,.]*(?:{h})(?=[{a}])'.format(a=ALPHA, h=HYPHENS),
            r'(?<=[{a}"])[:<>=/](?=[{a}])'.format(a=ALPHA),
            r'[/()]'])
    expression = '|'.join([piece for piece in entries if piece.strip()])
    return re.compile(expression)

def custom_tokenizer(nlp):
    return Tokenizer(nlp.vocab, prefix_search=nlp.tokenizer.prefix_search,
                                suffix_search=nlp.tokenizer.suffix_search,
                                infix_finditer=compile_infix_regex().finditer,
                                token_match=nlp.tokenizer.token_match)
`
And downloading the py file with the helper functions.

When I'm done prototyping I'll try a more elegant way and see if I can PR it. 

Thanks for your help.
