### ISSUE TITLE
out of memory in word_freqs

### ISSUE THREAD

**Issue by azarezade** [explosion/spaCy#1996]
When I learn word vector from a 4 GB corpus in a system with 8 GB RAM, it returns out-of-memory error while executing this:
```
python training/plain_word_freqs.py /path/to/data /path/to/lang_wiki.freqs
```
but it is ok for 2 GB corpus.
Is actually 8 GB RAM not sufficient for 4 GB corpus?!

## Environment
* Operating System: Mac OS X
* Python Version Used: 3.6
* spaCy Version Used: 2.0.7

**Comment by ines** [comment]
Yes, it's possible you're running out of memory here. You might want to check out Bounter by Gensim: https://github.com/RaRe-Technologies/bounter
