### ISSUE TITLE
Custom NER model with the official POS tagger

### ISSUE THREAD

**Issue by damianoporta** [explosion/spaCy#2003]
Hello,
i am training a custom NER model from scratch but i also need the official POS/LEMMA tagger. Can i add **my** ner to the current 'it' model ? Is that possible somehow? 

The problem is when i call spacy.blank('it') at the beginning, i lose the tagger and lemma.
How to hold them?

**Comment by r-wheeler** [comment]
You can remove and replace parts of the pipeline as per [here](https://spacy.io/usage/processing-pipelines)

```
nlp.remove_pipe('parser')
nlp.rename_pipe('ner', 'entityrecognizer')
nlp.replace_pipe('tagger', my_custom_tagger)
```
