### ISSUE TITLE
Installing spaCy via pip on Windows 10 fails with PermissionError & UnicodeDecodeError

### ISSUE THREAD

**Issue by ViktorSeifert** [explosion/spaCy#2004]
## Your Environment

* Operating System: Windows 10, 64 bit
* Python Version Used: 3.6.4 (through chocolatey)
* spaCy Version Used: 1.10.0+
* Environment Information: 

## Description
I'm trying to install spaCy on my machine unsing 'pip'.  With versions 1.10.0+ (I tried 2.0.8, 2.0.4 & 1.10.0) it fails with the errors described below.  Installation of 1.9.0 works.

The error description is PermissionError: `[WinError 5] Access denied: 'C:\\Users\\myusername\\AppData\\Local\\Temp\\pip-build-randomstring\\thinc\\include\\numpy'`
This is the last error message that is shown.  While at the top of exception messages it says:
```
Installing collected packages: thinc, spacy
  Running setup.py install for thinc: started
  Running setup.py install for thinc: finished with status 'error'
Exception:
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
  File "c:\python36\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 53: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\python36\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\python36\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\python36\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 53: invalid start byte
```

I tried running the installation in a bash-shell and a terminal in PyCharm.  The exact unicode changes but the install fails.
I don't quire understand why it throws a permission error on a temporary dir created by the install process.

When running the installation in PowerShell (tried as admin and regular user) and Windows command line I do not get the PermissionError's but the UnicodeDecodeError stays.

Although when I try the install after activating the virtual environment on the command line the PermissionError reappears: `PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'C:\\Users\\myusername\\AppData\\Local\\Temp\\pip-build-randomstring\\thinc'` = It cannot access the file because it is used by another process.

I searched for a solution but haven't found a way to install a version 1.10.0+.  The article https://reethi27.wordpress.com/2017/02/16/installing-spacy-in-windows-10-for-python-3-6/ did not change anything. (The article tells you to call `c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat` before running the install)

Some stackoverflow answers said that by giving all users permissions on the temp-dir should help.  But that seems quite bad and does not help with unicode-error.

Has anyone seen this error or something like it?

Any help is highly appreciated.

Cheers, Viktor

**Comment by ViktorSeifert** [comment]
I managed to solve my problem.  The solution is to install 'thinc' & 'spaCy' from sources.  I followed the instructions on their respective pages.
The important part seems to be calling `python setup.py build_ext --inplace` which does not fail with unicode and permission errors.

**Comment by salmanfarisvp** [comment]
I have the same issue In windows 10, it was solved my installing  **Microsoft Visual C++ Compiler for Python 2.7** . link :- https://www.microsoft.com/en-in/download/details.aspx?id=48145.

**Comment by ViktorSeifert** [comment]
Hello.  I upgraded my project to spacy 2.0.11 yesterday and the installation perfomed smoothly, even when not installing from sources.  The upgrade did not cause any problems in code.
For me the problem seems to be resolved.
Cheers, Viktor
