### ISSUE TITLE
Recommended language models incompatible with spacy.load('language_model')

### ISSUE THREAD

**Issue by CYUlysses** [explosion/spaCy#2007]
As the title stated. For example:

The default model for English when downloading using "en" is en_core_web_sm
But when running spacy.load('en'), the error is 
" [Errno 2] No such file or directory: 'C:\\ProgramData\\Anaconda3\\envs\\dflt3\\lib\\site-packages\\spacy\\data\\en\\en_core_web_sm-2.0.0\\vocab\\lexemes.bin' "

The default model for Spanish when downloading using "es" is es_core_news_sm
But when running spacy.load('es'), the rror is
"[Errno 2] No such file or directory: 'C:\\ProgramData\\Anaconda3\\envs\\dflt3\\lib\\site-packages\\spacy\\data\\es\\es_core_news_sm-2.0.0\\parser\\tok2vec_model' "

Also note that the two cases are missing different components...

I have tried re-downloading but the problem persisted. Using the "md" versions solved the problem, but it would be better if "sm" versions also worked.

Thanks.

## Your Environment

* Operating System: Windows 10 Pro
* Python Version Used: 3.5.4
* spaCy Version Used: 2.0.8
* Environment Information: conda 4.3.34

    Installed models (spaCy v2.0.8)
    C:\ProgramData\Anaconda3\envs\dflt3\lib\site-packages\spacy

    TYPE        NAME                  MODEL                 VERSION
    package     en-core-web-md        en_core_web_md        2.0.0
    package     en-core-web-sm        en_core_web_sm        2.0.0
    package     es-core-news-sm       es_core_news_sm       2.0.0
    package     es-core-news-md       es_core_news_md       2.0.0
    package     xx-ent-wiki-sm        xx_ent_wiki_sm        2.0.0
    link        es_core_news_md       es_core_news_md       2.0.0
    link        xx                    xx_ent_wiki_sm        2.0.0
    link        es                    es_core_news_md       2.0.0
    link        en                    en_core_web_sm        2.0.0
    link        en_core_web_md        en_core_web_md        2.0.0

**Comment by honnibal** [comment]
Sometimes the model directory can get into a weird state when installing on top of old versions. I'm still not 100% sure how this happens, because installing cleanly always works.

I think the problem comes down to some symbolic links, and things overwriting in a way we don't expect. If you uninstall and check that all the files are actually gone, you should have no trouble when you reinstall.
