### ISSUE TITLE
Getting error when passing words for training

### ISSUE THREAD

**Issue by UtkarshKhare** [explosion/spaCy#2009]
Hi @ines ,
Your approach of training is-
TRAIN_DATA = [
    ('Who is Shaka Khan?', {
        'entities': [(7, 17, 'PERSON')]
    })

**Problem**
what i am stuck with the small change that i made to your approach i.e.
  ('Who is Shaka Khan?', {
        'entities': [('Shaka Khan', 'PERSON')]
    })
 When doing this i am getting an error following same pattern except passing name instead off-sets.
![image](https://user-images.githubusercontent.com/25740386/36474345-421f29e8-171d-11e8-895c-e906d5fca2fb.png)

I want to know how can i train my model with entity names and not by passing starting and ending positions of entity.
Is it possible to train like this???
How i can make training with words as it is not always possible to sit and count indexes of each entity to train??
Is there any solution to my problem??

* Python Version Used: 3
* spaCy Version Used: 2

**Comment by honnibal** [comment]
Well you've changed the tuple to be of length 2, not 3 --- so now the lookup `ent[2]` fails as out of index.

If you only have one instance of the entity in your example, you can always get the start and end offsets with `string.index(name)` and `len(name)`. spaCy does require the start and end offsets, though --- it needs to know which bit of the string is the entity, unambiguously.
