### ISSUE TITLE
token pos_ not writeable

### ISSUE THREAD

**Issue by NiallRooney** [explosion/spaCy#2014]
Hello,

Getting an error message pos_ 

    word.pos_ = 'NOUN'
AttributeError: attribute 'pos_' of 'spacy.tokens.token.Token' objects is not writable

but can change word.tag_

Is it intended that tagging can't be changed

Python 2.7
Spacy 1.8.2

## Your Environment

* Operating System: 
* Python Version Used: 
* spaCy Version Used: 
* Environment Information:

**Comment by scribu** [comment]
I am interested in this question too.

My usecase: The word "plugin" can get parsed as either a `NOUN` or a `VERB`, but I know for certain that in the strings I'm processing it should always be tagged as a `NOUN`. How can I do that?

**Comment by honnibal** [comment]
We had the `.pos` attribute unwriteable because its value would be set by the `.tag` attribute. I now think this makes less sense: the mapping from the coarse-grained tag to the fine-grained tag isn't always so simple, so it's better to just let people write to the `.pos`. Will fix.
