### ISSUE TITLE
Problem in importing write_binary_vectors

### ISSUE THREAD

**Issue by tahirahmad2030** [explosion/spaCy#2017]
I try to import from spacy.vocab import write_binary_vectors
but get ImportError: cannot import name write_binary_vectors
Is write_binary_vectors still in vocab or has its name been changed !

The code is below:
import spacy.vocab

    def set_spacy_vectors(nlp, binary_loc, bz2_loc=None):
        if bz2_loc is not None:
            spacy.vocab.write_binary_vectors(bz2_loc, binary_loc)
        write_binary_vectors(bz2_input_loc, binary_loc)

        nlp.vocab.load_rep_vectors(binary_loc)
#Replace the vec.bin, so your vectors will be loaded by default

    from spacy.vocab import write_binary_vectors
    import spacy.en

    from os import path

    def main(bz2_loc):
        bin_loc = path.join(path.dirname(spacy.en.__file__), 'data', 'vocab', 'vec.bin')
        write_binary_vectors(bz2_loc, bin_loc)

if __name__ == '__main__':
    plac.call(main)

## Your Environment

* Operating System: Ubuntu 16.04
* Python Version Used: Python 2.7.12
* spaCy Version Used: spaCy version      2.0.9
* Environment Information: python shell

**Comment by tahirahmad2030** [comment]
@honnibal why is above code not working now. More specifically in spacy 2.0.9 from spacy.vocab import write_binary_vectors is giving the import error.
 ImportError: cannot import name write_binary_vectors

**Comment by honnibal** [comment]
This changed in v2. If you want to convert a text-based vectors file for use in spaCy, you should update to 2.0.10 and then run:

```python -m spacy init-model en /path/to/output -v /path/to/vectors.tar.gz```

The script should accept word2vec's text-based format (which is also the format produced by FastText), as either a .txt or a tar.gz file. It will then produce you a spaCy model directory, with the vocab and vectors in spaCy 2's format.
