### ISSUE TITLE
's isn't being flagged as a stop word when it is a contraction of "is"

### ISSUE THREAD

**Issue by tepu** [explosion/spaCy#2020]
In the sentence "That is good", 'is' is considered a stop word, but in the sentence "That's good", 's isn't considered a stop word even though it is a contraction of 'is'.

## Info about spaCy

* **spaCy version:** 2.0.9
* **Platform:** Darwin-17.2.0-x86_64-i386-64bit
* **Python version:** 3.6.2
* **Models:** en_core_web_sm, en

**Comment by tepu** [comment]
The same applies to "n't" and "not" in the sentences "I don't think so" and "I do not think so". "not" is flagged as a stop word while "n't" isn't

**Comment by ines** [comment]
Thanks! The English stop words are defined in [`lang/en/stop_words.py`](https://github.com/explosion/spaCy/blob/master/spacy/lang/en/stop_words.py) – if a lexeme's text is part of this list, it'll return `True` for `is_stop`.

If you want to submit a PR that adds the contractions to the list, that would be cool! 👍
