### ISSUE TITLE
can't download models

### ISSUE THREAD

**Issue by bhomass** [explosion/spaCy#2021]
I just installed spacy 2.1.0 on my mac, using conda. When I try to download any of the models I get incompatibility error message. 

python -m spacy download en_core_web_sm

    Compatibility error
    No compatible models found for v2.1.0 of spaCy.

## Your Environment
* **spaCy version:** 2.1.0.dev0
* **Platform:** Darwin-16.1.0-x86_64-i386-64bit
* **Python version:** 3.6.2

* Operating System: macOS Sierra 10.12
* Python Version Used: 3.6.2
* spaCy Version Used:  2.1.0
* Environment Information: conda virtual env

**Comment by honnibal** [comment]
Hm, conda shouldn't be giving you the dev build --- it's not ready yet, so we don't have models uploaded. The correct version is currently 2.0.9

**Comment by bhomass** [comment]
when I check with conda list, it shows spacy 2.0.8, but python -m spacy info --markdown shows * **spaCy version:** 2.1.0.dev0. why is that?

**Comment by ines** [comment]
This is very strange – did you also build spaCy from `master` recently? Maybe the `spacy` you're loading in your current environment isn't actually the spaCy you've installed via conda, but a different one?

Which version do you see if you open the Python interpreter and type the following?

```bash
>>> import spacy
>>> spacy.__version__
```

**Comment by eamonnkenny** [comment]
The git clone checkout is not download a 2.0.x version. Its downloading the 2.1.0 version and because the models are not available, this is why this error arises.

**Comment by honnibal** [comment]
@eamonnkenny There's a git tag for all release versions, so you can always build the v2.0.9 tag.

We need people to be writing patches against the current state, and sometimes those changes are going to require the models to be retrained. For instance, we held off merging fixes to the lexical attributes that affect model compatibility until now, but at some point those patches need to be on master so we can move forward.

The alternative is to freeze master to the last release, and perform all development on a branch until we're ready to release. This introduces a non-useful layer of bureaucracy --- if you want a version that's frozen to the last release, there's a tag for that. Patches go to master, and at some point the patches will be incompatible with the existing models.

**Comment by eamonnkenny** [comment]
@honnibal Thats fine to state in an issue tracker but surely the install guide at the top of the first page of the website should state this also for the moment. I installed spacy a month ago without any issues following the install guide, but found that I couldn't install it today at all from github based on the documentation. I've no problem going for tagged versions but not everyone is au fait with the versioning.

**Comment by honnibal** [comment]
@eamonnkenny Hmm. I do take your point --- apologies; your first comment made me a bit defensive.

I'm reluctant to add more caveats to the install docs, though --- usually when people are building from source, they do want to build master.

**Comment by honnibal** [comment]
@bhomass For simplicity can you just do like `conda install spacy==2.0.9`? That's the syntax for pip, not sure how to specify an exact version in conda.

There might be some caching involved, or something like that.

**Comment by bhomass** [comment]
no, sir, that won't help. I already tried reinstalling a few times, and it does install 2.0.8 for me. But when running, it still picks up the version I built from source. I can't find where that version sits on my laptop.

**Comment by bhomass** [comment]
I repeat git clone with the tag v2.0.9 and rebuilt. Now I got through. Thanks.

**Comment by tranand** [comment]
@bhomass I tried the git clone with v2.0.9 tag but inside python I still  get '2.1.0.dev4'. How did you get it to work?

**Comment by eamonnkenny** [comment]
One way to get it to work on older Linux systems and Ubuntu is to download
get-pip.py found online to upgrade your pip/pip3 to version 9.0.1 if that
version is not available already on your system. Then just install spacy
using pip or pip3. Works perfectly on Debian stretch.

**Comment by mobtexapp** [comment]
Same problem here

**Comment by eamonnkenny** [comment]
Did you try what I stated above:

wget https://bootstrap.pypa.io/get-pip.py 
python3 ./get-pip.py
pip3 --version
pip3 install spacy

Works perfect under Linux for me. Not sure what you should do under Windows.

**Comment by ines** [comment]
Since `v2.1.0` is taking longer than expected (due to getting the BLAS linking right on Windows), we moved the state back to `develop`, and `master` should now be synced with `v2.0.x` again. Sorry about the confusion.
