### ISSUE TITLE
pipeline threads number setting 

### ISSUE THREAD

**Issue by meshiguge** [explosion/spaCy#2022]
## Your Environment

* Operating System: osx 
* Python Version Used: 2.7
* spaCy Version Used: 2.0
* Environment Information: en

I reference the code  [Advice for parallel processing? #1839 
](https://github.com/explosion/spaCy/issues/1839)

```python
nlp = spacy.load('en', disable=['tokenizer', 'ner', 'textcat'])
lines = (line.rstrip('\n').decode('utf-8') for line in sys.stdin)
docs = nlp.pipe(lines)
# If you need the original input, you can do this:
data_tuples = ((line.rsplit('\n').decode('utf-8'), line) for line in sys.stdin)
for doc, raw_line in nlp.pipe(data_tuples, as_tuples=True, batch_size=20 , n_threads =2)
```
But  how to set the number of **batch_size** and **n_threads** ( 20 cpus can be used here)
why the speed of pipeline is just 100 it/s ?

**Comment by honnibal** [comment]
Please see here: https://github.com/explosion/spaCy/issues/2075

I would advise you to use multi-processing, e.g. with joblib, and configure numpy to use single threads. I'm really looking forward to getting this resolved --- it's been a huge pain to get the matrix multiplication solution compiled for Windows, but I finally have it done.
