### ISSUE TITLE
Avoid automatic prediction

### ISSUE THREAD

**Issue by damianoporta** [explosion/spaCy#2027]
Hello,
i am writing custom recognizer to find entities and feed the NER model with those custom samples.
I have noticed that spacy change my entities. Example below:

```
import spacy
from spacy.matcher import PhraseMatcher
from spacy.tokens import Span

nlp = spacy.blank('it')

custom_label = nlp.vocab.strings['CUSTOM']

ner = nlp.create_pipe('ner')
ner.add_label("CUSTOM")
nlp.add_pipe(ner)

nlp.begin_training()

doc = nlp("Ciao mi chiamo Mario Rossi, abito a Roma e sono nato nel 2000 a Milano")

patterns = [nlp(pattern) for pattern in ['Roma', 'Milano']]
matcher = PhraseMatcher(nlp.vocab)
matcher.add('city', None, *patterns)

matches = matcher(doc)

for _, start, end in matches:
    span = Span(doc, start, end, label=custom_label)
    doc.ents = list(doc.ents) + [span]

print('Entities', [(ent.text, ent.label_) for ent in doc.ents])

# Entities [('Ciao', 'CUSTOM'), ('mi chiamo', 'CUSTOM'), ('Rossi', 'CUSTOM'), (', abito a', 'CUSTOM'), ('Roma e', 'CUSTOM'), ('sono', 'CUSTOM'), ('nato nel 2000', 'CUSTOM'), ('Roma', 'CUSTOM')]

```
The PhraseMatcher has added **Roma** and **Milano**, what about the other tokens in the **ents** ? 

As i wrote i am creating a custom script that should train a blank **IT** model with custom labels. The problem is when i prepare the data from training. If i use all the ents i will feed wrong entities that will give me poor accuracy/recall.

Thanks.

## Your Environment

    Platform           Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial
    Python version     3.5.2          
    spaCy version      2.0.6.dev0     
    Models             en, it, en_core_web_md, en_core_web_sm
    Location           /home/damiano/lavoro/python/parser/.env/lib/python3.5/site-packages/spacy

**Comment by damianoporta** [comment]
suggestions?

**Comment by honnibal** [comment]
Sorry for the lack of reply on this. I didn't quite understand the problem, and then it slipped through the cracks.

It looks to me like the problem here is simply that you're running the NER model right after you initialize it with random weights...And then it just happens that the model predicts a lot of the class, because the weights are arbitrary. The problem should go away once you train the model.
