### ISSUE TITLE
Empty tag and pos attributes

### ISSUE THREAD

**Issue by belkhayaty** [explosion/spaCy#2028]
Hello,

I have an issue regarding spaCy.

Once I initiate my token (spacy.tokens.token.Token), the two attributes (.tag_ and .pos_) are empty.

I did install all required english libraries but still, the attributes remain empty.

`from spacy.lang.en import English
nlp = English()
nlp('The')[0].tag_`
Out = ''

Thank you for your help

## Your Environment

* Operating System: 
* Python Version Used: 
* spaCy Version Used: 
* Environment Information:

**Comment by Xeoncross** [comment]
I've run accross this issue as well. The spaCy v1 library seemed it always had a `spacy.tokens.token.Token.tag_` value. In spaCy 2 I have to add checks for empty `.tag_` values.
