### ISSUE TITLE
Named Entity Recognizer missing predict function

### ISSUE THREAD

**Issue by wpm** [explosion/spaCy#2029]
The [documentation](https://spacy.io/api/entityrecognizer#predict) says that named entity recognizer objects have a `predict` function which returns scores from the model. However, this doesn't appear to be the case.

```
>>> nlp = spacy.load("en")
>>> from spacy.pipeline import EntityRecognizer
>>> ner = EntityRecognizer(nlp.vocab)
>>> ner.predict([nlp("I live in Florida.")])
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-49-4c86d46d1a7a> in <module>()
----> 1 ner.predict([nlp("I live in Florida.")])

AttributeError: 'spacy.pipeline.EntityRecognizer' object has no attribute 'predict'
```
If this interface has changed, the documentation should be updated.

Also, I can't figure out how to get a probability of an hypothesized named entity without `predict`. How do I get NER probabilities?

## Info about spaCy

* **spaCy version:** 2.0.7
* **Platform:** Darwin-17.4.0-x86_64-i386-64bit
* **Python version:** 3.6.3
* **Models:** en

**Comment by thetravelingsalesman** [comment]
Try this:
model = EntityRecognizer(spacy.load(spacy_model))
for eg in model.make_best(DB.get_dataset(dataset)):
      print(json.dumps(eg))

**Comment by wpm** [comment]
Let's be really clear here since both spaCy and Prodigy have different `EntityRecognizer` objects.

```python
>>> import spacy
>>> from prodigy.models.ner import EntityRecognizer
>>> nlp = spacy.load("en")
>>> ner = EntityRecognizer(nlp)
>>> list(ner.make_best([{"text":"I love Florida"}]))
[{'_input_hash': 2067731791,
  '_task_hash': -1375766369,
  'spans': [{'end': 14,
    'label': 'GPE',
    'rank': 0,
    'score': 0.9993259674355696,
    'start': 7,
    'text': 'Florida'}],
  'text': 'I love Florida'}]

```
That definitely returns an entity with a score. Thanks.

@ines, is `make_best` a documented Prodigy feature? I can't find it in the Prodigy README.

What is the official best way to get scores with your proposed entities? I see this (undocumented?) `make_best` feature, then I also see @honnibal's discussion on the Prodigy support board about calculating the probabilities by [digging through the alternatives in a beam search](https://support.prodi.gy/t/accessing-probabilities-in-ner/94).

I suspect there isn't a single "right" way to do this, that the answer is "it depends" and is all bound up with the fact that the spaCy parser decoder can either be greedy or do a beam search. But I'm still unclear on the details. Maybe this would be a good topic for an Explosion.ai blog post.

**Comment by ines** [comment]
@wpm Sorry for only getting to this now – the "official" user-facing way of getting the highest scoring parses in Prodigy is the `ner.print-best` recipe: https://prodi.gy/docs/recipes#ner-print-best (but of course, you can also reuse the recipe code and call into the model directly if you prefer different usage)

> I suspect there isn't a single "right" way to do this, that the answer is "it depends" and is all bound up with the fact that the spaCy parser decoder can either be greedy or do a beam search. But I'm still unclear on the details. Maybe this would be a good topic for an Explosion.ai blog post.

Thanks for the suggestion! There are a still a few inconsistencies and things that we would like to iron out before we make recommendations. Some of the API details might also change again in the future. Being able to test the functionality in Prodigy has been incredibly helpful, though – and the results show that it's working pretty well.

Merging this issue with #2149 btw!

**Comment by arlinajsk** [comment]
to the original comment from @wpm the documentation clearly says there is a predict method from the spacy EntityRecognizer object but it isn't there: https://spacy.io/api/entityrecognizer#predict 
This really caused a lot of confusion.  If it only works with the EntityRecognizer in the prodigy lib then  please update the documentation.
