### ISSUE TITLE
What is the underlying ML for NER?

### ISSUE THREAD

**Issue by ctrado18** [explosion/spaCy#2030]
I cannot find anything on the spacy doc about the machine leasrning algorithms used for the ner. Only for the parser and its neural network arcitecture.

Did I oversee something in the doc?

Does the spacy ner uses the the parser as an input feature?

I only know CRF to do NER.

**Comment by honnibal** [comment]
The best description is in this video: https://www.youtube.com/watch?v=sqDHBH9IjRU

There's a lot to cover, and a video was the quickest way -- apologies if it's an inconvenient format for you.
