### ISSUE TITLE
can't download large models (en_core_web_lg, en_vectors_web_lg)

### ISSUE THREAD

**Issue by ttaranov** [explosion/spaCy#2033]
not quite directly caused by Spacy, but commands such as 
python -m spacy download en_vectors_web_lg
python -m spacy download en_core_web_lg

fail with 

pip._vendor.requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='github-production-release-asset-2e65be.s3.amazonaws.com', port=443): Read timed out.

I also tried downloading models directly from github releases, without using spacy download command. These ultimately seem to download models from github's AWS s3 bucket, but that fails too... it doesn't appear to be my internet connection - I'm on good network close to AWS datacenters in Northern VA. 

Any other way to download large spacy models? (Other than from github/AWS S3 buckets)

## Your Environment
* Operating System: Mac OS
* Python Version Used: 3.6
* spaCy Version Used: latest
* Environment Information: local laptop on good internet connection

**Comment by ttaranov** [comment]
thanks! no  rush with this for me - I was able to download models by lunching server in AWS and then scp'inf file locally (I guess github's/AWS s3 bucket is just a bucket without CDN in front, which is going to be unstable for such large downloads).

took me a little bit to figure how to link downloaded models - drop en_vectors_web_lg and folders into site-packages and then run - hope it helps someone:
python -m spacy link ~/py36/lib/python3.6/site-packages/en_vectors_web_lg en_vectors_web_lg
python -m spacy link ~/py36/lib/python3.6/site-packages/en_core_web_lg  en_core_web_lg

**Comment by ines** [comment]
Thanks for updating – glad you got it working! 👍 (And yeah, I guess this makes sense re: GitHub. I assume they also don't exactly prioritise release asset downloads for non-enterprise accounts.)

Btw, you can also just `pip install` the downloaded `.zip` files, if that's easier. Alternatively, you can also link models from a different directory somewhere else on your machine. I usually don't bother doing this for the small models – but if if you have several (virtual) spaCy environments using the large models, you could keep them in `/users/you/models` and then create a link in each environment.
