### ISSUE TITLE
Spacy-Bag of Words or Word Embeddings for text classification

### ISSUE THREAD

**Issue by loginofdeath** [explosion/spaCy#2034]
I have recently done text classification in spaCy. I know it uses CNN but I was just wondering does it use word embeddings or bag of words model? Thank you in advance.

**Comment by arijit32** [comment]
Is there a code sample on the spaCy website or somewhere else for me to look at an example? I wish to create document embeddings using spaCy i.e. convert an entire document into its vector representation

**Comment by cmward** [comment]
From https://spacy.io/api/textcategorizer:

"by default, the TextCategorizer class **uses a convolutional neural network to assign position-sensitive vectors to each word in the document**.

So it uses embeddings that are then projected into context-sensitive embeddings. The embeddings are the concatention of the word, prefix, suffix, and shape. The text cat model is defined here: https://github.com/explosion/spaCy/blob/95c1de90fd9b051e537324f1bae5e3cffff05dff/spacy/_ml.py#L469

@arijit32 You can use `doc.vector` to get a single vector representation for a doc. I believe the vector will be an average of the vectors for each word in the doc.
