### ISSUE TITLE
Customizing NER with a list/gazetter

### ISSUE THREAD

**Issue by ctrado18** [explosion/spaCy#2035]
Hi,

i like spacy and I am new to it. I need to customize the NER for my chatbot-project. I am struggling with training entities if I have many entities of the same class.  So I give many training sentences with one entity, lets say for product A. Then I would copy all these sentence to replace product A with every other product XY Name?

Example: What is the price of [product XY]? How much does [product XY] costs?...

What is the best practice to handle such things.

So I would like to have before the ner component is processed, that there is a look up in a list/gazetter for known entitiy classes. If the the entity is found it is tageed with the label and this token is omitted next in the NER component.

**Comment by honnibal** [comment]
If you've got a list of words or phrases and you just want to add a tag to them, the `Matcher` and `PhraseMatcher` components would be the best solution.

It's also possible to use the `Matcher` and `PhraseMatcher` rules to boot-strap an entity recognition model, to learn phrases which aren't in your set. I have an example of this here: https://www.youtube.com/watch?v=l4scwf8KeIA
