### ISSUE TITLE
en_core_web_md runs much slower than en_core_web_lg

### ISSUE THREAD

**Issue by yanfjz** [explosion/spaCy#2038]
Hi, I've met two problems with running space using **en_core_web_md-2.0.0** and **en_core_web_lg-2.0.0** model respectively.
The test.py code is the sample code in the spacy website as:
```
import spacy
nlp = spacy.load('en')
doc = nlp(u"This is a sentence.")
```

## Case 1: install spacy using `pip install spacy==2.0.5`
* link to model **en_core_web_md-2.0.0**.
Running the test.py shows that `spacy.load()` and `nlp()` both take about **52 sec** to run respectively.

* link to model **en_core_web_lg-2.0.0**.
Running the test.py shows that `spacy.load()` and `nlp()` both take about **16 sec** to run respectively.

## Case 2: install spacy from the source code (also v2.0.5) as instructed [here](https://github.com/explosion/spaCy/tree/v2.0.5)
* link to model **en_core_web_md-2.0.0**.
Running the test.py shows that `spacy.load()` and `nlp()` both take about **16 sec** to run respectively.

* link to model **en_core_web_lg-2.0.0**.
Running the test.py shows that `spacy.load()` and `nlp()` both take about **10 sec** to run respectively.

So I'm wondering what causes the performance difference between pip installation and install from source code? Also, considering the model size that the medium one is 115MB and the large one is 812MB shown [here](https://spacy.io/models/en#en_core_web_sm), why does medium-sized model loads and processes far slower than the large-sized one?

Thank you very much in advance for any kind hints here.

## Info about spaCy
* **spaCy version:** 2.0.5
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **Python version:** 3.6.4
* **Models:** en

**Comment by bbrinx** [comment]
Is this also an issue for spacy-nightly? If so, is it possible to install spacy nighly from the GitHub repo as well?

**Comment by ines** [comment]
@bbrinx Yes, you should be able to build `spacy-nightly` from source via the `develop` branch!
