### ISSUE TITLE
Subject-verb-object extraction using SpaCy

### ISSUE THREAD

**Issue by adsrc** [explosion/spaCy#2039]
Hi,

I was looking for a way to use SpaCy to do the Subject-verb-object extraction from a sentence. I came across this code: 

https://github.com/NSchrading/intro-spacy-nlp/blob/master/subject_object_extraction.py

However, I cannot understand the purpose of using recursion in fetching all objects etc. and there is no documentation. Can someone please point me to a good resource for understanding this implementation?

## Your Environment

* Operating System: 
* Python Version Used: 
* spaCy Version Used: 
* Environment Information:

**Comment by honnibal** [comment]
You don't necessarily need to use recursion, but you do need to take care that you're getting all of the triples from the tree. I think that code is fairly old, so I doubt you'll find documentation for it. It'll be best to write your own implementation, suited for your purpose.
