### ISSUE TITLE
Remove matcher rule support for PhraseMatcher

### ISSUE THREAD

**Issue by bsbarkur** [explosion/spaCy#2042]
The `PhraseMatcher` module doesn't contain an option to remove a matching rule which is present for `Matcher` that allows word level matching. 

## Info about spaCy

* **Python version:** 2.7.10
* **Platform:** Darwin-16.4.0-x86_64-i386-64bit
* **spaCy version:** 2.0.8
* **Models:** en, en_vectors_web_lg

**Comment by ines** [comment]
Thanks and yes, that's a good point. I've added this to the matcher master issue in #1971 (and closing this one to keep things in one place).
