### ISSUE TITLE
Question about JSON format for training.

### ISSUE THREAD

**Issue by melalonso** [explosion/spaCy#2045]
Hello @honnibal and @ines!

I'm currently trying to use the `train` command to make training faster and I only need the NER feature. I was wondering if all the `tags` are needed as I'd not need some of them (as can be seen in https://github.com/explosion/spacy/blob/master/examples/training/training-data.json). 

My real question is can I omit some of them? Something like:
```json
                {
                  "head": 44,  // Omit
                  "dep": "prep",  // Omit
                  "tag": "IN",  // Omit
                  "orth": "In",
                  "ner": "O",
                  "id": 0
                },
```

Regards!

## Info about spaCy

* **spaCy version:** 2.0.7
* **Platform:** Windows-10-10.0.16299-SP0
* **Python version:** 3.6.3

**Comment by melalonso** [comment]
@honnibal ?

**Comment by ines** [comment]
Yes, that's possible, you should be able to just leave it out – see [here in `gold.pyx`](https://github.com/explosion/spaCy/blob/master/spacy/gold.pyx#L317) for the relevant source.
