### ISSUE TITLE
Sentence tokenizer algorithm details

### ISSUE THREAD

**Issue by dvaosta** [explosion/spaCy#2046]
Hi,
I'm using spaCy for my thesis. In the introduction I have to compare the spaCy algorithms with those offered by other tools, such as NLTK.
I don't understand well how the sentence tokenizer work, in particular how it uses the syntactic information to improve the result. Can you explain me and maybe tell me where the code of that tokenizer is?

Thanks

**Comment by honnibal** [comment]
The sentence boundary detection is performed jointly with the parser, using the transition `Break`. This is implemented in `spacy/syntax/arc_eager.pyx`

Basically we get the whole document in the parser, and as we're deciding to push words onto the stack, pop them, make arcs etc, we can also decide to insert a sentence boundary. Here are two papers to cite:

http://www.aclweb.org/anthology/P16-1181

http://www.aclweb.org/anthology/P13-1074
