### ISSUE TITLE
Not able to update spacy

### ISSUE THREAD

**Issue by akshay-1993** [explosion/spaCy#2047]
used 
pip install -U spacy
but failed to run the setup file.

Running setup.py install for spacy ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\akshayc\\appdata\\local\\temp\\pip-build-z_ksqn\\spacy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\akshayc\appdata\local\temp\pip-dvccc3-record\install-record.txt --single-version-externally-managed --compile:

## Your Environment

* Operating System: Windows 10
* Python Version Used: 2.7
* spaCy Version Used: 2.07

**Comment by akshay-1993** [comment]
c:\users\akshayc\appdata\local\temp\pip-build-z_ksqn\spacy\include\msvc9/stdint.h:34:2: error: #error "Use this header only with Microsoft Visual C++ compilers!"

c:\users\akshayc\appdata\local\temp\pip-build-z_ksqn\spacy\include\msvc9/stdint.h:34:2: error: #error "Use this header only with Microsoft Visual C++ compilers!"
    error: command 'c:\\mingw\\bin\\gcc.exe' failed with exit status 1

Facing these errors.

**Comment by ines** [comment]
This looks like a problem with the compiler. Do any of the solutions in #741 work for you?

Alternatively, you can also install spaCy from conda, which already includes the binary wheels (so you won't have to compile it on your machine).

```bash
conda install -c conda-forge spacy
```

**Comment by akshay-1993** [comment]
successfully install on anaconda.
But when i install it htrough cmd it gives the error below,

Installing collected packages: numpy, murmurhash, wrapt, tqdm, toolz, cytoolz, six, pyreadline, dill, msgpack-python, msgpack-numpy, thinc, html5lib, idna, requests, regex, ftfy, spacy
  Found existing installation: numpy 1.10.4
    Uninstalling numpy-1.10.4:
      Successfully uninstalled numpy-1.10.4
  Found existing installation: murmurhash 0.26.4
    Can't uninstall 'murmurhash'. No files were found to uninstall.
  Found existing installation: wrapt 1.10.6
    DEPRECATION: Uninstalling a distutils installed project (wrapt) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Can't uninstall 'wrapt'. No files were found to uninstall.
  Found existing installation: tqdm 4.15.0
    Uninstalling tqdm-4.15.0:
      Successfully uninstalled tqdm-4.15.0
  Found existing installation: toolz 0.8.0
    Uninstalling toolz-0.8.0:
      Successfully uninstalled toolz-0.8.0
  Found existing installation: cytoolz 0.8.0
    DEPRECATION: Uninstalling a distutils installed project (cytoolz) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling cytoolz-0.8.0:
      Successfully uninstalled cytoolz-0.8.0
  Found existing installation: six 1.7.3
    Uninstalling six-1.7.3:
      Successfully uninstalled six-1.7.3
  Found existing installation: dill 0.2.5
    DEPRECATION: Uninstalling a distutils installed project (dill) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Can't uninstall 'dill'. No files were found to uninstall.
  Found existing installation: thinc 6.5.2
    Can't uninstall 'thinc'. No files were found to uninstall.
  Found existing installation: html5lib 0.999999999
    Uninstalling html5lib-0.999999999:
      Successfully uninstalled html5lib-0.999999999
  Found existing installation: idna 2.5
    Uninstalling idna-2.5:
      Successfully uninstalled idna-2.5
  Found existing installation: requests 2.6.0
    Uninstalling requests-2.6.0:
      Successfully uninstalled requests-2.6.0
  Found existing installation: regex 2017.7.28
    Uninstalling regex-2017.7.28:
      Successfully uninstalled regex-2017.7.28
  Found existing installation: ftfy 4.4.2
    Uninstalling ftfy-4.4.2:
      Successfully uninstalled ftfy-4.4.2
  Found existing installation: spacy 1.9.0
    Can't uninstall 'spacy'. No files were found to uninstall.
Successfully installed cytoolz-0.8.2 dill-0.2.7.1 ftfy-4.4.3 html5lib-1.0b8 idna-2.6 msgpack-numpy-0.4.1 msgpack-python-0.5.4 murmurhash-0.28.0 numpy-1.14.1 pyreadline-2.1 regex-2017.4.5 requests-2.18.4 six-1.11.0 spacy-2.0.9 thinc-6.10.2 toolz-0.9.0 tqdm-4.19.6 wrapt-1.10.11

**Comment by ines** [comment]
Glad it worked via conda! And the log you posted looks like a successful install?  The only thing that's a bit strange is this:

```
Found existing installation: spacy 1.9.0
Can't uninstall 'spacy'. No files were found to uninstall.
```

It's possible that you've ended up in a weird system state with empty directories. But it still says `spacy-2.0.9` was installed, so it seems to have worked. Another thing that often helps is restarting with a fresh (virtual) environment and installing everything from scratch. This way, you can make sure there's no weird, leftover state.
