### ISSUE TITLE
Error while training a new language NER properly 

### ISSUE THREAD

**Issue by rohithkodali** [explosion/spaCy#2048]
I'm currenlty working on multiple indian languages, i see a issue during traiing that there is a lot of difference in the training stats that i receive
ex:   {u'ner': 117.39830673843777}
        {u'ner': 9.619517890899863e-09}
        {u'ner': 5.403591185881967e-09}

the training value changed from 134 to 9.678e-09.   Is this normal while training?

## Your Environment

* **Python version:** 2.7.12
* **Platform:** Linux-4.4.0-112-generic-x86_64-with-Ubuntu-16.04-xenial
* **spaCy version:** 2.0.5
* **Models:** en, te, ta, ka

**Comment by ines** [comment]
Yes – the value the training example prints here is the loss, which can fluctuate as the model is learning.
