### ISSUE TITLE
Archaic lemma in italian lemmatizer conflicts with current speaked language

### ISSUE THREAD

**Issue by pietrogiuffrida** [explosion/spaCy#2050]
Hi all,
actually the italian lemmatizer contains the complete conjugation of the verb "sonare", that is an archaic form for "suonare" (play music).
The problem is that the first singular person of this archaic verb is "sono", that in current italian is the first singular person of essere (to be)!!!
As you can see, the verb be is most important, than I suggest the following changes:

file: spacy/lang/it/lemmatizer.py
remove the line row 286072:     **"sono": "sonare",**
before the line 333684, just before "è": "essere", add:    **"sono": "essere",**

**Comment by honnibal** [comment]
Thanks! Will fix. I hate when this happens...There were a couple of cases like this in the English data as well.
