### ISSUE TITLE
Saving NER models to AWS S3

### ISSUE THREAD

**Issue by tahirahmad2030** [explosion/spaCy#2055]
Can we save all the models of cutom NER to S3(AWS) and get the final best model in spacy.
Is there a spacy linkage with S3 where we can upload all models and get a final best performing model?

## Your Environment

* Operating System: 
* Python Version Used: 
* spaCy Version Used: 
* Environment Information:

**Comment by sahasrara62** [comment]
@tahirahmad2030  yes you can save the model to aws and access it via rest api . for finding the best performing model you need to test the model by yourself and if it is satisfy your result then you can chose it to run in aws.

**Comment by ines** [comment]
> Is there a spacy linkage with S3 where we can upload all models and get a final best performing model?

The `spacy train` output outputs the model for each epoch and selects the best one. You'd have to set up the S3 integration yourself – or maybe you can find a fuse binding for S3 that would let you mount an S3 bucket as a local directory.
