### ISSUE TITLE
Using the spacy scorer to evaluate a custom trained model for one entity type

### ISSUE THREAD

**Issue by Aditya-9712** [explosion/spaCy#2057]
I was able train spacy using the **train_ner.py** script with custom gathered data. I want to evaluate the accuracy of the generated model for only the PERSON and ORG entity types. 

Using the **scorer.py**, I was able to get the precision and recall numbers as a whole, but I would like these numbers for the entity types I want. How should I go about this?

## Info about spaCy

* **spaCy version:** 2.0.9
* **Platform:** Linux-3.10.0-693.17.1.el7.x86_64-x86_64-with-centos-7.4.1708-Cor                        e
* **Python version:** 3.6.4
* **Models:** en_core_web_sm, en

**Comment by cklat** [comment]
I'm also very interested in the solution for this problem.

@Aditya-9712 Could you give me a hint how to use the scorer.py file to get at least a general scoring of my data? I labeled them like in the code examples with character offsets and the corresponding entity type.

**Comment by honnibal** [comment]
@cklat Yes it's exact match, except that the scorer is currently lenient about tokenization errors. I think this is probably a bad thing, and should be changed.

You need to pass in the annotated `Doc` and a `GoldParse` object. If you have the character offsets it'd be like this:

```python

gold = GoldParse(doc, entities=entity_offsets)
scorer.score(doc, gold)
```
