### ISSUE TITLE
Loading other vector model after training

### ISSUE THREAD

**Issue by damianoporta** [explosion/spaCy#2058]
Hello, i have trained a custom NER and the TAGGER models. 
I would like to do a test using different word vectors models (ex. word2vec, glove and fastext)
does it impact the accuracy of the NER/TAGGER? 
Should i re-train the model from scratch if i change the word embedding algorithm?

Thanks.

**Comment by honnibal** [comment]
@damianoporta If you use a model with pre-trained word vectors (the `md` or `lg` family models), and you supply different vectors at run-time, yes you'll need to retrain. If you use an `sm` model, the vectors won't be used during prediction, so you won't need to retrain, but you also won't get any particular benefit from the vectors.
