### ISSUE TITLE
EPM NLP CODE

### ISSUE THREAD

**Issue by 522034404** [explosion/spaCy#2059]
Hi Team, 

Currently we were able to recognize only two entities as showed in the attached screen shot (ner.JPG).
Now, we need to scale up our solution to recognize all entities in our module.

Please refer the attached sheet, which contains the complete list of utterances used in our module.

Below are the sample utterances extracted from that sheet. We are using these for training the model:
•	Run DefCalc with 7 percent inflation for 2017
•	Run Capex data for Income Statement Planning
•	Get me Net Income for 2013 for Conventional Licensee restaurants
•	Get me Supplies Costs for FY15 for Total Ownership restaurants

We need to prepare similar kind of utterances from the sheet(attached) for training the model.

Please let me know if you need any other information.

[AlexaRequest_PBCSResponse_v2_Dec25.xlsx](https://github.com/explosion/spaCy/files/1781082/AlexaRequest_PBCSResponse_v2_Dec25.xlsx)
![ner](https://user-images.githubusercontent.com/36515581/36979308-0b60c358-2055-11e8-8eb9-9b5f19a3cb49.JPG)

Thank You.
Venkat.
+1-330-6455-091

**Comment by honnibal** [comment]
Hi Venkat,

I'm afraid we can't offer custom support to achieve accuracy on a given task. This tracker is limited to installation problems, bugs, and specific clarifications of usage and documentation.

If you're developing a chatbot with spaCy, you might want to check out Rasa NLU: Rasa.com  . The folks at Rasa do offer support for the type of thing you're doing.

Of course, if I've misunderstood and there's actually a bug here, please clarify! We definitely appreciate all reports.

Best,
Matt
