### ISSUE TITLE
in which file attention mechanism is encorporated for NER ?

### ISSUE THREAD

**Issue by prashant334** [explosion/spaCy#2060]
Python version: 2.7.6
    Platform: Linux-3.16.0-77-generic-x86_64-with-Ubuntu-14.04-trusty
    spaCy version: 2.0.0a17
    Models: en, en_core_web_sm, xx_ent_wiki_sm

@honnibal @ines

in which file attention mechanism is encorporated for NER ? WHAT ARE THE DIFFERENCES BETWEEN ATTENTION MECHANISM FOR NEURAL MACHINE TRANSLATION AND NER ?

**Comment by honnibal** [comment]
The named entity recognition model doesn't really have attention in the same sense as MT models. You can find an overview of the NER algorithm in this video: https://www.youtube.com/watch?v=sqDHBH9IjRU&t=2s

The relevant source files are:

* `spacy/_ml.py`
* `spacy/syntax/ner.pyx`
* `spacy/syntax/nn_parser.pyx`
