### ISSUE TITLE
Missing correspondences in french lemmatizer table

### ISSUE THREAD

**Issue by JonathanBonnaud** [explosion/spaCy#2067]
Hello,
I am using the version 2.0 with the French model "fr_core_news_sm", so all my following questions are about French. What's more, I have been trying to use spaCy for lemmatization purposes **only**.

And I noticed that there is no correspondence missing - **"voitures": "voiture"** which in this case is a noun.  in the lookup dictionary there is only **"voitures": "voiturer"** which is a verb. How do you handle this kind of case, when two same inflected forms give two different lemmas?

An other question : As the example for English in the documentation shows, would it be possible to instantiate a French Lemmatizer with parameters?
```
from spacy.lang.fr import LEMMA_INDEX, LEMMA_EXC, LEMMA_RULES
lemmatizer = Lemmatizer(LEMMA_INDEX, LEMMA_EXC, LEMMA_RULES)
lemmatizer("voitures", "NOUN")
> voiture
```
In the current version (for French) I feel like there is no link between lemmatization and tagging, which is a pity because it is obviously closely related.

Anyways, thank you for your good work. This a a great lib!

## Info about spaCy

* **Python version:** 3.5.2
* **spaCy version:** 2.0.9
* **Models:** en, en_core_web_md, fr_core_news_sm, fr_core_news_md
* **Platform:** Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial

**Comment by ines** [comment]
Sorry for only getting to this now – there's a similar thread in #2079, where I've posted more details on how to implement a better French lemmatizer. (I'll close this issue and merge it with #2079 to keep things in one place!)
