### ISSUE TITLE
Tokenization pb with not spaced sentences and quotes.

### ISSUE THREAD

**Issue by thomasopsomer** [explosion/spaCy#2070]
Hi,

I just fell on a little tokenization pb. It may be a edge case but it's quite annoying.
The use case is the following: A sentence that starts with a quote and that follows a first one, but without space between the two:
```
s = 'First sentence."A quoted sentence" he said ...'
```
which is tokenized as:
```
[First, sentence."A, quoted, sentence, ", he, said, ...]
```

I'm wondering which rules should be modified `infixes`, `prefixes` or `suffixes`. I naively tried to add `QUOTES` to the `infixes` but it brakes other stuff.

## Your Environment

* Operating System: 
* Python Version Used: 2.0.9
* spaCy Version Used: 
* Environment Information:

**Comment by ines** [comment]
Thanks for the report! And yes, in this case, you might need to fix the infix `.` and ensure that it's also split if it's followed by a `"`. I just hacked around the infix rules and changing the following line made the tokenizer split the example correctly:

```diff
- r'(?<=[{}])\.(?=[{}])'.format(ALPHA_LOWER, ALPHA_UPPER),
+ r'(?<=[{}])\.(?=[{}"])'.format(ALPHA_LOWER, ALPHA_UPPER),
```

However, I haven't run the tests yet so it might break some other stuff. If it doesn't and/or you can make it work, we'd be happy to accept a PR for this.

(We're also just in the process of improving the tokenizer and simplifying the rules – see #1642 and #2128. This should hopefully make fixes like this easier in the future.)

**Comment by ines** [comment]
Merging this with the master issue in #1642!
