### ISSUE TITLE
Incorrect POS tagging and dependency 

### ISSUE THREAD

**Issue by IrfanKhanTanoli** [explosion/spaCy#2071]
Hi everyone,
To process the text: "We also collect contact information user provide if user sync this information from a device"
The output is:
![p1](https://user-images.githubusercontent.com/10742585/37105642-02686738-2230-11e8-9d37-8b5650cc6815.png)
'Sync' should tag as 'VERB' instead it is tag as 'Noun'
How to solve this?
Is there a way to train dependency parser so that it should tag 'sync' as verb everytime it appear in another sentence?

Even with spacy display, result is same:
[Display Spacy visualizer:](https://demos.explosion.ai/displacy/?text=We%20also%20collect%20contact%20information%20user%20provide%20if%20user%20sync%20this%20information%20from%20a%20device&model=en_core_web_sm&cpu=1&cph=1)

Thanks
## Your Environment

* Operating System: 
* Python Version Used: 
* spaCy Version Used: 
* Environment Information:

**Comment by chrisjbryant** [comment]
I think the main problem is that there are a couple of grammar errors in your text and this confuses the model. 
Try changing your text to:
"We also collect the contact information the user provides if they sync this information from a device"

**Comment by DuyguA** [comment]
+1 to @chrisjbryant . The reason "sync" is tagged as a noun is most probably that it doesn't look like a verb. It comes after a singular word, "user" but admits no 3rd person present tense suffix.
