### ISSUE TITLE
Token.set_extension() is not setting the extension

### ISSUE THREAD

**Issue by justinkreft** [explosion/spaCy#2073]
Something is wrong with the set_extensions for Span / Token. I'm not having success in setting any extensions for Tokens. 

For example the sample from the docs [here](https://spacy.io/api/token#set_extension) doesn't actually assert True
```
#added init requirements
import spacy
nlp = spacy.load('en')

from spacy.tokens import Token
fruit_getter = lambda token: token.text in ('apple', 'pear', 'banana')
Token.set_extension('is_fruit', getter=fruit_getter)
doc = nlp(u'I have an apple')
assert doc[3]._.is_fruit
#> Assertion Error
```
But replace `Token.set_extension('is_fruit', getter=fruit_getter)` with `Span.set_extension('is_fruit', getter=fruit_getter)` and it evaluates True. Something is not working correctly here.

Something funky is going on with the set_extensions. Note the last two stars

```
import spacy
from spacy.tokens import Doc, Span, Token
#Init some extensions
Doc.set_extension('some', default=False)
Span.set_extension('other', default=False)
Token.set_extension('tag', default=False)
Token.has_extension('other')

#tests
Doc.has_extension('some')
#> True
Doc.has_extension('other')
#> False
Doc.has_extension('tag')
#> False
Span.has_extension('some')
#> False
Span.has_extension('other')
#> True
Span.has_extension('tag')
#> False
Token.has_extension('some')
#> False
Token.has_extension('other')
#> True******
Token.has_extension('tag')
#> False******
```
I have tried this in plain python3 terminal on both ubuntu, and windows as well as a Jupyter Notebook.

Is Span supposed to override set_extensions for Token class?

**Comment by justinkreft** [comment]
OK. I dug in a little deeper, and found that the Token class has the following definition
```
    @classmethod
    def get_extension(cls, name):
        return Underscore.span_extensions.get(name)

    @classmethod
    def has_extension(cls, name):
        return name in Underscore.span_extensions

```

I'm assuming that should be

**Comment by honnibal** [comment]
Thanks! You're definitely right
