### ISSUE TITLE
How to save the Doc to avoid do the same work at future?

### ISSUE THREAD

**Issue by juanremi** [explosion/spaCy#2074]
A have a large collection of papers, and i need save the result of each
`doc = nlp(txt)`
to avoit do the same word in the future and only do the similarity between docs, or for example:
- now i have 5 texts
- i have the similarity bewteen each text (total: 10 similarities)
- i add a new text and i need to know the similarity bewteen the saved documents and the new document, and try to do:
```
docToSave = nlp(textToProcess)
```
NOTE: When i run the before statement, i get the same input text and i think i could have the text after removed stemming, stopwords, lematization, tokenization, etc.
and after can do:
```
SELECT data1 FROM docs;
     doc1 = data1.doc
     SELECT data2 FROM docs WHERE id>data1.id:
          doc2 = data2.doc
          sim = doc1.similarity(doc2)
          saveSimilarity(sim)

```

**Comment by ines** [comment]
You can use the `Doc.to_bytes` or `Doc.to_disk` methods – see here for details:
https://spacy.io/api/doc#to_disk

```python
nlp = spacy.load('en')

doc = nlp("Some text to process")
doc.to_disk('/path/to/doc')
```

You can then load it back in later:

```python
from spacy.tokens import Doc

nlp = spacy.load('en')
doc = Doc(nlp.vocab).from_disk('/path/to/doc')
```
