### ISSUE TITLE
Model installer doesn't check for permissions until /after/ downloading the relevant model.

### ISSUE THREAD

**Issue by fake-name** [explosion/spaCy#2082]
This is a minor issue.

Basically, if you run `python3 -m spacy download en_core_web_lg` (or similar), the requisite install permissions are not checked until *after* the selected model has downloaded. The install then aboirts with a permission issue, and apparently any temporary downloads are deleted.

This means you can potentially wait a long time for a model to download, only to discover that you actually needed to run the command with `sudo`.

Furthermore, the downloaded model appears to not be cached, as rerunning `python3 -m spacy download en_core_web_lg` with `sudo` does not seem to be aware that the model was already downloaded.

It seems that it'd be ideal to have `python3 -m spacy download` either check for the permissions it needs to install the file it will download *before* beginning it's download, or have it store the temp downloads somewhere, and check there before doing a web retrieval.

**Comment by ines** [comment]
Thanks a lot – I definitely agree. We're aware of this problem and still thinking about the best cross-platform solution for this. I'll merge this issue with #1456, which is a collection of related issues and enhancement proposals around `spacy download`. We're also always open for suggestions if you have an idea for a good solution to this.

**Comment by fake-name** [comment]
Yeah, cross platform is really annoying.

This particular issue should be solvable in a platform-agnostic manner by just opening the output file *before* starting the download, I think?

**Comment by ines** [comment]
Thanks, that's a good point! The only problem here is that `spacy download` actually delegates to `pip install` in a subprocess, which will then download the file (and store it somewhere in the pip cache) and then install it. I haven't looked into this in a while, but so far, I couldn't find a way to make pip test the permissions first. There might be a way to work around this with a temporary directory and [`pip download`](https://pip.pypa.io/en/stable/reference/pip_download/) – but this seems like an overcomplicated roundtrip...

**Comment by fake-name** [comment]
Ah, well, that's a good reason.
