### ISSUE TITLE
loading a saved model loses information (occurs with to_bytes and to_disk)

### ISSUE THREAD

**Issue by justinkreft** [explosion/spaCy#2083]
When creating a custom model, and after saving it, if loaded according to the docs, model loses information: specifically, any pipelines enabled (including default ones) and any custom flags set.

```
#Make and save model
print("Initial model settings:")
nlp = spacy.load('en')
print("Flags of base model:", len(nlp.vocab.lex_attr_getters))
nlp_model.vocab.add_flag(lambda text: False, 50)
print("Flags after adding one:", len(nlp.vocab.lex_attr_getters))
def some_pipe(doc):
    return doc
nlp.add_pipe(some_pipe, "some_pipe") 
print("Pipelines of model after adding one:", nlp.pipelines)
nlp.to_disk("/path/to/models")

#now load and check flags and pipelines using method in documentation
print("Loaded model settings:")
from spacy.language import Language
nlp2 = Language().from_disk('/path/to/models')
#check flags and pipelines from loaded model
print("Loaded model flags:", len(nlp2.vocab.lex_attr_getters))
print("Loaded model pipelines:", nlp2.pipeline)
```

Print output:
```
Initial model settings:
Flags of base model: 26
Flags after adding one: 27
Pipelines of model after adding one: [('tagger', <spacy.pipeline.Tagger object at 0x7f88598037b8>), ('parser', <spacy.pipeline.DependencyParser object at 0x7f88597a50f8>), ('ner', <spacy.pipeline.EntityRecognizer object at 0x7f88597a5150>), ('some_pipe', <function __main__.some_pipe>)]

Loaded model settings:
Loaded model flags: 25
Loaded model pipelines: []
```
Note that `Language()` has 1 less flag than `spacy.load('en')`. And it appears that the `len(Language().from_disk("/path/to/models").vocab)` has about 500 less vocab than `len(spacy.load('en').vocab)` even when saved using the above method. New vocab added between the two steps seems to persist, but differences between Language() and 'en' model do not. But not I've not traveled down that rabbit hole yet.

Regardless, I found this surprising, as I assumed saving a model would persist any changes I made to it, and give me hesitation to start making alterations to the base models and training them since I'm wondering what precisely persists when "saved".

Note: again, this occurs on either to/from bytes or disk.

**Comment by justinkreft** [comment]
Also, `from_disk` on Vocab seems to (almost) double the size of the vocab?

```
nlp = spacy.load('en')
print(len(nlp.vocab)) #57852
nlp.vocab.to_disk('/path/to/vocab')
nlp.vocab.from_disk('/path/to/vocab')
print(len(nlp.vocab)) #115240
```

It feels like something pretty weird is going on here. I'll dig in during the days ahead

**Comment by justinkreft** [comment]
More issues with loading using the `Language().from_disk()` or  `Language().from_bytes()` methods
As demonstrated above, the pipelines are not loaded by default. So, creating them and adding them seemed like the right thing to do. However,

```
nlp = spacy.load('en')
nlp.to_disk('/spacy_model')

from spacy.language import Language
nlp2 = Language().from_disk('/spacy_model')
pipe = nlp2.create_pipe("parser")
nlp2.add_pipe(pipe)
pipe = nlp2.create_pipe("tagger")
nlp2.add_pipe(pipe)
pipe = nlp2.create_pipe("ner")
nlp2.add_pipe(pipe)
nlp2("Some text to process.")
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-46-ff2a4df03b6e> in <module>()
     10 pipe = nlp2.create_pipe("ner")
     11 nlp2.add_pipe(pipe)
---> 12 nlp2("Some text to process.")

c:\XXXX\lib\site-packages\spacy\language.py in __call__(self, text, disable)
    339             if name in disable:
    340                 continue
--> 341             doc = proc(doc)
    342         return doc
    343 

nn_parser.pyx in spacy.syntax.nn_parser.Parser.__call__()

nn_parser.pyx in spacy.syntax.nn_parser.Parser.parse_batch()

nn_parser.pyx in spacy.syntax.nn_parser.Parser.get_batch_model()

TypeError: 'bool' object is not iterable
```

It seems that Language() is not working the same way spacy.load() works

**Comment by justinkreft** [comment]
Sure, no problem.
```
python3 -m spacy info

    Info about spaCy

    Python version     3.4.3
    Models             en
    Location           /usr/local/lib/python3.4/dist-packages/spacy
    Platform           Linux-3.13.0-107-generic-x86_64-with-Ubuntu-14.04-trusty
    spaCy version      2.0.8
```

```
 python3 -m spacy validate

    Installed models (spaCy v2.0.8)
    /usr/local/lib/python3.4/dist-packages/spacy

    TYPE        NAME                  MODEL                 VERSION             
    package     en-core-web-sm        en_core_web_sm        2.0.0
    link        en                    en_core_web_sm        2.0.0
```

**Comment by justinkreft** [comment]
I can confirm that meta.json is there and the pipelines are listed. But they don't follow through on the round trip. Additionally, the vocab issue really has me scratching my head

**Comment by justinkreft** [comment]
@honnibal 

So, I've continued with this, and tested on Windows, Mac, and Ubuntu and I'm running into the same problems.

Below is code that could just be cut and pasted into terminal to reproduce what I'm seeing.

```

**Comment by ines** [comment]
I think the problem here is actually quite simple – sorry if this has been frustrating and confusing. `from_disk` only has the job of *loading in the binary data* and making it available to the language class – not constructing the pipeline or doing anything else.

If you want to load the full model, initialise the respective language class, construct the pipeline from the meta and load in the data, you can use the `spacy.load` method instead, which can take a package name or a path:

```python
nlp = spacy.load('/path/to/model')
```

So if you want to load a full model from a directory, this is the most convenient way. Under the hood, `spacy.load` does the following ([see here](https://spacy.io/usage/processing-pipelines#pipelines) for a more detailed explanation):

```python
lang = 'en'  # from meta.json
pipeline = ['tagger', 'parser', 'ner']  # from meta.json
data_path = 'path/to/en_core_web_sm/en_core_web_sm-2.0.0'

cls = spacy.util.get_lang_class(lang)   # 1. get Language instance, e.g. English()
nlp = cls()                             # 2. initialise it
for name in pipeline:
    component = nlp.create_pipe(name)   # 3. create the pipeline components
    nlp.add_pipe(component)             # 4. add the component to the pipeline
nlp.from_disk(model_data_path)          # 5. load in the binary data
```

If you're using custom pipeline components, keep in mind that those also need to be available to spaCy if you want to be able to load them from the `meta.json`. You can do this by adding an entry to `Language.factories` dict that allows spaCy to create the pipe – either in your code, or by packaging the model as a Python package using the `spacy package` command and shipping the custom code in your model's `__init__.py`. My comment in #1984 has some more details and a link to a full code example.

**Comment by justinkreft** [comment]
@ines Ok this makes a great deal more sense. Sorry it wasn't clear to me.
A quick follow up just to clarify my understanding (mostly stemming from the vocab differences I was seeing above).

When calling `nlp("Some random_word_not_in_vocab was or was not added to vocab")`
Will `random_word_in_vocab` be added to vocab? I think I was seeing some majorly weird stuff when using `from_disk` instead of `spacy.load()` and I want to sense check myself. 

Put another way, if I have processed a ton of documents, is the `nlp.vocab` being continually updated with new words it encounters, and therefor, should I be saving the model/model's vocab? 

Thanks in advance. and we can close this

**Comment by ines** [comment]
Thanks for updating – glad this answered your questions!

> Will `random_word_not_in_vocab` be added to vocab? I think I was seeing some majorly weird stuff

What was the weird stuff you were seeing? In general, words do get added to the vocab, but it shouldn't be that important. It's mostly just caching. In spaCy v1.x, always storing the vocab was more important, because the integer IDs weren't consistent across models (so the same ID could map to completely different words in different vocabs). In spaCy v2.x, this isn't such a problem anymore, since the `StringStore` now uses hash values that are consistent across models. [See here](https://spacy.io/usage/spacy-101#vocab) for more background and examples.

So even if you've never processed the lexeme "random_word_not_in_vocab" before, you'll be able to look it up in the `StringStore` and get an ID for it, that will be the same across all models and languages: `nlp.vocab.strings['random_word_not_in_vocab']`.

**Comment by justinkreft** [comment]
` In general, words do get added to the vocab, but it shouldn't be that important. It's mostly just caching.` + diff between 1.x and 2.x.

OK this history is great. Thanks for catching me up. The hashing component of 2.x was something that really caught my eye, but I guess I'm just so used to having to save vocab of a corpus. :)

The weird stuff I saw stemmed from the issues I was having with `to_disk` and `from_disk` .

In a nutshell:

```

**Comment by justinkreft** [comment]
@ines` In general, words do get added to the vocab, but it shouldn't be that important. It's mostly just caching.` + diff between 1.x and 2.x.

OK this history is great. Thanks for catching me up. The hashing component of 2.x was something that really caught my eye, but I guess I'm just so used to having to save vocab of a corpus. :)

The weird stuff I saw stemmed from the issues I was having with `to_disk` and `from_disk` .

In a nutshell:

```

**Comment by justinkreft** [comment]
@ines
` In general, words do get added to the vocab, but it shouldn't be that important. It's mostly just caching.` + diff between 1.x and 2.x.

OK this history is great. Thanks for catching me up. The hashing component of 2.x was something that really caught my eye, but I guess I'm just so used to having to save vocab of a corpus. :)

The weird stuff I saw stemmed from the issues I was having with `to_disk` and `from_disk` .

In a nutshell:

```
spacy.load('en').to_disk(cwd + '/spacy_model')
(len(spacy.load('en').vocab), len(spacy.load(cwd + '/spacy_model').vocab), len(spacy.load('en').from_disk(cwd + '/spacy_model').vocab))
```
gave
>>> (57852, 57864, 115240)

I understand that the last method was super messy and I shouldn't have attempted it (although interesting that the vocab doubled? and method 0 and method 1 differ by a few words?).

Sorry I enjoy pulling on threads :) again, happy to be working with this

**Comment by ines** [comment]
@justinkreft Thanks for sharing your example. This shouldn't be happening – it's reasonable to expect the vocab length to be identical when you save a model and load it back in. And it definitely shouldn't be doubled.

If you can reproduce this behaviour in a clean setting, would you mind opening a separate issue about this? Your code might not be "how it's done", but it illustrates the potential problem pretty well 👍

**Comment by justinkreft** [comment]
Absolutely, will do!
