### ISSUE TITLE
NER with word embedding

### ISSUE THREAD

**Issue by pengyu** [explosion/spaCy#2084]
The following NER example in spaCy does not use word embedding. Is there an example that uses word embedding?

https://github.com/explosion/spaCy/blob/master/examples/training/train_ner.py

**Comment by azarezade** [comment]
I have also the same question.
Can spaCy use pre-trained word vector in NER, for better performance?

**Comment by tahirahmad2030** [comment]
In which format do you have the word embeddings, Text or binary?

**Comment by tahirahmad2030** [comment]
Presuming you have pre trained word embeddings in text file, you can do something like this before training your model.
vector_file = open('your_embeding.txt','r').readlines()
 for line in vector_file:
    line_list = line.split(' ')
    word = line_list.pop(0)
    line_list[-1] = line_list[-1].strip()
    vector = numpy.asarray(line_list)
    nlp.vocab.set_vector(word, vector)
