### ISSUE TITLE
en_core_web_sm-2.0.0: vector shape inconsistency when using .pipe()

### ISSUE THREAD

**Issue by BeardyBear** [explosion/spaCy#2086]
Hello,

I've found some interesting behavior with `en_core_web_sm` model. When generating docs via `.pipe()` method, the doc vector shape is 128, but when parsing the doc directly - the vector shape is 384.
I might be misunderstanding something, but this is quite confusing.

Please advise :)

![vector_shape_inconsistency](https://user-images.githubusercontent.com/5111889/37254283-8dc974e0-2544-11e8-9582-05b2fdbf8895.png)

**Comment by honnibal** [comment]
Thanks. The `.tensor` attribute is pretty messy at the moment.
