### ISSUE TITLE
Import error 'relcl' and 'compound' still after update

### ISSUE THREAD

**Issue by IrfanKhanTanoli** [explosion/spaCy#2090]
Hi 
>>> from spacy.symbols import relcl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'relcl'

>>> import spacy
>>> from spacy.symbols import compound
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'compound'

This issue still not solved even spacy is updated.

## Your Environment

* Operating System: 10 
* Python Version Used: 3.5
* spaCy Version Used:  2.0.9
* Environment Information:

**Comment by IrfanKhanTanoli** [comment]
Any update?

**Comment by ChangeMyName** [comment]
the symbols module still missing relcl. however the following works:
`            if (token.dep == 7972625988311165362):
                entities.append(token.head.text)`

**Comment by IrfanKhanTanoli** [comment]
This works for relcl. 

But still compound error appears

**Comment by ChangeMyName** [comment]
print the dependency of the token i.e. token.dep you'll get its hash value. store it in a variable somewhere.

**Comment by IrfanKhanTanoli** [comment]
Thanks it worked :)

**Comment by IrfanKhanTanoli** [comment]
I have another question:
Suppose this is a sentence: "we collect information you provide".
![dep](https://user-images.githubusercontent.com/10742585/37688976-ea774108-2ca2-11e8-9e2f-83ba5079cc68.png)

Is there  a way i can extract this:
"we collect content and other information"
"you provide content and other information"

Thanks
