### ISSUE TITLE
displacy RTL support

### ISSUE THREAD

**Issue by azarezade** [explosion/spaCy#2091]
Unfortunately, it seems that displacy doesn't support LTR. It scrambles the text when I tried to visualize a doc in Persian using `style=ner` or `style=dep`.

## My Environment
* Operating System: Mac OS X  
* Python Version Used: 3.6
* spaCy Version Used: 2.0.7

**Comment by ines** [comment]
Thanks for bringing this up!

The dependency graphs are SVG graphics, which support a [`writing-mode` attribute](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/writing-mode) on `<text>` elements. The NER view is just simple, inline HTML, so we might only have to add `direction: rtl` to the `<body>`'s `style`. (If you want to experiment with this or hack in a quick solution yourself, you'll find the HTML templates [here](https://github.com/explosion/spaCy/blob/master/spacy/displacy/templates.py).)

For now, we could simply have this as an option to displaCy – but I think going forward, the individual language classes should expose their writing direction, so displaCy can adjust the presentation accordingly. This could also be very useful for other applications.

**Comment by azarezade** [comment]
Thanks for the reply. 
Great! I am looking forward to see it in future releases.

**Comment by ines** [comment]
@azarezade I was just experimenting with different changes to displaCy to make this work smoothly. Do you have an example text that I could use and maybe a screenshot of how it *shouldn't* look? I just want to make sure that my solution really works!

**Comment by azarezade** [comment]
@ines For dependency tree I found an example [here](http://www.sobhe.ir/hazm/), which shows dependency tree for the following sentence:
زنگ‌ها برای که به صدا در می‌آید؟

<img width="691" alt="screen shot 1396-12-28 at 08 16 13" src="https://user-images.githubusercontent.com/11195749/37579065-972de99a-2b51-11e8-958e-d943eb99f401.png">

I should mention that that tree is slightly different with spaCy result, also the arrows direction (I think is reverse) but it gives an overall sketch.

For NER the result of the following sentence:
رئیس جمهور به کرمانشاه خواهد رفت
should be something like:
<img width="608" alt="screen shot 1396-12-28 at 08 42 31" src="https://user-images.githubusercontent.com/11195749/37579153-0ae097c0-2b52-11e8-91a9-556d79038744.png">

**Comment by ines** [comment]
See #3393! (If there's still something you think is bad or unideal, let me know!)
