### ISSUE TITLE
Model documentation for spaCy textcat model

### ISSUE THREAD

**Issue by jmrosen155** [explosion/spaCy#2094]
I've been exploring the text categorizer model in spaCy v2.0 which claims to use a CNN model. Beyond this, there doesn't yet seem to be much documentation on the specifics of the algo behind the textcat model. Can you please provide more details or documentation on the model being used or is there a paper that can be referenced? The only references I've been able to find thus far are:

1. High-level summary:
https://spacy.io/api/textcategorizer
2. Another issue which briefly touches on the performance of NN vs. linear models for text classification:
https://github.com/explosion/spaCy/issues/1550

## Info about spaCy

* **Python version:** 2.7.14
* **Platform:** Darwin-15.6.0-x86_64-i386-64bit
* **spaCy version:** 2.0.5
* **Models:** en, en_core_web_lg

**Comment by honnibal** [comment]
There's no paper unfortunately, no. I know it's not very satisfying, but the model architecture is currently considered an implementation detail: it's subject to change based on experiments, new techniques as they're published, etc.

The model definition can be found here: https://github.com/explosion/spaCy/blob/master/spacy/_ml.py#L469
