### ISSUE TITLE
Adding new vectors to a model

### ISSUE THREAD

**Issue by pierrerappolt** [explosion/spaCy#2097]
I am trying to combine a model with word vectors, so that when I use the annotator I can use 'en_core_web_sm' for pos tagging, and en_vectors_web_lg for looking up word vectors.

I am trying the code below, but it doesn't seem to be working properly. Is there a way to do this?

`   _english_annotator = en_core_web_sm.load()
    throwaway_annotator = en_vectors_web_lg.load()
    _english_annotator.vocab.from_bytes(throwaway_annotator.to_bytes())
    throwaway_annotator.vocab.reset_vectors() `

## Your Environment
* **Platform:** Darwin-17.4.0-x86_64-i386-64bit
* **Models:** en_core_web_md, en_core_web_lg, en_vectors_web_lg, en
* **Python version:** 3.4.3
* **spaCy version:** 2.0.5

**Comment by pvcastro** [comment]
Hi, were you able to solve this on your own?

**Comment by honnibal** [comment]
@pierrerappolt I think this should be resolved now. You can try the `v2.0.12.dev0` model, or the `v2.1.0a0` model which should be released soon.
