### ISSUE TITLE
Spacy v2 performing 16x slower

### ISSUE THREAD

**Issue by pierrerappolt** [explosion/spaCy#2098]
# Spacy V2

### Code
```
import timeit
import en_core_web_lg
import en_vectors_web_lg

_english_annotator = en_core_web_lg.load()
throwaway_annotator = en_vectors_web_lg.load()
_english_annotator.vocab.vectors.from_bytes(throwaway_annotator.to_bytes())
throwaway_annotator.vocab.reset_vectors()

def analyze():
  sent1=_english_annotator.pipe([('sample sentence!! fkafks')], disable=['parser', 'ner']).__next__()
  sent2=_english_annotator.pipe([('cant find it.......................')], disable=['parser', 'ner']).__next__()
  sent1.similarity(sent2)

analyze()
print(timeit.timeit(analyze, number=1000))
```

### Speed Test Results
> 38.35965299606323 seconds to load spacy annotator
> 4.4430288990042754 seconds per call to analyze

## Your Environment
* **Python version:** 3.4.3
* **Models:** en_core_web_md, en_core_web_lg, en_vectors_web_lg, en
* **Platform:** Darwin-17.4.0-x86_64-i386-64bit
* **spaCy version:** 2.0.5

# Spacy V1

### Code
```
import timeit
import spacy

_english_annotator = spacy.load('en', vectors='en_glove_cc_300_1m_vectors')

def analyze():
en_annotator(text
  sent1= _english_annotator('sample sentence!! fkafks', parser=False, entity=False)
  sent2=_english_annotator('cant find it........................', parser=False, entity=False)
  sent1.similarity(sent2)

analyze()
print(timeit.timeit(analyze, number=1000))
```

### Speed Test Results
> 9.591062068939209 seconds to load spacy annotator
> 0.2583060929973726 seconds per call to analyze

## Your Environment
* **Python version:** 3.4.3
* **Platform:** Darwin-17.4.0-x86_64-i386-64bit
* **spaCy version:** 1.1.2
* **Installed models:** en_glove_cc_300_1m_vectors-1.0.0, en-1.1.0, __cache__

**Comment by honnibal** [comment]
Please see here: https://github.com/explosion/spaCy/issues/2032 . There's also a thread open about performance of the pipeline.

You should also take care in your benchmarks to avoid calling a small workload many times. This usually performs completely differently from normal workloads.

**Comment by pierrerappolt** [comment]
@honnibal 

### Loading
Thank you for the reference to #2032, but loading isn't nearly as big a problem for us as performance of the pipeline. 

### Performance of Pipeline
I looked through #1508, but it doesn't seem to have a fix yet that will make spacy2 worth moving to, am I right? 

### Benchmarks
Unfortunately, I am using spacy in a context which requires calling a small workload many times, and I can't think of a good workaround to fix this problem.
