### ISSUE TITLE
Assert error raised by spacy.tokens.doc.Doc.push_back()

### ISSUE THREAD

**Issue by Imane0** [explosion/spaCy#2101]
I am trying to use the nlp pipeline from spacy to parse an already tokenized sentence. Here is the code:
```
# coding: utf-8
import spacy
nlp = spacy.load('en')
tokens = ['', 'ORG', 'Volatility', 'EUR', '-', 'Institutional', 'Class', '-', 'M', 'Class', '-', 'Classic', 'Class', '-', 'Classic', 'S', 'Class', '-', 'Classic', 'H', 'Class', '-', '0.50', '%', '-', '0.40', '%', '-', '0.80', '%', '-', '0.90', '%', '-', '1.10', '%', '-', '0.10', '%', '-', '0.30', '%', '-', '0.30', '%', '-', '0.30', '%', '-', '0.30', '%', 'Volatility', 'Equities', 'Sub', '-', 'Fund', 'Volatility', 'Euro', 'Equities']
spaces = [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, False, True, True, False, True, True, False, True, True, False, True, True, False, True, True, False, True, True, False, True, True, False, True, True, False, True, True, True, False, False, True, True, True, False]
doc = spacy.tokens.doc.Doc(nlp.vocab, words=tokens, spaces=spaces)
```
The execution of this script gives the following assertion error:
```
Traceback (most recent call last):
  File "pb.py", line 12, in <module>
    doc = spacy.tokens.doc.Doc(nlp.vocab, words=tokens, spaces=spaces)
  File "doc.pyx", line 177, in spacy.tokens.doc.Doc.__init__
  File "doc.pyx", line 560, in spacy.tokens.doc.Doc.push_back
AssertionError
```

As you can see, there is no message with the assertion error. What causes this error ? and how can I avoid it ?

## Your Environment

* **spaCy version:** 2.0.9
* **Platform:** Linux-4.15.7-300.fc27.x86_64-x86_64-with-fedora-27-Twenty_Seven
* **Python version:** 3.6.4
* **Models:** en_core_web_lg, en, fr_core_news_md, fr

**Comment by ines** [comment]
Sorry about the lack of a useful error message! I just tested it and the problem is the first token, which is an empty string: `''`. A token's `ORTH` value can't be empty – otherwise spaCy would have a zero-width token (which is essentially no token). So if you remove that token and the corresponding space, the `Doc` is created without problems.
