### ISSUE TITLE
"'s" not lemmatized correctly

### ISSUE THREAD

**Issue by dkarmon** [explosion/spaCy#2111]
I followed the rule base matcher tutorial from [here](https://spacy.io/usage/linguistic-features#example1) and created the same rule as mentioned there:
`[{'LOWER': 'facebook'}, {'LEMMA': 'be'}, {'POS': 'ADV', 'OP': '*'}, {'POS': 'ADJ'}]`

The rule should have located sentences such as "Facebook's annoying" (as it stated in the link), but in reality, it missed that sentence.
```
matched_sents = [] # collect data of matched sentences to be visualized

def collect_sents(matcher, doc, i, matches):
    match_id, start, end = matches[i]
    span = doc[start : end] # matched span
    sent = span.sent # sentence containing matched span
    # append mock entity for match in displaCy style to matched_sents
    # get the match span by ofsetting the start and end of the span with the
    # start and end of the sentence in the doc
    match_ents = [{'start': span.start_char - sent.start_char,
                   'end': span.end_char - sent.start_char,
                   'label': 'MATCH'}]
    matched_sents.append({'text': sent.text, 'ents': match_ents })

pattern = [{'LOWER': 'facebook'}, {'LEMMA': 'be'}, {'POS': 'ADV', 'OP': '*'},
           {'POS': 'ADJ'}]
matcher.add('FacebookIs', collect_sents, pattern) # add pattern
doc = nlp("Facebook's annoying. facebook is good. facebook is very good")
matches = matcher(text) # match on your text

```
The output:
![image](https://user-images.githubusercontent.com/669552/37563951-d66fef4e-2a94-11e8-9592-fd3cd215e9ba.png)

I printed the flags and POS of the sentences and it seems that the "'s" token was successfully identified as a VERB (lemma be)
![image](https://user-images.githubusercontent.com/669552/37563965-32d76e6a-2a95-11e8-80f3-bfe88f2e6cda.png)

Model used: en

**Comment by ines** [comment]
Thanks for the report – it looks like there's actually a problem with the lemmatization of `"'s"`. Even though the tag is correct, the lemma isn't overwritten based on the context, so the rule doesn't match. Will look into this, thanks!

**Comment by ines** [comment]
Just tested the example again with the latest version on `master` and it now works as expected – I'm getting the following matches:

```
Facebook's annoying
Facebook's annoying
facebook is good
facebook is good
facebook is very good
facebook is very good
```

[Here's the example](https://explosion.ai/demos/matcher?text=Facebook%27s%20annoying.%20facebook%20is%20good.%20facebook%20is%20very%20good&model=en_core_web_sm&pattern=%5B%7B%22id%22%3A0%2C%22attrs%22%3A%5B%7B%22name%22%3A%22LOWER%22%2C%22value%22%3A%22facebook%22%7D%5D%7D%2C%7B%22id%22%3A1%2C%22attrs%22%3A%5B%7B%22name%22%3A%22LEMMA%22%2C%22value%22%3A%22be%22%7D%5D%7D%2C%7B%22id%22%3A2%2C%22attrs%22%3A%5B%7B%22name%22%3A%22POS%22%2C%22value%22%3A%22ADV%22%7D%2C%7B%22name%22%3A%22OP%22%2C%22value%22%3A%22*%22%7D%5D%7D%2C%7B%22id%22%3A3%2C%22attrs%22%3A%5B%7B%22name%22%3A%22POS%22%2C%22value%22%3A%22ADJ%22%7D%5D%7D%5D) in our new `Matcher` visualizer 🙂
