### ISSUE TITLE
An exception has occurred, use %tb to see the full traceback. System exit 2.

### ISSUE THREAD

**Issue by samanvayagarwal** [explosion/spaCy#2113]
Hi,

I am experimenting with spacy to see if I can extract some info from SEC 10-Qs. To begin with, I used the code below but I get the following error - 

> usage: __main__.py [-h] [model]
> __main__.py: error: unrecognized arguments: -f --matplotlib='inline'
> SystemExit: 2
> An exception has occurred, use %tb to see the full traceback.
> SystemExit: 2

Any help will be greatly appreciated. 

Thanks!

```
from __future__ import unicode_literals, print_function
import plac
import spacy

TEXTS = [
    'Net income was $9.4 million compared to the prior year of $2.7 million.',
    'Revenue exceeded twelve billion dollars, with a loss of $1b.',
]

@plac.annotations(
    model=("Model to load (needs parser and NER)", "positional", None, str))
def main(model='en_core_web_sm'):
    nlp = spacy.load(model)
    print("Loaded model '%s'" % model)
    print("Processing %d texts" % len(TEXTS))

    for text in TEXTS:
        doc = nlp(text)
        relations = extract_currency_relations(doc)
        for r1, r2 in relations:
            print('{:<10}\t{}\t{}'.format(r1.text, r2.ent_type_, r2.text))


def extract_currency_relations(doc):
    # merge entities and noun chunks into one token
    spans = list(doc.ents) + list(doc.noun_chunks)
    for span in spans:
        span.merge()

    relations = []
    for money in filter(lambda w: w.ent_type_ == 'MONEY', doc):
        if money.dep_ in ('attr', 'dobj'):
            subject = [w for w in money.head.lefts if w.dep_ == 'nsubj']
            if subject:
                subject = subject[0]
                relations.append((subject, money))
        elif money.dep_ == 'pobj' and money.head.dep_ == 'prep':
            relations.append((money.head.head, money))
    return relations


if __name__ == '__main__':
    plac.call(main)
```

**Comment by ines** [comment]
Well, it looks like the problem here is related to the arguments you've passed in on the command line:

```
main.py: error: unrecognized arguments: -f --matplotlib='inline'
```

The script you're using only specifies one argument: `model` – but no argument with the shortcut `f` or an argument named `matplotlib`. Try removing those arguments and run the script again.

**Comment by samanvayagarwal** [comment]
Thanks for your reply. Not sure I understand though. I don't see the arguments you mention in the script. I am sorry if this is something basic but I am quite new to NLP.

**Comment by ines** [comment]
I think this is more of a general Python problem, so don't worry, you don't have to be an NLP expert to make it work 😊 

When you called `main.py` on the command line to run the script, how did your command look? The error message says you likely did something like this by accident:

```bash
python main.py -f --matplotlib='inline
```

But the script you're using in `main.py` only accepts one positional argument – which defaults to `'en_core_web_sm'`. So your command should be: `python main.py`.

Are you running the command from a Jupyter notebook or something similar? If so, this might also be an explanation. The scripts in our examples are intended to be standalone Python files that can be executed by running `python name_of_script.py`, and allow you to pass in arguments on the command line. To do this, we use a library called [Plac](https://micheles.github.io/plac/).

But if you're already in a notebook, you won't need this – so you can remove the following lines:

```python
if __name__ == '__main__':
    plac.call(main)
```

And just call the `main()` function directly:

```python
main()
```
