### ISSUE TITLE
Sentence segmentation(addding puntuation to a sentence)

### ISSUE THREAD

**Issue by saisrinivas047** [explosion/spaCy#2115]
Hi @honnibal 
I am new to spacy. So can someone help me how to add punctuation(commas,fullstop,question marks) to a sentence?

and how to use sentence boundary detection ?

example:
input: hello mom how are you 
output:hello mom, how are you ?
any help will be appreciated.

**Comment by mdcclv** [comment]
You could build a language model to insert punctuation, but this is pretty far outside the range of things that spaCy does out of the box. Maybe ask in a forum like /r/learnmachinelearning on Reddit?
