### ISSUE TITLE
importing model as module but then can't use add_pipe

### ISSUE THREAD

**Issue by michaelcapizzi** [explosion/spaCy#2117]
I have updated my code to import models as modules as described [here](https://spacy.io/usage/models#models-loading).

But then when I try to use `add_pipe()` to add a custom component, I get an error that:

```
E   AttributeError: module 'en_core_web_sm' has no attribute 'add_pipe'
```

 Is the process for adding custom pipeline items *different* when loading models as modules?

## My Environment
* **spaCy version:** 2.0.9
* **Platform:** Linux-4.4.0-112-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.2

**Comment by honnibal** [comment]
@michaelcapizzi The following should work:

```python
import en_core_web_sm
nlp = en_core_web_sm.load()
nlp.add_pipe(...)
```

If it doesn't, please advise! The error message looks like you called add_pipe on the module.

**Comment by michaelcapizzi** [comment]
Thanks @honnibal for taking the time to close this.  My code had a silly error.
