### ISSUE TITLE
Spacy Ner training code does not working for larger data.

### ISSUE THREAD

**Issue by akkefa** [explosion/spaCy#2118]
I am using this Spacy [code](https://github.com/explosion/spaCy/blob/master/examples/training/train_new_entity_type.py) example for training a new entity type(store_name) and total training data is around 2000 store_name. 
`[
('Store name 1', {'entities': [(0, 11, 'store_name')]}), 
('Store name 2', {'entities': [(0, 11, 'store_name')]}),
('Store name 3', {'entities': [(0, 11, 'store_name')]})
...
]`

When I do training with 30-50 lines of training data. Spacy complete the training process and save the model. We can load the model. Its generate the entity results.  Everything working fine.

But when we do training using 2000 lines of training data. Spacy complete the training process and save the model. We can load the model. Its unable to produce the  #any entities results.    

## Your Environment

* spaCy Version Used: 2.0.9
* Platform: Linux-3.10.0-693.11.6.el7.x86_64-x86_64-with-centos-7.4.1708-Core
* Python version: 3.6.4

**Comment by mobtexapp** [comment]
The sample code did not work here.

Can you help me?

[https://github.com/explosion/spaCy/issues/2124#issuecomment-375504188](url)

**Comment by ines** [comment]
Merging this with #2124: See [my comment here](https://github.com/explosion/spaCy/issues/2124#issuecomment-376649363) for more details.
