### ISSUE TITLE
UPDATING NER MODEL

### ISSUE THREAD

**Issue by sunny031002** [explosion/spaCy#2124]
Dear Sir/Madam,
I wanted to retrain a model for updating NER model. However after I trained the model using my custom inputs, it don't have the NER detection model from the original model. 

I followed the way explained in the following link:

https://github.com/explosion/spaCy/blob/master/examples/training/train_ner.py#L26

Is there any way to update the existing model, means adding some new label within the existing model, while keeping all the existing Entity model.
Thanks.

## Your Environment

* Operating System: Windows 10
* Python Version Used:  3.6
* spaCy Version Used: 2.09
* Environment Information:

**Comment by mobtexapp** [comment]
Same problem here.

It looks like it was made to not work. I tested everything and it does not work!

From this example  ANIMAL: https://spacy.io/usage/training




```python

#animal.py from https://spacy.io/usage/training 

 python animal.py -m en -nm sux_model -o sux_model

root@l33t:# python animal.py -m en -nm sux_model -o sux_model
Loaded model 'en'
{u'ner': 25.441294859206288}
{u'ner': 22.205166164350054}
{u'ner': 19.964678184297398}
{u'ner': 11.579913574201592}
{u'ner': 11.819450177801349}
{u'ner': 15.088982435385073}
{u'ner': 21.754225865867813}
{u'ner': 13.395478483147425}
{u'ner': 13.493569968592984}
{u'ner': 10.993481818940493}
{u'ner': 9.376471302228083}
{u'ner': 10.764308007562931}
{u'ner': 13.638724764252338}
{u'ner': 11.20770020757342}
{u'ner': 9.77107546328094}
{u'ner': 13.067131907864908}
{u'ner': 13.079215467417395}
{u'ner': 13.872915302673924}
{u'ner': 12.060704130396555}
{u'ner': 12.31111441048179}
Entities in 'Do you like horses?'
ANIMAL horses
Saved model to sux_model
Loading from sux_model
ANIMAL horses

```

Run another script with created model:

```python
root@l33t:# python er.py
(u'Who', u'who', u'NOUN', u'WP', u'attr', u'Xxx', True, False)
(u'is', u'be', u'VERB', u'VBZ', u'ROOT', u'xx', True, True)
(u'Shaka', u'shaka', u'PROPN', u'NNP', u'compound', u'Xxxxx', True, False)
(u'Khan', u'khan', u'PROPN', u'NNP', u'nsubj', u'Xxxx', True, False)
(u'?', u'?', u'PUNCT', u'.', u'punct', u'?', False, False)
(u'I', u'-PRON-', u'PRON', u'PRP', u'nsubj', u'X', True, False)
(u'HATE', u'hate', u'VERB', u'VBP', u'ROOT', u'XXXX', True, False)
(u'THIS', u'this', u'DET', u'DT', u'det', u'XXXX', True, False)
(u'SUCKS', u'sucks', u'PROPN', u'NNP', u'compound', u'XXXX', True, False)
(u'MODEL', u'model', u'PROPN', u'NNP', u'ROOT', u'XXXX', True, False)
(u'they', u'-PRON-', u'PRON', u'PRP', u'nsubj', u'xxxx', True, True)
(u'pretend', u'pretend', u'VERB', u'VBP', u'ROOT', u'xxxx', True, False)
(u'to', u'to', u'PART', u'TO', u'aux', u'xx', True, True)
(u'care', u'care', u'VERB', u'VB', u'xcomp', u'xxxx', True, False)
(u'about', u'about', u'ADP', u'IN', u'prep', u'xxxx', True, True)
(u'your', u'-PRON-', u'ADJ', u'PRP$', u'poss', u'xxxx', True, True)
(u'feelings', u'feeling', u'NOUN', u'NNS', u'pobj', u'xxxx', True, False)
(u',', u',', u'PUNCT', u',', u'punct', u',', False, False)
(u'those', u'those', u'DET', u'DT', u'det', u'xxxx', True, True)
**(u'horse', u'horse', u'NOUN', u'NN', u'appos', u'xxxx', True, False)**

```

How solve this?

**Comment by DomHudson** [comment]
@sunny031002 Are you able to provide code that generates the issue? 

@mobtexapp Your issue is not the same as the OPs. Please create your own issue if you believe there is a bug. Your current code does not indicate any bug - you are not printing the entity of the word HORSE, only the part-of-speech tag. The noun annotation for 'horse' is correct.

**Comment by mschroeder78** [comment]
Sounds like someone might be listening and or watching the command and trying to stall?

**Comment by ines** [comment]
It sounds like what you're experiencing is the "catastrophic forgetting" problem – as your model learns about the new entities, it's "forgetting" what it had previously learned.

Here are some resources and threads with more information and possible solutions:
* https://explosion.ai/blog/pseudo-rehearsal-catastrophic-forgetting
* #1892: Lot of false positives when using the NER model
* #1777: Improve spacy model for MONEY entity recognition 
* #1337: Custom NER model doesn't recognize any entities
* #1382: Predefined entities not detected after adding custom entities
