### ISSUE TITLE
Named Entity recognition doesnt recognize entities of product class.

### ISSUE THREAD

**Issue by sreenivasaupadhyaya** [explosion/spaCy#2130]
I use Python 3.6.3  and Spacy's named entity recognition using en_core_web_md model.
My reason for using Spacy was its NER feature for extracting product entities from a sentence.
But I am unable to extract out any product entity. 
I tried the simple sentences like a = "This container has some Sugar"
Could anyone please tell if I am missing something.
@honnibal

**Comment by ahalterman** [comment]
I don't think the [OntoNotes](https://spacy.io/usage/linguistic-features#entity-types) data that spaCy is trained on placed a large emphasis on the `PRODUCT` label, so it's quite possible it's not very good. If getting better accuracy is important, you'll probably need to look into training a model yourself. See [here](https://spacy.io/usage/training#ner) for the overview of how to do this, or https://prodi.gy/ for a very easy (speaking from experience!) way of training a new model.
