### ISSUE TITLE
bug of vector similarity in OSX

### ISSUE THREAD

**Issue by meshiguge** [explosion/spaCy#2132]
## this issue is related to computation of similarity in OSX
the computation of word _similarity_ of `spacy` output unexpected result 
**dog** and **dog**  get vecy low cosine score 

 ```python
 import numpy
import spacy
 nlp = spacy.load('en_core_web_lg')
 dog = nlp(u'dog')
 print dog.similarity(dog)
#  -2.19152246288e-21   

## use token type 
dog_token = nlp(u'dog cat banana') [0]
print dog_token.similarity(dog_token )
# -2.1915221e-21 
```
this problem seems `numpy.dot` 
```python
vec = dog_token.vector
print vec.shape  # (300,)

print np.dot(vec, vec) # -1.0842e-19 
print print (vec ** 2).sum() # 49.4726 


```
the problem of `np.dot` related to `dtype('float32')` 

```python 
print vec.dtype # dtype('float32')
print np.dot(vec, vec) # -1.0842e-19 
print np.dot(vec.astype(np.float64), vec) # 49.4725554776  


```
I follow the method [here](https://github.com/ContinuumIO/anaconda-issues/issues/7480)   and [here](https://github.com/RaRe-Technologies/gensim/issues/1846)
update numpy and mkl 
```python
# conda update mkl
# conda install numpy=1.14 
```
## Your Environment

* Operating System: osx
* Python Version Used: 2.7 (Anaconda)
* spaCy Version Used: 2.0.4
* Environment Information: en_core_web_lg
* numpy : 1.13.3 
* mkl      : 2018.0.0

**Comment by honnibal** [comment]
Thanks! Very annoying...

**Comment by meshiguge** [comment]
@honnibal  yes, my own experience
1 update  numpy >= 1.14
2 update mkl >= 2018.0.1
