### ISSUE TITLE
A strange phenomenon in PhraseMatcher

### ISSUE THREAD

**Issue by SivilTaram** [explosion/spaCy#2134]
Hi developers, thanks to your big contributions!

I have encountered a strange problem in PhraseMatcher. I'm trying using integers, instead of strings, to distinguish different matches in PhraseMatcher. But when I use integer 0, it doesn't work.

My version of Spacy is v2.0.9, python 3.5, Windows 10.

Code Example:
```python
matcher = PhraseMatcher(nlp.vocab)
matcher.add(0, None, nlp("hello"))
matcher(nlp("hello world"))
```

It will return nothing. But if you fix it as below:

```python
matcher = PhraseMatcher(nlp.vocab)
matcher.add(1, None, nlp("hello"))
matcher(nlp("hello world"))
```

It will work fine. I find the solution(avoid using zero to mark matcher) but I wonder why is it? Thanks for your answers!

**Comment by honnibal** [comment]
I think you're likely to get confusing results if you do it this way. spaCy maintains a string<->integer mapping, so there's a matching string for "1" that's an internal symbol. The matching string for 0 is the empty string, which might be causing the confusion.
