### ISSUE TITLE
If you're working on Windows, help me get Thinc compiling? 

### ISSUE THREAD

**Issue by honnibal** [explosion/spaCy#2136]
There are a lot of nice improvements in v2.1, which is mostly waiting on Windows compatibility. The new version should resolve most of the speed problems from v2.0. There were two big speed problems in v2.0: a) the tokenizer, b) different users reported very different parser speeds, as the computational bottleneck was the `sgemm` (float32 matrix multiplication) function accessed via numpy, which called into a BLAS library assumed to be installed on the system.

In order to remove this system dependency, Thinc 6.12.0 will be shipping the C and ASM source files for OpenBLAS's sgemm implementation. We'll be compiling the function within distutils, and compiling it into an extension `thinc.openblas`. By bringing our own BLAS, we can make sure spaCy and Thinc perform the same regardless of how you've configured the rest of your system. All you need is a compiler, or a wheel file previously compiled with appropriate settings.

The problem is that I haven't convinced Windows to compile OpenBLAS's ASM files yet. Here's the current log: https://ci.appveyor.com/project/explosion/thinc/build/job/a3uaywbl3pxj21mg . It's hard to google for Windows problems because half the threads are about which menus to click through in Visual Studio.

Thinc's setup.py file can be found here: https://github.com/explosion/thinc/blob/master/setup.py

The compiler is being called with this line:

```
C:\Users\appveyor\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\ml64.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DOS_WINDOWS -DC_MSVC -DF_INTERFACE_GFORT -DNO_LAPACK -DNO_LAPACKE -UDOUBLE -UCOMPLEX -DMAX_STACK_ALLOC=2048 -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=sgemm_kernel -DASMFNAME=sgemm_kernel_ -DNAME=sgemm_kernel_ -DCNAME=sgemm_kernel -DCHAR_NAME=sgemm_kernel_ -DCHAR_CNAME=sgemm_kernel_ -IC:\Python27-x64\include -IC:\projects\thinc\include -IC:\projects\thinc\include\msvc9 -IC:\projects\thinc\thinc\_files -IC:\Python27-x64\include -IC:\Python27-x64\PC /TcC:\projects\thinc\thinc\_files\kernel\x86_64\sgemm_kernel_16x4_haswell.S /FoC:\projects\thinc\thinc\_files\kernel\x86_64\projects\thinc\thinc\_files\kernel\x86_64\sgemm_kernel_16x4_haswell.obj /TaC:\projects\thinc\thinc\_files\kernel\x86_64\sgemm_kernel_16x4_haswell.S
```

**Comment by pzelasko** [comment]
Its a linker problem, if you look at the command line of link.exe, for some reason it gets openblas.lib on it's input libs list, which doesn't exist. I don't see any obvious place in setup.py where it's added as a dependency (writing from mobile), so maybe you accidentally copied it from numpy when adding openblas info in build_options?

**Comment by honnibal** [comment]
@pzelasko That was an intermediate state, where I tried another approach (linking against numpy's openblas.dll). I pursued a lot of other false starts as well!

I'm pleased to say I have a solution :tada: . The only downside at the moment is that the solution requires Windows users to install LLVM to compile Thinc. If someone can help convince MSVC to compile the .S kernels, that would be better.

Attached below is a draft of the write-up of all this for the docs. I've also included the notes about what I tried that didn't work.

# BLAS Linkage

Neural networks need to multiply matrices together. This is the computational bottleneck, so it's very important that the linear algebra routines are well optimized for the machine you're running on.

Most Python libraries delegate matrix multiplications to Numpy, which delegates them to a "BLAS" library. On OSX this is easy: the OS provides a BLAS library that is always well-tuned for the hardware. On Windows and Linux the situation is more complicated.

If you're not using OSX, you want numpy linked against either Intel's MKL library, or the free OpenBLAS library. Further, you want to make sure the library you're linked against has detected your CPU features correctly, and is compiled with settings appropriate for the machine you're using. For best performance, the library needs to know your CPU's instruction set, cache size and number of CPUs. Containers complicate this further, because the number of cores on the system may not be the same as the number of cores available.

If numpy is installed via conda, it'll typically be linked against Intel's MKL, and results will be pretty good. If installed via pip, performance is often quite bad. This problem is hard to debug, and affected a majority of spaCy users for the 2.0 release. To avoid this, Thinc 6.11 introduces a new "bring our own BLAS" strategy, which should give better default performance for spaCy 2.1.

# Bringing our own OpenBLAS

Thinc 6.11 "vendorizes" the C and ASM source code for the key function we need from OpenBLAS: sgemm (Single-precision General Matrix Multiplication). This one function is the source of all the troubles described above.

If you install Thinc by source, it will compile the sgemm function and include it in the `thinc.openblas` module, unless you set the `THINC_BLAS` environment variable to tell Thinc where to find your preferred BLAS shared library.

If you're compiling Thinc with Microsoft Visual Studio, you'll need to install the LLVM compiler suite to build the OpenBLAS sgemm kernels, as we do not currently know how to convince MSVC to compile the required assembly files. If you can help with this, please let us know.

# If you like your BLAS, you can keep it

If you're compiling Thinc from source, you can control the BLAS library Thinc links against using the `THINC_BLAS` environment variable. You should set this to the full absolute path to the shared library file you want Thinc to link against.

# Summary of options

## Windows

- `conda -c conda-forge install thinc`

  Installs Thinc binary wheel, linked against its own OpenBLAS kernels.

- `pip install thinc`

  Installs Thinc binary wheel, linked against its own OpenBLAS kernels.

- `pip install thinc —no-binary :all:`

  Compiles and installs Thinc from source. Builds and links against its own OpenBLAS kernels. Requires both MSVC and LLVM. 

- `THINC_BLAS="C:\path\to\mkl.lib" pip install thinc —no-binary :all:`

  Compiles and installs Thinc from source, linking it against the specified BLAS library. Requires MSVC.

# Linux

- `conda -c conda-forge install thinc`

  Installs Thinc binary wheel, linked against its own OpenBLAS kernels.

- `pip install thinc`

  Compiles and installs Thinc from source. Builds and links against its own OpenBLAS kernels.

- `THINC_BLAS="/path/to/libmkl.so" pip install thinc`

  Compiles and installs Thinc from source, linking it against the specified BLAS library.

# OSX

- `conda -c conda-forge install thinc`

  Installs Thinc binary wheel, linked against the system's Accelerate framework.

- `pip install thinc`

  Compiles and installs Thinc from source, linked against the system's Accelerate framework.

- `THINC_BLAS="/path/to/libmkl.so" pip install thinc`

  Compiles and installs Thinc from source, linking it against the specified BLAS library.

# False starts

In case anyone's interested, here are some notes I made while trying to figure this out :)

Life in Windows/BLAS land remains frustrating. I have several avenues of attack:

1) Try to get the OpenBLAS assembly kernels compiling in MSVC. Status: Seems to require clang and LLVM? Not sure. Paused.
2) Try to get OpenBLAS generic kernels compiling. Status: Compiles, but gets wrong result on *both* Linux and Windows. Trying to figure out if I built incorrectly, or nobody uses this gemm_kernel_2x3.c file and it's broken.
3) Build against numpy's openblas.lib as a fallback. Status: Numpy only ships the dll, not the .lib.
4) Build against a different blas lib? No blas lib provided by Windows in any standard way. Installing blas seems hard. Also Windows users are bad at things and complain a lot.
5) Build optimized blis kernels, provide as Python package? I have this working for Linux in the cython-blis package. I think this hits the same ASM problem.
6) Build generic blis kernels? Bits of the code aren't portable C. I fixed 5-10 errors around stuff like typeof() or other GCC extensions and got to linking. Then I hit usage of gcc atomics such as `__sync_fetch_and_add`. They're used in the threading which we might not need, but I paused efforts there.
7) Call Numpy from Python as a fallback? This will be pretty slow, as we'll have to recreate the Python containers. At least it should work I guess.
