### ISSUE TITLE
Latest version mistaken: 2.10.x not 1.10.1

### ISSUE THREAD

**Issue by mosynaq** [explosion/spaCy#2143]
Hey @ines, I always check for spacy's latest version. Now I found version 1.10.1 is released. But I think version 2.10.x was expected. Am I wrong?

**Comment by ines** [comment]
Sorry if this was confusing – we did indeed push a patch to `v1.x` to fix an issue with pip for users who are still on older versions (see #2110). Didn't realise that GitHub would display that so prominently as the "latest release", which is definitely unideal. We just released `v2.0.10`, though, so everything should look normal again 😄
