### ISSUE TITLE
cx_Freeze compatibility 

### ISSUE THREAD

**Issue by clabe45** [explosion/spaCy#2145]
I'm using cx_Freeze to build an exe from my spacy python program. When I run the exe, I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\monke\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
    module.run()
  File "C:\Users\monke\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
    exec(code, m.__dict__)
  File "friendbot.py", line 361, in <module>
    nlp = spacy.load('en')
  File "C:\Users\monke\AppData\Local\Programs\Python\Python36-32\lib\site-packages\spacy\__init__.py", line 19, in load
    return util.load_model(name, **overrides)
  File "C:\Users\monke\AppData\Local\Programs\Python\Python36-32\lib\site-packages\spacy\util.py", line 113, in load_model
    return load_model_from_link(name, **overrides)
  File "C:\Users\monke\AppData\Local\Programs\Python\Python36-32\lib\site-packages\spacy\util.py", line 127, in load_model_from_link
    cls = import_file(name, path)
  File "C:\Users\monke\AppData\Local\Programs\Python\Python36-32\lib\site-packages\spacy\compat.py", line 120, in import_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\monke\\Documents\\python\\friendbot\\v0.1\\build\\exe.win32-3.6\\lib\\spacy\\data\\en\\__init__.py'
```

The important part is that the error occurs on the line of code `nlp = spacy.load('en')`, after `spacy` is imported.

**The problem is that I have an `__init__.pyc` in `lib\spacy\data\en` but not an `__init__.py`** (in my build directory).

My version of cx_Freeze is 5.1.1 .

## Info about spaCy

* **spaCy version:** 2.0.9
* **Platform:** Windows-10-10.0.16299-SP0
* **Python version:** 3.6.3
* **Models:** en

**Comment by mschroeder78** [comment]
Is the c at the end staring a deviated command? 
-------- Original message --------From: Caleb Sacks <notifications@github.com> Date: 3/24/18  6:01 PM  (GMT-06:00) To: explosion/spaCy <spaCy@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [explosion/spaCy] cx_Freeze compatibility (#2145) 
I'm using cx_Freeze to build an exe from my spacy python program. When I run the exe, I get the following error:
Traceback (most recent call last):
  File "C:\Users\monke\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
    module.run()
  File "C:\Users\monke\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
    exec(code, m.__dict__)
  File "friendbot.py", line 361, in <module>
    nlp = spacy.load('en')
  File "C:\Users\monke\AppData\Local\Programs\Python\Python36-32\lib\site-packages\spacy\__init__.py", line 19, in load
    return util.load_model(name, **overrides)
  File "C:\Users\monke\AppData\Local\Programs\Python\Python36-32\lib\site-packages\spacy\util.py", line 113, in load_model
    return load_model_from_link(name, **overrides)
  File "C:\Users\monke\AppData\Local\Programs\Python\Python36-32\lib\site-packages\spacy\util.py", line 127, in load_model_from_link
    cls = import_file(name, path)
  File "C:\Users\monke\AppData\Local\Programs\Python\Python36-32\lib\site-packages\spacy\compat.py", line 120, in import_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\monke\\Documents\\python\\friendbot\\v0.1\\build\\exe.win32-3.6\\lib\\spacy\\data\\en\\__init__.py'

The important part is that the error occurs on the line of code nlp = spacy.load('en'), after spacy is imported.
The problem is that I have an __init__.pyc in lib\spacy\data\en but not an __init__.py (in my build directory).
My version of cx_Freeze is 5.1.1 .
Info about spaCy

spaCy version: 2.0.9
Platform: Windows-10-10.0.16299-SP0
Python version: 3.6.3
Models: en


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/explosion/spaCy","title":"explosion/spaCy","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/explosion/spaCy"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"cx_Freeze compatibility  (#2145)"}],"action":{"name":"View Issue","url":"https://github.com/explosion/spaCy/issues/2145"}}}

**Comment by clabe45** [comment]
> Is the c at the end staring a deviated command? 
I don't follow you - what's a deviated command?

**Comment by honnibal** [comment]
Maybe try writing:

```python

import en_core_web_sm

nlp = en_core_web_sm.load()
```

Or alternatively `nlp = spacy.load('en_core_web_sm')`. I suspect the symbolic link required to alias `en_core_web_sm` to `en` is the part that's failing here. If you either import the model directly, or load it by its One True Name, you remove some layers of indirection so it might work better.

I've had success getting executables for Linux using the `pex` utility. This requires Python to be on the system, so it's note quite the same. But it does suggest that `cx_freeze` should work.

Good luck, and please update if you get it to work! We'd love to have instructions for this, and possibly even offer an exe for download.

**Comment by mschroeder78** [comment]
@media only screen and (min-width: 480px) {
    /*
         * Disable apple event/telephone links
         */
    a[x-apple-data-detectors] {
        color: inherit !important;
        text-decoration: none !important;
        font-size: inherit !important;
        font-family: inherit !important;
        font-weight: inherit !important;
        line-height: inherit !important
        }
    table[class~=lyft-email] {
        padding: 20px !important;
        min-width: 100% !important
        }
    table[class~=lyft-email-wrapper] {
        width: 100% !important
        }
    div[class~=lyft-email-body] {
        padding: 0 !important
        }
    table[class~=mobile-show], td[class~=mobile-show] {
        display: none !important
        }
    table[class~=mobile-hide] {
        display: table !important
        }
    td[class~=mobile-hide] {
        display: table-cell !important
        }
    table[class~=complaince-text] a {
        text-decoration: none !important;
        color: #00ADEF !important
        }
    }
@media only screen and (max-width: 480px) {
    /*
         * Media query styles should only use attribute selectors so they are not applied
         * erroneously by Yahoo Mail.
         * @see http://goo.gl/0dIf2C
         */
    /*
         * Disable apple event/telephone links
         */
    a[x-apple-data-detectors] {
        color: inherit !important;
        text-decoration: none !important;
        font-size: inherit !important;
        font-family: inherit !important;
        font-weight: inherit !important;
        line-height: inherit !important
        }
    table[class~=lyft-email] {
        padding: 0 !important;
        min-width: 100% !important
        }
    div[class~=lyft-email-header] {
        padding: 0 !important
        }
    table[class~=lyft-email-wrapper] {
        width: 100% !important
        }
    div[class~=lyft-email-header], table[class~=lyft-logo], table[class~=lyft-email-card] {
        -webkit-border-radius: 0 !important;
        -moz-border-radius: 0 !important;
        border-radius: 0 !important
        }
    table[class~=wrapper] {
        width: 100% !important
        }
    table[class=main_table] {
        width: 320px !important
        }
    td[class=side] {
        width: 15px !important
        }
    td[class=hide] {
        display: none !important
        }
    img[class=hide] {
        display: none !important
        }
    table[class=hide] {
        display: none !important
        }
    td[class=text] {
        text-align: center !important
        }
    a[class=text] {
        text-align: center !important
        }
    td[class=pad_top] {
        padding-top: 20px !important
        }
    td[class=pad_bottom] {
        padding-bottom: 20px !important
        }
    td[class=clear_both] {
        float: left !important;
        clear: both !important;
        width: 100% !important;
        height: auto !important
        }
    td[class=cen] {
        padding-left: 15px !important;
        padding-right: 15px !important
        }
    br[class=br1] {
        display: none !important
        }
    span[class=br2] {
        display: block !important
        }
    span[class=hide] {
        display: none !important
        }
    td[class=bg_mob] {
        background-image: none !important
        }
    td[class=side_top] {
        height: 12px !important
        }
    div[class=hide_desktop] {
        display: table !important;
        float: none !important;
        width: 100% !important;
        overflow: visible !important;
        height: auto !important
        }
    td[class=grey34] {
        text-align: center !important
        }
    td[class=text_size1] {
        font-size: 15px !important
        }
    td[class=text_size11] {
        font-size: 15px !important
        }
    td[class=text_size2] {
        font-size: 28px !important
        }
    td[class=bg_mob_col] {
        background-color: #e9e7e4 !important
        }
    td[class~=footer-links] {
        text-align: center !important
        }
    table[class=btn] table {
        width: 100% !important
        }
    table[class~=content-table] {
        width: 320px !important
        }
    table[class~=mobile-table-full] {
        width: 100% !important
        }
    h3[class~=mobile-text-center], td[class~=mobile-text-center] {
        text-align: center !important
        }
    table[class~=mobile-show] {
        display: table !important
        }
    td[class~=mobile-show] {
        display: table-cell !important
        }
    table[class~=mobile-hide], td[class~=mobile-hide] {
        display: none !important
        }
    table[class~=helpful-button] {
        padding-top: 8px !important;
        width: 100% !important
        }
    table[class~=helpful-button-td] {
        width: 100% !important
        }
    td[class~=mobile-text-left] {
        text-align: left !important
        }
    td[class~=mobile-text-right] {
        text-align: right !important
        }
    img[class~=mobile-remove-padding], table[class~=mobile-remove-padding] {
        padding: 0 !important
        }
    table[class~=mobile-padding-sides-sm] {
        padding-left: 5px !important;
        padding-right: 5px !important
        }
    table[class~=mobile-padding-sides-md] {
        padding-left: 10px !important;
        padding-right: 10px !important
        }
    table[class~=mobile-padding-sides-lg] {
        padding-left: 20px !important;
        padding-right: 20px !important
        }
    table[class~=footer-social-links] {
        width: auto !important
        }
    table[class~=complaince-text] a {
        text-decoration: none !important;
        color: #00ADEF !important
        }
    }
@media only screen and (min-width: 480px) and (max-width: 599px) {
    /*
         * Disable apple event/telephone links
         */
    a[x-apple-data-detectors] {
        color: inherit !important;
        text-decoration: none !important;
        font-size: inherit !important;
        font-family: inherit !important;
        font-weight: inherit !important;
        line-height: inherit !important
        }
    table[class~=lyft-email] {
        padding: 0 !important;
        min-width: 100% !important
        }
    div[class~=lyft-email-header] {
        padding: 0 !important
        }
    table[class~=lyft-email-wrapper] {
        width: 100% !important
        }
    div[class~=lyft-email-header], table[class~=lyft-logo], table[class~=lyft-email-card] {
        -webkit-border-radius: 0 !important;
        -moz-border-radius: 0 !important;
        border-radius: 0 !important
        }
    table[class~=wrapper] {
        width: 100% !important
        }
    table[class=main_table] {
        width: 480px !important
        }
    img[class=hide] {
        display: none !important
        }
    td[class=side] {
        width: 15px !important
        }
    td[class=side_top] {
        height: 12px !important
        }
    span[class=hide] {
        display: none !important
        }
    td[class=hide] {
        display: none !important
        }
    span[class=br2] {
        display: block !important
        }
    table[class=hide] {
        display: none !important
        }
    td[class=text] {
        text-align: center !important
        }
    td[class=grey34] {
        text-align: center !important
        }
    a[class=text] {
        text-align: center !important
        }
    td[class=text_size1] {
        font-size: 16px !important
        }
    td[class=text_size11] {
        font-size: 15px !important
        }
    td[class=clear_both] {
        float: left !important;
        clear: both !important;
        width: 100% !important;
        height: auto !important
        }
    div[class=hide_desktop] {
        display: table !important;
        float: none !important;
        width: 100% !important;
        overflow: visible !important;
        height: auto !important
        }
    td[class=cen] {
        padding-left: 15px !important;
        padding-right: 15px !important
        }
    br[class=br1] {
        display: none !important
        }
    td[class=pad_bottom] {
        padding-bottom: 20px !important
        }
    td[class=bg_mob_col] {
        background-color: #e9e7e4 !important
        }
    td[class=text_size2] {
        font-size: 28px !important
        }
    td[class~=footer-links] {
        text-align: center !important
        }
    table[class~=content-table] {
        max-width: 320px !important
        }
    table[class~=mobile-table-full] {
        width: 100% !important
        }
    h3[class~=mobile-text-center], td[class~=mobile-text-center] {
        text-align: center !important
        }
    table[class~=mobile-show] {
        display: table !important
        }
    td[class~=mobile-show] {
        display: table-cell !important
        }
    table[class~=mobile-hide], td[class~=mobile-hide] {
        display: none !important
        }
    table[class~=helpful-button] {
        padding-top: 8px !important;
        width: 100% !important
        }
    table[class~=helpful-button-td] {
        width: 100% !important
        }
    td[class~=mobile-text-left] {
        text-align: left !important
        }
    td[class~=mobile-text-right] {
        text-align: right !important
        }
    img[class~=mobile-remove-padding], table[class~=mobile-remove-padding] {
        padding: 0 !important
        }
    table[class~=mobile-padding-sides-sm] {
        padding-left: 5px !important;
        padding-right: 5px !important
        }
    table[class~=mobile-padding-sides-md] {
        padding-left: 10px !important;
        padding-right: 10px !important
        }
    table[class~=mobile-padding-sides-lg] {
        padding-left: 20px !important;
        padding-right: 20px !important
        }
    table[class~=footer-social-links] {
        width: auto !important
        }
    table[class~=complaince-text] a {
        text-decoration: none !important;
        color: #00ADEF !important
        }
    }









    



  
    
    
        
          
              
                 
              
              
                
                    
                       
                      
                        
                          
                        
                      
                       
                    
                  
              
              
                 
              
            
        
        
          
              
                
                  
                    
                      
                        
                          
                            
                              
                            
                          
                        
                        
                          
                            
                                

    
    

    
    
    
     

      
  
 
    
        
            
 Get Your $500 Bonus And Then Keep Earning 

        
    
    
    
        
            
                
            
        
    
    
        
            
            
                Matthew Schroeder thinks you'd be a perfect Lyft driver, and we agree.
                
                

                It's the right time to apply: You're eligible for an additional $2 bonus for every ride you give in your first 30 days, up to
                $500, just for signing up
                through Matthew's link.

                
                

            
        
    
    

        
            









    
        
            
                
                    
                        
                            
                                  
Learn More
  
                            
                        
                    
                
            
        
    

            
        
    





    
    
        
            
        
    
        
            -
        
    
        
            
        
    
    


    
 As a Lyft driver, you'll make money by giving rides in your own car, whenever you want. Lyft matches you with
        passengers who request rides through our app. When the ride ends, the app automatically charges the passenger's
        saved credit card, and directly deposits your earnings in your bank account weekly. It's that easy.
    
    

    
        Restrictions apply. See Terms .
    
    Offer valid for the first 1,000 applicants.


                                

                            
                          
                        
                      
                    
                  
                
              
            
        
        
          
              
                 
              
              
                
                    
                       
                      
                          
                            

                                
                                  
                                      
                                        
                                          
                                          
                                              © Lyft 2018
                                              185 Berry Street, Suite 5000
                                              San Francisco, CA 94107
                                          
                                        
                                      
                                      
                                         
                                      
                                    
                                
                              
                              
                                
                                  
                                      
                                        
                                            
                                              
                                                  
                                                    
                                                     
                                                    
                                                  
                                                
                                            
                                          
                                      
                                      
                                         
                                      
                                        
                                            


    
        
            Questions? Visit our Help Center
        
    
    
      
    Unsubscribe

**Comment by honnibal** [comment]
Why are you excluding spacy from the packages? I'm pretty sure you do need that.
