### ISSUE TITLE
Lemmatization of  acronyms need to be improved

### ISSUE THREAD

**Issue by supercoderhawk** [explosion/spaCy#2150]
OS: Ubuntu 16.04
Spacy version: 2.0.9
Python version: 3.6

Lemma of word need to be improved considering about acronyms.

Like word 'LED' means 'Light-emitting diode' in many conditions, so its lemma is just itself. However, spacy output the 'lead' as its lemma, seems 'LED' is considered as the preterit of 'lead'.

**Comment by honnibal** [comment]
Merging with #3052 (inaccurate prediction master thread)
