### ISSUE TITLE
SpaCy cannot run with Tensorflow >= 1.5 due to html5lib package version conflict

### ISSUE THREAD

**Issue by admackin** [explosion/spaCy#2151]
This is super frustrating – spaCy requires `html5lib==1.0b8`. But `tensorflow-tensorboard` [depends on](https://github.com/tensorflow/tensorboard/blob/master/tensorboard/pip_package/setup.py#L30) `html5lib==0.9999999`. Ordinarily this would be a version conflict and then I'd find some compatible set of dependencies (Python doesn't seem to handle this well but I know it's a hard problem!). However *of course* the `html5lib` devs decided to release the *same package* with two different version numbers (infuriating). So these are in fact the same version as required by `tensorboard` and the version conflict is totally spurious (I can't work out how to tell `pkg_resources` this though!).

One way to mitigate this might be to allow both `1.0b8` and `0.9999999` in `setup.py` but  `setuptools` doesn't seem to allow specifying *or* in the version spec. However I *think* a nice readable version spec like

`html5lib >=0.9999999, <= 1.0b8, != 0.99999999, != 0.999999999, != 1.0, !=1.0b2, != 1.0b3, != 1.0b4, != 1.0b5, != 1.0b6, != 1.0b7`

should do the trick and at least render spaCy slightly more compatible with other packages. 

Would you be amenable to this? I can submit a PR if so

## Your Environment

* Operating System: Multiple
* Python Version Used: 3.6
* spaCy Version Used: 2.0.8-2.0.10
* Environment Information: Also have transitive tensorflow deps

**Comment by honnibal** [comment]
Sorry for the frustration on this. We got into ependency hell with our dependencies over this, hence the tight pin.

For now, check out the tag for the version you want e.g. v2.0.10, edit the requirements and build yourself a wheel with `python setup.py bdist_wheel`. Should get you productive until we can release a fix.

**Comment by ines** [comment]
Some more background on the annoying dependency: It was needed to mitigate a problem with `six`, so spaCy isn't even using `html5lib` directly. We already got rid of both dependencies on `develop` and I'll see if I can port this over to `master` already so it's all set up correctly when you build from source.

**Comment by admackin** [comment]
hooray! Thanks both of you
