### ISSUE TITLE
Hashtag example not working for multiple hashtags

### ISSUE THREAD

**Issue by crazyfrogspb** [explosion/spaCy#2156]
Hashtag example (https://spacy.io/usage/linguistic-features#example3) doesn't work when you have multiple hashtags in the document:
```
from spacy.lang.en import English
from spacy.matcher import Matcher

nlp = English()
matcher = Matcher(nlp.vocab)

def merge_hashtag(matcher, doc, i, matches):
    match_id, start, end = matches[i]
    span = doc[start : end]
    span.merge()

matcher.add('HASHTAG', merge_hashtag, [{'ORTH': '#'}, {'IS_ASCII': True}])

text = "this is an #example of an awesome tweet with #manyhashtags #amazing"
doc = nlp(text)
matches = matcher(doc)

print([t.text for t in doc])

['this is an #example of an awesome tweet with #manyhashtags #amazing']
```
I guess this is because of how "span.merge()" works. Any workarounds? Thanks.

P.S. Not relevant to my particular problem, but
```
IS_HASHTAG = nlp.vocab.add_flag(lambda text: False)
def merge_hashtag(matcher, doc, i, matches):
    match_id, start, end = matches[i]
    span = doc[start : end]
    span.merge() # merge hashtag
    span.set_flag(IS_HASHTAG, True) # set IS_HASHTAG to True
```
from the same example produces the following error:
`AttributeError: 'spacy.tokens.span.Span' object has no attribute 'set_flag'`

## Your Environment
* **spaCy version:** 2.0.10
* **Platform:** Windows-10-10.0.16299-SP0
* **Python version:** 3.6.0
* **Models:** en-1.1.0, en_glove_cc_300_1m_vectors-1.0.0, __cache__

**Comment by ines** [comment]
Sorry about this – this should have been adjusted. To avoid messing with the token indices when merging the spans as the matches come in, a better strategy is to create the spans from the matches and merge them afterwards. The following works as expected:

```python
matcher = Matcher(nlp.vocab)
matcher.add('HASHTAG', None, [{'ORTH': '#'}, {'IS_ASCII': True}])

doc = nlp("this is an #example of an awesome tweet with #manyhashtags #amazing")
matches = matcher(doc)
spans = []
for match_id, start, end in matches:
    spans.append(doc[start:end])
for span in spans:
    spans.merge()

print([t.text for t in doc])
# ['this', 'is', 'an', '#example', 'of', 'an', 'awesome', 'tweet', 'with', '#manyhashtags', '#amazing']
```

Will change this accordingly in the docs! 👍

**Comment by crazyfrogspb** [comment]
Thanks a lot! 

One more question on this if you don't mind. I created my own Tokenizer class with a lot of custom matching rules, including different options for tokenizing hashtags (such as splitting compound hashtags into separate words). I initialize a matcher when a user creates a Tokenizer object, so in this case I would need to initialize two matchers, merge the hashtags first with the first matcher, and do the rest of processing with the second one, right? Are there any other, perhaps, more efficient ways to do it?

**Comment by ines** [comment]
> I initialize a matcher when a user creates a Tokenizer object, so in this case I would need to initialize two matchers, merge the hashtags first with the first matcher, and do the rest of processing with the second one, right? Are there any other, perhaps, more efficient ways to do it?

Yes, you can use two matchers if necessary – for example, if one of them needs to live within your tokenizer or a [custom pipeline component](https://spacy.io/usage/processing-pipelines#section-custom-components). Alternatively, you could also use the `match_id` to determine which action to trigger after all matches are collected. For example:

```python
for match_id, start, end in matches:
    match_id_string = nlp.vocab.strings[match_id]  # get the string value of the ID
    if match_id_string == 'HASHTAG':
        # do something hashtag-related
    elif match_id_string == 'SOME_OTHER_RULE':
        # do something else
```
