### ISSUE TITLE
💫 Suggestions for error messages and warnings

### ISSUE THREAD

**Issue by ines** [explosion/spaCy#2164]
I just submitted a PR in #2163 that addresses a variety of issues around spaCy's error handling and introduces a new system for managing error messages and custom warnings. Here's the gist:

> * Moved all errors and warning messages to `spacy.errors` with unique error codes to separate them from the code and make them reusable if necessary.
> * Replaced all random `assert`s in the code with actual, meaningful error messages.
> * Added handlers for custom, spaCy-specific warnings (deprecation, models, usage).

**We'd love to hear your feedback and suggestions for new errors and warnings to add!** Of course, we ideally want to iron out any quirks and weird behaviours as much as possible – if spaCy does weird and unexpected things, we'd rather make them consistent than print warnings.

Here are some examples:

* Easy mistakes to make, things you've tripped over before when using spaCy and that are difficult to prevent from the library side. Those are good cases for warnings.
* Other things that are "legal", but very bad practice because they often lead to various problems down the line. Those would also make good warnings. 
* Errors that are confusing. We've already replaced the various `AssertionError`s across the code base – but there might be other errors that are unclear.
* Missing error handling.

Looking forward to your feedback and ideas! 😊

**Comment by whiletruelearn** [comment]
@ines Something which took a while for me to figure out is that the `similarity` function that is present with the smaller models perform rather poorly and i was not aware of the need for downloading the larger models. While trying to get the vectors for words, i saw lots of them being returned as zero vectors.

I suggest adding a new Warning message which conveys the [important note message](https://spacy.io/usage/vectors-similarity) that is already present in the docs.
