### ISSUE TITLE
GPU usage in inference mode

### ISSUE THREAD

**Issue by yonilx** [explosion/spaCy#2174]
Is is possible to use the GPU in inference mode ? 
For example in the basic: 
```
nlp = spacy.load('en')
doc = nlp('this sentence is an example')  # gpu usage here ?
```
I've added gpu support to spacy but it doesn't seem to do much when running these lines other than allocating some memory.

Are there any plans to add support for this ?

## Your Environment

* **Python version:** 2.7.12
* **Platform:** Linux-4.10.0-28-generic-x86_64-with-Ubuntu-16.04-xenial
* **spaCy version:** 2.0.10
* **Models:** en

**Comment by hellolovetiger** [comment]
@yonilx I encountered the same problem with you. Can you run inference on GPU now?

**Comment by yonilx** [comment]
Nope, I'm pretty sure SpaCy wasn't design to run on GPU in inference mode.
At least for now.

**Comment by hellolovetiger** [comment]
Got it，thx
