### ISSUE TITLE
Are there projects that combine Spacy and Skos taxonomies?

### ISSUE THREAD

**Issue by jansaasman** [explosion/spaCy#2176]
Hi: this is a low priority and not very technical issue but I wanted to give it a try anyway. I'm having a blast exploring Spacy. The code and the APIs are very well done, the tutorials and documentation are amazing. So I want to combine it with my daily world of working with semantic technologies. What I tried to find on Google was projects that take an existing RDF/SKOS taxonomy and automatically add the leave nodes, both  the preflabels and the altlabels and add them programmatically to the entity extractor. Does anyone know if this has been done? Cheers, Jans

**Comment by DuyguA** [comment]
Hi jansaasman,

The procdure you describe is called "ontology learning", i.e. learn ontology elements from sturctured or unstructured data.

This sort of projects require huge amount of ML components. Extracting relations and placing them in an appropriate place is not an easy task. Usually one puts several modules together.

I include this link for a quick survey: https://www.inf.uni-hamburg.de/en/inst/ab/lt/publications/2005-biemannetal-ldvforum-ontology.pdf

Myself uses ontologies (owl format) for my chatbot project. Ontology goes into the context manager module and  SpaCy goes into the NLU module, we combine a knowledge graph with linguistic information that we mined from user queries.

Cheers, Duygu.

**Comment by jansaasman** [comment]
Hi Duygu: thanks very much for taking the time to write a response to my 
question. Your answer confuses me a little bit: I already have a 
taxonomy so I don't really have to learn it from the unstructured data, 
do I? I had hoped that by providing Spacy with word-lists the entity 
extractor would magically do its work .. or am I missing something? 
Regards, Jans

**Comment by ines** [comment]
@jansaasman Yes, that's definitely possible, too. spaCy's `PhraseMatcher` is designed to match very large terminology list by using `Doc` objects as match patterns. spaCy's `doc.ents` is writeable, so you can add the matches based on your word list and assign custom labels to them.

Here's a simple example:

```python
import spacy
from spacy.matcher import PhraseMatcher
from spacy.tokens import Span

nlp = spacy.load('en')  # or any other model
matcher = PhraseMatcher(nlp.vocab)

word_list = ['single', 'and', 'multi-token words', 'from', 'your', 'list']
patterns = [nlp(word) for word in word_list]  # create patterns from your word
matcher.add('YOUR_ENTITY_LABEL', None, *patterns)

doc = nlp("lots of text you want to process...")
matches = matcher(doc)
for match_id, start, end in matches:
   entity = Span(doc, start, end, label=label)  # create a span from our match
   doc.ents = list(doc.ents) + [entity]  # add it to the entities
```

You might also find these two examples useful – they show how to use the `PhraseMatcher` to match large terminology lists and add entity labels for them:

* [`custom_component_entities.py`](https://github.com/explosion/spaCy/blob/master/examples/pipeline/custom_component_entities.py)
* [`custom_component_countries_api.py`](https://github.com/explosion/spaCy/blob/master/examples/pipeline/custom_component_countries_api.py) (this one uses data via an API to show that this is possible, too)

Depending on your use case, a fully rule-based approach could be absolutely sufficient – especially if you already have extensive word lists and taxonomies. And if you do decide to train a model to recognise similar terms and phrases in context later on, you can use the matches produced by the `PhraseMatcher` as training data. ([This section](https://spacy.io/usage/training#training-data) has some more details on this.)

**Comment by ines** [comment]
Oh sorry, that was a typo – it was supposed to say `label=match_id`. This will assign the ID of the string `'YOUR_ENTITY_LABEL'` as the entity label. You can add several rules to your matcher like this – for example, one rule with per word list category.

> I changed into label=1 and the example started to work

Using `1` as a label works, too – but it might lead to unexpected or confusing results later on if you ever convert the integer label to a string. Under the hood, spaCy encodes all strings to integers and stores them in the `StringStore` – you can find more info on this [here](https://spacy.io/usage/spacy-101#vocab). So an ID like `1` also represents a string – usually something random like a part-of-speech tag or lexical attribute (because spaCy's labels are encoded, too).

Here's an interesting example:

```python
doc = nlp(u"hello world")
span = Span(doc, 0, 1, label=99)
print(span.text, span.label_)  # let's look at the span's text and string label
# 'hello' 'VERB'  <--- wtf?
```

Turns out that the part-of-speech tag "VERB" happens to be mapped to the ID `99` – you test this by looking it up in the `StringStore`, i.e. `vocab.strings`:

```python
nlp.vocab.strings[99]  # VERB
nlp.vocab.strings['VERB']  # 99
nlp.vocab.strings['YOUR_CUSTOM_LABEL']  # 11211630373680995617
```

**Comment by jansaasman** [comment]
Cool. I changed that it now it makes sense. Thanks for your help! Jans
