### ISSUE TITLE
__call__() got an unexpected keyword argument 'parse' error in spaCy

### ISSUE THREAD

**Issue by jonanem** [explosion/spaCy#2178]
nlp = spacy.load('en')
doc = nlp(text, parse = True)

for sent in doc.sents:
    print('> ', sent)

Getting error as below
TypeError                                 Traceback (most recent call last)
<ipython-input-79-6aa1288b7abf> in <module>()
      1 nlp = spacy.load('en')
----> 2 doc = nlp(text, parse = True)
      3 
      4 for sent in doc.sents:
      5     print('> ', sent)

TypeError: __call__() got an unexpected keyword argument 'parse'

## Your Environment

 spaCy version      2.0.10
   
   Platform           Windows-10-10.0.16299-SP0
    Python version     3.6.4
    Models             en

**Comment by ines** [comment]
What exactly are you trying to do, and where is this code snippet from? There's indeed no keyword argument `parse` on the `nlp` object (i.e. the `Language` class). When you call `nlp` on a string of text, spaCy will call all [pipeline components](https://spacy.io/usage/processing-pipelines) in order – so if you've loaded in a model that includes weights for the parser, this means that the document will also be parsed. So you can simply do:

```python
nlp = spacy.load('en')
doc = nlp(text)
```

If you want to *disable* the parser (or any other pipeline component), you can use the `disable` keyword argument on the `nlp` object or in `spacy.load` (to not even load the component at all). For example:

```python
nlp = spacy.load('en', disable=['ner'])
doc = nlp(u"I don't want parsed", disable=['parser'])
```

**Comment by jonanem** [comment]
Thanks for your response. I am trying for sentence splitting. Here is the link for the code snippet.
https://github.com/ceteri/a41124835ed0/blob/master/ex03.ipynb

Without passing parse it is working but I am still wondering why they have passed parse in the above note book

**Comment by ines** [comment]
Thanks for the quick reply – and hmm, it's possible that code in the notebook is quite old? I think spaCy versions *before* v1.x allowed this keyword argument – but if I remember correctly, it was already deprecated in v1.x (but maybe spaCy just didn't complain like it does now).
