### ISSUE TITLE
ner/cfg has wrong extra_labels

### ISSUE THREAD

**Issue by damianoporta** [explosion/spaCy#2179]
Hello,
this is my ner/cfg:

```
{
  "token_vector_width":128,
  "nr_class":5,
  "pretrained_dims":0,
  "beam_density":0.0,
  "cnn_maxout_pieces":3,
  "beam_width":1,
  "hidden_width":200,
  "maxout_pieces":2,
  "hist_width":0,
  "extra_labels":[
    "CITIZENSHIP",
    "CITIZENSHIP",
    "CITIZENSHIP",
    "CITIZENSHIP"
  ],
  "hist_size":0,
  "hidden_depth":1
}
```
i have created this model with this code:
```
damiano@damiano:~$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> nlp = spacy.blank('it')
>>> ner = nlp.create_pipe('ner')
>>> ner.add_label('CITIZENSHIP')
>>> nlp.add_pipe(ner)
>>> nlp.begin_training()
<thinc.neural.optimizers.Optimizer object at 0x7fcbed774cc0>
>>> nlp.to_disk('/home/damiano/ner')

```
as you can see i did not do anything special. Why my custom entity is repeated three times?

## Your Environment
    Info about spaCy

    Python version     3.5.2          
    Models                            
    Platform           Linux-4.13.0-37-generic-x86_64-with-Ubuntu-16.04-xenial
    spaCy version      2.0.10         
    Location           /home/damiano/.local/lib/python3.5/site-packages/spacy

**Comment by thomas-dorrington** [comment]
I'm seeing the same thing @damianoporta. Any updates?

**Comment by honnibal** [comment]
Should now be fixed in the latest `spacy-nightly`. Thanks for your help reporting.
