### ISSUE TITLE
html5lib==1.0b8 is required in the 2.0.10 release but not in git repository

### ISSUE THREAD

**Issue by romanczuk** [explosion/spaCy#2181]
It looks like the problem in https://github.com/explosion/spaCy/issues/2100 wasn't resolved in 2.0.10.

As @raphael0202 said, the html5lib requirement was dropped in https://github.com/explosion/spaCy/commit/6bba1db4cc41ef22bcba14046b498572019fba3e#diff-b4ef698db8ca845e5845c4618278f29a but still appears here: https://github.com/explosion/spaCy/blob/v2.0.10/setup.py

This requirement isn't compatible with Tensorflow 1.7.0.

## Your Environment
* **spaCy version:** 2.0.10
* **Platform:** Linux-4.9.49-moby-x86_64-with-debian-8.10
* **Python version:** 3.6.4
* **Models:** en_core_web_lg, en_core_web_md

**Comment by ines** [comment]
Yes, as mentioned in my comment in #2100, we initially planned to only drop it in `v2.1.0` (i.e. the next minor version).

However, our tests went well and we've already removed the dependency from the version on master (including a few other ones that were barely needed). We're just preparing spaCy `v2.0.11`, which will include the fix and will drop `html5lib`, `six`, `ftfy` and `requests` 👍
