### ISSUE TITLE
Getting an error when training a new text classifier - gold = GoldParse(doc, **gold)

### ISSUE THREAD

**Issue by sublimotion** [explosion/spaCy#2182]
I am trying to train a custom dataset from Kaggle after successfully stepping through the spacy training example for the IMDB dataset for a text classifier.
https://raw.githubusercontent.com/explosion/spaCy/master/examples/training/train_textcat.py

I am however getting an error when performing the training. My custom training dataset can be downloaded from here: https://www.kaggle.com/nicapotato/womens-ecommerce-clothing-reviews/data

Here is the code that I altered.
```python
#train_data, _ = thinc.extra.datasets.imdb()
#Custom dataset
df = pd.read_csv("~/notebooks/data/ecom_reviews.csv")
train_data = df.apply(lambda row: (row['Review Text'],row['Recommended IND']), axis=1).tolist()
#End custom dataset
```

It seems to me that the train_data is exactly the same shape and yet I am getting an error when switching to my custom dataset compared to the imdb dataset.

Here is the full error.
=====================================================

```
Training the model...
LOSS 	  P  	  R  	  F  
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-2bef4fe1e613> in <module>()
     12                 texts, annotations = zip(*batch)
     13                 nlp.update(texts, annotations, sgd=optimizer, drop=0.2,
---> 14                            losses=losses)
     15             with textcat.model.use_params(optimizer.averages):
     16                 # evaluate on the dev data split off in load_data()

~/anaconda2/envs/ipykernel_py3/lib/python3.6/site-packages/spacy/language.py in update(self, docs, golds, drop, sgd, losses)
    397                 doc = self.make_doc(doc)
    398             if not isinstance(gold, GoldParse):
--> 399                 gold = GoldParse(doc, **gold)
    400             doc_objs.append(doc)
    401             gold_objs.append(gold)

gold.pyx in spacy.gold.GoldParse.__init__()

TypeError: 'float' object is not iterable
============================================================================
```

## Info about spaCy

* **spaCy version:** 2.0.9
* **Platform:** Linux-4.4.0-21-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.3
* **Models:** en

**Comment by ines** [comment]
From the error, it does look like it might come down to a small difference in how your `annotations` are structured. Could you add a print statement and check how an annotation looks? It should be something like:

```python
{'cats': {'POSITIVE': 0.1234}}
```

The way the IMDB data is loaded and converted in the example isn't ideal – at least, I find the [`load_data` function](https://github.com/explosion/spaCy/blob/a350be0601113d6f2e1b07a7d40ab5e384a101f6/examples/training/train_textcat.py#L95) a little hacky. So depending on how the dataset is structured, you might prefer to just write your own converter function. All you need is a list of texts and a list of categories (like my example above) – one training set and one development set.

(Btw, the dataset looks interesting, so definitely keep us updated on your results!)

**Comment by sublimotion** [comment]
I have added this print statement in the batch loop.

The weird thing is I don't see any differences in the annotations format between the IMDB and the Kaggle dataset, but yet the IMDB works just fine.

for batch in batches:
            texts, annotations = zip(*batch)
            print(annotations)

Here is the output for the IMDB dataset.

Loaded model 'en'
Loading IMDB data...
Using 2000 examples (1600 training, 400 evaluation)
Training the model...
LOSS 	  P  	  R  	  F  
({'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}})
({'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': True}})
({'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}})
({'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}})
({'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': False}})
({'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': False}})
({'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': True}})
({'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': True}})
({'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': False}})
({'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': True}})
({'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}})
({'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': False}})
({'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': True}})
({'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}})
({'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': False}})
({'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': False}})
({'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': False}})
({'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': False}})
({'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}})
({'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': True}})

and here is the output from the Kaggle dataset.

Loaded model 'en'
Loading ecom data...
Using 2000 examples (1600 training, 400 evaluation)
Training the model...
LOSS 	  P  	  R  	  F  
({'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}})
({'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': True}})
({'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}})
({'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': False}})
({'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': True}})
({'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': False}})
({'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': False}})
({'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}})
({'cats': {'POSITIVE': False}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}}, {'cats': {'POSITIVE': True}})

**Comment by sublimotion** [comment]
My bad the data needed to be cleansed.

After dropping the null values I did not run into any issues.

I am pretty happy with the results. This model classifies the review if it has been recommended or not. It can then be used in turn to predict which review is most likely to be recommended.

Training the model...
LOSS 	  P  	  R  	  F  
52.900	0.839	0.991	0.909
34.806	0.870	0.964	0.914
23.225	0.895	0.946	0.919
15.268	0.905	0.943	0.923
10.861	0.898	0.931	0.914
8.093	0.905	0.943	0.923
7.451	0.906	0.934	0.920
4.859	0.906	0.934	0.920
4.395	0.906	0.934	0.920
3.798	0.913	0.919	0.916
2.978	0.911	0.928	0.919
2.894	0.912	0.937	0.924
2.514	0.906	0.925	0.915
2.595	0.901	0.931	0.916
1.843	0.901	0.931	0.916
2.508	0.902	0.919	0.910
1.950	0.905	0.916	0.910
1.544	0.905	0.916	0.910
1.742	0.904	0.934	0.919
1.895	0.893	0.934	0.913

**Comment by ines** [comment]
@sublimotion Thanks a lot for updating with the solution – looks good! 👍 If you're sharing your results on Kaggle, let us know – I think this is a nice example that others from the spaCy community would find very valuable, too.
