### ISSUE TITLE
NER training in command line, the final model send everything back as an entities.

### ISSUE THREAD

**Issue by KMohaghegh** [explosion/spaCy#2185]
Hi guys and thanks for your fantastic job, I have a problem regarding the NER training via command line which I will explain in the following. I train the NER with new entities in command line exact the same as explained in spaCy document. I am only interested to trained the NER. Both the training and the dev input are json format (as they should be).

The command I use is as follows:

 **python -m spacy train en ../Desktop/Spacy/Model-Train ../Desktop/Spacy/242018/gutenberg_devu.txt.json  ../Desktop/242018/gutenbergu.txt.json -n 20 
-P -T**

the out put is:
dropout_from = 0.2 by default
dropout_to = 0.2 by default
dropout_decay = 0.0 by default
batch_from = 1 by default
batch_to = 16 by default
batch_compound = 1.001 by default
max_doc_len = 5000 by default
beam_width = 1 by default
beam_density = 0.0 by default
learn_rate = 0.001 by default
optimizer_B1 = 0.9 by default
optimizer_B2 = 0.999 by default
optimizer_eps = 1e-08 by default
L2_penalty = 1e-06 by default
grad_norm_clip = 1.0 by default
parser_hidden_depth = 1 by default
parser_maxout_pieces = 2 by default
token_vector_width = 128 by default
hidden_width = 200 by default
embed_size = 7000 by default
history_feats = 0 by default
history_width = 0 by default
Itn.	P.Loss	N.Loss	UAS	NER P.	NER R.	NER F.	Tag %	Token %
0       0.000   0.000   0.000   1.913   20.379  3.498   0.000   100.000 17850.40.0
1       0.000   0.000   0.000   1.692   6.833   2.712   0.000   100.000 18645.00.0
2       0.000   0.000   0.000   2.290   17.970  4.063   0.000   100.000 17854.40.0
3       0.000   0.000   0.000   1.708   19.550  3.141   0.000   100.000 18009.60.0
4       0.000   0.000   0.000   0.902   11.493  1.672   0.000   100.000 14274.50.0
5       0.000   0.000   0.000   1.772   15.679  3.183   0.000   100.000 14633.40.0
6       0.000   0.000   0.000   2.617   42.299  4.930   0.000   100.000 15909.50.0
7       0.000   0.000   0.000   1.394   2.686   1.835   0.000   100.000 17427.70.0
8       0.000   0.000   0.000   1.308   4.502   2.027   0.000   100.000 16058.40.0
9       0.000   0.000   0.000   2.867   10.821  4.533   0.000   100.000 12611.60.0
10      0.000   0.000   0.000   0.904   4.502   1.506   0.000   100.000 17244.90.0
11      0.000   0.000   0.000   1.023   9.400   1.846   0.000   100.000 16253.10.0
12      0.000   0.000   0.000   2.470   25.592  4.506   0.000   100.000 18050.80.0
13      0.000   0.000   0.000   0.935   3.476   1.473   0.000   100.000 17420.50.0
14      0.000   0.000   0.000   1.372   6.714   2.279   0.000   100.000 16866.80.0
15      0.000   0.000   0.000   1.786   14.100  3.170   0.000   100.000 15634.50.0
16      0.000   0.000   0.000   2.234   13.981  3.852   0.000   100.000 17915.30.0
17      0.000   0.000   0.000   0.693   3.081   1.131   0.000   100.000 17383.00.0
18      0.000   0.000   0.000   1.540   3.002   2.036   0.000   100.000 18024.50.0
19      0.000   0.000   0.000   2.552   27.567  4.672   0.000   100.000 17402.80.0
Saving model...

but when I  load the final model is terrible and send me back every token in the text file is an entities. 
If some one had experience something similar or just have a quick look and find it out where is my problem, it is really appreciated. 

Just add if I run the  code in "Training the named entity recognizer" mentioned in documentation and create a model (train a new type entity orating to existing one) everything is fine and the model works totally fine, as several times mentioned on other tickets, that one do not fit huge data set and easily crashed when the number of tokens in training data is more than few hundred thousands. So the command line above do not crash with large training data but has a very strange behaviour! 

A part of the results is like this:

NAME crisis with the
NAME positions
NAME . therefore
NAME in portfolios
NAME .
NAME portfolios are
**everything is entity (even the punctuation)!!!**

Additional if someone explain what are these abbreviation in the output it also helps a lot:
P.Loss	N.Loss	UAS	NER P.	NER R.	NER F.	Tag %	Token %
**(take a look at output and all the first three columns are zero, Is it normal? )**

I run python 2.7.10 
on Mac with 
Spacy 2.0.9

Thanks in advance for your help.

**Comment by KarthikPunyamurthy** [comment]
I have been working on the same thing. but when i load the model-final there are no entities fetched and also all the columns of losses correspond to 0 except for the N.loss , would appreciate a solution for this problem for CLI train command 

Thanks

**Comment by honnibal** [comment]
[aij-wikiner-wp3-es-dev-iob.zip](https://github.com/explosion/spaCy/files/1886303/aij-wikiner-wp3-es-dev-iob.zip)

I'm pretty sure something's gone wrong with your pre-processing, and your data file is not correct. I've attached an IOB format data file that's likely to be easier to produce. Let's say you extract the file to your /tmp directory. Here's an example command that converts it:

```python
unzip /tmp/aij-wikiner-wp3-es-dev-iob.zip
python -m spacy convert aij-wikiner-wp3-es-dev-iob.zip
spacy convert /tmp/aij-wikiner-wp3-es-dev-iob.iob /tmp
```
This should give you a file `/tmp/aij-wikiner-wp3-es-dev-iob.json` , which should be correctly formatted for spaCy. You should then have a look at the .iob file, and try to get your data to match its format.


> P.Loss	N.Loss	UAS	NER P.	NER R.	NER F.	Tag %	Token %

* Parser loss (irrelevant for you)
* NER loss (important -- no should not be 0)
* Unlabelled attachment score for parser (irrelevant for you)
* NER Precision on development data
* NER recall on development data
* NER F on development data
* Tag accuracy on development data (irrelevant for you?)
* Tokenization accuracy on development data (irrelevant if you use the .iob format, which prevents you from learning from incorrectly tokenized text)

**Comment by honnibal** [comment]
> And the use of hyper_parameters from the CLI is difficult, can we directly change it in the script of train.py

The hyper-parameters are currently set via the environment variables because passing the configuration through to the arbitrary places they have to be read is difficult, and there's constantly new hyper-parameters to expose.

You could try writing to the `os.environ` dictionary? It's messy but I think it should work.

**Comment by KarthikPunyamurthy** [comment]
@honnibal Thank you for the reply, 
I checked the json file as per your guidelines and it looks perfect.  

And i also updated my spacy to 2.0.11 and it is giving the following error for the correct json file (conll_ner2json.py is the converter i used for converting the conll file):

C:\Users\karth>python -m spacy train en "C:\Users\karth\AppData\Local\Programs\Python\Python35\Lib\site-packages\law_md2" "E:\Office files\Python\Output\train.json" "E:\Office files\Python\Output\dev.json" -n 10 -P -T
dropout_from = 0.2 by default
dropout_to = 0.2 by default
dropout_decay = 0.0 by default
batch_from = 1 by default
batch_to = 16 by default
batch_compound = 1.001 by default
max_doc_len = 5000 by default
beam_width = 1 by default
beam_density = 0.0 by default
Warning: Unnamed vectors -- this won't allow multiple vectors models to be loaded. (Shape: (0, 0))
learn_rate = 0.001 by default
optimizer_B1 = 0.9 by default
optimizer_B2 = 0.999 by default
optimizer_eps = 1e-08 by default
L2_penalty = 1e-06 by default
grad_norm_clip = 1.0 by default
parser_hidden_depth = 1 by default
parser_maxout_pieces = 2 by default
token_vector_width = 128 by default
hidden_width = 200 by default
embed_size = 7000 by default
history_feats = 0 by default
history_width = 0 by default
Itn.    P.Loss  N.Loss  UAS     NER P.  NER R.  NER F.  Tag %   Token %
Saving model...
Traceback (most recent call last):
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\site-packages\spacy\__main__.py", line 31, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\site-packages\spacy\cli\train.py", line 133, in train
    drop=next(dropout_rates), losses=losses)
  File "C:\Users\karth\AppData\Local\Programs\Python\Python35\lib\site-packages\spacy\language.py", line 427, in update
    proc.update(docs, golds, drop=drop, sgd=get_grads, losses=losses)
  File "nn_parser.pyx", line 564, in spacy.syntax.nn_parser.Parser.update
  File "nn_parser.pyx", line 684, in spacy.syntax.nn_parser.Parser._init_gold_batch
  File "transition_system.pyx", line 76, in spacy.syntax.transition_system.TransitionSystem.get_oracle_sequence
  File "transition_system.pyx", line 131, in spacy.syntax.transition_system.TransitionSystem.set_costs
ValueError: [E024] Could not find an optimal move to supervise the parser. Usually, this means the GoldParse was not correct. For example, are all labels added to the model?

**Comment by KMohaghegh** [comment]
Thanks honnibal, your comment was very helpful and I mange to train the model. Now it works normal and not sending everything back as an entity. It was a problem in my json file.
Thanks a lot
