### ISSUE TITLE
attribute "orth_" remove whitespace from multiword string

### ISSUE THREAD

**Issue by lizisepul** [explosion/spaCy#2187]
I used spacy matcher to identify a list of terms in texts. Then, I used spacy doc object to represent each term included in the term list. When the term was only 1 word is everything ok, but if the term is multiword the matcher failed.  

Example: term = polar ice

If I use the following attribute to obtain the text:  term.text.lower(), I obtain the text like it is, but If I use
term.orth_.lower() the whitespace are removed and all the words appear together.

Following spacy documentation, there aren´t differences between "orth_" and "text", but in the doc appears "orth_=polarice" and "text=polar ice".

Any suggestions?
Thanks

## Your Environment
* Operating System: macOS
* Python Version Used: 3.6.2
* spaCy Version Used: 2.0.0rc2
* spaCy models Used: en_core_web_md

**Comment by ines** [comment]
How are you creating your `Doc` objects? Are you doing this manually? And if so, could you share an example of your code?

One explanation could be that the `spaces` keyword argument on the `Doc` is set incorrectly. This should be a list of boolean values specifying whether the token is followed by a space or not (e.g. two words vs. a word plus a period). Consider the following example:

```python
doc = Doc(vocab, words=['polar', 'ice'], spaces=[False, False])
print(doc.text, [t.orth_ for t in doc], [t.text for t in doc], [t.text_with_ws for t in doc])
#    'polarice'    ['polar', 'ice']        ['polar', 'ice']        ['polar', 'ice']
```

The `doc.text` consists of all tokens plus their respective whitespace, i.e. `token.text_with_ws`. So if you set the spaces to `[True, False]`, the whitespace is preserved correctly:

```python
doc = Doc(vocab, words=['polar', 'ice'], spaces=[True, False])
print(doc.text, [t.orth_ for t in doc], [t.text for t in doc], [t.text_with_ws for t in doc])
#    'polar ice'    ['polar', 'ice']        ['polar', 'ice']        ['polar ', 'ice']
```

Alternatively, if your terms are stored in plain text, you could also just use spaCy's tokenizer to create the `Doc` objects for you. This way, the whitespace should always be preserved correctly.

```python
from spacy.lang.en import English

nlp = English()
terms = ('polar ice', 'polar bear')
docs = [nlp(term) for term in terms]    
```

Btw, off-topic, but I just noticed your spaCy version is `2.0.0rc2` (i.e. an old release candidate based on the alpha version). If you're able to upgrade, I'd definitely recommend using the latest stable `v2.0.x` instead.

**Comment by lizisepul** [comment]
Hi Ines,

Thanks for you quickly answer. I share with you the code I use to create a doc for each term. As you can check we create a doc using a spaCy's tokenizer, then I think the problem it is not related to the spaces parameter. 

> nlp = spacy.load('en_core_web_md', disable=[])
> term = 'polar ice'
> doc = nlp(term)

After creating a doc, I use the tokenized string to build some patterns using the following lines.

>tokens = [x.orth_ for x in doc]
>print(tokens) --> ['polar', 'ice']

>patttern_1 = [{LOWER: x.lower()} for x in tokens]
>print(patttern_1) --> [{66: 'polar'}, {66: 'ice'}]
>pattern_2 = [{ORTH: x} for x in tokens]
>print(patttern_2) --> [{66: 'polar'}, {66: 'ice'}]

I'm checking if there is some error in a doc or patterns creation, but I think is everything ok. 

Question 1: When I create a doc, the orth_ attribute doesn't appear, while I can see other attributes like text and text_with_ws. How can I access orth_ attribute? The orth_ attribute appears after applying a matcher and joint all the words (polarice)

Question 2: When I debug my code using Pycharm, I inspect the doc object and I see several doc objects one inside another. Is this correct?

Thanks!

**Comment by ines** [comment]
Ah okay – if you're using spaCy to create the patterns, then just use the `doc.text` if you want to see the full document's text *with* whitespace, `token.text` if you need the individual tokens *without* whitespace, and `token.text_with_ws` if you need the individual tokens *with* whitespace.

So a pattern with two tokens `'polar'` and `'ice'` should definitely match the same tokens that appear in a document. Here's a full working example:

```python
import spacy
from spacy.matcher import Matcher

nlp = spacy.load('en')
matcher = Matcher(nlp.vocab)
matcher.add('PATTERN', None, [{'LOWER': 'polar'}, {'LOWER': 'ice'}])

doc = nlp(u"Polar ice. POLAR ICE.")
matches = matcher(doc)
for match_id, start, end in matches:
    span = doc[start:end]
    print(span.text)

# Polar ice
# POLAR ICE
```

> Question 1: When I create a doc, the orth_ attribute doesn't appear, while I can see other attributes like text and text_with_ws.

The `Doc` object doesn't have an `orth_` attribute, because it doesn't have an ID to represent its full text, either. Its text, available via `Doc.text`, consists of the individual tokens' `text_with_ws_`. (In general, the `orth_` attribute only exists for consistency with the other attributes, and should always be identical to `text`.)

> Question 2: When I debug my code using Pycharm, I inspect the doc object and I see several doc objects one inside another. Is this correct?

That's interesting – could you show an example?

**Comment by ines** [comment]
Thanks for updating – I'm glad I was able to help! 😃
