### ISSUE TITLE
Bug when running tests: no module named 'mock'

### ISSUE THREAD

**Issue by stephsamson** [explosion/spaCy#2191]
## Your Environment

* **Operating System**: macOS Sierra, Version 10.12.6
* **spaCy version:** 2.0.11
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **Python version:** 3.6.5
* **Environment Information**: Using `pipenv` to install spaCy.

## Error Reproduction
- `pipenv install spacy pytest`
- `python -c "import os; import spacy; print(os.path.dirname(spacy.__file__))"`
- `python -m pytest <spacy_path>`

## Error Thrown
```
ImportError while importing test module '/Users/stephsamson/.local/share/virtualenvs/spacymoji-RG7T2FJk/lib/python3.6/site-packages/spacy/tests/test_underscore.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../.local/share/virtualenvs/spacymoji-RG7T2FJk/lib/python3.6/site-packages/spacy/tests/test_underscore.py:5: in <module>
    from mock import Mock
E   ModuleNotFoundError: No module named 'mock'
```

**Comment by ines** [comment]
Thanks for the report!

The test-related and dev requirements are listed in the `requirements.txt`, so if you didn't build spaCy from source, you'll need to make sure to install those, too:

```bash
pip install -r path/to/requirements.txt
```

I just noticed that this is currently missing from the docs in the `README`, so I will fix this. Sorry about that. The [testing docs on the website](https://spacy.io/usage/#tests) are a little more detailed now and mention this.
