### ISSUE TITLE
Return the results of the info call and don't just print it

### ISSUE THREAD

**Issue by transfluxus** [explosion/spaCy#2196]
feature request:
I want to deliver spacy/model infos to a front end. the cli.info method just prints them.

Very simple. I can make a pull request if you tell me the branch :)

**Comment by ines** [comment]
Sure, that's a good idea! You can find the source of the command in [`spacy/cli/info.py`](https://github.com/explosion/spaCy/blob/master/spacy/cli/info.py). A pull request to master is fine!

**Comment by ines** [comment]
Just came across this issue and added a quick fix to `cli.info`. The update will then be included in the next release!
