### ISSUE TITLE
Kernel died, restarting on training spaCy NER model

### ISSUE THREAD

**Issue by manishprasadthapliyal** [explosion/spaCy#2199]
i am getting following error whenever i am training the model.
> Kernel died, restarting

kernel is restarting in this line. Inside a loop.
`self._nlp.update([text],[annotations],drop=float(dropout),sgd=optimizer,losses=losses)`

occasionally it works and train successfully but most of the times it is restarting the kernel
when i individually run the failed text it passes but training fails most of the time
any help will be appreciated
## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.6.5
* spaCy Version Used: 2.0.10
* Environment Information: Anaconda

**Comment by manishprasadthapliyal** [comment]
I used minibatch from spacy.util it helped but on large data i have to increase the batch size. On increasing the batch size accuracy and other metrics are coming as 0.0 and even with increased batch size as 252 the kernel is dying and restarting

**Comment by ameyn21** [comment]
I am getting a similar issue while training the model.

**Comment by honnibal** [comment]
I believe you're running out of memory, and need to set a smaller batch size for your data.

**Comment by lexNeurii** [comment]
I have reduced batch size 10. I have a training data of 1500. Using SpaCy for NER in paragraphs.

**Comment by lexNeurii** [comment]
I have reduced the batch size to 10. Have about 1000 training data. using SpaCy to NER some paragraphs.

**Comment by manishprasadthapliyal** [comment]
Using mini-batch helped me run the code without error

**Comment by gmanav91** [comment]
I am using the following code.

for itn in range(250):
           print("Statring iteration " + str(itn))
           #random.shuffle(TRAIN_DATA)
           #batch_data = TRAIN_DATA[0:5]
           batch_data = minibatch(TRAIN_DATA, size=3)
           losses = {}

There is no error as long as random.shuffle(TRAIN_DATA) is not executed. 

When I uncomment and execute "random.shuffle(TRAIN_DATA)", I receive the error "Kernel died, restarting" after a few iterations.

**Comment by CYUlysses** [comment]
I had to reduce my batch size to 3 to reduce the "crash chance" to below 1 out of every 10 iterations. Would be helpful if spaCy can throw an Exception instead of just crashing the kernel.
