### ISSUE TITLE
Typo in CLI for Packaging prevents creating meta

### ISSUE THREAD

**Issue by KevinJ90825** [explosion/spaCy#2200]
This just seems like a typo in the CLI from the new system for error messages and warnings. [This line ](https://github.com/explosion/spaCy/blob/master/spacy/cli/package.py#L97) should have a title of `Messages.M046`.

Right now it throws an error because Messages.Mo46 isn't defined.

**Comment by ines** [comment]
Arghhhhhh 🤦‍♀️ Sorry about that. Would you mind submitting a quick PR for this?

We should also run some clever search / linting to make sure there aren't any other typos like this anywhere that aren't caught by our tests or flake8 sanity checks (which only check for undefined names, not invalid class attributes).
