### ISSUE TITLE
NER does not recognise some simple names. 

### ISSUE THREAD

**Issue by ajayrfhp** [explosion/spaCy#2202]
## Info about spaCy

* **Models:** en_core_web_lg, en_core_web_md
* **Python version:** 3.5.2
* **spaCy version:** 2.0.7
* **Platform:** Linux-4.4.0-1054-aws-x86_64-with-Ubuntu-16.04-xenial

```
nlp_md = spacy.load('en_core_web_md')
nlp_lg = spacy.load('en_core_web_lg')
get_entities_spacy(nlp_md, "I am Alex") # => returns {}
get_entities_spacy(nlp_lg, "I am Alex") # => returns {}
```

**Comment by ines** [comment]
Sorry for only getting to this now. It's not 100% clear from your code what `get_entities_spacy` does, but I assume it calls the `nlp` on the text returns some reformatted version of `doc.ents`?

It's true that this construction is quite simple, so it'd be nice if the models recognised the `PERSON` entity here. However, models are statistical, the texts are very short and it's possible that similar examples weren't very common in the training data. If sentences like this are relevant to your application, you can always update the model with more examples: https://spacy.io/usage/training#section-ner

You could also use the [rule-based `Matcher`](https://spacy.io/usage/linguistic-features#section-rule-based-matching) to bootstrap similar examples, if you have a large corpus of text. For example, a pattern like `[{'ORTH': 'I'}, {'ORTH': 'am'}, {'IS_TITLE': True}]` could be a good start.
