### ISSUE TITLE
NER Retraining is forgetting old entities. 

### ISSUE THREAD

**Issue by ajayrfhp** [explosion/spaCy#2204]
## Info about spaCy

* **Models:** en_core_web_lg, en_core_web_md
* **Python version:** 3.5.2
* **spaCy version:** 2.0.7
* **Platform:** Linux-4.4.0-1054-aws-x86_64-with-Ubuntu-16.04-xenial

I wanted to improve the name recognition part, I trained with 5000 names. 

```
optimizer = nlp_lg.begin_training()
for i in range(1):
    losses = {}
    for i, name in enumerate(names):
        sentence, entities = get_sentence_and_entities(name)
        nlp_lg.update([sentence], [entities], drop = 0.7)
        if i % 100 == 0:
            print(i, len(names))
```

```
'My name is Annette. I have 300$ with me' # returns 300 is Person and Annette is Person. 
```

**Comment by ines** [comment]
It sounds like what you're experiencing is the "catastrophic forgetting" problem – as your model learns about the new entities, it's "forgetting" what it had previously learned.

Here are some resources and threads with more information and possible solutions:
* https://explosion.ai/blog/pseudo-rehearsal-catastrophic-forgetting
* #1892: Lot of false positives when using the NER model
* #1777: Improve spacy model for MONEY entity recognition 
* #1337: Custom NER model doesn't recognize any entities
* #1382: Predefined entities not detected after adding custom entities

**Comment by aferdoash** [comment]
Issue  #1777 is a bit different
The user first needs to do text normalisation and then NER
