### ISSUE TITLE
Entity Recognizer prediction on GPU

### ISSUE THREAD

**Issue by tahirahmad2030** [explosion/spaCy#2205]
Is there a way by which we can use GPU's to predict the spacy's entity recognizer?
I am currently using pipe which makes it multi threaded and batching. I am looking for using GPU's to gain more performance boost. Can spacy use GPU for prediction?
## Your Environment

* Operating System: Ubuntu
* Python Version Used: 2.7
* spaCy Version Used: 2.0.11
* Environment Information: Ubuntu/Shell

**Comment by kwhumphreys** [comment]
timings from a p2.xlarge EC2 machine (Tesla K80 GPU)

**Comment by honnibal** [comment]
Before loading the model, you should now be able to do:

```python

import spacy
spacy.prefer_gpu()
nlp = spacy.load('en_core_web_md')
```

There's another function, `spacy.require_gpu()`, which should raise an error if the GPU is unavailable.
