### ISSUE TITLE
Entity Recognizer classification report

### ISSUE THREAD

**Issue by tahirahmad2030** [explosion/spaCy#2206]
I want to generate classification report for each class separately for NER. Something like classification_report of Sklearn. I am currently using spacy's evaluate method to get precision, recall and f-score however its average of all classes combined. Can we have classification report for each class?

## Your Environment

* Operating System: Ubuntu
* Python Version Used: 2.7
* spaCy Version Used: 2.0.11
* Environment Information: shell

**Comment by ines** [comment]
spaCy doesn't have a built-in method for that – but you should be able to implement your own that counts the individual entity types (and calculates everything else you want to include in your report).

For details, see the implementation of the `Scorer` in [`scorer.py`](https://github.com/explosion/spaCy/blob/49cee4af9284f72eb19588f36f75888209710074/spacy/scorer.py#L87), specifically `Scorer.score`.
