### ISSUE TITLE
ssl module not available when trying to pip install 

### ISSUE THREAD

**Issue by EmillerOpenwhere** [explosion/spaCy#2208]
Hey I am getting the following errors when trying to install spacy in a new virtualenv. It is hard to tell if this is an issue with your guys' ssl certificate or something local to me. I've seen earlier that your ssl certificates have expired. Could that be it?

```
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting spacy
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/spacy/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/spacy/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/spacy/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/spacy/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/spacy/
  Could not fetch URL https://pypi.python.org/simple/spacy/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/spacy/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)) - skipping
```

**Comment by mdcclv** [comment]
This seems like a pypi issue related to recent changes in their infrastructure — see http://pyfound.blogspot.com/2018/03/warehouse-all-new-pypi-is-now-in-beta.html
and try `pip install --upgrade pip` or see that page's suggestion of 
`curl https://bootstrap.pypa.io/get-pip.py | python`

**Comment by ines** [comment]
Yes, this seems like the best explanation!

I can definitely confirm that when you install spaCy, no requests are made to any of our servers. In fact, as of v1.7.0, all spaCy models are hosted [on GitHub](https://github.com/explosion/spacy-models) and will be served from there.

**Comment by EmillerOpenwhere** [comment]
I fixed this. It was a local issue. python 3.6.5 does not install ssl credentials. You need to do that yourself.   You guys do great work. Sorry for thinking it was something on your end.
