### ISSUE TITLE
doc.noun_chunks not working as expected for spanish models

### ISSUE THREAD

**Issue by arequejo** [explosion/spaCy#2210]
This issue is occurring with both spanish models, the following error happens when trying to iterate over the the noun_chunks of a doc:

`Traceback (most recent call last):
  File "playground.py", line 10, in <module>
    for nc in doc.noun_chunks:
  File "doc.pyx", line 503, in __get__
  File "/usr/local/lib/python2.7/site-packages/spacy/lang/es/syntax_iterators.py", line 19, in noun_chunks
    left, right = noun_bounds(token)
  File "/usr/local/lib/python2.7/site-packages/spacy/lang/es/syntax_iterators.py", line 39, in noun_bounds
    if token.dep in np_left_deps:
NameError: global name 'np_left_deps' is not defined`

The same code works by using an english model and sentence instead of a spanish one.

## Your Environment
* **Python version:** 2.7.14
* **Platform:** Darwin-17.5.0-x86_64-i386-64bit
* **spaCy version:** 2.0.11
* **Models:** es_core_news_md, en_core_web_sm, es_core_news_sm

**Comment by ines** [comment]
Thanks for the report – looks like this might be a bug/typo in `lang/es/syntax_iterators.py`. Will look into this!

**Comment by oscartorres** [comment]
same issue here.

**Comment by ct1** [comment]
I have the same issue. What should I do to solve it?
