### ISSUE TITLE
Typos in CONTRIBUTING.md

### ISSUE THREAD

**Issue by jonahweissman** [explosion/spaCy#2223]
I think it should say "include it with your pull request, or submit it separately"
https://github.com/explosion/spaCy/blob/a5ea0fdf5a9656525dd8d78b7d6979538727a776/CONTRIBUTING.md#contributor-agreement

And it should say "replacement functions are suffixed with an underscore"
https://github.com/explosion/spaCy/blob/a5ea0fdf5a9656525dd8d78b7d6979538727a776/CONTRIBUTING.md#python-conventions

Hope that's helpful!

**Comment by skrcode** [comment]
Thanks @jonahweissman !
