### ISSUE TITLE
spaCy similiarty does not work properly on Jupyter

### ISSUE THREAD

**Issue by hadils** [explosion/spaCy#2225]
## Your Environment

* Operating System: Mac OS X 10.13.4
* Python Version Used:  3.6.3
* spaCy Version Used:  2.10
* Environment Information: 
IPython 6.3.1
```Info about spaCy

    spaCy version      2.0.10         
    Location           /Users/hadilsabbagh/anaconda3/lib/python3.6/site-packages/spacy
    Platform           Darwin-17.5.0-x86_64-i386-64bit
    Python version     3.6.3          
    Models             en_core_web_lg, en
```

I  tested the example code for token similarity in Jupyter:
```tokens = nlp(u'dog cat banana')

for token1 in tokens:
    for token2 in tokens:
        print(token1.similarity(token2))
```

and got these results:
```1.0
2.30727e-21
-7.82874e+17
2.30727e-21
1.0
-8.24222e+17
0.0
-0.0446812
1.0
```

**Comment by ines** [comment]
Sorry about the late reply – looks like this is related to #2132 (a problem with a numpy version that produced weird similarity results like this on OSX). Upgrading to `numpy >= 1.14` or the latest version of spaCy that pins to this version should fix the problem!

**Comment by WildandArt** [comment]
I have the same problem, and I have upgraded numpy to 1.14 as you suggested, but the results stayed the same

**Comment by WildandArt** [comment]
Eventually I did " condo update --all" , many packages were updated and now the results are correct:
tokens = nlp(u'dog cat banana')


for token1 in tokens:
    for token2 in tokens:
        print(token1.text, token2.text, token1.similarity(token2))
output:
dog dog 1.0
dog cat 0.8016855
dog banana 0.24327648
cat dog 0.8016855
cat cat 1.0
cat banana 0.28154367
banana dog 0.24327648
banana cat 0.28154367
banana banana 1.0
