### ISSUE TITLE
Broken tqdm progress bar in built-in train method

### ISSUE THREAD

**Issue by marekmodry** [explosion/spaCy#2231]
The `tqdm` progress bar in `train` method of `spacy.cli.train` does not work correctly when the training dataset contains documents that get filtered out by `max_doc_len` parameter. 

`total` parameter of `tqdm` is set to the total number of tokens in the dataset (including those exceeding `max_doc_len` limit) even though only documents shorter than `max_doc_len` contributes to the updates of the progress bar `pbar`.

This causes the progress bar to stop before reaching 100%.

I am willing to contribute by fixing this.

Can you just help me understand the idea behind `max_doc_len` parameter so I can suggest a solution? Why is it needed? And why it is not applied also on the dev dataset?

Two ideas from the top of my head:
* Move filtering before https://github.com/explosion/spaCy/blob/3141e04822a8c40e0d64e51a040305ade3f66d8c/spacy/cli/train.py#L124 (this way we would also avoid repeating the filtering in each iteration) and set `tqdm`'s `total` to the actual number of tokens after filtering `train_docs`.
* Filter documents when loading the corpus 

Thank you for your suggestions.

## Your Environment
* **spaCy version:** 2.0.9
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **Python version:** 3.6.2
* **Models:** en, en_core_web_lg, en_vectors_web_lg

**Comment by honnibal** [comment]
@marekmodry The `max_doc_len` is no longer needed on the version on develop. The reason we needed it was that the previous alignment code was quite inefficient, and ran in O(n**2) time. I finally got around to fixing this. The faster alignment code will be rolled out in spaCy 2.1.

**Comment by marekmodry** [comment]
Thanks for the clarification and for fixing it. I guess we can close this issue then?
