### ISSUE TITLE
code switching supported by multi-language model (xx_ent_wiki_sm)?

### ISSUE THREAD

**Issue by manishprasadthapliyal** [explosion/spaCy#2234]
I am working own Multi-language Named entity recognition.  I need help with a question that spacy multi-language model supports code switching or not?

## Your Environment

* Operating System: Windows
* Python Version Used: 3.6.5
* spaCy Version Used: 2.0
* Environment Information: anaconda 4.5.0

**Comment by ines** [comment]
The `xx` model is trained on a bunch of different languages but it's unclear whether it will perform well on code switching / mixed inputs. It might, but we haven't specifically tested it for that purpose. It also doesn't include any language-specific data like tokenizer exceptions and only uses the basic language-independent rules shared by all other language classes.

It's still quite experiment, so just try it out on your data and see how it performs. You might also want to try updating it with more examples!
