### ISSUE TITLE
unregister custom extension

### ISSUE THREAD

**Issue by Jean-Zombie** [explosion/spaCy#2242]
Is there a built-in function to unregister a custom extension set with `set_extension`? I manage to update existing extensions with `force=True` but I struggle to remove one altogeher.

 

* **spaCy version:** 2.0.11
* **Platform:** Darwin-17.5.0-x86_64-i386-64bit
* **Python version:** 3.6.2
* **Models:** de

**Comment by honnibal** [comment]
There's a gap in the API here, thanks.
