### ISSUE TITLE
Phrasematcher input for named entity recognition

### ISSUE THREAD

**Issue by barthr** [explosion/spaCy#2245]
## Info about spaCy
* **spaCy version:** 2.0.11
* **Platform:** Darwin-17.5.0-x86_64-i386-64bit
* **Python version:** 3.6.5
* **Models:** en_core_web_lg, nl_core_news_sm, nl

Hi, I trying to do named entity recognition with spacy for the dutch language. Now I need special entities which aren't in the standard entities. It's an extension on locations, I have a large set of all possible locations but not with a context.

My thoughts where to train a phrase matcher to include all those terms and then run it against a big dataset to see what matches it's able to get. Then use that result as input for the NER trainer. Will this be useless or actually add value in terms of matching documents?

Greetings,

Bart

**Comment by ines** [comment]
> My thoughts where to train a phrase matcher to include all those terms and then run it against a big dataset to see what matches it's able to get. Then use that result as input for the NER trainer. Will this be useless or actually add value in terms of matching documents?

Yes, we actually recommend approaches like this a lot, especially if you have a large corpus of text *and* a terminology list. The only thing to keep in mind is that the `PhraseMatcher` will only find exact string matches – but it's very efficient, so you can easily add different spellings (like, both capitalised and lowercase versions of the entities).

You already mentioned that your set of locations is very large, so this might not be relevant here – but you could also try training word vectors on your corpus, and then using those to find more terms similar to the ones on your list. If you merge noun phrases etc. before training the vectors (like [`sense2vec`](https://github.com/explosion/sense2vec)), you can also find multi-word expressions that are used in similar contexts, and then feed those forward to the `PhraseMatcher`, extract the mentions in context and then use those sentences as training data for your entity recognizer.

I actually just gave a talk on this approach for collecting training data, too – you can find the slides [here on GitHub](https://github.com/explosion/talks/blob/master/2018-04_12__Rapid-NLP-Annotation.pdf). (This [tutorial video](https://www.youtube.com/watch?v=l4scwf8KeIA) shows an end-to-end use case of word vectors &rarr; matcher &rarr; NER training data with our tool Prodigy – but you can also build a similar pipeline using spaCy.)

**Comment by barthr** [comment]
Thanks for the response! I've been looking into word vectors aswell to cluster relevant terms and common abbreviations. My use case is twitter data I'm currently researching if it's possible to recognize locations from tweets, but on a high detailed level. So the point of interest are specific street/city/squares/park mentions. I've used a big gazetteer list as input for the `PhraseMatcher`, which worked well but some of the locations were longer than the allowed length for the phrase matcher.

I've seen mordecai, really interesting project but a bit different then my use case. It wasn't perfomant enough for my use case. 

With the noisy nature of tweets POS tagging doesn't seem like a viable solution.  I've watched the talk/read the slides and I liked it. I've send out a request to prodi.gy for a research license, I wan't to try it out and see if I can get some accurate results.

I'm also interested into building this pipeline on my own using spaCy. the `sense2vec` library looks interesting I'm wondering how it compares in results to regular gloVe or word2vec.

**Comment by barthr** [comment]
@ines Is there any detail available on how to train using sense2vec?

**Comment by ines** [comment]
We haven't really had time to update the preprocessing scripts yet – but it's actually not that difficult (the most annoying part is loading the data and parallelizing the whole thing 😜 ).

The `sense2vec` component's `__call__` method includes the respective [transformations to the `Doc`](https://github.com/explosion/sense2vec/blob/702d9a1e10916e656b6c0cd938fc4ffe12eaeb59/sense2vec/__init__.py#L39), e.g. merging noun phrases without determiners, entities etc. The other two relevant functions are the following:

```python
def represent_word(word):
    if word.like_url:
        return '%%URL|X'
    text = re.sub(r'\s', '_', word.text)
    tag = word.ent_type_ or word.pos_ or '?'
    return text + '|' + tag


def represent_doc(doc):
    strings = []
    for sent in doc.sents:
        if sent.text.strip():
            words = ' '.join(represent_word(w) for w in sent if not w.is_space)
            strings.append(words)
    return '\n'.join(strings) + '\n' if strings else ''
```

This is how sense2vec expects the words and documents to be represented. You can then use Gensim to train your own vectors based on the preprocessed text.
