### ISSUE TITLE
Setting custom delimiters for the tokenizer

### ISSUE THREAD

**Issue by scmmmh** [explosion/spaCy#225]
Hello,

Thank you for this great library. I've been using it on a collection of slightly older texts and for the most part it works beautifully. The one problem I've run into is that I regularly have a question-mark/exclamation-mark/full-stop followed by an em-dash (—) in my texts. The em-dash is not separated from the punctuation or the next word by a space, so the tokeniser simply turns the whole word-punctuation-em-word into one big token. To handle this, I updated the "infix.txt" and added the following line:
```
[?.!]?—
```
This now nicely splits the punctuation-em from the words around it, but still has them as a single token. For example
```python
from spacy.en import English
nlp = English()
tokens = nlp('Will this road take me to Puddleton?\u2014No, you\'ll have to walk there.\u2014Ariel.')
print(list(tokens))
```
produces
```
[Will , this , road , take , me , to , Puddleton, ?—, No, , , you, 'll , have , to , walk , there, .—, Ariel, .]
```
I then added the following into the "specials.json":
```json
  "?—": [
    {
      "F": "?"
    },
    {
      "F": "—"
    }
  ],
  "!—": [
    {
      "F": "!"
    },
    {
      "F": "—"
    }
  ],
  ".—": [
    {
      "F": "."
    },
    {
      "F": "—"
    }
  ]
```
However, this has no effect, the output above remains unchanged. I tried adding an entry to the "specials.json" that splits "have" into "ha" and "ve" and that works fine, so I know I'm editing the right file. The one thing I could think of is that the em-dash in the keys of the new rules is somehow messing things up. Any ideas?

**Comment by honnibal** [comment]
Hmm.

Unlike the prefixes and suffixes, when you split a token with the infix.txt, the tokenizer doesn't re-enter on the component pieces and split them further. So, this is unexpectedly hard. There are work-arounds, but I'm thinking about the best way to fix this.

**Comment by scmmmh** [comment]
Ah interesting. Just out of curiosity, what is the reason that it does not re-enter? An alternative, at least for my problem would be to allow additional characters to be used to do the initial token splitting (which I assume is currently happening on white-space only). The additional characters could be output in the token stream in the same way as the new-lines are handled.

**Comment by honnibal** [comment]
We could re-enter, but I think I was worried about how this would interact with the rest of the tokenization. I think it could cause some unwanted results, because what you specify in prefixes and suffixes might not make sense after splitting on a hyphen etc.

I think specifying your own delimiters probably makes the most sense. I'll figure out how to open that up.

**Comment by scmmmh** [comment]
Of course. I see the re-entrance problem, although I'm not entirely sure I see how that differs from the prefix/suffix splitting?
