### ISSUE TITLE
lightning tour

### ISSUE THREAD

**Issue by matt-erhart** [explosion/spaCy#2250]
doc = nlp(u"Peach emoji is where it has always been. Peach is the superior "
          u"emoji. It's outranking eggplant 🍑 ")
hangs with the peach emoji but not without it. 
assert [apple.pos_, apple.pos] == [u'PROPN', 17049293600679659579] fails because apple.pos is 95 with 'en' and with en_core_web_lg.

* **spaCy version:** 2.0.11
* **Platform:** Windows-10-10.0.16299-SP0
* **Python version:** 3.6.4
* **Models:** en, en_core_web_lg, en_vectors_web_lg

**Comment by matt-erhart** [comment]
nlp.update([text], [annotations] sgd=optimizer) is missing a comma

**Comment by ines** [comment]
Thanks for the report and sorry about the mess! I've fixed all of these issues in #2274. The PR also includes editable and executable code examples for the docs, which should make these examples much more useful (and easier to maintain) 🎉
