### ISSUE TITLE
Benchmarking the German Lemmatizer

### ISSUE THREAD

**Issue by Liebeck** [explosion/spaCy#2259]
I would like to finally benchmark the German lemmatizer that is built-in since version 2.0. Furthermore, I'd like to compare the results with [IWNLP](http://www.iwnlp.com/iwnlp_results.html) since IWNLP is now available as a [spaCy extension](https://github.com/Liebeck/spacy-iwnlp).

I will evaluate the lemmatizer on three corpora. Each corpus provides pre-tokenized sentences and each token also has part-of-speech tags.

What is the fairest way to benchmark the lemmatizer? Should I process each sentence on its own or each word alone? Unfortunately, I can't  find a sample to initialize a sentence with tokens and POS tags. Can someone help provide me a short snippet?

**Comment by honnibal** [comment]
@Liebeck You can initialize a sentence with tokens and POS tags like this:

```python

from spacy.tokens import Doc

doc = Doc(vocab, words=['one', 'two', 'three'])
doc[0].tag_ = 'NN'
doc[1].tag_ = 'VBZ'
doc[2].tag_ = 'VBP'
```

When you set the `token.tag_` attribute, it should call into the `Morphology` class and then into the lemmatizer. So this should set the coarse-grained POS tag and the lemma, making it easy to evaluate.

**Comment by ines** [comment]
@Liebeck Btw, semi off-topic, but thanks for your spaCy extensions! Just submitted #2274, which will ship a new and improved extensions/plugins directory called "spaCy Universe" (I think you were probably one of the first to suggest something like this).

**Comment by honnibal** [comment]
@Liebeck I think there's at least one unfairness in your evaluation: spaCy commits to a lemma even if multiple are predicted, so you should use some sort of criterion for picking if multiple are returned. If you have a unigram frequency, that's a good way -- otherwise just take the first?

Keeping the form unchanged if it's unseen seems sound. In English we have some rewrite rules, and it would be nice to have the same for German. But failing that, keep is a good strategy.

**Comment by honnibal** [comment]
> I created a couple of source code files. Do you want to incorporate them somehow in your code?

If they're roughly the same size as the current dictionary, yes definitely! It seems an improvement.

**Comment by Liebeck** [comment]
> I think there's at least one unfairness in your evaluation: spaCy commits to a lemma even if multiple are predicted, so you should use some sort of criterion for picking if multiple are returned. If you have a unigram frequency, that's a good way -- otherwise just take the first?

@honnibal Yeah, not selecting a lemma from more than one option is disadvantegous for IWNLP. A unigram frequency selection based on another corpus / external resource, such as Wikipedia, would be possible. My initial motivation with IWNLP was to provide a lookup that is almost error-free (at least as long as the entries in Wiktionary are correct) and combine / default to rule-based approaches for unknown words. If I recall correctly, there are some ambiguous in IWNLP but not that many. Instead of guessing a lemma when multiple options are available, I have, for now, shifted the responsibility of picking the a lemma to the user, e.g., with word sense disambiguation, or by giving the users multiple options to choose from.

> If they're roughly the same size as the current dictionary, yes definitely! It seems an improvement.
The latest mapping is available as JSON: http://lager.cs.uni-duesseldorf.de/NLP/IWNLP/IWNLP.Lemmatizer_20170501.zip  
Since it is derived from Wiktionary, it is CC-licensed. I'm not sure how 'legal' it would be to merge from CC into MIT. Otherwise, I would be interesting to combine both dictionaries.

What I actually meant was that I ported the benchmark code to Python (except error analysis, as in where the lookup fails the most). In case you want to benchmark the quality of the German lemmatizer in the future, that would help you, I guess? ;-) You'd just need to set paths to the corpora. I guess you don't a subdirectory in Github for public benchmark code?

**Comment by ines** [comment]
> Since it is derived from Wiktionary, it is CC-licensed. I'm not sure how 'legal' it would be to merge from CC into MIT. Otherwise, I would be interesting to combine both dictionaries.

It might be worth double-checking, but it should work if the file itself specifies its CC license at the top? (Assuming it's a regular CC license and not CC-BY NC.)

> You'd just need to set paths to the corpora. I guess you don't a subdirectory in Github for public benchmark code?

We do have the [`spacy-benchmarks`](https://github.com/explosion/spacy-benchmarks) repo – it's not up to date, but it seems like the best place to put this for now.
