### ISSUE TITLE
feature request: zero-width lookahead/-behind expression in the Matcher

### ISSUE THREAD

**Issue by martijnvanbeers** [explosion/spaCy#2262]
The new Matcher in #1971 looks really neat! Maybe I haven't looked closely enough, but it seems that the idea in the title isn't part of the feature set. Say you want to find all loops in a text, but want to ignore fruit loops. You could do something like: `[{'LOWER': 'fruit', 'op': '!'}, {'LEMMA': 'loop'}]` (even with the old matcher), but that returns matches including whatever word is in front of loop.

I don't know how hard it would be to implement, but adding an extra flag, `include` (possibly with a better name) could make it possible to return the match as just 'loop':`[{'LOWER': 'fruit', 'op': '!', 'include' : False}, {'LEMMA': 'loop'}]`

**Comment by honnibal** [comment]
I've wanted this as well --- I definitely think it's a good idea, that shouldn't add significant implementation complexity.

**Comment by bayethiernodiop** [comment]
Any news for this

**Comment by chozelinek** [comment]
I also find it useful, maybe related to #3275

**Comment by justmars** [comment]
Would also appreciate this feature in case it's in the pipeline

**Comment by polm** [comment]
Closing this in favor of #6420, which is the same thing but more general.
