### ISSUE TITLE
Can't find 'update_shared' option in example of nlp.update(doc, gold, update_shared=True)

### ISSUE THREAD

**Issue by limesun** [explosion/spaCy#2267]
Hi Spacy,

Now I am trying to update NER pre-trained model without catastrophic forgetting problem following your guide at https://explosion.ai/blog/pseudo-rehearsal-catastrophic-forgetting.

1. 
But I was not able to find "update_shared" option in the root codes (language.py) of nlp.update.

Any idea?

This is the example code & error I got.
---------------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-29-a933eb7023df> in <module>()
      4 new_tags[0] = 'VBP'
      5 gold = GoldParse(doc, tags=new_tags)
----> 6 nlp.update(doc, gold, update_shared=True)

TypeError: update() got an unexpected keyword argument 'update_shared'

2. 
I've also tried the second method that the same website recommended but it has a key error.

This is the example code & error I got.
---------------------------------------------------------------------------------
import random
from toolz import partition_all

n_epoch =5
batch_size =32

for i in range(n_epoch):
    examples = revision_data  + fine_tune_data
    print(examples)
    random.shuffle(examples)    
    losses = {}
    
    for batch in partition_all(batch_size, examples):
        print("This is batch")
        print(batch)
        docs, golds = zip(*batch)
        print("This is docs")
        print(docs)
        print("This is golds")
        print(golds)
        nlp.update(docs, golds, losses=losses)

-------------------------------------------------------------------------------------------
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-e225e3804521> in <module>()
     25         print("This is golds")
     26         print(golds)
---> 27         nlp.update(docs, golds, losses=losses)

~\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\spacy\language.py in update(self, docs, golds, drop, sgd, losses)
    425                 continue
    426             grads = {}
--> 427             proc.update(docs, golds, drop=drop, sgd=get_grads, losses=losses)
    428             for key, (W, dW) in grads.items():
    429                 sgd(W, dW, key=key)

nn_parser.pyx in spacy.syntax.nn_parser.Parser.update()

nn_parser.pyx in spacy.syntax.nn_parser.Parser.get_batch_loss()

arc_eager.pyx in spacy.syntax.arc_eager.ArcEager.set_costs()

ValueError: [E021] Could not find a gold-standard action to supervise the dependency parser. The GoldParse was projective. The transition system has 111 actions. State at failure: __0 __0 Initial_2 | Content _

## Your Environment

    Info about spaCy

    spaCy version      2.0.12.dev0
    Platform           Windows-10-10.0.16299-SP0
    Location           C:\Users\great\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\spacy
    Python version     3.5.2
    Models             en, en_core_web_lg

**Comment by limesun** [comment]
Hey,

I've solved 2nd issue and error. It was because I didn't disable other pipelines other than NER.

However, the first issue is still open. I am still wondering how I can use the 'update_shared' in nlp.update.

**Comment by honnibal** [comment]
@limesun The `update_shared` argument is no longer current, as the pipeline now uses independent models for the parser, tagger and entity recognizer. Apologies for the confusion!
