### ISSUE TITLE
sense2vec installation error - UnicodeDecodeError

### ISSUE THREAD

**Issue by limesun** [explosion/spaCy#2271]
Hi spacy,

I am trying to install/test sense2vec but got an installation issue like below.

-------------------------------------------------------------------------------------------------------------------
C:\Users\great>pip install sense2vec==1.0.0a0
Collecting sense2vec==1.0.0a0
  Downloading https://files.pythonhosted.org/packages/28/4a/a1d9a28545adc839789c1442e7314cb0c70b8657a885f9e5b287fade7814/sense2vec-1.0.0a0.tar.gz (311kB)
    100% |################################| 317kB 1.8MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\great\AppData\Local\Temp\pip-install-2ics1q41\sense2vec\setup.py", line 169, in <module>
        setup_package()
      File "C:\Users\great\AppData\Local\Temp\pip-install-2ics1q41\sense2vec\setup.py", line 107, in setup_package
        readme = f.read()
      File "c:\users\great\appdata\local\enthought\canopy\edm\envs\user\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 13089: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\great\AppData\Local\Temp\pip-install-2ics1q41\sense2vec\

-----------------------------------------------------------------------------------------------------

## Your Environment

C:\Users\great>python -m spacy info

    Info about spaCy

    Python version     3.5.2
    Platform           Windows-10-10.0.16299-SP0
    Models             en, en_core_web_lg, en_core_web_md, en_vectors_web_lg
    Location           C:\Users\great\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\spacy
    spaCy version      2.0.12.dev0

**Comment by ines** [comment]
Thanks – looks like [this call](https://github.com/explosion/sense2vec/blob/master/setup.py#L106) in the `setup.py` is missing an `encoding='utf8'`. Just fixed this over in the [sense2vec repo](https://github.com/explosion/sense2vec), so this should be fixed for the next release. In the meantime, you can also clone the repo and build it from source:

```bash
python setup.py build_ext --inplace
```
