### ISSUE TITLE
All tokens are OOV and giving same probability

### ISSUE THREAD

**Issue by proy251183** [explosion/spaCy#2276]
Looks like a bug below is snippet and output 

import spacy
from spacy import load
nlp = spacy.load('en')

nlp.vocab[u'the'].prob
>> -20.0
nlp.vocab[u'not'].prob
>> -20.0
nlp.vocab[u'the'].is_oov
>> True
nlp.vocab[u'not'].is_oov
>> True

## Info about spaCy

* **spaCy version:** 2.0.11
* **Platform:** Windows-10-10.0.16299-SP0
* **Python version:** 3.6.1
* **Models:** en

**Comment by biarne-a** [comment]
This is not an issue. The 'en' model is a alias for the 'en_core_web_sm' model which is the minimalist model not containing word vectors. Use 'en_core_web_md' or 'en_core_web_lg' instead.
