### ISSUE TITLE
add separator attribute to Token class to make concatenation easier

### ISSUE THREAD

**Issue by inspirassion** [explosion/spaCy#2279]
It would be greate if we can have an attribute` separator` to the class Token, this way we can know the left separator used when splitting a sentence. this way we can reconcatenate sentence easily using tokens after some processing

**Comment by honnibal** [comment]
I think `token.whitepace_` does what you need, but it's the rightward separator. It's always either the empty string, or a single space.

Internally spaCy doesn't store the original string. When you call `doc.text`, it's always reconstructed by looking up the string via the hash keys and joining it back together.
