### ISSUE TITLE
Word Vectors are case insensitive 

### ISSUE THREAD

**Issue by r-wheeler** [explosion/spaCy#2281]
Is it expected that en_core_web_lg is using the lower cased glove vectors? 

```
nlp = spacy.load("en_core_web_lg")
np.array_equal(nlp.vocab.get_vector("Apple"), nlp.vocab.get_vector("apple")) 
```
True 

The StringStore has different hashes for each: 
```
nlp.vocab.strings['apple'] 
8566208034543834098
```
```
nlp.vocab.strings['Apple']
6418411030699964375
```

But even using these hashing to look up vectors with nlp.vocab.get_vector  It is true: 

```
nlp = spacy.load("en_core_web_lg")
np.array_equal(nlp.vocab.get_vector(6418411030699964375),nlp.vocab.get_vector(8566208034543834098))
True
``` 

## Info about spaCy

* **spaCy version:** 2.0.8
* **Platform:** Linux-4.4.0-1054-aws-x86_64-with-Ubuntu-16.04-xenial
* **Python version:** 3.6.3
* **Models:** en_core_web_lg, en_vectors_web_lg

**Comment by honnibal** [comment]
Confirmed true, and yes this surprised me.

Unfortunately we've been passing around these vocab and vectors files for a while for the large vocabulary, which allows a lot of scope for things to go wrong. I'm really looking forward to getting our data pipeline set up, so that we can trigger periodic retraining of vocabularies and vector models instead.

**Comment by svlandeg** [comment]
As this behaviour is still present, I've labeled it as bug to try and get this higher on our TODO list ;-)

**Comment by adrianeboyd** [comment]
We've been working on improved vectors off-and-on in the background for a while (in particular with [floret](https://github.com/explosion/floret)), and finally the English models for v3.4.0 have new English vectors that are case-sensitive.

If you're curious about the details, the project for training the vectors is available here:

https://github.com/explosion/spacy-vectors-builder/tree/lang/en

The project can train both fastText and floret vectors, but we want to keep using standard/default vectors for the v3 English models, so the new vectors are the fastText vectors.
