### ISSUE TITLE
How we could update an existing model by a command line?

### ISSUE THREAD

**Issue by KMohaghegh** [explosion/spaCy#2284]
First thanks for you fantastic software and works. I am after a bit of try manage to trained my NER model from command line. The problem was in Jason file and annotations. But now my question is how to update that trained model in/from the command line. I cannot find anything in documentation to load an existing  model and then trained it from a command line.

I convert by this command:
python -m spacy convert [input_file] [output_dir] [--converter] [--n-sents]
[--morphology]

I trained by this command:
python -m spacy train [lang] [output_dir] [train_data] [dev_data] [--n-iter]
[--n-sents] [--use-gpu] [--meta-path] [--vectors] [--no-tagger] [--no-parser]
[--no-entities] [--gold-preproc]

It might be I should do something with  [--meta-path]  but I have no idea, anything even small might help a lot. Thanks in advance for you help and time.

Mac
Python 2.7
Spacy 2.0.9

**Comment by honnibal** [comment]
The command-line naturally offers a subset of the functionality you can implement with the library. You can find the train command in `spacy/cli/train.py`. I suggest you make a copy of the file to make your own script, so you can modify it with the arguments you need.
