### ISSUE TITLE
German POS Tagger is case sensitiv

### ISSUE THREAD

**Issue by ctrado18** [explosion/spaCy#2288]
Hi,

I recognised that the POS Tagger is case sensitiv for german. I use the spacy POS tagger for NER wih CRF. Nouns get ADV or Verbs when writing in lower cases. Therefore, case sensitivity is very bad for NER. Shouldn't this be fixed? How can you fix that?

spacy v 2, small german model

**Comment by ines** [comment]
For many types of features and uses, case-sensitivity is a very important feature – especially in languages like German. The model is also trained on mostly news text, which means the training data mostly used proper capitalisation.

If you're working with web or chat text where you can't rely on that, you might want to [update the model](https://spacy.io/usage/training) with more examples to make it less case-sensitive. This works especially well if you have data specific to your application. You could also take existing labelled data and lowercase it – however, getting this working as expected might be a bit fiddly (and ultimately depends on that data).

There's also an enhancement issue about a German model on lowercase text: #1922
