### ISSUE TITLE
Stream-read data during training to avoid ujson failing with large json files

### ISSUE THREAD

**Issue by mollerhoj** [explosion/spaCy#2291]
Proposed solution:

Move to rapidjson.

Allow to load json from folder with multiple json files, not just one giant file.

I'd love to make the PR, just don't know what direction I should take.

**Comment by honnibal** [comment]
This is fixed on develop, and will be released into 2.1. I spent some time on this and did actually look at rapidjson, and a couple of other libraries. None really solved the problem, which is that the Python objects themselves are quite large when the annotation files get big.

The code on develop has some custom parsing code to just find the string offsets of the outermost objects in spaCy's data format: https://github.com/explosion/spaCy/blob/develop/spacy/gold.pyx#L304 . This is sufficient to solve the problem, and is pretty efficient.

I also added some code to write msgpack files for each document to disk, to make it easier to shuffle subsequent iterations without reading in all the data.
