### ISSUE TITLE
Pattern match is not greedy

### ISSUE THREAD

**Issue by zulkuf** [explosion/spaCy#2294]
Hi,

I am having issues with the rule-based matching. It seems that '+' and '\*' operators match non-greedy contrary to expected behavior.  '*' matches zero and stops, '+' matches one and stops rather than matching everything they can. 

For example,  the code below matches only "Donald said" part of the sentence. If I change '+' to '*' in `{'IS_ASCII': True, 'OP': '+'}`, then it matches only Donald as a PERSON entity.

```python
matcher = Matcher(nlp.vocab)
test_doc = nlp(u"Donald said that America will be great again in 2020")
pattern = [ {'ENT_TYPE': 'PERSON'},{'IS_ASCII': True, 'OP': '+'},{'ENT_TYPE': 'DATE', 'OP': '*'}]
#test_doc.ents entities: [('Donald', 'PERSON'), ('America', 'GPE'), ('2020', 'DATE')]
matcher.add('test_pattern', None, pattern)
matches = matcher(test_doc)

for match_id, start, end in matches:
    span = test_doc[start:end]
    print(span.text)    # outputs: 'Donald said'
```
However, similar regex version of the same pattern matches all:
```python
re.search(r"Donald[\w\s]+[\d]*",u"Donald said that America will be great again in 2020")
#outputs: 'Donald said that America will be great again in 2020'
```

## Your Environment

* **spaCy version:** 2.0.12.dev0
* **Platform:** Windows-10-10.0.16299-SP0
* **Python version:** 3.6.4
* **Models:** en, en_core_web_md, en_vectors_web_lg

**Comment by honnibal** [comment]
This is fixed on the develop branch, for v2.1. We haven't released it onto master yet as it may break people's code.
