### ISSUE TITLE
segment sentences on newlines

### ISSUE THREAD

**Issue by moh55m55** [explosion/spaCy#2299]
is there a way to recognize sentences as each newline in document? I did not find this in the docs
for example: 

```python
text=" I went to the store and got beck. he said.\n well,  thats should be ok."


doc=nlp(text)
for sent in doc.sents:
    print (sent)
```

The result is this : 
I went to the store and then got beck.
he said.
well, I thats should be ok.

where  the desired result is: 
I went to the store and then got beck. he said.
well, thats should be ok.

Thanks

**Comment by ines** [comment]
Sure – if that's what you want, you can implement a custom sentence segmentation strategy using the [`SentenceSegmenter` hook](https://github.com/explosion/spaCy/blob/414f5270b330e35d3cb16bbdae433f0debb3d310/spacy/pipeline.pyx#L40). This isn't documented well at the moment, but I'll put this on my list for examples to add to the docs 😊

The `SentenceSegmenter` is a pipeline component that can be initialised with a `strategy` argument (the function used to compute the boundaries). For example:

```python
import spacy
from spacy.pipeline import SentenceSegmenter

def split_on_newlines(doc):
   # compute your sentence boundaries here
   # and yield Span objects

nlp = spacy.load('en')
sbd = SentenceSegmenter(nlp.vocab, strategy=split_on_newlines)
nlp.add_pipe(sbd, first=True)
```

Setting `first=True` will add it before all other pipeline components and also before the parser (which normally sets the sentence boundaries). The parser should respect already set boundaries and ideally, you might also see better predictions – however, if you find that the POS tags and dependency labels are less accurate this way, you can also add it last in the pipeline by setting `last=True` instead.

**Comment by moh55m55** [comment]
Thanks. But "\n" is not considered as token in Doc object to detect sentence boundary. How to detect that ? 
Am I missing something here?
