### ISSUE TITLE
string indices must be integers

### ISSUE THREAD

**Issue by felixganz** [explosion/spaCy#2300]
Hi.. I try to evaluate my model with CLI, i got error like this
![screen shot 2018-05-07 at 12 08 03 am](https://user-images.githubusercontent.com/24998545/39675812-ca6eb596-518a-11e8-84df-b7a488582604.png)

can someone tell me what wrong here?

**Comment by ines** [comment]
This is difficult to debug without seeing your data, but I suspect that there's a problem with the way your your JSON data is formatted. If the [JSON input format](https://spacy.io/api/annotation#json-input) doesn't match (i.e. misses a level of nesting etc.), the data isn't read in correctly and creating the gold-standard data fails.

I had a look at the respective line that causes the error in `gold.pyx` – [see here for the source](https://github.com/explosion/spaCy/blob/9a1d3b63fbd8d90c41cbccac9f127950bbbb4c52/spacy/gold.pyx#L312). `doc['paragraphs']` failing with "string indices must be integers" indicates that in your case, `doc` ended up being a string, when it should be a dictionary with a key `'paragraphs'`. So if you compare your data with the [expected JSON format](https://spacy.io/api/annotation#json-input), you'll probably find that you're missing the `"paragraphs"` key and are just passing in a list of strings directly (or something similar).
