### ISSUE TITLE
on_match function of matcher with regex pattern won't execute

### ISSUE THREAD

**Issue by naxty** [explosion/spaCy#2311]
## How to reproduce the behaviour

Hi,

I just encountered a small bug when playing around with the patterns of [Matcher](https://spacy.io/api/matcher#add). When I am adding **{'REGEX': '[.]'}** to the patterns the specified **on_match** function won't get executed. See the code snippets below.

**Sample 1: Function is executed**

    def on_match(matcher, doc, id, matches):
        print('Matched!', matches)
    matcher = Matcher(nlp.vocab)
    matcher.add('GoogleMaps', on_match, [{'ORTH': 'Google'}, {'ORTH': 'Maps'}])
    doc = nlp(u'Hello World on Google Maps.')
    matches = matcher(doc)

Produces the output: Matched! [(4623319167898722399, 3, 5)]

**Sample 2: Function is not executed**

    def on_match(matcher, doc, id, matches):
        print('Matched!', matches)
    matcher = Matcher(nlp.vocab)
    matcher.add('GoogleMaps', on_match, [{'ORTH': 'Google'}, {'ORTH': 'Maps'}, {'REGEX':'[.]'}])
    doc = nlp(u'Hello World on Google Maps.')
    matches = matcher(doc)

Produces no output.

## Environment
I run the code in a jupyter notebook with the following environment:

* **spaCy version:** 2.0.11
* **Platform:** Linux-4.13.0-36-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.5
* **Models:** de, en

**Comment by ines** [comment]
The current version of the `Matcher` only supports using regular expressions via a flag – see [this section in the docs](https://spacy.io/usage/linguistic-features#regex) for examples. If this is sufficient for what you're trying to do, you could do something like:

```python
definitely_flag = lambda text: bool(re.compile(r'deff?in[ia]tely').match(text))
IS_DEFINITELY = nlp.vocab.add_flag(definitely_flag)
matcher.add('DEFINITELY', None, [{IS_DEFINITELY: True}])
```

The `REGEX` attribute and all other features I'm describing in #1971 are only the proposal / proposed feature spec – they're not actually available in spaCy yet. (Sorry if this was confusing – we're working on implementing the new matcher features and I'm looking forward to shipping them in one of the upcoming versions! 🚢) 

For a list of the currently available `Matcher` attributes, see [the overview here](https://spacy.io/usage/linguistic-features#adding-patterns-attributes).

**Comment by naxty** [comment]
Thanks for your quick and detailed response!
