### ISSUE TITLE
Pos-tagging in french

### ISSUE THREAD

**Issue by Gregory-Howard** [explosion/spaCy#2313]
## How to reproduce the behaviour
```
import spacy
nlp = spacy.load('fr') # same for fr_core_news_md
doc= nlp("Nous a-t-elle précisé ceci?")
print([x.pos_ for x in doc]) # ['PRON', '', 'PART', 'PRON', 'VERB', 'PRON', 'PUNCT']
doc= nlp("Nous a t-elle précisé ceci?")
print([x.pos_ for x in doc]) # ['PRON', 'AUX', 'NOUN', 'VERB', 'PRON', 'PUNCT']
```
The problem is the `AUX `missing in the first example

Problem should be here : https://github.com/explosion/spaCy/blob/master/spacy/lang/fr/tokenizer_exceptions.py#L63
Exception works. The problem is somewhere else.
## Info about spaCy

* **spaCy version:** 2.0.8
* **Platform:** Windows-7-6.1.7601-SP1
* **Python version:** 3.6.3
* **Models:** fr, fr_core_news_md

**Comment by ines** [comment]
Merging this with #3052 and added the example to my comment [here](https://github.com/explosion/spaCy/issues/3052#issuecomment-448958656).
