### ISSUE TITLE
For some tokens "has_vector" value is True, but "vector" is empty

### ISSUE THREAD

**Issue by marisst** [explosion/spaCy#2317]
For tokens such as "subindexes", "sportsclub", "unshelving", "datavault" and "freemark" the `has_vector` property value equals `True`, but the actual vector contains only zeros.

To replicate, run this script:
```
import spacy

nlp = spacy.load('en_vectors_web_lg')
doc = nlp("subindexes sportsclub unshelving datavault freemark marthe ladislav economypolicy parmeter")
for token in doc:
    print("Token: \"%s\"" % token)
    print("has_vector:", token.has_vector)
    print("vector:\n", token.vector, "\n")
```

The output looks like this:
```
Token: "subindexes"
has_vector: True
vector:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

...
```

### Info about spaCy
    spaCy version      2.0.11
    Location           /Users/marisstubelis/anaconda3/lib/python3.6/site-packages/spacy
    Platform           Darwin-17.4.0-x86_64-i386-64bit
    Python version     3.6.4
    Models             en_vectors_web_lg, en

**Comment by shreyashub** [comment]
Is there a way we can change the `has_vector` attribute and set it to False

**Comment by honnibal** [comment]
@shreyashub Yes, there are a couple of ways.

One is to set a custom function in `doc.user_token_hooks["has_vector"]`. You can have a pipeline component to help you install this. This will allow you complete control of the attribute.

Another way is to remove the key for these words from the `Vectors.key2row` data structure. I think this should work:

```python

for lex in nlp.vocab:
    if lex.has_vector and (lex.vector**2).sum() == 0:
        nlp.vocab.vectors.key2row.pop(lex.orth)
```

**Comment by ines** [comment]
The underlying data is definitely something we want to fix when we re-train the vectors. In the meantime, you can use the approach described by @honnibal above.
