### ISSUE TITLE
support printing of progress when using nlp.pipe()?

### ISSUE THREAD

**Issue by mdunnlp** [explosion/spaCy#2318]
## Feature description
As a user when I'm running a SpaCy pipe() with custom components on a large data set, I'd like to get an estimate of how far through the data set I've progressed. Is there a way to print something to standard out that would allow users to know how many records/percent of the data the pipeline has processed?

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
If so, we will tag it as [`project idea`](https://github.com/explosion/spaCy/labels/project%20idea) so other users can take it on.

It seems like this would need to be a feature of the cython multiprocessing code, so I don't think it would lend itself to a custom component.

**Comment by honnibal** [comment]
```
import tqdm

for doc in tqdm.tqdm(nlp.pipe(texts)):
    # Stuff
```
That should do what you want --- the `tqdm` library just wraps a loop. I think it's definitely normal and right that the progress bar logic belongs to your application, and isn't something spaCy does for you.
