### ISSUE TITLE
error in download cli

### ISSUE THREAD

**Issue by janimo** [explosion/spaCy#2320]
## How to reproduce the behaviour

python -m spacy download en

results in an traceback ending in
```
    data = url_read(url, verify=ssl_verify)
TypeError: url_read() got an unexpected keyword argument 'verify'
```
something like this solves it
```
--- spacy/cli/download.py
+++ spacy/cli/download.py
@@ -71,7 +71,7 @@ def download(model, direct=False, insecure=False, ca_file=None):
 
 def get_json(url, desc, ssl_verify):
     try:
-        data = url_read(url, verify=ssl_verify)
+        data = url_read(url)
```

## Your Environment

* Operating System: Linux
* Python Version Used: 3.6
* spaCy Version Used: master
* Environment Information:

**Comment by YanLiang1102** [comment]
yeah I saw the same issue and get rid of that parameter will fix it

**Comment by ines** [comment]
Hmm, so this parameter was added in #2212 to accommodate (custom) SSL certificate validation. I'm not sure why this causes an error for some users and not others, though...

The main reason we required this change is that we decided to drop the `requests` dependency (which spaCy only used in the CLI module). But I'm now thinking that maybe we should just accept the extra dependency in favour of convenience and fewer workarounds..
