### ISSUE TITLE
Part of Speech Tagger for training NER

### ISSUE THREAD

**Issue by KMohaghegh** [explosion/spaCy#2333]
First of all thanks for your fantastic works. I have a question regarding the TAGGER, wanted to know that first of all PART OF SPEECH TAG is necessary for training the NER. As some of lang module like Swedish do not have tagger just want to know that trough your experience how training without tagger effect the results. I tried with in spacy 2.0.9 and manage to train a NER for Swedish without the tagger but want to know your idea. It might be that trained model is a dummy version of a matcher as it was trained without the tagger and parser.

Using Mac
Spacy 2.0.9

**Comment by ines** [comment]
No, in spaCy v2.x, all pipeline components are independent, so you don't need a tagger to train the entity recognizer! 🙂

**Comment by KMohaghegh** [comment]
Thanks for your fast reply, but what about the accuracy and quality of the model? What do you think regarding the quality of the model trained without the Tagger but with a huge dta such as 100 to 200 MB of data.
