### ISSUE TITLE
Command line converter has a unicode issues

### ISSUE THREAD

**Issue by KMohaghegh** [explosion/spaCy#2337]
Hi again, I tries to convert an iob file to Jason via command line in spacy and I got the Jason file but all the non-english character has a unicode problem. I just put one line of my iob file here:

Det||O väntas||O EU-kommissionen||I-MISC föreslå||O i||O .||O

and the json converters:

[
  {
    "id":0,
    "paragraphs":[
      {
        "sentences":[
          {
            "tokens":[
              {
                "tag":"",
                "ner":"O",
                "orth":"Det"
              },
              {
                "tag":"",
                "ner":"O",
                "orth":"v\u00e4ntas"
              },
              {
                "tag":"",
                "ner":"U-MISC",
                "orth":"EU-kommissionen"
              },
              {
                "tag":"",
                "ner":"O",
                "orth":"f\u00f6resl\u00e5"
              },
              {
                "tag":"",
                "ner":"O",
                "orth":"i"
              },
              {
                "tag":"",
                "ner":"O",
                "orth":"."
              }
            ]
          }
        ]
      }
    ]
  }
]

It has a unicode issues. Please take a look and let me know how could I solve this issue. I checked the input it has a utf-8 format and when I open the .iob with several text editor it looks fine and no utf-8 problem.

Python 2.7
Spacy 2.0.9
On Mac

Thanks

**Comment by ines** [comment]
When the JSON is saved out, spaCy uses the default settings of `ujson` and all non-ASCII characters are converted to ASCII. When the data is loaded back in, those are converted back. Here's an example:

```python
import ujson

text = '{"tag":"", "ner":"O", "orth":"v\u00e4ntas"}'  # the JSON to load in
print(ujson.loads(text))
# {'tag': '', 'ner': 'O', 'orth': 'väntas'}
```

If you know that your format is UTF-8 and you won't have any encoding problems, you can also edit the converter and set `ensure_ascii=False` on `ujson.dumps` ([see here](https://pypi.org/project/ujson/)).
