### ISSUE TITLE
Norwegian language code should be "no"

### ISSUE THREAD

**Issue by gurudevrao** [explosion/spaCy#2339]
For Norwegian language spaCy currently uses "nb" as the language code.

However, "no" is the ISO 639-1 code for Norwegian.
"nb" is one of the two written standards of Norwegian ie Bokmål the other being Nynorsk (code "nn")

So, should "nb" be changed to "no" instead or change the language name to Bokmål?

**Comment by ines** [comment]
Merging this with #2338!
