### ISSUE TITLE
Vector of new word

### ISSUE THREAD

**Issue by Rahul6818** [explosion/spaCy#2341]
How exactly spacy vectorisation deals with new word which are not present in vocabulary.

**Comment by chandan2495** [comment]
Vector of a new word is simply one dimensional array of zeros. You can check it using the following code.
```python
import spacy
nlp = spacy.loads('en')
print(nlp.vocab.get_vector('abbbb')
```

**Comment by Rahul6818** [comment]
@chandan2495 it gives empty even for common English (like - name, city..) words. Didn't we feed it with English vocab when you loaded the nlp?

**Comment by chandan2495** [comment]
@Rahul6818 by default `en` loads the smaller statistical model which is having a smaller vocab of around 50000 words. Please try loading the large model `en_core_web_lg` which have around 1.3 million words.
