### ISSUE TITLE
Using spaCy without GPU but installed cupy

### ISSUE THREAD

**Issue by makcedward** [explosion/spaCy#2343]
We have a image of VM installed lots of library for both CPU and GPU machine. When invoking 

```
nlp = spacy.load('en')
article = 'test test test'
nlp(article)
```

It got 
```
CUDARuntimeError                          Traceback (most recent call last)
<ipython-input-33-8816fd999472> in <module>()
----> 1 device = cupy.cuda.device.Device(None)
      2 device.use()
      3 # Model.ops = CupyOps()
      4 # Model.Ops = CupyOps

cupy/cuda/device.pyx in cupy.cuda.device.Device.__init__()

cupy/cuda/runtime.pyx in cupy.cuda.runtime.getDevice()

cupy/cuda/runtime.pyx in cupy.cuda.runtime.check_status()

CUDARuntimeError: cudaErrorUnknown: unknown error
```

Checked use_gpu function, it seems that spaCy treat the machine has GPU if able to import cupy library. Suggesting that adding a optional parameter to force using cpu. 

Current workaround is uninstall cupy library.

```
def use_gpu(gpu_id):
    try:
        import cupy.cuda.device
    except ImportError:
        return None
    from thinc.neural.ops import CupyOps
    device = cupy.cuda.device.Device(gpu_id)
    device.use()
    Model.ops = CupyOps()
    Model.Ops = CupyOps
    return device
```

**Comment by honnibal** [comment]
Thanks, will fix.

**Comment by makcedward** [comment]
Before applying the bug fix, I pull the master branch and executing test case but got several hundred failure. Seems like there is environment issue in my VM.  I give up to fix env in order to execute original test case.

Anyway, proposing to enhance use_gpu function as following (not tested):
``
def use_gpu(gpu_id):
    ### Start: Added to check whether using CPU or not
    if gpu_id == -1:
        return None
    ### End:
    try:
        import cupy.cuda.device
    except ImportError:
        return None
    from thinc.neural.ops import CupyOps
    device = cupy.cuda.device.Device(gpu_id)
    device.use()
    Model.ops = CupyOps()
    Model.Ops = CupyOps
    return device

``

**Comment by honnibal** [comment]
I think this is resolved now, since we have the `prefer_gpu()` and `require_gpu()` helpers from Thinc.
