### ISSUE TITLE
Is spaCy ready for production use with Persian language?

### ISSUE THREAD

**Issue by reza-ebrahimi** [explosion/spaCy#2345]
I'm trying to start using spaCy with Persian language, but there is no official supported model to use, furthermore there is no useful information about how to build a model from scratch for spaCy, my question is spaCy was ready for production use with Persian language?

**Comment by mosynaq** [comment]
Hey @reza-ebrahimi , I think there IS an official guide to add languages to spaCy and you can find that [here](https://spacy.io/usage/adding-languages). It certainly takes time and needs resources.

**Comment by ines** [comment]
Hi! Sorry for only getting to this now. spaCy currently offers "alpha tokenization support" for a [variety of languages](https://spacy.io/usage/models#alpha-support) including Persian. The state of the language data varies, depending on community contributions and available resources. The language data is the first step towards being able to train a model – but ultimately, it comes down to the resources and finding a suitable training corpus.

For more information on how to train a full spaCy model from a Universal Dependencies treebank, see this section: https://spacy.io/usage/training#spacy-train-cli
