### ISSUE TITLE
Unclear documentation about the JSON input format for training

### ISSUE THREAD

**Issue by JamesMessinger** [explosion/spaCy#2353]
## Which page or section is this issue related to?
[JSON input format for training](https://spacy.io/api/annotation#json-input)

## Issue
The comment next to the `paragraphs.sentences.tokens.id` attribute says "_index of the token in the **document**_", but in the [sample JSON](https://github.com/explosion/spacy/blob/master/examples/training/training-data.json) on the same page, the `id` attribute seems to be the index of the token in the **sentence**.  Notice that [the `id` attribute resets to zero](https://github.com/explosion/spacy/blob/master/examples/training/training-data.json#L579) for tokens in the second sentence.

So which is correct?  The sample JSON, or the documentation?

If the sample is correct, then what is the best way to get the index of a token within its sentence?  It's easy to get the index within the document:

```python
sents = list(doc.sents)
first_token_of_second_sentence = list(sents[1])[0]
print(first_token_of_second_sentence.i)
>>> 49
```

but the only way I can find to determine the index of a token within its sentence is to subtract the index of the last token of the previous sentence, then subtract 1, which seems inelegant.  Is there a better way?

```python
sents = list(doc.sents)
last_token_of_first_sentence = list(sents[0])[-1]
first_token_of_second_sentence = list(sents[1])[0]
print(first_token_of_second_sentence.i - last_token_of_first_sentence.i - 1)
>>> 0
```

**Comment by ines** [comment]
Merging this with #2928 – thanks for your patience on this!
