### ISSUE TITLE
Error Testing

### ISSUE THREAD

**Issue by aristorinjuang** [explosion/spaCy#2355]
## How to reproduce the behaviour
I'm new at spaCy and want to develop a language model on it. I tried to run test based on this instruction (https://github.com/explosion/spaCy/tree/master/spacy/tests), but I got an error message.

> ModuleNotFoundError: No module named 'spacy.symbols'

That is what I got when I ran `py.test spacy` on spaCy (root folder).

Did I make a mistake?

I tried to follow this instruction: https://spacy.io/usage/adding-languages#section-testing

Thanks for help.

## Your Environment

* Operating System: Linux Ubuntu 18.04 LTS
* Python Version Used: 3.6.4
* My Repository: https://github.com/aristorinjuang/spaCy

**Comment by ines** [comment]
That error message looks like spaCy didn't compile correctly... Did you build spaCy from source after you made your edits? (Sorry if the docs here were unclear.) You can find more details on the process [here](https://spacy.io/usage/#source) or build the full command in our [quickstart widget](https://spacy.io/usage/#source). *TL;DR*: Run the following from within your spaCy directory:

```bash
export PYTHONPATH=`pwd`
pip install -r requirements.txt
python setup.py build_ext --inplace
```

The first command makes sure you're executing the right spaCy, i.e. your fork. The second installs the requirements and the third compiles the library. If you're only editing `.py` files, you'll only have to do this once in the beginning – if you're editing the `.pyx` files, you'll need to recompile spaCy before you can test it. Also, to be double safe, I usually run pytest with `python -m pytest spacy`, to make sure that I'm running the correct version of pytest in my environment (and not some old system one by mistake).

**Comment by aristorinjuang** [comment]
Thanks. It is working properly now.
