### ISSUE TITLE
New dependency labels not referenced yet?

### ISSUE THREAD

**Issue by boblespatates** [explosion/spaCy#2367]
Hi,
I used the spacy default english pipeline doing this littel piece of code:

nlp = spacy.load('en')
doc = nlp(u'Nearly 30,000 people packed the streets of San Francisco to pay him homage at his funeral.')

for sent in doc.sents:
    for word in sent:
        print(word.text, word.dep_)

I got the follwing result :

<details>
Nearly advmod /
30,000 nummod /
people nsubj /
packed ROOT /
the det /
streets dobj /
of prep /
San compound /
Francisco pobj /
to aux /
pay advcl /
him ## dative /
homage dobj /
at prep / 
his poss /
funeral pobj /
. punct /
</details> 

And the "dative" label isn't in : https://spacy.io/api/annotation#dependency-parsing
I also saw labels such as "predet" and "relcl", which I coudn't find anywhere in the github.
Is it new uptades not already documented, or it's my own fault because I did something wrong with the models (in that case I'm really sorry guys)?

By the way, this library is super cool. thanks a lot for doing this really great tool!

* **Models:** en, xx  (en_core_web_sm-2.0.0 model)
* **Platform:** Linux-4.9.0-6-amd64-x86_64-with-debian-9.4
* **Python version:** 3.5.3
* **spaCy version:** 2.0.11

**Comment by honnibal** [comment]
This is a fault in the documentation, and also the label list. I changed the minimum frequency cut-off for labels in the parser in v2, as it's now no problem to have more labels. In v1 the model was very sensitive to this, as we had to learn a distinct weight for each feature/label pair.

**Comment by boblespatates** [comment]
Oh. Thanks a lot. It's a lot more clear now!

**Comment by ines** [comment]
See 4e89cfaae17eed6e07206eb23bf505cfb77b02db!
