### ISSUE TITLE
spacy.errors warning handling overrides filtering of deprecation errors

### ISSUE THREAD

**Issue by vwood** [explosion/spaCy#2369]
## How to reproduce the behaviour

import spacy
import warning
warnings.filterwarnings("ignore")

Shouldn't be any warnings down here, yet there are!

Also, FYI - nobody cares about deprecation warnings coming from the libraries non-deprecated functions.

Your _warn function in spacy.error is removing the users ability to control their own error reporting. I'm having to reach into your modules and override the function to fix this ugly behaviour.

**Comment by honnibal** [comment]
Your comment came across as pretty hostile.

But sure, we'll fix this, thanks.

**Comment by ines** [comment]
Thanks! If there are any cases you've come across where spaCy itself triggers its own deprecation warnings, definitely report them. We did spot one or two instances after we initially introduced the warnings and fixed those.

The [latest version on `develop`](https://github.com/explosion/spaCy/blob/5d281cf302acd2ff5281ccde353ccc5b74c6f717/spacy/errors.py) now includes the option to ignore specific warning codes via the `SPACY_WARNING_IGNORE` and `SPACY_WARNING_TYPES` environment variables (e.g. to only ignore deprecation warnings but not user or model warnings), and set the filter via `SPACY_WARNING_FILTER`. I agree that it's bad that the existing `filterwarnings` isn't respected. I'll reread the `warnings` spec again and see if there's an easy way to get the existing configuration and use that as the default value, if available. Also always open for suggestions if you have implementation ideas!
