### ISSUE TITLE
Reading pre-trained word vectors (fasttext)

### ISSUE THREAD

**Issue by moh55m55** [explosion/spaCy#2375]
Hello, 
I downloaded fasttext pre-trained word vectors.ZIP from here https://fasttext.cc/docs/en/english-vectors.html. According to the Docs it can handle .ZIP, but when I tried to convert the vectors model into a binary format using this command 

`python -m spacy init-model en /temp -v  wiki-news-300d-1M.vec.zip`

I got this error : `'utf-8' codec can't decode byte ...`

even when I added  **"errors='ignore'"** in **init-model.py** I got this error:   `invalid literal for int() with base 10: 'PK\x03\x04\....`

Any idea? 
Thanks

## Your Environment

* Operating System: 
* Python Version Used: 
* spaCy Version Used: 
* Environment Information:

**Comment by honnibal** [comment]
Which version are you using? The .zip reading is pretty recent, I think in v2.0.11.

**Comment by ines** [comment]
Here's a similar issue from a while ago – do any of the suggestions on that thread help? The part about converting the unzipped to utf-8 might be relevant: https://github.com/explosion/spaCy/issues/2298#issuecomment-387183960

**Comment by ines** [comment]
Have you tried converting the unzipped file to utf-8 as described in [this comment](https://github.com/explosion/spaCy/issues/2298#issuecomment-387193623)?
