### ISSUE TITLE
Low and constant UAS score

### ISSUE THREAD

**Issue by rafidwiriz** [explosion/spaCy#2377]
Hi. I'm having trouble with training tagger and parser using Universal Dependencies corpus, especially with Indonesian.

I followed your instruction, do `spacy convert` and then do `spacy train`. I had no problem with `spacy convert`, but I had major issue with `spacy train` one. UAS score in every iteration is not more than 30. I tried to increase the iteration number, it's still same. And then, I found out that UAS score in one training is same as before (for example, in every training, UAS score in iteration #1 always 18.3).

I thought it because I used Indonesian language, which is not perfect because of no tagmap and other things. Then, I tried using English UD corpus. But, it's still having the same issues.
Did I do something wrong?

###Note:
+ I used UD train and dev corpus.
+ Command for convert:
    + `py -m spacy convert id_gsd-ud-train.conllu data -c conllu -n 4477` for train file.
    + `py -m spacy convert id_gsd-ud-dev.conllu data -c conllu -n 559` for dev file.
+ Command for train: `py -m spacy train id model data/id_gsd-ud-train.json data/id_gsd-ud-dev.json -n 60`
+ Result:
```
    Itn.    P.Loss  N.Loss  UAS     NER P.  NER R.  NER F.  Tag %   Token %
    0       0.000   0.000   14.665  0.000   0.000   0.000   0.008   100.000 2173.6  0.0
    1       0.000   0.000   18.914  0.000   0.000   0.000   0.008   100.000 3440.2  0.0
    2       0.000   0.000   18.017  0.000   0.000   0.000   0.008   100.000 3299.7  0.0
    3       0.000   0.000   15.901  0.000   0.000   0.000   0.008   100.000 3209.7  0.0
    4       0.000   0.000   17.182  0.000   0.000   0.000   0.008   100.000 2955.9  0.0
    5       0.000   0.000   13.659  0.000   0.000   0.000   0.008   100.000 3250.5  0.0
    6       0.000   0.000   18.953  0.000   0.000   0.000   0.008   100.000 3134.8  0.0
    7       0.000   0.000   16.433  0.000   0.000   0.000   0.008   100.000 3237.7  0.0
    8       0.000   0.000   16.552  0.000   0.000   0.000   0.008   100.000 3055.8  0.0
    9       0.000   0.000   21.446  0.000   0.000   0.000   0.008   100.000 2721.5  0.0
    ....
```

## Your Environment

* Operating System: Windows-10-10.0.17134-SP0
* Python Version Used: 3.6.5
* spaCy Version Used: 2.0.11
* Environment Information: Anaconda

**Comment by ines** [comment]
Sorry for only getting to this now. The Indonesian language data has since been updated, so feel free to try again now. Also see the master thread in #3056 for everything around adding new models. I'm merging this issue with the master thread to keep things in one place.

The low UAS score is definitely suspicious – the model seems to not learn the parse at all. A common cause of this are problems in the data, e.g. incorrectly converted annotations. Did you have a look at the converted output and check if it all looks reasonable?
