### ISSUE TITLE
ValueError when adding multi-task objective

### ISSUE THREAD

**Issue by kevinrosenberg21** [explosion/spaCy#2381]
## How to reproduce the behaviour
```
def get_resume_section(i, words, tags, heads, labels, ents):
    if len(words) < 20:
        return 'short-doc'
    elif i == 0:
        return 'first-word'
    elif i < 10:
        return 'early-word'
    elif i < 20:
        return 'mid-word'
    elif i == len(words)-1:
        return 'last-word'
    else:
        return 'late-word'

TRAIN_DATA = make_train_data(dataset)
nlp = spacy.blank('es')

word_to_vec = Word2Vec.load(w2v_dir)
nlp = set_vocab(nlp, word_to_vec)
    
nlp.tokenizer = custom_tokenizer(nlp)

ner = nlp.create_pipe('ner')
ner.add_multitask_objective(get_resume_section)
ner = add_labels(ner, TRAIN_DATA, 'entities')
nlp.add_pipe(ner, first=True)

#Training the named entity recognizer
optimizer = nlp.begin_training()
for i in range(iterations):
    random.shuffle(TRAIN_DATA_NER)
    for data in TRAIN_DATA_NER:
        text = data[0]
        annotations = data[1]
        print("Updating")
        nlp.update([text], [annotations], sgd=optimizer)
```

## Info about spaCy

* **Python version:** 3.5.2
* **spaCy version:** 2.0.11
* **Also tried with versions:** 2.0.5, 2.0.6
* **Platform:** Linux-4.13.0-41-generic-x86_64-with-debian-stretch-sid
* **Models:** en, es

Hi everyone,

I've been trying to add a multi-task objective to my NER model so that I can include domain knowledge. I've been doing so based on [this](https://github.com/explosion/spaCy/blob/master/examples/training/ner_multitask_objective.py) example. The first thing I tried was to create my own function and add that as a multitask objective but it kept failing with the following error for the first update call:

`
ValueError: zero-size array to reduction operation maximum which has no identity
`

Eventually, I reduced my problem to the code you can find above, which uses the exact same function in the exact same order as in the example, but it keeps failing in the same line with the same message. I don't think it's a data problem because when I comment the add_multitask_objective line out the training program runs with no problem.

**Comment by kevinrosenberg21** [comment]
UPDATE: I've kept trying to get it to work but it hasn't. Could it have something to do with my training data? I've been using the simplified format of (text, entities:[(i_from, i_to, entity)]) because that's the only information I've got for my use case, whereas the example also has PoS and dependency information.

**Comment by jainaayush05** [comment]
Even I am stuck on the exact same issue. @ines @honnibal , can you please help?

**Comment by honnibal** [comment]
Sorry for not getting to this.

I've tested the example https://github.com/explosion/spaCy/blob/develop/examples/training/ner_multitask_objective.py with the latest nightly (v2.1.0a9), and it's working correctly. Please reopen this (or post a new issue) if you're having trouble with the new version.
