### ISSUE TITLE
Question: Why shuffle the pipeline during training?

### ISSUE THREAD

**Issue by BigstickCarpet** [explosion/spaCy#2382]
I was stepping through the source code to learn more about how model training works, and I noticed these lines in the `Language.update()` method:

https://github.com/explosion/spaCy/blob/d85494bfae583b47a5a88f09aa6933f95891497a/spacy/language.py#L421-L427

I don't understand why the `random.shuffle(pipes)` line is in there.  Isn't the order of the pipeline important?  [The docs](https://spacy.io/usage/processing-pipelines) say the following:

> Although you can mix and match pipeline components, their **order and combination** is usually important. Some components may require certain modifications on the `Doc` to process it. 

If a pipeline component relies on certain attributes being set by a previous component, then won't the `shuffle(pipes)` mess that up?

**Comment by syllog1sm** [comment]
This line currently doesn't matter. If you have models which share some of their weights, eg they all update the same vectors, it can help to shuffle the order.

**Comment by BigstickCarpet** [comment]
Thank you for the detailed explanation.  I didn't realize that updating a pipeline component is order-independent, whereas processing a document is order-dependent.  

Keep up the good work.  Thanks for creating and maintaining this project. 👍 🥇 💯
