### ISSUE TITLE
Can I just evaluate Tagger model?

### ISSUE THREAD

**Issue by felixganz** [explosion/spaCy#2384]
Hi.. I had make tagger model for Indonesian Language. Can I evaluate tagger model only?

**Comment by honnibal** [comment]
Sure. If you're using the `spacy train` command, just set `-P -N` flags on the command line (`--pipeline tagger` on `spacy-nightly` version). If you've got a script, you should be able to see how the evaluation works by looking at the code in `spacy/cli/train.py`.
