### ISSUE TITLE
displacy.serve no results

### ISSUE THREAD

**Issue by jackie2jet** [explosion/spaCy#2387]
```
import spacy
from spacy import displacy
nlp = spacy.load("en")
doc = nlp(u"UN,ICS,Greece,U.S.A.")
print(spacy.displacy.serve(doc, style="ent", page="true"))
```
+++++++++++++++++++++++++++++++++
Serving on port 5000...
    Using the 'ent' visualizer
+++++++++++++++++++++++++++++++++

this message keeps running yet nothing exported.
I closed the firewall and still can't find out the reason
sos please!

**Comment by ines** [comment]
`displacy.serve` will start a web server, so once it's running, you should be able to open http://localhost:5000 in your browser and see the visualization.

If you want to export the visualization instead, you can use `displacy.render`, which only renders the HTML without starting a server:

```python
print(spacy.displacy.render(doc, style="ent", page="true"))
```

You can find more details in the docs: https://spacy.io/usage/visualizers

If you don't see any entities at all, it means that the model hasn't recognised any.

By the way, for general usage questions, [StackOverflow](https://stackoverflow.com/tags/spacy) might be a better forum. If you tag it `spacy` and `python`, more people will see it and be able to help. We try to keep the GitHub issue tracker limited to bug reports, feature requests and everything related to the spaCy source and code base.

**Comment by jackie2jet** [comment]
I'm really sorry about that,I 'm a newbie and just start learning spay from scratch with rare outsider knowledge，So sorry again for my inappropriate questions in here.
Thanks for your time and reply!
