### ISSUE TITLE
to_disk() / from_disk() methods on nlp objects doesnt work properly

### ISSUE THREAD

**Issue by faizanzaroo** [explosion/spaCy#2389]
**Issue:**
I use a custom PhraseMatcher component which i add to the NLP object as a pipe. The object is then saved using the to_disk() method. When loading the object using from_disk() method , it doesnt work as expected. The custom PhraseMatcher object doesnt recognise entities at all. Either the object is not properly saved using to_disk() method or the from_disk() doestnt properly loads the object.

**Code Snippets:**
1. Saving to disk:
```
nlp = spacy.load('en_core_web_sm')
nlp.remove_pipe('ner')
phone_matcher = CustomNERTagger(nlp,[u"Nokia 1100",u"Nokia 6",u"Samsung 3210"],'MOBILE',"phone_matcher")
nlp.add_pipe(phone_matcher)
doc = nlp(u"My friend bought 3 Nokia 1100 and Nokia 6 phones from Reliance Digital Store.The phone was really bad")
print nlp.pipe_names
print doc.ents
nlp.to_disk("custom_tager")
```

2. Loading from disk:
```
nlp = spacy.blank('en').from_disk("custom_tager")
doc = nlp(u"I got a Nokia 6 phone from Reliance Digital Store")
print  doc.ents
```

**Environment:**
* **Python version:** 2.7.12
* **Platform:** Linux-4.13.0-43-generic-x86_64-with-Ubuntu-16.04-xenial
* **spaCy version:** 2.0.12.dev0

**Comment by ines** [comment]
We actually *just* had another issue on the same topic – see #2388 for my reply and more details.
