### ISSUE TITLE
Unintuitive out-of-memory error message

### ISSUE THREAD

**Issue by henningpeters** [explosion/spaCy#239]
Out-of-memory isn't properly handled, see #236.

Error reports include:

```
Error in `python': free(): invalid next size (normal): 0x000000000dfff920 ***
Aborted (core dumped)
```

```
Error in `python': free(): invalid pointer: 0x0000000005fff4a8 ***
```

**Comment by honnibal** [comment]
Thanks. Definitely agree that there's a problem here.

Likely candidates are the raw calls to `PyMem_Malloc` and `PyMem_Realloc` in `thinc`. Mostly memory allocation goes via the `cymem` library, which I believe is checking status codes correctly.
