### ISSUE TITLE
ImportError: No module named ar

### ISSUE THREAD

**Issue by NourShalabi** [explosion/spaCy#2391]
## How to reproduce the behaviour

import spacy
from spacy.lang.ar import Arabic

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named ar

## Info about spaCy

* **Python version:** 3.5.2
* **Models:** en, en_core_web_sm, en_core_web_md
* **Platform:** Linux-4.4.0-124-generic-x86_64-with-Ubuntu-16.04-xenial
* **spaCy version:** 2.0.11

**Comment by ines** [comment]
Hi! We already merged the Arabic pull request (#2314) but we haven't released a new version of spaCy yet. The latest version `v2.0.11` that you're using was published before Arabic was added, so the module doesn't exist yet.

If you want to try it right now, you can always build spaCy from source. On Linux and Python 3, this would look something like this:

```bash
python -m pip install -U pip venv              # update pip & virtualenv
git clone https://github.com/explosion/spaCy   # clone spaCy
cd spaCy                                       # navigate into directory

venv .env                                      # create environment in .env
source .env/bin/activate                       # activate virtual environment
export PYTHONPATH=`pwd`                        # set Python path to spaCy directory
pip install -r requirements.txt                # install all requirements
python setup.py build_ext --inplace            # compile spaCy
```

You can then run spaCy within that environment, and you should be able to use the Arabic tokenizer. For more details, see the [quickstart widget](https://spacy.io/usage/#section-quickstart) (and select "from source") or check out [this section](https://spacy.io/usage/#source) in the docs.
