### ISSUE TITLE
Regarding usage of Spacy

### ISSUE THREAD

**Issue by ironside007** [explosion/spaCy#2393]
Hey m new to Spacy.

I have a very basic question. Say, I am writing the training code for a dataset and okay i run it , so then what?
Like how do i predict the output(like the basic working of a model).

Please a step by step elaboration ,of incorporating a data set and then running it (where,python IDLE?) and then what code to run for the prediction thing, would really help me a lot.

Thanks!
Itachi

**Comment by ines** [comment]
Hi! Here are some resources to get you started:

* [spaCy 101 guide](https://spacy.io/usage/spacy-101): Everything you need to know about spaCy, how to get predictions from a statistical model and how to use the individual components
* [Training models](https://spacy.io/usage/training): How training works and examples of training the individual components and testing the trained model, step by step
* [Neural network model architecture](https://spacy.io/api/#nn-model): How spaCy's models are designed and some background on [Thinc](https://github.com/explosion/thinc), spaCy's machine learning library
* [spaCy's Entity Recognition Model](https://www.youtube.com/watch?v=sqDHBH9IjRU) (video, ~1h): Matt gives a detailed walkthrough and explains the details of spaCy's models.

For general usage questions, you might also want to check out [StackOverflow](https://stackoverflow.com/tags/spacy). If you post there and tag it `spacy` and `python`, more people will see it and hopefully be able to help. (We try to keep the issue tracker focused on bug reports and new features, so we're not always able to answer more general usage questions here. We always appreciate feedback on what's missing in the docs, though!)
