### ISSUE TITLE
SpaCy 2.0 incredibly slow compared to Spacy 1.9

### ISSUE THREAD

**Issue by sudarshan85** [explosion/spaCy#2394]
This seems to be a known issue https://github.com/explosion/spaCy/issues/1508. I'm making a post about this to see if there is a potential fix because this is severely hindering my choice to switch SpaCy 2.0. I quote my post from there:

> I believe I'm having this issue as well. Running 100,000 documents with an average length of about 8500 took 1hr 28m. The notes are stored in pandas dataframe and just iterate through them and yield it to nlp.pipe(). I disabled the tagger and ner but I kept the parser since I wanted to detect sentences. I ran this on a 64 core instance with n_threads=-1. Given this, does that sound reasonable performance?
> 
> I was also writing the parsed notes to disk so, I'm curious whether that io contributed to the slow performance.
> 
> EDIT:
> I concatenated about 1000 documents into a single string and ran that through nlp directly and the Jupyter kernel keeps restarting. It does not spit out any information on why its happening. I ran htop and its only using about 1/2 the RAM capacity (16G out of 31G).
> 
> EDIT-2:
> I ran my documents using SpaCy 1.9 as many people have done here, and I get about 9x speed up:
> 
> Number of documents, Spacy2, Spacy1.9
> 100,7,3
> 1000,59,6
> 10000,548,63
> 100000,5250,596
> 
> All time are in seconds. This doesn't provide a great incentive to use SpaCy 2.0 which is unfortunate because I'd really like to use the neural models that is present in SpaCy 2.0. Is there any fix for this yet

## Info about spaCy
* **spaCy version:** 1.9.0
* **Platform:** Linux-4.4.0-124-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.4
* **Installed models:** en_default

**Comment by honnibal** [comment]
It's really better that we keep the discussion in one place. We've been working on the speed issues; v2.1 makes things quite a bit better, especially by reducing the reliance on the system configuration.
