### ISSUE TITLE
while installing rasa_core there's an error with a 'Twisted file'

### ISSUE THREAD

**Issue by ironside007** [explosion/spaCy#2395]
![screenshot 62](https://user-images.githubusercontent.com/38071184/40718528-f75097a4-642d-11e8-9e6e-c5edd70df8e3.png)

 and i have visual build tools installed already

**Comment by ines** [comment]
Hmm, it looks like you still have problems with the compiler. Looking around on Google, many  [similar problems](https://bitbucket.org/zzzeek/sqlalchemy/issues/3761/pip-install-fails-in-virtualenv-on-windows) have been solved by installing the correct C++ build tools for the respective system. Maybe [some of these threads](https://www.google.com/search?q=Microsoft+Visual+C%2B%2B+Compiler+for+Python+3+site%3Astackoverflow.com) help?

I don't know what Twisted is – it not a direct dependency of spaCy or Rasa, as far as I can tell. For more specific problems with Rasa, you might want to talk to [Rasa](https://github.com/RasaHQ/rasa_core) directly.
