### ISSUE TITLE
get_lca_matrix is incorrect

### ISSUE THREAD

**Issue by slavi** [explosion/spaCy#2396]
@ramananbalakrishnan 

In spacy version 2.0.11

> s = u"He created a test for spacy"
> doc = nlp(s)
> doc.get_lca_matrix()[3][5]

Expected: 3
Actual: 1

This branch of the recursion is incorrect:

https://github.com/explosion/spaCy/blob/master/spacy/tokens/doc.pyx#L732

It assumes that if n1 and n2 are not adjacent, then LCA(n1, n2) = LCA(n1.head, n2.head).

This is generally not true: there are many counterexamples, the above one with 3 nodes in a chain is the simplest.

**Comment by honnibal** [comment]
Thanks for the report, and yes -- a pull request would be much appreciated!

**Comment by alvaroabascar** [comment]
I reimplemented the function to solve this issue, PR [here](https://github.com/explosion/spaCy/pull/3089).
