### ISSUE TITLE
Spacy on Spark runs on only one executor + Serialization error

### ISSUE THREAD

**Issue by sbjanani** [explosion/spaCy#2397]
I am running a spark job that uses Spacy to POS-tag and parse documents. I am using spaCy 2.0, so was expecting the model serialization to work. However, i was hit with a serialization error, when I tried to us a "map" to process my documents.

I was able to overcome this issue by using "mapPartitions" instead, and loading the model once per partition. However, I see that the job runs only on one executor instead of utilizing all executors available. 

This is a simple version of my spaCy method:
def simple(jobs):
    import spacy
    nlp = spacy.load(SparkFiles.get('en_core_web_lg-2.0.0'), disable=['ner'])
    titles = []
    for job in jobs:
         doc = nlp(job.description)
         verbs = ','.join([str(token) for token in doc if token.pos_ == 'VERB'])
         titles.append(Row(verbs = verbs))
    return titles

This is my snippet from spark, that calls this method:
spark.sql(select_sql).rdd.repartition(1000).mapPartitions(simple).toDF()

## My Environment
* Python Version Used: 3.2
* spaCy Version Used: 2.0
* Environment Information: Running on a Spark Yarn Cluster with 6g driver memory and 4g executor memory.

**Comment by honnibal** [comment]
The new `spacy-nightly` version has fixed the problems with pickle serialization, but you should also try to avoid serialising the model for good performance. This post by Holden Karau explains what to do: https://blog.dominodatalab.com/making-pyspark-work-spacy-overcoming-serialization-errors/
