### ISSUE TITLE
running Phrase_Matcher example: data details

### ISSUE THREAD

**Issue by ljakimagia** [explosion/spaCy#2401]
Hello,

I'm interested in running the Phrase_Matcher.py example. The documentation specifies : "The example expects a .bz2 file from the Reddit corpus, and a patterns file, formatted in jsonl as a sequence of entries like this: ... "

Could it be possible to have more infos, like a link to the Reddit Corpus to download or (better) small data files to quickly test the example (especially, for the patterns file) ? 

Thanks !

**Comment by ines** [comment]
Sure! Here's the link to the full archive on Pushshift – I'll also update the example to include the link: https://files.pushshift.io/reddit/

You can download individual months, some of which are quite small, so for testing, you could just pick one of the smaller, earlier months. (The full 2015 corpus is also [available on archive.org](https://archive.org/details/2015_reddit_comments_corpus).)

While the example is set up for a patterns file with `{"text": "foo"}` entries, you can also modify the code to read in a regular text file line-by-line instead or consume a list of terms from somewhere else. If you have a cool idea for a terminology list (that's available with a compatible license), we could definitely include a sample file in the examples.

**Comment by ljakimagia** [comment]
Thank you very much ! Everything works.

Did you try or do you think it could scale to UMLS ? (or at least, the size of it ?)
https://en.wikipedia.org/wiki/Unified_Medical_Language_System

Thanks again.
