### ISSUE TITLE
Scorer Output

### ISSUE THREAD

**Issue by evanlalo** [explosion/spaCy#2405]
I've created and trained a custom NER model. When I go to evaluate using Spacy Scorer I get this output:

```
{'uas': 0.0, 'las': 0.0, 'ents_p': 90.14084507042254, 'ents_r': 92.7536231884058, 'ents_f': 91.42857142857143, 'tags_acc': 0.0, 'token_acc': 100.0}

{'uas': 0.0, 'las': 0.0, 'ents_p': 91.12227805695142, 'ents_r': 93.47079037800687, 'ents_f': 92.28159457167091, 'tags_acc': 0.0, 'token_acc': 100.0}

{'uas': 0.0, 'las': 0.0, 'ents_p': 92.45614035087719, 'ents_r': 92.9453262786596, 'ents_f': 92.70008795074759, 'tags_acc': 0.0, 'token_acc': 100.0}

{'uas': 0.0, 'las': 0.0, 'ents_p': 94.5993031358885, 'ents_r': 94.93006993006993, 'ents_f': 94.76439790575917, 'tags_acc': 0.0, 'token_acc': 100.0}

{'uas': 0.0, 'las': 0.0, 'ents_p': 92.07920792079209, 'ents_r': 93.15525876460768, 'ents_f': 92.61410788381743, 'tags_acc': 0.0, 'token_acc': 100.0}
```

I am not able to find anywhere in your documentation that explains what the keys are which makes the function pretty unhelpful. Am I missing this content somewhere?

thanks,

**Comment by ines** [comment]
[StackOverflow was quicker](https://stackoverflow.com/questions/50644777/understanding-spacys-scorer-output):

> - UAS (Unlabelled Attachment Score) and LAS (Labelled Attachment Score) are standard metrics to evaluate dependency parsing. UAS is the proportion of tokens whose head has been correctly assigned, LAS is the proportion of tokens whose head has been correctly assigned with the right dependency label (subject, object, etc).
> - `ents_p`, `ents_r`, `ents_f` are the precision, recall and [fscore](https://en.wikipedia.org/wiki/Precision_and_recall) for the NER task.
> - `tags_acc` is the POS tagging accuracy.
> - `token_acc` seems to be the precision for token segmentation.

For more details, [this comment](https://linguistics.stackexchange.com/questions/6863/how-is-the-f1-score-computed-when-assessing-dependency-parsing/6895#6895) also has a nice summary of the evaluation metrics for dependency parsing.

You're right that we currently don't really list these explanations anyway. We currently only show quick tooltips in the [models directory](https://spacy.io/models/en). Maybe we could add a small section on evaluation to the [spaCy 101](https://spacy.io/usage/spacy-101) in the future 🙂
