### ISSUE TITLE
spaCy freezes on nlp("some input")

### ISSUE THREAD

**Issue by aburkov** [explosion/spaCy#2407]
I have a strange problem. I run a Flask webservice, it downloads web pages and applies some analysis to the text, including named entity extraction with spaCy. The spaCy related code works well on my laptop (mac), it also works on the server from the python console, but it freezes when it's called as part of the Flask application on the server.

## How to reproduce the behaviour
```
        nlp = spacy.load('en_core_web_sm')
        print "I test spacy nlp"
        doc = nlp(u"London is the capital of the Great Britain.")
        #more code
```
The part "#more code" is not executed. The process freezes right after "nlp(u"London is the capital of the Great Britain.")"

As I said, in python console it works. All other ML/NLP libraries work OK in both cases.

## Your Environment

* **Python version:** 2.7.12
* **Platform:** Linux-4.4.0-127-generic-x86_64-with-Ubuntu-16.04-xenial
* **spaCy version:** 2.0.7
* **Models:** en_core_web_sm

**Comment by honnibal** [comment]
Hmm. I haven't seen this problem before, but my best guess is that the web server is calling spaCy from a subprocess, and then somehow when numpy launches multiple threads, the threads are deadlocking. Could you try setting the environment variable `OPENMP_NUM_THREADS=1`, to check that the problem still occurs when only one thread is launched?

**Comment by verilyanton** [comment]
Exactly the same problem running spaCy with Django.
Adding `os.environ["OPENMP_NUM_THREADS"] = "1"` to manage.py gives no result

**Comment by honnibal** [comment]
This should now be resolved in the new `spacy-nightly` versions. Instead of relying on numpy, which called into linear algebra libraries which weren't necessarily thread-safe, we've now managed to package the Blis linear algebra routines into a standalone library. This library is fully thread-safe, preventing these problems.
