### ISSUE TITLE
Language features for Tagger?

### ISSUE THREAD

**Issue by mirfan899** [explosion/spaCy#2409]
Which features are being used for tagger? I came out to average perceptron by @honnibal which uses https://github.com/hankcs/AveragedPerceptronPython/blob/39f10fb7d7925d14f7a7501c6f2c7727a300904b/PerceptronTagger.py#L121
are these features are being used or somewhat related features for tagger? 

## Info about spaCy

* **spaCy version:** 2.0.12.dev0
* **Platform:** Darwin-17.2.0-x86_64-i386-64bit
* **Python version:** 3.6.2
* **Models:** en

**Comment by honnibal** [comment]
In v2 the model is a neural network, which mostly builds its own feature combinations --- we only have to tell it features for the individual tokens. We use the prefix, suffix, word-shape, and lower-cased form of the word for this. The tagger model is similar to the NER, described here: https://www.youtube.com/watch?v=sqDHBH9IjRU&t=2s
