### ISSUE TITLE
NER categories overwrite custom categories in matcher

### ISSUE THREAD

**Issue by savkov** [explosion/spaCy#241]
Hi,

thanks for sorting the last bug I reported. I have another one though (which may or may not be related). In the newest version entities that are in the gazetteer (e.g. Facebook)  cannot be overwritten by manually adding the same entity to a different class. The following code recognises _Facebook_ as _ORG_ rather than _SOCIAL_MEDIA_.

```python
import spacy.en
import spacy.matcher
from spacy.attrs import ORTH, TAG, LOWER, IS_ALPHA, FLAG63

patterns = [
    [{ORTH: 'Facebook'}],
    [{ORTH: 'FACEBOOK'}]
]

nlp = spacy.en.English(tagger=False, parser=False, load_vectors=False)

nlp.matcher.add('SOCIAL_MEDIA', 'SOCIAL_MEDIA', {}, patterns)

docs = nlp('Facebook is Blizzard now.')

for e in docs.ents:
    print(e.text, e.label_)
```

I realise that this is a bit of a weird situation, as the gazetteer file can be changed to avoid it. Just thought you should know.

**Comment by honnibal** [comment]
Hmm.

Probably the best solution is to create your own Matcher instance, with full control over what gazetteer entries you load. You can assign the object directly, or pass it to `English.__init__`:

    # Assign directly
    nlp = English()
    nlp.matcher = my_matcher()
    # Pass in __init__
    nlp = English(matcher=my_matcher())

I'll think about what we want to do for the conflicts you mention. Silently ignoring them might not be the right answer.
