### ISSUE TITLE
Install fails on cygwin with fenv/fenv.c : No such file or directory

### ISSUE THREAD

**Issue by sylwiaoz** [explosion/spaCy#2411]
Hello,
I'm trying to install spacy on cygwin but I'm getting the following error message:

In file included from thinc/linear/linear.cpp:541:0:
  /tmp/pip-install-fEfiJ3/thinc/include/numpy/ufuncobject.h:393:23: erreur fatale : fenv/fenv.c : No such file or directory
   #include "fenv/fenv.c"

Any idea how to solve this?

Thank you !

**Comment by sylwiaoz** [comment]
There seems to be a similar issue here: https://github.com/explosion/spaCy/issues/518

But the access the solution seems  locked...

**Comment by rhmccullough** [comment]
I have the same problem. Earlier warnings say to use #define to avoid outdated interface. This should be the default to match current Cygwin.

**Comment by sankarshan-bhat** [comment]
Even I am facing same issue!

**Comment by KoichiYasuoka** [comment]
I've just made pull request for `thinc` https://github.com/explosion/thinc/pull/115 , however, **All checks have failed**. Umm... Here I write tentative procedure to install spaCy on Cygwin (64bit).

1. Make sure your Cygwin (64bit) has following packages: `python37-devel` `python37-pip` `python37-cython` `python37-numpy` `gcc-g++` `git` `swig`.
2. Install `thinc` by:
```sh
$ cd /tmp
$ git clone -b patch-1 https://github.com/KoichiYasuoka/thinc
$ cd thinc
$ pip3.7 install -r requirements.txt
$ python3.7 setup.py install
```
3. Install spaCy by:
```sh
$ cd /tmp
$ git clone https://github.com/explosion/spaCy
$ cd spaCy
$ pip3.7 install -r requirements.txt
$ python3.7 setup.py install
```

**Comment by ines** [comment]
See https://github.com/explosion/thinc/pull/115!

**Comment by KoichiYasuoka** [comment]
Thank you for releasing spaCy 2.2.2! Now I can install spaCy on Cygwin64 with `python37-devel` `python37-pip` `python37-cython` `python37-numpy` `python37-wheel` `gcc-g++` `git` `swig`:
```sh
pip3.7 install 'spacy>=2.2.2' --no-build-isolation
```
