### ISSUE TITLE
Failed installation of spaCy on Windows with anaconda

### ISSUE THREAD

**Issue by kormilitzin** [explosion/spaCy#2427]
I'm trying to install spaCy with anaconda on a Windows Server. 

First I created a new environment (in anaconda prompt)

> conda create -n py36 python=3.6 anaconda

> activate  py36
> pip install -U spacy

and then I started receiving the folioing errors (quite a lot):

![image001](https://user-images.githubusercontent.com/20815939/41161899-27cf5992-6b2c-11e8-9e11-4374ef9a2816.png)

![image002](https://user-images.githubusercontent.com/20815939/41161915-3222de3c-6b2c-11e8-8de7-08fb8eebd119.png)
![image003](https://user-images.githubusercontent.com/20815939/41161918-34153bcc-6b2c-11e8-9429-f5361858d0f4.png)
![image004](https://user-images.githubusercontent.com/20815939/41161924-37f2a680-6b2c-11e8-9bc6-0615df856ad6.png)

Any ideas? Thanks!
 

## How to reproduce the problem

```bash
# copy-paste the error message here
```

## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by ines** [comment]
If you're installing spaCy via `pip` on Windows, you need a compiler (see the error message and the link to the Visual C++ Build Tools).

However, since you're using conda anyways, you could also just install spaCy from conda instead. The conda distribution ships the pre-built wheels, so you won't have to compile spaCy locally.

```bash
conda install -c conda-forge spacy
```

**Comment by kormilitzin** [comment]
Thanks a lot, it did actually work, but now, once spacy (with models) is installed,Spyder is broken. When I wanted to install spacy (through conda), it did ask me to downgrade some packages and after that spyder crashed:

![image001](https://user-images.githubusercontent.com/20815939/41228791-7580740e-6d71-11e8-8734-4d70d20207ed.png)

and when I tried to run Spyder, I got this:

![capture](https://user-images.githubusercontent.com/20815939/41228917-0021a498-6d72-11e8-9ee8-be0538220985.PNG)

**Comment by ines** [comment]
Merging this with your other isssue #2488!
