### ISSUE TITLE
PhraseMatcher entity identification only for 'O' tags

### ISSUE THREAD

**Issue by nipunsadvilkar** [explosion/spaCy#2435]
I have been following custom pipeline [docs](https://spacy.io/usage/processing-pipelines#custom-components) where it's said to use `PhraseMatcher` as a rule-based approach as part of a data collection process, to help you "bootstrap" a statistical model. Although I am using it to increase accuracy of my pretrained custom model.

My custom Model identifies: `PERSON`, `ORG`, `DATE`
and I have provided `terms=('Khan', 'Dar', 'Kapoor', 'Jackson')` as `PERSON` entity to `PhraseMatcher`. 

For following sentence:

`Khan academy is best education platform to get free, world-class education`

My Model is able to Identify `Khan academy` as `ORG`, which is good :), but since I've added PhraseMatcher `after='ner'` it is overriding `Khan` token with `Khan` as `PERSON` entity.

I wish to use `PhraseMatcher` for only `O` tags and not on already identified entities by NER model (in this case not on `Khan academy`).

Is their any functionality in spaCy or code I can tweak/write to get such results?

That would be of great help! Thanks.

**Comment by ines** [comment]
Sure! The [token attributes](https://spacy.io/api/token#attributes) let you get a token's `ent_type_` (e.g. `'ORG'` or `''` if not an entity) and `ent_iob_` value (`I`, `O` or `B`). 

So before you add the matched spans to your `doc.ents`, you could check that the span doesn't already contain other entities and that the tokens' entity types are all `O`. For example:

```python
for match_id, start, end in matches:
    span = doc[start:end]  # get the matched slice of the document
    has_no_entity = all(token.ent_iob_ == 'O' for token in span)
    if has_no_entitiy:
        # span contains no entities, so go ahead and add it 
        new_span = Span(doc, start, end, label=match_id)
        doc.ents = list(doc.ents) + [new_span]
```

You could also add more complex filtering rules here if you like. For example, maybe you only want to override *some* entities but not all of them, depending on the match and entity label. 

You could also use the ID of the match pattern to write filtering rules. The `match_id` is the hash value of the name of your match pattern (the first argument passed to `matcher.add()`). To get its string value, you can look it up in the `doc.vocab.strings`:

```python
for match_id, start, end in matches:
   string_id = doc.vocab.strings[match_id]  # 'PERSON' etc.
   if string_id == 'PERSON':
       # do something...
```

**Comment by nipunsadvilkar** [comment]
@ines : Thanks! Worked like a charm.
