### ISSUE TITLE
Difference between spaCy & dispaCy ?

### ISSUE THREAD

**Issue by nalepae** [explosion/spaCy#244]
**spaCy version :** 0.100.2

When I ask the question _Who is Barack Obama ?_ in spaCy and when I tag each of these words, I obtain the following result : _WP VBZ NNP NNP ._ 

When I ask the same question on dispaCy in your [spaCy website](https://spacy.io), I obtain the following result : _NOUN VERB NNP PUNCT_.

In spaCy, _Who_ is **WP**. ==> OK
In dispaCy, _Who_ is **NOUN**. ==> KO

I find too bad the result is incorrect on dispaCy whereas it is correct on Spacy ...

I think most of users (like me) will think that dispaCy is just a HMI of Spacy.

Some of them could be disappointed because the result on dispaCy is not correct and will maybe not download spaCy to try it and see the result is actually correct in spaCy !

Anyway, thanks for you work :-)

**Comment by honnibal** [comment]
Hey,

Thanks for the feedback. The subtle thing is that displaCy employs a few simplifications: it merges base noun phrases and entities, and displays POS tags using the coarse-grained `.pos` attribute. We figured the fine-grained `.tag` attribute would be a little less accessible to many users.

Future versions of displaCy will make this a little bit clearer.
