### ISSUE TITLE
lemmatization on 20Newsgroups

### ISSUE THREAD

**Issue by irisava** [explosion/spaCy#2446]
## How to reproduce the behaviour
I am using spacy lemmatizing on 20 Newsgroups dataset.  
However, I found an incoherent behavior:

```
def lemma_wo_spacy_stopwords(text, nlp): 
    nlp = nlp
    spacytext = nlp((text))
    for stopword in stopwords:
        nlp.vocab[stopword].is_stop = True
    lemmas = []
    lemmas = [token.lemma_ for token in spacytext if not (token.is_stop or token.is_punct) ]
    return ' '.join(lemmas)
```
 If I put the whole text, there is at least one word (here: Ideologies ) doesn't have correct results. Also there are some stopwords still there:

**before lemma:**
![text1](https://user-images.githubusercontent.com/40242384/41362606-0fd6b056-6f32-11e8-9150-39f76f5a3e0b.JPG)

**after lemma:**
![text](https://user-images.githubusercontent.com/40242384/41363880-5b4c3350-6f35-11e8-91ca-e2a5bdc1e5d2.JPG)

However, if I use the same function and only take some sentences in the text as input, I got the singular form for all "Ideologies", and less stopwords ('also', 'upon'...etc): 

**before lemma:**
"Ideologies also split, giving more to disagree upon, and may also lead to intolerance. So do you also oppose all ideologies?“"

**after lemma:**
"ideology split give disagree lead intolerance so oppose ideology".

## Your Environment

* Operating System: win10
* Python Version Used: 3.6.4 |Anaconda custom (64-bit)|
* spaCy Version Used: 2.0.11
* Environment Information: 

## Info about spaCy

* **spaCy version:** 2.0.11
* **Platform:** Windows-10-10.0.15063-SP0
* **Python version:** 3.6.4

**Comment by honnibal** [comment]
Sorry for not getting to this sooner. I think this was related to a data caching issue that should be fixed in v2.1. If the problem still occurs with the version on `spacy-nightly`, please reopen the issue (or report a new one).
