### ISSUE TITLE
Add support for Serbian cyrillic language in spaCy

### ISSUE THREAD

**Issue by sasastarcevic** [explosion/spaCy#2450]
Hi All,

I would like to add Serbian cyrillic in spaCy. Do we have someone who is working on this issue?

Serbian cyrillic: https://sr.wikipedia.org/sr/%D0%A1%D1%80%D0%BF%D1%81%D0%BA%D0%B0_%D1%9B%D0%B8%D1%80%D0%B8%D0%BB%D0%B8%D1%86%D0%B0

I have take a look into: https://spacy.io/usage/adding-languages#section-language-data  and code/ tests for languages:

- **Code:** https://github.com/explosion/spaCy/tree/master/spacy/lang

- **Tests:** https://github.com/explosion/spaCy/tree/master/spacy/tests/lang

I'm not python developer, but maybe i can try to create PR with initial code and tests for adding Serbian cyrillic in spaCy.

Br,
Sasa

**Comment by ines** [comment]
Merging this with the master thread in #3056!
