### ISSUE TITLE
dependency graph plot in displacy: all arcs are shown in forward direction

### ISSUE THREAD

**Issue by kaushikacharya** [explosion/spaCy#2452]
## How to reproduce the behaviour

Tried the same example as shown in [Navigating the parse tree](https://spacy.io/usage/linguistic-features#navigating)
i.e. 

> Autonomous cars shift insurance liability toward manufacturers

Dependency head for each of the tokens on printing is coming same as in the above link, but the dependency tree plot locally shows otherwise.
All the arcs between the words and their corresponding heads are always going forward(i.e. from left to right) even when the head is on the right side(where we expect it go from right to left).

This happens in both cases:
a) rendering in jupyter
    `displacy.render(doc, style='dep', jupyter=True)`
b) dumping into svg file.

I can see that there's an issue #945 where people have faced issues for some particular versions of spaCy, but in my case its the same version as mentioned in the above link.

## Info about spaCy

* **Python version:** 2.7.13
* **Platform:** Windows-7-6.1.7601-SP1
* **spaCy version:** 2.0.11
* **Models:** en

**Comment by ines** [comment]
Do you have a more specific example or a screenshot? Here's the visualisation I get using the `displacy` module (also see the [online demo](https://explosion.ai/demos/displacy?text=Autonomous%20cars%20shift%20insurance%20liability%20toward%20manufacturers&model=en_core_web_sm&cpu=0&cph=0)):

![bildschirmfoto 2018-06-14 um 11 56 39](https://user-images.githubusercontent.com/13643239/41405459-14eee2c8-6fca-11e8-97aa-633b8948b33f.png)

The head is always the root of the arrow, so "cars" points to "autonomous" and "shift" to "liability".

**Comment by kaushikacharya** [comment]
@ines

Attached: screenshot of the output in Windows 7 using python 2.7
As you can see if I print the heads of dependency tree are correct but the plot is showing arcs in wrong direction (actually all in forward direction).

Following are the commands used:
```
import pandas as pd
nlp = spacy.load('en_core_web_sm')
doc = nlp(u"Autonomous cars shift insurance liability toward manufacturers")
displacy.render(doc, style='dep', jupyter=True)
```

![image](https://user-images.githubusercontent.com/4562867/41413745-9d1c8f42-7001-11e8-9bec-e56c41a5e858.png)

**Comment by ines** [comment]
Thanks – that's strange! 🤔 There's definitely *something* wrong here – it also seems like there's a problem with the dependency labels, because they're displayed underneath the arcs and not on top of them. I'll see if I can reproduce this result and get to the bottom of this.

When you have a second, could you share the SVG markup that it generated for you and that has the same problem?

**Comment by kaushikacharya** [comment]
Here's the svg it generated:

`u'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="0" class="displacy" width="1275" height="398" style="max-width: none; height: 398px; color: #000000; background: #ffffff; font-family: Arial">\n<text class="displacy-token" fill="currentColor" text-anchor="middle" y="308">\n    <tspan class="displacy-word" fill="currentColor" x="50">Autonomous</tspan>\n    <tspan class="displacy-tag" dy="2em" fill="currentColor" x="50">ADJ</tspan>\n</text>\n\n<text class="displacy-token" fill="currentColor" text-anchor="middle" y="308">\n    <tspan class="displacy-word" fill="currentColor" x="225">cars</tspan>\n    <tspan class="displacy-tag" dy="2em" fill="currentColor" x="225">NOUN</tspan>\n</text>\n\n<text class="displacy-token" fill="currentColor" text-anchor="middle" y="308">\n    <tspan class="displacy-word" fill="currentColor" x="400">shift</tspan>\n    <tspan class="displacy-tag" dy="2em" fill="currentColor" x="400">VERB</tspan>\n</text>\n\n<text class="displacy-token" fill="currentColor" text-anchor="middle" y="308">\n    <tspan class="displacy-word" fill="currentColor" x="575">insurance</tspan>\n    <tspan class="displacy-tag" dy="2em" fill="currentColor" x="575">NOUN</tspan>\n</text>\n\n<text class="displacy-token" fill="currentColor" text-anchor="middle" y="308">\n    <tspan class="displacy-word" fill="currentColor" x="750">liability</tspan>\n    <tspan class="displacy-tag" dy="2em" fill="currentColor" x="750">NOUN</tspan>\n</text>\n\n<text class="displacy-token" fill="currentColor" text-anchor="middle" y="308">\n    <tspan class="displacy-word" fill="currentColor" x="925">toward</tspan>\n    <tspan class="displacy-tag" dy="2em" fill="currentColor" x="925">ADP</tspan>\n</text>\n\n<text class="displacy-token" fill="currentColor" text-anchor="middle" y="308">\n    <tspan class="displacy-word" fill="currentColor" x="1100">manufacturers</tspan>\n    <tspan class="displacy-tag" dy="2em" fill="currentColor" x="1100">NOUN</tspan>\n</text>\n\n<g class="displacy-arrow">\n    <path class="displacy-arc" id="arrow-0-0" stroke-width="2px" d="M70,263 C70,176 215,176 215,263" fill="none" stroke="currentColor"/>\n    <text dy="1.25em" style="font-size: 0.8em; letter-spacing: 1px">\n        <textPath xlink:href="#arrow-0-0" class="displacy-label" startOffset="50%" fill="currentColor" text-anchor="middle">amod</textPath>\n    </text>\n    <path class="displacy-arrowhead" d="M215,265 L223,253 207,253" fill="currentColor"/>\n</g>\n\n<g class="displacy-arrow">\n    <path class="displacy-arc" id="arrow-0-1" stroke-width="2px" d="M245,263 C245,176 390,176 390,263" fill="none" stroke="currentColor"/>\n    <text dy="1.25em" style="font-size: 0.8em; letter-spacing: 1px">\n        <textPath xlink:href="#arrow-0-1" class="displacy-label" startOffset="50%" fill="currentColor" text-anchor="middle">nsubj</textPath>\n    </text>\n    <path class="displacy-arrowhead" d="M390,265 L398,253 382,253" fill="currentColor"/>\n</g>\n\n<g class="displacy-arrow">\n    <path class="displacy-arc" id="arrow-0-2" stroke-width="2px" d="M595,263 C595,176 740,176 740,263" fill="none" stroke="currentColor"/>\n    <text dy="1.25em" style="font-size: 0.8em; letter-spacing: 1px">\n        <textPath xlink:href="#arrow-0-2" class="displacy-label" startOffset="50%" fill="currentColor" text-anchor="middle">compound</textPath>\n    </text>\n    <path class="displacy-arrowhead" d="M740,265 L748,253 732,253" fill="currentColor"/>\n</g>\n\n<g class="displacy-arrow">\n    <path class="displacy-arc" id="arrow-0-3" stroke-width="2px" d="M420,263 C420,88 745,88 745,263" fill="none" stroke="currentColor"/>\n    <text dy="1.25em" style="font-size: 0.8em; letter-spacing: 1px">\n        <textPath xlink:href="#arrow-0-3" class="displacy-label" startOffset="50%" fill="currentColor" text-anchor="middle">dobj</textPath>\n    </text>\n    <path class="displacy-arrowhead" d="M745,265 L753,253 737,253" fill="currentColor"/>\n</g>\n\n<g class="displacy-arrow">\n    <path class="displacy-arc" id="arrow-0-4" stroke-width="2px" d="M420,263 C420,1 925,1 925,263" fill="none" stroke="currentColor"/>\n    <text dy="1.25em" style="font-size: 0.8em; letter-spacing: 1px">\n        <textPath xlink:href="#arrow-0-4" class="displacy-label" startOffset="50%" fill="currentColor" text-anchor="middle">prep</textPath>\n    </text>\n    <path class="displacy-arrowhead" d="M925,265 L933,253 917,253" fill="currentColor"/>\n</g>\n\n<g class="displacy-arrow">\n    <path class="displacy-arc" id="arrow-0-5" stroke-width="2px" d="M945,263 C945,176 1090,176 1090,263" fill="none" stroke="currentColor"/>\n    <text dy="1.25em" style="font-size: 0.8em; letter-spacing: 1px">\n        <textPath xlink:href="#arrow-0-5" class="displacy-label" startOffset="50%" fill="currentColor" text-anchor="middle">pobj</textPath>\n    </text>\n    <path class="displacy-arrowhead" d="M1090,265 L1098,253 1082,253" fill="currentColor"/>\n</g>\n</svg>'`

using the commands
`
>>> doc = nlp(u"Autonomous cars shift insurance liability toward manufacturers")
>>> svg = spacy.displacy.render(doc, style="dep")
>>> from pathlib import Path
>>> import os
>>> output_path = Path(os.path.join("./", "sentence.svg"))
>>> output_path
WindowsPath('sentence.svg')
>>> output_path.open('w', encoding="utf-8").write(svg)
`

![sentence](https://user-images.githubusercontent.com/4562867/41450988-5247fa42-7088-11e8-8a0f-977ebd92b17d.png)

Here the dependency labels are displayed as in online demo i.e. just below the arcs. **But** the direction of arcs are not correct.

**Comment by kleinay** [comment]
I encounter the same problem. I'm trying to visualize my own graphs (manual=True), and also all the arcs are going to the right, without considering the 'dir' attribute in the JSON I give as input (the markup stays the same with 'left' and 'right' arcs). 
I managed to fix it on my local clone of spacy. I changed one line in /spacy/displacy/render.py (line 138, get_arrowhead function):
instead of:
`if direction is 'left':`
I wrote:
`if direction == 'left':`
This way it will also be true if 'dir' value is a str (and not unicode, as it is expecting since it's importing unicode_literals). After this change, the arrows direction indeed was changed to left where it was supposed to, and the problem was fixed.

If you can fix that, I think it might be the main source of the problem.

**Comment by ines** [comment]
@kleinay 

> This way it will also be true if 'dir' value is a str (and not unicode, as it is expecting since it's importing unicode_literals). After this change, the arrows direction indeed was changed to left where it was supposed to, and the problem was fixed.

Omg, yes, this makes lots of sense 🤦‍♀️ Thanks so much for getting to the bottom of this! (Can't believe I didn't catch that or even write this code in the first place, haha.)

Would you like to submit a PR with your fix?
