### ISSUE TITLE
Error while finding module specification for 'spacy.en.download' (ModuleNotFoundError: No module named 'spacy.en')

### ISSUE THREAD

**Issue by byorxyz** [explosion/spaCy#2456]
## How to reproduce the problem

I uninstalled Anaconda python 3.6 and reinstalled Anaconda and spacy but I'm getting errors like below.

```bash
aerin@aerin-HP-Z230-Tower-Workstation:~$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
>>> exit()
 
aerin@aerin-HP-Z230-Tower-Workstation:~$ python -m spacy.en.download/home/aerin/anaconda3/bin/python: Error while finding module specification for 'spacy.en.download' (ModuleNotFoundError: No module named 'spacy.en')


```

## Your Environment

```
aerin@aerin-HP-Z230-Tower-Workstation:~$ python -m spacy info --markdown
/home/aerin/anaconda3/bin/python: No module named spacy.__main__; 'spacy' is a package and cannot be directly executed
```

But I can import spacy in python 3.6 (by Anaconda)
I've been dealing with Spacy issues for last 6 hours. I hope someone can help before I lose my hope in this library.

* Operating System: Ubuntu 16.04
* Python Version Used: 3.6 Anaconda
* spaCy Version Used: 1.9
* Environment Information:

**Comment by ines** [comment]
Sorry if this has been frustrating! 😞 Could you post the command your ran to install spaCy, and can you check that you are installing the correct version from conda, i.e. [this one](https://anaconda.org/conda-forge/spacy)?

```bash
conda install -c conda-forge spacy
```

One possible explanation could be that somehow, Anaconda gave you an old version of spaCy.

> `ModuleNotFoundError: No module named 'spacy.en'`

The `spacy.en.download` command has been deprecated for a while now, so the correct way to download a model is definitely `python -m spacy download en` ([see here](https://spacy.io/usage/models#download)). 

If there's something weird going on in your environment and you can't run the CLI commands (but you have the right version of spaCy), you can always just [download the models manually](https://spacy.io/usage/models#download-pip). For example:

```bash
pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz --no-deps
```

The above command will do the same thing as `spacy download en` – it will install the small English model package called `en_core_web_sm` as a Python package in your environment. (I've also added `--no-deps` to tell pip to only install the model package and not try to install spaCy again and mess with your conda environment.) You should then be able to do the following:

```python
import spacy
nlp = spacy.load('en_core_web_sm')
```

**Comment by ines** [comment]
The error you posted in #2455 definitely seems strange. For some reason, it's suddenly looking for that file in `.env/lib/python2.7`, while all other modules are correctly loaded from your anaconda environment. See here:

```diff
    from ..scorer import Scorer
+  File "/home/aerin/anaconda3/lib/python3.6/site-packages/spacy/scorer.py", line 4, in <module>
    from .gold import tags_to_entities
-  File ".env/lib/python2.7/site-packages/cymem/cymem.pxd", line 1, in init spacy.gold (spacy/gold.cpp:23496)
ModuleNotFoundError: No module named 'cymem.cymem'
```

Maybe you do have a stale `.env` somewhere in your working directory? Alternatively, does 
`conda update --all` help? (Apparently, this sometimes works wonders when nothing else does – I have no idea why, though.)

**Comment by ines** [comment]
Merging this with #2514!
