### ISSUE TITLE
What is the match pattern syntax for 'one or more tokens'?

### ISSUE THREAD

**Issue by lukeskywalkre** [explosion/spaCy#2458]
Hello, I have a general question concerning the syntax for matcher patterns. What is the syntax for 'one or more tokens'? My best guess, `{'OP':'+'}` does not seem correct.

**Comment by ines** [comment]
At the moment, you do need another attribute on the token description that you want to repeat – e.g. `IS_ALPHA`. This is slightly inconsistent and something we probably want to change with the updated patterns API (see #1971). You also usually want to use specific boundaries for your pattern – for example, a token with text X plus one or more tokens in between plus a token with text Y.

[Here's an example](https://explosion.ai/demos/matcher?text=A%20match%20is%20a%20tool%20for%20starting%20a%20fire.&model=en_core_web_sm&pattern=%5B%7B%22id%22%3A0%2C%22attrs%22%3A%5B%7B%22name%22%3A%22ORTH%22%2C%22value%22%3A%22match%22%7D%5D%7D%2C%7B%22id%22%3A1%2C%22attrs%22%3A%5B%7B%22name%22%3A%22OP%22%2C%22value%22%3A%22%2B%22%7D%2C%7B%22name%22%3A%22IS_ALPHA%22%2C%22value%22%3Atrue%7D%5D%7D%2C%7B%22id%22%3A2%2C%22attrs%22%3A%5B%7B%22name%22%3A%22ORTH%22%2C%22value%22%3A%22fire%22%7D%5D%7D%5D) of a pattern matching two specific tokens and one or more tokens in between. (You can also play with the attributes in the demo and try different patterns on your text.)

**Comment by lukeskywalkre** [comment]
Thank you very much for this answer and the example pattern. This solves my problem.
