### ISSUE TITLE
Inconsistent matcher behaviour when using contiguous 0 or 1 quantifiers

### ISSUE THREAD

**Issue by benhachey** [explosion/spaCy#2464]
A few things..
1. Contiguous '?' quantifiers behave differently when using `{'OP': '?'}` versus `{IS_SPACE: False, 'OP': '?'}`:
   - `{'OP': '?'}` — ignores the rest of the pattern including later required expressions;
   - `{IS_SPACE: False, 'OP': '?'}` — equivalent to not using the quantifiers.
2. What I'm really trying to do is limit the length of wildcard matches without exploding the number of patterns. Any suggestion for building a pattern that matches "bla blaa", "bla bla blaaa" and "bla bla bla blaaa" without matching "bla bla bla bla blaaa"?

## How to reproduce the behaviour
```
from spacy.matcher import Matcher
from spacy.attrs import IS_SPACE, ORTH
import spacy

nlp = spacy.load('en_core_web_sm')

def test_pattern(pattern):
    matcher = Matcher(nlp.vocab)
    matcher.add(
        'TEST',
        None,
        pattern
    )
    print('PATTERN:', pattern, '\n')
    for i in range(1, 5):
        text = ' '.join(['bla'] * i) + ' blaaa'
        print('TEXT:', repr(text))
        print('MATCHES:', matcher(nlp(text)), '\n')
```

#### Pattern 1:
```
test_pattern([{ORTH: 'bla'}, {'OP': '?'}, {'OP': '?'}, {ORTH: 'blaaa'}])
```
gives:
```
PATTERN: [{65: 'bla'}, {'OP': '?'}, {'OP': '?'}, {65: 'blaaa'}] 

TEXT: 'bla blaaa'
MATCHES: [(3458773305017611411, 0, 1)] 

TEXT: 'bla bla blaaa'
MATCHES: [(3458773305017611411, 0, 1), (3458773305017611411, 1, 2)] 

TEXT: 'bla bla bla blaaa'
MATCHES: [(3458773305017611411, 0, 1), (3458773305017611411, 1, 2), (3458773305017611411, 2, 3)] 

TEXT: 'bla bla bla bla blaaa'
MATCHES: [(3458773305017611411, 0, 1), (3458773305017611411, 1, 2), (3458773305017611411, 2, 3), (3458773305017611411, 3, 4)] 
```

#### Pattern 2:
```
test_pattern([{ORTH: 'bla'}, {IS_SPACE: False, 'OP': '?'}, {IS_SPACE: False, 'OP': '?'}, {ORTH: 'blaaa'}])
```
gives:
```
PATTERN: [{65: 'bla'}, {6: False, 'OP': '?'}, {6: False, 'OP': '?'}, {65: 'blaaa'}] 

TEXT: 'bla blaaa'
MATCHES: [] 

TEXT: 'bla bla blaaa'
MATCHES: [] 

TEXT: 'bla bla bla blaaa'
MATCHES: [(1046765068364475028, 0, 4)] 

TEXT: 'bla bla bla bla blaaa'
MATCHES: [(1046765068364475028, 1, 5)] 
```

## Your Environment

* **spaCy version:** 2.0.11
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **Python version:** 3.6.4

**Comment by benhachey** [comment]
I'm not actually sure I understand expected quantifier behaviour here. Should there be three matches for the `bla bla bla bla blaaa` text starting at 1, 2 and 3 respectively?

We're exploring custom automata at the moment since we have matching requirements beyond terms. So I haven't had a chance to play with the new features on develop.

**Comment by honnibal** [comment]
Fixed! 🎉
