### ISSUE TITLE
Incorrect lemmatization for German at beginning of sentence

### ISSUE THREAD

**Issue by karelin** [explosion/spaCy#2465]
## How to reproduce the behaviour
>>> import spacy
>>> nlp = spacy.load('de')
>>> doc = nlp('Gemeinsame Erklärung von Singapur: Was genau steht drin?')
>>> [(t.lemma_, t.pos_) for t in doc][0]
[('Gemeinsame', 'ADJ')]

BUG: expected lemma is `gemeinsam`, this lemma is produced e.g. in sentence
> US-Präsident Donald Trump und Nordkoreas Machthaber Kim Jong Un haben bei ihrem Gipfel in Singapur eine gemeinsame Erklärung unterzeichnet.

Note, in contrast with #2166, the POS tag is correct (for both sentences).

## Info about spaCy

* **spaCy version:** 2.0.11
* **Platform:** Windows-10-10.0.17134-SP0
* **Python version:** 3.6.5
* **Models:** de, en, xx

**Comment by ines** [comment]
Thanks! This is likely related to the case-sensitivity and possibly an underlying bug in the lemmatizer (see #2368). Will investigate – we definitely want to sort this out for `v2.1.x`.

**Comment by ines** [comment]
Merging this with #2486!
