### ISSUE TITLE
ImportError `CXXABI_1.3.9' not found on Debian Jessie

### ISSUE THREAD

**Issue by jesperromers** [explosion/spaCy#2467]
## Problem
We run spaCy inside Docker containers which run Debian Jessie. Recently we tried re-building our docker image, and could not start our application anymore, due to missing symbols inside `libstdc++`. 

Error message:
```
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /*********/env/lib/python3.6/site-packages/spacy/gold.cpython-36m-x86_64-linux-gnu.so)
```

Apparently `CXXABI_1.3.9' requires GCC 5 or higher, and Jessie comes with GCC 4.
Point is that we pin our version of spaCy, and previously encountered no such problems.

Upgrading our Debian version to Stretch, which included GCC 6, solved the problem.

## How to reproduce the behaviour

* Run Debian Jessie
* Try to run Spacy 2.0.9

## Your Environment

* Operating System: Debian Jessie
* Python Version Used: 3.6.1
* spaCy Version Used: 2.0.9
* Environment Information:

**Comment by ines** [comment]
We've just released `v2.0.13`, which comes with pre-build binary wheels for spaCy. We're also working on releasing wheels for all of our dependencies so users will be able to install spaCy without needing a compiler.

Could you try again installing the latest version via the wheels? If the issue still persists, feel free to reopen.
