### ISSUE TITLE
How can I further analyse/parse matcher results? 

### ISSUE THREAD

**Issue by lukeskywalkre** [explosion/spaCy#2468]
Hello,

I have created a matcher in spacy, but I am having difficulties to further parse the results of the matcher. 

My matcher looks as follows: 
`matcher.add('ZeroToMany', None,
            [{'DEP':'nsubj', 'OP' : '+'}, {'LEMMA': 'can'}, {},{'DEP':'dobj', 'OP' : '+'}]`

`matches = matcher(doc) 
for match_id, start, end in matches:
    span = doc[start:end]
    print(span.text)
    `
Which produces an output like this: 

`customers can place orders`

Now, I would like to continue parsing the results, by classifying certain dependencies (e.g. produce a lists of tokens marked as nsubj, etc. for each result (based on their dependency in the original sentence). 

I have already written some code to do this for the sentences in the doc:

```
objects = ["nsubj", "nsubjpass"] #dependency parameters for objects
dependents1 = ["dobj"] #dependency parameters for first-order dependents
dependents2 = ["nmod", "iobj", "pobj"] #dependency parameters for second-order dependents

#identify possible objects and dependents for each sentence based on dependency parameters, for each sentence add row to dataframe  

a = []
for sent in doc.sents:
        obj_toks =  [tok for tok in sent if (tok.dep_ in objects) ]
        dep1_toks = [tok for tok in sent if (tok.dep_ in dependents1) ]
        dep2_toks = [tok for tok in sent if (tok.dep_ in dependents2) ]
        relation1 = [tok.head for tok in obj_toks]
        relation2 = [tok.head for tok in dep2_toks]
        a.append([obj_toks, relation1, dep1_toks, relation2, dep2_toks])
    

#create dataframe    

df = pd.DataFrame(a, columns=['obj', 'rel1', 'dep1', 'rel2', 'dep2'])

#'unstack' 'objects' column 

lst_col = 'obj'

df = pd.DataFrame({col:np.repeat(df[col].values, df[lst_col].str.len()) for col in df.columns.difference([lst_col])}).assign(**{lst_col:np.concatenate(df[lst_col].values)})[df.columns.tolist()]

print(df)

```
Now I would like to recycle this code to further parse/classify the results of my matcher output. The problem is that the output of the matcher is a span-element, which obviously differs from a sentence. Any ideas on how I might proceed so that the output of my Matcher becomes compatible with the code above? Converting the results back to entire sentences (e.g. by using span.sent) is not an option, as I am only interested in the specific fragments retrieved by the matcher. 

Any ideas on how to proceed with this? 

Many thanks

**Comment by ines** [comment]
See [StackOverflow](https://stackoverflow.com/questions/50946778/parsing-the-results-of-a-spacy-rule-based-matcher):

> From an API perspective, the sentences in `doc.sents` are also just `Span` object. So you can use the same code you ran on a `sent` on the `doc[start:end]` spans produced by your matcher. The oniy limitation here is that you'll only be able to extract token attributes etc. from within the matched span – but it sounds like that's exactly what you want to do, right?

**Comment by lukeskywalkre** [comment]
Hello,

Thank you, this worked as expected!
