### ISSUE TITLE
Inaccurate dependency tree on multiple nouns sentence

### ISSUE THREAD

**Issue by moshest** [explosion/spaCy#2471]
## How to reproduce the behaviour

The following text parsed with [wrong relation dependencies](https://explosion.ai/demos/displacy?text=by%20mainstream%20and%20mass%20market%20vehicles&model=en_core_web_sm&cpu=0&cph=0):

> "by mainstream and mass market vehicles"

Although this version [parsed currently](https://explosion.ai/demos/displacy?text=mainstream%20and%20mass%20market%20vehicles&model=en_core_web_sm&cpu=0&cph=0):

> "mainstream and mass market vehicles"

Why this is happens and how can we prevent it?
## Your Environment

DisplaCy: https://explosion.ai/demos/displacy

**Comment by ines** [comment]
Merging this with #3052. We've now added a master thread for incorrect predictions and related reports – see the issue for more details.
