### ISSUE TITLE
How to merge words split by hyphen?

### ISSUE THREAD

**Issue by dkulagin** [explosion/spaCy#2476]
When processing a text spaCy also splits whole words containing hyphens:

```
import spacy

nlp = spacy.load('en_core_web_sm')
doc = nlp(u'in the pre-primary education')

for token in doc:
    print(token.text, token.lemma_, token.pos_, token.tag_, token.dep_,
          token.shape_, token.is_alpha, token.is_stop, token.i, token.head.i,
          token.ent_type_ if token.ent_type_ else "-", token.ent_iob_)

in in ADP IN ROOT xx True True 0 0 - O
the the DET DT det xxx True True 1 5 - O
(!) pre pre ADJ AFX amod xxx True False 2 4 - O
(!) - - PUNCT HYPH punct - False False 3 4 - O
(!) primary primary ADJ JJ amod xxxx True False 4 5 - O
education education NOUN NN pobj xxxx True False 5 0 - O
```
It's definetely an overkill for my particular task. Is there a way to implode such words into a single token?

## Info about spaCy

* **spaCy version:** 2.0.11
* **Platform:** Linux-4.13.0-45-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.5

**Comment by ines** [comment]
One option would be to [use custom tokenization rules](https://spacy.io/usage/linguistic-features#native-tokenizers) and tell spaCy *not* to split on hyphens in this case. But doing that might actually be even more overkill for you use case.

If there's a relatively well-defined category of tokens you want to merge back together, you could use the `Matcher` to find them and call `Span.merge()` to merge them into one token. [Here's a similar question](https://stackoverflow.com/a/50775597/6400719) I answered on StackOverflow the other day, which shows an example in more detail.

[`Span.merge`](https://spacy.io/api/span#merge) also lets you overwrite attributes like `lemma` (which, by default, are inherited from the root token of the phrase you're merging).   See [my comment here](https://github.com/explosion/spaCy/issues/2303#issuecomment-387787254) for an example of this, including some caveats and tips.
