### ISSUE TITLE
Confusing error when using Displacy with Span instead of Doc object.

### ISSUE THREAD

**Issue by ohenrik** [explosion/spaCy#2477]
I tried using Displacy, however i did not notice that i accidentally passed in a Span object in stead of a Doc object. 

The error i got was this:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-29-69085a7f22c5> in <module>()
      2 
      3 sent = list(post.content.sents)[0]
----> 4 html = displacy.render(sent, style='dep')
      5 display(HTML(html))

~/.pyenv/versions/3.6.5/envs/nudge-fe/lib/python3.6/site-packages/spacy/displacy/__init__.py in render(docs, style, page, minify, jupyter, options, manual)
     34     renderer, converter = factories[style]
     35     renderer = renderer(options=options)
---> 36     parsed = [converter(doc, options) for doc in docs] if not manual else docs
     37     _html['parsed'] = renderer.render(parsed, page=page, minify=minify).strip()
     38     html = _html['parsed']

~/.pyenv/versions/3.6.5/envs/nudge-fe/lib/python3.6/site-packages/spacy/displacy/__init__.py in <listcomp>(.0)
     34     renderer, converter = factories[style]
     35     renderer = renderer(options=options)
---> 36     parsed = [converter(doc, options) for doc in docs] if not manual else docs
     37     _html['parsed'] = renderer.render(parsed, page=page, minify=minify).strip()
     38     html = _html['parsed']

~/.pyenv/versions/3.6.5/envs/nudge-fe/lib/python3.6/site-packages/spacy/displacy/__init__.py in parse_deps(orig_doc, options)
     84     RETURNS (dict): Generated dependency parse keyed by words and arcs.
     85     """
---> 86     doc = Doc(orig_doc.vocab).from_bytes(orig_doc.to_bytes())
     87     if not doc.is_parsed:
     88         user_warning(Warnings.W005)

AttributeError: 'spacy.tokens.token.Token' object has no attribute 'to_bytes'
```
My code: 
```
from IPython.core.display import display, HTML

sent = list(post.content.sents)[0]
html = displacy.render(sent, style='dep')
display(HTML(html))
```

I needed to change `sent` to `sent.as_doc()`. This can ether be mentioned in the doc or Spacy should give a better error message when passing in Spans to Displacy.

## Which page or section is this issue related to?
https://spacy.io/usage/visualizers

**Comment by ines** [comment]
Thanks, good point! I think that calling `span.as_doc()` by default would be fine, because this is almost always what a user wants to accomplish if they pass a `Span` object to `displacy`. So we could do something like this:

```python
if not isinstance(obj, Span) and not isinstance(obj, Doc):
    raise ValueError("Need Span or Doc!")  # TODO: proper error
if isinstance(obj, Span):
    obj = obj.as_doc()
# etc...
```

Feel free to submit a PR if you like. Otherwise, I'm also happy to implement this 🙂

**Comment by ohenrik** [comment]
I’m not sure where to add this logic. Is this a good place?:
https://github.com/explosion/spaCy/blob/master/spacy/displacy/__init__.py#L32

Combined with the existing logic on line 32 the code would be quite convoluted.

There should maybe be some more duck typing here, so that both span and doc elements behave similarly. 

By adding the method `to_bytes` to Span, both Span and Doc would work. We can then use a try /except block to catch everything else and raise a more meaningful error message. This would also allow elements derived from Doc or Span objects to be used by displacy.

I guess a quick hack of adding to_bytes to Span would be something like this:

```
to_bytes(self):
    return self.as_doc().to_bytes()
```

But it should maybe be implemented properly?

**Comment by ines** [comment]
The only problem I see with this solution is that a `Span` is only a *view* of the `Doc` and doesn't hold any data itself. So even if we implemented a method or workaround like this for displaCy, the input/output wouldn't be consistent: you'd serialize a `Span`, i.e. a view of the `Doc` with references to the original document, and get out a serialized `Doc` with the same content as the `Span`, but no references.

> Combined with the existing logic on line 32 the code would be quite convoluted.

Ah, I forgot that `displacy.render` also takes a list of `Doc` objects and even dictionaries if set to `manual=True`. I'll think about this some more, maybe we can find a clever solution here.

**Comment by ohenrik** [comment]
I need to look closer at how the Span object works, still learning Cython and C/C++, but making a Span a view of a portion of the Doc object seems clever :) Probably really efficient. Btw. if you know of any online courses or resources for Cython (beyond the basics), let me know, the only course i have found online is from O'reilly.

I can see that it might be problematic, but is it possible for the span object to construct the result of `to_bytes` by filtering the relevant references and building the bytes object it self, just like the Doc object?

I managed to simplify the if else statement a bit on line 32, so we have a temporary solution. Hope it looks ok. All tests related to this seems to pass, and handing a span element seems to work. Let me know if I should change something.
