### ISSUE TITLE
In nlp.meta['name']   for multiple named entity recognition how to put multiple entities? 

### ISSUE THREAD

**Issue by prashant334** [explosion/spaCy#2479]
@ines @honnibal 

Info about spaCy

spaCy version      2.0.11         
Location           /home/prashant/.local/lib/python3.6/site-packages/spacy
Platform           Linux-4.15.0-20-generic-x86_64-with-Ubuntu-18.04-bionic
Python version     3.6.5          
Models            : en
suppose I want to extract 2 entities "**entity1**" and "**entity2**" , in nlp.meta['name'] how to assign both?

**Comment by ines** [comment]
From #2470:
> I have used CRIME_LOCATION only in nlp.meta['name']. Another question is how to assign 2 entities for meta.

`nlp.meta['name']` is the *model name* – so for example, an English model with the name `cool_model` will become `en_cool_model` when you package it. So you shouldn't put the entity label in the model name at all. It's enough to add them to the entity recognizer via the `add_label` method. This section explains what the meta is used for, and how it works:
https://spacy.io/usage/training#models-generating

For a possible explanation of what might be the problem with your model, see my comment in #2470:
> Crime locations and victims aren't very well-defined, independent categories. They're mostly defined by the *relationships* and *dependencies* within the text. For example, if "California" refers to the US state, it's always a `GPE` entity. But is it a crime location? That really depends. Sometimes you can find that information in the same sentence. Sometimes not. That makes those labels very difficult to predict from machine learning point of view. A better strategy for training a model could be to focus on improving the predictions of `PERSON`, `GPE`, `LOC` etc. and then use the dependency parse (or a custom parser) to extract whether they refer to a crime location or a victim.

You might also want to look at the model training docs in general for more details and examples:
https://spacy.io/usage/training
