### ISSUE TITLE
deleting model data or a language class from primary memory

### ISSUE THREAD

**Issue by dchatterjee172** [explosion/spaCy#2480]
## Info about spaCy

* **spaCy version:** 2.0.5
* **Platform:** Linux-4.17.2-200.fc28.x86_64-x86_64-with-fedora-28-Twenty_Eight
* **Python version:** 3.6.5

```python
cls = spacy.util.get_lang_class("en")
nlp = cls()   
spacy_data_path = "/home/some_user/en_core_web_lg-2.0.0/en_core_web_lg/en_core_web_lg-2.0.0"   
for name in ['tagger']:   
	nlp.add_pipe(nlp.create_pipe(name))   
nlp.from_disk(spacy_data_path)
```
   
this will load the model data from given path.  After i am done with `nlp`, how can I remove the whole model from the primary memory?

```
del nlp   
gc.collect()
```
this does not work.

**Comment by honnibal** [comment]
Python doesn't immediately return memory it uses to the system, so even after the object is marked for deletion, you won't immediately see a reduction in memory usage, necessarily.

I believe there's a way to look at the live objects using the `gc` module. If you see the `nlp` object hanging around when it shouldn't be, i.e. if there's a memory leak, please let us know. Based on my experience I don't think there's a bug here, but if there is we're definitely keen to fix it.
