### ISSUE TITLE
Chinese support for spacy

### ISSUE THREAD

**Issue by farhaanbukhsh** [explosion/spaCy#2483]
I have been trying to train the machine for chinese language, I used https://github.com/UniversalDependencies/UD_Chinese-PUD/tree/master
and converted into the JSON format using converter and stored it.

Trained the model since there is no other set such such as dev or train I used the same set for both after all this done I imported and started using the model.

```
In [2]: import spacy
   ...: nlp = spacy.load('models/model-final/')


In [3]: doc = nlp(u"嘿，你怎麼樣？")
   ...: for chunk in doc.noun_chunks:
   ...:     print(chunk.text, chunk.root.text, chunk.root.dep_,
   ...:           chunk.root.head.text)
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.222 seconds.
Prefix dict has been built succesfully.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-730a638fc8fd> in <module>()
      1 doc = nlp(u"嘿，你怎麼樣？")
----> 2 for chunk in doc.noun_chunks:
      3     print(chunk.text, chunk.root.text, chunk.root.dep_,
      4           chunk.root.head.text)
      5 

doc.pyx in __get__()

TypeError: 'NoneType' object is not callable
```

## Your Environment

* Operating System: Linux
* Python Version Used: Venv 2.7 and 3.x
* spaCy Version Used: latest
* Environment Information:

**Comment by farhaanbukhsh** [comment]
Am I doing something wrong or what could be the issue?

**Comment by honnibal** [comment]
I'm not immediately sure what commands you've run. The best way to train a Chinese model at the moment is to use the `ud-train` command on the develop branch. See here: https://github.com/explosion/spaCy/issues/2011

**Comment by ines** [comment]
About the `doc.noun_chunks` error you're seeing: The noun chunks are implemented via language-specific rules – see [here](https://github.com/explosion/spaCy/blob/master/spacy/lang/en/syntax_iterators.py) for an example for English. Rules like this currently don't exist for Chinese. It should definitely fail more gracefully here, though – I'm pretty sure this has been fixed already for the upcoming version, but I'll double-check!

**Comment by farhaanbukhsh** [comment]
Hey @ines what if I want to impose the same rule for chinese how do I do it?

**Comment by ines** [comment]
You could either copy the syntax iterators over and implement them [the way it's done in English](https://github.com/explosion/spaCy/blob/master/spacy/lang/en/__init__.py#L36), or you could just call the English `noun_chunks` function on your Chinese `doc`:

```python
from spacy.lang.en.syntax_iterators import noun_chunks

doc = nlp(u"嘿，你怎麼樣？")
chunks = noun_chunks(doc) 
```

Not sure if this all works as expected, though, and if the label scheme matches etc.

**Comment by farhaanbukhsh** [comment]
I am getting an empty list for all the inputs I am giving, can you guide me on how to do write one, I am not a native chinese speaker.

**Comment by farhaanbukhsh** [comment]
Hey I am using a Universal Dependency Chinese Corpora, will the label scheme be still different?

**Comment by farhaanbukhsh** [comment]
also if not that which language comes closes to it :smile:

**Comment by farhaanbukhsh** [comment]
hey @ines any take on this? Sorry to disturb you :smile:

**Comment by farhaanbukhsh** [comment]
hey I would love to work on this feature.

**Comment by howl-anderson** [comment]
Since the maintainer is very busy and I am also working on Chinese feature, I'd like to help you with this issue, I will work on it later and try to give you a solution. @farhaanbukhsh

**Comment by farhaanbukhsh** [comment]
@howl-anderson can we collaborate on it? It will be really awesome if we can

**Comment by howl-anderson** [comment]
@farhaanbukhsh I am currently working on https://github.com/howl-anderson/Chinese_models_for_SpaCy

**Comment by ines** [comment]
Merging this with the master thread in #3056!
