### ISSUE TITLE
Semantic Named Entity Recognition

### ISSUE THREAD

**Issue by jainaayush05** [explosion/spaCy#2487]
Hi,

I see that github issues are also being used for asking help and questions, so I hope it's okay to submit here. I am new to Spacy and have a couple of questions regarding NER. I am trying to build a semantic NER that takes contextual information into account.

1. Does NER benefits from other pipeline components like POS tagger and Dependency parser? I've read on SpaCy docs that NER, Tagger and Parser share the same CNN layer. So, does this mean that if my pipline looks like tagger > parser > ner, then the output of tagger will be automatically used for parser and output of parser will be used in ner? I am trying to create a semantic ner along the lines of sense2vec. 

2. Also, is it possible to get the top layer output of TextCategorizer instead of softmax outputs? I wish to use TextCategorizer as a feature generator rather than a classifier.

**Comment by jainaayush05** [comment]
After diving deeper into the documentation and other StackOverflow questions - It seems like Tagger, Parser and NER just share the CNN Layer, and do not utilize the output of one pipeline in other. I might be wrong about this - @ines @honnibal can you kindly confirm my assumption?

**Comment by honnibal** [comment]
@jainaayush05 Some of the information on StackOverflow is out of date --- sorry this is a bit confusing!

The tagger, parser and NER are currently quite independent. The NER does take advantage of the sentence boundaries inserted by the parser, but this isn't so critical. Overall you should be able to mix and match the components, or run one component without the others.

> Also, is it possible to get the top layer output of TextCategorizer instead of softmax outputs? I wish to use TextCategorizer as a feature generator rather than a classifier.

There's no public API for that at the moment, although I agree it'd be useful. You can have a look at how the model is built in `spacy/_ml.py`, in the `build_text_classifier` function. What we need to do is pop the last layer, the `logistic` function. It might be as simple as `textcat.model._layers.pop()`, but I'm not 100% sure.

**Comment by jainaayush05** [comment]
Thanks for your help! Have you released any documentation for the architecture of the various components? I have gone through [this](https://youtu.be/sqDHBH9IjRU) video and [architecture](https://spacy.io/api/) on the documentation page, but they talk about the overall model architecture. I am interested in knowing more about Neural Architecture for individual components like Tagger, Parser and NER.

I am also publishing a research paper on `Semantic and Hierarchical Classification and Tagging of E-Commerce Products using Natural Language Parser` and a lot of my work involved Spacy. What would be the best way to cite Spacy as a reference?

**Comment by jessecoleman** [comment]
I've been scouring the docs and source code, but this issue seems to get the closest to an answer to my question, so hopefully this is an appropriate place to ask. I'm using SpaCy to train a custom dependency parser to extract relationships between entities in my domain. Right now I'm following [this](https://spacy.io/usage/training#intent-parser) example to train my model, but I'm wondering if I could also train the POS tagger with custom entity classes in order to improve the parser. 

My question is, does the parser use the tags generated by the tagger as features in its decision-making? From the post above, it seems like it would.

> The tagger, parser and NER are currently quite independent.

**Comment by honnibal** [comment]
@jessecoleman No, the parser and NER don't currently use the POS tags. So, it wouldn't affect your model's performance if you repurposed those tags. Unfortunately we don't yet have a good way to add features to these models.
