### ISSUE TITLE
Can't install models / python problem (permission error)

### ISSUE THREAD

**Issue by kormilitzin** [explosion/spaCy#2488]
I'm trying to install spacy on windows 10 with Anaconda distribution, but have not luck so far.

I downloaded Anaconda 3 installation package (5.2), installed and all was fine. Then, in anaconda prompt, I create a virtual.env. and wanted to add spacy:

(base) > create -n nlp_py36_clone_0 python=3.6 anaconda
(base) > activate nlp_py36_clone_0
(nlp_py36_clone_0) > conda install -c condo-forge spacy
all worked fine, but when I wanted to test the package, by running python, I got the following error:

![screen shot 2018-06-28 at 3 00 15 pm](https://user-images.githubusercontent.com/20815939/42039459-4cc7b1d6-7ae5-11e8-8ed5-2eae4f439c5b.png)
 
(import numpy worked well)

Any ideas?

```bash
# copy-paste the error message here
```

## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by ines** [comment]
Hmm, that's interesting! So it looks like your user doesn't have permission to access the `pkg_resources` module? Here are some things you can try:

* Did you run the command as administrator? If not, this might fix it.
* Does setting the permissions on that directory manually (to read access) help?

**Comment by kormilitzin** [comment]
Hi ines, thanks. Actually, I'm the user and we are trying to set up spacy on anaconda on a remote windows server. Any ideas will be highly appreciated!

**Comment by ines** [comment]
Did you check the permissions on the server, and does the account you're using have admin privileges? And does it help to manually change the permissions on the directory it complains about (basically, [the Windows equivalent of `chmod` / `chown`](https://superuser.com/questions/106181/equivalent-of-chmod-to-change-file-permissions-in-windows))?
