### ISSUE TITLE
Issue with brown clusters with different versions of en_web_core_sm

### ISSUE THREAD

**Issue by oasis789** [explosion/spaCy#2489]
I came across some really strange behaviour that I can't get my head around.

When I am on spacy v1.9.0 and using the en_core_web_sm model v.1.2.0 I can retreive the brown clusters from a selection of text. With this setup, I get the following output with this snippet:

```
import spacy
nlp = spacy.load('en_core_web_sm')
doc = nlp('Hey there! Can you help me fix this?')
[(t.text, t.cluster) for t in doc]
Out[5]: 
[('Hey', 1726),
 ('there', 986),
 ('!', 0),
 ('Can', 702),
 ('you', 602),
 ('help', 309),
 ('me', 1898),
 ('fix', 3765),
 ('this', 63),
 ('?', 0)]
spacy.__version__
Out[6]: '1.9.0'
nlp.meta
Out[9]: 
{'author': 'Explosion AI',
 'description': 'Small English model for spaCy. Includes vocabulary, syntax, entities and word vectors (GloVe).',
 'email': 'contact@explosion.ai',
 'lang': 'en',
 'license': 'CC BY-SA 3.0',
 'name': 'core_web_sm',
 'spacy_version': '>=1.7.0,<2.0.0',
 'url': 'https://explosion.ai',
 'version': '1.2.0'}
```
This code is run with following environment
## Info about spaCy

* **spaCy version:** 1.9.0
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **Python version:** 3.6.1
* **Installed models:** en, en_core_web_sm, es_core_web_md

Now, if I switch to using Spacy 2.0 with the en_core_web_sm model v2.0.0 and run the snippet again, all of the clusters are 0:

```
In [1]: import spacy

In [2]: nlp = spacy.load('en_core_web_sm')

In [3]: doc = nlp('Hey there! Can you help me fix this?')

In [4]: [(t.text, t.cluster) for t in doc]
Out[4]:
[('Hey', 0),
 ('there', 0),
 ('!', 0),
 ('Can', 0),
 ('you', 0),
 ('help', 0),
 ('me', 0),
 ('fix', 0),
 ('this', 0),
 ('?', 0)]

In [5]: spacy.__version__
Out[5]: '2.0.11'

In [6]: nlp.meta
Out[6]:
{'lang': 'en',
 'pipeline': ['tagger', 'parser', 'ner'],
 'accuracy': {'token_acc': 99.8698372794,
  'ents_p': 84.9664503965,
  'ents_r': 85.6312524451,
  'uas': 91.7237657538,
  'tags_acc': 97.0403350292,
  'ents_f': 85.2975560875,
  'las': 89.800872413},
 'name': 'core_web_sm',
 'license': 'CC BY-SA 3.0',
 'author': 'Explosion AI',
 'url': 'https://explosion.ai',
 'vectors': {'width': 0, 'vectors': 0, 'keys': 0, 'name': None},
 'sources': ['OntoNotes 5', 'Common Crawl'],
 'version': '2.0.0',
 'spacy_version': '>=2.0.0a18',
 'parent_package': 'spacy',
 'speed': {'gpu': None, 'nwords': 291344, 'cpu': 5122.3040471407},
 'email': 'contact@explosion.ai',
 'description': 'English multi-task CNN trained on OntoNotes, with GloVe vectors trained on Common Crawl. Assigns word vectors, context-specific token vectors, POS tags, dependency parse and named entities.'}
```

This was run with the following environment:
## Info about spaCy

* **spaCy version:** 2.0.11
* **Platform:** Linux-4.4.0-1061-aws-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.5
* **Models:** en_core_web_sm

It seems as though for some reason with this specifc model version the brown clusters are no longer being assigned as they should be. Could you please look into the issue and see if there is a way to fix it.

**Comment by honnibal** [comment]
The `en_core_web_sm` model doesn't come with pre-computed vocabulary data, as shipping the vocabulary makes the model larger. You should use the `en_core_web_md` or `en_core_web_lg` to get the clusters, probabilities and word vectors.
