### ISSUE TITLE
How to make POS tagger work for russian language

### ISSUE THREAD

**Issue by HnustYm** [explosion/spaCy#2492]
In russian language the class variable tag_map is properly set, pymorphy2 provide detailed grammatical tags, but the following example doesn't work:

```
from spacy.lang.ru import Russian
sentences  = "Автономные автомобили переносят страховую ответственность на производителя"
ru = Russian()
tokens = ru(sentences)
print([(token.text, token.pos_,token.tag_)  for token in tokens])
```
print result:
[('Автономные', '', ''), ('автомобили', '', ''), ('переносят', '', ''), ('страховую', '', ''), ('ответственность', '', ''), ('на', '', ''), ('производителя', '', '')]

Information about environment:
spaCy version      2.0.11
Platform           Linux
Python version     3.6.2

**Comment by DuyguA** [comment]
Is Russian model has a  POS-tagger already?

**Comment by ines** [comment]
Merging this with the master thread in #3056!

**Comment by buriy** [comment]
@HnustYm you might take a look at https://github.com/buriy/spacy-ru
It supports 2 different options:
1) lemmatization -- based on pymorphy2 most popular lemma for the word
2) POS and Syntax tagging, trained on SyntaxNet, and then lemma induction based on predicted POS tag and pymorphy2.
The Russian language component included in Spacy has no models, but only a list of possible tags in tag_map .
