### ISSUE TITLE
Inconsistent Lemma for same sentence

### ISSUE THREAD

**Issue by milanpatel** [explosion/spaCy#2493]
Spacy is giving Inconsistent lemma for same sentence if I pass same text twice to spacy.  In following code you can see spacy predict lemma **will** and **not** for the word **"won't"** after tokenization. Same sentence if I pass it again to spacy it gives me lemma **wo** and **n't**.
Example.
--Code:
import spacy
nlp = spacy.load('en')
response = "Many high school students may agree with later start times, many won't."
doc = nlp(response)
print([token.lemma_ for token in doc])
doc = nlp(response)
print([token.lemma_ for token in doc])

--Output
['many', 'high', 'school', 'student', 'may', 'agree', 'with', 'later', 'start', 'time', ',', 'many', **'will', 'not'**, '.']
['many', 'high', 'school', 'student', 'may', 'agree', 'with', 'later', 'start', 'time', ',', 'many', **'wo', "n't"**, '.']

## Environment
* **spaCy version:** 1.9.0
* **Platform:** Windows-10-10.0.14393-SP0
* **Python version:** 3.6.0
* **Installed models:** en, en-1.1.0, en_core_web_md, en_glove_cc_300_1m_vectors-1.0.0, __cache__

**Comment by DuyguA** [comment]
I was unable to produce the result neither with Python2 nor with Pyton3.

Here is my system:

```
Python version     2.7.5          
    Platform           Linux-3.10.
    spaCy version      2.0.6          
    Models             de, en  
```


Would it be possible to upgrade to spacy2.0 and give the results again?

**Comment by ines** [comment]
It's possible that this is related to #1387, which was fixed in `v1.10` (if you want to stay on spaCy v1). Your example also seems to work as expected in spaCy v2 (if you're ready to upgrade).

**Comment by milanpatel** [comment]
I tested this issue is fixed in latest version of spacy but I am not sure if I can upgrade that easily. I rely on SPACY vocab for something and latest version has different vocab length.

**Comment by ines** [comment]
Did you test it with `v1.10.1` as well? Because this version will definitely be compatible with your current version, `v1.9.0`. It's possible that the issue you describe is the same as #1693, though, which seems to also occur in `v1.10.x`.

The vocab in spaCy v2 now uses [hashes instead of integer IDs](https://spacy.io/usage/spacy-101#vocab), so the IDs are not cross-compatible. (On the plus side, this won't be a problem going forward as of v2, because the hashes are always the same across models.)

**Comment by milanpatel** [comment]
Finally I upgraded to latest version of spacy 2.0.11 for fixing the issue.
