### ISSUE TITLE
Deep learning with keras Sentiment analysis

### ISSUE THREAD

**Issue by mihirpatel7** [explosion/spaCy#2501]
Deep learning with keras: 

   File "D:/Sentiment/datasets/DL_test_small.py", line 157, in evaluate
    for doc in nlp.pipe(texts, batch_size=1000, n_threads=4):
  File "C:\Python36\lib\site-packages\spacy\language.py", line 558, in pipe
    for name, proc in self.pipeline:
TypeError: 'Tagger' object is not iterable

## Your Environment

* Operating System: windows 10
* Python Version Used: 3.6
* spaCy Version Used: 2.0.11
* Environment Information:

**Comment by danielcanueto** [comment]
I have the same issue when evaluating the results.

**Comment by ines** [comment]
Merging this with #2758.
