### ISSUE TITLE
Wrong POS and tag when training a language model

### ISSUE THREAD

**Issue by katarkor** [explosion/spaCy#2503]
Hi,
I’m new to spaCy and I'm trying to train a language model for Norwegian. I follow the instructions on the website and use the “train” function from the terminal, but I end up with an uncomplete model. I train the model like this: 

```bash
python3 -m spacy train nb modelNDT UD_NDT_english/no_bokmaal-ud-train.json UD_NDT_english/no_bokmaal-ud-dev.json -n 5
```

make a package, install it and then load it:

```python
nlp2 = spacy.load('nb_unnamed')
doc2 = nlp2(u'Jeg liker små hunder, men det gjør ikke du.')
````

And that’s what I get when I print token.text, lemma_, pos_, tag_, dep_, shape_, is_alpha and is_stop:

```
Jeg Jeg X PRON nsubj Xxx True False
liker like X VERB ROOT xxxx True False
små liten X ADJ amod xxx True False
hunder hund X NOUN obj xxxx True False
, , X PUNCT punct , False False
men mene X CCONJ cc xxx True True
det det X PRON nsubj xxx True True
gjør gjøre X VERB conj xxxx True True
ikke ikke X PART advmod xxxx True True
du du X PRON nsubj xx True True
. . X PUNCT punct . False False
```

The POS column is always X and tag column seems to contain POS instead of tag, so I’m wondering if Spacy somehow can’t find the tag map while training the model? If I on the other hand just load a blank ‘nb’ model like this:

```python
nlp_nb = spacy.blank('nb')
```

and then “train” the tagger:

```python
tagger_nb = Tagger(nlp_nb.vocab)
nlp_nb.pipeline.append(tagger_nb)
optimizer = tagger_nb.begin_training(pipeline=nlp_nb.pipeline)
processed = tagger_nb(doc_nb)
```

I get:
```
Jeg Jeg ADJ ADJ__Abbr=Yes  Xxx True False
liker like ADJ ADJ__Abbr=Yes  xxxx True False
små liten ADJ ADJ__Abbr=Yes  xxx True False
hunder hund ADJ ADJ__Abbr=Yes  xxxx True False
, , ADJ ADJ__Abbr=Yes  , False False
men mene ADJ ADJ__Abbr=Yes  xxx True True
det det ADJ ADJ__Abbr=Yes  xxx True True
gjør gjøre ADJ ADJ__Abbr=Yes  xxxx True True
ikke ikke ADJ ADJ__Abbr=Yes  xxxx True True
du du ADJ ADJ__Abbr=Yes  xx True True
. . ADJ ADJ__Abbr=Yes  . False False
```

I guess the POS and tag are the same for every word, because I didn’t provide any gold tuples, but I just wanted to check if I would get POS and tag in correct columns. Why is it different and what do I have to do in order for the “train” function from terminal to work?

## Your Environment

* Operating System: macOS High Sierra 10.13.5
* Python Version Used: 3.6.5
* spaCy Version Used: 2.0.11
* Environment Information:

**Comment by honnibal** [comment]
@katarkor I think you're right that it's probably an issue with the tag map.

Could you have a look at your data and check what the tag values are, then compare them with the keys to the dict at `spacy.lang.nb.Norwegian.Defaults.tag_map`?

The tagger will try to learn the `"tag"` values attached to the tokens in your training data, and then the `Morphology` class should be mapping these down to the `POS` values, using the tag map.

The `spacy convert` CLI command has an argument that specifies whether to merge morphological features with the coarse-grained POS tags, to make the fine-grained tags. If this is set differently than the `tag_map` is expecting, you might see the error you're experiencing.

**Comment by katarkor** [comment]
Thank you for your answer, it turned out I didn't notice the possibility of adding --morphology when converting from .conllu to .json
