### ISSUE TITLE
Spacy for python3.7

### ISSUE THREAD

**Issue by saurabhbh21** [explosion/spaCy#2505]
Is spacy available for python 3.7 and respective English model?

**Comment by ines** [comment]
Yes, spaCy should be fully compatible with Python 3.7. We haven't added the qualifier to the `setup.py` yet, because the latest version was released before 3.7 was available.

**Comment by saurabhbh21** [comment]
from spacy.util import load_model_from_init_py, get_model_meta
ImportError: cannot import name load_model_from_init_py

I'm getting above error while downloading en model of spacy
