### ISSUE TITLE
Does TextCategorizer class uses doc.vector or doc.tensor for text classification?

### ISSUE THREAD

**Issue by jainaayush05** [explosion/spaCy#2516]
I am trying to build a context and entities sensitive classification system and am considering using TextCategorizer for the same. I've read that `doc.tensor` is a container for dense vector representations, that gets updated with additional information as `doc` passes through a pipeline.

So my question is: does TextCategorizer uses `doc.vector ` or `doc.tensor` as an input to it's CNN layer?

## Your Environment
* **spaCy version:** 2.0.9
* **Platform:** Darwin-16.6.0-x86_64-i386-64bit
* **Python version:** 3.6.4
* **Models:** en_core_web_lg, en_core_web_sm

**Comment by honnibal** [comment]
If you use the `en_core_web_lg` model, the pre-trained word vectors are used as features in the model, on the way to calculating the vectors that are stored in `doc.tensor`. The `en_core_web_sm` model doesn't have pre-trained vectors.

**Comment by jainaayush05** [comment]
Perfect! Thanks!
