### ISSUE TITLE
issue with similarity results

### ISSUE THREAD

**Issue by mikkokotila** [explosion/spaCy#2517]
TL;DR 

Using a simple example, spacy returns a higher similarity for car and duck than car and vehicle. This same behavior is present across several similar (no pun intended) examples. 

Consider the following example code:

```
import spacy as sp
nlp = sp.load('en')

car = nlp('car')
vehicle = nlp('vehicle')
duck = nlp('duck')
bird = nlp('bird')

print("car and vehicle %f" % car.similarity(vehicle))
print("car and duck %f" % car.similarity(duck))
print("duck and bird %f" % duck.similarity(bird))
print("vehicle and bird %f" % vehicle.similarity(bird))
```

Which yields: 

```
car and vehicle 0.709964
car and duck 0.776765
duck and bird 0.640578
vehicle and bird 0.648628
```

Am I missing something?

**Comment by mikkokotila** [comment]
I'm looking more to this in the meantime: 

```
def similarity_check(texts):
    
    for text in itertools.combinations(texts, 2):
        a = nlp(text[0])
        b = nlp(text[1])
        sim = a.similarity(b)
        print("%s || %s: %f" % (a, b, sim))
        
texts = ['blue', 'red', 'green', 'angry', 'happy', 'Mike', 'Finland', 'computer', 'snow', 'Jack']
similarity_check(texts)
```
It seems that mostly the results **do make sense**.

**Comment by honnibal** [comment]
Agree that's surprising, and word2vec similarity results are often weirder and worse than the hype would have us believe. Interesting example, thanks!

**Comment by mikkokotila** [comment]
"word2vec similarity results are often weirder and worse than the hype would have us believe" 

👍
