### ISSUE TITLE
Get sentence from token

### ISSUE THREAD

**Issue by ohenrik** [explosion/spaCy#2518]
## Feature description
I cannot find any simple way of extracting the sentence associated with a token. Would it be possible to create a map on the Doc object to ask for the sentence for any given token. 

## Example

```
doc = nlp("Maybe this will work one day. Maybe it won’t")
token = doc[2]
assert token.text == "will"

sentence = doc.get_sent(token)
assert sentence.text == "Maybe this will work one day."
```

This would be really handy (at least for me) related to putting for example entity tokens in perspective of a sentence.

**Comment by ines** [comment]
Yes, you're right, the `Token` object currently doesn't expose that information. So we should probably add a `Token.sent`, for consistency with `Span.sent`.

In the meantime, you could use the following workaround and create a `Span` of only one token:

```python
doc = nlp("Maybe this will work one day. Maybe it won’t")
token_span = doc[2:3]  # this will be a Span object, but it will only contain one token
assert token_span.text == "will"

sentence = token_span.sent
assert sentence.text == "Maybe this will work one day."
# 🎉
```

It's not very elegant, but it works. You could also implement this as a custom attribute with a getter that takes the token, generates the "token span" from the parent `Doc` (`token.doc`) and the token index (`token.i`):

```python
from spacy.tokens import Token

def get_token_sent(token):
    token_span = token.doc[token.i:token.i+1]
    return token_span.sent

Token.set_extension('sent', getter=get_token_sent)

doc = nlp("Maybe this will work one day. Maybe it won’t")
sentence = doc[2]._.sent
assert sentence.text == "Maybe this will work one day."
# 🎉
```
