### ISSUE TITLE
Installation problem with pip and Python 3.7

### ISSUE THREAD

**Issue by ashishsixt** [explosion/spaCy#2524]
I am new to Python. 
When i run following command `pip install -U spacy`. I am getting below error.

`
(my_env) AshishKumarsMBP:Environments ashishkumar$ pip install -U spacy
Collecting spacy
  Using cached https://files.pythonhosted.org/packages/3c/31/e60f88751e48851b002f78a35221d12300783d5a43d4ef12fbf10cca96c3/spacy-2.0.11.tar.gz
Requirement not upgraded as not directly required: numpy>=1.7 in ./my_env/lib/python3.7/site-packages (from spacy) (1.14.5)
Requirement not upgraded as not directly required: murmurhash<0.29,>=0.28 in ./my_env/lib/python3.7/site-packages (from spacy) (0.28.0)
Requirement not upgraded as not directly required: cymem<1.32,>=1.30 in ./my_env/lib/python3.7/site-packages (from spacy) (1.31.2)
Collecting preshed<2.0.0,>=1.0.0 (from spacy)
  Using cached https://files.pythonhosted.org/packages/1b/ac/7c17b1fd54b60972785b646d37da2826311cca70842c011c4ff84fbe95e0/preshed-1.0.0.tar.gz
Collecting thinc<6.11.0,>=6.10.1 (from spacy)
  Using cached https://files.pythonhosted.org/packages/55/fd/e9f36081e6f53699943381858848f3b4d759e0dd03c43b98807dde34c252/thinc-6.10.2.tar.gz
Collecting plac<1.0.0,>=0.9.6 (from spacy)
  Using cached https://files.pythonhosted.org/packages/9e/9b/62c60d2f5bc135d2aa1d8c8a86aaf84edb719a59c7f11a4316259e61a298/plac-0.9.6-py2.py3-none-any.whl
Collecting pathlib (from spacy)
  Using cached https://files.pythonhosted.org/packages/ac/aa/9b065a76b9af472437a0059f77e8f962fe350438b927cb80184c32f075eb/pathlib-1.0.1.tar.gz
Collecting ujson>=1.35 (from spacy)
  Using cached https://files.pythonhosted.org/packages/16/c4/79f3409bc710559015464e5f49b9879430d8f87498ecdc335899732e5377/ujson-1.35.tar.gz
Collecting dill<0.3,>=0.2 (from spacy)
  Using cached https://files.pythonhosted.org/packages/6f/78/8b96476f4ae426db71c6e86a8e6a81407f015b34547e442291cd397b18f3/dill-0.2.8.2.tar.gz
Collecting regex==2017.4.5 (from spacy)
  Using cached https://files.pythonhosted.org/packages/36/62/c0c0d762ffd4ffaf39f372eb8561b8d491a11ace5a7884610424a8b40f95/regex-2017.04.05.tar.gz
Collecting wrapt (from thinc<6.11.0,>=6.10.1->spacy)
  Using cached https://files.pythonhosted.org/packages/a0/47/66897906448185fcb77fc3c2b1bc20ed0ecca81a0f2f88eda3fc5a34fc3d/wrapt-1.10.11.tar.gz
Collecting tqdm<5.0.0,>=4.10.0 (from thinc<6.11.0,>=6.10.1->spacy)
  Using cached https://files.pythonhosted.org/packages/93/24/6ab1df969db228aed36a648a8959d1027099ce45fad67532b9673d533318/tqdm-4.23.4-py2.py3-none-any.whl
Collecting cytoolz<0.9,>=0.8 (from thinc<6.11.0,>=6.10.1->spacy)
  Using cached https://files.pythonhosted.org/packages/0f/e6/ccc124714dcc1bd511e64ddafb4d5d20ada2533b92e3173a4cf09e0d0831/cytoolz-0.8.2.tar.gz
Collecting six<2.0.0,>=1.10.0 (from thinc<6.11.0,>=6.10.1->spacy)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting termcolor (from thinc<6.11.0,>=6.10.1->spacy)
  Using cached https://files.pythonhosted.org/packages/8a/48/a76be51647d0eb9f10e2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz
Collecting msgpack-python (from thinc<6.11.0,>=6.10.1->spacy)
  Using cached https://files.pythonhosted.org/packages/8a/20/6eca772d1a5830336f84aca1d8198e5a3f4715cd1c7fc36d3cc7f7185091/msgpack-python-0.5.6.tar.gz
Collecting msgpack-numpy==0.4.1 (from thinc<6.11.0,>=6.10.1->spacy)
  Using cached https://files.pythonhosted.org/packages/2e/43/393e30e2768b0357541ac95891f96b80ccc4d517e0dd2fa3042fc8926538/msgpack_numpy-0.4.1-py2.py3-none-any.whl
Collecting toolz>=0.8.0 (from cytoolz<0.9,>=0.8->thinc<6.11.0,>=6.10.1->spacy)
  Using cached https://files.pythonhosted.org/packages/14/d0/a73c15bbeda3d2e7b381a36afb0d9cd770a9f4adc5d1532691013ba881db/toolz-0.9.0.tar.gz
Installing collected packages: preshed, wrapt, tqdm, toolz, cytoolz, plac, six, dill, termcolor, pathlib, msgpack-python, msgpack-numpy, thinc, ujson, regex, spacy
  Running setup.py install for preshed ... error
    Complete output from command /Users/ashishkumar/python/Environments/my_env/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/88/wb0wcbhx6c98qzzc1b8_vnpc0000gp/T/pip-install-w06kw95b/preshed/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/88/wb0wcbhx6c98qzzc1b8_vnpc0000gp/T/pip-record-0lh4pd_l/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ashishkumar/python/Environments/my_env/include/site/python3.7/preshed:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.13-x86_64-3.7
    creating build/lib.macosx-10.13-x86_64-3.7/preshed
    copying preshed/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/preshed
    copying preshed/about.py -> build/lib.macosx-10.13-x86_64-3.7/preshed
    creating build/lib.macosx-10.13-x86_64-3.7/preshed/tests
    copying preshed/tests/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/preshed/tests
    copying preshed/tests/test_pop.py -> build/lib.macosx-10.13-x86_64-3.7/preshed/tests
    copying preshed/tests/test_counter.py -> build/lib.macosx-10.13-x86_64-3.7/preshed/tests
    copying preshed/tests/test_hashing.py -> build/lib.macosx-10.13-x86_64-3.7/preshed/tests
    copying preshed/counter.pyx -> build/lib.macosx-10.13-x86_64-3.7/preshed
    copying preshed/maps.pyx -> build/lib.macosx-10.13-x86_64-3.7/preshed
    copying preshed/maps.pxd -> build/lib.macosx-10.13-x86_64-3.7/preshed
    copying preshed/__init__.pxd -> build/lib.macosx-10.13-x86_64-3.7/preshed
    copying preshed/counter.pxd -> build/lib.macosx-10.13-x86_64-3.7/preshed
    running build_ext
    building 'preshed.maps' extension
    creating build/temp.macosx-10.13-x86_64-3.7
    creating build/temp.macosx-10.13-x86_64-3.7/preshed
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m -I/private/var/folders/88/wb0wcbhx6c98qzzc1b8_vnpc0000gp/T/pip-install-w06kw95b/preshed/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/Users/ashishkumar/python/Environments/my_env/include -I/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c preshed/maps.cpp -o build/temp.macosx-10.13-x86_64-3.7/preshed/maps.o -O3 -Wno-strict-prototypes -Wno-unused-function
    preshed/maps.cpp:1128:35: warning: comparison of integers of different signs: 'long' and 'size_t' (aka 'unsigned long') [-Wsign-compare]
          __pyx_t_1 = ((__pyx_v_power < __pyx_v_initial_size) != 0);
                        ~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~
    preshed/maps.cpp:1564:138: warning: code will never be executed [-Wunreachable-code]
            __pyx_t_1 = PyTuple_GET_ITEM(__pyx_t_2, __pyx_t_4); __Pyx_INCREF(__pyx_t_1); __pyx_t_4++; if (unlikely(0 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                                                                                                                             ^~~~~~~
    preshed/maps.cpp:1556:137: warning: code will never be executed [-Wunreachable-code]
            __pyx_t_1 = PyList_GET_ITEM(__pyx_t_2, __pyx_t_4); __Pyx_INCREF(__pyx_t_1); __pyx_t_4++; if (unlikely(0 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                                                                                                                            ^~~~~~~
    preshed/maps.cpp:1835:138: warning: code will never be executed [-Wunreachable-code]
            __pyx_t_1 = PyTuple_GET_ITEM(__pyx_t_2, __pyx_t_4); __Pyx_INCREF(__pyx_t_1); __pyx_t_4++; if (unlikely(0 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                                                                                                                             ^~~~~~~
    preshed/maps.cpp:1827:137: warning: code will never be executed [-Wunreachable-code]
            __pyx_t_1 = PyList_GET_ITEM(__pyx_t_2, __pyx_t_4); __Pyx_INCREF(__pyx_t_1); __pyx_t_4++; if (unlikely(0 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                                                                                                                            ^~~~~~~
    preshed/maps.cpp:2610:138: warning: code will never be executed [-Wunreachable-code]
            __pyx_t_1 = PyTuple_GET_ITEM(__pyx_t_2, __pyx_t_4); __Pyx_INCREF(__pyx_t_1); __pyx_t_4++; if (unlikely(0 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                                                                                                                             ^~~~~~~
    preshed/maps.cpp:2602:137: warning: code will never be executed [-Wunreachable-code]
            __pyx_t_1 = PyList_GET_ITEM(__pyx_t_2, __pyx_t_4); __Pyx_INCREF(__pyx_t_1); __pyx_t_4++; if (unlikely(0 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                                                                                                                            ^~~~~~~
    preshed/maps.cpp:3614:34: warning: comparison of integers of different signs: 'int' and 'const __pyx_t_7preshed_4maps_key_t' (aka 'const unsigned long long') [-Wsign-compare]
        __pyx_t_1 = (((__pyx_v_i[0]) < __pyx_v_map_->length) != 0);
                       ~~~~~~~~~~~~  ^ ~~~~~~~~~~~~~~~~~~~~
    preshed/maps.cpp:3701:32: warning: comparison of integers of different signs: 'int' and 'const __pyx_t_7preshed_4maps_key_t' (aka 'const unsigned long long') [-Wsign-compare]
      __pyx_t_1 = (((__pyx_v_i[0]) == __pyx_v_map_->length) != 0);
                     ~~~~~~~~~~~~  ^  ~~~~~~~~~~~~~~~~~~~~
    preshed/maps.cpp:3778:32: warning: comparison of integers of different signs: 'int' and 'unsigned long long' [-Wsign-compare]
      __pyx_t_1 = (((__pyx_v_i[0]) == (__pyx_v_map_->length + 1)) != 0);
                     ~~~~~~~~~~~~  ^   ~~~~~~~~~~~~~~~~~~~~~~~~
    preshed/maps.cpp:6642:24: error: no member named 'exc_type' in '_ts'
        tmp_type = tstate->exc_type;
                   ~~~~~~  ^
    preshed/maps.cpp:6643:25: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?
        tmp_value = tstate->exc_value;
                            ^~~~~~~~~
                            curexc_value
    /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here
        PyObject *curexc_value;
                  ^
    preshed/maps.cpp:6644:22: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?
        tmp_tb = tstate->exc_traceback;
                         ^~~~~~~~~~~~~
                         curexc_traceback
    /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here
        PyObject *curexc_traceback;
                  ^
    preshed/maps.cpp:6645:13: error: no member named 'exc_type' in '_ts'
        tstate->exc_type = *type;
        ~~~~~~  ^
    preshed/maps.cpp:6646:13: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?
        tstate->exc_value = *value;
                ^~~~~~~~~
                curexc_value
    /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here
        PyObject *curexc_value;
                  ^
    preshed/maps.cpp:6647:13: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?
        tstate->exc_traceback = *tb;
                ^~~~~~~~~~~~~
                curexc_traceback
    /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here
        PyObject *curexc_traceback;
                  ^
    10 warnings and 6 errors generated.
    error: command 'clang' failed with exit status 1
    
    ----------------------------------------
Command "/Users/ashishkumar/python/Environments/my_env/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/88/wb0wcbhx6c98qzzc1b8_vnpc0000gp/T/pip-install-w06kw95b/preshed/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/88/wb0wcbhx6c98qzzc1b8_vnpc0000gp/T/pip-record-0lh4pd_l/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ashishkumar/python/Environments/my_env/include/site/python3.7/preshed" failed with error code 1 in /private/var/folders/88/wb0wcbhx6c98qzzc1b8_vnpc0000gp/T/pip-install-w06kw95b/preshed/
(my_env) AshishKumarsMBP:Environments ashishkumar$ spacy

`

**Comment by ines** [comment]
Merging this with #2490!
