### ISSUE TITLE
POS tagger error, for pronouns, all the lemmas are shown as -PRON-.

### ISSUE THREAD

**Issue by topgetgithub** [explosion/spaCy#2530]
The latest version is installed.

The code is as below:

```
import spacy


nlp = spacy.load('en_core_web_sm')

strT = u'They are our friends.'

doc = nlp(strT)

for token in doc:
    print(token.text, token.lemma_, token.pos_, token.tag_, token.dep_,
          token.shape_, token.is_alpha, token.is_stop)

```

The output:

```
They -PRON- PRON PRP nsubj Xxxx True False
are be VERB VBP ROOT xxx True True
our -PRON- ADJ PRP$ poss xxx True True
friends friend NOUN NNS attr xxxx True False
. . PUNCT . punct . False False
```
Why the lemma of each token is always '-PRON-'?

**Comment by ines** [comment]
Hi! The `-PRON-` lemma is by design and is the default value for all pronouns. [See here](https://spacy.io/usage/#pron-lemma):

> This is in fact expected behaviour and not a bug. Unlike verbs and common nouns, there's no clear base form of a personal pronoun. Should the lemma of "me" be "I", or should we normalize person as well, giving "it" — or maybe "he"? spaCy's solution is to introduce a novel symbol, `-PRON-`, which is used as the lemma for all personal pronouns.

So in your example, only "they" and "our" are lemmatized to `-PRON-`. A cleaner way of looking at it would be like this:

```python
doc = nlp(u"They are our friends.")
print([token.lemma_ for token in doc])
# ['-PRON-', 'be', '-PRON-', 'friend', '.']
```
