### ISSUE TITLE
Are non-entity tokens used as negative examples or simply ignored?

### ISSUE THREAD

**Issue by ValentinCalomme** [explosion/spaCy#2531]
This is related to this stackoverflow question: https://stackoverflow.com/questions/49121064/feeding-spacy-ner-model-negative-examples-to-improve-training

In the BILUO tagging scheme, I understand that each token is either of the 5 tag and that the loss is dependent on this (I'm assuming that I instead of L is not as bad as B instead of L for instance)

I was wondering how the O-tokens are treated? Are they considered as negative examples? As in, would it be the same if I tagged every non-entity token with a dummy entity called "NOT_AN_ENTITY"?

If not, could tagging the other tokens as "NOT_AN_ENTITY" improve performance? Or is there a way to tweak the way the loss is computed? By perhaps putting a smaller/larger penalty on O-tokens to improve the recall/precision?

**Comment by honnibal** [comment]
The `O` tokens are negative examples, yes. The model suffers loss if it predicts a `B` or `U` tag when the answer was `O`.
