### ISSUE TITLE
Please Provide a Pre-Trained Deep LM for Use in Classification Tasks

### ISSUE THREAD

**Issue by simonhughes22** [explosion/spaCy#2534]
Pre-Trained deep language models are replacing word vectors (which are obviously a simpler form of LM) as a lower-level feature representation for NLP tasks, some of which are then fine tuned on a task specific dataset -   https://www.ere.net/textio-uncommon-launch-new-features/ . There will be a huge demand for pre-trained models to replaced word vectors for use in NLP tasks.

**Comment by honnibal** [comment]
Discussion of this enhancement proposal here: https://github.com/explosion/spaCy/issues/2342

In short, we've always hoped to have pre-training of the sequence-sensitive layers of the model, and I think the field as a whole was surprised that this proved to be such a technical challenge. Now that solutions have been progressing quickly, I hope we'll be able to provide pre-trained components that are efficient on commodity hardware for this purpose.
