### ISSUE TITLE
Many problems installing Spacy on Windows server core

### ISSUE THREAD

**Issue by jeffsaremi** [explosion/spaCy#2539]
Environment:
Windows Server Core 1907 running in docker
Python 3.5.0
No Conda

Command issued:
`pip install -U spacy`

Results (truncated):
Collecting spacy
  Downloading https://files.pythonhosted.org/packages/3c/31/e60f88751e48851b002f78a35221d12300783d5a43d4ef12fbf10cca96c3/spacy-2.0.11.tar.gz (17.6MB)
    100% |████████████████████████████████| 17.6MB 2.2MB/s
Requirement not upgraded as not directly required: numpy>=1.7 in c:\python\lib\site-packages (from spacy) (1.14.5)
Collecting murmurhash<0.29,>=0.28 (from spacy)
  Downloading https://files.pythonhosted.org/packages/5e/31/c8c1ecafa44db30579c8c457ac7a0f819e8b1dbc3e58308394fff5ff9ba7/murmurhash-0.28.0.tar.gz
Collecting cymem<1.32,>=1.30 (from spacy)
  Downloading https://files.pythonhosted.org/packages/d2/2d/eebfedb0f54598f0edc70efe63b9ff37d9397b465bfa290c33eaf6f3cba7/cymem-1.31.2-cp35-none-win_amd64.whl
Collecting preshed<2.0.0,>=1.0.0 (from spacy)
  Downloading 

... snip

  Downloading https://files.pythonhosted.org/packages/14/d0/a73c15bbeda3d2e7b381a36afb0d9cd770a9f4adc5d1532691013ba881db/toolz-0.9.0.tar.gz (45kB)
    100% |████████████████████████████████| 51kB ...
Building wheels for collected packages: spacy, murmurhash, preshed, thinc, pathlib, ujson, dill, wrapt, cytoolz, termcolor, msgpack-python, pyreadline, toolz
  Running setup.py bdist_wheel for spacy ... error
  Complete output from command c:\python\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\pip-install-k9h_yxgx\\spacy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\ContainerAdministrator\AppData\Local\Temp\pip-wheel-39ix3uxm --python-tag cp35:
 running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.5
  creating build\lib.win-amd64-3.5\spacy
  copying spacy\about.py -> build\lib.win-amd64-3.5\spacy
  ...
  creating build\lib.win-amd64-3.5\spacy\data
  copying spacy\data\__init__.py -> build\lib.win-amd64-3.5\spacy\data
  creating build\lib.win-amd64-3.5\spacy\displacy
  copying spacy\displacy\render.py -> build\lib.win-amd64-3.5\spacy\displacy
  copying spacy\displacy\templates.py -> build\lib.win-amd64-3.5\spacy\displacy
  copying spacy\displacy\__init__.py -> build\lib.win-amd64-3.5\spacy\displacy
  creating build\lib.win-amd64-3.5\spacy\lang
  copying spacy\lang\char_classes.py -> build\lib.win-amd64-3.5\spacy\lang
  copying spacy\lang\entity_rules.py -> build\lib.win-amd64-3.5\spacy\lang
  copying spacy\lang\lex_attrs.py -> build\lib.win-amd64-3.5\spacy\lang
  copying spacy\lang\norm_exceptions.py -> build\lib.win-amd64-3.5\spacy\lang
  copying spacy\lang\punctuation.py -> build\lib.win-amd64-3.5\spacy\lang
  copying spacy\lang\tag_map.py -> build\lib.win-amd64-3.5\spacy\lang
  copying spacy\lang\tokenizer_exceptions.py -> build\lib.win-amd64-3.5\spacy\lang
  copying spacy\lang\__init__.py -> build\lib.win-amd64-3.5\spacy\lang
  creating build\lib.win-amd64-3.5\spacy\syntax
  copying spacy\syntax\__init__.py -> build\lib.win-amd64-3.5\spacy\syntax
  creating build\lib.win-amd64-3.5\spacy\tests
  ...
  creating build\lib.win-amd64-3.5\spacy\lang\en\lemmatizer
  copying spacy\lang\en\lemmatizer\lookup.py -> build\lib.win-amd64-3.5\spacy\lang\en\lemmatizer
  ...
  creating build\lib.win-amd64-3.5\spacy\lang\sv\lemmatizer
  copying spacy\lang\sv\lemmatizer\lookup.py -> build\lib.win-amd64-3.5\spacy\lang\sv\lemmatizer
  copying spacy\lang\sv\lemmatizer\__init__.py -> build\lib.win-amd64-3.5\spacy\lang\sv\lemmatizer
  creating build\lib.win-amd64-3.5\spacy\tests\doc
  copying spacy\tests\doc\test_add_entities.py -> build\lib.win-amd64-3.5\spacy\tests\doc
  ...
  copying spacy\tests\pipeline\__init__.py -> build\lib.win-amd64-3.5\spacy\tests\pipeline
  creating build\lib.win-amd64-3.5\spacy\tests\regression
  copying spacy\tests\regression\test_issue118.py -> build\lib.win-amd64-3.5\spacy\tests\regression
  ...
  copying spacy\tests\regression\test_issue999.py -> build\lib.win-amd64-3.5\spacy\tests\regression
  copying spacy\tests\regression\__init__.py -> build\lib.win-amd64-3.5\spacy\tests\regression
  creating build\lib.win-amd64-3.5\spacy\tests\serialize
  copying spacy\tests\serialize\test_serialization.py -> build\lib.win-amd64-3.5\spacy\tests\serialize
  ...
  creating build\lib.win-amd64-3.5\spacy\tests\lang\tr
  copying spacy\tests\lang\tr\test_lemmatization.py -> build\lib.win-amd64-3.5\spacy\tests\lang\tr
  copying spacy\tests\lang\tr\__init__.py -> build\lib.win-amd64-3.5\spacy\tests\lang\tr
  copying spacy\attrs.pyx -> build\lib.win-amd64-3.5\spacy
  ...
  copying spacy\tokens\_retokenize.pyx -> build\lib.win-amd64-3.5\spacy\tokens
  copying spacy\tokens\doc.pxd -> build\lib.win-amd64-3.5\spacy\tokens
  copying spacy\tokens\span.pxd -> build\lib.win-amd64-3.5\spacy\tokens
  copying spacy\tokens\token.pxd -> build\lib.win-amd64-3.5\spacy\tokens
  copying spacy\tokens\__init__.pxd -> build\lib.win-amd64-3.5\spacy\tokens
  copying spacy\tests\tokenizer\sun.txt -> build\lib.win-amd64-3.5\spacy\tests\tokenizer
  running build_ext
  building 'spacy.parts_of_speech' extension
  error: [WinError 2] The system cannot find the file specified

  ----------------------------------------
  Failed building wheel for spacy

...
building 'murmurhash.mrmr' extension
  error: [WinError 2] The system cannot find the file specified

  ----------------------------------------
  Failed building wheel for murmurhash

....
building 'preshed.maps' extension
  error: [WinError 2] The system cannot find the file specified

  ----------------------------------------
  Failed building wheel for preshed
...
running build_ext
  building 'thinc.linalg' extension
  error: [WinError 2] The system cannot find the file specified

  ----------------------------------------
  Failed building wheel for thinc
...
building 'ujson' extension
  error: [WinError 2] The system cannot find the file specified

  ----------------------------------------
  Failed building wheel for ujson
...
running build_ext
  building 'cytoolz.dicttoolz' extension
  error: [WinError 2] The system cannot find the file specified

  ----------------------------------------
  Failed building wheel for cytoolz
...
   Complete output from command c:\python\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\pip-install-k9h_yxgx\\murmurhash\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ContainerAdministrator\AppData\Local\Temp\pip-record-orvvjita\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    running build_ext
    building 'murmurhash.mrmr' extension
    error: [WinError 2] The system cannot find the file specified

    ----------------------------------------
Command "c:\python\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\pip-install-k9h_yxgx\\murmurhash\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ContainerAdministrator\AppData\Local\Temp\pip-record-orvvjita\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\ContainerAdministrator\AppData\Local\Temp\pip-install-k9h_yxgx\murmurhash\

**Comment by ines** [comment]
Do you have the correct compiler installed, i.e. the Visual C++ Build Tools? (Not Visual Studio, you should really just need the build tools / compiler). [This thread](https://forums.docker.com/t/visual-studio-build-tools-on-windows-server-core-container/32618/10) on Docker + Windows Server Core might be relevant.

Alternatively, you can try one of the solutions in [my comment on this thread](https://forums.docker.com/t/visual-studio-build-tools-on-windows-server-core-container/32618/10).

**Comment by jeffsaremi** [comment]
I had the VS 2017 build tools installed. I am going to try VS 2015 tools.

**Comment by jeffsaremi** [comment]
Thinking that the problem could be related to 2017 vs 2015. I installed build tools 2015. The results are virtually the same meaning that build fails with a lot of [WinError 2] The system cannot find the file specified.
It is not clear what file is missing.
Is there anything in the pyhon installation that i have missed? any pre-req packages?

**Comment by ines** [comment]
We've just released `v2.0.13`, which comes with pre-build binary wheels for spaCy. We're also working on releasing wheels for all of our dependencies so users will be able to install spaCy without needing a compiler.

In the meantime, you can also find pre-built wheels for Windows for spaCy and its dependencies (including `ujson` etc.) here: https://www.lfd.uci.edu/~gohlke/pythonlibs/
