### ISSUE TITLE
The word "multiple" is a stop word in the French model

### ISSUE THREAD

**Issue by nathanwdavis** [explosion/spaCy#2540]
## How to reproduce the behaviour
```
nlp = spacy.load('fr')
nlp.Defaults.stop_words.intersection(["multiple"])

 Out:  {'multiple'}
```

## Your Environment
* Operating System: MacOS High Sierra
* Python Version Used: Python 3.6.1 :: Anaconda custom (x86_64)
* spaCy Version Used: spacy==2.0.11
* Environment Information: Using the default French model downloaded via the download command.

From what I see on Google Translate and talking to a French-speaking coworker, that should not be considered a stop word - especially if it's not considered a stop word in the English model.

**Comment by ines** [comment]
Thanks for the report! In spaCy, we try to define stop words as "frequent with low semantic information", so by that definition, I agree that "multiple" is questionable and maybe shouldn't be in that list.

Here's the relevant line in the French stop list:

https://github.com/explosion/spaCy/blob/604272353543b618672c4b857e95dd72d822955b/spacy/lang/fr/stop_words.py#L47

Do you want to submit a PR for this? This would also make it easier to get some feedback from other French users.

**Comment by sammous** [comment]
I agree with the author that "multiple" should not be on the list. Though I'm not sure either about "multiples". In a way, it can be a synonym of "plusieurs".

**Comment by ines** [comment]
@sammous Words that are only sometimes a stop word in some contexts are probably also not ideal, so it sounds like both should be removed? Feel free to open a PR btw 🙂

**Comment by sammous** [comment]
sure, will do it at the end of the week if it is not done :)

**Comment by ines** [comment]
Thanks! I was just tidying up anyways so I quickly did it – but if you come across more French stuff that looks bad, feel free to keep reporting!
