### ISSUE TITLE
wheel installation error

### ISSUE THREAD

**Issue by suhasdatascience** [explosion/spaCy#2541]
trying to install spacy latest version , getting error like " Unable to install wheel for spacy", I tried both in windows and linux(fedora), got same error

**Comment by ines** [comment]
Hi! By latest version, do you mean `v2.0.11` or the new spaCy nightly `v2.1.0a0`?

And could you share more details on what you tried? Which commands did you run on Windows and Linux? Which package managers did you use? Which Python version are you on? And what was the exact error message?
