### ISSUE TITLE
Training data with BILOU labels

### ISSUE THREAD

**Issue by eswar3** [explosion/spaCy#2552]
In this issue, https://github.com/explosion/spaCy/issues/1626
@ines  has replied saying you should be able to also provide BILUO tags as entities instead of the offsets.

I tried the same, but it throws me the following error
Code

```python
MYTRAIN_DATA = [
    ('Consumer Complaints 445 12th Street SW Washington DC 20554', ['O','O','B-ADDR','I-ADDR','I-ADDR','I-ADDR','I-ADDR','I-ADDR','L-ADDR']),
    ('mail us to 574 SW MALABAR RD BLDG15 PALM BAY FL 32908',['O','O','O','B-ADDR','I-ADDR','I-ADDR','I-ADDR','I-ADDR','I-ADDR','I-ADDR','I-ADDR','L-ADDR'] ),
    ('Final bill for 419 S Government Ave Lot 24 Fayetteville AR 72701',['O','O','O','B-ADDR','I-ADDR','I-ADDR','I-ADDR','I-ADDR','I-ADDR','I-ADDR','I-ADDR','L-ADDR'] )
]

LABEL = 'ADDR'
nlp = spacy.blank('en')
print("Created blank 'en' model")
if 'ner' not in nlp.pipe_names:
    ner = nlp.create_pipe('ner')
    nlp.add_pipe(ner, last=True)
else:
    ner = nlp.get_pipe('ner')
ner.add_label(LABEL)
optimizer = nlp.begin_training()
other_pipes = [pipe for pipe in nlp.pipe_names if pipe != 'ner']
n_iter=10

with nlp.disable_pipes(*other_pipes):  # only train NER
    for itn in range(n_iter):
        random.shuffle(MYTRAIN_DATA)
        losses = {}
        for text, annotations in MYTRAIN_DATA:  
            nlp.update([text], [annotations], sgd=optimizer, drop=0.35,losses=losses) 
```

```
Error: 

TypeError: type object argument after ** must be a mapping, not list
```

## Your Environment

* Operating System: MAC
* Python Version Used: 3.5
* spaCy Version Used:  2.0.11
* Environment Information:

**Comment by eswar3** [comment]
I am very new Spacy. But I went through documentation and previous issues related BILOU tags. I couldn't find any examples for training NER with BILOU tags for new entity type. any help would be greatly appreciated

**Comment by eswar3** [comment]
I tried using offsets_from_biluo_tags which seems to be working. But can someone confirm whether this is the right way to do NER training

from spacy.gold import offsets_from_biluo_tags
a=dict()
with nlp.disable_pipes(*other_pipes):  # only train NER
    for itn in range(n_iter):
        random.shuffle(MYTRAIN_DATA)
        losses = {}
        for text, annotations in MYTRAIN_DATA:  
            a['entities'] = offsets_from_biluo_tags(nlp(text), annotations)
            nlp.update([text], [annotations], sgd=optimizer, drop=0.35,losses=losses)

**Comment by ines** [comment]
Yes, it looks like the problem was that spaCy expects the annotations to be a dictionary – for example:

```python
{'entities': ['O','O','B-ADDR','I-ADDR','I-ADDR','I-ADDR','I-ADDR','I-ADDR','L-ADDR']}
```

But your data only passed in the list directly, so Python raised an error. If you wrap the annotations in a dictionary, it should work without the `offsets_from_biluo_tags`. If you want to convert your BILUO tags to offsets, you probably want to do this *before* you train and not during training. Otherwise, it can slow things down because you also need to process *every single text* with your `nlp` object in addition to updating the model.

I'd also recommend creating the dictionary *within the loop*, not at the top. This has nothing to do with spaCy, though, and is more of a stylistic Python thing. For example:

```python
for text, annotations in MYTRAIN_DATA: 
    a = {'entities': annotations}
    # ...
```

**Comment by eswar3** [comment]
@ines Thank you very much for the prompt response.  Yes, it was very slow when I trained around 20k examples. I will consider your suggestion. Also, could you please point me to the right documentation to train using GPU??

**Comment by ines** [comment]
@eswar3 Yes, this makes sense – in your code, you were updating the model for each example *and* processing the text again, which can get very slow. The example code also only shows the very basic principle to make it easy to understand what's going on. Once you're more serious about training, you'll probably want to use the [`spacy train` command](https://spacy.io/usage/training#spacy-train-cli) or at least batch up your examples (see the [training tips and advice](https://spacy.io/usage/training#section-tips) for details).

To use spaCy on GPU, you'll have to install it following the GPU-specific instructions: https://spacy.io/usage/#gpu
