### ISSUE TITLE
Memory leak in spacy

### ISSUE THREAD

**Issue by mittalsuraj18** [explosion/spaCy#2555]
## How to reproduce the behaviour

`nlp = spacy.load('en',disable=["ner","textcat"])`
`docs = nlp.pipe(list_of_strings, n_threads=16, disable=["ner","textcat"], batch_size=100,cleanup=True)`
`from pickle import Pickler`
`fo = open("./temp.pkl","wb")`
`writer = Pickler(fo)`
`for d in docs:     writer.dump(d)`
`fo.close()`

This causes memory leak in spacy.
The size of `list_of_strings=600,000` with average of 200 words in a string. 
My python process crosses 64gb at 300,000 mark.

## Info about spaCy

* **spaCy version:** 2.0.11
* **Platform:** Linux-3.13.0-149-generic-x86_64-with-debian-jessie-sid
* **Python version:** 3.6.5
* **Models:** en

**Comment by mittalsuraj18** [comment]
Ok so this apparently an issue with pickler object.
I was able to solve it using spacy `doc.to_disk` method.

**Comment by honnibal** [comment]
This is still worth keeping an eye on, thanks. We might have a bug in our `__reduce__` special methods somewhere.
