### ISSUE TITLE
System gets hanged when tried to train dataset

### ISSUE THREAD

**Issue by LastFromtheTop** [explosion/spaCy#2559]
Hi,
I want to train the model with 280K unique names, but every time I try it, the system gets hanged. Should I load them in parts or increase the system configuration(am on i7 Processor with 16Gb)? please suggest. Does 280K not look like scalable?

* Operating System: Windows 10
* Python Version Used: Python 3.6
* spaCy Version Used: 2.0.12

**Comment by honnibal** [comment]
That should work, but how many words of text are you training with, and what commands are you running?

Just to clarify: you can't train the entity recognizer with just a list of names. It needs to see them in context. This would be a separate problem from the "hang" you're seeing here though. You could also try installing `spacy-nightly==2.1.0a0` to see if that has the problem resolved.
