### ISSUE TITLE
The word "number" is not in Spacy's vocab?

### ISSUE THREAD

**Issue by Enumaris** [explosion/spaCy#2561]
## How to reproduce the behaviour
`nlp = spacy.load('en_core_web_md')`
`'number' in nlp.vocab`
`False`

## Your Environment
* Operating System: Windows 10
* Python Version Used: 3.6.5
* spaCy Version Used: 2.0.11
* Environment Information: 

This behavior happens when using both `en_core_web_lg-2.0.0` and `en_core_web_md-2.0.0`.
Oddly, the word `Number` (capital "N") is in the vocab. This seems very odd.

**Comment by honnibal** [comment]
This (and other similar quirks) should be fixed in v2.1. You can install with `pip install spacy-nightly==2.1.0a0`

**Comment by ines** [comment]
Just tested it and looks like this might be some qurik in the data. The `v2.1.0` alpha model currently produces the same result. The good news is, we're now able to retrain the models much faster to fix that kind of stuff, thanks to our new model training infrastructure 🎉

**Comment by Enumaris** [comment]
I've noticed in my attempts at finding a complete list of English words to work with that other word lists also exhibit similar quirks to this one. E.g. nltk's `words.words()` is missing the word "has". If the word "number" is the only common word missing from `nlp.vocab`, it wouldn't be a big deal and I could work around it, but it does make me worry that other similarly common words might be missing. I wonder if it might be worth it after training a model to check the `nlp.vocab` against a standard English dictionary to make sure it contains all the common words?

**Comment by honnibal** [comment]
I think it's related to the fact that `number` is a special symbol in spaCy, because it's a dependency label. There's only a few of these, and most of them aren't also words.

You might be interested in the data from `nlp.vocab.morphology.lemmatizer.index`. This is sourced from WordNet, and contains lists of lemmas.

**Comment by Enumaris** [comment]
It appears you are right. I checked the dependency tags and none of them are in `nlp.vocab`. This means the common words `possessive`,`agent`,`mark`,`prep`,`root` are not in `nlp.vocab`!

**Comment by polm** [comment]
This seems to be resolved in `en_web_news_lg` in v3.0.4`.
