### ISSUE TITLE
PaddingError when installing from conda

### ISSUE THREAD

**Issue by kefa8** [explosion/spaCy#2563]
Hi,
I'm trying to install spacy from conda and am getting the a padding error:

thinc-6.10.2-p 100% |###############################| Time: 0:00:03 384.88 kB/s
spacy-2.0.11-p 100% |###############################| Time: 0:00:06   6.82 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
PaddingError: Placeholder of length '28' too short in package conda-forge::tk-8.5.19-vc14_1.
The package must be rebuilt with conda-build > 2.0.

I'm trying to install this on Windows 10, Python 3.5.3. The command I ran is:
conda install -c conda-forge spacy

This is the conda download plan.

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2018.4.16  |                0         176 KB  conda-forge
    openssl-1.0.2o             |           vc14_0         5.4 MB  conda-forge
    yaml-0.1.7                 |           vc14_0         103 KB  conda-forge
    zlib-1.2.11                |           vc14_0         119 KB  conda-forge
    icu-58.2                   |           vc14_0        21.8 MB  conda-forge
    jpeg-9b                    |           vc14_2         314 KB  conda-forge
    libpng-1.6.34              |           vc14_0         547 KB  conda-forge
    tk-8.5.19                  |           vc14_1         2.3 MB  conda-forge
    cymem-1.31.2               |      py35_vc14_0          25 KB  conda-forge
    msgpack-python-0.4.8       |           py35_0         270 KB  conda-forge
    murmurhash-0.28.0          |      py35_vc14_0          17 KB  conda-forge
    plac-0.9.6                 |             py_1          18 KB  conda-forge
    qt-5.6.2                   |           vc14_1        55.6 MB  conda-forge
    regex-2017.11.09           |           py35_0         768 KB  conda-forge
    termcolor-1.1.0            |             py_2           6 KB  conda-forge
    toolz-0.9.0                |             py_0          45 KB  conda-forge
    tqdm-4.23.4                |             py_0          35 KB  conda-forge
    wrapt-1.10.11              |           py35_0          44 KB  conda-forge
    cytoolz-0.8.2              |           py35_0         276 KB  conda-forge
    msgpack-numpy-0.4.1        |             py_0           8 KB  conda-forge
    preshed-1.0.0              |      py35_vc14_0          54 KB  conda-forge
    thinc-6.10.2               |      py35_vc14_0         1.3 MB  conda-forge
    spacy-2.0.11               |      py35_vc14_0        39.7 MB  conda-forge
    ------------------------------------------------------------
                                           Total:       128.7 MB

The following NEW packages will be INSTALLED:

    ca-certificates: 2018.4.16-0        conda-forge
    cymem:           1.31.2-py35_vc14_0 conda-forge [vc14]
    cytoolz:         0.8.2-py35_0       conda-forge
    msgpack-numpy:   0.4.1-py_0         conda-forge
    msgpack-python:  0.4.8-py35_0       conda-forge
    murmurhash:      0.28.0-py35_vc14_0 conda-forge [vc14]
    plac:            0.9.6-py_1         conda-forge
    preshed:         1.0.0-py35_vc14_0  conda-forge [vc14]
    regex:           2017.11.09-py35_0  conda-forge
    spacy:           2.0.11-py35_vc14_0 conda-forge [vc14]
    termcolor:       1.1.0-py_2         conda-forge
    thinc:           6.10.2-py35_vc14_0 conda-forge [vc14]
    toolz:           0.9.0-py_0         conda-forge
    tqdm:            4.23.4-py_0        conda-forge
    wrapt:           1.10.11-py35_0     conda-forge

The following packages will be UPDATED:

    icu:             57.1-vc14_0                    --> 58.2-vc14_0   conda-forge [vc14]
    jpeg:            9b-vc14_0                      --> 9b-vc14_2     conda-forge [vc14]
    libpng:          1.6.27-vc14_0                  --> 1.6.34-vc14_0 conda-forge [vc14]
    openssl:         1.0.2l-vc14_0                  --> 1.0.2o-vc14_0 conda-forge [vc14]
    tk:              8.5.18-vc14_0                  --> 8.5.19-vc14_1 conda-forge [vc14]
    yaml:            0.1.6-0                        --> 0.1.7-vc14_0  conda-forge [vc14]
    zlib:            1.2.8-vc14_3                   --> 1.2.11-vc14_0 conda-forge [vc14]

The following packages will be SUPERCEDED by a higher-priority channel:

    qt:              5.6.2-vc14_4                   --> 5.6.2-vc14_1  conda-forge [vc14]

**Comment by ines** [comment]
Hmm, this is strange. The package is not part of spaCy's dependencies, so it's probably related to a different package (likely `qt`?) that's updated in the process due to new dependency constraints.

Are you using the latest conda? [According to this issue](https://github.com/ContinuumIO/anaconda-issues/issues/1366), upgrading might help with a similar error. You could also try `conda update --all`:

```bash
conda update conda
conda update --all
```
