### ISSUE TITLE
A single OP:+ is not greedy

### ISSUE THREAD

**Issue by wpm** [explosion/spaCy#2569]
The '+' pattern matcher is not greedy. For example:

```python
matcher = Matcher(nlp.vocab)
matcher.add("RULE", None, [{'ENT_TYPE':'DATE', 'OP':'+'}])
document = nlp('It is May 15, 1993.')
[document[s:e] for _, s, e in matcher(document)]
```

returns `[May 15, 15,, , 1993, 1993]` where I would expect it to return `[May 15, 1993]`.

The entity list and token labels are what I would expect.

```python
[e for e in document.ents]  # returns [May 15, 1993]
[t for t in document if t.ent_type_ == 'DATE'] # returns [May, 15, ,, 1993]
```

The [documentation](https://spacy.io/usage/linguistic-features#quantifiers) says that "In versions before v2.1.0, the semantics of the + and * operators behave inconsistently" with respect to their greediness. But that is supposed to only occur when more than one quantifier operator is present. Here there is only a single "+".

Is this behavior an aspect of that bug or something different?

## Info about spaCy

* **spaCy version:** 2.0.11
* **Platform:** Darwin-17.7.0-x86_64-i386-64bit
* **Python version:** 3.6.5
* **Models:** en_core_web_lg, en

**Comment by felixheck** [comment]
Got the same issue with `*`.
Have to combine the same part of a rule with `?` instead – is annoying :/

**Comment by ines** [comment]
I just added a test case for this for v2.1.0 and it works as expected and correctly produces all combinations of matches, including the full span. Since you're using the `+` operator, which matches *one or more* tokens, it's expected that the matcher will always return all possible combinations, starting with a single token, up to the maximum number of matched tokens. Here's a minimal example:

```python
matched = [doc[start:end] for _, start, end in matcher(doc)]
matched = sorted(matched, key=len, reverse=True)
for span in matched:
    print([token.text for token in span])
```

```
['May', '15', ',', '1993']
['May', '15', ',']
['15', ',', '1993']
['May', '15']
['15', ',']
[',', '1993']
['May']
['15']
[',']
['1993']
```

If you're only looking for the longest possible match, you can always sort the matched spans by length like in my example above.

**Comment by felixheck** [comment]
Using the following pattern:
```py
pattern = [
    {'POS': 'SYM', 'OP': '?'},
    {'POS': 'NUM', 'OP': '+'},
    {'POS': 'NOUN', 'OP': '*'}
]
```

And the following text:
```
Opinion: A $31,000 dining room set for Ben Carson? Typical Trump administration behavior.
```

I just get `$31,000 dining` and not `$31,000 dining room set` or `$31,000 dining room` even though both `dining` and `room` are tagged as `NOUN`.

**Comment by wpm** [comment]
Ok. I see that the current behavior of "+" is as advertised in v2.1.0, so that is fixed.

I'd still like a way to make matches greedy, e.g. `{'ENT_TYPE':'DATE', 'OP':'+'}`. The sort by size trick works if you only have one date in a document, but breaks down for multiple ones. For example applying the above sorting trick to "He was born on May 15. She was born on June 4." returns this:

```
May 15
June 4
15
4
```

There's no way to know that the first _two_ items are what I'm looking for without doing some clever inclusion comparisons between the various spans. A greedy operator could do this more efficiently.

Should this be a separate feature request?
