### ISSUE TITLE
nlp = spacy.load('en') || Keyerror 'package'

### ISSUE THREAD

**Issue by nikhilsharma010** [explosion/spaCy#2571]
I installed spacy

import spacy works fine but when i try to run the following command 

nlp = spacy.load('en')

I get 

KeyError: 'package'

Spacy Version 2.0.11
Python version 3.6 [Running on Jupyter notebook

**Comment by ines** [comment]
> `KeyError: 'package'`

Could you post the full stack trace of that error? Basically, everything that was printed before it and that shows how the error occured.

**Comment by nikhilsharma010** [comment]
Sorry 

Here you go.

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-6-a3c4ad8bf46c> in <module>()
      1 import spacy
----> 2 nlp = spacy.load('en')
      3 doc = nlp(u'This is a sentence.')

/anaconda3/lib/python3.6/site-packages/spacy/__init__.py in load(name, vocab, tokenizer, parser, tagger, entity, matcher, serializer, vectors, via)
     13 def load(name, vocab=None, tokenizer=None, parser=None, tagger=None, entity=None,
     14          matcher=None, serializer=None, vectors=None, via=None):
---> 15     package = get_package_by_name(name, via=via)
     16     vectors_package = get_package_by_name(vectors, via=via)
     17     cls = get_lang_class(name)

/anaconda3/lib/python3.6/site-packages/spacy/util.py in get_package_by_name(name, via)
     42     try:
     43         return sputnik.package(about.__title__, about.__version__,
---> 44             name, data_path=via)
     45     except PackageNotFoundException as e:
     46         raise RuntimeError("Model '%s' not installed. Please run 'python -m "

/anaconda3/lib/python3.6/site-packages/sputnik/__init__.py in package(app_name, app_version, package_string, data_path)
    157         data_path = default_data_path(app_name)
    158 
--> 159     pool = Pool(app_name, app_version, expand_path(data_path))
    160     return pool.get(package_string)
    161 

/anaconda3/lib/python3.6/site-packages/sputnik/pool.py in __init__(self, app_name, app_version, path, **kwargs)
     17 
     18     def __init__(self, app_name, app_version, path, **kwargs):
---> 19         super(Pool, self).__init__(app_name, app_version, path, **kwargs)
     20         self.logger = logging.getLogger(__name__)
     21         self.cleanup()

/anaconda3/lib/python3.6/site-packages/sputnik/package_list.py in __init__(self, app_name, app_version, path, **kwargs)
     31             raise InvalidDataPathException(self.data_path)
     32 
---> 33         self.load()
     34 
     35     def packages(self):

/anaconda3/lib/python3.6/site-packages/sputnik/package_list.py in load(self)
     49     def load(self):
     50         self._packages = {}
---> 51         for package in self.packages():
     52             self._packages[package.ident] = package
     53 

/anaconda3/lib/python3.6/site-packages/sputnik/package_list.py in packages(self)
     45                 continue
     46 
---> 47             yield self.__class__.package_class(path=os.path.join(self.path, path))
     48 
     49     def load(self):

/anaconda3/lib/python3.6/site-packages/sputnik/package.py in __init__(self, path)
     13     def __init__(self, path):
     14         meta = util.json_load(os.path.join(path, default.META_FILENAME))
---> 15         super(Package, self).__init__(defaults=meta['package'])
     16 
     17         self.logger = logging.getLogger(__name__)

KeyError: 'package'

**Comment by nikhilsharma010** [comment]
This worked for me. Thanks 👍

**Comment by ines** [comment]
@nikhilsharma010 Yay and sorry about the frustration!

By the way, if you scroll up in your terminal, do you still have the original installation logs from *the first time* you installed spaCy via conda? The installation that gave you the old version? (It should look similar [like the table here](https://github.com/explosion/spaCy/issues/2514#issuecomment-405561903)). If you do, this would be super helpful. I finally want to understand what's going on and why this keeps happening!
