### ISSUE TITLE
Problem training custom NER model

### ISSUE THREAD

**Issue by lukeskywalkre** [explosion/spaCy#2573]
Hello, I am training a custom NER model in spaCy by building on the following sample code:  https://spacy.io/usage/training#ner 
However, when running my code, I get the following error.

Any ideas on how to resolve this? Many thanks!

```

`n [5]: runfile('C:/Users/u0084411/Box Sync/Werk/Postgraduaat/Text to model/Code/Custom_NER.py', wdir='C:/Users/u0084411/Box Sync/Werk/Postgraduaat/Text to model/Code')
Created blank 'en' model
Warning: Unnamed vectors -- this won't allow multiple vectors models to be loaded. (Shape: (0, 0))
Traceback (most recent call last):

  File "<ipython-input-5-792ee6a1f90a>", line 1, in <module>
    runfile('C:/Users/u0084411/Box Sync/Werk/Postgraduaat/Text to model/Code/Custom_NER.py', wdir='C:/Users/u0084411/Box Sync/Werk/Postgraduaat/Text to model/Code')

  File "C:\Users\u0084411\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Users\u0084411\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/u0084411/Box Sync/Werk/Postgraduaat/Text to model/Code/Custom_NER.py", line 282, in <module>
    plac.call(main)

  File "C:\Users\u0084411\AppData\Local\Continuum\Anaconda3\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)

  File "C:\Users\u0084411\AppData\Local\Continuum\Anaconda3\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)

  File "C:/Users/u0084411/Box Sync/Werk/Postgraduaat/Text to model/Code/Custom_NER.py", line 254, in main
    losses=losses)

  File "C:\Users\u0084411\AppData\Local\Continuum\Anaconda3\lib\site-packages\spacy\language.py", line 411, in update
    gold = GoldParse(doc, **gold)

  File "gold.pyx", line 420, in spacy.gold.GoldParse.__init__

  File "gold.pyx", line 522, in spacy.gold.biluo_tags_from_offsets

ValueError: need more than 0 values to unpack`


```

**Comment by ines** [comment]
Errors like this ("need more than X to unpack") usually point to formatting problems in the data. For example if you accidentally pass in just an entity tuple instead of *a list* of entity tuples. Could you share an example of the data it's failing on?

I'll also have a look at how this is currently handled internally – I'm sure we can find a way to make spaCy fail more gracefully here and output a better error message.

**Comment by lukeskywalkre** [comment]
Hi Ines,

Thank you for your quick response, the data are formatted as follows:
`('ï»¿Employees and leaders', {'entities':[()]}),
   ('For each project, a number of employees are assigned as team-members, and one employee is assigned as a project-leader.', {'entities':[(30, 39, 'OBJECT'), (65, 68, 'OBJECT'), (78, 86, 'OBJECT'), (104, 118, 'OBJECT')]}),
   ('A person can be a member and/or a leader of multiple projects.', {'entities':[(2, 8, 'OBJECT'), (18, 24, 'OBJECT'), (34, 40, 'OBJECT') ]}),`

**Comment by ines** [comment]
Try removing the `()` in the first entry and make it `'entities': []`! When spaCy converts the entity offsets to BILUO tags, it iterates over the entities and expects them to be `(start, end, label)` tuples. But `()` can't be unpacked into three values, so spaCy complains.

**Comment by lukeskywalkre** [comment]
Thank you very much, I no longer get the error. Training seems to be working now.

**Comment by screamfest** [comment]
Hello,
what "start" and "end" means?

how to determine the number or maybe a format for example if I need to create new NER training dataset
with this treebank?

`## Morphological Tagset

|   UD     |  ITB   | First position                  | Second position          | Third position              |
| -------- | ------ | ------------------------------- | ------------------------ | --------------------------- |
| `PROPN`  | `E--`  | `E` (Proper Noun)               |                          |                             |
| `NOUN`   | `NPF`  | `N` (Noun)                      | `P` (Plural)             | `F` (Feminine)              |
| `NOUN`   | `NPM`  | `N` (Noun)                      | `P` (Plural)             | `M` (Masculine)             |
| `NOUN`   | `NPD`  | `N` (Noun)                      | `P` (Plural)             | `D` (Non-Specified)         |
| `NOUN`   | `NSF`  | `N` (Noun)                      | `S` (Singular)           | `F` (Feminine)              |
| `NOUN`   | `NSM`  | `N` (Noun)                      | `S` (Singular)           | `M` (Masculine)             |
| `NOUN`   | `NSD`  | `N` (Noun)                      | `S` (Singular)           | `D` (Non-Specified)         |
| `PRON`   | `PP1`  | `P` (Personal Pronoun)          | `P` (Plural)             | `1` (First Person)          |
| `PRON`   | `PP2`  | `P` (Personal Pronoun)          | `P` (Plural)             | `2` (Second Person)         |
| `PRON`   | `PP3`  | `P` (Personal Pronoun)          | `P` (Plural)             | `3` (Third Person)          |
| `PRON`   | `PS1`  | `P` (Personal Pronoun)          | `S` (Singular)           | `1` (First Person)          |
| `PRON`   | `PS2`  | `P` (Personal Pronoun)          | `S` (Singular)           | `2` (Second Person)         |
| `PRON`   | `PS3`  | `P` (Personal Pronoun)          | `S` (Singular)           | `3` (Third Person)          |
| `VERB`   | `VPA`  | `V` (Verb)                      | `P` (Plural)             | `A` (Active Voice)          |
| `VERB`   | `VPP`  | `V` (Verb)                      | `P` (Plural)             | `P` (Passive Voice)         |
| `VERB`   | `VSA`  | `V` (Verb)                      | `S` (Singular)           | `A` (Active Voice)          |
| `VERB`   | `VSP`  | `V` (Verb)                      | `S` (Singular)           | `P` (Passive Voice)         |
| `NUM`    | `CC-`  | `C` (Numeral)                   | `C` (Cardinal Numeral)   |                             |
| `NUM`    | `CO-`  | `C` (Numeral)                   | `O` (Ordinal Numeral)    |                             |
| `NUM`    | `CD-`  | `C` (Numeral)                   | `D` (Collective Numeral) |                             |
| `ADJ`    | `APP`  | `A` (Adjective)                 | `P` (Plural)             | `P` (Positive)              |
| `ADJ`    | `APS`  | `A` (Adjective)                 | `P` (Plural)             | `S` (Superlative)           |
| `ADJ`    | `ASP`  | `A` (Adjective)                 | `S` (Singular)           | `P` (Positive)              |
| `ADJ`    | `ASS`  | `A` (Adjective)                 | `S` (Singular)           | `S` (Superlative)           |
| `CONJ`   | `H--`  | `H` (Coordinating Conjunction)  |                          |                             |
| `SCONJ`  | `S--`  | `S` (Subordinating Conjunction) |                          |                             |
| `X`      | `F--`  | `F` (Foreign Word)              |                          |                             |
| `ADP`    | `R--`  | `R` (Preposition)               |                          |                             |
| `AUX`    | `M--`  | `M` (Modal)                     |                          |                             |
| `DET`    | `B--`  | `B` (Determiner)                |                          |                             |
| `ADV`    | `D--`  | `D` (Adverb)                    |                          |                             |
| `PART`   | `T--`  | `T` (Particle)                  |                          |                             |
| `PART`   | `G--`  | `G` (Negation)                  |                          |                             |
| `INTJ`   | `I--`  | `I` (Interjection)              |                          |                             |
| `VERB`   | `O--`  | `O` (Copula)                    |                          |                             |
| `PRON`   | `WP-`  | `W` (Question)                  | `P` (Pronoun)            |                             |
| `ADV`    | `WD-`  | `W` (Question)                  | `D` (Adverb)             |                             |
| `DET`    | `WB-`  | `W` (Question)                  | `B` (Determiner)         |                             |
| `X`      | `X--`  | `X` (Unknown)                   |                          |                             |
| `PUNCT`  | `Z--`  | `Z` (Punctuation)               |                          |                             |

*) ~~untuk `W--` sebagai _interrogative pronouns_ (_who_; _siapa_, _siapakah_) menjadi `PRON`, `W--` sebagai _interrogative adverbs_ (_where_, _when_, _how_, _why_; _di mana_, _kapan_, _bilamana_, _bagaimana_, _mengapa_)  menjadi `ADV`, `W--` sebagai _interrogative determiners_ (_which_; _yang mana_) menjadi `DET`~~

**) ~~kelas `PROPN` masih belum ditentukan. oleh MorphInd, kelas yang digunakan adalah `X--` dan `F--`~~

## Lemma Tagset

|  .  | Tagset                     |
| --- | -------------------------- |
| `n` | Noun                       |
| `p` | Personal Pronoun           |
| `v` | Verb                       |
| `c` | Numeral                    |
| `q` | Adjective                  |
| `h` | Coordinating Conjunction   |
| `s` | Subordinating Conjunction  |
| `f` | Foreign Word               |
| `r` | Preposition                |
| `m` | Modal                      |
| `b` | Determiner                 |
| `d` | Adverb                     |
| `t` | Particle                   |
| `g` | Negation                   |
| `i` | Interjection               |
| `o` | Copula                     |
| `w` | Question                   |
| `x` | Unknown                    |
| `z` | Punctuation                |`

Thank you in advance
