### ISSUE TITLE
Textcat model using character-level embeddings?

### ISSUE THREAD

**Issue by jmrosen155** [explosion/spaCy#2583]
I've noticed that the spaCy text classification model somehow doesn't simply use word embeddings for classifying text into categories. For example, the two strings "abqdf" and "abrdf" both are not words in the dictionary (i.e. do not have a GloVe vector representation). Hence, they should both be the zero vectors. However, when classifying these two strings into categories using the spaCy model, I could get 2 different categories. Any idea why this would be the case? Thanks! 

## Info about spaCy
* Python version: 2.7.14
* Platform: Darwin-15.6.0-x86_64-i386-64bit
* spaCy version: 2.0.5
* Models: en, en_core_web_lg

**Comment by elyase** [comment]
There are some subwords features used in the text classifier. This is the relevant line:

https://github.com/explosion/spaCy/blob/3141e04822a8c40e0d64e51a040305ade3f66d8c/spacy/_ml.py#L498

**Comment by jmrosen155** [comment]
Thanks for the reply. It makes sense in cases where the prefix and/or suffix are different as in my original example. But how about the case "abqcdf" vs "abrcdf"? Since the prefix is the first character and the suffix is the last 3 characters, the subword features should all be identical. However, when classifying these two strings into categories using the spaCy model, I could still get 2 different categories.

**Comment by honnibal** [comment]
@jmrosen155 The model also learns word vectors for arbitrary words, with no strict limit on the vocabulary size. The word's NORM value is hashed with 4 different seeds, and the results modded into the embedding table. The resulting vectors are then summed. This is implemented in `thinc.neural._classes.hash_embed` if you want to have a look. The result is that distinct words will almost always receive a distinct vector, even if they're not in the vocabulary initially.
