### ISSUE TITLE
vocab.set_vector throws for oov word in windows 10

### ISSUE THREAD

**Issue by zhaoyu0810** [explosion/spaCy#2585]
## How to reproduce the behaviour

Run below code in windows 10:
```
import spacy
import numpy as np

nlp = spacy.load('en_core_web_lg')
vocab = nlp.vocab
vector = np.zeros(300,)
vocab.set_vector('thisisoovword', vector) #throws
print('completed')
```

Got error:
```
Traceback (most recent call last):  File "d:\git\test\testSet_vector.py", line 10, in <module>    vocab.set_vector('thisisoovword', vector)
  File "vocab.pyx", line 335, in spacy.vocab.Vocab.set_vector
  File "vectors.pyx", line 153, in spacy.vectors.Vectors.resize
TypeError: 'int' object is not iterable
```

The same code works well in ubuntu

## Your Environment

* Operating System: windows 10
* Python Version Used: 3.6
* spaCy Version Used: 2.0.0
* Environment Information:

**Comment by honnibal** [comment]
Could you upgrade to v2.0.12 and check again? I think the error has been fixed, which is why you're seeing it different on Ubuntu -- I think you're using a different version there.
