### ISSUE TITLE
Reducing Memory Usage?

### ISSUE THREAD

**Issue by Xeoncross** [explosion/spaCy#260]
Are their any parameters I can tweak to reduce the memory spaCy uses? Right now it seems to require about 1.7GB of RAM which is too much for many smaller virtual servers both locally or in datacenters.

I'm running it alone in a 2.5GB virtualbox ubuntu just to test and play around with.

I'm not sure exactly what vectors or [data spaCy loads](https://github.com/spacy-io/spaCy/tree/master/corpora/en) or how removing some of them would affect performance. Right now it seems to require about 1 minute on a dualcore i5 to load the data.

**Comment by syllog1sm** [comment]
Unfortunatly you can currently only reduce memory usage by removing capabilities. We hope to reduce memory usage in future by switching to a neural network model. Progress on that is going well.
