### ISSUE TITLE
Can tokenization influence NER labeling?

### ISSUE THREAD

**Issue by katarkor** [explosion/spaCy#2600]
I'm training a Norwegian model with named entity tags on a dataset annotated according to UD. I noticed that spaCy and UD differ in how they tokenize words with "-"; spaCy seems to always treat that kind of words as separate tokens, while UD treats them as a unit. A name like "Mette-Marit" is one token in UD, but three in spaCy. Instead of one NER tag for the whole name, I end up with:

Mette mette PROPN PROPN___ ROOT B PER
\- - PUNCT PUNCT___ punct I PER
Marit marit PROPN PROPN__Gender=Fem conj B PER

Not only is the name split, but spaCy also fails to recognize it as a unit and treats "Mette-" as one entity and "Marit" as another. Another example is "Ap-politikere" (Ap's politicians), which is one token in UD and three according to spaCy:

Ap ap PROPN PROPN___ nsubj B ORG
\- - PUNCT PUNCT___ punct O 
politikere politiker NOUN NOUN__Definite=Ind|Gender=Masc|Number=Plur conj O 

It looks correct, but in the dataset I work with this kind of tokens have a separate label "DRV" for tokens that contain a named entity, which I just label as "MISC", since it's impossible to know whether the entity is a person, location or organisation. But when the tokens get split in three, I guess I end up with "MISC" label for "Ap" token alone, which would be incorrect. I was wondering if any of the issues could lead to lower NER accuracy in general?

## Your Environment

* Operating System: macOS High Sierra 10.13.6
* Python Version Used: 3.6.5
* spaCy Version Used: 2.0.11

**Comment by honnibal** [comment]
If the tokenization doesn't align well to the NER dataset you're training from, yes, that will definitely lower performance.

Perhaps you could try adding some `Matcher` rules to post-process the entities into one token? You could also customize the `token_match` regular expression in the tokenizer, but the expression is currently enormous, making it quite difficult to work with. Post-processing rules seem like a better approach at this point.

**Comment by katarkor** [comment]
Allright, thanks for your answer :)
