### ISSUE TITLE
Documentation of missing value (NER)

### ISSUE THREAD

**Issue by pommedeterresautee** [explosion/spaCy#2603]
Hi,

In the documentation, it s said that it is possible for NER to have a token with "missing value".
In this case, loss is not applied on the token.
In the documentation it is said that it will happen when offset doesn't match a word boundary.

However it is not said how, as a user, we can declare ourself a token as missing value, for instance because we know there is a risk this token is part of an entity but we are not sure.
In particular, when declaring offset directly as a tuple?

Can you please complete the documentation on this point?

## Which page or section is this issue related to?
https://spacy.io/usage/linguistic-features

**Comment by honnibal** [comment]
Hey,

There's a way to do this, but the API around it isn't quite perfect. There's two ways to specify the NER labels: either as `(start, end, label)` offsets, or as the BILUO tags for each token. If you use the BILUO tags, you can set some values to `None` to indicate the value is missing. There's no equivalent way to do this with the tuples, unfortunately.

You can also write the `None` values to the `gold.ner` list after creating the `GoldParse` object.

**Comment by pommedeterresautee** [comment]
Just to confirm, you say that in biluo annotations, unknown tag is None. I ask because I have noticed that when offsets are wrong (because not matching word boundaries) spacy use "-" to indicate unknown entity. "-" is the same as None for spacy?

**Comment by honnibal** [comment]
This is a bit inconsistent in spaCy unfortunately, and I'm always going back and rechecking it myself to be honest. In the early days I had a few different ways to indicate missing values, but I've been trying to standardise on `None` as the right way to do it, as we've been steadily trying to improve the API around the `GoldParse` class and the data formats in general.

I expect `None` to work. If it seems to not, please do let me know and I'll try to fix that.

**Comment by pommedeterresautee** [comment]
I think there is a bug when the first item is None.
```
from spacy.gold import biluo_tags_from_offsets, GoldParse
...
nlp = get_empty_model(load_labels_for_training=True)
doc: Doc = nlp.make_doc("Ceci est un test.")
# works
GoldParse(doc, entities=['O', 'O', 'O', 'O'])
# works
GoldParse(doc, entities=['O', 'O', 'O', None, 'O'])
# crash
GoldParse(doc, entities=[None, 'O', 'O', 'O', 'O'])
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "gold.pyx", line 422, in spacy.gold.GoldParse.__init__
  File "gold.pyx", line 524, in spacy.gold.biluo_tags_from_offsets
TypeError: 'NoneType' object is not iterable
```

**Comment by honnibal** [comment]
Just looking at this again sorry. I think you're right and there's a bug here. We have:

```
462         elif not isinstance(entities[0], basestring):
```

Which will fail if `None` is provided as the first value. I think the implementation is easier if all the values are strings, but the API is better if we pass `None`. So a good solution is probably to translate the `None` values into `-` or `''` internally near the start of the function.
