### ISSUE TITLE
Improve tokenization of Swedish based on UD_Swedish-Talbanken

### ISSUE THREAD

**Issue by EmilStenstrom** [explosion/spaCy#2608]
This is a followup for #2578 for addressing the tokenization of Swedish. I plan to fix each of this issues in separate PR:s, but thought I'd summarize all of them in one issue.

## How to reproduce the behaviour
I've [downloaded UD_Swedish-Talbanken](https://raw.githubusercontent.com/UniversalDependencies/UD_Swedish-Talbanken/master/sv_talbanken-ud-dev.conllu), and reconstructed the orignal text from those files, run SpaCy on them, and compared the result. [Code available as a gist](https://gist.github.com/EmilStenstrom/dc67b8909ce9b5ea2c81153f57574c22).

It did the analysis on the sentence level, and marked that sentence as "incorrect" when I found the first mismatching token. So there are probably more mismatching tokens, but matching them up when an earlier one was too much work. The results look like this:

**Total sentences**: 6029
**Correct sentences**: 5488 (91.03% where correctly tokenized)
**Incorrect sentences**: 538

### ERROR_TYPES.DASH: 253
These errors occur when "EEC-apparaten" is tokenized as "EEC", "-", "apparaten". There are a lot of errors like this. 

### ERROR_TYPES.ABBR: 219
These errors occur when there are Swedish abbreviations that SpaCy doesn't yet support. Based on this, I have a new list that I'll try adding to SpaCy to see if these kinds of errors go away.

### ERROR_TYPES.GENITIVE: 41
These errors occur for two cases of Swedish genitive form. For uppercase organizations, the form "ECC:s" is used. The other case is the rare "Magnus' saker", where "Magnus" is a name the ends with and s. You can optionally add a ' after the s in that case. This form only occurs twice in this (slightly old-fashioned) corpus, so I'm not sure it's worth supporting.

### ERROR_TYPES.LISTS: 12
All over the corpus there are examples of lists inside sentences. A translated example could be: "Are you 1) happy to see me or 2) not happy at all?". Pieces with letters instead of numbers exist, as well as versions with "(a)" and "(b)" too.

### ERROR_TYPES.SINGLELETTER: 8
This is the error I reported in #2578, where single letters at the end of the sentence get grouped together with the period. Except for the case with "i" (translated "in"), I also found sentences like "The sea level is 3 m." (where "m" is short for "meters").

### ERROR_TYPES.PARENTESISEQUAL: 3
In three cases a parenthesis is used together with an equal sign to explain a calculation. Translated: "The tax is 2500 SEK (= 10000 SEK * 0.25)." Spacy tokenized "(=" as a single token, probably because it thinks it's a smiley.

### ERROR_TYPES.UNKNOWN: 2
There are also single strange cases. The first one is an error in Talbanken ([I'll report it to them](https://github.com/UniversalDependencies/UD_Swedish-Talbanken/pull/3)). The second is a case where "mån." is handled like a single term in SpaCy, as if it was an abbreviation. I can't find it in the abbr list for Swedish, and since it has an "å", I can't imagine it's in the global list...

## Next step
I plan to take these on, one by one, as separate PR:s. Unless you find that one of them goes against "the spirit" of how SpaCy handles tokenization. So I'd appreciate any input about that so I don't do duplicate work.

Thanks!

**Comment by EmilStenstrom** [comment]
I've run into a bit of trouble, is this a good place to ask questions? I'll try, please point me elsewhere if I'm doing this wrong.

In the corpus (and in real Swedish text) abbreviations are sometimes used without a dot in them. So "bl.a." is sometimes written as "bl a" instead. Problem is, I can't seem to find a way to merge two tokens using the language specific TOKENIZER_EXCEPTIONS. The examples I've read just talk about splitting tokens up, not merging them. Is this possible? Is there some documentations somewhere on how to do this?

**Comment by honnibal** [comment]
@EmilStenstrom Apologies for the delay in getting to this.

spaCy always splits on whitespace, so there's no way to "protect" a token like `bl a` from the tokenizer. What we should do instead is have a post-processing component that can merge the tokens. In v2.1.0a0, the merge rules can also be learnt in the parser. But if there are reliable rules for the merging, this would be good as a pipeline component, probably using the `Matcher`.

Re the possessive `'s`: Pretty much all treebanks will tokenize that out, yes. Most linguists analyse the English `'s` as a clitic, rather than a case-marker. Consider an example like:

```
a) "The box on top's left face is red".
```

 Now, this example might read a little strangely...But consider the alternative:

```
b) * the box's on top left face is red
```

I'm sure that even a non-native speaker can see that b) is completely wrong. Because `'s` attaches at the phrase level, rather than onto the word, it cannot be a bound morpheme, so it cannot be a case marker -- it must be a clitic, and therefore it must be its own token.

**Comment by EmilStenstrom** [comment]
@honnibal Does this also apply to words with dashes in them? "ECC-apparaten" gets tokenized into three tokens, instead of one, as it is supposed to according to this treebank. Swedish has, just like German, lots of compound words, and using dash doesn't change that it's still a compound.
