### ISSUE TITLE
make language models available in Conda

### ISSUE THREAD

**Issue by nicolas-legroux** [explosion/spaCy#2609]
Hi,

Would it be possible to publish the language models (like `en_core_web_sm`) to, eg. Conda forge ? Right now it seems it's only possible to install from Pip while downloading the source from GH. Making things available in Conda can be useful in production build systems that rely on, eg, proxied Conda channels.

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
If so, we will tag it as [`project idea`](https://github.com/explosion/spaCy/labels/project%20idea) so other users can take it on.

**Comment by ines** [comment]
Hi! The spaCy model packages are a bit special in the sense that they're very large and mostly consist of binary data. This also means we can't so easily upload them to existing package managers. Instead, spaCy relies on `pip`'s ability to install a package from a `.tar.gz` file (which we fetch [from GitHub](https://github.com/explosion/spacy-models)).

I don't know what conda-forge's file size limits are and whether there are restrictions around the contents of the packages. If uploading the models is possible (including the larger ~1GB models) and we can find a way to integrate it into our existing build processes without too much overhead, we'd definitely consider it.

**Comment by ines** [comment]
See here for more details and updates: conda-forge/staged-recipes#7728 😃
