### ISSUE TITLE
German medium model 2.1.0a0 not loading

### ISSUE THREAD

**Issue by FritzTheBat** [explosion/spaCy#2612]
Loading the new german md model produces this error for me. Loading the french model 2.1.0a0 works fine, so there might be somthing wrong with the model.

### running
import spacy
spacyDe = spacy.load('de_core_news_md')

### results in

ValueError                                Traceback (most recent call last)
<ipython-input-4-0b8c3c6b601c> in <module>()
      1 import spacy
----> 2 spacyDe = spacy.load('de_core_news_md')

/opt/conda/lib/python3.6/site-packages/spacy/__init__.py in load(name, **overrides)
     13     if depr_path not in (True, False, None):
     14         deprecation_warning(Warnings.W001.format(path=depr_path))
---> 15     return util.load_model(name, **overrides)
     16 
     17 

/opt/conda/lib/python3.6/site-packages/spacy/util.py in load_model(name, **overrides)
    111     if isinstance(name, basestring_):  # in data dir / shortcut
    112         if name in set([d.name for d in data_path.iterdir()]):
--> 113             return load_model_from_link(name, **overrides)
    114         if is_package(name):  # installed as package
    115             return load_model_from_package(name, **overrides)

/opt/conda/lib/python3.6/site-packages/spacy/util.py in load_model_from_link(name, **overrides)
    128     except AttributeError:
    129         raise IOError(Errors.E051.format(name=name))
--> 130     return cls.load(**overrides)
    131 
    132 

/opt/conda/lib/python3.6/site-packages/spacy/data/de_core_news_md/__init__.py in load(**overrides)
     10 
     11 def load(**overrides):
---> 12     return load_model_from_init_py(__file__, **overrides)

/opt/conda/lib/python3.6/site-packages/spacy/util.py in load_model_from_init_py(init_file, **overrides)
    172     if not model_path.exists():
    173         raise IOError(Errors.E052.format(path=path2str(data_path)))
--> 174     return load_model_from_path(data_path, meta, **overrides)
    175 
    176 

/opt/conda/lib/python3.6/site-packages/spacy/util.py in load_model_from_path(model_path, meta, **overrides)
    155             component = nlp.create_pipe(name, config=config)
    156             nlp.add_pipe(component, name=name)
--> 157     return nlp.from_disk(model_path)
    158 
    159 

/opt/conda/lib/python3.6/site-packages/spacy/language.py in from_disk(self, path, disable)
    657         if not (path / 'vocab').exists():
    658             exclude['vocab'] = True
--> 659         util.from_disk(path, deserializers, exclude)
    660         self._path = path
    661         return self

/opt/conda/lib/python3.6/site-packages/spacy/util.py in from_disk(path, readers, exclude)
    551     for key, reader in readers.items():
    552         if key not in exclude:
--> 553             reader(path / key)
    554     return path
    555 

/opt/conda/lib/python3.6/site-packages/spacy/language.py in <lambda>(p)
    645             ('meta.json', lambda p: self.meta.update(util.read_json(p))),
    646             ('vocab', lambda p: (
--> 647                 self.vocab.from_disk(p) and _fix_pretrained_vectors_name(self))),
    648             ('tokenizer', lambda p: self.tokenizer.from_disk(p, vocab=False)),
    649         ))

vocab.pyx in spacy.vocab.Vocab.from_disk()

strings.pyx in spacy.strings.StringStore.from_disk()

strings.pyx in spacy.strings.StringStore.from_disk()

ValueError: Unexpected character found when decoding array value (2)

## Your Environment
* **spaCy version:** 2.1.0a0
* **Platform:** Linux-4.9.87-linuxkit-aufs-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.3
* **Models:** fr_core_news_md, de_core_news_md, en_core_web_m

**Comment by honnibal** [comment]
Thanks for the report. Could you paste the values you get from `locale`?

**Comment by FritzTheBat** [comment]
That would be:

LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8

Cheers

**Comment by ines** [comment]
Should be fixed in the latest nightly models:

```python
pip install -U spacy-nightly
python -m spacy download de_core_news_md
```

If you still come across an issue, feel free to reopen!
