### ISSUE TITLE
Update vocabulary with words that are OOV

### ISSUE THREAD

**Issue by RutujaWanjari** [explosion/spaCy#2624]
Hello there !
Firstly, Thanks for this great library.

I want to add more words to the spacy vocabulary.
I guess the word is getting added as I can retrieve it using ---
nlp.vocab.__getitem__(u'wassup')
 But the vocab size is not increasing.
Also, I wanted to know how I can set attributes of this new token like lemma_, pos_, tag_, dep_  , etc

This is my code for setting vocab ---
vector = np.random.uniform(-1, 1, (300,))
wassup = nlp.vocab.strings[u'wassup']
nlp.vocab.vectors.add(wassup, vector=vector)
lex = nlp.vocab[u'wassup']
nlp.vocab.set_vector(wassup, vector)

## Environment
* **spaCy version:** 2.0.11
* **Platform:** Linux-4.15.0-29-generic-x86_64-with-debian-buster-sid
* **Python version:** 3.6.4
* **Models:** en_core_web_lg, en_vectors_web_lg, en

Thanks in advance

**Comment by honnibal** [comment]
`lex = nlp.vocab['wassup']` should add `wassup` to the vocab. I'm not thrilled by this API decision at this point, but that's how it's always been.

How are you checking that the vocab size isn't increasing?

**Comment by RutujaWanjari** [comment]
Thanks Honnibal for your answer.
I am checking `nlp.vocab.length` , but its showing same value. Also after updation code I am again checking whether `token.is_oov`  , the result is TRUE.

**Comment by honnibal** [comment]
I'm getting:

```
>>> nlp = spacy.load('en_core_web_lg')
>>> nlp.vocab[u'wassup'].is_oov
False
>>> 'wassup' in nlp.vocab
True
```

**Comment by RutujaWanjari** [comment]
Ok so I am getting:

`'wassup' in nlp.vocab`     TRUE
`nlp.vocab[u'wassup'].is_oov`     TRUE

I don't understand how will be this possible.

Please find the attachments - 
![vocab1](https://user-images.githubusercontent.com/19467081/43767831-93893346-9a53-11e8-851f-12e0b975557d.png)
![vocab2](https://user-images.githubusercontent.com/19467081/43767832-93b98064-9a53-11e8-9f15-36e329a8f73a.png)
![vocab3](https://user-images.githubusercontent.com/19467081/43767833-93f1278a-9a53-11e8-929e-4fd6fd00d16f.png)

**Comment by honnibal** [comment]
If necessary, you can always just write to the `lex.is_oov` value, and set `lex.is_oov = False`. This should let you mark the word as definitely in vocabulary.
