### ISSUE TITLE
visualising NER activations inside spaCy models

### ISSUE THREAD

**Issue by rbhambriiit** [explosion/spaCy#2625]
## Feature description
Wish to check if there are plans/documents around visualising/analysing the activation layers inside the NER models.  Some kind of deconv nets maybe?

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
Not sure. Perhaps a component.

If so, we will tag it as [`project idea`](https://github.com/explosion/spaCy/labels/project%20idea) so other users can take it on.
I think yes.

**Comment by rbhambriiit** [comment]
Motivation:

https://jacobgil.github.io/deeplearning/class-activation-maps

http://cnnlocalization.csail.mit.edu/

**Comment by honnibal** [comment]
I'd like to have an API that made it easier to save intermediate results in the models in general. You might find the example in this thread useful: https://support.prodi.gy/t/highlighting-the-matching-words-for-text-classfication/254/5

That example shows a hack to retain the attention weights from the text classifier. The general technique of finding the thinc layer you're interested in and adding a wrapping listener would apply.

**Comment by rbhambriiit** [comment]
@honnibal 
Any progress on the API for NER to see the activations?

**Comment by ines** [comment]
Merging this with #4338!
