### ISSUE TITLE
Language.to_disk/to_bytes does not save vocab.lex_attr_getters, breaking some functionality

### ISSUE THREAD

**Issue by andrew-christianson** [explosion/spaCy#2628]
`Language.to_disk` and `Language.to_bytes` use the corresponding `Vocab.to_disk` and `Vocab.to_bytes` methods to serialized the `vocab` attribute.  However, those methods don't appear to sufficiently capture features of their object e.g.: 

``` python
import spacy
from spacy.language import Language
from spacy.tokens import Doc
nlp = spacy.load('en')
nlp_rt = Language().from_bytes(nlp.to_bytes())

nlp.to_disk("./test.nlp")
nlp_rt_disk = Language().from_disk("./test.nlp/")

nlp.lang, nlp.vocab.lang # => ('en', 'en')
nlp_rt.lang, nlp_rt.vocab.lang # => (None, '')
nlp_rt_disk.lang, nlp_rt_disk.vocab.lang # => (None, '')
```

This results in some breakage in cases where the docs claim lossless serialization e.g.

``` python
doc = nlp("This is the chunker.")
doc_rt = Doc(nlp_rt.vocab).from_bytes(doc.to_bytes())

list(doc.noun_chunks) # => [the chunker]
list(doc_rt.noun_chunks) # => []
```

interestingly:

``` python
from spacy.lang.en.syntax_iterators import noun_chunks
doc_rt.noun_chunk_iterator = noun_chunks
list(doc_rt.noun_chunks) # => []
```

so it's not just the empty attribute `nlp_rt.vocab.lang` breaking `spacy.tokens.doc._get_chunker` as I first suspected.

This can be worked around by separately serializing the vocab object:

``` python
nlp_rt = Language(vocab=pickle.loads(pickle.dumps(nlp.vocab)))\
  .from_bytes(nlp.to_bytes(disable=['vocab']), disable'=['vocab'])
doc_rt = Doc(nlp_rt.vocab).from_bytes(doc.to_bytes())
list(doc_rt.noun_chunks) # => [the chunker]

```

but that's a bit ugly.  Is this expected behavior for to_bytes/to_disk? 

## Your Environment
* **spaCy version:** 2.0.12
* **Platform:** Darwin-17.7.0-x86_64-i386-64bit
* **Python version:** 3.6.5
* **Models:** en_core_web_lg, en

**Comment by honnibal** [comment]
`spacy.load('en')` creates an instance of the class `English`, which is a subclass of `Language`. So yes, if you do `Language().from_bytes()` you get the wrong result, as you're deserializing into the wrong language.

I suppose we could check this, but it would cause problems if someone is using a language code that isn't hard-coded into spaCy. The correct usage is:

```
import spacy
nlp = spacy.load('en')
nlp_rt = spacy.blank(nlp.lang).from_bytes(nlp.to_bytes())
```

You can also use `spacy.util.get_lang_class('en')`.

Reading the language from the byte-string is currently a bit awkward. If you don't have the language code, you should be able to get it by deserializing the bytes with msgpack, and reading the key `msg['meta']['lang']`

**Comment by honnibal** [comment]
@ines Do you think we should have a warning for this in `Language.from_bytes` and `Language.from_disk`? I'm not sure an error is a good idea, but a warning probably is.

**Comment by andrew-christianson** [comment]
@honnibal thanks for the help!  Clearly misuse on my part, but my 0.02 is that a warning would be helpful in that situation.

I'd also note that `Language().from_disk()`is the example used in the [API docs](https://spacy.io/api/language#from_disk):

```python
from spacy.language import Language
nlp = Language().from_disk('/path/to/models')
```

If that's not the prescribed usage, perhaps that example could be changed or clarified?

**Comment by ines** [comment]
Yes, +1 to the warning. Will have a look at this and implement it.

> If that's not the prescribed usage, perhaps that example could be changed or clarified?

Ahh yes, I see your point. The thing is that the example here is supposed to explicitly document the `Language.from_disk` method. But I think it'd definitely make sense to add a second example, and maybe a note that you'd commonly do this via a *subclass* of `Language`, like `English` etc.
