### ISSUE TITLE
Implementing custom POS Tagger in Spacy over existing english model fails

### ISSUE THREAD

**Issue by rohanreddy91** [explosion/spaCy#2635]
_spaCy version      2.0.11         
Platform           Darwin-16.7.0-x86_64-i386-64bit
Python version     3.6.6_          

I am trying to retrain the existing POS Tagger in spacy to display the proper tags for certain misclassified words using the code below. But it gives me this error on 'optimizer = nlp.begin_training()
' :

> Warning: Unnamed vectors -- this won't allow multiple vectors models to be loaded. (Shape: (0, 0))

```
from spacy.vocab import Vocab
from spacy.tokens import Doc
from spacy.gold import GoldParse


nlp = spacy.load('en_core_web_sm')
optimizer = nlp.begin_training()
vocab = Vocab(tag_map={})
doc = Doc(vocab, words=[word for word in ['ThermostatFailedOpen','ThermostatFailedClose','BlahDeBlah']])
gold = GoldParse(doc, tags=['NNP']*3)
nlp.update([doc], [gold], drop=0, sgd=optimizer)
```

Also, when i try to check to see if the tags have been classified correctly using the code below

```
doc = nlp('If ThermostatFailedOpen moves from false to true, we are going to party')
for token in doc:
    print(token.text, token.lemma_, token.pos_, token.tag_, token.dep_,
          token.shape_, token.is_alpha, token.is_stop)
```

> ThermostatFailedOpen thermostatfailedopen VERB VB nsubj XxxxxXxxxxXxxx True False

The words are not classified correctly (as expected I guess due to the error)! Any insights on how to fix this?

**Comment by honnibal** [comment]
The warning isn't problematic in your situation, and future versions should have disabled it when the vector size is 0.

Instead your main issue is that you're only training with one example, after randomly initialising the weights with `nlp.begin_training()`. You should probably just call `nlp.update()`, as your data is English-like enough to make use of the existing model.
