### ISSUE TITLE
Handling of whitespace in char_span is unclear

### ISSUE THREAD

**Issue by jnothman** [explosion/spaCy#2637]
`Doc.char_span` is documented as:
```
Create a #[code Span] object from the slice #[code doc.text[start : end]].
Returns #[code None] if the character indices don't map to a valid span.
```

When working with standoff character span annotations, they might not be perfectly aligned to token boundaries. And yet the handling of whitespace in `char_span` is undocumented, and perhaps too strict to be useful in many applications.

Current behaviour:

```py
import spacy
nlp = spacy.load('en')

doc = nlp(' a b ')
for start in range(5):
    for stop in range(start, 5):
        print(start, stop, doc.char_span(start, stop), '', sep='|')
```
produces
```
0|0|None|
0|1| |
0|2| a|
0|3|None|
0|4| a b|
1|1||
1|2|a|
1|3|None|
1|4|a b|
2|2|None|
2|3|None|
2|4|None|
3|3|None|
3|4|b|
4|4|None|
```

A whitespace-lenient approach would produce:

```
0|0|None|
0|1| |
0|2| a|
0|3| a|
0|4| a b|
1|1||
1|2|a|
1|3|a|
1|4|a b|
2|2|None|
2|3|None|
2|4|b|
3|3|None|
3|4|b|
4|4|None|
```

or something... exact semantics might need a bit of work, but the idea is to focus on the token spans, not the whitespace.

## Info about spaCy

* **spaCy version:** 2.0.12
* **Models:** en
* **Platform:** Darwin-17.7.0-x86_64-i386-64bit
* **Python version:** 3.5.2

**Comment by honnibal** [comment]
I think it would be pretty bad behaviour if `len(span.text)` didn't necessarily equal `end_char - start_char`. I much prefer the stricter approach here, and I think it's the one the user should assume.

If you take a slice of characters that doesn't start and end on a token boundary, you get `None`. The `Span` is uniquely identified by a `(token_start, token_end, label, doc)` tuple. If you allowed it to be addressed the way you suggest, this wouldn't be true --- there would be multiple start and end character positions for a given token span.

**Comment by jnothman** [comment]
Depends what your intention is in providing a public API for this. My use case is converting inline bracketing annotations to token-level standoff, but it would apply for character level standoff too, that you would want to disregard whitespace in acquiring a span.

I don't see how being lenient about whitespace would violate the unique identification of a span by (doc, token_start, token_end, label)... it would just mean that there was a many-to-one mapping between character spans and Spans.

My proposal would to offer it as a `strict=True` or `ignore_space=False` option. In my conversion of character-to-token spans, I'm using:

```py

def standoff_spans(doc, entities):
    char_to_tok = {}
    offset = 0
    for i, tok in enumerate(doc):
        if tok.is_space:
            continue
        for c in range(offset, tok.idx + 1):
            char_to_tok[c] = i
        offset = tok.idx + len(tok.text)
    for c in range(offset, len(str(doc)) + 1):
        char_to_tok[c] = i + 1

    for start, end, tag in entities:
        yield doc[char_to_tok[start]:char_to_tok[end]], tag
```

but there are computationally simpler ways to do it.

**Comment by jnothman** [comment]
I have people in the education faculty doing ad hoc annotation with an ad
hoc scheme. They inserted spaces around all tags and it was easier for me
not to clean them up.

but i don't really see why you would be particular about whether a tag
appeared before or after some whitespace in general

**Comment by jnothman** [comment]
in the first instance I believe the current behaviour deserves clearer
documentation

**Comment by honnibal** [comment]
> I have people in the education faculty doing ad hoc annotation with an ad hoc scheme. They inserted spaces around all tags and it was easier for me not to clean them up.

Cmon! Obviously that's not a basis to change the API :). Go fix your data.

**Comment by jnothman** [comment]
I don't entirely agree. I think the documentation is ambiguous. And I think
it would be a common application of this function, where instead you have
only helped the user with the case that is trivial to implement themselves

**Comment by norrishd** [comment]
@honnibal I got stuck on this same issue for a while yesterday (using spaCy 2.0.11), because the documentation available through introspection with `help(doc.char_span)`  is missing a key line included in the online documentation - "Returns None if the character indices don't map to a valid span." So I didn't realise this was the expected behaviour.

I guess the documentation is generated automatically, and 2.0.11 is just a little behind the 8-ball :-)
