### ISSUE TITLE
Space symbol at the end of the returned string when using token.string

### ISSUE THREAD

**Issue by prokopevaleksey** [explosion/spaCy#2638]
When I use `token.string` I sometimes end up with a space symbol at the end of returned string. However, when I use `str(token)` everything seems to be fine. This can be reproduced on a simple example shown below.

## How to reproduce the behaviour

`[token.string for token in nlp('So i can go out and play.')]`

\>\>\>`['So ', 'i ', 'can ', 'go ', 'out ', 'and ', 'play', '.']`

`[str(token) for token in nlp('So i can go out and play.')]`

\>\>\>`['So', 'i', 'can', 'go', 'out', 'and', 'play', '.']`

## Your Environment

* **spaCy version:** 2.0.11
* **Platform:** Linux-4.15.0-29-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.5
* **Models:** en_core_web_sm, en_core_web_lg, en_vectors_web_lg, en_core_web_md

**Comment by honnibal** [comment]
The `token.string` attribute is deprecated. You should use either `token.text` or `token.text_with_ws`.

In very early versions of spaCy, `.string` was used as the name for the text plus trailing whitespace attribute. This is obviously bad, so it's been changed to `text_with_ws`.
