### ISSUE TITLE
Documentation typo: descendent -> descendant

### ISSUE THREAD

**Issue by jnothman** [explosion/spaCy#2640]
I'd fix it, but again, can't be bothered with the contributor agreement...

**Comment by honnibal** [comment]
Thanks I guess. But why so grumpy?

**Comment by jnothman** [comment]
I had not expected to come across grumpy. I'll just sign the thing one
day...

Though I did have good reasons to be grumpy. if you'd like me to lie down
on a couch and talk about it, we can do that :)
