### ISSUE TITLE
ROUGE-SCORE for Statistical MT not found 

### ISSUE THREAD

**Issue by 53X** [explosion/spaCy#2641]
## Feature description

**ROUGE-SCORE** is a evaluation metric in **Statistical MT** for checking the quality of a system generated translation w.r.t reference translations. Reference translations are human generated translations. It was introduced in [this paper](www.aclweb.org/anthology/W04-1013).

It is used in all MT related tasks, text-summarization etc.

If this is issue is a go, I can make the PR.

**Comment by honnibal** [comment]
We'd prefer things like this to be in a separate library. spaCy doesn't really do text generation, and in general we prefer to only collect functions which are necessary internally, which use other spaCy internals, or which relate to the core spaCy data structures.
