### ISSUE TITLE
-ing forms are handled incorrectly in spaCy's English dependency parser model

### ISSUE THREAD

**Issue by mikpanko** [explosion/spaCy#2642]
I have noticed that -ing forms (see definitions [here](https://en.wikipedia.org/wiki/-ing) and [here](https://www.ef.edu/english-resources/english-grammar/ing-forms/)) are handled inconsistently and often incorrectly in spaCy's English dependency parser model. For example, gerunds and pure nouns are sometimes mislabeled with `csubj` instead of `nsubj`:

`Clicking on the button relaxes him.` --> `nsubj` ([displaCy Dependency Visualizer](https://explosion.ai/demos/displacy?text=Clicking%20on%20the%20button%20relaxes%20him.&model=en_core_web_sm&cpu=1&cph=0))
`Clicking on a button relaxes him.` --> `csubj` ([displaCy Dependency Visualizer](https://explosion.ai/demos/displacy?text=Clicking%20on%20a%20button%20relaxes%20him.&model=en_core_web_sm&cpu=1&cph=0))
`Loud shouting is rude.` --> `csubj` ([displaCy Dependency Visualizer](https://explosion.ai/demos/displacy?text=Loud%20shouting%20is%20rude.&model=en_core_web_sm&cpu=1&cph=0))

Is it possible to train the model better on -ing forms?

**Comment by ines** [comment]
Merging this with #3052. We've now added a master thread for incorrect predictions and related reports – see the issue for more details.
