### ISSUE TITLE
Missing link on how to convert the training data in any python data structure to Json format required for training NER model

### ISSUE THREAD

**Issue by eswar3** [explosion/spaCy#2643]
## Which page or section is this issue related to?

https://spacy.io/api/cli#convert

1) No explanation available about supported input file formats to this command. The link that I feel missing is, let us say that I have my training data in a python list/tuple format, how to feed that to convert command to get a JSON format required for NER training
2) BILOU not available under converters. If not supported currently, please mention it here. it will be so much more easier for someone looking for this information

**Comment by eswar3** [comment]
I just found an issue raised for the same missing link in the documentation. Kindly update the documenation.

Issue : https://github.com/explosion/spaCy/issues/2515
Suggested Solution: https://github.com/rbhambriiit/home/blob/master/spacy_enhanced/train_data_to_json.py

**Comment by ines** [comment]
Here are the details for the JSON format, which should be linked in the intro paragraph as "JSON Format": https://spacy.io/api/annotation#json-input

> BILOU not available under converters. If not supported currently, please mention it here. it will be so much more easier for someone looking for this information

The converters specifically target *file formats* and work mostly on file extensions. Maybe it'd be more clear if we called them "file format converters"? I'll change this in the docs. Btw, you can find the available converter functions here: https://github.com/explosion/spaCy/tree/master/spacy/cli/converters

If you're just looking to convert BILUO tags into the offset format, you might also find the `spacy.gold.offsets_from_biluo_tags` helper useful ([see here](https://spacy.io/api/goldparse#offsets_from_biluo_tags)).
