### ISSUE TITLE
Problem with vizualization of parsed sentence

### ISSUE THREAD

**Issue by pikaliov** [explosion/spaCy#2646]
I have problem with vizualizer of Spacy. It doesnt outputs arcs(syntax).
Example:

![this-is-another-one](https://user-images.githubusercontent.com/17013861/43833360-236ac424-9b13-11e8-9e47-1e58b3932c6f.png)

* Operating System:Linux Mint 19
* Python Version Used:3.6
* spaCy Version Used:2.012

**Comment by ines** [comment]
Thanks for the report! Could you share the code you used to produce the visualization? And could you post the result of running `displacy.render` (so the generated HTML/SVG markup)?
