### ISSUE TITLE
most_similar() not working as expected (KeyError)

### ISSUE THREAD

**Issue by neurotroph** [explosion/spaCy#2648]
## How to reproduce the behaviour
Using the `en_core_web_lg` model, I try to find the most similar word(s) for a given word or word vector:
```
import spacy
import numpy as np

nlp = spacy.load("en_core_web_lg")
tvec = nlp(u"dog").vector
# According to documentation in the source code (https://github.com/explosion/spaCy/blob/3141e04822a8c40e0d64e51a040305ade3f66d8c/spacy/vectors.pyx#L269), an array with one or more vectors should be supplied
nlp.vocab.vectors.most_similar(np.array([tvec]))
```
This yields a `KeyError`:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "vectors.pyx", line 302, in spacy.vectors.Vectors.most_similar
KeyError: 0
```

## Your Environment
* **spaCy version:** 2.0.11
* **Platform:** Windows-10-10.0.16299-SP0
* **Python version:** 3.6.6

**Comment by poke1024** [comment]
Same problem here :(

spacy 2.0.11, macOS 10.13.6, python 3.6.6

**Comment by ahmedmagdiosman** [comment]
Same issue :sob: 
spacy 2.0.12, Ubuntu 16.04, python 3.6

**Comment by PadenZach** [comment]
Also having this issue...

    spaCy version      2.0.12         
    Location           /usr/lib/python3.7/site-packages/spacy
    Platform           Linux-4.19.4-arch1-1-ARCH-x86_64-with-arch-18.9-Minimal-ISO-Rolling
    Python version     3.7.1          
    Models             en_core_web_lg 

Tried passing the vector in several ways, and all end up giving an error.
