### ISSUE TITLE
Cannot install spacy on virtualenv with python 3.6 getting  thinc error

### ISSUE THREAD

**Issue by ereday** [explosion/spaCy#2650]
When I try to install spacy on my virtual environment I got an error. The error message was very huge but I put the last part of it below. 

## How to reproduce the problem

python3.6 -m venv mytest
source mytest/bin/activate
pip install --upgrade pip
Cache entry deserialization failed, entry ignored
Collecting pip
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/5f/25/e52d3f31441505a5f3af41213346e5b6c221c9e086a166f3703d2ddaf940/pip-18.0-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 690kB/s
Installing collected packages: pip
  Found existing installation: pip 9.0.3
    Uninstalling pip-9.0.3:
      Successfully uninstalled pip-9.0.3
pip install -U spacy
```bash
  /usr/bin/nvcc -I/usr/include/python3.6m -I/tmp/pip-install-trfgtpzj/thinc/include -I/usr/include -I/home/users/mytest/include -I/usr/include/python3.6m -c include/_cuda_shim.cu -o build/temp.linux-x86_64-3.6/include/_cuda_shim.o -arch=sm_30 --ptxas-options=-v -c --compiler-options '-fPIC'
    /usr/include/c++/8/type_traits(1049): error: type name is not allowed

    /usr/include/c++/8/type_traits(1049): error: type name is not allowed

    /usr/include/c++/8/type_traits(1049): error: identifier "__is_assignable" is undefined

    3 errors detected in the compilation of "/tmp/tmpxft_001bc913_00000000-6__cuda_shim.cpp1.ii".
    error: command '/usr/bin/nvcc' failed with exit status 1

    ----------------------------------------
Command "/home/users/mytest/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-trfgtpzj/thinc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ofshblp8/install-record.txt --single-version-externally-managed --compile --install-headers /home/users/mytest/include/site/python3.6/thinc" failed with error code 1 in /tmp/pip-install-trfgtpzj/thinc/
```

## Your Environment

* Operating System: Fedora release 28
* Python Version Used: 3.6
* spaCy Version Used:
* Environment Information:

**Comment by BarclayII** [comment]
Are you using nvcc from the fedora-nvidia repository?  If so, you need to manually change the `compile_options` in `setup.py` to include the option `-ccbin cuda-gcc`.
```python
compile_options =  {'msvc'  : ['/Ox', '/EHsc'],
                    'other' : {
                        'gcc': ['-O2', '-Wno-strict-prototypes', '-Wno-unused-function'],
                        'nvcc': ['-ccbin', 'cuda-gcc', '-arch=sm_30', '--ptxas-options=-v', '-c', '--compiler-options', "'-fPIC'"]}}
```
The reason is that NVCC does not support GCC 8, and you need to tell NVCC to use the compatible version (which can be installed by `cuda-gcc-*` packages)
