### ISSUE TITLE
Tokenizer doesn't handle numbers followed by punctuation

### ISSUE THREAD

**Issue by AmitMY** [explosion/spaCy#2656]
## How to reproduce the behaviour
For the sentence:
> I went for 40.3, and got home by 10.0.

The tokenizer:
```python
import spacy
from spacy.tokenizer import Tokenizer

nlp = spacy.load('en')
tokenizer = Tokenizer(nlp.vocab)
```

returns: 
> ['I', 'went', 'for', '40.3,', 'and', 'got', 'home', 'by', '10.0.']

While NLTK word_tokenize returns: (correctly)
> ['I', 'went', 'for', '40.3', ',', 'and', 'got', 'home', 'by', '10.0', '.']

It seems like numbers with decimal points, followed by any punctuation (even "40.3.,.,.,") isn't separated into correct tokens.

I would use NLTK, except it can't handle unicode...

## Your Environment
* **Python version:** 2.7.15
* **Platform:** Windows-10-10.0.17134
* **spaCy version:** 2.0.11
* **Models:** en, xx

**Comment by ines** [comment]
Merging this with the master issue in #1642!
