### ISSUE TITLE
Doc Example with bad html tags: Html tags are not marked as stop words

### ISSUE THREAD

**Issue by romikforest** [explosion/spaCy#2657]
The sample from the docs https://spacy.io/usage/linguistic-features (with small changes to demonstrate an error) :
```
import spacy
from spacy.matcher import Matcher
from spacy.tokens import Token

# we're using a class because the component needs to be initialised with
# the shared vocab via the nlp object
class BadHTMLMerger(object):
    def __init__(self, nlp):
        # register a new token extension to flag bad HTML
        Token.set_extension('bad_html', default=False, force=True)
        self.matcher = Matcher(nlp.vocab)
        self.matcher.add('BAD_HTML', None,
            [{'ORTH': '<'}, {'LOWER': 'br'}, {'ORTH': '>'}],
            [{'ORTH': '<'}, {'LOWER': 'br/'}, {'ORTH': '>'}])

    def __call__(self, doc):
        # this method is invoked when the component is called on a Doc
        matches = self.matcher(doc)
        spans = []  # collect the matched spans here
        for match_id, start, end in matches:
            spans.append(doc[start:end])
        for span in spans:
            span.merge()   # merge
            for token in span:
                token._.bad_html = True  # mark token as bad HTML
                doc.vocab[token.text].is_stop = True  # mark lexeme as stop word
        return doc

nlp = spacy.load('en_core_web_sm')
html_merger = BadHTMLMerger(nlp)
nlp.add_pipe(html_merger, last=True)  # add component to the pipeline
doc = nlp(u"Hello<br>world! <br/> This <br> is a test.")
for token in doc:
    print(token.text, token._.bad_html, token.is_stop)

```

Here the first `<br>` is not marked as stop word. And `token.is_stop` is not writable. How I can mark all <br> tags as stop words?

spacy 2.0.11, python Python 3.6.6 :: Anaconda custom (64-bit), win 10 64 bit

**Comment by ines** [comment]
Thanks for the report! It looks like this is potentially related to the caching of lexical attributes (which are also included in the model data)? The first instance of lexeme doesn't have the correct flags set, while any subsequent lexemes do. Also, if you create your `nlp` object from just the `English` language class with no model data loaded in, it works as expected:

```python
from spacy.lang.en import English
nlp = English()
```

By the way, the reason `Token.is_stop` is not writable is that it's a property on the *lexeme*, the context-insensitive entry in the vocabulary. You can find some background on this (including planned changes in the upcoming version) in #2390.

**Comment by jeyendranbalakrishnan** [comment]
A different approach might avoid this problem: Use an HTML parser like BeautifulSoup4 to first parse the text as a fragment (ie., doesn't need DOCTYPE or <html> wrappers), then use get_text() to extract the text, which will yield the raw text minus all the HTML formatting. This can then be passed to nlp(...).
