### ISSUE TITLE
Wrong POS prediction

### ISSUE THREAD

**Issue by pbnsilva** [explosion/spaCy#2665]
## How to reproduce the behaviour
```python
nlp = spacy.load('en')

print(nlp('dungarees black')[0].pos_)
# outputs NOUN

print(nlp('dungarees red')[0].pos_)
# outputs VERB
```

Expected `NOUN` in both cases.

## Your Environment

* **spaCy version:** 2.0.12
* **Platform:** Darwin-17.6.0-x86_64-i386-64bit
* **Python version:** 3.6.5
* **Models:** en, __cache__

**Comment by ines** [comment]
The process of recognising part-of-speech tags is **statistical** and the model was trained on examples of those tags *in context*. POS tags are context-sensitive by definition – if you just see the word "duck" or "love", there's no way to know whether it's a verb or a noun (neither for a human, nor for a machine). So it's expected that the results won't be very meaningful if you only pass in single words. 

It's also important to keep in mind that the pre-trained models distributed with the library are baseline models that were tuned for the best possible compromise of speed, size, and accuracy and make it easy to get started building your own systems. You **almost always** want to adjust the model to your specific domain if extracting named entities is important to you. You can find more details on this in the [documentation on training and updating models](https://spacy.io/usage/training).
