### ISSUE TITLE
displacy NER example from jupyter notebook not working

### ISSUE THREAD

**Issue by NiklasDL** [explosion/spaCy#2666]
I'm using the code from the website to run a web server:

```

import spacy
from spacy import displacy

text = """But Google is starting from behind. The company made a late push
into hardware, and Apple’s Siri, available on iPhones, and Amazon’s Alexa
software, which runs on its Echo and Dot devices, have clear leads in
consumer adoption."""

nlp = spacy.load('en_core_web_lg')
doc = nlp(text)
displacy.serve(doc, style='ent')

```

My jupyter notebooks states

```
    Serving on port 5000...
    Using the 'ent' visualizer
```

So I assume the code is running properly. 

Yet when I try to reach localhost/5000 or http://127.0.0.1/5000, my firefox says:

> Unable to connect
Firefox can’t establish a connection to the server at 127.0.0.1.
The site could be temporarily unavailable or too busy. Try again in a few moments.
If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

I have run multiple flask apps from this machine where I was always able to start a web service.

## My Environment
* **spaCy version:** 2.0.11
* **Python version:** 3.5.5
* **Models:** en_core_web_lg
* **Platform:** Windows-10-10.0.14393-SP0

Edit: it does not work with both, a jupyter notebook as well as a standard .py script.

**Comment by ines** [comment]
If you're already in a Jupyter Notebook, you're already running a web server – so there shouldn't usually be a need to run `displacy.serve`. Instead, you can run `displacy.render` and set `jupyter=True`. This will call into the IPython methods and render the output in a cell, like this:

![displacy_jupyter](https://user-images.githubusercontent.com/13643239/44100093-7b632ea2-9fe4-11e8-8ef1-da81951c7ec4.jpg)

You can find more details on this in the "Visualizers" section in the docs:
https://spacy.io/usage/visualizers#jupyter

If it doesn't serve within a regular Python script, this might point to a configuration issue. displaCy doesn't do anything sophisticated, it just outputs the HTML and serves it via a `wsgiref.simple_server`. You can find the implementation [here](https://github.com/explosion/spaCy/blob/fe94e696d3dc5abdfb846d152ebf489518419513/spacy/displacy/__init__.py#L48). So if you prefer, you can probably get the same thing running super quickly with Flask, too.

**Comment by NiklasDL** [comment]
Meh, thank you both for your response. The problem was Indeed attributed to the „/„ instead of the „:“. I don‘t know why I was not able to figure this out on my own.. guess it‘s the heat 😰

**Comment by ines** [comment]
No worries, I can totally relate!
