### ISSUE TITLE
Are there fixed numerical values for POS tags?

### ISSUE THREAD

**Issue by mkraemerx** [explosion/spaCy#2667]
When I use spacy with the german language model for POS tagging, I seem to get the same numerical IDs for the tags every time, like 95 for PROPN. But I did not find any lookup table in the code.

Is there any fixed mapping for POS tag codes and tags? And if not, is there a value range? I'd like to use the numerical values for further processing in torchtext, but I need to figure out non-destructive additional values for <unk>, <pad> etc..

I used 2.0.11 on MacOS with python 3.7

**Comment by ines** [comment]
Hi! Sorry, this could have probably been documented better – I think you're looking for the `spacy.symbols.IDS`, which is a dictionary mapping the built-in symbols to their IDs (see [`symbols.pyx`](https://github.com/explosion/spaCy/blob/master/spacy/symbols.pyx) and [`symbols.pxd`](https://github.com/explosion/spaCy/blob/master/spacy/symbols.pxd) for the enum).

As of v2.x, spaCy encodes all strings to hashes, so you can also expect IDs to always map to the same strings, and vice versa. You'll still need the vocab to resolve the hashes to strings – but the token text `"hallo"` for instance will always be encoded to the same `ORTH` value, not matter which vocab or model you're using. See [this docs section](https://spacy.io/usage/spacy-101#vocab) for some background and examples.

**Comment by mkraemerx** [comment]
Thanks for the quick response.

I was indeed looking for the enum of the symbols. I've seen it just as a listing, but I didn't realize that the IDs are just counted upwards in the order of occurrence in that file.
