### ISSUE TITLE
How to convert the data to json format that the cli accepts for ner ?

### ISSUE THREAD

**Issue by pdcoded** [explosion/spaCy#2669]
## Which page or section is this issue related to?

@honnibal There should have been be atleast one script that takes this sort of data 

TRAIN_DATA = [
    ('Who is Shaka Khan?', {
        'entities': [(7, 17, 'PERSON')]
    }),
    ('I like London and Berlin.', {
        'entities': [(7, 13, 'LOC'), (18, 24, 'LOC')]
    })
]

and converts it into the json format accepted for large training using cli (let's say bilou format) .  Or can someone point out the exact steps coz I am facing a lot of errors using the standard cli convert

**Comment by honnibal** [comment]
In the latest nightly, v2.1.0a1, there's now a method that takes a list of `Doc` objects and writes out the json format: https://github.com/explosion/spaCy/blob/develop/spacy/gold.pyx#L571

If you're not using the nightly, you should still be able to copy-paste that to do what you need. See here for an example script that does the conversion; https://github.com/explosion/spaCy/blob/develop/spacy/cli/converters/jsonl2json.py

If you're using the v2.1.0a1 nightly, you should be able to just get your data into a jsonl format with the offsets referring to characters, and then run `spacy convert /path/to/jsonl`

**Comment by rbhambriiit** [comment]
See: https://github.com/explosion/spaCy/issues/2515
