### ISSUE TITLE
Matcher pattern related issue

### ISSUE THREAD

**Issue by mattkallo** [explosion/spaCy#2670]
Hi, 

Shouldn't the below pattern match the text? - "John Doe invests in one more stock in China."

pattern = [{'LEMMA': 'invest'}, {'LOWER': 'china'}]
matcher.add('JOHN', on_match, pattern)

It could be an issue with my understanding of how this works. Its not matching till I make the China optional by adding - 'OP': '?'

Pls let me know.

## Your Environment
* **Python version:** 2.7.10
* **Platform:** Darwin-17.3.0-x86_64-i386-64bit
* **spaCy version:** 2.0.5
* **Models:** en_glove_cc_300_1m_vectors-1.0.0, en-1.1.0, en_core_web_lg, en, __cache__

* Operating System:
macOS Sierra
* Python Version Used:
2.7.10
* spaCy Version Used:
2.0.5

**Comment by ned2** [comment]
I might have uncovered something that is is still a little fishy in @mattkallo's example, even on `spacy-nightly`.

```python
import spacy
from spacy.matcher import Matcher
nlp = spacy.load('en_core_web_sm')

def on_match(matcher, doc, id, matches):
    print('Matched!', matches)

matcher = Matcher(nlp.vocab)

matcher.add('JOHN', on_match, [{'LEMMA': 'invest'}, {'OP': '*'}, {'LOWER': 'china'}])
doc = nlp("John Doe invests in one more stock in China.")

for match in matcher(doc):
    print(match)
```
The above snipped does successfully find a match, printing this:

    (10603582739829208913, 2, 9)

However the `on_match` function does not fire.

The following snippet on the other hand, which has the greedy wildcard removed (and an updated string which matches) *does* cause the `on_match` function to fire:

```python
import spacy
from spacy.matcher import Matcher
nlp = spacy.load('en_core_web_sm')

def on_match(matcher, doc, id, matches):
    print('Matched!', matches)

matcher = Matcher(nlp.vocab)

matcher.add('JOHN', on_match, [{'LEMMA': 'invest'}, {'LOWER': 'china'}])
doc = nlp("John Doe invests China.")

for match in matcher(doc):
    print(match)
```
Outputting this: 

```
Matched! [(15211191707941042503, 2, 4)]
(15211191707941042503, 2, 4)
```

**Comment by ned2** [comment]
Just done over at #2675!

Note also that this behaviour is also present in 2.0.12
