### ISSUE TITLE
[v2.1] TextCategorizer fails at inference time because of 'drop' being None

### ISSUE THREAD

**Issue by thomasopsomer** [explosion/spaCy#2684]
## How to reproduce the behaviour

Hi,

I just tried the new pre release of spacy 2.1, and there is an issue with the `TextCategorizer` at inference time. The problem is that the `drop` parameter being `None` in the forward pass break the `concatenate_lists` function. To reproduce:
```python
import spacy
from spacy.pipeline import TextCategorizer
from spacy.gold import GoldParse

nlp = spacy.load("en_core_web_md")
textcat = TextCategorizer(nlp.vocab, pretrained_dims=300)

for label in ["cat_1", "cat_2", "cat_3"]:
    textcat.add_label(label)

nlp.add_pipe(textcat)

doc = nlp.tokenizer("Apple builds Iphones.")
cats = {"cat_1": True, "cat_2": False, "cat_3": True}
gold = GoldParse(doc, cats=cats)
with nlp.disable_pipes(*["ner", "tagger", "parser"]):
    optimizer = nlp.begin_training()
    losses = {}
    nlp.update([doc], [gold], sgd=optimizer, drop=0.2, losses=losses)

# inference
nlp("Apple builds Iphones.").cats
```
it results in:
```
  File "/Users/thomasopsomer/Envs/spacy-nightly/lib/python3.6/site-packages/thinc/api.py", line 61, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "<stdin>", line 15, in concatenate_lists_fwd
TypeError: unsupported operand type(s) for *=: 'NoneType' and 'float'
```

And just a comment on the textcat, it's a bit strange that the pretrained vectors are not used by default when available. 

btw speed improvement in v2.1 are awesome :) about 30% !

## Your Environment

* **spaCy version:** 2.1.0a1
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **Python version:** 3.6.2
* **Models:** en, en_core_web_md

**Comment by honnibal** [comment]
Thanks. That's two bugs, really --- we should be using the vectors if they're available by default.

**Comment by honnibal** [comment]
Both should be fixed now.
