### ISSUE TITLE
Prodigy initialization error 

### ISSUE THREAD

**Issue by mohitshopin** [explosion/spaCy#2686]
I am not able to initiate web server for prodigy, in https://prodi.gy/ steps for mac-os is available, i am using GCP(linux x_86_64), please provide  manual for same, I have tried looking for prodigy in git,but i am not able to find any repo.

**Comment by ines** [comment]
For everything related to Prodigy, see the Prodigy support forum: [https://support.prodi.gy](https://support.prodi.gy)

You can find more details on the installation process in your `PRODIGY_README.html` or [on this page](https://prodi.gy/docs/). If you still encounter problems and decide to post on the Prodigy forum, make sure to include more details on your error, including the command you ran and the full stack trace of any errors. This makes it easier to help.
