### ISSUE TITLE
Preserve boundaries and content for list of sentences input

### ISSUE THREAD

**Issue by j-rausch** [explosion/spaCy#2694]
## Description
I would like to use spaCy to generate NLP features for a document that is represented as a list of sentences.

At a different point in my script, I used spaCy's sentence splitter (https://spacy.io/usage/linguistic-features#sbd-component) to split different paragraphs into sentences and gathered all sentence strings in one list. Is is important to preserve this separation for further processing.

I would now like to enrich these sentences with additional NLP features by feeding them all into the spaCy pipeline as a single input. The elements of `doc.sents` should then correspond to the sentences in the input list.

As it is not possible to do following:
```
nlp = spacy.load('en')
doc = nlp(list_of_sentences)
```
, I see the option of concatenating all strings with a unique custom string and applying custom sentence boundaries (https://spacy.io/usage/linguistic-features#sbd-manual). However, it seems like in this case the custom string would be included as a token in the parsed document (such as the `...` separators in the second linked example). This would require additional filtering of the document for this custom string.

I am wondering whether there are more straight-forward ways to feed the list of sentences through into the NLP pipeline, while preserving the original sentence separation and content.

## Your Environment
* Python Version Used: 3.6
* spaCy Version Used: 2.0.12

**Comment by honnibal** [comment]
This example might be helpful for you: https://github.com/explosion/spaCy/blob/master/examples/pipeline/custom_sentence_segmentation.py

What we do here is set the `token.is_sent_start` attribute, which constrains the way the parser assigns sentence boundaries. You should get a single `Doc` that has sentences conforming to the rules you set. You can use the `SentenceSegmenter.split_on_punct(doc)` static method as the rules to get the same behaviour you're currently using.
