### ISSUE TITLE
nlp.update() crashes with batched data

### ISSUE THREAD

**Issue by opus111** [explosion/spaCy#2695]
## How to reproduce the behaviour

Updating NER models with CONLL2003 data.  Python exits with no message

Crash is controlled by the language loaded and the size of batch.  For example a blank language allows a batch size of 2000, 'en' limits to 512, and 'en_core_web_lg' requires a batch size of 32

                nlp = spacy.load('en_core_web_lg')
                ...
                for i in range(0, len(train_data), batch_size):
                   ts = texts[i:i+batch_size]
                   an = annotations[i:i+batch_size]
                   nlp.update(
                       ts,  
                       an, 
                       drop=0.5,  
                       sgd=optimizer,  
                       losses=losses)

## Your Environment

* Operating System: OSX 10.13.6
* Python Version Used: 3.6
* spaCy Version Used: 2.0.12
* Environment Information: virtualenv

**Comment by barneygovan** [comment]
Same problem here.  I can confirm that with `en_core_web_lg` and batch >= 16 leads to a crash eventually (unpredictable number of batches processed).  Keeping the batch number low (and using `minibatch` with sizes generated by `compounding(start=1, stop=16, compound=1.001)`) seems to keep it stable.

## My Environment:
* Operating System: OSX 10.13.6
* Python: 3.6.2
* spaCy: 2.0.12 (also happening with 2.0.11)
* Jupyter lab inside virtualenv

**Comment by barneygovan** [comment]
Seems to be related to https://github.com/explosion/spaCy/issues/1969

**Comment by honnibal** [comment]
Merging as a duplicate to #1969
