### ISSUE TITLE
Can we increase the phraseMatcher max_length?

### ISSUE THREAD

**Issue by tiru1930** [explosion/spaCy#2698]
What are the things we need to take care to increase phrase Matcher max_lenght from 10 to the value that  i want.

**Comment by honnibal** [comment]
This constraint is lifted in v2.1. You can try the alpha using the `spacy-nightly` package:

```
python -m pip install spacy-nightly
python -m spacy download en_core_web_md
python -m spacy validate # Check you don't have other models you need to update
```
