### ISSUE TITLE
Semantic Similarity 

### ISSUE THREAD

**Issue by pnandhini11** [explosion/spaCy#2699]
I am new to Spacy and understood it works faster and has more feature when compare to other libraries. So started exploring Spacy but got stuck at one point when I was working in a project to find sentiment analysis for the customer feedback. 

I have input as 300+ sentence phrases. And I have another attribute file that has 50 attribute words. 
I want to check the similarity of those 50 attributes with all the input sentences. 

Using two for loops will obviously take lots of time for each attribute to go through all sentence phrases. Anyways to find semantic similarity in a shorter duration?

Any help ??

## Your Environment

* Operating System: windows 10
* Python Version Used: 3.2
* spaCy Version Used: 2.0.11
* Environment Information:

**Comment by honnibal** [comment]
Hi,

There are a few ways you could achieve this. One simple approach is to make a `doc` object with your target words, like this:

```python
import spacy
from spacy.tokens import Doc
good_words = ['good', 'better', 'best']
nlp = spacy.load('en_vectors_web_lg')
doc = Doc(nlp.vocab, words=good_words)
```

You can then use `doc.similarity()` to check the similarity of your target words against some text, which might be a sentence or a doc. Under the hood, this will average the word vectors, and compute a cosine similarity. So you'll need to use a model with word vectors.

You could also train a text classification system. We have an annotation tool that makes this particularly easy: https;//prodi.gy
