### ISSUE TITLE
LILLA and SILLA algorithms

### ISSUE THREAD

**Issue by knyghty** [explosion/spaCy#270]
I'm back with another alignment-related feature request.

I'm looking to implement LILLA and SILLA as described in papers:
https://pdfs.semanticscholar.org/c883/8797233934980176e4a3d9269b711fe99b36.pdf
http://pss.sagepub.com/content/23/8/931.full.pdf
https://pdfs.semanticscholar.org/eff2/1c747cd965aa3430598dc536196e4048e8c0.pdf

I guess at least the latter may be dependent on #59

**Comment by honnibal** [comment]
These look like good suggestions --- they should be easy to implement. A dependency-based version of their SILLA measure looks like it should work, so I don't think constituency parsing will be necessary.

**Comment by knyghty** [comment]
Another day, another new paper: http://www.thoughtfill.com/docs/doyle_yurovsky_frank_www16.pdf

Looks like it could replace those two - I don't see why we couldn't use dependency trees and run it on that for a syntactic measure also.

I have some small doubts though, like they only used it on Twitter data, makes me wonder if they tried it on longform text and maybe didn't get the results they wanted...
