### ISSUE TITLE
Inconsistent lemmatization of unicode apostrophe

### ISSUE THREAD

**Issue by beowulfenator** [explosion/spaCy#2702]
There are some cases where unicode apostrophe (`\u2019`) is tokenized correctly, and some where it is not.

## How to reproduce the behaviour
```
import spacy

texts = [
    "That\u2019s all, folks!",
    "That's all, folks!",
    "I\u2019m here!",
    "I'm here!",
    "We\u2019re here.",
    "We're here.",
]

nlp = spacy.load('en_core_web_sm')

for text in texts:
    doc = nlp(text)
    print(text)
    for token in doc:
        print({
            "Token": token.orth_,
            "POS": token.pos_,
            "Lemma": token.lemma_,
        })
    print()
```

Result (only the incorrect part):
```
That’s all, folks!
{'POS': 'DET', 'Token': 'That', 'Lemma': 'that'}
{'POS': 'VERB', 'Token': '’s', 'Lemma': '’'}
{'POS': 'DET', 'Token': 'all', 'Lemma': 'all'}
{'POS': 'PUNCT', 'Token': ',', 'Lemma': ','}
{'POS': 'NOUN', 'Token': 'folks', 'Lemma': 'folk'}
{'POS': 'PUNCT', 'Token': '!', 'Lemma': '!'}
```

So all strings are fine except the `That\u2019s`. Is there a way to add an exception to properly tokenize that apostrophe? I realize it could mean either "to be" or "to have", but in my case assigning all instances of `\u2019s` to "to be" is much better than what happens now.

## Info about spaCy

* **spaCy version:** 2.0.12
* **Platform:** Linux-4.4.0-31-generic-x86_64-with-Ubuntu-16.04-xenial
* **Python version:** 3.5.2
* **Models:** en_core_web_lg

**Comment by ines** [comment]
Thanks for the report. Just to confirm, the splitting is all correct and you're mostly referring to the lemmatization here, right?

```
{'POS': 'VERB', 'Token': '’s', 'Lemma': '’'}
```

In unambiguous cases, the lemma is assigned [in the tokenizer exceptions](https://github.com/explosion/spaCy/blob/master/spacy/lang/en/tokenizer_exceptions.py). In all other cases, it should be left blank and then assigned later during rule-based lemmatization, depending on the POS tag. So this case is definitely strange 🤔

> Is there a way to add an exception to properly tokenize that apostrophe?

While you could dig into the exceptions and lemmatizer, the quickest workaround would probably be to add a custom component that applies overrides depending on the lemma and token text. The `Token.lemma_` attribute is writable, so you could do something as basic as this:

```python
def override_lemmas(doc):
    for token in doc:
        if token.text == '\u2019s':
            token.lemma_ = 'be'
    return doc

# add component to the pipeline
nlp.add_pipe(override_lemmas)
```

Of course, you're free to solve this more elegantly – for example, by creating a dict with the overrides and using that. This is btw also a good approach if you ever need to handle non-standard cases in your data that require different, domain-specific rules.

**Comment by beowulfenator** [comment]
Yes, the splitting is correct, but lemmatization is broken. Thank you for the workaround, it works great. Perhaps there is a way to make a change to rule-based lemmatization? Where are these rules defined anyway?

**Comment by honnibal** [comment]
Merging with #3052 (inaccurate prediction master thread)
