### ISSUE TITLE
Passing pipeline [xyz, ...] to Language initializer seems to get overwritten

### ISSUE THREAD

**Issue by hannahlindsley** [explosion/spaCy#2703]
## How to reproduce the behaviour
```
from spacy.language import Language

l = Language(vocab=True, pipeline=['anything'])
l.pipeline
```
yields
```
[]
```
where I would have expected 
```
['anything']
```

I found this while extending the Language class.

## Your Environment

* **spaCy version:** 2.0.11
* **Platform:** Darwin-17.3.0-x86_64-i386-64bit
* **Python version:** 3.6.5

**Comment by ines** [comment]
In v2.x, the pipeline should be instantiated explicitly, e.g. by calling `nlp.add_pipe`. This is also how it's done internally when you call `spacy.load`. The docstrings still included the `pipeline` and `disable` arguments, even though they don't actually exist anymore, so I fixed that. Maybe spaCy should even raise an error to make it clear that setting `pipeline` on `Language` isn't accepted anymore.
