### ISSUE TITLE
Which dependency labels are used in English model?

### ISSUE THREAD

**Issue by GitDimma** [explosion/spaCy#2705]
It was already asked before in #1682 .  Which dependency labels are used in English model? 
I see that in documentation **Universal Dependancy Labels** are mixed with **English Dependancy Labels** . 
It was said:
" The English models are trained on the the OntoNotes 5 corpus and all use the CLEAR style for dependency labels. You can see the full list of labels here:  https://spacy.io/api/annotation#dependency-parsing-english (You should be able to click on "English" and expand the section to show the full table)."

But in English model Annotation Specifications , for example,  **tags "nummod" , "compound", "acl" are absent** but you can find them  among **Universal Dependancy Labels** . While **tags "poss" and "case"**  are missing in **Universal Dependancy set** and the **tag "relcl"** is missing in both sets. Is it some kind of mixed version of both used by spaCy English model  or it is just incomplete documentation?

**Comment by ines** [comment]
Thanks for the report! I'm pretty sure we've adapted the overview from an existing list, so it's definitely possible that the English label list is missing a few entries.

I'll have a look at this and see what needs to be added! If you want to make a suggestion, feel free to check out the source of the docs page in [`website/api/_annotation/_dep-labels.jade`](https://github.com/explosion/spaCy/blob/master/website/api/_annotation/_dep-labels.jade) and submit a PR if you like.
