### ISSUE TITLE
spacy.explain() does not explain "FAC"

### ISSUE THREAD

**Issue by djancak** [explosion/spaCy#2706]
>>> spacy.explain("NORP")
			   
'Nationalities or religious or political groups'
>>> spacy.explain("DATE")
			   
'Absolute or relative dates or periods'
>>> spacy.explain("FAC")
			   
>>> plz explain FAC kthx???

screenshot:
![image](https://user-images.githubusercontent.com/42696151/44618496-8359ba80-a83c-11e8-9e6a-b402ce80d3aa.png)

>>> print(spacy.info())

    [93mInfo about spaCy[0m

    spaCy version      2.0.12         
    Location           C:\Python36\lib\site-packages\spacy
    Platform           Windows-10-10.0.17134-SP0
    Python version     3.6.4          
    Models                            

{'spaCy version': '2.0.12', 'Location': 'C:\\Python36\\lib\\site-packages\\spacy', 'Platform': 'Windows-10-10.0.17134-SP0', 'Python version': '3.6.4', 'Models': ''}

>>> extraneous information:
Love this module. Used it the other day to extract names and places from a book I wanted to speed-read in order to familiarize myself so I didn't end up confused as I went through the text at 700 wpm. Worked like a charm. Now I need a module to extract those pesky words that I've never seen before, like "wharves," "sestertii," and "praetorium".

**Comment by ines** [comment]
Thanks a lot! Fixing!

(Btw, we haven't updated the `spacy.explain` glossary in a while, so it's possible that other terms are missing. If you come across anything else, let us know!)
