### ISSUE TITLE
Example in "Annotation specifications" docs throws TypeError

### ISSUE THREAD

**Issue by jimmycallin** [explosion/spaCy#271]
This example from [Annotations Specifications](https://spacy.io/docs#spec) under Tokenization throws TypeError:

    from spacy.en import English
    nlp = English(parse=False)
    tokens = nlp('Some\nspaces  and\ttab characters')
    print([t.orth_ for t in tokens])

    TypeError: __init__() got an unexpected keyword argument 'parse'

I'm assuming it should be parser=False?

**Comment by honnibal** [comment]
Thanks, will fix.
