### ISSUE TITLE
Spanish lemmatization

### ISSUE THREAD

**Issue by chozelinek** [explosion/spaCy#2710]
I've been analysing a large amount of texts in Spanish and I've realised of several behaviours which are a bit weird regarding lemmatisation (in comparison with English at least).

Maybe, some issues could be avoided if the lemmatisation used the POS information to distinguish between word classes. If one loads a blank model, one gets lemmas.

See the examples below to reproduce the behaviour and my comments.

## How to reproduce the behaviour

```python
import spacy
nlp = spacy.load('es_core_news_md')  # same behaviour with spacy.blank('es')
```

```python
text1 = "Con estos fines, la Dirección de Gestión y Control Financiero monitorea la posición de capital del Banco y utiliza los mecanismos para hacer un eficiente manejo del capital."
for token in nlp(text1):
    print(token.text, token.lemma_, token.pos_)
```

Word | Lemma | POS | Comments
---|---|---|---
Con | Con | ADP
estos | este | DET
fines | finar | NOUN | instead of "fin" it uses the infinitive of a verb meaning to die
, | , | PUNCT
la | lo | DET
Dirección | Dirección | PROPN
de | de | ADP
Gestión | Gestión | PROPN
y | y | CONJ
Control | Control | PROPN
Financiero | Financiero | PROPN
monitorea | monitorea | VERB | not lemmatized, expected "monitorear"
la | lo | DET
posición | posición | NOUN
de | de | ADP
capital | capital | NOUN
del | del | ADP
Banco | Banco | PROPN
y | y | CONJ
utiliza | utilizar | VERB
los | lo | DET
mecanismos | mecanismo | NOUN
para | parir | ADP | "para" is a very frequent preposition in Spanish, here is lemmatized as the infinitive form of the verb to give birth, the parser got it right, the lemmatizer didn't
hacer | hacer | VERB
un | uno | DET
eficiente | eficiente | ADJ
manejo | manejar | NOUN | Manejo is an ambiguous word, because it could be the first person singular of present or a noun. In this case is the noun, as the POS information tells us, so the expected lemma would be manejo, and not the infinitive, the parser got it right, the lemmatizer didn't
del | del | ADP
capital | capital | NOUN
. | . | PUNCT

```python
text2 = "Incentivar la cultura de retroalimentación continua , nos dirige hacia el desarrollo de los talentos de los empleados, así como también, a la conformación de equipos de alto desempeño."
for token in nlp(text2):
    print(token.text, token.lemma_, token.pos_)
```

Word | Lemma | POS | Comments
---|---|---|---
Incentivar | Incentivar | VERB
la | lo | DET
cultura | cultura | NOUN
de | de | ADP
retroalimentación | retroalimentación | NOUN
continua | continuo | ADJ
, | , | PUNCT
nos | no | PRON
dirige | dirigir | VERB
hacia | hacia | ADP
el | el | DET | why if for "la", "los", "las" the lemma is "lo" do we get "el" for "el", for me this is an inconsistency in the lemmatization of determined article
desarrollo | desarrollar | NOUN | parser got it right, lemmatizer didn't
de | de | ADP
los | lo | DET
talentos | talento | NOUN
de | de | ADP
los | lo | DET
empleados | emplear | NOUN | parser got it right, lemmatizer didn't
, | , | PUNCT
así | asir | ADV | parser got it right, lemmatizer didn't
como | comer | SCONJ | parser got it right, lemmatizer didn't
también | también | ADV
, | , | PUNCT
a | a | ADP
la | lo | DET
conformación | conformación | NOUN
de | de | ADP
equipos | equipo | NOUN
de | de | ADP
alto | alto | ADJ
desempeño | desempeñar | NOUN | parser got it right, lemmatizer didn't
. | . | PUNCT

```python
text3 = "Por ello nuestra Política de Responsabilidad Corporativa fomenta, entre empleados y colaboradores, el comportamiento socialmente responsable, el compromiso con la creación de valor a largo plazo y la gestión sostenible."
for token in nlp(text3):
    print(token.text, token.lemma_, token.pos_)
```

Word | Lemma | POS | Comments
---|---|---|---
Por | Por | ADP
ello | él | PRON
nuestra | nuestro | DET
Política | Política | PROPN
de | de | ADP
Responsabilidad | Responsabilidad | PROPN
Corporativa | Corporativa | PROPN
fomenta | fomentar | VERB
, | , | PUNCT
entre | entrar | ADP | preposition not verb, parser got it right, lemmatizer didn't
empleados | emplear | NOUN | parser 1, lemmatizer 0
y | y | CONJ
colaboradores | colaborador | NOUN
, | , | PUNCT
el | el | DET
comportamiento | comportamiento | NOUN
socialmente | socialmente | ADV
responsable | responsable | ADJ
, | , | PUNCT
el | el | DET
compromiso | compromiso | NOUN
con | con | ADP
la | lo | DET
creación | creación | NOUN
de | de | ADP
valor | valor | NOUN
a | a | ADP
largo | largar | ADJ | parser got ir right, lemmatizer didn't
plazo | plazo | NOUN
y | y | CONJ
la | lo | DET
gestión | gestión | NOUN
sostenible | sostenible | ADJ
. | . | PUNCT

## Your Environment

* **spaCy version:** 2.0.11
* **Platform:** Darwin-17.7.0-x86_64-i386-64bit
* **Python version:** 3.6.3
* **Models:** en_core_web_md, fr_core_news_md, es_core_news_md, en_core_web_lg, de_core_news_sm, pt_core_news_sm, fr_core_news_sm

**Comment by ines** [comment]
Thanks for the detailed analysis, this will be very helpful for developing the rule-based lemmatizers. Using a rule-based approach instead of only a lookup table will likely make a big difference here. I'll merge this issue with #2668, which is the master enhancement issue for rule-based lemmatization.
