### ISSUE TITLE
Numpy DeprecationWarning 

### ISSUE THREAD

**Issue by bbrinx** [explosion/spaCy#2712]
## How to reproduce the behaviour
```python 
spacy.load('de_core_news_md')
#or 
import de_core_news_md
de_core_news_md.load()
```

While both load the model, it logs following in a loop:
```
/path/env/lib/python3.6/site-packages/msgpack_numpy.py:84: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  dtype=np.dtype(descr)).reshape(obj[b'shape'])
``` 

## My Environment
* **spaCy version:** 2.1.0a1
* **Platform:** Darwin-17.7.0-x86_64-i386-64bit
* **Python version:** 3.6.5
* **Models:** de_core_news_md

**Comment by r-wheeler** [comment]
Currently experiencing this issue as well.
