### ISSUE TITLE
Spacy V2 / nlp pipeline Extremely Slow

### ISSUE THREAD

**Issue by lazypocket** [explosion/spaCy#2713]
I want to ask for help as I have been following the discussion https://github.com/explosion/spaCy/issues/1508, but I didn't fully understand the solution and didn't want to pollute the discussion thread.
It seems that the benchmark speed should be roughly between 8,000 and 10,000 words per second when I use ```nlp``` or ```nlp.pipe```. However, when I called ```nlp```, I was able to get 10,000 tokens in ~2.9 seconds. Further, ```nlp.pipe``` did not help speed up (the performance was almost the same whether I used pipe or not)

## How to reproduce the problem

When I tried running "python -m blis.benchmark", my result was:
```bash
Blis...
11032016.6015625
149.47 seconds
Numpy...
11032010.7421875
3.47 seconds
```

## Your Environment

* Operating System: Darwin-17.4.0-x86_64-i386-64bit (OSX)
* Python Version Used: 3.6.4
* spaCy Version Used: 2.0.9
* Environment Information: en_core_web_sm, en

**Comment by honnibal** [comment]
Try updating to v2.1.0a1, and redownloading the model, to check that your performance is still the same. You might also need to limit the number of cores being used in your machine.
