### ISSUE TITLE
NN Models in each steps for NER training & prediction ?

### ISSUE THREAD

**Issue by HerveTrinh** [explosion/spaCy#2717]
Hi,

I'm a student in applied maths and want to be a data scientist in the future (I have some basics knowledge).
So I'm new in deep learning (I have a few knowledge for ANN (the use of forward / backward propagation and I can search for keywords if there's technical term).

firstly, I want to thank you to give us such an amazing tool for NER.
I achieved a 98,4% of accuracy in my use case, spaCy is intuitive and easy.

I trained with this format : 
`    TRAIN_DATA = [
    ('Who is Shaka Khan?', {
        'entities': [(7, 17, 'PERSON')]
    }),
    ('I like London and Berlin.', {
        'entities': [(7, 13, 'LOC'), (18, 24, 'LOC')]
    })
] `

But I will look for BILOU form and CLI command but before re-train my data, I want to understand the theory behind the training and the prediction of NER for this amazing tool.

after reading : 
https://explosion.ai/blog/deep-learning-formula-nlp
and looking : 
https://www.youtube.com/watch?v=sqDHBH9IjRU 

I understood that there were 4 steps (Embed, Encode, Attend and Predict) but I don't understand what's the models behind theses steps.

To sum up quickly what I understand : 
- The Embedding step is simply a "Word2vec" operation to convert a word (token) to a vector (out of the context)
(input : word ID (with the hashing trick?) / output : vector of each token) 

- The Encoding step, I don't understand how the bi-directionnal RNNs can convert the sequence of vectors into a sentence matrix, can you explain me in details or with a schema the ANN please ?
(what's the input / output ?)

- The Attend step, how to find the context vector ? and what's the ANN behind ? Can you explain me in details the steps behind this step please ?
(what's the input / output ?)

- And the Predict Step, what's the ANN behind too ? 
(what's the input / output for NER ? is it the label like PERSON, ORG, MISC etc ?)

Don't hesitate to give me some papers, I'm here to learn !
(I find this slide for NER detection: http://www.cis.uni-muenchen.de/~braune/NNlecture/NERslides.pdf )

Thanks for your help,
Hervé.

**Comment by honnibal** [comment]
Unfortunately further documentation is only within the library, and we don't currently have a paper detailing the NER model. The places in the code to consult for the particulars are:

* `spacy/_ml.py :: Tok2Vec`: This defines the embed and encode steps.
* `spacy/syntax/_parser_model.pyx` This defines the parsing models. There are actually two implemented here: a locally normalized one for greedy decoding, and a globally normalized one for beam-search decoding. There are implementation tricks to make the parser more efficient, specifically we pre-compute the feature values for the first hidden layer, similar to the work of Chen and Manning (2014).
* The parser and NER are trained with an imitation learning objective. You can read more about this algorithm here, in the context of the parser: https://explosion.ai/blog/parsing-english-in-python
