### ISSUE TITLE
‘nocturia’ tagged as INTJ

### ISSUE THREAD

**Issue by adam-ra** [explosion/spaCy#2718]
Model: en_core_web_sm 2.0.0
To reproduce: https://explosion.ai/demos/displacy?text=nocturia&model=en_core_web_sm&cpu=1&cph=1

It would be good to disallow out-of-vocabulary items to be tagged as closed classes. (mentioned in #753)

**Comment by adam-ra** [comment]
BTW, ‘hematuria’ is tagged as RB (ADV)

**Comment by honnibal** [comment]
It's a fair request, and there's an open enhancement issue about this: https://github.com/explosion/spaCy/issues/331

I'd take a pull request for the tagger if you want to prepare one?
