### ISSUE TITLE
Prefix rules affecting suffix rules

### ISSUE THREAD

**Issue by qiuwei** [explosion/spaCy#2719]
## How to reproduce the behaviour
I am trying to customize the tokenizer.
```
    prefixes = nlp.Defaults.prefixes + (r"[-/]", r"[a-zA-Z]+(?=[0-9])", r"[0-9]+(?=[a-zA-Z])")
    prefix_re = spacy.util.compile_prefix_regex(prefixes)
    tokenizer.prefix_search = prefix_re.search
    print(prefixes)

    suffixes = tuple(i for i in nlp.Defaults.suffixes if i != r"\'\'")  + (r"\.", )
    suffix_re = spacy.util.compile_suffix_regex(suffixes) 
    tokenizer.suffix_search = suffix_re.search
    print(suffixes)
```

Using this customization, I expect string ` 1g.` would be split into `1` `g` `.`

However, it is split in to `1` `g.`

Removing the prefix  `r"[0-9]+(?=[a-zA-Z])"` would split `g.` 

## Your Environment
*  **spaCy version:** 2.0.12
* **Platform:** Darwin-17.7.0-x86_64-i386-64bit
* **Python version:** 3.6.5
* **Models:** en_core_web_sm

**Comment by honnibal** [comment]
When the prefix rules and suffix rules have a conflict, the suffix rules end up taking precedence. The choice is sort of arbitrary, but I don't see how having prefix rules taking precedence would be better.
