### ISSUE TITLE
Unexpected behavior of the Tokenizer

### ISSUE THREAD

**Issue by qiuwei** [explosion/spaCy#2720]
## How to reproduce the behaviour
```
nlp = spacy.load('en_core_web_sm', disable=['tagger', 'parser', 'ner'])
nlp = English()

prefixes = (r"[0-9.]+(?=[a-zA-Z])", )
prefix_re = spacy.util.compile_prefix_regex(prefixes)
nlp.tokenizer.prefix_search = prefix_re.search
print(prefix_re.search("123.take"))
print([t for t in nlp("123.take")])
```
I expect the prefix_re.search can find `123.` as a prefix ,then the tokenizer would split `123.` from `take`.
The output of `print(prefix_re.search("123.take"))` confirms that it indeed finds `123.` as a prefix,
however, the last line still  outputs [123.take], which means '123.' was not split.

## Your Environment
* **spaCy version:** 2.0.12
* **Platform:** Darwin-17.7.0-x86_64-i386-64bit
* **Python version:** 3.6.5
* **Models:** en_core_web_sm

**Comment by honnibal** [comment]
Unfortunately another rule is interfering for you: set `nlp.tokenizer.token_match = None`

The `token_match` rule is mostly applied for URLs, which your example happens to look like. So spaCy is seeing the chunk, deciding it looks like a URL, and treating it that way.
