### ISSUE TITLE
How can i pass multi regex in spacy

### ISSUE THREAD

**Issue by karthikhadoop** [explosion/spaCy#2721]
## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by karthikhadoop** [comment]
i try to pass multi regex in spacy on text file lik below but it throws an error lik ebelow:
NUM_PATTERN = re.compile(r"(\w*-\d*-\d*\w*)" "(\d*-\w*-\d*)")

**Comment by honnibal** [comment]
Could you explain what you're trying to do in more detail?
