### ISSUE TITLE
Token Similarity Not Working as in Example

### ISSUE THREAD

**Issue by jjasonbell** [explosion/spaCy#2722]
import spacy 
    nlp = spacy.load('en_core_web_md')
    tokens = nlp(u'dog cat banana')

    for token1 in tokens:
        for token2 in tokens:
            print(token1.text, token2.text, token1.similarity(token2))
Returns:

    dog dog 1.0
    dog cat 0.0
    dog banana 0.0
    cat dog 0.0
    cat cat 1.0
    cat banana -0.044681177
    banana dog -7.828739e+17
    banana cat -8.242222e+17
    banana banana 1.0

* **spaCy version:** 2.0.12
* **Platform:** Darwin-17.7.0-x86_64-i386-64bit
* **Python version:** 3.6.5
* **Models:** en_core_web_md, en_core_web_lg, en, __cache__

**Comment by param-eter** [comment]
I'm having the same problem

**Comment by ines** [comment]
Could you check which version of numpy you're using and upgrade it if possible? If I remember correctly, there was a numpy bug / incompatibility that caused those negative similarity scores.

**Comment by jjasonbell** [comment]
That did it.  I upgraded from numpy 1.14.3 to 1.15.1 and it works.
