### ISSUE TITLE
Use en_vectors_web_lg with en_core_web_lg

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [explosion/spaCy#2724]
Hello.

I have downloaded both `en_core_web_lg` and `en_vectors_web_lg`. I want to use `ner`, `tagger` and `parser` of `en_core_web_lg` but I want to use `en_vectors_web_lg` for similarity.

How to assign `en_vectors_web_lg` vectors to loaded `en_core_web_lg` nlp variable?

I'm using SpaCy 2.0.12

**Comment by SuperMasterBlasterLaser** [comment]
I have been trying to load it like this:

    nlp = spacy.load('en_core_web_lg', vectors='en_vectors_web_lg')
    print(nlp.vocab.vectors.shape)

But it outputs:
    (684831, 300)

Which means it still uses `en_core_web_lg` vectors.

**Comment by honnibal** [comment]
Try:

```
nlp = spacy.load('en_core_web_lg')
spacy.load('en_vectors_web_lg', vocab=nlp.vocab)
```

I think this will be fine for these two models, but note that if you have vectors trained from a different source, if you used the above technique you'd probably mess up the tagger, NER and parser models. Those models are trained to expect the vectors the model comes with, so if you gave them completely different vectors, they'd suffer in performance. But the two vector packages in this example are from the same source (the GloVe vectors trained from the large common crawl dump, distributed by Stanford), so it should be fine.

**Comment by SuperMasterBlasterLaser** [comment]
@honnibal Thank you for answer
