### ISSUE TITLE
Multiple newline tokenization

### ISSUE THREAD

**Issue by frx08** [explosion/spaCy#2727]
Dear community, 
I'm using the tokenizer but recognition of multiple newlines is not behaving as expected, one newline will be marked as space, multiple newlines are not marked as space.
There is a way to force the tokenizer to create multiple tokens for multiple newlines and not only one containing multiple newlines?

```
import spacy
nlp = spacy.load('en')

doc = nlp(u'Line 1\nLine 2')
print([(w.text, w.pos_) for w in doc])
# out: [('Line', ''), ('1', ''), ('\n', 'SPACE'), ('Line', ''), ('2', '')]
doc = nlp(u'Line 1\n\nLine 2')
print([(w.text, w.pos_) for w in doc])
# out: [('Line', ''), ('1', ''), ('\n\n', ''), ('Line', ''), ('2', '')]
```

## Info about spaCy

* **spaCy version:** 1.10.1
* **Platform:** Windows-10-10.0.17134-SP0
* **Python version:** 3.6.3
* **Installed models:** en_depent_web_md

**Comment by giannisdaras** [comment]
Hello @frx08!
I managed to reproduce it by downgrading to spaCy 1.10.1.
However, this issue seems to have been resolved in spaCy v2.
Could you try to upgrade to the newest spaCy version and confirm that the output is as expected?

**Comment by ines** [comment]
Merging this with the master issue in #1642!
