### ISSUE TITLE
What is the proper way to train a model on a GPU?

### ISSUE THREAD

**Issue by cmckain** [explosion/spaCy#2729]
Given the problems noted at [spacy#1798](https://github.com/explosion/spaCy/issues/1798#issuecomment-416026767), how would one convert the examples listed in the documentation ("Simple training style" for instance) to run on a GPU? And yes, 'thinc.neural.gpu_ops' and 'cupy' are both working (in the sense that they don't fail immediately) with a confirmed increase in GPU usage and GPU memory used before the various mentioned errors.

* Operating System: Ubuntu 18.04
* Python Version Used: 3.6.5
* spaCy Version Used: 2.0.12
* Environment Information: 
thinc 6.10.3
cuda 9.2
cupy 4.4.0

**Comment by honnibal** [comment]
In v2.1 (or recent nightlies), the best approach is:

```python
import spacy
spacy.require_gpu()
```

If you want the same code to work on both cpu and gpu, depending on the hardware available, the `spacy.prefer_gpu()` function should be used.
