### ISSUE TITLE
Incorrect lemmatization for many English words

### ISSUE THREAD

**Issue by dzheng256** [explosion/spaCy#2736]
Similar to what's mentioned in #2257, many lemmas for basic English words are incorrect. #2257  was said to have been fixed, so not sure why this is still an issue?

For example: 
## How to reproduce the behaviour
```
import spacy
nlp = spacy.load('en')
doc = nlp('I hated that he was always coding')
for tok in doc:
    print(tok, tok.lemma_)
```

Output:
```
I -PRON-
hated hat
that that
he -PRON-
was be
always always
coding cod
```
Clearly "hated" should be lemmatized to "hate" and "coding" to "cod".  There are similar issues with other tokens, like "hoping" -> "hop", "rated" -> "rat", etc.

## Your Environment

* Operating System: Xubuntu 18.04
* Python Version Used: 3.6.5
* spaCy Version Used: 2.0.12
* Models: en

**Comment by ines** [comment]
As mentioned in the issue, the fix has been included on `develop` for the next minor version, so `v2.1.x`, which is currently available as `spacy-nightly`.

I just tested it and the underlying issue of #2257 seems to have been resolved in that version using the new models. However, it still seems to get "coding" wrong, so maybe this is actually related to something else or a missing exception.

**Comment by searchivarius** [comment]
Hi @ines , thank you for the quick fix! This didn't seem to help though. I use Python 3.6.5 Anaconda on Mac. I installed the nightly build and re-downloaded the models:
```
pip install -U spacy-nightly
python -m spacy download en
```
It does look like the version bumps up to 2.1.0a1? **This is the right one?**
Then, I run a simple code:
```
#!/usr/bin/env python3
import spacy
from spacy.lemmatizer import Lemmatizer
from spacy.lang.en import LEMMA_INDEX, LEMMA_EXC, LEMMA_RULES
lemmatizer = Lemmatizer(LEMMA_INDEX, LEMMA_EXC, LEMMA_RULES)

def custom_pipeline(nlp):
  return (nlp.tagger)
nlp = spacy.load('en', create_pipeline=custom_pipeline)

text='I like Spacy very much! It is a great software package! I hated that he was always coding.'

print('Spacy version: ' + spacy.__version__)

for doc in nlp.pipe([text]):
  for t in doc:
    print(t, '=> pipeline lemma:', t.lemma_, 'POS tag', t.tag_, 'lemma from the lemmatizer:', lemmatizer(str(t), t.tag_))
```
Which prints (I remove some parts) the wrong lemmas for both the pronoun I and the word coding. Well, as a slow workaround one may be able to re-lemmatize using the Lemmatizer class. Do I miss something?
```
Spacy version: 2.1.0a1
I => pipeline lemma: -PRON- POS tag PRP lemma from the lemmatizer: ['i']
like => pipeline lemma: like POS tag VBP lemma from the lemmatizer: ['like']
Spacy => pipeline lemma: Spacy POS tag NNP lemma from the lemmatizer: ['spacy']
very => pipeline lemma: very POS tag RB lemma from the lemmatizer: ['very']
much => pipeline lemma: much POS tag RB lemma from the lemmatizer: ['much']
! => pipeline lemma: ! POS tag . lemma from the lemmatizer: ['!']
...
I => pipeline lemma: -PRON- POS tag PRP lemma from the lemmatizer: ['i']
hated => pipeline lemma: hate POS tag VBD lemma from the lemmatizer: ['hated']
that => pipeline lemma: that POS tag IN lemma from the lemmatizer: ['that']
he => pipeline lemma: -PRON- POS tag PRP lemma from the lemmatizer: ['he']
was => pipeline lemma: be POS tag VBD lemma from the lemmatizer: ['was']
always => pipeline lemma: always POS tag RB lemma from the lemmatizer: ['always']
coding => pipeline lemma: cod POS tag VBG lemma from the lemmatizer: ['coding']
. => pipeline lemma: . POS tag . lemma from the lemmatizer: ['.']
```
Thank you!

**Comment by searchivarius** [comment]
PS: after submitting this, I noticed that the standalone lemmatizer actually doesn't always work correctly. For example, the first produced hypothesis for ``code`` is correct, but for ``hated`` it is wrong. Do you guys use dictionary-less lemmatization? If so, Hunspell has some reasonable dictionaries. The license seems to be rather permissive: GPL/LGPL/MPL, so it is probably possible to re-use these dictionaries in Spacy.
