### ISSUE TITLE
Ability to pass additional arguments to pipeline components

### ISSUE THREAD

**Issue by thomasopsomer** [explosion/spaCy#2740]
## Feature description

I'm intensively using custom components :) And Sometimes I would like to pass them additional, non text/doc arguments for instance the date of a document, tags, options...

One way to allow that could be to do like scikit learn does with their `Pipeline`: one can provide a dict of parameters (or a list of tuple), with keys being the arguments prefixed with the name of the of the component, something like `pipeline_params = {<component_name>__<arg_name>: "value"}` and each component of the pipeline extract its arguments from it.

**Comment by honnibal** [comment]
Finally got to this :tada: . I think it'll be a nice change. We went with the name `component_cfg`.
