### ISSUE TITLE
Sentence Segmentation

### ISSUE THREAD

**Issue by sakatipomu** [explosion/spaCy#2741]
I am new to Spacy and NLP. Facing the below issue while doing sentence segmentation using Spacy.

The text I am trying to tokenise into sentences contains numbered lists(with space between numbering and actual text) . Like below.

```
import spacy
nlp = spacy.load('en_core_web_sm')
text = "This is first sentence.\nNext is numbered list.\n1. Hello World!\n2. Hello World2!\n3. Hello World!"
text_sentences = nlp(text)
for sentence in text_sentences.sents:
    print(sentence.text)
```
Output(1.,2.,3. are considered as separate lines) is:

```
This is first sentence.

Next is numbered list.

1.
Hello World!

2.
Hello World2!

3.
Hello World!
```
But if there is no space between numbering and actual text, then sentence tokenisation is fine. Like below

```
import spacy
nlp = spacy.load('en_core_web_sm')
text = "This is first sentence.\nNext is numbered list.\n1.Hello World!\n2.Hello World2!\n3.Hello World!"
text_sentences = nlp(text)
for sentence in text_sentences.sents:
    print(sentence.text)
```
Output(desired) is:

```
This is first sentence.

Next is numbered list.

1.Hello World!

2.Hello World2!

3.Hello World!
```
please suggest whether we can customise sentence detector to this.

* Operating System: MacOSX
* Python Version Used: 3.6
* spaCy Version Used: 2.0.12

**Comment by honnibal** [comment]
You can either normalize your text, or write to the `token.is_sent_start` attribute. You can find an example of that here: https://github.com/explosion/spaCy/blob/master/examples/pipeline/custom_sentence_segmentation.py
