### ISSUE TITLE
tagging and parsing a predefined tokens

### ISSUE THREAD

**Issue by moh55m55** [explosion/spaCy#2742]
How to parse and tag predefined tokens? 
for example : 
`from spacy.tokens import Doc`
`doc = Doc(nlp.vocab, words=[u'hello', u'world', u'!'],spaces=[True, False, False])`
`doc.is_tagged`
`False`
how to tag the document object? its not clear in the docs. 

Thanks

**Comment by honnibal** [comment]
You can assign tags by writing to the `token.tag_` attribute, or by using the `doc.from_array()` method, which takes a numpy array with the attributes. For parsing, the whole tree has to be set at once, so only the `doc.from_array()` method can be used --- there's no way to set the heads one-by-one.
