### ISSUE TITLE
spaCy loops indefinetly during parsing of a typo ridden sentence

### ISSUE THREAD

**Issue by frenando** [explosion/spaCy#2744]
While trying to parse a large file with multiple tweets I found one which is completely typo ridden (using punctuation instead of spaces, mispellings, etc.), this specific text chain causes spaCy tokenizer to loop indefinetly.

## How to reproduce the behaviour
import spacy
nlp = spacy.load("es_core_news_sm")
doc = nlp(u'Me pongo alas vivas.por favor vendan alitas.de pavo.piernas.huacales.crudos.va.colitas.rostizadas.como.en.cd.juarez.chihuagua.va.gracias.')

## Your Environment

* Operating System: Windows 10-10.0.1734-SP0
* Python Version Used: 3.6.6
* spaCy Version Used: 2.0.11
* Environment Information: Models: "es"

**Comment by honnibal** [comment]
Thanks for the example! We need to make a test case for this, and then look into it.

**Comment by ines** [comment]
Just tested this with the new `spacy-nightly` and the new models and it works as expected now. This was likely related to an issue with the `TOKEN_MATCH`, which was resolved for the new version.
