### ISSUE TITLE
Lemmatizer doesn't work in special cases after the 'tag_' properties set function was called

### ISSUE THREAD

**Issue by kleinias** [explosion/spaCy#2749]
## How to reproduce the behaviour

import spacy
nlp = spacy.load('en_core_web_md')

doc = nlp("Chuck Norris is the most funny person.")

print ([x.lemma_ for x in doc])

doc[4].dep_ = doc[4].dep_
doc[4].tag_ = doc[4].tag_
doc[4].head = doc[4]

print ([x.lemma_ for x in doc])

"""
['chuck', 'norris', 'be', 'the', 'much', 'funny', 'person', '.']
['chuck', 'norris', 'be', 'the', 'most', 'funny', 'person', '.']
"""

## Your Environment

* Operating System: ubuntu 16
* Python Version Used: 3.6
* spaCy Version Used: 2
* Environment Information:

I think, the lemmatizer shoud reveal the same result after setting other/ resp. the same properties.

I don't know, why the behavior of that lemmatizer changes here by side effects. I found this happening just in case the 'tag_' is 'RBS' like in this sentence with 'most'.

**Comment by honnibal** [comment]
This is a fairly confusing case, thanks. I wonder whether the lemma for `most` is being set in the tokenizer exceptions? If so, that would explain why it's not being set when the tag is assigned. Not 100% sure what's going on here.

**Comment by honnibal** [comment]
This appears to be fixed in the latest `spacy-nightly`. Still not sure what went wrong though, which is disturbing! If the problem re-occurs, please reopen.
