### ISSUE TITLE
Incorrect Output when testing sentence with a homonym

### ISSUE THREAD

**Issue by poojamikk** [explosion/spaCy#2753]
## How to reproduce the behaviour

`import spacy
from spacy import displacy
from spacy.lang.en.stop_words import STOP_WORDS

nlp = spacy.load('en_core_web_sm')
doc = nlp(u'Tears well up in my eyes.')
for token in doc:
    print(token.text, token.pos_, token.dep_)
`
I was testing some of the parsing/tagging features of spaCy and decided to try out the sentence "Tears well up in my eyes." Instead of having 'well' marked as a verb, it got marked as an adverb in the output. I realized the output error could have occurred because 'well' as a word can be used in multiple contexts. However, I thought the surrounding words would have helped the model realize that 'well' here was used as an action verb. 
## Your Environment
* Operating System: Mac OS X
* Python Version Used: 3.6.3
* spaCy Version Used: 2.0.12
## Info about spaCy

* **spaCy version:** 2.0.12
* **Platform:** Darwin-15.6.0-x86_64-i386-64bit
* **Python version:** 3.6.3
* **Models:** en

**Comment by honnibal** [comment]
Because the models are statistical, some errors are to be expected. We generally try to stay within 1-2 years of the current state-of-the-art, in terms of a mix of speed and accuracy. We expect future models to continue to improve.
