### ISSUE TITLE
Add more arguments to textcat model, especially to disable ensembling and multi-class classification

### ISSUE THREAD

**Issue by honnibal** [explosion/spaCy#2756]
The textcat model is fairly specific, and was designed with the needs of Prodigy firmly in mind. To make it more general-case, we need to have some arguments to disable various features. Two important flags we need to support are:

1. Disable the ensemble with the bag-of-words model. This will mitigate the effect of https://github.com/explosion/spaCy/issues/1798

2. Support one-label-per-instance classification. Currently we assume all problems are multi-label, which makes the model less accurate on single-label problems.

**Comment by thomasopsomer** [comment]
And not to forget => use pretrained word vector by default :)
