### ISSUE TITLE
Pickle is slow

### ISSUE THREAD

**Issue by rominf** [explosion/spaCy#2757]
## How to reproduce the behaviour
In IPython:
```
import spacy
nlp = spacy.load('en')
%time _ = pickle.dumps(nlp)
# CPU times: user 3.19 s, sys: 168 ms, total: 3.36 s
# Wall time: 3.36 s
```

## Info about spaCy

* **spaCy version:** 2.0.12
* **Platform:** Linux-4.17.12-1-default-x86_64-with-glibc2.9
* **Python version:** 3.6.6
* **Models:** en

I think that pickling should last around a hundred milliseconds.

**Comment by honnibal** [comment]
Well...It simply isn't. The models can be quite large (up to a few hundred mb's). If you have a way to make serialization a few hundred milliseconds, we'd love to have a pull request.
