### ISSUE TITLE
Using Spacy with multiple GPUs

### ISSUE THREAD

**Issue by momoshiki-otsutsuki** [explosion/spaCy#2761]
We have been using spacy but it has been running successfully on a single gpu instance. What will be the way to run spacy using multiple GPU instances?

**Comment by honnibal** [comment]
During training, or inference? I'm afraid multi-GPU training is quite a long way off at the moment --- we're far from saturating even a modest card given the current implementation. For inference, you shouldn't need to do anything special: just start more processes, and tell them to use different GPU cards. You'll probably find CPU-based inference cheaper if you're using a cloud provider, though.

**Comment by momoshiki-otsutsuki** [comment]
During training. Only a single GPU is being used. How do we extend the training process to multiple GPUs?
