### ISSUE TITLE
undefined symbol: PyFPE_jbuf

### ISSUE THREAD

**Issue by ArmanAjdani** [explosion/spaCy#2764]
## How to reproduce the behaviour
Hi I try to use spacy but importing it gives me this error:

```
  File "/app/server_nlp_project/manager/spacy_manager.py", line 1, in <module>
    import spacy
  File "/app/spacy/spacy/__init__.py", line 4, in <module>
    from .cli.info import info as cli_info
  File "/app/spacy/spacy/cli/__init__.py", line 6, in <module>
    from .train import train
  File "/app/spacy/spacy/cli/train.py", line 12, in <module>
    from ..gold import GoldCorpus, minibatch
ImportError: /app/spacy/spacy/gold.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf

```

## Your Environment
* Operating System: 18.04 LTS (docker)
* Python Version Used: Python 3.6.5
* spaCy Version Used: 2.0.12.dev0
* Environment Information: pip3 freeze

absl-py==0.2.2
astor==0.6.2
atomicwrites==1.1.5
attrs==18.1.0
bleach==1.5.0
certifi==2018.4.16
chardet==3.0.4
click==6.7
cymem==1.31.2
Cython==0.27.3
cytoolz==0.8.2
dill==0.2.7.1
Flask==0.11.1
Flask-JWT==0.2.0
Flask-Script==2.0.5
gast==0.2.0
grpcio==1.12.1
gunicorn==19.8.1
h5py==2.8.0
html5lib==0.9999999
idna==2.7
itsdangerous==0.24
Jinja2==2.7.3
Keras==2.2.0
Keras-Applications==1.0.2
Keras-Preprocessing==1.0.1
Markdown==2.6.11
MarkupSafe==0.23
mock==2.0.0
more-itertools==4.2.0
msgpack-numpy==0.4.1
msgpack-python==0.5.6
murmurhash==0.28.0
numpy==1.14.5
pathlib==1.0.1
pbr==4.0.4
plac==0.9.6
pluggy==0.6.0
preshed==1.0.0
protobuf==3.6.0
py==1.5.3
PyJWT==0.4.1
Pympler==0.5
pytest==3.6.1
python-dateutil==2.4.2
pytz==2018.4
PyYAML==3.12
raven==6.9.0
redis==2.10.3
regex==2018.6.9
requests==2.19.0
requests-file==1.4.3
scikit-learn==0.19.1
scipy==1.1.0
six==1.11.0
tensorboard==1.8.0
tensorflow==1.8.0
termcolor==1.1.0
thinc==6.10.2
tldextract==2.2.0
toolz==0.9.0
tqdm==4.23.4
ujson==1.35
urllib3==1.23
validate-email==1.3
Werkzeug==0.14.1
wrapt==1.10.11

I have used this config very long time , but recently gives me this error. maybe any version changes or something , I'm not sure.

**Comment by ines** [comment]
We've just released `v2.0.13`, which comes with pre-build binary wheels for spaCy. We're also working on releasing wheels for all of our dependencies so users will be able to install spaCy without needing a compiler.

Could you try again installing the latest version via the wheels? If the issue still persists, feel free to reopen.
