### ISSUE TITLE
ner.add_label to existing model causes segmentation fault: 11

### ISSUE THREAD

**Issue by iperera** [explosion/spaCy#2769]
I was getting intermittent segmentation faults when training a new entity type, and so I thought I'd update spaCy to see if that helped. Unfortunately, now I get a segfault every single time, except not in training, but on adding entity types.

## How to reproduce the behaviour
Follow the spaCy/examples/training/train_new_entity_type.py example with the existing model 'en'. Segmentation fault occurs when adding a new entity label (ner.add_label(label)).

## Your Environment

* **spaCy version:** 2.1.0a1
* **Platform:** Darwin-17.7.0-x86_64-i386-64bit
* **Python version:** 3.7.0
* **Models:** en

I've attached the segfault log.

[segfault.txt](https://github.com/explosion/spaCy/files/2390338/segfault.txt)

**Comment by ines** [comment]
Thanks for the report. Are you able to share the examples you used and/or the labels you're adding? And do you have a reproducible example? Segfaults like this are always tricky to debug, so the more specific examples we have, the better.

**Comment by iperera** [comment]
The minimal reproducible example is the train_new_entity_type.py example script with the 'en' model loaded, with no other changes. That script adds the 'ANIMAL' entity tag. Note that this particular error is only with the nightly build.

The intermittent segmentation faults I referenced happend with other data but that issue has been mentioned in the past and is still open - #1969

**Comment by ines** [comment]
@nyejon Thanks for the example!

**Comment by honnibal** [comment]
Fixed :tada: 160b55c5729f
