### ISSUE TITLE
is_oov = True for all tokens in "en_core_web_sm"

### ISSUE THREAD

**Issue by mirandrom** [explosion/spaCy#2776]
Just wondering if this will be fixed?

```
>>> en = spacy.load('en_core_web_sm')
>>> x = en('This is a tessssst')
>>> [w.is_oov for w in x]
[True, True, True, True]
``` 

However, en_core_web_md 2.0.0 works just fine!

_Originally posted by @beowulfenator in https://github.com/explosion/spaCy/issues/1457#issuecomment-354189166_

**Comment by ines** [comment]
The reason behind this is that the `en_core_web_sm` model doesn't actually have a vocab or vectors, while the large models do. That's part of what makes them fast and compact, but it also means that all words are oov, and tokens don't have any vectors assigned.

We're currently looking at how to provide a more compact vocabulary for the small models, so their behaviour on this is less confusing. In the meantime, you can always use the `en_core_web_md` or `en_core_web_lg` models instead.

**Comment by beowulfenator** [comment]
Thank you, that's what I ended up doing - switching to `en_core_web_md`.
