### ISSUE TITLE
Zero 0 is treated as punctuation in after some standalone words

### ISSUE THREAD

**Issue by clippered** [explosion/spaCy#2777]
## Problem
This is the code:

```
import spacy

nlp = spacy.load('en_core_web_sm')

def show(text):
  doc = nlp(text)
  print('TEXT: ', doc.text)
  for token in doc:
      print('  TOKEN: ', token.text, token.pos_, token.dep_)
     
# bug appears
show('Hello 0 World')

# ok
show('Hello 1 World')
```

This is the output:

```
TEXT:  Hello 0 World
  TOKEN:  Hello INTJ ROOT
  TOKEN:  0 PUNCT punct
  TOKEN:  World NOUN npadvmod
TEXT:  Hello 1 World
  TOKEN:  Hello INTJ intj
  TOKEN:  1 NUM nummod
  TOKEN:  World NOUN ROOT
```

I was just expecting 0 (zero) should not be treated as a punctuation, instead, it should be a number.
It also happens on other cases like:
```
show('Hi 0 World')
show('Hey 0 World')
show('Welcome 0 World')
```

## Environment
* Python Version Used: 3.6.6
* spaCy Version Used: 2.0.11

**Comment by ines** [comment]
The process of recognising part-of-speech tags is **statistical** and the model was trained on examples of those tags *in context*. POS tags are context-sensitive by definition. So it's expected that the results won't be very meaningful if you only pass in single words or random strings like `"Hello 0 World"`, which doesn't usually occur in real-world text. So the part-of-speech tagger tries to make sense of it and predicts 

To be fair, it would make sense to restrict the tagger to only predict `PUNCT` for closed classes that are actually punctuation. See here for more details: #331

It's also important to keep in mind that the pre-trained models distributed with the library are baseline models that were tuned for the best possible compromise of speed, size, and accuracy and make it easy to get started building your own systems. You **almost always** want to adjust the model to your specific domain if extracting named entities is important to you. You can find more details on this in the [documentation on training and updating models](https://spacy.io/usage/training).
