### ISSUE TITLE
EntityRuler throws Segmentation Fault in complex pattern case

### ISSUE THREAD

**Issue by imaurer** [explosion/spaCy#2779]
## How to reproduce the behaviour
```python
import spacy
nlp = spacy.load("en_core_web_lg")
ruler = nlp.create_pipe('entity_ruler')
nlp.add_pipe(ruler, before="ner")
ruler.add_patterns([{"label": "PRODUCT", "pattern": [{"lower": "arial"}, {"lower": "("}, {"lower": "ab987"}, {"lower": ")"}, {"lower": "foo"}, {"lower": "bar"}, {"lower": "baz"}, {"lower": "boo"}]}])
nlp("Arial (ab987) foo bar baz boo")
```

Results in:`Segmentation fault: 11`

## Your Environment

* Operating System: Mac OS X (10.13.6)
* Python Version Used: 3.6.6
* spaCy Version Used: 2.1.0a1
* Environment Information: built from commit 1759abf1e5703cb568e0f2de56ed1beb0388a6f6 on develop branch

Related to Issue #2513

**Comment by ines** [comment]
Thanks a lot – also for testing the entity ruler with a real-world use case! This is really helpful. I suspect this case might have something to do with how the entity recognizer handles existing entities in this particular case.

**Comment by GregSilverman** [comment]
Hi,
I too am getting a segmentation fault on this example (which is a common pattern we are using):

```
import spacy
nlp = spacy.load("en_core_web_lg")
ruler = nlp.create_pipe('entity_ruler')
nlp.add_pipe(ruler, before="ner")
ruler.add_patterns([{"label": "Age", "pattern":[{"IS_DIGIT":True},{"LOWER":"years"}]}])
nlp("10 years")
```

**Comment by honnibal** [comment]
Thanks for the report! Fixed on develop now. Will be out in the next nightly.
