### ISSUE TITLE
Tokenizing Windows paths behaves differently than tokenizing UNIX paths

### ISSUE THREAD

**Issue by BramVanroy** [explosion/spaCy#2781]
I coincidentally stumbled upon this behaviour where paths in a text are treated differently depending on their 'style'. I'm unsure whether this is the desired behaviour. (Even though personally I'd like to see identical behaviour for the two.)

```
/u/slick/udfs/math.a --> /u / slick / udfs / math.a
d:\udfs\math.dll --> d:\udfs\math.dll
```

## How to reproduce the behaviour
```python
import spacy

nlp = spacy.load('en', disable=['parser', 'ner', 'tagger', 'textcat'])

unix = r'/u/slick/udfs/math.a'
win = r'd:\udfs\math.dll'

u_doc= nlp(unix)
w_doc = nlp(win )

unix = ' '.join(str(token) for token in u_doc)
win = ' '.join(str(token) for token in w_doc)

print(unix)
print(win)
```

## Your Environment
* Operating System: Windows 10 64 bit
* Python Version Used: 3.6.5
* spaCy Version Used: 2.0.12

**Comment by ines** [comment]
Thanks for the report, that's an interesting case we haven't really covered in our tests yet! Looks like the `/` is included in the infixes, while the `\` isn't. We should be able to fix that in the global rules 👍

**Comment by BramVanroy** [comment]
> Thanks for the report, that's an interesting case we haven't really covered in our tests yet! Looks like the `/` is included in the infixes, while the `\` isn't. The problem here is that ideally, we'd love to preserve file paths as one token – but for forward slashes, this is problematic, because it's near impossible to reliably detect whether a string is a file path or something else. So we might have to live with the inconsistency here.

I came to the same conclusion in a similar issue. I was trying to find unicode sequences (of the type `\uabcd`) in a text with regular expressions but it seems impossible to be sure whether a path `\my\little\path\` contains such a unicode sequence or if it's just the path's name.

**Comment by ines** [comment]
Yeah, I think this might be a better case for domain-specific adjustments or even statistical models users can train based on their data. I don't think spaCy will be able to just handle this out-of-the-box.

For the file paths, you could try to add an entity type `FILE_PATH` to the entity recognizer that predicts whether a sequence of tokens is a file path. This might work well, especially if there are relevant clues in the context and you have enough examples. (You might even be able to produce training data programmatically by generating random paths and swapping them out.)

Once you have a model that can predict this confidently, you can write a simple pipeline component that makes sure all file paths are merged into a single token. For example:

```python
def merge_file_paths(doc):
    spans = [ent for ent in doc.ents if ent.label_ == 'FILE_PATH']
    for span in spans:
        span.merge()
    return doc

nlp.add_pipe(merge_file_paths, after='ner')
```
