### ISSUE TITLE
vocab["-0.23"].like_num is False

### ISSUE THREAD

**Issue by phdowling** [explosion/spaCy#2782]
Pretty straight forward, it seems like negative numbers are currently not flagged as numbers in the Lexeme object.

**Comment by sakatipomu** [comment]
Yes. I am also facing the same issue. Did you find any work around for this?

**Comment by DuyguA** [comment]
I checked is_num feature for you:

https://github.com/explosion/spaCy/blob/master/spacy/lang/en/lex_attrs.py

As far as I see, minus sign in front is not parsed. @ines what do you say?

**Comment by sakatipomu** [comment]
I already tried like_num attribute in token class, but it is not working. Currently I am doing this
```
is_num=""
try:
    float(token.text)
    is_num = True
except ValueError:
    is_num = False
```

**Comment by ines** [comment]
This would be good to handle, yes. I'd propose the following:

```python
def like_num(text):
    if text.startswith('+') or text.startswith('-'):
        text = text[1:]
    # rest of the function
```

**Comment by DuyguA** [comment]
Btw @ines , startswith can take a tuple as argument when I first found about it, I instantly fall in love :heart: So this is possible:

```
def like_num(text):
  if text.startswith(('+', '-')):
    text = text[1:]
 #rest of the func
```

**Comment by ines** [comment]
Ahh, nice! That's even better. I'm just writing some tests for this for all languages that implement `like_num`, so we can test that it works as expected.

**Comment by phdowling** [comment]
What about possibly also handling "~5", etc? Also, "±1" ?I know we're getting into the grey area here, and this isn't very high priority, but those kind of cases might also be interesting. Of course at some point, it's probably up to the user to just handle this or use a regex for the use case. + and - are definitely a good improvement in the general case though.

**Comment by DuyguA** [comment]
From my side, why not... additions can go in a similar fashion.
