### ISSUE TITLE
Serialization of Vocab does not retain language

### ISSUE THREAD

**Issue by plison** [explosion/spaCy#2785]
I noticed a problem when serializing a `Vocab` object to disk:

```python
>> import spacy
>> nlp = spacy.load("en")
>> print(nlp.vocab.lang)`
'en'

>> nlp.vocab.to_disk("vocab")
>> vocab2 = spacy.vocab.Vocab().from_disk("vocab")
>> print(vocab2.lang)
''
```

This creates  problems when the vocabulary is used later on to create `Doc` objects, as the initialisation calls `_get_chunker(self.vocab.lang)`.

I'm using spacy 2.0.12. I also tried to use `vocab2 = spacy.load("en").from_disk("vocab")`, but this doesn't seem to properly load the vocabulary dumped on disk.

**Comment by honnibal** [comment]
Unfortunately there's not really a good way to solve this. The `from_disk()` and `from_bytes()` methods don't replace all of the arguments used in initialization, as we can't serialize the functions that set the lexical attributes. You need to use something like `nlp = spacy.blank('en')` to get the vocab initialized with the English defaults.

We could set the language in the `Vocab` serialization, but it seems like setting this one attribute while there's still other data left uninitialized isn't so helpful.
