### ISSUE TITLE
Missing words?

### ISSUE THREAD

**Issue by Vonderful** [explosion/spaCy#2787]
I'm LOVING spacy, but for my user case there appears to be key words missing from the vector model. For example when I run;
'reflexologist' in nlp.vocab
I get False.

As im new to both python and NLP, I was hoping there was an easy solution?
Thanks

**Comment by ines** [comment]
Which model are you using? If you're using the small `en_core_web_sm` model, this might be why:

> To make them compact and fast, spaCy's small [models](https://spacy.io/models) (all packages that end in sm) **don't ship with word vectors**, and only include context-sensitive **tensors**. This means you can still use the `similarity()` methods to compare documents, spans and tokens – but the result won't be as good, and individual tokens won't have any vectors assigned. So in order to use real word vectors, you need to download a larger model:
>
> ```bash
> python -m spacy download en_core_web_lg
> ```
> ([Source](https://spacy.io/usage/vectors-similarity))

We're currently looking at how to provide a more compact vocabulary for the small models, so their behaviour on this is less confusing.

**Comment by Vonderful** [comment]
Hi
Thanks for the response. I am using en_core_web_lg, which is why im confused as I would have expected reflexologist to exist within. No bother, im trying to work out if I can recode the search of reflexologist to something that is in the model!

**Comment by ines** [comment]
Ah okay, that's interesting. I just tested it, also with the new model for `spacy-nightly` (`v2.1.0`), and you're right, it doesn't seem to exist in the model / vocab / vectors. "reflexology" does, though:

```python
>>> nlp = spacy.load('en_core_web_lg')
>>> 'reflexologist' in nlp.vocab
False
>>> 'reflexology' in nlp.vocab
True
```

One thing you could to is parse a bunch of text, extract the words that are not in the vocab and then set their vectors to the vector of a similar word. If you use the [`Vectors.add` method](https://spacy.io/api/vectors#add), you can specify a `row` number of the existing vector to map the new word to – so you're not adding a separate vector, but are mapping the new word to an existing one. This lets you keep your vectors table small, while still achieving maximum coverage.

**Comment by Vonderful** [comment]
That sounds like a good plan, thanks! I don't suppose there are any code examples?!

**Comment by Vonderful** [comment]
Ive managed to write some code based on https://spacy.io/api/vectors#add. However when I run it I get an error;
CODE``
