### ISSUE TITLE
Seeking explicit instructions on how to recompile local project with proposed patch

### ISSUE THREAD

**Issue by gavrieltal** [explosion/spaCy#2794]
Hi,

I'm having trouble teaching myself how to toy with/test patches to my local clone of spaCy in a virtual environment python repl. In particular, whenever I make changes to the code, I don't see that reflected in values returned in the repl. In addition to following the basic instructions here compiling from source (https://spacy.io/usage/#section-quickstart), I've also tried `pip install -I -e .`, `python setup.py clean`, and `python -m compileall -f *directory*`. I get a failure from Fabric that says `No module named fabric.api` even though it is installed in my virtual environment. None of these commands I found online have helped me see my changes.

It would be appreciated if the documents describing how to compile from source also said how to recompile from source with changes for use in a repl or in testing.

Thanks!

**Comment by gavrieltal** [comment]
I should mention that, if you provide the instructions here and it works out for me, I may volunteer to actually put them in the documentation if you think it would be worthwhile.

**Comment by honnibal** [comment]
For my own development, I usually set `PYTHONPATH=`pwd`, and run `python setup.py build_ext --inplace`, which I often set to something convenient with a local alias. If you import spacy within your repl, and write `print(spacy.__file__)`, you should see that your local path. If not, then you've also somehow got spaCy installed in your virtualenv, which is not what you want.

The fabfile was a bad idea, as it introduces another dependency and isn't really worth it. On develop I've been using a Makefile: https://github.com/explosion/spaCy/blob/develop/Makefile

**Comment by gavrieltal** [comment]
So I actually think I may have set up the virtual environment correctly (using your Makefile and using the online instructions), since I have

`>>> print(spacy.__file__)
/home/gavriel/Desktop/python/spaCy/spacy/__init__.py`

I also noticed that if I totally comment out a function in the source code locally (`.py`), the python repl complains that the source code for that function is missing (as it should), and the complaint disappears if I uncomment. However, if I simply change the function (say, from `return True` to `return 445` or `return False`) I'll notice no change in behavior in the repl and get `True` regardless.

I'm guessing there's some trick about compiling python projects that I don't know. Do you know what might be up?

Thanks.

**Comment by honnibal** [comment]
@gavrieltal Are you restarting the repl? In theory you shouldn't have to, but I don't know whether the `reload()` function always works correctly.

**Comment by gavrieltal** [comment]
So, I simply tried playing with a different file using these instructions (as were also available online) and the recompilation was working fine.

On the other hand, my problem may have been trying to play explicitly with `lex_attrs.py`. Perhaps importing the English (`nlp = spacy.load('en')` or `nlp = English()`) has been overriding changes.

Thanks for the help.

**Comment by ines** [comment]
Loading the model will definitely override these properties, yes. This would also explain why Python complains if the file isn't there (because it tries to import it when initialising the language), and why changes are not reflected (because the model overrides them).

**Comment by gavrieltal** [comment]
So, to be clear, how would one work on a development version of the model?
