### ISSUE TITLE
importing spacy results in RuntimeWarning

### ISSUE THREAD

**Issue by Lunalight** [explosion/spaCy#2798]
I installed spacy with conda install -c conda-forge spacy. This all seemed to work fine, however, when I try to import spacy I get an error (see below). I even reinstalled numpy.

```
>>> import spacy
C:\Users\x\AppData\Local\Continuum\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
C:\Users\x\AppData\Local\Continuum\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192, got 176
  return f(*args, **kwds)
C:\Users\x\AppData\Local\Continuum\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
C:\Users\x\AppData\Local\Continuum\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192, got 176
  return f(*args, **kwds)
```

## Info about spaCy
* **spaCy version:** 2.0.12
* **Platform:** Windows-10-10.0.17134-SP0
* **Python version:** 3.6.6
* **Models:** en

**Comment by ines** [comment]
Hi and sorry about that. This is indeed related to a numpy version issue, and will be resolved in the next update of spaCy. 

The message you're seeing is only a warning, though, and not an error – so you should still be able to use spaCy normally. 

If you like, you can [disable Python warnings](https://stackoverflow.com/questions/14463277/how-to-disable-python-warnings) to hide the message. Alternatively, you could also try installing `numpy==1.14.5`, which should make the error go away (see #2593).

**Comment by raj6996** [comment]
PS C:\Users\YL> python
```
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
C:\Python37\lib\importlib\_bootstrap.py:219: RuntimeWarning: cymem.cymem.Pool size changed, may indicate binary incompatibility. Expected 48 from C header, got 64 from PyObject
  return f(*args, **kwds)
C:\Python37\lib\importlib\_bootstrap.py:219: RuntimeWarning: cymem.cymem.Address size changed, may indicate binary incompatibility. Expected 24 from C header, got 40 from PyObject
  return f(*args, **kwds)
>>>
```

**Comment by Jaypratap** [comment]
How i fix this issue, I have Python Version: 3.6.5, 
C:\Users\asn\AppData\Local\Programs\Python\Python36-32\lib\importlib\_bootstrap.py:219: RuntimeWarning: cymem.cymem.Pool size changed, may indicate binary incompatibility. Expected 24 from C header, got 32 from PyObject
  return f(*args, **kwds)
C:\Users\asn\AppData\Local\Programs\Python\Python36-32\lib\importlib\_bootstrap.py:219: RuntimeWarning: cymem.cymem.Address size changed, may indicate binary incompatibility. Expected 12 from C header, got 20 from PyObject
  return f(*args, **kwds)

**Comment by honnibal** [comment]
Could you try a 64 bit version of Python, instead of the 64-bit version you're using?

**Comment by Jaypratap** [comment]
when i try with python 3.6.5 (64 bit) got the following error which mentions by raj6996:

[C:\Users\asn\AppData\Local\Programs\Python\Python36\lib\importlib\_bootstrap.py:219: RuntimeWarning: cymem.cymem.Pool size changed, may indicate binary incompatibility. Expected 48 from C header, got 64 from PyObject
  return f(*args, **kwds)
C:\Users\asn\AppData\Local\Programs\Python\Python36\lib\importlib\_bootstrap.py:219: RuntimeWarning: cymem.cymem.Address size changed, may indicate binary incompatibility. Expected 24 from C header, got 40 from PyObject
  return f(*args, **kwds)](url)

**Comment by arlind19** [comment]
Same problem...no solution yet.

**Comment by Mani7895** [comment]
I am facing the same issue. How can I resolve it?

**Comment by Jaypratap** [comment]
I solve this issue, I used pycharm. and i try with python 32 bit as well as 64 bit but problem not solved.
Here is solution:
First of all  connect Pycharm with "Anacoda".
and install spacy.
Now you have to download model "en/en_core_web_lg" and so on. If you try with cmd or python terminal you got the same error again.
So you have to go Anaconda Navigator.
Enviroments-> choose folder-> open terminal
download by using python -m spacy download en_core_web_lg
Hope you resolve issue by this.

**Comment by BramVanroy** [comment]
The issue remains with Python 3.7.1. The solution as provided [here](https://github.com/explosion/spaCy/issues/2593) does not help.

**Comment by chpoit** [comment]
Still an issue

**Comment by Jefffish09** [comment]
Is this issue fixed now?

**Comment by honnibal** [comment]
Which version of spaCy are you installing? I haven't been able to reproduce this.

**Comment by BramVanroy** [comment]
@honnibal I haven't seen the error in a while, so I assume it is solved (for me).

**Comment by mishraprafful** [comment]
spacy version is 2.0.18.

**Comment by mishraprafful** [comment]
@honnibal the platform is ubuntu 16.04 with python 3.7.

**Comment by coffeebeanustb** [comment]
Aconda will deal the problem

**Comment by itcmixu** [comment]
i have spaCy 2.0.16, numpy 1.16.2, Ubuntu 18.0.4 64-bit. Python 3.7.1.

and have the same problem! any solutions out there?
