### ISSUE TITLE
Using a new spacy version in other projects

### ISSUE THREAD

**Issue by HediehZK** [explosion/spaCy#2813]
I have used Spacy and developed it for a new language. I have built it and I assumed that is ready. however I can't use it in other projects. I want to use Rasa chatbot which is using spacy. How can I use my own spacy instead of the global one???

* Operating System: Linux
* Python Version Used: 3.6

**Comment by ines** [comment]
If you install a third-party package that depends on spaCy (e.g. Rasa), it will install the latest release version from pip or conda, whichever package manager you use.

However, you can try the following to replace that version with your modified copy. If you haven't done so already, I'd also recommend using a virtual environment for your project, so you're not always installing packages globally: 

```python
python -m venv .env
source .env/bin/activate
# install your packages and dependencies
```

Next, uninstall the spaCy version that came with the package:

```bash
pip uninstall spacy
```

Then install your local spaCy directory (the one that you've modified) in "editable mode" or "development mode" by [using the `-e` flag](https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-e). If you're using a virtual environment for your chatbot project, make sure that it's activated. If you need help with this approach, try searching for ["install Python package in development mode"](https://www.google.com/search?q=install+Python+package+in++development+mode) or something similar.

```bash
pip install -e /path/to/your/local/spacy
```

To check that `spacy` maps to the correct version, you can run the following command to find the path of the installation within your `site-packages`:

```bash
python -c "import spacy; print(spacy.__file__)"
```

You can now double-check if that directory includes your local fixes.

Of course, this approach only works for local development – if you want to deploy your project or ship it to someone else, you obviously need to include your modified version of spaCy as well.

Finally, if the modifications you've made are something more general that other users would benefit from as well, you can always submit a pull request to this repo. If your changes are suitable to be merged into the core library, they'll be included in the next official release of spaCy, so you'll be able to use them by just installing the package from pip or conda.

**Comment by HediehZK** [comment]
Hello Ines,
Thanks for the perfect reply. I will follow the instructions tomorrow at
work. I have only one more question.
When i run the spacy through the terminal, it works fine, however i can not
run it with the python run. Do you have any idea about it?
