### ISSUE TITLE
💫 PyTorch / spaCy integration

### ISSUE THREAD

**Issue by honnibal** [explosion/spaCy#2816]
CuPy 5.0 will bring DLPack support to [Thinc](https://github.com/explosion/thinc), allowing us to complete the long-awaited [PyTorch](https://pytorch.org/) integration. This can already be tried on the latest `spacy-nightly` release. **The following notes are a draft of a post detailing the purpose of the integration, and how it will work.** See [`examples/pytorch_lstm_tagger.py`](https://github.com/explosion/thinc/blob/master/examples/pytorch_lstm_tagger.py) for a current working example of the wrapper in Thinc.

### How can I use PyTorch with spaCy?

While spaCy's internal machine learning needs are served by its own library ([Thinc](https://github.com/explosion/thinc)), for general-purpose deep learning models, we recommend most users try PyTorch first: it's well documented, popular, and has a design that's well suited for NLP's variable-length sequences.

The easiest way to use a PyTorch model in spaCy is to use one of Thinc's new wrapper classes:

* `thinc.extra.wrappers.PyTorchWrapper`
* `thinc.extra.wrappers.PyTorchWrapperRNN`

With these wrappers, you can build your PyTorch model as normal, pass it into the wrapper, and then pass the resulting Thinc model object into a spaCy pipeline component. The wrapper takes care of details like saving and loading, and ensures that calls to `component.update()` will be handled correctly.

One particularly neat aspect of this approach is that Thinc models follow a highly composable interface, making it easy to write higher-order functions to wire the model together. This is just as true of your wrapped models as any others.

For instance, let's say you want to use run spaCy's entity recognizer as a pre-process, and then merge the named entities into a single token, represented by their entity label. After pre-processing the text in this way, you want to run it through a text classification model, which you'll implement in PyTorch.

spaCy has built-in support for the first parts of the pre-processing logic – identifying the named entities and merging them: 

```python
nlp = spacy.load('en_core_web_md')
nlp.add_pipe(nlp.create_pipe('merge_entities'))
```

spaCy also has a `TextCategorizer` component. This component expects to pass a list of `Doc` objects to its model, and receive an array of scores, representing class probabilities. Predicted classes can then be stored on the `Doc` object, in the `doc.cats` attribute.

As we've seen, the `PyTorchWrapper` and `PyTorchWrapperRNN` classes can accept any PyTorch model, letting you implement that part however you like. However, the component is expecting to pass in `Doc` objects, which PyTorch models won't be expecting to receive. Fortunately, Thinc makes this problem very easy to solve. We just have to write a function to handle the pre-processing logic:

```python
from thinc.api import layerize

@layerize # The layerize decorator turns a stateless function into a Model.
def extract_arrays(docs, drop=0.):
    # Get a uint64 hash of the words in the document.
    arrays = [doc.to_array(['ORTH']) for doc in docs]
    output = pad_batch(arrays) # Whatever padding or truncation logic you want
    # Layers must return a tuple with the output, and a callback to do the
    # backward pass. We don't need to backprop this transformation, so we can
    # return None.
    backward = None
    return output, backward
```

Having applied the `@layerize` decorator, the `extract_arrays` function works like any other Thinc model. We simply need to place it before our `PyTorchWrapper` model, to compose the two together. The `chain()` function is the easiest way to do this: it's a higher-order function that takes two functions `f(x)` and `g(x)`, and composes them to make `g(f(x))`.

Putting it together, this is all we'd have to do to write our custom component:

```python
from spacy.pipeline import TextCategorizer
from thinc.api import chain
from thinc.extra.wrappers import PyTorchWrapper


class PyTorchTextCategorizer(TextCategorizer):
    @classmethod
    def Model(cls, nr_class, **cfg):
        return chain(
            extract_arrays,
            PyTorchWrapper(
                build_your_pytorch_model(nr_class, **cfg)))
```

You'd then be able to add the component to your spaCy pipeline, take advantage of spaCy's pre-processing, and easily access the predictions in the rest of your application.

Of course, not every task will have a built-in spaCy component. For instance, we don't currently have components for tasks like translation, semantic role labelling, or coreference resolution – but you can still use the same technique for these tasks. You'll just have to subclass a few more methods, especially `set_annotations()` and `get_loss()`.

**Comment by millawell** [comment]
Would be great if you could include https://github.com/explosion/spaCy/commit/a26fe8e7bb4350503843a3471d48ffd7891805a3 into the nightly build <3

**Comment by abhi18av** [comment]
Hi Team Spacy,

What are the plans regarding officially supporting `PyTorch` backend?

**Comment by samhardyhey** [comment]
Hey Matt,

This is a great little primer! I've followed your example as above as best I can with some slight alterations:

- I've implemented sequence padding via ```keras.preprocessing.sequence.pad_sequences```

- I've implemented a very basic FF NN, detailed below:

```
class Net(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(Net, self).__init__()
        self.layer_1 = nn.Linear(input_size, hidden_size, bias=True)
        self.relu = nn.ReLU()
        self.layer_2 = nn.Linear(hidden_size, hidden_size, bias=True)
        self.output_layer = nn.Linear(hidden_size, num_classes, bias=True)

    def forward(self, x):
        out = self.layer_1(x)
        out = self.relu(out)
        out = self.layer_2(out)
        out = self.relu(out)
        out = self.output_layer(out)
        return out
```
Pretty hacky I know, though I'm just trying to get something off the ground. When I try to insert this custom component into a pipeline via:

```
@layerize
def extract_arrays(docs, drop=0.):
    # Get a uint64 hash of the words in the document (hacky tokenization)
    # **potentially use some other tokenising logic here
    arrays = [doc.to_array(['ORTH']) for doc in docs]
    # Whatever padding or truncation logic you want
    output = pad_sequences(arrays, maxlen=100)
    # Layers must return a tuple with the output, and a callback to do the
    # backward pass. We don't need to backprop this transformation, so we can
    # return None.
    backward = None
    return output, backward


class PyTorchTextCategorizer(TextCategorizer):
    @classmethod
    def Model(cls, **cfg):
        return chain(
            extract_arrays,
            PyTorchWrapper(
                Net(sequence_length, num_hidden_layers, num_classes, **cfg)))


# add new component to pipeline
nlp = spacy.load('en')
ff_text_cat = PyTorchTextCategorizer(nlp)
nlp.add_pipe(ff_text_cat)
nlp.pipeline
```
The pipeline alterations go through just fine, though any attempt to process a document with this new pipeline results in a TypeError like so:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-90-5ac692dfa414> in <module>()
----> 1 nlp('hello world')

~/anaconda3/lib/python3.6/site-packages/spacy/language.py in __call__(self, text, disable)
    344             if not hasattr(proc, '__call__'):
    345                 raise ValueError(Errors.E003.format(component=type(proc), name=name))
--> 346             doc = proc(doc)
    347             if doc is None:
    348                 raise ValueError(Errors.E005.format(name=name))

pipeline.pyx in spacy.pipeline.TextCategorizer.__call__()

pipeline.pyx in spacy.pipeline.TextCategorizer.predict()

TypeError: 'bool' object is not callable
```

I think I've narrowed this down to a "lack of weights" being present within the pipeline component, as similar issues (stack traces) were encountered [here](https://support.prodi.gy/t/outdated-documentation-and-trouble-loading-textcat-model/759/3) and [here](https://github.com/explosion/spaCy/issues/1702).

So at this point, I'm thinking I would need to, train and write this custom component to disk (as one possible workflow at least), in a similar style to what is detailed within the other thinc torch examples.

Any hints would be greatly appreciated!

**Comment by honnibal** [comment]
@samhardyhey Try `ff_text_cat.begin_training()`

A bit of background on this: When you create the class, it doesn't create the model object (unless you pass one into the constructor). By default, it instead sets the `self.model` to the placeholder value `True`. You can also set `False` to tell it not to load a model later.

Setting the placeholder value allows us to separate the object creation from weights-loading, which is pretty important. In early versions of spaCy, we tried to load the weights inside the constructor, and this was a huge mess.

The upshot of all this is that you need to call either `.begin_training()` or a loading method like `.from_bytes()` or `.from_disk()` to get a model object. Alternatively, you can always create a model explicitly by calling the `pipe.Model()` classmethod, and assigning the output to the `pipe.model` attribute.

**Comment by samhardyhey** [comment]
Alright! Thanks for the prompt response as always. A few new issues:

I think there is a missing import call to ```contextlib``` within ```thinc.extra.wrappers.py```, at least within the most recent, spacy-compatible version of thinc (see env info below). I'm getting this traceback error message:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-3-7b9f8fdb5d21> in <module>()
      1 from spacy.pipeline import TextCategorizer
      2 from thinc.api import chain
----> 3 from thinc.extra.wrappers import PytorchWrapper
      4 from thinc.api import layerize
      5 

~/anaconda3/lib/python3.6/site-packages/thinc/extra/wrappers.py in <module>()
      9 
     10 
---> 11 class PytorchWrapper(Model):
     12     '''Wrap a PyTorch model, so that it has the same API as Thinc models.
     13     To optimize the model, you'll need to create a PyTorch optimizer and call

~/anaconda3/lib/python3.6/site-packages/thinc/extra/wrappers.py in PytorchWrapper()
     70         raise NotImplementedError
     71 
---> 72     @contextlib.contextmanager
     73     def use_params(self, params): # pragma: no cover
     74         # TODO: Implement

NameError: name 'contextlib' is not defined
```
I should have flagged this before my original issue (as a separate spacy/thinc issue I suppose). Nevertheless.

Getting a new stacktrace error which looks like this:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-38c9a8f7492f> in <module>()
----> 1 nlp(df.iloc[0].document)

~/anaconda3/lib/python3.6/site-packages/spacy/language.py in __call__(self, text, disable)
    344             if not hasattr(proc, '__call__'):
    345                 raise ValueError(Errors.E003.format(component=type(proc), name=name))
--> 346             doc = proc(doc)
    347             if doc is None:
    348                 raise ValueError(Errors.E005.format(name=name))

pipeline.pyx in spacy.pipeline.TextCategorizer.__call__()

pipeline.pyx in spacy.pipeline.TextCategorizer.predict()

~/anaconda3/lib/python3.6/site-packages/thinc/neural/_classes/model.py in __call__(self, x)
    159             Must match expected shape
    160         '''
--> 161         return self.predict(x)
    162 
    163     def pipe(self, stream, batch_size=128):

~/anaconda3/lib/python3.6/site-packages/thinc/api.py in predict(self, X)
     53     def predict(self, X):
     54         for layer in self._layers:
---> 55             X = layer(X)
     56         return X
     57 

~/anaconda3/lib/python3.6/site-packages/thinc/neural/_classes/model.py in __call__(self, x)
    159             Must match expected shape
    160         '''
--> 161         return self.predict(x)
    162 
    163     def pipe(self, stream, batch_size=128):

~/anaconda3/lib/python3.6/site-packages/thinc/neural/_classes/model.py in predict(self, X)
    123 
    124     def predict(self, X):
--> 125         y, _ = self.begin_update(X)
    126         return y
    127 

~/anaconda3/lib/python3.6/site-packages/thinc/extra/wrappers.py in begin_update(self, x_data, drop)
     36                 optimizer.step()
     37             return dX
---> 38         return self.ops.asarray(y_var.data), backward
     39 
     40     def to_disk(self, path):

NameError: name 'backward' is not defined
```

Sys info:
**spacy:** 6.12.1
**thinc:** 6.12.1
**OS:** Ubuntu 16.04

**Comment by honnibal** [comment]
Ah, you're using an old version. Try `spacy-nightly`. I think this problem was fixed a while ago, but I also just pushed a new version (2.1.0a8). Note that you'll need to redownload your models, as the new version has made some small changes that required the models to be retrained.

**Comment by samhardyhey** [comment]
Thanks for those pointers. I set up a new env spacy's latest nightly build (```2.1.0a9.dev0```) which came with thinc version ```7.0.1```. I've also re-downloaded the ```en``` model within this new env for use.

Now a different type error is being thrown. Detailed below is the stack trace that results from calling the modified pipeline:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-279-cab53cd6dad1> in <module>
----> 1 nlp(df.iloc[0].document)

~/miniconda3/envs/spacy_experimental/lib/python3.6/site-packages/spacy/language.py in __call__(self, text, disable)
    368             if not hasattr(proc, "__call__"):
    369                 raise ValueError(Errors.E003.format(component=type(proc), name=name))
--> 370             doc = proc(doc)
    371             if doc is None:
    372                 raise ValueError(Errors.E005.format(name=name))

pipes.pyx in spacy.pipeline.pipes.TextCategorizer.__call__()

pipes.pyx in spacy.pipeline.pipes.TextCategorizer.predict()

~/miniconda3/envs/spacy_experimental/lib/python3.6/site-packages/thinc/neural/_classes/model.py in __call__(self, x)
    163             Must match expected shape
    164         """
--> 165         return self.predict(x)
    166 
    167     def pipe(self, stream, batch_size=128):

~/miniconda3/envs/spacy_experimental/lib/python3.6/site-packages/thinc/neural/_classes/feed_forward.py in predict(self, X)
     38     def predict(self, X):
     39         for layer in self._layers:
---> 40             X = layer(X)
     41         return X
     42 

~/miniconda3/envs/spacy_experimental/lib/python3.6/site-packages/thinc/neural/_classes/model.py in __call__(self, x)
    163             Must match expected shape
    164         """
--> 165         return self.predict(x)
    166 
    167     def pipe(self, stream, batch_size=128):

~/miniconda3/envs/spacy_experimental/lib/python3.6/site-packages/thinc/neural/_classes/model.py in predict(self, X)
    127 
    128     def predict(self, X):
--> 129         y, _ = self.begin_update(X, drop=None)
    130         return y
    131 

~/miniconda3/envs/spacy_experimental/lib/python3.6/site-packages/thinc/extra/wrappers.py in begin_update(self, x_data, drop)
     49         along with a callback to handle the backward pass.
     50         """
---> 51         x_var = torch.autograd.Variable(xp2torch(x_data), requires_grad=True)
     52         # Make prediction
     53 

~/miniconda3/envs/spacy_experimental/lib/python3.6/site-packages/thinc/extra/wrappers.py in xp2torch(xp_tensor)
     24         return torch.utils.dlpack.from_dlpack(xp_tensor.toDlpack())
     25     else:
---> 26         return torch.from_numpy(xp_tensor)
     27 
     28 

TypeError: expected np.ndarray (got list)
```
I thought to wind things back a little and eliminate any variation in my pytorch model, as well as the ```TextCat``` component wrapper. I explicitly tried to train a thinc-wrapped pytorch model, via ```PyTorchWrapper```. The same type error resulted, specifically from the call to ```model.evaluate()```. I've used the mnist MLP detailed within ```thinc/examples/pytorch_mnist_mlp.py``` without any alterations, though I also tried my original MLP to be sure. The thinc training script looks like this:

```
model = PyTorchWrapper(Net(sequence_length, hidden_layer_size, num_classes))
nb_epoch = 10

with model.begin_training(train_X, train_y, L2=1e-6) as (trainer, optimizer):
    epoch_loss = [0.0]

    def report_progress():
        print(epoch_loss[-1],
              model.evaluate(dev_X, dev_y), trainer.dropout)
        epoch_loss.append(0.0)

    trainer.each_epoch.append(report_progress)
    trainer.nb_epoch = nb_epoch
    trainer.dropout = 0.3
    trainer.batch_size = 128
    trainer.dropout_decay = 0.0
    train_X = model.ops.asarray(train_X, dtype="float32")
    y_onehot = to_categorical(train_y)
    for X, y in trainer.iterate(train_X, y_onehot):
        yh, backprop = model.begin_update(X, drop=trainer.dropout)
        loss = ((yh - y) ** 2.0).sum() / y.shape[0]
        backprop(yh - y, optimizer)
        epoch_loss[-1] += loss
    with model.use_params(optimizer.averages):
        print("Avg dev.: %.3f" % model.evaluate(dev_X, dev_y))
```

I also ran the ```thinc/examples/pytorch_mnist_mlp.py``` example, which threw the exact same error np.ndarray-list type error. To eliminate any variation in my training data.

So looking into the specifics of ```model.evaluate()```, I was able to troubleshoot the issue to this line:
```
scores = self.ops.flatten(list(self.pipe(X)))
```
Which I've explicitly tested with sequence data I was attempting to put through. Specifically, the list-casting of the pipe call. I'm a bit lost at this point though haha, so any thoughts would be appreciated!

Thanks once again.

**Comment by honnibal** [comment]
This should be fixed now, and the PyTorch integration is a bit deeper with `spacy-pytorch-transformers`. So the work here is pretty much complete --- although we do want to publish more tutorials.
