### ISSUE TITLE
ValueError: [E088]

### ISSUE THREAD

**Issue by dripti** [explosion/spaCy#2817]
## Your Environment

* Operating System: 10 
* Python Version Used: Spyder, Python 3.6.4
* spaCy Version Used:(2.0.12)
   max_length=self.max_length))

ValueError: [E088] Text of length 5854574 exceeds maximum of 1000000. The v2.x parser and NER models require roughly 1GB of temporary memory per 100,000 characters in the input. This means long texts may cause memory allocation errors. If you're not using the parser or NER, it's probably safe to increase the `nlp.max_length` limit. The limit is in number of characters, so you can check whether your inputs are too long by checking `len(text)`.

**Comment by honnibal** [comment]
What's the problem?

**Comment by dripti** [comment]
The below given error, is there any fix to it?

ValueError: [E088] Text of length 5854574 exceeds maximum of 1000000. The v2.x parser and NER models require roughly 1GB of temporary memory per 100,000 characters in the input. This means long texts may cause memory allocation errors. If you're not using the parser or NER, it's probably safe to increase the nlp.max_length limit. The limit is in number of characters, so you can check whether your inputs are too long by checking len(text).

**Comment by honnibal** [comment]
As described in the error message, either decrease the length of the input, or increase the nlp.max_length limit.

**Comment by dripti** [comment]
how can i increase the limit?
