### ISSUE TITLE
Italian "po'" word is tokenized incorrectly

### ISSUE THREAD

**Issue by dvaosta** [explosion/spaCy#2822]
## Your Environment
* **spaCy version:** 2.0.12
* **Platform:** Windows-10-10.0.16299-SP0
* **Python version:** 3.6.5
* **Models:** it

"Po'" (with the apostrophe) is the truncated form of "poco" (that means "a little") and must be considered as a single word, while currently spacy considers "po" and "'" as two tokens.
Notice that "Po", without the apostrophe, is the name of the longhest river in Italy. But in this case it always has the capital P and is never followed by the apostrophe.

**Comment by dvaosta** [comment]
Thanks.

**Comment by ines** [comment]
Merging this with the master issue in #1642!
