### ISSUE TITLE
💫 Segfault if doc.ents includes previously set entities with unknown label

### ISSUE THREAD

**Issue by ines** [explosion/spaCy#2825]
Potentially related: #2779

## How to reproduce the behaviour

The entity recognizer should respect previously set entities, both with unknown labels (not added to the model) and known labels (added to the model). The following causes a segmentation fault:

```python
from spacy.lang.en import English
from spacy.tokens import Span

nlp = English()
ner = nlp.create_pipe('ner')
nlp.add_pipe(ner)
nlp.begin_training()

def test_component(doc):
    doc.ents = [Span(doc, 0, 1, label=doc.vocab.strings['YOLO'])]
    return doc

nlp.add_pipe(test_component, before='ner')
doc = nlp("Hello world")
```

Adding `ner.add_label('YOLO')` makes the code run as expected (but also adds a label to the model, which shouldn't be the default case).

The same problem occurs if no label is specified on the span:

```python
from spacy.lang.en import English

nlp = English()
nlp.add_pipe(nlp.create_pipe('ner'))
nlp.begin_training()

def test_component(doc):
    doc.ents = [doc[0:1]]
    return doc

nlp.add_pipe(test_component, before='ner')
doc = nlp("Hello world")
```

## Your Environment

* **spaCy version:** 2.1.0a1 (`spacy-nightly`)
* **Platform:** Darwin-18.0.0-x86_64-i386-64bit (macOS 10.14)
* **Python version:** 3.6.0

**Comment by honnibal** [comment]
Fixed by e24f94ce 🎉
