### ISSUE TITLE
Does spaCy text classifier take into account new words in the text and creates embeddings for them?

### ISSUE THREAD

**Issue by reachtarunhere** [explosion/spaCy#2827]
Are pre-trained embeddings that are part of the spacy 'en' model used here. Further, are embeddings learned for new words from the dataset?

## Which page or section is this issue related to?
https://spacy.io/usage/training#section-textcat

Thanks

**Comment by honnibal** [comment]
Yes, representations are learned for new words on the fly, due to the use of hash embeddings. See here: https://support.prodi.gy/t/can-you-explain-how-exactly-hashembed-works/564/2

**Comment by reachtarunhere** [comment]
Thanks for the answer and the amazing write-up :+1:
