### ISSUE TITLE
Installing spacy in Windows 10 fails Winerror 2

### ISSUE THREAD

**Issue by BinayakCloud** [explosion/spaCy#2828]
Issue:
Pip install spacy-2.0.12.tar.gz
in windows 10 failed.
Based on few google searches instslled visual studio 17 build tools..no luck yet..
please help...
individually tried to install murmurhash but same error...
...

building 'mmh3' extension
error: [WinError 2] The system cannot find the file specified.

## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.5.5
* spaCy Version Used: 2.0.5
* Environment Information:

**Comment by tushar-nitave** [comment]
Are you using PyCharm?

**Comment by honnibal** [comment]
We're working on getting binary wheels uploaded for spaCy and its dependencies for Windows, which will make installation easier. I'm not positive why your building is failing, but in the meantime, you might find it easier to install wheels from here: https://www.lfd.uci.edu/~gohlke/pythonlibs/ .

**Comment by ines** [comment]
We've just released `v2.0.13`, which comes with pre-build binary wheels for spaCy. We're also working on releasing wheels for all of our dependencies so users will be able to install spaCy without needing a compiler.

In the meantime, you can also find pre-built wheels for Windows for spaCy and its dependencies (including `ujson` etc.) here: https://www.lfd.uci.edu/~gohlke/pythonlibs/
