### ISSUE TITLE
Python crash while enumerating noun_chunks with as_doc method on span objects

### ISSUE THREAD

**Issue by RM-PDX** [explosion/spaCy#2831]
## How to reproduce the behaviour

```python
import spacy
nlp = spacy.load('en_core_web_lg')
doc = nlp(u'Apple is a great fruit. But it can be debatable if it is the best.')

for sentence in doc.sents:
    for ent in sentence.as_doc().ents:
        print(ent.text, ent.label_)

    # Causes python kernel to crash
    for chunk in sentence.as_doc().noun_chunks:
        print(chunk.text)
```
Output:
Apple ORG
Apple
a great fruit
**--> Python crashes.**

## Your Environment
* spaCy version      2.0.11
* Platform           Windows-10-10.0.16299-SP0
* Python version     3.6.4
* Models             en_core_web_lg

* Operating System: Win 10
* Python Version Used: Python 3.6.4 |Anaconda, Inc.
* spaCy Version Used: 
* Environment Information: Jupyter notebook

**Comment by honnibal** [comment]
Yes, there's an open bug around this unfortunately. Please see https://github.com/explosion/spaCy/issues/1537

**Comment by RM-PDX** [comment]
Thanks and apologies for the duplicate.
