### ISSUE TITLE
When i load a new Spacy model, the memory used by the old assignment does not get released

### ISSUE THREAD

**Issue by sola91** [explosion/spaCy#2832]
Hello,

I am not able to switch between different Spacy models and release the memory used by old assigned models at the same time.  The logic of my application imply that I can switch between different models at runtime so I cannot avoid the load of a new model at this stage. 
A simple example:

```
import spacy
import threading

def printhello():
  threading.Timer(10.0, printhello).start()
  print "Hello, World!"

nlp = spacy.load('/model1')
nlp = spacy.load('/model2')

doc = nlp(u'This is a sentence.')
printhello()
```

Notice that the dummy function printhello() is used here only to keep the program running so that I can look at the memory usage in real time. 

By looking at the memory consuption on this example, I have noticed that the allocated memory is the sum of the two models used singularly. Moreover, I tried to use the 'del' command after the first assignment and to call gc.collect() but that didn't help. I even tried to set "nlp = None" after the first assignment.
Do you know why the memory related to the first model doesn't get released once I re-assign the nlp variable to a new model? Is there some logic that holds in memory references of unassigned models?

Thanks.
 
## Info about my environment:
 python -m spacy info --markdown

* **Python version:** 2.7.15
* **Platform:** Darwin-17.7.0-x86_64-i386-64bit
* **spaCy version:** 2.0.11
* **Models:** en

**Comment by honnibal** [comment]
I think this is just Python not releasing the memory back to the OS immediately. If you load the models in a loop, I think you'll find the memory not increasing.

That said, if you find that there's indeed a memory leak here, that would be useful to track down. I think the gc module has some methods that can show you what variables are currently loaded.
