### ISSUE TITLE
'x' is tagged PUNCT

### ISSUE THREAD

**Issue by bittlingmayer** [explosion/spaCy#2834]
Displacy tags `x` in `What are some Spanish words that start with x?` as `PUNCT`.

https://explosion.ai/demos/displacy?text=What%20are%20some%20Spanish%20words%20that%20start%20with%20x%3F&model=en_core_web_sm&cpu=0&cph=0

<img width="1101" alt="screen shot 2018-10-09 at 23 00 23" src="https://user-images.githubusercontent.com/11457984/46691987-2ad95380-cc17-11e8-962b-bfbf392b1ab9.png">

**Comment by bittlingmayer** [comment]
Interestingly, although often the errors are correlated, this time Google gets it right, which leads me to think it is not just from the training data but an actual bug.

<img width="918" alt="screen shot 2018-10-09 at 23 01 53" src="https://user-images.githubusercontent.com/11457984/46692077-5bb98880-cc17-11e8-9dca-a8421eccda6a.png">

**Comment by ines** [comment]
Well, I assume Google's model is likely trained on a different corpus, using a different process and a different model architecture. While the comparison is always interesting, I'm not sure this really indicates anything deeper about spaCy's pre-trained models.

I'm merging this with #3052. We've now added a master thread for incorrect predictions and related reports – see the issue for more details.

**Comment by bittlingmayer** [comment]
> I assume Google's model is likely trained on a different corpus

From my observation (caveat: a sort of rolling average over the past few years and biased towards English), often relatively peculiar errors on parsing specific sentences are so suspiciously similar between spaCy, Google and to some degree Stanford that my perhaps naïve conclusion is that there must be significant overlap in the training data.
