### ISSUE TITLE
More in depth custom pipeline docs or examples

### ISSUE THREAD

**Issue by RonRademaker** [explosion/spaCy#2837]
Hi, I'd appreciate some more in depth docs on creating custom pipelines. More specifically custom pipelines that actually use some for of machine or deep learning technology. So that would require pipeline with some training and prediction capabilities (where the current examples I found only do predict). Perhaps drilling down on one of the existing thinc pipelines (for exampe the EntityRecognizer) would work? Or are there already examples anywhere on such pipelines that can get me started?

**Comment by honnibal** [comment]
While it's not perfect, you might find the neural coreference resolution system from HuggingFace a useful reference: https://github.com/huggingface/neuralcoref
