### ISSUE TITLE
Cuda9, Cuda10 installation doc. Outdated CUDA9 env variable?

### ISSUE THREAD

**Issue by mratsim** [explosion/spaCy#2839]
The docs refer to setting the environment variable `CUDA9=1` for Cuda installation here: https://github.com/explosion/spaCy/blob/4cd9ec0f00788d08c053b885b5591fe134666a65/website/usage/_install/_instructions.jade#L83-L87

Related Cuda 9 installation issue from a year ago: https://github.com/explosion/spaCy/issues/1530#issuecomment-343213919

Checking on master at the moment (with the notoriously approximative Github search though) I don't see any reference of this flag in the code so I suppose this line can be dropped from the documentation.

I've also compiled it on my machine without the flag on Cuda10 without issue.

**Comment by ines** [comment]
Thanks! In spaCy `v2.0.16`, we've improved GPU installation via a separate `thinc_gpu_ops` package. We've also updated the documentation accordingly – see here: https://spacy.io/usage/#gpu
