### ISSUE TITLE
Juniper use outside of Spacy

### ISSUE THREAD

**Issue by choldgraf** [explosion/spaCy#2840]
Hey all - we worked with @ines a while back to help get Juniper working with Binder so that Spacy's awesome landing page could run kernels interactively. It seems like this could be generally useful outside of the spacy documentation! I just took a pass at getting Juniper to work with a different site (running locally on Jekyll), and ran into the following error:

```
Failed to load https://hub.mybinder.org/user/binder-examples-jupyterlab-37zvnqwv/api/kernels?1539273084123: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

I went to the Juniper repo (https://github.com/ines/juniper) but found that issues weren't enabled. So, I have a couple questions:

* First - is Juniper planning on being maintained as an open project for use outside of Spacy?
* Second - if so, any reason issues aren't allowed there? Should issues just be opened here?
* Third - if this is the right place for this issue, @ines any ideas on this "Access-Control-Allow-Origin" problem?

**Comment by ines** [comment]
Hmmm, it looks like `hub.mybinder.org` now disallows CORS, so basically, it blocks all cross-origin requests – I can't get any of the examples to work, including the ones on spacy.io or anywhere else, https or not 🤔 Maybe there's something I'm missing or something that needs to be updated, but at the moment, all requests seem to be blocked...

> First - is Juniper planning on being maintained as an open project for use outside of Spacy?
> Second - if so, any reason issues aren't allowed there? Should issues just be opened here?

I can possibly make it available "officially" if people are interested! The main reason I disabled issues was that I didn't have time to provide support for it (but I still wanted to make the code available for people to read and use, and make it transparent how the spaCy site implements the interactive code examples).
