### ISSUE TITLE
Spacy Matcher

### ISSUE THREAD

**Issue by mousum-github** [explosion/spaCy#2847]
How to define a pattern so that 'java developer' and 'javadeveloper' are matched to same term 'java developer'.

* Python Version Used: 2.7
* spaCy Version Used: 2.0
* Environment Information:

**Comment by giannisdaras** [comment]
Hello @mousum-github :)
If I understand correctly your question, you are looking for something like that:
```
import spacy
nlp = spacy.load('en_core_web_sm')
from spacy.matcher import PhraseMatcher
matcher = PhraseMatcher(nlp.vocab)
matcher.add('java developer', None, *[nlp('javadeveloper'), nlp('java developer')])
doc = nlp(u"I am a good javadeveloper. Actually, I am really good java developer.")
matches = matcher(doc)
for match in matches:
    match_start = match[1]
    match_end = match[2]
    print(doc[match_start:match_end])
```
You can always search for questions like that in the [docs][1].

[1]: https://spacy.io/api/phrasematcher
