### ISSUE TITLE
thinc requirement incompatibility

### ISSUE THREAD

**Issue by piercefreeman** [explosion/spaCy#2848]
## How to reproduce the problem

On a fresh install of spacy on a clean virtualenv (python 3.6.5), I see the following:

```
thinc 6.10.6 has requirement cymem<3.0.0,>=2.0.2, but you'll have cymem 1.31.2 which is incompatible.
thinc 6.10.6 has requirement msgpack-numpy<0.4.4.0, but you'll have msgpack-numpy 0.4.4 which is incompatible.
thinc 6.10.6 has requirement preshed<3.0.0,>=2.0.1, but you'll have preshed 1.0.1 which is incompatible.
```

* Operating System: OS X 10.13.5
* Python Version Used: 3.6.5
* spaCy Version Used: 2.0.13

**Comment by honnibal** [comment]
I think you got in just while we were updating those dependencies, but just before we got spaCy live.Try again? You should get v2.0.14

**Comment by piercefreeman** [comment]
Downloaded 2.0.14 fresh and have fewer errors but still one for numpy:

thinc 6.10.6 has requirement msgpack-numpy<0.4.4.0, but you'll have msgpack-numpy 0.4.4 which is incompatible.

**Comment by honnibal** [comment]
Unpublished Thinc 6.10.6 and spaCy v2.0.14 for now, as there was indeed version problems. Thanks for the report!
