### ISSUE TITLE
Italian model : tagging prepositions and tokenizing at apostrophes

### ISSUE THREAD

**Issue by fiannuzzi** [explosion/spaCy#2850]
Hello! First, thanks to the Spacy team for the excellent work. I just got started with the Italian model and I thought I’d share some recurrent problems I singled out after running it on several tens of thousands of texts to the purpose of extracting keywords. I noticed that a specific class of **prepositions is systematically pos-tagged as ADJ or NOUN instead of ADP**. It occurs to the so-called “preposizioni articolate”, a fusion between a preposition and a definite article (eg _alla, della, sulla, nella_…). Also, I noticed that the **tokenizer tends not to split terms containing apostrophes** (eg _all’interno, l’attenzione, l’altro_…). These then get a single pos tag, typically ADJ or NOUN once again (instead of, say, ADP+NOUN). I was looking around here for a solution, which I found by reading the replies to issue  #2822  (thank you). I’m creating a number of custom rules to force the correct pos-tagging of these prepositions and I’m forcing tokenization at apostrophes by re.sub(“\‘“, “\’ “, text) during text pre-processing (not too proud of that, but hey). I just thought I’d post it here in case someone encounters the same problem and also as something to look into for future releases of the model. Thank you :-)

##  Environment
* **spaCy version:** 2.0.12
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **Models:** en, fr, it
* **Python version:** 3.5.2

**Comment by kabramova** [comment]
Hi, I hit the same problem with Italian tokenization. If many people are working on this and creating custom rules, could we at least share them with each other (and with the overall project obviously)?

**Comment by kabramova** [comment]
Hi @fiannuzzi thanks for sharing :)

Shouldn't the rules be more like this though?

```python
special_case = [{ORTH: u'de', LEMMA: u'di', POS: PREP}, {ORTH: u'lla', LEMMA: u'la', POS: DET}]
nlp.tokenizer.add_special_case(u'della', special_case)
```

In addition, there are other issues with spacy tokenizer, e.g. honorifics:

```python
doc = nlp(u"Egr. sig. Rossi")
print([w.text for w in doc])
# [u'Egr', u'.', u'sig', u'.', u'Rossi']
special_case = nlp.tokenizer.add_special_case(u'Egr.', [{ORTH: u'Egr.', LEMMA: u'Egregio', POS: u'ADJ'}])
special_case = nlp.tokenizer.add_special_case(u'sig.', [{ORTH: u'sig.', LEMMA: u'signor', POS: u'NOUN'}])
doc = nlp(u"Egr. sig. Rossi")
print([w.text for w in doc])
# [u'Egr.', u'sig.', u'Rossi']
```

I was just suggesting to share whatever custom rules anyone writes for their purposes. I can share mine when I'm done but a better strategy would be to implement a custom Italian class I guess.

**Comment by ines** [comment]
Merging this with the master issue in #1642!
