### ISSUE TITLE
Question/Feature Request: Reducing spaCy package size

### ISSUE THREAD

**Issue by DomHudson** [explosion/spaCy#2851]
## Summary
Hi,  I was recently investigating the causes of our large docker images and I noticed that the spacy installation (v2.0.12) is taking approximately 346mb in the site-packages directory.

The vast majority of this large folder size originates from the language packages. As I only use the English language, my plan of attack was to fork spaCy and remove all languages other than `en`. After removing these languages, the folder size goes down to 37.5mb. This approach seems to work fine although I am wary about doing this.

## My feature request is
What would be required to implement functionality to split out other languages so they are either optionally included in an installed wheel or optionally installed? Is this something that other people would find beneficial? 

## My question is
Is this a safe or the best approach? 

Many thanks
Dom

---

![screenshot from 2018-10-15 18-28-45](https://user-images.githubusercontent.com/10864294/46967377-44abe800-d0a8-11e8-9ff9-cd892423b037.png)

**Comment by ines** [comment]
Thanks for bringing this up and yes, I definitely agree! 

I think the biggest bloat at the moment comes from the lemmatization lookup tables and other similar resources. Going forward, we'd love to transition the lemmatizers to rule-based solutions that rely on the tagger or to entirely statistical components (shipped via the models). These would also perform much better, so it's a win-win overall.

Developing the components isn't trivial, but we do have someone working on lemmatization for spaCy now. You can find more details in #2668. We've also been getting awesome community contributions (most recently for Greek and French)

**Comment by DomHudson** [comment]
@ines Thanks very much for your thoughts and quick response! Good to hear that it's on your radar. Do you think my intermittent approach of simply removing those folders for now is okay?

Many thanks
Dom

**Comment by ines** [comment]
> Do you think my intermittent approach of simply removing those folders for now is okay?

Yes, from spaCy's perspective, this should be okay – the language data is lazy-loaded, so `spacy.tr` for instance is only ever required if you load a model that specifies it, if you run `util.get_lang_class('tr')`, or if you actually import it from `spacy.lang`. (And if you run the tests, I guess.)

**Comment by ines** [comment]
Merging this with #3258!
