### ISSUE TITLE
POS Tagging for Hindi language support

### ISSUE THREAD

**Issue by heaven00** [explosion/spaCy#2853]
## Feature description

Hi, I was wondering if its a good idea to extend the hindi language model with POS Tags there is another repo being worked on https://github.com/pemagrg1/Hindi-POS-Tagging-and-Keyword-Extraction that can be added into the spacy ecosystem.

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
I am not sure, pretty new to answer that question but I imagine this to become part of the language models available with spacy.

**Comment by ines** [comment]
Merging this with the master thread in #3056!
