### ISSUE TITLE
conda/pip package dependencies issues break spacy

### ISSUE THREAD

**Issue by stas00** [explosion/spaCy#2859]
We have just released a new version of `fastai` and it works fine with `pip` which fetched conda-2.0.16, but blows up with `conda`, which only has 2.0.12. It breaks when trying to load spacy:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/disc1/fast.ai-1/br/fastai/master/fastai/__init__.py", line 1, in <module>
    from .basic_train import *
  File "/mnt/disc1/fast.ai-1/br/fastai/master/fastai/basic_train.py", line 2, in <module>
    from .torch_core import *
  File "/mnt/disc1/fast.ai-1/br/fastai/master/fastai/torch_core.py", line 2, in <module>
    from .imports.torch import *
  File "/mnt/disc1/fast.ai-1/br/fastai/master/fastai/imports/__init__.py", line 1, in <module>
    from .core import *
  File "/mnt/disc1/fast.ai-1/br/fastai/master/fastai/imports/core.py", line 6, in <module>
    import html, re, spacy, requests
  File "/home/stas/anaconda3/envs/pytorch-dev/lib/python3.6/site-packages/spacy/__init__.py", line 7, in <module>
    from .cli.info import info as cli_info
  File "/home/stas/anaconda3/envs/pytorch-dev/lib/python3.6/site-packages/spacy/cli/__init__.py", line 6, in <module>
    from .train import train
  File "/home/stas/anaconda3/envs/pytorch-dev/lib/python3.6/site-packages/spacy/cli/train.py", line 12, in <module>
    from ..gold import GoldCorpus, minibatch
  File "cymem.pxd", line 1, in init spacy.gold
ValueError: cymem.cymem.Pool has the wrong size, try recompiling. Expected 64, got 48
```

The problem was `cymem` dependency that wasn't getting resolved correctly by the `spacy` conda package.

After experimenting, I found I had to:

`conda uninstall cymem spacy`

and then:

`conda install fastai -c fastai`

```
The following NEW packages will be INSTALLED:

    cymem:   1.31.2-py36h6bb024c_0       
    fastai:  1.0.6-py_1            fastai
    preshed: 1.0.1-py36he6710b0_0        
    spacy:   2.0.12-py36h962f231_0       
    thinc:   6.10.3-py36h962f231_0     
```  

and then it's fine.

Would it be possible to release 2.0.16 with correct dependencies on conda? Thank you!

**Comment by stas00** [comment]
More nuances I have observed while experimenting with various install/uninstall sequences:

(we set `spacy>=2.0.16` in `setup.py`, and no pin for `spacy` in `conda/meta.yml`)

```
$ conda uninstall -y fastai spacy
$ pip uninstall -y fastai spacy
$ pip install fastai
Successfully installed fastai-1.0.6 spacy-2.0.16
$ conda install -y fastai -c fastai
The following NEW packages will be INSTALLED:

    fastai: 1.0.6-py_1            fastai
    spacy:  2.0.12-py36h962f231_0
```

and then it breaks as shown in the first post.

I then tried to reduce the test case to something simpler so that it won't depend on fastai.

```
$ conda uninstall -y  spacy cymem
$ pip uninstall -y  spacy cymem
$ pip install spacy

Successfully installed cymem-2.0.2 spacy-2.0.16
```

but it's broken:

`ModuleNotFoundError: No module named 'thinc'`

So unless I'm doing something wrong spacy-2.0.16 pip package has dependencies issue too. Please verify my steps, I have been doing this for a few hours now, so I could be hallucinating.

And then conda install does give a working spacy:

```
$ conda install -y spacy
Solving environment: done

## Package Plan ##

  environment location: /home/stas/anaconda3/envs/pytorch-dev

  added / updated specs:
    - spacy


The following NEW packages will be INSTALLED:

    cymem:   1.31.2-py36h6bb024c_0
    preshed: 1.0.1-py36he6710b0_0
    spacy:   2.0.12-py36h962f231_0
    thinc:   6.10.3-py36h962f231_0
```

and we can load spacy now.

But notice that conda completely ignores that I already installed spacy 2.0.16 via pip - it probably does that because pip's spacy package didn't do dependencies right and so it basically had to recover to its own set that it knows to work.

**Comment by stas00** [comment]
Taking in all the experiments I think that conda's 2.0.12 spacy package is just fine, especially since it has been working all along and the problem started after installing spacy-2.0.16 via pip. Perhaps the real problem is spacy-2.0.16 pip package which installs wrong dependencies? But I'm not sure any longer, I'm going to take a  break.

**Comment by honnibal** [comment]
The situation is:

* spaCy 2.0.12 (and I think 2.0.13): Works fine on conda as before
* spaCy 2.0.16: Requires cymem 2.0.2, which has not been published on conda yet. Therefore this version is not currently available on conda.

If you start with conda and install a bunch of stuff, and then switch to pip to install 2.0.16, I think you'll end up with an inconsistent installation.

**Comment by honnibal** [comment]
You really can't test the installations with a stateful environment. Actually you should wipe your cache in between tests as well.

pip in particular is stateful, because it doesn't have a SAT solver (which is why it's faster). If you're testing, you should probably just delete the environment entirely and recreate it to check things.

**Comment by stas00** [comment]
That makes sense. We already do that in CI builds.

It's just usually faster to reuse when I manually test on my slow machine. I guess it just happened to work until now re-using the same env w/ uninstalls. I will switch to fresh environment in my own experiments as you suggested. thank you.

**Comment by stas00** [comment]
@honnibal, FYI, cymem 2.02. got released on conda last night: https://anaconda.org/anaconda/cymem
