### ISSUE TITLE
Error Loading Model into spaCy

### ISSUE THREAD

**Issue by theoldhat** [explosion/spaCy#2861]
Hi,

I am trying load a spaCy model trained in a linux  Env to a Windows machine running spaCy. When I attempt to load the model from the model path I get the following:

![image](https://user-images.githubusercontent.com/31282809/47105040-de8ea480-d210-11e8-9be6-fa882d2eca63.png)

The model loads fine when I try it on the Linux machine where it was created.

The envs are as follows

## Windows Environment

* Operating System:  Windows Server 2012 R2
* Python Version Used:  Python 3.4.2
* spaCy Version Used: spaCy 2.012
* Environment Information:  Numpy 1.15.2

## Linux Environment

* Operating System: Ubuntu 18.04 Server
* Python Version Used:  Python 3.4.2
* spaCy Version Used: spaCy 2.012
* Environment Information:  Numpy 1.15.2

I think it may be related to this issue: 
#1634 

but am not positive.

Has anyone else experienced this?

Thanks!

**Comment by dendrondal** [comment]
If this seems to be a common problem, I can submit a PR to try and fix it. I'll see if I can replicate the error on Windows 10.

**Comment by theoldhat** [comment]
I was actually just working through this and it looks like the issue was mine.  I errantly had msgpack-numpy 0.4.4.1 installed and reverted to msgpack-numpy 0.4.3.2.  After reverting things appear to be in working order.
