### ISSUE TITLE
Mistaken tagging in portuguese

### ISSUE THREAD

**Issue by letrasprogramandoletras** [explosion/spaCy#2862]
Hi,
   Just check a simple sentence in portuguese as "Os alunos amam os livros" (The students love the books). The output for a token.pos_ is 'DET', 'SYM', 'VERB', 'DET', 'SYM', where SYM stands for symbol. I checked the tag_map.py file for portuguese and noted some 17 instances where SYM is misplaced, all of them should be NOUN.

Best,
Ricardo

**Comment by ines** [comment]
Merging this with #3052. We've now added a master thread for incorrect predictions and related reports – see the issue for more details.
