### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by yuyuhan0306** [explosion/spaCy#2868]
## How to reproduce the behaviour
I can get the result if I'm using `displacy.render(doc, style='ent', jupyter=True)` but once I change the style to 'dep', it gives me an error message.

`import spacy
import en_core_web_sm
from spacy import displacy

nlp_sm = spacy.load('en_core_web_sm')
doc = nlp_sm(u'this is a sentence.')
displacy.render(doc, style='dep', jupyter=True)`

TypeError                                 Traceback (most recent call last)
<ipython-input-48-83f172436f08> in <module>()
----> 1 displacy.render(doc, style='dep', jupyter=True)

C:\ProgramData\Anaconda3\lib\site-packages\spacy\displacy\__init__.py in render(docs, style, page, minify, jupyter, options, manual)
     37     renderer, converter = factories[style]
     38     renderer = renderer(options=options)
---> 39     parsed = [converter(doc, options) for doc in docs] if not manual else docs
     40     _html['parsed'] = renderer.render(parsed, page=page, minify=minify).strip()
     41     html = _html['parsed']

C:\ProgramData\Anaconda3\lib\site-packages\spacy\displacy\__init__.py in <listcomp>(.0)
     37     renderer, converter = factories[style]
     38     renderer = renderer(options=options)
---> 39     parsed = [converter(doc, options) for doc in docs] if not manual else docs
     40     _html['parsed'] = renderer.render(parsed, page=page, minify=minify).strip()
     41     html = _html['parsed']

C:\ProgramData\Anaconda3\lib\site-packages\spacy\displacy\__init__.py in parse_deps(orig_doc, options)
     87     RETURNS (dict): Generated dependency parse keyed by words and arcs.
     88     """
---> 89     doc = Doc(orig_doc.vocab).from_bytes(orig_doc.to_bytes())
     90     if not doc.is_parsed:
     91         user_warning(Warnings.W005)

doc.pyx in spacy.tokens.doc.Doc.to_bytes()

C:\ProgramData\Anaconda3\lib\site-packages\spacy\util.py in to_bytes(getters, exclude)
    484         if key not in exclude:
    485             serialized[key] = getter()
--> 486     return msgpack.dumps(serialized, use_bin_type=True, encoding='utf8')
    487 
    488 

C:\ProgramData\Anaconda3\lib\site-packages\msgpack_numpy.py in packb(o, **kwargs)
    194     """
    195 
--> 196     return Packer(**kwargs).pack(o)
    197 
    198 def unpack(stream, **kwargs):

TypeError: __init__() got an unexpected keyword argument 'encoding'

## Your Environment

* Operating System: Windows 7
* Python Version Used: 3.6
* spaCy Version Used: v2.0.12 (conda install)
* Environment Information:

**Comment by ines** [comment]
It sounds like you might be running an incompatible version of `msgpack`, or two conflicting versions. Could you run the following and post the result?

```bash
conda list | grep msgpack
```

**Comment by yuyuhan0306** [comment]
> It sounds like you might be running an incompatible version of `msgpack`, or two conflicting versions. Could you run the following and post the result?
> 
> ```shell
> conda list | grep msgpack
> ```

Hi @ines Thanks for your quick response. I checked my conda list
msgpack-numpy 0.4.4.1
msgpack-python 0.5.6

**Comment by little-bamboo** [comment]
Ran into the same issue, also had the same msgpack version as listed above.  

I was able to solve this problem by modifying the util.py spacy site-package source file.  

Removed the encoding parameter in the to_bytes method return statement, but not sure how this will affect other areas of the app.

python3.6/site-packages/spacy/util.py

```
def to_bytes(getters, exclude):
    serialized = OrderedDict()
    for key, getter in getters.items():
        if key not in exclude:
            serialized[key] = getter()
#    return msgpack.dumps(serialized, use_bin_type=True, encoding='utf8')
    return msgpack.dumps(serialized, use_bin_type=True)
```

**Comment by krsnaa** [comment]
Seeing the exact same issue as @yuyuhan0306. 
Is @little-bamboo 's post the accepted answer?

**Comment by ines** [comment]
Thanks for the updating – I'm merging this with #2810!
