### ISSUE TITLE
is_sent_start on first document token should be True instead of None

### ISSUE THREAD

**Issue by andifunke** [explosion/spaCy#2869]
Hey everyone,

From the documentation of **Token.is_sent_start**:
"... It also now returns None if the answer is unknown, and _fixes a quirk in the old logic that would always set the property to 0 for the first word of the document_."

The value of is_sent_start for the first token in a document is now always **None** instead of 0. Is this the intended behavior? I would argue that **True** would be more reasonable and consistent. At least it caused some issues to my code when I concatenated several documents and the is_sent_start flag on each first document word was missing.

## How to reproduce the behaviour
```
import spacy
nlp = spacy.load('en')
text = "This is the first sentence. This is the second sentence."
doc = nlp(text)
for token in doc:
    print(token.i, token.is_sent_start, token.text)
```

## Info about spaCy
* **spaCy version:** 2.0.16
* **Platform:** Linux-4.13.0-38-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.7.0
* **Models:** en, de

Kind regards,
Andreas

**Comment by lhami** [comment]
I agree that this seems inconsistent with the naming of the attribute. I had assumed I must've done something wrong somehow when I discovered this was the case and the first word in my document was not the start of a sentence. If this isn't going to be changed, could we at least get a reasoning for why it is the way it is?

**Comment by honnibal** [comment]
Sorry for the delay getting to this.

I think it should stay `None` before any sentence processing is applied, so that it's easy to check that nothing has predicted sentence boundaries. Otherwise we can't tell a situation where a model has tried to predict sentence starts and only found the first word of the sentence.
