### ISSUE TITLE
begin training with GPU takes several minutes and allocates 1.5GB of GPU memory

### ISSUE THREAD

**Issue by veonua** [explosion/spaCy#2877]
## How to reproduce the behaviour
```
import spacy

print(spacy.prefer_gpu())
nlp = spacy.blank("xx")

if 'ner' not in nlp.pipe_names:
    ner = nlp.create_pipe('ner')
    nlp.add_pipe(ner, last=True)
else:
    ner = nlp.get_pipe('ner')

other_pipes = [pipe for pipe in nlp.pipe_names if pipe != 'ner']

with nlp.disable_pipes(*other_pipes):  # only train NER
    optimizer = nlp.begin_training()
```

## Your Environment
Ubuntu 18
Python 3.5
Spacy 2.0.16

cupy==5.0.0
thinc==6.12.0
thinc-gpu-ops==0.0.3

**Comment by honnibal** [comment]
I didn't think it would allocate so much with a blank model like that. Thanks, I'm not sure what this is due to. A few minutes also seems excessive.

**Comment by veonua** [comment]
this happens only with blank models with NER added to pipeline with GPU
training, loading model starts fine in the same time. I have second PC
without GPU and learning is faster there.

 Is there way to force CPU for Spacy? I would set a benchmark on the same PC

**Comment by honnibal** [comment]
In recent versions it shouldn't automatically engage the GPU, without you asking. There are two functions you can call to allocate on GPU: `spacy.prefer_gpu()` and `spacy.require_gpu()`. Without calling these, it should just use the CPU.
