### ISSUE TITLE
Code example train_new_entity_type.py doesn't seem to work as expected.

### ISSUE THREAD

**Issue by matthewbhall** [explosion/spaCy#2878]
## How to reproduce the behaviour
On a fresh isntallation of spacey, the first things I did were start running the code examples. One example, https://github.com/explosion/spacy/blob/master/examples/training/train_ner.py, doesn't seem to work as expected. The newly trained entity, horse -> ANIMAL, doesn't get recognized. Here is the script output:

C:\python36\lib\importlib\_bootstrap.py:219: RuntimeWarning: cymem.cymem.Pool size changed, may indicate binary incompatibility. Expected 24 from C header, got 32 from PyObject
  return f(*args, **kwds)
C:\python36\lib\importlib\_bootstrap.py:219: RuntimeWarning: cymem.cymem.Address size changed, may indicate binary incompatibility. Expected 12 from C header, got 20 from PyObject
  return f(*args, **kwds)
C:\python36\lib\importlib\_bootstrap.py:219: RuntimeWarning: cymem.cymem.Pool size changed, may indicate binary incompatibility. Expected 24 from C header, got 32 from PyObject
  return f(*args, **kwds)
C:\python36\lib\importlib\_bootstrap.py:219: RuntimeWarning: cymem.cymem.Address size changed, may indicate binary incompatibility. Expected 12 from C header, got 20 from PyObject
  return f(*args, **kwds)
Created blank 'en' model
Warning: Unnamed vectors -- this won't allow multiple vectors models to be loaded. (Shape: (0, 0))
Losses {'ner': 3.352960731417763}
Losses {'ner': 2.1387313530291516}
Losses {'ner': 1.4231954120514807}
Losses {'ner': 0.9599864604625694}
Losses {'ner': 1.5879636425572516}
Losses {'ner': 0.00012759523063688653}
Losses {'ner': 0.10524090359196434}
Losses {'ner': 0.05637522462945867}
Losses {'ner': 0.001495454859912165}
Losses {'ner': 8.717183293751417e-08}
Entities in 'Do you like horses?'

Is this a data set issue within the example?

## Your Environment
* **spaCy version:** 2.0.16
* **Platform:** Windows-10-10.0.17763-SP0
* **Python version:** 3.6.3

**Comment by thiagoananias** [comment]
Hello...I was going to put this question as well...worse than that...i used the same code but tested some other texts:

Entities in 'Do you like horses?' --> Sometimes works, sometimes don't
  --   ANIMAL horses

Those that are not 'Horses' always return as  Animals...

Entities in 'Vikings'
  --   ANIMAL Vikings
Entities in 'Ronaldo'
  --   ANIMAL Ronaldo
Entities in 'I want to watch Pequenos Confeiteiros'
  --   ANIMAL Pequenos
  --   ANIMAL Confeiteiros

I may as well making a beginner assumption but what do i have to do to this example recognize only Horse's as "animal"? Do i need to train it more samples? How to avoid the false positives?

Thanks
