### ISSUE TITLE
Token's property `is_currency` partially working

### ISSUE THREAD

**Issue by MaximeChurinUnchartech** [explosion/spaCy#2879]
Follow up on issue #2491

## How to reproduce the bug
I'm trying to use the token's property `is_currency` . As previously mention in the past issue,  the `is_currency` attribute was added after the current models were trained. But now, it seems they are partially added as shown in the table below (example : `€` but not `$` in the `en_core_web_sm` model).
```python
from spacy.lang.en import EnglishDefaults
from spacy.symbols import IS_CURRENCY
from spacy.lang.en import English
import pandas as pd

is_currency_original = EnglishDefaults.lex_attr_getters[IS_CURRENCY]
en_core_web_sm = spacy.load('en_core_web_sm')
en_core_web_lg = spacy.load('en_core_web_lg')
en_old = English()

data = []
text = "$ €"
for token in en_core_web_sm(text):
    data.append(['en_core_web_sm', token.text, token.tag_, token.is_currency, is_currency_original(token.text), unicodedata.category(token.text) == 'Sc'])
for token in en_core_web_lg(text):
    data.append(['en_core_web_lg', token.text, token.tag_, token.is_currency, is_currency_original(token.text), unicodedata.category(token.text) == 'Sc'])
for token in en_old(text):
    data.append(['English()', token.text, token.tag_, token.is_currency, is_currency_original(token.text), unicodedata.category(token.text) == 'Sc'])
pd.DataFrame(data, columns = ["model_name", "text", "tag_", "is_currency", "is_currency_original", "unicodedata"])
```

model_name | text | tag_ | is_currency | is_currency_original | unicodedata
-- | -- | -- | -- | -- | --
en_core_web_sm | $ | $ | False | True | True
en_core_web_sm | € | . | True | True | True
en_core_web_lg | $ | $ | False | True | True
en_core_web_lg | € | CD | False | True | True
English() | $ |   | True | True | True
English() | € |   | True | True | True

So at the moment only the `English()` is working correctly. Is it the correct desired behavior ? What about the `tag_` attribute for the two core models, not referencing then as a currency ?
Do you have more information on the next model release to take into account this new attribute ?

## Your Environment (Info about spaCy)
* **spaCy version:** 2.0.12
* **Platform:** Linux-4.15.0-36-generic-x86_64-with-debian-buster-sid
* **Python version:** 3.6.6
* **Models:** en, en_core_web_lg, en_core_web_sm

**Comment by honnibal** [comment]
The `spacy-nightly` models should have this fixed already.

**Comment by honnibal** [comment]
You're right that the information is missing in the cached lexemes, which causes the attribute to be incorrect for any lexemes that are loaded from the vocab off disk. This causes the issue you're seeing.

If you try the `spacy-nightly` models, you should find those models have updated data for these attributes. I'd like to rethink the way some of these caches work, as I'm not really satisfied by these problems.
