### ISSUE TITLE
Deploying to Azure Web Service fails with: en_core_web_sm

### ISSUE THREAD

**Issue by EdgardoValdez** [explosion/spaCy#2892]
## How to reproduce the problem
Follow this link: https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-python and using own python code as application.py containing this line: nlp_date = spacy.load('en_core_web_sm') 
Although it works locally in my computer (http://localhost:5000/), it fails when deployed to Azure with the following error:
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

Similar error occurs when executing pip freeze > requirements.txt, since the line -> en-core-web-sm==2.0.0 appears in the list and app cannot be deployed:
remote: Collecting en-core-web-sm==1.6.0 (from -r requirements.txt (line 136))        
remote:   Could not find a version that satisfies the requirement en-core-web-sm==1.6.0 (from -r requirements.txt (line 136)) (from versions: )        
remote: No matching distribution found for en-core-web-sm==1.6.0 (from -r requirements.txt (line 136))
      
```bash
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```

## Info about spaCy
* **spaCy version:** 2.0.16
* **Platform:** Windows-10-10.0.17763-SP0
* **Python version:** 3.7.1
* **Models:** en

[en_core_web_sm_IssueAzureAppServLog.txt](https://github.com/explosion/spaCy/files/2537281/en_core_web_sm_IssueAzureAppServLog.txt)

**Comment by ines** [comment]
If you want the model to be installed when spaCy is installed, you also need to provide the full URL to the model package in your `requirements.txt`. Otherwise, pip will just check its public registry, and while `en_core_web_sm` is a Python package, it's not a package uploaded to PyPi (which the models aren't really suited for, since they're mostly binary data and potentially quite large).

Here's an example of a `requirements.txt` listing spaCy models:

```
spacy>=2.0.10,<2.1.0

https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz#egg=en_core_web_sm==2.0.0
https://github.com/explosion/spacy-models/releases/download/en_core_web_md-2.0.0/en_core_web_md-2.0.0.tar.gz#egg=en_core_web_md==2.0.0
https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-2.0.0/en_core_web_lg-2.0.0.tar.gz#egg=en_core_web_lg==2.0.0
https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-2.0.0/de_core_news_sm-2.0.0.tar.gz#egg=de_core_news_sm==2.0.0
https://github.com/explosion/spacy-models/releases/download/es_core_news_sm-2.0.0/es_core_news_sm-2.0.0.tar.gz#egg=es_core_news_sm==2.0.0
https://github.com/explosion/spacy-models/releases/download/pt_core_news_sm-2.0.0/pt_core_news_sm-2.0.0.tar.gz#egg=pt_core_news_sm==2.0.0
https://github.com/explosion/spacy-models/releases/download/fr_core_news_sm-2.0.0/fr_core_news_sm-2.0.0.tar.gz#egg=fr_core_news_sm==2.0.0
https://github.com/explosion/spacy-models/releases/download/it_core_news_sm-2.0.0/it_core_news_sm-2.0.0.tar.gz#egg=it_core_news_sm==2.0.0
https://github.com/explosion/spacy-models/releases/download/nl_core_news_sm-2.0.0/nl_core_news_sm-2.0.0.tar.gz#egg=nl_core_news_sm==2.0.0
```

See here for more details: https://spacy.io/usage/models#models-download
