### ISSUE TITLE
spacy.load keyword argument vectors=False doesn't work > 2.0

### ISSUE THREAD

**Issue by suhassumukhv** [explosion/spaCy#2896]
## How to reproduce the behaviour

```
nlp = spacy.load("en_core_web_lg") 
```
takes the same amount of memory as
```
nlp = spacy.load("en_core_web_lg", vectors=False)
```
So, the vectors are still being loaded into memory. I want to deselect the vectors from being loaded, which consume a lot of space. I tried using `"en_core_web_sm"`, but the results are significantly different from the `"en_core_web_lg"` model. 
Following the issue on https://github.com/explosion/spaCy/issues/400 doesn't help. It seems to only work for <2.0

## Your Environment

* Operating System: Ubuntu
* Python Version Used: 2.7
* spaCy Version Used: 2.0.16
* Environment Information:

**Comment by honnibal** [comment]
@suhassumukhv You can set `nlp.vocab.vectors = None` after loading as a quick fix, but I suspect this won't do what you want.

Deleting the vectors from the `en_core_web_lg` model will invalidate all the statistical models, as these models are trained to expect input from the static vectors. You might want to try the `en_core_web_md` model, as a balance between the improved accuracy from the vectors, but without loading so much data.
