### ISSUE TITLE
SpaCy suddenly cannot find  strings.json file

### ISSUE THREAD

**Issue by Marry90** [explosion/spaCy#2902]
## How to reproduce the behaviour

I developed a pieces of code using spaCy. Everything was working for a few months, however, I suddenly faced the following error a day ago. 

> FileNotFoundError: [Errno 2] No such file or directory: '/Users/local/anaconda3/lib/python3.6/site-packages/spacy/data/en/en_core_web_sm-2.0.0/vocab/strings.json'

> ---------------------------------------------------------------------------
> FileNotFoundError                         Traceback (most recent call last)
> <ipython-input-2-81e497cfb431> in <module>()
> 
>  
> ---> 22 nlp = spacy.load('en')
> 
> ~/anaconda3/lib/python3.6/site-packages/spacy/__init__.py in load(name, **overrides)
>      19     if depr_path not in (True, False, None):
>      20         deprecation_warning(Warnings.W001.format(path=depr_path))
> ---> 21     return util.load_model(name, **overrides)
>      22 
>      23 
> ~/anaconda3/lib/python3.6/site-packages/spacy/util.py in load_model(name, **overrides)
>     110     if isinstance(name, basestring_):  # in data dir / shortcut
>     111         if name in set([d.name for d in data_path.iterdir()]):
> --> 112             return load_model_from_link(name, **overrides)
>     113         if is_package(name):  # installed as package
>     114             return load_model_from_package(name, **overrides)
> ~/anaconda3/lib/python3.6/site-packages/spacy/util.py in load_model_from_link(name, **overrides)
>     127     except AttributeError:
>     128         raise IOError(Errors.E051.format(name=name))
> --> 129     return cls.load(**overrides)
>     130 
>     131 
> ~/anaconda3/lib/python3.6/site-packages/spacy/data/en/__init__.py in load(**overrides)
>      10 
>      11 def load(**overrides):
> ---> 12     return load_model_from_init_py(__file__, **overrides)
> ~/anaconda3/lib/python3.6/site-packages/spacy/util.py in load_model_from_init_py(init_file, **overrides)
>     171     if not model_path.exists():
>     172         raise IOError(Errors.E052.format(path=path2str(data_path)))
> --> 173     return load_model_from_path(data_path, meta, **overrides)
>     174 
>     175 
> ~/anaconda3/lib/python3.6/site-packages/spacy/util.py in load_model_from_path(model_path, meta, **overrides)
>     154             component = nlp.create_pipe(name, config=config)
>     155             nlp.add_pipe(component, name=name)
> --> 156     return nlp.from_disk(model_path)
>     157 
>     158 
> ~/anaconda3/lib/python3.6/site-packages/spacy/language.py in from_disk(self, path, disable)
>     645         if not (path / 'vocab').exists():
>     646             exclude['vocab'] = True
> --> 647         util.from_disk(path, deserializers, exclude)
>     648         self._path = path
>     649         return self
> ~/anaconda3/lib/python3.6/site-packages/spacy/util.py in from_disk(path, readers, exclude)
>     509     for key, reader in readers.items():
>     510         if key not in exclude:
> --> 511             reader(path / key)
>     512     return path
>     513 
> ~/anaconda3/lib/python3.6/site-packages/spacy/language.py in <lambda>(p)
>     633             ('meta.json', lambda p: self.meta.update(util.read_json(p))),
>     634             ('vocab', lambda p: (
> --> 635                 self.vocab.from_disk(p) and _fix_pretrained_vectors_name(self))),
>     636             ('tokenizer', lambda p: self.tokenizer.from_disk(p, vocab=False)),
>     637         ))
> vocab.pyx in spacy.vocab.Vocab.from_disk()
> strings.pyx in spacy.strings.StringStore.from_disk()
> ~/anaconda3/lib/python3.6/pathlib.py in open(self, mode, buffering, encoding, errors, newline)
>    1179             self._raise_closed()
>    1180         return io.open(str(self), mode, buffering, encoding, errors, newline,
> -> 1181                        opener=self._opener)
>    1182 
>    1183     def read_bytes(self):
> ~/anaconda3/lib/python3.6/pathlib.py in _opener(self, name, flags, mode)
>    1033     def _opener(self, name, flags, mode=0o666):
>    1034         # A stub for the opener argument to built-in open()
> -> 1035         return self._accessor.open(self, flags, mode)
>    1036 
>    1037     def _raw_open(self, flags, mode=0o777):
> ~/anaconda3/lib/python3.6/pathlib.py in wrapped(pathobj, *args)
>     385         @functools.wraps(strfunc)
>     386         def wrapped(pathobj, *args):
> --> 387             return strfunc(str(pathobj), *args)
>     388         return staticmethod(wrapped)
>     389

I tried to fix this error by re-linking the model within spaCy's package  as it recommended [here](https://github.com/explosion/spaCy/issues/2406) and [here.](https://github.com/explosion/spaCy/issues/924)  However, it is still not working. Any ideas to fix this issue plz? 

  
    TYPE        NAME                  MODEL                 VERSION                                   
    package     en-core-web-sm        en_core_web_sm        2.0.0    ✔      
    link        en                    en_core_web_sm        2.0.0    ✔      
    link        my_model              en_core_web_sm        2.0.0    ✔      

## Your Environment
    Info about spaCy
    spaCy version      2.0.16         
    Platform           Darwin-16.7.0-x86_64-i386-64bit
    Python version     3.6.5          
    Models             en, my_model

**Comment by ines** [comment]
Hmm, maybe your environment got corrupted somehow? Have you tried uninstalling and then reinstalling the model again?

```bash
pip uninstall en_core_web_sm
python -m spacy download en
```

**Comment by Marry90** [comment]
Thank you ines for your reply. Yes I did many times but I still have the same issue =(  

> MacBook-Air:~ local$ **sudo -H pip uninstall en_core_web_sm**
> Uninstalling en-core-web-sm-2.0.0:
>   Would remove:
>     /Users/local/anaconda3/lib/python3.6/site-packages/en_core_web_sm-2.0.0-py3.6.egg-info
>     /Users/local/anaconda3/lib/python3.6/site-packages/en_core_web_sm/*
> Proceed (y/n)? y
>   Successfully uninstalled en-core-web-sm-2.0.0

> MacBook-Air:~ local$  **sudo python -m spacy download en**
> Collecting en_core_web_sm==2.0.0 from https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz#egg=en_core_web_sm==2.0.0
>   Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz (37.4MB)
>     100% |████████████████████████████████| 37.4MB 5.1MB/s 
> Installing collected packages: en-core-web-sm
>   Running setup.py install for en-core-web-sm ... done
> Successfully installed en-core-web-sm-2.0.0
> 
>     Linking successful
>     /Users/manalbinkhonain/anaconda3/lib/python3.6/site-packages/en_core_web_sm
>     -->
>     /Users/manalbinkhonain/anaconda3/lib/python3.6/site-packages/spacy/data/en
> 
>     You can now load the model via spacy.load('en')

> MacBook-Air:~ local$ **$ sudo -H python -m spacy link en_core_web_sm en --force**
> 
>     Linking successful
>     /Users/manalbinkhonain/anaconda3/lib/python3.6/site-packages/en_core_web_sm
>     -->
>     /Users/manalbinkhonain/anaconda3/lib/python3.6/site-packages/spacy/data/en
> 
>     You can now load the model via spacy.load('en')

**Comment by ines** [comment]
Does the same error happen if you import the model as a package?

```python
import en_core_web_sm
nlp = en_core_web_sm.load()
```

Alternatively, maybe there's still some weird cached leftovers of the package in your environment? Maybe try removing all `en_core_web_sm` folders in your `site-packages` directory by hand, and also make sure that this symlink / directory is deleted:

```
/Users/local/anaconda3/lib/python3.6/site-packages/spacy/data/en
```

**Comment by Marry90** [comment]
yes, I faced the same error by importing the model.  

I upgraded spaCy using " sudo -H  pip install -U spacy " +  blocked  antivirus App (Avast)  and re-ran the three commands mentioned above. It finally works =) 

Many thanks Ines
