### ISSUE TITLE
Docs for v1 and opening saved models

### ISSUE THREAD

**Issue by mhigginslp** [explosion/spaCy#2903]
I am considering downgrading to v1 because of the great speed up but I'm having some trouble loading my trained models.  I have successfully saved and loaded a ner but am having trouble understanding how to integrate textcat ...
Can I use the textcat component saved model from v2+ ? 
Or should I retrain a textcat model from v1?  Can you point me to sample code on how to train, save and load textcat in v1.  

More generally I am having trouble finding the docs on v1, where does it live?

**Comment by honnibal** [comment]
https://legacy.spacy.io/docs/

I think you probably won't be able to use the textcat though, it requires the neural net stuff.
