### ISSUE TITLE
File "cymem.pxd", line 1, in init preshed.maps ValueError: cymem.cymem.Pool has the wrong size, try recompiling. Expected 64, got 48

### ISSUE THREAD

**Issue by Hannabrahman** [explosion/spaCy#2904]
I have installed spacy using pip install before (I could import spacy). But when I tried to download spacy English module I got the following error:
```
No module named spacy.__main__; 'spacy' is a package and cannot be directly executed
```
I then used " conda install spacy -c conda-forge" according to one of the threads to address the issue and now I am getting a new error when importing spacy:
```
  File "cymem.pxd", line 1, in init preshed.maps
ValueError: cymem.cymem.Pool has the wrong size, try recompiling. Expected 64, got 48
```
Anyone knows what's going on?

## Your Environment

* Operating System: Unix
* Python Version Used: 3.6
* spaCy Version Used: 2.0.13 after installing via conda
* Environment Information:

**Comment by ines** [comment]
It's likely that you've ended up in a weird system state here. The first error you saw indicates that spaCy either didn't install properly or that you – more likely – had a very old version of spaCy installed that didn't yet have the CLI. When you installed the newer version over it, you possibly still had old compiled artifacts on your system which then causes this mismatch.

It's not the most satisfying answer, but what usually helps is to uninstall spaCy and all its dependencies (`thinc`, `cymem`, `preshed`, `murmurhash`), and then install spaCy again from scratch.

**Comment by calebdel** [comment]
It looks like sense2vec requires an older version of ```cymen``` then spaCy. Installing sense2Vec broke spaCy for me. https://github.com/explosion/sense2vec/issues/65

**Comment by ines** [comment]
This makes more sense – merging this with the issue on `sense2vec`. Since `sense2vec` doesn't actually depend in spaCy, it also doesn't define a compatible version range of spaCy, causing this mismatch. Updating the version and recompiling sense2vec with the new `cymem` should work, though.
