### ISSUE TITLE
Parallel nn inference in spacy?

### ISSUE THREAD

**Issue by gonglinyuan** [explosion/spaCy#2908]
I use spacy for sentence segmentation in a unix pipeline. I loaded the "en" model and followed the instructions on https://spacy.io/usage/linguistic-features#section-sbd. Here is my code:

    nlp = spacy.load('en')
    for line in sys.stdin:
        for sent in nlp(line).sents:
            sys.stdout.write(str(sent) + '\n')

On computer A with 2 E5-2699 v3, spacy worked pretty well and used all 36 CPU cores. The inference is quite fast. However, on another computer (let's call it computer B) with the E5-2680 v2 CPU, spacy only used 2 CPU cores and the inference is very slow. I want to know why this happens?

This is the conda environment of computer A:

    Linux ubuntu 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

    appdirs                   1.4.3            py37h28b3542_0    defaults
    asn1crypto                0.24.0                   py37_0    defaults
    attrs                     18.2.0           py37h28b3542_0    defaults
    automat                   0.7.0                    py37_0    defaults
    backcall                  0.1.0                    py37_0    defaults
    blas                      1.0                         mkl    defaults
    bleach                    3.0.2                    py37_0    defaults
    ca-certificates           2018.03.07                    0    defaults
    certifi                   2018.10.15               py37_0    defaults
    cffi                      1.11.5           py37he75722e_1    defaults
    chardet                   3.0.4                    py37_1    defaults
    constantly                15.1.0           py37h28b3542_0    defaults
    cryptography              2.3.1            py37hc365091_0    defaults
    cuda90                    1.0                  h6433d27_0    pytorch
    cudatoolkit               9.0                  h13b8566_0    defaults
    cudnn                     7.1.2                 cuda9.0_0    defaults
    cupy-cuda90               5.0.0                     <pip>
    cycler                    0.10.0                   py37_0    defaults
    cymem                     2.0.2            py37hfd86e86_0    defaults
    cytoolz                   0.9.0.1          py37h14c3975_1    defaults
    dataclasses               0.6                        py_0    fastai
    dbus                      1.13.2               h714fa37_1    defaults
    decorator                 4.3.0                    py37_0    defaults
    dill                      0.2.8.2                  py37_0    defaults
    en-core-web-sm            2.0.0                     <pip>
    entrypoints               0.2.3                    py37_2    defaults
    expat                     2.2.6                he6710b0_0    defaults
    fairseq                   0.6.0                     <pip>
    fastai                    1.0.3                      py_1    fastai
    fastprogress              0.1.9                      py_0    fastai
    fastrlock                 0.4                       <pip>
    fontconfig                2.13.0               h9420a91_0    defaults
    freetype                  2.9.1                h8a8886c_1    defaults
    glib                      2.56.2               hd408876_0    defaults
    gmp                       6.1.2                h6c8ec71_1    defaults
    gst-plugins-base          1.14.0               hbbd80ab_1    defaults
    gstreamer                 1.14.0               hb453b48_1    defaults
    html5lib                  1.0.1                    py37_0    defaults
    hyperlink                 18.0.0                   py37_0    defaults
    icu                       58.2                 h9c2bf20_1    defaults
    idna                      2.7                      py37_0    defaults
    incremental               17.5.0                   py37_0    defaults
    intel-openmp              2019.0                      118    defaults
    ipykernel                 5.1.0            py37h39e3cac_0    defaults
    ipython                   7.0.1            py37h39e3cac_0    defaults
    ipython_genutils          0.2.0                    py37_0    defaults
    ipywidgets                7.4.2                    py37_0    defaults
    jedi                      0.13.1                   py37_0    defaults
    jinja2                    2.10                     py37_0    defaults
    jpeg                      9b                   h024ee3a_2    defaults
    jsonschema                2.6.0                    py37_0    defaults
    jupyter                   1.0.0                    py37_7    defaults
    jupyter_client            5.2.3                    py37_0    defaults
    jupyter_console           6.0.0                    py37_0    defaults
    jupyter_core              4.4.0                    py37_0    defaults
    jupyterlab                0.35.2                   py37_0    defaults
    jupyterlab_launcher       0.13.1                   py37_0    defaults
    jupyterlab_server         0.2.0                    py37_0    defaults
    kiwisolver                1.0.1            py37hf484d3e_0    defaults
    libedit                   3.1.20170329         h6b74fdf_2    defaults
    libffi                    3.2.1                hd88cf55_4    defaults
    libgcc-ng                 8.2.0                hdf63c60_1    defaults
    libgfortran-ng            7.3.0                hdf63c60_0    defaults
    libpng                    1.6.35               hbc83047_0    defaults
    libsodium                 1.0.16               h1bed415_0    defaults
    libstdcxx-ng              8.2.0                hdf63c60_1    defaults
    libtiff                   4.0.9                he85c1e1_2    defaults
    libuuid                   1.0.3                h1bed415_2    defaults
    libxcb                    1.13                 h1bed415_1    defaults
    libxml2                   2.9.8                h26e45fe_1    defaults
    lightgbm                  2.2.0                     <pip>
    llvmlite                  0.25.0           py37hd408876_0    defaults
    markupsafe                1.0              py37h14c3975_1    defaults
    matplotlib                3.0.1            py37h5429711_0    defaults
    mistune                   0.8.4            py37h7b6447c_0    defaults
    mkl                       2019.0                      118    defaults
    mkl_fft                   1.0.6            py37h7dd41cf_0    defaults
    mkl_random                1.0.1            py37h4414c95_1    defaults
    msgpack-numpy             0.4.3.2                  py37_0    defaults
    msgpack-python            0.5.6            py37h6bb024c_1    defaults
    murmurhash                1.0.1            py37he6710b0_0    defaults
    nbconvert                 5.3.1                    py37_0    defaults
    nbformat                  4.4.0                    py37_0    defaults
    nccl                      1.3.5                 cuda9.0_0    defaults
    ncurses                   6.1                  hf484d3e_0    defaults
    ninja                     1.8.2            py37h6bb024c_1    defaults
    notebook                  5.7.0                    py37_0    defaults
    numba                     0.40.0           py37h962f231_0    defaults
    numpy                     1.15.3           py37h1d66e8a_0    defaults
    numpy-base                1.15.3           py37h81de0dd_0    defaults
    olefile                   0.46                     py37_0    defaults
    openssl                   1.0.2p               h14c3975_0    defaults
    pandas                    0.23.4           py37h04863e7_0    defaults
    pandoc                    2.2.3.2                       0    defaults
    pandocfilters             1.4.2                    py37_1    defaults
    parso                     0.3.1                    py37_0    defaults
    patsy                     0.5.0                    py37_0    defaults
    pcre                      8.42                 h439df22_0    defaults
    pexpect                   4.6.0                    py37_0    defaults
    pickleshare               0.7.5                    py37_0    defaults
    pillow                    5.3.0            py37h34e0f95_0    defaults
    pip                       10.0.1                   py37_0    defaults
    plac                      0.9.6                    py37_0    defaults
    preshed                   2.0.1            py37he6710b0_0    defaults
    prometheus_client         0.4.2                    py37_0    defaults
    prompt_toolkit            2.0.6                    py37_0    defaults
    ptyprocess                0.6.0                    py37_0    defaults
    pyasn1                    0.4.4            py37h28b3542_0    defaults
    pyasn1-modules            0.2.2                    py37_0    defaults
    pycparser                 2.19                     py37_0    defaults
    pygal                     2.4.0                     <pip>
    pygments                  2.2.0                    py37_0    defaults
    pyhamcrest                1.9.0                    py37_2    defaults
    pyopenssl                 18.0.0                   py37_0    defaults
    pyparsing                 2.2.2                    py37_0    defaults
    pyqt                      5.9.2            py37h05f1152_2    defaults
    pysocks                   1.6.8                    py37_0    defaults
    python                    3.7.0                h6e4f718_3    defaults
    python-dateutil           2.7.3                    py37_0    defaults
    pytorch-nightly           1.0.0.dev20181105 py3.7_cuda9.0.176_cudnn7.1.2_0    pytorch
    pytz                      2018.5                   py37_0    defaults
    pyzmq                     17.1.2           py37h14c3975_0    defaults
    qt                        5.9.6                h8703b6f_2    defaults
    qtconsole                 4.4.2                    py37_0    defaults
    readline                  7.0                  h7b6447c_5    defaults
    regex                     2018.1.10                 <pip>
    regex                     2018.08.29       py37h7b6447c_0    defaults
    requests                  2.19.1                   py37_0    defaults
    scikit-learn              0.20.0           py37h4989274_1    defaults
    scipy                     1.1.0            py37hfa4b5c9_1    defaults
    seaborn                   0.9.0                    py37_0    defaults
    send2trash                1.5.0                    py37_0    defaults
    service_identity          17.0.0           py37h28b3542_0    defaults
    setuptools                40.4.3                   py37_0    defaults
    simplegeneric             0.8.1                    py37_2    defaults
    sip                       4.19.8           py37hf484d3e_0    defaults
    six                       1.11.0                   py37_1    defaults
    spacy                     2.0.16           py37h962f231_0    defaults
    sqlite                    3.25.2               h7b6447c_0    defaults
    statsmodels               0.9.0            py37h035aef0_0    defaults
    termcolor                 1.1.0                    py37_1    defaults
    terminado                 0.8.1                    py37_1    defaults
    testpath                  0.4.2                    py37_0    defaults
    thinc                     6.12.0           py37h4989274_0    defaults
    tk                        8.6.8                hbc83047_0    defaults
    toolz                     0.9.0                    py37_0    defaults
    torchvision               0.2.1                      py_0    fastai
    tornado                   5.1.1            py37h7b6447c_0    defaults
    tqdm                      4.26.0           py37h28b3542_0    defaults
    traitlets                 4.3.2                    py37_0    defaults
    twisted                   18.9.0           py37h7b6447c_0    defaults
    typing                    3.6.4                    py37_0    defaults
    ujson                     1.35             py37h14c3975_0    defaults
    urllib3                   1.23                     py37_0    defaults
    wcwidth                   0.1.7                    py37_0    defaults
    webencodings              0.5.1                    py37_1    defaults
    wheel                     0.32.2                   py37_0    defaults
    widgetsnbextension        3.4.2                    py37_0    defaults
    wrapt                     1.10.11          py37h14c3975_2    defaults
    xx-ent-wiki-sm            2.0.0                     <pip>
    xz                        5.2.4                h14c3975_4    defaults
    zeromq                    4.2.5                hf484d3e_1    defaults
    zlib                      1.2.11               ha838bed_2    defaults
    zope                      1.0                      py37_1    defaults
    zope.interface            4.5.0            py37h14c3975_0    defaults

And here is the conda environment of computer B:

    Linux gcrgpu1149 4.13.9-coreos #1 SMP Thu Oct 26 03:21:00 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
    asn1crypto                0.24.0                   py37_0
    backcall                  0.1.0                    py37_0
    blas                      1.0                         mkl
    bleach                    3.0.2                    py37_0
    blessings                 1.7                       <pip>
    ca-certificates           2018.03.07                    0
    certifi                   2018.10.15               py37_0
    cffi                      1.11.5           py37he75722e_1
    chardet                   3.0.4                    py37_1
    cryptography              2.3.1            py37hc365091_0
    cuda90                    1.0                  h6433d27_0    pytorch
    cycler                    0.10.0                   py37_0
    cymem                     2.0.2            py37hfd86e86_0
    cython                    0.29             py37he6710b0_0
    cytoolz                   0.9.0.1          py37h14c3975_1
    dbus                      1.13.2               h714fa37_1
    decorator                 4.3.0                    py37_0
    dill                      0.2.8.2                  py37_0
    en-core-web-sm            2.0.0                     <pip>
    entrypoints               0.2.3                    py37_2
    expat                     2.2.6                he6710b0_0
    fontconfig                2.13.0               h9420a91_0
    freetype                  2.9.1                h8a8886c_1
    glib                      2.56.2               hd408876_0
    gmp                       6.1.2                h6c8ec71_1
    gpustat                   0.5.0                     <pip>
    gst-plugins-base          1.14.0               hbbd80ab_1
    gstreamer                 1.14.0               hb453b48_1
    icu                       58.2                 h9c2bf20_1
    idna                      2.7                      py37_0
    intel-openmp              2019.0                      118
    ipykernel                 5.1.0            py37h39e3cac_0
    ipython                   7.0.1            py37h39e3cac_0
    ipython_genutils          0.2.0                    py37_0
    ipywidgets                7.4.2                    py37_0
    jedi                      0.13.1                   py37_0
    jinja2                    2.10                     py37_0
    jpeg                      9b                   h024ee3a_2
    jsonschema                2.6.0                    py37_0
    jupyter                   1.0.0                    py37_7
    jupyter_client            5.2.3                    py37_0
    jupyter_console           6.0.0                    py37_0
    jupyter_core              4.4.0                    py37_0
    jupyterlab                0.35.2                   py37_0
    jupyterlab_server         0.2.0                    py37_0
    kiwisolver                1.0.1            py37hf484d3e_0
    libedit                   3.1.20170329         h6b74fdf_2
    libffi                    3.2.1                hd88cf55_4
    libgcc-ng                 8.2.0                hdf63c60_1
    libgfortran-ng            7.3.0                hdf63c60_0
    libpng                    1.6.35               hbc83047_0
    libsodium                 1.0.16               h1bed415_0
    libstdcxx-ng              8.2.0                hdf63c60_1
    libtiff                   4.0.9                he85c1e1_2
    libuuid                   1.0.3                h1bed415_2
    libxcb                    1.13                 h1bed415_1
    libxml2                   2.9.8                h26e45fe_1
    llvmlite                  0.25.0           py37hd408876_0
    markupsafe                1.0              py37h14c3975_1
    matplotlib                3.0.0            py37h5429711_0
    mistune                   0.8.4            py37h7b6447c_0
    mkl                       2019.0                      118
    mkl_fft                   1.0.6            py37h7dd41cf_0
    mkl_random                1.0.1            py37h4414c95_1
    msgpack-numpy             0.4.3.2                  py37_0
    msgpack-python            0.5.6            py37h6bb024c_1
    murmurhash                1.0.1            py37he6710b0_0
    nbconvert                 5.3.1                    py37_0
    nbformat                  4.4.0                    py37_0
    ncurses                   6.1                  hf484d3e_0
    ninja                     1.8.2            py37h6bb024c_1
    notebook                  5.7.0                    py37_0
    numba                     0.40.0           py37h962f231_0
    numpy                     1.15.2           py37h1d66e8a_1
    numpy-base                1.15.2           py37h81de0dd_1
    nvidia-ml-py3             7.352.0                   <pip>
    olefile                   0.46                     py37_0
    openssl                   1.0.2p               h14c3975_0
    pandas                    0.23.4           py37h04863e7_0
    pandoc                    2.2.3.2                       0
    pandocfilters             1.4.2                    py37_1
    parso                     0.3.1                    py37_0
    patsy                     0.5.0                    py37_0
    pcre                      8.42                 h439df22_0
    pexpect                   4.6.0                    py37_0
    pickleshare               0.7.5                    py37_0
    pillow                    5.3.0            py37h34e0f95_0
    pip                       10.0.1                   py37_0
    plac                      0.9.6                    py37_0
    preshed                   2.0.1            py37he6710b0_0
    prometheus_client         0.4.2                    py37_0
    prompt_toolkit            2.0.6                    py37_0
    psutil                    5.4.7                     <pip>
    ptyprocess                0.6.0                    py37_0
    pybind11                  2.2.4            py37hfd86e86_0
    pycparser                 2.19                     py37_0
    pygments                  2.2.0                    py37_0
    pyopenssl                 18.0.0                   py37_0
    pyparsing                 2.2.2                    py37_0
    pyqt                      5.9.2            py37h05f1152_2
    pysocks                   1.6.8                    py37_0
    python                    3.7.0                h6e4f718_3
    python-dateutil           2.7.3                    py37_0
    pytorch                   0.4.1           py37_py36_py35_py27__9.0.176_7.1.2_2    pytorch
    pytz                      2018.5                   py37_0
    pyyaml                    3.13             py37h14c3975_0
    pyzmq                     17.1.2           py37h14c3975_0
    qt                        5.9.6                h8703b6f_2
    qtconsole                 4.4.2                    py37_0
    readline                  7.0                  h7b6447c_5
    regex                     2018.11.02       py37h7b6447c_0
    requests                  2.19.1                   py37_0
    scikit-learn              0.20.0           py37h4989274_1
    scipy                     1.1.0            py37hfa4b5c9_1
    seaborn                   0.9.0                    py37_0
    send2trash                1.5.0                    py37_0
    setuptools                40.4.3                   py37_0
    simplegeneric             0.8.1                    py37_2
    sip                       4.19.8           py37hf484d3e_0
    six                       1.11.0                   py37_1
    spacy                     2.0.16           py37h962f231_0
    sqlite                    3.25.2               h7b6447c_0
    statsmodels               0.9.0            py37h035aef0_0
    terminado                 0.8.1                    py37_1
    testpath                  0.4.2                    py37_0
    thinc                     6.12.0           py37h4989274_0
    tk                        8.6.8                hbc83047_0
    toolz                     0.9.0                    py37_0
    torchfile                 0.1.0                      py_0    conda-forge
    torchvision               0.2.1                    py37_1    pytorch
    tornado                   5.1.1            py37h7b6447c_0
    tqdm                      4.26.0           py37h28b3542_0
    traitlets                 4.3.2                    py37_0
    ujson                     1.35             py37h14c3975_0
    urllib3                   1.23                     py37_0
    visdom                    0.1.8.5                       0    conda-forge
    wcwidth                   0.1.7                    py37_0
    webencodings              0.5.1                    py37_1
    websocket-client          0.53.0                py37_1000    conda-forge
    wheel                     0.32.2                   py37_0
    widgetsnbextension        3.4.2                    py37_0
    wrapt                     1.10.11          py37h14c3975_2
    xz                        5.2.4                h14c3975_4
    yaml                      0.1.7                had09818_2
    zeromq                    4.2.5                hf484d3e_1
    zlib                      1.2.11               ha838bed_2

I really appreciate it if you can tell me how to make Spacy faster. Thanks a million!!

**Comment by honnibal** [comment]
The following should perform better for you:

```
nlp = spacy.load('en_core_web_md')
nlp.disable_pipes(['tagger', 'ner'])
for doc in nlp.pipe(sys.stdin):
    for sent in doc.sents:
        sys.stdout.write(str(sent) + '\n')
```
