### ISSUE TITLE
Pickling Language is still not working for me

### ISSUE THREAD

**Issue by Rheelax246** [explosion/spaCy#2913]
## How to reproduce the behaviour

```
>>> import spacy
>>> import pickle

>>> spacy.cli.download('en')
>>> nlp = spacy.load('en')

>>> pickle.dumps(nlp)
AttributeError: Can't pickle local object 'FeatureExtracter.<locals>.feature_extracter_fwd'
```
I was reading about the similar issue #2121 but it isn't working for me still. What might be the reason? Would you recommend using the workaround from Issue #2121? Thank you! 

## Your Environment

spaCy version:     2.0.16         
Location:           /databricks/python/lib/python3.6/site-packages/spacy
Platform:           Linux-4.4.0-1070-aws-x86_64-with-debian-stretch-sid
Python version:     3.6.5          
Models:             en, en_core_web_sm

**Comment by honnibal** [comment]
This should now be fixed in spaCy v2.1.0a4. Sorry for the regression.
