### ISSUE TITLE
load vectors for norsk aviskorpus - norway 

### ISSUE THREAD

**Issue by alejandrojcastaneira** [explosion/spaCy#2914]
Hello. I'm trying to load custom vector from the repository: http://vectors.nlpl.eu/repository/ to the norwegian model created by Ole Henrik Skogstrøm: https://github.com/ohenrik/nb_dep_ud_sm using the Norsk Aviskorpus + NoWaC + NBDigital Corpus trained whit globe using 302854595 tokens resulting in a vocabulary of 4480047 vectors whit dimension=100.

Here it's the following code:
```python
import spacy
import numpy

nlp = spacy.load('nb_dep_ud_sm')

with open("E:/AJCR/vectors_embeddings/79/model.txt", 'rb') as file_:
    header = file_.readline()

    nr_row, nr_dim = header.split()

    nlp.vocab.reset_vectors(width = int(nr_dim))

    for line in file_:

        line = line.rstrip().decode('utf8')

        pieces = line.rsplit(' ', int(nr_dim))

        word = pieces[0]
        vector = numpy.asarray([float(v) for v in pieces[1:]], dtype='f')
        nlp.vocab.set_vector(word, vector)

    doc1= nlp("søt")

    doc2 = nlp("speisa")

    print(doc1.similarity(doc2))

nlp.to_disk("E:/AJCR/models/nb_dep_ud_lg")
```
```python
0.35125815165636043
```
This save the model to disk which I can load it later.
But this model is almost 1.88gb large so I considered call nlp.vocab.prune_vectors on him.

```python
nlp = spacy.load('E:/AJCR/models/nb_dep_ud_lg')

nlp.vocab.prune_vectors(1493349)
```
received the following warning:
```python
Warning: Unnamed vectors this won't allow multiple vectors models to be loaded. (Shape: (1, 100))
```
It finish automatically and the number of vectors in the model was reduced to :
 ```python
"vectors":{
    "width":100,
    "vectors":1,
    "keys":1,
    "name":"spacy_pretrained_vectors"
  },
``` 
So I check the meta data of the model before prune vectors:
 ```python
"vectors":{
    "width":100,
    "vectors":4644099,
    "keys":4480047,
    "name":null
  },
```
The number of keys it's considerably smaller than the number of vectors.

## Your Environment

* **spaCy version:** 2.0.16
* **Platform:** Windows-10-10.0.17134-SP0
* **Python version:** 3.6.6
* **Models:** de_core_news_sm, en_core_web_lg, en_core_web_sm, es_core_news_md, es_core_news_sm

**Comment by honnibal** [comment]
The way you're adding the vectors causes the vectors table to be resized dynamically, and when the table is reallocated, we add some slack so that we don't always resize the vectors table.

You can call `nlp.vocab.vectors.resize((int(nr_row), int(width))` to set the size at the beginning, which should also speed things up a fair bit. This should prevent any reallocations, which should make sure the vectors table is the size you expect.
