### ISSUE TITLE
Punctuation and quality of the NER

### ISSUE THREAD

**Issue by KMohaghegh** [explosion/spaCy#2921]
Hi, 
Just want to know that how punctuation could effect on quality of the NER training. Does the Punctuation need at all? What happens if the length of the sentences for instance become 3 times bigger? what happens if we do not have so many document and just have few documents (or even exactly one very huge one) for training the NER. How might be the NER trained on no punctuation data or low quality punctuation compare to the one trained on a good punctuation data.
I checked the already trained NER, give me back the same results on PUNCTUATION and NON-PUNCTUATION text. IS it Normal?

* Operating System:MACOSX
* Python Version Used:2.7.14
* spaCy Version Used:2.0.13
* Environment Information:

**Comment by ines** [comment]
> I checked the already trained NER, give me back the same results on PUNCTUATION and NON-PUNCTUATION text. IS it Normal?

It's possible, but not always the case. As far as spaCy is concerned, a punctuation token ist a token like any other and it can have an impact on the predictions in context.

Ideally, the data you're using for training should be similar to the data the model will see at runtime. If you only train your model without punctuation and it then sees punctuation at runtime, it'll likely get confused and predict something random. Similarly, a model trained on data with no typos and proper punctuation may struggle with social media text that often doesn't use proper spelling, punctuation or capitalisation.
