### ISSUE TITLE
Unreasonable hash for the character 'X'

### ISSUE THREAD

**Issue by sandydo** [explosion/spaCy#2930]
Hi everyone,

for some reason the character 'X' is not excepted in the StringStore. Do this
```
from spacy.strings import StringStore
SS = StringStore()
print(SS.add('X'))
```
It is hashed onto the number 100, which is not reasonable. Further it won't accept 'X' in the string store, do this
```
SS = StringStore()
print(len(SS))
SS.add('X')
print(len(SS))
```
it should print out 0 and 0, which is not reasonable neither.

There might be something wrong with the Murmur hashing...

I have:
Ubuntu 16.04.4 LTS
Python 3.6.4 :: Anaconda, Inc.
spacy version '2.0.11'

Looking forward to a response.

Best,
sandydo

**Comment by ines** [comment]
Yes, just like `X`, those are all part of the symbols – see [`symbols.pyx`](https://github.com/explosion/spaCy/blob/master/spacy/symbols.pyx). Symbols are built-in and receive one of the reserved IDs rather than a generated hash.
