### ISSUE TITLE
Uploading spacy model

### ISSUE THREAD

**Issue by zkrhm** [explosion/spaCy#2935]
Hi, how do I upload model so my model can be available for all spacy user and downloadable from spacy's cli?

* **spaCy version:** 2.0.17
* **Platform:** Darwin-18.2.0-x86_64-i386-64bit
* **Python version:** 3.7.0
* **Models:** en_core_web_sm, en, xx

**Comment by ines** [comment]
Hi! What model are you interested in contributing? Is it something we can train, or does it rely on data that can't be distributed?

All models we distribute need to be trained by us, so we can guarantee that they're good and safe, and so we can re-train then whenever we publish a new version. However, we do appreciate contributions and the best way you can help is by providing training pipelines that we can run – e.g. a series of settings and commands and the dataset you used, so we can reproduce your results and provide an official spaCy model.

Also see #2404:

> The problem is that we want to make sure all the models can be reproduced, so that when we release a new version, we can provide updated models. I've been working for a long time on better training automation, which might allow us to offer some facilities to contribute scripts. But for now the process is tied into our other infrastructure, so there's no clean repo to contribute to.
