### ISSUE TITLE
unwanted sensitivity to punctuations in p.m.

### ISSUE THREAD

**Issue by uriva** [explosion/spaCy#2937]
When using

```
import spacy
nlp_en = spacy.load('en_core_web_sm')
spacy.displacy.serve(nlp_en(text), style='dep')
```
Theses two sentences have radically different parses:

> it's for tomorrow 11 a.m. until Sunday 1 pm

> it's for tomorrow 11 a.m. until Sunday 1 p.m.

I'd say the latter has the more correct parse, where 1pm relates to sunday.

Anything to do about it?
Thanks

(spacy version 2.0.16)

**Comment by wxv** [comment]
Note that your sentences don't start with a capitalized letter and the first doesn't end with a period. Maybe that matters.

**Comment by uriva** [comment]
I hope not.
humans don't capitalize or end sentences with a dot at all times

**Comment by ines** [comment]
> humans don't capitalize or end sentences with a dot at all times

It's definitely possible that this has an impact on the model, depending on what it's seen during training. Models are statistical, and the tagger and parser only predict which analysis is most likely in this context – so if it hasn't seen certain alternative spellings during training, it might predict something differently.

Going forward, we're trying to make the models less sensitive to things like this, for example using data augmentation and the [norm exceptions](https://spacy.io/usage/adding-languages#norm-exceptions), which ensure that both "p.m." and "pm" receive similar representations, even if one is less frequent in the training data.

> Anything to do about it?

If examples like this are common in your data, you can always fine-tune the model and update it with more examples. [See here](https://spacy.io/usage/training#example-train-parser) for an example.
