### ISSUE TITLE
Splitting into paragraphs

### ISSUE THREAD

**Issue by d5555** [explosion/spaCy#2938]
Does spaCy have plans to support splitting into paragraphs?
I know we currently can extract sentences from doc, but what about paragraphs? 
There is a new function docs_to_json in spaCy and resulted json contains dictionary key "paragraphs". But it doesn't actually split into "paragraphs".  Why not to make spaCy do this job of splitting doc into paragraphs as well?

**Comment by BramVanroy** [comment]
To do so, you'd need consensus about what constitutes a paragraph. A new line? Probably. But what about indentation or numbering/listing?

**Comment by areeves87** [comment]
@BramVanroy what is your point? Is it that there are too many edge cases to cover for paragraph splitting? Or are you instead trying to get a list of edge cases started for future discussion?

**Comment by DuyguA** [comment]
Hello,
I doubt that one needs a statistical model. Statistical models are big hammers, both difficult to develop and test. Depending on your corpus, I think you can play some tricks. Here are some ideas:

1. Whitespace beginning at the sentence:

> You see how it ends with having affairs with coworkers.
>   At that point I thought, ....

2. Newline break after a line end:

> My dog bites the veterinary and he sued me for 1M Euro. At the same day my mom died and my wife told me we're divorcing and she'll marry my best friend.
> All happened three days ago. I assume all readers see my point.
> 
> After that  this point, ....

It depends on your corpus, is it customer emails or is it wiki pages, webpages... I advice to parse on
document structure.
