### ISSUE TITLE
fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86'

### ISSUE THREAD

**Issue by udaybhaskar4592** [explosion/spaCy#2939]
## How to reproduce the problem

```bash
# copy-paste the error message here
```

## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:
I have solved all the issues related to cl.exe. I am using windows 7 operating system. I have python 3.6.5 (64 bit) installed on it. I tried installing spacy using command pip -U install spacy. Earlier I could install spacy on 3.6.5 and 3.6.6 (32 bit versions). and it also shows
error: 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\link,exe' failed with exit status 1112

I have searched for this a bit and found this. Kindly look into this and revert.

[https://stackoverflow.com/questions/3563756/fatal-error-lnk1112-module-machine-type-x64-conflicts-with-target-machine-typ](url)

Thank you.

**Comment by udaybhaskar4592** [comment]
i have no issues installing it on 32 bit python. The problem is with 64 bit python only.

**Comment by udaybhaskar4592** [comment]
![attach to github](https://user-images.githubusercontent.com/45126894/48663998-0dbd5d80-eabe-11e8-95bb-e092ef29ca85.png)
same result when I used pip install spacy==2.0.16

**Comment by honnibal** [comment]
Your Windows is 64 bit, but I think you'll find that the Python you're using is 32 bit.

**Comment by honnibal** [comment]
Can you try `pip install spacy==2.0.18`? It should have wheel installation, which will avoid any errors like this.
