### ISSUE TITLE
Initialization in text 

### ISSUE THREAD

**Issue by opatrascoiu** [explosion/spaCy#2942]
In `evaluate `method from 
    https://github.com/explosion/spacy/blob/master/examples/training/train_textcat.py
tp, fp, fn, and tn (true positives etc) are initialized to 1e-8 (see below)

```
tp = 1e-8  # True positives
fp = 1e-8  # False positives
fn = 1e-8  # False negative
tn = 1e-8  # True negatives
```

Why are the values not initlaized to 0? When there are no true positives the precision is 0.5, That doesn't seem right.

**Comment by honnibal** [comment]
Fair point --- if there are no true or false positives, I guess the precision should be 0.0. I didn't think of that case.
