### ISSUE TITLE
Intent Parser Multi-word Entities

### ISSUE THREAD

**Issue by jfantell** [explosion/spaCy#2944]
I am trying to train a model using the following script:

https://github.com/explosion/spacy/blob/master/examples/training/train_intent_parser.py

I am providing the model this sample data:

    ("show me the best Marriot hotel in New York", {
    'heads': [0, 0, 5, 5, 5, 0, 7, 5, 5],
    'deps': ['ROOT', '-', '-', 'QUALITY', 'PLACE', 'PLACE', '-', 'LOCATION', 'LOCATION']
    })

Currently, this produces the following output:

[('show', 'ROOT', 'show'), ('best', 'QUALITY', 'hotel'), ('Marriot', 'PLACE', 'hotel'), ('hotel', 'PLACE', 'show'), ('New', 'LOCATION', 'hotel'), ('York', 'LOCATION', 'hotel')]

Instead, I want it to produce this output:

[('show', 'ROOT', 'show'), ('best', 'QUALITY', 'hotel'), ('Marriot hotel', 'PLACE', 'hotel'), ('New York', 'LOCATION', 'hotel')]

I did not find any documentation on how multi-word entities such as "New York" and "Marriot hotel" can be extracted using the intent parser. Could someone please advise me as to how this could be done? Thank you for your time in advance!

**Comment by honnibal** [comment]
You could try merging the named entities into one token each before training your intent parser. Alternatively, you might be better off leaving them as multiple tokens, and then dealing with the subtree afterwards. You can find docs about the merge method here: https://spacy.io/api/doc#merge
