### ISSUE TITLE
Semantic Analysis Inquiry

### ISSUE THREAD

**Issue by jfantell** [explosion/spaCy#2945]
I am trying to create a program that extracts the start and destination location from a sentence.
Consider the following two examples:

"I want to take a taxi to Boston from New York"
"I want to take a taxi from New York to Boston"

The start location is always New York. The end location is always Boston. However, because of the re-ordering of "from" and "to," the position in which the start and destination locations appear is swapped.

Is there a way to determine which location is the start and destination regardless of ordering using any of the tools in Spacy?
Any pointers (especially examples) would be very helpful! Thank you!

**Comment by honnibal** [comment]
I think using the dependency parse and the entity labels will probably be the best way for you. Have a look at the docs here: https://spacy.io/usage/processing-pipelines
