### ISSUE TITLE
Trying to figure out how to get a pipeline running on GPU.

### ISSUE THREAD

**Issue by deepdad** [explosion/spaCy#2952]
Using the GPU/vector model for English, 
```
p.

**Comment by BramVanroy** [comment]
Please provide more information:
 - a full code snippet (including sample data)
 - your environment (GPU, CUDA version, Python version, spaCy version)

**Comment by deepdad** [comment]
Fresh /latest yesterday:
CUDA 10
8 x Tesla V100 (AWS P3.16xlarge)
Ubuntu 18
Python3.6

without the fluff:
```
def parse(doc):
    ann_toks_deps_tags = []
    for tok in doc:
        ann_toks_deps_tags.append(tok.text, tok.tag_, tok.dep_)
        print(tok.text, tok.tag_, tok.dep_)

def process(sample =[]):
    for z in sample:
        doc = nlp(z["zin"])
        ann_toks_deps_tags = parse(doc)

def tag():
    spacy.prefer_gpu()
    nlp = spacy.load('en_core_web_lg')
    sample =[{"zin": "This is written here."}, {"zin":"I also typed it."}]
    process(sample)

tag()
```

**Comment by honnibal** [comment]
I suspect the problem is the use of CUDA 10, which is currently not supported by cupy. Try again with CUDA 9.2?

**Comment by deepdad** [comment]
thanks
