### ISSUE TITLE
Programmatic method for downloading word vectors

### ISSUE THREAD

**Issue by areeves87** [explosion/spaCy#2954]
Is there a programmatic method for downloading word vectors within a .py script? I am familiar with the `python -m spacy download en` terminal command. Instead of that, I would like to download the word vector file and load the word vectors all from within a python script. I'm not seeing any obvious approaches in the documentation. Is this currently possible?

Thank you!

## Which page or section is this issue related to?

https://spacy.io/models/

**Comment by honnibal** [comment]
All of the CLI commands are accessible as Python functions, using e.g. `spacy.cli.download` should do what you want. In some situations, you might not want to install a model into the virtual environment, as it's sometimes to work with the file-system yourself. In these situations, you might want to download the model packages directly. You can find them all here: https://github.com/explosion/spacy-models/releases
