### ISSUE TITLE
Comparison of spaCy text  segmentation with Stanford CoreNLP

### ISSUE THREAD

**Issue by Raghava14** [explosion/spaCy#2956]
Hello I want to know how does spaCy's sentence boundary detection compares with the [Stanford CoreNLP version](https://stanfordnlp.github.io/CoreNLP/ssplit.html). I have come across a [blog](https://tech.grammarly.com/blog/how-to-split-sentences) from grammarly which does comparison but does not include spaCy.
Thanks.

* **Python version:** 2.7.14
* **Platform:** Linux-4.4.0-135-generic-x86_64-with-debian-stretch-sid
* **spaCy version:** 2.0.10
* **Models:** en, de, de_core_news_sm

**Comment by honnibal** [comment]
I think the answer will really depend on your data -- so you should probably run tests yourself to find out how that impacts your application.
