### ISSUE TITLE
Text Classification example in docs should be replaced with a multi-label classification

### ISSUE THREAD

**Issue by TheShadow29** [explosion/spaCy#2957]
The issue is related to text classification described in docs here: https://spacy.io/usage/training#section-textcat

Currently, the example is given for binary classification dataset (imdb classifying into positives and negatives).

The suggestion is to replace or add another section with multi-label classification problem as it seems non-trivial to adapt the code to multi-label (at least I am still struggling with it). Also, the evaluation code can probably be replaced with scikit-learn metrics.

**Comment by honnibal** [comment]
+1 on replacing with multi-label text classification. In fact even on the binary text classification problem, the results are more reliable if we use two output neurons, one for POSITIVE and one for NEGATIVE.

The library doesn't currently depend on scikit-learn though, so I'd rather not use it just for metrics.

**Comment by honnibal** [comment]
The example for v2.1 now adds separate `POSITIVE` and `NEGATIVE` labels, which performs better and makes it more obvious how to change the example for more labels.
