### ISSUE TITLE
Loss keeps increasing while training multi label text categorizer with 'textcat'

### ISSUE THREAD

**Issue by chinmaygadkari7** [explosion/spaCy#2961]
Hi Team,
I am creating a multi label text classifier with at least 10 labels.
My input text is a a tuple of texts:
ex. `('This article is about health insurance', 'This article is about life insurance', .. )`

And, labels is a tuple containing dictionary in format:
`( {'cats': {'health insurance': True, 'insurance': True}}, {'cats': {'life insurance': True, 'insurance': True}})`

Other things are similar to the Spacy documented [TextCategorizer example](https://spacy.io/usage/training#section-textcat).
 
While training the model, loss value keeps increasing continuously. 
```
[100] Recall: 0.100, Precision: 0.040, Loss: 4.92038631439209
[200] Recall: 0.420, Precision: 0.120, Loss: 9.701560974121094
[300] Recall: 0.430, Precision: 0.130, Loss: 15.13874340057373
```
And so on..
I tried passing all labels by setting Negatives to `False`, but result doesn't change.

Am I passing input labels wrong or do I have to additionally specify something else?   

## Your Environment

* Operating System: Ubuntu 16.04LTS
* Python Version Used: 3.5.2
* spaCy Version Used: 2.0.12

**Comment by honnibal** [comment]
Are you sure that's not simply printing the accumulated loss across all epochs, instead of the loss for the last epoch?

**Comment by chinmaygadkari7** [comment]
Yeah, Thanks, it was a bug. I was calculating accumulated loss for batches. 
Closing this issue.
