### ISSUE TITLE
Cannot import 'prefer_gpu' error

### ISSUE THREAD

**Issue by devNaresh** [explosion/spaCy#2963]
Hi I just updated to latest version of spacy 2.0.16 and when i am trying to import spacy i am getting error.
```
ImportError                               Traceback (most recent call last)
<ipython-input-1-c080f6458562> in <module>()
----> 1 import spacy

/anaconda/lib/python3.6/site-packages/spacy/__init__.py in <module>()
      6
      7 # These are imported as part of the API
----> 8 from thinc.neural.util import prefer_gpu, require_gpu
      9
     10 from .cli.info import info as cli_info

ImportError: cannot import name 'prefer_gpu'
```

**Comment by devNaresh** [comment]
Resolved after updating thinc :-)

**Comment by qhungngo** [comment]
Hi, I also get error like that after updating 2.0.18
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-18-029dceea1711> in <module>()
----> 1 import spacy, nltk
      2 nlp = spacy.load('en')

C:\ProgramData\Anaconda3\lib\site-packages\spacy\__init__.py in <module>()
      6 
      7 # These are imported as part of the API
----> 8 from thinc.neural.util import prefer_gpu, require_gpu
      9 
     10 from .cli.info import info as cli_info

ImportError: cannot import name 'prefer_gpu'
