### ISSUE TITLE
deep_learning_keras - Google Colab

### ISSUE THREAD

**Issue by tfitzhardinge** [explosion/spaCy#2975]
Hi

I have working through the deep_learning_keras example in Google Colab. I deleted the if statements and @plac statements following recent advice that it is not compatible with Jupyter notebooks.

I have run the code which was executed quickly and no errors pop up. However no files are created in my google drive and no output is displayed in Google Colab.

What is meant to happen and is there a step I have missed.

Thanks

**Comment by ines** [comment]
What did you pass in as the `model_dir`, e.g. the output directory, when you ran the script? Is there some convention / specific path you need to use in Google Colab to save data to your account or environment?

If you haven't done so already, I'd also recommend adding a few `print` statements throughout the main function, so you get a better sense for what it's currently doing.
