### ISSUE TITLE
MemoryError when pruning vectors with small batch size

### ISSUE THREAD

**Issue by ALSchwalm** [explosion/spaCy#2976]
## How to reproduce the behaviour
```
import spacy
nlp = spacy.load('en_core_web_lg')
nlp.vocab.prune_vectors(500000, 100)
```

The usage of the 'batch_size' parameter in the above code should avoid the memory constraints. However, a bug in [vocab.pyx](https://github.com/explosion/spaCy/blob/58757c5684426d8ea1453a9a041915ddbad60359/spacy/vocab.pyx#L300) where the `batch_size` parameter is not passed on to the `most_similar` call (indeed, it is not used at all),  causes the batch matrix to be very large when `nr_row` is large.

I can submit a PR to fix this, but I am not clear what an appropriate test would look like. I could create a large vocabulary and prune it to a slightly smaller size using a small batch size, but it would take a very long time to run, and would not necessarily fail even without the fix (if the machine running the test had lots of RAM, for example). Any advice there would be appreciated.

## Your Environment
* **spaCy version:** 2.0.16
* **Platform:** Linux-4.18.16-arch1-1-ARCH-x86_64-with-arch
* **Python version:** 3.7.1
* **Models:** en_core_web_lg

**Comment by honnibal** [comment]
Thanks for a great report!

I think in this case it's fine to get by without a test case. If the modules weren't compiled, I think it would be possible to use mock to check that the argument was passed in...But we'd literally be checking only that, which seems pretty low value.

A pull request would be very welcome :)
