### ISSUE TITLE
I think you're missing the system package `python-dev` or `python3-dev`, or possibly `python3.6-dev` -- depending on what it's called on that version of Ubuntu.

### ISSUE THREAD

**Issue by harini20** [explosion/spaCy#2978]
_Originally posted by @honnibal in https://github.com/explosion/spaCy/issues/2160#issuecomment-377040918_

**Comment by harini20** [comment]
I am facing the same issue in windows.

**Comment by honnibal** [comment]
Well does it work after you install them?
