### ISSUE TITLE
Increasing parser network batch size?

### ISSUE THREAD

**Issue by ml-pickle** [explosion/spaCy#2987]
I'm trying to increase GPU utilization during inference without spawning any more processes (all 4 cores are pegged...presumably orchestrating forward pass in thinc) is there a better way to increase the default pipeline network batch sizes (it appears [hardcoded to 8 for the Parser?](https://github.com/explosion/spaCy/blob/v2.1.0a3/spacy/syntax/nn_parser.pyx#L220)) than subclassing Tagger, DependencyParser?  I had assumed .pipe()'s batch_size param was passed along and was going crazy trying to figure out why performance wasn't scaling.  

This would also help improve performance when feeding single sentence docs, which is *much* slower than larger chunks of text. 

Thanks so much you two, amazing work!

## Your Environment
* **spaCy version:** 2.1.0a3
* **Platform:** Linux-4.18.17-200.fc28.x86_64-x86_64-with-fedora-28-Twenty_Eight
* **Python version:** 3.6.6
* **Models:** en
* **CUDA:**  9.2

**Comment by honnibal** [comment]
Hm! Few issues here. First of all, that hard-code is a mistake, surely. Would you mind checking out the develop branch and seeing how your performance changes if you fix that?

Second, how come you're seeing usage on four cores? The nightly build you're using should be single-threaded. So, something's going wrong here.

**Comment by ml-pickle** [comment]
> Hm! Few issues here. First of all, that hard-code is a mistake, surely. Would you mind checking out the develop branch and seeing how your performance changes if you fix that?

Yes, increasing batch size improves performance significantly.

> Second, how come you're seeing usage on four cores? The nightly build you're using should be single-threaded. So, something's going wrong here.

I was spreading my work over multiple processes to increase GPU utilization because larger batches wouldn't. 

I can just roll with spacy from source passing forward batch_size in pipe() instead of sub-batching. I just wanted to make sure I wasn't crazy.

Thankyou so much.  Spacy is truly a gift.

**Comment by prateek1592** [comment]
> Yes, increasing batch size improves performance significantly for both large texts and sentence length.
Hi, could you describe what exactly you changed in the code that improved performance?

**Comment by honnibal** [comment]
The hard-coded batch size should be fixed in v2.1, which you can use in `spacy-nightly`. Instead of hard-coding the size of the inner batch, we now use 1/4 of the outer batch size.
