### ISSUE TITLE
what is  the default disable list ?

### ISSUE THREAD

**Issue by susht3** [explosion/spaCy#2989]
i want to know the list of display, but i cannot find that in document.

nlp = spacy.load('en', disable=['parser', 'tagger'])
i want to know the default disable list, i want to add more.

**Comment by ines** [comment]
Just to make sure I understand your question: You're looking for a list of all possible values in the `disabled=[]` list, right? By default, it's an empty list, but it can take the name of every **pipeline component** present in the model.

See here for an overview of the available pipeline components:
https://spacy.io/usage/processing-pipelines

The [model overview](https://spacy.io/models) shows which models have which pipeline components. For example, here's the small English model:
https://spacy.io/models/en

It has the pipeline components `tagger`, `parser` and `ner`. So these are all components you can disable when loading the model.

**Comment by Jasperty** [comment]
> It has the pipeline components `tagger`, `parser` and `ner`. So these are all components you can disable when loading the model.

thanks, my code is: 
spacy_model_name = "en_coref_md"
disable = ['vectors', 'textcat', 'tagger', 'parser', 'ner']
model = spacy.load(spacy_model_name, disable=disable)
doc = model('My sister has a dog, she loves him.')

and i get this:
ValueError: [E030] Sentence boundaries unset. You can add the 'sentencizer' component to the pipeline with: nlp.add_pipe(nlp.create_pipe('sentencizer')) Alternatively, add the dependency parser, or set sentence boundaries by setting doc[i].is_sent_start.

i do not know how to add sentencizer
