### ISSUE TITLE
where is spacy.load() function？

### ISSUE THREAD

**Issue by susht3** [explosion/spaCy#2990]

**Comment by ines** [comment]
See here:

https://github.com/explosion/spaCy/blob/585de273cd768355ddf4aaa399a8a32631e3c991/spacy/__init__.py#L17-L21

It them delegates to `spacy.util.load_model`:

https://github.com/explosion/spaCy/blob/585de273cd768355ddf4aaa399a8a32631e3c991/spacy/util.py#L100-L119

Btw, in case you haven't seen it yet, you can also type in function and method names in the search bar at the top of GitHub, and it'll show you everything it finds in the code base. For example, here, like this: https://github.com/explosion/spaCy/search?q=%22def+load%22&unscoped_q=%22def+load%22
