### ISSUE TITLE
Neural network model architecture and absence of the parser

### ISSUE THREAD

**Issue by KMohaghegh** [explosion/spaCy#2993]
Hi guys,
On the Spacy document under the "**Neural network model architecture**" mentioned:

**This convolutional layer is shared between the tagger, parser and NER, and will also be shared by the future neural lemmatizer. Because the parser shares these layers with the tagger, the parser does not require tag features. I got this trick from David Weiss's "Stack Combination" paper.**

I have trained a model for Swedish without the Parser. So if the parser is the feature responsible to share this layer, I wonder what happens if it does not exist?  
Another question is what is the feature of the neural network? Is it sentence wise? document wise?
When I look at json file for training I understand that the split is not make on actual sentences and it is based on newline on the input of the BILOU file which make it like a document. So as far as I understand each newline in BILOU file make a new document. Is this correct?
Also if it is exist and possible please share a document  about the neural network pipeline for NER training. I listen to the presentation of Matt but if you have a document on this, it is great. At least something about the shared layer might be very useful.

Thanks

**Comment by honnibal** [comment]
Apologies --- that information is outdated :(. Thanks for bringing this up. I forgot we'd said that on that page, and so we didn't update the docs when the architecture changed.

Currently the layers are *not* shared. The tagger, parser and NER use independent CNNs.

**Comment by honnibal** [comment]
The neural network is document-wise, i.e. it doesn't assume the input is segmented into sentences. You can train it on data that has one sentence per document, but then you should make sure that each `Doc` object only has one sentence at runtime.

I don't have a document about the neural network pipeline, sorry. The presentation is all I have at this point.
