### ISSUE TITLE
Write explicit dependency of Unidic for Japanese tokenizer

### ISSUE THREAD

**Issue by chezou** [explosion/spaCy#3001]
Since current Japanese tokenizer depends on MeCab with Unidic, which is less popular dictionary rather than IPAdic for MeCab, it would be nice to describe to use [Unidic](http://unidic.ninjal.ac.jp/back_number#unidic_bccwj) explicitly on the dependemcy section of "Alpha tokenizaion support" page.

## Which page or section is this issue related to?

https://spacy.io/usage/models#alpha-support

**Comment by honnibal** [comment]
That sounds reasonable. A pull request would be helpful if you have time? Thanks.

**Comment by chezou** [comment]
OK, Will do.
