### ISSUE TITLE
Long sequence of digits and dots cause exponential time increase

### ISSUE THREAD

**Issue by WolfFinster** [explosion/spaCy#3002]
## How to reproduce the behaviour

I discovered the following issue with a sentence from a wikipedia dump. Long sequences of digits and dots make the computation time explode.

```
In [3]: nlp = spacy.load('de_core_news_sm') 
   ...: nlp.remove_pipe('parser') 
   ...: nlp.remove_pipe('ner') 
In [13]: for x in nlp('Bei den Aufgaben der Rechenkünstler geht es natürlich um viel höhere Potenzen mehrstelliger Zahlen – zum Beispiel die Berechnung der 25. Wurzel aus 880.794.982.218.444.893.023.439.794.626.12
    ...: 0.190.780.624.990.275.329.063.400.179.824.681.489.784.873.773.249 (Lösung: 1729) und extremere Aufgaben.'): 
    ...:     print(x) 
```

The more digits-dot segments you add the worse it gets.

The following did not terminate for me. I waited several minutes:

```
In [31]: for x in nlp('880.794.982.218.444.893.023.439.794.626.120.190.780.624.990.275.671 ist eine lange Zahl'): 
    ...:     print(x) 
```

## Your Environment

* Operating System:

> Linux

* Python Version Used:

> 3.7

* spaCy Version Used:

> 2.0.16

* Environment Information:

>     spaCy version      2.0.16         
>     Location           /home/me/miniconda3/lib/python3.7/site-packages/spacy
>     Platform           Linux-4.13.9-1-default-x86_64-with-glibc2.9
>     Python version     3.7.0          
>     Models             de_core_news_sm

**Comment by honnibal** [comment]
Thanks. This is related to the use of the `regex` library, and the fact that non-fixed-width lookarounds have crept into our expressions. The tokenizer regex needs to be refactored significantly.

**Comment by ines** [comment]
I'll merge this with the regex issue in #1642 👍
