### ISSUE TITLE
'Process finished with exit code -1073741819 (0xC0000005)' error with 'drop=0.2' parameter in NER training

### ISSUE THREAD

**Issue by KavyaGujjala** [explosion/spaCy#3005]
## How to reproduce the behaviour

'Process finished with exit code -1073741819 (0xC0000005)' error when drop parameter is used in the nlp.update function.

example:
            for batch in tqdm(batches):
                texts, annotations = zip(*batch)
                nlp.update(
                    texts,  # batch of texts
                    annotations,  # batch of annotations
                    drop=0.2,  # dropout - make it harder to memorise data
                    sgd=optimizer,  # callable to update weights
                    losses=losses)
            print('Losses', losses)

**Not working when drop=0 also**

length of TRAIN_DATA used is 69k

What might be the reason?

## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.6
* spaCy Version Used: 2.0.10
* Environment Information:

**Comment by ines** [comment]
Could you update to the latest stable version and try again? 

You're still on `v2.0.10` and we recently fixed a bug that was likely responsible for most of the segfaults during NER training. So it's possible that this is also the case here and upgrading will resolve it 🙂

**Comment by KavyaGujjala** [comment]
Thanks for the prompt reply.

Updated it to spacy 2.0.18 and it's working fine now.
