### ISSUE TITLE
Strange parse of Italian sentence.

### ISSUE THREAD

**Issue by Copper-Head** [explosion/spaCy#3008]
## How to reproduce the behaviour

JSON formatting is mine.
```python
>>> import spacy
>>> model = spacy.load("it_core_news_sm", disable=["ner"])
>>> doc = model("la gatta mangia pesce")
>>> doc.print_tree()
[
    {
        "word":"pesce",
        "lemma":"pesce",
        "NE":"",
        "POS_fine":"S__Gender=Masc|Number=Sing",
        "POS_coarse":"NOUN",
        "arc":"ROOT",
        "modifiers":[
            {
                "word":"mangia",
                "lemma":"mangiare",
                "NE":"",
                "POS_fine":"V__Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin",
                "POS_coarse":"VERB",
                "arc":"nsubj",
                "modifiers":[
                    {
                        "word":"la",
                        "lemma":"la",
                        "NE":"",
                        "POS_fine":"RD__Definite=Def|Gender=Fem|Number=Sing|PronType=Art",
                        "POS_coarse":"DET",
                        "arc":"det",
                        "modifiers":[

                        ]
                    },
                    {
                        "word":"gatta",
                        "lemma":"gatta",
                        "NE":"",
                        "POS_fine":"S__Gender=Fem|Number=Sing",
                        "POS_coarse":"NOUN",
                        "arc":"amod",
                        "modifiers":[

                        ]
                    }
                ]
            }
        ]
    }
]
```

The parse claims *pesce* is the **ROOT** of the sentence, whereas in fact it is the object. The rest of the dependencies are correspondingly unrealistic.
Interesting to note that the POS-tagger seems to work fine, the parser just ignores the postags completely.

## Your Environment

* Operating System: Ubuntu 18.04
* Python Version Used: Python 3.6.7
* spaCy Version Used: 2.0.9
* Environment Information:
models: en, fr, de, nl, it

**Comment by honnibal** [comment]
The parser and POS tagger are independent --- it doesn't use POS tags as features. So yes, sometimes the parser makes errors that don't match the POS tags, sometimes vice versa.

**Comment by Copper-Head** [comment]
We played around a bit more with the model and for what it's worth, these variations of the sentence get parsed correctly:

- *la gatta mangia il pesce*
- *il gatto magia pesce*

**Comment by ines** [comment]
Merging this with #3052. We've now added a master thread for incorrect predictions and related reports – see the issue for more details.
