### ISSUE TITLE
Training a dependency parser from scratch breaks sentence segmentation

### ISSUE THREAD

**Issue by danielkingai2** [explosion/spaCy#3010]
## How to reproduce the behaviour
Hi! Thanks for the great library!

This is actually a follow up on #2652. @DeNeutoy

From the original issue:
"We have trained a dependency parser on the GENIA 1.0 trees (converted from phrase structure trees using Stanford Core NLP) and then converted to the spacy training format using spacy convert. From the spacy docs, it seems like the dependency parser should be identifying sentence boundaries - however, our trained model (which is a good dependency parser, ~ 90 UAS on biomedical data) does not set sentence attributes."

The exact commands I use are:
`python -m spacy convert {input_path} {output_dir} --n-sents {num_sents_in_conll_file}`
`python -m spacy train en {output_dir} train.json dev.json --n-sents {num_sents_in_train} -G`

I can verify that the converted json files have many sentences in one paragraph. I have also verified that the 'en' model in my environment does split sentences properly, but the retrained model (loaded from directory using spacy.load) does not segment sentences at all. 

Any pointers on what the issue might be here?

Thanks!

## Your Environment

* **spaCy version:** 2.0.18
* **Platform:** Linux-4.4.0-112-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.7.1
* **Models:** en, en_core_web_sm

**Comment by honnibal** [comment]
I'd say the issue is that `-G` flag in your `spacy train` command. It tells spaCy to train with gold-standard pre-processing, which means the parser learns one sentence per document.

By the way, I imagine your accuracy will go up if you use pre-trained vectors. After learning some with GloVe or FastText, you should be able to get a model file with just `spacy init-model`. Then you'll be able to pass them to `spacy train` with the `--vectors` flag.

**Comment by danielkingai2** [comment]
@honnibal Thanks for the response! I agree that adding pre-trained vectors would help, trying to get a retrained parser that still segments sentences first. As for the -G flag, what would be the correct way to train a parser on gold preprocessed text that still segments sentences? Is this not something that is possible?

**Comment by honnibal** [comment]
I think you want something like:

```
python -m spacy convert {input_path} {output_dir} --n-sents 10
python -m spacy train en {output_dir} train.json dev.json
```

The `--n-sents` command could be described better. What it's doing is concatenating sentences together into pseudo-documents, so that the model has to predict sentence boundaries for them.
