### ISSUE TITLE
New mecab-python3 version breaks Japanese

### ISSUE THREAD

**Issue by polm** [explosion/spaCy#3018]
The python package used for Mecab, [mecab-python3](https://github.com/SamuraiT/mecab-python3), had a release for the first time since 2014 recently. Unfortunately one of the parts spaCy relies on is broken, see SamuraiT/mecab-python3#19. 

Since this is an optional dependency I don't think we can peg an old version for it, but maybe we should put a note somewhere if it's not fixed quickly. I will see what I can do about fixing it upstream.

## How to reproduce the behaviour

    import spacy
    ja = spacy.blank('ja')
    print(ja("a b c d"))
    # output: a b c db c dc dd

## Your Environment

* **spaCy version:** 2.0.18
* **Platform:** Linux-4.18.9-arch1-1-ARCH-x86_64-with-arch
* **Python version:** 3.7.1

**Comment by honnibal** [comment]
Thanks for letting us know!

Maybe we could set this as an `extensions_require` dependency? Then you can version it. You could install spaCy with something like `spacy[mecab]`.

**Comment by polm** [comment]
That sounds great! I'll figure out how to do that and submit a PR.
