### ISSUE TITLE
There is a typo in Lightning tour -- Multi-threaded generator

### ISSUE THREAD

**Issue by Prajna-Ty** [explosion/spaCy#3020]
## How to reproduce the behaviour
iter_texts = (texts[i % 3] for i in xrange(100000000))
should be 
iter_texts = (texts[i % 3] for i in range(100000000))
instead

## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by honnibal** [comment]
`xrange` is the Python 2 version. If we used `range` in Python 2 here, it would create a very large list. I think for now it's fine to keep this as `xrange`, as it's just an example, and most Python programmers will recognise this and adjust the example for Python 3 if necessary.
