### ISSUE TITLE
How to add custom Entity having only possible set of values ?

### ISSUE THREAD

**Issue by SuyogShah** [explosion/spaCy#3025]
I am using spacy 2.0 and python 3.6. I would like to know the way of adding custom entity with only certain possible values.

**Example**
Entity Name: UserID
Possible values:
1
2
3
4
etc..

I have thousands of ids like this and i want make sure if any of the ID is present in any sentence at any location, i can assign it to UserID entity without providing training sentence for each ID.

Please let me know if it's possible to provide certain values and i don't need to create sentence and train without it.

**Comment by ines** [comment]
If you already have a list and you only want to find entries in that list, you definitely want to use a rule-based approach. Statistical models are only useful if you have examples and want to *generalize* based on those examples, to find other similar instances.

A good place to start is the `PhraseMatcher`: 
https://spacy.io/usage/linguistic-features#adding-phrase-patterns

Once you've matched your user IDs, you can add them to the `doc.ents` manually:
https://spacy.io/usage/linguistic-features#setting-entities

And to make it more elegant, you can later wrap your code in a custom pipeline component that's run automatically when you call `nlp` on your text:
https://spacy.io/usage/processing-pipelines#custom-components

Here's an example:

```python
from spacy.lang.en import English
from spacy.matcher import PhraseMatcher

user_ids = ["1", "2", "3", "4"]  # and so on

nlp = English()
matcher = PhraseMatcher(nlp.vocab)
patterns = [nlp.make_doc(user_id) for user_id in user_ids]  # create match patterns
matcher.add('USER_ID', None, *patterns)

doc = nlp("The user has the ID 2")
matches = matcher(doc)
for match_id, start, end in matches:
    # create a entity span for each matched span
    span = Span(doc, start, end, label=match_id)
    # add the entity span to the doc.ents
    doc.ents = list(doc.ents) + [span]

print([(ent.text, ent.label_) for ent in doc.ents])
# [('2', 'USER_ID')]
```

**Comment by SuyogShah** [comment]
Thanks ines. I appreciate your help. Looking forward to get your help on https://github.com/explosion/spaCy/issues/3041
