### ISSUE TITLE
Crash with single word docs

### ISSUE THREAD

**Issue by ml-pickle** [explosion/spaCy#3034]
## How to reproduce the behaviour
import spacy
nlp = spacy.load('en')
nlp("Word")

`/usr/include/c++/8/bits/stl_vector.h:932: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = __pyx_t_5spacy_6syntax_6_state_StateC*; _Alloc = std::allocator<__pyx_t_5spacy_6syntax_6_state_StateC*>; std::vector<_Tp, _Alloc>::reference = __pyx_t_5spacy_6syntax_6_state_StateC*&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
Aborted (core dumped)`

## Your Environment
Fresh env
2.1.0a4 **built from source from `develop` branch** using `python setup.py build_ext --inplace`
gcc 8.2.1

Multi-word docs are processed fine.  Don't see this problem with spacy-nightly.

**Comment by honnibal** [comment]
This might be a model incompatibility, but it's still worth knowing, thanks.

Develop is currently ahead of the models, compatible models are training.

**Comment by ml-pickle** [comment]
Hmm... Building `v2.1.0a3` from source (to eliminate newer model dependency possibility) causes this single word doc crash but spacy-nightly wheel (based on same `v2.1.0a3`) from pypi does not. 

Don't see any compilation issues other than warnings about comparing ints with different signs. 

Strange.
