### ISSUE TITLE
spaCy Turkish isn't working for me

### ISSUE THREAD

**Issue by Acedron** [explosion/spaCy#3039]
Hi! I am using spaCy's Turkish alpha.

    from spacy.lang.tr import Turkish
    nlp = Turkish()
    
    doc = nlp(u"Bu bir cümledir.")
    print([(w.text, w.pos_) for w in doc])

I get output like this;

`[('Bu', ''), ('bir', ''), ('cümledir', ''), ('.', '')]`

Why it doesn't give types of words?

**Comment by ines** [comment]
If you import `Turkish` or any other language class from spaCy, you'll only be able to use the language data that ships with the library. For example, the tokenization rules.

Predicting part-of-speech tags requires a [statistical model](https://spacy.io/models), but we don't offer a pre-trained model for Turkish yet. [My comment](https://github.com/explosion/spaCy/issues/1490#issuecomment-441373107) in #1490 explains what's still needed to we can train one 🙂
