### ISSUE TITLE
Use of Spacy to make simpler search engine

### ISSUE THREAD

**Issue by SuyogShah** [explosion/spaCy#3041]
This is further to https://github.com/explosion/spaCy/issues/3025 where i asked how to add custom entity. this is further to it how to combine it with statistical model and phrasematcher etc.

I have below kind of texts
1.  name of user 1
2.  name and location of user 1
3.  name of account 1
4.  who is the owner of account 1
5. what was the income tax return of account 1 last year
6. how much income tax did they filed in last 5 years
7. top 5 sales person for spacy account
etc..

**Scenarios** 
How to find if its account or user ( like if user 1 is user and account 1 is account  where 1 is list of possible ids )
How to find last year as 2017 or last five years  is 2013,2014,2015,2016,2017. (time entity and year or days months like last 5 days etc.)
how to find name/owner/location are required context or any one is asked ?
how to find top 5 and spacy account (consider id 1 is for spacy)

I am new to NLP and using spacy first time. It will be great if you can provide me ideas or samples using which i can make these kind things solved and i can query database ?

Thanks in advance.

**Comment by SuyogShah** [comment]
Can Ines / someone please provide your suggestion to achieve this?

**Comment by honnibal** [comment]
Unfortunately we really can't provide application-level advice. We try to provide usage pointers for specific questions and to provide detailed documentation, but there's a point at which the problems go much beyond the tooling we provide, to more general project design questions.
