### ISSUE TITLE
python -m spacy download en  insufficient privilege

### ISSUE THREAD

**Issue by yyHaker** [explosion/spaCy#3049]
## How to reproduce the problem

```bash
# python -m spacy download en
```
![image](https://user-images.githubusercontent.com/18585628/49941689-30586000-ff1e-11e8-98c5-b787a35de489.png)

## Your Environment

* Operating System: linux
* Python Version Used: py3.6
* spaCy Version Used: 2.0.12
* Environment Information:

**Comment by yyHaker** [comment]
I am using anaconda python environment!

**Comment by DuyguA** [comment]
How about doing a sudo?

**Comment by ines** [comment]
This looks like more of a general issue with pip? Your environment details say you're using Python 3, but the paths in your screenshot all refer to Python 2.7. Maybe the `pip` spaCy is calling in a subprocess is the wrong one?

If this is the case, you can always download and install the models manually. See here for details: https://spacy.io/usage/models#download-pip
