### ISSUE TITLE
doc vectors from different language not zero

### ISSUE THREAD

**Issue by khaerulumam42** [explosion/spaCy#3051]
I try to get doc vector from Indonesian sentences using 'en' model, I run code like this 
`import spacy`
`nlp = spacy.load('en')`
`query = "pesankan tiket ke bandung dong"`
`doc1 = nlp(query)`

when I type `doc1.vector`, the output is non-zero vector even-though tokens in query not have word vector.
As documentation say [here](https://spacy.io/usage/vectors-similarity), 
> Models that come with built-in word vectors make them available as the Token.vector  attribute. Doc.vector  and Span.vector  will default to an average of their token vectors

So how to get average vector when tokens vector are zero vector?

Thank you

**Comment by ines** [comment]
You're using the `en_core_web_sm` model here, right? 

I think what's happening here is that the `token.vector` defaults to the context tensors of the neural network models. Those are not "true word vectors", but they're also meaning representations of the words that are used internally by the tagger, parser and entity recognizer. If no word vectors are available in the model, spaCy will default to using the tensors so you're still able to use the `.similarity` methods.

This feature was originally intended to be helpful – but it's been causing some confusion, so we want to rethink the way this is handled in the library.

**Comment by khaerulumam42** [comment]
No, i'm not using `en_core_web_sm`,I'm using `en` model. 

I thought `token.vector` just create from the representation of token without tagger, parser and entity so before you explain that, I think when we use same language for word embedding and query we get better results than we use different language.

But yes, its very helpful when the case we work is many OOV appear.
Thank you so much @ines , your explanation make me clear and understand more how it works.
