### ISSUE TITLE
spacy.load Error ValueError: 93066 exceeds max_map_len(32768)

### ISSUE THREAD

**Issue by o10o** [explosion/spaCy#3053]
## How to reproduce the behaviour
I would like to use spacy with fr_core_news_sm, when i use spacy.load, i always have
this message **ValueError: 93066 exceeds max_map_len(32768)**

I tried several things found on the forum but nothing  works

!pip install spacy==2.0.18
import spacy
!python -m spacy download fr_core_news_sm 

!python -m pip install "msgpack==0.5.6"
nlp =spacy.load('fr_core_news_sm')

## Your Environment

* Operating System:  windows / google chrome
* Python Version Used:  python 3 
* spaCy Version Used: 2.0.18
* Environment Information: using Jupyter on google colab

**Comment by theudas** [comment]
The problem is an update of msgpack, a lot of librarys have this issue at the moment.

e.g. https://github.com/dask/distributed/issues/2392

**Comment by ines** [comment]
Downgrading `msgpack` should definitely work – maybe the problem here is that this line doesn't correctly remove and reinstall the package?

> ```
> !python -m pip install "msgpack==0.5.6"
> ```

What does the output say? Maybe there's something specific to Google Colab and Jupyter that you need to do in order to make this work as expected?
