### ISSUE TITLE
Expected GPU Memory Usage - inference - default models

### ISSUE THREAD

**Issue by ml-pickle** [explosion/spaCy#3057]
What type of GPU memory usage should we be looking at for the default `en_core_web_small` model using the tagger + parser?  

Say `batch of 128 docs` with `avg length of 178 tokens` (but up to 10x that possible).  

I'm seeing `~1-2GB+` which seems like very large matmul's.

**NOTES:**
* I've built from source to allow the parser's `pipe()` to take larger batches. 

* I've also made sure to sort input texts by length so the parser is not wasting too much memory on padding due to large diff in doc length.  I have 10's of thousands of docs so the variance in length should not be large in batches of 128. 

Thank you!

## Your Environment
* Operating System: linux
* Python Version Used: 3.6
* spaCy Version Used: `2.1.0a3`
* Environment Information: Cuda 9.2, cupy

**EDIT**

So I've found your architecture notes...I see that precomputing the hidden layer outputs can be a massive matmul if you don't have short docs.

**Comment by honnibal** [comment]
This is a very fair question, and I don't really have a good answer currently. I feel like somewhere in my implementation I could be wasting memory in the forward pass. It should be at least linear in the number of tokens in the batch --- if it's not something's deeply wrong. It'd be good to get the exact multiplier, so if you've done some testing I'd be eager to hear your findings.
