### ISSUE TITLE
Implement the Transformer

### ISSUE THREAD

**Issue by mr-bjerre** [explosion/spaCy#3058]
## Feature description
Implementing the [Transformer model](https://arxiv.org/abs/1706.03762) as an optional replacement of CNN. 

Now I am not entirely sure if this would make sense but it just seems that the Transformer model is very promising in every aspect in the NLP space so I was wondering if it would be worth implementing that in `spaCy` if its even possible?

**Comment by giannisdaras** [comment]
There is an ongoing effort to implement this for spaCy.
You can have a look in [this](https://github.com/giannisdaras/thinc/tree/feature/attention) branch of my forked repo of thinc.
The implementation is not ready yet but there has been significant progress, so hopefully, in the next days it will be 100% ready and merged to master branch.

**Comment by mfallu** [comment]
This is interesting- it would be convenient to be able to test elmo and Bert on problems directly via Spacy
https://jalammar.github.io/illustrated-bert/

**Comment by mr-bjerre** [comment]
Are there any progress on the Transformer implementation?

**Comment by honnibal** [comment]
@mr-bjerre See https://github.com/explosion/spacy-pytorch-transformers 🎉

**Comment by mr-bjerre** [comment]
You guys !! C,") I salute you
