### ISSUE TITLE
Training NER using the full corpus

### ISSUE THREAD

**Issue by miguelwon** [explosion/spaCy#3060]
I'm using spacy train command line interface to train a NER. I have done CV with 10 folds to check how it performs in all my data, where I have used each 90% fold as train and the respective 10% as development data. Everything is working fine and now I want to train one last model with all the available data. However, according to #1578, train command needs a development data. 

Is there a workaround to use train command without development data? 

* **spaCy version:** 2.0.18
* **Platform:** Linux-4.4.0-130-generic-x86_64-with-Ubuntu-16.04-xenial
* **Python version:** 3.6.6

**Comment by honnibal** [comment]
If you really want, you can just pass the file path for your training data as the development data. I would recommend sectioning off *some* examples as development data, though. If nothing else, you need to pick an epoch to export. The last epoch of training isn't necessarily the most accurate. If you just use the training data with no development data, you don't know whether the model has overfit towards the end of training, leaving you with a bad model.

**Comment by miguelwon** [comment]
Ok, that's a good point. Thanks for the advice.
