### ISSUE TITLE
Recommended way to build dialogue manager ? 

### ISSUE THREAD

**Issue by iccyrave** [explosion/spaCy#3061]
Given a Knowledge text and a question and answer to that question. How shall I go about using Spacy to answer another question which may be referencing context of the previous question?

Example-

Knowledge Text - "Delhi is Capital of India. People in Delhi celebrate Independence day by flying kites which is quite different from other parts of India".

Question - What is the capital of India?
Spacy - Delhi.
Question - How do people celebrate independence day there?
Spacy - ?

In this particular example, I could try to find subject Noun of the previous question and try answering. Solving this, in general, is something I want to get started on.

## Your Environment

* Operating System: Linux
* Python Version Used: >3
* spaCy Version Used: 2
* Environment Information:

**Comment by honnibal** [comment]
This is pretty much an unsolved research question. You might have noticed that systems like Siri sort of suck. So if you find out the answer, I'm sure Apple will be eager to hear it :).

A lot of users of spaCy use Rasa for their dialogue management: https://rasa.com/docs/nlu/
