### ISSUE TITLE
doc.to_array fails on singe string attribute

### ISSUE THREAD

**Issue by dswah** [explosion/spaCy#3064]
## How to reproduce the behaviour
Trying to export `doc.to_array` by specifying a single STRING attribute ([as per the documentation](https://spacy.io/api/doc#to_array)) fails, giving a `KeyError`:
```python
from spacy.attrs import POS
doc = nlp(u'the docs say i can use a string')
np_array = doc.to_array("POS")
```
results in :
```
KeyError                                  Traceback (most recent call last)
<ipython-input-127-904e71626dc6> in <module>
      1 from spacy.attrs import POS
      2 doc = nlp(u'the docs say i can use a string')
----> 3 np_array = doc.to_array("POS")

doc.pyx in spacy.tokens.doc.Doc.to_array()

doc.pyx in spacy.tokens.doc.Doc.to_array()

KeyError: 'P'
```
looks like spacy detects that the string is iterable and is treating the contents of the string as the attribute keys to be exported?

## Your Environment
* **spaCy version:** 2.0.18
* **Platform:** Linux-4.14.67-coreos-x86_64-with-debian-buster-sid
* **Python version:** 3.6.6
* **Models:** en

**Comment by dswah** [comment]
looks like https://github.com/explosion/spaCy/blob/57f274b693b08af5539fb38accd8a37cdf3c385b/spacy/tokens/doc.pyx#L595

should be checking:

```python
if hasattr(py_attr_ids, '__iter__') \
        and isinstance(py_attr_ids, basestring_):
            py_attr_ids = [py_attr_ids]
```

instead?

**Comment by honnibal** [comment]
@dswah There are three cases:

1. `doc.to_array('ORTH')` # String
2. `doc.to_array(ORTH)` # Integer ID
3. `doc.to_array(['ORTH'])` # List (might have string or integer entries)

We need to detect that something's a container without catching strings in the condition. I've always hated that Python makes this a bit hard. Maybe this would work:

```
if isinstance(py_attr_ids, basestring_):
    # Handle inputs like doc.to_array('ORTH')
    py_attr_ids = [py_attr_ids]
elif not hasattr(py_attr_ids, '__iter__'):
    # Handle inputs like doc.to_array(ORTH)
    py_attr_ids = [py_attr_ids]
```

We could make it a single "or" condition but I think the cases are tricky enough to warrant the multiple lines. We don't currently have line coverage set up for Cython, but once we do, it makes sense to be checking our tests cover both branches.

**Comment by dswah** [comment]
> We could make it a single "or" condition but I think the cases are tricky enough to warrant the multiple lines. We don't currently have line coverage set up for Cython, but once we do, it makes sense to be checking our tests cover both branches.

Agreed, this is easier to read and comprehend anyways.
