### ISSUE TITLE
SSL error when downloading models is still here behind a proxy

### ISSUE THREAD

**Issue by mn3mos** [explosion/spaCy#3066]
The problem reported in #2211 #2212 #2248 and #2414 is still there though discussion in #2414 says it is fixed in versions later than v2.0.11.
I tried with version v2.0.18 and I still have the problem.

A [fix/workaround](https://github.com/mn3mos/spaCy/tree/feature/ssl-certs-config) had been proposed in branch  feature/ssl-certs-config
But it seems it seems it never got merged - or was reverted?

I am volunteer to fix it properly if you tell me what was wrong with the previous fix.

Any way you see fit, but it is important as for now this restrains the use of spacy in many corporate environments.

## Your Environment

* **spaCy version:** 2.0.18
* **Platform:** Linux-3.10.0-957.1.3.el7.x86_64-x86_64-with-redhat-7.6-Maipo
* **Python version:** 3.6.6

**Comment by ines** [comment]
The previous fix relates to a different implementation of the `download` command – we briefly tried dropping the `requests` dependency, but it caused some additional SSL failures, so we ended up reverting this update and added the option of passing down pip arguments instead.

How do you normally download things from `pip` behind your proxy? The `spacy download` command will pass all additional flags and options on the command line to `pip install`.

**Comment by honnibal** [comment]
By the way, note that you can always download the models manually, by going to the releases page of the spacy-models repo here: https://github.com/explosion/spacy-models

After downloading a model, you can either install it with pip, or you can extract the data and point `spacy.load()` to the filepath of the model directory within it.

**Comment by shaked571** [comment]
I'm  actually having the same issue with the download, it's weird because i managed to install spacy but failed on the model downloading
