### ISSUE TITLE
Error while using using spacy for Hindi

### ISSUE THREAD

**Issue by salilmishra23** [explosion/spaCy#3068]
## How to reproduce the behaviour

```
from spacy.lang.hi import *
def word_tokenize(document):
    nlp = Hindi() # from spacy.lang.hi
    return [token.text for token in nlp(document)]
    
def docs_tokenize(documents_as_lists):   
    for document in documents_as_lists:
        tokens = word_tokenize(document)
        tokens_list.extend(tokens)
    
    return tokens_list
```

`File "/usr/local/lib/python3.6/dist-packages/spacy/lang/hi/lex_attrs.py", line 57
     LIKE_NUM: like_num
           ^
SyntaxError: invalid syntax`

## Your Environment

* Operating System: Linux
* Python Version Used: 3.6
* spaCy Version Used: 2.0.16
* Environment Information: On Google Colab

**Comment by ines** [comment]
Hi! I think the version you're using contained an error in Hindi due to a missing comma, which has since been fixed – see [here](https://github.com/explosion/spaCy/blob/v2.0.18/spacy/lang/hi/lex_attrs.py#L56-L57).

So if you're able to upgrade, try installing the latest version `v2.0.18`.
