### ISSUE TITLE
PhraseMatcher callback returning all matches

### ISSUE THREAD

**Issue by piercefreeman** [explosion/spaCy#3069]
## How to reproduce the behaviour

```
def on_match(matcher, doc, id, matches):
    print('Matched!', matches, id)

def on_match2(matcher, doc, id, matches):
    print('Matched 2!', matches, id)

matcher = PhraseMatcher(nlp.vocab)
matcher.add('OBAMA', on_match, nlp(u"Barack Obama"))
matcher.add('HEALTH', on_match2, nlp(u"health care reforms"),
                                nlp(u"healthcare reforms"))
doc = nlp(u"Barack Obama urges Congress to find courage to defend his healthcare reforms")
matches = matcher(doc)
```

```
Matched! [(7732777389095836264, 0, 2), (3161894980173008574, 10, 12)] 0
Matched 2! [(7732777389095836264, 0, 2), (3161894980173008574, 10, 12)] 
```

When I run this phrase matcher against the given input, I expect it to call the `on_match` function with the Barack Obama match and the `on_match_2` with the healthcare reform example.  It seems like each is triggered with all the results.  Is this a bug or a misunderstanding from the documentation?

## Your Environment
* Operating System: OS X
* Python Version Used: 3.6.5
* spaCy Version Used: 2.0.18

**Comment by honnibal** [comment]
Seems like a bug, thanks.

**Comment by ines** [comment]
Yeah, I'd also love to give the general `Matcher` and `PhraseMatcher` API an overhaul – I think we can make this nicer and more intuitive. But for backwards compatibility, this would have to wait until spaCy 3.
