### ISSUE TITLE
wrong tag_ predicting  -  empty string

### ISSUE THREAD

**Issue by d5555** [explosion/spaCy#3070]
English part-of-speech tagger ( .tag_ ) is supposed to label with 'XX' or 'NIL' unknown or missing tags according to tag scheme for English labels. It would match .pos_ tags : 'X' or (empty string for missing tag).
[https://spacy.io/api/annotation](https://spacy.io/api/annotation)
[https://github.com/explosion/spaCy/blob/master/spacy/lang/en/tag_map.py](https://github.com/explosion/spaCy/blob/master/spacy/lang/en/tag_map.py)
In the example below we can see that whitespace before London was tagged tag_='' ( repr of empty string).  But empty string is not in the  tag scheme or tag map for English labels.  it is supposed to be   "NIL":  {POS: ""}  or  "XX":  {POS: X}. 
It creates inconsistency.  When I'm trying to train tagger  based on spacy model and there is by accident empty string label among labels to add to tagger (tagger.add_label(tag, values))  I got Error :  ValueError: [T003] Resizing pre-trained Tagger models is not currently supported. 
Which confirms that empty string as a tag is missing in the spacy model ( en_core_web_sm)  but nonetheless we still got labels of empty string when predicting.  

Isn't it a bug and should be fixed ? Either empty string tag should be added so we don't get the Error when training model and trying to add labels or  this label should be excluded somehow from tagger so it gives NIL or XX instead.   

import spacy 
nlp=spacy.load('en')
doc=nlp('I like (**insert 2 whitespaces**) London and Berlin.')
for j in doc:
	print(j.text,  ', tag_=',   repr(j.tag_),   ', pos_=',    j.pos_ )

I , tag_= 'PRP' , pos_= PRON
like , tag_= 'VBP' , pos_= VERB
  , tag_= '' , pos_= SPACE
London , tag_= 'NNP' , pos_= PROPN
and , tag_= 'CC' , pos_= CCONJ
Berlin , tag_= 'NNP' , pos_= PROPN
. , tag_= '.' , pos_= PUNCT

* Operating System: Windows 10
* Python: 3.6
* spaCy Version Used:  **2.0.18**  or  **2.1.0a4**
* Environment Information:

**Comment by ines** [comment]
This looks like a problem in the model – you definitely shouldn't have to add the empty string as a label and the tagger should always assign a label, not an empty string.

Here's the minimal reproducible example (problem still exists in the nightly models):

```python
>>> nlp = spacy.load("en_core_web_sm")
>>> doc = nlp("I like  London and Berlin")
>>> [(t.tag_, t.pos_) for t in doc]
[('PRP', 'PRON'), ('VBP', 'VERB'), ('', 'SPACE'), ('NNP', 'PROPN'), ('CC', 'CCONJ'), ('NNP', 'PROPN')]
```

I'll merge this with the master thread in #3052.
