### ISSUE TITLE
User-defined model generating an empty list

### ISSUE THREAD

**Issue by ali4friends71** [explosion/spaCy#3071]
## How to reproduce the behaviour
After creating user-defined 'en' model and loading it, it is unable to generate the output according to the training given to the model . It is simply generating an empty list when any input is given,Previously by-default 'en' model it was generating but there was a lot of ambiguity in it,so I created a en model and loaded it but an empty list is generated. How to solve this ?? 

## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by ali4friends71** [comment]
Sorry for it as I'm using GitHub for first time !!

1
down vote
favorite
I am trying to train NER with my own data using Spacy. My question is how to integrate my trained NER into the original model ? so that it could be convenient to be continuously trained and used for my application. I did not find any sample.
This is the code I'm using 
train_data = [
    ('Who is Chaka Khan?', [(7, 17, 'PERSON')]),
    ('I like London and Berlin.', [(7, 13, 'LOC'), (18, 24, 'LOC')])
]

It is even executing and even I generated a meta.json file,vocab folder,parser folder etc. 
But when I'm loading this model and executing this model, it is not working and not parsing the string which I'm passing !!
Previously before training the NER , atleast it was parsing the string and generating outlist like this.
![untitled](https://user-images.githubusercontent.com/40916262/50287523-09071300-0489-11e9-8deb-e17e92fa915d.jpg)

But now instead of showing results accoriding to the trained NER, the output is generating an empty list !!
what can I do now ?

**Comment by ines** [comment]
No worries! GitHub can definitely be a bit confusing at first. It's always good to include as many details as possible when you open an issue. For example, a code snippet that other people can run so they can reproduce the problem. [See here](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code) for how to format code in the editor.

I'd also recommend keeping it short and very specific – this makes it a lot easier for others to understand the problem. For example: "I want to do X, so I did A, B and C. I then I got an error Y. I googled the error and tried solution Z (link), but it still happens. Here's a short code example that produces the error for me. I use Python 3.6 on Windows and spaCy 2.0.18".

It's always helpful to include details on your environment (operating system, Python version) and the spaCy version you're using (you can run `python -m spacy info` on the command line to find out.)

> I am trying to train NER with my own data using Spacy. My question is how to integrate my trained NER into the original model ? so that it could be convenient to be continuously trained and used for my application. I did not find any sample.

I assume you were running something similar to [this example](https://github.com/explosion/spaCy/blob/master/examples/training/train_ner.py), right? 

If you use a **blank** `'en'` model, this will start from scratch and train a completely new model from 0. This is probably not going to work very well with only 2 examples.

If you use an existing model like `en_core_web_sm`, you'll be able to update it with more examples. You probably also want to use a few more examples here, but it should generally work better.

If you already have text, try including training examples with entities that the model previously got correct. For example, the sentence with `"LUBNA NAAZ FATIMA"` as `PERSON`. This can help with "reminding" the model of that entity. You can find more info on training the entity recognizer here: https://spacy.io/usage/training#ner

**Comment by ali4friends71** [comment]
Thanks for the help !!
As you said to use the existing model 'en_core_web_sm', Still it is creating a blank 'en' model !!
I linked the existing 'en_core_web_sm' model using cmd administrator and it got linked successfully,
I even loaded it in my anaconda manually !!
![spacy](https://user-images.githubusercontent.com/40916262/50392418-48c54780-0774-11e9-81cc-e6e9b4f52ecd.png)

I'm loading model like this but still it is creating a new blank 'en' model and not loading the existing model !!
any further assistance please !!

**Comment by ines** [comment]
How are you calling the function (see the line above your screenshot) and what do you pass in as the argument `model`? If it's creating a blank model and printing "Creating blank model", it means that the variable `model` is `None` (the default value), so it executes the code under `else:`.

You could also just rewrite the code and construct the `nlp` object however you like? So instead of the `if`/`else`, just use `nlp = spacy.load('en_core_web_sm')` and move on.
