### ISSUE TITLE
There is a problem on your site:  ValueError: 1792000 exceeds max_bin_len(1048576)  

### ISSUE THREAD

**Issue by ibobak** [explosion/spaCy#3077]
Open the site https://spacy.io/usage/spacy-101#section-lightning-tour
and hit "Run" under the example named "Get tokens, noun chunks & sentences".

You will get this:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-874373258c12> in <module>
      1 import spacy
      2 
----> 3 nlp = spacy.load('en_core_web_sm')
      4 doc = nlp(u"Peach emoji is where it has always been. Peach is the superior "
      5           u"emoji. It's outranking eggplant 🍑 ")

/srv/conda/lib/python3.6/site-packages/spacy/__init__.py in load(name, **overrides)
     19     if depr_path not in (True, False, None):
     20         deprecation_warning(Warnings.W001.format(path=depr_path))
---> 21     return util.load_model(name, **overrides)
     22 
     23 

/srv/conda/lib/python3.6/site-packages/spacy/util.py in load_model(name, **overrides)
    112             return load_model_from_link(name, **overrides)
    113         if is_package(name):  # installed as package
--> 114             return load_model_from_package(name, **overrides)
    115         if Path(name).exists():  # path to model data directory
    116             return load_model_from_path(Path(name), **overrides)

/srv/conda/lib/python3.6/site-packages/spacy/util.py in load_model_from_package(name, **overrides)
    133     """Load a model from an installed package."""
    134     cls = importlib.import_module(name)
--> 135     return cls.load(**overrides)
    136 
    137 

/srv/conda/lib/python3.6/site-packages/en_core_web_sm/__init__.py in load(**overrides)
     10 
     11 def load(**overrides):
---> 12     return load_model_from_init_py(__file__, **overrides)

/srv/conda/lib/python3.6/site-packages/spacy/util.py in load_model_from_init_py(init_file, **overrides)
    171     if not model_path.exists():
    172         raise IOError(Errors.E052.format(path=path2str(data_path)))
--> 173     return load_model_from_path(data_path, meta, **overrides)
    174 
    175 

/srv/conda/lib/python3.6/site-packages/spacy/util.py in load_model_from_path(model_path, meta, **overrides)
    154             component = nlp.create_pipe(name, config=config)
    155             nlp.add_pipe(component, name=name)
--> 156     return nlp.from_disk(model_path)
    157 
    158 

/srv/conda/lib/python3.6/site-packages/spacy/language.py in from_disk(self, path, disable)
    645         if not (path / 'vocab').exists():
    646             exclude['vocab'] = True
--> 647         util.from_disk(path, deserializers, exclude)
    648         self._path = path
    649         return self

/srv/conda/lib/python3.6/site-packages/spacy/util.py in from_disk(path, readers, exclude)
    509     for key, reader in readers.items():
    510         if key not in exclude:
--> 511             reader(path / key)
    512     return path
    513 

/srv/conda/lib/python3.6/site-packages/spacy/language.py in <lambda>(p, proc)
    641             if not hasattr(proc, 'to_disk'):
    642                 continue
--> 643             deserializers[name] = lambda p, proc=proc: proc.from_disk(p, vocab=False)
    644         exclude = {p: False for p in disable}
    645         if not (path / 'vocab').exists():

pipeline.pyx in spacy.pipeline.Tagger.from_disk()

/srv/conda/lib/python3.6/site-packages/spacy/util.py in from_disk(path, readers, exclude)
    509     for key, reader in readers.items():
    510         if key not in exclude:
--> 511             reader(path / key)
    512     return path
    513 

pipeline.pyx in spacy.pipeline.Tagger.from_disk.load_model()

pipeline.pyx in spacy.pipeline.Tagger.from_disk.load_model()

/srv/conda/lib/python3.6/site-packages/thinc/neural/_classes/model.py in from_bytes(self, bytes_data)
    333 
    334     def from_bytes(self, bytes_data):
--> 335         data = msgpack.loads(bytes_data, encoding='utf8')
    336         weights = data[b'weights']
    337         queue = [self]

/srv/conda/lib/python3.6/site-packages/msgpack_numpy.py in unpackb(packed, **kwargs)
    182     object_hook = kwargs.get('object_hook')
    183     kwargs['object_hook'] = functools.partial(decode, chain=object_hook)
--> 184     return _unpackb(packed, **kwargs)
    185 
    186 load = unpack

msgpack/_unpacker.pyx in msgpack._cmsgpack.unpackb()

ValueError: 1792000 exceeds max_bin_len(1048576)

**Comment by ines** [comment]
Ah, damn, thanks a lot! Looks like we need to update the spaCy version used in the Binder that those widgets. Fixing!

**Comment by ines** [comment]
Ok, just updated the [image](https://github.com/ines/spacy-io-binder) to the latest version and it should work again now. Make sure to do a hard reload – it should say "v2.0.18 · Python 3 · via Binder" in the top-right corner of the code box.
