### ISSUE TITLE
NER Model retrain failed

### ISSUE THREAD

**Issue by m0a0k0s** [explosion/spaCy#3081]
Hello.
 
I've tried to retrain existing model NER several ways and get very poor results - 20-40% for NER P/R/F after training.
Initially I tried to train it with very few examples and then to check that retraining is working I started to check with source training data.
I downloaded Wikiner training data and used english source with ~2 million words. I used this set for checking results with spacy evalute.
I loaded 5k sentences from Wikiner and train xx_core_web_sm model with recently updated code from 'Updating the Named Entity Recognizer' running 100 epoch.
After that I checked model on Wikiner en and get next results: NER P 24.43 NER R 38.11 NER F 29.77
I think this is ideal environment for retraining model check, because I used huge amount of different data that model was trained before (https://explosion.ai/blog/pseudo-rehearsal-catastrophic-forgetting). So why results so pure comparing to initial model giving 
NER P 83.47, NER R 82.58, NER F 83.02. Is it possible to use model retraining at all?

Training log output:
Losses {'ner': 15063.066990082474}
Losses {'ner': 11629.889364530538}
Losses {'ner': 10494.161782337735}
Losses {'ner': 9623.809613426754}
Losses {'ner': 9142.404902400052}
Losses {'ner': 8639.16547262442}
Losses {'ner': 8459.444947359047}
Losses {'ner': 7941.9721914940055}
Losses {'ner': 7669.527320367472}
Losses {'ner': 7608.771949650602}
Losses {'ner': 7327.176064978128}
Losses {'ner': 7075.115230791447}
Losses {'ner': 7004.6924016013345}
Losses {'ner': 6670.628368807335}
Losses {'ner': 6719.906040001562}
Losses {'ner': 6541.140641508225}
Losses {'ner': 6373.065197750666}
Losses {'ner': 6187.52255028603}
Losses {'ner': 6188.456346469873}
Losses {'ner': 5945.065942535327}
Losses {'ner': 5928.391734070782}
Losses {'ner': 5781.87251618183}
Losses {'ner': 5726.948722697338}
Losses {'ner': 5698.842095540828}
Losses {'ner': 5594.911816915247}
Losses {'ner': 5476.623139583039}
Losses {'ner': 5399.218761012343}
Losses {'ner': 5393.962858256385}
Losses {'ner': 5180.310507435423}
Losses {'ner': 5184.917663437949}
Losses {'ner': 5255.646767346439}
Losses {'ner': 5049.3438865619}
Losses {'ner': 5006.051801752485}
Losses {'ner': 5126.498390270155}
Losses {'ner': 4931.881132303227}
Losses {'ner': 4903.77620897046}
Losses {'ner': 4815.970680039226}
Losses {'ner': 4869.446105438782}
Losses {'ner': 4752.001489196585}
Losses {'ner': 4749.1452747045105}
Losses {'ner': 4684.490625249131}
Losses {'ner': 4686.65270677296}
Losses {'ner': 4652.0041196014845}
Losses {'ner': 4532.425295642297}
Losses {'ner': 4597.851694887338}
Losses {'ner': 4603.022341920004}
Losses {'ner': 4585.898221105738}
Losses {'ner': 4362.555321542932}
Losses {'ner': 4359.977057576009}
Losses {'ner': 4431.069526548233}
Losses {'ner': 4537.661763865623}
Losses {'ner': 4404.21058083518}
Losses {'ner': 4317.334126414206}
Losses {'ner': 4324.015868989382}
Losses {'ner': 4280.837153941132}
Losses {'ner': 4085.5653676661364}
Losses {'ner': 4206.998216835518}
Losses {'ner': 4150.090601174477}
Losses {'ner': 4223.763730703552}
Losses {'ner': 4037.0037649564206}
Losses {'ner': 4224.653343702988}
Losses {'ner': 4132.8999594737315}
Losses {'ner': 4145.879738595007}
Losses {'ner': 4018.5912377032187}
Losses {'ner': 4106.8283101004345}
Losses {'ner': 4036.8007862988065}
Losses {'ner': 3991.2323565833617}
Losses {'ner': 3950.298744434533}
Losses {'ner': 3975.29642784109}
Losses {'ner': 3863.9817495027673}
Losses {'ner': 3861.8948883296307}
Losses {'ner': 3948.0756895615227}
Losses {'ner': 3897.68691941695}
Losses {'ner': 3962.5085762721856}
Losses {'ner': 3941.8293609340326}
Losses {'ner': 3751.5198740399314}
Losses {'ner': 3844.6950125026724}
Losses {'ner': 3807.371357590735}
Losses {'ner': 3829.3558887053737}
Losses {'ner': 3887.934958377564}
Losses {'ner': 3787.0113654127767}
Losses {'ner': 3754.949522888718}
Losses {'ner': 3785.3073014897486}
Losses {'ner': 3744.398673595233}
Losses {'ner': 3710.48395772588}
Losses {'ner': 3735.278587472417}
Losses {'ner': 3714.209315601868}
Losses {'ner': 3800.8156407004385}
Losses {'ner': 3647.9371526723157}
Losses {'ner': 3708.170002996947}
Losses {'ner': 3580.7662130972803}
Losses {'ner': 3685.329725901364}
Losses {'ner': 3624.1697674026136}
Losses {'ner': 3605.2621245154864}
Losses {'ner': 3610.3301118786544}
Losses {'ner': 3412.9983680328114}
Losses {'ner': 3694.3831085043644}
Losses {'ner': 3587.3276896920747}
Losses {'ner': 3589.6796999717358}
Losses {'ner': 3562.5060677709325}

**Comment by m0a0k0s** [comment]
I've also added nlp.add_pipe(nlp.create_pipe('sentencizer')), because otherwise training fail on random run with error custom sentence boundary error

**Comment by m0a0k0s** [comment]
training file
[5k_train.zip](https://github.com/explosion/spaCy/files/2702629/5k_train.zip)

**Comment by honnibal** [comment]
Which version of spaCy are you using, and could you link to the script you used?

**Comment by ines** [comment]
> spaCy version 2.1.0a3

Just as a sanity check and to make sure it's not related to anything that's already fixed: Could you try rerunning your code with the new `spacy-nightly`, `v2.1.0a4`?

**Comment by m0a0k0s** [comment]
with v2.1.0a4 different bug. Could not find an optimal move to supervise the parser, although all label loaded:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.2.4\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2018.2.4\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2018.2.4\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2018.2.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/maxim.yakovlev/PycharmProjects/testner/train_ner.py", line 182, in <module>
    plac.call(main)
  File "C:\PythonVirtEnv\testner\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "C:\PythonVirtEnv\testner\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "C:/Users/maxim.yakovlev/PycharmProjects/testner/train_ner.py", line 93, in main
    losses=losses)
  File "C:\PythonVirtEnv\testner\lib\site-packages\spacy\language.py", line 452, in update
    proc.update(docs, golds, drop=drop, sgd=get_grads, losses=losses)
  File "nn_parser.pyx", line 390, in spacy.syntax.nn_parser.Parser.update
  File "nn_parser.pyx", line 492, in spacy.syntax.nn_parser.Parser._init_gold_batch
  File "transition_system.pyx", line 86, in spacy.syntax.transition_system.TransitionSystem.get_oracle_sequence
  File "transition_system.pyx", line 141, in spacy.syntax.transition_system.TransitionSystem.set_costs
ValueError: [E024] Could not find an optimal move to supervise the parser. Usually, this means the GoldParse was not correct. For example, are all labels added to the model?

**Comment by honnibal** [comment]
Could you try again with v2.1.0a7? We've fixed some bugs in the meantime that could have been behind this.

**Comment by honnibal** [comment]
Just pushed further fixes to develop. Should be good on the next nightly release, v2.1.0a9
