### ISSUE TITLE
Core norwegian (nb) model

### ISSUE THREAD

**Issue by jarib** [explosion/spaCy#3082]
All I want for Christmas is a core `nb` model for spacy. And we're getting close!

Last week the Language Technology Group at the University of Oslo released [NER annotations on top of the Norwegian Dependency Treebank](https://github.com/ltgoslo/norne). The [`nb` tag map](https://github.com/explosion/spaCy/blob/2dc6c52ccc5a0e5093c8b5e4f8cf4083b0de64dd/spacy/lang/nb/tag_map.py#L3-L10) is made for it, thanks to @katarkor. So there's now both UD/POS and NER data.

TODO:

- [x] Word vectors
  - Large pre-trained word embeddings are available in the [NLPL word embeddings repository](http://vectors.nlpl.eu/repository/)
  - There's [a paper that compares them](https://www.duo.uio.no/handle/10852/61756). 
  - Can they be used directly, or should we build new ones using a spacy-tokenized version of those corpora? 
- [x] Figure out tagger/parser issues
  - ~[Model appears to diverge](https://github.com/explosion/spaCy/pull/1882#issuecomment-449344534)? Both @ohenrik and I have run into this.~ Not a problem after upgrading to 2.1.x
  - ~[How come sentence segmentation is not working?](https://gist.github.com/jarib/cd51c0b15dd8421c9f607e860f796b08)~ Fixed by passing `-n 10` to `spacy convert` and removing `--gold-preproc` from `spacy train`.
- [ ] Write more tests for Norwegian

**Comment by ohenrik** [comment]
@jarib I managed to publish (an unpolished) repo with the model i Trained for Nudge (Tagbox.ai):
https://github.com/ohenrik/nb_news_ud_sm

I will hopefully get to clean this up a bit more.


Also regarding: **"How come sentence segmentation is not working?":**

This is because you need to activate this for a new model. You can make this automatic by adding "sbd" to the list of pipelines in the meta.json file for the model. [See example here](https://github.com/ohenrik/nb_news_ud_sm/blob/master/packaged_models/nb_core_sm_v2/nb_core_news_sm-1.0.0/meta.json#L7)

**Comment by ohenrik** [comment]
@jarib Also the model i link to above does not appear to diverge after X iterations. So i think the dataset used to traing the NER (+ DEP) model did not have this problem.

**Comment by jarib** [comment]
Ah, great! I'll have a look. 

Was the NER/DEP dataset you used based on an earlier version of https://github.com/ltgoslo/norne/, or something else?

**Comment by ohenrik** [comment]
I don’t know if the dataset has changed since I got access to it, I got it by email earlier this summer. So the repo might have newer data. However I had to combine train, dev and test data, randomize it and then split it into train, dev and test again. This was to avoid the training from getting stuck and producing wired results.

**Comment by jarib** [comment]
Ah, I see. The training doesn't get stuck with the latest version, but the NER F score is ~79. I might be doing something else wrong though. I'll publish the steps I've taken soon.

Also, it seems that existing models (e.g. `en_core_web_sm`) is able to do sentence segmentation without `sbd` in the pipeline, apparently based on the dependency parse… I guess the same should be possible for norwegian?

**Comment by honnibal** [comment]
@jarib Thanks for your work on this! We're still on holidays, but some quick answers in the meantime:

> Do I need to retrain word vectors?

Maybe not. If you run the tokenizer, have a look at which words end up without a vector. Also check word vector entries which never occur in your data, after tokenizing a bunch of text. For instance if you were doing this for English and you found you didn't have a vector for "n't", and you had a vectors-table entry for "can't", you'd know you have problems. Also, check that the word vectors are case sensitive. Case sensitive vectors generally work better with spaCy.

Finally, and perhaps most importantly. check that the vectors have a compatible license. We'd like the vectors to be CC-BY, MIT or BSD licensed. If they're CC-BY-SA, CC-BY-NC or GPL licensed, they'll restrict how we can license the final model.

> Tagger/NER diverges

This seems to be resolved? About the accuracy plateauing, well, it has to top out somewhere right? You can try fiddling with the hyper-parameters maybe, to see if you can get better performance. Another trick is to run cross-fold training, and record the accuracy of each sentence in the training data across the different folds. Have a look at sentences in the training data which are consistently predicted poorly. Sometimes you'll find these sentences are just...bad, and accuracy might go up if these bad sentences are removed.

> Sentence boundary detection

Make sure you're setting the `-n` flag when you're converting the data, so that you have some documents with multiple sentences in them. This allows the parser to learn to divide the sentences. If you only have one sentence per document in the training data, the parser never learns to use the `Break` transition, and so accuracy on multi-sentence documents is very low.

**Comment by jarib** [comment]
@honnibal Thanks for the suggestions!

The problem with the divergence / tag accuracy dropping appears to be gone after I switched to spacy 2.1.0a4. 

I have some code running right now that does goes through all the Norwegian Bokmål word embedding models from the [NLPL repository](http://vectors.nlpl.eu/repository/) to see which one gives the best results. I haven't found much license information for those, but I'll look into it.

The results look promising to my eyes. Here's the output from one of the large (>2GB) models. I've also put up [the scripts I've used](https://github.com/jarib/spacy-nb).

```
=========
Model   0
=========
        Path: data/vectors-all/11-100

Vectors
-------
        Algorithm: Gensim Continuous Skipgram
        Corpus   : Norsk Aviskorpus + NoWaC + NBDigital (lemmatized=False, case preserved=True, tokens=3028545953)
        Vectors  : dimensions=100, window=5, iterations=5, vocab size=4480046

Training
--------
        UAS    NER P. NER R. NER F. Tag %  Token %
        86.532 86.734 87.253 86.993 94.617 100.000
        90.355 89.247 89.408 89.327 96.446 100.000
        89.914 89.653 89.707 89.680 96.361 100.000
        90.173 89.928 89.767 89.847 96.427 100.000
        90.593 88.889 89.048 88.969 96.641 100.000
        90.581 88.611 88.929 88.769 96.646 100.000
        89.569 89.467 89.467 89.467 96.210 100.000
        89.274 89.408 89.408 89.408 96.076 100.000
        90.267 88.949 89.108 89.028 96.564 100.000
        88.150 88.590 88.749 88.670 95.462 100.000
        90.543 89.121 89.228 89.175 96.638 100.000
        90.593 88.989 88.989 88.989 96.616 100.000
        90.638 88.439 88.809 88.623 96.624 100.000
        88.635 89.348 89.348 89.348 95.870 100.000
        90.618 89.241 89.348 89.294 96.613 100.000

Best
----
        Path: data/vectors-all/11-100/training/model-best
        Size: 2282 MB

        UAS    NER P. NER R. NER F. Tag %  Token %
        90.618 89.241 89.348 89.294 96.613 100.000

Evaluate
--------


         Time      3.72 s
         Words     30034
         Words/s   8079
         TOK       100.00
         POS       96.01
         UAS       90.48
         LAS       88.16
         NER P     85.24
         NER R     86.73
         NER F     85.98
```

**Comment by jarib** [comment]
The vectors are licensed CC-BY. For attribution, these publications can be cited:

Stadsnes, Øvrelid, & Velldal (2018)
http://ojs.bibsys.no/index.php/NIK/article/view/490/

Fares, Kutuzov, Oepen, & Velldal (2017)
http://www.ep.liu.se/ecp/article.asp?issue=131&article=037

**Comment by honnibal** [comment]
Numbers look great! I wonder exactly which change made the difference...Possibly just the different hyper-parameters, especially the narrower widths (which decreases overfitting).

It sounds like there's no barrier to adding this. I just have to add the data files to our corpora image.

**Comment by honnibal** [comment]
Thanks for running all this! Just to be clear, did you retrain with the new vectors? You can't really compare the accuracy by swapping in the vectors at runtime, because then all you're really measuring is how similar each vectors are to the one the model is trained with.

I think it would also be very useful to train an `sm` model to check how much improvement the vectors really make. Generally using `--prune-vectors 20000` (this is the setting we've been using for `md` models) gives a pretty good balance of accuracy and size.

**Comment by jarib** [comment]
I did retrain with the new vectors. I don't know spacy's internals well enough to dare swapping anything out :)

I'll train one model without vectors (= `sm`?) and one with pruning, and post the results here.

**Comment by honnibal** [comment]
Okay, great!

**Comment by jarib** [comment]
Here I've pruned the vectors from the third row in the table above (fastText skipgram on the "Norsk Aviskorpus + NoWaC" corpus) to 20 000 words. The final model ends up at 454 MB.

When I use `--prune-vectors 20000` I get this warning: `Warning: Unnamed vectors -- this won't allow multiple vectors models to be loaded. (Shape: (20000, 100))`. That doesn't happen if I remove the flag. Not sure if it matters.

##### Training

```
Itn    Dep Loss    NER Loss      UAS    NER P    NER R    NER F    Tag %  Token %  CPU WPS  GPU WPS
---  ----------  ----------  -------  -------  -------  -------  -------  -------  -------  -------
  0  159537.223    6402.911   85.781   82.008   82.107   82.057   93.723  100.000     8352     8415
  1  114886.809    3331.395   87.663   84.703   84.500   84.602   94.790  100.000     8268     8287
  2  102142.415    2465.607   88.314   84.886   85.039   84.963   95.278  100.000     8473     8422
  3   93845.905    1858.885   88.637   85.561   85.817   85.689   95.544  100.000     8630     8464
  4   87807.250    1485.389   88.958   85.697   86.056   85.876   95.728  100.000     8603     8586
  5   82416.232    1216.918   89.311   85.791   85.996   85.894   95.785  100.000     8559     8559
  6   78299.269    1105.943   89.598   85.629   85.577   85.603   95.900  100.000     8644     8627
  7   74927.845     946.399   89.746   85.117   85.218   85.167   95.914  100.000     8620     8647
  8   72173.234     775.656   89.912   84.455   84.859   84.657   95.974  100.000     8555     8532
  9   69231.955     732.922   90.027   83.750   84.201   83.975   96.068  100.000     8597     8571
 10   66741.832     681.178   90.077   84.223   84.979   84.599   96.114  100.000     8800     8773
 11   64863.437     592.628   90.235   85.296   85.398   85.347   96.114  100.000     8757     8763
 12   62994.504     544.747   90.391   85.084   85.338   85.211   96.150  100.000     8752     8711
 13   60421.970     527.930   90.435   85.305   85.458   85.381   96.155  100.000     8696     8727
 14   59108.179     483.949   90.481   84.123   84.979   84.549   96.172  100.000     8767     8711
 15   57507.565     414.018   90.446   84.734   85.697   85.213   96.240  100.000     8747     8665
 16   55917.333     445.512   90.446   84.811   85.877   85.340   96.229  100.000     8567     8583
 17   54140.529     401.599   90.405   84.734   85.697   85.213   96.235  100.000     8735     8656
 18   53235.531     345.128   90.460   84.479   85.338   84.906   96.262  100.000     8581     8534
 19   51425.662     370.436   90.510   84.438   85.398   84.915   96.271  100.000     8464     8546
 20   50373.646     343.464   90.591   84.830   85.338   85.084   96.262  100.000     8549     8555
 21   49415.185     337.757   90.644   84.551   85.159   84.854   96.224  100.000     8573     8564
 22   48312.131     274.937   90.756   83.589   84.740   84.160   96.221  100.000     8560     8563
 23   47543.626     361.788   90.738   84.360   85.218   84.787   96.224  100.000     8586     8547
 24   47092.949     330.405   90.780   85.459   85.817   85.638   96.210  100.000     8524     8487
 25   45720.017     282.577   90.744   85.629   85.937   85.783   96.232  100.000     8560     8591
 26   44934.282     250.263   90.656   84.816   85.577   85.195   96.260  100.000     8533     8538
 27   43830.520     255.366   90.576   84.456   85.518   84.984   96.284  100.000     8520     8543
 28   43344.429     284.323   90.686   84.834   85.697   85.263   96.295  100.000     8682     8589
 29   43504.905     286.349   90.699   84.775   85.637   85.204   96.287  100.000     8699     8710
```

##### Evaluation

```
Time      3.46 s
Words     29847
Words/s   8620
TOK       100.00
POS       95.64
UAS       90.25
LAS       87.93
NER P     82.96
NER R     84.79
NER F     83.87
```

**Comment by jarib** [comment]
So, comparing size and accuracy from `spacy evaluate`:

| Name | Size | TOK | POS | UAS | LAS | NER P | NER R | NER F |
| ---- | ---- |-----|----| --- | --- | ------| ----- | ----- |
| sm   | 15 MB | 100.00 | 94.66 | 88.97 |86.30|71.64|70.54|71.08|
| md   | 454 MB | 100.00 | 95.64 | 90.25 | 87.93 | 82.96| 84.79| 83.87 |
| lg   | 1308 MB | 100.00 | 95.96 | 90.42 | 88.30| 85.29 | 86.48 | 85.88 |

**Comment by jarib** [comment]
I'm unable to get sentence segmentation to work, even after changing to `spacy convert -n 10 [...]`. I do the conversion [here](https://github.com/jarib/spacy-nb/blob/21499de9f299217ad623274fa3bb182d8fffff9f/tools/download.norne.sh#L14).

**Comment by honnibal** [comment]
What happens? You're not passing `-G` during training are you?

The gap between the `sm` and `md` models is interesting. If you want you could experiment with `spacy pretrain` for this...It takes a jsonl file, formatted with each line being a dict like `{"text": "..."}`. This outputs pre-trained weights for the CNN. On small datasets, it can have a big improvement in accuracy. It's best to run it with at least 1 billion words of text, but even if you only have like 50-100 million it should still help

**Comment by jarib** [comment]
You're right, I was passing `-G`! Not sure where I got that from. I guess it could be clearer in the docs when it is or isn't appropriate.

I'll try to do the sm/md/lg training again without `-G`. The big table above with all the pre-trained vectors was done without `-G`, luckily (command [here](https://github.com/jarib/spacy-nb/blob/21499de9f299217ad623274fa3bb182d8fffff9f/tools/test_nlpl_vectors.py#L138-L154)).

I'll try `spacy pretrain` as well.

**Comment by jarib** [comment]
Updated results, without `-G`. Sentence segmentation now works well with all of them.

| Name | Size | TOK | POS | UAS | LAS | NER P | NER R | NER F |
| ---- | ---- |-----|----| --- | --- | ------| ----- | ----- |
| sm   | 15 MB | 100.00 | 94.60 | 88.59| 86.10 | 71.96 | 70.54 | 71.24 |
| md   | 454 MB | 100.00 | 95.59 | 89.88 | 87.65 | 83.15 | 84.50 | 83.82 |
| lg   | 1308 MB | 100.00 | 95.83 | 90.44 | 88.20 | 83.92 | 85.89 | 84.89 | 


<details>
  <summary><strong>sm</strong> training output</summary>

```
Itn    Dep Loss    NER Loss      UAS    NER P    NER R    NER F    Tag %  Token %  CPU WPS  GPU WPS
---  ----------  ----------  -------  -------  -------  -------  -------  -------  -------  -------
  0  140328.007    9713.144   81.386   69.818   66.727   68.237   91.036  100.000     6500     6424
  1   95301.408    5064.493   84.296   76.306   75.165   75.731   92.887  100.000     6197     6254
  2   81858.447    3635.719   85.439   77.488   76.421   76.951   93.682  100.000    10615    10428
  3   74299.650    2738.703   86.115   77.778   77.080   77.427   94.140  100.000    10497    10431
  4   68887.638    2227.522   86.737   77.544   77.080   77.311   94.392  100.000    10404    10339
  5   64298.027    1766.455   87.304   77.858   77.858   77.858   94.617  100.000     7621     6241
  6   61905.430    1505.741   87.480   78.138   77.858   77.998   94.719  100.000    10538     9815
  7   59213.529    1273.619   87.572   77.798   77.798   77.798   94.814  100.000     6155     6155
  8   56951.210    1104.528   87.714   77.564   77.379   77.472   94.930  100.000    10223    10270
  9   54658.723    1079.417   87.897   77.624   77.439   77.531   94.927  100.000     6292     6227
 10   52977.966     932.116   88.002   77.379   77.379   77.379   95.017  100.000     6189     6162
 11   51874.855     800.744   88.200   77.738   77.319   77.528   95.135  100.000     6233     6244
 12   50026.206     736.797   88.311   77.281   76.541   76.909   95.176  100.000    10411     7271
 13   49049.945     712.090   88.436   77.221   76.481   76.849   95.229  100.000    10293    10285
 14   47388.001     647.277   88.573   76.960   76.361   76.660   95.253  100.000     7194     6375
 15   47097.322     628.981   88.525   76.354   75.943   76.148   95.292  100.000     6091     6088
 16   44984.461     606.129   88.667   76.881   76.421   76.651   95.256  100.000    10292    10445
 17   44119.642     525.098   88.698   77.114   76.421   76.766   95.286  100.000     6647     6485
 18   43658.052     525.569   88.771   76.891   76.062   76.474   95.330  100.000    10247    10207
 19   42470.731     474.503   88.788   76.584   75.943   76.262   95.294  100.000     6089     6114
 20   41664.124     553.536   88.923   76.584   75.943   76.262   95.297  100.000    10200    10213
 21   41395.161     510.137   88.807   77.549   76.481   77.011   95.325  100.000    10207    10296
 22   40159.752     407.179   88.863   77.529   76.601   77.062   95.308  100.000     6658     6288
 23   39051.428     430.688   89.041   77.556   76.721   77.136   95.346  100.000    10146    10207
 24   38466.165     380.242   89.031   77.300   76.421   76.858   95.399  100.000     9764    10136
 25   37894.168     376.259   89.055   77.300   76.421   76.858   95.429  100.000     7419    10290
 26   37924.853     404.705   89.030   76.770   75.943   76.354   95.407  100.000     6100     6221
 27   36738.349     431.608   89.048   77.039   76.302   76.669   95.412  100.000     7700     6379
 28   36492.987     394.110   89.025   77.179   76.302   76.738   95.442  100.000    10228    10311
 29   35964.157     323.550   89.177   76.784   76.002   76.391   95.442  100.000     6265     6719
```

</details>

<details>
  <summary><strong>md</strong> training output</summary>

```
Itn    Dep Loss    NER Loss      UAS    NER P    NER R    NER F    Tag %  Token %  CPU WPS  GPU WPS
---  ----------  ----------  -------  -------  -------  -------  -------  -------  -------  -------
  0  125910.684    7581.375   84.740   82.388   81.747   82.067   93.613  100.000     6890     6078
  1   82290.664    3598.582   86.767   83.106   83.902   83.502   94.697  100.000     6495     6439
  2   70896.668    2724.962   87.885   85.312   85.159   85.235   95.204  100.000     9421     5991
  3   65209.235    2009.910   88.452   85.203   85.458   85.330   95.467  100.000     5999     6069
  4   59814.261    1610.226   88.626   85.646   86.056   85.851   95.582  100.000     5974     6042
  5   56224.491    1380.671   88.951   85.774   86.595   86.182   95.747  100.000    10059     6041
  6   54198.211    1154.143   89.329   85.207   86.176   85.689   95.878  100.000     6044    10186
  7   52108.301     985.541   89.417   86.012   86.475   86.243   95.903  100.000     6044     7271
  8   49958.169     845.080   89.650   85.859   86.116   85.987   95.988  100.000     9654     6023
  9   48384.992     719.396   89.924   85.748   86.056   85.902   96.016  100.000     6327    10027
 10   46380.225     676.546   89.960   85.510   85.817   85.663   96.024  100.000    10218     9840
 11   45604.224     698.995   89.960   85.723   85.877   85.800   96.057  100.000    10239    10192
 12   44398.147     574.467   90.036   85.603   85.757   85.680   96.024  100.000    10287    10000
 13   43337.924     481.058   90.052   85.569   85.877   85.723   96.090  100.000    10231    10321
 14   42124.992     494.542   90.032   86.139   86.655   86.396   96.131  100.000    10270    10062
 15   40621.568     416.546   90.129   85.841   86.715   86.276   96.136  100.000    10062    10072
 16   39310.532     471.311   90.213   85.697   86.774   86.233   96.139  100.000     9945    10052
 17   39134.968     373.413   90.343   85.883   87.014   86.445   96.109  100.000    10016     9996
 18   38455.480     439.943   90.360   85.816   86.894   86.351   96.095  100.000    10251    10142
 19   37404.740     390.323   90.429   85.782   86.655   86.216   96.139  100.000    10185    10144
 20   36686.148     394.971   90.478   85.833   86.655   86.242   96.131  100.000    10234    10144
 21   36009.123     364.551   90.485   85.917   86.894   86.403   96.169  100.000    10290    10552
 22   34603.331     320.468   90.496   85.630   86.655   86.139   96.153  100.000    10210    10540
 23   34493.734     321.966   90.537   85.529   86.655   86.088   96.180  100.000    10087    10498
 24   33816.817     337.003   90.561   84.979   85.996   85.485   96.164  100.000    10153    10104
 25   33440.944     295.308   90.430   85.604   86.475   86.038   96.199  100.000    10097    10169
 26   32788.472     311.987   90.421   85.258   86.176   85.714   96.166  100.000    10606    10346
 27   32166.413     275.568   90.515   85.264   85.877   85.569   96.112  100.000    10572    10243
 28   31914.538     270.512   90.584   85.110   85.518   85.313   96.081  100.000    10511    10122
 29   31567.351     249.013   90.507   85.348   85.757   85.552   96.101  100.000    10185     9963
 ```
 </details>

<details>
  <summary><strong>lg</strong> training output</summary>

```
Itn    Dep Loss    NER Loss      UAS    NER P    NER R    NER F    Tag %  Token %  CPU WPS  GPU WPS
---  ----------  ----------  -------  -------  -------  -------  -------  -------  -------  -------
  0  124258.144    7236.655   85.636   83.533   83.483   83.508   94.173  100.000     6226     6147
  1   80057.797    3228.932   87.450   86.283   86.954   86.617   95.429  100.000     6193     6244
  2   69706.663    2411.335   88.292   87.195   87.612   87.403   95.840  100.000     6194     6421
  3   63253.803    1862.183   88.854   88.067   88.330   88.198   96.142  100.000     8149     7202
  4   58398.192    1489.227   89.274   87.709   87.971   87.840   96.216  100.000     9753     9844
  5   55081.437    1233.046   89.604   88.067   88.330   88.198   96.317  100.000     5905     6208
  6   53114.583    1059.013   89.955   88.365   88.630   88.497   96.435  100.000     5708     5975
  7   50720.677     910.304   90.040   88.148   88.570   88.358   96.408  100.000    10395     9472
  8   48330.692     782.987   90.223   87.969   88.390   88.179   96.446  100.000     9343    10140
  9   47155.682     705.529   90.446   88.109   88.689   88.398   96.441  100.000     5594    10007
 10   45750.049     672.297   90.535   87.344   87.971   87.657   96.452  100.000     6098     6251
 11   44437.575     649.625   90.549   87.011   87.792   87.399   96.512  100.000    10378     6162
 12   43094.576     514.990   90.624   87.034   87.971   87.500   96.512  100.000     6111     5891
 13   41935.703     485.979   90.673   87.537   88.270   87.902   96.534  100.000     6170     5911
 14   40887.881     468.094   90.713   87.722   88.510   88.114   96.556  100.000     6033     6344
 15   39608.918     409.788   90.678   87.864   88.390   88.126   96.564  100.000    10087     7881
 16   38723.232     419.580   90.671   87.969   88.390   88.179   96.559  100.000     9331    10132
 17   37933.653     394.874   90.613   87.388   87.911   87.649   96.545  100.000     5948     5941
 18   37256.559     369.788   90.584   87.329   87.852   87.589   96.578  100.000     9515     9652
 19   36489.335     305.808   90.660   87.440   87.911   87.675   96.572  100.000     9344     9432
 20   35347.381     346.268   90.610   87.716   88.031   87.873   96.586  100.000     9378     9389
 21   34922.059     353.310   90.769   87.657   87.971   87.814   96.591  100.000    10213     9547
 22   34012.171     336.559   90.788   88.088   88.510   88.299   96.594  100.000    10272     9369
 23   33653.177     345.451   90.734   88.186   88.450   88.318   96.556  100.000    10148     9369
 24   33334.910     293.602   90.861   88.119   88.330   88.225   96.559  100.000    10321     9225
 25   32328.676     294.129   90.823   88.158   88.211   88.184   96.575  100.000    10163     9312
 26   31813.067     250.583   90.742   88.112   88.270   88.191   96.586  100.000     9302    10124
 27   31284.447     262.157   90.755   88.450   88.450   88.450   96.589  100.000     5931    10207
 28   31013.342     284.829   90.707   88.084   88.031   88.057   96.594  100.000     9286     9425
 29   30368.747     252.931   90.773   87.926   88.031   87.978   96.600  100.000    10066     9395
```
</details>

**Comment by jarib** [comment]
I've tried to improve the `sm` model with pretraining on a subset (~250 million words) of the Norwegian News Corpus.

| Name | Pretrained | Size   | POS | UAS | LAS | NER P | NER R | NER F |
| ---- | ---------- | ----   |----| --- | --- | ------| ----- | ----- |
| sm   | No         | 15 MB  | 94.60 | 88.59 | 86.10 | 71.96 | 70.54 | 71.24 |
| sm   | Yes        | 15 MB  | 95.07 | 90.14 | 87.82 | 78.92 | 78.69 | 78.81 |

I chose the subset of the corpus that was easy to convert into the correct format, so it can probably be further improved by pretraining on [the full corpus](https://www.nb.no/sprakbanken/show?serial=oai%3Anb.no%3Asbr-4&lang=nb), possibly in combination with [NoWaC](https://www.hf.uio.no/iln/om/organisasjon/tekstlab/prosjekter/nowac/) (700 million tokens). The vector model used for `md` and `lg` is trained on these corpora.

I ran `spacy pretrain` with the default settings. Each iteration takes about 2.5 hours (30k words per second) on my hardware, so the default 1000 iterations seems a bit much for me at the moment. The scores above is from the 7th iteration, randomly chosen.

**Comment by ohenrik** [comment]
What type of hardware do you have? I have an idle 1080ti graphics card that might speed things up a bit, but not sure if you already are using something similar. Let me know, and i can set it up and run it for you on my machine.

**Comment by jarib** [comment]
@ohenrik I've been using `p2.xlarge` instance from AWS. I can share the `.jsonl` file used for pretraining if you want to give it a try.

**Comment by ohenrik** [comment]
I can give it a try :) Just share what i need to set it up.

**Comment by jarib** [comment]
@ohenrik To try pretraining:

1. Download and extract [the NNC subset](https://github.com/jarib/spacy-nb/releases/download/v0.1/nnc-subset.tgz) to e.g. `data/nnc.jsonl`
1. Download the extract the [large model](https://github.com/jarib/spacy-nb/releases/download/v0.1/nb-lg.tgz) (vectors) to e.g. `data/nb-lg`
1. Run `python -m spacy pretrain data/nnc.jsonl data/nb-lg/ data/pretraining`

However I think we should eventually try a larger corpus in order to improve the `sm` model.

@honnibal Can `spacy pretrain` improve the `lg` model as well, or is that redundant?

**Comment by ohenrik** [comment]
@jarib should I convert the contents the ner_files folder i downloaded to jsonl using spacy? i did not get any files named nnc.jsonl (or jsonl files in general)

**Comment by jarib** [comment]
@ohenrik  [This file](https://github.com/jarib/spacy-nb/releases/download/v0.1/nnc-subset.tgz) contains `data/nnc.jsonl`.

**Comment by ohenrik** [comment]
Strange... I'm not sure what happened, but i somehow mixed up the zip files with some old NER i downloaded back on 17. desember :p So no wonder nothing made sense. I started training it now, will give an update soon when i know more about the speed

**Comment by jarib** [comment]
The NoWaC corpus is 700 million tokens and as such a good candidate for pretraining. But it's licensed CC BY-NC-SA. Will pretraining on this corpus affect the licensing of the final model?

**Comment by honnibal** [comment]
Still really keen to get full Norwegian support :). And also quite pleased with the pretraining performance!

We can merge this with the "Adding models" master thread, #3056 . Could you update once you have the licensing figured out?

**Comment by jarib** [comment]
@honnibal AFAICT there’s only a licensing issue if we want to use the NoWaC corpus for pretraining, The group who published the NLPL vectors used above confirmed to me that they are licensed CC-BY. 

I can try to negotiate special terms for NoWaC, or look for an alternative corpus that can be used for pretraining, if that’s a requirement for getting the Norwegian model included.

**Comment by honnibal** [comment]
Almost finished with the v2.1 release. After that I'll be updating the datasets in the model training pipeline, which should let us publish the official `nb` models 🎉
