### ISSUE TITLE
Transfer Learning Spacy word embeddings

### ISSUE THREAD

**Issue by ctrado18** [explosion/spaCy#3086]
Hi,

I would like to know if it is possible to do transfer learning and train spacy word embeddings on new text data for my specific domain?

Merry Christmas! 😄

**Comment by honnibal** [comment]
You can train a model with your own word embeddings, but you'll need to retrain. You can't plug in new word embeddings into a model trained with different embeddings --- that won't work.

**Comment by ctrado18** [comment]
Thanks. I meant with transfer leartning to fine tune the standard word embedding model (eg. german_md) with my own data? So you have the old embeddings together with new ones? That is how undertsand the concept of transfer learning.

> You can train a model with your own word embeddings, but you'll need to retrain.

yes but I still want the old ones
