### ISSUE TITLE
Use of Custom Model withouth any inbuilt language model

### ISSUE THREAD

**Issue by SuyogShah** [explosion/spaCy#3088]
Hi There,

Can someone please let me know below

Is it possible to have our own model without using any inbuilt language model for NER ?
If yes, how can we do ? Please provide any relevant url to refer?
Also, I have to match set of possible values (user names, user id, account names, account id) Is it possible to apply multiple match phraser on given text and find custom entity? How to achieve this ?
My use case is basically rule based (multiple rules) + statistical model combination.

**Comment by svlandeg** [comment]
I haven't done something like this myself yet, but here are some links to the docs to get you started: 
- https://spacy.io/usage/linguistic-features#section-named-entities
- https://spacy.io/usage/training#section-ner

**Comment by ines** [comment]
>  Also, I have to match set of possible values (user names, user id, account names, account id) Is it possible to apply multiple match phraser on given text and find custom entity? How to achieve this ?

To addd to the comment above, you can also use the `Matcher` and `PhraseMatcher` for rule-based entity extraction. The `Matcher` lets you write abstract token-based rules, while the `PhraseMatcher` lets you match large terminology lists.

* Rule-based matching: https://spacy.io/usage/linguistic-features#section-rule-based-matching
* Example of a custom component using the `Matcher` / `PhraseMatcher` to add entities to `doc.ents` manually: https://spacy.io/usage/processing-pipelines#custom-components

The upcoming version will also introduce the `EntityRuler` that makes rule-based named entity recoginition (and a combination of rule-based and statistical NER) simpler. You can read more about this here: #2513. Note that this component is currently only available for testing in the alpha version (installable as `spacy-nightly`).
