### ISSUE TITLE
How to use OR / AND operators while writing custom rules in Spacy's Matcher??? 

### ISSUE THREAD

**Issue by anustupdas** [explosion/spaCy#3091]
## Feature description

If I want to match a pattern like this :
{Token.length<3, Token.string!="Rn", Token.string!="Art" } If this is a rule how can I Write it in Spacy?

pattern = [{'LENGTH': >3, 'ORTH': 'RN', 'ORTH': 'Art', 'OP': '!'}]  
matcher.add('HelloWorld', None, pattern)

In the above pattern 
1) LENGTH': >3 is not supported
2) Adding ORTH more than once is not recognized by spacy
3) 'OP' operator do not work for multiple attributes mentioned in the Rule.

**Comment by rbhambriiit** [comment]
Can you try passing this as list of dicts instead of one dict?

**Comment by ines** [comment]
> LENGTH': >3 is not supported
> Adding ORTH more than once is not recognized by spacy

The patterns are written as Python lists containing Python dictionaries – so they also need to be valid Python. `>3` is not an accepted dictionary value in Python (if you type `{"test": >3}`, you'll see a syntax error). Similarly, if a dictionary has duplicate keys, the previous one will be overwritten, so `{"test": 1, "test": 2}` will be interpreted as `{"test": 2}`. Those are mostly Python syntax specifics and not necessarily limitations of spaCy.

That said, the logic you're trying to express here currently isn't supported by the rule-based `Matcher`. The new `Matcher` API updates coming in `v2.1.x` should make this possible, though – see #1971 for the spec and how the syntax will work. (Note that the issue I linked is only the *proposal* and describes the planned implementation. None of the code examples work out-of-the-box yet – but you'll be able to test the update in a future release of `spacy-nightly`.) 

> 'OP' operator do not work for multiple attributes mentioned in the Rule.

The `OP` value refers to the *entire token* described by the dictionary. So if you pattern describes a token of a certain length with a certain part-of-speech tag, that *type of token* will be matched according to the operator.
