### ISSUE TITLE
doc.ents is returnning an empty list

### ISSUE THREAD

**Issue by leungi** [explosion/spaCy#3097]
With reference to #2864 and #1936, facing the issue.

```
>>> import spacy
>>> nlp = spacy.load('en_core_web_sm')
>>> doc = nlp(u'Apple is looking at buying U.K. startup for $1 billion')
>>> print(" ".join([token.lemma_ for token in doc]))
Apple be look at buy U.K. startup for $ 1 billion

# lemma works

>>> for ent in doc.ents:
...   print(ent.text, ent.start_char, ent.end_char, ent.label_)
...
>>> doc.ents
()

# NER fails
>>>
```

## Info about spaCy
* **spaCy version:** 2.0.18
* **Platform:** Windows-7-6.1.7601-SP1
* **Python version:** 3.6.6
* **Models:** en_default

## Your Environment
{'commit_hash': '523ed2fe5',
 'commit_source': 'installation',
 'default_encoding': 'utf-8',
 'ipython_path': 'C:\\ProgramData\\Anaconda3\\envs\\mySpacy\\lib\\site-packages\
\IPython',
 'ipython_version': '7.2.0',
 'os_name': 'nt',
 'platform': 'Windows-7-6.1.7601-SP1',
 'sys_executable': 'C:\\ProgramData\\Anaconda3\\envs\\mySpacy\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '3.6.6 | packaged by conda-forge | (default, Jul 26 2018, '
                '11:48:23) [MSC v.1900 64 bit (AMD64)]'}

**Comment by rbhambriiit** [comment]
Maybe it's a generator and you exhausted it earlier.

Try without using the lemma. Or make everything as list?

**Comment by leungi** [comment]
@rbhambriiit, thanks for prompt response.

To your question, I don't believe it's a generator object. This is confirmed by calling doc.ents prior to lemmatizing, and it still yields and empty list.

**Comment by leungi** [comment]
@ines, thanks for prompt response!

`python -m spacy validate` always gives the well-documented (but hard to solve) SSL issue :), so I went with your suggestion to check model compatibility; it solved the problem :+1: 

I was using `en_core_web_sm` 1.2.0, and upgrading to 2.0.0 seems to be the solution when using `spacy` > 2.0*.

Appreciate the work and the tireless support!
