### ISSUE TITLE
can we use our method to split sentence into words in the spacy pos_tag function?

### ISSUE THREAD

**Issue by wangwang110** [explosion/spaCy#3098]
## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by honnibal** [comment]
You can create a `Doc` object with your own tokenization by passing in the `words` keyword argument, which takes a list of strings. See here: https://spacy.io/api/doc

**Comment by wangwang110** [comment]
> You can create a `Doc` object with your own tokenization by passing in the `words` keyword argument, which takes a list of strings. See here: https://spacy.io/api/doc

but I want to use the pos_tag function, what should I do?
