### ISSUE TITLE
Not able to load English language module of spacy with spacy.load('en')

### ISSUE THREAD

**Issue by Sanjaysaini24** [explosion/spaCy#3102]
I am not able to load English module in the jupyter notebook with below code-
I have installed python version 2.7.15, 3.6.7, 3.7.1 and Anaconda3 5.3.1

!pip install spacy
import spacy
spacy.load('en')

I have downloaded the spacy package with (!pip install spacy) and English package with (python spacy download en) in anaconda prompt

OSError Traceback (most recent call last) in () ----> 1 spacy.load('en')

C:\ProgramData\Anaconda3\lib\site-packages\spacy__init__.py in load(name, **overrides) 19 if depr_path not in (True, False, None): 20 deprecation_warning(Warnings.W001.format(path=depr_path)) ---> 21 return util.load_model(name, **overrides) 22 23

C:\ProgramData\Anaconda3\lib\site-packages\spacy\util.py in load_model(name, **overrides) 117 elif hasattr(name, 'exists'): # Path or Path-like to model data 118 return load_model_from_path(name, **overrides) --> 119 raise IOError(Errors.E050.format(name=name)) 120 121

OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

**Comment by Sanjaysaini24** [comment]
Thanks @ines for your responce

below is my comment-

If I try with nlp = spacy.load('en_core_web_sm') it works but when I move forward in my program and try to remove stopwords it shows error.
My program code-

`from nltk.corpus import stopwords 
from nltk.stem.wordnet import WordNetLemmatizer
import string
stop = set(stopwords.words('english'))
stop.add('[0-9]')
exclude = set(string.punctuation)
exclude.add(0-9)
lemma = WordNetLemmatizer()
def clean(doc):
    stop_free = " ".join([i for i in doc.lower().split() if i not in stop])
    punc_free = ''.join(ch for ch in stop_free if ch not in exclude)
    normalized = " ".join(lemma.lemmatize(word) for word in punc_free.split())
    return normalized

doc_clean = [clean(doc).split() for doc in texts] `

Error MSG -

---------------------------------------------------------------------------
LookupError                               Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\nltk\corpus\util.py in __load(self)
     79             except LookupError as e:
---> 80                 try: root = nltk.data.find('{}/{}'.format(self.subdir, zip_name))
     81                 except LookupError: raise e

C:\ProgramData\Anaconda3\lib\site-packages\nltk\data.py in find(resource_name, paths)
    674     resource_not_found = '\n%s\n%s\n%s\n' % (sep, msg, sep)
--> 675     raise LookupError(resource_not_found)
    676 

LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  Searched in:
    - 'C:\\Users\\QD0203/nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
    - 'C:\\ProgramData\\Anaconda3\\nltk_data'
    - 'C:\\ProgramData\\Anaconda3\\share\\nltk_data'
    - 'C:\\ProgramData\\Anaconda3\\lib\\nltk_data'
    - 'C:\\Users\\QD0203\\AppData\\Roaming\\nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

LookupError                               Traceback (most recent call last)
<ipython-input-38-00b8fd2e2e1d> in <module>()
      2 from nltk.stem.wordnet import WordNetLemmatizer
      3 import string
----> 4 stop = set(stopwords.words('english'))
      5 stop.add('[0-9]')
      6 exclude = set(string.punctuation)

C:\ProgramData\Anaconda3\lib\site-packages\nltk\corpus\util.py in __getattr__(self, attr)
    114             raise AttributeError("LazyCorpusLoader object has no attribute '__bases__'")
    115 
--> 116         self.__load()
    117         # This looks circular, but its not, since __load() changes our
    118         # __class__ to something new:

C:\ProgramData\Anaconda3\lib\site-packages\nltk\corpus\util.py in __load(self)
     79             except LookupError as e:
     80                 try: root = nltk.data.find('{}/{}'.format(self.subdir, zip_name))
---> 81                 except LookupError: raise e
     82 
     83         # Load the corpus.

C:\ProgramData\Anaconda3\lib\site-packages\nltk\corpus\util.py in __load(self)
     76         else:
     77             try:
---> 78                 root = nltk.data.find('{}/{}'.format(self.subdir, self.__name))
     79             except LookupError as e:
     80                 try: root = nltk.data.find('{}/{}'.format(self.subdir, zip_name))

C:\ProgramData\Anaconda3\lib\site-packages\nltk\data.py in find(resource_name, paths)
    673     sep = '*' * 70
    674     resource_not_found = '\n%s\n%s\n%s\n' % (sep, msg, sep)
--> 675     raise LookupError(resource_not_found)
    676 
    677 

LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  Searched in:
    - 'C:\\Users\\QD0203/nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
    - 'C:\\ProgramData\\Anaconda3\\nltk_data'
    - 'C:\\ProgramData\\Anaconda3\\share\\nltk_data'
    - 'C:\\ProgramData\\Anaconda3\\lib\\nltk_data'
    - 'C:\\Users\\QD0203\\AppData\\Roaming\\nltk_data'
**********************************************************************

**Comment by ines** [comment]
Glad the model installation is working now. 

As @jaypat87 mentioned above, the other error you're seeing is related to NLTK and not spaCy.

**Comment by Sanjaysaini24** [comment]
Thanks, @ines, and @jaypat87 for your support.
My issue resolved with your inputs.
A Big thanks to you all.
