### ISSUE TITLE
Pandas Dataframes into NLP pipelines?

### ISSUE THREAD

**Issue by CarKla** [explosion/spaCy#3115]
Hi everyone,

First things first: Thanks for that great framework! 

I have a problem with CSV files when I want to give them to an entire nlp pipeline. It appears to be as if it is not possible to inject a pandas dataframe into the pipeline without decomposing the dataframe structure.
It tried the following:

`df = df.apply(nlp)`

which results in:
> ("Argument 'string' has incorrect type (expected str, got Series)", 'occurred at index DocID')

Then I tried to put each column individually into the pipeline. 
```
for column in df:
     df[column] = df[column].apply(nlp)
```
This worked, but it is not helpful, since each pipeline component needs the information of each cell.  What can I do? Is there a workaround for my problem?

Thanks in advance!

**Comment by CarKla** [comment]
I give you a mini example. Consider the following example:
Dataframe:
```
ID   Name1  Name2
1    Daniel Daniela
2    Peter  John
``` 
Imagine one component in the pipeline computes the similarity of Name1 and Name2
Unfortunately this is not possible if the pipeline gets each column one after the other i.e. how can I put the df into the pipeline **without**  decomposing the dataframe (e.g. transform to linear string)

**Comment by rbhambriiit** [comment]
I don't know why you add constraints on decomposition.

I would have done something like:
df['score'] = df.apply(lambda row: nlp_similarity(row.Name1, row.Name2), axis=1)


nlp_similarity should be a method comparing 2 strings and returning the similarity score

**Comment by honnibal** [comment]
@CarKla I think if you imagine how to write the code if Pandas didn't exist, you might find your problem is actually easier. It doesn't seem like the dataframe is helping particularly here. Like, if you need to iterate tuples out of lines of a csv, can't you just have some generator function? Then you can do:

```python

def get_similarities(nlp, loc):
    for item1, item2 in read_csv(loc):
        doc1 = nlp.make_doc(item1)
        doc2 = nlp.make_doc(item2)
        yield doc1.similarity(doc2)
```
