### ISSUE TITLE
GoldParse Scorer Incorrect TP FP FN

### ISSUE THREAD

**Issue by davidbren** [explosion/spaCy#3120]
I have trained a custom NER model with a custom dataset 
When I evaluate the model on the "hold out" set using GoldParse I get a confusion matrix that seems incorrect for some values (see further) 

    ner_model = spacy.load(modelDir)
    scorer = Scorer()

    for input_, annot in examples:
        doc_gold_text = ner_model.make_doc(input_)
        gold = GoldParse(doc_gold_text, entities = annot['entities'])
        pred_value = ner_model(input_)
        scorer.score(pred_value, gold)

Unexpected results 

Expected Entities
(97039, 97012)

Predicted Entities
(97012,)

After
TP 0  FP 0  FN 0 

So no change of the counts after evaluation,  
I would expect 
TP 1 FP 1 FN 0

It was mentioned in another post that "The scorer is currently lenient about tokenization errors"
would this account for the above ??

A separate issue I have is that the FN results seem blunt 

Expected Entities
(98941, 99211, 27I00)

Predicted Entities
()

In this case the I expect the 
FN = 3 
but it is coming out as 
FN = 0

## Your Environment

* Operating System: Win 7
* Python Version Used:  2016.3.2
* spaCy Version Used: 2.0.18
* Environment Information:

**Comment by honnibal** [comment]
These lines of `scorer.py` calculate the precision and recall. They assume the candidate and gold entities are provided as tuples with the start, end and label:

```
 17     def score_set(self, cand, gold):
 18         self.tp += len(cand.intersection(gold))
 19         self.fp += len(cand - gold)
 20         self.fn += len(gold - cand)
```

At first glance this looks right to me. Maybe there's some weirdness in the way your data is being converted into a `GoldParse` object?

**Comment by davidbren** [comment]
I load the data for my golden test data from a json file, here is a sample of the format

[["Documant Séparatoi         Patch ll        Used to Sepaljate Each Transactign     OOXVEDIEIOM", 
{"entities": [[1871, 1876, "PAYER"], [6071, 6076, "PAYER"], [4041,4046, "CPT"]]
}], 
["Documant Séparatoi         Patch ll        Used to Sepaljate Each Transactign     OOXVEDIEIOM ",
{"entities": [[1991, 2001, "PAYER"], [4762, 4767, "CPT"], [4833, 4838, "CPT"], [3583, 3589, "CHG_Amts"]]
}]
]  #end of doc

*Note the above is just meant as an example of the layout I am using. 
 The real data strings are much longer & as such the end & start points can't be traced from above.

Does this format make sense to you ? Its the same format I used for the training set. 
Going back to the loop 

  for input_, annot in examples:
        doc_gold_text = ner_model.make_doc(input_)
        gold = GoldParse(doc_gold_text, entities = annot['entities'])
        pred_value = ner_model(input_)

The annot['entities'] is at this point a list of lists,  should this be a list of tuples ?
The funny thing is that its giving correct results for some but not others..

**Comment by davidbren** [comment]
To be more specific should this be the format of the entities 
"entities": [(1871, 1876, "PAYER"), (6071, 6076, "PAYER"), (4041, 4046, "CPT"), (6642, 6647, "CPT")]

Rather than 
"entities": [[1871, 1876, "PAYER"], [6071, 6076, "PAYER"], [4041, 4046, "CPT"], [6642, 6647, "CPT"]]

**Comment by davidbren** [comment]
I just tried an explicit convert to a list of tuples but it has no effect the confusion matrix is still incorrect for some. Is there any way to trace the output from GoldParse, when I step into it the entities don't have the original start end points ?

**Comment by davidbren** [comment]
Any further help would be great as I am fairly stuck here..

**Comment by davidbren** [comment]
For the items that are not being evaluated at all, it seems that the if statement below is the cause ?

def score(self, tokens, gold, verbose=False, punct_labels=('p', 'punct')):
..
..
        if '-' not in [token[-1] for token in gold.orig_annot]:
            cand_ents = set()
            for ent in tokens.ents:
                first = gold.cand_to_gold[ent.start]
                last = gold.cand_to_gold[ent.end-1]
                if first is None or last is None:
                    self.ner.fp += 1
                else:
                    cand_ents.add((ent.label_, first, last))
            self.ner.score_set(cand_ents, gold_ents)

The values that are being found 
II63056, 7I22612, II22558,

A full token looks like this 
<class 'tuple'>: (2188, 'lI22842', None, None, None, '-')

**Comment by davidbren** [comment]
For the items that are not being evaluated at all, it seems that the if statement below is the cause ?

def score(self, tokens, gold, verbose=False, punct_labels=('p', 'punct')):
 ..
 ..
 if '-' not in [token[-1] for token in gold.orig_annot]:
 cand_ents = set()
 for ent in tokens.ents:
 first = gold.cand_to_gold[ent.start]
 last = gold.cand_to_gold[ent.end-1]
 if first is None or last is None:
 self.ner.fp += 1
 else:
 cand_ents.add((ent.label_, first, last))
 self.ner.score_set(cand_ents, gold_ents)

The values that are being found
 II63056, 7I22612, II22558,

A full token looks like this
 <class 'tuple'>: (2188, 'lI22842', None, None, None, '-')

**Comment by honnibal** [comment]
Yes, that's right.

I agree it's confusing. On the corpora I'm training on, very few entities are misaligned with the tokenization, so this doesn't really cause a problem. The reason for the behaviour is that it lets you evaluate the model accuracy -- if the tokenization doesn't match, the model can't get the example right.

We've updated the docs, which will now note that entities which have misaligned tokenization aren't evaluated.
