### ISSUE TITLE
Inconsistency between documentation and behaviour in both "Span.subtree" and "Token.subtree"

### ISSUE THREAD

**Issue by alvaroabascar** [explosion/spaCy#3122]
## Regarding `Token.subtree`:

The [docstring](https://spacy.io/api/token#subtree) states that `Token.subtree` yields `"A descendant token such that self.is_ancestor(descendant)."`. But `subtree` includes in the generator the token itself, and `token.is_ancestor(token)` evaluates to `False`:

```python3
doc = nlp('this is a sentence')
token = doc[0]
print(list(token.subtree))
```

- Expected result, according to docs: `[]`
- Result: `[this]`

But:
```python3
token.is_ancestor(token)
```
- Result: `False`

So either the documentation is wrong, or the implementation of `Token.subtree` is wrong.

## Regarding `Span.subtree`:

The [docstring of Span.subtree](https://github.com/explosion/spaCy/blob/master/spacy/tokens/span.pyx#L494) states "Tokens that descend from tokens in the span, but fall outside it". Given this explanation, I expected that `span.subtree` would give me a subtree of tokens which descend from the tokens within `span`, but this subtree *would not* include the tokens within `span`. The behaviour, however, is to return the subtree *plus* the tokens within span.

```python3
doc = nlp('this is a sentence')
token_of_sentence = doc[-1]
print(list(token_of_sentence.subtree)) 
```

- Expected result, according to docs: `[a]`
- Result: `[a, sentence]`

I would the behaviour to match that of `Token.subtree`, but as I explained above, this is not clear to me either.

## Which page or section is this issue related to?
- [https://spacy.io/api/token#subtree](https://spacy.io/api/token#subtree)
- [https://spacy.io/api/span#subtree](https://spacy.io/api/span#subtree)

**Comment by honnibal** [comment]
True, this is inconsistent. Would definitely say the docs should change here, not the behaviour.

**Comment by alvaroabascar** [comment]
Then, suggestion [here](https://github.com/explosion/spaCy/pull/3124) :)

**Comment by honnibal** [comment]
Merged, thanks!
