### ISSUE TITLE
yuanjie-Mac:~ yuanjie$ python -m spacy download zh      Compatibility error     No compatible model found for 'zh' (spaCy v2.0.18).

### ISSUE THREAD

**Issue by Jie-Yuan** [explosion/spaCy#3123]
## How to reproduce the problem

```bash
# copy-paste the error message here
```

## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by svlandeg** [comment]
I don't think there currently is a Chinese model available (cf. https://spacy.io/models/#available-models) but it seems to be a work in progress, cf. https://github.com/howl-anderson/Chinese_models_for_SpaCy
