### ISSUE TITLE
Can we store and load NER models separately ?

### ISSUE THREAD

**Issue by An4567** [explosion/spaCy#3125]
To increase accuracy, we would like unique NER models per bucket or intent. So can we store and load NER models separately ? Or is there an alternative way to achieve, what we want to do.

**Comment by honnibal** [comment]
You might find the discussion in this thread interesting: https://github.com/explosion/spaCy/issues/2920 . If this matches what you want, let me know so we can close this and keep discussion in one place.

The short answer is that I think it's best to write yourself a pipeline component that orchestrates the multiple models you want to run. The annotations can be saved into extension attributes if they're allowed to have overlapping spans.

**Comment by An4567** [comment]
Actually I am training spaCy's NER model, and want to serialize only trained data model and not complete language model. It takes ~ 1 GB of space for en_core_web_lg. I am training separate NER model per intent (more than 10 intents). If I go with this it will take lot of disk space. 
I am using following method. Is there any other simple way ?
nlp.to_disk('/home/me/data/en_example_model')
https://spacy.io/usage/training#section-saving-loading

**Comment by ines** [comment]
@An4567 Just merged an update that makes the component serialization methods consistent and allows [excluding fields during serialization](https://spacy.netlify.com/api/entityrecognizer#serialization-fields) using the `exclude` argument. So in `v2.1`, you'll be able to do:

```python
ner = nlp.get_pipe("ner")
ner.to_disk("/path/to/ner", exclude=["vocab"])
```

This will exclude the shared vocabulary, including the vocab, which should be most of what makes the model so large.

In previous versions, you should be able to set `vocab=False`:

```python
ner = nlp.get_pipe("ner")
ner.to_disk("/path/to/ner", vocab=False)
```
