### ISSUE TITLE
Whitespaces interfere with final NER result

### ISSUE THREAD

**Issue by miguelwon** [explosion/spaCy#3132]
I trained a custom NER model to identfy names for Portuguese. The model performs very well (F1~92) but only if the tokenization is well performed, specifically, if there is no whitespaces as tokens. I show bellow an example of the same sentente, without and with whitespaces. The first example shows the correct prediction. 
I know that there is issue [#1717](https://github.com/explosion/spaCy/issues/1717) but the problem with the proposed solution is that it is only for post-processment. Is it possible to add in the pipeline a pre-processment such that the tokenizer do not consider a whitespace as a token?

```
>>> nlp = spacy.load("pt_M_INESC_NAME_d50")
>>> text = """Na terça-feira passada, o secretário de Estado norte-americano,
... Mike Pompeo, anunciou ter adiado um encontro com um alto
... dirigente norte-coreano. Pompeo ia encontrar-se, em Nova Iorque,
... com Kim Yong-chol para discutir os progressos no desarmamento
... norte-coreano e preparar uma nova cimeira entre o Presidente
... norte-americano, Donald Trump, e Kim Jong-un.""".replace('\n',' ')
>>> 
>>> text
'Na terça-feira passada, o secretário de Estado norte-americano, Mike Pompeo, anunciou ter adiado um encontro com um alto dirigente norte-coreano. Pompeo ia encontrar-se, em Nova Iorque, com Kim Yong-chol para discutir os progressos no desarmamento norte-coreano e preparar uma nova cimeira entre o Presidente norte-americano, Donald Trump, e Kim Jong-un.'
>>> 
>>> doc = nlp(text)
>>> for x in doc:
...     print((x.text,x.ent_type_))
... 
('Na', '')
('terça-feira', '')
('passada', '')
(',', '')
('o', '')
('secretário', '')
('de', '')
('Estado', '')
('norte-americano', '')
(',', '')
('Mike', 'NAME')
('Pompeo', 'NAME')
(',', '')
('anunciou', '')
('ter', '')
('adiado', '')
('um', '')
('encontro', '')
('com', '')
('um', '')
('alto', '')
('dirigente', '')
('norte-coreano', '')
('.', '')
('Pompeo', '')
('ia', '')
('encontrar-se', '')
(',', '')
('em', '')
('Nova', '')
('Iorque', '')
(',', '')
('com', '')
('Kim', 'NAME')
('Yong-chol', 'NAME')
('para', '')
('discutir', '')
('os', '')
('progressos', '')
('no', '')
('desarmamento', '')
('norte-coreano', '')
('e', '')
('preparar', '')
('uma', '')
('nova', '')
('cimeira', '')
('entre', '')
('o', '')
('Presidente', '')
('norte-americano', '')
(',', '')
('Donald', 'NAME')
('Trump', 'NAME')
(',', '')
('e', '')
('Kim', '')
('Jong-un', '')
('.', '')
>>> 
>>> 
>>> text = """Na terça-feira passada, o secretário de Estado norte-americano,
...     Mike Pompeo, anunciou ter adiado um encontro com um alto
...     dirigente norte-coreano. Pompeo ia encontrar-se, em Nova Iorque,
...     com Kim Yong-chol para discutir os progressos no desarmamento
...     norte-coreano e preparar uma nova cimeira entre o Presidente
...     norte-americano, Donald Trump, e Kim Jong-un.""".replace('\n',' ')
>>> 
>>> text
'Na terça-feira passada, o secretário de Estado norte-americano,     Mike Pompeo, anunciou ter adiado um encontro com um alto     dirigente norte-coreano. Pompeo ia encontrar-se, em Nova Iorque,     com Kim Yong-chol para discutir os progressos no desarmamento     norte-coreano e preparar uma nova cimeira entre o Presidente     norte-americano, Donald Trump, e Kim Jong-un.'
>>> doc = nlp(text)
>>> for x in doc:
...     print((x.text,x.ent_type_))
... 
('Na', '')
('terça-feira', '')
('passada', '')
(',', '')
('o', '')
('secretário', '')
('de', '')
('Estado', '')
('norte-americano', '')
(',', '')
('    ', '')
('Mike', '')
('Pompeo', '')
(',', '')
('anunciou', '')
('ter', '')
('adiado', '')
('um', '')
('encontro', '')
('com', '')
('um', '')
('alto', '')
('    ', '')
('dirigente', '')
('norte-coreano', '')
('.', '')
('Pompeo', '')
('ia', '')
('encontrar-se', '')
(',', '')
('em', '')
('Nova', '')
('Iorque', '')
(',', '')
('    ', '')
('com', '')
('Kim', '')
('Yong-chol', '')
('para', '')
('discutir', '')
('os', '')
('progressos', '')
('no', '')
('desarmamento', '')
('    ', '')
('norte-coreano', '')
('e', '')
('preparar', '')
('uma', '')
('nova', '')
('cimeira', '')
('entre', '')
('o', '')
('Presidente', '')
('    ', '')
('norte-americano', '')
(',', '')
('Donald', 'NAME')
('Trump', 'NAME')
(',', '')
('e', '')
('Kim', '')
('Jong-un', '')
('.', '')
```

## Info about spaCy

* **spaCy version:** 2.0.18
* **Platform:** Linux-4.4.0-130-generic-x86_64-with-Ubuntu-16.04-xenial
* **Python version:** 3.6.4
* **Models:** en, pt, pt_core_news_sm, en_core_web_sm

**Comment by ines** [comment]
> but the problem with the proposed solution is that it is only for post-processment. Is it possible to add in the pipeline a pre-processment such that the tokenizer do not consider a whitespace as a token?

spaCy's tokenizer is non-destructive, so by definition, its output needs to represent all characters  that were present in the original input, including whitespace etc. In theory, you *could* hack around this and write your own function that removes the whitespace tokens and then creates a new `Doc` manually – but I wouldn't really recommend that.

Instead, it's probably a better idea to do this *before* you tokenize the text. For example, you might find [`textacy`'s `normalize_whitespace` helper]( https://chartbeat-labs.github.io/textacy/api_reference.html#textacy.preprocess.normalize_whitespace) useful.

You could still give `spacy-nightly` a try if you like and see if/how your accuracy improves. 1e6725e9b734862e61081a916baf440697b9971e made it "illegal" for the entity recognizer to predict whitespace tokens as entities, so this should hopefully prevent most of the problematic results you're seeing. I'd also be curious to hear how the pretraining (see #2931) affects Portuguese.

> I trained a custom NER model to identfy names for Portuguese. The model performs very well (F1~92) 

That's nice to hear! There's been a lot of interest in Portuguese models, so if you ever end up writing a blog post about your training process, I'm sure it'd be very popular 😉

**Comment by miguelwon** [comment]
Ok, thanks. I'll work with textacy. 

> That's nice to hear! There's been a lot of interest in Portuguese models, so if you ever end up writing a blog post about your training process, I'm sure it'd be very popular 

Ok, I'll write whenever i can (and when I create a blog :sweat_smile: ).
