### ISSUE TITLE
Is there any way to skip model generation at end of each epoch during CLI Training

### ISSUE THREAD

**Issue by santhoshsridhar0304** [explosion/spaCy#3135]
I'm training a new entity using the CLI **spacy train** command. This is creating a model at the end of each epoch. I wish to have only the final model. Is there any way to achieve this?

**Comment by honnibal** [comment]
Are you sure you want only the final model though? The last model isn't necessarily the most accurate --- accuracy might go down during training. We therefore save all the models and return the best one. By default we do this on disk, although you could also do it in memory. If you need to, you should be able to modify the code in `spacy/cli/train.py` to change this.

**Comment by santhoshsridhar0304** [comment]
okay...Thanks for the info!
