### ISSUE TITLE
What features are used for custom NER?

### ISSUE THREAD

**Issue by ctrado18** [explosion/spaCy#3136]
Hi,

I want to train a custom NER in german and since below the nightly version the german models have only very few word embeddings, I am curious if word embeddings are used for the NER deep learning model? What else is used from within spacy model like the POS-Tags for NER?

BTW: Are there any free tools to annotate data for entity training like chatito for Rasa?

**Comment by honnibal** [comment]
The model should learn vectors for the words, and subword features. It uses pre-trained vectors as features as well if they're available, but it will still learn vectors for the words in the training data as well. It doesn't use part-of-speech tags.

Finally, you can find our annotation tool Prodigy here: https://prodi.gy , however it is not free. Prodigy is the product we use to support development of spaCy.
