### ISSUE TITLE
Can spaCy be called from multiple threads?

### ISSUE THREAD

**Issue by pudo** [explosion/spaCy#3137]
## How to reproduce the behaviour

I am trying to operate an API service that includes processing pieces of text via spaCy. As is usual with such an API, it's multi-threaded to handle incoming requests. My hope was to be able to use a single loaded spaCy model (``spacy.load(lang)``) and call it from multiple threads. However, it seems like doing that duplicates the amount of memory used by spacy for each thread. Can you give any guidance on how spaCy could be used in a multi-thread environment?

Please note that I am *not* referring the allowing spaCy to manage its own threads, as ``nlp.pipe`` seems to be doing.

## Your Environment
* Operating System: alpine:edge
* Python Version Used: 3.6.7
* spaCy Version Used: 2.0.18
* Environment Information: gRPC server app

The full source of my server implementation is in this file: 

https://github.com/alephdata/aleph/blob/master/services/extract-entities/entityextractor/service.py

**Comment by honnibal** [comment]
The current `spacy-nightly` should work for this. The matrix multiplications should be fully single-threaded, and everything should be pickling correctly. Try it out and let me know if you have any problems.

**Comment by pudo** [comment]
Thanks for getting back so quick. I just tried out `2.1.0a5` in our system. Overall throughput has tripled without any code changes, while memory use has fallen from 470MB to somewhere around 120MB for the NER service. I'm trying to see if this is a defect of some sort, because it looks too good to be true.
