### ISSUE TITLE
NER Retrainable  Model  lowers prediction accuracy 

### ISSUE THREAD

**Issue by yatin-rxlogix** [explosion/spaCy#3138]
I have developed a NER Prediction on Spacy using my own Custom Data (around 1.3 million statements), After some time I have some more records (10 thousand), 
So on top of previous model & new training data I build new Model.
But the new Model has very low accuracy numbers for the Training Data on which I earlier prepared my old model, The new model has only good accuracy numbers for New data.

Can somebody provide some link of how to add new  data to an existing ner model & create a new model.

**Comment by yatin-rxlogix** [comment]
@honnibal , Can you provide some hint as why accuracy got down for previous train data  when new data is added to ner to create a new model, Can you look into Code if i am doing something wrong.

**Comment by honnibal** [comment]
@yatin-rxlogix Are you retraining from a blank model in both cases? I think you probably don't want to do `spacy.load()` here. Just retrain with a mix of the two data sets. It's much harder to ensure accuracy when you're updating an existing model. If you have both data sets available, training on a combination of them will usually be better.

**Comment by yatin-rxlogix** [comment]
@honnibal  Thanks for the reply.
In the first model,  I have prepared on top of  'blank'  model  by calling begin_training()  & introduced  6 new customized fields in it. On top of this model I build a new model with more data and  same fields.   But the accuracy on earlier  Trained data falls.  

As you suggest I can do  a mix of two data sets.

But in my use case I would like to add more data  from time to time to existing model  as my data is huge.  
Kindly suggest me some option to do so.

**Comment by yatin-rxlogix** [comment]
@honnibal  , Can you provide some more  insights into the issue as I am still not able to resolve this.
