### ISSUE TITLE
GoldParse NER Evaluation Skipping Examples

### ISSUE THREAD

**Issue by davidbren** [explosion/spaCy#3140]
Just for clarity I am opening this as a separate issue,  I had logged another related bug here
https://github.com/explosion/spaCy/issues/3120 

Some training examples are not being scored at all, it seems that the if statement below is the cause ?

def score(self, tokens, gold, verbose=False, punct_labels=('p', 'punct')):
 ..
 ..
 if '-' not in [token[-1] for token in gold.orig_annot]:
 cand_ents = set()
 for ent in tokens.ents:
 first = gold.cand_to_gold[ent.start]
 last = gold.cand_to_gold[ent.end-1]
 if first is None or last is None:
 self.ner.fp += 1
 else:
 cand_ents.add((ent.label_, first, last))
 self.ner.score_set(cand_ents, gold_ents)

Some example values that are causing the training example to be skipped
 II63056, 7I22612, II22558,

A full token that causes a skip look like this 
 <class 'tuple'>: (2188, 'lI22842', None, None, None, '-')

I tried to find anything in the docs that would explain "-" label below but have not been able to 
Is the "-" related to negative examples ?

## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by davidbren** [comment]
Any direction on this would be really helpful. The results from spaCy look are really promising but I can't fully understand the F1 Calc here ? Let me know if there is anything I can do to make it clearer..

**Comment by btrungchi** [comment]
'-' labels happened to me when mismatched offsets being converted into a `GoldParse`

For example in this case where 'Google' and 'Inc.' are tokens and an annotation of 'Google Inc' is not matched to them, which makes those labels become '-'
`
>>> import spacy
>>> text = u"This is Google Inc."
>>> entities = [(8, 18, 'ORG')]
>>> nlp = spacy.blank('en')
>>> doc = nlp.make_doc(text)
>>> gold = spacy.gold.GoldParse(doc, entities=entities)
>>> gold.orig_annot
[(0, u'This', None, None, None, u'O'), (1, u'is', None, None, None, u'O'), (2, u'Google', None, None, None, u'-'), (3, u'Inc.', None, None, None, u'-')]
`

In the case our annotation is 'Google Inc.', it works well:
`
>>> import spacy
>>> text = u"This is Google Inc."
>>> entities = [(8, 19, 'ORG')]
>>> nlp = spacy.blank('en')
>>> doc = nlp.make_doc(text)
>>> gold = spacy.gold.GoldParse(doc, entities=entities)
>>> gold.orig_annot
[(0, u'This', None, None, None, u'O'), (1, u'is', None, None, None, u'O'), (2, u'Google', None, None, None, u'B-ORG'), (3, u'Inc.', None, None, None, u'L-ORG')]
`

**Comment by davidbren** [comment]
Thanks very much, that's exactly the problem my data is noisey OCR'd data so their are trailing characters appended to some of the entities of interest.  
For example the entity I am looking for is UHAA the ocr'd version of this however is UHAAe 
although I have given the correct start/end point the trailing e throws it off.  

Would be good to point this out within the docs, unless I have missed it. 
Thanks again for your reply its really helped me out, I better add some logic to account for this when marking the entities.

**Comment by ines** [comment]
Thanks for updating with the solution! We're currently working on improving the training data format (see #2928) and as part of this, we'll also improve the docs and mention this.
