### ISSUE TITLE
Quote char in a sentence produce extra sentence result

### ISSUE THREAD

**Issue by mehmetilker** [explosion/spaCy#3141]
## How to reproduce the behaviour
Parsing a sentence which contains quote char (“ or ") produce 2 sentences output.

Maybe related with: https://github.com/explosion/spaCy/issues/2424

```python
doc = nlp('“That’s a Protestant-looking house,” mothers would chirp after tidying up.')
for s in doc.sents:
    print(s)
```

output:
```
“
That’s a Protestant-looking house,” mothers would chirp after tidying up.
```

## Info about spaCy

* **spaCy version:** 2.1.0a5
* **Platform:** Windows-10-10.0.17134-SP0
* **Python version:** 3.6.6
* **Models:** en

BTW am I supposed to open this issue here?
https://github.com/explosion/spaCy/issues/3052
When I click New issue it looks same with opening a general issue.

**Comment by moh55m55** [comment]
I was going to ask about this. Yes I got the same issue for both quotations (start and end). Hopefully, someone help.

**Comment by moh55m55** [comment]
I found this link useful. You can add rules for that. 

[https://github.com/explosion/spaCy/blob/master/examples/pipeline/custom_sentence_segmentation.py](url)

**Comment by moh55m55** [comment]
Found it through this relevant issue. [https://github.com/explosion/spaCy/issues/2619](url)
