### ISSUE TITLE
how do I get the list of words configured for 'FAC' entity in SpaCy

### ISSUE THREAD

**Issue by waniaparna** [explosion/spaCy#3143]
I am looking for a list of words used to train the FAC entity in LUIS. How do I get that list?

## Your Environment

* Operating System: windows 10
* Python Version Used: 3.6
* spaCy Version Used: 101
* Environment Information:

**Comment by ines** [comment]
I hope I understand your question correctly. I can't answer about LUIS and I'm not even sure Microsoft fully discloses what their API models were trained on.

spaCy's models are trained from large corpora of entities *in context*. So there's no direct list that just shows you the words that were used. However, if you have the original corpus, you can extract that information to see what's in it.

The English models were trained on the OntoNotes 5 corpus: https://catalog.ldc.upenn.edu/LDC2013T19

You can find all other training sources in the models directory, for example here: https://spacy.io/models/en
