### ISSUE TITLE
Stop words are not working for en_core_web_lg

### ISSUE THREAD

**Issue by drorata** [explosion/spaCy#3146]
## How to reproduce the behaviour
Compare:

```python
nlp = spacy.load('en_core_web_lg')
doc = nlp(u'Apple is looking at buying U.K. startup for $1 billion')
[(w, w.is_stop) for w in doc]
```

which yields:

```
[(Apple, False),
 (is, False),
 (looking, False),
 (at, False),
 (buying, False),
 (U.K., False),
 (startup, False),
 (for, False),
 ($, False),
 (1, False),
 (billion, False)]
```

and

```python
nlp = spacy.load('en_core_web_sm')
doc = nlp(u'Apple is looking at buying U.K. startup for $1 billion')
[(w, w.is_stop) for w in doc]
```

yielding:

```
[(Apple, False),
 (is, True),
 (looking, False),
 (at, True),
 (buying, False),
 (U.K., False),
 (startup, False),
 (for, True),
 ($, False),
 (1, False),
 (billion, False)]
```

The former doesn't detect stop words at all. As per #1574 and #1625 it seems to be a known issue. Unfortunately, these two issues were closed (and locked) even thou the problem is still there.

Did I miss something or is it still an issue and the workaround is something like https://github.com/explosion/spaCy/issues/1625#issuecomment-346185033?

## Info about spaCy

* **spaCy version:** 2.0.18
* **Platform:** Darwin-18.2.0-x86_64-i386-64bit
* **Python version:** 3.6.8
* **Models:** en_core_web_lg, en_core_web_sm

**Comment by ines** [comment]
Since this is an issue *in the models*, it requires us to retrain them from scratch. The current models for `2.0.x` are still the ones that were trained with this issue, but we've been training new models for `spacy-nightly` that shouldn't have this problem anymore.

For the `2.0.x` models, that workaround is still valid, yes.

**Comment by ines** [comment]
You can already try the new models with `spacy-nightly`. We're getting pretty close to the `v2.1.0` release now – see here for the project board: https://github.com/explosion/spaCy/projects/5
