### ISSUE TITLE
Error on new Set membership feature

### ISSUE THREAD

**Issue by mehmetilker** [explosion/spaCy#3149]
## How to reproduce the behaviour

I am trying to use new set membership feature but I am getting following exception:

```python
    matcher.add('rule', on_match, *patterns)
  File "matcher.pyx", line 436, in spacy.matcher.Matcher.add
  File "matcher.pyx", line 305, in spacy.matcher.init_pattern
TypeError: an integer is required
```

```python
#same result with following patterns
patterns1 = [
    [{'POS': {'IN': ['VERB', 'CONJ', 'CCONJ']}}]
]

patterns2 = [[{'LEMMA': {'IN': ['like', 'love']}},
             {'LOWER': {'IN': ['apples', 'bananas']}}]
            ]

matcher.add('rule', on_match, *patterns2)

```

## Info about spaCy

* **spaCy version:** 2.1.0a5
* **Platform:** Windows-10-10.0.17134-SP0
* **Python version:** 3.6.6
* **Models:** en

**Comment by ines** [comment]
Sorry if this was confusing – the document in #1971 is only the *proposal* and outlines the planned features. It's not yet implemented in the stable version or `spacy-nightly` (and the matcher API updates are still marked as "under construction" in the [latest release](https://github.com/explosion/spaCy/releases/tag/v2.1.0a5)).
