### ISSUE TITLE
"SyntaxError: invalid syntax" when parsing text with apostrophe 

### ISSUE THREAD

**Issue by abalvet** [explosion/spaCy#3157]
### Info about spaCy

* **Python version:** 2.7.15rc1
* **Platform:** Linux-4.15.0-43-generic-x86_64-with-Ubuntu-18.04-bionic
* **spaCy version:** 2.0.18
* **Models:** es, fr, en

## Issue description
I am getting a "SyntaxError: invalid syntax" error message when trying to parse text where there are apostrophes. I can't find how to protect the ' character anywhere or use an explicit code (eg. &quote;)

### Commands leading to the issue

>>> doc = nlp(u'Le magnat de la presse a hérité de l'entreprise familiale de son grand-père.')
  File "<stdin>", line 1
    doc = nlp(u'Le magnat de la presse a hérité de l'entreprise familiale de son grand-père.')

This happens with French or English.
No issues with initial steps: loading models, etc.

**Comment by mauryaland** [comment]
Try using double quote instead of single quote for sentences containing single quote.
In your case:
```python
doc = nlp(u"Le magnat de la presse a hérité de l'entreprise familiale de son grand-père.")
```

**Comment by abalvet** [comment]
My bad I just discovered that.
Thx
