### ISSUE TITLE
Matcher and POS tags

### ISSUE THREAD

**Issue by ankitaunsw** [explosion/spaCy#3165]
I am trying to use Rule-based matching with POS tags.
For example: 
pattern = [{'POS': 'VERB', 'OP':'+'}, {'POS': 'ADV', 'OP':'+' },{'POS':'VERB','OP':'+'},{'POS': 'NOUN', 'OP':'?'}]

'OP' allows us to specify 'optional', 0 or more matches, 1 or more matches or 'no' matches. But can we specify that we want 'exactly 3 matches'? Is there a way to quantify the POS?
For example like this:

pattern = [{'POS': 'VERB', 'OP':'3'}, {'POS': 'ADV', 'OP':'2' },{'POS':'VERB','OP':'1'},{'POS': 'NOUN', 'OP':'1'}]

Thanks for the help!

**Comment by honnibal** [comment]
There's no support for that currently, as you can get the same thing by just expanding your pattern. if you want to add the syntactic sugar, you could add a pretty simple pre-processing rule to your patterns.
