### ISSUE TITLE
Parser assigns head from different sentence

### ISSUE THREAD

**Issue by f11r** [explosion/spaCy#3170]
The expectation is that every assigned `token.head` is present in the same sentence span, correct?

The following code raises an exception, as the head of `Trotz` is `anheizen`, even though the sentence is split into the two parts `Trotz [...] Teuerungsrate` and `ist [...] dürfte.`.
```
import de_core_news_sm

nlp = de_core_news_sm.load()
doc = nlp('''Trotz der beschleunigten
Teuerungsrate ist die Stimmung in der Wirtschaft
so gut, dass die Löhne in vielen Branchen steigen,
was die Inflation weiter anheizen dürfte.
''')
for sent in doc.sents:
    for token in sent:
        assert token.head in sent, (token, token.head, sent)
```

## Your Environment

* **spaCy version:** 2.1.0a5
* **Platform:** Linux-4.14.89-x86_64-with-glibc2.9
* **Python version:** 3.6.7

**Comment by honnibal** [comment]
This looks to be a bug in the way the sentences are calculated, thanks. It looks like somewhere the code is assuming the parse is projective, when in fact it can be non-projective. I thought I had fixed this bug, but apparently not!

**Comment by honnibal** [comment]
The specific example is working in `v2.1.0a7`. I'm worried that a small model change makes this particular example work, and the underlying bug is still there...But lacking a specific example I'll close this anyway. Hopefully if there's really an issue here we can get to the bottom of it soon.

**Comment by f11r** [comment]
@honnibal Here are some examples that are still broken in `v2.1.0a8`:

```
import de_core_news_sm

nlp = de_core_news_sm.load()
texts = [
'Diesmal hatte zwar der Freistaat die finanzielle Regie, aber die Gemeinde beteiligte sich in erheblichem Umfang an der Infrastruktur und nahm die Gelegenheit wahr, selbst eine Umgehungsstraße zu bauen, was auch Voraussetzung für eine Dorferneuerung war, die noch 2012 eingeleitet werden sollte.'
'''
1823 wurde Martin von Samuel Prowett, einem amerikanischen Verleger, damit beauftragt, John Milton Paradise Lost zu illustrieren, wofür ihm 2000 Pfund gezahlt wurden. Noch bevor die ersten 24 Stiche fertiggestellt waren, wurden ihm weitere 1500 Pfund für einen zweiten Satz von 24 kleineren Stichen gezahlt.''',
'''
Über diese Zurückweisung und die Transformation von Liliput in das Land von Gulliver ist Edward so verärgert, dass er ins feindliche Königreich Blefuscu überläuft und deren Truppen einen Bauplan für einen Roboter übergibt, den er in einem Magazin gefunden hat, das Gulliver mitbrachte.
''',
]

for text in texts:
    doc = nlp(text)
    for sent in doc.sents:
        for token in sent:
            if token.head not in sent:
                print(token, token.head, sent)
```


## Info about spaCy

* **spaCy version:** 2.1.0a8
* **Platform:** Linux-4.14.98-x86_64-with-glibc2.10
* **Python version:** 3.7.2
* **Models:** en, de

**Comment by syllog1sm** [comment]
Thanks! Will investigate.

**Comment by honnibal** [comment]
I see my previous fix wasn't enough for the tree shapes in these examples. The change I've made isn't very satisfying -- just looping again to fix things -- but I think it should work.
