### ISSUE TITLE
Lemmatizer fails on popular English proper nouns

### ISSUE THREAD

**Issue by mikpanko** [explosion/spaCy#3175]
English lemmatizer seems to fail converting popular English proper nouns to a singular form, for example: "Americans", "Russians", "Democrats", "Republicans". It also fails on common nouns, when they are used as proper nouns, such as "60 Minutes show". In all these cases POS is properly identified as a proper noun.

The issue might be related to this one: https://github.com/explosion/spaCy/issues/781.

## Your Environment
* Operating System: MacOS Mojave v10.14.2
* Python Version Used: 2.7.15
* spaCy Version Used: 2.0.18

**Comment by honnibal** [comment]
So the tagger tags these as `NNPS`, but then the lemmatizer isn't working correctly? If so then yes, that seems like a bug. If the tagger gets them as `NNP`, then it's merely a model failure.

**Comment by DuyguA** [comment]
> So the tagger tags these as `NNPS`, but then the lemmatizer isn't working correctly? If so then yes, that seems like a bug. If the tagger gets them as `NNP`, then it's merely a model failure.

Agree, NNPS should be trimmed a bit in this case :blush:

**Comment by honnibal** [comment]
I've now nearly finished proper support for morphological features: https://github.com/explosion/spaCy/pull/2807

This will allow us to write lemmatizer rules keyed by the fine-grained morphological attributes, which will clean up a lot of problems. Some promising lemmatization rules for Spanish have been developed, so overall I'd say this looks pretty good.

**Comment by honnibal** [comment]
Merging with #3052 (inaccurate prediction master thread)
