### ISSUE TITLE
Type error in French with "je", "moi" and other words.

### ISSUE THREAD

**Issue by foufaster** [explosion/spaCy#3178]
## How to reproduce the behaviour
Spacy yields a fatal error while dealing with some French words like "je", and "moi".

`import spacy`
``
nlp = spacy.load("fr")
``
`nlp("Je suis chez moi")`

## Info about spaCy

* **spaCy version:** 2.0.18
* **Platform:** Linux-4.4.0-141-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.7.2
* **Models:** fr

## Your Environment

* Operating System:
ubuntu 16.4
* Python Version Used:
3.7.2
* Environment Information:
atomicwrites==1.2.1
attrs==18.2.0
certifi==2018.11.29
chardet==3.0.4
cymem==2.0.2
Cython==0.27.3
cytoolz==0.9.0.1
dill==0.2.8.2
idna==2.8
mock==2.0.0
more-itertools==5.0.0
msgpack==0.5.6
msgpack-numpy==0.4.3.2
murmurhash==1.0.1
numpy==1.16.0
pathlib==1.0.1
pbr==5.1.1
plac==0.9.6
pluggy==0.8.1
preshed==2.0.1
py==1.7.0
pytest==4.0.2
regex==2018.1.10
requests==2.21.0
six==1.12.0
spacy==2.0.18
thinc==6.12.1
toolz==0.9.0
tqdm==4.29.1
ujson==1.35
urllib3==1.24.1
wrapt==1.10.11

**Comment by ines** [comment]
> Spacy yields a fatal error while dealing with some French words like "je", and "moi".

What exactly is the error?

And could you run `spacy validate` and share the result?

**Comment by foufaster** [comment]
>  Installed models (spaCy v2.0.18)
>     /home/****/spaCy/spacy
> 
>     TYPE        NAME                  MODEL                 VERSION                                   
>     link        fr                    fr_core_news_sm       2.0.0    ✔  

The error is:
File "", line 1, in  
> File "/home/****/spaCy/spacy/language.py", line 346, in *call*  
> doc = proc(doc)  
> File "pipeline.pyx", line 427, in spacy.pipeline.Tagger.*call*  
> File "pipeline.pyx", line 463, in spacy.pipeline.Tagger.set_annotations  
> File "morphology.pyx", line 111, in spacy.morphology.Morphology.assign_tag_id  
> File "morphology.pyx", line 182, in spacy.morphology.Morphology.lemmatize  
> TypeError: Expected unicode, got tuple

I actually fixed the error locally. I'm waiting for my contribution to be accepted.

**Comment by ines** [comment]
Just merged your PR with the contributor agreement – so feel free to submit your suggestion for the fix 🙂

**Comment by honnibal** [comment]
Seems to be fixed on `develop`, so you should be able to use the fix if you install from `spacy-nightly`. Thanks again for the report!
