### ISSUE TITLE
does spacy support adding custom pos label which not in ud tag set for training

### ISSUE THREAD

**Issue by labixiaoK** [explosion/spaCy#3192]
my question is just as what i say above,  ' custom pos label ' here is full custom, which have different means and can not map to ud sets.  ur doc said custom tag map need to map the ud sets, can I define my seq label set or add some new label not mapping to ud sets for training pos model?
ty.
## Your Environment

* **spaCy version:** 2.0.18
* **Platform:** Windows-10-10.0.17134-SP0
* **Python version:** 3.7.0

**Comment by honnibal** [comment]
The `token.pos` attribute is type-constrained with an `enum` type. This means we do hard-code for exactly those UD POS tags, and you can't store a value outside those integers in the `token.pos` attribute.

What you can do instead is use arbitrary tags, and just map them all to some UD tag like `X` or something. Then you can use the `token.tag` values you've set, and ignore the `token.pos` attribute. That should give you the results you're looking for.

If you want even further customisation, you could define your own tagger component that assigned to an extension attribute. If you have a look at the `Tagger` class in `spacy/pipeline.pyx`, you should see it's not so complicated.
