### ISSUE TITLE
doc.print_tree deprecation warnings points to wrong method

### ISSUE THREAD

**Issue by xrmx** [explosion/spaCy#3195]
## How to reproduce the behaviour

```
>>> doc.print_tree()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "doc.pyx", line 930, in spacy.tokens.doc.Doc.print_tree
ValueError: [E105] The Doc.print_tree() method is now deprecated. Please use Doc.json() instead.
>>> doc.json()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'spacy.tokens.doc.Doc' object has no attribute 'json'
```

doc.to_json() works fine :)

## Your Environment

* **spaCy version:** 2.1.0a6
* **Platform:** Linux-4.19.0-1-amd64-x86_64-with-debian-buster-sid
* **Python version:** 3.7.2
* **Models:** en_core_web_sm, it_core_news_sm

**Comment by ines** [comment]
Thans – that's definitly a typo!

Actually, we might re-add `Doc.print_tree` in 2.1.x, because the new `Doc.to_json` likely won't cover everything that `print_tree` does.
