### ISSUE TITLE
Macro Averaging

### ISSUE THREAD

**Issue by davidbren** [explosion/spaCy#3205]
## Feature description
Macro-averaging: Calculates the metrics for each class and averages the results, can this be added to the scorer library ?

**Comment by honnibal** [comment]
I agree that the current `Scorer` doesn't report quite enough detail, but I'd rather a general API improvement to it that say, returns the sets of correct and incorrect examples. Another option would be to have a hook to define more metrics.

I wouldn't really love just adding macro averages, though. It feels like the wrong granularity of solution to the problem.
