### ISSUE TITLE
Pretraining: batch size & document length

### ISSUE THREAD

**Issue by thomasopsomer** [explosion/spaCy#3216]
## Feature description

I was just testing the `pretrain` command and ran out of memory ^^ !
Looking at the code, it seems that the `batch_size` is fixed to 3000. I also noticed that document with length greater than 500 token are pruned by default. I guess this are default parameters for a corpus of sentence / small text... But maybe we should let the user set these parameters ?

**Comment by theudas** [comment]
I was looking into pretraining as well, since I only have a very limited number of labeled data and was hoping to boost the performance.  
Would it make sense to split the data in single sentences or maybe n-gram sentences?

**Comment by honnibal** [comment]
Try splitting into paragraphs or sentences at the moment, yeah. The `pretrain` command is still a bit rough in these respects --- it'll continue to improve.
