### ISSUE TITLE
Find closest word from vector

### ISSUE THREAD

**Issue by norkan** [explosion/spaCy#3219]
Hello !
I use this french model: fr_core_news_md
Could you please tell me if I understand how does it work: 579k keys, 20k unique vectors means 579k words mapped in (reduced to) 20k unique vectors ?
There is no method in Spacy to extract the closest token from a given vector ? If I calculate a vector value using token.vector (for example V=V2-V1+V3 using V=token2.vector - token1.vector + token3.vector) I have no method in Spacy to extract nearest tokens ?

Thank you !

I use last version of Spacy v2 on python 3.6, windows 7

**Comment by norkan** [comment]
Hello! Can SO help me to check these please ? Thank you!

**Comment by theudas** [comment]
This will probably help you: 
https://github.com/explosion/spaCy/issues/276
