### ISSUE TITLE
Multiprocessing doesn't buy much performance gain

### ISSUE THREAD

**Issue by CatalinVoss** [explosion/spaCy#3231]
## How to reproduce the behaviour

Here is a simple script that uses a process pool, loads a new spaCy model once for each worker and uses `nlp.pipe()` for better batching performance. Nevertheless, multi-processing this saves almost no time over the single-process implementation across various ProcessPool implementations (here using the native python one; also tested with Pathos).

```
import spacy
from multiprocessing import Pool
import cProfile

nlp = None

wisdom = "My fingers are long and beautiful, as, it has been well been " \
         "documented, are various other parts of my body. [...] He " \
         "referred to my hands, if they're small, something else must be " \
         "small. I guarantee you there's no problem. I guarantee it."


def process(big_doc):
    pr = cProfile.Profile()
    pr.enable()
    ##################################################################
    print("Parsing big doc %s" % big_doc)

    global nlp
    if nlp is None:
        nlp = spacy.load('en')
        print("Loaded Spacy with pipeline: %s" % nlp.pipe_names)
        # ==> ['tagger', 'parser', 'ner']

    # Call the parser using pipe per
    # https://github.com/explosion/spaCy/issues/1839
    all_gunk = [gunk for gunk in nlp.pipe([wisdom]*500)]

    ##################################################################
    pr.disable()
    pr.print_stats(sort='time')

    return len(all_gunk)

if __name__ == '__main__':
    p = Pool(8)
    print(p.map(process, [1, 2, 3, 4, 5, 6, 7,  9, 10]))
```

Specifically, when single-processing (i.e. running with `Pool(1)`), on my MBP, each call to `process()` takes ~4.5s. When multi-processing, the first child returns in 4.5s but all further children take >25s per call. Most of the time is spent in `ops.pyx:333(batch_dot)`.

```
         426522 function calls (411071 primitive calls) in 25.871 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      636   12.145    0.019   12.145    0.019 ops.pyx:333(batch_dot)
      126    3.628    0.029    3.628    0.029 {built-in method numpy.dot}
    870/0    1.416    0.002    0.000          nn_parser.pyx:435(_parseC)
  252/126    1.208    0.005    1.177    0.009 nn_parser.pyx:387(parse_batch)
      508    0.891    0.002    1.220    0.002 ops.pyx:452(seq2col)
      634    0.879    0.001    0.879    0.001 {built-in method numpy.concatenate}
       45    0.530    0.012    0.530    0.012 {method 'uniform' of 'mtrand.RandomState' objects}
        1    0.467    0.467    0.827    0.827 vocab.pyx:367(from_disk)
      635    0.333    0.001    0.468    0.001 _methods.py:91(_var)
      635    0.328    0.001    0.329    0.001 ops.pyx:419(maxout)
     1158    0.317    0.000    0.355    0.000 ops.pyx:158(allocate)
     7498    0.303    0.000    0.303    0.000 {method 'reduce' of 'numpy.ufunc' objects}
        1    0.298    0.298    0.298    0.298 vocab.pyx:450(lexemes_from_bytes)
      635    0.284    0.000    0.284    0.000 layernorm.py:102(_forward)
     2470    0.261    0.000    0.326    0.000 vocab.pyx:228(make_fused_token)
       30    0.219    0.007    0.224    0.007 <frozen importlib._bootstrap_external>:830(get_data)
        4    0.195    0.049    2.522    0.630 layernorm.py:43(predict)
      631    0.131    0.000    0.194    0.000 layernorm.py:70(_begin_update_scale_shift)
      631    0.103    0.000   10.723    0.017 maxout.py:66(begin_update)
       12    0.089    0.007    0.561    0.047 hash_embed.py:15(wrapped)
      ...
```

Is this happening because spaCy does sufficient multi-*threading* at the C++ level to make additional multi-processing at the python level "not worthwhile"? Is there any advice for making sure we max out the processor?

## Info about spaCy
* **spaCy version:** 2.0.18
* **Platform:** Darwin-18.2.0-x86_64-i386-64bit
* **Python version:** 3.6.5
* **Models:** en_core_web_sm, en

**Comment by CatalinVoss** [comment]
Seems that `OPENBLAS_NUM_THREADS=1` doesn't help much either

**Comment by honnibal** [comment]
Try `v2.1`, by installing `spacy-nightly`. You should find the multiprocessing performance is much better.

I think your main issue is that on OSX the Accelerate library is the one that numpy is calling into, and that doesn't respond to the `OPENBLAS_NUM_THREADS` environment variable. To address this, and make sure we're always using the same BLAS implementation across platforms, in v2.1 we've switched to providing our own package with the Blis kernels for matrix multiplication. Our Blis library is strictly single-threaded, solving the problem.

**Comment by CatalinVoss** [comment]
Much better indeed. Thank you! To be clear, multi-threading _within_ each process is still happening at the OpenMP level, correct? Would you recommend passing `n_threads=1` to account for that, assuming we max out the cores with multiple processes already?

The speedup with using `pipe()` also seems pretty dramatic with larger documents. I'm assuming that's for two reasons: (1) less python overhead, and (2) multithreading again? Is there a way to turn off (2) but still get the gains of (1)?

I guess I'm wondering if there's anything leftover where multiprocessing/threading could clash here?

**Comment by honnibal** [comment]
> To be clear, multi-threading _within_ each process is still happening at the OpenMP level, correct?

`spacy-nightly` should never be launching subthreads. It's possible I have some bug somewhere and a matrix multiplication gets handled by numpy, but the intention is to stay single-threaded. The idea is that the workload is embarrassingly parallel, so launching threads for small units of work is the wrong thing to do.

> `pipe()`

Yes, less overhead and fewer, larger matrix multiplications (so simd works better). Another minor effect is that a bit of computation is done to calculate the word representations, because we use subword features. In each minibatch, this is done once per word type, since it's not context sensitive. This caching works better if the minibatch is bigger.
