### ISSUE TITLE
Typo in https://spacy.io/api/cli#train-hyperparams

### ISSUE THREAD

**Issue by smartschat** [explosion/spaCy#3232]
In the descriptions for https://spacy.io/api/cli#train-hyperparams, it should be "Epsilon", not "Epsylon".

**Comment by svlandeg** [comment]
Hi @smartschat ! If you scroll down on that page and hit "Suggest edits", you can find the source file in which to correct the edit, and then create a Pull Request from your local fork to contribute directly (more info [in the getting started guide](https://github.com/explosion/spaCy/blob/master/CONTRIBUTING.md#getting-started)).

Ofcourse if you find multiple typo's, putting them together in one PR is most ideal!
