### ISSUE TITLE
what is shape in demo function

### ISSUE THREAD

**Issue by MohandesaliRahnema** [explosion/spaCy#3233]
hi how can i  call demo fun ?
what is parameters shape in it?

**Comment by ines** [comment]
I'm really not sure I understand the question. Could you provide more details and clarify?

**Comment by MohandesaliRahnema** [comment]
hi thank you for your answering
in page
https://github.com/explosion/spaCy/tree/master/examples/keras_parikh_entailment
in the first section of the page there is a fun def that says

def demo(shape):
....

i want to know how can i use this func?

**Comment by honnibal** [comment]
Hi,

You can find an example usage here: https://github.com/explosion/spaCy/blob/master/examples/keras_parikh_entailment/keras_decomposable_attention.py#L115
