### ISSUE TITLE
Unable to use spacy 2.0.18 with python 3.4?

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#3237]
Is Python 3.4 not compatible with the latest version of spacy (2.0.18)? 

I need to downgrade my environment to 3.4.x and was getting this error

```
(py34) D:\>conda install python=3.4
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - python=3.4
  - spacy=2.0.18 -> cymem[version='>=2.0.0,<2.1.0'] -> python[version='>=2.7,<2.
8.0a0']
  - spacy=2.0.18 -> msgpack-python[version='>=0.5.0']
  - spacy=2.0.18 -> numpy[version='>=1.15.4,<2.0a0'] -> *[track_features=blas_op
enblas]
Use "conda info <package>" to see the dependencies for each package.


```

I originally had python 3.4 installed in my environment but when I installed 2.0.18 conda had to upgrade python to 3.7.1 to resolve the dependencies.

**Comment by honnibal** [comment]
We don't test for Python 3.4, so we exclude it from the qualifiers and don't build it. I'm sorry if this causes inconvenience, but it's not the most useful version, and we need to keep our build matrix small to keep things somewhat sane.
