### ISSUE TITLE
Tokenization speed too slow for French

### ISSUE THREAD

**Issue by svlandeg** [explosion/spaCy#3242]
## Feature description
The evaluation on the UD corpora has shown that French tokenization is significantly slower (in words per second) than other languages. I'm opening this issue to experiment with a few ideas and discuss potential solutions.

#### Historical trail
Benchmarking the tokenizer has some flunctuations, but across runs this seems to be the general performance for the French blank model:
- early Jan 2019: 5-6K
- 30 Jan 2019 (from regex to re): 8-9K
- early Feb 2019 (after PR https://github.com/explosion/spaCy/pull/3218): 27-32K

![image](https://user-images.githubusercontent.com/8796347/52414271-25681900-2ae4-11e9-8f9f-8ea313e26af4.png)

**Comment by svlandeg** [comment]
I tried simplifying the `ALPHA` character class, which brings a lot of complexities because of Latin letters that are included but irrelevant for French, e.g. https://en.wikipedia.org/wiki/Latin_Extended-D.
I assumed that the large list of tokenization exceptions using the complicated `ALPHA` class would run faster when limiting to a much smaller set of Latin characters relevant to French only.

Unfortunately, this didn't seem to have much effect on the tokenization speed.

**Comment by svlandeg** [comment]
When I remove the [16K exceptions list](https://github.com/explosion/spaCy/blob/develop/spacy/lang/fr/_tokenizer_exceptions_list.py) entirely though, ofcourse some unit tests fail, but the UD evaluation accuracy remains almost the same on `fr_gsd-ud-train.txt`:
- Precision drops from 99% to 98%
- F-score stays at 99%

However, WPS rises to 73-74K!

**Comment by svlandeg** [comment]
If we do remove the exceptions, one potential direction is to also remove the [hyphens as infix](https://github.com/explosion/spaCy/blob/develop/spacy/lang/punctuation.py#L43) for French. This makes a lot of the current French exceptions redundant (most of the list + additional regular expressions), but will ofcourse result in some undersegmentation instead of oversegmentation.
- orig state: 0.1% under, 0.4% over, 99% precision, 99% F
- without exception list: 0.09% under, 0.7% over, 98% precision, 99% F
- **without hyphen as infix**: 0.2% under, 0.2% over, 99% precision, 99% F

This will bring WPS at around 90K.

I know the general trend is to move toward oversegmentation (because the models can learn to merge), but I'd be interested in hearing your opinion (@ines @honnibal) on how to move forward for French! I can prepare the PR accordingly.

**Comment by aborsu** [comment]
We actually use a custom french tokenizer (we just drop the exceptions) for all our in house models because of this.

**Comment by svlandeg** [comment]
Makes sense @aborsu. So do you then remove the hyphen as infix, too? Or do you have another solution to deal with names like `Sophie-Anne` ? Or is that not an issue on the data you're working with?

**Comment by aborsu** [comment]
@svlandeg we keep it as infix, but in our context it doesn't really matter. We mostly train models for entity detection, so the entity detector will recombine the tokens into a single entity. The fact that it is one or more token has no importance to us.
Of course this is specific for our use case, I wouldn't presume to make it standard behavior.

**Comment by honnibal** [comment]
@svlandeg Very interesting analysis!

I would lean towards removing the exceptions, and keeping the hyphen as an infix. Then we can hope that the model learns to rejoin the names etc in the parser. I'm happy to give this a try if you want to make the PR?

**Comment by svlandeg** [comment]
Ok, will prepare the PR !
