### ISSUE TITLE
Incorrect dependency tree for "there is..."

### ISSUE THREAD

**Issue by fersarr** [explosion/spaCy#3247]
The dependency tree is wrong for sentences that look like `there is a man..` or `there was a man...`
. The branch to 'man' is labeled as `attr` but I believe it should be `nsubj` as shown in the image from http://corenlp.run/ below.

## How to reproduce the behaviour
```
>>> nlp = spacy.load('en')
>>> parsed = nlp('there is a man outside')
>>> displacy.serve(parsed)
```

outputs:
![screen shot 2019-02-07 at 9 30 55 pm](https://user-images.githubusercontent.com/3913371/52444431-44849c00-2b20-11e9-8d2b-93127efa7029.png)

but I believe the arrow to 'man' should be 'nsubj' as in:
![screen shot 2019-02-07 at 9 36 30 pm](https://user-images.githubusercontent.com/3913371/52444499-77c72b00-2b20-11e9-8b1d-32e749b61535.png)

## Your Environment
* **spaCy version:** 2.0.18
* **Platform:** Darwin-18.2.0-x86_64-i386-64bit
* **Python version:** 3.7.0
* **Models:** en_core_web_md, en_core_web_lg, en

**Comment by ines** [comment]
Thanks – merging this with the master thread in #3052!

**Comment by fersarr** [comment]
Thanks! wasnt aware of it! If I find more like this, I will report them in the main thread then.
