### ISSUE TITLE
pickling of PhraseMatcher not resolved yet in version '2.1.0a6' (nightly build)

### ISSUE THREAD

**Issue by Abhijit-2592** [explosion/spaCy#3248]
#1971 Issue show that pickling is solved for PhraseMatcher. But, there still seems to be a bug in version **2.1.0a6**

Minimal reproducible example
```python
import spacy
from spacy.matcher import PhraseMatcher
import pickle

nlp = spacy.load("en")
matcher = PhraseMatcher(nlp.vocab, attr='LOWER')
matcher.add('president', None, nlp(u"Barack Obama"), nlp(u"Trump"))
matcher.add('health', None, nlp(u"health care reform"), nlp(u"hospital"))
print(len(matcher)) # shows 4
with open("./phrase_matcher.pkl", 'wb') as f:
    pickle.dump(obj=matcher,file=f)

with open("./phrase_matcher.pkl", 'rb') as f:
    loaded_matcher = pickle.load(f)
print(len(loaded_matcher)) # shows 0
```

## One more Bug:

According to documentation: `len(matcher)` should show 2 (only number of rule keys). But here it shows 4 (number of rules)

**Comment by Abhijit-2592** [comment]
@ines  Does this commit #3252 resolve it? How can get the latest one?

**Comment by ines** [comment]
Yes, my PR in #3252 should address my fix – we just need to review it and once it's merged, it'll be included in the next nightly. If you can't wait to test it, you can also build my `fix/phrasematcher-pickle-len` branch from source.

**Comment by Abhijit-2592** [comment]
@ines thanks a lot for your quick response
