### ISSUE TITLE
NLP for URLS returns SystemError spacy.tokenizer.Tokenizer returned NULL

### ISSUE THREAD

**Issue by mrtomo** [explosion/spaCy#3250]
Hi Everyone,
i use the Spacy NLP to reduce texts with some Bag Of words features. Those texts have URLs in the text that should be interpreted as one token. From my experience this worked on my Mac until december. I switched to a Windows operating system lately. Both times Chrome with Anaconda.
The issue is as follows:

```
import spacy
from spacy.attrs import LOWER, POS, ENT_TYPE, IS_ALPHA
from spacy.tokens import Doc
nlp = spacy.load('en_core_web_md')
#also tried this with en for spacy.load()
nlp('github.com')
```
returns
```---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
<ipython-input-5-85ef623d91d6> in <module>
      6 #also tried this with en for spacy.load()
      7 
----> 8 nlp('github.com')

~\AppData\Local\Continuum\anaconda3\lib\site-packages\spacy\language.py in __call__(self, text, disable)
    338             raise ValueError(Errors.E088.format(length=len(text),
    339                                                 max_length=self.max_length))
--> 340         doc = self.make_doc(text)
    341         for name, proc in self.pipeline:
    342             if name in disable:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\spacy\language.py in make_doc(self, text)
    370 
    371     def make_doc(self, text):
--> 372         return self.tokenizer(text)
    373 
    374     def update(self, docs, golds, drop=0., sgd=None, losses=None):

SystemError: <spacy.tokenizer.Tokenizer object at 0x1110DEF0> returned NULL without setting an error
```

* Operating System: Windows 7 Enterprise
* Python Version Used: Juypiter Notebook 5.7.4, , Pyhton 3
* spaCy Version Used:SpaCy 2.0.16
* Environment Information: Import for the NLP was done for en and en_core_web_md

The issue happens if there are two texts seperated with a dot or the URL that (usually) has a dot for the subdomain, host ...

**EDIT:** One more thing to mention: The jupyter notebook is stored in a synchronized dropbox. I thought this could impact it somehow. Copied the file to my desktop and run it again: Same result as described.

Thanks for your help, really appreciate it.
BR
Tom

**Comment by ines** [comment]
I've never seen this error before and it definitely sounds like some problem related to your environment – especially considering you switched recently.

Could you check that the Python you're running is 64bit? And could you run `python -m spacy validate` and double-check that the models are up to date?

**Comment by mrtomo** [comment]
Hi Ines,
did try same procedure on my Mac again. But have to update some libraries to the same version as on the Windows PC. Currently the problem with the same Jupyter notebook does not exist. 
Will keep you posted.

Also the SystemError looks like some data-storage that cannot be accessed. 
May have to use the good old Mac in this case.
BR, Tom

**Comment by ines** [comment]
>  Python running on Windows is 32 Bit Version due to (sad) regulations on the Computer.

This is most likely the problem then – spaCy required 64 bit Python and if you try to run it with the 32 bit version, you'll come across all kinds of weird problems like this.

I'm closing this but if you do end up with other problems on 64 bit, feel free to reopen. Btw, @honnibal is using Windows Subsystem for Linux on his Windows laptop and it's been working well for him – so if that's an option for you, you could try that as well?
