### ISSUE TITLE
Custom trained NER not displaying 'new_model_name' given in output directory

### ISSUE THREAD

**Issue by arindam77** [explosion/spaCy#3254]
<Once, I save a custom trained NER model with new added label, will the new added model name which is 'animal' in the example given(https://spacy.io/usage/training#section-ner), will this 'animal' name come as a file/package in the output dir with the same name given or will you get only the files(ner,parser,tagger,vocab) in the output directory without the model name ''?>

**Comment by ines** [comment]
Sorry if this was confusing! The model data will be directly written to the output directory. The `nlp.to_disk` model will place the files in the directory specified, and won't create any parent directories.

The model name is what will be added to the `meta.json` as the  `"name"`. So for example, if you're training an English model named `"animal"`, the full model name will be `"en_animal"`. If you're packaging your model later on using [`spacy package`](https://spacy.io/api/cli#package), your package will then be `en_animal`, and you'll be able to load your model as `spacy.load('en_animal')`.
