### ISSUE TITLE
Process a txt file with spacy

### ISSUE THREAD

**Issue by rmiaouh** [explosion/spaCy#3257]
(first of all sorry, for my english)
Hi, i use the spacy NER model

What i want now is to convert my .txt file : 

    ("Uber blew through $1 million a week", [(0, 4, 'ORG')]),
    ("Android Pay expands to Canada", [(0, 11, 'PRODUCT'), (23, 30, 'GPE')]),
    ("Spotify steps up Asia expansion", [(0, 8, "ORG"), (17, 21, "LOC")]),
    ("Google Maps launches location sharing", [(0, 11, "PRODUCT")]),
    ("Google rebrands its business apps", [(0, 6, "ORG")]),
    ("look what i found on google! 😂", [(21, 27, "PRODUCT")])]

to the the TRAIN_DATA variable.
I don't know why the model can't read my txt file. I transformed it to a list but that doesn't work too.

Can someone help me ?

**Comment by ines** [comment]
If you want to store data in a separate file, JSON is probably a better option than plain text. For more details on how to load and parse JSON data in Python, see this article: https://realpython.com/python-json/

**Comment by rmiaouh** [comment]
Thank for all,

i followed your article and this answer you gave in an other issue : 

`A simpler way might be working with JSON. Here's a an example of a file `data.json`:

```json
[
    ["Who is Shaka Khan?", {"entities": [[7, 17, "PERSON"]]}],
    ["I like London and Berlin", {"entities": [[7, 13, "LOC"], [18, 24, "LOC"]]}]
]
```

JSON doesn't have tuples, so you need to use lists everywhere. In Python, you can then do the following:

```python
import json
import io

with io.open('/path/to/data.json', encoding='utf8') as f:
    train_data = json.load(f)
````
