### ISSUE TITLE
PhraseMatcher returns empty list while trying to tag more than one item inside document

### ISSUE THREAD

**Issue by arindam77** [explosion/spaCy#3261]
PhraseMatcher returns empty list while trying to tag more than one item inside a document. I am passing values from a column in a csv to tag product names inside the document but PhraseMatcher is only tagging for rows with one string. When there are more than one elements for tagging, it's returning an empty list. What's the solution for this

```
import spacy
import re
import csv
from spacy.matcher import PhraseMatcher

#Function to convert PhraseMatcher return value to string indexes 
def str_index_conversion(lbl, doc, matchitem):
    o_one = len(str(doc[0:matchitem[1]]))
    subdoc = doc[matchitem[1]:matchitem[2]]
    o_two = o_one + len(str(subdoc))
    return (o_one, o_two, lbl)

#nlp = spacy.blank('en')
nlp = spacy.load('en')

if 'ner' not in nlp.pipe_names:
    ner = nlp.create_pipe('ner')
    nlp.add_pipe(ner)
else:
    ner = nlp.get_pipe('ner')

ner.add_label('PRODUCT')     

DIR = 'C:\\Users\\Lenovo\\.spyder-py3\\smoke\\'
matcher = PhraseMatcher(nlp.vocab)


list_str_index = []
to_train_ents = []
with open('qq1.csv', newline='') as myFile:
    
    reader = csv.reader(myFile)
    for row in reader:
        try:
            product = row[0].lower()
            filename = row[1]
            #print(product)
            file = open(DIR+filename, "r", encoding ='utf-8')
            filecontents = file.read()
            #print(product)
            for s in filecontents:
                filecontents = re.sub(r'\[[0-9]*\]', ' ', filecontents)
                filecontents = re.sub(r'\s+', ' ', filecontents)
                #filecontents = filecontents.encode().decode('unicode-escape')
                filecontents = ''.join([line.lower() for line in filecontents])                
                print(product.split())
                matcher.add('PRODUCT', None, nlp(product))
                doc = nlp(filecontents)
                matches = matcher(doc)
                        #print(matches)
                list_str_index = [str_index_conversion('PRODUCT', doc, x) for x in matches]
                to_train_ents.append((filecontents, dict(entities=list_str_index)))
                break
            
        except Exception as e:
            #print(e)
            pass`
```

The "to_train_ents" list is returning an empty list when there are more than one elements to tag inside the doc. The elements to tag are provided in the form of a csv as attached below:
`SAMPLE CSV:

```
PRODUCT          FILES
ABC              XXXX
ABC2, ABC3, BCA3 XXXX
BC2              XXXX
```
So, in the case of the 2nd row, it's returning an empty list in the to_train_ents list. What's the solution to tag such cases in the doc

**Comment by ines** [comment]
See my comment in https://stackoverflow.com/questions/54645926/phrasematcher-returns-empty-list-while-trying-to-tag-more-than-one-item-inside-d#comment96093196_54645926:

> Are you able to create simplified, reproducible example that only shows the behaviour of the `PhraseMatcher`, without opening a file, string conversion etc.? 
> 
> Before trying it, my first instinct would be that there's *some* error in your huge `try` block. Having a naked `try`/`except` like this is usually not a very good practice. If something goes wrong in one of the almost 20 lines (!) in `try`, the `except` block will trigger, nothing will be appended to your list (so you'll end up with an empty list) and you'll have no idea why and no error message to help you (like in this case now).
