### ISSUE TITLE
batch_size parameter is hard-coded in nlp.evaluate()

### ISSUE THREAD

**Issue by tamarit** [explosion/spaCy#3263]
## How to reproduce the behaviour
Hi,

first of all congratulations for your nice tool. It is really powerful. 

I was training a model using CLI commands with relatively small dataset. Then, I increased the size of the training dataset (and consequently of the development dataset) and start getting problems. It was training till suddenly stopped at ~26%, then printed some "tcmalloc: large alloc ..." and stopped. My computer is 8 GB of RAM, so I ask a workmate to run the same with his computer with 32GB of RAM. He could run it perfectly. So the problem was related to the memory. 

After some code inspection, prints ,etc I discovered that the problem was here:

https://github.com/explosion/spaCy/blob/master/spacy/language.py#L485

The hard-coded batch_size value is too big for my system, so I modified the module placing a smaller value and then I could use the CLI for training without any problem. 

Additionally, the fact I commented above that the training stopped at ~26%, is due to that it is discarding a lot of documents due to max_doc_len default value. This is expected but percentage should be updated accordingly and it is not. This problem  is related to the way the pbar is updated here:

https://github.com/explosion/spaCy/blob/master/spacy/cli/train.py#L135

which is not correct since it should take into account the unfiltered batch. I would suggest to add a batch_initial variable just before replacing the value of batch:

https://github.com/explosion/spaCy/blob/master/spacy/cli/train.py#L129

So it could be used afterwards when updating pbar. 

Thanks in advance!

## Info about spaCy
* **Python version:** 3.5.2
* **Platform:** Linux-4.4.0-45-generic-x86_64-with-Ubuntu-16.04-xenial
* **spaCy version:** 2.0.18
* **Models:** es

**Comment by honnibal** [comment]
I think these issues should be resolved in v2.1. Could you try again with `spacy-nightly` and let me know how you go?

**Comment by tamarit** [comment]
Thanks @honnibal for your prompt answer. 

I have tried nightly version and results were even worse than with stable version.

**Comment by honnibal** [comment]
Added the setting in `Language.evaluate()`
