### ISSUE TITLE
How can we use PhraseMatcher for the languages which are doesn't have any language model in spacy 

### ISSUE THREAD

**Issue by tiru1930** [explosion/spaCy#3269]
Hi 
I want to use PhraseMatcher for languages like Slovak and other which doesn't have a spacy model or languages support.

How can use this PhraseMatcher in those cases, Do I need to add basic language support code to spacy like stop words, tokenizer etc, or Is there any workaround.

**Comment by ines** [comment]
If the language you want to use doesn't require very specific tokenization, you could also use a different similar language class or the [`MultiLanguage` class](https://spacy.io/usage/models#multi-language), which only includes the very basic tokenization rules:

```python
from spacy.lang.xx import MultiLanguage
nlp = MutliLanguage()
# and so on
```

(That said, if you do have time and want to add basic language support for Slovak and/or one of the other Slavic languages that are still missing, we'd always appreciate a pull request!)
