### ISSUE TITLE
Get NER Parser loss for validation & test datasets

### ISSUE THREAD

**Issue by michaelpetruzzellocivicom** [explosion/spaCy#3272]
Currently there is no easy way to get the NER Parser loss for validation and test datasets. The multilabel log loss is being calculated on the internal states of SpaCy so it isn't something that can be done by comparing entity predictions and actual entities outside of SpaCy.

This would basically be the Pipe.get_loss method, but for the NER Parser.

**Comment by honnibal** [comment]
It's true that there's no easy way to get this, but I'm not sure I like the idea of a separate method. We'd end up duplicating code for something that's only marginally useful to most users. I'm not sure what the best solution is --- I don't love adding options to the main methods either.

**Comment by michaelpetruzzellocivicom** [comment]
By itself it may not sound useful, but I use this information to create different learning curves to take out some of the guess work of what will best improve the current algorithm:

![image](https://user-images.githubusercontent.com/12663419/53022091-7ce17f80-3428-11e9-8fbf-bf1a2e1b4ec7.png)

![image](https://user-images.githubusercontent.com/12663419/53022164-9f739880-3428-11e9-8f30-9e524be28d12.png)

![image](https://user-images.githubusercontent.com/12663419/53022218-b74b1c80-3428-11e9-9a93-9ff945f08c79.png)

**Comment by honnibal** [comment]
Why not use accuracy for that though?

The loss on the NER and parsing models is a bit hard to interpret, because it's trying to predict zero-cost transitions. So if it makes a costly error once, and then proceeds in that bad state, it might have a lot of low-cost transitions on a sentence it still scores poorly on. I think the accuracies will be much easier to reason about.

**Comment by michaelpetruzzellocivicom** [comment]
I haven't seen more abstract metrics used before for this graphing purpose, but I am trying it out now with F1 for document classification to see how they compare with previously generated loss graphs. And then I will try it with NER.

Do you use graphing of this sort with accuracy in your own experimentation?

**Comment by honnibal** [comment]
I don't typically, no. I usually print a few numbers to the command line. I think I'm a less visual thinker than most.

**Comment by michaelpetruzzellocivicom** [comment]
At first I was surprised to hear you say that, but it makes sense. You're focusing on creating a generalized algorithm that performs well regardless of the dataset input.

My use case is a bit different. I'm creating 100s of models to solve different classification tasks through a combined grid search and bayesian optimization automated hyper tuning. The graphs are part of diagnostic information so I can see how the automated system is performing and how it can perform better.

**Comment by honnibal** [comment]
How about this as a solution:

```python

ner = nlp.get_pipe('ner')
losses = {}
for batch in spacy.util.minibatch(zip(dev_docs, dev_golds), size=128):
    docs, golds = zip(*batch)
    ner.update(docs, golds, sgd=None, losses=losses)
```

Passing `sgd=None` means that no weight updates will be made, but the `ner.update()` method does calculate a loss. It's a bit wasteful because you're computing all the backprop for nothing, but hopefully the runtime difference won't matter too much for you.

**Comment by michaelpetruzzellocivicom** [comment]
Thank you! This is great!

I was thinking passing the sgd as None would cause it to be instantiated later on, which would have been problematic because all models are cached in memory in my API due to the slow load time from disk.

**Comment by honnibal** [comment]
Glad to provide a solution!

For future reference, the `sgd` value can also be a function like this:

```python
def mock_optimizer(W, dW, key=None):
    return None
```

There are no type-checks or anything, so you can pass in a function like that to spy on the gradients being generated.
