### ISSUE TITLE
Token.sent (via Span.sent) relies on dependency parse

### ISSUE THREAD

**Issue by chbrown** [explosion/spaCy#3274]
The [docs](https://spacy.io/api/token) say `Token.sent` is a property returning "The sentence span that this token is a part of." But, surprisingly, when disabling the parser and using a custom sentence boundary detector, like [the one in the docs](https://spacy.io/usage/processing-pipelines#component-example1) (which produces proper `Span`s when calling `Doc.sents`), `Token.sent` always returns a singleton `Span` containing _just_ that token. 

This is because [`Token.sent`](https://github.com/explosion/spaCy/blob/v2.0.18/spacy/tokens/token.pyx#L366) hands off to [`Span.sent`](https://github.com/explosion/spaCy/blob/v2.0.18/spacy/tokens/span.pyx#L297-L303), which depends on a full dependency parse, because it follows the dependency tree upward until `head == 0`. This is a problem, because with the parser disabled, every token is effectively already at the root of its tree. Thus the singleton `Span`s.

## How to reproduce the behaviour
```python
# this is all straight from the example in the docs except for the disable=[...] setting 
# and deleting the add_pipe(..., before='parser') placement
import spacy
def sbd_component(doc):
    for i, token in enumerate(doc[:-2]):
        if token.text == '.' and doc[i+1].is_title:
            doc[i+1].sent_start = True
    return doc
nlp = spacy.load('en_core_web_sm', disable=['parser', 'ner']) # disable parser and ner for speed
nlp.add_pipe(sbd_component) # order in pipeline defaults to last
doc = nlp('This is a sentence. This is another sentence.')
```
Let's give it a shot:
```python
sent0 = next(doc.sents)
assert sent0.text == 'This is a sentence.'  # checks out :)
```
That's all well and good, but then:
```python
assert doc[0].sent == sent0 # nope - raises AssertionError :(
```

## Workaround/fix
The following helpers rely on `Token.is_sent_start` and produce the expected output, but I'm not sure if this is the optimal way.
```python
def Span__sent(span):
    # look left for nearest sent start
    l_edge = span.start
    while l_edge > 0 and not span.doc[l_edge].is_sent_start:
        l_edge -= 1
    # look right for next sent start
    r_boundary = span.end
    while r_boundary < len(span.doc) and not span.doc[r_boundary].is_sent_start:
        r_boundary += 1
    return span.doc[l_edge:r_boundary]
        
def Token__sent(token):
    return Span__sent(token.doc[token.i : token.i+1])

assert Token__sent(doc[0]) == sent0  # yay!
```

## Your Environment
* **spaCy version:** 2.0.18
* **Platform:** Darwin-18.2.0-x86_64-i386-64bit
* **Python version:** 3.7.2
* **Models:** en_core_web_sm

**Comment by honnibal** [comment]
Thanks for the nice analysis! I think you're definitely correct that there's a mismatch here.

More generally, we do allow custom hooks for sentences, which could be calculated using other heuristics. If you have a look at the `doc.sents` implementation, you'll see that it might delegate to a custom handler.

It's a tricky problem though, because it means we'd be calling into this handler on every token for the full doc, as there's no way to cache the output.

**Comment by honnibal** [comment]
Wait, scratch that...This shouldn't be tricky at all. I misread this; I think it's just a bug and should have a straight-forward fix.

...And in fact it seems to be fixed on develop! If you try `spacy-nightly`, I think you'll find this is resolved. Thanks again for the report.
