### ISSUE TITLE
Inconsistent training performance between 2.0.18 and 2.1.0

### ISSUE THREAD

**Issue by ahalterman** [explosion/spaCy#3278]
I was experimenting with using `spacy pretrain` (#2931) to train an Arabic NER model on OntoNotes data and encountered very poor performance from `spacy train` in `spacy-nightly` (2.1.0a6) both with and without the pretrained `tok2vec` model. More importantly, `spacy train` without any pretraining gives an order of magnitude worse performance between 2.0 and 2.1 (NER F1 of 81.7 vs. 6.9).

The two spaCys are each in a fresh virtual environment.

## Run 1: spaCy 2.0.18, no pretrained vectors

```
(spacy_2-0-18) python -m spacy train ar model-onto onto-json/train.json onto-json/dev.json --no-tagger --no-parser

Itn.  Dep Loss  NER Loss  UAS     NER P.  NER R.  NER F.  Tag %   Token %  CPU WPS  GPU WPS
... [omitting the earlier rounds]
29    0.000     49.658    0.000   86.686  77.382  81.770  0.000   86.421   16737.8  0.0
```

## Run 2: spaCy 2.0.18, with pretrained fasttext vectors

The performance with a fasttext vector model is lower here, which is unexpected.

```
(spacy_2-0-18) python -m spacy train ar model-onto onto-json/train.json onto-json/dev.json --no-tagger --no-parser --vectors  ../spacy-dev-resources/ar_vector_model

Itn.  Dep Loss  NER Loss  UAS     NER P.  NER R.  NER F.  Tag %   Token %  CPU WPS  GPU WPS
[...]
29    0.000     10.377    0.000   60.358  56.440  58.333  0.000   86.421   12338.3  0.0
```

## Run 3: Using spaCy 2.1.0a6, with pretraining

The performance is quite bad. Maybe Run 2 indicates that this is an issue with the vectors used in pretraining? I'm not sure. There's also a relatively minor error that occurs after training.

```
(spacy-nightly) python -m spacy train ar model-t2v onto-json/train.json onto-json/dev.json -t2v /home/ahalt/spacy-dev-resources/pretrained/model25.bin -p ner 

Itn.  Dep Loss  NER Loss  UAS     NER P.  NER R.  NER F.  Tag %   Token %  CPU WPS  GPU WPS
[...]
 29       0.000     683.114    0.000    9.627    6.492    7.755    0.000   14.128    26182        0
```

The training concluded successfully, but then produced an error: `ValueError: Can't read file: model-t2v/model-best/accuracy.json
`

<details>
```
Traceback (most recent call last):
  File "/home/ahalt/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ahalt/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ahalt/spacy-nightly/lib/python3.6/site-packages/spacy/__main__.py", line 38, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/home/ahalt/spacy-nightly/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/ahalt/spacy-nightly/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/ahalt/spacy-nightly/lib/python3.6/site-packages/spacy/cli/train.py", line 301, in train
    best_model_path = _collate_best_model(meta, output_path, nlp.pipe_names)
  File "/home/ahalt/spacy-nightly/lib/python3.6/site-packages/spacy/cli/train.py", line 344, in _collate_best_model
    bests[component] = _find_best(output_path, component)
  File "/home/ahalt/spacy-nightly/lib/python3.6/site-packages/spacy/cli/train.py", line 361, in _find_best
    accs = srsly.read_json(epoch_model / "accuracy.json")
  File "/home/ahalt/spacy-nightly/lib/python3.6/site-packages/srsly/_json_api.py", line 49, in read_json
    file_path = force_path(location)
  File "/home/ahalt/spacy-nightly/lib/python3.6/site-packages/srsly/util.py", line 11, in force_path
    raise ValueError("Can't read file: {}".format(location))
ValueError: Can't read file: model-t2v/model-best/accuracy.json
```
</details>

## Run 4: Using spaCy 2.1.0a6, **without** pretraining

This is the puzzling result: without pretraining, the two `spacy train` commands should produce roughy equal results. But 2.1.0's performance is an order of magnitude worse than 2.0.18's:

```
(spacy-nightly) python -m spacy train ar model-no_t2v onto-json/train.json onto-json/dev.json -p ner

Itn    Dep Loss    NER Loss      UAS    NER P    NER R    NER F    Tag %  Token %  CPU WPS  GPU WPS
[...]
 29       0.000     684.263    0.000    7.416    6.492    6.924    0.000   14.128    28649        0
```

I'm happy to run the experiment with English OntoNotes if it would be helpful.

## Your Environment
* **spaCy version:** 2.0.18 OR 2.1.0a6 (different virtual envs)
* **Platform:** Linux-4.15.0-45-generic-x86_64-with-debian-buster-sid
* **Python version:** 3.6.5

**Comment by honnibal** [comment]
The `Token %` figure looks super suspicious. It's getting 15% tokenization accuracy. Did something change in the Arabic tokenizer? I haven't been tracking this, but if you could have a look at the tokenization and check whether something's broken, that would be super helpful.

**Comment by ahalterman** [comment]
Hmm, yeah, I didn't notice the bad token accuracy. It doesn't look like anything changed in `lang/ar/` in between the two releases, though. Let me re-do the two `spacy train` steps with English and see what happens.

**Comment by honnibal** [comment]
I wonder whether this is the same bug as https://github.com/explosion/spaCy/issues/3209

I'm leaning towards no, because of that tokenization accuracy bug. But it might be something to think about.

**Comment by ahalterman** [comment]
It's definitely not happening with English (I got an F1 of 80 without vectors or pretraining), and also you would have caught that in your experiments.

I'll clone and compile `develop` and see if that fixes it, and if not, I can compare the per-document tokenizing being done by 2.0.18 and 2.1.

**Comment by honnibal** [comment]
I think I know what might be going on.

Are the gold-standard tokens in your text vowelised? It could be that the new alignment code isn't handling this well, as I think it more strongly expects the gold-standard text to match up with the raw text.

**Comment by honnibal** [comment]
Closing this now that v2.2 is out. Please reopen if there's new insights with the new version.
