### ISSUE TITLE
displaCy looks weird on Windows

### ISSUE THREAD

**Issue by mfelice** [explosion/spaCy#328]
displaCy looks weird in Firefox, Internet Explorer and Chrome on Windows. Looks good on Ubuntu, though.

**Comment by inesmontani** [comment]
Hey, thanks for the heads-up! Do you have a screenshot or more details about what looks weird in particular? I've tested it in Windows 8 and Window 10 and the only thing I noticed was that there seems to be a problem with the rendering of the font ("Inconsolata"), especially in Firefox – which is indeed a little strange. Will look into that!

**Comment by Terrilocks** [comment]
I have a similar problem: screenshot attached.

The dropdown boxes let you choose the pos tag or parse label for an arc or token, although I don't think they actually do anything.

![displacy](https://cloud.githubusercontent.com/assets/16025737/14429758/ab9711e6-fff6-11e5-94a3-82cc37274b3f.png)

**Comment by inesmontani** [comment]
Thanks for the screenshot! Is this Internet Explorer? This really seems like a font issue, plus a few browser-specific form element fixes.

The dropdowns let you manually edit the tag and labels, which is probably more relevant in annotation mode. For example, you could create and illustrate a deliberately incorrect parse, or correct mistakes made by the model.

**Comment by mfelice** [comment]
@Terrilocks showed what happens in Internet Explorer. Here's a screenshot of what happens in Chrome and Firefox.

![displacy-chrome](https://cloud.githubusercontent.com/assets/11545607/14432252/3cc042a0-0001-11e6-93d3-ca75783f682b.PNG)

I also realised that if you are using a resized window and the "Parse" and "Annotate" buttons are shown below the main textbox (as in my screenshot), any attempt to click the buttons will make them disappear, so you cannot click them.
