### ISSUE TITLE
Spacy Web page Example Not Working

### ISSUE THREAD

**Issue by shenaimm** [explosion/spaCy#3287]
## How to reproduce the behaviour
import spacy
from spacy.matcher import Matcher

nlp = spacy.load('en_core_web_sm')
matcher = Matcher(nlp.vocab)

Get the ID of the 'EVENT' entity type. This is required to set an entity.
EVENT = nlp.vocab.strings['EVENT']

def add_event_ent(matcher, doc, i, matches):
    # Get the current match and create tuple of entity label, start and end.
    # Append entity to the doc's entity. (Don't overwrite doc.ents!)
    match_id, start, end = matches[i]
    entity = (EVENT, start, end)
    doc.ents += (entity,)
    print(doc[start:end].text, entity)

matcher.add('GoogleIO', add_event_ent,
            [{'ORTH': 'Google'}, {'ORTH': 'I'}, {'ORTH': '/'}, {'ORTH': 'O'}],
            [{'ORTH': 'Google'}, {'ORTH': 'I'}, {'ORTH': '/'}, {'ORTH': 'O'}, {'IS_DIGIT': True}])

doc = nlp(u"This is a text about Google I/O 2015.")
matches = matcher(doc)

I ran this code on the spacy webpages under the section Adding on_match rules. And I am getting the following error:-

``---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-e4bf6d350c29> in <module>
     21 
     22 doc = nlp(u"This is a text about Google I/O 2015.")
---> 23 matches = matcher(doc)

matcher.pyx in spacy.matcher.Matcher.__call__()

<ipython-input-1-e4bf6d350c29> in add_event_ent(matcher, doc, i, matches)
     13     match_id, start, end = matches[i]
     14     entity = (EVENT, start, end)
---> 15     doc.ents += (entity,)
     16     print(doc[start:end].text, entity)
     17 

doc.pyx in spacy.tokens.doc.Doc.ents.__set__()

ValueError: [E098] Trying to set conflicting doc.ents: '(5, 8, 'ORG')' and '(5, 9, 'EVENT')'. A token can only be part of one entity, so make sure the entities you're setting don't overlap.``

The link to the web page --> [link](https://spacy.io/usage/linguistic-features#section-rule-based-matching)

**Comment by ines** [comment]
Thanks! This is indeed a bad example, because spaCy now (correctly!) raises an error if two entities are overlapping, since a token can only be part of an entity. I updated the example for 2.1 and also added note about the new `EntityRuler`, which will handle those kinds of things automatically.
