### ISSUE TITLE
Bug with Matcher in v2.1.0a7

### ISSUE THREAD

**Issue by mr-bjerre** [explosion/spaCy#3290]
Strange results on the `Matcher`. I would expect the following to output `$2,174` but I see

    $2,174
    $2,174 million

Reproducible example

    import spacy
    from spacy.matcher import Matcher
    nlp = spacy.load('en')

    text = 'Consolidated sales of $2,174 million.'
    patterns = [
        [
            {'LIKE_NUM': True, 'OP': '+'},
            {'LOWER': {'IN': ['placeholder', ]}},
        ],
        [
            {'LIKE_NUM': True, 'OP': '+'},
            {'NORM': '$'},
        ],
        [
            {'NORM': '$'},
            {'LIKE_NUM': True, 'OP': '+'},
        ],
    ]
    matcher = Matcher(nlp.vocab)
    matcher.add('MONEY', None, *patterns)
    doc = nlp(text)
    print('\n'.join([doc[start:end].text for _, start, end in matcher(doc)]))

If I change patterns to (adding a different pattern before - the order is important for some reason)

    patterns = [
        [
            {'LOWER': {'IN': ['placeholder', ]}},
            {'LIKE_NUM': True, 'OP': '+'},
        ],
        [
            {'LIKE_NUM': True, 'OP': '+'},
            {'LOWER': {'IN': ['placeholder', ]}},
        ],
        [
            {'LIKE_NUM': True, 'OP': '+'},
            {'NORM': '$'},
        ],
        [
            {'NORM': '$'},
            {'LIKE_NUM': True, 'OP': '+'},
        ],
    ]
    matcher = Matcher(nlp.vocab)
    matcher.add('MONEY', None, *patterns)
    doc = nlp(text)
    print('\n'.join([doc[start:end].text for _, start, end in matcher(doc)]))

then I get zero matches.

## Info about spaCy

* **spaCy version:** 2.1.0a7
* **Platform:** Linux-4.15.0-45-generic-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.6.7
* **Models:** en

**Comment by ines** [comment]
I'll merge this with #1971, because it sounds pretty similar to some of the other examples reported there (custom attributes, incomplete matches, order matters etc.). We've already identified one issue so I suspect all the problems might come down to the same one or two bugs.
