### ISSUE TITLE
Lemmatizer doesn't always work for capitalized text (text in all caps and first letter capitalized cases)

### ISSUE THREAD

**Issue by c-streams** [explosion/spaCy#3297]
**How to reproduce the behaviour**

The lemmatizer doesn't always work properly when text is provided in uppercase or is capitalized. In the example below, IDENTIFIED and Identify are not lemmatized, GROUPING and MASKS are not lemmatized, however INSTRUCTIONS is lemmatized. 

```
nlp = spacy.load('en_core_web_sm')
doc = nlp(u"IDENTIFIED Identified identified MISTAKES WITH GROUPING grouping MASKS INSTRUCTIONS Masks")
[token.lemma_ for token in doc]
>>> ['identified', 'identified', 'identify', 'mistakes', 'with', 'grouping', 'group', 'masks', 'instruction', 'mask']  
```

**Your Environment**

* Operating System: macOS High Sierra 10.13.6
* Python Version Used: 3.6.5 
* spaCy Version Used: 2.0.18

**Comment by honnibal** [comment]
I think this comes down to errors in the part-of-speech tagger. If the tagger makes an incorrect prediction, the lemmatizer is likely to do the wrong thing. It's true that we'd like the part-of-speech tagger to be more case insensitive, but that's a more general issue.

Closing to merge with the mispredictions master thread, #3052 .
