### ISSUE TITLE
Merge spans is very slow on new nightly a7

### ISSUE THREAD

**Issue by nyejon** [explosion/spaCy#3300]
The span merging is much slower on the new spacy version. Previously my pipeline ran on a document in about 5s and now it takes over 45s and sometimes even up to 90s for the same document.

## How to reproduce the behaviour

Using a matcher with many matches the speed has decreased significantly from a6 when merging the spans. 

## Your Environment

* **spaCy version:** 2.1.0a7
* **Platform:** Darwin-18.2.0-x86_64-i386-64bit
* **Python version:** 3.7.1
* **Models:** en_core_web_md, de_core_news_md

**Comment by ines** [comment]
Could you share the code you're running, especially the part that performs the merging? And are you merging in an `on_match` callback or afterwards?

**Comment by honnibal** [comment]
Are you using the new bulk merge? The new workflow should be like:

```python

with doc.retokenize() as retokenizer:
    retokenizer.merge(span, attrs={})
```

**Comment by nyejon** [comment]
Hi @ines and @honnibal,

The code I am using comes from one of the examples in a matcher. Here are the various options I tried:

```
    def __call__(self, doc):
        """Find matches in document and add them as entities.
        doc (Doc): The Doc object in the pipeline.
        RETURNS (Doc): The Doc with added entities, if available.
        """
        t = datetime.now()
        matches = list(self.matcher(doc))
        # Remove duplicate matches
        matches = set([(m_id, start, end) for m_id, start, end in matches
                       if start != end])

        # Sort on the match_id (Prefer type1 to type2 and then the length and then the start token)
        def get_sort_key(m): return (m[0], m[2] - m[1], m[1])
        matches = sorted(matches, key=get_sort_key, reverse=False)
        entities = list(doc.ents)
        new_entities = []
        seen_tokens = set()
        for match_id, start, end in matches:
            # If there is any other entity in the match then only replace the entity
            # if the self.overwrite is True.
            if any(t.ent_type for t in doc[start:end]) and not self.overwrite:
                continue
            # check for end - 1 here because boundaries are inclusive

            if start not in seen_tokens and end - 1 not in seen_tokens:
                entity = Span(doc, start, end, label=self.label)
                new_entities.append(entity)
                # Removes overlapping entities
                entities = [e for e in entities
                            if not (e.start < end and e.end > start)]
                seen_tokens.update(range(start, end))
        doc.ents = entities + new_entities

        for span in new_entities:
            # Iterate over all spans and merge them into one token. This is done
            # after setting the entities – otherwise, it would cause mismatched
            # indices!
            span.merge()
        print(f"Matcher time {(datetime.now() - t).total_seconds()}s")
        return doc
```

@honnibal 

I have also tried replacing the last bit like this:

```
with doc.retokenize() as retokenizer:
    for span in new_entities:
        retokenizer.merge(span)
```

**Comment by honnibal** [comment]
Ah, sorry --- you're hitting #3288 , which I just pushed a fix for.

Would you mind setting `doc.tensor = None` before calling `retokenize()`, just to check whether the speed is still an issue?

**Comment by nyejon** [comment]
@honnibal Ok, this seems to be faster again. It seems to even be faster than a6 with the iteration through spans without the retokenizer.

Thanks for the quick assistance!

**Comment by ines** [comment]
That's nice to hear – the new retokenizer should definitely be more efficient, because it can merge in bulk. I'll add a noteto the v2.1 migration docs that mentions the possible slowness of the previous `merge` methods and how to rewrite existing code to use the retokenizer.
