### ISSUE TITLE
TypeError: an integer is required (using Spacy example code)

### ISSUE THREAD

**Issue by schlies** [explosion/spaCy#3305]
Hello Ines, I am going through your Datacamp course. The following code worked within the Datacamp site, but it didn't work when I directly copied and pasted it into my local environment. Why isn't it working? Thank you!

## How to reproduce the behaviour

```
# Import the Doc and Span classes
from spacy.tokens import Doc, Span

# Create a doc from the words and spaces
doc = Doc(nlp.vocab, words=['I', 'like', 'David', 'Bowie'],
spaces=[True, True, True, False])

# Create a span for "David Bowie" from the doc and assign it the label "PERSON"
span = Span(doc, 2, 4, label="PERSON")
print(span.text, span.label_)
```

> ERROR Message:
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-77-555d48244725> in <module>
>       6 
>       7 # Create a span for "David Bowie" from the doc and assign it the label "PERSON"
> ----> 8 span = Span(doc, 2, 4, label="PERSON")
>       9 print(span.text, span.label_)
> 
> span.pyx in spacy.tokens.span.Span.__cinit__()
> 
> TypeError: an integer is required

## Your Environment

* **spaCy version:** 2.0.16
* **Platform:** Darwin-18.0.0-x86_64-i386-64bit
* **Python version:** 3.6.8
* **Models:** en_core_web_sm

**Comment by ines** [comment]
Ah, sorry about that – the Datacamp course is currently in soft launch (so you were one of the first people to take it!) and already uses the very new version of spaCy, which will be released as a stable version very soon and includes a lot of improvements – including string labels for spans.

Solution 1 using the current version: Look up the span label in the `StringStore` first to get its integer ID.

```python
label = nlp.vocab.strings["PERSON"]
span = Span(doc, 2, 4, label=label)
```

Solution 2: Uninstall spaCy and install the latest alpha version using `pip install spacy-nightly`.

**Comment by schlies** [comment]
Thanks Ines. I like David Bowie too ;)

Dictated via iPhone
