### ISSUE TITLE
Python crashes when training in command line with no specific error message

### ISSUE THREAD

**Issue by mrxiaohe** [explosion/spaCy#3306]
My system information:
- Operating system: Windows Server 2016
- Python version: 3.6.5 (barebone Python)
- spaCy version: 2.0.12

I first converted CONLL 2003 dataset to json formats by doing the following:

```
(base) E:\Projects\NER\CONLL 2003>python -m spacy convert train.txt "E:\Projects\NER\CONLL 2003" -c ner
    Generated output file E:\Projects\NER\CONLL 2003\train.txt.json
    Created 1 documents

(base) E:\Projects\NER\CONLL 2003>python -m spacy convert test.txt "E:\Projects\NER\CONLL 2003" -c ner
    Generated output file E:\Projects\NER\CONLL 2003\test.txt.json
    Created 1 documents

(base) E:\Projects\NER\CONLL 2003>python -m spacy convert valid.txt "E:\Projects\NER\CONLL 2003" -c ner
    Generated output file E:\Projects\NER\CONLL 2003\valid.txt.json
    Created 1 documents
```

I then ran the following:
`(base) E:\Projects\NER\CONLL 2003>python -m spacy train en "E:\Projects\NER\CONLL 2003" train.txt.json valid.txt.json
`

which produced the following output:
```
dropout_from = 0.2 by default
dropout_to = 0.2 by default
dropout_decay = 0.0 by default
batch_from = 1 by default
batch_to = 16 by default
batch_compound = 1.001 by default
max_doc_len = 5000 by default
beam_width = 1 by default
beam_density = 0.0 by default
beam_width = 1 by default
beam_density = 0.0 by default
Warning: Unnamed vectors -- this won't allow multiple vectors models to be loaded. (Shape: (0, 0))
learn_rate = 0.001 by default
optimizer_B1 = 0.9 by default
optimizer_B2 = 0.999 by default
optimizer_eps = 1e-08 by default
L2_penalty = 1e-06 by default
grad_norm_clip = 1.0 by default
embed_size = 7000 by default
token_vector_width = 128 by default
parser_hidden_depth = 1 by default
parser_maxout_pieces = 2 by default
token_vector_width = 128 by default
hidden_width = 200 by default
embed_size = 7000 by default
history_feats = 0 by default
history_width = 0 by default
parser_hidden_depth = 1 by default
parser_maxout_pieces = 2 by default
token_vector_width = 128 by default
hidden_width = 200 by default
embed_size = 7000 by default
history_feats = 0 by default
history_width = 0 by default
Itn.  Dep Loss  NER Loss  UAS     NER P.  NER R.  NER F.  Tag %   Token %  CPU WPS  GPU WPS
```

When the last line of the above output was shown, I got a pop-up window saying Python stopped working (see screenshot below). No other error messages were shown. I wonder what might have happened. 

![image](https://user-images.githubusercontent.com/3064882/53135769-5c511c80-3531-11e9-924b-b43b08e69ca6.png)

Just to give you a bit more information:

The format of data files (prior to being converted to json files) is as follows:

```
-DOCSTART- -X- -X- O

CRICKET NNP B-NP O
- : O O
LEICESTERSHIRE NNP B-NP B-ORG
TAKE NNP I-NP O
OVER IN B-PP O
AT NNP B-NP O
TOP NNP I-NP O
AFTER NNP I-NP O
INNINGS NNP I-NP O
VICTORY NN I-NP O
. . O O

LONDON NNP B-NP B-LOC
1996-08-30 CD I-NP O

West NNP B-NP B-MISC
Indian NNP I-NP I-MISC
all-rounder NN I-NP O
Phil NNP I-NP B-PER
Simmons NNP I-NP I-PER
took VBD B-VP O
four CD B-NP O
for IN B-PP O
38 CD B-NP O
on IN B-PP O
Friday NNP B-NP O
as IN B-PP O
Leicestershire NNP B-NP B-ORG
beat VBD B-VP O
Somerset NNP B-NP B-ORG
by IN B-PP O
an DT B-NP O
innings NN I-NP O
and CC O O
39 CD B-NP O
runs NNS I-NP O
in IN B-PP O
two CD B-NP O
days NNS I-NP O
to TO B-VP O
take VB I-VP O
over IN B-PP O
at IN B-PP O
the DT B-NP O
head NN I-NP O
of IN B-PP O
the DT B-NP O
county NN I-NP O
championship NN I-NP O
. . O O

```

**Comment by ines** [comment]
Could you try again using the latest version, `v2.0.18`? We've fixed various issues around the training, some of which could have caused segmentation faults (C-level errors like the "Python stopped working" that you're seeing).

**Comment by mrxiaohe** [comment]
Does the update require updating various other packages/dependencies? I ask this because the server I am using has no internet connection. I have to download packages/wheels to a machine with internet and move them to the server. If the only thing that needs to be updated is spacy, then I can simply update spacy alone without updating other dependencies

**Comment by ines** [comment]
Ah okay, I understand. Here's the diff of the `requirements.txt` between the two versions:

https://github.com/explosion/spaCy/compare/v2.0.12...v2.0.18#diff-b4ef698db8ca845e5845c4618278f29a

You can ignore pytest (development only), and pretty sure also numpy and murmurhash (which only relax the version pins). So the remaining packages are `cymem`, `preshed` and `regex`.

**Comment by mrxiaohe** [comment]
I updated spaCy to the latest version and still got the same error

**Comment by honnibal** [comment]
I understand that it's hard to install all of the dependencies to try it. If you can get an environment where the Python will be in the same place as your server, you could try building a pex file. On Unix-like systems this is as simple as:

```git clone https://github.com/explosion/spaCy -b develop
cd spaCy
make
```

This builds an executable called `spacy.pex` that has the library and all of the Python dependencies within it. You can then run this file on your server, so long as it can find Python in the same place on your server as the machine you built the pex file.

I'm sorry that your set up makes it difficult to experiment with versions, but I do really think the version on `spacy-nightly` will solve your problem. It does require new versions of other libraries, though.
