### ISSUE TITLE
SpaCy tokenizer stopped working?

### ISSUE THREAD

**Issue by rafaleo** [explosion/spaCy#3309]
## Your Environment

* Operating System: 
* Python Version Used: 
* spaCy Version Used: 
* Environment Information: 
## Info about spaCy

* **spaCy version:** 2.0.13
* **Platform:** Windows-7-6.1.7601-SP1
* **Python version:** 3.6.5
* **Models:** en, en_core_web_md, spacy_lg

I'm simply reproducing example from tutorial [https://spacy.io/usage/linguistic-features#native-tokenizers] but it not working.

```
''' Defining customSpaCy tokenizer '''
def custom_tokenizer(nlp):
    prefix_re = re.compile(r'''^["']''')
    suffix_re = re.compile(r'''["']$''')
    infix_re = re.compile(r'''[-~]''')
    simple_url_re = re.compile(r'''^https?://''')

    return Tokenizer(nlp.vocab, prefix_search=prefix_re.search, suffix_search=suffix_re.search,
                                infix_finditer=infix_re.finditer, token_match=simple_url_re.match)

nlp = spacy.load('en_core_web_md')
print(nlp.meta['name'])
nlp.tokenizer = custom_tokenizer(nlp)

doc = 'Demolition of modern lean-to shed adjoining existing coach house.'
t_sent = nlp(doc)
print([t.text for t in t_sent])
```
Model is loaded but sentence is not parsed as expected. 
Result of print line: `['Demolition', 'of', 'modern', 'lean', '-', 'to', 'shed', 'adjoining', 'existing', 'coach', 'house.']`
Expected line: `['Demolition', 'of', 'modern', 'lean-to', 'shed', 'adjoining', 'existing', 'coach', 'house.']` where 'lean-to' is recognized as a single word.

**Comment by ines** [comment]
Are you using the latest version and is everything else up to date? I can't reproduce your example. Even if you enter your text [here in the interactive widget](https://spacy.io/usage/linguistic-features#native-tokenizers), it's tokenized as expected.

**Comment by rafaleo** [comment]
At my end it's not right on this interactive widget as well. Here's link: https://drive.google.com/open?id=1cji2njwrFWDE_iKuINnH7Xi3qcAVE_tf
I only changed model and sentence. Even when adding more hyphens `[\-\-\–\—\~]` into regex parser.

**Comment by ines** [comment]
Oh, I think I misread your question then. I thought the split tokens were the output you expected, because that's what the rules describe. The punctuation rules describe the characters to split on: before the token (prefix), after the token (suffix) and inside the token (infix). So a `-` in the infix rules tells the tokenizer to split on `-`. If you remove that hyphen from the infixes, the string `"lean-to"` won't be split on `-`.

**Comment by rafaleo** [comment]
Aha! So I misunderstood the regex usage though. It's exactly in-reverse of what I've expected. So basically, if I want to use standard infix parser but add only one rule of leaving hyphen-joint words, how should I write my regex?

I'm not sure what's the defaults and, for example, if I use `[\.,]` it looks as expected, but is it enough? Not sure. Anyways, you've helped me a lot. Thanks. My bad.

**Comment by ines** [comment]
No worries! And yes, exactly – you always tell the tokenizer what to split on. [This section](https://spacy.io/usage/linguistic-features#tokenization) has a graphic that shows how it steps through the raw text and applies the rules.

You can find the default tokenization rules here: https://github.com/explosion/spaCy/blob/master/spacy/lang/punctuation.py They should also be available as `nlp.Defaults.infixes` and so on.

**Comment by rafaleo** [comment]
Great but I still struggle to find out how to make tiny changes to the default parser. Following your links I've make such function:
```
from spacy.tokenizer import Tokenizer
from spacy.util import compile_prefix_regex, compile_infix_regex, compile_suffix_regex

def custom_tokenizer(nlp):
    prefix_re = compile_prefix_regex(nlp.Defaults.prefixes)
    suffix_re = compile_suffix_regex(nlp.Defaults.suffixes)
    # changing default infixed
    def_infx = nlp.Defaults.infixes    
    cur_infx = (d.replace('-|–|—|', '') for d in def_infx)
    infix_re = compile_infix_regex(cur_infx)
    
    return Tokenizer(nlp.vocab, prefix_search=prefix_re.search, suffix_search=suffix_re.search,
                                infix_finditer=infix_re.finditer, token_match=None)
```
Which should remove hyphens from infix parser. But it fails. Am I close to solution?

**Comment by rafaleo** [comment]
Actually, it works. My mistake. Thanks!
