### ISSUE TITLE
Chinese transliteration

### ISSUE THREAD

**Issue by shanalikhan** [explosion/spaCy#3310]
## Feature description
I want to know if Native Lanugage to english transliteration can be a part of spacy ?
For example, I am looking to add chinese version of transliteration in english characters ?
Would it be acceptable by spacy ? 

cc :  @honnibal and @ines

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
If so, we will tag it as [`project idea`](https://github.com/explosion/spaCy/labels/project%20idea) so other users can take it on.

**Comment by honnibal** [comment]
Hi @shanalikhan ,

I think it'd be cool to have something like this. The big question is whether the transliteration scheme is lossless and unambiguous, or whether the transliteration will depend on a statistical model.

If the transliteration is statistical (e.g. if it requires word segments), then it'll be best to use extension attributes to store the transliterated text. If characters always have the same transliteration regardless of context, then perhaps we could repurpose the `LOWER` attribute for this? After all, it's not like Chinese characters have case sensitivity...So the `LOWER` attribute is currently being wasted. It's a bit of a hack, but it'd be pretty useful.

**Comment by shanalikhan** [comment]
I am just asking to start research on this.
Chinese is an one language i was looking into, but might end up on other languages as well.

To be pretty sure, i dont want to research and send PR at the end and that would be **rejected** - losing all my contribution in spacy ? In short spacy allows languages english transliteration mode ?

What language code should i set for those languages ? are there any rules, or it will be on same language folder.
I was thinking as to mark en-{lang-code} as for translitated ones. 
https://www.w3schools.com/tags/ref_language_codes.asp
