### ISSUE TITLE
Length of text in named Entity recognition

### ISSUE THREAD

**Issue by yatin-rxlogix** [explosion/spaCy#3312]
Can anybody tell me what' the maximum length of text/document  supported by Named Entity Recognition without loss of Accuracy.

**Comment by honnibal** [comment]
The length of text shouldn't really impact accuracy. The model uses greedy search, so it's only maintaining one analysis at a time, and most of the features are local. You might find memory usage problems if you use very long documents at runtime though, like many thousand of words.
