### ISSUE TITLE
Installation of spacy-nightly over conda environment.yml

### ISSUE THREAD

**Issue by nadworny** [explosion/spaCy#3313]
## How to reproduce the problem
I would like to install spacy-nightly using conda with the following *environment.yml*
```
name: nlp
channels:
  - conda-forge
dependencies:
  - python=3.7
  - spacy-nightly=2.1.0a7
```
By executing
```
conda env create -f environment.yml
```

Error:
```
Solving environment: failed

ResolvePackageNotFound:
  - spacy-nightly
```

## Your Environment
* Operating System: MacOS
* Python Version Used: 3.7
* spaCy Version Used: 2.1.0a7
* Environment Information:

**Comment by ines** [comment]
`spacy-nightly` is currently only available on pip, sorry about that! (Building for conda always means a lot of additional overhead, so we haven't been adding the nightlies to conda yet.)
