### ISSUE TITLE
Allow setting of custom attributes during retokenization

### ISSUE THREAD

**Issue by phoerious** [explosion/spaCy#3314]
## Feature description

Perhaps I am just missing something, but I don't seem to be able to set custom attributes on a merged token during retokenization (using the new 2.1.x Retokenizer class).

    with doc.retokenize() as retokenizer:
        retokenizer.merge(span, attrs={ ... })

I can set any of the attributes listed in the Token documentation, but I am unable to do that for custom attributes. If there is a special syntax for setting custom attributes already, it should be documented.

**Comment by ines** [comment]
Yes, custom attributes aren't supported in the `attrs`, but it's an interesting idea.

The only potential problem I see here is that it can lead to confusing and inconsistent results: Not all custom attributes are writable – if the attribute isn't registered with a default value or doesn't have a setter, setting them on retokenization won't work. But then again, this _is_ pretty logical and I'm not sure people would really be so confused by that.

We could support it via the `_` property, like this:

```python
attrs = {"POS": "PROPN", "_": {"foo": "bar"}}
```
