### ISSUE TITLE
TextClassifier example gives very different results between versions 2.0.18 and 2.1

### ISSUE THREAD

**Issue by dtcto** [explosion/spaCy#3315]
## How to reproduce the behaviour
Install spacy 2.0.18, download the english language models, and run the example text classifier program https://github.com/explosion/spaCy/blob/master/examples/training/train_textcat.py with -m en_core_web_md -o output_md2_0 .  The only change made to the example program was to print the spacy version.

You get reasonable results:

python3 train_textcat.py -m en_core_web_md -o output_md2_0
spacy 2.0.18  <- I added this output to the program to display which version is being used
Loaded model 'en_core_web_md'
Loading IMDB data...
Using 2000 examples (1600 training, 400 evaluation)
Training the model...
LOSS 	  P  	  R  	  F  
86.797	0.850	0.754	0.799
33.462	0.851	0.846	0.848
13.090	0.851	0.846	0.848
6.030	0.843	0.856	0.850
3.122	0.839	0.882	0.860
2.093	0.832	0.887	0.859
1.040	0.831	0.882	0.856
0.980	0.831	0.856	0.843
0.599	0.833	0.846	0.840
0.779	0.833	0.872	0.852
0.371	0.836	0.862	0.848
0.289	0.824	0.862	0.842
0.227	0.823	0.856	0.839
0.223	0.817	0.846	0.831
0.190	0.831	0.856	0.843
0.407	0.839	0.856	0.848
0.169	0.842	0.846	0.844
0.392	0.838	0.851	0.845
0.187	0.838	0.851	0.845
0.447	0.843	0.856	0.850
This movie sucked {'POSITIVE': 0.2305149883031845}
Saved model to output_md2_0
Loading from output_md2_0
This movie sucked {'POSITIVE': 0.13291716575622559}

It does seem a bit odd that the classification is better after reloading the model from disk, but either result is reasonable.

Now setup a 2.1.0a9.dev0 (I also saw this with 2.1.0a7) environment and run the same command line again

python3 train_textcat.py -m en_core_web_md -o output_md2_1
spacy 2.1.0a9.dev0 <- I added this output to the program to display which version is being used
Loaded model 'en_core_web_md'
Loading IMDB data...
Using 2000 examples (1600 training, 400 evaluation)
Training the model...
LOSS 	  P  	  R  	  F  
176.750	0.537	1.000	0.699
176.750	0.537	1.000	0.699
176.750	0.537	1.000	0.699
176.750	0.537	1.000	0.699
176.750	0.537	1.000	0.699
176.750	0.537	1.000	0.699
176.750	0.537	1.000	0.699
176.750	0.537	1.000	0.699
176.750	0.537	1.000	0.699
176.750	0.537	1.000	0.699
176.750	0.537	1.000	0.699
176.750	0.537	1.000	0.699
176.750	0.537	1.000	0.699
176.750	0.537	1.000	0.699
176.750	0.537	1.000	0.699
176.750	0.537	1.000	0.699
176.750	0.537	1.000	0.699
176.750	0.537	1.000	0.699
176.750	0.537	1.000	0.699
176.750	0.537	1.000	0.699
This movie sucked {'POSITIVE': 1.0}
Saved model to output_md2_1
Loading from output_md2_1
This movie sucked {'POSITIVE': 1.0}

As you can see the model doesn't train well and the results of predictions are totally incorrect.  I saw the same results when using the small model and no model. 

## Your Environment

* Operating System: Linux-4.9.125-linuxkit-x86_64-with-Ubuntu-18.04-bionic
* Python Version Used: 3.6.7
* spaCy Version Used: 2.0.18 and 2.1.0a9.dev0 (results also seen with 2.1.0a7)
* Environment Information:

**Comment by honnibal** [comment]
Are you running the same script between the two versions? Because the script has been updated on the `develop` branch, to match the changes in the `TextCategorizer` model:

```
(env3.6) matt@LAPTOP-OMKOB3VM:~/repos/explosion/spacy-develop$ python examples/training/train_textcat.py
Created blank 'en' model
Loading IMDB data...

Using 2000 examples (1600 training, 400 evaluation)
Training the model...
LOSS      P       R       F
168.279 0.717   0.710   0.714
106.124 0.770   0.758   0.764
73.735  0.793   0.742   0.767
```

I'm just checking the accuracy with vectors provided (`en_core_web_md`) but I think the script difference is the problem.

**Comment by honnibal** [comment]
I think the text classifier changes might be too breaking to do by default in a minor release. I should probably change the default back to the previous architecture, and then we just document a setting. So, you do raise a valid concern here...

**Comment by honnibal** [comment]
Okay, I've set the default architecture back to how it was, and added a setting to switch to the  `"simple_cnn"` architecture, along with a separate setting to switch to mutually exclusive labels. See #3320 for discussion of a more satisfying solution to controlling the model architecture for pipeline components.

**Comment by dtcto** [comment]
I was running the same script between the two versions.  I can run the version from the develop branch later and report back if you like.
