### ISSUE TITLE
Tests for multithreading

### ISSUE THREAD

**Issue by honnibal** [explosion/spaCy#332]
After problems with the multithreading on Windows went apparently undetected, I think it's clear we should have tests that exercise the multithreading capabilities, if possible. I'm not sure how to write these, however. The tests should check that multiple cores get engaged, and I don't know how to check that from within Python off the top of my head.

We'd like to open development more to the community, now that the major design of the library is in place. If you have experience implementing this sort of test, we'd appreciate suggestions.

**Comment by aliabbasjp** [comment]
Should test with SPARK also. 
This  is currently not working in SPARK worker threads

https://github.com/spacy-io/spaCy/issues/413
