### ISSUE TITLE
Tokenization issues with em dash

### ISSUE THREAD

**Issue by mr-bjerre** [explosion/spaCy#3323]
Hi, I am not sure if the following is expected behavior.

     "November 2013–July 2014"

gets tokenized to `[November, 2013–July, 2014]`. I'd expect `[November, 2013, –, July, 2014]`? How do I fix this without the need to train my own model (I suppose that is required if I change the tokenizer, right?)?

Also is it on purpose that various `en` hyphens, dashes etc. aren't normalized to the same thing?

## Info about spaCy

* **spaCy version:** 2.1.0a8
* **Platform:** Linux-4.15.0-45-generic-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.6.7
* **Models:** en

**Comment by honnibal** [comment]
If you only make small changes to the tokenizer, I wouldn't say it needs to be retrained. The easiest way to change it is to load the model and then overwrite the `tokenizer.infix_finditer` function, which should be a function that works like a compiled regex's `.finditer` method. Here's an example of overwriting this:

```python

import spacy
import spacy.util

nlp = spacy.load('en_core_web_sm')
infixes = nlp.Defaults.infixes + (r'(?<=\d)[-–](?=[A-Z])',)
nlp.tokenizer.infix_finditer = spacy.util.compile_infix_regex(infixes).finditer
print(list(nlp.tokenizer("November 2013–July 2014")))
# [November, 2013, –, July, 2014]
```

**Comment by mr-bjerre** [comment]
Very neat and easy, thank you! Such a fan of `spaCy` and `prodigy`. 

Now is the opposite as easy? Making sure that certain phrases are considered a token?
