### ISSUE TITLE
Spacy email regex 

### ISSUE THREAD

**Issue by mihaivinaga** [explosion/spaCy#3326]
I am trying to use a regex to filter valid emails using spacy. I have created a custom entity called EMAIL and I am trying to filter just those that are valid emails. This is the code that I have come up with, but it returns every string

	matcher = Matcher(self.spacy_model.vocab)
	pattern = [{'EMAIL': {'REGEX': '^[^@]+@[^@]+\.[^@]+$'}}]
	matcher.add('email', None, pattern)
	
	doc = self.spacy_model(page_text)
	matches = matcher(doc)
	
	for match_id, start, end in matches:
    	string_id = self.spacy_model.vocab.strings[match_id]  # get string representation
    	span = doc[start:end]  # the matched span
    	print(match_id, string_id, start, end, span.text)

I am not sure I am on the right path.

**Comment by svlandeg** [comment]
For recognizing email addresses, you could simply use:
`{'LIKE_EMAIL': True}`

If you do want to use custom regular expressions, you can do something like this:

> email_flag = lambda text: bool(re.compile(r'^[^@]+@[^@]+\.[^@]+$').match(text))
> IS_MY_EMAIL = nlp.vocab.add_flag(email_flag)
> matcher.add('MY_EMAIL', None, [{IS_MY_EMAIL: True}])

More information in the docs: https://spacy.io/usage/linguistic-features#section-rule-based-matching

**Comment by ines** [comment]
Which version of spaCy are you using? The `'REGEX'` operator isn't yet available in the stable release (and has only been a proposal until recently). So if you want to test it, make sure you have `spacy-nightly` installed. 

> pattern = [{'EMAIL': {'REGEX': '^[^@]+@[^@]+\.[^@]+$'}}]

Patterns are keyed by **token attributes** – for example, `LOWER` will match on `token.lower_`. In this pattern, you're using `EMAIL`, which is invalid (there's no `token.email` attribute etc.). So you probably want to match on `LOWER` (lowercase form) or `ORTH` (verbatim text). If you're using the latest nightly, try setting `validate=True` when you initialize the `Matcher`:

```python
matcher = Matcher(self.spacy_model.vocab, validate=True)
```

This will check your pattern syntax and will complain if the pattern's invalid.

Finally, you might find that the `token.like_email` attribute is all you need? If it doesn't catch all your email addresses, we'd definitely be interested in examples it fails on so we can update spaCy's internal regex.
