### ISSUE TITLE
Matcher breaks with "complex" patterns

### ISSUE THREAD

**Issue by nyejon** [explosion/spaCy#3328]
Hi,

The matcher breaks with certain patterns. I think it has something to do with the "IN" when there are multiple patterns in a single matcher.

## How to reproduce the behaviour

```
import spacy
from spacy.tokens import Token, Doc, Span
from spacy.matcher import Matcher, PhraseMatcher

text = "Hello, how are you doing?"

nlp = spacy.load('en_core_web_md')

matcher = Matcher(nlp.vocab)
patterns = [
    [{'LOWER': {'IN': ["hello", "how"]}}],
    [{'LOWER': {'IN': ["you", "doing"]}}],
]

matcher.add('TEST', None, *patterns)

doc = nlp(text)

matches = matcher(doc)
for match_id, start, end in matches:
    span = Span(doc, start, end, label=match_id)
    print(span.text)
```
        
Output:

```
Hello  # OK
you . # OK
doing  #OK
?  #Not ok and missing "how"
```

## Your Environment
* **spaCy version:** 2.1.0a9.dev0
* **Platform:** Darwin-18.2.0-x86_64-i386-64bit
* **Python version:** 3.7.2
* **Models:** en_core_web_md, de_core_news_md

**Comment by honnibal** [comment]
Thanks! Introduced a regression in the last round of changes =/. I thought my test cases were more robust than this, but evidently not. Added another to check for this.
