### ISSUE TITLE
Training NER with existing model throws exception

### ISSUE THREAD

**Issue by andyp05** [explosion/spaCy#3330]
## How to reproduce the behaviour
Running example at: https://github.com/explosion/spacy/blob/master/examples/training/train_new_entity_type.py

If I add a model in the main() function call:
```
def main(model='en_core_web_lg', new_model_name='animal', output_dir='test', n_iter=10):
```
I get the following exception in the update function call:
```
nlp.update(texts, annotations, sgd=optimizer, drop=0.35, losses=losses)

C:\Python37\lib\site-packages\spacy\language.py:451: RuntimeWarning: invalid value encountered in greater_equal
  sgd(W, dW, key=key)
```
And on the following call I get another exception:
```
nlp2 = spacy.load(output_dir)

ValueError: could not broadcast input array from shape (77,64) into shape (73,64)
```

If I leave model=None, the error goes away, 
```
def main(model=None, new_model_name='animal', output_dir='test', n_iter=10):
```

I tried the latest nightly and the error remains. Using 2.1.0a7 models. Tried with/without GPU and get same results.

## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.7.2
* spaCy Version Used: 2.10 alpha 9

**Comment by honnibal** [comment]
Just pushed v2.1.0a9. Maybe you were using the `dev1` version? I've been working on this the last couple of days, and the script definitely works for me. Also, make sure you're using the version of the script from the develop branch.
