### ISSUE TITLE
How do I change hyperparameters for train ner?

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#3336]
Using the example script located here

https://github.com/explosion/spaCy/blob/master/examples/training/train_ner.py

How do you set the hyperparameters described in the API

https://spacy.io/api/cli

**Comment by honnibal** [comment]
The command line arguments for the `spacy train` CLI command don't all have an equivalent in the `train_ner.py` example script. We tried to balance completeness and simplicity in that example, so not all options are covered.

The environment variables can be set from your command line. If you're using a notebook, you can set them in the `os.environ` dictionary.

**Comment by erotavlas** [comment]
Are you saying that once I set the hyperparameters in the os.environ, that when spacy training runs it will read those parameters from there?  I don't really follow the example in the API document how to do that?
`parser_hidden_depth=2 parser_maxout_pieces=1 spacy train [...]`
What is parser_hidden_depth and parser_maxout_pieces?  I don't see those anywhere in the document. What comes after spacy train?

I was looking to try something simple at first like grid search over a few parameter variations.  Is this possible?  What about bayesian optimization methods?

If you would provide a simple example how to set the hyperparameters  it would be really appreciated. 
Thanks
