### ISSUE TITLE
Tokens printed out automatically when tokenizing tamil text for the first time

### ISSUE THREAD

**Issue by BLKSerene** [explosion/spaCy#3342]
Hi, I'm trying out the tamil alpha tokenization support, when tokenizing tamil text for the first time (when nlp is called for the first time), the tokens will be automatically printed out.

```
>>> import spacy

>>> nlp = spacy.blank('ta')
>>> nlp('தமிழ் மொழி (Tamil language) தமிழர்களினதும், தமிழ் பேசும் பலரதும் தாய்மொழி ஆகும்.')
தமிழ்
மொழி
(
Tamil
)
language

தமிழர்களினதும்
பேசும்
பலரதும்
தாய்மொழி
ஆகும்
தமிழ் மொழி (Tamil language) தமிழர்களினதும், தமிழ் பேசும் பலரதும் தாய்மொழி ஆகும்.
>>> nlp('தமிழ் மொழி (Tamil language) தமிழர்களினதும், தமிழ் பேசும் பலரதும் தாய்மொழி ஆகும்.') # Second call is ok
தமிழ் மொழி (Tamil language) தமிழர்களினதும், தமிழ் பேசும் பலரதும் தாய்மொழி ஆகும்.
```

* Operating System: Windows 10 64-bit
* Python Version Used: 3.7.2 64-bit
* spaCy Version Used: 2.1.0a9

**Comment by ines** [comment]
Thanks for the report! This was really confusing at first, but I think I found the culprit:

https://github.com/explosion/spaCy/blob/9b62639d198089c7d0708453005060c58359aac2/spacy/lang/ta/lex_attrs.py#L77

Looks like we forgot to remove a stray print statement in the lexical attribute getter function for `like_num`. Fixing! 👍
