### ISSUE TITLE
Bus Error 10 / Segmentation fault 11 with for loop with EntityRuler (spaCy-nightly)

### ISSUE THREAD

**Issue by kormilitzin** [explosion/spaCy#3345]
I'm using `EntityRuler` in my pipeline, so far so good. However, when I iterated over a collection of documents, after a while (5-10 docs) I get either 'Bus Error: 10' or 'Segmentation fault: 11' (Mac OS Mojave).

My pipeline:

I have a list of predefined 5 categories of named entities which I upload from a disk in a json format. In my pipeline, I'm adding EntityRuler before 'ner' and it works nicely. My data set is a collection of 300 documents and when I'm looping over them, I get either set fault or bus error. However (very odd!), when I'm trying to iterate over documents manually, all works fine, but when I'm using 'for' loop, I'm getting these errors.

** If I replace `EntityRuler` from the pipeline, I do not get any errors. 

> $ python test_1.py
>   5%|██████▌                                                                                                                                      | 14/303 [01:02<18:07,  3.76s/it]
Segmentation fault: 11
> 

> $ python test_1.py
>  10%|██████████████▌                                                                                                                              | 29/281 [01:54<14:50,  3.53s/it]
> Bus error: 10
> 
> 

Here is my example:

```

test_1.py:


import numpy as np
import pandas as pd
import spacy
import os, glob, re
import itertools
import pickle
from tqdm import tqdm
from spacy.pipeline import EntityRuler


nlp = spacy.load('en')
ruler = EntityRuler(nlp).from_disk('drug_patterns.jsonl')
nlp.add_pipe(ruler, before='ner')


def text_to_iob_scheme(text_i, nlp):
    doc_i = nlp(text_i)
    
    # get a list of named entities from the file
    labels = nlp_i.pipeline[2][1].labels
    
    df_tmp = pd.DataFrame([(e.text, e.ent_iob_, e.ent_type_) for e in doc_i])
    df_tmp['bio_tags'] = 'O'
    df_tmp.loc[df_tmp[1] != 'O', 'bio_tags'] = df_tmp.loc[df_tmp[1] != 'O', 1] + '-' + df_tmp.loc[df_tmp[1] != 'O', 2]
    
    # remove all IOB tags apart from those mentioned in EntityRuler 
    df_tmp.loc[~df_tmp.bio_tags.str.contains('|'.join(list(labels))), 'bio_tags'] = 'O'
    
    return df_tmp[[0, 'bio_tags']]


def main():
    
    df_texts = pd.read_csv('df_texts.csv')

    tmp_var = []

    for idx in tqdm(df_texts.doc_id.unique()):
         tmp_var.append(text_to_iob_scheme(df_texts_low.loc[df_texts.doc_id == idx, 'text'].iloc[0], nlp))
 
    output_var = pd.concat(tmp_var)
    output_var.to_csv('annotated_texts.tsv', header=False, index=False, sep='\t')
        
    
if __name__ == "__main__":

    main()


```

## Your Environment
* Operating System: Mac OSX Mojave
* Python Version Used: Anaconda 3.6.7
* spaCy Version Used: spaCy-nightly 2.1.0a16
* Environment Information:

**Comment by ines** [comment]
Thanks for the report! This sounds similar to #3338. 

I suspect the underlying problem might be a bug in the entity recognizer and how it deals with existing entities that were set previously in the pipeline. It should just accept them, move on and "predict around them", but in some specific cases, it seems to get confused.

If you're able to somehow narrow it down to a small set of patterns and examples and you can share those, that would be super helpful. Maybe you can print the texts before you process them and see if you can find one it always fails on?

(C-level errors like this sometimes lead to peculiar behaviour that's difficult to make sense of. At some point, a bit of arbitrary memory might have been modified, but it only leads to an issue if it's accessed later on. And this may happen in *some* scenarios – like when you loop over all texts – and not in others.)

**Comment by kormilitzin** [comment]
Hi @ines, I can't agree more, that C-level errors are tricky to catch. I'm reading similar threads here and will experiment with your suggestions. I will keep you posted.

**Comment by ines** [comment]
Okay, I think I was able to reproduce this (or at least *a* segmentation fault in combination with the entity ruler). At the moment, the entity recognizer tries to prevent adding entities across sentence boundaries – but the entity ruler doesn't care. 

So if the parser predicts a sentence boundary between one of the entities matched by the entity ruler, adding the entity works fine. But when the entity recognizer comes across this state of the `Doc` afterwards, it gets confused.

```python
import spacy
from spacy.pipeline import EntityRuler

nlp = spacy.blak("en_core_web_sm")
patterns = [{"label": "GPE", "pattern": "New York"}]
ruler = EntityRuler(nlp, patterns=patterns)

def sent_start_hack(doc):
    # Hard-code sentence boundaries because they need to
    # be set in the pipeline before the parser
    doc[4].is_sent_start = True
    return doc

nlp.add_pipe(sent_start_hack, before="parser")
nlp.add_pipe(ruler, before="ner")
doc = nlp("I live in New York")
```
