### ISSUE TITLE
xx NER tags "n’t" token in contractions as an entity

### ISSUE THREAD

**Issue by bittlingmayer** [explosion/spaCy#3347]
## How to reproduce the behaviour

Try some sentences with English contractions like `can’t` or `don’t` that are actually two tokens.  Note the apostrophe `’` (not `'`).

They can be in the beginning or the middle, and the input can be sentence case or title case.

```
>>> import spacy
>>> xx = spacy.load('xx')
>>> en = spacy.load('en')
>>> xx("It doesn’t end.").ents
(n’t,)
>>> xx("It can’t end.").ents
(n’t,)
>>> xx("It can't end.").ents
()
>>> en("It isn’t end.").ents
()
```
If you use the en model, it works as expected (no entity), also if you use `'` not `’` then it works.

## Your Environment

* **spaCy version:** 2.0.18
* **Platform:** Darwin-18.2.0-x86_64-i386-64bit
* **Python version:** 3.7.1
* **Models:** pt, en, xx

**Comment by honnibal** [comment]
Merging with #3052 (inaccurate prediction master thread)
