### ISSUE TITLE
Document similarity does not work on gpu with models including word vectors

### ISSUE THREAD

**Issue by danielkingai2** [explosion/spaCy#3348]
## How to reproduce the behaviour
It seems that the document similarity function does not work on GPU for spacy models that have word vectors.

```
Python 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 09:07:38) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> spacy.prefer_gpu()
True
>>> nlp = spacy.load('en_core_web_md')
>>> doc1 = nlp("this is some text.")
>>> doc2 = nlp("this is some more text.")
>>> doc1.similarity(doc2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "doc.pyx", line 322, in spacy.tokens.doc.Doc.similarity
  File "doc.pyx", line 386, in spacy.tokens.doc.Doc.vector_norm.__get__
  File "doc.pyx", line 361, in spacy.tokens.doc.Doc.vector.__get__
  File "cupy/core/core.pyx", line 1741, in cupy.core.core.ndarray.__array_ufunc__
  File "cupy/core/_kernel.pyx", line 789, in cupy.core._kernel.ufunc.__call__
  File "cupy/core/_kernel.pyx", line 86, in cupy.core._kernel._preprocess_args
TypeError: Unsupported type <class 'numpy.ndarray'>
```

## Info about spaCy

* **spaCy version:** 2.0.18
* **Platform:** Linux-4.4.0-112-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.7
* **Models:** en_core_web_md, en_core_web_sm

**Comment by honnibal** [comment]
Thanks! Disappointed I made this error, but I'm pretty sure I see what's wrong. If you have a look here:

https://github.com/explosion/spaCy/blob/develop/spacy/tokens/doc.pyx#L332

You should see that there's a direct call to `numpy.dot()`. We instead want to do something like:

```python
vector = self.vector
xp = thinc.neural.util.get_array_module(vector)
xp.dot(...)
```

This should select cupy or numpy, depending on the data. I don't have a GPU server booted just now, so if it's easy for you to do so, would you mind submitting a PR? You should also check the `token.similarity()` and `span.similarity()` methods, and ideally have a quick look for other direct invocations of numpy if the data could be on GPU.
