### ISSUE TITLE
Lemmatization not working properly for few verbs in a sentence

### ISSUE THREAD

**Issue by samarthsarin** [explosion/spaCy#3349]
## How to reproduce the behaviour

doc = nlp(u'My is reading and writing listening a new startup')
for token in doc:
    print(token.lemma_)
Output:
-PRON-
be
read
and
writing
listen
a
new
startup

Here you can see that reading and listening were lemmatized and writing was not
################################################################
Also I would like to know how do I keep I as I only and not changing it to -PRON-

## Your Environment

* Operating System: Windows 8.1
* Python Version Used: 3.5.6
* spaCy Version Used: 2.0.18
* Environment Information:

**Comment by BrianSladek** [comment]
"Writing" can be a noun or verb depending on context. I'm guessing Spacy thinks "writing" in this context is a noun and thus "writing" is the lemmatized form. You can check what part of speech Spacy assigns to the word to confirm this. The sentence itself is not really grammatically valid, so we can't say whether it should be considered a noun or verb.

> Also I would like to know how do I keep I as I only and not changing it to -PRON-
Add an if-statement that checks if the lemma is -PRON-, and if it is, use the token's text property instead.

**Comment by samarthsarin** [comment]
Ok thanks got it.
And can you please help me with the -PRON- in the lemma of few words.
Why is that happening?
Is there any way to keep the lemma of those words as it is rather than converting it into -PRON-.
Words like My, I, they.....?

**Comment by BrianSladek** [comment]
The -PRON- tag is used as the lemma for pronouns because there is debate over how pronouns should be lemmatized. Should the lemma of "my" be "I" or "my"? Should the lemma of "we" be "I" or "we"? If you want the lemma of the pronouns to be just the pronoun itself, you can easily do something like this:
```
for token in doc:
    if token.lemma_ == "-PRON-":
        print(token.text)
    else:
        print(token.lemma_)
```

**Comment by samarthsarin** [comment]
Thanks alot
