### ISSUE TITLE
Segmentation fault 11 with two NER pipes in 2.0.18

### ISSUE THREAD

**Issue by Apollo-XI** [explosion/spaCy#3353]
## How to reproduce the behaviour

Copy, paste and run the following code:

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import spacy
from spacy.pipeline import EntityRecognizer

nlp = spacy.load('es')
_, ner = nlp.remove_pipe('ner')
ner_ser = ner.to_bytes()

ner = EntityRecognizer(nlp.vocab)
ner.from_bytes(ner_ser)
ner.add_label('label1')
ner.add_label('label2')

nlp.add_pipe(ner, name='ner_1')
ner = EntityRecognizer(nlp.vocab)
ner.from_bytes(ner_ser)
ner.add_label('label3')
ner.add_label('label4')

nlp.add_pipe(ner, name='ner_0', last=True)

text = """Apoyo en la gestión de la plataforma de formación online (eCampus MAPFRE).
Colaboración en el diseño de programas online.
Redactar informes y elaborar presentaciones de impacto.
Colaborar en las tareas administrativas propias del departamento.
Participación en las reuniones y videoconferencias del Área, con los equipos de RRHH de todos los países, en inglés y español.
"""

# Segmentation fault: 11
doc = nlp(text)
```

It produces "Bus error: 10" or the following message using `python -q -X faulthandler spacy-bug.py`:
```
Fatal Python error: Segmentation fault

Current thread 0x00007fffb23e4380 (most recent call first):
  File "/Users/vferrer/miniconda3/envs/spacy/lib/python3.7/site-packages/spacy/language.py", line 346 in __call__
  File "spacy-bug.py", line 32 in <module>
Segmentation fault: 11
```
Sometimes, it doesn't produce a segmentation fault. If you remove some sentences, it doesn't break.

## Your Environment

* Operating System: macOs High Sierra (10.13.4)
* Python Version Used: Python 3.7.1 (installed with anaconda)
* spaCy Version Used: 2.0.18
* Environment Information:

This sound similar to #3338 and #3345 although happens in spacy stable and not in alpha.

**Comment by dado0583** [comment]
I am also seeing this issue in spacy stable. I've uploaded example code that produces the error here: https://github.com/dado0583/JupyterNotebooks/blob/master/SpacyExamples/Bus10SegmentFault.py. 

The difference with mine is that I am using a custom pipeline that is manually adding ents to the doc, instead of using a second EntityRecognizer.

### Environment:
MacOS 10.9
Python: 3.6
Spacy: 2.0.18

**Comment by honnibal** [comment]
Could you check that the error still occurs on `spacy-nightly`? I think we might have fixed this.

**Comment by honnibal** [comment]
Merging with #3345
