### ISSUE TITLE
Pretraining docs

### ISSUE THREAD

**Issue by RonRademaker** [explosion/spaCy#3354]
## Which page or section is this issue related to?
https://spacy.netlify.com/api/cli#pretrain

The first argument of the new pretrain command puzzles me: `Path to JSONL file with raw texts to learn from.`. Are there any docs (examples) on how this json should look? Is there some way to build this file from plain text?

**Comment by ines** [comment]
Thanks for the heads-up! I totally thought we had an example for this, but turns out we didn't. Already wrote up the section and will push it in a second!
