### ISSUE TITLE
Slow Doc creation with whitespace tokenization

### ISSUE THREAD

**Issue by mhham** [explosion/spaCy#3359]
## How to reproduce the behaviour
I would like to use spacy Docs for fast string processing (mainly counting words using `count_by` which is approximately 4 times faster than `collections.Counter` with a list of strings)

However, I noticed that `Doc` creation + whitespace tokenization is way slower than simply using `split()` on the string, which cancels the counting advantage.

Here is the code for simple string splitting:
```python
>>> %timeit text_list = str('test a b c '*10000).split()
1.23 ms ± 35.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
Then for spacy:
```python
from spacy.attrs import ORTH
from spacy.tokens import Doc
from spacy.vocab import Vocab
from spacy.language import Language

class WhitespaceTokenizer:
    def __init__(self, vocab):
        self.vocab = vocab

    def __call__(self, text):
        return Doc(self.vocab, words=text.split())

nlp = Language(Vocab())
nlp.tokenizer = WhitespaceTokenizer(nlp.vocab)

>>> %timeit doc = nlp('test a b c '*10000)
11.2 ms ± 60.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

Then for strings counting:
```python
>>> %timeit collections.Counter(text_list)
2.14 ms ± 110 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

>>> %timeit doc.count_by(ORTH)
560 µs ± 20.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

All in all, it is faster to just split the text and use `collections.Counter`.

Do you have any idea whether this is normal behaviour ?

Edit: I have investigated things into more detail. It turns out the main time consuming task is `Doc` creation, not tokenization:

```python
vocab = Vocab()
text_list = str('test a b c '*10000).split()

>>> %timeit Doc(vocab, words=text_list)
9.81 ms ± 61.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

## Your Environment

* **spaCy version:** 2.0.18
* **Platform:** Darwin-18.2.0-x86_64-i386-64bit
* **Python version:** 3.7.2

**Comment by honnibal** [comment]
`str.split()` is one of the things in Python that's pleasantly fast, so I'm not surprised we're not faster than it. One thing you should look at is using the vocab from a model, like `en_vectors_web_lg` or `en_core_web_lg`. The lexemes are cached in the vocab, and we do a fair bit of work when a new lexeme is seen. This might actually be most of the runtime for you.

If you just want fast counting, you might want to look at the bounter library, which implements approximate counting. This is a bit faster but hugely more memory efficient. You can also look at the implementation of `doc.count_by()`. It's pretty simple: all I'm doing is using my `preshed.counter.PreshCounter` class, which has the limitation that it only accepts 64bit keys. If you use the `StringStore` class to map your strings into hashes, you'll be able to count them with this class. The `StringStore` also uses a somewhat more memory efficient storage for the strings than Python. The difference used to be pretty big, but I think Python 3.6 and 3.7 made some improvements, so I'm not sure it's so significant now.

Finally, I would caution against running micro-benchmarks with timeit. You really need to run a bigger sample. Python has many optimisations for small strings, repeated string usage etc, and cache locality matters a huge amount.
