### ISSUE TITLE
Question about tokenization

### ISSUE THREAD

**Issue by chkoar** [explosion/spaCy#3361]
I have a text in XML like format  like `<TEST>test</TEST>`. 
I would like the tokenizer to produce `[<TEST>, test, </TEST>]` insted of `[<, TEST, >, test</TEST, >]`.
Is this possible?

**Comment by ines** [comment]
Yes, see here for details on how to customise the regular expressions used by the tokenizer: https://spacy.io/usage/linguistic-features#native-tokenizers

You probably want to write stricter rules that always split on `<`, `/` and `>` and then use the [`Matcher`](https://spacy.io/usage/linguistic-features#section-rule-based-matching) to merge the markup into single tokens. The patterns for this could look like this:

```python
[{"ORTH": "<"}, {"IS_UPPER": True}, {"ORTH": ">"}]
[{"ORTH": "<"}, {"ORTH": "/"}, {"IS_UPPER": True}, {"ORTH": ">"}]
```

Here's an example that shows a custom pipeline component that takes care of merging HTML markup automatically when you call `nlp` on a text: https://spacy.io/usage/linguistic-features#matcher-pipeline
