### ISSUE TITLE
Windows + Conda permission problem: PermissionError(13, 'Access is denied')

### ISSUE THREAD

**Issue by electrotipe** [explosion/spaCy#3363]
I have reviewed previous issues on stackoverflow:
https://stackoverflow.com/search?q=spacy+python+windows+PermissionError

Nor did I find answer here:
https://github.com/conda-forge/spacy-feedstock

## How to reproduce the problem

I am using Anaconda Navigator, and in turn conda to manage packages in Python.
I can't successfully install Spacy.
Workflow: open Anaconda Navigator GUI> base(root) - Open Terminal> conda install -c conda-forge spacy

Print out of what I see on command line after :

Downloading and Extracting Packages
ujson-1.35           | 25 KB     | ############################################################################ | 100%
conda-4.6.7          | 890 KB    | ############################################################################ | 100%
pyreadline-2.1       | 140 KB    | ############################################################################ | 100%
dill-0.2.9           | 135 KB    | ############################################################################ | 100%
plac-0.9.6           | 18 KB     | ############################################################################ | 100%
cymem-2.0.2          | 35 KB     | ############################################################################ | 100%
spacy-2.0.18         | 50.5 MB   | ############################################################################ | 100%
murmurhash-1.0.0     | 17 KB     | ############################################################################ | 100%
preshed-2.0.1        | 70 KB     | ############################################################################ | 100%
regex-2018.01.10     | 319 KB    | ############################################################################ | 100%
msgpack-numpy-0.4.3. | 8 KB      | ############################################################################ | 100%
thinc-6.12.1         | 1.3 MB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(507): An error occurred while uninstalling package 'defaults::conda-4.5.12-py37_0'.
PermissionError(13, 'Access is denied')
Attempting to roll back.

Rolling back transaction: done

PermissionError(13, 'Access is denied')

```bash
PermissionError(13, 'Access is denied')
```

## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.7.1
* spaCy Version Used: none, trying to install
* Environment Information: Conda

**Comment by honnibal** [comment]
Can you install other packages?

**Comment by electrotipe** [comment]
I get the same error when installing other packages from the command line (example below), but I can install packages while in Jupyter Notebook:

Downloading and Extracting Packages
openssl-1.1.1a       | 5.7 MB    | ############################################################################ | 100%
conda-4.6.7          | 1.7 MB    | ############################################################################ | 100%
ca-certificates-2018 | 155 KB    | ############################################################################ | 100%
pandas-0.23.4        | 8.6 MB    | ############################################################################ | 100%
certifi-2018.11.29   | 146 KB    | ############################################################################ | 100%
qt-5.9.7             | 92.3 MB   | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(507): An error occurred while uninstalling package 'defaults::pandas-0.23.4-py37h830ac7b_0'.
PermissionError(13, 'Access is denied')
Attempting to roll back.

Rolling back transaction: done

PermissionError(13, 'Access is denied')

**Comment by electrotipe** [comment]
However (confusingly to me), I can import other packages from Jupyter Notebook:

The below line runs without errors:

import pandas as pd

**Comment by ines** [comment]
Okay, this sounds like an issue with your environment maybe? (At least, if it affects other packages, we know that it's not a problem with spaCy directly.) If you can install from within the notebook, you might actually be executing a different Python environment there? The environment in your notebook may already have pandas pre-installed, which is why that import works and others don't. Or maybe the permissions are correct for the notebook and not on the command line?

I googled the error and found the following threads:
* https://github.com/conda/conda/issues/3448
* https://github.com/conda/conda/issues/4534
* https://stackoverflow.com/q/49092807/6400719

Some solutions described there included: running the Anaconda prompt as administrator and reinstalling Anaconda, changing from "for all users" to "for myself". I'll close this issue since it's not specific to spaCy, but I hope you'll be able to fix your conda installation 🙂
