### ISSUE TITLE
Is it possible to access the line number of a span?

### ISSUE THREAD

**Issue by mihaivinaga** [explosion/spaCy#3365]
I feed to spacy a whole document of text and for me it's important to know if the n'th span is on the same line as with the n'th+1 span. 

Is this something that can be done?

**Comment by ines** [comment]
How do you define a line? If you have this information available (e.g. character offsets of the lines in the original document) or you know that lines are separated by `\n` tokens, you could calculate the line a span belongs to and make it available as a [custom attribute](https://spacy.io/usage/processing-pipelines#custom-components-attributes) like `Span._.line_no`.

You could also create span objects for all lines in the document and make them available as `Doc._.lines`. To check whether an arbitrary span is part of a line, you can then check whether it overlaps with a given line span by comparing the `span.start` and `span.end` indices.
