### ISSUE TITLE
Tokenization error involving hyphen

### ISSUE THREAD

**Issue by bongbang** [explosion/spaCy#3376]
In a poorly formatted text with in which a grammatical dash has a space one side but not the other, spaCy lumps the dash and the word to which it is joined together as one token. 

Is there an easy way for me to fix this short of directly editing the source code? Preprocessing is an obvious solution, but I wonder if there's a way to deal with this within spaCy. It doesn't seem like a tokenizer exception would work since it matches only "whitespace-delimited chunks".

## How to reproduce the behaviour

```
def show_tokens(text):
    doc = nlp(text)
    for token in doc:
        print(token, token.tag_, token.pos_, token.dep_)

show_tokens('John -who loved Mary- was heartbroken.')
print()
show_tokens('John --who loved Mary-- was heartbroken.')
```
Output:

```
John NNP PROPN nsubj
-who HYPH PUNCT punct
loved VBD VERB csubjpass
Mary- NNP PROPN dobj
was VBD VERB auxpass
heartbroken JJ ADJ ROOT
. . PUNCT punct

John NNP PROPN npadvmod
--who : PUNCT nsubj
loved VBD VERB csubjpass
Mary-- NNP PROPN dobj
was VBD VERB auxpass
heartbroken JJ ADJ ROOT
. . PUNCT punct
```

## Your Environment
* Python Version Used: 3.6
* spaCy Version Used: 2.0.18

**Comment by ines** [comment]
Yes, you can customise the tokenization rules – [see here](https://spacy.io/usage/linguistic-features#native-tokenizers) for details. In your case, you probably want to add `--` to the tokenizer prefixes, i.e. the character split off at the beginning of a token.

For the new alpha docs, I also added a section on adding single rules to existing rule sets. This might actually be pretty much exactly what you need: https://spacy.netlify.com/usage/linguistic-features#native-tokenizer-additions

**Comment by bongbang** [comment]
Thank you.  What's the reason for triple quotes in the examples? Aren't single quotes enough?

**Comment by bongbang** [comment]
I added `'-+'` to both the prefixes and suffixes and it seems to work wonders. Many thanks for the solution.

```
John NNP PROPN nsubjpass
- : PUNCT punct
who WP NOUN nsubj
loved VBD VERB relcl
Mary NNP PROPN dobj
- : PUNCT punct
was VBD VERB auxpass
heartbroken JJ ADJ ROOT
. . PUNCT punct

John NNP PROPN nsubjpass
-- : PUNCT punct
who WP NOUN nsubj
loved VBD VERB relcl
Mary NNP PROPN dobj
-- : PUNCT punct
was VBD VERB auxpass
heartbroken JJ ADJ ROOT
. . PUNCT punct
```
