### ISSUE TITLE
`msgpack-numpy` monkey-patches msgpack upon `import spacy`. 

### ISSUE THREAD

**Issue by gwk** [explosion/spaCy#3384]
`import spacy` causes `msgpack-numpy` to replace `msgpack.Unpacker` with its own monkey-patched version. This breaks my code due to the missing `raw` keyword parameter in `msgpack_numpy.Unpacker.__init__`.

```
>>> import msgpack
>>> msgpack.Unpacker
<class 'msgpack._cmsgpack.Unpacker'>
>>> import spacy
>>> msgpack.Unpacker
<class 'msgpack_numpy.Unpacker'>
```

For a potential new user of Spacy like myself, this is pretty terrible. Monkey-patching is an easy way to alienate users with confusing bugs, and relying on dependencies that do so is arguably worse because the culprit becomes even more obscure.

Would it be possible for Spacy to drop this dependency and use the `ext_hook` features of msgpack instead? I would be happy to try to help out with this if there is interest from the developers.

Thanks!

**Comment by honnibal** [comment]
Agreed, and already fixed in `spacy-nightly` :). See https://github.com/explosion/srsly

**Comment by gwk** [comment]
Great, thank you. I switched to `develop` branch and have gotten past that error.
