### ISSUE TITLE
Fine-tuning dependency parsing

### ISSUE THREAD

**Issue by tehnar** [explosion/spaCy#339]
Hello. Actually, your library is very great, but sometimes it can fail on some specific texts. Is it possible to hand-label some sentences and then fine-tune spaCy to work properly on them? 
Is it necessary to have a large dataset, or there is some way to give my sentences some kind of high "priority"?

**Comment by honnibal** [comment]
It's possible to do this, yes. You can increase the 'priority' of the sentence by simply training on it repeatedly. The catch is that while you do this, you might be changing the model a lot, in unfortunate ways. Let's say you have a sentence like "I want a pizza with anchovies". You want the model to learn to attach "with anchovies" to "pizza". If you repeatedly train on this sentence, sure enough you'll get the analysis you want. But there's no reason to believe it'll learn the sort of *policy* you would find sensible. It might instead learn to always attach PPs to NPs! This would mean that "I want a pizza in an hour" will be understood with the wrong structure.

So, this is actually quite difficult to get just right. We care a lot about this, though. We're busily building out services around spaCy that will help you create annotations and quickly, and then use them to fine-tune the model. There are a few things you could try in the meantime, but it'll likely take some experimentation to get just right.

If you want to set annotations completely manually, you can use the `doc.from_array()` method, to set the  `HEAD` and `DEP` properties yourself.

**Comment by tehnar** [comment]
Thanks for your fast reply!

I understand possible bad outcomes of such a fine-tuning, also it's ok for me to set annotations completely manually. Could you point out API that I should use to fine-tune on hand-annotated sentence? Also, it would be great if you provide some snippet of code, but it's not necessary.

**Comment by tehnar** [comment]
@honnibal 
So, could you provide me some example or point out the API I should use?
