### ISSUE TITLE
NER  on multi GPU machines

### ISSUE THREAD

**Issue by mbanon** [explosion/spaCy#3394]
Hi all,
I'm using spaCy for NER tagging.
Since I have a multi-GPU machine, I wonder if there's a way to force "prefer_gpu()" and/or "require_gpu()" to use a given GPU, so I can distribute the work load through all GPUs  (for example, by passing a parameter with the GPU number).
Thanks!

**Comment by honnibal** [comment]
I haven't tested things on a multi-GPU machine before, so there might be some rough edges. But in theory if you select the device with cupy it should work. I think you might need to do the device selection before importing spaCy. You can read the docs on selecting the device here: https://docs-cupy.chainer.org/en/stable/tutorial/basic.html

It's worth noting though that processing text is only 3-4 times faster on GPU than on CPU. This means CPU is generally much better value, if you have the choice. Of course if you have multiple GPUs sitting around I guess you may as well use them...But you probably have jobs to train as well, and if so, you'll probably find it better to parse text on a bunch of cheap CPU VMs, and save your GPU server for when you need it.

**Comment by mbanon** [comment]
@honnibal  Ok, i see. I'l try selecting with cupy and see what happens. Thanks! :)

**Comment by honnibal** [comment]
The implementation details on this, in case you need to do some digging:

* The machine learning stuff is generally here: https://github.com/explosion/thinc/
* Thinc uses cupy for GPU execution, numpy, Blis and Cython kernels for CPU
* All models have an attribute `model.ops`. This is an instance of either `thinc.neural.ops.Numpy` or `thinc.neural.ops.Cupy`
* To set "GPU mode", we change two class members on the `thinc.neural._classes.Model`: `Model.ops` and `Model.Ops`. Changing these class members means that as new models are created, they end up with a `CupyOps` instance as `model.ops`.
