### ISSUE TITLE
Lemmatize named entities

### ISSUE THREAD

**Issue by rsuhada** [explosion/spaCy#3399]
Currently 
`nlp("Albert Einstein's name is Albert Einstein").ents`
      
yields two entities:
`(Albert Einstein's, Albert Einstein)`

instead of expected:
`(Albert Einstein, Albert Einstein)`

Is there maybe a simple workaround currently?

**Comment by mhham** [comment]
You can extract any entity's lemma via the attribute `lemma_`, but this does not solve your issue : 
```python
doc = nlp("Albert Einstein's name is Albert Einstein")
lemmas = [ent.lemma_ for ent in doc.ents]
```
will output: `["albert einstein 's", 'albert einstein']`

The problem lies with the NER model that detects the whole "Albert Einstein's"  as an entity

**Comment by ines** [comment]
Yes, what's going on in this case is that the first entity span includes the tokens `Albert` and `Einstein`, plus the particle `'s` (which is a separate token):

```python
['Albert', 'Einstein', "'s", 'name', 'is', 'Albert', 'Einstein']
```

So this is really a case of the entity recognizer predicting a span that's unideal. You could of course update it with more examples of person entities + particles to teach it to do this less – but you might find it easier to use a rule-based component instead.

For example, for each entity, you could check if it's a person entity and if the last token is `'s`. If so, you could create a new entity span that doesn't include the `'s`. Untested, but something like this should work:

```python
def remove_particles_from_entities(doc):
    new_ents = []
    for ent in doc.ents:
        # We only want to check person entities with more than one token
        if ent.label_ == "PERSON" and len(ent) > 1:
            if ent[-1].text == "'s":  # check if the last token is "'s":
                # Create a new span that's one token shorter (minus the particle)
                ent_without_particle = doc[ent.start:ent.end - 1])
                new_ents.append(ent_without_particle)
        else:
            new_ents.append(ent)  # Keep the entity span otherwise
    doc.ents = new_ents  # Overwrite the existing doc.ents with the filtered ones
    return doc

# Add the component to the pipeline and run it after the entity recognizer
nlp.add_pipe(remove_particles_from_entities, after="ner")
```

The idea is similar to the one described in this section I wrote for the new alpha docs: https://spacy.netlify.com/usage/rule-based-matching/#models-rules-ner
