### ISSUE TITLE
Don't results using PhraseMatcher 

### ISSUE THREAD

**Issue by dcordobar94** [explosion/spaCy#3400]
## How to reproduce the behaviour

Hi,
I'm trying to use PhraseMatcher but it does not always find results. For example:

    from spacy.matcher import PhraseMatcher 

    matcher = PhraseMatcher(nlp.vocab)
    doc = nlp("Fecha de ingreso: XXXXX. Fecha de alta: Médico responsable: Dr./Dra. ANTONIO RODRIGUEZ.")
    assert len(matcher) == 0
    matcher.add('CAT', None, nlp("Fecha de ingreso"))
    assert len(matcher) == 1
    matches = matcher(doc) # []

but:

    matcher = PhraseMatcher(nlp.vocab)
    doc = nlp("Fecha de ingreso: XXXXX. Fecha de alta: Médico responsable: Dr./Dra. ANTONIO RODRIGUEZ.")
    assert len(matcher) == 0
    matcher.add('CAT', None, nlp("de ingreso"))
    assert len(matcher) == 1
    matches = matcher(doc) # [(1610042320, 1, 3)]

but

    matcher = PhraseMatcher(nlp.vocab)
    doc = nlp(
        "Fecha de ingreso: XXXXX. Fecha de alta: Médico responsable: Dr./Dra. ANTONIO RODRIGUEZ.")
    assert len(matcher) == 0
    matcher.add('CAT', None, nlp("Dr./Dra. ANTONIO"))
    assert len(matcher) == 1
    matches = matcher(doc) # []

I don't know where is the problem

## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.7
* spaCy Version Used: 2.0.18

**Comment by ines** [comment]
Hmm, I just tried your examples in the latest version of `spacy-nightly` (upcoming v2.1) and it all works as expected there.

If you want, try out the new version and see if it solves the problem for you. (Make sure to use a new virtual environment, though, and don't forget to download the new models.)

**Comment by dcordobar94** [comment]
Yes, with spacy-nightly it works. Thanks!

**Comment by ines** [comment]
Cool, thanks for updating. Looks like whatever the problem was is already fixed then! 👍
