### ISSUE TITLE
cudaError on a VM with CUDA installed but no GPU

### ISSUE THREAD

**Issue by fcivardi** [explosion/spaCy#3403]
## How to reproduce the behaviour

import spacy
nlp = spacy.load('en_core_web_sm', disable=['parser', 'tagger'])
doc = nlp(u'Apple is looking at buying U.K. startup for $1 billion'
CUDARuntimeError                          Traceback (most recent call last)
<ipython-input-9-411ac162242e> in <module>()
      1 import spacy
      2 nlp = spacy.load('en_core_web_sm', disable=['parser', 'tagger'])
----> 3 doc = nlp(u'Apple is looking at buying U.K. startup for $1 billion')

C:\Anaconda\lib\site-packages\spacy\language.py in __call__(self, text, disable)
    344             if not hasattr(proc, '__call__'):
    345                 raise ValueError(Errors.E003.format(component=type(proc), name=name))
--> 346             doc = proc(doc)
    347             if doc is None:
    348                 raise ValueError(Errors.E005.format(name=name))

nn_parser.pyx in spacy.syntax.nn_parser.Parser.__call__()

nn_parser.pyx in spacy.syntax.nn_parser.Parser.parse_batch()

C:\Anaconda\lib\site-packages\spacy\util.py in get_cuda_stream(require)
    236 
    237 def get_cuda_stream(require=False):
--> 238     return CudaStream() if CudaStream is not None else None
    239 
    240 

C:\Anaconda\lib\site-packages\cupy\cuda\stream.py in __init__(self, null, non_blocking)
    108             self.ptr = runtime.streamCreateWithFlags(runtime.streamNonBlocking)
    109         else:
--> 110             self.ptr = runtime.streamCreate()
    111 
    112     def __del__(self):

cupy/cuda/runtime.pyx in cupy.cuda.runtime.streamCreate()

cupy/cuda/runtime.pyx in cupy.cuda.runtime.streamCreate()

cupy/cuda/runtime.pyx in cupy.cuda.runtime.check_status()

CUDARuntimeError: cudaErrorUnknown: unknown error

## Your Environment

* Operating System: Windows-10-10.0.14393-SP0
* Python Version Used: 3.6.7
* spaCy Version Used: 2.0.18
* Environment Information:

The error seems similar to that reported here #2343 

A similar VM with spacy 2.0.17 works instead fine.

**Comment by honnibal** [comment]
Could you try v2.1.1? I think the problem should be resolved.
