### ISSUE TITLE
Spacy Model Trained through CLI Freezes/Stops

### ISSUE THREAD

**Issue by jesro** [explosion/spaCy#3406]
When I try to train a model through command line it freezes after this stage.
File Size:
         training.json -> 9.7 MB
         test.json -> 2.2MB
Im not getting any error in command prompt.

Any ideas on how to resolve this? Many thanks!

> python -m spacy train en Desktop/Spacy/Model-Train Downloads/training.json Downloads/test.json -n 5 -P -T
> dropout_from = 0.2 by default
> dropout_to = 0.2 by default
> dropout_decay = 0.0 by default
> batch_from = 1 by default
> batch_to = 16 by default
> batch_compound = 1.001 by default
> max_doc_len = 5000 by default
> beam_width = 1 by default
> beam_density = 0.0 by default
> Warning: Unnamed vectors -- this won't allow multiple vectors models to be loaded. (Shape: (0, 0))
> learn_rate = 0.001 by default
> optimizer_B1 = 0.9 by default
> optimizer_B2 = 0.999 by default
> optimizer_eps = 1e-08 by default
> L2_penalty = 1e-06 by default
> grad_norm_clip = 1.0 by default
> parser_hidden_depth = 1 by default
> parser_maxout_pieces = 2 by default
> token_vector_width = 128 by default
> hidden_width = 200 by default
> embed_size = 7000 by default
> history_feats = 0 by default
> history_width = 0 by default
> Itn.  Dep Loss  NER Loss  UAS     NER P.  NER R.  NER F.  Tag %   Token %  CPU WPS  GPU WPS
>
>
>
>
>
>

**Comment by honnibal** [comment]
Can you try updating your version? I think this will probably be fixed in v2.1

I suspect there might be examples in your data that the it can't find a correct analysis for, which might be sending it into an infinite loop. Obviously that's a bug --- but I think it should be fixed.
