### ISSUE TITLE
Sentence Simplification in spaCy

### ISSUE THREAD

**Issue by enarke** [explosion/spaCy#3407]
I am looking for a way to decompose the compound sentence to simple sentences in spaCy.
For ex: Input: Verify that ads are displayed on Right Rail on Browsers and Long Tablets
Output: Verify that the ads are displayed on Right Rail on Browsers.
Verify that the ads are displayed on Right Rail on Long Tablets

## Your Environment
* Operating System: windows server 2012 R2
* Python Version Used: 3.7
* spaCy Version Used: 2.0.18

**Comment by svlandeg** [comment]
Hi @enarke, I don't think there is an out-of-the-box solution for this, but you could try using a model with dependency parsing, as visualised [here](https://explosion.ai/demos/displacy?text=Verify%20that%20ads%20are%20displayed%20on%20Right%20Rail%20on%20Browsers%20and%20Long%20Tablets&model=en_core_web_lg&cpu=1&cph=1). You can [navigate the tree](https://spacy.io/usage/linguistic-features#navigating) in code and look for `cc` relations and then break up the sentence accordingly.

For further help with coding implementation etc, [Stackoverflow ](https://stackoverflow.com/questions/tagged/spacy) is probably a better/quicker way to get help.
