### ISSUE TITLE
Does multithreading still work on Python 3.6 (or above)?

### ISSUE THREAD

**Issue by mrxiaohe** [explosion/spaCy#3410]
I'm trying to do NER on a set of 13 mil sentences. My CPU usage of the Python session in which spaCy is running is only 2 - 2.5%. The code I use is below. In addition, according #2075 spaCy should give a warning about n_threads being deprecated, but when I have it specified, I don't get any warning message whatsoever. Thanks!

```
def read_from_folder(filepaths):
    for filepath in filepaths:
        with io.open(filepath, "r+", encoding = "utf-8") as f:
            docid = filepath.replace(".txt", "")
            sentence = f.read().strip()
            if sentence:
                 yield (sentence, docid)

text_generator = read_from_folder(filepaths)
entities = []
nlp = spacy.load('en_core_web_lg', disable = ['parser', 'tagger', 'textcat'])
for doc, docidin nlp.pipe(text_generator, n_threads = 20, batch_size = 50000, as_tuples = True):
    entities.append([docidin, doc])

```
## Your Environment

* Operating System: Windows Server 2016
* Python Version Used: 3.6.7
* spaCy Version Used: 2.1.0a13
* Environment Information:

**Comment by ines** [comment]
The argument was marked as deprecated in the docs, but spaCy didn't actually raise deprecation warnings. I just fixed this!

**Comment by mrxiaohe** [comment]
And multithreading no longer works in spacy-nightly?

**Comment by mhham** [comment]
Apparently the 2.x models cannot release the global interpreter lock ([source](https://github.com/explosion/spaCy/commit/bec8db91e6b8aa8c64a24ac6562c9a8aaf639a13)):

    W016 = ("The keyword argument `n_threads` on the is now deprecated, as "
        "the v2.x models cannot release the global interpreter lock. "
        "Future versions may introduce a `n_process` argument for "
        "parallel inference via multiprocessing.")

**Comment by mrxiaohe** [comment]
I ended up using multiprocessing.

**Comment by randomgambit** [comment]
@mrxiaohe @ines hello there! sorry but I am a bit lost here. What is now, with `spacy 2.1`, the best way to parallelize the processing? I have about 2 million headlines in my Pandas dataframe... Is parallelizing automatic with the newest `nlp.pipe()` ?
