### ISSUE TITLE
Lemmatization of the adjective "more" at start of sentence in SpaCy 2.1

### ISSUE THREAD

**Issue by kut** [explosion/spaCy#3411]
The token "more" (tagged as an `ADJ`) is not lowercase in its lemmatization, if it occurs at the start of the sentence. Haven't been able to reproduce with other adjectives...

## How to reproduce the behaviour
```
doc = nlp("More information can be found on our website")
doc[0].lemma_    # "More" not "more"
```

## Your Environment

* Operating System: Windows, Linux
* Python Version Used: 3.6.1
* spaCy Version Used: 2.1.0a13
* Environment Information:

**Comment by ines** [comment]
Hi! Yes, I'm pretty sure this is expected behaviour. In 2.1.x, the lemmas aren't lowercased by default anymore. See [the release notes](https://github.com/explosion/spaCy/releases/tag/v2.1.0a13): 

> For better compatibility with the Universal Dependencies data, the lemmatizer now preserves capitalization, e.g. for proper nouns (see #3256).

**Comment by kut** [comment]
Thanks Ines! Trouble is, the words "more" and "most" are actually the only words I've found (by spot-checking) that exhibit this behaviour (for sentence start `ADJ`) - whereas others are lowercased, e.g.:

```
doc = nlp("Good information can be found on our website")    # doc[0].lemma_ == "good"
doc = nlp("Best information can be found on our website")    # doc[0].lemma_ == "good"
doc = nlp("Extensive information can be found on our website")    # doc[0].lemma_ == "extensive"
doc = nlp("Terrible information can be found on our website")    # doc[0].lemma_ == "terrible"
doc = nlp("Much information can be found on our website")    # doc[0].lemma_ == "much"
```
...versus...
```
doc = nlp("More information can be found on our website")    # doc[0].lemma_ == "More"
doc = nlp("Most information can be found on our website")    # doc[0].lemma_ == "Most"
```

Just trying to understand if that's expected behaviour (in which case I will always take `token.lemma_.lower()` whenever I'd like the lemma of an `ADJ`)?

Thanks for the help.

**Comment by ines** [comment]
Merging this with #2668!
