### ISSUE TITLE
Tokenizer in 2.1 not separating out punctuation (English)

### ISSUE THREAD

**Issue by sergeyf** [explosion/spaCy#3422]
## How to reproduce the behaviour
Here is code from 1.9 (which I upgraded from today):
```
import spacy
tokenizer = spacy.load('en', disable=['parser', 'ner', 'tagger'])

s = 'This is a sentence, and it has some commas. This is another sentence.'
[str(i) for i in tokenizer(s)]
```
This results in:
`['This', 'is', 'a', 'sentence', ',', 'and', 'it', 'has', 'some', 'commas', '.', 'This', 'is', 'another', 'sentence', '.']`

Here is the code from 2.1:
```
from spacy.vocab import Vocab
from spacy.language import Language
from spacy.tokenizer import Tokenizer

nlp = Language(Vocab())
tokenizer = Tokenizer(nlp.vocab)

s = 'This is a sentence, and it has some commas. This is another sentence.'
[str(i) for i in tokenizer(s)]
```

This results in: `['This', 'is', 'a', 'sentence,', 'and', 'it', 'has', 'some', 'commas.', 'This', 'is', 'another', 'sentence.']`

Note that the punctuation is not separately tokenized. I believe the behavior is 1.9 is correct and the behavior in 2.1 is not.

## Your Environment
* **spaCy version:** 1.9.0
* **Platform:** Windows-10-10.0.17134-SP0
* **Python version:** 3.6.8

and 

* **spaCy version:** 2.1.0
* **Platform:** Windows-10-10.0.17134-SP0
* **Python version:** 3.7.2

**Comment by sergeyf** [comment]
I tried using the more standard `import spacy; nlp = spacy.load("en_core_web_sm")` and the tokenization was just fine. 

What is wrong with the version that I ended up using? It was derived from 
https://spacy.io/api/language and https://spacy.io/api/tokenizer.

**Comment by ines** [comment]
@sergeyf I think the main problem here might be that the `Tokenizer` you're initializing from scratch doesn't have any rules – so the only thing that's hard-coded is that it'll split on whitespace. If you use the `English` language class, it'll use the default English rules, which includes splitting on punctuation, the English tokenizer exceptions etc.

**Comment by sergeyf** [comment]
Ah gotcha, thanks for the explanation. It's 90% my fault. I do think a brief comment in the aforementioned section could save a future person some quizzical behavior. Thanks for the really nice software!
