### ISSUE TITLE
Finding specific 'synonyms' to generic key words

### ISSUE THREAD

**Issue by HarshavardhanG513** [explosion/spaCy#3425]
Introduction:
Having learnt to use spacy, i got a project to work on from a startup. It has to do with getting suitable candidates for a given company's job offer.

Problem:
Recruiters may not have technical knowledge and can type in something generic. Example: They might type in database programming instead of specifying what database software they want someone to know. How do I match these generic statements with their more specific synonyms listed on resumes?

## Your Environment
latest versions of python and spacy as of 19th march 2018

**Comment by honnibal** [comment]
While we're happy to answer usage questions about spaCy here, I think this really goes beyond that to general NLP strategy. We do have to draw a line somewhere, and I think solving specific projects is out of scope.

You can have a look at the word vectors support, which might be helpful. I suspect some rules for the most common cases will also be useful.
