### ISSUE TITLE
💫 Raise error if user is running narrow unicode build

### ISSUE THREAD

**Issue by ines** [explosion/spaCy#3426]
## Feature description

Because v2.1 includes various changes to the regular expressions used in the tokenizer (including replacing `regex` with `re`), loading a model with a narrow unicode build of Python will fail with `sre_constants.error: bad character range`. See #3421 for details.

spaCy should probably check `sys.maxunicode` on import and raise an error if it's `65535`, meaning the user is running a narrow build. (Even aside form spaCy, a narrow unicode build is pretty inconvenient when working with text in Python.)

I've already added a section on this to the troubleshooting guide, so we can use text from that for the error message: https://spacy.io/usage#narrow-unicode

**Comment by sadovnychyi** [comment]
So on macOS I have used `brew install pyenv` followed by `CONFIGURE_OPTS="--enable-unicode=ucs4 MACOSX_DEPLOYMENT_TARGET=10.6" python-build 2.7.15 .python27`.

This seem to have invalidated all pre-built wheels, so everything has to be compiled from scratch (tons of time and various failures across different dependencies). Omitting `MACOSX_DEPLOYMENT_TARGET` would lead to a failure when installing thinc.

Is there any steps to make spacy's wheels work? I've spend way too much time trying to get everything working and now just considering staying on 2.1alpha while on macos. 

To be clear -- I did get spacy working, but the question is how to get it to install from wheels.
