### ISSUE TITLE
Spacy runs very slow when deployed to Google App Engine

### ISSUE THREAD

**Issue by jeffoneill** [explosion/spaCy#3429]
I'm using Spacy (2.0.18) with a Google App Engine app (GAE 2d Gen/Python 3.7), and I'm finding that Spacy runs very slow. 

On my Mac, processing 24 documents of 1800 words total takes 0.6 seconds.  When deployed, it takes 15 seconds so about 25 times slower.  I'm using the largest GAE instance (F4_1G | 1024 MB | 2.4 GHz) which is faster than my Mac.

GAE 2d gen uses pip to install Spacy and dependencies so mostly similar to how I do it on my Mac, though I wouldn't be surprised if there are differences behind the scenes at Google.

Any suggested fixes for speeding up Spacy when deployed to GAE?

**Comment by honnibal** [comment]
Can you try v2.1? The v2.0 version can end up calling into different matrix multiplication code, depending on the system state. I suspect you're ending up with a bad BLAS kernel on GAE, causing performance to be poor.

You can read more about the change of BLAS solution in v2.1 here: https://explosion.ai/blog/spacy-v2-1#matrix-multiplication

**Comment by jeffoneill** [comment]
I tried 2.1 and it is much better.  I tested en_core_web_sm with 2.0.18 and 2.1.0.

2.0.18: 20 seconds
2.1.0: 1.3 seconds

Nice work with the new release!
