### ISSUE TITLE
compatibility of serialized Docs across spacy/vocab versions

### ISSUE THREAD

**Issue by bdewilde** [explosion/spaCy#343]
Hi, I'm trying to determine whether docs serialized via `Doc.to_bytes()` using an older (or simply different) spacy version / Vocab object may be de-serialized via `Doc.from_bytes()` using a different version. Basically, are serialized spacy docs a viable "long-term" storage format? The documentation doesn't say, and I've dug myself deep into unfamiliar territory in spacy's code trying to find the answer. :)

If the same `Vocab` _is_ required, is there a recommended way for persisting the information needed to uniquely identify the object so that it can be loaded for correct de-serialization? I'm aware of using sputnik to get a package a la `sputnik.package(spacy.about.__title__, spacy.about.__version__, 'en')`, but unsure how to connect the dots to my use case.

Thanks a ton for your help!

**EDIT:** If this sort of question belongs in [spacy's subreddit](https://www.reddit.com/r/spacynlp), I'm happy to re-post there.

**Comment by honnibal** [comment]
I hadn't really given this enough thought. So, thanks for the question.

The data to deserialize can be saved along with the texts, by serializing the `Vocab` object. If we include some sort of version compatibility string, it should be suitable for long-term storage.
