### ISSUE TITLE
character tokenization in spacy 2.1

### ISSUE THREAD

**Issue by jfelectron** [explosion/spaCy#3438]
## How to reproduce the behaviour

Spacy 2.1
In [1]: import spacy

In [2]: spacy_nlp = spacy.load('en_core_web_sm')

In [3]: [d.text for d in spacy_nlp(u'I have a dog')]
Out[3]: [u'I', u'h', u'a', u'v', u'e', u'a', u'd', u'o', u'g']

Spacy 2.0
In [1]: import spacy

In [2]: spacy_nlp = spacy.load('en_core_web_sm')

In [3]: [d.text for d in spacy_nlp(u'I have a dog')]
Out[3]: [u'I', u'have', u'a', u'dog']

## Your Environment

* Operating System:   Ubuntu 18.10
* Python Version Used: Python
* spaCy Version Used:  2.0/2.1
* Environment Information: ?

**Comment by ines** [comment]
This is the same issue as #3356 and seems to be something related to Python 2 in some specific configuration. Unfortunately, we haven't been able to reproduce this yet on any of our test machines or CI 😞
