### ISSUE TITLE
'module' object has no attribute '_dl' 

### ISSUE THREAD

**Issue by aj47** [explosion/spaCy#3439]
## How to reproduce the problem
I recently installed reinstalled spacy after trying an older version for compatibility reasons. now when i try to run my python code i get the following error. I also get the same error when i try to run: python3 -m spacy download en
```bash
  File "server2.py", line 14, in <module>
    import spacy
  File "/Library/Python/2.7/site-packages/spacy/__init__.py", line 11, in <module>
    from .cli.info import info as cli_info
  File "/Library/Python/2.7/site-packages/spacy/cli/__init__.py", line 13, in <module>
    from .ud import ud_train, ud_evaluate  # noqa: F401
  File "/Library/Python/2.7/site-packages/spacy/cli/ud/__init__.py", line 2, in <module>
    from .ud_train import main as ud_train  # noqa: F401
  File "/Library/Python/2.7/site-packages/spacy/cli/ud/ud_train.py", line 36, in <module>
    import torch
  File "/Library/Python/2.7/site-packages/torch/__init__.py", line 72, in <module>
    import torch._dl as _dl_flags
AttributeError: 'module' object has no attribute '_dl'
```
Ive tried reinstalling torch too, unsure what to try now..
## Your Environment
* Operating System: macOS High Sierra 10.13.2
* Python Version Used: 2.7
* spaCy Version Used: 2.1
* Environment Information:

**Comment by ines** [comment]
This looks like an issue with PyTorch / `torch` installed in your environment. The `ud_train` command tries to import `torch` and defaults to `None` if it's not installed. But if it's installed but there's actually an issue with `torch`, that issue will come up. Maybe try uninstalling `torch` and/or use a virtual environment?

**Comment by aj47** [comment]
Yeah ive tried to reinstall torch with pip uninstall , pip install. I will try a virtual environment next. Thank you for the suggestion

**Comment by ines** [comment]
Ok, good! This is definitely a `torch` thing, though, and as soon as you don't have a broken version of `torch` installed in your environment anymore, everything should work as expected.
