### ISSUE TITLE
PIP installation not working

### ISSUE THREAD

**Issue by lorenzesz** [explosion/spaCy#3443]
## How to reproduce the problem
 python -m spacy download de

Successfully installed spacy-2.1.1 thinc-7.0.4
max@sz-host18:~$ python -m spacy download de
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/max/.local/lib/python3.6/site-packages/spacy/__init__.py", line 10, in <module>
    from thinc.neural.util import prefer_gpu, require_gpu
  File "/home/max/.local/lib/python3.6/site-packages/thinc/neural/__init__.py", line 4, in <module>
    from ._classes.model import Model  # noqa: F401
  File "/home/max/.local/lib/python3.6/site-packages/thinc/neural/_classes/model.py", line 10, in <module>
    from ..train import Trainer
  File "/home/max/.local/lib/python3.6/site-packages/thinc/neural/train.py", line 5, in <module>
    from tqdm import tqdm
ImportError: cannot import name 'tqdm'

* Operating System: Ubuntu 18.04
* Python Version Used: 3.6
* spaCy Version Used: 2.1.1
* Environment Information: I am trying to get it run also under 2.0.18 with thinc 6.12.1. Uninstalled a reinstalled several times and read all issues related. Nothing has fixed this. 

Compiling seem to work under 2.0.18 under venv. Maybe someone has a solution?

**Comment by honnibal** [comment]
Hm, it's not immediately obvious what could be going wrong here. When I make a clean install it works, and it's passed successfully through all our tests.

I suspect that installing and reinstalling might actually be the problem. pip can be rather dumb: when you upgrade a package in-place with pip, it doesn't necessarily clean out modules that no longer exist. This means you can end up with an inconsistent installation. This is one of several reasons why virtualenv is recommended --- you make sure you get a clean installation. Another potential problem is that the command `spacy` that you're executing might end up running an unexpected version, depending on how your `PATH` variable ends up looking.

Perhaps try:

```
python3 -m venv spacy-env
source spacy-env/bin/activate
python -m pip install spacy
```

**Comment by honnibal** [comment]
Just checked again and the installation definitely works into a clean environment. So, somehow your installation is in a state pip isn't cleanup up well.

**Comment by lorenzesz** [comment]
Pycharms remote interpreter don't support venv. Is it possible to clean the system environment?

**Comment by lorenzesz** [comment]
Uninstalling and reinstalling python didn't helped. I had to reinstall Ubuntu...
