### ISSUE TITLE
Question about spans_from_biluo_tags

### ISSUE THREAD

**Issue by chkoar** [explosion/spaCy#3445]
I have a question about [spans_from_biluo_tags](https://github.com/explosion/spaCy/blob/master/spacy/gold.pyx#L687) function. Internally uses the [tags_to_entities](https://github.com/explosion/spaCy/blob/master/spacy/gold.pyx#L27) which returns a list of (string, int, int). In this [line](https://github.com/explosion/spaCy/blob/master/spacy/gold.pyx#L700) the `label` parameter is a `string` but according to the [docs](https://spacy.io/api/span) a `Span` needs an `int` not a `string` in the label parameter. How is it supposed to work? Am I missing something? I haven't installed the latest version, but if use the following code it seems to work.

```python
def spans_from_biluo_tags(doc, tags):
    token_offsets = tags_to_entities(tags)
    spans = []
    for label, start_idx, end_idx in token_offsets:
        span = Span(doc, start_idx, end_idx + 1, label=doc.vocab.strings[label])
        spans.append(span)
        return spans
```

* **spaCy version:** 2.0.16
* **Platform:** Windows-8.1-6.3.9600-SP0
* **Python version:** 3.6.3
* **Models:** en

**Comment by ines** [comment]
Ah, I just realised that even though it's one of my favourite subtle improvements in v2.1., we forgot to add this to thge docs: As of v2.1, the `Span` can also take a string label! 🎉 This change was long overdue and makes a lot of the usage around adding and creating spans much easier.

If you're on v2.0.x, then yes, you need to modify the code just like you did in your version.

**Comment by chkoar** [comment]
@ines  ok, thanks.
