### ISSUE TITLE
End-to-end example usage of spacy pretrain

### ISSUE THREAD

**Issue by nahidalam** [explosion/spaCy#3448]
I was able to test out the `spacy pretrain` feature using
`python -m spacy pretrain ./data.jsonl en_vectors_web_lg ./pretrained-model`

At the end, the `pretrained-model` directory contains the models trained in each epoch. For example the last epoch produced `model999.bin`

Can you share an example of how to use it from there on? How do I load? How do I use it for different use cases like sentiment analysis and/or dialogue generation?

## Which page or section is this issue related to?
https://spacy.io/usage/v2-1

**Comment by honnibal** [comment]
If you're using the `spacy train` command, you can pass the trained weights with the `-t2v` argument. Here's an example command:

```python -m spacy train en tmp/ ~/data/PTB_SD_3_3_0/train.gold.json ~/data/PTB_SD_3_3_0/dev.gold.json --pipeline parser -t2v nv-cosine-reddit17-99.bin
```

More fundamentally, the weights files being produced by the `spacy pretrain` command are the result of calling something like `textcat.model.tok2vec.to_bytes()`. There's a couple of things to keep in mind about this. Let's say you first create a blank `TextCategorizer` object, like this:

```
textcat = nlp.create_pipe("textcat")
```

The new `textcat` object will start out with `textcat.model == True`. So, you won't immediately be able to call something like `textcat.model.tok2vec`. You need to create a model object first, which usually happens during the call to `nlp.begin_training()`. So, somewhere in your script after the call to `begin_training()`, but before you start making updates, you can add lines like this:

```
with open("/path/to/model999.bin", "rb") as file_:
    textcat.model.tok2vec.from_bytes(file_.read())
```

One more thing to be aware of. You need to make sure that the `textcat.model.tok2vec` instance you're loading the weights into has the same architecture and hyper-parameters as the model you used during pre-training. With the default textcat hyper-parameters, that's not quite true. The easiest solution is to pass the flag `architecture="simple_cnn"`. Putting everything together, usage should look something like this:

```python

nlp = spacy.blank("en")
textcat = nlp.create_pipe("textcat", config={"architecture": "simple_cnn", "exclusive_classes": True}))
textcat.add_label("LABEL1")
textcat.add_label("LABEL2")
# Alternatively, instead of adding all your labels explicitly, you could pass all your examples
# into textcat.begin_training, like this: textcat.begin_training(get_gold_tuples=lambda: my_data)
# It's fine to add the labels and not pass in the data, though. The nlp.begin_training() method will
# work the same as well, if you have other components in your pipeline you want to train.
optimizer = textcat.begin_training()
# Now that we have our model, we can load in the pretrained weights.
with open(path_to_pretrained_weights, "rb") as file_:
    textcat.model.tok2vec.from_bytes(file_.read())
# Now we can proceed with training
for epoch in range(nr_epoch):
    random.shuffle(train_data)
    for batch in minibatch(train_data, size=batch_size):
        X, y = zip(*batch)
        textcat.update(X, y, sgd=optimizer)
```

Sorry it's still not a fully working example. We're working on a proper tutorial.

**Comment by honnibal** [comment]
Added a `-t2v` argument to the `train_textcat` script. This should be an end-to-end example for text categorization: https://github.com/explosion/spaCy/commit/4e3ed2ea88d85834e5b9308faa27b3224d947bbd

For dialogue generation, I'm actually not sure the `spacy pretrain` command will perform well. One weakness of the "LMAO" trick we're using is that at each word, the model only gets to predict one vector. Normally, a language model will be predicting a probability distribution over the words in the vocabulary. We're only predicting a single point in vector-space. For the purpose of getting a token representation, I think the LMAO trade-off is pretty good. But if you really do want to generate words, it's probably not so good.

**Comment by alejandrojcastaneira** [comment]
Hello, I would like to know, how could I test it with ner, I imagine will need a change on the second line:

`with open("/path/to/model999.bin", "rb") as file_:
ner.model.tok2vec.from_bytes(file_.read())` 

If I train whit different widths in the cnns or different number of embedding rows, where I could set up these hiperparameters?

**Comment by tienduccao** [comment]
Hi @nahidalam , I wrote a blog post about using spacy pretrain for text classification on a new dataset here https://tienduccao.github.io/posts/spacy_pretrain/.
Hope that could help.

**Comment by nahidalam** [comment]
Thanks @tienduccao
