### ISSUE TITLE
Potential incorrect dependency tree

### ISSUE THREAD

**Issue by fersarr** [explosion/spaCy#3450]
I might be wrong (please correct me) but I believe this is a mistake in the dependency tree so it might be suited for the master thread (https://github.com/explosion/spaCy/issues/3052):

Given the sentence `"The assault resulted in robert fracturing his pelvis"`, I believe the subtree containing `"in robert"` should be rooted on `"fracturing"` not on `"resulted"` as shown below:

![Screen Shot 2019-03-20 at 10 00 18 PM](https://user-images.githubusercontent.com/3913371/54722240-f9689a80-4b5b-11e9-8cdd-9cb5fc2bbef7.png)

Links to interact: https://explosion.ai/demos/displacy?text=the%20assault%20resulted%20in%20robert%20fracturing%20his%20pelvis&model=en_core_web_lg&cpu=1&cph=1

To be more precise, I expected something like the tree given for
`"the assault resulted in robert needing stitches"`
https://explosion.ai/demos/displacy?text=the%20assault%20resulted%20in%20robert%20needing%20stitches&model=en_core_web_lg&cpu=1&cph=1

**Comment by honnibal** [comment]
The dependency annotation schemes often don't handle these types of constructions very well, so I'm not actually positive what the target annotation would be here. I know how I'd annotate the sentence in CCG, but the dependency syntax is often a little mysterious to me.

I do agree the sentence looks wrong though. I would hope for a nominal clause rooted by "fracturing", and attaching to `in`. I'd have `Robert` as a subject relationship to `fracturing` in this subordinate clause.

Closing this to merge with the master thread: https://github.com/explosion/spaCy/issues/3052
