### ISSUE TITLE
PIP install spacy fails on raspberry PI (debian 9, ARM)

### ISSUE THREAD

**Issue by pabou38** [explosion/spaCy#3451]
pip install spacy fails on raspberry PI 3 (ARM processor) running debian 9 (Stretch)

virtual environment used is as follows: 
 
atomicwrites==1.3.0
attrs==19.1.0
certifi==2019.3.9
chardet==3.0.4
cymem==2.0.2
Cython==0.29.6
flake8==3.5.0
idna==2.8
jsonschema==2.6.0
mccabe==0.6.1
mock==2.0.0
more-itertools==6.0.0
murmurhash==1.0.2
numpy==1.16.2
pathlib2==2.3.3
pbr==5.1.3
plac==0.9.6
pluggy==0.9.0
preshed==2.0.1
py==1.8.0
pycodestyle==2.3.1
pyflakes==1.6.0
pytest==4.0.2
pytest-timeout==1.3.3
requests==2.21.0
six==1.12.0
srsly==0.0.5
urllib3==1.24.1
wasabi==0.1.4

The issue is with the BLIS package (part of requirement.txt).  gcc reports an error related to some flag ‘-march=core-avx2’ (see below)

I checked with Ubuntu 16 running on the raspberry PI as well, and same problem.

I had installed spacy on Ubuntu 18, running on an Intel PC, and it worked like a charm.

do you support Linux ARM ?  

Thanks

 gcc -c /tmp/pip-install-l0gcf9n9/blis/blis/_src/kernels/zen/1/bli_amaxv_zen_int.c -o /tmp/tmpryu9665f/bli_amaxv_zen_int.o -O3 -mavx2 -mfma -mfpmath=sse -march=core-avx2 -fPIC -std=c99 -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.5.0-6" -DBLIS_IS_BUILDING_LIBRARY -Iinclude/linux-x86_64 -I./frame/3/ -I./frame/ind/ukernels/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -I/tmp/pip-install-l0gcf9n9/blis/blis/_src/include/linux-x86_64
      gcc: error: unrecognized argument in option ‘-march=core-avx2’
      gcc: note: valid arguments to ‘-march=’ are: armv2 armv2a armv3 armv3m armv4 armv4t armv5 armv5e armv5t armv5te armv6 armv6-m armv6j armv6k armv6kz armv6s-m armv6t2 armv6z armv6zk armv7 armv7-a armv7-m armv7-r armv7e-m armv7ve armv8-a armv8-a+crc armv8.1-a armv8.1-a+crc iwmmxt iwmmxt2 native
      gcc: error: unrecognized command line option ‘-mavx2’
      gcc: error: unrecognized command line option ‘-mfma’
      gcc: error: unrecognized command line option ‘-mfpmath=sse’
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-install-l0gcf9n9/blis/setup.py", line 266, in <module>
          'Topic :: Scientific/Engineering'
        File "/home/pi/spacy/lib/python3.5/site-packages/setuptools/__init__.py", line 145, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
          cmd_obj.run()
        File "/home/pi/spacy/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
          return orig.install.run(self)
        File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
          self.run_command('build')
        File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.5/distutils/command/build_ext.py", line 339, in run
          self.build_extensions()
        File "/tmp/pip-install-l0gcf9n9/blis/setup.py", line 105, in build_extensions
          objects = self.compile_objects(compiler.split('-')[0], arch, OBJ_DIR)
        File "/tmp/pip-install-l0gcf9n9/blis/setup.py", line 184, in compile_objects
          objects.append(self.build_object(env=env, **spec))
        File "/tmp/pip-install-l0gcf9n9/blis/setup.py", line 198, in build_object
          subprocess.check_call(command, cwd=BLIS_DIR)
        File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['gcc', '-c', '/tmp/pip-install-l0gcf9n9/blis/blis/_src/kernels/zen/1/bli_amaxv_zen_int.c', '-o', '/tmp/tmpryu9665f/bli_amaxv_zen_int.o', '-O3', '-mavx2', '-mfma', '-mfpmath=sse', '-march=core-avx2', '-fPIC', '-std=c99', '-D_POSIX_C_SOURCE=200112L', '-DBLIS_VERSION_STRING="0.5.0-6"', '-DBLIS_IS_BUILDING_LIBRARY', '-Iinclude/linux-x86_64', '-I./frame/3/', '-I./frame/ind/ukernels/', '-I./frame/1m/', '-I./frame/1f/', '-I./frame/1/', '-I./frame/include', '-I/tmp/pip-install-l0gcf9n9/blis/blis/_src/include/linux-x86_64']' returned non-zero exit status 1

      ----------------------------------------
  Command "/home/pi/spacy/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-l0gcf9n9/blis/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-a58yz6ze/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-812jftgz/overlay --compile --install-headers /home/pi/spacy/include/site/python3.5/blis" failed with error code 1 in /tmp/pip-install-l0gcf9n9/blis/

**Comment by honnibal** [comment]
Thanks, I think we should be able to fix this with a bit of effort.

**Comment by pabou38** [comment]
Hello ..

Thank you. 

Note that I just tried to pip install spacy==2.1, and same problem.

Please keep me in the loop, as much as possible. I’ve a bunch of spacy code running fine on Ubuntu, but which I need to use on the PI, as the rest of the application is already sitting there

Cheers

Pascal Boudalier

De : Matthew Honnibal
Envoyé le :vendredi 22 mars 2019 14:42
À : explosion/spaCy
Cc : pascal boudalier; Author
Objet :Re: [explosion/spaCy] PIP install spacy fails on raspberry PI (debian9, ARM) (#3451)

Thanks, I think we should be able to fix this with a bit of effort.

**Comment by mepresnell** [comment]
I am having the exact same issue with the blis files but on my Windows 10 system.

**Comment by r-reis** [comment]
Did anyone find a workaround?

**Comment by pabou38** [comment]
No. I tried with 2.1, and ubuntu  on raspberry (vs) raspian/debian, but no
luck.

Ubuntu on Pc works fine.

I am stuck and I would hate going to NLTK.

Pascal boudalier

Le jeu. 28 mars 2019 à 17:38, Rafael Reis <notifications@github.com> a
écrit :

**Comment by honnibal** [comment]
I mean...You can just install `spacy==2.0.18`? We'll fix the kernels for these things eventually. In the meantime I doubt the previous version will be much different for you.

**Comment by honnibal** [comment]
This should now be fixed. Sorry for the delay.

See here for the workaround: https://github.com/explosion/cython-blis/issues/9
