### ISSUE TITLE
Correct use of train_data in train_textcat.py

### ISSUE THREAD

**Issue by mindscratch** [explosion/spaCy#3464]
Following on from #3151 (which is closed, hence this issue), in the [train_textcat.py](https://github.com/explosion/spacy/blob/master/examples/training/train_textcat.py) example shouldn't the `train_data` be shuffled before calling `minibatch`?

For example:
```
for i in range(n_iter):
    losses = {}
    random.shuffle(train_data)
    batches = minibatch(train_data, size=compounding(4.0, 32.0, 1.001))
```

I was [reading](https://spacy.io/usage/training#annotations) and the "example training loop" doesn't use minibatch, but does shuffle the data.

**Comment by honnibal** [comment]
Yes, that's a bug! Thanks. I was sure I fixed this; I think maybe the commit didn't make it across from my GPU server. This explains my confusing recent results from that script...The batching was also wrong.

**Comment by honnibal** [comment]
Fixed here: https://github.com/explosion/spaCy/commit/4c5f265884776f7c643a2f37150f339a09549231
