### ISSUE TITLE
Token.sent doesn't work with sentencizer

### ISSUE THREAD

**Issue by bongbang** [explosion/spaCy#3474]
`Token.sent` no longer works when `sentencizer` is used instead of `parser` for sentence segmentation. In version 2.0.18, it just gives you the token back. In version 2.1.2, it gives you the whole doc. 

## How to reproduce the behaviour
```
import spacy
from spacy.lang.en import English

nlp = English()  # just the language with no model
sentencizer = nlp.create_pipe("sentencizer")
nlp.add_pipe(sentencizer)
doc = nlp(u"This is a sentence. This is another sentence.")
for sent in doc.sents:
    print(sent.text) # works as expected
 
print(doc[0].sent) # doesn't work
```

## Your Environment

* Operating System:
* Python Version Used: 3.6
* spaCy Version Used: 2.0.18, 2.1.2
* Environment Information:

**Comment by bongbang** [comment]
This causes a problem for the [Benepar](https://github.com/nikitakit/self-attentive-parser) plugin, which apparently relies on `token.sent` and not `doc.sents`.

**Comment by ines** [comment]
Could you try again with the latest version? I'm pretty sure this should be fixed by the update to the sentencizer. I just tried your example and it worked as expected for me!

**Comment by bongbang** [comment]
I didn't actually install 2.1.2. Instead, I just added a line to the [editable example](https://spacy.io/usage/linguistic-features#sbd-component) in your documentation. Maybe that kernel's version isn't the very latest.

**Comment by ines** [comment]
@bongbang Ah yes, the spaCy version is listed in the top right corner. It's currently v2.1.2, since v2.1.3 was just released. But I'll update it and rebuild the image for the new version now.
