### ISSUE TITLE
Change favicon of spacy.io

### ISSUE THREAD

**Issue by rominf** [explosion/spaCy#3475]
Favicon of spacy.io is too similar to Skype icon - same colors, same big letter. When you have many tabs open in your browser, you see at favicons first. So, I had a surprise: "what's Skype doing here?" when I looked at the open tab with spacy.io.

**Comment by ines** [comment]
Omg, I had no idea, I never go to the Skype site! Damn. I just took the old icon and added round corners so it looks a bit nicer as a favicon. I can try a version with the whole logo in the circle, but that might be too small... otherwise, maybe we should go back to the square icon.
