### ISSUE TITLE
Error while use "zh_core_web_sm-2.0.5.tar.gz" for spaCy2.1

### ISSUE THREAD

**Issue by fineartit** [explosion/spaCy#3478]
![image](https://user-images.githubusercontent.com/43510101/54897719-8321ba80-4f04-11e9-8a81-a4ef121d9339.png)
### **How to solve this problem？**

**Comment by ines** [comment]
`zh_core_web_sm` is not an official spaCy model, but based on the error and the model version `2.0.5`, it looks like the model isn't compatible with your version  of spaCy. 

Models are compatible across patch versions, but usually not minor versions. So spaCy v2.1 required training new models. So to use that particular model, you'd either have to run it with spaCy v2.0.x, or retrain the model with the latest version, spaCy v2.1.x.
