### ISSUE TITLE
Printing doc.sents failed when there's only one word in the text

### ISSUE THREAD

**Issue by BLKSerene** [explosion/spaCy#3479]
Hi, I'm using spaCy for text processing in my own tool. In order to improve the speed, I disable some of spaCy's pipelines during different text processing tasks.

```
>>> import spacy
>>> nlp = spacy.load('en', disable = ['tagger', 'parser', 'ner']) # I only need the sentencizer
>>> nlp.add_pipe(nlp.create_pipe('sentencizer'))
>>> doc = nlp('test')
>>> [[token.text for token in sentence.as_doc()] for sentence in doc.sents] # Get 2-D array with lists of tokens delimited by sentences
Traceback (most recent call last):
  File "<pyshell#48>", line 1, in <module>
    print([s for s in doc.sents])
  File "<pyshell#48>", line 1, in <listcomp>
    print([s for s in doc.sents])
  File "doc.pyx", line 589, in sents
ValueError: [E030] Sentence boundaries unset. You can add the 'sentencizer' component to the pipeline with: nlp.add_pipe(nlp.create_pipe('sentencizer')) Alternatively, add the dependency parser, or set sentence boundaries by setting doc[i].is_sent_start.

>>> doc = nlp('test sentence') # Text containing more than one word
>>> [[token.text for token in sentence.as_doc()] for sentence in doc.sents] # OK
[['test', 'sentence']]
```

Using the parser instead of the sentencizer fixes this, but it seems to me that the parser is a bit slower than the sentencizer, and in this case, I only want to do sentence tokenization, not dependency parsing.

```
>>> nlp = spacy.load('en', disable = ['tagger', 'ner'])
>>> doc = nlp('test')
>>> [[token.text for token in sentence.as_doc()] for sentence in doc.sents]
[['test']]
```

And every time when I need to add a pipeline that has been disabled back to the model, I have to re-initialize the model, since the following does not work for me. I'm wondering that is this the correct way to do this?

```
>>> nlp = spacy.load('en', disable = ['tagger', 'parser', 'ner'])
>>> nlp.add_pipe(nlp.create_pipe('tagger'))
>>> doc = nlp('test')
Traceback (most recent call last):
  File "<pyshell#81>", line 1, in <module>
    doc = nlp('test')
  File "D:\Python\lib\site-packages\spacy\language.py", line 385, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))
  File "pipes.pyx", line 374, in spacy.pipeline.pipes.Tagger.__call__
  File "pipes.pyx", line 386, in spacy.pipeline.pipes.Tagger.predict
  File "pipes.pyx", line 74, in spacy.pipeline.pipes.Pipe.require_model
ValueError: [E109] Model for component 'tagger' not initialized. Did you forget to load a model, or forget to call begin_training()?
```

This does not work for me either:

```
>>> nlp = spacy.load('en')
>>> nlp.remove_pipe('ner')
('ner', <spacy.pipeline.pipes.EntityRecognizer object at 0x00000193D68F69A8>)
>>> nlp.add_pipe(nlp.create_pipe('ner'))
>>> doc = nlp('test')
Traceback (most recent call last):
  File "<pyshell#78>", line 1, in <module>
    doc = nlp('test')
  File "D:\Python\lib\site-packages\spacy\language.py", line 385, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))
  File "nn_parser.pyx", line 205, in spacy.syntax.nn_parser.Parser.__call__
  File "nn_parser.pyx", line 238, in spacy.syntax.nn_parser.Parser.predict
  File "nn_parser.pyx", line 235, in spacy.syntax.nn_parser.Parser.require_model
ValueError: [E109] Model for component 'ner' not initialized. Did you forget to load a model, or forget to call begin_training()?
```

## Your Environment
* Operating System: Windows 10 64-bit
* Python Version Used: 3.7.2 64-bit
* spaCy Version Used: 2.1.3

**Comment by ines** [comment]
There are two separate things here:

> Using the parser instead of the sentencizer fixes this, but it seems to me that the parser is a bit slower than the sentencizer, and in this case, I only want to do sentence tokenization, not dependency parsing.

This is currently a limitation of the `sentencizer`, because the `is_sentenced` property is based on whether the `Token.is_sent_start` properties were changed. However, for the first token in a sentence, this will always default to `True`. So if the sentence only contains one token, there's no way for spaCy to tell whether the sentence boundaries have been set or not.

As a workaround, you could trick spaCy into ignoring this by setting `doc.is_parsed = True`, i.e. by making it believe that the dependency parse was assigned and sentence boundaries were applied this way.


> And every time when I need to add a pipeline that has been disabled back to the model, I have to re-initialize the model, since the following does not work for me. I'm wondering that is this the correct way to do this?

If you're using `disable` on `spacy.load`, the pipeline components and their data won't actually be loaded at all. Then you're adding blank new components without data to the pipeline, so spaCy is unable to use them because they're empty.

I think what you're looking for is `nlp.disable_pipes`, which temporarily disables one or more pipeline components *after they've been loaded and then allows restoring them: https://spacy.io/api/language/#disable_pipes

**Comment by BLKSerene** [comment]
Thanks, I got it.

**Comment by Meidan** [comment]
This used to work in version 2.1.0, but it fails in 2.1.3 (with error `ValueError: [E030] Sentence boundaries unset`:
```
nlp = spacy.load("en_core_web_sm", disable=["parser"])
nlp.add_pipe(nlp.create_pipe('sentencizer'))
d = nlp("Singletoken")
list(d.sents)
```
@ines are you saying this is not a bug? Should I use another initialization scheme so single token sentences don't fail?

**Comment by yangchangli** [comment]
spacy version change 2.1.3 to 2.1.0
@Meidan
