### ISSUE TITLE
Slow loading for small Spanish model (es_core_news_sm)

### ISSUE THREAD

**Issue by MIC-BO** [explosion/spaCy#3483]
## How to reproduce the behaviour

It takes around 5 minutes in loading the small corpus, when en_core_web_sm takes only 3 seconds in being loaded. Followig the code:

```python
print ("Loading corpus " + datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
nlp = spacy.load("es_core_news_sm")
print ("Corpus loaded " + datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
```

## Your Environment

* Operating System: Windows 8.1 Pro
* Python Version Used: 3 x64
* spaCy Version Used:  2.1.3
* Environment Information:

**Comment by ines** [comment]
This is very strange – can you double-check that the model you have installed is up to date and that you get the same behaviour in a clean environment? 

Just ran your code with the same spaCy version and the latest `es_core_news_sm` model and it took maybe a second for me: 

```
Loading corpus 2019-03-26 10:56:39
Corpus loaded 2019-03-26 10:56:39
```

**Comment by MIC-BO** [comment]
Hi Ines

Thanks for your time. I followed the spacy documentation running these lines:

pip install -U spacy
python -m spacy download es_core_news_sm

How could I check by myself the source of the problem?

Again, many thanks for your time, you rock !

Regards,
MIC-BO

**Comment by ines** [comment]
Thanks! You can run `python -m spacy validate` to check that your models are up to date. But if you've just installed a model, there shouldn't be a problem.

Are you using a virtual environment? If not, maybe try and reinstall spaCy and the model in a clean environment? If you always install into the same system Python, you can easily end up in a weird state that leads to all sorts of problems. On Windows, creating a new virtual environment could look like this:

```
python -m venv .env
.env\Scripts\activate
pip install -U spacy
python -m spacy download es_core_news_sm
```

**Comment by MIC-BO** [comment]
Dear Ines,

I was using Visual Studio 2017 to run my tests of Spacy. Since I got no way to make them run in a reasonable time, I decided to avoid VS2017 and the loading time for ES models is really fast.

Many, but truly, many thanks for your aid and time.

Best regards,
MIC
