### ISSUE TITLE
Italian Model appears as empty

### ISSUE THREAD

**Issue by paskaly** [explosion/spaCy#3488]
## Download size incorrect
The download size in https://github.com/explosion/spacy-models/releases//tag/it_core_news_sm-2.1.0 is stated as 10MB, but the file downloaded is only 47K.

**Comment by ines** [comment]
That's strange – I just tried downloading the attached `.tar.gz` manually and it worked fine for me? The unpacked size on disk is around 12 MB. Maybe something went wrong when you downloaded the file? Maybe the download got terminated?

**Comment by paskaly** [comment]
I retryed just now and seems to be fine.
I apologize.
Pasquale
