### ISSUE TITLE
Evaluation of NER model per entity type

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#3490]
I evaluated my NER model (built on three entity types ORG, PERSON, and LOC) and got results like this for one of the folds

```
{'uas': 0.0,
 'las': 0.0,
 'ents_p': 94.22382671480143,
 'ents_r': 92.226148409894,
 'ents_f': 93.21428571428572,
 'tags_acc': 0.0,
 'token_acc': 100.0}
```

using this method

```
import spacy
from spacy.gold import GoldParse
from spacy.scorer import Scorer
def evaluate(ner_model, examples):
    scorer = Scorer()
    for input_, annot in examples:
        doc_gold_text = ner_model.make_doc(input_)
        gold = GoldParse(doc_gold_text, entities=annot['entities'])
        pred_value = ner_model(input_)
        scorer.score(pred_value, gold)
    return scorer.scores
```
However I know that these values are for all entities, but I wanted to see what the results were per entity. I search here and on stackoverflow, and I found one of the solutions someon posted as follows

https://stackoverflow.com/a/53345979/1462656

```
import spacy
from spacy.gold import GoldParse
from spacy.scorer import Scorer

def evaluate(nlp, examples, ent='PERSON'):
    scorer = Scorer()
    for input_, annot in examples:
        text_entities = []
        for entity in annot.get('entities'):
            if ent in entity:
                text_entities.append(entity)
        doc_gold_text = nlp.make_doc(input_)
        gold = GoldParse(doc_gold_text, entities=text_entities)
        pred_value = nlp(input_)
        scorer.score(pred_value, gold)
    return scorer.scores
```
But when I ran it on one of my folds, I got a result like this

```
{'uas': 0.0,
 'las': 0.0,
 'ents_p': 10.743801652892563,
 'ents_r': 90.27777777777779,
 'ents_f': 19.202363367799112,
 'tags_acc': 0.0,
 'token_acc': 100.0}
```

Which leads me to believe that the GoldParse method is using all entities in its calculation so the solution above won't work.

One work around I can think of would be to create individual gold standard files (one for each entity type) and use the above solution on each entity type. 

But is there a more automated way to use the GoldParse method so that it calculates the scores based on a specific entity type? (without having to eliminate entities manually from the input)

**Comment by YuanFuIW** [comment]
Hey friend, I also wanna actualize this function and did my effort. but my result is even worse. It always prints 0 for any entities.

After training a model, it will call the evaluation method for each entity type. 
**
        # evaluation by each ent
        ents = ['street', 'description','date', 'file_nr']
        print('%-25s %-10s %-10s %-10s' % ("Entity", "Precision", "Recall", "f-measure"))
        for e in ents:
            results = evaluate(nlp2, test_data, e)
        # calculate precision, recall, f_measure
            report_scores(results, e)
**
Here is the evaluation method:
**
def evaluate(ner_model, test_data, ent):
    scorer = Scorer()
    for input_, annot in test_data:
        text_entities = []
        for entity in annot.get('entities'):
            if ent in entity:
                text_entities.append(entity)

        doc = ner_model(input_)
        gold = GoldParse(doc)
        pred_value = ner_model(input_)
        scorer.score(pred_value, gold)

    return scorer.scores
**
print score in table:
**
def report_scores(scores, e):
    """
    prints precision recall and f_measure
    :param scores:
    :return:
    """

    precision = '%.2f' % scores['ents_p']
    recall = '%.2f' % scores['ents_r']
    f_measure = '%.2f' % scores['ents_f']
    print('%-25s %-10s %-10s %-10s' % (e, precision, recall, f_measure))
**
result is always precision = 0.00 recall = 0.00, f_m=0.00 for all entities.

**Comment by honnibal** [comment]
We need to update the scorer to allow per entity evaluation. I haven't had a chance to check that StackOverflow code yet, but I hope the bug won't be too difficult to find. It shouldn't be such a difficult problem.

**Comment by elbaulp** [comment]
Hello, I am trying to solve this issue, right now its a work in progress, but I think I am very close to completely solve it. Please comment with any feedback if you have any suggestion.

**Comment by erotavlas** [comment]
@ines will this be included in the next release?  Do you know approximately when that will be? Thanks
