### ISSUE TITLE
Pickling of PhraseMatcher not yet resolved in 2.1.3

### ISSUE THREAD

**Issue by kushalc** [explosion/spaCy#3494]
https://github.com/explosion/spaCy/issues/1971 and https://github.com/explosion/spaCy/issues/3248 show that pickling works, but I'm still able to repro issues in 2.1.3.

## Minimal Reproducible Example
Building off #3252 unit test:
```
from spacy.matcher import PhraseMatcher
from spacy.lang.en import English
from spacy.compat import pickle
nlp = English()

matcher = PhraseMatcher(nlp.vocab)
matcher.add("TEST1", None, nlp("a"), nlp("b"), nlp("c"))
matcher.add("TEST2", None, nlp("d"))
data = pickle.dump(matcher, open("matcher.pickle", "wb"))
new_matcher = pickle.load(open("matcher.pickle", "rb"))
print(new_matcher(nlp("a b c")))  # prints [(9789093191506324669, 0, 1), (9789093191506324669, 1, 2), (9789093191506324669, 2, 3)]
print(matcher(nlp("a b c")))  # prints [(9789093191506324669, 0, 1), (9789093191506324669, 1, 2), (9789093191506324669, 2, 3)]
```

(re-start Python)
```
from spacy.lang.en import English
from spacy.compat import pickle
nlp = English()
new_matcher = pickle.load(open("matcher.pickle", "rb"))
new_matcher(nlp("a b c"))  # prints []
```

## Info about spaCy

* **spaCy version:** 2.1.3
* **Platform:** Darwin-18.2.0-x86_64-i386-64bit
* **Python version:** 3.7.2
* **Models:** en

**Comment by svlandeg** [comment]
I can reproduce your error with the code above. However, I don't think it's a `Matcher` pickling issue. If you would keep the same `nlp` object rather than constructing a new one, you wouldn't run into this, right?

**Comment by kushalc** [comment]
Is there a recommended best practice for pickling nlp/Matcher between
different processes? The fundamental use case we have to solve is
serialization across different machines so we can't simply re-use the same
nlp instance.

Kushal

**Comment by svlandeg** [comment]
Is it an option to serialize the `nlp` object (https://spacy.io/usage/saving-loading) ?
