### ISSUE TITLE
Training custom data

### ISSUE THREAD

**Issue by viksit** [explosion/spaCy#35]
Could you provide some insights on training custom data sets for spaCy? Looking at the code in vocab.pyx, it makes me think that if not already, it should be easy to load the google word2vec data through spacy? (I'm not very familiar with that format just yet).

```
..
string_id = self.strings[chars[:word_len]]
while string_id >= vectors.size():
vectors.push_back(EMPTY_VEC)
assert vec != NULL
vectors[string_id] = vec
..
```

**Comment by viksit** [comment]
@honnibal any insights?

**Comment by honnibal** [comment]
v1.0 introduces much better training APIs. More tutorials will be published, but hopefully this is enough to get people started:

https://spacy.io/docs/tutorials/training
