### ISSUE TITLE
Error while training a new entity with large datasets

### ISSUE THREAD

**Issue by HarshavardhanG513** [explosion/spaCy#3505]
## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by HarshavardhanG513** [comment]
sorry i pressed enter before writing something, so here's the problem.
I am training a model to identify job titles as an entity. I used a slightly modified version of the example code on the spacy.io website for training an additional entity.

while running the code with small amounts of data, it works. When tried to improve the accuracy by adding a lot more data, it stopped working and instead gave me the following:

File "getjob.py", line 389, in <module>
    main()
  File "getjob.py", line 360, in main
    nlp.update(texts, annotations, sgd=optimizer, drop=0.35, losses=losses)
  File "C:\Users\Harsha\Miniconda3\lib\site-packages\spacy\language.py", line 409, in update
    doc = self.make_doc(doc)
  File "C:\Users\Harsha\Miniconda3\lib\site-packages\spacy\language.py", line 378, in make_doc
    return self.tokenizer(text)
SystemError: <spacy.tokenizer.Tokenizer object at 0x05B6F270> returned NULL without setting an error

**Comment by HarshavardhanG513** [comment]
spaCy version      2.0.12
    Location           C:\Users\Harsha\Miniconda3\lib\site-packages\spacy
    Platform           Windows-10-10.0.17763-SP0
    Python version     3.7.1
    Models             en, en_core_web_md

**Comment by ines** [comment]
> `SystemError: <spacy.tokenizer.Tokenizer object at 0x05B6F270> returned NULL without setting an error`

This error sounds like you might be using a 32-bit version of Python instead of 64-bit. Also see #3250, where this has come up before.

Could you double-check your Python installation and try again with a 64-bit installation?

**Comment by HarshavardhanG513** [comment]
doesn't recognize spacy anymore. I used the following conda command:
conda install -c conda-forge spacy
the requested packages were installed
python -m spacy download en
no module named spacy.

just trying to resolve the error

**Comment by HarshavardhanG513** [comment]
i think its working. thank a lot. your advanced spacy course on datacamp was also quite helpful when i started.
