### ISSUE TITLE
Spacy nlp (v2.1.3) using all threads with Mac OS and conda version of numpy

### ISSUE THREAD

**Issue by deatinor** [explosion/spaCy#3506]
I am aware that in spacy 2.0 n_threads was not kept into account while running spacy nlp and all the threads available were used for the computations. (https://github.com/explosion/spaCy/issues/2075)
According to the cited issue, this should have been fixed with spacy 2.1.

I noticed that I have the same problem with spacy 2.1.3 and the conda version of numpy installed (on Mac OS X). If switching to the pip numpy only 1 thread is used as expected.

Thanks for taking this into account!

## My Environment
* Operating System: Mac OS X
* Python Version Used: 3.6.8
* spaCy Version Used: 2.1.3
* Environment Information: conda

**Comment by honnibal** [comment]
Hmm! What functions are you running? There must be somewhere we're calling into numpy on something it parallelises, which is not what we want.

**Comment by deatinor** [comment]
I'm just running the commands:

    nlp = spacy.load('en')
    nlp('some text')

It's probably the backend math library of numpy. I think that conda numpy uses MKL and pip numpy something else (maybe Open BLAS?)

**Comment by honnibal** [comment]
Hmm. Just for sanity can you print `spacy.__version__`?

The matrix multiplications in v2.1 should all be getting routed through Blis, not numpy. So I'm not sure what's going on. Maybe there's an operation apart from matrix multiplication that gets parallelised on the mkl version of numpy, but not on the OpenBLAS version?

Once we figure out what this is we can make sure that operation gets handled by Blis as well. But until we figure out where the call is happening it's tricky. Could you run `sudo perf top` while the code is running to see what compiled functions it says it's spending the most time in?
