### ISSUE TITLE
Training is using only one core

### ISSUE THREAD

**Issue by filipecaixeta** [explosion/spaCy#3507]
## How to reproduce the behaviour
I am training a NER with the following code ([simple training style example](https://spacy.io/usage/training#training-simple-style))
```
# get names of other pipes to disable them during training
other_pipes = [pipe for pipe in nlp.pipe_names if pipe != "ner"]
with nlp.disable_pipes(*other_pipes):  # only train NER
    # reset and initialize the weights randomly – but only if we're
    # training a new model
    if model is None:
        nlp.begin_training()
    for itn in range(n_iter):
        random.shuffle(TRAIN_DATA)
        losses = {}
        # batch up the examples using spaCy's minibatch
        batches = minibatch(TRAIN_DATA, size=compounding(8.0, 32.0, 1.01))
        for batch in batches:
            texts, annotations = zip(*batch)
            nlp.update(
                texts,  # batch of texts
                annotations,  # batch of annotations
                drop=0.5,  # dropout - make it harder to memorise data
                losses=losses
            )
        print("Losses", losses)
```

**When I use spaCy version 2.0.12 I have 48 cores on 100% usage**
**When I use spaCy version 2.1.3 I have 1 core on 100% usage**

## Your Environment

* **spaCy version:** 2.1.3
* **Platform:** Linux-4.20.1-arch1-1-ARCH-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.6.7

* Architecture:        x86_64
* CPU op-mode(s):      32-bit, 64-bit
* Byte Order:          Little Endian
* Address sizes:       46 bits physical, 48 bits virtual
* CPU(s):              96
* On-line CPU(s) list: 0-95
* Thread(s) per core:  2
* Core(s) per socket:  24
* Socket(s):           2
* NUMA node(s):        2
* Vendor ID:           GenuineIntel
* CPU family:          6
* Model:               85
* Model name:          Intel(R) Xeon(R) Platinum 8160 CPU @ 2.10GHz
* Stepping:            4
* CPU MHz:             1000.034
* CPU max MHz:         3700.0000
* CPU min MHz:         1000.0000
* BogoMIPS:            4201.00
* Virtualization:      VT-x
* L1d cache:           32K
* L1i cache:           32K
* L2 cache:            1024K
* L3 cache:            33792K

**Comment by honnibal** [comment]
Yes, I worked very hard to make that improvement. https://explosion.ai/blog/spacy-v2-1#matrix-multiplication

More cores isn't necessarily better. v2.0.18 left the matrix multiplication up to numpy, which delegated it to system libraries that usually incorrectly launched far too many threads. You should find training faster on that version if you limit the threads to two or three.

v2.1.3 limits to single thread to make much more efficient usage of the machine. You should find it almost as fast or actually faster, with vastly less machine usage. We're interested in implementing proper parallel training to outer loops as well, but for now preventing it from launching threads for the matrix multiplications is a big step forward.
