### ISSUE TITLE
details on which features/models are required per pipe

### ISSUE THREAD

**Issue by bdewilde** [explosion/spaCy#3508]
I'm curious about which features (and, in turn, the models that generate them) are required by a given pipe in a pipeline. I'm currently training a `TextClassifier`, and was wondering if it _must_ come after the POS tagger and dependency parser, or if `nlp.add_pipe(textcat, last=True)` from the example script is just a preference. I couldn't find this information anywhere in the docs, and wasn't able to figure it out from snooping around `pipes.pyx`. It's totally possible that I'm missing something obvious — like, maybe all it needs are tokens? — but figured I'd raise the issue just in case.

## Which page or section is this issue related to?

https://spacy.io/api/textcategorizer
https://spacy.io/usage/training

**Comment by ines** [comment]
I think [here's the section](https://spacy.io/usage/processing-pipelines#pipeline-components-order) you're looking for (sorry, it was in the processing pipelines docs):

> In spaCy v2.x, the statistical components like the tagger or parser are independent and don’t share any data between themselves. For example, the named entity recognizer doesn’t use any features set by the tagger and parser, and so on. This means that you can swap them, or remove single components from the pipeline without affecting the others.
>
> However, custom components may depend on annotations set by other components. For example, a custom lemmatizer may need the part-of-speech tags assigned, so it’ll only work if it’s added after the tagger. The parser will respect pre-defined sentence boundaries, so if a previous component in the pipeline sets them, its dependency predictions may be different. Similarly, it matters if you add the `EntityRuler` before or after the statistical entity recognizer: if it’s added before, the entity recognizer will take the existing entities into account when making predictions.

**Comment by bdewilde** [comment]
Aha! I figured it would be discussed somewhere. Thanks, Ines. :)

Since different/custom pipes _may_ have dependencies on annotations set by other models, would that be a thing to document in, say, the pipe class docstrings? Or is/could there a way to determine it programmatically, per pipe?

**Comment by honnibal** [comment]
We have some plans to implement a better metadata system for this, so that components can declare what they set and their requirements. At the moment the pipeline components are independent of each other so we're working around the lack of it that way.

One unsolved problem is what to do during training. Naively each component could make its predictions, update, and then set the annotations. But in v1 I came to really dislike that we'd be writing to the doc during training, as it meant each epoch we'd have to recreate the docs, or bad things would happen.
