### ISSUE TITLE
Can't parse after merge?

### ISSUE THREAD

**Issue by bongbang** [explosion/spaCy#3509]
The parser raises a `ValueError` when used after a span in the doc has been merged. The message is either one of these two:

1. cannot resize this array: it does not own its data
2. all the input array dimensions except for the concatenation axis must match exactly

## How to reproduce the behaviour

```
import spacy
nlp = spacy.load('en_core_web_sm')
parser = nlp.pipeline[1][1]
assert isinstance(parser, spacy.pipeline.DependencyParser)

doc = nlp('Henry V is the best.', disable=['parser'])
parser(doc) # works

doc = nlp('Henry V is the best.', disable=['parser'])
doc[0:2].merge()
parser(doc) 
# ValueError: all the input array dimensions except for the concatenation axis must match exactly
```

## Your Environment

* Operating System:
* Python Version Used: 3.6
* spaCy Version Used: 2.0.18
* Environment Information:

**Comment by honnibal** [comment]
This should be fixed in v2.1. The bug was that we didn't resize the tensors during merge. If you install v2.1 you should find it fixed.
