### ISSUE TITLE
The verb 'like' confuses the parser

### ISSUE THREAD

**Issue by fersarr** [explosion/spaCy#3516]
The verb 'like' confuses the parser (might be another one for perf/accuracy) . In some cases the branch of the dependency tree is `'prep'` when it should be `'nsubj'`. Also, `'like'` itself shouldn't be tagged as `'ADP'`, it should be a verb. See below for examples:

`'prep'` should be `'nsubj'`
![Screen Shot 2019-03-31 at 7 33 38 PM](https://user-images.githubusercontent.com/3913371/55293204-f2f3e180-53eb-11e9-8d12-65212668cdcc.png)

![Screen Shot 2019-03-31 at 7 36 45 PM](https://user-images.githubusercontent.com/3913371/55293248-5b42c300-53ec-11e9-80b1-dcc418f66df1.png)

**Comment by ines** [comment]
Merging this with #3052!
