### ISSUE TITLE
Contraction "n’t" not tagged as stop word ("n't" with dumb quote is fine)

### ISSUE THREAD

**Issue by admackin** [explosion/spaCy#3521]
## How to reproduce the behaviour

```
en = en_core_web_md.load(disable=['parser', 'ner', 'textcat'])
tok = en("don’t")[1]  # note that it is smartquote-like "’" not dumb "'"
print(tok.lemma_)   #  correctly returns "not"
print(tok.is_stop)   # incorrectly returns False
```

## Info about spaCy

* **spaCy version:** 2.1.3
* **Platform:** Darwin-17.7.0-x86_64-i386-64bit
* **Python version:** 3.6.4

**Comment by ines** [comment]
Thanks for the report – looks like we might have to add `n’t` to the list of English stop words as well.

**Comment by svlandeg** [comment]
I suggest to make a little loop in [stop_words.py](https://github.com/explosion/spaCy/blob/master/spacy/lang/en/stop_words.py) that goes through all hyphens for those stopwords that are hyphenated, then we'll catch all cases. I can quickly draft that PR if noone's currently working on it.

**Comment by svlandeg** [comment]
Should be fixed with PR https://github.com/explosion/spaCy/pull/3530 !
