### ISSUE TITLE
Returned null without setting an error (Incorrect answer)

### ISSUE THREAD

**Issue by HarshavardhanG513** [explosion/spaCy#3522]
See your other issue in #3505: This error occurs if you're running a 32-bit version of Python instead of a 64-bit version.
That is incorrect as my python version is a 64-bit version. I installed the 64-bit version just yesterday.

**Comment by ines** [comment]
Could you post the exact error you're seeing?

**Comment by HarshavardhanG513** [comment]
SystemError: <spacy.tokenizer.Tokenizer object at 0x06E0E7B0> returned NULL without setting an error

**Comment by ines** [comment]
To double-check, could you run the following and share the result?

```bash
python -c "import struct;print( 8 * struct.calcsize('P'))"
```

**Comment by HarshavardhanG513** [comment]
64

**Comment by ines** [comment]
Does the error still occur with the latest version, `v2.1.3`?

**Comment by HarshavardhanG513** [comment]
i upgraded it, but when i try to install modules like sklearn it downgrades spacy.

**Comment by HarshavardhanG513** [comment]
i think it worked. thanks a lot.
