### ISSUE TITLE
AttributeError: 'English' object has no attribute 'resume_training' on line optimizer = nlp.resume_training()

### ISSUE THREAD

**Issue by ameyn21** [explosion/spaCy#3524]
## Your Environment

* Operating System: windows 10
* Python Version Used: Python 3.6.5 :: Anaconda, Inc.
* spaCy Version Used:  2.0.11
* Environment Information:

**Comment by ines** [comment]
Not sure what you're trying to do, but the `resume_training` attribute was only added in spaCy v2.1.x. It looks like you're running an older version, 2.0.11. So you'd either have to upgrade your spaCy installation, or rewrite your code to not use `resume_training`.
