### ISSUE TITLE
Saving model with EntityRuler pipeline doesn't preserve the overwrite flag

### ISSUE THREAD

**Issue by chingan-tsc** [explosion/spaCy#3526]
## How to reproduce the behaviour

```python
    # Create the model
    nlp = spacy.load("xx")
    ruler = EntityRuler(nlp, overwrite_ents=True)
    ruler.add_patterns([{"label": "ORG", "pattern": "Apple"}])
    nlp.add_pipe(ruler)
    nlp.to_disk("test_model")

    print(nlp.pipeline)
    print(nlp.pipeline[-1][-1].patterns)
    print(nlp.pipeline[-1][-1].overwrite) # This prints True

    # Load the saved model
    nlp3 = spacy.load("test_model")
    print(nlp3.pipeline)
    print(nlp3.pipeline[-1][-1].patterns)
    print(nlp3.pipeline[-1][-1].overwrite) # This prints False
```

## Your Environment

* Operating System: Mac Mojave
* Python Version Used: 3.6
* spaCy Version Used: 2.1.3
* Environment Information:

I am trying to use `EntityRuler` by adding it to the existing xx model and saving the model to disk as described in the docs but I noticed after reloading the model from disk the `overwrite_ents` flag is not preserved. Any ideas?

**Comment by ines** [comment]
Thanks, good point! It looks like we're currently not serializing the config of the component. So we should probably be writing out an additional `entityruler.cfg` or something like that and also include that information in the serialized bytes, similar to how the `Sentencizer` is doing it ([see here](https://github.com/explosion/spaCy/blob/24cecdb44fe7349f7382dddeeb6ce047c32db813/spacy/pipeline/pipes.pyx#L1156)).

In the meantime, you should be able to overwrite it manually after loading the model:

```python
nlp = spacy.load("test_model")
ruler = nlp.get_pipe("entity_ruler")
ruler.overwrite_ents = True
```

**Comment by chingan-tsc** [comment]
Yeah I am actually am doing that right now as a workaround solution. Thanks for the advice.
