### ISSUE TITLE
ValueError: [E024]

### ISSUE THREAD

**Issue by HarshavardhanG513** [explosion/spaCy#3527]
What is wrong with this piece of code? It seems to follow the correct format for the latest spacy versions.

```python
other_pipes = [pipe for pipe in nlp.pipe_names if pipe != 'ner']
    with nlp.disable_pipes(*other_pipes):  # only train NER
        optimizer = nlp.begin_training()
        for itn in range(10):
            print("Statring iteration " + str(itn))
            random.shuffle(TRAIN_DATA)
            losses = {}
            for text, annotations in TRAIN_DATA:
                nlp.update(
                    [text],  # batch of texts
                    [annotations],  # batch of annotations
                    drop=0.2,  # dropout - make it harder to memorise data
                    sgd=optimizer,  # callable to update weights
                    losses=losses
                )
            print(losses)
```

It throws the following error:

ValueError: [E024] Could not find an optimal move to supervise the parser. Usually, this means the GoldParse was not correct. For example, are all labels added to the model?

I have read that this is due to a labeling error. Is the labeling error in the training set?

**Comment by HarshavardhanG513** [comment]
If so how can i fix this?

**Comment by HarshavardhanG513** [comment]
environment:
spaCy version    2.1.3
Location         C:\Users\Harsha\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy
Platform         Windows-10-10.0.17763-SP0
Python version   3.7.3

**Comment by ines** [comment]
Did you check that all labels are present in the model? For example, before your training loop, did you make sure that all labels that are in your data were added?

**Comment by shankar939014** [comment]
n_iter=10
nlp = spacy.blank("en")

if "ner" not in nlp.pipe_names:
    ner = nlp.create_pipe("ner")
    nlp.add_pipe(ner, last=True)
    
for _, annotations in TRAIN_DATA:
        for ent in annotations["entities"]:
            ner.add_label(ent[2])
        

def reformat_train_data(tokenizer, examples):
    """Reformat data to match JSON format"""
    print(examples)
    output = []
    for i, (text, entity_offsets) in enumerate(examples):
        doc = tokenizer(text.strip())
        ner_tags = biluo_tags_from_offsets(tokenizer(text), entity_offsets['entities'])
        words = [w.text for w in doc]
        tags = ['-'] * len(doc)
        heads = [0] * len(doc)
        deps = [''] * len(doc)
        sentence = (range(len(doc)), words, tags, heads, deps, ner_tags)
        output.append((text, [(sentence, [])]))
    return output

def get_data(): return reformat_train_data(nlp.tokenizer, TRAIN_DATA)

optimizer = nlp.begin_training(get_data)

for itn in range(10):
        random.shuffle(TRAIN_DATA)
        losses = {}
        for raw_text, entity_offsets in TRAIN_DATA:
            doc = nlp.make_doc(raw_text.strip())
            #ents = [(ent[0], ent[1], ent[2]) for ent in entity_offsets]
            gold = GoldParse(doc, entities=entity_offsets['entities'])
            nlp.update([doc], [gold], drop=0.5, sgd=optimizer, losses=losses)    

I have tried with the above code. I am also getting the same error. Labels got added to the pipe line. Still getting the issue. Is there any bug in Spacy 2.1.3 ? It worked with the previous version.

**Comment by jlebeda** [comment]
Same problem here. I have a trained model in version 2.0.18. When I try to train a model using same data and code in new version I get an error. Even when I roll back and try to do the training in old version now, it works just fine.

**Comment by honnibal** [comment]
Could you provide an annotated sentence that makes it fail? I'm just trying to understand the problem better, but without the failing case it's hard.

**Comment by Zerthick** [comment]
I'm experiencing this issue as well. The NER model trains fine on `v2.0.18`, but throws this error on `v2.1.3`.  Here's an example of a sentence that causes it to break taken from the dataset given here: https://dataturks.com/blog/named-entity-recognition-in-resumes.php

```JSON
[
    "Deepika S\nTest Engineer - Infosys Ltd\n\n- Email me on Indeed: indeed.com/r/Deepika-S/1b4436206cf5871b\n\nWORK EXPERIENCE\n\nTest Engineer\n\nInfosys Ltd -  Chennai, Tamil Nadu -\n\nApril 2017 to Present\n\nTesting Executive, Infosys Ltd, Chennai\n\nE-publisher -  Coimbatore, Tamil Nadu -\n\nMay 2013 to July 2014\n\nSeptember 2014 - March 2017)\n\nTest Management Tool\n\nHP ALM -\n\n2012 to 2012\n\n\u2022 Domain: Retail, Banking\n\u2022 Utilities: Putty, WinScp.\n\u2022 Operating Systems: Windows XP/7/8\n\nPROFESSIONAL EXPOSURE \nSoftware Testing Projects\n\nCiti Bank -\n\n2005 to 2005\n\nDescription of the Project: The objective of the project is to track the Gifts and Entertainment\nprovided to or received from client or potential client or anyone else whom citi does business.\nCGE it is a web based application.\nAnd the project uses separate tool IFW for reporting.\nTesting Management Tool: ALM for tracking defect\nDuration: Nov 2016 to Till Date\n\nCustomer Service Representative\n\nTNT Express -\n\n2004 to 2004\n\nDescription of the Project: The Objective of the project is to use Salesforce for servicing the\ncustomer. TNT express is a courier company which does international business with more than 60\n\nhttps://www.indeed.com/r/Deepika-S/1b4436206cf5871b?isid=rex-download&ikw=download-top&co=IN\n\n\ncountries. They are using more than 30 applications for tracking their process and it is difficult to\nprovide service for the customer. This project integrates with all application and provided single\ninterface for customer service. Also it helps CSR (Customer Service Representative) to provide\nservice for the customer by tracking where exactly their consignment is placed and how much\ntime it will take to reach the destination. Also CSR can receive voice calls and place calls to the\ncustomer through salesforce.\n\nJob scheduling tool: Director Client\nTesting Management Tool\n\nUtilities\nDatabase tools\n\nDuration\n: ALM for tracking requirements, test plans, test execution, reporting and Defect tracking\n\n: WinScp, Putty\n\n: SQL Developer, DataStage for DB2\n\n: Mar 2016 - Oct 2016\n03 Project Name: CRM Sales\n\nClient: TNT Express\nDescription of the Project: The Objective of the project is to use Salesforce for customer\nrelationship management that stores customer contact information like names, addresses, and\nphone numbers. TNT express is a courier company which does international business with more\nthan 60 countries. They used CDB for storing customer information. This project integrates with\nCDB and extracts all customer information. And it creates opportunities for the customers.\n\nTesting Management Tool\n\nUtilities\nDatabase tools\n\nDuration\n: ALM for tracking requirements, test plans, test execution, reporting and Defect tracking\n\n: WinScp, Putty\n\n: SQL Developer\n\n: Jan 2016 - Feb 2016\n02 Project Name: CDB UI Changes\n\nClient: TNT express\nDescription of the Project\n\nTest Management Tool\n\n\n\nThe project is about TNT needs some UI Changes in the CDB application.\n\nALM\n\n01 Duration\nProject Name\nClient\nDescription of Project\n\nDevices tested\n\nDefect Management Tool\nDuration\n\nE-Pub\nClient\nDescription of Project\n\nEDUCATION\n\nB.Sc. in Computer Science\n\nBharathiyar University -  Coimbatore, Tamil Nadu\n\n2013",
    {
        "entities":[
            [
                3170,
                3174,
                "Graduation Year"
            ],
            [
                3120,
                3143,
                "College Name"
            ],
            [
                3093,
                3118,
                "Degree"
            ],
            [
                281,
                285,
                "Graduation Year"
            ],
            [
                226,
                234,
                "Location"
            ],
            [
                213,
                225,
                "Companies worked at"
            ],
            [
                148,
                156,
                "Location"
            ],
            [
                119,
                132,
                "Designation"
            ],
            [
                61,
                101,
                "Email Address"
            ],
            [
                25,
                37,
                "Companies worked at"
            ],
            [
                10,
                23,
                "Designation"
            ],
            [
                0,
                9,
                "Name"
            ]
        ]
    }
]
```

**Comment by ines** [comment]
Merging this with #3558!

**Comment by saipavanmeruga** [comment]
This issue can be resolved by text pre-processing. After reading this thread i checked on my dataset and there were a lot of escape sequence characters including the white spaces.....then i created a separate function for cleaning up the text and gave it to train in spacy v2.1.3 then it works fine. I cant say this solution is generic but text pre processing helps you resolve it.

**Comment by abinpaul1** [comment]
> This issue can be resolved by text pre-processing. After reading this thread i checked on my dataset and there were a lot of escape sequence characters including the white spaces.....then i created a separate function for cleaning up the text and gave it to train in spacy v2.1.3 then it works fine. I cant say this solution is generic but text pre processing helps you resolve it.

But if we pre-process the text to remove the spaces, won't we have to annotate the data again because the start character and end character for each span will change for each text.

**Comment by Zerthick** [comment]
@abinpaul1 See https://github.com/explosion/spaCy/issues/3558#issuecomment-487953653 for a fix without re-annotating the data.
