### ISSUE TITLE
Displacy producing KeyError: 'settings'

### ISSUE THREAD

**Issue by paulrinckens** [explosion/spaCy#3531]
## How to reproduce the behaviour
Running the example from the docs for manual entity visualization:

```python
from spacy import displacy

ex = [{"text": "But Google is starting from behind.",
       "ents": [{"start": 4, "end": 10, "label": "ORG"}],
       "title": None}]
html = displacy.render(ex, style="ent", manual=True)
```

## Error
```
line 52, in render
    _html["parsed"] = renderer.render(parsed, page=page, minify=minify).strip()

line 257, in render
    self.direction = p["settings"].get("direction", DEFAULT_DIR)
KeyError: 'settings'
```

## Info about spaCy

* **spaCy version:** 2.1.3
* **Platform:** Darwin-18.2.0-x86_64-i386-64bit
* **Python version:** 3.7.1

**Comment by ines** [comment]
Thanks for the report! The `"settings"` were added in v2.1 to allow passing through additional config (like the writing direction for RTL languages) – but it seems like the rendering logic expects that `"settings"` always exists, which it probably shouldn't.
