### ISSUE TITLE
Running list of unexpected outputs

### ISSUE THREAD

**Issue by piotr-teterwak** [explosion/spaCy#354]
Hey all,

spaCy is awesome, but occasionally it gives unexpected answers. Sometimes these unexpected outputs are handled better by NLTK, for instance. I'm sure it goes the other way too sometimes. 

I thought it might be useful to start an issue with a running list of unexpected outputs. This may help folks notice patterns to start debugging models. 

I'll start.  

``` python
import spacy
nlp = spacy.English()
doc = nlp(u"Thankyou Emeril- I couldnt find a crust without added flour, yours is Just cornmeal...... I didnt have any shortening so i substituted solid bacon fat - it worked great for my quiche!! your recipe was so easy - my 1st homemade crust! Anika in California")
for sent in doc.sents:
    print(sent)
```

Gives 

```
Thankyou Emeril- I couldnt find a crust without added flour, yours is Just cornmeal...... I didnt have any shortening
so i substituted solid bacon fat - it worked great for my quiche!!
your recipe was so easy - my 1st homemade crust!
Anika in California
```

It should not break on the `so`, in my opinion.

**Comment by piotr-teterwak** [comment]
Another:

```python
import spacy
nlp = spacy.English()
doc = nlp(u"The quick brown fox jumps.The slow brown fox crawls")
for tok in doc:
    print(str(tok) + tok.tag_)
```

gives

```
The DT
quick JJ
brown JJ
fox NN
jumpsNNS
..
The DT
slow JJ
brown NN
fox NN
crawlsVBZ
```

jumps isn't a noun, and neither is brown.

**Comment by Terrilocks** [comment]
Heya,
I also noticed the sentence splitting on "so" and reported it. Take a look at #231 to see what they said about it (quite a long thread!).

**Comment by piotr-teterwak** [comment]
Thanks @Terrilocks. Quite a good discussion!
