### ISSUE TITLE
Matcher with `validate = True` raises on valid patterns 

### ISSUE THREAD

**Issue by jjhbw** [explosion/spaCy#3549]
Hi guys, thanks for this amazing library!

I was playing with the rule based matching functionality and came across some weird behaviour with the `Matcher` class. It seems initiating it with `validate = True` causes valid patterns to raise `spacy.errors.MatchPatternError`.

I've copied an [example from the docs](https://spacy.io/usage/rule-based-matching#adding-patterns) and added the `validate = True` kwarg.

## How to reproduce the behaviour
```python
import spacy
from spacy.matcher import Matcher
nlp = spacy.load("en_core_web_sm")

matcher = Matcher(nlp.vocab, validate = True)
pattern = [{"LOWER": "hello"}, {"LOWER": "world"}]
matcher.add("HelloWorld", None, pattern)
doc = nlp(u'hello world!')
matches = matcher(doc)
```

This results in:
```
Traceback (most recent call last):
  File "./tests/matchertest.py", line 7, in <module>
    matcher.add("HelloWorld", None, pattern)
  File "matcher.pyx", line 109, in spacy.matcher.matcher.Matcher.add
spacy.errors.MatchPatternError: Invalid token patterns for matcher rule 'HelloWorld'

Pattern 0:


```

## Info about spaCy

* **spaCy version:** 2.1.3
* **Platform:** Darwin-18.5.0-x86_64-i386-64bit
* **Python version:** 3.6.8
* **Models:** en

**Comment by ines** [comment]
Thanks for the report – no idea how this happened 🤔 Looks like the match pattern error was also raising even if there were no errors. Should be fixed now!

**Comment by jjhbw** [comment]
Wow that was quick, thanks so much for the fix!
