### ISSUE TITLE
a lemma is not lowercace.

### ISSUE THREAD

**Issue by lancemoon** [explosion/spaCy#3551]
## Issue

When I try to get lemma of following sentence, the lemma of first word "At" is started with uppercase. 

> 'At that level of impact, gender equity is a top solution to restore a climate fit for life.'

Do you guys have any idea why this is happening?

(I reproduced it by Binder which is embedded at https://spacy.io/usage/spacy-101#annotations-pos-deps )

## Source

import spacy

nlp = spacy.load('en_core_web_sm')
doc = nlp(u'At that level of impact, gender equity is a top solution to restore a climate fit for life.')

for token in doc:
    print(token.text, token.lemma_, token.pos_, token.tag_, token.dep_,
            token.shape_, token.is_alpha, token.is_stop)
    
spacy.info()

## Result

**At At ADP IN prep Xx True True**
that that DET DT det xxxx True True
level level NOUN NN pobj xxxx True False
of of ADP IN prep xx True True
impact impact NOUN NN pobj xxxx True False
, , PUNCT , punct , False False
gender gender NOUN NN compound xxxx True False
equity equity NOUN NN nsubj xxxx True False
is be VERB VBZ ROOT xx True True
a a DET DT det x True True
top top ADJ JJ amod xxx True True
solution solution NOUN NN attr xxxx True False
to to PART TO aux xx True True
restore restore VERB VB relcl xxxx True False
a a DET DT det x True True
climate climate NOUN NN compound xxxx True False
fit fit NOUN NN dobj xxx True False
for for ADP IN prep xxx True True
life life NOUN NN pobj xxxx True False
. . PUNCT . punct . False False

============================== Info about spaCy ==============================

spaCy version    2.1.3                         
Location         /srv/conda/lib/python3.7/site-packages/spacy
Platform         Linux-4.14.91+-x86_64-with-debian-buster-sid
Python version   3.7.2                         
Models                                         

{'spaCy version': '2.1.3',
 'Location': '/srv/conda/lib/python3.7/site-packages/spacy',
 'Platform': 'Linux-4.14.91+-x86_64-with-debian-buster-sid',
 'Python version': '3.7.2',
 'Models': ''}

**Comment by honnibal** [comment]
Thanks! Fixed.
