### ISSUE TITLE
Poor quality sentence segmentation around quotation marks

### ISSUE THREAD

**Issue by BramVanroy** [explosion/spaCy#3553]
The output of the below script is 

> The generic name refers to the dextrinoid reaction of the hyphal trama with Melzer's reagent; the specific epithet "aquaticus" alludes to the watery texture of fresh fruit bodies.
> "
> Dextrinoporus" occupies an isolated phylogenetic position in the "core polyporoid clade" (a phylogenetic grouping roughly equivalent to the Polyporaceae), related to the clade containing the crust fungi "Lopharia cinerascens" and "Dentocorticium sulphurellum".
> "
> Dextrinoporus" fruit bodies are shelf-like and broadly attached to the substrate, measuring up to broad, wide and thick at the base.
> The dimensions of the watery fresh specimens decrease substantially upon drying, becoming up to one-third of the original size.

As you can see, it separates the quotation marks and puts on of a pair on a separate line. That is, of course, not correct. Expected output:

> The generic name refers to the dextrinoid reaction of the hyphal trama with Melzer's reagent; the specific epithet "aquaticus" alludes to the watery texture of fresh fruit bodies.
> "Dextrinoporus" occupies an isolated phylogenetic position in the "core polyporoid clade" (a phylogenetic grouping roughly equivalent to the Polyporaceae), related to the clade containing the crust fungi "Lopharia cinerascens" and "Dentocorticium sulphurellum".
> "Dextrinoporus" fruit bodies are shelf-like and broadly attached to the substrate, measuring up to broad, wide and thick at the base.
> The dimensions of the watery fresh specimens decrease substantially upon drying, becoming up to one-third of the original size.

I am aware that this is based on a statistical model, but it seems too big an error to just let lie around. Can anything be done about this? In the meanwhile I will try to develop a rule that combats this.

## How to reproduce the behaviour
You can run the following code [online](https://spacy.io/usage/linguistic-features#sbd) at the sentence boundary detection documentation.

```
import spacy

nlp = spacy.load("en_core_web_sm")
texts = 'The generic name refers to the dextrinoid reaction of the hyphal trama with Melzer\'s reagent; the specific epithet "aquaticus" alludes to the watery texture of fresh fruit bodies. "Dextrinoporus" occupies an isolated phylogenetic position in the "core polyporoid clade" (a phylogenetic grouping roughly equivalent to the Polyporaceae), related to the clade containing the crust fungi "Lopharia cinerascens" and "Dentocorticium sulphurellum". "Dextrinoporus" fruit bodies are shelf-like and broadly attached to the substrate, measuring up to broad, wide and thick at the base. The dimensions of the watery fresh specimens decrease substantially upon drying, becoming up to one-third of the original size.'

doc = nlp(texts)
for sent in doc.sents:
    print(sent.text)
```

**Comment by BramVanroy** [comment]
For now I have edited a method to the pipeline that prevents SBD on tokens that are between quotation marks `"` or between brackets. This seems to work well for my purposes, but it is important to realise that this will keep multiple sentences in a single citation together as one sentence, e.g.

> Wilson said of the "Times"' owner, the Journal Register Company, "They don't care about the product. They don't care about the customer. They don't care about the employees. And they don't know anything about the business."

Is one 'sentence'.

```python
import spacy

def prevent_sbd(doc):
    """ Ensure that SBD does not run on tokens inside quotation marks and brackets. """
    quote_open = False
    bracket_open = False
    can_sbd = True
    for token in doc:
        # Don't do sbd on these tokens
        if not can_sbd:
            token.is_sent_start = False

        # Not using .is_quote so that we don't mix-and-match different kinds of quotes (e.g. ' and ")
        # Especially useful since quotes don't seem to work well with .is_left_punct or .is_right_punct
        if token.text == '"':
            quote_open = False if quote_open else True
        elif token.is_bracket and token.is_left_punct:
            bracket_open = True
        elif token.is_bracket and token.is_right_punct:
            bracket_open = False

        can_sbd = not (quote_open or bracket_open)

    return doc

if __name__ == '__main__':
    text = ['He said "I do not like you" and that was that. "But wait", he said. (I laughed on the inside.) "How are you?" And he left.']

    nlp = spacy.load('en_core_web_sm', disable=['ner', 'textcat'])
    # Comment out the following line to see the difference.
    nlp.add_pipe(prevent_sbd, name='prevent-sbd', before='parser')

    docs = list(nlp.pipe(text))
    sents = [sent.text for doc in docs for sent in doc.sents]

    for i, s in enumerate(sents, 1):
        print(i, s)
```

**Comment by xwiz** [comment]
Interesting problem and solution. I think you should open a pull request

**Comment by BramVanroy** [comment]
If that is what @ines and @honnibal want, I'm happy to do so. But I don't think we'd want to start adding parts to the default pipe just to fix some strange model behavior. I would think a better approach should be possible even though I'm not sure which one that is.

**Comment by xwiz** [comment]
The DL approach will likely be to use LSTM to learn/predict segmentation markers. Here's an example with Tensorflow I think. It can probably be an extension to replace Spacy segmentation but it may be overkill. https://github.com/bedapudi6788/deepsegment/blob/master/deepsegment/deepsegment.py

**Comment by BramVanroy** [comment]
Isn't that how spaCy 2.x's segmentation works in the first place? An RNN model that predicts segmentation markers?

**Comment by honnibal** [comment]
This should now be improved in the v2.2 models, as they've been trained with some random replacement of quotation characters with unicode quotes. If the problem's still around, the best place to report it is in the model predictions master thread.
