### ISSUE TITLE
incredibly slow multiprocessing with joblib, pandas and loaded Spacy LG model

### ISSUE THREAD

**Issue by randomgambit** [explosion/spaCy#3556]
## Info about spaCy

* **spaCy version:** 2.1.3
* **Platform:** Windows-10
* **Python version:** 3.7.1
* **CPU** XEON E5-2687W v3 (10 cores)

Hello there, I am struggling to get `spacy` to work with `joblib` when an external model is loaded even with a tiny dataframe. 

Here is a very simple (and fully working example).

### no multiprocessing: the whole parsing takes less than 20 seconds

```
import pandas as pd
import numpy as np
import spacy
import re
from joblib import Parallel, delayed
import time

mydf = pd.DataFrame({'mytext' : ['the cat eats the chocolate mouse',
                                     'the cat eats the chocolate mouse',
                                     'the cat eats the chocolate mouse']})
    
mydf = pd.concat([mydf] * 1000, ignore_index = True)
    
    
def myfunc(dataframe):

    #loading model
    
    print('loading model')
    nlp = spacy.load('C:\\\\Users\john\\Documents\\en_core_web_lg-2.1.0\\en_core_web_lg\\en_core_web_lg-2.1.0')

    mytokens = []
      
    print('start processing')
    for parsed_doc in nlp.pipe(iter(dataframe.mytext), batch_size=2000):
          if parsed_doc.is_parsed:
              mytokens.append([re.sub(' ' , '-',tok.text) for tok in parsed_doc.noun_chunks]) 
          else:
              mytokens.append(None)
    
    dataframe['noun_chunks'] = mytokens
        
    print('collapse noun chunks')
    dataframe['noun_chunks'] = dataframe.noun_chunks.apply(lambda x: ' '.join(map(str, x)))

    print(dataframe.head(2))
    return dataframe


t0 = time.time()   
myfunc(mydf)
print (time.time() - t0)
```
which gives
```
loading model
start processing
collapse noun chunks
                             mytext                  noun_chunks
0  the cat eats the chocolate mouse  the-cat the-chocolate-mouse
1  the cat eats the chocolate mouse  the-cat the-chocolate-mouse
14.932860136032104
```

###  multiprocessing with `joblib`: takes forever and never ends

```
import pandas as pd
import numpy as np
import spacy
import re
from joblib import Parallel, delayed
import time

def myfunc(dataframe):

    #loading model
    
    print('loading model')
    nlp = spacy.load('C:\\\\Users\john\\Documents\\en_core_web_lg-2.1.0\\en_core_web_lg\\en_core_web_lg-2.1.0')

    mytokens = []
      
    print('start processing')
    for parsed_doc in nlp.pipe(iter(dataframe.mytext), batch_size=2000):
          if parsed_doc.is_parsed:
              mytokens.append([re.sub(' ' , '-',tok.text) for tok in parsed_doc.noun_chunks]) 
          else:
              mytokens.append(None)
    
    dataframe['noun_chunks'] = mytokens
        
    print('collapse noun chunks')
    dataframe['noun_chunks'] = dataframe.noun_chunks.apply(lambda x: ' '.join(map(str, x)))

    print(dataframe.head(2))
    return dataframe

def chunker(seq, size):
    return (seq[pos:pos + size] for pos in range(0, len(seq), size))

if __name__ == '__main__':
         
    mydf = pd.DataFrame({'mytext' : ['the cat eats the chocolate mouse',
                                     'the cat eats the chocolate mouse',
                                     'the cat eats the chocolate mouse']})
    
    mydf = pd.concat([mydf] * 1000, ignore_index = True)
    
     
    t0 = time.time()   
    mylist = Parallel(n_jobs=8,  verbose=200, backend = 'multiprocessing', prefer="processes")(delayed(myfunc)(chunk) for chunk in chunker(mydf, 100))
    mydata = pd.concat(mylist)
    print (time.time() - t0)
     
```

Do you know what is the issue here? How can I run this in parallel efficiently? My real dataset has millions of observations.

Thanks!!

**Comment by honnibal** [comment]
You can find an example of using spaCy with multiprocessing here: https://github.com/explosion/spaCy/blob/master/examples/pipeline/multi_processing.py

The main problem is that you're processing the documents in batches that are far too small. spaCy should be running at around 8-10k words per second, but the lg model takes about 20 seconds to load. That means if you need to do around 150k words per loading of the model just to break even. If you process fewer words than that, you'd be better off just using one process.

Try figuring out how long the model takes to load on your machine, and then see how many documents you can process in about 10 times that length. Then if you set that as your batch size, you'll get 10% overhead, 90% work. You could set it to 20 times the load-length to get the overhead down to 5%.

**Comment by randomgambit** [comment]
@honnibal very interesting. thanks! I am trying right now and will report what I find. It seems to me that what really matters in the `chunksize` at the `Parellel()` level (here = 100 as I split the dataframe in chunks of 100 rows). That is, the `batch_size` argument of `nlp` is almost irrelevant because the model is loaded once per process. Am I correct here?

Thanks!

**Comment by randomgambit** [comment]
@honnibal I tried with a larger chunk size... and it seems to still take forever. Can you run my little example on your computer?

**Comment by randomgambit** [comment]
I let the program run the whole night. I didnt finish. There is something wrong with the `joblib` code here...

**Comment by randomgambit** [comment]
@honnibal posted the question on SO. I think it is of interest of many people trying to parallelize your magic `spacy` package. Thanks!! https://stackoverflow.com/questions/55593143/how-to-parallelize-spacy-using-pandas-joblib-and-a-custom-model

**Comment by randomgambit** [comment]
using linux solved it. never use windows for multiprocessing...
