### ISSUE TITLE
Loss of entity name

### ISSUE THREAD

**Issue by arunchaitanya24** [explosion/spaCy#3560]
## How to reproduce the behaviour

```python
import spacy
from spacy import displacy
from collections import Counter
import en_core_web_sm
nlp = en_core_web_sm.load()
doc = nlp('Ousted Nissan Motor Co boss Carlos Ghosn on Wednesday said on Twitter that he was getting ready to tell the truth about recent events and that he would hold a news conference on April 11.')
print(([(X, X.ent_type_) for X in doc]))
displacy.render(nlp(str(doc)), jupyter=True, style='ent')
displacy.render(nlp(str(doc)), style='dep', jupyter = True, options = {'distance': 120})
```
## output

```
[(Ousted, ''), (Nissan, ''), (Motor, ''), (Co, ''), (boss, ''), (Carlos, 'PERSON'), (Ghosn, 'PERSON'), (on, ''), (Wednesday, 'DATE'), (said, ''), (on, ''), (Twitter, ''), (that, ''), (he, ''), (was, ''), (getting, ''), (ready, ''), (to, ''), (tell, ''), (the, ''), (truth, ''), (about, ''), (recent, ''), (events, ''), (and, ''), (that, ''), (he, ''), (would, ''), (hold, ''), (a, ''), (news, ''), (conference, ''), (on, ''), (April, 'DATE'), (11, 'DATE'), (., '')]
```

## Your Environment

* Operating System: macOS Mojave
* Python Version Used: 3.7
* spaCy Version Used: 2.1.3  
* Environment Information: en_core_web_sm, Anaconda

**Comment by ines** [comment]
Could you explain the problem you're reporting? Do you mean that the entity "Nissan Motor Co" isn't recognised as an `ORG` or that "Twitter" isn't recognised as a `PRODUCT`? 

The process of recognising named entities is **statistical** – so the English model has no deeper knowledge of what a "product" is, or how an "organization" is defined. It only *predicts* what label is most likely in this context and which span to apply it to, based on the data the model was trained on. So it's totally possible that the model makes mistakes – in fact, even if you train a super good state-of-the-art model that's 90% accurate on your data, every 10th prediction it makes will be wrong.

It's also important to keep in mind that the pre-trained models distributed with the library are baseline models that were tuned for the best possible compromise of speed, size, and accuracy. You **almost always** want to adjust the model to your specific domain if extracting named entities is important to you. You can find more details on this in the [documentation on training and updating models](https://spacy.io/usage/training). You might also want to augment your model with rules and names that you know are *always* a certain entity, e.g. using the new [`EntityRuler`](https://spacy.io/usage/rule-based-matching#entity-ruler).

**Comment by arunchaitanya24** [comment]
Thanks for the update.

Yes,  "Nissan Motor Co" isn't recognised as an ORG and "Twitter" isn't recognised as a PRODUCT.

I am trying to understand the how `spaCy` NER works as part of my college thesis. We are working on news articles to extract entity names and products. 

As you mentioned will try to train the model with our data set to get the desired results.

**Comment by ines** [comment]
@arunchaitanya24 You might also find this video helpful then: https://www.youtube.com/watch?v=sqDHBH9IjRU
