### ISSUE TITLE
Accessing the depencency parsing scores

### ISSUE THREAD

**Issue by cbobed** [explosion/spaCy#3561]
According to the documentation, *predict* method of the DependencyParser should return a list of (score, tensor) tuples with the scores of each dependency  in each document. However, it returns a StateClass instance instead. 

## How to reproduce the behaviour
nlp = spacy.load("en")
parser = nlp.get_pipe('parser')
scores = parser.predict(doc)

## Your Environment

* Operating System: win 10
* Python Version Used: 3.7.3
* spaCy Version Used: 2.1.3

**Comment by honnibal** [comment]
The docs are wrong on this, and should be updated, thanks.

It's not so easy to get the scores of each dependency, as that's not quite how the model works. We use a greedy transition-based model, where as each word, we predict a distribution over actions that can push or pop words to a stack, add arcs, and introduce sentence breaks. This means we don't have predict a distribution over heads or labels for each token.

There's a hacky way to get something like a probability distribution, by running the model with beam search. It doesn't produce such well-calibrated estimates, but it might work for your application. The relevant method is `.beam_parse`. If you have a look for examples of this (mostly in the context of the entity recognizer), you should be able to see how to get the set of parses produced, from which you can calculate probabilities. There are some further examples on the Prodigy forum: https://support.prodi.gy
