### ISSUE TITLE
Multitask objective

### ISSUE THREAD

**Issue by damianoporta** [explosion/spaCy#3563]
Hello
I am running this example: https://github.com/explosion/spaCy/blob/master/examples/training/ner_multitask_objective.py
It works good and looks very interesting.
I have a doubt regarding the concept behind its work. I read in the prodigy forum that i should not add such custom features during the testing. Could anyone explain the reason of using those features on training only? Thanks

## Your Environment
spaCy version      2.0.18         
Platform           Linux-4.15.0-47-generic-x86_64-with-Ubuntu-18.04-bionic
Python version     3.6.7

**Comment by honnibal** [comment]
The multi-task objective only makes sense to add during training. It teaches the model to predict a second objective. This can't do anything at test time, as no updates can be made.
