### ISSUE TITLE
Experimental spaCy language model for Indonesian

### ISSUE THREAD

**Issue by jeannefukumaru** [explosion/spaCy#3566]
## Feature description
I've built an experimental spaCy language model for Indonesian using the Universal Dependencies dataset and packaged it into an installable `pip` package. Full details of the training process and results can be found from this repo: https://github.com/jeannefukumaru/id_dep_ud_sm.git

I've named the files and structured the repo in a format similar to how the Norwegian experimental model was packaged. Referenced from this discussion:
https://github.com/explosion/spaCy/issues/3082

Let me know what changes or tweaks you would like to include. I've added some suggestions for contributions so other spaCy users / Indonesian native speakers can get involved too. 

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
If so, we will tag it as [`project idea`](https://github.com/explosion/spaCy/labels/project%20idea) so other users can take it on.
Yes

**Comment by YukaLangbuana** [comment]
What's the progress on this? I'd love to contribute. I want to know the current issue and improvements needed.

**Comment by ines** [comment]
Merging this with #3056!
