### ISSUE TITLE
LEMMA in pattern matcher not working as expected

### ISSUE THREAD

**Issue by Zhenshan-Jin** [explosion/spaCy#3572]
## How to reproduce the behaviour

```
import spacy
from spacy.matcher import Matcher
nlp = spacy.load("en_core_web_sm")

matcher = Matcher(nlp.vocab)
pattern = [{"LEMMA": "bike"}]
matcher.add("BasinTest", None, pattern)

doc = nlp("The Bike is a great tools")
matches = matcher(doc)
for match_id, start, end in matches:
    string_id = nlp.vocab.strings[match_id]  # Get string representation
    span = doc[start:end]  # The matched span
    print(match_id, string_id, start, end, span.text)
```
In the code above the LEMMA matching is not working, which means `Bike` is not matched. Then I look in to the lemma of each of the token in the sentence,
```
[t.lemma_ for t in doc]
```
the output is `['the', 'Bike', 'be', 'a', 'great', 'tool']`, which is wired. Seems like spacy is not alwasy lower case the words during lemmatization.

The above result is getting from en_core_web_sm.2.1.0; I tested the above code on 2.0.0, which works fine

## Your Environment

* Operating System:
* Python Version Used:3.6
* spaCy Version Used:2.1.3
* Environment Information:

**Comment by ines** [comment]
Merging this with #3551!
