### ISSUE TITLE
Loading model from directory doesn't work

### ISSUE THREAD

**Issue by christian-vorhemus** [explosion/spaCy#3578]
## How to reproduce the behaviour
I want to load a package from a directory path via spacy.load() function as described [here](https://spacy.io/usage/models#usage). However, spacy complains:

`Can't find model 'C:\Users\[...]\functions_classification\en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory`

I tried relative and absolute paths.

The content of en_core_web_sm is
```
en_core_web_sm-2.1.0
__init__.py
meta.json
__pycache__
```
For several reasons, I don't want to download the package with `python -m spacy download en_core_web_sm` but use a directory path.

## Your Environment

* Operating System: Windows 10.0.17763.437
* Python Version Used: 3.6
* spaCy Version Used: 2.1.3

**Comment by ines** [comment]
I think the problem here is that you're trying to load the top-level Python package instead of the model data directory. What happens if you load `en_core_web_sm/en_core_web_sm-2.1.0`?

Also see here for details on the directory structure: https://spacy.io/usage/models#download-manual

**Comment by christian-vorhemus** [comment]
Same behavior:

```
path = os.path.abspath('./en_core_web_sm/en_core_web_sm-2.1.0')
nlp = spacy.load(path)
```
leads to

`Can't find model 'C:\[...]\functions_classification\en_core_web_sm\en_core_web_sm-2.1.0'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory`

**Comment by ines** [comment]
And the relative path (and resulting absolute path) definitely exists?

Here's the logic that gets called when you load a model and that eventually raises the error you're seeing. So by the time the `IOError` is raised, all other checks must have failed for some reason:

https://github.com/explosion/spaCy/blob/531c0869b2535eacb47b07b649fe1710233ce001/spacy/util.py#L117-L136

**Comment by christian-vorhemus** [comment]
Thanks for the hint @ines, now In understand what's going on: I'm running spacy in an Azure Python Function and the path could not be resolved correctly. It works with

```
path = pathlib.Path(__file__).parent / 'en_core_web_sm/en_core_web_sm-2.1.0'
nlp = spacy.load(path)
```

So, not an issue with spacy, I'll close this.
