### ISSUE TITLE
Retokenizer and custom pipeline components

### ISSUE THREAD

**Issue by thomwolf** [explosion/spaCy#3579]
Some pipeline components (like NeuralCoref) may store `Span`s as results of their processes.
When a `Doc` is retokenized, these `Span`s may not be pointing to the right tokens anymore.

Here is a simple example using `NeuralCoref` (from https://github.com/huggingface/neuralcoref/issues/110):
```python
import spacy
import neuralcoref
nlp = spacy.load('en_coref_sm')
neuralcoref.add_to_pipe(nlp)

text = nlp("Michelle Obama is the wife of former U.S. President Barack Obama. Prior to her role as first lady, she was a lawyer.")

spans = list(text.noun_chunks)
with text.retokenize() as retokenizer:
    for span in spans:
        retokenizer.merge(span)

for word in text:
    print(word)
    if(word._.in_coref):
        print(text._.coref_clusters)
```

This throws an error (`IndexError: [E037] Error calculating span: Can't find a token ending at character offset 78`).

The simplest fix is to re-run the specific pipeline component once the tokens have been merged.

I'm just opening this issue to discuss whether there could be a (simple) way to have a more automated solution (I don't have anything specific in mind though).

**Comment by honnibal** [comment]
Hmm. The spans should actually be robust to changes in tokenization, but only if there are actually tokens to point to. If after merging a span would end in the middle of a token, you get the error above.

The question is how you should resolve this inconsistency. If the tokenization invalidates the span, should the span simply be discarded? Or should it be adjusted to meet the new boundary? Or should something else happen?
