### ISSUE TITLE
Add a parameter for saving only the n latest epochs while using CLI Training

### ISSUE THREAD

**Issue by Bharat123rox** [explosion/spaCy#3584]
## Feature description

Enable saving models of the `n_latest` epochs alone to disk (say `n_latest=5`, save only the last 5 epochs to disk) in spacy train cli [here](https://spacy.io/api/cli#train).
This would ideally be a parameter, `n_latest`, specified by the user, to save only that many epochs to disk at the end of training, for example:-

If `n_iter=9` and `n_latest=5`, then only model5 to model9 must be saved on disk, however to prevent losing information in the event of some crash/errors, a suggested implementation is model0 may be deleted only after model5 is saved, model1 may be deleted only after model6 is saved etc.

This will help users decide the appropriate tradeoffs for disk space vs ability to choose the "best" model.

In my case, I certainly require this feature as I'm running out of disk space.

@ines  @honnibal  I'm ok to submit a PR for this, if this feature seems ok. (Even if it is a breaking change, I feel it's essential moving forward and some steps could be taken to make it a v2.1 feature)

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
If so, we will tag it as [`project idea`](https://github.com/explosion/spaCy/labels/project%20idea) so other users can take it on.

No, since it is a parameter specific to Spacy's CLI Training

**Comment by svlandeg** [comment]
Merging with Issue #5280 which also addresses the issue of trying to save disk space by only saving a few models, and not all of them.
