### ISSUE TITLE
Is there any script to convert the ontonotes 5.0 data to jsonl format that can be used for training?

### ISSUE THREAD

**Issue by kaushik88** [explosion/spaCy#3587]

**Comment by DuyguA** [comment]
I know this repo, would it be of any help? : https://github.com/jsalt18-sentence-repl/jiant/blob/master/probing/data/README.md

**Comment by honnibal** [comment]
My conversion process was a bit ad hoc, as I took some trouble to align the WSJ portions against the original raw text. So, I don't have a single script that produces our json output, unfortunately.

**Comment by kaushik88** [comment]
I found this repo - https://github.com/yuchenlin/OntoNotes-5.0-NER-BIO which converts the ontonotes to NER format. I then used this to convert to json/jsonl format.
