### ISSUE TITLE
Incorrect POS tagging in Spacy v2.1.3

### ISSUE THREAD

**Issue by aafreenrah** [explosion/spaCy#3588]
The current version is slightly inaccurate.
**For example:**
Actual POS tag of the term "**cook**" is **VBP** (VBD - cooked). 
It has correctly captured in the older version. 
**Example:** She cook daily --> She/PRP **cook/VBP** daily/RB (v2.0.16)
**Example:** She cook daily --> She/PRP **cook/VBD** daily/RB (v2.1.3)

**Comment by ines** [comment]
Merging this with #3052. In general, there are always trade-offs – overall, I think the new models are slightly mode accurate on the given evaluation, but this can also mean that it gets different things wrong in comparison to a different, less accurate model.
