### ISSUE TITLE
Issue with iterating through extension attribute names

### ISSUE THREAD

**Issue by Eliotfrazier** [explosion/spaCy#3590]
Just a small question regarding iterating a process through multiple extension attribute names. Apologies if this is a basic one, I'm new to the library and have been very much enjoying using it. 

In short, I want to store the outputs of a set of 13 conditional random fields models I have within the spacy Doc class for each sentence. Currently, I've set_extensions with default values for all of these 13 varieties formerly in the code. However, when I iterate the prediction and storage method as shown bellow, I simply get the error message:

AttributeError: [E046] Can't retrieve unregistered extension attribute 'tag_name'. Did you forget to call the `set_extension` method?

whereby clearly the 'tag_name' is assumed to be the extension name, rather than it's corresponding value (the genuine name of the set extensions)

`    def tag_text(self, js):
        cleaned_bodd = self.get_cleaned_first_body()
        tagging_sents = sent_tokenize(cleaned_bodd)

        for sentence in tagging_sents:
            cleaned_spacy_doc = HtmltoDoc(js['body'], sentence)
            tagging_features = sent2features(cleaned_spacy_doc.Doc)

            for tag_name in tag_vars:
                tagger = models_container[tag_name]
                preds = tagger.tag(tagging_features)

                for x, y in zip(cleaned_spacy_doc.Doc, preds):
                    x._.tag_name = y`
 
The important part here is the last two for loops. I'm sure I'm overlooking a very simple workaround, but I've been playing with it for a while, and I'd rather not have to repeat code by writing this out 13 times with each tag variety named explicitly.

**Comment by Eliotfrazier** [comment]
My point really being is there an equivalent to the normal python getattr, for spacy extension attributes?

**Comment by ines** [comment]
I hope I understand your question correctly – but the `._.` property also has `set`, `get` and `has` methods:

```python
token._.has('some_extension')
value = token._.get('some_extension')
token._.set('some_extension', new_value)
```

Those should probably be documented better – it seems like this part in the docs got rewritten and lost in the recent update 🤔

**Comment by Eliotfrazier** [comment]
Exactly what I was looking for, many thanks :)
