### ISSUE TITLE
Reducing vocabulary size

### ISSUE THREAD

**Issue by lcswillems** [explosion/spaCy#3593]
## Feature description
I downloaded the `en_core_web_md` model and it has 1,000,000+ words in the vocabulary. Is it possible to only keep the 30,000 most frequent words (for example) in the vocabulary?

**Comment by ines** [comment]
Sorry for only getting to this now!

The easiest way to reduce the vocab size would be to create a new `Vocab` object and only keep the entries that you want. You can use the `Lexeme.prob` attribute to sort the entries. You can then overwrite the `nlp.vocab` – just make sure to save the `nlp` object to disk and load it back to make sure that all pipeline components are reinitialised with the new vocab.

One important thing to note, though: If you remove an entry from the vocabulary, you're also removing its word vector. The word vectors were used during training, so removing them can potentially cause the model to perform worse.

**Comment by lcswillems** [comment]
Thank you for your answer. But, I was more asking "Is there a native way to do it in Spacy ?" And if no, I was proposing a "feature request".
