### ISSUE TITLE
Spanish POS-tagging tags years as NOUN instead of NUM

### ISSUE THREAD

**Issue by mariabg** [explosion/spaCy#3595]
## Description
Spanish POS-tagging tags years as NOUNs, since they follow [a particular grammar format](https://www.9h05.com/wa_files/STYLE_20GUIDELINES_20FOR_20GOOGLE_20TRANSLATIONS.pdf#page=34), not [the general one](https://www.9h05.com/wa_files/STYLE_20GUIDELINES_20FOR_20GOOGLE_20TRANSLATIONS.pdf#page=33). Normally, numbers larger than 999 have a dot in between every three digits (i.e. 1.000 or 33.000.000), but this does not apply for dates ("año 2019"). In the current version of SpaCy only the numbers following the general rule are tagged as numbers.

I'd like to add as well that the correct punctuation for digits it's not very common in informal contexts (outside publishing houses or newsrooms), so as a personal opinion I suggest that every digit gets tagged as NUM (as I believe that is implemented in English), and not only when spelled correctly.

## My Environment
* Operating System: macOS Mojave (v. 10.14.2)
* Python Version Used: Python 3.6.4 (Anaconda)
* spaCy Version Used: 2.1.3

**Comment by ines** [comment]
Adding this to #3052!

**Comment by mariabg** [comment]
Cool, let me know if it can be a good first contribution to the project! :D
