### ISSUE TITLE
Encoding is breaking when using spacy convert

### ISSUE THREAD

**Issue by theudas** [explosion/spaCy#3596]
## How to reproduce the behaviour
When converting a jsonl file with "umlauten" with:
python -m spacy convert test.jsonl converted --lang de -t json

to train the NER the converted file loses all Umlaute, it seems like there is a json conversion without ensure_ascii=False, except you are using your own json implementation.

expected: großes 
got: gro\u00dfes

## Your Environment
* **spaCy version:** 2.1.3
* **Platform:** Windows-10-10.0.17763-SP0
* **Python version:** 3.6.4
* **Models:** de

**Comment by honnibal** [comment]
That's just the encoded representation. It should be coming back out fine:

```python
>>> print(u"gro\u00dfes")
großes
```
