### ISSUE TITLE
Universal Dependencies model

### ISSUE THREAD

**Issue by AvivWn** [explosion/spaCy#3597]
I using the dependency parsing of Spacy.
I am also using the model en_core_web_sm.

I wonder if the labels that resulted from this model are Universal Dependencies or not.
If not, do you have any trained Universal Dependencies model in Spacy?

**Comment by ines** [comment]
The English models were trained on the OntoNotes 5 corpus. You can find more details on the sources here: https://spacy.io/models/en The other models were mostly trained on Universal Dependencies.

We don't have a UD model for English, but the `spacy convert` and `spacy train` commands let you train your own. You just need to make sure the tags in the `tag_map` match the part-of-speech tags used in the treebank.
