### ISSUE TITLE
Cannot force displacy.render to return html when in IPython/Spyder

### ISSUE THREAD

**Issue by fizban99** [explosion/spaCy#3598]
I am using Spyder, which uses IPython by default, with the limitation that it is not able to render HTML inline. Instead it just displays `<IPython.core.display.HTML object>` on the console.

When using `displacy.render` and even when passing `jupyter=False`, I just get the above message and I cannot capture the html markup and use it offline.

[Looking at the code ](https://github.com/explosion/spaCy/blob/master/spacy/displacy/__init__.py)it seems that the render function overrides the value of the parameter if it runs on IPython:
` if jupyter or is_in_jupyter():  # return HTML rendered by IPython display()`

Which means that the example code to generate svg at
https://spacy.io/usage/visualizers?#jupyter does not work for me as `svg `is set to `None` and 
I get `TypeError: write() argument must be str, not None`
```
import spacy
from spacy import displacy
from pathlib import Path


nlp = spacy.load("en_core_web_sm")
sentences = [u"This is an example.", u"This is another one."]
for sent in sentences:
    doc = nlp(sent)
    svg = displacy.render(doc, style="dep")
    file_name = '-'.join([w.text for w in doc if not w.is_punct]) + ".svg"
    output_path = Path("/images/" + file_name)
    output_path.open("w", encoding="utf-8").write(svg)
```

* **spaCy version:** 2.1.3
* **Platform:** Windows-10-10.0.16299-SP0
* **Python version:** 3.7.1

**Comment by theudas** [comment]
Try: displacy.render(doc, style="dep", jupyter=True)

**Comment by MinLiiiii** [comment]
me too. Have you solved this problem ?

**Comment by ines** [comment]
Thanks for the report and analysis, this makes sense!

We should probably set `jupyter=None` by default, and then check something like:

```python
if jupyter or jupyter is None and is_in_jupyter():
```

If you want to test this and submit a PR, that'd be great. Otherwise, I can also take care of this in the next round of bugfixing.
