### ISSUE TITLE
Handling address in parsing.

### ISSUE THREAD

**Issue by hifall** [explosion/spaCy#3602]
When I ran spaCy through some text with an address, the address was not recognized as a single entity. Instead, it was split into multiple parts, without a coherent connection between them.

## How to reproduce the behaviour
Run this code:
```
import spacy
from spacy import displacy

nlp = spacy.load("en_core_web_sm")
doc = nlp(u"Microsoft is located in 3000 MS way, Redmond WA 98052.")
# Since this is an interactive Jupyter environment, we can use displacy.render here
displacy.render(doc, style='dep')
```

## Your Environment

* Operating System:
* Python Version Used: 3
* spaCy Version Used:  2.1.3
* Environment Information:

I ran the code in the sandbox on the official spaCy page: https://spacy.io/usage/linguistic-features. Kindly go there using the sandbox under "Visualizing dependencies", and run the code above to reproduce the issue.

I expect the whole address to be under a single node in the parse tree, with subnodes representing constituent parts of the address, like number, street, city, state, country, etc.

**Comment by honnibal** [comment]
The parser uses a statistical model, and doesn't always produce the desired parse. You can annotate more data to try to improve the accuracy, or use matcher rules to extract the span boundary, and consider merging the token together before or after parsing.
