### ISSUE TITLE
Moving lemmatization lookup outside the library/lazy loading from json file

### ISSUE THREAD

**Issue by cstruct** [explosion/spaCy#3603]
## Feature description
As of Spacy version 2.1.3 the lemmatization lookup tables are 184MB of 229MB disk space used by an installation. I propose that all this data is moved outside the library and downloaded on demand or at least moved to a json file and lazy loaded.

Having these large lookup tables causes multiple issues:
- 184MB of disk space used for a feature that might not even be used in Docker images causes a lot of bloat
- Python debugger takes a long time to handle a import of a Spacy lang with a large lookup table
- Anything doing static code analysis will be very slow building an AST for the files containing the lookup tables

| Size | File                        |
|------|-----------------------------|
|0     | tl/lemmatizer.py            |
|4.0K  | bn/lemmatizer.py            |
|4.0K  | el/lemmatizer/lemmatizer.py |
|8.0K  | fr/lemmatizer/lemmatizer.py |
|8.0K  | ru/lemmatizer.py            |
|8.0K  | uk/lemmatizer.py            |
|48K   | nb/lemmatizer/lookup.py     |
|900K  | ur/lemmatizer.py            |
|1020K | id/lemmatizer.py            |
|1.2M  | en/lemmatizer/lookup.py     |
|1.2M  | hu/lemmatizer.py            |
|6.5M  | fr/lemmatizer/lookup.py     |
|9.4M  | ro/lemmatizer.py            |
|11M   | it/lemmatizer.py            |
|12M   | de/lemmatizer.py            |
|15M   | es/lemmatizer.py            |
|18M   | ca/lemmatizer.py            |
|22M   | sv/lemmatizer/lookup.py     |
|24M   | da/lemmatizer.py            |
|25M   | pt/lemmatizer.py            |
|40M   | tr/lemmatizer.py            |
|184M  | total                       |

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
No

**Comment by ines** [comment]
Thanks for the proposal and putting together the stats – this is definitely on our radar, we just need to come up with the best way to do this. I'll merge this thread with #3258 🙂
