### ISSUE TITLE
Tokenizer is slower in 2.1.3 relative to 2.0.16

### ISSUE THREAD

**Issue by jorjacman** [explosion/spaCy#3606]
## How to reproduce the behaviour

Also, appears that nlp.pipe does not improve performance - at least w/ the example texts. 

![image](https://user-images.githubusercontent.com/8989875/56294686-79e9cf00-60f9-11e9-8f62-d32a6864caf8.png)

## Your Environment
* **spaCy version:** 2.1.3 (and 2.0.16)
* **Platform:** Darwin-17.7.0-x86_64-i386-64bit
* **Python version:** 3.6.5
* **Models:** en_core_web_sm, en_vectors_web_lg, en

**Comment by honnibal** [comment]
The pipe method isn't faster for the tokenizer, as we don't currently implement multi-processing for that. The batching only becomes relevant for the statistical models.

As for the comparison between v2.0.16 and v2.1.3: On the benchmarks we've conducted, the v2.1 tokenizer is indeed faster. Care needs to be taken to always run benchmarks under realistic workloads. The tokenizer includes caching, so running it on repeated strings doesn't exercise it properly. If you do find a realistic workload where the v2.0 tokenizer performs better, please open a new issue.
