### ISSUE TITLE
Different dependency after reinstallation

### ISSUE THREAD

**Issue by vivi91** [explosion/spaCy#3609]
I had to reinstall anaconda and spacy because of other problems. After the reinstallation I got different dependencies than before. Any ideas why? I used the same language model as before.

Before reinstallation:
nach ADP mnr
Altbatterien NOUN nk
von ADP op
nach ADP mo
Absatz NOUN cj
Geräte- X nk
Altbatterien NOUN nk

After reinstallation:
nach ADP mo
Altbatterien NOUN oa
von ADP mnr
nach ADP mnr
Absatz NOUN mo
Geräte- X ag
Altbatterien PROPN cj

```
import spacy
nlp = spacy.load('de_core_news_sm')

doc3 = nlp("Die Hersteller sind verpflichtet, die von den Vertreibern nach § 9 Absatz 1 Satz 1 zurückgenommenen Altbatterien und die von öffentlich-rechtlichen Entsorgungsträgern nach § 13 Absatz 1 erfassten Geräte- Altbatterien unentgeltlich zurückzunehmen und nach § 14 zu verwerten.")

for word in doc3:
    print (word.text, word.pos_, word.dep_)
```

## Your Environment
* Operating System: Windows 10 Education
* Python Version Used: 3.7.0

**Comment by ines** [comment]
Which spaCy version are you using currently, and which version were you using before? Is it possible that you were previously running spaCy 2.0 and after reinstallation, downloaded the latest version, v2.1 and the new models? 

Minor spaCy version updates usually means that there are also new models – and their predictions can sometimes differ between versions. The new models should be slightly more accurate overall, but that ususally also means that they'll just make different mistakes.

**Comment by vivi91** [comment]
I am using Version 2.1.3 right now. The last time I installed spaCy in December. So it must have been 2.0. Thank you very much.
