### ISSUE TITLE
Website IPv6 support

### ISSUE THREAD

**Issue by tambry** [explosion/spaCy#3615]
[The website](https://spacy.io/) lacks IPv6 support.

Instructions for enabling IPv6 are in [Netlify's IPv6 support announcement](https://www.netlify.com/blog/2018/11/26/announcing-ipv6-support-on-the-netlify-application-delivery-network/#are-we-there-yet).

**Comment by ines** [comment]
Ah, that was easy. Just enabled IPv6 for spacy.io and will close this as soon as I can confirm it's live.

**Comment by tambry** [comment]
Working now. Thanks!
