### ISSUE TITLE
regex not working with spaces?

### ISSUE THREAD

**Issue by simonm3** [explosion/spaCy#3617]
The entity ruler regex option does not seem to work with spaces. For example code below works showing regex working. However if I replace the _ with a space it does not find any entities.

he was president of the united_states POST in the United_Ssssstates POST

```
nlp = spacy.load('en_core_web_sm')
ruler = EntityRuler(nlp)
pattern = [{"TEXT": {"REGEX": "[Uu]nited_[Ss]*tates"}}]
ruler.add_patterns([dict(label="POST", pattern=pattern)])
nlp.add_pipe(ruler)
doc = nlp("he was president of the united_states in the United_Ssssstates")
displacy.render(doc, style="ent")
```

Also the the example regex could be clearer:
- It looks like the entity has to be both president and united states. I may be misinterpreting but it is not clear what it is trying to do.
- There is an unmatched bracket in it
- It won't work anyway due to the space issue above

**Comment by simonm3** [comment]
OK this is not actually a bug but misinterpretation as did not realise the patterns are a list of tokens excluding spaces. However the documentation examples make the same mistake and need correcting.

This example needs to split the united and states; and has mismatched brackets:

pattern = [{"TEXT": {"REGEX": "^([Uu](\.?|nited) ?[Ss](\.?|tates)"}},
           {"LOWER": "president"}]

This example looks like it works but if you change the label to TEST1 then you can see it does not. The pattern has to split the two words

`patterns = [{"label": "ORG", "pattern": "MyCorp Inc."}]`

**Comment by simonm3** [comment]
Some related issues with regex documentation and behaviour.

1) If start/end word boundaries are not used then spacy regex returns extra characters at the start/end; whereas python re returns the word.

`re.findall("united", "123united")` ==> "united"

`pattern = [{"LOWER": {"REGEX": "united"}}` applied to 123united ==> "123united". 

2. The examples in the docs should have not just words separated but also each word needs start and end boundaries e.g.

`pattern = [{"LOWER": {"REGEX": "^united\\b"}}, {"LOWER": {"REGEX": "^states\\b"}}]`

3. If say middle token is regex "(word)?" then it finds any word e.g. "United bla States". It works with the OP="?" operator but would be neater if were possible to use standard regex with spaces and ? on a group of tokens. As a workaround I use standard regex on multi-word phrases before tokenisation and convert spaces to _.

**Comment by ines** [comment]
Sorry for only replying to this now – we recently added some more examples to the regular expression matching section (including best practices for matching on the `doc.text` directly). This should address the problems discussed here 🙂 https://spacy.io/usage/rule-based-matching#regex
