### ISSUE TITLE
problem installing spyCy

### ISSUE THREAD

**Issue by dtsonov** [explosion/spaCy#3619]
Hi there, 
I have problem installing spaCy.

I use python 3.7.3 installed with Anaconda package.
Windows 10 Pro.

When I run:
pip install spacy 
or
pip install -U spacy

I always get:

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/spacy/
Could not fetch URL https://pypi.org/simple/spacy/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/spacy/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
Requirement already up-to-date: spacy in c:\users\dtsonov\appdata\local\continuum\anaconda3\lib\site-packages (2.1.3)
Requirement already satisfied, skipping upgrade: numpy>=1.15.0 in c:\users\dtsonov\appdata\local\continuum\anaconda3\lib\site-packages (from spacy) (1.16.2)
Requirement already satisfied, skipping upgrade: wasabi<1.1.0,>=0.2.0 in c:\users\dtsonov\appdata\local\continuum\anaconda3\lib\site-packages (from spacy) (0.2.1)
Requirement already satisfied, skipping upgrade: requests<3.0.0,>=2.13.0 in c:\users\dtsonov\appdata\local\continuum\anaconda3\lib\site-packages (from spacy) (2.21.0)
Requirement already satisfied, skipping upgrade: thinc<7.1.0,>=7.0.2 in c:\users\dtsonov\appdata\local\continuum\anaconda3\lib\site-packages (from spacy) (7.0.4)
Requirement already satisfied, skipping upgrade: plac<1.0.0,>=0.9.6 in c:\users\dtsonov\appdata\local\continuum\anaconda3\lib\site-packages (from spacy) (0.9.6)
Requirement already satisfied, skipping upgrade: jsonschema<3.0.0,>=2.6.0 in c:\users\dtsonov\appdata\local\continuum\anaconda3\lib\site-packages (from spacy) (2.6.0)
Requirement already satisfied, skipping upgrade: cymem<2.1.0,>=2.0.2 in c:\users\dtsonov\appdata\local\continuum\anaconda3\lib\site-packages (from spacy) (2.0.2)
Requirement already satisfied, skipping upgrade: murmurhash<1.1.0,>=0.28.0 in c:\users\dtsonov\appdata\local\continuum\anaconda3\lib\site-packages (from spacy) (1.0.2)
Requirement already satisfied, skipping upgrade: preshed<2.1.0,>=2.0.1 in c:\users\dtsonov\appdata\local\continuum\anaconda3\lib\site-packages (from spacy) (2.0.1)
Requirement already satisfied, skipping upgrade: srsly<1.1.0,>=0.0.5 in c:\users\dtsonov\appdata\local\continuum\anaconda3\lib\site-packages (from spacy) (0.0.5)
Requirement already satisfied, skipping upgrade: blis<0.3.0,>=0.2.2 in c:\users\dtsonov\appdata\local\continuum\anaconda3\lib\site-packages (from spacy) (0.2.4)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\users\dtsonov\appdata\local\continuum\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2019.3.9)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in c:\users\dtsonov\appdata\local\continuum\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.0.4)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in c:\users\dtsonov\appdata\local\continuum\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (1.24.1)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in c:\users\dtsonov\appdata\local\continuum\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.8)
Requirement already satisfied, skipping upgrade: tqdm<5.0.0,>=4.10.0 in c:\users\dtsonov\appdata\local\continuum\anaconda3\lib\site-packages (from thinc<7.1.0,>=7.0.2->spacy) (4.31.1)
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

**Comment by BramVanroy** [comment]
This is not an issue with spaCy but with pip. Either pypi had some certificate issues or your python installation is missing some modules. I suggest reinstalling python.
