### ISSUE TITLE
Convert command line on .iob Conll-2003 file not working

### ISSUE THREAD

**Issue by AlexisPister** [explosion/spaCy#3620]
## How to reproduce the behaviour
Hello, I would like to convert the conll-2003 dataset from iob to json. I removed the 2 middle columns with python and my files look like this now :

```
-DOCSTART- O
 
CRICKET O
- O
LEICESTERSHIRE B-ORG
TAKE O
OVER O
AT O
TOP O
AFTER O
INNINGS O
VICTORY O
. O
```

I tried to convert them to the json format with the command line convert but I get the following message each time :
✔ Generated output file (0 documents)
json_output/valid.msg

An empty file is generated. Here is the command I used :
python -m spacy convert valid.iob json_output/ -t msg -c iob

I tried the three output format possible but it always give the same thing

## Your Environment
* Operating System: Elementary OS 5.xx
* Python Version Used: 3.7.1
* spaCy Version Used: 2.1.1

**Comment by honnibal** [comment]
Thanks, it looks like there's a bug in the spacy/cli/converters/iob2json.py file. The code really doesn't look right there --- possibly an append has ended up in the wrong block?

**Comment by AlexisPister** [comment]
I would be glad to help, but I really don't understand how the script should be working. The read_iob function is not called anywhere and I don't get what the loop in the iob2json function is doing.

**Comment by flamierd** [comment]
This has halted my exploration of spacy.io for Gate replacement.  I'm not enough of a pythonista to go through the framework and locate how and why, though I can confirm it simply writes out empty files even with something as simple as:

Borg|B-ORG
Inc|I-ORG
is|O
back|O
!|O

**Comment by ines** [comment]
@AlexisPister Damn, it looks like that's the problem, yes 🤔 I just briefly checked the history of that file and it seems like the converter possibly got messed up in a merge. So it's currently iterating over an empty list, which obviously produces another empty list.

Here's the previous state of the file: https://github.com/explosion/spaCy/blob/9a5003d5c8b03c9ae53f32d7b3fc987726cd5617/spacy/cli/converters/iob2json.py

The main thing that has changed in v2.1 is that the converters aren't opening and writing the files anymore (which created a lot of code duplication). Instead, they receive the opened file as the first argument `input_data` and no output path ([see here](https://github.com/explosion/spaCy/blob/master/spacy/cli/convert.py#L80)) and return the contents to write to the JSON file. So in theory, using the old converter and simplifying the main function to something like this should work:

```python
sentences = read_iob(input_data)
docs = merge_sentences(sentences, n_sents)
return docs
```
