### ISSUE TITLE
Review/Comparison between SpaCy and other NLP libraries

### ISSUE THREAD

**Issue by DonaldTsang** [explosion/spaCy#3621]
Goal: To find missing features in these repositories and add them to SpaCy
- [ ] https://github.com/nltk/nltk
- [ ] https://github.com/sloria/TextBlob
- [ ] https://github.com/RaRe-Technologies/gensim
- [ ] https://github.com/clips/pattern
- [ ] https://github.com/aboSamoor/polyglot

Others:
https://kleiber.me/blog/2018/02/25/top-10-python-nlp-libraries-2018/
https://nlpforhackers.io/libraries/

**Comment by BramVanroy** [comment]
I agree that documented benchmarks would be nice. Perhaps in paper format with a written out experimental setup and the results. For instance in tagging accuracy and speed, to name just one.

I don't agree that the goal of spaCy should be to preemptively fill itself with features from other libraries. If it makes sense to add it to core, and if it is needed: sure. Otherwise, create a plugin to add it to the spaCy-verse, separate from core.

The main focus should be the current implementation of spaCy and all issues reported, I think.

**Comment by DonaldTsang** [comment]
@BramVanroy in a sense, not all features are necessary well written, but the "general themes/needs" should be considered. And it does not matter if is is in a plugin or it is in SpaCy-core, as long as the compatibility is well maintained.

The benchmark idea is very useful though.

**Comment by BramVanroy** [comment]
Maybe it would help if you list the features that you think are useful and needed that are still missing. That way it's more straightforward for the developers to decide what they think should be added to spaCy.

**Comment by DonaldTsang** [comment]
@BramVanroy not just that, but it gives the community an avenue to improve the library by setting a goal. Will do once I get home

**Comment by honnibal** [comment]
Definitely want to stress that we don't need to be "one library to rule them all". The boundaries of the core library are roughly defined by what needs to be implemented into the core data structures. For instance, morphology support, coreference support and entity linking support all need to be properly integrated into the underlying data structures, so those need to be in the core library. Something like word vector learning really doesn't.

As a rule of thumb, we normally won't want anything that's a pure function. If it can be implemented as a pure function, it's hard to see how it could need integration with the core data structures.

**Comment by DonaldTsang** [comment]
@honnibal the idea is that there should be, at least, an attempt to create a SciPy-like suite that shows what packages should be used in conjunction with SpaCy with maximum compatibility.

Agreed on the "pure function" idea though.
