### ISSUE TITLE
Make Indonesian fastText vectors available for download as a `spaCy` model similar to  `en_core_vectors_lg` 

### ISSUE THREAD

**Issue by jeannefukumaru** [explosion/spaCy#3622]
## Feature description

Make Indonesian fastText vectors available for download as a `spaCy` model similar to  `en_core_vectors_lg` 

fastText currently [distributes](https://fasttext.cc/docs/en/crawl-vectors.html) word vectors trained on Wikipedia and Common Crawl for 157 languages. These vectors are made available under the MIT license. spaCy users can call on these vectors by first initializing a blank `Language` class and then loading in the vectors. 

```
from spacy.lang.id import Indonesian
nlp = Indonesian()
# load in vectors
```
I wanted get feedback on whether it would be useful to make these word vectors available for download as a spaCy model similar to `en_core_web_lg` for English. Also, is this permissible license-wise? From my reading and understanding of the MIT license, the answer seems to be yes. 

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
If so, we will tag it as [`project idea`](https://github.com/explosion/spaCy/labels/project%20idea) so other users can take it on.
Custom component 
Currently, I have the fastText Indonesian word vectors packaged as a spaCy model  after running `python -m spacy init-model`. The model is too big to upload on github but a quick workaround might be to host the model on something like Google Drive.

**Comment by BramVanroy** [comment]
If this can be done, then we might as well do this for all languages that are already supported by spaCy.

**Comment by honnibal** [comment]
The `spacy init-model` command takes an argument `--vectors` that can accept a path to one of these FastText zips. We want to avoid having packages which depend on these artifacts we can't reproduce, as once we've added support for a model artifact, we want to maintain it. So, we may have a package like `id_vectors_web_lg`, but we want it to be based on a model we're training ourselves.

As for distributing the artifact: we actually provide our models as attachments to github releases. When you do `spacy download`, that's where the model is ultimately served from. So, you should be able to make your own release to distribute your file if you like.

**Comment by ines** [comment]
Btw, quick comment on the license. Where did you find the MIT information? On the FastText site, it says:

> The word vectors are distributed under the Creative Commons Attribution-Share-Alike License 3.0.

So with this license, it'd be okay to redistribute the vectors – just not as MIT. They'd also have to be CC BY-SA.

**Comment by jeannefukumaru** [comment]
Thanks for the clarification @honnibal. Noted about not depending on external artifacts. 

And yes, @ines you're right. The word vectors are CC BY_SA. I have been referencing the fastest GitHub instead of the webpage with word vector download links. My mistake!

**Comment by equester** [comment]
Hi @jeannefukumaru & @ines. 
I have trained spacy model (Indonesian Model)  with FastText new ID Vectors (https://fasttext.cc/docs/en/crawl-vectors.html)  that has both Wiki and CommonCrawl. I have trianed with default parameters on GPU and getting UAS ~84% and Tag ~94. 

The output seems very good so far given the accuracies are good. However, i would like to do custom training and would like to do something like GridSearch. @ines Can you help me set that up?
I have seen the current solution is to set the enviornment variable, but how do i set this up programmatically? Any reference would be helpful. 
 
If that happens, i can release the LG model to general public. 

Also, how do i create custom version of LG model (currently, it's close to moret than 5GB) which are smaller? like md, sm version?

**Comment by ines** [comment]
Merging this with ##3056!
