### ISSUE TITLE
PyTorch vs Tensorflow

### ISSUE THREAD

**Issue by damianoporta** [explosion/spaCy#3626]
Hello everybody, 
I do not want to start a framework battle but I would like to understand which of those frameworks is well integrated with Spacy. I have never used a DL framework so I am starting from zero, which is "better"?

**Comment by honnibal** [comment]
Well, we don't use either of these in spaCy, so you're free to use either :). I think many people do find PyTorch better for NLP, as it has better handling of variable length sequences. The fast.ai course is a good place to start.
