### ISSUE TITLE
jsonschema dep specification raises warnings

### ISSUE THREAD

**Issue by uda** [explosion/spaCy#3628]
## How to reproduce the problem
Install spacy in a library that requires `jsonschema>=3.0.0,<3.1.0`

```bash
spacy 2.1.3 has requirement jsonschema<3.0.0,>=2.6.0, but you'll have jsonschema 3.0.1 which is incompatible.
```

When I install all requirements at once this is just an annoyance, and I will still get the newer jsonschema (I am using the `Draft7Validator`), but when I install directly the latest spacy, it will just revert to jsonschema 2.6.0 which lacks the newer validators.

Since spacy uses Draft4Validator directly (and not an inferred one) there should be no issue allowing the newer versions - at least 3.0.x for now.

## Your Environment
* **spaCy version:** 2.1.3
* **Platform:** Linux-4.15.0-47-generic-x86_64-with-debian-buster-sid
* **Python version:** 3.6.8

**Comment by ines** [comment]
Ahh, cool, I was looking forward to v3.0.x coming out! Pretty sure that when I added the schema-powered features to spaCy, it wasn't out as a stable release yet, so I used the conservative version pin (also to prevent a v3.0 release from breaking things, just in case).

But your PR should be safe to merge 👍
