### ISSUE TITLE
Attributes on spans differs whether they are referenced from ents or doc slice

### ISSUE THREAD

**Issue by mr-bjerre** [explosion/spaCy#3633]
## How to reproduce the behaviour
I am not sure if this is a bug or if this behavior is intended.

    import spacy.lang.en
    import spacy.pipeline
    nlp = spacy.lang.en.English()
    ruler = spacy.pipeline.EntityRuler(nlp)
    ruler.add_patterns([{'label': 'LABEL', 'pattern': 'DK'}])
    nlp.add_pipe(ruler)
    doc = nlp('I am from DK.')

Now I can get `span.label_` from `doc.ents` elements as expected. But if I try to get `span.label_` from the corresponding `doc` slice then I get an empty string.

    ent = doc.ents[0]
    assert ent == doc[-2:-1]  # ok
    assert ent.label_ == 'LABEL'  # ok
    assert doc[-2:-1].label_ == 'LABEL'  # fail

## Info about spaCy

* **spaCy version:** 2.1.3
* **Platform:** Linux-4.18.0-17-generic-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.7.1
* **Models:** en

**Comment by ines** [comment]
This is currently the expected behaviour. A `Span` is only a view of a `Doc`, and you can have multiple spans over the exact same tokens for different purposes and different labels.

When you query the `Span`s in the `doc.ents`, they are created using the token's `ent_type_` attribute as the label. But if you just create a span outside of that context, the span isn't going to have a label, because the span label isn't necessarily equivalent to the entity label of the underlying tokens.

**Comment by mr-bjerre** [comment]
I see. Is it possible to create a span over non-neighbouring tokens? E.g.

> Earnings per share excluding non-recurring items were EUR 0.06 (0.01) and including non-recurring items EUR 0.08 (0.02).

I would like to have to entities here: `Earnings per share excluding non-recurring items` and `Earnings per share including non-recurring items`. Is that possible?

**Comment by ines** [comment]
No – by definition, a `Span` is a slice of a `Doc` and a sequence of neighbouring tokens. (This is even more important if you're looking at it from the perspective of named entities: the entity recognizer learns to predict a sequence of *valid* BILUO tags. Something like `B`-`I`-`O`-`O`-`L` will never be a valid entity.)

What you're looking for seems to be more of a collection of tokens? You could probably handle this in a custom attribute?

**Comment by mr-bjerre** [comment]
That makes sense and yes custom attribute for sure. To actually make the attributes I suppose I need to train the dependency parser. Looking at the [`label-scheme`](https://spacy.io/api/annotation#dependency-parsing) I am not really sure which labels to focus on though but I guess [`Token.subtree`](https://spacy.io/usage/linguistic-features#navigating-around) will be pretty useful. Any other advice? Thank you.
