### ISSUE TITLE
Are the NER metrics strict, lenient or average ?

### ISSUE THREAD

**Issue by AlexisPister** [explosion/spaCy#3634]
Hi,

I am using the Scorer object to compare a gold standard with the results of a trained spacy NER model. The attribute Scorer.scores gives me the recall, precision and f1-score. However, these metrics can have different interpretations given the possible overlaps of the gold and predicted annotations and if they are micro or macro (calculated with all annotations or weighted on the annotation types). I did not find any info on the doc, could you detail how these are computed ?

Thanks

**Comment by honnibal** [comment]
The metrics are strict, in the sense that a span is only counted as correct if there's an exact match between it and the gold-standard. You can have a look at the implementation in `spacy/scorer.py`. We use set membership for the check, with elements defined by `(start, end, label)` tuples.
