### ISSUE TITLE
Cusom NER model wont run when using R Reticulate package

### ISSUE THREAD

**Issue by Vonderful** [explosion/spaCy#3635]
Hi
I created a custom NER model from scatch with no other pipelines includes as I just want a customer NER, which works fantastically when running in spyder. In fact is great for capturing my custom entities. 

However, when I  run from r;

library(reticulate)
source_python("//GetEntitiesOnly.py")

WHere GetEntities.py is;

from __future__ import unicode_literals, print_function
import spacy
nlp=spacy.load(r'\\SLK NER Model2')

I get the following error;
Error in py_run_file_impl(file, local, convert) : 
  FileNotFoundError: [Errno 2] No such file or directory: '\\SLK NER Model2\\ner\\tok2vec_model

## Your Environment
    spaCy version      2.0.11
    Platform           Windows-7-6.1.7601-SP1
    Python version     3.6.5

Am I being a div?! Create the new model, exported it and can load it ok in sypder, but not in R?

Thanks in advance!

**Comment by ines** [comment]
Is the model compatible with the version of spaCy you're running? For example, I think the `spacy` in your R environment might be referring to a newer version like spaCy v2.1.x, while the model you're trying to load may have been trained with v2.0.x.

**Comment by Vonderful** [comment]
Thanks for the ubber quick response. Ill take a look at the versioning as its slight complicated by anaconda install!

**Comment by ines** [comment]
Okay, cool! I'm pretty sure the underlying problem comes down to the version incompatibility, because that's also what usually causes this error. Closing this, since it's likely not a problem within spaCy – but if you end up with any other problems, feel fre to reopen.

**Comment by Vonderful** [comment]
Just to let you know it was indeed versioning! Setting the right conda envy in R resolved the issue! Thanks!
