### ISSUE TITLE
quotes tokenization in the new version

### ISSUE THREAD

**Issue by TalSchuster** [explosion/spaCy#3636]
Something has changed in the way that `` quotes are tokenized.
Is that intentionally?

Example:

```
spacy.__version__
# out: '2.0.18'
spacy_model = spacy.load('en_core_web_sm')
[t for t in spacy_model("``example``")]
# out: [``, example, ``]
```

new vesrion:

```
spacy.__version__
# out: '2.1.3'
spacy_model = spacy.load('en_core_web_sm')
[t for t in spacy_model("``example``")]
# out: [`, `, example, `, `]
```

**Comment by ines** [comment]
This is likely a side-effect of the update in #3218, which refactored the tokenization rules to achieve 2-3 times faster tokenization. In some cases, we accept oversegmentation in favour of simpler and faster tokenization rules.

If it's important for your use case, you can always write a custom pipeline component that uses the [retokenizer](https://spacy.io/usage/linguistic-features#retokenization) to merge the quotes back together.
