### ISSUE TITLE
Add is_sent_end to token attributes

### ISSUE THREAD

**Issue by michelleful** [explosion/spaCy#3637]
## Feature description
Tokens already have an attribute called `is_sent_start` which can be used in the Matcher. Having an equivalent `is_sent_end` would be useful, so that we can say "only match this token if it's at the end of a sentence".

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?

It seems more at home in the SpaCy library itself.

**Comment by kutoxinyi** [comment]
Any update?

**Comment by honnibal** [comment]
I think I like this idea. Some implementation notes:

Several files need to be changed to support this. We need the computed property in the `spacy/tokens/token.pyx` file, and we also need the attribute name in the `spacy.attrs` file. Then we need to support the attribute at the Cython level, in the `spacy/tokens/token.pxd` file's `Token.get_struct_attr` method. And of course, we need to test the feature and add it to the docs.

The `is_sent_end` attribute should not be a writeable property. Instead, we'll want to raise an error that points people towards the right way to specify the sentence boundaries (`is_sent_start`).

When implementing the `token.is_sent_end` property, care should be taken to account for the `None` case. `is_sent_start` is ternary valued, to support cases where the sentence boundaries are unspecified. If the next token's `is_sent_start` value is `None`, we want `is_sent_end` to be `None` as well.

The `is_sent_end` value for the final token in the `Doc` should always be `True`.

**Comment by igor-susic** [comment]
@honnibal If this is available and no one is working on it, I would give it a try :)

**Comment by jackmen** [comment]
@igor-susic 
Any update on this issue? Would be interested in this feature. Thanks!

**Comment by MiniLau** [comment]
I am interested in this feature, is anyone working on this ?

**Comment by adrianeboyd** [comment]
No, I don't think anyone is working on this right now. (If you'd like to work on it, you are welcome to submit a PR. If you have questions or need feedback along the way, it's fine to submit a PR that's still in progress, just mark it as a WIP at first.)

**Comment by polm** [comment]
It looks like code for this was merged in May but the PR didn't get linked here.

https://github.com/explosion/spaCy/pull/5375

**Comment by svlandeg** [comment]
Ah, thanks @polm!
