### ISSUE TITLE
Displacy Render Doesn't "Return" anything

### ISSUE THREAD

**Issue by hmswaffles** [explosion/spaCy#3639]
In the Jupyter Notebook environment, I when I call displacy.render(*args), I see the output beneath the cell but I can't capture the output from the function, it is as if there is none. 

Here is the code I used to achieve the error:
sentences = [u"This is an example.", u"This is another one."]
for sent in sentences:
    doc = nlp(sent)
    svg = displacy.render(doc, style="dep",page=True)
    file_name = '-'.join([w.text for w in doc if not w.is_punct]) + ".svg"
    output_path = Path(file_name)
    output_path.open("w", encoding="utf-8").write(svg)

## The error I get

TypeError                                 Traceback (most recent call last)
<ipython-input-xxxxxx> in <module>
      5     file_name = '-'.join([w.text for w in doc if not w.is_punct]) + ".svg"
      6     output_path = Path(file_name)
----> 7     output_path.open("w", encoding="utf-8").write(svg)

TypeError: write() argument must be str, not None

## How the screen looks:
![image](https://user-images.githubusercontent.com/3068065/56776507-a51b9080-6781-11e9-950b-85253b6954e2.png)

## Your Environment
* Operating System: MacOs Mojave
* Python Version Used: Python 3.7. / Ipython 7.4.0
* Clang Version: 10.0.0
* spaCy Version Used: spacy==2.1.3

Any help would be much appreciated.

**Comment by ines** [comment]
Thanks for the report. This looks like the same issue as #3598, which has already been fixed on `master`!
