### ISSUE TITLE
hello i can't run tokenize with Thai language

### ISSUE THREAD

**Issue by Dobita21** [explosion/spaCy#3640]
i used this code but i cant to use tokenize. help me pls

from spacy.lang.th import Thai
nlp = Thai()  # use directly # import from spacy/lang/th
doc = nlp(["สวัสดีครับผมชื่อบุษบาลันลาลันลา"])
for token in doc:
  print(token.text)

## Your Environment

* Operating System: ubuntu 18.04.1 lts
* Python Version Used: 3
* spaCy Version Used: 2.1.3
* Environment Information: none

**Comment by ines** [comment]
The `nlp` object expects a string, but you're passing in a list instead of a string here:

> `doc = nlp(["สวัสดีครับผมชื่อบุษบาลันลาลันลา"])`

**Comment by wannaphongcom** [comment]
fixed https://github.com/explosion/spaCy/pull/3693

**Comment by Dobita21** [comment]
Thank you
