### ISSUE TITLE
Learning Algorithm behind spaCy model

### ISSUE THREAD

**Issue by Ghaliamus** [explosion/spaCy#3647]
Hello everyone and many thanks to those behind every detail of this great, up-to-date, rich-pipeline, well-documented library. 

I'm using spaCy for NER problem. I'm using the model: spacy.blank('en'). The optimisation is with language.begin_training, the looping with language.update. I got interesting results. I'm interested and thankful. 

However, searching the spaCy documentation did not help me with a very important knowledge: what is the learning algorithm used behind my spaCy code? I'm aware of an appreciated YouTube video ([https://www.youtube.com/watch?v=sqDHBH9IjRU](url)) as I'm aware of an interesting question but without answer ([https://stackoverflow.com/questions/45632241/spacy-ner-model-behind-the-scene](url)). However, I wish that there is a documented information about such cornerstone of such modelling. Such documentation is important to be cited in any presentation, blog, or research paper.

Is there any published documentation or paper telling the reader in direct way: What is the spacy language model? What the objective function considered in the optimisation? Are the answers: word2vec and SGD, respectively? In NER case, if we assumed that the NERecogniser learns the context of entities by using word2vec, in the next step (which predicting entities among new texts), what is the used prediction model? Is the answer: linear, random forest, SVM, etc. Can I conclude that NERecogniser is: word2vec for features representation learning, and (linear, RF or SVM) for prediction learning? 

Many thanks for the time in reading and possibly answering. 

Best wishes, 
Ghaliamus

**Comment by honnibal** [comment]
Hi @Ghaliamus ,

It's true that a paper could be useful, but I think you might actually find other information about neural methods for NLP more instructive. For instance, we don't really use word2vec for the context of the entities -- the word2vec algorithm learns something sort of like a thesaurus, so it's not what would be used as part of a neural network (although it's often a popular pre-process). Most models do not use word vectors as inputs to not-neural methods such as linear model, random forest, SVM etc.

The video you linked does describe the model in quite some detail: it explains that we use a neural network model, with convolutional layers to encode some ngram context, and a transition-based process with greedy search and a dynamic oracle loss. We also use a fairly intricate word embedding strategy, with subword features.

**Comment by Ghaliamus** [comment]
Hello @honnibal ,

I profoundly thank you for your appreciated time and every single word in your comment. I'm also sorry for my ignorance regarding the word2vec & NER context misunderstanding. 

I believe that I'll refer to the video & spaCy website in my paper & my thesis. 

Many thanks to you. 

Best wishes,
Ghaliamus
