### ISSUE TITLE
Website local build instructions

### ISSUE THREAD

**Issue by bjascob** [explosion/spaCy#3648]
When trying to preview the website locally after changes to universe.json I ran into documentation issues on how to do this.

1 - In **Contributing.md** under **Updating the Website**  the instructions call for running `harp server` but this didn't work and I'm wondering if these instructions are actually for an older version of the site.  Should these be updated or possibly just refer the user to the website's Readme.md for instructions?

2 - Under **website/Readme.md** there is a different process using `gatsby`, however these instructions didn't work for me initially either.  I'm using Ubuntu 18.04 (latest LTS release) which has NodeJS v8 as the default.  I upgraded to V10.15.3.  After upgrading I was able to get the website to run eventually, however there were apparently a number of npm version compatibility / cached dependency issues that caused a lot of headaches/time to resolve.  Should v10.15.3 be called out as a minimum version on this page?

I'm happy to make these small doc changes but want feedback prior to submitting a PR.

**Comment by ines** [comment]
Thanks for pointing this out and sorry for the frustration! Looks like I forgot to update the docs in `CONTRIBUTING.md` when we switched to the new site. We should probably just link to the website README from there, to prevent too much duplication of stuff that may change.

> Should v10.15.3 be called out as a minimum version on this page?

Yes, I just checked, and I also run it with v10.15. So mentioning that requirement is a good idea. We could also [add the Node version to the `package.json`](https://docs.npmjs.com/files/package.json#engines) – not sure if this has an effect if you install it locally with `npm install`, but I'm hoping it'd at least show a warning.
