### ISSUE TITLE
different noun_chunks behavior

### ISSUE THREAD

**Issue by bdewilde** [explosion/spaCy#365]
Hi! Loving the update to v0.100.7 so far. One thing I've noticed is that the corrected assignment of `PROPN` and `PRON` POS tags (see #191?) results in very different sets of `noun_chunks`, since in [this function](https://github.com/spacy-io/spaCy/blob/76f1d871da6d82371e1c55055ec2d57ce3c2efb2/spacy/syntax/iterators.pyx#L4) only heads with `word.pos == NOUN` are included. Is it expected and desirable to exclude spans that are just proper nouns ("United States", ...) or pronouns ("I", "we", ...)?

**Comment by honnibal** [comment]
Fixed, thanks!

@wbwseeker , can you verify that the fix is correct for German too? I haven't tested this fix yet either.

**Comment by wbwseeker** [comment]
should work now for German as well
