### ISSUE TITLE
Add Sentence pointer in Named Entity object

### ISSUE THREAD

**Issue by lababidi** [explosion/spaCy#366]
The named entities returned from `.ents` have individual `span`s returned. Is it possible to add a member to the `span` so that it points to the sentence that it is a part of? 

Would breaking a document up into sentences first be a better way to go to keep entities and sentences self-contained?

**Comment by honnibal** [comment]
Hmm. Maybe.

In the meantime something like this should work:

    def get_sent(span):
        root = span.root
        i = 0
        while root.head is not root:
            root = root.head
            i += 1
            if i > len(root.doc):
                raise ValueError("Infinite loop. Cycle in parse tree?")
        return root.doc[root.left_edge.i : root.right_edge.i + 1

**Comment by honnibal** [comment]
Done. Marking this issue `docs` so I don't forget to add it.

**Comment by lababidi** [comment]
This is clever. I'm almost tempted, though, to just run `nlp()/English()` on `.sents` individually because of how fast your wrote this thing. Is there something wrong with doing it this way?

**Comment by honnibal** [comment]
There shouldn't be anything wrong with that, no. Should work fine. A list of `Doc` objects might be less convenient than a single `Doc` in some situations though.
