### ISSUE TITLE
How was parsing done for the spacy model train on common-crawl

### ISSUE THREAD

**Issue by ibtingzon** [explosion/spaCy#3664]
For the spacy model [`en_vectors_web_lg-2.1.0`](https://github.com/explosion/spacy-models/releases) which was trained on the [Common Crawl dataset](https://commoncrawl.org/the-data/), I would like to know how the dataset was parsed. I understand that the corpus contains raw web page data, metadata extracts and text extracts. Are html tags, urls, and such filtered out? I'm asking in order to better understand the trained model. Thanks!

**Comment by honnibal** [comment]
@ibtingzon The source of the vectors is the Stanford GloVe vectors model. Unfortunately my understanding is that details of their preprocessing have been lost. I've looked for this information too, and my recollection is that as is sometimes the case with research, not all of the details were preserved.

For spaCy 3 we expect to switch to word vectors trained via our own pipelines. But until now the trade-off has been that there's value in using a "standard" vectors model, and the large GloVe vectors is definitely one such standard.
