### ISSUE TITLE
Setting vector values while using GPU

### ISSUE THREAD

**Issue by varun-96** [explosion/spaCy#3666]
When I was trying to set vectors to some of the terms, it throws the error mentioned below. After  analyzing, it turns out that importing `cupy` changes default array module. However, `cupy` module does not have **`resize`**  attribute.
## How to reproduce the behaviour
Run this code: 
```
import spacy
spacy.prefer_gpu()
nlp = spacy.load('en')
nlp.vocab.set_vector('htn', nlp.vocab.get_vector(u'cancer'))
```
Got this error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-cf00707dbdc6> in <module>()
----> 1 nlp.vocab.set_vector('htn', nlp.vocab.get_vector(u'cancer'))
vocab.pyx in spacy.vocab.Vocab.set_vector()
vectors.pyx in spacy.vectors.Vectors.resize()
AttributeError: 'module' object has no attribute 'resize'

```
## Your Environment
* Operating System: `Linux`
* Python Version Used: `2.7.16`
* spaCy Version Used: `2.0.16`
* Environment: **GPU** (`GRID K520`), `Cuda 9.2`

Please let me know if there is anything wrong with my approach

**Comment by honnibal** [comment]
This should be fixed in v2.1.3. We no longer implicitly activate the GPU just because cupy is available.
