### ISSUE TITLE
Unexpected behavior when load pre-trained word2vec

### ISSUE THREAD

**Issue by F0rge1cE** [explosion/spaCy#3667]
## How to reproduce the behaviour

I got **[E094] Error reading line 50 in vectors file ...** when I tried to load my own pre-train Gensim word2vec in .txt fotmat. 
I track down the exception and find it is raised here: 
**https://github.com/explosion/spaCy/blob/master/spacy/cli/init_model.py#L184**

Should it be `line.rsplit(' ', vectors_data.shape[1])` ? For example, if we have a n-dimension wordvec, there should be n+1 columns for each row. To split the row into n+1 elements(1 word + n-d vec), we only need to split it n+1-1=n times.

`line.rsplit(' ', vectors_data.shape[1] + 1)` may cause problem when a word token contains whitespaces.
 
## Your Environment

* **spaCy version:** 2.0.16
* **Platform:** Darwin-17.7.0-x86_64-i386-64bit
* **Python version:** 3.7.3

**Comment by honnibal** [comment]
@F0rge1cE I think you're right, sorry for the off-by-one error. Could you make a pull request with the fix?
