### ISSUE TITLE
Unable to load textcat model with pretraining from disk

### ISSUE THREAD

**Issue by nikhildes** [explosion/spaCy#3668]
## How to reproduce the behaviour

I first performed language model pretraining on my own unlabeled data, and was able to successfully train a multi-class textcat model and save it to my `output_dir` using the `train_textcat.py` example code with the `-t2v` flag. 

When I try to load the saved model in using this code: 
``` 
print("Loading from", output_dir)
nlp2 = spacy.load(output_dir)
```
I get the following error message: 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-48-4711bd0dfd51> in <module>
----> 1 nlp2 = spacy.load('spacy_srk')

~/anaconda2/envs/spacy/lib/python3.6/site-packages/spacy/__init__.py in load(name, **overrides)
     25     if depr_path not in (True, False, None):
     26         deprecation_warning(Warnings.W001.format(path=depr_path))
---> 27     return util.load_model(name, **overrides)
     28 
     29 

~/anaconda2/envs/spacy/lib/python3.6/site-packages/spacy/util.py in load_model(name, **overrides)
    131             return load_model_from_package(name, **overrides)
    132         if Path(name).exists():  # path to model data directory
--> 133             return load_model_from_path(Path(name), **overrides)
    134     elif hasattr(name, "exists"):  # Path or Path-like to model data
    135         return load_model_from_path(name, **overrides)

~/anaconda2/envs/spacy/lib/python3.6/site-packages/spacy/util.py in load_model_from_path(model_path, meta, **overrides)
    171             component = nlp.create_pipe(name, config=config)
    172             nlp.add_pipe(component, name=name)
--> 173     return nlp.from_disk(model_path)
    174 
    175 

~/anaconda2/envs/spacy/lib/python3.6/site-packages/spacy/language.py in from_disk(self, path, exclude, disable)
    784             # Convert to list here in case exclude is (default) tuple
    785             exclude = list(exclude) + ["vocab"]
--> 786         util.from_disk(path, deserializers, exclude)
    787         self._path = path
    788         return self

~/anaconda2/envs/spacy/lib/python3.6/site-packages/spacy/util.py in from_disk(path, readers, exclude)
    609         # Split to support file names like meta.json
    610         if key.split(".")[0] not in exclude:
--> 611             reader(path / key)
    612     return path
    613 

~/anaconda2/envs/spacy/lib/python3.6/site-packages/spacy/language.py in <lambda>(p, proc)
    780             if not hasattr(proc, "from_disk"):
    781                 continue
--> 782             deserializers[name] = lambda p, proc=proc: proc.from_disk(p, exclude=["vocab"])
    783         if not (path / "vocab").exists() and "vocab" not in exclude:
    784             # Convert to list here in case exclude is (default) tuple

pipes.pyx in spacy.pipeline.pipes.Pipe.from_disk()

~/anaconda2/envs/spacy/lib/python3.6/site-packages/spacy/util.py in from_disk(path, readers, exclude)
    609         # Split to support file names like meta.json
    610         if key.split(".")[0] not in exclude:
--> 611             reader(path / key)
    612     return path
    613 

pipes.pyx in spacy.pipeline.pipes.Pipe.from_disk.load_model()

~/anaconda2/envs/spacy/lib/python3.6/site-packages/thinc/neural/_classes/model.py in from_bytes(self, bytes_data)
    369                     if isinstance(name, bytes):
    370                         name = name.decode("utf8")
--> 371                     dest = getattr(layer, name)
    372                     copy_array(dest, param[b"value"])
    373                 i += 1

AttributeError: 'FeedForward' object has no attribute 'W'
```

Do I need to load in the the pretrained weights somehow for the new nlp pipeline? Or is this a bug? 

## Your Environment
* **spaCy version:** 2.1.3
* **Platform:** Linux-4.15.0-47-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.8
* **Models:** en

**Comment by ines** [comment]
Thanks for the report. What did you use as the base when you ran the `train_textcat.py` script? Did you start off with a pre-trained model or a blank model?

**Comment by nikhildes** [comment]
I started out with a blank 'en' model as the base.

**Comment by nikhildes** [comment]
Hi @ines. Any update on this?

**Comment by honnibal** [comment]
It looks to me like you might have a mismatch between the use of pretrained word vectors during pretraining, and during testing. If you don't specify the `--use-vectors` argument during pretraining, you can't use the word vectors in the input when you use `spacy train`.

**Comment by nikhildes** [comment]
thanks @honnibal 
If I understand correctly, when I use the `--use-vectors` flag during pretraining, it will create a vectors file that I pass in to the `spacy train` command as an argument. 
Is this correct? Is there any documentation or an example for how this is done? I know pretraining is a new feature in SpaCy, but it's a really useful one!

**Comment by honnibal** [comment]
@nikhildes That's not quite right. The representation we're learning with `spacy pretrain` is the weights for the `tok2vec` component in the spaCy models. We need to use the same config for that model component as what we pretrained.

An important setting for the `Tok2Vec` class is whether to use a word vectors file as one of the features for the word representations. We can pretrain while setting this to `False`. In this scenario, we'll use the word vectors table as part of the pretraining, but we won't need it during runtime. But if we set it to `True`, we do need the vectors at runtime.

In either case, we won't be *creating* the word vectors during pretraining.

**Comment by jfelectron** [comment]
When using pretrained tok2vec weights with TexCat, do you have to use the simple_cnn arch as the script indicates? On another issue @honnibal commented there is a hyperparam mismatch. I assume this could be fixed through proper init of textcat.

**Comment by svlandeg** [comment]
@nikhildes: Have you been able to solve your issue by revising the parameters used for running the CLI scripts? If not, could you paste the exact commands you're running here, so we can try and replicate this?
