### ISSUE TITLE
how to get better accuracy on NER P,NER R, NER F?

### ISSUE THREAD

**Issue by mvdream** [explosion/spaCy#3672]
I can't able to get better accuracy on NER . How increase accuracy for NER. My input data format is json.

Itn    Dep Loss    NER Loss      UAS    NER P    NER R    NER F    Tag %  Token %  CPU WPS  GPU WPS
---  ----------  ----------  -------  -------  -------  -------  -------  -------  -------  -------
  0     157.390    3351.249  100.000    0.249   10.000    0.485   97.119  100.000     2542        0                                           
  1       0.000    4672.161  100.000    0.000    0.000    0.000   98.079  100.000     7984        0                                           
  2       0.000    3091.492  100.000    0.000    0.000    0.000   96.519  100.000     7919        0                                           
  3       0.000    2529.554  100.000    0.000    0.000    0.000   99.160  100.000     8115        0                                           
  4       0.000    2443.754  100.000    0.000    0.000    0.000   99.520  100.000     7935        0                                           
  5       0.000    1525.564  100.000    0.000    0.000    0.000   99.280  100.000     7465        0                                           
  6       0.000    2130.643  100.000    0.000    0.000    0.000   99.400  100.000     8007        0                                           
  7       0.000    2233.730  100.000    0.000    0.000    0.000   99.640  100.000     8161        0                                           
  8       0.000    1261.388  100.000    0.000    0.000    0.000   99.520  100.000     7566        0                                           
  9       0.000    2275.507  100.000    7.692   10.000    8.696   99.280  100.000     8152        0                                           
 10       0.000     932.935  100.000   12.500   10.000   11.111   99.760  100.000     8110        0                                           
 11       0.000    1700.813  100.000    0.000    0.000    0.000   99.640  100.000     8013        0                                           
 12       0.000    1513.372  100.000    0.000    0.000    0.000   99.760  100.000     8184        0                                           
 13       0.000    1999.472  100.000    5.556   10.000    7.143   99.760  100.000     8181        0                                           
 14       0.000    1905.670  100.000    0.000    0.000    0.000   99.640  100.000     8168        0                                           
 15       0.000    1488.246  100.000    0.000    0.000    0.000   99.400  100.000     8147        0                                           
 16       0.000    1105.822  100.000    0.000    0.000    0.000   99.400  100.000     8180        0                                           
 17       0.000    1417.900  100.000    7.143   10.000    8.333   99.760  100.000     8150        0                                           
 18       0.000     939.226  100.000    7.143   10.000    8.333   99.400  100.000     8140        0                                           
 19       0.000     873.056  100.000    9.091   20.000   12.500   99.520  100.000     7645        0                                           
 20       0.000     488.043  100.000    6.250   10.000    7.692   99.640  100.000     8126        0                                           
 21       0.000    2462.479  100.000   10.526   20.000   13.793   99.640  100.000     8139        0                                           
 22       0.000    1015.176  100.000   15.385   20.000   17.391   99.640  100.000     8189        0                                           
 23       0.000    1382.601  100.000   12.500   20.000   15.385   99.640  100.000     8122        0                                           
 24       0.000     790.499  100.000   13.333   20.000   16.000   99.760  100.000     8137        0                                           
 25       0.000     850.898  100.000    7.692   10.000    8.696   99.760  100.000     8089        0                                           
 26       0.000     571.842  100.000    6.667   10.000    8.000   99.760  100.000     8164        0                                           
 27       0.000    1279.056  100.000    6.667   10.000    8.000   99.760  100.000     8146        0                                           
 28       0.000    2097.155  100.000    6.667   10.000    8.000   99.760  100.000     8101        0                                           
 29       0.000     927.751  100.000    5.263   10.000    6.897   99.640  100.000     8064        0   

## Your Environment

* Operating System:Ubantu
* Python Version Used:3.6
* spaCy Version Used:2.1.3

**Comment by honnibal** [comment]
There's no general-purpose answer to that, sorry. The answer depends deeply on what you're doing and how you're doing it. If you need better results than you can achieve by yourself, one approach would be to engage  a consultant with experience in NLP to try to help you.
