### ISSUE TITLE
Splitting into custom tokens

### ISSUE THREAD

**Issue by mr-bjerre** [explosion/spaCy#3673]
Looking the [custom tokenizer](https://spacy.io/usage/linguistic-features#native-tokenizers) it is not really clear to me exactly how I would achieve a tokenization that does the following

    Q418 => ['Q4', '18']

and 

    Q4/2018 => ['Q4', '/', '2018']

Whenever I have a `Q[1-4]` match then it should be a token. I suppose it is quite easy but I am confused on how my regex should look like and if I should _prefix_, _suffix_ or _infix_. 

The following seems to be working but I am a bit concerned whether I break something or if this is the right way to do it really?

    infixes = nlp.Defaults.infixes + (
        r'(?<=Q[1-4])', 
    )
    nlp.tokenizer.infix_finditer = spacy.util.compile_infix_regex(infixes).finditer

**Comment by ines** [comment]
For cases like this, it's probably specific enough to not clash with anything else – so this is a fine solution and probably the most efficient way to do this. Just keep an eye on the maintainability, so you don't end up with loads of hard-to-maintain and messy regex rules.

An alternative would be to use the new [`Retokenizer.split`](https://spacy.io/usage/linguistic-features#retokenization). You could then write a custom pipeline component that uses the matcher and the token shape etc. to find those tokens, and then split them accordingly. But this is likely going to be a bit slower.
