### ISSUE TITLE
Bug in init_model.py read_vectors()

### ISSUE THREAD

**Issue by jeffoneill** [explosion/spaCy#3674]
This is the current code for read_vectors:

```
def read_vectors(vectors_loc):
    f = open_file(vectors_loc)
    shape = tuple(int(size) for size in next(f).split())
    vectors_data = numpy.zeros(shape=shape, dtype="f")
    vectors_keys = []
    for i, line in enumerate(tqdm(f)):
        line = line.rstrip()
        pieces = line.rsplit(" ", vectors_data.shape[1] + 1)
        word = pieces.pop(0)
        if len(pieces) != vectors_data.shape[1]:
            msg.fail(Errors.E094.format(line_num=i, loc=vectors_loc), exits=1)
        vectors_data[i] = numpy.asarray(pieces, dtype="f")
        vectors_keys.append(word)
    return vectors_data, vectors_keys
```

The `+1` should be removed from `rsplit` because n+1 splits results in n+2 things but we only want n+1 things (the word and the vector of length n).  

This bug only manifests itself when there is whitespace in the word since the parameter is the maximum number of splits.

Bonus bug: when you have a word with whitespace, and do this:

    python -m spacy init-model en w2vdir --vectors-loc w2v.txt.gz

you get this error:

    ✘ [E094] Error reading line 3345 in vectors file w2vtmp.txt.

but execution of the Python script never stops and you see this on the command line:

    ⠴ Reading vectors from w2vtmp.txt.gz

At first I thought the script was still running though it was actually hung.

**Comment by ines** [comment]
Thanks for the report – I think this might be the same issue as #3667, right?
