### ISSUE TITLE
Format of Training Data of NER

### ISSUE THREAD

**Issue by mmanishh** [explosion/spaCy#3676]
## Your Environment

I am trying to train my own NER model on addresses to parse the given address into different format like district, province, city, street name. But the NER is not working well, My question is what should be the format of the training data? Is it need to be in sentence or contextual format? I labelled the district, village as a single token and try to tag in the full address. 

* **spaCy version:** 2.1.3
* **Platform:** Linux-4.18.0-17-generic-x86_64-with-debian-buster-sid
* **Python version:** 3.7.3
* **Models:** en

**Comment by honnibal** [comment]
Does this help? https://spacy.io/usage/training#example-train-ner

The NER model does expect at least sentence context. Paragraphs are often good too.

**Comment by ines** [comment]
Also, here's the full JSON format if you want to provide an annotated corpus to `spacy train`: https://spacy.io/api/annotation#json-input
