### ISSUE TITLE
Link to Universe Github broken

### ISSUE THREAD

**Issue by BramVanroy** [explosion/spaCy#3680]
At the bottom of [Universe](https://spacy.io/universe), the link to the Github section for it is broken. It directs to `https://github.com/explosion/spaCy/tree/master/website/universe/README.md` which doesn't exist any longer. I cannot find where the content now resides, so I cannot do a PR myself.

**Comment by ines** [comment]
Omg, I totally didn't realise I deleted the universe docs 😭 Here's the old file: https://github.com/explosion/spaCy/blob/49cee4af9284f72eb19588f36f75888209710074/website/universe/README.md

Maybe we could just move them to `website/UNIVERSE.md` for now and update the links accordingly? If you have time to submit the PR, that'd be great! 👍

**Comment by BramVanroy** [comment]
Done at https://github.com/explosion/spaCy/pull/3688.
