### ISSUE TITLE
quotation marks tagged as NOUN (german, french and english), add_special_case()

### ISSUE THREAD

**Issue by scalleri** [explosion/spaCy#3683]
Hey there 

I'm building a corpus in German/French and have been trying to add a special case to correctly POS-tag "«" as PUNCT (and also "»"). According to the docs this should be possible with nlp.tokenizer.add_special_case(STRING,CASE). The quotationmarks are wrongly tagged in English, German and French as far as I've seen now. 

Do you know why this doesn't work? 

I also tried to add suffix/infix/prefix rules, but the problem is the POS-Tagging.

Thanks for any input! :-) 

## How to reproduce the behaviour
```
import spacy
from spacy.symbols import ORTH, POS, NOUN, VERB, TAG
nlp = spacy.load('de_core_news_md')
doc = nlp("«Das ist ein Test.»")
for token in doc:
    print(token,token.pos_,token.lemma_)

#results in:
« NOUN «
Das PRON der
ist AUX sein
ein DET einen
Test NOUN Test
. PUNCT .
» NOUN »

#add special case
nlp.tokenizer.add_special_case(u"«",[{ORTH:u"«",POS:u"PUNCT",TAG:u"$("}])
doc = nlp("«Das ist ein Test.»")

for token in doc:
    print(token,token.pos_,token.lemma_)

#results with special case are the same
« NOUN «
Das PRON der
ist AUX sein
ein DET einen
Test NOUN Test
. PUNCT .
» NOUN »
```

## Info about spaCy
* **spaCy version:** 2.1.3
* **Platform:** Linux-4.4.0-97-generic-x86_64-with-Ubuntu-16.04-xenial
* **Python version:** 3.5.2

**Comment by BramVanroy** [comment]
I don't think Tokenizer is the right place to make such change. It is meant to have more control over the tokenization process. You are interested in the Tagger, it seems.

I am not sure how you can directly tell the Tagger that you want a specific token to be tagged in a specific way. What you can do, though, is adding a custom item to the pipeline which checks the text and changes the POS tag when necessary. Something like

```python
import spacy


def fix_quoation_marks(doc):
    for token in doc:
        if token.text in {'«', '»'}:
            token.pos_ = 'PUNCT'

    return doc


nlp = spacy.load('de_core_news_sm')
nlp.add_pipe(fix_quoation_marks, after='tagger')
doc = nlp("«Das ist ein Test.»")

for token in doc:
    print(token, token.pos_, token.lemma_)
```

But beware that this only changes the `.pos_` attribute. Other things such as `.is_punct` or `.tag_` are not influenced by this.

**Comment by scalleri** [comment]
thanks for the quick reply! Yeah I wasn't sure where to fix it because you cannot 'overwrite' the tagger anywhere. This seems like a good solution for the time being :-)
