### ISSUE TITLE
Using `pretrain` programmatically?

### ISSUE THREAD

**Issue by phdowling** [explosion/spaCy#3684]
I couldn't find the documentation on this so I figured I would ask here - can I programatically use the `pretrain` functionality (including fine-tuning a classifier on top) from python? I've only seen command line usage for that command.

**Comment by ines** [comment]
The CLI commands are all regular Python functions that live in [`spacy/cli`](https://github.com/explosion/spaCy/tree/master/spacy/cli) – so you should be able to import them directly and call them from Python as well. For instance:

```python
from spacy.cli.pretrain import pretrain

pretrain(texts_loc, vectors_model, output_dir)
```
