### ISSUE TITLE
💫 Retokenizer.merge should automatically skip duplicates

### ISSUE THREAD

**Issue by ines** [explosion/spaCy#3687]
Inspired by #3681. 

If you try to merge two overlapping spans using the new `Retokenizer`, spaCy will now correctly raise an error, since it's impossible to achieve the intended result. For instance:

```python
# Impossible because there's no reality where both spans can exist as a separate merged token
with doc.retokenize() as retokenizer:
    for span in [doc[0:3], doc[1:4]]:
        retokenizer.merge(span)
```

Duplicate spans can easily happen when you combine matches or things like entities and noun chunks. Because two identical spans are also "overlapping" in theory, an error is also raised when you try to merge them: 

```python
# Possible, but still raises an error
with doc.retokenize() as retokenizer:
    for span in [doc[0:3], doc[0:3]]:
        retokenizer.merge(span)
```

My PR in #3686 adds a helper `filter_spans` that removes overlapping spans and duplicates, and alternatively, users can also write custom functions (e.g. to expand overlapping spans to the largest possible sequence of neighbouring tokens). But the basic case of duplicates should be handled internally and shouldn't require the user to write their own filter functions.

Retokenizer source: https://github.com/explosion/spaCy/blob/master/spacy/tokens/_retokenize.pyx

**Comment by BramVanroy** [comment]
What is this `Retokenizer`? I haven't encountered it before!

**Comment by BreakBB** [comment]
@BramVanroy from [the docs](https://spacy.io/usage/v2-1/#retokenizer):

> The new Doc.retokenize context manager allows merging spans of multiple tokens into one single token, and splitting single tokens into multiple tokens. Modifications to the Doc’s tokenization are stored, and then made all at once when the context manager exits. This is much more efficient, and less error-prone. Doc.merge and Span.merge still work, but they’re considered deprecated.

Most likely this can be used for edge cases or general improvements to the tokenization.

**Comment by ines** [comment]
Yep, also see here: https://spacy.io/usage/linguistic-features#retokenization

It's essentially the new implementation of what was previously `Doc.merge` and `Span.merge`. It lets you merge one or more tokens into a single token, and as of v2.1, also split tokens. This can improve tokenization for cases that are difficult to handle with prefix/suffix/infix rules only. It's also helpful if you're using spaCy as a pre-processing step and you want to train word vectors etc. and merge named entities or noun chunks into single tokens first.

**Comment by BramVanroy** [comment]
Ah, I see. Cool! For a moment I was hoping that this allowed subword morphemic tokenisation. Especially useful in languages such as German or Dutch where compounds can get really long. I've been searching for a well-performing subword tokenizer that is better than wild frequency guesses à la BPE.

**Comment by naiveai** [comment]
Hey, I'd like to work on this issue. As far as I understand this, and I'm quite new to NLP so I might be wrong here - theoretically, this is as easy as simply checking whether a `Span` is already in our list of `self.merges`, right? The existing overlap check code is so far as I can tell correct.

**Comment by ines** [comment]
@naiveai Thanks a lot 🙏 And I think so, yes! If we already have a span with the same start and end index in the merges, we know that the current one is a duplicate and we can skip it. And yes, the test for this can go in the regression tests as `test_issue3687` 🙂

**Comment by vonum** [comment]
Hey, what is the current state of this issue?
