### ISSUE TITLE
Language.update has no return value

### ISSUE THREAD

**Issue by BreakBB** [explosion/spaCy#3692]
The code doc as well as the API doc references a return value for the `Language.update` method (which should be a dict), but as I see it in the code there is none. I guess the docs weren't updated after changes to that method?

## Which page or section is this issue related to?
https://spacy.io/api/language#update
https://github.com/explosion/spaCy/blob/master/spacy/language.py#L415

**Comment by BramVanroy** [comment]
This seems to go way back to https://github.com/explosion/spaCy/commit/66ea9aebe748ce99a104480bb41ade6725e37c9a#diff-b6b3e43f85a70fd78f0b9e8395857783 where the `state` (i.e. the modified, returned dict) was removed.

**Comment by BreakBB** [comment]
Would make the PR as well. I think it's just the doc string that needs an update to not state that `update` returns something. Just like at other places in spaCy an implicit return should be fine and not mentioned in the doc that the method returns `None`.

**Comment by BramVanroy** [comment]
Maybe this is also a good time to document the `rehearse` method at https://github.com/explosion/spaCy/blob/master/spacy/language.py#L461-L511.

**Comment by honnibal** [comment]
I think it should return `None`, yeah. So this would be a docs change.

The rehearse method is still pretty experimental: I haven't actually run the tests to check that the thing works well in practice. So I'm a bit reluctant to start recommending it already.
