### ISSUE TITLE
Pattern with match operator "!" does not work if text is shorter

### ISSUE THREAD

**Issue by mr-bjerre** [explosion/spaCy#3695]
Suppose I want to match all tokens that have **match** as lowercase *if* there is not a **not** preceding token.

I'd expect all assertions here to pass but the last does not.

    import spacy.lang.en
    import spacy.matcher

    nlp = spacy.lang.en.English()
    matcher = spacy.matcher.Matcher(nlp.vocab)
    matcher.add('MATCH', None, [{'LOWER': 'not', 'OP': '!'}, {'LOWER': 'match'}])
    assert len(matcher(nlp('a match'))) == 1
    assert len(matcher(nlp('not match'))) == 0
    assert len(matcher(nlp('match'))) == 1

Is there a workaround?

## Info about spaCy

* **spaCy version:** 2.1.3
* **Platform:** Linux-4.18.0-18-generic-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.7.1

**Comment by BramVanroy** [comment]
It is normal that this does not work and should not be changed in my opinion. You are telling the matcher: match two tokens: the first cannot match lower 'not', and the second has to match lower 'match'. In your last case, no match if found because you requested to match two tokens but your input only consists of one token. As such, the match has to fail.

**Comment by mr-bjerre** [comment]
I agree that there might be use cases where you'd want to match two tokens and the first can't be something *but* I think there are a lot more use cases like mine though.

Is it not possible to achieve my goal then (except for adding additional patterns)?

**Comment by mr-bjerre** [comment]
What about having multiple operators. So I could have both `'OP': ['!', '?']`?

**Comment by BramVanroy** [comment]
Since the matcher works on a Token level, I'm not sure how to accomplish what you want. I thought we could do something like this, but that doesn't work either.

```python
matcher.add('MATCH', None, [{'LOWER': 'not', 'OP': '!'}, {'LOWER': 'match'}])
matcher.add('MATCH_SENT_START', None, [{'LOWER': 'match', 'IS_SENT_START': True}])
```

**Comment by mr-bjerre** [comment]
Yeah I was considering that as well but then the first one will still just give a match. Looks like a feature request then?

I mean it would be good to be able to match a token, requiring that a specific token is not preceding (if any preceding).

**Comment by BramVanroy** [comment]
Yes, I agree. I would propose an operator `!^` where the preceding token is either *not* X *or* string start. String start can be checked by token index I assume.

 In pseudo code.

```
where x_token is the token to be matched
    and prev_token its preceding token;
if x_token.text == 'match':
    if x_token.index == 0: match
    elif prev_token.text != 'not': match
```

**Comment by mr-bjerre** [comment]
Cool. Do I need to do anything or are you on top of it?

**Comment by BramVanroy** [comment]
If you have the time, feel free to make a PR about it.

**Comment by mr-bjerre** [comment]
Alright. Can you point me in the direction where to implement it? Haven't contributed before

**Comment by BramVanroy** [comment]
I haven't fiddled with the ins and outs of the matcher yet, so I can't really help. For starters, the new operator must be added to the operator list, though. It might be better to wait for input from @honnibal  or @ines .

**Comment by honnibal** [comment]
Agree with @BramVanroy that the current behaviour is expected. Your quantifier idea wouldn't really work though. Imagine this in a regular expression:

```[^a]?b```

This is going to match the `b` in a string like `ab` just fine. I guess what you want is something with the semantics of:

```(?<!a)b```

I would advise you to just match on `b`, and then have some discard logic that you add in the `on_match` callback. We'd like to support look-arounds, but it's been a pretty tough road to get the matcher to its current level of stability, with the current feature set. We only just added a bunch of semantics for stuff like extension attributes, so I want to make sure everything's working well with the current feature set before I add something as complicated as look-arounds.

**Comment by BramVanroy** [comment]
I'm not sure how the matcher works behind the scenes, but I though that the Matcher would have more capabilities than mere regex, right? In other words,  token matching is not restricted to regex, I suppose?

I understand that you wouldn't want people messing with this feature, and in that case the `on_match` is probably the best approach indeed. But theoretically, would an implementation such as I proposed (https://github.com/explosion/spaCy/issues/3695#issuecomment-491223129) not work, or would it be technically too difficult to integrate (performance and API-wise)?

**Comment by honnibal** [comment]
I do think your suggestion would work, and it probably wouldn't add *that* much complexity. It's worth considering in future.

**Comment by cruzelante098** [comment]
Hi, has there been any progress on this matter?

**Comment by polm** [comment]
Going to close this since we're not actively working on it (and nobody else is that we're aware of), and, as pointed out, this is basically already covered by using `on_match` without much difficulty. 

If someone is interested in doing a PR please feel free to post in here or open a new thread though.
