### ISSUE TITLE
Make most_similar work like Gensim's version

### ISSUE THREAD

**Issue by mjspeck** [explosion/spaCy#3697]
## Feature description

Currently `nlp.vocab.vectors.most_similar()` returns only the single most similar vector for each vector passed to it. Gensim's `most_similar()` [returns the n-most similar vectors to a given vector](https://radimrehurek.com/gensim/models/keyedvectors.html#gensim.models.keyedvectors.BaseKeyedVectors.most_similar). This seems like a more useful implementation.

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
If so, we will tag it as [`project idea`](https://github.com/explosion/spaCy/labels/project%20idea) so other users can take it on.
This would not be a custom component or plugin.

**Comment by honnibal** [comment]
I guess we could support this. If someone wants to take this on, I would suggest using the `libcpp.queue.priority_queue` class to implement it. The `Vectors` class is already in Cython and uses C++ data structures, so there's no problem with using a C++ class in this function. I've found the STL `priority_queue` class much better than the Python equivalents.

**Comment by CartierPierre** [comment]
@mjspeck how to use this actual `most_similar` ? Is there any simple usage like
```
apples = nlp(u"I like apples")
oranges = nlp(u"I like oranges")
bananas = nlp(u"I like bananas")
most = apples.most_similarity(oranges, bananas)
```
or in a list ?

**Comment by CartierPierre** [comment]
I tried this
```
vect = Vectors(data=nlp("This is sentence").vector)
most = vect.most_similar(nlp("This is other sentence").vector)
```
and an error appeared :
```
Traceback (most recent call last):
  File "nlp.py", line 79, in <module>
    test_nlp()
  File "nlp.py", line 57, in test_nlp
    print(vect.most_similar(nlp("This is other sentence").vector))
  File "vectors.pyx", line 322, in spacy.vectors.Vectors.most_similar
  File "/home/pierre/.local/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 2481, in norm
    return sqrt(add.reduce(s, axis=axis, keepdims=keepdims))
numpy.AxisError: axis 1 is out of bounds for array of dimension 1
```
I also tried with more than 1 vector (using np.stack) and same error.

**Comment by mjspeck** [comment]
Yeah that I think is a separate issue. You need to reshape the vector like this: `nlp.vocab.vectors.most_similar(nlp.vocab['hello'].vector.reshape(1,300))`.
