### ISSUE TITLE
No name 'ORTH' in module 'spacy.attrs' in VSCode problems

### ISSUE THREAD

**Issue by Patrick-David** [explosion/spaCy#3699]
## How to reproduce the behaviour

When running **from spacy.attrs import ORTH** I get the error message 
**No name 'ORTH' in module 'spacy.attrs'**

The error message appears using VS Code in the 'Problems' tab,
but doesn't stop the script running.

I am trying to use the 'count_by' method from the Spacy API.

The count_by method seems to work - it returns  'word_id /  value' pairs as expected,

but the import error persists.

## Your Environment

* Operating System: Ubuntu 18.04 LTS
* Python Version Used: 3.6.7 64bit
* spaCy Version Used: 2.1.3
* Environment Information: venv

**Comment by BreakBB** [comment]
I think that [the example](https://spacy.io/api/doc#count_by) isn't correct and it should be:

`from spacy.symbols import ORTH`

**Comment by ines** [comment]
Thanks for the report – I think this could potentially have something to do with how the Cython is compiled, and how the VSCode debugger interprets the module (or fails to interpret it)? So, it thinks it's not there.

It's possible that we can fix this by changing something in the way the code is compiled, or exposing something to help VSCode. I'll also tag this `help wanted` in case someone else has an idea.

**Comment by Patrick-David** [comment]
Thanks Ines,
FWIW I also tried:

**from spacy.symbols import ORTH** 

as was suggested by @BreakBB . Again a similar VS Code "problems"  error showed:

 **No name 'ORTH' in module 'spacy.symbols'**

**Comment by BramVanroy** [comment]
Note that this is not unique to VS Code. Things like this also occur in PyCharm (but possibly in other cases). I know for a fact that PyCharm has issues with the PyTorch package and in some cases doesn't recognize simple things such as `tensor()`. As far as I know, this cannot be fixed from the package creator's side - but correct me if I'm wrong.

**Comment by honnibal** [comment]
I think it's because we do a sneaky trick in that part of the code, and manually insert the items into `globals()`. Personally I don't use an IDE (I use vim), so I tend not to notice these tooling consequences. Sorry.

It's hard to avoid the insertion trick for this code, as we'd otherwise have a fair bit of code duplication. It does seem to be a bug in VSCode though? I mean, if you execute the code in actual Python, it definitely works.

**Comment by ines** [comment]
I use VSCode, so I can try this. However, as @BramVanroy correctly notes, it's not exclusive to VSCode, and rather the way those Python debuggers work. So I'm not even sure I'd classify this as a bug – but I think the standard way of inspecting the modules just doesn't capture things like the globals hack.

**Comment by BramVanroy** [comment]
I cannot reproduce this specific issue on PyCharm. Considering that PyCharm is very specific for Python-related projects, it might make sense that the developers have done their best to figure out 'unusual' import/export methods (e.g. by using `globals()`).

However, I can also not reproduce this in VSCode. Using a `pipenv` and Python 3.7.
