### ISSUE TITLE
[Documentation] Clarify Token Attribute "Prob"

### ISSUE THREAD

**Issue by hmswaffles** [explosion/spaCy#3701]
A documentation suggestion: 

In the table of [Token Attributes](https://spacy.io/api/token), the explanation of "Prob"  is "Smoothed log probability estimate of token’s type." However, it isn't clear whether this refers to some sort of estimate about an entity type, the part of speech or a dependency relation. 

Please consider updating the documentation so we users know what "prob" refers to.

**Comment by honnibal** [comment]
It refers to word type (as opposed to token). I agree it could be improved, but it's hard to find the right blend of conciseness and clarity. Suggestions welcome?

**Comment by hmswaffles** [comment]
I'd love to give you suggestions, but I'm afraid I don't know what you mean when you say "word type" in this context. Do you mean the word's inferred `tag_`?

**Comment by honnibal** [comment]
Ah, sorry. The sentence `the cat sat on the mat` has 6 tokens, of 5 types. The word types are `{the, cat, sat, on, mat}`. If we say just "word", it seems true that there are 6 words in the sentence, but from another perspective, there are also only 5 different words in the sentence. The traditional terminology for this distinction is type vs token.

**Comment by ines** [comment]
To add more details, the "word type" in spaCy is implemented as the `Lexeme` object, the context-insensitive entry in the vocabulary: https://spacy.io/api/lexeme

Here's the word / word type distinction in code:

```python
doc = nlp("the cat sat on the mat")

word = doc[0]
word_type = nlp.vocab[word.text]

word2 = doc[4]
word_type2 = nlp.vocab[word2.text]

assert not word == word2
assert word_type == word_type2
``` 

So I guess in the docs for `Token.prob`, we could say: "Smoothed log probability estimate of token’s type (context-insensitive entry in the vovabulary)".
