### ISSUE TITLE
error in rule-based matching documentation

### ISSUE THREAD

**Issue by ggdhines** [explosion/spaCy#3708]
The following code (taken from a couple of different places [here](https://spacy.io/usage/rule-based-matching#entityruler)) produces no matches:

```python
import spacy
from spacy.matcher import Matcher

nlp = spacy.load("en_core_web_sm")
matcher = Matcher(nlp.vocab)
# Add match ID "HelloWorld" with no callback and one pattern
pattern = [{"TEXT": {"REGEX": "([Uu](\.?|nited) ?[Ss](\.?|tates))"}},
           {"LOWER": "president"}]
matcher.add("HelloWorld", None, pattern)

doc = nlp(u"This is about a United States president")
matches = matcher(doc)
for match_id, start, end in matches:
    string_id = nlp.vocab.strings[match_id]  # Get string representation
    span = doc[start:end]  # The matched span
    print(match_id, string_id, start, end, span.text)
```
It seems that the regex cannot deal with spaces - i.e. each element of the pattern list must match one individual token.

**Comment by aaronkub** [comment]
This is expected behavior. There's a note on the page you linked to: _"When writing patterns, keep in mind that each dictionary represents one token. If spaCy’s tokenization doesn’t match the tokens defined in a pattern, the pattern is not going to produce any results."_ That being said, you would want something like:
```
pattern = [{"TEXT": {"REGEX": "([Uu](\.?|nited)"}}, 
                   {"TEXT": {"REGEX": "[Ss](\.?|tates)"}},
                   {"LOWER": "president"}]
```
Phrases like this are often better handled by the [PhraseMatcher](https://spacy.io/api/phrasematcher).

**Comment by ggdhines** [comment]
Sorry, should have stated that
```python
pattern = [{"TEXT": {"REGEX": "([Uu](\.?|nited) ?[Ss](\.?|tates))"}},
           {"LOWER": "president"}]
```
is taken directly from the documentation - https://spacy.io/usage/rule-based-matching#regex

**Comment by aaronkub** [comment]
Oh you're right. I think that whole regex section needs to be updated. The block below it also has `pattern = [{"_": {"country": {"REGEX": "^([Uu](\.?|nited) ?[Ss](\.?|tates)"}}}]`. Unless the author assumed that "United States" would be an entity that had been merged into one token, in which case these patterns would work. Either way the examples are misleading I think.
