### ISSUE TITLE
Bug on rule based matcher when trying to use custom attribute

### ISSUE THREAD

**Issue by mr-bjerre** [explosion/spaCy#3716]
I'd expect the following example to pass but it doesn't

    import spacy.lang.en
    import spacy.matcher
    import spacy.tokens

    spacy.tokens.Token.set_extension('ent', default=None)
    nlp = spacy.lang.en.English()

    doc = nlp('This is just a stupid example')

    matcher = spacy.matcher.Matcher(nlp.vocab)
    matcher.add('MATCH', None, [{'LOWER': 'stupid'}, {'_': {'ent': 'EXAMPLE'}}])

    assert len(matcher(doc)) == 0

    doc[-1]._.ent = 'EXAMPLE'
    assert len(matcher(doc)) == 1

I am getting the following error

      File "site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
        exec(code_obj, self.user_global_ns, self.user_ns)
      File "<ipython-input-2-c8dfba776706>", line 13, in <module>
        assert len(matcher(doc)) == 0
      File "matcher.pyx", line 177, in spacy.matcher.matcher.Matcher.__call__
      File "matcher.pyx", line 232, in spacy.matcher.matcher.find_matches
    TypeError: an integer is required

However if I do 

    spacy.tokens.Token.set_extension('ent', default='')

then it actually works as expected. So it doesn't like the None value

## Info about spaCy

* **spaCy version:** 2.1.3
* **Platform:** Linux-4.18.0-18-generic-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.7.1

**Comment by honnibal** [comment]
Matching on extension attributes is currently constrained to only work on string- and integer-typed values. Whether to handle `None` is a good question.

* Pro: It lets you use `None` as a default value, distinct from 0 or the empty string.
* Pro: Equating `None` and 0 is *probably* what the user wants.
* Con: It's more implicit, and potentially surprising.
* Con: If `None` and empty-string are supposed to be distinct, is it good to match on them the same way?

I would lean towards not handling this. It seems weird to allow the matcher to match on `None` for extension attributes if you can't also distinguish it as a value from 0 or `""`. You'd get particularly weird results if you're trying to match something like "not empty string", and you end up not matching `None`.
