### ISSUE TITLE
--base-model argument on spacy train is unrecognized

### ISSUE THREAD

**Issue by Arakkun** [explosion/spaCy#3720]
## How to reproduce the behaviour
Try executing spacy train with the --base-model or -b parameter.
The result will be "spacy train: error: unrecognized arguments:" meaning the argument is not usable despite being advertised as usable in the Docs

## Your Environment
* **spaCy version:** 2.0.16
* **Platform:** Windows-10-10.0.17134-SP0
* **Python version:** 3.6.8
* **Models:** en, en_core_web_lg

**Comment by ines** [comment]
Thanks for the report – looks like we forgot to add the "new in version" tag to that argument. It was introduced in spaCy v2.1, but you're using spaCy 2.0.16. I'll update the arguments table accordingly! 👍
