### ISSUE TITLE
Lemmatizer and Pipeline conflicting results

### ISSUE THREAD

**Issue by AmitMY** [explosion/spaCy#3724]
## How to reproduce the behavior
If I run:
```py
from spacy.lemmatizer import Lemmatizer
lemmatizer = Lemmatizer()

print(lemmatizer("faces", "NN"))
print(lemmatizer("faces", "NNS"))
```
I get "faces"

If I run: 
```py
import spacy
nlp = spacy.load('en', disable=["parser", "ner"])
print(nlp("faces")[0].lemma_)
```
I get "face"

## Info about spaCy
* **spaCy version:** 2.1.3                                         
* **Platform:** Linux-3.10.0-957.10.1.el7.x86_64-x86_64-with-centos-7.6.1810-Cor e
* **Python version:** 3.7.3 
* **Models:** en
--

**Comment by honnibal** [comment]
The lemmatizer class currently expects the universal POS tag and morphological features, not the English-specific rich tag you're providing. Try:

```python

lemmatizer("faces", "noun", morphology={"Number": "Plur"})
```
