### ISSUE TITLE
what is meant by “raw text” in documentation?

### ISSUE THREAD

**Issue by d5555** [explosion/spaCy#3726]
spaCy documentation says:  you can also use the “simple training style” and pass raw texts and dictionaries of annotations to nlp.update.  But what is meant   by “raw text” ? 
 **Does it mean 'raw string' containing escape characters like this :**  "This is a first string.\nThis is another string.\n" ?
**Or it should be like this :**  
"This is a first string.
This is another string.
"
**Then how should look the following text in training sample ?** 
"This text has tripple quotation marks, """ and ''' ": he said' 

Given I want to create training data in "simple training style" like : 
TRAIN_DATA = [
        (u"Uber blew through $1 million a week", {"entities": [(0, 4, "ORG")]}),...

* Operating System: Windows 10
* Python Version Used: 3.7
* spaCy Version Used: 2.1.3

**Comment by ines** [comment]
Yes, it means a raw string. As far as Python is concerned, *how* you format your strings doesn't really matter. Consider the following example:

```python
text1 = """hello
world"""
text2 = "hello\nworld"
assert text1 == text2
```

Python also allows you to escape quotation marks, like this:

```python
text = "\"This text has triple quotation marks, \"\"\" and ''' \": he said'"
```

If you're storing your data as JSON, CSV or plain text, this will also happen automatically when you load the file into Python.
