### ISSUE TITLE
Proper way of walking through dependencies

### ISSUE THREAD

**Issue by Arttii** [explosion/spaCy#373]
So I have more of a question not an issue, but wasn't sure were it is appropriate to ask this.

I have a case where I need to build a rich text query based on an input sentence.

For example: All documents about Jesus or Dogs and Donald Trump.

I am pondering the proper way to say get all the relationships between the words. I guess I have to find all the conjunctions and walk left and right and find all the words that are say Nouns and adjectives and group them somehow. Or I should walk down from the root to get this?

I was wondering whats a good way of going about this?

Please feel free to remove if this is not the appropriate place to ask this.

Thanks.

**Comment by honnibal** [comment]
So you want a logical representation, something like this? Excuse my appalling notation:

    x = documents
    y = Jesus || (dogs && Donald Trump)
    z = about(x, y)
    all(z)

That's admittedly difficult to do --- the representation you get back from spaCy is much shallower than that. If you need this, you could consider contacting us about a consulting project.

You can have a look at some of the alternative representations offered by the TextaCy library, built on top of spaCy: http://textacy.readthedocs.io/en/latest/ . Maybe you'll find something useful there.
