### ISSUE TITLE
Mac Os Install  ucs4 conflicts 

### ISSUE THREAD

**Issue by dlemke01** [explosion/spaCy#3730]
## How to reproduce the problem

Hi, I'm attempting to install spacy on mac os x 10.13.3.  On the first pass failed with:

```bash
SystemError: [E130] You are running a narrow unicode build, which is incompatible with spacy >= 2.1.0. To fix this, reinstall Python and use a wide unicode build instead. You can also rebuild Python and set the --enable-unicode=ucs4 flag.
```

so I built a new python 2.7.16 with macports via
```bash
port install python27 +ucs4
```
and verified with 
```bash
>>> print(sys.maxunicode)
1114111
```
I also installed numpy with macports, hoping that this would build "off" the wide python build,
but I am getting the following error:

```bash
>>> import spacy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/laurn/Library/Python/2.7/lib/python/site-packages/spacy/__init__.py", line 10, in <module>
    from thinc.neural.util import prefer_gpu, require_gpu
  File "/Users/laurn/Library/Python/2.7/lib/python/site-packages/thinc/__init__.py", line 5, in <module>
    import numpy  # noqa: F401
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/_multiarray_umath.so, 2): Symbol not found: _PyUnicodeUCS2_AsASCIIString
  Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/_multiarray_umath.so
  Expected in: flat namespace
 in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/_multiarray_umath.so
```

with the critical Symbol not found: _PyUnicodeUCS2_AsASCIIString error.  Is there a known way to fix this? 

Thanks!

## Your Environment

* Operating System: MacOS 10.13.3
* Python Version Used: 2.7.16
* spaCy Version Used: 2.1.4
* Environment Information: fresh macports install

**Comment by honnibal** [comment]
I notice that you're installing numpy from a system directory. Could it be that that numpy was installed for the previous Python build, and now you need to install afresh for the updated Python?

Pip installation is surprisingly stateful, so it's really best to use virtualenv, so that you can manage the state a bit better. It's a bit like having a namespace or a local scope. If you install everything into the system path, that's like having one global scope you're dumping everything into. You can easily end up with a state that's very difficult to reason about, where you're getting weird problems.

Maybe try something like:

```
python -m virtualenv env
env/bin/python -m pip install -U pip
env/bin/python -m pip install spacy
```

Also, do you *have* to use Python 2.7 for your project? I think you would've gotten a less confusing error on Python 3, because I think the installations distinguish the unicode builds better.

**Comment by dlemke01** [comment]
You are referring to the system directory:
```bash
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/_multiarray_umath.so
```
? This is the directory on the path of the updated python 2.7.16 +ucs4 build, which I would have suspected to be the correct one.  The actual system version is ucs2, the confusing part to me is that the "correct" version seems to be checking for a usc2 flag: _PyUnicodeUCS2_AsASCIIString. 
Also, on mac os it appears you can not just continually delete all the versions of numpy to then reinstall a single version since the default system python 2.7.10 is installed with dist-utils.

If I go the virtualenv route it puts me back to the beginning since it copies the system python into env/bin
```bash
SystemError: [E130] You are running a narrow unicode build, which is incompatible with spacy >= 2.1.0. To fix this, reinstall Python and use a wide unicode build instead. You can also rebuild Python and set the --enable-unicode=ucs4 flag.
```
I do have to use 2.7 in the short term.  I'm trying to bring Spacy into a 1.5 year old NLP project that I recently joined, and the code is entirely python 2.7.   My end goal is to get it installed into a shared github package repository.  My first attempt used virtualenv for installation into the repo, and everything went well on my linux box, but it dies for the 2 macbook users who have these "narrow" python builds.  So then I tried just doing a vanilla installation on a mac book and here I am.

**Comment by ines** [comment]
@dlemke01 If it's only a short-term thing and you don't specifically need any of the new features introduced in spaCy v2.1, you could also start with spaCy v2.0.x? It uses the `regex` library, so it works on narrow unicode builds – but it also means that tokenization may be slower at scale.

Alternatively, maybe you can use `pyenv` to install a separate wide-unicode build (apparently now [the default](https://github.com/pyenv/pyenv/issues/257)?) on the MacBooks? That way, you might be able to avoid any side-effects of existing system installations.

**Comment by dlemke01** [comment]
@ines that could work (reverting to 2.0.x) in the short-term, even though I'd hate to dig deeper into the pit of deprecation; I will have to review the changes as the main tool we are using at present is the matcher.

I was able to compile a wide build of python from source, and then I built numpy from source 
with the following steps:

- build python 2.7.16 from source into /usr/local and with option 
```bash
--enable-unicode=ucs4
```
and verify it's default python and verify max unicode.

- pip uninstall all possible versions of numpy, as far as you can go, for me this is until the only version is the system version installed with dist-utils
- build numpy from source and install locally with
```bash
python setup.py build_ext --inplace
```
- copy local numpy to /usr/local/lib/python2.7/site-packages

So now I have a working wide python build in which I can import numpy but now 

```bash
>>> import spacy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/laurn/Library/Python/2.7/lib/python/site-packages/spacy/__init__.py", line 10, in <module>
    from thinc.neural.util import prefer_gpu, require_gpu
  File "/Users/laurn/Library/Python/2.7/lib/python/site-packages/thinc/neural/__init__.py", line 4, in <module>
    from ._classes.model import Model  # noqa: F401
  File "/Users/laurn/Library/Python/2.7/lib/python/site-packages/thinc/neural/_classes/model.py", line 7, in <module>
    import srsly
  File "/Users/laurn/Library/Python/2.7/lib/python/site-packages/srsly/__init__.py", line 4, in <module>
    from ._json_api import read_json, write_json, read_jsonl, write_jsonl
  File "/Users/laurn/Library/Python/2.7/lib/python/site-packages/srsly/_json_api.py", line 7, in <module>
    from . import ujson
  File "/Users/laurn/Library/Python/2.7/lib/python/site-packages/srsly/ujson/__init__.py", line 1, in <module>
    from .ujson import *
ImportError: dlopen(/Users/laurn/Library/Python/2.7/lib/python/site-packages/srsly/ujson/ujson.so, 2): Symbol not found: _PyUnicodeUCS2_AsUTF8String
  Referenced from: /Users/laurn/Library/Python/2.7/lib/python/site-packages/srsly/ujson/ujson.so
  Expected in: flat namespace
 in /Users/laurn/Library/Python/2.7/lib/python/site-packages/srsly/ujson/ujson.so
```
I did try reinstalling srsly like I did for numpy but the error persists, so it's starting to feel like my environment is just trashed now.  After glancing ay pyenv that does seem like a clean solution.  Thank you for the suggestions.  I think I will give that a try first, since I would like to use v2.1 of spacy.  I will give that a try tonight, and if then close out this issue.

**Comment by ines** [comment]
Ugh, I can definitely relate to the frustration 😭 And yeah, it looks like you ended up in a messed up environment somehow (and the fact that it's all in the system installation probably makes things trickier as well).

> it appears that they decided to not make ucs4 the default for pyenv only on mac os x

Ahhh sorry, my bad, I misread that part. But did you get it working with `pyenv`? If so, feel free to close this issue, yes. Otherwise... yeah, I'm not really sure what to suggest, because it sounds like it all comes down to getting a wide unicode build of Python 2 working as expected on OS X.

(In the worst case, maybe you can set up a Linux VM the developers can SSH into? 😅 VS Code [just announced](https://devblogs.microsoft.com/python/remote-python-development-in-visual-studio-code/) remote SSH workspaces, so the development experience can be very similar to running it all on your own machine.)

**Comment by dlemke01** [comment]
@ines,  I did implement a pyenv ucs4 python build, but pyenv still looks to the system build for various packages and I had similar problems.  At this point though my environment is trashed so it's getting hard to debug, so I don't want to say definitively that that method won't work, but one would have to be very aggressive in controlling and enforcing some kind of boundary between the pyenv and the system build, because by default they do overlap quite a bit, and any overlap seems to cause problems re: ucs2 vs ucs4.  I do not know if  it is possible to enforce that boundary. 

 I love the idea of implementing a VM , thank you for that suggestion.  This is the second time we've faced an issue with python on the macs (the other was with multi-threading crashes) and it really slows down development and takes the wind out of my sails.  We need to stabilize our development environments seems to be the lesson here :)  

As of now, the solutions seem to be:

- update to python 3 (unicode issue is gone)
- keep python 2 and revert to spacy 2.0 ([review changes](https://spacy.io/usage/v2-1))
- use a VM

**Comment by ines** [comment]
If you like the VM idea, it's probably the best solution to be honest! Even if you found a way to make the unicode build work for spaCy, it's totally possible that you'll run into some other issue with some other library on those machines later on.
