### ISSUE TITLE
NER single date tag

### ISSUE THREAD

**Issue by sr33kant** [explosion/spaCy#3731]
* Operating System: windows 10 
* Python Version Used: 3.5.1
* spaCy Version Used: 2.1.3
* Environment Information:

**Comment by sr33kant** [comment]
Im working with spacy 2.1.3. Im not sure if this is a bug or my limited understanding of the tokenization . ner model is identifying the entire string as one single date while it should have been two dates. Is it possible to get around this issue with special case tokenization ?
like this  nlp.tokenizer.add_special_case(u"* months ending ", special_case)


**txt='nine months ended spetember 2016 and 2015'
by=nlp(txt)
for ent in by.ents:
    print (ent.text,' : ',ent.label_)**

**Comment by ines** [comment]
The tokenization and named entitiy recongition are two separate things. The tokenizer uses rules to split the string into words. The named entity recognizer uses pre-trained statistical weights to *predict* whether one or more tokens are of a certain type (e.g. `DATE`), based on what it's seen during taining.

You might want to check out the 101 docs that explain those concepts in more detail: https://spacy.io/usage/spacy-101

What you're looking for sounds more like rule-based matching: define token-based rules and then assign a label to the result. You can find more details on this here: https://spacy.io/usage/rule-based-matching

Also make sure to check out the docs on the `EntityRuler`: https://spacy.io/usage/rule-based-matching#entityruler
