### ISSUE TITLE
lemma of who's is always who'

### ISSUE THREAD

**Issue by robscott95** [explosion/spaCy#3732]
Hey, just like in the title - here's more info on it though.

## How to reproduce the behaviour
```
import re
import spacy
from spacy.tokenizer import Tokenizer

nlp = spacy.load("en_core_web_sm")
# We have done the cleaning in a specific way, thus 
# we don't want to tokenize by anything new via spacy.
supress_re = re.compile(r'''[\s]''')
nlp.tokenizer = Tokenizer(nlp.vocab,
                          infix_finditer=supress_re.finditer,
                          suffix_search=supress_re.search,
                          prefix_search=supress_re.search)

doc = nlp(u"who's getting popcorn")
print([t.lemma_ for t in doc])
```
Output is:
`["who'", 'get', 'popcorn']`
What's interesting is that if it's uppercase `Who's` then it works properly.
It also doesn't matter if it's in the beginning, middle, or end of text, the results are the same.

I'm aware that there were some changes made to the not-yet released version, but I haven't checked it. Couldn't find anything similar in the rest of the issues, so posting it here for visibility.

EDIT: Just to be sure, the .text output is correct, only .lemma_ throws out this weird behavior.
```
doc = nlp(u"who's getting popcorn")
print([t.text for t in doc])
```
output:
`["who's", 'getting', 'popcorn']`

## Your Environment
* **spaCy version:** 2.1.4
* **Platform:** Windows-10-10.0.17763-SP0
* **Python version:** 3.7.3
* **Models:** en

I also was able to reproduce it on the window here: https://spacy.io/usage/linguistic-features#tokenization

**Comment by ines** [comment]
Merging this with the master issue in #2668!
