### ISSUE TITLE
Nvidia-smi: Insuficient Permissions when training in GPU mode

### ISSUE THREAD

**Issue by mrxiaohe** [explosion/spaCy#3735]
I was trying the [Training in the Command-line Interface](https://spacy.io/usage/training#spacy-train-cli) example. I have both the CPU version and the GPU version (cuda90) of spaCy installed, in two separate Anaconda virtual environments. When I noticed that the training speed with the GPU spaCy was not any faster than the CPU version, I ran `nvidia-smi` to check GPU usage, and got the following output:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 385.54                 Driver Version: 385.54                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  TCC  | 00000000:84:00.0 Off |                    0 |
| N/A   50C    P0    40W / 250W |    945MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      6572      C   Insufficient Permissions                     422MiB |
+-----------------------------------------------------------------------------+
```

I wonder if anyone has any idea about what the **Insufficient Permissions** message indicates. I have no issue training models with GPU with tensorflow and pytorch, and I've never see this message while working with tensorflow/pytorch. Thanks!

## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.7.3
* spaCy Version Used: 2.1.4.
* Environment Information:

**Comment by BramVanroy** [comment]
I found [this](https://devtalk.nvidia.com/default/topic/638761/cuda-setup-and-installation/-expected-behavior-nvidia-smi-reports-incorrect-memory-usage-in-windows-7-8-x64/post/4021359/#4021359).

> The “Used GPU Memory” is not available on Windows when running in WDDM mode. Because Windows KMD manages all the memory not NVIDIA driver.
> So your observed behaviors on K6000 GPU are expected:
> In TCC mode, the nvidia-smi.exe reports correct GPU memory usage;
> In WDDM mode, the “GPU memory usage” is not available;
> 
> In nvidia-smi’s documentation, it’s described as following.
> 
> Used GPU Memory
> Amount memory used on the device by the context. Not available on Windows when
> running in WDDM mode because Windows KMD manages all the memory not NVIDIA
> driver.

In your training command, did you enable the GPU? This is done by the `--use-gpu` flag.

**Comment by mrxiaohe** [comment]
@BramVanroy I did not specify the gpu option because I was under the impression that by default gpu would be used if GPU spaCy is installed and GPU is available. I will try adding the option to see how it works and report back. Thanks!

> I found [this](https://devtalk.nvidia.com/default/topic/638761/cuda-setup-and-installation/-expected-behavior-nvidia-smi-reports-incorrect-memory-usage-in-windows-7-8-x64/post/4021359/#4021359). It seems that on Windows, this message is to be expected.
> 
> > The “Used GPU Memory” is not available on Windows when running in WDDM mode. Because Windows KMD manages all the memory not NVIDIA driver.
> > So your observed behaviors on K6000 GPU are expected:
> > In TCC mode, the nvidia-smi.exe reports correct GPU memory usage;
> > In WDDM mode, the “GPU memory usage” is not available;
> > In nvidia-smi’s documentation, it’s described as following.
> > Used GPU Memory
> > Amount memory used on the device by the context. Not available on Windows when
> > running in WDDM mode because Windows KMD manages all the memory not NVIDIA
> > driver.
> 
> In your training command, did you enable the GPU? This is done by the `--use-gpu` option.
> 
> > Whether to use GPU. Can be either 0, 1 or -1.

**Comment by svlandeg** [comment]
Hi @mrxiaohe, as we haven't heard back, can we assume this issue was resolved ?
