### ISSUE TITLE
AttributeError: 'FunctionLayer' object has no attribute 'Q' with Spacy 2.1.4

### ISSUE THREAD

**Issue by Tpt** [explosion/spaCy#3736]
We have some internal models initialized with `spacy.blank('fr'')` with a trained textcat and ner components with the default options.

Models trained with Spacy 2.1.3 returns the following error when run with Spacy 2.1.4:

```
     self._nlp = spacy.load(model_name)
   File "/usr/local/lib/python3.7/site-packages/spacy/__init__.py", line 27, in load
     return util.load_model(name, **overrides)
   File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 133, in load_model
     return load_model_from_path(Path(name), **overrides)
   File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 173, in load_model_from_path
     return nlp.from_disk(model_path)
   File "/usr/local/lib/python3.7/site-packages/spacy/language.py", line 791, in from_disk
     util.from_disk(path, deserializers, exclude)
   File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 630, in from_disk
     reader(path / key)
   File "/usr/local/lib/python3.7/site-packages/spacy/language.py", line 787, in <lambda>
     deserializers[name] = lambda p, proc=proc: proc.from_disk(p, exclude=["vocab"])
   File "pipes.pyx", line 204, in spacy.pipeline.pipes.Pipe.from_disk
   File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 630, in from_disk
     reader(path / key)
   File "pipes.pyx", line 197, in spacy.pipeline.pipes.Pipe.from_disk.load_model
   File "/usr/local/lib/python3.7/site-packages/thinc/neural/_classes/model.py", line 371, in from_bytes
     dest = getattr(layer, name)
 AttributeError: 'FunctionLayer' object has no attribute 'Q'
 [2019-05-13 21:40:42 +0000] [9] [INFO] Worker exiting (pid: 9)
```

## Your Environment
* **spaCy version:** 2.1.4
* **Platform:** Linux-5.0.0-13-generic-x86_64-with-Ubuntu-19.04-disco
* **Python version:** 3.7.3

**Comment by honnibal** [comment]
Does it work if you retrain with v2.1.4?

**Comment by cachdealz** [comment]
I have the same issue with a model created with prodigy. Exact code works in the python shell via anaconda prompt but not in a jupyter notebook. Running Spacy v2.1.4 

` import spacy`
`nlp = spacy.load('C:\\Users\\Desktop\\model')`
`doc = nlp('This is a text I want to classify')`
`doc.cats`
`{'SOME_LABEL': 0.9511789679527283}`

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-20-9673e4b35fc0> in <module>()
      1 import spacy
      2 
----> 3 nlp = spacy.load('C:\\Users\\Desktop\\royalty-model-4')

~\AppData\Local\Continuum\anaconda3\lib\site-packages\spacy\__init__.py in load(name, **overrides)
     25     if depr_path not in (True, False, None):
     26         deprecation_warning(Warnings.W001.format(path=depr_path))
---> 27     return util.load_model(name, **overrides)
     28 
     29 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\spacy\util.py in load_model(name, **overrides)
    131             return load_model_from_package(name, **overrides)
    132         if Path(name).exists():  # path to model data directory
--> 133             return load_model_from_path(Path(name), **overrides)
    134     elif hasattr(name, "exists"):  # Path or Path-like to model data
    135         return load_model_from_path(name, **overrides)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\spacy\util.py in load_model_from_path(model_path, meta, **overrides)
    171             component = nlp.create_pipe(name, config=config)
    172             nlp.add_pipe(component, name=name)
--> 173     return nlp.from_disk(model_path)
    174 
    175 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\spacy\language.py in from_disk(self, path, exclude, disable)
    784                 continue
    785             if not hasattr(proc, "from_disk"):
--> 786                 continue
    787             deserializers[name] = lambda p, proc=proc: proc.from_disk(p, exclude=["vocab"])
    788         if not (path / "vocab").exists() and "vocab" not in exclude:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\spacy\util.py in from_disk(path, readers, exclude)
    609         if key.split(".")[0] not in exclude and key in msg:
    610             setter(msg[key])
--> 611     return msg
    612 
    613 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\spacy\language.py in <lambda>(p, proc)
    780         deserializers["vocab"] = lambda p: self.vocab.from_disk(p) and _fix_pretrained_vectors_name(self)
    781         deserializers["tokenizer"] = lambda p: self.tokenizer.from_disk(p, exclude=["vocab"])
--> 782         for name, proc in self.pipeline:
    783             if name in exclude:
    784                 continue

pipes.pyx in spacy.pipeline.pipes.Pipe.from_disk()

~\AppData\Local\Continuum\anaconda3\lib\site-packages\spacy\util.py in from_disk(path, readers, exclude)
    609         if key.split(".")[0] not in exclude and key in msg:
    610             setter(msg[key])
--> 611     return msg
    612 
    613 

pipes.pyx in spacy.pipeline.pipes.Pipe.from_disk.load_model()

~\AppData\Local\Continuum\anaconda3\lib\site-packages\thinc\neural\_classes\model.py in from_bytes(self, bytes_data)
    369                     if isinstance(name, bytes):
    370                         name = name.decode("utf8")
--> 371                     dest = getattr(layer, name)
    372                     copy_array(dest, param[b"value"])
    373                 i += 1

AttributeError: 'FunctionLayer' object has no attribute 'Q'

**Comment by cachdealz** [comment]
Upgrading to spaCy version: 2.1.4 and restarting the kernel solved this issue.
