### ISSUE TITLE
Language.replace_pipe should check if component is callable

### ISSUE THREAD

**Issue by BreakBB** [explosion/spaCy#3737]
## Feature description
The `replace_pipe` method should check if the component parameter is a `callable`, just like `add_pipe` does. This would prevent unintended usage of the pipeline.

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
No, this should simply be handeled internally.

`add_pipe` checks for the `__call__` attribute which should be done in `replace_pipe` as well. A new error message similar to [E004](https://github.com/explosion/spaCy/blob/8baff1c7c0418b26bf690756e1cac81ecf655816/spacy/errors.py#L98) might be necessary to show an example usage of `nlp.replace_pipe("pipe_name", nlp.create_pipe("component"))`.

**Comment by ines** [comment]
Good point, I agree! If you want to go ahead and submit a PR, that'd be super cool 😃
