### ISSUE TITLE
Example of pretrain with NER component

### ISSUE THREAD

**Issue by alejandrojcastaneira** [explosion/spaCy#3738]
Hello, I have a similar question as #3448 I whould like to know how to use pretrained weights for training a NER component inside an script and how to set up the hiperparameters to match the used on the pretrain, like other CNN depths or widths, by example?  

Best regards

**Comment by ines** [comment]
You should be able to adapt the code from #3448 and use `ner.model.tok2vec` etc. Now that the version is out, we also want to add some more examples to the training docs.
