### ISSUE TITLE
Question regarding lemmatizer on verb ending with -ing / noun

### ISSUE THREAD

**Issue by userFT** [explosion/spaCy#3740]
Hi! I'd like to change the behaviour of the lemmatizer regarding verb ending with -ing.
In the current version, sometimes, when a noun like "plastering", "quilting" or "painting" is being processed, the result of the lemmatization is the "basic form" of the verb.
For example:
"plastering" -> "plaster"
"quilting" -> "quilt"
"plastic tube for building" -> "plastic tube for build"

I'd like to keep the whole noun after the lemmatization and even if I have to "hardcode" it. Is this something easy to set up ? How can I do so ?

Thank you for your help

## Your Environment

* Operating System: Windows
* Python Version Used: 3.6.6
* spaCy Version Used: 2.1.3

**Comment by bjascob** [comment]
When I try this on spaCy 2.1.3 with [testSpacyLemmas.txt](https://github.com/explosion/spaCy/files/3177988/testSpacyLemmas.txt), I get the right answers.  Is your token.pos_ a NOUN or VERB?
```
nouns
plastering / NOUN  ->  plastering
quilting / NOUN  ->  quilting
painting / NOUN  ->  painting

verbs
plastering / VERB  ->  plaster
quilting / VERB  ->  quilt
painting / VERB  ->  paint
```

**Comment by userFT** [comment]
When running the same text, I get the same answer as yours.
But in these cases : 

**1st case** : Word alone
words = ['plastering', 'quilting', 'painting','coaching', 'building']
for word in words:
	sent = '%s' % word
	token = nlp(sent)[0]
	print(word, '/', token.pos_, ' -> ', token.lemma_)

plastering / VERB  ->  plaster
quilting / VERB  ->  quilt
painting / NOUN  ->  painting
coaching / VERB  ->  coach
building / NOUN  ->  building

---
**2nd case** : Word with little context
words = ['plastering', 'quilting', 'painting','coaching', 'building']
for word in words:
	sent = 'plastic tube for %s' % word
	token = nlp(sent)[3]
	print(word, '/', token.pos_, ' -> ', token.lemma_)

plastering / VERB  ->  plaster
quilting / VERB  ->  quilt
painting / NOUN  ->  painting
coaching / NOUN  ->  coaching
building / NOUN  ->  building

Depending on the situation, the lemma results of some nouns are verbs and some others are still nouns. I'm not sure to understand why.
Can I change something to keep the noun when the word is alone (without context) - like in the 1st case with the words painting / building ?

**Comment by bjascob** [comment]
I'm not seeing your issue.  To me, this looks like it's working correctly.
* When pos_ == NOUN the word remains the same
* When pos_ == VERB the 'ing' ending is removed, lemmatizing to the base word.  In the cases you've listed above, plaster and quilt are both verbs (of course their nouns too).

**Comment by userFT** [comment]
I also think it's working fine, but in my case I'd like to have pos_ == NOUN when the word is alone (like painting/building). I was wondering if I could change the priority or the behavior of the lemmatizer. This way, every time a noun is ending with 'ing', it will be considered as a noun.

Sorry if I'm not making myself understandable / sense.

**Comment by bjascob** [comment]
Reading this again, maybe this will help... 
Spacy needs to parse the sentence to figure out what the pos is.  When you don't supply a full sentence it really can't do that so it's going to get pos wrong a lot.  If, what you're asking is, "how do I force it to treat the word as a Noun", I'm not aware of a documented method but here's a little hack that I used and works for me...
```
nlp = spacy.load('en_core_web_sm')
svocab = nlp.vocab
word = 'plastering'
pos = 'NOUN'
lemmas = svocab.morphology.lemmatizer(word, pos)
lemma = lemmas[0]    # See morphology.pyx::lemmatize

**Comment by userFT** [comment]
Thank you very much! I think that may help me, I'll try to add a condition using your code. 
I'll close the issue. 😄
