### ISSUE TITLE
How many new custom NER entity types can be added during a single training session?

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#3742]
Hello,

I was just wondering what is the recommended process for adding multiple custom entity types to a model?  The example in the documentation adds only one
https://spacy.io/usage/training#example-new-entity-type

But then in the code I see you can call add_label() method as many times as you wish.  

    ner.add_label(LABEL)  # add new entity label to entity recognizer
    # Adding extraneous labels shouldn't mess anything up
    ner.add_label("VEGETABLE")

And it says if you do so the additional labels 'shouldn't mess anything up' - what does that mean?

Will it only train on the first label that was entered? What happens to the other labels that are added after the first?

And if it only accepts one - should we do something like

Training 1 input
- MODEL_0 
- Train Data = data used in building Mode_0 + additional LABEL1 data 

Train on LABEL1  -> output MODEL_0_plus_LABEL1

Training 2 input
- MODEL_0_plus_LABEL1 
- Train Data = data used in building MODEL_0_plus_LABEL1 + additional LABEL2 data 

 train on additional LABEL2 -> output MODEL_0_plus LABEL1_plus_LABEL2

etc

**Comment by abinpaul1** [comment]
You can add any number of labels.
LABELS_NEW=[''PLACE', 'DATE', 'SKILL', 'COURSE' , 'DEGREE', 'STREAM']

for label in LABELS_NEW:
    	ner.add_label(label)

Make sure your TRAINING_DATA has enough examples for these new labels. When the amount of labels increase, they can tend to overlap with existing labels. If they overlap, you will need a lot of examples to teach the model to recognize them. Another solution is to train a completely new model but even the you will need at least a few hundred to get a good output.

**Comment by ines** [comment]
Also, to add to the "shouldn't mess anything up" part: In spaCy, we've made a number of implementation choices to make it easy to add new labels to existing pre-trained models, which isn't something that all libraries allow out-of-the-box. So this comment in the example is meant to show that adding a new label is no problem, and shouldn't "mess up" the existing weights of the pre-trained model.
