### ISSUE TITLE
problems with lexeme, redux

### ISSUE THREAD

**Issue by bdewilde** [explosion/spaCy#3743]
## How to reproduce the behaviour

Following up on Issue #1031 — I'm seeing unexpected behavior on `Lexeme`s.

```python
>>> nlp = spacy.load("en")
>>> for word in ("the", "of", "hello", "goodbye"):
...     lex = nlp.vocab[word]
...     print(lex.text, lex.rank)
the 0
of 0
hello 0
goodbye 0
>>> lex.lex_id
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-56-7309e3631149> in <module>
----> 1 lex.lex_id

AttributeError: 'spacy.lexeme.Lexeme' object has no attribute 'lex_id'
```

This doesn't agree with the documentation [here](https://spacy.io/api/lexeme#attributes).

## Your Environment

* **spaCy version:** 2.1.4
* **Platform:** Darwin-18.5.0-x86_64-i386-64bit
* **Python version:** 3.7.0
* **Models:** es, en

**Comment by bdewilde** [comment]
Similarly (I think?):

```pycon
>>> for tok in doc:
...     print(tok.text, tok.lex_id, tok.rank)
Mr. 0 0
Speaker 0 0
, 0 0
480,000 0 0
Federal 0 0
employees 0 0
are 0 0
working 0 0
without 0 0
pay 0 0
, 0 0
...
```

**Comment by BreakBB** [comment]
I think (couldn't find it in the commit history) that `lex_id` was simply moved from the lexeme to the token class as property and the docs weren't updated accordingly.

**Comment by honnibal** [comment]
The attribute was renamed `.rank` on the lexeme :(. Sorry for the confusion on this. It's a messy spot.

**Comment by bdewilde** [comment]
No worries, messy spots happen. :) Just to be sure: Should we expect `.rank` on all the lexemes in my initial code snippet to be 0?

**Comment by honnibal** [comment]
It depends whether you have word vectors loaded and being used by the models. The `lex.rank` attribute is the feature that's extracted to index into pretrained vectors. There's a helper in `spacy._ml` called `link_vectors_to_models` that we call to sync the `lex.rank` attributes up with the rows in the word vectors table.
