### ISSUE TITLE
Loading Issue after converting FastText for spacy model

### ISSUE THREAD

**Issue by sahilsoni91** [explosion/spaCy#3744]
## How to reproduce the problem

```bash
# copy-paste the error message here
```

## Your Environment

* Operating System: Ubuntu
* Python Version Used: 3.6
* spaCy Version Used: 2.0.12
* Environment Information:

I have converted fasttext embedding to spacy compatible model using 
*python -m spacy init-model en ./enSpacyCompatibleModel --vectors-loc ../data/ta/cc.en.300.vec.gz*

After converting linked model with language code using
*sudo python -m spacy link ./enSpacyCompatibleModel cen*

When loading *cen* model returns
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.6/site-packages/spacy/data/cen/__init__.py'

please suggest.

**Comment by honnibal** [comment]
The `spacy link` command only works on models which are installed as Python packages. The `init-model` command produces a directory. You can convert the directory into a Python package and install it with `spacy package` and `pip install`.
