### ISSUE TITLE
span label not present where ent label is

### ISSUE THREAD

**Issue by bdewilde** [explosion/spaCy#3746]
## How to reproduce the behaviour

```pycon
>>> nlp = spacy.load("en")
>>> doc = nlp("Burton DeWilde was here.")
>>> ent = doc.ents[0]
>>> span = doc[0:2]
>>> print(ent, ent.start, ent.end, ent.label_)
Burton DeWilde 0 2 PERSON
>>> print(span, span.start, span.end, span.label_)
Burton DeWilde 0 2 
```

Since `Span`s are just views over the underlying `Doc` data, I expected the span to have entity labels. Maybe this is a feature and I'm just confused...

## Your Environment

* **spaCy version:** 2.1.4
* **Platform:** Darwin-18.5.0-x86_64-i386-64bit
* **Python version:** 3.7.0
* **Models:** es, en

**Comment by ines** [comment]
Sorry if this was confusing – maybe we can make this more clear somewhere in the docs. But this is currently the expected behaviour. Also see #3633:

> This is currently the expected behaviour. A `Span` is only a view of a `Doc`, and you can have multiple spans over the exact same tokens for different purposes and different labels.
>
> When you query the `Span`s in the `doc.ents`, they are created using the token's `ent_type_` attribute as the label. But if you just create a span outside of that context, the span isn't going to have a label, because the span label isn't necessarily equivalent to the entity label of the underlying tokens.

**Comment by bdewilde** [comment]
Understood. It makes sense, but definitely surprised/confused me. Thanks!
