### ISSUE TITLE
set_custom_boundaries

### ISSUE THREAD

**Issue by tr-andrew** [explosion/spaCy#3747]
This could very well be a problem on my end, I'm just not sure.

I have set up a custom boundary for newline ("\n") using the following code:

```python
def set_custom_boundaries(doc):
    for token in doc[:-1]:
        if token.text == "\n":
            doc[token.i+1].is_sent_start = True
    return doc
nlp = spacy.load("en_core_web_lg")
nlp.add_pipe(set_custom_boundaries, before='tagger')
```

I did this to fix an issue in my use case that is similar to this:

> This is a test
> Calculate, show your work, and submit your answers

Without a period at the beginning of the first line, and without the custom boundary, spaCy seems to combine the sentences and parse them together: 
![Screen Shot 2019-05-15 at 9 58 57 AM](https://user-images.githubusercontent.com/50682649/57815663-289b2280-772d-11e9-879d-f929bfdc6078.png)

After adding the custom boundary for \n, the boundary seems to keep the sentences separate in terms of the dependencies and sentences, but the parse for the second sentence is still incorrect (note specifically that the word "Calculate" here should be a verb): 
![Screen Shot 2019-05-15 at 9 58 06 AM](https://user-images.githubusercontent.com/50682649/57815720-6d26be00-772d-11e9-9789-445c75b4827a.png)

I set the custom boundaries to run before the tagger, so I thought it would tag tokens with the knowledge that Calculate is the beginning of a new sentence.

I was hoping it would parse something like it does when there is just a period separating the two sentences:
![Screen Shot 2019-05-15 at 9 58 12 AM](https://user-images.githubusercontent.com/50682649/57815791-c131a280-772d-11e9-9341-d8e8827efd01.png)

I also tried using a custom sentencizer, but same results. Is this happening because of the model? Is there any way for me to get \n to work in the way that a period does so that things are tagged accordingly, or is the only real way to fix this by updating the model?

## Your Environment

* Operating System: MacOS Mojave 10.14.4
* Python Version Used: 3.7.3
* spaCy Version Used: 2.1.3 with model en_core_web_lg 2.1.0
* Environment Information:

**Comment by tr-andrew** [comment]
I tried setting punct to true for \n with
`doc[token.i].is_punct = True`
But 
> attribute 'is_punct' of 'spacy.tokens.token.Token' objects is not writable

Is there any way to get a setter method for is_punct as lemma was made writable in this ticket: https://github.com/explosion/spaCy/issues/973 ?

Sorry, I'm pretty new to Python and spaCy in general, so I'm sorry if I'm missing something obvious here.

**Comment by honnibal** [comment]
You've used the `is_sent_start` attribute correctly, but unfortunately in this situation the model remains confused. It does look at the surrounding text for clues, and it seems that it's reading the `\n` differently from the punctuation, given that this is a strange sentence. Hopefully you can improve this if you give it some examples and use `nlp.update()`.
