### ISSUE TITLE
With spaCy 2.1, is Brown Clusters part required yet?

### ISSUE THREAD

**Issue by mosynaq** [explosion/spaCy#3748]
I trained my model with spaCy v2.0.18 and I trained Brown Clusters which took a long time. Now that spaCy 2.1 is out, are Brown Clusters need yet? I like so much to skip this step if it does not affect the model performance and accuracy.

**Comment by honnibal** [comment]
The clusters aren't required by the models anymore. I agree this was a big relief: I had a lot of trouble getting clusters trained as well, especially on bigger corpora.

**Comment by aatimofeev** [comment]
Are `freqs` deprecated as well?

**Comment by honnibal** [comment]
`freqs` are used to calculate the `.prob` attribute in the vocabulary. You don't need this for the models, it won't affect accuracy.

**Comment by mosynaq** [comment]
That's big relief! Thanks @honnibal!
