### ISSUE TITLE
Word Vector Training Script doesn't work with recent Gensim

### ISSUE THREAD

**Issue by polm** [explosion/spaCy#3749]
## How to reproduce the behaviour

If you try to run the `bin/train_word_vectors.py` script it will die at the call to `model.scale_vocab()` because that method is gone. 

## Your Environment

* **spaCy version:** 2.1.4
* **Platform:** Linux-5.0.4-arch1-1-ARCH-x86_64-with-arch
* **Python version:** 3.7.2
* **Gensim version:** 3.7.3

-----

I guess one way to fix this is by using an earlier version, but I managed to change the training script to work with current Gensim. The changes to the training related functions are described in Rare-Technologies/gensim#1777 and some of the issues are mentioned in RaRe-Technologies/gensim#2085. I get the impression the methods used in the training script were renamed suddenly rather than being gradually deprecated, though I'm not sure.

It seems like these are the main changes:

1. `model.scale_vocab()` → `model.vocabulary.prepare_vocab()`
2. `model.finalize_vocab()` → `model.trainables.prepare_weights()`
3. some members that were on the model aren't anymore, like `raw_vocab`, or need to be explicitly passed to functions, like `nr_iter`, `corpus_count`

Because the new methods aren't on the model object you also need to pass in parameters - I have updated the script so the code runs, but my output vectors seem off so I think I didn't convert things over correctly yet. If I get it working I'll make a PR with a fix.

**Comment by honnibal** [comment]
Thanks for the heads up! Definitely useful to know. I think this might affect a convenience function in Prodigy as well...

**Comment by BramVanroy** [comment]
It might be interesting to also ping @gojomo about this.
