### ISSUE TITLE
Change log level of wasabi

### ISSUE THREAD

**Issue by cuent** [explosion/spaCy#3752]
I am debugging some parts of Spacy and I'd like to see some log messages printed. How can I change the logging level for wasabi library?

**Comment by ines** [comment]
I'm not 100% sure I understand the question – do you have an example?

[`wasabi`](https://github.com/ines/wasabi) is currently only intended for printing formatted messages, e.g. on the command line. We only ever use it in `spacy.cli` and internally, it only calls `print`.

**Comment by BramVanroy** [comment]
I assume OP is talking about [`logging` levels](https://docs.python.org/3/library/logging.html#levels). But, of course, if wasabi does not use `logging`, such levels are useless.

**Comment by ines** [comment]
Ah okay, yes, then the answer is: no, `wasabi` doesn't log, it just prints. The codebase should be pretty lightweight and easy to follow – see here: https://github.com/ines/wasabi

If you are running it on a server etc., you can set `WASABI_LOG_FRIENDLY=1` to remove all color, animations etc. and give you a nice and clean log you can write to a file. This also allows you to do stuff like:

```bash
python -m spacy download en_core_web_sm > download.log
```
