### ISSUE TITLE
spaCy on multi GPU

### ISSUE THREAD

**Issue by EtienneAb3d** [explosion/spaCy#3758]
I had a read on this https://github.com/explosion/spaCy/issues/3394#issuecomment-471701609
I would also enjoy to be able to choose the GPU where spaCy is running. 

@honnibal 
`It's worth noting though that processing text is only 3-4 times faster on GPU than on CPU. This means CPU is generally much better value, if you have the choice. Of course if you have multiple GPUs sitting around I guess you may as well use them...But you probably have jobs to train as well, and if so, you'll probably find it better to parse text on a bunch of cheap CPU VMs, and save your GPU server for when you need it.`

I'm using spaCy for POS-tagging on large data sets.
I tried spaCy on CPU. It is using 100% of my 16/32 Threadripper for very poor tagging rate. I didn't take a precise note of it, but it would certainly have taken several months for 100M sentences. Like this, it's impossible to go faster.
I then ran 10 copies of spaCy on a single 2080Ti card. It is now using 100% of this GPU, with only 40% of my Threadripper CPU (including my own processing). It is processing 700K sentences/hour. It will take around 6 days.
I would like to use my second 2080Ti card to be able to use 100% of my machine.

**Comment by BramVanroy** [comment]
700K/hour? That is ~195 sentences per second? That is *really* slow. The problem must be somewhere else in your code. With [this repo](https://github.com/BramVanroy/spacy-extreme) I parsed 8K sentences _per second_ with the large spaCy model.

**Comment by EtienneAb3d** [comment]
Very interesting !

My main code is in Java. I thus use displaCy server. This means that the main CPU and/or GPU capability is used by displaCy ? 

Possibly I need to run spaCy in a pre-processing, then retrieve its result from a file.

Remark: I read your memory problem description. Did you try a python profiler to identify the memory leak ?

**Comment by BramVanroy** [comment]
I'm not sure how Java is integrated with spaCy or how you get the results from spaCy's displaCy into your Java code? But that in itself sounds like a huge bottleneck already.

**Comment by EtienneAb3d** [comment]
I used displaCy as a REST server.  The bottleneck is certainly coming from the fact that I'm sending it sentences one by one. It should produces a lot of pre/post-processing, or exchanges with the GPU, with a very poor efficient parallelisation of the analyse itself.

**Comment by BramVanroy** [comment]
Ah, I didn't even know there were REST APIs. Cool! Even though it does seem that, indeed, they are rather limited with respect to the options and capabilities (as is to be expected, I think). As far as I can see you cannot send a batch (array) as input so you are indeed very restricted.

Perhaps knowing that you can achieve 40x performance by going to Python, persuades you to write your code in Python instead of Java. `;-)`

**Comment by EtienneAb3d** [comment]
The displaCy server is very simple to adapt. I will also have look at the spaCy pipe. In this case, I may obtain much better results when using only the tagger component, rather the the whole pipe including parser and ner.
https://spacy.io/usage/processing-pipelines
Knowing that spaCy can process much faster than what I got till now, I will find an explanation and a solution to make it giving the best of it.
;-)

**Comment by EtienneAb3d** [comment]
When removing the parser and the ner components from the pipe, keeping only the tagger, I now get much higher performances on CPU (using several copies of the displaCy server). In my configuration, GPU and CPU are now of similar performances: about 2M sentences/hour. I think I'm still far from your speed because I'm sending sentences one by one. 
Thanks for your help!
