### ISSUE TITLE
Is it possible to integrate subword vectors for OOV words in the nlp pipeline>

### ISSUE THREAD

**Issue by ophiry** [explosion/spaCy#3761]
## Feature description
from: https://github.com/explosion/spaCy/pull/2247 spacy does support subword vectors, however, these vectors aren't part of the regular pipeline (and used in the NER) 
for example:  
`nlp('xyxy')[0].vector = [0...]`
even though explicitly using subword vectors does work
`nlp.vocab.get_vector('xyxy', 2,3) != [0...]`

**Comment by honnibal** [comment]
Customizing the `doc.user_hooks["vector"]`, `doc.user_span_hooks["vector"]` and `doc.user_token_hooks["vector"]` entries should work for this. It might be easiest to understand by looking at the `spacy/tokens/doc.pyx` file: in the `vector` property, we first check for a function in the `doc.user_hooks`, and use that if it's set. So this lets you customize the behaviour of this property.

**Comment by ophiry** [comment]
Would these hooks persist if saving the model to disk?
