### ISSUE TITLE
PROPN being mislabelled as ADJ

### ISSUE THREAD

**Issue by dlemke01** [explosion/spaCy#3766]
Hi, this PROPN is misidentifed.

## How to reproduce the behaviour

>>> import spacy
>>> nlp = spacy.load("en_core_web_sm")
>>> doc = nlp(u"Lillian has 3 cars.")
>>> doc[0], doc[0].pos_
(Lillian, u'ADJ')

## Your Environment

* Operating System: Linux arch 5.0.5-arch1-1-ARCH
* Python Version Used: 2.7.16
* spaCy Version Used: 2.1.3

**Comment by ines** [comment]
Thanks! Merging this with #3052.
