### ISSUE TITLE
upgrades to several packages in requirements.txt

### ISSUE THREAD

**Issue by OTLabs** [explosion/spaCy#3770]
## Feature description
Several packages mentioned in `requirements.txt` probably could be upgraded:

```
blis 0.3.0
plac 1.0.0
pytest 4.4.0
flake8 3.7.7
```

What do you think?

**Comment by ines** [comment]
Have you confirmed that the latest versions of those packages all work as expected? 

We usually try to pin to a version range that we know is working, prevents accidentally pulling in breaking changes when they are released, and is wide enough so it doesn't cause dependency conflicts with other libraries that depend on the same packages.

> `blis 0.3.0`

This is [our own package](https://github.com/explosion/cython-blis), so there might be a reason spaCy is still on `<0.3.0`. Will need to check this.

> `pytest 4.4.0`

I vaguely remember some issues with `pytest` 4.1.0+, so we pinned it to a lower version to make sure our CI tests run as expected. `pytest` and `flake8` are only development dependencies, so the versions shouldn't matter much here. Unless you're building from source, they won't be installed anyways.
