### ISSUE TITLE
It is possible to substitute Adam optimizer with another one?

### ISSUE THREAD

**Issue by beapaoli** [explosion/spaCy#3771]
It is possible to substitute Adam optimizer with another one?
If yes, how?

**Comment by honnibal** [comment]
Yes, but not from the command-line. The `nlp.update()` method expects an argument `optimizer` that should be a callable object, taking `weights`, `gradient` and an ID for the parameters. You can see examples of classes implementing this here: https://github.com/explosion/thinc/blob/master/thinc/neural/optimizers.pyx
