### ISSUE TITLE
Vocabulary Encoding

### ISSUE THREAD

**Issue by alejandrojcastaneira** [explosion/spaCy#3774]
Hello. I opened the strings list file inside the vocab of a trained model in Spanish and noticed this encodings:
```
"informaci\u00f3n",
  "i\u00f3n",
  "qu\u00e9",
  "caso",
  "aso",
  "est\u00e1n",
  "t\u00e1n",
.
.
```

look's like it's not encoding strings in 'utf-8'. Could by happening also in runtime? 
Best regards

**Comment by BreakBB** [comment]
This is because the used [srsly](https://github.com/explosion/srsly] library dumps the JSON as ascii encoded string.

I believe this could be changed if [here](https://github.com/explosion/srsly/blob/master/srsly/_json_api.py#L62) `json_dumps(data, indent=indent)` would be extended to `json_dumps(data, indent=indent, ensure_ascii=False)`.

**Comment by alejandrojcastaneira** [comment]
Thansk you! for your quick reply.

For versions before spacy 2.1 it could by fixed by changing this [line](https://github.com/explosion/spaCy/blob/bbaca991baee5d2c21cd48a9da535b7d2144ecda/spacy/compat.py#L68) for python 3 in the spacy/compat.py file: 

`json_dumps = lambda data: ujson.dumps(data, indent=2, escape_forward_slashes=False)`

by:

`json_dumps = lambda data: ujson.dumps(data, indent=2, escape_forward_slashes=False, ensure_ascii=False)`

**Comment by alejandrojcastaneira** [comment]
Well, went I update the line on srsly got: 

TypeError: json_dumps() got an unexpected keyword argument 'ensure_ascii'

so It' actually on [line 25 ](https://github.com/explosion/srsly/blob/master/srsly/_json_api.py#L25) in same file just extend:

 `result = ujson.dumps(data, indent=indent, escape_forward_slashes=False, ensure_ascii=False )`

**Comment by alejandrojcastaneira** [comment]
Just to notice, I saw in the defaul models like es_core_news_md also de_core_news_md they have these little miss/encodings inside their vocabulary.

**Comment by honnibal** [comment]
The encodings are correct, it's better to do it this way because it makes the Python 2 compatibility more reliable. The strings read in correctly, it's just that they're less human-readable. But that's not the primary concern for the serialization.
