### ISSUE TITLE
ValueError: spacy.syntax.nn_parser.Parser size changed, may indicate binary incompatibility. Expected 72 from C header, got 64 from PyObject

### ISSUE THREAD

**Issue by dumbori** [explosion/spaCy#3776]
Hello, I have an issue related to below:
when I run this code, 
import spacy
nlp = spacy.load('en')

I've got value error message: 
ValueError: spacy.syntax.nn_parser.Parser size changed, may indicate binary incompatibility. Expected 72 from C header, got 64 from PyObject

    Models             en_core_web_lg, en_core_web_sm, de, en
    Platform           Darwin-18.5.0-x86_64-i386-64bit
    Python version     3.5.4          
    spaCy version      2.0.12    
    Operating System: MacOX

ValueError                                Traceback (most recent call last)
<ipython-input-21-d84f1dc1b8dc> in <module>()
      1 import spacy
----> 2 nlp = spacy.load('en')

~/anaconda/lib/python3.5/site-packages/spacy/__init__.py in load(name, **overrides)
     13     if depr_path not in (True, False, None):
     14         deprecation_warning(Warnings.W001.format(path=depr_path))
---> 15     return util.load_model(name, **overrides)
     16 
     17 

~/anaconda/lib/python3.5/site-packages/spacy/util.py in load_model(name, **overrides)
    110     if isinstance(name, basestring_):  # in data dir / shortcut
    111         if name in set([d.name for d in data_path.iterdir()]):
--> 112             return load_model_from_link(name, **overrides)
    113         if is_package(name):  # installed as package
    114             return load_model_from_package(name, **overrides)

~/anaconda/lib/python3.5/site-packages/spacy/util.py in load_model_from_link(name, **overrides)
    127     except AttributeError:
    128         raise IOError(Errors.E051.format(name=name))
--> 129     return cls.load(**overrides)
    130 
    131 

~/anaconda/lib/python3.5/site-packages/spacy/data/en/__init__.py in load(**overrides)
     10 
     11 def load(**overrides):
---> 12     return load_model_from_init_py(__file__, **overrides)

~/anaconda/lib/python3.5/site-packages/spacy/util.py in load_model_from_init_py(init_file, **overrides)
    171     if not model_path.exists():
    172         raise IOError(Errors.E052.format(path=path2str(data_path)))
--> 173     return load_model_from_path(data_path, meta, **overrides)
    174 
    175 

~/anaconda/lib/python3.5/site-packages/spacy/util.py in load_model_from_path(model_path, meta, **overrides)
    141     if not meta:
    142         meta = get_model_meta(model_path)
--> 143     cls = get_lang_class(meta['lang'])
    144     nlp = cls(meta=meta, **overrides)
    145     pipeline = meta.get('pipeline', [])

~/anaconda/lib/python3.5/site-packages/spacy/util.py in get_lang_class(lang)
     48     if lang not in LANGUAGES:
     49         try:
---> 50             module = importlib.import_module('.lang.%s' % lang, 'spacy')
     51         except ImportError:
     52             raise ImportError(Errors.E048.format(lang=lang))

~/anaconda/lib/python3.5/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

~/anaconda/lib/python3.5/importlib/_bootstrap.py in _gcd_import(name, package, level)

~/anaconda/lib/python3.5/importlib/_bootstrap.py in _find_and_load(name, import_)

~/anaconda/lib/python3.5/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

~/anaconda/lib/python3.5/importlib/_bootstrap.py in _load_unlocked(spec)

~/anaconda/lib/python3.5/importlib/_bootstrap_external.py in exec_module(self, module)

~/anaconda/lib/python3.5/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

~/anaconda/lib/python3.5/site-packages/spacy/lang/en/__init__.py in <module>()
     13 from ..tokenizer_exceptions import BASE_EXCEPTIONS
     14 from ..norm_exceptions import BASE_NORMS
---> 15 from ...language import Language
     16 from ...attrs import LANG, NORM
     17 from ...util import update_exc, add_lookups

~/anaconda/lib/python3.5/site-packages/spacy/language.py in <module>()
     16 from .vocab import Vocab
     17 from .lemmatizer import Lemmatizer
---> 18 from .pipeline import DependencyParser, Tensorizer, Tagger, EntityRecognizer
     19 from .pipeline import SimilarityHook, TextCategorizer, SentenceSegmenter
     20 from .pipeline import merge_noun_chunks, merge_entities

~/anaconda/lib/python3.5/site-packages/spacy/pipeline/__init__.py in <module>()
      2 from __future__ import unicode_literals
      3 
----> 4 from .pipes import Tagger, DependencyParser, EntityRecognizer, EntityLinker
      5 from .pipes import TextCategorizer, Tensorizer, Pipe, Sentencizer
      6 from .entityruler import EntityRuler

pipes.pyx in init spacy.pipeline.pipes()

ValueError: spacy.syntax.nn_parser.Parser size changed, may indicate binary incompatibility. Expected 72 from C header, got 64 from PyObject

**Comment by ines** [comment]
This looks like you ended up with dependency conflicts or outdated files in your installation. Try upgrading to the latest version of spaCy and use a fresh virtual environment.

**Comment by dumbori** [comment]
ines, I deleted spaCy and install it again. Finally, it works. Thank you
