### ISSUE TITLE
The Spacy models trained on how much data?

### ISSUE THREAD

**Issue by KMohaghegh** [explosion/spaCy#3783]
Hi
I am looking for model specifications such as how much data used for model training, such as NER, tagger and parser. For instance the NER on sm/md/lg English model trained on how much raw data? I am looking but I found the information on how accurate the model is on meta.json and how the architecture is build and so on. I also end up in this link:
https://figshare.com/articles/Learning_multilingual_named_entity_recognition_from_Wikipedia/5462500 and also in your support page on this: 
https://github.com/explosion/spaCy/issues/1977
I also see that you mentioned the source in new release "Common Crawl" but how much data it was and many other questions?
You do me a reat favour if you could help me if you might answer that 
how much data was used? and how the spacy model was created?

Best
Kasra

**Comment by BreakBB** [comment]
Have you have a look at the docs for the [en models](https://spacy.io/models/en)? There you can read that e.g. the "sm" model was trained on the "OntoNotes 5.0" dataset which you can find [here](https://catalog.ldc.upenn.edu/LDC2013T19). That dataset includes:

![grafik](https://user-images.githubusercontent.com/33514570/58478129-8e3bd580-8155-11e9-8761-5b7bd442436f.png)

The "Common Crawl" datasets are listed [here](http://commoncrawl.org/the-data/get-started/). Each version has a different size. According to the description:

> It contains raw web page data, extracted metadata and text extractions.

**Comment by KMohaghegh** [comment]
Hi
Thanks for your reply now I got an idea about it, but now I am confused with that the whole "Common Crawl" data base was annotated or just part of it, so if I rephrase my question, it might be this how much raw data needs to be annotated to have the same English large model accuracy for instance, 0ne peta byte or few giga bytes or even 100s mega bytes? Thanks for your fast reply

**Comment by KMohaghegh** [comment]
Hi
Thanks for your reply now I got an idea about it, but now I am confused with that the whole "Common Crawl" data base was annotated or just part of it, so if I rephrase my question, it might be this how much raw data needs to be annotated to have the same English large model accuracy for instance, 0ne peta byte or few giga bytes or even 100s mega bytes? Thanks for your fast reply

**Comment by KMohaghegh** [comment]
Hi
Thanks for your reply now I got an idea about it, but now I am confused with that the whole "Common Crawl" data base was annotated or just part of it, so if I rephrase my question, it might be this how much raw data needs to be annotated to have the same English large model accuracy for instance, 0ne peta byte or few giga bytes or even 100s mega bytes? Thanks for your fast reply

**Comment by KMohaghegh** [comment]
Hi
Thanks for your reply now I got an idea about it, but now I am confused with that the whole "Common Crawl" data base was annotated or just part of it, so if I rephrase my question, it might be this how much raw data needs to be annotated to have the same English large model accuracy for instance, 0ne peta byte or few giga bytes or even 100s mega bytes? Thanks for your fast reply

**Comment by ines** [comment]
The English models (tagger, parser, NER) were trained on the OntoNotes corpus. See the table above for details on the data. For English, it's roughly 2 million words annotated with part-of-speech tags, dependencies and named entity labels.

The CommonCrawl data was only used for the **word vectors**. So that hasn't been annotated – it's just the raw text.
