### ISSUE TITLE
Tokenization by space only

### ISSUE THREAD

**Issue by usptact** [explosion/spaCy#379]
Is it possible to use Spacy, notably POS and dependecy parsing, on text which has been tokenized using *only* the space as the single rule? For example, I wish the following words to be kept as-is:
"can't" -> "can't"
"i've" -> "i've"
...

**Comment by honnibal** [comment]
The POS tagger and parser won't be accurate if you change the tokenisation. The statistical model won't recognise a token like "can't" if it's been trained to expect it always gets split into "ca" and "n't".

Instead you should run the pipeline and use the `span.merge()` (or `doc.merge()`) methods to put the tokens back together. You could use the `token.whitespace_` attribute to find tokens that are not followed by a space, and use that to figure out what to merge.

**Comment by knyghty** [comment]
I find myself needing something like this and not figuring out how to put it together, it might be nice as a helper function, I think getting the list of actual words out, while not useful for further processing, is still pretty useful.
