### ISSUE TITLE
German-Model: "sein" --> token.lemma == "mein" ???

### ISSUE THREAD

**Issue by snape6666** [explosion/spaCy#3793]
## How to reproduce the behaviour
txt= u'Er ist froh dick zu sein.'
nlp = spacy.load('de_core_news_md')
doc = nlp(bsp)
for token in doc:
    print(token.text, token.lemma_, token.pos_, token.tag_, token.dep_,
            token.shape_, token.is_alpha, token.is_stop)

Er ich PRON PPER sb Xx True True
ist sein AUX VAFIN ROOT xxx True True
froh froh ADJ ADJD mo xxxx True False
dick dick ADJ ADJD pd xxxx True False
zu zu PART PTKZU pm xx True True
sein mein AUX VAINF oc xxxx True True
. . PUNCT $. punct . False False

## Your Environment
I use Anaconda with python3 and installed the latest version today.

My Question:
Why does spacy give me "mein" as a lemma for "sein"? Shouldnt "sein" be the lemma? What iam missing?

**Comment by snape6666** [comment]
Same happens with:
"Remotesupport sollte möglich sein."

----
Remotesupport Remotesupport NOUN NN sb Xxxxx True False
sollte sollen VERB VMFIN ROOT xxxx True True
möglich möglich ADJ ADJD pd xxxx True True
sein mein AUX VAINF oc xxxx True True

**Comment by DuyguA** [comment]
Hellos,
I remember commenting on a similar issue about lemmatization of German pronouns: #3296

**Comment by snape6666** [comment]
I see, but in this case "sein" isnt a pronoun (not "his car") but a form of "to be".

But ill take a look at the other issue, maybe it helps.

**Comment by DuyguA** [comment]
I didn't read the issue properly, I'll quickly check then.

1 Haz 2019 Cmt 10:18 AM tarihinde snape6666 <notifications@github.com> şunu
yazdı:

**Comment by snape6666** [comment]
thx!

**Comment by ines** [comment]
Merging this with the master issue in #2668!

**Comment by snape6666** [comment]
I am looking forward to the Fix! =)
