### ISSUE TITLE
Spanish like_num False for each number-like string in "2 dos 1000 mil 12 doce"

### ISSUE THREAD

**Issue by munozbravo** [explosion/spaCy#3803]
```
nlp = spacy.load('es_core_news_md')

[t.like_num for t in nlp("2 dos 1000 mil 12 doce")]
[True, False, True, False, True, False]

[t.pos_ for t in nlp("2 dos 1000 mil 12 doce")]
['NUM', 'NUM', 'NUM', 'NUM', 'NUM', 'NUM']
```
Shouldn't like_num be true for all?

* **spaCy version:** 2.1.3
* **Platform:** Darwin-18.6.0-x86_64-i386-64bit
* **Python version:** 3.7.3

"es_core_news_md" for model.

**Comment by ines** [comment]
The `like_num` attribute is populated by a getter function thst takes the token text and returns a boolean. You can see examples of this here: 

* https://github.com/explosion/spaCy/blob/master/spacy/lang/en/lex_attrs.py
* https://spacy.io/usage/adding-languages#lex-attrs

It looks like the Spanish language data currently doesn't overwrite the default getter function, so it handles digits, but no Spanish-specific numbers. I'll tag this with `help wanted`, if someone wants to take this on.

**Comment by munozbravo** [comment]
Thank you.

I would like to help but not sure how to do it. (never done this before).

Just to check if what I think is the solution is correct...

I added a test with the issue, updated `__init__.py` within `es` to include:
```
from .lex_attrs import LEX_ATTRS
```
and the within the SpanishDefault class included
```
lex_attr_getters.update(LEX_ATTRS)
```

Created a `lex_attrs.py` within `es` that is equal to the english one except for `_num_words` which would be:
<details>_num_words = [
    "cero",
    "uno",
    "dos",
    "tres",
    "cuatro",
    "cinco",
    "seis",
    "siete",
    "ocho",
    "nueve",
    "diez",
    "once",
    "doce",
    "trece",
    "catorce",
    "quince",
    "dieciséis",
    "diecisiete",
    "dieciocho",
    "diecinueve",
    "veinte",
    "treinta",
    "cuarenta",
    "cincuenta",
    "sesenta",
    "setenta",
    "ochenta",
    "noventa",
    "cien",
    "mil",
    "millón",
    "billón",
    "trillón",
] </details>

Is this correct? 
Test is now passing.

If not...sorry for wasting your time.

Thank you!
