### ISSUE TITLE
anaconda windows package and multithreading

### ISSUE THREAD

**Issue by andrely** [explosion/spaCy#381]
I'm using the Anaconda python 2.7 on Windows 8 and installed the latest version as per the documentation (conda config --add channels spacy; conda install spacy).

But I cannot manage to get to Spacy to run multiple threads as verified with process explorer.

Is the Anaconda package compiled with OpenMP support or does it require manual installation to enable compilation with OpenMP?

Kind regards

André Lynum

**Comment by xysmas** [comment]
I can confirm that via the anaconda 2 and 3 packages on os x that the multithreading is not working correctly. 

Building from source with anaconda 2 and 3 on OSX 10.11 doesn't work by default, but a bit of fiddling with the compiler options gets it going okay. 

By default, homebrew will install gcc to be used with the versioned name, e.g. ```gcc-6```. you can either add the lines

```
os.environ["CC"] = "gcc-6"
os.environ["CXX"] = "g++-6"
``` 
to setup.py or call
`CC=gcc-6; python setup.py build; pip install -e . ` to get it working correctly. this should be updated in the docs.

**Comment by msunil10052** [comment]
@andrely , were you able to find "Is the Anaconda package compiled with OpenMP support in Windows ?."
