### ISSUE TITLE
Different tokens between displaCy and python?

### ISSUE THREAD

**Issue by wtfuzz** [explosion/spaCy#382]
In displaCy, "girl's" is treated as a single noun token, but using spaCy in python, "girl" and "'s"  treated as separate tokens.

Is this normal behavior, or is displaCy doing some post processing of the tokens?

Here's an example:

```python
from spacy.en import English
nlp = English()

tokens = [i for i in nlp(u"girl's")]
print(tokens)
```

```
$ python test.py
[girl, 's]
```

**Comment by honnibal** [comment]
It's just how things are displayed on displaCy. If you want to achieve this with the Python API, you can use the `.whitespace_` attribute and the `.merge()` method.
