### ISSUE TITLE
in EntityRuler, allow using case insensitive phrase matches

### ISSUE THREAD

**Issue by ophiry** [explosion/spaCy#3822]
EntityRuler allow using both token patterns and phrase patterns

for token patterns it's possible to specify whether the match  is case sensitive or not.
for phrase patterns the option isn't available 

the workaround I use now is:
```
er = spacy.pipeline.EntityRuler(nlp)
# override the phrase matcher with case insensitive matcher
er.phrase_matcher = spacy.matcher.PhraseMatcher(nlp.vocab, attr='LOWER')
```

though it would be cleaner if this was an option when creating an EntityRuler object

**Comment by ines** [comment]
Yes, good point – I guess we could add a `phrasematcher_attr` argument to `EntityRuler.__init__`?

The entity ruler currently isn't serializing its settings, though (see #3526), so we need to add this as well to make this modification useful. (See the [`Sentencizer`](https://github.com/explosion/spaCy/blob/68900066e060b6e2fd7b74e343e6b4c93d8d96c2/spacy/pipeline/pipes.pyx#L1113) for an example of how the component settings could be serialized.)
