### ISSUE TITLE
Spacy pretrain attempts to load all data to memory

### ISSUE THREAD

**Issue by jfelectron** [explosion/spaCy#3825]
## Your Environment

* Operating System:  Ubuntu
* Python Version Used: 2.7
* spaCy Version Used: 2.1
* Environment Information:

It seems like the pretrain command is limited to relatively small corpuses. https://github.com/explosion/spaCy/blob/master/spacy/cli/pretrain.py#L92   attempts to load the entire dataset into memory. You can easily run out of memory.  Why does it need to load the entire set rather than stream from disk during each iteration?

It appears that minibatch_by_words can take a generator as input so see no reason why the entire datset should be loaded.

**Comment by honnibal** [comment]
Shuffling requires the data to be loaded into memory, so if you want to make multiple passes over the data, it assumes it needs to be read in.

If your dataset is large, I would recommend piping it into stdin. If you do that, the data should be streamed, allowing arbitrary large input text to be read.
