### ISSUE TITLE
Deploying to Azure Web Service doesn't get spacy and en models from requirements.txt

### ISSUE THREAD

**Issue by dchankova** [explosion/spaCy#3829]
I am using spacy and en_core_web_sm models in my project. I've created venv with all packages on my machine, freeze it to the requirenments.txt file and it works, but when I deploy the code on Azure - a problem with finding spacy modules appears. I've added in my requirements file -
- spacy==2.1.4
- https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz#egg=en_core_web_sm 
but it seems that spacy and its models aren't in antenv folder and the code fails.
I rewrite my code from using 
> import spacy
> nlp = spacy.load('en_core_web_sm')

to 

> import en_core_web_sm
> nlp = en_core_web_sm.load()

But still it doesn't find the used module.

**Comment by BreakBB** [comment]
Do you have other modules listed in the `requirements.txt`? And if yes, are they loaded just fine?

**Comment by dchankova** [comment]
Yes, there isn't any errors, but the application can't start because the error ModuleNotFoundError: No module named 'spacy'
Here is the log after the deployment:
> Running oryx build...
> Command: oryx build /home/site/wwwroot -o /home/site/wwwroot -l python --language-version 3.7 -p virtualenv_name=antenv
> Build orchestrated by Microsoft Oryx, https://github.com/Microsoft/Oryx
> You can report issues at https://github.com/Microsoft/Oryx/issues
> Oryx Version       : 0.2.20190420.8, Commit: 391f7dd882e6fe5bea69edf6ba76d77e3d310e96
> Build Operation ID : |A+XnZcVSX7o=.fd44d8bb_
> Repository Commit  : c28d2802785ebb62fb0cc81c41f9015f0ac99fab
> Source directory     : /home/site/wwwroot
> Destination directory: /home/site/wwwroot
> Python Version: /opt/python/3.7.2/bin/python3
> Python Virtual Environment: antenv
> Creating virtual environment ...
> Activating virtual environment ...
> Upgrading pip...
> Requirement already up-to-date: pip in ./antenv/lib/python3.7/site-packages (19.1.1)
> Done in 4 sec(s).
> Running pip install...
> [09:24:31+0000] Requirement already satisfied: attrs==19.1.0 in ./antenv/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (19.1.0)
> [09:24:31+0000] Requirement already satisfied: blis==0.2.4 in ./antenv/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (0.2.4)
> [09:24:31+0000] Requirement already satisfied: certifi==2019.3.9 in ./antenv/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (2019.3.9)
> [09:24:31+0000] Requirement already satisfied: chardet==3.0.4 in ./antenv/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (3.0.4)
> [09:24:31+0000] Requirement already satisfied: Click==7.0 in ./antenv/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (7.0)
> [09:24:31+0000] Requirement already satisfied: cymem==2.0.2 in ./antenv/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (2.0.2)
> [09:24:31+0000] Requirement already satisfied: Flask==1.0.3 in ./antenv/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (1.0.3)
> [09:24:31+0000] Requirement already satisfied: idna==2.8 in ./antenv/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (2.8)
> [09:24:32+0000] Requirement already satisfied: itsdangerous==1.1.0 in ./antenv/lib/python3.7/site-packages (from -r requirements.txt (line 9)) (1.1.0)
> [09:24:32+0000] Requirement already satisfied: Jinja2==2.10.1 in ./antenv/lib/python3.7/site-packages (from -r requirements.txt (line 10)) (2.10.1)
> [09:24:32+0000] Requirement already satisfied: jsonschema==3.0.1 in ./antenv/lib/python3.7/site-packages (from -r requirements.txt (line 11)) (3.0.1)
> [09:24:32+0000] Requirement already satisfied: MarkupSafe==1.1.1 in ./antenv/lib/python3.7/site-packages (from -r requirements.txt (line 12)) (1.1.1)
> [09:24:32+0000] Requirement already satisfied: murmurhash==1.0.2 in ./antenv/lib/python3.7/site-packages (from -r requirements.txt (line 13)) (1.0.2)
> [09:24:32+0000] Requirement already satisfied: numpy==1.16.4 in ./antenv/lib/python3.7/site-packages (from -r requirements.txt (line 14)) (1.16.4)
> [09:24:32+0000] Requirement already satisfied: plac==0.9.6 in ./antenv/lib/python3.7/site-packages (from -r requirements.txt (line 15)) (0.9.6)
> [09:24:32+0000] Requirement already satisfied: preshed==2.0.1 in ./antenv/lib/python3.7/site-packages (from -r requirements.txt (line 16)) (2.0.1)
> [09:24:32+0000] Requirement already satisfied: pyrsistent==0.15.2 in ./antenv/lib/python3.7/site-packages (from -r requirements.txt (line 17)) (0.15.2)
> [09:24:32+0000] Requirement already satisfied: requests==2.22.0 in ./antenv/lib/python3.7/site-packages (from -r requirements.txt (line 18)) (2.22.0)
> [09:24:32+0000] Requirement already satisfied: six==1.12.0 in ./antenv/lib/python3.7/site-packages (from -r requirements.txt (line 19)) (1.12.0)
> [09:24:32+0000] Collecting spacy==2.1.4 (from -r requirements.txt (line 20))
> [09:24:33+0000]   Using cached https://files.pythonhosted.org/packages/04/44/d260185f41e5d1a43878e63b754befabf4178893af83df5c7e8a95cbd9bd/spacy-2.1.4-cp37-cp37m-manylinux1_x86_64.whl
> [09:25:00+0000] Collecting en_core_web_sm from https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz#egg=en_core_web_sm (from -r requirements.txt (line 21))
> [09:25:01+0000]   Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz (11.1MB)
> [09:25:06+0000] Requirement already satisfied: srsly==0.0.5 in ./antenv/lib/python3.7/site-packages (from -r requirements.txt (line 22)) (0.0.5)
> [09:25:06+0000] Requirement already satisfied: thinc==7.0.4 in ./antenv/lib/python3.7/site-packages (from -r requirements.txt (line 23)) (7.0.4)
> [09:25:06+0000] Requirement already satisfied: tqdm==4.32.1 in ./antenv/lib/python3.7/site-packages (from -r requirements.txt (line 24)) (4.32.1)
> [09:25:06+0000] Requirement already satisfied: urllib3==1.25.3 in ./antenv/lib/python3.7/site-packages (from -r requirements.txt (line 25)) (1.25.3)
> [09:25:06+0000] Requirement already satisfied: wasabi==0.2.2 in ./antenv/lib/python3.7/site-packages (from -r requirements.txt (line 26)) (0.2.2)
> [09:25:06+0000] Requirement already satisfied: Werkzeug==0.15.4 in ./antenv/lib/python3.7/site-packages (from -r requirements.txt (line 27)) (0.15.4)
> [09:25:07+0000] Collecting wheel==0.33.4 (from -r requirements.txt (line 28))
> [09:25:07+0000]   Downloading https://files.pythonhosted.org/packages/bb/10/44230dd6bf3563b8f227dbf344c908d412ad2ff48066476672f3a72e174e/wheel-0.33.4-py2.py3-none-any.whl
> [09:25:08+0000] Requirement already satisfied: setuptools in ./antenv/lib/python3.7/site-packages (from jsonschema==3.0.1->-r requirements.txt (line 11)) (40.6.2)
> [09:25:08+0000] Installing collected packages: spacy, en-core-web-sm, wheel
> Done running pip install.
> Removing existing manifest file
> Done.
> Running post deployment command(s)...
> Deployment successful.
> App container will begin restart within 10 seconds.

**Comment by BreakBB** [comment]
Hmm.. So the installation of the modules is working just fine. And all the other modules are listed in your  `antenv` folder? I am not very familiar with Azure, but can you make sure your App is using the `antenv`?
