### ISSUE TITLE
bug in conll_train.py

### ISSUE THREAD

**Issue by attardi** [explosion/spaCy#383]
I installed the latest version from GitHub and I noticed that the following argument is missing in main() from bin/parser/conll_trainpy

    eval_only=False, 

Besides, I got this error when trying to train a parser:

    IOError: spacy/vocab/strings.json

How do I produce such a file?

**Comment by honnibal** [comment]
Sorry for the lack of docs.

You need to run the `bin/init_model.py` script, e.g.:

    python bin/init_model.py de lang_data/ corpora/ models/de

The script requires the following files:

    lang_data/prefix.txt # For tokenizer
    lang_data/suffix.txt  # For tokenizer
    lang_data/infix.txt    # For tokenizer
    lang_data/specials.json # For tokenizer
    lang_data/morphs.json # For lemmatizer
    lang_data/lemma_rules.json # For lemmatizer
    lang_data/gazetteer.json # For rule-based NER
    lang_data/tag_map.json # For tagger

For `train_conll.py`, you don't really need a tokenizer, so it won't matter what's in the tokenizer files, so long as they exist, and so long as the json ones are valid. So you could have '{}' as the values for instance.

For the `tag_map.json` file, you'll need to make sure that all POS tags in your treebank are listed in the tag map, and mapped to one of the coarse-grained tags listed in `spacy/parts_of_speech.pxd`. If you write a tag map we're missing, pull requests appreciated.

Finally, you don't *have* to provide a `corpora/clusters.txt` file, but the feature sets for all models are tuned towards Brown clusters being available.

Let me know how you go.

**Comment by tehnar** [comment]
@honnibal 
Do not want to open a new issue, so I'll ask it there.
How can I obtain the full train data that SpaCy uses?
