### ISSUE TITLE
spacy hook for PyInstaller

### ISSUE THREAD

**Issue by brightening-eyes** [explosion/spaCy#3831]
hi,
I'm currently making a hook for PyInstaller in order to turn my script which uses spacy into an executable.
I have created a hook which adds spacy into hiddenimports and allocates it's data, and a run-time hook which set's the data path, but I get an error like this:
```
ImportError: [E048] Can't import language en from spacy.lang: No module named 'spacy.syntax._parser_model'
```
this is the code to my hook:
```python
from PyInstaller.utils.hooks import collect_data_files
import spacy

# add datas for spacy
datas = collect_data_files('spacy', False)

# append spacies data path
datas.append((spacy.util.get_data_path(), 'spacy/data'))

hiddenimports=['cymem', 'cymem.cymem', 'thinc.linalg', 'murmurhash', 'murmurhash.mrmr',
'cytoolz', 'cytoolz.utils', 'cytoolz._signatures', 'spacy.strings',
'spacy.morphology', 'spacy.lexeme', 'spacy.tokens', 'spacy.tokens.underscore', 'spacy.parts_of_speech',
'dill', 'spacy.tokens.printers', 'spacy.tokens._retokenize', 'spacy.syntax', 'spacy.syntax.stateclass',
'spacy.syntax.transition_system', 'spacy.syntax.nonproj', 'spacy.syntax.nn_parser', 'spacy.syntax.arc_eager', 'thinc.extra.search',
'spacy.syntax._beam_utils', 'spacy.syntax.ner', 'thinc.neural._classes.difference', 'srsly.msgpack.util', 'preshed',
'preshed.maps', 'thinc.neural', 'thinc.neural._aligned_alloc', 'thinc', 'blis',
'blis.py', 'spacy.vocab', 'spacy.lemmatizer', 'spacy._align', 'spacy.util',
'spacy.lang', 'spacy.data.en', 'spacy.syntax._parser_model']

```
and here is the code to my run-time hook:
```python
import sys
import os
import spacy

spacy.util.set_data_path(os.path.join(sys._MEIPASS, "spacy", "data"))

```
if anything else i should do, please let me know to fix this.
thanks in advance for your help.

**Comment by ines** [comment]
Here are some threads on spaCy and PyInstaller, maybe some of the info there helps?

* #2536
* #3592

**Comment by brightening-eyes** [comment]
hi,
I managed to fix it, the problem was PyInstaller couldn't load
"en_core_web_sm", and I made a hook for it which collected it's data
with collect_data_files()

۱۳۹۸-۰۳-۲۰ ۱۳:۱۳ ‎+۰۴:۳۰ گرینویچ, Ines Montani <notifications@github.com>:

**Comment by skyguy126** [comment]
@brightening-eyes could you please share the full hook code, once you added support for "en_core_web_sm"?

**Comment by brightening-eyes** [comment]
@skyguy126 here it is:
```python
from PyInstaller.utils.hooks import collect_data_files

datas = collect_data_files("en_core_web_sm")

```
basically you can modify it to work with others such as en_core_web_lg or md and anything else.

**Comment by skyguy126** [comment]
@brightening-eyes what is the hook file named?

**Comment by brightening-eyes** [comment]
hook-en_core_web_sm.py
