### ISSUE TITLE
Text annotation: option for already tokenised text?

### ISSUE THREAD

**Issue by anetschka** [explosion/spaCy#3837]
Hi, I am currently evaluating spaCy for a German task. This said, it's obvious that I am new to the tool.

I am asking myself whether there is some option that I can pass to the model indicating that I feed text that already has been split/tokenised. In particular, my data is 1 sentence per line.  I currently get awkward output at sentence ends:

`	SPACE`

or

`		.	False`

This is not terribly bad, but also not terribly nice to filter out. Any hints?

Best,
a

## Environment

* Operating System: Windows 10
* Python Version Used: 3.5.2
* spaCy Version Used: 2.1.4

**Comment by honnibal** [comment]
Do you want one `Doc` object with all of the data, or are you happy to have one `Doc` object per line?

If the latter, it should be okay to just make sure your sentences don't have trailing whitespace. If the former, then the tricky thing is you have these characters in your text (`\n`) that aren't really part of the input --- they're delimiters. spaCy assumes that all of the characters in the text are actually part of the language, so it gives you a token for them to avoid destroying information. I would suggest keeping the character offsets of the sentence starts and ends, and then you can use the `Doc.char_span()` method to get a `Span` object. You could then mark the sentence boundaries by setting `span[0].is_sent_start = True`.

If your text is fully tokenized, and you don't just have the sentence boundaries, you'll want to create your `Doc` objects directly, e.g. `doc = Doc(nlp.vocab, words=["hello", "world"])`.

Hope that helps!

**Comment by ines** [comment]
> If your text is fully tokenized, and you don't just have the sentence boundaries, you'll want to create your Doc objects directly, e.g. doc = Doc(nlp.vocab, words=["hello", "world"]).

A quick note on this, to include how to process the `Doc` with a statistial model in the pipeline:

When you process a text with the `nlp` object like this...

```python
nlp = spacy.load("de_core_news_sm")
doc = nlp("Hallo Welt!")
```

... spaCy pretty much does the following under the hood:

```python
doc = nlp.make_doc("Hallo Welt!")
for name, proc in nlp.pipeline:  # call all pipeline components like tagger, parser, ner on doc
    doc = proc(doc)
```

`nlp.make_doc` turns the raw text into a `Doc` object, and spaCy then calls each pipeline component (like the tagger, parser or entity recognizer) on that `Doc` object in order. You can also [create a `Doc` manually](https://spacy.io/api/doc), so if you already have the pre-tokenized text, you can do the following:

```python
from spacy.tokens import Doc

doc = Doc(nlp.vocab, words=["Hallo", "Welt", "!"], spaces=[True, False, False])
for name, proc in nlp.pipeline:
    doc = proc(doc)
```

**Comment by anetschka** [comment]
Thanks for the hints!
