### ISSUE TITLE
pretrain with incorrect input file raises "cryptic" error

### ISSUE THREAD

**Issue by BreakBB** [explosion/spaCy#3840]
## How to reproduce the behaviour

I ran into this issue with a JSONL file which lines are simple strings instead of real key-value JSON. Running `pretrain` with a file which includes neither the `text` nor the `tokens` attribute, e.g.

> "This is just some string with no attributes"

Such input leads to an error [right here](https://github.com/explosion/spaCy/blob/f35ce097762c3bfc7010cfe6ee8398c66d8223b0/spacy/cli/pretrain.py#L201) when `record["text"]` is called while `record` doesn't have the `text` key.

The error message is:

> TypeError: string indices must be integers

## Your Environment
* Operating System: Windows 10
* Python Version Used: Python 3.7.3
* spaCy Version Used: 2.1.4

## Possible solution

As far as I know a simple string is still valid JSON therefore [srsly](https://github.com/explosion/srsly) shouldn't raise an error [here](https://github.com/explosion/spaCy/blob/f35ce097762c3bfc7010cfe6ee8398c66d8223b0/spacy/cli/pretrain.py#L103) or [here](https://github.com/explosion/spaCy/blob/f35ce097762c3bfc7010cfe6ee8398c66d8223b0/spacy/cli/pretrain.py#L108).

Instead a simple check if the `text` key exists would prevent this and raising a good error message in a new `else` path could hint the user about the invalid input.

**Comment by ines** [comment]
Thanks – this makes sense and I agree with the proposed solution 👍 If you want to submit a PR, that'd be awesome.

If I read this correctly, we could even consider checking this right before we shuffle the examples [here](https://github.com/explosion/spaCy/blob/f35ce097762c3bfc7010cfe6ee8398c66d8223b0/spacy/cli/pretrain.py#L105). First, make sure that `len(texts)` – if you have no texts, we might as well exit early and raise an error before we load the model and set everything up to do... nothing. And once we know that there's at least one text, we can do a simple check of `texts[0]`, make sure it's a dict and make sure it has the right keys etc.

**Comment by BreakBB** [comment]
Sure thing, I will gladly submit a PR for this. Already started with the work. Do you think empty values should simply be skipped (and maybe log a counter as warning) or should another error be raised?

**Comment by ines** [comment]
Yeah, you're right – I think skipping is better. If you have a few million texts, it'd kinda suck if you had to wait until all of those were processed, just to find out that text 934,529 was empty 😅
