### ISSUE TITLE
Spacy.Load from memory

### ISSUE THREAD

**Issue by smiles3983** [explosion/spaCy#3841]
Spacy.Load appears to only accept a physical storage path, or name of an installed package, which would also reside on physical storage.  We are being limited by our storage space, but are being given large memory allocation.  We are able to get the large data model into the running python's memory but cannot then get it into the spacy.load method.  We have tried using MemoryFS, binary object, etc.  It would be nice if the spacy.load method accepted either a binary object, or had the ability to access MemoryFS directories.

* Operating System: Red Hat Linux
* Python Version Used: 2.7.14
* spaCy Version Used: 2.0.18
* Environment Information: Openshift and docker

**Comment by ines** [comment]
Main thing here is that a model package consists of binary data *and* the `meta.json`, and `spacy.load` does several things: it initializes the blank language class for the given language, sets up the processing pipeline components and then loads in the binary data. See here for a more detailed explanation: https://spacy.io/usage/processing-pipelines#pipelines

That said, you can do this yourself and then use the [`nlp.to_bytes`](https://spacy.io/api/language#to_bytes) and [`nlp.from_bytes`](https://spacy.io/api/language#from_bytes) methods:

```python
nlp = spacy.load("en_core_web_sm")
meta = nlp.meta
bytes_data = nlp.to_bytes()

# Restore the nlp object from the meta and the bytes data
# 1. Initialize blank language class
nlp = spacy.blank(meta["lang"])
# 2. Initialize the pipeline
for pipe_name in meta["pipeline"]:
    pipe = nlp.create_pipe(pipe)
    nlp.add_pipe(pipe)
# 3. Load in the binary data
nlp.from_bytes(bytes_data)
```
