### ISSUE TITLE
Cannot load any other models except "en_core_web_sm"

### ISSUE THREAD

**Issue by Jordan9675** [explosion/spaCy#3844]
## How to reproduce the problem

I installed spacy and the different models by following the instructions provided in the website e.g `pip install -U spacy`, `python -m spacy download en_core_web_lg` or `python -m spacy download en_core_web_sm` but the only model I can load is the en_core_web_sm one, when loading the others, I obtain the following error

```bash
OSError: [E050] Can't find model 'en_core_web_md'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```

I'm kind of a beginner and I tried to check where the models have been installed and they are all located in the same subfolder "site-packages" within python3.6, lib and finally anaconda3

## Info about spaCy

* **spaCy version:** 2.0.13
* **Platform:** Darwin-18.6.0-x86_64-i386-64bit
* **Python version:** 3.6.5
* **Models:** en

* Operating System: macOS Mojave 10.14.5 
* Python Version Used: 3.6.5 
* spaCy Version Used: 2.0.13
* Environment Information: Anaconda

Thanks for the help !

**Comment by Jordan9675** [comment]
My bad, I finally found a way to load them having resort to 

```
import en_core_web_lg
nlp = en_core_web_lg.load()
```
 However, I am facing another problem as I cannot load models from other languages by proceeding the same way. After running a `python -m spacy download fr_core_news_sm`, I ran : 

```
import fr_core_news_sm
nlp= fr_core_news_sm.load()
```

Which returned Import Error: [E048] Can't import language fr from spacy.lang: cannot import name 'QUOTES'

The same is happening with German and the "de_core_news_sm" model.

Thanks for the help !

**Comment by BreakBB** [comment]
Have you had a look at the [Quickstart](https://spacy.io/usage/models#quickstart)? Basically spaCy comes with 4 pretrained models for English as you can read [here](https://spacy.io/models/en).

And you have to install the one you want to load. So when you want to use the `en_core_web_md` model then you have to run `python -m spacy download en_core_web_md`.

Are you sure you are installing the models in the same environment where you are trying to load them?

**Comment by Jordan9675** [comment]
Hey @BreakBB, thanks for the answer !

As I said in my answer to myself, I found a way to load the 4 pretrained models that I installed separately by running another lines of code. 

However, the problem now is that when I repeated the same steps as for the english pretrained models but with the German and French one, I cannot load any models as it is returning the previously mentioned error "Error: [E048] Can't import language fr from spacy.lang: cannot import name 'QUOTES'" :/

**Comment by BreakBB** [comment]
It still is strange that you can't load in the normal way (`nlp = spacy.load("en_core_web_sm")`)...

Is it possible for you to update spaCy and try again?

**Comment by Jordan9675** [comment]
I've updated spaCy and I've run `python -m spacy validate`.

This told me that I had the models in version 2.1.0 which was not able with my spaCy version, I did revert to 2.0.0 as proposed and now, I cannot load the models anymore, neither by the normal way nor by the following method

```
import fr_core_news_sm
nlp= fr_core_news_sm.load()
```

**Comment by BreakBB** [comment]
Okay so now the installation seems to be totally broken >_>

Do me favor and try from zero in a new environment with the following steps:

1. create a new folder
2. create a virtual environment using `python -m venv .env`
3. activate the env with `source .env/bin/activate`
4. install spacy with `pip install -U spacy` (or `conda install -c conda-forge spacy` for conda`)
5. install the en model with `python -m spacy download en_core_web_sm`
6. create a .py file
7. load the spacy model with:

```python
import spacy
nlp = spacy.load("en_core_web_sm")
```

**Comment by Jordan9675** [comment]
I will do so as other people also advised me to work with virtual environments.

Will come back later to keep you updated !

Thanks for the much appreciated help !

**Comment by ines** [comment]
Yep, I agree with @BreakBB's analysis – it's very likely you accidentally ended up in a messy environment state, which can be quite frustrating. Usually, the best solution is to just start from scratch with a clean environment. Once you're using virtual environments, problems like this will also be easier to deal with: if something goes wrong, just delete your env and start again 🙂
