### ISSUE TITLE
Is it possible to use en_vectors_web_lg in conjunction with en_core_web_lg?

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#3848]
I wanted to know if it is possible to begin training an NER model starting from one of the pre trained models like en_core_web_lg but provide the larger word vectors model from en_vectors_web_lg. 

According to this post, it is

https://github.com/explosion/spaCy/issues/2724#issuecomment-420296570

However when I look at the documentation for spacy.load() method, there is no mention of an options called 'vocab'.

https://spacy.io/api/top-level#spacy.load

**Comment by BreakBB** [comment]
Yes, it is possible. `spacy.load` has an `**override` parameter and leads to the instanziation of the `Language` class (which has the `vocab` parameter). So you can use what honnibal already stated in #2724:

```python
nlp = spacy.load('en_core_web_lg')
spacy.load('en_vectors_web_lg', vocab=nlp.vocab)
```
