### ISSUE TITLE
Mixture in results when using built-in parser & custom one

### ISSUE THREAD

**Issue by agombert** [explosion/spaCy#3849]
Hello,

I've just found out a really weird result when creating a weird pipeline. The idea was to use the built-in spaCy parser to get some results and do my own parsing to get other results. But when I combine the two parsers, I managed to get a mixture or results (label from first parser in pipeline are present in the final parsing labels, but they don't share any label but the ROOT one). 

## How to reproduce the behaviour

1st I load my parser from the disk and load the big spanish corpus.

```python
nlp = spacy.load('es_core_news_md', disable=['ner'])
parser_ = DependencyParser(nlp.vocab)
parser_.from_disk('path/to/my/own/parser')
nlp.add_pipe(parser_, name='my_own_parser', first=True)
nlp.pipe_names
```

2nd I compute the dependencies to check if I get my results:

```Python
doc = nlp('Pienso que estamos en Barcelona y no en Madrid, pero es raro este tiempo')
[(token, token.dep_) for token in doc], [token.dep_ for token in parser_(doc)]
```

Output (1st is the results from the pipeline, 2nd the parser only):

``` output
(['ROOT', 'mark',  'dep',  'case',  'ccomp',  'cc',  'conj',  'case',  'nmod',  'dep',
  'cc', 'cop',  'conj',  'det',  'nsubj'],
 ['ROOT',  'dep',  'dep',  'dep',  'dep',  'dep',  'dep',  'dep',  'dep',  'dep',
  'dep', 'dep',  'dep',  'dep',  'dep'])
```

So you can see that I got dep in the first one, whereas normally when you only the built-in parser you should get:

```output
['ROOT', 'mark', 'cop', 'case', 'ccomp', 'cc', 'conj', 'case', 'nmod', 'punct', 
'cc', 'cop', 'conj', 'det', 'nsubj']
```

I also add the code I used to train my parser, maybe the bug comes from there:

```python
nlp = spacy.blank('es')
nlp.vocab = spacy.load('es_core_news_md', disable=['tagger', 'parser', 'ner']).vocab
parser = nlp.create_pipe("parser")
nlp.add_pipe(parser, first=True)

TRAINING_DATA = list(srsly.read_jsonl(join(PATH_TO_TRAIN, '{}.jsonl'.format(data_train))))
TRAINING_DATA = [(train['text'], {'heads': [train['heads'][str(i)] for i, key in enumerate(train['heads'])],
                                              'deps': [train['deps'][str(i)] for i, key in enumerate(train['deps'])]}) for train in TRAINING_DATA]

for _, annotations in TRAINING_DATA:
    for dep in annotations.get("deps", []):
        parser.add_label(dep)
    optimizer = nlp.begin_training()

for itn in range(epochs):
    random.shuffle(TRAINING_DATA)
    losses = {}
    batches = minibatch(TRAINING_DATA, size=batch_size)
    for batch in batches:
        texts, annotations = zip(*batch)
        nlp.update(texts, annotations, sgd=self.optimizer, losses=losses)
```

## Your Environment
```
Linux-4.9.0-7-amd64-x86_64-with-debian-buster-sid
Python 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 09:07:38) 
[GCC 7.3.0]
NumPy 1.16.4
SciPy 1.3.0
spacy 2.1.4
gensim 3.7.2
FAST_VERSION 1
```

**Comment by honnibal** [comment]
There's not really a great way to make this work at the moment, because the parser writes to fixed attributes on the `Doc` object, and there's only space for one set of analyses. What you should do is subclass the `DependencyParser` class and overwrite the `set_annotations` method. This will let you store your parse information in extension attributes, and then the normal parser can run afterwards.

**Comment by agombert** [comment]
Yeah actually, it works really well ! thank you very much!
