### ISSUE TITLE
Problem upgrading to version 2.1.4 via conda-forge

### ISSUE THREAD

**Issue by Fourthought** [explosion/spaCy#3851]
## Problem
I have been trying to upgrade to version 2.1.4 using conda-forge, however, without success, i only seem to be able to reach version 2.0.12. Would you be able to assist please?

And keep up the great work!

## How to reproduce the problem
Using command: conda install -c conda-forge spacy 

## Environment info
spaCy version: 2.0.12
Platform: Windows-10-10.0.17763-SP0
Python version 3.7.1

**Comment by Fourthought** [comment]
## Solved!

After upgrading to Python 3, was installing using pip.

If you have the same problem use pip3 installer: pip3 install --user spacy

**Comment by ines** [comment]
Thanks for updating! It's still a bit strange – but maybe conda just didn't have wheels available for your platform? You can see the available files here: https://anaconda.org/conda-forge/spacy/files

**Comment by Fourthought** [comment]
Thank you Ines. Looking forward to a great conference in a couple of weeks. Hopefully, we'll get a chance to meet.

Steve
