### ISSUE TITLE
Import error 'msgpack' 

### ISSUE THREAD

**Issue by GladiatorX** [explosion/spaCy#3854]
## How to reproduce the problem

Error message pop's up as soon as I import spacy , it was working fine till yeasterday
```bash
"C:\Users\XXX\Anaconda3\envs\tf_gpu\lib\site-packages\spacy\util.py", line 27, in <module>
from thinc.neural._classes.model import msgpack
ImportError: cannot import name 'msgpack' 
```

## Your Environment

* Operating System: Windows 10 64
* Python Version Used: 3.6.8
* spaCy Version Used: 
* Environment Information: conda

**Comment by ines** [comment]
Did you reinstall spaCy or upgrade it? It looks like you might have ended up with conflicting installationds and dependencies – for example, the latest version of spaCy, but an older version of its dependency, Thinc. In cases like this, it often helps to just start out with a clean environment and reinstall from scratch.

**Comment by GladiatorX** [comment]
Anyways reinstalling the latest version worked.
