### ISSUE TITLE
I need Chatbot Structure

### ISSUE THREAD

**Issue by sepidehamiri** [explosion/spaCy#3857]
I have a chatbot project that I want to use spacy library. I have several questions and answers that I want to train questions and then find the answer by asking the similar question. Is there a full and useful tutorial for this job?
thank you

## Your Environment

* **spaCy version:** 2.1.4
* **Platform:** Linux-4.15.0-51-generic-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.6.8
* **Models:** en

**Comment by ines** [comment]
While spaCy can be used to power conversational applications like chatbots, it’s not designed specifically for chatbots, and only provides the underlying text processing capabilities.

If you're just getting started, I'd suggest taking a lot at Rasa (which also lets you use spaCy under the hood): https://rasa.com
