### ISSUE TITLE
pretrain with -t2v to resume overwrites existing weight files

### ISSUE THREAD

**Issue by BreakBB** [explosion/spaCy#3859]
## How to reproduce the behaviour
Using the same output directory for a continued run (`-t2v`) of `pretrain` will overwrite existing weight files, since the counting of `epoch` begins at 0 again, even though you might use a weight file which was created after 100 iterations. Then [_save_model](https://github.com/explosion/spaCy/blob/81c12640ab4f16ad2a9c718416f32409d0c457d2/spacy/cli/pretrain.py#L139) saves the next epoch as `model0.bin` instead of `model101.bin`.

## Your Environment
* Operating System: Windows 10
* Python Version Used: 3.7.3
* spaCy Version Used: latest master commit

## Possible solution
This should either be added to the docs or maybe some useful information is included in the weight file. Trying to parse the epoch from the `-t2v` value is not a good idea I think.

**Comment by honnibal** [comment]
This is a good point. I do find the idea of reading the epoch from the filename tempting though, since these filenames are written by spaCy into the directory.

Perhaps we could have an argument that lets you specify the epoch to start counting from, and infer it by default if the `-t2v` argument is set?

**Comment by BreakBB** [comment]
I don't really see a reason to rename a weight file after it's creation (from the user perspective). But your suggested argument would allow it without a drawback.

What if the user doesn't add this `epoch-start` (just an idea) argument and the file doesn't match the `modelN.bin` pattern? I think spaCy should raise an error to prevent overwriting existing files and give a hint to the new argument.
