### ISSUE TITLE
Rule matcher example doesn't match

### ISSUE THREAD

**Issue by dataframing** [explosion/spaCy#3862]
Hi,

I noticed that an example for the `Matcher` doesn't seem to produce what the documentation suggests it should. Specifically, the following code block is expected to invoke the `add_event_ent` callback once the `Google I/O` pattern is matched (I've added two inline print statements for clarity): 

```python
import spacy
from spacy.matcher import Matcher
from spacy.tokens import Span

nlp = spacy.load("en_core_web_sm")
matcher = Matcher(nlp.vocab)

def add_event_ent(matcher, doc, i, matches):
    # Get the current match and create tuple of entity label, start and end.
    # Append entity to the doc's entity. (Don't overwrite doc.ents!)
    match_id, start, end = matches[i]
    entity = Span(doc, start, end, label="EVENT")
    doc.ents += (entity,)
    print(entity.text)

pattern = [{"ORTH": "Google"}, {"ORTH": "I"}, {"ORTH": "/"}, {"ORTH": "O"}]
matcher.add("GoogleIO", add_event_ent, pattern)

doc = nlp(u"This is a text about Google I/O.")
print([t.text for t in doc])
# ['This', 'is', 'a', 'text', 'about', 'Google', 'I', '/', 'O.']

matches = matcher(doc) # <<< Note: this does not invoke `print(entity.text)`
print(matches)
# []
```

However, it seems like (at least, on `en_core_web_sm` and `en_core_web_md` models) the input text is tokenized such that the trailing period is included with the `O`, which is outside of the rule's pattern.

Assuming it was a typo, I tried removing the period and spaCy raised a Cython error on `Span` initialization:

```pytb
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-25-cc1c83c2de13> in <module>
     24 print(f"Tokens: {[t.text for t in doc]}")
     25 
---> 26 matches = matcher(doc)
     27 print(f"Matches: {matches}")

matcher.pyx in spacy.matcher.Matcher.__call__()

<ipython-input-25-cc1c83c2de13> in add_event_ent(matcher, doc, i, matches)
     13     # Append entity to the doc's entity. (Don't overwrite doc.ents!)
     14     match_id, start, end = matches[i]
---> 15     entity = Span(doc, start, end, label="EVENT")
     16     doc.ents += (entity,)
     17     print(entity.text)

span.pyx in spacy.tokens.span.Span.__cinit__()

TypeError: an integer is required
```

I think it may just be that the `EntityRecognizer` picks up `Google I/O.` as a `PRODUCT` entity type, and the Matcher doesn't allow for overlapping entity types. In a fresh environment:

```python
import spacy

nlp = spacy.load("en_core_web_sm")
doc = nlp(u"This is a text about Google I/O.")
print([(ent.text, ent.label_) for ent in doc.ents])
# [('Google I/O.', 'PRODUCT')]
```

I tried looking around previous issues and #3287 seems to be the closest issue, to which [this commit](https://github.com/explosion/spaCy/commit/38e4422c0db522e23c86728824ae09966d4ad14c) aimed to resolve. Sorry if this has already been resolved!

## Which page or section is this issue related to?

https://spacy.io/usage/rule-based-matching#on_match

**Comment by BreakBB** [comment]
I can reproduce your issue with the latest spaCy commit in some way.

With `"This is a text about Google I/O."` I get `"Google I/O."` as `"ORG"`, just as you do.
However if I remove the trailing period I get "`Google"` as `"ORG"` before running into:

```python
ValueError: [E103] Trying to set conflicting doc.ents: '(5, 6, 'ORG')' and '(5, 9, 'EVENT')'. A token can only be part of one entity, so make sure the entities you're setting don't overlap.
```

That confirms your assumption that overlapping entities are not allowed just as [the docs}(https://spacy.io/usage/rule-based-matching#on_match) you linked:

> A very similar logic has been implemented in the built-in EntityRuler by the way. It also takes care of handling overlapping matches, which you would otherwise have to take care of yourself.

I can get the `on_match` executed when using a blank model:

```python
import spacy
from spacy.matcher import Matcher
from spacy.tokens import Span

nlp = spacy.blank("en")
matcher = Matcher(nlp.vocab)


def add_event_ent(matcher, doc, i, matches):
    # Get the current match and create tuple of entity label, start and end.
    # Append entity to the doc's entity. (Don't overwrite doc.ents!)
    match_id, start, end = matches[i]
    entity = Span(doc, start, end, label="EVENT")
    doc.ents += (entity,)
    print(entity.text)  # prints Google I/O


pattern = [{"ORTH": "Google"}, {"ORTH": "I"}, {"ORTH": "/"}, {"ORTH": "O"}]
matcher.add("GoogleIO", add_event_ent, pattern)
doc = nlp(u"This is a text about Google I/O")
matches = matcher(doc)
```

So the whole issue seems to be related to #3052 with inaccurate models/predictions.
