### ISSUE TITLE
NER differing results between code and displaCy Named Entity Visualizer

### ISSUE THREAD

**Issue by rshahrabani** [explosion/spaCy#3866]
Hi,

I'm getting differing results in NER between code and displaCy.  Below is the snippet of code used.

```python
text = "Navistar International Corporation (NYSE: NAV) today announced second quarter 2019 net loss of $48 million, or $0.48 per diluted share, compared to second quarter 2018 net income of $55 million, or $0.55 per diluted share."

nlp = spacy.load("en_core_web_lg")
doc = nlp(text)
print([e.text for e in doc.ents])

#the above print returns:
#['Navistar International Corporation', 'NYSE', 'NAV', 'today', 'second quarter 2019', '$48 million', '0.48', '$55 million', '0.55']

#whereas displaCy returns:
#['Navistar International Corporation', 'NYSE', 'NAV', 'today', 'second quarter 2019', '$48 million', '0.48', 'second quarter 2018', '$55 million', '0.55']

#displayCy correctly recognizes 'second quarter 2018' as a DATE whereas the code does not.
```

Not sure if this is a bug or the code is incorrect.

Thanks.

## Info about spaCy

* **spaCy version:** 2.1.4
* **Platform:** Windows-10-10.0.17134-SP0
* **Python version:** 3.7.3
* **Models:** en

**Comment by ines** [comment]
By "displaCy", do you mean the [displaCy demo here](https://explosion.ai/demos/displacy)? Note that the demo currently uses v2.0.x of spaCy and the old models. (Sorry we haven't updated this yet – it's on our todo list!) 

So the results may differ from the results produced by the v2.1.x models. Overall, the new models should be more accurate – but it also means that they can make different mistakes. When you compare the results, also double-check that you're running the same models. The `lg` model may produce different predictions than the `sm` model, and so on.

**Comment by rshahrabani** [comment]
Hi,

I was referring to the displayCy Named Entity Visualizer demo here: https://explosion.ai/demos/displacy-ent.  You are correct, the code is using v2.1x models (am using the lg model always).

What can we do about the missing entities, do I need to update the model and train the NER or is this an easy fix in spaCy? (I have more examples - should I post them here?)

Thanks.

**Comment by ines** [comment]
Well, I think what's happening here is that the new models are just different, so they make different mistakes. Overall, they're more accurate than the previous models – but it doesn't mean they're necessarily more accurate on your data or on a very specific example. 

But if you have examples and correct entity annotations, you can always update the model with more examples of the entities it's missing. You could probably also automate this: run the spaCy v2.0 models over your data, extract the correct entities and then update the v2.1 model with that data.
