### ISSUE TITLE
Invalid noun_chunks resulted in some specific cases

### ISSUE THREAD

**Issue by ZeeshanA1i** [explosion/spaCy#3867]
## How to reproduce the behaviour

**import spacy
nlp = spacy.load('en_core_web_md')**

_expected noun_chunks are 'a battle' and 'casualties'_
**for chunk in nlp('After a battle casualties are usually heavy.').noun_chunks: print (chunk)**
a battle casualties

_expected noun_chunks are 'a young age', 'children', 'who', and 'them'_
**for chunk in nlp("From a young age children learn to ostracize those who aren't like them.").noun_chunks: print (chunk)**
a young age children
who
them

_expected noun_chunks are 'a doubt', 'memories', and 'my past life'_
**for chunk in nlp("Those were without a doubt memories from my past life.").noun_chunks: print (chunk)**
a doubt memories
my past life

When there is no comma after a prepositional phrase at the start of the sentence or when there are no commas separating a prepositional phrase in between a sentence, spacy confuses the noun phrase of the prepositional phrase and that of the subject or so.

## Your Environment

* Operating System: 64 Bit
* Python Version Used: 3.6
* spaCy Version Used: 2.1.6
* Environment Information: ThinkPad E580 i7-8550U @1.80 GHz

**Comment by ZeeshanA1i** [comment]
>>> sentence = "Cancer is not one but more than hundred distinct diseases."
>>> for chunk in nlp(sentence).noun_chunks: print (chunk)
... 
Cancer
one but more than hundred distinct diseases

**Comment by ines** [comment]
Merging this as #3052, as this seems to come down to the underlying predictions.
