### ISSUE TITLE
Sentence is split into two after an abbreviation

### ISSUE THREAD

**Issue by ZeeshanA1i** [explosion/spaCy#3868]
## How to reproduce the behaviour

```
>>> for token in nlp("Today match is Pakistan v.s. India."): print (token.text)
... 
Today
match
is
Pakitan
v.s
.
India
.
>>> 
```

## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by ines** [comment]
The problem here is that `v.s.` currently isn't a tokenizer exception, so it's split into two tokens: `["v.s", "."]`. This also makes the parser analyse it as two sentences.

You can adjudt this by adding a special case rule to the tokenizer: https://spacy.io/usage/linguistic-features#special-cases
