### ISSUE TITLE
Problem with contractions It's

### ISSUE THREAD

**Issue by nartz** [explosion/spaCy#387]
I am having trouble with the contraction "It's", as i can't seem to get the word/lemma "is"/"be" for the 's part of the contraction:

```
[t.lemma_ for t in nlp(u"It's not my fault")]
[u'it', u"'", u'not', u'my', u'fault']
i.e.
nlp(u"It's not my fault")[1].lemma_
-> u"'"
```

I would expect this lemma to be 'be' (infinitive of 'is'). I am wondering if this is a bug, or just not the default behavior?
I.e. i would expect it to yield the same results as:
 [t.lemma_ for t in nlp(u"It is not my fault")]
[u'it', u'be', u'not', u'my', u'fault']

Thanks!

**Comment by ines** [comment]
Closing this and merging it with #401 since it's related to the same problem – this will hopefully be fixed very soon.
