### ISSUE TITLE
Losses vary across runs despite fix_random_seed()

### ISSUE THREAD

**Issue by chssch** [explosion/spaCy#3870]
## How to reproduce the behaviour

```
import spacy

spacy.util.fix_random_seed()

nlp = spacy.blank("en")

ner = nlp.create_pipe("ner")
ner.add_label("TEST")
nlp.add_pipe(ner)

losses = {}
nlp.begin_training()

for i in range(10):
    
    nlp.update(
        ["test"],  # batch of texts
        [{"entities": [(0, 4, "TEST")]}],  # batch of annotations
        losses=losses,
    )
    print(losses)
```

I get different losses every time I run the code (only on first iteration it stays the same). I would expect that with the seed settings, the losses should stay stable?

Related
https://github.com/explosion/spaCy/issues/3182#issue-401435816
(It works in this example, because it is stable for the first iteration)

## Info about spaCy

* **spaCy version:** 2.1.4
* **Platform:** Linux-4.15.0-45-generic-x86_64-with-Ubuntu-16.04-xenial
* **Python version:** 3.6.7

**Comment by honnibal** [comment]
Thanks, it does look like there's a bug here. I'm quite puzzled though -- I'm not sure what I could've broken.

**Comment by honnibal** [comment]
One theory: `array.max()` and `array.argmax()` might not always be deterministic? If not, we'd get different gradient calculations.

**Comment by chssch** [comment]
I might have tracked it down:

The seed for the HashEmbed seems to be always different:
https://github.com/chssch/thinc/blob/master/thinc/neural/_classes/hash_embed.py#L55

The parameter is not recognized in `__init__` and just set to the object-id
https://github.com/chssch/thinc/blob/master/thinc/neural/_classes/hash_embed.py#L37

My current Hotfix looks like this at for `Tok2Vec`:
https://github.com/explosion/spaCy/blob/master/spacy/_ml.py#L322

```
        norm = HashEmbed(width, embed_size, column=cols.index(NORM), name="embed_norm")
        norm.seed = 23

        if subword_features:
            prefix = HashEmbed(
                width, embed_size // 2, column=cols.index(PREFIX), name="embed_prefix"
            )
            prefix.seed = 23
            suffix = HashEmbed(
                width, embed_size // 2, column=cols.index(SUFFIX), name="embed_suffix"
            )
            suffix.seed = 23
            shape = HashEmbed(
                width, embed_size // 2, column=cols.index(SHAPE), name="embed_shape"
            )
            shape.seed = 23
```

**Comment by chssch** [comment]
For documentation, if somebody else is running into the problem:  I was just wondering why sometimes the problem occurs and sometimes (e.g. if I use Prodigy) I get stable results. The answer is clear now. If you run the training in the same Python session (like a Notebook / IPython) the `Model.id` isn't reinitialized and you get different hash embeddings.

Workarounds: always run a fresh execution (e.g. restart script / kernel) or initialize the Model.id before running the training: `thinc.neural._classes.model.Model.id = 0`

To eventually fix this one solution could be to draw the hash seed in thinc from the random generator? I'm not 100% sure about the model serialization though, if it's implicit serializing the seed over Model.id at the moment.
