### ISSUE TITLE
Warning:Unname vectors

### ISSUE THREAD

**Issue by ZHUchaojun** [explosion/spaCy#3871]
## Your Environment

* Operating System: ubuntu18.04
* Python Version Used:python3.6
* spaCy Version Used:2.0.18
* Environment Information: numpy==1.16.2, scikit-learn==0.20.3

When I training en_core_web_sm model, I got this error. Anyone can tell me how to fix this warning and tell me it's has any influence in my model. Think you very much!

**Comment by honnibal** [comment]
Can you try again with v2.1.4? I think it should be fixed.
