### ISSUE TITLE
NER recall / precision balance

### ISSUE THREAD

**Issue by RonRademaker** [explosion/spaCy#3872]
## Feature description
We use spacy on a corpus with 30+ custom entities. User feedback is telling us we're doing well on precision, but users are expecting better recall. It would be very good if we'd have some parameters to tune the ner component to be better at recall (or precision for cases where precision is more important).

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
If so, we will tag it as [`project idea`](https://github.com/explosion/spaCy/labels/project%20idea) so other users can take it on.
I don't think so

**Comment by honnibal** [comment]
This isn't so easy to do with the current model. You could try using the beam search, but out-of-the-box it'll give worse results, and you'll have to train it in beam mode for a while before it starts to improve. There's some example code in issues --- I'm a bit reluctant to reproduce it as I think it's probably not the best solution.

I think you'll be best off just trying to collect more examples with the false negatives, or possibly upsampling the training data with more entities. If you can build a training corpus with higher coverage, you should be able to improve the recall. You can also try adding rules for some of the most common missed entities, using the `EntityRuler`.
