### ISSUE TITLE
Understanding the implementation of token.prob

### ISSUE THREAD

**Issue by armsp** [explosion/spaCy#3874]
Wanted to understand how the output of `token.prob` is implemented.

I am looking for something that would tell me how frequently(or how popular is a word in everyday usage) is a particular word used in English. `toke.prob` looked promising.
For e.g. _translucent_, _gossamer_ and _diaphanous_ can be used interchangeably in the sentence: _The clouds moved like (diaphanous/gossamer/translucent) folds in a gentle breeze._
According to google, the usage statistics varies in descending order as `translucent -> gossamer -> diaphanous`.
If I construct these 3 sentences and get the corresponding token probabilities then I get the following -
```
import spacy
nlp = spacy.load('en_core_web_md')
s1 = 'The clouds moved like diaphanous folds in a gentle breeze.'
s2 = 'The clouds moved like gossamer folds in a gentle breeze.'
s3 = 'The clouds moved like translucent folds in a gentle breeze.'
s_list = [s1, s2, s3]
for s in s_list:
  doc = nlp(s)
  for token in doc:
    print(token.orth_, token.prob)
```
Output -
```
diaphanous -18.54680633544922
gossamer -17.05768585205078
translucent -13.898991584777832

```
This may NOT be the intended use of `token.prob`. The implementation details could help or maybe the authors could comment on this usage.

**Comment by armsp** [comment]
Hello authors, any clarifications would be very helpful. I can then help with editing the docs too.

**Comment by honnibal** [comment]
The `token.prob` attribute provides the log unigram probability, estimated on frequency counts from the Reddit corpus. The frequency counts were smoothed using the simple Good-Turing technique. The implementation for this can be found in the `preshed.counts` module.

So your `token.prob` values there do actually match up with the usage statistics. The prob of an unknown word gets returned as -20, so diaphanous is one of the rarest words in the vocab, while translucent is much more common.
