### ISSUE TITLE
NER consistently missing several organizations

### ISSUE THREAD

**Issue by MrEricL** [explosion/spaCy#3877]
I'm updating the NER with new data (about 2k more sentences) using existing tags. However when examining what the model missed with the manual annotation, there are a few ORGs that the model consistently seems to miss despite multiple examples in those sentences. Similar looking ORGs don't seem to suffer from the same issue. 

Is there a way for me to fix this without going into the over fitting territory?

**Comment by ines** [comment]
The most straightforward way would probably be to add a rule-based layer on top that handles the edge cases the model fails on. The [`EntityRuler`](https://spacy.io/usage/rule-based-matching#entityruler) lets you add token-based or exact string patterns and can be plugged into the pipeline before or aftert the statistical named entity recognizer. It also serializes to a JSON file and is loaded back in automatically when you load your model. So you get pretty much the same NER experience. 

You could even do this for other words that you know are *always* a certain entity. Augmenting the results like that can potentially give you a huge boost in accuracy on your specific domain at a very low cost – and without having to mess with the statistical model and potentially causing unintended side-effects. Also see the docs on [combining models and rules](https://spacy.io/usage/rule-based-matching#models-rules) for more complex examples.
