### ISSUE TITLE
Spacy Token parent issue

### ISSUE THREAD

**Issue by asarmohd** [explosion/spaCy#3881]
## How to reproduce the behaviour

Run Spacy dependency parsing for the above sentence using the large module.

Whenever we try to find token which has simillar to some other token in the sentence wrong parent is getting fetched.

```python
text = "The increase in non-cash adjustments was primarily due to a " \
"$26.0 million increase in stock-based compensation as a result of increase in headcount, $15.9 million **amortization** of issuance cost "\
"related to convertible notes, and $7.1 million increase in **amortization** of deferred sales commission and depreciation and **amortization**."
nlp = spacy.load("en_core_web_lg")
doc=nlp(str(text))

print(doc[55].text)

print([x.text for x in doc[55].ancestors])
amortization
['depreciation', 'commission', 'of', '**amortization**', 'in', 'increase', '**amortization**', 'increase', 'of', 'result', 'as', 'increase', 'due', 'was']
```

In the above output

 instead of taking parent of 2nd amortization it took parent of 1 st amortization

```python
print(doc[47].text)

print([x.text for x in doc[47].ancestors])
amortization
['in', 'increase', 'amortization', 'increase', 'of', 'result', 'as', 'increase', 'due', 'was']
```

**Comment by honnibal** [comment]
Could you try to explain the problem again? I'm having trouble following what you mean sorry.

**Comment by asarmohd** [comment]
If we same two similar tokens in the sentence .. While retrieving parent for the second token we are getting the parent of the first token.

**Comment by svlandeg** [comment]
@asarmohd : I don't think there's a problem with spaCy's output. The `.ancestors` retrieves *all* tokens the current token depends on, and it happens to be the case that the third instance of "amortization" relies (indirectly) on the second, and the second on the first. So you do see all the same words coming back, but this is the correct behaviour.

You can check the parse [with this displacy demo](https://explosion.ai/demos/displacy?text=The%20increase%20in%20non-cash%20adjustments%20was%20primarily%20due%20to%20a%20%2426.0%20million%20increase%20in%20stock-based%20compensation%20as%20a%20result%20of%20increase%20in%20headcount%2C%20%2415.9%20million%20amortization%20of%20issuance%20cost%20related%20to%20convertible%20notes%2C%20and%20%247.1%20million%20increase%20in%20amortization%20of%20deferred%20sales%20commission%20and%20depreciation%20and%20amortization.&model=en_core_web_lg&cpu=1&cph=1).
