### ISSUE TITLE
Retokenizer.split old documentation?

### ISSUE THREAD

**Issue by gorqkop** [explosion/spaCy#3885]
I'm trying to implement Retokenizer.split in my project as noticed [here](https://spacy.io/api/doc#retokenizer.split), but noticed that even given example not works. It gives 2 errors:
- split() has no attribute heads;
- 'spacy.tokens.token.Token' object has no attribute 'start_char'.

Could you please provide working example in documentation.

**Comment by ines** [comment]
I'm not sure which code you're running (and where the `start_char` comes from), but if I run the code examples with the latest version of spaCy (v2.1), it works as expected for me:

```python
import spacy

nlp = spacy.load("en_core_web_sm")
doc = nlp(u"I live in NewYork")
with doc.retokenize() as retokenizer:
    heads = [(doc[3], 1), doc[2]]
    attrs = {"POS": ["PROPN", "PROPN"],
             "DEP": ["pobj", "compound"]}
    retokenizer.split(doc[3], ["New", "York"], heads=heads, attrs=attrs)
```

Also see the examples here, which you can run in your browser: https://spacy.io/usage/linguistic-features#retokenization

As mentioned in the docs, note that the `Retokenizer` requires spaCy v2.1+.

**Comment by gorqkop** [comment]
Thank you, version was my mistake((
