### ISSUE TITLE
Invalid noun_chunk in a specific case

### ISSUE THREAD

**Issue by ZeeshanA1i** [explosion/spaCy#3886]
## How to reproduce the behaviour

>>> sentence = "The Cleveland Chamber of Commerce is more a good-government organization than a commercial body."
>>> for chunk in nlp(sentence).noun_chunks: print (len(chunk), chunk)
... 
3 The Cleveland Chamber
1 Commerce
6 more a good-government organization
3 a commercial body
>>> 

The third noun_chunk should have been just "**a good-government organization**"; "**more**" before it is extraneous and/or not part of it.

## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by ines** [comment]
I'll merge this with your other issue in #3886!
