### ISSUE TITLE
tracking Language.pipe progress. Is batch_size mandatory?

### ISSUE THREAD

**Issue by jcrousse** [explosion/spaCy#3888]
## Description:
When trying to track the progress of the `Language.pipe` function with `tqdm`  as suggested in #2318  (also tried [progressbar2)](https://pypi.org/project/progressbar2/) it appears that the progress tracking is updated only at the end of the processing.
The below code takes about 13 seconds to run on my machine, and the tqdm progress bar "jumps" from 0 to 500 at the end of the 13 seconds.

**I can "fix" the issue by setting the option `batch_size` to 1, but then I lose in efficiency.**

If I add a custom component to track the progress (by example by printing something) the print output appears all at once at the end (if last component of the pipeline) or at the very beginning before processing the text (if first component of the pipeline).

Maybe this is the intended behaviour, but the answer to #2318 makes me think it is not.

## How to reproduce the behaviour

Took a random dataset from [here](https://www.kaggle.com/utathya/imdb-review-dataset/downloads/imdb-review-dataset.zip/1)
```python
from tqdm import tqdm
import pandas as pd
import spacy

DATASET = pd.read_csv("imdb_master.csv", 
                      encoding="latin-1",  nrows=500)["review"].values

nlp = spacy.load("en_core_web_sm")

processed_docs = []
for doc in tqdm(nlp.pipe(DATASET)):
    processed_docs.append(doc)
```

## Environment

* Operating System: Ubuntu 18.04
* Python Version Used: 3.6.8
* spaCy Version Used: 2.1.4
* Environment Information:

**Comment by ines** [comment]
The thing here is that `tdqm` or any other progress bar library can't know what's happening inside the code that's executed in the loop. So what you're seeing is the expected result of calculating the progress for a batch processing loop.

As @honnibal mentioned in #2318, the `tqdm` library just wraps a loop. When you call it around `nlp.pipe`, the loop you're wrapping are the individual batches. You can either update the progress at the start or at the end, but the progress you're getting is per batch, not per text in batch. Your analysis is correct that one way of working around this is to get the progress on a loop of individual texts instead – but processing texts is much less efficient than processing batches of texts.

If you really need to have instant progress updates for each text, another alternative would be to implement your own batch processing logic that makes the calls to the progress library whenever you need them. But I'm not 100% sure that's worth the effort. Only seeing progress updates every ~10s isn't *so* uncommon.
