### ISSUE TITLE
Tokenizer fails to initilize correctly (or different initialization behaviors)

### ISSUE THREAD

**Issue by aryehgigi** [explosion/spaCy#3892]
## How to reproduce the behaviour
This is according to the following [tokenizer initialization example](https://spacy.io/api/tokenizer#init).

import spacy
from spacy.tokenizer import Tokenizer
nlp = spacy.load("en_core_web_lg") # for example
test_case = "I don't know."
tokenizer_lame = Tokenizer(nlp.vocab)
[token for token in tokenizer_lame(test_case)] # will produce first output
tokenizer_awesome = nlp.Defaults.create_tokenizer(nlp)
[token for token in tokenizer_awesome(test_case)] # will produce second output

**First output:**
[I, don't, know.] # BAD

**Second output:**
[I, do, n't, know, .] # GOOD

**Notes:**
1. Not sure if this is the expected behavior (?), but even so, presenting both initializations as the same is misleading (IMHO).
2. I came across this when I used [spacy_conll](https://spacy.io/universe/project/spacy-conll){ @BramVanroy  } (and passed the flag is_tokenized=False), as they use the first method I posted as their tokenizer initialization step.

## Your Environment
* **spaCy version:** 2.1.4
* **Platform:** Windows-10-10.0.17134-SP0
* **Python version:** 3.6.5

**Comment by ines** [comment]
Thanks – this should probably be more clear in the docs.

In the construction example 1, we're only constructing a blank `Tokenizer` using the shared vocab. The example doesn't add any punctuation rules or tokenizer exceptions.

In the construction example 2, we're calling `English.Defaults.create_tokenizer`, which will construct the English tokenizer using the respective rules and exceptions defined in the language data.

**Comment by BreakBB** [comment]
@ines I am not sure about if there are any doc guidelines, but I could just add comments to the example code to make the difference of the construction examples clear.

**Comment by ines** [comment]
@BreakBB Yes, that sounds good! We could also add a link to the method description that points to the tokenization usage docs. Something like:

> For examples of how to construct a custom tokenizer with different tokenization rules, see the [usage documentation](https://spacy.io/usage/linguistic-features#native-tokenizers).
