### ISSUE TITLE
How to label entity positions in custom data (in paragraph form) for NER training

### ISSUE THREAD

**Issue by mrxiaohe** [explosion/spaCy#3896]
## Your Environment

* Operating System: Window 10
* Python Version Used: 3.7
* spaCy Version Used: 2.1.4
* Environment Information:

Based on https://github.com/explosion/spaCy/issues/3676, it is OK to use paragraphs as training data (each piece of training data is a paragraph), as opposed to sentences. In the example from your website, the training data can be annotated in the format below, where the indices indicate the start and end positions of a named entity.

```
train_data = [
    ("Uber blew through $1 million a week", [(0, 4, 'ORG')]),
    ("Android Pay expands to Canada", [(0, 11, 'PRODUCT'), (23, 30, 'GPE')]),
    ("Spotify steps up Asia expansion", [(0, 8, "ORG"), (17, 21, "LOC")]),
    ("Google Maps launches location sharing", [(0, 11, "PRODUCT")]),
    ("Google rebrands its business apps", [(0, 6, "ORG")]),
    ("look what i found on google! 😂", [(21, 27, "PRODUCT")])]
```

If each piece of training data is a paragraph, should I annotate the positions the same way, only now the start and end positions are with respect to the full paragraph? So for the sample data below which is a short paragraph consisting of two sentences, if I want to annotate "San Diego", the positions would be the positions in the paragraph?  

```
train_data = [
    ("It's going to rain tomorrow. I think you should bring an umbrella with you to San Diego.", [(78, 87, 'GPE')])]



Thanks!

**Comment by BreakBB** [comment]
> If each piece of training data is a paragraph, should I annotate the positions the same way, only now the start and end positions are with respect to the full paragraph?

Yes, if you want to use more than one sentence, you simply use the index of the named entity based on the position in the hole string.

Note that this format is only valid for the use in python. If you want to use the CLI you should have a look at the [JSON input format](https://spacy.io/api/annotation#json-input).
