### ISSUE TITLE
Coreference resolution for german

### ISSUE THREAD

**Issue by snape6666** [explosion/spaCy#3897]
Is there a Coreference resolution feature for german in spacy now?

I saw #820 but there only solutions for english. Is there something for german too? I am also happy about other tool suggestions.

**Comment by ines** [comment]
If you have data, you can use `neuralcoref` to train your own model. See here for details:

* https://github.com/huggingface/neuralcoref/blob/master/neuralcoref/train/training.md
* https://medium.com/huggingface/how-to-train-a-neural-coreference-model-neuralcoref-2-7bb30c1abdfe
