### ISSUE TITLE
German part-of-speech tagging

### ISSUE THREAD

**Issue by hermes-z** [explosion/spaCy#3904]
Hi, I am encountering some problems with the German POS tagger. Even though the tokenizer works correctly on \u201e and \u201c, the part-of-speech does not work.

## How to reproduce the behaviour
```
nlp = space.load('de_core_news_md')
text = "\u201eDas ist nicht gut.\u201c"
doc = nlp(text)
for tk in doc:
  print(tk.text, tk.pos_)
```

In this case, is assigned VERB and \u201c PROPN.

However, the following works as expected:
```
nlp = space.load('de_core_news_md')
text = "'Das ist nicht gut.'"
doc = nlp(text)
for tk in doc:
  print(tk.text, tk.pos_)
```

## Your Environment

* Operating System: macOS 10.14.5
* Python Version Used: 3.6.6
* spaCy Version Used: 2.1.4
* Environment Information:

**Comment by BreakBB** [comment]
This seems to be simply related to an insufficient training of the model. With "de_core_news_sm" you get "XY" for `tag_` and "X" for `pos_` of `\u201e`.

And at least the `\u201e` is tagged correctly in the following:

```python
import spacy
nlp = spacy.load('de_core_news_sm')

text = "\u201eSollen wir weiter gehen?\u201c"
doc = nlp(text)
for tk in doc:
    print(tk.text, tk.tag_, tk.pos_)

# Output
# „ $( PUNCT
# Sollen VMFIN VERB
# wir PPER PRON
# weiter ADV ADV
# gehen VVINF VERB
# ? $. PUNCT
# “ NE PROPN
```

With the "de_core_news_md" model however `\u201e` is tagged as "NOUN" for the second sentence.

**Comment by hermes-z** [comment]
Thanks for thew answer. I thought that there was a rule-based system for dealing with quotation marks in spacy, but I guess I was wrong. What is interesting is that even in your example, if you process `text2 = "'Sollen wir weiter gehen?'"` it gets it right.
Maybe a quick-and-solution would be to substitute `\u201e` and `\u201c` with `'`?

**Comment by BreakBB** [comment]
Funny enough the "en_core_web_sm" model gets all the punctuation correct.

> Maybe a quick-and-solution would be to substitute \u201e and \u201c with '?

Yes, you could easily preprocess your text to replace the quotations marks.

```python
import spacy
nlp = spacy.load('de_core_news_md')

text = "\u201eDas ist nicht gut.\u201c"

text = text .replace("\u201e", "'")
text = text .replace("\u201c", "'")

doc = nlp(text)
for tk in doc:
    print(tk.text, tk.tag_, tk.pos_)
```
