### ISSUE TITLE
Model download extremely slow and interrupted in China

### ISSUE THREAD

**Issue by piofel** [explosion/spaCy#3905]
I live in China. When I want to download the `en_core_web_sm` model, the download speed becomes below 1KB/s and then timed-out. When added `--default-timeout=3600 `option, what surprisingly works, I receive `pip._vendor.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))`, after some time passes.

**Comment by BreakBB** [comment]
You could try to get the model from github directly. You can get the "en_core_web_sm" [here](https://github.com/explosion/spacy-models/releases/tag/en_core_web_sm-2.1.0).

You simply have to extract the "en_core_web_sm" folder and the "en_core_web_sm.egg-info" folder to the "site-packages" folder where you want to use the model.

**Comment by piofel** [comment]
Thank you for your quick answer. Getting it directly was also very slow, I just asked a friend from Europe to download it for me.
