### ISSUE TITLE
German large/pretrained model

### ISSUE THREAD

**Issue by hermes-z** [explosion/spaCy#3906]
## Feature description
Would it be possible to have a de_core_news_lg model and/or a pertained German model?

**Comment by BreakBB** [comment]
Please have a look at the pinned #3052 thread

**Comment by ines** [comment]
Yes, we'd love to add larger German models in the future – but we'd want to train our own word vectors for it. We're working on a reliable pipeline for this, but we don't have that ready at the moment. In the meantime, if you have the TIGER corpus, you can train your own large German model by using FastText vectors.

Also merging this with #3056.
