### ISSUE TITLE
Evaluate NER wrong results

### ISSUE THREAD

**Issue by pika97** [explosion/spaCy#3909]
## How to reproduce the behaviour

I have annotated about 600 sentences for NER in the spacy format. 
When I run the evaluate function, on the data it shows 0 for all values except token_acc.
I tried to run it for individual sentences, it shows 100 for some ad 0 for the others. 

Function I'm using: 

```python
import spacy 
from spacy.gold import GoldParse
from spacy.scorer import Scorer 

def evaluate(ner_model,examples):
	scorer = Scorer()
	for input_,annot in examples:
		doc_gold_text = ner_model.make_doc(input_)
		gold = GoldParse(doc_gold_text,entities = annot['entities'])
		pred_value = ner_model(input_)
		scorer.score(pred_value,gold)
		return scorer.scores,gold
```

**Individual results (ie per sentence)**
_Correct (ie P =100  R=100 F=100):_
('with the assistance of the canadian red cross, city staff quickly mobilized to provide reception centres for those torontonians who were without power.', {'entities': [(115, 127, 'NORP')]})

_Incorrect(ie P=0 R=0 F= 0)_
('b   province of new brunswick preparedness, response and recovery december 2013 ice storm  after action review report   5 august 2014  final version     presented to:  mr. greg maccallum director new brunswick emergency measures organization po box 6000 364 argyle street, room 3-92 fredericton, new brunswick e3b 5h1     prepared by:  jim bruce atlantic security group inc 33 paul thomas drive dartmouth, nova scotia, b2w 6a1    0c table of contents  executive summary .', {'entities': [(17, 30, 'GPE'), (66, 90, 'EVENT'), (120, 134, 'DATE'), (168, 187, 'PERSON'), (197, 242, 'ORG'), (259, 272, 'LOC'), (17, 30, 'GPE'), (337, 346, 'PERSON'), (348, 370, 'ORG'), (407, 418, 'GPE'), (396, 405, 'GPE')]})

**Grouped results**
When I include even one of the incorrect sentences with several correct ones as part of the goldparse, it gives 0 for all values except token_acc. 

Even if the goldparse if off by one character the result changes to 0 for P,F & R.  
Eg: Predicted = (8,16,'PERSON')
      GoldParse = (7,16,'PERSON')  

Can someone please clarify why this is happening? I have gone through the code yet I don't understand why partially correct entities are being scored as 0 for P, R and F-Score.  

## Your Environment

* Operating System: Ubuntu 18.04 (Using Colab)
* Python Version Used: 3.6.8
* spaCy Version Used: 2.1.4 
* Environment Information: Running on Colab

**Comment by honnibal** [comment]
You're returning the scores for a single doc, rather than counting the scores over the whole evaluation (which is what one would normally do).

> Even if the goldparse if off by one character the result changes to 0 for P,F & R.
> Eg: Predicted = (8,16,'PERSON')
> GoldParse = (7,16,'PERSON')

That's how the evaluation metrics for the NER task are normally defined. It does make sense for most applications.

**Comment by pika97** [comment]
Despite the label being correct, the P,R & F-score are 0 because of the difference in character, I'm guessing because of white space?

Also, a single doc might contain multiple entities so there is no partial scoring?

**Comment by ines** [comment]
NER evaluation metrics typically don't consider partial results like this. The objective is to predict the correct sequence of BILUO tags over a sequence of tokens. If it's off by one character, it's wrong. And if there are no correct predictions, precision will always be 0.

That said, if you do want an additional metric that reflects overlaps between the gold parse and the predictions, you could write your own function that calculates those for the incorrect predictions.
