### ISSUE TITLE
Dependency graph labels appear upside down

### ISSUE THREAD

**Issue by urigoren** [explosion/spaCy#3917]
## How to reproduce the behaviour

The following code generates a dependecy graph visualisation, with some of the arc labels shown upside down.

See [screenshot](https://imgur.com/sXZzaL7)

> from spacy import displacy
> 
> viz = {'words': [{'text': 'Balmer', 'tag': ''},
>   {'text': 'replaces', 'tag': ''},
>   {'text': 'Gates', 'tag': ''},
>   {'text': 'at', 'tag': ''},
>   {'text': 'Microsoft', 'tag': ''}],
>  'arcs': [{'start': 0, 'end': 1, 'dir': 'left', 'label': 'nsubj'},
>   {'start': 1, 'end': -1, 'dir': 'right', 'label': 'root'},
>   {'start': 2, 'end': 1, 'dir': 'right', 'label': 'obj'},
>   {'start': 3, 'end': 4, 'dir': 'left', 'label': 'case'},
>   {'start': 4, 'end': 1, 'dir': 'right', 'label': 'obl'}]}
>   
> 
> html = displacy.render(viz,
>                            jupyter=False,
>                            style="dep",
>                            manual=True,
>                            options={"compact": True,"color": "blue",}
>                           )
> with open("bug.html", 'w') as f:
>     f.write(html)

## Your Environment

* Operating System: Win10
* Python Version Used: 3.6.7
* spaCy Version Used: spacy==2.1.4
* Environment Information:

**Comment by ines** [comment]
Sorry for only getting to this now. I initially thought this was a bug, but I think it's actually related to how the data is formatted. In your `arcs`, you're using *relative* indices and things like `'end': -1`. displaCy however expects *absolute indices*.

For instance, here's the result displaCy would internally produce for that parse:

```python
import spacy
from spacy.displacy import parse_deps

nlp = spacy.load("en_core_web_sm")
doc = nlp("Balmer replaces Gates at Microsoft")
print(parse_deps(doc))
```

```
{'words': [{'text': 'Balmer', 'tag': 'PROPN'},
  {'text': 'replaces', 'tag': 'VERB'},
  {'text': 'Gates', 'tag': 'PROPN'},
  {'text': 'at', 'tag': 'ADP'},
  {'text': 'Microsoft', 'tag': 'PROPN'}],
 'arcs': [{'start': 0, 'end': 1, 'label': 'nsubj', 'dir': 'left'},
  {'start': 1, 'end': 2, 'label': 'dobj', 'dir': 'right'},
  {'start': 2, 'end': 3, 'label': 'prep', 'dir': 'right'},
  {'start': 3, 'end': 4, 'label': 'pobj', 'dir': 'right'}],
 'settings': {'lang': 'en', 'direction': 'ltr'}}
```

<img width="751" alt="Screenshot 2019-08-20 at 15 39 51" src="https://user-images.githubusercontent.com/13643239/63352125-c7ed3880-c360-11e9-8968-6da81583c3a1.png">
