### ISSUE TITLE
Cannot increase the speed of training with cpu_count

### ISSUE THREAD

**Issue by pratapaprasanna** [explosion/spaCy#3920]
Hi all, 

I have been going using spacy and i like it but when i try to boost the speed of my training as per the suggestion in here [#1530-comment](https://github.com/explosion/spaCy/issues/1530#issuecomment-343229717) and i see the performace is not difference the code i used is as follows

```
    nlp.add_pipe(sbd)
    nlp.add_pipe(ner, last=True)
    evaluation_steps = int(config['evaluation']['evaluation_interval'])
    output_dir = config['TRAIN']['model_save_path']
    for _, annotations in train_data:
        for ent in annotations.get('entities'):
            ner.add_label(ent[2])
    other_pipes = [pipe for pipe in nlp.pipe_names if pipe != 'ner']
    with nlp.disable_pipes(*other_pipes):
        n_iter = int(config['TRAIN']['num_epochs'])
        optimizer = nlp.begin_training(cpu_count=96)
        for itn in range(n_iter):
```

Please correct me if there is any mistake in the code or approach.

## Your Environment

* Operating System: ubuntu 18.04
* Python Version Used: 3.6.8
* spaCy Version Used: 2.1.4
* Environment Information:

**Comment by BreakBB** [comment]
The comment you quote is about a pretty old version of spaCy. I can't find any use of the parameter `cpu_count` in the code, so I guess it will be simply ignored. As far as I know the new models don't support multi-trheading for the training.

You can use [multi_processing](https://github.com/explosion/spaCy/blob/master/examples/pipeline/multi_processing.py) though for processing data with an existing model.

**Comment by pratapaprasanna** [comment]
thanks @BreakBB  so is there any sample code for training a blank model for NER with multi-processing.?

**Comment by BreakBB** [comment]
Sorry for not being clear enough: With "the new models don't support multi-threading for the training" I meant the new architecture of the models. So (at least as far as I know) there is no way to use multihreading on a CPU to speed up the training with spaCy at the moment.

**Comment by honnibal** [comment]
@BreakBB is correct, currently we don't have parallel training. I'm looking forward to implementing it, but it'll take a bit of effort, and it's not the number one priority currently.

**Comment by pratapaprasanna** [comment]
@BreakBB @honnibal  Yes agreed, I think the code u shared is for inference I have a 72 core machine in aws and i want to use all the cores for my training. Is there a way i can use all the cores in training ?

If yes please let me know. 

Thanks
Pratapa.
