### ISSUE TITLE
How to use different NER models loading only one vocabulary

### ISSUE THREAD

**Issue by romlatron** [explosion/spaCy#3921]
I have a model with different NER categories, which I want to separate to optimize training results. To do so, I thought about having one Spacy model with different custom components, one for each category. The problem is, I then have to load the same vocabulary for each one of my NER components, which is pretty heavy because we use custom word vectors which take a lot of memory space (> 1Gb). I tried to load the NER models without the vectors, which raises an error. I also tried to load them with very few vocabulary, and then assign them the vocab of the original NLP model:
 
ner = spacy.load(“path/to/ner”)
nlp = spacy.load(“path/to/nlp”)
ner.vocab = nlp.vocab
 
But it didn’t seem to work so well as the last line did not affect the NER results.
Is there a way to assign the same vocabulary to every component, without loading it multiple times which takes considerably too much space in memory? I thought about redefining the EntityRecognizer object, but is it a good approach, as it won’t let me load the model without the vectors?

## Your Environment
* **spaCy version:** 2.0.18
* **Platform:** Windows-10-10.0.17134-SP0
* **Python version:** 3.6.6

**Comment by BreakBB** [comment]
You might be able to use `to_disk` and `from_disk` and exlude the vocab, instead of `spacy.load` ([the docs](https://spacy.io/api/entityrecognizer#to_disk).

Give this a try (can't test it atm):

```python
import spacy
from spacy.pipeline import EntityRecognizer

# Saving the model after training
# ner = nlp.get_pipe("ner")  # might be necessary
ner.to_disk("my/fancy/path", exclude=["vocab"])

# Loading it later for usage
nlp = spacy.load("myModel")

ner = EntityRecognizer(nlp.vocab)
ner.from_disk("my/fancy/path", exclude=["vocab"])
```

**Comment by romlatron** [comment]
The problem is that I don't get the results I had when I Ioaded the NER as a normal component of the NLP model, so everything happens as if it didn't take into account the vocabulary of my nlp model when I execute this line:

ner = EntityRecognizer(nlp.vocab)

By the way, when I completely remove the vocab for the NER directory, it shows me an error, even though I specified exclude=["vocab"]:

FileNotFoundError: [Errno 2] No such file or directory: '..\\..\\models\\textcat_model\\ner_models\\negations_model\\vocab\\strings.json'

**Comment by romlatron** [comment]
Ok, I finally found the problem. Instead of exclude=["vocab"] as a parameter, I pass vocab=False, which works fine!

**Comment by BreakBB** [comment]
I totally missed that you're not using spaCy v2.1. So it makes sense that the `exclude` parameter has no effect but you have to use `vocab=False`. Note that this is deprecated since spaCy 2.1.

Great to hear your problem is fixed!
