### ISSUE TITLE
Incorrect segmentation of a sentence into two due to capitalized tokens

### ISSUE THREAD

**Issue by ZeeshanA1i** [explosion/spaCy#3930]
## How to reproduce the behaviour

>>> for sentence in nlp("There Are Many capitalization Mistakes In This Sentence.").sents: print (sentence.text)
... 
There Are Many capitalization Mistakes
In This Sentence.
>>> 
## Your Environment

* Operating System: Windows 10 Pro 64-Bit
* Python Version Used: 3.6
* spaCy Version Used: 2.0.18
* Environment Information:

**Comment by ines** [comment]
This isn't too surprising – by default, the sentence boundaries are set by the parser and if the capitalisation is off, the parser may make mistakes. You can either fine-tune the parser on your data to make it more accurate, or use a rule-based sentence segmentation strategy like the `Sentencizer` instead: https://spacy.io/usage/linguistic-features#sbd

**Comment by ZeeshanA1i** [comment]
Isn't that a simple sentence with no other punctuation but a full stop at the end? Why does Spacy fail to recognize it as one sentence?
