### ISSUE TITLE
Cant dump utf-8 text strings in the EntityRuler

### ISSUE THREAD

**Issue by shaked571** [explosion/spaCy#3931]
Can't dump a ruler with utf-8 pattern:
```

 from spacy.pipeline import EntityRuler
        import en_core_web_md
        nlp = en_core_web_md.load()
        ruler = EntityRuler(nlp, overwrite_ents=True)
        ruler.add_patterns( {"label": "CALENDAREVENT", "pattern": [{"lower": "day"}, {"lower": "of"}, {"lower": "andalucía"}]})
       ruler.to_disk('my/path/config') # also tried with ('my/path/config', ensure_ascii=False, encoding='utf-8' 

```
==>my/path/config.jsonl:
       {"label":"CALENDAREVENT","pattern":[{"lower":"day"},{"lower":"of"},{"lower":"andaluc\u00eda"}]}

I manage to solve it using this patch:

```

 def dump_ruler_nonascii(data_path, ruler):
        path = Path(os.path.join(data_path, 'config.jsonl'))
        pattern = ruler.patterns
        with open(path, "a", encoding="utf-8") as f:
            for line in pattern:
                f.write(json.dumps(line, ensure_ascii=False) + "\n")


import en_core_web_md
nlp = en_core_web_md.load()
ruler = EntityRuler(nlp, overwrite_ents=True)
ruler.add_patterns( {"label": "CALENDAREVENT", "pattern": [{"lower": "day"}, {"lower": "of"}, {"lower": "andalucía"}]})
dump_ruler_nonascii('my/path/config', ruler)
```
==>my/path/config.jsonl:
       {"label":"CALENDAREVENT","pattern":[{"lower":"day"},{"lower":"of"},{"lower":"andalucía"}]}

## Info about spaCy

* **spaCy version:** 2.1.4
* **Platform:** Windows-7-6.1.7601-SP1
* **Python version:** 3.6.2
* Environment Information:

**Comment by BreakBB** [comment]
What error message do you get?

**Comment by BreakBB** [comment]
The problem lies in the [srsly](https://github.com/explosion/srsly) library spaCy uses for serilization adn therefore is not specific to the EntityRuler.

In [this line](https://github.com/explosion/srsly) it is:

```python
result = ujson.dumps(data, indent=indent, escape_forward_slashes=False)
```

instead of:


```python
result = ujson.dumps(data, indent=indent, escape_forward_slashes=False, ensure_ascii=False)
```

**Comment by shaked571** [comment]
I think there is a problem with path. 

But yes, the problem is there. in `srsly._json_api.py`. 
I just bypath it, not a big deal, just would be better if it was an option for users, cause it can produce annoying encoding bugs.

**Comment by honnibal** [comment]
There's actually no problem here. The text will deserialize fine when you load it back in -- it only looks strange when you view the file, but making the serialized form human-readable is not a priority.

We use the `ensure_ascii` mode so that it loads back in cleanly in both Python 2 and Python 3. Please open a new report if it actually causes problems when you deserialize.
