### ISSUE TITLE
Question: Can dependency parser use existing tokens and tags to increases accuracy?

### ISSUE THREAD

**Issue by zhunyoung** [explosion/spaCy#3936]
I've got a large amount of domain specific text. Can I use pre-defined tokens and tags to increase the accuracy of the dependency parser?

**Comment by honnibal** [comment]
You can use predefined tokens, and the predefined POS tags might be used to improve the POS tagger. But the parser doesn't currently use the POS tagger as features, so improving it won't be so straightforward.

What you could do is use the POS tags to find cases the model is getting wrong, and perhaps fix them and update the model? The process won't be so straight-forward, but it could be a way to use the resources.

**Comment by zhunyoung** [comment]
Thank you so much for your quick reply! As for updating the model, do you mean to train the existing model with some representative examples? This doesn't seem to work if I need the model to know that some multiple regular expressions should belong to certain tags.

**Comment by honnibal** [comment]
If you can express the constraints as regular expressions, you could have a sort of validation pass, where you use your regex to identify cases the tagger got wrong. You could use that process to create improved data, and use that to retrain (or just make calls to the `tagger.update()` method).
