### ISSUE TITLE
Create proper pypi packages for downloadable models and data sets

### ISSUE THREAD

**Issue by spearsem** [explosion/spaCy#3938]
## Feature description

There was an issue reported in https://github.com/explosion/spaCy/issues/1143 but the stated solution (to modify `egg-info`) is not adequate for many use cases. For example, in a lot of Python projects it is customary to automatically parse the entries of `requirements.txt` and populate the `install_requires` field in `setup.py` when building a package.

If some of the dependencies need to be specified as git URLs, it can make this process needless complicated to deal with dependency links and updating egg-info tags.

Why not build spaCy downloadable artifacts as proper installable packages? This would be especially nice because the artifact can specify the range of versions of spacy that are compatible, and then users can specify everything with pinned versions like usual in a single place, and ensure their combination of spacy and downloaded artifacts will 'just work' regardless of what type of packaging / environment situation they are working in.

Please consider changing the existing data set release procedure to build proper pypi-distributed packages (and also conda-forge to be extra awesome).

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
If so, we will tag it as [`project idea`](https://github.com/explosion/spaCy/labels/project%20idea) so other users can take it on.

**Comment by ines** [comment]
Hi! spaCy models are already regular versioned Python packages, so if you host your own PyPi index, you could already upload them there and use them like any other dependency if you want that experience.

However, it's actually not that easy for us to "just upload all models to PyPi". You can read more about it in #3536. We'll likely never be able to provide *all* models this way (due to the package sizes) and we're also concerned that shipping statistical models falls outside of the intended usage for PyPi, and may not be sustainable. The other alternative would be hosting our own warehouse and package index, but we really don't necessarily want our open source users to have to rely on our private infrastructure to use the library and download models. It'd be great to make this work, but at the moment, there doesn't really seeem to be a perfect solution. (Merging this issue with #3536 to keep things in one place.)

**Comment by spearsem** [comment]
@ines I feel this was closed without sincere consideration for the purpose of the feature request. I appreciate your perspective and realize there are additional constraints making packaging of models hard, but the current workflow where they are published as packages but not included in regular indices like pypi or conda channels is a significantly degraded user experience and makes various Python workflows much harder than they need to be.

> spaCy models are already regular versioned Python packages

I apologize if I wasn't clear, but in this use case, I am taking "regular Python package" to mean something that does not require use of a GitHub URL in requirements.txt to specify the package and version, rather something that is known to pypi and other package sources like conda channels by a name only. I'm not talking about the file layout and setup.py config to define a package, but actually just talking about the shared artifact itself existing via package name at standard package indices.

E.g. the feature I am requesting is to be able to do something like

```
pip install spacy_en_core_web_md==2.1.0
```

for example so that a package manager can consult metadata from the package index and not re-download the same package every time the way pip will do for GitHub URLs. (This is expected behavior of pip for installing from URLs, which is to say it is a degraded experience if spacy relies on URLs as the mechanism for pip installation).

Another option you could take is to have a Python interface to your `download` functionality. The fact that one needs to call spaCy with the `__main__.py` mechanism via `python -m spacy download ...` or `spacy download ...` is quite limiting. For example consider the way NLTK provides `download` as a Python function callable from Python code (without an OS system call). At least this way a running program can bootstrap the data it needs, which won't be re-downloaded if it is installed. To do the same with spaCy, you'd have to make a separate call to download outside the context of the program that is trying to bootstrap.

Given that it's not easy to make the GitHub URLs work with standard Python packaging mechanisms in setup.py, please at least consider making the download functionality callable from within a running Python script itself without a system call needed.

**Comment by spearsem** [comment]
@ines In fact, it looks like this would be quite easy to implement with the existing code from `__main__.py` .. 

```
spacy.cli.download('en_core_web_md')
```

Perhaps moving this functionality out of `cli` and into a separate downloader util would be enough. Then `cli` can just import from the downloader util and still work exactly the same way, but there can be a separately documented non-cli interface to calling the function as well, and this can be added to the top-level spaCy docs as a viable alternative.
