### ISSUE TITLE
Just an interesting discovery in the English NER model

### ISSUE THREAD

**Issue by jltchiu** [explosion/spaCy#394]
Hi,

First I wish to thank you for this wonderful toolkit, but there's an interesting discovery of it and I think it's probably relevant with your training data for NER. For some reason, "Barack Obama" always been recognized as an organization name instead of a person's name. For a person famous like him this actually surprise me a bit. Or is the training data comes from earlier time?

If there's an updated language model that I didn't know, please let me know as well, thanks!

**Comment by geovedi** [comment]
can you provide some examples?

**Comment by jltchiu** [comment]
Yes, 

For example when I printed out the parsing result with

text = unicode("Barack Obama")
toks = nlp(text)

for tok in toks:
    print(tok.orth_, tok.dep_, tok.pos_, tok.ent_type_, [t.orth_ for t in tok.lefts], [t.orth_ for t in tok.rights])


And it will shows

(u'Barack', u'compound', u'PROPN', u'ORG', [], [])
(u'Obama', u'ROOT', u'PROPN', u'ORG', [u'Barack'], [])


This will be the same even in a bigger context (A complete sentence which contains Barack Obama). Maybe you can try it on your computer but I guess it could be the same.

**Comment by geovedi** [comment]
NER system implemented here in spaCy is relying heavily on the context and not just on a single phrase. 
I'm not spaCy developer, but I'm sure this issue will be improved. 

Also, see #62.

**Comment by jltchiu** [comment]
If you want I can provide more examples with context:

(u'What', u'attr', u'NOUN', u'', [], [])
(u'is', u'ROOT', u'VERB', u'', [u'What'], [u'height'])
(u'the', u'det', u'DET', u'', [], [])
(u'height', u'nsubj', u'NOUN', u'', [u'the'], [u'of'])
(u'of', u'prep', u'ADP', u'', [], [u'Obama'])
(u'Barack', u'compound', u'PROPN', u'ORG', [], [])
(u'Obama', u'pobj', u'PROPN', u'ORG', [u'Barack'], [])

Of course there are context that will help, such as "Who is Barack Obama", and the Barack Obama's NER tag will be correct here.

Still, this is just sharing some interesting discovery, if any developer found this interesting and decided to investigate it that's good, if not, at least people knows that the model works in this way.
