### ISSUE TITLE
ENT_IOB as a token pattern key

### ISSUE THREAD

**Issue by Varun-Epi** [explosion/spaCy#3940]
## Feature description
Adding `ENT_IOB` attribute as one of the pattern key. Currently, it has not been integrated into entity ruler pipeline.

### Example
```
import spacy
from spacy.pipeline import EntityRuler

nlp = spacy.load('en')
ruler = EntityRuler(nlp, overwrite_ents=True)
pattern = [{'ENT_TYPE': 'GPE', 'OP': '+'}, {'ORTH': 'california'}]
ruler.add_patterns([{"label":'COMB', "pattern":pattern}])
```
```
print('Before Ruler')
print(nlp('Delhi New York california').ents)
Output: (Delhi, New York)
```
```
print('After Ruler')
nlp.add_pipe(ruler)
print(nlp('Delhi New York california').ents)
-- Output: (Delhi New York california,)
```
Correct Output should be **(Delhi, New York california)**

Logical answer would be to annotate only `New York california` as new entity, but here since `ENT_IOB` option is not available, it annotates all the `GPE` present in the given pattern

**Comment by honnibal** [comment]
Fair point, although the `ENT_IOB` values currently have pretty obscure semantics, which makes usability a bit difficult. The field takes a numeric value with the following interpretation:

0: Missing
1: I -- In
2: O -- Out
3: B -- Begin

**Comment by ines** [comment]
@honnibal I guess we could also have it take the strings `I`, `O` and `B` and a `0` for missing?

**Comment by honnibal** [comment]
@ines I've thought a couple of times about how to clean this up. It's pretty annoying: if we take `I`, then what about the hash code of `I`? At least 0 always corresponds to the empty string, so that's easy.

This is one of the only places in the library where we'd using a numeric encoding that's *not* the same as the string-store encoding.

**Comment by kinghuang** [comment]
Any updates on getting `ENT_IOB` added to token patterns?

I'm trying to write a pattern that will pick up and overwrite an existing entity. But, without `ENT_IOB` information, it's hard to accurately pick up all the tokens for an entity.

**Comment by svlandeg** [comment]
Happy to report that this feature will be available in the next release!
