### ISSUE TITLE
💫 Proposal: component decorator for pipeline metadata and static analysis

### ISSUE THREAD

**Issue by ines** [explosion/spaCy#3943]
As I mentioned in [our talk at spaCy IRL](https://speakerdeck.com/inesmontani/spacy-and-explosion-past-present-and-future), here's a rough proposal for enhanced pipeline component metadata.

## Overview
spaCy lets you add your own components to the pipeline that take a `Doc`, modify it and return it. You can assemble your components however you like. Their order doesn't always matter, but it can: for instance, you could write a custom lemmatizer that runs after the part-of-speech tagger, uses the tokens and part-of-speech tags and sets the `Token.lemma`/`Token.lemma_` attribute. However, your custom component will always be a black box, and there's currently no way to express that it requires the `Token.pos` and `Token.tag` attributes to be set and that it writes to `Token.lemma`. You have to know this, and make sure to add your components correctly and do your error handling in your components if necessary. It's also currently not really exposed to the user *where* many attributes are set and what they're based on. If pipeline components could define what they set and what they require, spaCy could output more helpful diagnostics.

In terms of the implementation, there's a challenge here: How do we add metadata to a component? Pipeline components need to be callables that take a `Doc`, modify it and return it. If a component is a class with a `__call__` method, adding more attributes is easy – but we don't want to require pipeline components to be classes, because the "just write a function" thing is actually pretty great.

### Advantages and use cases
* Output more details on the attributes on the `Doc` and `Token` and where in the pipeline they're set. For example, you could see that the `"parser"` component sets `Token.dep` and `Doc.sents`.
* Raise better error messages for custom components. If your custom component depends on the POS tags and they're not set, spaCy will be able to tell you this before it even runs.
* Generate pipeline overviews and visualizations of the `Doc` passing through the pipeline

### Pseudocode example implementation

```python
@component(
    assigns={"token": {"lemma": True, "_": {"extended_lemma": True}}},
    requires={"token": {"pos": True}}
)
def custom_lemmatizer(doc):
    return doc
```

| Name | Type | Description |
| --- | --- | ---|
| `assigns` | dict | Attributes set or overwritten by the component. |
| `requires` | dict | Attributes required by the component. |
| `name` ? | str | Alternative default component name. |

The above `assigns` definition means that the component will set two attributes: `Token.lemma` (and by proxy, `Token.lemma_`) and the custom [extension attribute](https://spacy.io/usage/processing-pipelines#custom-components-attributes) `Token._.extended_lemma`.

The `requires` definition means that it requires the `Token.pos` attribute to be set.

## Syntax

The above implementation was just an example to illustrate the idea. There are different ways we could structure the `assigns` and `requires` arguments.

### 1. Dict keyed by object and string attributes with boolean values

```python
assigns = {
    "token": {
        "lemma": True,
        "_": {
            "extended_lemma": True
        }
    }
}
```

👍 **Pros:** Most obvious way to represent nested values.
👎 **Cons:** Can get pretty verbose and boolean values are technically not necessary because there's no reason to use `False`.

### 2. Dict kexed by object with list of string attributes

```python
assigns = {
    "token": ["lemma"],
    "_": {
        "token": ["extended_lemma"]
    }
}
```

```python
assigns = {
    "token": ["lemma"],
    "token_": ["extended_lemma"]  # or: "token._", "token_underscore"
}
```

👍 **Pros:** Easier to read, less verbose, only includes what's needed.
👎 **Cons:** The handling of the `_` can easily get awkward and unintuitive.

### 3. Dot notation

```python
assigns = ["token.lemma", "token._.extended_lemma"]
```

👍 **Pros:** Very straightforward and closest to how a user thinks about these attributes, as they're written the same way they're accessed.
👎 **Cons:** Requires an additional helper to parse into dict representation, e.g. [something like this](https://stackoverflow.com/a/25389993/6400719).

## Implementation notes and open questions

* We do need to take the built-in and the user's annotation at face value. If a component claims that it assigns `Token.pos`, we assume that this is true. We don't actually want to go and check each token to see if the attribute is set.
* Can a component require something like `Doc.is_parsed` to be `True`? If so, how do we handle this? Requiring a flag to have a certain value is quite different from requiring attributes to be set.
* How do we implement this efficiently on the `Language` class so that we can output warnings when calling `nlp.add_pipe`? For each component, we need to be able to retrieve its left dependencies (what's in `assigns`) and then match that up with the component's `requires`.

**Comment by svlandeg** [comment]
I really like this idea of making the inner workings of the pipeline components more explicit. Also for the entity linker for instance I'd been thinking about how best to ensure that there's an entity recognizer earlier in the pipeline, or it will just crash somewhere during execution.

With respect to the different options, I'd definitely go for one which doesn't make the booleans explicit (as you said - `False` would never be used anyway). I think I have a small preference for the dot notation, you'd only have to implement a kind of parser once, while keeping the notation intuitive, short and simple for humans :-)

One other thing I was thinking about: so if you want to create the alerts/warnings when calling `nlp.add_pipe`, does that mean your pipeline will never be allowed to be in a sort of "inconsistent" state? Suppose you create your pipe by first adding the entity linker and then adding the ner in front of it, that would throw an error in between? I think that may be fine, just something to think about that this may break current code that actually does work correctly...

**Comment by ines** [comment]
> so if you want to create the alerts/warnings when calling nlp.add_pipe, does that mean your pipeline will never be allowed to be in a sort of "inconsistent" state? Suppose you create your pipe by first adding the entity linker and then adding the ner in front of it, that would throw an error in between?

In that case, you might see a `UserWarning` after the first call to `add_pipe`, yes. I definitely wouldn't suggest raising errors here by default (this could be an optional setting if a user wants spaCy to be very strict). So the change should be fully backwards-compatible.

**Comment by svlandeg** [comment]
I think this can be closed with the implementation of the [`@Language.component`](https://nightly.spacy.io/api/language#component) and [`@Language.factory`](https://nightly.spacy.io/api/language#factory) decorators that take optional `assigns` and `requires` flags in spaCy [v3](https://github.com/explosion/spaCy/releases/tag/v3.0.0rc1). These support [nlp.analyze_pipes](https://nightly.spacy.io/api/language#analyze_pipes) which can be pretty useful (pun intended) :-)
