### ISSUE TITLE
tokenizer.add_special_case not working

### ISSUE THREAD

**Issue by bklippstein** [explosion/spaCy#3944]
tokenizer.add_special_case is not working for me. 

```
import spacy

from spacy.symbols import ORTH, POS, X, LEMMA

nlp = spacy.load('en')

nlp.tokenizer.add_special_case('»', [{ORTH: '»', POS: X, LEMMA:'Test'  }])
nlp.tokenizer.add_special_case('«', [{ORTH: '«', POS: X, LEMMA:'Test' }])

doc = nlp('He said: »I am lying.«')

for token in doc:
    print('{:10}{:10}{:10}'.format(token.text, token.pos_, token.lemma_))
```
returns
```
He        PRON      -PRON-    
said      VERB      say       
:         PUNCT     :         
»         PUNCT     »         
I         PRON      -PRON-    
am        VERB      be        
lying     VERB      lie       
.         PUNCT     .         
«         PUNCT     «   
```

The reason why I try to change the POS tags is that they are wrong for '»'  and '«' in the german model. 

Even the code from [here](https://stackoverflow.com/questions/51766157/how-to-force-a-pos-tag-in-spacy-before-after-tagger) is not working:

```
import spacy

from spacy.symbols import ORTH, POS, NOUN, VERB

nlp = spacy.load('en')

nlp.tokenizer.add_special_case('{G}', [{ORTH: '{G}', POS: NOUN}])
nlp.tokenizer.add_special_case('{T}', [{ORTH: '{T}', POS: VERB}])

doc = nlp('This {G} a noun and this is a {T}')

for token in doc:
    print('{:10}{:10}'.format(token.text, token.pos_))
  
# Wanted output:
# This      DET       
# {G}       NOUN      
# a         DET       
# noun      NOUN      
# and       CCONJ     
# this      DET       
# is        VERB      
# a         DET       
# {T}       VERB

# My output:
# This      DET       
# {G}       NOUN      
# a         DET       
# noun      NOUN      
# and       CCONJ     
# this      DET       
# is        VERB      
# a         DET       
# {T}       NOUN   <<<<<<<<<<<<<<<<<<<
```

## Your Environment

* Operating System: Linux-5.0.0-20-generic-x86_64-with-debian-buster-sid
* Python Version Used: 3.6.8
* spaCy Version Used: 2.1.4  [cuda100]
* Environment Information:

**Comment by svlandeg** [comment]
I think there's a few things going on here. 

First, the `add_special_case` doesn't work defining only a `POS` annotation. It does work when defining only a `TAG` but in that case it keeps the `POS` emtpy. So you're better off defining both, e.g.
`nlp.tokenizer.add_special_case('lying', [{ORTH: 'lying', POS: X, TAG: X, LEMMA: 'Test'}])`
which outputs
> lying     X         X         Test      

when changing the print statement to 
`print('{:10}{:10}{:10}{:10}'.format(token.text, token.pos_, token.tag_, token.lemma_))`

Second, it looks like these rules don't work with punctuation such as `«` or `{`. Would it make more sense to redefine your punctuation/prefix/suffix lists instead? (cf https://spacy.io/usage/linguistic-features#native-tokenizer-additions)

**Comment by honnibal** [comment]
We've actually been considering removing this functionality, as it's pretty confusing to set the `TAG` attribute within the tokenizer, and there are other ways of achieving the same sort of thing (e.g. with `Matcher` rules). In the library itself, we'll definitely be avoiding having the exception rules set token attributes.

So, I would second the suggestion to consider alternative implementations, even though you can make this work by using the `TAG` attribute instead of `POS`, as @svlandeg points out. The exception rules do work with punctuation though.

**Comment by bklippstein** [comment]
thanks svlandeg, but you are right, it's not working with punctuation signs. 

I understand that it's pretty confusing to set the TAG attribute. 
It's all because of the wrong POS in the german model, I tried to fix it:
```
import spacy
nlp = spacy.load('de_core_news_sm') 

doc = nlp('Er sagte: »Ich gehe in das Haus.«')

for token in doc:
    print('{:10}{:10}'.format(token.text, token.pos_))

# Result:
# Er        PRON      
# sagte     VERB      
# :         PUNCT     
# »         PROPN    <<<<<<< Should be X or PUNCT
# Ich       PRON      
# gehe      VERB      
# in        ADP       
# das       DET       
# Haus      NOUN      
# .         PUNCT     
# «         NOUN    <<<<<<< Should be X or PUNCT
```
It's difficult to find the Noun in the sentence if the tokenizer tags punctuation signs as nouns.
I tried to use other signs for literal speech, but the problem is the same with other chars
`› ‹ „ “ ‚ ‘ “ ”    ` 

So really a Matcher is the best way to fix this?

**Comment by ines** [comment]
> It's difficult to find the Noun in the sentence if the tokenizer tags punctuation signs as nouns.

The tokenizer doesn't tag anything – it really just splits a string into tokens. What you're seeing here are incorrect predictions by the part-of-speech tagger. You can prevent this by adding rules that run *before* the tagger and that set the correct part-of-speech tags for certain tokens like `»`. The tagger will then respect the pre-defined tags and only fill in the blanks, which typically results in better predictions at runtime.

The most elegant way of implementing fixup rules like this is to use a `Matcher` that finds the tokens, then overwrite the `Token.tag_` (fine-grained, language-specific part-of-speech tag) and apply it in the pipeline before the statistical component runs (in this case, the tagger).

**Comment by bklippstein** [comment]
ok, thanks! This code worked for me:

```
# define pipeline component
# fix issues with the literal speech signs in german
def wrede(doc):
    
    lex = doc.vocab['»']
    lex.is_left_punct = True
    lex.is_right_punct = False

    lex = doc.vocab['«']
    lex.is_left_punct = False
    lex.is_right_punct = True
    
    matcher = Matcher(doc.vocab)
    pattern1 = [{'TEXT': '»'}]
    pattern2 = [{'TEXT': '«'}]
    matcher.add('PATTERN_is_punct', None, pattern1, pattern2)
    
    matches = matcher(doc)
    
    for match_id, start, end in matches:
        #print("Match found:", doc[start].text)
        doc[start].tag_ = '$('    
        
    return doc
    


# activate pipeline component 
if 'wrede' not in nlp.pipe_names:
    nlp.add_pipe(wrede, first=True)
nlp.pipe_names    
    
```
