### ISSUE TITLE
Unexpected behaviour about noun_chunks in specific examples

### ISSUE THREAD

**Issue by DiamondI** [explosion/spaCy#3956]
## How to reproduce the behaviour

**Code:**

```python
import spacy

nlp = spacy.load("en")

sentences = [
    "Fruits, for example bananas, oranges and peaches.",
    "Fruits, for example, bananas, oranges and peaches.",
    "Fruits, for example apples, bananas, oranages and peaches.",
    "Fruits, for example, apples, bananas, oranges and peaches.",
    "Fruits, for example apples, bananas, watermelons, oranages and peaches.",
    "Fruits, for example, apples, bananas, watermelons, oranages and peaches."
]

cnt = 6

for sentence in sentences:
    doc = nlp(sentence)
    results = list([i for i in doc.sents][0].noun_chunks)
    if cnt & 1:
        print("'for example,' with comma")
    else:
        print("'for example' without comma")
    print("Sentence: {sentence}\nReal Examples: {coe}\nNumber of noun phrases:"
          " {len_of_result}\nResults: {results}\n\n".
         format(sentence=sentence, coe=cnt//2,
                len_of_result=len(results), results=results))
    cnt += 1
```

**Outputs:**

```
'for example' without comma
Sentence: Fruits, for example bananas, oranges and peaches.
Real Examples: 3
Number of noun phrases: 5
Results: [Fruits, example, bananas, oranges, peaches]


'for example,' with comma
Sentence: Fruits, for example, bananas, oranges and peaches.
Real Examples: 3
Number of noun phrases: 5
Results: [Fruits, example, bananas, oranges, peaches]


'for example' without comma
Sentence: Fruits, for example apples, bananas, oranages and peaches.
Real Examples: 4
Number of noun phrases: 6
Results: [Fruits, example, apples, bananas, oranages, peaches]


'for example,' with comma
Sentence: Fruits, for example, apples, bananas, oranges and peaches.
Real Examples: 4
Number of noun phrases: 5
Results: [Fruits, example, bananas, oranges, peaches]


'for example' without comma
Sentence: Fruits, for example apples, bananas, watermelons, oranages and peaches.
Real Examples: 5
Number of noun phrases: 7
Results: [Fruits, example, apples, bananas, watermelons, oranages, peaches]


'for example,' with comma
Sentence: Fruits, for example, apples, bananas, watermelons, oranages and peaches.
Real Examples: 5
Number of noun phrases: 6
Results: [Fruits, example, bananas, watermelons, oranages, peaches]
```

From the example above, we shall see that the noun phrase, '**apple**' in this example, right behind "**for example,** " will be ignored by spacy when the number of example noun phrases are greater than 3. However, there's no such problem when using "**for example**" without a comma.

## Your Environment

* Operating System: Mac OS X 10.14.5 18F132
* Python Version Used: Python 3.6.3
* spaCy Version Used: 2.1.4
* Environment Information:

**Comment by svlandeg** [comment]
Hi @DiamondI, which English model did you use to produce this output?

When I check with `en_core_web_md` I can reproduce some of your output. I think it's mainly an error in the dependency parsing. The "for example" gets attached to the first fruit in the summation, with `pobj` and `prep` dependencies, and then "example" gets tagged as a `Noun`. As `noun_chunks` only retrieves the base noun phrases, it then skips that first fruit in the summation with the nested Noun "example" inside it. This doesn't always happen because the dependency parse may vary slightly when the sentence changes ...

**Comment by DiamondI** [comment]
I use `en-core-web-sm`. So the parser considers '**for example, apples**' as a whole and the base noun phrase in this case is '**example**'?

**Comment by svlandeg** [comment]
Yea, you can check the parse tree with [displacy](https://spacy.io/api/top-level#displacy) or run this:

```
 for token in doc:
        print(token.text, token.pos_, token.dep_, token.head.text)
```


You'll see that in the cases where it doesn't miss a fruit, the "for" (and consequently also "example") is attached to "Fruits":
> Fruits NOUN ROOT Fruits
> for ADP prep Fruits
> example NOUN pobj for
> apples NOUN appos Fruits

In the other cases, e.g. where "apples" goes missing, it's because the "for example" was wired differently:
> Fruits NOUN ROOT Fruits
> for ADP prep apples
> example NOUN pobj for
> apples NOUN appos Fruits

I'm still a little puzzled though why in the latter case "apples" is not returned as its own noun phrase (while e.g. Fruits always is)

**Comment by DiamondI** [comment]
I see. 'apple' missing happens when 'for example, apples' is considered as a whole. In the phrases, 'example' is the first NOUN thus noun_chunks would return 'example' and miss 'apples'. Wow, I never thought that a comma would joint two phrases not separate them before. Well, is there any way to avoid this situation?

**Comment by svlandeg** [comment]
It really depends on the underlying data that the dependency parser was trained on. For instance, if you use `en_core_web_lg` you'll see the opposite behaviour: with the comma it will attach "for example" to "Fruits" (and retrieve one more noun phrase), and without comma it will usually attach it to the first fruit in the summation (and miss one noun phrase).

So as a solution, you can always try using a bigger model, retrain an existing model, and/or do some error analysis and check whether the sentences you're feeding into the model, are in fact grammatically correct. Either way, you should assume the parser is never going to be 100% accurate...

**Comment by DiamondI** [comment]
Fine. Thanks for your help and I know better about spacy now! :smile:
