### ISSUE TITLE
Modified pos attribute not being serialized

### ISSUE THREAD

**Issue by aabbi** [explosion/spaCy#3959]
## How to reproduce the behaviour
Since `pos` attribute of tokens is now writable (related [comment](https://github.com/explosion/spaCy/issues/2014#issuecomment-376642763) ), I ran into the issue that I changed the pos tag and serialized the doc but on deserializing, it retained the original pos tag. 
I believe this is happening because only the `tag` attributes are pickled

```
import spacy
nlp = spacy.load('en')
d = nlp("displaCy uses JavaScript, SVG and CSS to show you how computers understand language")
print(d[0].pos_) # prints ADJ
d[0].pos_ = "NOUN"
d.to_disk("t.txt")

d2 = nlp("")
d2.from_disk("t.txt")
print(d2[0].pos_) # prints ADJ
```
Wasn't entirely sure if this should be a bug or a feature request to make pos tags picklable or maybe documentation could be added specifying how serializing would not save changes in coarse grained attributes with pos tag as examples

## Your Environment
* **spaCy version:** 2.1.3
* **Platform:** Ubuntu-14.04-trusty
* **Python version:** 3.6.8
* **Models:** en_core_web_lg, en, en_core_web_md

**Comment by svlandeg** [comment]
Thanks for the report, good catch! Fixed in PR #4092.
