### ISSUE TITLE
Regex does not pick up the token that contains a word

### ISSUE THREAD

**Issue by SaulML** [explosion/spaCy#3960]
Hi,
I am running below simple code to obtain all tokens that contains the word ( for example, words containing acompared, notcompared, thiscompared).

But, the spaCy regrex does not return anything. The regular expression word fine on python re.

Could you let me know if this is an spaCy issue or how resolve the issue?
import plac
from spacy.lang.en import English
from spacy.matcher import PhraseMatcher, Matcher
from spacy.tokens import Doc, Span, Token
import spacy

nlp = spacy.load("en_core_web_sm")

text = """
    "Net income was $9.4 million acompared to the prior year of $2.7 million.",
    "Revenue exceeded twelve billion dollars, with a loss of $1b. run",
"""
doc = nlp(text)

pattern = [{"LOWER": {"REGEX": "\b\w*compared\w*\b"}}]

matcher = Matcher(nlp.vocab)
matcher.add("item", None,  pattern )
matches = matcher(doc)
print(matches)
print(matcher)

Thanks,

Saul

## Your Environment

* Operating System:
Ubuntu 18
* Python Version Used:
3.7.3  
* spaCy Version Used:
2.1.4
* Environment Information:

**Comment by FallakAsad** [comment]
It is because your regex does not match any string in text. '\w' matches word that equals to [a-zA-Z0-9_] but there is no word in text that matches 'compared' followed by a character that matches '\w'. The example words what would match your regex would be 'compareda', 'comparedb', 'comparedA', 'compared1' etc

**Comment by SaulML** [comment]
Thanks Fallak. 

I updated the code. But still not working. The code is below.

import plac
from spacy.lang.en import English
from spacy.matcher import PhraseMatcher, Matcher
from spacy.tokens import Doc, Span, Token
import spacy

nlp = spacy.load("en_core_web_sm")

text = """
"Net income was $9.4 million acompared to the prior year of $2.7
million.",
"Revenue exceeded twelve billion dollars, with a loss of $1b. run",
"""

doc = nlp(text)

pattern = [{"LOWER": {"REGEX": "\\b\w*(?:compared)\w*\b"}}]

matcher = Matcher(nlp.vocab)
matcher.add("item", None, pattern )
matches = matcher(doc)
print(matches)
print(matcher)

**Comment by FallakAsad** [comment]
Add 'r' at the beginning of your regex as follows:
pattern = [{"LOWER": {"REGEX": r"\b\w*compared\w*\b"}}]
