### ISSUE TITLE
comparison to magpie

### ISSUE THREAD

**Issue by bytearchive** [explosion/spaCy#3963]
can you provide comparison to magpie

**Comment by BreakBB** [comment]
Well... spaCy is a python library for NLP while magpies are the most intelligent birds on earth...

Sorry, seriously now. It would be great if you could provide some more information about what exactly you want to compare spaCy to and under what perspective.

Moreover if you have a look at [spacy.io](spacy.io) you have a wide range of information and docs which will help you to understand what spaCy is and what it is capable of.
