### ISSUE TITLE
How to save best models for Spacy

### ISSUE THREAD

**Issue by pratapaprasanna** [explosion/spaCy#3965]
Hi all, 

Currently i am going through this document and see that i can save the model.  Is there any facility to save the best model as-in the model which doesn't overfit. I didnt find any relevant part in the link [saving and loading](https://spacy.io/usage/saving-loading)

* Operating System: Ubuntu 18.04
* Python Version Used: python 3.6.8
* spaCy Version Used: 2.1.4
* Environment Information:

Thanks in advance

**Comment by BreakBB** [comment]
No, there is no build in function for that. But you can simply compare the evaluated scores and keep a copy of the best model and the achieved scores.

As example if you're training the `textcat` pipeline you would do something like this:

```python
best_fmeasure = 0
best_textcat = None

# Do the basic training stuff here

with textcat.model.use_params(optimizer.averages):
  # evaluate on the eval data
  scores = evaluate(nlp.tokenizer, textcat, eval_texts, eval_cats)

if scores["f_measure] > best_fmeasure:
  best_fmeasure = score["f_measure"]
  best_textcat = nlp.get_pipe("textcat")

# After training is done
with nlp.use_params(optimizer.averages):
  nlp.replace_pipe("textcat", best_textcat)
  nlp.to_disk("my/fancy/path")
```

**Comment by svlandeg** [comment]
@BreakBB : shouldn't you also store the "best" optimizer weights, instead of taking the averages?

**Comment by alejandrojcastaneira** [comment]
Hi guys, you could also check also a similar post #3706 that we asked a couple months ago, regards.

**Comment by BreakBB** [comment]
@svlandeg I adapted what the post of @alejandrojcastaneira shows, since honnibal did not suggest any changes.

**Comment by svlandeg** [comment]
@BreakBB : Right - but I think the line `with nlp.use_params(optimizer.averages):` is redundant though
