### ISSUE TITLE
How can I add words to model?

### ISSUE THREAD

**Issue by sepidehamiri** [explosion/spaCy#3967]
## Feature description
 
I downloaded the en_core_web_lg package and I want to use it for similarity, but I have some special words, which the vectors are zero and I want to add the vector. What is the order?

for example:
```
    nlp = spacy.load('en_core_web_lg')

    vector_data = {u"maestro": np.random.uniform(-1, 1, (300,)),
                   u"bot": np.random.uniform(-1, 1, (300,)),
                   u"nugget": np.random.uniform(-1, 1, (300,))}
    vocab = Vocab()
    for word, vector in vector_data.items():
        vocab.set_vector(word, vector)
```

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
If so, we will tag it as [`project idea`](https://github.com/explosion/spaCy/labels/project%20idea) so other users can take it on.

**Comment by BreakBB** [comment]
Since you already loaded the "en_core_web_lg" model you should update the vocab of that model instead of creating a new vocab.

```python
nlp = spacy.load('en_core_web_lg')

vector_data = {u"maestro": np.random.uniform(-1, 1, (300,)),
                       u"bot": np.random.uniform(-1, 1, (300,)),
                       u"nugget": np.random.uniform(-1, 1, (300,))}
vocab = nlp.vocab  # Get the vocab from the model
for word, vector in vector_data.items():
  vocab.set_vector(word, vector)
```

**Comment by sepidehamiri** [comment]
> Since you already loaded the "en_core_web_lg" model you should update the vocab of that model instead of creating a new vocab.
> 
> ```python
> nlp = spacy.load('en_core_web_lg')
> 
> vector_data = {u"maestro": np.random.uniform(-1, 1, (300,)),
>                u"bot": np.random.uniform(-1, 1, (300,)),
>                u"nugget": np.random.uniform(-1, 1, (300,))}
> vocab = nlp.vocab  # Get the vocab from the model
> for word, vector in vector_data.items():
>     vocab.set_vector(word, vector)
> ```

Thank you!
