### ISSUE TITLE
Create your own tok2vec

### ISSUE THREAD

**Issue by RonRademaker** [explosion/spaCy#3973]
If I understand correctly, the tok2vec property that was created for the bert-like pretraining is a model that creates an embedding vector for a token instead of just getting one from a word2vec model. Is there an API or something I could implement to create my own tok2vec model?

## Which page or section is this issue related to?
https://github.com/explosion/spaCy/issues/3448

**Comment by honnibal** [comment]
So if I understand correctly, you want to define a custom model architecture for that part of the network, and have it used in the models?

We don't really have a great API for this. The easiest way currently is to subclass the component and define a `Model` classmethod, which assembles the custom architecture.

**Comment by RonRademaker** [comment]
Actually, this question is now outdated (I created a custom pipeline wrapping pytorch instead)
