### ISSUE TITLE
Transient segmentation fault in noun_chunks and as_doc()

### ISSUE THREAD

**Issue by tedgoddard** [explosion/spaCy#3974]
This crash was observed on macOS but also occurs on Ubuntu 18.04 on docker. The error reported on linux is slightly more informative than "segmentation fault", it's "corrupted size vs. prev_size" or "corrupted double-linked list". The crash is being called transient because it only occurs after many invocations, hence the while loop. It also seems to occur less often (never?) for short text input.

As a workaround, I am using nlp(chunk.text) rather than as_doc(), but this is significantly slower.

## How to reproduce the behaviour

```
import spacy

nlp = spacy.load('en_core_web_sm')

while True:
    text = "Goku is introduced in the Dragon Ball manga and anime at 12 years of age[23] (initially, he claims to be 14,[22] but it is later clarified during the Tournament Saga that this is because Goku had trouble counting), as a young boy living in obscurity on Mount Paozu. Goku owns the Power Pole and the four-star Dragon Ball, inheritances from his grandfather."
    doc = nlp(text)
    result = [ [token.text for token in chunk.as_doc()] for chunk in doc.noun_chunks ]
    print(result)
```

## Your Environment

* **spaCy version:** 2.1.6
* **Platform:** Linux-4.9.125-linuxkit-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.6.8
* **Models:** en

**Comment by honnibal** [comment]
Thanks for the report. We have a fix for this in the works, see #3969.
