### ISSUE TITLE
Unable to process multiple jsonlines files as input

### ISSUE THREAD

**Issue by akornilo** [explosion/spaCy#3975]
## How to reproduce the behaviour
I am trying to train a new spacy NER model, my training data is spread across multiple jsonlines files in one directory.  I created each example using `from spacy.gold import docs_to_json`.

Using this data, I tried to run `python -m spacy train en testtest train_docs/ test_docs/ -b en`

and got the error:

---
My train_docs and test_docs directories look like:

0000.jsonl
0001.jsonl

-----

## Your Environment

* Operating System: Ubuntu 16.04.5 LTS (Xenial Xerus)
* Python Version Used: Python 3.6.5 :: Anaconda, Inc.
* spaCy Version Used: 2.1.5
* Environment Information:

## A fix?

I made a custom fix - but I would like to know if there is a better solution.

I was able to fix this issue locally, by modifying the gold.pyx file as follows:

```
@@ -142,7 +142,7 @@ class GoldCorpus(object):
                 continue
             elif path.is_dir():
                 paths.extend(path.iterdir())
-            elif path.parts[-1].endswith(".json"):
+            elif path.parts[-1].endswith(".json") or path.parts[-1].endswith(".jsonl"):
                 locs.append(path)
         return locs

@@ -154,7 +154,7 @@ class GoldCorpus(object):
             if loc.parts[-1].endswith("json"):
                 gold_tuples = read_json_file(loc)
             elif loc.parts[-1].endswith("jsonl"):
-                gold_tuples = srsly.read_jsonl(loc)
+                gold_tuples = jsonl_to_tuples(srsly.read_jsonl(loc))
             elif loc.parts[-1].endswith("msg"):
                 gold_tuples = srsly.read_msgpack(loc)
             else:
@@ -311,6 +311,10 @@ def json_to_tuple(doc):
         if sents:
             yield [paragraph.get("raw", None), sents]

+def jsonl_to_tuples(docs):
+    for doc in docs:
+        for json_tuple in json_to_tuple(doc):
+            yield json_tuple
```

**Comment by ines** [comment]
Ah, looks like the `.json` is still hard-coded for this particular case. Do you want to submit a PR with your modifications?


We can probably even simplify this part:
```python
- elif path.parts[-1].endswith(".json") or path.parts[-1].endswith(".jsonl"):
+ elif path.parts[-1].endswith((".json", ".jsonl")):
```

**Comment by akornilo** [comment]
Hey I created a PR to reflect the directory issue, but I believe that the current procedure for ingesting jsonlines files is broken - thats why I proposed the second set of changes above.

My training data in the jsonlines files looks like:

```
{id: 123, paragraphs: []}
{id: 245, paragraphs:[]}
```

where the structure within the paragraphs is as described here; https://spacy.io/api/annotation#json-input

When I try to ingest these files, the gold corpus code finds no examples. The `srsly.read_jsonl` part works correctly - it yields a generator of the input jsons. But because the `json_to_tuple` code does not run - the corpus appears empty.

Is the jsonlines training format supposed to look different from the json one?

**Comment by akornilo** [comment]
I have revisited this project and my concern still remains. As far as I can tell, there are two separate issues involved:

1. the `gold.docs_to_json` function returns a dict NOT a list (despite the spec saying that it will return a list)
2. When the input format file name is json - the `GoldCorpus.read_tuples` assumes that the input is already in the tuple format (output from the `json_to_tuples` function) - but when the input is from a file that ends with json - it assumes that the input is in the standard training format.

I think that there needs to be clear documentation - right now its not obvious what the function expects - and it expects different things depending on the file ending.

**Comment by akornilo** [comment]
I think the short term fix can come in the form of documentation:

"If input is json files - then the input should conform with the format described here: https://spacy.io/api/annotation#training"

If the input is in jsonlines files - then each line should be in the GoldCorpus format that can be generated with json_to_tuple.

**Comment by ines** [comment]
Merging this with #4462!
