### ISSUE TITLE
incorrect pos tag

### ISSUE THREAD

**Issue by dlemke01** [explosion/spaCy#3976]
"quit" is being tagged as a noun, when it should be a verb.

## How to reproduce the behaviour
> doc = nlp(u"There were 100 contestants on the gameshow and then 20 quit.")
> [(token, token.pos_) for token in doc]
[(There, u'ADV'), (were, u'VERB'), (100, u'NUM'), (contestants, u'NOUN'), (on, u'ADP'), (the, u'DET'), (gameshow, u'NOUN'), (and, u'CCONJ'), (then, u'ADV'), (20, u'NUM'), (quit, u'NOUN'), (., u'PUNCT')]

as opposed to:
> doc = nlp(u"There were 100 contestants on the gameshow and then 20 decided to quit.")
> [(token, token.pos_) for token in doc]
[(There, u'ADV'), (were, u'VERB'), (100, u'NUM'), (contestants, u'NOUN'), (on, u'ADP'), (the, u'DET'), (gameshow, u'NOUN'), (and, u'CCONJ'), (then, u'ADV'), (20, u'NUM'), (decided, u'VERB'), (to, u'PART'), (quit, u'VERB'), (., u'PUNCT')]

## Info about spaCy

* **Python version:** 2.7.16
* **Platform:** Linux-5.1.12-arch1-1-ARCH-x86_64-with-glibc2.2.5
* **spaCy version:** 2.1.3
* **Models:** en_core_web_sm

**Comment by BreakBB** [comment]
Please have a look at the pinned issue #3052 .
