### ISSUE TITLE
Fasttext vectors usage in spacy

### ISSUE THREAD

**Issue by van51** [explosion/spaCy#3978]
Spacy recently added support for fasttext vectors, but it is not clear to me how to package them, along with the info about subword features. *init-model* does not look like it knows to work with both the word vectors and the ngram vectors.
The approach I have been using so far is to create a custom Spacy component which sets the
vector user_hooks to a wrapper function which knows how to properly embed even OOV words.
However, later on I realised that these vectors hooks are not used throughout training, since the Tok2Vec expects to find the vectors pre-loaded in the vocab.

Could you tell me if I am missing something or if there is an easy work-around? 

##  Environment
* **spaCy version:** 2.1.4
* **Platform:** Darwin-18.6.0-x86_64-i386-64bit
* **Python version:** 3.7.3
* **Models:** en

**Comment by honnibal** [comment]
@van51 The support for FastText subword vectors is only partial,. To use it, you'll need to make sure all of the subword entries are added to the vectors (which is a bit weird, admittedly).

The model also won't use the subword vector calculation during the text classification, NER, tagger etc components. I think probably the most useful way to make use of the functionality would be to get a list of words that are common in your data but not in the vectors model, and then use the `vocab.get_vector` function to add a vector for those words to the table. Once the vector is in the table, it'll be available for the models.
