### ISSUE TITLE
Wrong tokenization of text with quotes separated only by coma

### ISSUE THREAD

**Issue by serzh** [explosion/spaCy#3981]
## How to reproduce the behaviour
Spacy do wrong tokenization of the text that has quotes in it that are seprated only with coma, without the space. For example:

```
   > list(map(print(nlp.tokenizer('"high","low"'))))
   "
   high","low
   "
```

With space everything works as expected:

```
   > list(map(print(nlp.tokenizer('"high", "low"'))))
   "
   high
   "
   ,
   "
   low
   "
```
This whole is a little bit confusing, because documentation says that Tokenizer works "recursively", however in the code we see that `infix_finditer` is called only once at the end of suffix-prefix iterations.
As a fix I've added `spacy.lang.char_classes.LIST_QUOTES` to the lisft of Tokenizer infixes and overrided `infix_finditer`, but I think it is better to fix it in the spacy itself.

## Your Environment
* **spaCy version:** 2.1.6
* **Platform:** Darwin-17.7.0-x86_64-i386-64bit
* **Python version:** 3.6.6

**Comment by svlandeg** [comment]
Thanks for the report! If you think your edits to the tokenizer are general enough and wouldn't negatively impact speed/accuracy, please feel free to open a pull request with your contributions (see [here](https://github.com/explosion/spaCy/blob/master/CONTRIBUTING.md) for general guidelines). 

You could also add a unit test [here](https://github.com/explosion/spaCy/tree/master/spacy/tests/regression) for this specific issue to ensure regressions don't pop up in later developments. Note that statistical models should not be used in these texts, but you can easily rely on the `en_tokenizer`, for an example see https://github.com/explosion/spaCy/blob/master/spacy/tests/regression/test_issue3521.py.
