### ISSUE TITLE
Installing spacy with fewer languages to save disk space

### ISSUE THREAD

**Issue by martinpeck** [explosion/spaCy#3983]
I'm building a docker container that contains a the Python library `spacy`. I'm now trying to reduce the size of this container, and `spacy` appears to be the main contributor to the disk image size.
 
Without any models installed, and without any other code/dependencies etc, `spacy` consumes around 500MB of disk when installed. It looks like the lang folder within this package is the main cause of this disk usage.

I'd like to be able to install spacy with a smaller set of languages, or to be able to remove them in a supported manner post-install, but I've not seen any docs that explain how this might be done.
 
My repro steps are:

```bash
mkdir foo1                  # create a folder 
cd foo1                     # change directory
python3 -m venv .venv       # create virtual environment
source .venv/bin/activate   # activate virtual environment
pip install --upgrade pip   # upgrade pip
pip install spacy           # install spacy
``` 

After doing this, I then navigate into the following folder...
 
`foo1/.venv/lib/python3.7/site-packages`
 
... and can see that the spacy folder is very large:
 
```bash
$ du -sh spacy
425M	spacy
```
 
Specifically, it's the language folder that's large:

```bash
$ du -sh spacy/lang
401M spacy/lang
``` 

There are 52 languages in that folder, and for many situations I only want one or two languages. For the specific app I'm working on now, I'm only interested in English.
 
When I look at the sizes, English is the 14th largest (only showing the top 14 in this list)...

```bash
$ du -sH spacy/lang/* | sort -n -r 

142024 spacy/lang/tr
86608 spacy/lang/pt
78368 spacy/lang/nb
76592 spacy/lang/da
74840 spacy/lang/sv
60672 spacy/lang/ca
50880 spacy/lang/es
48296 spacy/lang/fr
41688 spacy/lang/de
36960 spacy/lang/nl
34008 spacy/lang/it
32632 spacy/lang/ro
24160 spacy/lang/lt
8712 spacy/lang/en  <--- THE ONE I WANT
```

Is there a spacy-specifc way of installing `spacy` without all of these languages?
 
I can hack around post-install, but is there a safer way to install fewer languages?

My environment, and details about the versions installed in the above...

```bash
$ pip freeze
blis==0.2.4
certifi==2019.6.16
chardet==3.0.4
cymem==2.0.2
idna==2.8
murmurhash==1.0.2
numpy==1.16.4
plac==0.9.6
preshed==2.0.1
requests==2.22.0
spacy==2.1.6
srsly==0.0.7
thinc==7.0.8
tqdm==4.32.2
urllib3==1.25.3
wasabi==0.2.2
```

``` bash
$ python --version
Python 3.7.4
```

Installed on MacOS

**Comment by ines** [comment]
Hi! Thanks for the detailed issue 🙂 I definitely agree that the package size is a problem and it's actually something we're actively working on at the moment. 

There are some constraints that make it difficult to just allow a "spaCy light" installation (also see #3258), so we're starting by compressing the existing resources at build time to just make everything smaller. Next, we'll be moving the lookup tables and everything else that takes up space out of the library entirely – either by updating the lemmatization so lookups aren't needed (see #2668 and @guadi1994's [great talk at spaCy IRL](https://www.youtube.com/watch?v=88zcQODyuko&list=PLBmcuObd5An4UC6jvK_-eSl6jCvP1gwXc&index=7)) or by allowing efficient lookups using external resources and model packages (see #3971). @polm will be working with us on the compression and efficient dictionary part of this btw 🙌

**Comment by martinpeck** [comment]
Thanks, @ines, for that really helpful, and timely, update!
I'm happy to see there are issues already tracking these things. I'll watch the issues you've mentioned.
