### ISSUE TITLE
Pretraining gives AttributeError: 'FunctionLayer' object has no attribute 'G'

### ISSUE THREAD

**Issue by DeltaSierra4** [explosion/spaCy#3984]
The full error log I get is below:

```
Traceback (most recent call last):
  File "classify.py", line 461, in <module>
    plac.call(main)
  File "/usr/local/lib/python3.7/dist-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/usr/local/lib/python3.7/dist-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "classify.py", line 193, in main
    textcat.model.tok2vec.from_bytes(file_.read())
  File "/usr/local/lib/python3.7/dist-packages/thinc/neural/_classes/model.py", line 375, in from_bytes
    dest = getattr(layer, name)
AttributeError: 'FunctionLayer' object has no attribute 'G'
```

## How to reproduce the behaviour
I obtained several .bin files from running the following line:
```
python3 -m spacy pretrain data.jsonl en_vectors_web_lg binaries
```
then I used the .bin file for a text classifier with the -t2v command line argument:
```
python3 classify.py -t2v binaries/model100.bin [...other optional arguments...]
```
(classify.py is basically the sample code that is presented in the [textcat section of the documentation](https://spacy.io/usage/training#textcat)) It loads the en model and initializes the pipelines correctly, but when it reaches the line where it is trying to read in the .bin file it crashes with the error log above.

Retraining with a different version (2.1.4) or using python 2.7 or Python 3.6 instead of python 3.7.3 didn't work. Following the suggestions on issue #3668 (i.e. setting --use-vectors during pretraining) didn't work either.

## Your Environment
* Operating System: Linux Ubuntu 18.04.2 LTS
* Python Version Used: 3.7.3
* spaCy Version Used: 2.1.6

**Comment by honnibal** [comment]
@deltasierra4 Apologies for the terrible error message on this: it's probably the worst debugging experience in the library at the moment.

After you call `.begin_training()`, could you do `print(json.dumps(textcat.cfg, indent=2))` and paste the result? I'm thinking you might be missing `architecture="simple_cnn"` in the `TextCategorizer` config.

**Comment by DeltaSierra4** [comment]
Thanks for the reply! Actually you're right. I did remove that line from the code. The printout gives the following output:

```
{
  "labels": [
    ...categories added...
  ], 
  "pretrained_vectors": "en_model.vectors"
}
```

When I added the line back, the training resumed without any problem. Thanks!
