### ISSUE TITLE
Sentence boundary fails with sentence containing parentheses

### ISSUE THREAD

**Issue by colingoldberg** [explosion/spaCy#3990]
Hi,

I found unexpected behavior in the following sentence.

## How to reproduce the behaviour
`
import spacy
nlp = spacy.load('en_core_web_sm')

text = "The Amazon rainforest (Portuguese: Floresta Amazônica or Amazônia; Spanish: Selva Amazónica, Amazonía or usually Amazonia; French: Forêt amazonienne; Dutch: Amazoneregenwoud), also known in English as Amazonia or the Amazon Jungle, is a moist broadleaf forest that covers most of the Amazon basin of South America"

doc = nlp(text)

for sentence in doc.sents:
	print(sentence)
	print(sentence.root)
`

produces three sentences:
`
The Amazon rainforest
rainforest
`
`
(Portuguese: Floresta Amazônica or Amazônia; Spanish: Selva Amazónica, Amazonía or usually Amazonia; French: Forêt amazonienne;
amazonienne
`
`
Dutch: Amazoneregenwoud), also known in English as Amazonia or the Amazon Jungle, is a moist broadleaf forest that covers most of the Amazon basin of South America
is
`

## Your Environment
$ python3 -m spacy info --markdown

## Info about spaCy

* **spaCy version:** 2.1.4
* **Platform:** Darwin-18.6.0-x86_64-i386-64bit
* **Python version:** 3.6.7

Is this a bug? How to fix it?

Colin Goldberg

**Comment by BreakBB** [comment]
You could write a [custom sentence segmentation](https://github.com/explosion/spaCy/blob/master/examples/pipeline/custom_sentence_segmentation.py). You might wanna have a look at example I left [here](https://github.com/explosion/spaCy/issues/3942#issuecomment-510772362) as well to get the idea.

**Comment by colingoldberg** [comment]
This is not the type of "solution" that I was expecting. I am trying to build a "generalized" application, where I don't know what idiosyncracies to expect in the input text. 

At this point, I do not really know the cause of this issue (eg. is it just the parentheses? Or a combination of parentheses plus colons, semi-colons, etc.?). Without this knowledge, it would be difficult to write a custom segmentizer.

I do not believe that building a custom segmentizer is the best course of action if I want a generalized capability. My expectation is that the parser would be iteratively improved - over time - to handle reported issues such as this.

This particular example comes from SQuAD (The Stanford Question Answering Dataset - https://rajpurkar.github.io/SQuAD-explorer/), Amazon_rainforest devset.

**Comment by BreakBB** [comment]
The thing is that sentences boundaries are normally predicted by the [DependencyParser](https://spacy.io/api/dependencyparser) and rely on the performance of the underlying model. Therefore it is not as easy to improve, but of cause those predictions should and will be improved in the future, as you can see in the pinned issue #3052 .

But with a custom segmentizer you can handle "edge cases" by yourself by explicitly setting `is_sent_start` to `True` or `False` for specific tokens. For the tokens with `is_sent_start == None` the model will try to predict its values as far as I know.

**Comment by colingoldberg** [comment]
Thank you. Should I do anything to add this issue to the "Inaccurate pre-trained model predictions master thread #3052", or will this be handled automatically?

**Comment by BreakBB** [comment]
It is referenced in the pinned thread now.
