### ISSUE TITLE
python -m spacy download en too slow

### ISSUE THREAD

**Issue by db12138** [explosion/spaCy#3998]
the speed is less 10KB/s when  I run `python -m spacy download en` 
*for example*:
Looking in indexes: https://pypi.mirrors.ustc.edu.cn/simple/
Collecting en_core_web_sm==2.1.0 from https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz#egg=en_core_web_sm==2.1.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz (11.1MB)
    29% |█████████▍                      | 3.2MB 8.0kB/s eta 0:16:16 

and then the connection will break because of reading time out.
but I can download en_core_web_sm-2.1.0.tar.gz in my browser quickly.
how can I use en_core_web_sm-2.1.0.tar.gz directly by using a command line such as
`python -m  spacy install ./en_core_web_sm-2.1.0.tar.gz`

**Comment by ines** [comment]
You can always click on the URL of the `.tar.gz` archive and download it via your browser. You can then [install it manually](https://spacy.io/usage/models#download-pip) via `pip`. You can also find more details on this in the docs.
