### ISSUE TITLE
PhraseMatcher to match in a different token attribute

### ISSUE THREAD

**Issue by jesusfbes** [explosion/spaCy#4002]
According to the documentation of PhraseMatcher it’s also possible to make it match on different token attributes, for instance the POS tag of the dependency. Is it posible also to match other attibutes like norm? We are trying to modify the norm token attibute to remove the accents of spanish words and it is correctly changed (we checked the token.norm_ attribute) but it is not able to match in those cases:

```python
class Deaccentuate(object):

    def __init__(self, nlp):
        self._nlp = nlp

    def __call__(self, doc):
        for token in doc:
            token.norm_ = deaccent(token.lower_)
           
        return doc

ruler = EntityRuler(nlp, phrase_matcher_attr="NORM")
ruler.add_patterns(patterns_)
nlp.add_pipe(ruler)

custom_component = Deaccentuate(nlp)
nlp.add_pipe(custom_component, first=True)

```

## Your Environment

* **spaCy version:** 2.1.6
* **Platform:** Windows-10-10.0.16299-SP0
* **Python version:** 3.7.3

**Comment by svlandeg** [comment]
Hi @jesusfbes, thanks for the report! You are right that it should be possible to match on the `NORM` attribute. We're currently working on a PR that should hopefully fix this bug.
