### ISSUE TITLE
Failure for proper noun ending in "ly"

### ISSUE THREAD

**Issue by colingoldberg** [explosion/spaCy#4005]
## How to reproduce the behaviour

`
import spacy

nlp = spacy.load('en_core_web_sm')

text = "Carly has a large family"

doc = nlp(text)

print("Noun phrases:", [chunk.text for chunk in doc.noun_chunks])
`

produces:

> 
Noun phrases: ['a large family']
> 

Where's Carly?

## Your Environment

* **spaCy version:** 2.1.4
* **Platform:** Darwin-18.6.0-x86_64-i386-64bit
* **Python version:** 3.6.7

**Comment by BreakBB** [comment]
This is again related to #3052 . If you use the "en_core_web_md" model the output is as expected:

```python
import spacy

nlp = spacy.load('en_core_web_md')

text = "Carly has a large family"
doc = nlp(text)

print("Noun phrases:", [chunk.text for chunk in doc.noun_chunks])

# Noun phrases: ['Carly', 'a large family']
```
