### ISSUE TITLE
tag every token from the matched sentence

### ISSUE THREAD

**Issue by nadachaabani1** [explosion/spaCy#4006]
## Feature description
As i understand from the documentation, we can match sentence using rules with adding patterns, 
example : 
```
nlp = spacy.load("en_core_web_sm")
matcher = Matcher(nlp.vocab)

doc = nlp(
    "i want to buy an iPhone X"
)
pattern = [{"TEXT": "iPhone"}, {"TEXT": "X"}]

matcher.add("Phone", None, pattern)
matches = matcher(doc)
print("Total matches found:", len(matches))

for match_id, start, end in matches:
    print("Match found:", doc[start:end].text)
```

the program will return : 
```
Total matches found: 1
Match found: iPhone X
```

now we want to tag each token from the matched sentence: 

we want a result as: 
```
Phone Product: iPhone
Version: X
```

`Phone Product` and `Version` are two variables tags provided by the user

is there a way to achieve this result ?

**Comment by BreakBB** [comment]
You could either iterate over the tokens and store the results in some structure like this:

```python
result = {}

for match_id, start, end in matches:
    match = doc[start:end]
    print("Match found:", match.text)
    if len(match) == 2:
        result[match.text] = {}
        result[match.text]["Phone Product"] = match[0].text
        result[match.text]["Version"] = match[1].text

print(result)

# {'iPhone X': {'Phone Product': 'iPhone', 'Version': 'X'}}
```

or use spaCys [extension attributes](https://spacy.io/usage/processing-pipelines#custom-components-attributes). These will allow you to add attributes to the tokens and make this available like `token.phone_product` and `token.version`.

**Comment by nadachaabani1** [comment]
Thanks for your advice. It was very helpful.
