### ISSUE TITLE
Training on GPU -> Inference on CPU

### ISSUE THREAD

**Issue by alejandrojcastaneira** [explosion/spaCy#4010]
Hello.
I would like to know how to make the inference on a CPU configuration, from a GPU trained model.
Best regards

**Comment by honnibal** [comment]
This should just work? I don't think you need to do anything special.

**Comment by alejandrojcastaneira** [comment]
Thanks, It works

I realized now the error it's happening only when I change the hyperparameters on 
`begin_training(component_cfg={"..."}})`:

>  deserializers[name] = lambda p, proc=proc: proc.from_disk(p, exclude=["vocab"])
>   File "nn_parser.pyx", line 634, in spacy.syntax.nn_parser.Parser.from_disk
>   File "/home/user/anaconda3/envs/Glove/lib/python3.6/site-packages/thinc/neural/_classes/model.py", line 375, in from_bytes
>     dest = getattr(layer, name)
> AttributeError: 'HashEmbed' object has no attribute 'G'

The training finishes but when I try to load It happens independently of GPU or CPU.

**Comment by alejandrojcastaneira** [comment]
As a work around definining the environments variables with the proper hyperparameters before load, solves the problem, by e.g: `os.environ["embed_rows"]="5000"` or `os.environ["token_vector_width"]="256"`
