### ISSUE TITLE
Make extensions local to a pipeline

### ISSUE THREAD

**Issue by johann-petrak** [explosion/spaCy#4011]
Currently, extensions are something that gets defined on a global, system wide basis.
I think this is a serious design flaw since it severely restricts how spacy can be used.

It is not hard to find situations where people would want to use several pipelines, several languages etc. within the same system and clearly, extensions would ideally be specific to a pipeline. This would allow to have several pipelines which all may use different extensions. 
Of course, there is nothing that would prevent us from declaring shared callbacks for several pipelines.

**Comment by honnibal** [comment]
I think I disagree. If the extension attributes aren't global, then within a given program, you'll receive a `Doc`, `Span` or `Token` object and have to inspect it to figure out which attributes are available. If you have the same attribute being assigned by different pipelines, and these have different semantics, your problems would be even worse.

**Comment by johann-petrak** [comment]
If several pipelines use documents with different sets of features, no matter if the semantics of the overlapping features are identical or not (there may e.g. be slight differences for pipelines for different languages), I do not see the need to inspect: clearly a well designed pipeline and its components will know which of the features to use for what and a component for German will simply be a different component or differently parametrised component than for English or Chinese, knowing about the attributes it needs. 

Not to pollute a global namespace is one of the oldest and most important design rules and luckily python follows this rule in general. There are good reasons why the nlp instance is an instance and not a global singleton, I think there are good reasons why not to have global singletons for the Token, Span, and Doc attribute configs either. 

To answer your question: since registering an extension can also register callbacks, the callbacks would have to be assigned globally too, which makes different handling of attributes for different pipelines awkward. The only way I can see around this would be for the user to "re-invent" per-pipeline namespaces by including some pipeline-identifier in the name of the attribute and then pollute all the documents from different pipelines with the union of all those attributes. Not very pretty, from a design perspective in my opinion.

**Comment by honnibal** [comment]
>  I do not see the need to inspect: clearly a well designed pipeline and its components will know which of the features to use for what and a component for German will simply be a different component or differently parametrised component than for English or Chinese, knowing about the attributes it needs.

Yeah but you'll likely have functions outside the pipeline which take the `doc` objects as arguments. These functions should be able to work with a single `doc` definition, without worrying which pipeline the `doc` came from. If you only have functions inside the pipeline, there's actually no problem with them being global either: you can set them up at the start and tear them down at the end.

It's much better if there's always one definition of a `doc` object, rather than several. So we definitely prefer to have the extensions registered globally.
