### ISSUE TITLE
GPU spacy objects to CPU

### ISSUE THREAD

**Issue by yanaiela** [explosion/spaCy#4019]
I'm running spacy on large amounts of text, and wanted to persist the annotations to the disk.
To speed things up, I started using gpus, but then got the following error:
TypeError: can not serialize 'cupy.core.core.ndarray' object
I'm persisting the annotations using pickle.

When running on the cpus it works fine.
Is there a method to transfer all the cupy objects into numpy or something similar?

## How to reproduce the behaviour

```
import spacy
import pickle

spacy.prefer_gpu()
nlp = spacy.load('en_core_web_sm')
s = nlp("Hello World")
pickle.dump(s, open('temp.pickle', "wb"))
```

## Your Environment

* Operating System: CentOS Linux v.7
* Python Version Used: 3.7.3
* spaCy Version Used: 2.1.6
* Environment Information:

**Comment by honnibal** [comment]
I would've expected pickle to work, even with the cupy objects -- but regardless, pickle isn't the best solution.

The best way to persist a single doc will be `doc.to_bytes()`. For a collection of docs, there's a new serialization helper called `DocBox` (previously called `Binder` during development):

```python

from spacy.tokens._serialize import DocBox
from spacy.attrs import *

doc1 = nlp("Hello World")
doc2 = nlp("Hello again")
box = DocBox(attrs=[TAG, DEP, HEAD, ENT_TYPE, ENT_IOB])
box.add(doc1)
box.add(doc2)
data = box.to_bytes()

# Later
nlp = spacy.load("en_core_web_sm")
box = DocBox().from_bytes(data)
doc1, doc2 = box.get_docs(nlp.vocab)
```

**Comment by yanaiela** [comment]
great, thanks!
