### ISSUE TITLE
gold.biluo_tags_from_offsets should throw E103 if two entity labels are overlapping

### ISSUE THREAD

**Issue by RyanZHe** [explosion/spaCy#4020]
## Feature description
`spacy.gold.biluo_tags_from_offsets` should throw `Error.E103` when the collection of entites passed in have overlapping tokens. 

For example,
```
from spacy.gold import biluo_tags_from_offsets

doc = nlp(u"I like California Pizza Kitchen.")
entities = [(7, 17, "LOC"), (7, 31, "BRAND") ]
tags = biluo_tags_from_offsets(doc, entities) # should throw Error.E103
```
Right now `tags` is being assigned as `["O", "O", "U-LOC", "I-BRAND", "L-BRAND"]`, which violates the biluo tagging schema.

**Comment by pratapaprasanna** [comment]
I agree that an error has to be raised while forming tags only and not while giving input to gold corpus . It now throws error while feeding in data in goldcorpus. which I think a bad way.
-
Thanks
