### ISSUE TITLE
Editing spacy NER result before evaluation

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#4024]
Is it possible to make changes to the result spacy provides before passing it to evaluation method?  

What I want to do is iterate over the found entities and if one is a false positive (that I know for sure by other means) I want to remove it from the spacy result.  Then I want to evaluate the modified result against my gold standard after having removed the false positive items.   I know the evaluation would no longer be a true representation of spacy performance, and I'm doing this because I'm combining spacy with another process to produce a final result and I want to evaluate the combined performance. 

Is this possible?

**Comment by rockonrob** [comment]
If you use the `recall` accuracy (from the [PFScorer](https://github.com/explosion/spaCy/blob/05fbf5d97688d0c774f38ec9152e7cfb034bb82c/spacy/scorer.py#L27) it should not take into account the false positive rate. You could also extend the [Scorer](https://github.com/explosion/spaCy/blob/05fbf5d97688d0c774f38ec9152e7cfb034bb82c/spacy/scorer.py#L37) to not account for false positives.

**Comment by ines** [comment]
If you just need a `Doc` object with corrected `doc.ents`, you can also overwrite the `doc.ents` with a list of filtered spans. So basically:

```python
doc.ents = [ent for ent in doc.ents if not is_false_positive(ent)]
```
