### ISSUE TITLE
How to use gensim word2vec output for training NER?

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#4027]
A few questions regarding using word vectors for NER

1 - After training the word2vec model using Gensim, what are we saving to file how do we import the Gensim output to spacy when training an NER model? (using the train_ner.py script provided, are we supposed to use this `spacy.load(vocabulary, vocab=nlp.vocab)`  where vocabulary is something like en_vectors_web_lg

2 - I'm using the same corpus of text for both steps - training the NER model and creating word2vec model.  Is this the correct approach?

3 - When building the word2vec model should we preserve word shape? or make everything lowercase?  Also should we remove numerics?

4- CBOW vs Skip Gram for NER?

**Comment by pratapaprasanna** [comment]
@svlandeg I think u can use this command to get the spacy init model

```python -m spacy init-model en /tmp/la_vectors_wiki_lg --vectors-loc cc.la.300.vec.gz````

though it was said binary can be used but I got errors so I save my w2v model in the text format 

I,e 
word <vector>

sample script:

```wv_from_bin = KeyedVectors.load_word2vec_format(datapath("euclidean_vectors.bin"), binary=True)```

and then convert the model to text format 
as mentioned here 

https://radimrehurek.com/gensim/models/word2vec.html#gensim.models.word2vec.Word2Vec.save_word2vec_format

Post that u can load the model instead of the blank model and continue with your training.

**Comment by erotavlas** [comment]
@pratapaprasanna  what does this do?  `init-model en` ?  I suppose its initializing an empty English model.  However what happens if you put a trained model instead of `en`?

**Comment by ines** [comment]
See here for details on the `init-model` command: https://spacy.io/api/cli#init-model

The first argument is the language code. You shouldn't be using a pre-trained model here. You can then use the base model containing the custom vectors to train your named entity recognizer.

> 2 - I'm using the same corpus of text for both steps - training the NER model and creating word2vec model. Is this the correct approach?

Yes, that's fine.

> 3 - When building the word2vec model should we preserve word shape? or make everything lowercase? Also should we remove numerics?

No, don't do any of that. Just use the raw text.

> 4- CBOW vs Skip Gram for NER?

See here for details on the current model architecture: https://spacy.io/models#architecture
