### ISSUE TITLE
What is the lemma for noun_chunk "two pets"?

### ISSUE THREAD

**Issue by colingoldberg** [explosion/spaCy#4028]
Should the lemma for noun chunk "two pets" be "two pets" or "two pet"?

`
import spacy
nlp = spacy.load('en_core_web_md')

doc = nlp("John has two pets")
for chunk in doc.noun_chunks:
	print(chunk.lemma_)
`
- produces: "two pet"

Methinks it should be "two pets"

## Your Environment
* **spaCy version:** 2.1.6
* **Platform:** Linux-4.4.0-154-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.7

Also on macosx (with en_core_web_sm)
* **spaCy version:** 2.1.4
* **Platform:** Darwin-18.7.0-x86_64-i386-64bit
* **Python version:** 3.6.7

**Comment by ines** [comment]
Noun chunks are `Span` objects, i.e. sequences of tokens. The lemma of a `Span` consists of the concatenated lemmas of its tokens. The lemma of "two" is "two" and the lemma of "pets" is "pet", so the lemma of "two pets" is "two pet". 

That said, looking at the lemma on the span level is probably not very useful and it makes more sense to work on the token level.
