### ISSUE TITLE
German loading times

### ISSUE THREAD

**Issue by the-holger** [explosion/spaCy#403]
Hi there!

I was wondering if I'm doing something wrong, as the loading time differences between English and German are quite significant on my machine:

```
%time spacy.en.English()
CPU times: user 7.45 s, sys: 1.42 s, total: 8.87 s
Wall time: 9.71 s
```
vs.
```
%time spacy.de.German()
CPU times: user 29.5 s, sys: 3.33 s, total: 32.8 s
Wall time: 35.1 s
```

I think the German models might just be a bit more complicated (as they were also larger to download), but I'm kind of hoping to be able to scrape off a few seconds :-)

Thanks!
Holger

**Comment by honnibal** [comment]
Unfortunately there's no easy answer for this :(. It's not a bug — that's just the data.
