### ISSUE TITLE
Upper/Lower case changes from `pobj` to `dobj`

### ISSUE THREAD

**Issue by fersarr** [explosion/spaCy#4034]
In the sentence 'He used to like icecream', if we change 'he' to 'He' the `pobj` becomes `dobj` as shown below:

Upper case 'He' -> `pobj`
![Screen Shot 2019-07-28 at 2 54 04 PM](https://user-images.githubusercontent.com/3913371/62007619-bccf3000-b147-11e9-840a-e62b3d8f0d76.png)

Lower case 'he' -> `dobj`
![Screen Shot 2019-07-28 at 2 54 15 PM](https://user-images.githubusercontent.com/3913371/62007620-bd67c680-b147-11e9-9b2c-aa7fb2339e0d.png)

Using `en_core_web_lg`.

Expected behaviour: both sentences should use `dobj`, not `pobj`

This is probably another one for the [perf/accuracy](https://github.com/explosion/spaCy/labels/perf%20%2F%20accuracy) tag

**Comment by ines** [comment]
Merging this with #3052!
