### ISSUE TITLE
Get the pattern of the matched sentence

### ISSUE THREAD

**Issue by nadachaabani1** [explosion/spaCy#4037]
## Feature description
As i understand from the documentation, we can match sentence using rules with adding patterns,
example :
```
import spacy
from spacy.matcher import Matcher

nlp = spacy.load("en_core_web_sm")
matcher = Matcher(nlp.vocab)

doc = nlp(
    "i want to buy an iPhone X"
)
pattern1 = [{"TEXT": "iPhone"}, {"TEXT": "X"}]
pattern2 = [{"TEXT": "Samsung"}, {"TEXT": "S 10"}]

matcher.add("Phone", None, pattern1,pattern2)
matches = matcher(doc)
print("Total matches found:", len(matches))

for match_id, start, end in matches:
    print("Match found:", doc[start:end].text)
```
the program will return :
```
Total matches found: 1
Match found: iPhone X
```
in this step, the program has successful extracted the `iPhone X`, and it was due to the `match.add` method call.
in our implementation, we need to identify witch pattern was successful ( in this example `[{"TEXT": "iPhone"}, {"TEXT": "X"}]` was the pattern chosen to return this result).

**Comment by BreakBB** [comment]
You could add each pattern with a unique `ID` instead of add them all as "Phone". That way the `match_id` of the returned matches will directly reference the pattern that was hit and you could get it with `matcher.get(match_id)`.

**Comment by ines** [comment]
Btw, quick tip: Note that `{"TEXT": "S 10"}` will never match, since there likely won't be a token `S 10` and instead, two tokens: `S` and `10`. You might want to check out the matcher demo to test your patterns: https://explosion.ai/demos/matcher

**Comment by nadachaabani1** [comment]
Sorry i have made a mistake , the pattern2 sould be `[{"TEXT": "Samsung"}, {"TEXT": "S" },{"IS_DIGIt":True}]`
