### ISSUE TITLE
Support custom features for NER training

### ISSUE THREAD

**Issue by bratao** [explosion/spaCy#4039]
## Feature description

My task is to extract/segment information from a semi structured text. But not only the text is important some "external features" are also important.

For example, imagine that I want to segment this text about GitHub projects in Category, Project name, URl and description.

![image](https://user-images.githubusercontent.com/1090152/58190397-d14c0380-7c92-11e9-91e2-c1b9dd62737a.png)

I utilize an BIO scheme to tag each html token as a category. 

Where
token=NLP start_of_p=True bold=True center=True B-Category
token=Projects start_of_p=False bold=True center=True I-Category
token=Project start_of_p=True bold=True center=False B-Project-name
token=Name start_of_p=False bold=True center=False I-Project-name
token=: start_of_p=False bold=False center=False I-Project-name

The final result is something like:

![image](https://user-images.githubusercontent.com/1090152/58190447-eaed4b00-7c92-11e9-9279-f331324c828b.png)

Pay attention that some features are important such as: Text formatting (italic, bold, centered), position in text and more...

This would be a scenario where Spacy can work with?
I can see a lot of moviment around Tok2Vec. But looking at https://github.com/explosion/spaCy/blob/87fcf3141c16535b3a58edc11f799589e97fa6f1/spacy/_ml.py#L322 , apparently it still glove | norm | prefix | suffix | shape only.

There is anyway of using those custom external features for training Spacy?

Thank you!

**Comment by ines** [comment]
Hi! This is currently not possible out-of-the-box, but we'd love to support this in the future. There are a few pointers and some background info in #2328 – I'll also merge this issue with the existing thread to keep things in one place 🙂
