### ISSUE TITLE
spacy.en.download mirror

### ISSUE THREAD

**Issue by alph486** [explosion/spaCy#404]
Hi,

It takes 5 minutes and sometimes longer for me to download the static data provided by the command `python -m spacy.en.download` . It would be great if this could be put behind a global CDN like CloudFront.

If that's something you aren't capable of doing, it would be nice if a URL parameter and some docs could be put together on how to host a mirror of this data.

Thanks!

**Comment by iqbal-chowdhury** [comment]
I am getting this error while trying to install the language model.

python -m spacy.en.download
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/iqbal/spaCy/spacy/en/download.py", line 1, in <module>
    import plac
  File "/home/iqbal/.local/lib/python2.7/site-packages/plac.py", line 38, in <module>
    from plac_tk import TkMonitor
  File "/home/iqbal/.local/lib/python2.7/site-packages/plac_tk.py", line 46
    print('Process %d killed by CTRL-C' % os.getpid(), file=sys.stderr)
                                                           ^
SyntaxError: invalid syntax

**Comment by pquentin** [comment]
@iqbal-chowdhury Run `pip install plac==0.9.2`. See #414 for details.

**Comment by sconeyard** [comment]
What is going on in this issue? 
@iqbal-chowdhury this has nothing to do with the issue right?
@alph486 A CDN is not free, considering SpaCy has a lot of users loading a language model of 400-500 MB everytime they install it or deploy it on production this will costs a bit. But I guess the community could crowdsource it. Or is the SpaCy team on this already?

**Comment by alph486** [comment]
@sconeyard Agree about @iqbal-chowdhury issue, this is unrelated.

As for CDN, correct it's not free, but its not that bad. I'm sure they're paying for some sort of bandwidth serving it in Germany where it is now. If that were an issue though, that's why I suggested documenting the package structure so others could host public / private mirrors; this is the same way many other open source package managers handle this problem.

**Comment by iqbal-chowdhury** [comment]
Hi,
Extrmely sorry for being late in reply. After running that command
everything is fine now.
Thanks

**Comment by kurtg1224** [comment]
Any updates on this?  More details on the language files per @alph486 comments would be helpful.
