### ISSUE TITLE
Can't find model 'en_model.vectors'.

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#4040]
spacy version 2.1.6

I trained multiple spacy models which completed without error.  But when I tried to reload the models I get the following error

> OSError: [E050] Can't find model 'en_model.vectors'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

When training I used the en_core_web_lg model to start and added the en_vectors_web_lg on top of that using

`spacy.load(voc, vocab=nlp.vocab)` 
where voc is `en_vectors_web_lg`

**Comment by BreakBB** [comment]
The error message states that you have a place in your code where you want to run `spacy.load("en_model.vectors")` which most likely is not the name of a model nor a path to a model.

> When training I used the en_core_web_lg model to start and added the en_vectors_web_lg on top of that using

Not sure what you mean by that. Could you explain more in detail?

**Comment by ines** [comment]
Looks like you might be hitting the same problem described in #3552 – see that thread for more details and a workaround!
