### ISSUE TITLE
spaCy2.0.12 doesn't have span.ents

### ISSUE THREAD

**Issue by wli-chegg** [explosion/spaCy#4045]
## How to reproduce the behaviour

spaCy 2.0.12 didn't have span.ent as you claimed, it's a bit inconvenient because you have to go back to the doc object to match ents.
<img width="584" alt="image" src="https://user-images.githubusercontent.com/52253269/62093341-c16e1400-b22d-11e9-8f76-0acc12671070.png">

`import spaCy
nlp = spacy.load("en_core_web_md"
doc = nlp('some random text. test sentences 2.')
for sent in doc.sents:
print(sent.ents)`

## Your Environment

* Operating System: mac os
* Python Version Used: Python3.6
* spaCy Version Used: 2.0.12
* Environment Information: virtual environment

**Comment by BreakBB** [comment]
It seems that the documentation is off.

`Span.ents` has been introduces with #2599 and have been added with [2.0.13](https://github.com/explosion/spaCy/blob/v2.0.13/spacy/tokens/span.pyx#L305).

**Comment by ines** [comment]
Thanks for pointing this out and thanks @BreakBB for looking up the PR 🙏 Fixed!
