### ISSUE TITLE
Installation error for "pip install -U spacy[cuda]" on Ubuntu 18.04, CUDA 10.1, cuDNN 7.5, cupy for CUDA 10.1 

### ISSUE THREAD

**Issue by tomtel** [explosion/spaCy#4046]
## How to reproduce the problem

```bash
# copy-paste the error message here
```

## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by BreakBB** [comment]
It would be great if you could add some information to your post. Moreover you should put your environment information into the place of the template instead of the title.

**Comment by tomtel** [comment]
How to reproduce the problem
My error message:

(base) user0001@LINUX0001:~$ pip install -U spacy[cuda]
Collecting spacy[cuda]
  Using cached https://files.pythonhosted.org/packages/89/2c/42d5c9385c95a84d370aa3b678ea8e0593735abf93ab886edf853f837eb7/spacy-2.1.6-cp37-cp37m-manylinux1_x86_64.whl
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy[cuda])
  Using cached https://files.pythonhosted.org/packages/73/fc/10eeacb926ec1e88cd62f79d9ac106b0a3e3fe5ff1690422d88c29bd0909/murmurhash-1.0.2-cp37-cp37m-manylinux1_x86_64.whl
Collecting cymem<2.1.0,>=2.0.2 (from spacy[cuda])
  Using cached https://files.pythonhosted.org/packages/65/26/e534148e509cbebbea3ee29f50f59eb206621d12c35e4594507da8dc54cc/cymem-2.0.2-cp37-cp37m-manylinux1_x86_64.whl
Collecting thinc<7.1.0,>=7.0.8 (from spacy[cuda])
  Using cached https://files.pythonhosted.org/packages/36/42/d7ea7539af3852fd8c1f0b3adf4a100fb3d72b40b69cef1a764ff979a743/thinc-7.0.8-cp37-cp37m-manylinux1_x86_64.whl
Requirement already satisfied, skipping upgrade: numpy>=1.15.0 in ./anaconda3/lib/python3.7/site-packages (from spacy[cuda]) (1.16.4)
Collecting plac<1.0.0,>=0.9.6 (from spacy[cuda])
  Using cached https://files.pythonhosted.org/packages/9e/9b/62c60d2f5bc135d2aa1d8c8a86aaf84edb719a59c7f11a4316259e61a298/plac-0.9.6-py2.py3-none-any.whl
Collecting preshed<2.1.0,>=2.0.1 (from spacy[cuda])
  Using cached https://files.pythonhosted.org/packages/bc/2b/3ecd5d90d2d6fd39fbc520de7d80db5d74defdc2d7c2e15531d9cc3498c7/preshed-2.0.1-cp37-cp37m-manylinux1_x86_64.whl
Requirement already satisfied, skipping upgrade: requests<3.0.0,>=2.13.0 in ./anaconda3/lib/python3.7/site-packages (from spacy[cuda]) (2.22.0)
Collecting wasabi<1.1.0,>=0.2.0 (from spacy[cuda])
  Using cached https://files.pythonhosted.org/packages/f4/c1/d76ccdd12c716be79162d934fe7de4ac8a318b9302864716dde940641a79/wasabi-0.2.2-py3-none-any.whl
Collecting blis<0.3.0,>=0.2.2 (from spacy[cuda])
  Using cached https://files.pythonhosted.org/packages/fa/5f/47b7b29ad202b2210020e2f33bfb06d1db2abe0e709c2a84736e8a9d1bd5/blis-0.2.4-cp37-cp37m-manylinux1_x86_64.whl
Collecting srsly<1.1.0,>=0.0.6 (from spacy[cuda])
  Using cached https://files.pythonhosted.org/packages/f9/d2/75ed228767b20b1109f52d08d6db2f4c4ca33c5ab55f0d7f0422a390dd02/srsly-0.0.7-cp37-cp37m-manylinux1_x86_64.whl
Collecting thinc-gpu-ops<0.1.0,>=0.0.1; extra == "cuda" (from spacy[cuda])
  Using cached https://files.pythonhosted.org/packages/a4/ad/11ab80a24bcedd7dd0cfabaedba2ceaeca11f1aaeeff432a3d2e63ca7d02/thinc_gpu_ops-0.0.4.tar.gz
Collecting cupy>=5.0.0b4; extra == "cuda" (from spacy[cuda])
  Using cached https://files.pythonhosted.org/packages/1b/c3/da7ee609aa39182ebc4af652d00508032160b017bca05d7bc27112891532/cupy-7.0.0b2.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/user0001/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6ku2puxn/cupy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6ku2puxn/cupy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-6ku2puxn/cupy/
    Complete output (43 lines):
    Options: {'package_name': 'cupy', 'long_description': None, 'wheel_libs': [], 'wheel_includes': [], 'no_rpath': False, 'profile': False, 'linetrace': False, 'annotate': False, 'no_cuda': False}
    
    -------- Configuring Module: cuda --------
    gcc: error trying to exec 'cc1plus': execvp: Datei oder Verzeichnis nicht gefunden
    command 'gcc' failed with exit status 1
    
    ************************************************************
    * CuPy Configuration Summary                               *
    ************************************************************
    
    Build Environment:
      Include directories: ['/usr/local/cuda-10.1/include']
      Library directories: ['/usr/local/cuda-10.1/lib64']
      nvcc command       : ['/usr/local/cuda-10.1/bin/nvcc']
    
    Environment Variables:
      CFLAGS          : (none)
      LDFLAGS         : (none)
      LIBRARY_PATH    : (none)
      CUDA_PATH       : /usr/local/cuda-10.1
      NVTOOLSEXT_PATH : (none)
      NVCC            : (none)
    
    Modules:
      cuda      : No
        -> Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'cufft.h', 'curand.h', 'cusparse.h', 'nvrtc.h']
        -> Check your CFLAGS environment variable.
    
    ERROR: CUDA could not be found on your system.
    Please refer to the Installation Guide for details:
    https://docs-cupy.chainer.org/en/stable/install.html
    
    ************************************************************
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6ku2puxn/cupy/setup.py", line 120, in <module>
        ext_modules = cupy_setup_build.get_ext_modules()
      File "/tmp/pip-install-6ku2puxn/cupy/cupy_setup_build.py", line 647, in get_ext_modules
        extensions = make_extensions(arg_options, compiler, use_cython)
      File "/tmp/pip-install-6ku2puxn/cupy/cupy_setup_build.py", line 402, in make_extensions
        raise Exception('Your CUDA environment is invalid. '
    Exception: Your CUDA environment is invalid. Please check above error log.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(base) user0001@LINUX0001:

**Comment by tomtel** [comment]
My Environment
Operating System: 
x86_64
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

Python Version Used: 
Python 3.7.3

spaCy Version Used: 
spaCy is not installed

Environment Information: 
(base) user0001@LINUX0001:~$ printenv
CLUTTER_IM_MODULE=xim
CONDA_SHLVL=1
LD_LIBRARY_PATH=/usr/local/cuda-10.1/lib64
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
CONDA_EXE=/home/user0001/anaconda3/bin/conda
LESSCLOSE=/usr/bin/lesspipe %s %s
XDG_MENU_PREFIX=gnome-
LANG=de_DE.UTF-8
DISPLAY=:1
GNOME_SHELL_SESSION_MODE=ubuntu
COLORTERM=truecolor
CUDA_PATH=/usr/local/cuda-10.1
USERNAME=user0001
CONDA_PREFIX=/home/user0001/anaconda3
XDG_VTNR=2
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
_CE_M=
XDG_SESSION_ID=3
USER=user0001
DESKTOP_SESSION=ubuntu
QT4_IM_MODULE=xim
TEXTDOMAINDIR=/usr/share/locale/
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/d1324337_0a68_424d_b658_e7e868284cbf
PWD=/home/user0001
HOME=/home/user0001
CONDA_PYTHON_EXE=/home/user0001/anaconda3/bin/python
TEXTDOMAIN=im-config
SSH_AGENT_PID=1885
QT_ACCESSIBILITY=1
XDG_SESSION_TYPE=x11
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop
_CE_CONDA=
XDG_SESSION_DESKTOP=ubuntu
GJS_DEBUG_OUTPUT=stderr
CONDA_PROMPT_MODIFIER=(base) 
GTK_MODULES=gail:atk-bridge
WINDOWPATH=2
TERM=xterm-256color
SHELL=/bin/bash
VTE_VERSION=5202
QT_IM_MODULE=xim
XMODIFIERS=@im=ibus
IM_CONFIG_PHASE=2
XDG_CURRENT_DESKTOP=ubuntu:GNOME
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
GNOME_TERMINAL_SERVICE=:1.114
XDG_SEAT=seat0
SHLVL=1
GDMSESSION=ubuntu
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
LOGNAME=user0001
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_RUNTIME_DIR=/run/user/1000
XAUTHORITY=/run/user/1000/gdm/Xauthority
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
PATH=/usr/local/cuda-10.1/bin:/home/user0001/anaconda3/bin:/home/user0001/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
CONDA_DEFAULT_ENV=base
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
SESSION_MANAGER=local/LINUX0001:@/tmp/.ICE-unix/1790,unix/LINUX0001:/tmp/.ICE-unix/1790
LESSOPEN=| /usr/bin/lesspipe %s
GTK_IM_MODULE=ibus
_=/usr/bin/printenv

**Comment by ines** [comment]
This looks like it's not a problem with spaCy. Check out your error log:

```
Modules:
  cuda      : No
    -> Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'cufft.h', 'curand.h', 'cusparse.h', 'nvrtc.h']
    -> Check your CFLAGS environment variable.

ERROR: CUDA could not be found on your system.
Please refer to the Installation Guide for details:
https://docs-cupy.chainer.org/en/stable/install.html
```

Looks like cupy (which spaCy uses) can't find CUDA. Once you've fixed that, spaCy should also work as expected.
