### ISSUE TITLE
Tokens with ',"' in between are being mistaken as one token

### ISSUE THREAD

**Issue by ZeeshanA1i** [explosion/spaCy#4047]
## How to reproduce the behaviour

>>> sentence = """John said,"There's an elephant outside the window."."""
>>> for token in nlp(sentence): print (token.text, token.tag_)
... 
John NNP
said,"There NNP
's VBZ
an DT
elephant NN
outside IN
the DT
window NN
. .
" ''
. .
>>> 

## Your Environment

* Operating System:
* Python Version Used: 3.xx
* spaCy Version Used: 2.1.6
* Environment Information:

**Comment by ines** [comment]
You can always customise the tokenization rules here and modify how punctuation is handled: https://spacy.io/usage/linguistic-features#native-tokenizer-additions

Note that issues like this are typically not a good fit for this issue tracker – unless you want to propose a very specific change to the global rules included with the library. In that case, we would need to ensure that the proposed change doesn't have any unintended side-effects and that all existing tests pass. If you've found a configuration that works and solves this problem, feel free to submit a PR.
