### ISSUE TITLE
Retokenizer not setting POS tags correctly

### ISSUE THREAD

**Issue by prashantbudania** [explosion/spaCy#4051]
## How to reproduce the behaviour
I am trying to merge entities and noun chunks for a custom application without having to use merge_entities or merge_noun_chunks pipeline. But the pos tag information is inaccurate. Here's one example: 
```
import spacy 
from spacy import displacy
from spacy.util import filter_spans

nlp = spacy.load('en_2.1.0_md')
doc = nlp("While our net charge-off rate improved from a year ago, our provision expense increased due to a $150 million reserve build in the first quarter of 2019 compared with a $550 million reserve release a year ago.")

spans = list(doc.ents) + list(doc.noun_chunks)
spans = filter_spans(spans)

with doc.retokenize() as retokenizer:
    for span in spans:
        retokenizer.merge(span)

for i, tkn in enumerate(doc):
    print("{:<2}{:<2}{:<32}{:<2}{:<8}{:<2}{:<8}{:<2}{:<2}".format(i, '|', tkn.text, '|', tkn.pos_, '|', tkn.dep_, '|', tkn.ent_type_))
```

But if I specifically set the pos attribute to be the same as the root's attribute, it works fine: 

```
with doc.retokenize() as retokenizer:
    for span in spans:
        retokenizer.merge(span, attrs={"POS": span.root.pos_})
```
I remember this being the default behaviour in 2.0. And also, even after the fix, displacy would show the incorrect pos tag information: 
```
displacy.render(doc, style='dep')
```

## Your Environment
* Operating System: MacOS
* Python Version Used: 3.6
* spaCy Version Used: 2.1.4

**Comment by ines** [comment]
Thanks for the report. I think what you're obversing here in displaCy might be related to a recent change that made the `pos` attribute writable (but possibly doesn't always account for the `pos` &rarr; `tag`) relationship. What happens if you set both the `POS` and the `TAG`?

And yes, I do think it makes sense for those attribute to default to the root – not sure why this isn't happening here.

**Comment by prashantbudania** [comment]
Yeah, it works fine if both the `POS` and the `TAG` attributes are set.
