### ISSUE TITLE
Active Learning using uncertainty

### ISSUE THREAD

**Issue by m-michalek** [explosion/spaCy#4060]
Is it possible to get a certainty score for each token or sentence? I want to use spaCy in my **bachelor thesis** about active learning for named entity recognition. My first approach would be active learning with uncertainty sampling, but therefore I need my model to support me an indication about how certain it is with its predictions.

It looks like prodigy also uses [uncertainty sampling](https://support.prodi.gy/t/annotating-entities-in-text-documents/73/15) so I guess technically it should be possible for spaCy to support some kind of certainty score.

I couldn't find that kind of information in the official spaCy documentation. 

Thank you for your great tool and any help!

**Comment by svlandeg** [comment]
There is some prior literature on this topic here: Issue https://github.com/explosion/spaCy/issues/881, and, more recently, here: Issue https://github.com/explosion/spaCy/issues/2601#issuecomment-410524883.

**Comment by m-michalek** [comment]
Thank you, I will check that out!
