### ISSUE TITLE
Misidentifies the ner using goldparse

### ISSUE THREAD

**Issue by bellamkondaprakash** [explosion/spaCy#4061]
<!--- Please provide a summary in the title and describe your issue here.
Is this a bug or feature request? 
I have created the train json with "Haryana" as GPE but when it passes to GoldParse misidentifying the ner as 0 example: ('Haryana', 'NN', 'O')

**Comment by bellamkondaprakash** [comment]
Hello team,
When i given the "Haryana" as the GPE in train json but when it comes from GoldParse it comes ('Haryana', 'VBD', 'O'). How did it misidentified ? could make it to reach with the context of noun from the BILUO scheme

**Comment by svlandeg** [comment]
Not sure I fully understand the problem / question, could you please elaborate? How many examples are you training on? When you say "misidentify", do you mean that the final, trained model made a wrong prediction? Or is there a problem during training with the conversion of your training dataset to the GoldParse format?

**Comment by bellamkondaprakash** [comment]
The question is tagged entities parsed to goldparse,it is retrieved as the 'O' in the entity tag,Thank you for reverting back,i have solved it.

**Comment by svlandeg** [comment]
Ok good to hear you've been able to solve it!
