### ISSUE TITLE
nlp = English() , wont load in a Script

### ISSUE THREAD

**Issue by webscent** [explosion/spaCy#408]
from spacy.en import English
nlp = English()

when called in a python script it never loads and the process has to be killed to continue.

I installed spacy using conda, could never get it to work using pip.

**Comment by pdeburen** [comment]
A bit more information on your issue would be helpful. Did you download the english module (python -m spacy.en.download)?
Do you have enough memory on your machine for the module? It won't load for example on ec2 micro instances, see #416
