### ISSUE TITLE
endless loop when Analyzing corpus...

### ISSUE THREAD

**Issue by phiedulxp** [explosion/spaCy#4087]
## How to reproduce the behaviour

endless loop when Analyzing corpus...
```
=========================== Data format validation ===========================
✔ Loaded train.json
✔ Loaded dev.json
✔ Training data JSON format is valid
✔ Development data JSON format is valid
⠏ Analyzing corpus...
```

## Info about spaCy

* **spaCy version:** 2.1.7
* **Platform:** Windows-10-10.0.17134-SP0
* **Python version:** 3.7.3

**Comment by phiedulxp** [comment]
the  endless loop is acused by `GoldParse.__init__()` when `len(doc) >10`

**Comment by phiedulxp** [comment]
Does `projectivize/deprojectivize mechanism in Nivre & Nilsson 2005
for doing pseudo-projective parsing implementation uses the HEAD decoration
scheme` support other lang such as zh?

**Comment by phiedulxp** [comment]
I just want to know what if set `make_projective=False` in `GoldParse`
```
# if make_projective and heads is not None and deps is not None:
        #    heads, deps = nonproj.projectivize(heads, deps)
```
Will it cause any problem on `GoldParse`?

**Comment by phiedulxp** [comment]
Also in spacy\language.py
```
        for name, proc in self.pipeline:
            print(name, proc)
            if hasattr(proc, "begin_training"):
                kwargs = component_cfg.get(name, {})
                kwargs.update(cfg)
                proc.begin_training(
                    get_gold_tuples,
                    pipeline=self.pipeline,
                    sgd=self._optimizer,
                    **kwargs
                )
        return self._optimizer
```
use python -m spacy train:
print message
`parser <spacy.pipeline.pipes.DependencyParser object at 0x000001D14C5E8828>`
then endless loop

**Comment by honnibal** [comment]
I suspect you have a problem with your training data -- see the error message in your other thread.

Additionally, please edit your original message next time when updating with more information. It's also helpful if you can make the initial message more informative.
