### ISSUE TITLE
Add check for cycles in dependency trees to debug-data CLI

### ISSUE THREAD

**Issue by adrianeboyd** [explosion/spaCy#4096]
## Feature description

The debug-data CLI should also check for cycles in dependency trees.

Cycles should be identified elsewhere, too, to prevent the kind of error from #4083, but a check in debug-data would also be helpful.

**Comment by adrianeboyd** [comment]
Wait, I already get the `ValueError [E069]` from `GoldCorpus` when the corpus is loaded, so maybe it is just a matter of reporting that more cleanly.

**Comment by ines** [comment]
Yes, that's a good idea! It might also be nice to test the `debug-data` a bit more thoroughly to make sure it really works as expected – and then I can document it properly 🙂 (It's currently still considered experimental and thus undocumented – but it has held up really well and people who've tried it found it very useful.)
