### ISSUE TITLE
Flaky matcher test and ghost IDs

### ISSUE THREAD

**Issue by svlandeg** [explosion/spaCy#4098]
When merging PR #4097 we ran into an error for [test_issue_1971_4 ](https://github.com/explosion/spaCy/blob/master/spacy/tests/regression/test_issue1501-2000.py#L319) which was resolved after restarting. What [happened](https://dev.azure.com/explosion-ai/Public/_build/results?buildId=1276) is that test, which is supposed to produce 1 match like `[(1046765068364475028, 0, 3)]`, produced 1 for each token instead: `[(9223420625083070725, 0, 1), (9223420625083070725, 1, 2), (9223420625083070725, 2, 3)]`. I can't reproduce the error on my own system, even though I also run Windows and Python 3.6.

Note that the unit test has a comment:
`# Uncommenting this caused a segmentation fault` 

After discussing with @ines, this seems related to previous issues #3839 and #3291, where the matcher was producing "ghost matches" with IDs that weren't in the string store.
Possibly, the fix that was supposed to resolve the original issue (matcher segfault) didn't fully fix it...

Not very clear on how to proceed here because it's so difficult to test, but we wanted to record this for future reference.

**Comment by svlandeg** [comment]
More background: https://github.com/explosion/spaCy/issues/1971

**Comment by svlandeg** [comment]
Again [weird behaviour](https://dev.azure.com/explosion-ai/Public/_build/results?buildId=1458&view=logs) with the tests running Windows and Python 3.6, this time the flaky failing test is #3839 (noted earlier to be related) 

> Traceback (most recent call last):
  File "D:\a\1\s\spacy\tests\regression\test_issue3839.py", line 17, in test_issue3839
    assert matches[0][0] == en_vocab.strings[match_id]
AssertionError: assert 10304252664499679735 == 11920309760829426267

**Comment by honnibal** [comment]
Do we believe this resolved by #4179, or should we keep this open?

**Comment by ines** [comment]
Maybe assume it's resolved and reopen if it turns out it's not? 😅 Alternatively, we could wait for a week or two and if we don't get a random ghost match test failure, assume it's resolved?

**Comment by svlandeg** [comment]
Sure :-)

**Comment by svlandeg** [comment]
This flaky behaviour is still here :(
PR #4219 [failed ](https://dev.azure.com/explosion-ai/Public/_build/results?buildId=1602) on Windows with Python 3.6 with 

> ______________________________ test_issue_1971_4 ______________________________
> Traceback (most recent call last):
>   File "D:\a\1\s\spacy\tests\regression\test_issue1501-2000.py", line 331, in test_issue_1971_4
>     assert len(matches) == 1
> AssertionError: assert 2 == 1
>  +  where 2 = len([(10304252440187197422, 0, 2), (10304252440187197422, 1, 3)])

**Comment by ines** [comment]
Another puzzling one just now on #4219. Windows 3.7 only, likely producing a ghost ID:

```
___________________ test_matcher_sets_return_correct_tokens ___________________
Traceback (most recent call last):
  File "D:\a\1\s\spacy\tests\matcher\test_matcher_logic.py", line 144, in test_matcher_sets_return_correct_tokens
    texts = [Span(doc, s, e, label=L).text for L, s, e in matches]
  File "D:\a\1\s\spacy\tests\matcher\test_matcher_logic.py", line 144, in <listcomp>
    texts = [Span(doc, s, e, label=L).text for L, s, e in matches]
  File "span.pyx", line 118, in spacy.tokens.span.Span.__cinit__
ValueError: [E084] Error assigning label ID 9223502301541240625 to span: not in StringStore.
```

**Comment by svlandeg** [comment]
Thinking about this some more ... ghost id's could exist after calling `vocab.strings[my_string]` directly to retrieve a hash. This will succeed even if `my_string` is not known in the vocab. This is in contrast with calling `vocab["my_string"]` which will actually add `my_string` to the string store (if it was previously unknown).

So perhaps we need to carefully review all cases (there's quite a few) that call `vocab.strings[my_string]` directly?

**Comment by ines** [comment]
A new one this time on Windows, Python 3.7 ([build](https://dev.azure.com/explosion-ai/Public/_build/results?buildId=2113)):

```
    def test_issue4120(en_vocab):
        """Test that matches without a final {OP: ?} token are returned."""
        matcher = Matcher(en_vocab)
        matcher.add("TEST", None, [{"ORTH": "a"}, {"OP": "?"}])
        doc1 = Doc(en_vocab, words=["a"])
        assert len(matcher(doc1)) == 1  # works
    
        doc2 = Doc(en_vocab, words=["a", "b", "c"])
>       assert len(matcher(doc2)) == 2  # fixed
E       assert 1 == 2
E        +  where 1 = len([(9799931953538066242, 0, 1)])
E        +    where [(9799931953538066242, 0, 1)] = <spacy.matcher.matcher.Matcher object at 0x000001BA0F5D95C8>(a b c )
```

**Comment by svlandeg** [comment]
Have also been seeing quite a lot of failures on `test_issue3879` (e.g. recently [here](https://dev.azure.com/explosion-ai/Public/_build/results?buildId=2158))

**Comment by svlandeg** [comment]
Another matcher-related test [failing](https://dev.azure.com/explosion-ai/Public/_build/results?buildId=2182) :( 

> def test_issue3951(en_vocab):
>         """Test that combinations of optional rules are matched correctly."""
>         matcher = Matcher(en_vocab)
>         pattern = [
>             {"LOWER": "hello"},
>             {"LOWER": "this", "OP": "?"},
>             {"OP": "?"},
>             {"LOWER": "world"},
>         ]
>         matcher.add("TEST", None, pattern)
>         doc = Doc(en_vocab, words=["Hello", "my", "new", "world"])
>         matches = matcher(doc)
> >       assert len(matches) == 0
> E       assert 1 == 0
> E        +  where 1 = len([(1046765068364475028, 0, 1)])

**Comment by mehmetilker** [comment]
I was planning to open a new issue but I am seeing following exception randomly but looks the same problem mentioned here.

"[E018] Can't retrieve string for hash '10304854973658986072'. This usually refers to an issue with the `Vocab` or `StringStore`."

It happens every few run (same code base/no change).
And I am using matcher with spacy_stanfordnlp. Not sure it is related.

Is it possible it could be related with Bloom Embeddings ?

Spacy version 2.2.0 (same problem 2.1 as well)

**Comment by svlandeg** [comment]
Hi @mehmetilker, thanks for the report! Could be related. Can you give a bit more information on your system & Python version? And the specific code that runs into this issue, preferably with an example text?

**Comment by svlandeg** [comment]
Hopeful that PR #4423 may have fixed this. Let's keep this open for a week orso and close if we don't see any more ghost matches!

**Comment by mehmetilker** [comment]
Hi @svlandeg 
Please find version details as follows.

## Info about spaCy

* **spaCy version:** 2.2.0
* **Platform:** Windows-10-10.0.18362-SP0
* **Python version:** 3.7.4

I am trying to prepare an example code but my rules are more then 5000.
I am adding them as CITY, COUNTRY, TITLE etc...

~~~
matcher = Matcher(nlp.vocab)
matcher.add("COUNTRY", None, *[
    [{'LEMMA': 'Angola'}],
    [{'LEMMA': 'SERBIA'}]
])

matcher.add("CITY", None, *[
    [{'LEMMA': 'Tokyo'}],
    [{'LEMMA': 'Bogota'}]
])
~~~

I am sure it is not related with sentence.
Matcher gives me the start and end token index but when try to access label, throws an exception I mentioned above.
~~~python
for (match_id, start, end) in matches:
         try:
               label = doc.vocab.strings[match_id]
         except KeyError as err:
              print(err)
~~~

When it happens throws exception only for COUNTRY or only for CITY label.

Maybe  I should check vocabulary first for those labels and add them if there are not in vocab.

I will wait for a release to try.

**Comment by svlandeg** [comment]
@mehmetilker : thanks for the details. The matcher shouldn't be returning `match_id`'s that are not known in the Vocab, so that is definitely a bug. If it's an option for you to build spaCy from source, I would love to hear whether the current version on master fixes your problems. If not, let's check in the next minor patch release.

If the problem persists, feel free to open a specific issue.

**Comment by svlandeg** [comment]
Meanwhile, I've seen no ghost matches anymore in the open PRs since PR #4423 was merged. Tentatively closing this issue, but will keep an eye out. Here's to hoping we don't have to reopen :sunglasses:  :ghost:

**Comment by mehmetilker** [comment]
@svlandeg The thing is I could not understand why it happens randomly. If it is not in vocab it should throw exception on every run.

Another thing is, maybe I am wrong, it is just a label I am assigning to the rule. It is not related with the text that I am parsing. Why it has to be in vocab?

Trying to build... Unfortunately I am working on windows and every few months I need to refresh my installation. When I install Visual Studio I need to find right C++ dependency installation combination and I forgot what I have installed last time.
I still could not install v2.2.1 either. Building Windows binary wheel takes sometimes I guess.

Anyway, I will try and let you know if there is new findings.
Thank you for letting me know.

**Comment by svlandeg** [comment]
@mehmetilker : I know, it's quite a pain to get the right compiler stuff set up for Windows... (I need to format my laptop too but have been reluctanct exactly because of this!)

The original issue described here (ghost IDs) were very much the same random erratic behaviour as what you describe. We found a spot in the code where we were reading corrupt data from memory which would every once in a while result in this type of behaviour. So I really do think you're issue was the same and should also be resolved with the latest PR. In the meantime I'm afraid there's no easy workaround.

@honnibal & @ines : should we include this patch in a minor release anytime soon?

**Comment by AnneShowenHsu** [comment]
I am still getting a problem with the match_id missing from doc.vocab.strings

sentence = 'I misunderstood you'
doc = nlp(sentence)
matches = PSYCH_VERB_MATCHER(doc)
match_id, start, end = matches[0]
doc.vocab.strings[match_id]

Gives the following
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-82-532fa19bd9d0> in <module>
      3 matches = PSYCH_VERB_MATCHER(doc)
      4 match_id, start, end = matches[0]
----> 5 doc.vocab.strings[match_id]

strings.pyx in spacy.strings.StringStore.__getitem__()

KeyError: "[E018] Can't retrieve string for hash '1840701988003946082'. This usually refers to an issue with the `Vocab` or `StringStore`."
