### ISSUE TITLE
Improvements on setting attributes in merge_noun_chunks function

### ISSUE THREAD

**Issue by alaponin** [explosion/spaCy#4107]
## Feature description

It would be nice if during the merging of noun chunks the lemma would also be properly set. Currently, the lemma of the merged token is the lemma of the first word in the noun chunk sequence, which I don't think is the desired behavior in most cases. 
Additionally, it would be nice to have more flexibility in setting the attributes of the merged token. For example, I would like to keep the entity type of the root token as the entity type of the whole merged token.

**Comment by ines** [comment]
I think those both sound like reasonable defaults, so we should probably consider just adding them to the built-in function 🙂 Feel free to submit a PR btw.

We probably want to avoid introducing settings to the built-in component functions – it adds too much complexity for what they are (small wrappers around `doc.retokenize`), and once we add settings, we then also need to add serialization methods to preserve them. 

Btw, also in case others come across this issue later: the `merge_noun_chunks` function itself is tiny, so if you ever need fully custom settings that might not be good defaults, I'd recommend just copying it and writing your own:

https://github.com/explosion/spaCy/blob/250a54414b41e365dfe5f45a17ca1f2c245ca3a2/spacy/pipeline/functions.py#L7-L21

**Comment by ines** [comment]
Resolved by #4219!
