### ISSUE TITLE
spacy convert .iob fix.

### ISSUE THREAD

**Issue by vsraptor** [explosion/spaCy#4111]
## How to reproduce the behaviour

spacy convert test.iob ./

It fails if the file have tokens that contain "? , $"  f.e. PRP$ i.e. explain('PRP$') => 'pronoun, possessive'

Here is the fix. Modify the regex in iob2json.py::read_iob() , from  : 

 tokens = [re.split("[^\w\-]", line.strip())]

to:

 tokens = [re.split("[^\w\-$,?.]", line.strip())]

or it will be probably better to split on white-space, rather than enumerating all the exception cases !!

Example :

Lily NNP B-SRC
has VBZ O
sung VBN B-PRED
the DT O
blues NNS B-DTGT
all PDT O
her PRP$ O
life NN O

**Comment by BreakBB** [comment]
Could you explain a bit more what issue you have?

And if you have a fix or improvement for something it would be great if you could open a pull request.

**Comment by svlandeg** [comment]
It would indeed be helpful to understand what issues you're having with your file `test.iob`, can you elaborate?
