### ISSUE TITLE
Why can i not tag \n as entity?

### ISSUE THREAD

**Issue by damianoporta** [explosion/spaCy#4115]
Hello,
i am building a custom sentence boundaries classifier using the NER.
Basically i would like to tag the \n with EOS label (End Of Sentence).

It seems not possible because during the training I get:

>   File "/home/damiano/lavoro/python/.virtualenvs/parser/lib/python3.6/site-packages/spacy/language.py", line 475, in update
>     proc.update(docs, golds, sgd=get_grads, losses=losses, **kwargs)
>   File "nn_parser.pyx", line 413, in spacy.syntax.nn_parser.Parser.update
>   File "nn_parser.pyx", line 519, in spacy.syntax.nn_parser.Parser._init_gold_batch
>   File "transition_system.pyx", line 86, in spacy.syntax.transition_system.TransitionSystem.get_oracle_sequence
>   File "transition_system.pyx", line 148, in spacy.syntax.transition_system.TransitionSystem.set_costs
> ValueError: [E024] Could not find an optimal move to supervise the parser. Usually, this means that the model can't be updated in a way that's valid and satisfies the correct annotations specified in the GoldParse. For example, are all labels added to the model? If you're training a named entity recognizer, also make sure that none of your annotated entity spans have leading or trailing whitespace. You can also use the experimental `debug-data` command to validate your JSON-formatted training data. For details, run:
> python -m spacy debug-data --help

I must not tag all the \n characters as EOS, because of this reason i would like to use the NER to take context decisions.

A workaround could be replacing \n with a specific code/word like NL or [NL] or whatever... is this the only solution?

## Your Environment
spaCy version    2.1.8                         
Location         /home/damiano/lavoro/python/.virtualenvs/parser/lib/python3.6/site-packages/spacy
Platform         Linux-5.0.0-23-generic-x86_64-with-Ubuntu-18.04-bionic
Python version   3.6.8

**Comment by ines** [comment]
Yes, spaCy v2.1 explicitly made this illegal because whitespace-only entities were frequently misrecognised. Predicting a whitespace token as an entity is pretty much always incorrect and there's not really any reasonable NER label scheme where whitespace-only entities make sense.

While you can sometimes use the entity recognizer to predict things that are not actually named entities by definition (like EOS), we can't guarantee that this will always work, because it's just not what the model has been designed to do.

**Comment by damianoporta** [comment]
> Yes, spaCy v2.1 explicitly made this illegal because whitespace-only entities were frequently misrecognised. Predicting a whitespace token as an entity is pretty much always incorrect and there's not really any reasonable NER label scheme where whitespace-only entities make sense.
> 
> While you can sometimes use the entity recognizer to predict things that are not actually named entities by definition (like EOS), we can't guarantee that this will always work, because it's just not what the model has been designed to do.

i think using the NER is the only solution no? I mean, Sentencier cannot be used because i have not "fixed" rules. I mean take care of context. Is there any other soltuon @ines  ?
