### ISSUE TITLE
Generate generic sentences and then train the model on top of that. Is it a good idea?

### ISSUE THREAD

**Issue by AbhishekKargawal** [explosion/spaCy#4118]
I am training a model from scratch to predict food items from the text. I have tagged around 500 sentences to train my model and the accuracy is pretty good. But, I am a bit worried about the unseen real-world data so I have come up with an interesting idea. So I wanted to know some experienced person thought in this interesting idea.

So the idea is to convert the 500 sentences into maybe 10000 sentences. For that, I have first I replaced the actual entity with tag and then filled with possible entities. Example of this as follows:
------------------------------------------------------------------------
Original training Sentences: 
1. "Tesco sold fifty thousand pizza last year. " ---  Food = pizza
2. "He loves to eat pudding when he is alone." --- Food =  pudding
Generic Sentences:
1. "Tesco sold fifty thousand <Food> last year. "
2. "He loves to eat <Food> when he is alone."
Food List:
1. pizza
2. pudding
New training sentences:
1. "Tesco sold fifty thousand pizza last year. " ---  Food = pizza
2. "Tesco sold fifty thousand pudding last year. " ---  Food = pudding
3. "He loves to eat pizza when he is alone." --- Food =  pizza
4. "He loves to eat pudding when he is alone." --- Food =  pudding
------------------------------------------------------------------------
So is this a good to generate training sentences like this.
Benefits which I think:
1. More sentences.
2. The single entity will have more example instead of one or two.
3. May be high accuracy.
Issues could be:
1. Training data full of similar sentence pattern.

Thanks, Please let me know thoughts on this approach.

**Comment by svlandeg** [comment]
Hi @AbhishekKargawal - as this is an issue that is not `spaCy`-specific, it's probably best to continue the conversation at [StackOverflow ](https://stackoverflow.com/questions/57494201/spacy-generate-generic-sentences-and-then-train-the-model-on-top-of-that-is-it)where there is some response already.
