### ISSUE TITLE
spacy==2.1.6 with neuralcoref

### ISSUE THREAD

**Issue by tnmcneil** [explosion/spaCy#4121]
Trying to use huggingface neuralcoref with spacy version 2.1.6 and receive the following error when I try to add coref to the pipe:

```
RuntimeWarning: spacy.tokens.span.Span size changed, may indicate binary incompatibility. Expected 72 from C header, got 80 from PyObject
```

Have already tried this:
```
pip uninstall neuralcoref
pip install neuralcoref --no-binary neuralcoref
```

Right now the only solution seems to be using spacy 2.1.3 or lower but I need version 2.1.6 - anyone else running into this?

* Operating System: Mac OS
* Python Version Used: 3.5.1
* spaCy Version Used: 2.1.6
* Environment Information:

**Comment by adrianeboyd** [comment]
I can confirm this problem, but it works if you build neuralcoref from source. Uninstall neuralcoref, clone the neuralcoref repository, and:

```
cd neuralcoref
python setup.py build_ext --inplace
python setup.py install
```

**Comment by svlandeg** [comment]
Indeed, the `pip install neuralcoref --no-binary neuralcoref` does not work unfortunately, but installing `neuralcoref` from source (see [here](https://github.com/huggingface/neuralcoref#install-neuralcoref-from-source) or with @adrianeboyd's commands) does work.

We're discussing this with the maintainers of the neuralcoref, too, see related issue [here](https://github.com/huggingface/neuralcoref/issues/158#issuecomment-514534252).
