### ISSUE TITLE
Empty files in Norwegian lemmatizer

### ISSUE THREAD

**Issue by polm** [explosion/spaCy#4126]
Not sure if this is an issue or not, but there are several files in the Norwegian (`nb`) lemmatizer directory that are basically empty. Here's an example - this is the whole file:

```
# coding: utf8
from __future__ import unicode_literals


NOUNS = set(
    """
""".split()
)
```

The `NOUNS` object is imported and used elsewhere so maybe it's a placeholder for something but this just seems pointless. 

If this actually serves no purpose, I guess the files should be deleted. On the other hand, if it's there for a reason, it's probably best to add a comment explaining what that is.

**Comment by ines** [comment]
Yeah, I think this was probably a placeholder that was never filled in. In any case, as part of the rules overhault, it's definitely fine to delete this and/or just pass in an empty list for the noun rules when the lemmatizer is constructed.
