### ISSUE TITLE
Export SVG graphics of dependency parses

### ISSUE THREAD

**Issue by Fourthought** [explosion/spaCy#4127]
Hi Ines,

I'm using the code below from your documentation to export images of dependency parses, however, it throws up 'TypeError: write() argument must be str, not None'.

print(type(svg)) shows svg to be a <class 'NoneType'>

I don't seem to be able to find a solution online, do you have any suggestions please. Hopefully a quick solution which should take too much of your time!

`import spacy
from spacy import displacy
from pathlib import Path

nlp = spacy.load("en_core_web_sm")
sentences = [u"This is an example.", u"This is another one."]
for sent in sentences:
     doc = nlp(sent)
     svg = displacy.render(doc, style="dep")
     file_name = '-'.join([w.text for w in doc if not w.is_punct]) + ".svg" 
     output_path = Path("/images/" + file_name)
     output_path.open("w", encoding="utf-8").write(svg)`

**Comment by svlandeg** [comment]
Hi @Fourthought , when I copy your code it works exactly as expected for me: it saves two .svg pictures at the specified directory.

**Comment by Fourthought** [comment]
Thanks for checking @svlandeg 

Do you why I might be getting a NoneType class for type(svg) in the code?

**Comment by svlandeg** [comment]
Ah, that does make a difference, see the documentation [here ](https://spacy.io/usage/visualizers) and [here](https://spacy.io/usage/visualizers#jupyter): 

>  If you’re running a Jupyter notebook, displaCy will detect this and return the markup in a format ready to be rendered and exported.

Could be that you need to switch to an IDE like PyCharm for the above code to work like you intend it to - as the "expected" use-case when running `displacy.render` in Jupyter, is to visualise the contents in the notebook directly.

**Comment by Fourthought** [comment]
@svlandeg , I knew it would be something trivial, thank you so much for responding!
