### ISSUE TITLE
Unable to build spacy

### ISSUE THREAD

**Issue by StKi2** [explosion/spaCy#4134]
I am trying to setup Spacy on Mojave 10.14.6. I get this persistent build error. 
pip install spacy
 warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
 
spacy/_align.cpp:833:14: fatal error: 'complex' file not found
#include <complex>
^~~~~~~~~
2 warnings and 1 error generated.
error: command 'gcc' failed with exit status 1
----------------------------------------
 I see the header files in /usr/include and yet it will not build.  Does spacy work with the latest version of MacOs?

## Your Environment

* Operating System: 
* Python Version Used: 
* spaCy Version Used: 
* Environment Information:

**Comment by ines** [comment]
>  Does spacy work with the latest version of MacOs?

It should! I use the latest version of MacOS and I compile spaCy all the time.

Can you double-check that you have the [xcode command line tools](http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/) installed correctly?

**Comment by StKi2** [comment]
Hi there Ines, thanks for responding. Yes, I have the xcode command line
tools installed, they are there in

/Library/Developer/CommandLineTools


I can find the header files in /usr/include but the spaCy build doesnt seem
to be able to find them. Is there any special path or environment variable
I should be setting?

**Comment by honnibal** [comment]
@StKi2 Could you try again with the new v2.2 version?
