### ISSUE TITLE
How can I exactly import the en_core_web_lg?

### ISSUE THREAD

**Issue by alperendurmus** [explosion/spaCy#4145]
I am not sure my code is using the which model.
import spacy
nlp = spacy.load('en_core_web_**sm**')
doc = nlp(u"Access to documents independently of time and space")
spacy.displacy.serve(doc, style='dep')
and
import spacy
nlp = spacy.load('en_core_web_**lg**')
doc = nlp(u"Access to documents independently of time and space")
spacy.displacy.serve(doc, style='dep')
are giving the same result(arcs). They should be different.

**Comment by svlandeg** [comment]
The code you're using is correct.

Why do you think the results should be different? Ideally, both `en_core_web_sm` and `en_core_web_lg` give the correct, **identical** dependency parse. However in practice, you may ofcourse notice some differences, as they have been trained slightly differently and obtain different [accuracy results](https://spacy.io/models/en). But that's not to say that they may still make the same predictions on the same sentence.

**Comment by alperendurmus** [comment]
In fact, the difference is in the [explosion.ai](https://explosion.ai/demos/displacy). 
For example, [explosion.ai](https://explosion.ai/demos/displacy) is showing an arc labeled **xcomp** when I used the large model. Example sentence is:

> Access to documents independently of time and space 

But I am not able to see this **xcomp** arc on my local. Can you please share your [explosion.ai](https://explosion.ai/demos/displacy) options to me? How can I reach the arc labeled **xcomp** from my code?

**Comment by alperendurmus** [comment]
Any idea?

**Comment by svlandeg** [comment]
Do I understand it correctly that your questions is, why you're not seeing the same results as in the documentation?

Different models may differ a little bit in their results, and the results in the documentation are probably from an older model which is slightly different than the one you are using now in code.

You can find more information about navigating the parse tree in code [here](https://spacy.io/usage/linguistic-features#navigating),
