### ISSUE TITLE
Setting number of layers hyperparameter for Simple CNN

### ISSUE THREAD

**Issue by miskolc** [explosion/spaCy#4146]
I'm looking into the Spacy documentation for a way to set the number of layers for the `simple_cnn` (or `ensamble`) architecture for a **TextClassifier**. 
I've found the `depth` parameter in the documentation for the pretrained models https://spacy.io/api/cli#pretrain
Is there a similar parameter for the TextClassifier based models?
If not what is the default number of layers for a Simple CNN based model?

**Comment by svlandeg** [comment]
For `simple_cnn`, the depth of the `Tok2Vec` layer is called `conv_depth` and set to 4 by default, see [here](https://github.com/explosion/spaCy/blob/master/spacy/_ml.py#L326).

For `ensemble`, the parameter is called `depth` and set to 2 by default, see [here](https://github.com/explosion/spaCy/blob/master/spacy/_ml.py#L549).

You can specify these arguments in the same way as how you define the `architecture`.
