### ISSUE TITLE
Token.set_extension parameter force is not documented

### ISSUE THREAD

**Issue by johann-petrak** [explosion/spaCy#4148]
The function Token.set_extension has a kw parameter force which can be set to True, but the documentation here https://spacy.io/api/token
does not document it. The python documentation string does include the info though.
I am not sure why the information on the web "API" documentation pages differs from what is actually present in the Python code?

**Comment by honnibal** [comment]
>  I am not sure why the information on the web "API" documentation pages differs from what is actually present in the Python code?

No interesting reason --- just an oversight. We'll fix it thanks.

**Comment by honnibal** [comment]
The docs are pretty easy to edit if you want to make a PR next time: https://github.com/explosion/spaCy/commit/ce4c3e520491a07b516459840314e565a8e273ce

**Comment by johann-petrak** [comment]
Thanks! I was just assuming those tables would get generated automatically :)
