### ISSUE TITLE
Converting data for spacy train CLI

### ISSUE THREAD

**Issue by kormilitzin** [explosion/spaCy#4149]
While I'm following the examples #3813 , I'm stuck with this problem:

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-11-1d23120a4961> in <module>
>       9     print(doc.ents)
>      10     #json_docs.append(doc.to_json())
> ---> 11     json_docs.append(docs_to_json(doc, id=i))
>      12 
>      13 with open(os.path.join(path_to_data, 'train_set.json'), 'w') as fh:
> 
> gold.pyx in spacy.gold.docs_to_json()
> 
> doc.pyx in sents()
> 
> ValueError: [E030] Sentence boundaries unset. You can add the 'sentencizer' component to the pipeline with: nlp.add_pipe(nlp.create_pipe('sentencizer')) Alternatively, add the dependency parser, or set sentence boundaries by setting doc[i].is_sent_start.

 How to reproduce the behaviour

```
import spacy
from spacy.gold import docs_to_json


TRAINING_DATA = [{"text": "Horses are too tall and they pretend to care about your feelings", "entities": [(0, 6, 'ANIMAL')]},
{"text": "Do they bite?", "entities": []},
{"text": "horses are too tall and they pretend to care about your feelings", "entities": [(0, 6, 'ANIMAL')]},
{"text": "horses pretend to care about your feelings", "entities": [(0, 6, 'ANIMAL')]},
{"text": "they pretend to care about your feelings, those horses", "entities": [(48, 54, 'ANIMAL')]},
{"text": "horses?", "entities": [(0, 6, 'ANIMAL')]}]

nlp = spacy.load('en_core_web_lg')

json_docs = []
for i, training_data_i in enumerate(TRAINING_DATA ):
    doc = nlp.make_doc(training_data_i['text'])
    doc[0].is_sent_start = True
    doc.ents = [doc.char_span(s, e, label=L) for s, e, L in training_data_i["entities"]]
    print(doc.ents)
    json_docs.append(docs_to_json(doc, id=i))
    
with open(os.path.join(path_to_data, 'train_set.json'), 'w') as fh:
    fh.write(json.dumps(json_docs))

```

I'm getting the aforementioned error.

HOWEVER (!!!), If I change the line:

` json_docs.append(docs_to_json(doc, id=i))` -> `json_docs.append(doc.to_json())`

then it works. BUT (!!!), If I use the resulted `train_set.json` file, the CLI spacy training fails with:

>   File "gold.pyx", line 130, in spacy.gold.GoldCorpus.__init__                
>   File "gold.pyx", line 141, in spacy.gold.GoldCorpus.write_msgpack           
>   File "gold.pyx", line 181, in read_tuples                                   
>   File "gold.pyx", line 393, in _json_iterate                                 
>   File "gold.pyx", line 307, in json_to_tuple                                 
> KeyError: 'paragraphs'                                      

                 
Any ideas how to properly convert `TRAINING_DATA` into a format that is compatible with spacy CLI train? Thanks.

## Info about spaCy                                                     
                                                                        
* **spaCy version:** 2.1.7                                              
* **Platform:** Linux-4.15.0-55-generic-x86_64-with-Ubuntu-18.04-bionic 
* **Python version:** 3.6.8                                             
* **Models:** en

**Comment by ines** [comment]
>  `json_docs.append(docs_to_json(doc, id=i))` -> `json_docs.append(doc.to_json())`

This currently isn't expected to work. The `doc.to_json` method returns a general-purpose JSON representation of the `Doc`. But it doesn't return the gold-standard training data format. That's what `docs_to_json` is for. Sorry this is a bit confusing at the moment – we do plan to unify the formats and make them easier to generate, but that'd be a breaking change.

>  ```python
> doc = nlp.make_doc(training_data_i['text'])
> doc[0].is_sent_start = True
> ```

Pretty sure the sentence boundary problem happens here: You're only using `make_doc`, which will only apply the tokenizer. Then you're setting the sentence start to `True` for the first token, but *not* to `False` for the subsequent tokens. spaCy now allows sentence boundaries to be explicitly unset (`None`), so in order to confirm that boundaries have been applied, you want to set both `True` and `False`. Alternatively, you could also just call the `sentencizer` on the `Doc`.

**Comment by kormilitzin** [comment]
@ines , many thanks! I replace then with `nlp = spacy.load('en_core_web_lg', disable=['ner'])` and `doc = nlp(training_data_i['text'])`. The resulting gold data set is:

> {'id': 0,
>  'paragraphs': [{'raw': 'Horses are too tall and they pretend to care about your feelings',
>    'sentences': [{'tokens': [{'id': 0,
>        'orth': 'Horses',
>        'tag': 'NNS',
>        'head': 1,
>        'dep': 'nsubj',
>        'ner': 'U-ANIMAL'},
>       {'id': 1,
>        'orth': 'are',
>        'tag': 'VBP',
>        'head': 0,
>        'dep': 'ROOT',
>        'ner': 'O'},
>       {'id': 2,
>        'orth': 'too',
>        'tag': 'RB',
>        'head': 1,
>        'dep': 'advmod',
>        'ner': 'O'},
>       {'id': 3,
>        'orth': 'tall',
>        'tag': 'JJ',
>        'head': -2,
>        'dep': 'acomp',
>        'ner': 'O'},
>       {'id': 4,
>        'orth': 'and',
>        'tag': 'CC',
>        'head': -3,
>        'dep': 'cc',
>        'ner': 'O'},
>       {'id': 5,
>        'orth': 'they',
>        'tag': 'PRP',
>        'head': 1,
>        'dep': 'nsubj',
>        'ner': 'O'},
>       {'id': 6,
>        'orth': 'pretend',
>        'tag': 'VBP',
>        'head': -5,
>        'dep': 'conj',
>        'ner': 'O'},
>       {'id': 7,
>        'orth': 'to',
>        'tag': 'TO',
>        'head': 1,
>        'dep': 'aux',
>        'ner': 'O'},
>       {'id': 8,
>        'orth': 'care',
>        'tag': 'VB',
>        'head': -2,
>        'dep': 'xcomp',
>        'ner': 'O'},
>       {'id': 9,
>        'orth': 'about',
>        'tag': 'IN',
>        'head': -1,
>        'dep': 'prep',
>        'ner': 'O'},
>       {'id': 10,
>        'orth': 'your',
>        'tag': 'PRP$',
>        'head': 1,
>        'dep': 'poss',
>        'ner': 'O'},
>       {'id': 11,
>        'orth': 'feelings',
>        'tag': 'NNS',
>        'head': -2,
>        'dep': 'pobj',
>        'ner': 'O'}],
>      'brackets': []}]}]}

Then I used CLI to train (just for the sake of running the model, for dev set I used the same as train set), but then it failed again:

> (spacy) kormilitzin@dataCentre_1stRackFromBottom:/mnt/sdf/work/projects/med9_trans$ CUDA_VISIBLE_DEVICES=3 python -m spacy train en model_1 data/train_set.json data/train_set.json -b en_core_web_lg -p ner                        
> Training pipeline: ['ner']                                                                                                                                                                                                                 
> Starting with base model 'en_core_web_lg'                                                                                                                                                                                                  
> Counting training words (limit=0)                                                                                                                                                                                                          
>                                                                                                                                                                                                                                            
> Itn    Dep Loss    NER Loss      UAS    NER P    NER R    NER F    Tag %  Token %  CPU WPS  GPU WPS                                                                                                                                        
> ---  ----------  ----------  -------  -------  -------  -------  -------  -------  -------  -------                                                                                                                                        
>                                                                                                                                                                                                                                            
>   0%|                                                                                                                                                                                                               | 0/47 [00:00<?, ?it/s]
>                                                                                                                                                                                                                                            
>                                                                                                                                                                                                                                            
>                                                                                                                                                                                                                                            
> ✔ Saved model to output directory                                                                                                                                                                                                          
> model_1/model-final                                                                                                                                                                                                                        
>                                                                                                                                                                                                                                            
> ⠙ Creating best model...                                                                                                                                                                                                                   
> ⠹ Creating best model...                                                                                                                                                                                                                   
> ⠸ Creating best model...                                                                                                                                                                                                                   
> ⠼ Creating best model...                                                                                                                                                                                                                   
> ⠴ Creating best model...                                                                                                                                                                                                                   
> ⠦ Creating best model...                                                                                                                                                                                                                   
> ⠧ Creating best model...                                                                                                                                                                                                                   
> ⠇ Creating best model...                                                                                                                                                                                                                   
> ⠏ Creating best model...                                                                                                                                                                                                                   
> Traceback (most recent call last):                                                                                                                                                                                                         
>   File "/mnt/sdf/work/spacy/lib/python3.6/site-packages/spacy/cli/train.py", line 257, in train                                                                                                                                     
>     losses=losses,                                                                                                                                                                                                                         
>   File "/mnt/sdf/work/spacy/lib/python3.6/site-packages/spacy/language.py", line 471, in update                                                                                                                                     
>     proc.update(docs, golds, sgd=get_grads, losses=losses, **kwargs)                                                                                                                                                                       
>   File "nn_parser.pyx", line 413, in spacy.syntax.nn_parser.Parser.update                                                                                                                                                                  
>   File "nn_parser.pyx", line 516, in spacy.syntax.nn_parser.Parser._init_gold_batch                                                                                                                                                        
>   File "ner.pyx", line 106, in spacy.syntax.ner.BiluoPushDown.preprocess_gold                                                                                                                                                              
>   File "ner.pyx", line 165, in spacy.syntax.ner.BiluoPushDown.lookup_transition                                                                                                                                                            
> KeyError: "[E022] Could not find a transition with the name 'U-ANIMAL' in the NER model."                                                                                                                                                  
>                                                                                                                                                                                                                                            
> During handling of the above exception, another exception occurred:                                                                                                                                                                        
>                                                                                                                                                                                                                                            
> Traceback (most recent call last):                                                                                                                                                                                                         
>   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main                                                                                                                                                                     
>     "__main__", mod_spec)                                                                                                                                                                                                                  
>   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code                                                                                                                                                                                
>     exec(code, run_globals)                                                                                                                                                                                                                
>   File "/mnt/sdf/work/spacy/lib/python3.6/site-packages/spacy/__main__.py", line 35, in <module>                                                                                                                                    
>     plac.call(commands[command], sys.argv[1:])                                                                                                                                                                                             
>   File "/mnt/sdf/work/spacy/lib/python3.6/site-packages/plac_core.py", line 328, in call                                                                                                                                            
>     cmd, result = parser.consume(arglist)                                                                                                                                                                                                  
>   File "/mnt/sdf/work/spacy/lib/python3.6/site-packages/plac_core.py", line 207, in consume                                                                                                                                         
>     return cmd, self.func(*(args + varargs + extraopts), **kwargs)                                                                                                                                                                         
>   File "/mnt/sdf/work/spacy/lib/python3.6/site-packages/spacy/cli/train.py", line 368, in train                                                                                                                                     
>     best_model_path = _collate_best_model(meta, output_path, nlp.pipe_names)                                                                                                                                                               
>   File "/mnt/sdf/work/spacy/lib/python3.6/site-packages/spacy/cli/train.py", line 431, in _collate_best_model                                                                                                                       
>     path2str(best_component_src / component), path2str(best_dest / component)                                                                                                                                                              
> TypeError: unsupported operand type(s) for /: 'NoneType' and 'str'                                                                                                                                                                         
> (spacy) kormilitzin@dataCentre_1stRackFromBottom:/mnt/sdf/work/projects/med9_trans$ CUDA_VISIBLE_DEVICES=3 python -m spacy train en model_1 data/train_set.json data/train_set.json -b en_core_web_lg -p ner                        
>                                                                                                                                                                                                                                            
> 

It feels like I'm nearly there, I'm also reading #3782

**Comment by adrianeboyd** [comment]
I've run into this kind of error, which seems to be related to not having enough examples in the training data for a particular label.

If you train a new model rather than `-b en_core_web_lg` then the CLI train works as expected with a small number of examples.

I've been wondering if there's a graceful way to handle this?

**Comment by kormilitzin** [comment]
Thanks for ideas! The large number of example is not a problem, I just wanted (and presented here) a minimal running conceptual example how to train spacy model using CLI and the conversion file. I will try with more example and update the tread.

**Comment by adrianeboyd** [comment]
`-b` assumes that the model already has the components you want to update and `en_vectors_web_lg` doesn't include an `ner` component. If you want to load vectors from a model, use `-v`.

To make it easier to debug/help, let's focus on one issue at a time, though. I think that the train command from your earlier comment should work if you have a larger number of training examples. Does it?

**Comment by kormilitzin** [comment]
> `-b` assumes that the model already has the components you want to update and `en_vectors_web_lg` doesn't include an `ner` component. If you want to load vectors from a model, use `-v`.
> 
> To make it easier to debug/help, let's focus on one issue at a time, though. I think that the train command from your earlier comment should work if you have a larger number of training examples. Does it?

Makes perfect sense! Let me try the previous one with more examples and I'll update the thread here. Thanks for help.

**Comment by adrianeboyd** [comment]
On the other hand, if you don't want to update the existing NER model, then `-v` instead of `-b` would make sense and it might be easier to get a minimal example working.

**Comment by kormilitzin** [comment]
> On the other hand, if you don't want to update the existing NER model, then `-v` instead of `-b` would make sense and it might be easier to get a minimal example working.

I am training a completely new NER model (not re-using one of the space's). Normally I would use their explicit script and it worked, but now I wanted to train CLI and then all failed.

Just to confirm, with `-v en_vectors_web_lg` worked as a charm! Thanks!

**Comment by adrianeboyd** [comment]
Okay, then `-b` is definitely not the right option for your task. Glad everything is working!
