### ISSUE TITLE
💫 Matcher issues with 'OP': '?'

### ISSUE THREAD

**Issue by ines** [explosion/spaCy#4154]
Creating a master issue for some of the reported `Matcher` bugs, especially those related to `'OP': '?'` (optional tokens) to keep things in one place. We believe that they're all likely related to the same root cause and should be fixed at the same time. Each reported test case is already reflected in a regression test.

* #3879: False positive matches on subsequent OPs in the Matcher patterns
  Regression test: [`test_issue3879.py`](https://github.com/explosion/spaCy/blob/master/spacy/tests/regression/test_issue3879.py)
* #3951: Issue with several optional rule in Token Matcher
  Regression test: [`test_issue3951.py`](https://github.com/explosion/spaCy/blob/master/spacy/tests/regression/test_issue3951.py)
* #4120: Matches without a final {OP: ?} token are not returned
  Regression test: [`test_issue4120.py`](https://github.com/explosion/spaCy/blob/master/spacy/tests/regression/test_issue4120.py)

**Comment by svlandeg** [comment]
Fixed Issues 3879 and 3951 in PR #4162 - there was a small bug in the code that caters for subsequent RETRY actions, like those triggerd by `"OP": "?"`.

Will continue the hunt for Issue 4120.

**Comment by svlandeg** [comment]
The trouble with Issue 4120 was related (in the same part of the algorithm) but not exactly the same bug. Think I also fixed it - more details in PR #4166.

**Comment by ines** [comment]
Thanks @svlandeg, you're amazing! 👍 Can't believe I already get to close this – I was worried that those issues would keep haunting us for a while 😅
