### ISSUE TITLE
Wrong language code for the Serbian language

### ISSUE THREAD

**Issue by BLKSerene** [explosion/spaCy#4155]
Hi, I'm wondering that shouldn't the language code for Serbian be `sr` rather than `rs` (according to [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes))?

And since Serbian uses either the [Cyrillic alphabet](https://en.wikipedia.org/wiki/Serbian_Cyrillic_alphabet) or the [Latin alphabet](https://en.wikipedia.org/wiki/Gaj%27s_Latin_alphabet), is there any need to distinguish between the two writing systems (e.g. sr-Cyrl for Serbian Cyrillic and sr-Latn for Serbian Latin according to [ISO 15924](https://en.wikipedia.org/wiki/ISO_15924)) in spaCy to make things more clear (the newly-added stop words for Serbian in #4078 uses the Cyrillic alphabet)?

Similar issues: #2339 (Norwegian Bokmål and Norwegian Nynorsk), #1308, Simplified Chinese and Tradition Chinese

* Operating System: Windows 10 64-bit
* Python Version Used: 3.7.4
* spaCy Version Used: 2.1.8

**Comment by svlandeg** [comment]
Hm, I think you're right, it should be "sr" (in fact @ines got it right with the issue labels!)

**Comment by svlandeg** [comment]
This is only a recent addition (cf PR #4078) so we can probably still change this without breaking too many people's code.

CC @Pavle992

**Comment by Pavle992** [comment]
I agree that it should be **sr**, I was using the usual abbreviation for [republic of serbia](https://en.wikipedia.org/wiki/Country_codes_of_Serbia). I will create new update asap.

**Comment by svlandeg** [comment]
Thanks for fixing this so quickly with PR #4159 !
