### ISSUE TITLE
Lowercasing causes different tokenization result

### ISSUE THREAD

**Issue by Halvani** [explosion/spaCy#4157]
If I lowercase a specific text, the resulting token sequence differs from the one of the original text. This happens in particular in cases where fullstops are attached to short strings. For example, "St." results in "st", while the fullstop "." dissapears. The same problem occurs when a text contains a fullstop without a separating space. For example, "similarity.In" results in "similarity" and then "in" such that the fullstop "." again dissapears.

Here is a shoprt example: 
---------------------------------
import spacy

def read_text(path):
    with open(path, encoding="utf-8") as f:
        return f.read()

nlp = spacy.load("en_core_web_sm", disable=["parser", "ner"])
p = r"Some_Text_File.txt"

text_normal = read_text(p)
text_lower = read_text(p).lower()
doc_normal = nlp(text_normal)
doc_lower = nlp(text_lower.lower())

// At some point you can notice what caused the wrong tokenization...
for i, token in enumerate(doc_normal):
    if doc_lower[i] != doc_normal[i]:
        print(token, doc_lower[i])

**Comment by svlandeg** [comment]
Hi @Halvani. That is correct, the models are trained on text that is properly capitalized and punctuated. When those lexical clues are removed from the input, by e.g. lowercasing everything, the model will have a harder time making correct predictions.
