### ISSUE TITLE
NER Model results are not satisfying

### ISSUE THREAD

**Issue by Farnod-glitch** [explosion/spaCy#4161]
## Your Environment

* Operating System: Windows/Linux
* Python Version Used: 3.6.8
* spaCy Version Used: 2.1
* Environment Information: CPU: Intel Core i5-7300U with 16 GB Ram

Am am trying to figure out, how to improve the results of my Spacy NER model. My trainings data is a text document with sentences in every line. I am using the PhraseMatcher to tokenize a this text document. I am also using your "Training an additional entity type" on the Spacy page. 
1) I don't know how to train my own Model with one specific Label (My label consists of 12 vocabularies
2) I don't know what the loss function has to say and how to build in the eval function.

**Comment by BreakBB** [comment]
To train an additional entity type it is very important to have enough *representative* trainings data of the new entity type and to also include previously learned entities and some sentences with no entity at all.

How many sentences are in your text document and do I understand you correctly that you tokenize them just to create your trainings data from the text document?

**Comment by Farnod-glitch** [comment]
Yes I don't label the trainings data manually, I am using the Phrasematcher from Spacy. For the Model I am only using the labelt sentences. I only want to train my own Model not another, this is the reason why I don't use other Labels. I am not sure how to mix sentences with and whith out labels, can you recomend a mix ratio. I am using 950 Labelt sentences.

**Comment by BreakBB** [comment]
Well if you don't need other labels than your own there is indeed no need to add examples of existing labels.

About the unlabelt sentences it really depends on your situation. If you're expecting a lot of texts with no entity at all then you should train your model that way. If you expect that all the texts have entities then you should only add a few or none.
If you can't tell I would start with something about 10% (just a feeling not some scientific value) and test around with it.

Could you explain what exactly you mean by "my label consistis of 12 vocabs"?

**Comment by Farnod-glitch** [comment]
I will test it out your idea with the mixture, thank you.
"Could you explain what exactly you mean by "my label consistis of 12 vocabs"?" I mean that my own label as an example (ANIMAL) does have 20 entities which wil be detected as the Label.
"Horses are too tall and they pretend to care about your feelings.", {"entities": [(0, 6, ANIMAL)]},
or "A lion pride consists of a few adult males, related females and cubs.", {"entities": [(2, 6, ANIMAL)]},
As in this example there are 2 entities, which will be recognised as the label ANIMAL
