### ISSUE TITLE
Unexpected behavior during convert .iob to json file

### ISSUE THREAD

**Issue by F0rge1cE** [explosion/spaCy#4170]
## How to reproduce the behaviour

I try to call `python -m spacy convert <path> ./ -t json -c iob` with this labeled NER training corpus:
[https://github.com/EuropeanaNewspapers/ner-corpora/blob/master/enp_DE.onb.bio/enp_DE.onb.bio](url)

After the conversion, you can get a json file with content:
```
[
  {
    "id":0,
    "paragraphs":[
      {
        "sentences":[
          {
            "tokens":[
              {
                "orth":"November",
                "tag":"-",
                "ner":"O"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "id":0,
    "paragraphs":[
      {
        "sentences":[
          {
            "tokens":[
              {
                "orth":"Heute",
                "tag":"-",
                "ner":"O"
              }
            ]
          }
        ]
      }
    ]
  },
......
```
Such behavior is really weired. Seems that every separate token is considered as a whole sentence and a paragraph. 

Another issue has already mentioned here: #4111 , which will cause exception when the token contains any non-word char ("[^\w\-]" in the regex scope).

## Your Environment

* Operating System: OSX 10.13.6
* Python Version Used: 3.7.3
* spaCy Version Used: 2.1.8
* Environment Information: N/A

**Comment by adrianeboyd** [comment]
This looks like a bug. I'll take a look.

**Comment by adrianeboyd** [comment]
For a temporary solution that uses `-c ner`, see: https://stackoverflow.com/q/57551479/461847

(The OCR errors are probably going to cause a lot of problems and I suspect that the lack of sentence/document boundaries is going to cause problems during training. Even if automatic sentence boundaries aren't perfect, it would be better to divide the data into sentence-ish segments for shuffling/batching during training.)
