### ISSUE TITLE
if I give a text with html tags Spacy NER will ignore html tags and recognize named entity between raw text only.

### ISSUE THREAD

**Issue by Anticsss** [explosion/spaCy#4177]
## Feature description
Sometimes it is difficult to retain the original structure of text from which we recognize named entities. For example I have text between standard html tags(ex. web page source) and while recognizing named entity from text I remove all the html tags and give raw text to Spacy NER engine but after prediction if I want to display text in original format with surrounded html tags it is not possible. it will break the originality of data.

if there is feature in spacy that can ignore specific pattern while recognizing named entities from text it will helpful to retain the originality of text. 

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
If so, we will tag it as [`project idea`](https://github.com/explosion/spaCy/labels/project%20idea) so other users can take it on.

It will be a custom component so other users can specify the pattern which they want to ignore.

**Comment by adrianeboyd** [comment]
This is a very reasonable thing to want to do, but it's really outside the scope of spacy. While processing your text, you just need to create a character position mapping between the raw text and your HTML string.

One very simple way to do this initially is to replace all the HTML tags with spaces rather than removing them, so the character positions don't change. The sentence boundaries might not be quite where you want as a result of extra whitespace, but you'd have to test that out with your data.

**Comment by Anticsss** [comment]
What if i want to again replace the original html tags with spaces ? I may not know which html tags I have to replace with which space.

In stanfordcorenlp if word is tagged to 'O' than it ignores the word while training if spacy has similar kind of ignoring capability of specified pattern it would be easier to recognize named entities without doing pre-processing and displaying the text in original format.

**Comment by adrianeboyd** [comment]
I'm sorry, I'm not sure I understand your question about spaces. I meant that you could overwrite each HTML tag with spaces so the position of each text character in the string didn't shift (`<p>` would be replaced with three spaces). It's a kind of hacky suggestion in any case, so the less hacky option of creating a character position mapping between an HTML string and a plain text string should be simple enough.

All of spacy's pretrained models are intended to work with plain text and won't work well if there are HTML tags present in the text. If you want to work with HTML you will have to handle the preprocessing and postprocessing steps outside of spacy.
