### ISSUE TITLE
Dataflow ValueError: spacy.syntax.nn_parser.Parser size changed, may indicate binary incompatibility. Expected 72 from C header, got 64 from PyObject [while running 'ParDo(CollectQuestions)']

### ISSUE THREAD

**Issue by yasminalounis** [explosion/spaCy#4180]
Hello, I'm using SpaCy to do some preprocessing in a dataflow pipeline (based on apache beam),
I installed SpaCy using the beam setup.py as a specific requirement,
When I launch the pipeline I got on "spacy.load('en')"

ValueError: spacy.syntax.nn_parser.Parser size changed, may indicate binary incompatibility. Expected 72 from C header, got 64 from PyObject [while running 'ParDo(CollectQuestions)']

Is it a version issue, or just the dataflow environment?
I have already downgraded SpaCy, but no result, I have also tried to install with --no-binary option

* Python Version Used:
3.7
* spaCy Version Used:
2.1.8
* Environment Information:
GCP

**Comment by honnibal** [comment]
This error indicates that some compiled C files have been generated expecting a previous version of spaCy. If the `ParDo` collection is in your code, try cleaning out the `.c`, `.cpp` or `.so` files that were built against the previous version, and then run your `setup.py` again.

**Comment by yasminalounis** [comment]
Thank you for the answer, the problem was solved by adding the installation of spacy in the setup.py of beam as a custom command
Before:
`REQUIRED_PACKAGES = [
    'spacy',
]

setuptools.setup(
    name='PM-beam-pipeline',
    version='0.0.1',
    description=' NLP on beam',
    install_requires=REQUIRED_PACKAGES,
    packages=setuptools.find_packages(),
)
`
After:
`
CUSTOM_COMMANDS = [
    ['apt-get', 'update', '--assume-yes'],
    ['apt-get', '--assume-yes', 'install', 'libsnappy-dev', 'libyaml-dev', 'wget', 'unzip', 'hunspell'
        , 'libhunspell-dev', 'myspell-en-gb', 'myspell-fr'],
    ['pip', 'install', 'spacy_hunspell'],
    ['python', '-m', 'spacy', 'download', 'en'],
    ['python', '-m', 'spacy', 'download', 'fr'],
    ['pip', 'install', 'spacy-langdetect'],
]


class CustomCommands(setuptools.Command):
    def initialize_options(self):
        pass

    def finalize_options(self):
        pass

    def RunCustomCommand(self, command_list):
        print ('Running command: %s' % command_list)
        p = subprocess.Popen(
            command_list,
            stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        stdout_data, stdout_err = p.communicate()
        print ('Command output: %s | Command err: %s' % (stdout_data, stdout_err))
        if p.returncode != 0:
            raise RuntimeError(
                'Command %s failed: exit code: %s' % (command_list, p.returncode))

    def run(self):
        for command in CUSTOM_COMMANDS:
            self.RunCustomCommand(command)

setuptools.setup(
    name='PM-beam-pipeline',
    version='0.0.1',
    description='ETL NLP on beam',
    packages=setuptools.find_packages(),
    cmdclass={
        # Command class instantiated and run during pip install scenarios.
        'build': build,
        'CustomCommands': CustomCommands,
    }
)
`
Because I'm using also hunspell
