### ISSUE TITLE
RuntimeError Error: Numpy 1.15.0 requires Python version >= 3.5.

### ISSUE THREAD

**Issue by PoojaPradeep** [explosion/spaCy#4185]
## How to reproduce the problem

```bash
# copy-paste the error message here
```

## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by PoojaPradeep** [comment]
Error: File "/tmp/pip-build-gyfVq7/numpy/setup.py", line 31, in <module>
        raise RuntimeError("Python version >= 3.5 required.")

Operating System: Ubuntu 14.04
Python Version Used: Python 2.7

**Comment by honnibal** [comment]
Is it possible for you to use Python 3 for your project? If so that would be the preferred solution.

I thought pip should be smart enough to use the correct numpy version for Python2.7, and generally installation on Python2.7 works --- our CI service tests this. Perhaps you need to update your pip?

**Comment by PoojaPradeep** [comment]
No, I need it to be installed for Python 2.7 only. I have updated the pip and setuptools but still it's not working. Is there any other way to resolve this issue?

**Comment by PoojaPradeep** [comment]
Am I missing anything during installation? Please let me know if is there any other way to install spacy on python 2.7. I have also cloned the package but still, it's giving the same error.

**Comment by ines** [comment]
Can you install numpy 1.15.0 separately? How you do it doesn't matter – but if it's present in the environment, pip should be happy when you install spaCy.

**Comment by PoojaPradeep** [comment]
hey, @ines Thanks and it works properly when I tried it for spacy 2.1.0. Previously I was trying for spacy 2.1.8. Also, I have reinstalled the system-level dependencies.
