### ISSUE TITLE
How to use PreTrained BERT Model for Textclassification?

### ISSUE THREAD

**Issue by snape6666** [explosion/spaCy#4194]
Hi,
i saw the new release of spacy v2.1 and the new bert model for german. Iam new in this area, but would like to get started with the combination of BERT and spacy.

I would like to classify German free text requirements. Since we don't have a lot of training data available (about 100-200 sentences per class with about 6 requirement classes), I became interested in BERT, which is why I would like to test it for this use case.

How large must the training data be for us to achieve meaningful results with the pre-trained model? Are there any examples of using the new models?

Thank you in advance!

## Your Environment
* newest spacy version (today 2019.08.25)
* Windows 10
* Anaconda Python 3.7

**Comment by adrianeboyd** [comment]
An example script for text classification is in the [spacy-pytorch-transformers](https://github.com/explosion/spacy-pytorch-transformers/) repository:

https://github.com/explosion/spacy-pytorch-transformers/blob/master/examples/train_textcat.py

We have seen promising initial results with just 200 instances for English, but it really depends on the data, so you'll have to try it out for your task.

**Comment by snape6666** [comment]
Thx for the quick response! Looking forward to test it! =)
