### ISSUE TITLE
Getting Memory Error 

### ISSUE THREAD

**Issue by AbhayGodbole** [explosion/spaCy#4196]
Hi
When I am trying to build a model to extract my custom entities, I am getting memory error.
There are 9000 comments data that I have from which I need to extract custom entities
steps:
1. created tagged tsv file contents around 125000 words
2. converted tsv to josn
3. converted json to spacy required format.
4. executed the function for creating new model using the file in step 4. While executing getting memory error. PFA the error SS and the .py file
[memoryError.zip](https://github.com/explosion/spaCy/files/3539776/memoryError.zip)

 
## Your Environment
========== Info about spaCy ======
spaCy version    2.1.8
Platform         Windows-10-10.0.16299-SP0
Python version   3.7.1
Models           en
Memory: 8GB

Please help

**Comment by ines** [comment]
How long are your texts on average? 8 GB RAM should be fine (although 16 is often better), but if one of your texts is super long, it's possible you're just running out of memory. The easiest solution would be to split your texts into smaller chunks.

**Comment by AbhayGodbole** [comment]
I checked the Max length of comment, it is 267. Is this a very long string to process?

**Comment by AbhayGodbole** [comment]
Hi
I figured out the issue. I was using the custom WhiteSpace Tokenizer ( I wanted to retain the hyphen separated dates) that some how disturbed sentence generation while converting tagged csv to json, and generated long sentences and that could be the reason behind Memory error. 
Surprisingly the memory error is not coming, when I try the same on my Linux machine at home..
