### ISSUE TITLE
Split dev-dependencies into requirements-dev.txt

### ISSUE THREAD

**Issue by Froskekongen** [explosion/spaCy#4201]
spaCy should split its development requirements into a separate file (e.g. `requirements-dev.txt`). There is no reason for keeping dependency and build requirements in the main `requirements.txt` file, and only makes it harder to integrate spaCy in complex projects. 
## Your Environment
This suggestion is not environment dependent.

**Comment by ines** [comment]
Hi! What's your workflow like, and when do you install from the `requirements.txt`? Are you building spaCy from source?

In general, the `requirements.txt` should only be needed if you're building from source, and the `setup.py` only includes the runtime dependencies.

**Comment by Froskekongen** [comment]
Understood. Now we are installing from pypi, but we needed to pull a specific hash at some time, and then we used requirements, which is not needed. I think this can be closed.
