### ISSUE TITLE
Training Custom NER model with Pretraining using ELMO /  BERT

### ISSUE THREAD

**Issue by keshav787** [explosion/spaCy#4204]
Since Spacy v2.1 supports BERT/ELMO pre-training . Is it possible somehow to use ELMO while training a custom NER model? If yes then how? If No then can we have this feature in the releases to come.

**Comment by ines** [comment]
One thing to note is that spaCy doesn't *exactly* include BERT or ELMO pretraining – but it includes a pretraining mechanism that's similar and also produces pre-trained context-sensitive representations from raw text.

That's the main idea: all of these approaches are about producing better representations that the models can use during training. spaCy's [`pretrain` functionality](https://spacy.io/api/cli#pretrain) is one way to create them. If you have existing pre-trained BERT or ELMO representations and want to make them available in spaCy, check out [this comment](https://github.com/explosion/spaCy/issues/3772#issuecomment-498008841) for code examples.

We also show an approach for using pre-trained transformer models in [`spacy-pytorch-transformers`](https://github.com/explosion/spacy-pytorch-transformers). If you check out the model implementation, you can see how the representations are used. It does require new and more specific implementations, though, and we haven't developed a new and custom NER model yet ([see here for background](https://github.com/explosion/spacy-pytorch-transformers/issues/23#issuecomment-526732208)).
