### ISSUE TITLE
Conjugation of verbs

### ISSUE THREAD

**Issue by rrrepos** [explosion/spaCy#4206]
## Feature description
Is there a plan to add conjugation (tense, 1st or 3rd, singular or plural) to the Spacy library?

**Comment by ines** [comment]
Language generation is not a priority for the core library – but there's are third-party plugins that you can add to your spaCy pipeline: 

* https://github.com/bjascob/pyInflect
* https://github.com/bjascob/LemmInflect

Also see #3171 (merging the two issues to keep things in one place).

**Comment by rrrepos** [comment]
oh. thanks
