### ISSUE TITLE
Same text input, but got different token tag_ and dep_ with different version of spacy model&languages 

### ISSUE THREAD

**Issue by yano27** [explosion/spaCy#4211]
Hello, I tested spacy with two different version and the same text produce two different dependency and tags.

## Your Environment
Operating System: windows 10
Python version: 3.6
First Test: 
- spacy version: 2.0.13
- model: de_core_news_sm 2.0.0 
- environment: anaconda, jupyterNotebook

Second Test: 
- spacy version: 2.1.8
- model: de_core_news_sm 2.1.0 
- environment: visualStudio, django

## How to reproduce the behaviour

The text that I tested is "Das Auto muss gleich gelb sein"
![chrome_2019-08-29_16-25-22](https://user-images.githubusercontent.com/33882480/63949494-cd423580-ca7a-11e9-9273-9ea7ae27e438.png)

And the first test result
![chrome_2019-08-29_16-25-34](https://user-images.githubusercontent.com/33882480/63949571-efd44e80-ca7a-11e9-87a6-fc7c5c694355.png)

second test result
![python_2019-08-29_16-12-14](https://user-images.githubusercontent.com/33882480/63949616-fa8ee380-ca7a-11e9-814f-7d20409bfaf7.png)

As you can see the dep and tag from "gelb" and "muss" are different. 
And when I change the word "gelb" to "blau" on the second test 
![python_2019-08-29_16-32-08](https://user-images.githubusercontent.com/33882480/63950075-a5070680-ca7b-11e9-8766-107be17ed690.png)
The tag will change from VVPP into an ADJD.
I would like to know if it is a bug by the language model or something else, and what should I do to get the same result from older version in the newer version from Spacy? Because I have a function that are using the dependecy and POS-Tagging as parameter from the older version (first test)

Thank you

**Comment by ines** [comment]
That's not _that_ surprising – models are statistical and different models trained with different settings may produce different results. Even if a model is more accurate overall (on a given evaluation set), it may make different mistakes.

There's not really a way to just "get the same predictions" with a different model. If you know the mistakes you don't want it to make, you can add manual fixup rules. Or you can update it with more examples similar to your data and fine tune it.

Also merging this with #3052.

**Comment by yano27** [comment]
Okay, thanks for your feedback :)
