### ISSUE TITLE
Retokenization when text changes

### ISSUE THREAD

**Issue by rrrepos** [explosion/spaCy#4215]
For my use-case, I read a document (multiple sentences) and perform some cleanup in the pipeline. This includes sending the document via a coref pipe to replace some text content. Another custom cleanup could include removing sentences that are irrelevant. The question I have is: 
A. is there a way to update and/ or delete text from the original text?
B. If so, Is there some way I can retokenize the document? 

Currently, I store the text in an intermediary file / stream and re-open it as a new doc. Thanks

**Comment by adrianeboyd** [comment]
There's no way to do this currently, but see #4128 for a discussion of the same issue.

**Comment by rrrepos** [comment]
Thanks @adrianeboyd .
