### ISSUE TITLE
Bad interpretation for a french word using fr_core_news_sm-2.1.0 

### ISSUE THREAD

**Issue by dadadel** [explosion/spaCy#4216]
## How to reproduce the behaviour

Using the french model `fr_core_news_sm` leads to a bad interpretation of word `"musique"` when it is given alone.

### Incorrect behaviour

It is recognized as ADJ while it can never be an adjective as it is always a noun (even if the verb `"musiquer"` exists, but if the word is used isolated it is a noun).
```python
import spacy
spacy = spacy.load("fr_core_news_sm")
text = "musique"
for token in spacy(text):
    print(token, token.tag_)
text2 = "la musique"
for token in self.spacy(text2):
    print(token, token.tag_)
```
```
musique ADJ__Number=Sing
```
![musique_adj](https://user-images.githubusercontent.com/1339801/64007293-2d38ea80-cb14-11e9-890f-391ca77a61e0.png)

### Correct behaviour

When it is in a sentence like `"la musique"` it is well recognized as NOUN.
```python
import spacy
spacy = spacy.load("fr_core_news_sm")
text2 = "la musique"
for token in self.spacy(text2):
    print(token, token.tag_)
```
```
la DET__Definite=Def|Gender=Fem|Number=Sing|PronType=Art
musique NOUN__Gender=Fem|Number=Sing
```
![musique_noun](https://user-images.githubusercontent.com/1339801/64007285-290ccd00-cb14-11e9-8981-f5188ce64a3b.png)

## The Environment

* Operating System: Ubuntu 19.04
* Python Version Used: python 3.7
* spaCy Version Used: spaCy 2.1.8 / fr_core_news_sm-2.1.0

**Comment by ines** [comment]
There's not really a point in giving the tagger and parser single words. They're trained to predict words *in context*, so if you just give the model a single word without context, how are they supposed to predict the correct tags? 

The results you get will be completely arbitrary because there's nothing to base the prediction on (like, surrounding words and a *real sentence*). Models are statistical and their predictions are based on the context and the data they were trained on (typically, natural language text).

**Comment by dadadel** [comment]
You're right Ines, but we can sometimes say something like just `"musique !"` or `"musique Maëstro !"`.
However, in that case, `"musique"` is definitely NOT an adjective, in any case nor any context.
So this is an issue !

Actually, the issue I met was getting "musiqu" as the lemma of "musique" while I was expecting "musique". I need lemmas because I am working on an AI with speech recognition and I need to check some expecting words. The stems are not enough precise so the lemmas were the good option but if spaCy's language model has such errors it is difficult to have a reliable analysis.
