### ISSUE TITLE
Heroku build problem with fixed versions in requirements.txt

### ISSUE THREAD

**Issue by loganyc1934** [explosion/spaCy#4223]
I'm trying to use spacy with `en_core_web_sm` model on Heroku and had build issues. I looked at some similar previous issues but didn't see one that has exactly the same problem, so I'm opening a new one. Please let me know if this is a known issue, what is the best solution here (avoid pip freeze or something).

## How to reproduce the problem

I included 

```
spacy>=2.0.0,<3.0.0
https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz#egg=en_core_web_sm
```

as instructed [here](https://spacy.io/usage/models#production). Then I did `pip freeze` and my requirements.txt looks like this 

```
alembic==1.1.0
APScheduler==3.6.1
autopep8==1.4.4
blis==0.2.4
certifi==2019.6.16
chardet==3.0.4
Click==7.0
cycler==0.10.0
cymem==2.0.2
en-core-web-sm==2.1.0
Flask==1.1.1
Flask-Migrate==2.5.2
Flask-SQLAlchemy==2.4.0
gevent==1.4.0
greenlet==0.4.15
gunicorn==19.9.0
idna==2.8
itsdangerous==1.1.0
jellyfish==0.5.6
Jinja2==2.10.1
joblib==0.13.2
kiwisolver==1.1.0
Mako==1.1.0
MarkupSafe==1.1.1
matplotlib==3.1.1
murmurhash==1.0.2
numpy==1.17.1
Pillow==6.1.0
plac==0.9.6
preshed==2.0.1
psycopg2-binary==2.8.3
pycodestyle==2.5.0
pyparsing==2.4.2
python-dateutil==2.8.0
python-dotenv==0.10.3
python-editor==1.0.4
pytz==2019.2
requests==2.22.0
scikit-learn==0.21.3
scipy==1.3.1
six==1.12.0
spacy==2.1.8
SQLAlchemy==1.3.8
sqlitedict==1.6.0
srsly==0.1.0
thinc==7.0.8
tqdm==4.35.0
tweet-preprocessor==0.5.0
tzlocal==2.0.0
urllib3==1.25.3
us==1.0.0
wasabi==0.2.2
Werkzeug==0.15.5
wordcloud==1.5.0
```

With this, I push to Heroku and it fails with the following error

```
-----> Installing requirements with pip
       Collecting alembic==1.1.0 (from -r /tmp/build_1dda2d7d8fcdc780d5ec99f2fb927a0e/requirements.txt (line 1))
         Downloading https://files.pythonhosted.org/packages/9a/0f/a5e8997d58882da8ecd288360dddf133a83145de6480216774923b393422/alembic-1.1.0.tar.gz (1.0MB)
       Collecting en-core-web-sm==2.1.0 (from -r /tmp/build_1dda2d7d8fcdc780d5ec99f2fb927a0e/requirements.txt (line 10))
         Could not find a version that satisfies the requirement en-core-web-sm==2.1.0 (from -r /tmp/build_1dda2d7d8fcdc780d5ec99f2fb927a0e/requirements.txt (line 10)) (from versions: )
       No matching distribution found for en-core-web-sm==2.1.0 (from -r /tmp/build_1dda2d7d8fcdc780d5ec99f2fb927a0e/requirements.txt (line 10))
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

**Comment by svlandeg** [comment]
As the error message state, there is no package called "en-core-web-sm", you'll have to include the full URL as you did in your original `requirements.txt` file.

**Comment by loganyc1934** [comment]
@svlandeg Please read my post first. My original requirements.txt has

```
spacy>=2.0.0,<3.0.0
https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz#egg=en_core_web_sm
```

THEN I did the pip freeze. And THERE IS a `"en-core-web-sm"` package in the list. The problem is not there isn't one. I even added the full url to the pip freeze version of the requirements.txt, then the error becomes "Double requirements given" because there is a clash with the `en-core-web-sm==2.1.0` line there.

**Comment by svlandeg** [comment]
I did read your first post, and I do think the answer still is that you'll have to include the full URL in your `requirements.txt` for Heroku exactly as you did in your original `requirements.txt` file.

I realise it's annoying that `pip freeze` does not retain the original URL, and the output of it does not work directly as you'd hoped. It sees `en-core-web-sm` as a package, but it's not as such available to dowload/install with `pip`. So you'll have to make sure the statistical models in the `requirements.txt` have the full URL, e.g. by removing `en-core-web-sm==2.1.0` and inserting `https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz#egg=en_core_web_sm`.

**Comment by loganyc1934** [comment]
@svlandeg thanks for the reply. This makes sense now, but it's a clear gotcha for model installation in requirements.txt. I guess what I want is to install model correctly by pip, similar to the ask here https://github.com/explosion/spaCy/issues/3536
