### ISSUE TITLE
No more matching on NORM?

### ISSUE THREAD

**Issue by mr-bjerre** [explosion/spaCy#4224]
I might be remembering wrong but wasn't it possible to match on the norm of a word a while back with the Token matcher?

I can't seem to find anything about it in the documentation anymore, nor creating custom norm exceptions.

I would use it for having a norm for single-token month expressions (that would be faster than having a matcher setting custom attributes, right?)

**Comment by svlandeg** [comment]
You're right that it should be possible to match on the norm of a word, using `PhraseMatcher(en_vocab, attr="NORM")`. However, recently we did [identify](https://github.com/explosion/spaCy/issues/4002) ánd [fix](https://github.com/explosion/spaCy/pull/4080) a bug in that code. Could you try pulling in the latest version from the `master` branch and check whether your custom exceptions work then?

If they still don't work - can you provide a minimal non-working example?

**Comment by mr-bjerre** [comment]
Sorry I might not have been too clear. I am looking for the docs on it. I can’t really make my minimal example without :-)

**Comment by svlandeg** [comment]
The documentation is [here](https://spacy.io/usage/rule-based-matching#phrasematcher-attrs), and in your case you'd set `attr="NORM"`. It doesn't explicitly mention the `NORM` attribute as an option in the docs, but it should work. Feel free to open a new issue in case you would run into a bug. Generic questions on your specific use-case are probably best discussed on StackOverflow, so we can keep this tracker mainly for bugs and feature requests ;-)

**Comment by mr-bjerre** [comment]
Got it. But a few months back there were some documentation on creating custom norm exceptions though which is a different thing (that’s why I posted here). I want to set the norm for some specific tokens but I suppose the reason is that I should use custom attribute instead now.

**Comment by svlandeg** [comment]
Ah, hmm, I'm not exactly sure what you mean. There's documentation around [norm exceptions](https://spacy.io/usage/adding-languages#norm-exceptions) in the context of defining new languages - maybe that's what you remember?

**Comment by mr-bjerre** [comment]
Ah yes. Turns out I was simply bad at searching the docs. I will be more thorough next time. Thanks for your help Sofie !
