### ISSUE TITLE
Entity ruler and ner outputs not as expected

### ISSUE THREAD

**Issue by AnnaAnia** [explosion/spaCy#4227]
I have a custom NER model created in Spacy and loaded from file. Trying to add an entity ruler as per code below. Output is either the ruler or ner but not a combination where entities wouldnt overlap. 

Is this a bug or am I missing somthing?

`ner_model_ruler = spacy.load(r"***path_to_model***")`
```
patterns=[{"label":"COVER_TYPE_R","pattern":[{"LOWER":"word_1"},{"LOWER":"word_2"}]},
          ..... ]
```

```
ruler = EntityRuler(ner_model_ruler,validate=True)
ruler.add_patterns(patterns)
ner_model_ruler.add_pipe(ruler,after='ner') 
```

Help would be very much appreciated.

## Your Environment

* Python Version Used: 3.7
* spaCy Version Used: 2.1.5

**Comment by adrianeboyd** [comment]
You should be able to use an NER model and the EntityRuler to label entities that **don't overlap** in the same text. If the NER model has already labeled a span, the EntityRuler skips any overlapping entities unless you add the option `overwrite_ents=True`.

I can't reproduce this error with a toy example, but it's also hard to figure out what's going on without more details about the custom model or patterns. Is it possible that your custom NER entities and the EntityRuler entities do overlap in many cases? What happens if you try this:

```
ruler = EntityRuler(ner_model_ruler, validate=True, overwrite_ents=True)
ruler.add_patterns(patterns)
print([(ent.text, ent.label_, ent.start, ent.end) for ent in ner_model_ruler(text).ents])
ner_model_ruler.add_pipe(ruler, after='ner')
print([(ent.text, ent.label_, ent.start, ent.end) for ent in ner_model_ruler(text).ents])
```

Do you see EntityRuler entities in place of NER entities in the second line?

**Comment by AnnaAnia** [comment]
@adrianeboyd thank you. I will check tomorrow following your advice. I have tried with overwrite=True, but will reproduce again and make notes

**Comment by AnnaAnia** [comment]
@adrianeboyd  I have tested your print suggestions and no, I'm not seeing EntityRuler entities in place of NER in the second print

**Comment by adrianeboyd** [comment]
Add this to the comparison?

```
print([(ent.text, ent.label_, ent.start, ent.end) for ent in ner_model_ruler(text).ents])
ruler = EntityRuler(ner_model_ruler, validate=True, overwrite_ents=True)
ruler.add_patterns(patterns)
print([(ent.text, ent.label_, ent.start, ent.end) for ent in ner_model_ruler(text).ents])
ner_model_ruler.add_pipe(ruler, after='ner')
print([(ent.text, ent.label_, ent.start, ent.end) for ent in ner_model_ruler(text).ents])
```

There are some bugs with interactions between EntityRuler and NER (#4042, #4229), but so far only if the EntityRuler is before NER. Again, without knowing more about your models/output, it's really hard for us to debug. 

Can you make a similar example with the default 'en' model and some EntityRuler labels that shows the problem?

**Comment by AnnaAnia** [comment]
@adrianeboyd something very odd. I have reloaded the model again and run the same as before including your prints and I'm now I'm seeing the EntityRuler entities in place of NER entities
