### ISSUE TITLE
nlp.use_params:  'bool' object has no attribute 'use_params'

### ISSUE THREAD

**Issue by tsoernes** [explosion/spaCy#4228]
## How to reproduce the behaviour
When using multiprocessing or joblib to train multiple texcats. I get errors when trying to save the model, but only *sometimes*. Most of the time it works.
```
trainer_ = partial(
    trainer,
    labels=labels,
    n_iter=n_iter,
    dropout=dropout,
    learn_rate=learn_rate,
    batch_start=batch_start,
    batch_max=batch_max
)
with Pool(processes=4) as pool:
    pool.starmap(trainer_, zip(model_dirs, train_data))

def trainer(
    model_dir,
    train_data,
    labels,
    n_iter,
    dropout,
    learn_rate,
    batch_start,
    batch_max,
):
    nlp = spacy.load('en_core_web_lg')
    print(f"Starting {model_dir}")
    config = {"exclusive_classes": False, "architecture": 'bow'}
    textcat = nlp.create_pipe("textcat", config=config)
    nlp.add_pipe(textcat, last=True)

    for label in labels:
        textcat.add_label(label)

    batch_sizes = compounding(batch_start, batch_max, 1.001)
    other_pipes = [pipe for pipe in nlp.pipe_names if not pipe != "textcat"]
    with nlp.disable_pipes(*other_pipes):
        optimizer = nlp.begin_training()
        # handle_ctrlc(nlp, optimizer, model_dir, None, None, None)
        for epoch in range(1, n_iter + 1):
            losses = {}
            random.shuffle(train_data)
            batches = minibatch(train_data[:100], size=batch_sizes)
            for batch in batches:
                texts, cats = zip(*batch)
                nlp.update(texts, cats, sgd=optimizer, drop=dropout, losses=losses)
    print(f"Finished {model_dir}")
    with nlp.use_params(optimizer.averages):
        textcat.to_disk(model_dir)
```

## Your Environment

* Operating System: Fedora 30
* Python Version Used: 3.7
* spaCy Version Used: spacy                      2.1.8           
* Environment Information: 

```
"""
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/nlp/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/ubuntu/anaconda3/envs/nlp/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/ubuntu/fintechdb/nlp/catml/textcat/train_hierarchy.py", line 103, in trainer
    with nlp.use_params(optimizer.averages):
  File "/home/ubuntu/anaconda3/envs/nlp/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/ubuntu/anaconda3/envs/nlp/lib/python3.7/site-packages/spacy/language.py", line 675, in use_params
    next(context)
  File "pipes.pyx", line 152, in use_params
AttributeError: 'bool' object has no attribute 'use_params'
"""
```

**Comment by svlandeg** [comment]
Hmm, odd. So in general what happens is that the `model` of your pipeline component is set to `True` by default when running `nlp.create_pipe`. Then this model gets properly initialized when calling `nlp.begin_training` (if the pipe is not disabled). So by the time you call `nlp.use_params`, which is delegated to `model.use_params` of the pipeline component, the model should be properly instantiated and not still be a `bool`. 

It looks to me at first sight that your code is doing this correctly, but the error message indicates that the model has not actually been created. It's still a `bool`.

So perhaps somehow your multiprocessing approach is messing up the order of your calls?

**Comment by adrianeboyd** [comment]
Nothing to do with multiprocessing, this is the problem:

```
other_pipes = [pipe for pipe in nlp.pipe_names if not pipe != "textcat"]
```

You mean:

```
other_pipes = [pipe for pipe in nlp.pipe_names if pipe != "textcat"]
```

I could reproduce the error with the script, but the most noticeable thing was that the training was unbearably slow, which indicated that something else was going wrong. 'bow' should be really fast.

**Comment by tsoernes** [comment]
@adrianeboyd Good catch! However, I still get this error. Please note that it's intermittent -- most workers finish without error. If I switch to using
```
    with textcat.use_params(optimizer.averages):
        textcat.to_disk(model_dir)
```
instead, I get this error:
```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/nlp/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/ubuntu/anaconda3/envs/nlp/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/ubuntu/fintechdb/nlp/catml/textcat/train_hierarchy.py", line 100, in trainer
    with textcat.use_params(optimizer.averages):
AttributeError: __enter__
```

**Comment by svlandeg** [comment]
good catch @adrianeboyd :-)

@tsoernes: you can't use `with textcat.use_params`, because it's the `nlp` object that takes care of the context manager. `with nlp.use_params` should work just fine **if** all your pipes were instantiated correctly.

**Comment by adrianeboyd** [comment]
Use:

```
with nlp.use_params(optimizer.averages):
    nlp.to_disk(model_dir)
```

Are you sure the other workers were actually finishing without error (you have a model saved in the output directory that you can load and that has learned some cats)? I think your "Finished" message might be a bit misleading.

Check out how this is handled in the train CLI script to get an idea:

https://github.com/explosion/spaCy/blob/419ae59c79bada005a807d468f7b173c3c163bad/spacy/cli/train.py#L272-L306

There should hopefully be support for textcat training and evaluation with the train CLI soon, which might make this a bit easier.
