### ISSUE TITLE
pytorch-transformers version 1.1.0 support

### ISSUE THREAD

**Issue by Code4SAFrankie** [explosion/spaCy#4230]
## Feature description
Can you please support pytorch-transformers version 1.1.0 otherwise I can't run spacy and flair at the same time. I hate virtualenv.

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
If so, we will tag it as [`project idea`](https://github.com/explosion/spaCy/labels/project%20idea) so other users can take it on.

**Comment by ines** [comment]
Not sure I understand the question? spaCy should be compatible with `pytorch-transformers` (in fact, we use it ourselves in the [`spacy-pytorch-transformers` package](https://github.com/explosion/spacy-pytorch-transformers). spaCy itself doesn't require `pytorch-transformers`.

**Comment by Code4SAFrankie** [comment]
Spacy is compatible with `pytorch-transformers`, but only with version 1.0.0; whereas version 1.1.0 is already out. Flair requires version 1.1.0, but Spacy then complains about not finding version 1.0.0. Could you upgrade Spacy to use version 1.1.0 of `pytorch-transformers`?

**Comment by Code4SAFrankie** [comment]
spacy-pytorch-transformers v0.4.0 fixed the issue
