### ISSUE TITLE
Unexpected Low similarity for similar tokens 

### ISSUE THREAD

**Issue by chikubee** [explosion/spaCy#4231]
## Your Environment

* Operating System: Built on Google Colab
* Python Version Used: python 3
* spaCy Version Used: 2.1.8
* spacy-pytorch-transformers verison: 2.1.1

I was wondering if you could help me understand why there is extremely low similarity for some genuinely similar cases.
Sentence1: I am a salaried person
Sentence2: I am a person who gets salary
The similarity between the tokens salaried and salary is extremely less.
While Sentence2 actually matches with other sentences in the corpora relevant to salary, Sentence1 does not.

Does it have something to do with the word-pieces as salaried gets broken into sal ##ari ##ed?
And how exactly is the final vector constructed from wordpieces for a particular token?

<img width="866" alt="Screenshot 2019-09-04 at 11 21 04 AM" src="https://user-images.githubusercontent.com/25073753/64229399-4cb28780-cf07-11e9-8455-3bf2818b4a61.png">

**Comment by ines** [comment]
See @honinbal's comment in explosion/spacy-pytorch-transformers#55:

> There's many dimensions of "similarity". The word "salaried" is an adjective, so in some ways it's more similar to any other adjective than it will be to "salary".
>
> In general it's quite hard to predict how the model will assign similarities before you train it. You might need to train it for the specific behaviours you want.

(Btw, it's usually better to only open an issue once in the relevant repo – in this case, `spacy-pytorch-transformers`. This makes it easier for us to keep track of the questions and it also ensures we don't waste time by answering the same issue twice.)

**Comment by chikubee** [comment]
@ines I am sorry but I am still struggling, what are you suggesting? Don't you think 0.22 similarity is way too less even if salaried is an adjective. Maybe the technique of alignment of word-pieces or the way they are combined here to get to the token vector is questionable?
