### ISSUE TITLE
How does textcat deal with multi-sentence passages?

### ISSUE THREAD

**Issue by H20Watermelon** [explosion/spaCy#4233]
## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.7
* spaCy Version Used: 2.1.8

I wonder how spaCy's `textcat` computes scores for longer passages. Since CNN typically requires a fixed length sequence (typically when I train CNN models for text classification). But for longer passages, does spaCy simply chops off part of a long passage, or does it do some kind of averaging based on individual sentences (if there are multiple sentences). Thanks!

**Comment by honnibal** [comment]
After calculating the token vectors with the CNN, we do mean pooling to extract a document vector. So we don't discard any text, no. There's nothing in the CNN algorithm that says the texts need to be fixed width --- those tend just to be implementation constraints in various libraries.
