### ISSUE TITLE
Weird Greek Lemmas

### ISSUE THREAD

**Issue by polm** [explosion/spaCy#4241]
I can not read Greek, but looking at the nouns in the `lemma_index.json` file for Greek, these are the first several entries:

    "(ιρλανδικά)", "(σκωτικά)", "(σοράνι)", "-αλγία", "-βατώ", "-βατῶ", "-ούλα", "-πληξία", "-ώνυμο", "sofa", "table", "άβακας", "άβατο", "άβατον"

I'm pretty sure parentheses don't belong there, and the things that begin with hyphens and "table" and "sofa" seem out of place.

Maybe this is due to a bug in the Wiktionary parsing script mentioned by @giannisdaras in #2558?

If someone who speaks Greek could check and clarify what, if anything, should be removed, that would be great.

**Comment by GiorgioPorgio** [comment]
Greek here. 

Parentheses don't belong there. 
Stuff beginning with hyphens are suffixes so don't belong there. 
'sofa', 'table' also don't belong there and I also spotted 'n-διάστατος' which is not a Greek lemma. 

Can take care of this is you want :) 
I can have a closer look at `lemma_index.json` to find anything that doesn't belong. Is it more helpful if I edit the file myself and push to the branch or just let you know which ones should be removed? Or some other approach (eg check the parsing script)?

**Comment by ines** [comment]
@GiorgioPorgio Thanks! You could submit a PR to the `spacy-lookups-data` repo here: https://github.com/explosion/spacy-lookups-data/

**Comment by GiorgioPorgio** [comment]
@ines Happy to help! Ready to submit my PR.
Also, 8 lemmas in total included the English 'o' char instead of Greek. Not sure why, but changed that these 'o's to Greek to be consistent and because they're different character codes. 

One Q though:
Should I make the .github/contributors/giorgioporgio.md? I don't mind of course, but asking because it's such a tiny tiny contribution :)

**Comment by ines** [comment]
@GiorgioPorgio The contributor agreement is up to you – for a small change like this, it's okay to leave it out for now.

**Comment by ines** [comment]
See explosion/spacy-lookups-data#3 (note that the changes will be reflected in `Greek` with the next release of `spacy-lookups-data`, but the models still include the previous data until we retrain them).
