### ISSUE TITLE
Docs: difference between POS and TAG / origins of these

### ISSUE THREAD

**Issue by poke1024** [explosion/spaCy#4242]
As shown in the table in https://spacy.io/usage/linguistic-features#pos-tagging, spacy differentiates two kinds of POS tags (POS and TAG). Probably I'm just a newbie, but is there some docs, which kind of philosophy these are based on? TAG seem to be based on Penn TreeBank tags, POS on a more universal set (as in Petrov, Slav, et al. "A Universal Part-of-Speech Tagset"). Any additional explanation on this would be helpful for the docs I guess, especially for people like me ;-)

**Comment by adrianeboyd** [comment]
The details about the annotation schemes are here:

https://spacy.io/api/annotation

(It would probably be useful to link here from the language-specific model pages, since I've also thought it was a bit hard to find.)
