### ISSUE TITLE
[T008] Bad configuration of Tagger.

### ISSUE THREAD

**Issue by achyutjoshi** [explosion/spaCy#4243]
Hi! I was just importing the model(en_core_web_lg) and I got this error  - ` [T008] Bad configuration of Tagger. This is probably a bug within spaCy. We changed the name of an internal attribute for loading pre-trained vectors, and the class has been passed the old name (pretrained_dims) but not the new name (pretrained_vectors).`

## My Environment

* **spaCy version:** 2.0.18
* **Platform:** Darwin-18.5.0-x86_64-i386-64bit
* **Python version:** 3.7.2
* **Models:** en_core_web_lg

**Comment by svlandeg** [comment]
Hi @achyutjoshi , could you run `python -m spacy validate` and paste the output here so we can check in more detail?

**Comment by achyutjoshi** [comment]
Installed models (spaCy v2.0.18)
    /Users/apple/miniconda3/envs/nlp/lib/python3.7/site-packages/spacy

    TYPE        NAME                  MODEL                 VERSION
    package     en-core-web-lg        en_core_web_lg        2.0.0    ✔
    link        en_core_web_lg        en_core_web_lg        2.0.0    ✔

**Comment by ines** [comment]
Just released v2.2, which comes with new models. Could you try again with the new version and models? If the issue still persists, feel free to reopen.
