### ISSUE TITLE
Spanish is identifying compound verbs as nouns

### ISSUE THREAD

**Issue by sontek** [explosion/spaCy#4253]
## How to reproduce the behaviour
```
>>> import spacy
>>> nlp = spacy.load('es')
>>> sentence = "No puedo hacerlo."
>>> doc = nlp(sentence)
>>> for token in doc:
...     print(token.text, token.lemma_, token.pos_, token.tag_, token.dep_, token.shape_, token.is_alpha, token.is_stop)
...
```

Which returns:

- No No ADV ADV__Polarity=Neg advmod Xx True True
- puedo poder AUX AUX__Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin ROOT xxxx True True
- hacerlo hacerlo NOUN NOUN__Gender=Masc|Number=Sing obj xxxx True True
. . PUNCT PUNCT__PunctType=Peri punct . False False

`hacerlo` is Compound of the infinitive hacer and the pronoun lo.  It is not a noun.

## Info about spaCy

* **spaCy version:** 2.1.8
* **Platform:** Darwin-18.0.0-x86_64-i386-64bit
* **Python version:** 3.6.7
* **Models:** es

* Operating System: OSX
* Python Version Used: Python3.6

**Comment by ines** [comment]
Merging this with #3052. It's less useful to have these reports and test cases as separate issues – they're typically not immediately actionable, because these things come down to the statistical models. 

Maybe inaccuracies here point to a deeper problem, maybe they're just something that has to be accepted because of the training data that's available and the fact that models are statistical. (Even if a model is 90% accurate, every 10th prediction it makes will be wrong.)

**Comment by sontek** [comment]
I don't know how any of this works, but I did find that the stanford NLP lemmatizer picks this up correctly. It uses this under the hood:

https://github.com/UniversalDependencies/UD_Spanish-AnCora

this is the code I used to test it:

```
>>> import stanfordnlp
>>> stanfordnlp.download('es')
>>> nlp = stanfordnlp.Pipeline("es")
>>> sentence = "No puedo hacerlo."
>>> doc = nlp(sentence)
>>> doc.sentences[0].print_tokens()
<Token index=1;words=[<Word index=1;text=No;lemma=no;upos=ADV;xpos=ADV;feats=Polarity=Neg;governor=3;dependency_relation=advmod>]>
<Token index=2;words=[<Word index=2;text=puedo;lemma=poder;upos=AUX;xpos=AUX;feats=Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin;governor=3;dependency_relation=aux>]>
<Token index=3-4;words=[<Word index=3;text=hacer;lemma=hacer;upos=VERB;xpos=VERB;feats=VerbForm=Inf;governor=0;dependency_relation=root>, <Word index=4;text=lo;lemma=él;upos=PRON;xpos=PRON;feats=Case=Acc|Gender=Masc|Number=Sing|Person=3|PronType=Prs;governor=3;dependency_relation=obj>]>
<Token index=5;words=[<Word index=5;text=.;lemma=.;upos=PUNCT;xpos=PUNCT;feats=PunctType=Peri;governor=3;dependency_relation=punct>]>
```

Could we utilize some of the publicly available data they have to help better train our spanish one?
