### ISSUE TITLE
Spanish is giving the infinitive verb as the lemma for a SCONJ

### ISSUE THREAD

**Issue by sontek** [explosion/spaCy#4255]
## How to reproduce the behaviour
```
>>> import spacy
>>> nlp = spacy.load('es')
>>> sentence = "sencillo como habrían deseado."
>>> doc = nlp(sentence)
>>> for token in doc:
...     print(token.text, token.lemma_, token.pos_)
...
sencillo sencillo ADJ
como comer SCONJ
habrían haber AUX
deseado desear VERB
. . PUNCT
>>>
```

`como` in this case is conjunction in this case but the lemma is showing `comer` which is the infinitive verb.

## Info about spaCy

* **spaCy version:** 2.1.8
* **Platform:** Darwin-18.0.0-x86_64-i386-64bit
* **Python version:** 3.6.7
* **Models:** es

* Operating System: OSX
* Python Version Used: 3.6

**Comment by ines** [comment]
Spanish currently only uses simple lookup tables for lemmatization, so it's limited in ambiguous cases like this. 

See #2668 for details on the planned changes to the lemmatization. You might also want to check out @guadi1994's talk on the planned rule-based lemmatization strategy for Spanish and German: https://www.youtube.com/watch?v=88zcQODyuko&list=PLBmcuObd5An4UC6jvK_-eSl6jCvP1gwXc&index=7

**Comment by sontek** [comment]
When people start looking into this, I did find that the stanford NLP lemmatizer picks this up correctly. It uses this under the hood:

https://github.com/UniversalDependencies/UD_Spanish-AnCora

this is the code I used to test it:

```
>>> import stanfordnlp
>>> stanfordnlp.download('es')
>>> nlp = stanfordnlp.Pipeline("es")
>>> sentence = "sencillo como habrían deseado."
>>> doc = nlp(sentence)
>>> doc.sentences[0].print_tokens()
<Token index=1;words=[<Word index=1;text=sencillo;lemma=sencillo;upos=ADJ;xpos=ADJ;feats=Gender=Masc|Number=Sing;governor=0;dependency_relation=root>]>
<Token index=2;words=[<Word index=2;text=como;lemma=como;upos=SCONJ;xpos=SCONJ;feats=_;governor=3;dependency_relation=mark>]>
<Token index=3;words=[<Word index=3;text=habrÃían;lemma=haber;upos=VERB;xpos=VERB;feats=Mood=Ind|Number=Plur|Person=3|Tense=Imp|VerbForm=Fin;governor=1;dependency_relation=acl>]>
<Token index=4;words=[<Word index=4;text=deseado;lemma=deseado;upos=ADJ;xpos=ADJ;feats=Gender=Masc|Number=Sing|VerbForm=Part;governor=3;dependency_relation=obj>]>
```

Could we utilize some of the publicly available data they have to help better train our spanish one?
