### ISSUE TITLE
Spacy pretraining

### ISSUE THREAD

**Issue by keemsunguk** [explosion/spaCy#4256]
I would like to learn the theory behind the Spacy pretraining.  The website says BERT/ULMFit "like" but wish to know more detail.  Where can I find references you've used to implement pretrain module?

Thanks

## Your Environment

* Operating System: OSX, Linux
* Python Version Used: 3.7
* spaCy Version Used: 2.1
* Environment Information: conda

**Comment by ines** [comment]
You can find more details on how spaCy's pretraining works and what your "LMAO" approach is based on in the blog post: https://explosion.ai/blog/spacy-v2-1#pretraining

The idea is very similar to this paper by Kumar and Tsvetkov (2018): https://arxiv.org/pdf/1812.04616.pdf
