### ISSUE TITLE
Spacy doesnot identify GPE correctly

### ISSUE THREAD

**Issue by dhwani2410** [explosion/spaCy#4260]
I tried running my example in your binder (https://spacy.io/usage/linguistic-features#tokenization)

import spacy
​
nlp = spacy.load("en_core_web_sm")
doc = nlp(u"Trypsin-sensitive photosynthetic activities in chloroplast membranes from Chlamydomonas reinhardi, y-1.;Location of electron transport chain components in chloroplast membranes of chlamydomonas reinhardi, y-1 was investigated by use of proteolytic digestion with soluble or insolubilized trypsin.")
​
for ent in doc.ents:
    print(ent.text, ent.start_char, ent.end_char, ent.label_)

Trypsin 0 7 GPE
Chlamydomonas 74 87 GPE

As for I understand GPE is the geopolitical entity which includes Countries, Cities or location. However the result it is throwing is a chemical or an organism name.

Is there some way to rectify it.

**Comment by adrianeboyd** [comment]
The standard models are trained on news/web text and won't perform well on scientific text like this.

Instead, try the scispacy models that have been trained on scientific/biomedical corpora:

https://allenai.github.io/scispacy/
