### ISSUE TITLE
Replacing vec.bin with wordtovec model

### ISSUE THREAD

**Issue by ShwetaSood** [explosion/spaCy#427]
I am trying to replace vec.bin as per the blog: https://spacy.io/docs/tutorials/load-new-word-vectors
Code am using is as per the above cited link:
from spacy.en import English
nlp = English()
n_dimensions = nlp.vocab.load_vectors('~/Downloads/GoogleNews-vectors-negative300.bin.gz')
print n_dimensions
The file to be loaded is Google News pre-trained model on this link: https://github.com/3Top/word2vec-api
But it displays 0 as dimension. Am not able to resolve this. Please help!

**Comment by mrmechko** [comment]
I'm getting a similar error.

However, I start with a text file, one line per vector of the format:

```
word_1 float_1 float_2 ...
word_2 float_dim+1 float_dim+2 ...
...
```

The text file is then bzip'd and fed into `spacy.vocab.write_binary_vectors("vec.bz2", "vectors.bin")`.
I then try to load `vectors.bin` as above and am informed that `n_dimensions` is `0`.
