### ISSUE TITLE
GPE tagging not available using the scispacy package

### ISSUE THREAD

**Issue by dhwani2410** [explosion/spaCy#4273]
Hello i am using spacy binder to run the same text using two spacy and sci-spacy

nlp =  spacy.load("en_core_sci_sm")
nlp1 = spacy.load('en_core_web_sm')

sent = "HLA antigens in arterial occlusive diseases in Japan. Using a NIH standard lymphocytotoxicity test, a possible Japanese specific HLA antigen, HLA-BJW 22.2 was identified in 17 out of 48 patients with thromboangiitis obliterans (35.4 per cent), in 5 out of 15 patients with Takayasu's arteritis (33.3 per cent) and in 11 out of 113 normal controls (9.7 per cent). On the other hand, HLA-CWl was found in 4 out of 47 patients with arteriosclerosis obliterans (8.5 per cent) and in 41 out of 113 normal controls (36.3 per cent).

doc=nlp(sent)
doc1 = nlp1(sent)

I am not able to get any GPE tags using the sci spacy method while getting using normal spacy.
Please see below for results.

>>> for ent in doc.ents:
...     print(ent.text, ent.start_char, ent.end_char, ent.label_)
... 
HLA antigens 0 12 ENTITY
arterial occlusive diseases 16 43 ENTITY
Japan 47 52 ENTITY
NIH standard 62 74 ENTITY
lymphocytotoxicity test 75 98 ENTITY
Japanese 111 119 ENTITY
HLA antigen 129 140 ENTITY
HLA-BJW 142 149 ENTITY
patients 186 194 ENTITY
thromboangiitis obliterans 200 226 ENTITY
patients 259 267 ENTITY
Takayasu's arteritis 273 293 ENTITY
cent 304 308 ENTITY
normal controls 331 346 ENTITY
HLA-CWl 382 389 ENTITY
patients 415 423 ENTITY
arteriosclerosis 429 445 ENTITY
obliterans 446 456 ENTITY
normal controls 493 508 ENTITY

>>> for ent in doc1.ents:
...     print(ent.text, ent.start_char, ent.end_char, ent.label_)
... 
Japan 47 52 GPE
NIH 62 65 ORG
Japanese 111 119 NORP
17 173 175 CARDINAL
48 183 185 CARDINAL
35.4 per cent 228 241 MONEY
5 247 248 CARDINAL
15 256 258 CARDINAL
Takayasu 273 281 PERSON
33.3 per cent 295 308 MONEY
11 317 319 CARDINAL
113 327 330 CARDINAL
9.7 per cent 348 360 MONEY
4 403 404 CARDINAL
47 412 414 CARDINAL
8.5 per cent 458 470 MONEY
41 479 481 CARDINAL
113 489 492 CARDINAL
36.3 per cent 510 523 MONEY
>>>

**Comment by ines** [comment]
scispaCy is a package and set of models developed by Allen AI (not by us) and trained on biomedical data, with biomedical-specific categories. You can find an overview of the available entity types in the model in their documentation: https://allenai.github.io/scispacy/

They weren't trained on data labelled with `GPE` (geopolitical entity). That's not a fault in spaCy or the models – it's just how the models were designed. If you're interested in `GPE` entities, you can use a model that was trained to predict them – or train your own.
