### ISSUE TITLE
How to make models with scispacy data for GPE

### ISSUE THREAD

**Issue by dhwani2410** [explosion/spaCy#4274]
I want to extract GPE labels from biomedical data available in scispacy. Can you please share a link on how to proceed for the same

**Comment by dhwani2410** [comment]
I mean how to make models trained TO extract GPE data

**Comment by ines** [comment]
Please note that this is the **issue tracker for spaCy** and focused on bug reports and feature requests. We cannot provide individual advice on how to train your models.

As we've already explained in #4273 and #4260, you'll either need to use a pre-trained model that predicts `GPE`, or train your own. Training your own model isn't easy, though, and you'll need a lot of labelled data and make sure you're updating the model correctly. The trainig documentation is a good place to start learning about this process: https://spacy.io/usage/training
