### ISSUE TITLE
Licensing of norwegian spaCy model

### ISSUE THREAD

**Issue by miktoki** [explosion/spaCy#4280]
Referring to #3082, I have been in contact with the legal owner of noWaC, the dataset we wish to base a norwegian spaCy model on together with @jarib. They are unable to change the license of the corpus itself due to norwegian law (se explanation in section 1.2 in [the noWaC paper](https://www.aclweb.org/anthology/W10-1501)), but are willing to set up some special agreement which would allow us to use the corpus to generate the language model. They have a [standard contract](https://drive.google.com/open?id=0B5kK200rMY83ZDVXdkd2U1V1VVRRTE1VSHJBZDlLS3BsNERB) available, where we could set the cost of the license to 0, and specific terms specified in Appendix 2. I also think we should further discuss the duration of the contract with them.

As pointed out by @ines [here](https://github.com/explosion/spaCy/issues/3082#issuecomment-452316225), the language models could count as derivative works based on the corpus. 

@honnibal @ines, what do you need the terms of the contract to include? Also, is it sufficient to have the agreement in Norwegian? Do you perhaps have a template we could base the contract no, or alternatively, if their contract is used, what should be included in Appendix 2?

**Comment by ines** [comment]
@jarib Sounds good! The standard contract looks fine to me. Once we're to wire up the pretraining, we can discuss the details over email and get this signed 🙂
