### ISSUE TITLE
Define Annotation Parameters 

### ISSUE THREAD

**Issue by mpfp** [explosion/spaCy#4286]
It'd be help to have definitions of the annotation parameters in the "Training spaCy’s Statistical Models" article (e.g., in the "Simple training style" and in the code in the "Updating Named Entity Recognizer" section). 

For instance, in the code you have:

# training data
TRAIN_DATA = [
    ("Who is Shaka Khan?", {"entities": [(7, 17, "PERSON")]}),
    ("I like London and Berlin.", {"entities": [(7, 13, "LOC"), (18, 24, "LOC")]}),
]

It'd be nice to specify the the parameters of the entity annotation are (start_pos, end_pos, entity_type).  It took me a while to figure that out.

## Your Environment

* Operating System: 
* Python Version Used: 
* spaCy Version Used: 
* Environment Information:

**Comment by svlandeg** [comment]
Hi @mpfp, the training data is a list of (doc, annotation) tuples, and what could be helpful to know is that those annotations are parsed into `GoldParse` objects (see [here](https://spacy.io/usage/training#annotations)). You can find a bit more information about those `GoldParse` objects [here](https://spacy.io/api/goldparse#init), including the tuple format for `entities`.

The docs are written such that you get a high-level overview of all functionality first, and only afterwards delve into the details of everything. I realise that may sometimes be confusing if you want to know everything in detail up front... In general, the [api pages](https://spacy.io/api) are a good place to look for those implementation details.
