### ISSUE TITLE
Unclear how Spacy gets word embeddings for sentences.

### ISSUE THREAD

**Issue by LostInBayes** [explosion/spaCy#4293]
Spacy offers pre-trained vectors for words. However I have noticed that you can get vectors for sentences too:

`spacy_nlp('hello I').has_vector == True`
However I can't figure how it calculates the word2vecs from the sentences. I've tried:

```
spacy_nlp('hello I').vector == spacy_nlp('hello').vector + spacy_nlp('I').vector
False
```

```
spacy_nlp('hello I').vector/spacy_nlp('hello I').vector_norm == spacy_nlp('hello').vector/spacy_nlp('hello').vector_norm + spacy_nlp('I').vector/spacy_nlp('I').vector_norm
False
```

I can't seem to find or work out how spacy computes the w2v for sentences.

**Comment by ines** [comment]
See the docs on [word vectors and similarity](https://spacy.io/usage/vectors-similarity) here:

> Models that come with built-in word vectors make them available as the Token.vector attribute. Doc.vector and Span.vector will default to an average of their token vectors.

Sentences are `Span` objects, so their vector will be the *average* of the vectors in the span. You can also see the implementation here:

https://github.com/explosion/spaCy/blob/04d36d2471bc48548abbae6c8913b2371b68d3bf/spacy/tokens/span.pyx#L445-L459

**Comment by LostInBayes** [comment]
Hi @ines . Then there must be a bug as the average of the vectors 'hello' and 'I' do not give the vector for 'hello I'

**Comment by adrianeboyd** [comment]
The small models don't contain real word vectors, just context-sensitive tensors. You need to use md or lg models for this:

```
spacy_nlp = spacy.load('en_core_web_md')
spacy_nlp('hello I').vector == (spacy_nlp('hello').vector + spacy_nlp('I').vector)/2
```

For the small models, `.vector` for spans does still average the context-sensitive tensors, but they're only consistent in this way if the context is identical:

```
spacy_nlp = spacy.load('en_core_web_sm')
doc = spacy_nlp('hello I')
doc[0:2].vector == (doc[0].vector + doc[1].vector)/ 2
```
