### ISSUE TITLE
Custom pipes flooring all model scores for ner entity type

### ISSUE THREAD

**Issue by AnnaAnia** [explosion/spaCy#4299]
Hi, 
I'm adding a custom pipe to my custom NER model. It is inteded to enhance my entity of CMPNY with your "ORG" entity. As I'm adding the pipe in after ner, I was expecting to see better recall and possibly worse precision due more false positives. Instead all scores plumment. I can't work out where it is I'm going wrong or if something not working as expected. I would apprecite any help.

Custom pipe:
```
def company(doc):
    
    Model_Spacy = spacy.load("en_core_web_sm-2.1.0")
    
    Doc=Model_Spacy(doc.text)
    
    ent_doc=[]
    for ent in doc.ents:
        ent_doc.append(ent)
    
    add_ents=[]
    for ent in Doc.ents:
        if ent.label_ == 'ORG' and ent.end<= 300:
            add_ent = Span(Doc,ent.start,ent.end,label=CMPNY )
            add_ents.append(add_ent)
        else:
            continue
    
    ent_doc_temp=[]
    for ent in ent_doc:
        if ent.start<300:
            ent_doc_temp.append(ent)
    
    new_ents=[]
    for ent in add_ents:
        count=[]
        for e in ent_doc_temp:
            ent_range=set(range(ent.start,ent.end))
            e_range=set(range(e.start,e.end))
            if ent_range.issubset(e_range) or e_range.issubset(ent_range):
                count.append(1)
                break
            if not ent_range.isdisjoint(e_range):
                count.append(1)
                break
            else:
                continue
        if len(count)==0:
            new_ents.append(ent)
    
    for ent in new_ents:
        ent_doc.append(ent)  
    
    doc.ents=ent_doc
    
    return (doc)

```
Add pipe to model:
`Model_S215_V2.add_pipe(company, after='ner')`

Evaluate new model:

 ```
def evaluate(ner_model, examples):
        """ Evaluate spacy model with p,r & f overall scores and scores per entity """
        scorer = Scorer()
        for input_, annot in examples:
            doc_gold_text = ner_model.make_doc(str(input_))
            gold = GoldParse(doc_gold_text, entities=annot.get("entities"))
            pred_value = ner_model(str(input_))
            scorer.score(pred_value, gold)
        return scorer.scores

results = evaluate(Model_S215_V2,BLIND_S216_V2)  

```
Results before adding the pipe in:

```
'CMPNY': {'p': 40.625,
'r': 71.65354330708661, |  
'f': 51.85185185185185}, | 
``` 

Resulft after:

```
  'CMPNY': {'p': 2.0091556459816884,
   'r': 16.08961303462322,
   'f': 3.572236038887632}
```

**Comment by ines** [comment]
There are a few problem here which make the logic slightly confusing and probably more difficult to debug:

1. You're *loading* the spaCy model in the component function, i.e. every time the component is called. This is really inefficient and unnecessary. 
2. Processing the `doc.text` *again* in a pipeline component is also unideal – I can see why you've chosen this approach and combining multiple entity recognizers can be difficult (see #2920).
3. When you're creating the new `Span` objects, you're creating them with reference to the newly created `Doc` and then you add them to the *existing* `Doc`. This can potentially lead to a mismatched `Vocab` (and possibly other side-effects).
4. Do the `Doc` objects your component produces look reasonable? Does your filtering logic work correctly, or are you maybe accidentally filtering out non-overlapping previous entities?
5. Is your evaluation correct? Do all your spans have the correct label and are you comparing against the same labels? Maybe print some examples and check the differences. This should give you a lot of clues about what might be going wrong here.

We can't really help with debugging your code, and it's pretty complex and application-specific. But I hope the above points will make it easier to debug and figure out what's going wrong. If you can break the problem down to one single, simple example (ideally not using any more, just pre-set entities for demonstration) and you think there's a bug in spaCy, feel free to reopen.

**Comment by AnnaAnia** [comment]
Thanks @ines. Appreciate your comments. 
1. I was intending on loading the model only once once once the final model is build. I haven't worked out yet how best to do it
3. I'm creating the Spans to get a list of potential entities to be added to doc. It's the same "text" that is run through my ner built on blank en as is run through en_core_web_sm-2.1.0
4/5. Filtering logic seems to be working judging by examples.

One more thing: I're removed some of the obvious mislabelling of ORG and the scores have come back up.  SO...  where I thought this would only be affected precision, it appears to be affecting recall too
