### ISSUE TITLE
Duplicated definition of `Parser.tok2vec`

### ISSUE THREAD

**Issue by tamuhey** [explosion/spaCy#4302]
`Parser.tok2vec` seems to be defined twice.
Is this intentional?

https://github.com/explosion/spaCy/blob/47055d59881264635c399370e20f850c0cc22f5b/spacy/syntax/nn_parser.pyx#L134

https://github.com/explosion/spaCy/blob/47055d59881264635c399370e20f850c0cc22f5b/spacy/syntax/nn_parser.pyx#L153

**Comment by ines** [comment]
Thanks, that's definitely not intentional. Fixing! 👍
