### ISSUE TITLE
Make configuration operations return new objects? (or least add_pipe)

### ISSUE THREAD

**Issue by stuz5000** [explosion/spaCy#4311]
It looks like the steps to load a model and attach a pipline are both expensive in time and mutating. This makes it very expensive to construct a suite of tests that runs many pipeline variants with the same base model, and also tedious within the REPL when a minor change cause the need to reload a model.

It would be great if:
 - we could assume the model to be immutable
 - operations to construct new pipeline didn't require the expensive reload of a model and instead returned an object with a modified pipeline.

For example:

```
@cached
def load_model(modelname):
    # Time consuming load, just once and user cached it
    return spacy.load(modelname)

#@cached  # Not needed
def build_pipeline(modelname, feature1=False, feature2=False, ...):
    nlp = load_model(modelname)
    if feature1:
        nlp = nlp.add_pipe( Feature1(), in_place=False  )  <<<<< in_place=False, returns new object
    if feature2:
        nlp = nlp.add_pipe( Feature2(), in_place=False )
     ...
    return nlp

def test1():
    # First call is slow
    nlp = build_pipeline(modelname, feature1=False, feature2=False, ...)
    ...

def test2():
    # Fast
    nlp = build_pipeline(modelname, feature1=True, feature2=False, ...):

def test3():
    # Fast
    nlp = build_pipeline(modelname, feature1=False, feature2=False, ...):
...
```

^^^ In this example, all that's needed is for `add_pipe` to return an `nlp` object with a pipeline with the added feature, leaving the original nlp object unchanged. Pandas back-fitted this pattern by adding and `in_place` parameter to decide if the instance should be modified, or a new instance returned - seems to work OK.

Thanks.

**Comment by honnibal** [comment]
Well...Testing is pretty much the only use-case for that though? Like, for actual usage, when would you want to create a whole new pipeline when you're adding a tagger?

You also won't actually save any time, whatsoever. Like, it's expensive to load in all the word vectors and vocab, sure --- but copying the NLP object is no cheaper. The two operations basically use the same code paths.

The only thing adding a component does to the `nlp` object is modify the `nlp.pipeline` attribute. So you might find it easier to just remove your pipeline components by manipulating that variable, perhaps with the help of the `nlp.disable_pipes` method.

I don't think we would consider making `nlp.add_pipe` return a copy.

**Comment by stuz5000** [comment]
Returning a new object doesn’t imply copying all of the original
data.(similarly for pandas)

My use right now is manually experimenting with different pipelines (e.g.
enable/disable abbreviation detection, stemming, etc,) to debug failure
modes.

**Comment by honnibal** [comment]
You can always just use `nlp.disable_pipes()` --- or just manipulate the `nlp.pipeline` list.

**Comment by stuz5000** [comment]
Useful. Are pipelines the only configurable state in the model?
