### ISSUE TITLE
ValueError when loading e_core_web_sm model

### ISSUE THREAD

**Issue by Monida** [explosion/spaCy#4312]
Hi, 

I have a problem when loading the **en_core_web_sm** model. These are the steps I followed that lead to the error.

1. I installed spacy using
```bash
conda install -c conda-forge spacy
````
following instructions form [here](https://spacy.io/usage/). And the **en_core_web_sm** model using:

```bash
conda install -c conda-forge spacy-model-en_core_web_sm
````

following the instructions [here](https://anaconda.org/conda-forge/spacy-model-en_core_web_sm). 

2. Then I import spacy and the **en_core_web_sm** model in Spyder (Python 3.6) with no issues:
```Python
import spacy
import en_core_web_sm
```
3. However, when I do either:
```Python
nlp = spacy.load('en_core_web_sm')
```
or 
```Python
nlp = en_core_web_sm.load()
```
 I got the following message:

```bash
"ValueError: could not broadcast input array from shape (96) into shape (128)"
```
I read issues https://github.com/explosion/spaCy/issues/3113 and https://github.com/explosion/spaCy/issues/3226, but they don't really resemble my problem.  I can't find any other resources on the internet to help me solve this issue. Does anyone have any idea of how to fix this?

## Your Environment
* Operating System: Windows x64
* Python Version Used: Python3.6
* spaCy Version Used: 2.0.16
* Environment Information: Running Spyder3 on Miniconda3

**Comment by ines** [comment]
Can you run `python -m spacy validate` and check that the model you installed is compatible? I don't know which model is available as `spacy-model-en_core_web_sm` on conda (it's an inofficial distributon, so it'S not maintained by us).

**Comment by Monida** [comment]
Hi Ines, thank you for your quick help.

As you suggested I ran  
```bash 
python -m spacy validate 
```

and this was the output:

```bash
Installed models (spaCy v2.0.16)
    C:\Users\Public\Miniconda3\lib\site-packages\spacy

    TYPE        NAME                  MODEL                 VERSION
    package     en-core-web-sm        en_core_web_sm        2.1.0    --> 2.0.0

    Use the following commands to update the model packages:
    python -m spacy download en_core_web_sm
```

So, I ran 
```bash
    python -m spacy download en_core_web_sm
```

and after running  python -m spacy validate  again, the output was 

```bash
Installed models (spaCy v2.0.16)
    C:\Users\Public\Miniconda3\lib\site-packages\spacy

    TYPE        NAME                  MODEL                 VERSION
    package     en-core-web-sm        en_core_web_sm        2.0.0

    Use the following commands to update the model packages:
    python -m spacy download en_core_web_sm
```

Which means I downgraded the model. I then tried to load the model in Spyder and it worked!!!

I guess if I want to use the most updated version of spaCy and the models I can't do it in anaconda. But for now, it's fine because I'm just playing around with it.

Thanks!!
