### ISSUE TITLE
Glove embedding for multi-word phrases

### ISSUE THREAD

**Issue by AishwaryaAgrawal** [explosion/spaCy#4319]
Hi there,

I used spacy to load glove vectors as below -- 
`glove_vectors = spacy.load('en', vectors='en_glove_cc_300_1m_vectors')`

and then to obtain glove embeddings for phrases, as below --
`concept = 'red and white'`
`embedding = glove_vectors(u'%s' %concept).vector`

The `embedding` returned from above is a 300 dim vector. But I could not find out how multi word phrases are dealt under the hood. Could someone explain me this?

Thanks!

**Comment by svlandeg** [comment]
Cf the documentation on [vectors and similarity](https://spacy.io/usage/vectors-similarity#_title): 

> `Doc.vector` and `Span.vector` will default to an average of their token vectors. 

See also the API documentation for [`doc.vector`](https://spacy.io/api/doc#vector).

**Comment by AishwaryaAgrawal** [comment]
Thanks so much!
