### ISSUE TITLE
Spacy installation error

### ISSUE THREAD

**Issue by harish2sista** [explosion/spaCy#4323]
## How to reproduce the problem
 python -m spacy info --markdown

```bash
Traceback (most recent call last):
  File "/Users/harish2sista/anaconda2/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/Users/harish2sista/anaconda2/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/Users/harish2sista/anaconda2/lib/python2.7/site-packages/spacy/__init__.py", line 20, in <module>
    raise SystemError(Errors.E130)
SystemError: [E130] You are running a narrow unicode build, which is incompatible with spacy >= 2.1.0. To fix this, reinstall Python and use a wide unicode build instead. You can also rebuild Python and set the --enable-unicode=ucs4 flag.
```

## Your Environment

* Operating System: Mac OS
* Python Version Used: 2.7
* spaCy Version Used: 2.1.0
* Environment Information: Mojave 10.14.6

**Comment by svlandeg** [comment]
You can find some background on this in Issue #3426, explaining why a wide unicode build is necessary. Did you try following the steps outlined in the error message?

**Comment by harish2sista** [comment]
Hello, 

I have tried the solution you have mentioned. Now I am getting a new error when I run the same command,

ValueError: cymem.cymem.Pool has the wrong size, try recompiling. Expected 64, got 48. 

Could you please help me solve this?
