### ISSUE TITLE
Is there any way to use a model trained with previous version of spaCy on its newest version?

### ISSUE THREAD

**Issue by tamarit** [explosion/spaCy#4328]
I have been googling for a while but I 've not found anything which was close to this question. I suppose that due to several internal changes or models characteristics/technology/approach there is no way to reuse our models which were trained on previous spaCy version (1.8.*). However, we would like to be sure just in case we could avoid to recompute all our models.

Thanks in advance!

**Comment by honnibal** [comment]
There's no way, no, especially not v1.x, which mapped all of the strings to integers completely differently.

I'd like to bring back the linear models as an option, probably in an extension package. But you should definitely retrain.

**Comment by tamarit** [comment]
Thanks Matthew for your prompt answer. We'll retrain all our models then to get the advantages of all your nice improvements :)
