### ISSUE TITLE
Are there any plans to introduce type hints ?

### ISSUE THREAD

**Issue by tamuhey** [explosion/spaCy#4337]
## Feature description

- Which area of the library is it related to?

all

- What specific solution would you like?

Add type hints in code base, or add stub files (.pyi)

**Comment by honnibal** [comment]
Once we no longer support 2.7 and 3.5, we'll look at type hints.

Incidentally, most of our stuff is already typed, because most of the library is implemented in Cython. I'm hoping there will be a way to generate stub files from Cython, so that we don't have to repeat the type declarations.

**Comment by tamuhey** [comment]
@honnibal 
If you use stub files, you don't have to worry about 2.7 and 3.5.
Still, are you not going to adopt it?
