### ISSUE TITLE
Spanish parsing of verbs gets wrong lemma if the verb is start of sentence

### ISSUE THREAD

**Issue by sontek** [explosion/spaCy#4341]
## How to reproduce the behaviour
```
>>> import spacy
>>> nlp = spacy.load('es')
>>> sentence = 'Vea nomás, qué bonito, tía.'
>>> doc = nlp(sentence)
>>> for token in doc:
...     print(token.text, token.lemma_, token.pos_)
...
Vea Vea NOUN
nomás nomás ADV
, , PUNCT
qué qué DET
bonito bonito NOUN
, , PUNCT
tía tío NOUN
. . PUNCT
```

You can see "Vea" was considered a now when it should've been the verb "Ver".   I can fix this by lowering the string to make sure it parses it correctly, but this causes issues that I reported in #4340

## Info about spaCy

* **spaCy version:** 2.1.8
* **Platform:** Darwin-18.0.0-x86_64-i386-64bit
* **Python version:** 3.6.7
* **Models:** es

* Operating System: OSX
* Python Version Used: 3.6

**Comment by sontek** [comment]
I don't know how any of this works, but I did find that the stanford NLP lemmatizer picks this up correctly. It uses this under the hood:

https://github.com/UniversalDependencies/UD_Spanish-AnCora

this is the code I used to test it:

```
>>> import stanfordnlp
>>> stanfordnlp.download('es')
>>> nlp = stanfordnlp.Pipeline("es")
>>> sentence = "Vea nomás, qué bonito, tía."
>>> doc = nlp(sentence)
>>> doc.sentences[0].print_tokens()
<Token index=1;words=[<Word index=1;text=Vea;lemma=Ver;upos=VERB;xpos=VERB;feats=Mood=Imp|Number=Sing|Person=3|VerbForm=Fin;governor=0;dependency_relation=root>]>
<Token index=2;words=[<Word index=2;text=nomás;lemma=nomás;upos=INTJ;xpos=INTJ;feats=_;governor=1;dependency_relation=dep>]>
<Token index=3;words=[<Word index=3;text=,;lemma=,;upos=PUNCT;xpos=PUNCT;feats=PunctType=Comm;governor=5;dependency_relation=punct>]>
<Token index=4;words=[<Word index=4;text=qué;lemma=qué;upos=DET;xpos=DET;feats=PronType=Int;governor=5;dependency_relation=det>]>
<Token index=5;words=[<Word index=5;text=bonito;lemma=bonito;upos=ADJ;xpos=ADJ;feats=Gender=Masc|Number=Sing;governor=1;dependency_relation=obj>]>
<Token index=6;words=[<Word index=6;text=,;lemma=,;upos=PUNCT;xpos=PUNCT;feats=PunctType=Comm;governor=1;dependency_relation=punct>]>
<Token index=7;words=[<Word index=7;text=tía.;lemma=tía.;upos=PUNCT;xpos=PUNCT;feats=PunctType=Peri;governor=1;dependency_relation=punct>]>
```

Could we utilize some of the publicly available data they have to help better train our spanish one?

**Comment by adrianeboyd** [comment]
Unfortunately the license for this corpus (GPL) isn't compatible with spacy's (MIT), so we can't use it.

As an alternative, you can use the [spacy stanfordnlp wrapper](https://github.com/explosion/spacy-stanfordnlp) to use their models in a spacy pipeline.

**Comment by svlandeg** [comment]
With respect to the underlying inaccurate prediction, statistical models will (unfortunately) always make mistakes, see also [Ines' earlier comment](https://github.com/explosion/spaCy/issues/4254#issuecomment-529190262). It probably makes more sense to collect these kind of performance issues in a central thread rather than opening a separate issue for each. Merging with #3052.
