### ISSUE TITLE
cannot merge disjoint spans'

### ISSUE THREAD

**Issue by tnmcneil** [explosion/spaCy#4352]
I wrote a Token Matcher to capture 'measures' in my corpus- eg a number followed by a unit like 5g.  I want to expand it to capture proportions like 5g/mL but am receiving the error: cannot merge disjoint spans because 5g is already part of the tokens to merge. is it possible to use nested patterns?
## Your Environment
* Operating System: Mac OS
* Python Version Used: 3.5.1
* spaCy Version Used: 2.1.6

**Comment by adrianeboyd** [comment]
There's a utility function that can filter the spans to return the longest non-overlapping spans, which will then work with the retokenizer:

https://spacy.io/api/top-level#util.filter_spans

It would probably make sense to suggest this as a possible solution in the error message and to mention it in the retokenizer section in the docs.
