### ISSUE TITLE
NER is lumping 2 MONEY entities as one

### ISSUE THREAD

**Issue by rshahrabani** [explosion/spaCy#4354]
Hi,

NER is incorrectly combining 2 MONEY entities as one in the following sentence:

"Q2 2019 revenue decreased $1.2 million to $23.5 million, from $24.7 million in Q2 2019."  I am using en_core_web_lg for processing the above.

Is there a way to correct this and have separate entities for "$1.2 million" and "$23.5 million"?  (NOTE: It is correctly identifying "$24.7 million" as a separate MONEY entity).

The fully list of entities that the application is extracting for this sentence is:
[second quarter 2019, $1.2 million to $23.5 million, $24.7 million, second quarter 2019]

Thanks for your help,
Ronny

## Your Environment
* **spaCy version:** 2.1.4
* **Platform:** Windows-10-10.0.18362-SP0
* **Python version:** 3.7.3
* **Models:** en

**Comment by adrianeboyd** [comment]
Statistical models like the NER model aren't perfect and finding a small number of mistakes is not unexpected. The original training data used for this model (OntoNotes) treats ranges like `$89 to $109` in the context `for as little as $89 to $109` as a single MONEY entity, which is probably why it makes this kind of prediction here.

If you know that `to` should never appear in your MONEY entities, it might work to post-process the results to split these entities.

In the future, this kind of issue should be added to #3052, thanks!
