### ISSUE TITLE
noun_chunks yield inconsistent results between language models and sentences.

### ISSUE THREAD

**Issue by ggloial** [explosion/spaCy#4356]
## Description of the issue
Is this a bug or feature request? If a bug, include all the steps that led to the issue.
This might be a bug.

I want to extract the noun_chunks from the sentence 'the quick brown fox jumps over the lazy dog.'

Using the three different models for en_core_web_ return different results.
I also modified the original text to 'the quick brown foxes jump over the lazy dog.'
And got yet another set of results.
I saw https://github.com/explosion/spaCy/issues/3867 and https://github.com/explosion/spaCy/issues/3886 which are closed but I think this use case surfaces a deeper issue: the plural form of a sentence interacts with the results as do the models (sm, md, lg)

|  lang. model \ text  |  the quick brown fox jumps over the lazy dog.  |  the quick brown foxes jump over the lazy dog.  | 
|---|---|---|
|  en_core_web_sm  |  [ 'the lazy dog' ]  |  [ 'the quick brown foxes', 'the lazy dog' ]  |
|  en_core_web_md  |  [ 'the quick brown fox', 'the lazy dog' ]  |  [ 'the quick brown foxes', 'the lazy dog' ]  | 
|  en_core_web_lg  |  [ 'the quick brown', 'jumps', 'the lazy dog' ]  |  [ 'the quick brown', 'foxes', 'the lazy dog' ]  | 

Steps to reproduce:
```python
import spacy

theText1 = '''the quick brown fox jumps over the lazy dog.'''
theText2 = '''the quick brown foxes jump over the lazy dog.'''

theLangModel = "en_core_web_lg" # "en_core_web_sm" # "en_core_web_md"

theNLP = spacy.load(theLangModel)

theDoc1 = theNLP(theText1)
theDoc2 = theNLP(theText2)

print(' | ', "lang. model \ text", ' | ', theText1, ' | ', theText2, ' | ')
print("|---|---|---|")
print(' | ', theLangModel, ' | '
         , '[', ', '.join(["'"+theChunk.text+"'" for theChunk in theDoc1.noun_chunks]), ']', ' | '
         , '[', ', '.join(["'"+theChunk.text+"'" for theChunk in theDoc2.noun_chunks]), ']', ' | ')
```

## Your Environment

python -m spacy info --markdown 
Info about spaCy

* **spaCy version:** 2.1.8
* **Platform:** Darwin-18.7.0-x86_64-i386-64bit
* **Python version:** 3.7.1
* **Models:** en

python -m spacy validate
✔ Loaded compatibility table

====================== Installed models (spaCy v2.1.8) ======================
ℹ spaCy installation:
/..../Entrust/venv/lib/python3.7/site-packages/spacy

TYPE      NAME                         MODEL                        VERSION                            
package   en-pytt-xlnetbasecased-lg    en_pytt_xlnetbasecased_lg    2.1.1   ✔
package   en-pytt-bertbaseuncased-lg   en_pytt_bertbaseuncased_lg   2.1.1   ✔
package   en-core-web-sm               en_core_web_sm               2.1.0   ✔
package   en-core-web-md               en_core_web_md               2.1.0   ✔
package   en-core-web-lg               en_core_web_lg               2.1.0   ✔
link      en                           en_core_web_sm               2.1.0   ✔

* Operating System: MacOS Mojave (OSX 10.14.6)
* Python Version Used: 3.7
* spaCy Version Used: 2.1.8
* Environment Information: MacBook pro

**Comment by adrianeboyd** [comment]
Statistical NLP models are typically sensitive to differences in word form, capitalization, punctuation, etc. and in these examples the parser is making mistakes that lead to the differences in noun chunks.

The provided models are trained on web/news texts, so they will also not perform as well on texts from a different genre like this example sentence. (`fox` is going to be very rare in news texts!)

Even on news texts, the models aren't perfect, so some mistakes are to be expected. If it makes sense for your task, you can try steps like post-processing the parses to catch common kinds of errors, but you'll still have to deal with some level of noise/errors in most cases.

In the future, this kind of issue should be added to #3052, thanks!
