### ISSUE TITLE
DocBin's init has an issue with `attrs` as a `list`

### ISSUE THREAD

**Issue by paoloq** [explosion/spaCy#4367]
## Error
```
attrs = sorted(intify_attrs(attrs))
  File "attrs.pyx", line 144, in spacy.attrs.intify_attrs
AttributeError: 'list' object has no attribute 'items'
```
## How to reproduce the behaviour
`doc_bin = DocBin(attrs=["LEMMA", "ENT_IOB", "ENT_TYPE"])`

## Your Environment
* **spaCy version:** 2.2.0
* **Platform:** Linux-4.9.0-9-amd64-x86_64-with-debian-10.1
* **Python version:** 3.7.3

**Comment by honnibal** [comment]
Thanks for the report. I can't believe I didn't have tests for that :(.

We should have a patch up today.
