### ISSUE TITLE
Usage of word embeddings in NER/Textcat models

### ISSUE THREAD

**Issue by luispsantos** [explosion/spaCy#4376]
Hello, this may be a rookie question but I need to know the answer for my use case of an email booking system. I want to train from scratch the EntityRecognizer and TextCategorizer models with annotated texts from my domain, and we don't have a lot of annotated data. While I don't need to load the pre-built components, I would like to use the pre-trained embeddings. My understanding is that if I call _nlp = spacy.blank('en')_ and train the models using the training recipes, I wouldn't get the benefits of transfer learning from the embeddings. So if I were to call _nlp = spacy.load('en_core_web_md', disable=['parser', 'tagger', 'ner'])_ or just spacy.load('en_vectors_web_lg'), would I get the benefit of the pre-trained embeddings on the first layer of the NN when training from scratch the NER and Textcat models?

**Comment by svlandeg** [comment]
Hi @luispsantos : the blank models indeed don't contain pretrained word vectors, nor does `en_core_web_sm`. So you could use `en_core_web_md` or `en_core_web_lg`. Another option is to use [`en_vectors_web_lg`](https://spacy.io/models/en#en_vectors_web_lg) which doesn't have the pipeline components that you don't need anyway.
