### ISSUE TITLE
Extension is not recognized when reloading spacy doc 

### ISSUE THREAD

**Issue by moh55m55** [explosion/spaCy#4377]
Hello, 
custom extensions is not recognized when loading spacy doc object from disk. It does recognized it when the same kernal is active, however when restarting the kernal custom extensions are not recognized whereas other attributes are ok.  
For example:
```
import spacy
from spacy.tokens import Doc, Span, Token

Doc.set_extension('doc_cat',force=True,default=None )
nlp = spacy.load("en_core_web_sm")
doc=nlp("I am trying to set an extension for doc object")
doc._.set("doc_cat","AN")
doc.to_disk("corpus/mydoc")

loaded_doc = Doc(nlp.vocab).from_disk("corpus/mydoc")
print(loaded_doc._.doc_cat )## output "AN"
```
after shutting down (restarting) the kernel, I got this error: 
```
import spacy
from spacy.tokens import Doc, Span, Token
nlp = spacy.load("en_core_web_sm")
loaded_doc = Doc(nlp.vocab).from_disk("corpus/mydoc")
print(loaded_doc._.doc_cat)
```
```
AttributeError                            Traceback (most recent call last)
<ipython-input-1-0b8d370be645> in <module>
      3 nlp = spacy.load("en_core_web_sm")
      4 loaded_doc = Doc(nlp.vocab).from_disk("corpus/mydoc")
----> 5 loaded_doc._.doc_cat

~/anaconda3/envs/back/lib/python3.6/site-packages/spacy/tokens/underscore.py in __getattr__(self, name)
     33     def __getattr__(self, name):
     34         if name not in self._extensions:
---> 35             raise AttributeError(Errors.E046.format(name=name))
     36         default, method, getter, setter = self._extensions[name]
     37         if getter is not None:

AttributeError: [E046] Can't retrieve unregistered extension attribute 'doc_cat'. Did you forget to call the `set_extension` method?
```
Any idea why is that? 

====================== Installed models (spaCy v2.2.1) ======================
ℹ spaCy installation:
anaconda3/envs/back/lib/python3.6/site-packages/spacy

TYPE      NAME             MODEL            VERSION                            
package   en-core-web-sm   en_core_web_sm   2.2.0   ✔
package   en-core-web-lg   en_core_web_lg   2.2.0   ✔

**Comment by ines** [comment]
This is kind of expected – an extension attribute is a custom attribute registered on the *global* `Doc` class. When you serialize the a `Doc`, you can serialize the values of its `user_data` (which includes custom attribute values). But if you want to *retrieve* that value, you first need to register the extension attribute again.

Registering attributes automatically on deserialization would be problematic, because it'd make it very difficult to deal with conflicting attributes from different docs (e.g. if one doc has attr A and another has attr B, would all docs now have A and b?).

**Comment by moh55m55** [comment]
I see. Thanks. It would be great if I had this line in documentation (serialization section) . 
" For custom extensions, It only serialize the values, you will need to register the extension attribute again to restore the value"
