### ISSUE TITLE
Missing PyPi wheel for Windows (amd64) with Python 3.7 (cp37)

### ISSUE THREAD

**Issue by mborsetti** [explosion/spaCy#4380]
https://pypi.org/project/spacy/#files is missing the wheel for Windows amd64 with Python 3.7 
 (i.e. spacy-2.2.1-cp37-cp37m-win_amd64.whl). All previous versions, including 2.2.0, had this wheel.

## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.7.4
* spaCy Version Used: 2.2.0 because of failure of > pip install -U spacy
* Environment Information:

**Comment by ines** [comment]
Thanks for the heads-up – looks like that wheel build didn't complete ([see here](https://github.com/explosion/wheelwright/releases/tag/spacy-v2.2.1)). We're just re-triggering the build!

**Comment by honnibal** [comment]
Should be uploaded now. Thanks again for reporting. 👍
