### ISSUE TITLE
An error while pruning vectors

### ISSUE THREAD

**Issue by ryszardtuora** [explosion/spaCy#4386]
I'm trying to retrain my models because of the 2.2 version update (btw the old ones seem to work alright, but I'm retraining them to be sure), and while trying to initialize a model using CLI i get an error inside the vector pruning function.

The error is as follows
<pre><font color="#4E9A06">✔ Successfully created model</font>
2123132it [01:09, 30354.25it/s]i-forms-all-100-skipg-hs.txt
<font color="#4E9A06">✔ Loaded vectors from nkjp+wiki-forms-all-100-skipg-hs.txt</font>
Traceback (most recent call last):
  File &quot;/usr/lib/python3.6/runpy.py&quot;, line 193, in _run_module_as_main
    &quot;__main__&quot;, mod_spec)
  File &quot;/usr/lib/python3.6/runpy.py&quot;, line 85, in _run_code
    exec(code, run_globals)
  File &quot;/home/rtuora/.local/lib/python3.6/site-packages/spacy/__main__.py&quot;, line 35, in &lt;module&gt;
    plac.call(commands[command], sys.argv[1:])
  File &quot;/home/rtuora/.local/lib/python3.6/site-packages/plac_core.py&quot;, line 328, in call
    cmd, result = parser.consume(arglist)
  File &quot;/home/rtuora/.local/lib/python3.6/site-packages/plac_core.py&quot;, line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File &quot;/home/rtuora/.local/lib/python3.6/site-packages/spacy/cli/init_model.py&quot;, line 90, in init_model
    add_vectors(nlp, vectors_loc, prune_vectors, vectors_name)
  File &quot;/home/rtuora/.local/lib/python3.6/site-packages/spacy/cli/init_model.py&quot;, line 201, in add_vectors
    nlp.vocab.prune_vectors(prune_vectors)
  File &quot;vocab.pyx&quot;, line 324, in spacy.vocab.Vocab.prune_vectors
  File &quot;vectors.pyx&quot;, line 341, in spacy.vectors.Vectors.most_similar
ValueError: could not broadcast input array from shape (1323132,1) into shape (1024,1)
</pre>

## How to reproduce the behaviour
the exact commend I use is 
`python3 -m spacy init-model pl output --vectors-loc nkjp+wiki-forms-all-100-skipg-hs.txt --prune-vectors 800000`

I've tried this with 2 different embeddings, and all seems to work well unless I enable the pruning option. 

## Your Environment
* **spaCy version:** 2.2.1
* **Platform:** Linux-4.15.0-58-generic-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.6.8

BTW: I'm not sure if my reasoning on pruning vectors is correct. The loading times of my models are very long, and I suspect this might be because of it. If my initial embeddings have 3.5 m entries, and I prune them down to the first 800.000, is this a good practice for a general purpose model? Perhaps I should delete these entries altogether, as their effect on regular parsing task must be marginal (or maybe even need not be positive).

**Comment by adrianeboyd** [comment]
The `most_similar()` method was just updated and it looks like it's not taking the `batch_size` into account correctly. We'll look into it.
