### ISSUE TITLE
ner_jsonl2json() got an unexpected keyword argument 'seg_sents'

### ISSUE THREAD

**Issue by vitaly-d** [explosion/spaCy#4389]
## How to reproduce the behaviour

The 'jsonl2json' convertor fails with the "got an unexpected keyword argument" message:

To reproduce:
python -m spacy convert -c jsonl --lang en  sample.jsonl /tmp

Nothing interesting within sample.jsonl, the behaviour does not depend on its content.

[sample.jsonl.zip](https://github.com/explosion/spaCy/files/3696608/sample.jsonl.zip)

After modifying the signature of ner_jsonl2json, my large dataset was converted without any issues:

```
(.env) vitaly@iMac spaCy % git diff
diff --git a/spacy/cli/converters/jsonl2json.py b/spacy/cli/converters/jsonl2json.py
index 91dd4298..c6abc487 100644
--- a/spacy/cli/converters/jsonl2json.py
+++ b/spacy/cli/converters/jsonl2json.py
@@ -7,7 +7,9 @@ from ...gold import docs_to_json
 from ...util import get_lang_class, minibatch
 
 
-def ner_jsonl2json(input_data, lang=None, n_sents=10, use_morphology=False):
+def ner_jsonl2json(
+    input_data, lang=None, n_sents=10, use_morphology=False, seg_sents=None, model=None
+):
     if lang is None:
         raise ValueError("No --lang specified, but tokenization required")
     json_docs = []
```

## Info about spaCy
* **spaCy version:** 2.2.1
* **Platform:** Darwin-19.0.0-x86_64-i386-64bit
* **Python version:** 3.7.3

**Comment by honnibal** [comment]
Thanks, it's hard to keep all of the CLI stuff tested. I think it's best to add a `**kwargs` catch-all, in case arguments are added for other converters that don't apply.
