### ISSUE TITLE
PhraseMatcher does not execute callback function on matches

### ISSUE THREAD

**Issue by zrlaida** [explosion/spaCy#4396]
## How to reproduce the behaviour

In the example from the documentation https://spacy.io/api/phrasematcher
the callback function is not executed.

import spacy
import de_core_news_sm

nlp = spacy.load("en_core_web_sm")

def on_match(matcher, doc, id, matches):
      print('Matched!', matches)

matcher = spacy.matcher.PhraseMatcher(nlp.vocab)
matcher.add("OBAMA", on_match, nlp("Barack Obama"))
matcher.add("HEALTH", on_match, nlp("health care reform"),
                                  nlp("healthcare reform"))
doc = nlp("Barack Obama urges Congress to find courage to defend his healthcare reforms")
matches = matcher(doc)

for match in matches:
    print("Match: ", match, nlp.vocab.strings[match[0]])

Another example.

import spacy
import de_core_news_sm

def on_match(matcher, doc, id, matches):
    print('Callback executes on matches!', matches)

nlp = spacy.load("en_core_web_sm")
matcher = spacy.matcher.PhraseMatcher(nlp.vocab)
matcher.add("OBAMA", on_match, nlp("Barack Obama"))
matcher.add("HEALTH", on_match, nlp("health care reform"), nlp("healthcare reform"))
doc = nlp("Barack Obama urges Congress to find courage to defend his healthcare reform")

print("Start matching. Print in on_match should come after this.")

matches = matcher(doc)

for match in matches:
    print("Match: ", match, nlp.vocab.strings[match[0]])

## Your Environment

* Operating System:
MacOS
* Python Version Used:
python 3.7
* spaCy Version Used:
2.2.1
* Environment Information:

**Comment by zrlaida** [comment]
Sorry for the formatting typos. Cleaner version created in https://github.com/explosion/spaCy/issues/4397.

**Comment by svlandeg** [comment]
Thanks! You should have also been able to edit the original message, but no problem ;-)
