### ISSUE TITLE
EntityRuler to unmatch spans

### ISSUE THREAD

**Issue by dalevskaya** [explosion/spaCy#4398]
Hello,

I'm using Spacy for NER and would like to improve accuracy by adding a  PhraseMatcher after the NER step. According to the EntityRuler doc, I can add spans to the Doc.ents, however I need exactly opposite - to exclude incorrectly predicted spans. For instance Spacy NER always predicts the type of the span AAAA to be X, which is always incorrect. 
Is it possible to use EntityRuler API to unmatch incorrectly recognised entities/spans. 
 
## Your Environment

* Operating System: mac OS
* Python Version Used: 3.7
* spaCy Version Used: 2.1.3
* Environment Information:

**Comment by adrianeboyd** [comment]
The `EntityRuler` doesn't support this, but you can use a list of matches from `EntityRuler` to filter `doc.ents` directly. See an example here of how to delete entities:

https://stackoverflow.com/a/54875300/461847
