### ISSUE TITLE
AttributeError: module 'thinc_gpu_ops' has no attribute 'hash' when running nlp on gpu

### ISSUE THREAD

**Issue by tylerjthomas9** [explosion/spaCy#4404]
code: 

import spacy
spacy.require_gpu() #returns True
nlp = spacy.load('en_core_web_sm')
doc = nlp('test sentence')

error: 
--------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-f87dadac1f38> in <module>
      2 spacy.require_gpu()
      3 nlp = spacy.load('en_core_web_sm')
----> 4 doc = nlp('test sentence')

~/anaconda3/envs/tyler_spacy/lib/python3.7/site-packages/spacy/language.py in __call__(self, text, disable, component_cfg)
    436             if not hasattr(proc, "__call__"):
    437                 raise ValueError(Errors.E003.format(component=type(proc), name=name))
--> 438             doc = proc(doc, **component_cfg.get(name, {}))
    439             if doc is None:
    440                 raise ValueError(Errors.E005.format(name=name))

pipes.pyx in spacy.pipeline.pipes.Tagger.__call__()

pipes.pyx in spacy.pipeline.pipes.Tagger.predict()

~/anaconda3/envs/tyler_spacy/lib/python3.7/site-packages/thinc/neural/_classes/model.py in __call__(self, x)
    167             Must match expected shape
    168         """
--> 169         return self.predict(x)
    170 
    171     def pipe(self, stream, batch_size=128):

~/anaconda3/envs/tyler_spacy/lib/python3.7/site-packages/thinc/neural/_classes/feed_forward.py in predict(self, X)
     38     def predict(self, X):
     39         for layer in self._layers:
---> 40             X = layer(X)
     41         return X
     42 

~/anaconda3/envs/tyler_spacy/lib/python3.7/site-packages/thinc/neural/_classes/model.py in __call__(self, x)
    167             Must match expected shape
    168         """
--> 169         return self.predict(x)
    170 
    171     def pipe(self, stream, batch_size=128):

~/anaconda3/envs/tyler_spacy/lib/python3.7/site-packages/thinc/api.py in predict(seqs_in)
    308     def predict(seqs_in):
    309         lengths = layer.ops.asarray([len(seq) for seq in seqs_in])
--> 310         X = layer(layer.ops.flatten(seqs_in, pad=pad))
    311         return layer.ops.unflatten(X, lengths, pad=pad)
    312 

~/anaconda3/envs/tyler_spacy/lib/python3.7/site-packages/thinc/neural/_classes/model.py in __call__(self, x)
    167             Must match expected shape
    168         """
--> 169         return self.predict(x)
    170 
    171     def pipe(self, stream, batch_size=128):

~/anaconda3/envs/tyler_spacy/lib/python3.7/site-packages/thinc/neural/_classes/feed_forward.py in predict(self, X)
     38     def predict(self, X):
     39         for layer in self._layers:
---> 40             X = layer(X)
     41         return X
     42 

~/anaconda3/envs/tyler_spacy/lib/python3.7/site-packages/thinc/neural/_classes/model.py in __call__(self, x)
    167             Must match expected shape
    168         """
--> 169         return self.predict(x)
    170 
    171     def pipe(self, stream, batch_size=128):

~/anaconda3/envs/tyler_spacy/lib/python3.7/site-packages/thinc/neural/_classes/model.py in predict(self, X)
    131 
    132     def predict(self, X):
--> 133         y, _ = self.begin_update(X, drop=None)
    134         return y
    135 

~/anaconda3/envs/tyler_spacy/lib/python3.7/site-packages/thinc/api.py in uniqued_fwd(X, drop)
    377         )
    378         X_uniq = layer.ops.xp.ascontiguousarray(X[ind])
--> 379         Y_uniq, bp_Y_uniq = layer.begin_update(X_uniq, drop=drop)
    380         Y = Y_uniq[inv].reshape((X.shape[0],) + Y_uniq.shape[1:])
    381 

~/anaconda3/envs/tyler_spacy/lib/python3.7/site-packages/thinc/neural/_classes/feed_forward.py in begin_update(self, X, drop)
     44         callbacks = []
     45         for layer in self._layers:
---> 46             X, inc_layer_grad = layer.begin_update(X, drop=drop)
     47             callbacks.append(inc_layer_grad)
     48 

~/anaconda3/envs/tyler_spacy/lib/python3.7/site-packages/thinc/api.py in begin_update(X, *a, **k)
    161     def begin_update(X, *a, **k):
    162         forward, backward = split_backward(layers)
--> 163         values = [fwd(X, *a, **k) for fwd in forward]
    164 
    165         output = ops.xp.hstack(values)

~/anaconda3/envs/tyler_spacy/lib/python3.7/site-packages/thinc/api.py in <listcomp>(.0)
    161     def begin_update(X, *a, **k):
    162         forward, backward = split_backward(layers)
--> 163         values = [fwd(X, *a, **k) for fwd in forward]
    164 
    165         output = ops.xp.hstack(values)

~/anaconda3/envs/tyler_spacy/lib/python3.7/site-packages/thinc/api.py in wrap(*args, **kwargs)
    254 
    255     def wrap(*args, **kwargs):
--> 256         output = func(*args, **kwargs)
    257         if splitter is None:
    258             to_keep, to_sink = output

~/anaconda3/envs/tyler_spacy/lib/python3.7/site-packages/thinc/api.py in begin_update(X, *a, **k)
    161     def begin_update(X, *a, **k):
    162         forward, backward = split_backward(layers)
--> 163         values = [fwd(X, *a, **k) for fwd in forward]
    164 
    165         output = ops.xp.hstack(values)

~/anaconda3/envs/tyler_spacy/lib/python3.7/site-packages/thinc/api.py in <listcomp>(.0)
    161     def begin_update(X, *a, **k):
    162         forward, backward = split_backward(layers)
--> 163         values = [fwd(X, *a, **k) for fwd in forward]
    164 
    165         output = ops.xp.hstack(values)

~/anaconda3/envs/tyler_spacy/lib/python3.7/site-packages/thinc/api.py in wrap(*args, **kwargs)
    254 
    255     def wrap(*args, **kwargs):
--> 256         output = func(*args, **kwargs)
    257         if splitter is None:
    258             to_keep, to_sink = output

~/anaconda3/envs/tyler_spacy/lib/python3.7/site-packages/thinc/api.py in begin_update(X, *a, **k)
    161     def begin_update(X, *a, **k):
    162         forward, backward = split_backward(layers)
--> 163         values = [fwd(X, *a, **k) for fwd in forward]
    164 
    165         output = ops.xp.hstack(values)

~/anaconda3/envs/tyler_spacy/lib/python3.7/site-packages/thinc/api.py in <listcomp>(.0)
    161     def begin_update(X, *a, **k):
    162         forward, backward = split_backward(layers)
--> 163         values = [fwd(X, *a, **k) for fwd in forward]
    164 
    165         output = ops.xp.hstack(values)

~/anaconda3/envs/tyler_spacy/lib/python3.7/site-packages/thinc/api.py in wrap(*args, **kwargs)
    254 
    255     def wrap(*args, **kwargs):
--> 256         output = func(*args, **kwargs)
    257         if splitter is None:
    258             to_keep, to_sink = output

~/anaconda3/envs/tyler_spacy/lib/python3.7/site-packages/thinc/neural/_classes/hash_embed.py in begin_update(self, ids, drop)
     57         if ids.ndim >= 2:
     58             ids = self.ops.xp.ascontiguousarray(ids[:, self.column], dtype="uint64")
---> 59         keys = self.ops.hash(ids, self.seed) % self.nV
     60         vectors = self.vectors[keys].sum(axis=1)
     61         mask = self.ops.get_dropout_mask((vectors.shape[1],), drop)

ops.pyx in thinc.neural.ops.CupyOps.hash()

AttributeError: module 'thinc_gpu_ops' has no attribute 'hash'

**Comment by svlandeg** [comment]
Thanks for the report - that certainly doesn't look right!

Could you paste the output of both `python -m spacy info --markdown` and `python -m spacy validate` ?

**Comment by tylerjthomas9** [comment]
output of python -m spacy info --markdown:
## Info about spaCy

* **spaCy version:** 2.2.1
* **Platform:** Linux-5.0.0-29-generic-x86_64-with-debian-buster-sid
* **Python version:** 3.7.4

output of python -m spacy validate (I re-downloaded the medium and large models since posting the package list):
![Capture](https://user-images.githubusercontent.com/36181311/66429768-59cb0680-e9de-11e9-8b5b-03e9dc612be6.PNG)

**Comment by adrianeboyd** [comment]
Hmm, the package versions for everything related to spacy looks fine. There are some weird packages at the top of the list (`-pacy` and `-umpy`).

Do you get the same error if you try a new virtual environment with only spacy installed?

**Comment by tylerjthomas9** [comment]
I get the same error with a fresh environment, that I pip installed jupyter, and spacy.

**Comment by tylerjthomas9** [comment]
Closing the issue. I started with a fresh linux install, and spacy was fixed when I got it installed again.
