### ISSUE TITLE
Misspelling on Lemmatizer Example

### ISSUE THREAD

**Issue by ghollah** [explosion/spaCy#4406]
## Which page or section is this issue related to?

from spacy.lemmatizer import Lemmatizer
from spacy.lookups import Lookups
_**lookups = Loookups()**_
lookups.add_table("lemma_rules", {"noun": [["s", ""]]})
lemmatizer = Lemmatizer(lookups)
lemmas = lemmatizer("ducks", "NOUN")
assert lemmas == ["duck"] 
![Screenshot from 2019-10-09 07-35-15](https://user-images.githubusercontent.com/13104952/66451976-6ba4bc00-ea67-11e9-9909-e625073bfab7.png)

Suggestion:
 Remove extra **_o_** in the _**lookups = Loookups()**_

**Comment by svlandeg** [comment]
Thanks! 

Do you want to go ahead and submit a Pull Request to fix this? The relevant file is https://github.com/explosion/spaCy/blob/master/website/docs/api/lemmatizer.md, and generic guidelines for contributing to spaCy can be found [here](https://github.com/explosion/spaCy/blob/master/CONTRIBUTING.md).

**Comment by ghollah** [comment]
I will do that.
