### ISSUE TITLE
Which one of TextCategorizer architectures use our pre-trained word vectors?

### ISSUE THREAD

**Issue by zfallahnejad** [explosion/spaCy#4407]
I want to train a `TextCategorizer` model. The documentation says that there are three different architectures for `TextCategorizer` model. Which one of these `TextCategorizer` architectures use our pre-trained word vectors? 
(I have trained my own word2vec model in `gensim` and I load it in spacy.)

**Comment by svlandeg** [comment]
Both `simple_cnn` and `ensemble` should be using the pre-trained word vectors. You'll have to make sure to set the argument `pretrained_vectors` though. I think there may be an issue with the `ensemble` architecture right now (cf. Issue #4009), so I would start experimenting with `simple_cnn` if I were you.
