### ISSUE TITLE
Sentence splitter not working for Greek

### ISSUE THREAD

**Issue by pdimiel** [explosion/spaCy#4408]
Hello everyone.
I have been using Spacy for a long time without any problems processing English texts.

The last coupe of weeks I have tried the Greek model and I noticed that it does not split the sentences but instead considers the full text to be one sentence.
If I use the English models on the same text, it is split to sentences.

It does not seem to be a setup problem as the same behaviour is noticed on the Displacy website

## How to reproduce the behaviour
Displacy Greek Model:
https://explosion.ai/demos/displacy?text=%CE%91%CF%85%CF%84%CE%AE%20%CE%B5%CE%AF%CE%BD%CE%B1%CE%B9%20%CE%BC%CE%B9%CE%B1%20%CF%80%CF%81%CF%8C%CF%84%CE%B1%CF%83%CE%B7.%20%CE%91%CF%85%CF%84%CE%AE%20%CE%B5%CE%AF%CE%BD%CE%B1%CE%B9%20%CE%BC%CE%B9%CE%B1%20%CE%AC%CE%BB%CE%BB%CE%B7%20%CF%80%CF%81%CF%8C%CF%84%CE%B1%CF%83%CE%B7.&model=el_core_news_sm&cpu=0&cph=0

Displacy English Model:
https://explosion.ai/demos/displacy?text=%CE%91%CF%85%CF%84%CE%AE%20%CE%B5%CE%AF%CE%BD%CE%B1%CE%B9%20%CE%BC%CE%B9%CE%B1%20%CF%80%CF%81%CF%8C%CF%84%CE%B1%CF%83%CE%B7.%20%CE%91%CF%85%CF%84%CE%AE%20%CE%B5%CE%AF%CE%BD%CE%B1%CE%B9%20%CE%BC%CE%B9%CE%B1%20%CE%AC%CE%BB%CE%BB%CE%B7%20%CF%80%CF%81%CF%8C%CF%84%CE%B1%CF%83%CE%B7.&model=en_core_web_sm&cpu=0&cph=0

Keep up the great work.

**Comment by adrianeboyd** [comment]
Thanks for the report! This is the same kind of problem as in #4401: the model was trained on a corpus where each document only has one sentence so the parser model seems determined to try to parse any given text as one sentence.

I will work on improving the training data so we can train and release an updated model, hopefully by next week at the latest.

In the meanwhile, you can try the sentencizer, which splits on punctuation symbols:

https://spacy.io/api/sentencizer

**Comment by pdimiel** [comment]
Thanks for the quick response.
Sentencizer will do for the time being as we can add some sentence delimiters like ";".
Looking forward to the updated model.

**Comment by ines** [comment]
Just released new versions of the Greek models that should resolve the problem 😃
