### ISSUE TITLE
When will the Chinese model be supported?

### ISSUE THREAD

**Issue by suozq1** [explosion/spaCy#4410]
When will the Chinese model be supported?

**Comment by adrianeboyd** [comment]
Hi, we hope to be able to train a model for Chinese using data from OntoNotes soon. Would you be interested in helping us test a beta version of the model?

**Comment by suozq1** [comment]
It's my pleasure.If I'm not busy with my work,I will help test the model

**Comment by suozq1** [comment]
In addition,we are using spacy in work,the current model for Chinese we used is open source on github，but It's crude. So we would like to use the beta version in work to test it.
If you have the beta version,you can send it to me. Thank you!

**Comment by yzj19870824** [comment]
> Hi, we hope to be able to train a model for Chinese using data from OntoNotes soon. Would you be interested in helping us test a beta version of the model?

Is the Spacy Version 2.1?

**Comment by yzj19870824** [comment]
@adrianeboyd  Is the beta version suitable for SpaCy 2.1?

**Comment by yzj19870824** [comment]
@adrianeboyd  If it's so, I'd like to be helpful to test your software

**Comment by GoooIce** [comment]
有人感兴趣么？

https://github.com/cn-spacy-lm/how-to-make-chinese-models-for-spacy

**Comment by howl-anderson** [comment]
Hi, @suozq1 @adrianeboyd @yzj19870824 @GoooIce, 

https://github.com/howl-anderson/Chinese_models_for_SpaCy has a model to support Chinese for SpaCy 2.1.x, I will update it to supporting SpaCy 2.2.x recently. Also, I will update the instructions and tools.

**Comment by howl-anderson** [comment]
@suozq1 @adrianeboyd @yzj19870824 @GoooIce [non-official] Chinese model for SpaCy 2.2.x already released in `https://github.com/howl-anderson/Chinese_models_for_SpaCy`.  please feel free to try it.

**Comment by svlandeg** [comment]
Thanks for the link, @howl-anderson !

Merging this thread with #4410 to keep the discussion in one place.
