### ISSUE TITLE
Spaces from Doc

### ISSUE THREAD

**Issue by AnnaAnia** [explosion/spaCy#4413]
Is it possible to retrieve a list of spaces from Doc in the same way they are used to construct Doc

doc = Doc(nlp.vocab, words=words, spaces=spaces)

Thank you

**Comment by svlandeg** [comment]
You can do this via the `token.whitespace_` attribute:
```
    nlp = English()
    doc = nlp("These are tokens, some with spaces, some without")
    print([token.text for token in doc])
    print([token.whitespace_ for token in doc])
```
prints

> 
> ['These', 'are', 'tokens', ',', 'some', 'with', 'spaces', ',', 'some', 'without']
> [' ', ' ', '', ' ', ' ', ' ', '', ' ', ' ', '']

**Comment by AnnaAnia** [comment]
Thank you

**Comment by svlandeg** [comment]
Welcome! :-)
