### ISSUE TITLE
Training entity linking classifier

### ISSUE THREAD

**Issue by petulla** [explosion/spaCy#4418]
I'm trying to follow the entity linking documentation but I don't really follow.

It seems like the documentation on [an entity linker](https://spacy.io/usage/training#entity-linker) shows how to do custom linking. But what if you just want to use the out of the box Wikipedia linking? How do I set that up? Seems like it's a matter of running the scripts but I'm not sure which ones or in which order.

## Which page or section is this issue related to?
https://spacy.io/usage/linguistic-features#entity-linking

**Comment by svlandeg** [comment]
PR #4375 contains a readme file that addresses exactly which scripts to run and how!

**Comment by petulla** [comment]
Wonderful. Any idea when it'll be merged?

**Comment by svlandeg** [comment]
I would expect within the next week ;-)

**Comment by svlandeg** [comment]
You can find an overview of the pipeline here: https://github.com/explosion/spaCy/tree/master/bin/wiki_entity_linking
