### ISSUE TITLE
doc vs token similarity

### ISSUE THREAD

**Issue by aie0** [explosion/spaCy#442]
There is a different when comparing single word document with another token and comparing document's token?
```
last_token = spacy("assign last to Victor")[1]
token1 = spacy('recent')
token2 = spacy('recent')[0]

assert last_token.similarity(token1) == last_token.similarity(token2) # 0.71 != 0.5
# or rather
assert token1.vector_norm == token2.vector_norm
```

What is the correct way of comparing the tokens?

**Comment by syllog1sm** [comment]
That definitely looks like a bug. Thanks.

**Comment by adam-ra** [comment]
Also,

    doc_apple = en_nlp('apple')
    tok_apple = doc_apple[0]
    print(doc_apple.similarity(doc_apple)) # almost 1.0
    print(tok_apple.similarity(tok_apple)) # almost 0.5 (!)

**Comment by honnibal** [comment]
Finally fixed this.

Thanks for continuing to report, even when there wasn't much response — this issue was very helpful.
