### ISSUE TITLE
Matcher doesn't match when lemmas are set by lemma_lookup in spaCy 2.2.1

### ISSUE THREAD

**Issue by zrlaida** [explosion/spaCy#4426]
## How to reproduce the behaviour

In `spacy==2.2.1`, the following code snippet doesn't match. Whereas, in `spacy==2.1.8`, it matches correctly.

```
import spacy

nlp = spacy.load("de_core_news_sm")

nlp.Defaults.lemma_lookup["therapie"] = "Therapie"
nlp.Defaults.lemma_lookup["versuch"] = "Versuch"

doc = nlp("ein therapie versuch")

matcher = spacy.matcher.Matcher(nlp.vocab)

pattern = [{'LEMMA': 'Therapie'}, {'LEMMA': 'Versuch'}]

matcher.add("test_id", None, pattern)

for match in matcher(doc):
    print("Match: ", match, nlp.vocab.strings[match[0]])
```

## Your Environment

* Operating System: macOS 10.14.6
* Python Version Used: 3.7.0
* spaCy Version Used: 2.2.1
* Environment Information:

**Comment by ines** [comment]
The lemma lookups work slightly differently in v2.2 (see [release notes](https://spacy.io/usage/v2-2#incompat)), so writing to `Defaults.lemma_lookup` won't make a difference (we should probably remove the properties and raise an error here).

Lemmatization tables are now powered by the new [`Lookups` API](https://spacy.io/api/lookups). Also see the `Lemmatizer` docs for details: https://spacy.io/api/lemmatizer

If I change your code like this, it works as expected:

```python
lemma_lookup = nlp.vocab.lookups.get_table("lemma_lookup")
lemma_lookup["therapie"] = "Therapie"
lemma_lookup["versuch"] = "Versuch"
```
