### ISSUE TITLE
Wrong Wikidata dump format references in `wikidata_pretrain_kb.py`

### ISSUE THREAD

**Issue by alepiscopo** [explosion/spaCy#4438]
## How to reproduce the behaviour
Run `bin/wiki_entity_linking/wikidata_pretrain_kb.py`: steps 1-3 runs with no issues;
Step 4 raises an error while reading the Wikidata dumps file:

```OSError: Not a gzipped file (b'BZ')```

This is because the docstring at the beginning of the script suggests to download the dumps in bz2 format:

```For the Wikidata dump: get the latest-all.json.bz2 from https://dumps.wikimedia.org/wikidatawiki/entities/```

However, the script expects them to be in gz and uses the gzip library to open them.

## Your Environment
* **spaCy version:** 2.2.1
* **Platform:** Linux-4.15.0-1037-gcp-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.6.8

**Comment by svlandeg** [comment]
Thanks for the report! This is already fixed in the open pull request #4375, which will be merged soon.
