### ISSUE TITLE
Memory and text files ?

### ISSUE THREAD

**Issue by vsraptor** [explosion/spaCy#444]
hi,
I only need a capability to tokenize the text correctly to word-lemmas and sentences.
Taking this to account I have two questions ... 

1. Is there a way to decrease the memory usage ? Having said that I only need word-lemmas and sentences.
2. What is the correct way to parse text file ? Currently I load the whole file into memory, I don't want to do that. I would prefer to pass let say generator instead.

Here is my current code :

```
import spacy
nlp = spacy.load('en', tagger=False, entity=False, matcher=False)
txt = open('../data/very_small.txt').read()
doc = nlp( unicode(txt) )

for s in doc.sents :	print s
```

**Comment by honnibal** [comment]
Unfortunately spaCy doesn't have such a neat configuration for your purposes at the moment. The sentence detection requires the parser, which is what uses all the memory.

If you want to write your own sentence boundary detection heuristic, suitable for your text, the required code would look something like this:

```
import spacy
nlp = spacy.load('en', tagger=False, entity=False, matcher=False, parser=False)
txt = open('../data/very_small.txt').read()
doc = nlp( unicode(txt) )
for s in get_sents(doc):
    print s
```

**Comment by vsraptor** [comment]
I see, neat, thanks ... but this also means I can not use word.lemma_ , right ? :(

Quick question, is there shortcut way to loop over only the words, not all the tokens.
I mean if a word repeat multiple times I want to go trough it just once !!

**Comment by syllog1sm** [comment]
The pipeline is like:

* Tokenize
* POS tag (sets lemmas)
* Parser (sets sentence boundaries)
* NER

So you can use the lemmas without the parser.

To iterate through the word types, I would probably just do something like `set(w.lemma_ for w in doc)`
