### ISSUE TITLE
Extracting Verb Phrases (VP) using spaCy

### ISSUE THREAD

**Issue by phosseini** [explosion/spaCy#4441]
## Feature description
It would be nice if there be a verb chunking method for extracting Verb Phrases (VP) using spaCy. There's already a Noun Phrase (NP) chunker but I wonder why there's no VP chunker?

Also, one thing to think about when developing the VP chunker is resolving the overlapping VPs issue. For example, we can extract VPs using CoreNLP's tregex, but the problem is that we sometimes have VPs with overlaps. So it would be nice if the output of the VP chunker in spaCy have this issue already resolved.

**Comment by naveenjafer** [comment]
Does someone have reliable collateral or reading material on VP chunking? I am able to find a lot of content for NP chunking.

**Comment by svlandeg** [comment]
I think it would be a great idea to add VP chunking to the [syntax iterators](https://spacy.io/usage/adding-languages#syntax-iterators). I've added it to the master thread #4338 - merging this issue with that thread. Contributions welcome!

**Comment by randomgambit** [comment]
Hi there, please see my idea for VP extraction here https://github.com/explosion/spaCy/issues/4338
