### ISSUE TITLE
EntityRuler does not support LENGTH type patterns in 2.2.1; worked in 2.1.8

### ISSUE THREAD

**Issue by ewaldatsensentia** [explosion/spaCy#4442]
## How to reproduce the behaviour
import spacy
from spacy.pipeline import EntityRuler
nlp =  spacy.load('en_core_web_md')
ruler = EntityRuler(nlp, validate=True, overwrite_ents=True)
patterns = [{"label":"MYCODE", "pattern":[{"LENGTH":5,"SHAPE":"dddd"}]}]
ruler.add_patterns(patterns)

## Result
ValueError                                Traceback (most recent call last)
<ipython-input-31-b26e98cd177a> in <module>
      4 ruler = EntityRuler(nlp, validate=True, overwrite_ents=True)
      5 patterns = [{"label":"MYCODE", "pattern":[{"LENGTH":5,"SHAPE":"dddd"}]}]
----> 6 ruler.add_patterns(patterns)

~\Anaconda3\lib\site-packages\spacy\pipeline\entityruler.py in add_patterns(self, patterns)
    200                     raise ValueError(Errors.E097.format(pattern=pattern))
    201             for label, patterns in self.token_patterns.items():
--> 202                 self.matcher.add(label, None, *patterns)
    203             for label, patterns in self.phrase_patterns.items():
    204                 self.phrase_matcher.add(label, None, *patterns)

matcher.pyx in spacy.matcher.matcher.Matcher.add()

matcher.pyx in spacy.matcher.matcher._preprocess_pattern()

matcher.pyx in spacy.matcher.matcher._get_attr_values()

ValueError: [E153] The value type int is not supported for token patterns. Please use the option validate=True with Matcher, PhraseMatcher, or EntityRuler for more details.

## Your Environment
* **spaCy version:** 2.2.1
* **Platform:** Windows-10-10.0.18362-SP0
* **Python version:** 3.7.3

**Comment by adrianeboyd** [comment]
Thanks for the report! The validation added in 2.2 was a bit overzealous here and hopefully should be fixed in the next minor release. I think the following workaround should work in the meanwhile:

```
[{"LENGTH": {"==": 5}}]
```

**Comment by ewaldatsensentia** [comment]
Thank you for the workaround.
