### ISSUE TITLE
Training a blank NER with custom beam settings

### ISSUE THREAD

**Issue by davidbren** [explosion/spaCy#4450]
I am training a NER model from scratch. I have added the beam search functionality to the query logic. This means that I can get a probability for Test data I send to the model.  This is in line with  the code in previous posts https://github.com/explosion/spaCy/issues/881 

However it has also been suggested that to get more stable results you should train your model with the beam settings also being set to customized values of your choosing.
Have you any example of code to do this ? 

I had been looking at doing it using 

os.environ['SPACY_BEAM_WIDTH'] = '16'
os.environ['SPACY_BEAM_DENSITY'] = '0.0001'

However when I look at the ner\cfg file it still has the default values 
{
  "beam_width":1,
  "beam_density":0.0,
  "beam_update_prob":1.0,
....
}

This seems to indicate it hasn't picked up my settings ?

## Your Environment
* Operating System: Unix
* Python Version Used: 2.6.5
* spaCy Version Used: 2.1.8

**Comment by adrianeboyd** [comment]
Command-line options to `spacy train` haven't been implemented for these settings, but you can see how the `pipe_cfg` is set up here for existing vs. blank models:

https://github.com/explosion/spaCy/blob/a98d1cd58e64b55b43db40ad674041b84c127295/spacy/cli/train.py#L150-L211

You can add the corresponding `pipe == "ner"` blocks to set these settings.
