### ISSUE TITLE
Matcher remove not working on master

### ISSUE THREAD

**Issue by danielkingai2** [explosion/spaCy#4453]
## How to reproduce the behaviour
Having cloned master and building from source, it seems that the matcher remove functionality is not working properly. It does remove the pattern from `_patterns` but it is still matching on the pattern. I confirmed that this bug does not exist in the released version (2.2.1). I would also suggest that the test found here: https://github.com/explosion/spaCy/blob/2d249a9502bfc5d3d2111165672d964b1eebe35e/spacy/tests/matcher/test_matcher_logic.py#L148 be modified to make sure that no matches are found once the pattern has been removed.

Repro steps (on master)
```
>>> import spacy
>>> nlp = spacy.load('en_core_web_sm')
>>> from spacy.matcher import Matcher
>>> text = "This is some text."
>>> doc = nlp(text)
>>> matcher = Matcher(nlp.vocab)
>>> matcher(doc)
[]
>>> matcher.add("pattern", None, [{"ORTH": "some"}])
>>> matcher(doc)
[(15329811787164753587, 2, 3)]
>>> matcher.remove("pattern")
>>> matcher(doc)
[(15329811787164753587, 2, 3)]
>>> matcher._patterns
{}
```

## Info about spaCy

* **spaCy version:** 2.2.1 (I have actually compiled from source on master branch)
* **Platform:** Linux-4.4.0-112-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.7

**Comment by svlandeg** [comment]
Thanks for the report! I'll have a look.
