### ISSUE TITLE
Custom Named Entity Recognizer

### ISSUE THREAD

**Issue by rambabusure** [explosion/spaCy#4457]
* **spaCy version:** 2.2.1
* **Platform:** Linux-4.14.146-93.123.amzn1.x86_64-x86_64-with-glibc2.9
* **Python version:** 3.6.5
* **Models:** en

We are trying to build ner model for custom entity recognition . We tried with 10 samples as shown from https://spacy.io/usage/training
It is not recognizing any custom entity

1) do we need to provide the correct grammar data for training ?
2) what is the minimum training data for custom named entity model ?
3) Do we need to load 'en' or 'en_core_web_sm'?
4) ner losses are low if we train 10 samples. If we give same sentence from training data , it is not recognizing?

**Comment by adrianeboyd** [comment]
You probably want at least several hundred examples to get started. You want your training data to look as much like your intended test/eval data as possible. If the data is noisy (OCR errors, lots of misspellings, etc.), you will probably need more training examples than if it's more consistent.

Whether you start with a pretrained model or a blank model depends on what you want to do and whether the new NER types possibly conflict with the existing ones. Be aware of the [catastrophic forgetting problem](https://explosion.ai/blog/pseudo-rehearsal-catastrophic-forgetting) if you are trying to update a pretrained model.
