### ISSUE TITLE
Train NamedEntityRecognizer via cli throws OverflowError

### ISSUE THREAD

**Issue by adridjs** [explosion/spaCy#4461]
## Your Environment

* Operating System: Ubuntu 16.04
* Python Version Used: Python 3.6
* spaCy Version Used: 2.2

I'm trying to add Hindi Language from scratch in Spacy. I already formatted the train/dev data into the correct json format as shown in [https://spacy.io/api/annotation#named-entities](url)

When using this command: `python -m spacy train hi /data/disk2/adrinerhindi/models /data/disk2/adrinerhindi/cli_formatted/wiki_train.json /data/disk2/adrinerhindi/cli_formatted/wiki_dev.json -ne 5 -G -p ner`

 it throws the following error:
```
Training pipeline: ['ner']
Starting with blank model 'hi'
Counting training words (limit=0)
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/adria/envs/hindi-nlp/lib/python3.6/site-packages/spacy/__main__.py", line 35, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/home/adria/envs/hindi-nlp/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/adria/envs/hindi-nlp/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/adria/envs/hindi-nlp/lib/python3.6/site-packages/spacy/cli/train.py", line 205, in train
    corpus = GoldCorpus(train_path, dev_path, limit=n_examples)
  File "gold.pyx", line 130, in spacy.gold.GoldCorpus.__init__
  File "gold.pyx", line 141, in spacy.gold.GoldCorpus.write_msgpack
  File "gold.pyx", line 181, in read_tuples
  File "gold.pyx", line 339, in read_json_file
  File "gold.pyx", line 386, in _json_iterate
OverflowError: value too large to convert to int
```

What am I doing wrong?

**Comment by adrianeboyd** [comment]
I suspect something is wrong with the JSON format. I would normally suggest running `spacy debug-data`, but I suspect you'll run into the same error loading the corpus before it gets to the analysis.

Can you try to load subsets of your corpus to narrow it down to possibly one document or paragraph that leads to this error? Instead of `spacy train`, you can use `spacy debug-data` to load and validate the corpus.

**Comment by adridjs** [comment]
Ok, sorry for not commenting it earlier but I also tested with debug-data. It seems that the format is correct, as it states it, but it has trouble in finding memory (it shouldn't, executing on a machine with 50+ GB RAM). I also tried python json library to load the files and all are correctly parsed and loaded into memory. I copy-paste the error just in case, thank you.

`=========================== Data format validation ===========================
✔ Corpus is loadable

=============================== Training stats ===============================
Training pipeline: tagger, parser, ner
Starting with blank model 'hi'
102885 training docs
12860 evaluation docs
⚠ 214 training examples also in evaluation data

============================== Vocab & Vectors ==============================
ℹ 10362343 total words in the data (453908 unique)
⚠ 1092 misaligned tokens in the training data
⚠ 130 misaligned tokens in the dev data
ℹ No word vectors present in the model

========================== Named Entity Recognition ==========================
ℹ 3 new labels, 0 existing labels
0 missing values (tokens with '-' label)
✔ Good amount of examples for all labels
✔ Examples without occurrences available for all labels
✔ No entities consisting of or starting/ending with whitespace

=========================== Part-of-speech Tagging ===========================
ℹ 1 label in data (19 labels in tag map)
✘ Label '' not found in tag map for language 'hi'

============================= Dependency Parsing =============================
ℹ Found 10038080 sentences with an average length of 1.0 words.
ℹ 2 labels in train data
ℹ 2 labels in projectivized train data

================================== Summary ==================================
✔ 4 checks passed
⚠ 3 warnings
✘ 1 error
`

I only want to train the NER, so I think I can obviate the error from dependency parser.

**Comment by adrianeboyd** [comment]
Thanks, that's very helpful! I noticed that you're using `-G` and this may the source of the problems, since there are some bugs with `-G` in 2.2 (see #4392 and #4402).

Can you try the train command without `-G`? Or try training with spacy 2.1.8 instead if you need `-G`? (We'd be able to help a bit if there are straightforward issues with the current tokenization for Hindi that can be fixed, too.)

Can you post an example document? The main question I have is whether you have some form of sentence segmentation in your training data. It's possible that `-G` without dependency annotation is leading to some unusual documents. I would have expected the error here to look more like #4402 rather than your `OverflowError`, so I'm not sure what's going on. If I can replicate it on my end with an example document that would make it easier to figure out the details.

**Comment by adridjs** [comment]
Regarding the sentence segmentation, no I don't apply any type of it. The original `OverflowError` dissapeared, I'm a little bit lost on the cause though.

This is a sample document, I got a list of these.
`{"id": 48408, "paragraphs": [{"raw": "\u091a\u0902\u0926\u093e\u092f\u0928  \u092e\u0941\u0932\u094d\u0932\u093e \u0926\u093e\u090a\u0926  \u0915\u0943\u0924  \u0939\u093f\u0902\u0926\u0940  \u0915\u093e \u091c\u094d\u091e\u093e\u0924 \u092a\u094d\u0930\u0925\u092e \u0938\u0942\u092b\u0940   \u092a\u094d\u0930\u0947\u092e\u0915\u093e\u0935\u094d\u092f  \u0964 \u0907\u0938\u092e\u0947\u0902 \u0928\u093e\u092f\u0915 \u0932\u094b\u0930 , \u0932\u093e\u0930\u093e , \u0932\u094b\u0930\u0915 , \u0932\u094b\u0930\u093f\u0915 \u0905\u0925\u0935\u093e \u0928\u0942\u0930\u0915 \u0914\u0930 \u0928\u093e\u092f\u093f\u0915\u093e \u091a\u093e\u0901\u0926\u093e \u092f\u093e \u091a\u0902\u0926\u093e \u0915\u0940 \u092a\u094d\u0930\u0947\u092e\u0915\u0925\u093e \u0935\u0930\u094d\u0923\u093f\u0924 \u0939\u0948\u0964 \u0930\u091a\u0928\u093e\u0915\u093e\u0932 \u0935\u093f\u0935\u093e\u0926\u0917\u094d\u0930\u0938\u094d\u0924 \u0939\u0948\u0964 \u092a\u094d\u0930\u0938\u093f\u0926\u094d\u0927 \u0907\u0924\u093f\u0939\u093e\u0938\u0915\u093e\u0930 \u0905\u0932\u094d \u092c\u0926\u093e\u092f\u0942\u0928\u0940 \u0915\u0947 \u0906\u0927\u093e\u0930 \u092a\u0930 , \u091c\u093f\u0938\u0928\u0947 \u0938\u0928\u094d 772 \u0939\u093f\u091c\u0930\u0940 \u0915\u0947 \u0906\u0938\u092a\u093e\u0938 \u0907\u0938\u0915\u0940 \u092a\u094d\u0930\u0938\u093f\u0926\u094d\u0927\u093f \u0915\u093e \u0909\u0932\u094d\u0932\u0947\u0916 \u0915\u093f\u092f\u093e \u0939\u0948 , \u0908 .", "sentences": [{"tokens": [{"head": 0, "dep": "", "tag": "", "orth": "\u091a\u0902\u0926\u093e\u092f\u0928", "ner": "O", "id": 0}, {"head": 0, "dep": "", "tag": "", "orth": "\u092e\u0941\u0932\u094d\u0932\u093e", "ner": "O", "id": 1}, {"head": 0, "dep": "", "tag": "", "orth": "\u0926\u093e\u090a\u0926", "ner": "O", "id": 2}, {"head": 0, "dep": "", "tag": "", "orth": "\u0915\u0943\u0924", "ner": "O", "id": 3}, {"head": 0, "dep": "", "tag": "", "orth": "\u0939\u093f\u0902\u0926\u0940", "ner": "O", "id": 4}, {"head": 0, "dep": "", "tag": "", "orth": "\u0915\u093e", "ner": "O", "id": 5}, {"head": 0, "dep": "", "tag": "", "orth": "\u091c\u094d\u091e\u093e\u0924", "ner": "O", "id": 6}, {"head": 0, "dep": "", "tag": "", "orth": "\u092a\u094d\u0930\u0925\u092e", "ner": "O", "id": 7}, {"head": 0, "dep": "", "tag": "", "orth": "\u0938\u0942\u092b\u0940", "ner": "O", "id": 8}, {"head": 0, "dep": "", "tag": "", "orth": "\u092a\u094d\u0930\u0947\u092e\u0915\u093e\u0935\u094d\u092f", "ner": "O", "id": 9}, {"head": 0, "dep": "", "tag": "", "orth": "\u0964", "ner": "O", "id": 10}, {"head": 0, "dep": "", "tag": "", "orth": "\u0907\u0938\u092e\u0947\u0902", "ner": "O", "id": 11}, {"head": 0, "dep": "", "tag": "", "orth": "\u0928\u093e\u092f\u0915", "ner": "O", "id": 12}, {"head": 0, "dep": "", "tag": "", "orth": "\u0932\u094b\u0930", "ner": "O", "id": 13}, {"head": 0, "dep": "", "tag": "", "orth": ",", "ner": "O", "id": 14}, {"head": 0, "dep": "", "tag": "", "orth": "\u0932\u093e\u0930\u093e", "ner": "O", "id": 15}, {"head": 0, "dep": "", "tag": "", "orth": ",", "ner": "O", "id": 16}, {"head": 0, "dep": "", "tag": "", "orth": "\u0932\u094b\u0930\u0915", "ner": "O", "id": 17}, {"head": 0, "dep": "", "tag": "", "orth": ",", "ner": "O", "id": 18}, {"head": 0, "dep": "", "tag": "", "orth": "\u0932\u094b\u0930\u093f\u0915", "ner": "O", "id": 19}, {"head": 0, "dep": "", "tag": "", "orth": "\u0905\u0925\u0935\u093e", "ner": "O", "id": 20}, {"head": 0, "dep": "", "tag": "", "orth": "\u0928\u0942\u0930\u0915", "ner": "O", "id": 21}, {"head": 0, "dep": "", "tag": "", "orth": "\u0914\u0930", "ner": "O", "id": 22}, {"head": 0, "dep": "", "tag": "", "orth": "\u0928\u093e\u092f\u093f\u0915\u093e", "ner": "O", "id": 23}, {"head": 0, "dep": "", "tag": "", "orth": "\u091a\u093e\u0901\u0926\u093e", "ner": "O", "id": 24}, {"head": 0, "dep": "", "tag": "", "orth": "\u092f\u093e", "ner": "O", "id": 25}, {"head": 0, "dep": "", "tag": "", "orth": "\u091a\u0902\u0926\u093e", "ner": "O", "id": 26}, {"head": 0, "dep": "", "tag": "", "orth": "\u0915\u0940", "ner": "O", "id": 27}, {"head": 0, "dep": "", "tag": "", "orth": "\u092a\u094d\u0930\u0947\u092e\u0915\u0925\u093e", "ner": "O", "id": 28}, {"head": 0, "dep": "", "tag": "", "orth": "\u0935\u0930\u094d\u0923\u093f\u0924", "ner": "O", "id": 29}, {"head": 0, "dep": "", "tag": "", "orth": "\u0939\u0948\u0964", "ner": "O", "id": 30}, {"head": 0, "dep": "", "tag": "", "orth": "\u0930\u091a\u0928\u093e\u0915\u093e\u0932", "ner": "O", "id": 31}, {"head": 0, "dep": "", "tag": "", "orth": "\u0935\u093f\u0935\u093e\u0926\u0917\u094d\u0930\u0938\u094d\u0924", "ner": "O", "id": 32}, {"head": 0, "dep": "", "tag": "", "orth": "\u0939\u0948\u0964", "ner": "O", "id": 33}, {"head": 0, "dep": "", "tag": "", "orth": "\u092a\u094d\u0930\u0938\u093f\u0926\u094d\u0927", "ner": "O", "id": 34}, {"head": 0, "dep": "", "tag": "", "orth": "\u0907\u0924\u093f\u0939\u093e\u0938\u0915\u093e\u0930", "ner": "O", "id": 35}, {"head": 0, "dep": "", "tag": "", "orth": "\u0905\u0932\u094d", "ner": "O", "id": 36}, {"head": 0, "dep": "", "tag": "", "orth": "\u092c\u0926\u093e\u092f\u0942\u0928\u0940", "ner": "O", "id": 37}, {"head": 0, "dep": "", "tag": "", "orth": "\u0915\u0947", "ner": "O", "id": 38}, {"head": 0, "dep": "", "tag": "", "orth": "\u0906\u0927\u093e\u0930", "ner": "O", "id": 39}, {"head": 0, "dep": "", "tag": "", "orth": "\u092a\u0930", "ner": "O", "id": 40}, {"head": 0, "dep": "", "tag": "", "orth": ",", "ner": "O", "id": 41}, {"head": 0, "dep": "", "tag": "", "orth": "\u091c\u093f\u0938\u0928\u0947", "ner": "O", "id": 42}, {"head": 0, "dep": "", "tag": "", "orth": "\u0938\u0928\u094d", "ner": "O", "id": 43}, {"head": 0, "dep": "", "tag": "", "orth": "772", "ner": "O", "id": 44}, {"head": 0, "dep": "", "tag": "", "orth": "\u0939\u093f\u091c\u0930\u0940", "ner": "O", "id": 45}, {"head": 0, "dep": "", "tag": "", "orth": "\u0915\u0947", "ner": "O", "id": 46}, {"head": 0, "dep": "", "tag": "", "orth": "\u0906\u0938\u092a\u093e\u0938", "ner": "O", "id": 47}, {"head": 0, "dep": "", "tag": "", "orth": "\u0907\u0938\u0915\u0940", "ner": "O", "id": 48}, {"head": 0, "dep": "", "tag": "", "orth": "\u092a\u094d\u0930\u0938\u093f\u0926\u094d\u0927\u093f", "ner": "O", "id": 49}, {"head": 0, "dep": "", "tag": "", "orth": "\u0915\u093e", "ner": "O", "id": 50}, {"head": 0, "dep": "", "tag": "", "orth": "\u0909\u0932\u094d\u0932\u0947\u0916", "ner": "O", "id": 51}, {"head": 0, "dep": "", "tag": "", "orth": "\u0915\u093f\u092f\u093e", "ner": "O", "id": 52}, {"head": 0, "dep": "", "tag": "", "orth": "\u0939\u0948", "ner": "O", "id": 53}, {"head": 0, "dep": "", "tag": "", "orth": ",", "ner": "O", "id": 54}, {"head": 0, "dep": "", "tag": "", "orth": "\u0908", "ner": "O", "id": 55}, {"head": 0, "dep": "", "tag": "", "orth": ".", "ner": "O", "id": 56}]}]}]}`

I got this error now... Seems like I forgot to strip in some part of the code, although I have explicitly called string.strip(). Is that the correct method? What could be the cause of having blank spaces?
Could it be that the encoding is not properly set? Or that I'm passing empty strings for the data I don't have (head, dep, tag)?

**Comment by adrianeboyd** [comment]
That sounds more like a misalignment between `raw` and `orth`, but I am not totally sure. Check that you don't actually have an empty `orth` somewhere.

You can try removing `raw` to see if it's a problem with the alignment between `raw` and `orth`. If they don't align perfectly you might end up with weird internal tokens.

Next, I would try leaving out the attributes that you don't have, so try with just `ner` and `orth` for each token.

Also: what's the original format of your data? It might be better to use one of the built-in NER converters with `spacy convert`.

**Comment by adridjs** [comment]
There's no original format of the data, I'm parsing whole Hindi wikipedia and using a method to extract named entities based on Wikidata. I just constructed a parser to follow the format asked in the annotation specs for the NamedEntityRecognizer in Spacy's docs.

I'll first try to feed to the cli the data that will actually be used. If that doesn't work, I'll first to look for any empty 'orth'. I'll report after testing both things. Thank you for your help!

**Comment by adridjs** [comment]
Sorry but I forgot to ask about it, but what do you mean when you say 

> missalignment between `raw` and `orth`

Aren't they supposed to not be the same in most of the cases? Raw being the token and orth being the stem or lemma?

**Comment by adridjs** [comment]
Ok, I just started training and seems it is working. I had a missalignment due to a preprocessing bug that didn't split the input sentence correctly. Nevertheless, it is throwing an `IndexError` when using `-T` as a flag for the `spacy train` command. I'd like to use it because Hindi has many inflections and I think it could be useful to disambiguate words, correct me if I'm mistaken.

Error:
```
python -m spacy train hi /data/disk2/adrinerhindi/ner/ /data/disk2/adrin$
rhindi/wiki_train_ngram.json /data/disk2/adrinerhindi/wiki_dev_ngram.json -n 50 -p ner -ne 3 -t2v /data/disk2/adri$
erhindi/pretrained/model149.bin
⚠ Output directory is not empty
This can lead to unintended side effects when saving the model. Please use an
empty directory or a different path instead. If the specified output path
doesn't exist, the directory will be created for you.
Training pipeline: ['ner']
Starting with blank model 'hi'
Counting training words (limit=0)
Loaded pretrained tok2vec for: ['ner']

Itn  NER Loss   NER P   NER R   NER F   Token %  CPU WPS
---  ---------  ------  ------  ------  -------  -------
✔ Saved model to output directory                                                                                  
/data/disk2/adrinerhindi/ner/model-final

Traceback (most recent call last):
  File "/home/adria/envs/hindi-nlp/lib/python3.6/site-packages/spacy/cli/train.py", line 356, in train
    for batch in util.minibatch_by_words(train_docs, size=batch_sizes):
  File "/home/adria/envs/hindi-nlp/lib/python3.6/site-packages/spacy/util.py", line 569, in minibatch_by_words
    doc, gold = next(items)
  File "gold.pyx", line 222, in train_docs
  File "gold.pyx", line 243, in iter_gold_docs
  File "gold.pyx", line 266, in spacy.gold.GoldCorpus._make_golds
  File "gold.pyx", line 541, in spacy.gold.GoldParse.from_annot_tuples
  File "gold.pyx", line 630, in spacy.gold.GoldParse.__init__
  File "gold.pyx", line 101, in spacy.gold.align
  File "_align.pyx", line 132, in spacy._align.multi_align
  File "_align.pyx", line 167, in spacy._align._get_mapping
IndexError: list index out of range
```

**Comment by adrianeboyd** [comment]
`-T` is a parser setting, so I don't think it should affect an NER model. Something got pasted incorrectly in the comment above and I can't really tell what's going on, sorry.

If you can provide the train command along with the training data that produces a particular error, I can try to look into it, but it sounds like it might still be formatting/conversion problems with your data.
