### ISSUE TITLE
GoldParse.__init__ arguments different from GoldParse.from_annot_tuples

### ISSUE THREAD

**Issue by jessecoleman** [explosion/spaCy#4463]
## How to reproduce the behaviour
in [gold.pyx#L539](https://github.com/explosion/spaCy/blob/master/spacy/gold.pyx#L539) it appears as if the static `from_annot_tuples` function unpacks a tuple of length 7, but in the constructor [gold.pyx#L635](https://github.com/explosion/spaCy/blob/master/spacy/gold.pyx#L635), `self.orig_annot` is populated with a length 6 tuple (discarding the cat annotation). This is creating a bug in the `scorer.py` [score function](https://github.com/explosion/spaCy/blob/master/spacy/scorer.py#L222) where the gold object is reconstructed with `from_annot_tuples` function. I discovered this bug when trying to override the cli train function. 

## Your Environment
* Operating System: Ubuntu 16.04.6 LTS
* Python Version Used: 3.6.8
* spaCy Version Used: 2.2.1
* Environment Information: N/A

**Comment by adrianeboyd** [comment]
Thanks for the report! I must have missed this spot when adding `cats` in 2.2 and I'll look into it...
