### ISSUE TITLE
How to  link to model in entity linking wiki pretrainer?

### ISSUE THREAD

**Issue by petulla** [explosion/spaCy#4474]
When running `wikipedia_pretrain_kb.py` how should the model be linked to? I've tried passing in my parameters like:

`python wikipedia_pretrain_kb.py wd_json='./' wp_xml='./' output_dir="./output' model='/Users/spetulla/...lib/python3.7/site-packages/en_core_web_md/'`

This doesn't work, however. Despite my best efforts, still getting the "can't find model" exception thrown.

I can load the model from spacy with the same path using spacy.load() however. 

Maybe this is the wrong model altogether? 

## Which page or section is this issue related to?
https://github.com/explosion/spaCy/tree/master/bin/wiki_entity_linking

**Comment by svlandeg** [comment]
Hi @petulla, that's weird, because this script calls `spacy.load(model)`, cf https://github.com/explosion/spaCy/blob/master/bin/wiki_entity_linking/wikidata_pretrain_kb.py#L84. Could you paste the log file up until the error and the details of the error message itself?

**Comment by svlandeg** [comment]
Also, are you sure it's not tripping over the `wd_json` or `wp_xml` parameters? Because those are not filled in the arguments your provided here (you have to specify the path including the full name of the file for each, not just its directory)

**Comment by petulla** [comment]
I think it may have been tripping over those.. Adding the explicit paths and removing the keyword arguments and it runs. 🍿

**Comment by svlandeg** [comment]
Update for future reference: the Wikipedia EL code was moved to https://github.com/explosion/projects/tree/master/nel-wikipedia (spaCy v2).
