### ISSUE TITLE
Adding pipe for aliasing name entities.

### ISSUE THREAD

**Issue by Khanifsaleh** [explosion/spaCy#4476]
Is there a way to add pipeline that can aliasing entities name? 
Ex, text = "Obama is President of America". 
Lets the model can return ent.text "Obama" as "Barack Obama"?

So, if we run
`doc = nlp(text)`
`for ent in doc.ents: print(ent.text, ent.label_)`

can return (Barack Obama, Person)

**Comment by svlandeg** [comment]
Hi @Khanifsaleh, the task you're referring to is basically Entity Linking: First identifying the "real world entity" associated to a mention/alias in text, and then replacing each textual occurrence or synonym of this entity, by a canonical description or name such as "Barack Obama" for the real world entity https://www.wikidata.org/wiki/Q76.

We are currently implementing such an Entity Linking functionality in spaCy, though it's sort of in a beta phase. You can find some documentation here: https://spacy.io/usage/linguistic-features#entity-linking. We have run experiments with WikiData as knowledge base, and parsing Wikipedia to get a training set, cf. scripts [here](https://github.com/explosion/spaCy/tree/master/bin/wiki_entity_linking). Once you have the pipe set up and trained, you should be able to run something like `print([(ent.text, ent.label_, ent.kb_id_) for ent in doc.ents])` and `kb_id_` would give you the unique identifier (e.g.  `Q76`).

Like I said we're still working on this functionality so some of the scripts/APIs may still change. Specifically the model accuracy should still be improved. But feel free to try it out and let us know what you think! If you run into specific issues, you can open a new issue :-)

**Comment by swicaksono** [comment]
@svlandeg I'm trying to create new KB with my own dataset by adjusting and modifying the scheme in the https://spacy.io/usage/training#entity-linker. But when I tried to test the saved model and reload the knowledge base and the same instance vocab I got the following error:

```
 print(kb.get_size_entities(), "kb entities:", kb.get_entity_strings())
  File "kb.pyx", line 101, in spacy.kb.KnowledgeBase.get_entity_strings
  File "strings.pyx", line 136, in spacy.strings.StringStore.__getitem__
KeyError: "[E018] Can't retrieve string for hash '14568781525751431168'. This usually refers to an issue with the `Vocab` or `StringStore`."

```

Any helps? Thanks.

**Comment by svlandeg** [comment]
Hi @swicaksono : could you open a separate issue for this? To keep a good overview on the issue tracker, it's easier for us to track one issue at the time. It's probably also useful to include a bit more of your code (the saving and loading of the vocab/nlp object for example).
