### ISSUE TITLE
Jupyter notebook on Anaconda OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

### ISSUE THREAD

**Issue by toshreyansjain** [explosion/spaCy#4480]
## spaCy validation on Jupyter
!python -m spacy validate

✔ Loaded compatibility table

====================== Installed models (spaCy v2.1.8) ======================
ℹ spaCy installation:
/Users/shreyansjain_2/anaconda3/envs/ENV3/lib/python3.7/site-packages/spacy

TYPE      NAME             MODEL            VERSION                            
package   en-core-web-sm   en_core_web_sm   2.1.0   ✔
package   en-core-web-lg   en_core_web_lg   2.1.0   ✔
link      en_core_web_lg   en_core_web_lg   2.1.0   ✔
link      en_default       en_core_web_sm   2.1.0   ✔
link      en               en_core_web_sm   2.1.0   ✔

-----------
##  Spacy works well on terminal :
(ENV3) Shreyanss-MBP:~ shreyansjain_2$ python -m spacy validate
✔ Loaded compatibility table

====================== Installed models (spaCy v2.1.8) ======================
ℹ spaCy installation:
/Users/shreyansjain_2/anaconda3/envs/ENV3/lib/python3.7/site-packages/spacy

TYPE      NAME             MODEL            VERSION                            
package   en-core-web-sm   en_core_web_sm   2.1.0   ✔
package   en-core-web-lg   en_core_web_lg   2.1.0   ✔
link      en_core_web_lg   en_core_web_lg   2.1.0   ✔
link      en               en_core_web_sm   2.1.0   ✔

(ENV3) Shreyanss-MBP:~ shreyansjain_2$ python
Python 3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> nlp = spacy.load('en_core_web_sm')
>>> doc = nlp("She ate the  pizza")
>>> for token in doc:
...    print(token.text, token.pos_)
... 
She PRON
ate VERB
the DET
  SPACE
pizza NOUN
>>> 

---------

##  I am not able to fix this on jupyter.
Already did following on Jupyter notbook :
!python -m spacy download en
!python -m spacy link en_core_web_sm en_default

-------------

##  Here is the error on jupyter when I run any of following commands : 
import spacy
nlp = spacy.load('en')

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-21-5a0e94ab804c> in <module>
      1 #Spacy Statistical model
      2 import spacy
----> 3 nlp = spacy.load('en')

~/anaconda3/lib/python3.7/site-packages/spacy/__init__.py in load(name, **overrides)
     25     if depr_path not in (True, False, None):
     26         deprecation_warning(Warnings.W001.format(path=depr_path))
---> 27     return util.load_model(name, **overrides)
     28 
     29 

~/anaconda3/lib/python3.7/site-packages/spacy/util.py in load_model(name, **overrides)
    169     elif hasattr(name, "exists"):  # Path or Path-like to model data
    170         return load_model_from_path(name, **overrides)
--> 171     raise IOError(Errors.E050.format(name=name))
    172 
    173 

OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

or 

nlp = spacy.load('en_core_web_sm')

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-15-12102ff9e1a9> in <module>
----> 1 nlp = spacy.load('en_core_web_sm')

~/anaconda3/lib/python3.7/site-packages/spacy/__init__.py in load(name, **overrides)
     25     if depr_path not in (True, False, None):
     26         deprecation_warning(Warnings.W001.format(path=depr_path))
---> 27     return util.load_model(name, **overrides)
     28 
     29 

~/anaconda3/lib/python3.7/site-packages/spacy/util.py in load_model(name, **overrides)
    169     elif hasattr(name, "exists"):  # Path or Path-like to model data
    170         return load_model_from_path(name, **overrides)
--> 171     raise IOError(Errors.E050.format(name=name))
    172 
    173 

OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

## How to reproduce the problem

Here is the error on jupyter when I run any of following commands : 
import spacy
nlp = spacy.load('en')

or

nlp = spacy.load('en_core_web_sm')

OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

## Your Environment

* Operating System: macos : 10.15 (19A602)
* Python Version Used: 3.7.4 (Anaconda installation)
* spaCy Version Used: 2.1.0
* Environment Information: macbook pro

**Comment by svlandeg** [comment]
spaCy and the models seem to be installed correctly in your virtual environment `ENV3`, and the path to this install is `/Users/shreyansjain_2/anaconda3/envs/ENV3/lib/python3.7/site-packages/spacy` as shown by your log files.

However the error message shows that when you're executing `spacy.load(...)`, it's accessing a spaCy install at `~/anaconda3/lib/python3.7/site-packages/spacy/`, which is the default location for your Anaconda installation and not the path to your specific virtual environment `ENV3`. So I think you'll have to double check that you're actually executing your notebook in the correct environment.
