### ISSUE TITLE
Custom Pipeline

### ISSUE THREAD

**Issue by Khanifsaleh** [explosion/spaCy#4481]
I want to make the model can return full name of entites (PERSON). 
For example:
 
`def my_component(doc):`
      `my_dict = {"Thrump":"Donald Thrump","Jokowi":"Joko Widodo"}`
      `for ent in doc.ents:`
             `if ent.text in my_dict.keys():`
                     `return my_dict[ent.text]`

`nlp = spacy.load(path/to/model)`
`nlp.add_pipe(my_component, before='ner')`
`text = "Thrump is President of America and Jokowi is president of Indonesia"`
`doc = nlp(text)`

So, if I run:
`for ent in doc.ents:`
the model return ent.text : Donald Trumph and Jokowi Widodo

**Comment by adrianeboyd** [comment]
`doc.ents` returns `Span` elements, where `span.text` should always correspond to the actual tokens in the text. Instead, you could add a [custom extension](https://spacy.io/usage/processing-pipelines#custom-components-attributes) to `Span` to store the full name.

Here's how to create a custom pipeline component: https://spacy.io/usage/processing-pipelines#custom-components
