### ISSUE TITLE
Universal POS Tag scheme discrepancies

### ISSUE THREAD

**Issue by chrisjbryant** [explosion/spaCy#4485]
Although I raised this issue ages ago (#593) and I know some work has been done on it, I just want to let you know there is still a discrepancy in the way spacy maps fine POS tags to coarse POS tags for English.

Specifically, the current spacy [tag_map](https://github.com/explosion/spaCy/blob/master/spacy/lang/en/tag_map.py) maps PRP$ and WP$ to PRON while Universal Dependencies map them to DET ([UD tag map](https://universaldependencies.org/tagset-conversion/en-penn-uposf.html)). These are words like "_my_ car" and "_whose_ car", which UD lists as examples of determiners ([link](https://universaldependencies.org/u/pos/DET.html)).

I also noticed some old information on the annotation specifications page:
https://spacy.io/api/annotation#pos-tagging

Specifically, the header in the Universal Part-of-speech Tags tab says you use the Universal Dependencies scheme, while the headers in the English and German tabs say you use the Google Universal Tagset. The latter is no longer true (although maybe it is for German?)!

**Comment by adrianeboyd** [comment]
Thanks for bringing this up again! The tag maps should all be to UD v2 at this point, so this is a mistake. I'll verify the conversion tables based on the UD conversion info and update the documentation.
