### ISSUE TITLE
Tokenizer edge condition - back-to-back parentheses

### ISSUE THREAD

**Issue by pythonBerg** [explosion/spaCy#4490]
The tokenizer is return unexpected results for me in 2.1.8. I know I can enhance by extending, but I though this obvious enough to report...

"Twenty-four thousand, two hundred dollars ($24,000,200)(the loan amount)"

I am seeing where tokens include "(", $24,000,200)(the" and the remainder as expected. It seems like the prefix and suffix regexs are conflicting and thus ignored. Perhaps adding each of \) \( to infix would solve...it has for me in testing

**Comment by adrianeboyd** [comment]
The prefix and suffix regexes look at the edges of whitespace-separated segments, so they wouldn't be applied here. As you observed, you would need to treat this as an infix if you want to extend the tokenizer to split tokens like this.

I think this is a unusual/special case that doesn't really need to be handled by the default (English) tokenizer.

**Comment by pythonBerg** [comment]
So am I correct, that to customize I should be able to...

        infixes = nlp.Defaults.infixes + (r'''\)\(''',)
        infix_regex = spacy.util.compile_infix_regex(infixes)
        nlp.tokenizer.infix_finditer = infix_regex.search

This is mirroring the current example for suffixes. It also causes error 
TypeError: 'NoneType' object is not iterable

**Comment by adrianeboyd** [comment]
Infixes use `.finditer` rather than `.search`:

```
nlp.tokenizer.infix_finditer = infix_regex.finditer
```

**Comment by pythonBerg** [comment]
Thanks. Might be good note in documentation. So many like me cut and paste until we can't
