### ISSUE TITLE
ImportError: cannot import name 'get_string_id' from 'spacy.strings'

### ISSUE THREAD

**Issue by LizMcQuillan** [explosion/spaCy#4491]
Installing and loading spaCy on a new machine. I've done this a few times, but have never run into errors before. I had a handful error messages to get through just to install and import spacy (things like #2514) and in the end I manually deleted all spaCy files and directories to do a clean installation. 

Not sure what to do here.

### My code:
```
from spacy.lang.en.stop_words import STOP_WORDS
from spacy.lang.en import English
parser = English()
from spacy import en_core_web_sm
nlp = spacy.load("en_core_web_sm")
```

### Full Traceback:
```---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-28-8db0160a0952> in <module>
      2 #!python -m spacy download en
      3 from spacy.lang.en.stop_words import STOP_WORDS
----> 4 from spacy.lang.en import English
      5 parser = English()
      6 from spacy import en_core_web_sm

~/anaconda3/lib/python3.7/site-packages/spacy/lang/en/__init__.py in <module>
     12 from ..tokenizer_exceptions import BASE_EXCEPTIONS
     13 from ..norm_exceptions import BASE_NORMS
---> 14 from ...language import Language
     15 from ...attrs import LANG, NORM
     16 from ...util import update_exc, add_lookups

~/anaconda3/lib/python3.7/site-packages/spacy/language.py in <module>
     15 from .vocab import Vocab
     16 from .lemmatizer import Lemmatizer
---> 17 from .lookups import Lookups
     18 from .pipeline import DependencyParser, Tagger
     19 from .pipeline import Tensorizer, EntityRecognizer, EntityLinker

~/anaconda3/lib/python3.7/site-packages/spacy/lookups.py in <module>
      8 from .errors import Errors
      9 from .util import SimpleFrozenDict, ensure_path
---> 10 from .strings import get_string_id
     11 
     12 

ImportError: cannot import name 'get_string_id' from 'spacy.strings' (/Users/lmcquillan/anaconda3/lib/python3.7/site-packages/spacy/strings.cpython-37m-darwin.so)
```

## My Environment
* **Operating System: Mac
* **spaCy version:** 2.2.1
* **Platform:** Darwin-18.7.0-x86_64-i386-64bit
* **Python version:** 3.7.3
* **Models:** en

**Comment by ines** [comment]
It looks like you somehow ended up with an old installation and conflicting files (compiled artifacts from a previous version that don't yet include new functions).

Are you installing with `pip` or `conda`? If you're using pip with the Anaconda environment, try installing from conda instead, and make sure to use a clean virtual environment. Also, how are you setting up Anaconda? Are you using the official Anaconda distribution? It's possible that the distribution already includes an older version of spaCy that ends up causing problems. I do think the conda environment stuff is likely the cause of the problem here.

Unfortunately, those are all things we don't have much control over 😞 All we can do is make sure we always provide the latest versions on conda (via `conda-forge`) and pip, and provide pre-compiled binary wheels for the supported platforms.

**Comment by LizMcQuillan** [comment]
> It looks like you somehow ended up with an old installation and conflicting files (compiled artifacts from a previous version that don't yet include new functions).

That is possible. However, prior to this installation I uninstalled spaCy and manually deleted all spaCy files. I believe this would have eliminated any older versions or files, no?

> Are you installing with `pip` or `conda`? 

I used `conda install -c conda-forge spacy` as other issues have recommended.


>Also, how are you setting up Anaconda? Are you using the official Anaconda distribution?

Yes

>It's possible that the distribution already includes an older version of spaCy that ends up causing problems. I do think the conda environment stuff is likely the cause of the problem here.

Again, that is possible. However, prior to this installation I uninstalled spaCy and manually deleted all spaCy files. I believe this would have eliminated any older versions or files, no?
How would I check this?

**Comment by svlandeg** [comment]
Hi  @LizMcQuillan : from the paths in your error trace (`~/anaconda3/lib/python3.7/site-packages/spacy/`) it looks like you're accessing the default Conda location. Could you instead try installing in a new virtual environment?

**Comment by LizMcQuillan** [comment]
When I use a fresh venv , the same code yields:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-58c87616cdfd> in <module>
      4 from spacy.lang.en import English
      5 parser = English()
----> 6 from spacy import en_core_web_sm
      7 nlp = spacy.load("en_core_web_sm")

ImportError: cannot import name 'en_core_web_sm' from 'spacy' (/Users/lmcquillan/anaconda3/lib/python3.7/site-packages/spacy/__init__.py)
```

I get this error even after specifically downloading en_core_web_sm like so :
`(spacy-venv) (base) graphikas-MacBook-Pro-4:~ lmcquillan$ python -m spacy download en_core_web_sm`

I can see from the traceback that even in a virtual environment it still seems to be looking in the anaconda directory. I double check this using `spacy.util.get_data_path()`, which unsurprisingly returns `PosixPath('/Users/lmcquillan/anaconda3/lib/python3.7/site-packages/spacy/data')`

**Comment by svlandeg** [comment]
Hm, yes, it is indeed still looking in the Anaconda directory. So that's not good :(
Are you sure you're executing that code within the correct virtual environment? Is this in a jupyter notebook? Can you run `which python` ?

**Comment by LizMcQuillan** [comment]
which python returns `/Users/lmcquillan/spacy-venv/bin/python`

Also, when I use validate to make sure I have actually downloaded the model I get the following:

```
(spacy-venv) (base) graphikas-MacBook-Pro-4:~ lmcquillan$ python -m spacy validate
✔ Loaded compatibility table

====================== Installed models (spaCy v2.2.1) ======================
ℹ spaCy installation:
/Users/lmcquillan/spacy-venv/lib/python3.7/site-packages/spacy

TYPE      NAME             MODEL            VERSION                            
package   en-core-web-sm   en_core_web_sm   2.2.0   ✔
```

For additional context here is the output from 
`pwd`: 
`'/Users/lmcquillan/spacy_venv_notebook'`

and `sys.path:`
`['/Users/lmcquillan/NIH_Topic_Modeling', '/Users/lmcquillan/anaconda3/lib/python37.zip', '/Users/lmcquillan/anaconda3/lib/python3.7', '/Users/lmcquillan/anaconda3/lib/python3.7/lib-dynload', '', '/Users/lmcquillan/anaconda3/lib/python3.7/site-packages', '/Users/lmcquillan/anaconda3/lib/python3.7/site-packages/javabridge-1.0.18.post16+gc7ccaed-py3.7-macosx-10.9-x86_64.egg', '/Users/lmcquillan/anaconda3/lib/python3.7/site-packages/IPython/extensions', '/Users/lmcquillan/.ipython']`

**Comment by ines** [comment]
> ```
> ----> 6 from spacy import en_core_web_sm
> ```

I think the problem here is that this is expected to fail. `spacy` has no module `en_core_web_sm`. You can either run `nlp = spacy.load("en_core_web_sm")` or run `import en_core_web_sm`.

**Comment by LizMcQuillan** [comment]
@ines - commented that line out and everything ran with no issues.
