### ISSUE TITLE
Tokenizer missing data during enumeration

### ISSUE THREAD

**Issue by davidbren** [explosion/spaCy#4494]
## How to reproduce the behaviour
from spacy.tokenizer import Tokenizer

    tokens = tokenizer(sample)
    result = len(tokens.text)

    print("tokens length " + str(result))
    
    totalTokenSize = 0

    for i in tokens:
        totalTokenSize = totalTokenSize + len(i.text)

    print("totalTokenSize " + str(totalTokenSize))

Output is 

tokens length   34,980
totalTokenSize  30,034

So I am missing 4.946 when I loop vs when I take length 

## Your Environment
* Operating System: Windows 10 
* Python Version Used: 3.6
* spaCy Version Used: 2.1.8

**Comment by adrianeboyd** [comment]
Each token may have a following space that is not included in `len(token.text)`. If you want the full length, you need `len(token.text_with_ws)`.

**Comment by svlandeg** [comment]
`tokens.text` is the original text of your document though, so len(`tokens.text`) would count all the characters including spaces. While `token.text` doesn't include space.

**Comment by davidbren** [comment]
I have done a diff between the two strings & I can see that the tokens in the enumeration are missing spaces? So how do I loop through the tokens in a way that preserves the spaces ?

**Comment by davidbren** [comment]
That works !  Thanks very much Sofie :)
