### ISSUE TITLE
Multiple tokens generated for a plural form

### ISSUE THREAD

**Issue by ewaldatsensentia** [explosion/spaCy#4495]
This happens for "thats" and "whens".  Both those words are in the nlp.vocab.  They are split into tokens "that" and "s" by both nlp and nlp.make_doc.
## How to reproduce the behaviour
import spacy
nlp =  spacy.load('en_core_web_md')
for t in nlp("How many thats are in this sentence?"): print (t,t.lemma_)
## output
How how
many many
that that
s s
are be
in in
this this
sentence sentence
? ?

## Your Environment
* **spaCy version:** 2.2.1
* **Platform:** Windows-10-10.0.18362-SP0
* **Python version:** 3.7.3

**Comment by adrianeboyd** [comment]
These are tokenizer exceptions for English specified here:

https://github.com/explosion/spaCy/blob/b0bdb18b4d3bc74448e37ccb8cc0901c4693a570/spacy/lang/en/tokenizer_exceptions.py

Contractions like "that's" are sometimes written without the apostrophes, which is where this is coming from. If you don't want this behavior, you'll have to create a custom tokenizer with a different set of exceptions (`rules`). Here's a sketch of how to do this in general:

https://stackoverflow.com/a/58112065/461847

Of course, you would want to customize the exceptions rather than the infix patterns.

**Comment by ewaldatsensentia** [comment]
If this is coming from "that's", shouldn't the lemmas be "that" and "'s"?

**Comment by adrianeboyd** [comment]
Right now that's not specified in the exception (although it could be) and if you did specify it, the lemma should be "be".

**Comment by adrianeboyd** [comment]
Sorry, I misread your comment. I think it would make sense to set `NORM` to `'s` in these cases, but `token.text` should always correspond to the exact string covered by the token in the text.

**Comment by ewaldatsensentia** [comment]
I see the code is consistent in the other cases as well.  I just don't understand the utility of returning 's'.  Maybe I am missing something?  I would argue that you should change all of them to "'s", etc.

**Comment by adrianeboyd** [comment]
Normalization is tricky. spacy is careful to never modify the original text in any of its processing and `token.text` will always correspond to a substring of `doc.text`. If you have normalizations, you can store them in `token.norm` or in your own custom extensions if you need to, or you can preprocess your texts before processing them with spacy.

**Comment by ewaldatsensentia** [comment]
I see the problem.  So you won't be able to use the lemma of "s", unfortunately, as in 
doc = nlp("Thats the end.")  Preprocessing might be best for most cases.

**Comment by adrianeboyd** [comment]
Whether `s` is analyzed correctly in this context depends on the tagger and the lemmatization rules. It's totally possible to have your intended analysis just as for `'s`, but I think the lemmatizer doesn't know what to do with `VBZ`/`s`. (`VBZ` can really only be `is`, so the analysis with the small 'en' model is already very very close. Just the rule-based lemmatizer doesn't know how to handle this case. If you want to make this change, it should be very easy!

**Comment by ewaldatsensentia** [comment]
Thank you for the explanations.
