### ISSUE TITLE
Train entitiy linking always get segmented fault

### ISSUE THREAD

**Issue by swicaksono** [explosion/spaCy#4502]
I successfully created the KB model by using my own dataset. Well, when I'm gonna try to train and add the EL component into the pipeline alongside with NER, I've had always encountered the error segmented fault (core dump), although the vocab is the one I used to create the KB model. I trace it and it's always when load_bulk the KB model.
 
```
KnowledgeBase(vocab=nlp.vocab)

# here I've always get segmented fault
kb.load_bulk(os.path.join(path_kb, lang))
```
Any helps?
Thanks.

## Your Environment

* Operating System: Ubuntu 19
* Python Version Used: 3.6.6
* spaCy Version Used: 2.2.1

**Comment by svlandeg** [comment]
Hi @swicaksono, sorry to hear you're running into issues!
Could you provide the actual error message ? I think the `load_bulk` method may not be very robust to different path formatting.

**Comment by swicaksono** [comment]
So by putting the kb model into the same directory with the train code?. Ok, I'll try it. 
Here is the code for storing kb model as part of the train function. 
```
# vocab_path
vocab_path = os.path.join(path_model, 'lang', 'vocab')
# save kb model
output_dir = Path(os.path.join(path_kb, self.lang))
if not output_dir.exists():
      output_dir.mkdir()
kb_path = str(output_dir / "kb")
kb.dump(kb_path)
print("Saved KB to ", kb_path)

print ()
print("Loading vocab from", vocab_path)
print("Loading KB from", kb_path)
vocab2 = Vocab().from_disk(vocab_path)
kb2 = KnowledgeBase(vocab=vocab2)
kb2.load_bulk(kb_path)
_print_kb(kb2)
        print()
```

So before this, I got an issue #4476 about the missing key in the Vocab, but then I figured out that I forget to do the `kb.vocab.to_disk(vocab_path)`. Well, what I'm still confused here is that the vocab path that written in the [doc](https://github.com/explosion/spaCy/blob/master/examples/training/pretrain_kb.py) is the same as the vocab from the model we load when we do the `kb.vocab_to_disk(vocab_path)` or it should be anywhere? Thanks.

**Comment by svlandeg** [comment]
Ok, so in the example script `pretrain_kb.py` you either provide an existing `nlp` model or a `vocab` object. This is used to then create the KB with. Subsequently, when you are adding entities and aliases to the `kb`, its `vocab` object will change to hold new words, and at the end of this script you should again store the `vocab` somewhere on file. Then when you create the actual Entity Linking pipe (e.g. with `train_entity_linker.py`) you need to give it both the path to the `kb` object as well as to the (adjusted) `vocab`.

If you're having an issue at the line `kb.load_bulk()`, you are most likely not passing the exact right path to the KB file. It should be exactly the same as the call to `kb.dump()`.
