### ISSUE TITLE
Losing pos feature when saving/loading with to_disk/from_disk

### ISSUE THREAD

**Issue by johann-petrak** [explosion/spaCy#4503]
## How to reproduce the behaviour

The following code demonstrates that all the POS tags (feature pos_/pos) are blank/0  
after saving and loading using the to_disk/from_disk methods. 
On the other hand the tag and dp features are restored fine.
But ... why????

```python
from spacy.tokens import Doc
from spacy.vocab import Vocab
import spacy 
nlp = spacy.load("de")

t1 = "Dies ist ein deutscher Satz. Und hier noch einer."

doc1 = nlp(t1)
print("Version: ", spacy.__version__)
print("After NLP: ", [t.pos_ for t in doc1])
print("After NLP: ", [t.pos for t in doc1])
print("As JSON: ", doc1.to_json())

doc1.to_disk("debug_spacy_save.spacy")
doc1.vocab.to_disk("debug_spacy_save_vocab.spacy")

voc2 = Vocab().from_disk("debug_spacy_save_vocab.spacy")
doc2 = Doc(voc2).from_disk("debug_spacy_save.spacy")
print("After Load: ", [t.pos_ for t in doc2])
print("After Load: ", [t.pos for t in doc2])
print("As JSON: ", doc2.to_json())
```

## Info about spaCy

* **spaCy version:** 2.1.6
* **Platform:** Linux-4.15.0-62-generic-x86_64-with-debian-buster-sid
* **Python version:** 3.6.9
* **Models:** es, en, de

**Comment by adrianeboyd** [comment]
Hi, this has been fixed in v2.2. (`pos` is always mapped from `tag`, so it is not stored in quite the same way.)
