### ISSUE TITLE
Vectors.most_similar should always return 1.0 for identical vectors

### ISSUE THREAD

**Issue by ines** [explosion/spaCy#4506]
We should probably hard-code the workaround for the imprecision, just like we do for the built-in similarity methods.

## How to reproduce the behaviour

https://github.com/explosion/spaCy/blob/74a19aeb1cc384e8ccdff8b664c9df0550be2f92/spacy/tests/vocab_vectors/test_vectors.py#L144-L154

**Comment by svlandeg** [comment]
Just out of curiosity - why is this a requirement? Shouldn't equality on real values always be tested with some margin?

**Comment by ines** [comment]
@svlandeg It's not really a requirement, but when we didn't clip the values for the `.similarity` methods, people found this pretty confusing (e.g. when `nlp("x").similarity(nlp("x"))` wasn't `1.0`). And since we're doing it this way for other similarity comparisons, we might as well do it for the `most_similar`.
