### ISSUE TITLE
spacy sentencizer is breaking the sentences at irrelevant points.

### ISSUE THREAD

**Issue by niki33** [explosion/spaCy#4508]
## How to reproduce the behaviour
  self.nlp = English()
        sentencizer = self.nlp.create_pipe("sentencizer")
        self.nlp.add_pipe(sentencizer)
         faq_answerr_token_doc = self.nlp("The weekly off/holidays, during the rainy period, shall not be counted as a leave in a government office. (Weekly off refers to employees who are in support roles working on a follow the moon model, granted a weekly day off in lieu of weekends).")

It should break the sentence at "." but it is breaking at "(". 
Hence the response looks like below:
1.) The intervening weekly off/holidays, during the leave period, shall not be counted as leave. (
2.) Weekly off refers to employees who are in support roles working on a follow the sun model, granted a weekly day off in lieu of weekends).")

## Your Environment

* Operating System: Linux and windows
* Python Version Used:3.6.3
* spaCy Version Used:2.1.8
* Environment Information: I am using this with the Rasa framework 3.6.2.

**Comment by adrianeboyd** [comment]
See: https://stackoverflow.com/q/58516766/461847

**Comment by niki33** [comment]
@adrianeboyd It would be really helpful if you could share a code snippet of the parser of the English model.

**Comment by adrianeboyd** [comment]
Please have a look at the docs: https://spacy.io/usage/processing-pipelines

**Comment by PiotrCzapla** [comment]
@niki33  I have similary hard time using the pipeline and @adrianeboyd  comments would only set me off.

The issue is that Parser is unreliable on my text (Scientific papers) SciSpacy doesn't help, and custom sentencizer is very simplistic,  it splits the sentences each time it notice the "." , but instead of splitting it exactly at the dot it skips all the "punctation" tokens and splits on the first word. The "(" is punctation token. Have a look at the code:
https://github.com/explosion/spaCy/blob/f8d740bfb1c7d41d7c0e34a57e70a11bc86572ab/spacy/pipeline/pipes.pyx#L1462-L1475

If you really care about ( ,you could modify it to not threat the (  as punctation. 

But you will end up with other issues like splitting sentences on "e.g." or "et al." or "J.",  as it is by default it is tokenized to "e" "." "g" "." which is 2 times dot - 2 new sentences. To fix this issue I'm using a Matcher to detect such common abbreviations and join them.

**Comment by PiotrCzapla** [comment]
I've checked again scispacy and the reason it wasn't working was that sentence boundaries aren't fixed in the parser!
They have their own rule based Sentencizer: https://github.com/allenai/scispacy/blob/master/scispacy/custom_tokenizer.py that uses: https://github.com/nipunsadvilkar/pySBD .

**Comment by adrianeboyd** [comment]
As I said on StackOverflow, the sentencizer is good for splitting texts with formal punctuation into sentence-ish chunks and it's very fast, but it's extremely simple and it's not going to have high accuracy on scientific texts with a lot of complicated punctuation usage.

The parsers in the scispacy models do set sentence boundaries just like the parsers in the spacy models. I just tested `en_core_sci_sm` and `en_core_sci_md` v0.2.4, which are the current models for spacy v2.2:

```
import spacy
import scispacy
nlp = spacy.load("en_core_sci_sm")
doc = nlp("The weekly off/holidays, during the rainy period, shall not be counted as a leave in a government office. (Weekly off refers to employees who are in support roles working on a follow the moon model, granted a weekly day off in lieu of weekends).")
print([sent.text for sent in doc.sents])
# ['The weekly off/holidays, during the rainy period, shall not be counted as a leave in a government office.', '(Weekly off refers to employees who are in support roles working on a follow the moon model, granted a weekly day off in lieu of weekends).']
```

The default spacy models are mostly trained on newspaper and web text, so they may not do as well on scientific text as other models/approaches. I haven't tested it myself, but a rule-based SBD component like pySBD is a good choice as long as its rules work for your task.

Another helpful section of the documentation might be: http://spacy.io/usage/linguistic-features#sbd

**Comment by PiotrCzapla** [comment]
@adrianeboyd  Thank you for the explanation. I've used sbd and it is working fine as far as I can see, but it is super slow. I was thinking about using it to generate sentence boundaries and then combining it with the data from news and web to update the model. Do you know maybe if the data on which the spacy model was trained is available?

btw. the `#sbd ` section does not exists on linguistic-features, have you meant: https://spacy.io/universe/project/python-sentence-boundary-disambiguation
