### ISSUE TITLE
spacy_factories in nlp.meta

### ISSUE THREAD

**Issue by tamuhey** [explosion/spaCy#4514]
I made many custom components of spacy, and sometimes I want to put same components in one nlp pipeline.
I tried changing one of their name and they can be put in one pipeline, but that made it impossible to restore with `spacy.load`.

So it is great if `nlp.meta` can holds `spacy_factories` to avoid confliction.

**Comment by christian-storm** [comment]
I agree with the need for this.  I ended up writing my own. To achieve this I ended up writing a wrapper around spacy.  With this I can also swap in different tokenizers and a preprocessing pipeline.  It required me to override mac_doc and pipeline factories.

**Comment by ines** [comment]
See #4517 🙂 We'll be shipping this as part of v2.2.2, so you can start trying it out before the `@component` decorator becomes "official" in spaCy v3. Decorated components will automatically register their factories and provide both their name and factory name (so spaCy knows that `textcat_a` needs the `textcat` factory, and so on).

**Comment by tamuhey** [comment]
@ines Thanks! But I want to restore the pipe when  `spacy.load("packaged_dir")`. 
I think it is required that `cli.package` generate `spacy_factories` entry in `setup.py`, and the mapping of model name to its actual implementation is retrieved from nlp.meta.
