### ISSUE TITLE
Is there a way to call only sentence and word tokenization?

### ISSUE THREAD

**Issue by phdowling** [explosion/spaCy#453]
I need to tokenize a lot of text, but I also need sentences. My problem is basically that processing the full pipeline takes quite a long time, and I really only need a few of it's features. I'm not interested in grammatical parsing, NER and things like that - is there a way to call only the sentence tokenizer via `nlp.pipe()` ?

I've been able to use the regular tokenizer via `nlp.tokenizer.pipe(...)`, but I haven't found an equivalent for sentence tokenization.

**Comment by Terrilocks** [comment]
I run just the word tokenizer by running:
```
nlp = spacy.load("en")
doc = nlp("text goes here", parser=False, tagger=False, entity=False)
```

Unlike most other NLP tools, spaCy uses the parse tree to do sentence tokenization so I believe you can't do sentence tokenization without pos tagging and parsing. The devs previously told me this was more robust than using some other rule-based method.

**Comment by DomHudson** [comment]
Note:

It is now:
```
nlp = spacy.load("en")
doc = nlp("text goes here", parse=False, tag=False, entity=False)
```

**Comment by benjaminvdb** [comment]
**Note**

API changed again. It is now:

```
nlp = spacy.load("en")
doc = nlp(u"text goes here", disable=[parser,tagger,ner])
```

**Comment by phdowling** [comment]
@benjaminvdb Is that right, shouldn't those be strings or are those symbols imported from somewhere?

**Comment by benjaminvdb** [comment]
It is right. I've updated my comment with a reference to the documentation.

**Comment by phdowling** [comment]
@benjaminvdb Ah, I see - you are just missing the quotation marks inside the list

**Comment by benjaminvdb** [comment]
@phdowling Ah, now I see what you mean. My bad! I've updated the comment.
