### ISSUE TITLE
Backport memory leak fix to patch spacy 2.0 and 2.1

### ISSUE THREAD

**Issue by kabirkhan** [explosion/spaCy#4538]
## Feature description

My team (and I assume a lot of other companies) are using spacy 2.0 and 2.1 in various places. We have A LOT of trained models in spacy 2.0 and 2.1. It would be great to have the fix @adrianeboyd made here https://github.com/explosion/spaCy/pull/4486 for the memory leak ported back to the older versions as well since it's a really small change with a pretty huge impact.

i.e. It's much easier to upgrade to spacy 2.1.9 from 2.1.8 rather than 2.2.2 and retrain all the models we have.

Thanks!

And not sure this counts as a feature request but didn't seem like a bug either haha.

**Comment by adrianeboyd** [comment]
It would be easy to backport this to 2.1. I'm less sure about 2.0 but I will look into it.

**Comment by adrianeboyd** [comment]
I had to double-check to be sure, but 2.0 is not affected by this bug. A quick analysis didn't find any similar memory leaks in 2.0.

**Comment by ines** [comment]
Here's a v2.1.x branch that we can add this to and release from: https://github.com/explosion/spaCy/tree/v2.1.x

**Comment by honnibal** [comment]
Definitely happy to support this. Do you see any other patches you want while you're there?

Btw, a feature we haven't really advertised, but might be helpful for you: if you type "make" in the repo you'll get a `dist/spacy.pex` file. This is an executable that only depends on the Python interpreter on the system. When you run it it basically unzips a virtualenv and runs it --- it's like a jar file. So if you're using spaCy's CLI, it's a nice way to deploy.

**Comment by ines** [comment]
@kabirkhan See #4542. v2.1.9 should be up soon – just building the sdist and wheels 🙌

**Comment by kabirkhan** [comment]
...meant to comment here not the PR:

Haha, our time difference is pretty evident here. Thank you all for the quick responses and for getting this out. Really appreciate the fast turnaround!
