### ISSUE TITLE
No wheels for 2.1.9

### ISSUE THREAD

**Issue by HiromuHota** [explosion/spaCy#4546]
First of all, congratulations on the v2.1.9 release.
It's been released just two hours ago, but no wheels are available to download yet.
Please build and upload wheels.

**Comment by honnibal** [comment]
Thanks, the CI was just a little slow, leading to the gap. They should be up over the next 5-10 minutes.

**Comment by HiromuHota** [comment]
Thanks for replying. Now my CI can pick up the wheel.
