### ISSUE TITLE
Unable to update stop words list in en_core_web_sm

### ISSUE THREAD

**Issue by LizMcQuillan** [explosion/spaCy#4547]
## How to reproduce the behaviour
Attempting to append the default stop words list, but can't seem to add anything using either

```
more_stops = ['like', 'vet', 'veteran', 'Veterans']
STOP_WORDS.update(more_stops)
```

or 

`nlp.Defaults.stop_words |= {"like", "vet", "veteran", "Veterans"}`

Neither command results in an error message, but when I go on to filter out stop words they remain in the dataset.

**Comment by svlandeg** [comment]
Could it be that you're changing the stop words after initializing the `nlp` object? A full code snippet would be helpful to diagnose further. 

As far as I can see, the stop words are read when [creating](https://github.com/explosion/spaCy/blob/master/spacy/language.py#L68) the `vocab`, and this probably isn't updated if you changed the stop words afterwards. Could you try switching the order as a workaround ?

**Comment by ines** [comment]
The first code snippet isn't going to work, because you're just editing the default stop words shipped with the library.

The second approach should work – however, stop words are cached with the vocab, so if you want to modify them, you should do that *before* you process text. Once you've processed a token, its `is_stop` value is cached.

```python
nlp = spacy.load("en_core_web_sm")                                                                                        
nlp.Defaults.stop_words |= {"xyz"}                                                                                 
print([t.is_stop for t in nlp("hello xyz")])                                                                          
# [False, True]
```
