### ISSUE TITLE
CharacterEmbed broken in architecture refactor

### ISSUE THREAD

**Issue by svlandeg** [explosion/spaCy#4550]
With respect to current code on `master` branch.

https://github.com/explosion/spaCy/blob/master/spacy/ml/tok2vec.py#L88 doesn't work because it needs to refer to https://github.com/explosion/spaCy/blob/master/spacy/_ml.py#L913 instead of to its own constructor (the one in `_ml.py` then probably needs to be moved or you'd get a circular dependency from `_ml` to `ml.py` and back?)

Further issues: https://github.com/explosion/spaCy/blob/master/spacy/ml/tok2vec.py#L20: 
> tok2vec = chain(doc2feats, with_flatten(chain(embed, encode), pad=field_size))

This works when `embed` is `MultiHashEmbed`, but doesn't work if it's `CharacterEmbed` because the latter needs access to the original `Doc`, and thus perhaps `doc2feats` and `embed` need to be `concatenate_lists()`'d in this case?

Stumbled upon all this when running `ud_train.py`, which uses `build_morphologizer_model()` which sets 
> char_embed = cfg.get("char_embed", True)

Setting that to `False`, makes the script run again.

@honnibal : considering this is new code and I assume you're still working on this, let me know if you'd rather fix this yourself or if you'd like me to have a stab at a PR.

**Comment by honnibal** [comment]
@svlandeg Ah, good catch. Yeah I'll fix it, thanks!
