### ISSUE TITLE
dependency parsing error

### ISSUE THREAD

**Issue by xiaozw123** [explosion/spaCy#4567]
Training data 
1	我们	我们	PN	PN	_	7	Agt	_	_
2	应	应	VV	VV	_	7	mMod	_	_
3	把	把	BA	BA	_	6	mPrep	_	_
4	产品	产品	NN	NN	_	6	Host	_	_
5	的	的	DEG	DEG	_	4	mAux	_	_
6	质量	质量	NN	NN	_	7	Pat	_	_
7	放	放	VV	VV	_	0	Root	_	_
8	在	在	P	P	_	10	mPrep	_	_
9	第一	第一	OD	OD	_	10	Seq	_	_
10	位	位	M	M	_	7	Loc	_	_
11	，	，	PU	PU	_	7	mPunc	_	_
12	产品	产品	NN	NN	_	14	Host	_	_
13	与其	与其	DEG	DEG	_	15	mConj	_	_
14	数量	数量	NN	NN	_	15	Exp	_	_
15	多	多	VA	VA	_	7	eAban	_	_
16	而	而	CC	CC	_	18	mConj	_	_
17	质量	质量	NN	NN	_	18	Exp	_	_
18	差	差	NN	NN	_	15	eCoo	_	_
19	，	，	PU	PU	_	18	mPunc	_	_
20	不如	不如	VV	VV	_	22	mConj	_	_
21	数量	数量	NN	NN	_	22	Exp	_	_
22	少	少	VA	VA	_	15	ePref	_	_
23	而	而	MSP	MSP	_	25	mConj	_	_
24	质量	质量	AD	AD	_	25	Exp	_	_
25	好	好	VA	VA	_	22	eCoo	_	_
26	。	。	PU	PU	_	25	mPunc	_	_

ValueError: [E020] Could not find a gold-standard action to supervise the dependency parser. The tree is non-projective (i.e. it has crossing arcs - see spacy/syntax/nonproj.pyx for definitions). The ArcEager transition system only supports projective trees. To learn non-projective representations, transform the data before training and after parsing. Either pass `make_projective=True` to the GoldParse class, or use spacy.syntax.nonproj.preprocess_training_data.

**Comment by adrianeboyd** [comment]
Hi, this error is basically telling you what's going on: your training sentence is not projective, so you can't use it to train the parser directly. spacy's approach when training with nonprojective sentences is to temporarily make sentences projective, train/parse, and then convert the temporary dependencies back to a nonprojective version for output/evaluation.

I'm not sure how you're loading your training data, but if you have the CoNLL-U format (which is what this looks like), you can convert your data with `spacy convert file.conllu output_dir` to spacy's internal JSON format. Then you can use `spacy train` to train models, and it handles the conversion of nonprojective trees to projective trees during training.

You can see details about the number of nonprojective sentences with `spacy debug-data zh train.json dev.json`.

Also, if you load your spacy JSON corpus with `GoldCorpus` you can access the projectivized training examples with `GoldCorpus.train_docs()`.
