### ISSUE TITLE
spacy.gold.align function misses some mappings

### ISSUE THREAD

**Issue by filipdbrsk** [explosion/spaCy#4569]
The aligning function seems to work good in most cases, but for some reason, it fails in the case below. Namely, it is unable to map the first two SpaCy tokens to the initial 6 BERT tokens.

## How to reproduce the behaviour

```
    bert_tokens=['[CLS]', 'Sy', '##mpi', '##esis', 'kara', '##gios', '##is', 'is', 'een', 'vliesvleugelig', 'insect', 'uit', 'de', 'familie', 'Eulophidae', '.', '[SEP]']
    our_tokens=['Sympiesis', 'karagiosis', 'is', 'een', 'vliesvleugelig', 'insect', 'uit', 'de', 'familie', 'Eulophidae', '.']
```

## Your Environment

* Operating System: Ubuntu 18.04
* Python Version Used: 3.7
* spaCy Version Used: 2.1.4

**Comment by adrianeboyd** [comment]
The `spacy.gold.align()` function is intended to align raw texts with a sequence of tokens where the tokens are identical or nearly identical to the raw text other than whitespace and things like ASCII vs. unicode quotes. It is a little buggy (see #4554) and we're working on updating it. This is definitely a bug and it's a good test case to add, thanks!

If you strip the special tokens and characters, you could try the newer, simpler align function in v2.2.2 that only handles cases where the character strings are identical other than whitespace:

```
# set this flag to switch to the newer function
spacy.gold.USE_NEW_ALIGN = True
cleaned_bert_tokens = ['', 'Sy', 'mpi', 'esis', 'kara', 'gios', 'is', 'is', 'een', 'vliesvleugelig', 'insect', 'uit', 'de', 'familie', 'Eulophidae', '.', '']
cost, i2j, j2i, i2j_multi, j2i_multi = spacy.gold.align(cleaned_bert_tokens, our_tokens)
assert list(i2j) == [-1, -1, -1, -1, -1, -1, -1,  2,  3,  4,  5,  6,  7,  8,  9, 10, -1]
assert i2j_multi == {1: 0, 2: 0, 3: 0, 4: 1, 5: 1, 6: 1}
```

This is just for testing right now and we're not making any promises about how this will work in future versions of spacy. Spacy isn't intending to provide a general-purpose alignment tool with this functionality, so in general I'd recommend using another library that's focused on string alignment.

**Comment by filipdbrsk** [comment]
Thanks! Indeed, this specific example seems to work in v2.2.2. 
And I understand that it is not spacy's intent to provide an alignment tool.

In case you have any such library for string alignment in mind, please share.

And, feel free to close the issue.

**Comment by adrianeboyd** [comment]
I'm afraid I'm not familiar enough with python string alignment libraries to make any recommendations. 

I'm a little confused about why you're doing string alignment at all in this case when it's easy to use the special characters/tokens to do the alignment, but maybe this is just an example? In any case, spacy is not the right tool for this.
