### ISSUE TITLE
Approximate Nearest Neighbors for Aliases in KB for Entity Linking

### ISSUE THREAD

**Issue by kabirkhan** [explosion/spaCy#4572]
## Feature description

Currently, the EntityLinker is looking for exact match aliases. While this might be ideal for some entity types and even for the WikiData KB in general, there are some obvious cases where this won't work well. 

Specifically for custom knowledge bases, I think it makes sense to compute an Approximate Nearest Neighbors index for all aliases in a knowledge base using character ngrams and tfidf.

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
If so, we will tag it as [`project idea`](https://github.com/explosion/spaCy/labels/project%20idea) so other users can take it on.

This could be a custom pipeline component but I think it makes more sense to have this functionality present in the EntityLinker. Open to discussion on this though.

**Comment by svlandeg** [comment]
I know what you mean. For Wikipedia/Wikidata you already get a lot of synonyms and spelling variants in the KB, but for custom KB's you may require some sort of more fuzzy matching. There's an obvious precision/recall/speed trade-off to consider here ofcourse. 

This functionality is the responsibility of the [`get_candidates()`](https://github.com/explosion/spaCy/blob/87fcf3141c16535b3a58edc11f799589e97fa6f1/spacy/kb.pyx#L192) method of the KB. I think it should be possible to extend the current KB class to plug in this kind of functionality for your custom use-case.

**Comment by kabirkhan** [comment]
You know what, the more I think about this the more it makes sense to add a custom component. Any efficient implementation would require another dependency (like https://github.com/nmslib/nmslib) and since the kb doesn't actually store alias strings the custom pipe probably couldn't even use the kb. 

I'll work on this separately and maybe contribute a package to universe

**Comment by svlandeg** [comment]
Great! In case that wasn't clear - I just want to point out that the KB does store *hashes* of alias strings, which can be converted to actual strings through the `vocab` with `kb.vocab.strings[alias_hash]`

**Comment by kabirkhan** [comment]
Reopening to track this. I do think there's one required spaCy change to make this functionality work.
Could we possibly make the get_candidates function a registered function with catalogue with the default being what that function does now? Not sure if that would work with the kb being cython. 

But my idea is a user could plug in any get_candidates function that returns List[Candidate].

Otherwise it'd be impossible to integrate the this ANN index with the current EntityLinker setup.

**Comment by svlandeg** [comment]
Merging with Issue #4981 and the related PR #4988 to keep the discussion in one place
