### ISSUE TITLE
Matcher breaks with "complex" patterns ppc64le

### ISSUE THREAD

**Issue by rjknight** [explosion/spaCy#4576]
Hello, I am seeing failures in the matcher unit tests, when complex patterns are involved.

It seems very similar to this older issue `Matcher breaks with "complex" patterns #3328`

## How to reproduce the behavior
run the following sample code from issue 3328:
```
import spacy
from spacy.tokens import Token, Doc, Span
from spacy.matcher import Matcher, PhraseMatcher

text = "Hello, how are you doing?"

nlp = spacy.load('en_core_web_md')

matcher = Matcher(nlp.vocab)
patterns = [
    [{'LOWER': {'IN': ["hello", "how"]}}],
    [{'LOWER': {'IN': ["you", "doing"]}}],
]

matcher.add('TEST', None, *patterns)

doc = nlp(text)

matches = matcher(doc)
for match_id, start, end in matches:
    span = Span(doc, start, end, label=match_id)
    print(span.text)
```
## Exected results
running in an x86 container I see the following
```
(wmlce) pwrai@8d94e9e4cbc2:~$ python ./testme.py 
Hello
how
you
doing
(wmlce) pwrai@8d94e9e4cbc2:~$ python -m spacy info --markdown

## Info about spaCy

* **spaCy version:** 2.2.1
* **Platform:** Linux-3.10.0-957.5.1.el7.x86_64-x86_64-with-debian-buster-sid
* **Python version:** 3.7.3
```

## Actual results
when running the same sample code in a ppc64le container I see the following:
```
(wmlce) pwrai@ed647b42dde1:~$ python testme.py 
Hello
,
how
are
you
doing
?
(wmlce) pwrai@ed647b42dde1:~$ python -m spacy info --markdown

## Info about spaCy

* **spaCy version:** 2.2.1
* **Platform:** Linux-4.14.0-115.10.1.el7a.ppc64le-ppc64le-with-debian-buster-sid
* **Python version:** 3.7.4
* **Models:** en


```

**Comment by adrianeboyd** [comment]
Thanks for the report! I'm curious about what might be going on, but I'm not sure we have the resources to debug this right now. It does sound like a bug, so I'll add that label so we'll know to come back to it in the future.

**Comment by Xiaoming-Zhao** [comment]
@rjknight Hi, May I know what channel you used to install the `spacy` package? I have searched several channels but could not find the `spacy >= 2.1.0`. Thanks a lot!

**Comment by rjknight** [comment]
> @rjknight Hi, May I know what channel you used to install the `spacy` package for `ppc64le`? I have searched several channels but could not find the `spacy >= 2.1.0`. Thanks a lot!

@Xiaoming-Zhao from here https://anaconda.org/powerai/repo

**Comment by svlandeg** [comment]
If anyone working on this architecture feels like testing & debugging this issue, all help is welcome!

**Comment by adrianeboyd** [comment]
I can confirm that I see the same type of test failure when attempting to build spacy v2.3.2 for ppc64le on conda-forge.
