### ISSUE TITLE
JSON files on MongoDB connection to SpaCy ?

### ISSUE THREAD

**Issue by Mustyy** [explosion/spaCy#458]
Hi,
Firstly, this is a fantastic platform and I'm slowly testing it out
I have a bunch of data scraped from financial news sites stored in a MongoDB database.
Any idea as to how I can load it into SpaCy or if there is a way to connect SpaCy directly to the database so it reads every page.
Thanks!!

**Comment by viksit** [comment]
spacy purely handles NLP tasks - if you want to analyze a stream of data from a source, see this tutorial here https://spacy.io/docs/tutorials/twitter-filter

The ```Connection``` class can simply be your MongoDB connection rather than Twitter.

**Comment by Mustyy** [comment]
Thank you for the quick reply
I have one more question for now. In terms of analyzing tweets. For example if I want to analyze the term "Mutual Fund" together is this possible with SpaCy? 
I can get the twitter count for each of the terms seperately but together I keep getting a term count of 0. Any ideas?
