### ISSUE TITLE
TypeError: beam_parse() takes at least 2 positional arguments

### ISSUE THREAD

**Issue by Julius-ZCJ** [explosion/spaCy#4588]
Spacy==2.2.2
My code is that:

import spacy
nlp = spacy.load('en_core_web_sm', disable=['tagger', 'parser'])
utterance = "Apple is looking at buying U.K. startup for $1 billion"
doc = nlp(utterance)
print(doc.ents)
for ent in doc.ents:
    print(ent.text, ent.start_char, ent.end_char, ent.label_)
with nlp.disable_pipes('ner'):
    _doc_entity_scores = nlp(utterance)
print(_doc_entity_scores)
(beams, _) = nlp.entity.beam_parse([_doc_entity_scores])
print(beams)

When I run I get error:  TypeError: beam_parse() takes at least 2 positional arguments (1 given)
And I go to Spacy official website to find document, but I'm failed, Where I can find document about function "entity.beam_parse" info?

**Comment by adrianeboyd** [comment]
`beam_parse()` requires the `beam_width` as the second argument, so something like:

```
beams = nlp.entity.beam_parse([_doc_entity_scores], 16)
```

The sample script in #4432 works, if that is helpful. Note that the same issue shows a memory leak related to `beam_parse()` that hasn't been fixed yet, so don't use this in long-running processes.

**Comment by Julius-ZCJ** [comment]
@adrianeboyd  Thank you, It's work, And I also want to know where can I find the spacy documents, I have some functions don't know their function, Can you tell me the url or link.

**Comment by adrianeboyd** [comment]
These functions are mainly meant for internal use and I'm afraid there's no official documentation at this point. Matt's examples on the prodigy support forum are the main explanations that I'm aware of.

**Comment by Julius-ZCJ** [comment]
Alright, Thank you
