### ISSUE TITLE
pip install -U spacy fails

### ISSUE THREAD

**Issue by arencambre** [explosion/spaCy#4591]
## How to reproduce the problem
On a computer with vanilla Windows 10 Professional 
1. Download and install the **Windows x86-64 executable installer** from [https://www.python.org/downloads/release/python-380/](https://www.python.org/downloads/release/python-380/).
1. In a command prompt window, run `pip install -U spacy`.

Instead of a successful install, I get a litany of errors: [errors.txt](https://github.com/explosion/spaCy/files/3809800/errors.txt)

## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.8.0
* spaCy Version Used: Whatever downloads on Nov. 5, 2019 with `pip install -U spacy`
* Environment Information: N/A

**Comment by ines** [comment]
Hi! See my comment on #4581:

> I think the main thing that's causing problems here is that you're using Python 3.8. We can't yet ship pre-compiled wheels for Python 3.8 (unfortunately it's not fully supported by any CI providers we use at the moment), so if you want to install spaCy on 3.8, you have to build everything from source. And that seems to fail, likely due to how your compiler is configured, which is not correct for compiling `blis`.
>
> Simplest solution: use Python 3.7 for now.

**Comment by arencambre** [comment]
Thank you. Asked for documentation to be improved at #4593.
