### ISSUE TITLE
Python version compatibility list is wrong

### ISSUE THREAD

**Issue by arencambre** [explosion/spaCy#4593]
The instructions at [https://spacy.io/usage](https://spacy.io/usage) suggests they work with Python 3.8: at the top, it says spaCy is compatible with "64-bit CPython 2.7 / 3.5+". That invites users to just jump in.

That needs to be clarified. Per #4581, Python 3.8 requires you to compile spaCy. Therefore, the instructions should state that you can't simply jump in at the top if you have Python 3.8. Otherwise, users will get errors that are hard to decipher.

**Comment by ines** [comment]
I'll add a warning infobox to the top of the page that explains this and recommends using Python 3.7 was the quickest solution. (spaCy itself and its dependencies are all compatible with 3.8 – the only difference is that we currently cannot ship pre-compiled binary wheels for our packages.)
