### ISSUE TITLE
blacklist word/token from a specific label

### ISSUE THREAD

**Issue by Khanifsaleh** [explosion/spaCy#4602]
Is there a way in ner spacy feature to blacklist tokens/words so that they are not specific label?

**Comment by adrianeboyd** [comment]
No, there's no built-in way to do this. One simple option is to post-process the entity labels to remove ones that you don't want.

If there's a span that you don't want to be an entity at all and you want this information to inform your NER model, you could also pre-process your text to add a custom entity span with a label like `IGNORE`, which you then remove in post-processing. The NER model recognizes existing labels in your `Doc` and will only add labels to spans that aren't already part of an entity, so the presence of some entities can affect the NER model's predictions nearby.
