### ISSUE TITLE
Matcher is returning some duplicates entry

### ISSUE THREAD

**Issue by gargpuja** [explosion/spaCy#4627]
I want output as ["good customer service","great ambience"] but I am getting ["good customer","good customer service","great ambience"] because pattern is matching with "good customer" also but this phrase doesn't make any sense. How can I remove these kind of duplicates

```
import spacy
from spacy.matcher import Matcher
nlp = spacy.load("en_core_web_sm")
doc = nlp("good customer service and great ambience")
matcher = Matcher(nlp.vocab)

# Create a pattern matching two tokens: adjective followed by one or more noun
 pattern = [{"POS": 'ADJ'},{"POS": 'NOUN', "OP": '+'}]

matcher.add("ADJ_NOUN_PATTERN", None,pattern)

matches = matcher(doc)
print("Matches:", [doc[start:end].text for match_id, start, end in matches])

```

## Your Environment

* Operating System: Mac OS
* Python Version Used:  3.7.3  
* spaCy Version Used: 2.1.8

**Comment by adrianeboyd** [comment]
Hi, this question is better suited for StackOverflow than the issue tracker, thanks!

For reference: https://stackoverflow.com/q/58815066/461847

**Comment by gargpuja** [comment]
I feel Like its a bug

**Comment by adrianeboyd** [comment]
`"OP": '+'` can match one or more tokens and the `Matcher` returns all possible matches, not just the longest match, so this is the intended behavior and not a bug.
