### ISSUE TITLE
can't load "en_cor_web_lg"

### ISSUE THREAD

**Issue by haleha** [explosion/spaCy#4631]
I am trying to download en_core_web_lg  using "python -m spacy download en_core_web_lg" . I keep getting bad handchake erro. Here is the complete error: 

 raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/shortcuts-v2.json (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

**Comment by adrianeboyd** [comment]
Can you try downloading the model and installing it directly with `pip` instead? Here is the link to the most recent version of `en_core_web_lg`:  https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-2.2.0/en_core_web_lg-2.2.0.tar.gz

Other models are available as releases in the `spacy-models` repository: https://github.com/explosion/spacy-models/releases/

**Comment by haleha** [comment]
I tried downloading it, but after linking it, I still had problem importing in python
