### ISSUE TITLE
ValueError: spacy.syntax.nn_parser.Parser size changed, may indicate binary incompatibility. Expected 72 from C header, got 64 from PyObject

### ISSUE THREAD

**Issue by chrisnweb** [explosion/spaCy#4635]
* Environment Information:  Jupyter Notebooks
When do the following:
import spacy
nlp = spacy.load('en_core_web_lg')

I received error as shown below

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-58-f9ea1b8cc5d1> in <module>()
      1 import spacy
----> 2 nlp = spacy.load('en_core_web_lg')

~\Anaconda3\lib\site-packages\spacy\__init__.py in load(name, **overrides)
     13     if depr_path not in (True, False, None):
     14         deprecation_warning(Warnings.W001.format(path=depr_path))
---> 15     return util.load_model(name, **overrides)
     16 
     17 

~\Anaconda3\lib\site-packages\spacy\util.py in load_model(name, **overrides)
    112             return load_model_from_link(name, **overrides)
    113         if is_package(name):  # installed as package
--> 114             return load_model_from_package(name, **overrides)
    115         if Path(name).exists():  # path to model data directory
    116             return load_model_from_path(Path(name), **overrides)

~\Anaconda3\lib\site-packages\spacy\util.py in load_model_from_package(name, **overrides)
    133     """Load a model from an installed package."""
    134     cls = importlib.import_module(name)
--> 135     return cls.load(**overrides)
    136 
    137 

~\Anaconda3\lib\site-packages\en_core_web_lg\__init__.py in load(**overrides)
     10 
     11 def load(**overrides):
---> 12     return load_model_from_init_py(__file__, **overrides)

~\Anaconda3\lib\site-packages\spacy\util.py in load_model_from_init_py(init_file, **overrides)
    171     if not model_path.exists():
    172         raise IOError(Errors.E052.format(path=path2str(data_path)))
--> 173     return load_model_from_path(data_path, meta, **overrides)
    174 
    175 

~\Anaconda3\lib\site-packages\spacy\util.py in load_model_from_path(model_path, meta, **overrides)
    141     if not meta:
    142         meta = get_model_meta(model_path)
--> 143     cls = get_lang_class(meta['lang'])
    144     nlp = cls(meta=meta, **overrides)
    145     pipeline = meta.get('pipeline', [])

~\Anaconda3\lib\site-packages\spacy\util.py in get_lang_class(lang)
     48     if lang not in LANGUAGES:
     49         try:
---> 50             module = importlib.import_module('.lang.%s' % lang, 'spacy')
     51         except ImportError:
     52             raise ImportError(Errors.E048.format(lang=lang))

~\Anaconda3\lib\importlib\__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

~\Anaconda3\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

~\Anaconda3\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

~\Anaconda3\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

~\Anaconda3\lib\importlib\_bootstrap.py in _load_unlocked(spec)

~\Anaconda3\lib\importlib\_bootstrap_external.py in exec_module(self, module)

~\Anaconda3\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

~\Anaconda3\lib\site-packages\spacy\lang\en\__init__.py in <module>()
     13 from ..tokenizer_exceptions import BASE_EXCEPTIONS
     14 from ..norm_exceptions import BASE_NORMS
---> 15 from ...language import Language
     16 from ...attrs import LANG, NORM
     17 from ...util import update_exc, add_lookups

~\Anaconda3\lib\site-packages\spacy\language.py in <module>()
     16 from .vocab import Vocab
     17 from .lemmatizer import Lemmatizer
---> 18 from .pipeline import DependencyParser, Tensorizer, Tagger, EntityRecognizer
     19 from .pipeline import SimilarityHook, TextCategorizer, SentenceSegmenter
     20 from .pipeline import merge_noun_chunks, merge_entities

~\Anaconda3\lib\site-packages\spacy\pipeline\__init__.py in <module>()
      2 from __future__ import unicode_literals
      3 
----> 4 from .pipes import Tagger, DependencyParser, EntityRecognizer, EntityLinker
      5 from .pipes import TextCategorizer, Tensorizer, Pipe, Sentencizer
      6 from .morphologizer import Morphologizer

pipes.pyx in init spacy.pipeline.pipes()

**Comment by adrianeboyd** [comment]
Hi, this can happen if there are some conflicting dependencies or outdated files in your installation. Can you try installing spacy in a new virtual environment?

Duplicate issue: #3776.

**Comment by chrisnweb** [comment]
I have not try installing it in a new virtual environment. Please kindly advice with instruction how to do it.

**Comment by chrisnweb** [comment]
Another questions: 
1. Do you recommend uninstall spacy and then reinstall it again?
2. Do you think spacy is conflicting because I also download 'en_core_web_sm' and download 'en_core_web_md'?
3. I have python3.6.5, should I update to 3.7? Will this helps solving the problem?

**Comment by adrianeboyd** [comment]
Uninstalling and reinstalling spacy may help, but our best advice here is to try installing spacy in a new virtual environment.

The two English models shouldn't cause any conflicts with each other and python3.6 vs python3.7 shouldn't make a difference.

**Comment by chrisnweb** [comment]
So option 1: How do you do uninstall spacy?
option 2: Do I need to uninstall spacy first before installing it in a new virtual environment. Also, please kindly provide instructions how to do this option.

**Comment by chrisnweb** [comment]
reference to option 1: How do you do uninstall spacy?
option 2: Do I need to uninstall spacy first before installing it in a new virtual environment. Also, please kindly provide instructions how to do this option.

**Comment by adrianeboyd** [comment]
These are very general python usage questions that are not specific to spacy and I'm afraid we don't have the resources to provide more general support. I can point you to the spacy installation instructions here: https://spacy.io/usage#installation. Otherwise other alternatives like online tutorials and StackOverflow are better place to look when you're just getting started.
