### ISSUE TITLE
Unable to find data used to trained Portuguese model

### ISSUE THREAD

**Issue by thak123** [explosion/spaCy#4644]
#1886 has the list of documents used to train the Pt ner model. I am not able to find the dataset.

## Info about spaCy

* **spaCy version:** 2.2.1
* **Platform:** Linux-4.4.0-18362-Microsoft-x86_64-with-debian-stretch-sid
* **Python version:** 3.7.3

**Comment by adrianeboyd** [comment]
The current Portuguese model is trained with an older version (v1.3, I think) of UD_Portuguese-Bosque. Check out the model docs, too: https://spacy.io/models/pt

**Comment by thak123** [comment]
which column or features were used for training the model ? I am unable to find Per,Org etc neither B-I-O type tags

**Comment by adrianeboyd** [comment]
Sorry, I missed that you were looking for the NER data. It uses WikiNER, there's a link in the model docs page mentioned above.
