### ISSUE TITLE
Is possible to run spacy model in Ray?

### ISSUE THREAD

**Issue by swicaksono** [explosion/spaCy#4652]
I'm trying to load spaCy model in ray.remote, but when I'm trying to get the results, it's getting an error in the serialization problem. Is it possible to load the model and run it in distributed clusters?

Thank you.

**Comment by honnibal** [comment]
You should be able to load spaCy within a Ray actor, and then pass the texts into it. The best way to pass the results out is the `DocBin` class: https://spacy.io/usage/saving-loading#docs

If you already have a Ray cluster set up, this might be a good strategy. But in general for large-scale parsing, I usually go for a disk-to-disk strategy: you partition up all your text into chunks, and then have a script that reads in a chunk, works, and writes the result to disk. The parallelisation then consists of running your script with different arguments on different machines.
