### ISSUE TITLE
model saving and loading difference

### ISSUE THREAD

**Issue by chunlei2** [explosion/spaCy#4659]
# How to reproduce the behaviour

#4649 Hi, this is a follow up with the problem since it is closed. I don't mean to create a representative model, just want to figure out why the saved model is different from the model before saved. I upgrade the spacy to 2.2.2 and still have the issue. I reproduce the error using Google Colab. [link](https://colab.research.google.com/drive/1vOsDU_7NZ1FCLy3E22eU-Y9qIF4IB3uw)

## Your Environment

* Operating System: Google Colab
* Python Version Used: 3.6
* spaCy Version Used: 2.2.2
* Environment Information:

**Comment by adrianeboyd** [comment]
I'll close this and reopen the original issue, since this is weird.
