### ISSUE TITLE
Loading the same model repeatedly gradually consumes more memory

### ISSUE THREAD

**Issue by mabraham** [explosion/spaCy#4668]
When loading the same model in spaCy many times, it allocates a small amount of new memory when a model is loaded. That memory cannot be cleaned up with python gc. This behaviour does not suit use in a long-lived server where the model is a parameter derived from the user, because eventually the server process will run out of memory. The repro script below continues to allocate new memory even with the iteration count increased to at least 200. Apparently the core data persists in CPython memory space and can be re-used, but each new model loaded also allocates additional memory, and this is problematic.

Possible solutions
* run spaCy in its own process/container and accept the overhead of process creation, model load, and communication
* change Language.load() to allocate data that is unique to the load() of that model in Python space, so that Python scoping means that gc will eventually clean it up after the reference goes out of scope
* change Language.load() to not allocate data that is unique to the load() of that model, so that repeated load() of the same model does not lead to growth in memory allocated
* add new method Language.unload() deallocates all memory in CPython for that model

Output of script below:

<details>
<pre>
INFO:root:Loaded en iteration 0
INFO:root:Current peak memory 178438144
INFO:root:Ran gc, found 0 unreachable objects
INFO:root:Current peak memory 178438144
INFO:root:Loaded en iteration 1
INFO:root:Current peak memory 294264832
INFO:root:Ran gc, found 0 unreachable objects
INFO:root:Current peak memory 294264832
INFO:root:Loaded en iteration 2
INFO:root:Current peak memory 301137920
INFO:root:Ran gc, found 0 unreachable objects
INFO:root:Current peak memory 301137920
INFO:root:Loaded en iteration 3
INFO:root:Current peak memory 310259712
INFO:root:Ran gc, found 0 unreachable objects
INFO:root:Current peak memory 310259712
INFO:root:Loaded en iteration 4
INFO:root:Current peak memory 310374400
INFO:root:Ran gc, found 0 unreachable objects
INFO:root:Current peak memory 310374400
INFO:root:Loaded en iteration 5
INFO:root:Current peak memory 310829056
INFO:root:Ran gc, found 0 unreachable objects
INFO:root:Current peak memory 310829056
INFO:root:Loaded en iteration 6
INFO:root:Current peak memory 311013376
INFO:root:Ran gc, found 0 unreachable objects
INFO:root:Current peak memory 311013376
INFO:root:Loaded en iteration 7
INFO:root:Current peak memory 311492608
INFO:root:Ran gc, found 0 unreachable objects
INFO:root:Current peak memory 311492608
INFO:root:Loaded en iteration 8
INFO:root:Current peak memory 311492608
INFO:root:Ran gc, found 0 unreachable objects
INFO:root:Current peak memory 311492608
INFO:root:Loaded en iteration 9
INFO:root:Current peak memory 311492608
INFO:root:Ran gc, found 0 unreachable objects
INFO:root:Current peak memory 311492608
INFO:root:Ran gc, found 0 unreachable objects
INFO:root:Current peak memory 311492608
</pre>
</details>

## How to reproduce the behaviour

Script
<details>

    import gc, logging, resource, spacy, sys

    logging.basicConfig(stream=sys.stdout, level=logging.INFO)

    def log_peak_memory():
        peak_memory = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        logging.info(f"Current peak memory {peak_memory}")

    def run_gc():
        unreachable = gc.collect()
        logging.info(f"Ran gc, found {unreachable} unreachable objects")
        log_peak_memory()

    for i in range(20):
        logging.info(f"Loaded en iteration {i}")
        nlp = spacy.load("en_core_web_sm")
        log_peak_memory()
        run_gc()

    run_gc()

</details>

## Your Environment

* **spaCy version:** 2.2.2
* **Platform:** Darwin-19.0.0-x86_64-i386-64bit
* **Python version:** 3.7.5

**Comment by adrianeboyd** [comment]
I think that this is more of a python issue than a spacy issue, although it's definitely annoying and frustrating. I double-checked with valgrind to see if loading a model repeatedly leads to a memory leak that spacy might be directly responsible for and I didn't find anything.

I think that using child processes is probably going to be the most straight-forward way to handle this.

> Possible solutions
>
>   * run spaCy in its own process/container and accept the overhead of process creation, model load, and communication
> 
>   * change Language.load() to allocate data that is unique to the load() of that model in Python space, so that Python scoping means that gc will eventually clean it up after the reference goes out of scope
> 
>   * change Language.load() to not allocate data that is unique to the load() of that model, so that repeated load() of the same model does not lead to growth in memory allocated
> 
>   * add new method Language.unload() deallocates all memory in CPython for that model

I'm not sure this last option is (easily) possible, but if you know more about the details, I'd be interested to learn how it could be implemented!

**Comment by mabraham** [comment]
> I think that this is more of a python issue than a spacy issue, although it's definitely annoying and frustrating. I double-checked with valgrind to see if loading a model repeatedly leads to a memory leak that spacy might be directly responsible for and I didn't find anything.

That's frustratingly inconsistent :-) Thanks for the double check.

> I think that using child processes is probably going to be the most straight-forward way to handle this.

Sure, but also the least performant (where that matters)

> > Possible solutions
> > 
> > * run spaCy in its own process/container and accept the overhead of process creation, model load, and communication
> > * change Language.load() to allocate data that is unique to the load() of that model in Python space, so that Python scoping means that gc will eventually clean it up after the reference goes out of scope
> > * change Language.load() to not allocate data that is unique to the load() of that model, so that repeated load() of the same model does not lead to growth in memory allocated
> > * add new method Language.unload() deallocates all memory in CPython for that model
> 
> I'm not sure this last option is (easily) possible, but if you know more about the details, I'd be interested to learn how it could be implemented!

Sorry, pure speculation on my part that there is some kind of handle returned when building a CPython data structure. If so, that handle should be useful for deallocation, e.g. by holding it in a python object that is eventually gc-ed.

**Comment by adrianeboyd** [comment]
> > I think that this is more of a python issue than a spacy issue, although it's definitely annoying and frustrating. I double-checked with valgrind to see if loading a model repeatedly leads to a memory leak that spacy might be directly responsible for and I didn't find anything.
> 
> That's frustratingly inconsistent :-) Thanks for the double check.

It's not inconsistent exactly, it's more that spacy doesn't control how python manages memory for objects like `nlp`.
 
> > I think that using child processes is probably going to be the most straight-forward way to handle this.
> 
> Sure, but also the least performant (where that matters)

I think that loading a model each time is the really expensive part here, though? (I'm not sure there's a better solution given #4349, though.)

> > > * add new method Language.unload() deallocates all memory in CPython for that model
> > 
> > 
> > I'm not sure this last option is (easily) possible, but if you know more about the details, I'd be interested to learn how it could be implemented!
> 
> Sorry, pure speculation on my part that there is some kind of handle returned when building a CPython data structure. If so, that handle should be useful for deallocation, e.g. by holding it in a python object that is eventually gc-ed.

No, as far as I know there's not an easy way to do this.
