### ISSUE TITLE
adding new lang to spacy-lookups-data

### ISSUE THREAD

**Issue by ramilrg** [explosion/spaCy#4669]
## How to reproduce the behaviour

Hi,
I want to add a new language to "spacy-lookups-data", I already made a necessary changes on setup.cfg, setup.py and __init__.py files, and a new generated az_lemma_lookup.json is also exists, but when I try to test it got an error:

####################
```
az_nlp = <spacy.lang.az.Azeri object at 0x000002A0078E92E8>
string = 'çatmaqdakındansınız', lemma = 'çatmaq'

    @pytest.mark.parametrize(
        "string,lemma",
        [
            ("şikəncələrdəkinin", "şikəncə"),
            ("gözaydınlığındakılardanmış", "gözaydınlığı"),
            ("çatmaqdakındansınız", "çatmaq"),
        ],
    )
    def test_az_lemmatizer_lookup_assigns(az_nlp, string, lemma):
        tokens = az_nlp(string)
>       assert tokens[0].lemma_ == lemma
E       AssertionError: assert 'çatmaqdakındansınız' == 'çatmaq'
E         - çatmaqdakındansınız
E         + çatmaq

spacy_lookups_data\tests\test_az.py:23: AssertionError
```
####################

## Your Environment

* Operating System: Win10
* Python Version Used: 3.6
* spaCy Version Used: 2.2
* Environment Information:

**Comment by adrianeboyd** [comment]
Hmm, it looks like it's not lemmatizing, but it's hard to tell what might be going on without seeing your changes. Do you have a github branch that shows what you've been working on?

If you can't share your full lemma table for licensing reasons, you could make a demo table with a few entries for the words that you are testing here and it should be enough to show us what might be going on.

**Comment by ramilrg** [comment]
here is a simplified branch:
[https://github.com/ramilrg/spacy-lookups-data](url)

**Comment by adrianeboyd** [comment]
Thanks! Can you also include `spacy/lang/az/__init__.py` here?

**Comment by ramilrg** [comment]
file `spacy/lang/az/__init__.py:`

```
# coding: utf8
from __future__ import unicode_literals

from .tokenizer_exceptions import TOKENIZER_EXCEPTIONS
from .stop_words import STOP_WORDS
from .lex_attrs import LEX_ATTRS
from .tag_map import TAG_MAP

from ..tokenizer_exceptions import BASE_EXCEPTIONS
from ..norm_exceptions import BASE_NORMS
from ...util import update_exc, add_lookups
from ...language import Language
from ...lookups import Lookups
from ...attrs import LANG, NORM

class AzeriDefaults(Language.Defaults):
    lex_attr_getters = dict(Language.Defaults.lex_attr_getters)
    lex_attr_getters[LANG] = lambda text: "az"
    lex_attr_getters[NORM] = add_lookups(
        Language.Defaults.lex_attr_getters[NORM], BASE_NORMS
    )
    tokenizer_exceptions = update_exc(BASE_EXCEPTIONS, TOKENIZER_EXCEPTIONS)
    stop_words = STOP_WORDS
    tag_map = TAG_MAP

class Azeri(Language):
    lang = "az"
    Defaults = AzeriDefaults

# Set default export – this allows the language class to be lazy-loaded
__all__ = ["Azeri"]
```

**Comment by ines** [comment]
Did you install your customised `spacy-lookups-data` package in your environment, e.g. in edit mode (`pip install -e .`)? The lemma tables are advertised via entry points, and those will only be available to spaCy if the package is actually installed in the environment.

**Comment by ramilrg** [comment]
just added a new language info to "entry_points.txt" file, and it works
