### ISSUE TITLE
Empty AssertionError:  for KnowledgeBase.dump

### ISSUE THREAD

**Issue by kabirkhan** [explosion/spaCy#4674]
## How to reproduce the behaviour

I'm creating a component for candidate generation using nearest neighbors and am trying to use the spacy KnowledgeBase. 

I'm running into this error in boty spacy 2.1.9 and spacy 2.2.2 where I get an empty AssertionError:
when trying to dump the KnowledgeBase like below.

```python
def to_disk(self, path, exclude=tuple(), **kwargs):
        """Save data to disk"""
        path = ensure_path(path)
        serialize = {}
        serialize["cfg"] = lambda p: srsly.write_json(p, {"k_neighbors": self.k})
        serialize["kb"] = lambda p: self.kb.dump(p)
        exclude = util.get_serialization_exclude(serialize, exclude, kwargs)
        util.to_disk(path, serialize, exclude)
        self.cg.to_disk(path)
```

Seems to be an issue actually writing the file using the cython c file I/O libraries.

In the file: `kb.pyx` in the Writer _write method. I guess the status is not 1.
```
cdef int _write(self, void* value, size_t size) except -1:
    status = fwrite(value, size, 1, self._fp)
    assert status == 1, status
```
## Your Environment

* Operating System: Tried on Ubuntu 18.04 in WSL and Ubuntu 16.04 in Azure Machine Learning
* Python Version Used: 3.6
* spaCy Version Used: Issue in 2.1.9 and 2.2.2
* Environment Information:

**Comment by kabirkhan** [comment]
@svlandeg 
Related to https://github.com/explosion/spaCy/issues/4572

**Comment by honnibal** [comment]
Hi @kabirkhan , Sofie's on holidays until early December, and she'll have a bit of catching up to do once she's back --- so unfortunately this will have to wait a little bit. If you have time to prepare a PR, that would definitely help.

**Comment by kabirkhan** [comment]
Not sure I'll have time to submit a fix for this any time soon but I found the issue if others run into this. 

If you use set_entities and add multiple entities with the same id the KnowledgeBase won't throw an error. Then if you try to dump the kb the file write operation fails with the empty assertion error.

**Comment by svlandeg** [comment]
Hi @kabirkhan , thanks for the report and sorry for the delay in answering this. I'll have a look into this.

If you could, it would be very helpful if you could create a minimal working code snippet that throws this error / shows the erratic behaviour, that'll help me solve this faster. Thanks again!

**Comment by svlandeg** [comment]
@kabirkhan : Ok I can reproduce the problem - you're right that this is triggered if you call `set_entities` with a duplicate unique identifier (which you shouldn't really do). I'll make sure the error/warning is more explicit and that the method recovers more gracefully.
