### ISSUE TITLE
SpaCy for JAVA language ??

### ISSUE THREAD

**Issue by himanshurobo** [explosion/spaCy#4682]
## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
If so, we will tag it as [`project idea`](https://github.com/explosion/spaCy/labels/project%20idea) so other users can take it on.

**Comment by adrianeboyd** [comment]
Hi, there are no plans for a Java version of spacy, sorry!
