### ISSUE TITLE
cannot import name 'prefer_gpu'

### ISSUE THREAD

**Issue by Julius-ZCJ** [explosion/spaCy#4693]
## How to reproduce the behaviour

I install spaCy with command: pip install spacy==2.0.18
when I import spacy I got this error:

  File "train.py", line 13, in <module>
    from training.nlu.ner import NerTrainer
  File "C:\Users\two\Project\mtwoai\training\nlu\ner.py", line 9, in <module>
    import spacy
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\spacy\__init__.py", line 8, in <module>
    from thinc.neural.util import prefer_gpu, require_gpu
ImportError: cannot import name 'prefer_gpu'

## Your Environment

* Operating System: win 10
* Python Version Used: python3.6.8
* spaCy Version Used: 2.0.18
* Environment Information:

**Comment by Julius-ZCJ** [comment]
Hi someone, I have refer to #2810, first I refresh thinc is not work, I got a new error, and I still reinstall cymem with conda, don't use pip, I find I can run spacy.

**Comment by adrianeboyd** [comment]
Yes, this was probably due to an old version of thinc. Glad you got it working!
