### ISSUE TITLE
SpaCy for Android/iOS ??

### ISSUE THREAD

**Issue by himanshurobo** [explosion/spaCy#4694]
## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
If so, we will tag it as [`project idea`](https://github.com/explosion/spaCy/labels/project%20idea) so other users can take it on.

**Comment by svlandeg** [comment]
I'll assume this question is related to #4682 ;-) 
As spaCy is written in Python, you'd have to find a way to run your Python code on a JVM. This is out of spaCy's scope, though.
