### ISSUE TITLE
Pipeline components with with > 2 mb file is slow on processing

### ISSUE THREAD

**Issue by absolution54321** [explosion/spaCy#4698]
I decided to create a pattern/regex based matching approach with Matcher embedded inside pipeline. For small file MAX_TOKEN < 10000 it performs great but texts with size > 2 mb takes time for processing.

I have tried to speed up processing by chunking text into smaller batch, i.e every batch contain maximum of 10000 tokens, text processing was faster but some of the matcher rules missed out matches because chunking process moved part entities to different batch.

Example: 
I want to match New York Boston

A text file of 2 mb
'text started here some blah blah ....... New York Boston .....'

for faster processing I am using nlp.pipe with batches of large file
above text becomes
texts = [ 'text started here some blah blah ....', '......... New York', 'Boston ..........']

nlp.pipe/ matcher.pipe(texts) this speeds up the process but 'New York Boston' is not to be found in matches because entity exists in two different batch.

I have disabled all memory consuming pipe components - NER, POS, DEPS

Currently, I have to trade off functionality for scaling. Do anyone have a suggestion, how to tackle large files? I want to use PhraseMatcher & Matcher.

## Your Environment

* Operating System: Linux-3.10.0-1062.1.1.el7.x86_64-x86_64-with-centos-7.7.1908-Core
* Python Version Used: 3.6.8
* spaCy Version Used: 2.1.8
* Environment Information: 16 GB, 8 Cores No GPU

**Comment by ines** [comment]
Could you share the code you're using in your component? And is it possible for you to just split up your input file and process it in smaller chunks? Processing 2mb at once is kinda inconvenient anyways and can easily lead to more problems down the line.

**Comment by adrianeboyd** [comment]
And two potential ways to split texts up:

* if you can, try to split your data at sensible points (paragraph boundaries, blank lines, headlines, whatever boundary wouldn't be within a match...)
* if you can't easily split your data at sensible points, create text chunks that overlap slightly (the overlap just needs to be longer than the longest possible match); requires a small amount of additional logic to filter duplicate matches and a small amount of additional processing due to processing all the overlapping tokens twice

If you're using PhraseMatcher with a large number of patterns (1000+ patterns), you should upgrade to the most recent version of v2.2 because the v2.1 version sometimes is buggy and misses matches with a lot of patterns.

**Comment by absolution54321** [comment]
> Could you share the code you're using in your component? And is it possible for you to just split up your input file and process it in smaller chunks? Processing 2mb at once is kinda inconvenient anyways and can easily lead to more problems down the line.

Sample code:
`   def __init__(self, nlp):

        self.vocab = nlp.vocab
        self.nlp = nlp
        self.matcher = PhraseMatcher(self.vocab, attr="LOWER")

    def __call__(self, doc):
        matches = self.matcher(doc)
        spans = []
        for match_id, start, end in matches:
            entity = Span(doc, start, end, label=self.vocab.strings[match_id])
            spans.append(entity)

        # doc._.ents is a custom container, I may receive overlapping ents
        doc._.ents = tuple(spans)
        return doc`

And yes I am splitting 2 mb file into multiple chunks, after that I am using nlp.pipe([chunks]) to make processing faster but phrasematcher misses out on most of the match

**Comment by absolution54321** [comment]
@adrianeboyd
> And two potential ways to split texts up:
> 
>     * if you can, try to split your data at sensible points (paragraph boundaries, blank lines, headlines, whatever boundary wouldn't be within a match...)
> 
>     * if you can't easily split your data at sensible points, create text chunks that overlap slightly (the overlap just needs to be longer than the longest possible match); requires a small amount of additional logic to filter duplicate matches and a small amount of additional processing due to processing all the overlapping tokens twice
> 
> 
> If you're using PhraseMatcher with a large number of patterns (1000+ patterns), you should upgrade to the most recent version of v2.2 because the v2.1 version sometimes is buggy and misses matches with a lot of patterns.

Thanks for the suggestion I will try separating files with overlapped batches.

@ines 

> Could you share the code you're using in your component? And is it possible for you to just split up your input file and process it in smaller chunks? Processing 2mb at once is kinda inconvenient anyways and can easily lead to more problems down the line.

yes I am splitting 2 mb file into multiple chunks, after that I am using nlp.pipe([chunks]) to make processing faster but phrasematcher misses out on most of the match

#Sample code:
`
def __init__(self, nlp):
      self.vocab = nlp.vocab
      self.nlp = nlp
      self.matcher = PhraseMatcher(self.vocab, attr="LOWER")

def __call__(self, doc):
      matches = self.matcher(doc)
      spans = []
      for match_id, start, end in matches:
           entity = Span(doc, start, end, label=self.vocab.strings[match_id])
           spans.append(entity)

      # doc._.ents is a custom container, I may receive overlapping ents
      doc._.ents = tuple(spans)
      return doc`

**Comment by adrianeboyd** [comment]
> > If you're using PhraseMatcher with a large number of patterns (1000+ patterns), you should upgrade to the most recent version of v2.2 because the v2.1 version sometimes is buggy and misses matches with a lot of patterns.
> 
> Thanks for the suggestion I will try separating files with overlapped batches.
> Is Token based Matcher also improved in v2.2?

PhraseMatcher in v2.2 is completely rewritten from v2.1, but Matcher is basically the same, just a small number of bugfixes.

**Comment by absolution54321** [comment]
achieved great accuracy with overlapping batches, but I compared phrasematcher with pattern search algorithm like ahocorasick it provided less processing time.
appreciate the help though.
