### ISSUE TITLE
Huge RAM consumption during NER training

### ISSUE THREAD

**Issue by mosynaq** [explosion/spaCy#4700]
I am trying to train a NER model from scratch. I have successfully built `train.json`, `dev.josn`, and `test.json`. I issue the below command to start training:
```python -m spacy train xx out train.json dev.json -p ner```
I have a PC with +60GB of RAM. spaCy occupies all but ~500MB. After some time and doing nothing, it stops and spits something like "not enough memory"!
I had this very problem with spaCy 2.2.2 too.
I use python v3.7.5, spaCy 2.2.3, and Windows 10

**Comment by honnibal** [comment]
You must have an instance that's really long. We should probably put the length cap back in, or possibly raise an error. What's the longest document in your data?

**Comment by mosynaq** [comment]
Thank you @honnibal! After I looked into the training data, I found multiple tool-long sentences. After they were split into smaller ones, the training works like a charm!
Thanks!
