### ISSUE TITLE
Why is the updated model faster than the original pretrained model?

### ISSUE THREAD

**Issue by Boreaso** [explosion/spaCy#4705]
I use the example code provided [here](https://github.com/explosion/spaCy/blob/master/examples/training/train_ner.py) to update the pretraind model [en_core_web_lg-2.2.5](https://github.com/explosion/spacy-models/releases//tag/en_core_web_lg-2.2.5) by my own dataset. I found that, the updated model is faster than the the origianal during inference stage(about 3 times faster). Is it due to the model architecture or some other settings has changed?
## Environment
* Operating System: Windows 10
* Python Version Used: 3.7
* spaCy Version Used: 2.2.3
* Environment Information:

**Comment by svlandeg** [comment]
Hm, that's a little weird, I can't immediately think of a reason why the model would speed up so much.

Could you provide some more information by looking at some stats of your two models?
- double check which pipeline components are in both models by printing `nlp.pipe_names` - perhaps a component got dropped by accident ?
- how big is the dataset you retrained with?
- which NER labels are being predicted by both models ?
- check the performance (accuracy) on a sample evaluation set for both models
