### ISSUE TITLE
Evaluate : which corpus format are supported for? 

### ISSUE THREAD

**Issue by phiedulxp** [explosion/spaCy#4706]
When I use ner_data.json[only entities annotation], corpus read nothing.
## Which page or section is this issue related to?

https://spacy.io/api/cli#evaluate

**Comment by adrianeboyd** [comment]
What does `spacy debug-data` show for the same data?

**Comment by phiedulxp** [comment]
`python -m spacy train --pipeline ner`   when evaluate the first epoch: ->
`
spacy\language.py", line 673, in evaluate
    docs, golds = zip(*docs_golds)
ValueError: not enough values to unpack (expected 2, got 0)
`

**Comment by phiedulxp** [comment]
`
python -m spacy debug-data zh train.json dev.json --pipeline ner
`
`
=========================== Data format validation ===========================
✔ Corpus is loadable

=============================== Training stats ===============================
Training pipeline: ner
Starting with blank model 'zh'
0 training docs
0 evaluation docs
✔ No overlap between training and evaluation data
✘ Low number of examples to train from a blank model (0)

============================== Vocab & Vectors ==============================
ℹ 0 total words in the data (0 unique)
ℹ No word vectors present in the model

========================== Named Entity Recognition ==========================
ℹ 0 new labels, 0 existing labels
0 missing values (tokens with '-' label)
✔ Good amount of examples for all labels
✔ Examples without occurrences available for all labels
✔ No entities consisting of or starting/ending with whitespace

================================== Summary ==================================
✔ 5 checks passed
✘ 1 error
`

**Comment by adrianeboyd** [comment]
Hmm, I'm confused. Is it JSON or JSONL? If it's JSONL data, the filename needs to end with `.jsonl`.

If that's not the problem, then something may be wrong with the formatting. Can you show a sample? How was it generated? What version of spacy are you using?

**Comment by phiedulxp** [comment]
whole annotation dataset format: [train-data](https://github.com/explosion/spaCy/tree/master/examples/training/training-data.json)
with cli-evaluate is ok.
ner dataset format:
`
train_data = [
    ("text", [(start, end, 'label')]),
]
`
doesn't work.

**Comment by adrianeboyd** [comment]
I'm still not sure I understand what format you're trying to work with, but my guess would be that the overall problem is related to #4173. There's no built-in conversion from the style shown in the example scripts to the JSON format used by the CLI.

The basic problem is that this format can be used for training directly (passed to `nlp.update()` as text / annotation), but can't be loaded by the CLI:

```
["Who is Shaka Khan?",{"entities":[[7,17,"PERSON"]]}]
```

You can see in the `debug-data` output that it's not finding any docs to work with. If `debug-data` says 0 docs, `train` and `evaluate` aren't going to find any, either. They all load the data in the exact same way.

Right now, the easiest method to convert data like this to the supported JSON training format is use a similar format (that comes from prodigy) that does have a built-in converter (only for NER, though!):

```
{"text":"Who is Shaka Khan?","entities":[{"start":7,"end":17,"label":"PERSON"}]}
{"text":"I like London and Berlin.","entities":[{"start":7,"end":13,"label":"LOC"},{"start":18,"end":24,"label":"LOC"}]}
```

If this data is saved in a file called `train.jsonl`, you can convert it with:

```
spacy convert -l en train.jsonl .
```

Set the right language with `-l` to get appropriate tokenization of the raw text.

**Comment by phiedulxp** [comment]
evaluate: `KeyError: 'paragraphs'`  means format like  [train-data](https://github.com/explosion/spaCy/tree/master/examples/training/training-data.json) ?
convert: `KeyError: 'spans'` means replace the key `entities` with `spans` ?

**Comment by adrianeboyd** [comment]
I'm sorry, I'm having trouble understanding what you want to do. The format handling depends mainly on the file extensions, so using `.json` vs. `.jsonl` might be the source of some of the errors, but it's hard to know without more details. Can you please provide:

1. a full example of one document (anonymized if needed)
1. the script or CLI command that you want to run

**Comment by phiedulxp** [comment]
I check the source code, `evalute` only support for format like `paragraphs ->sentences -> tokens`, 
as `.json` & `.jsonl` will call `json_to_tuple`
