### ISSUE TITLE
Pipe Name is used when deserializing instead of Pipe Type => Can't deserialize

### ISSUE THREAD

**Issue by oliviercwa** [explosion/spaCy#4712]
## How to reproduce the behaviour

1- Create a pipeline with 2 components of the **same type each with different name**. (One is enough, but this is to show that sometimes we want the name different from the pipe type)
[code below reproduces the problem]
2- Pipe these components together
3- Save to disk (or to_byte)
4- Load from disk

Result:
The loader does not find the pipe as it's looking for the name of the pipe in the factory instead of its Python type

Expected:
Persistence to persist the name and the pipe type

```
import spacy
import os

class MockComponent():
  ComponentName: str = 'MockComponent'
  def __init__(self, name = ''):
    self.name = name
  def __call__(self, doc):
    return doc

from spacy.language import Language
Language.factories[MockComponent.ComponentName] = lambda nlp, **cfg: MockComponent(**cfg) 
nlp = spacy.blank('en')

first = nlp.create_pipe(MockComponent.ComponentName, {'name':'first'})
last = nlp.create_pipe(MockComponent.ComponentName, {'name':'last'})
nlp.add_pipe(first, first.name, first=True)
nlp.add_pipe(last, last.name, last=True)
nlp.to_disk(os.path.join(os.path.dirname(__file__), 'temp'))
nlp2 = spacy.load(os.path.join(os.path.dirname(__file__), 'temp'))
```

Result:
"KeyError: "[E002] Can't find factory for 'first'. This usually happens when spaCy calls `nlp.create_pipe` with a component name that's not built in - for example, when constructing the pipeline from a model's meta.json. If you're using a custom component, you can write to `Language.factories['first']` or remove it 
from the model meta and add it via `nlp.add_pipe` instead."

Expected:
The serializer to serialize the Pipe Type (here MockComponent) and the Pipe Name. On load it would use the Pipe Type to create the object and assign the name in the pipeline.

## Your Environment

* Operating System: Win 10
* Python Version Used: 3.7.4
* spaCy Version Used: 2.1.9
* Environment Information:

**Comment by ines** [comment]
I'm not 100% sure I understand the problem, because to me it looks like it's working as intended? If only a component name is available, spaCy will look up the component name in the factories to create it. So you either need to add factories for all the component names. 

To make it easier to have components with different names that use the same factories, we've also been working on a new API for defining pipeline components (see #4517). It's already supported in v2.2, but currently only used under the hood.

The easiest solution for your use case would be to set `self.factory = "MockComponent"` in your component.

The new API using the component decorator would look like this:

```python
from spacy import component

@component("MockComponent")
def mock_component(doc):
    return doc

nlp.add_pipe(mock_component, name="first", first=True)
nlp.add_pipe(mock_component, name="last", last=True)
```

**Comment by oliviercwa** [comment]
Hello @ines ,
The issue is with the serialization/deserialization and still happens with a single element. Essentially today you can't have a pipe name that differs from a factory name. Would you expect the following to work?

```
import spacy
import os
from spacy.language import Language

class MockComponent():
  def __call__(self, doc):
    return doc

Language.factories['MockComponent'] = lambda nlp, **cfg: MockComponent(**cfg) 

nlp = spacy.blank('en')
foobar = nlp.create_pipe('MockComponent')
nlp.add_pipe(foobar, 'foobar', first=True)
nlp.to_disk(os.path.join(os.path.dirname(__file__), 'temp'))
nlp2 = spacy.load(os.path.join(os.path.dirname(__file__), 'temp'))
```

I would personally. I create a pipe using a factory name, then I insert the component inside a pipeline and assign a name. In spacy v2.1.9, that name in the pipeline can not be different from the factory name.

The code above throws:
```[E002] Can't find factory for 'foobar'. This usually happens when spaCy calls `nlp.create_pipe` with a component name that's not built in - for example, when constructing the 
pipeline from a model's meta.json. If you're using a custom component, you can write to `Language.factories['foobar']` or remove it from the model meta and add it via `nlp.add_pipe` instead."```
