### ISSUE TITLE
Error on token attribute in pattern matcher

### ISSUE THREAD

**Issue by RandomJungle** [explosion/spaCy#4717]
Hello, 

I noticed a strange behavior when updating to new version 2.2.3 from the version I was using before, which was 2.1.4. The 'LENGTH' attribute of token used in patterns started to match on anything. Below is the piece of code I used to reproduce the error:

```
import spacy
from spacy.matcher import Matcher
nlp = spacy.load("fr_core_news_md")
matcher = Matcher(nlp.vocab)
pattern = [{'SHAPE': 'dddd', 'LENGTH': 9}]
matcher.add("number", None, pattern)
doc = nlp("Bonjour nous sommes bien en 2005 ! Il est 9h du matin")
matches = matcher(doc)
print(matches)
```
On former version, there was no match, which is expected behavior. On newer version however, I get a match on 2005, [(432, 5, 6)]. Now here's a run of the same code, without the "shape" ingredient : 

```
import spacy
from spacy.matcher import Matcher
nlp = spacy.load("fr_core_news_md")
matcher = Matcher(nlp.vocab)
pattern = [{'LENGTH': 10}]
matcher.add("number", None, pattern)
doc = nlp("Bonjour nous sommes bien en 2005 ! Il est 9h du matin, surprenant !")
matches = matcher(doc)
if matches:
    for match in matches:
        print(doc[match[1]:match[2]])
```
It prints out every token of the sentence, which is odd to me, since LENGTH is listed as one of the token attribute that can be used in matcher on the official doc. Now if I run the exact same code with the former version (2.1.4) with model 2.1 of fr_core_news_md, it prints out "surprenant", which makes sense. 

Is the LENGTH attribute of the token deprecated in the new model version ?

**Comment by RandomJungle** [comment]
Update : I noticed that on release 2.2.2 it was mentioned that a new pattern adding behavior had been added, meant to replace the former. I tried using that but it produced the same result : 

```
import spacy
from spacy.matcher import Matcher
nlp = spacy.load("fr_core_news_md")
matcher = Matcher(nlp.vocab)
pattern = [[{'LENGTH': 10}]]
matcher.add("number", pattern)
doc = nlp("Bonjour nous sommes bien en 2005 ! Il est 9h du matin, surprenant !")
matches = matcher(doc)
if matches:
    for match in matches:
        print(doc[match[1]:match[2]])
```

prints out : 

```
Bonjour
nous
sommes
bien
en
2005
!
Il
est
9h
du
matin
,
surprenant
!
```
Unless I missed another major change on version 2.2 that explains that behavior ?

**Comment by adrianeboyd** [comment]
No, this looks like an unrelated bug. I can reproduce the problem and will see if I can figure out what's going on.

**Comment by adrianeboyd** [comment]
In spacy v2.1, invalid features were silently discarded, so you could have `{'ASDF': 'asdf'}` and it would act like `{}`. We tried to improve the validation so that you couldn't add as many obviously invalid patterns without `validate=True` and so that `Matcher` with `validate=True` would run a complete pattern scheme validation.

It looks like `{'LENGTH': 2}` ends up passing the validation (see #4442) but is still being silently discarded, which is kind of the worst of both options.

I still have to figure out why the integer version is not working as expected, but in the meanwhile, this pattern syntax does work:

```
[{'LENGTH': {"==": 2}}]
```

**Comment by RandomJungle** [comment]
Got it, 
I ended up using the 'REGEX' operator but I think this will be faster, thanks a lot for the workaround !
