### ISSUE TITLE
spacy train CLI skips training and saves the model

### ISSUE THREAD

**Issue by kormilitzin** [explosion/spaCy#4719]
**Preamble**:
I am interested in training a spaCy NER model with 8 categories and I have collected a small annotated dataset with all 8 categories. However from my previous experiments, I have a substantial amount of annotated data, but only for 5 of 8 categories. Therefore I decided to:
- first train a small NER model with only 5 categories 
- and then re-use it as a baseline model, for NER model with all 8 categories.

This is similar to spaCy examples on extending the list of entities by re-using a standard model and adding new categories.

However, when I use spaCy CLI for training, the training step is skipped and the model is directly saved:

![Screenshot 2019-11-27 at 00 00 31](https://user-images.githubusercontent.com/20815939/69683006-39006280-10ab-11ea-9e41-d1218fb45608.png)

## Your Environment
![Screenshot 2019-11-27 at 00 03 05](https://user-images.githubusercontent.com/20815939/69683023-43226100-10ab-11ea-947a-80c9962bb765.png)

Any ideas?

**Comment by ines** [comment]
This looks like there might be an uncaught exception in this block, so it skips and goes straight to the output. https://github.com/explosion/spaCy/blob/16cb19e960d614ddfcf04e35350f5c2fe4b6ba71/spacy/cli/train.py#L339

Could you run the `spacy debug-data` command with your data and see if it shows anything suspicious?

**Comment by kormilitzin** [comment]
thanks @ines, 

If I debug data without the pertained model (with less categories), than it looks OK:

![Screenshot 2019-11-27 at 15 08 02](https://user-images.githubusercontent.com/20815939/69735308-68a18000-1128-11ea-9209-2254c5192396.png)

And I can start training a blank model normally. However, if I use the pre-trained model, it shows errors: "misalignment tokens"

![Screenshot 2019-11-27 at 15 08 47](https://user-images.githubusercontent.com/20815939/69735288-617a7200-1128-11ea-9fb9-dd58fe048c29.png)

**However**, adding pertained model also changes the number of words: without the model: 164929, with the model 164665 (less). So definitely, the model somehow interfere.

Also, what is 'Misaligned token'?

**Comment by adrianeboyd** [comment]
Misaligned tokens are cases where spacy's tokenization doesn't line up with the tokens in the training data. Before training, it runs the tokenizer on the provided `raw` text and tries to align those tokens with the provided token `orth` values. If it can't align the tokens and `orths` in any useful way, the annotation on those tokens becomes `None` during training.
