### ISSUE TITLE
KeyError when trying to follow provided train_entity_linker.py script

### ISSUE THREAD

**Issue by JohnGiorgi** [explosion/spaCy#4723]
## How to reproduce the behaviour

Simply run the provided [`pretrain_kb.py`](https://github.com/explosion/spaCy/blob/master/examples/training/pretrain_kb.py) and [`train_entity_linker.py`](https://github.com/explosion/spaCy/blob/master/examples/training/train_entity_linker.py) scripts. E.g.

```
python pretrain_kb.py -m en_core_web_lg -n 1 -o ./tmp
python train_entity_linker.py ./tmp/kb ./tmp/vocab -o ./tmp -n 1       
```

During the execution of the second command, a KeyError is raised with the following traceback

```
Created blank 'en' model with vocab from 'tmp/vocab'
Loaded Knowledge Base from 'tmp/kb'
('Russ Cochran his reprints include EC Comics.', 'Russ Cochran captured his first major title with his son as caddie.', 'Russ Cochran has been publishing comic art.', "Russ Cochran was a member of University of Kentucky's golf team.") ({'links': {(0, 12): {'Q7381115': 1.0, 'Q2146908': 0.0}}}, {'links': {(0, 12): {'Q7381115': 0.0, 'Q2146908': 1.0}}}, {'links': {(0, 12): {'Q7381115': 1.0, 'Q2146908': 0.0}}}, {'links': {(0, 12): {'Q7381115': 0.0, 'Q2146908': 1.0}}})
Traceback (most recent call last):
  File "train_entity_linker.py", line 167, in <module>
    plac.call(main)
  File "/Users/johngiorgi/miniconda3/envs/el/lib/python3.7/site-packages/plac_core.py", line 367, in call
    cmd, result = parser.consume(arglist)
  File "/Users/johngiorgi/miniconda3/envs/el/lib/python3.7/site-packages/plac_core.py", line 232, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "train_entity_linker.py", line 127, in main
    sgd=optimizer,
  File "/Users/johngiorgi/miniconda3/envs/el/lib/python3.7/site-packages/spacy/language.py", line 515, in update
    proc.update(docs, golds, sgd=get_grads, losses=losses, **kwargs)
  File "pipes.pyx", line 1219, in spacy.pipeline.pipes.EntityLinker.update
KeyError: (0, 12)
```

There is another closed issue (#4469) that reports this same problem. Suggestions are to use the latest version of SpaCy (I tried with `2.2.2` and `2.2.3`) and to update the line

```
kb = KnowledgeBase(vocab=nlp.vocab)
```

in [`pretrain_kb.py`](https://github.com/explosion/spaCy/blob/48ea2e8d0ff6e46f65761425c24369c5d4ac30e1/examples/training/pretrain_kb.py#L57) with

```
kb = KnowledgeBase(vocab=nlp.vocab, entity_vector_length=64)
```

This solution did not work for me (I recieve the same error as above).

## Your Environment

* **spaCy version:** 2.2.2
* **Platform:** Darwin-19.0.0-x86_64-i386-64bit
* **Python version:** 3.7.5

**Comment by svlandeg** [comment]
Thanks for the very helpful report, @JohnGiorgi !  

The example scripts got outdated after the last refactor of the EL pipeline, which assumes the entities are properly set in the document. To simulate this, I added a EntityRuler to the example script, but for a realistic case you'd need to have a proper NER module.

I also created a more friendly warning that the one you ran into ...

PR #4789 contains the fixes. Once merged, feel free to try the code again and let me know if there still would be any issues.

**Comment by JohnGiorgi** [comment]
Hi @svlandeg,

Thanks for the PR! Sorry, this took a while, but I re-ran the scripts and now face a `thinc.exceptions.ShapeMismatchError` when running the latest version of the `pretrain_kb.py` script. 

I opened another issue regarding this error (#4876 )
