### ISSUE TITLE
Cannot replace spaCy lemmatized pronouns (-PRON-) through text

### ISSUE THREAD

**Issue by val-st** [explosion/spaCy#4727]
I'm trying to lemmatise a text with spaCy. Since spaCy uses -PRON- as lemma for personal pronouns, I want to keep the original text in all those cases.

Here's the relevant section of my code:

...
```

fout = open('test.txt', 'w+')
doc = nlp(text)
for word in doc:
     if word.lemma_ == "-PRON-":
          write = word.text
          print(write)
     else:
          write = word.lemma_
          fout.write(str(write))
          fout.write(" ")
```
...

It correctly identifies all the instances where it should produce text instead of '-PRON-' and the print statement does indeed print the original words rather than '-PRON-'

However, my output file (test.txt) always contains '-PRON-' for those cases, even though I would expect it to write the original words for those cases (I, us etc.)

I tried different versions, including using the pos_ tag to identify the pronouns etc. but always with the same result, i.e., that my output contains '-PRON-'s

I have spaCy version 2.2.2, Python version 3.7.4., running on a mac (Mojave)

**Comment by adrianeboyd** [comment]
Hi, this kind of problem is better-suited for StackOverflow, where you've already asked this question: https://stackoverflow.com/q/59077577/461847
