### ISSUE TITLE
How to extend spacy entity extraction?

### ISSUE THREAD

**Issue by brianrusso** [explosion/spaCy#473]
I'd like to extend spaCy's entity extraction to include things like IP addresses, URLs, email addresses, phone numbers, etc..

I'm more than happy to write the code and contribute it back, etc... 

All I'm looking for is where in the code I should start. I.e. what module I need to extend, etc.
Thanks!

**Comment by sainathadapa** [comment]
For future reference, this SO post has an example of how to achieve this : https://stackoverflow.com/questions/48112057/customized-tag-and-lemmas-for-urls-using-spacy
