### ISSUE TITLE
Spacy Hanging in a Django app when deployed on Apache Server

### ISSUE THREAD

**Issue by shuvayan-wgt** [explosion/spaCy#4732]
I am developing a resume parser where I have used spacy to parse 'Name' from a resume. Everything is working fine when I'm running it using 'python3 manage.py runserver' command. But after I have deployed it in a apache server, its hanging just after loading the spacy language module. Earlier it was freezing while loading only, but that got resolved after installing spacy-nightly. But now it is freezing while I'm passing any text through through the object created after loading the module.

`nlp = spacy.load('en_core_web_sm')`
`print('encoreweb')`
`doc = nlp(text)`
`print('name')`

Its printing 'encoreweb' but its not going to the next print.
## Your Environment

* Operating System: Ubuntu 16.04
* Python Version Used: 3.5
* spaCy Version Used: spacy-nightly
* Environment Information:

**Comment by adrianeboyd** [comment]
`spacy-nightly` is an alpha version of an older release. Please try upgrading to the most recent release, which should be v2.2.3 (or upgrade to v2.1.9 if you have custom v2.1 models).
