### ISSUE TITLE
Very slow matcher pattern

### ISSUE THREAD

**Issue by mr-bjerre** [explosion/spaCy#4742]
First of all, this might not be a bug at all. It might just be heavy misuse of pattern matching. I have a pattern where I want to match all phrases starting with `profit` or `profits` and ending with `ebitda` (at max 12 tokens in between). I.e. I want to encapsulate that.

```python
from spacy.matcher import Matcher
from spacy.lang.en import English

pattern = [{'LOWER': {'IN': ["profit", 'profits']}}, {'OP': '?'}, {'OP': '?'}, {'OP': '?'},
           {'OP': '?'}, {'OP': '?'}, {'OP': '?'}, {'OP': '?'}, {'OP': '?'}, {'OP': '?'}, {'OP': '?'}, {'OP': '?'},
           {'OP': '?'}, {'LOWER': 'ebitda'}, {'ORTH': ')', 'OP': '?'}]

text = '"improving operating profit and maintaining a disciplined approach to capital allocation."'

nlp = English()
matcher = Matcher(nlp.vocab)
matcher.add("ThisHangs", None, pattern)

matcher(nlp(text))  # this takes several seconds
```

## Your Environment

* **spaCy version:** 2.1.9
* **Platform:** Darwin-19.0.0-x86_64-i386-64bit
* **Python version:** 3.7.5
* **Models:** en

**Comment by adrianeboyd** [comment]
I think this kind of pattern is just going to be slow because it's internally finding a very large number of potential ways to assign the middle tokens to the ? patterns. It filters out equivalent spans at the end, but I don't think there's an easy way to improve the performance during matching -- maybe `Matcher` isn't the best tool for this?

**Comment by honnibal** [comment]
Agree that this might not be an ideal case for the matcher. You could try avoiding the quantifiers and just add extra patterns? For instance, `[{'LOWER': {'IN': ["profit", 'profits']}}, {}, {'LOWER': 'ebitda'}]` will match the case where there's only one word in between.
