### ISSUE TITLE
Dependency Parsing stability

### ISSUE THREAD

**Issue by frakar637** [explosion/spaCy#4744]
Hi

I'm new to spaCy and at the moment, I'm looking for the best ways to use it for dependency parsing.

Results from https://explosion.ai/demos/displacy
en_core_web_lg
Change the color to red. => color => red[dep=relcl]
Change the color to green. => change => to[dep=prep] => green[dep=pboj]
Change the color to yellow. => change => yellow[dep=advcl]
Change the color to pink. => change => pink[dep=advcl]

en_core_web_sm
Change the color to pink. => change => pink[dep=advcl]
Change the color to green. => change => green[dep=advcl]
Change the color to yellow. => change => yellow[dep=advcl]
Change the color to red. => change => red[dep=advcl]

It seems all the models do not have the same stability
I would expect the lg model to be more stable than the sm.
What the best way to insure the most stable parsing ?

**Comment by honnibal** [comment]
A frustrating problem that we've always had in the parser is that the model does poorly on imperatives. Try just making it "We change the color to red." That should make the model more confident, giving you better consistency.

**Comment by adrianeboyd** [comment]
Also, colors aren't a frequent topic in financial newspaper text, so the parser doesn't have much to go on. I think plenty of common colors aren't mentioned at all.

**Comment by frakar637** [comment]
So in that case,  shouldn't we expect the en_core_web_lg to be better than
the sm model?
Or maybe the concept of lg vs model is not related to efficiency?

Le lun. 2 déc. 2019 à 18:53, adrianeboyd <notifications@github.com> a
écrit :

**Comment by svlandeg** [comment]
You're right - in general you would expect the `lg` model to perform better - some more information about the different models can be found in Ines' SO comment [here](https://stackoverflow.com/a/57885943/7961860). You can see the benchmark performance of the different models [here](https://spacy.io/usage/facts-figures#benchmarks-models-english). `UAS` refers to the parser accuracy and you can see the difference is minimal. But even if `lg` is better in general, it may still be that the `sm` model is getting certain things correct that `lg` gets wrong.

Merging this issue with the master thread (Issue #3052) about inaccurate predictions - thanks again for the report!
