### ISSUE TITLE
Can't assign a name different from the factory name then save and load

### ISSUE THREAD

**Issue by oliviercwa** [explosion/spaCy#4747]
Save/Load cycle fails if pipe name differs from the factory name

## How to reproduce the behaviour
1- Create a pipe using create_pipe
2- Insert the component inside a pipeline using add_pipe and assign a name other than the factory name
3- Save and Load back the pipeline

**Result**: Exception E002 raised
Code below repros the problems with a single component

**Expected**: Be able to save and load a pipeline that was previously created. If Spacy lets me give an arbitrary pipe name, it should be able to load the pipeline back. **Today there's an expectation that the pipe name == factory name**

Note: This issue was raised in #4712  and I believe it was incorrectly closed.

```
import spacy
import os
from spacy.language import Language

class MockComponent():
  def __call__(self, doc):
    return doc

Language.factories['MockComponent'] = lambda nlp, **cfg: MockComponent(**cfg) 

nlp = spacy.blank('en')
foobar = nlp.create_pipe('MockComponent')
nlp.add_pipe(foobar, 'foobar', first=True)
nlp.to_disk(os.path.join(os.path.dirname(__file__), 'temp'))
nlp2 = spacy.load(os.path.join(os.path.dirname(__file__), 'temp'))
```

The code above throws on loading:
[E002] Can't find factory for 'foobar'. This usually happens when spaCy calls `nlp.create_pipe` with a component name that's not built in - for example, when constructing the pipeline from a model's meta.json. If you're using a custom component, you can write to `Language.factories['foobar']` or remove it from the model meta and add it via `nlp.add_pipe` instead."

## Your Environment
* Operating System: Windows 10
* Python Version Used: 3.7.4
* spaCy Version Used: 2.1.9
* Environment Information:

**Comment by ines** [comment]
As I explained in my comment in #4712, your observation is correct and this is expected:

> If only a component name is available, spaCy will look up the component name in the factories to create it. So you either need to add factories for all the component names. 

In your example, spaCy cannot know that the component `'foo'` in the pipeline requires the factory `MockComponent`. So you need to add a factory for `'foo'` explicitly. 

We also added a new feature  in v2.2.2 to make it easier to reuse component factories and build pipelines with multiple instances of the same component. This allows you to add an attribute `self.factory = 'MockComponent'` to your component:

```python
class MockComponent():
    factory = "MockComponent"
    
    def __call__(self, doc):
        return doc
```

You can also use the new `@component` decorator (already shipped in v2.2.2, but still "unofficial") that takes care of this for you behind the scenes:

> ```python
> from spacy import component
> 
> @component("MockComponent")
> def mock_component(doc):
>     return doc
> 
> nlp.add_pipe(mock_component, name="first", first=True)
> nlp.add_pipe(mock_component, name="last", last=True)
> ```

Here's a working end-to-end example that shows the serialization. Both components now know that they need the `MockComponent` factory and will deserialize accordingly.

```python
import spacy

@spacy.component("MockComponent")
def mock_component(doc):
    return doc

nlp = spacy.blank("en")
nlp.add_pipe(mock_component, name="first", first=True)
nlp.add_pipe(mock_component, name="last", last=True)

nlp.to_disk("/tmp/test-model")

new_nlp = spacy.load("/tmp/test-model")
print(new_nlp.pipe_names)  # ['first', 'last']
print(new_nlp.pipe_factories)  # {'first': 'MockComponent', 'last': 'MockComponent'}
```

**Comment by oliviercwa** [comment]
Hello Ines,

 

Thank you very much Ines for the long explanation, and thanks a lot for all your work on spacy. It’s fantastic! Also, I know you are very busy, so feel free to ignore the below 😊. 

 

It’s not a big deal as I am able to work around it in my code by serializing both the pipe name and the factory name, but I am still confused with your comment

 

“If only a component name is available”

 

The sample code provides both: a factory name during the component instantiation in create_pipe (doc clearly says the name is a factory name), and a pipeline name once inserted in the pipeline using add_pipe

 

foobar = nlp.create_pipe('MockComponent')

nlp.add_pipe(foobar, 'foobar', first=True)

 

“spaCy cannot know that the component 'foo' in the pipeline requires the factory MockComponent.”

I believe it can know that the component Foo requires the factory MockComponent. We just need to serialize it when saving the pipeline. My code actually wraps some of the Spacy classes and does precisely this. In the metadata section,  I store key dictionary with name and types:

 

“custom-pipeline”:[{“type”:”MockComponent”, “name”:”foobar”}] 

 

Danke schon,

 

Olivier

**Comment by ines** [comment]
> The sample code provides both: a factory name during the component instantiation in create_pipe (doc clearly says the name is a factory name), and a pipeline name once  inserted in the pipeline using add_pipe

When you call `add_pipe`, the `name` names the **instance of the component in the pipeline**. So you can use a factory "foo" that creates a component "bar" and add it to your pipeline with the name "baz".

When you're calling `create_pipe`, the name is the name of the **factory**. This is always going to be "foo", even if you renamed your component to "baz".

> I believe it can know that the component Foo requires the factory MockComponent. We just need to serialize it when saving the pipeline.

Of course it *could* know this – but in the v2.1 implementation it can't and doesn't if you run your code like this. You can use a workaround and serialize your own factory mapping. Or you can upgrade to the latest version that ships a new API to handle factories and components.
