### ISSUE TITLE
Wrong version when installing from pip

### ISSUE THREAD

**Issue by ddelange** [explosion/spaCy#4752]
When installing in a fresh environment (dockerized python:3.7-slim in this case), the `__version__` attribute does not correspond with `pkg_resources.get_distribution('spacy').version` (the version passed in `setup.py - setup()`). This is leading to unexpected errors in our implementation, and makes me doubt whether pip install is a stable way of installing older versions of spacy.

## How to reproduce the behaviour
```
pip install --upgrade 'spacy<2.1'
Collecting spacy<2.1
  Using cached https://files.pythonhosted.org/packages/cd/70/65504a011d7b262e73cfe470c36ca245a1f8e45b3b6661081289ffd72009/spacy-2.0.18-cp37-cp37m-manylinux1_x86_64.whl
...
Installing collected packages: spacy
Successfully installed spacy-2.2.3

python
>>> import spacy
>>> spacy.__version__
'2.0.18'

pip list | grep spacy
spacy                2.2.3
```

## Your Environment

* Operating System: buster (debian 10)
* Python Version Used: 3.7.5
* spaCy Version Used: not clear!
* Environment Information: clean dockerized env using `python:3.7-slim`

**Comment by ines** [comment]
I doubt this is a problem with spaCy. I just tried it locally and installing an old version from pip works fine for me using that syntax. It correctly installed v2.0.18.

Also in the output you shared, pip correctly downloads `spacy-2.0.18-cp37-cp37m-manylinux1_x86_64.whl`? And then for some reason it reports installing `spacy-2.2.3`? If that's really what happens, there must be something very strange going on in your installation and I don't think it's related to the wheels/packages we ship.

>  the __version__ attribute does not correspond with pkg_resources.get_distribution('spacy').version (the version passed in setup.py - setup())

The `__version__` should always match. There's only one place we're defining it, and it's what gets used in the setup, the wheels, etc. So it's not possible for the same installation to report different versions.

I suspect that when you're running `python` here, you're running a different Python that has a different version of spaCy installed. So `pip` is installing into a different Python. You can check this by running `which python` and `which pip`.

**Comment by ddelange** [comment]
thanks for the swift reply, i can confirm your explanation (by looking into the tar from pypi), but i still cant explain why this is the case in the docker image. i will investigate more tomorrow, but indeed i doubt its on spacy side indeed (since CI is passing which doesnt use this docker image). i will close this issue, and report back if i found the cause. thanks for your reply!

**Comment by ddelange** [comment]
This error occurred because we injected into setup.py a post-installation step: the installation of two pre-trained spacy models (pip install from tar), which executed before the right version of spacy was actually installed. So this pip-in-pip injection messed it up, ending up with latest spacy on system, since the pre-trained models did not have an upper spacy version pinned. Hence also the weird looking version differences between `pip list` and `__version__`, which is by the way still a mystery to me.
