### ISSUE TITLE
PyPI distributions contain files unnecessary to the installation

### ISSUE THREAD

**Issue by ddelange** [explosion/spaCy#4754]
## How to reproduce the behaviour
[Download](https://files.pythonhosted.org/packages/b7/f2/052bfe5861761599b5421916aba3eb0064d83145ff3072390ecdc5a836de/spacy-2.2.3.tar.gz) the latest tar from [PyPI](https://pypi.org/project/spacy/#files) and inspect

When creating dists for upload to PyPI, by default all top-level files are excluded, but there are many more files included in the tar than specified in MANIFEST.in. Minimal suggestion is to remove test files from the tar by adding `recursive-exclude spacy/tests/` to MANIFEST.in (which are now all installed along spacy, unnecessarily taking up space), but a safer way of setting this up would be building the tar up from scratch: starting empty, and building up selectively from there (for instance with recursive includes using `graft`), e.g. something like
```
global-exclude *
include setup.py
include README*
include LICENSE*
graft bin/
graft include/
graft spacy/
recursive-exclude spacy/tests/
recursive-exclude * __pycache__
include pyproject.toml
recursive-exclude spacy/lang *.json
recursive-include spacy/lang *.json.gz
```

**Comment by honnibal** [comment]
Thanks for the concern, but the tests are included intentionally, so that we can run the tests while building the conda package. The conda package is built from the PyPi source, and otherwise we'd have to check out the repository. It also allows anyone to run the tests over their installation.
