### ISSUE TITLE
AttributeError: 'English' object has no attribute 'noun_chunks'

### ISSUE THREAD

**Issue by dldisha** [explosion/spaCy#4759]
I'm trying to use `spacy noun_chunks`.

I downloaded the model with `python -m spacy download en_core_web_sm`

```
nlp = spacy.load("en_core_web_sm")
noun_chunks = nlp.noun_chunks
```
but it's throwing an error:
`AttributeError: 'English' object has no attribute 'noun_chunks'`

- Operating System: Ubuntu
- Python Version Used: 3.6
- spaCy Version Used: 2.2.3

Can somebody help me fix this issue? Thanks in advance!

**Comment by adrianeboyd** [comment]
Hi, here's an example for how to use noun_chunks:

https://spacy.io/usage/linguistic-features#noun-chunks
