### ISSUE TITLE
NER training with custom loss

### ISSUE THREAD

**Issue by basque21** [explosion/spaCy#4764]
Hi, I'm training my custom NER model with Spacy. Everything is OK, with the training and the model, but I have a problem: My dataset is partially labeled. So, say I have one only label. I want to weight this label in order to force model to predict it more usually although it sees examples where it's not labeled.

I don't know if I explained properly the problem... If someone has any idea I would really appreciate it!

Thanks!

**Comment by svlandeg** [comment]
All statistical models in spaCy are a subclass of [`Pipe`](https://github.com/explosion/spaCy/blob/master/spacy/pipeline/pipes.pyx#L46), which has a `get_loss` function. So what you could do, is subclass the component and implement a custom loss function.

The other thing you could try (which may be more straightforward) is upsample entities with the label you want to overrepresent, and feed that resampled dataset to your training procedure.
