### ISSUE TITLE
Procesing text by batch or by single string gives inconsistent doc.tensor values

### ISSUE THREAD

**Issue by wavymazy** [explosion/spaCy#4766]
## How to reproduce the behaviour

So I've been working with the en_trf_bertbaseuncased_lg model and ended up getting different classification results depending on how I processed text initially.
If I process text with the Language object using only 1 string 

_for ex_: **nlp(my_text)** or **nlp.pipe(my _text, batchsize=1)**

I end up with different doc.tensor had I used : 

**nlp.pipe(my_texts, batchsize=500)**

I compared the resulting doc, for each string, on a 1 by 1 basis, and the resulting vectors weren'T the same. I believe this to be the reason my classification results vary, and possibly why I get bad results when ingesting the same data by batch.

Thanks for reading and please let me know if I'm missing something, or if this is expected results. :+1: 

cheers!
## Your Environment

* Operating System: ubuntu 18.04
* Python Version Used: 3.6
* spaCy Version Used: 2.2.1
* Environment Information: I'm working with RASA.

**Comment by adrianeboyd** [comment]
Hi, thanks for the report! I could imagine that there could be an unintended interaction related to batching but I can't reproduce this, with either transformer or non-transformer models. Could you provide a minimal example that shows the problem?

**Comment by wavymazy** [comment]
Hey @adrianeboyd,

Thanks you for your reply.
Here is a scipt I run on my machine with 2 sentences that, on my machine, show me the tensors are different.

```
import spacy
import numpy as np

nlp = spacy.load('en_trf_bertbaseuncased_lg')

messages = ["Hello my name is daniel", "I would like to participate in interesting events"]

docs_by_batch = nlp.pipe(messages, batch_size=2)
docs_standard = [nlp(message) for message in messages]

for doc_by_batch, doc_standard in zip(docs_by_batch, docs_standard):
    if np.array_equal(doc_by_batch.tensor, doc_standard.tensor):
        print("Identical Vectors")
    else:
        print("Different Vectors")
```

Let me know how it goes when you test it.

Cheers !

**Comment by adrianeboyd** [comment]
Huh, the behavior is stranger than I expected and when I tested things I just lucked into test cases that don't show this problem. Some more test cases:

```
import spacy
import numpy as np

nlp = spacy.load('en_trf_bertbaseuncased_lg')

messages = [["Hello my name is daniel", "I would like to participate in interesting events"], ["I would like to participate in interesting events", "Hello my name is daniel", "one"], ["one", "two"], ["a sentence", "another sentence"], ["a sentence", "Hello my name is daniel"], ["Hello my name is daniel", "a sentence", "one", "two"]]

for i, texts in enumerate(messages):
    print("Round", i + 1)
    print("=======")
    docs_by_batch = nlp.pipe(texts, batch_size=2)
    docs_standard = [nlp(text) for text in texts]

    for doc_by_batch, doc_standard in zip(docs_by_batch, docs_standard):
        #print(doc_by_batch.tensor)
        #print(doc_standard.tensor)
        if np.array_equal(doc_by_batch.tensor, doc_standard.tensor):
            print("Identical Vectors:", doc_by_batch.text)
        else:
            print("Different Vector:", doc_by_batch.text)
    print("\n")
```

We'll look into it!

**Comment by adrianeboyd** [comment]
It looks like this happens for all models with vectors and all models on GPU, so the only model without this result is a small model on CPU.

**Comment by adrianeboyd** [comment]
I looked into this again and it really just seems to be due to float rounding differences. Checking whether the tensors are close rather than identical shows that the results are very similar. (Whew!)

**Comment by wavymazy** [comment]
Hi @adrianeboyd,

So I tested it out and tried with this script that rounds the vectors to 2 decimals:

    import spacy
    import numpy as np

    nlp = spacy.load('en_trf_bertbaseuncased_lg')

    messages = ["Hello my name is daniel", "I would like to participate in interesting events",
                "something is very strange with SpaCy", "The vectors aren't similar",
                "let us try to round both vectors to 5 decimals"]

    docs_by_batch = nlp.pipe(messages, batch_size=2)
    docs_standard = [nlp(message) for message in messages]

    for doc_by_batch, doc_standard in zip(docs_by_batch, docs_standard):
        if np.array_equal(np.around(doc_by_batch.tensor, 2), np.around(doc_standard.tensor, 2)):
            print("Identical Vectors")
        else:
            print("Different Vectors")

But unfortunately, results were very inconsistent. The second, third and fifth sentences in the list had identical vectors, but the first and fourth were different.

**Comment by adrianeboyd** [comment]
Hmm, you're right, sorry for not getting back to this sooner! I think I was focused on CPU vs. GPU for spacy and didn't check the transformers model carefully.

> **Update**: it's all spacy models on GPU, all transformers models with or without GPU.

This seems to still basically be true:

* spacy models show some small float rounding differences on GPU
* transformers models show major differences both on CPU and GPU

Spacy seems okay, so I'll open this as a new `spacy-transformers` issue.
