### ISSUE TITLE
Can't load the NER model by itself without disabling the vocab

### ISSUE THREAD

**Issue by oliviercwa** [explosion/spaCy#4768]
## How to reproduce the behaviour
1- Load vocab from any spacy model
2- Instantiate EntityRecognizer with vocab
3- Load EntityRecognizer model from disk by passing either the 'ner' folder path or the model root pat

```python
import os
import sys
from distutils.sysconfig import get_python_lib
from spacy.pipeline import EntityRecognizer
from spacy.vocab import Vocab
import spacy

model_path = os.path.join(get_python_lib(), 'en_core_web_sm')
vocab = Vocab()  
vocab = vocab.from_disk(os.path.join(model_path,'en_core_web_sm-2.1.0', 'vocab'))
ner = EntityRecognizer(vocab)
ner.from_disk(os.path.join(model_path,'en_core_web_sm-2.1.0', 'ner'))
```

**Result:** 
Passing the NER folder path ==>
**"ValueError: Can't read file: ...\Python\Python37\Lib\site-packages\en_core_web_sm\en_core_web_sm-2.1.0\ner\vocab\strings.json"**

Passing the root folder path ==>
**FileNotFoundError: [Errno 2] No such file or directory: ...\\Python\\Python37\\Lib\\site-packages\\en_core_web_sm\\en_core_web_sm-2.1.0\\moves'**

**Expected:**
Be able to load independently each component model

Notes:
1- the model is located in the folder and all the folders exist.
2- You can load the full pipeline using spacy.load, but in certain scenarios we need to load independently each component model.
3- The issue is that the EntityRecognizer needs files in both the NER folder and in the VOCAB folder and there does not seem to be a way to pass both paths.
4- The workaround is to disable the vocab:
```
ner.from_disk(os.path.join(model_path,'en_core_web_sm-2.1.0', 'ner'), exclude = ['vocab'])
```

## Your Environment
* Operating System: Win 10
* Python Version Used: 3.7.4
* spaCy Version Used: 2.1.9
* Environment Information:

**Comment by adrianeboyd** [comment]
Hi, this is exactly how the individual components are loaded internally (with `exclude=["vocab"]`), so I think that if you want to load individual components like this, it's a good way to do it, see:

https://github.com/explosion/spaCy/blob/e626a011cc94d77aa67a09a58f097d60cb1134c0/spacy/language.py#L907-L943

What's the reason for loading components separately?

**Comment by oliviercwa** [comment]
Hello,

 

Thank you for your answer Adriane.

 

The reason is so we can dynamically (meaning at runtime) create pipelines based on conditions. Imagine 8 component pipelines that can work independently or together depending on the situation. Creating 2^8 pipelines to represent all combinations is not an option. Instead we load component individually and build the pipeline on-demand.

 

I hope that makes sense. 

 

Best,
Olivier

**Comment by adrianeboyd** [comment]
Okay, I don't think there's a better way to do this currently, then.

It seems like you are aware of this, but you do need to be careful that all components are loaded with the same vocab or things won't work as intended. The API will let you create a pipeline from components with different vocabs without errors or warnings, but they won't run correctly in the end. (We should add some errors.)

**Comment by oliviercwa** [comment]
Thank you very much for the heads up. Yes we are very careful of this and in fact we have warnings in our wrapper code for this when adding components to the pipeline that use vocab

 

Thanks for all the wonderful work on spacy! It has been really helpful to us.

 

Best,

Olivier
