### ISSUE TITLE
Text classification results (Document.cat) missing when multiprocessing enabled

### ISSUE THREAD

**Issue by EdwardJB** [explosion/spaCy#4770]
## How to reproduce the behaviour

On a model that contains some text classifiers, run this code with `n_process=1`. It works as expected; classifications are present:

```python
text='my test text'
docs = self.model.pipe([text],n_process=1)
response = []
for i, (text, doc) in enumerate(zip(texts, docs), start=1):
    print(doc.to_json())
{'text': 'my test text', 'sents': [{'start': 0, 'end': 12}], 'cats': {...all of my cats are here..}, 'tokens': [{'id': 0, 'start': 0, 'end': 2}, {'id': 1, 'start': 3, 'end': 7}, {'id': 2, 'start': 8, 'end': 12}]}
```

Now run the same with `n_process=-1`, and they are missing:

```python
text='my test text'
docs = self.model.pipe([text],n_process=-1)
response = []
for i, (text, doc) in enumerate(zip(texts, docs), start=1):
    print(doc.to_json())
    print(doc.cats)
{'text': 'my test text', 'sents': [{'start': 0, 'end': 12}], 'tokens': [{'id': 0, 'start': 0, 'end': 2}, {'id': 1, 'start': 3, 'end': 7}, {'id': 2, 'start': 8, 'end': 12}]}
{}
```

## Info about spaCy

* **spaCy version:** 2.2.3
* **Platform:** Linux-4.4.0-18362-Microsoft-x86_64-with-glibc2.2.5
* **Python version:** 3.8.0

**Comment by adrianeboyd** [comment]
Thanks for the report! I can replicate this and it looks like the `cats` are going missing when the `Doc` is serialized. I'm surprised this bug wasn't noticed a lot earlier...
