### ISSUE TITLE
Installing spacy on spark kubernetes docker image takes a long time

### ISSUE THREAD

**Issue by jdukatz** [explosion/spaCy#4771]
## How to reproduce the problem
I'm running spark on a kubernetes cluster to do some data processing, so I'm using spark's recommended image to build my spark containers, which is found here: 

https://github.com/apache/spark/blob/master/resource-managers/kubernetes/docker/src/main/dockerfiles/spark/bindings/python/Dockerfile

I want to do some distributed processing with spacy, so I added the following lines to it:

```
RUN pip3 install spacy==2.1.1 \
    && python3 -m spacy download en
```

To be clear, spacy works just fine once the container is built, but the installation takes a *long* time, around 3 hours, mostly due to installing dependencies, e.g. `Running setup.py install for blis: still running...` (I can paste the full output if it would help).

I've messed around with trying to add some of the dependency libraries via apk install which seems to help a bit, but it's still over 2 hours.

So my question is, is this something I have to live with, or is there a way to install some of the dependencies manually so it goes faster?

## Your Environment

* Operating System: alpine linux
* Python Version Used: 3
* spaCy Version Used: 2.1.1
* Environment Information: spark kubernetes docker image

**Comment by ines** [comment]
Which exact Python version are you running during installation? 

It's compiling `blis` (and potentially other dependencies) from source because pip doesn't seem to serve a wheel. This shouldn't be happening, because we do build wheels for most platforms, e.g. see here: https://pypi.org/project/blis/0.4.1/#files So I think solving this problem will come down to figuring out how you can get pip to install from wheels only.

**Comment by jdukatz** [comment]
Thanks. Looks like the exact python version is 3.6.9.

My next thought for a workaround was to try to install directly from whl like you suggest. Unfortunately alpine seems to not like the `manylinux1` format of wheel on spacy's site (I get `not a supported wheel on this platform`, discussed in [this pip issue](https://github.com/pypa/pip/issues/3969))

I wonder if it would work to just wait for the build to complete, then hold on to that wheel and update my docker file to have pip install from that wheel directly. I can give that a shot and update this ticket.

**Comment by jdukatz** [comment]
Ok the wheel installs worked and are much quicker, but because of the `manylinux1` incompatibility I mentioned above you have to install spacy on the image first, compiling everything from source, then get wheels from that. So, yeah, if it helps any subsequent devs using spacy in this configuration with spark/kubernetes, my workaround is:

 - Build the docker image with regular old `pip install spacy`
 - Go do something else for a few hours
 - In the container use pip wheel to generate wheel files for spacy and its dependencies
 - pip install those wheel files on subsequent builds of the container

Not sure that there's anything you guys can do on the spacy side for this so I'll go ahead and close, but hopefully this helps someone else who might be running into the same thing.
