### ISSUE TITLE
"Unsupported type <class 'numpy.ndarray'> spacy on GPU using python3 multiprocessing

### ISSUE THREAD

**Issue by kbmlcoding** [explosion/spaCy#4773]
I am trying to run spacy similarity on bunch of documents on machine which has GPU tesla card 
 and using python3 multiprocessing to run in parallel but running into below issue
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "gpu.py", line 35, in chan_similarity
    df['sim_measure'] =  df.apply(lambda x : run_sim(x), axis=1)
  File "/home/kadu/venv/lib/python3.6/site-packages/pandas/core/frame.py", line 6913, in apply
    return op.get_result()
  File "/home/kadu/venv/lib/python3.6/site-packages/pandas/core/apply.py", line 186, in get_result
    return self.apply_standard()
  File "/home/kadu/venv/lib/python3.6/site-packages/pandas/core/apply.py", line 292, in apply_standard
    self.apply_series_generator()
  File "/home/kadu/venv/lib/python3.6/site-packages/pandas/core/apply.py", line 321, in apply_series_generator
    results[i] = self.f(v)
  File "gpu.py", line 35, in <lambda>
    df['sim_measure'] =  df.apply(lambda x : run_sim(x), axis=1)
  File "gpu.py", line 23, in run_sim
    return  (nlp_glob(x['all_train_data_with_desc_trim_100_null_removed.mov_chan_desc']).similarity(nlp_glob(x['all_train_data_with_desc_trim_100_null_removed.proj_chan_desc'])))
  File "doc.pyx", line 395, in spacy.tokens.doc.Doc.similarity
  File "doc.pyx", line 464, in spacy.tokens.doc.Doc.vector_norm.__get__
  File "doc.pyx", line 312, in __iter__
  File "cupy/core/core.pyx", line 935, in cupy.core.core.ndarray.__add__
  File "cupy/core/_kernel.pyx", line 828, in cupy.core._kernel.ufunc.__call__
  File "cupy/core/_kernel.pyx", line 90, in cupy.core._kernel._preprocess_args
TypeError: ("Unsupported type <class 'numpy.ndarray'>", 'occurred at index 2')
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gpu.py", line 78, in <module>
    dt = parallelize(chunk, chan_similarity)
  File "gpu.py", line 54, in parallelize
    data = pd.concat(pool.map(func, data_split))
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
TypeError: ("Unsupported type <class 'numpy.ndarray'>", 'occurred at index 2')
## Your Environment

* Operating System: Centos
* Python Version Used: python 3.6.8
* spaCy Version Used: spacy 2.2.3
* Environment Information: Running on Tesla GPU card

**Comment by adrianeboyd** [comment]
Thanks for the report! I tried a really simple example with multiprocessing and `doc.similarity()` and I can't easily reproduce this problem. It's also a little hard to tell exactly what's going on from the traceback. Could you see if you can provide a minimal example that shows the problem (preferably without pandas)?

**Comment by kadu9** [comment]
Thanks for responding. Please see the below snippet i am running.Hope this helps

def hive_connection(schema):
    conn = hive.Connection(host=host_name, port=port, username=user, database=schema)
    print("Acquired connection to hive ..")
    return conn
def get_spacy():
    if "nlp" not in globals():
        spacy.prefer_gpu()
        globals()["nlp"] = spacy.load('en_core_web_lg')
    return globals()["nlp"]

def run_sim(x):
    print(type(x))

    print(type(x['all_train_data_with_desc_trim_100_null_removed.mov_chan_desc']) ,"ele")
    d1 = str(x['text1])
    d2 = str(x['text2'])
    nlp_glob = get_spacy()
    return  (nlp_glob(d1).similarity(nlp_glob(d2)))

def chan_similaritydf):
    dsc1 = df['text1']
    dsc2 = df['text2']
    if (dsc1 is None or dsc2 is None):
        return float(0)
    if ((len(str(dsc1)) < 1 or str(dsc1) == "") or (len(str(dsc2)) < 1 or str(dsc2) == "")):
        return float(0)
    print(type(df),"in chan_sim")
    df['sim_measure'] =  df.apply(run_sim, axis=1)
    return df

def parallelize(data, func):
    data_split = np.array_split(data, partitions)

    print("in parallel", type(data_split))
    pool = Pool(cores)
    print('using', cores)
    data = pd.concat(pool.map(func, data_split))
    pool.close()
    pool.join()
    return data

data_list = list()
conn = hive_connection('schema')
data =pd.read_sql('select * from tablename limit 10', chunksize= 5, con=conn)

i=0
for chunk in data:
    print("processing chunk ", i)
    dt = parallelize(chunk, chan_similarity)
    data_list.append(dt)
    i = i + 1


big_df = pd.concat(data_list)

big_df.to_csv('train_data_with_sim_measure.csv', mode='a')
print("done generating sim measure")

**Comment by kbmlcoding** [comment]
Thanks for responding. Please see the below snippet i am running.Hope this helps

`def hive_connection(schema):
    conn = hive.Connection(host=host_name, port=port, username=user, database=schema)
    print("Acquired connection to hive ..")
    return conn
def get_spacy():
    if "nlp" not in globals():
        spacy.prefer_gpu()
        globals()["nlp"] = spacy.load('en_core_web_lg')
    return globals()["nlp"]

def run_sim(x):
    print(type(x))

    print(type(x['all_train_data_with_desc_trim_100_null_removed.mov_chan_desc']) ,"ele")
    d1 = str(x['text1])
    d2 = str(x['text2'])
    nlp_glob = get_spacy()
    return  (nlp_glob(d1).similarity(nlp_glob(d2)))

def chan_similaritydf):
    dsc1 = df['text1']
    dsc2 = df['text2']
    if (dsc1 is None or dsc2 is None):
        return float(0)
    if ((len(str(dsc1)) < 1 or str(dsc1) == "") or (len(str(dsc2)) < 1 or str(dsc2) == "")):
        return float(0)
    print(type(df),"in chan_sim")
    df['sim_measure'] =  df.apply(run_sim, axis=1)
    return df

def parallelize(data, func):
    data_split = np.array_split(data, partitions)

    print("in parallel", type(data_split))
    pool = Pool(cores)
    print('using', cores)
    data = pd.concat(pool.map(func, data_split))
    pool.close()
    pool.join()
    return data

data_list = list()
conn = hive_connection('schema')
data =pd.read_sql('select * from tablename limit 10', chunksize= 5, con=conn)

i=0
for chunk in data:
    print("processing chunk ", i)
    dt = parallelize(chunk, chan_similarity)
    data_list.append(dt)
    i = i + 1


big_df = pd.concat(data_list)

big_df.to_csv('train_data_with_sim_measure.csv', mode='a')
print("done generating sim measure")`


sorry i could not get it to format correctly the code here but i have some functions defined which are utilized

**Comment by adrianeboyd** [comment]
Hmm, that's still pretty hard to read, plus a lot of it is unrelated to this error. To improve the formatting, check that you have three backticks on a separate line (\`\`\`) before and after the code block.

Two easy things to try:

* put `spacy.prefer_gpu()` outside the `if` so it's run in every subprocess
* try loading a separate `nlp` object in each subprocess rather than having a global one (at least temporarily)

**Comment by kbmlcoding** [comment]
i was able to run this after building from latest source code from master branch  and is now using gpu1.

Another thing i noticed is , i have 4 tesla gpu cards in one machine but spacy is using only one of the card. is there any way i can tell spacy to use all 4 or maybe specific ones?

**Comment by kbmlcoding** [comment]
@adrianeboyd  can you advise if we can use/run spacy with multiple gpu cards on same machine?

**Comment by adrianeboyd** [comment]
With the caveat that I only have one GPU and haven't tested this, you should be able to use `spacy.util.use_gpu(gpu_id)` to specify which GPU spacy should use. This is also an option with the train CLI as `spacy train -g gpu_id`, so you can use `spacy train -g 0` to train on GPU 0.

**Comment by kbmlcoding** [comment]
Thanks !!
