### ISSUE TITLE
spacy import fail

### ISSUE THREAD

**Issue by guzhang480** [explosion/spaCy#4782]
I install spacy using multiple method, all are success, like this below:
pip install -U spacy[cuda100]
pip install -U spacy
pip install spacy
...
Successfully installed spacy-2.2.3

But import always fail. I got error:
AttributeError: type object 'cupy.core.core.Indexer' has no attribute '__reduce_cython__'

full error are below (Using "pip install spacy")
import spacy
Traceback (most recent call last):

  File "<ipython-input-2-76a01d9c502b>", line 1, in <module>
    import spacy

  File "C:\Users\guzha\anaconda3\lib\site-packages\spacy\__init__.py", line 10, in <module>
    from thinc.neural.util import prefer_gpu, require_gpu

  File "C:\Users\guzha\anaconda3\lib\site-packages\thinc\neural\__init__.py", line 4, in <module>
    from ._classes.model import Model  # noqa: F401

  File "C:\Users\guzha\anaconda3\lib\site-packages\thinc\neural\_classes\model.py", line 11, in <module>
    from ..train import Trainer

  File "C:\Users\guzha\anaconda3\lib\site-packages\thinc\neural\train.py", line 7, in <module>
    from .optimizers import Adam, linear_decay

  File "optimizers.pyx", line 14, in init thinc.neural.optimizers

  File "ops.pyx", line 24, in init thinc.neural.ops

  File "C:\Users\guzha\anaconda3\lib\site-packages\thinc\neural\_custom_kernels.py", line 8, in <module>
    import cupy

  File "C:\Users\guzha\anaconda3\lib\site-packages\cupy\__init__.py", line 15, in <module>
    from cupy import core  # NOQA

  File "C:\Users\guzha\anaconda3\lib\site-packages\cupy\core\__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA

  File "cupy\core\carray.pxi", line 50, in init cupy.core.core

AttributeError: type object 'cupy.core.core.Indexer' has no attribute '__reduce_cython__'

## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.7
* spaCy Version Used: 2.2
* Environment Information: regular installation

**Comment by guzhang480** [comment]
I do have 4 GB GPU in my windows computer.

**Comment by adrianeboyd** [comment]
Looks similar to this: https://stackoverflow.com/questions/53953623/attributeerror-type-object-cupy-core-core-broadcast-has-no-attribute-reduc -- check that you are installing the right version of cupy-cuda?

I would suggest installing without GPU support at first: uninstally `cupy` and `cupy-cuda100` and see if spacy works as expected. Then, reinstall cupy with `pip install spacy[cuda100]` (or whatever the correct CUDA version is).

Here's the same cupy requirements link from the SO question for reference: https://docs-cupy.chainer.org/en/stable/install.html#requirements

**Comment by BramVanroy** [comment]
This error occurs, as stated above, when you have a mismatch between the installed CUDA version and the installed spaCy version. You can try `pip install spacy[cuda]` if you're not sure which version you have installed (installation will take a bit longer). To find out the version of your current CUDA, type `nvcc --version` in your command line.

**Comment by guzhang480** [comment]
Thanks for the suggestions, everybody.
Finally I fixed the problem by the step below:

1. pip uninstall cupy-cuda100
2. pip install cupy-cuda101 (reinstall cupy) (or: pip install --pre cupy-cuda101)
3. pip install spacy[cuda101]

I repalce cuda100 using cuda101, because my cuda drive is 10.1, so 101 should be used!!!

**Comment by BramVanroy** [comment]
@guzhang480  Good that you solved it. By the way, since you're on Windows and using CUDA, it would be nice to see if you're also running into unexpected results. If you have the time, can you check out this topic and try out the repo? https://github.com/explosion/spaCy/issues/4758 Thanks a lot!

**Comment by guzhang480** [comment]
@BramVanroy Can you post your code produced unexpected results? I will repeat it soon.

**Comment by BramVanroy** [comment]
You can find the code here: https://github.com/BramVanroy/parsers-test

**Comment by guzhang480** [comment]
I'm using fin = r"D:\test Spacy in win10\head-1k-DPC.en"
replace your code: fin = r'data/head-1k-DPC.en'
but I got error: OSError: [Errno 22] Invalid argument: 'D:\test Spacy in win10\\head-1k-DPC.en'

any suggestion?

**Comment by guzhang480** [comment]
I convert the head-1k-DPC.en data file to txt format, the error keep same.

**Comment by BramVanroy** [comment]
Can you post the full error trace? If you just clone the repo you shouldn't have to change the paths.

**Comment by guzhang480** [comment]
Traceback (most recent call last):

  File "<ipython-input-44-054ea9d6db28>", line 40, in <module>
    number=n_runs)

  File "C:\Users\guzha\anaconda3\lib\timeit.py", line 232, in timeit
    return Timer(stmt, setup, timer, globals).timeit(number)

  File "C:\Users\guzha\anaconda3\lib\timeit.py", line 176, in timeit
    timing = self.inner(it, self.timer)

  File "<timeit-src>", line 13, in inner

  File "<ipython-input-44-054ea9d6db28>", line 5, in parse
    with open(fin, encoding='utf-8') as fhin:

OSError: [Errno 22] Invalid argument: 'D:\test Spacy in win10\\head-1k-DPC en.txt'

**Comment by guzhang480** [comment]
1. I copy-paste your sample data and save it here: D:\test Spacy in win10\head-1k-DPC en.txt
2. I'm using fin = r"D:\test Spacy in win10\head-1k-DPC.en"
    replace your code: fin = r'data/head-1k-DPC.en'
Above is my changes.

**Comment by BramVanroy** [comment]
Can you post the full code that you changed.

**Comment by guzhang480** [comment]
import timeit


def parse(nlp, fin):
    with open(fin, encoding='utf-8') as fhin:a
        text = fhin.read()
    doc = nlp(text)
    tokens = [token for sent in doc.sents for token in sent]


def parse_pipe(nlp, fin):
    with open(fin, encoding='utf-8') as fhin:
        lines = fhin.readlines()
    docs = list(nlp.pipe(lines))
    tokens = [token for doc in docs for sent in doc.sents for token in sent]


def parse_line_per_line(nlp, fin):
    with open(fin, encoding='utf-8') as fhin:
        for line in fhin:
            doc = nlp(line)
            tokens = [token for sent in doc.sents for token in sent]

if __name__ == '__main__':
    n_runs = 3

    setup_spacy = '''
import spacy
using_gpu = spacy.prefer_gpu()
print('spaCy using GPU?', using_gpu)
nlp = spacy.load('en_core_web_sm', disable=['ner', 'textcat'])
fin = r"D:\test Spacy in win10\head-1k-DPC en.txt"
'''
    t_spacy = timeit.timeit(stmt="from __main__ import parse; parse(nlp, fin)",
                            setup=setup_spacy,
                            number=n_runs)

    t_spacy_pipe = timeit.timeit(stmt="from __main__ import parse_pipe; parse_pipe(nlp, fin)",
                                 setup=setup_spacy,
                                 number=n_runs)
    t_spacy_line = timeit.timeit(stmt="from __main__ import parse_line_per_line; parse_line_per_line(nlp, fin)",
                                 setup=setup_spacy,
                                 number=n_runs)

    print(f"spaCy (avg of {n_runs:,} runs)", t_spacy / n_runs)
    print(f"spaCy pipe (avg of {n_runs:,} runs)", t_spacy_pipe / n_runs)
    print(f"spaCy line-per-line (avg of {n_runs:,} runs)", t_spacy_line / n_runs)

**Comment by BramVanroy** [comment]
Can't you just clone the repo and run it instezad of copypasting? It's hard to debug this way. If you can just leave the scripts and data as-is, that should just work.
