### ISSUE TITLE
Issue with loading lookups

### ISSUE THREAD

**Issue by christophermfeld** [explosion/spaCy#4784]
`ModuleNotFoundError: No module named 'spacy.lookups'
`
Getting stuck on the lookups import.

## Code Snippet:
```
from spacy.lemmatizer import Lemmatizer
from spacy.lookups import Lookups
lookups = Lookups()
lookups.add_table("lemma_rules", {"noun": [["s", ""]]})
lemmatizer = Lemmatizer(lookups)
```

## Environment
spaCy version    2.1.3
Location         /data01/anaconda3/lib/python3.7/site-packages/spacy
Platform         Linux-4.1.12-61.1.18.el7uek.x86_64-x86_64-with-redhat-7.6-Maipo
Python version   3.7.3
Models

**Comment by adrianeboyd** [comment]
You need a newer version of spacy for that example. Lookups was added in spacy v2.2. Try the most recent version, currently v2.2.3.
