### ISSUE TITLE
Labeling tool for dependency parser retraining

### ISSUE THREAD

**Issue by vonum** [explosion/spaCy#4785]
I am aware of the https://prodi.gy/ tool for labeling named entities.
However, I have not found an existing tool for handling the dependency parser.
Is there an existing tool that would solve labeling `dep_` and `head` tags through some kind of UI (like prodigy)?
If there is not, how would you recommend to go on with this problem?

## Your Environment
* **spaCy version:** 2.2.3
* **Platform:** Linux-4.15.0-60-generic-x86_64-with-debian-buster-sid
* **Python version:** 3.6.3

**Comment by adrianeboyd** [comment]
This is a bit outside the scope of spacy support, but there are quite a few tools for dependency annotation. This list of annotation tools provided by UD is a good place to start:

https://universaldependencies.org/tools.html#third-party-tools

If you need support for some of the UD-specific things like subtokens, your choice may be restricted a bit.
