### ISSUE TITLE
Explicitly prevent Doc.to_bytes() from saving the Vocab 

### ISSUE THREAD

**Issue by ldorigo** [explosion/spaCy#4786]
Hello,

Not entirely sure that this isn't currently possible, but if it is, then this should be seen as a request for better documentation :-)

I am doing large-scale automated processing of medical literature, and am storing the texts (and related information) in a relational database. Since parsing a text with Spacy takes a significant amount of time, I'd like to store the parsed docs as a blob of bytes alongside each text in the database. 

At the moment, unless I misunderstand something, the choice is between serializing docs directly (with `doc.to_bytes()`), which saves the whole vocab for each doc, or using `DocBin` for a list of docs, which serializes the vocab only once. Unfortunately neither of these are optimal for my use-case: serializing the vocab in each and every doc is a huge waste of space, and DocBin only makes sense if I stored all of the docs together - which doesn't allow me to retrieve them individually.

Ideally, it should be possible to serialize the doc without the vocab, and to add an optional parameter to `Doc.from_bytes` that allows using a specific vocab when deserializing. 

If this is already possible, please let me know how and I'd be happy to add a small section in the documentation to make it clearer for future users.

**Comment by adrianeboyd** [comment]
If you only want to save typical token-level annotation (tokens, sentence boundaries, tags, parses, NER), you could potentially use `doc.to_array()` and `doc.from_array()` instead. See the example here: https://spacy.io/api/doc#from_array

I think it could make sense to have an option to minimize the vocab for a particular doc on serialization, too, but that's not implemented.

**Comment by ldorigo** [comment]
I dug a bit into the code and ran some tests, and it appears that the `Vocab` was actually _not_ being serialized when using `doc.to_bytes`. The bulk of the space in the resulting bytes was actually used by the `tensor` attribute, which can be disabled by doing `to_bytes(exclude = "tensor")`. I'm a bit confused now, why do the docs say that the vocab does get serialized?

**Comment by adrianeboyd** [comment]
Hmm, you're right, and I was confused, too. I can't find a place where the docs say that `to_bytes()` includes the vocab, so I think the confusion comes from the section on using `pickle`, which would include the vocab with the doc. For pickle, it could make sense to have a `__reduce__()` function that minimizes the vocab, but this isn't relevant for `to_bytes()`.

If you don't need any of the information from the tensor in the future, then I think that `exclude=["tensor"]` is a good way to reduce the size.
