### ISSUE TITLE
Shipping model with custom tokenizer and custom preprocessor

### ISSUE THREAD

**Issue by mr-bjerre** [explosion/spaCy#4788]
I'd like to ship my model with a custom tokenizer but it doesn't load properly.

```python
from spacy import load
from spacy.tokenizer import Tokenizer
from spacy.lang.en import English


class CustomTokenizer(Tokenizer):
    def __call__(self, text):
        return super().__call__(text.replace("\u2013", "-"))


nlp = English()
nlp.tokenizer = CustomTokenizer(nlp.vocab)

assert nlp("\u2013").text == "-"  # passes

nlp.to_disk("test-model")
nlp = load("test-model")
assert nlp("\u2013").text == "-"  # fails
```

How is this achieved? I assume I have to create my own language, i.e. extend `English`? I tried the following as well with same result

```python
from spacy import load
from spacy.lang.en import English


class CustomEnglish(English):

    def make_doc(self, text):
        return self.tokenizer(text.replace("\u2013", "-"))


nlp = CustomEnglish()

assert nlp("\u2013").text == "-"  # passes

nlp.to_disk("test-model")
nlp = load("test-model")
assert nlp("\u2013").text == "-"  # fails
```

I also want to ship custom components and I recall Ines writing a post with Snake but I can't find it now. Link anyone?

Btw. I do realise that right now I only preprocess the text but I intent to change the tokenizer as well.

## Info about spaCy

* **spaCy version:** 2.2.3
* **Platform:** Darwin-19.0.0-x86_64-i386-64bit
* **Python version:** 3.7.5

**Comment by adrianeboyd** [comment]
I think your custom tokenizer needs its own serialization methods to save/load the relevant data. See: https://spacy.io/usage/saving-loading

**Comment by mr-bjerre** [comment]
Indeed the right place to look. However I extend `Tokenizer` so I inherit `to_disk` and `from_disk`. Shouldn't that make it work for me? Evidently not of course.

**Comment by adrianeboyd** [comment]
If you haven't, look at the `Tokenizer` methods for this. I think you're expected it to be like more like `pickle` than it is.

**Comment by mr-bjerre** [comment]
Thanks for responding so fast. I’m still not sure what to do though. 

Do you mind adding a few lines of code?

**Comment by mr-bjerre** [comment]
I took a peak into what they are doing at Allen AI with [scispaCy](https://github.com/allenai/scispacy/blob/master/scripts/init_model.py#L69). To me it looks like they are simply changing `nlp.tokenizer` to their own and then run a `nlp.to_disk` which is exactly what I'm doing as well. Now my example is not actually tokenization but preprocessing, the following example actually works for tokenization

```python
from spacy.language import Language
from spacy.tokenizer import Tokenizer
from spacy.util import compile_suffix_regex, compile_prefix_regex, compile_infix_regex
from spacy.lang.en import English
from spacy import load


def modify_tokenizer(nlp: Language) -> Tokenizer:
    prefixes = nlp.Defaults.prefixes + (
        r'[1-4][Qq]', '[Qq][1-4]',
    )
    infixes = nlp.Defaults.infixes
    suffixes = nlp.Defaults.suffixes + (
        r'[1-4][Qq]', '[Qq][1-4]',
    )

    nlp.tokenizer.prefix_search = compile_prefix_regex(prefixes).search
    nlp.tokenizer.infix_finditer = compile_infix_regex(infixes).finditer
    nlp.tokenizer.suffix_search = compile_suffix_regex(suffixes).search


nlp = English()
assert len([t for t in nlp('Q42018')]) == 1
modify_tokenizer(nlp)
assert len([t for t in nlp('Q42018')]) == 2
nlp.to_disk('test-model')

nlp = load('test-model')
assert len([t for t in nlp('Q42018')]) == 2
```

So my question is really; how do I ship a model with a custom preprocessor, i.e. I want `nlp(text)` to preprocess `text`? Is it possible? 

I noticed scispaCys [`remove_new_lines`](https://github.com/allenai/scispacy/blob/master/scispacy/custom_tokenizer.py#L12) that states
> Used to preprocess away new lines in the middle of words. This function is intended to be called on a raw string before it is passed through a pipeline

**Comment by mr-bjerre** [comment]
I almost have it working but I can't figure out how to load my preprocesser in.

I am missing the implementations of `to_disk` and `from_disk` to make this work.

```python
from spacy.language import Language
from spacy.tokenizer import Tokenizer
from spacy.util import compile_suffix_regex, compile_prefix_regex, compile_infix_regex
from spacy.lang.en import English
from spacy import load
from pathlib import Path


class Preprocessor:

    def __init__(self, tokenizer, **cfg):
        self.tokenizer = tokenizer

    def __call__(self, text):
        return self.tokenizer(text.replace('\u2013', '-'))

    def to_bytes(self, exclude=None, *args, **kwargs):
        pass

    def to_disk(self, path, **kwargs):
        pass

    def from_bytes(self, bytes_data, exclude=None, *args, **kwargs):
        pass

    def from_disk(self, path, **kwargs):
        pass


def modify_tokenizer(nlp: Language) -> Tokenizer:
    prefixes = nlp.Defaults.prefixes + (
        r'[1-4][Qq]', '[Qq][1-4]',
    )
    infixes = nlp.Defaults.infixes
    suffixes = nlp.Defaults.suffixes + (
        r'[1-4][Qq]', '[Qq][1-4]',
    )

    nlp.tokenizer.prefix_search = compile_prefix_regex(prefixes).search
    nlp.tokenizer.infix_finditer = compile_infix_regex(infixes).finditer
    nlp.tokenizer.suffix_search = compile_suffix_regex(suffixes).search
    nlp.tokenizer = Preprocessor(nlp.tokenizer)


nlp = English()
assert len([t for t in nlp('Q42018')]) == 1
assert nlp('\u2013').text != '-'
modify_tokenizer(nlp)
assert len([t for t in nlp('Q42018')]) == 2
assert nlp('\u2013').text == '-'
nlp.to_disk('test-model')

nlp = load('test-model')
assert len([t for t in nlp('Q42018')]) == 2
assert nlp('\u2013').text == '-'  # fails
```

**Comment by adrianeboyd** [comment]
Because of how the tokenizer is loaded differently than other pipeline components, I think this is trickier than I thought initially and I'm not entirely sure whether this is possible without a custom version of spacy (where a custom language would probably be a straightforward way to do this).

The difference with scispacy (and this is a good example to look at!) is that in the end they're just customizing a standard `Tokenizer`, which does save all the relevant settings (prefixes, suffixes, etc.) with `to_bytes()`. Again, look in detail at what `Tokenizer.to_bytes()` is doing: it's saving a prefix setting, not anything about what `__call__()` does.

One of spacy's principles is that the pipeline never modifies the input text, so the usual approach would be to do this kind of preprocessing outside of spacy. Even scispacy does it this way, see this test:

https://github.com/allenai/scispacy/blob/25e4c5d9e30f48eebbddc121bb05ff1057d5992a/tests/custom_tests/test_custom_tokenizer.py#L50-L55

Are you sure that you can't modify the tokenizer to work with the text that you have? Or preprocess your text outside spacy?

**Comment by mr-bjerre** [comment]
I think I'll preprocess outside spaCy. Thanks for looking into it!
