### ISSUE TITLE
token.ent_iob should be writable

### ISSUE THREAD

**Issue by tamuhey** [explosion/spaCy#4790]
I think `token.ent_iob` should be writable because `token.ent_type` is writable:
https://github.com/explosion/spaCy/blob/38e1bc19f4a1c28e27938f46bb3805df4919fedc/spacy/tokens/token.pyx#L733

`token.ent_iob` is not writable now, it can be only changed in cython:
https://github.com/explosion/spaCy/blob/38e1bc19f4a1c28e27938f46bb3805df4919fedc/spacy/tokens/token.pyx#L751

**Comment by adrianeboyd** [comment]
I've wondered about this, too, and it seems like a good idea to make it consistent. It is a little difficult to manage modifying both while making sure that nothing ends up in an invalid state, though.

**Comment by adrianeboyd** [comment]
Hi, we're just reviewing some older issues. As of v3, I think that `Doc.set_ents` is flexible enough to allow you to modify the entity attributes on any given span while making sure that the doc state remains consistent, e.g.:

```python
doc = nlp("An Entity")
doc.ents = [Span(doc, 0, 2, "ENTITY")]
assert doc.ents == ((Span(doc, 0, 2, "ENTITY")),)
doc.set_ents([], outside=[Span(doc, 0, 1)], default="unmodified")
assert doc.ents == ((Span(doc, 1, 2, "ENTITY")),)
```
