### ISSUE TITLE
Can I select a word as ROOT before dependency parsing?

### ISSUE THREAD

**Issue by JScarlet** [explosion/spaCy#4795]
## How to reproduce the behaviour

I'm using the dependency parser to parse a set of sentences with the same verb. I wanted the results that the __ROOT__ of every sentence is always the same verb. For example, I hope the ROOTs of the two sentences "pin shortcuts on a package." and "pins a contact at a provided position." is "__pin__". However, the __ROOT__ of the first sentence is "__shortcuts__". "__pin__" is labeled as a "NOUN", and the dep is "__amod__". The second sentence is what I want.

So I use the *__add_special_case__* method of the tokenizer, and label the word "__pin__" as a "__VERB__" before parsing. However, it just changes the POS tag and the dep is still "__amod__". 

My codes and outputs look like the following:

```
import spacy
from spacy.attrs import ORTH, LEMMA, POS, TAG

nlp = spacy.load('en')
sentence1 = 'pin shortcuts on a package.'
sentence2 = 'pins a contact at a provided position'

nlp_text1 = nlp(sentence1)
nlp_text2 = nlp(sentence2)

for token in nlp_text1:
    print(token.text, token.pos_, token.dep_)

print('---------')

for token in nlp_text2:
    print(token.text, token.pos_, token.dep_)

print("============")

special_case1 = [{ORTH: 'pin', LEMMA: 'pin', POS: 'VERB', TAG: 'VERB'}]
special_case2 = [{ORTH: 'pins', LEMMA: 'pin', POS: 'VERB', TAG: 'VERB'}]
nlp.tokenizer.add_special_case('pin', special_case1)
nlp.tokenizer.add_special_case('pins', special_case2)

new_nlp_text1 = nlp(sentence1)
new_nlp_text2 = nlp(sentence2)

for token in new_nlp_text1:
    print(token.text, token.pos_, token.dep_)

print('-------')

for token in new_nlp_text2:
    print(token.text, token.pos_, token.dep_)
```

```
pin NOUN amod
shortcuts NOUN ROOT
on ADP prep
a DET det
package NOUN pobj
. PUNCT punct
---------
pins VERB ROOT
a DET det
contact NOUN dobj
at ADP prep
a DET det
provided VERB amod
position NOUN pobj
============
pin VERB amod
shortcuts NOUN ROOT
on ADP prep
a DET det
package NOUN pobj
. PUNCT punct
-------
pins VERB ROOT
a DET det
contact NOUN dobj
at ADP prep
a DET det
provided VERB amod
position NOUN pobj
```

So I wonder whether I can select a word like "__pin__" as a __ROOT__ before dependency parsing, like what the *__add_special_case__* method of the tokenizer does?

## Your Environment

* Operating System: macOS Catalina 10.15.1
* Python Version Used: python 3.7
* spaCy Version Used: 2.1.4
* Environment Information:

**Comment by adrianeboyd** [comment]
The tagger and parser are completely independent, so setting tags won't affect the parser at all. Most of the components do respect existing labels, so you can set tags for some words, run the tagger, and it won't change any of the existing tags. Looking at the code, I don't think that the parser is written to try to preserve any existing labels, so it's an exception to this.

It's a known issue that the parser does poorly on imperatives (see another recent issue: https://github.com/explosion/spaCy/issues/4744#issuecomment-560505327). There aren't a lot of imperatives in the newspaper/web text the model is trained on, so it just hasn't seen enough examples of this kind of sentence.

If you know in advance that a sentence is an imperative, Matt's suggestion to temporarily rephrase them to get better parses is probably the best suggestion if you want to use the provided models.

**Comment by JScarlet** [comment]
Thanks for your reply.

Well, I haven't read the source codes about the tagger and parser yet and it seems that my thought is a little naive. I'll complement a subject for these imperatives and try to parse them again. Hope I can get a better result for my task. Also, hope we can train a better model for such imperatives later. If we can implement such a function, that would be great. Thanks.

**Comment by adrianeboyd** [comment]
No, it's not naive, since it does work like this in all components but the parser. I think it's potentially a lot harder to incorporate partial information into the parser than it is for the other models. The tagger just skips the tag assignment any words than already have tags and the NER model restricts itself to predicting new entities for "O" sequences.
