### ISSUE TITLE
NER with spaCy Bert

### ISSUE THREAD

**Issue by darshan99** [explosion/spaCy#4800]
## How to reproduce the behaviour
!pip install spacy-transformers
!python -m spacy download en_trf_bertbaseuncased_lg

import spacy
from spacy.util import minibatch
import random
import torch

ner = nlp.create_pipe("trf_ner", config={"exclusive_classes": True})

Error :
Component named "trf_ner" not found , where as i see it in lib files

## Your Environment
* Operating System: Windows
* Python Version Used: 3.7
* spaCy Version Used: 2.0
* Environment Information:

**Comment by adrianeboyd** [comment]
Hi, some of the groundwork is there, but I don't think this is supported yet. ("exclusive_classes" is only a relevant config setting for textcat.)

**Comment by darshan99** [comment]
> Hi, some of the groundwork is there, but I don't think this is supported yet. ("exclusive_classes" is only a relevant config setting for textcat.)

i did tried removing it , cloning the rep as an alternative to just pip install , but no success

**Comment by adrianeboyd** [comment]
The pipeline component "trf_ner" is not implemented yet, so this will not work no matter what the options are, sorry for the confusion!
