### ISSUE TITLE
Inconsistent return value type for .vector on GPU

### ISSUE THREAD

**Issue by jarib** [explosion/spaCy#4809]
Using a GPU, the return value of `.vector` is inconsistent depending on whether the token in question has a vector or not. Example:

```
>>> type(nlp('test').vector)
<class 'cupy.core.core.ndarray'>
>>> type(nlp('testasdasdasd').vector)
<class 'numpy.ndarray'>
```

* **spaCy version:** 2.2.2
* **Platform:** Linux-5.0.0-1026-gcp-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.6.8

**Comment by adrianeboyd** [comment]
Thanks for the report! This is a duplicate of #4673 and has been fixed by #4680.
