### ISSUE TITLE
Spacy reload models each time I hit ctrl+s

### ISSUE THREAD

**Issue by chaouiy** [explosion/spaCy#4810]
Is it normal to wait for 10 seconds (time to load models) each time I hit "ctrl+s" to save file in dev environment because of server reload (I use spacy inside django project) ?

**Comment by adrianeboyd** [comment]
10 seconds doesn't sound unusual, especially if it's reloading a `md` or `lg` model or loading multiple models. A `sm` model typically takes a few seconds to load.

**Comment by chaouiy** [comment]
> 10 seconds doesn't sound unusual, especially if it's reloading a `md` or `lg` model or loading multiple models. A `sm` model typically takes a few seconds to load.

TY, but the problem is more about how to avoid reloading same models each time I hit  ctrl+s than about the duration (10s)

**Comment by ines** [comment]
This sounds like it's related to how you've configured your editor and Django project, so maybe look into that? You probably want to configure it so it doesn't automatically restart the whole server whenever you edit a file. That seems pretty inefficient, especially when working with machine learning models.

**Comment by chaouiy** [comment]
I think it is normal that django reload the  server after each change so
that I can see results. The question is how to avoid wait time caused by
model loading during each server reload
