### ISSUE TITLE
Initializing language with a vocab is not working

### ISSUE THREAD

**Issue by oliviercwa** [explosion/spaCy#4812]
## How to reproduce the behavior
1- Initialize a Language class with a vocab. 
2- Add NER component
3- run on one sentence
(Code below / Method 1)

**Result**: No Named Entity detected

**Expected**: NER to work, and no difference between the two methods

Note: interestingly enough, if you assign the vocab property directly (method 2 below), it works. I am not quite sure why.

```python
import spacy
import os
import distutils.sysconfig
from spacy.vocab import Vocab
from spacy.language import Language
from pathlib import Path

model_path = os.path.join(distutils.sysconfig.get_python_lib(),'en_core_web_sm', 'en_core_web_sm-2.1.0')
vocab_path = os.path.join(model_path, 'vocab')
ner_path = os.path.join(model_path, 'ner')
sentence = "John Smith went to Berlin"

vocab = spacy.vocab.Vocab()
vocab.from_disk(vocab_path)

# Method 1: creating language with vocab ==> Named entities is empty
nlp = Language(vocab)
sentencizer = nlp.create_pipe('sentencizer')
nlp.add_pipe(sentencizer, first=True)

ner_pipe = nlp.create_pipe('ner')
ner_pipe.from_disk(Path(ner_path), exclude=['vocab'])
nlp.add_pipe(ner_pipe, last=True)
method1 = nlp(sentence)
assert(method1.ents != ())  # ASSERT TRIGGERS

#Method 2: assigning vocab ==> Named entity works as expected
nlp2 = Language()
nlp2.vocab = vocab
sentencizer = nlp2.create_pipe('sentencizer')
nlp2.add_pipe(sentencizer, first=True)

ner_pipe2 = nlp2.create_pipe('ner')
ner_pipe2.from_disk(Path(ner_path), exclude=['vocab'])
nlp2.add_pipe(ner_pipe2, last=True)
method2 = nlp2(sentence)
assert(method2.ents != ())  # ASSERT DOES NOT TRIGGER
```

## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by adrianeboyd** [comment]
I'm not sure which part of `Language.Defaults.create_vocab()` vs. `Language(vocab=Vocab())` is leading to this result with the NER model, but the following method should work:

```
nlp = Language()
nlp.vocab = nlp.vocab.from_disk(vocab_path)
```

**Comment by oliviercwa** [comment]
It works but if you pass the tokenizer, it does not work anymore:
```python
spacy_model_path = os.path.join(distutils.sysconfig.get_python_lib(),'en_core_web_sm', 'en_core_web_sm-2.1.0')
spacy_vocab_path = os.path.join(spacy_model_path, 'vocab')

en_core_vocab = spacy.vocab.Vocab()
en_core_vocab.from_disk(spacy_vocab_path)

nlp = Language()
nlp.vocab = en_core_vocab
nlp.tokenizer = Tokenizer(vocab = en_core_vocab)
ner = nlp.create_pipe('ner')
ner.from_disk(Path(spacy_model_path)/'ner', exclude=['vocab'])
nlp.add_pipe(ner, last=True)
result = nlp('John Smith went to Paris')
```

==> result.ents is empty

How can I load the vocab and the tokenizer independently and get a successful NER?

Thank you

**Comment by adrianeboyd** [comment]
Again, the problem seems to be related to using `spacy.vocab.Vocab()` to initialize the vocab. Instead, let `Language()` call `create_vocab()` internally and then load from the path:

```
nlp = Language()
nlp.vocab.from_disk(spacy_vocab_path)
nlp.tokenizer.from_disk(Path(spacy_model_path)/'tokenizer')
ner = nlp.create_pipe('ner')
ner.from_disk(Path(spacy_model_path)/'ner', exclude=['vocab'])
nlp.add_pipe(ner, last=True)
result = nlp('John Smith went to Paris')
```

This isn't something that many users try to do, so you may hit some undocumented or inconsistent corners (like `Tokenizer.from_disk()` not accepting a unicode argument as it says in the docs), but your best bet is to try to make your code as similar to `Language.from_disk()` as possible, since that's the standard, well-tested approach.

**Comment by oliviercwa** [comment]
Thank you @adrianeboyd . It seems the issue is with the tokenizer. When loaded independently with the example I provided above it fails. When loaded using nlp.tokenizer.from_disk it works. 

We have our own tokenizer, so how can I make the above example work by providing our own Tokenizer?

Thank you

**Comment by oliviercwa** [comment]
I think I found the magic sequence by sticking to the language.from_disk as you suggested:

```python
spacy_model_path = os.path.join(distutils.sysconfig.get_python_lib(),'en_core_web_sm', 'en_core_web_sm-2.1.0')
spacy_vocab_path = os.path.join(spacy_model_path, 'vocab')

nlp = Language()
nlp.vocab.from_disk(spacy_vocab_path)
tokenizer = SpacyTokenizer(vocab = nlp.vocab)
tokenizer.from_disk(Path(spacy_model_path)/'tokenizer', exclude=['vocab'])
nlp.tokenizer = tokenizer
ner = nlp.create_pipe('ner')
ner.from_disk(Path(spacy_model_path)/'ner', exclude=['vocab'])
nlp.add_pipe(ner, last=True)
result = nlp('John Smith went to Paris')
```

**Comment by adrianeboyd** [comment]
The difference is using `nlp.vocab` instead of the `Vocab()` vocab when initializing the tokenizer.

**Comment by oliviercwa** [comment]
Yes, you are absolutely right. 
**This works**
```python
nlp = Language()
nlp.vocab.from_disk(spacy_vocab_path)
```
**This does not work:**
```python
en_core_vocab = spacy.vocab.Vocab().from_disk(spacy_vocab_path)
nlp = Language()
nlp.vocab = en_core_vocab
```

**And neither does this:**
```python
en_core_vocab = spacy.vocab.Vocab().from_disk(spacy_vocab_path)
nlp = Language(vocab=en_core_vocab)
```

A possible reason is that Vocab is not serializing everything in the to_disk method. The BaseDefaults.create_vocab creates a vocab by passing 3 arguments:
```python
        vocab = Vocab(
            lex_attr_getters=lex_attr_getters,
            tag_map=cls.tag_map,
            lemmatizer=lemmatizer,
        )
```

And at least lex_attr_getters is not being serialized in Vocab.to_disk (possibly the two others). So there's no guarantee to get back the same object

**Comment by ines** [comment]
If you're starting out with the `English` language class (e.g. via a model like `en_core_web_sm`, that initializes itself by calling `get_lang_class("en")`), you also want to be loading your model back in with that class, and not just a blank instance of `Language`.

> And at least lex_attr_getters is not being serialized in Vocab.to_disk (possibly the two others). So there's no guarantee to get back the same object.

The lexical attribute getters are functions and won't be serialized. spaCy will only serialize data – it's not going to pickle and eval arbitrary code. That's also why it's important to start with the language class of the language you're using.

> Language, Vocab, and Tokenizer are tightly intertwined. Is there a document that goes about the relationships between these 3 classes?

The docs on adding languages explain the components the individual language classes can define: https://spacy.io/usage/adding-languages

Also see this graphic, which shows where they're used (`Morphology` is part of the `Vocab`):

<img width="657" alt="Screenshot 2019-12-17 at 21 56 26" src="https://user-images.githubusercontent.com/13643239/71033699-244a4400-2118-11ea-89e4-a155ac128ed0.png">

**Comment by oliviercwa** [comment]
Thank you Ines for the detailed explanations
