### ISSUE TITLE
Add a way to easily explore the syntactic parser results

### ISSUE THREAD

**Issue by raphael0202** [explosion/spaCy#482]
Stanford NLP provides a easy way to explore the results of their dependency parser, through Semgrex (http://nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/semgraph/semgrex/SemgrexPattern.html) and Tokenregex (http://nlp.stanford.edu/software/tokensregex.shtml).
It allows to match syntactic patterns in a very concise way, and avoids boilerplate code.
I didn't find anything similar in spaCy, is there other easy ways to explore dependencies ?
And if not, would you consider implementing such pattern recognition algorithms in spaCy?

**Comment by herrowna** [comment]
Agreed. Would love to see graphics for it too.
