### ISSUE TITLE
Matching on lemma without POS tagger

### ISSUE THREAD

**Issue by mr-bjerre** [explosion/spaCy#4824]
I am getting the following error when running a matcher on `spacy.lang.en.English`.

    ValueError: [E155] The pipeline needs to include a tagger in order to use Matcher or PhraseMatcher with the attributes POS, TAG, or LEMMA. Try using nlp() instead of nlp.make_doc() or list(nlp.pipe()) instead of list(nlp.tokenizer.pipe()).

That puzzles me since `Token.lemma_` does exist on the tokens, e.g. does the following yield True 

```python    
nlp('Dec.')[0].lemma_ == 'December'
```

I am aware that you probably shouldn't be able to match on lemma but I think the above is still confusing. I assume lemma is replaced by norm, maybe?

## Info about spaCy

* **spaCy version:** 2.2.3
* **Platform:** Darwin-19.0.0-x86_64-i386-64bit
* **Python version:** 3.7.5

**Comment by svlandeg** [comment]
Hi @mr-bjerre, this is indeed a bit of a confusing situation.

What happens is that running `token.lemma_` has a fallback mechanism to return something useful (from a lookup list) when that field is not actually set on the underlying Cython structure (by the tagger). For the matcher to work properly, it was decided that we really need the better quality lemmas. Maybe editing that error msg slightly could helpful clarify things ?

**Comment by svlandeg** [comment]
Actually, to be honest I'm not sure how to change that error msg without make things even more complicated / confusing. It does give a good explanation of what you should do to make it work. On top of that, if we do get rid of the lookup lemmas at some point, this point will become mute. So closing tentavily - hoping I did resolve your confusion about this!

**Comment by mr-bjerre** [comment]
@svlandeg I totally agree with you. The error message is actually perfectly fine. Whats confusing is that you have `Token.lemma_` without the POS tagger and thereby lemma matching available. You can close it for now yes.
