### ISSUE TITLE
PhraseMatcher not matching LEMMA even using 'nlp(term)'

### ISSUE THREAD

**Issue by seljaseppala** [explosion/spaCy#4825]
## How to reproduce the behaviour
I have the following function to process lists of terms with the PhraseMatcher:
```python
def add_patterns_to_phrasematcher(nlp, term_list, attr=None):
	
    if attr is None:
        nlp = English()

    matcher = PhraseMatcher(nlp.vocab, attr, validate=True)
    
    # If default PhraseMatcher (i.e., attr='ORTH')
    if attr is None:
        term_patterns_list = [nlp.make_doc(term) for term in term_list]

    # If attribute is specified
    else:
        term_patterns_list = [nlp(term) for term in term_list]

    # Add term patterns in list to PhraseMatcher
    term_label = 'USE_' + str(attr)
    matcher.add(term_label, None, *term_patterns_list)

    return matcher
```

The idea is to call the function with different attributes to create different matchers, and then combine and filter the matches output by matchers.

However, when using the PhraseMatcher with `attr=LEMMA` and `nlp = spacy.load('en_core_web_md', disable=['ner'])`, the returned matches are the same as when using it without any attributes (with the default `ORTH`) and `nlp = English()`. 

This seems to be confirmed by the warning message that is displayed when running the PhraseMatcher with `attr=LEMMA`:
```UserWarning: [W012] A Doc object you're adding to the PhraseMatcher for pattern 'USE_LEMMA' is parsed and/or tagged, but to match on 'ORTH', you don't actually need this information. This means that creating the patterns is potentially much slower, because all pipeline components are applied. To only create tokenized Doc objects, try using `nlp.make_doc(text)` or process all texts as a stream using `list(nlp.tokenizer.pipe(all_texts))`.```

Similar issues were already reported on the issue tracker, the closest one being [#4100](https://github.com/explosion/spaCy/issues/4100#issue-478869684), but the solutions don't seem to be working in my case.

Would this be an issue with the PhraseMatcher or with the way I am using it?

## Your Environment

* **spaCy version:** 2.2.3
* **Platform:** Darwin-19.2.0-x86_64-i386-64bit
* **Python version:** 3.7

**Comment by svlandeg** [comment]
Sorry, I'm having trouble understanding what exactly the problem is. The warning is mainly about speed, pointing out that you  `make_doc` should be more efficient in your case.

But if I understand you correctly, the main issue that you're expecting different result with different types of matching rules? If that's the case, could you provide an example (working code snippet) with the match rules you're applying, the output you're getting and what instead you would be expecting ?

**Comment by seljaseppala** [comment]
Thank you for your fast reply! Here is a full example with the expected and actual outputs.

```python
#!/usr/bin/python
# coding=<utf-8>
import spacy
from spacy.lang.en import English
from spacy.matcher import PhraseMatcher


def add_patterns_to_phrasematcher(nlp, term_list, attr=None):

    if attr is None:
        nlp = English()

    matcher = PhraseMatcher(nlp.vocab, attr, validate=True)

    # If default PhraseMatcher (i.e., attr='ORTH')
    if attr is None:
        term_patterns_list = [nlp.make_doc(term) for term in term_list]

    # If attribute is specified
    else:
        term_patterns_list = [nlp(term) for term in term_list]

    # Add term patterns in list to PhraseMatcher
    term_label = 'USE_' + str(attr)
    matcher.add(term_label, None, *term_patterns_list)

    return matcher


def print_matches(matches):
    for match_id, start, end in matches:
        label = nlp.vocab.strings[match_id]
        span = doc[start:end]
        print('MATCH_INFO:', match_id, label, start, end, span.text)


nlp = spacy.load('en_core_web_md', disable=['ner'])

voc = ['guidance', 'firm', 'communication', 'dealing', 'right of set-off']
text = "(1) This guidance applies to firms only with respect to their communications and dealings with consumers where a firm has a right of set-off."

lemma_matcher = add_patterns_to_phrasematcher(nlp, voc, attr='LEMMA')
text_matcher = add_patterns_to_phrasematcher(nlp, voc)

doc = nlp(text)

print_matches(lemma_matcher(doc))
print_matches(text_matcher(doc))

```

Expected output:

	MATCH_INFO: 15298788076101934575 USE_LEMMA 4 5 guidance
	MATCH_INFO: 15298788076101934575 USE_LEMMA 7 8 firms
	MATCH_INFO: 15298788076101934575 USE_LEMMA 13 14 communications
	MATCH_INFO: 15298788076101934575 USE_LEMMA 15 16 dealings
	MATCH_INFO: 15298788076101934575 USE_LEMMA 20 21 firm
	MATCH_INFO: 15298788076101934575 USE_LEMMA 23 28 right of set-off

Actual output:

	MATCH_INFO: 15298788076101934575 USE_LEMMA 4 5 guidance
	MATCH_INFO: 15298788076101934575 USE_LEMMA 20 21 firm
	MATCH_INFO: 15298788076101934575 USE_LEMMA 23 28 right of set-off


But now I get the following message for the default PhraseMatcher: 

	KeyError: "[E018] Can't retrieve string for hash '4420219867604095479'. This usually refers to an issue with the `Vocab` or `StringStore`."

**Comment by svlandeg** [comment]
Ok the hash string `KeyError` is because you redefine your `nlp` object when calling `add_patterns_to_phrasematcher` with no `attr`, but you don't use that new `nlp` object afterwards for `nlp(text)`, so there is a mismatch between your vocab hashes.

**Comment by svlandeg** [comment]
And I found the other bug in your code causing the original confusion here. It needs to be :
```
matcher = PhraseMatcher(nlp.vocab, attr=attr, validate=True)
```
instead of 
```
matcher = PhraseMatcher(nlp.vocab, attr, validate=True)
```
because the signature of `PhraseMatcher` is 
```
def __init__(self, Vocab vocab, max_length=0, attr="ORTH", validate=False):
```
so your `attr` got parsed as `max_length`.

This is not clear from the [docs ](https://spacy.io/api/phrasematcher#init) though, where it is mentioned that `max_length` is deprecated, but not that it could still mess up the order of arguments. I'll try to fix that in the documentation.

Hope that resolves your trouble !

**Comment by seljaseppala** [comment]
Thank you very much for the detailed explanations! It was very helpful!

The PhraseMatcher with the `LEMMA` attribute works now. 

However, when using the default PhraseTagger, I get the following message: `File "phrasematcher.pyx", line 56, in spacy.matcher.phrasematcher.PhraseMatcher.__init__
AttributeError: 'NoneType' object has no attribute 'upper'`

Would you know why this is happening?
