### ISSUE TITLE
please add the build dependencies back to pyproject.toml

### ISSUE THREAD

**Issue by AlJohri** [explosion/spaCy#4829]
Please add the build dependencies back to pyproject.toml or remove the file altogether. I need to install the package from source and I want to do it in a single step using `pip install git+https://...`.

As you can see below, I forked the repo and added the build dependencies back in which fixed the installation via pip.

## How to reproduce the problem

FAILS:
```
.venv/bin/pip install git+https://github.com/explosion/spaCy
```

WORKS:

```bash
.venv/bin/pip install git+https://github.com/AlJohri/spaCy
```

My fork has a single commit which adds the build dependencies back to pyproject.toml: https://github.com/AlJohri/spaCy/commit/8156172ef4d14ef7bca14792a394a88fe5ab0a69

## Your Environment

`$ .venv/bin/python -m spacy info --markdown`

* **spaCy version:** 2.2.3
* **Platform:** Darwin-18.7.0-x86_64-i386-64bit
* **Python version:** 3.7.5

cc @ines

**Comment by ines** [comment]
I'd be happy to remove the `pyproject.toml` alltogether for now. I'll need to find the original issue, but I think we initially added it because a user requested it for a specific use case.

But it turned out to not really be feasible to list the build dependencies in *yet another* place. A single out-of-sync version pin can easily cause a lot of headache, so ideally, we'd only want to list dependencies in the `setup.cfg` and `requirements.txt`.

**Comment by AlJohri** [comment]
@ines sure I think that works. let me try removing the `pyproject.toml` file in my fork and seeing if that facilitates the direct pip install from git

**Comment by b-long** [comment]
@AlJohri Any luck?

**Comment by AlJohri** [comment]
sorry, not yet- will do that this weekend

**Comment by AlJohri** [comment]
@ines Unfortunately, running `.venv/bin/pip install git+https://github.com/AlJohri/spaCy` doesn't install the build dependencies. I think build dependencies can only be specified using PEP 518 (using the pyproject.toml).

To get it to work _without_ the `pyproject.toml` file, I had to run the following commands. This still requires running two separate commands and doesn't inside of a single requirements.txt file.

```bash
.venv/bin/pip install -r <(curl -s https://raw.githubusercontent.com/explosion/spaCy/master/requirements.txt)
.venv/bin/pip install git+https://github.com/AlJohri/spaCy
```

Even explicitly defining the build dependencies doesn't work as pip is unable to find the build dependencies (that are already installed in the venv). Providing `--no-build-isolation` doesn't help.

```
.venv/bin/pip install --no-build-isolation -r requirements.txt
```

```
cython>=0.25
cymem>=2.0.2,<2.1.0
preshed>=3.0.2,<3.1.0
murmurhash>=0.28.0,<1.1.0
thinc==7.4.0.dev0
-e git+https://github.com/AlJohri/spaCy#egg=spaCy
```

I think if there was some way to keep the pyproject.toml with the build dependencies defined that would be the most ideal user experience for installing from source.

**Comment by ines** [comment]
Thanks for looking into this! I guess there's no way around maintaining our dependency lists in 3 different places then 😭

We can update this again for the next release. I guess we could also have a test that reads the `setup.cfg`, `pyproject.toml` and `requirements.txt` and fails if the same package is defined with different version pins. (Or if build dependencies are missing in either the `setup.cfg` or the `pyproject.toml`.)

**Comment by svlandeg** [comment]
I thought the unit test was a great idea to make sure things remain in-sync, I've been struggling with that in the past too. It's kind of ad-hoc and ugly, but hopefully still helpfull? cf PR https://github.com/explosion/spaCy/pull/5008
