### ISSUE TITLE
How to train multiple labels of NER at the same time?

### ISSUE THREAD

**Issue by youikim** [explosion/spaCy#4832]
Hi there, I am having a issue with creating & training multiple labels of NER. It works fine with single label tho. As I am a coding beginner, please take a look my code below and please give me a proper solution to resolve the issue. 
----------------
TRAIN_DATA = [
    ("If Contractor is not liable to pay any compensation to Contractor for loss of profits or loss of goodwill or for any other loss or damage howsoever arising as a result of the termination",
    {"entities": [(70, 86, "LOP")]}),
    ("For the portion of the Contract Price that exceeds NOK 1 billion, the liability for liquidated damages is limited to 5 % of the excessive amount",
    {"entities": [(107, 115, "Limited")]}),
    ("Nor the BUILDER shall in any circumstance be responsible or liable for any consequential or special loss, damage or expense",
    {"entities": [(75, 89, "Consequential")]}),
    ("Contractor shall pay to Owner, as liquidated damages for such delay, the amount corresponding to the percentage of the Contract Price of the FLNG as per Section 9.2.1.",
     {"entities": [(34, 54, "Governed")]}),
    ("CONTRACTOR shall not take and is not authorized to take any action in the name of or otherwise on behalf of COMPANY which would violate applicable LAW or which would subject either party to liability or penalty under any laws, rules, regulations or decrees of any governmental authority",
     {"entities": [(203, 211, "Penalty")]}),
    ("FIDIC strongly recommends that the Employer ensures that the Employers Requirements contain a clearly identified, defined and described specific purpose or purposes for which the facility will be used when complete, in order that the Contractor can comply with the obligation to provide Works which are fit for the purpose(s) for which they are intended as stated in this Sub-Clause.",
    {"entities": [(303, 322, "FFP")]}),
    ("Upon notice to Contractor, Owner may in its absolute discretion withhold or deduct payment of any amount described in an Invoice or portions thereof in an amount and to such extent as may in its sole opinion be reasonably necessary to protect Owner due to Liquidated damages such as Delay Damages which Contractor owes.",
     {"entities": [(283, 296, "D-Damages")]}),
    ("when completed, not being fit for the purpose(s) for which they are intended under Sub-Clause 4.1.",
     {"entities": [(26, 45, "FFP")]}),
    ("The parties hereto agree that the validity and the interpretation of this Contract and of each Article and part thereof shall be governed by the laws of England.",
     {"entities": [(130, 139, "Governed")]}),
    ("COMPANY shall not be liable for any other damages including, without limitation, loss of anticipated profits.",
     {"entities": [(83, 110, "LOP")]}),
    ("shall mean (i) indirect or consequential losses and/or (ii) loss of production, loss of product, loss of use and loss of revenue, profit or antic ipated profit",
    {"entities": [(27, 41, "Consequential")]}),
    ("The Contractor shall be responsible for this part and it shall, when the Works are completed, be fit for such purpose(s) for which the part is intended as are specified in the Contract (or, where no purpose(s) are so defined and described, fit for their ordinary purpose(s).",
     {"entities": [(97, 117, "FFP"), (240, 270,"FFP")]}),
    ("This Contract is governed by and interpreted under the laws of England, without regard to its choice of law rules.",
     {"entities": [(18, 27, "Governed")]}),
    ("All exclusions and indemnities given under this ARTICLE 22(save for those under Section 22.1.1(c), Section 22.2.1(c), and Section 22.9(Consequential Damages) shall apply irrespective of cause and notwithstanding the negligence or breach of duty(whether statutory or otherwise)of the indemnified party or any other entity or  party and shall apply irrespective of any claim in tort, under contract or otherwise at law.",
     {"entities": [(135, 156, "D-Damages")]}),
    ("If these revised methods cause the Employer to incur additional costs, the Contractor shall subject to Sub Clause 2.5 pay these costs to the Employer, in addition to delay damages under Sub Clause 8.7 below.",
     {"entities": [(166, 181, "D-Damages")]}),
    ("To the extent, if any, that the Contractor is responsible for the design of part of the Permanent Works under Sub-Clause 4.1, and/or any other design under the Contract, the Contractor shall also indemnify and hold harmless the Employer against all acts, errors or omissions by the Contractor in carrying out the Contractors design obligations that result in the Works, when completed, not being fit for the purpose(s) for which they are intended Under Sub-Clause 4.1.",
     {"entities": [(396, 415, "FFP")]}),
    ("Contractor's liability for any delay this might cause shall be limited to the maximum liability for delays that the Subcontractor can incur towards Contractor",
    {"entities": [(64, 72, "Limited")]}),
    ("24.1 CONTRACTOR shall compensate COMPANY for any consequential, special, or indirect damages or loss of anticipated profits sustained by COMPANY, limited, however to the extent CONTRACTOR may recover from insurance carried by it and to the extent it may recover such damages or losses from vendors, subcontractors, renters of construction tools and construction equipment, or others.",
     {"entities":[(76, 91, "D-Damages")]}),
    ("Contractor must provide all Construction Equipment necessary for the performance of the Work. Such Construction Equipment must be fit for the use it is intended for and maintained at all times in good operating condition with appropriate and uninterrupted valid certification in accordance with Applicable Laws and the Contract requirements.",
     {"entities": [(130, 145, "FFP")]}),
    ("Interest, penalties, or other liabilities arising from such failures shall be for CONTRACTOR's account.",
     {"entities": [(10, 20, "Penalty")]}),
    ("the PERMANENT WORK shall be fit for the purposes specified in the CONTRACT, or where no such purpose is specified, fit for its ordinary purpose.",
     {"entities": [(115, 144, "FFP")]}),
    ("any sums that would be payable under this ARTICLE 20 are in the nature of liquidated damages.",
     {"entities": [(74, 93, "D-Damages")]}),
    ("The Work shall be fit for the purposes specified in the Contract or, where no such purpose is specified, fit for its ordinary purpose.",
     {"entities": [(105, 144, "FFP")]}),
    ("Except as provided in ARTICLE 21 and Sections 10.8 and Section 22.1.2, payment of the Delay Damages shall be Owner’s sole and exclusive remedy for Contractor’s failure to achieve the Handover of the FLNG on or before the applicable Handover Date or achieve Commencement of Stable Operation on or before the applicable Commercial Operation Date.",
     {"entities": [(86, 99, "D-Damages")]}),
    ("This Sub-Clause shall not limit liability in any case of fraud, gross negligence, deliberate default or reckless misconduct by the defaulting Party",
    {"entities": [(26, 42, "Limited")]}),
    ("The maximum total amount of liquidated damages payable under Section20.2 (“Delay Damages”) in respect of the Physical Work or FLNG shall be equal to ten percent of the Contract Price of the FLNG.",
     {"entities": [(77, 90, "D-Damages")]}),
    ("The proposal shall contain a breakdown of the total compensation for the Work, including all claims to be made by Contractor, less any liquidated damages and other amounts due to Company.",
     {"entities": [(135, 155, "D-Damages")]}),
    ("Williams Field Services Group LLC, here in after referred to as Company,  a Delaware limited liability company",
    {"entities": [(85, 103, "Limited")]}),
    ("The Contractor has no liability for any indirect or consequential loss or damage suffered by the Employer as a result of any negligence by the Contractor in designing the Works to be fit for purpose.",
     {"entities": [(183, 198, "FFP")]}),
    ("if there is no Schedule of Performance Guarantees under the Contract, or no applicable Performance Damages, a reduction in the Contract Price.",
     {"entities": [(87, 107, "D-Damages")]}),
    ("If CONTRACTOR fails to achieve COMPLETION of PLANT by the SCHEDULED COMPLETION DATE indicated in 3.2 above for reasons other than those resulting from force majeure or those directly attributable to actions taken by COMPANY, CONTRACTOR shall pay to COMPANY, for each week or part of a week of delay, in place of actual damages incurred by COMPANY due to such delay in COMPLETION of PLANT, the fixed sum(s) and agreed liquidated damages specified below.",
     {"entities": [(417, 435, "D-Damages")]}),
    ("Such Construction Equipment must be fit for the use it is intended for and maintained at all times in good operating condition with appropriate and uninterrupted valid certification in accordance with Applicable Laws and the Contract requirements.",
     {"entities": [(36, 52, "FFP")]}),
    ("Nor the BUILDER shall in any circumstance be responsible or liable for any consequential or special loss, damage or expense including but not limited to loss of time, loss of profit of earning or demurrage directly or indirectly occasioned to the BUYER.",
     {"entities": [(168, 183, "LOP")]}),
    ("The payment of liquidated damages shall not relieve CONTRACTOR from all of its other obligations and liabilities under CONTRACT, including its obligation to perform WORK.",
     {"entities": [(15, 33, "D-Damages")]}),
    ("Performance Damages means the damages to be paid by the Contractor to the Employer for the failure to achieve the guaranteed performance of the Plant and/or the Works or any part of the Works.",
     {"entities": [(0, 20, "D-Damages")]}),
    ("Company shall indemnify Contractor Group from and against claims mentioned in the first paragraph above, to the extent that they exceed the limitations of liability mentioned above, regardless of any form of liability, whether strict or by negligence, in whatever form, on the part of Contractor Group",
    {"entities": [(141, 165, "Limited")]}),
    ("Conciliation Act, Cap. A18, Laws of the Federation of Nigeria, 2004 and any amendments thereto, by three arbitrators each party will appoint an arbitrator.",
     {"entities": [(19, 22, "CAP")]}),
    ("the Works (or Section or major item of Plant, if any) shall be fit for the purpose(s) for which they are intended, as defined and described in the Employer’s Requirements or, where no purpose(s) are so defined and described, fit for their ordinary purpose(s)",
     {"entities": [(63, 82, "FFP"), (227, 257, "FFP")]}),
    ("CONTRACTOR shall pay COMPANY, in lieu of actual damages, one half of one percent (0.5%) of the sum of (i) CONTRACT PRICE indicated in paragraph 1.1 of Exhibit A herein plus (ii) contract price paid to ENGINEERING CONTRACTOR for work performed by it in connection with PLANT, (both prices as adjusted for approved CHANGE ORDERS ) for each week or part of a week the COMPLETION of PLANT is delayed beyond the SCHEDULED COMPLETION DATE (as adjusted for approved CHANGE ORDERS).",
     {"entities":[(41, 54, "D-Damages")]}),
    ("the Works, or a Section, fail to pass any or all of the Tests after Completion; and (b) applicable Performance Damages are set out in the Schedule of Performance Guarantees the Employer shall be entitled subject to Sub-Clause 20.2 [Claims For Payment and/or EOT] to payment of these Performance Damages by the Contractor in full satisfaction of this failure.",
     {"entities": [(99, 119, "D-Damages")]}),
    ("Any VARIATION shall be governed by all the provisions of the CONTRACT.",
     {"entities": [(24, 33, "Governed")]}),
    ("the Contractor’s liability to the Company will instead be for general damages at law with the same maximum amount.",
     {"entities": [(86, 102, "D-Damages")]}),
    ("it may adversely affect the Contractor’s obligation to complete the Works so that they shall be fit for the purpose(s) for which they are intended.",
     {"entities": [(98, 117, "FFP")]}),
    ("Acceptance and payment by Company of any such Work or Materials shall not relieve Contractor of any liability to Company under this Contract",
    {"entities": [(101, 110, "Liability")]}),
    (" If the proceeds of sale are insufficient to pay such total costs and loss of profit as aforesaid, the BUYER shall promptly pay the deficiency to the BUILDER upon request.",
     {"entities": [(70, 85, "LOP")]}),
    ("when completed, not being fit for the use for which they are intended under Sub-Clause 4.1.",
     {"entities": [(26, 41, "FFP")]}),
    ("if such information is Excluded Work Document, it shall be Confidential Information and such disclosure shall be governed by Section 25.14.",
     {"entities": [(114, 123, "Governed")]}),
    ("worker's compensation and employer's liability insurance, unemployment compensation insurance, old age benefits, welfare funds, pensions and annuities, and disability insurance",
    {"entities": [(38, 47, "Liability")]}),
    ("Contractor shall be liable to Owner for all resulting from FLNG underperformance, provided always that the cap on total liability under Section 22.7.1, shall apply.",
     {"entities": [(107, 111, "CAP")]}),

]

@plac.annotations(
    model=("Model name. Defaults to blank 'en' model.", "option", "m", str),
    output_dir=("Optional output directory", "option", "o", Path),
    n_iter=("Number of training iterations", "option", "n", int),
)

def main(model='en_core_web_sm', output_dir=None, n_iter=100):
    """Load the model, set up the pipeline and train the entity recognizer."""
    if model is not None:
        nlp = spacy.load(model)  # load existing spaCy model
        print("Loaded model '%s'" % model)
    else:
        nlp = spacy.blank("en")
        print("Created blank 'en' model")

    if "ner" not in nlp.pipe_names:
        ner = nlp.create_pipe("ner")
        nlp.add_pipe(ner, last=True)

    else:
        ner = nlp.get_pipe("ner")

    # add labels
    for _, annotations in TRAIN_DATA:
        for ent in annotations.get("entities"):
            ner.add_label(ent[2])

    # get names of other pipes to disable them during training
    other_pipes = [pipe for pipe in nlp.pipe_names if pipe != "ner"]
    with nlp.disable_pipes(*other_pipes):  # only train NER
        if model is None:
            nlp.begin_training()
        for itn in range(n_iter):
            random.shuffle(TRAIN_DATA)
            losses = {}
            # batch up the examples using spaCy's minibatch
            batches = minibatch(TRAIN_DATA, size=compounding(4.0, 32.0, 1.001))
            for batch in batches:
                texts, annotations = zip(*batch)
                nlp.update(
                    texts,  # batch of texts
                    annotations,  # batch of annotations
                    drop=0.5,  # dropout - make it harder to memorise data
                    losses=losses,
                )
            print("Losses", losses)

    # test the trained model
    for text, _ in TRAIN_DATA:
        doc = nlp(text)
        print("Entities - ", [(ent.text, ent.label_) for ent in doc.ents])
        print("Tokens - ", [(t.text, t.ent_type_, t.ent_iob) for t in doc])

    # save model to output directory
    if output_dir is not None:
        output_dir = Path(output_dir)
        if not output_dir.exists():
            output_dir.mkdir()
        nlp.to_disk(output_dir)
        print("Saved model to", output_dir)

        # test the saved model
        print("Loading from", output_dir)
        nlp2 = spacy.load(output_dir)
        for text, _ in TRAIN_DATA:
            doc = nlp2(text)
            print("Entities - ", [(ent.text, ent.label_) for ent in doc.ents])
            print("Tokens - ", [(t.text, t.ent_type_, t.ent_iob) for t in doc])

label_ = ["FFP", "D-Damages", "LOP", "Governed", "CAP", "Penalty", "Consequential", "Limited", "Liability"]

@plac.annotations(new_model_name=("New model name for model meta.", "option", "nm", str))

def main(model='en_core_web_sm', new_model_name= label_, output_dir=None, n_iter=30):
    random.seed(0)
    if model is not None:
        nlp = spacy.load(model)  # load existing spaCy model
        print("Loaded model '%s'" % model)
    else:
        nlp = spacy.blank("en")  # create blank Language class
        print("Created blank 'en' model")
    # Add entity recognizer to model if it's not in the pipeline
    # nlp.create_pipe works for built-ins that are registered with spaCy
    if "ner" not in nlp.pipe_names:
        ner = nlp.create_pipe("ner")
        nlp.add_pipe(ner)
    # otherwise, get it, so we can add labels to it
    else:
        ner = nlp.get_pipe("ner")

    for LABEL in label_:
        ner.add_label(LABEL)  # add new entity label to entity recognizer

    if model is not None:
        optimizer = nlp.begin_training()
    else:
        optimizer = nlp.resume_training()
    move_names = list(ner.move_names)
    # get names of other pipes to disable them during training
    other_pipes = [pipe for pipe in nlp.pipe_names if pipe != "ner"]
    with nlp.disable_pipes(*other_pipes):  # only train NER
        sizes = compounding(1.0, 4.0, 1.001)
        # batch up the examples using spaCy's minibatch
        for itn in range(n_iter):
            random.shuffle(TRAIN_DATA)
            batches = minibatch(TRAIN_DATA, size=sizes)
            losses = {}
            for batch in batches:
                texts, annotations = zip(*batch)
                nlp.update(texts, annotations, sgd=optimizer, drop=0.35, losses=losses)
            print("Losses", losses)

    test_text = "Contractor warrants that the Plant will: (a) be fit for the purpose and use for which it was intended; (b) be free from defects in materials, design, construction and workmanship; and (c) comply with Applicable Laws. (a) Procurement and Supply : (i) Contractor must procure, manufacture, fabricate, supply and deliver all Contractor Items so as to ensure that the Work are performed in accordance with the Work Time Schedule, including performing all related operations such as testing, inspecting, packing, handling and transport and the like, necessary for carrying out the Work. (ii) All Contractor Items must: (A) be new and comply with the description, quality and quantity required by the Contract; (B) be of sound design, specification, materials and workmanship; (C) be capable of the degree of performance specified in the Contract; and (D) be fit for the purpose and use for which they were intended. If Contractor makes any change in breach of these provisions, then Company is entitled to apply as liquidated damages the amounts set out in Exhibit K.(e) Each Party acknowledges that the liquidated damages payable pursuant to sub-Article 26.1(d) are a genuine pre-estimate of Company loss and does not constitute a penalty. If the liquidated damages set out in Exhibit K are found not to be enforceable or the clauses in this Contract in relation to liquidated damages are found to be invalid or unenforceable for any reason, Contractor remains liable to Company for any loss or damage suffered by Company up to the amount of the relevant liquidated damages referred to in Exhibit K. (a) Contractor must provide all Construction Equipment necessary for the performance of the Work. Such Construction Equipment must be fit for the use it is intended for and maintained at all times in good operating condition with appropriate and uninterrupted valid certification in accordance with Applicable Laws and the Contract requirements. (a) Contractor acknowledges that time is of the utmost importance and that the completion of the Work by the Completion Date(s) is an essential condition of the Contract and of the overall Project development programme. Contractor must complete the Work, and each separate designated part of the Work, on or before the key dates and times for completion set out in the Work Time Schedule. (b) Contractor warrants that it will perform the Work in accordance with the Work Time Schedule, failing which Company has the remedies specified under the Contract, including those provided for under Article 51 and sub-Article 36.1 concerning defective performance by Contractor and liquidated damages for late completion. Subject to the provisions of sub-Article 20.3, if the results of the Performance Tests are within the range specified in Exhibit D, Company may either: (i) apply liquidated damages in accordance with the provisions of sub-Article 36.2. In such a case, Contractor is entitled to formally request the issuance of the Provisional Acceptance Certificate in accordance with the procedure defined in sub-Article 19.2(a); or (ii) request Contractor to promptly perform the necessary corrections in accordance with the provisions of sub-Article 19.2(e). If liquidated damages are found not to be payable or the Articles in this Contract in relation to liquidated damages are found to be invalid or unenforceable for any reason, then the Parties agree that Contractors liability to Company will instead be for general damages at law for Contractors failure to comply with the relevant obligation. If Contractor fails to complete the relevant part of the Work by the relevant Completion Date then Contractor will pay liquidated damages to Company in accordance with Exhibit B. (b) Subject to Company rights and remedies provided for under Article 35, sub-Articles 36.2 to 36.5 and Article 51, the payment of liquidated damages under sub-Article 36.1(a) are the sole and exclusive financial remedy of Company in respect of Contractors failure to complete the relevant part of the Work by the Completion Date. It is acknowledged and agreed by the Parties that  any sums that would be payable under this are in the nature of liquidated damages, and are not a penalty or consequential damages. If Company decides to apply liquidated damages, in accordance with the provisions of sub-Article 19.2(f) due to a failure of the Plant to achieve the Performance Tests, Contractor will pay to Company liquidated damages in accordance with Exhibit B. The payment of liquidated damages under this Article 36 or elsewhere in this Contract does not prevent Company from exercising any other rights and remedies provided for under this Contract (including for the avoidance of doubt its rights under sub-Article 35.3 and Article 51), and does not relieve Contractor from its obligations to diligently complete the Work or from any other obligations and liabilities under the Contract. Delay Damages also are not be deemed to cover the cost  of completion of the Works or other damages and Owner shall also been titled to rely on its other remedies under this Agreement for all Defaults. Contractor shall indemnify, hold harmless and defend each member of Owner Group from and against any and all claims, losses, damages (including consequential damages), liabilities, judgments, fines, costs and expenses (including arbitration and court procedures costs in any level of jurisdiction and experts’ and attorneys’ fees) and claims, demands, proceedings, actions,causes of action."
    doc = nlp(test_text)
    print('Entities', [(ent.text, ent.label_) for ent in doc.ents])

    #test_text = sent_tokenize(doc)
    #print("running nlp")
    print("Entities in - '%s'" % test_text, "-", [(ent.text, ent.label_) for ent in doc.ents] )

    #spacy.displacy.serve(doc, style='ent')
    print(spacy.displacy.render(doc, style="ent", page="true"))

    # ents = []
    # 
    # for ent in doc.ents:
    #     print(ent.label_,"-", ent.text)
    #     if ent.label in ents:
    #         ents.append(ents)
    #         risk_sentences = [sentence for sentence in sentences if ent.text in sentence]
    #         for sent in risk_sentences:
    #             print(sent)

    # save model to output directory
    if output_dir is not None:
        output_dir = Path(output_dir)
        if not output_dir.exists():
            output_dir.mkdir()
        nlp.meta["name"] = new_model_name  # rename model
        nlp.to_disk(output_dir)
        print("Saved model to", output_dir)

        # test the saved model
        print("Loading from", output_dir)
        nlp2 = spacy.load(output_dir)
        # Check the classes have loaded back consistently
        assert nlp2.get_pipe("ner").move_names == move_names
        doc2 = nlp2(text)
        for ent in doc2.ents:
            print(ent.label_, ent.text)

if __name__ == "__main__":
    plac.call(main)

## Your Environment

* Operating System: ubuntu 18.04
* Python Version Used: 2.7
* spaCy Version Used: how to check?
* Environment Information:

**Comment by svlandeg** [comment]
Hi, sorry to hear you're running into issues! It should be perfectly possible to train NER with multiple labels. I can't immediately figure out what's wrong with your code though. It's difficult to read 
as the formatting of the code blocks is not consist. Also, there seem to be duplicate code parts (e.g. two `main` methods, two code blocks adding labels, etc). Could you clean this up a bit to create a minimal working code snippet?

Also, could you provide some more information on what the exact issue is? You mention that it doesn't work, but does this mean that the training loss is not decreasing, or does it throw an error ... ? It may be helpful to include also your output here so we can have a better understanding of what may be going wrong.

**Comment by svlandeg** [comment]
Finally, I also noticed you're running Python 2.7. It's probably worth pointing out that the support for Python 2 will be dropped soon (https://pythonclock.org/) so you probably want to switch to a newer version of Python.

**Comment by naveenjafer** [comment]
@youikim I just had a look at the type of examples you have used for training, most of those are better suited to a phrase matcher rather than training the NLP model.

**Comment by youikim** [comment]
> @youikim I just had a look at the type of examples you have used for training, most of those are better suited to a phrase matcher rather than training the NLP model.

great thank you for letting me know. I will try applying a phrase matcher.

**Comment by youikim** [comment]
> Hi, sorry to hear you're running into issues! It should be perfectly possible to train NER with multiple labels. I can't immediately figure out what's wrong with your code though. It's difficult to read
> as the formatting of the code blocks is not consistent. Also, there seem to be duplicate code parts (e.g. two `main` methods, two code blocks adding labels, etc). Could you clean this up a bit to create a minimal working code snippet?
> 
> Also, could you provide some more information on what the exact issue is? You mention that it doesn't work, but does this mean that the training loss is not decreasing, or does it throw an error ... ? It may be helpful to include also your output here so we can have a better understanding of what may be going wrong.

Thank you for your reply. I worked it out with couple of new lines. I dont know how to edit the code for better looking...

**Comment by 2Max4** [comment]
@youikim would you mind sharing your final solution since have some issues concerning multi label ner training, too....;) Greetings
