### ISSUE TITLE
Segmentation fault during model download (Spacy-2.2.3)

### ISSUE THREAD

**Issue by mike94043** [explosion/spaCy#4838]
## How to reproduce the problem

mkg@vicky:~$ python3 -m spacy download de
Collecting de_core_news_sm==2.2.5 from https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-2.2.5/de_core_news_sm-2.2.5.tar.gz#egg=de_core_news_sm==2.2.5
  Downloading https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-2.2.5/de_core_news_sm-2.2.5.tar.gz (14.9MB)
    100% |████████████████████████████████| 14.9MB 8.1MB/s 
Collecting spacy>=2.2.2 (from de_core_news_sm==2.2.5)
  Downloading https://files.pythonhosted.org/packages/47/13/80ad28ef7a16e2a86d16d73e28588be5f1085afd3e85e4b9b912bd700e8a/spacy-2.2.3-cp36-cp36m-manylinux1_x86_64.whl (10.4MB)
    100% |████████████████████████████████| 10.4MB 6.7MB/s 
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy>=2.2.2->de_core_news_sm==2.2.5)
  Downloading https://files.pythonhosted.org/packages/a6/e6/63f160a4fdf0e875d16b28f972083606d8d54f56cd30cb8929f9a1ee700e/murmurhash-1.0.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting numpy>=1.15.0 (from spacy>=2.2.2->de_core_news_sm==2.2.5)
  Downloading https://files.pythonhosted.org/packages/92/e6/45f71bd24f4e37629e9db5fb75caab919507deae6a5a257f9e4685a5f931/numpy-1.18.0-cp36-cp36m-manylinux1_x86_64.whl (20.1MB)
    100% |████████████████████████████████| 20.1MB 7.6MB/s 
Collecting catalogue<1.1.0,>=0.0.7 (from spacy>=2.2.2->de_core_news_sm==2.2.5)
  Downloading https://files.pythonhosted.org/packages/4b/4c/0e0fa8b1e193c1e09a6b72807ff4ca17c78f68f0c0f4459bc8043c66d649/catalogue-0.2.0-py2.py3-none-any.whl
Collecting requests<3.0.0,>=2.13.0 (from spacy>=2.2.2->de_core_news_sm==2.2.5)
  Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 2.2MB/s 
Collecting setuptools (from spacy>=2.2.2->de_core_news_sm==2.2.5)
  Downloading https://files.pythonhosted.org/packages/54/28/c45d8b54c1339f9644b87663945e54a8503cfef59cf0f65b3ff5dd17cf64/setuptools-42.0.2-py2.py3-none-any.whl (583kB)
    100% |████████████████████████████████| 583kB 6.4MB/s 
Collecting blis<0.5.0,>=0.4.0 (from spacy>=2.2.2->de_core_news_sm==2.2.5)
  Downloading https://files.pythonhosted.org/packages/41/19/f95c75562d18eb27219df3a3590b911e78d131b68466ad79fdf5847eaac4/blis-0.4.1-cp36-cp36m-manylinux1_x86_64.whl (3.7MB)
    100% |████████████████████████████████| 3.7MB 8.0MB/s 
Collecting thinc<7.4.0,>=7.3.0 (from spacy>=2.2.2->de_core_news_sm==2.2.5)
  Downloading https://files.pythonhosted.org/packages/07/59/6bb553bc9a5f072d3cd479fc939fea0f6f682892f1f5cff98de5c9b615bb/thinc-7.3.1-cp36-cp36m-manylinux1_x86_64.whl (2.2MB)
    100% |████████████████████████████████| 2.2MB 9.0MB/s 
Collecting cymem<2.1.0,>=2.0.2 (from spacy>=2.2.2->de_core_news_sm==2.2.5)
  Downloading https://files.pythonhosted.org/packages/e7/b5/3e1714ebda8fd7c5859f9b216e381adc0a38b962f071568fd00d67e1b1ca/cymem-2.0.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting wasabi<1.1.0,>=0.4.0 (from spacy>=2.2.2->de_core_news_sm==2.2.5)
  Downloading https://files.pythonhosted.org/packages/ff/ef/e8266e158ed32bf5f723fac862b6518833d0b53ca183165a8718f212c0d5/wasabi-0.4.2-py3-none-any.whl
Collecting srsly<1.1.0,>=0.1.0 (from spacy>=2.2.2->de_core_news_sm==2.2.5)
  Downloading https://files.pythonhosted.org/packages/d7/fb/34136c7b2ad04d4472dd9ea86536f5e9fb71fb0eb78edc8dad76a3f9edf2/srsly-0.2.0-cp36-cp36m-manylinux1_x86_64.whl (185kB)
    100% |████████████████████████████████| 194kB 14.3MB/s 
Collecting preshed<3.1.0,>=3.0.2 (from spacy>=2.2.2->de_core_news_sm==2.2.5)
  Downloading https://files.pythonhosted.org/packages/db/6b/e07fad36913879757c90
ba03d6fb7f406f7279e11dcefc105ee562de63ea/preshed-3.0.2-cp36-cp36m-manylinux1_x86_64.whl (119kB)
    100% |████████████████████████████████| 122kB 4.8MB/s 
Collecting plac<1.2.0,>=0.9.6 (from spacy>=2.2.2->de_core_news_sm==2.2.5)
  Downloading https://files.pythonhosted.org/packages/86/85/40b8f66c2dd8f4fd9f09d59b22720cffecf1331e788b8a0cab5bafb353d1/plac-1.1.3-py2.py3-none-any.whl
Collecting importlib-metadata>=0.20; python_version < "3.8" (from catalogue<1.1.0,>=0.0.7->spacy>=2.2.2->de_core_news_sm==2.2.5)
  Downloading https://files.pythonhosted.org/packages/e9/71/1a1e0ed0981bb6a67bce55a210f168126b7ebd2065958673797ea66489ca/importlib_metadata-1.3.0-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests<3.0.0,>=2.13.0->spacy>=2.2.2->de_core_news_sm==2.2.5)
  Downloading https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl (156kB)
    100% |████████████████████████████████| 163kB 9.3MB/s 
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests<3.0.0,>=2.13.0->spacy>=2.2.2->de_core_news_sm==2.2.5)
  Downloading https://files.pythonhosted.org/packages/b4/40/a9837291310ee1ccc242ceb6ebfd9eb21539649f193a7c8c86ba15b98539/urllib3-1.25.7-py2.py3-none-any.whl (125kB)
    100% |████████████████████████████████| 133kB 4.9MB/s 
Collecting idna<2.9,>=2.5 (from requests<3.0.0,>=2.13.0->spacy>=2.2.2->de_core_news_sm==2.2.5)
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 17.3MB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests<3.0.0,>=2.13.0->spacy>=2.2.2->de_core_news_sm==2.2.5)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 10.7MB/s 
Collecting tqdm<5.0.0,>=4.10.0 (from thinc<7.4.0,>=7.3.0->spacy>=2.2.2->de_core_news_sm==2.2.5)
  Downloading https://files.pythonhosted.org/packages/8c/c3/d049cf3fb31094ee045ec1ee29fffac218c91e82c8838c49ab4c3e52627b/tqdm-4.41.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 63.0MB/s 
Collecting zipp>=0.5 (from importlib-metadata>=0.20; python_version < "3.8"->catalogue<1.1.0,>=0.0.7->spacy>=2.2.2->de_core_news_sm==2.2.5)
  Downloading https://files.pythonhosted.org/packages/74/3d/1ee25a26411ba0401b43c6376d2316a71addcc72ef8690b101b4ea56d76a/zipp-0.6.0-py2.py3-none-any.whl
Collecting more-itertools (from zipp>=0.5->importlib-metadata>=0.20; python_version < "3.8"->catalogue<1.1.0,>=0.0.7->spacy>=2.2.2->de_core_news_sm==2.2.5)
  Downloading https://files.pythonhosted.org/packages/68/03/0604cec1ea13c9f063dd50f900d1a36160334dd3cfb01fd0e638f61b46ba/more_itertools-8.0.2-py3-none-any.whl (40kB)
    100% |████████████████████████████████| 40kB 51.5MB/s 
Installing collected packages: murmurhash, numpy, more-itertools, zipp, importlib-metadata, catalogue, certifi, urllib3, idna, chardet, requests, setuptools, blis, cymem, preshed, srsly, tqdm, wasabi, plac, thinc, spacy, de-core-news-sm
  Running setup.py install for de-core-news-sm ... done
Successfully installed blis-0.4.1 catalogue-0.2.0 certifi-2019.11.28 chardet-3.0.4 cymem-2.0.3 de-core-news-sm-2.2.5 idna-2.8 importlib-metadata-1.3.0 more-itertools-8.0.2 murmurhash-1.0.2 numpy-1.18.0 plac-1.1.3 preshed-3.0.2 requests-2.22.0 setuptools-42.0.2 spacy-2.2.3 srsly-0.2.0 thinc-7.3.1 tqdm-4.41.0 urllib3-1.25.7 wasabi-0.4.2 zipp-0.6.0
✔ Download and installation successful
You can now load the model via spacy.load('de_core_news_sm')
Segmentation fault (core dumped)

(Also happens with python3 -m spacy download en)

# Segmentation fault (core dumped)
```

## Your Environment
<!-- Include details of your environment. If you're using spaCy 1.7+, you can also type `python -m spacy info --markdown` and copy-paste the result here.-->

mkg@vicky:~$ python3 -m spacy info --markdown

## Info about spaCy

* **spaCy version:** 2.2.3
* **Platform:** Linux-5.0.0-37-generic-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.6.9

* Environment Information:

mkg@vicky:~$ uname -a
Linux vicky 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by svlandeg** [comment]
Hmm, I'm not sure what's going on here, but I would advise to first install spaCy in a clean environment with `pip install spacy` (see https://github.com/explosion/spaCy/#install-spacy) and only after that went succesfully, try downloading the `de` model. Could you give that a try and post the log here? That will help us understand whether the issue is with the model installation, or with the spaCy installation.

**Comment by svlandeg** [comment]
And the other thing you could try if you still get an error, is to run `python -m spacy download de_core_news_sm` which would avoid symlink problems linking `de` to `de_core_news_sm`.

**Comment by mike94043** [comment]
So,
mkg@vicky:~$ python3 -m spacy download de_core_news_sm
doesn't do the trick:

Successfully installed blis-0.4.1 catalogue-0.2.0 certifi-2019.11.28
chardet-3.0.4 cymem-2.0.3 de-core-news-sm-2.2.5 idna-2.8
importlib-metadata-1.3.0 more-itertools-8.0.2 murmurhash-1.0.2 numpy-1.18.0
plac-1.1.3 preshed-3.0.2 requests-2.22.0 setuptools-42.0.2 spacy-2.2.3
srsly-0.2.0 thinc-7.3.1 tqdm-4.41.0 urllib3-1.25.7 wasabi-0.5.0 zipp-0.6.0
✔ Download and installation successful
You can now load the model via spacy.load('de_core_news_sm')
Segmentation fault (core dumped)

**Comment by mike94043** [comment]
> Hmm, I'm not sure what's going on here, but I would advise to first install spaCy in a clean environment with `pip install spacy` (see https://github.com/explosion/spaCy/#install-spacy) and only after that went succesfully, try downloading the `de` model. Could you give that a try and post the log here? That will help us understand whether the issue is with the model installation, or with the spaCy installation.

So, created a new users, tried a pip install spacy, but... that failed because

    Best match: numpy 1.18.0
    Processing numpy-1.18.0.zip
    Writing /tmp/easy_install-wgBUEx/numpy-1.18.0/setup.cfg
    Running numpy-1.18.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-wgBUEx/numpy-1.18.0/egg-dist-tmp-zHai7C
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ouDIdf/spacy/setup.py", line 200, in <module>
        setup_package()
      File "/tmp/pip-build-ouDIdf/spacy/setup.py", line 195, in setup_package
        cmdclass={"build_ext": build_ext_subclass},
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
[...]
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-wgBUEx/numpy-1.18.0/setup.py", line 31, in <module>
    
    RuntimeError: Python version >= 3.5 required.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ouDIdf/spacy/

So, on to pip3 install spacy which worked successfully as before, but 
test@vicky:~$ python3 -m spacy download de

still fails as before:
[...]
✔ Download and installation successful
You can now load the model via spacy.load('de_core_news_sm')
Segmentation fault (core dumped)

So does
# python3 -m spacy download de_core_news_sm
[...]
✔ Download and installation successful
You can now load the model via spacy.load('de_core_news_sm')
Segmentation fault (core dumped)

**Comment by mike94043** [comment]
I'm hoping this strace might give more insight to those that are familiar with the spacy internals?

[...]

  Running setup.py install for de-core-news-sm ... done
Successfully installed blis-0.4.1 catalogue-0.2.0 certifi-2019.11.28 chardet-3.0.4 cymem-2.0.3 de-core-news-sm-2.2.5 idna-2.8 importlib-metadata-1.3.0 more-itertools-8.0.2 murmurhash-1.0.2 numpy-1.18.0 plac-1.1.3 preshed-3.0.2 requests-2.22.0 setuptools-43.0.0 spacy-2.2.3 srsly-0.2.0 thinc-7.3.1 tqdm-4.41.1 urllib3-1.25.7 wasabi-0.5.0 zipp-0.6.0
[{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 26073
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=26073, si_uid=1000, si_status=0, si_utime=742, si_stime=113} ---
write(1, "\33[38;5;2m\342\234\224 Download and instal"..., 114✔ Download and installation successful
You can now load the model via spacy.load('de_core_news_sm')) = 114
write(1, "\n", 1
)                       = 1
getcwd("/home/mkg/nlp", 1024)           = 14
stat("/home/mkg/nlp", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
stat("/usr/lib/python3.6", {st_mode=S_IFDIR|0755, st_size=20480, ...}) = 0
stat("/usr/lib/python3.6/lib-dynload", {st_mode=S_IFDIR|0755, st_size=12288, ...}) = 0
stat("/home/mkg/.local/lib/python3.6/site-packages", {st_mode=S_IFDIR|0700, st_size=12288, ...}) = 0
openat(AT_FDCWD, "/home/mkg/.local/lib/python3.6/site-packages", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
fstat(3, {st_mode=S_IFDIR|0700, st_size=12288, ...}) = 0
getdents(3, /* 245 entries */, 32768)   = 10048
getdents(3, /* 0 entries */, 32768)     = 0
close(3)                                = 0
stat("/home/mkg/.local/lib/python3.6/site-packages/de_core_news_sm/__init__.cpython-36m-x86_64-linux-gnu.so", 0x7fffc1f91fc0) = -1 ENOENT (No such file or directory)
stat("/home/mkg/.local/lib/python3.6/site-packages/de_core_news_sm/__init__.abi3.so", 0x7fffc1f91fc0) = -1 ENOENT (No such file or directory)
stat("/home/mkg/.local/lib/python3.6/site-packages/de_core_news_sm/__init__.so", 0x7fffc1f91fc0) = -1 ENOENT (No such file or directory)
stat("/home/mkg/.local/lib/python3.6/site-packages/de_core_news_sm/__init__.py", {st_mode=S_IFREG|0664, st_size=291, ...}) = 0
stat("/home/mkg/.local/lib/python3.6/site-packages/de_core_news_sm/__init__.py", {st_mode=S_IFREG|0664, st_size=291, ...}) = 0
openat(AT_FDCWD, "/home/mkg/.local/lib/python3.6/site-packages/de_core_news_sm/__pycache__/__init__.cpython-36.pyc", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0664, st_size=503, ...}) = 0
lseek(3, 0, SEEK_CUR)                   = 0
fstat(3, {st_mode=S_IFREG|0664, st_size=503, ...}) = 0
read(3, "3\r\r\n:7\313]#\1\0\0\343\0\0\0\0\0\0\0\0\0\0\0\0\3\0\0\0@\0\0"..., 504) = 503
read(3, "", 1)                          = 0
close(3)                                = 0
stat("/home/mkg/.local/lib/python3.6/site-packages/de_core_news_sm", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
stat("/home/mkg/.local/lib/python3.6/site-packages/de_core_news_sm/meta.json", {st_mode=S_IFREG|0664, st_size=2909, ...}) = 0
stat("/home/mkg/.local/lib/python3.6/site-packages/de_core_news_sm/meta.json", {st_mode=S_IFREG|0664, st_size=2909, ...}) = 0
openat(AT_FDCWD, "/home/mkg/.local/lib/python3.6/site-packages/de_core_news_sm/meta.json", O_RDONLY|O_CLOEXEC) = 3
ioctl(3, FIOCLEX)                       = 0
fstat(3, {st_mode=S_IFREG|0664, st_size=2909, ...}) = 0
ioctl(3, TCGETS, 0x7fffc1f91eb0)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(3, 0, SEEK_CUR)                   = 0
lseek(3, 0, SEEK_CUR)                   = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
mkg@vicky:~/nlp$

**Comment by iabd** [comment]
Hi @mike94043 , 
you probably need to sudo the download of spacy. 
eg. 
`sudo python3 -m spacy download de` should do it

**Comment by iabd** [comment]
Hi @mike94043 
You probably need to sudo the download.
eg. 
`sudo python3 -m spacy download de` should do it.

**Comment by mike94043** [comment]
@iabd Thanks for the suggestion.  That did indeed fix it.  Thanks so much! 

I wonder why though?  The installation is local in my homedir, so shouldn't need extra permissions?

Also, the instructions given everywhere don't suggest the need for sudo, so at least need updated docs?

Finally, SIGSEGV is never OK for an app (unless it's some version of abort() or such), so I've also submitted an ubuntu one to have somebody have a look at why python segfaults?

------------- snip ---------------------------
mkg@vicky:~/nlp $ sudo python3 -m spacy download de
[sudo] password for mkg: 
Requirement already satisfied: de_core_news_sm==2.2.5 from https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-2.2.5/de_core_news_sm-2.2.5.tar.gz#egg=de_core_news_sm==2.2.5 in /home/mkg/.local/lib/python3.6/site-packages
Requirement already satisfied: spacy>=2.2.2 in /home/mkg/.local/lib/python3.6/site-packages (from de_core_news_sm==2.2.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /home/mkg/.local/lib/python3.6/site-packages (from spacy>=2.2.2->de_core_news_sm==2.2.5)

[...]

Requirement already satisfied: importlib-metadata>=0.20; python_version < "3.8" in /home/mkg/.local/lib/python3.6/site-packages (from catalogue<1.1.0,>=0.0.7->spacy>=2.2.2->de_core_news_sm==2.2.5)
Requirement already satisfied: zipp>=0.5 in /home/mkg/.local/lib/python3.6/site-packages (from importlib-metadata>=0.20; python_version < "3.8"->catalogue<1.1.0,>=0.0.7->spacy>=2.2.2->de_core_news_sm==2.2.5)
Requirement already satisfied: more-itertools in /home/mkg/.local/lib/python3.6/site-packages (from zipp>=0.5->importlib-metadata>=0.20; python_version < "3.8"->catalogue<1.1.0,>=0.0.7->spacy>=2.2.2->de_core_news_sm==2.2.5)
✔ Download and installation successful
You can now load the model via spacy.load('de_core_news_sm')
✔ Linking successful
/home/mkg/.local/lib/python3.6/site-packages/de_core_news_sm -->
/home/mkg/.local/lib/python3.6/site-packages/spacy/data/de
You can now load the model via spacy.load('de')

**Comment by iabd** [comment]
> @iabd Thanks for the suggestion. That did indeed fix it. Thanks so much!
> 
> I wonder why though? The installation is local in my homedir, so shouldn't need extra permissions?
> 
> Also, the instructions given everywhere don't suggest the need for sudo, so at least need updated docs?
> 
> Finally, SIGSEGV is never OK for an app (unless it's some version of abort() or such), so I've also submitted an ubuntu one to have somebody have a look at why python segfaults?
> 
> ------------- snip ---------------------------
> mkg@vicky:~/nlp $ sudo python3 -m spacy download de
> [sudo] password for mkg:
> Requirement already satisfied: de_core_news_sm==2.2.5 from https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-2.2.5/de_core_news_sm-2.2.5.tar.gz#egg=de_core_news_sm==2.2.5 in /home/mkg/.local/lib/python3.6/site-packages
> Requirement already satisfied: spacy>=2.2.2 in /home/mkg/.local/lib/python3.6/site-packages (from de_core_news_sm==2.2.5)
> Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /home/mkg/.local/lib/python3.6/site-packages (from spacy>=2.2.2->de_core_news_sm==2.2.5)
> 
> [...]
> 
> Requirement already satisfied: importlib-metadata>=0.20; python_version < "3.8" in /home/mkg/.local/lib/python3.6/site-packages (from catalogue<1.1.0,>=0.0.7->spacy>=2.2.2->de_core_news_sm==2.2.5)
> Requirement already satisfied: zipp>=0.5 in /home/mkg/.local/lib/python3.6/site-packages (from importlib-metadata>=0.20; python_version < "3.8"->catalogue<1.1.0,>=0.0.7->spacy>=2.2.2->de_core_news_sm==2.2.5)
> Requirement already satisfied: more-itertools in /home/mkg/.local/lib/python3.6/site-packages (from zipp>=0.5->importlib-metadata>=0.20; python_version < "3.8"->catalogue<1.1.0,>=0.0.7->spacy>=2.2.2->de_core_news_sm==2.2.5)
> ✔ Download and installation successful
> You can now load the model via spacy.load('de_core_news_sm')
> ✔ Linking successful
> /home/mkg/.local/lib/python3.6/site-packages/de_core_news_sm -->
> /home/mkg/.local/lib/python3.6/site-packages/spacy/data/de
> You can now load the model via spacy.load('de')

Its not python but low level C which is signaling SigSegV. Its  a signal for trying to read/write memory that you do not have access to. 
Some possible reasons include
- Using uninitialized pointer
- De-referencing a NULL pointer
- Trying to access memory which is already de-allocated (dangling pointers) etc.
- Trying to access memory that the program doesn’t own 

In your case, I believe it was trying to write a file/directory which it could read but couldn't write due to permission issues or something similar.  It happens when python installation is messed up. But it's just my guess on your case.

**Comment by svlandeg** [comment]
Thanks for the help @iabd, and happy to hear this got resolved !
