### ISSUE TITLE
Pre-trained Vectors are not stored with pickling + saving then loading + un-pickling trained model

### ISSUE THREAD

**Issue by acherednychenko** [explosion/spaCy#4841]
1. Pre-train model with vectors
2. Train and pickle model. Save to file
3. Load from file, unpickle model, call predict:

```OSError: [E050] Can't find model 'en_core_web_md.vectors'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.```

## Your Environment
* **spaCy version:** 2.2.3
* **Platform:** Linux-4.14.154-128.181.amzn2.x86_64-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.9

Please assist

**Comment by adrianeboyd** [comment]
I'm not sure why you're running into this error with pickle (possibly different versions of spacy used when pickling and unpickling?), but spacy has its own internal serialization methods that are easy to use. You can save a model with `Language.to_disk()` and use `spacy.load()` to load the saved model:

```
nlp = spacy.load("en_core_web_md")
nlp.to_disk("/path/to/model")
nlp_reloaded = spacy.load("/path/to/model")
assert nlp.to_bytes() == nlp_reloaded.to_bytes()
```

Pickling should also work, though. What are the exact steps you're using to pickle / unpickle / predict?
