### ISSUE TITLE
''Empty label found in new labels" with `spacy debug-data` and Prodigy

### ISSUE THREAD

**Issue by kormilitzin** [explosion/spaCy#4845]
I was annotating with Prodigy (`ner.make-gold`, 7 categories), and when wanted to validate the training dataset, got the following error:

![Screenshot 2019-12-28 at 22 37 50](https://user-images.githubusercontent.com/20815939/71550241-3606d380-29c3-11ea-983a-5fce7815478b.png)

That's a bit strange, as I haven't missed tokens and used labels from the list. Moreover, I have explicitly checked, and none of the labels in the annotated examples, contains the empty label (`' '`).
Is it possible to introduce an automated way to remove such empty labels in future releases? It will be very helpful. 

Is there a simple solution to remove such labels from the data? Thanks.

**Comment by svlandeg** [comment]
Sorry to hear you're running into problems with this! 

Could you share the prodigy and spacy commands you ran for annotating & converting your dataset?

**Comment by adrianeboyd** [comment]
The empty label is an empty string, not a space. Could you look for the label `""` in your input to `spacy debug-data`? It would probably look like `"ner":""` or `"ner": ""` in the spacy JSON training format.

Is there anything unusual about those tokens that might help explain how they ended up with empty labels in prodigy? (Token includes whitespace, tokenization looks weird, etc.?)

What are the exact steps you used to convert the data from prodigy?
