### ISSUE TITLE
Error handling with nlp.pipe

### ISSUE THREAD

**Issue by AlJohri** [explosion/spaCy#4847]
I'm using `nlp.pipe` (with multiple processes) in the latest spaCy (master branch) and having trouble doing proper error handling in a generator.

I have a custom pipeline component which occasionally errors on some documents with `ValueError: [E103] Trying to set conflicting doc.ents: '(1387, 1388, 'PERSON')' and '(1387, 1388, 'PERSON')'. A token can only be part of one entity, so make sure the entities you're setting don't overlap.`.

#### Issue

1) I can't easily figure out which document ID caused the issue since my custom pipeline components doesn't have access to the `context`. The `context` is provided to `nlp.pipe` via the `as_tuples=True` argument.

    ```python
    gen = tqdm(
        nlp.pipe(zip(df.text, df.id), as_tuples=True, batch_size=10, n_process=16),
        total=len(df),
    )
    ```

2) I can't figure out how to ignore the exception and continue processing since it doesn't seem like there's an easy way to catch the error and continue the generator, especially in a multiprocessing setting.

#### Potential Solution

Can we add an `ignore_exceptions=True, error_handler=callable` which allows ignoring exceptions and running some error handler function that has access to the `handler(error, doc, context)`?

#### Info about spaCy

* **spaCy version:** 2.2.3
* **Platform:** Darwin-18.7.0-x86_64-i386-64bit
* **Python version:** 3.7.5

**Comment by adrianeboyd** [comment]
General error handling is a larger issue that should be addressed, but to avoid the immediate `ValueError [E103]` above in your custom component, you can use `util.filter_spans()` to filter out overlapping spans before setting entities: https://spacy.io/api/top-level#util.filter_spans

**Comment by AlJohri** [comment]
Thanks- I think for my particular use case I might need to keep the entities separate. Once I get my hands on the offending document, I'll know more.

I also have highly varying sizes of documents in my list. In terms of number of characters:

```
count     40389.000000
mean      15318.084256
std       16388.481913
min           1.000000
25%        4220.000000
50%        7209.000000
75%       22718.000000
max      242799.000000
Name: length, dtype: float64
```

I keep lowering the batch size on each invocation but I keep running into:

```
MemoryError: Unable to allocate 542. MiB for an array with shape (142106, 1000) and data type float32
```

I am now trying a batch size of 1 even though I'm running on a fairly beefy c5.4xlarge machine (16 cpu, 32gb ram).

I think it might make sense to change `batch_size` to be in bytes instead of number of documents? That way the library can determine how many documents to do based on the size in memory.

**Comment by AlJohri** [comment]
@adrianeboyd ah, I read the error wrong- I didn't realize those were exactly the same token, not adjacent spans. that method will work great- thanks!

**Comment by svlandeg** [comment]
Assuming the original issue got addressed, I'll close this for now :-)

**Comment by AlJohri** [comment]
@svlandeg what do you think of the Potential Solution I listed above? This fixed the particular error I was getting but not error handling in general.

**Comment by svlandeg** [comment]
I think you're right that in general, the error handling for multiprocessing can be improved. This feature is relatively new (2.2.2) so it will definitely be made more robust in the future. If you feel like contributing with a PR, that would be great!

**Comment by AlJohri** [comment]
@svlandeg yes, I'm interested in submitting a PR. I wanted to confirm my approach before moving forward. What do you think of the following API?

```python
def handler(e, doc):
    print("ERROR", e, doc)

nlp.pipe(docs, ignore_exceptions=True, error_handler=handler)
```

**Comment by svlandeg** [comment]
I don't think you need a `ignore_exceptions` flag if you can specify a handler? You can just have the handler ignore things, if that's what you really want?
