### ISSUE TITLE
spaCy on macOS is slower than Linux?

### ISSUE THREAD

**Issue by rivamarco** [explosion/spaCy#4848]
I'm using spaCy for NER Training for adding a new entity type.

My initial setup was Manjaro Linux on a Dell Latitude laptop with an Intel i5-5300u and 16GB of RAM, and after one iteration of my data using spacy train en output train.json validation.json -p ner I obtained ~16000 CPU WPS with 100% CPU usage (on one core only).

## Info about spaCy

* **spaCy version:** 2.2.3
* **Platform:** Linux-4.19.88-1-MANJARO-x86_64-with-glibc2.2.5
* **Python version:** 3.8.0
* **Models:** en

(same results with python 3.7.6)

I moved this project (same training files, same python packages, all the same) on a MacBook Pro 15 2015 with i7 2.2Ghz (should be i7-4770HQ) 16GB and macOS Catalina.

## Info about spaCy

* **spaCy version:** 2.2.3
* **Platform:** Darwin-19.2.0-x86_64-i386-64bit
* **Python version:** 3.7.6
* **Models:** en

Now with this configuration, I obtain ~13000 CPU WPS with the CPU that is far away to reach the 100% mark, even on a single-core, like the Dell with Linux.

I think that with the MacBook's CPU I have to get better results (maybe only a little), am I wrong? Is this the correct behavior or for macOS there is something that I have to keep in mind?

Thank you for your help

**Comment by adrianeboyd** [comment]
Hi, there are so many different factors here, both hardware and OS-related, that some small differences in speed aren't too surprising, even if it's not what you might expect just from the CPUs. (It might be faster with linux on the macbook, if that's something you'd want to try!)
