### ISSUE TITLE
Tokens aren't added to the vocab in the same way in models with and without vectors

### ISSUE THREAD

**Issue by adrianeboyd** [explosion/spaCy#4856]
## How to reproduce the behaviour

When a model has vectors (?) previously unseen tokens are not added to the vocab in the same way. They are added to the `StringStore` but not the vocab. I'm not sure this has any problematic side effects in typical usage, but I suspect it's a bug that it's inconsistent. The results with the small model are what I expected to happen for all three.

```python
import spacy

def test_process_unseen_vocab(model, token):
    nlp = spacy.load(model)
    print(model, "\n==============")
    print("vocab length:", len(nlp.vocab))
    print(token, "in vocab:", token in nlp.vocab)
    print("processing text...", nlp(token))
    print("vocab length:", len(nlp.vocab))
    print(token, "in vocab:", token in nlp.vocab)
    print(token, "in vocab.strings:", token in nlp.vocab.strings)
    print()
    
for model in ["en_core_web_sm", "en_core_web_md", "en_core_web_lg"]:
    test_process_unseen_vocab(model, "asdfasdfasdf")
```

Output:

```
en_core_web_sm 
==============
vocab length: 478
asdfasdfasdf in vocab: False
processing text... asdfasdfasdf
vocab length: 479
asdfasdfasdf in vocab: True
asdfasdfasdf in vocab.strings: True

en_core_web_md 
==============
vocab length: 1340242
asdfasdfasdf in vocab: False
processing text... asdfasdfasdf
vocab length: 1340242
asdfasdfasdf in vocab: False
asdfasdfasdf in vocab.strings: True

en_core_web_lg 
==============
vocab length: 1340242
asdfasdfasdf in vocab: False
processing text... asdfasdfasdf
vocab length: 1340242
asdfasdfasdf in vocab: False
asdfasdfasdf in vocab.strings: True
```

## Your Environment

* **spaCy version:** 2.2.3
* **Platform:** Linux-5.3.0-0.bpo.2-amd64-x86_64-with-debian-10.2
* **Python version:** 3.7.3

**Comment by honnibal** [comment]
Agree it's confusing, but I don't think it's literally a bug.

The `Vocab` adds unseen entries up to a certain vocab size, and then stops. So in the small model, the vocab starts out small, and new entries are saved into the vocab. But for models with vectors, the vocab is already large enough, and new entries are only saved in the string store.

**Comment by adrianeboyd** [comment]
`nlp.vocab["asdfasdfasdf"]` adds a lexeme no matter what but `nlp("asdfasdfasdf")` doesn't. That is confusing...
