### ISSUE TITLE
Spacy Entity Linking model for NER

### ISSUE THREAD

**Issue by zainbnv** [explosion/spaCy#4859]
I wanted to use the spacy entity linking model with the version spacy==2.0.11. I just want the NER from this model, not the linking. I am getting this error 
KeyError: "[E002] Can't find factory for 'entity_linker'. This usually happens when spaCy calls `nlp.create_pipe` with a component name that's not built in - for example, when constructing the pipeline from a model's meta.json. If you're using a custom component, you can write to `Language.factories['entity_linker']` or remove it from the model meta and add it via `nlp.add_pipe` instead."
Although I have used this entity linking model on a newer version of spacy but my deployment server is having some prodigy based model trained on older version.Is there a way I can use this with previous version?
## Info about spaCy

* **spaCy version:** 2.0.18
* **Platform:** Windows-10-10.0.17134-SP0
* **Python version:** 3.6.5

**Comment by zainbnv** [comment]
<!-- I wanted to use the spacy entity linking model with the version spacy==2.0.11. I just want the NER from this model, not the linking. I am getting this error 
KeyError: "[E002] Can't find factory for 'entity_linker'. This usually happens when spaCy calls `nlp.create_pipe` with a component name that's not built in - for example, when constructing the pipeline from a model's meta.json. If you're using a custom component, you can write to `Language.factories['entity_linker']` or remove it from the model meta and add it via `nlp.add_pipe` instead."
Although I have used this entity linking model on a newer version of spacy but my deployment server is having some prodigy based model trained on older version.Is there a way I can use this with previous version?
## Your Environment

## Info about spaCy

* **spaCy version:** 2.0.18
* **Platform:** Windows-10-10.0.17134-SP0
* **Python version:** 3.6.5

**Comment by svlandeg** [comment]
Hi @zainbnv, I assume this is a model you've created and trained yourself, on a newer version of spaCy? Unfortunately you won't be able to use this model (I assume you wrote it to disk) in an older version of spaCy. 

First off, like the error message suggests, the `entity_linking` component was not yet implemented in 2.0.11 so spaCy has no idea how to recreate this from file. In general, you could get around this by only saving the original NER model [to disk](https://spacy.io/api/language#to_disk) while [disabling](https://spacy.io/api/language#disable_pipes) the `entity_linking` pipe, and [loading](https://spacy.io/api/language#from_disk) that in. 

However, note that it is possible that even the NER model might not work with the older spaCy version on your deployment server. You haven't mentioned which spaCy version the model was trained on, but there could be incompatibilities with 2.0.X. Sometimes when we publish a major new release of spaCy, the underlying codebase has changed so much that it is actually required to retrain your models for the new version. See e.g. for the release of 2.2, https://spacy.io/usage/v2-2#incompat 

> If you’ve been training your own models, you’ll need to retrain them with the new version. Also don’t forget to upgrade all models to the latest versions. Models for v2.0 or v2.1 aren’t compatible with models for v2.2. To check if all of your models are up to date, you can run the spacy validate command.
