### ISSUE TITLE
Noun Phrase Matcher implementation

### ISSUE THREAD

**Issue by naveenjafer** [explosion/spaCy#4860]
## Feature description
Noun Phrase Matcher as a part of the Doc object.

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
Source code change?

I had come across a previous enhancement request for Verb phrase matcher request in SpaCy. While tinkering with the existing noun phrase matcher, I had come across a few sources that show how noun phrase matching is generally done(http://www.nltk.org/book_1ed/ch07.html#ref-chunkex-grammar). While the implementation in NLTK and few other resources I found is a fairly simple grammar rule such as DT?JJ*NN. I could see that the implementation in spacy was different. In fact the simple example of "Autonomous cars shift insurance liability toward manufacturers" gives three noun phrases according to the spacy implementation - 

1. Autonomous cars(ADJ NOUN)  
2. insurance liability(NOUN NOUN)
3. manufacturers(NOUN)

If we go by the grammar rule as defined in NLTK, the "insurance liability" NP will not be captured. Therefore, I took the liberty to modify the regex to DT?JJ*{NN PROPN PRON}* (I am not sure if this is incorrect). When I wrote down the implementation for this in spaCy, it consistently performs ~30 percent faster than the existing implementation for noun phrase matcher and passes all the test cases as a part of the "test_parser.py". 

**Is the regex based method less reliable than the subtree based method used in spaCy? Additionally, both of these happen to be rule based noun phrase matcher, does someone have any idea about how one would go about implementing a phrase matcher that can be trained on data?** The only piece of I came across was "textblob.np_extractors.ConllExtractor, which uses the CoNLL 2000 corpus to train a tagger."

The code I had put down is 

```
def noun_chunks_2(obj):
    doc = obj.doc  # Ensure works on both Doc and Span.
    np_label = doc.vocab.strings.add("NP")
    lastValid = -1
    for i, word in enumerate(obj):
        start = 0
        end = 0
        validNP = False
        if i > lastValid:
            if word.pos == DET:
                start = i
                cur = i
                while cur+1 < len(obj) and obj[cur+1].pos == ADJ:
                    cur = cur + 1
                while cur+1 < len(obj) and obj[cur+1].pos in (NOUN,PROPN,PRON):
                    cur = cur + 1
                    end = cur
                    validNP = True
                if validNP:
                    lastValid = end
                    yield start,end+1,np_label
            elif word.pos == ADJ:
                validNP = False
                start = i
                cur = i
                while cur+1 < len(obj) and obj[cur+1].pos == ADJ:
                    cur = cur + 1
                while cur+1 < len(obj) and obj[cur+1].pos in (NOUN,PROPN,PRON):
                    cur = cur + 1
                    end = cur
                    validNP = True
                if validNP:
                    lastValid = end
                    yield start,end+1,np_label
            elif word.pos in (NOUN,PROPN,PRON):
                start = i
                cur = i
                end = start
                while cur+1 < len(obj) and obj[cur+1].pos == NOUN:
                    cur = cur + 1
                    end = cur
                yield start,end+1,np_label
```

**Comment by svlandeg** [comment]
Do I understand it correctly that the provided code snippet is meant to replace the code in https://github.com/explosion/spaCy/blob/master/spacy/lang/en/syntax_iterators.py#L7 ?

If so, it would probably be easier to review this as a pull request rather than an issue. 

If you want to propose this new implementation, the provided speed test is definitely of interest, but what I would additionally recommend is to take a random piece of text (no cherrypicking!), run that through both NP matchers, and analyse specifically the differences. Which results are returned by one and not by the other? That would help us better understand whether the proposed function is equivalent than the original ones.

The fact that the tests succeed ofcourse is also good, but we don't have exhaustive tests checking everything, so an analysis "in the wild" could be more informative.

**Comment by adrianeboyd** [comment]
This is just a demo example from the NLTK book and I don't think it will have the same coverage as the existing noun chunk iterator.

If you're interested in experimenting with chunking for English, you could take a look at the data from the CoNLL 2000 shared task: https://www.clips.uantwerpen.be/conll2000/chunking/. I'm not sure whether spacy's noun chunks correspond exactly to the ones used in this task (especially when there is coordination), but it would be a good place to start.

If you find cases that aren't handled correctly by the current noun chunk iterator, bug reports and PRs are welcome!

**Comment by naveenjafer** [comment]
@adrianeboyd  True, I ran the 2 against real life sentences from different datasets and got agreement in only about 30 percent of the cases and the spacy implementation being more suited in more scenarios. However, I plan on documenting the cases where the spacy chunker doesnt work as expected using the ground truth from the Conll2000 task. **Can you elaborate a little more on what you mean by "coordination"?** Most of the models proposed under that task are based on trained data, the implementation in spacy seems to be more of a rule-based approach based off the dependency trees.

**Comment by naveenjafer** [comment]
@adrianeboyd @honnibal @ines is there any way to know as to which paper/implementation served as the motivation for the spaCy implementation of noun chunker? 

I ran tests of spacy noun chunker against the CoNNL-2000 dataset for chunking. Here are the results.
Precision:     92.44
Recall: 	     80.84
F Score: 	     86.25

The reported F scores in https://www.clips.uantwerpen.be/conll2000/chunking/ seem to be a little higher owing to higher recall, if someone is interested in verifying the results just to ensure that I have not blundered while calculating the recall, I will update it in the next comment

**Comment by naveenjafer** [comment]
```
import time
import copy
import spacy

nlp = spacy.load("en_core_web_sm")

with open("test.txt") as fp:
    line = fp.readline()
    count = 0

    sentenceList = []
    sentCount = 0
    NPstarted = False
    NPList = []
    sentence = ""
    runningNP = ""
    while line:
        lineList = line.split(" ")
        if line.strip() == "":
            tempObj = {"sentence" : sentence.strip(), "NPList" : copy.deepcopy(NPList)}
            sentenceList.append(tempObj)
            sentCount = sentCount + 1
            #print(sentCount)
            NPstarted = False
            NPList = []
            runningNP = ""
            sentence = ""
            line = fp.readline()
            continue

        word = lineList[0]
        POS = lineList[1]
        POS = POS.strip()
        NP = lineList[2]
        NP = NP.strip()
        if NP == "B-NP" and NPstarted == False:
            #print("came here")
            NPstarted = True
            runningNP = word
        else:
            if NPstarted == True and (NP == "I-NP" or (NP == "B-NP" and POS == "POS")):
                #print("came here ")
                if POS == "POS" or POS == "." or POS == ",":
                    runningNP = runningNP + word
                else:
                    runningNP = runningNP + " " + word

            elif NPstarted == True and NP != "I-NP":
                #print("came in elif")
                NPstarted = False
                NPList.append(runningNP.strip())
                runningNP = ""
                if NP == "B-NP":
                    NPstarted = True
                    runningNP = word

        if POS == "POS" or POS == "." or POS == ",":
            #print("came here")
            sentence = sentence + word
        else:
            sentence = sentence + " " + word

        count = count + 1
        line = fp.readline()

print("Number of sentences " + str(sentCount))
onlySentenceList = [item["sentence"] for item in sentenceList]

docs = list(nlp.pipe(onlySentenceList))
time1 = time.time()

chunks = list(list(doc.noun_chunks) for doc in docs)
time2 = time.time()

same = 0
changes = []

totalChunksGroundTruth = 0
totalChunksPredicted = 0
totalCorrectChunksPredicted = 0
for i in range(len(chunks)):

    chunkList = []
    for item in chunks[i]:
        chunkList.append(str(item))
    totalChunksGroundTruth = totalChunksGroundTruth + len(sentenceList[i]["NPList"])
    totalChunksPredicted = totalChunksPredicted + len(chunkList)

    for predictedNP in chunkList:
        if predictedNP in sentenceList[i]["NPList"]:
            totalCorrectChunksPredicted = totalCorrectChunksPredicted + 1
    if chunkList == sentenceList[i]["NPList"]:
        same = same + 1
    else:
        changes.append(i)

print("Fraction of same items is " + str(same/len(chunks)))
precision = (totalCorrectChunksPredicted/totalChunksPredicted)*100
print("Precision: \t" + str(precision))
recall = (totalCorrectChunksPredicted/totalChunksGroundTruth)*100
print("Recall: \t" + str(recall))
FScore = 2 * ((precision * recall)/(precision + recall))
print("F Score: \t" + str(FScore))
```
Sequences of (B-NP)+(I-NP)* from the http://www.clips.uantwerpen.be/conll2000/chunking/test.txt.gz have been clubbed together to form the Noun Phrases. Once the noun phrases are extracted from test.txt they act as our ground truth. 

These sentences are then run through the spaCy noun chunker. 

Evaluation:
Precision : (Number of NPs predicted correctly / Number of NPs predicted)
Recall : (Number of NPs predicted correctly / Number of correct NPs in ground truth) - Can someone please verify if this is how Recall will be calculated in this case.

**Comment by naveenjafer** [comment]
Here is the repo for evaluations of spaCy Noun phrase chunker https://github.com/naveenjafer/spaCy_noun_chunk_evaluator
