### ISSUE TITLE
Advanced NLP with spaCy: Chapter #4

### ISSUE THREAD

**Issue by nick250386** [explosion/spaCy#4861]
I am a newbie trying to learn NLP and started with this framework.
While going through the wonderful interactive course you have provided [here](https://course.spacy.io/chapter4), I ran into an error and am unable to understand the issue from the error message reported.
I did go through the below references before raising this issue:

- [Ref#1](https://support.prodi.gy/t/ner-batch-train-error-trying-to-set-conflicting-doc-ents/2196)

- [Ref#2](https://github.com/explosion/spaCy/issues/2550)

- [Ref#3](https://stackoverflow.com/questions/57132117/spacy-valueerror-e103-trying-to-set-conflicting-doc-ents)

**SECTION:
Chapter 4: Training a neural network model
----> The training loop
------------>Example loop**

Below is my code:

```
import json 
from spacy.matcher import Matcher

from spacy.lang.en import English

with open("iphone.json") as f:
    TEXTS = json.loads(f.read())

nlp = English()
matcher = Matcher(nlp.vocab)

#Two tokens whose lowercase forms match 'iphone' and 'x'
pattern1 = [{'LOWER': 'iphone'}, {'LOWER': 'x'}]

#Token whose lowercase form matches 'iphone' and an optional digit
pattern2 = [{'LOWER': 'iphone'}, {'IS_DIGIT': True, 'OP': '?'}]

#Add patterns to the matcher
matcher.add("GADGET", None, pattern1, pattern2)

TRAINING_DATA = []

#Create a Doc object for each text in TEXTS
for doc in nlp.pipe(TEXTS):
    #Match on the doc and create a list of matched spans
    spans = [doc[start:end] for match_id, start, end in matcher(doc)]
    #Get (start character, end character, label) tuples of matches
    entities = [(span.start_char, span.end_char, "GADGET") for span in spans]
    #Format the matches as a (doc.text, entities) tuple
    training_example = (doc.text, {"entities": entities})
    #Append the example to the training data
    TRAINING_DATA.append(training_example)

import spacy

print('Training data:\n', TRAINING_DATA)
#*****BELOW CODE NOT WORKING
##Loop for 10 iterations
for i in range(10):
    #Shuffle the training data
    random.shuffle(TRAINING_DATA)
    #Create batches and iterate over them
    for batch in spacy.util.minibatch(TRAINING_DATA):
        #Split the batch in texts and annotations
        texts = [text for text, annotation in batch]
        annotations = [annotation for text, annotation in batch]
        #Update the model
        nlp.update(texts, annotations)

#Save the model
nlp.to_disk('.')>
```
**OUTPUT (with error stack):**
```
Training data:
 [('The iPhone 8 reviews are here', {'entities': [(4, 10, 'GADGET'), (4, 12, 'GADGET')]}), 
('How to preorder the iPhone X', {'entities': [(20, 28, 'GADGET'), (20, 26, 'GADGET')]}), 
('Your iPhone goes up to 11 today', {'entities': [(5, 11, 'GADGET')]}), 
('Should I pay $1,000 for the iPhone X?', {'entities': [(28, 36, 'GADGET'), (28, 34, 'GADGET')]}), 
('I need a new phone! Any tips?', {'entities': []}), 
('iPhone X is coming', {'entities': [(0, 8, 'GADGET'), (0, 6, 'GADGET')]})]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-27-2bc6b845db70> in <module>
     35         annotations = [annotation for text, annotation in batch]
     36         # Update the model
---> 37         nlp.update(texts, annotations)
     38 
     39 # Save the model

C:\ProgramData\Anaconda3\lib\site-packages\spacy\language.py in update(self, docs, golds, drop, sgd, losses, component_cfg)
    494             sgd = self._optimizer
    495         # Allow dict of args to GoldParse, instead of GoldParse objects.
--> 496         docs, golds = self._format_docs_and_golds(docs, golds)
    497         grads = {}
    498 

C:\ProgramData\Anaconda3\lib\site-packages\spacy\language.py in _format_docs_and_golds(self, docs, golds)
    466                     err = Errors.E151.format(unexp=unexpected, exp=expected_keys)
    467                     raise ValueError(err)
--> 468                 gold = GoldParse(doc, **gold)
    469             doc_objs.append(doc)
    470             gold_objs.append(gold)

gold.pyx in spacy.gold.GoldParse.__init__()

gold.pyx in spacy.gold.biluo_tags_from_offsets()

ValueError: [E103] Trying to set conflicting doc.ents: '(20, 28, 'GADGET')' and '(20, 26, 'GADGET')'. A token can only be part of one entity, so make sure the entities you're setting don't overlap.
```

I am trying to understand the issue and what went wrong here. If this is not the right forum to ask this, then please feel free to let me know so that I can take it to relevant forum for requested information.

**Comment by svlandeg** [comment]
Hi @nick250386, thanks for the detailed report!

I think the example given in the interactive course is not exactly ideal, because the two patterns result in partly overlapping entities, such as `iPhone` being `(20, 26, 'GADGET')` and `iPhone X` being `(20, 28, 'GADGET')` in the same sentence. The internals of spaCy don't allow you to set (partly) overlapping entities for the same tokens. So when you actually try to use this data for training, like you did, spaCy sees these as "conflicting" entities and crashes.

As a quick fix, I would suggest to remove the `, 'OP': '?'` from the second pattern so that it will always require a number there to match. This will remove the `iPhone` matches and will hopefully result in a non-conflicting dataset. 

At the same time, maybe we should revise this example in the course, @ines ?

**Comment by nick250386** [comment]
Thank you for the input @svlandeg , I will update my example accordingly.
If I could make a suggestion, an example to demonstrate this scenario in the docs will be a good idea for other learners like me to know how spaCy behaves under such scenarios for better understanding and designing the custom models.
