### ISSUE TITLE
Tokenization of URLs is different between English language model 2.2.0 and 2.2.5

### ISSUE THREAD

**Issue by clippered** [explosion/spaCy#4862]
## How to reproduce the behaviour
Hi,

There was a change in tokenizing URLs between sPacy language model en_core_web_sm 2.2.0 and 2.2.5

This code:
```
import spacy
nlp = spacy.load('en_core_web_sm')
doc = nlp('the url is https://www.example.com.ai/foo/bar/)
for t in doc:
  print(t.lower_)
```

Using en_core_web_sm 2.2.0, the output is:
```
the
url
is
https://www.example.com.ai/foo/bar/
```

Using en_core_web_sm 2.2.5, the output is:
```
the
url
is
https://www.example.com.ai
/
foo
/
bar/
```

But the weird thing is when using just `https://www.example.com/foo/bar/` without `.ai` in domain, the output is the same for both model versions
```
the
url
is
https://www.example.com/foo/bar/
```

Any ideas? Thanks.

## Your Environment
* Operating System: macOS Catalina 10.15.2
* Python Version Used: 3.7.6
* spaCy Version Used: 2.2.3
* Environment Information: Language model en_core_web_sm 2.2.0 and 2.2.5

**Comment by adrianeboyd** [comment]
Thanks for the report! It looks like one of the changes in I made in #4374 (in v2.2.2+) broke the pattern for host names with more than a simple `host.domain.tld` format.

**Comment by clippered** [comment]
Glad to help :)
