### ISSUE TITLE
Include pxd in source tarball

### ISSUE THREAD

**Issue by bollwyvl** [explosion/spaCy#4868]
## Feature description

It would be lovely to have the `pxd` files included in _some_ official distribution, so that other packages can confidently build against `spacy`. I'm looking to make a  [conda package for neuralcoref](https://github.com/conda-forge/staged-recipes/issues/10517), and my approach of merging the pypi tarball (preferred) and the github tarball (which has the pxd, but probably isn't tested) gives me the willies :scream_cat:.

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?

Pretty much would have to be on the mainline. Luckily, I'd imagine it's a one-liner to `MANIFEST.in`, but I don't know enough about the build chain to know if that's A Bad Idea for some reason... other than size, perhaps? If there's no obvious red flags, I'll PR said line!

**Comment by syllog1sm** [comment]
Hey,

We definitely intend the pxd to be in the source tarball! The cython api is part of the api, and it's intended to be usable by downstream packages. This is a bug in recent releases after updating our setup logic. We'll get that fixed.

We're also working actively to get neuralcoref into the main library :). If you have time to work on this it's possible we could use your help? I'm travelling today but hopefully I can write more tonight.

**Comment by bollwyvl** [comment]
Intriguing! I'm more of an amateur packaging puzzle solver than
professional cython hacker (or even spacy power user), but I do have it all
building locally, so at least there's that.

So, always glad to help!  Sure sounds easier than maintaining _n_
additional packages in the long run, as I thought would be required. Getting
the pretrained model pip-installable would help heaps, too.

In the near term, if the pxd are coming back, I won't worry about how ugly
my hack is to get something out.

**Comment by honnibal** [comment]
Should be fixed for the next release.

**Comment by svlandeg** [comment]
I just saw that Ines had already fixed this on `develop` when I submitted a fix for `master`, so yea it should be properly fixed :-)
