### ISSUE TITLE
Gitter chat for spaCy

### ISSUE THREAD

**Issue by viksit** [explosion/spaCy#487]
As the community grows, it might be useful to have a gitter chat room for spaCy (http://gitter.im). 

Any repo admin should be able to get it going with a couple of clicks, and anyone with a github account can sign in and lurk/chat/ask questions. I've found it quite useful for other projects I'm part of, and highly recommend we do it - especially when the community can answer many questions in real time.

cc @honnibal

**Comment by honnibal** [comment]
I made a spaCy-users channel.

Does Gitter differ in important ways from Slack or IRC?

I favour using whatever's the common consensus platform (i.e. whatever other similar projects are doing)

**Comment by viksit** [comment]
@honnibal Users can just join a chat room without an invitation (slack has this "invite to a team" issue that has been solved by some unofficial ways - check out http://rauchg.com/slackin/)

 Also, vs IRC - being browser based just means less friction to join. My 2c. I still like slack though and am open to either one, as long as one is officially chosen and added to the project page :)

**Comment by viksit** [comment]
@honnibal also, how do I find this chat room? Not sure if it's public. Maybe link to it here?

One established thing people do is to put the badge on the project page - http://blog.gitter.im/2014/01/27/badgers/ to put a "build passing" style badge.

Openai (https://gitter.im/openai/deeplearning) and Scikit (https://gitter.im/scikit-learn/scikit-learn) are using it.

**Comment by jeffsilverm** [comment]
I found out about spacy a couple of days ago, installed it, and now I am confused.  I'd like to be able to bring up my questions in an informal setting which is dedicated to spaCy.  I don't care about the mechanism: I'm running on linux so I can do anything.

**Comment by viksit** [comment]
@honnibal slack vs gitter?

**Comment by crawfordcomeaux** [comment]
@viksit The Gitter room is now showing up in searches. https://gitter.im/spaCy-users/

If any integrations are needed that Slack does offer and Gitter doesn't, I think there are ways to connect the two via bots, so may be able to augment Gitter that way. It's also possible to connect Gitter to IRC. Are there any meaningful downsides to just having all 3 interconnected like that? If I'm not mistaken, the Gitter room lets users add other users to it, so I think someone could conceivably set it up themselves without having to bother @honnibal about it. 

If I had a server to host the bots, I'd start laying it out tonight. I may just set it up locally on my laptop and/or see if there's anything out there in the way of serverless bots for this.

**Comment by ines** [comment]
Yay, just fixed the Gitter mess. Here's the new spaCy room: https://gitter.im/explosion/spaCy

We now have a new channel linked to the Explosion org. This way, all discussion stays in one place and we can open up more rooms for different topics or repos, in case people want to discuss sense2vec, displaCy or other things in the future.
