### ISSUE TITLE
Loading one model after another results in incorrect predictions for the second model

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#4872]
[spacy version 2.1.8]

I think I'm encountering an issue relating to this
https://github.com/explosion/spaCy/issues/3853#issuecomment-502440883

What I have in my script is this piece of code that loads a new NER model on demand.  the script starts by first loading an initial model 

```
try:
	dataPath = Path(input())
	modelPath = Path(input())

	set_data_path(dataPath)
	nlp_model = spacy.load(modelPath, disable=["parser", "tagger"])
	print("ready")
except BaseException as error:
	print("Error 1:", sys.exc_info()[0], error, dataPath, modelPath)
```

Then I enter a loop where I can continually submit text for evaluation and get back results.  At any time I can change the model 

```
	elif a == 'loadmodel':
		try:
			modelPath = input()
			nlp_model = spacy.load(modelPath, disable=["parser", "tagger"])
			print("ready")
		except BaseException as error:
			print("Error 2:", sys.exc_info()[0], error,  modelPath)
```

I've been comparing models built using different training data as well using different word vectors and when I start with an old model and load a new model, the predictions are different than those I would get if I started with the new model alone (no reloading)

I think something is being held in memory, perhaps the word vectors and it is affecting the predictions of the model that has been loaded.  

**Example**
_Green highlighted text is Date, and Purple highlight is Organization_

1 - Start script
2 - Load the new model (spacy.load called only once) - these the expected results for the new model
![latestModel_noreloading](https://user-images.githubusercontent.com/10454265/71734858-e5f09c80-2e1a-11ea-9804-5866f3286c54.PNG)

1 - Start script
2 - Load old model and don't change it yet (spacy.load called first time)
![oldModel_loadedFirst](https://user-images.githubusercontent.com/10454265/71734930-12a4b400-2e1b-11ea-84f2-30dcd4bbc3a3.PNG)

3 - Load new model after the old one (spacy.load called a second time) 
![latestModel_loadedAfterOld](https://user-images.githubusercontent.com/10454265/71734972-2d772880-2e1b-11ea-9440-043842d606e0.PNG)

Is there any way to solve this?

**Comment by adrianeboyd** [comment]
I suspect that the shape check that was added as a quick fix for default v2.1 models is not sufficient here for custom models where the shape may be the same for both models even though the vectors are different.

https://github.com/explosion/spaCy/blob/04113a844d9042f04c1fa0bc5830f11355b9b526/spacy/_ml.py#L303-L312

The vector name handling has been improved in recent releases. Can you try v2.2.3 with unique `--vector-name` settings with `spacy init-model` and see if this fixes the problem?
