### ISSUE TITLE
Lemmatizer on "best" returns token "good"

### ISSUE THREAD

**Issue by timforr** [explosion/spaCy#4874]
The 'en' lemmatizer lemmatizes the word "best" in to "good"

## How to reproduce the behaviour:
nlp = spacy.load('en')
test = nlp("best")
test[0].lemma_
>>> 'good'

**Comment by adrianeboyd** [comment]
I think that `good` is fine as a lemma for `best`. What did you expect the lemma to be?

**Comment by timforr** [comment]
I expected it to return "best", not "good". They have different meanings, and I don't want Spacy do make those decisions for me.

**Comment by adrianeboyd** [comment]
`good-better-best` is a typical paradigm that's handled by a lemmatizer, so I think spacy's output is okay here.

The exact definition of "lemma" can vary from tool to tool and the kinds of lemmas you want can also vary a bit from task to task, so spacy's lemmatizer might not be the right tool for your task or you may need to customize it.

`best` as an adjective is handled by a lemmatizer exception and you can modify it like this:

```
nlp.vocab.lookups.get_table("lemma_exc")["adj"]["best"] = ["new_lemma"]
```

You can see all the lemmatizer data in the package [`spacy-lookups-data`](https://github.com/explosion/spacy-lookups-data).

**Comment by timforr** [comment]
Alright, that makes sense. Thanks for the info on how to update the lemmatizer.
