### ISSUE TITLE
Strip Quotations from Document

### ISSUE THREAD

**Issue by AlJohri** [explosion/spaCy#4885]
I asked this question on StackOverflow more than a week ago so I wanted to to try my luck here: https://stackoverflow.com/questions/59504980/how-do-i-robustly-strip-quotations-from-news-articles-using-spacy

I'm looking to essentially take this Github Issue a step further: https://github.com/explosion/spaCy/issues/3196.

My goal is to remove or tag quotations from news articles, but I'm not sure how to robustly do so. I want to treat tokens inside quotes differently than tokens outside. For example, I would like to ignore entities found within quotations for my current use case.

My current implementation is brittle to unmatched quotes and also seems inefficient since its using the Matcher in a while loop for each document. One idea I had was ditching the `Matcher` which matches at a token level and start using something that allows me to take whitespace into account so I can match `"\s`. Would love any help.

Thanks!

## Info about spaCy

* **spaCy version:** 2.2.3
* **Platform:** Darwin-18.7.0-x86_64-i386-64bit
* **Python version:** 3.7.6

**Comment by adrianeboyd** [comment]
I'm not sure `Matcher` is going to be best tool for this in terms of performance, and robust performance on unmatched or noisy quotes is a completely separate issue, however:

Spacy does have an internal attribute for whether a token is followed by a space and the only reason it's not currently available in `Matcher` is the pattern validation, so this is easy to modify. Add this to `spacy/matcher/_schemas.py`:

```
            "SPACY": {
                "title": "Token is followed by a space",
                "$ref": "#/definitions/boolean_value",
            },
```

Then for matched ASCII double quotes you could have a pattern like:

```
pattern = [{"ORTH": '"', "SPACY": False}, {"ORTH": {"NOT_IN": ['"']}, "OP": "*"}, {"SPACY": False}, {"ORTH": '"'}]
```

The `Matcher` doesn't have an option for non-greedy matches, but with a pattern like this I think the performance should be okay. A custom component that uses non-greedy regexes on the plain text to provide character spans for quotes might be a lot faster, but you'd have to try it out...
