### ISSUE TITLE
Splitting document into sentences for Portuguese

### ISSUE THREAD

**Issue by mananeau** [explosion/spaCy#4887]
Hi and thanks for this cool repo :)

I'm trying to split a big Portuguese corpora into sentences and the split is not always clean. See for instance where sentences 48 and 49 should be one: 
![image](https://user-images.githubusercontent.com/29440170/71910021-6abc1d00-3171-11ea-8e21-da3fde3636d0.png)

Here is my code: 
![image](https://user-images.githubusercontent.com/29440170/71910304-ee760980-3171-11ea-91ce-5b703db37d5d.png)

Anything I'm doing wrong?

## Your Environment

* Operating System: Ubuntu Linux
* Python Version Used: 3.7.4

* spaCy Version Used: 2.2.3
* Model: pt_core_news_sm

**Comment by adrianeboyd** [comment]
Hi, you're not doing anything wrong. The sentence boundaries are provided by the statistical parser, which will not have perfect performance on all texts.  See similar issues and more detailed explanations in #3052.
