### ISSUE TITLE
Calling nlp.evaluate over a large number dev documents cause the process to crash

### ISSUE THREAD

**Issue by ZhuoruLin** [explosion/spaCy#4888]
I trained a custom textcat pipeline where the model is replaced by a custom PyTorch module (very simple CBOW model) wrapped by thinc wrapper. When I tried to evaluate the model using `nlp.evaluate` the process would crash.
 
My dev_docs consist of around 90000 documents (of over 6000 mutual exclusive classes), they are not preprocessed and therefore are in the base string type. I suspect whether in line 673-675 in `language.py`

        docs = [
            self.make_doc(doc) if isinstance(doc, basestring_) else doc for doc in docs
        ]

the storages of these docs are creating the memory issue? (Although I don't think it is very likely to be the case).

## Your Environment

* **spaCy version:** 2.0.18
* **Platform:** Linux-4.9.0-8-amd64-x86_64-with-debian-9.7
* **Python version:** 3.7.2

**Comment by adrianeboyd** [comment]
Hmm, there are so many different components involved that it's hard to know without more details about the crash.

Just the memory usage for the docs above should be easy to test independently of the rest of your code, so you can try that and see whether that is the problem? We haven't done a lot of testing on datasets with so many dev documents or so many categories, but I also wouldn't expect `make_doc()` (just the tokenizer) for those documents to be the problem.

Is there any more information you can provide about when/where it's crashing? Can you gradually increase the number of dev docs to see if the size of the dev set might be the source of the problem?
