### ISSUE TITLE
Span.ent_id_ returns first token ent_id in span

### ISSUE THREAD

**Issue by mr-bjerre** [explosion/spaCy#4895]
It seems that `span.ent_id_` just gives you the first non empty value of `[t.ent_id_ for t in span]`. I'd expect `span.ent_id_ = ''` if there are multiple non unique ids in the span.

Is this expected behavior?

* **spaCy version:** 2.2.3
* **Platform:** Linux-5.0.0-37-generic-x86_64-with-glibc2.27
* **Python version:** 3.8.1

**Comment by svlandeg** [comment]
`span.ent_id_` in fact returns the `ent_id_` of the token that is considered to be the `root` within the span. This `root` is the token that has the shortest path to the root of the sentence.

Usually `ent_id_` is used in the context of the `PhraseMatcher` or `EntityRuler` where this makes sense. I'm trying to think of a valid use-case where there would be different `ent_id`'s part of the same `Span` - can you give an example ?

**Comment by mr-bjerre** [comment]
Imagine a sentences like

> The result was 5 per cent higher than last year.
> The revenue was EUR 72 million. 

Using patterns I want to extract `5 per cent` and `EUR 72 million`. To achieve this I use two `EntityRuler`s with the second one depending on the first one. The first one locates currencies (EUR) and multipliers (per cent and million) and retokenizes those to single tokens. The second one then matches on ENT_TYPE to match the phrases of interest. 

Does it make sense?

**Comment by svlandeg** [comment]
Right, so that use-case would require some sort of nested entities, which is something that spaCy does not naturally support. However you should be able to work around this using custom attributes, and then match on those for your second `EntityRuler`. 

So I'm afraid the answer is, it's not a bug, but a feature ;-)

**Comment by mr-bjerre** [comment]
Perfectly fine. It’s not causing me any real issues anyways - just wanted to let you know in case it was a bug.

**Comment by mr-bjerre** [comment]
Sorry for reopening but I just have a related follow up question. Is it bad practice to remove an `ent_id` by `token.ent_id_ = ''`?

**Comment by svlandeg** [comment]
I think that should be fine!
