### ISSUE TITLE
doc similarity is different between GPU version and CPU version

### ISSUE THREAD

**Issue by omri374** [explosion/spaCy#4896]
## How to reproduce the behaviour

Introducing GPU makes doc.similarity return `<class 'cupy.core.core.ndarray'>` of size 1 instead of a scalar. On CPU the same call returns a scalar.

Reproduce:
```python
import spacy
nlp1 = spacy.load("en_vectors_web_lg")
doc1 = nlp1("Hey there how are you?")
doc2 = nlp1("I'm good and you?")
doc1.similarity(doc2)
```
0.9182046417319748

Then, when requiring GPU:
```python
spacy.require_gpu()
```
True

```python
nlp2 = spacy.load("en_vectors_web_lg")
doc1 = nlp2("Hey there how are you?")
doc2 = nlp2("I'm good and you?")
doc1.similarity(doc2)
```
array(0.9182048, dtype=float32)

## Your Environment
* **spaCy version:** 2.2.3
* **Platform:** Linux-4.15.0-1064-azure-x86_64-with-debian-stretch-sid
* **Python version:** 3.7.5

**Comment by omri374** [comment]
A quick workaround is to call `.item()` in any case.

**Comment by BramVanroy** [comment]
The difference is so small that I would argue that it is negligible/rounding noise. I do agree that it'd be better if in both cases, the same type is returned.

**Comment by svlandeg** [comment]
Thanks for the report! This boils down to the difference in output type of the `dot` method between [numpy](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) and [cupy](https://docs-cupy.chainer.org/en/stable/reference/generated/cupy.dot.html). numpy automatically converts an array with a single element to a scalar, which `cupy` doesn't. Calling `item()` makes sense, I'll update the codebase accordingly so there are no surprises.

**Comment by BramVanroy** [comment]
> Thanks for the report! This boils down to the difference in output type of the `dot` method between [numpy](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) and [cupy](https://docs-cupy.chainer.org/en/stable/reference/generated/cupy.dot.html). numpy automatically converts an array with a single element to a scalar, which `cupy` doesn't. Calling `item()` makes sense, I'll update the codebase accordingly so there are no surprises.

Hi. I think that's a good decision, indeed! Make sure to document this well, though, because in itself this breaks the way it was implemented before (different type returned). I don't know how many people use this in their code base, but it might cause unexpected bugs when suddenly the `item()` instead of the array is returned. Therefore, documenting seems very important.

**Comment by svlandeg** [comment]
Yea, I was just thinking about that, we'll probably introduce it as part of v.3 ;-)

**Comment by svlandeg** [comment]
Fixed by PR https://github.com/explosion/spaCy/pull/4969 - will be in spaCy v.3
