### ISSUE TITLE
Training NER model

### ISSUE THREAD

**Issue by leandermelms** [explosion/spaCy#490]
Hi,
I'm currently experimenting with creating a drug NER model. I'm trying to identify the following ner entities: 
- DrugName (e.g. simvastatin)
- BrandName (e.g. zocor)

I've applied the learning script postet in #187 and modified it according to my needs, starting with the DrugName entity.

I'm entirely new to spaCy and NLP in general, and I'm not sure how a training file should be designed. I'd be very thankful if you could explain how a training file should look like. Also, I'd be interested in how large the file should be to perform an acceptable precision.

Any help is greatly appreciated.

**Comment by viksit** [comment]
@leandermelms if you already know the names, why not just use a gazetteer (aka dictionary lookup) rather than train a statistical model?
