### ISSUE TITLE
Dutch model 'nl_core_news_sm' never returns lemma

### ISSUE THREAD

**Issue by jeroensilvis** [explosion/spaCy#4905]
## How to reproduce the behaviour

The ".lemma_" attribute always returns the text itself, never a lemma, using "nl_core_news_sm". 

## Your Environment

* Operating System:  Windows-10-10.0.17763-SP0
* Python Version Used:  3.7.3
* spaCy Version Used: 2.2.2
* Environment Information: most recent Anaconda distribution

**Comment by adrianeboyd** [comment]
Can you check the model version with `spacy validate`? The lemma data was missing from an earlier v2.2 release (2.2.1, see #4589) but the more recent ones (the current version is 2.2.5) should be fixed. I'm pretty sure that `spacy download nl` should update to the newest version, but if not, you can delete the package and use `spacy download nl` to reinstall it.

**Comment by jeroensilvis** [comment]
That seems to have done the trick! Thanks a lot for the quick response and sorry I had missed issue #4589

**Comment by adrianeboyd** [comment]
Glad it's working!
