### ISSUE TITLE
Any plan to make version >= 2.1.0 available on ppc64le?

### ISSUE THREAD

**Issue by Xiaoming-Zhao** [explosion/spaCy#4907]
Hi, I am wondering whether there are some plans to make `spacy>=2.1.0` available on `ppc64le`? Several popular packages, such as `allennlp`, require `spacy>=2.1.0`.

I have searched several channels but could not find `spacy>=2.1.0`. May I have some suggestions about how to utilize `spaCy` on `ppc64le`? Thanks a lot!

## How to reproduce the problem

Any command to install `spacy>=2.1.0`

## Your Environment

* Operating System:
```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"
```
* Python Version Used: have tried with Python 3.6 and 3.7
* spaCy Version Used: wish to install `spacy>=2.1.0`

**Comment by honnibal** [comment]
Hi,

The relevant incompatibility is in the Blis package. If you're just using spaCy within allennlp, they probably don't run any of the prediction through spaCy -- so you might not actually have a problem.

You can also try the instruction:

```
BLIS_ARCH="generic" pip install spacy --no-binary blis
```

See more info here: https://github.com/explosion/cython-blis

Another approach would be to check out the original Blis source, and get it built for your machine. You could then modify the `cython-blis` setup.py to link against your version.

**Comment by Xiaoming-Zhao** [comment]
Hi, thanks a lot for your quick reply!

I have tried your command but still got the following error related to Blis. It seems that the installation does not ignore the requirement of Blis. Any suggestions would be appreciated!
```bash
Collecting blis<0.3.0,>=0.2.1
    Using cached https://files.pythonhosted.org/packages/59/9e/84a83616cbe5daa94909da38b780e93bf566dc2113c3dc35d7b4cad52f63/blis-0.2.4.tar.gz
      ERROR: Command errored out with exit status 1:
       command: /home/users/.conda/envs/test/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xgx9lbe9/blis/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xgx9lbe9/blis/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-xgx9lbe9/blis/pip-egg-info
           cwd: /tmp/pip-install-xgx9lbe9/blis/
```

**Comment by svlandeg** [comment]
Could you try adding [`--no-cache-dir`](https://pip.pypa.io/en/stable/reference/pip_install/#caching)?
