### ISSUE TITLE
Possible copy-paste bug in NN parser

### ISSUE THREAD

**Issue by jakepoz** [explosion/spaCy#4908]
https://github.com/explosion/spaCy/blob/a3c43a1692a34db8c453109456a0924f3600506d/spacy/syntax/nn_parser.pyx#L59-L60

Is it possible there is a copy/paste mistake when reading the `conv_window` parameter, and it just reads the same value as `conv_depth`?

**Comment by honnibal** [comment]
That is indeed a mistake! Thanks. Now I'm confused as to why this hasn't caused more problems? I guess it might be relatively recent.

**Comment by svlandeg** [comment]
Thanks for the report! I had recently found and [fixed](https://github.com/explosion/spaCy/commit/cd0a9e58dcf5ec4316e6b1aaa954c55a9ea18cf4) this on a side branch of spaCy that will be integrated in the near future, but I'll quickly add the fix also to `master` for use in the meantime.
