### ISSUE TITLE
Crashing when processing single word - built from 2.2.3 sources

### ISSUE THREAD

**Issue by Lupotslboy** [explosion/spaCy#4919]
Just as described in #3034: this is happening on spaCy built from  2.2.3 sources 
The installation has been done running
```
    pip install -r requirements.txt && \
    python3 setup.py build_ext --inplace && \
    pip install -e . 
```
The author of #3034 eventually commented it was due to some gcc8 flag, but I'm not too sure what needs to change in the above install commands.

## How to reproduce the behaviour
```
import spacy
nlp = spacy.load('en')
nlp("Word")
```
This will result in 

 `/usr/include/c++/8/bits/stl_vector.h:932: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = __pyx_t_5spacy_6syntax_6_state_StateC*; _Alloc = std::allocator<__pyx_t_5spacy_6syntax_6_state_StateC*>; std::vector<_Tp, _Alloc>::reference = __pyx_t_5spacy_6syntax_6_state_StateC*&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.`

## Your Environment
* **spaCy version:** 2.2.3
* **Platform:** Linux-4.4.0-166-generic-x86_64-with-redhat-8.1-Ootpa
* **Python version:** 3.6.8
* **Models:** es, en

**Comment by svlandeg** [comment]
Hmm. Readin the other thread, the author was able to fix it by building with gcc7 instead of gcc8. Could you try that? You should be able to run `sudo update-alternatives --config gcc` to define the default one (as explained [here](https://askubuntu.com/questions/1028601/install-gcc-8-only-on-ubuntu-18-04))

**Comment by Lupotslboy** [comment]
Just an update about this issue: we found that the gcc8 worked just fine compiling sources. 
It looks the problem we had was when using sources obtained by cloning the git repo and compressing it in a tar.gz.
For some reasons that did not work well.
Downloading the zip of sources directly from git 
```shell
curl https://codeload.github.com/explosion/spaCy/zip/v2.2.3  --output spaCy-v2.2.3.zip) 
```
did the trick for us

**Comment by svlandeg** [comment]
Ok, great to hear you were able to resolve this, and thanks for reporting the fix!
