### ISSUE TITLE
Possible bug in spacy.gold.align

### ISSUE THREAD

**Issue by Frojdholm** [explosion/spaCy#4936]
The `b2a` mapping is not one-to-one when the longer sequence is passed as `tokens_a`. Additionally the many-to-one mappings are only created when the longer sequence is passed as `tokens_a`.

From my understanding similar to how `a2b` is explained in the [documentation](https://spacy.io/api/goldparse)
> If `a2b[3] == 2`, that means that `tokens_a[3]` aligns to `tokens_b[2]`. If there’s no one-to-one alignment for a token, it has the value -1.

the same should be true for `b2a`. If `b2a[2] == 3` then `tokens_b[2] == tokens_a[3]` 

## How to reproduce the behaviour
The following code shows the alignment using `a2b`.
```python
from spacy.gold import align
import numpy as np

other_tokens = ["obama", "'", "s", "podcast"]
spacy_tokens = ["obama", "'s", "podcast"]

cost, a2b, b2a, a2b_multi, b2a_multi = align(other_tokens, spacy_tokens)

for a, b in enumerate(a2b):
    if b != -1:
        print(f"other_tokens: {other_tokens[a]:>10}\tspacy_tokens: {spacy_tokens[b]:>10}")

# Output:
# other_tokens:      obama        spacy_tokens:      obama
# other_tokens:    podcast        spacy_tokens:    podcast
```

Testing `b2a` we get.

```python
for b, a in enumerate(b2a):
    if a != -1:
        print(f"other_tokens: {other_tokens[a]:>10}\tspacy_tokens: {spacy_tokens[b]:>10}")

# Output:
# other_tokens:      obama        spacy_tokens:      obama
# other_tokens:          s        spacy_tokens:         's    <- tokens differ
# other_tokens:    podcast        spacy_tokens:    podcast 
```

The many-to-one mappings seem to be correct.
```python
print(a2b_multi, b2a_multi)

# Output:
# {1: 1, 2: 1} {}
```

However, if we switch `other_tokens` and `spacy_tokens` the one-to-one mappings are now correct, but the many-to-one mapping is empty.

```python
# switch other_tokens and spacy_tokens
cost, a2b, b2a, a2b_multi, b2a_multi = align(spacy_tokens, other_tokens)

for a, b in enumerate(a2b):
    if b != -1:
        print(f"other_tokens: {other_tokens[b]:>10}\tspacy_tokens: {spacy_tokens[a]:>10}")

# Output:
# other_tokens:      obama        spacy_tokens:      obama
# other_tokens:    podcast        spacy_tokens:    podcast
```

This time, using `b2a`, the result is the same as using `a2b`.

```python
for b, a in enumerate(b2a):
    if a != -1:
        print(f"other_tokens: {other_tokens[b]:>10}\tspacy_tokens: {spacy_tokens[a]:>10}")

# Output:
# other_tokens:      obama        spacy_tokens:      obama
# other_tokens:    podcast        spacy_tokens:    podcast
```

Many-to-one mapping is now empty.

```python
print(a2b_multi, b2a_multi)

# Output:
# {} {}
```

## Your Environment
* **spaCy version:** 2.2.3
* **Platform:** Windows 10
* **Python version:** 3.7.6

**Comment by adrianeboyd** [comment]
Hi, thanks for the report! We're aware of this (#4525) and there's a faster alignment method that will be used in the next version of spacy (#4526). It requires the raw text to match the token orths more closely, but is faster and the multi alignments are correct.

You can use it in v2.2.3 by setting `spacy.gold.USE_NEW_ALIGN = True`.
