### ISSUE TITLE
Span.as_doc() does not preserve values of Token custom extensions 

### ISSUE THREAD

**Issue by jack-rory-staunton** [explosion/spaCy#4937]
## How to reproduce the behaviour
I set a custom extension on Tokens, tok._.x. When I create a Doc, the Tokens all have the correct value of the token extension. If I then select a span and call span.as_doc(), the resulting document's tokens' .has_extension() is True, but the value is set to the default value. On closer inspection, it appears that .as_doc() does not process the span into a doc by using the nlp pipeline that originally created the span. If I process the doc returned from Span.as_doc() with the relevant pipeline component, I get the expected values on the tokens' custom extension.  Is this the expected behavior? It seems like .as_doc() should respect the originating pipeline. I'm not 100% sure, but I never noticed this kind of discrepancy with Span or Doc custom extensions not being preserved in this way, so it may be specific to the token extensions.

## Your Environment
* **spaCy version:** 2.2.3
* **Platform:** Darwin-19.2.0-x86_64-i386-64bit
* **Python version:** 3.7.4

**Comment by svlandeg** [comment]
Hi @jack-rory-staunton. It's helpful if you provide a minimal, runnable example code snippet that shows the behaviour you're running into. This helps us debugging :-)

Anyway you have to supply [`copy_user_data=True`](https://spacy.io/api/span#as_doc) to the `as_doc` call, and it should work:

```
from spacy.language import Language
from spacy.tokens import Token

def test_issue4973():
    Token.set_extension("my_attr", default=342)
    nlp = Language()
    doc = nlp("I'm just testing issue 4973")
    doc[2]._.my_attr = 666
    print()
    for t in doc:
        print(t.text, t._.my_attr)
    my_span = doc[0:5].as_doc(copy_user_data=True)
    print()
    for t in my_span:
        print(t.text, t._.my_attr) 
```
prints
> I'm 342
> just 342
> testing 666
> issue 342
> 4973 342
> 
> I'm 342
> just 342
> testing 666
> issue 342
> 4973 342

**Comment by jack-rory-staunton** [comment]
Ah - Sorry - and Thanks! - I had not noticed the bit in the API section about the copy_user_data key.

**Comment by svlandeg** [comment]
No problem :-)
