### ISSUE TITLE
UserWarning: [W008] Evaluating Lexeme.similarity based on empty vectors.

### ISSUE THREAD

**Issue by lmorillas** [explosion/spaCy#4939]
## How to reproduce the behaviour
```
import spacy
nlp =  spacy.load("es_core_news_md")

def most_similar(word):
    by_similarity = sorted(word.vocab, key=lambda w: word.similarity(w), reverse=True)
    return [w.orth_ for w in by_similarity[:10]]

most_similar(nlp.vocab['perro'])
```
**es_core_news_md** include vectors  [1] but it raises a warning: UserWarning: [W008] Evaluating Lexeme.similarity based on empty vectors.

[1] https://github.com/explosion/spacy-models/releases//tag/es_core_news_md-2.2.5

## Info about spaCy

* **spaCy version:** 2.2.3
* **Platform:** Linux-4.13.0-46-generic-x86_64-with-Ubuntu-17.10-artful
* **Python version:** 3.6.3

**Comment by adrianeboyd** [comment]
The vocab and the vectors are populated from two different sources, so there's no guarantee that all the words in the vocab have vectors. There are 1230022 lexemes (initially, more can be added as you process texts) and 533736 words with vectors.

You can iterate over words with vectors:

```
for word in nlp.vocab.vectors:
    print(nlp.vocab.strings[word], nlp.vocab.vectors[word])
```

Or check whether a vocab entry has a vector:

```
nlp.vocab["word"].has_vector
```
