### ISSUE TITLE
Training NER model from scratch

### ISSUE THREAD

**Issue by Legited** [explosion/spaCy#494]
Hi, I'm trying to train a Named Entity Recognition model, and so far only found a method to train it on top of the default one, but since I'm adding new entity labels and some words already belong to other entities in the end it doesn't make correct prediction.  

Since we don't really need labels from original model, I want to start training one from scratch, but can't find the the method for that. How was the original model trained? Or how can I clear the 
loaded entity model before training it?

**Comment by debanjanmahata** [comment]
Hi! Is there any documentation for training a new entity recognizer from scratch without including the pre-trained labels? I followed the documentation and could only found docs for training a model with new labels on the pre-existing ones.
