### ISSUE TITLE
error: bad escape \p at position 257

### ISSUE THREAD

**Issue by utilizzatore** [explosion/spaCy#4944]
I'm getting the error:
`Error in py_call_impl(callable, dots$args, dots$keywords) : error: bad escape \p at position 257 `
running a python code with **R** through the use of **"reticulate" package**.

The issue comes up while executing the row:
`spacy.load('en_core_web_lg')`
I already checked with spacy validate that I have a version of spacy (v2.0.18) that agrees with the language model version (2.0.0).

Of course the code runs fine if executed with python.

**Comment by svlandeg** [comment]
Hm, I think usually this sort of error does indeed point to an incompatibility between the spaCy version and the model version, but I understand everything looks OK when you run `spacy validate`. 

Maybe a stupid question, but I don't have experience with `reticulate`. Is it running in exactly the same environment where you ran the `validate` command? (cf https://rstudio.github.io/reticulate/#getting-started)
