### ISSUE TITLE
Transferring a the transformer model fined tuned using GPU to CPU 

### ISSUE THREAD

**Issue by ehsanasgari** [explosion/spaCy#4948]
Hi there,

First of all, thanks for the great work. I am trying to pickle the fine tuned model over GPU. For this I need to transfer it to cpu otherwise I would get the following error:

TypeError: can not serialize 'cupy.core.core.ndarray' object

May I ask if you know how can I transfer the GPU model to CPU so that I can pickle it?

## How to reproduce the behaviour
with open('temp.pickle', 'wb') as handle:
    pickle.dump(best_model, handle)

## Your Environment
* Ubuntu

**Comment by ehsanasgari** [comment]
Hi @ines, so there is no solution to save the fine-tuned model using GPU? 
1) I can not pickle the model on GPU directly -- getting errors
2) There is no method in spacy to transfer the model from GPU to CPU so that we can pickle it.
3)The ".to_disk" method also doesn't work properly. When you load the model it is a raw model, not the fine-tuned.

**Comment by svlandeg** [comment]
I'm not sure, but could you check whether this is fixed with the latest [release 1.0.2 of srsly](https://github.com/explosion/srsly/releases/tag/v1.0.2)?

**Comment by svlandeg** [comment]
If it isn't - could you please share a minimal code snippet that exhibits the error? That's helpful for debugging things more quickly :-)
