### ISSUE TITLE
Simple train dependency parser on sentence splitting

### ISSUE THREAD

**Issue by pdimiel** [explosion/spaCy#4955]
Hello everyone,

I'm currently trying to train a blank language model based on an existing language.
I want to train the tagger and the dependency parser.
The annotated corpus I have includes multi-sentence documents.
When I use the method described in https://spacy.io/usage/training#example-train-parser , both modules are trained but converting to the desired input format drops sentence boundaries information and the trained model does not split sentences.
If I do not want to use a custom sentence spliter or sentenciser but want to depende on the parser sentence splitting, how should I format the following to be treated as a two sentence document in the training?

```
TRAIN_DATA = [
    (
        "They trade mortgage-backed securities.",
        {
            "heads": [1, 1, 4, 4, 5, 1, 1],
            "deps": ["nsubj", "ROOT", "compound", "punct", "nmod", "dobj", "punct"],
        },
    ),
    (
        "I like London and Berlin.",
        {
            "heads": [1, 1, 1, 2, 2, 1],
            "deps": ["nsubj", "ROOT", "dobj", "cc", "conj", "punct"],
        },
    ),
]
```

Thanks in advance

**Comment by adrianeboyd** [comment]
Hi, you are probably at the point where it would make more sense to switch to the spacy JSON training format and use `spacy train`, but if you want to use this format, you just need to concatenate the texts + annotations, obviously adjusting the dependency head offsets::

```
TRAIN_DATA = [
    (
        "They trade mortgage-backed securities. I like London and Berlin.",
        {
            "heads": [1, 1, 4, 4, 5, 1, 1, 7, 7, 7, 8, 8, 7],
            "deps": ["nsubj", "ROOT", "compound", "punct", "nmod", "dobj", "punct", "nsubj", "ROOT", "dobj", "cc", "conj", "punct"],
        },
    )
]
```
