### ISSUE TITLE
Slow performance with Span.ents

### ISSUE THREAD

**Issue by jakepoz** [explosion/spaCy#4958]
## How to reproduce the behaviour
``` python
doc = self.nlp(sentence)

for sentence in doc.sents:
  for ent in sentence.ents:
    [process some stuff]
```

The code above ends up having n^2 runtime, because the Span's class .ents property causes document entities to be recalculated from scratch, and then searched linearly:

https://github.com/explosion/spaCy/blob/d031440de2df1f0587d704c85b114d49ec9df53c/spacy/tokens/span.pyx#L413-L426

We worked around this by adding a cache around doc.ents and then binary search to get the start and end entities. 

```python
import bisect

from typing import List, Tuple
from spacy.tokens.span import Span
from spacy.tokens.doc import Doc

from functools import lru_cache


@lru_cache()
def __get_doc_ents(doc: Doc) -> Tuple[List[Span], List[int], List[int]]:
    """
    Returns a precached version of a document's entity list from spacy.
    Includes returning ordered indexes of the span start and end positions for easy binary searching.

    :param doc: Spacy document
    :return: (list of entities, list of start indexes, list of end indexes)
    """
    ents = doc.ents
    return ents, [x.start for x in ents], [x.end for x in ents]


def get_cached_ents(span: Span) -> List[Span]:
    """
    Returns the spacy ents for a span of text within a spacy document.

    It does this really fast by caching the entity list, and using binary search.
    :param span: the Span you want to get entities from
    :return: List of Entities as Spacy Spans
    """
    ents, starts, ends = __get_doc_ents(span.doc)

    start_index = bisect.bisect_left(starts, span.start)
    end_index = bisect.bisect_right(ends, span.end)

    return ents[start_index: end_index]
```

Performance for parsing really large documents (3+MB of raw text), went from 30+ minutes to 3 minutes when we used the code above. 

I wanted to post this here for reference in case anyone else had the same problem, and to ask if such a change would be accepted into mainline spacy.

**Comment by svlandeg** [comment]
Hi @jakepoz, thanks for the detailed analysis & suggested solution! I think your binary search solution makes a lot of sense, as your experiments also point out ;-)

We are currently working towards the release of spaCy v.3 in which we'll redesign the `ents` property entirely to be more flexible (and hopefully also more performant!). It's probably good to keep this issue open so we can revise it then when we're releasing v.3 (and if you'd be able to test it out again afterwards that would be helpful too ;-)).

**Comment by jakepoz** [comment]
Thank you! A big part of the performance also comes from creating+allocation the entire document ents array on each call. Will look forward to Spacy v3!

**Comment by adrianeboyd** [comment]
Just a note: if you want a very fast way to get ents for a sentence, there's no need to go through `doc.ents` or `span.ents` at all, just look at `token.ent_type` and `token.ent_iob` for the tokens in your sentence to extract the entities. You can see how `doc.ents` does this underneath:

https://github.com/explosion/spaCy/blob/d031440de2df1f0587d704c85b114d49ec9df53c/spacy/tokens/doc.pyx#L499-L526
