### ISSUE TITLE
📚Missing sections on spacy.io website 

### ISSUE THREAD

**Issue by kautukkundan** [explosion/spaCy#4961]
I was reading the getting started guide at spacy.io and found some missing sections. The sections "Powered by SpaCy" and "Other Libraries" seem to redirect at "Feature Comparison" and "Benchmarks" sections respectively. 

## Which page or section is this issue related to?

https://spacy.io/usage/facts-figures#powered-by

https://spacy.io/usage/facts-figures#other-libraries

**Comment by ines** [comment]
Thanks, good point! This was old content that has been removed, but it looks like we forgot to remove the section references. Fixing 🙂
