### ISSUE TITLE
Translating the website docs to other languages

### ISSUE THREAD

**Issue by dmesquita** [explosion/spaCy#4973]
Hello! I'm starting to translate the spaCy docs to Brazilian Portuguese (I think the usage section is very useful and it may worth the translation effort) but I didn't find any info about contributing with translations so I think I should ask first

Having different languages might add a little complexity to manage the docs (it would require us to [use a package](https://www.gatsbyjs.org/docs/localization-i18n/) or develop a way of doing it from scratch). Do you guys think it's worth it or should I host it somewhere else? Thanks!

**Comment by ines** [comment]
Sorry for only getting to this now! The idea sounds sounds very cool, thanks so much 😃

One thing that's always tricky with docs translations is that they can easily go out-of-sync, and we wouldn't be able to maintain multiple translations. Even just changing small details would become difficult and we wouldn't want to constantly hassle our [insert language]-speaking users to fix our own docs for us.

I think one option could be to have different versions of the [101 guide](https://spacy.io/usage/spacy-101) – it's pretty general and stable, and covers the most important concepts that people need to get started (and that might be easier to get across in their language). For that, I wouldn't add localization and just create separate pages that we can link from the main one (e.g. `spacy-101-pt-br`).

Another idea would be to translate the [spaCy course](https://course.spacy.io/)! If I remember correctly, someone is already working on a Chinese translation. The course is fully standalone and all open-source, so you can just fork the repo and then host it for free on Netlify or GitHub pages. And once it's done, we can promote it and link to it from the website and main course. Also, if you're looking for contributors, let us know and we'd be happy to make a Twitter post to get more Brazilian users involved 🙂

**Comment by dmesquita** [comment]
Thanks for the feedback! I loved the suggestions!
Indeed, it's to much work to keep the docs in sync and I think it wouldn't be of much use as well.

I liked the idea of simply having different pages for different languages. I'll start translating the 101 guide since it's relatively small. I think it would provide a nice "welcoming effect" for beginners if they see these guides in their own language. My goal is to submit a pull request next month and I'll document the process so we can add this to the [Contribute to spaCy](https://github.com/explosion/spaCy/blob/master/CONTRIBUTING.md) guides.

And I'll definitely work on translating the course as well! This looks like a larger project, so I guess it's best if I start looking for contributors after this first _experiment_ of translating the 101 guide. I'll let you guys know so you can tweet there o/

Thank you so much again, I'm very excited to work on this! :smiley:
