### ISSUE TITLE
Hyphen POS is sometimes PUNCT, sometimes NOUN

### ISSUE THREAD

**Issue by ewaldatsensentia** [explosion/spaCy#4974]
## How to reproduce the behaviour
```
import spacy
nlp = spacy.load("en_core_web_md")
doc = nlp("Pre-processing is good.")
for token in doc:
    print(token.orth_, token.pos_, token.tag_, token.dep_)
```
```
Pre ADJ JJ dep
- NOUN NN dep
processing NOUN NN nsubj
is AUX VBZ ROOT
good ADJ JJ acomp
. PUNCT . punct
```

```
doc = nlp("Cyber-bullying is bad.")
for token in doc:
    print(token.orth_, token.pos_, token.tag_, token.dep_)
```
```
Cyber NOUN NN compound
- PUNCT HYPH punct
bullying NOUN NN nsubj
is AUX VBZ ROOT
bad ADJ JJ acomp
. PUNCT . punct
```

## Your Environment
spaCy version    2.2.1                         
Platform         Windows-10-10.0.18362-SP0     
Python version   3.7.3                         
Models                                         
nlp.meta['version']  '2.2.0'

**Comment by adrianeboyd** [comment]
Hi, the tagger is a statistical model that will make a (hopefully small) number of mistakes. #3052 has a good explanation at the top and in the future, it's a good place to report issues like this!
