### ISSUE TITLE
create_pipe from factory initialized with Language, not Vocab

### ISSUE THREAD

**Issue by maxmealy** [explosion/spaCy#4979]
The `spacy.Language.create_pipe` method returns `factory(self, **config)` but `spacy.Pipe` is initialized as `def __init__(self, vocab, model=True, **cfg)`. So, a Language is being passed in, but Pipes are expecting Vocabs.

This is giving me issues with deserializing components that serialize vocab. For example:
```
from spacy.lang.en import English
nlp = English()
tagger = nlp.create_pipe("tagger")
tagger.from_disk("path/to/tagger")
```
Returns `ValueError: Can't read file: path/to/tagger/vocab/strings.json`

**Comment by adrianeboyd** [comment]
Hi, this is how to load the vocab and tagger separately:

```
from spacy.lang.en import English
nlp = English()
nlp.vocab.from_disk("path/to/vocab")
tagger = nlp.create_pipe("tagger")
tagger.from_disk("path/to/tagger", exclude=["vocab"])
nlp.add_pipe(tagger)
```

If the vocab isn't the same one the tagger was trained with (the main concern is the vectors) you won't get sensible results from the tagger.

Look at the code for `Language.from_disk()` to see how this is set up in general.
