### ISSUE TITLE
module 'bin.wiki_entity_linking.wikipedia_processor' has no attribute 'read_training_indices'

### ISSUE THREAD

**Issue by kurodenjiro** [explosion/spaCy#4982]
Traceback (most recent call last):
  File "wikidata_train_entity_linker.py", line 172, in <module>
    plac.call(main)
  File "C:\Users\Admin\Anaconda3\envs\spacy_nlu\lib\site-packages\plac_core.py", line 367, in call
    cmd, result = parser.consume(arglist)
  File "C:\Users\Admin\Anaconda3\envs\spacy_nlu\lib\site-packages\plac_core.py", line 232, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "wikidata_train_entity_linker.py", line 82, in main
    train_indices, dev_indices = wikipedia_processor.read_training_indices(training_path)
AttributeError: module 'bin.wiki_entity_linking.wikipedia_processor' has no attribute 'read_training_indices'

After trained a model wiki_data process successful so i got this issue 
How can i fix it ?

**Comment by svlandeg** [comment]
The method `read_train_indices` was introduced in a very recent version of the NEL module, cf https://github.com/explosion/spaCy/pull/4811. If you are running the scripts from the current `master` branch ( bin/wiki_entity_linking/wikidata_train_entity_linker.py ), then you'll also have to run them with a version of spaCy built from source with the `master` branch.

Alternatively, you'll have to run the scripts in the `bin` folder from the spaCy version you installed on your system.

**Comment by kurodenjiro** [comment]
i dont see the bin folder in spacy i installed

**Comment by kurodenjiro** [comment]
i ran python ./bin/wiki_entity_linking/wikidata_train_entity_linker.py output_kb_pretrain/  but it's still got same error

**Comment by kurodenjiro** [comment]
python3 ./bin/wiki_entity_linking/wikidata_train_entity_linker.py ./bin/wiki_entity_linking/kb-data -o ./models-nel in spacy current master branch

**Comment by svlandeg** [comment]
Right, the `bin` folder is not included in the distribution because it's outside the main folder.

If you've installed spaCy through `pip`, you can run these scripts for 2.2.3: https://github.com/explosion/spaCy/tree/v2.2.3/bin/wiki_entity_linking

**Comment by svlandeg** [comment]
Update for future reference: the Wikipedia EL code was moved to https://github.com/explosion/projects/tree/master/nel-wikipedia
