### ISSUE TITLE
Additional attributes attached to patterns in Matcher

### ISSUE THREAD

**Issue by savkov** [explosion/spaCy#499]
I was just wondering how the additional attributes in term patterns, for example `{"wiki_en":` "Google_Now"}` in [this example](https://github.com/spacy-io/spaCy/blob/master/examples/matcher_example.py), are exposed after tagging? I see that they are stored, but not sure how to check if/where they appear again. Is this something that is still under development?

**Comment by syllog1sm** [comment]
This still needs to be implemented — a pull request would be very welcome :)

I put the attributes into the API as a placeholder, as I knew we'd want this, so we may as well be forwards compatible. But it's still not implemented.

**Comment by savkov** [comment]
Can you point me to the places I need to look at if I want to do it? I might be able to do it on company time because we actually need it. Any further guidelines/advice will be welcome.

**Comment by honnibal** [comment]
Hard to be more precise than matcher.pyx at this point.

Meet me at http://appear.in/spacynlp Friday 10am GMT to discuss? Others are welcome to join if you have an interest.

**Comment by savkov** [comment]
Hey, should we reschedule? I tried both 11am and 12pm Berlin time.

**Comment by honnibal** [comment]
Fuck I went to the wrong room. I was in /spacy. Coming =/

**Comment by honnibal** [comment]
See here: https://github.com/spacy-io/spaCy/commit/58e83fe34bbec777db588f19723668c2ec431f71

**Comment by honnibal** [comment]
Improved version of this is in 1.0.0
