### ISSUE TITLE
 Error: Couldn't link model to 'fr_core_news_sm'

### ISSUE THREAD

**Issue by gfelot** [explosion/spaCy#4992]
## How to reproduce the problem
After installing the package with `conda` I want to load the fr package with
`python -m spacy download fr_core_news_sm`
I'm inside a conda env where I execute all the installation process.

```bash
Error: Couldn't link model to 'fr_core_news_sm'
    Creating a symlink in spacy/data failed. Make sure you have the required
    permissions and try re-running the command as admin, or use a
    virtualenv. You can still import the model as a module and call its
    load() method, or create the symlink manually.

    C:\Users\gfelot\.conda\envs\test\lib\site-packages\fr_core_news_sm -->
    C:\Users\gfelot\.conda\envs\test\lib\site-packages\spacy\data\fr_core_news_sm


    Creating a shortcut link for 'en' didn't work (maybe you don't have
    admin permissions?), but you can still load the model via its full
    package name: nlp = spacy.load('{name}')
    Download successful but linking failed
```

It seems it's because I'm not ADMIN of my machine. How can I handle that without being able to be admin ? I'm not sure about the process.

## Your Environment
* Operating System: Windows 10
* Python Version Used: 3.7
* spaCy Version Used: latest
* Environment Information: ???

**Comment by svlandeg** [comment]
As the error message states, creating symlinks will require admin access on your Windows machine. This is mainly useful to create shortcuts like `"fr"`. 

As it also states, you should be able to still use the package with its full name. Can you give the output of `pip list` after running the above command? `fr_core_news_sm` should be there.

**Comment by gfelot** [comment]
```
pip list

Package            Version
------------------ -------------------
attrs              19.3.0
blis               0.4.1
catalogue          1.0.0
certifi            2019.11.28
cffi               1.13.2
chardet            3.0.4
Click              7.0
cryptography       2.8
cymem              2.0.3
et-xmlfile         1.0.1
fr-core-news-sm    2.2.5
idna               2.8
importlib-metadata 1.5.0
inflect            4.1.0
jaraco.itertools   5.0.0
jdcal              1.4.1
joblib             0.14.1
jsonschema         3.2.0
mkl-fft            1.0.15
mkl-random         1.1.0
mkl-service        2.3.0
more-itertools     8.2.0
murmurhash         1.0.0
nltk               3.4.5
numpy              1.18.1
openpyxl           3.0.3
pandas             1.0.0
pathlib            1.0.1
pip                20.0.2
plac               0.9.6
preshed            3.0.2
pycparser          2.19
pyOpenSSL          19.1.0
pyrsistent         0.14.11
PySocks            1.7.1
python-dateutil    2.8.1
python-dotenv      0.10.5
pytz               2019.3
requests           2.22.0
scikit-learn       0.22.1
scipy              1.3.2
setuptools         45.1.0.post20200127
six                1.14.0
spacy              2.2.3
srsly              1.0.0
thinc              7.3.0
tqdm               4.42.0
urllib3            1.25.7
wasabi             0.6.0
wheel              0.34.1
win-inet-pton      1.1.0
wincertstore       0.2
xgboost            0.90
xlrd               1.2.0
zipp               2.1.0
```

I'm not admin of my machine. I got a hack to launch gitbash as admin but it's a pain in the *ss to do it. Do I have to install the language package on each conda environment or it's done one for all ?

**Comment by svlandeg** [comment]
You have to install the model / package in each env you want to use it.

I see you have `fr-core-news-sm` properly installed in your environment, so you will be able to load it with `nlp = spacy.load('fr_core_news_sm')`.

**Comment by gfelot** [comment]
`fr_core_news_sm` is installed yep because I did the `python -m ...` command. But since it's seems to have an issue about the symlink I was wondering if it was working or not.
