### ISSUE TITLE
E018 still not fixed

### ISSUE THREAD

**Issue by biavarone** [explosion/spaCy#4993]
## [E018] Can't retrieve string for hash '4251533498015236010'. This usually refers to an issue with the `Vocab` or `StringStore`.
I'm getting this error several times and it seems completely random. I've seen that this error was already reported, but it keeps happening. I'm using Matcher to match on text and I've added to it a few rules. It somehow seems to be related to the string name given to the key.
E.g. 
-if I add the rules like this `places_matcher.add('workplace', None, workplace1, workplace2, workplace3)` the code returns the error above.
-weirdly, if I change it into `places_matcher.add('work', None, workplace1, workplace2, workplace3)` it works fine.
-If I modify the string key into something else...it doesn't work again.

I first thought that it depended on the length of the string key, but I'm using also longer strings that don't raise any error. 

Something else I've noticed is that the error is more common when the rule contains different choices for lemmas, like in this case: `workplace1 = [{'LEMMA': {'IN': ['administration', 'job', 'office', 'work', 'workplace']}, 'POS': 'NOUN'}]`
While if I create a rule for each lemma, this doesn't seem to happen.

## Environment

* Operating System: Linux Mint 19.2 Cinnamon
* Python Version Used: 3.7
* spaCy Version Used: v2.2.3

**Comment by adrianeboyd** [comment]
Hmm, there have been problems with "ghost" matches before in Windows (#4098) where the `Matcher` returned match_ids that weren't in the vocab, but they didn't occur in linux and we haven't seen this bug again in any of our tests since bug fixes in v2.2.2 (#4993).

Do you have a minimal working example that shows where you run into this error? Does the error occur predictably for the same key+pattern combination in the same script or not?

**Comment by biavarone** [comment]
So, it doesn't look like a ghost match, because the match_ids are actually in the vocab, but for some reasons sometimes the `StringStore` is unable to retrieve the string id, given the hash.

It'd be actually quite hard to give you a minimal working example, because - what's even weirder - is that if I copy and paste the key+pattern combinations where I'm getting the error in another python file and run that file with the same settings I was using before, the error doesn't occur anymore. That's why it seems random and I can't understand what's wrong. I'm quite sure it doesn't depend on the key+pattern combinations. However, I'll try to reproduce the error in a minimal example and post it asap.

It seems that the error is more likely to occur when many patterns and keys are added to the `Matcher`.

**Comment by adrianeboyd** [comment]
At what point do you see the `StringStore` error? When you're processing the match results tuples? An example script would be helpful even if the error only happens sometimes, since it would be useful to see the context so we can see exactly what's going on when you run into the error.

There were some bugs in the previous implementation of `PhraseMatcher` (which used `Matcher` underneath) that only happened with a large number of patterns, so something along those lines is definitely a possibility. In that case, though, it stopped returning matches it should have returned rather than having `StringStore` errors, but in case it seems like similar behavior, take a look at #4308. I ended up rewriting the whole `PhraseMatcher` and never figured out what was causing those problems.

**Comment by biavarone** [comment]
Hi, here's a minimal working code! I get the error when trying to retrieve the rule_id from the match_id, at this point: `rule_id = nlp.vocab.strings[match_id] `

```
import spacy
from spacy.matcher import Matcher

nlp = spacy.load('en_core_web_sm')
matcher = Matcher(nlp.vocab, validate=True)

work_study1 = [{'LEMMA': {'IN': ['essay', 'exam', 'homework', 'revision']}, 'POS': 'NOUN'}]
work_study2 = [{'LEMMA': {'IN': ['learn', 'revise', 'study', 'work']}, 'POS': 'VERB'}]

matcher.add('workstudy', None, work_study1, work_study2)

sentence = "I've been nervous about returning to work on Monday but I feel calm now"
sentence = nlp(sentence)
for sent in sentence.sents:
    sent = sent.as_doc()
    matches = matcher(sent)

    for match_id, start, end in matches:
         rule_id = nlp.vocab.strings[match_id]  # get the unicode ID
         span = sentence[start: end]  # get the matched slice of the doc
```

Hope this helps for discovering what's going on!
Notice that in my code it happens that if I change the rule_id from "workstudy" to "work", the code doesn't return any error. If again I try to change it into something else, it may work or not.

**Comment by adrianeboyd** [comment]
Frustratingly, I can't replicate this. It does seem like it might be a ghost match because I don't get any matches for this example with the same model. Can you show the output of `spacy validate` and also show the document annotation (lemmas and POS) and the contents of `matches` before you get the error?

And it's a long-shot, but just as a check, do you get the same errors without the `sent.as_doc()`?

```
matches = matcher(doc)
for match_id, start, end in matches:
     rule_id = nlp.vocab.strings[match_id]  # get the unicode ID
     span = doc[start: end]  # get the matched slice of the doc
```

**Comment by biavarone** [comment]
Yes, I get the same error even without `sent.as_doc()`

This is the annotation:
I, PRON
have, AUX
be, AUX
nervous, ADJ
about, ADP
return, VERB
to, PART
work, VERB
on, ADP
Monday, PROPN
but, CCONJ
I, PRON
feel, VERB
calm, ADJ
now, ADV

And here's the output of `spacy validate`
====================== Installed models (spaCy v2.2.3) ======================
ℹ spaCy installation:
/home/benedetta/anaconda3/lib/python3.7/site-packages/spacy

TYPE      NAME                             MODEL                            VERSION                            
package   it-core-news-sm                  it_core_news_sm                  2.2.5   ✔
package   en-vectors-web-lg                en_vectors_web_lg                2.1.0   ✔
package   en-trf-robertabase-lg            en_trf_robertabase_lg            2.2.0   ✔
package   en-trf-distilbertbaseuncased-lg   en_trf_distilbertbaseuncased_lg   2.2.0   ✔
package   en-trf-bertbaseuncased-lg        en_trf_bertbaseuncased_lg        2.2.0   ✔
package   en-core-web-sm                   en_core_web_sm                   2.2.5   ✔
package   en-core-web-lg                   en_core_web_lg                   2.2.5   ✔

**Comment by adrianeboyd** [comment]
Thanks for your patience! This is very weird, because with the exact same version of spacy and the exact same English model, the annotation on my end looks like this:

```
-PRON- PRON
have AUX
be AUX
nervous ADJ
about ADP
return VERB
to ADP
work NOUN
on ADP
Monday PROPN
but CCONJ
-PRON- PRON
feel VERB
calm ADJ
now ADV
```

I especially don't understand why you don't have `-PRON-` lemmas, and the POS tags for `to work` shouldn't be different, either.

Could you trying installing spacy in a new environment to see if you get the same output and errors?

```
conda create -n spacytest python=3.7
conda activate spacytest
conda install -c conda-forge spacy==2.2.3
spacy download en
[run script above]
```

**Comment by biavarone** [comment]
First, sorry, I wrote the wrong output. I was making some tests using spacy.udpipe and I forgot switching to the other model. With 'en_core_web_sm' my output is the same as yours.

For the new environment, same error - but on a different rule. This one:
`fearful1 = [{'LEMMA': {'IN': ['anxiety', 'anxious', 'concern', 'concerned', 'excluded', 'exposed', 'fearful',
                              'frightened', 'helpless', 'inadequate', 'inferior', 'insecure', 'insignificant',
                              'nervous', 'overwhelmed', 'persecuted', 'rejected', 'scare', 'threatened', 'weak',
                              'worried', 'worry', 'worthless']}, 'POS': {'IN': ['NOUN', 'ADJ', 'ADV']}}]

matcher.add('fearful', None, fearful1)`

**Comment by biavarone** [comment]
I have an update. If the word I'm trying to match is the same as the `rule_id`, I get no error. For any other word present in the rule, I get the error.
Making an example with the rule I wrote before, if I try to match on the word "fearful" it works fine, if I try to match on any other word in the rule (like anxious, or nervous, ...) the error comes up!

**Comment by adrianeboyd** [comment]
Does the problem go away if you specifically add all your lemmas to the vocab before adding the pattern to the `Matcher`?

```
for lemma in lemma_list:
    nlp.vocab.strings.add(lemma)
```

Can you also check whether the `match_id` that's not in the vocab corresponds to one of the lemmas (with `nlp.vocab.strings[lemma]`)? Internally the `Matcher` shouldn't care whether the words are in the `StringStore`, but maybe this points to where the bug might be.

**Comment by biavarone** [comment]
The problem still remains even if I add the lemmas to the vocab before adding the pattern to the `Matcher`.

Yes, the `match_id` corresponds to one of the lemmas.

The thing is, the `match_id` actually IS in the vocab, because if I return the matches I get the `(match_id, start, end)` correctly. The problem occurs only here `rule_id = nlp.vocab.strings[match_id] `

**Comment by adrianeboyd** [comment]
Hmm, I could imagine a situation with a ghost match from the `Matcher`, but not that it removes entries from the `StringStore`, so I'm not sure I explained that test clearly enough in my last comment.

Can you double-check that `doc`, `Matcher`, and the `nlp.vocab` in your `matches` loop might not be referring to the same vocab. You should have:

```
assert nlp.vocab == matcher.vocab
assert matcher.vocab == doc.vocab
assert nlp.vocab == doc.vocab
```

Is that at all a possibility (especially if you're experimenting with different models)?

If not, and if I've understood your "fearful" example correctly, the script below should fail in at least one case for you in the new environment. Can run this script in the environment where this example fails and copy the output here?

```
import spacy
from spacy.matcher import Matcher

def print_matches(matches):
    for match_id, start, end in matcher(doc):
        try:
            print(match_id)
            print(nlp.vocab.strings[match_id])
        except Exception as e:
            print(e)
    print()

fearful1 = [{'LEMMA': {'IN': ['anxiety', 'anxious', 'concern', 'concerned', 'excluded', 'exposed', 'fearful', 'frightened', 'helpless', 'inadequate', 'inferior', 'insecure', 'insignificant', 'nervous', 'overwhelmed', 'persecuted', 'rejected', 'scare', 'threatened', 'weak', 'worried', 'worry', 'worthless']}, 'POS': {'IN': ['NOUN', 'ADJ', 'ADV']}}]
text = "I've been nervous about returning to work on Monday but I feel calm now"

# matched lemma as match_id

nlp = spacy.load('en_core_web_sm')
matcher = Matcher(nlp.vocab, validate=True)

matcher.add('nervous', None, fearful1)

doc = nlp(text)
print_matches(matcher(doc))

# matched lemma not as match_id

nlp = spacy.load('en_core_web_sm')
matcher = Matcher(nlp.vocab, validate=True)

matcher.add('anxious', None, fearful1)

doc = nlp(text)
print_matches(matcher(doc))

# matched lemma not as match_id with all lemmas added to vocab

nlp = spacy.load('en_core_web_sm')
for lemma in fearful1[0]["LEMMA"]["IN"]:
    print(lemma, nlp.vocab.strings.add(lemma))

matcher = Matcher(nlp.vocab, validate=True)

matcher.add('anxious', None, fearful1)

doc = nlp(text)
print_matches(matcher(doc))
```

My output is:

```
11216294436333666104
nervous

17666472240380234790
anxious

anxiety 3518314200804635422
anxious 17666472240380234790
concern 16371372851814722007
concerned 14408474211775539142
excluded 1626452767944994551
exposed 11001471243418056114
fearful 736430059246765513
frightened 5036881813963765413
helpless 3077801403441042307
inadequate 17995393726734896709
inferior 3137895292270495849
insecure 14119583471037768949
insignificant 7368706981661636913
nervous 11216294436333666104
overwhelmed 18284834717952337641
persecuted 5864936813983524155
rejected 15944366691696846854
scare 11215537710704286927
threatened 17398512174444510244
weak 15297485476841041274
worried 1590835026366056004
worry 7760832780032654484
worthless 13095714296952392496
17666472240380234790
anxious
```

**Comment by biavarone** [comment]
Hi there, I double checked and the `Matcher` was actually referring to a different `vocab`. It's all fixed now, thank you for your patience and help!

**Comment by adrianeboyd** [comment]
Glad you figured it out!
