### ISSUE TITLE
Support for MemoryFS and or CephFS for model loading

### ISSUE THREAD

**Issue by smiles3983** [explosion/spaCy#4999]
## Feature description
We are limited at the amount of data we can store in our openshift file system within our enterprise platform.  When we use the large data model, we cant store it within our docker pods container.  We do have plenty of memory available.  We have been able to load the model into a MemoryFS and may in the future setup CephFS.  But the model loading currently only works with a real FS object only.  We are currently getting around this using an S3 bucket and using the from_bytes loader, but I would like to be able to bring the models tar file into memory and then load it that way instead of having to extract and store the byte level object of the model like we do with from_bytes.

**Comment by honnibal** [comment]
I think the `model.from_bytes()` solution is the right approach. It's what I would have suggested, and it's why we've made sure to have bytes-based serialization as an option, for full flexibility.

I'm really not keen to add support for the file-systems you listed: it's actually the first time I've heard of either of them, and we wouldn't be able to support or test those code paths.
