### ISSUE TITLE
Frozen read train

### ISSUE THREAD

**Issue by kurodenjiro** [explosion/spaCy#5003]
![Untitled](https://user-images.githubusercontent.com/26534614/74297189-abaedf00-4d78-11ea-8ab6-40e613191324.png)
I check debug but it's not run

**Comment by svlandeg** [comment]
How many lines are in the `gold_entities.jsonl` file? Also see the advice in the discussion [here](https://github.com/explosion/spaCy/pull/4811#issuecomment-567461500) to limit that training data file, which is probably just too huge right now. Could you try that? 

Note that the comments there do refer to the new version of the code, currently on the master branch. I'm afraid this functionality is still changing quite a bit and not quite stable yet.

**Comment by kurodenjiro** [comment]
> How many lines are in the `gold_entities.jsonl` file? Also see the advice in the discussion [here](https://github.com/explosion/spaCy/pull/4811#issuecomment-567461500) to limit that training data file, which is probably just too huge right now. Could you try that?
> 
> Note that the comments there do refer to the new version of the code, currently on the master branch. I'm afraid this functionality is still changing quite a bit and not quite stable yet.

I see problem , my language dont have ent to train

**Comment by kurodenjiro** [comment]
do i need ent in my process language ?

**Comment by svlandeg** [comment]
You do need a pipeline component that performs Named Entity Recognition, yes. Have a look through the documentation [here](https://spacy.io/usage/training#entity-linker) and [here](https://spacy.io/usage/linguistic-features#entity-linking) for more details.
