### ISSUE TITLE
Multilingual core model release

### ISSUE THREAD

**Issue by alexcombessie** [explosion/spaCy#5012]
Hi there,

First of all, thanks a lot for the great work! Really useful.

For security reasons, I need to package the installation of spacy models through pip. Hence I am using https://github.com/explosion/spacy-models/releases/... I have found all the core languages (thanks!), but not the multilingual one.

Could you release the multilingual one as well on Github?

Thanks,

Alex

**Comment by svlandeg** [comment]
You can find the multi-lingual NER model here: https://github.com/explosion/spacy-models/releases/tag/xx_ent_wiki_sm-2.2.0. Hope that solves your question!

**Comment by alexcombessie** [comment]
Indeed, it solved it! As GitHub does not offer an easy way to search for releases, I missed it. Thank you so much!

**Comment by svlandeg** [comment]
Sure! Actually if you go through the [model docs](https://spacy.io/models/), you can more easily navigate to the correct model and click the "RELEASE DETAILS" button ;-)
