### ISSUE TITLE
Thinc upgrade to 8.0.0

### ISSUE THREAD

**Issue by andre-cavalheiro** [explosion/spaCy#5014]
## Feature description
Spacy is currently using Thinc version 7.4.0.dev0. However, Thinc has released its 8.0.0 version which is a lot more powerful.  Using both packages means that if I want to use spacy, I have to downgrade my Thinc version which takes most of the cool stuff away. 

Do you have any idea on when you'll be updating (if ever)? Having to choose one or the other doesn't seem like a viable option.

**Comment by svlandeg** [comment]
Yes, this is obviously something we're working on ;-)

Thinc 8 has been quite the overhaul, and we're currently in the process (on the `develop` branch) to refactor spaCy accordingly. This will be published as spaCy v.3. But as you can imagine we want to do this carefully so nothing breaks in the process.

Feel free to keep an eye on the `develop` branch! We're hoping to get a spacy-nightly out soonish so we can start testing with thinc8-compatible models etc.
