### ISSUE TITLE
OSError: [E050] Can't find model 'en_core_web_lg'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

### ISSUE THREAD

**Issue by dbl001** [explosion/spaCy#5015]
## How to reproduce the behaviour

From 'jupyter lab'
import spacy
print(spacy.__version__)
nlp = spacy.load("en_core_web_lg")

## Info about spaCy

* **spaCy version:** 2.2.3
* **Platform:** Linux-4.4.0-164-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.6.7
* Operating System:
Ubuntu 16.04LTS
* Python Version Used:
Anaconda 3.6
* spaCy Version Used:
2.2.3
* Environment Information:
Jupyter lab

I can load 'en_core_wb_lg' from ipython, but not from jupyter lab:

![Screen Shot 2020-02-13 at 1 23 16 PM](https://user-images.githubusercontent.com/3105499/74479680-6e278000-4e64-11ea-9a1b-746f5271706d.png)
![Screen Shot 2020-02-13 at 1 23 05 PM](https://user-images.githubusercontent.com/3105499/74479682-6f58ad00-4e64-11ea-8d96-dae4b0bbd946.png)

Here's iPython:
```
(lda2vec) ubuntu@ip-10-0-1-71:~/Lda2vec-Tensorflow/tests/twenty_newsgroups/data$ ipython
Python 3.6.7 | packaged by conda-forge | (default, Nov  6 2019, 16:19:42) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.12.0 -- An enhanced Interactive Python. Type '?' for help.


In [1]: import spacy                                                            

In [2]: print(spacy.__version__)                                                
2.2.3

In [3]: nlp = spacy.load("en_core_web_lg")                                      
nlp

In [4]: nlp                                                                     
Out[4]: <spacy.lang.en.English at 0x7f4802ee36d8>
```

**Comment by svlandeg** [comment]
It looks like `en_core_web_lg.load()` works fine, but spacy.load("en_core_web_lg") doesn't, is that right? So for now at least you can use the first way as a workaround?

Could you try following [this suggestion](https://github.com/explosion/spaCy/issues/4577#issuecomment-550159196), installing the package from file?

**Comment by dbl001** [comment]
I had already tried that suggestion and it didn’t work.
Curiously, after several hours ... it started working.
I have no idea why.

**Comment by svlandeg** [comment]
Huh, that's weird. On my end I can't replicate this either, so it's not clear whether this is a problem with spaCy, with jupyter or maybe a matter of admin/access rights... I'll close this for now, let's hope it keeps working for you ;-)

**Comment by dbl001** [comment]
Spacy worked everytim from iPython but NOT from jupyter lab … until, eventually, it did.
