### ISSUE TITLE
Fast (cythonised) method for retrieving token character indices for all tokens at once

### ISSUE THREAD

**Issue by MisterKeefe** [explosion/spaCy#5029]
## Feature description
Hi, 

The `Doc` object currently exposes the `to_array` method for rapidly converting from tokens to an array of feature data. It would be nice to have something similar for the start and end character offsets of each token within the original string (that is, `token.idx, token.idx + len(token)` ).  

Internally these aren't attributes and so `to_array` can't be used. It is of course possible to retrieve the offsets in Python, but it can be pretty slow for large documents. A Cythonised version would be a bit snappier.

I [have a branch](https://github.com/MisterKeefe/spaCy/blob/token-offsets-method/spacy/tokens/doc.pyx#L664) where I've added a `to_token_offsets` method which returns a 2-by-N array for N tokens, with the first column being start offsets and the second end offsets. I'd be happy to raise a PR with this change if it seems like a useful utility method. 

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?

I don't think so, for the performance reasons outlined above.

**Comment by honnibal** [comment]
Yes this is just an oversight --- we should definitely have an `IDX` attribute you can use in `to_array`. I was surprised it wasn't there! That should actually be all we need: I don't think we need a separate method.

**Comment by MisterKeefe** [comment]
OK great, that's easier! I've raised a PR :+1:

**Comment by svlandeg** [comment]
Closed by PR #5030 👍
