### ISSUE TITLE
'en' shortcut link issues with loading spacy 

### ISSUE THREAD

**Issue by yjnkwn** [explosion/spaCy#5042]
* On my Jupyer Notebook, when I try loading spacy by using the following command:
`nlp = spacy.load('en')`

* I get an error message: 
`OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.`

* I've read through the issues and StackOverflow
(https://github.com/explosion/spaCy/issues/1721)
 (https://stackoverflow.com/questions/54334304/spacy-cant-find-model-en-core-web-sm-on-windows-10-and-python-3-5-3-anacon)

* and tried the following: 

`'pip install - U spacy`

`import en_core_web_sm
en_core_web_sm.load()`

`!python -m spacy download en_core_web_sm`

`spacy.load("en_core_web_sm")`

`conda install -c conda-forge spacy`

* Each time I re-run the code to use spacy, I get the same error message. 

* Environment Information:

: `============================== Info about spaCy ==============================
spaCy version    2.2.3
Location         C:\Users\Anaconda3\lib\site-packages\spacy
Platform         Windows-10-10.0.18362-SP0
Python version   3.7.4
Models`

**Comment by yjnkwn** [comment]
To update, following this StackOverflow thread (https://stackoverflow.com/questions/54334304/spacy-cant-find-model-en-core-web-sm-on-windows-10-and-python-3-5-3-anacon), I tried: 

` python -m spacy download en_core_web_sm`
`python -m spacy link en_core_web_sm en`

`python -m spacy download en_core_web_lg`
`python -m spacy link en_core_web_lg en`

*  Downloading both lg and sm work successfully but linking throws me an error: 
`(base) C:\Users\>python -m spacy link en_core_web_sm en
You do not have sufficient privilege to perform this operation.
✘ Couldn't link model to 'en'
Creating a symlink in spacy/data failed. Make sure you have the required
permissions and try re-running the command as admin, or use a virtualenv. You
can still import the model as a module and call its load() method, or create the
symlink manually.`

**Comment by svlandeg** [comment]
Have you tried following the instructions in that last error message?

Also, it is not really necessary to use the `en` abbreviation. You should be able to just run `spacy.load('en_core_web_lg')` or `spacy.load('en_core_web_md')` and work with that. We will probably drop the usage of these symlinks such as `en` in future versions of spaCy anyway.
