### ISSUE TITLE
Spacy considers spelled-out numbers as stop words

### ISSUE THREAD

**Issue by AnishaMohandass** [explosion/spaCy#5045]
Why Spacy considers the spell-out numbers (one, five, thirty, etc.) as stop words?
![Screenshot (96)](https://user-images.githubusercontent.com/42888835/75031738-f513d280-54cc-11ea-9178-3674db8cfedc.png)

* Operating System: Windows 8
* Python Version Used: 3.7.3
* spaCy Version Used: 2.2.3
* Environment Information: Anaconda``

**Comment by adrianeboyd** [comment]
Stop words depend a lot of your task, so you can think of the list provided by spacy as one suggestion, but you'll frequently want to customize it:

```
import spacy
nlp = spacy.load('en')
assert nlp.vocab["eleven"].is_stop == True
# remove 'eleven' as a stop word
nlp.vocab["eleven"].is_stop = False
assert nlp.vocab["eleven"].is_stop == False
```

**Comment by AnishaMohandass** [comment]
I think numbers are important information that we don't want to dispose of.
Thanks for your response @adrianeboyd !
