### ISSUE TITLE
LEMMA "Russia" doesn't match  "Russian"

### ISSUE THREAD

**Issue by vbaidin** [explosion/spaCy#5046]
## How to reproduce the behaviour

matcher = Matcher(nlp.vocab)
pattern = [{'LEMMA': "Russia"}]
matcher.add('Russia', None, pattern)
doc = nlp("I from Russia and have Russian dog")
matches = matcher(doc)
matches

## Your Environment

* Operating System: Win10
* Python Version Used: 3.8
* spaCy Version Used: 2.2
* Environment Information:

**Comment by svlandeg** [comment]
In principle the `Matcher` should work just fine on the lemma, but the trouble is that "Russian" isn't being lemmatized to "Russia" in this sentence:
```
    nlp = spacy.load('en_core_web_sm')
    text = "I'm from Russia and I have a Russian dog"
    doc = nlp(text)
    print([(token.text, token.lemma_) for token in doc])
```
gives
```
[('I', '-PRON-'), ("'m", 'be'), ('from', 'from'), ('Russia', 'Russia'), ('and', 'and'), ('I', '-PRON-'), ('have', 'have'), ('a', 'a'), ('Russian', 'russian'), ('dog', 'dog')]
```
If we would set `doc[8].lemma_ = "Russia"` you'll see that the Matcher works.

With respect to getting better lemmatization, this could definitely be improved much, and we're currently working on that. I will close this here in the meantime.

**Comment by adrianeboyd** [comment]
@svlandeg: `Russian` shouldn't be lemmatized to `Russia` because this is derivational and not inflectional.
