### ISSUE TITLE
detecting opposite Sentences

### ISSUE THREAD

**Issue by snape6666** [explosion/spaCy#5053]
Hi,
i was wondering if there is any implementation for german sentences, wich is able to detect opposite sentences or neutral sentences.

The background is the following:

i want to analyse new requirement-sentences with all already saved requirements and automaticaly wanna find requirements wich are similar, the opposite or not related to the new requirement.

Does anybody know if there is something like that out there? For similarity we already use https://github.com/UKPLab/sentence-transformers wich works perfectly to find similarities. Now i would like to have something similar for "opposite" sentences.

Thx in advance.

**Comment by adrianeboyd** [comment]
No, there's nothing built-in to spacy that does this. You will need to look for other resources and tools.
