### ISSUE TITLE
How to improve NER on random capitalized characters in a word

### ISSUE THREAD

**Issue by shuson** [explosion/spaCy#5055]
Hi guys, I am trying SpaCy's pretrained model to do NER task. It works fine when I feed it normal text. For example, "In Stanford, I eat apple everyday, and buy Apple stock every week.", SpaCy can correctly give me "Stanford", "Apple" as ORG. 

However, for "In Stanford, I create Audit Report every month". And it would give me "Audit Report" as ORG.

You know some free text articles, people just randomly or purposely capitalize first character of some words, for no reason. 

Is there any advice to let SpaCy ignore those words?

**Comment by adrianeboyd** [comment]
Sorry, no, there's no easy way to handle this within spacy.

You might look into "truecasing" and see if it's helpful to normalize your texts in this way before analyzing them with spacy's default NER model.
