### ISSUE TITLE
Matcher support for searching on a Span, as well as a Doc

### ISSUE THREAD

**Issue by paoloq** [explosion/spaCy#5056]
## Feature description

It would be nice to have support for running pattern matching on Span, as well as Doc.
Sometimes it could be not necessary to perform the pattern searching in the whole document, but in some sentences or, more generally, spans only.

I already implemented and partially tested a solution locally, any downside I'm not aware of in terms of policies or code design constraints for this kind of feature?

Here are some of my changes in the matcher.pyx:
```
def __call__(self, doc_or_span):
        """ ... """
        if isinstance(doc_or_span, Doc):
            doc = doc_or_span
        elif isinstance(doc_or_span, Span):
            doc = doc_or_span.doc
        else:
            raise ValueError()
        
        ...

        length = (
            (doc_or_span.end - doc_or_span.start)
            if isinstance(doc_or_span, Span) else len(doc)
        )
        matches = find_matches(&self.patterns[0], self.patterns.size(), doc_or_span, length, 
                                extensions=self._extensions, predicates=self._extra_predicates)
```
where `find_matches` changes accepting `doc_or_span` and `length` as new parameters:
```
cdef find_matches(TokenPatternC** patterns, int n, doc_or_span, int length, extensions=None, predicates=tuple()):
        ...
```

**Comment by svlandeg** [comment]
Thanks a lot for your contribution! It's now merged, and will be included in the next release of spaCy, probably 2.3 (or otherwise 3.0) 👍
