### ISSUE TITLE
`user_hooks` serialization

### ISSUE THREAD

**Issue by MartinoMensio** [explosion/spaCy#5057]
## Feature description

Hi! I am having an issue with serialization of `Doc` objects that have `user_hooks`.
What I am trying to do, is to compute the `vectors` property of `Doc` objects by using a custom pipeline component that takes the value from a custom extension and sets the `vector` thanks to `doc.user_hooks`. 

After deserializing a `Doc` object, I can see the extension (correctly deserialised) but the `doc.vector` is not correctly shown because the `doc.user_hooks` results as empty.
This code shows in details

```python
import spacy
import numpy as np
from spacy.tokens import Doc, Span


def get_encoding(token_span_doc):
    return np.ones((5,5), dtype=np.float32)

def overwrite_vectors(doc):
    doc.user_hooks["vector"] = lambda a: a._.special_vector
    doc.user_span_hooks["vector"] = lambda a: a._.special_vector
    doc.user_token_hooks["vector"] = lambda a: a._.special_vector
    return doc

def get_nlp():
    nlp = spacy.load('en_core_web_sm')
    nlp.add_pipe(overwrite_vectors)
    return nlp

Doc.set_extension('special_vector', getter=get_encoding, force=True)
Span.set_extension('special_vector', getter=get_encoding, force=True)
nlp = get_nlp()

print(nlp.pipe_names)
# ['tagger', 'parser', 'ner', 'overwrite_vectors']

# create a doc
doc = nlp('Hi there I would like to serialize the user_hooks')
span = doc[1:5]

print(span._.special_vector.shape)
# (5, 5) the shape of the special vector
print(doc.user_hooks)
print(doc.user_span_hooks)
# {'vector': <function overwrite_vectors.<locals>.<lambda> at 0x145983950>}
print(span.vector.shape)
# the same as the extension

doc_bytes = doc.to_bytes()

# restore doc
doc = Doc(nlp.vocab).from_bytes(doc_bytes)
span = doc[1:5]

print(span._.special_vector.shape)
# (5, 5) as before
print(doc.user_hooks)
print(doc.user_span_hooks)
# empty {}
print(span.vector.shape)
# (96,) from the default tensors
```

If it was only on the `doc` I could simply set the `vector` property, but I need to setup the hooks in order to be able to assign the vector to the Tokens and Spans with a model that provides encodings.
I need a way to have the `vector` in `doc.user_hooks` after I restore from disk (or an equivalent alternative). I am using this code to wrap a call to TensorFlow Hub and I need to overwrite the vector with a call to a TensorFlow model https://github.com/MartinoMensio/spacy-universal-sentence-encoder-tfhub/blob/master/universal_sentence_encoder/language.py .

Alternatively, Is there an easy way to tell SpaCy to use a custom `Doc` class with an overridden `from_bytes` method that sets the `user_hooks`? I could not find a similar example.

The span vectors cannot be just computed as a simple operation from the token vectors (e.g. mean), neither be precomputed on all the possible spans, so I need to restore an object that triggers my function `get_encoding` to get the vector after deserialization.

Thanks in advance for any help.

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
If so, we will tag it as [`project idea`](https://github.com/explosion/spaCy/labels/project%20idea) so other users can take it on.

This is related to custom components but shouldn't be itself a custom component.

**Comment by svlandeg** [comment]
You are right that the `user_hooks` are not being serialized in `Doc.to_bytes()`.
Fortunately, there is a workaround using `pickle`. If you replace these lines
```
doc_bytes = doc.to_bytes()
doc = Doc(nlp.vocab).from_bytes(doc_bytes)
```
with

```
b = pickle.dumps(doc)
doc = pickle.loads(b)
```
You'll see that you get your expected output:
```
['tagger', 'parser', 'ner', 'overwrite_vectors']
(5, 5)
{'vector': <function overwrite_vectors.<locals>.<lambda> at 0x000001C44C36DF28>}
{'vector': <function overwrite_vectors.<locals>.<lambda> at 0x000001C44C36DE18>}
(5, 5)
(5, 5)
{'vector': <function overwrite_vectors.<locals>.<lambda> at 0x000001C456408598>}
{'vector': <function overwrite_vectors.<locals>.<lambda> at 0x000001C456408A60>}
(5, 5)
```
Hopefully that works for your use-case?
