### ISSUE TITLE
Option to average vectors when using "merge_entity" pipeline.

### ISSUE THREAD

**Issue by mitchelldehaven** [explosion/spaCy#5082]
Would it be possible to have an option for averaging the vectors of merge entities when using the "merge_entities" pipeline? For example, when named entities are represented as a Span in doc.ents, you can have a vector representation which is the average over the vectors in the Span. When using the merge_entities pipeline, the vector representation of the entity is a zero vector.

**Comment by svlandeg** [comment]
I think that would make sense - cf. PR #5085 !
