### ISSUE TITLE
Set sentiment on Span

### ISSUE THREAD

**Issue by thomasthiebaud** [explosion/spaCy#5087]
It is not possible to set the `sentiment` property on a `Span`. Here is the a small snipet to reproduce that

```
import spacy

nlp = spacy.load('en_core_web_sm')
doc = nlp("This is a sentence. Here is another one.")
doc.sentiment = 1 # Works fine

for sentence in doc.sents:
  sentence.sentiment = 1 # Does not work
```

It fails with

```
AttributeError: attribute 'sentiment' of 'spacy.tokens.span.Span' objects is not writable
```

Is there a setter to call instead? I tried `set_sentiment` without success. Am I missing something? Is it a bug?

**Comment by thomasthiebaud** [comment]
A workaround would be to use `extension attribute`

```
import spacy
from spacy.tokens import Span

nlp = spacy.load("en_core_web_sm")
doc = nlp("This is a sentence. Here is another one.")
doc.sentiment = 1  # Works fine

Span.set_extension("sentiment", default=None)

for sentence in doc.sents:
    sentence._.sentiment = 1 # Works fine
    print(sentence._.sentiment) 
    sentence.sentiment = 1  # Does not work
```

but that sounds wrong if there is a `sentiment` field on the `Span`

**Comment by svlandeg** [comment]
You can find the implementation of `Span.sentiment` [here](https://github.com/explosion/spaCy/blob/master/spacy/tokens/span.pyx#L495). You can see it is indeed not writable, because it either looks up the value in `self.doc.user_span_hooks`, or takes the average of `token.sentiment` for the tokens in that span.

That also provides you with an easy workaround: you can just set the sentiment for each token in the span.

**Comment by thomasthiebaud** [comment]
But my model cares about sentences (Span) and approximating the sentiment by the mean of the sentiment on the token is huge

**Comment by svlandeg** [comment]
If that doesn't work for your application, you can use `doc.user_span_hooks` :-)

**Comment by svlandeg** [comment]
(as a bit more explanation: currently, spans are always views, which is why you can't easily set fields on them. this might be revised in the future)

**Comment by thomasthiebaud** [comment]
For reference https://stackoverflow.com/questions/60502140/how-to-set-the-sentiment-attribute-on-a-span
