### ISSUE TITLE
Streamlit app doesn't show arc labels with displaCy

### ISSUE THREAD

**Issue by shovalsa** [explosion/spaCy#5089]
Trying out your displaCy+streamlit gist as is, the output tree doesn't show arc labels:
![image](https://user-images.githubusercontent.com/24814427/75773214-1d65c180-5d56-11ea-8adf-0ac907299d98.png)

However, rendering the output svg in a simple html file yields the desired image:
![image](https://user-images.githubusercontent.com/24814427/75773329-5a31b880-5d56-11ea-9351-47a53c0f55a7.png)

There is a solution that worked for me and might be a good idea to include in the formal gist (following [this](https://discuss.streamlit.io/t/display-svg/172/5) solution on streamlit discussion board).
```
def render_svg(svg):
    """Renders the given svg string."""
    b64 = base64.b64encode(svg.encode('utf-8')).decode("utf-8")
    html = r'<img src="data:image/svg+xml;base64,%s"/>' % b64
    st.write(html, unsafe_allow_html=True)
...
    for sent in docs:
        html = displacy.render(sent, options=displacy_style_options, style="dep")  # svg object
        # Double newlines seem to mess with the rendering
        html = html.replace("\n\n", "\n")
        if split_sents and len(docs) > 1:
            st.markdown(f"> {sent.text}")
        render_svg(html)
```

## Environment
* **spaCy version:** 2.2.1
* **Platform:** Linux-5.3.0-40-generic-x86_64-with-debian-buster-sid
* **Python version:** 3.7.4

**Comment by svlandeg** [comment]
Thanks a lot for the report, the analysis and the fix! I double checked and could reproduce all your results. The fix is commited in PR https://github.com/explosion/spaCy/pull/5168 and the new example script will be distributed with spaCy 3.0 onwards.
