### ISSUE TITLE
serializing phrase matcher to_disk.

### ISSUE THREAD

**Issue by tahirahmad2030** [explosion/spaCy#5096]
## Feature description

Dump phrasematcher object to load it back later.
 
## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
If so, we will tag it as [`project idea`](https://github.com/explosion/spaCy/labels/project%20idea) so other users can take it on.

EntityRuler https://github.com/explosion/spaCy/blob/master/spacy/pipeline/entityruler.py does have a method(to_disk ) to serialize the ruler however phrasematcher https://github.com/explosion/spaCy/blob/master/spacy/matcher/phrasematcher.pyx doesn't have that option yet. How can we serialize phrasematcher in spacy. I am currently using pickle to persist it but is there a better way like we see in Entity ruler?

**Comment by adrianeboyd** [comment]
`pickle` is the right method to use for serializing `Matcher` and `PhraseMatcher` objects. There's not a good (safe) way to serialize the callback functions with the approach used for other components in `to_disk()/from_disk()`.
