### ISSUE TITLE
Distinguish between Subjects and properties

### ISSUE THREAD

**Issue by yano27** [explosion/spaCy#5103]
Hello,

I would like to know if spaCy have the ability to distinguish between subject components and properties. 

The examples of are as follows:
Die **Tür** des Autos sollte aus Metall sein. --> Tür == Subcomponent from Auto
Die **Farbe** des Autos sollte gelb sein. --> Farbe == Property or Attribute from Auto
Another examples for attribute: Geschwindigkeit, Beschleunigung, and Bankleitzahl.

I have already tried the NER trainings method from spacy and the result from the losses precentage from 30 iteration is around 0.5. Some of the new Entity can be detected correctly and some of them are not detected or detected incorrectly. The correctly detected entity are occured in my training data around 5 times or more. In the documentation from spaCy, the train data of the word "horse" occured 6 times. My questions is, if the occurence of the new words in the training data must be more than 5 to be detected correctly? Or if there is any aspects that I should add to improve the results? 

If my approach is false, could you suggest an alternative solution for my problem. Thanks before!

Cheers,
Ryan

## Your Environment

* Operating System: Windows
* Python Version Used: 3.6
* spaCy Version Used: 2.1.8
* Environment Information: de_core_news_md 2.1.0

**Comment by adrianeboyd** [comment]
No, not really. I don't think the NER model is going to be a good match for this task. You could potentially use it to identify the components like "Tür", but probably not to identify relations between components.

I think typical approaches would build a knowledgebase that contains information about "part-whole" and other types of relations for a particular domain.

**Comment by yano27** [comment]
Thank you for your reply. I'll try that approach then.
