### ISSUE TITLE
doc.is_nered returns True for empty doc

### ISSUE THREAD

**Issue by Tiljander** [explosion/spaCy#5117]
## How to reproduce the behaviour
```
nlp = spacy.load('en')
empty_doc = nlp("")
print(list(empty_doc.ents)) # --> Returns []
empty_doc.is_nered   # --> Returns True
```

According to **is_nered** definition, atleast 1 token must have a named entity tag set. **doc.is_nered** should therefore return False for an empty doc.

```
def is_nered(self):
        """Check if the document has named entities set. Will return True if
        *any* of the tokens has a named entity tag set (even if the others are
        unknown values).
        """
        if len(self) == 0:
            return True         # <----- SHOULD BE FALSE
        for i in range(self.length):
            if self.c[i].ent_iob != 0:
                return True
        return False
```

## Your Environment

* **spaCy version:** 2.2.2
* **Platform:** Windows-10-10.0.17134-SP0
* **Python version:** 3.8.0
* **Models:** en

**Comment by adrianeboyd** [comment]
It's tricky to decide what these flags should mean for empty documents, but the general decision has been that empty docs are tagged/parsed/nered:

```
>>> import spacy
>>> nlp = spacy.load('en')
>>> doc = nlp("")
>>> doc.is_parsed
True
>>> doc.is_tagged
True
>>> doc.is_nered
True
```

You're right that this isn't explained in the docs, which should be improved to make this clearer.

**Comment by svlandeg** [comment]
We updated the docs to avoid this confusion, cf. https://github.com/explosion/spaCy/pull/5127
