### ISSUE TITLE
Issues while importing spacy in jupyter

### ISSUE THREAD

**Issue by ApoorvaRani93** [explosion/spaCy#5118]
Installed spacy and reinstalled again using conda method as an administrator and getting import error on jupyter!!! can anyone please tell me the steps on how to reinstall or uninstall Im quite new to this so a detailed solution is appreciated.

ImportError: cannot import name 'msgpack' from 'thinc.neural._classes.model' (C:\Users\rania\Anaconda3\envs\nlp_course\lib\site-packages\thinc\neural\_classes\model.py)

```

## Your Environment
* **spaCy version:** 2.2.3
* **Platform:** Windows-10-10.0.18362-SP0
* **Python version:** 3.7.3
* **Models:** en

**Comment by svlandeg** [comment]
Your safest bet is probably to start with an entirely new virtual environment, see [here](https://docs.python.org/3/tutorial/venv.html).
