### ISSUE TITLE
Multiprocess slows down a lot?

### ISSUE THREAD

**Issue by lingvisa** [explosion/spaCy#5119]
Spacy 2.2.3
Ubuntu 18

I have a plain text file of 238MB, around 200,000 lines. My code is the following:
```
def regular_spacy():
    nlp = spacy.load("en_core_web_lg")
    nlp.disable_pipes(['tagger', 'ner', 'parser'])

    lines = []
    print('Loading file ...')
    with open(os.path.join(abspath, datafile), 'r', encoding='utf8') as f:
        for line in f:
            lines.append(line)

    print("Processing file ...")

    token_list = []
    docs = nlp.pipe(lines, n_process=-1)
    for doc in docs:
        token_list.append([(tok.lemma_, tok.pos_) for tok in doc if not tok.is_stop and tok.text])
    return token_list
```

When n_process = '1' , the total time spent is: 2.3 minutes, and when n_process = '-1', it takes 5.4 minutes. However, when I add the 'tagger' back to the pipeline by doing:
` nlp.disable_pipes(['ner', 'parser']) `

Multiprocessing takes 11 minutes and singleprocessing takes 18 minutes. In this case, it is indeed speeding up. But why multiprocessing is almost 3 times slower when it is doing tokenization only. 

The system monitor shows the cpu usage is stably around 20% with multi-processing, even though multiple python processes are showing.  With single processor, only about 15% cpu is used.   

Probably I should follow the joblib example for multiprocessing?

**Comment by adrianeboyd** [comment]
There's a lot of overhead in multiprocessing (serializing data and making copies of model data in memory), so depending on how large the model is, how CPU-intensive the tasks are, etc., the performance differences due to multiprocessing can vary.

For tokenizing a relatively small number of texts, `nlp.pipe(n_process=1)` can be the best option.

**Comment by lingvisa** [comment]
238MB of text is a decent size. I will try the joblib option.

**Comment by jesusfbes** [comment]
I am interested in your results here

**Comment by svlandeg** [comment]
I'll assume the original question got properly addressed by Adriane and will go ahead and close this.
