### ISSUE TITLE
 I'm getting SystemExit: 2 error how can I fix this?

### ISSUE THREAD

**Issue by Sunil4423** [explosion/spaCy#5123]
this is the code i'm used 
# construct the argument parse and parse the arguments
ap = argparse.ArgumentParser()
ap.add_argument("-i", "--image", required=True,
	help="path to input image")
ap.add_argument("-p", "--prototxt", required=True,
	help="path to Caffe 'deploy' prototxt file")
ap.add_argument("-m", "--model", required=True,
	help="path to Caffe pre-trained model")
ap.add_argument("-l", "--labels", required=True,
	help="path to ImageNet labels (i.e., syn-sets)")
args = vars(ap.parse_args())

and i'm getting the output as 
usage: ipykernel_launcher.py [-h] -i IMAGE -p PROTOTXT -m MODEL -l LABELS
ipykernel_launcher.py: error: the following arguments are required: -i/--image, -p/--prototxt, -m/--model, -l/--labels

An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

**Comment by adrianeboyd** [comment]
Hmm, I'm not sure this issue is related to spacy. Could you provide a minimal working example that shows what you're trying to do?

**Comment by Sunil4423** [comment]
**i'm work on **_deep_learning_with_opencv.py_**
this is  my minimal working codes** 

import numpy as np
import argparse
import time
import cv2

 **construct the argument parse and parse the arguments**
ap = argparse.ArgumentParser()
ap.add_argument("-i", "--image", required=True,
	help="path to input image")
ap.add_argument("-p", "--prototxt", required=True,
	help="path to Caffe 'deploy' prototxt file")
ap.add_argument("-m", "--model", required=True,
	help="path to Caffe pre-trained model")
ap.add_argument("-l", "--labels", required=True,
	help="path to ImageNet labels (i.e., syn-sets)")
args = vars(ap.parse_args())

**And the output is** 
usage: ipykernel_launcher.py [-h] -i IMAGE -p PROTOTXT -m MODEL -l LABELS
ipykernel_launcher.py: error: the following arguments are required: -i/--image, -p/--prototxt, -m/--model, -l/--labels

An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

**Comment by adrianeboyd** [comment]
Sorry, this isn't the right place! This issue tracker is just for bug reports and questions related to spacy (https://spacy.io).
