### ISSUE TITLE
wrong sentence split on english model small 2.2.5

### ISSUE THREAD

**Issue by MartinoMensio** [explosion/spaCy#5124]
Hi,

I have an issue with the sentencizer of the `en_core_web_sm` model.

## How to reproduce the behaviour

This applies to the models version 2.2.5.

Code to reproduce:
```python
import spacy
nlp_sm = spacy.load('en_core_web_sm')
nlp_md = spacy.load('en_core_web_md')

text = '''Mr Johnson was asked why he did not visit the flooded communities sooner as she was shown flood defences by the Environment Agency (EA) in Bewdley.

"It's too easy for a PM to come to a place in a middle of an emergency, it's not so easy frankly for the emergency services," he said.

"What I've been doing since the flooding began is co-ordinating the national response but also looking at what we can do in the next months and years to ensure this country really is ready to cope with the impacts of flooding."'''

doc_sm = nlp_sm(text)
sents_sm = list(doc_sm.sents)
doc_md = nlp_md(text)
sents_md = list(doc_md.sents)

print(sents_sm[1])
# "It's too easy for a PM to come to a place in a middle of an emergency
print(sents_sm[2])
# , it's not so easy frankly for the emergency services," he said.
#
#
print(sents_md[1])
# "It's too easy for a PM to come to a place in a middle of an emergency, it's not so easy frankly for the emergency services," he said.
# 
# 
# 
```

The medium and large models split correctly the sentence, while the small one fails (there is an unwanted sentence split).

## Your Environment

* **spaCy version:** 2.2.3
* **Platform:** Darwin-19.3.0-x86_64-i386-64bit
* **Python version:** 3.7.6
* Operating System: macOS Catalina 10.15.3

Spacy models (`spacy validate`):
```
package   en-core-web-sm              en_core_web_sm              2.2.5   ✔
package   en-core-web-md              en_core_web_md              2.2.5   ✔
package   en-core-web-lg              en_core_web_lg              2.2.5   ✔
```

**Comment by MartinoMensio** [comment]
Instead this text produces wrong sentence split on the `md` package (correct results on the `sm` and `lg` ones):

```python
text = '''Brits are facing more heavy downpours with up to four inches of rain and 50mph winds set to batter the UK on Monday.

The atrocious weather shows little signs of abating, with Brits suffering a fifth consecutive wet weekend.'''
```

Shouldn't the sentencizer be the same on the three models?

**Comment by adrianeboyd** [comment]
The sentence boundaries are predicted by the parser, which makes different predictions for each model size because each has a different configuration for its pretrained word vectors.

It's a little unusual for an NLP tool to have the parser be the source of sentence boundaries, but it works well in practice because the parser is good at identifying phrase boundaries, so it can work relatively well even if the punctuation or capitalization is missing or noisy.

**Comment by MartinoMensio** [comment]
Thanks @adrianeboyd  for the explanation. I tested the 2.2.0 version of the models, and it is performing good on these samples. I see that the [model releases](https://github.com/explosion/spacy-models/releases//tag/en_core_web_sm-2.2.5) are usually accompanied by the accuracy metrics, so I wonder if there are some stats also for the sentencization task.
Just to know if I'm just unlucky with these samples that I found. 

For my task I am using multiple models at the same time and I need to rely on the same sentencization.
I discovered that if I add the default rule-based sentencizer as first step of the pipeline, I can get the same division of sentences with multiple models.

From an initial analysis, the performance looks better than the sentencization caused by the statistical parsing because in my data the punctuation and capitalization is quite reliable.

```python
import spacy
nlp = spacy.load('en_core_web_sm')
sentencizer = nlp.create_pipe('sentencizer')
nlp.add_pipe(sentencizer, first=True)
```

**Comment by adrianeboyd** [comment]
If you have formal / edited text and you need the same sentence boundaries across models then the sentencizer is a good choice.

I've added metrics for sentence boundary detection in the upcoming spacy v3, but I'm not sure the numbers would help you a whole lot here. Off the top of my head, I think on our English evaluation data the `md` model is slightly better than the other two, but the differences are quite small. I think the f-score for English is around 95-96, but I'd have to double-check to be sure. Here are the only numbers I can find easily, just for the `sm` model: https://github.com/explosion/spaCy/pull/4713. The new statistical `SentenceRecognizer` component will also be included in v3, so you can train on your own data without needing full dependency parses.

I think the best way to know would be to go through a sample of your data and evaluate the performance.

**Comment by MartinoMensio** [comment]
Thank you very much for the details. That's super useful to know.

**Comment by svlandeg** [comment]
Hoping that this was sufficiently answered, I'll go ahead and close this issue :-)
