### ISSUE TITLE
Is there a way to access matched tokens or chunks in Matcher?

### ISSUE THREAD

**Issue by lingvisa** [explosion/spaCy#5128]
The rule is as follows:
``[{"TEXT": "US"}, {"TEXT": "is"}, {"TEXT": "United States"}]``

And this rule is placed in a json file. I want to extract 'same_as' relations from text.:
`US same_as Unites States`

In order for this to be working, there is a need to access the head and tail tokens in the relation, because you won't want the whole pattern to be the output, and the pattern could be any length. The syntax could be something like this:
`[{"TEXT": "US" ^head}, {"TEXT": "is"}, {"TEXT": "United States" ^tail}]`

Then the caller has a way to get this two tokens/chunks back:
```
US=^head
United States = ^tail
```

The current implementation shouldn't be able to support this, or something like this. Right? Otherwise, this logic has to be implemented in python code, not in separate json file. A few rules are ok by hard coding in source python file, but i won't scale up. Those patterns should stand alone in json files, to make them scale up. 

Any suggestions?

**Comment by adrianeboyd** [comment]
No, this isn't currently possible, see #3275.
