### ISSUE TITLE
Clarification on python -m spacy pretrain usage

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#5133]
Which page or section is this issue related to?
https://spacy.io/api/cli#pretrain

Say I have a large amount of unlabeled text (from which I labelled some for NER and also created word2vec model from)  

1) regarding the text
- How long does each `text` need to be in the jsonl file?  Can I use spacy sentencizer to create these strings?  Or do they need to be much longer (say a whole document of text)?

2) regarding vectors
- I used as the vectors the word2vec model I created using all the text.  Is this correct?

3) usage
- How can I use the output of the pretraining in your train_ner.py script https://github.com/explosion/spaCy/blob/master/examples/training/train_ner.py
- Also do I include the word vectors I used above during pretraining?

**Comment by erotavlas** [comment]
Any guidance on this would be appreciated.

**Comment by yuhui-zh15** [comment]
Same here. Really appreciate any documentation about how to incorporate `pretrain` into NER training.

**Comment by erotavlas** [comment]
@yuhui-zh15  I found this blog post https://explosion.ai/blog/spacy-v2-1  It has some useful info.

**Comment by yuhui-zh15** [comment]
@erotavlas Thanks! This is helpful.

**Comment by svlandeg** [comment]
This was still experimental and consequently not so well documented in v.2. We're currently working on additional experiments with `pretrain` for version v.3. We'll also include more documentation, and config files that will make it much easier to first run pretrain, and then use the results in a downstream training task.

Closing this issue for now - stay tuned for spaCy 3.0 ;-)
