### ISSUE TITLE
'spacy.syntax.nn_parser.array' has no attribute '__reduce_cython__'

### ISSUE THREAD

**Issue by sandilya45** [explosion/spaCy#5136]
I have tried to import spacy after installation of latest version and below is the error i am facing. Although i have checked multiple blogs, the fix has not been discussed anywhere. Please help me in resolving this issue.

```bash
~\Anaconda3\lib\site-packages\spacy\__init__.py in <module>
     10 from thinc.neural.util import prefer_gpu, require_gpu
     11 
---> 12 from . import pipeline
     13 from .cli.info import info as cli_info
     14 from .glossary import explain

~\Anaconda3\lib\site-packages\spacy\pipeline\__init__.py in <module>
      2 from __future__ import unicode_literals
      3 
----> 4 from .pipes import Tagger, DependencyParser, EntityRecognizer, EntityLinker
      5 from .pipes import TextCategorizer, Tensorizer, Pipe, Sentencizer
      6 from .morphologizer import Morphologizer

pipes.pyx in init spacy.pipeline.pipes()

~\Anaconda3\lib\site-packages\spacy\syntax\nn_parser.cp37-win_amd64.pyd in init spacy.syntax.nn_parser()

AttributeError: type object 'spacy.syntax.nn_parser.array' has no attribute '__reduce_cython__
```

## Your Environment

* Operating System: Win 10
* Python Version Used: 3.6
* spaCy Version Used: 2.2.3
* Environment Information:

**Comment by adrianeboyd** [comment]
Usually this indicates that some older files didn't get cleaned up properly by pip or conda when you upgraded. Try uninstalling spacy completely before reinstalling a newer version, and if it still isn't working, try installing spacy in a brand new virtual environment.
