### ISSUE TITLE
✘ No compatible models found for v2.2.4 of spaCy

### ISSUE THREAD

**Issue by jklaise** [explosion/spaCy#5140]
## How to reproduce the behaviour
Upgrading spacy to `2.2.4` and running the command to download a model:
```
python -m spacy download en_core_web_md 
```
results in an error:

```
✘ No compatible models found for v2.2.4 of spaCy
```

## Your Environment      
* **spaCy version:** 2.2.4
* **Platform:** Linux-5.4.15-arch1-1-x86_64-with-arch
* **Python version:** 3.7.3

**Comment by adrianeboyd** [comment]
Thanks for the report! We'll get this updated quickly...

**Comment by svlandeg** [comment]
Fixed by https://github.com/explosion/spacy-models/pull/32 I think ?

**Comment by kleczekr** [comment]
Hi! Downloading German model seems to work fine, but trying to do this:
!python -m spacy download pl_core_news_sm
results in error:
✘ No compatible model found for 'pl_core_news_sm' (spaCy v2.2.4).
(using Jupyter notebook on Colab)

**Comment by adrianeboyd** [comment]
The Polish models were added in spacy v2.3, so you'll need to upgrade to spacy 2.3.x in colab (the most recent version is currently 2.3.2) to use them.
