### ISSUE TITLE
overwritting customer extension attribute example doesn't work

### ISSUE THREAD

**Issue by blaco78** [explosion/spaCy#5142]
## How to reproduce the behaviour
import spacy
from spacy.tokens import Token

# Register a custom token attribute, token._.is_musician
Token.set_extension("is_musician", default=False)

nlp = spacy.load("en_core_web_sm")
doc = nlp("I like David Bowie")
print("Before:", [(token.text, token._.is_musician) for token in doc])

with doc.retokenize() as retokenizer:
    retokenizer.merge(doc[2:4], attrs={"_": {"is_musician": True}})
print("After:", [(token.text, token._.is_musician) for token in doc])

## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.7
* spaCy Version Used:spacy 2.2.4-cp36-cp36m-win_amd64.whl
* Environment Information:

**Comment by blaco78** [comment]
I forgot the error message...

_retokenize.pyx in spacy.tokens._retokenize.Retokenizer.__exit__()

_retokenize.pyx in spacy.tokens._retokenize._merge()

TypeError: an integer is required

**Comment by adrianeboyd** [comment]
Thanks for the report! I tried to replicate this, but both the website example (with v2.2.0) and a local test (with v2.2.4) run as expected for me.

Sometimes old files aren't cleaned up correctly when you upgrade to a newer version of spacy -- could you try installing spacy in a brand new virtual environment and see if you still run into the same problems?

If that doesn't help, could you provide the full error message and traceback (use \`\`\` on a separate line before and after the code block to keep the original formatting)?

**Comment by blaco78** [comment]
You were right. I re did the installation and it works fine now.
Thanks you
