### ISSUE TITLE
incorrect behavior of spacy.tests.util.assert_docs_equal

### ISSUE THREAD

**Issue by tamuhey** [explosion/spaCy#5144]
```python
import spacy
from spacy.tests.util import assert_docs_equal

nlp = spacy.load("en_core_web_sm")
text = "This is a sentence"
doc1 = nlp(text)
doc2 = nlp(text)
assert_docs_equal(doc1, doc2) # raise error
```

spacy version: master

**Comment by adrianeboyd** [comment]
Thanks for the report! `Span` comparisons were modified in #5005, so now spans from different documents are never equal. I think this test could be updated to check the `Token.is_sent_start` values instead.

**Comment by tamuhey** [comment]
Or simply compare `sent.text` instead of `sent`?
