### ISSUE TITLE
may you help me?

### ISSUE THREAD

**Issue by hotse827** [explosion/spaCy#5145]
## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by svlandeg** [comment]
Hi @hotse827. This issue tracker is focused specifically on bug reports and issues for the spaCy library. If you have an issue, please describe it and provide some example code to help us better understand & debug. If you have more general code questions or want advice on a specific use-case, a forum like [Stackoverflow ](https://stackoverflow.com/questions/tagged/spacy)is probably more useful as you will reach more people through there.
