### ISSUE TITLE
Roadmap for SpaCy

### ISSUE THREAD

**Issue by nikhilsaldanha** [explosion/spaCy#5151]
Hi, 

**Some background:** We are a group of masters students from Delft University. We are studying SpaCy's architecture and are also looking to try and fix issues that we come across. We (among other student groups) will be documenting our findings in a series of blogs that can be found [here](https://desosa2020.netlify.com/).

During our study of the repository, we noticed that **SpaCy does not currently have a roadmap of features** on the website, blog or repository. The addition of a roadmap would make SpaCy more complete. It would be helpful to indicate to new users about the direction in which SpaCy is heading. It would also help new and existing contributors to raise and solve relevant issues for upcoming releases. Currently this is documented only in pinned issues which is hard to discover and navigate.

**We are willing to work with the maintainers to get the ball rolling on this.** To this end, we have studied multiple roadmaps and already have an idea about how it could be structured to be most effective.

This is a rough example template that we have in mind right now:

---

### Feature group 1
1. [Roadmap for SpaCy](https://github.com/explosion/spaCy/issues/5151): _description_

2. ~~\[Completed Issue\](link to closed issue): _description_~~ **Issue completed(link to PR)**

### Feature group 2
1. **Feature A:** _description_

## II. Features being considered for minor release 2.3.0
1. **Feature C:** _description_

## III. Long term features
1. **Feature E:** _description collecting together all threads where the feature was discussed_

**Comment by svlandeg** [comment]
Hi! 

Apologies for the late answer. 

Back in March we were hard at work at developing v3 of spaCy, and in the meantime we've published a few release candidates, currently referred to as the "nightly" releases. I think our vision on spaCy is clear from the changes we've made for this v3 version. You can find more details here: https://nightly.spacy.io/usage/v3

For new and existing users to [contribute](https://github.com/explosion/spaCy/blob/master/CONTRIBUTING.md) to the code-base, we like to refer to issues with the ["help wanted"](https://github.com/explosion/spaCy/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22+) and ["help wanted (easy)"](https://github.com/explosion/spaCy/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted+%28easy%29%22) labels, and new features can be discussed on the [Discussions forum](https://github.com/explosion/spaCy/discussions/categories/new-features-project-ideas), which is a great (new) place for community collaboration.
