### ISSUE TITLE
doc.similarity(token) got a confusing results betwwen different tokens

### ISSUE THREAD

**Issue by Raibows** [explosion/spaCy#5152]
## How to reproduce the behaviour
Hi, 
I'm trying to get a similarity between a sentence and a word.
```
import spacy
text = "Talk about being boring!<br /><br />I got this expecting a fascinating insight into the life of the man who wrote the mythical Night on the Galactic Railroad. I expected to see crazy stories and hijinks of an eccentric man and to discover his inspirations for such bizarre material. Boy, was I wrong.<br /><br />Spring and Chaos is mostly boring with only sporadic moments of innovative animation. It's certainly nothing to write home about and nowhere near as good as NOTGR which is something that I suggest you watch instead. Leave this bore alone. If you absolutely MUST see then either rent it or find it somewhere cheap. Do not pay top dollar."
nlp = spacy.load('en')
x = nlp('Talk')
y = nlp('let')
print(type(y))
print(type(y[0]))
print(len(y))
doc = nlp(text)
print(doc[0:x[0].i + 3].similarity(y[0])) ## error occured
```
The consoles prints erros as below if you take ``y=nlp('let')``:
![errorocc](https://user-images.githubusercontent.com/37944786/76685984-e5625680-6652-11ea-9b28-6ac0adca7c62.jpg)

What makes me confused is it works well if you take ``y=nlp('spell')`` or ``y=nlp('apple')`` or other words. The console prints well like below
![微信图片_20200315000757](https://user-images.githubusercontent.com/37944786/76685753-12156e80-6651-11ea-88b1-4b5d8e43a3d7.png)

## Your Environment

* Operating System: Ubuntu 18.04
* Python Version Used: 3.7.4
* spaCy Version Used: 2.0.16
* Environment Information: Anaconda, x64
* model compatibility is as below
![compatibility](https://user-images.githubusercontent.com/37944786/76685935-6d942c00-6652-11ea-935a-85524e33f774.png)

**Comment by svlandeg** [comment]
Thanks for the detailed report and analysis, it's very useful! This certainly looks like a bug - I can replicate it on my end. I'll have a look :-)

**Comment by svlandeg** [comment]
Fun bug. The reason it crashes on that specific case `'let'` and not on `'spell'` is because it only crashes when the number of characters in the token equals the number of tokens in the span (i.e. 3 in your example). Yes, I know that doesn't make sense, bugs rarely do ;-)

Fixed in https://github.com/explosion/spaCy/pull/5155, will be incorporated in spaCy v.3.0 onwards. 

Thanks for the nice find!
