### ISSUE TITLE
Pretrain command

### ISSUE THREAD

**Issue by CatarinaPC** [explosion/spaCy#5164]
I'm training my own French NER models using SpaCy and evaluating them along with SpaCy's French NER pre-trained models.

I wanted to experiment with the SpaCy pretrain command and see if I can improve my models. I have the JSONL file with raw texts.

I was trying to run something, following the example in [this](https://spacy.io/usage/v2-1) link:

`python3 -m spacy pretrain webhose.jsonl vectors_model? ./test`

However, I don't know what to put in the '`vectors_model`' parameter to have French vectors.

I tried running the example in the link (which is for English) but it gives an error:

```
catarinapc@catarinacpc:~//datasets/interim$ python3 -m spacy pretrain webhose.jsonl en_vectors_web_lg ./test
ℹ Not using GPU
✔ Saved settings to config.json
✔ Loaded input texts

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/catarinapc/.local/lib/python3.6/site-packages/spacy/__main__.py", line 33, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/home/catarinapc/.local/lib/python3.6/site-packages/plac_core.py", line 367, in call
    cmd, result = parser.consume(arglist)
  File "/home/catarinapc/.local/lib/python3.6/site-packages/plac_core.py", line 232, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/catarinapc/.local/lib/python3.6/site-packages/spacy/cli/pretrain.py", line 157, in pretrain
    nlp = util.load_model(vectors_model)
  File "/home/catarinapc/.local/lib/python3.6/site-packages/spacy/util.py", line 169, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_vectors_web_lg'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```

How do I make this work, in particular for French?

**Comment by erotavlas** [comment]
Did you download them first?

`python -m spacy download en_vectors_web_lg`

**Comment by adrianeboyd** [comment]
For French, provide a French model that contains vectors like `fr_core_news_md`. If you have your own vectors in the text word2vec format, you can create your own vectors model with `spacy init-model`.

**Comment by svlandeg** [comment]
> Or if spaCy comes with a French version you can try that. Not sure where to find it though.

You can find all models here: https://spacy.io/models. spaCy has two [French](https://spacy.io/models/fr) ones: `fr_core_news_sm` and `fr_core_news_md`.

I'll assume that @adrianeboyd answered the original question sufficiently and close this issue - if you run into any trouble, let us know.

**Comment by CatarinaPC** [comment]
Thank you

I've managed to run the command.

I'm using 72 249 737 tokens. It has been running for a few days and is still in iteration 35. I see that it will run for 1000 iterations. 

Do you think I can lower the number of iterations, and if so, what is the acceptable minimum number of iterations? 

Or, should I reduce the number of tokens?
