### ISSUE TITLE
How can we force the program to parse the text as one sentence?

### ISSUE THREAD

**Issue by daya0576** [explosion/spaCy#517]
``` python
text = u"Brando was born on April 3, 1924, in Omaha, Nebraska, to Marlon Brando, Sr., a pesticide and chemical feed manufacturer, and Dorothy Julia (nee Pennebaker)." 

doc = spacynlp(text)
sentences = [sent.string.strip() for sent in doc.sents]
print(sentences)
```
result: ['Brando was born on April 3, 1924, in Omaha, Nebraska, to Marlon Brando, Sr.', ', a pesticide and chemical feed manufacturer, and Dorothy Julia (nee Pennebaker).']

However, I want to parse the text as one sentence, how can I achieve that?

Thank u!

**Comment by honnibal** [comment]
It'd be good to surface something for this in the Python API, but for now you have to reach deep into the internals, and write a Cython function.

Take a look at the parsing loop [here](https://github.com/explosion/spaCy/blob/master/spacy/syntax/parser.pyx#L169):

```python

        while not state.is_final():
            self.model.set_featuresC(&eg, state)
            self.moves.set_valid(eg.is_valid, state)
            self.model.set_scoresC(eg.scores, eg.features, eg.nr_feat)

            guess = VecVec.arg_max_if_true(eg.scores, eg.is_valid, eg.nr_class)

            action = self.moves.c[guess]
            if not eg.is_valid[guess]:
                return 1

            action.do(state, action.label)
            memset(eg.scores, 0, sizeof(eg.scores[0]) * eg.nr_class)
            for i in range(eg.nr_class):
                eg.is_valid[i] = 1
```

The parser is a push-down automaton with a fixed inventory of actions, that each cause the state to be manipulated in a different way. At each state, we ask for the next valid actions, score the actions with the model, and then pick the best-scoring valid move. You can read more about the parsing algorithm [here](https://explosion.ai/blog/parsing-english-in-python), although the transition-system used by spaCy is a bit different (it's only described in an academic paper, that I wrote for EMNLP 2015).

For the dependency parser, the line `self.moves.set_valid(eg.is_valid, state)` results in a call to `ArcEager.set_valid`, implemented [here](https://github.com/explosion/spaCy/blob/master/spacy/syntax/arc_eager.pyx#L392). The action whose behaviour we need to change is the `Break` action, which introduces sentence breaks. You need to make a Cython module, subclass `ArcEager`, and overwrite this `set_valid` method. I suggest you set `is_valid[BREAK] = st.eol()`. This will make the `Break` action only valid when the buffer is exhausted, i.e. when you're at the end of the string.

**Comment by daya0576** [comment]
Thank you so much.  
I will spend some time to look deeper into it.
