### ISSUE TITLE
How does one use spaCy/displaCy in Rasa?

### ISSUE THREAD

**Issue by ganeshviyer** [explosion/spaCy#5171]
I'm able to use the spaCy NLP inside my Rasa pipeline, but I'm struggling to get displaCy working as well.  How do I include displaCy so that I can detect locations/GPE objects in a user utterance?

## Which page or section is this issue related to?
https://spacy.io/universe/project/rasa

**Comment by svlandeg** [comment]
Assuming `spacy` is installed as part of the dependencies, displaCy should be available through `from spacy import displacy`. The [docs](https://spacy.io/usage/visualizers) show some example code. 

What exactly have you tried to make it work? What are the errors you're getting?

**Comment by ganeshviyer** [comment]
Hello @svlandeg - thank you for your reply!  I can try this as part of my Rasa pipeline and see if I'm able to import it.  I did not find any documentation on how to use displaCy as part of Rasa so I don't have answers for your questions right now.

**Comment by ganeshviyer** [comment]
Hello @svlandeg, here's what I tried -
1. I used this image in my Docker file - https://hub.docker.com/layers/rasa/rasa/1.7.0-spacy-en/images/sha256-bffd11e9051751ee533102e4df20c25cd9aa4b1aa8ab3e2a649c3024e04ca36f?context=explore

2. I configured the pipeline to use the Spacy NLP.  Here are the components of the pipeline -
  - name: "SpacyNLP"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "RegexFeaturizer"
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: "SklearnIntentClassifier"

3. In my actions.py file, I tried to import spacy, but I got the error `ModuleNotFoundError: No module named 'spacy'`.  I think this is where I'm importing spacy incorrectly.

**Comment by svlandeg** [comment]
I haven't used Rasa myself, but it looks like it doesn't actually install `spacy` as part of its dependencies. You'll have to have spaCy installed to be able to use displaCy.

**Comment by ganeshviyer** [comment]
Hello @svlandeg, thank you for your response!  I'll re-evaluate how to get this configured and get back to you.  Feel free to close this issue.
