### ISSUE TITLE
CUDA 10.1 Support

### ISSUE THREAD

**Issue by danem** [explosion/spaCy#5175]
Seems like Spacy doesn't work with CUDA 10.1?

## How to reproduce the problem

```bash
> conda create --name spacytest python=3.8
> conda activate spacytest
> conda install -c conda-forge spacy                                                 ✘ 1 
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                              

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.1=0
  - feature:|@/linux-64::__cuda==10.1=0

Your installed CUDA driver is: 10.1

```

## Your Environment

* Operating System: Linux 5.3.0-40-generic #32~18.04.1-Ubuntu
* Python Version Used: 3.8
* spaCy Version Used:
* Environment Information: GIO_LAUNCHED_DESKTOP_FILE_PID=4650
TERMINATOR_DBUS_PATH=/net/tenshu/Terminator2
LANG=en_US.UTF-8
DISPLAY=:1
SHLVL=1
LOGNAME=ttt
XDG_VTNR=2
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
PWD=/home/ttt/Programming/pg-geonames
XAUTHORITY=/run/user/1000/gdm/Xauthority
GIO_LAUNCHED_DESKTOP_FILE=/usr/share/applications/terminator.desktop
GTK_IM_MODULE=ibus
COLORTERM=truecolor
XDG_SESSION_ID=2
DESKTOP_SESSION=ubuntu
IM_CONFIG_PHASE=2
XDG_SESSION_DESKTOP=ubuntu
GDMSESSION=ubuntu
TEXTDOMAINDIR=/usr/share/locale/
USERNAME=ttt
WINDOWPATH=2
TEXTDOMAIN=im-config
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
TERMINATOR_UUID=urn:uuid:95a81114-773f-4f06-8066-223203ff789f
VTE_VERSION=5202
CLUTTER_IM_MODULE=xim
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
QT4_IM_MODULE=xim
TERMINATOR_DBUS_NAME=net.tenshu.Terminator20x1a6021154d881d
XDG_MENU_PREFIX=gnome-
GNOME_SHELL_SESSION_MODE=ubuntu
SHELL=/bin/zsh
QT_IM_MODULE=ibus
XDG_SESSION_TYPE=x11
GJS_DEBUG_OUTPUT=stderr
SSH_AGENT_PID=2143
GTK_MODULES=gail:atk-bridge
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
XDG_CURRENT_DESKTOP=ubuntu:GNOME
PATH=/home/ttt/anaconda3/envs/ars/bin:/home/ttt/anaconda3/bin:/home/ttt/anaconda3/condabin:/usr/local/bin:/usr/local/sbin:/home/ttt/anaconda3/bin:/home/ttt/.local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda/bin

Thanks

**Comment by svlandeg** [comment]
Could you try with `pip install -U spacy[cuda]` instead ?

**Comment by danem** [comment]
That worked. Thanks. The docs suggested that the conda method should work as well.

**Comment by svlandeg** [comment]
Happy to hear the alternative worked for you!
