### ISSUE TITLE
Underscore attributes not being preserved during serialisation via DocBin

### ISSUE THREAD

**Issue by EdwardJB** [explosion/spaCy#5178]
Hi.

I'm trying to serialise/deserialise the output of a `scispacy` pipline, which includes an Underscore field, `umls_ents`. I _think_ I've set everything up right, but the field isn't being preserved. Is this a bug or user error somewhere?

## How to reproduce the behaviour

```
import spacy
from scispacy.umls_linking import UmlsEntityLinker
from spacy.tokens import DocBin, Doc

TEXT = 'This often leads to cardiac arrest.'
nlp = spacy.load('en_core_sci_lg')
linker = UmlsEntityLinker(resolve_abbreviations=True)
nlp.add_pipe(linker)
doc = nlp(TEXT)

print(doc.ents[0])  # cardiac arrest
print(doc.ents[0]._.umls_ents)  # [('C0018790', 0.9999998807907104), ...]


# Now serialise and deserialise the doc.

doc_bin = DocBin(attrs=["ENT_IOB", "ENT_TYPE"],store_user_data=True) # nb. I took value for `attrs` from spacy docs. No idea what it should actually be.
doc_bin.add(doc)
doc_bin_round_robin=DocBin().from_bytes(doc_bin.to_bytes())
doc_round_robin=list(doc_bin_round_robin.get_docs(nlp.vocab))[0]
Doc.set_extension("umls_ents", default=None)

print(doc_round_robin.ents[0])  # cardiac arrest
print(doc_round_robin.ents[0]._.umls_ents)  # [] MISSING!
```

## Your Environment
* **spaCy version:** 2.2.4
* **Platform:** Linux-4.19.84-microsoft-standard-x86_64-with-debian-10.2
* **Python version:** 3.7.6

**Comment by adrianeboyd** [comment]
You need to use the same `store_user_data=True` option for the second `DocBin` or it skips the custom extension values when it loads the docs:

```
doc_bin_round_robin=DocBin(store_user_data=True).from_bytes(doc_bin.to_bytes())
```

**Comment by EdwardJB** [comment]
@adrianeboyd That works, thanks very much!

Even so, I think the argument name is a bit confusing, given it essentially means "store and/or load user data". Perhaps name it something that implies both like `include_user_data`?
