### ISSUE TITLE
Empty POS field, exception tags mismatch `map_tag` - French and more?

### ISSUE THREAD

**Issue by ygorg** [explosion/spaCy#5179]
## Your Environment
* Operating System: MacOS 10.15.3
* **spaCy version:** 2.2.3
* **Platform:** Darwin-19.3.0-x86_64-i386-64bit
* **Python version:** 3.7.2

Related to #2313, #1958, [this comment](https://github.com/explosion/spaCy/issues/3052#issuecomment-448958656).

I'm using spacy to get the postags of a french text to extract chunks using nltk's [RegexpParser](https://www.nltk.org/api/nltk.chunk.html#nltk.chunk.regexp.RegexpParser).
There is an error because sometimes the spacy field `token.pos_` is empty. This only happen with tokens that appear in the `tokenizer_exceptions.py`.

My diagnostic is that the TAG used in `tokenizer_exceptions.py` do not match the ones in `tag_map.py` ('VERB' in [exceptions](https://github.com/explosion/spaCy/blob/0226b3bf0e388d6341ae03e4384aa2f479286b3b/spacy/lang/fr/tokenizer_exceptions.py#L84) would be 'VERB__VerbForm=Inf' in the [map](https://github.com/explosion/spaCy/blob/0226b3bf0e388d6341ae03e4384aa2f479286b3b/spacy/lang/fr/tag_map.py#L215)). This might be happening in other languages too ?

IMO what should be done is making sure that the tags assigned in exceptions occur in map_tag.

## Example

```
nlp = spacy.load('fr')

[t.pos_ for t in nlp('est-ce')]
# ['', 'PRON']  # It should be ['VERB', 'PRON']

[t.tag_ for t in nlp('est-ce')]
# ['VERB', 'PRON__Number=Sing|Person=3']
# It should be ['VERB__VerbForm=Inf', 'PRON__Number=Sing|Person=3']
```

A try at finding the problems root + a piece of code:

<details>

### Analyse of the example

The exception rule for `est-ce` is `[{LEMMA: "est", ORTH: "est", TAG: "VERB"}, {LEMMA: "ce", ORTH: "-ce"}]`.

According to [linguistic-features.md#rule-based-morphology-rule-based-morphology](https://github.com/explosion/spaCy/blob/479e81bafc90f61556bab5583566e134a00f6aaa/website/docs/usage/linguistic-features.md#rule-based-morphology-rule-based-morphology) I tried to follow to journey of the `pos` field, **everything here is my guess** as I wasn't able to modify spacy's code to print things around.

1. "The tokenizer consults a mapping table TOKENIZER_EXCEPTIONS, which allows sequences of characters to be mapped to multiple tokens. Each token may be assigned a part of speech and one or more morphological features."
	- Exceptions tokens are assigned a TAG. I can not figure where but my guess is : where the `morphology.assign_tag` function is used.
	- Using the exception rule we have : ['est': {'tag': 'VERB'}, '-ce': {}]
2. "The part-of-speech tagger then assigns each token an extended POS tag. In the API, these tags are known as Token.tag. They express the part-of-speech (e.g. VERB) and some amount of morphological information, e.g. that the verb is past tense."
	- I guess that the TAG attributes is not overwritten by the postagger [cf.](https://github.com/explosion/spaCy/blob/master/spacy/pipeline/pipes.pyx#L438)
	- After the POSTagger we have : ['est': {'tag': 'VERB'}, '-ce': {'tag': 'PRON__Number=Sing|Person=3'}]
3. "For words whose POS is not set by a prior process, a mapping table TAG_MAP maps the tags to a part-of-speech and a set of morphological features."
	- We fill the POS attribute by searching 'VERB' in [lang/fr/tag_map.py](https://github.com/explosion/spaCy/blob/f580302673ae16c673619603632378e5d390dacd/spacy/lang/fr/tag_map.py), but it does not exist ('VERB__VerbForm=Inf' would be the correct value), i think that we fall under the first case described below.
	- `token.pos` is either assigned like:
		- [this](https://github.com/explosion/spaCy/blob/16aa092fb5cffb5ec7079951ea0c04cb96733b3e/spacy/morphology.pyx#L285) if the `tag` is not in `reversed_index` then there is no `pos`
		- [this](https://github.com/explosion/spaCy/blob/16aa092fb5cffb5ec7079951ea0c04cb96733b3e/spacy/morphology.pyx#L310) the `pos` is `map_tag[tag]['pos']`
		- [this](https://github.com/explosion/spaCy/blob/16aa092fb5cffb5ec7079951ea0c04cb96733b3e/spacy/morphology.pyx#L320) if the token comes from an exception the `pos` is `exceptions[orth]['pos']`
	- Applying the Morphology object :
	- 'est': 'VERB' do not exist in `tag_map`, so `POS` is not set,
	- '-ce': 'PRON__Number=Sing|Person=3' exist in `tag_map`. POS is assigned to `PRON`. The exception rule has no POS for '-ce'.
	- We end up with : ['est': {'tag': 'VERB', 'pos': ''}, '-ce': {'tag': 'PRON__Number=Sing|Person=3'}]

## Piece of code to ensure the behaviour is not isolated

This code prints the exceptions that have no empty POS (without an issue then), but we filter out the one that have TAGs in TAG_MAP. We keep only the exceptions where `map_tag[TAG]` will not work to show that this is where the problem comes from.

```python
import spacy 
from spacy.symbols import TAG 

nlp = spacy.load('fr')
exceptions = nlp.Defaults.tokenizer_exceptions
pos_map = nlp.Defaults.tag_map
for k, v in exceptions.items(): 
    # If there is no TAG in the exception 
    if not any(TAG in t for t in v): 
        continue 
    # If all TAG in the exception are in POS_MAP (account for _SP)  
    if all(t[TAG] in pos_map for t in v if TAG in t): 
        continue 
    pos_list = [t.pos_ for t in nlp(k)] 
    # If there is an empty POS 
    if '' not in pos_list: 
        print(k, pos_list, exceptions[k])
```

</details>

**Comment by adrianeboyd** [comment]
Thanks for the report!

It would definitely work to use the full tag+morph in the exceptions, but I think for these cases it's better to remove the tag so the model can tag it just like any other occurrence of `est`. Then even if the tags or tag map changes, the exceptions don't need to be modified.

If you need a solution for an existing model, you can remove the "TAG" specifications from the exceptions after loading the model:

```
import spacy
from spacy.symbols import TAG

nlp = spacy.load("fr_core_news_sm")
rules = nlp.tokenizer.rules
for orth, token_dicts in rules.items():
    for token_dict in token_dicts:
        if TAG in token_dict:
            del token_dict[TAG]
nlp.tokenizer.rules = rules # this property assignment flushes the cache

print([t.pos_ for t in nlp("qu'est-ce")]) # ['PRON', 'AUX', 'PRON']
```

**Comment by ygorg** [comment]
Thanks a lot for the workaround code !

I'm trying to make a code to to see whether this happens in other languages, i'll update this thread when I have results.

**Comment by ygorg** [comment]
I made a code to inspect all the lang in `spacy/lang`. The code is kinda (a lot) hacky but what I did was load `TAG_MAP` and `TOKENIZER_EXCEPTIONS` for every lang in `spacy/lang`. And then compute the number of `POS` or `TAG` used in `TOKENIZER_EXCEPTION` and see if they appear in `TAG_MAP` or not.
My result is that the following languages uses POS or TAG field in `TOKENIZER_EXCEPTION`:

| lang | field | uniq values | uniq values in maptags | unmatched values |
|:---- |:----- | --:| --:| ----- |
| uk   | pos   | 1  | 1  | {}    | # Fine
| de   | tag   | 1  | 1  | {}    | # Fine
| en   | tag   | 8  | 8  | {}    | # Fine
| ga   | pos   | 7  | 0  | {'ADV', 'ADP', 'CCONJ', 'NOUN', 'X', 'AUX', 'DET'} |
| fa   | tag   | 7  | 2  | {'PART', 'VERB', 'ADP', 'SCONJ', 'NOUN'} |
| da   | tag   | 2  | 1  | {'CC'} | # Uses `spacy/lang/tag_map.py`
| fr   | tag   | 2  | 0  | {'VERB', 'ADV'} |

And that there might be the same problem in `ga`, `da` and `fa`, but there are no spacy model's for these languages.

**Comment by ygorg** [comment]
@adrianeboyd `nlp.tokenizer.rules` does not exist so what I did was:

```python
import spacy
from spacy.symbols import TAG

nlp = spacy.load("fr_core_news_sm")

rules = nlp.Defaults.tokenizer_exceptions
for orth, token_dicts in rules.items():
    for token_dict in token_dicts:
        if TAG in token_dict:
            del token_dict[TAG]
nlp.tokenizer = nlp.Defaults.create_tokenizer(nlp)
```

and a fallback for the use case of getting the pos of a sentence if the latter doesn't work is:
```python
text = nlp('qu'est-ce')
[t.pos_ or t.tag_ for t in text]
# ['ADV', 'VERB', 'PRON']
```
