### ISSUE TITLE
numpy header included with spaCy too old to build on cygwin

### ISSUE THREAD

**Issue by dellelce** [explosion/spaCy#518]
The build of spaCy fails currently on cygwin with the following error:

```c
    In file included from spacy/lexeme.cpp:260:0:
    /tmp/pip-build-ram30b0i/spaCy/include/numpy/ufuncobject.h:393:23: fatal error: fenv/fenv.c: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```

the current (at time of my testing) version of numpy  builds without issues as it includes the correct file (/usr/include/fenv.h).

It appears that the fenv.c was a non-standard "feature" of cygwin what was (probably 2015?) replaced with the standard header.

**Comment by dellelce** [comment]
The failing code was removed from numpy in 2013:

https://github.com/numpy/numpy/commit/dcfe3260e2d6d9de7a2c3fb0022ecf124faa2ae2#diff-a7ca3a1c2d2ca3dd24f9e33438f6be93

**Comment by honnibal** [comment]
Thanks — sorry I didn't get to this sooner. You really wrote a good ticket on this.

Would you mind testing the v1.0.2 branch?

**Comment by dellelce** [comment]
I am trying to try it but I am having problemis with DLLs handling, summary:

- build works (setup.py install)
- execution does not work

I tried to rebase all the dlls(rebaseall+ rebase -s for dlls in virtualenv) but still have this error:

```python
>>> import spacy
>>> e = spacy.load('en')
>>> help(e)
      1 [main] python3.4m 1412 child_info_fork::abort: address space needed by '_opcode.cpython-34m.dll' (0x47490000) is already occupied
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/_sitebuiltins.py", line 103, in __call__
    return pydoc.help(*args, **kwds)
  File "/usr/lib/python3.4/pydoc.py", line 1827, in __call__
    self.help(request)
  File "/usr/lib/python3.4/pydoc.py", line 1877, in help
    else: doc(request, 'Help on %s:', output=self._output)
  File "/usr/lib/python3.4/pydoc.py", line 1614, in doc
    pager(render_doc(thing, title, forceload))
  File "/usr/lib/python3.4/pydoc.py", line 1414, in pager
    pager(text)
  File "/usr/lib/python3.4/pydoc.py", line 1436, in <lambda>
    return lambda text: pipepager(text, 'less')
  File "/usr/lib/python3.4/pydoc.py", line 1455, in pipepager
    pipe = os.popen(cmd, 'w')
  File "/usr/lib/python3.4/os.py", line 949, in popen
    bufsize=buffering)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1395, in _execute_child
    restore_signals, start_new_session, preexec_fn)
BlockingIOError: [Errno 11] Resource temporarily unavailable
```

I'll try another set of rebaseall/rebase -s runs but these should be handled by setup.py/pip I believe.

Summary: spaCy builds fine, still issues related to DLLs not sure if to be handled by setup/install process or user.

**Comment by mmaaww** [comment]
I still have the same issue. I use cygwin64, python 361.
