### ISSUE TITLE
Priority rules for overlapping matches with EntityRuler

### ISSUE THREAD

**Issue by Tiljander** [explosion/spaCy#5180]
Hi,

First of all, thank you so much for a great library!

When there are overlapping matches in a Doc, EntityRuler prioritize longer patterns over shorter, and if equal in length the match occuring first in the Doc is chosen.

This is great, but it would be good if this behavior is explicitly stated in the documentation for clarity. Could be stated under __init__ or __call__.

## Which page or section is this issue related to?
https://github.com/explosion/spaCy/blob/master/spacy/pipeline/entityruler.py

**Comment by svlandeg** [comment]
Yes, it would be a good idea to clarify that in the docs. Do you want to go ahead and make the PR for that?

The relevant source code can be found here: https://github.com/explosion/spaCy/blob/master/website/docs/api/entityruler.md

And perhaps a note somewhere in the usage section would be good, too. Perhaps here: https://github.com/explosion/spaCy/blob/master/website/docs/usage/rule-based-matching.md

**Comment by Tiljander** [comment]
Ok, I just did!

I created 2 pull requests #5198 and #5199. I uploaded the contributor agreement #5197 as well. I hope I uploaded the contributor agreement correctly.

**Comment by adrianeboyd** [comment]
Updated by #5197, thanks!
