### ISSUE TITLE
Applicabilty of wiki_entity_linking to multiple languages

### ISSUE THREAD

**Issue by kprice-aktors** [explosion/spaCy#5182]
I have been working on testing the wiki_entity_linking module on documents written in English. I am curious how many different languages this module can be applied to?
According to the [spaCy documentation](https://spacy.io/models) , there is a multi-language core model. However, it seems that the [wikidata_pretrain_kb script](https://github.com/explosion/spaCy/blob/master/bin/wiki_entity_linking/wikidata_pretrain_kb.py) requires a [vector model](https://spacy.io/models/en#en_core_web_lg) in order to properly generate a knowledge-base for a particular language. If there is no way to use the multi-language model for this task, is it possible to use a model from a different source?

## Info about spaCy
* **Python version:** 2.7.17
* **Platform:** Linux-5.3.0-40-generic-x86_64-with-Ubuntu-19.10-eoan
* **spaCy version:** 2.2.3

**Comment by svlandeg** [comment]
This is currently not supported, and would entail quite some complexity: managing vectors in different languages, support a multi-lang knowledge base, run the training script with enough examples for each language, etc etc. So I'm afraid this is currently not possible: you'll have to train multiple different models and run the correct one, depending on the language of your input.
