### ISSUE TITLE
Cannot create vectors table with dimension 0.

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#5184]
spacy version: 2.2.4
OS: Windows 10

Step 1: generate pretrained model `python -m spacy pretrain rawtext.jsonl "P:\ML Models\Word2Vec\spacy_word2vec\1.0.0.4\spacy_word2vecmodel_1.0.0.4" "G:\spacypretrained"  -nw 5 -bs 1500 --n-iter 50`
Step 2: use pretrained model in train `python -m spacy train en "D:\temp\spacytrain\model" train.json test.json -g 0 --init-tok2vec G:\spacypretrained\model49.bin`
Step 3: Load model (created using pretrained weights) 
Step 3: Load different model (one that was created with word vectors - word2vec)

Loading of model looks like this

```
import spacy
import sys
import json
from pathlib import Path

from spacy.util import set_data_path

try:
	dataPath = Path(r"D:\temp")
	modelPath = Path(r"P:\spaCy\models\v2.2.3\v1.0.0.2")

	set_data_path(dataPath)
	nlp_model = spacy.load(modelPath, disable=["parser", "tagger"])
	print("ready")
except BaseException as error:
	print("Error 1:", sys.exc_info()[0], error, dataPath, modelPath)
	
```

Result in the following warning

> D:\Anaconda\lib\runpy.py:193: UserWarning: [W019] Changing vectors name from spacy_pretrained_vectors to spacy_pretrained_vectors_300046, to avoid clash with previously loaded vectors. See Issue #3853.
>   "__main__", mod_spec)

And this error 

> Error 1: <class 'ValueError'> Cannot create vectors table with dimension 0.
> If you're using pre-trained vectors, are the vectors loaded? D:\temp P:\spaCy\models\v2.2.3\v1.0.0.2

**EDIT:**
I then tried the reverse - loading the regular model (what was trained only on word2vec vectors) and then loading the model with pretrained weights and the issue didn't occur, even if I went back and forth loading one model after another.  

The issue only seems to happen if the first model loaded is the one that was created using pretraining.

**Comment by svlandeg** [comment]
The `pretrain` command was still experimental in spaCy v2, not very well documented and probably had some bugs or unexpected consequences with certain parameter sets.

The good news is, that the recent [pre-release of spaCy v3](https://github.com/explosion/spaCy/releases/tag/v3.0.0rc1) comes with a revamped API for pretraining and swapping out `Tok2Vec` layers. The relevant documentation is here: https://nightly.spacy.io/usage/embeddings-transformers

The [pretrain](https://nightly.spacy.io/usage/embeddings-transformers) command is now run with the same [config file](https://nightly.spacy.io/usage/training#config) you'd also use during training, making the whole process much more robust and transparent. You can get started with these config files using [`init config`](https://nightly.spacy.io/api/cli#init-config) and setting the pretraining flag, e.g.:
```
python -m spacy init config config.cfg --lang en --pipeline ner --optimize accuracy --pretraining
```
which will produce a config file with (hopefully) sensible defaults.

Hope that's useful to you! I will preliminary close this issue, but feel free to comment here or open a new one if you run into any issues with pretraining in v3.
