### ISSUE TITLE
Installation on Ubuntu x32

### ISSUE THREAD

**Issue by jmarroyave** [explosion/spaCy#5195]
Can not install spacy on Ubuntu x32. Is there a way to install it? or do you know if there is a unofficial build for x32?

Thanks

## Your Environment

* Operating System: ubuntu 18.04
* Python Version Used: 2.7.17
* spaCy Version Used:
* Environment Information: x32

**Comment by svlandeg** [comment]
spaCy requires Python 64 bit so I don't think this will work ?

**Comment by jmarroyave** [comment]
Hi svlandeg, the requierement of the 64bits it is only because of blis?

**Comment by jmarroyave** [comment]
Solved with this:

`BLIS_ARCH="generic" pip install spacy --no-binary blis`

**Comment by jmarroyave** [comment]
Solved with this:

`BLIS_ARCH="generic" pip install spacy --no-binary blis`

**Comment by svlandeg** [comment]
Ok great, thanks for posting the solution! 
Linking https://github.com/explosion/cython-blis/issues/21 for future reference.
