### ISSUE TITLE
ASCII tree parsing output format

### ISSUE THREAD

**Issue by kengz** [explosion/spaCy#520]
As used in [Syntaxnet](https://github.com/tensorflow/models/tree/master/syntaxnet#parsing-from-standard-input), 

``` shell
echo 'Bob brought the pizza to Alice.' | syntaxnet/demo.sh

Input: Bob brought the pizza to Alice .
Parse:
brought VBD ROOT
 +-- Bob NNP nsubj
 +-- pizza NN dobj
 |   +-- the DT det
 +-- to IN prep
 |   +-- Alice NNP pobj
 +-- . . punct
```

the ASCII tree output format would greatly help, and is data efficient (save from multiple runs to get NER, POS, dependency separately.

Also wrote a py snippet that does that [here](https://github.com/kengz/spacy-nlp/blob/master/src/py/nlp.py#L53), with the output at [README](https://github.com/kengz/spacy-nlp#usage), except it returns the data type in JSON. Would be even easier for the users if Spacy does this natively.

**Comment by honnibal** [comment]
This would be cool, yes. Would you mind making a pull request?

**Comment by kengz** [comment]
More than glad :)
Can you point me to the folder path where I shd add this? I think it can be a separate source file. Also where I shd import the method to expose it, and method name conflicts to look out for.

**Comment by kengz** [comment]
@honnibal pls review the PR ^
