### ISSUE TITLE
Add vectors to spacy text categorizer

### ISSUE THREAD

**Issue by tahirahmad2030** [explosion/spaCy#5208]
## Feature description

Spacy's NER does have an argument to add custom word embeddings like pubmed. The same is not yet for spacy text categorizer. Do we have a way to add w2v pubmed embedings  to text categorizer?

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
If so, we will tag it as [`project idea`](https://github.com/explosion/spaCy/labels/project%20idea) so other users can take it on.

**Comment by svlandeg** [comment]
This will become available from spaCy 3.0 onwards. We're currently working on this version on the `develop` branch. What will change is that you'll have much more control over the ML model's internals, including the `tok2vec` layer, cf. e.g. https://github.com/explosion/spaCy/pull/5143/files#diff-7ab747872ac13372a21c54a569f3c175.
