### ISSUE TITLE
Named entities and speech tagging

### ISSUE THREAD

**Issue by TiagoMRodrigues** [explosion/spaCy#521]
If i need to add some entities I can add them using the Matcher.add. and then I can merge and there is examples online for both steps, #Thanks. Now I need to Tag the entities found as NNP because some of them are being miss classified and i know for sure what they are (Portuguese Football clubs in my example).

Also is it possible to set the 2nd parameter in mather.add to for example Portuguese_football_club instead of ORG?

**Comment by dyc3** [comment]
"Portuguese_football_club" seems a bit specific

**Comment by TiagoMRodrigues** [comment]
Let me explain my problem better.
Let's say I have this two phrases
**<when will Paços de Ferreira and Rio Ave play each other?>** and **<when will Miami Heat and Golden State Warriors play each other?>**
and these are the entities for each one
**1st**
>Paços de Ferreira ORG
>Rio Ave ORG

**2nd**
>Miami Heat ORG
>Golden State Warriors ORG

and using one of the prints in the examples we obtain these two trees
**1st**
>when advmod Paços de Ferreira [] []
>will aux Paços de Ferreira [] []
>**Paços de Ferreira ROOT Paços de Ferreira ['when', 'will'] ['and', 'Rio Ave', 'play', '?']**
>and cc Paços de Ferreira [] []
>Rio Ave conj Paços de Ferreira [] []
>play ccomp Paços de Ferreira [] ['other']
>each det other [] []
>other dobj play ['each'] []
>? punct Paços de Ferreira [] ['\n']

**2nd**
>when advmod play [] []
>will aux play [] []
>**Miami Heat nsubj play [] ['and', 'Golden State Warriors']**
>and cc Miami Heat [] []
>Golden State Warriors conj Miami Heat [] []
>play **ROOT** play ['when', 'will', 'Miami Heat'] ['other', '?']
>each det other [] []
>other dobj play ['each'] []
>? punct play [] ['\n']

in the first we can see that Paços de Ferreira,  a soccer club, is used as root and the same does not happen with Miami heat. So the question is what do I need to do so Paços de Ferreira and other ORGanizations stay in equal foot with the ones that the algorithm trains with.

**Comment by honnibal** [comment]
Hi Tiago,

Does this help? https://spacy.io/docs/tutorials/rule-based-matcher

Matt
