### ISSUE TITLE
Outdated link to documentation in matcher demo [small fix]

### ISSUE THREAD

**Issue by guerda** [explosion/spaCy#5212]
The [matcher demo page ](https://explosion.ai/demos/matcher) currently links to an old documentation page:
![image](https://user-images.githubusercontent.com/230782/77648491-8660e380-6f68-11ea-8f64-9648c23fb67b.png)
It links to https://spacy.io/usage/linguistic-features#rule-based-matching
The new link is https://spacy.io/usage/rule-based-matching

I couldn't find the source code so no PR ;)

## Which page or section is this issue related to?
https://explosion.ai/demos/matcher

**Comment by svlandeg** [comment]
Thanks so much for the report!
And yes, this code is indeed not available on the github, but @ines made the change and it should be live by now 👍

**Comment by guerda** [comment]
Wow, that was fast :)
