### ISSUE TITLE
How to use dependency parsing features for text classification?

### ISSUE THREAD

**Issue by kalyanks0611** [explosion/spaCy#5214]
I did dependency parsing for a sentence using spacy and obtained syntactic dependency tags.
```
import spacy
nlp = spacy.load('en')
doc = nlp('Wall Street Journal just published an interesting piece on crypto currencies')

for token in doc:
    print("{0}/{1} <--{2}-- {3}/{4}".format(
        token.text, token.tag_, token.dep_, token.head.text, token.head.tag_))
```
**Output**

Wall/NNP <--compound-- Street/NNP

Street/NNP <--compound-- Journal/NNP

Journal/NNP <--nsubj-- published/VBD

just/RB <--advmod-- published/VBD

published/VBD <--ROOT-- published/VBD

an/DT <--det-- piece/NN

interesting/JJ <--amod-- piece/NN

piece/NN <--dobj-- published/VBD

on/IN <--prep-- piece/NN

crypto/JJ <--compound-- currencies/NNS

currencies/NNS <--pobj-- on/IN

**I'm not unable to understand, how can I use this information to generate dependency-based features for text classification. What are the possible ways to generate features from this for text classification?

Thanks in advance............**

**Comment by svlandeg** [comment]
Referring to the Stackoverflow issue https://stackoverflow.com/questions/60868220/how-to-use-dependency-parsing-features-for-text-classification, as we try to keep this Issue Tracker focused mainly on bug reports and feature requests. Thanks!
