### ISSUE TITLE
Shape mismatch: Training pretrain_textcat.py

### ISSUE THREAD

**Issue by tahirahmad2030** [explosion/spaCy#5215]
## How to reproduce the behaviour

Trying to train the example provided by spacy - to train pretrain_textcat.py
1) I converted a w2v based embeding using `spacy init-model` command in spacy vector model.
2) Now I used a command to train `pretrain_textcat.py`, No change in this file as found in github.

`python text_classifier_pretrain.py 100 200 -pn 1 -tn 1 -eg 10 '/home/tahir/15-6-2018/EPI_NER/word_vectors/data/pubmed_model`

I got the following error on mismatch of shape

```Train tensorizer
  0%|                                                                                                                                                                              | 0/50000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "text_classifier_pretrain.py", line 221, in <module>
    plac.call(main)
  File "/home/tahir/anaconda2/envs/py36/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/tahir/anaconda2/envs/py36/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "text_classifier_pretrain.py", line 215, in main
    optimizer = train_tensorizer(nlp, texts, dropout=0.2, n_iter=pretrain_iters)
  File "text_classifier_pretrain.py", line 117, in train_tensorizer
    tensorizer.update(docs, None, losses=losses, sgd=optimizer, drop=dropout)
  File "pipes.pyx", line 333, in spacy.pipeline.pipes.Tensorizer.update
  File "/home/tahir/anaconda2/envs/py36/lib/python3.6/site-packages/thinc/check.py", line 155, in checked_function
    check(arg_id, fix_args, kwargs)
  File "/home/tahir/anaconda2/envs/py36/lib/python3.6/site-packages/thinc/check.py", line 70, in has_shape_inner
    raise ShapeMismatchError(arg.shape, tuple(shape_values), shape)
thinc.exceptions.ShapeMismatchError: 

  Shape mismatch: input (8,) not compatible with (None, 96).

  Traceback:
  ├─ call in /home/tahir/anaconda2/envs/py36/lib/python3.6/site-packages/plac_core.py:328
  ├─── consume in /home/tahir/anaconda2/envs/py36/lib/python3.6/site-packages/plac_core.py:207
  └───── main in text_classifier_pretrain.py:215
         >>> optimizer = train_tensorizer(nlp, texts, dropout=0.2, n_iter=pretrain_iters)
```

Please help me to figure out this error. what steps should I follow

## Your Environment

* Operating System: Ubuntu 16.04
* Python Version Used: 3.6
* spaCy Version Used: 2.2.4 
* Environment Information: command line

**Comment by svlandeg** [comment]
Hi @tahirahmad2030, apologies for the late follow up.

I've been looking into this, and it does feel like a bug have crept into this script, the underlying `Tensorizer` component, or the Thinc models. I haven't been able to pinpoint the exact problem yet.

To be honest, I think this `pretrain_textcat` script may have not aged well... Also, we're working on a rewrite of these training and pretraining scripts, for spaCy v.3. The idea is to rely more on config files instead of internal default values to set dimensions and parameters. This new version will rely on [Thinc 8](https://thinc.ai/), a recent revamped release of our DL library. This should also make it much easier to debug these kind of `ShapeMismatchError` errors.

**Comment by svlandeg** [comment]
As a workaround - I think it makes sense to use the `pretrain.py` script instead, as discussed in Issue #5221

**Comment by tahirahmad2030** [comment]
@svlandeg Thanks for your reply, I will be waiting for V3 of spacy for many features to come.
