### ISSUE TITLE
Is it possible to alter the behviour of tokenization when using the CLI?

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#5231]
regarding this previous issue https://github.com/explosion/spaCy/issues/4198#issue-485378317

I wanted to add a custom rule for tokenization.

But how do you do this when using the CLI for training, and evaluating?

**Comment by adrianeboyd** [comment]
Save the model with the modified tokenization to disk and use it as the base model with the train CLI.

**Comment by erotavlas** [comment]
@adrianeboyd  Thanks, while making the changes I wasn't sure whether to use infix or suffix for example I'm trying to fix this

`DATE:01/01/01`

By adding this rule to infix

`r"(?<=[{a}])[:](?=[0-9])".format(a=ALPHA)`

It works however I wasn't sure if it was really an infix or not.  Maybe the colon is a suffix to DATE?
Does this even matter?

What do you think?
