### ISSUE TITLE
My custom ner model recognize entities on the first sentence only. Unable to recognize from the whole paragraph

### ISSUE THREAD

**Issue by kasabaman** [explosion/spaCy#5233]
## How to reproduce the behaviour

```
import sys
import spacy
import json
import pysbd
from spacy.matcher import Matcher
nlp = spacy.load(r'.\try_1')
print(nlp.pipe_names)
doc = nlp("Effective January 1, 2020 Argentina enacted a new non-creditable export duty with a cap of twelve percent (15%) on the export of the services. This tax is charged as a cost to contracts. Although the export duty is set to expire in November 2020, it is possible that the Argentina government would extend this indefinitely. They elaborated a service  with a new and fresh approach strategic related to Quality Engineering for a top Bank in Argentina, the presenters was : Alex Smith (Technology Director), John Smith (Technology Manager) and Alex John (Consulting Senior Manager).")
print("INPUT:", doc)
for ent in doc.ents:
  print("ENTITY:",ent.text, ent.label_, ent.start_char, ent.end_char)
```

If I use the built-in model like the "en_core_web_sm" it can recognize entities not just from the first sentence but also the succeeding sentences. But my custom trained model only recognizes entities from first sentence only. Did I miss some steps in training my model? I print the nlp.pipe_names to check and I got these values: ['tagger', 'parser', 'ner']

My model is to recognize Argentina and labelt it "COUNTRY"

Please help me as I am also new to nlp and spaCy. Thank you so much in advance! 

## Info about spaCy

* **spaCy version:** 2.2.4
* **Platform:** Windows-10
* **Python version:** 3.7.5

**Comment by svlandeg** [comment]
To test your hypothesis that the model only recognizes entities in the first sentence, could you copy paste that first sentence to the end of your string, so that it's in their twice, run it again through `nlp`, and print here the results?

**Comment by kasabaman** [comment]
```
import sys
import spacy
import json
import pysbd
from spacy.matcher import Matcher
nlp = spacy.load(r'.\try_1')
print(nlp.pipe_names)
doc = nlp("Effective January 1, 2020 Argentina enacted a new non-creditable export duty with a cap of twelve percent (15%) on the export of the services. Effective January 1, 2020 Argentina enacted a new non-creditable export duty with a cap of twelve percent (15%) on the export of the services.")
print("INPUT:", doc)
for ent in doc.ents:
  print("ENTITY:",ent.text, ent.label_, ent.start_char, ent.end_char)
```

I ran the code above and here are my results.

['tagger', 'parser', 'ner']
INPUT: Effective January 1, 2019 Argentina enacted a new non-creditable export duty with a cap of twelve percent (12%) on the export of the services. Effective January 1, 2019 Argentina enacted a new non-creditable export duty with a cap of twelve percent (12%) on the export of the services.
ENTITY: Argentina COUNTRY 26 35

**Comment by svlandeg** [comment]
I'm a little stupified by this, can't really imagine what is going wrong on the background.

If you put "Argentina" in the sentence twice, does it recognize both cases ?

**Comment by kasabaman** [comment]
```
import sys
import spacy
import json
import pysbd
from spacy.matcher import Matcher
nlp = spacy.load(r'.\try_1')
print(nlp.pipe_names)
doc = nlp("Effective January 1, 2019 Argentina Argentina enacted a new non-creditable export duty with a cap of twelve percent (12%) on the export of the services in Argentina. Effective January 1, 2019 Argentina enacted a new non-creditable export duty with a cap of twelve percent (12%) on the export of the services.")
print("INPUT:", doc)
for ent in doc.ents:
  print("ENTITY:",ent.text, ent.label_, ent.start_char, ent.end_char)
```
Result: 
INPUT: Effective January 1, 2019 Argentina Argentina enacted a new non-creditable export duty with a cap of twelve percent (12%) on the export of the services in Argentina. Effective January 1, 2019 Argentina enacted a new non-creditable export duty with a cap of twelve percent (12%) on the export of the services.
ENTITY: Argentina Argentina COUNTRY 26 45

**Comment by svlandeg** [comment]
So whatever you do, `len(doc.ents)` is always 1?

During training of your custom model, do you perhaps always show exactly one labeled entity per document? That may be biasing the model towards only wanting to predict one.

**Comment by kasabaman** [comment]
Yes the length is always 1.  

Some of my train data has 2 entities, but most of my train_data consist of 1 sentence per 1 entity. But the tutorial I followed also used a 1 sentence per 1 entity as their train_data.

**Comment by svlandeg** [comment]
Right, but it depends on whether each example text really only does have one correct entity, or has multiple and you only annotate one.

For instance, if you have the text "I live in London. I used to live in Berlin." If you feed this example text to your training algorithm, you really do need to annotate both locations, or otherwise the training algorithm will learn that London is a city, and Berlin is not. So you need to be consistent in this annotation. I'm guessing this may be where your custom model training goes wrong, but it's difficult to say for sure.

The best advice I can give for now is to review your original annotations and make sure they are consistent & complete.

**Comment by svlandeg** [comment]
I just noticed you also opened a [StackOverflow issue](https://stackoverflow.com/questions/60942541/my-custom-ner-model-recognize-entities-on-the-first-sentence-only-unable-to-rec), which is probably a better forum to follow up on this, as we try to keep this tracker focused on bug reports and feature requests. I will follow up on the SO issue as well.
