### ISSUE TITLE
Autocompletion for extension attributes

### ISSUE THREAD

**Issue by mr-bjerre** [explosion/spaCy#5235]
At the moment [extension attributes](https://spacy.io/usage/processing-pipelines#custom-components-attributes) are not recognized by IDEs using intellisense. 

It would be great if IDEs were able to recognized what components and extension attributes are being set by our `nlp` classes.

I do however realize that this might be too hard or even impossible to implement but maybe not?

I noticed this [thread](https://github.com/explosion/spaCy/issues/3707) which suggests that it should already be working? However it doesn't for me.

**Comment by svlandeg** [comment]
Hm, interesting. The `dir` thing does work:
```
Doc.set_extension("has_country", default=True)
nlp = English()
doc = nlp("Some text about Colombia and the Czech Republic")
print(dir(doc._))
```
> ['get', 'has', 'has_country', 'set']

But in my IDE, PyCharm, the autocompletion doesn't work either. Then again, it looks like PyCharm just doesn't: https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000665110-auto-completion-for-dynamic-module-attributes-in-python

Maybe the same it true for Intellisense? They're both from Jetbrains, right?

**Comment by mr-bjerre** [comment]
I thought Intellisense was a general term across IDEs but now I realize it's actually a Microsoft tool for code completion - my mistake. 

I'm using PyCharm as well.

**Comment by svlandeg** [comment]
Ok so for PyCharm, it doesn't work in the normal editor, but it does work in the "Python console":

![image](https://user-images.githubusercontent.com/8796347/79321134-2f1cb600-7f0b-11ea-835d-2f65bc6c3b66.png)
![image](https://user-images.githubusercontent.com/8796347/79321382-8d499900-7f0b-11ea-962b-f189d8762b04.png)

So I'd conclude that spaCy does support this, but maybe not all IDE's adhere to this `__dir__` principle? Not sure what else can be done on our end...?

**Comment by mr-bjerre** [comment]
Yes at least with ipython I see. The console uses runtime

**Comment by svlandeg** [comment]
Good to have that confirmed, thanks! So it seems to be an issue with Pycharm really ...

**Comment by mr-bjerre** [comment]
So you're saying that PyCharm does not support auto-completion `Doc.set_extension` etc.

Hmm I wonder how that could be fixed.

**Comment by svlandeg** [comment]
What I meant is that PyCharm doesn't seem to support **dynamic** attributes for auto-completion. This thread https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000665110-auto-completion-for-dynamic-module-attributes-in-python confirms that. The original poster had also implemented a `__dir__` method, but still auto-completion doesn't work:

> PyCharm can't provide completion for such a dynamic code

and a comment from Feb 2020:
> there's no plans for the near future
