### ISSUE TITLE
"how many" gets put into noun chunks

### ISSUE THREAD

**Issue by dyc3** [explosion/spaCy#524]
When a noun is preceded by "many", spaCy includes it in a noun chunk. This is expected behavior. However, if "many" is preceded by "how" then that is also included in the noun chunk. 

For example: 
- _How many apples_ are in this barrel?
- _How many shoes_ are on the table?

**Comment by ines** [comment]
Closing this and making #1057 the master issue – work in progress for spaCy v2.0!
