### ISSUE TITLE
NER model with custom tokenization failed to resolve named entities

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#5241]
Regarding tokenizing special case where number is attached to alphabetic character via colon such as `DATE:01/01/1901` (see [issue #4198](https://github.com/explosion/spaCy/issues/4198))

I was unable to get this to work for NER according to [this instruction](https://github.com/explosion/spaCy/issues/5231)

I first started with a blank nlp model `nlp = nlp.blank('en')` and added an infix expression as follows 

    # modify tokenizer infix patterns
    infixes = (
        LIST_ELLIPSES
        + LIST_ICONS
        + [
            r"(?<=[0-9])[+\-\*^](?=[0-9-])",
            r"(?<=[{al}{q}])\.(?=[{au}{q}])".format(
                al=ALPHA_LOWER, au=ALPHA_UPPER, q=CONCAT_QUOTES
            ),
            r"(?<=[{a}]),(?=[{a}])".format(a=ALPHA),
            r"(?<=[{a}])(?:{h})(?=[{a}])".format(a=ALPHA, h=HYPHENS),
            r"(?<=[{a}0-9])[:<>=/](?=[{a}])".format(a=ALPHA),
            
            #this regex is added to handle volon as infix preceded by alpha and followed by numeric
            r"(?<=[{a}])[:/](?=([0-9][0-9]?[/]))".format(a=ALPHA),
        ]
    )
    
    infix_re = compile_infix_regex(infixes)
    nlp.tokenizer.infix_finditer = infix_re.finditer
    doc = nlp(text)
    print([t.text for t in doc]) 

I tested it and it worked fine to tokenize my test cases.
Then I saved the model

    output_dir = r'D:\temp\spacy\customTokenizerModel_blanken'
    
    # save model to output directory
    if output_dir is not None:
        output_dir = Path(output_dir)
        if not output_dir.exists():
            output_dir.mkdir()
            nlp.to_disk(output_dir)
            print("Saved model to", output_dir)
        else:
            nlp.to_disk(output_dir)
            print("Saved model to", output_dir)

Then I used that model as input to the train command

    python -m spacy train en E:\models\output_model E:\trainingdata\FINALTRAIN.json E:\trainingdata\FINALTEST.json --base-model E:\customTokenizerModel_blanken --vectors "E:\spacy_word2vecmodel_1.0.0.4" --n-iter 30

But when I test the output model, it does not detect the date entities that I had tagged, the ones that were connected by colon to the alpha character.

**NOTE:** my word2vec model was trained earlier on a separate occasion (without the custom tokenization)  

Does it also need to start from my blank en model with custom tokenization rules?

I think some more explanation on correct usage for a complete workflow is required in the documentation. 

**EDIT:** I tried removing the vectors model and re training, but same result.  The annotated dates such as `DATE:01/01/1901` are not detected

I also tested the resulting model and the custom tokenization is preserved (i.e. the custom tokenization still produces the desired tokens)

**Comment by svlandeg** [comment]
Hi @erotavlas : I was looking at the Stackoverflow issue I think you created earlier, but I can't find it anymore? I think SO is actually a better forum for these kind of usage questions.

**Comment by erotavlas** [comment]
@svlandeg Sorry, actually i wasn't sure where to post this, I moved it after because I felt my attempt  should have been working based on the documentation and instructions I received, but perhaps didn't because of a bug  or issue in spacy, Also it actually caused a somewhat serious problem today in our production application and I needed a quick reply.. (although I did get around the issue temporarily)

Our company is using the custom trained NER model in a tool to detect named entities in medical report text for de-identification purpose.  A recent case we found was  selecting part of a medical term 'cancer' that was joined together with a report ID 'AB12-3456' via semi-colon  so it looks like '... breast cancer;AB12-3456'  which ended up like '...breast xxxxxx;XX11-1111' because the default tokenizer splits it like this  'breast', 'cancer;AB12', '-', '3456'.  My entity recognizer model correctly identified the report id entity but unfortunately because the term cancer is merged to the beginning of it via semicolon, it gets included as part of the report id entity.   By itself it's no big deal, but the de-identified text is used downstream by other processes such as classification and the absence of a keyword like 'cancer' causes mis-classification of the report for example.  

I've only observed this to be a problem if I annotated entities that were 'connected' to other tokens in that manner, and during training I guess the entity is expanded by spacy because the start index lies in the middle of what it thinks is a token and the start index is adjusted to encompass the additional text. Then the model gets trained on the 'expanded' entity, if that makes any sense.  So I have refrained from annotating entities that I thought were 'connected' to other tokens like that so the model does not learn these 'false' annotated entities.  However recently I found the models still seems to pick them up some times, so now I've been trying to fix this at the tokenizer level to prevent this from happening.  

Regardless, I decided to get around the issue temporarily by introducing a text pre-processing in problem locations that replaces characters like : and ;  with a character that guarantees correct tokenization (like single white space)  before I pass the text to spacy. It works so far.

**Comment by erotavlas** [comment]
@svlandeg I think I finally got it to work now.  See for dates the new model is picking them up

Before (left) and after adding custom tokenization (right)
![image](https://user-images.githubusercontent.com/10454265/79268796-50c56100-7e69-11ea-863e-9ebb4a3ed82e.png)

I'm not sure what I missed the first time.
