### ISSUE TITLE
Will additional training of tagger improve parser results?

### ISSUE THREAD

**Issue by nrodnova** [explosion/spaCy#5248]
Currently, spacy tagger/parser performs pretty unreliably on medical texts. I am trying to come up with a plan to annotate some data and re-train the model. However, dependency annotation is a pain. The model makes a lot of mistakes with POS tags as well. If I annotate POS tags, and train the model (starting with the pre-trained one), will dependency parser behave better? I read everything I found about the model, and I listened to the Matthew's video, so I understand that parser and tagger share some neural layers. But it is still pretty unclear to me if training the tagger will help the parser.

## Your Environment

* Operating System: macOS
* Python Version Used: 3.6
* spaCy Version Used: 2.2
* Environment Information:

**Comment by svlandeg** [comment]
Hi @nrodnova : no, the tagger and parser are currently entirely independent, so training the tagger won't help your parser's performance.

As you're using medical texts, I'd like to point you to [scispacy](https://github.com/allenai/scispacy), which has specific support for the biomedical domain. Perhaps you'll find that the performance of the scispacy models are better on your use-case!

From their docs:

> there is a custom tokenizer that adds tokenization rules on top of spaCy's rule-based tokenizer, a POS tagger and syntactic parser trained on biomedical data and an entity span detection model. Separately, there are also NER models for more specific tasks.
