### ISSUE TITLE
conda install spacy error on python 3.4

### ISSUE THREAD

**Issue by KenHollandWHY** [explosion/spaCy#525]
UnsatisfiableError: The following specifications were found to be in conflict:
- python 3.4*
- spacy
  Use "conda info <package>" to see the dependencies for each package.

I thought in the documentation spacy could be installed on python 3.4?

**Comment by honnibal** [comment]
Hi,

Sorry for the late reply --- did you get this sorted out?

There should be no known problems with Python 3.4, but we've dropped tests for it to keep our matrix smaller. I think the metadata on that spaCy version might have been out of date.
