### ISSUE TITLE
No python 3.8 binaries on conda-forge

### ISSUE THREAD

**Issue by buhrmann** [explosion/spaCy#5254]
Hi, there were two previous issues that are now locked. I understand that Azure pipelines didn't support 3.8 initially, but I think that should be resolved by now. Would it be possible to push 3.8 support on conda-forge?

**Comment by svlandeg** [comment]
Py3.8 distributions of the latest spacy 2.2.4 are now [uploaded](https://anaconda.org/conda-forge/spacy/files) thanks to @adrianeboyd :-)
