### ISSUE TITLE
Unexpected behaviour of tokenizer.to_disk compared to documentation

### ISSUE THREAD

**Issue by lfiedler** [explosion/spaCy#5256]
More precisely, if, for some reason, someone uses `tokenizer.to_disk(path)` as follows:
```python
from spacy.util import get_lang_class
from tempfile import TemporaryDirectory
from pathlib import Path

tokenizer = get_lang_class("xx").Defaults.create_tokenizer()

with TemporaryDirectory() as temp_dir:
    tokenizer.to_disk(Path(temp_dir))
```
a `PermissionError` is raised, whereas
```python
with TemporaryDirectory() as temp_dir:
    tokenizer.to_diks(Path(temp_dir) / "tokenizer.json")
```
works.

Judging from from this and the source code, `path` is opened as if it was a file.
The [documentation ](https://spacy.io/api/tokenizer#to_disk) of `tokenizer.to_disk`, however, describes it to require a path to a directory as argument. This seems to be inconsistent with its actual behaviour.

## Your Environment
* **spaCy version:** 2.2.4
* **Platform:** Windows-10-10.0.18362-SP0
* **Python version:** 3.7.7
* Environment Information:
  * **conda version:** 4.8.3
  * **conda-build version:** 3.18.11

**Comment by svlandeg** [comment]
I think you're right, and the documentation needs to change.

**Comment by willpeppo** [comment]
take
