### ISSUE TITLE
Sentence boundary detection splits at 'Sr.'

### ISSUE THREAD

**Issue by FabianSinn** [explosion/spaCy#5268]
```
import spacy
nlp = spacy.load('en_core_web_lg')
nlp.disable_pipes('tagger', 'ner', 'parser')
nlp.add_pipe(nlp.create_pipe('sentencizer'))
doc = nlp('John Sr. goes for a walk.')
print([i for i in doc.sent])
```
Leads to two sentences
"John Sr." and "goes for a walk" while it should be one sentence.

**Comment by svlandeg** [comment]
The [`sentencizer`](https://spacy.io/api/sentencizer) is a very simple pipeline component, basically splitting sentences on dots. We advice to use the dependency parser for higher accuracy, which is by default available in the `en_core_web_lg` model:

```
import spacy
nlp = spacy.load('en_core_web_lg')
doc = nlp('John Sr. goes for a walk.')
print([i for i in doc.sents])
```

produces just the one sentence:

> [John Sr. goes for a walk.]

**Comment by FabianSinn** [comment]
Maybe this should be explained in the documentation?

**Comment by svlandeg** [comment]
Also, as an FYI, @adrianeboyd is working on a new component which will probably be called `senter`. It's a trainable sentence splitter which should provide a balance between better accuracy than `sentencizer` and higher speed than the dependency parser. But this is work-in-progress for v.3.0, cf e.g. https://github.com/explosion/spaCy/pull/5109/files#diff-986a41991603940e9d43a36933db7ded

**Comment by svlandeg** [comment]
> 
> 
> Maybe this should be explained in the documentation?

I think there are various places where this is already mentioned: 

https://spacy.io/usage/linguistic-features#sbd

> Unlike other libraries, spaCy uses the dependency parse to determine sentence boundaries. This is usually more accurate than a rule-based approach, but it also means you’ll need a statistical model and accurate predictions. If your texts are closer to general-purpose news or web text, this should work well out-of-the-box. For social media or conversational text that doesn’t follow the same rules, your application may benefit from a custom rule-based implementation. You can either use the built-in Sentencizer or plug an entirely custom rule-based function into your processing pipeline.

https://spacy.io/usage/linguistic-features#sbd-component

> The Sentencizer component is a pipeline component that splits sentences on punctuation like ., ! or ?. You can plug it into your pipeline if you only need sentence boundaries without the dependency parse.

https://spacy.io/api/sentencizer

> A simple pipeline component, to allow custom sentence boundary detection logic that doesn’t require the dependency parse. By default, sentence segmentation is performed by the DependencyParser, so the Sentencizer lets you implement a simpler, rule-based strategy that doesn’t require a statistical model to be loaded. 

Hope that answers your questions!

**Comment by FabianSinn** [comment]
I followed the advice from the error message because I assumed this would just add the components necessary to do sentence splitting:
> ValueError: [E030] Sentence boundaries unset. You can add the 'sentencizer' component to the pipeline with: nlp.add_pipe(nlp.create_pipe('sentencizer')) Alternatively, add the dependency parser, or set sentence boundaries by setting doc[i].is_sent_start.

**Comment by FabianSinn** [comment]
If I use the method you describe, it still fails for slightly more complex examples. For example see:
`import spacy
nlp = spacy.load('en_core_web_lg')
doc = nlp("Augustine Washington Sr. (November 12, 1694 – April 12, 1743) was the father of the first U.S. President George Washington. He belonged to the Colony of Virginia's landed gentry and was a planter and slaveholder.")
print([i for i in doc.sents])
`
