### ISSUE TITLE
left and right as adjectives

### ISSUE THREAD

**Issue by dyc3** [explosion/spaCy#527]
spaCy parses "right turn" correctly: "turn" as the root word, and "right" as an adjective, as expected. 
However, if "left turn" is given, spaCy thinks that "left" is the _root_, and "turn" is a _direct object_. If given a full sentence like "The car took a left turn," spaCy correctly parses "left" as an adjective of "turn."

**Comment by rajhans** [comment]
This probably explains it:
https://books.google.com/ngrams/graph?content=left_NOUN%2Cleft_VERB%2C+right_NOUN%2C+right_VERB&case_insensitive=on&year_start=1800&year_end=2000&corpus=15&smoothing=3&share=&direct_url=t4%3B%2Cleft_NOUN%3B%2Cc0%3B%2Cs0%3B%3Bleft_NOUN%3B%2Cc0%3B%3BLeft_NOUN%3B%2Cc0%3B%3BLEFT_NOUN%3B%2Cc0%3B.t4%3B%2Cleft_VERB%3B%2Cc0%3B%2Cs0%3B%3Bleft_VERB%3B%2Cc0%3B%3BLeft_VERB%3B%2Cc0%3B.t4%3B%2Cright_NOUN%3B%2Cc0%3B%2Cs0%3B%3Bright_NOUN%3B%2Cc0%3B%3BRight_NOUN%3B%2Cc0%3B.t1%3B%2CRIGHT_VERB%3B%2Cc0

**Comment by dyc3** [comment]
@rajhans Ah, that makes sense if spaCy is trained off of texts instead of spoken language. It's because of sentences like "There are 10 apples left over." where "left" in this instance is a verb.

[And this is the correct graph link](https://books.google.com/ngrams/graph?content=left_ADJ%2Cleft_VERB%2Cright_ADJ%2Cright_VERB&case_insensitive=on&year_start=1800&year_end=2000&corpus=15&smoothing=3&share=&direct_url=t4%3B%2Cleft_ADJ%3B%2Cc0%3B%2Cs0%3B%3Bleft_ADJ%3B%2Cc0%3B%3BLeft_ADJ%3B%2Cc0%3B.t4%3B%2Cleft_VERB%3B%2Cc0%3B%2Cs0%3B%3Bleft_VERB%3B%2Cc0%3B%3BLeft_VERB%3B%2Cc0%3B.t1%3B%2Cright_ADJ%3B%2Cc0%3B.t1%3B%2CRIGHT_VERB%3B%2Cc0), looking at verbs and adjs instead of verbs and nouns.

**Comment by rajhans** [comment]
Yes, ADJ sorry. Basically in the absence of any other context, the parser will likely get the dependencies wrong.
