### ISSUE TITLE
Preprecessing OntoNotes Release 5.0 

### ISSUE THREAD

**Issue by lzadrija** [explosion/spaCy#5276]
Hello, 

is this OntoNotes 5.0 dataset (https://catalog.ldc.upenn.edu/LDC2013T19) anyhow preprocessed before it was used for training these models:
en_core_web_md &
en_core_web_lg?
To be more concrete, is this OntoNotes 5.0 dataset changed anyhow before it is converted using https://spacy.io/api/cli#convert to change it to the form spacy expects for training?
For example, using: https://pyconll.readthedocs.io/en/stable/?

Also, regarding this comment:
https://github.com/explosion/spaCy/issues/2824#issuecomment-439744192
would you be so kind as to provide the preprocessed Ontonotes 5.0 dataset used for training the mentioned models (en_core_web_md, en_core_web_lg) with distinction what is used as a dev, and what as a test set?

We are trying to reproduce the results obtained on the Ontonotes 5.0 dataset

## Which page or section is this issue related to?
https://spacy.io/models/en

**Comment by honnibal** [comment]
Yes, there's some preprocessing done. I aligned the ontonotes WSJ portions against the raw WSJ text, in order to train on paragraphs of text (as the raw text wasn't distributed as part of the data).

Unfortunately we're not able to distribute the processed corpus, as I think that's against the license terms. I'm sorry that this is inconvenient but there's not really a solution.

**Comment by adrianeboyd** [comment]
And about conversions: the `spacy convert` CLI converts from a few dependency formats (like CoNLL-U), but it doesn't do any complicated constituency-to-dependency conversions like you'd need if you're starting from the original OntoNotes data. This step was done with the [ClearNLP](https://github.com/clir/clearnlp) converter.

**Comment by adrianeboyd** [comment]
And data is split as described here:

https://www.aclweb.org/anthology/W13-3516.pdf

Following these IDs:

http://conll.cemantix.org/2012/download/ids/english/all/

I hope that helps!

**Comment by lzadrija** [comment]
Hello,

thank you for your replies. 
Can you please share the location of the raw Wall Street Journal text you used to align the ontonotes WSJ? Can it be obtained from https://catalog.ldc.upenn.edu/?

**Comment by lzadrija** [comment]
Also, 

since you mentioned that you used the data split described [here](https://www.aclweb.org/anthology/W13-3516.pdf),
did you use their data conversion process described [here](http://cemantix.org/data/ontonotes.html)? 
I am referring to the usage of skeleton2conll.sh script to convert data to the *_conll File Format.
