### ISSUE TITLE
Training NER with positive examples only.

### ISSUE THREAD

**Issue by buriy** [explosion/spaCy#5277]
Please could you help me to set up training from a subset with no negative examples.
For example, if we take https://en.wikipedia.org/wiki/Donald_Trump we see
"...Trump was born and raised in [Queens], a borough of New York City, and received a [bachelor's degree] in economics from the [Wharton School]. ..." (links are in square brackets [ ])
Now we know that "Wharton School" is a "school" which is ORG, "Queens" is a LOC, but we notice that "New York City" is not selected. Now we want to give positive feedback for "Queens" that it's LOC, and for "Wharton School" that it's an ORG. We'll give negative feedback to the network that "Queens" is not a PER, neither a LOC.
But we do not want to give negative feedback to the model for answering that New York City is a LOC. However, we don't want to reinforce model on whether New York City is really a LOC because we are not sure if it is so, so we can't just copy non-identified entities from the model output.
So what do we do to ignore a term in that position?

**Comment by adrianeboyd** [comment]
I think the closest thing you can do is construct training examples that use the "ignore/missing" tag `-` to skip particular tokens while training. For example, instead of https://github.com/explosion/spaCy/blob/cf579a398d121617c0ab684d414af5f067677078/examples/training/ner_example_data/ner-sent-per-line.json, you would have this if you want to skip `Sebastian Thrun`:

```
[
  {
    "id":0,
    "paragraphs":[
      {
        "sentences":[
          {
            "tokens":[
              {
                "orth":"When",
                "tag":"WRB",
                "ner":"O"
              },
              {
                "orth":"Sebastian",
                "tag":"NNP",
                "ner":"-"
              },
              {
                "orth":"Thrun",
                "tag":"NNP",
                "ner":"-"
              },
...
```

**Comment by buriy** [comment]
Thanks, that would work perfectly for this case. And how do I do that using a GoldParse?

**Comment by adrianeboyd** [comment]
You provide `entities` as a list of BILUO tags, so `["O", "-", "-", ...]`.

**Comment by buriy** [comment]
...And if I have a list of entities listed with [(start, end, type), ...] ?
Use to_biluo(entities) , then to_biluo(exclusions), then combine them?
Thank you!

**Comment by buriy** [comment]
Closing unless you need to write this at some place in the doc or do some other action.
