### ISSUE TITLE
unrecognized arguments: -tm and --tag-map-path

### ISSUE THREAD

**Issue by dobryy** [explosion/spaCy#5285]
## How to reproduce the behaviour
According to the documentation, this arg was added in the latest 2.2.3 but doesn't work for me for some reason :/

Command:
`/home/name/anaconda3/envs/ingredients/bin/python -m spacy debug-data ru recipes/train-5.json recipes/validate-5.json --verbose -tm ../ingr/model-final/tagger/tag_map 
`
Result:
```
usage: spacy debug-data [-h] [-b None] [-p tagger,parser,ner] [-IW] [-V] [-NF]
                        lang train_path dev_path
spacy debug-data: error: unrecognized arguments: -tm ../ingr/model-final/tagger/tag_map
```

The same issue with the option `--tag-map-path`

## Your Environment
/home/name/anaconda3/envs/ingredients/bin/python -m spacy info --markdown

## Info about spaCy

* **spaCy version:** 2.2.3
* **Platform:** Linux-5.3.0-45-generic-x86_64-with-debian-buster-sid
* **Python version:** 3.7.6

**Comment by adrianeboyd** [comment]
Sorry, that's a mistake in the docs. It was added in 2.2.4.

**Comment by svlandeg** [comment]
Hi @dobryy , we're fixing it in the documentation - meanwhile you could try updating to 2.2.4 to use this feature!

**Comment by dobryy** [comment]
Okay, thank you :)
