### ISSUE TITLE
Evaluation ents_f

### ISSUE THREAD

**Issue by pandhir** [explosion/spaCy#5286]
I use `en_core_web_sm` for NER prediction on my data. Classes are Loc, Per, Org, Misc, O.

Does the F score for NER `ents_f` include only entity classes or O class with entity classes?

URL: https://spacy.io/api/scorer/

**Comment by adrianeboyd** [comment]
It is the F-score over all entity spans (`O` is not counted as an entity type). A predicted entity has to match exactly (both the exact tokens covered and the label) to be counted as correct. So if the gold data has `(PERSON, 10, 12)` the model predicts `(PERSON, 10, 11)`, the predicted entity would count as a false positive and the missing `(PERSON, 10, 12)` would be counted as a false negative.
