### ISSUE TITLE
Support for openCL

### ISSUE THREAD

**Issue by umarbutler** [explosion/spaCy#5288]
## Feature description
Are there currently any plans to support non-Nvidia GPUs via the use of openCL? This could be extremely helpful for those with powerful AMD GPUs which are going unused when training and updating models.

Since spaCy uses CuPy for gpu acceleration, a library like ClPy could easily be swapped in for training on non-Nvidia GPUs. Alternatively, there are other openCL implementations of NumPy, such as Numba, which could be used instead of ClPy.

If this is a feature which is not already being considered or has not already been rejected, and is something that others think would be useful, I would be more than happy to try and write an implementation which uses ClPy or Numba.

**Comment by honnibal** [comment]
I think this should be possible with [Thinc v8](https://thinc.ai), which is how spaCy will coordinate its ML (you can use Thinc to wrap PyTorch etc).

If ClPy has a numpy-like interface, you could have an `Ops` class that uses it, just like the `CupyOps` class.

**Comment by umarbutler** [comment]
@honnibal I took a deeper look at ClPy and it appears to still be in its infacy, so I think it'd be best to use Numba. I'm looking through the thinc source code now and it should be possible for me to create a NumbaOps class which can be switched in for CupyOps. I can't see to find anything about openCL in the documentation for thinc (nor in the issues section), so I might just work on a PR for a Numba class thinc which can then be added to spaCy at a later time.

**Comment by umarbutler** [comment]
I'm going to close this issue for now. openCL implementation is probably better suited for the thinc team rather than spaCy.

**Comment by umarbutler** [comment]
I'm going to close this issue for now. openCL implementation is probably better suited for the thinc team rather than spaCy.
