### ISSUE TITLE
Using .pipe() to optimize the code is sometimes classifying tokens differently

### ISSUE THREAD

**Issue by Damiox** [explosion/spaCy#5294]
## How to reproduce the behaviour
I've been trying to optimize the following code [A] code that is currently running spacy individually for each single sentence. I tried to do this in a batch mode [B] with `.pipe()`, but I ran into a discrepancy issue when comparing my results...

[A] (current code):
```
nlp = en_core_web_lg.load()
results = []
for text in texts:
  results.append(nlp(text))
```

[B] (the optimization I was trying):
```
nlp = en_core_web_lg.load()
results = list(nlp.pipe(texts)
```

The throughput is improving tremendously with [B]. Unfortunately, I'm noticing this improvement is bringing a discrepancy as shown below... so in some cases with `.pipe()` some tokens are getting different results from Spacy and looks like it depends on the batch context (e.g. if I reduced the batch size then the issue wouldn't be reproducible for that sentence)... Is this issue expected to happen? I couldn't find some info about this in https://spacy.io/usage/processing-pipelines)

For instance:

The following token info is changing for single [A] vs batch [B] classification:
```
* For [A]: {token.text} = arsenal ; {token.pos_} = ADJ ; {token.tag_} = JJ
* For [B]: {token.text} = arsenal ; {token.pos_} = PROPN ; {token.tag_} = NNP
```

Could it be possible that `pipe()` may bias the results I was expecting (from [A]) by other sentences in the batch being processed? Why am I getting a different token.pos_ and token.tag_ for "arsenal" for single vs batch version of my code? 

## Your Environment
* Operating System: Linux
* Python Version Used: 3.7
* spaCy Version Used: 2.2.4 (latest, at the moment)
* Environment Information:

**Comment by adrianeboyd** [comment]
No, this isn't expected, but I think it is theoretically possible that some float rounding differences could potentially lead to slight differences, especially on GPU. I looked into this a bit when there was a bug related to `pipe` for `spacy-transformers`, but I never found issues with `spacy`, see #4766. It's probably worth investigating, in any case.

Would it be difficult to create a minimal example that shows the problem? If you can share some of your data but don't want to post it here, you can also email me an example at adriane AT explosion DOT ai.
