### ISSUE TITLE
`EntityRecognizer` cannot access `labels` property 

### ISSUE THREAD

**Issue by R1j1t** [explosion/spaCy#5306]
## How to reproduce the behaviour
```py
nlp = spacy.load("en_core_web_sm", disable=["tagger", "parser"])
print(nlp.entity.labels)
```
----
```
from spacy.pipeline import EntityRecognizer
ner = EntityRecognizer(nlp.vocab)
ner.add_label("MY_LABEL")
print(ner.labels)
```

Both print statment gives the following error:
```
AttributeError: 'spacy.pipeline.EntityRecognizer' object has no attribute 'labels'
```
## Your Environment
* **Platform:** Darwin-19.4.0-x86_64-i386-64bit
* **Python version:** 3.5.4
* **Models:** fr, en
* **spaCy version:** 2.0.16

**Comment by svlandeg** [comment]
Hi @R1j1t, I think you'll have to upgrade your version of spaCy for this to work. I just tested this with 2.2.4 and there it works:
```
import spacy
nlp = spacy.load("en_core_web_sm", disable=["tagger", "parser"])
print(nlp.entity.labels)
``` 
gives output:
> ('CARDINAL', 'DATE', 'EVENT', 'FAC', 'GPE', 'LANGUAGE', 'LAW', 'LOC', 'MONEY', 'NORP', 'ORDINAL', 'ORG', 'PERCENT', 'PERSON', 'PRODUCT', 'QUANTITY', 'TIME', 'WORK_OF_ART')

**Comment by R1j1t** [comment]
Thanks @svlandeg for the answer. I updated the version and now it is working. The only question I had was in the [documentation section](https://spacy.io/api/entityrecognizer#labels) it wasn't mentioned that it was introduced in > v2.0, hence raised this issue. no worries!

**Comment by svlandeg** [comment]
Yea, you're right. I'll try to dig up since which version this has been implemented!
