### ISSUE TITLE
Is it possible to control the tagged entity from model side? For example, I have 6 annotation tags for model training, but I want only 4 annotation tags, when I am doing NER.

### ISSUE THREAD

**Issue by Zer0-dev115** [explosion/spaCy#5307]
## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by Zer0-dev115** [comment]
What is happening in between these steps, when I am loading spacy NER model and annotating the text?

**Comment by adrianeboyd** [comment]
No, there's no direct support for this. The closest you could get would be to filter out the entity types you don't want after running the NER component, but this will probably have slightly different results than a model trained only on a subset of the tags.

If you have data with six tags and only want to train on four, you will need to create a filtered copy of your dataset to train the model. There's not really a built-in mechanism to filter the annotation while loading a dataset or training.

**Comment by Zer0-dev115** [comment]
Thanks @adrianeboyd .
I was asking, I have trained a model for NER with 6 annotation tags. But when I am loading the model for output prediction, I want only 4 annotation tags. I tried with reducing annotation tag from meta.json file. It didn't help.

**Comment by adrianeboyd** [comment]
I think your best option is to filter the entity types in `doc.ents` after running the model. You could write a custom pipeline component to do this or make the filtered entities available through a custom extension.
