### ISSUE TITLE
Pre-existing tokenization generates empty doc

### ISSUE THREAD

**Issue by vikrantsharma7** [explosion/spaCy#531]
Tried to create doc using pre-existing tokenization.
[https://spacy.io/docs/tutorials/byo-annotations](url)

`tokens = [u'A', u'list', u'of', u'strings', u'.']`
`has_space = [True, True, True, False, False]`
`doc = Doc(nlp.vocab, orth_and_spaces=zip(tokens, has_space))`
`assert len(doc) == len(tokens)`

The above is straight from the docs.
First of all, the keyword argument `orth_and_spaces` is actually `orths_and_spaces`.
But most importantly, the immediately following assertion `assert len(doc) == len(tokens)` fails as the doc is empty

**Comment by honnibal** [comment]
Thanks, I know this was a frustrating bug.

This is fixed in the 1.0 release (just pushed). I've also deprecated the `orths_and_spaces` name, in favour of two keyword arguments `words` and `spaces`.

**Comment by vikrantsharma7** [comment]
Thanks! Will upgrade.
