### ISSUE TITLE
Bug in `is_new_osx()` – specifically returning the current minor version of macOS / Mac OS X

### ISSUE THREAD

**Issue by jsekamane** [explosion/spaCy#5310]
**Orginal function:**

https://github.com/explosion/spaCy/blob/3d2c308906e2bde7ca57d2e8213252530b944502/setup.py#L15-L27

**Tests** on `macOS Catalina version 10.15.4 (19E287)`:

```console
$ python3
>> import sys
>> sys.platform
'darwin'

>> import distutils.util
>> distutils.util.get_platform()
'macosx-10.6-intel'

>> import platform
>> platform.platform()
'Darwin-19.4.0-x86_64-i386-64bit'

>> platform.mac_ver()
('10.15.4', ('', '', ''), 'x86_64')
```

A closer look at the [documentation](https://docs.python.org/3/library/sysconfig.html#sysconfig.get_platform) of `get_platform()` shows that Mac OS X can return:

* macosx-10.6-ppc
* macosx-10.4-ppc64
* macosx-10.3-i386
* macosx-10.4-fat

So clearly `minor_version` will never equal or exceed 7 in the original function.

**Proposed function:**

```python
import sys
import platform
def is_new_osx():
    """Check whether we're on OSX >= 10.10"""
    if sys.platform != 'darwin':
        return False
    else:
        minor_version = int(platform.mac_ver()[0].split('.')[1])
        if minor_version >= 7:
            return True
        else:
            return False
```

There is also a mismatch between the comment saying `OSX >= 10.10` and the code saying `minor_version >= 7`. Perhaps @honnibal knows the rational for this?

**Comment by jsekamane** [comment]
Note that `get_platform()` behaves differently in Python3 and Python2.7: https://stackoverflow.com/a/27204111/1053612

**Comment by svlandeg** [comment]
Thanks so much for the detailed report, @jsekamane !
I created a PR here: https://github.com/explosion/spaCy/pull/5376 - could you please review?

I changed your proposed solution a bit, as it wasn't checking on the "10" bit anymore, so I think it would be returning `True` for e.g. "9.8" ?

I also think that the comment should have read `OSX >= 10.7` instead of `10.10`. Also requested a review from Matt to get his 2 cents on the issue.

**Comment by svlandeg** [comment]
PR #5376 has been merged so tentavily closing this - let me know if you do run into issues though, @jsekamane . This will be live from spacy 3.0 onwards.
