### ISSUE TITLE
Misaligned GET STARTED button

### ISSUE THREAD

**Issue by letmerecall** [explosion/spaCy#5311]
## How to reproduce the behaviour

goto: https://spacy.io/

## Screenshots
![spacy](https://user-images.githubusercontent.com/19938474/79350502-29e45900-7f55-11ea-94e5-ecc6c3d6183e.PNG)

## Your Environment

* Browser: Firefox, Brave, Chrome

**Comment by svlandeg** [comment]
That's so weird, I hadn't noticed that before! And the code hasn't changed in months... 

Thanks for the report!

**Comment by svlandeg** [comment]
Fixed by Ines, will be live when we next update the docs ;-)
