### ISSUE TITLE
spaCy models and unit tests

### ISSUE THREAD

**Issue by koaning** [explosion/spaCy#5313]
I want to add more unit tests for a package that depends on spaCy (https://rasahq.github.io/whatlies/) but I may not want to exhaust your endpoints by downloading big spaCy models in my CI. Is there a best practice when writing unit tests for code that uses big spaCy models? 

It feels wrong to download 100s of MB every time you run CI. I could dockerize it, but I was wondering if there was a norm.

**Comment by slowtokyo** [comment]
We just dockerize the models for our unit tests and put the models into a separate dependencies container (with our other dependencies) so that it only gets updated whenever the dependencies need updating. The core application is rolled in a separate container and imports the dependencies container.

**Comment by ines** [comment]
While things like pre-downloading models is an option, it often makes sense to ask yourself whether you really need to load the _actual_ model in your test. Unless your testing objective is "Does spaCy work and can it load the model?" or "Does my library correctly handle the entire large vectors model in memory?" (or similar) or your code directly depends on very specific predictions and you need to ensure those don't change, there's typically not a good reason to actually load the whole model. 

You can usually achieve the same result by setting up the objects and data you need from scratch, and it'll run faster and more efficiently, with fewer side effects.

For instance, our standard test suite for spaCy includes _a lot of_ tests for very specific functionality of the models and vectors, and related downstream features. But none of them actually download or use any of the models (see the [vectors tests](https://github.com/explosion/spaCy/blob/master/spacy/tests/vocab_vectors/test_vectors.py) for examples).

Of course, it depends on what you need to do. But if you want to test that given the vector space X, it outputs result Y, you could set up a blank `nlp` object populate its instance of `spacy.vectors.Vectors` with a predefined number of vectors, and then test if your logic does the right thing. 

If you want it to be extra fancy, you could probably even use [`hypothesis`](https://hypothesis.readthedocs.io/en/latest/) to generate the vectors for you, so you have broader coverage and test scenarios that maybe don't occur in the default vectors package (but could in custom user vectors).

**Comment by koaning** [comment]
I was contemplating making my own spaCy model manually with only a few tokens in it and after reading what @ines said here I am convinced. 

Building that should also be a fun exercise. Thanks!
