### ISSUE TITLE
wikidata_pretrain_kb.py fails to process wiki articles due to change {lang}wiki-latest-pages-articles.xml.bz2

### ISSUE THREAD

**Issue by elben10** [explosion/spaCy#5314]
The format of {lang}wiki-latest-pages-articles.xml.bz2 has changed.

The text tag previous looked like this `<text xml:space="preserve">` but now look like this `<text bytes="{NUMBER}" xml:space="preserve">`

Thus, the function `bin.entity_linking.wikipedia_processor._process_wp_text` fails to parse any wikipedia article.

**Comment by svlandeg** [comment]
Thanks again for the report and for contributing the PR! This is now live on the `master` branch and will be fixed from 2.3 onwards.

**Comment by elben10** [comment]
You're welcome. Thanks for the good guidance. Have a nice day!
