### ISSUE TITLE
How to get multiple word tokens in dependency parsing?

### ISSUE THREAD

**Issue by jltchiu** [explosion/spaCy#532]
Hi,
In the demo page, I tried "What is your favorite color"

https://demos.explosion.ai/displacy/?text=what%20is%20your%20favorite%20color&model=en&cpu=1&cph=1

The demo result shows that the sentence was segmented into three chunk ("what", "is", "your favorite color"), and the dependency between the chunk is displayed. When I am actually using spacy, I use

    toks = nlp("what is your favorite color")
    for tok in toks:
        print(tok.orth_, tok.dep_, tok.pos_, tok.ent_type_, tok.is_stop, tok.lemma_, [t.orth_ for t in tok.lefts], [t.orth_ for t in tok.rights])

However, with this setup, I can only see dependency parsing between every tokens. Is there a way to just get the dependency between different chunks instead of word tokens? Thanks.

**Comment by honnibal** [comment]
You want the `.merge()` method. Here's what the displaCy service does: https://github.com/explosion/spacy-services/blob/master/displacy/displacy_service/parse.py
