### ISSUE TITLE
Time for type stubs?

### ISSUE THREAD

**Issue by talwrii** [explosion/spaCy#5326]
## Feature description

Implement type stubs as as in #4337 (locked). In this issue you say "Once we no longer support 2.7 and 3.5, we'll look at type hints.".  #4828 drops support for python 2.7 and 3.5 (and makes some code improvement that this allows). 

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?

Not really. The type stubs needs to be kept in sync with the code.

**Comment by svlandeg** [comment]
Happy to report that the upcoming spaCy v3 (which drops support for Python 2) will include type hints - you can have a sneak peak on the `develop` branch ;-) I'll close this issue as this is implemented, just not released yet - which is only a matter of time ;-)
