### ISSUE TITLE
Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

### ISSUE THREAD

**Issue by senthilmk** [explosion/spaCy#5327]
## How to reproduce the behaviour

nlp = spacy.load("en_core_web_sm")

Works with Python 3.6 but not with Python 3.8 

## Your Environment
* Operating System: Darwin 
* Python Version Used: 3.6 / 3.8
* spaCy Version Used:  2.2.4
* Environment Information: None

**Comment by svlandeg** [comment]
The [models](https://spacy.io/usage/models) need to be installed with the command
> python -m spacy download en_core_web_sm

If that succeeds, you should be able to find it in the output of `pip list`. If not, you'll get that error message above.

If the error persists, could you paste the full log of running the above command, and the output of the command `python -m spacy validate` ?
