### ISSUE TITLE
python -m spacy download en_core_web_sm does nothing

### ISSUE THREAD

**Issue by JGCoelho** [explosion/spaCy#5337]
## How to reproduce the problem
Running pip install spaCy goes smoothly without issues, but trying to download en_core_web_sm does nothing, it doesn't even show a error message, the command line just goes straight to the next command.

```
C:\Users\JGC\Desktop\Trabalhos\Python\autocompletebot>python -m spacy download en_core_web_sm

C:\Users\JGC\Desktop\Trabalhos\Python\autocompletebot>python3 -m spacy download en_core_web_sm

C:\Users\JGC\Desktop\Trabalhos\Python\autocompletebot>
```

I know it isn't installing it because when i try to run the command 'spacy.load("en_core_web_sm")' on python, even from the command line,  i get the following error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\JGC\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "C:\Users\JGC\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\util.py", line 169, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```

## Environment

* Windows 10:
* Python 3.7.0b5
* spaCy 2.2.4:

**Comment by adrianeboyd** [comment]
I'm not sure why the download isn't working, but as an alternative, you can install the model directly with pip like this (see https://spacy.io/usage/models#download-pip):

```
pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.5/en_core_web_sm-2.2.5.tar.gz
```

You can get the links to the models by clicking the "release details" button on any model page (like https://spacy.io/models/en) and then scrolling down to the assets at the bottom of the page.

You can check that this worked by running `python -m spacy validate`, which should show a list of installed models. If that command also doesn't do anything, then I'd try reinstalling spacy in a clean environment to see if that helps.

**Comment by JGCoelho** [comment]
> pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.5/en_core_web_sm-2.2.5.tar.gz

That worked. Thanks, adriane.
