### ISSUE TITLE
Language class for Malayalam

### ISSUE THREAD

**Issue by sabiqueqb** [explosion/spaCy#5339]
I have found that there are no Language class for the Malayalam language currently.
I would like to contribute a Malayalam Language class to SpaCy.

**Comment by adrianeboyd** [comment]
That would be a very welcome contribution! If you haven't already seen it, the basic guidelines are here: https://spacy.io/usage/adding-languages

The best way would be to submit a PR with the new language directory. It's also fine to start with a partial PR (just mark it as a WIP) and we can help if you have any questions about the details.

**Comment by sabiqueqb** [comment]
@adrianeboyd Thank you for your quick response. I have already started to develop it. I will open a pull request soon.

**Comment by adrianeboyd** [comment]
Merged, thanks!
