### ISSUE TITLE
Wrong spacy lemmatization and postag for "quelle(s)" in French when capitalized

### ISSUE THREAD

**Issue by CloCimpello** [explosion/spaCy#5340]
## How to reproduce the behaviour
#For doc1, the lemma is the right one : "quel", POS: "DET" instead of "PRON"
#For doc2, the lemma is "quelle" (singular feminine) POS: "NUM" instead of "PRON"
#For doc3, the lamma is "quell" (which is not even a word) POS: "DET" instead of "PRON"

import spacy
nlp = spacy.load("fr_core_news_sm")
doc1 = nlp(u"n'importe quelle option peut fonctionner.")
doc2 = nlp(u"N'IMPORTE QUELLE OPTION PEUT FONCTIONNER.")
doc3 = nlp(u"n'importe Quelle option peut fonctionner.")

## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.7
* spaCy Version Used: 2.2.4
* Environment Information: pycharm, fr_core_news_sm 2.1.0

**Comment by CloCimpello** [comment]
I just installed fr_core_news_sm 2.2.5 and I tried : 

"N'importe quelles options." -> lemma : quel POS : DET
"N'IMPORTE QUELLES OPTIONS." -> lemma : quel POS : DET
"N'importe quelle option." -> lemma : quel POS : DET
"N'IMPORTE QUELLE OPTION." -> lemma : quel POS : DET

This tend to make me think that the problem is resolved  (the choice of tag DET is accepted by many linguists) but I still have these cases :

Plural
1. "Quelles que soient les options, tout doit fonctionner." -> lemma : quelle POS : ADJ
2. "QUELLES QUE SOIENT LES OPTIONS, TOUT DOIT FONCTIONNER." -> lemma : quelle POS : NOUN
3. "Tout doit fonctionner, quelles que soient les options." -> lemma : quelle POS : ADJ
4. "TOUT DOIT FONCTIONNER, QUELLES QUE SOIENT LES OPTIONS." -> lemma : quelle POS : NOUN

Singular
1. "Quelle que soit l'option, tout doit fonctionner." -> lemma : quell POS : ADJ
2. "QUELLE QUE SOIT L'OPTION, TOUT DOIT FONCTIONNER." -> lemma : quelle POS : ADV
3. "Tout doit fonctionner, quelle que soit l'option." -> lemma : quel POS : DET
4. "TOUT DOIT FONCTIONNER, QUELLE QUE SOIT L'OPTION." -> lemma : quelle POS : ADV

**Comment by svlandeg** [comment]
Thanks for the analysis, and happy to hear that the more recent model provides more accurate results for your use-case.

The pretrained models that we distribute, have been trained on news text that is, in general, properly capitalized. There may be some uppercase titles orso, but their proportion will be minimal. If your use-case requires parsing of many such uppercase sentences, it may be worthwile to train your own model with such examples, or to retrain the existing French model. You could use sentences that are correct in their "normal" cased variants, uppercase them, and feed those as training examples. Meanwhile, make sure to also keep feeding "normal cases" so the model doesn't "forget" how to do those.

That said, the POS tagger is a Machine Learning model, ofcourse, and thus will always make *some* mistakes. We collect them all in Issue #3052 to try and make the models better over time, but 100% accuracy will never be achieved I'm afraid... 

Closing this to merge with #3052.
