### ISSUE TITLE
CoNLL 2018 shared task?

### ISSUE THREAD

**Issue by diegollarrull** [explosion/spaCy#5347]
Hello!

I came across this post about submitting to the CoNLL 2018 shared task
https://github.com/explosion/spaCy/issues/2011

I just wanted to know if you ended up making a submission. 
If so, under which name? Is there any way I can access the submission for English? 

Thank you very much in advance.

**Comment by adrianeboyd** [comment]
I don't think there was a submission in the end, sorry!
