### ISSUE TITLE
Knowledge Base error in hashing.

### ISSUE THREAD

**Issue by amitbcp** [explosion/spaCy#5364]
## How to reproduce the behaviour
aliases =  kb.get_alias_strings()

KeyError : "[E018] Can't retrieve string for has '454'. This usually refers to an issue with the `Vocab` or `StringStore`

## Your Environment

* Operating System: RHEL 7
* Python Version Used:  3.6.5
* spaCy Version Used: 2.2.4

I created  a KB with the bin/wiki_entity_linking example on the full dump rather than 200000 lines. The KnowledgeBase was created successfully but I get this error while using it.

**Comment by svlandeg** [comment]
Hm, that does seem to indicate a problem with the `vocab` instance used by the KB. Did you write the KB to file at some point? 

Could you provide a minimal code snippet that exhibits this error, and provide the full stack trace of the error? That will help us debug what may be going on here.

**Comment by amitbcp** [comment]
Command used to create KB : 
`python wikidata_pretrain_kb.py 'latest-all.json.bz2' 'enwiki-latest-pages-articles-multistream.xml.bz2' './kb_full_1' 'en_core_web_lg'`

Code to Load the KB 


```
from spacy.vocab import Vocab
import spacy
from spacy.kb import KnowledgeBase

vocab = Vocab().from_disk("./kb_full_1/nlp_kb/vocab")
kb = KnowledgeBase(vocab=vocab)
kb.load_bulk("kb_full_1/kb")
```

The wikidata_pretrain_kb.py script creates the vocab in the nlp_kb folder. So I loaded that itself.

Error is generated at this point :  
aliases =  kb.get_alias_strings()

```
KeyError 
kb.pyx in spacy.kb.KnowledgeBase.get_alias_strings()
strings.pyx in spacy.strings.StringStore.__getitem__()
KeyError : "[E018] Can't retrieve string for has '454'. This usually refers to an issue with the `Vocab` or `StringStore` ."
```

**Comment by svlandeg** [comment]
Ok, this is definitely strange. Could you provide the output of `python -m spacy validate` in the environment where you're running this script ?

**Comment by amitbcp** [comment]
@svlandeg sorry, I had to manually type the environment result , due to some limitation of the environment.

[tick] Loaded Compatibility  table
================= Installed models(spaCy v2.2.4) ================
spaCy installation : /usr/local/lib/python3.6/dist-packages/spacy

TYPE        NAME                    MODEL                 VERSION
package   en-core-web-sm   en_core_web_sm   2.2.5         [tick]
package   en-core-web-md   en_core_web_md   2.2.5         [tick]
package   en-core-web-lg   en_core_web_lg   2.2.5         [tick]

**Comment by svlandeg** [comment]
Your models certainly seem up-to-date, but the issue you're getting doesn't seem to be related to the KB functionality. It seems more of a fundamental problem with the `StringStore`/`Vocab` on your installation. Can you run these lines and let us know what the output is? 

```
import spacy
v = spacy.vocab.Vocab()
v.strings[454]
```

Also, from the results of the `validate` command, it looks like you're not running this is in a separate environment. Usually it's better to create an new virtual environment, install spaCy etc from scratch in it, and then execute the scripts, all the while making sure that you're executing these different scripts and commands in the same env.

**Comment by amitbcp** [comment]
@svlandeg 
Output
```
>>> import spacy
>>> v = spacy.vocab.Vocab()
>>> v.strings[454]
'IDX'
>>> v.strings['454']
3577388440593456605
```
This was a fresh ec2 instance so I did not create an environment. If you suggest, I can redo that in a new environment.

Also, another issue is with the gold_entities.jsonl . No matter what parameters I use, it's creating an empty file.

**Comment by svlandeg** [comment]
> >>> v.strings[454]
> 'IDX'

That is indeed the correct result we'd expect.

> This was a fresh ec2 instance so I did not create an environment. If you suggest, I can redo that in a new environment.

I'm afraid the point is to run this specific command in the environment where you got the original error

> KeyError : "[E018] Can't retrieve string for has '454'. This usually refers to an issue with the Vocab or StringStore

It would be important for us to know whether in that environment, it knows the hash fro `IDX` or not. If not, which is how it looks like, the entire environment may somehow be corrupt, which could also explain other issues you're having.

Alternatively - you could try running the scripts again in the new environment (where `v.strings[454]` works).

**Comment by amitbcp** [comment]
@svlandeg  yes. The same/instance and environment. Also this isn't shared with anyone show no other source of tinkering with installations

**Comment by svlandeg** [comment]
Hi @amitbcp, sorry for the late follow-up, but I'm afraid I just ran out of ideas at the time as to what could be wrong. No chance you've been able to figure it out in the meantime?

Could it be that you updated your spaCy models after you created the KB, but before you loaded it back in?

**Comment by amitbcp** [comment]
Hey @svlandeg !
Sorry for the delay.Even I was not able to find a solution to that.
Though I started a new VM and reran all the steps from scratch with a fresh installation and still faced the same error. Post that , I moved to Facebook's [BLINK](https://github.com/facebookresearch/BLINK) and it's performing really well with a good degree of flexibility.

**Comment by svlandeg** [comment]
I do think this should be fixed in the new v3, yes. Anyway sorry we couldn't be more helpful, but good to hear that BLINK is working well for your use-case!

I'll close this in the meantime, but feel free to reply / open a new issue if some new problem pops up.

**Comment by notrueblood** [comment]
I ran into this error as well, and would like to share what caused it in my case in the hopes it helps someone:

I instantiated the knowledge base with:

```python
kb = KnowledgeBase(
  vocab=nlp.vocab,
  entity_vector_length=nlp.vocab.vectors.shape[1],
)
```

Then, after populating the kb, materialized `nlp.vocab` and `kb`. However, that was incorrect. As the knowledge base is populated, it adds to the vocab object's string store. So, instead of storing `nlp.vocab`, which will have an out of date string store, `kb.vocab` should be stored.

**Comment by svlandeg** [comment]
Hi @notrueblood, thanks for sharing! It's always good to understand common problems people may run into, so we can improve upon the user experience.

I'm not sure I fully understand your point though. When you create the KB with the vocab, `kb.vocab` and `nlp.vocab` should really be referring to the same Vocab object? So serializing either of the two should give the same result? (ofcourse only if you serialise AFTER you're done adding to the KB/vocab)

**Comment by svlandeg** [comment]
This is also how I'd use to do it, cf https://github.com/explosion/projects/blob/master/nel-emerson/scripts/el_tutorial.py#L42: I'd serialize the `nlp` object and the `kb`, and deserialize the `kb` with the deserialized `nlp` object. If you found that this doesn't actually always work, would you be able to provide a minimal code snippet to investigate whether this may be a bug or not?
