### ISSUE TITLE
Please Help with fastText to spaCy

### ISSUE THREAD

**Issue by miraille** [explosion/spaCy#5369]
Hi Community, please help with

1. I need use FastText for Spacy on RasaNLU (0.15.0a1) for Czech Support
2. I think, that i must use https://github.com/facebookresearch/fastText/blob/master/docs/crawl-vectors.md a and czech model
3. **Please, write me or post link for python script or command line step by step, for this tranformation and train**
4. Whats is better? Use https://fasttext.cc/docs/en/pretrained-vectors.html or crawl https://fasttext.cc/docs/en/crawl-vectors.html
5. MY GOAL IS USE FASTTEXT on SPACY for RASA NLU --- please help me ... i used lot of libraries but with wrong result :(

THANKS :) :)

**Comment by adrianeboyd** [comment]
Hi, this bug tracker is mainly focused on bugs and feature requests for spacy itself, so it's probably not the best place for these kinds of questions. StackOverflow or other Rasa support forums may be a better place with more users who are knowledgeable about Rasa.

For the spacy-specific part of your question: if you want to initialize a spacy model from the word2vec text format (like the `.vec` file produced by fasttext), you can do that with `python -m spacy init-model`: https://spacy.io/api/cli#init-model

This will only produce a model with vectors (no tagger, parser, or NER), so if you need other spacy components you will need to train them from annotated data. The basics are described here: https://spacy.io/usage/training
