### ISSUE TITLE
ImportError: No module named 'spacy.attributes'

### ISSUE THREAD

**Issue by lhawizy** [explosion/spaCy#537]
Hi,
I've been trying to run the rule-based-matcher example (https://spacy.io/docs/tutorials/rule-based-matcher) for the latest version of spacy but I seem to be getting an ImportError for spacy.attributes
is there something else I should be downloading when I upgrade to the new version?

**Comment by honnibal** [comment]
Fixed --- should read `spacy.attrs`. D'oh.

**Comment by lhawizy** [comment]
Cheers thanks, I was just going through the code. Thank you!

**Comment by lhawizy** [comment]
Sorry one last question, is there an example of how to use the merge_phrases function just to see how it could work?

**Comment by supercr7** [comment]
@lhawizy As your question is different from the issue, try asking it on their [Gitter channel](https://gitter.im/explosion/spaCy) or on [stackoverflow](http://stackoverflow.com/questions/tagged/spacy).

**Comment by lhawizy** [comment]
Thanks, i will close this issue and discuss it in Gitter!
