### ISSUE TITLE
Unable to access GPU - cloud VMs and other machines

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#5383]
I'm having issue running training/pretraining on Azure VM, I found that there are two devices on the VM when I run 

`sudo lshw -C video`

```
  *-display
       description: VGA compatible controller
       product: Hyper-V virtual VGA
       vendor: Microsoft Corporation
       physical id: 8
       bus info: pci@0000:00:08.0
       version: 00
       width: 32 bits
       clock: 33MHz
       capabilities: vga_controller bus_master rom
       configuration: driver=hyperv_fb latency=0
       resources: irq:11 memory:f8000000-fbffffff memory:c0000-dffff
  *-display
       description: 3D controller
       product: GK210GL [Tesla K80]
       vendor: NVIDIA Corporation
       physical id: 1
       bus info: pci@6d22:00:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list
       configuration: driver=nvidia latency=0
       resources: iomemory:100-ff iomemory:140-13f irq:0 memory:41000000-41ffffff memory:1000000000-13ffffffff memory:1400000000-1401ffffff
```

But spacy will not detect GPU at all, even though the virtual machine comes preconfigured with everything installed (using Data Science Virtual Machine - Ubuntu 18)

I have a feeling it's because its defaulting to the device 0.

Is there a way to specify device 1 instead (like we can do in `spacy train` command?  I don't see any option in the CLI reference for specifying GPU in pretrain.

**Comment by svlandeg** [comment]
The function `prefer_gpu` takes an argument `gpu_id` which indeed defaults to 0. Could you try giving it a different ID in the `pretrain` script? (around L127)

**Comment by erotavlas** [comment]
Ok so I think there is something else going on because I cannot get access to GPU using spacy at all.  I tried multiple VM on Azure (Data Science Windows 2019, Data Science Ubuntu, I even created my own VM from scratch and installed CUDA toolkit myself and still nothing)  All tested using NC_6 level machine with Tesla GPU.  

Furthermore pytorch is able to see and access the GPU when I run the following 

```
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> spacy.prefer_gpu()
False
>>> spacy.require_gpu()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Miniconda\envs\spacy\lib\site-packages\thinc\neural\util.py", line 87, in require_gpu
    raise ValueError("GPU is not accessible. Was the library installed correctly?")
ValueError: GPU is not accessible. Was the library installed correctly?
>>> import torch
>>> torch.cuda.current_device()                                                                                         0
>>> torch.cuda.device_count()
1
>>> torch.cuda.get_device_name(0)
'Tesla K80'
>>> torch.cuda.is_available()
True
>>>

```

**Comment by erotavlas** [comment]
I was having difficulty getting spacy to run pretraining on GPU until finally I succeeded.  In case anyone else encounters this issue on Windows 10 environment this is what I did

(Already had installed latest NVIDIA graphics driver)

- Install CUDA 9.2 base installer (say no to HD audio or graphics driver - installed graphics driver separately)
- Install CUDA 9.2 patch
- Apply cuDNN files for CUDA 9.2
- check environment variables correct, and `nvcc --version` return version 9.2

- Create new conda environment
- activate environment and `pip install -U spacy[cuda92]`
- then `pip install torch==1.5.0+cu92 torchvision==0.6.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html`

- test `spacy.require_gpu()` return True
- run `python - m spacy pretrain` - fails with error from issue #5380
- pip uninstall cupy-cuda92
- pip install cpupy-cuda92

- try again pretrain command and it works

**Comment by BramVanroy** [comment]
K80's are relatively slow compared to today's standards - that's why Google and others can offer them for free: they don't use them themselves anymore because they have been replaced by V100's in their own research. A GTX 1080TI is much more modern and was, at its introduction, the best consumer card that you could get. If you are looking for a beast deep learning GPU, it's the go-to card to go looking for second hand.

**Comment by svlandeg** [comment]
Thanks for reporting back with such detail @erotavlas! It will surely be useful to others running into the same issue. 

I've lost the track of this thread a bit - can we close this, or are there still spaCy-specific issues to resolve ?

**Comment by erotavlas** [comment]
No more isssues.
