### ISSUE TITLE
https://spacy.io/usage/training#entity-linker "cannot fetch code example" error

### ISSUE THREAD

**Issue by biwa7636** [explosion/spaCy#5384]
The site documentation for [entity-linker](https://spacy.io/usage/training#entity-linker) failed to load `explosion/spaCy/master/examples/training/pretrain_kb.py` with the following error message:

```
Can't fetch code example from GitHub :(

Please use the link below to view the example. If you've come across
a broken link, we always appreciate a pull request to the repository,
or a report on the issue tracker. Thanks!
```
![Screen Shot 2020-04-29 at 7 12 40 PM](https://user-images.githubusercontent.com/3793823/80662417-6ed8b700-8a4e-11ea-9acf-525aed71747d.png)

I pulled the latest code and looks like the example got renamed to be `create_kb.py` and the documentation also got fixed. 

```
    ...
    The following example shows how to build a knowledge base from scratch, given a
    list of entities and potential aliases. The script requires an `nlp` model with
    pretrained word vectors to obtain an encoding of an entity's description as its
    vector.

    ```python
    https://github.com/explosion/spaCy/tree/master/examples/training/create_kb.py
    ```

    #### Step by step guide {#step-by-step-kb}
    ...
``` 
Was it because the site is out of sync of the master branch?

**Comment by svlandeg** [comment]
Thanks for the report! Yes, I need to publish those last edits to the website.

**Comment by svlandeg** [comment]
This is fixed now, if you refresh you'll see the script. Thanks again!
