### ISSUE TITLE
Training with `sgd=None`

### ISSUE THREAD

**Issue by PeriRamm** [explosion/spaCy#5391]
Hi all,

I am trying to better monitor the training process, e.g. similar to [#3272](https://github.com/explosion/spaCy/issues/3272#issuecomment-4671191722). In order to calculate the losses on the validation dataset, we can use `nlp.update()` on the validation dataset, but we have to make sure no training is performed during this call. And for that, the recommendation is to pass `sgd=None`. However, as observed in [#3827](https://github.com/explosion/spaCy/issues/3827), training still occurs, even with this argument.
I also tried the `mock_optimizer()` as described in both of the above, but I get:
> AttributeError: 'function' object has no attribute 'alpha'

My code is a stripped-down version of [train_ner.py](https://github.com/explosion/spaCy/blob/master/examples/training/train_ner.py) and my spaCy version is 2.2.4.
Here are some sample results on a small dataset of 80 sentences/annotations, with `n_iter=20, batch_size=10, dropout=0.2` :

**sgd=optimizer**
0 Losses {'ner': 1464.7454776763916}
1 Losses {'ner': 634.3032090365887}
2 Losses {'ner': 440.0272770226002}
3 Losses {'ner': 410.35564574133605}
4 Losses {'ner': 408.49212035536766}
5 Losses {'ner': 323.394298017025}
6 Losses {'ner': 351.0968653857708}
7 Losses {'ner': 270.81515773385763}
8 Losses {'ner': 285.4459361732006}
9 Losses {'ner': 240.3636882379651}
10 Losses {'ner': 245.11084604263306}
11 Losses {'ner': 169.6679366081953}
12 Losses {'ner': 149.34064027597196}
13 Losses {'ner': 168.96019242657349}
14 Losses {'ner': 126.60987199726515}
15 Losses {'ner': 147.14523822488263}
16 Losses {'ner': 132.61510113321128}
17 Losses {'ner': 108.35290025125141}
18 Losses {'ner': 101.8219898318639}
19 Losses {'ner': 94.16760026384145}

**sgd=None**
0 Losses {'ner': 1394.6776196956635}
1 Losses {'ner': 575.818231523037}
2 Losses {'ner': 415.5179923065007}
3 Losses {'ner': 387.30344139039516}
4 Losses {'ner': 382.1322239115834}
5 Losses {'ner': 349.18331672251225}
6 Losses {'ner': 356.0930958390236}
7 Losses {'ner': 298.56941036880016}
8 Losses {'ner': 306.7900950908661}
9 Losses {'ner': 233.5822250135243}
10 Losses {'ner': 239.88101813942194}
11 Losses {'ner': 200.91727551165968}
12 Losses {'ner': 217.89652734412812}
13 Losses {'ner': 167.43169686105102}
14 Losses {'ner': 127.4877402735874}
15 Losses {'ner': 191.35798652283847}
16 Losses {'ner': 196.55787479749415}
17 Losses {'ner': 104.47489528617007}
18 Losses {'ner': 102.94161436567083}
19 Losses {'ner': 104.83368398029779}

**Comment by honnibal** [comment]
The optimizer is a bit hacky in the current version unfortunately. We're really looking forward to upgrading to the new version of [Thinc](https://thinc.ai) which is much more consistent.

For now you should be able to hack in the extra properties you need on the mock optimizer. I think you should set `alpha`, `b1` and `b2`.

You'll probably find it helpful to refer to the code here: https://github.com/explosion/spaCy/blob/master/spacy/language.py#L479 . Mostly you should be able to just do:

```
losses = {}
for name, proc in nlp.pipeline:
    if hasattr(proc, "update"):
        proc.update(docs, golds, sgd=None, losses=losses)
```

And I would expect that to update the losses without performing any weight updates.

**Comment by PeriRamm** [comment]
Thanks for the answer. For now, instead of re-calculating the losses for training/validation dataset, I will calculate the f-scores, as in [here](https://confusedcoders.com/data-science/deep-learning/how-to-create-custom-ner-in-spacy):

```
def evaluate_spacy(model, examples):
    scorer = Scorer()
    for input_, annot in examples:
        doc_gold_text = model.make_doc(input_)
        gold = GoldParse(doc_gold_text, entities=annot['entities'])
        pred_value = model(input_)
        scorer.score(pred_value, gold)
    return scorer.scores
```
I'll happily take any other advice for better monitoring the training process (e.g. when over-fitting starts)

**Comment by svlandeg** [comment]
I think it makes sense to monitor your training loss and your dev F-score to find the point of overfitting. That's how I usually do it, too.

**Comment by PeriRamm** [comment]
Hello,

I can see what you mean 'hacky'. When trying to output the losses while iterating over batches, it seems that the loss is consistently increasing, as per the below.
I guess that's why in [train_ner.py](train_ner.py) only the losses of the last batch are being printed.

Iteration#  0
 batch 0   losses=165.00
 batch 1   losses=334.33
 batch 2   losses=508.92
 batch 3   losses=647.80
 batch 4   losses=810.17
 batch 5   losses=925.86
 batch 6   losses=1000.54
 batch 7   losses=1053.27
 batch 8   losses=1139.80
 batch 9   losses=1211.72
Time=0.889, Losses= 779.74+-336.03

Iteration#  1
 batch 0   losses= 31.07
 batch 1   losses= 85.74
 batch 2   losses=164.75
 batch 3   losses=191.30
 batch 4   losses=256.13
 batch 5   losses=309.89
 batch 6   losses=375.98
 batch 7   losses=393.55
 batch 8   losses=422.61
 batch 9   losses=469.08
Time=0.795, Losses= 270.01+-141.25

Iteration#  2
 batch 0   losses= 56.11
 batch 1   losses=107.77
 batch 2   losses=153.09
 batch 3   losses=189.11
 batch 4   losses=212.23
 batch 5   losses=263.00
 batch 6   losses=296.29
 batch 7   losses=327.02
 batch 8   losses=373.89
 batch 9   losses=400.11
Time=0.713, Losses= 237.86+-108.17

....

**Comment by svlandeg** [comment]
When calculating the loss of a batch, this value is actually [added](https://github.com/explosion/spaCy/blob/a0998868ffe6d0d8d1a610374f537a4f41eda83e/spacy/syntax/nn_parser.pyx#L596) to the `losses` dictionary and not normalized for # of examples. So it makes sense that this is increasing (and doesn't tell you much otherwise). 

> I guess that's why in train_ner.py only the losses of the last batch are being printed.

The `train_ner.py` script doesn't print the loss of the last batch, but the loss of the last iteration, which includes the losses of each batch within that iteration.

I'll close this for now as I don't think there's any direct action point for us (correct me if I'm wrong Matt). As mentioned, this should hopefully all become more consistent when we integrate the new Thinc in spaCy 3.0.

**Comment by PeriRamm** [comment]
Thanks Sofie,

> doesn't print the loss of the last batch, but the loss of the last iteration

Are you sure we are talking about the same code? In [train_ner.py](https://github.com/explosion/spaCy/blob/master/examples/training/train_ner.py#L78) it seems the printout is in every iteration, right after going over all batches. 

![image](https://user-images.githubusercontent.com/19927743/81423462-623e1800-914c-11ea-9923-c786233f5bd1.png)

Am I missing something? Thanks again.

**Comment by svlandeg** [comment]
I think so, maybe I'm just not expressing myself clearly? One iteration = several batches. So the print on line 78 shows the loss of that iteration, which is the sum of the losses of the batches in that iteration.

In your previous post, you said
> When trying to output the losses while iterating over batches

which I interpreted as printing the `losses` after each `batch` (in the code snippet above, that would be after line 77, but still in the `for batch in batches` loop). 

But if you do that, the `losses` dictionary is not being reset within that inner loop, or normalized to number of examples, so it's quite normal to see a constant increase of loss if you print each batch separately (which would explain the output of your previous post).

**Comment by shyamrallapalli** [comment]
here are my two cents on this issue

if you set `sgd=None` then it is going to set optimizer to a default one based on below code block in languge.py
https://github.com/explosion/spaCy/blob/07639dd6ac9db6f874d1f01ccb5e37a910924feb/spacy/language.py#L496

So i have done following 

```python
from spacy._ml import create_default_optimizer
from thinc.neural import Model
dummy_optimizer = create_default_optimizer(Model.ops)
dummy_optimizer.learn_rate = 0
dummy_optimizer.alpha = 0
dummy_optimizer.b1 = 0
dummy_optimizer.b2 = 0
```
then pass that dummy_optimizer to get eval loss
```
nlp.update(texts, annotations, sgd=dummy_optimizer, losses=eval_losses)
```

**Comment by alexf-a** [comment]
@shyamrallapalli Your solution was the only one that worked for me, using sgd=None or a regular dummy function was giving me behaviour indicating that weight updates were getting made. Metric scores on test way way higher than runs without the dummy optimizer.
