### ISSUE TITLE
Licence fee for using Spacy library in our commercial product

### ISSUE THREAD

**Issue by himanshumohan19** [explosion/spaCy#5394]
Hi ,
We are planning to use spacy in one of our commerical product . can you please let us know f we need to pay any licence fee to use spacy library in our production system?

Thanks

**Comment by adrianeboyd** [comment]
Hi, the library can be used under the terms of the MIT license, which is included in the repository here: https://github.com/explosion/spaCy/blob/master/LICENSE

If you're using any of the provided models, they each have separate licensing information depending on the source corpora, which can be found on the models pages and in the metadata included in the model download (in `meta.json`): https://spacy.io/models/

**Comment by jchonc** [comment]
Sorry to comment on an old closed thread,  but does that mean if we are planning to use en_core_web_sm(MIT) in our commercial product we don't need to worry about the OntoNotes license (LDC)?  There are quite some mixed discussions around if trained model should be bound as derived work thus covered by the license from original dataset thus the confusion.  

Thanks in advance!

**Comment by adrianeboyd** [comment]
We have a membership agreement with LDC for OntoNotes that allows us to distribute models with an MIT license, so this should not be a problem. (OntoNotes is available under several different licenses, which depend on the organization's membership with LDC. The for-profit membership agreement allows for commercial use of derived work.)
