### ISSUE TITLE
NER model trained on Wikipedia Scheme

### ISSUE THREAD

**Issue by akshayparakh25** [explosion/spaCy#5400]
## Environment

* Operating System: Ubuntu 18
* Python Version Used: 3.6 
* spaCy Version Used: 2.1.8

I am working with Wikipedia text and was looking for NER model trained on Wikipedia Scheme. Is there any way, where I can switch it from OntoNotes Scheme to Wikipedia Scheme?

**Comment by adrianeboyd** [comment]
No, the provided model is only trained on OntoNotes. You would need to train your own NER model using Wikipedia data like the WikiNER data that's used for a lot of the non-English provided models.

The training basics are here: https://spacy.io/usage/training

I'd recommend the train CLI for training larger models and I think the convert CLI should also handle converted the WikiNER data with `-c iob`: https://spacy.io/api/cli#train and https://spacy.io/api/cli#convert
