### ISSUE TITLE
Warnings About Python 3.8 Not Yet Merged

### ISSUE THREAD

**Issue by skilfullycurled** [explosion/spaCy#5402]
Hello,

There was an [issue](https://github.com/explosion/spaCy/issues/4593) a while back about installing SpaCy on Python 3.8.  @ines added warnings in a [commit](https://github.com/explosion/spaCy/commit/828ef27a3206a969a56a6dbe47fa38d6e9a1a621) on November 5, 2019 in two places:

1) The repo's README.md between "#install-spacy" and "#pip" 
2) The index.md of the website right above "#Quickstart"

Looks like it was committed, but only [merged](https://github.com/explosion/spaCy/pull/4259#event-2796701907) to the `explosion:develop` branch on November 13, 2019.

Just yesterday I had the same problem as #4593 on both Conda and pip.  I know even small changes to a website can have unintended consequences but I think there would be a lot of benefit to merging this particular fix.

**Comment by adrianeboyd** [comment]
Thanks for the report! I think this status changed and we are now able to provide 3.8 wheels for the newest version, at least for `pip` at this point. If you can't install `v2.2.4` with `pip`, can you provide a little more information about your environment in case there's a problem we need to track down?

I think the `conda` packages on `conda-forge` do still need to be updated to include `v2.2.4`, which is basically just an oversight on our end, thanks for the reminder!

**Comment by skilfullycurled** [comment]
Sure, I'll definitely get some more info.  (Un)fortunately, I was able to install it on 3.7 so I think I deleted the env but I'll set one up as soon as I get the opportunity and get back to you.  Aside from the error message, is there anything else I can send you that would be helpful?  The message isn't more than a few lines long and it's as a result of trying to find it.  There isn't an error when it gets installed, I don't think I got that far.

**Comment by adrianeboyd** [comment]
We should now have `v2.2.4` available through `conda-forge` for python 3.6 and 3.7, but the conda-forge config hasn't been extended to support python 3.8 yet.

**Comment by adrianeboyd** [comment]
Okay, now there should be python 3.8 on `conda-forge`, too, so we don't need to add the warning back. If you are still have trouble installing, please open a new issue with details about the error messages and your environment.

**Comment by skilfullycurled** [comment]
Thanks @adrianeboyd!  As I said, if I get a chance I'll try it again with `pip`.  I'm pretty confident it happened because `pip` is what I tried after `conda-forge` but it's great to have it there since I trust a lot of people who use `conda` will try that first.
