### ISSUE TITLE
Update and Retrain Tagger

### ISSUE THREAD

**Issue by daniyalSelani** [explosion/spaCy#5403]
## Your Environment

I have annotation data on dependencies on a large corpora. I want to train the spacy tagger with this data. I believe there is a high level api i can use (nlp.update) to achieve this. But the api doesnt allow a lot of control on the training process. Also is there a way to train a tagger from scratch?

Thanks!

**Comment by adrianeboyd** [comment]
We would recommend using the train CLI: https://spacy.io/api/cli#train

You can update an existing (base) model  or train a new tagger model from scratch. For a tagger model, you will probably need to provide a tag map that maps the fine-grained tags to UD tags with `--tag-map-path` (the tag map dict in JSON format).

**Comment by daniyalSelani** [comment]
Thank you!
Is there any inherent performance benifit to training the tagger and parser together? Since i eventually want to improve the parsers performance on my corpora as well

**Comment by adrianeboyd** [comment]
The models are completely separate, so there's no benefit to training them together.
