### ISSUE TITLE
binary incompatibility?

### ISSUE THREAD

**Issue by petacube** [explosion/spaCy#5406]
## How to reproduce the behaviour
    from spacy.lang.en import English
../../../../miniconda3/lib/python3.7/site-packages/spacy/lang/en/__init__.py:15: in <module>
    from ...language import Language
../../../../miniconda3/lib/python3.7/site-packages/spacy/language.py:18: in <module>
    from .pipeline import DependencyParser, Tensorizer, Tagger, EntityRecognizer
../../../../miniconda3/lib/python3.7/site-packages/spacy/pipeline/__init__.py:4: in <module>
    from .pipes import Tagger, DependencyParser, EntityRecognizer, EntityLinker
pipes.pyx:1: in init spacy.pipeline.pipes
    ???
E   ValueError: spacy.syntax.nn_parser.Parser size changed, may indicate binary incompatibility. Expected 72 from C header, got 64 from PyObject

## Info about spaCy

* **spaCy version:** 2.0.16
* **Platform:** Darwin-17.7.0-x86_64-i386-64bit
* **Python version:** 3.7.6

**Comment by adrianeboyd** [comment]
Hi, this can happen if there are some conflicting dependencies or outdated files in your installation. We'd recommend trying to install spacy in a new virtual environment to see if that resolves the problem.
