### ISSUE TITLE
en_core_web_sm has been built successfully in conda but facing issue with __init__.py file

### ISSUE THREAD

**Issue by mdwasi89** [explosion/spaCy#5409]
I have installed and built successfully en_web_core_sm but when i run & use code then getting issue. 
I used this code  for import. ** from spacy import en_core_web_sm** then got below error

**ImportError: cannot import name 'en_core_web_sm' from 'spacy' ( ~\Anaconda\lib\site-packages\spacy\__init__.py)**. 

Earlier when i installed couple of packages then after getting the same issue with __init__.py file. Could you please help me how to resolve this error. 

* Python Version Used:  3.7.6
* spaCy Version Used:    2.2.3
* Environment Information: Anaconda

**Comment by adrianeboyd** [comment]
The models like `en_core_web_sm` are installed as separate packages, not as part of the `spacy` module.  Here are examples with several methods for loading models: https://spacy.io/usage/models#usage and https://spacy.io/usage/models#usage-import
