### ISSUE TITLE
Thoughts on updating/retraining Parser

### ISSUE THREAD

**Issue by daniyalSelani** [explosion/spaCy#5410]
I have been updating spacy's parser on my own training data and i had a few questions and thoughts.
1. I have POS annotations as well in my training data, can those be used as input features to train the parser.
2. I also have custom word vectors. As far as  i know the en_core_web_sm doesnt contain any vectors. Will updating the parser for this parser using my vectors make any difference?

Thank you!

**Comment by adrianeboyd** [comment]
1. I don't want to say it's impossible, but not easily, no, unless you're willing to dig into a lot of the spacy code for v2. (This will get easier with the new config system in v3.)
2. You can't add vectors to an existing `sm` model. You'd want to start training from scratch with a new model that's been defined with vectors as features.
