### ISSUE TITLE
Using all attributes in DocBin class

### ISSUE THREAD

**Issue by moh55m55** [explosion/spaCy#5411]
Is it possible to include all token and span states (attributes) when using DocBin class ? instead of specifying which attr to be saved in DocBin(attrs=[]). 
Thanks

**Comment by svlandeg** [comment]
That's currently not possible, no. The default is `None`, which then only stores the standard attributes `orth` and `spacy` (see [here](https://spacy.io/api/docbin#init)). The idea is to keep the serialization as compact as possible by really only saving the information that is required by a certain application.

You could create a custom helper function to try and define the attributes you want for any given doc, if you don't want to hard-code them.  Something like

```
if doc.is_nered():
    attrs.append("ENT_IOB")
    attrs.append("ENT_TYPE")
```
etc.

See also [here](https://spacy.io/api/doc#attributes) for useful functions you can run on `Doc` objects and [here](https://spacy.io/api/token) for more information on the Token-level fields.
