### ISSUE TITLE
en_core_web_sm is Down

### ISSUE THREAD

**Issue by kevinlu1248** [explosion/spaCy#5416]
## How to reproduce the behaviour

Both of the following yield Error 403
```bash
python -m spacy download en_core_web_sm
wget https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.5/en_core_web_sm-2.2.5.tar.gz
```

## Your Environment

* Operating System: Ubuntu 18.04 on three machines
* Python Version Used: 3.6
* spaCy Version Used: 2.2
* Environment Information: 
My project can be found here https://github.com/kevinlu1248/researchy-api, if that helps

**Comment by evanjd** [comment]
We were impacted as well, but it looks like it's back up.

**Comment by svlandeg** [comment]
Looks like there was an issue with Github, cf also Issue #5415
