### ISSUE TITLE
How do I add custom tokenization AND preserve parser (statistical sentencizer)?

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#5420]
From the recommendation on issue #5231

I start with a blank model and modify the existing tokenization rules, then save the model to disk and use that as my base model for downstream tasks including training, pretraining etc.

This is what I start with before editing tokenization rules

```
nlp = spacy.blank('en')
nlp.add_pipe(nlp.create_pipe('sentencizer'))
```

But I notice now my new trained model sentencizer is breaking the sentences poorly compared to if I had just started with blank en model (instead of my custom model from above)

I was looking at this answer https://stackoverflow.com/a/58519668/1462656
Which suggests to use 'parser' instead?

How can I do this? 

**NOTE:** this is for NER and I don't want to start with any of the learned entities from spacy models, which is why I didn't start with en_core_web_em or similar. 

Maybe the closest I want to do is graft the parser from one of the statistical models like en_core_web_sm onto the blank 'en' model.

I tried starting by loading en_core_web_sm instead but was getting an error 

`ImportError: [E048] Can't import language en_core_web_sm from spacy.lang: No module named 'spacy.lang.en_core_web_sm'
`

because in my code to modify tokenization rules I have stuff like this

`r"(?<=[{a}])(?:{h})(?=[{a}])".format(a=ALPHA, h=HYPHENS),
`
using imports 

```
from spacy.lang.char_classes import ALPHA, ALPHA_LOWER, ALPHA_UPPER, HYPHENS, UNITS, PUNCT
from spacy.lang.char_classes import CONCAT_QUOTES, LIST_ELLIPSES, LIST_ICONS, LIST_PUNCT, LIST_QUOTES, CURRENCY
from spacy.util import compile_infix_regex
from spacy.util import compile_suffix_regex 
```

**Comment by adrianeboyd** [comment]
If you don't have vectors, you can add the parser from `en_core_web_sm` to a blank model. The serialization/deserialization step handles reloading everything with the same vocab as the blank model.

```
import spacy
nlp = spacy.blank("en")
nlp_core_sm = spacy.load("en_core_web_sm")
nlp.add_pipe(nlp.create_pipe("parser"))
nlp.get_pipe("parser").from_bytes(nlp_core_sm.get_pipe("parser").to_bytes())
assert nlp.pipe_names == ["parser"]
```
