### ISSUE TITLE
where can I find the test dataset when you do  "Algorithm comparison" 

### ISSUE THREAD

**Issue by wangwang110** [explosion/spaCy#5421]

**Comment by wangwang110** [comment]
I want to know where can I find the dataset "Parse accuracy (Penn Treebank / Wall Street Journal)" 
https://spacy.io/usage/facts-figures#parse-accuracy-penn

**Comment by adrianeboyd** [comment]
This is the original dataset: https://catalog.ldc.upenn.edu/LDC99T42. You'll have to look into the details of which dependency conversions have been used in each paper in that table, since I don't think it's 100% consistent.
