### ISSUE TITLE
Spacy can't finish NER for one (very) long word.

### ISSUE THREAD

**Issue by resuls** [explosion/spaCy#5440]
## How to reproduce the behavior
I have a string consisting of just one repeated character 'a' (300.000 times). The problem is that when I try to find NER in this string spacy just hangs and never finishes the process. I also tried the same string at https://explosion.ai/demos/displacy-ent with spacy version 2.2 and the result is the same.

## Your Environment

* Operating System: Ubuntu 18.04
* Python Version Used: 3.6
* spaCy Version Used: 2.1.9

**Comment by adrianeboyd** [comment]
This is a problem with the regex used to detect URLs (see #4362). It should be improved in spacy v2.2.2-v2.2.4.

If you're not concerned about identifying URLs as tokens, you can just remove the URL regex from the tokenizer. For most languages, you can just set `token_match` to `None`:

```
nlp.tokenizer.token_match = None
```

A few languages use `token_match` to do more complicated tokenization (French, Hungarian), so you'd want to examine the `token_match` definition to remove the URL pattern without removing the other patterns.

**Comment by resuls** [comment]
That solved my issue for now.

**Comment by svlandeg** [comment]
As there is an acceptable work-around, and this should be fixed in newer versions of spaCy, I guess this issue can be closed Adriane? Feel free to reopen if you feel like there is still some action point on our side.
