### ISSUE TITLE
Spacy Custom Entity Recognition Model Training

### ISSUE THREAD

**Issue by cnarul** [explosion/spaCy#5442]
I have problem descriptions from a customer executive and want to categorise them into 6 predefined categories like hardware issue, software issue,etc.
I started with Rule Based Matching Approach and Phrase Matching Approach and used that to train my model. The model is becoming very hardcoded as it is only able to categorise the issues predefined and not even slightly related to it. How should I improve my model?

**Comment by svlandeg** [comment]
Hi @cnarul, these kind of general usage questions are probably better asked at StackOverflow, Gitter or Reddit, as you'd reach a larger community there. It also helps us focus this issue tracker on bugs and feature requests.

Anyway, from your description, I wonder whether it wouldn't make more sense for you to train a custom `textcat` component. This would basically take a sentence (or larger document) as input, and output one or more labels (`exclusive_classes` can be `True` or `False`). You can find more information in our docs [here](https://spacy.io/usage/training#textcat) and [here](https://spacy.io/api/textcategorizer).
