### ISSUE TITLE
displacy issues when representing overlapping arcs

### ISSUE THREAD

**Issue by diegollarrull** [explosion/spaCy#5447]
Hi, I'm using displacy's manual mode to render weigthed depedency graphs (that is, custom labels and, possibly, loops). In the case I get a two-node loop, labels get overwritten and the arc gets overwritten as well. See output below: 

![displacy](https://user-images.githubusercontent.com/468837/82163251-5bb44c80-9880-11ea-8f38-29c735a8952b.png)

Is there any way to offset labels so that I can avoid overlap, or anything similar to use as a workaround? 

## Info about spaCy

* **spaCy version:** 2.2.4
* **Platform:** Darwin-19.4.0-x86_64-i386-64bit
* **Python version:** 3.6.10

Best regards,

**Comment by adrianeboyd** [comment]
The visualizer has been developed for spacy's dependency trees, which aren't allowed to contain cycles. I'm sure this could be supported in theory, but I don't think it's going to be a priority to add support for this. (@ines: Correct me if I'm wrong!)

Maybe there is another visualizer that would be a better choice for these graphs? I only tried on example but it looks like webanno (and therefore possibly just brat, which would be more lightweight than webanno) would support this better. This list of tools is a reasonable place to start if you're looking for dependency tree viewers/editors: https://universaldependencies.org/tools.html#third-party-tools

**Comment by ines** [comment]
Yes, that's correct – if two arcs connect the same tokens, they're currently displayed as overlapping. I can't immediately think of an easy workaround that wouldn't have to touch the rendering algorithm.

It essentially works like this: the arc offsets are determined based on [their levels](https://github.com/explosion/spaCy/blob/master/spacy/displacy/render.py#L147) and each distance (`end - start`) receives a level. For each dependency, we then look up its level and use that to calculate how high to draw the arc, and whether to offset the start and end of the arrow to prevent overlaps. So if we wanted to treat two arcs between the same tokens differently, we'd have to somehow reflect that in the levels and use a different logic here – for instance, key them by `(start, end, label)` or `(distance, label)` if we're not expecting two _identical_ arcs. (Incidentally, that's also – roughly – how I ended up solving it for the [relations UI in Prodigy](https://twitter.com/_inesmontani/status/1259793452541362176) where two tokens can be connected with multiple relations.)

Adding support for this in displaCy definitely wouldn't be a priority, but I'd be happy to accept a PR that adds it 🙂
