### ISSUE TITLE
spacy algorithms

### ISSUE THREAD

**Issue by bayethiernodiop** [explosion/spaCy#5453]
@honnibal  Is there any papers/blog that explains the algorithms used in spacy. Especially the one used for NER recognizer. Thanks

**Comment by svlandeg** [comment]
I'm afraid we haven't really documented this properly yet, sorry. You can go through the [source code](https://github.com/explosion/spaCy/tree/master/spacy/syntax), ofcourse, and there's also this video by Matt on the NER algorithm specifically: https://www.youtube.com/watch?v=sqDHBH9IjRU.

You might be interested to know that Matt's also been experimenting with a [new NER model designed to work with transformers](https://github.com/explosion/spaCy/pull/5449) specifically, which has been achieving promising results. This is coupled to a recent complete rewrite of [thinc](https://thinc.ai/) and of [spacy-transformers](https://github.com/explosion/spacy-transformers/pull/173), which will all come together when we launch spaCy v.3.

Hope that helps!

FYI - please avoid pinging maintainers directly, as it makes our Github mentions more difficult to use.
