### ISSUE TITLE
Inconsistency in tag assigned to opening/closing quote characters

### ISSUE THREAD

**Issue by drfraser** [explosion/spaCy#5455]
```
import spacy
nlp = spacy.load('en_core_web_sm')
text = "I figuered, \"okay, it's just the carpet.\""
document = nlp(text)
for se in document.sents:
    for t in se:
        if t.text == '"': print(t.text, t.pos_, t.tag_, t.is_sent_start)
```
Expected:   (equivalent of Stanford Tagger)
    " PUNCT `` None
    " PUNCT '' None

Actual:  (for en_core_web_sm, en_core_web_md, en_core_web_lg)
    " PUNCT '' None
    " PUNCT '' None

* Operating System:  OS X 10.11
* Python Version Used:  3.8.0
* spaCy Version Used:  2.2.4  (2.2.5 of models)
* Environment Information:  only ran 'python' to get a prompt

If I change the text to 
```
text = "I know people who have worked many years in the hotel industry and they always warned that lazy housekeeping will make things \"appear\" clean but in fact they make no effort to keep things sanitary."
```
then the output is:  (en_core_web_lg, md, and sm)
     " PUNCT  `` None
     " PUNCT backtick backtick None  (markdown not handling this right)

All the other POS and tag values look correct.

1) Should spacy be setting the tags to `` and ", equivalent to the Stanford parser?
2) Am I misunderstanding the docs about opening / closing quotes?
 (re: https://spacy.io/api/annotation#pos-tagging)

The thing is, if these sentences are part of a larger doc (I am doing analysis of fake reviews) the tags actually change - the opening quote is marked as " and the closing as `` or both quotes are the same - never anything correct.  I can not see how these are complex sentences which would break some logic.  I do have a custom sentencizer to deal with bad English issues, but that is working perfectly. Should I look at token.is_sent_start to make sure that is getting set properly? I assume it is, but haven't read the spaCy code yet to see how the tag value gets set.
And I can't find any open or closed issues that might relate to this.

thanks.

**Comment by drfraser** [comment]
I thought of something and tried this: merged the two sentences together like so:
```
text="I know people who have worked many years in the hotel industry and they always warned that lazy housekeeping will make things \"appear\" clean but in fact they make no effort to keep things sanitary.  I figuered, \"okay, it's just the carpet.\""
```
 and printing out each sentence show they get detected properly, but the quotes are still off
```
I know people who have worked many years in the hotel industry and they always warned that lazy housekeeping will make things "appear" clean but in fact they make no effort to keep things sanitary. 
" PUNCT `` None
" PUNCT `` None
I figuered, "okay, it's just the carpet."
" PUNCT '' None
" PUNCT '' None
```

**Comment by adrianeboyd** [comment]
With more standard orthography, the tagger does perform better:

```
text="""I know people who have worked many years in the hotel industry and they
always warned that lazy housekeeping will make things \"appear\" clean but in
fact they make no effort to keep things sanitary.  I figured, \"Okay, it's just
the carpet.\""""
```

Output:

```
" PUNCT `` None
" PUNCT '' None
" PUNCT `` None
" PUNCT '' None
```

Using a current English provided model, I think you could have a post-processing step that looks at whitespace to improve the tags for quotes with relatively high accuracy for examples like these. The tagger doesn't use the sentence boundaries at all, so modifying those won't make a difference.

The tagger doesn't currently have as a feature for whether the token is followed by a space, which I think would potentially help the performance in this particular case.

In general, statistical models will make some mistakes, especially if the text looks different from the kinds of standardized/edited newspaper texts the model is trained on or if potentially relevant features are missing. In the future, issue #3052 is a good place to report issues like this, thanks!
