### ISSUE TITLE
lemmatizer does not take adverb as a parameter currently

### ISSUE THREAD

**Issue by luffycodes** [explosion/spaCy#5459]
## Feature description
Lemmatizer just takes NOUN, ADV, and VERB as the parameter. Can you please add ADVERB to it as well - https://github.com/explosion/spaCy/blob/develop/spacy/lemmatizer.py?

**Comment by adrianeboyd** [comment]
Yes, this should be extended to cover all the UPOS tags. I think a few things related to English might break if we modify the `PROPN` behavior, but for all the other UPOS tags, this should be easy to extend.
