### ISSUE TITLE
Test session. "3 failed" 

### ISSUE THREAD

**Issue by jhave** [explosion/spaCy#546]
i just installed and ran test
"3 failed" --is this normal?

Terminal Output:
_________________

$ python -m pytest //anaconda/lib/python3.5/site-packages/spacy --vectors --model --slow
============================= test session starts =============================
platform darwin -- Python 3.5.2, pytest-3.0.3, py-1.4.31, pluggy-0.4.0
rootdir: /anaconda/lib/python3.5/site-packages/spacy, inifile: 
collected 292 items 

. ............X..............................................................................................X.......x...............................................x....x.............................................................................................Xxx................FFF........

================================== FAILURES ===================================
________________________ test_get_tokens_and_sentences ________________________

doc = This is a sentence. This is another sentence. And a third.

    @pytest.mark.models
    def test_get_tokens_and_sentences(doc):
        token = doc[0]
        sentence = next(doc.sents)
        assert token is sentence[0]
>       assert sentence.text == 'Hello, world.'
E       assert 'This is a sentence.' == 'Hello, world.'
E         - This is a sentence.
E         + Hello, world.

//anaconda/lib/python3.5/site-packages/spacy/tests/website/test_home.py:30: AssertionError
____________________ test_use_integer_ids_for_any_strings _____________________

nlp = <spacy.en.English object at 0x1777bd588>, token = This

    @pytest.mark.models
    def test_use_integer_ids_for_any_strings(nlp, token):
        hello_id = nlp.vocab.strings['Hello']
        hello_str = nlp.vocab.strings[hello_id]
    
>       assert token.orth  == hello_id  == 3125
E       assert 580 == 3125
E        +  where 580 = This.orth

//anaconda/lib/python3.5/site-packages/spacy/tests/website/test_home.py:38: AssertionError
___________________ test_get_and_set_string_views_and_flags ___________________

nlp = <spacy.en.English object at 0x1777bd588>, token = This

    def test_get_and_set_string_views_and_flags(nlp, token):
>       assert token.shape_ == 'Xxxxx'
E       assert 'Xxxx' == 'Xxxxx'
E         - Xxxx
E         + Xxxxx
E         ?     +

//anaconda/lib/python3.5/site-packages/spacy/tests/website/test_home.py:43: AssertionError
======== 3 failed, 281 passed, 5 xfailed, 3 xpassed in 191.91 seconds =========

**Comment by honnibal** [comment]
Nope, not normal.

Do you have the data installed?

```bash
python -m spacy.en.download all
```

**Comment by honnibal** [comment]
This should be fixed in 1.1.2. Please reopen if it's not.

**Comment by jhave** [comment]
yes. ran following without problems before the test:

*$ python -c "import spacy; spacy.load('en'); print('OK')"*

*OK*

*$ python -c "import os; import spacy;
print(os.path.dirname(spacy.__file__))"*

*//anaconda/lib/python3.5/site-packages/spacy*

**Comment by thmai** [comment]
Hi, 
pytest also failed for me at lemmatizer
`$ python3 -m pytest /usr/local/lib/python3.5/site-packages/spacy --vectors --models --slow
================================================================= test session starts ==================================================================
platform darwin -- Python 3.5.2, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: /usr/local/lib/python3.5/site-packages/spacy, inifile:
collected 2929 items

../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/test_attrs.py ...
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/test_download.py ......
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/test_orth.py .......................................................
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/test_pickles.py .x
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/doc/test_add_entities.py .
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/doc/test_array.py ...
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/doc/test_doc_api.py ............
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/doc/test_noun_chunks.py .
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/doc/test_token_api.py ........
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/matcher/test_entity_id.py ...
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/matcher/test_matcher.py ...........
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/parser/test_ner.py ...
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/parser/test_nonproj.py .....
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/parser/test_noun_chunks.py .....
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/parser/test_parse.py ......
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/parser/test_parse_navigate.py ...
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/parser/test_sbd.py ......
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/parser/test_sbd_prag.py ..x....x.....xx..x......x.....xxx.xxxxx..x..x..x.xxx
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/parser/test_space_attachment.py ......
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/serialize/test_codecs.py ...
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/serialize/test_huffman.py .....
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/serialize/test_io.py ...
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/serialize/test_packer.py .....
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/serialize/test_serialization.py ..........
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/spans/test_merge.py ......
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/spans/test_span.py .......
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/stringstore/test_freeze_string_store.py .
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/stringstore/test_stringstore.py ..........
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/tagger/test_lemmatizer.py .....F...
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/tagger/test_morph_exceptions.py .
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/tagger/test_spaces.py ..
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/tagger/test_tag_names.py .
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/tokenizer/test_exceptions.py ............................................
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/tokenizer/test_tokenizer.py ............................................................................................................................................................................................
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/tokenizer/test_urls.py ...................................xx...................................xxx....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/tokenizer/test_whitespace.py .............................................................................
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/vectors/test_similarity.py .....
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/vectors/test_vectors.py ...............
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/vocab/test_add_vectors.py .
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/vocab/test_lexeme.py ......
../../../../../../usr/local/lib/python3.5/site-packages/spacy/tests/vocab/test_vocab_api.py ....................

======================================================================= FAILURES =======================================================================
__________________________________________________________ test_tagger_lemmatizer_base_forms ___________________________________________________________

lemmatizer = <spacy.lemmatizer.Lemmatizer object at 0x1047cee10>

    @pytest.mark.models
    def test_tagger_lemmatizer_base_forms(lemmatizer):
        if lemmatizer is None:
            return None
>       assert lemmatizer.noun('dive', {'number': 'sing'}) == set(['dive'])
E       AssertionError: assert {'diva'} == {'dive'}
E         Extra items in the left set:
E         'diva'
E         Extra items in the right set:
E         'dive'
E         Use -v to get the full diff

/usr/local/lib/python3.5/site-packages/spacy/tests/tagger/test_lemmatizer.py:23: AssertionError
================================================= 1 failed, 2902 passed, 26 xfailed in 745.17 seconds ==================================================
`
I can import and invoke downloaded models, no issue, only have problem when I use `assert x == y`
