### ISSUE TITLE
Lemmatization is not working properly in the new version of Spacy_2.2.4. 

### ISSUE THREAD

**Issue by jacksonsunny29** [explosion/spaCy#5469]
Lemmatization is not properly reducing the words to their root words. The lemmatized word in not getting stored to text.lemma_. But its working properly in Spacy_2.2.0

**Comment by svlandeg** [comment]
Could you share some examples of words that are not properly lemmatized in the current version, but are in the older one ?

**Comment by jacksonsunny29** [comment]
<img width="913" alt="Screenshot 2020-05-21 at 11 24 24 AM" src="https://user-images.githubusercontent.com/36571126/82528117-b33f0a80-9b55-11ea-80e6-adc3522389e6.png">
The above given  code is written using spacy 2.2.4 and as seen in the output below, no words have been lemmatized.

<img width="1179" alt="Screenshot 2020-05-21 at 11 24 32 AM" src="https://user-images.githubusercontent.com/36571126/82528196-e08bb880-9b55-11ea-9ef4-bd3a49a881d0.png">

The below given code is written using spacy 2.2.0 and all the word were lemmatized perfectly.

<img width="612" alt="Screenshot 2020-05-21 at 11 24 43 AM" src="https://user-images.githubusercontent.com/36571126/82528336-23e62700-9b56-11ea-9225-4c5f0e889e17.png">

**Comment by adrianeboyd** [comment]
If you're using a blank model (with `nlp = English()` or `nlp = spacy.blank("en")`), you need to have the additional package `spacy-lookups-data` installed in order to have the data for the lookup lemmatizer. You can install it directly or with the option `spacy[lookups]` when installing spacy.

Could you check if you have `spacy-lookups-data` installed in the v2.2.0 virtual environment but not in the v2.2.4 virtual environment? This would explain the difference you're seeing.

**Comment by jacksonsunny29** [comment]
No I've installed v2.2.0 without any lookups.

**Comment by adrianeboyd** [comment]
Hmm, v2.2.0 should be the version where the lookups were moved out of the main library and into `spacy-lookups-data`, so I'm not sure what's going on. My only guess at this point is that an upgrade didn't clean up all the lemmatizer files from an older version and they're still getting loaded unintentionally.

What do you see if you install v2.2.0 in a brand new virtual environment?

And if you install `spacy-lookups-data` with v2.2.4, does your example provide the lemmas as expected?

**Comment by jacksonsunny29** [comment]
The spacy version 2.2.4 works fine with lemmatization when lookups are installed.
Please do: `pip install spacy-lookups-data`
Thanks a lot, everyone😊
