### ISSUE TITLE
Updating to spacy 1.0 fails on Windows

### ISSUE THREAD

**Issue by notnami** [explosion/spaCy#547]
Hi!

I tried updating to spacy 1.0 and got the "Unknown MS Compiler version 1900" error. 

I know this error shows up when trying to install numpy and related packages on Windows from source, but I am using anaconda, and so should have all the dependencies, and they should all be up to date (including numpy 1.11.12).

Has anyone else encountered this, or is there something I'm missing?

For reference, I'm using Python 3.5 under Windows 10 with VS2015.

Thanks!

**Comment by honnibal** [comment]
(Btw — If this issue affects you, please add a reaction thumbs!)

**Comment by notnami** [comment]
I take it the VS2015 compiler won't suffice?

**Comment by notnami** [comment]
I would like to point out that installing spacy 1.2 works under Python 3.6b3 on Windows.

**Comment by honnibal** [comment]
There's now more activity on getting conda updated — binary wheels should follow 🎉 

Follow #778 for progress.
