### ISSUE TITLE
Question: Why java-style getters & setters

### ISSUE THREAD

**Issue by Ablesius** [explosion/spaCy#5487]
Hi explosion team,

while browsing the spacy API documentation I found some examples of java-style setters & getters, e. g. [here](https://github.com/explosion/spaCy/blob/65c7e82de24739977d7ca775d585cacc7dc25cd5/spacy/lexeme.pyx#L88) and in [this issue comment](https://github.com/explosion/spaCy/issues/860#issuecomment-282681155). I was wondering whether you do this on purpose? I ask because [Python Anti-Patterns](https://docs.quantifiedcode.com/python-anti-patterns/correctness/implementing_java-style_getters_and_setters.html) defines this as unpythonic, and recommends using `@property` decorators instead. My question is totally open to reasoning, I'm curious whether this is something you'd be interested to change or whether you made a conscious decision to do it, and if so why :)

Cheers,
Alex

**Comment by honnibal** [comment]
Actually we do a fair bit with properties, but that method in particular takes a list, so it's a different interface. Also setters allow keyword arguments, where attribute assignment does not. Setters are also more transparent in some issues.

In general rules-of-thumb will only go so far in any problem that comes down to balancing multiple trade-offs. I must say I took exception to your comment: it came across as condescending and presumptuous. You're asking "Have you thought about the decisions behind your API", and the answer is...well, yes! And no we're not open to discussing changes to it on the basis of reference to generic rules of thumb.

**Comment by Ablesius** [comment]
> I must say I took exception to your comment: it came across as condescending and presumptuous.

I'm sorry you took it that way. As I said, that was not my intention. I'm trying to understand how and why things are done in order to learn. I don't assume to know better; I assume you had a good reason, and I was trying to ask what that reason was, so that I can learn why my "counter example" is _not_ a good idea or not applicable for that case.

> You're asking "Have you thought about the decisions behind your API"

That is actually not what I meant to ask, but I can see now why it came across as such. I'm sorry for this misunderstanding. I assumed that you know very well what you are doing, and I'm not pointing out something you would have overlooked. I rather thought "I know of decorators, and here I see something different, why is this solution better than decorators? There must be a reason".

Thank your for your explanation. I will try to understand it in detail.

Best regards,
Alex
