### ISSUE TITLE
Add 'head token index' attribute to words in nlp(doc)

### ISSUE THREAD

**Issue by Mustyy** [explosion/spaCy#549]
@honnibal 

When navigating a spaCy-processed document, e.g --

from spacy.en import English
nlp = English()
doc = nlp('The old man shook hands with the young man.')
for word in doc:
    print(word, word.tag_, word.head.i)

the result of using word.head.i  or token.head.i
gives incorrect position of the tokens in the sentence
Is there a workaround?

The DT 2
old JJ 2
man NN 3
shook VBD 3
hands NNS 3
with IN 3
the DT 8
young JJ 8
man NN 5
. . 3

**Comment by honnibal** [comment]
Hm? The head of "The" is "man". So `doc[0].head.i == 2` --- because "man" is at index 2.
