### ISSUE TITLE
AttributeError: module 'cupy' has no attribute 'resize' while using  retokenizer.merge with CUDA

### ISSUE THREAD

**Issue by jenspedde** [explosion/spaCy#5494]
if model has vectors and gpu is used, spacy calls retokenizer.merge( ) an unsupported cupy method resize as mentioned in
[https://docs-cupy.chainer.org/en/stable/reference/comparison.html](url)
## prerequisites

- CUDA

- model with vectors

## How to reproduce the behaviour
import spacy  
spacy.require_gpu()
nlp = spacy.load("en_core_web_md")
doc = nlp("just an example")
spans = list(doc.noun_chunks)
spans = spacy.util.filter_spans(spans)
with doc.retokenize() as retokenizer:
        for span in spans:
            retokenizer.merge(span)

## Stack
_retokenize.pyx in spacy.tokens._retokenize.Retokenizer.__exit__()
_retokenize.pyx in spacy.tokens._retokenize._merge()
vocab.pyx in spacy.vocab.Vocab.set_vector()
vectors.pyx in spacy.vectors.Vectors.resize()
AttributeError: module 'cupy' has no attribute 'resize'

## Environment
spaCy version    2.2.4
Platform         Windows-10-10.0.18362-SP0
Python version   3.7.4
cupy-cuda102                       7.4.0

**Comment by adrianeboyd** [comment]
Thanks for the report! This has been fixed in #5216 and the fix will be included in the upcoming v2.3.0 release.
