### ISSUE TITLE
difference between entail_dir=left and entail_dir=right and entail_dir=both

### ISSUE THREAD

**Issue by pourjafari** [explosion/spaCy#5501]
hi
What is the difference between entail_dir=left and entail_dir=right and entail_dir=both in decomposition attention (parikh)?

What is a vanilla and Intra-sentence Attention model? 
Is this code vanilla  or Intra-sentence Attention ?

**Comment by adrianeboyd** [comment]
Hi, I'm not sure this is the right issue tracker for your question? If it's a question related to spacy, could you provide more context about what you're asking?

**Comment by pourjafari** [comment]
question in 
https://github.com/explosion/spaCy/blob/master/examples/keras_parikh_entailment/keras_decomposable_attention.py

**Comment by svlandeg** [comment]
I'm afraid this example may have gone a bit out-of-date, but you can find more information in the original paper, https://arxiv.org/pdf/1606.01933.pdf by Parikh et al.
