### ISSUE TITLE
Unable to restore the original sentence with the dependency tree, and inconsistency between output and the demo in https://explosion.ai/demos

### ISSUE THREAD

**Issue by entalent** [explosion/spaCy#5505]
## How to reproduce the behaviour

```
import spacy
from spacy import displacy
nlp = spacy.load('en_core_web_sm')
sent = 'A street sign is seen in front of a bench and some flowers'
doc = nlp(sent)
for token in doc:
    print(token.text, token.dep_, token.head.text, token.head.pos_, [child for child in token.children])
displacy.serve(doc, style='dep')
```

The output in the console:
```
A det sign NOUN []
street compound sign NOUN []
sign nsubjpass seen VERB [A, street, flowers]
is auxpass seen VERB []
seen ROOT seen VERB [sign, is, in]
in prep seen VERB [front]
front pobj in ADP [of]
of prep front NOUN [bench]
a det bench NOUN []
bench pobj of ADP [a, and]
and cc bench NOUN []
some det flowers NOUN []
flowers acl sign NOUN [some]
```

The visualization of displacy:
![image](https://user-images.githubusercontent.com/10328486/82857229-0395de00-9f43-11ea-9186-2318a2529f03.png)

I am unable to restore the order of words in the original sentence with this dependency tree. The word `flowers` is in the right of the root `seen`  , but it is a child of the word `sign` which is in the left of the root `seen`.

The output of the spacy demo (https://explosion.ai/demos/displacy?text=A%20street%20sign%20is%20seen%20in%20front%20of%20a%20bench%20and%20some%20flowers&model=en_core_web_sm&cpu=1&cph=0) seems correct, but inconsistent with the output I got.

## Info about spaCy

* **spaCy version:** 2.2.4
* **Platform:** Linux-4.4.0-142-generic-x86_64-with-debian-jessie-sid
* **Python version:** 3.7.4

* Operating System: Ubuntu 14.04.6 LTS
* Python Version Used: python 3.7
* spaCy Version Used: 2.2.4
* Environment Information: en-core-web-sm 2.2.5 is installed

**Comment by entalent** [comment]
Just experimented with spacy 2.2.0 and en-core-web-sm 2.2.0 and the output is correct... So is it because the en-core-web-sm 2.2.5 and spacy 2.2.4 package are incompatible?

**Comment by adrianeboyd** [comment]
All the v2.2.x models are compatible with spacy v2.2.x, but there can be some small differences across model versions due to minor changes to the language configuration (like the tokenizer) or the training setup.

A dependency tree on its own does not provide enough information to determine the order of the words in a sentence. The order is provided by the `Doc`, where each token has the attribute `token.i` as its position in the doc.
