### ISSUE TITLE
New Model for Contribution

### ISSUE THREAD

**Issue by lordtt13** [explosion/spaCy#5509]
I have been working on a spacy model trained on word2vec vectors based on the CORD-19 dataset, a large model based on all training data and a small model based on only the abstracts of the research papers. All of my work is done in collaboration with @smoke-trees and @CYBINT-IN. How do I go about the submission?

**Comment by adrianeboyd** [comment]
This kind of contribution is typically added as an entry to the spacy universe page. Check out https://spacy.io/universe and see the info at the bottom of the page for details on how to submit your project.

**Comment by lordtt13** [comment]
Thank you, will definitely create one PR on the website repository.
