### ISSUE TITLE
Strange behaviour with lemmatization

### ISSUE THREAD

**Issue by Arjunsankarlal** [explosion/spaCy#5511]
I am trying to create a small pipeline which should do tokenization and lemmatization. And following [this](https://spacy.io/api/tokenizer) pretty much does everything for me. Initially thought it only tokenizes the text, but later found out lemma is also done.

So when I compare the outputs of the normal way, 
```
nlp = spacy.load("en")
tokens = nlp("Some text")
```
and 
```
nlp = English()
tokenizer = english_nlp.Defaults.create_tokenizer(english_nlp)
tokens = tokenizer("Some text")
```
I find that the tokens are similar for both the methods, but the lemma results vary, but only for few words, below are some examples (first line and second line of each item corresponding to the above methods tried) and each line has (actual_token lemma) format

```
you -PRON- 
you you 
------------------------------
it -PRON-
it it
------------------------------
its -PRON-
its its
------------------------------
more more
more much
------------------------------
followed followed
followed follow
------------------------------
an an
an a
------------------------------
she -PRON-
she she
------------------------------
their -PRON-
their their
------------------------------
related related
related relate
------------------------------
left left
left leave
------------------------------
``` 

## Info about spaCy

* **spaCy version:** 2.0.18
* **Platform:** Darwin-18.0.0-x86_64-i386-64bit
* **Python version:** 3.6.2
* **Models:** en

So I am missing something, or is this an actual bug ? Any help would be much appreciated.

Thanks for the awesome work ❤️

**Comment by Arjunsankarlal** [comment]
So I guess, here the text is not processed with the `parser` pipeline and hence this difference is caused. If this is the reason, feel free to close the issue :)

**Comment by svlandeg** [comment]
The lemmatizer indeed uses the POS tags. When you're using a blank model like `English()` and don't have tags available, you need to have the additional package `spacy-lookups-data` installed in order to have the data for the lookup lemmatizer. You can install it directly or with the option `spacy[lookups]` when installing spaCy, see also Issue #5469 for more background.
