### ISSUE TITLE
How to load model files, without link variable?

### ISSUE THREAD

**Issue by ValeriiBaidin** [explosion/spaCy#5515]
I use spacy in Julia from PyCall.
I work on Unix server. 
I've installed spacy by Conda. 
Unfortunately,  I don't have excess to an executable python file, so I can't run any of this time "python -m .........." 
How can I use models, without "python -m ...." commands.

Thank you in advance.

**Comment by adrianeboyd** [comment]
The models are available as `pip` packages that you can download and install directly. Click the blue "Release Details" button next to any model on https://spacy.io/models to go to the release page, which has the model as a `.tar.gz ` asset at the bottom. Directions are here: https://spacy.io/usage/models#download-pip

Within a `conda` env, one option would be installing `pip` in your env and using it to install the spacy models from the github URLs. There are also some unofficial spacy model packages on `conda-forge` but we can't vouch for the contents.
