### ISSUE TITLE
Autocompletion broken with basic setup

### ISSUE THREAD

**Issue by LifeIsStrange** [explosion/spaCy#5520]
## How to reproduce the behaviour
Create a basic spaCy hello world and retrieve Doc element

## Your Environment

* Operating System: Linux Manjaro
* Python Version Used: 3.8+
* spaCy Version Used: 2.2+
* Environment Information: Pycharm professional 2020.1

Hi, I have created my first spaCy project and Pycharm professional cannot autocomplete anything from spaCy.
I am NOT using virtualenv, I have only one version of spaCy on my system, installed with pip install spaCy.
I am using latest spaCy release (2.2 +) with python 3.8

I import spaCy in my code use nlp() to get the Doc element of a text and it works at runtime.
But I have zero autocomplete, I constantly fall into errors such as do my token has .root or .lemna_ field it is horrible to work with, its the 21's century autocomplete should just work (tm).

What should I do ? It's been a few days of struggle and if I cannot make it work I am going to switch to a java / kotlin lib, please help !

**Comment by LifeIsStrange** [comment]
Dumb example:

import pandas
import spaCy

df = pandas.DataFrame() 
now if I use df (from the pandas lib) I can get proper autocompletion

nlp = spacy.load("en_core_web_sm")

instead I have zero autocomplete with nlp or any other subsequent object from spaCy.

Is this the expected behavior of the library ?

**Comment by LifeIsStrange** [comment]
The problem both reproduce on VScode and Pycharm but not on jupyter notebook, why ?

**Comment by svlandeg** [comment]
Not sure what may be going on, but autocompletion just works on my system with Pycharm:

![image](https://user-images.githubusercontent.com/8796347/90773359-0f046580-e2f6-11ea-97c4-5a93bc8e9d0b.png)

**Comment by svlandeg** [comment]
Is this still an issue for you with the latest spaCy 2.3.2?
