### ISSUE TITLE
Checking if model is compatible (without using CLI )

### ISSUE THREAD

**Issue by d5555** [explosion/spaCy#5522]
What is the best way to check if a model is compatible with my version of spaCy?  **(without using CLI )**
For instance I got some old models trained with spaCy 2.0.0 and now I'm using 2.2.4.  I still can load old model but then I get an error when I start parsing. 

## Your Environment
* **spaCy version:** 2.2.4
* **Platform:** Windows-10 
* **Python version:** 3.7.3

**Comment by adrianeboyd** [comment]
For spacy v2, models are compatible if they were trained with the same major.minor version, so models trained with v2.0.x are compatible with spacy v2.0.x, likewise for v2.1 and v2.2. You can see the version that a model was trained with in `meta.json` under the key `spacy_version`, or if you can load the model under `nlp.meta` (ignore the `>=`, which isn't really accurate).

Across minor versions some of the default model parameters or the model serialization details may change. The CLI can only validate the models provided by spacy (it checks a compatibility table), so it's not able to check custom models.

Models from v2.0.0 won't be compatible with v2.2.4, so you'll need to train new models on your data for v2.2.

**Comment by d5555** [comment]
It would be nice to have an option to validate model. 
Smth like this:
`spacy.validate('model')`

**Comment by adrianeboyd** [comment]
This has been added for the upcoming spacy v3 in #5516 and there are some simpler checks/warnings added in a similar way for v2.3 in #5535 (limited to some extent by still supporting python 2.7).
