### ISSUE TITLE
💫 Document workflow: Training the tagger, parser and entity recogniser

### ISSUE THREAD

**Issue by ines** [explosion/spaCy#553]
We're [reorganising and improving the docs and tutorials](https://github.com/explosion/spaCy/projects/2). The new docs will separate task-oriented workflows from the basic API reference. This issue is the one to follow to stay in the loop about this topic – closing the related issues to keep the discussion in one place.

Addresses: #339, #494, #490, #120, #187, #479, #473, #288, #452, #62

**Comment by honnibal** [comment]
Done: https://spacy.io/docs/usage/training

Can always use more examples, iterations etc. But, closing this.
