### ISSUE TITLE
Windows Docker - Spacy language model installation in python returns ImportError: DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by Soumya44** [explosion/spaCy#5539]
I am building a Windows-based Docker image to run a Flask Application. For that, I need SpaCy language model to be installed. But I am encountering the following issue again and again and could not find any robust solution till yet.

**Runtime:** Windows Container (Docker)

**Error Trace:**  

    Step 6/9 : RUN python -m spacy download en_core_web_sm
     ---> Running in 6f8f33207c8f
            Traceback (most recent call last):
          File "C:\Python\lib\runpy.py", line 183, in _run_module_as_main
            mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
          File "C:\Python\lib\runpy.py", line 142, in _get_module_details
            return _get_module_details(pkg_main_name, error)
          File "C:\Python\lib\runpy.py", line 109, in _get_module_details
            __import__(pkg_name)
          File "C:\Python\lib\site-packages\spacy\__init__.py", line 12, in <module>
            from . import pipeline
          File "C:\Python\lib\site-packages\spacy\pipeline\__init__.py", line 4, in <module>
            from .pipes import Tagger, DependencyParser, EntityRecognizer, EntityLinker
          File "pipes.pyx", line 1, in init spacy.pipeline.pipes
        ImportError: DLL load failed: The specified module could not be found.

**Dockerfile:**

    FROM winamd64/python:3.7-windowsservercore
    COPY requirements.txt .
    COPY models/* ./models/
    RUN pip install --no-cache-dir -r requirements.txt
    RUN python -m nltk.downloader stopwords
    RUN python -m spacy download en_core_web_sm
    COPY . .
    EXPOSE 5000
    CMD python waitress_server.py

**requirements.txt:**  

    Flask==1.1.1
    future==0.17.1
    httplib2==0.13.1
    nltk==3.4.5
    numpy==1.18.2
    pandas
    pandocfilters==1.4.2
    pickleshare==0.7.5
    regex==2019.8.19
    requests>=2.13.0
    requests-oauthlib
    requests-toolbelt
    scikit-learn==0.22.1
    scipy==1.3.1
    simplejson==3.16.0
    urllib3==1.24.3
    xlrd==1.2.0
    zipp==0.6.0
    lightgbm
    sner
    flask-bcrypt
    waitress==1.4.4
    spacy

**waitress_server.py:**

    print("Hello World")

Other files are some trained NLP models.

**Note:** 

 - I have tried with multiple versions of windows images but no result
 - I have tried with multiple NumPy and spacy versions
 - Found an Issue on GitHub [https://github.com/explosion/spaCy/issues/4733#issuecomment-561123652][1] But it doesn't seem to solve the issue.

Thanks in Advance!

  [1]: https://github.com/explosion/spaCy/issues/4733#issuecomment-561123652

**Comment by adrianeboyd** [comment]
This looks related to #5332.

**Comment by jpraveenkanna** [comment]
The issue may be because of lack in dependency with the Spacy version installed.
Use `Validate` command to see incompatibility issues and installation instructions.

It might help to solve the issue.

`python -m spacy validate`

**Comment by svlandeg** [comment]
@Soumya44 : have you had any luck trying to fix this, or is the issue still persisting?
