### ISSUE TITLE
💫 Document workflow: Part-of-speech tagging

### ISSUE THREAD

**Issue by ines** [explosion/spaCy#554]
We're [reorganising and improving the docs and tutorials](https://github.com/explosion/spaCy/projects/2). The new docs will separate task-oriented workflows from the basic API reference. This issue is the one to follow to stay in the loop about this topic – closing the related issues to keep the discussion in one place.

Addresses: #176, #191, #527

**Comment by honnibal** [comment]
# Usage

```python

nlp.tagger(doc)
for word in doc:
    print(word.text, word.lemma, word.lemma_, word.tag, word.tag_, word.pos, word.pos_)
```

# Coarse and fine part-of-speech tags

`token.tag` vs `token.pos`

# Lemmatizer

* Explain what a lemma is
* Mention we use WordNet's algorithm for English
* Currently no lemmatizer for German

# English POS tag scheme

# German POS tag scheme
