### ISSUE TITLE
Option -t for python -m spacy init-model doesn't exist

### ISSUE THREAD

**Issue by mohateri** [explosion/spaCy#5540]
## How to reproduce the behaviour

In the [doc](https://spacy.io/api/cli#init-model) it is specified that the `-t` option can be used to truncate the word vectors to a certain extent, but as I tried to run the following command I had an error message: 
`python -m spacy init-model fr /my/directory --vectors-loc my_vectors.tar.gz -t 100`

The error message stated that the `-t` option was invalid: 
![image](https://user-images.githubusercontent.com/30265937/83730944-0fbc2280-a64a-11ea-998e-7bea713d3d2d.png)

So I was wondering why the doc presents it as a valid option, and what can I do in order to truncate the word vectors?

## Your Environment

* **spaCy version:** 2.2.4
* **Platform:** Windows-10-10.0.17134-SP0
* **Python version:** 3.6.5

**Comment by svlandeg** [comment]
Hi! This is a very recent addition to init_model, cf PR #5362. It will be available from 2.3 onwards (or if you build spaCy from source). We'll clarify that in the docs. Thanks for the report !

**Comment by mohateri** [comment]
Thank you for the fast reply and for all the work to improve spaCy!
