### ISSUE TITLE
Spacy dependency parser not showing correct tags

### ISSUE THREAD

**Issue by APNS1976** [explosion/spaCy#5549]
Our requirement:
We are using the spacy model for extracting Medical Entity Relations from Texts using Dependency Information (Connecting accurately SITE with adverse event(AE)).
Example:
Burning, Itching, Blemishes on Facial skin and itching, swelling and rashes on neck
Here for first clause “Burning, Itching, Blemishes on Facial skin”
AE are “Burning, Itching, and Blemishes” and site is “Facial skin”
And in second clause “itching, swelling and rashes on neck”
AE are “itching, swelling and rashes” and site is “neck”
In both cases AE should be accurately connected to site
Like this we are having 5k+ review reports (Texts)
We tried custom tags to label AE and SITES and custom routing strategy also. It did not work.
Also, Routing strategy defined by the “en_core_web_md” model with standard labels defined in UD
ae --> clf, site -->  cop, ae_dep --> fixed, site_dep --> flat, list, parataxis, goeswith 
even this doesn’t work either.

Training method:
We use nlp.update method call to train a custom dependency model. 
Note: Blank English model (“en”) is used to train the model.

Issue:
Parser replaces the dependency label that we defined while annotating, with lables like xcomp, conj, dobj, pobj etc.,
One Eg: During pregnancy , I had to vomit from brushing my teeth 
In above example we have tagged Vomit as “clf”. After training, it has changed that tag as “xcomp”  from “clf”

Info about environment:
•	spaCy version: 2.2.4
•	Platform: windows 10
•	Python version: 3.7.7
Could you please let us know how to solve this issue? Your Quick response will be highly appreciated.

**Comment by leomrocha** [comment]
I'm no expert in SpaCy, so please correct me if I get the issue wrong.
From what I read on @APNS1976 's description you are trying to use SpaCy's *dependency* parser as another kind of parser for more of a NER (Named Entity Recognition) task.

If I'm on the right track I wouldn't modify the parser as it gives important clues to later being able to identify the right relationships between tokens, instead I would train a NER stage in the pipe using the parsed dependencies as entry for this stage.

**Comment by APNS1976** [comment]
NER is extracting the entities but issue is Parser is not showing the correct relationship for us to link the entities properly. 
For  Example as mention: Burning, Itching, Blemishes on Facial skin and itching, swelling and rashes on neck
Code :
  text = '''Burning, Itching, Blemishes on Facial skin and itching, swelling and rashes on neck'''
  print(text)
  text = _re.remove_interfering_characters(text)
  doc = nlp(text)
  [print (t.text,t.dep_,t.head.text, t.head.dep_) for t in doc ]

Output:
Burning, Itching, Blemishes on Facial skin and itching, swelling and rashes on neck
Burning ROOT Burning ROOT
, punct Burning ROOT
Itching conj Burning ROOT
, punct Itching conj
Blemishes dobj Burning ROOT
on prep Blemishes dobj
Facial amod skin pobj
skin pobj on prep
and cc skin pobj
itching conj skin pobj
, punct itching conj
swelling conj itching conj
and cc swelling conj
rashes conj swelling conj
on prep rashes conj
neck pobj on prep

According to the text, burning, itching and blemishes should be attached to the Facial skin only and itching, swelling and rashes should connect with neck only. But parser attaches
1. The “itching” to “skin”
2. “itching”, “swelling” and “rashes” connecting to both “facial skin” and “neck”
Both of them are not correct either. This relationship is misleading. 

Example  2:
Text : The consumer experienced small blisters on hands, redness and itching on body and neck itching after using the product

Output:
The det consumer nsubj
consumer nsubj experienced ROOT
experienced ROOT experienced ROOT
small amod blisters dobj
blisters dobj experienced ROOT
on prep experienced ROOT
hands pobj on prep
, punct hands pobj
redness conj hands pobj
and cc redness conj
itching conj redness conj
on prep itching conj
body pobj on prep
and cc body pobj
neck conj body pobj
itching advcl experienced ROOT
after prep itching advcl
using pcomp after prep
the det product dobj
product dobj using pcomp

In both cases it is difficult to navigate to get the correct relationship between medical conditions and affected sites. I will appreciate if you let us know how to address this issue.

**Comment by svlandeg** [comment]
That does sound like something strange is going on. Could you create a minimal working code snippet that replicates this behaviour? You could take for instance one example sentence from your dataset and have that hard-coded in the snippet, show the code you're using for training and prediction. This would help us try and pin down what could be going wrong.

It would also help if you could use some [formatting](https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax) in your post, because right now it's a little difficult to follow.
