### ISSUE TITLE
💫 Document workflow: Using the dependency parse / dependency parsing

### ISSUE THREAD

**Issue by ines** [explosion/spaCy#555]
We're [reorganising and improving the docs and tutorials](https://github.com/explosion/spaCy/projects/2). The new docs will separate task-oriented workflows from the basic API reference. This issue is the one to follow to stay in the loop about this topic – closing the related issues to keep the discussion in one place.

Addresses: #233, #271, #259, #409, #482, #512, #517, #523, #438

**Comment by honnibal** [comment]
```python

doc.sents
doc.noun_chunks

token.head
token.dep
token.dep_
token.lefts
token.rights
token.n_lefts
token.n_rights
token.children
token.subtree
token.conjuncts

parser.step_through()
```

# Annotation scheme
