### ISSUE TITLE
Wrong sentence boundary detection in blanc models for '\n' or '\n\n' 

### ISSUE THREAD

**Issue by d5555** [explosion/spaCy#5550]
blanc models don't assign correctly `.is_sent_start` for tokens like '\n' or '\n\n'.
Instead of putting them to the end of sentence they always got **is_sent_start == True**  to start a following sentence.

```
from spacy.lang.en import English
nlp = English()
sentencizer = nlp.create_pipe("sentencizer")
nlp.add_pipe(sentencizer)
doc=nlp("""The announcement of the decision will be made at the White House in the next few weeks, the report said.

The White House did not immediately respond to a request for comment.

"We cannot comment on information that is market-moving," a U.S. Department of Health and Human Services official said.""")
for token in doc:
	print(repr(token.text), token.is_sent_start)
```
'The' True
'announcement' False
'of' False
'the' False
'decision' False
'will' False
'be' False
'made' False
'at' False
'the' False
'White' False
'House' False
'in' False
'the' False
'next' False
'few' False
'weeks' False
',' False
'the' False
'report' False
'said' False
'.' False
**'\n\n' True**
'The' False
'White' False
'House' False
'did' False
'not' False
'immediately' False
'respond' False
'to' False
'a' False
'request' False
'for' False
'comment' False
'.' False
**'\n\n' True**
'"' False
'We' False
'can' False
'not' False
'comment' False
'on' False
'information' False
'that' False
'is' False
'market' False
'-' False
'moving' False
',' False
'"' False
'a' False
'U.S.' False
'Department' False
'of' False
'Health' False
'and' False
'Human' False
'Services' False
'official' False
'said' False
'.' False

## Your Environment
* **spaCy version:** 2.2.4
* **Platform:** Windows-10 
* **Python version:** 3.7.3

**Comment by adrianeboyd** [comment]
I don't think there's a clear right or wrong answer to whether whitespace belongs to the preceding or following sentence. The parser attaches space tokens to a preceding token so whitespace ends up grouped with the preceding sentence, which does mean the sentencizer behaves differently than the parser by default, and we could consider whether it makes sense to make the two components a bit more similar here. In any case, the behavior should be relatively easy to customize:

The `sentencizer` has a list of sentence-final tokens and looks for a sentence-final token followed by a non-sentence final token that's also not punctuation. Newlines aren't included by default in this list, but you can add them if you'd like them to be included in the previous sentence. To make it fast, there's no support for regexes, so you have to add `\n`, `\n\n`, `\n\n\n`, etc. for each possible whitespace token combination. The punctuation tokens are stored in a set and you can add additional punctuation like this after the component is added:

```
nlp.get_pipe("sentencizer").punct_chars.add("\n")
nlp.get_pipe("sentencizer").punct_chars.add("\n\n")
nlp.get_pipe("sentencizer").punct_chars.add("\n\n\n")
```

Another option would be to create a custom sentencizer derived from `Sentencizer` that just modifies `__call__` to check that the following token is not punctuation OR whitespace to get this behavior.

And if you need to support more complicated patterns, you may want to implement a custom sentence segmentation component instead. Here's an example: https://spacy.io/usage/processing-pipelines#component-example1

**Comment by svlandeg** [comment]
Yep, we will consider this for future enhancements. I think for now though, the workarounds described by Adriane should be sufficient. Thanks for the report!
