### ISSUE TITLE
In German model, lemma "mein" improper

### ISSUE THREAD

**Issue by LeoK987** [explosion/spaCy#5557]
All these words are stemmed as "mein":
'meines', 'eures', 'ihre', 'unsere', 'sein', 'ihres', 'deines', 'eure', 'seine', 'meinen', 'unserer', 'deine', 'eurem', 'unseren', 'dein', 'seinem', 'euren', 'meinem', 'deinen', 'unseres', 'deinem', 'seines', 'ihr', 'ihren', 'ihrem', 'unserem'

## How to reproduce the behaviour
nlp = spacy.load('de_core_news_sm')
doc = nlp("seine")
print(doc[0].lemma_)

## Info about spaCy

* **spaCy version:** 2.2.4
* **Platform:** Linux-5.4.0-33-generic-x86_64-with-Ubuntu-20.04-focal
* **Python version:** 3.7.7

**Comment by adrianeboyd** [comment]
Let's close this and merge it with #5556.
