### ISSUE TITLE
SpaCy Custom NER Model: Dependency Parser Training Error

### ISSUE THREAD

**Issue by saarthak99** [explosion/spaCy#5559]
Hello everyone,
I was trying to build a custom NER model using spacy. After building the model for entities, it was necessary to train the model for dependency parsers. 

I tried following the sample code provided on the Spacy website given below: [SpaCy Dependecy Parser Training](https://spacy.io/usage/training#tagger-parser)

The sample code for the training data given the SpaCy website is:
```
    TRAIN_DATA = [
    (
        "They trade mortgage-backed securities.",
        {
            "heads": [1, 1, 4, 4, 5, 1, 1],
            "deps": ["nsubj", "ROOT", "compound", "punct", "nmod", "dobj", "punct"],
        },
    )]
```
In this sample code, for the training data, there is a label called “heads”. I am not very particular on what it exactly is and what is its significance in the code.

I tried to run the model without the "heads" label in the training data.  A sample of my training data is:
`    TRAIN_PARSER = ('Mr Manjunath who is in-charge of the motor at their Goa location.', {'deps': ['compound',    'ROOT',    'nsubj',    'relcl',    'prep',    'punct',    'pobj',    'prep',    'det',    'pobj',    'prep',    'poss', 'compound','pobj', 'punct']})`

When I try to run the model without the heads label and keeping the other part of the code same, I get the following error:
`IndexError: list index out of range`

Can someone please explain it to me, what the exact problem is over here and how can I solve it? Also, how can I generate the "heads" label for my training data?

**Comment by svlandeg** [comment]
The `heads` information is required to identify what the immediate 'parent' of a token is in the tree. For example, in 
```
"I like London and Berlin.",
        {
            "heads": [1, 1, 1, 2, 2, 1],
            "deps": ["nsubj", "ROOT", "dobj", "cc", "conj", "punct"],
        },
```
the word `I` has the head at index 1, i.e. the word `like`, and is connected to it with the dependency `nsubj`.

**Comment by svlandeg** [comment]
Closing in favour of following up on [Stackoverflow](https://stackoverflow.com/questions/62258260/spacy-custom-ner-model-dependency-parser-training-error/62263001#62263001).

**Comment by saarthak99** [comment]
@svlandeg How do I get the position values for these `heads` through the spacy library? What command should I be using?

**Comment by svlandeg** [comment]
The documentation I linked has more info on that: you can call `token.head`. Ofcourse when you're creating labeled training data, you'll need to somehow annotate the heads yourselves. For instance in (the upcoming version 1.10 of) our annotation tool Prodigy, this is done by drawing an arch between the token and its head:  https://support.prodi.gy/t/beta-testers-wanted-new-manual-dependencies-relations-ui-v1-10/2893
