### ISSUE TITLE
💫 Document workflow: Customising the tokenizer

### ISSUE THREAD

**Issue by ines** [explosion/spaCy#557]
We're [reorganising and improving the docs and tutorials](https://github.com/explosion/spaCy/projects/2). The new docs will separate task-oriented workflows from the basic API reference. This issue is the one to follow to stay in the loop about this topic – closing the related issues to keep the discussion in one place.

Addresses: #379, #225

**Comment by honnibal** [comment]
Done: https://spacy.io/docs/usage/customizing-tokenizer

Can always use more examples, iterations etc. But, closing this.
