### ISSUE TITLE
Spacy GPU support failing

### ISSUE THREAD

**Issue by anetschka** [explosion/spaCy#5576]
I fail to get GPU support with spacy. After getting error messages, I made sure to check my PyTorch version and that it uses the GPU. GPU is ok with both Keras and PyTorch. Cupy is installed and works correctly. 

However, from the error messages it seems that loading GPU support through PyTorch fails for spacy:

![image](https://user-images.githubusercontent.com/17731067/84374645-950d7d00-abde-11ea-95be-b0edf5e42d32.png)

![image](https://user-images.githubusercontent.com/17731067/84374595-80c98000-abde-11ea-89f2-8bc5cb6ce638.png)

Is there an environment variable that I need to set?

## Your Environment
* Operating System: Windows 10
* Python Version Used: 3.7.5
* spaCy Version Used: 2.2.4
* Environment Information: Cuda 10.1

**Comment by adrianeboyd** [comment]
Can you try this in a new virtual environment with only `spacy` and `cupy` installed and not `torch`?

The machine learning library behind spacy (`thinc`) does try to import torch if it's installed when you enable the GPU, but this is only needed in case you're using some experimental features not for any of the core library functionality or provided models.

I'm not sure what's causing the torch error, but you should have no problems using spacy on GPU without torch.

**Comment by anetschka** [comment]
Hi Adriane, thank you, but I can't confirm that this works. I tried installing spacy[cuda101] in a pipenv.

![image](https://user-images.githubusercontent.com/17731067/84388163-67cbc980-abf4-11ea-90ac-c2e92b67134b.png)

(The output printed is "False" for spacy.prefer_gpu() and the exception for spacy.require_gpu().)

Do I need to install another library beforehand?

Cheers,
Anne

**Comment by anetschka** [comment]
Ok, added cupy and it works. Thanks, @adrianeboyd !
