### ISSUE TITLE
Installing spacy[cuda] via pip on AWS SageMaker extremely slow (~1hr+)

### ISSUE THREAD

**Issue by mgbvox** [explosion/spaCy#5579]
## How to reproduce the problem

I'm running a standard-issue AWS p2.xlarge SageMaker Jupyter Lab notebook instance. To replicate: either via in-lab terminal or from a notebook, run:
`source activate pytorch_p36 # this only on terminal`
`!pip install -U spacy[cuda]`

The installation proceeds and completes as necessary; however, the **cupy** wheels building step appears to hang for at least one hour (or at least, outputs no progress report beyond `Building wheels for collected packages: cupy`
`  Running setup.py bdist_wheel for cupy ...`). I haven't been able to stick around long enough to see it complete; typically, I go walk my dog, and by the time I return, I still have time to make lunch before the installation finishes. The process is similarly slow - and sticks in the same spot, e.g. cupy wheels building - on google colab.

I attempted to include a spacy[cuda] install in the Life Cycle config for my notebook, but then startup fails after a very long wait period.

```bash
No Error - just SLOW.
```

## Your Environment

* Operating System: AWS Linux-4.14.171-105.231.amzn1.x86_64-x86_64-with-glibc2.9
* Python Version Used: 3.6.5
* spaCy Version Used: 2.2.4
* Environment Information: The environment pip freeze and conda env (as .yaml) are pasted below. 

## Info about spaCy

* **spaCy version:** 2.2.4
* **Platform:** Linux-4.14.171-105.231.amzn1.x86_64-x86_64-with-glibc2.9
* **Python version:** 3.6.5

## pip freeze:
alabaster==0.7.10
anaconda-client==1.6.14
anaconda-project==0.8.2
asn1crypto==0.24.0
astroid==1.6.3
astropy==3.0.2
attrs==18.1.0
autovizwidget==0.15.0
awscli==1.18.39
Babel==2.5.3
backcall==0.1.0
backports.shutil-get-terminal-size==1.0.0
bcrypt==3.1.7
beautifulsoup4==4.6.0
bitarray==0.8.1
bkcharts==0.2
blaze==0.11.3
bleach==2.1.3
blis==0.2.4
bokeh==1.0.4
boto==2.48.0
boto3==1.12.39
botocore==1.15.39
Bottleneck==1.2.1
cached-property==1.5.1
certifi==2019.11.28
cffi==1.11.5
chardet==3.0.4
click==6.7
cloudpickle==0.5.3
clyent==1.2.2
colorama==0.3.9
contextlib2==0.5.5
cryptography==2.9
cycler==0.10.0
cymem==2.0.2
Cython==0.28.2
cytoolz==0.9.0.1
dask==0.17.5
dataclasses==0.6
datashape==0.5.4
decorator==4.3.0
defusedxml==0.6.0
distributed==1.21.8
docker==4.2.0
docker-compose==1.25.5
dockerpty==0.4.1
docopt==0.6.2
docutils==0.14
entrypoints==0.2.3
enum34==1.1.9
environment-kernels==1.1.1
et-xmlfile==1.0.1
fastai==1.0.60
fastcache==1.0.2
fastprogress==0.2.2
filelock==3.0.4
Flask==1.0.2
Flask-Cors==3.0.4
gevent==1.3.0
glob2==0.6
gmpy2==2.0.8
greenlet==0.4.13
h5py==2.8.0
hdijupyterutils==0.15.0
heapdict==1.0.0
html5lib==1.0.1
idna==2.6
imageio==2.3.0
imagesize==1.0.0
importlib-metadata==1.5.0
ipykernel==4.8.2
ipyparallel==6.2.2
ipython==6.4.0
ipython-genutils==0.2.0
ipywidgets==7.4.0
isort==4.3.4
itsdangerous==0.24
jdcal==1.4
jedi==0.12.0
Jinja2==2.10
jmespath==0.9.4
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
jupyterlab==0.32.1
jupyterlab-launcher==0.10.5
kiwisolver==1.0.1
lazy-object-proxy==1.3.1
llvmlite==0.23.1
locket==0.2.0
lxml==4.2.1
MarkupSafe==1.0
matplotlib==3.0.3
mccabe==0.6.1
mistune==0.8.3
mkl-fft==1.0.6
mkl-random==1.0.1
mock==4.0.1
more-itertools==4.1.0
mpmath==1.0.0
msgpack==0.6.0
msgpack-python==0.5.6
multipledispatch==0.5.0
murmurhash==1.0.2
nb-conda==2.2.1
nb-conda-kernels==2.2.2
nbconvert==5.4.1
nbformat==4.4.0
networkx==2.1
nltk==3.3
nose==1.3.7
notebook==5.5.0
numba==0.38.0
numexpr==2.6.5
numpy==1.15.4
numpydoc==0.8.0
odo==0.5.1
olefile==0.45.1
onnx==1.5.0
opencv-python==4.1.1.26
openpyxl==2.5.3
packaging==20.1
pandas==0.24.2
pandocfilters==1.4.2
paramiko==2.7.1
parso==0.2.0
partd==0.3.8
path.py==11.0.1
pathlib2==2.3.2
patsy==0.5.0
pep8==1.7.1
pexpect==4.5.0
pickleshare==0.7.4
Pillow==5.4.1
pkginfo==1.4.2
plac==0.9.6
plotly==4.5.2
pluggy==0.6.0
ply==3.11
preshed==2.0.1
prompt-toolkit==1.0.15
protobuf==3.5.2
protobuf3-to-dict==0.1.5
psutil==5.4.5
psycopg2==2.7.5
ptyprocess==0.5.2
py==1.5.3
py4j==0.10.7
pyasn1==0.4.8
pycodestyle==2.4.0
pycosat==0.6.3
pycparser==2.18
pycrypto==2.6.1
pycurl==7.43.0.1
pyflakes==1.6.0
pygal==2.4.0
Pygments==2.2.0
pykerberos==1.2.1
pylint==1.8.4
PyNaCl==1.3.0
pyodbc==4.0.23
pyOpenSSL==18.0.0
pyparsing==2.2.0
PySocks==1.6.8
pyspark==2.3.4
pytest==3.5.1
pytest-arraydiff==0.2
pytest-astropy==0.3.0
pytest-doctestplus==0.1.3
pytest-openfiles==0.3.0
pytest-remotedata==0.2.1
python-dateutil==2.7.3
pytz==2018.4
PyWavelets==0.5.2
PyYAML==5.3.1
pyzmq==17.0.0
QtAwesome==0.4.4
qtconsole==4.3.1
QtPy==1.4.1
requests==2.20.0
requests-kerberos==0.12.0
retrying==1.3.3
rope==0.10.7
rsa==3.4.2
ruamel-yaml==0.15.35
s3fs==0.1.5
s3transfer==0.3.3
sagemaker==1.55.3
sagemaker-pyspark==1.3.0
scikit-image==0.13.1
scikit-learn==0.20.3
scipy==1.1.0
seaborn==0.8.1
Send2Trash==1.5.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
smdebug-rulesconfig==0.1.2
snowballstemmer==1.2.1
sortedcollections==0.6.1
sortedcontainers==1.5.10
spacy==2.1.8
sparkmagic==0.12.5
Sphinx==1.7.4
sphinxcontrib-websupport==1.0.1
spyder==3.2.8
SQLAlchemy==1.2.11
srsly==0.1.0
statsmodels==0.9.0
sympy==1.1.1
tables==3.4.3
TBB==0.1
tblib==1.3.2
terminado==0.8.1
testpath==0.3.1
texttable==1.6.2
thinc==7.0.8
toolz==0.9.0
torch==1.4.0
torchvision==0.5.0
tornado==5.0.2
tqdm==4.42.1
traitlets==4.3.2
typing==3.6.4
typing-extensions==3.7.4.1
unicodecsv==0.14.1
urllib3==1.23
wasabi==0.2.2
wcwidth==0.1.7
webencodings==0.5.1
websocket-client==0.57.0
Werkzeug==0.14.1
widgetsnbextension==3.4.2
wrapt==1.10.11
xlrd==1.1.0
XlsxWriter==1.0.4
xlwt==1.3.0
zict==0.1.3
zipp==3.0.0

## Conda YAML (**exported after install**):
name: pytorch_p36
channels:
  - pytorch
  - conda-forge
  - fastai
  - defaults
dependencies:
  - libgfortran=3.0.0=1
  - mpi=1.0=openmpi
  - openmpi=3.1.0=h26a2512_3
  - _libgcc_mutex=0.1=main
  - alabaster=0.7.10=py36h306e16b_0
  - anaconda-client=1.6.14=py36_0
  - anaconda-project=0.8.2=py36h44fb852_0
  - asn1crypto=0.24.0=py36_0
  - astroid=1.6.3=py36_0
  - astropy=3.0.2=py36h3010b51_1
  - attrs=18.1.0=py36_0
  - babel=2.5.3=py36_0
  - backcall=0.1.0=py36_0
  - backports=1.0=py36hfa02d7e_1
  - backports.shutil_get_terminal_size=1.0.0=py36hfea85ff_2
  - beautifulsoup4=4.6.0=py36h49b8c8c_1
  - bitarray=0.8.1=py36h14c3975_1
  - bkcharts=0.2=py36h735825a_0
  - blas=1.0=mkl
  - blaze=0.11.3=py36h4e06776_0
  - bleach=2.1.3=py36_0
  - blosc=1.14.3=hdbcaa40_0
  - bokeh=0.12.16=py36_0
  - boto=2.48.0=py36h6e4cd66_1
  - boto3=1.12.0=py_0
  - botocore=1.15.0=py_0
  - bottleneck=1.2.1=py36haac1ea0_0
  - bzip2=1.0.6=h14c3975_5
  - ca-certificates=2020.1.1=0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.11.28=py36_0
  - cffi=1.11.5=py36h9745a5d_0
  - chardet=3.0.4=py36h0f667ec_1
  - click=6.7=py36h5253387_0
  - cloudpickle=0.5.3=py36_0
  - clyent=1.2.2=py36h7e57e65_1
  - colorama=0.3.9=py36h489cec4_0
  - contextlib2=0.5.5=py36h6c84a62_0
  - cryptography=2.2.2=py36h14c3975_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - curl=7.60.0=h84994c4_0
  - cycler=0.10.0=py36h93f1223_0
  - cython=0.28.2=py36h14c3975_0
  - cytoolz=0.9.0.1=py36h14c3975_0
  - dask=0.17.5=py36_0
  - dask-core=0.17.5=py36_0
  - datashape=0.5.4=py36h3ad6b5c_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py36_0
  - defusedxml=0.6.0=py_0
  - distributed=1.21.8=py36_0
  - docutils=0.14=py36hb0f60f5_0
  - entrypoints=0.2.3=py36h1aec115_2
  - et_xmlfile=1.0.1=py36hd6bccc3_0
  - expat=2.2.5=he0dffb1_0
  - fastcache=1.0.2=py36h14c3975_2
  - filelock=3.0.4=py36_0
  - flask=1.0.2=py36_1
  - flask-cors=3.0.4=py36_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - get_terminal_size=1.0.0=haa9412d_0
  - gevent=1.3.0=py36h14c3975_0
  - glib=2.56.1=h000015b_0
  - glob2=0.6=py36he249c77_0
  - gmp=6.1.2=h6c8ec71_1
  - gmpy2=2.0.8=py36hc8893dd_2
  - graphite2=1.3.11=h16798f4_2
  - graphviz=2.40.1=h21bd128_2
  - greenlet=0.4.13=py36h14c3975_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.8.0=py36h989c5e5_3
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - heapdict=1.0.0=py36_2
  - html5lib=1.0.1=py36h2f9c1c0_0
  - icu=58.2=h9c2bf20_1
  - idna=2.6=py36h82fb2a8_1
  - imageio=2.3.0=py36_0
  - imagesize=1.0.0=py36_0
  - intel-openmp=2018.0.0=8
  - ipykernel=4.8.2=py36_0
  - ipython=6.4.0=py36_0
  - ipython_genutils=0.2.0=py36hb52b0d5_0
  - ipywidgets=7.2.1=py36_0
  - isort=4.3.4=py36_0
  - itsdangerous=0.24=py36h93cc618_1
  - jbig=2.1=hdba287a_0
  - jdcal=1.4=py36_0
  - jedi=0.12.0=py36_1
  - jinja2=2.10=py36ha16c418_0
  - jmespath=0.9.4=py_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py36h006f8b5_0
  - jupyter=1.0.0=py36_4
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=5.2.0=py36he59e554_1
  - jupyter_core=4.4.0=py36h7c827e3_0
  - jupyterlab=0.32.1=py36_0
  - jupyterlab_launcher=0.10.5=py36_0
  - kiwisolver=1.0.1=py36h764f252_0
  - krb5=1.14.2=hcdc1b81_6
  - lazy-object-proxy=1.3.1=py36h10fcdad_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libcurl=7.60.0=h1ad7b7a_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libssh2=1.8.0=h9cfc8f7_4
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.9=he85c1e1_1
  - libtool=2.4.6=h544aabb_3
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - libxslt=1.1.32=h1312cb7_0
  - llvmlite=0.23.1=py36hdbcaa40_0
  - locket=0.2.0=py36h787c0ad_1
  - lxml=4.2.1=py36h23eabaa_0
  - lzo=2.10=h49e0be7_2
  - markupsafe=1.0=py36hd9260cd_1
  - matplotlib=3.0.3=py36h5429711_0
  - mccabe=0.6.1=py36h5ad9710_1
  - mistune=0.8.3=py36h14c3975_1
  - mkl=2018.0.3=1
  - mkl-service=1.1.2=py36h17a0993_4
  - mkl_fft=1.0.6=py36h7dd41cf_0
  - mkl_random=1.0.1=py36h629b387_0
  - more-itertools=4.1.0=py36_0
  - mpc=1.0.3=hec55b23_5
  - mpfr=3.1.5=h11a74b3_2
  - mpmath=1.0.0=py36hfeacd6b_2
  - msgpack-python=0.5.6=py36h6bb024c_0
  - multipledispatch=0.5.0=py36_0
  - murmurhash=1.0.2=py36he6710b0_0
  - nb_conda=2.2.1=py36_0
  - nb_conda_kernels=2.2.2=py36_0
  - nbconvert=5.4.1=py36_3
  - nbformat=4.4.0=py36h31c9010_0
  - ncurses=6.1=hf484d3e_0
  - networkx=2.1=py36_0
  - ninja=1.9.0=py36hfd86e86_0
  - nltk=3.3.0=py36_0
  - nose=1.3.7=py36hcdf7029_2
  - notebook=5.5.0=py36_0
  - numba=0.38.0=py36h637b7d7_0
  - numexpr=2.6.5=py36h7bf3b9c_0
  - numpy=1.15.4=py36h1d66e8a_0
  - numpy-base=1.15.4=py36h81de0dd_0
  - numpydoc=0.8.0=py36_0
  - odo=0.5.1=py36h90ed295_0
  - olefile=0.45.1=py36_0
  - openpyxl=2.5.3=py36_0
  - openssl=1.0.2u=h7b6447c_0
  - packaging=17.1=py36_0
  - pandas=0.24.2=py36he6710b0_0
  - pandoc=1.19.2.1=hea2e7c5_1
  - pandocfilters=1.4.2=py36ha6701b7_1
  - pango=1.42.3=h8589676_0
  - parso=0.2.0=py36_0
  - partd=0.3.8=py36h36fd896_0
  - patchelf=0.9=hf79760b_2
  - path.py=11.0.1=py36_0
  - pathlib2=2.3.2=py36_0
  - patsy=0.5.0=py36_0
  - pcre=8.42=h439df22_0
  - pep8=1.7.1=py36_0
  - pexpect=4.5.0=py36_0
  - pickleshare=0.7.4=py36h63277f8_0
  - pillow=5.4.1=py36h34e0f95_0
  - pip=10.0.1=py36_0
  - pixman=0.34.0=hceecf20_3
  - pkginfo=1.4.2=py36_1
  - plac=0.9.6=py36_0
  - pluggy=0.6.0=py36hb689045_0
  - ply=3.11=py36_0
  - preshed=2.0.1=py36he6710b0_0
  - prompt_toolkit=1.0.15=py36h17d85b1_0
  - psutil=5.4.5=py36h14c3975_0
  - ptyprocess=0.5.2=py36h69acd42_0
  - py=1.5.3=py36_0
  - pycodestyle=2.4.0=py36_0
  - pycosat=0.6.3=py36h0a5515d_0
  - pycparser=2.18=py36hf9f622e_1
  - pycrypto=2.6.1=py36h14c3975_8
  - pycurl=7.43.0.1=py36hb7f436b_0
  - pyflakes=1.6.0=py36h7bd6a15_0
  - pygments=2.2.0=py36h0d3125c_0
  - pykerberos=1.2.1=py36h14c3975_0
  - pylint=1.8.4=py36_0
  - pyodbc=4.0.23=py36hf484d3e_0
  - pyopenssl=18.0.0=py36_0
  - pyparsing=2.2.0=py36hee85983_1
  - pyqt=5.9.2=py36h751905a_0
  - pysocks=1.6.8=py36_0
  - pytables=3.4.3=py36h02b9ad4_2
  - pytest=3.5.1=py36_0
  - pytest-arraydiff=0.2=py36_0
  - pytest-astropy=0.3.0=py36_0
  - pytest-doctestplus=0.1.3=py36_0
  - pytest-openfiles=0.3.0=py36_0
  - pytest-remotedata=0.2.1=py36_0
  - python=3.6.5=hc3d631a_2
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.4=py36_0
  - pywavelets=0.5.2=py36he602eb0_0
  - pyyaml=3.12=py36hafb9ca4_1
  - pyzmq=17.0.0=py36h14c3975_0
  - qt=5.9.6=h52aff34_0
  - qtawesome=0.4.4=py36h609ed8c_0
  - qtconsole=4.3.1=py36h8f73b5b_0
  - qtpy=1.4.1=py36_0
  - readline=7.0=ha6073c6_4
  - requests=2.20.0=py36_0
  - rope=0.10.7=py36h147e2ec_0
  - ruamel_yaml=0.15.35=py36h14c3975_1
  - s3fs=0.1.5=py36_0
  - s3transfer=0.3.3=py36_0
  - scikit-image=0.13.1=py36h14c3975_1
  - scikit-learn=0.19.1=py36h7aa7ec6_0
  - scipy=1.1.0=py36hfc37229_0
  - seaborn=0.8.1=py36hfad7ec4_0
  - send2trash=1.5.0=py36_0
  - setuptools=39.1.0=py36_0
  - simplegeneric=0.8.1=py36_2
  - singledispatch=3.4.0.3=py36h7a266c3_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.11.0=py36h372c433_1
  - snappy=1.1.7=hbae5bb6_3
  - snowballstemmer=1.2.1=py36h6febd40_0
  - sortedcollections=0.6.1=py36_0
  - sortedcontainers=1.5.10=py36_0
  - sphinx=1.7.4=py36_0
  - sphinxcontrib=1.0=py36h6d0f590_1
  - sphinxcontrib-websupport=1.0.1=py36hb5cb234_1
  - spyder=3.2.8=py36_0
  - sqlalchemy=1.2.7=py36h6b74fdf_0
  - sqlite=3.23.1=he433501_0
  - statsmodels=0.9.0=py36h3010b51_0
  - sympy=1.1.1=py36hc6d1c1c_0
  - tbb=2018.0.4=h6bb024c_1
  - tbb4py=2018.0.4=py36h6bb024c_1
  - tblib=1.3.2=py36h34cf8b6_0
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36h8cadb63_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.9.0=py36_0
  - tornado=5.0.2=py36_0
  - tqdm=4.42.1=py_0
  - traitlets=4.3.2=py36h674d592_0
  - typing=3.6.4=py36_0
  - unicodecsv=0.14.1=py36ha668878_0
  - unixodbc=2.3.6=h1bed415_0
  - urllib3=1.23=py36_0
  - wcwidth=0.1.7=py36hdf4376a_0
  - webencodings=0.5.1=py36h800622e_1
  - werkzeug=0.14.1=py36_0
  - wheel=0.31.1=py36_0
  - widgetsnbextension=3.2.1=py36_0
  - wrapt=1.10.11=py36h28b7045_0
  - xlrd=1.1.0=py36h1db9f0c_1
  - xlsxwriter=1.0.4=py36_0
  - xlwt=1.3.0=py36h7b00a1f_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.2.5=h439df22_0
  - zict=0.1.3=py36h3a3bf81_0
  - zlib=1.2.11=ha838bed_2
  - cymem=2.0.2=py36he1b5a44_0
  - cython-blis=0.2.4=py36h516909a_1
  - dataclasses=0.6=py_0
  - fastai=1.0.60=1
  - fastprogress=0.2.2=py_0
  - nvidia-ml-py3=7.352.0=py_0
  - spacy=2.1.8=py36hc9558a2_0
  - srsly=0.1.0=py36he1b5a44_0
  - thinc=7.0.8=py36hc9558a2_0
  - wasabi=0.2.2=py_0
  - pytorch=1.4.0=py3.6_cuda10.1.243_cudnn7.6.3_0
  - torchvision=0.5.0=py36_cu101
  - pip:
    - autovizwidget==0.15.0
    - awscli==1.18.39
    - bcrypt==3.1.7
    - blis==0.4.1
    - cached-property==1.5.1
    - catalogue==1.0.0
    - cupy==8.0.0b3
    - docker==4.2.0
    - docker-compose==1.25.5
    - dockerpty==0.4.1
    - docopt==0.6.2
    - enum34==1.1.9
    - environment-kernels==1.1.1
    - fastrlock==0.5
    - hdijupyterutils==0.15.0
    - importlib-metadata==1.5.0
    - ipyparallel==6.2.2
    - mock==4.0.1
    - msgpack==0.6.0
    - onnx==1.5.0
    - opencv-python==4.1.1.26
    - paramiko==2.7.1
    - plotly==4.5.2
    - protobuf==3.5.2
    - protobuf3-to-dict==0.1.5
    - psycopg2==2.7.5
    - py4j==0.10.7
    - pyasn1==0.4.8
    - pygal==2.4.0
    - pynacl==1.3.0
    - pyspark==2.3.4
    - requests-kerberos==0.12.0
    - retrying==1.3.3
    - rsa==3.4.2
    - sagemaker==1.55.3
    - sagemaker-pyspark==1.3.0
    - smdebug-rulesconfig==0.1.2
    - sparkmagic==0.12.5
    - tables==3.4.3
    - texttable==1.6.2
    - torch==1.4.0
    - typing-extensions==3.7.4.1
    - websocket-client==0.57.0
    - zipp==3.0.0
prefix: /home/ec2-user/anaconda3/envs/pytorch_p36

**Comment by mgbvox** [comment]
## NOTE:
nvcc --version gives 10.0. 
**However,** installing spacy[cuda100] and then: `import spacy` followed by `spacy.require_gpu()` throws: `ValueError: GPU is not accessible. Was the library installed correctly?`

**Comment by mgbvox** [comment]
## Further NOTE:
while nvcc --version does give, 10.0, `import torch` followed by `torch.version.cuda()` gives 10.1. Attempting `pip install -U spacy[cuda101]`gives the `does not provide the extra 'cuda101'` error.

**Comment by adrianeboyd** [comment]
I think you need to figure out which CUDA version is correct for your environment, since I'm not sure where the conflicting information is coming from. `cupy` doesn't depend on `torch`, so most likely `nvcc --version` is what you should rely on, but I'm not 100% sure about what's going on in your environment here.

But once you have the right CUDA version, it's usually easiest just to install the corresponding binary package for `cupy` by hand. The order of the installs doesn't matter, so you can install it before or after installing `spacy` and it'll be detected correctly when you enable the GPU in spacy.

```
pip install spacy
pip install cupy-cuda100
```

This should be equivalent to `pip install spacy[cuda100]`, but it might be easiest to figure out what's going on by running them separately.

It looks like the `cupy` package installs from source, which might be what is taking so long. I'd recommend the binary `cupy-cuda100` packages instead. Make sure that you clean up any lingering `cupy` packages in advance, since they conflict.

**Comment by mgbvox** [comment]
Thanks for your detailed response!

How would one get the cupy binaries? Is there a way to specify binaries using pip? Or would I need to download from the cupy website?

**Comment by adrianeboyd** [comment]
`cupy` is the source package, `cupy-cudaNNN` are the binary packages.
