### ISSUE TITLE
💫 Document workflow: Using word vectors and semantic similarities

### ISSUE THREAD

**Issue by ines** [explosion/spaCy#558]
We're [reorganising and improving the docs and tutorials](https://github.com/explosion/spaCy/projects/2). The new docs will separate task-oriented workflows from the basic API reference. This issue is the one to follow to stay in the loop about this topic – closing the related issues to keep the discussion in one place.

Addresses: #423, #197, #427

**Comment by honnibal** [comment]
```python

doc.vector
span.vector
token.vector
lexeme.vector

doc.similarity(other)
span.similarity(other)
token.similarity(other)
lexeme.similarity(other)

nlp.vocab.resize_vectors(new_size)
nlp.vocab.load_vectors(file_)
nlp.vocab.load_vectors_from_bin_loc(path)
```
