### ISSUE TITLE
Custom tokenizer token_match doesn't seem to take proper precedence [reopen #4645]

### ISSUE THREAD

**Issue by nikeqiang** [explosion/spaCy#5584]
## Feature description
Understand there was a design decision to have prefix/suffix matches take precedence over token_match.   As noted elsewhere (e.g. #4645), for users that rely heavily on token_match to customize their tokenizer (i.e. not just for URL-matches) this can be a significant breaking change making it difficult to transition to v2.2.  Noting there are pros and cons of having pre/suffix take precedence over token_match (and/or special cases, which seem to still take precedence over prefix/suffix),  would it be possible to let users decide the order in which the pre/suff-regexes, special  cases and token_match are applied in the tokenizer routine?  Based on the pseudo code, it seems like this could be a simple fix - i.e. having the token_match come before or after the second while-loop based on user preference.   As always, thanks so much for the amazing improvements that are continuously introduced to the spacy library.  Really fantastic!

**Comment by adrianeboyd** [comment]
Yeah, this change was a bad decision. It worked well for spaCy's internal use of `token_match` for URLs but not for many other uses. It will be reverted in v2.3.0, which should be released soon. There will then be `token_match` as in v2.2.1 and `url_match` for a match with precedence after prefixes and suffixes. If you'd like, you can currently test the dev release `spacy==2.3.0.dev1`.
