### ISSUE TITLE
No module named 'setuptools.build_meta'

### ISSUE THREAD

**Issue by hernandezurbina** [explosion/spaCy#5585]
I'm having problems installing spacy (2.2.4) via "pip install -U spacy" on a virtual environment running python 3.5. Error is "ImportError: No module named **'setuptools.build_meta'**"
I have version 47.1.1 of setuptools in the virtualenv, and 20.7 of python3-setuptools system-wide. My OS is Ubuntu 16.04.

**Comment by adrianeboyd** [comment]
This looks like a bug related to pip and setuptools. See: https://github.com/pypa/pip/issues/6264 and https://github.com/pypa/setuptools/issues/1694

I'm not sure what the easiest solution is here, to be honest. This comment contains a number of suggestions: https://github.com/pypa/setuptools/issues/1694#issuecomment-466010982

As far as I can tell, spacy should have the fix related to `pyproject.toml`, so I'm not sure why that isn't working as explained, but maybe one of the suggestions related to `--system-site-packages` would help?

**Comment by hernandezurbina** [comment]
Thank you. I successfully installed it on Python 3.6 :)

**Comment by adrianeboyd** [comment]
Glad to hear it's working!
