### ISSUE TITLE
spacy.cli.download

### ISSUE THREAD

**Issue by lixin6135** [explosion/spaCy#5587]
## How to reproduce the problem

For some reason, I can not use `python -m spacy download en` or pip, conda install etc. So I can only use `spacy.cli.download()`. And it reports as below, how do I set up the `--no-deps`?
```
import spacy.cli
import spacy
spacy.cli.download("en_core_web_sm",'--no-deps')


```

```bash
# copy-paste the error message here
⚠ Skipping model package dependencies and setting `--no-deps`. You
don't seem to have the spaCy package itself installed (maybe because you've
built from source?), so installing the model dependencies would cause spaCy to
be downloaded, which probably isn't what you want. If the model package has
other dependencies, you'll have to install them manually.
```

## Your Environment

* Operating System:CentOS
* Python Version Used:3.7
* spaCy Version Used:2.2.0.dev15
* Environment Information:

**Comment by adrianeboyd** [comment]
This is a warning that `--no-deps` has been set, not that it's missing. Is the model not downloaded and installed correctly by this step?

(Unless you have a particular reason for using an older dev version, we'd recommend the most recent v2.2 (v2.2.4) or at least a final release like v2.2.0.)

**Comment by lingvisa** [comment]
For the latest release, I installed Spacy from the source. When I run python -m spacy download en_core_web_sm, I got the warning message:

 ```
⚠ Skipping model package dependencies and setting `--no-deps`. You
don't seem to have the spaCy package itself installed (maybe because you've
built from source?), so installing the model dependencies would cause spaCy to
be downloaded, which probably isn't what you want. If the model package has
other dependencies, you'll have to install them manually.
```

The installation seems working file, despite this warning.

**Comment by lingvisa** [comment]
Also, when I install jieba, it reports this error message:
 pip install jieba
Processing /Users/congminmin/Library/Caches/pip/wheels/24/aa/17/5bc7c72e9a37990a9620cc3aad0acad1564dcff6dbc2359de3/jieba-0.42.1-py3-none-any.whl
ERROR: zh-core-web-sm 2.3.1 requires pkuseg>=0.0.22, which is not installed.
ERROR: zh-core-web-sm 2.3.1 requires spacy<2.4.0,>=2.3.0, which is not installed.

The fact is that spacy2.4.0 is already installed into a virtual environment from the source and I am working in this virtual environment.

**Comment by Tejas7-mac** [comment]
Skipping model package dependencies and setting `--no-deps`. You
don't seem to have the spaCy package itself installed (maybe because you've
built from source?), so installing the model dependencies would cause spaCy to
be downloaded, which probably isn't what you want. If the model package has
other dependencies, you'll have to install them manually.





i am getting this isuue i think beacuse of this while loading the 

nlp = spacy.load("en_core_web_sm")

i am getting the error as 


AttributeError: module 'en_core_web_sm' has no attribute 'load'
