### ISSUE TITLE
💫 Document workflow: Rule-based matching

### ISSUE THREAD

**Issue by ines** [explosion/spaCy#559]
We're [reorganising and improving the docs and tutorials](https://github.com/explosion/spaCy/projects/2). The new docs will separate task-oriented workflows from the basic API reference. This issue is the one to follow to stay in the loop about this topic – closing the related issues to keep the discussion in one place.

Addresses: #521

**Comment by honnibal** [comment]
# Rule Matcher

## Entities and patterns

```python

matcher.add_entity()
matcher.add_pattern()
matcher.add()
matcher = Matcher(vocab, patterns=patterns)

attrs = matcher.get_entity(entity_id)
matcher.has_entity(entity_id)
```

## Writing patterns

### Attributes

### Using quantifiers

## Acceptor functions

## Callback functions

**Comment by Murgates** [comment]
Can ENT_TYPE be used in patterns. For example if ENT_TYPE is PERSON and followed by a token LOWER of jr (junior )or sr (senior)

**Comment by hmngwy** [comment]
Yes. This worked for me as a pattern:

```
{LOWER:'to'},{ENT_TYPE:'GPE'}
```

You're gonna want to put a trimming mechanism on your on_match callback.
