### ISSUE TITLE
'spacy.syntax.nn_parser.array' has no attribute '__reduce_cython__'

### ISSUE THREAD

**Issue by khushhalm** [explosion/spaCy#5590]
It is similar to the following issues:  [#5136](https://github.com/explosion/spaCy/issues/5136) [#4571](https://github.com/explosion/spaCy/issues/4571) [#2883](https://github.com/explosion/spaCy/issues/2883)

## How to reproduce the behavior

Flask app deployed on AWS Elastic Beanstalk having spacy==2.2.3 and few other libraries including Cython==0.29.17

## Your Environment

* Operating System: Linux
* Python Version Used: 3.6
* spaCy Version Used: 2.2.3
* Environment Information: virtualenv

**Comment by adrianeboyd** [comment]
This can be due to files that weren't cleaned up properly by pip or conda when you upgraded spacy. Our best advice is to try uninstalling spacy completely before reinstalling a newer version, and if it still isn't working, try installing spacy in a brand new virtual environment.

**Comment by khushhalm** [comment]
I'm using Elastic Beanstalk, so with every deployment, the environment is refreshed. So I don't think that is the issue.

**Comment by adrianeboyd** [comment]
Hmm, I'm not sure what else might cause this error. What are the other libraries that are being installed along with spacy in your environment? Do any of them have spacy as a dependency?

**Comment by khushhalm** [comment]
No spacy is not a dependency of another package.

## My requirements.txt file is this:
```python
absl-py==0.4.0
aniso8601==8.0.0
APScheduler==3.6.3
asn1crypto==0.24.0
astor==0.7.1
awscli==1.15.59
backports.functools-lru-cache==1.6.1
bcrypt==3.1.7
beautifulsoup4==4.8.1
blessed==1.16.1
blis==0.2.2
boto==2.49.0
boto3==1.7.58
botocore==1.10.58
bz2file==0.98
cached-property==1.5.1
cement==2.8.2
certifi==2019.11.28
cffi==1.14.0
chardet==3.0.4
click==7.1.2
colorama==0.3.9
colorhash==1.0.2
configparser==5.0.0
cryptography==2.8
cymem==2.0.3
Cython==0.29.17
cytoolz==0.9.0.1
dill==0.2.8.2
docker==3.7.3
docker-compose==1.23.2
docker-pycreds==0.4.0
dockerpty==0.4.1
docopt==0.6.2
docutils==0.15.2
docx==0.2.4
elasticsearch==6.3.1
Flask==1.1.1
Flask-MonitoringDashboard==3.0.9
future==0.16.0
gast==0.2.0
gensim==3.8.1
googletrans==2.4.0
grpcio==1.14.1
gunicorn==19.9.0
h5py==2.8.0
html5lib==1.0.1
idna==2.7
importlib-metadata==1.6.1
indic-transliteration==1.8.9
inflect==3.0.2
itsdangerous==1.1.0
jellyfish==0.7.2
Jinja2==2.11.1
jmespath==0.9.4
joblib==0.15.1
jsonschema==2.6.0
lxml==4.4.2
Markdown==2.6.11
MarkupSafe==1.1.1
msgpack==0.5.6
msgpack-numpy==0.4.1
msgpack-python==0.5.6
murmurhash==1.0.2
nltk==3.5
normalizer==0.2.1
num2words==0.5.10
numpy==1.17.4
pandas==1.0.4
paramiko==2.7.1
pathlib==1.0.1
pathspec==0.5.9
pdfminer.six==20170720
Pillow==6.2.1
plac==0.9.6
preshed==2.0.1
protobuf==3.6.1
psutil==5.7.0
pyasn1==0.4.3
pycparser==2.19
pycryptodome==3.9.4
PyNaCl==1.4.0
pyOpenSSL==18.0.0
PyPDF2==1.26.0
python-dateutil==2.8.0
pytrends==4.7.3
pytz==2020.1
PyYAML==3.10
regex==2019.11.1
requests==2.20.1
requests-aws4auth==0.9
rsa==3.4.2
s3transfer==0.1.12
scipy==1.3.3
selenium==3.141.0
semantic-version==2.5.0
six==1.15.0
smart-open==1.9.0
soupsieve==2.0.1
spacy==2.1.3
splinter==0.11.0
SQLAlchemy==1.3.17
srsly==0.2.0
tabulate==0.7.5
termcolor==1.1.0
texttable==0.9.1
thinc==7.0.2
thinc-gpu-ops==0.0.4
toolz==0.9.0
tqdm==4.46.1
tzlocal==2.1
ujson==1.35
urllib3==1.24.3
wasabi==0.4.0
wcwidth==0.1.7
webencodings==0.5.1
websocket-client==0.56.0
Werkzeug==0.16.0
word2number==1.1
wrapt==1.12.1
zipp==3.1.0
```

**Comment by adrianeboyd** [comment]
Hmm, I'm confused about which version you're trying to install. The requirements list above specifies `spacy==2.1.3` and spacy's dependencies also have the right versions for 2.1.3, but in your initial message you say you're trying to install spacy 2.2.3?

**Comment by khushhalm** [comment]
I was trying to update the spacy, latest version was 2.2.3 which was having issue. So I reverted to 2.1.3 for the time being.

**Comment by svlandeg** [comment]
Hi @khushhalm, sorry for the late follow-up. It's always difficult to debug installation issues from a distance. Is this issue still occurring? Have you tried with the latest spaCy 2.3.2?
