### ISSUE TITLE
Dependency Parser ignoring Tokenizer exceptions.

### ISSUE THREAD

**Issue by theudas** [explosion/spaCy#5591]
## How to reproduce the behaviour
When abbreviations are added to the tokenizer exceptions, they are ignored by the dependency parser.

```
o_doc = nlp("differentialdiagnostisch Tumor links.")
for sent in o_doc.sents:
    print(sent)
```

differentialdiagnostisch Tumor links.

```
from spacy.attrs import ORTH, NORM, TAG
case = [{ORTH: "dd", NORM: "differentialdiagnostisch", TAG:"ADJD"}]
nlp.tokenizer.add_special_case("dd", case)

abb_doc = nlp("dd Tumor links.")

for sent in abb_doc.sents:
    print(sent)
```

dd
Tumor links.

Expected would be, that I get one sentence as well.

## Info about spaCy

* **spaCy version:** 2.3.0
* **Platform:** Windows-10-10.0.18362-SP0
* **Python version:** 3.7.4

**Comment by svlandeg** [comment]
I can't reproduce this - which `nlp` model are you using?

**Comment by theudas** [comment]
de_core_web_lg

**Comment by svlandeg** [comment]
Ok, thanks, that helps.

So to get the behaviour I think you want, you'd specifically need to change the `ORTH` of the Token, for the dependency parser to have access to it:

```
nlp = spacy.load("de_core_news_lg")
from spacy.attrs import ORTH, NORM, TAG

case = [{ORTH: "differentialdiagnostisch", NORM: "differentialdiagnostisch", TAG: "ADJD"}]
nlp.tokenizer.add_special_case("dd", case)

abb_doc = nlp("dd Tumor links.")

for sent in abb_doc.sents:
    print(sent)
```
gives
> differentialdiagnostisch Tumor links.

This does give just one sentence, because now "dd" is rewritten to "differentialdiagnostisch".

**Comment by adrianeboyd** [comment]
Rewriting `ORTH` with exceptions is a bad idea (it changes the whole underlying text) that shouldn't really be allowed (there will be checks preventing this in spacy v3).

I think the new `NORM` value is what is leading to differences in the parser output. I would expect the same parser output if you don't have `NORM` in the exception? Or are you using `NORM` for a custom pipeline component later?

**Comment by svlandeg** [comment]
I think the OP's point is that the parser **isn't** influenced by the new `NORM` value ?

Just running `doc = nlp("dd Tumor links.")` results in 2 sentences with `de_core_news_lg` - whether or not you add the abbreviation from the original post. But `doc = nlp("differentialdiagnostisch Tumor links.")` is just one sentence, so if I understand correctly, the question is how to get the parser to behave as if "dd" is "differentialdiagnostisch".

**Comment by adrianeboyd** [comment]
Ah, I misunderstood, sorry. (Still: it's a really bad idea to rewrite `ORTH`! Normalizing texts in preprocessing outside of spacy would be an alternative solution.)

I don't think the provided models (meant for newspaper text) are a good match for this task.

**Comment by theudas** [comment]
Changing the ORTH is not possible since the input and outputs of the text need to be identical.
I guess capitalization is important to the Parser, which is why it cannot take the NORM?

We have a trained language model (Vectors and TAGs) but no dependency parsing, creating a huge corpus to train the parser on is not possible for us to do at this point. This is why I wanted to evaluate the new core_news_lg model.

**Comment by svlandeg** [comment]
That makes sense. Could you, like Adriane suggests, perform the abbreviation rewrite in pre-processing?

**Comment by adrianeboyd** [comment]
If the sentence boundaries are the problem, you can set individual tokens sentence starts (or not) with something like:

```
token.is_sent_start = True
token.is_sent_start = False
```

The parser will respect these settings and find a parse that fits as well as it can without adding new sentence boundaries. Maybe a custom sentence boundary component (you don't have to set all tokens, just the ones where you care that it is/isn't a boundary) would help?

You really need something like the German equivalent of scispacy, though. I'm not sure the parses are going to be of much help even if the sentence boundaries are correct, since the parser has never seen most of these kinds of tokens.

**Comment by theudas** [comment]
Thank you for the idea, I will try change my custom sentencizer to work like this.
The parser usually works good enough to work. Scispacy is awesome though. There are just not openly available texts in German like mimic or pubmed.
