### ISSUE TITLE
English POS Tagger incorrectly tags word into PUNCT

### ISSUE THREAD

**Issue by DGideas** [explosion/spaCy#5596]
## How to reproduce the behaviour
``` python
import spacy
nlp=spacy.load("en_core_web_md")
assert(nlp("back scatter")[1].pos_!="PUNCT")
```
What's wrong: The POS for scatter should definitely not be PUNCT

## Your Environment

* **spaCy version:** 2.2.4
* **Platform:** Linux-5.4.0-37-generic-x86_64-with-glibc2.29
* **Python version:** 3.8.2

**Comment by DGideas** [comment]
There is something wrong with the word `back`, for words like: `back home`, `back side`, `back to back`, `back off`, all of these POSes are WRONG!

**Comment by svlandeg** [comment]
POS tagging depends on having the context of a full sentence - giving the tagger just one or two tokens will typically result in non-sensical results:

```
nlp = spacy.load("en_core_web_md")
doc = nlp("back off")
print([(token.text, token.pos_) for token in doc])
```
Is not an actual sentence and results in 
> [('back', 'ADV'), ('off', 'ADV')]

However, using the phrase in a proper sentence:
```
nlp = spacy.load("en_core_web_md")
doc = nlp("You need to back off, buddy.")
print([(token.text, token.pos_) for token in doc])
```
yields
> [('You', 'PRON'), ('need', 'VERB'), ('to', 'PART'), **('back', 'VERB'), ('off', 'ADV')**, (',', 'PUNCT'), ('buddy', 'NOUN'), ('.', 'PUNCT')]

**Comment by DGideas** [comment]
@svlandeg We're trying to get the POS of every word in "English phrases" which are not full sentences, could you point us in a direction on how we could get them w/o full sentences? e.g. another framework?

**Comment by svlandeg** [comment]
Because of how POS taggers generally work, I personally think it's always going to be a challenge to get such results with high accuracy. But I guess you could try to [retrain](https://spacy.io/usage/training#example-train-tagger) the tagger on phrases only.
