### ISSUE TITLE
💫 Document workflow: Processing text

### ISSUE THREAD

**Issue by ines** [explosion/spaCy#560]
We're [reorganising and improving the docs and tutorials](https://github.com/explosion/spaCy/projects/2). The new docs will separate task-oriented workflows from the basic API reference. This issue is the one to follow to stay in the loop about this topic – closing the related issues to keep the discussion in one place.

Addresses: #550, #472, #549, #474

**Comment by honnibal** [comment]
# Processing a single text

# Processing a batch of texts with `.pipe()`

# Invoking the components individually
