### ISSUE TITLE
CONLL-U to doc

### ISSUE THREAD

**Issue by gakonorde** [explosion/spaCy#5600]
Is there an option to create doc container using an .conllu file?

There are ways to save doc as .conllu (spacy_conll). Could you advise how to do the opposite?

It seems that [doc](https://spacy.io/api/doc) can be created only from text string, list of words or saved doc. Probably, it's possible to [convert](https://spacy.io/api/cli#convert) .conllu to doc format somehow? 

Sorry, as far as I know, this issue was not raised for now...

## My Environment
* Operating System: Win64x
* Python Version Used: 3.7
* Environment Information: conda

**Comment by adrianeboyd** [comment]
There's not a direct built-in method, but spacy does this in its CoNLL-U converter in the `develop` branch (which will soon become spacy v3). The basics for the CoNLL-U lines for one sentence without any special handling of multi-word tokens:

```
import spacy
from spacy.tokens import Doc

# from UD-English_EWT
# sent_id = weblog-juancole.com_juancole_20051126063000_ENG_20051126_063000-0028
# text = This item is a small one and easily missed.

text = """1\tThis\tthis\tDET\tDT\tNumber=Sing|PronType=Dem\t2\tdet\t2:det\t_
2\titem\titem\tNOUN\tNN\tNumber=Sing\t6\tnsubj\t6:nsubj|9:nsubj\t_
3\tis\tbe\tAUX\tVBZ\tMood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin\t6\tcop\t6:cop\t_
4\ta\ta\tDET\tDT\tDefinite=Ind|PronType=Art\t6\tdet\t6:det\t_
5\tsmall\tsmall\tADJ\tJJ\tDegree=Pos\t6\tamod\t6:amod\t_
6\tone\tone\tNOUN\tNN\tNumber=Sing\t0\troot\t0:root\t_
7\tand\tand\tCCONJ\tCC\t_\t9\tcc\t9:cc\t_
8\teasily\teasily\tADV\tRB\t_\t9\tadvmod\t9:advmod\t_
9\tmissed\tmiss\tVERB\tVBN\tTense=Past|VerbForm=Part\t6\tconj\t6:conj:and\tSpaceAfter=No
10\t.\t.\tPUNCT\t.\t_\t6\tpunct\t6:punct\t_"""

def doc_from_conllu(vocab, lines):
    words, spaces, tags, poses, morphs, lemmas = [], [], [], [], [], []
    heads, deps = [], []
    for i in range(len(lines)):
        line = lines[i]
        parts = line.split("\t")
        id_, word, lemma, pos, tag, morph, head, dep, _1, misc = parts
        if "." in id_ or "-" in id_:
            continue
        if "SpaceAfter=No" in misc:
            spaces.append(False)
        else:
            spaces.append(True)

        id_ = int(id_) - 1
        head = (int(head) - 1) if head not in ("0", "_") else id_
        tag = pos if tag == "_" else tag
        morph = morph if morph != "_" else ""
        dep = "ROOT" if dep == "root" else dep

        words.append(word)
        lemmas.append(lemma)
        poses.append(pos)
        tags.append(tag)
        morphs.append(morph)
        heads.append(head)
        deps.append(dep)

    doc = Doc(vocab, words=words, spaces=spaces)
    for i in range(len(doc)):
        doc[i].tag_ = tags[i]
        doc[i].pos_ = poses[i]
        doc[i].dep_ = deps[i]
        doc[i].lemma_ = lemmas[i]
        doc[i].head = doc[heads[i]]
    doc.is_parsed = True
    doc.is_tagged = True

    return doc

nlp = spacy.blank("en")
doc = doc_from_conllu(nlp.vocab, text.split("\n"))
spacy.displacy.serve(doc, options={"collapse_punct": False})
```

`morphs` is read in but can't be set easily in v2, so it's skipped above. This will improve in v3.

This is simplified from the v3 CoNLL-U to JSON converter (relevant snippet below), which includes some additional handling of multi-word tokens (be aware that the`develop` API is still a bit unstable):

https://github.com/explosion/spaCy/blob/a1c5b694be117ac92e21f9860309821ad6da06f7/spacy/cli/converters/conllu2json.py#L179-L264

**Comment by gakonorde** [comment]
@adrianeboyd Thank you for your answer! I tried your solution, but it returns `Attribute Error`. Full traceback:

`Traceback (most recent call last):
  Python Shell, prompt 69, line 1
    # Used internally for debug sandbox under external interpreter
  File "C:\ProgramData\Miniconda3\Lib\site-packages\conllu_doc.py", line 35, in doc_from_conllu
    doc[i].pos_ = poses[i]
builtins.AttributeError: attribute 'pos_' of 'spacy.tokens.token.Token' objects is not writable
`
It happens both if I use your sample text and my data. Is there some way to handle it?

**Comment by adrianeboyd** [comment]
What version of spacy are you using? It should work with v2.1+, I think.

Otherwise you'll have to pick one of the XPOS/UPOS values to set for `token.tag_` and just be able to have one value here.

**Comment by gakonorde** [comment]
I'm using spacy 2.0.16. I attempted to upgrade it to [2.3.0](https://anaconda.org/conda-forge/spacy), but it seems that the newest version supported by Python 3.7 is 2.0.16. If I install spacy 2.3.0 from source, I get `ModuleNotFoundError: No module named 'spacy.pipeline.pipes'`. Well, thanks again!

**Comment by adrianeboyd** [comment]
You need to use `-c conda-forge` to get the newer versions with conda. v2.3.0 should be there as of yesterday. v2.0.16 is really quite old and we'd recommend upgrading!

**Comment by gakonorde** [comment]
Hmm, this is precisely what i did, but conda still installs v2.0.16:

![image](https://user-images.githubusercontent.com/58014330/85023254-0e8d0880-b1a7-11ea-8d52-767962ced82d.png)

In the [Meta](https://pypi.org/project/spacy/#files) section of the Pypi page of the v2.3.0 Python 3.7 is not mentioned, only Python !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, >=2.7.

I guess Python 3.7 is just not supported by spacy v2.3.0.

**Comment by adrianeboyd** [comment]
Hmm, we definitely support python 3.7, but only for 64-bit windows / OS X / linux. It looks like you might have a 32-bit windows system?

**Comment by gakonorde** [comment]
Nope, it's 64-bit. I installed 2.3.0 and 2.2.4 just through copying package files into the conda environment, but when trying to `import spacy` I get 

`Traceback (most recent call last):
  Python Shell, prompt 3, line 1
    # Used internally for debug sandbox under external interpreter
  File "C:\ProgramData\Miniconda3\Lib\site-packages\spacy\__init__.py", line 12, in <module>
    from . import pipeline
  File "C:\ProgramData\Miniconda3\Lib\site-packages\spacy\pipeline\__init__.py", line 4, in <module>
    from .pipes import Tagger, DependencyParser, EntityRecognizer, EntityLinker
builtins.ModuleNotFoundError: No module named 'spacy.pipeline.pipes'`

People usually [get ](https://stackoverflow.com/questions/58735715/getting-a-spacy-error-no-module-named-spacy-pipeline-pipes-spacy-pipeline)this error while using spacy, not while importing it... It's kinda puzzling: how can \\pipeline\\__init__.py refer to pipes with an error if it's within the same package?

**Comment by adrianeboyd** [comment]
I thinking copying package files is probably part of the problem, since you may have files from two versions that didn't get cleaned up correctly, which are causing this error. It should really be possible to install with either `conda` or `pip`.

Can you try installing from `conda-forge` in a new `conda` environment? As a backup option, you could also try installing using `pip` in the `conda` environment? In either case, be sure `conda` and `pip` don't see any previous `spacy` installations before starting. Double-check with `conda uninstall spacy` / `pip uninstall spacy`.

**Comment by gakonorde** [comment]
@adrianeboyd It was problem with my conda environment. I needed to delete it completely and use pip... Anyway, it all fine by now! Thank for your patience and explanations.

**Comment by gakonorde** [comment]
Hello again.

I modified the code a bit, so it can be used on the texts with multiple sentences:

```
import spacy
from spacy.tokens import Doc

def doc_from_conllu(vocab, raw_conllu):
    
    words, spaces, tags, poses, morphs, lemmas = [], [], [], [], [], []
    heads, deps = [], []
    
    lines = raw_conllu.split('\n')
    lines = [i for i in lines if len(i) is not 0 and not i.startswith('#') and i not in ['\r']]
    
    token_id = 0
    
    for i in range(len(lines)):
        line = lines[i]
        parts = line.split("\t")
        original_id, word, lemma, pos, tag, morph, head, dep, _1, misc = parts
        if "." in original_id or "-" in original_id:
            continue
        if "SpaceAfter=No" in misc:
            spaces.append(False)
        else:
            spaces.append(True)

        head = token_id + (int(head) - int(original_id))
        tag = pos if tag == "_" else tag
        morph = morph if morph != "_" else ""
        dep = "ROOT" if dep == "root" else dep

        words.append(word)
        lemmas.append(lemma)
        poses.append(pos)
        tags.append(tag)
        morphs.append(morph)
        heads.append(head)
        deps.append(dep)
        
        token_id += 1

    doc = Doc(vocab, words=words, spaces=spaces)
    
    for i in range(len(doc)):
        doc[i].tag_ = tags[i]          
        doc[i].pos_ = poses[i]
        doc[i].dep_ = deps[i]
        doc[i].lemma_ = lemmas[i]
        doc[i].head = doc[heads[i]]
    doc.is_parsed = True
    doc.is_tagged = True

    return doc
```

It works (it can read the dependencies etc. correctly), but creates doc objects consisting of a single sentence (which is wrong). Is there an option to make sentence splitting available?
