### ISSUE TITLE
conda installing version '2.2.4' while the Pypi has '2.30.'

### ISSUE THREAD

**Issue by j-a-h-i-r** [explosion/spaCy#5601]
## How to reproduce the problem

`conda install -c conda-forge spacy`
`python -m spacy info`
Version should be '2.3.0' but shows '2.2.4'

## Your Environment

* **spaCy version:** 2.2.4 (Should be 2.3.0?)
* **Platform:** Windows-10-10.0.18362-SP0
* **Python version:** 3.7.7

This issue is causing downloading newer models to fail (I was trying to download the danish models).

**Comment by adrianeboyd** [comment]
It takes us a bit to update the conda release after the pypi release is available. It should be available later today.

**Comment by j-a-h-i-r** [comment]
Thank you.

**Comment by adrianeboyd** [comment]
I think this should be available now. Reopen this and let us know if you run into any problems...

**Comment by j-a-h-i-r** [comment]
I just checked and it's getting the latest version. Thanks for the update.
