### ISSUE TITLE
Is it possible to support quantifier (n,m) for rule matching? 

### ISSUE THREAD

**Issue by lingvisa** [explosion/spaCy#5603]
```
! | Negate the pattern, by requiring it to match exactly 0 times.
-- | --
? | Make the pattern optional, by allowing it to match 0 or 1 times.
+ | Require the pattern to match 1 or more times.
* | Allow the pattern to match zero or mo
```
In addition to the operators above, is it possible to support the {n,m} quantifier in the rule matcher? Or least {n} times. The reason is that, for linear matching, there is often a need to restrict how far two tokens occur in a piece of text. The shorter the distance, the more reliable the pattern. For example:

```
pattern = [{"LOWER": "hello"},
           {"LOWER": "world"}] 
```
For this pattern, I want to add an additional condition to require that the two words 'hello' and 'world' will be within a distance of no more than 12 words. Is there a way to express this logic for the current matcher? If not, how likely this can be supported by introducing the RE quantifier {n,m}? This is very useful for pattern matching in practical applications.

**Comment by adrianeboyd** [comment]
If you have a simple pattern with one quantifier in the middle like  `A * B`, then we'd suggest using the `on_match` callback to filter matches based on length.

Since the `Matcher` doesn't support capturing groups, this is not going to help for more complicated patterns with multiple quantifiers, though.

**Comment by svlandeg** [comment]
Labeling this as "help wanted" - in case anyone is interested in implementing this feature, we'd accept a PR!

**Comment by delzac** [comment]
@lingvisa It it still matters to you, you can do it like so.

`
patterns = [TOKEN1] + [{"OP": "?"}] * num_of_padding + [TOKEN2]`

**Comment by ankh6** [comment]
Hi @svlandeg I'd like to make my first contribution here if it is still opened...
Have the requirements changed since Sep 22, 2020 ?
Can you redirect me to the relevant code section ?

**Comment by svlandeg** [comment]
Hi! The matcher code can be found here: https://github.com/explosion/spaCy/blob/master/spacy/matcher/matcher.pyx

**Comment by ankh6** [comment]
Thanks @svlandeg I am getting familiar with spacy codebase. I'll submit a PR as soon as possible
