### ISSUE TITLE
neuralcoref

### ISSUE THREAD

**Issue by snape6666** [explosion/spaCy#5605]
Hi,
we try to use neuralcoref but always get some errors while loading the model:
https://github.com/huggingface/neuralcoref/issues/260

Is there a way to check if the vectors are compatible with the current model?

Supplementary to this the question. Is it possible to use spacy 2.3.0 with neuralcoref? Did any of you already try that?

**Comment by svlandeg** [comment]
Have you tried installing both from source as explained in https://github.com/huggingface/neuralcoref/issues/197 ?

**Comment by svlandeg** [comment]
Closing here to follow up at huggingface/neuralcoref#260
