### ISSUE TITLE
sys.argv not present anytime

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [explosion/spaCy#5610]
## How to reproduce the behaviour
We are using Py03 rust binding, and in this case the python context does not defines the `argv` in `sys` module.
In the code on different points `sys.argv` is accessed without checking if it's exists.

Is it possible to fix that ?
We have a workaround with adding the definition of argv in the sys module.

## Your Environment
* **spaCy version:** 2.3.0
* **Platform:** Darwin-19.2.0-x86_64-i386-64bit
* **Python version:** 3.7.7

**Comment by adrianeboyd** [comment]
I don't think this is something we want to address for spacy v2, but I think the very recently proposed CLI updates may fix this issue #5626 for spacy v3.
