### ISSUE TITLE
💫 Document workflow: Adding a new language

### ISSUE THREAD

**Issue by ines** [explosion/spaCy#562]
We're [reorganising and improving the docs and tutorials](https://github.com/explosion/spaCy/projects/2). The new docs will separate task-oriented workflows from the basic API reference. This issue is the one to follow to stay in the loop about this topic – closing the related issues to keep the discussion in one place.

Addresses: #134, #158, #468, #470

**Comment by honnibal** [comment]
**Quick notes to self**

# Create Language subclass

See spacy/de/__init__,py for example.

# Create language data

See spacy/de/lang_data.py for example

# Defaults class

See spacy/language.py and spacy/de/__init__.py for examples.

# Create vocab data

* Prepare Wikipedia dump

See #[a(href="https://github.com/wikilinks/wikijson") here].

* Create frequencies

    $ python bin/get_freqs.py
    $ python bin/gather_freqs.py

* Brown clusters

See https://github.com/percyliang/brown-cluster

* Over-write attribute functions if necessary

Run `init_model.py`

# Customize Tokenizer

See customize tokenizer workflow.

# Customize Pipeline

See customize pipeline workflow.

# Train pipeline.

See training workfow.
