### ISSUE TITLE
unexpected "ill formed IOB input detected B"

### ISSUE THREAD

**Issue by dswah** [explosion/spaCy#5625]
## How to reproduce the behaviour
The `iob_to_biluo` function produces an unexpected ValueError when parsing a seemingly valid sentence.

Exception:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gold.pyx", line 611, in spacy.gold.iob_to_biluo
  File "gold.pyx", line 633, in spacy.gold._consume_ent
ValueError: [E177] Ill-formed IOB input detected: B
```
sample code:
```python
import spacy
from spacy.gold import iob_to_biluo
nlp = spacy.load("en_core_web_sm")
doc = nlp(u'My name is George, and I am an Englishman')
iobs = [i.ent_iob_ for i in doc]
iob_to_biluo(iobs)
```

## Your Environment

* **spaCy version:** 2.2.3
* **Platform:** Linux-4.15.0-1065-aws-x86_64-with-debian-buster-sid
* **Python version:** 3.6.6

**Comment by adrianeboyd** [comment]
`iob_to_biluo()` is expecting full IOB tags like `I-ENT` while `Token.ent_iob_` is only the IOB part, not the entity type part. You'd need to combine it with `Token.ent_type_` to get the full tag.

```
iobs = [i.ent_iob_ for i in doc]
assert iobs == ['O', 'O', 'O', 'B', 'O', 'O', 'O', 'O', 'O', 'O']
```

There's not a converter that does this directly from `doc.ents`, but if you want BILUO tags from a `Doc`, you can use:

```
biluo_tags = spacy.gold.biluo_tags_from_offsets(doc, [(ent.start_char, ent.end_char, ent.label_) for ent in doc.ents])
assert biluo_tags == ['O', 'O', 'O', 'U-PERSON', 'O', 'O', 'O', 'O', 'O', 'O']
```

**Comment by dswah** [comment]
Thanks for the help @adrianeboyd.

I'm not sure your reason is correct though, because adding a "surname" to George makes the code work:
```python
import spacy
from spacy.gold import iob_to_biluo
nlp = spacy.load("en_core_web_sm")
doc = nlp(u'My name is George Smith, and I am an Englishman')
iobs = [i.ent_iob_ for i in doc]
iob_to_biluo(iobs)
```

In fact it seems like the problem occurs whenever there is a `B` follwed by an `O`:
this works:
```
iob_to_biluo(['B', 'I'])
```
this doesn't 
```
iob_to_biluo(['B', 'O'])
```

**Comment by adrianeboyd** [comment]
The error-checking / validation for the input isn't as comprehensive as it could be here, but the main issue is that it's expecting input with entity labels like this:

```
assert iob_to_biluo(['B-PER', 'O', 'O']) == ['U-PER', 'O', 'O']
```

It's not intended to work with just the partial IOB parts of the tags.

**Comment by dswah** [comment]
ok thanks!
