### ISSUE TITLE
💫 Document workflow: Customising the pipeline

### ISSUE THREAD

**Issue by ines** [explosion/spaCy#563]
We're [reorganising and improving the docs and tutorials](https://github.com/explosion/spaCy/projects/2). The new docs will separate task-oriented workflows from the basic API reference. This issue is the one to follow to stay in the loop about this topic – closing the related issues to keep the discussion in one place.

Addresses: #235, #363, #432, #433, #453

**Comment by honnibal** [comment]
# Customizing the pipeline

spaCy provides several linguistic annotation functions by default. Each function takes a `Doc` object, and modifies it in-place. The default pipeline is `[nlp.tagger, nlp.entity, nlp.parser]`. spaCy 1.0 introduced the ability to customize this pipeline with arbitrary functions.

The easiest way to customize the pipeline is to pass a `create_pipeline` callback to the `spacy.load()` function:

```python

import spacy

import spacy

def arbitrary_fixup_rules(doc):
    for token in doc:
        if token.text == u'bill' and token.tag_ == u'NNP':
            token.tag_ = u'NN'

def custom_pipeline(nlp):
    return (nlp.tagger, arbitrary_fixup_rules, nlp.parser, nlp.entity)

nlp = spacy.load('en', create_pipeline=custom_pipeline)
```
