### ISSUE TITLE
spaCy 2.3.0 vocabulary size of en_core_web_lg too small

### ISSUE THREAD

**Issue by datanizing** [explosion/spaCy#5633]
Compared to spaCy 2.2 the vocabulary size is extremely small. Interestingly, "cat", "dog" and "banana" from the examples are still there.

Am I doing something wrong? Have the models changed?

Regards
Christian

## How to reproduce the behaviour

`pip install spacy==2.3.0`
`python -m spacy download en_core_web_lg`
`python3 -c "import spacy; nlp = spacy.load('en_core_web_lg'); print(len(nlp.vocab))"`
`478`

## Your Environment

* **spaCy version:** 2.3.0
* **Platform:** Linux-4.15.0-20-generic-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.6.9

**Comment by adrianeboyd** [comment]
There are two main differences, the first is the relevant one here:

* the vocab isn't prepopulated on loading (to improve loading times)
* the optional `prob` and `cluster` features aren't included as part of the model

You can see the number of unique vectors (`vectors`) and the number of words with vectors (`keys`) by looking at `nlp.meta['vectors']` (or `len(nlp.vocab.vectors)` and `nlp.vocab.vectors.n_keys`).

As you process texts, the lexemes you see will be added automatically, so you typically wouldn't need to worry about preloading anything. If you access a lexeme like `cat` with `nlp.vocab["cat"]` it will be added if necessary and you can see `len(nlp.vocab)` increase as you process texts or access lexemes.

If you do want to add lexemes for all the words with vectors, here's how:

```
for s in nlp.vocab.vectors:
    _ = nlp.vocab[s]
```

We should probably have a better way to do this optionally on loading for cases where it is needed. One example where you might need this is if you're doing similarity calculations across all the vectors and aren't processing texts directly.

I'll add more details to the migration guide (https://spacy.io/usage/v2-3) and see where this can be clarified better in the docs.

**Comment by datanizing** [comment]
Wow, thanks for this fast and complete answer, much appreciated. 

Actually, I wanted to use `anchor-exp` for explaining a model and this relies on `nlp.vocab`, but also on the scale `w.prob` which is set to -15 (fixed). Inserting your code and changing that to `-20` makes it work again.

Big THANKS. Will be part of our upcoming book.
