### ISSUE TITLE
CORS issue on Interactive matcher explorer

### ISSUE THREAD

**Issue by visini** [explosion/spaCy#5644]
## How to reproduce the behaviour
Since a few days, I'm running into a CORS issue while accessing the [interactive matcher explorer](https://explosion.ai/demos/matcher). The issue is persistent on any browser, device, OS, ...

Is this a known issue?

<img width="1242" alt="Screenshot 2020-06-25 09 34 07" src="https://user-images.githubusercontent.com/10230606/85676635-12e58400-b6c7-11ea-8d61-4805b596e3f0.png">

## Your Environment

* Operating System: MacOS, Windows
* Browser: Any

**Comment by svlandeg** [comment]
Thanks for the report, that does look like a bug! We'll look into it.

**Comment by visini** [comment]
> Thanks for the report, that does look like a bug! We'll look into it.

Thank you for your effort. This tool is incredibly useful for adjusting complex match patterns. 

Some follow up info: All demos on https://explosion.ai/software#demos seem to be affected. Accessing /*/models (e.g., https://api.explosion.ai/matcher/models) returns 502 Bad Gateway. 

Please don't hesitate to let me know what I can do to help in tracking down this issue. Cheers!

**Comment by eam17** [comment]
Having the same issue. 
Is there any way to use the demo meanwhile, maybe locally?

**Comment by eam17** [comment]
@visini is the code for the matcher on the GitHub too? I couldn't find it

**Comment by eam17** [comment]
@svlandeg is the code for the matcher on the GitHub too? I couldn't find it

**Comment by visini** [comment]
I don‘t believe the code for the matcher demo is open source... https://support.prodi.gy/t/rules-gui/2629/4

Any update on a fix, or some way to avoid this issue? Is only a portion of users affected?

**Comment by svlandeg** [comment]
We're working on a fix, and it's high up the priority list, but obviously not the only thing on that list ;-)
So please be patient and avoid pinging maintainers for known issues, as that makes our GH mentions hard to use.

Obviously as a "workaround", you can just run the matcher from code: https://spacy.io/usage/rule-based-matching

**Comment by visini** [comment]
I can confirm that the CORS issue is fixed as of today. Thank you very much for your effort!
