### ISSUE TITLE
es_core_web_lg spaCy v2.2.4 not found

### ISSUE THREAD

**Issue by p9ablo** [explosion/spaCy#5646]
## How to reproduce the behaviour

python -m spacy download es_core_web_lg
No compatible model found for 'es_core_web_lg' (spaCy v2.2.4).

## Info about spaCy

* **spaCy version:** 2.2.4
* **Platform:** Windows-10-10.0.18362-SP0
* **Python version:** 3.7.7

**Comment by adrianeboyd** [comment]
This model is new for spacy v2.3, so you need to upgrade spacy (the latest release is currently 2.3.0) to be able to use it.

**Comment by p9ablo** [comment]
Same result :S
No compatible model found for 'es_core_web_lg' (spaCy v2.3.0).

**Comment by adrianeboyd** [comment]
Sorry, didn't catch the model name typo. Glad to hear it's working!
