### ISSUE TITLE
sentences don't work

### ISSUE THREAD

**Issue by mikebenfield** [explosion/spaCy#565]
Possibly I am misunderstanding something, but it looks like the "sentences" spacy finds are just individual words.

```
In [1]: import spacy

In [2]: nlp = spacy.load('en')

In [3]: doc = nlp('Hello, world. Here is a second sentence.')

In [4]: sentence = next(doc.sents)

In [5]: sentence.text
Out[5]: 'Hello'
```

If I understand the documentation, this should be `'Hello, world.'`

**Comment by honnibal** [comment]
Hi,

Did you download and install the data?

**Comment by honnibal** [comment]
See issue #566.

**Comment by mikebenfield** [comment]
If downloading the data means doing `sudo python -m spacy.en.download all`, yes, I did.

**Comment by honnibal** [comment]
Hmm. Have a look within the package directory, and check that the data is actually there. `sudo` can be tricksy with Python, because it fiddles with your environment variables.
