### ISSUE TITLE
Model size in documentation vs. Memory usage when loading model

### ISSUE THREAD

**Issue by CharlesGaydon** [explosion/spaCy#5650]
This may be a quite naive question, but based on the documentation for [fr_core_news_md](https://spacy.io/models/fr#fr_core_news_md), I expected that the memory usage would be 43MB when loading the model _via_ `nlp = spacy.load("fr_core_news_md")`. Instead, I end up with a memory usage up to almost one Go, as reported by Windows task manager:

![image](https://user-images.githubusercontent.com/11660435/85781948-85398100-b726-11ea-958f-5a8e843b404e.png)

Does the documentation actually refers to a size of a compressed file, and does not inform on the memory usage of the model once loaded? Or am I totally wrong in my way of measuring memory usage?

On a related note: would there be a way to measure the actual memory used by the `nlp` object in my python terminal?

## Which page or section is this issue related to?

Source : https://spacy.io/models/fr#fr_core_news_md

**Comment by adrianeboyd** [comment]
The size in the model description is the size of the download for the compressed model package. It will be slightly larger when uncompressed and installed on disk, and the memory usage for whole python process (python + libraries + model) will be much higher.

For an example of how to measure the memory usage for the python process as a whole, there's a nice example in #4432.
