### ISSUE TITLE
Load English model error

### ISSUE THREAD

**Issue by mosesli** [explosion/spaCy#5651]
Hi,

      I have install spacy and the English support by:
             $pip install -U spacy
             $pip install /home/mosesli/Software/spacy/en_core_web_sm-2.3.0.tar.gz

      When I run:
             import spacy
             spacy.load("en_core_web_sm")
       the output is:
              <spacy.lang.en.English at 0x7f46f9940210>

        Howerver, when I run:
              import spacy
              spacy.load("en")

         the system complaint:
               OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

          The python version is 3.7.6 and the spacy version is 2.3.0. 

          Could you help me.
          Thanks in advance!

**Comment by svlandeg** [comment]
The installation of spaCy and the English model seems to have gone just fine. I would advise you to just keep using `spacy.load("en_core_web_sm")` - this way it's always clear which English model exactly you're using.

If you do want to have the option to specify `spacy.load("en")`, you can create a [symlink](https://spacy.io/usage/models#usage-link): 
```
python -m spacy link [package name or path] [shortcut]
```
See also the API documentation [here](https://spacy.io/api/cli#link). 

However, do note that using symlinks will not be supported anymore from spaCy version 3.0 onwards, so we don't really recommend it anymore.

**Comment by mosesli** [comment]
@svlandeg Thanks for your quick reply, it works.

Actually this error occurred at when I used torchtext:

from torchtext import data
TEXT = data.Field(tokenize="spacy")

which invoke:
        spacy.load("en")
not:
        spacy.load("en_core_web_sm")

**Comment by svlandeg** [comment]
Ah, gotcha. We used to rely a lot on these symlinks, and we'd also use them in the documentation. But like I said, we're trying to move away from this practice, and the packages in the spaCy universe will have to follow eventually. Which English model you want to use, should really be a parameter instead of some prefixed value.

Anyway, happy to hear the `link` command worked fine!
