### ISSUE TITLE
Token Matcher - Pattern Matching Order (Important when there is an overlap)  

### ISSUE THREAD

**Issue by sahinbatmaz** [explosion/spaCy#5655]
```
def my_callback(matcher, doc, i, matches):
    match_id, start, end = matches[i]
    string_id = matcher.vocab.strings[match_id]
    print(string_id)

matcher = Matcher(nlp.vocab)

matcher.add('custom', [[{"TEXT": "my"},  {"TEXT": "text"} ],],  my_callback)
matcher.add('temp', [[{"LOWER": {"REGEX": r"^.*?$"}}]],  my_callback)

doc = nlp("my text")
matches = matcher(doc)
```

The matcher object matches 'temp' even if the 'custom' is added before.
I changed the add order but still 'temp' pattern is matched first.

What can I do to apply patterns in an order?

**Comment by svlandeg** [comment]
I believe the matches are compiled in the order they are encountered in the text. The order of the different match rules doesn't matter, and the two different rules also don't interact with eachother. In your example, it looks like the `temp` rule matches every token as a separate ht, and the `custom` rule matches the two tokens "my text" as one hit. You can see this better if you test with a slightly longer text.

In post-processing, you can compare the different matches and for instance set `doc.ents` according to prioritization rules you can freely implement: e.g. if spans from both rules overlap, you could take the one from `custom` and ignore the overlapping ones from `temp`.

Does that help ?

**Comment by svlandeg** [comment]
FYI : there's a few different flavors of rule-based matching in spaCy, cf: https://spacy.io/usage/rule-based-matching. It really depends on your use-case/needs which one is more useful to you!

**Comment by sahinbatmaz** [comment]
I have read everything in https://spacy.io/usage/rule-based-matching . I think token matcher is the most flexible option.

I have tested the matcher in a long sentence. 

The order of different match rules does matter. spacy does not allow to add overlapping entities to doc.ents . Only one match for a token can be set in doc.ents . So if I add  the first match to doc.ents, I can not add the second because it will raise an error. Therefore I can not solve the problem in post-processing.  

How can I implement a prioritization ?

I think this operation should be handled in the callback but callback operation is applied one by one. 

As from my observation, the matcher iterates on each word, then length 1 patterns applied in add order, then length 2 patterns applied in add order and so on. My problem is I want to prioritize length 2 pattern `custom` before length 1 pattern `temp`. Do you have any idea to prioritize in this way?

(To do post processing, I can create a custom extension, add the matches and then apply a post processing prioritization. But I think there should be a smarter way.)

**Comment by sahinbatmaz** [comment]
As the solution, I have created different matchers to apply prioritization.

```
matcher1 = Matcher(nlp.vocab)
matcher1.add('custom', [[{"TEXT": "my"},  {"TEXT": "text"} ],],  my_callback)

matcher2 = Matcher(nlp.vocab)
matcher2.add('temp', [[{"LOWER": {"REGEX": r"^.*?$"}}]],  my_callback)

doc = nlp("my text")
matches = matcher1(doc)
matches = matcher2(doc)
```

**Comment by svlandeg** [comment]
Whatever works for you!
