### ISSUE TITLE
Named Entity Recognition mismatch

### ISSUE THREAD

**Issue by shivacharan-git** [explosion/spaCy#5659]
**spaCy** is currently classifying **Croatia** as an **Organization** (ORG) while it is actually a **Country** (GPE).
I know this doesn't work perfectly every time as It might change with context. 
But it would be better if the model gives factual data like country names correctly irrespective of the context.

## How to reproduce the behaviour

import spacy

nlp = spacy.load("en_core_web_sm")
doc = nlp("spaCy thinks Croatia is an organization but Croatia is a country")

for ent in doc.ents:
    print(ent.text, ent.label_)

![image](https://user-images.githubusercontent.com/64947329/85946608-2f9de800-b963-11ea-933b-483b64bff774.png)

## Your Environment
* Operating System:
* Python Version Used: Python 3
* spaCy Version Used: spaCy v2.3.0
* Environment Information:

**Comment by adrianeboyd** [comment]
If you have a list of country names (or similar lists for other entity types) that are correct for your task, then it's often helpful to combine the statistical NER model with a rule-based `EntityRuler` to handle cases like this more consistently.

Alternatively, you can update the NER model with more examples (be sure to annotate all entity types!) with the names from your task. See: https://spacy.io/usage/training#ner
