### ISSUE TITLE
`doc.noun_chunks` function CAN NOT deal with the symbol [ correctly in English

### ISSUE THREAD

**Issue by zhangjianzhang** [explosion/spaCy#5660]
## Code Example

```python
import spacy
nlp = spacy.load('en')

doc = nlp('Buying into the relationship [business software]')
for item in doc.noun_chunks:
  print(item)
```
## Wrong Result

```
the relationship
[business software
```

## Experiment Environment

* **spaCy version:** 2.2.4
* **Platform:** Linux-4.13.0-36-generic-x86_64-with-debian-stretch-sid
* **Python version:** 3.7.1
* **Models:** de, en

**Comment by adrianeboyd** [comment]
The noun chunks depend on the POS tags and the dependency parse, so it's not just an interaction with a particular kind of symbol. The dependency parse looks like this:

![bracket](https://user-images.githubusercontent.com/5794899/85989091-535b3f80-b9f0-11ea-9b93-d7a4a114d1d8.png)

The final bracket isn't attached correctly, but the rest of the parse looks plausible to me. It's probably the case that the brackets are throwing off the parser to some degree here, but to be fair to the parser, when I read this example I'm not even sure what the intended noun chunk(s) would be. 

Is `relationship [business software]` the intended noun chunk?
