### ISSUE TITLE
Past participle "Defaulted" is not picked up by lemma attribute

### ISSUE THREAD

**Issue by huisigoh** [explosion/spaCy#5689]
## How to reproduce the behaviour
```
import spacy
from spacy.matcher import Matcher

nlp = spacy.load('en_core_web_sm')
matcher = Matcher(nlp.vocab)

pattern = [
    [{
        'LEMMA': 'default'
    }]
]

[matcher.add('TERMS', None, p) for p in pattern]

textLine = nlp('waive or elect not to exercise remedies in respect of any default with respect to any defaulted security')
matches = matcher(textLine)

for match_id, start, end in matches:
    span = textLine[start:end]
    print(span.text)
```

**Expected results**: default, defaulted

**Results received**: default

## Your Environment

* Operating System: Win 10
* Python Version Used: 3.7.1
* spaCy Version Used: 2.2.3

**Comment by adrianeboyd** [comment]
The English rule-based lemmatizer uses the POS tags to decide whether to apply particular rules. There are a lot of cases where past participles and adjectives are difficult to distinguish. In this context the tagger has tagged `defaulted` as `ADJ`, so it doesn't apply the verb-related rules.

You could consider using the lookup lemmatizer instead, which will always return `default` for `defaulted` regardless of context. To do this, disable the `tagger` in the pipeline.

```
nlp = spacy.load("en_core_web_sm", disable=["tagger"])
```

Obviously this isn't a good idea if you need the POS tags for other processing. The pipeline currently tries to pick the best lemmatizer given the available components and unfortunately there aren't good settings for users to control this in a more fine-grained way.
