### ISSUE TITLE
Spacy 2.3 'with nlp.disable_pipes()' does not properly restore the pipes.

### ISSUE THREAD

**Issue by eaporetsky** [explosion/spaCy#5695]
## How to reproduce the behaviour
When I run the example https://spacy.io/usage/training/#example-train-ner with a pretrained model `en_core_web_md` the `with nlp.disable_pipes():` does not get properly closed and the saved model only has the `ner` component, not the tagger and parser. However if I do the normal disable flow without the context manager `disabled.restore()` it works fine.

Seems like a bug to me but wondering if others can reproduce.

## Your Environment

* **spaCy version:** 2.3.0
* **Platform:** Darwin-18.6.0-x86_64-i386-64bit
* **Python version:** 3.7.7

**Comment by adrianeboyd** [comment]
Thanks for the report! I screwed up the `with` syntax when I added the warnings filter. It should be fixed now in `master` by #5690, so if you look at the current version it should be correct: https://github.com/explosion/spaCy/blob/master/examples/training/train_ner.py

(Permalink: https://github.com/explosion/spaCy/blob/2bd78c39e33b90f788b1121b93b3b098c4c4af10/examples/training/train_ner.py)

**Comment by svlandeg** [comment]
Should be fixed so closing this - but do let us know if you still run into issues with the new version on `master` !

**Comment by eaporetsky** [comment]
Awesome - you guys are fast!
