### ISSUE TITLE
Documents meta data within the component life cycle

### ISSUE THREAD

**Issue by Getitdan** [explosion/spaCy#5698]
Apparently, components lack the possibility to act upon text meta data. I think a document, besides the words it consists of, might be highly influenced by its meta data too. It would be useful to be able to build component's logic based on meta data.

### When text meta data matters?

For instance, suppose we have news articles. Each article could have tags (politics, lifestyle, world, tech), publication date and titles.

A reasonable task would be to create a component that labels article entities based on the tags of the article. Entities like "core", "static", "local" and "dynamic" make more sense specifically for the "tech" tag, than to any other one.

Another component might find diseases mentioned in articles, and Coronavirus would make more sense to be found in articles with publication dates greater than March 2020 (prior to this date, any "Corona" has more changes to describe the beer).

In addition, article titles may also add some importance to their entities. 

All of the examples above use data that doesn't reside inside the text itself, hence the term meta data.

### What do we have?

Currently, there doesn't seem to be an easy way to get any meta data inside the components' workflow.

The closest to working with meta data we get, is the `context`, which we use with `nlp.pipe` when setting `as_tuples=True`. But this happens after all components have already finished their job, which forces us to either use code outside the components convention, or to manually call the components (without `nlp.add_pipe` and all the benefits of disabling pipes).

The argument `component_cfg` won't help us neither to pass data per each document. (Moreover, its terminology and usage are component oriented, while meta data should be document oriented).

### Solution

Please see [my fork](https://github.com/Getitdan/spaCy/tree/feature/text_meta) and [compare](https://github.com/explosion/spaCy/compare/master...Getitdan:feature/text_meta). The `text_meta` option in `nlp.pipe` assigns the meta data to the `Doc`, right before the components take place. That means, the components would be able to build logic based on the meta data.

_Example:_

```
import datetime

article1 = article2 = article3 = article4 = 'This is just a test article'
date1 = date2 = date3 = date4 = datetime.datetime(2020, 7, 2)

texts = [article1, article2, article3, article4]
texts_meta = [
    {'date': date1, 'tags': ['politics']},
    {'date': date2, 'tags': ['lifestyle']},
    {'date': date3, 'tags': ['world']},
    {'date': date4, 'tags': ['tech', 'hardware']}
]

for doc in nlp.pipe(texts, texts_meta=texts_meta):  # now components can access text meta data
    meta = doc.text_meta  # it's also possible to access text meta after the components' life cycle
```

### Side notes
- In my solution, I added `text_meta` property to the `Doc`. It is possible to leave the `Doc` untouched, while using the existing `user_data` property instead, but its usage wasn't clear to me, and there might be possible conflicts.
- I consider whether adding `user_` prefix like: `user_text_meta` might be better suited with the convention to denote that the user is in charge of the content of this property (and it is not being automatically populated by the library).
- Do you think `context` and `as_tuples` might be useless because of it, or do they still serve another goal?
- I'll be glad to hear your opinions, and whether I've missed something on the way.
- If it seems like a good idea, I will be honored to fine tune the code and make a pull request.

What do you think?

**Comment by svlandeg** [comment]
I may be missing something, but wouldn't this pretty much be the same functionality as currently offered by [extension attributes](https://spacy.io/usage/processing-pipelines#custom-components-attributes) ?

**Comment by Getitdan** [comment]
Hello @svlandeg, by the time we can use extension attributes, it is already too late. That means the `doc` has already been constructed, and the components' life cycle has already took place. Even if I created a components that is the first one, I couldn't get the meta data that is external to the text (and therefore couldn't set a new extension attribute). I'm talking especially of the `nlp.pipe` workflow.

Am I right? Please tell me if my intension is still not clear, and I'll be glad to show detailed examples.

**Comment by svlandeg** [comment]
Right, I get your point!

Sorry if I'm being annoying, just trying to figure out whether there's a way we could solve that use-case problem with the current implementation. We just want to avoid having overlapping functionality that could do the same thing, as then it gets confusing as to what should be used when.

So anyway I was thinking: What if you add a custom component to your pipeline, right at the start, which basically runs right after the tokenization. Let's call it `my_preproc`. This component would set the `Doc`'s meta data as custom attributes, and then all components further down the pipeline will be able to use that meta data as they please. `my_preproc` would get its information through `component_cfg` I guess? It feels a little like abusing the `component_cfg`, but I think it could work?

**Comment by Getitdan** [comment]
I totally agree with your view, it is better not to have overlaps.

Using `component_cfg` would successfully help when processing a single `Doc`, like that: `doc = nlp(text, component_cfg=text_meta)`. In this case we have no problems or limitations.

However, it won't help when processing multiple documents with `nlp.pipe`, because it will pass the _entire_ `texts_meta` to each `Doc`, regardless to what meta data each of them actually relates to.

So when we try to pass text meta (which is unique to each document) with the `component_cfg` option:

```
for doc in nlp.pipe(texts, component_cfg={'my_preproc': {'texts_meta': texts_meta}}):
    pass
```

We cannot get a specific `text_meta` per each `doc`, inside our component call:

```
@component("my_preproc")
class MyPreprocComponent:
    def __call__(self, doc, texts_meta):
        # every single doc gets the entire `texts_meta`, and we cannot know what to fit per each.
        # doc._.meta_data = ?
```

Do you see any possible way to pass data per each document?
Thanks a lot for your assistance.

**Comment by adrianeboyd** [comment]
If I can make a suggestion, I think what might work better is a custom tokenizer that creates a doc and adds metadata. Something like this:

```
import spacy
from spacy.tokens import Doc
from spacy.util import DummyTokenizer

class CustomTokenizer(DummyTokenizer):
    def __init__(self, vocab, tokenizer):
        self.vocab = vocab
        self.tokenizer = tokenizer

    def __call__(self, docinfo):
        text = docinfo["text"]
        meta = docinfo["meta"]
        doc = self.tokenizer(text)
        doc._.meta = meta
        return doc

nlp = spacy.blank("en")
nlp.tokenizer = CustomTokenizer(nlp.vocab, nlp.tokenizer)
Doc.set_extension("meta", default={})
doc = nlp({"text": "This is a sentence.", "meta": {"id": "id123", "author": "author456"}})
```

Serialization (saving with `nlp.to_disk` and reloading with `spacy.load`) is not going to work for this tokenizer yet, but it makes it possible to create the documents with metadata as part of a normal pipeline. The metadata should be accessible in the custom extension to any later components in the pipeline. It also shouldn't be a problem to use any existing components like the tagger in the same pipeline, since they'll just ignore the custom extension.

**Comment by Getitdan** [comment]
Hello @adrianeboyd, thank you for your response. It's clever, and makes the work done.

Wouldn't you see any benefit to include this meta behavior as an integrated part of the `language` class, like in my solution? Same to the `as_tuples`, and the new option I added: `use_tuples_as_texts_meta`. Just curious to hear your opinion. Thanks!

**Comment by svlandeg** [comment]
Merging with Issue #4160 which has related discussion!
