### ISSUE TITLE
training use cases with BERT model

### ISSUE THREAD

**Issue by SumeetSandhu** [explosion/spaCy#5712]
This is a question not an issue - will spacy 3.0 include documentation for how to train different use cases on top of BERT models? e.g. these or more https://huggingface.co/transformers/examples.html 

If so, what is the ETA for spacy 3.0 :)

**Comment by svlandeg** [comment]
Yes :-)

spaCy v.3 will introduce a lot of new functionality and we've been working hard on it. It's difficult to pin a specific release date on it, but stay tuned ;-)
