### ISSUE TITLE
Probelm in installing en_core_web_sm on Heroku

### ISSUE THREAD

**Issue by aryanc55** [explosion/spaCy#5713]
I am having a problem in importing en_core_web_sm on Heroku, while the code works fine on the local machine it is not able to do so on the Heroku server.

```
import spacy
from spacy import displacy
import en_core_web_sm
from spacy import load

nlp = en_core_web_sm.load() # I am trying to use like this instead of spacy.load('en_core_web_sm')

```
I am installing the en_core_web_sm using URL, requirements.txt:

```
spacy==2.3.0
https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.0/en_core_web_sm-2.3.0.tar.gz


```
I have also tried putting link as 

`en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.0/en_core_web_sm-2.3.0.tar.gz
`
I have also tried using spacy.load('') but it also does not works.

I am using heroku free tier services.

I have referenced these links #1099 #308 but was unable to solve my problem.
local machine:
* **spaCy version:** 2.3.0
* **Platform:** Linux-4.15.0-106-generic-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.6.9

heroku 
* **spaCy version:** 2.3.0
* **Platform:** Linux-4.4.0-1073-aws-x86_64-with-debian-buster-sid
* **Python version:** 3.6.10

**Comment by adrianeboyd** [comment]
Hi, sorry you're having trouble! Nothing in your setup looks incorrect at first glance. Are there error logs from the installation step or from when you try to load the model?

**Comment by aryanc55** [comment]
Thank you for replying. There are no errors while deploying the webapp. Heroku installs all the dependencies smoothly and deploys the app but when I try to access the website it throws error that it can not find en_core_web_sm module. 

A work around I found out from [StackOverflow](https://stackoverflow.com/questions/50934751/how-to-deploy-rasa-bot-to-heroku-using-spacy) was that in the Procfile I had to add the statement to install en_core_web_sm.

`web: sh setup.sh && streamlit run NLPJenny.py`  #this was giving error 

`web: python -m spacy download en_core_web_sm && sh setup.sh && streamlit run NLPJenny.py`  #this works fine

I am confused now, why this Procfile thing works and not the earlier methods I have used? Is this a spacy problem or Heroku's?

**Comment by adrianeboyd** [comment]
I don't think this is a problem with spacy itself. Especially since you don't have trouble getting it to work locally, it looks like some step in your heroku setup isn't downloading or installing the model as you expect. I'm afraid I'm not familiar with how heroku works.

**Comment by aryanc55** [comment]
Okay, thank you.
