### ISSUE TITLE
Unable to extrcat the proper entities using spacy en_core_sci_md model

### ISSUE THREAD

**Issue by Raghu17s** [explosion/spaCy#5725]
Hi folks,

I have a medical text which looks like ``chronic kidney disease hypertension diabetes mellitus coronary artery disease`` and trying to extract the following entities `` 1) chronic kidney disease, 2) hypertension,  3)diabetes mellitus,  4)coronary artery disease``. But it is giving me only two entities ``1)chronic kidney disease 2) hypertension diabetes mellitus coronary artery disease``

How do I get proper entities from any given text?

Here is my code.
```
import spacy 
nlp = spacy.load("en_core_sci_md")
doc = nlp("chronic kidney disease hypertension diabetes mellitus coronary artery disease")
for ent in doc.ents:
    print(ent.text, ent.label_)`
```
Output
```
chronic kidney disease ---> ENTITY
hypertension diabetes mellitus coronary artery disease ---> ENTITY
```

Expected Output
```
chronic kidney disease ---> ENTITY
hypertension ---> ENTITY
diabetes mellitus  ---> ENTITY
coronary artery disease ---> ENTITY
```
```

* Environment Information: 
* **spaCy version:** 2.2.4
* **Platform:** Windows-10-10.0.18362-SP0
* **Python version:** 3.7.3

**Comment by adrianeboyd** [comment]
Hi, these models are from AllenAI and not us so I'm not very familiar with the training data, but I think the models are trained on text that looks more like an academic article where the entities are used in context in full sentences, or at least with some context around them. If you just have a list of concatenated terms as your text, it's not going to have the clues from the context that help it disambiguate entity types and boundaries.

If you have a list of terms, you could consider using an `EntityRuler` in addition to the NER component. If the entities aren't used in context (especially in contexts that are at least somewhat similar to the training data), then the NER model is just not a good fit for this task.

**Comment by Raghu17s** [comment]
Yes, I agree they are from AllenAI. Keeping Scispacy aside,
I have trained a new spacy model from scratch, using the above entities, but the issue still exits having a length entity extracted by a trained spacy model.

Could you please assist other models, if NER is not a good fit (wrt to your last line)

**Comment by svlandeg** [comment]
It really depends on the particular challenge you're facing and how your data looks like. Like Adriane says, if you have very little context but you're really just looking for a dictionary-type of matching, you can find several approaches documented in detailed in the docs [here](https://spacy.io/usage/rule-based-matching).
