### ISSUE TITLE
spaCy v2.3.1 can't be imported in Python 2.7

### ISSUE THREAD

**Issue by convoliution** [explosion/spaCy#5729]
## How to reproduce the behaviour

```bash
python2 -m pip install spaCy==2.3.1
python2 -c "import spacy"
```
results in
```python
vocab.pyx:18: in init spacy.vocab
    ???
E     File "/home/travis/build/explosion/spaCy/spacy/lemmatizer.py", line 24
E       def __init__(self, lookups, *args, is_base_form=None, **kwargs):
E                                                     ^
E   SyntaxError: invalid syntax
```
spaCy's Python 2.7 build pipeline on Travis [is failing with the same error](https://travis-ci.org/github/explosion/spaCy/builds/706096302).

## Your Environment

* Operating System: macOS
* Python Version Used: 
* spaCy Version Used: 2.3.1
* Environment Information: clean environment

**Comment by adrianeboyd** [comment]
Thanks for the report! We'll get this fixed for the next release, v2.3.2.
