### ISSUE TITLE
No compatible model found for 'it_core_news_lg' (spaCy v2.2.4)

### ISSUE THREAD

**Issue by Tuzze** [explosion/spaCy#5737]
How to reproduce the behaviour
Upgrading spacy to 2.2.4 and running the command to download a model:

python -m spacy download it_core_news_lg 
results in an error:

✘ No compatible models found for v2.2.4 of spaCy
Your Environment
spaCy version: 2.2.4
Platform: Linux-5.4.15-arch1-1-x86_64-with-arch
Python version: 3.7.4

**Comment by adrianeboyd** [comment]
Sorry, this model is only available for spacy v2.3.
