### ISSUE TITLE
How to print all the trained entities in pretrianed spacy model?

### ISSUE THREAD

**Issue by Raghu17s** [explosion/spaCy#5738]
Hi folks,

I am using pre-trained spacy model (scispacy) and would like to check what are the entities are present in the model?
How do I print them?
Further, Is there any way I can remove partucular entity from the trained spacy model?

Thanks

**Comment by adrianeboyd** [comment]
No, it's just a statistical NER model, it doesn't contain any entity lists. One option is to update the model as described here to get it to forget particular kinds of examples: https://spacy.io/usage/training#ner . The very top of that page on training models may also be helpful.

Updating the models while retraining the performance for the remaining entity types can be tricky, so sometimes it's better to start from scratch with a new NER model or to use additional components like `EntityRuler` or `PhraseMatcher` to add and/or filter particular entities.
