### ISSUE TITLE
'Empty label found in new labels" with `spacy debug-data`

### ISSUE THREAD

**Issue by bburns632** [explosion/spaCy#5739]
## The issue
Hi, I ran into the same issue as #4845 (that is now closed and locked).  I found my missing labels within the spacy converted json as `"ner":"U-"`.  Just wanted to share.   

## How to reproduce the behavior 

1. Start with some hand labeled data with some mistakes. 
2. Reformat data into jsonl format with text labels 
`{"text": "Never mind - I found it! So a couple things ...", "entities": [{"start": 751, "end": 764, "label": "BRAND"}, ...]}`
3. Split data into test / train sets
4. Convert both files with `spacy convert` 
```
python -m spacy convert --lang en ./train.jsonl ./ 
python -m spacy convert --lang en ./test.jsonl ./ 
```
5. run debug-data
```
python -m spacy debug-data en ./train.json ./test.json -b en_core_web_md -p ner -V
```

## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by bburns632** [comment]
A more robust regex to search in the data would be `"ner":".*-"`

**Comment by adrianeboyd** [comment]
I think the JSONL converter was mainly intended for use with prodigy output (now if you're using prodigy we'd recommend the `data-to-spacy` option instead) and is not as robust as it could be, in particular if there are missing labels or tokenization mismatches between your character spans and spacy's tokenization. It's going to be removed in the upcoming spacy v3.
