### ISSUE TITLE
Force PoS mapping to UD tag set

### ISSUE THREAD

**Issue by petterhh** [explosion/spaCy#575]
I'm trying to train the PoS tagger in spaCy for Norwegian, and I see in the `train_tagger.py` script that one has to include a mapping from the tag set in the training data to the universal (UD) tag set. The problem arises when the mapping between the original tags and the tags in the UD tag set is not a one-to-one-mapping, which is the case for some of the tags in the Norwegian Dependency Treebank (NDT - see http://www.lrec-conf.org/proceedings/lrec2016/pdf/462_Paper.pdf). For instance, NDT does not distinguish between auxiliary and main verbs, hence a mapping would be something like `'verb': {'pos':('VERB', 'AUX')}`. Why is this mapping forced? Shouldn't the tagger be able to learn from the tags in the training data, no matter the tag set?

**Comment by honnibal** [comment]
The mapping is forced so that the user can take advantage of the `.pos` attribute. You can feel free to just shrug and say the coarse-grained tags won't be particularly accurate in your tagger. You can also use some fix-up process afterwards to correct them, if you want.

**Comment by petterhh** [comment]
Ah, okay, got it. 

By the way, should the `train_tagger.py` tutorial suffice for the training of the tagger? I'm running in it on Norwegian and reaching an accuracy of 44% on the test data, which is disappointing to say the least. It seems to make all kinds of extremely strange errors, such as tagging '.' as noun.

**Comment by honnibal** [comment]
Hmm.

If you don't have lemmatization or Brown clusters the tagger might be pretty bad. But 44% seems wrong.

**Comment by petterhh** [comment]
Yeah, something must be off, the types of errors are all kinds of strange.  I'm not using lemmatization or Brown clusters, instead simply supplying the tokens and tags, which is common when evaluating PoS taggers to my knowledge. I've evaluated taggers such as TnT, HunPos ad SVMTool in an identical manner, reaching accuracies exceeding 97%.

**Comment by honnibal** [comment]
See #579 for resolution
