### ISSUE TITLE
Spanish PROPN tag as INTJ

### ISSUE THREAD

**Issue by jccaleroe** [explosion/spaCy#5754]
Hello, when I run the POS tagging is Spanish, I am not getting the PROPN tag, instead I get INTJ in the proper names, for example:

INTJ	Alcalde
INTJ	Enrique
INTJ	Peñalosa

If just PROPN tags are in INTJ, I can skip the problem, but if INTJ and PROPN tags are mixed, that is a problem.

## How to reproduce the behaviour

```
nlp = spacy.load("es_core_news_lg")
with open("text_ins_spanish.txt") as f:
    doc = nlp(f.read())

for token in doc:
    print(token.pos_ + "\t" + token.lemma_)
```

## Your Environment
* Operating System: CentOS 8
* Python Version Used: 3.6.8
* spaCy Version Used: 2.3.1

**Comment by adrianeboyd** [comment]
Thanks for the report! This is indeed a bug in the tag map that maps the `token.tag` `PROPN` to the `token.pos` `INTJ`. (I think there's a mistake in one token in the AnCora corpus that led to this mapping.) This error should be consistent, so you can correct all the tokens with `tag` `PROPN` to have `pos` `PROPN` without worrying that some correct examples are mixed in.

I'll release updated versions of the models soon.

If you'd like to fix your installed model in the meanwhile, I've attached an updated tag map, which you can copy to the installed model directory (the attached file `tag_map.txt` below should overwrite the installed tag map at a path like `venv/lib/python3.7/site-packages/es_core_news_lg/es_core_news_lg-2.3.0/tagger/tag_map` -- I had to add `.txt` for github to let me attach it here, but the final name should be `tag_map`). You can double-check that this assertion holds to check that it was updated as intended:

```
nlp = spacy.load("es_core_news_lg")
assert nlp.vocab.morphology.tag_map["PROPN"][74] == 96
```

Updated Spanish model v2.3.0 tag map: [tag_map.txt](https://github.com/explosion/spaCy/files/4911728/tag_map.txt)
