### ISSUE TITLE
Incorrect dependency parse tree for cut-up text

### ISSUE THREAD

**Issue by ravishpankar** [explosion/spaCy#5758]
## How to reproduce the behaviour
I'm trying to run dependency parser on a job description. It contains a lot of cut-up text such as
Direct software development
Create test cases
Direct is pos tagged as noun and so is Create. Sometimes, when the capitalisation of first letter of these verbs are removed, they are pos tagged as verbs. The dependency parser displays these two cut-up sentences as qualifiers of cases then cases and qualifier of development then development. The correct behaviour should be direct and create should be verbs with edges to direct objects development and cases.

## Your Environment
* Operating System: windows 7
* Python Version Used:3.7.6
* spaCy Version Used:2.2
* Environment Information:

**Comment by svlandeg** [comment]
I don't know which prebuilt model you're using, but in general these are trained on more "proper" sentences. It's to be expected that ML/NLP models will perform worse when applied on input data that is significantly different than its training set, and so it doesn't really surprise me that they won't work particularly well on job descriptions.

I think your best bet will be to [retrain the dependency parser](https://spacy.io/usage/training#tagger-parser) for your specific texts / domain.
