### ISSUE TITLE
Multiple entities are not being labeled. Only few are

### ISSUE THREAD

**Issue by Carlongo** [explosion/spaCy#5760]
Hi,

So im training a model to recognize multiple labels (24 to be exact). So I've made a data set with combinations os sentences and combinations of words for each entity. 
For example: 

IDCard = "identification number", "citizen card".
ITIN = "individual taxpayer identification number", "itin".

Whats is happening is: When i train the model, with a dataset of almost 100k sentences, it only gets 4 of 24 entities. The sentences are like this: 

"update identification number",
"update individual taxpayer identification number".

I already solved the problem of overlapping entities, when it found overlapping entities in a sentence, it chooses the biggest entity combination.

What can be happening?

**Comment by adrianeboyd** [comment]
Without more information about your entities and training data, it's hard to know what might be going wrong. If there are many overlapping or nested entities in the underlying annotation scheme (like "individual taxpayer identification number" vs. "identification number") and it's hard to annotate them consistently in the simplified version without nested tags that's required for training the NER model, the model may have a hard time learning what to do.

You should also check that there's not a problem with your character offsets for the entities using:

```
spacy.gold.biluo_tags_from_offsets(nlp.make_doc(text), entities)
```

If you see `-` BILUO tags in the output, there are annotations that can't be aligned to the tokens and the model ignores them during training. This could explain why particular entity types aren't being identified as expected.

As an alternative, if you have fixed lists of known entities, you may want to use the `EntityRuler` instead of trying to train the NER model with artificial data.

**Comment by Carlongo** [comment]
Adriane, thank you so much for the reply!

I started using the EntityRuler already, because the model was in a hard time to identify those entities with NER model. The overlapping entities were a huge problem indeed.

If i may ask, do you know if the displacy.render have a limited number of colors. Because it is not showing all the entities when i use it.

The code:

from __future__ import unicode_literals, print_function
import spacy
from spacy import displacy
from spacy.matcher import Matcher
from spacy.lang.en import English
import matplotlib.pyplot
import json
import plac
import random
from pathlib import Path

model = r"/content/drive/My Drive/A DocumentCategory/TrainedModel"

# test the saved model
print("Loading from", model)
nlp = spacy.load(model)

ner = nlp.get_pipe("ner")
move_names = list(ner.move_names)

# Check the classes have loaded back consistently
assert nlp.get_pipe("ner").move_names == move_names

# Check the classes have loaded back consistently
assert nlp.get_pipe("ner").move_names == move_names

# Get the colors to the entities "linear-gradient(90deg, #aa9cfc, #fc9ce7)"

colors = {
    "Passport":"#87421f",
    "SSN": "#ffc300",
    "BirthCertificate": "#ffc300",
    "I9Sec1":"#9d6cd4",
    "I9Sec1and2":"#f6cd37",
    "PermanentResCard":"#c1442e",
    "EmploymentAuthDocCard":"#7b68ee",
    "AlienRegNo":"#cd5b45",
    "USCISNo":"#7a378b",
    "DriversLic":"#c1cdcd",
    "IDCard":"#cc7f32",
    "SchoolIDCardWithPhoto":"#604d3c",
    "VoterRegCard":"#838ede",
    "MilitaryCard":"#c48e48",
    "MilitaryDepID":"#cdad00",
    "USCoastGuardMerchantMarinerDocCard":"#db2929",
    "NativeAmericanTribalDoc":"#d43d1a",
    "VISA":"#ff6600",
    "SchoolRecOrReportCard":"#d6d6d6",
    "ClinicDoctorOrHospitalRec":"#3579dc",
    "TaxID":"#353f3e",
    "ITIN":"#fffafa",
    "EIN":"#00cd66" 
    }

options = {
    "ents": [
        "Passport", 
        "SSN", 
        "BirthCertificate", 
        "I9Sec1",
        "I9Sec1and2",
        "PermanentResCard",
        "EmploymentAuthDocCard",
        "AlienRegNo",
        "USCISNo",
        "DriversLic",
        "IDCard",
        "SchoolIDCardWithPhoto",
        "VoterRegCard",
        "MilitaryCard",
        "MilitaryDepID",
        "USCoastGuardMerchantMarinerDocCard",
        "NativeAmericanTribalDoc",
        "VISA",
        "SchoolRecOrReportCard",
        "ClinicDoctorOrHospitalRec",
        "TaxID",
        "ITIN",
        "EIN"
        ], "colors": colors}

print("\n")
while (test_text != "exit"):
    doc = nlp(test_text)
    displacy.render(doc, style='ent', jupyter=True, options=options)
    print("\n")
    test_text = input("Input: ")
    print("\n")

**Comment by adrianeboyd** [comment]
I think the displacy problem is the same as reported here: #4866. The color mapping currently expects labels to be in all caps. This is a problem that still needs to be addressed.

**Comment by Carlongo** [comment]
Thank you!!
