### ISSUE TITLE
Loading one model after another causes incorrect predictions

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#5765]
spacy 2.2.4

This is the same issue I reported in #4872

I thought it was resolved but apparently not.  In my application I noticed that when I change from one model to another the predictions become highly incorrect.  Please refer to original issue for python code used to reload model.

What is the correct way to totally reset everything when switching from one model to another so as to avoid this issue?

**EDIT**: TO be clear what I mean when I say the predictions become incorrect

Say I have on the left side a model loaded (version 1.0.0.10)  and on the right side I have a series of model from 1.0.0.5 to 1.0.0.11.  Using a single text I process it on the left side and get the results.  On the right side using an entirely separate instance of spacy I process the text through various models to compare the output with version 1.0.0.10 on the left.  However when I jump from any model other than 1.0.0.10, back to 1.0.0.10 the results on the left and right side are different, but they should be identical because I am passing the exact same text through the exact same model. In addition to that, this action of loading model after model causes the other models performance to degrade significantly as well.

I'm just pointing out that the changes in predictions are not attributed only to changing one model with another model, but that the actual predictions of a model for a specific text vary when they should remain consistent.

**Comment by adrianeboyd** [comment]
Do you see any warnings about vector names? Can you check the vector names in the two models (loaded separately) with `nlp.meta['vectors']['name']`?

**Comment by erotavlas** [comment]
I get this warning when I reload a new model

D:\Anaconda\lib\runpy.py:193: UserWarning: [W019] Changing vectors name from en_model.vectors to en_model.vectors_248089, to avoid clash with previously loaded vectors. See Issue #3853.
  "__main__", mod_spec)

those were also the names of the vectors given by the command `nlp.meta['vectors']['namw']`

**Comment by adrianeboyd** [comment]
Right, so the best solution here is to make the vectors names in your models unique (see my comment in the linked issue https://github.com/explosion/spaCy/issues/4872#issuecomment-570777456). You can edit the name in `meta.json` or provide a vectors name to `spacy init-model` with the option `--vector-name`.

**Comment by erotavlas** [comment]
@adrianeboyd 

I still experience incorrect classifications. What I tried was to set the name different in each of the model meta.json files.

**Comment by erotavlas** [comment]
@adrianeboyd  hello, are there any updates regarding this issue?

**Comment by erotavlas** [comment]
@adrianeboyd @svlandeg if its not possible to solve at the moment, is there a workaround?  Is there a procedure for clearing everything from memory before reloading a new model with spacy.load()?

**Comment by svlandeg** [comment]
@erotavlas: could you please avoid pinging maintainers, as this makes our GH mentions practically unusable? 

Could you please try again with spaCy 2.3.2? 
I have tried replicating your scenario by training 2 separate models on different vectors with the same name, but when I switch the `nlp` model from one to the other, the predictions consistently are those of each model as you'd expect them if you just run the models in isolation.

If you tried with 2.3.2 and the error persists, we're going to need more information to try and replicate this issue. Would it at all be possible to share your two models somewhere, so we can try to use those for replicating this issue?

**Comment by erotavlas** [comment]
@svlandeg I can provide a jupyter notebook with two models that will reproduce the issue.   I am not currently able to upgrade to 2.3.2 so this was tested on spacy 2.2.4.  Please provide instructions on where to place these files for your review. Thanks

**Comment by adrianeboyd** [comment]
The only thing I can think of: with the suggestion to edit `meta.json` I was mainly thinking of vectors-only models produced `spacy init-model`, not models that already contain trained pipeline components. If you have trained components in the model, you'd need to edit `meta.json` **and** `model/cfg` for each model to change `pretrained_vectors` in the config for each model to point to the same new unique name.

I'd expect you to see other errors when loading a model if these two settings are out-of-sync, but it's possible that if you always loaded multiple models in the same order and one of the other models has already provided the vectors with the mismatched name, the mismatch went unnoticed.

Starting from the beginning of the training process using a unique `--vectors-name` with `spacy init-model` is the best advice in general.

**Comment by erotavlas** [comment]
Honestly, I think calling spacy `load()` method (or some code within that) is the problem.  There appears to be some kind of data or state retained between successive calls.  Maybe variables are not being reset correctly?  That is the only explanation that makes sense given the observed results.  

Each successive call to load should produce a model what works exactly as if no model had been loaded before it.  If it doesn't then there is definitely something wrong with the spacy code base.

**Comment by adrianeboyd** [comment]
It's just an issue with how the vector tables are loaded and stored in memory, not any other variables. The idea behind it is that if two models use the same vector table that's identified by the same name, the vector table only needs to be loaded once in memory, but I agree that it's frustrating that the vector names have this kind of unexpected interaction. This will be fixed in spacy v3.

**Comment by svlandeg** [comment]
As @adrianeboyd has pointed out the underlying reasons that may be causing this, and how to avoid this in the future, and because this should be fixed in v3, I'll go ahead and close this issue as I don't think there are any actionable items for us at this point.
