### ISSUE TITLE
How is word segmentation done in Chinese models?

### ISSUE THREAD

**Issue by AlfredWGA** [explosion/spaCy#5775]
I am interested about how spaCy's Chinese model perform on word segmentation compared to other tools. I ran to following code,
```
import spacy
from spacy.lang.zh import Chinese

nlp1 = spacy.load("zh_core_web_sm")
nlp2 = Chinese() # jieba by default
text = "西门子将努力参与中国的三峡工程建设。"
doc1 = nlp1(text)
print('/'.join([t.text for t in doc1]))
doc2 = nlp2(text)
print('/'.join([t.text for t in doc2]))
```
The output is 
```
西门子/将/努力/参与/中国/的/三峡/工程/建设/。
西门子/将/努力/参与/中国/的/三峡工程/建设/。
```
How is word segmentation done when using `zh_core_web_**` models?

## Your Environment
* Operating System: Windows 10
* Python Version Used: 3.7.4
* spaCy Version Used: 2.2.3

**Comment by adrianeboyd** [comment]
Hi, it's using a custom `pkuseg` model trained on OntoNotes. See more details here, click to expand "Details on pretrained and custom Chinese models": https://spacy.io/usage/models#chinese
