### ISSUE TITLE
A model fails to load after adding custom vectors

### ISSUE THREAD

**Issue by sbushmanov** [explosion/spaCy#5780]
## How to reproduce the behaviour

I am following the instructions for adding custom vecs from here https://spacy.io/usage/vectors-similarity#custom-vectors-add.

Afterwards, Importing a custom trained model results in an error message:
```
import spacy
nlp_ru2 = spacy.load("/home/sergey/Py_Spacy_RU/ru2vec_2000000")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
pipes.pyx in spacy.pipeline.pipes.Tagger.from_disk.load_model()

~/anaconda3/envs/rasa/lib/python3.7/site-packages/thinc/neural/_classes/model.py in from_bytes(self, bytes_data)
    374                         name = name.decode("utf8")
--> 375                     dest = getattr(layer, name)
    376                     copy_array(dest, param[b"value"])

AttributeError: 'FunctionLayer' object has no attribute 'vectors'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-1-e62f0c90930a> in <module>
      3 import spacy.language
      4 spacy.language._fix_pretrained_vectors_name = lambda nlp: nlp
----> 5 nlp_ru2_2000000 = spacy.load("/home/sergey/Py_Spacy_RU/ru2vec_2000000")
      6 # nlp_ru2_2000000.pipeline

~/anaconda3/envs/rasa/lib/python3.7/site-packages/spacy/__init__.py in load(name, **overrides)
     25     if depr_path not in (True, False, None):
     26         deprecation_warning(Warnings.W001.format(path=depr_path))
---> 27     return util.load_model(name, **overrides)
     28 
     29 

~/anaconda3/envs/rasa/lib/python3.7/site-packages/spacy/util.py in load_model(name, **overrides)
    166             return load_model_from_package(name, **overrides)
    167         if Path(name).exists():  # path to model data directory
--> 168             return load_model_from_path(Path(name), **overrides)
    169     elif hasattr(name, "exists"):  # Path or Path-like to model data
    170         return load_model_from_path(name, **overrides)

~/anaconda3/envs/rasa/lib/python3.7/site-packages/spacy/util.py in load_model_from_path(model_path, meta, **overrides)
    209             component = nlp.create_pipe(name, config=config)
    210             nlp.add_pipe(component, name=name)
--> 211     return nlp.from_disk(model_path)
    212 
    213 

~/anaconda3/envs/rasa/lib/python3.7/site-packages/spacy/language.py in from_disk(self, path, exclude, disable)
    876             # Convert to list here in case exclude is (default) tuple
    877             exclude = list(exclude) + ["vocab"]
--> 878         util.from_disk(path, deserializers, exclude)
    879         self._path = path
    880         return self

~/anaconda3/envs/rasa/lib/python3.7/site-packages/spacy/util.py in from_disk(path, readers, exclude)
    668         # Split to support file names like meta.json
    669         if key.split(".")[0] not in exclude:
--> 670             reader(path / key)
    671     return path
    672 

~/anaconda3/envs/rasa/lib/python3.7/site-packages/spacy/language.py in <lambda>(p, proc)
    871                 continue
    872             deserializers[name] = lambda p, proc=proc: proc.from_disk(
--> 873                 p, exclude=["vocab"]
    874             )
    875         if not (path / "vocab").exists() and "vocab" not in exclude:

pipes.pyx in spacy.pipeline.pipes.Tagger.from_disk()

~/anaconda3/envs/rasa/lib/python3.7/site-packages/spacy/util.py in from_disk(path, readers, exclude)
    668         # Split to support file names like meta.json
    669         if key.split(".")[0] not in exclude:
--> 670             reader(path / key)
    671     return path
    672 

pipes.pyx in spacy.pipeline.pipes.Tagger.from_disk.load_model()

pipes.pyx in spacy.pipeline.pipes.Tagger.from_disk.load_model()

ValueError: [E149] Error deserializing model. Check that the config used to create the component matches the model being loaded.
```
1. The base model was a vectorless ['tagger','parser','ner'] model
2. Vectors were added:

```
for word,vector in zip(word,vectors):
    nlp.vocab.set_vector(word, vector)
``` 
3. Model was trained (for i. all pipeline elements, and ii. `ner` only):

```
now_tot = time.time()

with nlp.disable_pipes('tagger','parser'):
    for itn in range(10):
        now = time.time()
        losses = {}
        random.shuffle(data)
        # batch up the examples using spaCy's minibatch
        batches = minibatch(data, size=compounding(4.0, 64.0, 1.001))
        for batch in batches:
            texts, annotations = zip(*batch)
            nlp.update(
                texts,  # batch of texts
                annotations,  # batch of annotations
                drop=0.5,  # dropout - make it harder to memorise data
                losses=losses,
            )
        print("Iteration:", itn, "Losses", losses, "Time spent in minutes:", (time.time() - now)/60)

    print("Total time spent in hours:", (time.time() - now_tot)/3600)
```
4. For both of (3), the above message is produced while loading a saved `nlp.to_disc()` model.
5. Neither [trying](https://github.com/explosion/spacy-transformers/issues/105#issuecomment-557707931) `2.2.1` version  or `spacy.language._fix_pretrained_vectors_name = lambda nlp: nlp` helped.
6. There is no such an issue if I only train `ner` in CLI with vectors provided via `-v` option. The same updated model loads just fine.

## Your Environment

* Operating System: Ubuntu 18.04
* Python Version Used: 3.7.6
* spaCy Version Used: 2.1.9, 2.2.1, 2.3.1, 2.3.2

**Comment by adrianeboyd** [comment]
It's not possible to update an existing component model like a tagger by adding vectors after the model has already been initialized.

Within the same saved spacy model, you can currently save one set of vectors. You should be able to have some components that use these vectors as features and some components that don't. You can check in `tagger/cfg`, `ner/cfg`, etc. to see whether `pretrained_vectors` is set to `null` or to the vectors name from `meta.json`.

Adding vectors to a base model without vectors should result in vectors in the `vocab` that are ignored by the components that are already initialized without `pretrained_vectors`. When you run `nlp.update`, I think the vectorless model should be updated without referring to any vector features.

I tested a few quick examples and 2.3.2 and wasn't able to produce the same error after combining and updating component models with and without vectors, so I'm not quite sure what's going on with your error above. Do you have a complete minimal example that we could run that results in the same error? It can just have a few toy vectors and a few toy training texts.

Just in case, also make sure you're not mixing models trained with v2.1, v2.2, and v2.3, since the model formats are slightly different underneath. v2.3 should check model version compatibility explicitly, but the older versions may just fail to load instead of providing clear errors and warnings.

**Comment by sbushmanov** [comment]
`"Pretrained vectors changed"` in tagger' and parser's cfg changed indeed from `null` to something else (`"pretrained_vectors":"spacy_pretrained_vectors_569319"` in my case).

Am I getting you right, changing manually back to `null` should cure the problem?

(I will try to compose a reproducible example later).

**Comment by adrianeboyd** [comment]
Those vectors names are what you end up with when you have multiple models loaded at the same time with the same vectors name but different shapes. It tries to rename vectors if it finds clashing names, but it doesn't always succeed and the names aren't always unique in the end. (The whole vectors names setup is a bit janky. The idea behind it is that you might have two models that both refer to the vectors from `en_core_web_lg` and you only need to have those vectors in memory once for both models to work, so it tries to just keep a reference to one copy under the provided name. It all works okay, but only as long as the names don't clash.)

The best solution is use unique vector names for unique underlying vectors when you create the models initially with `spacy init-model` or by changing `nlp.vocab.vectors.name`.

It's also possible `_fix_pretrained_vectors_name` screws things up when you have a mix of `pretrained_vectors` settings, I'm not sure. We typically assume that all the relevant models would be using the included vectors if they're there, so a setup with some models with vectors and some without isn't something we've tested a lot, and there may be bugs / inconsistencies.

**Comment by sbushmanov** [comment]
What is my way forward? Can I add vectors to a vectorless model like:
 ```
for word,vector in zip(word,vectors):
    nlp.vocab.set_vector(word, vector)
```
and train, train, load trained model afterwards?

**Comment by sbushmanov** [comment]
> Adding vectors to a base model without vectors should result in vectors in the vocab that are ignored by the components that are already initialized without pretrained_vectors. When you run nlp.update, I think the vectorless model should be updated without referring to any vector features.

Am I getting you right it's not possible to add vectors to a vectorless model?

**Comment by adrianeboyd** [comment]
No, you'd have to initialize and train a whole new model from scratch.

**Comment by sbushmanov** [comment]
Is it also true that supplying vectors in CLI like `spacy train -b model -v vectors -n 'ner' ... ` useless?

**Comment by adrianeboyd** [comment]
[Sorry, just clicked close by accident.]

The vectors provided to `spacy train` are not going to affect models that are already initialized and trained in the base model. Once the model has been initialized and trained without vectors, all the relevant model features and parameters are set and can't be changed later.

**Comment by adrianeboyd** [comment]
You cannot add vectors to extend an existing trained model. If you want to include vectors, you need to initialize and train the model from scratch.

**Comment by sbushmanov** [comment]
I still do not quite understand where we are with adding custom vecs.

Can somebody from Explosion confirm it's a bug and remove the section from the document https://spacy.io/usage/vectors-similarity#custom-vectors-add (or at least clarify what and when can be added and when cannot).

Because I'm following the instructions in the documentation, and then the model with added vecs fails to load.

I do think it's a bug though, because after adding vecs, pipeline component cfg's are updated with vecs, which shouldn't occur.
