### ISSUE TITLE
Context-based medical concepts extraction from the given text

### ISSUE THREAD

**Issue by Raghu17s** [explosion/spaCy#5782]
Hi Folks,

I am looking for some suggestions or algorithms for my NLP problem.
I have a medical text which has a diagnosis, past history, negations (like no headache, fever), and in what case-patient to consult a doctor in the future/emergency.  

Example of text

**The patient admitted to the hospital with hypertension and chronic kidney disease. The patient had a past history of diabetes mellitus and coronary artery disease. When the patient admitted to the hospital, no symptoms of fever, giddiness, and headache found. The patient is asked to consult a doctor in case of vomiting and nausea.** 

The above sentence has a present illness (sentence 1), past history (sentence 2), negations (sentence 3), and future consultation (sentence 4). I have been using scispacy for medical concept extraction and negspacy for negotiations, both of them are working fine. 

How do I separate present illness, past history, and future consultations in the NLP technique?
I need to extract the context-based medical concepts from the given text.

**Comment by adrianeboyd** [comment]
This is a fairly general question, so I think it's better suited for StackOverflow. Here's the link for anyone who comes across this: https://stackoverflow.com/questions/62989596/context-based-medical-concepts-extraction-from-the-given-text-in-python

**Comment by Raghu17s** [comment]
Check out this, I found a way to tackle this problem. 
https://github.com/jenojp/negspacy/issues/17
