### ISSUE TITLE
Spacy seems to miss simple amod dependency

### ISSUE THREAD

**Issue by rickbeeloo** [explosion/spaCy#5797]
When taking a simple sentence like _"He bought a beautiful and fast car."_  Spacy does find the dependency beautiful-car but not fast-car (also noticed here on[ StackOverflow](https://stackoverflow.com/questions/32329039/get-corresponding-verbs-and-nouns-for-adverbs-and-adjectives))

## How to reproduce the behaviour
```
import spacy
nlp = spacy.load('en_core_web_lg')
doc = nlp('He bought a beautiful and fast car.')
spacy.displacy.serve(doc, style='dep')
```

![Uploading image.png…]()

## Your Environment
spaCy version    2.3.2                         
Location         /python3.6/site-packages/spacy
Platform         Linux-5.3.0-62-generic-x86_64-with-Ubuntu-18.04-bionic
Python version   3.6.9

**Comment by adrianeboyd** [comment]
The spacy dependency parser can't produce extended dependencies like in that example. It has a restriction that each token can only have one head, so it will only produce parses more like the Stanford "basic dependencies".

**Comment by rickbeeloo** [comment]
Aah thankyou Adriane, can you recommend an alternative package or workaround in order to detect this?

**Comment by adrianeboyd** [comment]
There's no workaround for spacy -- the internal dependency graph representation simply does not support this. You can try out the Stanford dependency parser (only for English, I think), or for more cutting edge work there was just a shared task on this topic: https://universaldependencies.org/iwpt20/ and https://www.aclweb.org/anthology/volumes/2020.iwpt-1/

**Comment by rickbeeloo** [comment]
Thanks, Adriane, I checked all the papers and this indeed looks amazing. However, since it was that recent (this month actually) the codes are either not available or not documented at all. I also tried the Stanford parsers (Stanford NLP and core NLP) however this also does not recognize the amod dependency :(. Since you are more familiar in this field you perhaps may have other suggestions?

**Comment by adrianeboyd** [comment]
I'm not that familiar with the options here, but I think the Stanford dependency parser is probably a good choice for a stable tool. Coordination is extremely hard and you'll probably need to allow for some degree of error no matter which tool you use.

**Comment by rickbeeloo** [comment]
Aaah thankyou Adriane!
