### ISSUE TITLE
JA model drops POS tags when using displacy.

### ISSUE THREAD

**Issue by solarmist** [explosion/spaCy#5802]
## How to reproduce the behavior
The error is visible at 
https://explosion.ai/demos/displacy?text=若葉は薄い色合いから日に日に濃さを増している%E3%80%82&model=ja_core_news_sm&cpu=1&cph=1
```
import spacy
from spacy import displacy

text = "若葉は薄い色合いから日に日に濃さを増している。"
nlp = spacy.load("ja_core_news_lg")
doc = nlp(text)
displacy.render(doc, style="dep")
```

This seems to be caused by 
https://github.com/explosion/spaCy/blob/v2.3.2/spacy/displacy/__init__.py#L122
`    doc = Doc(orig_doc.vocab).from_bytes(orig_doc.to_bytes(exclude=["user_data"]))`

When I drop into `pdb` and examine the object `orig_doc` has the pos's tagged, but `doc` doesn't and it doesn't seem to be as simple as the fact that the Japanese model stores meta-data in the user_data dictionary.

## Your Environment

* **spaCy version:** 2.3.2
* **Platform:** macOS-10.15.5-x86_64-i386-64bit
* **Python version:** 3.8.2
* Environment Information:

**Comment by solarmist** [comment]
@polm issue we chatted about.

**Comment by adrianeboyd** [comment]
Ah, the problem is that the tokenizer needs to set `doc.is_tagged` here. If you set `doc.is_tagged = True` above, it should work, I think.

**Comment by solarmist** [comment]
Yup, that fixes it for me.
