### ISSUE TITLE
Problem with noun chunks in 2.3.1 version

### ISSUE THREAD

**Issue by xricht29** [explosion/spaCy#5805]
Hi there.
I'm using spacy with doc.nun_chunks. The problem is, that spacy 2.3.1 behaves differently from demo-version (2.3.0) on the official spacy website [https://spacy.io/](https://spacy.io/). It often doesn't find the ROOT chunk, or even any chunk in the sentence or phrase, but the demo-version finds it.

Here's the example of code:
```
import spacy
nlp = spacy.load("en_core_web_sm")
doc = nlp("star in the constellation Cassiopeia")
for chunk in doc.noun_chunks:
    print(chunk.text, chunk.root.text, chunk.root.dep_, chunk.root.head.text)
```

My spacy's version finds only one chunk, "the constellation", but demo-version finds also "star", (which I need as ROOT) and "Cassiopeia". Also if I use this code with text "soprano", the demo-version finds "soprano" as ROOT, but version 2.3.1 finds nothing.
Does anyone know where the problem could be? Thanks for any advice.

## Environment
* Operating System: Linux-4.15.0-72-generic-x86_64-with-Ubuntu-18.04-bionic
* Python Version Used: 3.6.9
* spaCy Version Used: 2.3.2

**Comment by adrianeboyd** [comment]
The attachment of `Cassiopeia` is kind of ambiguous in this example and there's not any surrounding context to help disambiguate (maybe it's `[star in the constellation] Cassiopeia` vs. `star in the [constellation Cassiopeia]`). Slight differences in these kinds of cases are hard to avoid when retraining the parsing models.

I do see more consistent results with a full sentence like `I saw the brightest star in the constellation Cassiopeia.`. I'd also recommend trying the `en_core_web_md` model, which may be a bit more accurate without being much larger or slower.

If you want the exact same results as in the demo, you can install the `en_core_web_sm 2.3.0` model directly with:

```
pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.0/en_core_web_sm-2.3.0.tar.gz
```

The models should be very similar overall, but there were some very minor English tokenization setting changes between spacy 2.3.0 and spacy 2.3.1, so the English models were retrained using the new settings and released along with spacy 2.3.1. However any models with versions 2.3.x should be compatible with any spacy 2.3.x version.

If you come across similar instances in the future, #3052 is a good place to report them.
