### ISSUE TITLE
Lemmas for Portuguese

### ISSUE THREAD

**Issue by gnegrelli** [explosion/spaCy#5811]
Hi.

I'm currently working on lemmas for Portuguese and I would love to contribute with a PR on the tables for this language. However, I got a little confused on how the Lemmatizer uses the lookups tables.

As far as I understand, the lemmatizer applies the replaces described on the 'lemma_rules' table and checks if any of the results obtained are listed on the 'lemma_index' table. At the same time, it looks for the token on the exceptions table 'lemma_exc'. All these searches are made considering POS (and, in some cases, morphology).
If none of those tables exist (which is the case for portugues right now), the lemmatizer simply looks for the lemma on the 'lemma_lookups' table.

Is this correct? Does it have any additional steps that I missed? In languages that have 'lemma_rules', 'lemma_index' and 'lemma_exc', does the lemmatizer still use 'lemma_lookups' table for something else?

**Comment by adrianeboyd** [comment]
Yes, I'm pretty sure that's right. For the default lemmatizer as soon as it finds a 'lemma_rules' table, it switches 100% to the rule-based approach and stops referring to the lookups table at all. If you write a custom lemmatizer (see examples in French and Greek), I don't think would be hard to change, though. If the tables are there, I think you could use the lookups table for certain POS tags and rules for others, for instance.

**Comment by gnegrelli** [comment]
@adrianeboyd, thanks for the answer, I'll have a look on the custom lemmatizers you mentioned. 

In the meantime, I was doing some testing with the standard lemmatizer in English. When lemmatizing the token `'cause`, I got `because` instead of `'cause`, despite the fact it only being listed on the `en_lemma_lookups` table. I understand that `because` is the correct lemma for `'cause`, but following the logic mentioned, shouldn't the token's lemma be `'cause`? Is there any previous step that forces its lemma to the correct one?

**Comment by adrianeboyd** [comment]
Those come from the tokenizer exceptions, e.g.:

https://github.com/explosion/spaCy/blob/b97dbab998640479e8ba0dfbe8fa1759908195df/spacy/lang/en/tokenizer_exceptions.py#L423-L424

We decided that letting the tokenizer set these kinds of attributes (anything beyond `NORM`) was a bad idea overall and we're going to remove this in the future, so please don't use this approach.
