### ISSUE TITLE
Core dumped in NER extraction

### ISSUE THREAD

**Issue by GregBueno** [explosion/spaCy#5815]
## How to reproduce the behaviour
I'm running spacy model inside docker with python 3.6.
When I try to run `doc = model(text)` return this message:

> libblis: /io/checkout/blis/_src/frame/base/check/bli_obj_check.c (line 106):
> libblis: Encountered invalid row stride relative to n dimension.
> libblis: Aborting.
> Aborted (core dumped)

I've already test the process in docker with ubuntu18.04 image, upgrade memory, del variables during process to relieve memory.

What should I do?

Curiously, when i run process outside docker, works 
My machine has Ubuntu 18.04, 16GB ram.

## Your Environment
* Operating System: Docker with python:3.6 image.
* Python Version Used: 3.6
* spaCy Version Used: 2.2.3

**Comment by adrianeboyd** [comment]
Core dumps are hard to debug from afar, hmm. And this isn't at all helpful, but I have seen this error a few times locally but I don't remember what caused it.

My first guess might be that you have incompatible versions of `spacy` and `thinc`. Can you compare the docker vs. non-docker output for `pip list` carefully to see if there are any differences for all the packages related to `spacy`? My second guess would be that you might have a model that was trained with an incompatible version of spacy. If you're using spacy v2.2.3 then your model should be trained using spacy v2.2.x.

I suspect that this is something related to `thinc` or the model configuration, not the amount of RAM. Or can you observe that it's running out of memory?

**Comment by GregBueno** [comment]
Dear Adriane, thanks for your help.
My models are trained and running in spacy v2.2.3 and thinc 7.3.1.
I'm using 4 models loaded as singleton.

After 3 days changing everything, I solved core dumped problem changing the **vectors name** between models, because all models have the same **vectors name**.

Files to change: **ner/cfg**, **meta.json** and **vocab/vector**.

Using the code below I've changed meta.json and vocab/vector. But I didn't found any variable referent **ner/cfg** to update in model loaded, so I've to change manually the keys _vectors_name_ and _pretrained_vectors_ in **ner/cfg** file
```
import spacy
from pathlib import Path

ner = spacy.load(Path("./resources/models/ner/model1/"))
custom_vec_name = 'pt_model_general.vectors'
ner.vocab.vectors.name = custom_vec_name
ner.meta["vectors"]["name"] = custom_vec_name

output_dir = "./resources/models/ner/model1_updated/"
ner.to_disk(output_dir)
```

**Comment by adrianeboyd** [comment]
Glad you figured it out! Sorry the vectors name setting is not obvious and can be frustrating to debug.

If you want to change the vectors name in the model config programmatically, it is possible but the model config isn't very well documented for v2, so it's not surprising that you couldn't find the right place. The meta is derived directly from the vectors object, so you just need to change two places if you only have an NER model:

```python
nlp.vocab.vectors.name = custom_vec_name
nlp.get_pipe("ner").cfg["pretrained_vectors"] = custom_vec_name
nlp.to_disk(output_path)
```

I'm guessing that you had vectors with different dimensions but with the same name and that's what led to the error above?

Did you create your models with `spacy init-model`? I think `spacy init-model` needs to do a better job of getting the vectors name set sensibly. For most cases, I think a random name would be a better result than what we have now.

**Comment by GregBueno** [comment]
Adrine thanks for your advice,
In cfg file I've change two keys: _deprecation_fixes_ and _pretrained_vectors_
So, the solution to solve the crash of core dumped is :

```
import spacy
from pathlib import Path

model_folder = "ner_general"
input_dir = f"./resources/models/ner/{model_folder}/"
output_dir = f"./resources/models/ner_v2/{model_folder}/"

custom_vec_name = f'{model_folder}.vectors'

model = spacy.load(Path(input_dir))
model.get_pipe("ner").cfg['deprecation_fixes']['vectors_name'] = custom_vec_name
model.get_pipe("ner").cfg['pretrained_vectors'] = custom_vec_name
model.vocab.vectors.name = custom_vec_name
model.to_disk(output_dir)
```

My training process is:

```
python -m spacy init-model pt skip_s100_spacy --vectors-loc skip_s100.zip
python -m spacy train pt ner_general data_train.json data_test.json -n 100 -ne 10 -p ner -v skip_s100_spacy/
```

**Comment by adrianeboyd** [comment]
Okay, if you're starting with `init-model`, you want to add the option `--vectors-name` instead, and then you can skip all of the hacky config editing:

```
python -m spacy init-model pt skip_s100_spacy --vectors-loc skip_s100.zip --vectors-name pt_skip_s100_1234.vectors
```

Or some unique name per set of vectors.

**Comment by GregBueno** [comment]
It's a great advice, I'll use in the next training.

Each model has 1GB, most of the size is from vectors. Is there any possibility of using one vector shared in all ner models ?
The memory usage will reduce considerably.

**Comment by GregBueno** [comment]
Any suggestion for:
**_Each model has 1GB, most of the size is from vectors. Is there any possibility of using one vector shared in all ner models ?
The memory usage will reduce considerably._**

**Comment by FullDataAlchemist** [comment]
I recently got this problem and non of the above were fixing it. I solved it by changing two things same as each other:
1-  `pretrained_vectors` field inside the `cfg` file in the `ner` folder
2- `vectors[name]` inside the meta.json file
