### ISSUE TITLE
unable to use spacy with GPU 

### ISSUE THREAD

**Issue by StephennFernandes** [explosion/spaCy#5816]
`spacy.require_gpu()`  returns true 
But on using the nlp() method returns error. 
All cuda devices are busy or unavailable. 

Tried even after several reboots. 

tried `pip install spacy[cuda102]` .. also tried with several other cuda versions .... no python virtual enviroment issue , already checked 

Environment
* **spaCy version:** 2.3.2
* **Platform:** Linux-5.4.0-42-generic-x86_64-with-debian-buster-sid
* **Python version:** 3.7.3

**Comment by adrianeboyd** [comment]
The error looks like it might related to the compute mode for the card you're trying to use. Here's a related thread I found (among others, this may not be the most relevant one for your case): https://forums.developer.nvidia.com/t/why-all-cuda-capable-devices-are-busy-or-unavailable/17588

In any case, you shouldn't be guessing about the CUDA version. You need to figure out which CUDA version you have installed (`nvcc --version`) and if it's a new install, it's a good idea to verify the CUDA installation using the sample programs in the install instructions. Then install the corresponding `cupy` package called `cupy-cudaNNN` with the right version like `cupy-cuda101`. You can do a minimal verification that `cupy` is working by creating a small array:

```python
import cupy
a = cupy.zeros((1,1))
```

**Comment by StephennFernandes** [comment]
done, Fixed .. Thanks
