### ISSUE TITLE
Fractional words not being classified as a number

### ISSUE THREAD

**Issue by rahul1990gupta** [explosion/spaCy#5827]
When I process fractional words like "third" or "fourth" spacy doesn't classify it as a number. Maybe It's the desired behavior. I thought I would point it out.

## How to reproduce the behaviour

```
from spacy.lang.en import English

nlp = English()
doc = nlp("One-third of Bhutan’s population is under the age of 14; its median age is 22.3 years.")

for token in doc[:3]:
  print(token.text, token.like_num)

```
This output 
One True
 '-' False
 third False

I am happy to release a fix if spacy wants to classify these fractional words as numbers.
## Info about spaCy

* **spaCy version:** 2.3.2
* **Platform:** macOS-10.12.6-x86_64-i386-64bit
* **Python version:** 3.8.5

**Comment by svlandeg** [comment]
I think it would make sense to have them classified as such, though you're right it looks like English doesn't yet do this.

Dutch, for instance, does specifically care about ordinal words: https://github.com/explosion/spaCy/blob/master/spacy/lang/nl/lex_attrs.py#L15. I like how it's split up in two separate private lists, allowing further fine-grained functionality in the future, if we'd need it.

**Comment by rahul1990gupta** [comment]
That makes sense. I think this will have to be implemented separately for each of the languages.  I am working on improving lexical attributes for the Hindi language and will add Hindi ordinal words as well. 

I will add English ordinal words in a separate PR today.

**Comment by svlandeg** [comment]
Awesome, thanks!
