### ISSUE TITLE
Incorrect word vector location in load new word vectors tutorial

### ISSUE THREAD

**Issue by pokey** [explosion/spaCy#583]
In the load-new-word-vectors tutorial, it says that the word vectors are at `data/vocab/vec.bin`, but I don't see them there.  For me, they're in `data/en-1.1.0/vocab/vec.bin`.  Is this a bug in the tutorial, or an oddness in my SpaCy installation?

**Comment by honnibal** [comment]
That's a bug in the tutorial.

By the way: you've probably noticed that the tutorials are in a pretty messy state at the moment. If you have the patience to keep reporting (or even pull requesting) these issues, I'd really appreciate it.

If it gets too much and you want to keep a rough list of notes instead, well...that's at least better than nothing.

**Comment by pokey** [comment]
Ok, I'm not sure how to fix that one robustly, so I'll leave it. Would be
great to see the solution, though, as right now I've just put a hard-coded
path into my code, which is never a good feeling

And I'll keep submitting issues / PRs as I find problems. Overall great
stuff though! The tutorials are very helpful
