### ISSUE TITLE
Is it possible to print the repeated entities more than once is in a sentence?

### ISSUE THREAD

**Issue by AkshayO-95** [explosion/spaCy#5832]
I created a NER model. The model detects all the entities accurately but the sentences I have are like "1 tray of pastries, 1 box of salad". The NER will detect "1" only once although it appears twice in the sentence. Is there an easy way to allow NER to print the duplicate entities more than once? I need to further use these detected entities and process them as tables. 

## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.7.8
* spaCy Version Used: 2.3.2
* Environment Information:

**Comment by adrianeboyd** [comment]
The NER model should be able to detect each `1` separately. For example, with the provided model:

```python
import spacy

nlp = spacy.load("en_core_web_sm")
doc = nlp("1 tray of pastries, 1 box of salad")

for ent in doc.ents:
    print(ent.text, ent.start, ent.end, ent.label_)
```

Output:

```none
1 0 1 CARDINAL
1 5 6 CARDINAL
```

If your model is only detecting one of the `1` instances, you may need to extend your training data.
