### ISSUE TITLE
EntityRuler overlapping matches of the same length, the one appearing last in the document is chosen instead of the first

### ISSUE THREAD

**Issue by mdgilene** [explosion/spaCy#5840]
Believe this is caused by the following line using `reverse=True` for both sort keys. It should be reverse sorted on entity length, then regular sort on start index:
https://github.com/explosion/spaCy/blob/03ab518f285544cda22cffa8627255d405255c88/spacy/pipeline/entityruler.py#L98-L99

## How to reproduce the behaviour

```
import spacy
from spacy.pipeline import EntityRuler

patterns = [
    {"label": "FOOBAR", "pattern": "foo bar"},
    {"label": "BARBAZ", "pattern": "bar baz"},
]

nlp = spacy.load("en_core_web_sm")
ruler = EntityRuler(nlp)
ruler.add_patterns(patterns)
nlp.add_pipe(ruler, before="ner")

doc = nlp("foo bar baz")

print([(ent.text, ent.label_, ent.ent_id_) for ent in doc.ents])
```

## Your Environment

* **spaCy version:** 2.3.2
* **Platform:** Windows-10-10.0.17134-SP0
* **Python version:** 3.7.5

**Comment by adrianeboyd** [comment]
Thanks for the report! We'd fixed the same issue in `util.filter_spans` but missed the same issue here.
