### ISSUE TITLE
SpaCy 2.3.2 - awkward reference to tokenizations.tokenization messes up load model [SOLVED!]

### ISSUE THREAD

**Issue by Bogula** [explosion/spaCy#5850]
##Problem
1. Installed SpaCy 2.3.2 on Ubuntu 18.04. with CUDA support for Jetson Nano,
works and imports fine, is_gpu -> TRUE. 

2. Installed "de_trf_bertbasecased_lg" successfully.

3. nlp = spacy.load("de_trf_bertbasecased_lg") 
does result in an awkward error: "No module named 'tokenizations.tokenizations'"

I have imported: torch, transformers and spacy

4. Installed "en_core_web_sm" to countercheck, same behavior.

Can anybody make sense of the reference to a module tokenizations, which is expected in the site-packages directory?

##Error message from Jupyter Notebook:

/home/ai/.local/lib/python3.6/site-packages/spacy_transformers/pipeline/wordpiecer.py in <module>()
      1 from spacy.pipeline import Pipe
      2 from spacy.util import minibatch
----> 3 from tokenizations import get_alignments
      4 import re
      5 import numpy

/home/ai/.local/lib/python3.6/site-packages/tokenizations/__init__.py in <module>()
----> 1 from .tokenizations import get_alignments, get_charmap, get_original_spans
      2 
      3 __all__ = ["get_charmap", "get_alignments", "get_original_spans"]

ModuleNotFoundError: No module named 'tokenizations.tokenizations'

## My Environment

* **spaCy version:** 2.3.2
* **Platform:** Linux-4.9.140-tegra-aarch64-with-Ubuntu-18.04-bionic
* **Python version:** 3.6.9

**Comment by adrianeboyd** [comment]
What version of `spacy-transformers` do you have installed?

**Comment by adrianeboyd** [comment]
Also the output of `spacy validate` would be useful.

**Comment by Bogula** [comment]
Dear Adriane,

thanks for coming back to me on this issue.

spacy                                   2.3.2
spacy-transformers            0.6.2
srsly                         1.0.2
thinc                         7.4.1

python3 -m spacy validate
✔ Loaded compatibility table

====================== Installed models (spaCy v2.3.2) ======================
ℹ spaCy installation:
/home/ai/.local/lib/python3.6/site-packages/spacy

TYPE      NAME                                     MODEL                          VERSION                            
package   en-core-web-sm                en_core_web_sm                2.3.1   ✔
package   de-trf-bertbasecased-lg   de_trf_bertbasecased_lg   2.3.0   ✔

Thank you
 Werner

**Comment by adrianeboyd** [comment]
Hmm, when you installed `spacy-transformers` it should have also installed the package `pytokenizations`. Can you check your list of installed packages to see what version is installed?

I'm wondering whether there could be a package naming conflict somewhere related to with `pytokenizations` vs. `tokenizations`, but I would have expected an install error for `spacy-transformers` from `pip` even so.

**Comment by Bogula** [comment]
Thank you Adriane,

pytokenizations is installed in version 0.5.0

it seems the error originates from pipeline/wordpiecer

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-0d4d604956c2> in <module>()
      3 
      4 # Load English tokenizer, tagger, parser, NER and word vectors
----> 5 nlp = spacy.load("en_core_web_sm")
      6 
      7 # Process whole documents

/home/ai/.local/lib/python3.6/site-packages/spacy/__init__.py in load(name, **overrides)
     28     if depr_path not in (True, False, None):
     29         warnings.warn(Warnings.W001.format(path=depr_path), DeprecationWarning)
---> 30     return util.load_model(name, **overrides)
     31 
     32 

/home/ai/.local/lib/python3.6/site-packages/spacy/util.py in load_model(name, **overrides)
    168             return load_model_from_link(name, **overrides)
    169         if is_package(name):  # installed as package
--> 170             return load_model_from_package(name, **overrides)
    171         if Path(name).exists():  # path to model data directory
    172             return load_model_from_path(Path(name), **overrides)

/home/ai/.local/lib/python3.6/site-packages/spacy/util.py in load_model_from_package(name, **overrides)
    189     """Load a model from an installed package."""
    190     cls = importlib.import_module(name)
--> 191     return cls.load(**overrides)
    192 
    193 

/home/ai/.local/lib/python3.6/site-packages/en_core_web_sm/__init__.py in load(**overrides)
     10 
     11 def load(**overrides):
---> 12     return load_model_from_init_py(__file__, **overrides)

/home/ai/.local/lib/python3.6/site-packages/spacy/util.py in load_model_from_init_py(init_file, **overrides)
    237     if not model_path.exists():
    238         raise IOError(Errors.E052.format(path=path2str(data_path)))
--> 239     return load_model_from_path(data_path, meta, **overrides)
    240 
    241 

/home/ai/.local/lib/python3.6/site-packages/spacy/util.py in load_model_from_path(model_path, meta, **overrides)
    201     lang = meta.get("lang_factory", meta["lang"])
    202     cls = get_lang_class(lang)
--> 203     nlp = cls(meta=meta, **overrides)
    204     pipeline = meta.get("pipeline", [])
    205     factories = meta.get("factories", {})

/home/ai/.local/lib/python3.6/site-packages/spacy/language.py in __init__(self, vocab, make_doc, max_length, meta, **kwargs)
    169         RETURNS (Language): The newly constructed object.
    170         """
--> 171         user_factories = util.registry.factories.get_all()
    172         self.factories.update(user_factories)
    173         self._meta = dict(meta)

/home/ai/.local/lib/python3.6/site-packages/catalogue.py in get_all(self)
    110         result = OrderedDict()
    111         if self.entry_points:
--> 112             result.update(self.get_entry_points())
    113         for keys, value in REGISTRY.items():
    114             if len(self.namespace) == len(keys) - 1 and all(

/home/ai/.local/lib/python3.6/site-packages/catalogue.py in get_entry_points(self)
    125         result = {}
    126         for entry_point in AVAILABLE_ENTRY_POINTS.get(self.entry_point_namespace, []):
--> 127             result[entry_point.name] = entry_point.load()
    128         return result
    129 

/usr/local/lib/python3.6/dist-packages/importlib_metadata/__init__.py in load(self)
    103         """
    104         match = self.pattern.match(self.value)
--> 105         module = import_module(match.group('module'))
    106         attrs = filter(None, (match.group('attr') or '').split('.'))
    107         return functools.reduce(getattr, attrs, module)

/usr/lib/python3.6/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

/usr/lib/python3.6/importlib/_bootstrap.py in _gcd_import(name, package, level)

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _load_unlocked(spec)

/usr/lib/python3.6/importlib/_bootstrap_external.py in exec_module(self, module)

/usr/lib/python3.6/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

/home/ai/.local/lib/python3.6/site-packages/spacy_transformers/__init__.py in <module>()
      1 from .language import TransformersLanguage
----> 2 from .pipeline.tok2vec import TransformersTok2Vec  # noqa
      3 from .pipeline.textcat import TransformersTextCategorizer  # noqa
      4 from .pipeline.wordpiecer import TransformersWordPiecer  # noqa
      5 from .model_registry import register_model, get_model_function  # noqa

/home/ai/.local/lib/python3.6/site-packages/spacy_transformers/pipeline/__init__.py in <module>()
      1 from .textcat import TransformersTextCategorizer  # noqa
      2 from .tok2vec import TransformersTok2Vec  # noqa
----> 3 from .wordpiecer import TransformersWordPiecer  # noqa

/home/ai/.local/lib/python3.6/site-packages/spacy_transformers/pipeline/wordpiecer.py in <module>()
      1 from spacy.pipeline import Pipe
      2 from spacy.util import minibatch
----> 3 from tokenizations import get_alignments
      4 import re
      5 import numpy

/home/ai/.local/lib/python3.6/site-packages/tokenizations/__init__.py in <module>()
----> 1 from .tokenizations import get_alignments, get_charmap, get_original_spans
      2 
      3 __all__ = ["get_charmap", "get_alignments", "get_original_spans"]

ModuleNotFoundError: No module named 'tokenizations.tokenizations'

**Comment by Bogula** [comment]
Also strange: the incriminated tokenizations folder seems to be almost empty

ai@ai-desktop:~/.local/lib/python3.6/site-packages/tokenizations$ ll
total 20
drwxrwxr-x   3 ai ai 4096 Aug  3 11:20 ./
drwx------ 106 ai ai 4096 Aug  4 16:49 ../
-rw-rw-r--   1 ai ai  142 Aug  3 11:20 __init__.py
-rw-rw-r--   1 ai ai  362 Aug  3 11:20 __init__.pyi
drwxrwxr-x   2 ai ai 4096 Aug  3 11:20 __pycache__/
-rw-rw-r--   1 ai ai    0 Aug  3 11:20 py.typed

**Comment by Bogula** [comment]
Just for your information:

tried to build pytokenizations from source, and got installation errors: 


>pytokenizations-0.6.0-cp36-cp36m-manylinux1_aarch64.whl is not a supported wheel on this platform.

I think tokenization does not work on the aarch64 architecture of Jetson Nano...

Never mind, going back to Colab.

Werner

**Comment by Bogula** [comment]
OK I got it solved, I leave the solution here just for reference.

1. Rebuild tokenizations module from source.

$ git clone https://github.com/tamuhey/tokenizations
$ cd python
$ pip install maturin
$ maturin build

2. pip will fail to install on platform Jetson Nano with the resulting whl - filename.
as a result the .so file will not land in the tokenizations folder 

3. change just the name of the wheel file to pytokenizations-0.6.0-cp36-nono-any.whl
and install with 

sudo pip3 install pytokenizations-0.6.0-cp36-none-any.whl

maybe you have to force-reinstall.

finally you'll find the .so file in the tokenizations folder and it will work.

Thanks and good bye
 Werner Bogula

**Comment by adrianeboyd** [comment]
Thanks for posting your solution!
