### ISSUE TITLE
Can the build script remove it?

### ISSUE THREAD

**Issue by lingvisa** [explosion/spaCy#5852]
To recompile the package, it reports the following if the package has been built before:

```
Cythonizing sources
running build_ext
```
And then it won't rebuild it. I have to manually remove Cythonizing file cythonize.json. Can the setup script automatically remove this file before it builds it?

**Comment by adrianeboyd** [comment]
Hmm, we rebuild all the time without running into this problem. Is there a longer error message? Which branch(es) are you typically building? Can you show the exact steps you're using?

**Comment by lingvisa** [comment]
I typically download from the source https://github.com/explosion/spaCy.git and build it. I slightly changed the requirements.txt and specify the whole project's dependencies by doing this:

# Our libraries
```
../jieba-weibo
../nlu-weibo

cymem>=2.0.2,<2.1.0
preshed>=3.0.2,<3.1.0
thinc==7.4.1
blis>=0.4.0,<0.5.0
murmurhash>=0.28.0,<1.1.0
wasabi>=0.4.0,<1.1.0
srsly>=0.1.0,<1.1.0
catalogue>=0.0.7,<1.1.0
```

These are my own additions:
.```
./jieba-weibo
../nlu-weibo
```
This error message doesn't always occur. I will look into it further next time when it happens.

**Comment by lingvisa** [comment]
I am on a ubutn 16.04 and git cloned a fresh copy of spacy. After I ran "python setup.py build_ext --inplace" and ran it again, it  reports:
```
Cythonizing sources
running build_ext
```

After I manually remvove the 'cythonize.json ' I can rebuild it with the same command above. Is this expected? Or it should automatically remove the 'cythonize.json ' file whenever the command above is executed?

**Comment by svlandeg** [comment]
I think this is the normal behaviour? The build script checks for changes, and if there aren't any, doesn't do anything. I think that's fine?

If you'd go and change a `.pyx` file after you've compiled the first time, it should definitely notice that and rebuild just that one module. This basically means that we're not all the time rebuilding the Cython files when we're making small changes in the code.
