### ISSUE TITLE
Noun chunks not being updated appropriately according to multiple sentences in paragraph

### ISSUE THREAD

**Issue by thefirebanks** [explosion/spaCy#5853]
## How to reproduce the behaviour

Hello! First of all, this awesome package! I am trying to do 2 things: 
- Divide a string into sentences
- Get the `noun_chunks` of each sentence

I am aiming to do this in a variety of languages, but primarily experimenting with English, Spanish and Portuguese. 

**Issue 1**: With the Spanish model, I get the following behavior:

- Sentence 1:  En resúmen AR es un servicio que auxilia los tecnicos de campo a obtener ayuda en la atención de casos     complejos o que necesite de un soporte de un especialista.
Noun chunks:  [AR, un servicio, los tecnicos, campo, ayuda, la atención, casos, complejos, un soporte, un especialista]

- Sentence 2:  Se puede con eso utilizar del smartphone para compartir de manera segura la imagen del device permitindo que se haga notaciones en la pantalla facilitando el reparo.
Noun chunks:  [AR, un servicio, los tecnicos, campo, ayuda, la atención, casos, complejos, un soporte]

As you can see, the noun chunks for sentence 2 seem to be referring to the first sentence, as if when I call `sentence.noun_chunks` I would still be referring to the past sentence. 

<img width="1734" alt="image" src="https://user-images.githubusercontent.com/31460539/89092012-f7733600-d362-11ea-82c8-89a8cc80297e.png">

**Issue 2:** With the Portuguese model, I get the following sentence (same code as above only with the portuguese model `pt_core_news_sm` loaded: 

- Sentence 1: Qual é o link para o estudo de Forrester sobre MVS em Portugues?
noun chunks: [[]]

- Sentence 2: Aproveite a leitura e compartilhe com seus clientes.
noun chunks: [[]]

Am I doing something wrong or is this expected behavior? Maybe because it's a different language? In English things seem to be working relatively well. Thank you very much!

## Your Environment

* Operating System: MacOS Catalina 10.15.5
* Python Version Used: 3.7
* spaCy Version Used:  2.3.2
* Environment Information:

**Comment by adrianeboyd** [comment]
Thanks for the report, this does look like a bug for Spanish. We'll look into it!

Not all languages have an implemented `noun_chunks` method and there isn't one yet for Portuguese. Since it relies on UD POS tags and dependencies, it's possible that once the Spanish `noun_chunks` is fixed, you can adapt it easily to also work for Portuguese, since I would guess that Portuguese noun chunks are quite similar to Spanish noun chunks.
