### ISSUE TITLE
pos_ tag of linking "be" verbs should be "VERB" not "AUX"

### ISSUE THREAD

**Issue by lawbothood** [explosion/spaCy#5856]
From [this](https://github.com/explosion/spaCy/issues/1113), it appears that spaCy used to tag linking "be" verbs as "VERB" but it now tags them as "AUX" but "AUX" without "VERB" doesn't look right. 

```
>>> import spacy
>>> print(spacy.__version__)
2.3.2
>>> nlp = spacy.load("en_core_web_sm")
>>> doc = nlp("It is good")
>>> 
>>> for token in doc:
...     print(token.text, token.pos_, token.dep_)
... 
It PRON nsubj
is AUX ROOT
good ADJ acomp
>>> doc = nlp("It is getting better")
>>> 
>>> for token in doc:
...     print(token.text, token.pos_, token.dep_)
... 
It PRON nsubj
is AUX aux
getting VERB ROOT
better ADJ acomp
>>> doc = nlp("It looks good")
>>> 
>>> for token in doc:
...     print(token.text, token.pos_, token.dep_)    
... 
It PRON nsubj
looks VERB ROOT
good ADJ acomp
>>> doc = nlp('Today is Monday')
>>> for token in doc:
...     print(token.text, token.pos_, token.dep_)
... 
Today NOUN nsubj
is AUX ROOT
Monday PROPN attr
```
It shouldn't be too difficult to correct this as dep_ clearly shows them as "ROOT". 

## Your Environment

* Operating System: Darwin 19.6.0
* Python Version Used: 3.8.5
* spaCy Version Used: 2.3.2
* Environment Information: en_core_web_sm

**Comment by adrianeboyd** [comment]
Hi, thanks for the report! The POS tags come from a mapping from PTB tags, which don't distinguish AUX vs. VERB, so the current models aren't going to be able to get this right all the time. The intention is to follow this table: https://universaldependencies.org/tagset-conversion/en-penn-uposf.html, but it looks like some additional morphology exceptions are setting the POS to `AUX` for forms of `to be`, which is something that should be corrected. We will look into it!

When the tagger does the mapping it doesn't rely on any annotation outside of tags (your pipeline may or may not contain a parser), but you're right that a post-processing component run after a tagger and a parser should have enough information to handle most of these cases.

**Comment by RafaelWO** [comment]
Any updates on this one? I also just stumbled across the issue.

**Comment by adrianeboyd** [comment]
We added some additional rules to the `attribute_ruler` that try to set the POS for `to be` correctly. It's `VERB` by default and a few rules look for cases where it should be `AUX` based on the dependency tree. If there's no parser, then the rules don't apply and it stays `VERB`. If the dependency tree is wrong, it may also end up with the wrong POS.

According to the UD guidelines, copulas remain `AUX`: https://universaldependencies.org/u/pos/AUX_.html

You can modify the rules if you'd like a different behavior. Look at `nlp.get_pipe("attribute_ruler").patterns`.

Checking for `AUX` or `VERB` should work.
