### ISSUE TITLE
POS tagging not working 

### ISSUE THREAD

**Issue by epratheeban** [explosion/spaCy#586]
Hi,

I recently updated spaCy 
```
In [33]: spacy.about.__version__
Out[33]: '1.1.2'
```
I trying to get pos tags using `.tag_` attribute . But it doesn't print anything. 
```
In [9]: newdata = "So if a photon is directed through a plane with two slits in it and either slit is observed, it will not go through both slits."

In [10]: from spacy.en import English

In [11]: nlp = English()

In [15]: for token in nlp(newdata):
    print(token,token.tag_,token.pos_)
   ....:
So
if
a
photon
is
directed
through
a
plane
with
two
slits
in
it
and
either
slit
is
observed
,
it
will
not
go
through
both
slits
.
```
Is this a bug in new version ? Because I used to achieve POS tag in the old version.

**Comment by honnibal** [comment]
Hi,

I think the data is not installed for you. Do

```python

python -m spacy.en.download
```

**Comment by epratheeban** [comment]
It worked. Thanks. 
Quick question about citing. How to cite spaCy NER and pos tagging in a paper. Is there any benchmark evaluations available  ?

**Comment by honnibal** [comment]
I would just footnote with the library version and url for the citation.
