### ISSUE TITLE
Can't load trained word vectors for new language model

### ISSUE THREAD

**Issue by jamalainm** [explosion/spaCy#5862]
## How to reproduce the behaviour

Thank you for your time! I hope I'm not just being a bonehead!

After slightly modifying [train_word_vectors.py](https://github.com/explosion/spaCy/blob/master/bin/train_word_vectors.py) to fit my custom model and texts, I get no error messages, and the model is saved.

I'm not sure how exactly I'm supposed to load the model, though:

`>>>  nlp_latin = spacy.load('tmp/la_vectors_phi')`

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/inalja/PythonProjects/spaCy/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/home/inalja/PythonProjects/spaCy/spacy/util.py", line 172, in load_model
    return load_model_from_path(Path(name), **overrides)
  File "/home/inalja/PythonProjects/spaCy/spacy/util.py", line 198, in load_model_from_path
    meta = get_model_meta(model_path)
  File "/home/inalja/PythonProjects/spaCy/spacy/util.py", line 253, in get_model_meta
    raise IOError(Errors.E053.format(path=meta_path))
OSError: [E053] Could not read meta.json from tmp/la_vectors_phi/meta.json

I'm sure there's a lot I'm missing, and I understand that I'm not creating a meta.json and that the product of train_word_vectors.py is not a directory; I'm just trying to follow the process outlined on the [Adding Languages docs](https://spacy.io/usage/adding-languages).
## Your Environment

* Operating System: Debian GNU/Linux 10 (buster)
* Python Version Used: 3.7.8
* spaCy Version Used: 2.3.2
* Environment Information: Not sure what to put here, but [this is a link to the repository](https://github.com/jamalainm/Spatiale) and the model produced in tmp/.

**Comment by adrianeboyd** [comment]
The output here is a vectors file, not a spacy model. I think it's going to be in a binary gensim format (but I haven't used gensim in a while), which `spacy` can't process directly, either. I think you probably want to modify the script to use `model.wv.save_word2vec_format` instead.

Once you have the plaintext word2vec format, the next step is to use `spacy init-model` to load those these vectors into a new model, which can be loaded with `spacy.load()`. It's not required by default, but it's a very good idea to also specify a unique name for the set of vectors with `--vectors-name`.

**Comment by jamalainm** [comment]
That worked perfectly! Thanks so much for your quick and concise assessment!
