### ISSUE TITLE
Found some potential code quality issues

### ISSUE THREAD

**Issue by pnijhara** [explosion/spaCy#5864]
I forked this repo around a week ago and ran DeepSource analysis on it and found some interesting things that you would appreciate.

Some interesting issues found in the source code:
- [(Bug risk) Dangerous default argument in functions](https://deepsource.io/gh/pnijhara/spaCy/issue/PYL-W0102/)
- This issue can be automatically fixed by DeepSource: [Autofix](https://deepsource.io/gh/pnijhara/spaCy/autofix/5eab5722-15fb-46bf-8250-bac99f18a5d4/) (and it's [PR on GitHub](https://github.com/pnijhara/spaCy/pull/1))
- [(Performance) Unnecessary comprehension](https://deepsource.io/gh/pnijhara/spaCy/issue/PTC-W0016/)
- [(Performance) Built-in function `len()` used as condition](https://deepsource.io/gh/pnijhara/spaCy/issue/PYL-C1801/)
- [(Anti-Pattern) Module imported but unused](https://deepsource.io/gh/pnijhara/spaCy/issue/PYL-W0611/)

You can find a detailed description and fixes for some of them [here](https://deepsource.io/gh/pnijhara/spaCy/issues/?category=recommended)

Please let me know what issues you'd like to focus on fixing and I'd be happy to take a look into it. Also, you can choose to hide certain types of issues too (if you wish to ignore them or you believe it is a false positive or made intentionally). I'd also be happy to send a patch with the DeepSource configuration file with the required fixes.

You can find the required configuration file for DeepSource [here](https://github.com/pnijhara/spaCy/blob/master/.deepsource.toml).

**Comment by honnibal** [comment]
Hi @pnijhara , 

Thanks for running this, it's good to run a variety of static checks periodically.

> Dangerous default arguments

We've decided to use this style in the codebase as it's better than alternatives. We simply accept that we have to be vigilant against that type of bug, but it's better than complicating the types.

> Unnecessary comprehension

We do this deliberately in tests, as it makes the test output more informative if the condition fails.

> Built-in `len()` as condition

This is more of a style point. I'm okay with assuming that types will return an integer value for `len()`, and so I wouldn't consider this an error.

> Module import

These happen sometimes from merges. We generally identify them with flake8, so we don't need a more complex tool like deep source for it.
