### ISSUE TITLE
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

### ISSUE THREAD

**Issue by mkw18** [explosion/spaCy#5897]
```
import kindred

trainCorpus = kindred.bionlpst.load('2016-BB3-event-train')
devCorpus = kindred.bionlpst.load('2016-BB3-event-dev')
predictionCorpus = devCorpus.clone()
predictionCorpus.removeRelations()
classifier = kindred.RelationClassifier()
classifier.train(trainCorpus)
classifier.predict(predictionCorpus)
f1score = kindred.evaluate(devCorpus, predictionCorpus, metric='f1score')
```
When I try to run the code above, I get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\SC\Anaconda3\lib\site-packages\kindred\RelationClassifier.py", line 76, in train
    parser = kindred.Parser(model=self.model)
  File "C:\Users\SC\Anaconda3\lib\site-packages\kindred\Parser.py", line 33, in __init__
    Parser._models[model] = spacy.load(model, disable=['ner'])
  File "C:\Users\SC\Anaconda3\lib\site-packages\spacy\__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "C:\Users\SC\Anaconda3\lib\site-packages\spacy\util.py", line 175, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

How can I solve this problem?
## Your Environment

* Operating System: Windows10
* Python Version Used: python3.7.4
* spaCy Version Used: 2.3.2
* kindred Version Used: 2.7.1
* Environment Information:

**Comment by arditoibryan** [comment]
Hi, I tried to run the code from Google Colab:

```
!pip install kindred
!pip install spacy

import kindred

trainCorpus = kindred.bionlpst.load('2016-BB3-event-train')
devCorpus = kindred.bionlpst.load('2016-BB3-event-dev')
predictionCorpus = devCorpus.clone()
predictionCorpus.removeRelations()
classifier = kindred.RelationClassifier()
classifier.train(trainCorpus)
classifier.predict(predictionCorpus)
f1score = kindred.evaluate(devCorpus, predictionCorpus, metric='f1score')

f1score
0.49800796812749004
```

I don't get any error

**Comment by mkw18** [comment]
Thank you! Maybe I can try to install it again.

**Comment by svlandeg** [comment]
Did you install an English spaCy model as outlined [here](https://pypi.org/project/kindred/)? 
If you keep running into issues - can you try installing everything from scratch in a new virtual environment?
