### ISSUE TITLE
ERROR: kindred 2.7.1 requires sphinx==1.5.5, but you'll have sphinx 3.1.2 which is incompatible.

### ISSUE THREAD

**Issue by mkw18** [explosion/spaCy#5898]
## How to reproduce the problem

I used following command to install kindred:
```bash
pip install kindred
```
However, I encountered this error:
```bash
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

numpydoc 0.9.1 requires sphinx>=1.6.5, but you'll have sphinx 1.5.5 which is incompatible.
```
Then I tried this command:
```bash
pip install --use-feature=2020-resolver numpydoc
```
and the Sphinx-3.1.2 was automatically installed and the Sphinx 1.5.5 was uninstalled. But then I got this error:
```bash
ERROR: kindred 2.7.1 requires sphinx==1.5.5, but you'll have sphinx 3.1.2 which is incompatible.
```
How can I make kindred and numpydoc compatible?
## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by honnibal** [comment]
This seems like a dependency issue within kindred rather than spaCy. We don't depend on Sphinx. So I think you'll need to ask the kindred developers.
