### ISSUE TITLE
IMDB Database yields zero results

### ISSUE THREAD

**Issue by wpeguero** [explosion/spaCy#5899]
I tried copying the example and running the load_data function to understand how to process the data before training it on my own text classifier, but whenever I try to load the raw IMDB data I get an empty list.
## Which page or section is this issue related to?

URL: https://spacy.io/usage/training#basics
SOURCE: https://github.com/explosion/spaCy/blob/master/website/docs/usage/training.md

**Comment by svlandeg** [comment]
Could you post some example script to illustrate your issue? Because I can't replicate the problem with spaCy 2.3.2.

When I run this code:
```
import thinc
    import random

    def load_data(limit=0, split=0.8):
        """Load data from the IMDB dataset."""
        # Partition off part of the train data for evaluation
        train_data, _ = thinc.extra.datasets.imdb()
        random.shuffle(train_data)
        train_data = train_data[-limit:]
        texts, labels = zip(*train_data)
        cats = [{"POSITIVE": bool(y), "NEGATIVE": not bool(y)} for y in labels]
        split = int(len(train_data) * split)
        return (texts[:split], cats[:split]), (texts[split:], cats[split:])

    (train_texts, train_cats), (dev_texts, dev_cats) = load_data()
    print("len train_texts", len(train_texts))
    print("len train_cats", len(train_cats))
    print("len dev_texts", len(dev_texts))
    print("len dev_cats", len(dev_cats))
```
I get 
```
len train_texts 20000
len train_cats 20000
len dev_texts 5000
len dev_cats 5000
```
You can also limit the amount of data you want, by putting `load_data(limit=100)` and then you'd get this:
```
len train_texts 80
len train_cats 80
len dev_texts 20
len dev_cats 20
```

If you keep running into issues, can you post a minimal code snippet that illustrates where/how you can get an empty list?

**Comment by wpeguero** [comment]
Traceback (most recent call last):
  File "path-to-file/test.py", line 15, in <module>
    (train_texts, train_cats), (dev_texts, dev_cats) = load_data()
  File "path-to-file/test.py", line 7, in load_data
    train_data, _ = thinc.extra.datasets.imdb()
AttributeError: module 'thinc' has no attribute 'extra'

I tried copying the code you had placed above and running it. I got the error above.

**Comment by svlandeg** [comment]
Which version of spaCy are you running, and which version of Thinc?

**Comment by wpeguero** [comment]
I am running the following version of spaCy and Thinc:
spacy==2.3.2
spacy-lookups-data==0.3.2
thinc==7.4.1

**Comment by svlandeg** [comment]
Hm, that's weird. 7.4.1 definitely has that function at that location, see here: https://github.com/explosion/thinc/blob/v7.4.1/thinc/extra/datasets.py

**Comment by wpeguero** [comment]
It might be an issue, on my end. I'll check and see what is going on. I thought that at first that dataset had been deprecated since it used to not give me any values.

Thank you for the help though, I really appreciate this. 😄

**Comment by svlandeg** [comment]
Sure thing! I also get the feeling that something might be off on your local setup/install, because I can't reproduce this and I've been using the IMDB dataset for various tests internally...
Let us know how you go!
