### ISSUE TITLE
fine tune pretrained word vectors of de_core_news_md with custom ones

### ISSUE THREAD

**Issue by spaceisonlynoise** [explosion/spaCy#5901]
hello everyone,
i would like to fine tune the de_core_news_md model by adding custom vectors.
i dont want to just load custom vectors in a new model. i want to keep using the pretrained word vectors but add my custom ones to them. 
How would I do this?
Any help is greatly appreciated, thanks in advance!

## Your Environment
spaCy version    2.3.0                         
Location         /usr/local/lib/python3.7/site-packages/spacy
Platform         Darwin-18.7.0-x86_64-i386-64bit
Python version   3.7.7

**Comment by honnibal** [comment]
You probably won't be able to do this. You could add new vectors for specific words using the `nlp.vocab.set_vector` method, but unless the new vectors are within the same _vector space_, you'll destroy the predictions from the pretrained components.

As a quick test, take a look at how similar the vectors are between the ones you want to load and the current vectors in the package for some common words (`die`, `und`, `ist`, etc). If your vectors are very different on these common words, you won't be able to load them, as you'll change the input features for the components too much.

You could add your own vectors to the `de_core_news_sm` model, but if you want to have new vectors as features in the components, you'll have to retrain the models.

**Comment by spaceisonlynoise** [comment]
thank you so much @honnibal ! 
just to clarify: I shouldn't add new vectors to the`de_core_news_md` model unless they are very similar.
and another question: if i add the new vectors to `de_core_news_sm `, which has no built-in vectors, wouldn't that mean that the model would only use my custom vectors? and how would i retrain it?

**Comment by honnibal** [comment]
>  just to clarify: I shouldn't add new vectors to thede_core_news_md model unless they are very similar.

You should really just expect that you can't add the new vectors, it's not really worth checking to see that they are very similar because it's really unlikely that they will be, unless they were trained together. But if you do want to look into it, the similarity check is a way you can get a better sense of what will happen.

> and another question: if i add the new vectors to de_core_news_sm , which has no built-in vectors, wouldn't that mean that the model would only use my custom vectors? 

Yes that's correct.

> and how would i retrain it?

You would need to prepare the training corpus for your tasks, and then use the `spacy train` command. See here: https://spacy.io/usage/training

**Comment by fcggamou** [comment]
I was also looking for a way to do this.
What I ended up doing is creating a new spacy model from scratch using a fasttext set of vectors, which can be downloaded like this (e.g. for spanish):

`!wget https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.es.300.vec.gz`

The you can create the spacy model using those vectors like this:
`!python -m spacy init-model es model --vectors-loc cc.es.300.vec.gz`

Also, [fasttext provides vectors for words that are out of vocabulary](https://fasttext.cc/docs/en/unsupervised-tutorial.html) (check the section "Printing word vectors"), and I wanted to use these on my model as well, so I added them to the spacy model using the set_vector method, like this:

`
# Load the fasttext model
import fasttext
from fasttext import util
util.download_model('es', if_exists='ignore') 
ft = fasttext.load_model('cc.es.300.bin')

# Load the spacy model created from the fasttext vectors
nlp = spacy.load('model')

# Iterate over my text dataset
for text in df['Text']:
  doc = nlp(text)
  for word in doc:
    # If there's not a vector for this word, add it using fasttext's vector
    if not word.has_vector:
      print(word.text)      
      nlp.vocab.set_vector(word.text, ft.get_word_vector(word.text))
`

Hope this helps, and hope someone more experienced can validate that what I'm doing actually makes sense.

**Comment by spaceisonlynoise** [comment]
@honnibal thank you for your answer!
@fcggamou thank you for your answer!
I think I will try to combine the two proposed answers and will keep you updated on how it goes.
Thanks again!
