### ISSUE TITLE
loading and saving models (parsers)

### ISSUE THREAD

**Issue by tang0mani** [explosion/spaCy#5903]
## How to reproduce the behaviour

I was testing spacy examples, specifically `Training a custom parser for chat intent semantics.`
I saved the model into output_dir, and when I loaded it, it seemed to have degraded the model's performance to an extent. 
For example, initial test right after training, which aligns with the expected results:
`find me the cheapest gym near work
[('find', 'ROOT', 'find'), ('cheapest', 'QUALITY', 'gym'), ('gym', 'PLACE', 'find'), ('near', 'ATTRIBUTE', 'gym'), ('work', 'LOCATION', 'near')]`
test after loading model:
`find me the cheapest gym near work
[('find', 'TIME', 'me'), ('me', 'ROOT', 'the'), ('the', 'ROOT', 'cheapest'), ('cheapest', 'TIME', 'gym'), ('gym', 'ROOT', 'gym'), ('near', 'PRODUCT', 'work'), ('work', 'ROOT', 'work')]`

## Your Environment

* Python Version Used: 3.7.3
* spaCy Version Used: 2.1.0

**Comment by honnibal** [comment]
Could you try again with the latest version? It might be fixed.
