### ISSUE TITLE
Can’t install on CPU without AVX-512

### ISSUE THREAD

**Issue by Mazdaywik** [explosion/spaCy#5905]
## How to reproduce the problem
I type:
```
pip3 install spacy
```

```bash
C:\Users\Mazdaywik\AppData\Local\Temp\pip-install-78nor8q5\blis\blis\_src\kernels\skx\3\bli_dgemm_skx_asm_16x12_l2.c:542:28: error: unknown register name 'zmm0' in asm
            "r13", "r14", "r15", "zmm0", "zmm1", "zmm2", "zmm3", "zmm4", "zmm5",
                                 ^
      .\frame\include\bli_x86_asm_macros.h:102:22: note: expanded from macro 'END_ASM'
      #define END_ASM(...) __VA_ARGS__ );
                           ^
      1 error generated.
```
Full stderr and stdout:
* [stderr.txt](https://github.com/explosion/spaCy/files/5053015/stderr.txt)
* [stdout.txt](https://github.com/explosion/spaCy/files/5053016/stdout.txt)

## Your Environment
* Operating System: Windows 10 19041.388
* Python Version Used: Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:20:19) [MSC v.1925 32 bit (Intel)] on win32
* spaCy Version Used:
* Environment Information: CPU Intel® Core™ i5-2430M, **don’t support AVX-512.** On computer there are installed Visual Studio 2013, Visual Studio 2019, gcc version 4.8.1, clang version 3.7.0.

**Comment by honnibal** [comment]
Thanks for the report. I need to do some work on the underlying Blis library to improve this.

**Comment by Mazdaywik** [comment]
Thank you! It works on Python x64!
