### ISSUE TITLE
source of word probability

### ISSUE THREAD

**Issue by rajhans** [explosion/spaCy#591]
Hello

Can you share the name of the corpus you use to compute the word probabilities? Also is it possible to set custom word probabilities? 

I am thinking of using word prob in lieu of IDF and just want to know the source of the data. I am guessing your probabilities are computed from raw term counts which is not exactly compatible with counts of documents containing the term, but that's a separate issue.

Thanks!

**Comment by honnibal** [comment]
The probabilities derive from Good-Turing smoothed counts estimated on the Reddit Comment Corpus.

You can override the `.prob` estimates by iterating over the vocabulary, and assigning to the lexemes:

```
for lex in nlp.vocab:
    lex.prob = your_probs[lex.orth]
```

**Comment by rajhans** [comment]
Great... thanks!
