### ISSUE TITLE
Rule-base sentence splitting is broken for Armenian and Amharic, and broken on questions for Arabic and Hebrew

### ISSUE THREAD

**Issue by bittlingmayer** [explosion/spaCy#5911]
## How to reproduce the behaviour
```
import spacy
from spacy.lang.hy import Armenian
from spacy.lang.el import Greek
from spacy.lang.ar import Arabic

nlp = Armenian()  # just the language with no model
sentencizer = nlp.create_pipe("sentencizer")
nlp.add_pipe(sentencizer)
doc = nlp('Ինչպե՞ս ես:  Սա թեստ է:  123')
for sent in doc.sents:
    print(sent.text)
```

Expected:
> ['Ինչպե՞ս ես:', 'Սա թեստ է:', '123']

Actual:
> ['Ինչպե՞ս ես:  Սա թեստ է:  123']

Similar for Greek `;` and Arabic `؟`, which are used only at the end of question sentences.

## Background

Armenian (`hy`) does not normally use the ASCII full-stop `.` as sentence-final punctuation, it uses its own `:`, even for questions and exclamations.  (As you can see in https://github.com/explosion/spaCy/tree/master/spacy/lang/hy/examples.py).

Note that `:` is *not* the ASCII colon, but rather a distinct Unicode character with a slightly different glyph.

Armenian does use the ASCII full-stop `.` for abbreviations.  So in that sense, sentence splitting in Armenian is very simple, because, unlike in English and many other languages, the main character used for marking sentence boundaries is used for that purpose only.

This does not affect the languages with similar writing traditions that spaCy supports or could soon support, namely Georgian and Hebrew, as they have fully adopted the generic Latin-style punctuation.

**Comment by honnibal** [comment]
Thanks for the fix!
