### ISSUE TITLE
merge_entities does not set IOB correctly for two consecutive entities

### ISSUE THREAD

**Issue by jsalbr** [explosion/spaCy#5918]
Sorry that I have to report a small issue with merge_entities that I came across.

Problem: If two named entities appear directly adjacent in a sentence and you call merge_entities to merge their tokens, also the entities get merged, because the IOB of the second entity is set to I instead of B.
 
Example: Original Sequence B-I-I-B-I-O-O
Merge entities merges the tokens 0:3 and 3:5 correctly, but the IOB-tags are B-I-O-O and not B-B-O-O.
Thus, doc.ents returns just one entity. See the example below.

```python
import spacy
from spacy.pipeline import merge_entities

nlp = spacy.load('en')
text = "LIfetime Corp said Retirement Housing Corp has accepted."
doc = nlp(text)

# two directly consecutive named entities detected:
# "LIfetime Corp said" and "Retirement Housing Corp"
# the first one is wrong, but that's not the point
for t in doc:
    if t.ent_type_ != '':
        print(f"'{t.text}' {t.ent_iob_} {t.ent_type_} " )
print()

# after merge entities 
doc = merge_entities(doc)
for t in doc:
    if t.ent_type_ != '':
        print(f"'{t.text}' {t.ent_iob_} {t.ent_type_} " )
print()

for e in doc.ents:
    print(f"ents: '{e.text}' {e.label_}" )
```

Output:
```
# before merge:
'LIfetime' B ORG 
'Corp' I ORG 
'said' I ORG 
'Retirement' B ORG 
'Housing' I ORG 
'Corp' I ORG 

# after merge:
'LIfetime Corp said' B ORG 
'Retirement Housing Corp' I ORG 

ents: 'LIfetime Corp said Retirement Housing Corp' ORG
```

So not only the tokens, but also the entities got merged. Expected would be 
```
'LIfetime Corp said' B ORG 
'Retirement Housing Corp' B ORG 
```

* Operating System: Linux
* Python Version Used: 3.8
* spaCy Version Used: 2.3

**Comment by svlandeg** [comment]
Thanks for the report and code sample, that's very useful :-) 

This does look like a bug on first glance - we'll investigate further.

**Comment by jsalbr** [comment]
You're welcome and thanks for having a look at it!Best, Jens-------- Ursprüngliche Nachricht --------Von: Sofie Van Landeghem <notifications@github.com>Datum: So., 16. Aug. 2020, 00:18An: explosion/spaCy <spaCy@noreply.github.com>Cc: Jens Albrecht <jsalbr@gmail.com>, Author <author@noreply.github.com>Betreff: Re: [explosion/spaCy] merge_entities does not set IOB correctly for two consecutive entities (#5918)
Thanks for the report and code sample, that's very useful :-)
This does look like a bug on first glance - we'll investigate further.

**Comment by svlandeg** [comment]
Hm, I'm trying to replicate this but I can't. Below is the code I'm using. It is almost the same as yours, but doesn't rely on a pretrained model, and adds the entities with an `EntityRuler` instead:

```
import spacy
from spacy.pipeline import merge_entities

nlp = English()

patterns = [
    {"label": "ORG", "pattern": "Lifetime Corp said"},
    {"label": "ORG", "pattern": "Retirement Housing Corp"},
]

ruler = EntityRuler(nlp)
ruler.add_patterns(patterns)
nlp.add_pipe(ruler)

text = "Lifetime Corp said Retirement Housing Corp has accepted."
doc = nlp(text)

for t in doc:
    if t.ent_type_ != '':
        print(f"'{t.text}' {t.ent_iob_} {t.ent_type_} ")
print()
for e in doc.ents:
    print(f"ents: '{e.text}' {e.label_}")

print()
print("MERGING")
print()

# after merge entities
doc = merge_entities(doc)
for t in doc:
    if t.ent_type_ != '':
        print(f"'{t.text}' {t.ent_iob_} {t.ent_type_} ")
print()

for e in doc.ents:
    print(f"ents: '{e.text}' {e.label_}")
```
This gives me:
```
'Lifetime' B ORG 
'Corp' I ORG 
'said' I ORG 
'Retirement' B ORG 
'Housing' I ORG 
'Corp' I ORG 

ents: 'Lifetime Corp said' ORG
ents: 'Retirement Housing Corp' ORG

MERGE

'Lifetime Corp said' B ORG 
'Retirement Housing Corp' B ORG 

ents: 'Lifetime Corp said' ORG
ents: 'Retirement Housing Corp' ORG
```

Which seems fine. So I have a few follow-up questions to try and get to the bottom of this:
- Which kind of `en` model are you using? Is it predicting "Lifetime Corp said" as `ORG` wrongly out of the box? Did you retrain it?
- Could you try running my above code on your machine and check the output? If the error really is in `merge_entities`, I'd expect you to see the same problem with my code (even though I don't see the problem)
- Could you try upgrading to spaCy 2.3.2 and see if the problem persists?

**Comment by jsalbr** [comment]
Hi, surprisingly with an entity ruler the problem does not show up, only with the model.

Expected behaviour in my opinion is, however, that the number of entities should not change after calling `merge_entities`, but it does so frequently (e.g. in 5% of the articles in the Reuters corpus).

Here is a sentence that makes problems also in 2.3.2 (not with a ruler, though, only with the model (en_core_web_sm, pretrained))

```
text = """
Digicon Inc said it has completed the previously-announced disposition
of its computer systems division to an investment group led by
Rotan Mosle Inc's Rotan Mosle Technology Partners Ltd affiliate.
"""
```

I attached a small notebook with an updated example of me and a piece of code to produce over 100 such examples in a subset of 2000 articles of the Reuters corpus. The notebook includes all the output.

[Spacy_Merge_Entities_Issue.zip](https://github.com/explosion/spaCy/files/5150485/Spacy_Merge_Entities_Issue.zip)

**Comment by svlandeg** [comment]
Thanks for the additional info! Now I can replicate this :-) 

> Expected behaviour in my opinion is, however, that the number of entities should not change after calling merge_entities, but it does so frequently (e.g. in 5% of the articles in the Reuters corpus).

Definitely! This is a bug and shouldn't happen. I'll look further into it.

**Comment by svlandeg** [comment]
@jsalbr: I think I found and fixed the bug. There was an error in the code that would only hit certain edge cases with a certain type of dependency parse, which is why I couldn't initially replicate this with a blank model without parser. The fix is pretty [straightforward](https://github.com/explosion/spaCy/pull/6005/files#diff-f5bc16d1b6c3cedc53a3d75424a8f33c). If you wish to apply this to your local installation, you'll have to recompile the files though, as the error was in a Cython file. The other option is to wait for the bug release ;-)

**Comment by jsalbr** [comment]
Great, thanks! I can wait for the bug release.
