### ISSUE TITLE
Wrong “latest” versions shown on spacy.io/models/en

### ISSUE THREAD

**Issue by gthb** [explosion/spaCy#5919]
The models pages say the English models have latest version 2.2.5, but versions 2.3.1 of them were released in July, see https://github.com/explosion/spacy-models/releases/tag/en_core_web_sm-2.3.1

## Which page or section is this issue related to?

https://spacy.io/models/en

**Comment by svlandeg** [comment]
Where exactly are you seeing the reference to 2.2.5? When I look at the link you provided, https://spacy.io/models/en, I see: 
![image](https://user-images.githubusercontent.com/8796347/90322507-6fda1980-df55-11ea-8b3c-22187dd1d2a7.png)

**Comment by gthb** [comment]
Hm, that's exactly where I was seeing 2.2.5, but now I see 2.3.1 like you do. Maybe a website caching bug, and I've blown away my browser cache by reloading so now I can't reproduce it?

**Comment by svlandeg** [comment]
Let's assume it was a browser caching thing then indeed ;-)
I'll go ahead and close this.
