### ISSUE TITLE
Allow tokenization of list of words

### ISSUE THREAD

**Issue by Uzay-G** [explosion/spaCy#5922]
Tokenization into a doc only supports the string type for now:

```python3
nlp = spacy.load(<model>)
nlp("a cat walked into a bar")
```

However, especially when treating words that are not specifically linked, it is more direct to call it on a list.

For now, one can for example join the list with spaces and then call tokenization on the returned string.

This is slightly clumsy it would also be slightly more efficient to be able to simply directly call the tokenization on the list.

This is a small change, and if I am missing any context or background info that makes this pr useless, please fill me in! :+1:

Intended feature:

```python3
nlp(["man", "woman", "dog", "pool"])
```

**Comment by graue70** [comment]
As explained in [the docs](https://spacy.io/api/language#pipe) and in [the course](https://course.spacy.io/en/chapter3) (part 13 and 14), this is already possible:

```python
nlp = spacy.load(<model>)
docs = nlp.pipe(["man", "woman", "dog", "pool"])
```
Note that this yields a generator object. If you need the docs in a list, you can follow up by `docs = list(docs)`.

**Comment by Uzay-G** [comment]
oh alright, thanks
