### ISSUE TITLE
How can i save a Spacy model with UMLSEntityLinker added in the pipeline? 

### ISSUE THREAD

**Issue by sachinsingh3107** [explosion/spaCy#5923]
I have been using UMLSEntityLinker for my project and i want to save the spacy model with the linker added in the pipeline.How can i do that?

```
import scispacy
import spacy
# import en_core_sci_sm   #The model we are going to use
from spacy import displacy
from scispacy.abbreviation import AbbreviationDetector
from scispacy.umls_linking import UmlsEntityLinker

nlp = spacy.load('en_core_sci_sm-0.2.5/en_core_sci_sm/en_core_sci_sm-0.2.5')
linker = UmlsEntityLinker(resolve_abbreviations=True)

nlp.add_pipe(linker)

```

**Comment by svlandeg** [comment]
You can find general documentation about spaCy's IO [here](https://spacy.io/usage/saving-loading#models), and you can check whether the loaded `nlp` object has the correct components by inspecting `nlp.pipe_names`.

The `UmlsEntityLinker` is a custom component provided by `scispacy` though, an external plugin not developed by us, so I think the question would be better asked on their issue tracker.
