### ISSUE TITLE
POS Mapping to UD

### ISSUE THREAD

**Issue by chrisjbryant** [explosion/spaCy#593]
Congrats on spacy v1.0!

I just wanted to remind you that the tag_map.json to convert PTB tags to UD tags still doesn't reflect the one on the Stanford website: http://universaldependencies.org/tagset-conversion/en-penn-uposf.html 
C.f. #191 

I believe I've fixed your current version (attached):
[tag_map.txt](https://github.com/explosion/spaCy/files/559982/tag_map.txt)

The only lines that were changed:
"NIL": {"pos": "x"}, 
"PDT": {"pos": "det", "adjtype": "pdt", "prontype": "prn"},
"PRP$": {"pos": "det", "prontype": "prs", "poss": "poss"},
"WDT": {"pos": "det", "prontype": "int|rel"},
"WP": {"pos": "pron", "prontype": "int|rel"},
"WP$": {"pos": "det", "poss": "poss", "prontype": "int|rel"},
"AFX": {"pos": "x"}, - repeated, so deleted.
"HYPH": {"pos": "punct"}, - repeated, so deleted.

**Comment by christian-storm** [comment]
Is there a reason this is still outstanding, e.g., don't want to introduce a breaking change?  Do you disagree with the UD, e.g., WDT -> DET? Spacy confusingly maps WDT -> ADJ even though the description reads 'wh-determiner'?

Happy Holidays!

**Comment by honnibal** [comment]
Sorry for not attending to this sooner. It got left out of the 2.0 changes, and then I kept glancing over the issue and not seeing that it was very simple. I think I was also worried about backwards compatibility. Will be patched in v2.1.

Fortunately we've steadily got the issue tracker under control, so these sorts of oversights shouldn't occur in future...
