### ISSUE TITLE
EntityRuler fails on case-insensitive match when entity name contains a "."

### ISSUE THREAD

**Issue by OmriPi** [explosion/spaCy#5944]
Hi, I am a long time spaCy user, and I use it a lot for NER tasks.
Specifically I'm using the extremely useful EntityRuler class right now in order to locate entities in a text given to me in a list of companies.
I came across what I believe is a strange bug in the EntityRuler:

When the EntityRuler is set to do case-insensitive matching:

`ruler = EntityRuler(nlp, 'LOWER', patterns=pattern)`

and the entity name happens to be in uppercase letters and contains a "." character, for example in my case:

`FEDERAL EXPRESS INTERNATIONAL INC.`

the entity ruler will not match on the following text:

`"I am an employee of Federal Express International Inc. (\"FEII\"), which is a parcel delivery company."`

despite the ruler being set to 'LOWER' (which is supposed to make it case-insensitive as far as I'm aware).

Removing the "." from the text and the entity results in a successful match.
Additionally, using the entity case as it appears in the text (instead of the given uppercase form) also results in a successful match, without having to remove the "." character.
I believe there is some kind of problem when matching entities containing "." (and possibly other special characters as well, though I didn't check that) using the 'LOWER' attribute of the matcher.
Since the EntityRuler is an essential part of my NER component, this bug constitutes a significant problem for me.
If anyone can recreate and confirm the existence of this bug, and tell me whether I can fix it somehow, I would be very grateful.

Thanks and please keep on doing amazing job with spaCy!
Omri

My Environment:
**spaCy version:** 2.2.3
**Platform:** Windows-10-10.0.19041-SP0
**Python version:** 3.7.6

**Comment by svlandeg** [comment]
Happy to help, I know chasing these little things can be frustrating, it took me a while to figure out what was going on, too!

I think it should work if you use `nlp.tokenizer.add_special_case('inc.', [{ORTH: 'inc.'}])`. Mind the capitalization ;-)
"Inc." by itself is already an exception, so you don't have to add that again.
