### ISSUE TITLE
I can not use GPU to train my own NER model 

### ISSUE THREAD

**Issue by TTThanos** [explosion/spaCy#5950]
## Your Environment

* Operating System: Win 10
* Python Version Used: 3.7.4
* spaCy Version Used: 2.2.4
* Environment Information: running environment: Jupyter notebook, GPU: RTX 2070 Super, CUDA: 10.2

**Hi guys, I try to use my GPU to accelerate my NER training after successfully installed Cupy， Pytorch, and My prefer_gpu() and require_gpu() are both "True", then when I start to train my model, an error occurred.**

```
AttributeError                            Traceback (most recent call last)
<ipython-input-25-137762d06647> in <module>
----> 1 NER_training_func(new_model_name="AUS model_5", output_dir='./Models/Model_AUS_5', n_iter=60,data_to_train=Final_traindata_AUS)

<ipython-input-24-ef43b291b2da> in NER_training_func(model, new_model_name, output_dir, n_iter, data_to_train)
     25 #     ner.add_label("VEGETABLE")
     26     if model is None or reset_weights:
---> 27         optimizer = nlp.begin_training()
     28     else:
     29         optimizer = nlp.resume_training()

~\Anaconda3\lib\site-packages\spacy\language.py in begin_training(self, get_gold_tuples, sgd, component_cfg, **cfg)
    627                     pipeline=self.pipeline,
    628                     sgd=self._optimizer,
--> 629                     **kwargs
    630                 )
    631         return self._optimizer

nn_parser.pyx in spacy.syntax.nn_parser.Parser.begin_training()

_parser_model.pyx in spacy.syntax._parser_model.ParserModel.begin_training()

~\Anaconda3\lib\site-packages\thinc\check.py in checked_function(wrapped, instance, args, kwargs)
    154                     raise ExpectedTypeError(check, ["Callable"])
    155                 check(arg_id, fix_args, kwargs)
--> 156         return wrapped(*args, **kwargs)
    157 
    158     def arg_check_adder(func):

~\Anaconda3\lib\site-packages\thinc\neural\_classes\model.py in begin_training(self, train_X, train_y, **trainer_cfg)
    120     def begin_training(self, train_X, train_y=None, **trainer_cfg):
    121         for hook in self.on_data_hooks:
--> 122             hook(self, train_X, train_y)
    123         return self.Trainer(self, **trainer_cfg)
    124 

~\Anaconda3\lib\site-packages\spacy\_ml.py in <lambda>(model, X, y)
    149 
    150 @describe.on_data(
--> 151     _set_dimensions_if_needed, lambda model, X, y: model.init_weights(model)
    152 )
    153 @describe.attributes(

~\Anaconda3\lib\site-packages\spacy\_ml.py in init_weights(model)
    268         t_i = 0
    269         for t_i in range(t_max):
--> 270             acts1 = predict(ids, tokvecs)
    271             var = model.ops.xp.var(acts1)
    272             mean = model.ops.xp.mean(acts1)

~\Anaconda3\lib\site-packages\spacy\_ml.py in predict(ids, tokvecs)
    254                 (hiddens.shape[0] * model.nF, model.nO * model.nP)
    255             )
--> 256             model.ops.scatter_add(vectors, ids.flatten(), hiddens)
    257             vectors = vectors.reshape((vectors.shape[0], model.nO, model.nP))
    258             vectors += model.b

ops.pyx in thinc.neural.ops.CupyOps.scatter_add()

AttributeError: module 'cupy' has no attribute 'scatter_add'
```

**What should I do to fix this problem, I have tried reinstall spaCy and Cupy, it did not work, and if this problem can not be solved now, then how should I change into CPU training mode, since spaCy automatically tries to use my GPU to train....** 

**Package version check:**
CUDA 10.2:
 nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:32:27_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.2, V10.2.89

Cupy correspond to CUDA version
$ pip install cupy-cuda102
Requirement already satisfied: cupy-cuda102 in c:\users\ttthanos\anaconda3\lib\site-packages (8.0.0b5)
Requirement already satisfied: fastrlock>=0.3 in c:\users\ttthanos\anaconda3\lib\site-packages (from cupy-cuda102) (0.4)
Requirement already satisfied: numpy>=1.15 in c:\users\ttthanos\anaconda3\lib\site-packages (from cupy-cuda102) (1.16.5)

Spacy version:
$ python -m spacy info

============================== Info about spaCy ==============================

spaCy version    2.2.4

Location         C:\Users\TTThanos\Anaconda3\lib\site-packages\spacy
Platform         Windows-10-10.0.18362-SP0
Python version   3.7.4
Models

**Comment by Mistobaan** [comment]
wrong/incompatible cupy version
> `AttributeError: module 'cupy' has no attribute 'scatter_add'`

**Comment by svlandeg** [comment]
Could you double check which version of `cupy` is present in your environment? If you installed an older version of spaCy (2.2.4) with `pip install spacy[cuda]`, you might not have gotten the correct version. Could you try reinstalling `cupy-cuda102` (directly, not via spaCy)?

**Comment by svlandeg** [comment]
> how should I change into CPU training mode, since spaCy automatically tries to use my GPU to train....**

The `train` CLI command should use CPU by default, or you could explicitely set `-g -1`

**Comment by TTThanos** [comment]
> Could you double check which version of `cupy` is present in your environment? If you installed an older version of spaCy (2.2.4) with `pip install spacy[cuda]`, you might not have gotten the correct version. Could you try reinstalling `cupy-cuda102` (directly, not via spaCy)?

When I found this error happened, I search for the reason, someone said just like what you recommend. However, I tried to uninstall Cupy afterwards and reinstall Cupy using `pip install cupy-cuda102`, it still doesn't work.

**Comment by TTThanos** [comment]
> wrong/incompatible cupy version
> 
> > `AttributeError: module 'cupy' has no attribute 'scatter_add'`

Actually, no. I added some "package check" result now, you can see that CUDA, Cupy, and spaCy do not conflict with each other.

**Comment by adrianeboyd** [comment]
I think the problem in 2.2.4 is that it was missing an upper version pin for cupy and then there were some breaking changes in cupy v8. Don't use the option `spacy[cuda-102]` (which picks the wrong version) but instead install `cupy` directly with:

```
pip install "cupy-cuda102<8.0.0"
```

If `cupy` is installed `spacy` will detect it automatically.
