### ISSUE TITLE
Maintain a list in the docs of the languages supported by spaCy

### ISSUE THREAD

**Issue by eshansingh** [explosion/spaCy#598]
As said in the title, I think we should maintain a list of the languages that are supported by spaCy in the docs. Right now, it's very easy to determine by other means that spaCy supports English and German, but later, when more languages are added, I think it's a good idea to have a central list. Moreover, people can simply link to this page in their own project's docs.

I'm willing to make a PR for this, I just need some input on where to put the page.

**Comment by ines** [comment]
Good point – now that I'm looking at the site and GitHub again, it should definitely be mentioned more explicitly that spaCy currently supports German and English, that we're planning to add more languages in the future and that you can also add your own (a tutorial for that is in the works, see #562).

I'll definitely add the languages to the list of features and think about a good way of presenting this in the docs. Maybe it could even be its own page, after "Facts & Figures". With more info and a features table, something like this:

| Language | Token | SBD | Lemma | POS | NER | Dep | Vector | Sentiment |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| English `en` | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ⛔️ |
| German `de` | ✅ | ✅ | ⛔️ | ✅ | ✅ | ✅ | ✅ | ⛔️ |

What do you think? I can add this to the site, that's no problem.

**Comment by eshansingh** [comment]
Sorry for not checking in and a lot of thanks, @ines!
