### ISSUE TITLE
Incorrect scores evalution

### ISSUE THREAD

**Issue by moniquebm** [explosion/spaCy#5981]
## How to reproduce the behaviour

```
i = 0

scorer = Scorer()
with jsonlines.open(self.arquivo_validaco) as reader:
    for obj in reader:
        texto = obj['text']
        text_entities = obj['labels']
        doc_gold_text = self.nlp.make_doc(texto)
        gold = GoldParse(doc_gold_text, entities=text_entities)
        pred_value = self.preds[i]
        scorer.score(pred_value, gold)
print(scorer.scores['ents_per_type'])
```

## Info about spaCy

* **spaCy version:** 2.3.2
* **Platform:** Windows-10-10.0.19041-SP0
* **Python version:** 3.8.3
* **Models:** de, en

I'm using the Portuguese model fine-tuned with a new entity type.

For a particular text, "gold" object shows the following:

gold.ner[256:260] = ['B-ORG', 'I-ORG', 'I-ORG', 'L-ORG']

And "pred_value" shows:

pred_value.ents[14].label_ = 'ORG'
pred_value.ents[14].start = 256
pred_value.ents[14].end = 260

So, this particular prediction was correct.

However:

scorer.scores['ents_per_type']['ORG'] = {'p': 0.0, 'r': 0.0, 'f': 0.0}

This is one particular sample - several other texts in the dataset have ORG entities correctly identified, but Scorer always reports {'p': 0.0, 'r': 0.0, 'f': 0.0} for ORG.  The same problem occurs for another entity type, but doesn't occur for the other two.

How can this behaviour be explained?

**Comment by adrianeboyd** [comment]
I think you're accidentally creating a `GoldParse` with no entity annotation in these lines below:

>         text_entities = []       
>         gold = GoldParse(doc_gold_text, entities=text_entities)

**Comment by moniquebm** [comment]
Hi @adrianeboyd 

In fact, the snippet was wrong but I've just corrected it (the original code is longer and I had put a reduced version).

So the problem is the same:

gold.ner[256:260] = ['B-ORG', 'I-ORG', 'I-ORG', 'L-ORG']

And "pred_value" shows:

pred_value.ents[14].label_ = 'ORG'
pred_value.ents[14].start = 256
pred_value.ents[14].end = 260

"pred_values" is consistent with "gold".

Any ideas?

**Comment by adrianeboyd** [comment]
If you can provide a minimal working example including all the data for one example that we can run, we can see if we can replicate the bug on our end.

I suspect it's a problem with the format of the entity annotation provided to `GoldParse`, but without more details it's hard to help. You can create a toy example or replace the tokens in your text with something like `xx x xxxxx` to anonymize the data while preserving the offsets if that would easier.
