### ISSUE TITLE
spaCy Version is incompatible

### ISSUE THREAD

**Issue by Mohammedzuhair** [explosion/spaCy#5983]
UserWarning: [W031] Model 'en_training' (0.0.0) requires spaCy v2.1 and is incompatible with the current spaCy version (2.3.2). This may lead to unexpected results or runtime errors. To resolve this, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)

spaCy version    2.3.2
Platform         Windows-10
Python version   3.7.9

**Comment by svlandeg** [comment]
I'm not sure I can add more information than the custom warning is already giving ;-)
It looks like you trained a model with 2.1, but it's not compatible with 2.3.2 anymore. So either you'll have to downgrade spaCy to 2.1, or you'll have to retrain your model with 2.3.2.
