### ISSUE TITLE
[E167] Unknown morphological feature: 'Person'  (2313063860588076218) when training a model with a tag map

### ISSUE THREAD

**Issue by ttasovac** [explosion/spaCy#6019]
Training a model without a tag map works as expected. 

Adding a tag map (https://github.com/BCDH/spacy-serbian-pipeline/blob/master/sr/tag_map.py) and referencing it in https://github.com/BCDH/spacy-serbian-pipeline/blob/master/sr/__init__.py, leads to:

```
⚠ Aborting and saving the final best model. Encountered exception:
[E167] Unknown morphological feature: 'Person' (2313063860588076218). This can
happen if the tagger was trained with a different set of morphological features.
If you're using a pretrained model, make sure that your models are up to date:
python -m spacy validate
```
This issue and the above suggested solution have been discussed before (for instance: https://github.com/huggingface/neuralcoref/issues/206). But my case is different because I am not using a pretrained model, I'm training my own.

I'll be grateful for any tips on how to fix this.

## How to reproduce the behaviour

`python3 -m spacy train sr models/sr sr_training_data/sr_set-ud-train.json sr_training_data/sr_set-ud-dev.json -n 1`

The training data and everything else can be found here: https://github.com/BCDH/spacy-serbian-pipeline 

## Your Environment

* **spaCy version:** 2.3.2
* **Platform:** Darwin-19.6.0-x86_64-i386-64bit
* **Python version:** 3.7.7

**Comment by ttasovac** [comment]
Thanks a lot for the explanation, @adrianeboyd.

After changing the values of Person to strings, I'm noticing the same error being thrown for `Gender[psor]` and `Number[psor]` which are UD tags for possessor's gender and number, which is, in some languages, a feature of possessive adjectives and pronouns having two genders and two numbers (one for the object possessed, and one for the person possessing them). 

The values there are the same as in "regular" Gender and Number tags (i.e. no need to convert numbers to strings or something like that), but you can sometimes have two possessor's genders, for instance: 

`"Gender":"Neut", "Gender[psor]":"Masc,Neut"`

I wonder if there a way to keep these in v2 or would I have to get rid of them altogether for the time being?

**Comment by adrianeboyd** [comment]
In v2 there's a fixed list of support morph features and values, so you if you see this error, it's easiest to remove those features. Multiple values for the same feature like `"Masc,Neut"` aren't supported, either. Looking at the code, I think it can parse the non-standard version "Masc|Neut" but it only takes the first value rather than both. Unless you really need the morphological features for v2, it might be easier to just work with a tag map that only maps to `POS`, and wait for v3 for the morphology.

**Comment by ttasovac** [comment]
Got it. Thanks a million for your help!
