### ISSUE TITLE
Memory leak when NLP results are passed out to Jupyter

### ISSUE THREAD

**Issue by courtarro** [explosion/spaCy#6030]
## How to reproduce the behavior

1. Create a single cell in a Jupyter notebook. Put this line of code in it:

        spacy.load('en_core_web_lg')

2. Run the cell
3. Observe that `<spacy.lang.en.English at 0x0123456789AB>` is displayed in the cell output
4. Review the memory usage by the Python kernel
5. Run the cell again
6. Review the memory usage by the Python kernel and note that it has gone up considerably
7. Each time you run the cell you can see that memory usage goes up and keeps going up

Now we can review what happens if we do NOT pass the output to Jupyter. Now add `None` to the end of the cell to suppress displaying the NLP output in Jupyter:

    spacy.load('en_core_web_lg')
    None

Observe that memory usage does NOT increase if you run the cell multiple times. I hypothesize that Jupyter is maintaining a reference to the spaCy output in such a way that spaCy does not realize it can garbage collect that data. Maybe this is a Jupyter bug, but it seems much more pronounced with spaCy than with other libraries I've used, though that may just be because spaCy's reference tree includes the large model data, which gets reloaded each time.

Here is a workaround:

    from IPython.display import display
    display(spacy.load('en_core_web_lg'))

This displays the output but does not trigger the memory leak. Of course it also means that the "output" does not live in the cell's "output" field, which causes a slight difference in the user experience. But at least it works.

Additional testing shows that this problem occurs if ANY spaCy data is passed as Jupyter cell output: simply viewing the `nlp.pipeline` is enough to create a reference that prevents garbage collection.

## Your Environment

* **spaCy version:** 2.3.2
* **Platform:** Linux-5.4.0-42-generic-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.7.5
* **ipykernel version:** 5.2.1
* **Jupyter Notebook version:** 4.6.3

**Comment by svlandeg** [comment]
I'm closing this for now, as I'm not sure there's any action item on our end.
