### ISSUE TITLE
Problem using ja_core_news_sm (ContextualVersionConflict sortedcontainers)

### ISSUE THREAD

**Issue by japoveda10** [explosion/spaCy#6031]
Hello,

I am facing a problem with the `ja_core_news_sm` model. This is the Google Colab notebook that shows the error: https://colab.research.google.com/drive/169tk9gfnhZZdC-16iMiGs2xdmXb4ldj_?usp=sharing

In summary, I obtain the following error:
"ContextualVersionConflict: (sortedcontainers 2.2.2 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('sortedcontainers~=2.1.0'), {'sudachipy'})"

Can you help me please?

Thank you.

**Comment by adrianeboyd** [comment]
The trick seems to be to restart the runtime after installing `ja_core_news_sm`. So run the first two cells, restart the runtime, and then run again (it will just say the requirements are satisfied and won't reinstall anything).

**Comment by japoveda10** [comment]
Hello @adrianeboyd,

Thank you for your help!
