### ISSUE TITLE
German model lemma and pos inconsistency

### ISSUE THREAD

**Issue by Bobdad1** [explosion/spaCy#6032]
Using the model `de_core_news_lg`, I noticed that certain verb tokens can be mislemmatised as if they were nouns if they happen to share the same spelling. To show what I mean:

```
doc = nlp('1935 tritt Bonhoeffer der Bekennenden Kirche bei.')
tritt = doc[1]
print(tritt.pos_)
--> 'VERB'
print(tritt.lemma_)
--> 'tritt'
```

Apparently, the model correctly identifies the pos tag, but when it comes to lemmatising, it seems to mistake the verb **treten** for the noun **Tritt**.

**Comment by adrianeboyd** [comment]
In spacy v2 German is using an extremely low-tech lookup lemmatizer that doesn't know anything about the POS or context around the token. There's one entry for `tritt` and that's the lemma you get for `tritt` in any context. The particular lookup table also has some questionable / inconsistent entries, so the German lemmatizer performance is unfortunately just not great overall at this point.

We're working on a rule-based German lemmatizer for spacy v3 that will hopefully be a major improvement. For spacy v2, you may be better off looking for another tool that does a better job for lemmatization.
