### ISSUE TITLE
Trimming NER model for production

### ISSUE THREAD

**Issue by fcggamou** [explosion/spaCy#6038]
Hi, I'm trying to reduce the size of a trained NER model to be used in production. I only need to use the NER, and as far as I can see I can safely remove the 'tagger' and 'parser' pipes of the model. 
Can I also safely remove the 'vocab'? The model still works after doing so, but I'm wondering if it can affect the results; as far as I can see it doesn't, but it seems counter-intuitive to me. Doesn't the model need the vectors to work properly?

Thanks.

## Your Environment
* **spaCy version:** 2.3.1
* **Platform:** Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.6.9

**Comment by adrianeboyd** [comment]
You can safely remove the tagger and the parser, but you do always need the vocab. I'm not sure how you tried to remove the vocab, but if it was really removed entirely from the model, you wouldn't be able to load it at all, so I'm not sure what happened? In any case, keep the vocab.

You may already be doing this, but if not: you can also reduce the size of the model by resizing the vectors before training. For example, in the `md` provided models, the vectors are resized from ~500K for the original vectors (in `lg`) to 20K with a relatively small drop in performance (obviously evaluate this carefully for your own tasks).

**Comment by fcggamou** [comment]
Thanks Adriane; indeed I tried again and I could not make it work without the vocab, sorry for the confusion.

I will carefully try your vectors resize suggestion.

Thanks,
Fede.
