### ISSUE TITLE
Vocab loads with very small number of tokens

### ISSUE THREAD

**Issue by sbp-dev** [explosion/spaCy#6056]
## How to reproduce the behaviour
I used spaCy version 2.0.16 before, recently updated to 2.3.2. In the older version, when I used to load "en_core_web_md", I used to get close to 13M tokens. For the new version, I get just 489. Tried installing through both pip and conda with same results. Attaching my conda env file for reproduceability.
Code:
`import spacy  
print(spacy.__version__)  
nlp = spacy.load("en_core_web_md")  
print(len(nlp.vocab))`

Attaching output for comparison. Is this an expected behavior?
![Spacy_2_3_2](https://user-images.githubusercontent.com/54526452/92989443-16ccb980-f4f2-11ea-909a-f00c8915a6c0.png)

## Info about spaCy

* **spaCy version:** 2.3.2
* **Platform:** Windows-10-10.0.18362-SP0
* **Python version:** 3.7.7
* **Models:** en

* **Conda env details:** [environment.zip](https://github.com/explosion/spaCy/files/5212334/environment.zip)

**Comment by adrianeboyd** [comment]
Yes, this was a change in v2.3, see the three sections starting with "No preloaded vocab" here: https://spacy.io/usage/v2-3#migrating
