### ISSUE TITLE
[E102] Can't merge non-disjoint spans

### ISSUE THREAD

**Issue by simonschoe** [explosion/spaCy#6073]
I feel my issue is related to #5393, in my case occurring with German text.

## How to reproduce the behaviour
```
import spacy
import de_core_news_md
#load the German NLP spacy model
nlp = spacy.load('de_core_news_md')

merge_nps = nlp.create_pipe("merge_noun_chunks")
nlp.add_pipe(merge_nps)

texts = ["Weil Deutschlands Topkonzerne bestens aufgestellt sind, hält der\nAufwärtstrend in diesem Jahr an, sagen die vom Handelsblatt befragten\nKapitalmarktexperten."]

nlp_pipeline = nlp.pipe(texts, disable=[], batch_size = 20) 
for doc in nlp_pipeline:
    lemma = [token.lemma_.lower() for token in doc]
```

## Your Environment

* **spaCy version:** 2.3.2
* **Platform:** Windows-10-10.0.18362-SP0
* **Python version:** 3.8.5

## Error Message
`ValueError: [E102] Can't merge non-disjoint spans. 'Deutschlands' is already part of tokens to merge. If you want to find the longest non-overlapping spans, you can use the util.filter_spans helper: https://spacy.io/api/top-level#util.filter_spans`

**Comment by adrianeboyd** [comment]
Thanks for the report! I can replicate the error and it does look related to the earlier issue. It looks like the German noun chunk iterator wasn't modified in that earlier fix, but it may require different modifications anyway. We will take a look...
