### ISSUE TITLE
French models under LGPL or LGPLLR?

### ISSUE THREAD

**Issue by ajorg-aws** [explosion/spaCy#6079]
I found #1865, which suggests that the `LGPL` license declared on the French models might actually be [LGPLLR](https://spdx.org/licenses/LGPLLR.html) or more likely the reduced (missing several conditions) LGPLLR [from the Universal Dependencies repo](https://github.com/UniversalDependencies/UD_French-Sequoia/blob/master/LICENSE.txt), but the models page instead links to [LGPL-3.0](https://www.gnu.org/licenses/lgpl.html) which is a very different license.

Can you help us know under what license the French models are distributed?

**Comment by honnibal** [comment]
Thanks for pointing this out, that's a distinction we weren't aware of.

Our intention is not to impose additional restrictions in addition to the licensing of the source data. So I think we'll be able to update the license to LGPLLR for future releases.

**Comment by svlandeg** [comment]
This is fixed in the meantime: https://nightly.spacy.io/models/fr
Thanks again for pointing this out!
