### ISSUE TITLE
Implement __version__ at the base of the package (PEP 396)

### ISSUE THREAD

**Issue by halfak** [explosion/spaCy#608]
[PEP 396](https://www.python.org/dev/peps/pep-0396/) states that 
> When a module (or package) includes a version number, the version SHOULD be available in the __version__ attribute.

Spacy is currently non-standard in that the `__version__` variable under `spacy.about.__version__` rather than expected `spacy.__version__`.

**Comment by honnibal** [comment]
This was done to make it easier to import the `__version__` symbol from other modules in the package, to assist with code/model compatibility constraints. I'll import the symbol into the `__init__`, to make it available.

**Comment by halfak** [comment]
Great!  Solution seems very reasonable.  Thanks.
