### ISSUE TITLE
How can I get the vector of dependency path type?

### ISSUE THREAD

**Issue by Feilouce** [explosion/spaCy#6080]
## Feature description

Hi，

I want to get a vector representation of the extracted dependencies type, is there a  interface for this?

Or can you tell me which function in the code is doing dependency parser? 

Thanks!

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
If so, we will tag it as [`project idea`](https://github.com/explosion/spaCy/labels/project%20idea) so other users can take it on.

**Comment by adrianeboyd** [comment]
Hi, I'm not sure exactly what you're asking. Can you explain a bit more or give an example?

The current base parser class (used for both dependency parsing and NER with different transition systems) is here:

https://github.com/explosion/spaCy/blob/a26f864ed3c227fab1d2a506e27cb4b5b5d831d2/spacy/syntax/nn_parser.pyx

Most of the parser code is in the same directory, `spacy/syntax`. The dependency parser component is defined here:

https://github.com/explosion/spaCy/blob/a26f864ed3c227fab1d2a506e27cb4b5b5d831d2/spacy/pipeline/pipes.pyx#L1092-L1139
