### ISSUE TITLE
Adding entites to spacy doc object using BERT's offsets

### ISSUE THREAD

**Issue by ud2195** [explosion/spaCy#6081]
Is there any way to add entities to a spacy doc object using BERT's offsets ? Problem is my whole pipeline is spacy dependent and i am using the latest PUBMEDBERT for which spacy doesnt provide support.

So at times the offsets of entities given by pubmedbert dont result into a valid SPAN for spacy as the tokenization is completely different.

what work have i done till now to solve my problem ? I made a custom tokenizer by asking spacy to split on punctuation, similar to bert but there are certain cases wherein i just cant make a rule. for example:-

```
text = '''assessment
Exdtve age-rel mclr degn, left eye, with actv chrdl neovas
Mar-10-2020
assessment'''

```
Pubmedbert predicted 13:17 to be an entity i.e. dtve but on adding the span as entity in spacy doc object it results NONE as it is not a valid span.

```
span = doc.char_span(row['start'], row['end'], row['ent'])
doc.ents = list(doc.ents) + [span]
TypeError: object of type 'NoneType' has no len()
```
Consider row['start'] to be 13, row['end'] to be 17 and row['ent'] to be label

how can i solve this problem ? is there anyway i can just add entities in spacy doc object using starting and ending offset given by pubmedbert

would really appreciate any help on this, Thank you.

**Comment by mefrem** [comment]
Hi ud2195. I don't have anything super helpful other than to point out that we both submitted issues for different reasons but that seem to get at similar desires for functionality (my issue here: https://github.com/explosion/spaCy/issues/6071).

Just for your benefit I thought I'd share it, in case one gets resolved.

**Comment by ud2195** [comment]
Hi mefrem, Thanks for mentioning your issue here. I have added my comment on your issue. Please do have a look and let me know if it solves your problem.

**Comment by adrianeboyd** [comment]
This is more of a general usage question, so let's discuss on SO: https://stackoverflow.com/a/63956838/461847
