### ISSUE TITLE
CLI commands "train" and "evaluate" use different names for "GPU to use" argument

### ISSUE THREAD

**Issue by chopeen** [explosion/spaCy#6082]
Long version of argument `-g` is `--use-gpu` for one command and `--gpu-id` for the other.

I will submit a PR to unify them, but which one should be used?

## Info about spaCy

* **spaCy version:** 2.3.2
* **Platform:** Linux-4.15.0-112-generic-x86_64-with-glibc2.10
* **Python version:** 3.8.5

**Comment by svlandeg** [comment]
Hi @chopeen, thanks for the report and attention to detail ;-)

The current `master` branch will probably only be used for small bugfix releases for v2.x. I don't think we want to introduce changes that will break people's scripts at this point.

On the `develop` branch, where we're working on v3.x, I noticed these parameters are already unified: they both use `use_gpu`. So I think that should be fine, and it's probably not worth your trouble to submit a PR ;-)
