### ISSUE TITLE
Load multiple models concurrently from single spacy instance

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#6088]
## Feature description
Is it possible to add support for loading multiple models into memory at the same time?

For example, store the models into a dictionary

	dataPath = Path('data')
	set_data_path(dataPath)
	
	dirs = getSubDirs('models')
	for i in dirs:
		modelname = i.name
		modelPath = Path(os.join('models', modelPath))
	
		models[modelname] = spacy.load(modelPath)

Then in a webservice you can call an api endpoint to run your text against whichever model you want without having to reload them each time, or create separate services to host each model.

**Comment by adrianeboyd** [comment]
I think this is outside the scope of what the `spacy` library itself should support. It would be up to users to decide how to load and manage multiple models, given the needs of their particular applications.
