### ISSUE TITLE
Add reference/explanation for BILOU

### ISSUE THREAD

**Issue by hobofan** [explosion/spaCy#609]
As someone with a lack of academic NLP background, one hurdle while trying to train a custom named entity recognizer was finding out what BILOU stands for. A simple google search for "BILOU" yields nothing relevant, and most other terms I tried don't either.

A reference to a definition of BILOU at the relevant places in the docs would be very helpful, and a link to a layman's introduction would, of course, be even more awesome :wink: 

What I was finally able to find (for anyone stumbling upon this issue):
- http://www.anthology.aclweb.org/S/S14/S14-2.pdf#page=636
- https://stackoverflow.com/questions/17116446/what-do-the-bilou-tags-mean-in-named-entity-recognition

**Comment by honnibal** [comment]
Agreed, thanks!

**Comment by ines** [comment]
Thanks! 👍 Added this issue to the list of topics for the NER workflow to make sure we don't forget. (Also closing this one to keep the discussion in one place.)
