### ISSUE TITLE
Would you add `camphr` to website?

### ISSUE THREAD

**Issue by tamuhey** [explosion/spaCy#6095]
Hi, I published [camphr](https://github.com/PKSHATechnology-Research/camphr) in 6 months ago, and I've just noticed that [Contributing.md](https://github.com/explosion/spaCy/blob/master/CONTRIBUTING.md#publishing-spacy-extensions-and-plugins) says I should open an issue about it to request my library for [the website](https://spacy.io/universe#extensions).
Would you add my library to the website?

## Which page or section is this issue related to?

https://spacy.io/universe#extensions

**Comment by adrianeboyd** [comment]
Hi, you can submit a PR modifying this file to add `camphr`: https://github.com/explosion/spaCy/tree/master/website/meta/universe.json

You can just add an entry with the right details (don't forget the `category`) at the top of the resources list.
