### ISSUE TITLE
Incorrect sentence segmentation for German sentence

### ISSUE THREAD

**Issue by f11r** [explosion/spaCy#611]
The sentence 'Alternative Heilmethoden sollte er kennen.' is (incorrectly) split into the sentences 'Alternative' and 'Heilmethoden sollte er kennen.'.

~~~
import spacy
nlp = spacy.load('de')
for sent in nlp('Alternative Heilmethoden sollte er kennen.').sents:
    print(sent)
~~~
~~~
Alternative
Heilmethoden sollte er kennen.
~~~

* **spaCy Version Used:** tested with `0.101.0` and `1.2.0`

**Comment by ines** [comment]
This problem will be fixed with the next data release. Closing this issue to keep this topic in one place (see #725).
