### ISSUE TITLE
Unable to load Vocabulary of a trained NER model

### ISSUE THREAD

**Issue by ud2195** [explosion/spaCy#6115]
I want to load the Vocabulary part of my NER model, However i am unable to do so

Code-
```
from spacy.vocab import Vocab
vocab = Vocab().from_disk('/xxx/model-83k/vocab')

```
Error-

```
Traceback (most recent call last):

  File "<ipython-input-146-9e215644756b>", line 1, in <module>
    vocab = Vocab().from_disk('/xxx/model-83k/vocab')

  File "vocab.pyx", line 464, in spacy.vocab.Vocab.from_disk

  File "strings.pyx", line 244, in spacy.strings.StringStore.from_disk

  File "/yyy/miniconda3/lib/python3.6/site-packages/srsly/_json_api.py", line 52, in read_json
    return ujson.load(f)

ValueError: Expected object or value
```

`spacy_version==2.2.4`

**Comment by adrianeboyd** [comment]
Hmm, it seems to be having trouble reading `vocab/strings.json`, which is a very simple file that just contains a list of strings in JSON format. Check that this file is present in `vocab/` and that you can load it with:

```python
import srsly
strings = srsly.read_json("vocab/strings.json")
```

If you run into errors here, open `vocab/strings.json` with a text editor to see if anything looks unusual. It should look like this (not necessarily with the same strings, this is from `en_core_web_sm`):

```json
[
  "\"\"",
  "#",
  "$",
  "''",
  ",",
  "-LRB-",
  "-RRB-",
  ".",
  ":",
  "ADD",
  "AFX",
  "BES",
  "CC",
  "CD",
  "DT",
  "EX",
  "FW",
  ...
]
```

If it's missing or not just a list of strings, something may have gone wrong when this model was saved to disk.

**Comment by ud2195** [comment]
Hey Adriane, thanks for replying. The issue was in this file only. Encountered some unwanted characters in there. After deleting the same. It loaded perfectly. Hence, closing the issue.
