### ISSUE TITLE
Named Entity Recognition: How to add 2 new classes to existing entities if I have a list of all possible words in txt file?

### ISSUE THREAD

**Issue by KhrystynaKosenko** [explosion/spaCy#612]
Hi, 
I am relatively new to spacy, but i`m wondering how can i add a new entity to already existed?

I have 2 txt files with all words that can belong to the entity, how can I add them to new NER entity and train new model? 
I have seen #187 issue, but still have troubles with how it has to be done.

Thank you for your help

I`m using 
* **Linux Mint 17.2 Rafaela** 
* **Python 2.7.11** 
* **spacy  0.101.0**

**Comment by honnibal** [comment]
This usage page provides some help to start with: https://spacy.io/docs/usage/entity-recognition

There's further discussion on the ongoing questions around this in #773. Closing this so we can keep the discussion in one place.
