### ISSUE TITLE
Feature Request-ish: Consider adding the semi-colon as a default INFIX for the English tokenizer

### ISSUE THREAD

**Issue by stevegoldman** [explosion/spaCy#6126]
I'd argue that a semi-colon in the middle of some English string is always a good place to split.  Just as you have the comma as both SUFFIX and INFIX by default, I'd add the semi-colon.

I noticed this behavior when doing tokenization of list items separated by semi-colons.  With no space after the semi-colon, the whole mess got tokenized as a single token.

Thanks.

**Comment by stevegoldman** [comment]
Example:

```
from spacy.lang.en import English
nlp=English()
tokenizer=nlp.Defaults.create_tokenizer(nlp)
doc=tokenizer('hydrochloric acid; water; picric acid')
print([t for t in doc])
```
[hydrochloric, acid, ;, water, ;, picric, acid] - Yay!

```
doc=tokenizer('hydrochloric acid;water;picric acid')
print([t for t in doc])
```
[hydrochloric, acid;water;picric, acid] - Sad!

**Comment by svlandeg** [comment]
> I'd argue that a semi-colon in the middle of some English string is always a good place to split.

I'm not sure I agree with this. If I recall correctly, biomedical literature for instance does have entities which contain a `;`.  I'm sure there may be other cases. Also, changing the default tokenization rules in spaCy has a great effect on many other things, including trained models and other people's scripts.

If you're sure that the `;` in your texts should always be split upon, you could modify this behaviour in your own scripts, cf https://spacy.io/usage/linguistic-features#native-tokenizer-additions. I hope that works for you?

**Comment by stevegoldman** [comment]
That works for me.  Thanks for your response!

**Comment by svlandeg** [comment]
I'll go ahead and close then :-)
