### ISSUE TITLE
Tags in TAG_MAP not being found in debug-data

### ISSUE THREAD

**Issue by erip** [explosion/spaCy#6129]
## How to reproduce the behaviour

1. Add tags from Korean UD to `spacy/lang/ko/tag_map.py`
2. Build spaCy from source
3. debug data:

```sh
(spacy-ko) [erip@blah spacy-ko]$ python -m spacy debug-data ko korean-json/train.json korean-json/dev.json --verbose | grep "not found" | head -n5
✘ Label 'ncpa+ncn' not found in tag map for language 'ko'
✘ Label 'ncpa+ncn+jcm' not found in tag map for language 'ko'
✘ Label 'ncpa+jxt' not found in tag map for language 'ko'
✘ Label 'mag' not found in tag map for language 'ko'
✘ Label 'ncn' not found in tag map for language 'ko'
$
$
(spacy-ko) [erip@blah spacy-ko]$ python
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> from spacy.lang.ko import tag_map
>>> all(tag in tag_map.TAG_MAP for tag in ['ncpa+ncn', 'ncpa+ncn+jcm', 'ncpa+jxt', 'mag', 'ncn'])
True
```

## Info about spaCy

* **spaCy version:** 2.3.2 (master)
* **Platform:** Linux-3.10.0-1127.8.2.el7.x86_64-x86_64-with-centos-7.8.2003-Core
* **Python version:** 3.6.12

**Comment by erip** [comment]
And for posterity, my `tag_map.py` looks like...

```python
# encoding: utf8
from __future__ import unicode_literals

from ...symbols import POS, PUNCT, INTJ, X, SYM, ADJ, AUX, ADP, CONJ, NOUN, PRON
from ...symbols import VERB, ADV, PROPN, NUM, DET, PART, CCONJ, SCONJ

TAG_MAP = {
  # J.{1,2} 조사
    "JKS": {POS: ADP},
    "JKC": {POS: ADP},
    # There are a lot...
     "xsn" : {POS: PART},
    "xsv+ecc" : {POS: PART},
    "xsv+ecs" : {POS: PART},
    "XSV+EC" : {POS: VERB},
    "xsv+ecx+px+ep+ef" : {POS: PART},
    "xsv+ep+ecx" : {POS: PART},
    "XSV+EP+ETM" : {POS: VERB},
    "xsv+etm" : {POS: PART},
    "XSV+ETM" : {POS: VERB},
}
```

**Comment by erip** [comment]
Found the issue. In [this code](https://github.com/explosion/spaCy/blob/597bcc629e173dfd87422188dc76a2f1053a9bba/spacy/cli/debug_data.py#L62-L74), the tag map is being replaced with an empty dict because no tag-map is being provided. It seems like the workaround is that L74 should happen in the if-statement after L64.

**Comment by adrianeboyd** [comment]
That does look like a bug, thanks for the report!

We're trying to move away from having the tag maps specified within the library in the language data (since they're corpus-specific and not language-specific) so you don't need a custom spacy install, etc. to manage them, but the library tag map should be the default with `spacy train`, not an empty tag map.

As a workaround, you can use the `--tag-map-path` option with your tag map in JSON format. Unfortunately JSON encoding restrictions make converting the tag map more of a hassle than you'd expect, but it's what we're using internally now for all the provided models. See the example at the very bottom here: https://spacy.io/usage/v2-3. Just replace the model with `spacy.blank("ko")` from your custom spacy install.

**Comment by erip** [comment]
Thanks, @adrianeboyd. I recalled that the there was some movement to move away from coupling corpus-specific tagmaps to langs, so this seems like a good solution. :-) 

In any case, I'm happy to submit a PR with the proposed fix outlined above (which worked for me) if you think it's worth it. I don't know how many 2.3.x releases you anticipate because cutting the 3.x release, so maybe moot - your call.

**Comment by svlandeg** [comment]
Hey @erip, we're definitely going to release at least one more bugfix release for 2.x, since we have a few fixes accumulated on `master` already. I haven't looked at the details of this issue, but if it's a quick fix we'd definitely appreciate the contribution!

**Comment by erip** [comment]
Done, @svlandeg. Hopefully nothing too controversial, but let me know if you would like me to make any changes. 👍

**Comment by svlandeg** [comment]
Thanks! :-)
