### ISSUE TITLE
PT problem install

### ISSUE THREAD

**Issue by ScrimForever** [explosion/spaCy#6144]
## How to reproduce the behaviour
I tried like:

pip install https://github.com/explosion/spacy-models/archive/pt_core_news_lg-3.0.0a0.tar.gz

----
I made download too,  pt_core_news_lg-3.0.0a0.tar.gz , but when i use pip to install, this erro happening 

        ERROR: Command errored out with exit status 1:
     command: /home/scrimfx/Documents/Indra/NovoBot/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-li1eig_4/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-li1eig_4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-nks3xqbk
         cwd: /tmp/pip-req-build-li1eig_4/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-li1eig_4/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

## Your Environment

* Operating System: Ubuntu 18.04
* Python Version Used: 3.6
* spaCy Version Used: 2.2.4
* Environment Information:

**Comment by adrianeboyd** [comment]
Hi, for spacy v2.2.4, please use `python -m spacy download pt_core_web_sm` to download a Portuguese model. There's no `lg` model for v2.2, you'll need to upgrade to v2.3 if you'd like a `md` or `lg` model with vectors.

Sorry that the website accidentally linked to the newest alpha versions that aren't quite ready for release yet, I've temporarily switched it back to the v2.3 versions for now.
