### ISSUE TITLE
Invalid device for GPU usage in pretrain CLI

### ISSUE THREAD

**Issue by LvLs9** [explosion/spaCy#6147]
You have one big mistake in **cli/pretrain.py** in row 128 - by default it use GPU with ID 1
![image](https://user-images.githubusercontent.com/34302242/94256636-c19d9880-ff32-11ea-93b6-b35e621521a4.png)

## How to reproduce the behaviour
`spacy pretrain pretrained.jsonl de_core_news_lg pretrained_output`

## Your Environment
* **spaCy version:** 2.3.2
* **Platform:** Linux-5.3.0-1035-aws-x86_64-with-glibc2.27
* **Python version:** 3.8.5
* Environment Information: Cuda 10.1

## Solution
I think you can just change it to 0 or add plac-flag for selecting GPU-id

**Comment by adrianeboyd** [comment]
Yes, this was an accidental commit. The fix is in #5808.

**Comment by LvLs9** [comment]
Then when it will be in release? I just need to change sources on each machine where I'm doing pretrain :smile:

**Comment by adrianeboyd** [comment]
We don't have a concrete release date planned yet, sorry.

In the meanwhile, you can just make a copy of `spacy/cli/pretrain.py`, change the relative spacy imports to absolute imports, make the gpu id fix, and you should have a standalone script that you can run anywhere you have spacy v2.3.x installed. Or alternatively, you can downgrade to v2.3.1 if you're not using the experimental additions in v2.3.2.
