### ISSUE TITLE
Matcher.remove crashes if {"OP": "!"} token is in any pattern of any rule

### ISSUE THREAD

**Issue by delzac** [explosion/spaCy#6148]
## How to reproduce the behaviour
```
nlp = en_core_web_sm.load()
matcher = Matcher(nlp.vocab)

offending_pattern = [{'OP': '!'}, ]
matcher.add('test-rule', [offending_pattern ])
matcher.add('random-rule', [[{"LOWER": "hi"}]])
assert 'random-rule' in matcher
matcher.remove('random-rule')  # crashes here: "Process finished with exit code -1073741819 (0xC0000005)"
assert 'random-rule' not in matcher

```

When `{"OP": "!"}` is inside any pattern, removing __any__ rules will result in program crashing `"Process finished with exit code -1073741819 (0xC0000005)"`

## Your Environment

* Operating System: Windows 10
* Python Version Used: Python 3.6
* spaCy Version Used: Spacy v2.3.2
* Environment Information: nil

**Comment by adrianeboyd** [comment]
Hi, I can replicate this and we will look into it.
