### ISSUE TITLE
Are german models available for spaCy v3.0 ?

### ISSUE THREAD

**Issue by cibeah** [explosion/spaCy#6166]
Hi ! 

I am working with spaCy from the `develop` branch that I built from source. I would like to download a german model compatible for v3.0, and the documentation from spacy-nightly seems to say that they are available: [https://nightly.spacy.io/models/de](https://nightly.spacy.io/models/de.)
 Yet 
`python -m spacy download de_core_news_md` tries to download the package from [here](https://github.com/explosion/spacy-models/releases/download/de_core_news_md-3.0.0a0/de_core_news_md-3.0.0a0.tar.gz)., where it does no exist. I looked at the releases from the spacy-models repository and it looks like [german models do not have any model to download in their assets.](https://github.com/explosion/spacy-models/releases/tag/de_core_news_md-3.0.0a0). 

So does that mean that german models are actually not available for v3.0 ?
Note: Downloading other v3.0 models worked perfectly.

Thank you very much for your help !

**Comment by adrianeboyd** [comment]
Ah, we should take those down again. We thought we were extremely close to a nightly release, but found some problems with the models (not just with German) in more extended testing and are working on a solution. German will be there when we have an official nightly/alpha release.

**Comment by cibeah** [comment]
Oh I see ! Thank for your answer, I'll stay on v2.0 for now then !
