### ISSUE TITLE
Changing the format of lemma_lookup.json

### ISSUE THREAD

**Issue by jacintodavila** [explosion/spaCy#6169]
## Feature description

This is about modifying the proposed content structure of the lemma_lookup.json  file, of the spacy_lookup_data package, for a new language model for ancient Greek. Instead of requesting the feature, we are actually implementing it as part of the Diogenet project and plan to present it as a new language extension, in due course. The proposed format looks like this:

{
    "́κου": {
        "pron": "ποῦ"
    },
    "́περ": {
        "part": "πέρ"
    },
    "̄καί": {
        "sconj": "καί"
    },
    "̄ὁμοίως": {
        "verb": "ὁμοιόω"
    },
...
    "’χῃ": {
        "noun": "ἠχή"
    },
    "’ω": {
        "noun": "ἠώς"
    }
}

This being a huge file with more than a million entries. The index corresponds to the token being looked up, and the value store a dict with the pos tag and the lemma. That will help us check the lemma that corresponds to that use of the word as that pos relates, which is a very specific need for ancient Greek. 

Unfortunately, we have not been able to test it, as the Lookups objects fails to load the file and does not give any clear indication of errors. 

We need help to test the feature in our lemmatizer and trace the loading process. 

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?

Yes, we do hope so. 

If so, we will tag it as [`project idea`](https://github.com/explosion/spaCy/labels/project%20idea) so other users can take it on.

Please!. 
Regards

**Comment by adrianeboyd** [comment]
To test, try loading it like this:

```python
from spacy import util
filenames = util.registry.lookups.get("grc") # {'lemma_lookup': '/path/to/grc_lemma_lookup.json'}
data = util.load_language_data(filenames["lemma_lookup"])
```

There should be errors if it can't find the entry point for `"grc"` or it can't load the table.

You might want to take a look at how the POS-based lookup lemmatizer is implemented for Polish. The tables are pretty flexible (you just need string keys, which is required by JSON in any case) and you don't necessarily have to put everything in one huge table. Once the tables are loaded you can use them however you want in your custom lemmatizer.

**Comment by jacintodavila** [comment]
Thank you.
