### ISSUE TITLE
textcat model weights are not deterministic even with random.seed

### ISSUE THREAD

**Issue by themrmax** [explosion/spaCy#6177]
I'm trying to write some unit tests for my code and am struggling to make them deterministic. Consider the following example:

```python
import spacy
import random

for _ in range(2):
    spacy.util.fix_random_seed(0)

    model = spacy.load('en_core_web_sm')

    model.add_pipe(model.create_pipe('textcat'))
    model.remove_pipe('parser')
    model.remove_pipe('tagger')

    cat = model.get_pipe('textcat')
    cat.add_label("dog")
    cat.add_label("donut")

    model.begin_training()
    print(model("What even is?").cats)

# output:
# {'dog': 0.527805507183075, 'donut': 0.8244330286979675}
# {'dog': 0.6659842729568481, 'donut': 0.19725579023361206}
```

Looks like maybe a duplicate/regression of https://github.com/explosion/spaCy/issues/3182

## Your Environment

* Operating System: Mac OS 10.15.7
* Python Version Used: 3.7.4
* spaCy Version Used: 2.3.0
* Environment Information: anaconda3

**Comment by adrianeboyd** [comment]
Yes, this is a known (and frustrating!) issue, see #5551. I think this will be fixed in spacy v3. The relevant PR is #5735.

At first glance, I think this wouldn't be too hard to backport to spacy v2, but this hasn't been done yet.

**Comment by svlandeg** [comment]
PR #6218 should fix it for v2. When I run your code, I get:
```
{'dog': 0.5329195857048035, 'donut': 0.5502294301986694}
{'dog': 0.5329195857048035, 'donut': 0.5502294301986694}
```
