### ISSUE TITLE
✘ No compatible model found for 'ja_ginza' (spaCy v2.3.2).

### ISSUE THREAD

**Issue by JSB97** [explosion/spaCy#6189]
I am trying to download ja_ginza from spacy directly. According to ginza docs, it [requires spacy version 2.3.2 or above.](https://github.com/megagonlabs/ginza/blob/develop/requirements.txt). I cannot download the model using the usual commands.

## How to reproduce the problem
spacy download ja_ginza

```bash
✘ No compatible model found for 'ja_ginza' (spaCy v2.3.2).
```

## Your Environment
spaCy version    2.3.2                         
Location         /home/jbennett/.pyenv/versions/Prodigy2/lib/python3.8/site-packages/spacy
Platform         Linux-4.4.0-87-generic-x86_64-with-glibc2.17
Python version   3.8.1

**Comment by svlandeg** [comment]
Hi, this is not a model provided by spaCy, but by the [GiNZA NLP Library](https://github.com/megagonlabs/ginza). I'm not sure how their models are defined or downloaded - perhaps they are included upon install? 

I haven't worked with these models or this library myself yet, so I'm afraid the best place to ask for further help is probably on their issue tracker. Hope you get it resolved soon!
