### ISSUE TITLE
Reading special case tokenization rules from a file

### ISSUE THREAD

**Issue by clairempr** [explosion/spaCy#619]
Thanks for adding the documentation on customizing the tokenizer. I see that there's a way to add special cases to the existing tokenizer, which is what I'd like to do, but I was wondering if there was a simple way to add a number of special cases all in one go by reading them from a file, similar to specials.json. 

Is it easiest to add the the rules one by one with add_special_case as I read them from the file, or is there a better method?

**Comment by honnibal** [comment]
Sorry about the delay replying to this — I think I actually misread this the first time around.

The simple answer is, no, you should just loop over your entries and make successive calls to the `add_special_case` function. In general I think it's better that the API is smaller. Personally I'd rather write loops than look through extra methods in the library :)
