### ISSUE TITLE
Double space in input has an effect on dependency tree

### ISSUE THREAD

**Issue by tsaltena** [explosion/spaCy#621]
When providing Spacy with an input that contains double spaces, it seems to change the result of the parse. See for instance:

[https://demos.explosion.ai/displacy/?text=I%20%20have%20%20already%20generated%20constructs%20%20for%20a%20pilot%20project%20in%20these%20species.&model=en&cpu=1&cph=1]

@honnibal comment on this through Gitter:

```
>>> with nlp.parser.step_through(doc) as state:
...   while not state.is_final:
...     action = state.predict()
...     print(action)
...     state.transition(action)
... 
L-nsubj
S
L-advmod
L-aux
R-dobj
R-prep
S
S
L-compound
L-det
R-pobj
R-prep
S
L-det
R-pobj
D
D
D
D
D
R-punct
```
so. it looks like the token gets attached to the space, and then moved over in post-processing
so there's probably a bug here, possibly.

## Environment
* **Operating System: Debian Jessie 7.5 ** 
* **Python Version Used: Python 3.4.2 ** 
* **spaCy Version Used: 1.2.9**

**Comment by ines** [comment]
Closing this and making #1057 the master issue – work in progress for spaCy v2.0!
