### ISSUE TITLE
Configurable pkuseg model

### ISSUE THREAD

**Issue by lingvisa** [explosion/spaCy#6214]
Spacy 2.3

It seems that the pkuseg used is a small model (32MB), probably the 'web' model. The 'mixed' model is much larger, over 100MB and it works better while I tested on a number of cases.  Although it is documented as 'default' model in Spacy, which is supposed to be the 'mixed' model, it is actually a 32MB model under the tokenizer directory, when I untarred the zh_core_web_lg-2.3.1.tar.gz file. It should be the 'web' model. 

I tried to copy the 'features.pkl' & 'weights.npz' from the mixed model files to overwrite the corresponding two files in zh_core_web_g-2.3.1.tar.gz/zh_core_web_lg/zh_core_web_lg-2.3.1/tokenizer/pkuseg_model/, and then tar zip again, but it reports an model loading error. 

There may be a mistake in packaging the zh_core_web_g-2.3.1.tar.gz and please take a look.

**Comment by adrianeboyd** [comment]
The pkuseg model provided with the spacy `zh` models is a custom model we trained only on OntoNotes. It is slightly worse than the `mixed` model (something like ~1% tokenization accuracy on OntoNotes using spacy's evaluation), but we wanted to be able to distribute the model under an MIT license. The models provided by `pkuseg` are trained on data that is restricted to research/academic use.

The `pkuseg` binary wheels provide the `mixed` model as part of the package under the name `default`, so if you install the binary package with `pip` and run `seg = pkuseg.pkuseg()` or `seg = pkuseg.pkuseg(model_name="default")` you get the `mixed` model with the default user dictionary.

You should be able to replace the `features.pkl` and `weights.npz` with another model if you want, so I'm not sure what went wrong for you here. Test it first by loading the model from the path with `spacy.load()` and once you know it's working as intended, then repackage it. I just tried the method you described, replacing our OntoNotes model with the `news` model, and it seemed to work fine?

**Comment by lingvisa** [comment]
This is what I did to replace the default model in spacy's pkuseg model:

1) text = '采用天然有机成分'
spacy output: ['采用', '天然', '有', '机成', '分']     
pkuseg output : ['采用', '天然', '有机', '成分']       ((not in spacy))
The difference is in the 3rd token.
2) check pkuseg model size:
```
ls -lah ~/.venv/pkuseg/lib/python3.8/site-packages/pkuseg/models/default/
 -rw-r--r--  1 congminmin  staff     0B Oct  6 11:04 __init__.py
drwxr-xr-x  3 congminmin  staff    96B Oct  6 11:04 __pycache__
-rwxr-xr-x  1 congminmin  staff    **73M** Oct  6 11:04 features.pkl
-rwxr-xr-x  1 congminmin  staff   **101M** Oct  6 11:04 weights.npz

```
3) check spacy pkuseg model size:
```
ls -lah ~/.venv/test-spacy/lib/python3.8/site-packages/zh_core_web_lg/zh_core_web_lg-2.3.1/tokenizer/pkuseg_model/
total 122680
drwxr-xr-x  4 congminmin  staff   128B Oct  6 12:06 .
drwxr-xr-x  5 congminmin  staff   160B Oct  6 12:06 ..
-rw-r--r--  1 congminmin  staff    **24M** Jun 17 00:29 features.pkl
-rw-r--r--  1 congminmin  staff    **36M** Jun 17 00:29 weights.npz 

```

4) Replace features.pkl and weights.npz:
cp ~/.venv/pkuseg/lib/python3.8/site-packages/pkuseg/models/default/features.pkl ~/.venv/test-spacy/lib/python3.8/site-packages/zh_core_web_lg/zh_core_web_lg-2.3.1/tokenizer/pkuseg_model/
cp ~/.venv/pkuseg/lib/python3.8/site-packages/pkuseg/models/default/weights.npz ~/.venv/test-spacy/lib/python3.8/site-packages/zh_core_web_lg/zh_core_web_lg-2.3.1/tokenizer/pkuseg_model/

5) Re-test and the new results are the same as the pkuseg model.

Now, my model file is under a directory:
```
ls model-files/zh/
README.txt			zh_core_web_lg-2.3.1.tar.gz
```

I usually install the model this way and it works fine:
`pip install model-files/zh/zh_core_web_lg-2.3.1.tar.gz`

Now, I untar the file:
`tar -xf zh_core_web_lg-2.3.1.tar.gz `

The I copy the two mixed model files to replace the ones in this directory, and create the .gz file again:
`tar -czf zh_core_web_lg-2.3.1.tar.gz zh_core_web_lg-2.3.1`

The problem occurs here when I run the install command again:
```
pip install model-files/zh/zh_core_web_lg-2.3.1.tar.gz
Processing ./model-files/zh/zh_core_web_lg-2.3.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /Users/congminmin/.venv/wbnlu/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/cr/x7st48l55rx8ntr0vxk242vr0000gn/T/pip-req-build-yz6hsoky/setup.py'"'"'; __file__='"'"'/private/var/folders/cr/x7st48l55rx8ntr0vxk242vr0000gn/T/pip-req-build-yz6hsoky/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/cr/x7st48l55rx8ntr0vxk242vr0000gn/T/pip-req-build-yz6hsoky/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/cr/x7st48l55rx8ntr0vxk242vr0000gn/T/pip-req-build-yz6hsoky/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Is that because the .gz is not be created through 'tar' command, but some other way?



```

**Comment by adrianeboyd** [comment]
That's exactly what I did, so I'm not sure what's going on. It's related to the pip package, not the pkuseg model. Compare the directory structure with `tar tf` for both the original model and the new one to make sure that all the subdirectories and filenames are identical? Maybe you accidentally added or removed a top-level subdirectory?

**Comment by lingvisa** [comment]
I repeat it on a linux machine and it has no problem. The problem occurs on my Mac and still looking into it.

**Comment by lingvisa** [comment]
I did another test, just uncompress it, and compress the package back again, and do the pip install command, and it generates this error message. In this case, I didn't replace any files. It seems this command changes something inside the package:

`tar -czf zh_core_web_lg-2.3.1.tar.gz zh_core_web_lg-2.3.1`

**Comment by adrianeboyd** [comment]
Hmm, I also tested in linux, so I'm not sure what's going on. You could try using `spacy package` as an alternative to see if that works more reliably for you. But I don't think this problem is related to spacy or its model packages in the end?

**Comment by lingvisa** [comment]
What do you mean by 'spacy package'?

Also, once the 2 model files are replaced, do I also need to update vocab files, even the vector model (new vocabulary added)? Or the replacement has nothing to do with vocab in terms of the correct working of the tool.  If those are also needed to be updated, perhaps I don't need to bother to update the two files only without updating the whole models.

**Comment by adrianeboyd** [comment]
`spacy package`: https://spacy.io/api/cli#package

You'll probably see a slight degradation in performance if the tokenizer is slightly different, but it should still be usable. If you change it a lot (e.g., you switch to jieba or something like that), the trained model components won't produce anything useful. You don't need to update the vocab, but you might notice that vectors are missing for the new tokens.

For the spacy OntoNotes model vs. `mixed`, I would just try it and see if it helps for your task?

**Comment by lingvisa** [comment]
I am planning to switch to pkuseg from jieba, and need to take care of a few issues.

**Comment by lingvisa** [comment]
The 'spacy package' works better, and I am able to get it work. Thanks.
