### ISSUE TITLE
word boundary condition - split of audio

### ISSUE THREAD

**Issue by Tortoise17** [explosion/spaCy#6215]
## Feature description
<!-- Please describe the feature: 
I am trying to split the audio at the word level boundary instead of silent boundary. Usually Spacy is very smart in recognizing the words and languages. Is there any feature possible to handle such issue. I can provide you the link as example manually done. 

webrtcvad is doing this, but it is splitting at the silence, which has the minimum duration and sometimes it overlaps the actual signal and lot of signal is not possible retrieve at splits. So, if the word boundary with its actual time of start and end is possible?
This is a question and if not possible, this is feature request.

**Comment by svlandeg** [comment]
I'm guessing this issue was meant to be posted on a different library (see also https://github.com/Uberi/speech_recognition/issues/520 and https://github.com/jiaaro/pydub/issues/523). If you have any spaCy-specific questions or bug reports, feel free to open a new issue!
