### ISSUE TITLE
python 3.9 pip install fails (tar.gz instead of .whl)

### ISSUE THREAD

**Issue by NeuroFox** [explosion/spaCy#6228]
## How to reproduce the behaviour

Python 3.9 command
```
py -3.9 -m pip install spacy
```

Python 3.9 output:
```
Downloading spacy-2.3.2.tar.gz (5.9 MB)
Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python /usr/local/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-_x7vz17k/overlay --no-warn-script-location --no-
binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'cython>=0.25' 'cymem>=2.0.2,<2.1.0' 'preshed>=3.0.2,<3.1.0' 'murmurhash>=0.28.0,<1.1.0' thinc==7.4.1
       cwd: None

```

requirements.txt
```
spacy
```

Dockerfile (to reproduce from 0)
```
FROM python:3.9
RUN pip install --upgrade pip

COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install --no-cache-dir -r requirements.txt
```

docker image test
```
docker build --tag spacy-bug-test:1.0 .
```

docker image test output
```
...

Step 5/5 : RUN pip install --no-cache-dir -r requirements.txt
 ---> Running in 750721f1c153
Collecting spacy
  Downloading spacy-2.3.2.tar.gz (5.9 MB)

# and fails too because its .tar.gz

...
```

Python 3.8 command
```
py -3.8 -m pip install spacy
```

Python 3.8 output
```
Downloading spacy-2.3.2-cp38-cp38-manylinux1_x86_64.whl
Here all is ok because its .whl
```

(The very exact moment i change Dockerfile to 3.8 or lower it starts to download wheel and all works)

I suppose that spaCy wheel is not yet ready for python 3.9?

## Your Environment
* Operating System: Linux (docker python 3.9), Windows 10
* Python Version Used: python 3.9
* spaCy Version Used: 2.3.2 and any before
* Environment Information: Clean docker system

I use docker (linux) AND windows 10. Fails same for both. Clean install of python 3.9 (no packages in freeze)

## Possibly related issues

https://github.com/pandas-dev/pandas/issues/32045

**Comment by adrianeboyd** [comment]
There are no python 3.9 wheels yet. We'll build them for upcoming releases, but we typically don't go back to build wheels for earlier releases. Right now, we have to wait a bit for our CI/build infrastructure to support python 3.9 and for our dependencies (numpy is the main one) to publish 3.9 wheels. We plan to have releases for v2 and v3 relatively soon (v2.3.3 and v3.0.0 alpha releases), so there will be updated wheels in time.

**Comment by NeuroFox** [comment]
Perfect. No problems :) Waiting eagerly and wish luck. Thank you for good job

**Comment by DaveSV** [comment]
I have the same error types using W10 and Py3.9 > since package 'wheel' is not installed.
In addition >> error: Microsoft Visual C++ 14.0 is required. (Well, it can be solved easely)

**Comment by svlandeg** [comment]
As both 2.3.4 and 2.3.5 now have wheels for Python 3.9, I think we can close this issue. If there are still issues with installation, feel free to open a new ticket!
