### ISSUE TITLE
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

### ISSUE THREAD

**Issue by WolfgangFahl** [explosion/spaCy#6237]
## How to reproduce the behaviour
run https://github.com/WolfgangFahl/ProceedingsTitleParser/blob/master/tests/test_Spacy.py in Jenkins Continuous integration environment on a Ubuntu 20.04 LTS machine

## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:
```
 python3 -m spacy info --markdown

## Info about spaCy

* **spaCy version:** 2.3.2
* **Platform:** Linux-5.4.0-48-generic-x86_64-with-glibc2.29
* **Python version:** 3.8.5
``` bash
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

**Comment by svlandeg** [comment]
Did you [download](https://spacy.io/models) the model? Could you share the output of `python -m spacy validate`?

**Comment by WolfgangFahl** [comment]
python3 was necessary for the download python was also linke to a python3 version but a different one so it had no effect on 3.8.5

**Comment by WolfgangFahl** [comment]
You might want to give a different error message on load and not rely on the operating system's error message which might be misleading and force people to search for a ticket like this one.

**Comment by svlandeg** [comment]
I'll assume you got it sorted out after going through the documenation and/or reading my reply, so I will close this issue.

**Comment by WolfgangFahl** [comment]
As outlined in my comment i'd really appreciate if spacy would give a different error message so closing this issue is not what represents the needs of users like me that are confused by the OS error message which might have different reasons. It would IMHO be better to immediately give hints on how to solve the problem.

**Comment by svlandeg** [comment]
It is not a default error message. It is a custom error message `E050` defined in https://github.com/explosion/spaCy/blob/master/spacy/errors.py. As you can see from that file, we in fact spend a lot of time and effort writing custom error messages to help people solve errors they may run into. I personally do, however, also expect a minimum level of effort from users - i.e. at least read the minimal installation documents that we've also spent quite a bit of time working on.

And even when they haven't read that - like you obviously didn't - I'm still answering your questions on a Saturday and a Sunday. I wrote you back within the hour on a Saturday evening, to help you get set up with a free, open-source library. So I really don't understand why you feel the need to use this tone. I will not be following up on this thread and will spend my time on users who do appreciate the help.

**Comment by WolfgangFahl** [comment]
Thank you for pointing to https://github.com/explosion/spaCy/blob/master/spacy/errors.py where the error message could be improved. Shall i create a pull request for the improvement?
