### ISSUE TITLE
Parsing POS problem

### ISSUE THREAD

**Issue by ndvbd** [explosion/spaCy#6243]
When I parse the sentence:

**We know that the events in paragraph four lead to a bigger battle.**

I get that the word "**lead**" is a noun instead of a verb. Is there a way to fix that?

**Comment by adrianeboyd** [comment]
See the notes in the top post here about what you can expect from statistical models like the tagger: #3052.

One way to improve it is to fine-tune the model for your data. A very basic intro is here (also check out the more general introduction to model training at the top of this page): https://spacy.io/usage/training#example-train-tagger
