### ISSUE TITLE
PhraseMatcher seems to modify the vocabulary somehow

### ISSUE THREAD

**Issue by sadovnychyi** [explosion/spaCy#626]
```python
import spacy

doc_text = u'Withholding'
doc_bytes = b'\n\x00\x00\x00\x01\x00\x00\x00F\xfc,\xb52\x02'
nlp = spacy.load('en', parser=False, entity=False, tagger=False, matcher=False)
# nlp(doc_text).to_bytes()
matcher = spacy.matcher.PhraseMatcher(nlp.vocab, [
  spacy.tokens.Doc(nlp.vocab, words=['a', 'Indemnitee']),
  spacy.tokens.Doc(nlp.vocab, words=['a', 'Setoff']),
  spacy.tokens.Doc(nlp.vocab, words=['Intercreditor', 'Agreement']),
  spacy.tokens.Doc(nlp.vocab, words=['c', 'Clawback']),
])
doc = spacy.tokens.Doc(nlp.vocab).from_bytes(doc_bytes)
if doc.text != doc_text:
  raise ValueError('wrong document: %s', doc.text)
```

`Witholding` becomes `workbooks`. Does not happens without all of phrases in the matcher presented and if we convert save document into the bytes before. Seems *really* strange for me, have no idea how to narrow this down.

## Your Environment
* **Operating System:**  macOS
* **Python Version Used:** 3.5.2
* **spaCy Version Used:** 1.2.0
* **Environment Information:** NA

**Comment by honnibal** [comment]
Vocabulary modification happens here:

https://github.com/explosion/spaCy/blob/master/spacy/matcher.pyx#L507

Not sure what the best solution will be. Will think about this.

**Comment by honnibal** [comment]
Closing this, because the problem should no longer be relevant for spaCy 2.
