### ISSUE TITLE
Spacy 3.0 - nlp.add_pipe(ruler) failes

### ISSUE THREAD

**Issue by AlexSchmidke** [explosion/spaCy#6265]
Hi,

we are trying to use the EntityRuler with the new spacy nightly version. The Code word using the old spacy version but fails at the nlp.add_pipe(ruler) step using spacy nightly 3.0.

The Code (just the example from the spacy website):

```python
import spacy
from spacy.pipeline import EntityRuler

nlp = spacy.load("en_core_web_trf")
ruler = EntityRuler(nlp)
ruler.add_patterns([{"label": "ORG", "pattern": "Apple"}])
nlp.add_pipe(ruler)
```

The same Code runs with the Old Spacy Version (Using the Old Language Set) but fails with following error using spacy nightly

ValueError: [E966] `nlp.add_pipe` now takes the string name of the registered component factory, not a callable component. Expected string, but got <spacy.pipeline.entityruler.EntityRuler object at 0x7f6237e88640> (name: 'None').

- If you created your component with `nlp.create_pipe('name')`: remove nlp.create_pipe and call `nlp.add_pipe('name')` instead.

- If you passed in a component like `TextCategorizer()`: call `nlp.add_pipe` with the string name instead, e.g. `nlp.add_pipe('textcat')`.

- If you're using a custom component: Add the decorator `@Language.component` (for function components) or `@Language.factory` (for class components / factories) to your custom component and assign it a name, e.g. `@Language.component('your_name')`. You can then run `nlp.add_pipe('your_name')` to add it to the pipeline.

## My Environment
copy-paste the result here.-->
* Operating System: Ubuntu 18.04
* Python Version Used: 3.7
* spaCy Version Used: 3.0
* Environment Information:
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
argon2-cffi               20.1.0           py37h7b6447c_1  
async_generator           1.10             py37h28b3542_0  
attrs                     20.2.0                     py_0  
backcall                  0.2.0                      py_0  
bleach                    3.2.1                      py_0  
blis                      0.7.1                    pypi_0    pypi
boto3                     1.15.18                  pypi_0    pypi
botocore                  1.18.18                  pypi_0    pypi
brotlipy                  0.7.0           py37h7b6447c_1000  
ca-certificates           2020.10.14                    0  
catalogue                 2.0.1                    pypi_0    pypi
certifi                   2020.6.20                py37_0  
cffi                      1.14.3           py37he30daa8_0  
chardet                   3.0.4                 py37_1003  
click                     7.1.2                    pypi_0    pypi
cryptography              3.1.1            py37h1ba5d50_0  
cymem                     2.0.3                    pypi_0    pypi
de-core-news-sm           3.0.0a0                  pypi_0    pypi
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
entrypoints               0.3                      py37_0  
idna                      2.10                       py_0  
importlib-metadata        2.0.0                      py_1  
importlib_metadata        2.0.0                         1  
ipykernel                 5.3.4            py37h5ca1d4c_0  
ipython                   7.18.1           py37h5ca1d4c_0  
ipython_genutils          0.2.0                    py37_0  
jedi                      0.17.2                   py37_0  
jinja2                    2.11.2                     py_0  
jmespath                  0.10.0                   pypi_0    pypi
json5                     0.9.5                      py_0  
jsonschema                3.2.0                      py_2  
jupyter_client            6.1.7                      py_0  
jupyter_core              4.6.3                    py37_0  
jupyterlab                2.2.6                      py_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         1.2.0                      py_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libsodium                 1.0.18               h7b6447c_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
markupsafe                1.1.1            py37h14c3975_1  
mistune                   0.8.4           py37h14c3975_1001  
murmurhash                1.0.2                    pypi_0    pypi
nbclient                  0.5.1                      py_0  
nbconvert                 6.0.7                    py37_0  
nbformat                  5.0.8                      py_0  
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.4.1                      py_0  
notebook                  6.1.4                    py37_0  
numpy                     1.19.2                   pypi_0    pypi
openssl                   1.1.1h               h7b6447c_0  
packaging                 20.4                       py_0  
pandoc                    2.11                 hb0f4dca_0  
pandocfilters             1.4.2                    py37_1  
parso                     0.7.0                      py_0  
pathy                     0.3.1                    pypi_0    pypi
pexpect                   4.8.0                    py37_1  
pickleshare               0.7.5                 py37_1001  
pip                       20.2.3                   py37_0  
preshed                   3.0.2                    pypi_0    pypi
prometheus_client         0.8.0                      py_0  
prompt-toolkit            3.0.8                      py_0  
ptyprocess                0.6.0                    py37_0  
pycparser                 2.20                       py_2  
pydantic                  1.6.1                    pypi_0    pypi
pygments                  2.7.1                      py_0  
pyopenssl                 19.1.0                     py_1  
pyparsing                 2.4.7                      py_0  
pyrsistent                0.17.3           py37h7b6447c_0  
pysocks                   1.7.1                    py37_1  
python                    3.7.9                h7579374_0  
python-dateutil           2.8.1                      py_0  
pytokenizations           0.6.0                    pypi_0    pypi
pyzmq                     19.0.2           py37he6710b0_1  
readline                  8.0                  h7b6447c_0  
requests                  2.24.0                     py_0  
s3transfer                0.3.3                    pypi_0    pypi
send2trash                1.5.0                    py37_0  
setuptools                50.3.0           py37hb0f4dca_1  
six                       1.15.0                     py_0  
smart-open                2.2.1                    pypi_0    pypi
spacy-nightly             3.0.0rc1                 pypi_0    pypi
sqlite                    3.33.0               h62c20be_0  
srsly                     2.3.0                    pypi_0    pypi
terminado                 0.9.1                    py37_0  
testpath                  0.4.4                      py_0  
thinc                     8.0.0rc0                 pypi_0    pypi
tk                        8.6.10               hbc83047_0  
tornado                   6.0.4            py37h7b6447c_1  
tqdm                      4.50.2                   pypi_0    pypi
traitlets                 5.0.5                      py_0  
typer                     0.3.2                    pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.25.10                    py_0  
wasabi                    0.8.0                    pypi_0    pypi
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py37_1  
wheel                     0.35.1                     py_0  
xz                        5.2.5                h7b6447c_0  
zeromq                    4.3.3                he6710b0_3  
zipp                      3.3.0                      py_0  
zlib                      1.2.11               h7b6447c_3

**Comment by honnibal** [comment]
Yes this is one of the workflows that's changed in v3. We've tried to make the error message as helpful as possible. If you have a look at the error you pasted, is it clear to you what needs to be done? I thought the wording there was quite good, but I understand it's always hard to guess how things come across to users. You can also find this covered in the migration guide: https://nightly.spacy.io/usage/v3#migrating-add-pipe

**Comment by adrianeboyd** [comment]
Maybe we could provide the string name in the error message for the built-in components in case two? I think a lot of the names aren't obvious from the class names...
