### ISSUE TITLE
Performance per label

### ISSUE THREAD

**Issue by aCampello** [explosion/spaCy#6266]
I understand that the documentation contains the performance on each specific tags. I was wondering whether it is possible to also include the performance PER label? (e.g., for NER, the precision and recall for `PERSON`, `NORP`, etc..)

## Which page or section is this issue related to?

https://nightly.spacy.io/models/en#en_core_web_trf

**Comment by adrianeboyd** [comment]
Sure, we have the per-type evaluation internally, it's just a matter of modifying a few steps in our training process so that it ends up saved in the model as well.

**Comment by aCampello** [comment]
Thanks a lot @adrianeboyd  - that would be really useful!. Perhaps this could be added to the model json: 
```
https://github.com/explosion/spacy-models/blob/en_core_web_trf-3.0.0a0/meta/en_core_web_trf-3.0.0a0.json
```
