### ISSUE TITLE
Erroneous Unicode character in lemma lookup entry for "first"

### ISSUE THREAD

**Issue by peter-exos** [explosion/spaCy#6281]
## How to reproduce the behaviour

The English lookup-based lemmatizer returns `'\ufeff1'` as the lemma for the token `"first"` instead of the expected `"1"`, i.e. somehow the invisible byte-order marker `U+FEFF` made it into that entry.
Other ordinals do not seem to be affected.

Minimal example for spacy 2.3.2
```python
import spacy
import en_core_web_sm

nlp = en_core_web_sm.load(disable=['tagger', 'parser', 'ner'])

text = 'The first days'
for tok in nlp(text):
    print(tok.text, tok.lemma_, repr(tok.lemma_))
```
This outputs
```
The The 'The'
first ﻿1 '\ufeff1'
days day 'day'
```

The same happens in spacy 3.0.0rc1 if `nlp` is initialized as
```python
import spacy

nlp = spacy.blank("en")
nlp.add_pipe("lemmatizer", config={"mode": "lookup"})
nlp.initialize()
```

FWIW, I'm not sure how much I like the expected behavior here: 
- the lemma of `third` is `3`, but
- the lemma of `three` is `three`.

This seems a bit inconsistent.

## Your Environment
* **spaCy version:** 2.3.2 **and** 3.0.0rc1
* **Platform:** macOS-10.14.6-x86_64-i386-64bit
* **Python version:** 3.8.5

**Comment by svlandeg** [comment]
Thanks for the report! That certainly does look like a bug, and you're right that it's still present in the RC for v3. We will look into it.

**Comment by adrianeboyd** [comment]
PR to fix this here: https://github.com/explosion/spacy-lookups-data/pull/16 . I think we'll have to backport it to 0.3.x for spacy v2.3.x.

The overall quality of the lemma lookup tables is not great. They were meant to fill a gap before rule-based or statistical lemmatizers were added, but it's taken longer than expected to implement the statistical lemmatizer option, so for many languages it's still the only option. For English, we'd typically recommend using a pipeline with a tagger so you can use the rule-based lemmatizer instead. In v3, you need a component that sets POS (either `tagger`+`attribute_ruler` or `morphologizer` depending on the training data)  plus the new separate lemmatizer component.

**Comment by peter-exos** [comment]
Awesome, thank you!

I agree that the quality of the lemma lookup tables is not always great.
I skimmed the English table and found a few examples I fix manually in my code. 
I list them here, in case they are helpful:
```
'does'  # verb 'do' is probably more common than the noun 'doe'
'as'  # I'd rather leave 'as' as is; instead of treating it like 'bs', 'cs', ...
'data'  # maybe not a plural any more
'ai'  # form of 'have'?
```
The following are listed as lemmas of some other forms, but have a different form as their own lemma:
```
'crew' 
'dive'
'lay'
'rent'
```

In general, I agree that a rule- or model-based lemmatizer is probably the better option, but there are use cases for lookup-based lemmatizers:
- in my experience, the lookup-based lemmatizer is a good replacement for a stemmer, because it lemmatizes more "radically" than the rule-based one, without producing garbled outputs. I sometimes use lemmas instead of words as features for some downstream ML models.
- in some applications, we don't need any of the statistical annotations, but just the spacy tokenizer and rule-based matchers (which are amazing, so much better than plain regexes). Being able to reference the lemma in token patterns, can make some patterns more concise. 

Incidentally, in spacy 2.x the Matcher does not accept patterns containing `"LEMMA"` if there is no tagger in the pipeline, despite the fact that lemmas are set correctly. A dirty workaround is to manually set `doc.is_tagged = True`. 
Looks like in spacy 3 this issue will be resolved.

**Comment by svlandeg** [comment]
It looks like the original issue has been fixed - so I think we might be able to close this bug report? Or was there anything else you still wanted to address, @adrianeboyd ?
