### ISSUE TITLE
Support loading model with module path (dot-separated)

### ISSUE THREAD

**Issue by pawamoy** [explosion/spaCy#6282]
## Feature description
I'm trying to wrap spaCy models into Python namespace packages.

For example:

```
project/
  src/
    my_namespace/
      my_package/
        __init__.py
        meta.json
        en_core_web_md-2.3.0/
          meta.json
          ...  # actual files
```

The contents of `project/src/my_namespace/my_package/__init__.py` is:

```python
from pathlib import Path
from spacy.util import load_model_from_init_py, get_model_meta

__version__ = get_model_meta(Path(__file__).parent)['version']


def load(**overrides):
    return load_model_from_init_py(__file__, **overrides)
```

My package distribution name is `my-namespace-my-package`. 

Now I would like to be able to do this:

```python
import spacy

model = spacy.load("my_namespace.my_package")
```

Unfortunately it does not work because to check if the given string is a package, you check if it appears in the list returned by `pkg_resources.working_set.by_key.keys()`, replacing dashes with underscores in each package name.

So, `pkg_resources` returns a list containing `my-namespace-my-package`, which is transformed into `my_namespace_my_package`, so `is_package("my_namespace.my_package")` fails.

If I do `spacy.load("my_namespace_my_package")` instead, `is_package` returns True, but then you try to import it with `importlib.import_module`, and no module of this name exists of course.

In fact, the current code expects the distribution name to be equal to the import name (not considering dashes vs. underscores), which is not always the case! So if I publish a package whose distribution name is `python-a`, and whose import name is `a`, I won't be able to load it, since `is_package` will return True only for `python_a` (and not `a`), but `python_a` is not importable.

What I suggest instead is to try to import the given name, and if an ImportError or ModuleNotFoundError is raised, check if the given name exists on the disk and use it as a path. Or in the reverse order: it it's a file/dir and exists, use it as a path, otherwise try to import it as is. You don't need to check the installed packages with `pkg_resources`.

Something like this:

```python
def load_model(name, **overrides):
    """Load a model from a shortcut link, module or data path.

    name (unicode): Module name, shortcut link or model path.
    **overrides: Specific overrides, like pipeline components to disable.
    RETURNS (Language): `Language` class with the loaded model.
    """
    data_path = get_data_path()
    if not data_path or not data_path.exists():
        raise IOError(Errors.E049.format(path=path2str(data_path)))
    if isinstance(name, basestring_):  # in data dir / shortcut
        if name.startswith("blank:"):  # shortcut for blank model
            return get_lang_class(name.replace("blank:", ""))()
        if name in set([d.name for d in data_path.iterdir()]):
            return load_model_from_link(name, **overrides)
        if Path(name).exists():  # path to model data directory
            return load_model_from_path(Path(name), **overrides)
        try:  # possible module path
            return load_model_from_package(name, **overrides)
        except ImportError:
            pass  # will raise IOError
    elif hasattr(name, "exists"):  # Path or Path-like to model data
        return load_model_from_path(name, **overrides)
    raise IOError(Errors.E050.format(name=name))
```

This would allow to do what I described above, with arbitrary Python module paths, separated with dots.

Happy to send a PR!

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
I'm not sure but I don't think so.

**Comment by svlandeg** [comment]
Hi @pawamoy, thanks for the detailed explanation and apologies for the late follow-up. 

I think this discussion is probably easier if you do make the PR, so we can see the actual changes that would be involved. Your reasoning sounds good to me, but I might be missing some subtleties that other members of the team may wish to comment on.

**Comment by pawamoy** [comment]
Hello @svlandeg, thank you for your answer, and no problem about the delay (I'm myself quite late to answer!).
I eventually lost interest in this, as we will mostly load model from paths on the filesystem. Feel free to reopen if you still want to keep track of this!
