### ISSUE TITLE
Add spacy model as dependency to SETUP.PY

### ISSUE THREAD

**Issue by madkote** [explosion/spaCy#6287]
## How to reproduce the problem
I would like to add spacy model to `setup.py` as dependency.
by installing the package with spacy model as dependency, there is an error.

```python
REQUIRES_INSTALL = [
    'en-core-web-sm@git+https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.0/en_core_web_sm-2.3.0.tar.gz',
...
]
```

```bash
pip setup.py bdist_wheel
pip install mypack.whl
ERROR: Could not find a version that satisfies the requirement en-core-web-sm (from mypack==0.3.5) (from versions: none)
ERROR: No matching distribution found for en-core-web-sm (from mypack==0.3.5)
```

## Your Environment
* Operating System: ubuntu
* Python Version Used: 2.7.9
* spaCy Version Used: 2.3.2

**Comment by adrianeboyd** [comment]
Hi, here's how you can provide the model URL as a pip requirement:

https://spacy.io/usage/models#models-download

I have to admit I'm not entirely sure what all the possibilities are here in terms of how `pip` can interpret the URL, but the model is an asset attached to the github release, not part of the `spacy-models` git repo itself, so I think that you don't want a `git+https` URL.

**Comment by madkote** [comment]
@adrianeboyd thx. well, that is the requirements.txt and not setup.py -> the question was explicit and not answered.

**Comment by adrianeboyd** [comment]
Have you not tried the URL as shown in the docs above? This should work:

```
en_core_web_sm@https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz
```

**Comment by madkote** [comment]
@adrianeboyd I think I did, let me come back to it today or tomorrow. thx!

**Comment by SalmanZafar-DataScience** [comment]
> @adrianeboyd I think I did, let me come back to it today or tomorrow. thx!

I'm also stuck while trying to add _de_core_news_sm_ model as a dependency in setup.py. Have you already come up with any solution?
