### ISSUE TITLE
-PRON- doesn't appear as tag but as a word in a sentence when spacy md is used

### ISSUE THREAD

**Issue by irocks04** [explosion/spaCy#6291]
## How to reproduce the behaviour

Pycharm: Using spacy
pos = spacy.load('en_core_web_md') 
nltk.download('punkt')
## Your Environment

* Operating System: 
* Python Version Used: 3.0
* spaCy Version Used: en_core_web_md'
* Environment Information:
![image](https://user-images.githubusercontent.com/20955417/96914102-2e6c6a00-14c2-11eb-85c4-573d3f94a2cd.png)
In the attached screen shot i see sometimes -PRON- appears as a word but not as a tag

**Comment by adrianeboyd** [comment]
`-PRON-` is a special symbol used as a lemma for pronouns in some languages in spacy v2. There's not really enough information in your description above to be sure about what's going on, but I'm guessing that you're replacing words with their lemmas at some point in your processing?

If you want lemmas in general but you don't want `-PRON-`, you'll need to add an extra step that goes back through the docs and replaces `-PRON-` with the word form or another alternative. You can implement this as a simple pipeline component if you'd like, see: https://spacy.io/usage/processing-pipelines#custom-components

(I do agree that it's more of a tag than a lemma. It will no longer be used in the upcoming spacy v3.)
