### ISSUE TITLE
Noun_chunks algorithm is missing object predicatives

### ISSUE THREAD

**Issue by vha14** [explosion/spaCy#6301]
## How to reproduce the behaviour
```python
import spacy
nlp = spacy.load("en_core_web_md")
for nc in nlp("It's a system called Rake"): print(nc)

it
a system
```
Note that "Rake" is missing as a noun chunk. The problem seems to be that Rake's dependency tag, `oprd` 
is not in the [list](https://github.com/explosion/spaCy/blob/5ce02c1b17eb72ade2c1577461c9a4f0213635aa/spacy/lang/en/syntax_iterators.py#L12) of tags accepted. 

## Your Environment
* Operating System: Ubuntu 20.04
* Python Version Used: 3.8.5
* spaCy Version Used: 2.3.2
* Environment Information:

**Comment by adrianeboyd** [comment]
That does look like an oversight, thanks for the PR!
