### ISSUE TITLE
ImportError: cannot import name set_gpu_allocator

### ISSUE THREAD

**Issue by yw2903** [explosion/spaCy#6329]
![image](https://user-images.githubusercontent.com/46970976/97904467-8602a500-1d0e-11eb-8506-fcc46f0435bf.png)
Thinc version  8.0.0rc1. 
I'm trying to use the new feature from spacy-nightly so I download the latest version of thinc. However, I could not import certain function as the the demo code. 

## Your Environment

* Operating System: Azure R studio 
* Python Version Used: 3.7
* spaCy Version Used: 2.3 and nightly

**Comment by svlandeg** [comment]
Hm, that's weird, Thinc's [api](https://github.com/explosion/thinc/blob/master/thinc/api.py) definitely does have the `set_gpu_allocator` function. It looks like you're running this from a notebook, could it be that you have the wrong environment running in the notebook? Could you run these lines before anything else and let us know what the output is?
```
import spacy
print(spacy.__version__)

import thinc
print(thinc.__version__)
```

**Comment by forgetso** [comment]
I had the same issue. Try `pip install thinc==8.0.0rc2`. You probably have an older version of thinc installed.
