### ISSUE TITLE
Annotating Tokens similar to Doc

### ISSUE THREAD

**Issue by suryasumukh** [explosion/spaCy#635]
Hi,
I have two neural nets, a token-wise sentiment tagger and a NER tagger that i would like to include in the nlp pipeline. I was wondering if there was a way to add custom annotations to Token similar to Doc (eg. doc.user_data['sentiment']) following from the [hooking a deep net model example](https://github.com/explosion/spaCy/blob/master/examples/deep_learning_keras.py).

Thanks!

**Comment by honnibal** [comment]
Hi,

tl;dr:

* Set `doc.ents` for the entity recogniser
* Use `doc.user_token_hooks['sentiment']` for the token
* See https://spacy.io/docs/usage/deep-learning

The unintuitive thing here is that the `Token` object is only a view --- all the data is owned by the `Doc`. There's also currently no `sentiment` field on the `TokenC` struct. To customise the behaviour of the `token.sentiment` property, we register a hook with the `Doc` object: https://github.com/explosion/spaCy/blob/master/spacy/tokens/token.pyx#L123

**Comment by suryasumukh** [comment]
Thanks!
