### ISSUE TITLE
tqdm does not work with spacy

### ISSUE THREAD

**Issue by SamEdwardes** [explosion/spaCy#6351]
## Feature description

I would like to use the tqdm library with spaCy so I can monitor progress on large number of documents.

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
If so, we will tag it as [`project idea`](https://github.com/explosion/spaCy/labels/project%20idea) so other users can take it on.

No need for feature component. For some reason tqdm progress bar does not seem to work correctly for nlp.pipe. For example:

```python
>>> import spacy
>>> from tqdm import tqdm
>>> nlp = spacy.load('en_core_web_sm')
>>> raw_texts = ['This is the first text', 'this is the second']
>>> # does not work for list comprehnsion
>>> [doc for doc in tqdm(nlp.pipe(raw_texts))]
2it [00:00,  6.71it/s]
[This is the first text, this is the second]
>>> # does not work in a loop
>>> for doc in tqdm(nlp.pipe(raw_texts)):
...     print(doc)
0it [00:00, ?it/s]This is the first text
this is the second
2it [00:00, 142.75it/s]
>>> # confirming tqdm does work on my computer for other use cases
>>> [i for i in tqdm(range(10))]
100%|████████████████████████████████████████████████████████████████████████| 10/10 [00:00<?, ?it/s]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
>>> spacy.__version__
'2.3.2'
```

python version (using miniconda):

```bash
$ python --version
Python 3.8.5
```

Please note that I did review issue #2318 but they did not seem to have the same problem as me.

**Comment by adrianeboyd** [comment]
Try this instead:

```python
[doc for doc in nlp.pipe(tqdm(raw_texts))]
```

**Comment by SamEdwardes** [comment]
Hi @adrianeboyd thank you for the suggestion. I confirmed that it works. Marking this issue as closed.
