### ISSUE TITLE
Problem loading the trained model with transformer component for Croatian language [spacy-nightly]

### ISSUE THREAD

**Issue by danielvasic** [explosion/spaCy#6352]
## How to reproduce the behaviour

Hello everyone,

I have successfully trained the model by using @adrianeboyd suggestion in #6319 and it worked like a charm It gave me far better results for all tasks, but the error occurred when trying to load the saved component. It cannot load the transformer component because it cannot find the factory for the language hr(Croatian):

```
ValueError: [E002] Can't find factory for "transformer" for language Croatian (hr). This usually happens when spaCy calls "nlp.create_pipe" with custom component name that's not registered on the current language class. If you're using a custom component, make sure you've added the decorator "@Language.component" (for function components) or "@Language.factory" (for class components).
```

## Info about spaCy

- **spaCy version:** 3.0.0rc2
- **Platform:** Darwin-19.6.0-x86_64-i386-64bit
- **Python version:** 3.7.9

**Comment by adrianeboyd** [comment]
Double-check that you have `spacy-transformers` installed in the venv where you're loading the model.

**Comment by danielvasic** [comment]
Stupid me, sorry for not checking dependencies first. Thank you very much. :-)

**Comment by Aleksandar1932** [comment]
Steps to solve:
- `pip install spacy-transformers`
- import spacy_transformers
