### ISSUE TITLE
Manipulating embedding output?

### ISSUE THREAD

**Issue by Khanifsaleh** [explosion/spaCy#6355]
* Operating System: Ubuntu 18
* Python Version Used: 3.6
* spaCy Version Used: 2.x

Can I manipulating output of embedding layer for each token when training?
ex: multiply 'apple' vector by 5.

**Comment by svlandeg** [comment]
I'm not sure what exactly you're asking. Can you provide some more details / example code snippet on what it is you're currently doing, and what you'd like to change?
