### ISSUE TITLE
[E018] Can't retrieve string for hash, on raspbian system

### ISSUE THREAD

**Issue by DanBmh** [explosion/spaCy#6356]
## Info about spaCy

* **spaCy version:** 2.3.2
* **Platform:** Linux-5.4.0-52-generic-armv7l-with-debian-10.6
* **Python version:** 3.7.3
* **Models:** es, de, fr, en

Spacy installation is done like this:
```
RUN BLIS_ARCH="generic" pip3 install  --no-cache-dir --upgrade "blis<0.5.0,>=0.4.0"
RUN BLIS_ARCH="generic" pip3 install  --no-cache-dir --upgrade spacy --no-binary blis
```

Complete error message:
```
Traceback (most recent call last):
  File "/usr/local/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/rasa/__main__.py", line 115, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/usr/local/lib/python3.7/dist-packages/rasa/cli/shell.py", line 89, in shell_nlu
    rasa.nlu.run.run_cmdline(nlu_model)
  File "/usr/local/lib/python3.7/dist-packages/rasa/nlu/run.py", line 36, in run_cmdline
    result = interpreter.parse(message)
  File "/usr/local/lib/python3.7/dist-packages/rasa/nlu/model.py", line 398, in parse
    component.process(message, **self.context)
  File "/usr/local/lib/python3.7/dist-packages/rasa/nlu/tokenizers/tokenizer.py", line 114, in process
    tokens = self.tokenize(message, attribute)
  File "/usr/local/lib/python3.7/dist-packages/rasa/nlu/tokenizers/spacy_tokenizer.py", line 44, in tokenize
    for t in doc
  File "/usr/local/lib/python3.7/dist-packages/rasa/nlu/tokenizers/spacy_tokenizer.py", line 45, in <listcomp>
    if t.text and t.text.strip()
  File "token.pyx", line 894, in spacy.tokens.token.Token.lemma_.__get__
  File "strings.pyx", line 136, in spacy.strings.StringStore.__getitem__
KeyError: "[E018] Can't retrieve string for hash '456356374'. This usually refers to an issue with the `Vocab` or `StringStore`."
```

## How to reproduce the behaviour

I'm using spacy as backend for rasa's nlu pipeline in a raspbian based container.  As for the word embeddings I'm using the pretrained _en_core_web_md_ corpus. I didn't find an easy way for others to reproduce it yet, because container building alone does take over 4h. There are no problems when running the same things in an ubuntu based container.

But for me I could reproduce it by running rasa predictions including one word a second time. The first time I get a correct response, and as soon as I use a word in the sentences a second time I get the error message. 
Similar for training, if I add some debug prints to the code, I can see that the words a tagged correctly with their word type on the first time they occur, but if they occur again, most of them throw the above error (also see my rasa issue [here](https://github.com/RasaHQ/rasa/issues/6633)).

So I belive I have something like a caching problem here.
Any ideas on this?

**Comment by DanBmh** [comment]
Found an easy to reproduce code:

```
import spacy
nlp = spacy.load("en_core_web_sm")


# Everything works fine here

doc = nlp("Apple is looking at buying U.K. startup for $1 billion")
for token in doc:
    print(token.text, token.lemma_, token.pos_, token.tag_)


# Calling it again, we get the error

doc = nlp("Apple is looking at buying U.K. startup for $1 billion")
for token in doc:
    print(token.text, token.lemma_, token.pos_, token.tag_)

```

I have no problems running it in my ubuntu container, but as soon as I use the raspbian installation, it doesn't work.

**Comment by adrianeboyd** [comment]
Hi, you need a raspberry pi 3 or 4 with a 64-bit OS and 64-bit python for spacy. See the notes here:

https://github.com/explosion/spaCy/issues/6021#issuecomment-687059113

We should explicitly check for 32-bit python somewhere, probably in the `blis` setup, to prevent you from going further here by accident.

**Comment by DanBmh** [comment]
Running the suggested command from the other issue: `python3 -c "import sys; print(sys.maxsize > 2**32)"` returns `True` for my container version.

Are you sure this is because 32/64 bit versions? Because the first sentence does work without problems, only the second time I try to analyse it doesn't work.

**Comment by adrianeboyd** [comment]
Hmm, I'm pretty sure both `raspbian` and `armv7l` is going to be 32-bit. Which raspberry pi model do you have? I think you'll need raspberry pi os or debian or ubuntu. It has to be the 64-bit version of the OS, which will require 64-bit hardware.

My `spacy info` for my raspberry pi 4 looks like this:

* **spaCy version:** 2.3.2
* **Platform:** Linux-5.4.51-v8+-aarch64-with-debian-10.5
* **Python version:** 3.7.3

To check a little more, what is the output of `lscpu` and `file /usr/bin/python3.7`?

**Comment by DanBmh** [comment]
`lscpu` gives my my `Ryzen 7 3700X` processor, because currently I'm running the container on my computer (using qemu).

On my Pi3 I'm currently struggling installing spacy directly, because there I have a 32bit system.

**Comment by DanBmh** [comment]
Sorry, did use the wrong container before, now `python3 -c "import sys; print(sys.maxsize > 2**32)"` returns `False`.
Thanks for now for the hint, I will check a different base image and update the results then.

**Comment by DanBmh** [comment]
Do you know an easy way to just disable the stringstore caching?
This might be easier for me than than reinstalling the Raspberry PIs.

**Comment by adrianeboyd** [comment]
No, this is a core part of spacy. You really have to have 64-bit python.

**Comment by DanBmh** [comment]
I think I found a solution for my problem. I did replace the stringstore lookup here: https://github.com/explosion/spaCy/blob/v2.3.2/spacy/tokens/token.pyx#L894 with the longer lookup two lines above. Now the code doesn't try to look up the too long hashes, and I don't get an exception in the second part of the code above. My first tests with rasa did work too.

I will do some further tests in the next time, but I hope this solves it, because in a trade-off between switching to a 64bit-OS or longer rasa training times without spacy, the no spacy solution would win right now.

**Comment by adrianeboyd** [comment]
The use of spacy in rasa may be limited enough that this works for your purposes, but be aware that there are a few spots where spacy is not going to be compatible with 32-bit python (the lemma cache is one of them), so you may run into other similar issues in the future.

We might consider updating spacy and a few dependencies to support 32-bit officially, but it's not going to be a high priority.
