### ISSUE TITLE
Film script breakdown?

### ISSUE THREAD

**Issue by wadeeProd** [explosion/spaCy#6358]
Hi, I'm a filmmaker not developer. 
what is the best roadmap for me to develop a method to use your amazing spaCy in my website? 
I need it to generate some lists from every film script: 
characters List, Locations, Times, costumes, Sounds and Music list. 
Where I can start?  hire developer from your community? how?Thank you for your answer.
Wadee

**Comment by svlandeg** [comment]
Hi, happy to hear you're considering spaCy in your project!
I'm afraid we can't really provide project-specific advice and guidance, we simply don't have the resources for that. We try to keep this issue tracker focused on bug reports and feature requests.

In my honest personal opinion: yes, it could be a good investement to hire an NLP consultant for your project. You might try [this thread](https://support.prodi.gy/t/spacy-prodigy-consultants/738) to look for someone.
