### ISSUE TITLE
Is this morphology correct?

### ISSUE THREAD

**Issue by gleidsonh** [explosion/spaCy#6359]
**Correct**
sentence = nlp('Hoje eu comprei um carro') //Today I buy a car
{'Mood_ind': True, 'Number_sing': True, 'Person_one': True, 'Tense_past': True, 'VerbForm_fin': True, 74: 100}

**Correct**
sentence = nlp('Hoje nós compramos um carro') //Today we bought a car
{'Mood_ind': True, 'Number_plur': True, 'Person_one': True, 'Tense_pres': True, 'VerbForm_fin': True, 74: 100}

**Incorrect**
sentence = nlp('Ontem nós compramos um carro') //Yesterday we bought a car
{'Mood_ind': True, 'Number_plur': True, 'Person_one': True, **'Tense_pres'**: True, 'VerbForm_fin': True, 74: 100}
* See [picture](https://i.imgur.com/nWCn4WY.png) - Both present and past is similar, but in this case is past because I'm talking about Yesterday.

## Your Environment
* **spaCy version:** 2.3.2
* **Platform:** Linux-5.4.0-52-generic-x86_64-with-glibc2.29
* **Python version:** 3.8.5

**Comment by adrianeboyd** [comment]
The morphological analysis comes from the statistical tagger, which does not have 100% accuracy. Especially if the word forms are identical for two different analyses, it's likely that the tagger may make mistakes. See the top post in #3052 for more details about what you can expect from the pretrained statistical models.
