### ISSUE TITLE
bin/wiki_entity_linking is missing?

### ISSUE THREAD

**Issue by aced125** [explosion/spaCy#6362]
This link: https://github.com/explosion/spaCy/blob/master/bin/wiki_entity_linking is missing!

**Comment by svlandeg** [comment]
Hi! Apologies for the confusion, this linked has been moved to https://github.com/explosion/projects/tree/master/nel-wikipedia. Where did you find the original link? We should update it.

**Comment by aced125** [comment]
It's all over the internet :joy: @svlandeg

**Comment by aced125** [comment]
Also the nel stuff isn't in explosion/projects master branch either.

**Comment by svlandeg** [comment]
The Wikipedia parsing scripts for NEL are in fact present in the `master` branch of our projects repo, cf the link I shared earlier: https://github.com/explosion/projects/tree/master/nel-wikipedia. This code works with spaCy v2.

We don't want to keep supporting these arbitrary parsing scripts, as the WP dumps occassionally change format. Additionally, the Wikipedia data has a lot of bias in its annotations, which means it's not a great source to train your NEL algorithm on. This is why we moved the scripts out of the main repo.

If you want to work with spaCy v3, you should use the `v3` branch of the projects repo: To get started with NEL in v3, we recommend checking out the sample project https://github.com/explosion/projects/tree/v3/tutorials/nel_emerson. This gives you an idea of how the code & configuration file should work, but you'll still need to bring your own annotated data to obtain a model suitable for your specific use-case.
