### ISSUE TITLE
ValueError: [E002] Can't find factory for 'transformer' for language English (en). 

### ISSUE THREAD

**Issue by yw2903** [explosion/spaCy#6367]
I encounter the following error when loading pacakge en_core_web_trf:

```nlp = spacy.load("en_core_web_trf")```
```nlp = spacy.load("/home/weiy/.venvSpacy/lib/python3.7/site-packages/en_core_web_trf/en_core_web_trf-3.0.0a0")```

![image](https://user-images.githubusercontent.com/46970976/98571910-0717ea00-2283-11eb-9764-5e78bbbacf14.png)

## Your Environment

* Operating System: Azure
* Python Version Used: 3.7
* spaCy Version Used: 3.0.0rc2

**Comment by svlandeg** [comment]
Did you install [spacy-transformers](https://github.com/explosion/spacy-transformers)?

**Comment by yw2903** [comment]
Oh right, thanks.

**Comment by rukshar69** [comment]
> Did you install [spacy-transformers](https://github.com/explosion/spacy-transformers)?

Yes, but it still didn't resolve my issue. I am using Google Colab.

**Comment by polm** [comment]
@rukshar69 Can you provide the output of `spacy info`?
