### ISSUE TITLE
Allow spacy.en.download to take a file path

### ISSUE THREAD

**Issue by ExplodingCabbage** [explosion/spaCy#637]
As noted at https://github.com/explosion/spaCy/issues/208#issuecomment-184009513, it's possible to install spaCy models to a custom path via `sputnik.install`, but looking at the code for `en/download.py` it seems that there's no way to specify a custom path when installing via `python -m spacy.en.download`.

It would be nice to have this feature, especially since `download.py` offers niceties like checking whether the model is already installed that `sputnik.install` doesn't do.

A syntax like `python -m spacy.en.download --download-path=/path/to/download/model/to` seems like it'd be ideal.

**Comment by honnibal** [comment]
Sounds great. Do you want to make the pull request?

**Comment by ExplodingCabbage** [comment]
Sure - I'll try to get round to it today, otherwise I'll put something together over the weekend.

**Comment by honnibal** [comment]
Btw, I've been trying to improve options for file loading more generally. There's some stuff in spacy.utils that isn't in the docs yet but might be relevant. Specifically, you should be able to set the default data path.
