### ISSUE TITLE
Allow installation with specified languages only

### ISSUE THREAD

**Issue by rnikiforova** [explosion/spaCy#6372]
## Feature description
Currently spacy is shipped with over 40 languages which is great. Some languages have bigger lemmatizers (40 MB for Turkish for example). However, many projects use only a handful of languages and have to use spacy in environments with limited storage (such as AWS Lambda). Personally for my project I found that the size of the languages I don't use is over 250 MB. It would be great if there's a way to choose which languages to install or move them to stand-alone packages.

**Current solution:** I believe that currently the only way to solve this is to build spacy from source with the languages removed.

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?
No.

**Comment by adrianeboyd** [comment]
Hi, yes, we realized the package size was becoming a problem and moved the larger language data files to the separate package `spacy-lookups-data` in spacy v2.2.0. It depends a bit on the platform, but the size on disk is ~5-10x smaller. In my local linux install for v2.3.2, the `spacy` directory is now ~60MB.
