### ISSUE TITLE
offline installation

### ISSUE THREAD

**Issue by geoHeil** [explosion/spaCy#6375]
I have downloaded the spacy models and placed them all into `/path/to/folder/spacy` as `tar.gz` zipped files.
- https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-2.3.0/de_core_news_sm-2.3.0.tar.gz
- https://github.com/explosion/spacy-models/releases/download/de_core_news_md-2.3.0/de_core_news_md-2.3.0.tar.gz
- https://github.com/explosion/spacy-models/releases/download/de_core_news_lg-2.3.0/de_core_news_lg-2.3.0.tar.gz
- https://github.com/explosion/spacy-models/releases/download/de_trf_bertbasecased_lg-2.3.0/de_trf_bertbasecased_lg-2.3.0.tar.gz

Then I have untarred: `tar -xvf de_core_news_sm-2.3.0.tar.gz`.

When trying to use the models in spacy:

```
import spacy
nlp = spacy.load('/path/to/folder/spacy/de_core_news_sm-2.3.0')

```

it fails:

```
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/folder/spacy/de_core_news_sm-2.3.0/tokenizer'

```

Do I need to perform an alternative (manual) installation of the models which unpack & create the missing `tokenizer` folder.

**Comment by adrianeboyd** [comment]
You can install the model with `pip install de_core_news_sm-2.3.0.tar.gz` and then load from the package name as `de_core_news_sm`.

If you want to unpack the archive and load from a path, the actual model directory you want to load is two levels deeper in the package at `/path/to/folder/spacy/de_core_news_sm-2.3.0/de_core_news_sm/de_core_news_sm-2.3.0`.

**Comment by geoHeil** [comment]
Great. This works. Any chance you would plan to put them to pypy or conda so the installation is more native / does not require working around firewalling / proxy but works via the default tooling?

**Comment by adrianeboyd** [comment]
No, the main problem is that the models are too large for this to be practical. See the discussion here: #5967
