### ISSUE TITLE
 224.173.171.229  recognition into NUM！

### ISSUE THREAD

**Issue by chushuai** [explosion/spaCy#6381]
import spacy
from spacy import displacy

nlp = spacy.load("en_core_web_sm")
doc = nlp("""220 www219b.sakura.ne.jp ESMTP Sendmail 8.15.2/8.15.2; Thu, 12 Nov 2020 11:41:36 +0900 (JST)
250-www219b.sakura.ne.jp Hello 224.173.171.229 [224.173.171.229], pleased to meet you
250-ENHANCEDSTATUSCODES""")
displacy.serve(doc, style="dep")

**Comment by svlandeg** [comment]
I don't think it's such a strange annotation to label an IP address with NUM?

Either way, it probably makes sense to [train your own NER model](https://spacy.io/usage/training#ner), or [update](https://spacy.io/usage/training#example-train-ner) the existing one with your own annotations. This ensures that the model is tuned to your specific use-case.
