### ISSUE TITLE
textcat score greater than 1 ?

### ISSUE THREAD

**Issue by chushuai** [explosion/spaCy#6389]
```
for text in texts:
    doc = nlp(text)
    print(doc.cats)
```
Here are the results of the classification
{'other': 3.5263908557681134e-06, 'nids': 1.0463782018632628e-06, 'fw': 0.9999954700469971}
{'other': 7.255982836795738e-06, 'nids': 3.4195954867755063e-06, 'fw': 0.9999892711639404}
{'other': 3.5213763567298884e-06, 'nids': 3.07873347082932e-06, 'fw': 0.9999934434890747}
{'other': 6.489870884252014e-06, 'nids': 1.3813800251227804e-05, 'fw': 0.9999797344207764}
{'other': 5.090719696454471e-06, 'nids': 6.428010237868875e-06, 'fw': 0.9999884366989136}
{'other': 7.816949619154911e-06, 'nids': 4.3881286728719715e-06, 'fw': 0.9999878406524658}
{'other': 0.00039436970837414265, 'nids': 0.9993810653686523, 'fw': 0.00022457526938524097}
{'other': 0.22554467618465424, 'nids': 4.56416055385489e-05, 'fw': 0.7744096517562866}
{'other': 0.9997510313987732, 'nids': 7.85488446126692e-05, 'fw': 0.0001704699534457177}
{'other': 0.999688982963562, 'nids': 0.00021079376165289432, 'fw': 0.0001002637145575136}
## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by adrianeboyd** [comment]
Hi, which values are higher than 1? Don't miss the exponents (`e-06`) at the end of the float strings:

```python
from numpy.testing import assert_almost_equal

assert_almost_equal(3.5263908557681134e-06, 0.000003563908557681134)
```

**Comment by chushuai** [comment]
I got it
