### ISSUE TITLE
'spacy.lexeme.Lexeme' object has no attribute 'upper' when instantiate a DocBin

### ISSUE THREAD

**Issue by MatthieuDurand08** [explosion/spaCy#6392]
## How to reproduce the behaviour
import spacy
from spacy.tokens import Doc, DocBin

nlp = spacy.load('fr_core_news_sm")
docbin = docbin = DocBin(nlp.vocab)

[RUN]

I get --> 
/home/matthieu/anaconda3/bin/python /home/matthieu/Documents/SpacyNghTest/ohio/create_docbin_data.py
Traceback (most recent call last):
  File "/home/matthieu/Documents/SpacyNghTest/ohio/create_docbin_data.py", line 6, in <module>
    docbin = DocBin(nlp.vocab)
  File "/home/matthieu/anaconda3/lib/python3.7/site-packages/spacy/tokens/_serialize.py", line 56, in __init__
    attrs = sorted([intify_attr(attr) for attr in attrs])
  File "/home/matthieu/anaconda3/lib/python3.7/site-packages/spacy/tokens/_serialize.py", line 56, in <listcomp>
    attrs = sorted([intify_attr(attr) for attr in attrs])
  File "attrs.pyx", line 170, in spacy.attrs.intify_attr
AttributeError: 'spacy.lexeme.Lexeme' object has no attribute 'upper'
(base) matthieu@matthieu-ub:~/Documents/SpacyNghTest$ 

## Your Environment
* **spaCy version:** 2.3.2
* **Platform:** Linux-5.4.0-52-generic-x86_64-with-debian-bullseye-sid
* **Python version:** 3.7.6

**Comment by adrianeboyd** [comment]
Hi, when you instantiate the `DocBin`, the only args are `attrs` and `store_user_data`. You probably just want:

```python
docbin = DocBin()
```

See the API docs here: https://spacy.io/api/docbin

(You provide `nlp.vocab` when you get the docs out of the `DocBin` with `get_docs`, not when you add them.)

**Comment by jeffmax** [comment]
The sample code in the nightly docs may need to be updated- I received this error when running the sample code here:

https://nightly.spacy.io/usage/training#data

**Comment by adrianeboyd** [comment]
Ah, thanks for pointing that out, we'll get it updated...
