### ISSUE TITLE
installation problem "ModuleNotFoundError: No module named 'thinc.backends.numpy_ops"  

### ISSUE THREAD

**Issue by myeghaneh** [explosion/spaCy#6393]
## How to reproduce the problem
I start to use spacy nightly 

```
pip install spacy-nightly
pip install ml-datasets
python -m spacy download en_core_web_md
```
I faced with this error 
```bash
Traceback (most recent call last):
  File "C:\Users\moha\Anaconda3\envs\testv04\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\moha\Anaconda3\envs\testv04\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\moha\Anaconda3\envs\testv04\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\moha\Anaconda3\envs\testv04\lib\site-packages\spacy\__init__.py", line 10, in <module>
    from thinc.api import prefer_gpu, require_gpu  # noqa: F401
  File "C:\Users\moha\Anaconda3\envs\testv04\lib\site-packages\thinc\api.py", line 2, in <module>
    from .initializers import normal_init, uniform_init, glorot_uniform_init, zero_init
  File "C:\Users\moha\Anaconda3\envs\testv04\lib\site-packages\thinc\initializers.py", line 4, in <module>
    from .backends import Ops
  File "C:\Users\moha\Anaconda3\envs\testv04\lib\site-packages\thinc\backends\__init__.py", line 7, in <module>
    from .cupy_ops import CupyOps, has_cupy
  File "C:\Users\moha\Anaconda3\envs\testv04\lib\site-packages\thinc\backends\cupy_ops.py", line 18, in <module>
    from .numpy_ops import NumpyOps
ModuleNotFoundError: No module named 'thinc.backends.numpy_ops'```

## Your Environment
<!-- Include details of your environment. If you're using spaCy 1.7+, you can also type `python -m spacy info --markdown` and copy-paste the result here.-->
* win 10
*3.8
*spacy nightly 
* 
```
Package             Version
------------------- -------------------
argon2-cffi         20.1.0
async-generator     1.10
attrs               20.3.0
backcall            0.2.0
bleach              3.2.1
blis                0.7.2
catalogue           1.0.0
certifi             2020.6.20
cffi                1.14.3
chardet             3.0.4
click               7.1.2
colorama            0.4.4
cymem               2.0.4
decorator           4.4.2
defusedxml          0.6.0
entrypoints         0.3
filelock            3.0.12
graphviz            0.14.1
idna                2.10
ipykernel           5.3.4
ipython             7.19.0
ipython-genutils    0.2.0
ipywidgets          7.5.1
jedi                0.17.2
Jinja2              2.11.2
joblib              0.16.0
jsonschema          3.2.0
jupyter-client      6.1.7
jupyter-core        4.6.3
jupyterlab-pygments 0.1.2
MarkupSafe          1.1.1
mistune             0.8.4
ml-datasets         0.1.6
murmurhash          1.0.4
nbclient            0.5.1
nbconvert           6.0.7
nbformat            5.0.8
nest-asyncio        1.4.3
nltk                3.5
notebook            6.1.5
numpy               1.19.4
packaging           20.4
pandas              1.1.4
pandocfilters       1.4.3
parso               0.7.1
pathy               0.3.3
Penman              1.1.0
pickleshare         0.7.5
pip                 20.2.4
preshed             3.0.4
prometheus-client   0.8.0
prompt-toolkit      3.0.8
pycparser           2.20
pydantic            1.6.1
Pygments            2.7.2
pyparsing           2.4.7
PyQt5               5.15.0
PyQt5-sip           12.8.1
pyrsistent          0.17.3
python-dateutil     2.8.1
pytokenizations     0.7.2
pytz                2020.4
pywin32             300
pywinpty            0.5.7
pyzmq               20.0.0
regex               2020.7.14
requests            2.25.0
sacremoses          0.0.43
Send2Trash          1.5.0
sentencepiece       0.1.91
setuptools          50.3.1.post20201107
six                 1.15.0
smart-open          3.0.0
smatch              1.0.4
spacy-nightly       3.0.0rc2
srsly               2.3.2
terminado           0.9.1
testpath            0.4.4
thinc               8.0.0rc2
tokenizers          0.8.1rc2
tornado             6.1
tqdm                4.51.0
traitlets           5.0.5
transformers        3.1.0
typer               0.3.2
Unidecode           1.1.1
urllib3             1.26.2
wasabi              0.8.0
wcwidth             0.2.5
webencodings        0.5.1
wheel               0.35.1
widgetsnbextension  3.5.1
wincertstore        0.2

```

**Comment by svlandeg** [comment]
Hm, that's weird. Did you start from a clean environment when you ran those installation commands? Did they output any warnings or errors?

**Comment by myeghaneh** [comment]
thank you for the quick response, yes, I started from a clean env , there was no error before 
this was the last error 
```
ModuleNotFoundError: No module named 'thinc.backends.numpy_ops
```

**Comment by myeghaneh** [comment]
now I make a new envs by python 3.8  , it seems it works

**Comment by svlandeg** [comment]
Ok, happy to hear it works now! I'll close this - but let us know if you should run into any other issues.
