### ISSUE TITLE
[Spacy nightly] Processing errors when feeding paragraphs into  en_core_web_trf pipeline

### ISSUE THREAD

**Issue by curtkohler** [explosion/spaCy#6400]
We have a simple driver that processes a set of documents. After reading a document, it extracts out a set of text blocks (e.g. paragraphs) and then feeds them into spaCy a pipeline one at a time for processing. In this case, we are attempting to leverage the en_core_web_trf pipeline (with 'ner' and 'textcat' disabled). Out of a set of 208 documents, we are seeing more than half generating errors while processing paragraphs (a document will fail processing on a paragraph exception). None of the documents have issues running with the core_web_sm model.

We capture the error as well as the text that is being processed by spaCy if an error is encountered and have been seeing two flavors of errors in our logs:

- Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length.  (I'm assuming this is coming from the transformer library)
- cudaErrorAssert: device-side assert triggered. (this one is less frequent and I believe related to some of the content of the text being processed)

The paragraphs that triggered the first exception runs through the pipeline/model fine standalone.

Some examples:

**Caught Exception:** Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. **Error Generating Text**: Schematic representation of the behavioural paradigm. Within a block of trials subjects were instructed to fixate on the centre of the screen and were subsequently presented, in random order, with a series of different face and car images at one of six phase coherence levels. Each image was presented for 30 ms, followed by an inter-stimulus interval lasting between 1500 and 2000 ms, during which subjects were required to discriminate among the two types of images and respond by pressing a button. A block of trials was completed once all face and car images at all six phase coherence levels have been presented.

 **Caught Exception**: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. **Error Generating Text**: The observed multihadronic cross section as a function of the c.m. energy for the two scans. The curves are the result of the fits of the narrow resonances. The inserts show closeup of the J/ψ and ψ(2S) regions.

As I mentioned the flow is fairly simple, basically:

```
import spacy
spacy.require_gpu()
nlp = spacy.load('en_core_web_trf',disable=['ner', 'textcat'])

for d in docs:
    for para in d:
        try:
           doc = nlp(para)
       except Exception as e:
           #print (debug)
           break
       # do stuff with good results
```

Are there any additional settings that need to be configured when using the transformer-based model?

## Info about spaCy

- **spaCy version:** 3.0.0rc2
- **Platform:** Linux-4.4.0-1114-aws-x86_64-with-debian-buster-sid
- **Python version:** 3.7.6
- **Pipelines:** en_core_web_trf (3.0.0a0)
* Environment Information:
- **AWS instance has a single GPU
- **Instance shows CUDA version as: 10.1.243
- **installed spaCy on box using command:  pip install -U spacy-nightly[cuda101]

**Comment by svlandeg** [comment]
Hi, thanks for the detailed report and sorry to hear you're running into so much trouble!

This feels like a bug, but I can't quite replicate it yet. The example texts you provided, run fine for me with `nlp(text)`, but I guess that's what you implied with 
> The paragraphs that triggered the first exception runs through the pipeline/model fine standalone.

Could you provide a code snippet (and text example or batch) that does throw an error?

**Comment by curtkohler** [comment]
I did a bit more digging today and I believe that the two classes of errors are related to each other.  It appears that the occurrence of a  "cudaErrorAssert: device-side assert triggered" exception causes subsequent calls to nlp() to generate the exception regarding truncate/pad tensors.  I'll try and confirm and get a couple of sample paragraphs to use as a test case pulled together for you this week

**Comment by svlandeg** [comment]
That would be awesome, thanks Curt. We'd love to help, but it's really difficult to debug/fix anything if we can't reproduce on our end.

**Comment by curtkohler** [comment]
So very simple test driver with 5 text blocks to process that generates the issue in my env.  The 4th para (actually an extraction of data from a table's cells) is what appears to cause the initial issue. I wouldn't expect any usable output from spaCy for it, but the previous non-transformer models were able to handle it ok and not leave the state of the software failing all the subsequent calls. Hope this helps.

```
import spacy

print("spacy version: " + spacy.__version__)
spacy.require_gpu()

test_paras = ["Summary of the POIs adopted for the current analysis (province of Modena).",
"No. of POIs (province of Modena)Airports12Petrol stations328Shopping malls43Car parking35Bus parking5TOTAL423Table A2",
"Fleet, trips and mileage shares for BEVs and HEVs (province of Modena).",
"EV typeStrategyTrips and mileage sharesStr. 1Str. 2Str. 3Str. 4Long-Stop R-ACShort-Stop R-DCSmart ACMixed Time AC/DCSmall size vehicleBEV fleet7.99%14.81%14.65%29.70%HEV fleet92.01%85.19%85.35%70.30%BEV trips0.68%2.62%1.78%8.87%HEV trips (electric)75.74%82.54%77.91%73.34%HEV trips (ICE)23.58%14.84%20.31%17.79%BEV mileage1.35%4.29%3.91%14.10%HEV mileage (electric)51.79%64.19%53.80%60.94%HEV mileage (ICE)46.86%31.51%42.29%24.96%Medium size vehicleBEV fleet12.98%25.84%21.02%43.71%HEV fleet87.02%74.16%78.98%56.29%BEV trips1.29%5.33%2.70%13.98%HEV trips (electric)76.33%75.03%72.86%61.18%HEV trips (ICE)22.38%19.64%24.44%24.84%BEV mileage3.14%10.63%6.69%25.15%HEV mileage (electric)56.58%65.17%51.93%55.45%HEV mileage (ICE)40.29%24.20%41.38%19.39%Medium size vehicle (high performance)BEV fleet22.15%41.42%30.01%58.67%HEV fleet77.85%58.58%69.99%41.33%BEV trips2.57%9.40%4.10%19.69%HEV trips (electric)73.12%61.67%66.73%46.01%HEV trips (ICE)24.31%28.93%29.17%34.30%BEV mileage7.67%22.32%11.65%39.68%HEV mileage (electric)59.48%59.86%51.08%45.69%HEV mileage (ICE)32.85%17.81%37.27%14.63%Table A3 ",
"Summary of the mineralogy and petrographic types of carbonates in the 14 CMs studied. The carbonate types that occur in each meteorite are indicated by a grey box. Type 2a calcite and dolomite were described from Cold Bokkeveld by Johnson and Prinz (1993) and de Leuw et al. (2010), as indicated by the striped boxes."]

test_nlp = spacy.load('en_core_web_trf',disable=['ner', 'textcat'])
for p in test_paras:
  try:
    print("============\nProcessing Text: " + p)
    doc = test_nlp(p)
  except Exception as e:
    print('Exception: ' + str(e))
    
  for sent in doc.sents:
    print("Sentence: ", sent)
```

Outputs:

```
spacy version: 3.0.0rc2
============
Processing Text: Summary of the POIs adopted for the current analysis (province of Modena).
Sentence:  Summary of the POIs adopted for the current analysis (province of Modena).
============
Processing Text: No. of POIs (province of Modena)Airports12Petrol stations328Shopping malls43Car parking35Bus parking5TOTAL423Table A2
Sentence:  No. of POIs (province of Modena)Airports12Petrol stations328Shopping malls43Car parking35Bus parking5TOTAL423Table A2
============
Processing Text: Fleet, trips and mileage shares for BEVs and HEVs (province of Modena).
Sentence:  Fleet, trips and mileage shares for BEVs and HEVs (province of Modena).
============
Processing Text: EV typeStrategyTrips and mileage sharesStr. 1Str. 2Str. 3Str. 4Long-Stop R-ACShort-Stop R-DCSmart ACMixed Time AC/DCSmall size vehicleBEV fleet7.99%14.81%14.65%29.70%HEV fleet92.01%85.19%85.35%70.30%BEV trips0.68%2.62%1.78%8.87%HEV trips (electric)75.74%82.54%77.91%73.34%HEV trips (ICE)23.58%14.84%20.31%17.79%BEV mileage1.35%4.29%3.91%14.10%HEV mileage (electric)51.79%64.19%53.80%60.94%HEV mileage (ICE)46.86%31.51%42.29%24.96%Medium size vehicleBEV fleet12.98%25.84%21.02%43.71%HEV fleet87.02%74.16%78.98%56.29%BEV trips1.29%5.33%2.70%13.98%HEV trips (electric)76.33%75.03%72.86%61.18%HEV trips (ICE)22.38%19.64%24.44%24.84%BEV mileage3.14%10.63%6.69%25.15%HEV mileage (electric)56.58%65.17%51.93%55.45%HEV mileage (ICE)40.29%24.20%41.38%19.39%Medium size vehicle (high performance)BEV fleet22.15%41.42%30.01%58.67%HEV fleet77.85%58.58%69.99%41.33%BEV trips2.57%9.40%4.10%19.69%HEV trips (electric)73.12%61.67%66.73%46.01%HEV trips (ICE)24.31%28.93%29.17%34.30%BEV mileage7.67%22.32%11.65%39.68%HEV mileage (electric)59.48%59.86%51.08%45.69%HEV mileage (ICE)32.85%17.81%37.27%14.63%Table A3 
Exception: cudaErrorAssert: device-side assert triggered
Sentence:  Fleet, trips and mileage shares for BEVs and HEVs (province of Modena).
============
Processing Text: Summary of the mineralogy and petrographic types of carbonates in the 14 CMs studied. The carbonate types that occur in each meteorite are indicated by a grey box. Type 2a calcite and dolomite were described from Cold Bokkeveld by Johnson and Prinz (1993) and de Leuw et al. (2010), as indicated by the striped boxes.
Exception: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length.
Sentence:  Fleet, trips and mileage shares for BEVs and HEVs (province of Modena).
```

**Comment by svlandeg** [comment]
Thanks, that's very helpful. It looks like this is the same bug as https://github.com/explosion/spaCy/issues/6321 and we have to investigate what is going on. I'll merge this issue with that other one - thanks for the additional test snippet!
