### ISSUE TITLE
doc.user_token_hooks are removed when docs are produced with nlp.pipe() using n_process > 1

### ISSUE THREAD

**Issue by alvaroabascar** [explosion/spaCy#6402]
## How to reproduce the behaviour

I do not know whether this is a known behavior or not, but I found the following: when customizing `doc.user_token_hooks`, in my case by `doc.user_token_hooks['vector'] = user_token_hook_vector`, this hook is lost when the docs are produced by calling `nlp.pipe(texts, n_process=n)` where `n > 1`. If `n == 1`, the hooks are preserved. Checking the implementation of `Language.pipe` and `Language._multiprocessing_pipe` I see that this is due to the serializing/deserializing of docs into bytes (see the second snippet).

#### First snippet: user_token_hooks lost after processing with `.pipe(n_process=2)`

```python3
import spacy

def user_token_hook_vector(token):
    print('Hook called!', flush=True)
    vocab = token.doc.vocab
    return vocab.get_vector(token.text)

def pipe_add_hook(doc):
    doc.user_token_hooks['vector'] = user_token_hook_vector
    return doc

nlp = spacy.load('en_core_web_md')
nlp.add_pipe(pipe_add_hook, first=True)

doc = nlp('hi there')
doc[0].vector
# prints "Hook called!"
print(doc.user_token_hooks)
# prints {'vector': <function user_token_hook_vector at 0x7...>}

docs = list(nlp.pipe(['hi there']))
docs[0][0].vector
# prints "Hook called!"
print(docs[0].user_token_hooks)
# prints {'vector': <function user_token_hook_vector at 0x7...>}

docs = list(nlp.pipe(['hi there!'], n_process=2)) #os.cpu_count()))
docs[0][0].vector
# does not print
print(docs[0].user_token_hooks)
# prints {}
```

#### Second snippet: hook is lost when serializing/deserializing doc as bytes.

```python
import spacy
from spacy.tokens import Doc

def user_token_hook_vector(token):
    print('Hook called!', flush=True)
    vocab = token.doc.vocab
    return vocab.get_vector(token.text)

def pipe_add_hook(doc):
    doc.user_token_hooks['vector'] = user_token_hook_vector
    return doc

nlp = spacy.load('en_core_web_md')
nlp.add_pipe(pipe_add_hook, first=True)

doc = nlp('hi there')
doc[0].vector
# prints "Hook called!"
print(doc.user_token_hooks)
# prints '{vector': <function user_token_hook_vector at 0x7...>}

doc_bytes = doc.to_bytes()
doc2 = Doc(doc.vocab).from_bytes(doc_bytes)
doc2.vector
# no print
print(doc2.user_token_hooks)
# prints {}
```

## Environment
* **spaCy version:** 2.3.2
* **Platform:** Linux-4.15.0-123-generic-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.7.5

**Comment by adrianeboyd** [comment]
Hmm, this is a bug, but the problem is that there's no good way to serialize the user hooks for multiprocessing here. They are serialized if you pickle a doc, but we only want to use `to_bytes` here to avoid the security problems related to pickle.

We should see if it's possible add a warning or an error when user hooks are set so that you know that you need to handle the multiprocessing at a higher level rather than with `nlp.pipe`.

**Comment by alvaroabascar** [comment]
Maybe the hooks could be sent along with the bytes somehow?

In my case, by now I'm resetting the hooks after processing:

```python
docs = nlp.pipe(texts, n_process=2)
for doc in docs:
    doc.user_token_hook["vector"] = my_hook
```

**Comment by adrianeboyd** [comment]
Hmm, maybe it's possible to restructure things so you have a custom pipeline component at the beginning of the pipeline that sets the user hooks?

There's not going to be a way to include it with `doc.to_bytes`, though.

**Comment by alvaroabascar** [comment]
If you take a look at the snippet I provided, there is already a custom pipe which sets the user hook, but still they are lost. Now I'm wondering whether they are lost at some point during the execution of the pipeline, or when the pipeline has finished and the `docs` are being returned from the child processes to the main one. I guess it's the latter.

**Comment by alvaroabascar** [comment]
Also, even if it is not included in `doc.to_bytes`, maybe this sending of the hooks along with the bytes could be implemented just for `Language.pipe`?

**Comment by adrianeboyd** [comment]
Ah, you're right. I was thinking about whether subsequent pipeline components have access to the hooks when you add it with an initial component while multiprocessing, not whether the doc is returned with the hook intact. If you add the hooks like you do above, they should be available to later components in the pipeline. Here's an example:

```python
import spacy

def user_token_hook_vector(token):
    print('Hook called!', token.text, flush=True)
    return token.doc.vocab.get_vector(token.text)

def pipe_add_hook(doc):
    print("add hook")
    doc.user_token_hooks['vector'] = user_token_hook_vector
    return doc

def pipe_access_hook(doc):
    print("access hook")
    for token in doc:
        v = token.vector
    return doc

nlp = spacy.load('en_core_web_md')
nlp.add_pipe(pipe_add_hook, first=True)
nlp.add_pipe(pipe_access_hook)

print("With call:\n")

doc = nlp('hi there')

print("\nWith pipe with multiprocessing:\n")

docs = list(nlp.pipe(['hi there'], n_process=2))
```

Output:

```none
With call:

add hook
access hook
Hook called! hi
Hook called! there

With pipe with multiprocessing:

add hook
access hook
Hook called! hi
Hook called! there
```

I do think the best workaround is to add the hook to the doc again after calling `nlp.pipe`.

I can also imagine that you could implement an alternate way of defining hooks with registered functions that make them easier to serialize, but this would be a major change from how things currently work.

There's just really no acceptable way to serialize a function with `to_bytes`. If you want to, you can save your `Doc` objects with user hooks with pickle, but we don't want to use pickle in the serialization here. (As a warning, along with being insecure pickle is going to be really inefficient. It would be smaller and faster to use `DocBin` and re-add the hooks after extracting the docs, similar to how you can add them after `nlp.pipe`.)

I do still think there should be a warning or error here so this behavior isn't a surprise, but I don't think we can fix it given the way user hooks are implemented right now.

(Or are you expecting your user hook vectors to be accessed when the tagger and other pretrained components are run? That's not going to change with or without multiprocessing and it would require a completely different explanation about what's going on behind the scenes with the vectors data.)

**Comment by alvaroabascar** [comment]
So so far we have seen that:

1. Hooks are preserved within the pipeline. That's great! It means that pipes depending on a hook will not fail when using multiprocessing.
2. Hooks are lost in the returned doc, but we can set them again after `nlp.pipe`.

Given this, it would be ideal if `nlp.pipe` could somehow re-add the hooks before returning, so that the process would be transparent to the user and she wouldn't have to add the hooks again. But I'm guessing this is not possible.

Then again, maybe we should add a warning in the documentation. Would it be possible to also detect these cases in running code to raise a warning?

**Comment by svlandeg** [comment]
Runtime warning added by PR #6595
