### ISSUE TITLE
Is there a reason why contextualised embeddings are dropped? 

### ISSUE THREAD

**Issue by koaning** [explosion/spaCy#6403]
## How to reproduce the behaviour

A while ago I was playing around with [spacy-transformers](https://explosion.ai/blog/spacy-transformers). It had a lot of cool features, one of which is the ability to fetch contextualized tensors per token.

```python
nlp = spacy.load("en_trf_bertbaseuncased_lg")
doc = nlp("Here is some text to encode.")
assert doc.tensor.shape == (7, 768)  # Always has one row per token
```

In spaCy 3.0 this feature seems to be dropped. I'm wondering why. I'm partially asking this because my use-case for this feature is educational but also because these features can be useful for libraries downstream (like [rasa](https://rasa.com/), [whatlies](https://rasahq.github.io/whatlies/)).

This is what I see when using spacy-nightly. 

```python
import spacy 
nlp = spacy.load("en_core_web_trf")
doc = nlp("Here is some text to encode.")
doc.tensor.shape # (0,)
```

## Info about spaCy

- **spaCy version:** 3.0.0rc2
- **Platform:** Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
- **Python version:** 3.6.9
- **Pipelines:** en_core_web_trf (3.0.0a0)

**Comment by koaning** [comment]
Gah! OK. While writing this question I found the answer. 

I'm adding an answer below such that folks might find it. Turns out I misread the docs. In particular, this [bit](https://nightly.spacy.io/usage/embeddings-transformers#transformers-runtime). 

You can fetch the tensors via;

```python
token_emb, sent_emb = nlp("i duck to hide")._.trf_data.tensors
token_emb.shape, sent_emb.shape
```

**Comment by svlandeg** [comment]
Thanks for posting the fix!

In case it's useful to you or anyone stopping by in the future - I just want to add that you can provide an additional callback to the transformer config, that allows you to customize how things are stored. You can set `set_extra_annotations`, nightly docs here: https://nightly.spacy.io/api/transformer#config (note that these docs currently contain a [typo](https://github.com/explosion/spaCy/pull/6404), the attribute that is always set is `doc._.trf_data` as @koaning pointed out)

```python
@registry.annotation_setters("my_setter.v1")
def custom_annotation_setter(docs, trf_data):
    doc_data = list(trf_data.doc_data)
    for doc, data in zip(docs, doc_data):
        doc._.custom_attr = data
```
and then in code:
```python
nlp = spacy.load("en_core_web_trf")
nlp.get_pipe("transformer").set_extra_annotations = custom_annotation_setter
doc = nlp("This is a text")
assert isinstance(doc._.custom_attr, TransformerData)
print(doc._.custom_attr.tensors)
```
or in the config:
```
[components.transformer.set_extra_annotations]
@annotation_setters = "my_setter.v1"
```
