### ISSUE TITLE
nlp.vocab.prune_vectors destroying most vectors due to lack of lexemes.

### ISSUE THREAD

**Issue by alvaroabascar** [explosion/spaCy#6405]
Since version 2.3 Lexemes are not loaded when loading a language with vectors, and since `vocab.prune_vectors` iterates over the `vocab` to retrieve all lexemes before pruning, this means that loading a language with vectors, and then calling `vocab.prune_vectors(n)` results in a model which retains only a few lexemes (those included by default with that spaCy language) .

## How to reproduce the behaviour

Using the following code you can reproduce this. Observe that we call `vocab.prune_vectors(n)` with `n=10000`, but the final `vectors` has only 324 entries.
 
```python
import spacy

nlp = spacy.load('en_core_web_md')
print(nlp.vocab.vectors.shape)
# prints (20000, 300)

nlp.vocab.prune_vectors(10000)
print(nlp.vocab.vectors.shape)
# prints (324, 300)
```

The following works. I found the solution in the [2.3 release notes](https://spacy.io/usage/v2-3), in the section **No preloaded vocab for models with vectors**.

```python
import spacy

nlp = spacy.load('en_core_web_md')
print(nlp.vocab.vectors.shape)
# prints (20000, 300)

for orth in nlp.vocab.vectors:
    nlp.vocab[orth]

nlp.vocab.prune_vectors(10000)
print(nlp.vocab.vectors.shape)
# prints (324, 300)
```

This makes me think that maybe that `for` loop (or something which loads all lexemes) should happen by default when calling `prune_vectors`. If needed I can prepare a MR.

## Environment

* **spaCy version:** 2.3.2
* **Platform:** Linux-4.15.0-123-generic-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.7.5

**Comment by adrianeboyd** [comment]
Thanks for the report, that does look like a bug!

We normally only prune through `spacy init-model`, which does add all the lexemes first, so we missed this. I'll fix this for the upcoming v2.3.3 release.
