### ISSUE TITLE
Problem to run spaCy and add language models

### ISSUE THREAD

**Issue by DaveSV** [explosion/spaCy#6423]
I got problems installing spaCy in Python 3.9 in Windows 10.
I changed to Python 3.7 and could make the installation with no problems, until used the python command for language models downloading. In fact, I can´t import spaCy running console. This is the error

>>>import spacy ** On entry to DGEBAL parameter number 3 had an illegal value ** On entry to DGEHRD parameter number 2 had an illegal value ** On entry to DORGHR DORGQR parameter number 2 had an illegal value ** On entry to DHSEQR parameter number 4 had an illegal value Traceback (most recent call last): File "", line 1, in File "C:\Users\Alberto\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy_init_.py", line 10, in from thinc.neural.util import prefer_gpu, require_gpu File "C:\Users\Alberto\AppData\Local\Programs\Python\Python37\lib\site-packages\thinc_init_.py", line 5, in import numpy # noqa: F401 File "C:\Users\Alberto\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy_init_.py", line 305, in win_os_check() File "C:\Users\Alberto\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy_init.py", line 302, in _win_os_check raise RuntimeError(msg.format(file)) from None RuntimeError: The current Numpy installation ('C:\Users\Alberto\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\init.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information:

Previously, trying to download the language model I got error as well: 

C:\Users\Alberto>python -m spacy download es_core_news_sm ** On entry to DGEBAL parameter number 3 had an illegal value ** On entry to DGEHRD parameter number 2 had an illegal value ** On entry to DORGHR DORGQR parameter number 2 had an illegal value ** On entry to DHSEQR parameter number 4 had an illegal value Traceback (most recent call last): File "C:\Users\Alberto\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 183, in _run_module_as_main mod_name, mod_spec, code = _get_module_details(mod_name, _Error) File "C:\Users\Alberto\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 142, in get_module_details return get_module_details(pkg_main_name, error) File "C:\Users\Alberto\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 109, in get_module_details import(pkg_name) File "C:\Users\Alberto\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy_init.py", line 10, in from thinc.neural.util import prefer_gpu, require_gpu File "C:\Users\Alberto\AppData\Local\Programs\Python\Python37\lib\site-packages\thinc_init.py", line 5, in import numpy # noqa: F401 File "C:\Users\Alberto\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy_init.py", line 305, in win_os_check() File "C:\Users\Alberto\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy_init.py", line 302, in _win_os_check raise RuntimeError(msg.format(file)) from None RuntimeError: The current Numpy installation ('C:\Users\Alberto\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\init.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information:
```

**Comment by svlandeg** [comment]
It looks like this was answered by https://stackoverflow.com/questions/64938304/problem-to-run-spacy-and-add-language-models and https://stackoverflow.com/questions/64654805/how-do-you-fix-runtimeerror-package-fails-to-pass-a-sanity-check-for-numpy-an - so I'll close this issue. Hope you got everything sorted out. If you still run into installation issues, feel free to open a new issue!

**Comment by DaveSV** [comment]
Yes, thanks!
