### ISSUE TITLE
import error in spaCy/examples/training/train_textcat.py

### ISSUE THREAD

**Issue by svathsa** [explosion/spaCy#6426]
## How to reproduce the behaviour

Running train_textcat.py errors out with ModuleNotFoundError: No module named 'thinc.extra.datasets'. I believe import has to be altered to ml_datasets.

## Your Environment

* Operating System: Mac OS
* Python Version Used: 3.7.9
* spaCy Version Used: 3.0.0rc2
* Environment Information:

**Comment by adrianeboyd** [comment]
These example training scripts only work with spacy v2 and thinc v7, so if you're using `spacy-nightly` and thinc v8, these scripts will no longer work. (We need to update the "Compatible with" notes!)

If you're using spacy v3, switch to the new `spacy project` command with some of the example projects, e.g.:

```bash
spacy project clone tutorials/textcat_docs_issues
spacy project clone benchmarks/textcat_architectures
```

The second project uses the same IMDB data as the v2 example script. Here are the new projects docs: https://nightly.spacy.io/usage/projects
