### ISSUE TITLE
✘ No compatible models found for v2.3.4 of spaCy

### ISSUE THREAD

**Issue by iconix** [explosion/spaCy#6452]
## How to reproduce the behaviour

Upgrade spacy to `2.3.4` and run the command to download a model:

```
python -m spacy download en_core_web_sm
```

results in an error:
```
✘ No compatible models found for v2.3.4 of spaCy
```

## Your Environment
* **spaCy version:** 2.3.4
* **Platform:** macOS-10.15.7-x86_64-i386-64bit
* **Python version:** 3.8.6

**Comment by adrianeboyd** [comment]
Thanks for the report! We've updated it and it should be working in a few minutes.

**Comment by iconix** [comment]
confirmed it works now, thanks!
