### ISSUE TITLE
Ability to match on whitespace (SPACY) attribute in Matcher

### ISSUE THREAD

**Issue by kinghuang** [explosion/spaCy#6453]
## Feature description

I am attempting to write a Matcher pattern that takes into account whether the token has a trailing whitespace. However, `whitespace_`/`SPACY` is not among the [available token attributes](https://spacy.io/usage/rule-based-matching#adding-patterns-attributes).

> ValueError: [E152] The attribute SPACY is not supported for token patterns. Please use the option validate=True with Matcher, PhraseMatcher, or EntityRuler for more details.

I've written a token extension to return whether the token has a `whitespace_` character. It would be nicer if spaCy provided access to the underlying attribute.

## Could the feature be a [custom component](https://spacy.io/usage/processing-pipelines#custom-components) or [spaCy plugin](https://spacy.io/universe)?

A plugin could be created to provide a custom Token extension. But, this would be better implemented in the core code.

**Comment by adrianeboyd** [comment]
I could have sworn we'd already added this, but it must have just been in testing. The feature is available underneath, so it's just a matter of adding it to the list of supported attributes.

If you want to enable it locally, you just need to add it to `spacy/matcher/_schemas.py` (no recompiling necessary!):

```diff
diff --git a/spacy/matcher/_schemas.py b/spacy/matcher/_schemas.py
index 4ef7ae49a..44392edbe 100644
--- a/spacy/matcher/_schemas.py
+++ b/spacy/matcher/_schemas.py
@@ -174,6 +174,10 @@ TOKEN_PATTERN_SCHEMA = {
                 "title": "Token is the first in a sentence",
                 "$ref": "#/definitions/boolean_value",
             },
+            "SPACY": {
+                "title": "Token has a trailing space",
+                "$ref": "#/definitions/boolean_value",
+            },
             "LIKE_NUM": {
                 "title": "Token resembles a number",
                 "$ref": "#/definitions/boolean_value",
```
