### ISSUE TITLE
✘ No compatible model found for 'en_core_sci_md' (spaCy v2.3.4).

### ISSUE THREAD

**Issue by chryssa-zrv** [explosion/spaCy#6458]
I am getting the same error for all en_core_sci_* models. I am using python 3.7 on jupyter

The behaviour can be reproduced by:

!{sys.executable} -m spacy download en_core_sci_md
or
!python3 -m spacy download en_core_sci_md

**Comment by adrianeboyd** [comment]
Hi, `spacy download` only works for the models we distribute ourselves (available models: https://spacy.io/models). I think you need to download the scispacy models from here: https://allenai.github.io/scispacy/

You can copy the download link and install it directly with `pip`, e.g.:

```bash
pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.3.0/en_core_sci_sm-0.3.0.tar.gz
```

See their README: https://github.com/allenai/SciSpaCy#installation
