### ISSUE TITLE
Save spacy model to a google storage

### ISSUE THREAD

**Issue by geewynn** [explosion/spaCy#6469]
I am trying to save a spacy model on google cloud storage using this method `trainer.to_disk('gs://{bucket-name}/model)` and I get this error in return 
`FileNotFoundError: [Errno 2] No such file or directory: 'gs:/{bucket-name}/model'`

Is there a way to do this?

## Your Environment

* Operating System: Linux
* Python Version Used: 3.7
* spaCy Version Used: 2.3.2
* Environment Information:

**Comment by adrianeboyd** [comment]
This question is better fit for StackOverflow, let's keep the discussion there: https://stackoverflow.com/q/65071321/461847
