### ISSUE TITLE
Why isn't GPU not working in inference?

### ISSUE THREAD

**Issue by lingvisa** [explosion/spaCy#6471]
I installed spacy from the source and installed cupy and the thinc_gpu_ops:

`pip install thinc_gpu_ops thinc[cuda100]`

I also used:
`spacy.require_gpu()`

And the code for inference is bellow:
`nlpdocs = self.nlp.pipe(texts, disable=disable, n_process=1)`

It doesn't report any issue when running, however, nvidia-smi shows that no GPU is used. I used segmentation, pos tagger and ner models in spacy 2.3 on Ubuntu. The following command shows that there is only one gpu used, but this gpu is used by another program before I started my spacy program on the same machine. How to debug this further?

```
# nvidia-smi
Tue Dec  1 01:13:09 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.01    Driver Version: 418.87.01    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  On   | 00000000:00:0D.0 Off |                    0 |
| N/A   37C    P0    35W / 250W |   3599MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE...  On   | 00000000:00:0E.0 Off |                    0 |
| N/A   67C    P0   192W / 250W |  15601MiB / 16280MiB |     96%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P100-PCIE...  On   | 00000000:00:0F.0 Off |                    0 |
| N/A   31C    P0    27W / 250W |     10MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P100-PCIE...  On   | 00000000:00:10.0 Off |                    0 |
| N/A   33C    P0    27W / 250W |     10MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

```

**Comment by lingvisa** [comment]
Also, for tagger and ner models, the inference time using GPU would be noticeably faster than cpu, or not necessarily? In another post, I saw suggestions that when GPU is used, multiprocessing shouldn't be used. So I am testing speed between GPU without multiprocessing VS CPU with multiprocessing. But first I need to get GPU working.

**Comment by svlandeg** [comment]
Did you execute `spacy.require_gpu()` in the same script _before_ loading a pretrained `nlp` model?

Also, it looks like you have CUDA 10.1, so I think you want to execute `pip install thinc[cuda101]` instead? I'm not sure what happens if you specify a "wrong" version. Either way, `require_gpu` should throw an error when it can't access the GPU.

**Comment by lingvisa** [comment]
@svlandeg the 10.1 shown by nvidia-smi is not the actual cuda version. nvidia-smi only shows the level of driver support. nvcc check the right verson. I updated. Yes, I added 'require_gpu()' in the same script, outside of a class definition, right after 
 those import statements in the same scripts, including 'import spacy'.

**Comment by lingvisa** [comment]
I didn't execute 'pip install thinc[cuda101]'. Instead, I did 'pip install cupy-cuda100'. thinc is already included in spacy package. right?

**Comment by adrianeboyd** [comment]
Only install `spacy[cuda100]`, or if you want to install `spacy` and `cupy` separately run `pip install spacy "cupy-cuda100<8.0.0"`. It doesn't matter whether you install spacy or cupy first. Don't install `thinc_gpu_ops`, which is no longer used, and just let `thinc` get installed as a `spacy` dependency.

`spacy.require_gpu()` should either raise an error or return `True`. After you load a model you should see the memory usage in `nvidia-smi`. You can check that a loaded model is using cupy with something like this:

```
import spacy
import thinc
spacy.require_gpu()
nlp = spacy.load("en_core_web_sm")
assert isinstance(nlp.get_pipe("tagger").model.ops, thinc.neural.ops.CupyOps)
```

You probably just need to double-check that `spacy.require_gpu()` is actually being called before the model is loaded in your script?

**Comment by lingvisa** [comment]
@adrianeboyd The assertion is true when I run them at iPython terminal, which says the installation of drivers and spacy are good. I remember that spacy can only use one gpu by default, and since my other program (unrelated to Spacy) is already using one GPU, so in order for Spacy to use GPU through Tensorflow, I need to do some additional configurations?

**Comment by adrianeboyd** [comment]
You can pick the GPU to use with `spacy.require_gpu(gpu_id=0)`. Tensorflow is not involved.

Without a reproducible example we can't provide much more help here...
