### ISSUE TITLE
FR lemmatizer switches gender

### ISSUE THREAD

**Issue by leapingllamas** [explosion/spaCy#6477]
I'm seeing the FR lemmatizer switch the gender in the output:

```
>>> import spacy
>>> nlp_fr = spacy.load(‘fr’)
>>> [t.lemma_ for t in nlp_fr.tokenizer(“Fruit de la passion”)]
[‘Fruit’, ‘de’, ‘le’, ‘passion’]
>>> [t.lemma_ for t in nlp_fr.tokenizer(“la”)]
[‘le’]
```

Any workarounds for this, other than treating these as stop words?

**Comment by adrianeboyd** [comment]
If you're using the rule-based lemmatizer (when your pipeline includes a tagger, as for `fr_core_news_sm`), the settings are in the tables:

```
nlp.vocab.lookups.get_table("lemma_rules")
nlp.vocab.lookups.get_table("lemma_exc")
nlp.vocab.lookups.get_table("lemma_index")
nlp.vocab.lookups.get_table("lemma_lookup")
```

It looks like `la` -> `le` is coming from the exceptions table in `lemma_exc` (look under `det`). The POS tags are lowercased in the lemmatizer tables for historical reasons, so for the POS-based tables look under `token.pos_.lower()`.

You can customize the tables to suit your task. The lemmatizer code is here, look at `lemmatize()` for the rule-based lemmatizer:

https://github.com/explosion/spaCy/blob/53c0fb7431a00243224288a058f3d1e7cae88f6f/spacy/lang/fr/lemmatizer.py

If you save the model with `nlp.to_disk("/path/to/model")` any changes to these tables are saved with the model, so when you load it again it will already contains your customizations.

If your model doesn't contain a tagger, then it just uses the lookup table, which also maps `la` to `le`.
