### ISSUE TITLE
spacy.gold.offsets_from_biluo_tags error

### ISSUE THREAD

**Issue by Makrenos** [explosion/spaCy#6487]
Here is the following function:

def getAllOffsets(all_sentences,all_tags):
    entities = list()
    for sentence, tags in zip(all_sentences,all_tags):
        doc = nlp(str(sentence))
        tag = bio_to_bilou(tags)
        temp = offsets_from_biluo_tags(doc, tag)
        entities.append(temp)
    return entities

It gets two lists, the first containing the sentences, the second containg the BILOU tags. If i run manually the "offsets_from_biluo_tags" function to each pair of sentence-tag, i got the correct behavior. But as soon as i put it into a for loop, the function crashes with the following error:

TypeError                                 Traceback (most recent call last)
<ipython-input-306-c1dcb653c34d> in <module>
----> 1 all_offsetts = getAllOffsets(all_sentences,all_tags)

<ipython-input-304-43514d6e218e> in getAllOffsets(all_sentences, all_tags)
      4         doc = nlp(str(sentence))
      5         tag = bio_to_bilou(tags)
----> 6         temp = offsets_from_biluo_tags(doc, tag)
      7         entities.append(temp)
      8     return entities

gold.pyx in spacy.gold.offsets_from_biluo_tags()

gold.pyx in spacy.gold.spans_from_biluo_tags()

span.pyx in spacy.tokens.span.Span.__cinit__()

TypeError: an integer is required

## Info about spaCy

* **spaCy version:** 2.3.4
* **Platform:** Windows-10-10.0.18362-SP0
* **Python version:** 3.7.6

**Comment by adrianeboyd** [comment]
Hi, unless we have enough information to reproduce the error on our end it's going to be hard to track down what's going on. Could you provide a minimal working script with sample input to `offsets_from_biluo_tags` that leads to this error?
