### ISSUE TITLE
Lemmatizer silently fails if some modules are disabled

### ISSUE THREAD

**Issue by raffaem** [explosion/spaCy#6498]
EDIT: Amended to reflect the actual problem

## How to reproduce the behaviour

```
nlp = spacy.load("en_core_web_sm", disable=["tagger", "parser", "ner", "tok2vec", "attribute_ruler"])
docs = nlp.pipe(["Yesterday I ate a sandwich", "I was running fast"])
for doc in docs:
    for word in doc:
        print(word.lemma_, end=' ')
    print()
```

Actual Output:

```
yesterday i ate a sandwich 
i was running fast 
```

Expected Output:

```
yesterday I eat a sandwich
I be run fast
```

## Solution

It looks like the following modules MUST be enabled for the lemmatizer to suceed:
* tok2vec
* tagger
* attribute_ruler

This initialization works:

`nlp = spacy.load("en_core_web_sm", disable=["parser", "ner"])`

## What is the problem

When you disable the modules needed for the lemmatizer to work, but leave the lemmatizer in place, **spaCy whould warn you that the lemmatizer is not going to work**, and perharps remove the lemmatizer altogether from the pipeline.

Instead spaCy silently fails. 

## Your Environment

- **spaCy version:** 3.0.0rc2
- **Platform:** Windows-10-10.0.18362-SP0
- **Python version:** 3.8.5
- **Pipelines:** en_core_web_sm (3.0.0a0), en_core_web_trf (3.0.0a0)

**Comment by adrianeboyd** [comment]
Yes, your analysis is correct. The tagger requires `tok2vec`, the `attribute_ruler` maps tag to pos, and the `lemmatizer` requires pos to lemmatize.

This kind of dependency analysis is going to be really hard to do at runtime in general. Imagine you add one custom component that assigns `token._.my_feature` and a second custom component that requires `token._.my_feature`. There's no easy way to know which attributes are read or assigned.

One thing we've tried to do is have a developer-provided static analysis of what each component `assigns` and `requires` that can be shown with `nlp.analyze_pipes()`. It works well for something like `merge_entities`, but it breaks down for `tok2vec`, `attribute_ruler`, and `lemmatizer`.

`tagger` doesn't necessarily require `tok2vec` (it can be configured with its own tok2vec, like `ner` is in this pipeline) and `attribute_ruler` can assign any token attribute. The `lemmatizer` may be a lookup lemmatizer that doesn't require any annotation, or it may require other attributes, so you can't give a general `requires` here, either.

I do think it would be reasonable to have the rule-based lemmatizer method warn you if it gets docs without `pos` set. The warning message wouldn't be able to tell exactly how to fix it (you might need a `morphologizer` or some other component), but at least you'd know why it wasn't going to work as expected and where to start looking.

**Comment by thiippal** [comment]
Thanks @raffaem for opening this issue: I also encountered this issue yesterday and was really confused until I came up with exactly the same initialisation procedure as you. I was about to file an issue but you got there first. 👍 

Great to know that this is being taken care of.
