### ISSUE TITLE
pycharm fail on spacy.load('en') : module' object has no attribute 'load'

### ISSUE THREAD

**Issue by ihabZhaika** [explosion/spaCy#650]
HI,
i download the library and installed the language pack , i tried to run the DEMO  app with ipython and no problem , but with pycharm i get an error

THE CODE :

```
import spacy
nlp = spacy.load('en')
doc = nlp(u'I like green eggs and ham.')
for np in doc.noun_chunks:
    print(np.text, np.root.text, np.root.dep_, np.root.head.text)
```

THE ERROR

```
Traceback (most recent call last):
  File "/home/ihab/PycharmProjects/nlp/spacy.py", line 1, in <module>
    import spacy
  File "/home/ihab/PycharmProjects/nlp/spacy.py", line 2, in <module>
    nlp = spacy.load('en')
AttributeError: 'module' object has no attribute 'load'

```

##  Environment
* **Operating System:** 
ubuntu 16.04
* **Python Version Used:** 
Python 2.7.12+
* **spaCy Version Used:** 
1.2.0

**Comment by aborsu** [comment]
Are you using the correct path for modules in pycharm.
By default pycharm doesn't use any path for modules to avoid having undefined modules installed in your project and making deployment easier to manage. 
This means that you need yo add your module to the pycharm path or tell pycharm that you are using spacy.
This might help: http://stackoverflow.com/questions/19885821/how-do-i-import-modules-in-pycharm

**Comment by ihabZhaika** [comment]
ok thanks
