### ISSUE TITLE
spaCy freezes my PC (memory: 100%, disk usage: 100%) regardless my corpus being small

### ISSUE THREAD

**Issue by raffaem** [explosion/spaCy#6500]
I have a very simple task: given a list of input documents, I have to split each document in sentences, each sentences in words, and save a list of lists of words. Example:
`in = ["Hello. I am Mark", "What is your name?"]`
Have to become:
`out = [["hello"], ["i","am","mark"], ["what", "is", "your", "name", "?"]]`
Yes, "I am Mark" is a different element because it is a different sentence.
Then i will pass the vector `out` to GenSim in order to train a word2vec model on it.

Here is my spaCy code.
Initialization:
```
nlp = spacy.load("en_core_web_sm", disable=["parser", "ner"])
nlp.add_pipe("sentencizer")
```
Processing:
```
def build_sent_corpus_spacy(incorpus):
    
    print("Using Spacy")
    
    corpus = []
    for docn,doc in enumerate(nlp.pipe(incorpus)):
        print(f"Processing {docn}/{len(incorpus)} ({docn/len(incorpus):.2%})", end="\r")
        for sent in doc.sents:
            sentl = list()
            for word in sent:
                if config["lemmatization"]:
                    word = word.lemma_
                # !! We need to lower here because stopwords are lowercase !!
                word = str(word).lower()
                if word not in string.punctuation and \
                word not in enstopwords and \
                count_alpha(word)>=1:
                    word = word.replace(".","")
                    sentl.append(word)
            corpus.append(sentl)
    return corpus
```
Here are some stats about my corpus (obtained with NLTK tokenization for the reasons afterwards):
```
N. documents: 2,344
N. sentences: 406,037
N. words: 11,385,332
Max sentences per doc: 4,915
Max word per sentence: 3,463
Max word per doc: 168,282
```

Well, when I call the `build_sent_corpus_spacy` function on my corpus my PC goes completely stuck. Using the task manager I can see that memory used is 100% (I have 16 GB of RAM) and  disk usage is 100%. The PC goes completely stuck and spaCy never ends its processing. I have to manually kill the python process.

And, please note, I am even using the "small" 20 MB linguistic model (*_sm), not the transformers one!

On a small sidenote, [this blog article](https://towardsdatascience.com/benchmarking-python-nlp-tokenizers-3ac4735100c5) compared different tokenizers and found spaCy to be the slowest.

How is spaCy fast? I don't think it scales well with document size.

Correct me if I am wrong or if there is something wrong in my initialization/processing.

## Info about spaCy

- **spaCy version:** 3.0.0rc2
- **Platform:** Windows-10-10.0.18362-SP0
- **Python version:** 3.8.5
- **Pipelines:** en_core_web_sm (3.0.0a0), en_core_web_trf (3.0.0a0)

**Comment by svlandeg** [comment]
What happens when you would just run 
```
doc_nr = 0
for doc in nlp.pipe(incorpus):
    doc_nr += 1
print(doc_nr)
```
?

**Comment by raffaem** [comment]
1. @svlandeg  When I run:

```
doc_nr = 0
for doc in nlp.pipe(incorpus):
    doc_nr += 1
    print(doc_nr, end='\r')
print(doc_nr)
```
The computer gets slower and slower until it freezes. After 5 minutes the number "1000" is displayed.
After 15 minutes form the start the code chunk did not finish processing yet and I killed the python process.
This timing to just go over the corpus is definitively too long.

2. When I use the transformer model, the situation "improves", in the sense that the computer does not freeze. CPU usage becomes 80%, RAM usage 60%-80%, GPU usage always 0% (although I have pytorch with CUDA 10.1). Again the algorithm never finishes, and I have to stop it manually.

**Comment by adrianeboyd** [comment]
What happens with spacy v2? For this kind of simple preprocessing, you're probably better off using a stable version. There's really no benefit from using a huge transformers model here, it's just going to be slower.

If you can pinpoint a particular text that causes problems (and can share your data with us, obviously), we can try to look into it, but from the information provided, it's hard for us to figure out what might be going on. Also try it without the tagger to see if it's possibly just the tokenizer causing problems and not the tagger. If you're not lemmatizing, this would all be much faster with `spacy.blank("en")`.

Your longest text sounds very long for typical spacy use, but this depends more on what components are used, where it's mainly `ner` and `parser` that run into issues. You may want to segment your texts into paragraphs before processing. You can see if you run into the max_length warning (which is in `nlp()` but not `nlp.pipe()`) on your texts:

```
for text in texts:
    doc = nlp(text)
```

For v3 `en_core_web_sm` without `ner` and `parser`, I'd expect the speed to be something around 10K words/minute on a modern laptop. The whole pipeline would probably be around 5K words/minute.
