### ISSUE TITLE
Transformer based word vectors

### ISSUE THREAD

**Issue by danielvasic** [explosion/spaCy#6511]
I was wondering if spaCy nightly is supporting similarity method for BERT trained transformer model. I have trained the model but fail to find semantic similarity on `Word`, `Doc`, `Span` with this error:

```
UserWarning: [W008] Evaluating Token.similarity based on empty vectors.
```

## Your Environment

============================== Info about spaCy ==============================

spaCy version    3.0.0rc2
Platform         Darwin-19.6.0-x86_64-i386-64bit
Python version   3.7.9                         
Pipelines        hr_pipeline (0.0.1)

**Comment by svlandeg** [comment]
I don't think that functionality is readily available, but you should be able to implement something yourself.

If you've trained a spaCy pipeline with a transformer component, you can access the data in `doc._.trf_data`. This holds the tensor outputs for the doc, the tokens data, and the alignment information. More information in the docs: https://nightly.spacy.io/api/transformer#transformerdata

You can also specify a `set_extra_annotations` function in the config, to store the data in the `Doc` in any other way you'd like: https://nightly.spacy.io/usage/embeddings-transformers#transformers-runtime

**Comment by danielvasic** [comment]
Thanks for the response,

Basically what I need to do is take the output hidden states calculate the average using the alignment information and I can set the vector value in the vocabulary to the token and then I can use the similarity method as is?

**Comment by svlandeg** [comment]
Yes - that sounds about right :-)

**Comment by danielvasic** [comment]
Thank You very much :-)

**Comment by danielvasic** [comment]
@svlandeg one more question, sorry for reopening the post but I have one more question. When setting the vector in vocabulary that is the same but based on the context has different vector, so for example the in two sentences "Apple je računalna tvrtka" ("Apple is an IT company") and "Imao je psa koji je se zvao Apple" ("He had a dog named Apple") the "Apple" has different vectors but the last occurrence of the word Apple overrides the initial vector so every word has the same vector as in FastText or Word2Vec models. I suppose there is another way to set contextual vectors but I could not find anything in the documentation. Here is my implementation based on the previous sugesstions:

```
for doc in docs:
    lengths = doc._.trf_data.align.lengths
    for i, token in enumerate(doc):
        trf_vector = []
        for len_idx in range(lengths[i]):
            trf_vector.append(doc._.trf_data.tensors[0][0][i+len_idx])
        trf_vector = np.array(trf_vector)
        parser.nlp.vocab.set_vector(token.text, np.average(trf_vector, axis=0))
```
