### ISSUE TITLE
Wheel support for linux aarch64[arm64]

### ISSUE THREAD

**Issue by odidev** [explosion/spaCy#6533]
**Summary**
Installing spaCy on aarch64 via pip using command "pip3 install spaCy" tries to build wheel from source code

**Problem description**
spaCy doesn't have wheel for aarch64 on PyPI repository. So, while installing spaCy via pip on aarch64, pip builds wheel for same resulting in it takes more time to install spaCy. Making wheel available for aarch64 will benefit aarch64 users by minimizing spaCy installation time.

**Expected Output**
Pip should be able to download spaCy wheel from PyPI repository rather than building it from source code.

@spaCy-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make spaCy wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by honnibal** [comment]
We're working on wheel support for more platforms. It's a matter of build automation, so it's not something that's easy for others to assist with.

Please do not open template issues on multiple repositories. It is not appreciated.
