### ISSUE TITLE
spacy.load() doesn't raise error on writing wrong parameters with wrong values

### ISSUE THREAD

**Issue by shyamcody** [explosion/spaCy#6536]
## How to reproduce the behaviour
`import spacy` 
`nlp = spacy.load('en_core_web_sm',garbage = ['haha'])`
I was expecting it to raise an issue saying that garbage is a unknown parameter. Problem with this bug is that, even if you forget to write disabling pipeline elements correctly, this doesn't give error. For example,
`nlp = spacy.load('en_core_web_sm',diable = ['ner'])` doesn't raise any issues and doesn't disable the ner component. 
## My Environment
* Operating System: ubuntu 18.04
* Python Version Used: 3.6.9
* spaCy Version Used: 2.3.4
* en_core_web_sm Version Used:  2.3.1

**Comment by adrianeboyd** [comment]
Yes, it was originally set up like this so you can pass arbitrary keyword arguments to various components while loading, but it does have a number of drawbacks.

We're not planning to modify this for v2, but with the new config system in spacy v3, `spacy.load` no longer allows arbitrary kwargs so this kind of error will be flagged for users more clearly.

**Comment by shyamcody** [comment]
so in spacy v3, it is resolved; and for v2 we'll have to look out for it. Thanks for the clarification!
