### ISSUE TITLE
"(8)" not correctly splitted in spacy 2.3.4

### ISSUE THREAD

**Issue by zhanqiwang** [explosion/spaCy#6552]
When you run the following code, "8)" is splitted as one token while all other similar texts are correctly taken apart.
## How to reproduce the behaviour

```
import regex as re
import spacy
nlp = spacy.load("en_core_web_sm", disable=["ner"])
s= """
(1) (2) (3) (4) (5) (6) (7) (8) (9) (10)
"""
doc = nlp(s)
has_break = re.compile("\n")

for t in doc:
    print(t.text, " - ", t.lemma_)
```
## Your Environment

* **spaCy version:** 2.3.4
* **Platform:** Windows-10-10.0.19041-SP0
* **Python version:** 3.8.6

**Comment by adrianeboyd** [comment]
See the duplicate issue #5742.
