### ISSUE TITLE
Missing documentation on dependency parsing results

### ISSUE THREAD

**Issue by kristall** [explosion/spaCy#657]
I used spacy to analyze a short (german) sentence and would like to know more about the used "names"

For example:
<--sb--- 
<-ROOT-- 
<--oa--- 
<--cd--- 
<--cj--- 
<--oa--- 
<--svp-- 

ROOT is the only "clear" one. I checked https://spacy.io/docs/api/annotation but in the given pdf (http://www.mathcs.emory.edu/~choi/doc/clear-dependency-2012.pdf) these abbrevations are not used.
Also following the links to ClearNLP only lead to https://emorynlp.github.io/nlp4j/components/dependency-parsing.html which also did not the contain the needed information.

Where can I find a legend of the used abbrevations?

**Comment by honnibal** [comment]
Ah, damn. This part of the docs needs to be generalised for German...

The German model was trained on the TIGER treebank. I'll find the docs and update the page.
