### ISSUE TITLE
word vectors missing

### ISSUE THREAD

**Issue by baziotis** [explosion/spaCy#659]
I want to use my own pretrained word embeddings. So i used `vocab.load_vectors()` and `vocab.dump_vectors()` methods  to create a binary file with the vectors for faster loading. Then i replaced the `vec.bin` in `\data\en_glove_cc_300_1m_vectors-1.0.0\vocab` so spacy will load my binary file from now on.

But the problem is that even though the words in my file are approximately 1.2M, the words in `spacy.vocab` containing vectors are less than half of them. Am i doing something wrong?

Here the exact process i followed:

**Step 1 : find how many words with vectors are in the `vocab`.**
```python
import spacy

en_nlp = spacy.load("en")
print("vocab size: ", len(en_nlp.vocab))
print("lexemes with vectors: ", sum(1 for lex in en_nlp.vocab if lex.has_vector))
```
**Output**
```
vocab size:  1297536
lexemes with vectors:  645315
```
even now there are less than i think they should be (~1M).

**Step 2 : load my the vectors from the text file, and dump them to a binary file.**
```python
nlp = spacy.load("en", add_vectors=lambda vocab: vocab.load_vectors(open("glove.twitter.27B.200d.txt", "r", encoding="utf-8")))
print("vocab size: ", len(nlp.vocab))
print("lexemes with vectors: ", sum(1 for lex in nlp.vocab if lex.has_vector))

nlp.vocab.dump_vectors("glove.twitter.27B.200d.bin")
```
**Output**
```
vocab size:  2313295
lexemes with vectors:  1193513
```
So the vectors are loaded fine, and now i have my binary file. Then i rename it to `vec.bin` and replace the default glove `vec.bin`.

**Step 3 : verify that spacy loads all my vectors correctly.**
```python
import spacy

en_nlp = spacy.load("en")
print("vocab size: ", len(en_nlp.vocab))
print("lexemes with vectors: ", sum(1 for lex in en_nlp.vocab if lex.has_vector))
```
**Output**
```
vocab size:  1297536
lexemes with vectors:  416700
```
So most of them are missing! (and there are even fewer than the defaults)

Am i doing something wrong?

## Environment
* **Python Version Used: 3.5** 
* **spaCy Version Used: 1.2.0**

**Comment by honnibal** [comment]
I think the problem is that you need to save the lexicon and strings as well after you write the vectors. I'm not 100% sure but I think the problem here is that you don't have a lexical entry for the words you're trying to add a vector for.

**Comment by cbaziotis** [comment]
I see. I inspected the vectors (i use the pretrained glove twitter vectors) and more than half of them are no even english words. 
So this must be it.

Can you give me an example on how to do it? Or is there a tutorial that you can point me to?
 
Thanks!

**Comment by ines** [comment]
Just going through some old issues – this will be addressed in the usage tutorial on getting and setting lexical attributes. You can check out the current draft in #581.  Closing this issue to keep the topic in one place.
