### ISSUE TITLE
Pip install fails in Windows

### ISSUE THREAD

**Issue by channita** [explosion/spaCy#661]
Hi! 

Unfortunately, when I try to Pip install SpaCy in my Windows system I get the following error:

error: Unable to find vcvarsall.bat
Failed building wheel for spacy

error: Unable to find vcvarsall.bat
Failed building wheel for ujson
Command "c:\users\cn\appdata\local\continuum\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\cn\\AppData\\Local\\Temp\\pip-build-21b_nkx7\\ujson\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\cn\AppData\Local\Temp\pip-t2445xiu-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\cn\AppData\Local\Temp\pip-build-21b_nkx7\ujson\

## My Environment
* **Operating System: Microsoft Windows [Version 10.0.14393]  
* **Python Version Used: Python 3.5.2
* **spaCy Version Used: Spacy 1.2.0

I have checked other error reports, but, unfortunately, can't figure out the reason for the mistake. Hope you can help me!

Thanks a ton in advance :)

**Comment by honnibal** [comment]
Hi,

You need to have a build environment installed -- a compiler etc. spaCy doesnt currently support wheel-only installation.
