### ISSUE TITLE
Sentencizer read model from disk

### ISSUE THREAD

**Issue by roelvanderburg** [explosion/spaCy#6615]
I re-trained the sentence tagger by way of [https://github.com/explosion/spaCy/issues/6382](https://github.com/explosion/spaCy/issues/6382).

However I do get a:

RegistryError: Cant't find './output_dir/model-best/senter' in registry spacy -> architectures. Available names: spacy-transformers.Tok2VecTransformer.v1 

Error when trying to read in the model. I'm trying to load the model from disk with below code.

```
nlp = spacy.load('nl_core_news_sm')

# Construction via create_pipe with custom model
# config = {"model": {"@architectures": "./output_dir/model-best/senter/model"}}
# senter = nlp.add_pipe(factory_name='sentencizer',name="senter_custom_roel", config=config)

senter = nlp.add_pipe(factory_name='sentencizer', name="senter_custom",config=config)
senter.from_disk("./output_dir/model-best/senter/model")


```
## Your Environment

- **spaCy version:** 3.0.0rc2
- **Platform:** macOS-10.16-x86_64-i386-64bit
- **Python version:** 3.8.5
- **Pipelines:** nl_core_news_sm (3.0.0a0)

**Comment by svlandeg** [comment]
The `@architectures` keyword in a config dictionary typically refers to a registered [architecture](https://nightly.spacy.io/api/architectures), and not a file location. 

You should be able to just load the whole `nlp` model back from file with 
```
nlp = spacy.load("outputdir/model-best")
```
