### ISSUE TITLE
Potential Bug in Tokenizer Exceptions English

### ISSUE THREAD

**Issue by dzelilas** [explosion/spaCy#6624]
Sorry if this has been brought up before but I was unable to dig up anything by searching. 

I noticed that the verb "cause" was being wrongly normalized to "because" even without an apostrophe that would mark a contraction exception, even though 'cause' wasn't e.g. on the lexeme norm lookup lists etc. Occurs both in empty English language and in model (en_core_web_sm)

Example:

     import spacy
     from spacy.lang.en import English
     nlp = English()
     doc = nlp ("Many factors cause heart disease")
     [t.norm_ for t in doc]

The output is:

`['many', 'factors', 'because', 'heart', 'disease']`

I saw something weird in lang/en/tokenizer_exceptions. I looked at lang/en/tokenizer_exceptions for the nightly build as well and it seems to be the same there as well.

The problem seems to be this part:  

    for exc_data in [
     {ORTH: "cause", NORM: "because"},

        {ORTH: "em", NORM: "them"},

        {ORTH: "ll", NORM: "will"},

        {ORTH: "nuff", NORM: "enough"},

    ]:
        exc_data_apos = dict(exc_data)

        exc_data_apos[ORTH] = "'" + exc_data_apos[ORTH]

        for data in [exc_data, exc_data_apos]:

            _exc[data[ORTH]] = [data]

This adds to the _exc dictionary entries with both the apostrophe-less forms and the apostrophe forms as keys. Changing this bit to:

    for exc_data in [  {ORTH: "cause", NORM: "because"},

        {ORTH: "em", LEMMA: PRON_LEMMA, NORM: "them"},

        {ORTH: "ll", LEMMA: "will", NORM: "will"},

        {ORTH: "nuff", LEMMA: "enough", NORM: "enough"}, ]:

        exc_data_apos = dict(exc_data)

        exc_data_apos[ORTH] = "'" + exc_data_apos[ORTH]

        for data in [exc_data_apos]:

           _exc[data[ORTH]] = [data]

Seems to resolve the issue in the sense that it only considers these to be contractions when preceded by an apostrophe.

I tested by changing the file in lang/en in a virtual environment and then loading the model as above. With the change:

     doc = nlp("Many factors cause heart disease 'cause heart disease is complex")

    [t.norm_ for t in doc]`

Output is:

`['many', 'factors', 'cause', 'heart', 'disease', 'because', 'heart', 'disease', 'is', 'complex']`

And now output is "correct" for the other words in the group as well (e.g. nuff vs. 'nuff). The other ones aren't a huge issue like "cause", but I guess they could show up in texts, like "em" could be wrongly capitalized "Em" as in e-minor or something.

This problem seems to be also present with models like en_core_web_sm. Using en_core_web running nlp.tokenizer.explain returns 'Special-1' in the above sentence for both apostrophe and non-apostrophe case.

     nlp = spacy.load("en_core_web_sm")

    nlp.tokenizer.explain("Many factors cause heart disease 'cause heart disease is complex")

Output:

`[('TOKEN', 'Many'), ('TOKEN', 'factors'), ('SPECIAL-1', 'cause'), ('TOKEN', 'heart'), ('TOKEN', 'disease'), ('SPECIAL-1', "'cause"), ('TOKEN', 'heart'), ('TOKEN', 'disease'), ('TOKEN', 'is'), ('TOKEN', 'complex')`

 "ll" without an apostrophe is also marked as Special-1. Looking at nlp.Defaults.tokenizer_exceptions wasn't useful everything seemed to be ok there. 

But in nlp.tokenizer.rules there is:

'cause': [{65: 'cause', 67: 'because'}]

Not familiar with model internals and how everything is generated so not sure how to fix in this case beyond manually removing from nlp.tokenizer.rules after loading.

* **spaCy version:** 2.3.5
* **Platform:** Windows-10-10.0.18362-SP0
* **Python version:** 3.7.9

**Comment by svlandeg** [comment]
Thanks for the report - and nice digging ;-)

You're right that this English tokenizer exception is resolving any `cause` or `'cause` to NORM `because`. I agree that this is definitely unideal and we should change this. I'm not sure about the other words, like `em`, `ll` and `nuff`. I suppose they were added also without apostrophe to accomodate for more noisy texts like tweets. For minimal impact, perhaps we can just change the `cause` one. I'll create a quick PR. Older models incorporate their own tokenizer so you won't see the change there, but if we merge the PR, then afterwards the change will be reflected in newly trained models.
