### ISSUE TITLE
catching errors with nlp.pipe

### ISSUE THREAD

**Issue by louisabraham** [explosion/spaCy#6630]
In a very large corpus, some of them have special characters. When launching en_trf_bertbaseuncased_lg with nlp.pipe, I get exceptions like the one under but I have no way to catch them. This is related to #4847.

```
/usr/local/lib/python3.6/dist-packages/spacy_transformers/pipeline/wordpiecer.py in pipe(self, stream, batch_size)
     74             docs = list(docs)
     75             outputs = self.predict(docs)
---> 76             self.set_annotations(docs, outputs)
     77             for doc in docs:
     78                 yield doc

/usr/local/lib/python3.6/dist-packages/spacy_transformers/pipeline/wordpiecer.py in set_annotations(self, docs, outputs, tensors)
    177                 self.model.max_len = max_len
    178                 raise ValueError(
--> 179                     f"Error calculating word pieces for sentences. Total number "
    180                     f"of wordpieces in the doc was {nr_word}, but adding up the "
    181                     f"wordpieces for its sentences we get {words_per_sent}. This "

ValueError: Error calculating word pieces for sentences. Total number of wordpieces in the doc was 1437, but adding up the wordpieces for its sentences we get 1435. This means there's a bug in the extension attributes or the tokenizer.add_special_tokens() logic, often when a spaCy sentence aligns against 0 wordpieces.
```

**Comment by svlandeg** [comment]
Right, so there are two issues here:

- The `ValueError` that is being thrown by `en_trf_bertbaseuncased_lg ` feels like a bug, though I couldn't say whether it's coming from `spacy-transformers` itself or from the underlying transformer library. For [spaCy v3](https://nightly.spacy.io/usage/v3), we've revamped the `spacy-transformers` library quite significantly. In v2, this was very much still experimental and I think fixing (potential) bugs in that old version will have lower priority now that we're on the verge of releasing 3.0. Ofcourse if this is still an issue in v3, we'd definitely need to look into this further. A reproducible code snippet with sample data would help us to investigate further.
- The error handling around `nlp.pipe()`. I understand the frustration here, and originally I thought that perhaps the solution suggested in https://github.com/explosion/spaCy/issues/4847 would make sense. I'm not so sure of that anymore though. The `pipe()` method work such that the input of a batch of documents is concatenated into larger tensors, and those tensors are fed to the Machine Learning models. The ML results are then interpreted by linking each row (orso) of the result tensor back to the corresponding document. However during processing by the Machine Learning model(s), those models don't have a concept of what is one document or which row(s) (or whatever) belongs to which doc. So it's going to be challenging to design this kind of error handling callback as proposed in that original issue. I'm not sure we can even do it on the granularity of one doc.

It's still annoying when you have just a few "offending" documents crashing an entire batch of data though. I guess what you could in your script, is to surround the `pipe` call with a `try-except` block, to at least ensure that processing of the next batch continues when you feel the thrown exception is not critical for the remainder of the processing. 

The other thing you could do, for debugging purposes, is when you surround the `pipe` call with a `try-except`, is to then in the `except` block iterate through the batch and process the docs in it one-by-one. This is ofcourse not efficient, but it will at least create a script that quickly identifies some "offending" documents, and you could isolate one such document and use it for a reproducible example to file a bug here ;-)

**Comment by louisabraham** [comment]
Thanks for your answer.

- I don't think it's a major bug of `en_trf_bertbaseuncased_lg`, my document was probably weird.
- Here the bug happened before the neural network, at the wordpiece level. I think one should be able to ignore conflicting documents (and have a special value returned).

About your suggestion: how can I resume the execution? Do I need some kind of custom batcher?

**Comment by svlandeg** [comment]
Currently it would require mimicking the code in `language.pipe` a little bit, something like this:
```
nlp = spacy.load("en_core_web_lg")
texts = ["Oh hi January " + str(i) for i in range(100)]
docs = (nlp.make_doc(text) for text in texts)
for name, proc in nlp.pipeline:
    docs = _pipe(proc, docs, batch_size=30)
print(f"Final docs: {len(list(docs))}") 

def _pipe(proc, docs, batch_size):
    if hasattr(proc, "pipe"):
        for batch in minibatch(docs, batch_size):
            try:
                # raising an error for demonstration purposes 
                if len(batch) == batch_size:
                    raise ValueError(f"Don't feel like processing {batch_size} items")
                yield from proc.pipe(batch, batch_size=batch_size)
            except:
                print(f"Error processing batch of length {len(batch)} - continuing with other batches.")
                # Alternatively, go through the docs one by one to see which one crashed
    else:
        # here, you can do error catching one-by-one
        yield from (proc(doc) for doc in docs)
```
This would generate a crash in the first 3 batches of 30 items, but it would still process the last 10:
>Error processing batch of length 30 - continuing with other batches.
Error processing batch of length 30 - continuing with other batches.
Error processing batch of length 30 - continuing with other batches.
Final docs: 10

Realistically you'd probably only have one crashing document, and you could go through the docs one-by-one in the `except` block when a whole batch fails.

To solve this more generally in the upcoming spaCy 3, I submitted a PR, cf https://github.com/explosion/spaCy/pull/6817.
