### ISSUE TITLE
Loading NER model from dump doesn't work

### ISSUE THREAD

**Issue by savvopoulos** [explosion/spaCy#664]
I'm using the EntityRecognizer.load method to load my model. This is seems to run successfully, but the resulting EntityRecognizer doesn't work properly; whereas the original one does.

Whereas https://github.com/explosion/spaCy/blob/master/examples/training/train_ner.py outputs:
```
Who WP  2
is VBZ  2
Shaka NNP PERSON 3
Khan NNP PERSON 1
? .  2
```

The loaded one outputs:
```
$ python3 load_ner.py
Who WP  2
is VBZ  2
Shaka NNP  2
Khan NNP  2
? .  2
```
(notice the missing ent_type_!)

I've included code to repro here:
https://github.com/savvopoulos/spaCy/commit/943f979ce4b80837b873fd3d10091c6db5b4b484

**Comment by honnibal** [comment]
Hey,

Sorry about the lack of clarity on this. I think others have been having trouble with this too.

There are a few problems with your code.

1. `EntityRecognizer.load()` is a classmethod --- it returns a new instance of `EntityRecognizer`. It doesn't modify the instance in place. So, your line `ner.load()` does nothing. What you need is `ner = EntityRecognizer.load()`

2. You should save and load the vocabulary as well as the entity recognition model.

3. You should either save and load the tagger, or not use the tagger when running the NER.

**Comment by savvopoulos** [comment]
Many thanks for your answer!

Re: 2
Why do I need to save + load the vocab, given that I'm using spacy's vocab?
I see you added this line: _ = nlp.vocab[word.orth]
Does this add ortho features for previously unknown words, and thus help with training?

Re: 3
Similarly, why save the tagger, given that I'm using spacy's?

Also:
Does having the tags/vectors for a document improve new NER's performance?

**Comment by savvopoulos** [comment]
BTW. If I use tagger.model.dump, I get:
```
Traceback (most recent call last):
  File "train_ner.py", line 82, in <module>
    main('ner')
  File "train_ner.py", line 77, in main
    nlp.tagger.model.dump(str(model_dir / 'pos' / 'model'))
  File "thinc/linear/avgtron.pyx", line 75, in thinc.linear.avgtron.AveragedPerceptron.dump (thinc/linear/avgtron.cpp:2754)
  File "thinc/linear/serialize.pyx", line 23, in thinc.linear.serialize.Writer.__init__ (thinc/linear/serialize.cpp:1521)
AssertionError
```

**Comment by honnibal** [comment]
Finally getting back on top of the backlog a bit.

Is this closable, given your PR #679 ?

**Comment by savvopoulos** [comment]
Yes, and they also still work under 1.5.
