### ISSUE TITLE
NER Scores at spaCy 3.0 ?

### ISSUE THREAD

**Issue by gennsev** [explosion/spaCy#6644]
I wonder if, with spaCy 3.0, we will finally get a way to extract the NER entities sconfidence scores. I have the impression that it is an upcomming feature, by some of the commits that I've been looking at (like [this one](https://github.com/explosion/spaCy/pull/6575/commits/096a8906a4202bf1d684722485d4933fe80ca258)), but I did not find anything regarding that on the documentation.

With spaCy 2.x, I used a method proposed by  [#3996](https://github.com/explosion/spaCy/issues/3996), [#881](https://github.com/explosion/spaCy/issues/881), [#831](https://github.com/explosion/spaCy/issues/831) and finally [#5917](https://github.com/explosion/spaCy/issues/5917). However, it does not work anymore, giving me the following error message: `AttributeError: 'English' object has no attribute 'entity'`

## Your Environment

- Operating System: Windows 10
- Python Version Used: 3.8
- spaCy Version Used: 3.0

**Comment by svlandeg** [comment]
This is indeed a work-in-progress that we're hoping to get ready for 3.0.

With respect to the old code referring to `nlp.entity`, you can replace that with `nlp.get_pipe("ner")`.

**Comment by gennsev** [comment]
> This is indeed a work-in-progress that we're hoping to get ready for 3.0.
> 
> With respect to the old code referring to `nlp.entity`, you can replace that with `nlp.get_pipe("ner")`.

Still it fails, but for a different reason.
Now I got the following: 
```
beams = nlp.get_pipe(\"ner\").beam_parse([doc], beam_width=16, beam_density=0.0001)
AttributeError: 'spacy.pipeline.ner.EntityRecognizer' object has no attribute 'beam_parse'
```
Should I suppose this attribute is no longer available at spaCy 3.0?

**Comment by svlandeg** [comment]
Oh, I thought you said you were using 2.x. 
But yea, for 3.0 it's work in progress. I think we can close this feature request and merge it with https://github.com/explosion/spaCy/issues/5917.

**Comment by metalaureate** [comment]
@svlandeg hi, apologies (and thank you), wondering where to ask this--I was using this article https://towardsdatascience.com/custom-named-entity-recognition-using-spacy-7140ebbb3718  to learn how to add new labels to the NER model, but it isn't compatible with spaCy 3, generating the error listed in this thread. Can you recommend an alternative tutorial for training new labels?

**Comment by polm** [comment]
@metalaureate If you have a question about usage the right place to ask is in [Discussions](https://github.com/explosion/spaCy/discussions). 

That article looks like a generic NER tutorial, maybe try following the [training docs](https://spacy.io/usage/training) or looking at the [example projects](https://github.com/explosion/projects/tree/v3/tutorials). If you'd like more details please open a discussion thread.
