### ISSUE TITLE
English POS incorrectly tagging some adjectives as verbs 

### ISSUE THREAD

**Issue by sachinsdate** [explosion/spaCy#6652]
## How to reproduce the behavior

```
import spacy
nlp = spacy.load("en_core_web_lg")

# Consider this string
s = 'broken window'
doc = nlp(s)
# tok =  'broken':
tok = list(doc)[0]
# The following should print 'ADJ' but it prints 'VERB':
print(tok.pos_)
# Let's try a different string:
s = 'playful dog'
doc = nlp(s)
# tok = 'playful':
tok = list(doc)[0]
# The following prints 'ADJ' as expected:
print(tok.pos_)
```

## Info about spaCy
* **spaCy version:** 2.3.5
* **Platform:** Windows-10-10.0.18362-SP0
* **Python version:** 3.7.4

**Comment by svlandeg** [comment]
There's a few things to note here:

- ML models will never be 100% accurate. We collect wrong predictions in [this thread](https://github.com/explosion/spaCy/issues/3052), but typically some wrong predictions are always to be expected and depend on the training data. You can [retrain](https://spacy.io/usage/training#example-train-tagger) the tagger to be more accurate on your specific dataset, or train one from scratch.
- That said, I don't think this particular case is inherently a wrong prediction - there is simply too little context for the tagger to make an informed guess. Sure, you could say that in this case it's more likely that "broken" is an adjective, but it could well be a verb too, e.g. "broken window. gained access."

I also did some tests with a new version (3.0.0a0) of `en_core_web_lg`:
```
import spacy
nlp = spacy.load("en_core_web_lg")
doc = nlp('broken window')
print([tok.pos_ for tok in doc if tok.text in ["broken", "window"]])
```
>['ADJ', 'NOUN']

The predictions across different versions of the models may differ slightly, as you see here. The result for `3.0.0a0` is what you're hoping to see with your model, but again, this sentence really provides too little context to obtain high confidence predictions.

```
import spacy
nlp = spacy.load("en_core_web_lg")
doc = nlp('I noticed the broken window.')
print([tok.pos_ for tok in doc if tok.text in ["broken", "window"]])
```
>['ADJ', 'NOUN']


```
import spacy
nlp = spacy.load("en_core_web_lg")
doc = nlp('broken window. gained access.')
print([tok.pos_ for tok in doc if tok.text in ["broken", "window"]])
```
>['VERB', 'NOUN']

**Comment by sachinsdate** [comment]
Thank you. I am closing the issue.

**Comment by svlandeg** [comment]
Welcome!
