### ISSUE TITLE
KeyError: "[E002] Can't find factory for ''tagger''

### ISSUE THREAD

**Issue by dankaiv** [explosion/spaCy#6676]
Hi,

I'm trying to train tagger for Serbian from Jupiter notebook based on the process described on https://spacy.io/api/cli.

!python -m spacy debug-data sr {JSON_DIR}/file-train.json {JSON_DIR}/file-dev.json --pipeline 'tagger' --verbose
and getting error:
Training pipeline: 'tagger'
[x] Pipeline component ''tagger'' not available in factories

when I try to train the tagger:
!python -m spacy train sr {MODEL_DIR} {JSON_DIR}/file-train.json {JSON_DIR}/file-dev.json --pipeline 'tagger' --n-iter 2

I'm getting the following error:
KeyError: "[E002] Can't find factory for ''tagger''. This usually happens when spaCy calls `nlp.create_pipe` with a component name that's not built in - for example, when constructing the pipeline from a model's meta.json. If you're using a custom component, you can write to `Language.factories[''tagger'']` or remove it from the model meta and add it via `nlp.add_pipe` instead."

I cannot find anywhere how to add components into the factory. There is no spacy model for Serbian and I haven't created it before.

## Info about spaCy

* **spaCy version:** 2.3.5
* **Platform:** Windows-10-10.0.17763-SP0
* **Python version:** 3.7.6

Thanks and regards,
Danka,

**Comment by adrianeboyd** [comment]
Try specifying the pipeline without the quotes: `--pipeline tagger`

**Comment by dankaiv** [comment]
Thanks, debug command is working now. I remember that I tried this before but still training command got stuck without any output so I thought it might be wrong solution solution. 
The training command still not working, it's getting stuck without any message. The same code is working fine on spacy 2.2. The only thing I see strange is that there are items where POS tag is an empty string.

**Comment by svlandeg** [comment]
What do you mean exactly by getting "stuck"? There's just no output at all? 

Could you try running on a very small dataset - for instance keep only 2 instances in both the training and dev file, then run the command again, and share the full output log?

**Comment by dankaiv** [comment]
Yes,  in Jupiter notebook I didn't get any output, the command got stuck and couldn't get completed. Then I tried the same train command in CLI and it worked well. 
Still not sure why it was not working in Jupyter. I prepared the files for testing as you said - how to log in this case when the command cannot finish properly?

**Comment by svlandeg** [comment]
If the command works on the CLI, but not in the notebook, I'm not sure there's an issue with spaCy, really. Perhaps the notebook gets a time out? Does not have enough memory?

If you train on the much smaller files in the notebook, what happens?

**Comment by dankaiv** [comment]
I tried with a smaller dataset and it worked but only for very small (few senetences on Jupyter) and around 100 in Spyder. Anyway, this training serves for educational purposes and has only 1500 sentences in the dataset and that shouldn't be a problem.
thanks for help!

**Comment by svlandeg** [comment]
Sure, you're welcome! If you run into any other problems, feel free to open a new issue.
