### ISSUE TITLE
Doc: Full Pipeline & Custom tokenization with given lists of strings ?

### ISSUE THREAD

**Issue by juanmirocks** [explosion/spaCy#668]
@honnibal first of all, thank you to you and your team for creating such a great library. It simplifies the life of many of us.

Regarding custom tokenization, I hope you can clarify what is the preferred spaCy way of using custom tokenization with given lists of strings yet without access to the original splitting function.

Concretely, my case:

* I had already tokenized strings into lists of split substrings, e.g. `["spaCy", "is", "awesome"]`
* I do not necessarily have access to the original splitting function (thus I cannot use [this tutorial](https://spacy.io/docs/usage/customizing-tokenizer)) or [this answer](https://github.com/explosion/spaCy/issues/42#issuecomment-135755528)
* I want to apply at least both tagging and parsing
* And btw this [tutorial link](https://spacy.io/docs/tutorials/byo-annotations) is broken :)

As far as I read from a previous answers of yours, I have can do it by:

```python
doc = nlp.tokenizer.tokens_from_list(["spaCy", "is", "awesome"])
nlp.tagger(doc)
nlp.parser(doc)
# possibly more: nlp.entity(doc), ... other?
print('🎉')
```

That appears to work just fine. However, this feels to me a bit hacky and I'm worried that maybe now or in future changes of spaCy, I am just not applying each step of the pipeline in the right order or actually applying every step of the pipeline.

Or is this the solution?

```python
doc = nlp.tokenizer.tokens_from_list(["spaCy", "is", "awesome"])
for pipe in filter(None, nlp.pipeline):
  pipe(doc)
print('🎉')
```

Ideally, I would like to just do something like:

```python
nlp(["spaCy", "is", "awesome"])
print('🎉')
```

Hope you can clarify the preferred way for custom tokenization :)

Thank you again.

**Comment by honnibal** [comment]
Hey,

Probably the best way is to customize the `make_doc` function. There are currently three options for doing this (which is...not great. Which is why I've held off finalising this in the docs yet — I'm not 100% happy.)

* Override the `make_doc()` method on the `Language` class

* Pass a function to the `make_doc` keyword of `Language.__init__` or `spacy.load()`

* Pass a function to the `create_make_doc` keyword of `Language.__init__` or `spacy.load()`

**Comment by juanmirocks** [comment]
Thank you very much Matthew,

I will wait for a final recommended way until I change my current working
code.

Feel free to close the issue if this is not a priority for the project.

**Comment by ines** [comment]
This problem will finally be easier to solve in v2.0 – see the alpha docs for more details: https://alpha.spacy.io/docs/usage/customizing-tokenizer
