### ISSUE TITLE
Inconsistent Iteration Results

### ISSUE THREAD

**Issue by fatihbozdag** [explosion/spaCy#6703]
## Your Environment

Greetings,

I have been studying dative alternation in corpora and struggling with the inconsistent results. Here is my code;

```
dative_results_directory = "C:/Users/fatih/OneDrive/Belgeler/Dative/turkish"
access_rights = 0o755
nlp = spacy.load("en_core_web_lg")
nlp.max_length = 150000000
dative_sents = []
nsubj = []
root = []
dative = []
direct_obj = []
pre_obj = []
sents = []
nsubj_pre = []
root_pre = []
dative_pre = []
direct_obj_pre = []
sent_pre = []
dative_sentences_pre = []
dative_sentences = []
print("Please choose a text file from directory")
text = open(askopenfilename(), encoding = "utf-8").read()

def text_preproc(x):
  x = x.lower()
  x = x.encode('ascii', 'ignore').decode()
  x = re.sub(r'https*\S+', ' ', x)
  x = re.sub(r'@\S+', ' ', x)
  x = re.sub(r'#\S+', ' ', x)
  x = re.sub(r'\'\w+', '', x)
  x = re.sub('[%s]' % re.escape(string.punctuation), ' ', x)
  x = re.sub(r'\w*\d+\w*', '', x)
  x = re.sub(r'\s{2,}', ' ', x)
  return x

print("Text files cleaned succesfully, now parsing text...")
 
doc = nlp(text_preproc(text))

print("dative sentences are being extracted...")

for token in doc:
    if token.dep_ == "dative" and token.head.pos_ == "VERB":
        dative_sents.append(token.sent)
        
for t in dative_sents:
            for d in t:
                if d.dep_ == "dative" and d.pos_ != "ADP" and d.head.pos_ == "VERB":
                    for n in d.head.children:
                        if n.dep_ == "nsubj":
                            for x in d.head.children:
                                if x.dep_ == "dobj":
                                    
                                        dative.append(d.text)
                                        root.append(d.head.text)
                                        nsubj.append(n.text)
                                        direct_obj.append(x.text)
                                        dative_sentences.append(d.sent)
                                                                            
for a in dative_sents:
            for b in a:
                if b.dep_ == "dative" and b.pos_ == "ADP" and b.head.pos_ == "VERB":
                    for m in b.head.children:
                        if m.dep_ == "nsubj":
                            for k in b.head.children:
                                if k.dep_ == "dobj":
                                    for l in b.children:
                                        if l.dep_ == "pobj":
                                    
                                         dative_pre.append(b.text)
                                         root_pre.append(b.head.text)
                                         nsubj_pre.append(m.text)
                                         direct_obj_pre.append(k.text)
                                         pre_obj.append(l.text)
                                         dative_sentences_pre.append(b.sent)
                                         
            
dative_without_pre = pd.DataFrame({"Nsubj" : nsubj, "Verb" : root, "Dative" : dative, "Direct_Obj" : direct_obj, "Dative_Sentences" : dative_sentences})
dative_with_pre = pd.DataFrame({"Nsubj" : nsubj_pre, "Verb" : root_pre, "Direct_Obj" : direct_obj_pre, "Dative" : dative_pre, "Prepositional Object": pre_obj, "Dative_Sentences" : dative_sentences_pre})
``` 

Problem is that I see dative_sents has 376 span(dative sentences). However, when combined dative_sentences (this is the dative alternation without preposition) and dative_sentences_pre (this is the datives with prepositional phrase), overall sentence (span number) does not match the original number of span in list dative_sents. 

Why is the difference? 

```
dative_sentences list size 126
dative_sentences_pre list size 121 
dative_sents list size 376

```

Also itireation over noun_chunks provide different results;

```
dative_sents = []
for nc in doc.noun_chunks:
    if nc.root.dep_ == "dative" and nc.root.head.pos_ == "VERB":
        dative_sents.append(nc.sent)
```
`dative_sents list size 167`

## Info about spaCy

* **spaCy version:** 2.3.5
* **Platform:** Windows-10-10.0.19041-SP0
* **Python version:** 3.8.5
*  Environment Information: Anaconda - Spyder

**Comment by svlandeg** [comment]
I'm not sure I understand your question/problem. You're restricting the results in `dative_sentences` and `dative_sentences_pre` by filtering on properties other than just `token.dep_` and `token.head.pos_`, so it seems plausible that some of your original sentences in `dative_sents` didn't make it through those filters?

Also, you're appending sentence spans to a list, but what is preventing you from adding (and counting) the same sentence more than once? Is that on purpose?

If I were you, I'd investigate in a bit more detail which sentences are not in either of your two result sets anymore, and try to figure out why. Perhaps your filters are not doing exactly what you think they're doing?

FYI - in general, these kind of usage questions are best asked at the [Discussions forum](https://github.com/explosion/spaCy/discussions). Github has temporarily disabled the feature to move an issue to there, otherwise I would have done this myself. But we do try to keep the issue tracker more focused on actual bugs, so please consider posting these kind of questions on the Discussions forum instead. I think the forum has a more natural way of supporting community collaboration rather than this issue-ticket system ;-)

**Comment by fatihbozdag** [comment]
Well, here is the thing. There are two different structures for `datives`. First one is like `"I gave him money, Nsubj/Verb/Dative/DirectObj" `and the second one is with `prepositions, "I gave money to him, Nsubj/Verb/Directobj/Preposition/Prepositional Object"`. That's why I filtered sentences and created two list. The thing I am trying to explain, `dative_sents` includes all sentences with two variation. However, when filtered sizes do not match. All the sentences in `dative_sents `are sentences with at least one` token's dep_` is `"dative".` There are only two options for datives. It can be `noun/pronoun or preposition`. So first filter is for extracting `datives `as `noun/pronouns `excluding` prepositional ones`. Second one is extracting `datives` with `prepositions `excluding ones with `dative as noun/pronoun`. So total size of `dative_sentences` + `dative_sentences_pre` must be equal to `dative_sents`, yet it is not. 

Also when iterated via token, total number of sentences are different from the number of sentences iterated via noun_chunks. Why so? They are supposed to refer to same pattering, at least in my case. Am I wrong?

I thought I started the topic as general/usage related issues. Should I post the same question to general discussion section?

**Comment by fatihbozdag** [comment]
Fixed! 

I've just removed the code;

```
for token in doc:
    if token.dep_ == "dative" and token.head.pos_ == "VERB":
        dative_sents.append(token.sent)
```
and now everything is so far so good. Rather than iterating over `span`, I applied loop to` doc `and no problem.
