### ISSUE TITLE
Danish noun_chunk is always empty

### ISSUE THREAD

**Issue by KennethEnevoldsen** [explosion/spaCy#6708]
## How to reproduce the behavior

As seen in the following minimal example the noun_chunks is always empty for Danish. This seems like a potential bug. The dataset used here contains >4000 samples.

```
import datasets  # huggingface's datasets

import spacy

# load sample danish dataset
ds = datasets.load_dataset("dane", split="train")

nlp = spacy.load('da_core_news_lg')
docs = nlp.pipe(ds["text"])

max_length_noun_chunks = max([len(list(doc.noun_chunks)) for doc in docs])
print(max_length_noun_chunks)
```

```
0
```

## Your Environment

* **spaCy version:** 2.3.2
* **Platform:** macOS-10.15.7-x86_64-i386-64bit
* **Python version:** 3.8.5
* **Models:** en

**Comment by svlandeg** [comment]
Hi! The noun chunker for Danish has been [implemented](https://github.com/explosion/spaCy/pull/6246) very recently, and will be available in the next release. Currently, `doc.noun_chunks` returns an empty list when it's not (yet) implemented, which is kind of confusing.

**Comment by adrianeboyd** [comment]
I think we could change this in v3 to do `raise NotImplementedError` instead? I remember mentioning it in https://github.com/explosion/spaCy/discussions/6337. Can anyone think of any particularly bad side effects of changing this?

**Comment by svlandeg** [comment]
I agree that a `NotImplementedError` would make more sense!

**Comment by KennethEnevoldsen** [comment]
Thanks for the quick response 🙏

Not implemted yet would indeed make a lot of sense. The only issue is that I probably wouldn't have gotten to know that the feature was indeed implemented.

**Comment by KennethEnevoldsen** [comment]
For any other having this issue, installing the newest Spacy version from github solve the issue (as per previous comment).
```
pip uninstall spacy
pip install git+https://github.com/explosion/spaCy
```
