### ISSUE TITLE
Incorrect POS Tagging 

### ISSUE THREAD

**Issue by catherinealvarado** [explosion/spaCy#673]
I wrote the following function to get POS tags for sentences:

```
def pos_tup_list(s):
    processed = nlp(s)
    tup_list = []
    for token in processed:
        tup_list.append((str(token),token.pos_))
    return tup_list
```

When I check the tags for my, your, his, her, its, our, their, and ours I get incorrect tags. Look below:

`print(pos_tup_list("My cat is cute"))`
`print(pos_tup_list("Your cat is cute."))`
`print(pos_tup_list("His cat is brown."))`
`print(pos_tup_list("Her dog is cute!"))`
`print(pos_tup_list("The cat hurt its paw."))`
`print(pos_tup_list("Our plane won."))`
`print(pos_tup_list("Their plane won."))`
`print(pos_tup_list("Maybe it is ours"))`

`[('My', 'ADJ'), ('cat', 'NOUN'), ('is', 'VERB'), ('cute', 'ADJ')]`
`[('Your', 'ADJ'), ('cat', 'NOUN'), ('is', 'VERB'), ('cute', 'ADJ'), ('.', 'PUNCT')]`
`[('His', 'ADJ'), ('cat', 'NOUN'), ('is', 'VERB'), ('brown', 'ADJ'), ('.', 'PUNCT')]`
`[('Her', 'ADJ'), ('dog', 'NOUN'), ('is', 'VERB'), ('cute', 'ADJ'), ('!', 'PUNCT')]`
`[('The', 'DET'), ('cat', 'NOUN'), ('hurt', 'VERB'), ('its', 'ADJ'), ('paw', 'NOUN'), ('.', 'PUNCT')]`
`[('Our', 'ADJ'), ('plane', 'NOUN'), ('won', 'VERB'), ('.', 'PUNCT')]`
`[('Their', 'ADJ'), ('plane', 'NOUN'), ('won', 'VERB'), ('.', 'PUNCT')]`
`[('Maybe', 'ADV'), ('it', 'PRON'), ('is', 'VERB'), ('ours', 'ADJ')]`

**Comment by honnibal** [comment]
Thanks! I think this is probably related to #593

**Comment by ines** [comment]
Closing this, since it definitely seems to be related to #593. The issue will be fixed with the next data release!
