### ISSUE TITLE
Empty assertion errror when loading KB from disk

### ISSUE THREAD

**Issue by Joozty** [explosion/spaCy#6730]
## How to reproduce the behaviour
I was facing an empty assertion error when I tried to load KB from disk. Since I had too many aliases it was hard to debug this error. After some time I found out it was caused by empty alias (which is actually my bad and wrong usage I guess). It would be nice if you can make this assertion error more verbose. Thanks a lot :)

```python3
import spacy
from spacy.kb import KnowledgeBase

nlp = spacy.load("en_core_web_md")
kb = KnowledgeBase(vocab=nlp.vocab, entity_vector_length=nlp.vocab.vectors_length)
kb.add_entity(
    entity="1",
    freq=148,
    entity_vector=nlp("1").vector
)

kb.add_alias(
    alias="",
    entities=["1"],
    probabilities=[0.4],
)

kb.add_alias(
    alias="t",
    entities=["1"],
    probabilities=[0.4],
)

kb.to_disk("kb/")
kb.from_disk("kb/")
```

Output:
```
Traceback (most recent call last):
  File "/Documents/project/project/test.py", line 42, in <module>
    kb.from_disk("kb/")
  File "spacy/kb.pyx", line 342, in spacy.kb.KnowledgeBase.from_disk
  File "/Documents/project/venv/lib/python3.8/site-packages/spacy/util.py", line 1085, in from_disk
    reader(path / key)
  File "spacy/kb.pyx", line 340, in spacy.kb.KnowledgeBase.from_disk.lambda2
  File "spacy/kb.pyx", line 471, in spacy.kb.KnowledgeBase.read_contents
AssertionError
```

## Your Environment

* Operating System: Ubuntu 20.04.1
* Python Version Used: 3.8
* spaCy Version Used: spacy-nightly 3.0.0rc2

Possible duplicate of https://github.com/explosion/spaCy/issues/4674

**Comment by svlandeg** [comment]
Thanks for the report and reproducible example! That's always very appreciated :-)

You're right that it should warn/error with a more user-friendly message earlier on in the pipeline. I'll have a look.

**Comment by svlandeg** [comment]
FYI - PR https://github.com/explosion/spaCy/pull/6840 will resolve this by raising an error specifically when an empty string is added as alias. There's also an additional fall-through that raises an error when an alias could not be added for any other reason - to avoid the more cryptic AssertionError you got. I've also updated the documentation to clarify that empty aliases should be avoided.

Thanks again for the report!
