### ISSUE TITLE
Adding text categories to an existing model is not allowed?

### ISSUE THREAD

**Issue by rsoika** [explosion/spaCy#6748]
I have a general question about text categorizing. 

As far as I understand, it is not possible to add a new Category in an already existing model. If I load a 'textcat' pipe from an existing model, I am not allowed to add new categories. As a result the following code will not work:

```
 nlp = spacy.load(modelPath) 
 textcat = nlp.get_pipe("textcat")
 textcat.add_label("my_new_category")
```

Is this correct? 

This implies that I have to know all categories for my model before I start the training for a new empty model. 

This behaviour seems to be different to the Entity Recognition feature. When I get a 'ner' pipe from an existing model I can provide new entities and spyCy will refine the model. 

I just ask this, because form the documentation and examples (which in general are really great!) this restriction is not clearly documented.

**Comment by adrianeboyd** [comment]
That's right, you can't add new labels to an existing textcat model in v2. (You will be able to to in v3, though!)

It depends on the component (you also can't add labels to a tagger) and you're right that this isn't clearly documented.

**Comment by rsoika** [comment]
ok, thanks a lot for clarifying.

**Comment by rsoika** [comment]
Sorry to reopen this issue. But I did not found how this works in v3. I did a lot of testing but struggled with adding new cats to an existing model. See also my new discussion thread here: https://github.com/explosion/spaCy/discussions/6905
Can you please give me a hint...

**Comment by svlandeg** [comment]
I'm afraid the `textcat` components is not actually resizable in v3, only the NER is. You can check this yourself by calling `pipe.is_resizable`.

Let's continue the discussion on the forum, and I'll close this issue again to avoid duplicate conversations ;-)
