### ISSUE TITLE
Should GoldParse.__init__ accept doc=None?

### ISSUE THREAD

**Issue by themrmax** [explosion/spaCy#6768]
Not sure if this is bug exactly (the [GoldParse API documentation](https://spacy.io/api/goldparse) isn't specific on whether the `doc` argument is optional or not, but given that there is a `words` argument, it would be nice to not have to pass in `doc` when this argument has been specified
## How to reproduce the behaviour
```
from spacy.gold import GoldParse

annotation = GoldParse(words=["some", "words"], cats={"mylabel": 1.0})
```
produces the following error.
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-28-f161c45966e4> in <module>
----> 1 annotation = GoldParse(words=["some", "words"], cats={"mylabel": 1.0})

gold.pyx in spacy.gold.GoldParse.__init__()

TypeError: __init__() takes at least 1 positional argument (0 given)
```

My current workaround is something like the following, but would be nice to avoid this unless it is still necessary for a reason that I am missing.

```
from spacy.gold import GoldParse
import spacy

tokenizer = spacy.load('en_core_web_sm').tokenizer
annotation = GoldParse(tokenizer(" ".join(["some", "words"])), cats={"mylabel": 1.0})
```

## Your Environment

* **spaCy version:** 2.3.5
* **Platform:** Darwin-20.2.0-x86_64-i386-64bit
* **Python version:** 3.7.4

**Comment by svlandeg** [comment]
The `doc` argument is indeed required. You can't really pass in just the `words` - you would still be lacking information such as the spaces (which words are followed by space and which aren't?) and the vocab. In the `GoldParse` constructor, we don't have access to the `nlp` object or tokenizer, so you can't just recreate the `doc` from the `words`.

In your code, you can do:
```
doc = Doc(my_vocab, words=words, spaces=spaces)
gp = GoldParse(doc, words=words, cats={"mylabel": 1.0})
```

**Comment by themrmax** [comment]
@svlandeg thanks for the response! So is the words keyword redundant then, maybe it should be removed from the `GoldParse` API? I.e. is there an example where the `words` in the `GoldParse` would be different than the `words` in the `Doc`?

**Comment by svlandeg** [comment]
If you leave the `words` blank, they will indeed be deduced from the provided `doc`:
```
if words is None:
    words = [token.text for token in doc]
```
However, there is definitely a use-case for providing both the `doc` ànd the `words`, which is when the tokenization of your pipeline does not align with the tokenization in your gold-standard dataset. To avoid having gold entities that don't align to token boundaries, you'd provide the words as they are defined in the gold dataset, and `GoldParse` will align them behind the scenes to the tokens that are in the original `doc`, at the same time also transferring the alignment of other annotations like entities.

**Comment by themrmax** [comment]
Thanks for the clarification @svlandeg, this makes sense now!
