### ISSUE TITLE
Phrasematcher; OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by fatihbozdag** [explosion/spaCy#6770]
## How to reproduce the behaviour

Greetings;

I am trying to use Spacy PhraseMatcher with token attr `'IS_SENT_START'`. I guess like other attributes like '`IS_PUNCT`' it should be possible to use the is_sent_start attr yet I got the following error.

```
`matcher = PhraseMatcher(nlp.vocab, attr = "IS_SENT_START")
Traceback (most recent call last):

  File "<ipython-input-74-c8e7d50d6aec>", line 1, in <module>
    matcher = PhraseMatcher(nlp.vocab, attr = "IS_SENT_START")

  File "phrasematcher.pyx", line 63, in spacy.matcher.phrasematcher.PhraseMatcher.__init__

OverflowError: Python int too large to convert to C long`
```

Here is the sample code;

```
import spacy
nlp = spacy.load('en_core_web_sm')
from spacy.matcher import PhraseMatcher
sub_list = ['however', 'although', 'on the other hand', 'nonetheless']
patterns = [nlp.make_doc(text) for text in sub_list]
matcher = PhraseMatcher(nlp.vocab, attr = 'IS_SENT_START')
```

Why so? I am trying to see if phrases in list are sent_start = `True or False`. No problem with Matcher yet it is not working with Phrasematcher. Can you help me with the solution or a work around? 

## Your Environment

* Operating System: macOS Catalina
* Python Version Used: 3.7.9
* spaCy Version Used: 2.0
* Environment Information: Anaconda-Spyder

**Comment by svlandeg** [comment]
Hi! 

The error the matcher throws should definitely be more user-friendly, and the documentation should be updated too.

But you can make this work with `attr='SENT_START'`. Note that this will make the `PhraseMatcher` look at sentence segmentation, and so you'll have to compile your patterns with `nlp()` instead of `nlp.make_doc(text)` to ensure that the parser runs (which does the sentence segmentation in `en_core_web_sm`)

This should work:
```
import spacy
from spacy.matcher import PhraseMatcher

nlp = spacy.load('en_core_web_sm')
sub_list = ['This is nice. Extraordinary.']
patterns = [nlp(text) for text in sub_list]    
```
The pattern will now be `[True, None, None, None, True, None]`
```
matcher = PhraseMatcher(nlp.vocab, attr='SENT_START')
matcher.add("TerminologyList", None, *patterns)
text = "It is awesome. Great. Just great. What I think? Awesome."
doc = nlp(text)
matches = matcher(doc)
for match_id, start, end in matches:
    span = doc[start:end]
    print(start, end, "-->", span.text, [t.is_sent_start for t in span])
```
This prints
```
0 6 --> It is awesome. Great. 
9 15 --> What I think? Awesome.
```

**Comment by svlandeg** [comment]
FYI - the `Matcher` rewrites `IS_SENT_START` to `SENT_START` under the hood, so I've added the same logic to `PhraseMatcher` so it would work more as expected/documented.

**Comment by fatihbozdag** [comment]
Yet I got an other issue. When added `attr = Sent_Start`, Phrasematcher missess the words in the list. 

```
nlp = spacy.load('en_core_web_lg')
sub_list =['Although', 'However', 'Nonetheless']
patterns = [nlp(text) for text in sub_list]
matcher = PhraseMatcher(nlp.vocab, attr='SENT_START')
matcher.add("TerminologyList", None, *patterns)
text = open('F:/Learner Corpora/onetextfiles/turkish.txt').read()
doc = nlp(text)
```
and
```
matcher = PhraseMatcher(nlp.vocab)
patterns = [nlp(text) for text in sub_list]
matcher.add("TerminologyList", None, *patterns)
matches = matcher(doc)
for match_id, start, end in matches:
    span = doc[start:end]
    print(start, end, "-->", span.text, span.sent)
```

This way results the sentences expects with phrases stated in the pattern. If I drop the `attr = SENT_START`, I got the list of phrases stated in the sub_list. 

**Output with attr = Sent_Start** 

```
for match_id, start, end in matches:
    span = doc[start:end]
    print(start, end, "-->", span.text, span.sent)
For For example; you can live in a house in which all the people want to live but can't and have a car which the poor even can't see in their dreams, also you wear the best clothes, eat the best things, go to the best places.
25983 25984 --> In In short , you are the best, the most powerful and it is very well known that " money " brings you this power as it opens all the locked doors .

26017 26018 --> Moreover Moreover, you are the best-hearted person in the world because you have "MONEY " and you are the only person that the others can benefit from you not the poor as poors' heart
26055 26056 --> can can ' t give anything to others expect their friendship, so,, your money makes you to have a good heart itself .
```

**Output without `attr Sent_Start**
`

```
for match_id, start, end in matches:
    span = doc[start:end]
    print(start, end, "-->", span.text, span.sent)
    
1422 1423 --> Although Although men and women are said to have the equal rights, in all societies of the world, the men are one step forward from women.
1670 1671 --> Although Although there are magnificent celebrations for boys under the name of "sÃ¼nnet dÃ¼ÄŸÃ¼nÃ¼", the passing of the little girls from the childhood to the youth is kept secret.
2152 2153 --> However However, women haven't given the same rights for a long time past, they can compete with men in every subject; especially we can come across with this situation in this period.
2389 2390 --> However However it is different for the teachers.
3440 3441 --> Although Although, women are treated as inferior, they can do anything what men do.
4383 4384 --> Although Although I cheated in the exams I confess that it is not fair .
```

**Comment by adrianeboyd** [comment]
The `PhraseMatcher` is **only** matching on the provided attribute, so it's only comparing `[t.is_sent_start for t in pattern_doc]` to see if the same sequence of `[True, False, False, False, ...]` appears in the doc you're processing. It's not looking at the token text at all. This is probably not what you want to do?

What you actually want is to find phrases at the start of sentences, maybe? For that, you'd need to use the `Matcher` instead and add `"SENT_START": True` to the right token in the pattern.

(To be honest, I can't imagine very many sensible uses of `PhraseMatcher(attr="IS_SENT_START")`. It's just not enough information to give results other than very simple things like the first three tokens in each sentence, which you don't need a `PhraseMatcher` to find.)

**Comment by fatihbozdag** [comment]
I use `PhraseMatcher` since I would like to look up a `list `of `SCONJ` in a `doc`. In some cases, when the phrase itself is more than one `token,` like `'on the other hand'` and since the `list` consists of more than 20 phrases, it is not enough to use `Matcher` or simple for loop with `token.is_sent_start`. I want to find `phrases` listed in `sub_list` if they are at the start of a sentence.

**Comment by adrianeboyd** [comment]
Yeah, you'll have to use the `Matcher` for this. You can programmatically generate the matcher token patterns dicts from docs to get the right tokenization and add `SENT_START` in the right place.

**Comment by fatihbozdag** [comment]
can you please share a sample code? I do not think I am eligible to code that.

**Comment by adrianeboyd** [comment]
Sorry, that's out of the scope of the support we're able to provide here.

Then I'd recommend taking a step back and writing the patterns for your phrases by hand instead of automatically generating them. The spaCy course (https://course.spacy.io) is a good place to start to learn how to write `Matcher` patterns. Chapter 1, Section 10 is where the patterns are introduced. There are a lot of examples in the docs, too: https://spacy.io/usage/rule-based-matching

**Comment by fatihbozdag** [comment]
Thanks anyway. Figured out already. 

Regards.
