### ISSUE TITLE
Different NER results on two instances of the same pipeline

### ISSUE THREAD

**Issue by kdutia** [explosion/spaCy#6774]
## How to reproduce the behaviour
I have two identical spaCy pipelines set up using `en_core_web_trf`, NER, some EntityRuler components, and a custom rule-based component.

For the text "Seal Matrix (reversed), Muswell Hill & Palace Railway Co.", the two following variants are produced (the second of which is correct):

## Streamlit
![image](https://user-images.githubusercontent.com/20212179/105173148-84c86380-5b18-11eb-976b-d3443f319950.png)

## Jupyter Lab
![image](https://user-images.githubusercontent.com/20212179/105173186-927de900-5b18-11eb-8e53-85ee418fd1e0.png)

For my streamlit instance I'm also getting the below warning, but I checked the huggingface docs and it seems to sort itself out by disabling parallelism.
```
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
```

Disabling all custom components to use the default `en_core_web_trf` pipeline doesn't resolve the issue.

### Streamlit virtualenv
- **spaCy version:** 3.0.0rc3
- **Platform:** Darwin-20.2.0-x86_64-i386-64bit
- **Python version:** 3.7.3
- **Pipelines:** en_core_web_trf (3.0.0a1)

### Jupyter virtualenv
- **spaCy version:** 3.0.0rc3
- **Platform:** Darwin-20.2.0-x86_64-i386-64bit
- **Python version:** 3.7.3
- **Pipelines:** en_core_web_sm (3.0.0a1), en_core_web_trf (3.0.0a1), en_core_web_lg (3.0.0a0)

**Comment by adrianeboyd** [comment]
Hi, can you share a reproducible code example that shows how you get differing results with just `en_core_web_trf`? It probably needs to the include the surrounding streamlit setup for us to reproduce the error, since it's not something I can reproduce with a very simple test case with this text.

There have also been some similar issues with spacy-transformers v0.6 related to batching, although I'm not aware of any for v1.0 at this point.

**Comment by kdutia** [comment]
Hi @adrianeboyd - I think it was maybe a streamlit error with using the wrong version of spaCy or something. I've just tried a new virtualenv and although the result of `python -m spacy info --markdown` is exactly the same as my last comment, streamlit is showing the correct entity span now.

**Comment by adrianeboyd** [comment]
Okay, thanks for getting back to us. Please open a new issue if you run into a similar issue in the future!
