### ISSUE TITLE
Bug in IS_STOP function(?)

### ISSUE THREAD

**Issue by sniranjan** [explosion/spaCy#678]
I am using the below code to check if a word is a stop word or not. As you can see below, if the try block fails, the IS_STOP function is throwing an error.

```
import spacy
nlp = spacy.load('en')
try:
    print 0/0 #Raise and Exception 
except:
    print nlp.is_stop('is')
```

I get the below error:

```
      5     print 0/0
      6 except:
----> 7     print spacy.load('en').is_stop('is')
AttributeError: 'English' object has no attribute 'is_stop'
```
I am using Spacy 1.3.0 on Windows (Python 2.7)

**Comment by honnibal** [comment]
I'm sort of confused here. There is indeed no `is_stop` function on `English`. Do the docs say there should be, somewhere?

**Comment by sniranjan** [comment]
Hi, I am following the below  [link](https://github.com/explosion/spaCy/issues/226). In fact, if I try the below it works, only when I put it in a try catch block it fails. Is there another way that I can find a stop word in Spacy? 
```
import spacy
nlp = spacy.load('en')
print nlp.is_stop('is')
>> 1
```

**Comment by honnibal** [comment]
That use of `is_stop` was always undocumented. The main way to find stop words is on the tokens or vocab words, using the `token.is_stop` or `lexeme.is_stop` attributes:

```python

import spacy

nlp = spacy.load('en')

doc = nlp(u'Which of these are stop words?')
for word in doc:
    print(word.text, word.is_stop)
```

If you need the stop list itself, it can now be found in `spacy.en.language_data.STOP_WORDS`.
