### ISSUE TITLE
 nl_core_news_lg-3.0.0a1 missing tar.gz

### ISSUE THREAD

**Issue by umarniz** [explosion/spaCy#6801]
## How to reproduce the behaviour
I know that 3.0.x are RCs and not complete yet but I noticed that all the 3.0.x model releases have a `tar.gz` file except the model `nl_core_news_lg-3.0.0a1`:

https://github.com/explosion/spacy-models/releases/tag/nl_core_news_lg-3.0.0a1

Compared to all other releases:

https://github.com/explosion/spacy-models/releases

This would cause the command in the documentation:

`python -m spacy download nl_core_news_lg` 

to fail with the error:

`ERROR: HTTP error 404 while getting https://github.com/explosion/spacy-models/releases/download/nl_core_news_lg-3.0.0a1/nl_core_news_lg-3.0.0a1.tar.gz#egg=nl_core_news_lg==3.0.0a1`

**Comment by adrianeboyd** [comment]
Thanks for the note, the upload must have failed somehow. I uploaded it again by hand and I think it should be okay now?

**Comment by svlandeg** [comment]
Looks OK to me, Adriane!

**Comment by umarniz** [comment]
Thanks @adrianeboyd it downloads and loads perfectly :)
