### ISSUE TITLE
Argument 'string' has incorrect type (expected unicode, got list)

### ISSUE THREAD

**Issue by Rahulvks** [explosion/spaCy#681]
import pandas as pd
import spacy 
import itertools as it
import codecs
nlp = spacy.load('en')
from __future__ import unicode_literals

with codecs.open("//home/nlp/Spacy_test",'r','utf-8') as f:
    sample_text = f.readlines()

sample_review = nlp(sample_text)

Facing this error when i compile 
Argument 'string' has incorrect type (expected unicode, got list)
sample_text have reviews about hotels

**Comment by aborsu** [comment]
Hello,

`f.readlines()` reads a file into a list of strings. (Each line of the file being an element of the list.)
`nlp` expects to have a string not a list.
So you need to either read the file in one go `f.read()` or feed each line seperately to the parser.

**Comment by honnibal** [comment]
To add to @aborsu's advice: If you do want to parse a list of texts, you could consider using the `.pipe()` method.
