### ISSUE TITLE
char_span returns none even with outside & inside alignment

### ISSUE THREAD

**Issue by tshrjn** [explosion/spaCy#6812]
## How to reproduce the behaviour

`doc.char_span` returns None even when the alignment is inside or outside & it even covers the tokens.

Here is an example demonstrating the issue:
```
from spacy.lang.en import English

t = 'Hello at 2/24/2017 11:00 AM'
nlp = English() 

d = nlp(t)


print("***** TOKENS ****")

for i, token in enumerate(d):
    print(i, token.text, token.pos_, token.dep_)
    
print("***** SPANS strict ****")
print(d.char_span(0, 25,  alignment_mode='strict'))
print(d.text[0:25])


print("***** SPANS inside ****")
print(d.char_span(0, 25,  alignment_mode='inside'))
print(d.text[0:25])

print("***** SPANS outside ****")
print(d.char_span(0, 25,  alignment_mode='outside'))
print(d.text[0:25])

```

This outputs the following:
```
***** TOKENS ****
0 Hello  
1 at  
2 2/24/2017  
3 11:00  
4 AM  
***** SPANS strict ****
None
Hello at 2/24/2017 11:00 
***** SPANS inside ****
None
Hello at 2/24/2017 11:00 
***** SPANS outside ****
None
Hello at 2/24/2017 11:00
```

## Your Environment

* Operating System: Ubuntu 18.04.5 LTS
* **spaCy version:** 2.3.5
* **Platform:** Linux-4.15.0-122-generic-x86_64-with-glibc2.10
* **Python version:** 3.8.5

**Comment by adrianeboyd** [comment]
Ah, the docs got out-of-sync here. The modes should be: `strict`, `contract`, and `expand`, and if it doesn't recognize the mode, it silently picks `strict`. We'll get it updated and think about how to add a warning without making it too verbose.
