### ISSUE TITLE
No meaningful message when a language is not supported by doc.noun_chunks

### ISSUE THREAD

**Issue by Tpt** [explosion/spaCy#682]
When the vocabulary language is not set to "en" or "de" the doc.noun_chunks method fails with the following error:

```
File "XX.py", line 55, in YY
for np in doc.noun_chunks:
File "spacy/tokens/doc.pyx", line 404, in __get__ (spacy/tokens/doc.cpp:9194) TypeError: 'NoneType' object is not callable
```

It is because there is no CHUNKERS defined for the language in spcay.syntax.iterators. A meaningful error message should maybe be added and a nice way to plug-in others LANG_noun_chunks functions.

## Your Environment
* **Operating System:** Ubuntu 16.04
* **Python Version Used:** 3.5
* **spaCy Version Used:** 1.3
* **Environment Information:**

**Comment by honnibal** [comment]
Agreed, thanks!

**Comment by ines** [comment]
This should now be fixed both on master and in v2. Also improved the error messages – they now link to the documentation instead of telling the user to download a specific model (which was non-existent for languages other than `en`, `de` and `fr` – see #1051).
