### ISSUE TITLE
spacy.gold and spacy.morphology assumes that the 'SP' POS tags exists

### ISSUE THREAD

**Issue by Tpt** [explosion/spaCy#683]
Spacy.gold and spacy.morphology both assumes that the 'SP' fine grain POS tag exists. It should be probably documented somewhere that the custom tag lists should include this POS tag.

An other possibility is to make Vocab and Tagger constructors automatically register it.

## Your Environment
* **spaCy Version Used:** 1.3

**Comment by honnibal** [comment]
Agreed, thanks!

**Comment by honnibal** [comment]
Fixed in the `Morphology` class, which I think should fix this elsewhere too.
