### ISSUE TITLE
Different dependency results from demo site

### ISSUE THREAD

**Issue by ThomasBurgess2000** [explosion/spaCy#6851]
## How to reproduce the behaviour
I load the model with `nlp = spacy.load("en_core_web_sm", disable=["ner", "textcat"])` and then do `doc = nlp("convert ten miles to feet")` and get this dependency graph: 

![image](https://user-images.githubusercontent.com/14812407/106230710-ba72e980-61b5-11eb-8e37-c33a82ea8ae3.png)

I really need the output that I get from the demo site, where "feet" is a child of "to" and has the "pobj" dependency:

![image](https://user-images.githubusercontent.com/14812407/106230776-e2fae380-61b5-11eb-9d54-b0226c05b7ce.png)
https://explosion.ai/demos/displacy?text=convert%20ten%20miles%20to%20feet&model=en_core_web_sm&cpu=1&cph=0

Any idea why I'm getting different results? I've tried both 2.3.0 and 2.3.5.

## Info about spaCy

* **spaCy version:** 2.3.5
* **Platform:** Windows-10-10.0.20236-SP0
* **Python version:** 3.8.5

**Comment by adrianeboyd** [comment]
You want to look at the model version with:

```bash
$ python -m spacy validate
```

e.g.:

```none
TYPE      NAME                MODEL               VERSION

package   en-core-web-sm      en_core_web_sm      2.3.0   ✔
```

The demo is using model v2.3.0 and you may get different results if you have the newer v2.3.1. For sentences like this, you might get different results just if you change the numbers slightly, so don't count on having this exact analysis for all similar sentences even if you install the exact same older model.

You can find older versions at https://github.com/explosion/spacy-models/releases e.g.:

https://github.com/explosion/spacy-models/releases//tag/en_core_web_sm-2.3.1
https://github.com/explosion/spacy-models/releases//tag/en_core_web_sm-2.3.0

You have to download the `.tar.gz` model package from the assets and install it directly with pip:

```bash
pip install en_core_web_sm-2.3.0.tar.gz
```
