### ISSUE TITLE
Release date for version 3.0.

### ISSUE THREAD

**Issue by rsoika** [explosion/spaCy#6865]
I know you don't like this question, but are there any hints form your side when the first final release of version 3.0 will be available?

We are implementing a new open source project including the Spacy API for text recognition in business documents. The question came up - should we work with v3.0.0rc3 to avoid a bigger refactoring in the near future?

**Comment by honnibal** [comment]
We've actually announced a date this time! It's tomorrow :)

**Comment by svlandeg** [comment]
It's today!
