### ISSUE TITLE
Feature request - multi-sentence processing && SentenceBERT-style training

### ISSUE THREAD

**Issue by aced125** [explosion/spaCy#6876]
Hey Spacy,

I would like to propose the following two requests:

a) The processing of multiple sentences at once in transformer models.

b) SentenceBERT-style pretraining (if we are going to stick to just processing sentence-wise).

Rational for a): 

Transformer models are usually trained on segments of sub-token length 512. Moreover, this way they can incorporate long-range attention (eg see GPT2-generated text and its long-range references). Benchmark scores also go up when the full segment length is used.

From a computational perspective, we are going to pad sequences up to length 512 anyway, if I recall correctly. So it may be faster anyway to fill up the sequences to 512.

I feel like it wouldn't be too hard to implement. It simply requires stacking multiple sentences into a segment until that segment is just under 512 in length.

Rational for b):

It has been shown that sentence embeddings from transformer-based models tend to perform not nearly as well as we'd expect them to, on tasks like semantic sentence similarity. 

The following paper, published in EMNLP, essentially solves this problem: https://arxiv.org/abs/1908.10084

Furthermore, they provide an easy-to-use library to get their enhanced sentence-embeddings: https://github.com/UKPLab/sentence-transformers

The repository includes all the code as well as pre-trained models. 

Here are results on STS - clearly, averaging or taking the CLS vector of BERT embeddings is suboptimal.

Model | STS benchmark | SentEval
-- | -- | --
Avg. GloVe embeddings | 58.02 | 81.52
BERT-as-a-service avg. embeddings | 46.35 | 84.04
BERT-as-a-service CLS-vector | 16.50 | 84.66
InferSent - GloVe | 68.03 | 85.59
Universal Sentence Encoder | 74.92 | 85.10
Sentence Transformer Models |   |  
bert-base-nli-mean-tokens | 77.12 | 86.37
bert-large-nli-mean-tokens | 79.19 | 87.78
bert-base-nli-stsb-mean-tokens | 85.14 | 86.07
bert-large-nli-stsb-mean-tokens | 85.29 | 86.66

**Comment by polm** [comment]
Since this issue was created v3 was released, and now it should be possible to implement this just by registering a custom [span getter](https://spacy.io/api/transformer#span_getters).
