### ISSUE TITLE
v3 is no longer thread-safe when used with transformers

### ISSUE THREAD

**Issue by titanous** [explosion/spaCy#6879]
## How to reproduce the behaviour

Use a pipeline containing a transformer model from multiple threads (for example, `spacy.load("en_core_web_trf")`).

The pipeline will sometimes fail with an `Already borrowed` error.

This may be related to an upstream issue: https://github.com/huggingface/tokenizers/issues/537

## Your Environment

* Operating System: Ubuntu
* Python Version Used: 3.7.3
* spaCy Version Used: 3.0.0
* Environment Information:

**Comment by adrianeboyd** [comment]
Hi, I'm fairly certain that this is an issue with `transformers` or `tokenizers` and not with `spacy` itself. I'm not sure it would solve this problem, but you could try switching to the slow tokenizer by editing the config in `en_core_web_trf` to set `components.transformer.model.tokenizer_config.use_fast` to `false`.

For most of the config settings, editing them by hand like this would break the model loading and/or performance, but I think this one shouldn't have any major side effects, aside from speed of course.

**Comment by phaterpekar** [comment]
Facing the same issue while using "en_core_web_trf" with multiple threads.

**Comment by severinsimmler** [comment]
Using the slow tokenizer solves the problem (at least until `tokenizers` is thread-safe).

**Comment by imichaeldotorg** [comment]
@adrianeboyd Is there a way to set the slow tokenizer at runtime in Python?

**Comment by imichaeldotorg** [comment]
This seems to do the trick.  You might need to adjust the path to your site-packages depending on the Python install.

    `sed -i 's/use_fast = true/use_fast = false/' /usr/local/lib/python3.8/site-packages/en_core_web_trf/en_core_web_trf-3.0.0/config.cfg`

**Comment by svlandeg** [comment]
Thanks for all the comments. It looks like there is a workaround (though not ideal), and the issue is not in spaCy itself. I'll thus close this issue as there is not really any required action on our side - let's hope this gets fixed upstream soon enough :-)

**Comment by svlandeg** [comment]
(or I'll forget to close and have a very helpful colleague who will ;-))
