### ISSUE TITLE
No compatible packages found for v3.0.1 of spaCy

### ISSUE THREAD

**Issue by koaning** [explosion/spaCy#6888]
It seems like the recently pushed `3.0.1` version has some issues downloading models. 

```
python -m spacy download en_core_web_md

✘ No compatible packages found for v3.0.1 of spaCy
```

Here's my system info. 

```
============================== Info about spaCy ==============================

spaCy version    3.0.1                         
Location         /Users/vincent/Development/rasa/venv/lib/python3.7/site-packages/spacy
Platform         Darwin-19.3.0-x86_64-i386-64bit
Python version   3.7.7                         
Pipelines       
```

**Comment by adrianeboyd** [comment]
Ah, thanks for the note, this should be working in a few minutes.

**Comment by shqkrck** [comment]
spacy.cli.download('en_core_web_lg') from within the code works well, command line does not

**Comment by koaning** [comment]
The command line seems to be running locally now. Thanks, @adrianeboyd! I'll just check if the CI jobs can also pick it up again. If so, I'll close the issue.

**Comment by koaning** [comment]
There are still some other integration bugs I gotta fix to support the new spaCy version in Rasa, but our CI jobs are passing the download phase now. Thanks!
