### ISSUE TITLE
Typo in spacy.en.STOPWORDS: "fify"

### ISSUE THREAD

**Issue by rjmorris** [explosion/spaCy#689]
I'm using spaCy 0.101.0 and Python 3.5.2 on Windows 7. There appears to be a typo in `spacy.en.STOPWORDS`. One of the tokens is "fify", but I suspect it should be "fifty".

**Comment by ines** [comment]
Thanks, just fixing this!

I'm currently in the process of reorganising the language data, so I've been making a lot of edits and improvements on a separate branch and forgot to actually fix the most obvious errors on master. 

You can follow the work in progress on the [organize-language-data](https://github.com/explosion/spaCy/tree/organize-language-data/spacy) branch btw. We should hopefully be able to merge this very soon – just need to run a few more tests etc.
