### ISSUE TITLE
textcat labels expects Optional[Dict] but it should expect Optional[Iterable[str]]

### ISSUE THREAD

**Issue by reneoctavio** [explosion/spaCy#6908]
Hi!
I was testing textcat_multilabel using a config file.
First I used the `spacy init labels` command, then I tried to read it from the file created.
The generated file has an array of labels as expected.
```
[initialize.components.textcat.labels]
@readers = "spacy.read_labels.v1"
path = ${paths.labels}
```
The error occurs while validating.
```
✘ Error validating initialization settings in
[initialize.components]
textcat -> labels   value is not a valid dict

{'labels': ['related', 'request', 'offer', 'aid_related', 'medical_help', 'medical_products', 'search_and_rescue', 'security', 'military', 'water', 'food', 'shelter', 'clothing', 'money', 'missing_people', 'refugees', 'death', 'other_aid', 'infrastructure_related', 'transport', 'buildings', 'electricity', 'tools', 'hospitals', 'shops', 'aid_centers', 'other_infrastructure', 'weather_related', 'floods', 'storm', 'fire', 'earthquake', 'cold', 'other_weather', 'direct_report']}
```

I think the culprit is that `labels` is expecting an `Optional[Dict]` instead of an `Optional[Iterable[str]]` as per [documentation](https://spacy.io/api/multilabel_textcategorizer#initialize).

https://github.com/explosion/spaCy/blob/2cdfcd2d190d22d60728beb690e073fa6a509c95/spacy/pipeline/textcat_multilabel.py#L135-L141

I noticed that it also happens for the [textcat component](https://spacy.io/api/textcategorizer#initialize).

https://github.com/explosion/spaCy/blob/2cdfcd2d190d22d60728beb690e073fa6a509c95/spacy/pipeline/textcat.py#L306-L313

I can do a PR fixing this if changing from `Optional[Dict]` to `Optional[Iterable[str]]` is correct.

## Your Environment
- **spaCy version:** 3.0.1
- **Platform:** Linux-5.8.0-41-generic-x86_64-with-glibc2.10 (Ubuntu 20.04)
- **Python version:** 3.8.5
- **Pipelines:** en_core_web_trf (3.0.0), pt_core_news_sm (3.0.0), pt_core_news_lg (3.0.0)

**Comment by svlandeg** [comment]
Yes, your analysis looks correct, and a PR would be appreciated!
