### ISSUE TITLE
Spacy recognizes `gonna` as an adverb

### ISSUE THREAD

**Issue by nilehmann** [explosion/spaCy#691]
In sentences like `I'm gonna send an invitation` spacy recognizes `gonna` as an adverb. This messes up dependency parsing. Stanford instead tokenizes `gonna` as two tokens (gon=VBG, na=TO), so its behaves like `going to`. I found this behaviour more appropriate.

**Comment by honnibal** [comment]
Thanks. We'll add this to the tokenizer exceptions.

**Comment by ines** [comment]
Adding this on the [organize-language-data](https://github.com/explosion/spaCy/tree/organize-language-data) branch in the new format so it'll be fixed in v2.
