### ISSUE TITLE
Transformer NER training on GPU 

### ISSUE THREAD

**Issue by JulesBelveze** [explosion/spaCy#6922]
## How to reproduce the behaviour
Hey guys, I am trying to train a NER on my own data on a GPU, using your transformer model.
I have installed SpaCy following the instructions [here](https://spacy.io/usage) and generated my `config.cfg` following your tutorials. 
The commands I ran: 
```
pip3 install --upgrade pip
pip3 install -U pip setuptools wheel
pip3 install -U spacy
pip3 install -U spacy[cuda110,transformers,lookups]
python3 -m spacy download en_core_web_trf
pip3 install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
```

The installation seems to be okay since I can open an IPython terminal and running `spacy.require_gpu()` returns `True`.

However when I run: 
```
python3 -m spacy train config.cfg
``` 
I get the following: `ℹ Using CPU` even though I specified a `gpu_allocator` on my config file.

My `config.cfg` file looks like this:
```
...
[system]
gpu_allocator = "pytorch"
seed = 0
...
[training]
accumulate_gradient = 3
dev_corpus = "corpora.dev"
train_corpus = "corpora.train"
seed = ${system.seed}
gpu_allocator = ${system.gpu_allocator}
dropout = 0.1
patience = 1600
max_epochs = 0
max_steps = 20000
eval_frequency = 200
frozen_components = []
before_to_disk = null
...
```

Is there any other parameter I need to modify in order to make it run on the available GPU?
Thanks for your help! :) 

## Your Environment

* Operating System: Ubuntu 18.04
* Python Version Used: Python 3.7.9
* spaCy Version Used: 3.0.1
* Environment Information: CUDA 11.0
```
> pip freeze
backcall==0.2.0
blis==0.7.4
catalogue==2.0.1
certifi==2020.12.5
chardet==4.0.0
click==7.1.2
cupy-cuda110==8.4.0
cymem==2.0.5
decorator==4.4.2
en-core-web-trf @ https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.0.0/en_core_web_trf-3.0.0-py3-none-any.whl
fastrlock==0.5
filelock==3.0.12
ftfy==5.8
idna==2.10
importlib-metadata==3.4.0
ipython==7.20.0
ipython-genutils==0.2.0
jedi==0.18.0
Jinja2==2.11.3
joblib==1.0.0
MarkupSafe==1.1.1
murmurhash==1.0.5
numpy==1.20.0
packaging==20.9
parso==0.8.1
pathy==0.3.5
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.1.0
preshed==3.0.5
prompt-toolkit==3.0.14
ptyprocess==0.7.0
pydantic==1.7.3
Pygments==2.7.4
pyparsing==2.4.7
regex==2020.11.13
requests==2.25.1
sacremoses==0.0.43
six==1.15.0
smart-open==3.0.0
spacy==3.0.1
spacy-alignments==0.7.2
spacy-legacy==3.0.1
spacy-lookups-data==1.0.0
spacy-transformers==1.0.1
srsly==2.4.0
thinc==8.0.1
tokenizers==0.9.4
torch==1.7.1+cu110
torchaudio==0.7.2
torchcontrib==0.0.2
torchvision==0.8.2+cu110
tqdm==4.56.0
traitlets==5.0.5
transformers==4.2.2
typer==0.3.2
typing-extensions==3.7.4.3
urllib3==1.26.3
wasabi==0.8.2
wcwidth==0.2.5
zipp==3.4.0
```

```
> nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Thu_Jun_11_22:26:38_PDT_2020
Cuda compilation tools, release 11.0, V11.0.194
Build cuda_11.0_bu.TC445_37.28540450_0
```

**Comment by honnibal** [comment]
Hi Jules,

You've done 99% of it right. I think the only thing you're missing is specifying the actual GPU device on the CLI:

```python3 -m spacy train config.cfg --gpu-id 0```

We debated this a few times (and actually changed it and changed it back...). The GPU is something that will often need to be assigned at runtime by the environment, so we didn't want to put it in the config file, which then gets checked into repositories etc. So that's why it's a CLI argument, not in the config file.

**Comment by JulesBelveze** [comment]
Awesome it's working :)
Thanks for @honnibal

**Comment by aditya-malte** [comment]
Hi @JulesBelveze,
We might want to update the tutorial/guide [here](https://spacy.io/usage/training#quickstart) then, I ran into the same issue and was unable to figure out the problem until I saw this issue.

**Comment by JulesBelveze** [comment]
Hey @aditya-malte,
You're right I haven't found the `gpu-id` flag mentioned anywhere in the docs either.
