### ISSUE TITLE
✘ No compatible model found for 'de_core_news_sm==2.3.0' (spaCy v2.3.5).

### ISSUE THREAD

**Issue by michaelhochleitner** [explosion/spaCy#6927]
## How to reproduce the behaviour
pip install spacy==2.3.5
python -m spacy download de_core_news_sm==2.3.0

Those two are compatible according to https://github.com/explosion/spacy-models/blob/master/compatibility.json .

Installing those two versions together was possible at Tue Feb  2 09:59:04 2021 as the output of the following shows.

```
import pkg_resources, os, time

for package in pkg_resources.working_set:
    print("%s: %s" % (package, time.ctime(os.path.getctime(package.location))))
```
spacy 2.3.5: Tue Feb  2 09:59:04 2021
de-core-news-sm 2.3.0: Tue Feb  2 09:59:04 2021

## Your Environment

* Operating System: Linux Mint 20.1 Ulyssa
* Python Version Used: 3.9.1
* spaCy Version Used: v2.3.5
* Environment Information: venv created by pycharm

**Comment by michaelhochleitner** [comment]
pip install https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-2.3.0/de_core_news_sm-2.3.0.tar.gz
did not show the error message.

`python -m spacy validate`

✔ Loaded compatibility table

====================== Installed models (spaCy v2.3.5) ======================
ℹ spaCy installation:
/home/mh/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/spacy

TYPE      NAME              MODEL             VERSION                            
package   de-core-news-sm   de_core_news_sm   2.3.0   ✔

**Comment by adrianeboyd** [comment]
Yes, the `spacy download` CLI only supports downloading the most recent compatible version and doesn't support additional version specifications, so using the direct github asset link with pip as above is the best way to install an older version.
