### ISSUE TITLE
en_core_web_md and ch_core_web_md are differently treated in Pool?

### ISSUE THREAD

**Issue by wagu0809** [explosion/spaCy#6936]
## Problem
When I use en_core_web_mb in Pool, it worked well. When I changed to zh_core_web_mb, it gave me this error:
TypeError: can't pickle module objects

> Traceback (most recent call last):
File "<input>", line 1, in <module>
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2019.2.2\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2019.2.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/ProgramData/PycharmProjects/NLP_DEMOS/multiprocessing_demo.py", line 31, in <module>
    with Pool(1, global_initializer, (nlp,)) as pool:
  File "D:\ProgramData\Anaconda3\envs\Env3\lib\multiprocessing\pool.py", line 174, in __init__
    self._repopulate_pool()
  File "D:\ProgramData\Anaconda3\envs\Env3\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
    w.start()
  File "D:\ProgramData\Anaconda3\envs\Env3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\ProgramData\Anaconda3\envs\Env3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\ProgramData\Anaconda3\envs\Env3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\ProgramData\Anaconda3\envs\Env3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle module objects

## How to reproduce the behaviour
Here is my code:
```python
from multiprocessing.pool import Pool
import en_core_web_md
import zh_core_web_lg
import zh_core_web_md

nlp_e = en_core_web_md.load()
nlp = zh_core_web_md.load()

def global_initializer(nlp_object):
    global spacy_nlp
    spacy_nlp = nlp_object


if __name__ == "__main__":
    with Pool(10, global_initializer, (nlp,)) as pool:
        print('sss')
````
## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.6.12
* spaCy Version Used: 2.3.2
* Environment Information: zh_core_web_md-2.3.1, en_core_web_md-2.3.1,

**Comment by adrianeboyd** [comment]
Hmm, this looks related to how the spacy v2 Chinese tokenizer is loading `jieba` in the background even though the model itself doesn't require it.

A workaround is to uninstall `jieba` and set `use_jieba` to `False` before loading the model:

```python
from spacy.lang.zh import ChineseDefaults
ChineseDefaults.use_jieba = False
nlp = spacy.load("zh_core_web_sm")
```

In spacy v3 the Chinese tokenizer has been refactored so that `jieba` is only loaded if it's going to be used, so this should work out of the box, if you're interested in upgrading.

**Comment by wagu0809** [comment]
> Hmm, this looks related to how the spacy v2 Chinese tokenizer is loading `jieba` in the background even though the model itself doesn't require it.
> 
> A workaround is to uninstall `jieba` and set `use_jieba` to `False` before loading the model:
> 
> ```python
> from spacy.lang.zh import ChineseDefaults
> ChineseDefaults.use_jieba = False
> nlp = spacy.load("zh_core_web_sm")
> ```
> 
> In spacy v3 the Chinese tokenizer has been refactored so that `jieba` is only loaded if it's going to be used, so this should work out of the box, if you're interested in upgrading.

Hi there,
Thanks very much for your feedback. I tried your solution on V2, just added your code into mine, it didn't work either. It gave the same error. I'll try upgrading to the new version and will update the comment once I have the result.

**Comment by wagu0809** [comment]
Hi there,
It worked after upgrading to V3.
Thanks for your help!

**Comment by adrianeboyd** [comment]
Glad to hear it's working!

As a note, I think the reason it didn't work in v2 is that you have uninstall `jieba` with `pip uninstall jieba` for it to actually skip loading jieba entirely. The Chinese tokenizer loading / configuration is a bit clunky in v2 because we didn't want modify the default behavior for v2.0-v2.2, and it works a lot more cleanly in v3.
