### ISSUE TITLE
Unable to run transformer pipeline for transformer model other than default one

### ISSUE THREAD

**Issue by jessevig** [explosion/spaCy#6958]
I am unable to process a document using a transformer other than the default one that comes with en_core_web_trf. 

I've tried to run the code snippet from the documentation (https://spacy.io/api/transformer):

```
from spacy_transformers.pipeline_component import DEFAULT_CONFIG

nlp.add_pipe("transformer", config=DEFAULT_CONFIG["transformer"])
```

However, this code does not specify how to construct nlp. 

## How to reproduce
When I run the following:

```
import spacy
from spacy_transformers.pipeline_component import DEFAULT_CONFIG
nlp = spacy.blank("en")
nlp.add_pipe("transformer", config=DEFAULT_CONFIG["transformer"])
doc = nlp("This is a sentence.")
```

I get the following error:

```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/rgym-source/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-6d9c6cf1e173>", line 1, in <module>
    runfile('/Users/jvig/repos/robustness-gym/robustsumm/space_transformer_test.py', wdir='/Users/jvig/repos/robustness-gym/robustsumm')
  File "/Users/jvig/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/193.6015.41/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Users/jvig/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/193.6015.41/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/jvig/repos/robustness-gym/robustsumm/space_transformer_test.py", line 39, in <module>
    doc = nlp("This is a sentence.")
  File "/opt/anaconda3/envs/rgym-source/lib/python3.8/site-packages/spacy/language.py", line 994, in __call__
    error_handler(name, proc, [doc], e)
  File "/opt/anaconda3/envs/rgym-source/lib/python3.8/site-packages/spacy/util.py", line 1495, in raise_error
    raise e
  File "/opt/anaconda3/envs/rgym-source/lib/python3.8/site-packages/spacy/language.py", line 989, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))
  File "/opt/anaconda3/envs/rgym-source/lib/python3.8/site-packages/spacy_transformers/pipeline_component.py", line 183, in __call__
    outputs = self.predict([doc])
  File "/opt/anaconda3/envs/rgym-source/lib/python3.8/site-packages/spacy_transformers/pipeline_component.py", line 218, in predict
    activations = self.model.predict(docs)
  File "/opt/anaconda3/envs/rgym-source/lib/python3.8/site-packages/thinc/model.py", line 312, in predict
    return self._func(self, X, is_train=False)[0]
  File "/opt/anaconda3/envs/rgym-source/lib/python3.8/site-packages/spacy_transformers/layers/transformer_model.py", line 121, in forward
    transformer = model.layers[0]
IndexError: list index out of range
```

I've tried other ways of initializing nlp, e.g. from en_core_web_trf or en_core_web_sm but end up getting the same error. Is there a different way I should initialize nlp? My ultimate goal is to use spacy transformers to compute output embeddings that are aligned with spacy tokens.

## Info about spaCy

- **spaCy version:** 3.0.1
- **Platform:** macOS-10.14.6-x86_64-i386-64bit
- **Python version:** 3.8.5
- **Pipelines:** en_core_web_sm (3.0.0a1), en_core_web_trf (3.0.0)

**Comment by honnibal** [comment]
Hi @jessevig ,

I agree that that docs example does leave some steps out. We'll think about the best way to improve it.

I think the only step missing is to call `.initialize()` on the transformer component. This step has to be separate from just adding the component, because we need to be able to setup the pipeline before we either load it back in from disk, or initialize the whole pipeline.

However, we also have some usability problems here that definitely need to be fixed. The following code will work for now, but we'll want to improve things.

```python

import spacy
from spacy_transformers.pipeline_component import DEFAULT_CONFIG
nlp = spacy.blank("en")
transformer = nlp.add_pipe("transformer", config=DEFAULT_CONFIG["transformer"]).initialize()
transformer.model.initialize([nlp.make_doc("hello world")])
doc = nlp("This is a sentence.")
```

**Comment by pmbaumgartner** [comment]
Adding a +1 for this and #7027. I tried to get started with initializing this component so I could switch out the transformer model used and struggled a bit.

Posting on this issue b/c I attempted the example code above with initialize and get the following traceback:

```
Traceback (most recent call last):
  File "trf_test.py", line 4, in <module>
    transformer = nlp.add_pipe("transformer", config=DEFAULT_CONFIG["transformer"]).initialize()
TypeError: initialize() missing 1 required positional argument: 'get_examples'
```

---

## Info about spaCy

- **spaCy version:** 3.0.3
- **Platform:** macOS-10.15.7-x86_64-i386-64bit
- **Python version:** 3.8.8
- **Pipelines:** en_core_web_sm (3.0.0), en_core_web_trf (3.0.0)

**Comment by jessevig** [comment]
Thanks, I also got the error described above with the revised code.

**Comment by adrianeboyd** [comment]
There's a mistake in Matt's original example. Don't be surprised, I've edited it above already to make it clearer for future readers.

It should be:

```python
import spacy
from spacy_transformers.pipeline_component import DEFAULT_CONFIG

nlp = spacy.blank("en")
transformer = nlp.add_pipe("transformer", config=DEFAULT_CONFIG["transformer"])
transformer.model.initialize([nlp.make_doc("hello world")])
doc = nlp("This is a sentence.")
```

Alternatively, you can initialize the whole pipeline with `Example` rather than `Doc` objects like this, which is what you would need to do if you have additional components in your pipeline that also need to be initialized. If the other components have labels (like a `tagger`), be aware that you'd need to provide `Example` objects with annotation in the reference docs that cover all the possible labels. Usually if that's the case, you'd be using `spacy train`, which handles this for you.

```python
import spacy
from spacy_transformers.pipeline_component import DEFAULT_CONFIG
from spacy.training import Example

nlp = spacy.blank("en")
transformer = nlp.add_pipe("transformer", config=DEFAULT_CONFIG["transformer"])
nlp.initialize(lambda: [Example(nlp.make_doc("hello"), nlp.make_doc("hello"))])
doc = nlp("This is a sentence.")
```

**Comment by jessevig** [comment]
Thank you! Is there a simple example of how to align these transformer outputs with the spacy tokens? I looked at https://spacy.io/usage/embeddings-transformers (see screenshot below) but wasn't clear how to apply the alignment example to this use case.

![image](https://user-images.githubusercontent.com/45317205/110167682-f13ab180-7daa-11eb-844d-7e20ca18761e.png)

**Comment by pmbaumgartner** [comment]
@jessevig The code snippet below is a little more than you asked for, but should show you how to align spacy tokens with transformer-based tokenization.

```
import en_core_web_trf
import numpy as np

nlp = en_core_web_trf.load()

text = "I doubt ouroboric is a token."
doc = nlp(text)

doc._.trf_data.tokens  # input_ids, attention_mask, input_texts

doc._.trf_data.tensors  # [0].shape (1, 11, 768), [1].shape (1, 768)

assert doc[2].text == "ouroboric"
assert doc._.trf_data.align.lengths[2] > 1  # multiple wordpiece

wp_indices = doc._.trf_data.align[2].dataXd.squeeze()

squeezed_tensors = doc._.trf_data.tensors[0].squeeze()
assert squeezed_tensors.shape == (
    len(doc._.trf_data.align.data) + 2, # add start and end document tokens
    doc._.trf_data.width,
)
token_tensor = squeezed_tensors[wp_indices].mean(axis=0)
```

Where `token_tensor` is the mean pooled wordpiece (or whatever tokenisation scheme transformers is using) vector for that spaCy token - in this example, the token `ouroboric`

**Comment by jessevig** [comment]
Thank you so much, this is great!!

**Comment by kad-beukes** [comment]
Does this mean that it is currently not possible to use transformer models from huggingface that were not adopted as spacy models yet, or am I missing another way to do this? I've been trying to get a Dutch transformer model to work (using  the example on https://spacy.io/api/transformer#init) quite some time now, but none of the initializations suggested above seem to lead anywhere. Is there any documentation on how to use a huggingface transformer model within the Spacy -framework, or is https://github.com/explosion/spaCy/issues/7027 the only (not yet availavle) way?
