### ISSUE TITLE
spacy.vocab.Vocab no attribute 'lookups_extra' after installing spacy-lookups-data

### ISSUE THREAD

**Issue by jacksonwalters** [explosion/spaCy#6959]
## How to reproduce the problem

I'm trying to use `.prob` to lookup the probabilities of words. This used to work in a previous version, however it looks like some changes were made in v2.3+. I installed spacy-lookups-data via pip

spacy               3.0.1
spacy-alignments    0.7.2
spacy-legacy        3.0.1
spacy-lookups-data  1.0.0
spacy-transformers  1.0.1

however when following the instructions under "Probability and cluster features" at [What's New in v2.3](https://spacy.io/usage/v2-3), I receive an error. At the repo, the requirements.txt file requires `spacy-nightly>=3.0.0rc5,<3.1.0`. I tried installing the nightly, and was able to run pytest which returned at least one failure, and it seemed to break some other things and still claimed spacy.vocab had no lookups_extra attribute.

```bash
>>>import spacy
>>>nlp = spacy.load("en_core_web_lg")
>>>if nlp.vocab.lookups_extra.has_table("lexeme_prob"):
>>>...     nlp.vocab.lookups_extra.remove_table("lexeme_prob")
AttributeError: 'spacy.vocab.Vocab' object has no attribute 'lookups_extra'
>>> nlp.vocab["a"].prob
-20.0
```

## Your Environment

- **spaCy version:** 3.0.1
- **Platform:** Windows-10-10.0.19041-SP0
- **Python version:** 3.9.0
- **Pipelines:** en_core_web_lg (3.0.0), en_core_web_md (3.0.0), en_core_web_sm (3.0.0), en_core_web_trf (3.0.0)

**Comment by adrianeboyd** [comment]
Here's how to add the tables to an existing v3 model:

https://github.com/explosion/spaCy/discussions/6388#discussioncomment-330606

We should get this added to the migration guide.

**Comment by jacksonwalters** [comment]
Thanks, that solution worked. Now getting `[t for t in nlp("a")][0].lex.prob = -3.9297883511` as expected.
