### ISSUE TITLE
Matcher outputs entity IDs as integers, even if given strings

### ISSUE THREAD

**Issue by KlausSchaefersAtWork** [explosion/spaCy#696]
I tried running the following example:

```
from spacy.matcher import Matcher
matcher = Matcher(nlp.vocab)
matcher.add_pattern("HelloWorld", [{LOWER: "hello"}, {IS_PUNCT: True}, {LOWER: "world"}])

doc = nlp(u'Hello, world!')
matches = matcher(doc)

for ent_id, label, start, end in matches 
    print(doc[start:end].text, label, ent_id )
    # Hello, world 315854 1
```

I would have expected that at ent-id or label would be "HelloWorl" but instead I get some int ID (315854 ), which dies not help.

According to the API the ent_id should be the Id i passed to the add_pattern method:

```
    def add_pattern(self, *args, **kwargs): # real signature unknown
        """
        Add a pattern to the matcher.
        
                Arguments:
                    entity_key (unicode or int):
                        An ID for the entity.
                    token_specs:
                        Description of the pattern to be matched.
                    label:
                        Label to assign to the matched pattern. Defaults to "".
                Returns:
                    None
        """
        pass
```

## Your Environment

* **Operating System:** Win10
* **Python Version Used:** 3.5
* **spaCy Version Used:** 1.4
* **Environment Information:**

**Comment by KlausSchaefersAtWork** [comment]
I debugged a little. It seems the self._entities map in the matcher.pyx contains an empty object. Also If I ask matcher.get_entity() I receive {}

**Comment by honnibal** [comment]
Thanks, agree this is confusing.

The integer that's returned is a string ID — the library interns all strings internally. I'll have another think about how this should behave.

For now you can get your string back by doing `matcher.vocab.strings[ent_id]`.

I'm not sure I read the second part of your report correctly, though. Are you saying the entity information is missing, even if you look it up by integer?

**Comment by KlausSchaefersAtWork** [comment]
Hi,

thanks this help already a lot! When I perform matcher.get_entity(ent_id) returns  and empty object {}. But getting the String id is enough for me. I just want to create a bunch of patterns (like 100k) and run them against the document. So I need to know for each match, which one was the correct one.

**Comment by honnibal** [comment]
Cool. Check out the `PhraseMatcher` class as well if you haven't. It might be relevant to you.
