### ISSUE TITLE
Broken link to Thinc in docs

### ISSUE THREAD

**Issue by koaning** [explosion/spaCy#6970]
At the bottom of [this guide on the docs](https://spacy.io/usage/training#config) there is a link to Thinc. Here's the screenshot. 

![image](https://user-images.githubusercontent.com/1019791/107219705-bfcfff80-6a11-11eb-9089-4077f361e713.png)

The **Thinc’s config system docs** link points to [here](https://thinc.ai/usage/config) which currently gives a 404.

**Comment by svlandeg** [comment]
Thanks for the report! Should be fixed by PR https://github.com/explosion/spaCy/pull/6975
