### ISSUE TITLE
Can I use pretraining with GPU in V3?

### ISSUE THREAD

**Issue by ksingh196** [explosion/spaCy#6973]
I created a config using the init config command keeping the gpu option, with pretraining flag and with pipeline = ner.
When I tried pretraining I got the below error
KeyError: "[E001] No component 'tok2vec' found in pipeline. Available names: ['transformer', 'ner']"

However if I create a config without gpu option and the same pipeline and pretraining flag I am able to do pretraining.

Has anyone faced this ?

**Comment by svlandeg** [comment]
Can you share the exact command you ran for `init config` and all output it gave? I think it should have included a warning about the fact that no `tok2vec` component was found in the pipeline.

Basically what happens, is that the `init config` command decides, based on the input given, whether the embedding layer in the pipeline should be a "simple" `tok2vec` component, or a `transformer`. But for `pretraining`, the default configuration will assume that there is a `tok2vec` component in your pipeline, and it'll refer to it as such:
```
[pretraining]
component = "tok2vec"
```
so you'd need to update that manually before the pretraining will work.

**Comment by ksingh196** [comment]
`python -m spacy init config i2b2_sp_v3_config.cfg --pipeline ner --optimize accuracy --gpu --pretraining  --force`
The output I got is mentioned below :
`ℹ Generated config template specific for your use case
- Language: en
- Pipeline: ner
- Optimize for: accuracy
- Hardware: GPU
- Transformer: roberta-base
⚠ No tok2vec component found in the pipeline. If your tok2vec component
has a different name, you may need to adjust the tok2vec_model reference in the
[pretraining] block. If you don't have a tok2vec component, make sure to add it
to your [components] and the pipeline specified in the [nlp] block, so you can
pretrain weights for it.
✔ Auto-filled config with all values
✔ Saved config
test_config.cfg
You can now add your data and train your pipeline:
python -m spacy train test_config.cfg --paths.train ./train.spacy --paths.dev ./dev.spac`


Yeah you are right I got a warning about missing tok2vec. So I have remove all the transformer components with simple tok2vec. After doing that only I should be able to do pretraining using GPU?
I will try that and update.

**Comment by ksingh196** [comment]
Yeah its working.
Thanks a lot.

**Comment by svlandeg** [comment]
Happy to hear it, thanks for reporting back!
