### ISSUE TITLE
Does spaCy require Universal POS tags to be upper case? KeyError: -67203143

### ISSUE THREAD

**Issue by yosiasz** [explosion/spaCy#6981]
## How to reproduce the behaviour

Created my own sample conllu for Amharic: am_geeztypes-train.conllu. Then when running the following 

```
python -m spacy convert am_geeztypes-train.conllu train.spacy -n 10
```
I get KeyError: -67203143

The following does not work

```
# sent_id = 1
# text = እንግሊዝኛ እየተማርኩ ነው ።
# translit = IngIlizIN_a Iy_etemarku new .
1	እንግሊዝኛ	_	noun	_	_	_	_	_	Translit=IngIlizIN_a
2	እየተማርኩ	_	verb	_	_	_	_	_	Translit=Iy_etemarku
3	ነው	_	verb	_	_	_	_	_	Translit=new
4	።	_	punct	_	_	_	_	_	Translit=.
```

the following does work 
```
# sent_id = 1
# text = እንግሊዝኛ እየተማርኩ ነው ።
# translit = IngIlizIN_a Iy_etemarku new .
1	እንግሊዝኛ	_	NOUN	_	_	_	_	_	Translit=IngIlizIN_a
2	እየተማርኩ	_	VERB	_	_	_	_	_	Translit=Iy_etemarku
3	ነው	_	VERB	_	_	_	_	_	Translit=new
4	።	_	PUNCT	_	_	_	_	_	Translit=.
```

## Your Environment
 **spaCy version:** 3.0.1
- **Platform:** Windows-10-10.0.18362-SP0
- **Python version:** 3.8.7
- 
* Operating System: Windows 10
* Python Version Used: 3.8.7
* spaCy Version Used: 3.0.1
* Environment Information:
All good

**Comment by adrianeboyd** [comment]
Yes, POS values need to be uppercase. The supported list is here: https://github.com/explosion/spaCy/blob/master/spacy/parts_of_speech.pyx
