### ISSUE TITLE
Multiprocessing when running from CLI

### ISSUE THREAD

**Issue by snthibaud** [explosion/spaCy#6985]
I could not find anything in recent docs about using multiprocessing from the CLI command. Is it possible or should I use a notebook for this?

**Comment by adrianeboyd** [comment]
Hi, which CLI command(s) are you referring to? (For quite a few of the commands, multiprocessing wouldn't make sense or wouldn't be supported internally.)

**Comment by snthibaud** [comment]
@adrianeboyd I was referring to `python -m spacy train ...`. I think it is possible to specify n_process on the pipeline when training from a notebook/program, but setting that property in the config file does not work.

**Comment by adrianeboyd** [comment]
`n_process` is supported for `nlp.pipe`, but not directly for `spacy train` (internally: `nlp.update`).

For spacy v3, it's still under development so you might run into bugs or missing features, but you could try out `spacy-ray`, see:

* https://spacy.io/usage/training#parallel-training
* https://github.com/explosion/spacy-ray
