### ISSUE TITLE
Cannot install en_core_web_trf model in docker

### ISSUE THREAD

**Issue by cameron-martin** [explosion/spaCy#7010]
## How to reproduce the problem

Build the following dockerfile:

```dockerfile
FROM python:3.8.7-buster

RUN pip install spacy
RUN python -m spacy info --markdown
RUN python -m spacy download en_core_web_trf

```

It then errors with code 247 when trying to install pytorch.

<details>
<summary>Log</summary>
<pre>
Sending build context to Docker daemon  88.58kB

Step 1/4 : FROM python:3.8.7-buster
 ---> 8f6adb7689b5
Step 2/4 : RUN pip install spacy
 ---> Using cache
 ---> d6f69d2f4105
Step 3/4 : RUN python -m spacy info --markdown
 ---> Using cache
 ---> 4bef3c4561f8
Step 4/4 : RUN python -m spacy download en_core_web_trf
 ---> Running in 785ad7371204
Collecting en-core-web-trf==3.0.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.0.0/en_core_web_trf-3.0.0-py3-none-any.whl (459.7 MB)
Requirement already satisfied: spacy<3.1.0,>=3.0.0 in /usr/local/lib/python3.8/site-packages (from en-core-web-trf==3.0.0) (3.0.1)
Collecting spacy-transformers<1.1.0,>=1.0.0rc4
  Downloading spacy_transformers-1.0.1-py2.py3-none-any.whl (38 kB)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-trf==3.0.0) (3.0.5)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-trf==3.0.0) (2.25.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-trf==3.0.0) (2.11.3)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-trf==3.0.0) (2.0.5)
Requirement already satisfied: setuptools in /usr/local/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-trf==3.0.0) (53.0.0)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.0 in /usr/local/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-trf==3.0.0) (3.0.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.1 in /usr/local/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-trf==3.0.0) (2.0.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-trf==3.0.0) (4.56.1)
Requirement already satisfied: typer<0.4.0,>=0.3.0 in /usr/local/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-trf==3.0.0) (0.3.2)
Requirement already satisfied: srsly<3.0.0,>=2.4.0 in /usr/local/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-trf==3.0.0) (2.4.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-trf==3.0.0) (20.9)
Requirement already satisfied: blis<0.8.0,>=0.4.0 in /usr/local/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-trf==3.0.0) (0.7.4)
Requirement already satisfied: pathy in /usr/local/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-trf==3.0.0) (0.3.5)
Requirement already satisfied: thinc<8.1.0,>=8.0.0 in /usr/local/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-trf==3.0.0) (8.0.1)
Requirement already satisfied: pydantic<1.8.0,>=1.7.1 in /usr/local/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-trf==3.0.0) (1.7.3)
Requirement already satisfied: numpy>=1.15.0 in /usr/local/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-trf==3.0.0) (1.20.1)
Requirement already satisfied: wasabi<1.1.0,>=0.8.1 in /usr/local/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-trf==3.0.0) (0.8.2)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-trf==3.0.0) (1.0.5)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.8/site-packages (from packaging>=20.0->spacy<3.1.0,>=3.0.0->en-core-web-trf==3.0.0) (2.4.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.1.0,>=3.0.0->en-core-web-trf==3.0.0) (1.26.3)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.1.0,>=3.0.0->en-core-web-trf==3.0.0) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.1.0,>=3.0.0->en-core-web-trf==3.0.0) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.1.0,>=3.0.0->en-core-web-trf==3.0.0) (2020.12.5)
Collecting torchcontrib<0.1.0,>=0.0.2
  Downloading torchcontrib-0.0.2.tar.gz (11 kB)
Collecting ftfy<6.0.0,>=5.0.0
  Downloading ftfy-5.8.tar.gz (64 kB)
Collecting torch>=1.5.0
  Downloading torch-1.7.1-cp38-cp38-manylinux1_x86_64.whl (776.8 MB)
The command '/bin/sh -c python -m spacy download en_core_web_trf' returned a non-zero code: 247

</pre>
</details>

## Your Environment

- **spaCy version:** 3.0.1
- **Platform:** Linux-4.19.121-linuxkit-x86_64-with-glibc2.2.5
- **Python version:** 3.8.7

**Comment by adrianeboyd** [comment]
It's probably running out of memory in docker. There are some known issues with pip's memory usage when caching large packages. Try:

```bash
python -m spacy download en_core_web_trf --no-cache-dir
```

It might also help to install `torch` in a separate step before downloading the model so pip's not trying to handle both at the same time, and then maybe it would work without the extra `--no-cache-dir`, but I'm not really sure how much difference that makes.

**Comment by cameron-martin** [comment]
This indeed was the problem, thanks. Docker for mac has the memory limit set to 2GB. Either using --no-cache-dir or increasing the memory limit fixes this.
