### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by xiaoyuxin1002** [explosion/spaCy#7030]
## How to reproduce the problem
I tried to install the latest spaCy package via 
```
conda install -c conda-forge spacy==3.0.1
``` 
or 
```
pip install -U pip setuptools wheel
pip install -U spacy
````
as specified on the website. The installation was successful. However, I encountered the following error while trying to validate the installation or downloading pre-trained models. What could be possible reasons?
```
$ python -m spacy validate
Illegal instruction (core dumped)
$ python -m spacy download en_core_web_sm
Illegal instruction (core dumped)
```

## Your Environment

* Operating System: Ubuntu
* Python Version Used: 3.8
* spaCy Version Used: 3.0.1

**Comment by svlandeg** [comment]
Did you install the package via conda, or via pip? Are you using a clean virtual environment? Were there any warnings during installation?

When the "illegal instruction" error happens, is there any error trace, or just that one line?

**Comment by xiaoyuxin1002** [comment]
Thanks for the quick response!
I tried both conda and pip, but the same error occurred.
I am assuming that I am using a clean virtual environment.
I didn't see any warnings during the installation.
The error occurred with only one line.

**Comment by polm** [comment]
Based on a [similar issue](https://github.com/tensorflow/tensorflow/issues/17411) in Tensorflow, it's possible this is due to your CPU being old and spaCy using instructions it doesn't support. Can you tell us what CPU you're using?
