### ISSUE TITLE
Sentence splitting seems almost random on Spacy 3.0 & en_core_web_lg

### ISSUE THREAD

**Issue by adam-ra** [explosion/spaCy#7034]
## How to reproduce the behaviour
```
In [1]: import spacy; nlp = spacy.load('en_core_web_lg')                        

In [2]: list(nlp("tired all of the time").sents)                                
Out[2]: [tired, all of the time]

In [3]: list(nlp("Severe pain, after trauma").sents)                            
Out[3]: [Severe pain, ,, after trauma]

In [4]: list(nlp("headache when bending head").sents)                           
Out[4]: [headache, when bending head]

In [5]: list(nlp("jaundice after stress").sents)                                
Out[5]: [jaundice after stress]

In [6]: list(nlp("jaundice after increased stress").sents)                      
Out[6]: [jaundice, after increased stress]

```

## Your Environment
Python 3.8.5, Ubuntu 20.04, 5.4.0-65-generic
spacy==3.0.1
en-core-web-lg @ https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.0.0/en_core_web_lg-3.0.0-py3-none-any.whl

**Comment by svlandeg** [comment]
Hi! I'm going to convert this issue to the discussions as I think it's more suited for the forum than for the issue tracker. You may get a notification that this thread was closed - but really it was just moved and is still open on the forum :-)
