### ISSUE TITLE
Invalid similarity() results

### ISSUE THREAD

**Issue by ValentinCalomme** [explosion/spaCy#7053]
## How to reproduce the behaviour

```py
import spacy

nlp = spacy.load("nl_core_news_lg")
score = nlp("2©Ā").similarity(nlp("Ā©2"))

assert -1.0 <=score <= 1.0, f"Invalid score: {score}"
```

The above code produces a score of `1.0000000072041835`. Fun fact, I found this edge case using `hypothesis`, which I learned existed by looking at SpaCy's list of requirements.

## Your Environment

- **spaCy version:** 3.0.1
- **Platform:** Windows-10-10.0.19041-SP0
- **Python version:** 3.8.7
- **Pipelines:** nl_core_news_lg (3.0.0)

**Comment by adrianeboyd** [comment]
I can't find the thread, but I feel like we had discussed leaving dealing with float rounding errors up to the user at some point in the past?

Is this a major problem for your use case?

**Comment by ValentinCalomme** [comment]
@adrianeboyd, this isn't a problem at all. I am handling it on my end.

I just thought that I would share the particular scenario, in case it helps uncover some other bugs.

**Comment by honnibal** [comment]
@ValentinCalomme It's indeed worth keeping in mind, but I do think it's better to allow the floating point imprecision to occur.

Funnily enough I'm always adjusting my hypothesis tests...Sometimes I wonder whether it's all worth it, because it can be quite annoying :p.
