### ISSUE TITLE
spacy.training doesn't get recognized 

### ISSUE THREAD

**Issue by saguillo2000** [explosion/spaCy#7069]
## How to reproduce the problem
 I tried to reinstall all, but the problem is that the package training is installed in the spacy package, and I don't know why it isn't recognized. I tried also Google Collab and displays the same issue:

![image](https://user-images.githubusercontent.com/47833532/107922512-66675380-6f70-11eb-8e72-f81f210b26df.png)

```bash
# Cannot find reference 'training' in '__init__.py | __init__.py'
```

## PyCharm

* Operating System: Windows10
* Python Version Used: 3.8
* spaCy Version Used: 3.0.3
* Environment Information: Using venv

**Comment by svlandeg** [comment]
Hi! I'm moving this to the discussions forum so don't be alarmed if it says "issue closed" or whatnot - it's really just moved and will stay an open thread on the forum :-)
