### ISSUE TITLE
Too high loss while training NER with custom entities

### ISSUE THREAD

**Issue by AlexFridman** [explosion/spaCy#7083]
Hello! I faced with too high losses training custom NER (2000+). 
I use the pipe to train with a default config (en large)

```
python -m spacy train config.cfg --output ./output --paths.train ./train.spacy --paths.dev ./dev.spacy
```
From other discussions I see -- the problem is because my data does not contain predefined entities. Is it possible to completely reset the list of entities I train in the config file?

```
E    #       LOSS TOK2VEC  LOSS NER  ENTS_F  ENTS_P  ENTS_R  SCORE 
---  ------  ------------  --------  ------  ------  ------  ------
  0       0          0.00     40.00    9.57    6.09   22.33    0.10
  0     200         35.70   2163.45   83.16   83.79   82.53    0.83
  0     400         11.09   1182.04   88.91   89.03   88.78    0.89
  0     600         13.27   1150.09   89.98   90.20   89.77    0.90
  0     800         19.24   1087.27   92.02   91.73   92.32    0.92
  0    1000         25.08   1343.08   93.06   92.75   93.38    0.93
```

Could you also point me to the NER format description. I understand what is 
B-..
I-..,
but confused with L-, U-.

Currently, my dataset built with B- and I- tags.

Thank you for your help!

Best Wishes,
Alex

- **spaCy version:** 3.0.1
- **Platform:** Linux-5.8.0-43-generic-x86_64-with-glibc2.29
- **Python version:** 3.8.3
- **Pipelines:** en_core_web_trf (3.0.0), en_core_web_lg (3.0.0)

**Comment by svlandeg** [comment]
Hi! I'll be moving this to the discussion forum that is better suited for discussing best practices and use-case specific help from the community. It may look like this issue got closed/locked, but it's really just moved ;-)
