### ISSUE TITLE
GPU is not accessible - spacy3 with cuda 10.1

### ISSUE THREAD

**Issue by soerenetler** [explosion/spaCy#7089]
## How to reproduce the problem
I was trying to use spacy3 on GPU. I have cuda Version 10.1 installed  (see `nvidia-smi`output below. 
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.50       Driver Version: 430.50       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  On   | 00000000:09:00.0 Off |                  N/A |
|  0%   23C    P8     6W / 250W |      0MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```
I installed spacy with `pip install -U spacy[cuda101]` and added `spacy.require_gpu()` to my code.
The code now crashes with `ValueError: GPU is not accessible. Was the library installed correctly?`

When I use the general `pip install -U spacy[cuda]` installer, my spacy version get's downgraded to spacy 2.0.13.. Is spacy 3 not compatible with cuda 10.1?

What can I do to fix this error? Thank you a lot for your help in advance.

P.S. changing again to spacy[cuda101], I get an `ImportError: cannot import name 'hash_unicode'` when running the code. This is due to an old `murmurhash` version in the requirements, where a newer version is needed. 

## Your Environment
- **spaCy version:** 3.0.3
- **Platform:** Linux-4.15.0-126-generic-x86_64-with-Ubuntu-18.04-bionic
- **Python version:** 3.6.9
- **Pipelines:** en_core_web_trf (3.0.0), en_core_web_sm (3.0.0)

**Comment by adrianeboyd** [comment]
Downgrading or upgrading with `pip` can be a problem because it doesn't always clean up old files well, which may be what's causing the weird murmurhash errors. In addition, `spacy[cuda]` sometimes doesn't work that well because it's compiling cupy from scratch and it doesn't always work out-of-the-box. I don't know why `spacy[cuda]` would try to downgrade (it really shouldn't?), but that's probably how things got kind of corrupted.

In a brand new virtual environment, try only:

```bash
pip install spacy[cuda101]
```

Then try this to test the basic cupy installation. If there's an error, hopefully it will be more informative:

```python
import cupy
a = cupy.zeros((1,1))
```

(If you're not sure about the CUDA version, double-check with `nvcc --version`, since `nvidia-smi` can sometimes show a different version.)

**Comment by soerenetler** [comment]
Thank you for your fast response.

This is the output of `nvcc --version`. It seems to be the correct version.
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

In a new virtual environment (created with `python3 -m venv test-env` and `source test-env/bin/activate`) nothing works :D I can't even `pip install spacy[cuda101]`. Obviously, this error would be easy to fix by just installing numpy, but this wouldn't help overall. I pretty sure there is a very easy fix to this, but I am not super familiar with virtual environments:
```
Collecting spacy[cuda101]
  Using cached https://files.pythonhosted.org/packages/c4/47/a88314964e2204d4085c04af4d515ffc6921072b282737b22a76b0fbf2ca/spacy-3.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ja8rb98o/spacy/setup.py", line 5, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ja8rb98o/spacy/
```
When running the lines in the default environment I get the following output:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cupy/__init__.py", line 20, in <module>
    from cupy import core  # NOQA
  File "/usr/local/lib/python3.6/dist-packages/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import cupy
  File "/usr/local/lib/python3.6/dist-packages/cupy/__init__.py", line 41, in <module>
    raise ImportError(_msg) from e
ImportError: CuPy is not correctly installed.

If you are using wheel distribution (cupy-cudaXX), make sure that the version of CuPy you installed matches with the version of CUDA on your host.
Also, confirm that only one CuPy package is installed:
  $ pip freeze

If you are building CuPy from source, please check your environment, uninstall CuPy and reinstall it with:
  $ pip install cupy --no-cache-dir -vvvv

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html
```
There are two `cupy-cudaXX` (101 and 100) listed in my `pip freeze` but I currently do not have the rights to uninstall the 100 version.

**Comment by adrianeboyd** [comment]
Ah, I forgot a step for the new venv. For spacy alone (not cupy yet), don't forget to upgrade `pip`, etc. first with: `pip install -U pip setuptools wheel`. Then `pip install spacy` will be able to find a binary wheel for spacy and won't try to install from source.

`cupy` will only work if exactly one version of the package is installed, so that's the problem there. How are you creating the venv?

**Comment by soerenetler** [comment]
After updating `pip`, I was able to install `spacy[cuda101]`.
My `pip freeze` is:
```
blis==0.7.4
catalogue==2.0.1
certifi==2020.12.5
chardet==4.0.0
click==7.1.2
contextvars==2.4
cupy-cuda101==8.4.0
cymem==2.0.5
dataclasses==0.8
fastrlock==0.5
idna==2.10
immutables==0.15
importlib-metadata==3.4.0
Jinja2==2.11.3
MarkupSafe==1.1.1
murmurhash==1.0.5
numpy==1.19.5
packaging==20.9
pathy==0.4.0
pkg-resources==0.0.0
preshed==3.0.5
pydantic==1.7.3
pyparsing==2.4.7
requests==2.25.1
smart-open==3.0.0
spacy==3.0.3
spacy-legacy==3.0.1
srsly==2.4.0
thinc==8.0.1
tqdm==4.56.2
typer==0.3.2
typing-extensions==3.7.4.3
urllib3==1.26.3
wasabi==0.8.2
zipp==3.4.0
```
But the cupy error is the same as in the default environment. Even there is only one cupy version.

**Comment by adrianeboyd** [comment]
Okay, then the step is probably to set the CUDA paths correctly. You can set `CUDA_PATH` to the top-level directory like `/opt/cuda-11.0` or you can add the `/opt/cuda-11.0/bin` directory (wherever `nvcc` is) to `PATH`. See: https://docs.cupy.dev/en/latest/install.html#working-with-custom-cuda-installation. You may also need to add the right `lib64` directory to `LD_LIBRARY_PATH`.

**Comment by soerenetler** [comment]
Cuda is located in `/usr/local/cuda`. This should be one of the default path.
Anyway I set the environment variables. 
```
$ echo $LD_LIBRARY_PATH
/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/extras/CUPTI/lib64
$ echo $CUDA_PATH
/usr/local/cuda
$ echo $PATH
/usr/local/cuda/bin:...
```

Afterwards I use `pip install cupy` to install cupy in an empty environment.
This gives the following error.
```
ERROR: Could not find a version that satisfies the requirement cupy
ERROR: No matching distribution found for cupy
```

If I use `pip install cupy-cuda101` installation works fine, but doesn't change the error, when running the code.

**Comment by adrianeboyd** [comment]
The binary wheel with `cupy-cuda101` should be the better choice here. Uninstall all `cupy` and `cupy-cudaXXX` packages (or start in a new venv, remembering to upgrade `pip` first) and then install only `cupy-cuda101`.

Otherwise, I'm unfortunately not really sure why it's not working. Have you successfully used this CUDA installation in other projects? Or have you run some of the simple CUDA samples (e.g., https://github.com/NVIDIA/cuda-samples/tree/v10.1) to test it?

**Comment by laxmimerit** [comment]
It works if you put your cuda version too while installing spacy. For me
```
pip install -U spacy[cuda112]
```
because I have cuda 11.2. get the cuda version from here `nvidia-smi`
