### ISSUE TITLE
Spacy confuses verb and proper noun

### ISSUE THREAD

**Issue by quangduc** [explosion/spaCy#7097]
Hi,

I need to parse the sentence: "Northstar Capital Invests in Alpaca Audiology". It is supposed that "invests" is the root verb of this sentence. Instead, because Invest is capitalized, spacy produces a dependency tree like this:

<img width="899" alt="Screen Shot 2021-02-16 at 20 35 04" src="https://user-images.githubusercontent.com/4360657/108112772-da9c1700-7096-11eb-887e-58c5bdbbe6ad.png">

Even when I try to lowercase the word "invests", it still generates this tree, even though invest is not a noun:

<img width="831" alt="Screen Shot 2021-02-16 at 21 38 35" src="https://user-images.githubusercontent.com/4360657/108119056-88132880-709f-11eb-93bc-65f2bfdb2eed.png">

Can you give me some hint on how to guide spacy to handle this case? Thanks a lot

**Comment by honnibal** [comment]
Sometimes the parse tree is just wrong, unfortunately. Generally the `en_core_web_trf` model in v3 will be the most accurate. You can try doing "uptraining" on your data by running the `en_core_web_trf` model and training a smaller model on the resulting parses.

**Comment by quangduc** [comment]
Thanks you. I got it. Let me try with ``en_core_web_trf``
