### ISSUE TITLE
Support for Confidence Scores in NER models (spaCy 3.0)?

### ISSUE THREAD

**Issue by abhipn** [explosion/spaCy#7098]
Does spaCy 3.0 supports a way to extract the NER entities and also their confidence scores. I have read few previous discussions [#6644 ](https://github.com/explosion/spaCy/issues/5917) [#5917](https://github.com/explosion/spaCy/issues/5917), where it was mentioned that it will be available by v3. This is very useful when we want to discard certain entities which are wrongly predicted and has low confidence score.

Any update on it?

**Comment by honnibal** [comment]
It's definitely an important requirement, but I haven't been able to get useful scores out of the main NER component. The `SpanCategorizer` component in development will provide this as a key feature: https://github.com/explosion/spaCy/pull/6747

The difference is that the `SpanCategorizer` assigns a probability to `(span, label)` pairs directly, it doesn't operate token-by-token. The scores will therefore be much more useful.

**Comment by honnibal** [comment]
Closing to merge with #5917
