### ISSUE TITLE
The example on https://spacy.io/usage/rule-based-matching#phrasematcher didn't work?

### ISSUE THREAD

**Issue by RebeWu** [explosion/spaCy#7099]
## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:

**Comment by RebeWu** [comment]
Here is the bug info, I don't understand why and how to fix it 
ValueError                                Traceback (most recent call last)
<ipython-input-59-90a6833abc9c> in <module>
     10   }
     11 ]
**---> 12 matcher.add("FOUNDED", [pattern])**
     13 doc = nlp("Smith founded two companies.")
     14 matches = matcher(doc)

dependencymatcher.pyx in spacy.matcher.dependencymatcher.DependencyMatcher.add()

dependencymatcher.pyx in spacy.matcher.dependencymatcher.DependencyMatcher.validateInput()

**ValueError: [E098] Invalid pattern specified: expected both SPEC and PATTERN.**

**Comment by svlandeg** [comment]
Hm, that's weird. This example does work for me on spaCy 3.0.3 - both on a local install as well as when I select "Run" on the website docs itself.

Which exact version of spaCy are you using, and how did you install it? 
Can you also copy the exact code you're running - just to eliminate that no errors may have crept in?

**Comment by rcao1997** [comment]
Same thing happened to me. 

# spaCy version    3.0.1                         
# Platform         Darwin-19.3.0-x86_64-i386-64bit
# Python version   3.7.6                         
# Pipelines        en_core_web_sm (3.0.0)

`import spacy
from spacy.matcher import DependencyMatcher

nlp = spacy.load("en_core_web_sm")
matcher = DependencyMatcher(nlp.vocab)
pattern = [
  {
    "RIGHT_ID": "anchor_founded",       # unique name
    "RIGHT_ATTRS": {"ORTH": "founded"}  # token pattern for "founded"
  }
]
matcher.add("FOUNDED", [pattern])
doc = nlp("Smith founded two companies.")
matches = matcher(doc)
print(matches) # [(4851363122962674176, [1])]`

Code is exactly same as shown in the website. 

The most weird thing is that the code works for me last week, but it doesn't work anymore.

**Comment by adrianeboyd** [comment]
The error looks like it's from from running a spacy v3.x example with spacy v2.x. The dependency matcher pattern format was changed from v2 (where it was still officially undocumented) to v3. The v3 version no longer uses `SPEC` or `PATTERN`.

**Comment by rcao1997** [comment]
Thanks for your answer. I double checked my version and it is true that it becomes v2.3.5. I had installed v3 when v3 just released. I am wondering why the version becomes v2 today? Will it because that I installed `spacy-stanza 0.2.4` yesterday which requires `spacy<3.0.0,>=2.1.0`?

**Comment by adrianeboyd** [comment]
Yes, installing `spacy-stanza==0.2.4` would downgrade `spacy` to v2. I think this is a frustrating side effect of installing things incrementally with pip. I think it will detect the conflict if you try to install both packages at the same time, but otherwise it will assume your most recent `pip install` should override earlier versions.

It also looks like we screwed up with `spacy-stanza<=0.2.3`, which mistakenly think they're compatible with spacy v3 when they aren't. We should potentially yank those releases, I think.
