### ISSUE TITLE
AttributeError: 'spacy.tokenizer.Tokenizer' object has no attribute '_prefix_re'

### ISSUE THREAD

**Issue by ionree** [explosion/spaCy#710]
## Problem Description

Passing the pipeline obtained by `spacy.load('en')` between processes with a BaseManager requires the object to be pickled. This calls the `__reduce__` method on the Tokenizer, which tries to return the following non-existing attributes:

```
1) _prefix_re
2) _suffix_re
3) _infix_re
```

The affected source file is `tokenizer.pyx`.

## Traceback
```
Traceback (most recent call last):
  File "E:\code\textstats\analyser.py", line 115, in worker
    parser = nlp_proxy.get_nlp()
  File "<string>", line 2, in get_nlp
  File "C:\Python27\lib\multiprocessing\managers.py", line 774, in _callmethod
    raise convert_to_error(kind, result)
RemoteError: 
---------------------------------------------------------------------------
Unserializable message: Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\managers.py", line 288, in serve_client
    send(msg)
  File "spacy/tokenizer.pyx", line 103, in spacy.tokenizer.Tokenizer.__reduce__ (spacy/tokenizer.cpp:4728)
    self._prefix_re,
AttributeError: 'spacy.tokenizer.Tokenizer' object has no attribute '_prefix_re

---------------------------------------------------------------------------`
```

## Your Environment

* **Operating System:** Windows 10
* **Python Version Used:** Python 2.7.13
* **spaCy Version Used:** 1.4.0

**Comment by honnibal** [comment]
Unfortunately spaCy doesn't currently support the pickle protocol. This is on the roadmap for v2. You can find more discussion on this issue in #125, #377, and #606 .

**Comment by ionree** [comment]
Is there any way of running multiple processes in parallel using the same pipeline?

**Comment by honnibal** [comment]
Here's how I usually do that: https://github.com/explosion/spaCy/blob/master/examples/parallel_parse.py
