### ISSUE TITLE
cli.evaluate displacy function not displaying entities

### ISSUE THREAD

**Issue by timothyjlaurent** [explosion/spaCy#7108]
## How to reproduce the behavior

```bash
python -m spacy evaluate training/best-model corpus/dev.spacy --displacy-path=training/displacy
```
When I do this the displacy HTML has no annotations, just empty divs  :(

If I actually process the `example.predictions` in the displacy block then it renders properly:

```python 

from spacy.cli.evaluate import render_parses

displacy_path = 'training/displacy'

factory_names = [nlp.get_pipe_meta(pipe).factory for pipe in nlp.pipe_names]
docs = [nlp(ex.predicted.text) for ex in ds] # <-- before this was just ex.predicted - 
render_deps = "parser" in factory_names
render_ents = "ner" in factory_names
render_parses(
    docs,
    displacy_path,
    model_name='model',
    limit=100,
    deps=render_deps,
    ents=render_ents,
)
msg.good(f"Generated {displacy_limit} parses as HTML", displacy_path)

```

## Your Environment

- **spaCy version:** 3.0.3
- **Platform:** Linux-5.4.0-1035-aws-x86_64-with-glibc2.10
- **Python version:** 3.8.5

This Is pretty much because the `ex.predicted.ents` is always `()` after loading the corpus - when you evaluate the model, the pipeline somehow gets run on a copy of the examples (I couldn't figure out how), but this doesn't happen in render_parses.

**Comment by adrianeboyd** [comment]
Yes, this changed right before the v3.0 release so that `nlp.evaluate()` only runs on a copy of the predicted docs, since you might have gold annotation in `ex.predicted` that you need to use for the evaluation, so you don't want to clobber it. But the `evaluate` CLI didn't get updated to handle this change.
