### ISSUE TITLE
URL of spacy.en model

### ISSUE THREAD

**Issue by wyysfzj** [explosion/spaCy#711]
Since our server which used to locate spacy have no internet access, we downloaded the spacy-1.4.0.tar.gz from PIP site firstly, and the install. Now we have to download spacy.en model file separately, and then install.

However, we cannot find the URL of spacy.en model for downloading separately. 

would you please advise the URL of spacy.en model which can download separately?

**Comment by xushenkun** [comment]
http://index.spacy.io/models/en-1.1.0/archive.gz

**Comment by davidolsen1994** [comment]
Now how to link this to the spacy-master ?

**Comment by ines** [comment]
After trying out different solutions, we decided to simply attach the models as archive files to the latest release. The files are still quite large (between 500 and ~700MB), but they can now be downloaded via the browser. The English and German models are already uploaded and I'm currently waiting for the GloVe vectors to finish (which is the largest file).

➡️ https://github.com/explosion/spaCy/releases/tag/v1.6.0

Here's how to install the models manually:

1. **Find the default data path.** Use `spacy.util.get_data_path()` to find the directory where spaCy will look for its models, or change the default data path with `spacy.util.set_data_path()`.
2. **Unpack the archive** and place the contained folder in that directory.
3. **Load the model** via `spacy.load('en')` or `spacy.load('de')`.

cc: @wyysfzj, @xushenkun, @davidolsen1994

**Comment by awestley** [comment]
I just want to add to the steps @ines and mention: `spacy.util.get_package()` as a way to load the model from a directory. 

So it would be like `spacy.util.get_package('PATH to archive.gz')`
