### ISSUE TITLE
entity_linker.set_kb(kb): TypeError: 'spacy.kb.KnowledgeBase' object is not callable

### ISSUE THREAD

**Issue by moyid** [explosion/spaCy#7119]
## How to reproduce the behaviour
```
import spacy
nlp = spacy.load("en_core_web_lg")
from spacy.kb import KnowledgeBase
kb = KnowledgeBase(vocab=nlp.vocab, entity_vector_length=300)

entity_linker = nlp.create_pipe("entity_linker", config={"incl_prior": False})
entity_linker.set_kb(kb)

```
## Your Environment
- **spaCy version:** 3.0.3
- **Platform:** macOS-10.16-x86_64-i386-64bit
- **Python version:** 3.8.5
- **Pipelines:** en_core_web_lg (3.0.0)

**Comment by svlandeg** [comment]
You actually need to pass in a callable function to [`entity_linker.set_kb`](https://spacy.io/api/entitylinker#initialize). This function should take a vocab instance, and return the KB. This way, we ensure that the vocab from the KB and from the pipeline are always synced.

Admittedly this is a little counter-intuitive, but the required changes to your call are minimal. This should work:
```
    import spacy
    nlp = spacy.load("en_core_web_lg")
    from spacy.kb import KnowledgeBase
    
    def create_kb(vocab):
        return KnowledgeBase(vocab=vocab, entity_vector_length=300)

    entity_linker = nlp.create_pipe("entity_linker", config={"incl_prior": False})
    entity_linker.set_kb(create_kb)
```
I'll have a look into making the error message more specific/helpful here!
