### ISSUE TITLE
Main matcher won't capture custom patterns after 1.4

### ISSUE THREAD

**Issue by adam-ra** [explosion/spaCy#712]
The main matcher object apparently changed its behaviour in 1.4 or earlier. It no longer responses to adding custom patterns, these are silently ignored even though entity keys are being added to _entities.

This code works properly with Spacy 0.101.0 (prints out one match as expected) but nothing is captured when using Spacy 1.4 or 1.5. Using add_pattern instead of add (the line commented out) doesn't help.
Creating an external matcher object works, but the main matcher object seems resistant to customisations :(

```
import spacy
nlp = spacy.en.English()

spec = [{spacy.symbols.LOWER: 'horn'}, {spacy.symbols.LOWER: 'pub'}]
nlp.matcher.add('MyPattern', 'pat1', {}, [spec])
#nlp.matcher.add_pattern('MyPattern', spec, label='pat1')

for match in nlp('Porn hub or horn pub?').ents:
    print('>', match.label, match.text)
```

Tested under Python 3 (3.4.3+), Ubuntu 15.10 64-bit

**Comment by adam-ra** [comment]
Something fishy is going on here, the matcher_example.py (https://github.com/explosion/spaCy/blob/2f7ef4b150d2ed055b97f47dfd7fb75eabc926f6/examples/matcher_example.py) now (Spacy 1.5.0) outputs two PERSON annotations even though there is no rule for PERSON added.

```
Before
Google Now PERSON ['NNP', 'RB']
After
Google Now PERSON ['NNP', 'RB']
Sydney True
sydney False
Sydney True
sydney True
SYDNEY True
```

**Comment by honnibal** [comment]
Hey,

Just before I test this: did you see that the `Matcher` works a bit differently after 1.0? Specifically, it no longer writes to the `Doc` by default — it just outputs the matches, and then you can add a callback to handle them.

I agree that this behaviour is confusing in the case of the default matcher, especially since it's different from before.

**Comment by adam-ra** [comment]
Hi,
I missed this change to be honest. But also, I haven't used the matcher directly (except adding patterns), I just assumed that the matcher will be used internally when parsing a paragraph with nlp(text), so I'm not sure if this is change is intended.
Some background of my use: This was very convenient to be able to add custom rules to the main matcher that will be fired by default, especially that later on in my code I no longer have access to Doc objects, only single sentences, so there's probably no possibility of calling matcher again without major refactoring.

**Comment by honnibal** [comment]
Have you tried attaching a callback?

I'll think about how to communicate this better...

**Comment by adam-ra** [comment]
No, I haven't tried so far, perhaps this would solve the problem.
Meantime, I've almost finished the refactor so that the main matcher will not be needed. An extra benefit is that there is no need for firing the default NER anymore which I don't need.

As for communicating, you could discourage users from fiddling with the main matcher, remove that unfortunate matcher example and possibly add an example that people can obtain matches by doing this:

`ent = spacy.tokens.span.Span(s_par, idx0, idx1, label=label_idx)`

What would remain unclear, though, is the purpose of the main matcher.

**Comment by honnibal** [comment]
I was thinking of having a Matcher subclass called something like RuleNER, owned by the entity recogniser. Then the two instances can work together, and it's transparent that the rules will modify the document.

The logic behind the change was that the Matcher class is really a much more general building block, that isn't specific to NER.

**Comment by adam-ra** [comment]
I don't know the whole picture, but guessing from your description another subclass would increase the perceived complexity of the system without adding much value, so I'd rather just rename the instance (rule_ner_matcher or something related) if anything. But, again, I'm not sure if I understand the whole design.

**Comment by adam-ra** [comment]
BTW is there a way of transferring those entities captured by an external matcher onto token level? That is, to be able to access them via tok.ent_type_ as in older Spacy?

**Comment by honnibal** [comment]
If you assign to `doc.ents`, it should update the `token.ent_type`. The token is a view of the document, which is the single source of truth. So if it's visible on the document it should be reflected at the token and span. If it's not, something's really wrong.

**Comment by adam-ra** [comment]
Wow, I didn't know that tokens and sentences are only views.
Indeed assigning to doc.ents works like a charm, it even works correctly no matter if the entities are Span objects or tuples as output by the matcher.
Thanks a lot for this explanation, all the previous help and all the great work, I really appreciate it!

**Comment by honnibal** [comment]
I know the docs used to be pretty useless, but have a look at https://spacy.io/docs if you haven't checked it out lately :). There's a page on the data model now, that I wish I'd written much sooner. There's another page on the matcher, if you haven't seen it.

No problem — we've got a lot more planned for early next year.

**Comment by adam-ra** [comment]
I've seen the updated docs but I've missed the section on data model, thanks!
BTW I wish I had heard about Cython some years ago, I used to write NLP projects in C++/SWIG/Python combo, maintaining those was really painful.
