### ISSUE TITLE
UkrainianLemmatizer initializes to RussianLemmatizer and does not use Ukrainian dicts

### ISSUE THREAD

**Issue by isamokhin** [explosion/spaCy#7124]
## How to reproduce the behaviour

At the moment, UkrainianLemmatizer is inherited from RussianLemmatizer, because it is using the same tool - pymorphy2 - as aid to lemmatization. For use with Ukrainian, in addition to pymorphy2, Ukrainian dicts also have to be installed, and it is stated in error message when trying to initialize UkrainianLemmatizer without pymorphy2 in the system:
```
        try:
            from pymorphy2 import MorphAnalyzer
        except ImportError:
            raise ImportError(
                "The Ukrainian lemmatizer requires the pymorphy2 library and "
                "dictionaries: try to fix it with "
                '"pip install pymorphy2 pymorphy2-dicts-uk"'
            ) from None
```
However, right now class is initialized using `super().__init__()` before checking for pymorphy2 and Ukrainian dicts. As a result, RussianLemmatizer is initialized.

If there is no pymorphy2 in the system,  this code
```
nlp = spacy.blank('uk')
lemmatizer = nlp.add_pipe("lemmatizer")
print(lemmatizer._morph.lang)
```

gets you the message:

```
  File "/home/igor/Applications/miniconda3/envs/spacy3_test/lib/python3.9/site-packages/spacy/lang/uk/__init__.py", line 32, in make_lemmatizer
    return UkrainianLemmatizer(nlp.vocab, model, name, mode=mode, overwrite=overwrite)
  File "/home/igor/Applications/miniconda3/envs/spacy3_test/lib/python3.9/site-packages/spacy/lang/uk/lemmatizer.py", line 19, in __init__
    super().__init__(vocab, model, name, mode=mode, overwrite=overwrite)
  File "/home/igor/Applications/miniconda3/envs/spacy3_test/lib/python3.9/site-packages/spacy/lang/ru/lemmatizer.py", line 31, in __init__
    raise ImportError(
ImportError: The Russian lemmatizer requires the pymorphy2 library: try to fix it with "pip install pymorphy2"
```

This is RussianLemmatizer error message, no mention of Ukrainian dicts.
If pymorphy2 and pymorphy2-dicts-uk are installed, the same code prints "ru" - meaning that pymorphy2 analyzer is set to Russian language and therefore will not work properly for Ukrainian.

The problem is with this code in lemmatizer.py for Ukrainian:
```
        if UkrainianLemmatizer._morph is None:
            UkrainianLemmatizer._morph = MorphAnalyzer(lang="uk")
```

Since `super().__init__()` is called _earlier_, UkrainianLemmatizer._morph is never None - it is already set to Russian version of MorphAnalyzer. This code will never be executed.

**How to solve the problem**:

The easiest solution seems to be changing the above line to something like

```
        if UkrainianLemmatizer._morph is None or UkrainianLemmatizer._morph.lang != 'uk':
            UkrainianLemmatizer._morph = MorphAnalyzer(lang="uk")
```
I think it is easy to fix, but if you need help, I can make a pull request.

I know UkrainianLemmatizer will not work out of the box using blank model, and I found the bug only when trying to use it in the trained model with tagger and parser.

## Your Environment

* Operating System: Linux Mint 19
* Python Version Used: 3.9.1
* spaCy Version Used: 3.0.3
* Environment Information:

**Comment by adrianeboyd** [comment]
Thanks for the report! It's hard to keep this tested when we don't have Ukrainian models ourselves.

I think it would be fine to just move the `super.__init__()` below the pymorphy2 initialization, which should get this back in the right order to load `uk` instead of `ru`.

**Comment by isamokhin** [comment]
Thank you for the quick reaction!

Moving `super.__init__()` up also would work, if we add `_morph = None` above `__init__()` method, to avoid `AttributeError` when checking the `UkrainianLemmatizer._morph` value.
