### ISSUE TITLE
Custom Text Classification Model - Labels for component 'textcat' not initialized

### ISSUE THREAD

**Issue by oliverbj** [explosion/spaCy#7125]
## How to reproduce the behaviour

I am trying to create a custom model on some training data. For this, I want to train a custom text classification model. This is my approach (simplified):

First I have some training data, that looks like this:

```
[('Some text....', {'cats': {'POSITIVE': True, 'NEGATIVE': False}}), ("Another text......", {'cats': {'POSITIVE': True, 'NEGATIVE': False}})]
```

Then I try to create a blank model with a custom text classification:
```
# Load model
nlp=spacy.blank("en")
#Create a new pipeline
category = nlp.create_pipe('textcat')
#Add our two labels
category.add_label("POSITIVE")
category.add_label("NEGATIVE")
nlp.add_pipe('textcat')

# Train the model:
# train_data contains
train_model(nlp, train_data)
```

The `train_model` method looks like the below:
```python
#Train the model:
def train_model(nlp, TRAINING_DATA, output_dir='C:\\Users\\Oliver\\Documents\\PythonAPI\\'):
    # Start the training
    nlp.begin_training()

    # Loop for 10 iterations
    for _ in range(10):
        # Shuffle the training data
        random.shuffle(TRAINING_DATA)
        losses = {}

        # Batch the examples and iterate over them
        for batch in spacy.util.minibatch(TRAINING_DATA, size=1):
            texts = [nlp(text) for text, entities in batch]
            annotations = [{"cats": entities} for text, entities in batch]
            nlp.update(texts, annotations, losses=losses)

    nlp.to_disk(output_dir)
    print("Saved model to", output_dir)
```

The above code gives me the below error:

> ValueError: [E143] Labels for component 'textcat' not initialized. This can be fixed by calling add_label, or by providing a representative batch of examples to the component's `initialize` method.

## Your Environment
* Operating System: Windows
* Python Version Used: 3.8
* spaCy Version Used: 3

**Comment by oliverbj** [comment]
I changed the code where I load the blank model and add the custom categories:

```python
# Load model
nlp=spacy.blank("en")

#Create a new pipeline
category = nlp.add_pipe('textcat')

#Add our two labels
category.add_label("POSITIVE")
category.add_label("NEGATIVE")
```

Which seems to have fixed the above error.

**Comment by adrianeboyd** [comment]
As a note, aside from `nlp.add_pipe("textcat")` this script looks like it was written for spacy v2, so you'll need to downgrade to spacy v2 or make some additional changes related to training in v3, see https://spacy.io/usage/v3#migrating-training-python.

We hope to have a simple demo textcat project available soon, which will show how to train from demo data with `spacy train` instead of this kind of script, which was only intended to demonstrate the basics for v2 and is missing a number of features you'd probably like to have in your training setup.

**Comment by oliverbj** [comment]
> As a note, aside from `nlp.add_pipe("textcat")` this script looks like it was written for spacy v2, so you'll need to downgrade to spacy v2 or make some additional changes related to training in v3, see https://spacy.io/usage/v3#migrating-training-python.
> 
> We hope to have a simple demo textcat project available soon, which will show how to train from demo data with `spacy train` instead of this kind of script, which was only intended to demonstrate the basics for v2 and is missing a number of features you'd probably like to have in your training setup.

Thanks @adrianeboyd for further clarifiying! I actually ended up starting from scatch and using this: [textcat_goemtions](https://github.com/explosion/projects/tree/v3/tutorials/textcat_goemotions). By using this as my starting point, I have successfully trained my own custom model using my own labels :)

**Comment by adrianeboyd** [comment]
Glad to hear it, that's exactly what the projects are intended for. We also have some simpler textcat ones that will be added soon: https://github.com/explosion/projects/pull/39
