### ISSUE TITLE
Matcher Docs Code example broken

### ISSUE THREAD

**Issue by richAtreides** [explosion/spaCy#7136]
The code does not compile here: 

https://spacy.io/usage/rule-based-matching as the function signature has changed for Matcher.add. Additionally the pattern is not in a nested list and so does not work.

I've fixed the code. Here it is so you can add it:

```import spacy
from spacy.matcher import Matcher

nlp = spacy.load("en_core_web_sm")
matcher = Matcher(nlp.vocab)
# Add match ID "HelloWorld" with no callback and one pattern
pattern = [[{"LOWER": "hello"}, {"IS_PUNCT": True}, {"LOWER": "world"}]]
matcher.add("HelloWorld", pattern)

doc = nlp("Hello, world! Hello world!")
matches = matcher(doc)
for match_id, start, end in matches:
    string_id = nlp.vocab.strings[match_id]  # Get string representation
    span = doc[start:end]  # The matched span
    print(match_id, string_id, start, end, span.text)```

**Comment by adrianeboyd** [comment]
Hmm, this example runs as expected for me in the interactive demo on this page with v3.0. The older v2 example with the now-deprecated `Matcher.add` syntax also runs fine with v2.3.5 here: https://v2.spacy.io/usage/rule-based-matching

Can you check if it runs correctly on your end after a hard refresh of the web page?
