### ISSUE TITLE
Test if word in vocabulary of spacy

### ISSUE THREAD

**Issue by kootenpv** [explosion/spaCy#714]
Great job on Spacy, fantastic dependency parser!

Question: is there a way to test if words are in the (english) vocabulary?

**Comment by kootenpv** [comment]
It's actually really obvious:

`s in nlp.vocab`

**Comment by FrancescoSaverioZuppichini** [comment]
Not working

```
nlp = spacy.load('en')

doc = nlp('I am sflmgmavknsaccasas')

for token in doc:
    print(token in nlp.vocab)
```
Error:

```
TypeError: an integer is required
```
Also, `is_oov` is broken:

```
for token in doc:
    print(token.is_oov)
```
```
True
True
True
```

**Comment by ghonk** [comment]
Same issue, attempting to use the method to find *only* real words in scraped text. The `in nlp.vocab` approach throws an error and all real words tested are `True` for `is_oov`

```
doc = nlp('I am sflmgmavknsaccasas dog cat bird bulbasaur')
```
```
[tok for tok in doc if tok in nlp.vocab]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
  File "vocab.pyx", line 194, in spacy.vocab.Vocab.__contains__
TypeError: an integer is required
```

```
[tok.is_oov for tok in doc]
[True, True, True, True, True, True, True]
```

**Comment by zveryansky** [comment]
@ghonk  here is a workaround:
`
for token in 'k8s sdjhsd horse hit'.split(' '):
    print(nlp.vocab.has_vector(token))
`
