### ISSUE TITLE
Convert the earlier Spacy Tuples to training data for version 3

### ISSUE THREAD

**Issue by anselmn** [explosion/spaCy#7143]
hi Team, I am new to spacy and just late last year got started on spacy version 2, I now want to adopt to the latest version 3, but I am clueless of how to build my training dataset. 
In version 2 I had created a set of Tuples of the form --- 
[("Hello. I used the gel with Glycolic Acid and it was bad for my skin, even some pimples appeared.", {"entities": [(80,95, "ReportedTerm")]})].....
And used to directly pass this in Jupyter notebook to train the model, how do I now convert these set of tuples into a .spacy file for training spacy v3. 

Any help here will be greatly appreciated, have been going through the documentation in circles without any clear instruction set. 

Thanks. 

## Your Environment

- Operating System: Windows10
- Python Version Used:3.8.5
- spaCy Version Used:3
- Environment Information:

**Comment by svlandeg** [comment]
Hi! This is a good question for the discussion forum, so I'll move it there. You may get a notification that your issue was closed/locked, but the thread is still open at the forum and you should be forwarded their automatically :-)
