### ISSUE TITLE
[E970] Can not execute command 'mkdir -p training/cnn'. Do you have 'mkdir' installed?

### ISSUE THREAD

**Issue by oliverbj** [explosion/spaCy#7145]
## How to reproduce the behaviour
I am trying to use the project feature in spaCy version 3. More specifically, I have installed the project [textcat_goemotions](https://github.com/explosion/projects/tree/v3/tutorials/textcat_goemotions). Following the spaCy documentation [here](https://spacy.io/usage/projects), I am running the following commands:

```ssh
python -m spacy project clone tutorials/textcat_goemotions
cd textcat_goemotions python -m spacy project assets
python -m spacy project run preprocess
```

All of this works. However, when I want to run the workflow like:

```
python -m spacy project run all
```

I get the following error:
> [E970] Can not execute command 'mkdir -p training/cnn'. Do you have 'mkdir' installed?

This seems to happen at the training pipeline `python -m spacy project run train`

If I go to `project.yml` and remove the following line: 

```
script:
      - "mkdir -p training/${vars.config}"
```
I can successfully run the `run all` command. 

I am not sure if this error is because I started by running `run preprocess` then followed by `run all`?

## Your Environment

* Operating System: Windows
* Python Version Used: 3.8
* spaCy Version Used: 3

**Comment by svlandeg** [comment]
I guess this is the same issue as https://github.com/explosion/spaCy/issues/6957 - the example projects are currently a bit Unix-centered and use commands such as `mkdir` that may not be available in every CLI tool on Windows. I'll go ahead and close this issue to merge it with https://github.com/explosion/spaCy/issues/6957 if that's alright by you. But yes this should be addressed (contributions welcome!).
