### ISSUE TITLE
vocab.load_vector() not parsing vector file correctly

### ISSUE THREAD

**Issue by hamelsmu** [explosion/spaCy#715]
I have am following the instructions here: https://spacy.io/docs/usage/word-vectors-similarities

> You can load new word vectors from a file-like buffer using the vocab.load_vectors() method. The file should be a whitespace-delimited text file, where the word is in the first column, and subsequent columns provide the vector data.

For debugging purposes, I have created a sample file that is 100 dimensions and follows the above instructions (it is whitespace delimited, etc.)  I attached this text file to this post (is just 8 lines).  

[sample.txt](https://github.com/explosion/spaCy/files/678951/sample.txt)

```
import spacy
en_nlp = spacy.load('en')
en_nlp.vocab.load_vectors('sample.txt')
```

This returns 0 (should return 100)  What is wrong?  I have verified that the vector is not loaded. 
I am using spacy version '1.5.0'

**Comment by honnibal** [comment]
Hmm. Possibly a bug here. It's working for me:

    >>> import spacy
    >>> nlp = spacy.load('en')
    >>> text = open(u'/Users/matt/Downloads/sample.txt')
    >>> nlp.vocab.load_vectors(text)
    100

So:

* Do you have the data installed? It should still work if not, but this might be a difference.
* Python version?
* OS?

**Comment by hamelsmu** [comment]
I'm not able to reproduce this error now so I will go ahead and close this issue.  I updated my OS to Sierra and also did a fresh install of spacy and these problems went away.
