### ISSUE TITLE
nlp.rehearse error in spacy version 3.0.1

### ISSUE THREAD

**Issue by anilnishad19799** [explosion/spaCy#7161]
I have build custom NER , i just want to add new pattern/ner label in my existing model without forgetting
previous knowledge(incremental/online learning), so that i used rehearse and resume_training method from https://spacy.io/api/language#resume_training

### Environment
* Operating System: Windows
* spaCy Version Used: 3.0.1

### Training Code
```
TRAIN_DATA = [
    ('Who is Kofi Annan?',{
    'entities':[(7,18,'PERSON')]
    }),
    ('Who is Steve Jobs?',{
    'entities':[(7,17,'PERSON')]
    }),
    ('I like London and Berlin.',{
    'entities':[(7,13,'LOC'),(18,24,'LOC')]
    })
]

nlp = spacy.blank('en')

ner = nlp.create_pipe('ner')
nlp.add_pipe('ner')

for _,annotations in TRAIN_DATA:
    for ent in annotations.get('entities'):
        ner.add_label(ent[2])

optimizer = nlp.begin_training()
for itn in range(100):
    for raw_text,entity_offsets in TRAIN_DATA:
        doc = nlp.make_doc(raw_text)
        example = Example.from_dict(doc,entity_offsets)
        nlp.update([example],sgd=optimizer)

nlp.to_disk(output_dir)
```
### Incremental Training Code
I have used rehearse and resume_training method in place of  update method for incremental training (completely new data).
```
training_data = [
    ('Hi Anil',{'entities':[(3,7,'PERSON')]
    }),
    ('Hi Anil, how are you?',{'entities':[(3,7,'PERSON')]
    }),
    ('Hi Ravish, how you doing?',{'entities':[(3,9,'PERSON')]
    })
]

nlp_incremental_try = spacy.load(output_dir)
ner = nlp_incremental_try.get_pipe('ner')

for _,annotations in training_data:
    for ent in annotations.get('entities'):
        ner.add_label(ent[2])

optimizer = nlp_incremental_try.resume_training()
for itn in range(100):
    random.shuffle(training_data)
    for raw_text,entity_offsets in training_data:
        doc = nlp_incremental_try.make_doc(raw_text)
        example = Example.from_dict(doc,entity_offsets)
        nlp_incremental_try.rehearse([example],sgd=optimizer)
```

### Error

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-cab349d2a8fa> in <module>
     12         doc = nlp_incremental_try.make_doc(raw_text)
     13         example = Example.from_dict(doc,entity_offsets)
---> 14         nlp_incremental_try.rehearse([example],sgd=optimizer)

~\AppData\Local\Programs\Python\Python38\lib\site-packages\spacy\language.py in rehearse(self, examples, sgd, losses, component_cfg, exclude)
   1170                 continue
   1171             grads = {}
-> 1172             proc.rehearse(
   1173                 examples, sgd=get_grads, losses=losses, **component_cfg.get(name, {})
   1174             )

~\AppData\Local\Programs\Python\Python38\lib\site-packages\spacy\pipeline\transition_parser.pyx in spacy.pipeline.transition_parser.Parser.rehearse()

~\AppData\Local\Programs\Python\Python38\lib\site-packages\spacy\pipeline\trainable_pipe.pyx in spacy.pipeline.trainable_pipe.TrainablePipe.finish_update()

~\AppData\Local\Programs\Python\Python38\lib\site-packages\thinc\model.py in finish_update(self, optimizer)
    322             for name in node.param_names:
    323                 if node.has_grad(name):
--> 324                     param, grad = optimizer(
    325                         (node.id, name), node.get_param(name), node.get_grad(name)
    326                     )

~\AppData\Local\Programs\Python\Python38\lib\site-packages\spacy\language.py in get_grads(W, dW, key)
   1161 
   1162         def get_grads(W, dW, key=None):
-> 1163             grads[key] = (W, dW)
   1164 
   1165         get_grads.learn_rate = sgd.learn_rate

TypeError: unhashable type: 'numpy.ndarray'
```
So kindly suggest me what am i doing wrong?
please help me.

**Comment by anilnishad19799** [comment]
Is this a bug or am i doing something wrong?
Any update on this issue?

please suggest me

**Comment by rammohanrrr** [comment]
I got the same issue

**Comment by polm** [comment]
Hey, sorry you're having trouble with this, and for the delayed reply. That does look like a bug, but resuming training is still an experimental feature, so it's kind of in a use-at-your-own-risk state. I think it's reasonably complete and we want to polish it up with examples but I don't think we're actively working on it at the moment.

**Comment by pradeeptimeinc** [comment]
Any updates on this ?
Or if anybody can point me to the file or where the issue is , i may try to look for solution for it.
Thanks

**Comment by polm** [comment]
I don't think any of us are actively working on this at the moment. If you want to look at it I would start with the location in the code pointed out by the stack trace in the first post here.

**Comment by xadrianzetx** [comment]
Hi,

I had a look into this and found that `get_grads` seems to be called with arguments in incorrect order. This function gets passed to `finish_update()` in `thinc.model.Model` as `optimizer`, which calls it like so:
```python
param, grad = optimizer((node.id, name), node.get_param(name), node.get_grad(name))
```
but definition of `get_grads()` is as follows:

```python
def get_grads(W, dW, key=None):
```

As a result, tuple with node id and name is passed as weights, weights as grads and grads as key, like so:

![image](https://user-images.githubusercontent.com/37713008/123686008-99d7ba00-d84f-11eb-8396-9b4908338c65.png)

Of course in this case we are trying to set `numpy.array` as dict key, which results in original exception.

I would like to work on this further, but not sure how to proceed, since simply switching ordering of arguments in `get_grads` will  result in another exception (`optimizer` is expected to return tuple, but `get_grads` returns `NoneType`).

**Comment by FaCoffee1984** [comment]
Any update on this, @xadrianzetx? I am facing the same issue and had to conclude that, until this is resolved, it is not possible for me to take a pre-trained model and add custom NER labels to it, hence creating a model capable of tagging default but also bespoke categories.

**Comment by xadrianzetx** [comment]
I did not investigate it further.

**Comment by polm** [comment]
@FaCoffee1984 You could always use two separate NER pipelines. See [this example project](https://github.com/explosion/projects/tree/v3/tutorials/ner_double) for how that works.

**Comment by FaCoffee1984** [comment]
@polm certainly interesting to see an example. 

At any rate, I thought that one workaround could be:

1. Create a blank model and train it using the set of custom NER labels
2. Load a pre-trained model and use the train data as in point 1 as test dataset, so as to apply the default labels
3. In case of overlapping tags, as shown in your example, define a rule that specifies which set of NER labels has the precedence.
