### ISSUE TITLE
Sentencizer - Performance regression

### ISSUE THREAD

**Issue by Jooakim** [explosion/spaCy#7164]
Hello, since spacy v.3 I've noticed a clear performance regression when using the Sentencizer. The issue is not that apparent when chunking small pieces of text, but for large documents the sentencizer is almost unusable due to it's current performance. 

I've tracked the degradation to the change in the `__call__` function here:
https://github.com/explosion/spaCy/blob/b1996a51a1a51e310df8ce08964359376bd11a46/spacy/pipeline/sentencizer.pyx#L69

as compared to < v.3
https://github.com/explosion/spaCy/blob/c70e6ee72da59fac588b530cd5ad1295ea880b17/spacy/pipeline/pipes.pyx#L1549

The performance goes back to previous speed when using the <v.3 implementation of `__call__`. Consider the following snippet:
```python
import datetime
from spacy import blank
from spacy.pipeline.sentencizer import Sentencizer
slow_pipe = blank("en")
slow_pipe.add_pipe("sentencizer")
text = ' '.join(["This is a sentence."]*10000)

start = datetime.datetime.now()
slow_doc = slow_pipe(text)
print(f"total_time: {(datetime.datetime.now()-start).total_seconds()}")

fast_pipe = blank("en")
sentencizer= Sentencizer()

start = datetime.datetime.now()
fast_doc = fast_pipe(text)
tokvecses = sentencizer.predict([fast_doc])
sentencizer.set_annotations([fast_doc], tokvecses)
print(f"total_time: {(datetime.datetime.now()-start).total_seconds()}")
```
On my machine, the above code snippet results in ~17s for the first pipeline, and 0.02s for the second pipeline.

I'm not too familiar with spacy's source code, but I suspect that the current implementation is slower due to not operating on the cdef Doc/TokenC directly as in `set_annotations`.
## Your Environment

- Operating System: macOS Catalina 10.15.7
- Python Version Used: python 3.8.6
- spaCy Version Used: spacy 3.0.3
- Environment Information:

**Comment by adrianeboyd** [comment]
Thanks for the report, this does looks like a regression in v3. I could have sworn I had already done this (#4721), so I'm not sure what happened -- probably a mistake in some refactoring step for v3. We will get it fixed for the next v3 release (should be v3.0.4).

**Comment by adrianeboyd** [comment]
And as a note: you can use `nlp.pipe([text])` instead of `nlp(text)` to get the faster performance in v3.0.3.

**Comment by Jooakim** [comment]
Thank you for the fast response and fix 👍
