### ISSUE TITLE
Further training a Greek model (el_core_news_lg) for NER 

### ISSUE THREAD

**Issue by m-nlp-q** [explosion/spaCy#7166]
I am trying to further train a Greek model for NER, using the training configuration system with the [train](https://spacy.io/api/cli#train) command.
I converted to .spacy my training and dev datasets, and provided them as arguments to the train command and I get this error:

`It looks like there is no proper sample data to initialize the Model of component 'tok2vec'. To check your input data paths and annotation, run: python -m spacy debug data config.cfg`.

I run the debug data command and displays this:

`Received invalid get_examples callback in `Tok2Vec.initialize`. Expected function that returns an iterable of Example objects but got: []` 

It seems that my config file in `[paths]` section misses init_tok2vec value. What should I provide here and where can I find it?

This is my config file

```
[paths]
train = ./training_configuration/train.spacy
dev =. /training_configuration/dev.spacy
vectors = null
init_tok2vec = null

[system]
gpu_allocator = null
seed = 0

[nlp]
lang = "el"
pipeline = ["tok2vec","ner"]
batch_size = 1000
disabled = []
before_creation = null
after_creation = null
after_pipeline_creation = null
tokenizer = {"@tokenizers":"spacy.Tokenizer.v1"}

[components]

[components.ner]
factory = "ner"
moves = null
update_with_oracle_cut_size = 100

[components.ner.model]
@architectures = "spacy.TransitionBasedParser.v2"
state_type = "ner"
extra_state_tokens = false
hidden_width = 64
maxout_pieces = 2
use_upper = true
nO = null

[components.ner.model.tok2vec]
@architectures = "spacy.Tok2VecListener.v1"
width = ${components.tok2vec.model.encode.width}
upstream = "*"

[components.tok2vec]
factory = "tok2vec"

[components.tok2vec.model]
@architectures = "spacy.Tok2Vec.v2"

[components.tok2vec.model.embed]
@architectures = "spacy.MultiHashEmbed.v1"
width = ${components.tok2vec.model.encode.width}
attrs = ["ORTH","SHAPE"]
rows = [5000,2500]
include_static_vectors = false

[components.tok2vec.model.encode]
@architectures = "spacy.MaxoutWindowEncoder.v2"
width = 96
depth = 4
window_size = 1
maxout_pieces = 3

[corpora]

[corpora.dev]
@readers = "spacy.Corpus.v1"
path = ${paths.dev}
max_length = 0
gold_preproc = false
limit = 0
augmenter = null

[corpora.train]
@readers = "spacy.Corpus.v1"
path = ${paths.train}
max_length = 2000
gold_preproc = false
limit = 0
augmenter = null

[training]
dev_corpus = "corpora.dev"
train_corpus = "corpora.train"
seed = ${system.seed}
gpu_allocator = ${system.gpu_allocator}
dropout = 0.1
accumulate_gradient = 1
patience = 1600
max_epochs = 3
max_steps = 20000
eval_frequency = 200
frozen_components = []
before_to_disk = null

[training.batcher]
@batchers = "spacy.batch_by_words.v1"
discard_oversize = false
tolerance = 0.2
get_length = null

[training.batcher.size]
@schedules = "compounding.v1"
start = 100
stop = 1000
compound = 1.001
t = 0.0

[training.logger]
@loggers = "spacy.ConsoleLogger.v1"
progress_bar = false

[training.optimizer]
@optimizers = "Adam.v1"
beta1 = 0.9
beta2 = 0.999
L2_is_weight_decay = true
L2 = 0.01
grad_clip = 1.0
use_averages = false
eps = 0.00000001
learn_rate = 0.001

[training.score_weights]
ents_per_type = null
ents_f = 1.0
ents_p = 0.0
ents_r = 0.0

[pretraining]

[initialize]
vectors = null
init_tok2vec = ${paths.init_tok2vec}
vocab_data = null
lookups = null
before_init = null
after_init = null

[initialize.components]

[initialize.tokenizer]
```
Do I have anything else to provide in order to start training?

p.s. Is thraining the right commnad?
@svlandeg

**Comment by adrianeboyd** [comment]
Maybe the `debug data` issue is due to this typo here:

```ini
dev =. /training_configuration/dev.spacy
```

I'm actually not sure how this gets parsed in the end, but the `. /` is probably not what you meant. Can you fix this and try to run `debug data` again?

`init_tok2vec` is related to pretraining and it's fine for it to be `null` in your config.

**Comment by m-nlp-q** [comment]
@adrianeboyd thank you for your answer, this typo happened when copying the config file here. When I ran the command, it was correct. I continue to search the spaCy library and figuring out how it works. What I want to do, is to continue the training of the `el_core_news_lg` with a dataset I have and trying to construct the config file. Is there an example of a config file that continues the training of an already trained pipeline?

**Comment by svlandeg** [comment]
Hi! As I think this thread is well suited for the discussions forum, I'll move it there :-)
