### ISSUE TITLE
Token similarity is negative

### ISSUE THREAD

**Issue by Wasabi375** [explosion/spaCy#7171]
This issue is similar to https://github.com/explosion/spaCy/issues/2722

```
nlp = spacy.load('en_core_web_md')
a = nlp("allocation")
>>> b = nlp("cs")
>>> a.similarity(b)
-0.012003981687445186
```

I expect the similarity of 2 tokens to be between 0 and 1.

## Info about spaCy

* **spaCy version:** 2.3.2
* **Platform:** macOS-10.15.7-x86_64-i386-64bit
* **Python version:** 3.8.2
* **NumPy version:** 1.20.1

**Comment by svlandeg** [comment]
Hm, this is related to https://github.com/explosion/spaCy/issues/7053 where it was discussed that rounding errors may happen, though in this case it feels like quite a large rounding error from 0.

Did you happen to stumble upon this one, or did you test a larger batch of similarities and did you find this behaviour rather often? Or is really just a one-off?

**Comment by adrianeboyd** [comment]
I think the expected range for cosine similarity of word vectors is -1 to 1?

**Comment by svlandeg** [comment]
Oh yea you're right Adriane. So this is just expected behaviour really :-)

**Comment by Wasabi375** [comment]
I found this issue testing a large batch of similarities. I only found 1 case with a negative value in idk around ~10000 similarities.  

Does this mean that I can treat a similarity of 2 word vectors that is negative as just 0 or what exactly is the meaning of a negative number if this is expected?

**Comment by adrianeboyd** [comment]
I think that word vectors are often relatively clustered in the overall vector space, so negative cosine similarity may be rare. Negative cosine similarity is definitely not equivalent to 0.

**Comment by Wasabi375** [comment]
So before now I was under the impression that `a.similarity(b)` would return a value between 0 and 1 meaning that 2 equal words get a value of 1 and 2 words that are farthest apart get a value of 0. 
Based on your answers here I'm wrong and the result is a value between -1 and 1 with 1 meaning "equal" and -1 meaning farthest apart. Right?

**Comment by adrianeboyd** [comment]
Yes, that's right.
