### ISSUE TITLE
How to config a pkuseg tokenizer to a trained ner model?

### ISSUE THREAD

**Issue by baiziyuandyufei** [explosion/spaCy#7173]
## Your Environment

- **spaCy version:** 3.0.0rc5
- **Platform:** Darwin-20.3.0-x86_64-i386-64bit
- **Python version:** 3.6.12
- **Pipelines:** zh_core_web_trf (3.0.0a1)

use the config file generated by [https://spacy.io/usage/training](https://spacy.io/usage/training), get the model, the tokenizer.segmenter is 'char'.

```
>>> import spacy
>>> nlp = spacy.load("model-best-trf")
>>> nlp.tokenizer.segmenter
'char'
```

but the 'zh_core_web_trf-3.0.0a1' model's segmenter is 'pkuseg', How realize? 

```
>>> import spacy
>>> nlp = spacy.load("zh_core_web_trf")
>>> nlp.tokenizer.segmenter
'pkuseg'
```

I need to modify the training data to per word one line, not per character one line?

```
我                  O
非常              O
喜欢              O
贾                  B-PERSON
思                  I-PERSON
琪                  I-PERSON
。                  O
```

**Comment by adrianeboyd** [comment]
Hi, this is a good kind of question for the new discussions board. I'll transfer the issue there in a second. You'll get an automatic message that this issue is locked, but the discussion can continue in the new thread there.
