### ISSUE TITLE
Detailed tag is the same as the universal tag in Spanish models es_core_news_es and es_core_news_md

### ISSUE THREAD

**Issue by luckytito** [explosion/spaCy#7184]
## How to reproduce the behaviour

```
nlp = spacy.load('es_core_news_md')
text = 'Actualmente, la Hispanidad se celebra dentro y fuera de España, aunque es una de las fiestas que máspolémica generan.'
doc = nlp(text)
for token in doc:
    if token.text == mask:
        print(token.text, token.tag_, token.pos_, token.morph)

```

Output:

> Actualmente ADV ADV 
> , PUNCT PUNCT PunctType=Comm
> la DET DET Definite=Def|Gender=Fem|Number=Sing|PronType=Art
> Hispanidad PROPN PROPN 
> se PRON PRON Case=Acc,Dat|Person=3|PrepCase=Npr|PronType=Prs|Reflex=Yes
> celebra VERB VERB Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin
> dentro ADV ADV 
> y CCONJ CCONJ 
> fuera NOUN NOUN 
> de ADP ADP AdpType=Prep
> España PROPN PROPN 
> , PUNCT PUNCT PunctType=Comm
> aunque SCONJ SCONJ 
> es AUX AUX Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin
> una PRON PRON Gender=Fem|Number=Sing|PronType=Ind
> de ADP ADP AdpType=Prep
> las DET DET Definite=Def|Gender=Fem|Number=Plur|PronType=Art
> fiestas NOUN NOUN Gender=Fem|Number=Plur
> que PRON PRON PronType=Int,Rel
> máspolémica VERB VERB Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin
> generan VERB VERB Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin
> . PUNCT PUNCT PunctType=Peri

## Your Environment

* Operating System: Ubuntu 20.04
* Python Version Used: 3.8
* spaCy Version Used: `3.0.3`
* Environment Information:

**Comment by adrianeboyd** [comment]
Yes, this is a change from v2. There are no separate fine-grained tags for the Spanish training corpus, so the UPOS from `token.pos` is just copied to `token.tag` for convenience. The statistical `morphologizer` is predicting `token.pos` and `token.morph` underneath and `attribute_ruler` copies pos to tag.
