### ISSUE TITLE
Sudachi (Japanese tokenizer dep) fails

### ISSUE THREAD

**Issue by bittlingmayer** [explosion/spaCy#7196]
Partly to support spaCy, Sudachi now offers 3 versions - core, full and small.  The idea is that small has a smaller footprint.

spaCy anyway uses core though, not small - see https://github.com/explosion/spaCy/search?q=sudachipy
```
ja =
    sudachipy>=0.4.9
    sudachidict_core>=20200330
```

For whatever reason, SudachiPy has a problem whenever multiple versions are installed.

3 potential solutions, none ideal:

1. `pip uninstall sudachi_small` - That's a bit hacky.
2. `sudachipy link -t core` per the [Sudachi docs](https://github.com/WorksApplications/SudachiDict#python-packages).
3. Ask Sudachi to fix this.

## How to reproduce the problem

Add `spacy` and `spacy[ja]` to requirements.txt and pip install.  (pip3 in this case)

```bash
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
src/service/spacy.py:32: in _get_sentences
    nlp = _get_sentencizer(lang)
src/service/spacy.py:51: in _get_sentencizer
    _init_sentencizer(lang)
src/service/spacy.py:62: in _init_sentencizer
    nlp = NLP() # just the language with no model
venv/lib/python3.7/site-packages/spacy/language.py:177: in __init__
    self.tokenizer = create_tokenizer(self)
venv/lib/python3.7/site-packages/spacy/lang/ja/__init__.py:34: in japanese_tokenizer_factory
    return JapaneseTokenizer(nlp, split_mode=split_mode)
venv/lib/python3.7/site-packages/spacy/lang/ja/__init__.py:43: in __init__
    self.tokenizer = try_sudachi_import(self.split_mode)
venv/lib/python3.7/site-packages/spacy/lang/ja/__init__.py:198: in try_sudachi_import
    tok = dictionary.Dictionary().create(mode=split_mode)
venv/lib/python3.7/site-packages/sudachipy/dictionary.py:37: in __init__
    self._read_system_dictionary(config.settings.system_dict_path())
venv/lib/python3.7/site-packages/sudachipy/config.py:107: in system_dict_path
    dict_path = create_default_link_for_sudachidict_core(output=f)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

output = <_io.TextIOWrapper name='/dev/null' mode='w' encoding='UTF-8'>

    def create_default_link_for_sudachidict_core(output):
        try:
            dict_path = Path(import_module('sudachidict').__file__).parent
        except ImportError:
            try:
                import_module('sudachidict_core')
            except ImportError:
                raise KeyError('You need to specify `systemDict` in the config when `sudachidict_core` is not installed.')
            try:
                import_module('sudachidict_full')
                raise KeyError('Multiple dictionaries installed. Set the default with `link -t` command.')
            except ImportError:
                pass
            try:
                import_module('sudachidict_small')
>               raise KeyError('Multiple dictionaries installed. Set the default with `link -t` command.')
E               KeyError: 'Multiple dictionaries installed. Set the default with `link -t` command.'

venv/lib/python3.7/site-packages/sudachipy/config.py:69: KeyError
==================== 1 failed, 166 passed in 47.28 seconds =========
```

## Your Environment

* Operating System: Ubuntu 18.04.5 LTS
* Python Version Used: 3.7.3 (circleci/python:3.7.3-stretch)
* spaCy Version Used: 3.0.3
* Environment Information: CircleCI (Docker Medium)

**Comment by adrianeboyd** [comment]
Let me make sure I understand the problem: you installed `sudachidict_small` previously and then `spacy[ja]` installs `sudachidict_core` in addition, leading to this error?

Running `pip install spacy spacy[ja]` in a new venv does not lead to any conflicts because it only installs `sudachidict_core`, right?

If you want to use `sudachidict_small` instead, I think this is something you'll have to manage separately in your project requirements rather than using `spacy[ja]`. You can have requirements like this:

```none
spacy>=3.0.0
sudachipy>=0.4.9
sudachidict_small
```

And then I think you'll still have set things up to run the linking part (`sudachipy link -t small`) separately.

I can't immediately replicate the failure when both are installed, so I couldn't really test it, though. The spaCy Japanese support has been developed using `core` and some unit tests fail with with `small`, so I would also expect the `ja_core_*` pipelines to see degraded performance with `small` instead of `core`.

If you're training a new model from scratch, you can certainly use `small` instead of `core`. You can have `sudachidict_small` as the model requirement instead by adding it to the `requirements` in the model `meta.json`.

**Comment by bittlingmayer** [comment]
To be clear, as far as I know, we do not install `sudachidict_small`.  It could be that some other dependency does.

So all we do is `pip install spacy spacy[ja]` (i.e. `spacy` and `spacy[ja]` are in the requirements.txt) in CircleCI (i.e. a relatively clean environment).

For now, we don't have the bandwidth to investigate this one more given the languages we cover and our use of spaCy (sentence segmentation), we just removed `spacy[ja]` and user `xx` for Japanese which works for our purposes.

**Comment by adrianeboyd** [comment]
I'm surprised that `xx` sentence segmentation would work at all for Japanese, but maybe enough of the punctuation symbols are split off for some degree of sentence segmentation to work.

In any case, we don't have any good mechanism to manage or inspect dependencies from other projects and how they might conflict with our dependencies, so there aren't any better options on our end for `spacy[ja]` right now.

**Comment by bittlingmayer** [comment]
`。`, `！`,  `．` and `？` are in the Sentencizer punct char defaults.

**Comment by adrianeboyd** [comment]
They're in the `punct_char` defaults, but the sentencizer only works if they're separate tokens, so the following doesn't work because the internal punctuation is not split into separate tokens by the `xx` tokenizer:

```python
import spacy
nlp = spacy.blank("xx")
nlp.add_pipe("sentencizer")
doc = nlp("舗。舗！舗？") # nonsense text for demonstration
assert [t.text for t in doc] == ['舗。舗！舗', '？']
assert [sent.text for sent in doc.sents] == ['舗。舗！舗？']
```
