### ISSUE TITLE
Various errors when using n_threads=-1 with Language.pipe()

### ISSUE THREAD

**Issue by rappdw** [explosion/spaCy#720]
With n_threads=-1, pipe() results in either a 

"libgomp: Thread creation failed: Resource temporarily unavailable" 

or 

"Segmentation fault"

## Your Environment

Debian 8.6
Python 3.5.2
Spacy 1.5.0

**Comment by honnibal** [comment]
Thanks. This will be difficult =/

Does it work with say, n_threads=6?

**Comment by rappdw** [comment]
Yes, it works if n_threads are not specified (using default of 2). It also works with n_threads set to a positive integer (although I've only tried several options here). 

If it helps I could point to a docker image that demonstrates the issue...

**Comment by honnibal** [comment]
This issue occurs because the `initialize_state` method is allowed to add classes to the transition-system --- so threads are modifying shared state. I think it's fixed already, but I need to do some further checking to make sure.
