### ISSUE TITLE
Spacy to be used on Embedded platforms

### ISSUE THREAD

**Issue by getsiddd** [explosion/spaCy#721]
Can Spacy be used on embedded platforms like raspberry pie or beagle bone, etc. as it consumes much RAM, So i think not so what are other alternatives in which we can used spacy on these platforms?

**Comment by honnibal** [comment]
How much ram does a raspberry pie have?

**Comment by kootenpv** [comment]
@honnibal What is known about spaCy 2.0 :O?

**Comment by ines** [comment]
@kootenpv You can check out the [project board](https://github.com/explosion/spaCy/projects/3) for an overview of the work in progress. We're actually pretty close to a first pre-release! 😃

**Comment by mattmacy** [comment]
@ines I think you can safely dup this issue to #730 - As well as note that a fix is coming shortly.

**Comment by mattmacy** [comment]
@getsiddd see #788 - it doesn't address the size, but it will help with memory usage

**Comment by ohenepee** [comment]
Have anyone tried this? And what is the current average RAM usage?
