### ISSUE TITLE
v3 KnowledgeBase get_candidates method is missing

### ISSUE THREAD

**Issue by walkertuesday** [explosion/spaCy#7210]
## How to reproduce the behaviour
import spacy
from spacy.kb import KnowledgeBase
nlp = spacy.load("en_core_web_sm")
new_kb = KnowledgeBase(vocab=nlp.vocab, entity_vector_length=96)
new_kb.get_candidates("anything")

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-e01b6ede4f09> in <module>
      3 nlp = spacy.load("en_core_web_sm")
      4 new_kb = KnowledgeBase(vocab=nlp.vocab, entity_vector_length=96)
----> 5 new_kb.get_candidates("anything")

AttributeError: 'spacy.kb.KnowledgeBase' object has no attribute 'get_candidates'

## Your Environment
- **spaCy version:** 3.0.3
- **Platform:** `Linux-4.14.219-161.340.amzn2.x86_64-x86_64-with-debian-stretch-sid`
- **Python version:** 3.6.13
- **Pipelines:** en_core_web_sm (3.0.0)

I couldn't find anything mentioning get_candidates in the migration or backward incompatibilities docs.

**Comment by svlandeg** [comment]
Ah, you're right, you should now import `get_candidates` from `spacy.kb` and call `get_candidates(kb, span)` instead.

I'll update the docs & migration overview. Thanks for the report!

**Comment by walkertuesday** [comment]
Great!  It is working with kb.get_alias_candidates.  Glad it's just a migration and documentation issue and thanks for the quick reply.
