### ISSUE TITLE
Instantiate Spacy object  only once in apache mod_wsgi environment 

### ISSUE THREAD

**Issue by uday553** [explosion/spaCy#722]
```python

# **myapp.py**

# ----  import statements ---

parser = None
app = Flask(_ _name_ _)

@app.route('/xxxxxx/yyy')
def markDealStatud():
    text = 'matthew honnibal created spacy library'
    parsedData = parser(text.decode("utf-8"))
    xxxxxxxxxxxxx
    xxxxxxxxxxx
    xxxxxxxxxx
    xxxxxxxxxxxx


def initSpacy():
    global parser
    parser = English()

if __name__ == '__main__':
    initSpacy()
    app.run()​

if __name__ == 'myapp':
    initSpacy()
```

when i run this app in development mode, __main__ will execute and it will instantiate spacy only once and i will use that.

For production we are using apache server mod_wsgi configuration. similarly i want to instantiate it once(myapp) and use the same obj. 
In my configuration it is instantiating for each request. Suggest some solution plz. 

##  Environment

* **Operating System:**  Linux
* **Python Version Used:**  2.7
* **Environment Information:** apache mod_wsgi deployment

**Comment by honnibal** [comment]
> For production we are using apache server mod_wsgi configuration. similarly i want to instantiate it once(myapp) and use the same obj. In my configuration it is instantiating for each request. Suggest some solution plz. Suggest some solution plz.

This is a general question about usage of `mod_wsgi`. The answer will be the same no matter what code you were trying to execute. It's therefore out of our scope.
