### ISSUE TITLE
SpaCy error on create_pipe() , add_pipe() 

### ISSUE THREAD

**Issue by maroofih** [explosion/spaCy#7232]
I am pretty new with SpaCy. Trying to run these codes:
#Import the requisite library
import spacy

nlp = spacy.load("en_core_web_sm")
text = "Treblinka is a small village in Poland. Treblinka was also an extermination camp."
ruler = nlp.create_pipe("entity_ruler")
patterns = [
                {"label": "GPE", "pattern": "Treblinka"}
            ]
ruler.add_patterns(patterns)
nlp.add_pipe(ruler)
doc = nlp(text)
for ent in doc.ents:
    print (ent.text, ent.label_)

 encountered this error:

ValueError: [E966] `nlp.add_pipe` now takes the string name of the registered component factory, not a callable component. Expected string, but got <spacy.pipeline.entityruler.EntityRuler object at 0x000001DE843F4200> (name: 'None').

- If you created your component with `nlp.create_pipe('name')`: remove nlp.create_pipe and call `nlp.add_pipe('name')` instead.

- If you passed in a component like `TextCategorizer()`: call `nlp.add_pipe` with the string name instead, e.g. `nlp.add_pipe('textcat')`.

- If you're using a custom component: Add the decorator `@Language.component` (for function components) or `@Language.factory` (for class components / factories) to your custom component and assign it a name, e.g. `@Language.component('your_name')`. You can then run `nlp.add_pipe('your_name')` to add it to the pipeline.

Then updated the nlp.create_pipe("entity_ruler") with nlp_add_pipe("textcat") as suggested by error and get this new error:

AttributeError: 'TextCategorizer' object has no attribute 'add_patterns'

Do you have any idea what could be wrong?

spaCy version    3.0.3
Platform         Windows-10-10.0.19041-SP0
Python version   3.9.1
Pipelines        en_core_web_lg (3.0.0), en_core_web_md (3.0.0), en_core_web_sm (3.0.0)

**Comment by polm** [comment]
In the example in the error text `textcat` is a generic example, not an example specific to your usage. So if you you use `nlp.add_pipe("entity_ruler")` it should work.

For example:

```
import spacy

nlp = spacy.load("en_core_web_sm")
text = "Treblinka is a small village in Poland. Treblinka was also an extermination camp."
patterns = [
        {"label": "GPE", "pattern": "Treblinka"}
        ]
ruler = nlp.add_pipe('entity_ruler')
ruler.add_patterns(patterns)
doc = nlp(text)
for ent in doc.ents:
    print (ent.text, ent.label_)
```

Output:

```
Treblinka GPE
Poland GPE
Treblinka GPE
```

**Comment by maroofih** [comment]
Thanks for your response. I already had tried nlp.add_pipe("entity_ruler"), but encountered error. So, you basically removed nlp.add_pipe(ruler), so how is it supposed to add the ruler to the pipeline?

**Comment by polm** [comment]
So the old way to add components was this:

    xxx = nlp.create_pipe("XXX")
    nlp.add_pipe(xxx)

But in the new style, just one step creates the component, adds it to the pipeline, and returns it.

    xxx = nlp.add_pipe("XXX")

Because of this there's no need to pass the pipeline object back to the nlp object.

Does that clarify things? If not, could you paste your error output here? The example code I posted works for me.

**Comment by maroofih** [comment]
Just an update on this issue. Just figure that the codes actually work on SpaCy v2.2, in newer version 3 that was released recently there were changes that are affecting theses codes.

**Comment by maroofih** [comment]
I see. Thanks for your clear and complete explanation!
