### ISSUE TITLE
Add support to pass extra parameters in matcher.

### ISSUE THREAD

**Issue by Kavan72** [explosion/spaCy#7233]
Hi ! I need to match a pattern using matcher but it should also return other information i pass. If we have fexibillity of passing more than one parameters to matchers and get that data in return along with match string and start and end node, it would do my work.
for Eg. : 

```
import spacy
from spacy.matcher import Matcher

nlp = spacy.load("en_core_web_lg")
matcher = Matcher(nlp.vocab)

pattern = [{"LOWER": "Santa Inés", "extra": {"id": 5, ...}}]
matcher.add("COUNTRY", [pattern])

doc = nlp("i love Santa Ines.")
matches = matcher(doc)

matches will be like this :- [(4000319556510314152, 2, 3, {"id": 5, ...})]
```

Suppose for example with label "CITY" i match a city name, but ita not an ascii, still it matches and retrurns me with input string
and match string, but i want to get other details such as country name and state name as well.

## My Environment
- Operating System: ubuntu 20.04 LTS
- Python Version Used:  3.8.5
- spaCy Version Used: 3.0.3

**Comment by polm** [comment]
If you use the EntityRuler you can [add IDs to matches](https://spacy.io/usage/rule-based-matching#entityruler-ent-ids), and you could then use those IDs to look up information in another data structure. Would that work for your use case?

The docs have an example with city names:

```
from spacy.lang.en import English

nlp = English()
ruler = nlp.add_pipe("entity_ruler")
patterns = [{"label": "ORG", "pattern": "Apple", "id": "apple"},
            {"label": "GPE", "pattern": [{"LOWER": "san"}, {"LOWER": "francisco"}], "id": "san-francisco"},
            {"label": "GPE", "pattern": [{"LOWER": "san"}, {"LOWER": "fran"}], "id": "san-francisco"}]
ruler.add_patterns(patterns)

doc1 = nlp("Apple is opening its first big office in San Francisco.")
print([(ent.text, ent.label_, ent.ent_id_) for ent in doc1.ents])
```

**Comment by Kavan72** [comment]
@polm hey, sorry for late reply. It's working
