### ISSUE TITLE
Resume training from checkpoint

### ISSUE THREAD

**Issue by jzallen07** [explosion/spaCy#7241]
## How to reproduce the behaviour

Using Spacy 3. Train a model until a checkpoint is produced e.g. the model-best output. Seemingly no way to resume training from the produced checkpoint. I've tried using the `source` parameter in the config file and get an error saying that the path is not a package error. There is some documentation around resuming training in the PRE training method but nothing for the general training method and no apparent way to provide a path to the config file other than initializing a new NLP object to train from. 

## Your Environment

- **spaCy version:** 3.0.3
- **Platform:** Linux-5.3.0-1035-aws-x86_64-with-Ubuntu-18.04-bionic
- **Python version:** 3.6.9
- **Pipelines:** en_core_web_lg (3.0.0)

**Comment by adrianeboyd** [comment]
This is a good kind of question for our new discussion board, so I'll move it there in a second. You'll get an automatic message that this issue is locked, but the new thread will be open for discussion.
