### ISSUE TITLE
Error parsing config overrides - `nlp.tokenizer` sections does not exist

### ISSUE THREAD

**Issue by sztal** [explosion/spaCy#7254]
## How to reproduce the behaviour
Maybe this is not a bug, but just my error, but I could not find an example of loading `nlp` object based on a config by hand. 

The problem is  that the `nlp` object cannot be loaded using a default config file. It seems that a problem may be related to a weirdly formated `tokenizer` entry which at the moment when the error is raised looks like this in PDB:

```
'tokenizer': '{"@tokenizers":"spacy.Tokenizer.v1"}'
```
So it seems the key `tokenizer` is mapped to a string representation of a dict, which supposedly should define a subsection in which `spacy.Tokenizer.v1` is loaded from the registry.

### Error message
```
ConfigValidationError: 

Error parsing config overrides

nlp -> tokenizer -> @tokenizers   not a section value that can be overwritten
```

Error happens here:

```python
    346     def _set_overrides(self, config: "ConfigParser", overrides: Dict[str, Any]) -> None:
    347         """Set overrides in the ConfigParser before config is interpreted."""
    348         err_title = "Error parsing config overrides"
    349         for key, value in overrides.items():
    350             err_msg = "not a section value that can be overwritten"
    351             err = [{"loc": key.split("."), "msg": err_msg}]
    352             if "." not in key:
    353                 raise ConfigValidationError(errors=err, title=err_title)
    354             section, option = key.rsplit(".", 1)
    355             if section not in config or option not in config[section]:
--> 356                 raise ConfigValidationError(errors=err, title=err_title)
    357             config.set(section, option, try_dump_json(value, overrides))
```

### Reproduce
```bash
# TERMINAL
python -m spacy init config spacy.cfg
```

```python
# PYTHON
import spacy
config = spacy.util.load_config('./spacy.cfg')
nlp = spacy.load("en_core_web_sm", config=config)
```

## Environment
I use Python 3.9 and Spacy v3.0.3 installed in a Conda environment (but via PIP) on Ubuntu 20.04.02 LTS.

**Comment by adrianeboyd** [comment]
See: https://stackoverflow.com/a/66441287
