### ISSUE TITLE
ValueError: [E002] Can't find factory for 'relation_extractor' for language German (de). 

### ISSUE THREAD

**Issue by JRE-joe** [explosion/spaCy#7262]
I've come across the issue:
ValueError: [E002] Can't find factory for 'relation_extractor' for language German (de). This usually happens when spaCy calls `nlp.create_pipe` with a custom component name that's not registered on the current language class. If you're using a Transformer, make sure to install 'spacy-transformers'. If you're using a custom component, make sure you've added the decorator `@Language.component` (for function components) or `@Language.factory` (for class components).

I've added the Custom Component Relation_Extractor from the SpaCy Projects to my NER Pipline.

This is my .cfg-file:
```
[paths]
ner_train = ""
ner_dev = ""
ner_vectors = null

init_tok2vec = null

rel_train = ""
rel_dev = ""
rel_raw = null

[system]
gpu_allocator = null
ner_seed = 0
rel_seed = 342

[nlp]
lang = "de"
pipeline = ["tok2vec","ner","relation_extractor"]
batch_size = 1000
disabled = []
before_creation = null
after_creation = null
after_pipeline_creation = null
tokenizer = {"@tokenizers":"spacy.Tokenizer.v1"}

[components]

[components.tok2vec]
factory = "tok2vec"

[components.tok2vec.model]
@architectures = "spacy.Tok2Vec.v2"

[components.tok2vec.model.embed]
@architectures = "spacy.MultiHashEmbed.v1"
width = ${components.tok2vec.model.encode.width}
attrs = ["NORM", "PREFIX", "SUFFIX", "SHAPE"]
rows = [2000,1000,1000,1000]
include_static_vectors = false

[components.tok2vec.model.encode]
@architectures = "spacy.MaxoutWindowEncoder.v2"
width = 128
depth = 6       
window_size = 1
maxout_pieces = 3

[components.ner]
factory = "ner"
moves = null
update_with_oracle_cut_size = 100

[components.ner.model]
@architectures = "spacy.TransitionBasedParser.v2"
state_type = "ner"
extra_state_tokens = false
hidden_width = 64
maxout_pieces = 2
use_upper = true
nO = null

[components.ner.model.tok2vec]
@architectures = "spacy.Tok2VecListener.v1"
width = ${components.tok2vec.model.encode.width}
upstream = "*"

[components.relation_extractor]
factory = "relation_extractor"
threshold = 0.5

[components.relation_extractor.model]
@architectures = "rel_model.v1"

[components.relation_extractor.model.create_instance_tensor]
@architectures = "rel_instance_tensor.v1"

[components.relation_extractor.model.create_instance_tensor.tok2vec]
@architectures = "spacy.Tok2VecListener.v1"
width = ${components.tok2vec.model.encode.width}

[components.relation_extractor.model.create_instance_tensor.pooling]
@layers = "reduce_mean.v1"

[components.relation_extractor.model.create_instance_tensor.get_instances]
@misc = "rel_instance_generator.v1"
max_length = 100

[components.relation_extractor.model.classification_layer]
@architectures = "rel_classification_layer.v1"
nI = null
nO = null

[corpora]

[corpora.ner]

[corpora.ner.dev]
@readers = "spacy.Corpus.v1"
path = ${paths.ner_dev}
max_length = 0
gold_preproc = false
limit = 0
augmenter = null

[corpora.ner.train]
@readers = "spacy.Corpus.v1"
path = ${paths.ner_train}
max_length = 2000
gold_preproc = false
limit = 0
augmenter = null

[corpora.rel]

[corpora.rel.train]
@readers = "Gold_ents_Corpus.v1"
file = ${paths.rel_train}

[corpora.rel.dev]
@readers = "Gold_ents_Corpus.v1"
file = ${paths.rel_dev}

[training]

[training.ner]
dev_corpus = "corpora.ner.dev"
train_corpus = "corpora.ner.train"
seed = ${system.ner_seed}
gpu_allocator = ${system.gpu_allocator}
dropout = 0.1
accumulate_gradient = 1
patience = 1600
max_epochs = 0
max_steps = 20000
eval_frequency = 200
frozen_components = []
before_to_disk = null

[training.ner.batcher]
@batchers = "spacy.batch_by_words.v1"
discard_oversize = false
tolerance = 0.2
get_length = null

[training.ner.batcher.size]
@schedules = "compounding.v1"
start = 100
stop = 1000
compound = 1.001
t = 0.0

[training.ner.logger]
@loggers = "spacy.ConsoleLogger.v1"
progress_bar = false

[training.ner.optimizer]
@optimizers = "Adam.v1"
beta1 = 0.9
beta2 = 0.999
L2_is_weight_decay = true
L2 = 0.01
grad_clip = 1.0
use_averages = false
eps = 0.00000001
learn_rate = 0.001

[training.ner.score_weights]
ents_per_type = null
ents_f = 1.0
ents_p = 0.0
ents_r = 0.0

[training.rel]
seed = ${system.rel_seed}
gpu_allocator = ${system.gpu_allocator}
dropout = 0.1
accumulate_gradient = 1
patience = 1600000
max_epochs = 0
max_steps = 10000
eval_frequency = 500
frozen_components = []
dev_corpus = "corpora.rel.dev"
train_corpus = "corpora.rel.train"
before_to_disk = null
logger = {"@loggers":"spacy.ConsoleLogger.v1"}

[training.rel.batcher]
@batchers = "spacy.batch_by_words.v1"
discard_oversize = false
tolerance = 0.2

[training.rel.batcher.size]
@schedules = "compounding.v1"
start = 100
stop = 1000
compound = 1.001

[training.rel.optimizer]
@optimizers = "Adam.v1"
beta1 = 0.9
beta2 = 0.999
L2_is_weight_decay = true
L2 = 0.01
grad_clip = 1.0
use_averages = false
eps = 0.00000001
learn_rate = 0.001

[training.score_weights]
rel_micro_p = 0.0
rel_micro_r = 0.0
rel_micro_f = 1.0

[initialize]

[initialize.ner]
vectors = "de_core_news_lg"
init_tok2vec = ${paths.init_tok2vec}
vocab_data = null
lookups = null
before_init = null
after_init = null

[initialize.relation_extractor]

[initialize.components]

[initialize.tokenizer]
```

And the Relation Extraction Component is from https://github.com/explosion/projects/tree/v3/tutorials/rel_component
I can't manage to find a reasonable solution to my issue.

**Comment by adrianeboyd** [comment]
Have you included the code that defines this component using the `--code` argument with your `spacy train` command?

See how it's included with `-c` (short for `--code`) in the linked project:

https://github.com/explosion/projects/blob/fdd9823599d7c298d2bc824f2e67b2a5fe904e99/tutorials/rel_component/project.yml#L53

**Comment by JRE-joe** [comment]
The Code for the custom_functions.py is included in the SpaCy train command.

**Comment by svlandeg** [comment]
Can you provide the full console output, which command you're running and the full traceback of the error?

**Comment by JRE-joe** [comment]
So first i run "spacy project run all" and this error message pops up:
=========================== Initializing pipeline ===========================
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/joe/Desktop/nlp/.env/lib/python3.7/site-packages/spacy/__main__.py", line 4, in <module>
    setup_cli()
  File "/Users/joe/Desktop/nlp/.env/lib/python3.7/site-packages/spacy/cli/_util.py", line 68, in setup_cli
    command(prog_name=COMMAND)
  File "/Users/joe/Desktop/nlp/.env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/joe/Desktop/nlp/.env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/joe/Desktop/nlp/.env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/joe/Desktop/nlp/.env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/joe/Desktop/nlp/.env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/joe/Desktop/nlp/.env/lib/python3.7/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/joe/Desktop/nlp/.env/lib/python3.7/site-packages/spacy/cli/train.py", line 56, in train_cli
    nlp = init_nlp(config, use_gpu=use_gpu)
  File "/Users/joe/Desktop/nlp/.env/lib/python3.7/site-packages/spacy/training/initialize.py", line 28, in init_nlp
    raise ValueError(Errors.E1015.format(value="[training] seed"))
ValueError: [E1015] Can't initialize model from config: no [training] seed found. For more information, run: python -m spacy debug config config.cfg

Then i run "spacy debug config ./configs/tok2vec.cfg" and this error shows on the console:

============================= Config validation =============================
Traceback (most recent call last):
  File "/Users/johanneseiler/Desktop/nlp/.env/bin/spacy", line 8, in <module>
    sys.exit(app())
  File "/Users/joe/Desktop/nlp/.env/lib/python3.7/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/joe/Desktop/nlp/.env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/joe/Desktop/nlp/.env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/joe/Desktop/nlp/.env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/joe/Desktop/nlp/.env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/joe/Desktop/nlp/.env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/joe/Desktop/nlp/.env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/joe/Desktop/nlp/.env/lib/python3.7/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/joe/Desktop/nlp/.env/lib/python3.7/site-packages/spacy/cli/debug_config.py", line 42, in debug_config_cli
    config_path, overrides=overrides, show_funcs=show_funcs, show_vars=show_vars
  File "/Users/joe/Desktop/nlp/.env/lib/python3.7/site-packages/spacy/cli/debug_config.py", line 56, in debug_config
    nlp = util.load_model_from_config(config)
  File "/Users/joe/Desktop/nlp/.env/lib/python3.7/site-packages/spacy/util.py", line 432, in load_model_from_config
    validate=validate,
  File "/Users/joe/Desktop/nlp/.env/lib/python3.7/site-packages/spacy/language.py", line 1655, in from_config
    raw_config=raw_config,
  File "/Users/joe/Desktop/nlp/.env/lib/python3.7/site-packages/spacy/language.py", line 772, in add_pipe
    validate=validate,
  File "/Users/joe/Desktop/nlp/.env/lib/python3.7/site-packages/spacy/language.py", line 638, in create_pipe
    raise ValueError(err)
ValueError: [E002] Can't find factory for 'relation_extractor' for language German (de). This usually happens when spaCy calls `nlp.create_pipe` with a custom component name that's not registered on the current language class. If you're using a Transformer, make sure to install 'spacy-transformers'. If you're using a custom component, make sure you've added the decorator `@Language.component` (for function components) or `@Language.factory` (for class components).

Available factories: attribute_ruler, tok2vec, merge_noun_chunks, merge_entities, merge_subtokens, token_splitter, parser, beam_parser, entity_linker, ner, beam_ner, entity_ruler, lemmatizer, tagger, morphologizer, senter, sentencizer, textcat, textcat_multilabel, transformer

**Comment by svlandeg** [comment]
Ah, that makes sense. You actually have to add the same `--code` flag to the `debug` command: https://spacy.io/api/cli#debug.

**Comment by JRE-joe** [comment]
I desperatly can't  manage to fix my issue, even though with this help. Can you please provide further insights and explanations to this ?

**Comment by svlandeg** [comment]
Sure! So you said,

> Then i run "spacy debug config ./configs/tok2vec.cfg" and this error shows on the console:
> (...)
> ValueError: [E002] Can't find factory for 'relation_extractor'

What this means is that the `debug config` command starts running, but then errors because it doesn't know the `relation_extractor`, because that's not a built-in function from spaCy. You need to tell the `debug config` command where to find this function, and this is what the `--code` or `-c` part is for. It's used in a similar way as for the `train` command. So in your `yml` file you've got (filling in the variables):
```
python -m spacy train configs/rel_tok2vec.cfg --output training --paths.rel_train data/train.rel.spacy --paths.rel_dev data/dev.rel.spacy -c ./scripts/rel_custom_functions.py
```
But you said that this resulted in errors. So, to better understand what is wrong with the config file, you can run `debug config` but you have to give it all the same parameters as you would in your `train` command:
```
python -m spacy debug config ./configs/rel_tok2vec.cfg --output training --paths.rel_train data/train.rel.spacy --paths.rel_dev data/dev.rel.spacy -c ./scripts/rel_custom_functions.py
```
I also noticed that your project has two config files, but I assume the NER config `configs/tok2vec.cfg` doesn't actually refer to the `relation_extractor`, right?

**Comment by adrianeboyd** [comment]
Looking again at the config above, I think part of the problem is the subsections like `corpora.ner`, `training.ner`, and `initialize.ner` that aren't supported by the config schema. The config should define one training pipeline with corpora/initialize/training settings for the whole pipeline at once. Depending on your setup, you may need two separate configs for two separate pipelines, where the second config uses `source` to include a component from the first trained pipeline.

**Comment by JRE-joe** [comment]
Thank you for the background information.

>I also noticed that your project has two config files, but I assume the NER config configs/tok2vec.cfg doesn't actually refer to the relation_extractor, right? `

This `rel_tok2vec.cfg` points to the same config the NER uses. So i've changed it to the same variable.

> What this means is that the debug config command starts running, but then errors because it doesn't know the relation_extractor, because that's not a built-in function from spaCy. You need to tell the debug config command where to find this function, and this is what the --code or -c part is for. It's used in a similar way as for the train command. So in your yml file you've got (filling in the variables)`

Debugging with `spacy debug config configs/tok2vec.cfg -c ./scripts/rel_custom_functions.py` shows the following:

`✘ Couldn't load Python code: scripts/rel_custom_functions.py
No module named 'scripts' `

spaCy can't find the module `scripts ` so it can't import the `make_relation_extractor` from scripts.rel_pipe. Therefore the factory doesn't works. Even tough the paths are correct and a `__init__.py` file is in the scripts folder.

It's confusion, because in the original `rel_component` from your tutorial has the same directory structure as my new pipeline project.

**Comment by svlandeg** [comment]
Hm, I'm not sure what the issue could be. On my Windows machine, when in the `rel_component` folder of the original project, I can run 
```
python -m spacy train configs/rel_trf.cfg --output temp_training --paths.train data/train.spacy --paths.dev data/dev.spacy -c ./scripts/custom_functions.py
```
and I can run
```
python -m spacy debug config configs/rel_trf.cfg --paths.train data/train.spacy --paths.dev data/dev.spacy -c ./scripts/custom_functions.py
```
and both seem to find the `custom_functions.py` file just fine - but ofcourse it depends on how your system & directory structure is set up.

**Comment by svlandeg** [comment]
FYI - I'm going to move this to the discussion board as it's really more suited for that. Don't worry if you get an email that says this is closed - we'll be able to just continue the discussion over there, and it should automatically forward you as well.
