### ISSUE TITLE
✘ No compatible package found for 'en_trf_bertbaseuncased_lg' (spaCy v3.0.3)

### ISSUE THREAD

**Issue by baixiaofanya123** [explosion/spaCy#7269]
### How to reproduce the problem

Upgrade spacy to 3.0.3 and run the command to download a model:

```python -m spacy download en_trf_bertbaseuncased_lg```

results in an error:

```✘ No compatible model found for 'en_trf_bertbaseuncased_lg' (spaCy v3.0.3).```

### Your Environment

Operating System: MacOS
Python Version Used: 3.7.3
spaCy Version Used: 3.0.3

**Comment by polm** [comment]
The `en_trf_bertbaseuncased_lg` model was for spacy-transformers in spaCy v2 - in spaCy v3 the English transformers model is [en_core_web_trf](https://spacy.io/models/en#en_core_web_trf). You can install it like this:

    python -m spacy download en_core_web_trf

**Comment by baixiaofanya123** [comment]
Thank you for the response! So I dowloaded the model, but when I tried to load it, it shows me the following:

**Comment by baixiaofanya123** [comment]
It works! Thanks, is there a tutorial for how to train a text classifier model using transformer in the new release?

**Comment by polm** [comment]
Yes, you can choose the GPU and textcat options in the Quickstart here:

https://spacy.io/usage/training#quickstart

**Comment by baixiaofanya123** [comment]
Thank you, it works! One last question, if I want to construct training data for the textcat classifier, do I need to change data to json format first and then using ```convert```command to change it to the ```.spacy``` file?

**Comment by adrianeboyd** [comment]
No, the JSON format is overkill for textcat annotation. Here's a sketch of how to construct the training data from a list of `(text, cats)` tuples:

```
import spacy
from spacy.tokens import DocBin
nlp = spacy.blank("en")
db = DocBin()
for text, cats in data:
    doc = nlp.make_doc(text)
    doc.cats = cats
    db.add(doc)
db.to_disk("train.spacy")
```
