### ISSUE TITLE
spacy train E930 & E923

### ISSUE THREAD

**Issue by karmalegend** [explosion/spaCy#7276]
## Which page or section is this issue related to?
https://spacy.io/usage/training#basics

```python -m spacy train config.cfg --output ./output --paths.train ./train.spacy --paths.dev ./dev.spacy```

I'm at an absolute loss i've been trying to get spacy to train on NER for 2 days now and i just can't seem to get it to run.

I've follow every step in the documentation, i had an old trainingdata format that i supposedly converted using

```python -m spacy convert ./training.json ./output```

now my config looks as follows:

```
[paths]
train = output/
dev = output/
vectors = null
init_tok2vec = null

[system]
gpu_allocator = "pytorch"
seed = 0

[nlp]
lang = "nl"
pipeline = ["transformer","ner"]
batch_size = 128
disabled = []
before_creation = null
after_creation = null
after_pipeline_creation = null
tokenizer = {"@tokenizers":"spacy.Tokenizer.v1"}

[components]

[components.ner]
factory = "ner"
moves = null
update_with_oracle_cut_size = 100

[components.ner.model]
@architectures = "spacy.TransitionBasedParser.v2"
state_type = "ner"
extra_state_tokens = false
hidden_width = 64
maxout_pieces = 2
use_upper = false
nO = null

[components.ner.model.tok2vec]
@architectures = "spacy-transformers.TransformerListener.v1"
grad_factor = 1.0
pooling = {"@layers":"reduce_mean.v1"}
upstream = "*"

[components.transformer]
factory = "transformer"
max_batch_items = 4096
set_extra_annotations = {"@annotation_setters":"spacy-transformers.null_annotation_setter.v1"}

[components.transformer.model]
@architectures = "spacy-transformers.TransformerModel.v1"
name = "GroNLP/bert-base-dutch-cased"

[components.transformer.model.get_spans]
@span_getters = "spacy-transformers.strided_spans.v1"
window = 128
stride = 96

[components.transformer.model.tokenizer_config]
use_fast = true

[corpora]

[corpora.dev]
@readers = "spacy.Corpus.v1"
path = ${paths.dev}
max_length = 0
gold_preproc = false
limit = 0
augmenter = null

[corpora.train]
@readers = "spacy.Corpus.v1"
path = ${paths.train}
max_length = 500
gold_preproc = false
limit = 0
augmenter = null

[training]
accumulate_gradient = 3
dev_corpus = "corpora.dev"
train_corpus = "corpora.train"
seed = ${system.seed}
gpu_allocator = ${system.gpu_allocator}
dropout = 0.1
patience = 1600
max_epochs = 0
max_steps = 20000
eval_frequency = 200
frozen_components = []
before_to_disk = null

[training.batcher]
@batchers = "spacy.batch_by_padded.v1"
discard_oversize = true
size = 2000
buffer = 256
get_length = null

[training.logger]
@loggers = "spacy.ConsoleLogger.v1"
progress_bar = false

[training.optimizer]
@optimizers = "Adam.v1"
beta1 = 0.9
beta2 = 0.999
L2_is_weight_decay = true
L2 = 0.01
grad_clip = 1.0
use_averages = false
eps = 0.00000001

[training.optimizer.learn_rate]
@schedules = "warmup_linear.v1"
warmup_steps = 250
total_steps = 20000
initial_rate = 0.00005

[training.score_weights]
ents_per_type = null
ents_f = 1.0
ents_p = 0.0
ents_r = 0.0

[pretraining]

[initialize]
vectors = null
init_tok2vec = ${paths.init_tok2vec}
vocab_data = null
lookups = null
before_init = null
after_init = null

[initialize.components]

[initialize.tokenizer]
```

As boilerplate as one can get however running
```python -m spacy train config.cfg --output ./output --gpu-id 0```

Results in : 

```AssertionError: [E923] It looks like there is no proper sample data to initialize the Model of component 'ner'. To check your input data paths and annotation, run: python -m spacy debug data config.cfg```

My training data looks like:

```
[
    [
        "long string.",
        {
            "entities": [
                [
                    173,
                    176,
                    "surface"
                ],
                [
                    527,
                    528,
                    "bedrooms"
                ]
            ]
        }
    ],
    [
        "long string.",
        {
            "entities": [
                [
                    99,
                    102,
                    "surface"
                ],
                [
                    625,
                    626,
                    "bedrooms"
                ]
            ]
        }
    ],
```

before converting ofcourse and ```python -m spacy debug data config.cfg``` results in:

```TypeError: [E930] Received invalid get_examples callback in `Transformer.initialize`. Expected function that returns an iterable of Example objects but got: []```

I genuinely don't know what to try anymore been looking through the docs for ages. I'm not sure if this is even the right place to ask, but i'd really appreciate any instructions.

**Comment by adrianeboyd** [comment]
That's not the JSON format that `spacy convert` can convert, so it's possible your train/dev corpora are empty. (The only JSON format the converter can convert is the v2 JSON training format: https://v2.spacy.io/api/annotation#training)

Try loading the `.spacy` files directly to inspect the docs and NER annotation:

```python
import spacy
from spacy.tokens import DocBin

nlp = spacy.blank("en")
db = DocBin().from_disk("train.spacy")
docs = list(db.get_docs(nlp.vocab))
for doc in db.get_docs(nlp.vocab):
    print(doc.text, doc.ents)
    # or
    spacy.displacy.serve(doc, style="ent")
```

We do have a demo `spacy project` proejct in progress that is similar to the old `train_ner.py` script and that shows how to convert from the old demo `TRAIN_DATA` format. You can see a draft of the conversion script here: https://github.com/explosion/projects/pull/38/files#diff-f20ffa19cedd7c97ab89c0eb96c654e57d886be1c67426ee94aa5dbb189801e4R1

**Comment by adrianeboyd** [comment]
And let me convert this to a discussion thread on the new discussions board. This issue will get locked but the new thread will be open there.
