### ISSUE TITLE
Deserialization fails based on whether "nlp" object was used yet

### ISSUE THREAD

**Issue by brendano** [explosion/spaCy#728]
When I try to deserialize using a fresh `nlp` object, spaCy crashes, though it manages to deserialize fine if it's the same `nlp` object that was used to originally parse the text.  I can't tell if I'm using the library in a way it's not intended to be used, or if this is a bug?
(This is spaCy version 1.5.0 on Linux with Python 2.7)

```
from spacy.tokens.doc import Doc
import spacy
nlp = spacy.load("en")
text = u"Hello world."

# Parse it. Works.
doc = nlp(text)
print len(set([o for o in doc]))

# Save a serialized copy
with open("out",'w') as f:
    f.write(str(doc.to_bytes()))

# Deserialize: works
doc2 = Doc(nlp.vocab)
doc2.from_bytes(open("out").read())
print len(set([o for o in doc2]))

# Deserialize with a fresh nlp object: crashes
nlp = spacy.load("en")
doc3 = Doc(nlp.vocab)
doc3.from_bytes(open("out").read())
print len(set([o for o in doc3]))
```

**Comment by brendano** [comment]
FYI: it seems to work fine with version 0.101.0.

**Comment by honnibal** [comment]
Thanks for the report. For the record: Segmentation Fault is never expected behaviour :). So every time you get an outright crash without a Python traceback, that's *always* a bug, and we appreciate you bringing it to our attention.

I'll add an (xfail) test for this now and put it on the queue.

**Comment by ines** [comment]
I was just about to add the regression test for this issue, but I'm having trouble reproducing the error. It works fine for me (spaCy 1.5.0). I also tried restarting the interpreter: 

```bash
>>> from spacy.tokens.doc import Doc
>>> import spacy
>>> nlp = spacy.load("en")
>>> doc = Doc(nlp.vocab)
>>> doc.from_bytes(open("out").read())
Hello world.
```

Maybe double-check that you have the model installed correctly? If not, this might explain what's going on here: everything works fine in the first two steps, since you have the `vocab` information from the parsed text – but if you start with an empty vocabulary, it doesn't know how to decode the strings. What do you get for `len(nlp.vocab)`?

**Comment by brendano** [comment]
Oh now it works!  I reinstalled the model and now it has both these two directories in spacy/data:

```
en-1.1.0
en_glove_cc_300_1m_vectors-1.0.0
```

Before, it only had `en-1.1.0` after I installed the model.

**Comment by brendano** [comment]
Well... I have no idea why the model was installed wrong in the first place.  I thought I did a new install of it yesterday when trying to get it to work.  Not sure.

**Comment by ines** [comment]
Oh, I misread your comment then. This is indeed weird – there's always a chance it might have been a `PYTHONPATH` mixup, but if this happens again, please open an issue with more info so we can investigate.
