### ISSUE TITLE
Documentation does not specify dependency label schemes

### ISSUE THREAD

**Issue by GillesJ** [explosion/spaCy#7280]
I have trouble finding the specific part-of-speech and dependency label schemes used by Spacy 3.0 models in the documentation site.

The old link https://spacy.io/api/annotation#dependency-parsing-english redirects to https://spacy.io/api/data-formats#dependency-parsing-english which does not specify this information, neither can it be found with the search function.

An old [StackOverflow answer](https://stackoverflow.com/questions/40288323/what-do-spacys-part-of-speech-and-dependency-tags-mean) suggests the following links but the docs do not contain the full spec any longer:
- https://spacy.io/api/annotation#pos-tagging
- https://spacy.io/api/annotation#dependency-parsing-english
- https://spacy.io/api/data-formats#dependency-parsing-german 
- https://spacy.io/api/data-formats#dependency-parsing-universal

Neither do the English, German and other (universal) model pages link the label specification.
- https://spacy.io/models/de
- https://spacy.io/models/en

https://spacy.io/usage/linguistic-features#pos-tagging does state UPOS is used in the right sidebar, but in a textbox readers are refered to the model pages.

I vaguely recall there being 3 dependency schemes used: 
- English: [CLEAR dependencies](https://github.com/clir/clearnlp-guidelines/blob/master/md/specifications/dependency_labels.md) as used in Ontonotes 5.0 which differ slightly from [Choi's guidelines (2012)](http://www.mathcs.emory.edu/~choi/doc/cu-2012-choi.pdf).
- German: [Tiger Treebank](https://www.ims.uni-stuttgart.de/en/research/resources/corpora/tiger) (exact version unknown)
- All other: Universal dependencies (UD) (exact version)
I also recall all models using simplified [Universal Dependencies v2 POS tag set](https://universaldependencies.org/v2/postags.html).

Is this still correct? I remember there was an intention to switch to Universal Dependencies across all models.

The model pages do link the data source, but this poses issues of resource description availability and an arduous lookup.
For example for English, the data source states Ontonotes 5.0 but the only readily available information on OntoNotes 5.0 is [the LDC page](https://catalog.ldc.upenn.edu/LDC2013T19) which does not specify the dependency label scheme.

Given that there is considerable overlap in label names between [Universal Dependencies](https://universaldependencies.org/u/dep/), [Stanford Typed Dependencies
](https://nlp.stanford.edu/software/dependencies_manual.pdf), and [CLEAR](https://www.mathcs.emory.edu/~choi/doc/cu-2012-choi.pdf), it would be prudent to link each model to each label scheme specification.

**Comment by adrianeboyd** [comment]
See: https://github.com/explosion/spaCy/discussions/7181. This info will mostly likely get moved to the models pages under https://spacy.io/models after the next model release.
