### ISSUE TITLE
No way to extract Attention from my transformer?

### ISSUE THREAD

**Issue by KennethEnevoldsen** [explosion/spaCy#7283]
After digging for a couple of hours on documentation on thinc, spacy, and spacy-transformers it seems that it is not possible to extract the attention weights from the huggingface transformer model?

Examining the transformerdata [documentation](https://spacy.io/api/transformer#transformerdata) it seems that this should be doable from the *"Generally activations that are 2-dimensional will be attention weights. Details of this variable will differ depending on the underlying transformer model."*

Am I missing something?

For convenience this code here makes a forward pass and nothing else using an HF transformer:
```python
nlp = spacy.blank("en")

# Construction via add_pipe with custom config
config = {
    "model": {
        "@architectures": "spacy-transformers.TransformerModel.v1",
        "name": "bert-base-uncased",
        "tokenizer_config": {"use_fast": True}
    }
}
transformer = nlp.add_pipe(
    "transformer", config=config)
transformer.model.initialize()

doc = nlp("This is a sentence.")
doc._.trf_data.tensors[0].shape # (1, 7, 768) <-- wordpiece embedding
doc._.trf_data.tensors[1].shape  # (1, 768) <-- assuming this is the pooled embedding? At least I don't believe it is the attention as (maybe) suggested in the documentation
```

I do get that one rarely wants to extract attention, but it might be relevant for e.g. XAI applications, thus it could e.g. be turned on using the config:
```
config = {
    "model": {
        "@architectures": "spacy-transformers.TransformerModel.v1",
        "name": "bert-base-uncased",
        "transformer_config": {"output_attentions": True}  
        "tokenizer_config": {"use_fast": True}
    }
}
```

I would love to contribute to this if it is not implemented yet, I assume one would change the current `_convert_transformer_outputs` - probably further back as well to make sure the attention matrix is saved.

## Info about spaCy

- **spaCy version:** 3.0.3
- **Platform:** macOS-10.15.7-x86_64-i386-64bit
- **Python version:** 3.8.8
- **Pipelines:** da_core_news_sm (3.0.0), en_core_web_sm (3.0.0)

**Comment by honnibal** [comment]
Hi @KennethEnevoldsen ,

You want the attention matrix for that batch right, not the weights from the model? I think you need to get `output_attentions=True` set onto the transformer model. It looks like we're missing an option here: we have a configuration parameter that we pass through to the tokenizer, but there's no equivalent configuration for the transformer.

Here's a quick hack that should work in the meantime:

```python

trf_component = nlp.get_pipe("transformer")
for node in trf_component.model.walk():
    if node.attrs.get("has_transformer"):
        # Here we're iterating over the model, to find the PyTorchWrapper layer that holds
        # the transformer. We're assuming that the transformer has already been loaded.
        # If it hasn't been loaded yet, we could replace the set_transformer function of the node instead.
        wrapper = node.layers[0]
        wrapper.attrs["convert_inputs"] = add_cfg(wrapper.attrs["convert_inputs"], {"output_attentions": True})


def add_cfg(converter: Callable, config: Dict) -> Callable:
    """Wrap a conversion function, injecting the config into the 'args kwargs' object. The ArgsKwargs
    will be passed into the pytorch model as *ak.args, **ak.kwargs. So we want to update the kwargs.
    This function returns a function that acts as the converter.
    """
    def convert_with_cfg(model: Model, X: Any, is_train: bool) -> Tuple[ArgsKwargs, Callable]:
        Y, backprop = model(X, is_train)
        Y.kwargs.update(config)
        return Y, backprop
    return convert_with_cfg
```

I would welcome a PR that adds the option to pass extra arguments into the HF transformer.

**Comment by KennethEnevoldsen** [comment]
Thank you for this, this is exactly what I was looking for. I will work on a PR tomorrow.

PS: As this looks kinda like something I experimented with it seems to not handle the output (as the output wrapper function does not extract the attention)

**Comment by KennethEnevoldsen** [comment]
Just to finish the thread I have added a pull request here which solves the issue: https://github.com/explosion/spacy-transformers/pull/268

**Comment by polm** [comment]
Since the relevant PR was merged I'm going to go ahead and close this. Thanks for the PR!
