### ISSUE TITLE
Lexeme probs not defined in en_core_web_lg and de_core_news_lg

### ISSUE THREAD

**Issue by ilijaplusx** [explosion/spaCy#7290]
## How to reproduce the behaviour
```python
import spacy

nlp = spacy.load("en_core_web_lg")
most_common_words = ["the", "be", "to", "of", "and"]
print([nlp.vocab[w].prob for w in most_common_words])
# [-20.0, -20.0, -20.0, -20.0, -20.0]
```

I've tried this for `en_core_web_lg`, `en_core_web_md` and `de_core_news_lg`, all of them with the same undefined `prob`.

## Your Environment
* Operating System: Ubuntu 18.04
* Python Version: 3.8.8
* spaCy Version: 3.0.3
* Environment Information: JupyterLab 3.0.7
* Model versions: 3.0.0

**Comment by adrianeboyd** [comment]
See: https://github.com/explosion/spaCy/discussions/6388#discussioncomment-330606

**Comment by ilijaplusx** [comment]
Thanks @adrianeboyd the referenced comment did the work!

Follow up - is this mentioned somewhere in the docs that I missed? If not, maybe it can be added in?

**Comment by adrianeboyd** [comment]
Yeah, it's something that should at least be added to the v3 migration guide.

**Comment by ilijaplusx** [comment]
Super :) Thanks for the answers. I can than leave this issue open so you can track that?
