### ISSUE TITLE
Spacy English parser takes > 35 seconds to load in (0.101 -or- 1.5).  Crashes in 1.5 with...

### ISSUE THREAD

**Issue by enjoysmath** [explosion/spaCy#730]
Any way to use 0.101.0 and speed up load time, or fix the crash / load time in 1.5?

1.5 Crash after 30 seconds of loading english = English():

> builtins.MemoryError: Error assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytesError assigning 16777216 bytes

## Your Environment

* Operating System:  Win7 64-bit
* Python Version Used:  3.5.2
* spaCy Version Used:  1.5
* Environment Information:  python -m spacy.en.download all

**Comment by honnibal** [comment]
How much memory do you have?

**Comment by sk-** [comment]
Would it be possible to specify which parts of the model you want to load (or even better download)? At the moment there are two models for english, the glove vectors and the model for POS tagging, Named Entity recognition and syntactic dependency tree.

In bith English and german the model uses more than 1gb of memory. A good compromise would be If i could specify whether to load or not the model for Named entities or dependency tree.

**Comment by mattmacy** [comment]
@enjoysmath watch https://github.com/explosion/spaCy/pull/788 - as it should dramatically reduce the amount of physical memory needed, at least for smaller data sets
