### ISSUE TITLE
Lemmatizer wrong roots for "singing" in English

### ISSUE THREAD

**Issue by ccsv** [explosion/spaCy#7306]
## How to reproduce the behaviour

Root for singing should be sing not singe. Root for singeing should be singe

Code:
```
import spacy
from spacy.lang.en import English

nlp = spacy.load("en_core_web_sm")
lemmatizer = nlp.get_pipe("lemmatizer")

words = nlp('singing singeing ' )

for word in words:
	print(word.text,word.lemma_)
```
Output:
```
singing singe
singeing singeing
```

Singeing and singe [means to burn](https://www.thefreedictionary.com/singeing) not the same as sing 

## Your Environment

* Operating System: Windows
* Python Version Used: Python 3.8
* spaCy Version Used: 3
* Environment Information:

**Comment by polm** [comment]
Thanks for pointing that out, that looks like a mistake in the language data. We'll look at fixing it.

**Comment by ccsv** [comment]
@polm It might be a good idea to unit test the lemmatizer against manually tailored one

**Comment by polm** [comment]
The English lemma data is based on WordNet, which is manually collected and generally high quality. It does regard "singe" as related to "singing" though, while also including "sing".

http://wordnetweb.princeton.edu/perl/webwn?s=singing&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=

**Comment by polm** [comment]
Since the fix PR has been merged this will be fixed with the next release of the lookups. Thanks for reporting it!
