### ISSUE TITLE
Entity linker error: "entity_linker -> nsents   extra fields not permitted"

### ISSUE THREAD

**Issue by cj2001** [explosion/spaCy#7309]
## How to reproduce the behaviour
I am using the code that is in the docs as follows:

```
from spacy.pipeline.entity_linker import DEFAULT_NEL_MODEL

config = {
   "labels_discard": [],
   "nsents": 0,
   "incl_prior": True,
   "incl_context": True,
   "model": DEFAULT_NEL_MODEL,
   "entity_vector_length": 64,
   "get_candidates": {'@misc': 'spacy.CandidateGenerator.v1'},
}

nlp_ent = spacy.load('en_core_web_sm')
nlp_ent.add_pipe("entity_linker", config=config)
```

However, when I run this, I get the following error:

```
ConfigValidationError: 

Config validation error

entity_linker -> nsents   extra fields not permitted

{'nlp': <spacy.lang.en.English object at 0x7f2ea2a63f70>, 'name': 'entity_linker', 'entity_vector_length': 64, 'get_candidates': {'@misc': 'spacy.CandidateGenerator.v1'}, 'incl_context': True, 'incl_prior': True, 'labels_discard': [], 'model': {'@architectures': 'spacy.EntityLinker.v1', 'tok2vec': {'@architectures': 'spacy.HashEmbedCNN.v1', 'pretrained_vectors': None, 'width': 96, 'depth': 2, 'embed_size': 2000, 'window_size': 1, 'maxout_pieces': 3, 'subword_features': True}}, 'nsents': 0, '@factories': 'entity_linker'}
```

If I remove `"nsents": 0` then it runs fine and outputs the expected results with `print(nlp_ent.pipe_names)`.

## Your Environment

* Operating System: Ubuntu 20.04 LTS
* Python Version Used: 3.8.5
* spaCy Version Used: 3.0.3
* Environment Information:

**Comment by svlandeg** [comment]
Thanks for the report!

It looks like the docs are a little ahead - they are already documenting functionality that was recently [merged](https://github.com/explosion/spaCy/pull/7100), but hasn't been officially released yet. This should become available in the next release, and it would be great if you could test it again then!

In the meantime, you'll have to indeed leave this parameter out for now.

**Comment by cj2001** [comment]
Looking forward to the new functionality!  Thank you, @svlandeg!
