### ISSUE TITLE
💫 Doc.from_array() is missing support for some Token attributes

### ISSUE THREAD

**Issue by honnibal** [explosion/spaCy#731]
Currently the `doc.from_array()` method only supports a few token attributes. It's missing support for e.g. TAG, LEMMA, and others. It also fails with a confusing error if given an `ORTH` value.

## Details

* **Difficulty:** easy / suitable for new contributors
* **Implementation:**  [`tokens/doc.pyx#L466`](https://github.com/explosion/spaCy/blob/master/spacy/tokens/doc.pyx#L466)
* **Tests:** [`tests/doc/test_doc_api.py`](https://github.com/explosion/spaCy/blob/master/spacy/tests/doc/test_doc_api.py)
* **Related issues:** #815, #731

### Relevant docs
* API: [`Doc.to_array()`](https://spacy.io/docs/api/doc#to_array)
* Workflow: [spaCy's data model](https://spacy.io/docs/usage/data-model) 
* TODO: Setting lexical attributes (see #581)

**Comment by ines** [comment]
Fixed in v2.0!
