### ISSUE TITLE
Spacy Transformers:

### ISSUE THREAD

**Issue by balachander1964** [explosion/spaCy#7318]
## Your Environment

- Operating System:
- Python Version Used:
- spaCy Version Used:
- Environment Information:
Hi, I request you to provide us with examples on how to transfer learn, and use transformers based models. Also, could you please provide examples on how to use transformers in pipelines. Awaiting your response. Available documents regarding this is verbose and am not finding excamples at all.  Bala

**Comment by svlandeg** [comment]
Hi! I'll move this issue to the discussion forum, which is more suited for general questions on how to use the library, get help with specific code implementations etc. We're trying to keep the issue tracker itself focused on mainly bugs.

You may get a note saying this got closed - but the related discussion will remain open on the forum.
