### ISSUE TITLE
Spacy POS tree looks wrong to me.

### ISSUE THREAD

**Issue by prabhatmnnit** [explosion/spaCy#733]
I am using this function spacy.en.English()  for pos tagging of following statement.
"ENTITY is a 1987 American slasher film and the third film in the Nightmare on Elm Street series. ".

It is giving following pos tree:
{u'is': {u'series': {u'film': {u'a': {}, u'1987': {}, u'and': {}, u'slasher': {}, u'american': {}, u'film': {u'the': {}, u'third': {}, u'in': {u'nightmare': {u'on': {u'street': {u'elm': {}}}, u'the': {}}}}}}, u'.': {}, u'entity': {}}}

With following pos tags:
[(ENTITY, u'NNP'), (is, u'VBZ'), (a, u'DT'), (1987, u'CD'), (American, u'JJ'), (slasher, u'NN'), (film, u'NN'), (and, u'CC'), (the, u'DT'), (third, u'JJ'), (film, u'NN'), (in, u'IN'), (the, u'DT'), (Nightmare, u'NNP'), (on, u'IN'), (Elm, u'NNP'), (Street, u'NNP'), (series, u'NN'), (., u'.')]

Pos tree looks wrong for me because film should be head noun here rather then series. And film should be child of "is"  rather then child of series . "is"  used for film rather then series by the statement.

Is it expected behavior  or a bug ?

## Your Environment
* Operating System: Linux 
* Python Version Used:  2.7.3
* spaCy Version Used: 0.101.0
* Environment Information:

**Comment by honnibal** [comment]
Hey,

I agree the parse looks bad here: https://demos.explosion.ai/displacy/?text=ENTITY%20is%20a%201987%20American%20slasher%20film%20and%20the%20third%20film%20in%20the%20Nightmare%20on%20Elm%20Street%20series.&model=en&cpu=1&cph=0

But we can't address bad parses on a case-by-case basis...Unless there's a bug in the code here, or a systematic problem we can design features to address, there's not much to say about individual parse errors.

spaCy's dependency parser is about 92% accurate. That means some sentences will be parsed quite badly. We're working on updating to new algorithms, to reduce the number of these errors.
