### ISSUE TITLE
Pydantic ConfigError when nlp Typed as Language in Custom Factory

### ISSUE THREAD

**Issue by gandersen101** [explosion/spaCy#7344]
In my spaCy extension package [spaczz](https://github.com/gandersen101/spaczz) I use type hints and type check with MyPy. I was able to update my custom factory component the [SpaczzRuler](https://github.com/gandersen101/spaczz/blob/master/src/spaczz/pipeline/_spaczzruler.py) to work with spaCy v3, however I ran into an issue when typing the `nlp` parameter in the `@Language.factory` decorated constructor. If I use the `Any` type it works fine, however if I type it correctly as `Language`, I get an Pydantic ConfigError (details below).

This is not a high priority issue for me as it works with the `Any` type, and it's entirely possible my own typing elsewhere is causing this error, but I wanted to bring it to your attention.

## How to reproduce the behaviour

The code snippet for the factory constructor is (lines 38-74 in the SpaczzRuler link above):

```python
@Language.factory(
    "spaczz_ruler",
    assigns=["doc.ents", "token.ent_type", "token.ent_iob"],
    default_config={
        "overwrite_ents": False,
        "ent_id_sep": DEFAULT_ENT_ID_SEP,
        "fuzzy_defaults": simple_frozen_dict,
        "regex_defaults": simple_frozen_dict,
        "token_defaults": simple_frozen_dict,
    },
    default_score_weights={
        "ents_f": 1.0,
        "ents_p": 0.0,
        "ents_r": 0.0,
        "ents_per_type": None,
    },
)
def make_spaczz_ruler(
    # typing nlp with Language causes issue with Pydantic in spaCy integration
    nlp: Language,
    name: str,
    overwrite_ents: bool,
    ent_id_sep: str,
    fuzzy_defaults: Dict[str, Any],
    regex_defaults: Dict[str, Any],
    token_defaults: Dict[str, Any],
) -> SpaczzRuler:
    """Factory method for creating a `SpaczzRuler`."""
    return SpaczzRuler(
        nlp,
        name,
        overwrite_ents=overwrite_ents,
        ent_id_sep=ent_id_sep,
        fuzzy_defaults=fuzzy_defaults,
        regex_defaults=regex_defaults,
        token_defaults=token_defaults,
    )
```

The error I get is:

```python
../../Library/Caches/pypoetry/virtualenvs/spaczz-L6XjOrzm-py3.9/lib/python3.9/site-packages/spacy/language.py:767: in add_pipe
    pipe_component = self.create_pipe(
../../Library/Caches/pypoetry/virtualenvs/spaczz-L6XjOrzm-py3.9/lib/python3.9/site-packages/spacy/language.py:658: in create_pipe
    resolved = registry.resolve(cfg, validate=validate)
../../Library/Caches/pypoetry/virtualenvs/spaczz-L6XjOrzm-py3.9/lib/python3.9/site-packages/thinc/config.py:721: in resolve
    resolved, _ = cls._make(
../../Library/Caches/pypoetry/virtualenvs/spaczz-L6XjOrzm-py3.9/lib/python3.9/site-packages/thinc/config.py:770: in _make
    filled, _, resolved = cls._fill(
../../Library/Caches/pypoetry/virtualenvs/spaczz-L6XjOrzm-py3.9/lib/python3.9/site-packages/thinc/config.py:825: in _fill
    filled[key], validation[v_key], final[key] = cls._fill(
../../Library/Caches/pypoetry/virtualenvs/spaczz-L6XjOrzm-py3.9/lib/python3.9/site-packages/thinc/config.py:889: in _fill
    result = schema.parse_obj(validation)
pydantic/main.py:520: in pydantic.main.BaseModel.parse_obj
    ???
pydantic/main.py:360: in pydantic.main.BaseModel.__init__
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   pydantic.errors.ConfigError: field "nlp" not yet prepared so type is still a ForwardRef, you might need to call ArgModel.update_forward_refs().

pydantic/main.py:960: ConfigError
```

For reference my entry point is written like so using Poetry:

```
[tool.poetry.plugins."spacy_factories"]
"spaczz_ruler" = "spaczz.pipeline:SpaczzRuler"
```

## Your Environment

* Operating System:
    * macOS 11.1
* Python Version Used:
    * 3.9.0 
* spaCy Version Used:
    * 3.0.3 
* Environment Information:
    * Using Poetry 1.1.4
 
<ins>No Dev Packages:</ins>
blis               0.7.4
catalogue          2.0.1
certifi            2020.12.5
chardet            4.0.0
click              7.1.2
cymem              2.0.5
idna               2.10
importlib-metadata 1.7.0
jinja2             2.11.3
markupsafe         1.1.1
murmurhash         1.0.5
numpy              1.20.1
packaging          20.9
pathy              0.4.0
preshed            3.0.5
pydantic           1.7.3
pyparsing          2.4.7
rapidfuzz          1.2.1
regex              2020.11.13
requests           2.25.1
smart-open         3.0.0
spacy              3.0.3
spacy-legacy       3.0.1
srsly              2.4.0
thinc              8.0.1
tqdm               4.59.0
typer              0.3.2
typing-extensions  3.7.4.3
urllib3            1.26.3
wasabi             0.8.2
zipp               3.4.1

If you need dev packages too let me know.

Thanks!

**Comment by svlandeg** [comment]
Hi, and apologies for the late follow-up.

I'm a little confused why you're getting this error. For the internal spaCy factories, we also just type `nlp` as `Language` and haven't gotten issues with that. See for instance https://github.com/explosion/spaCy/blob/master/spacy/pipeline/lemmatizer.py

What code are you executing when you're running into this? Are you training with a config file, or writing a custom training loop?

**Comment by gandersen101** [comment]
Hi @svlandeg thanks for getting back to me.

This happens simply by adding my custom pipeline component to a pipeline. So for example:

```python
nlp = spacy.blank("en")
spaczz_ruler = nlp.add_pipe("spaczz_ruler")
```
I did figure out how to use the `Language` type in the custom factory without raising the error but I'm not sure if I understand exactly why.

My custom component uses postponed type evaluations from PEP 563. I import `annotations` from `__future__` so I can self-reference my classes. If I remove the `__future__` import and change my self-references into strings the error goes away.

I see there is a way to update forward refs with Pydantic models but my code does not use Pydantic.

It doesn't seem like using the `Any` type instead of `Language` is causing any harm so I'd rather not strip out the PEP 563 annotations from my code unless you believe there may be some future and/or subtle problems my PEP 563 annotations may cause.

Thanks!

**Comment by polm** [comment]
Hello, apologies again for the very delayed reply to this. I don't think aware of any subtle issues with this, I think we're still figuring out everything with types ourselves, and the landscape is still changing pretty regularly. 

I think this is resolved, but if you know of a way we can improve our annotations feel free to let us know any time.
