### ISSUE TITLE
ValueError: [E002] Can't find factory for 'relation_extractor' for language English (en)

### ISSUE THREAD

**Issue by HarshadaPatil26** [explosion/spaCy#7345]
I've come across the issue:
ValueError: [E002] Can't find factory for 'relation_extractor' for language English (en). This usually happens when spaCy calls `nlp.create_pipe` with a custom component name that's not registered on the current language class. If you're using a Transformer, make sure to install 'spacy-transformers'. If you're using a custom component, make sure you've added the decorator `@Language.component` (for function components) or `@Language.factory` (for class components).

Available factories: attribute_ruler, tok2vec, merge_noun_chunks, merge_entities, merge_subtokens, token_splitter, parser, beam_parser, entity_linker, ner, beam_ner, entity_ruler, lemmatizer, tagger, morphologizer, senter, sentencizer, textcat, textcat_multilabel, en.lemmatizer

I am referring the link for realtion extractor:
https://github.com/explosion/projects/tree/v3/tutorials/rel_component

**Comment by svlandeg** [comment]
(also as a maintenance note - I'll move this question to the discussions forum. You'll get a notification that this got closed, but there will be a link to the related thread that remains open)
