### ISSUE TITLE
Feature request: keep shorter spans in util.filter_spans

### ISSUE THREAD

**Issue by ktobah** [explosion/spaCy#7346]
According to the util.filter_spans docs, it says:

> Filter a sequence of Span objects and remove duplicates or overlaps. Useful for creating named entities (where one token can only be part of one entity) or when merging spans with Retokenizer.merge. When spans overlap, the (first) longest span is preferred over shorter spans.

I was wondering if it is possible to make this function more flexible and allow the user to choose to either keep the shorter or longer spans? In my case, I need to keep the shorter spans.

**Comment by adrianeboyd** [comment]
We're trying to keep the issue tracker more focused on bugs, so I'm going to convert this to a discussion thread in our new "Feature requests" discussion topic. You'll get a message that this issue is locked, but the new thread will be open.
