### ISSUE TITLE
EntityRuler labels order not deterministic

### ISSUE THREAD

**Issue by jankrepl** [explosion/spaCy#7352]
## How to reproduce the behaviour
If you run the below script multiple times you will realize that the order of labels is random.
```python
# myscript.py
import json
import spacy

nlp = spacy.blank("en")
ruler = nlp.add_pipe("entity_ruler")
patterns = [
    {"label": "label_1", "pattern": "pattern_1"},
    {"label": "label_2", "pattern": "pattern_2"},
]
ruler.add_patterns(patterns)

nlp.to_disk("output_folder")

with open("output_folder/meta.json", "r") as f:
    print(json.load(f)["labels"]["entity_ruler"])

```
Locally, I run
```bash
for i in {1..10}
do
  python myscript.py
done
```
and get
```bash
['label_2', 'label_1']
['label_1', 'label_2']
['label_1', 'label_2']
['label_2', 'label_1']
['label_1', 'label_2']
['label_1', 'label_2']
['label_1', 'label_2']
['label_2', 'label_1']
['label_1', 'label_2']
['label_1', 'label_2']
```
Note that this is problematic because the MD5 hash of the `meta.json` is not deterministic (tools like DVC rely on it).

## Your Environment

* Operating System: MacOS
* Python Version Used: 3.8.8
* spaCy Version Used: very recent master commit 3f3e8110dc6ec3c1449b120c29ffc7d5475ef622. The same issue should therefore be present in multiple Spacy versions.
* Environment Information: nothing special I assume

**Comment by polm** [comment]
Thanks for the report; this is related to https://github.com/explosion/spaCy/issues/7028, if not quite a duplicate, so you might want to look at that.
