### ISSUE TITLE
Internal parser of NER implying cost even if predicted and golds labels match

### ISSUE THREAD

**Issue by davesuketu215** [explosion/spaCy#7380]
https://github.com/explosion/spaCy/blob/3b911ee5ef2240919b66a0ce55a5d387ceb6f904/spacy/pipeline/_parser_internals/ner.pyx#L381
```
        elif g_act == BEGIN:
            # B, Gold B --> Label match
            return label != g_tag
```
I was having a deep-dive into the spaCy coding for NER internal parser, where I found that at the above position in the code, even if the actual and predicted labels are matching, 'False' is being returned, which would in-turn imply a cost to the move.

Could you please let me know whether I am missing something here, or is this a valid issue?

Also, is this file, the proper place where the cost matrix is built up?? I am asking this because I want to customize the cost matrix to imply greater penalty to False Positives, compared to False Negatives. Any means to achieve this?

**Comment by svlandeg** [comment]
> even if the actual and predicted labels are matching, 'False' is being returned, which would in-turn imply a cost to the move.

I could be wrong - but doesnt `False` imply a cost of `0`? So you'll get a cost of 1 (for `True`) if the labels don't match?

**Comment by davesuketu215** [comment]
Let me just correct my understanding from both philosophical and algorithmic aspect. I have the below thoughts and questions. I am looking at it in depth. Correct me if I am wrong:

1. Is the definition of 'cost' in this file a penalty for wrong moves during training? Or is that the opposite?
2. So if there is a move which is in accordance to golds, ideally cost should be 0 if it is defined as penalty.
3. I see at some places the cost is assigned as 9000 in case where ```is_valid( )``` fails. Why is this cost so high and different as compared to cost of 1 during non-matching of labels? Ideally both of these should be same because in either cases, the model is making a mistake.
4. Is this 'cost' the same ones which is used by ```cpu_log_loss``` in ```Parser``` to calculate the batch loss in each training epoch?
5. I want to tweak the spaCy training in such a way that the model is penalized for making wrong moves (wrong moves means the moves which are not in accordance with those in golds) How do I achieve that? Is ```_parser_internals/ner.pyx``` the correct place for that?

**Comment by honnibal** [comment]
That code will return a cost of 1 if the labels don't match, which is correct.

The value of 9000 is used to denote invalid to make debugging easier; in practice invalid moves are removed from the set and get 0 gradient so it doesnt matter what cost is assigned to them.

I'm not sure I understand what you're trying to do? The parser does learn not to make incorrect moves.

**Comment by davesuketu215** [comment]
Thank You for the clarification on the value of 9000. I was getting confused with it somehow, but now I am clear about it.

Alright, so what I am trying to do is that I want to define a custom cost matrix in place of the default ones which is in place.
The discussion is towards cost-sensitive learning. At present, all the mistakes are at the same level of wrongness, that is all mistakes have penalty of 1.
Rather, I define certain mistakes as more critical compared to others. So maybe a cost of 1000 for such critical ones, and cost of say 1 for the remaining ones. I would want the model to be stricter.

I define False Positive as a scenario where the model classifies a span as entity, but it actually isn't. I define False Negative as a scenario where the model misses to identify the span as an entity, but actually it is an entity.

So, it is like if in a transition move, if the model classifies a B instead of an O, I say that model is creating a False Positive, which is a mistake of bigger magnitude. On the contrary, if it classifies the move as O instead of a B, i say that this is a mistake of smaller magnitude.
There are certain technical reasons behind this, as the result of NER would be used at a place where we want as minimal False Positives as much as the model can, but still be able to identify entities in unseen data within the context.

I hope you got my point now. In a nutshell, I want my custom spaCy model to do cost-sensitive learning. So that my model learns the way I would want it to learn.

**Comment by polm** [comment]
Sorry for the delayed reply to this. 

Using a custom cost matrix sounds like an interesting idea, but I don't think we're interested in making that part of the public API. If there's something in particular you don't understand you could open a Discussion for help with that, but since you're delving pretty deep into the parser internals we may only be able to give limited support. 

Since there's no action for us to take on this (and it's diverged from the title) I'm going to mark it as resolved.
