### ISSUE TITLE
EntityRuler needs morphologizer to match patterns with POS attribute

### ISSUE THREAD

**Issue by kelvin-tran** [explosion/spaCy#7382]
## How to reproduce the behaviour
Am getting a `ValueError` when attempting to use the `EntityRuler` pipeline component with additional patterns containing the `POS` attribute (eg, match additional named entities based on custom patterns). This means it's no longer possible to use the EntityRuler with patterns to match on `POS` values. Such functionality which was possible before v3.0.0 and is suggested as still possible in the [docs](https://spacy.io/usage/rule-based-matching) and the [Matcher Explorer](https://explosion.ai/demos/matcher) (no mention of the morphologizer being required in the pipeline).

Code to reproduce:
```
import spacy

nlp = spacy.load("en_core_web_md")  # or any of the 4 English models
ruler = nlp.add_pipe("entity_ruler", before="ner")
patts = [
    {
            "label": "STATUTE",
            "pattern": [
                {"POS": "PROPN", "OP": "+"},  # Securities Exchange
                {"LOWER": "act"},
                {"LOWER": "of"},
                {"POS": "NUM"},  # 1933
            ],
    }
]
ruler.add_patterns(patts)
doc = nlp("Some doc")
```

This leads to the `ValueError`:
```
File ".../lib/python3.8/site-packages/spacy/pipeline/entityruler.py", line 147, in match
    matches = list(self.matcher(doc)) + list(self.phrase_matcher(doc))
  File "spacy/matcher/matcher.pyx", line 231, in spacy.matcher.matcher.Matcher.__call__
ValueError: [E155] The pipeline needs to include a morphologizer in order to use Matcher or PhraseMatcher with the attribute POS. Try using `nlp()` instead of `nlp.make_doc()` or `list(nlp.pipe())` instead of `list(nlp.tokenizer.pipe())`
```

The issue seems to be the `self.matcher(doc)` call (ie, `phrase_matcher` returns fine). Again, nothing in the [Matcher docs](https://spacy.io/api/matcher) suggests we need a morphologizer to use `POS` patterns. 

Calling `nlp` works if we omit the `POS` part of the pattern (but obviously then the pattern is incomplete). 

Was it intended that a morphologizer was required to use the `POS` attribute in match pattern? This code worked very recently in Spacy < 3.0.0. I've attempted to add `morphologizer` to the pipeline but that seems to error as well:
```
File ".../lib/python3.8/site-packages/spacy/ml/_character_embed.py", line 31, in forward
    E = model.get_param("E")
  File .../lib/python3.8/site-packages/thinc/model.py", line 212, in get_param
    raise KeyError(
KeyError: "Parameter 'E' for model 'charembed' has not been allocated yet."

The above exception was the direct cause of the following exception:
File ".../lib/python3.8/site-packages/spacy/language.py", line 992, in __call__
ValueError: [E109] Component 'morphologizer' could not be run. Did you forget to call `initialize()`?
```

How do we get EntityRuler matching based on patterns with `POS` attributes working?

## Your Environment

* Operating System: macOS-10.15.5-x86_64-i386-64bit
* Python Version Used: 3.8.6
* spaCy Version Used: 3.0.3
* Environment Information: en_core_web_md (3.0.0), en_core_web_sm (3.0.0), en_core_web_trf (3.0.0)

**Comment by adrianeboyd** [comment]
Ack, I should never post examples without running them. It should be (already edited above):

```python
nlp.add_pipe("ner", source=spacy.load("en_core_web_sm"))
```

**Comment by kelvin-tran** [comment]
Thanks @adrianeboyd. Can confirm this fixes the issue. For anyone else that comes across this, the order of the pipeline components, after removing and adding the `ner` component per the steps above, are as follows:
```
print(nlp.pipe_names)
# ['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'entity_ruler', 'ner', ... ]
```

**Comment by simonschoe** [comment]
Sorry, for re-opening this one. I am running into the exact same error when activating the `senter` component:

```python
import spacy

nlp = spacy.load(
    'en_core_web_trf',
    disable=['ner'],
    config={'components.lemmatizer.mode': 'rule'}
)

nlp.add_pipe('senter')
```
If I comment the last line out, the pipeline runs through. Any ideas? :)
