### ISSUE TITLE
import en_ner_bionlp13cg_md results in error --> AttributeError: type object 'Language' has no attribute 'component'

### ISSUE THREAD

**Issue by Rd0394** [explosion/spaCy#7383]
Code:
!pip install spacy
!pip install scispacy
!pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.0/en_ner_bionlp13cg_md-0.2.0.tar.gz                #install an NER model trained on bionlp13c corpus

#Environment used:

* Operating System: Ubuntu 20.04.2 LTS
* Python Version Used: Python 3.8.5
* spaCy Version Used: Spacy 3.0.4

![git](https://user-images.githubusercontent.com/78722507/110588559-30964300-819b-11eb-8c0e-86df99e4bfbe.png)

I need to load the bionlp model and filter out the biological terms in my dataset

**Comment by adrianeboyd** [comment]
Hi, you need to update your model URL to the one for the version of scispacy that supports spacy v3. See:

https://github.com/allenai/scispacy/#available-models

The older models for spacy v2 / scispacy 0.2.x/0.3.x are not compatible with the spacy v3.

**Comment by adrianeboyd** [comment]
And this is a good question for our new discussions board, so I'll transfer it there in a second. This issue will be locked, but the new discussion thread will be open.
