### ISSUE TITLE
Help understanding how parse features work

### ISSUE THREAD

**Issue by matthayes** [explosion/spaCy#739]
Reading through the documentation on [training](https://spacy.io/docs/usage/training), I wanted to understand which atomic predictors are available.  Looking at [ner](https://github.com/explosion/spaCy/blob/master/spacy/syntax/_parse_features.pyx#L112) I see enum values like `N0W`, `P1W`, etc. being referenced.   I see these defined [here](https://github.com/explosion/spaCy/blob/master/spacy/syntax/_parse_features.pxd) but it's not clear what they refer to.  I can't find them documented and a full text search wasn't helpful either.  

Similarly, looking in [tagger.pyx](https://github.com/explosion/spaCy/blob/master/spacy/tagger.pyx) I see values like `W_shape` in the feature templates but don't see how this is defined.

**Comment by ines** [comment]
Sorry for the late reply – we've now added a new page to the docs that includes an overview of the feature scheme and context tokens. 

For more info, check out #857 or the feature scheme docs: https://spacy.io/docs/api/features

**Comment by matthayes** [comment]
This doc looks great, thanks!
