### ISSUE TITLE
Date parsing

### ISSUE THREAD

**Issue by pokey** [explosion/spaCy#740]
Date parsing seems to have changed from SpaCy 1.5.0 to 1.5.1.  The following code snippet:

```
import spacy

nlp = spacy.load('en')
doc = nlp('We started on 3/4/2012.')
print(list(doc))
```

prints `[We, started, on, 3/4/2012, .]` in SpaCy 1.5.0, and `[We, started, on, 3, /, 4, /, 2012, .]` in SpaCy 1.5.1.  Is this intended?

## Your Environment
* Operating System: OS X 10.11.6
* Python Version Used: Python 3.5.2
* spaCy Version Used: 1.5.1
* Environment Information:

**Comment by ines** [comment]
Ah, looks like this was a side-effect of the new (and slightly stricter) [punctuation rules](https://github.com/explosion/spaCy/blob/master/spacy/language_data/punctuation.py).

I'll be pushing a fix and test for this in a second. It should handle dates like `3/4/2012` as one token again, but it'll still split dates like `3-4-2012`. 

This will be hard to prevent, as it clashes with the numeric ranges that follow a similar pattern (and that should be split by the tokenizer). The simple regexes used to split infixes are not sufficient to make this distinction, so in the long run, we'll have to find a better solution here to keep things consistent.

**Comment by matthayes** [comment]
It seems like it would be nicer to have the tokenizer split on both `/` and `-` so that the dates are handled consistently for both formats.
