### ISSUE TITLE
Problem while installing spacy in windows 10 with pip and also using source

### ISSUE THREAD

**Issue by kishorenayar** [explosion/spaCy#741]
I tried to install spacy in windows 10, I have **python 3.5**, the installation was made using [anaconda](https://anaconda.org/) also I have **Microsoft Visual C++ 15**. The reason I tried with pip instead of conda is because, **conda spacy packages are very old** and I want the latest one. So I tried two approaches one with **pip** and with **source** 

Using pip - **pip install spacy**, I got the following error

 running build_ext                                                                                                                                         
 building 'spacy.parts_of_speech' extension                                                                                                                
 error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools   
                                                                                                                                                           
 ----------------------------------------                                                                                                                  
 Failed building wheel for spacy                                                                                                                           
 Running setup.py clean for spacy                                                                                                                          
 Running setup.py bdist_wheel for ujson ... error                                                                                                          
 Complete output from command D:\Programs\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Skanda\\AppData\\Local\\Temp\\pip-bu
ttr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Skanda\A
l- --python-tag cp35:                                                                                                                                      
 running bdist_wheel                                                                                                                                       
 running build                                                                                                                                             
 running build_ext                                                                                                                                         
 building 'ujson' extension                                                                                                                                
 error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools   
                                                                                                                                                           
 ----------------------------------------                                                                                                                  
 Failed building wheel for ujson                                                                                                                           
 Running setup.py clean for ujson                                                                                                                          
ailed to build spacy ujson                                                                                                                                 
nstalling collected packages: ujson, spacy                                                                                                                 
 Running setup.py install for ujson ... error                                                                                                              
   Complete output from command D:\Programs\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Skanda\\AppData\\Local\\Temp\\pip-
tattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Skan
cord\install-record.txt --single-version-externally-managed --compile:                                                                                     
   running install                                                                                                                                         
   running build                                                                                                                                           
   running build_ext                                                                                                                                       
   building 'ujson' extension                                                                                                                              
   error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools 

When I tried to install with source **python setup.py install**, I got this error

Cythonizing sources                                                                                                                                    
running install                                                                                                                                        
running bdist_egg                                                                                                                                      
running egg_info                                                                                                                                       
writing top-level names to spacy.egg-info\top_level.txt                                                                                                
writing dependency_links to spacy.egg-info\dependency_links.txt                                                                                        
writing spacy.egg-info\PKG-INFO                                                                                                                        
writing requirements to spacy.egg-info\requires.txt                                                                                                    
reading manifest file 'spacy.egg-info\SOURCES.txt'                                                                                                     
reading manifest template 'MANIFEST.in'                                                                                                                
writing manifest file 'spacy.egg-info\SOURCES.txt'                                                                                                     
installing library code to build\bdist.win-amd64\egg                                                                                                   
running install_lib                                                                                                                                    
running build_py                                                                                                                                       
running build_ext                                                                                                                                      
building 'spacy.parts_of_speech' extension                                                                                                             
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

**Comment by hft7h11** [comment]
Hi All,

When I installed from PIP I got

gcc.exe: error: spacy/parts_of_speech.cpp: No such file or directory
    gcc.exe: fatal error: no input files
    compilation terminated.

I tried installing from the source using setup.py using the 1.3.0 zip from https://github.com/explosion/spaCy/releases/tag/v1.3.0

I recieved the following error:

Cythonizing sources
Processing cfile.pyx

Error compiling Cython file:
------------------------------------------------------------
...
from libc.stdio cimport fopen, fclose, fread, fwrite, FILE
from cymem.cymem cimport Pool
^
------------------------------------------------------------

cfile.pxd:2:0: 'cymem\cymem.pxd' not found
Traceback (most recent call last):
  File "C:\Anaconda2\Lib\site-packages\spaCy-1.3.0\bin\cythonize.py", line 156, in <module>
    run(args.root)
  File "C:\Anaconda2\Lib\site-packages\spaCy-1.3.0\bin\cythonize.py", line 147, in run
    process(base, filename, db)
  File "C:\Anaconda2\Lib\site-packages\spaCy-1.3.0\bin\cythonize.py", line 113, in process
    preserve_cwd(base, process_pyx, root + '.pyx', root + '.cpp')
  File "C:\Anaconda2\Lib\site-packages\spaCy-1.3.0\bin\cythonize.py", line 78, in preserve_cwd
    func(*args)
  File "C:\Anaconda2\Lib\site-packages\spaCy-1.3.0\bin\cythonize.py", line 60, in process_pyx
    raise Exception('Cython failed')
Exception: Cython failed
Traceback (most recent call last):
  File "setup.py", line 263, in <module>
    setup_package()
  File "setup.py", line 214, in setup_package
    generate_cython(root, 'spacy')
  File "setup.py", line 146, in generate_cython
    raise RuntimeError('Running cythonize failed')
RuntimeError: Running cythonize failed

I have tried this on cython 0.23.4 and cython 0.23.5 Should I try another version?
I am running Windows 10, Anaconda 2, Python 2.7

**Comment by mattmacy** [comment]
@hft7h11 this looks like a path problem. Can you see where cymem.pxd is on your file system.

**Comment by mingsterism** [comment]
I had the same problem on windows using pip and python 3.5. Just install Microsoft Visual C++ Build Tools. It worked fine for me after that.

**Comment by afsun** [comment]
I have the same problem....

**Comment by sivu1** [comment]
If you are using anaconda, use the conda-forge packages. Its seamless
`conda install -c conda-forge spacy=1.8.2`

**Comment by BadrulAlom** [comment]
@sivu1 Actually this gives me an error: ERROR conda.core.link:_execute_actions(337): An error occurred while installing
package 'conda-forge::tqdm-4.19.2-py_0'.
