### ISSUE TITLE
Different lemmas for the same word

### ISSUE THREAD

**Issue by Tantacula** [explosion/spaCy#7410]
## How to reproduce the behaviour
Hi, I wrote next python script:

```
import spacy
nlp = spacy.load('en_core_web_md')
doc = nlp(input())
for token in doc:
    print(token, token.lemma_)
```
And it returns different results for the same words:
```
echo Focused | python3 lemmatize.py

Focused focus
```

```
echo in Focused | python3 lemmatize.py

in in
Focused Focused
```

I assume it should return the same result for the "Focused" word.

## Your Environment
- **spaCy version:** 3.0.3
- **Platform:** Linux-4.19.121-linuxkit-x86_64-with-debian-10.8
- **Python version:** 3.7.3
- **Pipelines:** en_core_web_md (3.0.0)

**Comment by adrianeboyd** [comment]
No, the rule-based lemmatizer in `en_core_web_md` depends on the predicted POS, which depends on the context around the word.
