### ISSUE TITLE
[Enhancement] DocBin interface : constructor and add -> append

### ISSUE THREAD

**Issue by DSLituiev** [explosion/spaCy#7416]
Some suggestions on design for `DocBin`:

1. `from_disk` can be made a class-level constructor:

in `class DocBin`:
```python
@classmethod
    def from_disk(
```

user-facing: `data = DocBin.from_disk(filename)`

2. Pythonic `append()` instead of `add()` might be more intuitive for many users, as it is standard syntax for growing lists.

**Comment by svlandeg** [comment]
Hi!

Thanks for the suggestion, but I think with spaCy 3 just recently released, we're not too keen on changing the names of user-facing methods.

With respect to the class-level constructor, I don't think that works? We're calling `self.from_bytes` which needs access to the actual values of the current `DocBin` instance.
