### ISSUE TITLE
spacy 1.5.1 TypeError: unhashable type: 'spacy.tokens.token.Token'

### ISSUE THREAD

**Issue by kootenpv** [explosion/spaCy#743]
I now get a `TypeError: unhashable type: 'spacy.tokens.token.Token'` while in 1.5.0 the code runs (added Token to a set).

## Your Environment

* Operating System:  OSX
* Python Version Used:  3.5
* spaCy Version Used: 1.5.1
* Environment Information:

**Comment by honnibal** [comment]
Thanks! Puzzled why this worked before. Will add a `__hash__` special method.
