### ISSUE TITLE
masked token prediction

### ISSUE THREAD

**Issue by BHX2** [explosion/spaCy#7434]
Is it possible to use the spacy-transformer model for prediction of `<mask>` tokens? I had originally planned to use the pytorch shim for roberta-base that I thought would be within en_core_web_trf but it seems that the thinc model does not include the pytorch model within it. My understanding is that only the converted model is kept. If so, would a forward pass with injected `<mask>` tokens predict probabilities similar to the original pytorch transformer?

**Comment by svlandeg** [comment]
[Maintenance note: Moving this thread to the discussion forum. The original issue will be closed but will contain a link to the newly opened thread on the forum, where discussion can continue]
