### ISSUE TITLE
doc.noun_chunks is not supported for Chinese language, how to figure this out?

### ISSUE THREAD

**Issue by maohbao** [explosion/spaCy#7436]
I want to extract noun chunks from the Chinese text, but it seems that doc.noun_chunks is not supported for Chinese language, what shall I do?

**Comment by polm** [comment]
What exactly defines a "noun chunk" is highly language dependent, so each language in spaCy has its own implementation of this. The way you would add it to a language is to add or modify the `syntax_iterators.py` file for your language and define a `noun_chunks` function. You can see the English version here:

https://github.com/explosion/spaCy/blob/master/spacy/lang/en/syntax_iterators.py

When I added `noun_chunks` for Japanese, what I did was copy over the English version, prepare a bunch of example sentences, and then modify the function until the results were correct for all my example sentences. You could use a similar approach for Chinese.

Another option if you don't want to modify the language implementation is to use the [PhraseMatcher][] to match based on part of speech tags, or the [DependencyMatcher][] to match based on dependencies. 

[PhraseMatcher]: https://spacy.io/usage/rule-based-matching#phrasematcher
[DependencyMatcher]: https://spacy.io/usage/rule-based-matching#dependencymatcher

**Comment by polm** [comment]
Since we're not actively working on this, and nobody has volunteered, I'm going to close this issue since there's no action for us to take on it. But if someone wants to open a PR to add noun chunks for Chinese (or any other language) it would be welcome!
