### ISSUE TITLE
wrong token

### ISSUE THREAD

**Issue by CnsAd** [explosion/spaCy#744]
INPUT:
```
import spacy
nlp = spacy.load('en')
doc1 = nlp(u"They have killed the bat last night. We were so scared!")
for token in doc1:
    print(token)
```
OUTPUT:
They
have
killed
the
bat
last
night
.
We
we
re
so
scared
the "were" has been tokenized wrongly!

**Comment by keotic** [comment]
Noticed that as well, currently spotted this bug only at "were"

**Comment by ines** [comment]
Ah, this seems to be a mistake in the tokenizer exceptions. It's adding all contractions with and without apostrophes, but `were` and `Were` should obviously have been excluded (like it's currently done for `well`, `hell`, `ill` etc). 

This is easy to fix – will do this now and add a regression test.
