### ISSUE TITLE
[E053] Could not read config.cfg

### ISSUE THREAD

**Issue by SapiensSuwan** [explosion/spaCy#7453]
## my code
!pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.0.tar.gz
!pip install pyresparser
data_words_nostops = remove_stopwords(abs_words)
data_words_bigrams = make_bigrams(data_words_nostops)
nlp = spacy.load('en_core_web_sm', disable=['parser', 'ner'])

## Error I've got
`OSError: [E053] Could not read config.cfg from /Users/suwanlong/opt/anaconda3/lib/python3.8/site-packages/en_core_web_sm/en_core_web_sm-2.3.1/config.cfg`

## Your Environment

* Operating System: Mac OS
* Python Version Used: anaconda python 3.8
* spaCy Version Used: 3.0.5

## I have tried

`pip install -U pip setuptools wheel
pip install -U spacy
python -m spacy download en_core_web_sm`

`$!python -m spacy download en_core_web_sm
import spacy
nlp = spacy.load("en_core_web_sm")
 `

All of them are not working for my case.

Any ideas? thanks!

**Comment by svlandeg** [comment]
Hi! The 2.2.0 model is incompatible with spaCy v3. You can check your models and installation with 
```
python -m spacy validate
```
So I'm afraid you'll either have to downgrade spaCy to `2.2.4` to work with this particular model, or download a new model, e.g. https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0.tar.gz

**Comment by SapiensSuwan** [comment]
> https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0.tar.gz

Amazing! It solved my issue. Thank you so much!

**Comment by svlandeg** [comment]
Happy to hear it!
