### ISSUE TITLE
English lemmatizer does not work. 

### ISSUE THREAD

**Issue by satya77** [explosion/spaCy#7460]
When trying to use the lemmatizer for en_core_web_sm, the lemma always the same as the token text. 

```python
import spacy
nlp = spacy.load('en_core_web_sm')
doc = nlp("I am interested in this interesting project and going to participate in it. ")
for token in doc:
    print(token, token.lemma_)
```

I tried this on a rather larger document collection and always the lemma is same as the token text, only lowercased. 

## Your Environment

- Operating System: linux 
- Python Version Used: 3.9 
- spaCy Version Used: 3.0 
- Environment Information: en_core_web_sm (3.0.0)

**Comment by adrianeboyd** [comment]
Hi, hmm, I can't replicate this. The output I get for this example is:

```none
I I
am be
interested interested
in in
this this
interesting interesting
project project
and and
going go
to to
participate participate
in in
it it
. .
```

**Comment by satya77** [comment]
sorry you are right, I did not pay attention to "am" and "be" but rather different tenses of the verbs like "interesting" those seems to always remain the same.

**Comment by polm** [comment]
If you also print out the part of speech of the tokens, you'll see that "interested" and "interesting" in your sentence are both marked as ADJ. Since lemmas are part of speech dependent it makes sense that they would be the same as the literal form in this case.

**Comment by satya77** [comment]
I see, thank you for the clarification.
