### ISSUE TITLE
Importing SpanGroup does not work

### ISSUE THREAD

**Issue by thiippal** [explosion/spaCy#7468]
## How to reproduce the behaviour

When attempting to import a SpanGroup object [as exemplified in the documentation](https://spacy.io/api/spangroup#init), spaCy raises an ImportError.

```
ImportError: cannot import name 'SpanGroup' from 'spacy.tokens' (/Users/xxxx/virtualenv/lib/python3.8/site-packages/spacy/tokens/__init__.py)
```

If this is simply because the SpanGroup class is not imported from `.span_group`, then I could try to fix this myself. 

I've never contributed code to a big library like this, but would be willing to give it a try.

## My environment

* Operating System: macOS-10.14.6-x86_64-i386-64bit
* Python Version Used: 3.8.5
* spaCy Version Used: 3.0.3

**Comment by polm** [comment]
Ah, sorry you ran into that - that's been fixed in the latest version, 3.0.5, so if you upgrade it should be fine.

The fix was merged in #7182.
