### ISSUE TITLE
Multiprocessing documentation is missing in Spacy 3.0

### ISSUE THREAD

**Issue by f0lie** [explosion/spaCy#7470]
## Which page or section is this issue related to?

https://spacy.io/usage/examples#multi-processing

Some documentation out there refers to this link but redirects to https://spacy.io/usage/projects . Also, if you use the search bar and look up `multiprocessing`, the link shows up but redirects to projects instead. You can go to Spacy 2 docs and find the documentation so I think it's an issue from the updating to Spacy 3.0.

Also, a related issue is that the multiprocessing example doesn't mention how `pipe`'s `n_process` argument can be used to get multiprocessing instead of using `joblib`. Plus, I think the documentation should mention that spawning processes in Windows is much slower than Linux. I gave some hard numbers here: https://github.com/explosion/spaCy/issues/6700 .

**Comment by pmbaumgartner** [comment]
Adding a +1 here. The only documentation I found was on the migrating to 3.0 page.

I can make a separate issue for this, but feel like it might be something to be documented as well: It looks like `n_process` freezes when using transformer models. 

```python
import spacy
nlp = spacy.load("en_core_web_trf")

[d for d in nlp.pipe(["this is a sentence."] * 2, n_process=2)] # have to keyboard interrupt

%time [d for d in nlp.pipe(["this is a sentence."] * 2, n_process=1)]
CPU times: user 148 ms, sys: 78.2 ms, total: 226 ms
Wall time: 231 ms
```

Also note the first time this is run, it gives a warning about setting the `TOKENIZERS_PARALLELISM` environment variable, which I also did before testing again:

```
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
```

**Comment by adrianeboyd** [comment]
Thanks for the notes, we'll have a look at the docs to see how we can expand them on this topic.

That kind of runtime difference for `spawn` vs. `fork` is expected. You can have multiprocessing use spawn in linux, too, to see similar behavior with `multiprocessing.set_start_method("spawn")`. Multiprocessing is not always beneficial for short tasks, where short is usually something on the order of seconds to a few minutes. The startup costs for multiprocessing can be very high, especially with `spawn` with large models with vectors, so using `nlp.pipe` and 1 process can often be faster for a short task.

The transformers issue is most likely a known torch issue (deadlock related to libgomp), see: https://github.com/explosion/spaCy/issues/7470
