### ISSUE TITLE
Training a new parser or NER using a model with no lexeme normalization table.

### ISSUE THREAD

**Issue by drisspg** [explosion/spaCy#7487]
## Your Environment

- Operating System: Mac OS Big Sur 11.2.3
- Python Version Used: 3.7.9
- spaCy Version Used: spacy==3.0.5, spacy-lookups-data==1.0.0
- Environment Information:

I am running the training CLI script `python -m spacy train --verbose` and am seeing this Debug Statement even though I already installed space-lookups-data: ```Training a new parser or NER using a model with no lexeme normalization table. This may degrade the performance of the model to some degree. If this is intentional or the language you're using doesn't have a normalization table, please ignore this warning. If this is surprising, make sure you have the spacy-lookups-data package installed. The languages with lexeme normalization tables are currently: da, de, el, en, id, lb, pt, ru, sr, ta, th```

My training pipeline: Pipeline: ['tok2vec', 'ner', 'textcat_multilabel']
Added vectors: en_core_web_lg

Not sure why I am still seeing this debug statement.

**Comment by adrianeboyd** [comment]
Ah, we need to update this error message a bit more to give the config details. In v2 it was added automatically if `spacy-lookups-data` was installed, but in v3 it's not. To load the table, you need to modify your config as follows to edit the `initialize.lookups` setting:

```ini
[initialize.lookups]
@misc = "spacy.LookupsDataLoader.v1"
lang = ${nlp.lang}
tables = ["lexeme_norm"]
```

**Comment by drisspg** [comment]
That worked for me, thank you for the help!
