### ISSUE TITLE
require_gpu() + retokenize = AttributeError: module 'cupy' has no attribute 'delete'

### ISSUE THREAD

**Issue by rmalouf** [explosion/spaCy#7507]
retokenizer.merge( ) wth GPU enabled calls delete method, which isn't unsupported by cupy (cf. #5494)

## How to reproduce the behaviour

```import spacy
spacy.require_gpu()
nlp = spacy.load("en_core_web_sm")
doc = nlp("just an example")
spans = list(doc.noun_chunks)
spans = spacy.util.filter_spans(spans)
with doc.retokenize() as retokenizer:
    for span in spans:
        retokenizer.merge(span)
```

## Info about spaCy

- **spaCy version:** 3.0.5
- **Platform:** Linux-3.10.0-1160.21.1.el7.x86_64-x86_64-with-glibc2.10
- **Python version:** 3.8.6
- **Pipelines:** en_core_web_sm (3.0.0), en_core_web_lg (3.0.0)

**Comment by polm** [comment]
Thanks for reporting that, it looks like this is the line at issue.

https://github.com/explosion/spaCy/blob/66ebd5c69e811c851bc8838115d68015319f9fd2/spacy/tokens/_retokenize.pyx#L297
