### ISSUE TITLE
Bug: Spacy uses extremem amount of memory when loading language. 

### ISSUE THREAD

**Issue by follnoob** [explosion/spaCy#751]
When I load a language with spacy.load() it fills my memory up to 2,5gb (max amount of currently free memory).  It also happens in Python 2.7

python3 is the process where spacy is run.
![spacy_taskmgr](https://cloud.githubusercontent.com/assets/15342895/22058827/b3df51c2-dd6a-11e6-9326-034a497183d6.png)

## Your Environment

* Operating System: Ubuntu 14.04
* Python Version Used: 3.4.3, 2.7.6
* spaCy Version Used: 1.6.0
* Environment Information: 
  - 4gb memory
  - Intel(R) Core(TM) i5 CPU 4x2.67GHz

**Comment by follnoob** [comment]
Forgot to download modal for python2 and english. I updated my problem.

**Comment by honnibal** [comment]
That's currently just the nature of the beast. spaCy 2.0 will use less memory, by replacing the linear model with neural networks. You can use less memory by disabling some of the functionality.
