### ISSUE TITLE
usage: token sentiment

### ISSUE THREAD

**Issue by davidsbatista** [explosion/spaCy#7515]
is the token sentiment a property that comes already with the models or just a place holder for some other operation that you have to do in order to have a sentiment associated to each token?

Currently it seems it's always `0.0`

```
import spacy
from spacy.lang.en.examples import sentences

nlp = spacy.load("en_core_web_lg")
doc = nlp(sentences[0])
print(doc.text)
for token in doc:
    print(token.text, token.sentiment, token.pos_, token.dep_)
```

```
Apple is looking at buying U.K. startup for $1 billion
Apple 0.0 PROPN nsubj
is 0.0 AUX aux
looking 0.0 VERB ROOT
at 0.0 ADP prep
buying 0.0 VERB pcomp
U.K. 0.0 PROPN compound
startup 0.0 NOUN dobj
for 0.0 ADP prep
$ 0.0 SYM quantmod
1 0.0 NUM compound
billion 0.0 NUM pobj

```

**Comment by polm** [comment]
Good question. The `sentiment` property has been in spaCy a long time but I don't think it's used in any of the pretrained models currently. There's instructions on how to set it in [some old docs](https://github.com/explosion/spaCy/blob/dfb23a419ee0410f5ef0ce8ebd8b031cd5790e2d/website/docs/usage/v2-3.md#user-content-load-and-save-extra-prob-lookups-table:~:text=If%20you'd%20like%20to%20include%20custom%20cluster%2C%20prob%2C%20or%20sentiment%20tables%20as), though it looks like it should still work. You can include it as an extra table in the lookup data and it will be applied to every token.
