### ISSUE TITLE
Is it possible to train a new label with 'en_core_web_trf' model

### ISSUE THREAD

**Issue by rammohanrrr** [explosion/spaCy#7525]
Am able to train a new label to 'sm' model.

How ever, while I training 'md' / 'lg' / 'trf' models, 
am getting error """site-packages\spacy_transformers\layers\listener.py, line 47, in verify_inputs     raise ValueError""" at nlp.update()

Can I get suggestions here

Thanks

**Comment by polm** [comment]
Hey, sorry to hear you're having trouble with this. This looks like a good fit for our discussions board so I'm going to move this there.
