### ISSUE TITLE
Out-of-vocabulary items tagged as personal pronouns

### ISSUE THREAD

**Issue by adam-ra** [explosion/spaCy#753]
Spacy (1.6.0) has a tendency to tag unknown words as pronouns.
For instance: “feels hot/feverish” is tokenised as two tokens and ‘hot/feverish’ is tagged as PRP.

Personal pronouns are closed-class words and it is very unlikely that any new personal pronoun will get introduced to the language, so it would be an improvement if the statistical model was somehow tamed not to produce these eagerly. Probably the same applies to other closed classes, for instance prepositions.

**Comment by honnibal** [comment]
This really sounds like a bug.

**Comment by adam-ra** [comment]
I confirm that prepositions also crop up, e.g., “I feel overexcited” -> ‘overexcited’ tagged as “IN”

**Comment by ines** [comment]
Closing this and making #1057 the master issue – work in progress for spaCy v2.0!
