### ISSUE TITLE
In Spacy 3.0,the rel_component pipeline has pretrained model to transform doc to the NER relations such as visit 、arrive or live?

### ISSUE THREAD

**Issue by 13360806188** [explosion/spaCy#7531]
I have study the introduction about "Example: Entity relation extraction component".I can run the project tempate https://github.com/explosion/projects/tree/v3/tutorials/rel_component,and i can transform the doc ,find the relations of two entities.But I find the the annotions is about the biology,it is not I want to do.I want to find the relations of two entites such as someone visit some place，someone live in someplace.I know from the introduction viedo https://youtu.be/8HL-Ap5_Axo that Spacy 3.0 can get visit relation.
how can I do? do you have the pretrained model about the relations such as visit 、arrive or live?

Please help me ,thanks.

## Your Environment

- Operating System:Centos 7
- Python Version Used: 3.8.3
- spaCy Version Used:3.0
- Environment Information:

**Comment by polm** [comment]
We do not have a pretrained model about visiting / arriving / living somewhere. 

In order to make a model like that you'd need to create your own training data and train a model with it, though you should be able to use the relation extraction architecture as is.
