### ISSUE TITLE
Error while training NER pipe with 'en_core_web_trf' model

### ISSUE THREAD

**Issue by rammohanrrr** [explosion/spaCy#7538]
Am able to train a new label to 'sm' model.

How ever, while I training 'md' / 'lg' / 'trf' models,
am getting error """site-packages\spacy_transformers\layers\listener.py, line 47, in verify_inputs raise ValueError""" at nlp.update()

# Here is my code,

TRAIN_DATA = [ ('Who is Kamal Khumar?', {
        'entities': [(7, 19, 'MAN')]}) ]

model = "en_core_web_trf"
nlp = spacy.load(model)  # load existing spaCy model
print("Loaded model '%s'" % model)
ner = nlp.get_pipe("ner")

for text, annotations in TRAIN_DATA:
    for ent in annotations.get("entities"):
        ner.add_label(ent[2])

pipe_exceptions = ["ner", "trf_wordpiecer", "trf_tok2vec"]
other_pipes = [pipe for pipe in nlp.pipe_names if pipe not in pipe_exceptions]

with nlp.disable_pipes(*other_pipes):  # only train NER
    examples = []
    optimizer = nlp.resume_training()
    for text, annots in TRAIN_DATA:
        examples.append(Example.from_dict(nlp.make_doc(text), annots))
    for itn in range(n_iter):
        random.shuffle(examples)
        losses = {}
        for batch in minibatch(examples, size=compounding(4.0, 16.0, 1.001)):
            nlp.update(batch, sgd=optimizer, drop=0.2, losses=losses)
        print('losses : ', losses)

**Comment by adrianeboyd** [comment]
Hi, please don't open duplicate issues/threads. Let's keep this in the existing discussion thread: https://github.com/explosion/spaCy/discussions/7526
