### ISSUE TITLE
coercing to Unicode: need string or buffer, Series found 

### ISSUE THREAD

**Issue by Rahulvks** [explosion/spaCy#754]
Am facing error when loading text for preprocessing. 

`Amazon_Meta_Data = pd.read_csv("/home/nlp/Downloads/Amazon_Unlocked_Mobile.csv",encoding='utf_8')`
`sample_review = Reviews[:2000]`
`sample_review = sample_review.replace('\\n', '\n')`
```
with codecs.open(sample_review, encoding='utf_8') as f:
    sample_review = sample_review.replace('\\n', '\n')
print sample_review
```
`parsed_review = nlp(sample_review)`

**TypeError: coercing to Unicode: need string or buffer, Series found**

I passed encoding also. 

## Your Environment

* Operating System: Ubuntu 14.0
* Python Version Used: 2.7 Jupiter /Ipython
* spaCy Version Used: spacy 1.6.0
* Environment Information:

**Comment by honnibal** [comment]
Hi,

Your data is in the form of a `pandas.Series` object. spaCy expects a `unicode` string. The error you're seeing is the expected behaviour. The pandas docs should help you get a string value from the cells you need.

Matt

**Comment by Rahulvks** [comment]
How can correct this error ?
Can you help to correct this
