### ISSUE TITLE
Example dependency matching on spacy website not working

### ISSUE THREAD

**Issue by rishkum** [explosion/spaCy#7540]
Code from tutorial: https://spacy.io/usage/rule-based-matching#dependencymatcher 

```
import spacy
import en_core_web_sm
from spacy.matcher import DependencyMatcher
nlp = en_core_web_sm.load()


matcher = DependencyMatcher(nlp.vocab)

pattern = [
    {
        "RIGHT_ID": "anchor_founded",
        "RIGHT_ATTRS": {"ORTH": "founded"}
    },
    {
        "LEFT_ID": "anchor_founded",
        "REL_OP": ">",
        "RIGHT_ID": "founded_subject",
        "RIGHT_ATTRS": {"DEP": "nsubj"},
    },
    {
        "LEFT_ID": "anchor_founded",
        "REL_OP": ">",
        "RIGHT_ID": "founded_object",
        "RIGHT_ATTRS": {"DEP": "dobj"},
    },
    {
        "LEFT_ID": "founded_object",
        "REL_OP": ">",
        "RIGHT_ID": "founded_object_modifier",
        "RIGHT_ATTRS": {"DEP": {"IN": ["amod", "compound"]}},
    }
]

matcher.add("FOUNDED", [pattern])
doc = nlp("Lee, an experienced CEO, has FOUNDED two AI startups.")
matches = matcher(doc)

print(matches) 
```

 - result I should get [(4851363122962674176, [6, 0, 10, 9])]

What I get is this []

## Info about spaCy

- **spaCy version:** 3.0.5
- **Platform:** Windows-10
- **Python version:** 3.6.13
- en_core_web_sm = 3.0.0

**Comment by polm** [comment]
It looks like the issue here is that you have used `FOUNDED` in your input sentence, and that is causing it to be detected as a proper noun rather than a verb. 

So rather than this:

> Lee, an experienced CEO, has FOUNDED two AI startups.

If you use this:

> Lee, an experienced CEO, has founded two AI startups.

It works as intended. 

The spaCy models are trained to not be overly sensitive to changes in case, but that's a pretty unusual example, so it's not entirely surprising it confuses the models.

**Comment by adrianeboyd** [comment]
As an additional note, the first node in the pattern matches the token as `{"ORTH": "founded"}` which is why it doesn't match `FOUNDED`. You could modify the pattern to use `LOWER` to be case-insensitive.
