### ISSUE TITLE
add my project  to template format

### ISSUE THREAD

**Issue by myeghaneh** [explosion/spaCy#7547]
I want to add my project which is a custom NER (with standard tagger and dep of sm model), in this project, I have provided 

dev.spacy
train.spacy 
 

I have followed this  template 

https://github.com/explosion/projects

tutorials/ner_fashion_brands

but as you here, this template is kind of starting from the zero, 

since I have my data, as well as model, how can I use a template for my case?

**Comment by polm** [comment]
Since this is more of a usage question I'm going to move it to our Discussion board. Follow the link at the bottom of this issue to see the thread there.
