### ISSUE TITLE
Bug: spacy.de.download --force throws exception

### ISSUE THREAD

**Issue by follnoob** [explosion/spaCy#755]
The command spacy.de.download --force throws following exception:
- NameError: name 'shutil' is not defined

after looking in the file download.py I found out that you forgot to import shutils

## Your Environment

* Operating System: Ubuntu 14.04
* Python Version Used: 3.4.3
* spaCy Version Used: 1.6.0
* Environment Information:

**Comment by honnibal** [comment]
Thanks, fixed!
