### ISSUE TITLE
Update Spacy version in Anaconda distribution

### ISSUE THREAD

**Issue by iron0012** [explosion/spaCy#756]
[It appears that the most recent version of Spacy on Anaconda is 0.101.0, ](https://anaconda.org/spacy/spacy) which by now is many months old, and several versions behind. Many people (including myself) prefer to manage Python packages using Anaconda rather than Pip. Would you please consider updating the version of Spacy on Anaconda, and keeping it up-to-date going forward? Thanks!

**Comment by honnibal** [comment]
Replied on #778 — closing this to keep the discussion in one place :)
