### ISSUE TITLE
How can I design my own entities, entity types, color to visualize the text in spacy without nlp just mark? 

### ISSUE THREAD

**Issue by YijianLiu** [explosion/spaCy#7577]
Thanks to your so nice visualize, but now I just want mark the text only but no use nlp, for example,
I give the sentence: Mike likes dog, and then I input data:
{ent: 'like', type: 'PERSON', color:'#D2423'} 
{ent: 'dog, type: 'LOC', color:'#E3213'} 
Then it will mark like as PERSON and dog as LOC,
I really want to use your nice mark functino without doing any other nlp,
many thanks~ HELPHELPHELP!

**Comment by polm** [comment]
This sounds more like a usage question so I'm going to move it to our Discussions forum.
