### ISSUE TITLE
ParserStateError

### ISSUE THREAD

**Issue by muthupl** [explosion/spaCy#758]
Hi,

We are getting a parser state error. 
Here is our test:

```
nlp = spacy.en.English()
nlp.matcher.add('splash', 'my entity', {},[ [{LEMMA: 'splash'}, {LEMMA: 'on'}]])
nlp('splash On')
```
Here is the trace:
```
Traceback (most recent call last):
File "lib/python3.5/site-packages/spacy/language.py", line 328, in call
proc(doc)
File "spacy/syntax/parser.pyx", line 146, in spacy.syntax.parser.Parser.call (spacy/syntax/parser.cpp:6114)
spacy.syntax.parser.ParserStateError: Error analysing doc -- no valid actions available. This should never happen, so please report the error on the issue tracker. Here's the thread to do so --- reopen it if it's closed:
#429
Please include the text that the parser failed on, which is:
'splash On'
```

Our spacy version: spacy==1.3.0
Python 3.5.1
Mac OSX EI Capitan

Any help or fix is much appreciated! Let us know if you need more details.

**Comment by honnibal** [comment]
Thanks! Will investigate.

**Comment by ejschoen** [comment]
Hi.  Thanks for all your work.  For what it's worth, I'm running into the same issue in version 1.5.0.  I added a comment to issue #429 describing the code (match rule, with callback, doing a span merge) and the text I'm parsing, but I'm thinking that's not really the issue where it belongs.

**Comment by honnibal** [comment]
I think this is fixed now. The code in this `doc.merge()` method is still quite poor, and needs to be rewritten. But there's now a passing test for this specific issue. Thanks again for reporting!
