### ISSUE TITLE
Missing space at end of strings in NUM_WORDS

### ISSUE THREAD

**Issue by Derek-Jones** [explosion/spaCy#759]
The following code in spacy/orth.pyx

NUM_WORDS = set('zero one two three four five six seven eight nine ten'
                'eleven twelve thirteen fourteen fifteen sixteen seventeen'
                'eighteen nineteen twenty thirty forty fifty sixty seventy'
                'eighty ninety hundred thousand million billion trillion'
                'quadrillion gajillion bazillion'.split())

is missing a space character after ten, seventeen, seventy, trillion.

At the moment ten is not recognised as a number, but teneleven is treated as like_number.

**Comment by ines** [comment]
Thanks – will be pushing the fix and regression test in a second! Also, now that I see it, this data should probably be moved to the English language data at some point in the future.
