### ISSUE TITLE
Frozen tagger and parser making uninformed predictions

### ISSUE THREAD

**Issue by marc-poweruser** [explosion/spaCy#7599]
## How to reproduce the behaviour
I have a config with both frozen and trainable components as follows:
- Frozen components: transformer, tagger, and parser (all sourced from en_core_web_trf)
- Trainable components: transformer (named "trainable_transformer"), ner, textcat

I'm feeding the pipeline just 100 test Docs with some messy data and only training for 2 epochs.  During inference, I don't expect the trainable components to give intelligent answers, but I do expect the frozen components to work well.  Unfortunately, the frozen components provide similarly uninformed answers.  The parser sets the root token dep to ROOT, but all others to aux.  The tagger provides labels with more variety, but incredibly poor accuracy.

Shouldn't frozen components sourced from en_core_web_trf provide labels during inference you'd expect to see from en_core_web_trf regardless of data provided or training conducted?  Or am I missing something?

## config.cfg
```
[paths]
train = null
dev = null
vectors = null
init_tok2vec = null
model = "../models-v3"

[system]
gpu_allocator = "pytorch"
seed = 0

[nlp]
lang = "en"
pipeline = ["transformer","trainable_transformer","tagger","parser","ner","textcat"]
batch_size = 128
disabled = []
before_creation = null
after_creation = null
after_pipeline_creation = null
tokenizer = {"@tokenizers":"spacy.Tokenizer.v1"}

[components]

[components.ner]
factory = "ner"
moves = null
update_with_oracle_cut_size = 100

[components.ner.model]
@architectures = "spacy.TransitionBasedParser.v2"
state_type = "ner"
extra_state_tokens = false
hidden_width = 768
#64
maxout_pieces = 2
use_upper = false
nO = null

[components.ner.model.tok2vec]
@architectures = "spacy-transformers.TransformerListener.v1"
grad_factor = 1.0
pooling = {"@layers":"reduce_mean.v1"}
upstream = "trainable_transformer"

[components.textcat]
factory = "textcat"
threshold = 0.5

[components.textcat.model]
@architectures = "spacy.TextCatEnsemble.v2"
nO = null

[components.textcat.model.linear_model]
@architectures = "spacy.TextCatBOW.v1"
exclusive_classes = true
ngram_size = 1
no_output_layer = false
nO = null

[components.textcat.model.tok2vec]
@architectures = "spacy-transformers.TransformerListener.v1"
grad_factor = 1.0
pooling = {"@layers":"reduce_mean.v1"}
upstream = "trainable_transformer"

[components.parser]
source = "en_core_web_trf"

[components.parser.model]

[components.parser.model.tok2vec]
@architectures = "spacy-transformers.TransformerListener.v1"
grad_factor = 1.0
pooling = {"@layers":"reduce_mean.v1"}
upstream = "transformer"

[components.tagger]
source = "en_core_web_trf"

[components.tagger.model]

[components.tagger.model.tok2vec]
@architectures = "spacy-transformers.TransformerListener.v1"
grad_factor = 1.0
pooling = {"@layers":"reduce_mean.v1"}
upstream = "transformer"

[components.transformer]
source = "en_core_web_trf"

[components.trainable_transformer]
factory = "transformer"
max_batch_items = 4096
set_extra_annotations = {"@annotation_setters":"spacy-transformers.null_annotation_setter.v1"}

[components.trainable_transformer.model]
@architectures = "spacy-transformers.TransformerModel.v1"
name = "roberta-base"

[components.trainable_transformer.model.get_spans]
@span_getters = "spacy-transformers.doc_spans.v1"

[components.trainable_transformer.model.tokenizer_config]
use_fast = true

[corpora]

[corpora.dev]
@readers = "spacy.Corpus.v1"
path = ${paths.dev}
max_length = 0
gold_preproc = false
limit = 0
augmenter = null

[corpora.train]
@readers = "spacy.Corpus.v1"
path = ${paths.train}
max_length = 500
gold_preproc = false
limit = 0
augmenter = null

[training]
accumulate_gradient = 3
dev_corpus = "corpora.dev"
train_corpus = "corpora.train"
seed = ${system.seed}
gpu_allocator = ${system.gpu_allocator}
dropout = 0.1
patience = 1600
max_epochs = 2
#0 for unlimited
#60 for old standard
max_steps = 20000
eval_frequency = 200
frozen_components = ["transformer","tagger","parser"]
before_to_disk = null

[training.batcher]
@batchers = "spacy.batch_by_padded.v1"
discard_oversize = true
size = 2000
buffer = 256
get_length = null

[training.logger]
@loggers = "spacy.ConsoleLogger.v1"
progress_bar = false

[training.optimizer]
@optimizers = "Adam.v1"
beta1 = 0.9
beta2 = 0.999
L2_is_weight_decay = true
L2 = 0.01
grad_clip = 1.0
use_averages = false
eps = 0.00000001

[training.optimizer.learn_rate]
@schedules = "warmup_linear.v1"
warmup_steps = 250
total_steps = 20000
initial_rate = 0.00005

[training.score_weights]
dep_las_per_type = null
sents_p = null
sents_r = null
ents_per_type = null
cats_score_desc = null
cats_micro_p = null
cats_micro_r = null
cats_micro_f = null
cats_macro_p = null
cats_macro_r = null
cats_macro_f = null
cats_macro_auc = null
cats_f_per_type = null
cats_macro_auc_per_type = null
tag_acc = 0.25
dep_uas = 0.12
dep_las = 0.12
sents_f = 0.0
ents_f = 0.25
ents_p = 0.0
ents_r = 0.0
cats_score = 0.25

[pretraining]

[initialize]
vectors = null
init_tok2vec = ${paths.init_tok2vec}
vocab_data = null
lookups = null
before_init = null
after_init = null

[initialize.components]

[initialize.tokenizer]
```

## Your Environment
- **spaCy version:** 3.0.5
- **Platform:** Linux-4.14.219-164.354.amzn2.x86_64-x86_64-with-debian-buster-sid
- **Python version:** 3.6.13
- **Pipelines:** en_core_web_trf (3.0.0)

**Comment by adrianeboyd** [comment]
Hi, this is due to an internal implementation detail. The `transformer` component saves its predictions as `doc._.trf_data`, so what's happening is that `trainable_transformer` is overwriting this data with its predictions before `tagger` and `parser` have accessed it for their predictions.

Right now it looks like the only solution is to reorder the pipeline components so that transformer components are grouped with all the components that listen to them, so that the second transformer comes after all components that listen to the first one:

```ini
pipeline = ["transformer","tagger","parser","trainable_transformer","ner","textcat"]
```

You can configure the exact custom extension name (so not necessarily `trf_data`), but only globally, not per transformer component. Longer-term this could potentially be a config setting so that you can also have both transformer outputs saved in the doc at the end of the pipeline.

If you want data from both transformers at the end of the pipeline, I think you could currently use `set_extra_annotations` to copy it to another custom extension.

**Comment by marc-poweruser** [comment]
Ah, that makes sense.  Reordering the pipeline as follows gives the desired results:
```
pipeline = ["transformer","tagger","parser","trainable_transformer","ner","textcat"]
```

But I did notice something else when I tried to add the next piece of my pipeline, a parser to train on custom labels.  The idea is to have two parsers, one trained on standard labels (sourced from en_core_web_trf and frozen), and another trained on custom labels (named "custom_parser" below) that relies on a trainable transformer.  With two sets of resulting dep labels, I use a custom factory (named "move_dep" below) to move one set of dep labels to a custom extension so they aren't overwritten.

If I use the following pipeline ordering and a move_dep factory that saves the standard dep labels separately, it works great:
```
pipeline = ["transformer","tagger","parser","move_dep","trainable_transformer","custom_parser","ner","textcat"]
```

```
@Language.factory("move_dep")
class MoveDepComponent:
    def __init__(self, nlp, name):
        Token.set_extension("std_dep", default=None)
        Token.set_extension("std_dep_", default=None)

    def __call__(self, doc):
        for tok_idx, tok in enumerate(doc):
            doc[tok_idx]._.set("std_dep", tok.dep)
            doc[tok_idx]._.set("std_dep_", tok.dep_)
        return doc
```

But if I reverse the pipeline order as follows and have the move_dep factory save the custom dep label separately, I create a problem.  Now, the ROOT token ends up with an 'aux' dep label instead of 'ROOT' for the standard dep labels.  All other standard dep labels look good - just the ROOT is incorrect.

```
pipeline = ["trainable_transformer","custom_parser","move_dep","ner","textcat","transformer","tagger","parser"]
```

```
@Language.factory("move_dep")
class MoveDepComponent:
    def __init__(self, nlp, name):
        Token.set_extension("custom_dep", default=None)
        Token.set_extension("custom_dep_", default=None)

    def __call__(self, doc):
        for tok_idx, tok in enumerate(doc):
            doc[tok_idx]._.set("custom_dep", tok.dep)
            doc[tok_idx]._.set("custom_dep_", tok.dep_)
        return doc
```

Since I have an approach that works, it's not currently an issue for me.  But the behavior doesn't make sense to me so perhaps it's a bug?

In case you need it, here is the new portion of the config I'm using for the custom_parser and move_dep components:

```
[components.move_dep]
factory = "move_dep"

[components.custom_parser]
factory = "parser"
name = "custom_parser"
learn_tokens = false
min_action_freq = 30
moves = null
update_with_oracle_cut_size = 100

[components.custom_parser.model]
@architectures = "spacy.TransitionBasedParser.v2"
state_type = "parser"
extra_state_tokens = false
hidden_width = 128
maxout_pieces = 3
use_upper = false
nO = null

[components.custom_parser.model.tok2vec]
@architectures = "spacy-transformers.TransformerListener.v1"
grad_factor = 1.0
pooling = {"@layers":"reduce_mean.v1"}
upstream = "trainable_transformer"
```

**Comment by adrianeboyd** [comment]
The parser uses some information from the current state (mainly the sentence boundaries) in its predictions, so it's probably an interaction there. Try resetting the entire parse tree and sentence boundaries in the intermediate step to see if that solves the problem. For initial testing the python version would look like this:

```python
# reset entire dependency tree
for token in doc:
    token.dep = 0
    token.head = token
# then reset all sentence starts
for token in doc:
    token.is_sent_start = None
```

This will be slow because setting `token.head` recalculates a bunch of token features like left/right children and the sentence boundaries.

If you do this in practice, you'd want to do it in cython, which would look more like this:

```python
for i in range(doc.length):
    doc.c[i].head = 0
    doc.c[i].dep = 0
set_children_from_heads(doc.c, 0, doc.length)
for i in range(doc.length):
    doc.c[i].sent_start = 0
```

**Comment by marc-poweruser** [comment]
Resetting the dependency tree and sentence starts worked for fixing the dep ROOT prediction - thank you!
I'm having a problem using cython with spacy - it's not finding the cimport file I need despite the path being correct.  But I'll open a different issue for that if I can't get it to work.

**Comment by adrianeboyd** [comment]
There's a hard-coded list of cython modules in `setup.py`.
