### ISSUE TITLE
Support for numeric ranking words and fractions

### ISSUE THREAD

**Issue by Derek-Jones** [explosion/spaCy#760]
How about adding support for numeric ranking words and common fractions:

* first, second, third, fortieth, etc
* half, quarter, etc

Then of course there are the less straight forward cases, e.g., "several thousand", "thousands".
One usage for this functionality: http://shape-of-code.coding-guidelines.com/2017/01/22/full-fact-checking-of-number-words/

**Comment by ines** [comment]
Yes, this could definitely be added to the library by default. 

You can always add these manually, though, and set custom flags, like `is_fraction` etc. This isn't fully documented at the moment, but a usage tutorial is in the works (see #581).

**Comment by ines** [comment]
Merging this with #1439 – now the master issue for lexical attribute suggestions!
