### ISSUE TITLE
Weird Visualisations created when offsets aren't sorted

### ISSUE THREAD

**Issue by nawabhussain** [explosion/spaCy#7604]
## How to reproduce the behaviour

When visualizing the entity recognizer  using the sample code where the offsets aren't sorted, as shown below:
`
ex = [{"text": "But Google and FB are starting from behind.","ents": [{"start": 15, "end": 17, "label": "ORG"}, {"start": 4, "end": 10, "label": "ORG"}], "title": None}]`
`displacy.render(ex, style="ent", manual=True)`

results in the output:

> But Google and FB{ORG} Google{ORG} and FB are starting from behind

## Environment
- spaCy version    2.3.2
- Platform         Windows-10-10.0.17763-SP0
- Python version   3.8.5

**Comment by adrianeboyd** [comment]
Hi, having the offsets sorted is just a requirement for the manual option, see: https://spacy.io/usage/visualizers#manual-usage

**Comment by nawabhussain** [comment]
Thank you for the clarification. I missed that part.
