### ISSUE TITLE
Improved behaviour (and documentation) of DocBin.to_disk() with large corpora

### ISSUE THREAD

**Issue by arc12** [explosion/spaCy#7627]
The failure of DocBin to_disk() is seemingly well-known, e.g. discussion: #7061 
This is a bit of a WTF moment for newbies, especially when considering using the docbin output for training, as it isn't quickly obvious that you can pass a directory to train. Additionally, we're left guessing/experimenting about what "too large" looks like, so the chunking will be rather hit-or-miss.

Suggestion:
1. to_disk() either provides an option to automatically split output, or makes this the default, and takes an informed view of what the chunk size should be.
2. documentation of to_disk() explains this, and that giving a directory for paths.train works as it does.

**Comment by arc12** [comment]
thanks @svlandeg for your considered and educational reply.
I appreciate the call to make a PR, but I don't have the knowledge (yet?) to make a sensible contribution.

**Comment by svlandeg** [comment]
No worries. If you ever do feel like contributing, https://github.com/explosion/spaCy/blob/master/CONTRIBUTING.md#contributing-to-the-code-base has some pointers ;-)
