### ISSUE TITLE
Issue with importing spacy.pipeline: No module named pipeline 

### ISSUE THREAD

**Issue by ericzhao28** [explosion/spaCy#764]
I received this error on a fresh install of Spacy:
>>> import spacy
>>> import spacy.pipeline
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pipeline

spacy.pipeline is used in a number of spacy "examples" but it doesn't seem to exist. Has spacy.pipeline been renamed to something else?

**Comment by aikramer2** [comment]
There might be an issue with your environment or you could be using an old version of spacy. Can you provide some details like what version of python and spacy you're using?

**Comment by mattmacy** [comment]
There are a lot of channels still using version 0.10 which predates the pipeline implementation. You'll need to upgrade.

**Comment by ericzhao28** [comment]
Reinstalling and making sure I had the newest version fixed it - probably was using an outdated version. Thanks guys!
