### ISSUE TITLE
ModuleNotFoundError: No module named 'spacy.gold'

### ISSUE THREAD

**Issue by erotavlas** [explosion/spaCy#7659]
Our annotation tool outputs annotations in this format (I'm not sure what this format is called in the documentation - but it was present in many examples)

`[("""Run date: 11/12/15 1705               """,{'entities':[(10,18,'DATE')]}),("""NAME: LNAMEZ,FNAME             DOB: 12/12/1901   """,{'entities':[(6,18,'PERSON'),(36,46,'DATE')]})]`

For Spacy versions prior to 3.0 I was using the following code to convert the above annotations to jsonl format like this

```
import os
import spacy
import srsly
from spacy.gold import docs_to_json, biluo_tags_from_offsets, spans_from_biluo_tags

path_train = r'D:\training\'
file_train = os.path.join(path_train, 'FINALTRAIN')

file = open(file_train, mode='r')
all_text = file.read()
file.close()

TRAIN_DATA = eval(all_text)

nlp = spacy.load(r'D:\spacy_baseModel\1.0.0.4') 

docs_train = []
for text, annot in TRAIN_DATA:
    doc = nlp(text)
    tags = biluo_tags_from_offsets(doc, annot['entities'])
    entities = spans_from_biluo_tags(doc, tags)
    doc.ents = entities
    docs_train.append(doc)
	
srsly.write_json(os.path.join(path_train, 'finaltrain.json'), [docs_to_json(docs_train)])
```
Then I can use the output file in the command line argument to train the model.

However after running my code in a new environment with Spacy 3.0.5, at the beginning of the code at the imports I get the following error

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-16069662e278> in <module>
      1 import spacy
      2 import srsly
----> 3 from spacy.gold import docs_to_json, biluo_tags_from_offsets, spans_from_biluo_tags

ModuleNotFoundError: No module named 'spacy.gold'
```

If `apacy.gold` has been removed what changes can I make either to the code above, or to my data set format to get it working using the command line training?

**EDIT**: I see in the documentation that you have converted to an `Example` object, 

```
# Training data for an entity recognizer (option 2)
doc = nlp("Laura flew to Silicon Valley.")
gold_dict = {"entities": [(0, 5, "PERSON"), (14, 28, "LOC")]}
example = Example.from_dict(doc, gold_dict)
```

although it doesn't say it, it seems that a training  instance is considered to be the same as a sentence? Or does it represent the entire document with multiple sentences?

If the example provided only shows a single sentence of the document - how do we add more than one sentence?

**Comment by svlandeg** [comment]
This is a good question for the Discussions forum, so I'll move it there. The original issue will be closed and will link to the new open thread on the forum.
