### ISSUE TITLE
Unable to install Spacy 2.1.0 with Python 3.9.1

### ISSUE THREAD

**Issue by dimaelzein** [explosion/spaCy#7675]
I am unable to  install Spacy 2.1.0 with Python 3.9.1. with an error message "Could not find a version that satisfies..."
- Windows 10
- installing packaging from pip on cmd
- Recent versions of Spacy were working fine. But I have to downgrade to use neuralcoref 
- I already cleaned the environment and retried. Didn't work
- I already tried pip install spacy==2.1.0 --no-cache-dir. Didn't work

**Comment by adrianeboyd** [comment]
Let me move this to the install questions section in our discussion board. This issue will be locked, but the new discussion thread will remain open.
