### ISSUE TITLE
CLI command for assembling (but not training) a model

### ISSUE THREAD

**Issue by kinghuang** [explosion/spaCy#7686]
We've recently upgraded to spaCy thanks for the commercial support! We do a "two-phase" approach to building our language model, where the `ner` component is trained and versioned in one project, and then assembled with other components in another project.

The final assembly is being done by running [spacy train …](https://spacy.io/api/cli#train) with a [training config](https://spacy.io/api/data-formats#config) that has every trainable pipeline component frozen. The goal of the assembly isn't to train any of the components, but to assemble a bunch of components together into a complete NLP model/package. However, using the `train` command requires train and dev data to be passed in and causes a training pipeline to run, even though there's no actual training being performed.

It would be useful if there was a command akin to `assemble`, that does all the package assembly that the `train` command does (e.g., collecting components and generating a Python package), without invoking any training.

## Your Environment

- Operating System: Debian 10 (python container)
- Python Version Used: 3.8.
- spaCy Version Used: 3.0.5
- Environment Information: N/A

**Comment by polm** [comment]
Thanks for the suggestion. Proposals go in Discussions these days, so I'll move this thread there.
