### ISSUE TITLE
How to use ner model outside spacy ?

### ISSUE THREAD

**Issue by ayush-raj7** [explosion/spaCy#7692]
Hi,
I am using spacy to train ner model. I want to use the model outside spacy. 
1.)  Is it possible to convert the model to a pytorch model  or any other format and then use it outside spacy?
2.)  How can I get the model weights (for the model components in ner model and whole model )?
3.)  Is it possible to get the component weights or extract the model weights and use it outside spacy using pytorch? 

I also want to deploy the model on tensor RT to be able run inference. Please let me know how can I do that as well?

**Comment by polm** [comment]
Hey, this looks like a topic for our discussion forums, so I'm going to move it there.
