### ISSUE TITLE
POS field is returning number

### ISSUE THREAD

**Issue by enod** [explosion/spaCy#770]
Hi all,

For any text like: 
"The Foreign Relations Senate Committee has narrowly approved Rex Tillerson as US secretary of state, despite concerns about his business ties to Russia.", "It split along party lines, with all 11 Republicans voting in favour and all 10 Democrats against. A full vote will now be held in the Republican-run Senate."
```
{
						"tag": "DT",
						"ner": "ORG",
						"oov": false,
						"lemma": "the",
						"url": false,
						"token": "The",
						"num": false,
						"offsets": {
							"end": 3,
							"begin": 0
						},
						**"pos": 87,**
						"email": false,
						"stop": true,
						"title": true
					},
```
POS tag suddenly changed to number instead of text. Is it updated in spacy 1.6? 

## Your Environment

* Operating System: Linux
* Python Version Used: 3.4
* spaCy Version Used: 1.6
* Environment Information: AWS beanstalk

**Comment by honnibal** [comment]
What code are you using to generate that output?
