### ISSUE TITLE
extract patterns out the the negated entities

### ISSUE THREAD

**Issue by hollywzw** [explosion/spaCy#7700]
Hi, how do we extract the patterns of the negations identified? Is there any standard methods of negex we can use?

Like if I want to know which negation pattern below was identified for the negated entity.

NegEx Patterns
psuedo_negations - phrases that are false triggers, ambiguous negations, or double negatives
preceding_negations - negation phrases that precede an entity
following_negations - negation phrases that follow an entity
termination - phrases that cut a sentence in parts, for purposes of negation detection (.e.g., "but")

**Comment by polm** [comment]
There's a 3rd-party plugin called [negspacy](https://github.com/jenojp/negspacy) based on negex.

**Comment by polm** [comment]
Ah, this is better for the Discussion board, so I'm going to migrate it there.
