### ISSUE TITLE
Improve Entity Ruler accuracy

### ISSUE THREAD

**Issue by aoleiReiz** [explosion/spaCy#7703]
## How to reproduce the behaviour

`nlp = spacy.load(model_dir)`
`nlp.add_pipe(nlp.create_pipe('sentencizer'))`
`ruler = EntityRuler(nlp)`
`patterns = generate_patterns_from_file()`
`ruler.add_patterns(patterns)`
`nlp.add_pipe(ruler)`

the model failed to extract most of the rule patterns, for example:
the model can identify "IKEA" as label "EXT-ORG", but after add the rule based pattern
 `{"label": "ORG-EXT", "pattern": [{"LOWER": "ikea ab"}]}` 
the model failed to extract it in text "ikea ab data lake"

## Your Environment

* Operating System: Windows 10
* Python Version Used: 3.6.8
* spaCy Version Used: 2.3.5
* Environment Information:

**Comment by adrianeboyd** [comment]
Let me move this to the discussion board, which is a better place for usage questions...
