### ISSUE TITLE
[Help need] Error in Entity linking Traing

### ISSUE THREAD

**Issue by aoleiReiz** [explosion/spaCy#7706]
## How to reproduce the behaviour

  File "C:/Users/aolei.bao/PycharmProjects/entity_linking_demo/src/el_train.py", line 271, in train
    sgd=optimizer,
  File "C:\Users\aolei.bao\Envs\ic_new\lib\site-packages\spacy\language.py", line 529, in update
    proc.update(docs, golds, sgd=get_grads, losses=losses, **kwargs)
  File "pipes.pyx", line 1270, in spacy.pipeline.pipes.EntityLinker.update
RuntimeError: [E188] Could not match the gold entity links to entities in the doc - make sure the gold EL data refers to valid results of the named entity recognizer in the `nlp` pipeline.

I used custom trained NER model for entity linking training, also I wrote script to make sure the entity ner model recoginzed has been annotated and contained in Knowledgebase, still getting this error, what else can i do to fix this training error, thanks

## Your Environment

* Operating System: Win10
* Python Version Used: 3.6.8
* spaCy Version Used: 2.3.5
* Environment Information:

**Comment by svlandeg** [comment]
Hi! As a maintenance note - this is a good question for the discussion forum, so I'll move it there. The original issue will be closed, but will link through to the new, open discussion thread.
