### ISSUE TITLE
can create_kb just build once when train the entity linking model

### ISSUE THREAD

**Issue by Zhou0418** [explosion/spaCy#7707]
## Your Environment

- Operating System:
- Python Version Used:
- spaCy Version Used:
- Environment Information:

**Comment by svlandeg** [comment]
Hi! As a maintenance note - this type of question is better suited for the discussion forum, so I'll move it there. The original issue will be closed, but will link through to the new, open discussion thread.

**Comment by svlandeg** [comment]
@Zhou0418 : can you elaborate a little on your question?

**Comment by Zhou0418** [comment]
> 
![image](https://user-images.githubusercontent.com/29883149/114155479-1f845180-9954-11eb-972a-94b8b7796670.png)
In spacy v2 we can create kb and save it.
But in spacy v3 we must put it with entity_linker train together as a function and can't save KB only
it will be called every time when i train el model and cost much time to repeat the same thing!
