### ISSUE TITLE
Masking PROPN when training/predicting with textcat

### ISSUE THREAD

**Issue by fyamagata** [explosion/spaCy#7708]
General guidance says that masking PROPN before training/predicting with text classification models to prevent over-fitting to some PROPN entities. Some datasets such as GoEmotios previously masks PROPN, like [NAME]. But, Spacy's sample training code or dataset doesn't. Do I need to mask PROPN's previously, to avoid over-fitting or Spacy training code masks them by itself? Please provide a best practice on preprocessing text data.
Thank you.

**Comment by svlandeg** [comment]
Hi! As a maintenance note - this is a good question for the discussion forum, so I'll move it there. The original issue will be closed, but will link through to the new, open discussion thread.
