### ISSUE TITLE
Conflicting version of plac between setup.py and requirements.txt

### ISSUE THREAD

**Issue by raphael0202** [explosion/spaCy#771]
## Bug

In `requirements.txt`, we ask for `plac<0.9.3` and in `setup.py` for `plac`. As [plac 0.9.6 is released](https://pypi.python.org/pypi/plac), if we start by a `pip3 install -r requirements.txt` then `python3 setup.py install`, we get a conflicting version error.

As a side note, in `requirements.txt` we don't have a version requirement for `ujson`, but we do in `setup.py` (`ujson>=1.35`). It would be great to change this too.

## Your Environment
* spaCy Version Used: HEAD

**Comment by honnibal** [comment]
Thanks!
