### ISSUE TITLE
Bug in Norwegian tokenizer

### ISSUE THREAD

**Issue by katarkor** [explosion/spaCy#7721]
I recently updated spaCy from version 2.2.4 to 2.3.5 and noticed that words connected with slash in the middle didn't get split into 3 separate tokens anymore. I run Token explainer to see what was going on:
det      TOKEN
var      TOKEN
mange    TOKEN
menn/kvinner     TOKEN
på       TOKEN
foredraget       TOKEN
i        TOKEN
går      TOKEN 
Then I tried blank models in different languages and only the Norwegian one seemed to fail. I figured out that the change happened in version 2.3.0 after this change https://github.com/explosion/spaCy/commit/79737adb90f286ca5b9be6e1020ea5b1855eed58. I compared the code for Danish and Norwegian and it turned out that the Danish version of punctuation.py had an extra infix regex. When I just pasted it in to the Norwegian version it worked as it should:
det      TOKEN
var      TOKEN
mange    TOKEN
menn     TOKEN
/        INFIX
kvinner          TOKEN
på       TOKEN
foredraget       TOKEN
i        TOKEN
går      TOKEN

So that seems to fix the issue (should I create a pull request for that? If so please help me a bit with that, I'm not good at git), but I'm wondering why it worked before without this regex. I suspect it could have something to do with token_match, but I'm not sure.

## How to reproduce the behaviour
1. Use a blank Norwegian model (version 2.3.0+) on a text with "/" splitting 2 words, like "det var mange menn/kvinner på foredraget i går" and check how the sentence is split into tokens, e.g. with 
```
nlp.tokenizer.explain("det var mange menn/kvinner på foredraget i går")
```
2. Add
```
r"(?<=[{a}0-9])[:<>=/](?=[{a}])".format(a=ALPHA),
```
to the list of infixes in spacy/lang/nb/punctuation.py and run tokenizer.explain again.

## Your Environment
* Operating System: macOS Catalina 10.15.7
* Python Version Used: 3.6
* spaCy Version Used: 2.2.4, 2.3.0, 3.0.5

**Comment by adrianeboyd** [comment]
Hi, sorry for the late reply!

It does look like this edit would improve the Norwegian tokenizer for UD_Norwegian-Bokmaal, so we'd be happy to accept a PR. For a simple edit like this, you can probably just do it in the github web UI if you'd like:

* Fork the repo by clicking "Fork" in the upper righthand corner, if you haven't already
* In your fork (your username in the github URL), browse through the repo to the file you want to edit, click the edit button, and make the changes
* Choose the "Create a new branch" option when saving and then when you click on "Propose changes" it creates a PR

Here's a tutorial with screenshots: https://docs.github.com/en/github/managing-files-in-a-repository/editing-files-in-your-repository
