### ISSUE TITLE
Span doesn't align with start and end id when '-' is performed in the text. 

### ISSUE THREAD

**Issue by effyli** [explosion/spaCy#7727]
Currently I am using SpaCy visualizer and the Span class to visualize self-defined entity mentions. 
However I found out that when a token has '-' in it, the token will be split into three parts and therefore the visualization doesn't align with the ids anymore. 

## How to reproduce the behaviour
```
import spacy
from spacy import displacy
from spacy.tokens import Span

nlp = spacy.load("en_core_web_sm")
text = "A light earthquake has struck Northern California , and there are no reports of injuries or damage . The U.S. Geological Survey says the 4.4-magnitude temblor on Sunday at 9:27 a.m. was centered 23 miles north of Santa Rosa , and two miles from The Geysers . "
t = nlp(text)
print(t)
new_span = Span(t, 24, 25, "ent")
t.set_ents([new_span])
displacy.serve(t, style="ent")
```

As you can see in the result, only '4.4' is highlighted instead of '4.4-magnitude', which doesn't make sense to me.

**Comment by polm** [comment]
This is not a bug, and looks like a good fit for our Discussion board, so I'll move it there.
