### ISSUE TITLE
ValueError: [E966] `nlp.add_pipe` now takes the string name of the registered component factory, not a callable component. Expected string, but got <spacy.pipeline.sentencizer.Sentencizer object at 0x000001CA1A69DF00> (name: 'None').

### ISSUE THREAD

**Issue by dalalBerrezoug** [explosion/spaCy#7741]
i don't understand the error
my code:
def getSentences(text):
    nlp = English()
    nlp.add_pipe(nlp.create_pipe('sentencizer'))

    document = nlp(text)
    return [sent.string.strip() for sent in document.sents]

the error:

   sentences = getSentences(text)
  File "C:\Users\***\PycharmProjects\tutospacy\main.py", line 8, in getSentences
    nlp.add_pipe(nlp.create_pipe('sentencizer'))
  File "C:\Python\Python39\lib\site-packages\spacy\language.py", line 749, in add_pipe
    raise ValueError(err)
ValueError: [E966] `nlp.add_pipe` now takes the string name of the registered component factory, not a callable component. Expected string, but got <spacy.pipeline.sentencizer.Sentencizer object at 0x000001CA1A69DF00> (name: 'None').

- If you created your component with `nlp.create_pipe('name')`: remove nlp.create_pipe and call `nlp.add_pipe('name')` instead.

- If you passed in a component like `TextCategorizer()`: call `nlp.add_pipe` with the string name instead, e.g. `nlp.add_pipe('textcat')`.

- If you're using a custom component: Add the decorator `@Language.component` (for function components) or `@Language.factory` (for class components / factories) to your custom component and assign it a name, e.g. `@Language.component('your_name')`. You can then run `nlp.add_pipe('your_name')` to add it to the pipeline.

my Environment
- **spaCy version:** 3.0.5
- **Platform:** Windows-10-10.0.19041-SP0
- **Python version:** 3.9.4
- **Pipelines:** en_core_web_sm (3.0.0)

**Comment by polm** [comment]
Moving this to discussions.
