### ISSUE TITLE
[spaCy 3.0] NER training metrics zeroed-out

### ISSUE THREAD

**Issue by fapbatista** [explosion/spaCy#7752]
## Your Environment

- Operating System: Ubuntu 20.04
- Python Version Used: Python 3.8.8 on Anaconda env
- spaCy Version Used: 3.0.5
- Environment Information: Using GPU for training CUDA 10.2

I'm training a custom NER model (not using pipelines though, I'm using my own custom training loop as I used to do on spaCy 2.0). I partitioned my dataset in train/dev/test, I'm training on train set and evaluating on dev set each iteration. I keep getting zeroed metrics for ent_* key on Scorer object. Has anyone experienced any issues regarding NER metrics? 

Version 2.3.5 with a very similar approach seems to deliver metrics correctly.

Thanks on advance!

**Comment by svlandeg** [comment]
Hi! As a maintenance note - this type of question is well suited for the discussions forum, so I'll move it there. The original issue will be closed, but will link through to the open discussion.
