### ISSUE TITLE
'NameError: name 'Doc' is not defined' when trying to create doc-object with Doc()

### ISSUE THREAD

**Issue by Ratatam123** [explosion/spaCy#776]
Hi,
I am trying to create some doc-object from a pretokenized text (= list of strings). I am following the example from https://spacy.io/docs/usage/processing-text.

Code-snippet:
from spacy import *
...
token_list = test_dataframe['token'].tolist()
nlp = spacy.load('en')
doc = Doc(nlp.vocab, words=token_list)
...

but I keep getting the error message: 'NameError: name 'Doc' is not defined'

Can anyone help me? If it's the wrong place for the question, let me know.

## Your Environment

* Operating System: OSx 10.11.3
* Python Version Used:  3.5
* spaCy Version Used: 1.6.0
* Environment Information:

**Comment by honnibal** [comment]
You need to do `from spacy.tokens import Doc`

Maybe `Doc` should be available in the top-level namespace. I'll think about this.

**Comment by Ratatam123** [comment]
Hi, thanks for the advice, this brought me a little further. However, how do I continue from there to have Spacy do any automatic text-processing (e.g. POS-tagging & dependency parsing)?

**Comment by ines** [comment]
@Ratatam123 Yes! You can check out the [usage workflows](https://spacy.io/docs/usage/) for examples and tutorials.
The [lightning tour](https://spacy.io/docs/usage/lightning-tour) is also a great place to get started and see code examples of spaCy in action.
