### ISSUE TITLE
Getting error while downloading language model

### ISSUE THREAD

**Issue by pratapwarrohit13** [explosion/spaCy#7761]
- Operating System: Win 10 64 Bit
- Python Version Used:  3.7
- spaCy Version Used: 3.0
- Environment Information: Base

I am getting below error when i try to download any language model from spacy
 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)'))': /explosion/spacy-models/releases/download/nl_core_news_sm-3.0.0/nl_core_news_sm-3.0.0-py3-none-any.whl

ERROR: Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /explosion/spacy-models/releases/download/nl_core_news_sm-3.0.0/nl_core_news_sm-3.0.0-py3-none-any.whl (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))

**Comment by polm** [comment]
Works fine here. Are you in a corporate network environment? If so you may need to [specify a proxy][proxy] or contact your IT department for help. 

If you are not in a corporate network environment, let us know and there are other things we can look into.

[proxy]: https://stackoverflow.com/questions/50960583/pip-install-fail-with-ssl-certificate-verify-failed-ssl-c833

**Comment by pratapwarrohit13** [comment]
Hi @polm I am using my company laptop but using on open network and I am administrator of Anaconda software but getting this error

**Comment by polm** [comment]
As a workaround, if you can download the file from the URL in your browser, you can install the file directly:

    pip install whatever.whl

Does that work?

I'm otherwise not sure why you would get this error. Most people who had it seem to have been affected when PyPI changed URLs a few years ago, but that's not relevant here. It could be something with your ISP I guess but that would be hard to troubleshoot...

**Comment by pratapwarrohit13** [comment]
![error](https://user-images.githubusercontent.com/14905985/114543664-1c9ca000-9c77-11eb-8536-4010b38aa6c8.JPG)
I received this error

**Comment by polm** [comment]
Please replace `whatever.whl` with the name of the file you download. This is the URL you were originally trying to download:

https://github.com/explosion/spacy-models/releases/download/nl_core_news_sm-3.0.0/nl_core_news_sm-3.0.0-py3-none-any.whl

**Comment by polm** [comment]
You can look at the releases [here](https://github.com/explosion/spacy-models/tags) for links to things, though it's probably easiest to just edit the URL.

Just a hunch, but could you try upgrading pip by running `pip install -U pip`?

**Comment by pratapwarrohit13** [comment]
Thanks I will use above link to download any model
