### ISSUE TITLE
Bug: The different punctuation at the end of a sentense lead analysis results wrong.

### ISSUE THREAD

**Issue by qingyun1988** [explosion/spaCy#7777]
## How to reproduce the behaviour

There is a sentence "Whose bike is broken?". However, the analysis result is wrong.
If I added a Chinese question mark "？" to the end of the sentence, the analysis result would be correct!
By multiple tests, I found that If I added different punctuation to the end of the sentence the analysis results would be different.
These different punctuations are "?", "？", "." and none.
The details are in the attached files. Please have a look at it.
How can I resolve the bug? thank you!

![2](https://user-images.githubusercontent.com/38597436/114651017-c7639b80-9d15-11eb-9a2c-e19e5a0558eb.png)
## Your Environment

* Operating System: windows 10
* Python Version Used: v3.7.8
* spaCy Version Used: v3.0 and the model version is en_core_web_trf 3.0
* Environment Information:

**Comment by polm** [comment]
Moving to a discussion.
