### ISSUE TITLE
Custom trained POS tagger pipeline tags pos as empty string.

### ISSUE THREAD

**Issue by Rolands-Laucis** [explosion/spaCy#7791]
## Which page or section is this issue related to?
https://spacy.io/usage/spacy-101#training

I trained a custom pipeline with tok2vec and tagger components. I want to do POS tagging for the Latvian language using word embeddings, that i've generated prior. I used the tool on [the usage site (https://spacy.io/usage/training) to generate the base_config file. Then went through the steps on CLI.
Filling in the defaults for config:
`python -m spacy init fill-config base_config.cfg config.cfg`
Converting my .conllu training files to .spacy:
`python -m spacy convert lv_lvtb-ud-test.conllu .\ --converter conllu`
Converting my embeddings into .spacy:
`python -m spacy init vectors lv ../../Models/SSG_model/ssg_5_200_sg.txt ../../Models/Spacy_tagger/vectors --name lv-ssg-5-200`
Then in that dir in the config added that output path under [Initialize] vectors = ...
Then ran the training like so:
`python -m spacy train config.cfg --output ../../Models/Spacy_tagger/ssg_5_200_pos --paths.train ./lv_lvtb-ud-train.spacy --paths.dev ./lv_lvtb-ud-dev.spacy`
Then in python run this code:
`import spacy

nlp = spacy.load("../../Models/Spacy_tagger/ssg_5_200_pos/model-last/")
doc = nlp("Es pārbaudu kā strādā šis kods.")

print(nlp.pipeline)

for token in doc:
    #print(token.text, token.pos)
    print(token.text, token.pos_)`

That outputs:
[('tok2vec', <spacy.pipeline.tok2vec.Tok2Vec object at 0x0000029654EA17C0>), ('tagger', <spacy.pipeline.tagger.Tagger object at 0x0000029654F8BE00>)]
Es
pārbaudu
kā
strādā
šis
kods 
.

Clearly the POS property of the token is "" and doing token.pos prints all of them 0.

What am i doing wrong? There were no errors in the training or other steps. I have read and reread the docs and dont understand. During training the accuraccy of tagger was 77% at the end.

**Comment by adrianeboyd** [comment]
Let me move this to the new discussion board...
