### ISSUE TITLE
💫 Lemmatizer should apply rules on OOV words

### ISSUE THREAD

**Issue by honnibal** [explosion/spaCy#781]
@juanmirocks points out in #327 that the lemmatizer fails on OOV words:

```python

>>> nlp.vocab.morphology.lemmatizer(u'endosomes', 'noun', morphology={'number': 'plur'})set([u'endosomes'])
>>> nlp.vocab.morphology.lemmatizer(u'chromosomes', 'noun', morphology={'number': 'plur'})
set([u'chromosome'])
```

Suggested patch to lemmatizer.py

```python

    oov_forms = []
    for old, new in rules:
        if string.endswith(old):
            form = string[:len(string) - len(old)] + new
            if form in index or not form.isalpha():
                forms.append(form)
            else:
                oov_forms.append(form)
    if not forms:
        forms.extend(oov_forms)
```

## Your Environment

* Operating System: 
* Python Version Used: 
* spaCy Version Used: 
* Environment Information:

**Comment by juanmirocks** [comment]
@honnibal thanks for looking into this -- Know I understand the problem better.

Looking forward to a fix as I think it will greatly improve the performance of my methods.

Kindly let me know if I can help with the patch.

**Comment by ines** [comment]
@juanmirocks If you have time to add the patch to `lemmatizer.py` and make a pull request, that would be great 👍  

The only thing that's important is to make sure it's properly tested. In this case, I think it'd be fine to just add a [regression test](https://github.com/explosion/spaCy/blob/master/CONTRIBUTING.md#fixing-bugs) for this issue, using the above examples.

**Comment by juanmirocks** [comment]
Thanks Ines.

I will gladly help and try. Is that patch code all what is necessary as per
decided for Hannibal?

I will dive in

**Comment by juanmirocks** [comment]
Other examples that I will use for debugging and testing:

* "colocalizes" is lemmatized the same, "colocalizes"
  * > PP2A colocalizes with shugoshin at centromeres and is required for centromeric protection .

**Comment by honnibal** [comment]
Merged!
