### ISSUE TITLE
how to split corpus into train/dev ?

### ISSUE THREAD

**Issue by d5555** [explosion/spaCy#7819]
Is it possible to add a feature to `Corpus` to get iterable according persentage from the start and from the end  so I can devide my dataset into train and dev ?
`train=Corpus (DATASET_Path ,   0.8 )` # 80%  from the start 
`dev=Corpus (DATASET_Path ,   -0.2 )` # 20%  from the end

There is an option `limit` but it won't work if we need to set a limit from the end (to get `dev` Corpus)

## Your Environment
- Operating System:
- spaCy Version Used: 3.0.5

**Comment by adrianeboyd** [comment]
We can consider whether more built-in options make sense here.

Currently your best option is write your own corpus reader. Here's what the provided one looks like:

https://github.com/explosion/spaCy/blob/ed561cf428494c2b7a6790cd4b91b5326102b59d/spacy/training/corpus.py#L22-L39

You'd want to modify the options and how the corpus is returned to split a single file into partitions.

**Comment by adrianeboyd** [comment]
Let me move this to the new discussion board...
