### ISSUE TITLE
Installing spacy-transformers on mac with m1 chip fails

### ISSUE THREAD

**Issue by JeffryCA** [explosion/spaCy#7829]
## How to reproduce the behaviour
pip install spacy-transformers

and also failing (no error it just gets stuck every time):

python -m spacy download de_dep_news_trf
 

## Your Environment

* Operating System: OS 11.2.3
* Python Version Used: 3.9 (conda)
* spaCy Version Used: 3.0.5

**Comment by adrianeboyd** [comment]
Hi, it looks like the current `spacy-transformers` (v1.0.1) was released before there was a version of `tokenizers` that can use a version of rust with support for the M1 architecture, so there's not a version of `tokenizers`+`transformers` that can be installed according to the `spacy-transformers` v1.0.1 requirements.

If you want to use it in the meanwhile, you will need to install rust (for `tokenizers` and `spacy-alignments`) and it's best to install pytorch separately first (probably: `conda install pytorch -c conda-forge`).

Then I think `pip install https://github.com/explosion/spacy-transformers/archive/master.zip` will work from the current `master` branch. There aren't many changes beyond extending the supported `transformers` version.

We can hopefully release the next version of `spacy-transformers` soon (will be v1.0.2) with support for newer versions of `tokenizers`.

**Comment by adrianeboyd** [comment]
Let me move this to the install section of the new discussion board...
