### ISSUE TITLE
Support for French tokenization exceptions

### ISSUE THREAD

**Issue by raphael0202** [explosion/spaCy#783]
I recently submitted a PR so that spaCy supports tokenization in French. I'm currently working to add the numerous tokenization exceptions existing in French.
With the help of wiktionary, I ended up with ~100k tokenization exceptions. 
You can find [here](https://github.com/explosion/spaCy/files/737066/tokenization_exceptions.gz) the gzipped exception file.

I first tried to directly load the gzipped file in `fr/language_data.py`, but it had a major impact on spaCy loading time: it took 2.0s just to `import spacy` (1.8s spent in `fr/language_data.py`).
By saving the processed `TOKENIZER_EXCEPTIONS` in a file with `numpy.save`, and loading it with `numpy.load`, it only took 0.8s to load `fr/language_data.py`. It's still too much, as this file is imported everytime spacy is loaded.

I wanted to have some insights from spaCy developers, in order to find a good solution concerning this tokenizer exceptions problem. One possibility would be to do lazy loading, by transforming `French.tokenizer_exceptions` into a lazy object which only imports the tokenizer exceptions if some of its methods (such as `.items()`) are called.

**Comment by honnibal** [comment]
Hmm!

Maybe we should have a frequency-pruned version of this in the `TOKENIZER_EXCEPTIONS`, and load the rest when you call `nlp = spacy.load('fr')`?

I'm sure the top 5k or top 10k entries here will give very good coverage. I would run this over the common crawl data here: http://statmt.org/ngrams/pages/raw-data.html

**Comment by raphael0202** [comment]
Do we actually need `TOKENIZER_EXCEPTIONS` to be loaded with spaCy or can we simply load it during `spacy.load('fr')`?

**Comment by honnibal** [comment]
We can load it during `spacy.load('fr')`. I'd like to ship decent tokenizer data with the library, though — I want to make sure people don't need to download anything just to use the library.

**Comment by oroszgy** [comment]
Guys, looked into the data, and it looks like that a decent amount of them could covered with good old regexes. (Maybe here: https://github.com/explosion/spaCy/pull/700) What do you think?

**Comment by honnibal** [comment]
If regular expressions work, that's a fine solution. I think to a great extent these things should be to the taste of the developer.

Thinking it through, the performance should actually be identical. The tokenizer will cache the result of every whitespace-delimited "chunk" it analyses, so long as the chunk consists of words in the vocabulary. This means that the regular expression will only have to match the chunks once --- after that they're in exactly the same cache that the tokeniser exceptions will load them into.

**Comment by raphael0202** [comment]
@oroszgy Yes indeed, it could solve this loading time issue, as many entries are highly similar (many verb declension). Shouldn't the documentation (Adding language) be updated to add this feature?

**Comment by honnibal** [comment]
You're right, that's definitely an oversight.

**Comment by ines** [comment]
@raphael0202 Good point, I can take care of adding this to the docs. I guess it should probably go in the "Custom tokenizer exceptions" section.

@oroszgy Since you've contributed the `token_match` functionality, would you be interested in writing up a short explanation (1-2 sentences) for the docs, or maybe a nice, simplified example from Hungarian? We could also do a little table instead that shows regex examples + match examples. I'm happy to do all the formatting/markup for the site, so plain text would be fine.

**Comment by raphael0202** [comment]
@oroszgy Hi, I have a question about your token_match feature. I've used it to specify tokens that should not be further splitted, and it works very well. But can I use it too in order to split tokens that match the same pattern in similar ways?
For instance the French expression `a-t-elle` must be tokenized into `['a', '-t', '-elle']`. Could I write a pattern like `([{alpha}]+)(-t)(-elle)`, with the parenthesis indicating the split position?

**Comment by oroszgy** [comment]
@raphael0202 Unfortunately, no. It is only for handling exceptions meaning that you can use that for preventing the affixes be split. (See the URL pattern which is used across languages.)

@ines Sure, will do that soon.
