### ISSUE TITLE
AttributeRuler for `is_stop` gets "cached"

### ISSUE THREAD

**Issue by maxtrem** [explosion/spaCy#7837]
## How to reproduce the behaviour

Hi, 
I was trying to add the word "order" as a stop word when it comes in the context "in order to".

I used the attribute ruler to make a rule for this however as soon as the attribute ruler is triggered all other tokens "order" are also marked as stop words, no matter in which context, see the example below.

**Code:**
```
import spacy, sys
nlp = spacy.load('en_core_web_sm')
ruler = nlp.get_pipe("attribute_ruler")

patterns = [
    {
        "patterns":[[{"LOWER": "in"}, {"LOWER": "order"}, {"LOWER": "to"}]],
        "attrs": {"IS_STOP": True},
        "index": 1,
    }
]

ruler.add_patterns(patterns)
print('Spacy Version:', spacy.__version__)
print('Python Version:', sys.version)

doc = nlp('in order')
print('doc:', doc)
for t in doc:
    print(f' - token: "{t}"  \t is_stop: {t.is_stop}')
print()
    
doc = nlp('order to')
print('doc:', doc)
for t in doc:
    print(f' - token: "{t}"  \t is_stop: {t.is_stop}')
print()

doc = nlp('in order to')
print('doc:', doc)
for t in doc:
    print(f' - token: "{t}"  \t is_stop: {t.is_stop}')
print()

doc = nlp('in order')
print('doc:', doc)
for t in doc:
    print(f' - token: "{t}"  \t is_stop: {t.is_stop}')
print()
    
doc = nlp('order to')
print('doc:', doc)
for t in doc:
    print(f' - token: "{t}"  \t is_stop: {t.is_stop}')
print()
```

**Output:**

```
Spacy Version: 3.0.5
Python Version: 3.8.2 (default, Mar 26 2020, 15:53:00) 
[GCC 7.3.0]
doc: in order
 - token: "in"  	 is_stop: True
 - token: "order"  	 is_stop: False

doc: order to
 - token: "order"  	 is_stop: False
 - token: "to"  	 is_stop: True

doc: in order to
 - token: "in"  	 is_stop: True
 - token: "order"  	 is_stop: True
 - token: "to"  	 is_stop: True

doc: in order
 - token: "in"  	 is_stop: True
 - token: "order"  	 is_stop: True   # should be False again

doc: order to
 - token: "order"  	 is_stop: True   # should be False again
 - token: "to"  	 is_stop: True
```

(I guess this is some kind of lookup and the attribute ruler might add "order" to the lookup once triggered?)

Is there some easy fix for this behaviour? If not, is there an alternative solution to archive this behaviour? 

Thanks!
/Max

## Your Environment

* Operating System: Ubuntu 20.04
* Python Version Used: 3.8.2 (default, Mar 26 2020, 15:53:00) 
[GCC 7.3.0]
* spaCy Version Used: 3.0.5

**Comment by maxtrem** [comment]
I was  actually able to solve the problem by adding another rule that generally sets the token `"order".is_stop` to `False`:

```
patterns = [
    {
        "patterns": [[{"LOWER": "order"}]],
        "attrs": {"IS_STOP": False},
    },
    {
        "patterns": [[{"LOWER": "in"}, {"LOWER": "order"}, {"LOWER": "to"}]],
        "attrs": {"IS_STOP": True},
        "index": 1,
    }
]
```

This of course is more inefficient than it needs to be, but it does the job. But it would probably be helpful mentioning this limitation somehow.

**Comment by adrianeboyd** [comment]
Hmm, I'm not sure that workaround is going to work?

`IS_STOP` is a `Lexeme` attribute, not a `Token` attribute, so there's just one lexeme entry for `order`, which is either a stop word or not.

(`NORM` is the only lexeme feature that's on both lexemes and tokens, so you can override `norm` for individual tokens.)

An alternative is to use a custom token extension to store whether individual tokens are stop words. It could back off to the lexeme attribute unless it's set.

**Comment by adrianeboyd** [comment]
Let me move this to a discussion thread...
