### ISSUE TITLE
My training stopped and I want to continue the training (I had saved on a file but didn't end to train)

### ISSUE THREAD

**Issue by keyssi93** [explosion/spaCy#7840]
I had use the basic config from spacy to train with trf 

`!python -m spacy train config.cfg --paths.train ./data/train-loc/ --paths.dev ./data/dev-loc/ --output ./spacy_train_location_8 --gpu-id 0
`
But it has stoped 
<img width="381" alt="Capture2" src="https://user-images.githubusercontent.com/49962161/115450319-5c1c3c80-a1e1-11eb-8a4d-473ff3e4b584.PNG">

I would like to know how to continue training that model to get better score 

## Your Environment
- Operating System:
- Python Version Used:Python 3.7.10
- spaCy Version Used:spacy v3.0
- Environment Information:pytorch_latest_p37

**Comment by polm** [comment]
Moving this to Discussions...
