### ISSUE TITLE
There is just one token, but the iterator would split it and loop twice

### ISSUE THREAD

**Issue by Amitdedhia6** [explosion/spaCy#7844]
## How to reproduce the behaviour
In the following code, I pass just one word to spacy nlp object. When we print the nlp object, it prints exactly that same word. But when we iterate the nlp object, it splits it and loops twice.

```
        nlp = spacy.load('en_core_web_lg')
        tokens = nlp('wont')
        print(tokens)               # prints wont  
        
        for token in tokens:
            print(token)    # prints two tokens -> wo and nt
```

## Your Environment

* Operating System: Windows 10 Pro
* Python Version Used: 3.8.6
* spaCy Version Used: 3.0.5
* Environment Information:

**Comment by adrianeboyd** [comment]
Hi, please don't open duplicate issues. The discussion board is a good place for this question: https://github.com/explosion/spaCy/discussions/7843
