### ISSUE TITLE
ValueError on nlp.set_kb() with SpaCy v3

### ISSUE THREAD

**Issue by bmiret-teklia** [explosion/spaCy#7848]
Hi,

I tried to follow the tutorial on Entity Linker training but I'm stuck at the training part with the following error when calling `set_kb()`: 

```
ValueError: [E885] entity_linker.set_kb received an invalid 'kb_loader' argument: expected a callable function, but got: <class 'spacy.kb.KnowledgeBase'>

```
The same code runs fine on spaCy 2.2.4 (with the "v2 version" lines). I tried to look at what changed in spaCy v3 but didn't see anything that could help (but real beginner here). Also, EntityLinker.set_kb is tagged as a new v3 feature in the documentation...?
Did I miss something?

## How to reproduce the behaviour

```
import spacy
from spacy.kb import KnowledgeBase

nlp = spacy.load("en_core_web_sm")

name_dict ={
    'Q312545': 'Roy Stanley Emerson',
    'Q48226': 'Ralph Waldo Emerson',
    'Q215952': 'Emerson Ferreira da Rosa'
}

desc_dict = {
    'Q312545': 'Australian tennis player',
    'Q48226': 'American philosopher, essayist, and poet',
    'Q215952': 'Brazilian footballer'
}

kb = KnowledgeBase(vocab=nlp.vocab, entity_vector_length=96)

for qid, desc in desc_dict.items():
    desc_doc = nlp(desc)
    desc_enc = desc_doc.vector
    kb.add_entity(entity=qid, entity_vector=desc_enc, freq=324)

for qid, name in name_dict.items():
    kb.add_alias(alias=name, entities=[qid], probabilities=[1])

qids = name_dict.keys()
probs=[0.3 for qid in qids]
kb.add_alias(alias="Emerson", entities=qids, probabilities=probs)

# v3 version
entity_linker = nlp.add_pipe("entity_linker", config={"incl_prior":False}, last=True)
entity_linker.set_kb(kb)

# # v2 version
# entity_linker = nlp.create_pipe("entity_linker", config={"incl_prior":False})
# entity_linker.set_kb(kb)
#  nlp.add_pipe(entity_linker, last=True)
```
## Info about spaCy

- **spaCy version:** 3.0.5
- **Platform:** Linux-4.15.0-136-generic-x86_64-with-Ubuntu-18.04-bionic
- **Python version:** 3.6.9
- **Pipelines:** en_core_web_sm (3.0.0)

Thanks!

**Comment by svlandeg** [comment]
Hi! As a maintenance note: this is a good question for the discussions forum, so I'll move it there. The original issue will be closed and will link through to the open discussion thread.
