### ISSUE TITLE
Entity Types

### ISSUE THREAD

**Issue by MalikRumi** [explosion/spaCy#7860]
It is a simple thing: I want a list of the built in named entity types. I’ve seen it before, but it isn’t memorized. But can I find it on your site, or in your documentation? No, I cannot. After many fruitless searches for “named entity list”, “default named entity types” and other variations that yield nothing, this is what I settle on:

_https://spacy.io/usage/linguistic-features#entity-types
Built-in entity types
Annotation scheme
For details on the entity types available in spaCy’s trained pipelines, see the “label scheme” sections of the individual models in the  models directory._

The string “label” is nowhere on this page! Neither is the string “scheme”! “Models”, as used on this page, refers to size
	_In the sm/md/lg models:_
or architecture
	_In the transformer (trf) models,_ 

On the left there is a list of “trained pipelines”, and it seems that this was where you intended to send us. Then the referring page should say *exactly* that, and not confuse us with terminology. There is no “models directory” here, either, by the way. 

_https://spacy.io/usage/linguistic-features#named-entities
“...The default trained pipelines …”_

This links to the same page, but at least gives us a better hint at where you expect us to go.
I will submit a pull request.

**Comment by polm** [comment]
Sorry you had a frustrating experience with this, and thank you for your suggestion about improving the docs. 

However, since the current docs already direct you to the pages for the individual models, I don't think there's need for a change here.
