### ISSUE TITLE
spacy default english tokenizer changes when re-assigned

### ISSUE THREAD

**Issue by gustavz** [explosion/spaCy#7866]
## Your Environment

* Operating System: macOS Mojave
* Python Version Used: 3.8.6
* spaCy Version Used: 3.0.5
* Environment Information: virtualenv

When you assign the tokenizer in spacy's (v3.0.5) english language model `en_core_web_sm` its own default tokenizer it changes its behaviour.

I would expect no change, but it silently fails. Why is this?

Code to reproduce:

    import spacy

    text = "don't you're i'm we're he's"

    # No tokenizer assignment, everything is fine
    nlp = spacy.load('en_core_web_sm')
    doc = nlp(text)
    [t.lemma_ for t in doc]
    >>> ['do', "n't", 'you', 'be', 'I', 'be', 'we', 'be', 'he', 'be']
    
    # Default Tokenizer assignent, tokenization and therefore lemmatization fails
    nlp = spacy.load('en_core_web_sm')
    nlp.tokenizer = spacy.tokenizer.Tokenizer(nlp.vocab)
    doc = nlp(text)
    [t.lemma_ for t in doc]
    >>> ["don't", "you're", "i'm", "we're", "he's"]

**Comment by gustavz** [comment]
To create a true default tokenizer it is necessary to pass all defaults to the tokenizer class not just the vocab:

rules = nlp.Defaults.tokenizer_exceptions
infix_re = compile_infix_regex(nlp.Defaults.infixes)
prefix_re = compile_prefix_regex(nlp.Defaults.prefixes)
suffix_re = compile_suffix_regex(nlp.Defaults.suffixes)

tokenizer = spacy.tokenizer.Tokenizer(
        nlp.vocab,
        rules = rules,
        prefix_search=prefix_re.search,
        suffix_search=suffix_re.search,
        infix_finditer=infix_re.finditer,
    )

**Comment by adrianeboyd** [comment]
Yes, this is basically correct. Be sure you include all the settings including `url_match` and `token_match`, too.

Be aware that the defaults from the current install of the `spacy` library (under `nlp.Defaults`, which here is `English.Defaults`) may differ slightly from the settings saved in the model (that the model was trained with, so it's important that they are exactly the same and why they're included in the model).

To get the exact same tokenizer:

```python
tokenizer = Tokenizer(nlp.vocab, rules=nlp.tokenizer.rules, prefix_search=nlp.tokenizer.prefix_search, ...)
# or just deserialize to get the same settings all copied at once
tokenizer = Tokenizer(nlp.vocab)
tokenizer.from_bytes(nlp.tokenizer.to_bytes())
```
