### ISSUE TITLE
Run Spacy like a process/server

### ISSUE THREAD

**Issue by Oxi84** [explosion/spaCy#787]
Hi,

Is it possible to run spacy like a process/server? If not i suggest to implement this feature, because if someone runs a script (on linux) and uses Spacy he has to wait for 10-20 sec for it to load each time the script is used. And if it is possible to run it like a server or cache it in memory it could be run instantly after it is loaded first.

Here is example of making a simple script runing like a process: http://stackoverflow.com/questions/16420092/how-to-make-python-script-run-as-service

Thanks

**Comment by raphael0202** [comment]
Hi,
You can easily create a web application encapsulating spacy, with a web framework such as [Flask](http://flask.pocoo.org/).

**Comment by oroszgy** [comment]
Look around here: https://github.com/explosion/spacy-services

**Comment by Oxi84** [comment]
I would like to try some of these examples but spacy worked just once on my pc, and after that I am getting memory errors each time I run it. Spacy seems to be using more than 2GB of memory and python 32 bit and windows do not seem to support it.

script:
############################
#from spacy.en import English
#nlp = English()
import spacy
nlp = spacy.load('en', entity=False)
#import spacy
#nlp = spacy.en.English(tagger=True, parser=True, entity=True)
print 1
import timeit
begin = timeit.default_timer()
doc = nlp(u'I love apples.')
for np in doc.noun_chunks:
    print 2
    print(np.text, np.root.text, np.root.dep_, np.root.head.text)
print begin - timeit.default_timer()  
raw_input(11)  
#############################

Error:
:::::::::::::::::::::::::::::
    nlp = spacy.load('en', entity=False)
  File "C:\Python27\lib\site-packages\spacy\__init__.py", line 42, in load
    return cls(**overrides)
  File "C:\Python27\lib\site-packages\spacy\en\__init__.py", line 34, in __init__
    Language.__init__(self, **overrides)
  File "C:\Python27\lib\site-packages\spacy\language.py", line 283, in __init__
    if 'parser' not in overrides \
  File "C:\Python27\lib\site-packages\spacy\language.py", line 110, in create_parser
    return DependencyParser.load(nlp.path / 'deps', nlp.vocab, **cfg)
  File "spacy/syntax/parser.pyx", line 99, in spacy.syntax.parser.Parser.load (spacy/syntax/parser.cpp:5426)
    self.model.load(str(path / 'model'))
  File "thinc/linear/avgtron.pyx", line 97, in thinc.linear.avgtron.AveragedPerceptron.load (thinc/linear/avgtron.cpp:3228)
    while reader.read(self.mem, &feat_id, &feature):
  File "thinc/linear/serialize.pyx", line 99, in thinc.linear.serialize.Reader.read (thinc/linear/serialize.cpp:2750)
    raise MemoryError()
MemoryError
::::::::::::::::::::::::::::::

**Comment by Oxi84** [comment]
Solver it using another version of spacy - pip install spacy==0.101.0

**Comment by Oxi84** [comment]
Very cool. I ended up making a simple function and here it is if someone needs it:

`from flask import Flask
from flask import request
import spacy
nlp = spacy.load('en')
app = Flask(__name__)

@app.route("/parse/")
def parse_text():
    sentence = request.args.get('sentence') 
    doc = nlp(sentence.decode('unicode-escape'))    
    out = [(d.text, d.dep_, d.pos_) for d in doc]
    out2 = [e[1] for e in out]
    out_str = " ".join(out2)
    return out_str
	
#example #http://127.0.0.1:5000/parse/?sentence=I like apples.	`

**Comment by ines** [comment]
@Oxi84 Thanks for sharing – slightly edited your comment btw to make it easier to read.
