### ISSUE TITLE
Behavior change in assignment of 'tag' property of Token (spaCy 2.3.5 vs 3.0.5)

### ISSUE THREAD

**Issue by nrodnova** [explosion/spaCy#7879]
## How to reproduce the behaviour

In spacy 2, an assignment of the granular tag `token.tag_` would also change `token.pos` to a corresponding part of speach. In spacy 3 this behavior disappeared. And while a work-around is not hard, I think it was the right behavior. I hope you can put it back.

### Code fragment
```
nlp = spacy.load('en_core_web_sm')
txt = "We are running short of cooking oil."
doc = nlp(txt)
token = doc[5]
print("Token: %s, Tag: %s, POS: %s" % (token, token.tag_, token.pos_))
token.tag_ = 'JJ'
print("Token: %s, Tag: %s, POS: %s" % (token, token.tag_, token.pos_))
```
### Spacy 2 output:
```
Token: cooking, Tag: NN, POS: NOUN
Token: cooking, Tag: JJ, POS: ADJ
```
### Spacy 3 output:
```
Token: cooking, Tag: VBG, POS: VERB
Token: cooking, Tag: JJ, POS: VERB
```
As you can see, the second lines of both versions differ, in spacy 3 we how have a VERB with tag JJ.

The difference is coming from `Token`'s `tag` property. 
In spacy 2:
```
    property tag:
        """RETURNS (uint64): ID of fine-grained part-of-speech tag."""
        def __get__(self):
            return self.c.tag

        def __set__(self, attr_t tag):
            self.vocab.morphology.assign_tag(self.c, tag)

```
In spacy 3:
```
property tag:
        """RETURNS (uint64): ID of fine-grained part-of-speech tag."""
        def __get__(self):
            return self.c.tag

        def __set__(self, attr_t tag):
            self.c.tag = tag
```
## Info about spaCy

- **spaCy version:** 3.0.5
- **Platform:** Darwin-18.7.0-x86_64-i386-64bit
- **Python version:** 3.7.3
- **Pipelines:** en_core_web_lg (3.0.0), en_core_web_md (3.0.0), en_core_web_sm (3.0.0), en_core_web_trf (3.0.0)

**Comment by nrodnova** [comment]
Actually, I am seeing now that tag_map.py disappeared in spacy 3. Is this information stored somewhere else?

**Comment by polm** [comment]
Since this isn't a bug it's a better fit for our Discussions board, so I'll move it there.
