### ISSUE TITLE
Feature Request: German Lemmatization

### ISSUE THREAD

**Issue by schlichtanders** [explosion/spaCy#789]
Dear spaCy Team,

it would be great to have German lemmas available directly within spacy.
After some research I found an open German lemmatizer as part of textblob-de

In the respective source code one of the decisive code snippet is this one
https://github.com/markuskiller/textblob-de/blob/dev/textblob_de/ext/_pattern/text/de/__init__.py#L186-L199

Is it possible to bring this to spacy too?

**Comment by ines** [comment]
Yes, agreed! We'd love to add at least a a lookup-table based lemmatizer for German. It shouldn't even be too much work, but unfortunately, we haven't gotten around to it yet. We're currently busy getting spaCy 2.0 ready, but if you want to play around with this (maybe porting it over from textblob could be an option?) and make a pull request, we'd definitely be happy to help and support!

I'll copy this over to #390 (another discussion of the German lemmatizer feature request) and closing this issue to keep the discussion in one place.

**Comment by schlichtanders** [comment]
thanks for the fast response and the link to the other issue
(I haven't found it in the issue tracker by myself, don't know why)
