### ISSUE TITLE
`load_lookups` return type misleading

### ISSUE THREAD

**Issue by jklaise** [explosion/spaCy#7894]
## How to reproduce the behaviour
`load_lookups` returns a `Lookup` object instead of a `Dict[str, Any]` as suggested in the function definition: https://github.com/explosion/spaCy/blob/df3444421aba611d4ad1238610ce189df158d85a/spacy/lookups.py#L15-L17

This makes typecheckers fail when calling methods of the object, e.g. `lookups.get_table('lexeme_prob')`.

Moreover, the current docstring is misleading as `Lookups` doesn't even implement a `__getitem__` method.

**Comment by svlandeg** [comment]
You're right - both the type and the documentation should be adjusted. Do you feel like contributing the PR?

**Comment by jklaise** [comment]
Sure, I should be able to do it later today.
