### ISSUE TITLE
Is it possible to apply PhraseMatcher on the lowered text of a Doc ?

### ISSUE THREAD

**Issue by thomasopsomer** [explosion/spaCy#790]
Hi,

I use the PhraseMatcher to detect multiwords given a list of entities, and I'm wondering if it is possible to apply it only on lower text, without having to lower the text before.

For instance given a phrasematcher built with one entity ["machine learning], I would like to retrieve "machine learning" in 
- "Machine learning is cool."
- "machine learning is cool."
- "Machine Learning is cool."

without having to add the different version of the entity in the matcher or to lower the input text.

Thanks,
Thomas.

**Comment by honnibal** [comment]
The easiest way to do this is to subclass the `PhraseMatcher` and write a new `add()` method. You'll have to do this in a Cython file. The only change you need from the original is to change `token.orth` to `token.lower`.

**Comment by thomasopsomer** [comment]
Great, Thanks for the trick, its perfect for non-named / general entity multiwords :)

**Comment by thomasopsomer** [comment]
Hey, I spoke to fast ! I did changed the `add()` method as suggested however it doesn't work. Looking at the code, I guess the trick I'm looking for is in the `matcher.call()` method, but I can't figure out how to make it 'indifferent' of capital letters.
