### ISSUE TITLE
ModuleNotFoundError: No module named 'thinc.types'

### ISSUE THREAD

**Issue by jacekwachowiak** [explosion/spaCy#7905]
#7219 
Hi, I am having problems with importing Spacy, I have used a requirements file to install all libraries to a new venv and what worked on an older one does not work anymore, I get the error:

```---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-76a01d9c502b> in <module>
----> 1 import spacy

C:\Users\XXX\AppData\Roaming\Python\Python37\site-packages\spacy\__init__.py in <module>
      8 
      9 # These are imported as part of the API
---> 10 from thinc.api import prefer_gpu, require_gpu, require_cpu  # noqa: F401
     11 from thinc.api import Config
     12 

C:\Users\XXX\AppData\Roaming\Python\Python37\site-packages\thinc\__init__.py in <module>
      3 
      4 from .about import __version__
----> 5 from .config import registry

C:\Users\XXX\AppData\Roaming\Python\Python37\site-packages\thinc\config.py in <module>
     20 import re
     21 
---> 22 from .types import Decorator
     23 
     24 

ModuleNotFoundError: No module named 'thinc.types'
```

My settings:

```$ pip list | grep spacy
spacy               3.0.0
spacy-alignments    0.8.3
spacy-legacy        3.0.5
$ pip list | grep thinc
thinc               8.0.3
```

## Info about spaCy

- **spaCy version:** 3.0.0
- **Platform:** Windows-10-10.0.18362-SP0
- **Python version:** 3.7.4
- **Pipelines:** de_core_news_lg (3.0.0)

I can't find any solution and the other closed ticket is about an old version, which is not my issue. I tried to reinstall everything, with or without transformers but to no avail.

**Comment by polm** [comment]
Since this is installation related I'm going to move it to Discussions. Please follow the link to find the Discussion and I'll follow up there.
