### ISSUE TITLE
Kernel dies importing spacy

### ISSUE THREAD

**Issue by bosanipietro** [explosion/spaCy#7906]
## How to reproduce the behaviour

`import spacy`

## Your Environment

* Operating System: macOS with Apple M1 chip
* Python Version Used: 3.9.4
* spaCy Version Used: 3.0.0
* Environment Information:

Importing spaCy library into Jupiter notebook within the above environment kills my kernel, with the package failing to import. Any help would be greatly appreciated, thanks for all your hard work!

**Comment by polm** [comment]
Sorry to hear you're having trouble with this. Since this is installation related I'm going to move it to Discussions, just follow the link to find it.
