### ISSUE TITLE
Quickstart config.cfg has a bug with defaults

### ISSUE THREAD

**Issue by dcavar** [explosion/spaCy#7913]
## How to reproduce the behaviour

Go to the interface: https://spacy.io/usage/training#quickstart

Start a new textcat config, do not touch the "exclusive categories" checkbox.

The generated base_config.cfg will set the flag:

exclusive_classes = true

If you select "exclusive categories" and then unselect it, the generated file contains the correct setting:

exclusive_classes = false

This is just an issue with setting the defaults right from the outset.

Not a big problem, just one that made us generate a little bit carbon unnecessarily.

All the best

[Damir](http://damir.cavar.me/)

## Your Environment

* Operating System: Fedora 34
* Python Version Used: 3.9.x
* spaCy Version Used: 3.x
* Environment Information:

**Comment by svlandeg** [comment]
Thanks, nice catch!

**Comment by svlandeg** [comment]
Ines [fixed](https://github.com/explosion/spaCy/commit/12d3d0feddc4f813d1cc63ab2465e31e9c8816cc) this bug, and it looks like now the `exclusive_classes` checkbox is properly checked on the UI, matching the actual settings in the generated config file. So I think I can go ahead and close this issue, thanks again for the report!
