### ISSUE TITLE
Error with command "train"

### ISSUE THREAD

**Issue by dosamy** [explosion/spaCy#7918]
I prepared data for training a NER model in Spanish. I followed all the steps for creating the configuration file and the data in spacy's binary format. 
When I run the command `python -m spacy train config.cfg --paths.train ./train.spacy --paths.dev ./dev.spacy`, I get this error: 
`ValueError: Attempt to change dimension 'nI' for model 'maxout' from 768 to 192`

I have 2 questions please:
How can I solve this error to start the training?
What is the reason of the error as I haven't changed any configurations.

## Your Environment

- Operating System: Ubuntu
- Python Version Used: Python 3.8
- spaCy Version Used: Spacy 3

**Comment by polm** [comment]
Since this looks like a usage question I'm going to move it to Discussions. Please follow the link to see the thread there.
