### ISSUE TITLE
Spacy v3.0 TOKENIZE incorrect result

### ISSUE THREAD

**Issue by TimVanDorpe** [explosion/spaCy#7932]
Hi,

So, I'm using spacy to tokenize sentences in my application.
Simple things like 'can't' and 'id' are split up in multiple tokens , see attachments.
Is there a reason for this splitting up or is this still an issue/bug from this version (2.2.43) ? 

- Operating System: Windows-10-10.0.14393-SP0
- Python Version Used: 3.7.5
- spaCy Version Used: 2.2.43

![image](https://user-images.githubusercontent.com/10908646/116401674-cb221280-a82b-11eb-9d7d-5f4136432a9f.png)
![image](https://user-images.githubusercontent.com/10908646/116401825-f99fed80-a82b-11eb-87e4-a092bfef958f.png)

Tim

**Comment by adrianeboyd** [comment]
Let me move this to the discussion board...
