### ISSUE TITLE
'Weights and Biases' sending spam?

### ISSUE THREAD

**Issue by VegaDeftwing** [explosion/spaCy#7940]
I received this email this morning:

![image](https://user-images.githubusercontent.com/11283620/116436415-00216b80-a812-11eb-844d-e0f11f082c36.png)

The GitHub star scraping for my email definitely feels a little ... off. To the point that I'd be surprised if it's not a GitHub TOS violation.

**Comment by adrianeboyd** [comment]
Yes, we feel the same way and Ines and Matt are working on a response. I got the email even though I haven't starred the repo (I just don't star anything and my email is not part of my public profile), so our best guess is that they must have scraped email addresses out of the commits.

**Comment by minimaxir** [comment]
Per the [API docs for getting stargazers](https://docs.github.com/en/rest/reference/activity#list-stargazers), it shouldn't be possible to get emails from that alone if they aren't listed in the user profile, which makes how they did this interesting.

**Comment by lavanyashukla** [comment]
Hi folks,

I want to apologize to you on behalf of our entire team for the email you got from W&B in the past week. That email should not have been sent. Our SDR team messed up and I want you to know we don’t take mistakes like this lightly.

We care deeply about our relationship with our users (and the ML community at large). We spend a lot of our time creating useful resources for the community (like our podcast and AMAs and paper reading groups), and giving a platform to people in the ML community working on interesting things with our Salon talks and Fully Connected. We take a lot of pride in our community.

Let me explain briefly what happened and how we’re fixing the problem going forward.

As ML engineers ourselves, we don't like getting outbound emails. That’s why we try to be extremely cautious when we send them and use them extremely sparingly. But in this instance, in particular, we failed. Essentially, we were excited to tell people about the new SpaCy integration we've been working on the last month, and in addition to tweets and telling our community, we also scraped some emails and an over-zealous SDR team sent out an email telling the spaCy community about the new features the integration added. Like a lot of startups, we try to move quickly, and sometimes, that backfires. It certainly did here.

We know trust is hard to gain and easy to lose. Going forward, we’ve put a lot of internal processes in place to keep this from happening again. We’re big fans and believers in spaCy and we take none of the support we’ve gotten for granted.

So from me and the rest of the team at W&B, please accept our sincerest apologies. If you have *any* questions for me or us, please reach out and I’d be happy to answer them. 

Thank you for reading.

**Comment by VegaDeftwing** [comment]
I am not affiliated with SpaCy, but frankly, it's really hard to take that apology seriously, as it still reads like you're advertising your product. "We spend a lot of our time creating useful resources for the community 
> "(like our podcast and AMAs and paper reading groups)"

or

>"working on interesting things with our Salon talks and Fully Connected"

so at least to me, this is meaningless. If you want to apologize, it helps not to do the thing everyone is mad about in the apology. All you had to do was say "we scraped emails, we acknowledge this was wrong, and it will **never** happen again." 

but that's not how this reads. This has the exact same vibe as a YouTuber apology video that's been monetized so the fake tears can be use to sell Raid Shadow Legends and line some pocketbooks.
