### ISSUE TITLE
token.conjuncts does not return conjuncts of conjuncts

### ISSUE THREAD

**Issue by aikramer2** [explosion/spaCy#795]
If you have the sentence: 

"The boy and the girl and the man went to the store."

boy.conjuncts will only return girl, and girl.conjuncts will not return anything. Seems to be caused by 
[this line](https://github.com/explosion/spaCy/blob/e7f8e13cf3740487e557beec52c26233847da9a9/spacy/tokens/token.pyx#L480) Personally i would expect:

boy.conjuncts -> [girl]
girl.conjuncts -> [man]

I think the only requirements are that the elements are connected by a coordinating conjunction, with no restriction on either element being a conjunction themselves.

* Operating System: Ubuntu
* Python Version Used: 2.7
* spaCy Version Used: 1.6.0

**Comment by honnibal** [comment]
I think I was intending for 

    boy.conjuncts -> [boy, girl, man]
    girl.conjuncts -> [boy, girl, man]

I think it's nice to get all of the conjuncts.

**Comment by aikramer2** [comment]
makes sense, so calling conjuncts on any element of a continuous sequence of dependent conjuncts returns the whole sequence, in order of dependence, including itself. If you agree I can do a PR sometime this week.

**Comment by honnibal** [comment]
Sounds good!

**Comment by aikramer2** [comment]
@honnibal Initial pass is below, but the trouble is that we need to do recursion in both directions. Its 3X slower than the current conjuncts, but on the same order as token.subtree. Do you think the benefits of the full conjunctive list is worth the slowdown?

```
from spacy.symbols import conj
def recurse_subtree(token):
    #yield token
    for child in token.children:
        if child.dep == conj:
            yield child
            #yield from recurse_subtree(child) in python3
            for grand_child in recurse_subtree(child):
                yield grand_child
                
def recurse_supertree(token):
    yield token
    if token.dep_ == conj:
        #yield from recurse_supertree(token.head) in python3
        for parent in recurse_supertree(token.head):
            yield parent

def recurse_supertree_reversed(token):
    for conjunct in list(recurse_supertree(token))[::-1]:
        yield conjunct
        
def conjuncts(token):
    if token.dep == conj or any(child.dep == conj for child in token.children):
        for conjunct in recurse_supertree_reversed(token):
            yield conjunct
        for conjunct in recurse_subtree(token):
            yield conjunct
```

**Comment by GitDimma** [comment]
"I like apples, oranges and bananas." 
 [ i for i in doc[2].conjuncts] --> returns only  [ oranges ]
