### ISSUE TITLE
Entity Recognizer is removing kb_id information

### ISSUE THREAD

**Issue by Fourthought** [explosion/spaCy#7959]
## How to reproduce the behaviour

I've created a matcher for custom entity patterns that includes a verification step from a look up function to return a `kb_id`.

The named entity recognizer, howver, seems to be removing the `span.kb_id` attribute.

The Custom component is shown here:

`
    
    class CustomTokeniser:

    """
    pipeline component for tokenising and verifying:
    - dates
    - phone numbers
    - VRNs
    - Postcodes
    step 1: regex matching of full and partial values
    step 2: match multiple partials
    step 3: verify the token as a date, phone number etc
    step 4: merge partial tokens
    step 5: apply appropriate labels

    This pipeline component ensure unique identifiers are correctly tokenised.
    """

    def __init__(self, vocab, patterns=patterns):

        # Initialise the Matcher
        self.matcher = Matcher(vocab, validate=True)
        
        # the patterns object includes a verification function which is added
        # when the patterns are added
        self.verificationFunctions = dict()

        if patterns:
            self.addPatterns(patterns)

    def __call__(self, doc):

        matches = self.matcher(doc, as_spans=True)
        print("PRE MATCH:", [(ent, ent.label_, ent.kb_id_) for ent in doc.ents])

        # open the retokenizer to enable the merging of constitutent components of a unique identifier.
        with doc.retokenize() as retokenizer:

            for span in filter_spans(matches):

                attrs = dict()
                attrs['_'] = {}
                attrs['_']['verified'] = False
                attrs['ent_type_'] = span.label_

                if self.verificationFunctions.get(span.label_):
                    # if the match is verified by the verification function, the `verified` attribute becomes True
                    # and a attrs["kb_id"] attribute is added
                    span, attrs['_']['verified'], attrs = self.verificationFunctions[span.label_](span, attrs=attrs)

                # create span when a unique ID is returned from verification function
                if attrs.get("kb_id"):
                    span = doc.char_span(span.start_char, span.end_char, label=span.label_, kb_id=attrs.get("kb_id"))

                retokenizer.merge(span, attrs=attrs)

                doc.set_ents(filter_spans(list(doc.ents) + [span]))

        print("POST MATCH:", [(ent, ent.label_, ent.kb_id_) for ent in doc.ents])
        return doc

    def addPatterns(self, patterns_obj):

        """
        add match patterns and verification functions to the pipeline component
        """

        for pattern in patterns_obj:

            if pattern.get('label') and pattern.get('pattern'):
                self.matcher.add(pattern["label"], [pattern["pattern"]])

            if pattern.get('label') and pattern.get('function'):
                self.verificationFunctions[pattern['label']] = pattern['function']
`

The pipeline component features twice in the pipeline for different patterns sets. Below is the output for when this custom component is placed before the NER component. As can be seen, the `span.kb_id` attribute is retained when the custom compoment is called (pre and post match), but is lost when `print("OUTPUT:", [(ent, ent.label_, ent.kb_id_) for ent in doc.ents])` is called.

Do you know how to retain the `kb_id` attribute after the `ner` component please?

`

    PRE MATCH: []
    POST MATCH: [(Saturday, April 15th, 2017, 'DATE', '2017-04-15T00:00:00Z')]
    PRE MATCH: [(Saturday, April 15th, 2017, 'DATE', '2017-04-15T00:00:00Z')]
    POST MATCH: [(Saturday, April 15th, 2017, 'DATE', '2017-04-15T00:00:00Z')]
    OUTPUT: [(Saturday, April 15th, 2017, 'DATE', '')]
`

## Your Environment
- **spaCy version:** 3.0.5
- **Platform:** Windows-10-10.0.18362-SP0
- **Python version:** 3.8.8
- **Pipelines:** en_core_web_lg (3.0.0), en_core_web_md (3.0.0), en_core_web_sm (3.0.0), en_core_web_trf (3.0.0)

**Comment by svlandeg** [comment]
Thanks for the report, I'll have a look into this, it feels like this might be a bug.

**Comment by adrianeboyd** [comment]
I don't think it's a bug exactly, but we could extend the retokenizer merge to cover this.

I think the problem is that the token attribute is `ENT_KB_ID` and the retokenizer doesn't look at the `KB_ID` of the span at all (at this point, anyway). Instead, provide `ENT_TYPE` and `ENT_KB_ID` in the `attrs`.

As a note, I don't think that `ent_type_` is going work in `attrs`, either. Use `ENT_TYPE` instead. You can provide a string value for `ENT_TYPE` and it will be converted automatically during the retokenization.

**Comment by Fourthought** [comment]
Thank you for taking a look Adriane, and for the proper attribute string values!

I've just tried a number of configurations and it seems disabling the `ner` component resolves the problem. So it seems something in the `ner` component is stripping out some entity attributes. I think `retokeniser.merge` seems to be working ok.

`

    nlp = spacy.load("en_core_web_md", disable=['ner'])

    gives the following desired ouput:

    PRE MATCH: []
    POST MATCH: [(Saturday, April 15th, 2017, 'DATE', '2017-04-15T00:00:00Z')]
    PRE MATCH: [(Saturday, April 15th, 2017, 'DATE', '2017-04-15T00:00:00Z')]
    POST MATCH: [(Saturday, April 15th, 2017, 'DATE', '2017-04-15T00:00:00Z')]

    print("OUTPUT:", [(ent, ent.label_, ent.kb_id_) for ent in doc.ents])
    OUTPUT: [(Saturday, April 15th, 2017, 'DATE', '2017-04-15T00:00:00Z')]
`

**Comment by adrianeboyd** [comment]
I can't follow all the details of the custom components above, but I can reproduce the fact that the `ner` component is stripping the `kb_id` values from existing entities. Here's a shorter example where the second assertion fails:

```python
import spacy
from spacy.tokens import Span

nlp = spacy.load("en_core_web_sm")
doc = nlp("This is a sentence.")
span = Span(doc, 2, 4, label="NP", kb_id=1234)
doc.ents = [span]

assert doc.ents[0].kb_id == 1234

doc = nlp.get_pipe("ner")(doc)

assert doc.ents[0].kb_id == 1234
```

We will look into it!

**Comment by svlandeg** [comment]
(maintenance note: adding back the NEL label as the `kb_id` is relevant for NEL and it's useful to see this thread when filtering on that label)

**Comment by Fourthought** [comment]
Thank you!
