### ISSUE TITLE
Reintroduce page with annotation specs?

### ISSUE THREAD

**Issue by plison** [explosion/spaCy#7960]
The documentation for Spacy v2 had a very useful page describing the various (coarse and fine-grained) tagsets used for POS tagging, NER, etc. (https://v2.spacy.io/api/annotation).  I often used it to find out a description of various tags, along with (very useful!) examples.

As far as I could see, this part of the documentation has disappeared in Spacy v3, and is replaced with a simple list of tags for each model, but without any description or examples. I know that one can use the function `explain` to get an explanation of a specific tag, but I found it useful to have easily access to the full tagset with examples from the doc website. 

Would it be possible to reintroduce those tables in some form or another? I realise it may be difficult to maintain as the number of models (and associated tagsets) grows larger, but this was a super useful part of the previous documentation in my opinion :-)

**Comment by svlandeg** [comment]
Yes, you're right. We have it on our TODO to bring this page back in some form, see also: https://github.com/explosion/spaCy/discussions/7181 :-)

**Comment by polm** [comment]
Going to close this in favor of #7280, since they're basically the same thing.
