### ISSUE TITLE
POS tag explanation is missing in Chinese parsing models

### ISSUE THREAD

**Issue by XiulinYang** [explosion/spaCy#7983]
Hi, I try to find out what the POS tags in the Chinese parsing model `zh_core_web_trf`  mean by using spacy.explain() function but got many 'None'. The pos tag explanation document refers to the Universal Dependency explanation https://universaldependencies.org/docs/u/pos/ but I couldn't find the pos tags used in `zh_core_web_trf`. The same problem also occurs in the dependency relation explanation. Is there any other document that I missed? Thank you very much in advance. :)

The GitHub page of `zh_core_web_trf` https://github.com/explosion/spacy-models/releases//tag/zh_core_web_trf-3.0.0.
## Your Environment

* **spaCy version:** 2.3.5
* **Platform:** macOS-10.16-x86_64-i386-64bit
* **Python version:** 3.8.5

**Comment by XiulinYang** [comment]
That's the code and the result.
```
import spacy
l = ['AD', 'AS', 'BA', 'CC', 'CD', 'CS', 'DEC', 'DEG', 'DER', 'DEV', 'DT', 'ETC', 'FW',
     'IJ', 'INF', 'JJ', 'LB', 'LC', 'M', 'MSP', 'NN', 'NR', 'NT', 'OD', 'ON', 'P', 'PN',
     'PU', 'SB', 'SP', 'URL', 'VA', 'VC', 'VE', 'VV', 'X']

for x in l:
    print(x, spacy.explain(x))
```

```
AD None
AS None
BA None
CC conjunction, coordinating
CD cardinal number
CS None
DEC None
DEG None
DER None
DEV None
DT determiner
ETC None
FW foreign word
IJ None
INF None
JJ adjective
LB None
LC None
M None
MSP None
NN noun, singular or mass
NR None
NT None
OD None
ON None
P None
PN None
PU None
SB None
SP space
URL None
VA None
VC None
VE None
VV None
X other
```

**Comment by adrianeboyd** [comment]
Hi, the fine-grained part-of-speech tags are from OntoNotes 5, from the Chinese Penn Treebank. Some links to documentation:

https://repository.upenn.edu/cgi/viewcontent.cgi?article=1039&context=ircs_reports

https://faculty.washington.edu/fxia/mpapers/2005/CTB_NLE2005.pdf

We are planning to add model-specific pages with more documentation for v3.1. Related issues are: #7181, #7280, #7960

We can also try to add more of the explanations for Chinese to `spacy.explain`, but if there are conflicts between different tag sets, like English `CD` is not the same as Chinese `CD`, `spacy.explain` isn't designed to handle this very well.

**Comment by XiulinYang** [comment]
Thank you very much!

**Comment by XiulinYang** [comment]
> Hi, the fine-grained part-of-speech tags are from OntoNotes 5, from the Chinese Penn Treebank. Some links to documentation:
> 
> https://repository.upenn.edu/cgi/viewcontent.cgi?article=1039&context=ircs_reports
> 
> https://faculty.washington.edu/fxia/mpapers/2005/CTB_NLE2005.pdf
> 
> We are planning to add model-specific pages with more documentation for v3.1. Related issues are: #7181, #7280, #7960
> 
> We can also try to add more of the explanations for Chinese to `spacy.explain`, but if there are conflicts between different tag sets, like English `CD` is not the same as Chinese `CD`, `spacy.explain` isn't designed to handle this very well.

Hi, thanks for your kind help. I'm also wondering, is there any document about the dependency relations of the Chinese? The Penn Chinese Treebank is a constituency parsed treebank, so I couldn't find any explanation related to dependency relations. I can't find all the dependency relations in the v2 docs, either. Many thanks in advance. :)

**Comment by adrianeboyd** [comment]
Hi, it's the UD conversion of OntoNotes using the CoreNLP converter. Currently the quality of the conversion is not very good (lots of `dep` relations, problems with unnecessary non-projective punct annotation, etc.). The conversion was primarily a user contribution, discussion in #4083.

**Comment by XiulinYang** [comment]
> Hi, it's the UD conversion of OntoNotes using the CoreNLP converter. Currently the quality of the conversion is not very good (lots of `dep` relations, problems with unnecessary non-projective punct annotation, etc.). The conversion was primarily a user contribution, discussion in #4083.

Thanks!
