### ISSUE TITLE
Unable to parse list of empty Docs using from_docs function

### ISSUE THREAD

**Issue by darnox** [explosion/spaCy#7998]
## How to reproduce the behaviour

Creating a new Doc from a list of empty Docs causes an exception. Here's the example code:
```python
import spacy
from spacy.tokens import Doc
nlp = spacy.load("en_core_web_sm")
Doc.from_docs([Doc(nlp.vocab), Doc(nlp.vocab)])
```
Result:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "spacy/tokens/doc.pyx", line 1165, in spacy.tokens.doc.Doc.from_docs
IndexError: list assignment index out of range
```
The problem doesn't occur if at least one Doc has words:
```python
Doc.from_docs([Doc(nlp.vocab, ["word"]), Doc(nlp.vocab)])
```
## Your Environment

* Operating System: Ubuntu 20.04
* Python Version Used: 3.6.13
* spaCy Version Used: 3.0.6
* Environment Information:
  - **spaCy version:** 3.0.6
  - **Platform:** Linux-5.4.0-1042-gcp-x86_64-with-debian-bullseye-sid
  - **Python version:** 3.6.13
  - **Pipelines:** en_core_web_sm (3.0.0)

**Comment by polm** [comment]
Thanks for the report, that looks like a bug. That should probably throw an exception anyway, but the current exception is a bit hard to understand.

Can you elaborate a little on what you're doing that caused this to come up?

**Comment by svlandeg** [comment]
The fix for this will be released in the next version!
