### ISSUE TITLE
Converting strings to docs using an custom entity ruler model slow

### ISSUE THREAD

**Issue by bhargav0795** [explosion/spaCy#8016]
## How to reproduce the behavior
I built a Rule-based model using an entity ruler with 40k multi-words patterns as follows
{"label":"JT","pattern":[{"LOWER":"chief"},{"LOWER":"executives"}]}
{"label":"JT","pattern":[{"LOWER":"chief"},{"LOWER":"sustainability"},{"LOWER":"officers"}]}

What I'm trying to do?
The idea is to identify job titles from a string. I have a dataset of 140k strings. The process occurs in two phases, the first step involves identifying necessary data points from the string and break the string into multiple substrings, and then in the next step each substring is converted to a spacy doc object, and the job titles are extracted and stored.
`nlp.pipe()` function is invoked once per string. On average, a string is divided into 4 substrings. Average size of a substring is 850 words.

**Code**
`nlp.pipe(df.iloc[:10]['txt'], 
disable = ["tok2vec", "tagger", "parser", "attribute_ruler", "lemmatizer"],
n_process = len(df.iloc[:10]['txt'])-1, 
batch_size = 1)`

**Benchmarks**
To process 10 sub-strings 
```
%%timeit

4.86 s ± 93.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Is there a way to optimize the process? 

## Your Environment
* **spaCy version:** 2.3.0
* **Platform:** Linux-4.15.0-142-generic-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.6.9

**Comment by polm** [comment]
This is better suited for Discussions, so I'll be moving it. Click on the link to follow up there.
