### ISSUE TITLE
Transformer data for Italian language is missing

### ISSUE THREAD

**Issue by diegmonti** [explosion/spaCy#8018]
When using the quickstart widget available at https://spacy.io/usage/training#quickstart, if you select as language Italian and as hardware GPU you will get a blank page. The Javascript error is the following: `TypeError: i.transformer_data is null`.

**Comment by polm** [comment]
Ah, thanks for pointing that out. We don't have an Italian Transformer model, but the website should provide some kind of meaningful output in that case. It definitely shouldn't blank the whole page.
