### ISSUE TITLE
Incomplete coverage of ordinals as numbers

### ISSUE THREAD

**Issue by kinghuang** [explosion/spaCy#8019]
## How to reproduce the behaviour

#5830 extended `like_num` to include ordinals. But, it only checks `th` as a suffix. This leaves out `1st`, `2nd`, and `3rd`.

```python
import spacy

nlp = spacy.load("en_core_web_lg")
doc = nlp("1st 2nd 3rd 4th 5th")

for t in doc:
    print(t.text, t.like_num)
```

```
1st False
2nd False
3rd False
4th True
5th True
```

## Info about spaCy

- **spaCy version:** 3.0.6
- **Platform:** Linux-5.10.25-linuxkit-x86_64-with-glibc2.2.5
- **Python version:** 3.8.9
- **Pipelines:** en_core_web_lg (3.0.0)

**Comment by polm** [comment]
Nice catch! Should be easy to fix at least.
