### ISSUE TITLE
Token vectors are empty using `en_core_web_trf` model.

### ISSUE THREAD

**Issue by erip** [explosion/spaCy#8037]
## How to reproduce the behaviour

```python
>>> import spacy
>>> spacy.__version__
'3.0.6'
>>> nlp = spacy.load('en_core_web_trf')
>>> s = "Hello, my name is Elijah."
>>> doc = nlp(s)
>>> doc[0].vector
array([], dtype=float32)
```

## Info about spaCy

- **spaCy version:** 3.0.6
- **Platform:** macOS-10.16-x86_64-i386-64bit
- **Python version:** 3.8.8
- **Pipelines:** en_core_web_lg (3.0.0), en_core_web_trf (3.0.0)

**Comment by erip** [comment]
I imagine the model is trained on subwords, so maybe the alignment between those and tokens in the spaCy since is causing issues?

**Comment by polm** [comment]
This isn't a bug, so I'm moving it to discussions, click the link to go to the page there.
