### ISSUE TITLE
 Depricationwarning in simple test case

### ISSUE THREAD

**Issue by djhenderson** [explosion/spaCy#8046]
Depricationwarning in simple test case:

```
> py
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> nlp = spacy.load("en_core_web_sm")
C:\Program Files\Python39\lib\site-packages\packaging\version.py:127: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
>>>
```
- Operating System: Windows 10 Pro
- Python Version Used: Python 
- spaCy Version Used: 3.0.0
- Environment Information:
```
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2
CUDA_PATH_V11_2=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2
PYTHONDEVMODE=1
PYTHONUTF8=1
```

**Comment by polm** [comment]
Thanks for the report. On Linux I get the output described in #7036, but not the DeprecationWarning. Can you give the full output of `pip freeze`? It might be an interaction with another package. 

Also would be great if you could try in a fresh environment with the latest spaCy.

**Comment by djhenderson** [comment]
This is a first time install of spaCy, CuPy, CUDA, etc.

I think this is a packaging warning that may be unique to the Windows packages.

attached is output from ```py -m pip freeze```.
[freeze.txt](https://github.com/explosion/spaCy/files/6447931/freeze.txt)

It looks like this message is generated from the ```packaging``` package at line 127. This is triggered when the regexp at about line 256 is not matched for a version string. HTH.

BTW: ```py -V``` gives ```Python 3.9.5```

**Comment by polm** [comment]
I think you are referring to this line:

https://github.com/pypa/packaging/blob/8c78c35bc20fc7b4aacb7a71ad5f5db9817630c1/packaging/version.py#L112

Looking at your requirements.txt, it's not clear to me that any of them have a Legacy Version. I tried parsing all the versions on lines with `==` and they all seem fine. Maybe the model packages, which have a @ instead, are causing the issue... We'll need to look at this more. https://github.com/pypa/packaging/blob/8c78c35bc20fc7b4aacb7a71ad5f5db9817630c1/packaging/version.py#L112

**Comment by polm** [comment]
Looks like the pip setuptools bug may be the one described in https://github.com/pypa/pip/issues/9250. 

Since it's not clear we're doing anything wrong here, and since this is just a warning, I'm going to close this for now, but feel free to add further information at any time. We can re-open it if there is actually something for us to fix.
