### ISSUE TITLE
More issues with CUDA OOM errors with en_core_web_trf

### ISSUE THREAD

**Issue by michelemarzollo** [explosion/spaCy#8065]
Hello,

I am having issues similar to those reported in #7593 and  #7268. Following all the suggestions there, I still get OOM errors.
## Context
I am working on a corpus that contains text extracted from various sources, so it is not always plain English text, it also contains tables that are translated into numbers and spaces.
## How to reproduce the behaviour
* I am processing documents one by one and not in batches, in order to reduce the possibility of OOM errors.
* I cut the documents into blocks of at most 100k characters.
* I disable all pipeline components but the transformer and NER.
* I clear the cache calling `torch.cuda.empty_cache()` and `cupy.get_default_memory_pool().free_all_blocks()` before each block is processed. I also set `nlp.get_pipe("transformer").model.attrs["flush_cache_chance"] = 1`.
* I don’t save the processed documents.
* Still, I get OOM errors. When this happens, I observed that the blocks contain sequences of numbers.
* Took me some time, but I managed to narrow it down to a set of 3 documents that are guaranteed to trigger the OOM: if you process them in the order provided in the code you get a cuda OOM error when processing the last document. Note that if you process the last document alone you don’t get any error (although you almost fill the GPU memory).

You can find the code, the files and the instructions to reproduce the error at this link https://github.com/francelabs/spacy3oombugreproduction.

## Your Environment
I am using a Scaleway instance (https://www.scaleway.com/en/gpu-instances/) with the following specifications:
* Operating System: Ubuntu 18.04.5 LTS
* NVIDIA Tesla P100 16GB PCIe
* CPUs: 10 Intel Xeon Gold 6148 cores
* RAM: 45 GB
* Python Version Used: 3.8.5
* spaCy Version Used: 3.0.6
* CUDA 10.1
* cupy-cuda101 8.6.0
* torch 1.8.1
* transformers 4.5.1

Thank you in advance for your time.

**Comment by michelemarzollo** [comment]
Thank you very much for your fast answer and for the suggestion of using smaller document sizes.

I have read that it should indeed prevent OOM errors from happening. And in my testing I couldn't reach OOM when using smaller chunk sizes (50k characters). However, I am surprised that with moderate sizes (70k characters), when processing thousands of documents in a row, I still sometimes reach OOM on some documents. And processing those same documents alone with the same chunk sizes does not result in any OOM.
The provided example with a chunk size of 100k chars is an extreme one I managed to build to provide you with an easily reproducible case of the problem. I thought document processing was independent and so if a document can be processed alone, it could be processed in any chain of documents without encountering any error on that particular document. Hence my report.
As a side note, manually freeing the memory helped me reduce the OOM errors in this setting, but i agree that with smaller sizes it shouldn't be necessary.

For now, I will go for smaller chunks. Thank you again!

**Comment by adrianeboyd** [comment]
To be honest, I don't know enough details about how pytorch manages GPU memory, so I'm not sure what's going on. My guess would be that some garbage collection step hasn't fully completed before it starts trying to process the next large batch, but I don't really know for sure.

In this particular case, smaller documents + larger batch sizes are definitely going to be faster and easier to manage, and shouldn't affect the quality of the annotation.

If you're concerned about the annotations at the beginning and end of the split texts, one option is to process overlapping segments instead and merge annotations in the overlapping parts, but this is probably overkill for most use cases as long as you can split the documents at semantically meaningful points like sections.

**Comment by michelemarzollo** [comment]
Ok, thank you very much for the suggestions!
