### ISSUE TITLE
DocBin with serialized Vocab - no lower_ and is_punct attributes

### ISSUE THREAD

**Issue by nrodnova** [explosion/spaCy#8070]
## How to reproduce the behaviour

My initial problem was the one addressed in https://github.com/explosion/spaCy/issues/8041. I tried to avoid it by saving a `Vocab` object together with `DocBin`, and then deserializing it and using it to get `Docs` from `DocBin`. If I understand correctly, there is nothing wrong with doing it. `Docs` extracted from `DocBin` with this vocabulary are missing at least `lower_` and `is_punct` attributes. Here's a code fragment that reproduces it:
```python
import spacy
from spacy.tokens import DocBin
from spacy.vocab import Vocab

nlp = spacy.load('en_core_web_sm')

text = "Hello, world!"
doc = nlp(text)

print("*** Before serialization ***")
for token in doc :
    print(token, "\t", token.lower_, "\t", token.is_punct, "\t", token.ent_id_)

attributes = ("ORTH", "TAG", "HEAD", "DEP", "ENT_IOB", "ENT_TYPE", "ENT_ID", "ENT_KB_ID", "LEMMA", "MORPH", "POS", "LOWER", "SENT_START", "SENT_END", "IDX", 'IS_PUNCT', 'LIKE_NUM', 'IS_BRACKET', "IS_LEFT_PUNCT", "IS_RIGHT_PUNCT")

# Serialize
doc_bin = DocBin(attrs = attributes, store_user_data = False, docs = [doc])
serialized_docs = doc_bin.to_bytes()
serialized_vocab = nlp.vocab.to_bytes()

# Deserialize
vocab = Vocab().from_bytes(serialized_vocab)
doc_bin = DocBin(attrs = attributes, store_user_data=False).from_bytes(serialized_docs)
docs = list(doc_bin.get_docs(vocab))

print("\n*** After serialization ***")
for token in docs[0] :
    print(token, "\t", token.lower_, "\t", token.is_punct, "\t", token.ent_id_)
```
The code fragment above produces the following output:
```text
*** Before serialization ***
Hello 	 hello 	 False 	 
, 	 , 	 True 	 
world 	 world 	 False 	 
! 	 ! 	 True 	 

*** After serialization ***
Hello 	  	 False 	 
, 	  	 False 	 
world 	  	 False 	 
! 	  	 False 	 
```

## Info about spaCy

- **spaCy version:** 3.0.6
- **Platform:** Darwin-20.3.0-x86_64-i386-64bit
- **Python version:** 3.7.9
- **Pipelines:** en_core_web_lg (3.0.0), en_core_web_md (3.0.0), en_core_web_sm (3.0.0)

**Comment by adrianeboyd** [comment]
Hi, the short/practical answer to load from a `DocBin` in v3.0.6 is that the derivable lexeme features are not stored in the serialized vocab, so you need to initialize the vocab with the right language settings to have these features set correctly in the vocab that's used for the deserialized docs:

```python
nlp = spacy.blank("en")  # or nlp = English()
docs = list(db.get_docs(nlp.vocab))
```

Most of these come from the `lex_attr_getters` that are part of the language-specific settings like `English.Defaults`. These are functions, so they can't be serialized safely with the model data, so instead they're reloaded based on the language settings in the library when you initialize a new pipeline. If you initialize a vocab with `Vocab()` without any language settings, it doesn't include any `lex_attr_getters` by default.

----------

That said, this question does touch on a number of relevant issues where there is inconsistent behavior around serialization and lexemes.

1. It does seem inconsistent that you can't set lexeme attributes from `DocBin` (underlying: `Doc.from_array`) like you can with the retokenizer. You do have to realize that `Lexeme` attributes affect every occurrence of the token, so it effectively modifies all docs that refer to the same vocab, but it seems reasonable to allow you to set these features from `Doc.from_array` if you really want to.

    In general, though, you probably don't want a vocab without the language defaults and `lex_attr_getters` because so many attributes will be missing. If your only goal is to reload these particular docs and work with the specified features, then it would be okay, but if you used these reloaded docs for training the built-in statistical models, a lot of the feature extraction wouldn't work as intended because attributes like `NORM` and `SHAPE` would be missing.

2. The other main issue is what information is serialized with the vocab. Before v2.3, the vocab included a serialized table of lexeme entries. Most of the information was easily derivable from the `lex_attr_getters`, so it bloated the model size and was slow to load from disk.

    In #5238, I worked on removing a lot of the derivable features. The non-derivable features were moved into separate tables (`NORM`, `CLUSTER`, `PROB`) and everything else was no longer serialized. I did miss `IS_STOP` as a non-derivable feature in that PR, but we have plans to add the set of stop words to the serialized vocab in v3.1.

    For the derivable lexeme attributes, I can only think of extremely bizarre situations where it makes sense to modify any of these features for individual lexemes rather than creating a custom language with custom `lex_attr_getters` that are applied consistently for new lexemes.

3. I think there might also be some inconsistent behavior around serialization and custom lexeme flags (`Vocab.add_flag`), but this feature seems to be rarely used in practice. As with the `lex_attr_getters`, a serialized lexeme table would include in the values for the lexemes that have been seen before, but wouldn't help with unseen lexemes after deserialization. In most cases, a better solution is a custom language.

**Comment by adrianeboyd** [comment]
I looked into serializing stop words better as a lookups table `lexeme_is_stop` and it's a mess in various aspects:

* `lex_attr_getters` only contains a function that tells you if something is a stop word, so you have to add `stop_words` as additional `Vocab` setting, which additionally makes stop words look even more important in the API which seems bad
* preserving the current default of lowercasing requires hard-coding the `lower` behavior in the lexeme init

For reference, this is what it might look like:

https://github.com/adrianeboyd/spaCy/tree/feature/serialize-stop-words

As a note, the old saved lexeme table only saved `IS_STOP` for the case variants that had been seen previously, so even restoring this would not really do the right thing.

This is so messy that I would punt and say that customizing the language defaults (custom language, custom callback) remains the best option here.
