### ISSUE TITLE
Allow abbreviations in the Sentencizer

### ISSUE THREAD

**Issue by mr-bjerre** [explosion/spaCy#8073]
I have a use case where I prefer the rule based Sentencizer component over a statistical model for performance reasons. It gives me fine results although I have a few abbreviations that I'd like to account for. E.g. `approx. 100` shouldn't be split into two sentences. 

I've looked at the source code for [`predict`](https://github.com/explosion/spaCy/blob/master/spacy/pipeline/sentencizer.pyx#L75) and I think I could pretty easily add the possibility to provide `abbreviations` and account for those - same way the `punct_chars` can be given for instance.

Would you allow for a PR on that feature or what do you think about it?

**Comment by mr-bjerre** [comment]
I'm thinking something like this

```python
    def predict(self, docs):
        """Apply the pipe to a batch of docs, without modifying them.
        docs (Iterable[Doc]): The documents to predict.
        RETURNS: The predictions for each document.
        """
        if not any(len(doc) for doc in docs):
            # Handle cases where there are no tokens in any docs.
            guesses = [[] for doc in docs]
            return guesses
        guesses = []
        for doc in docs:
            doc_guesses = [False] * len(doc)
            if len(doc) > 0:
                start = 0
                seen_period = False
                previous_was_abbreviation = False
                doc_guesses[0] = True
                for i, token in enumerate(doc):
                    is_in_punct_chars = token.text in self.punct_chars
                    if seen_period and not token.is_punct and not is_in_punct_chars:
                        doc_guesses[start] = True
                        start = token.i
                        seen_period = False
                    elif is_in_punct_chars and not previous_was_abbreviation:
                        seen_period = True
                    
                    # determine if "previous" (seen from next "non-punct" token) was an abbreviation or not
                    if token.text in self.abbreviations:
                        previous_was_abbreviation = True
                    elif not token.is_punct and not is_in_punct_chars:
                        previous_was_abbreviation = False
                if start < len(doc):
                    doc_guesses[start] = True
            guesses.append(doc_guesses)
        return guesses
```

**Comment by adrianeboyd** [comment]
Hmm, I understand what you're trying to do, but I think a better overall solution here (if you only want to use built-in components) is to add tokenizer exceptions so that the underlying token is `approx.`, and then the sentencizer wouldn't split here.

Since it's pretty easy to implement custom rule-based components, I think it would better to keep the built-in sentencizer fairly simple / streamlined and not to introduce any additional settings.

**Comment by mr-bjerre** [comment]
the tokenizer exceptions merge the tokens into a single token?

**Comment by adrianeboyd** [comment]
Sure, if you define the exception that way, e.g.:

https://github.com/explosion/spaCy/blob/d5bbd1f94fd6e89416d83fbd3f28f4d7c8f2a0fb/spacy/lang/en/tokenizer_exceptions.py#L421-L473

**Comment by mr-bjerre** [comment]
I'll close this - but just to be sure. You'd add those exceptions with `nlp.tokenizer.add_special_case`?

**Comment by mr-bjerre** [comment]
Also I want to give my own list of punct chars (all the default ones except a few) but when I look at the [default ones](https://github.com/explosion/spaCy/blob/d5bbd1f94fd6e89416d83fbd3f28f4d7c8f2a0fb/spacy/pipeline/sentencizer.pyx#L32) it looks a bit odd!?

```python
    default_punct_chars = ['!', '.', '?', '։', '؟', '۔', '܀', '܁', '܂', '߹',
            '।', '॥', '၊', '။', '።', '፧', '፨', '᙮', '᜵', '᜶', '᠃', '᠉', '᥄',
            '᥅', '᪨', '᪩', '᪪', '᪫', '᭚', '᭛', '᭞', '᭟', '᰻', '᰼', '᱾', '᱿',
            '‼', '‽', '⁇', '⁈', '⁉', '⸮', '⸼', '꓿', '꘎', '꘏', '꛳', '꛷', '꡶',
            '꡷', '꣎', '꣏', '꤯', '꧈', '꧉', '꩝', '꩞', '꩟', '꫰', '꫱', '꯫', '﹒',
            '﹖', '﹗', '！', '．', '？', '𐩖', '𐩗', '𑁇', '𑁈', '𑂾', '𑂿', '𑃀',
            '𑃁', '𑅁', '𑅂', '𑅃', '𑇅', '𑇆', '𑇍', '𑇞', '𑇟', '𑈸', '𑈹', '𑈻', '𑈼',
            '𑊩', '𑑋', '𑑌', '𑗂', '𑗃', '𑗉', '𑗊', '𑗋', '𑗌', '𑗍', '𑗎', '𑗏', '𑗐',
            '𑗑', '𑗒', '𑗓', '𑗔', '𑗕', '𑗖', '𑗗', '𑙁', '𑙂', '𑜼', '𑜽', '𑜾', '𑩂',
            '𑩃', '𑪛', '𑪜', '𑱁', '𑱂', '𖩮', '𖩯', '𖫵', '𖬷', '𖬸', '𖭄', '𛲟', '𝪈',
            '｡', '。']
```

**Comment by adrianeboyd** [comment]
Yes, that's right.
