### ISSUE TITLE
💫 Document workflow: Saving and loading

### ISSUE THREAD

**Issue by ines** [explosion/spaCy#808]
The documentation for saving and loading is currently missing. spaCy v2.0 will support the pickle protocol and make this much easier, but in the meantime (and to support people using spaCy 1.x in the future), we should add a workflow explaining how it's currently done.

As discussed on Gitter, @ematvey offered to take this on and write a small tutorial for the docs 🎉  I'll take care of all formatting and adding it to the site.

Feel free to add questions and suggestions!

**Comment by ematvey** [comment]
`Doc` is a sequence of tokens, which are pointers to lemmas and strings within the `Vocab` object. When spacy discovers unknown word, it adds news strings and lemmas to the `Vocab` it used to parse this text. So, if we want to serialize `Doc`s, we need to put a `Vocab` alongside it, right?

Not so. Docs can be restored perfectly using default `Vocab` even if they contain unknown (OOV) tokens.

I've digged around a bit and found that `Doc.to_bytes()` checks if `Doc` contains OOV words. If not, it encodes with ORTH IDs. But if it does, it fallbacks to char-encoding. It seems that Docs are self-describing in this way (conditional on default vocab). No need to save `Vocab` separately? If we dont care about space, that is. And if we do care about space, is there any way to set Vocab to immediately internalize new OOV tokens? That is, not treat them as OOV.

**Comment by ematvey** [comment]
Actually no, it doesn't work like that. I tried restoring `Doc`s with both default vocab (`spacy.load('en')`) and with persisted,
```python
en = spacy.load('en')
with open(vocab_strings_fn, 'r') as f:
  en.vocab.strings.load(f)
en.vocab.load_lexemes(vocab_lexeme_fn)
```
Both results in data corruption and `Buffer exhausted at .../... symbols read` errors.
Wierdly, data corruption looks like this:

Decoded with encoder `nlp` (also correct one):

> Anarchism is a political philosophy that advocates self-governed societies based on voluntary institutions. These are often described as stateless societies, although several authors have defined them more specifically as institutions based on non-hierarchical free associations. Anarchism holds the state to be undesirable, unnecessary, and harmful. While anti-statism is central, anarchism entails opposing authority or hierarchical organization in the conduct of all human relations, including, but not limited to, the state system.

Decoded with default `nlp` or restored `nlp`:

> Soundtrack isa political philosophythat advocatesself- governedsocietiesbased on voluntaryinstitutions .These areoften described asstateless societies ,althoughseveralauthors havedefined them more specifically as institutions based on non-hierarchicalfreeassociations .Soundtrack Routinethatto white pulsars unnecessary, and harmful. While anti - statismiscentral,anarchism entails opposing authority or hierarchical organization in theconductof all human relations , including, but not limited to , the statesystem .

In all 3 vocabs (encoder, default, and restored) "Soundtrack" has ID 34429 while "Anarchism" has ID 34430. Could this be some kind of aliasing bug in `Doc.to_bytes()`?

**Comment by ematvey** [comment]
@ines @honnibal 

Guys, I need some guidance regarding the tutorial. So far my understanding is this:

- `Doc`s are self-describing and could be serialized without accompanying `Vocab`
- `nlp.pipe()` with intensive multithreading results in unstable serialization, even though results could be used within the same process

**Comment by honnibal** [comment]
Hm! I think you've almost gotten to the bottom of a concurrency bug here. Thanks!

So, there must be somewhere in the parser/entity-recogniser that writes to the `StringStore` or vocab during the concurrent loop, leading to the race condition.

The parser and entity recogniser are the only parts that are multi-threaded. They use different transition systems, but most of the same code otherwise. Let me look into this.

**Comment by honnibal** [comment]
Here's the `parser.pipe()` loop for your reference:

https://github.com/explosion/spaCy/blob/97a1286129cf5a8dd3dc16fe4ced653bd9d61b2a/spacy/syntax/parser.pyx#L173

I see there's a note here I left to myself previously. Have you by any chance added new labels to the entity recogniser?
