### ISSUE TITLE
span.get_lca_matrix() goes out of bounds

### ISSUE THREAD

**Issue by svlandeg** [explosion/spaCy#8095]
Originally reported in https://github.com/explosion/spaCy/discussions/8056

## How to reproduce the behaviour
```
import spacy
nlp = spacy.load("en_core_web_sm")
doc = nlp("I like New York in Autumn")
span = doc[1:4]
matrix = span.get_lca_matrix()
```
Confirmed to be a bug.

**Comment by adrianeboyd** [comment]
It looks like this has been broken since v2.1.0, probably since `_get_lca_matrix` created as a helper method in `doc.pyx` for both `Span` and `Doc`.
