### ISSUE TITLE
Regex pattern for Currency is not working while using it through entity_ruler

### ISSUE THREAD

**Issue by Ashufet** [explosion/spaCy#8101]
## How to reproduce the behaviour
```
nlp = spacy.load("en_core_web_md",disable=['attribute_ruler','lemmatizer','tagger','parser'])
config = {
           "phrase_matcher_attr": None,
           "validate": True,
           "overwrite_ents": True,
           "ent_id_sep": "||",
            }
ruler = nlp.add_pipe("entity_ruler",config=config,after='ner')
ruler.add_patterns([{"label": "CURRENCY", "pattern": [{"TEXT": {"REGEX": "\$\-?\d+[\.\,]+\d+|\$\-?\d+"}}]}])
```

It's not predicting the currency entity($200) for the below data -

"I have **$200** money with me."

Can you please me, what I am doing wrong here?

## Your Environment
Spacy version - 3.0.6

**Comment by svlandeg** [comment]
Hi! As a maintenance note: this is a good question for the discussions forum, so I'll move it there. The original issue will be closed and will link through to the open discussion thread.
