### ISSUE TITLE
No LOCAL_DATA_DIR 

### ISSUE THREAD

**Issue by vladimircape** [explosion/spaCy#812]
In Anaconda i type

`import os
from spacy.en import English, LOCAL_DATA_DIR

data_dir = os.environ.get('SPACY_DATA', LOCAL_DATA_DIR)`

but got

> ImportError:cannot import name LOCAL_DATA_DIR'

by conda list i got

spacy                     0.101.0                  py27_0  
spacy                     1.6.0                     <pip>

**Comment by honnibal** [comment]
I'd say the two different versions there are almost certainly to blame.

**Comment by vladimircape** [comment]
AS i understand spacy 0.101.0 py27_0 is old ?

**Comment by syllog1sm** [comment]
Yes. The `LOCAL_DATA_DIR` variable was deprecated some time ago. If you use the current version (1.6) and the usage from the docs, everything should work fine --- let me know if it doesn't.
