### ISSUE TITLE
Spacy 2.3.6 is missing distribution files

### ISSUE THREAD

**Issue by harupy** [explosion/spaCy#8126]
![image](https://user-images.githubusercontent.com/17039389/118612969-3fcbe980-b7f9-11eb-8add-bd8a8f1bc0f3.png)

https://pypi.org/project/spacy/2.3.6/#files

Looks like `spacy 2.3.6` is missing distribution files.

---

## Your Environment

- Operating System:
- Python Version Used:
- spaCy Version Used:
- Environment Information:

**Comment by polm** [comment]
Sorry about that, we're aware of this and dealing with it. Unfortunately during the release of 2.3.6 we bumped up against some PyPI size limits, so we need to get those increased before we can add more release files.

**Comment by adrianeboyd** [comment]
Hmm, I wonder if we can temporarily yank it? I think we can unyank it later. We can look into the details.

**Comment by adrianeboyd** [comment]
Also, if you would like to install v.2.3.6 from an individual wheel, we've attached them here temporarily:

https://github.com/explosion/spaCy/releases/tag/v2.3.6

**Comment by harupy** [comment]
@polm @adrianeboyd Thans for the quick reply! Got it.
