### ISSUE TITLE
Spacy lemmatize Documentation

### ISSUE THREAD

**Issue by vladimircape** [explosion/spaCy#813]
Is it possible to expand lemmatize to add my personal cases of words, of existing or new words?

**Comment by honnibal** [comment]
It is, but as you've noticed there isn't really documentation. The `Lemmatizer` class is pretty simply Python though. If you have a look at how the `.exc` dict is structured you should be able to add your entries.

**Comment by vladimircape** [comment]
Am i right you mean such files.
https://github.com/explosion/spaCy/blob/master/corpora/en/wordnet/dict/verb.exc
https://github.com/explosion/spaCy/blob/master/corpora/en/wordnet/dict/adj.exc
https://github.com/explosion/spaCy/blob/master/corpora/en/wordnet/dict/noun.exc
but i check them they have small amount of words?

and what these files for vrb extension and noun extension?
https://github.com/explosion/spaCy/blob/master/corpora/en/wordnet/dict/sentidx.vrb
https://raw.githubusercontent.com/explosion/spaCy/master/corpora/en/wordnet/dict/index.noun

**Comment by honnibal** [comment]
Lemmatization has now been refactored, and made much more consistent. There are no longer these old .exc and .index data files, so I'm going to close this.
