### ISSUE TITLE
Operator + does only match 1 time

### ISSUE THREAD

**Issue by marmg** [explosion/spaCy#8144]
I'm using the SpaczzRuler pipeline as specified in [here](https://spacy.io/universe/project/spaczz/) to detect companies based on patterns.  Is a very simple pipeline in which I'm trying to match uppercase tokens, but when using the operator + it matches only one token in uppercase, and not as many as possible. The [documentation](https://spacy.io/api/matcher) says:
``+ | Require the pattern to match 1 or more times.``

However, if using the * operator it indeed matches all possible times, as expected.

## How to reproduce the behaviour
```python
import spacy
from spaczz.pipeline import SpaczzRuler

model = spacy.blank('es')
spaczz_ruler = SpaczzRuler(model)
spaczz_ruler.add_patterns([
    {"label": "COMPANY", 'pattern': [
        {"IS_UPPER": True, "OP": "+"}, {"IS_PUNCT": True, "OP": "?"},
        {"TEXT": {"REGEX": "S\.\s?[A-Z]\.?\s?[A-Z]?\.?"}},
        {"IS_PUNCT": True, "OP": "?"}], 
     "type": "token", "id": "COMPANY SL"}
])
model.add_pipe(spaczz_ruler)

doc = model("My company is called LARGO AND MARMG S.L.")
print(doc.ents)
# (MARMG S.L.,)

model = spacy.blank('es')
spaczz_ruler = SpaczzRuler(model)
spaczz_ruler.add_patterns([
    {"label": "COMPANY", 'pattern': [
        {"IS_UPPER": True, "OP": "*"}, {"IS_PUNCT": True, "OP": "?"},
        {"TEXT": {"REGEX": "S\.\s?[A-Z]\.?\s?[A-Z]?\.?"}},
        {"IS_PUNCT": True, "OP": "?"}], 
     "type": "token", "id": "COMPANY SL"}
])
model.add_pipe(spaczz_ruler)

doc = model("My company is called LARGO AND MARMG S.L.")
print(doc.ents)
# (LARGO AND MARMG S.L.,)
```

## Info about spaCy
* **Platform:** Windows-10-10.0.17134-SP0
* **Python version:** 3.8.6
* **spaCy version:** 2.3.5
* **spaczz Version Used: 0.5.0

**Comment by polm** [comment]
spaczz is a third-party project, not something we develop directly. You should ask about this at [their repo](https://github.com/gandersen101/spaczz).
