### ISSUE TITLE
Does Spacy in named entities find locations?

### ISSUE THREAD

**Issue by vladimircape** [explosion/spaCy#816]
I check examples 
https://nicschrading.com/project/Intro-to-NLP-with-spaCy/
but in code 
```
    example = "Apple's stocks dropped dramatically after the death of Steve Jobs in October."
    parsedEx = parser(example)
    for token in parsedEx:
        print(token.orth_, token.ent_type_ if token.ent_type_ != "" else "(not an entity)")
        ents = list(parsedEx.ents)
        for entity in ents:
            print(entity.label, entity.label_, ' '.join(t.orth_ for t in entity))
```

did not find all types of entites which spacy can provide, can you share a link to documentation or file responsible for that?

As i found it names GPE?

**Comment by honnibal** [comment]
Well...There's no way to document the behaviours of the system on any specific sentence --- it's a statistical model, and you just have to try and see. We hope to have improved NER models in spaCy 2.0.

The best way to check how the current system tends to behave is the displaCy demo, at demos.explosion.ai
