### ISSUE TITLE
How does spacy handle transformers sequence limit?

### ISSUE THREAD

**Issue by John-8704** [explosion/spaCy#8163]
I like spacy because of using it for many document level entity recognition which have sequence length of 2000 -3000 words. But in spacy v3 we have transformers to choose as pre-trained model. But we know that bert like models have a sequence limit of 512 words. So then how can I use spacy with my documents for entity recognition. I want to understand how does spacy overcome this, and what options do I have here?

**Comment by polm** [comment]
Since this is a question and not a bug I'm going to move it to Discussions.
