### ISSUE TITLE
How to get relarionship indexes as in example.

### ISSUE THREAD

**Issue by Oxi84** [explosion/spaCy#817]
How to I get universal dependencies indexes like in stanford parser. The numbers from the example bellow.

Sentence:  "I like apples but my sister does not."
nsubj(like-**2**, I-**1**)
root(ROOT-**0**, like-**2**)
dobj(like-**2**, apples-**3**)
cc(like-**2**, but-**4**)
nmod:poss(sister-**6**, my-**5**)
nsubj(does-**7**, **sister-6)**
conj(like-**2**, does-**7**)
neg(does-**7**, not-**8**)

I am now able to get just this:
##############
I : nsubj : PRP
like : ROOT : VBP
apples : dobj : NNS
but : cc : CC
my : poss : PRP$
sister : nsubj : NN
does : conj : VBZ
not : neg : RB
. : punct : .
##############

Using the code:
`    import spacy`
    `  nlp = spacy.load('en')`
   `   doc = nlp(u"I like apples but my sister does not.")    `
   `   for word in doc:`
        `   `   `  print(word.text, word.lemma, word.lemma_, word.tag, word.tag_, word.pos, word.pos_)`

**Comment by honnibal** [comment]
I think you probably want `word.head`, which returns a token. You could then do `word.head.i` to get the position of the head in the sentence if that's what you want.

**Comment by Oxi84** [comment]
Thans very much.
