### ISSUE TITLE
How to predict multiword ids in tokenization?

### ISSUE THREAD

**Issue by wangxinyu0922** [explosion/spaCy#8177]
## Your Environment

- Operating System:
- Python Version Used:
- spaCy Version Used:
- Environment Information:

Hi, I wonder how to predict a UD-like tokenization, for [example](https://universaldependencies.org/format.html):
```
1-2    vámonos   _
1      vamos     ir
2      nos       nosotros
3-4    al        _
3      a         a
4      el        el
5      mar       mar
```

So how can I predict `1-2    vámonos` and `3-4    al        _` given the
```
doc = nlp(text)
```
? Thank you.

**Comment by polm** [comment]
Since this isn't a bug report I'm going to move it to a Discussion, follow the link to follow up.
