### ISSUE TITLE
Typo in example code 

### ISSUE THREAD

**Issue by yury-gurevich** [explosion/spaCy#8189]
Example code on https://spacy.io/api/language#add_pipe 
In the 
def component_func(doc):
 #modify Doc and return it return doc

Should be 
def component_func(doc):
 #modify Doc and return it 
return doc

## Your Environment

- Operating System:
- Python Version Used:
- spaCy Version Used:
- Environment Information:

**Comment by polm** [comment]
Well spotted, thanks!
