### ISSUE TITLE
pip installation spacy

### ISSUE THREAD

**Issue by vladimircape** [explosion/spaCy#819]
Ubuntu16 Python 2.7
I tried install spacy by pip . 
>>>pip install spacy && python -m spacy.en.download

but got error
`huffman.so:` undefined symbol: _ZSt24__throw_out_of_range_fmtPKc

log of output
>>>Requirement already satisfied: spacy in /home/vshebuniayeu/anaconda2/lib/python2.7/site-packages
Requirement already satisfied: thinc<6.3.0,>=6.2.0 in /home/vshebuniayeu/anaconda2/lib/python2.7/site-packages (from spacy)
Requirement already satisfied: six in /home/vshebuniayeu/anaconda2/lib/python2.7/site-packages (from spacy)
Requirement already satisfied: murmurhash<0.27,>=0.26 in /home/vshebuniayeu/anaconda2/lib/python2.7/site-packages (from spacy)
Requirement already satisfied: ujson>=1.35 in /home/vshebuniayeu/anaconda2/lib/python2.7/site-packages (from spacy)
Requirement already satisfied: sputnik<0.10.0,>=0.9.2 in /home/vshebuniayeu/anaconda2/lib/python2.7/site-packages (from spacy)
Requirement already satisfied: cloudpickle in /home/vshebuniayeu/anaconda2/lib/python2.7/site-packages (from spacy)
Requirement already satisfied: pathlib in /home/vshebuniayeu/anaconda2/lib/python2.7/site-packages (from spacy)
Requirement already satisfied: numpy>=1.7 in /home/vshebuniayeu/anaconda2/lib/python2.7/site-packages (from spacy)
Requirement already satisfied: preshed<0.47.0,>=0.46.0 in /home/vshebuniayeu/anaconda2/lib/python2.7/site-packages (from spacy)
Requirement already satisfied: plac in /home/vshebuniayeu/anaconda2/lib/python2.7/site-packages (from spacy)
Requirement already satisfied: cymem<1.32,>=1.30 in /home/vshebuniayeu/anaconda2/lib/python2.7/site-packages (from spacy)
Requirement already satisfied: cytoolz<0.9,>=0.8 in /home/vshebuniayeu/anaconda2/lib/python2.7/site-packages (from thinc<6.3.0,>=6.2.0->spacy)
Requirement already satisfied: tqdm<5.0.0,>=4.10.0 in /home/vshebuniayeu/anaconda2/lib/python2.7/site-packages (from thinc<6.3.0,>=6.2.0->spacy)
Requirement already satisfied: flexmock in /home/vshebuniayeu/anaconda2/lib/python2.7/site-packages (from thinc<6.3.0,>=6.2.0->spacy)
Requirement already satisfied: semver in /home/vshebuniayeu/anaconda2/lib/python2.7/site-packages (from sputnik<0.10.0,>=0.9.2->spacy)
/home/vshebuniayeu/anaconda2/bin/python: /home/vshebuniayeu/anaconda2/lib/python2.7/site-packages/spacy/serialize/huffman.so: undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz

**Comment by vladimircape** [comment]
No help?

**Comment by vladimircape** [comment]
The same error in python 3.5

> shebuniayeu@vshebuniayeu:~$ python -m spacy.en.download
Traceback (most recent call last):
  File "/home/vshebuniayeu/anaconda3/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/vshebuniayeu/anaconda3/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/vshebuniayeu/anaconda3/lib/python3.5/site-packages/spacy/__init__.py", line 6, in <module>
    from . import en
  File "/home/vshebuniayeu/anaconda3/lib/python3.5/site-packages/spacy/en/__init__.py", line 8, in <module>
    from ..language import Language
  File "/home/vshebuniayeu/anaconda3/lib/python3.5/site-packages/spacy/language.py", line 17, in <module>
    from .tokenizer import Tokenizer
  File "spacy/morphology.pxd", line 25, in init spacy.tokenizer (spacy/tokenizer.cpp:12137)
  File "spacy/vocab.pxd", line 27, in init spacy.morphology (spacy/morphology.cpp:10684)
  File "spacy/serialize/packer.pxd", line 4, in init spacy.vocab (spacy/vocab.cpp:17937)
  File "spacy/serialize/huffman.pxd", line 15, in init spacy.serialize.packer (spacy/serialize/packer.cpp:23899)
ImportError: /home/vshebuniayeu/anaconda3/lib/python3.5/site-packages/spacy/serialize/huffman.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz

**Comment by vladimircape** [comment]
fixed by setting the same version for gcc and g++, and install additional modules for conda

**Comment by ines** [comment]
Really sorry for the late reply, just catching up with the issue tracker backlog. But thanks a lot for getting to the bottom of this and updating with your solution! 👍 This is very helpful in case others experience the same issue.

**Comment by gbonnard** [comment]
Hi vladimircape,

I have the exact similar issue. what conda additional packages did you install?

Thanks a lot.

Gaël
