### ISSUE TITLE
Config overrides lost once `spacy.load()` is done.

### ISSUE THREAD

**Issue by narayanacharya6** [explosion/spaCy#8190]
## How to reproduce the behaviour

I am trying to load a spaCy model with a custom component. The custom component depends on a custom KB and the config for the same requires a path to the KB. Below is a snippet of how I am loading the model.

```
import spacy

# noinspection PyUnresolvedReferences
import package.holding.my.custom.components

# THIS STEP WORKS
nlp = spacy.load('/path/to/my/custom/model',
                 config={
                     "source": {
                         "file": '/path/to/my/file'
                     }
                 })

# THIS STEP FAILS
nlp.initialize()
```

Debugging through the steps, I can see when my model is being loaded, the config overrides are available. But when I try to initialize (where my component actually uses the file), the `nlp` object has the config without the overrides.

I am not sure if this is a bug or expected behavior but I believe the issue stems from this piece of code:

https://github.com/explosion/spaCy/blob/0c553ecd4eaeedffb0ff4445100ad2c4b9a113a8/spacy/util.py#L360-L392

The config field on the `nlp` object on line 391 has the config overrides but the object returned by `nlp.from_disk` on line 392 does not have the config overrides. Is this expected behavior - to default the config after the load is done?

## Your Environment

- **spaCy version:** 3.0.6
- **Platform:** macOS-10.16-x86_64-i386-64bit
- **Python version:** 3.8.8
- **Pipelines:** en_core_web_lg (3.0.0), en_core_web_md (3.0.0), en_core_web_sm (3.0.0), en_core_web_trf (3.0.0)

**Comment by svlandeg** [comment]
Thanks for the report - we've merged your PR https://github.com/explosion/spaCy/pull/8208 so this should be fixed :-)
