### ISSUE TITLE
Patterns get duplicated when calling EntityRuler.add_patterns multiple times

### ISSUE THREAD

**Issue by nrodnova** [explosion/spaCy#8216]
## How to reproduce the behaviour
When calling `EntityRuler.add_patterns` multiple times, existing rules in the underlying 'matcher' get duplicated on every call. I believe it is done here (`entityruler.py line 322`):
```python
for label, patterns in self.token_patterns.items():
     self.matcher.add(label, patterns)
```
#### This code fragment demonstrates the behavior:

```python
import spacy
from spacy.pipeline import EntityRuler

nlp = spacy.load('en_core_web_sm')
entity_ruler = EntityRuler(nlp, validate = True)

patterns = [
    {'label' : 'pattern 1', 'pattern' : [{'LOWER' : 'a'}], 'id' : '1'},
    {'label' : 'pattern 2', 'pattern' : [{'LOWER' : 'b'}], 'id' : '2'},    
]

print("---------After adding 2 patterns ---------")
entity_ruler.add_patterns(patterns)
for name, pattern in entity_ruler.matcher._patterns.items() :
    print(nlp.vocab.strings[name], pattern)

entity_ruler.add_patterns([])
print("---------After adding empty array ---------")
for name, pattern in entity_ruler.matcher._patterns.items() :
    print(nlp.vocab.strings[name], pattern)

entity_ruler.add_patterns([ {'label' : 'pattern 3', 'pattern' : [{'LOWER' : 'c'}], 'id' : '3'},])
print("---------After adding a new pattern ---------")
for name, pattern in entity_ruler.matcher._patterns.items() :
    print(nlp.vocab.strings[name], pattern)

```

#### Output:

```
---------After adding 2 patterns ---------
pattern 1||1 [[{'LOWER': 'a'}]]
pattern 2||2 [[{'LOWER': 'b'}]]
---------After adding empty array ---------
pattern 1||1 [[{'LOWER': 'a'}], [{'LOWER': 'a'}]]
pattern 2||2 [[{'LOWER': 'b'}], [{'LOWER': 'b'}]]
---------After adding a new pattern ---------
pattern 1||1 [[{'LOWER': 'a'}], [{'LOWER': 'a'}], [{'LOWER': 'a'}]]
pattern 2||2 [[{'LOWER': 'b'}], [{'LOWER': 'b'}], [{'LOWER': 'b'}]]
pattern 3||3 [[{'LOWER': 'c'}]]

```

## Info about spaCy

- **spaCy version:** 3.0.6
- **Platform:** Darwin-20.3.0-x86_64-i386-64bit
- **Python version:** 3.7.9
- **Pipelines:** en_core_web_lg (3.0.0), en_core_web_md (3.0.0), en_core_web_sm (3.0.0)

**Comment by svlandeg** [comment]
Thanks for the comprehensive report and example code! This does look like a bug, we'll look into it.

**Comment by dhruvrnaik** [comment]
I was just about to report this. Thanks @nrodnova

**Comment by svlandeg** [comment]
I don't think it'll change the results? It might be slightly slower though, which may get worse the more this happens...

**Comment by dhruvrnaik** [comment]
This seems to be the issue: https://github.com/explosion/spaCy/blob/5957ab74f710da8e19be4a3373210e841a45e5f8/spacy/pipeline/entityruler.py#L322-L325

Just have to use temporary lists instead of using `self.token_patterns`/`self.phrase_patterns`

**Comment by svlandeg** [comment]
This is fixed by https://github.com/explosion/spaCy/pull/8246
