### ISSUE TITLE
Docs for training entity out-dated?

### ISSUE THREAD

**Issue by alanhorizon** [explosion/spaCy#822]
Hi,

I'm pretty new to spacy, actually trying out some of the example code in the docs, seems like the example at the following link is out-dated: https://spacy.io/docs/usage/training#train-entity

Am I correct in saying that that call to entity.update should take a GoldParse object? Or am I just doing something wrong?

**Comment by honnibal** [comment]
I think you're probably right, thanks.

**Comment by ines** [comment]
The new version 1.8.0 comes with bug fixes to the NER training procedure and a new `save_to_directory()` method. We've also updated the docs with more information on training and NER training in particular:
* Workflow: [Training the Named Entity Recognizer](https://spacy.io/docs/usage/training-ner)
* Workflow: [Saving and loading models](https://spacy.io/docs/usage/saving-loading)
* Example: [Training an additional entity type](https://github.com/explosion/spaCy/blob/master/examples/training/train_new_entity_type.py)
* [Command line interface](https://spacy.io/docs/usage/cli#model) for initialising, training and packaging models

I hope this helps!
