### ISSUE TITLE
Error using nlp.pipe with GPU. SystemError: <class 'list'> returned NULL without setting an error

### ISSUE THREAD

**Issue by LoganWalls** [explosion/spaCy#8229]
Hello, 
I'm running into the following error when I use `nlp.pipe()` on GPU: `SystemError: <class 'list'> returned NULL without setting an error`. I'm using the transformer model together with Huggingface Datasets, all running inside a docker container. 

I have looked at #3250 and #3522 but I checked the python version (using `python3.8 -c 'import struct;print( 8 * struct.calcsize("P"))'`) and it is 64 bit. As you'll see below the Linux version is also 64 bit. So I don't think this has the same root issue.

Thank you in advance for your help!

## How to reproduce the behaviour
The following script can reproduce the error in my container:
```python
import spacy
from datasets import load_dataset

spacy.prefer_gpu()

dataset = load_dataset("wikitext", "wikitext-2-raw-v1").filter(bool, input_columns=["text"])
nlp = spacy.load("en_core_web_trf")
docs = list(nlp.pipe((x["text"] for x in dataset["test"])))   # Fails on this line after processing a few of the items.
```
I've also made a [repo](https://github.com/LoganWalls/spacy-mwe) with the script above and a minimal version of my docker container if you'd like to reproduce it yourself. 

Assuming you have Docker and Nvidia Docker installed already, you should be able to reproduce the result by just cloning the repo and running the `run.sh`.

## Info about spaCy
- **spaCy version:** 3.0.6
- **Platform:** Linux-5.8.0-53-generic-x86_64-with-glibc2.27
- **Python version:** 3.8.10
- **Pipelines:** en_core_web_trf (3.0.0)

## `python -m spacy validate` output
================= Installed pipeline packages (spaCy v3.0.6) =================
ℹ spaCy installation: /usr/local/lib/python3.8/dist-packages/spacy

NAME              SPACY            VERSION                            
en_core_web_trf   >=3.0.0,<3.1.0   3.0.0   ✔

**Comment by polm** [comment]
Can you give the full error output so we can be sure where in the code this is happening? Not just the error line, but also the stack trace.

**Comment by LoganWalls** [comment]
That's just it... The entire stack trace is this:

```python
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    docs = list(nlp.pipe((x["text"] for x in dataset["test"])))
SystemError: <class 'list'> returned NULL without setting an error
```
I refactored it to use a loop instead of the list constructor, and to use `nlp.__call__()` instead of `nlp.pipe()`:
```python
import spacy
from datasets import load_dataset

spacy.prefer_gpu()

dataset = load_dataset("wikitext", "wikitext-2-raw-v1").filter(bool, input_columns=["text"])
nlp = spacy.load("en_core_web_trf", exclude=["ner"])

docs = []
for x in dataset["test"]:
    docs.append(nlp(x["text"]))
```

That gives a different error with a better trace: 
```python
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    docs.append(nlp(x["text"]))
  File "/usr/local/lib/python3.8/dist-packages/spacy/language.py", line 1000, in __call__
    error_handler(name, proc, [doc], e)
  File "/usr/local/lib/python3.8/dist-packages/spacy/util.py", line 1503, in raise_error
    raise e
  File "/usr/local/lib/python3.8/dist-packages/spacy/language.py", line 995, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))
  File "/usr/local/lib/python3.8/dist-packages/spacy_transformers/pipeline_component.py", line 184, in __call__
    outputs = self.predict([doc])
  File "/usr/local/lib/python3.8/dist-packages/spacy_transformers/pipeline_component.py", line 220, in predict
    activations = self.model.predict(docs)
  File "/usr/local/lib/python3.8/dist-packages/thinc/model.py", line 312, in predict
    return self._func(self, X, is_train=False)[0]
  File "/usr/local/lib/python3.8/dist-packages/spacy_transformers/layers/transformer_model.py", line 142, in forward
    tensors, bp_tensors = transformer(wordpieces, is_train)
  File "/usr/local/lib/python3.8/dist-packages/thinc/model.py", line 288, in __call__
    return self._func(self, X, is_train=is_train)
  File "/usr/local/lib/python3.8/dist-packages/thinc/layers/pytorchwrapper.py", line 80, in forward
    Ytorch, torch_backprop = model.shims[0](Xtorch, is_train)
  File "/usr/local/lib/python3.8/dist-packages/thinc/shims/pytorch.py", line 29, in __call__
    return self.predict(inputs), lambda a: ...
  File "/usr/local/lib/python3.8/dist-packages/thinc/shims/pytorch.py", line 38, in predict
    outputs = self._model(*inputs.args, **inputs.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/roberta/modeling_roberta.py", line 815, in forward
    encoder_outputs = self.encoder(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/roberta/modeling_roberta.py", line 508, in forward
    layer_outputs = layer_module(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/roberta/modeling_roberta.py", line 395, in forward
    self_attention_outputs = self.attention(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/roberta/modeling_roberta.py", line 323, in forward
    self_outputs = self.self(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/roberta/modeling_roberta.py", line 187, in forward
    mixed_query_layer = self.query(hidden_states)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

If it helps at all, the text that it is trying to process when it fails is below.

> In 2006 , Boulter starred alongside Whishaw in the play Citizenship written by Mark Ravenhill . He appeared on a 2006 episode of the television series , Doctors , followed by a role in the 2007 theatre production of How to Curse directed by Josie Rourke . How to Curse was performed at Bush Theatre in the London Borough of Hammersmith and Fulham . Boulter starred in two films in 2008 , Daylight Robbery by filmmaker Paris Leonti , and Donkey Punch directed by Olly Blackburn . In May 2008 , Boulter made a guest appearance on a two @-@ part episode arc of the television series Waking the Dead , followed by an appearance on the television series Survivors in November 2008 . He had a recurring role in ten episodes of the television series Casualty in 2010 , as " Kieron Fletcher " . Boulter starred in the 2011 film Mercenaries directed by Paris Leonti .


However, before failing it successfully processes the below text:

> Robert Boulter is an English film , television and theatre actor . He had a guest @-@ starring role on the television series The Bill in 2000 . This was followed by a starring role in the play Herons written by Simon Stephens , which was performed in 2001 at the Royal Court Theatre . He had a guest role in the television series Judge John Deed in 2002 . In 2004 Boulter landed a role as " Craig " in the episode " Teddy 's Story " of the television series The Long Firm ; he starred alongside actors Mark Strong and Derek Jacobi . He was cast in the 2005 theatre productions of the Philip Ridley play Mercury Fur , which was performed at the Drum Theatre in Plymouth and the Menier Chocolate Factory in London . He was directed by John Tiffany and starred alongside Ben Whishaw , Shane Zaza , Harry Kent , Fraser Ayres , Sophie Stanton and Dominic Hall .

**Comment by polm** [comment]
Thanks for the details! It's not clear to me what's going wrong yet but that stack trace should help us track it down. 

Also I have tried using your Docker container, but I haven't used nvidia-docker in a long time and it doesn't seem to be finding my GPU, so I haven't been able to reproduce the issue locally yet.

**Comment by svlandeg** [comment]
@LoganWalls : Which version of PyTorch are you on, and which CUDA version are you on?

**Comment by LoganWalls** [comment]
Thank you for your responses!

@svlandeg I am using Cuda 11.1 and the following versions of PyTorch:
```
torch==1.8.1+cu111
torchaudio==0.8.1
torchvision==0.9.1+cu111
```

@polm Please let me know if there's anything I can do to help!

**Comment by svlandeg** [comment]
Would you be able to retry with Pytorch 1.7 instead? 

The reason I'm asking is because of this thread: https://github.com/pytorch/pytorch/issues/53957:
> I upgraded to PyTorch 1.8.0 only today and am getting the same error on a call of the function torch.bmm. (...) I had the error with CUDA 11.1, so tried 11.2, but same error here as well.

**Comment by LoganWalls** [comment]
Downgrading PyTorch does seem to fix the problem, thanks! I take it this means that it is a PyTorch issue rather than SpaCy one?

For anyone who encounters the same problem later, it is working for me with the following packages:
```
torch==1.7.0+cu110
torchvision==0.8.1+cu110
torchaudio===0.7.0
```
(PyTorch 1.7 does not support CUDA 11.1, but the above seems to work anyway).

**Comment by svlandeg** [comment]
Happy to hear that downgrading works, and thanks for posting a working combination of versions.

It does feel like the issue is not in spaCy, but rather with PyTorch, considering that many other PyTorch users seem to be running into this. I'm not really sure there's anything else we can do at this point :|

**Comment by LoganWalls** [comment]
Alright, thank you for your help! I'll close the issue for now.
