### ISSUE TITLE
libc.so.6: version `GLIBC_2.14' not found

### ISSUE THREAD

**Issue by nooralahzadeh** [explosion/spaCy#823]
any advice for the following error ( it comes in : import spacy)
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /private/anaconda2/lib/python2.7/site-packages/cymem/cymem.so)

**Comment by hiteshpaul** [comment]
Try to run the following command in your conda environment:

conda install libgcc

This should solve your problem!

**Comment by nooralahzadeh** [comment]
I did, but still there is the same error after import spacy
