### ISSUE TITLE
No compatible package found for 'en_trf_bertbaseuncased_lg' (spaCy v3.0.0rc5)

### ISSUE THREAD

**Issue by shrirang3010** [explosion/spaCy#8237]
## Your Environment

- - **spaCy version:** 3.0.0rc5
- **Platform:** Windows-10-10.0.19041-SP0
- **Python version:** 3.8.9
- **Pipelines:** en_core_web_sm (3.0.0)

**Comment by polm** [comment]
Moving to Discussions since this is an installation issue.
