### ISSUE TITLE
Error installing spacy on python 2.7 on windows 7

### ISSUE THREAD

**Issue by vladimircape** [explosion/spaCy#824]
I tried 
`pip install spacy

It looks that spacy required only Microsoft Visula Studio ?

>d:\Programms\Anaconda2\Scripts\gcc.bat -DMS_WIN64 -mdll -O -Wall -Id:\programms\anaconda2\include -Ic:\users\runa\appdata\local\temp\pip-b uild-pgrnrn\spacy\include -Ic:\users\runa\appdata\local\temp\pip-build-pgrnrn\spacy\include\msvc9 -Id:\programms\anaconda2\include -Id:\prog ramms\anaconda2\PC -c spacy/parts_of_speech.cpp -o build\temp.win-amd64-2.7\Release\spacy\parts_of_speech.o -O3 -Wno-strict-prototypes -Wno- unused-function cc1plus.exe: warning: command line option '-Wno-strict-prototypes' is valid for C/ObjC but not for C++ [enabled by default] spacy/parts_of_speech.cpp: In function 'void __Pyx_RaiseTooManyValuesError(Py_ssize_t)': spacy/parts_of_speech.cpp:1947:94: warning: unknown conversion type character 'z' in format [-Wformat] spacy/parts_of_speech.cpp:1947:94: warning: too many arguments for format [-Wformat-extra-args] spacy/parts_of_speech.cpp: In function 'void __Pyx_RaiseNeedMoreValuesError(Py_ssize_t)': spacy/parts_of_speech.cpp:1953:48: warning: unknown conversion type character 'z' in format [-Wformat] spacy/parts_of_speech.cpp:1953:48: warning: format '%s' expects argument of type 'char*', but argument 3 has type 'Py_ssize_t {aka long lo ng int}' [-Wformat] spacy/parts_of_speech.cpp:1953:48: warning: too many arguments for format [-Wformat-extra-args] writing build\temp.win-amd64-2.7\Release\spacy\parts_of_speech.def d:\Programms\Anaconda2\Scripts\g++.bat -DMS_WIN64 -shared -s build\temp.win-amd64-2.7\Release\spacy\parts_of_speech.o build\temp.win-amd64 -2.7\Release\spacy\parts_of_speech.def -Ld:\programms\anaconda2\libs -Ld:\programms\anaconda2\PCbuild\amd64 -Ld:\programms\anaconda2\PC\VS9. 0\amd64 -lpython27 -lmsvcr90 -o build\lib.win-amd64-2.7\spacy\parts_of_speech.pyd building 'spacy.strings' extension d:\Programms\Anaconda2\Scripts\gcc.bat -DMS_WIN64 -mdll -O -Wall -Id:\programms\anaconda2\include -Ic:\users\runa\appdata\local\temp\pip-b uild-pgrnrn\spacy\include -Ic:\users\runa\appdata\local\temp\pip-build-pgrnrn\spacy\include\msvc9 -Id:\programms\anaconda2\include -Id:\prog ramms\anaconda2\PC -c spacy/strings.cpp -o build\temp.win-amd64-2.7\Release\spacy\strings.o -O3 -Wno-strict-prototypes -Wno-unused-function cc1plus.exe: warning: command line option '-Wno-strict-prototypes' is valid for C/ObjC but not for C++ [enabled by default] In file included from spacy/strings.cpp:248:0: c:\users\runa\appdata\local\temp\pip-build-pgrnrn\spacy\include\msvc9/stdint.h:34:2: error: #error "Use this header only with Microsoft Visual C++ compilers!" In file included from c:\users\runa\appdata\local\temp\pip-build-pgrnrn\spacy\include/murmurhash/MurmurHash3.h:8:0, cc1plus.exe: warning: command line option '-Wno-strict-prototypes' is valid for C/ObjC but not for C++ [enabled by default] In file included from thinc/linalg.cpp:248:0: c:\users\runa\appdata\local\temp\pip-build-pgrnrn\thinc\include\msvc9/stdint.h:34:2: error: #error "Use this header only with Microsoft Vi sual C++ compilers!" error: command 'd:\Programms\Anaconda2\Scripts\gcc.bat' failed with exit status Failed building wheel for thinc Running setup.py clean for thinc Failed to build spacy thinc Installing collected packages: thinc, pathlib, semver, sputnik, ujson, spacy

**Comment by vladimircape** [comment]
Problem was fixed, Spacy required only Visual Studio for Windows, no other compilers :(

**Comment by ines** [comment]
Sorry about this – we hope to improve Windows support in the future, especially with wheel downloads. (We also finally have a machine for Windows development!  🎉)
