### ISSUE TITLE
Nested rc_clauses parsing problems

### ISSUE THREAD

**Issue by Fxlix** [explosion/spaCy#8248]
When parsing german Sentences with nested rc_clauses ("Die schöne Frau, die Fritten, welche schwarz sind, isst, und die nervige Katze baden im Fluss." ) the spaCy Dependency parser pipeline from the de_dep_news_trf Model  will fail with high propability.
When recursively cutting the innermost "rc_clause", the Dependency parser does what it is expected to do. 
So I thought I could reparse the Sentence without the rc_clause and then line up the cutted rc_clause via retokenizer splitting. 
Computing the new heads and attrs should work fine - But the retokenizer just prints:
"ValueError: [E117] The newly split tokens must match the text of the original token. New orths: Fritten,welcheschwarzsind,. Old text: Fritten""

I understand that inserting and changing tokens is not what spacy is intended for, because its intended to keep the origin, but I really could need a good workaround, because its a recurring error. 

## Your Environment

- **spaCy version:** 3.0.6
- **Platform:** Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-debian-10.9
- **Python version:** 3.7.3
- **Pipelines:** de_dep_news_trf (3.0.0), de_core_news_lg (3.0.0)

**Comment by svlandeg** [comment]
Hi! I think this is a good question for the discussions forum, so I'll move it there. The original issue will be closed and will link through to the open discussion thread.
