### ISSUE TITLE
Force pos tag in tagger and moprhologizer

### ISSUE THREAD

**Issue by pdimiel** [explosion/spaCy#8259]
Hello everyone.

I am trying to add a custom partial tagger module in the pipeline.
The goal is to be able to force some pos tags according to rules or the output of an external pos tagger but not for all the tokens.

In spacy 3.0.6 I have the following as an example.
The actual function will use complex rules or given tags from another resource.

```
@Language.component("custom_tagger")
def custom_tagger(doc):
    for i, token in enumerate(doc):
        if token.orth_.lower() == "είδα":
            doc[i].tag_ = "VERB"
        elif token.orth_.lower() == "saw":
            doc[i].tag_ = "NN"

    return doc
```

I have a test function:

```
def process_and_print(given_nlp, text):
    print(nlp.pipe_names)
    doc = given_nlp(text)
    for sent in doc.sents:
        print(sent.text)
        for token in sent:
            print(token, token.tag_)
    print()
```

and I use it for two languages, English (that use a tagger) and Greek (that use a morphologizer) as:

```
sample = "I saw you cutting the tree."
nlp = spacy.load("en_core_web_sm")
process_and_print(nlp, sample)
nlp.add_pipe("custom_tagger", before="tagger")  # Insert before the tagger
process_and_print(nlp, sample)

sample = "Είδα ένα δέντρο."
nlp = spacy.load("el_core_news_sm")
process_and_print(nlp, sample)
nlp.add_pipe("custom_tagger", before="morphologizer")  # Insert before the morphologizer
process_and_print(nlp, sample)
```

In the English case, the output is the expected

> ['tok2vec', 'tagger', 'parser', 'ner', 'attribute_ruler', 'lemmatizer']
> I saw you cutting the tree.
> I PRP
> **saw VBD**
> you PRP
> cutting VBG
> the DT
> tree NN
> . .
> 
> ['tok2vec', 'custom_tagger', 'tagger', 'parser', 'ner', 'attribute_ruler', 'lemmatizer']
> I saw you cutting the tree.
> I PRP
> **saw NN**
> you PRP
> cutting VBG
> the DT
> tree NN
> . .

In the Greek case, there is no effect.

> ['tok2vec', 'morphologizer', 'parser', 'ner', 'attribute_ruler', 'lemmatizer']
> Είδα ένα δέντρο.
> **Είδα NOUN**
> ένα DET
> δέντρο NOUN
> . PUNCT
> 
> ['tok2vec', 'custom_tagger', 'morphologizer', 'parser', 'ner', 'attribute_ruler', 'lemmatizer']
> Είδα ένα δέντρο.
> **Είδα NOUN**
> ένα DET
> δέντρο NOUN
> . PUNCT

I suppose that it has something to do with the use of morphologizer instead of a tagger.

If that is the issue, is there a way to feed (force) coarse grained tags to the morphologizer and let it decide the fine grained details?

Thanks in advance

**Comment by polm** [comment]
Since this is more of a question than a bug report I'm going to move it to a Discussion. You can click on the link to see the Discussion.
