### ISSUE TITLE
InvalidChecksumException

### ISSUE THREAD

**Issue by andrew0harney** [explosion/spaCy#826]
Running:
    sputnik.install('spacy', spacy.about.__version__, 'en') 

Gives:
    sputnik.uget.InvalidChecksumException: 19f792a0986e57535be945d87df347d5 != 84cc5c9869bfdc09072bb8d217d30c53

OS: Ubuntu 16.04.1 LTS
Python Version Used: 3.5.2
spaCy Version Used: 1.6.0
Environment Information: Virtualenv

**Comment by ines** [comment]
Hmm, this looks like your download didn't complete successfully. Have you tried re-downloading the model?

**Comment by ines** [comment]
Closing this issue – for the new version, we've improved the download process and retired sputnik, so it should work more smoothly now.
