### ISSUE TITLE
AttributeError: Can't get attribute 'cluster' on <module 'spacy.lang.lex_attrs' 

### ISSUE THREAD

**Issue by sebastiz** [explosion/spaCy#8264]
## How to reproduce the behaviour

I am have used the fast.ai library to train a model for text classification (fastai2). This produces a pickle file. This was created in google colabs (
```
* **spaCy version:** 2.2.4
* **Platform:** Linux-5.4.109+-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.7.10
* **Models:** en)
```

I then tried to use the trained model in a new script in a jupyter notebook by loading it in to a learner

```
!pip install -Uqq fastbook
import fastbook
fastbook.setup_book()
from fastbook import *
from fastai.text.all import *

import pandas as pd
learner = load_learner('/content/gdrive/MyDrive/Colab_data/BarrettsPragueModel.pkl')
```

## Info about spaCy

```
* **spaCy version:** 2.3.4
* **Platform:** Linux-3.10.0-1160.24.1.el7.x86_64-x86_64-with-glibc2.10
* **Python version:** 3.8.8
```

When I load the learner I get the error as below:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-58-06af04e8023c> in <module>
----> 1 learner = load_learner('BarrettsPragueModel.pkl')

/opt/conda/lib/python3.8/site-packages/fastai/learner.py in load_learner(fname, cpu, pickle_module)
    379     "Load a `Learner` object in `fname`, optionally putting it on the `cpu`"
    380     distrib_barrier()
--> 381     res = torch.load(fname, map_location='cpu' if cpu else None, pickle_module=pickle_module)
    382     if hasattr(res, 'to_fp32'): res = res.to_fp32()
    383     if cpu: res.dls.cpu()

/opt/conda/lib/python3.8/site-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    590                     opened_file.seek(orig_position)
    591                     return torch.jit.load(opened_file)
--> 592                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
    593         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
    594 

/opt/conda/lib/python3.8/site-packages/torch/serialization.py in _load(zip_file, map_location, pickle_module, pickle_file, **pickle_load_args)
    849     unpickler = pickle_module.Unpickler(data_file, **pickle_load_args)
    850     unpickler.persistent_load = persistent_load
--> 851     result = unpickler.load()
    852 
    853     torch._utils._validate_loaded_sparse_tensors()

vocab.pyx in spacy.vocab.unpickle_vocab()

/opt/conda/lib/python3.8/site-packages/srsly/_pickle_api.py in pickle_loads(data)
     21     RETURNS: The deserialized Python object.
     22     """
---> 23     return cloudpickle.loads(data)

AttributeError: Can't get attribute 'cluster' on <module 'spacy.lang.lex_attrs' from '/opt/conda/lib/python3.8/site-packages/spacy/lang/lex_attrs.py'>
```

I've noticed a few others online getting the same error. Is this a spacy version issue? Is there a workaround? Thanks in advance

**Comment by polm** [comment]
This seems like a version mismatch issue. In v2.2.4 `lex_attrs.py` had a `cluster` defined, but it always returned zero. In v2.3.4 `cluster` was no longer defined. 

You should be able to resolve this by using the same spaCy version in your different environments.

**Comment by sebastiz** [comment]
Thanks. Unfortunately downgrading my spacy version to 2.2.4 has not resolved the error. Is there any suitable workaround?

**Comment by polm** [comment]
Did you get exactly the same error? That's strange, as the particular attribute should be there if the spaCy version is the same.

I'm not really sure what would cause that, but perhaps you could try using spaCy's serialization methods instead of pickle as a workaround. To do that:

1. Load the model on colab
2. After loading the model, use `nlp.to_disk(path)` to save it to a directory
3. copy the directory to your non-colab machine
4. use `spacy.load(path)` to load the model

**Comment by sebastiz** [comment]
I retrained the model in colab and exported:

```
import spacy
nlp = spacy.load('en_core_web_sm')
nlp.to_disk("BarrettsPragueModel_nlp.pkl")
```

I then tried to load and use the model in jupyter:

`dd=spacy.load("BarrettsPragueModel_nlp.pkl")`

but I get the error:

`AttributeError: 'English' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.`

I guess Im not very familiar with spaCy. So instead of using
```

nlp = spacy.load('en_core_web_sm')
nlp.to_disk("BarrettsPragueModel_nlp.pkl")
```

I should be serializing somehow?

**Comment by polm** [comment]
I've become kind of confused about what's going on. To be clear, I'm not really familiar with fast.ai. 

If you have a spaCy model, you can serialize it using `nlp.to_disk`. 

```
import spacy
nlp = spacy.load('en_core_web_sm')
nlp.to_disk("BarrettsPragueModel_nlp.pkl")
```

This is is not serializing your model. This loads the pretrained small model (`en_core_web_sm`) and assigns it to the variable `nlp`. Then it serializes that model (not your model) to a directory named `BarrettsPragueModel_nlp.pkl`, which I don't think is what you want to do. 

I assumed that your fast.ai code resulted in a spaCy model (an instance of the `Language` class). If you have that object, you can use `mymodel.to_disk` to serialize it. spaCy serialization doesn't use pickle anywhere (pretty sure about that), so it should avoid this error you're getting. 

If your spaCy model is just part of a fast.ai model, with other parts that need serialization, then this might be more complicated.

Note that if your model is already serialized, you *should not* have to retrain it. You can just unpickle it in the colab environment you created it in, and then serialize it using `to_disk` (at least for the spaCy part).

**Comment by GCKA** [comment]
Hello,

I am having the same issue. Running Spacy in a VM.
Tried with the following Spacy versions:
- 2.3.0
- 2.3.1
- 2.3.2
- 2.3.5
I'm using en-core-web-lg

I keep having this issue: 

vectorizer = pkl.load(file)
  File "vocab.pyx", line 583, in spacy.vocab.unpickle_vocab
  File "/usr/local/lib/python3.5/dist-packages/srsly/_pickle_api.py", line 23, in pickle_loads
    return cloudpickle.loads(data)
AttributeError: Can't get attribute 'cluster' on <module 'spacy.lang.lex_attrs' from '/usr/local/lib/python3.5/dist-packages/spacy/lang/lex_attrs.py'>

**Comment by polm** [comment]
To be clear, were you also using FastAPI? What spaCy version was used to create the pickle data?

**Comment by GCKA** [comment]
I'm not using FastAPI. spaCy version was 2.3.2 for the creation of the pickle.
Then I had to use the pickle in another VM and installed spaCy 2.3.5 at first. This is where I encountered the issue, then I tried to downgrade but I keep having the same error.

**Comment by polm** [comment]
I am not able to reproduce this :/

Using spaCy 2.3.2 I loaded the `en_core_web_lg` model and pickled it. I then upgraded spaCy to 2.3.5, but I was able to load the pickled model without issue. 

What version of srsly are you using?

**Comment by polm** [comment]
Actually, I do get an E050 when trying to create a document with the deserialized model, but that's related to vectors and is different from the error here. The unpickling itself is without issue.

**Comment by polm** [comment]
Looking at the srsly source more, it seems like cloudpickle might be the issue. cloudpickle is designed for efficiency rather than compatibility, and so it's only supposed to work with the exact same Python version. So this may just be a limitation of how the model is pickled. 

Here's a comment about this in the srsly source:

https://github.com/explosion/srsly/blob/03043242350d5e262bb7b76e3e523ce600ff81e1/srsly/cloudpickle/cloudpickle.py#L69
