### ISSUE TITLE
TypeError in entity linker if kb is not set

### ISSUE THREAD

**Issue by graue70** [explosion/spaCy#8280]
I tried something similar to the example from the [docs](https://spacy.io/api/entitylinker#set_kb):
```python
def create_kb(vocab):
    kb = KnowledgeBase(vocab, entity_vector_length=128)
    kb.add_entity(...)
    kb.add_alias(...)
entity_linker = nlp.add_pipe("entity_linker")
entity_linker.set_kb(create_kb)
```
I actually forgot to add the line `return kb` in `create_kb()`. Running the code leads to the following, not very nice looking error:
```
File "[...]/venv/lib/python3.8/site-packages/spacy/pipeline/entity_linker.py", line 159, in validate_kb
    if len(self.kb) == 0:
TypeError: object of type 'NoneType' has no len()
```

I think there should be a simple check for `None` added to this line:
https://github.com/explosion/spaCy/blob/ff5cf3606cf354c7639ce40b81cacc93bfb03583/spacy/pipeline/entity_linker.py#L159

I would open a pull request, but I don't know whether you want a new error message or whether I should change the existing one.

**Comment by svlandeg** [comment]
> I would open a pull request, but I don't know whether you want a new error message or whether I should change the existing one.

Sounds good, we welcome a PR to deal with this edge case and raise a custom error. You can add a new error message to `spacy.errors` and raise it when `kb is None` (which really shouldn't happen)
