### ISSUE TITLE
Downloading models broken in 2.3.6

### ISSUE THREAD

**Issue by rbange** [explosion/spaCy#8286]
## How to reproduce the behaviour
Calling `spacy download <anymodel>` results in a `TypeError: can only concatenate list (not "tuple") to list` 

## Your Environment
spacy 2.3.6

## How to fix
https://github.com/explosion/spaCy/commit/41ee75ac6dba87a6ea97dc4539fe1308a158c309 effectively broke this command as `pip_args` is now a Tuple:
https://github.com/explosion/spaCy/blob/2c1de4b9a4d0e277a2fc0bbc3f9e94a8a1e811a4/spacy/cli/download.py#L131

The behavior is fixed in 3.x (https://github.com/explosion/spaCy/commit/b9573e9e2232c3a91e7713f78191a23d4d3e9c77), but not in 2.3.x by simply casting `pip_args` to a list:
https://github.com/explosion/spaCy/blob/ff5cf3606cf354c7639ce40b81cacc93bfb03583/spacy/cli/download.py#L108

However if one cannot update to 3.0 (e.g. because of using prodigy 1.10) this bug effectively breaks the model downloading as explained in various documentations (spacey and prodigy)

**Comment by adrianeboyd** [comment]
Thanks for the report, we will have to yank this release and fix it in v2.3.7. In the meanwhile, please use v2.3.5.

**Comment by adrianeboyd** [comment]
Sorry about that! Please upgrade to v2.3.7 now instead.
