### ISSUE TITLE
Is there a way to remove a particular entity from a knowledge base given their entity id?

### ISSUE THREAD

**Issue by epb378** [explosion/spaCy#8305]
## Spacy knowledge base

Is there an elegant way to remove an entity from a knowledge base? It looks like you might be able to copy all the existing entities (minus the one to be deleted) to a new kb, but this doesn't seem like an elegant approach, and it doesn't look like it will keep the probabilities of each alias being assigned to each entity.
[source](https://github.com/explosion/spaCy/blob/master/spacy/kb.pyx)

**Comment by polm** [comment]
Since this is not a bug report I'm going to move it to a Discussion.
