### ISSUE TITLE
Lemma of feminine and masculine are inconsistent for some data in French

### ISSUE THREAD

**Issue by Rajgeel** [explosion/spaCy#8317]
Hello!

I'm using spacy for a few months now. I am using the French model fr_core_news_sm and the version is 3.0.0 and also adding melt_tagger pipeline. The problem is that I am giving the feminine and masculine of the same words as input but it is not giving the same lemma for the feminine and masculine of the same words for few words. Ideally, it should give the same lemma for the same feminine and masculine words because it gives the masculine lemma of any words.  I am sharing the code snippet and also sharing some feminine and masculine words for which it is not giving the same lemma.

Then, here is the sample code:

```
import spacy
from spacy_lefff import LefffLemmatizer, POSTagger
from spacy.language import Language

@Language.factory('french_lemmatizer')
def create_french_lemmatizer(nlp, name):
    return LefffLemmatizer(after_melt=True, default=True)

@Language.factory('melt_tagger')  
def create_melt_tagger(nlp, name):
    return POSTagger()
 
nlp = spacy.load('fr_core_news_sm')
nlp.add_pipe('melt_tagger', after='parser')
nlp.add_pipe('french_lemmatizer', after='melt_tagger')
doc = nlp(u"Apple cherche a acheter une startup anglaise pour 1 milliard de dollard")
for d in doc:
    print(d.text, d.pos_, d._.melt_tagger, d._.lefff_lemma, d.tag_, d.lemma_)
```

Following are the few words for which it is not giving the same lemma for the same feminine and masculine words:

         |           masculine(A)               |                feminine (B)              |              d.lemma(A)                 |             d.lemma(B)           |
         |  ----------------------------------  | ---------------------------------------- | ------------------------------------    |  -----------------------------   |
         |           régisseur                  |                régisseuse                |              régisseur                  |              régisseus           |
         |        masseur kinésithérapeute      |          masseuse kinésithérapeute       |          masseur kinésithérapeute       |   masseus kinésithérapeute       |
         |        enseignant des écoles         |            enseignante des écoles        |            enseigner un école           |       enseignant de école        |
         |        maître d’école primaire       |          maîtresse d’école primaire      |          maître décole primaire         |      maîtresse décole primaire   |

Following are the few words for which it is giving the same lemma for the same feminine and masculine words:

         |           masculine(A)               |                feminine (B)              |              d.lemma(A)                 |             d.lemma(B)           |
         |  ----------------------------------  | ---------------------------------------- | ------------------------------------    |  -----------------------------   |
         |      professeur d’art dramatique     |       professeure d’art dramatique       |       professeur dart dramatique        | professeur dart dramatique       |
         |            chauffeur de car          |             chauffeuse de car            |             chauffeur de car            |       chauffeur de car      |
         |            gérant de tutelle         |             gérante de tutelle           |             gérant de tutelle           |       gérant de tutelle          |
         |            formateur interne         |             formatrice interne           |             formateur interne           |       formateur interne     |

## Your Environment

- Operating System: Linux 20.04
- Python Version Used: Python 3.8.5
- spaCy Version Used: spacy  3.0.4 
- Environment Information: 
         - **Models**: fr_core_news_sm  3.0.0
         - **spacy-lefff**: 0.4.0

**Comment by adrianeboyd** [comment]
Hi, I'm not sure whether you're concerned about the Lefff output or you're just pointing out problems with the default French rule-based lemmatizer by comparing it to Lefff? `LefffLemmatizer` only sets `token._.lefff_lemma`, so you won't see its lemmas in `token.lemma_`. 

Overall, I'm not surprised that the `LefffLemmatizer` has better performance than the default rule-based lemmatizer since it includes a large lexical database.

If you don't need the default lemmatizer, you can remove it with `nlp.remove_pipe("lemmatizer")`.

License-wise it looks like we could consider adding the `lefff` lemmatizer as an option for French or with some additional effort related to data formats / serialization, include it in the `fr_core_news_sm` pipeline.
