### ISSUE TITLE
Entity Recognition example 3 fails (version 2.0)

### ISSUE THREAD

**Issue by vaulttech** [explosion/spaCy#832]
After #803 , I tried the example 3 again, and it fails in the last line.

```
In [79]: doc.ents = [('London', u'GPE', 0, 1)]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-79-2597d30e8b4a> in <module>()
----> 1 doc.ents = [('London', u'GPE', 0, 1)]

c:\python27\lib\site-packages\spacy\tokens\doc.pyx in spacy.tokens.doc.Doc.ents.__set__ (spacy/tokens/doc.cpp:8870)()
    368                     ent_type, start, end = ent_info
    369                 else:
--> 370                     ent_id, ent_type, start, end = ent_info
    371                 if ent_type is None or ent_type < 0:
    372                     # Mark as O

TypeError: an integer is required
```

I believe the problem is the same as in issue #803 (at least using `doc.vocab.strings['GPE'])` seems to have fixed the problem). I will create a pull request soon with the fix.

Still, I don't understand what the "ent_id" is used for. If I do:

```
In [114]: doc
Out[114]: London is a big city in the United Kingdom.

In [115]: doc.ents =  [('LondonCity', doc.vocab.strings['GPE'], 0, 1)]

In [116]: doc.ents
Out[116]: (London,)

In [117]: doc.ents[0].ent_id_
Out[117]: u''   # <-- I was expecting "LondonCity"

In [118]: doc.ents[0].ent_id
Out[118]: 0L   # <-- And here I expected some number associated with "LondonCity"
```

that is... it doesn't seem to use `ent_id` anyway. Am I doing something wrong?

I am using spaCy in a Windows 7 Ultimate, Service Pack 1, 64-bit, with Python 2.7.13. I installed spaCy today following the tutorial (i.e., with pip install -U spacy). It's version in my computer is 1.6.0.

**Comment by ines** [comment]
Thanks for the report and pull request! 👍  `doc.vocab.strings` should do the trick. 

The way this is currently handled is not ideal, so it should be fixed in spaCy at some point to make things more convenient and avoid this extra step.

**Comment by UtkarshKhare** [comment]
Hie @honnibal and All,

Please help me out with this as i am done till NER but got stuck while using the code available at the documentations.

doc = nlp(u'London is a big city in the United Kingdom.')
doc.ents = []
assert doc[0].ent_type_ == ''
#doc.ents = [Span(0, 1, label='GPE')]
#doc.ents = [Span(doc, 0, 1, label=doc.vocab.strings['GPE'])]
docs.ents = [spacy.tokens.span.Span(doc, 0, 1, label='GPE')]
assert doc[0].ent_type_ == 'GPE'
doc.ents = []
doc.ents = [(u'LondonCity', u'GPE', 0, 1)]

Encountering with the error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-104-4aa5c529e4e8> in <module>()
      4 #doc.ents = [Span(0, 1, label='GPE')]
      5 #doc.ents = [Span(doc, 0, 1, label=doc.vocab.strings['GPE'])]
----> 6 docs.ents = [spacy.tokens.span.Span(doc, 0, 1, label='GPE')]
      7 assert doc[0].ent_type_ == 'GPE'
      8 doc.ents = []

AppData\Local\Continuum\Anaconda3\lib\site-packages\spacy\tokens\span.pyx in spacy.tokens.span.Span.__cinit__ (spacy/tokens/span.cpp:3332)()

Please help me out with this , immediate help is highly appreciated.
Thanks,
