### ISSUE TITLE
What is [initialize] vector='model' and what are the differences between stock models?

### ISSUE THREAD

**Issue by source19069** [explosion/spaCy#8328]
We have a trained a bioinformatics model using spacy for inference of numeric test values associated with specific disease treatments, with good scores. The input datasets were created using the spacy _en_core_web_sm_ model. 

We'd now like to compare our results by generating other models using different stock models as a base, so we'd like to understand the difference between, say the _en_core_web_sm_ and _en_core_web_lg_ models.

Obviously we can just rebuild the datasets using different as bases and train new models, but what is the effect of using 

[initialize]
vector='model' 

in the config file during training?

We used 'en_core_web_lg' for the existing model training and the statistics and results look good, but we would really like to know what effect this parameter actually has, if any,  on the trained model.

Thank you.

**Comment by polm** [comment]
Since this is a usage question I'm moving it to Discussions.
