### ISSUE TITLE
How to use Doc.__init__ with heads

### ISSUE THREAD

**Issue by pb-jeff-oneill** [explosion/spaCy#8329]
I'm trying to create a Doc from the constructor with specified heads like this:

> nlp = spacy.blank('en')
> d = Doc(nlp.vocab, ['The', 'cat'], heads=[1,1])

The goal is for 'cat' to be the root and also the head for 'The' like [this](https://explosion.ai/demos/displacy?text=The%20cat&model=en_core_web_sm&cpu=0&cph=0).

I've tried many combinations of values for heads, but the result of 
> for tk in d: print(tk, tk.head, tk.head.i)

is always

> The The 0
> cat cat 1

or a value error.

I'm using spacy 3.0.6.

I'm completely stumped and it would be great if the docs could provide more details of how to do this correctly.

Thank you!

## Which page or section is this issue related to?
https://spacy.io/api/doc#init

**Comment by polm** [comment]
Since this is a usage question and not a bug I'm going to move it to Discussions.
