### ISSUE TITLE
Type checking in vscode

### ISSUE THREAD

**Issue by ezorita** [explosion/spaCy#8363]
## How to reproduce the behaviour

Not really a bug, but rather an issue with type checking using vscode. Not sure if this is an issue of spacy or the vscode Pylance extension...
```Python
import spacy
from spacy.tokens import Doc, Span, Token
from spacy.language import Language
from spacy.lang.en import English
```

Importing `Doc`, `Span`, or `Token` triggers an **unknown import symbol**.

![image](https://user-images.githubusercontent.com/3889419/121724182-cec1de00-cae7-11eb-85f7-dff9a87f6047.png)

## Your Environment

* Operating System: Ubuntu 20.04
* Python Version Used: 3.8.5
* spaCy Version Used: 3.0.6
* Environment Information: vscode 1.57.0 with Pylance v2021.6.1

**Comment by polm** [comment]
I believe this is because those types are defined in Cython and therefore don't have normal type annotations. 

Since this is not a bug report I'm going to move it to a Discussion.
