### ISSUE TITLE
Span.lemma joins tokens with spaces unconditionally, which is wrong for languages like Japanese

### ISSUE THREAD

**Issue by solarmist** [explosion/spaCy#8368]
https://github.com/explosion/spaCy/blob/f4008bdb13e262c389e3d0c7017a634605f6e706/spacy/tokens/span.pyx#L757

```
import spacy
nlp = spacy.load("ja_core_news_sm")
doc = nlp("本須麗乃は本が好きだ。")
name = doc[:3]
print(name.text)
print(name.lemma_)
print(name.text != name.lemma_)
```

The lemma output gives us "本 須 麗乃" which introduces spaces between tokens.

**Comment by polm** [comment]
Nice catch. This also doesn't work with other languages if you have punctuation or a hyphenated multi-token word.
