### ISSUE TITLE
Non-deterministic lemmatization for pretrained Greek models

### ISSUE THREAD

**Issue by npit** [explosion/spaCy#8381]
## How to reproduce the behaviour

Snippet `code.py` with the random seed fixed, that runs in CPU and prints lemmas with a [greek model](https://spacy.io/models/el#el_core_news_sm):
```python
import spacy
import numpy

numpy.random.seed(42)
spacy.util.fix_random_seed(42)
nlp = spacy.load("el_core_news_sm")

doc = nlp("Τις δύο προηγούμενες χρονιές, οι υποψήφιοι της είχαν τη δυνατότητα να επιλέξουν ανάμεσα στο παλαιό και το νέο σύστημα εξετάσεων, όμως το 2021 τα μαθήματα είναι κοινά για όλους.")

print("\n".join([t.lemma_ for t in doc]))
```

Running the code three times, saving the output is saved and comparing the output files with `diff`:

```bash
for x in $(seq 1 3); do python3 code.py > "l$x"; done; 
echo "1 vs 2"; diff l1 l2; 
echo "1 vs 3"; diff l1 l3;
```

Output:
```
Compare 1 vs 2:
13c13
< επιλέζω
---
> επιλέξω
21c21
< εξετάσεο
---
> εξετάσεα
Compare 1 vs 3:
21c21
< εξετάσεο
---
> εξετάσεα
27c27
< μαθήματο
---
> μαθήματας
```
I.e., there are differences in the lemmatization prediction. Similar behaviour is observed with the `el_core_news_md` model.
How can I fix the random seed / apply a workaround to guarantee deterministic behaviour?

## Environment info:
- **spaCy version:** 3.0.6
- **Platform:** Linux-5.12.9-arch1-1-x86_64-with-glibc2.2.5
- **Python version:** 3.8.9
- **Pipelines:** el_core_news_md (3.0.0), en_core_web_sm (3.0.0), el_core_news_sm (3.0.0)

**Comment by adrianeboyd** [comment]
Closing duplicate issue, see #8382.
