### ISSUE TITLE
Non-deterministic lemmatization with Greek pretrained models

### ISSUE THREAD

**Issue by npit** [explosion/spaCy#8382]
## How to reproduce the behaviour
Code implementing lemmatization for Greek and printing output lemmas, using a provided pretrained model:
```python
import spacy
import numpy


numpy.random.seed(42)
spacy.util.fix_random_seed(42)
nlp = spacy.load("el_core_news_sm")

doc = nlp("Τις δύο προηγούμενες χρονιές, οι υποψήφιοι της είχαν τη δυνατότητα να επιλέξουν ανάμεσα στο παλαιό και το νέο σύστημα εξετάσεων, όμως το 2021 τα μαθήματα είναι κοινά για όλους.")

print("\n".join([t.lemma_ for t in doc]))
```
Invokation of the above script 3 times, and comparison with `diff` of the output lemmas:
```bash
for x in $(seq 1 3); do python3 code.py > "l$x"; done; 
echo "Compare 1 vs 2:"; diff l1 l2; 
echo "Compare 1 vs 3:"; diff l1 l3;
```
Output:
```
Compare 1 vs 2:
6c6
< η
---
> ο
21c21
< εξετάσεα
---
> εξετάσεο
Compare 1 vs 3:
21c21
< εξετάσεα
---
> εξετάσεο
```
I.e., there are differences -- lemmatization output is not deterministic. Similar behaviour is observed with the `el_core_news_md` model. 
How can I fix the random seed or apply a workaround / fix to guarantee deterministic behaviour of the pipeline and the lemmatization output?

## Your Environment
- **spaCy version:** 3.0.6
- **Platform:** Linux-5.12.9-arch1-1-x86_64-with-glibc2.2.5
- **Python version:** 3.8.9
- **Pipelines:** el_core_news_md (3.0.0), en_core_web_sm (3.0.0), el_core_news_sm (3.0.0)

**Comment by adrianeboyd** [comment]
Greek has a custom lemmatizer that uses `set`, leading to non-deterministic results. This is the line that needs to be changed to remove duplicates without using `set`:

https://github.com/explosion/spaCy/blob/507422149f343f10b2d78ad217283d3f465d7fef/spacy/lang/el/lemmatizer.py#L60

The default lemmatizer does this instead:

```
forms = list(dict.fromkeys(forms))
```

**Comment by npit** [comment]
Thanks @adrianeboyd  -- is there an estimate for when the fix will be included in a stable release?

**Comment by adrianeboyd** [comment]
Sorry, we don't have an estimated release date.

**Comment by npit** [comment]
Got it, thanks! Closing this.
