### ISSUE TITLE
Are spacy.tokens.{Doc, Token, etc.} supposed to be typed? If yes: bug report, if not: feature request

### ISSUE THREAD

**Issue by ldorigo** [explosion/spaCy#8383]
## How to reproduce the behaviour

Hello, 
Throughout the documentation you use type annotations like `List[Doc]` or `Token`. when I do that, my language server (Pylance which uses pyright as a type checker) complains that the type of `Doc` (or the others) is unknown.

Is that supposed to be the case? Is so, it would be great to have type annotations for those classes (although I don't know how/how well type annotations work for cpython code). If not, then something is wrong with either spacy's imports or Pylance - I'm happy to give more information on demand. 

## Info about spaCy

- **spaCy version:** 3.0.6
- **Platform:** Linux-5.10.39-1-lts-x86_64-with-glibc2.33
- **Python version:** 3.9.5
- **Pipelines:** en_core_sci_scibert (0.4.0)

**Comment by hixan** [comment]
Would writing a stubfile for the cpython work in this instance?

**Comment by polm** [comment]
1. This is the same as #8373 
2. cpython and cython are not the same thing, and these classes are written in Cython.

I'm going to close this as a dupe, but please feel free to continue the discussion over at #8373.
