### ISSUE TITLE
cuda out of memory while trying to train a model with Transformer model of spacy

### ISSUE THREAD

**Issue by codester13** [explosion/spaCy#8392]
I'm trying to train a custom NER model on top of Spacy transformer model. For faster training, I'm running it on a GPU with cuda on Google Colab Pro with High-Ram server.

After the first iteration, I get an error:

> RuntimeError: CUDA out of memory. Tried to allocate 480.00 MiB (GPU 0; 11.17 GiB total capacity; 9.32 GiB already allocated; 193.31 MiB free; 10.32 GiB reserved in total by PyTorch)

For the above error I tried emptying cache too. But still I'm getting this error. Seems like it’s not freeing up enough space.

```
import torch
torch.cuda.empty_cache()
```
Moreover I also tried reducing the batch sizes even to 2. Still the same error occurs.

## Your Environment

- Python Version Used: 3.7.10
- spaCy Version Used: 3.0.6
- Environment Information: Google Colab

**Comment by polm** [comment]
Can you paste your whole training config? How large are your training documents?

**Comment by codester13** [comment]
the following is my complete config file.

> [paths]
> train = null
> dev = null
> vectors = null
> init_tok2vec = null
> 
> [system]
> gpu_allocator = "pytorch"
> seed = 0
> 
> [nlp]
> lang = "en"
> pipeline = ["transformer","ner"]
> tokenizer = {"@tokenizers":"spacy.Tokenizer.v1"}
> disabled = []
> before_creation = null
> after_creation = null
> after_pipeline_creation = null
> 
> 
> [components]
> 
> [components.ner]
> source = "en_core_web_trf"
> moves = null
> update_with_oracle_cut_size = 100
> 
> [components.ner.model]
> @architectures = "spacy.TransitionBasedParser.v1"
> state_type = "ner"
> extra_state_tokens = false
> hidden_width = 64
> maxout_pieces = 2
> use_upper = false
> nO = null
> 
> [components.ner.model.tok2vec]
> @architectures = "spacy-transformers.TransformerListener.v1"
> grad_factor = 1.0
> pooling = {"@layers":"reduce_mean.v1"}
> 
> [components.transformer]
> source = "en_core_web_trf"
> max_batch_items = 2
> set_extra_annotations = {"@annotation_setters":"spacy-transformers.null_annotation_setter.v1"}
> 
> [components.transformer.model]
> @architectures = "spacy-transformers.TransformerModel.v1"
> name = "roberta-base"
> 
> [components.transformer.model.get_spans]
> @span_getters = "spacy-transformers.strided_spans.v1"
> window = 128
> stride = 96
> 
> [components.transformer.model.tokenizer_config]
> use_fast = true
> 
> [corpora]
> 
> [corpora.dev]
> @readers = "spacy.Corpus.v1"
> path = ${paths.dev}
> max_length = 0
> gold_preproc = false
> limit = 0
> augmenter = null
> 
> [corpora.train]
> @readers = "spacy.Corpus.v1"
> path = ${paths.train}
> max_length = 500
> gold_preproc = false
> limit = 0
> augmenter = null
> 
> [training]
> accumulate_gradient = 3
> dev_corpus = "corpora.dev"
> train_corpus = "corpora.train"
> seed = ${system.seed}
> gpu_allocator = ${system.gpu_allocator}
> dropout = 0.1
> patience = 1600
> max_epochs = 0
> max_steps = 20000
> eval_frequency = 200
> frozen_components = []
> before_to_disk = null
> 
> [training.batcher]
> @batchers = "spacy.batch_by_padded.v1"
> discard_oversize = true
> size = 2000
> buffer = 256
> get_length = null
> 
> [training.logger]
> @loggers = "spacy.ConsoleLogger.v1"
> progress_bar = false
> 
> [training.optimizer]
> @optimizers = "Adam.v1"
> beta1 = 0.9
> beta2 = 0.999
> L2_is_weight_decay = true
> L2 = 0.01
> grad_clip = 1.0
> use_averages = false
> eps = 0.00000001
> 
> [training.optimizer.learn_rate]
> @schedules = "warmup_linear.v1"
> warmup_steps = 250
> total_steps = 20000
> initial_rate = 0.00005
> 
> [training.score_weights]
> ents_per_type = null
> ents_f = 2.0
> ents_p = 2.0
> ents_r = 6.0
> 
> [pretraining]
> 
> [initialize]
> vectors = null
> init_tok2vec = ${paths.init_tok2vec}
> vocab_data = null
> lookups = null
> 
> [initialize.components]
> 
> [initialize.tokenizer]
> 

For training data I have around 500 text documents.

**Comment by polm** [comment]
How long are your individual training documents? Are they like sentences or multi-page documents?

When posting your config, rather than the blockquote syntax, it's better if you wrap it in code fences (triple backticks: ```). See the [markdown guide](https://guides.github.com/features/mastering-markdown/).

**Comment by codester13** [comment]
Each document has some number of sentences. Not more than a page per document.

**Comment by polm** [comment]
OK, that's somewhat helpful. A page can have a lot of tokens, so that might be taking up too much memory. You might want to consider breaking your document into paragraphs or other smaller units. For NER the effects of long-distance context are generally limited, so you typically won't lose much by doing this.

Your config mostly looks OK, one thing you could try adjusting is the `size` in `training.batcher`. Maybe make it very small, like 100 or 200, and then adjust it up if that works.

**Comment by adrianeboyd** [comment]
From your report it's not clear when it's running out of memory, but be aware that there are two relevant batch sizes. The batch size used during the model update step comes from `training.batcher` and the batch size during the eval step comes from `nlp.batch_size` (which seems to be missing from your config example even though it's a required parameter?).

`nlp.batch_size` is also the batch size used by the pipeline by default when you use `nlp.pipe` in the future when you're just running the pipeline, so it can be useful to adjust this to a reasonable default for your planned task / env.
