### ISSUE TITLE
Restricting Entity Labels across Models

### ISSUE THREAD

**Issue by source19069** [explosion/spaCy#8399]
We are basing our training and training Docs on different models to determine which has the best performance. For example, let's say en_core_web_sm. Is there a way to use this model without using any of its named entities (PERSON, ORG etc)? All we would like to see in the trained model is the entity label that we've trained it for.

I have attached a copy of our training config file. In particular, I'd like to point out two changes we've made to achieve restricting entities (which of course, have not worked out):

[components.ner]
source = "en_core_web_sm" (This line was added, those below were commented.)
#factory = "ner"
#moves = null
#update_with_oracle_cut_size = 100

[initialize]
vectors = "en_core_web_sm"  (Only this line was changed)
init_tok2vec = ${paths.init_tok2vec}
vocab_data = null
lookups = null
before_init = null
after_init = null

Any guidance you can provide would be appreciated. Thank you!

[en_core_web_sm.config.txt](https://github.com/explosion/spaCy/files/6657921/en_core_web_sm.config.txt)

## Your Environment

 python -m spacy info --markdown

## Info about spaCy

- **spaCy version:** 3.0.1
- **Platform:** Windows-2012ServerR2-6.3.9600-SP0
- **Python version:** 3.7.6
- **Pipelines:** en_core_sci_lg (0.4.0), en_core_sci_md (0.4.0), en_core_sci_sm (0.4.0), en_core_web_lg (3.0.0), en_core_web_md (3.0.0), en_core_web_sm (3.0.0), en_core_web_trf (3.0.0), en_ner_bionlp13cg_md (0.4.0), en_pdl1_value (0.0.1), en_pdl1_value_trf (0.0.1)

**Comment by polm** [comment]
Since this is a question and not a bug report I'm going to move it to Discussions.
