### ISSUE TITLE
Google colab cannot find installed spacy model : OSError: [E050] 

### ISSUE THREAD

**Issue by Hadrien-Cornier** [explosion/spaCy#8417]
## Description 
running in Google Colab the command : 

`! python -m spacy download en_core_web_lg`

followed by  :  

```python
import spacy
nlp = spacy.load('en_core_web_lg')
```
returns the following error : 

```
OSError: [E050] Can't find model 'en_core_web_lg'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```
## How to reproduce the behaviour
Run this google colab : 
https://gist.github.com/Hadrien-Cornier/5b87e232277c8063756f13b70417c64d
## Your Environment

* Operating System:
`NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic`
* Python Version Used: Python 3.7.10
* spaCy Version Used: 2.2.4
* Environment Information: Google colab

**Comment by polm** [comment]
Glad you found a workaround, though that shouldn't be necessary. Maybe see https://github.com/explosion/spaCy/discussions/7435 for tips on debugging Jupyter environment weirdness.

**Comment by SamyAteia** [comment]
I stumbeled upon the same error while playing with german and spacy in google colab. 
`spacy.load` does not work, but importing the package directly does work:
```
import de_core_news_sm
nlp_de = de_core_news_sm.load()
```
see this google colab notebook:
https://colab.research.google.com/drive/1NCVd_f7z9TS0nUI9hYiPlWixSSQgqa2-?usp=sharing
