### ISSUE TITLE
How training data looks like for Relation extraction component? 

### ISSUE THREAD

**Issue by Ibrokhimsadikov** [explosion/spaCy#8429]
Hello dear SpaCy funs,

Quick question regarding very important tutorial on Relation extraction component. Everything seems to be pretty clear in terms development and architecture of the trainable component, but it is still blur for me how training data looks like for relation  extraction. For ner it is pretty clear and very well documented, but what about Relation extraction. Please, help me to understand and discover it. in rel_component tutorial they give us overall prodigy annotated json, but it  has parsing and tokens as well, seemed  they re-trained everything on the one go, what if I am only interested in ner and relation extraction part.

Thank you for your time

**Comment by svlandeg** [comment]
Hi! As a maintenance note: this is a good question for the discussions forum, so I'll move it there. The original issue will be closed and will link through to the open discussion thread.
