### ISSUE TITLE
keras_parikh_entailment model location confusion

### ISSUE THREAD

**Issue by znat** [explosion/spaCy#845]
I am a bit confused about the model location:

[Here](https://github.com/explosion/spaCy/blob/master/examples/keras_parikh_entailment/__main__.py#L45), the location where the model is actually saved differs from what is printed. `model_dir`is a supplied argument, so it seems it should be the model destination but it's used neither to save the model nor to load it. 

```
   if not (nlp.path / 'similarity').exists():
        (nlp.path / 'similarity').mkdir()
    print("Saving to", model_dir / 'similarity')
```

**Comment by honnibal** [comment]
Thanks. For now I'll remove the option, so that it at least reflects the current behaviour. It'll be nice to add the option back, but it's a little awkward because the code assumes the `similarity/` directory is located along with the other spaCy models.
