### ISSUE TITLE
NER of spacy 3.0.6 does not recognize GPE which was recognized in version 2.2.4

### ISSUE THREAD

**Issue by drbarak** [explosion/spaCy#8474]
Using the doc= nlp('haifa, israel') and checking entities, in version 2.4.4 both were recognized as GPE, whereas in version 3.0.6 only 'israel' is recognized.
It happened for other combinations as well.

I tested it on Colab and on PythonAnywhere - same results

For the time being I went back to version 2.2.4
Python Version Used on PythonAnywhere server = 3.8

My email is drbarak@talkie.co.il and my name is Zvi

**Comment by polm** [comment]
This is not a bug, so I'm going to move it to a Discussion.

Also not we are not going to email you.
