### ISSUE TITLE
**Config Validation Error** when load en_core_web_trf

### ISSUE THREAD

**Issue by su-park** [explosion/spaCy#8483]
Thank you for your swift response.

Since I am working on closed environment there is no way but to download and install the model in [repository](https://github.com/explosion/spacy-models/releases/tag/en_core_web_trf-3.0.0) manually.

Is there any way to download updated version?

> ## How to reproduce the behaviour
> When I try to load 'en_core_web_trf' it returns below error.
> 
> ```
> import spacy
> nlp = spacy.load("en_core_web_trf")
> ```
> 
> ```
> ConfigValidationError: 
> 
> Config validation error
> 
> batch_size   field required
> 
> {'lang': 'en', 'pipeline': ['transformer', 'tagger', 'parser', 'ner', 'attribute_ruler', 'lemmatizer'], 'disabled': [], 'before_creation': None, 'after_creation': None, 'after_pipeline_creation': None, 'tokenizer': {'@tokenizers': 'spacy.Tokenizer.v1'}}
> ```
> 
> ## Your Environment
> * **spaCy version:** 3.0.6
> * **Platform:** Linux-4.15.0-45-generic-x86_64-with-Ubuntu-18.04-bionic
> * **Python version:** 3.7.5
> * **Pipelines:** en_core_web_sm (3.0.0), en_core_web_trf (3.0.0a0)

**Comment by polm** [comment]
Don't open a new issue, please reply in your Discussion thread. It's here:

https://github.com/explosion/spaCy/discussions/8480
