### ISSUE TITLE
Present spacy.cli.download in the doc as an alternative procedure

### ISSUE THREAD

**Issue by linogaliana** [explosion/spaCy#8494]
In some situations, a python user does not have access to command line and cannot install trained pipeline. In my case, I was unable to run

```python
python -m spacy download fr_core_news_sm
```

and thus could not download the required models. I give an example regarding French models but this is a generalizable *issue*.

I managed to solve this problem by using, within a python session,

```python
import spacy
spacy.cli.download('fr_core_news_sm')
```

I think this would be great to also propose, in the right side of the screen, this alternative procedure. This could also be presented in the `README` in [this section](https://github.com/explosion/spaCy#-download-model-packages)

## Which page or section is this issue related to?

* [README on Github](https://github.com/explosion/spaCy#-download-model-packages)
* [French - spaCy](https://spacy.io/models/fr#fr_core_news_sm)
* and more generally all suggestions in [models sections](https://spacy.io/models)

**Comment by polm** [comment]
Can you give an example of a situation when a user is unable to use the command line?

**Comment by svlandeg** [comment]
FYI - This issue has been closed automatically because we merged the PR that added some additional explanations to the docs that should address this :-)
