### ISSUE TITLE
LIKE_URL pattern is not matching on 'bare' urls with a route

### ISSUE THREAD

**Issue by daqieq** [explosion/spaCy#8503]
## How to reproduce the behaviour

I want to identify all URLs given in some text. However, some tokens are clearly URLs but they are not being matched by the `{'LIKE_URL': True}` pattern.

My testing below shows that most URL patterns are captured, but URLs without `http(s)://` which also have a web-site route are not captured by the pattern.

I tried exploring the find_matches cdef ([matcher.pyx#L334](https://github.com/explosion/spaCy/blob/master/spacy/matcher/matcher.pyx#L334)), but I very quickly got lost ...

My test code and output are below as run in a Jupyter notebook.

### Code
```python
import spacy
from spacy.matcher import Matcher

nlp = spacy.load("en_core_web_sm")

url_pattern = [[{'LIKE_URL': True}]]
matcher = Matcher(nlp.vocab)

matcher.add("URL", url_pattern)

tests = [
    ("i cant log onto the http://abc.com/testroute site.",   'http with route'),
    ("i cant log onto the https://abc.com/testroute site.",  'https with route'),
    ("i cant log onto the http://abc.com site.",             'http without route'),
    ("i cant log onto the https://abc.com site.",            'https without route'),
    ("i cant log onto the abc.com site.",                    'bare without route'),
    ("i cant log onto the abc.com/testroute site.",          'bare with route'),
]
url_pos = 6  # position of URL in text tests above

for text, label in tests:
    print(label)
    doc = nlp(text)
    t = doc[url_pos]
    m = nlp.Defaults.url_match(t.text)
    e = nlp.tokenizer.explain(doc.text)[url_pos]
    matches = matcher(doc)
    print('\t', t)        # URL token
    print('\t', m)        # URL match function on the URL token
    print('\t', e)        # tokenizer explaination
    print('\t', matches)  # matches found by the matcher
    print()
```
### Output
```python
http with route
	 http://abc.com/testroute
	 <re.Match object; span=(0, 24), match='http://abc.com/testroute'>
	 ('URL_MATCH', 'http://abc.com/testroute')
	 [(2582013287274679728, 6, 7)]

https with route
	 https://abc.com/testroute
	 <re.Match object; span=(0, 25), match='https://abc.com/testroute'>
	 ('URL_MATCH', 'https://abc.com/testroute')
	 [(2582013287274679728, 6, 7)]

http without route
	 http://abc.com
	 <re.Match object; span=(0, 14), match='http://abc.com'>
	 ('URL_MATCH', 'http://abc.com')
	 [(2582013287274679728, 6, 7)]

https without route
	 https://abc.com
	 <re.Match object; span=(0, 15), match='https://abc.com'>
	 ('URL_MATCH', 'https://abc.com')
	 [(2582013287274679728, 6, 7)]

bare without route
	 abc.com
	 <re.Match object; span=(0, 7), match='abc.com'>
	 ('URL_MATCH', 'abc.com')
	 [(2582013287274679728, 6, 7)]

bare with route
	 abc.com/testroute
	 <re.Match object; span=(0, 17), match='abc.com/testroute'>
	 ('URL_MATCH', 'abc.com/testroute')
	 []
```
The last test case - **`bare with route`** - is the one that does not return a match tuple as do the rest of the test cases.

### Info about spaCy

- **spaCy version:** 3.0.6
- **Platform:** Windows-10-10.0.18362-SP0
- **Python version:** 3.8.8
- **Pipelines:** en_core_web_md (3.0.0), en_core_web_sm (3.0.0), en_core_web_trf (3.0.0)

**Comment by polm** [comment]
Thanks for reporting that, that looks like a bug to me. There might be some interaction with other parts of the tokenizer that explains why things work that way but we'll take a look at it.

**Comment by adrianeboyd** [comment]
There are two different URL settings that are relevant. The first one is a URL regex in the tokenizer, which keeps URLs as a single token (it does match without the initial `http`) and a simpler/quicker `LIKE_URL` method in the lexical attributes that looks more for website URLs than all general URL types.

If this is primarily for use with the `Matcher`, then I mightsuggest using an alternate regex pattern rather than trying to adjust `LIKE_URL`. You could try using the same URL pattern that's used in the tokenizer with `REGEX`. It's available as `spacy.lang.tokenizer_exceptions.URL_PATTERN`, however it also matches email addresses and other kinds of URLs that might not be what you want.

Here's the current URL pattern:

https://github.com/explosion/spaCy/blob/bb781ae7f77d9d36ad7a9d556845e15edd767768/spacy/lang/tokenizer_exceptions.py#L10-L56

You can also modify the `LIKE_URL` lexical attribute if you'd like, see what it looks like here:

https://github.com/explosion/spaCy/blob/bb781ae7f77d9d36ad7a9d556845e15edd767768/spacy/lang/lex_attrs.py#L89-L112

One way to modify these settings is with a custom `before_creation` callback, but to be honest, this has a number of drawbacks. (I can explain more of the issues if you decide to go this way.)

**Comment by adrianeboyd** [comment]
In general, I'd be hesitant to make changes to `LIKE_URL`, since it's hasn't changed much for quite a few years at this point and making changes in the core lexical attributes can affect a lot of users, but we can think about whether a change to also recognize this type of URL makes sense. I can imagine that there are things like patient or case numbers that could have a similar form but not be URLs, as an example.

**Comment by daqieq** [comment]
Admittedly I don't know the impacts to the broader user community, and I'm also unfamiliar with all patient or case numbers that might be structured like a URI. However, I do know that `LIKE_URL` doesn't recognize the following as URLs:

github.com/explosion
spacy.io/usage
prodi.gy/demo

I can use the alternate regex pattern as suggested, but I'd also like to point out that it might be simple enough to change the `tld`  on line 107:
https://github.com/explosion/spaCy/blob/bb781ae7f77d9d36ad7a9d556845e15edd767768/spacy/lang/lex_attrs.py#L107

Making the change shown below and numbering the `return` statements provided the below results:
```python
tld = text.rsplit(".", 1)[1].split(":", 1)[0].split("/", 1)[0]
```
```
(True, 7) 	 prodi.gy
(True, 7) 	 prodi.gy/demo
(True, 7) 	 spacy.io
(True, 7) 	 spacy.io/usage
(True, 1) 	 http://github.com
(True, 1) 	 http://github.com/
(True, 1) 	 https://github.com
(True, 1) 	 https://github.com/
(True, 1) 	 https://github.com:443
(True, 1) 	 https://github.com/:443
(True, 1) 	 https://username:password@github.com
(True, 1) 	 https://username:password@github.com/
(True, 1) 	 https://username:password@github.com:443
(True, 1) 	 https://username:password@github.com/:443
(True, 1) 	 https://:@github.com
(True, 1) 	 https://:@github.com/
(True, 1) 	 https://:@github.com:443
(True, 1) 	 https://:@github.com/:443
(True, 1) 	 http://github.com/explosion
(True, 1) 	 https://github.com/explosion
(True, 1) 	 https://github.com/explosion:443
(True, 1) 	 https://username:password@github.com/explosion
(True, 1) 	 https://username:password@github.com/explosion:443
(True, 1) 	 https://:@github.com/explosion
(True, 1) 	 https://:@github.com/explosion:443
(True, 7) 	 github.com
(True, 7) 	 github.com/
(True, 7) 	 github.com:443
(True, 7) 	 github.com/:443
(False, 4) 	 username:password@github.com
(False, 4) 	 username:password@github.com/
(False, 4) 	 username:password@github.com:443
(False, 4) 	 username:password@github.com/:443
(False, 4) 	 :@github.com
(False, 4) 	 :@github.com/
(False, 4) 	 :@github.com:443
(False, 4) 	 :@github.com/:443
(True, 7) 	 github.com/explosion
(True, 7) 	 github.com/explosion
(True, 7) 	 github.com/explosion:443
(False, 4) 	 username:password@github.com/explosion
(False, 4) 	 username:password@github.com/explosion:443
(False, 4) 	 :@github.com/explosion
(False, 4) 	 :@github.com/explosion:443
```

I think it's also worth pointing out, that the `_tlds` set will need to be updated at some point to include the extended TLD approved by ICANN/IANA - https://data.iana.org/TLD/tlds-alpha-by-domain.txt - **OR** simply removed and replaced with a different validation check. Perhaps a regex pattern is needed here as in the tokenizer.

**Comment by daqieq** [comment]
Would it be more helpful if I submitted a PR with this change? I don't often contribute to OS projects, but I do benefit a lot from them ... offering to help if it would be more useful to review in that format than just my comments above.

**Comment by adrianeboyd** [comment]
You can tell that the `LIKE_URL` code is pretty old, and maybe it would better to use the tokenizer URL pattern after it goes through the quicker initial checks, which could also still just skip tokens with `@` in them.

I don't know for sure, but I don't actually think that many people use `LIKE_URL` in practice, but for ones who do, changes here can be unexpected/problematic. Most of the other lexical attributes have stayed pretty stable over time, so we try to be pretty conservative with changes in these functions.

Don't worry about a PR for this particular instance, it's more that we need to decide internally what to do.
