### ISSUE TITLE
pip install error in windows

### ISSUE THREAD

**Issue by jithurjacob** [explosion/spaCy#851]
Hi guys, I've been trying to setup spacy using pip install. I know conda version is there but I wanted to install using the native approach. I've installed VC++ 2015 build tools, now I'm getting a cl.exe missing source file name error. Any help is much appreciated

* Operating System: Windows 7
* Python Version Used: 3.5
* Environment Information: Anaconda 3 

![image](https://cloud.githubusercontent.com/assets/7101452/23130003/cb96d6f0-f7aa-11e6-814b-5a304868a22f.png)

**Comment by eromoe** [comment]
For me,  it works fine with `Anaconda 3` , but I can't get spacy works on python2.7...

- Operating System: Windows 7 X64
- Python Version Used: 3.5 env
- spaCy Version Used: latest
- Environment Information: Anaconda 3

**Comment by ines** [comment]
We just released v1.7.0. Could you check again to see if it's fixed now? If you're still having problems, feel free to reopen.

* [Release notes](https://github.com/explosion/spaCy/releases) for 1.7.0
* [Models documentation](https://spacy.io/docs/usage/models)
* [Command line interface documentation](https://spacy.io/docs/usage/cli)
