### ISSUE TITLE
Help to map some Chinese PoS tag to universalde dependencies tag

### ISSUE THREAD

**Issue by eromoe** [explosion/spaCy#853]
Hi,
I am trying to make a Chinese tokenizer `thulac` work with spacy.
The first thing is map tag, which follow below tag explanation:
http://universaldependencies.org/u/pos/all.html

But I found there are some tags can't not map:

- h/前接成分  (some post-decorator of word, not adj, maybe either meaningless or meaningful like `non-` in `non-profit`)
- k/后接成分 (some tail-decorator of word, not adj, may have meaning or not)
- t/时间词 (date, time, today, 2016年12月，6:33)
- i/习语 (idiom, may be adj, adv, v, n)
- j/简称 (abbreviation, words for short,  may be adj, adv, v, n)
- o/拟声词 (words mimicking sound of objects)

**Comment by honnibal** [comment]
Hi,

Sorry for the delay getting to this. Thanks for your efforts on making the tagger.

I would say that it's normal that the UD tag scheme doesn't perfectly cover all of your "native" tag set. The POS tag map isn't used for any important purposes internally --- it's just there to calculate features that are useful to the user, specifically the `.pos` attribute, and in most languages it's useful for the `.lemma`, morphology, etc. None of that matters for Chinese.

So I would say you should adopt whatever policy seems useful to you. For instance you might map all the non-fitting tags to the X POS, or something.
