### ISSUE TITLE
Sentencizer produces blank sentences

### ISSUE THREAD

**Issue by dmitra79** [explosion/spaCy#8543]
## How to reproduce the behaviour

Here is an example:
```
import spacy
from spacy.lang.en import English 
nlp = spacy.load("en_core_web_lg")
nlp.add_pipe('sentencizer') 

text="No acute cardiopulmonary process.\nThere is no focal consolidation, pleural effusion or pneumothorax.  Bilateral\r\n nodular opacities that most likely represent nipple shadows. The\r\n cardiomediastinal silhouette is normal.  Clips project over the left lung,\r\n potentially within the breast. The imaged upper abdomen is unremarkable.\r\n Chronic deformity of the posterior left sixth and seventh ribs are noted."
doc=nlp(text)
[sent for sent in doc.sents]
```
This produces 9 sentences:
```
[No acute cardiopulmonary process.,
 ,
 There is no focal consolidation, pleural effusion or pneumothorax.,
  Bilateral
  nodular opacities that most likely represent nipple shadows.,
 The
  cardiomediastinal silhouette is normal.,
  Clips project over the left lung,
  potentially within the breast.,
 The imaged upper abdomen is unremarkable.,
 
  ,
 Chronic deformity of the posterior left sixth and seventh ribs are noted.]
```
of which two consist of empty spaces/new lines.

## Info about spaCy

- **spaCy version:** 3.0.6
- **Platform:** Windows-10-10.0.18363-SP0
- **Python version:** 3.9.5
- **Pipelines:** en_core_web_lg (3.0.0), en_core_web_md (3.0.0), en_core_web_sm (3.0.0)

**Comment by polm** [comment]
spaCy doesn't alter the input string, so the leftover newlines in your input have to go somewhere, whether that be an independent sentence or at the start or end of another sentence. I'm a little surprised that the first newline ended up as its own sentence but that seems harmless? I would recommend you filter out empty sentences in post-processing.

I also notice your raw text has `\r` characters in it. I would filter those out entirely. I'm pretty sure there's no `\n` in the spaCy training data, but I'm very sure there's no `\r`, and they aren't adding anything to your text. For the particular example you gave, I would recommend preprocessing to remove `\r`, replace `\n` with spaces, and collapsing multiple spaces in a row.

**Comment by dmitra79** [comment]
I see - thanks for the explanation!
