### ISSUE TITLE
Possible Memory Leaks for en_core_web_trf inside K8S, no GPU Used

### ISSUE THREAD

**Issue by VMAtm** [explosion/spaCy#8554]
Hi, we're trying to use `en_core_web_trf` inside the K8S container, without GPU, and run into strange behavior.
We got 16 cores of CPU and 10 Gb for each container. After start and loading the model we got 1.9 Gb used (which is expected), but after that we start to analyze texts with model, and memory usage grows, without freeing up.

We tried 3 different approaches: analyze the same 1 document again and again; analyze 64 same documents again and again; analyze different texts each time. The result is the same: after about 2500 documents (no matter are they repeated or are they the same) we got our memory full with container restart. We do not store any results of model in memory, and we do not have any other code rather than calling the model.

What have we tried:

* #8065 and flush_cache_chance = 1
* #7593 and gc.collect, with reloading model object after some time
* #3618 is not applicable, as we need `ner` pipeline in our code

We're using spacy 3.0 and file with model `en_core_web_trf-3.0.0.tar.gz`. It looks like we missing something here, do you have any ideas how to deal with memory leaks in this case?

**Comment by adrianeboyd** [comment]
Hi, can you provide more details about the code that you're running? Without more information, it's pretty hard for us to try to reproduce or debug this kind of case. My initial guess would be that you are keeping the resulting docs in memory in some form, which means that memory fills up with the `doc._.trf_data` tensors.

Some of the notes here might be relevant: https://github.com/explosion/spaCy/issues/7593#issuecomment-828246588

I did test for memory leaks on CPU using valgrind, but I didn't run other tests with a large number of texts on CPU because it would have been slow.

**Comment by VMAtm** [comment]
Hi @adrianeboyd 
Thank you for the quick answer. As I mentioned, I saw that ticket and `trf_data` is being nulled in our code:
```
import spacy


nlp_trf = spacy.load("en_core_web_trf")
nlp_trf.get_pipe('transformer').model.attrs['flush_cache_chance'] = 1
nlp_trf.get_pipe('tagger').model.attrs['flush_cache_chance'] = 1
nlp_trf.get_pipe('parser').model.attrs['flush_cache_chance'] = 1
nlp_trf.get_pipe('ner').model.attrs['flush_cache_chance'] = 1


def analize_text(text, verbose):
    parsed = nlp_trf(text)
    result = {
        'input': text,
        'entities': sorted({(entity.text, entity.label_)
                            for entity in parsed.ents if entity.label_ in {'ORG', 'PERSON'}}),
    }
    parsed._.trf_data = None
    del parsed
    return result
```

This code is being used in a web-service application like this:

```
async def _analize_and_map_text(text):
    if not text.endswith('.'):
        text += '.'
    result = analize_text(text)
    companies = {e[0] for e in result['entities'] if e[1] == 'ORG'}
    people = {e[0] for e in result['entities'] if e[1] == 'PERSON'}
    ...
    return result
```

The memory leak can be reproduced even on the same document. I hope that this is a simple error from our side.

**Comment by adrianeboyd** [comment]
Can you include the output from `spacy info` inside the container and which version of torch?

Can you try adding this before loading the model to see if it makes a difference?

```
import torch
torch.set_num_threads(1)
```

I'm pretty sure the cache flush option doesn't really work as intended. You can try the manual ones mentioned in that thread, but it's not really going to be a solution.

**Comment by VMAtm** [comment]
```
============================== Info about spaCy ==============================

spaCy version    3.0.6
Location         /service/venv/lib/python3.7/site-packages/spacy
Platform         Linux-5.8.9-1.el7.elrepo.x86_64-x86_64-with-debian-10.4
Python version   3.7.4
Pipelines        en_core_web_trf (3.0.0)
```

Versions

```
torch              1.9.0
transformers       4.6.1
```

Will check with 1 thread and return back here

**Comment by VMAtm** [comment]
@adrianeboyd I can confirm that in case of 1 thread there is no memory leak, only 1 core is being used, without any memory increase. Moreover, i works with any number of threads being set directly! So, `torch.set_num_threads` is ultimate solution for our problem.

My wild guess here is that `torch` somehow tries to calculate available memory for the calculations, and instead of available memory for **container** it gets available memory on **physical machine** and do not handle it appropriately.

With any numbers of threads the memory consumption is about 2.1 Gb during calculations, with corresponding number of cores in use.

So, the issue is resolved now. :)

**Comment by kaushikepi** [comment]
@adrianeboyd Do we need to add multiprocessing even after adding `torch.set_num_threads(1)` before loading the spacy transformer model in a GPU-based server?

**Comment by kaushikepi** [comment]
### API codebase using in production
```
import time
from http import HTTPStatus
from typing import Any, Dict, List, Optional

import spacy
from spacy.language import Language

import torch
from fastapi import FastAPI, Request
from pydantic import BaseModel
from thinc.api import require_gpu, set_gpu_allocator

app = FastAPI(
    title="NPI - Made with Transformers",
    description="Predict provider namse given a text input from a medical chart",
    version="0.1",
)

if spacy.prefer_gpu():
    print("\n\033[92m" + "✔ Using GPU" + "\033[0m\n")
    set_gpu_allocator("pytorch")
    require_gpu(0)
else:
    print("\n\033[91m" + "✘ NOT Using GPU!" + "\033[0m\n")

torch.set_num_threads(1)
nlp_trf = spacy.load(
    "en_core_web_trf", exclude=["tagger", "parser", "attribute_ruler", "lemmatizer"]
)

@Language.component("remove_trf_data")
def remove_trf_data(doc):
    doc._.trf_data = None
    return doc

nlp.add_pipe("remove_trf_data")

class RecordRequest(BaseModel):
    page_no: str
    page_text: str


class RecordRequestIn(BaseModel):
    values: List[RecordRequest]


class RecordResponseOut(BaseModel):
    entities: Dict[int, Optional[List[Any]]]
    time_taken: str


@app.get("/", tags=["General"])
def _index(request: Request):
    """Health check."""
    response = {
        "message": HTTPStatus.OK.phrase,
        "status-code": HTTPStatus.OK,
        "nlp_pipeline": nlp_trf.pipe_names,
        "data": {},
    }

    return response


@app.post("/entities", response_model=RecordResponseOut)
def extract_per_entities(body: RecordRequestIn):
    start_time = time.time()

    records = body.values
    chart_info_pagewise = {}

    page_ids = [doc.page_no for doc in records]
    texts = [doc.page_text for doc in records]

    for doc_id, spacy_doc in zip(page_ids, nlp_trf.pipe(texts)):
        pagewise_entities = []
        for ent in spacy_doc.ents:
            if ent.label_ == "PERSON":
                pagewise_entities.append(
                    (ent.text, ent.start, ent.end, ent.start_char, ent.end_char)
                )
        if not pagewise_entities:
            chart_info_pagewise[doc_id] = None
        else:
            chart_info_pagewise[doc_id] = pagewise_entities

    response = {"entities": chart_info_pagewise, "time_taken": str(time.time() - start_time)}
    return response

```

### DockerFile Used

```
FROM nvidia/cuda:10.0-devel-ubuntu18.04

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

# Install base packages.
RUN apt-get update --fix-missing && apt-get install -y \
    bzip2 \
    ca-certificates \
    python3-dev \
    python3-pip \
    libc-dev \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    libevent-dev \
    libgl1-mesa-glx \
    build-essential && \
    rm -rf /var/lib/apt/lists/*

ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64

# Tell nvidia-docker the driver spec that we need as well as to
# use all available devices, which are mounted at /usr/local/nvidia.
# The LABEL supports an older version of nvidia-docker, the env
# variables a newer one.
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
LABEL com.nvidia.volumes.needed="nvidia_driver"

#Install spacy and its dependencies
RUN pip3 install --upgrade pip && \
    pip3 install -U setuptools wheel && \
    pip3 install spacy==3.0.5 spacy-transformers==1.0.4 cupy-cuda100 sentry-sdk==1.3.0 && \
    python3 -m spacy download en_core_web_trf && \
    pip3 install fastapi uvicorn pydantic

WORKDIR /app
COPY ./app /app

EXPOSE 5000

ENTRYPOINT ["uvicorn"]
CMD ["api:app", "--host", "0.0.0.0", "--timeout-keep-alive", "300", "--workers", "4" ,"--port", "5000"]

```

### Getting OOM Error 
`CUDA out of memory. Tried to allocate 20.00 
MiB (GPU 0; 14.76 GiB total capacity; 486.44 MiB already allocated; 6.75 MiB free; 530.00 MiB reserved in total by PyTorch)`

`Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length.`

Have seen above two error while doing testing API on the production server

@adrianeboyd @svlandeg Can you guys can help me out? I may be missing something

**Comment by VMAtm** [comment]
> @adrianeboyd Do we need to add multiprocessing even after adding `torch.set_num_threads(1)` before loading the spacy transformer model in a GPU-based server?

You probably want to open a new issue, as this one is closed

**Comment by kaushikepi** [comment]
@VMAtm How did you solve the OOM issue?

**Comment by VMAtm** [comment]
> @VMAtm How did you solve the OOM issue?

As mentioned above, by limiting the threads manually instead of automatically defining their number
