### ISSUE TITLE
What do feature annotations mean in Spacy?

### ISSUE THREAD

**Issue by dminh** [explosion/spaCy#857]
I am trying to customize EntityRecognition model of Spacy by modifying the NER feature templates, but I do not understand the meanings of feature annotations that are defined in the file: https://github.com/explosion/spaCy/blob/master/spacy/syntax/_parse_features.pxd.
Please help me to describe each of them, such as S2w, S2W, S2p, S2c, S2c4, S2c6, etc.
I am sorry for breaking the rule of posting issue but I posted the question to stackoverflow for a while and got no answer http://stackoverflow.com/questions/41500392/what-do-feature-annotations-mean-in-spacy

**Comment by honnibal** [comment]
Hey,

No problem about asking here --- I think the information definitely belongs in the docs, so I think an issue is appropriate anyway.

The feature scheme makes a bit more sense if you consider a technicality about the way the model is working: it's a push-down automaton, that maintains a "stack" that holds the current entity, and a "buffer" consisting of the words to be processed.

At any given point, we have a state consisting of the words on the stack (if any), which consistute the current entity being constructed. We also have the current word, and the two subsequent words. Finally, we also have the entities previously built.

This gives us a number of tokens to ask questions about, to make the features. About each of these tokens, we can ask about a number of different properties. Each feature identifier asks about a specific property of a specific token of the context. The tokens are:

* S0: The first word on the stack, i.e. the token most recently added to the current entity.
* S1: The second word on the stack, i.e. the second most recently added
* S2: The third word on the stack, i.e. the third most recently added
* N0: The first word of the buffer, i.e. the current word being tagged.
* N1: the second word of the buffer
* N2: The third word of the buffer
* P1: The word immediately before N0
* P2: The word two before N0
* E0: The first word of the previously constructed entity
* E1: The first word of the second previously constructed entity

About each of these tokens, we can ask:

 * N0w: `token.orth`: The word form
 * N0W: `token.lemma`: The word's lemma
 * N0p: `token.tag`: The word's (full) POS tag
 * N0c: `token.cluster`: The word's (full) Brown cluster
 * N0c4: First four digit prefix of the word's Brown cluster
 * N0c6: First six digit prefix of the word's Brown cluster
 * N0L: The word's dependency label. Not used as a feature in the NER
 * N0_prefix: `token.prefix`: The first three characters of the word
 * N0_suffix: `token.suffix`: The last three characters of the word
 * N0_shape: `token.shape`: The word's shape, ie. is it alphabetic, numeric, etc
 * N0_ne_iob: `token.ent_iob`: The Inside/Outside/Begin code of the word's NER tag
 * N0_ne_type: `token.ent_type`: The word's NER type.

Hope that helps,
Matt

**Comment by ines** [comment]
Great – also added this overview to the API docs: https://spacy.io/docs/api/features

**Comment by dminh** [comment]
Hi honnibal,
This is exactly what I am looking for. 
Thank you so much! 
Minh Dinh
