### ISSUE TITLE
Model download HTTP error 404 for spacy 3.1.0

### ISSUE THREAD

**Issue by lingvisa** [explosion/spaCy#8574]
I installed spacy 3.1.0 from source with success, but when I download the model, it gives this error:

 ```
python -m spacy download en_core_web_sm
Collecting en-core-web-sm==3.1.0
  ERROR: HTTP error 404 while getting https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.1.0/en_core_web_sm-3.1.0-py3-none-any.whl#egg=en_core_web_sm==3.1.0
ERROR: Could not install requirement en-core-web-sm==3.1.0 from https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.1.0/en_core_web_sm-3.1.0-py3-none-any.whl#egg=en_core_web_sm==3.1.0 because of HTTP error 404 Client Error: Not Found for url: https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.1.0/en_core_web_sm-3.1.0-py3-none-any.whl for URL https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.1.0/en_core_web_sm-3.1.0-py3-none-any.whl#egg=en_core_web_sm==3.1.0
```

What might be the issue? This is true for both mac and ubuntu.

**Comment by polm** [comment]
We haven't actually released 3.1 yet so those models aren't available. Please wait a bit longer.

Also note that we haven't made the 3.1 tag yet so the release is not quite finalized.

**Comment by svlandeg** [comment]
Also -just FYI- the 3.0 models should in fact still work for the upcoming 3.1 release, though you'll get a warning.
But in the meantime just so you can keep working, you should be able to install the model from the URL you can find at https://github.com/explosion/spacy-models/releases, e.g.
```
pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0-py3-none-any.whl --no-dependencies
```

Keep an eye out though - the 3.1 release will be out soon, including newly trained models :-)

**Comment by lingvisa** [comment]
I downgraded to 3.06 and downloaded the models file to install, which is fine.

Is 3.1 going to be a major/big release compared to 3.06? And how soon would it be going out?

**Comment by polm** [comment]
spaCy uses [semantic versioning](https://semver.org/), so yes, 3.1 will be larger than point releases. We don't have specific date, though the release will probably be quite soon.
