### ISSUE TITLE
How to control segmenter while loading Chinese full models in Spacy 3.06?

### ISSUE THREAD

**Issue by lingvisa** [explosion/spaCy#8576]
`nlp = spacy.load('zh_core_web_trf')`

If I want to choose a particular segmenter, how to do that? I can't do the following:
`nlp = spacy.load('zh_core_web_trf', config={'segmenter': 'jieba'})`

 Or I create the tokenizer first:

```
cfg = {"segmenter": "pkuseg"}
nlp = Chinese.from_config({"nlp": {"tokenizer": cfg}})
nlp.tokenizer.initialize(pkuseg_model="mixed")
```
Then how to load other models, pos, ne, parser etc through this nlp object?

**Comment by adrianeboyd** [comment]
This is better suited to the discussion board, let me move it over...
