### ISSUE TITLE
Extra space within doc.text method

### ISSUE THREAD

**Issue by huajunzeng** [explosion/spaCy#859]
An unexpected space was added within the doc.text.
code as below:
```
>>> nlp=spacy.load('en', add_vectors=False)
>>> nlp(u"aaabbb@ccc.com\nThank you!").text
u'aaabbb@ccc.com \nThank you!'
```

Note that there is a space before \n which was not there in the input. This caused incorrect position of tokens when I tried to map to original text

## Your Environment

* Operating System: Ubuntu
* Python Version Used: Python 2.7.12 :: Anaconda 4.1.1 (64-bit)
* spaCy Version Used: 1.6.0
* Environment Information:

**Comment by honnibal** [comment]
Thanks -- bad bug.

I could've sworn I'd seen and fixed this before, but now I can't even find an issue for it. Odd.

**Comment by oroszgy** [comment]
Recently `\n` keeps being a token which is a bit strange for me.
See this:
```
>>>repr(nlp(u"Hi\nThank you!")[1])
'\n'
```

**Comment by honnibal** [comment]
@oroszgy Non-trivial whitespace has always been a token in spaCy -- I figured you'd have noticed this before. Is something new here that I'm not understanding?

**Comment by oroszgy** [comment]
Hm, interesting, somehow I did not noticed this behaviour before. I guess my previous comment is useless in this case.
