### ISSUE TITLE
Issues with NER with BERT_BASE in Spacy

### ISSUE THREAD

**Issue by JessitaMS** [explosion/spaCy#8602]
Hello:

I'm a new one in this of NLP. 

I'm just trying to use a pretrained model to extract the PERSON that I have in my text. First at all, I used the pretrained model **es_core_news_md**. This mark as PERSON the following words, if you can see mark as well Bucéfalo de Alejandro, Babieca, but borró is a verb, so I don't why this is marked.

![image](https://user-images.githubusercontent.com/26332548/124460769-0e4eb380-dd90-11eb-9167-2b261b975db1.png)

Then I'm trying to use **"bert-base-multilingual-cased"** with Transformer:

![image](https://user-images.githubusercontent.com/26332548/124461022-6e455a00-dd90-11eb-9319-7c2cb0320322.png)

But they don't have in the pipeline the name "NER", so I tried to add the pipe created NER, but also it don't seems work o.0

![image](https://user-images.githubusercontent.com/26332548/124461254-aea4d800-dd90-11eb-9a20-f9ffe26bbc6e.png)

Anyone can help me with this issues, cause I can't use _displacy_ because don't recognized the NER component..

Thanks!

**Comment by polm** [comment]
Since this is not a bug report I'm going to move it to Discussions.
