### ISSUE TITLE
Normalization of contractions: inconsistency between lemmatizer and norm

### ISSUE THREAD

**Issue by phipsgabler** [explosion/spaCy#8615]
I am a bit concerned about the following appearent inconsistency between lemmata and normal forms:

```
>>> [(t.lemma_, t.norm_, t.tag_) for t in nlp("he's flying")]
[('he', 'he', 'PRP'), ('be', "'s", 'VBZ'), ('fly', 'flying', 'VBG')]
>>> [(t.lemma_, t.norm_, t.tag_) for t in nlp("I'll be flying")]
[('I', 'i', 'PRP'), ("'ll", 'will', 'MD'), ('be', 'be', 'VB'), ('fly', 'flying', 'VBG')]
```

Why is `'ll` lemmatized as `'ll` but normalized to its full form `will`, whereas `'s` behaves the other way round?  I'd surely consider `will` the lemma of `'ll`.  Is this a bug or done intentionally?

What I want to get, eventually, is the sequence of "expanded lemmata":

```
["he", "be", "fly"]
["I", "will", "be", "fly"]
```

which I had hoped is possible without manual intervetion by a custom pass or writing exceptions.

- **spaCy version:** 3.0.6
- **Platform:** Linux-5.8.0-59-generic-x86_64-with-glibc2.10
- **Python version:** 3.8.10
- **Pipelines:** en_core_web_sm (3.0.0)

(I have asked this on [StackOverflow](https://stackoverflow.com/q/68196089/1346276) first, but got not answer.)

**Comment by adrianeboyd** [comment]
Let me move this to a discussion...
