### ISSUE TITLE
Segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by eromoe** [explosion/spaCy#863]
Hi,

Sorry, I only get `Segmentation fault (core dumped)`, no detail error message is really hurt, by http://stackoverflow.com/questions/13654449/error-segmentation-fault-core-dumped, I think this error may come from the cython code? 

---------------

I am tring to integrate Chinese tokenizer and tagger into spaCy  https://github.com/explosion/spaCy/issues/854#issuecomment-282453136 . 

- My code  : https://github.com/eromoe/spaCy/tree/dev/spacy/zh 

- Model data( from 1000 articles ),  trained by this [example:](https://github.com/explosion/spaCy/blob/master/examples/training/train_tagger.py) : https://drive.google.com/file/d/0B0s8xDKW3sIGM1VlVVRCcnNmNVE/view?usp=sharing

### Test code

```
import spacy
import os

model_path = os.path.abspath(os.path.join('some_path', 'model_cn'))
spacy.util.set_data_path(model_path)
spacy.load('zh')
```

### Result
```
Segmentation fault (core dumped)
```

------------------

Then I found `Vocab.load` get this error ,  

```
from spacy.vocab import Vocab
vocab = Vocab.load(model_path)
```

PS: does training only tagger and vocab enough here? I only want to make spacy annotate works with Chinese ...

**Comment by honnibal** [comment]
Hey,

If you trigger a C-level error (a segfault etc) from Python code, that's *always* a bug, and I appreciate you reporting it here, even with little detail. It's usually very difficult for everyone but me to debug these.

I think the problem in this case comes from not saving and loading the strings. I'm having trouble finding the script you're executing to train and save your vocab. Could you paste that?

Thanks,
Matt

**Comment by eromoe** [comment]
I'am late, sorry :P. 
Here is my code: https://github.com/eromoe/spaCy/blob/dev/examples/training/train_tagger_cn.py
I would upload some sample text to google drive later.

**Comment by honnibal** [comment]
Yes if the order is being iterated differently, that will be a problem.

Also: If you're running on Python 2, you might want to check your json read/write. Is it handling the codec correctly, or is it getting corrupted?

Finally, `orths_and_spaces` is deprecated. You should use the `words=` and `spaces=` keyword arguments.

**Comment by eromoe** [comment]
Actually that training finish without any problem. The `try .. except ...` block in code is just because some texts can not tokenize properly(lost pos tag on some word) , so skip.

**Comment by honnibal** [comment]
I think this is resolved, right? Please reopen if I'm reading wrong.
