### ISSUE TITLE
Spacy do not extract all entities.

### ISSUE THREAD

**Issue by vladimircape** [explosion/spaCy#867]
Can you explain me why spacy not extract entity from such simple sentance.

from spacy.en import English
parser = English()
t = parser('Facebook is the best.')
t.ents
()

**Comment by h1man5hu** [comment]
The entities are recognised by the tagger, not the parser.

**Comment by andychisholm** [comment]
I think this is more likely a limitation of the NER model. If the model doesn't lean too heavily on gazetteers, this kind of sentence is actually deceptively tricky to classify. 

E.g. token capitalization is a less significant feature at the start of the sentence. If we rearrange the sentence a little, you can see it correctly catches the Facebook entity:
```python
>>> nlp(u'Facebook is the best.').ents
()
>>> nlp(u'Some say Facebook is the best.').ents
(Facebook,)
```

**Comment by ines** [comment]
The new version 1.8.0 comes with bug fixes to the NER training procedure and a new `save_to_directory()` method. We've also updated the docs with more information on training and NER training in particular:
* Workflow: [Training the Named Entity Recognizer](https://spacy.io/docs/usage/training-ner)
* Workflow: [Saving and loading models](https://spacy.io/docs/usage/saving-loading)
* Example: [Training an additional entity type](https://github.com/explosion/spaCy/blob/master/examples/training/train_new_entity_type.py)
* [Command line interface](https://spacy.io/docs/usage/cli#model) for initialising, training and packaging models

I hope this helps!
