### ISSUE TITLE
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

### ISSUE THREAD

**Issue by simonschoe** [explosion/spaCy#8697]
## How to reproduce the behaviour

I followed the official [spacy-transformers documentation](https://github.com/explosion/spacy-transformers#-installation) and run in a clean venv:
```sh
pip install spacy[transformers,cuda112]
spacy download en_core_web_trf
```
The GPU is properly detected via `!nvidia-smi`, however, `spacy` is returning an error when running:
```python
from thinc.api import set_gpu_allocator, require_gpu
set_gpu_allocator('pytorch')
require_gpu(0)
```
```python
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_8948/4226459810.py in <module>
      2 
      3 set_gpu_allocator('pytorch')
----> 4 require_gpu(0)

c:\Users\...\Desktop\L09_Desktop\stratTransf\.venv\lib\site-packages\thinc\util.py in require_gpu(gpu_id)
    188 
    189     set_current_ops(CupyOps())
--> 190     set_active_gpu(gpu_id)
    191     return True
    192 

c:\Users\...\Desktop\L09_Desktop\stratTransf\.venv\lib\site-packages\thinc\util.py in set_active_gpu(gpu_id)
    149         import torch
    150 
--> 151         torch.cuda.set_device(gpu_id)
    152         torch.set_default_tensor_type("torch.cuda.FloatTensor")
    153     except ImportError:

c:\Users\...\Desktop\L09_Desktop\stratTransf\.venv\lib\site-packages\torch\cuda\__init__.py in set_device(device)
    262     device = _get_device_index(device)
    263     if device >= 0:
--> 264         torch._C._cuda_setDevice(device)
    265 
    266 

AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'
```
Any idea what might cause the problem? I would be super grateful for any help!

## Info about spaCy

- **spaCy version:** 3.1.0
- **Platform:** Windows-10-10.0.19041-SP0
- **Python version:** 3.8.5
- **Pipelines:** en_core_web_trf (3.1.0)

## Edit
As per #7123, I added another line when setting up the environment and changed to `cuda111` (since `pytroch` stable does not yet support `cu112`):
```sh
pip install torch==1.9.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html
pip install spacy[transformers, cuda111]
spacy download en_core_web_trf
```
Afterwards, I am not able to load the transformer model any longer, i.e. running `spacy download en_core_web_trf` yields the following error:
```python
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users\...\Desktop\L09_Desktop\stratTransf\.venv\lib\site-packages\torch\lib\cublas64_11.dll" or one of its dependencies.
```
However, 
```python
from thinc.api import set_gpu_allocator, require_gpu
set_gpu_allocator('pytorch')
require_gpu(0)
```
now returns `True`... I am pretty much clueless. 😆

**Comment by polm** [comment]
What version of Cuda do you have? Use the output of `nvcc --version`. It sounds like maybe Pytorch doesn't like 11.2, but you have that installed so the 11.1 version can't find a DLL.

**Comment by simonschoe** [comment]
Hi @polm, you're right, I have indeed CUDA 11.2 installed. However, I was using `transformers` and `pytroch` in another project without any issues. Hence, I expected the higher version of CUDA to not be an issue here with `spacy` since, as I understood it, it refers to `transformers` and `pytorch` under the hood as well.

**Comment by BramVanroy** [comment]
I am not sure whether this is the same issue but it also relates to CUDA. I have 11.4 installed. When I install spacy[cuda112], installation succeeds. But if I then try to train a model with GPU I get the error that the GPU is not available. 

I ended up doing a `spacy[cuda]` install instead. This then compiled the correct version for me that works - but I am not sure how I can see which version of CUDA it is using, then. It confuses me a bit.

**Comment by polm** [comment]
@BramVanroy When you install from source, the compiler looks for the headers on your machine and automatically uses the installed version of the library if it's compatible. Often the source supports versions that don't have binary builds released yet. 

When you install a prebuilt binary, like with `cuda112`, the binary is configured to look up the version of library it was compiled against using dynamic linking. Install just copies over binary files without checking what libraries are installed on your system, but when you execute the program the dynamic linking lookup fails. 

> This then compiled the correct version for me that works - but I am not sure how I can see which version of CUDA it is using, then. It confuses me a bit.

You can use `ldd` on an `.so` file to find what it links against. 

So your issue, which seems to just be a cuda version mismatch, is unrelated.

The original issue is either something weird with the Pytorch install (which happens a lot) or an issue with cupy (which also happens, but is usually easier to fix on Linux).

**Comment by BramVanroy** [comment]
Right, I understand that, but I thought that CUDA minor versions were backwards compatible. So I don't quite understand why spaCy with 11.2 would not work on 11.4. If needed I can make a separate topic, although this is not an urgent matter for me.

(Sorry for topic steal!)

**Comment by simonschoe** [comment]
### Update
I experimented a little bit with the ordering of package installations and now produced a new error:
```python
pip install -U pip setuptools wheel
pip install torch==1.9.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html
pip install spacy[transformers]
spacy download en_core_web_trf
pip install cupy-cuda112
```
```python
import torch
torch.cuda.is_available()
>> True
```
```python
from thinc.api import set_gpu_allocator, require_gpu
set_gpu_allocator('pytorch')
require_gpu(0)
```
```python
ImportError: CuPy is not correctly installed.

If you are using wheel distribution (cupy-cudaXX), make sure that the version of CuPy you installed matches with the version of CUDA on your host.
Also, confirm that only one CuPy package is installed:
$ pip freeze

If you are building CuPy from source, please check your environment, uninstall CuPy and reinstall it with:
$ pip install cupy --no-cache-dir -vvvv

Check the Installation Guide for details:
https://docs.cupy.dev/en/latest/install.html

original error: DLL load failed while importing runtime: Die angegebene Prozedur wurde nicht gefunden.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
c:\Users\...\Desktop\L09_Desktop\stratTransf\.venv\lib\site-packages\cupy\__init__.py in <module>
     15 try:
---> 16     from cupy import _core  # NOQA
     17 except ImportError as e:

c:\Users\...\Desktop\L09_Desktop\stratTransf\.venv\lib\site-packages\cupy\_core\__init__.py in <module>
----> 1 from cupy._core import core  # NOQA
      2 from cupy._core import fusion  # NOQA
      3 from cupy._core import internal  # NOQA

cupy\_core\core.pyx in init cupy._core.core()

c:\Users\...\Desktop\L09_Desktop\stratTransf\.venv\lib\site-packages\cupy\cuda\__init__.py in <module>
      7 from cupy._environment import get_hipcc_path  # NOQA
----> 8 from cupy.cuda import compiler  # NOQA
      9 from cupy.cuda import device  # NOQA

c:\Users\...\Desktop\L09_Desktop\stratTransf\.venv\lib\site-packages\cupy\cuda\compiler.py in <module>
     10 
---> 11 from cupy.cuda import device
     12 from cupy.cuda import function

cupy\cuda\device.pyx in init cupy.cuda.device()

ImportError: DLL load failed while importing runtime: Die angegebene Prozedur wurde nicht gefunden.

The above exception was the direct cause of the following exception:

ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_4100/4124341650.py in <module>
      1 from thinc.api import set_gpu_allocator, require_gpu
      2 
----> 3 set_gpu_allocator('pytorch')
      4 require_gpu(0)

c:\Users\...\Desktop\L09_Desktop\stratTransf\.venv\lib\site-packages\thinc\backends\__init__.py in set_gpu_allocator(allocator)
     28     """
     29     if allocator == "pytorch":
---> 30         use_pytorch_for_gpu_memory()
     31     elif allocator == "tensorflow":
     32         use_tensorflow_for_gpu_memory()

c:\Users\...\Desktop\L09_Desktop\stratTransf\.venv\lib\site-packages\thinc\backends\__init__.py in use_pytorch_for_gpu_memory()
     47     (or vice versa), but do not currently have an implementation for it.
     48     """
---> 49     import cupy.cuda
     50 
     51     assert_pytorch_installed()

c:\Users\...\Desktop\L09_Desktop\stratTransf\.venv\lib\site-packages\cupy\__init__.py in <module>
     35 original error: {}'''.format(_exc_info[1]))  # NOQA
     36 
---> 37     raise ImportError(_msg) from e
     38 
     39 

ImportError: CuPy is not correctly installed.

If you are using wheel distribution (cupy-cudaXX), make sure that the version of CuPy you installed matches with the version of CUDA on your host.
Also, confirm that only one CuPy package is installed:
  $ pip freeze

If you are building CuPy from source, please check your environment, uninstall CuPy and reinstall it with:
  $ pip install cupy --no-cache-dir -vvvv

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

original error: DLL load failed while importing runtime: Die angegebene Prozedur wurde nicht gefunden.
```
I would be super grateful for any help in the matter!

**Comment by simonschoe** [comment]
@polm any new/other ideas on this one? I am hitting a road block here, since I cannot scale my pre-processing workflow to my entire data without the GPU being leveraged... :/

**Comment by BramVanroy** [comment]
Accordinig to the cupy set up you do not have cudnn installed. Make sure [that's installed](https://developer.nvidia.com/rdp/cudnn-archive) and available via your path or CUDA libs.

**Comment by polm** [comment]
Sorry but I 'm not really sure what to tell you, it might just be an issue with using a very new cuda version and library compatibility. Maybe try downgrading cuda to 11.1 and using that for all libraries? 

I wouldn't try to install the base `cupy` package, I think it'll try to build from source or something which is likely to be involved.

**Comment by simonschoe** [comment]
Okay, so I was finally able to fix it, thanks for all your help! Downgrading to CUDA 11.1 eventually did the trick. For all coming after me, this was the order of installations:
```sh
python -m venv .venv
.\.venv\Scripts\activate
python -m pip install -U pip setuptools wheel
python -m pip install torch==1.9.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html
python -m pip install -U spacy[transformers,cuda111]
python -m spacy download en_core_web_trf
```
I believe the `cudnn` error was mainly due to me trying to install `cupy` from source instead of using the `cupy-cuda111` wheel. (Note that the `torch` install step is crucial since `spacy[transformers]` does only load the CPU-only version of `torch` as far as I am concerned)

**Comment by BramVanroy** [comment]
The installation of torch will indeed depend on your environment both in terms of architecture, device and OS. 

It's a bit strange that building cupy from source did NOT work. It's one of those "last resorts" that should always work if the prerequisites are installed correctly. So something in your environment is not set up correctly to build from source. Either way, glad that you solved it. You can close this issue now.

**Comment by polm** [comment]
Glad that fixed your issue, thanks for reporting back! Unfortunately there's a lot around GPU compatibility and torch that is kind of mysterious.

Building from source should generally work, but since it's usually slow and there's more that can go wrong I would typically recommend against doing it unless you have a specific reason for doing so (using unusual architecture features or something).

**Comment by polm** [comment]
@BramVanroy Sorry for not replying to this point sooner, but...

> Right, I understand that, but I thought that CUDA minor versions were backwards compatible. So I don't quite understand why spaCy with 11.2 would not work on 11.4. If needed I can make a separate topic, although this is not an urgent matter for me.

I think in theory they should be backwards compatible but given the amount of issues I have seen with version differences I would not count on it, and would unify versions first thing if any issues are encountered.
