### ISSUE TITLE
Import Error: No module named spacy

### ISSUE THREAD

**Issue by babebe** [explosion/spaCy#870]
installed spacy but import is not working:
i get the following error:
File "/home/vmagent/app/zibbli_backend_v4.py", line 23, in <module>
    import spacy
ImportError: No module named spacy

I run " python -m pip list" and it shows that version  1.6.0 is installed and  I use python 2.7

Please advice

**Comment by vladimircape** [comment]
Check maybe you have different python, 
what you got on
"whereis python"

**Comment by CharleyPeng1** [comment]
You've probably got python3 as default. Try run the script with `python2`

**Comment by babebe** [comment]
I have python 2 ...and i was able to download spacy and run " sudo python
-m spacy.en.download all"
and now when i run token.dep_ it returns an empty unicode string and 0 pos
tag. When i do token.is_stop it returns True, correctly so.

**Comment by vladimircape** [comment]
python on sudo can be other version of python, different from python on you user

**Comment by babebe** [comment]
Okay so i realized that i had not downloaded the data (english module). But now, my script gets interrupted  because it takes along time for it to load the module. What's the best way to fix that? I am running the script on a VM on GAE

**Comment by ines** [comment]
Thanks for updating with the solution and thanks for opening a separate issue for the other problem.  I'm closing this one to keep things organised!

**Comment by satyansh-sagar** [comment]
I am spacy in my system , when i am importing the same from spyder , is is giving an error 'module not found'
