### ISSUE TITLE
False warning messages in pipelines?

### ISSUE THREAD

**Issue by lingvisa** [explosion/spaCy#8711]
MacPro 11, Spacy 3.1.0

```
import spacy

nlp = spacy.load("en_core_web_sm")
doc = nlp("Apple is looking at buying U.K. startup for $1 billion")

for token in doc:
    print(token.text, token.lemma_, token.pos_, token.tag_, token.dep_,
            token.shape_, token.is_alpha, token.is_stop)
```

When I debug to see the nlp.pipe_names, it displays one error message:

`[E926] It looks like you're trying to modify `nlp.pipe_names` directly. This doesn't work because it's an immutable computed property. If you need to modify the pipeline, use the built-in methods like `nlp.add_pipe`, `nlp.remove_pipe`, `nlp.disable_pipe` or `nlp.enable_pipe` instead.`

Also, if I check the variable 'pipe_labels', it displays another error message:
`'[E095] Can\'t write to frozen dictionary. This is likely an internal error. Are you writing to a default function argument?'`

This doesn't really affect the running of the code, just annoying.

**Comment by polm** [comment]
When you say you "check the variable", do you mean you're just doing something like `print(nlp.pipe_names)`? Can you give example code that causes this? 

What are you using as a debugger? That might explain it. 

Just accessing these variables normally doesn't give any output for me.

**Comment by lingvisa** [comment]
I use  Pycharm Debugger to see nlp.pipe_names.

**Comment by polm** [comment]
So if you look [at the code that throws this error](https://github.com/explosion/spaCy/blob/8bd0474730c5c4d2e25e772e371bc16561e3f431/spacy/util.py#L183), you'll see that it's called when you try to call a list method that would modify the list. I don't use PyCharm Debugger, but it must be calling one of those under the hood, though I'm not sure why it would do so. 

Unfortunately I think this is just something weird PyCharm Debugger is doing. If you can figure out what exactly it's doing and there's something minor we can do to make it better, let us know, but I think this is mainly a PyCharm problem.
