### ISSUE TITLE
Sentencizer with custom punctuation marks not breaking sentences

### ISSUE THREAD

**Issue by prathameshk** [explosion/spaCy#8727]
## How to reproduce the behaviour
nlp = spacy.load("en_core_web_sm")
punc=[".", "?", "!"]
config = {"punct_chars": punc}
nlp.add_pipe("sentencizer", config=config, before='parser')
[i for i in nlp('How are you. [test]').sents]

gives [I love you. [, test]]. It is not breaking on the dot 

## Info about spaCy

- **spaCy version:** 3.1.0
- **Platform:** Darwin-20.3.0-x86_64-i386-64bit
- **Python version:** 3.7.9
- **Pipelines:** en_core_web_lg (3.0.0), en_core_web_sm (3.0.0), en_core_web_trf (3.0.0)

**Comment by adrianeboyd** [comment]
To handle cases like `He asked, "How are you?" And then...`, the sentencizer doesn't add the sentence break until the next non-punct token.

The sentencizer is meant to be fast and approximate for texts with sentence-final punctuation. It will get you sentence-ish chunks. If you need higher quality sentence boundaries, the `senter` or `parser` are a better choice.

**Comment by prathameshk** [comment]
ok thanks for clarifying
