### ISSUE TITLE
broken URL in Corpus.md

### ISSUE THREAD

**Issue by DSLituiev** [explosion/spaCy#8732]
in the table  "See **Corpus** for details. bool" -- URL is broken
https://github.com/explosion/spaCy/blob/master/website/docs/api/corpus.md

**Comment by adrianeboyd** [comment]
Hi, I might be misunderstand what you're asking, but the website is generated from these files, so they're not really intended to work when viewing the markdown in github. As far as I can tell the link looks fine on the website itself:

https://spacy.io/api/corpus#config

You can also set up the website locally as described here (caveat: the node/npm install tends to be fiddly):

https://spacy.io/styleguide#setup
