### ISSUE TITLE
convert from conll2003 to ner-json loses tags

### ISSUE THREAD

**Issue by LadyHangaku** [explosion/spaCy#8737]
## How to reproduce the behaviour
command: `spacy convert filename.conll . --converter ner`

File must be a in a CoNLL-2003 format.

## Bug
When converting a file from CoNLL-2003 to an ner json file, a lot of the tags get lost in the process. Here are some snippets of the conll and ner files. In the first example, the tag gets lost, in the second one, with the same tags, the ner file maintained them:

CoNLL-2003:
```
Name _ O I-PER		
Last Name _ O I-PER
```

ner:
```
  "orth":"Name",
  "tag":"_",
  "ner":"O"
},
{
  "orth":"Last Name",
  "tag":"_",
  "ner":"O"
```
------------------------------------------

CoNLL-2003:
```
Another Name _ O I-PER
Another Last Name _ O I-PER
```

ner: 
```
  "orth":"Another Name ",
  "tag":"_",
  "ner":"B-PER"
},
{
  "orth":"Another Last Name",
  "tag":"_",
  "ner":"L-PER"
```

## My Environment
* **spaCy version:** 2.3.7
* **Platform:** Linux-4.15.0-144-generic-x86_64-with-debian-buster-sid
* **Python version:** 3.7.6

**Comment by adrianeboyd** [comment]
Hi, the problem is that this format doesn't support spaces in the tokens. The converter expects to be able to split the columns by whitespace and that the IOB annotation is in the same column in all lines after splitting, typically either always in the 2nd column or always in the 4th column depending on the dataset.

**Comment by adrianeboyd** [comment]
Let me move this to the discussion board. This issue will be locked but you can follow the link the new thread.
