### ISSUE TITLE
Segmentation fault (core dumped) when import spacy 

### ISSUE THREAD

**Issue by Claus1** [explosion/spaCy#8740]
## How to reproduce the behaviour
I installed fresh tensorflow and tensorboard with Open GIM in my common repo.
After that 
```
import spacy
```
causes
```
Segmentation fault (core dumped)
```
I removed all new packages, made force install new/old versions 3.0-3.1. Nothing helps.

## Your Environment
* Operating System:
* Mint/ubuntu 18.04
* Python Version Used:
* 3.6
* spaCy Version Used:
* 3.0, 3.1
* Environment Information:
Main system

**Comment by Claus1** [comment]
I found a problem. I used different for pytorch and torch paths. So when I changed .bashrc to old torch lib the import starts to works. So it is not obvious that spacy uses torch, pip said only about problems with tensorflow and tensorboard.

**Comment by polm** [comment]
Sorry you had trouble, thanks for reporting the fix!
