### ISSUE TITLE
Rule-based Matcher Explorer does not show matches with length pattern

### ISSUE THREAD

**Issue by FabianHertwig** [explosion/spaCy#8756]
## How to reproduce the behaviour
Go to the  [Rule-based Matcher Explorer and set a length based rule (included in the link)](https://explosion.ai/demos/matcher?text=A%20match%20is%20a%20tool%20for%20starting%20a%20fire.%20Typically%2C%20modern%20matches%20are%20made%20of%20small%20wooden%20sticks%20or%20stiff%20paper.%20One%20end%20is%20coated%20with%20a%20material%20that%20can%20be%20ignited%20by%20frictional%20heat%20generated%20by%20striking%20the%20match%20against%20a%20suitable%20surface.%20Wooden%20matches%20are%20packaged%20in%20matchboxes%2C%20and%20paper%20matches%20are%20partially%20cut%20into%20rows%20and%20stapled%20into%20matchbooks.&model=en_core_web_sm&pattern=%5B%7B%22id%22%3A2%2C%22attrs%22%3A%5B%7B%22name%22%3A%22LENGTH%22%2C%22value%22%3A%222%22%7D%5D%7D%5D)

No matches are shown. I would expect that matches for every token of length 2 are shown. 

When recreating the same scenario in code, matches are found:

```python
import spacy
from spacy.matcher import Matcher

text = "A match is a tool for starting a fire. Typically, modern matches are made of small wooden sticks or stiff paper. One end is coated with a material that can be ignited by frictional heat generated by striking the match against a suitable surface. Wooden matches are packaged in matchboxes, and paper matches are partially cut into rows and stapled into matchbooks."
nlp = spacy.load("en_core_web_sm")
matcher = Matcher(nlp.vocab)

matcher.add("LENGTH", [[{'LENGTH': 2}]])

doc = nlp(text)
matches = matcher(doc)

for match_id, start, end in matches:
    print(doc[start:end])

```

```text
is
of
or
is
be
by
by
in
```

## Info about spaCy

- **spaCy version:** 3.1.0
- **Platform:** Darwin-20.5.0-x86_64-i386-64bit
- **Python version:** 3.7.3
- **Pipelines:** en_core_web_sm (3.1.0)

**Comment by polm** [comment]
Thanks for the report, that does seem to not be working.

Note that the backends of the public demos haven't been updated in a while, so they're still running the v2.2 series of spaCy. Even in the older versions that attribute should work though... We'll take a look at it.

**Comment by polm** [comment]
Checking this again it still seems to be an issue - it looks like the LENGTH matches specifically usually, but not always, cause some kind of server-side error.
