### ISSUE TITLE
install Huggingface Transformers to got: AttributeError: 'Version' object has no attribute 'major' 

### ISSUE THREAD

**Issue by guzhang480** [explosion/spaCy#8757]
## How to reproduce the behaviour

Using office step to install Transformers: pip install transformers
No error report within install process. But When I import it:

import transformers

I got error: AttributeError: 'Version' object has no attribute 'major' 

## Your Environment

(base) C:\Users\guzha>python -c "from transformers import pipeline; print(pipeline('sentiment-analysis')('we love you'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\guzha\anaconda3\lib\site-packages\transformers\__init__.py", line 43, in <module>
    from . import dependency_versions_check
  File "C:\Users\guzha\anaconda3\lib\site-packages\transformers\dependency_versions_check.py", line 36, in <module>
    from .file_utils import is_tokenizers_available
  File "C:\Users\guzha\anaconda3\lib\site-packages\transformers\file_utils.py", line 281, in <module>
    _torch_fx_available = (torch_version.major, torch_version.minor) == (
AttributeError: 'Version' object has no attribute 'major'

* Operating System:
* Window 10
* Python Version Used: Python3.7,
* tensorflow version: '2.5.0'
* Pytorch version: '1.9.0+cpu'
* spaCy version: '2.2.4'
* Environment Information:
Transformers 3.1 works fine, I just upgrade it then the new version cannot be imported. Before I upgrade transformers, I upgrade both Tensorflow and Pytorch. 

I tried uninstall Transformers using: pip uninstall transformers, then install again, Got same error.

I will appreciate any help and suggestion.

**Comment by guzhang480** [comment]
I try to install Transformers4.8.2

**Comment by guzhang480** [comment]
I fixed it out by installing from source:
pip install git+https://github.com/huggingface/transformers

Thanks.

**Comment by svlandeg** [comment]
Hi!

I'm not sure whether this is related to `spacy` at all, but either way it sounds like you've found a workaround, so I'll go ahead and close this issuse.
