### ISSUE TITLE
span equality is wrong when creating a span from out of bounds of doc

### ISSUE THREAD

**Issue by cadiv** [explosion/spaCy#8767]
the simple case I encountered:
``` python
doc = nlp("text")
span1 = doc[0:1]
span2 = doc[1:1]
span1 == span2 # True
```

from a quick look in the source I found out that what is actually compared is `start_char` and `end_char`, and indeed:
``` python
span1.start_char, span1.end_char, span1.start, span1.end # (0, 4, 0, 1)
span2.start_char, span2.end_char, span2.start, span2.end # (0, 4, 1, 1)
```

and as far as I can tell that's caused by this line in `Span`s init:
https://github.com/explosion/spaCy/blob/ffaead8fe002f8593febd5cd4ccf8335b1d35deb/spacy/tokens/span.pyx#L113

It's worth mentioning I'm working with spacy 2.3.2, so it's not exactly what I sent, however, AFAICS the init and `richcmp` function haven't changed meaningfully (for this case) between the version.

for completeness:
## Info about spaCy

* **spaCy version:** 2.3.2
* **Platform:** Windows-10-10.0.19041-SP0
* **Python version:** 3.7.4

**Comment by adrianeboyd** [comment]
Thanks for the report! There were several bugs around the start/end chars for empty spans, hopefully fixed in the linked PR.
