### ISSUE TITLE
Custom tokenizer not initialized correctly on debug data

### ISSUE THREAD

**Issue by lluissalord** [explosion/spaCy#8774]
Using a custom function on `initialize.before_init` like the one below. I found that debug data was not working correctly because it was returning some misalignments where it should not.

```python
def get_puntuations_infix_regex(language='es'):
    punctuations = list(string.punctuation)
    punctuations += ['\u200b', '\u200c', '−', '’', '´']
    infixes = spacy.blank(language).Defaults.infixes
    for x in punctuations:
        infixes = infixes + [re.escape(x)]
    infix_regex = spacy.util.compile_infix_regex(infixes)

    return infix_regex

@registry.callbacks("customize_tokenizer")
def make_customize_tokenizer():
    def customize_tokenizer(nlp):
        # Replace infix regex
        infix_regex = get_puntuations_infix_regex('es')
        nlp.tokenizer.infix_finditer = infix_regex.finditer
    return customize_tokenizer
```

On config.cfg:
```
[initialize.before_init]
@callbacks = "customize_tokenizer"
```

Finally, I realized that the issue is on the snippet below where the initialization happens after the generation of the corpus and due to this then I got the misaligments.

https://github.com/explosion/spaCy/blob/d48c01a6f77a90db06e936ae903d1d0ea151ae31/spacy/cli/debug_data.py#L101:#L109

I would propose to change the code as below:

```python
    nlp.initialize(lambda: list(train_corpus(nlp)))
    msg.good("Pipeline can be initialized with data")

    train_dataset = list(train_corpus(nlp))
    dev_dataset = list(dev_corpus(nlp))
    msg.good("Corpus is loadable")
```

**Comment by adrianeboyd** [comment]
Thanks, good catch! Would you like to submit a PR? (You can leave out the `list` in `nlp.initialize`.) If not, we can do it, no problem...

**Comment by lluissalord** [comment]
Currently I do not have the setup for PR and I have limited time available for coding, so I would appreciate if you could do it. Thanks!
