### ISSUE TITLE
Wrong location detection in Spanish

### ISSUE THREAD

**Issue by rjgarciar** [explosion/spaCy#8777]
## How to reproduce the behaviour

With this simple code:
```
import spacy
text="""El auge de la variante Delta -originaria de la India- preocupa cada vez más por su alta transmisibilidad"""
nlp = spacy.load("es_core_news_lg")
doc = nlp(text)
print(*[f'{ent.text}|{ent.label_}' for ent in doc.ents], sep='\n')
```
the output is:

```
Delta|ORG
India-|LOC
```

as you can see, it detects _India-_ instead of _India_ as a location

## Your Environment

* Operating System: Windows 10 Pro
* Python Version Used: 3.7.5
* spaCy Version Used: 3.1.0
* Environment Information: conda 4.7.12

**Comment by polm** [comment]
Thanks for the report, sorry you're having trouble with this.

Note that isolated wrong predictions are not bugs, so we handle them in Discussions. Also see https://github.com/explosion/spaCy/issues/3052. 

I'm going to migrate this to a Discussion, you can follow the link to follow up there.
