### ISSUE TITLE
Custom tagging in a sentence

### ISSUE THREAD

**Issue by IrfanKhanTanoli** [explosion/spaCy#878]
Hi everyone,

I have few questions. Is there any way i can custom tag  a sentence with spacy?
e.g
"I am using spacy. This is my first project"

After sentence tokenize
output
I am using Spacy
This is my first project.

Then
Tagging like this sentences not word

e.g 
"I am using spacy" tag as A1
"This is my first project" tag as A2

Something like this.

Also for dependency A1 follows A2.
e.h
Printing  A1->A2 means A1 follows A2
and A2=>A1

Thanks 

## Your Environment

* Operating System: Windows
* Python Version Used: 2.7
* spaCy Version Used: Anaconda for Spacy
* Environment Information:

**Comment by honnibal** [comment]
Hi,

I'm not 100% sure I've understood your requirements, but it sounds to me like you'll need to do some machine learning on top of spaCy. In the examples directory you should find some scripts for learning, say, sentiment tags.
