### ISSUE TITLE
Option `no_skip: true` is not working

### ISSUE THREAD

**Issue by alex-eurec** [explosion/spaCy#8796]
## How to reproduce the behaviour
Download a spacy project (for example from the tutorials), and try to set one or more steps not to be skipped.

```bash
# create venv
python3 -m venv testing_venv

#Activate Venv
source testing_venv/bin/activate

#Install Spacy v3.1.1
python3 -m pip install -U pip setuptools wheel
python3 -m pip install -U spacy[transformers,lookups]
python3 -m spacy download en_core_web_sm #small web model
python3 -m spacy download en_core_web_md #medium web model
python3 -m spacy download en_core_web_lg #large web model
python3 -m spacy download en_core_web_trf #for accuracy

# Clone one example project
python -m spacy project clone tutorials/textcat_goemotions
cd textcat_goemotions

# Fetch the assets
python -m spacy project assets

#CHANGE ONE OR MORE STEPS TO HAVE THE PROPERTY no_skip: true

# Run workflow once
python -m spacy project run all

# Run workflow all twice, and all should be skipped except for the changes made previously.
# Instead, all is skipped
``` 

![image](https://user-images.githubusercontent.com/81571132/126776582-c0939705-4578-4a3f-8a91-86c056701d9c.png)

## Your Environment

- **spaCy version:** 3.1.1
- **Platform:** Linux-5.4.0-80-generic-x86_64-with-Ubuntu-18.04-bionic (also tryed on Ubuntu Server 20.04)
- **Python version:** 3.6.9
- **Pipelines:** en_core_web_md (3.0.0), en_core_web_sm (3.0.0)

**Comment by polm** [comment]
Thanks for the report, confirmed this is an issue. We'll look at fixing it!
