### ISSUE TITLE
Matcher patterns for names with apostrophes. 

### ISSUE THREAD

**Issue by maraimm** [explosion/spaCy#8799]
Hi, 

I am using the matcher to create patterns for people names.  Some of them names have apostrophe's, and they never get matched. When I checked the patterns, they seem to be surrounded by multiple double quotes 
```
{'ORTH': 'Murphy'}
"{'ORTH': ""O'Neill""}"
"{'ORTH': ""O'Shannon""}"
```
* Operating System: MacOS Catalina 
* Python Version Used: 3.9
* spaCy Version Used:  3.1.0

**Comment by polm** [comment]
This doesn't seem to be a bug, so I'm moving it to Discussions.
