### ISSUE TITLE
Spacy loading English module takes too long

### ISSUE THREAD

**Issue by babebe** [explosion/spaCy#880]
I have installed Spacy and the english module in a virtual environment but loading it takes too long and returns the following:

>>> import spacy
>>> nlp = spacy.load('en')
Killed

what is the work around to this problem:

**Comment by yooper** [comment]
@babebe, how long does it take to load on your system? Mine loaded within 10 seconds. 

```python
time python -c "import spacy; spacy.load('en');"
```
```
real    0m10.864s
user    0m9.550s
sys     0m1.280s
```

**Comment by aborsu** [comment]
How much memory does your virtual environment have?

**Comment by yooper** [comment]
memory info
```
free -m
              total        used        free      shared  buff/cache   available
Mem:           5818        1153        1373         162        3290        4223
Swap:          2360         220        2139
```
cpu info 

```
lscpu

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 94
Model name:            Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
Stepping:              3
CPU MHz:               2592.000
BogoMIPS:              5184.00
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              6144K
```

**Comment by honnibal** [comment]
I've got a small memory model trained for use with the upcoming 1.7 release. It makes about 15% more errors, but is only 50mb on disk, and should also be small in memory.

**Comment by babebe** [comment]
It doesn't finish loading .....here's the output:
Killed
real    0m23.793s
user    0m4.460s
sys     0m3.344s

Memory:
total       used       free     shared    buffers     cached
Mem:           594        247        347          0         15         81
-/+ buffers/cache:        150        443
Swap:          767        145        622

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 45
Model name:            Intel(R) Xeon(R) CPU @ 2.60GHz
Stepping:              7
CPU MHz:               2600.000
BogoMIPS:              5200.00
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              20480K
NUMA node0 CPU(s):     0

**Comment by ines** [comment]
Just pushed a new release – there are now different models to choose from, including a much smaller English model (~50MB, about 2% less accurate than the larger model).

The small model is now the default model, so in 1.7.0, you can simply do:

```bash
python -m spacy download en # download small model (50MB)
python -m spacy download en_core_web_md # download medium model (1GB)
```

* [Release notes](https://github.com/explosion/spaCy/releases) for 1.7.0
* [Models documentation](https://spacy.io/docs/usage/models)
* [Command line interface documentation](https://spacy.io/docs/usage/cli)
