### ISSUE TITLE
Requirements and safety

### ISSUE THREAD

**Issue by irejwan** [explosion/spaCy#8805]
spaCy v2 does not support new versions of thinc (>=8.0.4) and catalogue (>=2.0.4), although older versions of thinc has known security vulnerabilities (according to [safety](https://pypi.org/project/safety/)).
These versions are supported in spaCy v3, but we cannot upgrade to v3 due to changes in tokenization, and also [errant](https://github.com/chrisjbryant/errant) does not support it.
Can you add support for these new versions in v2 too?

How to reproduce:
> pip install spacy==2.3.7
> pip install safety
> python -m safety check --full-report
>>>
Output:
+==============================================================================+
|                                                                              |
|                               /$$$$$$            /$$                         |
|                              /$$__  $$          | $$                         |
|           /$$$$$$$  /$$$$$$ | $$  \__//$$$$$$  /$$$$$$   /$$   /$$           |
|          /$$_____/ |____  $$| $$$$   /$$__  $$|_  $$_/  | $$  | $$           |
|         |  $$$$$$   /$$$$$$$| $$_/  | $$$$$$$$  | $$    | $$  | $$           |
|          \____  $$ /$$__  $$| $$    | $$_____/  | $$ /$$| $$  | $$           |
|          /$$$$$$$/|  $$$$$$$| $$    |  $$$$$$$  |  $$$$/|  $$$$$$$           |
|         |_______/  \_______/|__/     \_______/   \___/   \____  $$           |
|                                                          /$$  | $$           |
|                                                         |  $$$$$$/           |
|  by pyup.io                                              \______/            |
|                                                                              |
+==============================================================================+
| REPORT                                                                       |
| checked 29 packages, using free DB (updated once a month)                    |
+============================+===========+==========================+==========+
| package                    | installed | affected                 | ID       |
+============================+===========+==========================+==========+
| thinc                      | 7.4.5     | <8.0.4                   | 40660    |
+==============================================================================+
| Thinc 8.0.4 starts to avoid the 'Pydantic' versions with security            |
| vulnerabilities.                                                             |
+==============================================================================+

* Operating System: MacOS
* Python Version Used: 3.7.4
* spaCy Version Used: 2.3.7

**Comment by adrianeboyd** [comment]
Hi, I think this report is just a bit misleading in terms of the affected versions. `thinc<8.0.0` and `spacy<3.0.0` don't require `pydantic`, so they're not affected by this security vulnerability.

(If you want to use v3 with the v2 tokenization, see an example here of how to package a custom tokenizer, so if you wanted to you could use the exact v2 tokenizer as a custom tokenizer: https://github.com/adrianeboyd/custom-cython-tokenizer)

**Comment by irejwan** [comment]
Thanks for the ref to v2 tokenizer, I'll try it out.
Anyway, I don't have `pydantic` in my env. I created a new virtual env with python 3.7.4 and installed only `spacy 2.3.7` and `safety`. This package does not come from `safety`, so as far as I understand - it must come from spacy.
I'd be happy to share more details if needed.

**Comment by adrianeboyd** [comment]
The example repo only shows how to do the packaging, not the exact v2 tokenizer, but I made the demo for a user who wanted to skip the v3 special case handling.

`pydantic` should not be installed with v2.3.7, so double-check your venv there? I suspect that `safety` has an entry in its database for `thinc` which only references the version for the fix, not the lower version for when the vulnerability was introduced.

**Comment by irejwan** [comment]
You're right, I re-checked it and `pydantic` is indeed not installed with spacy. So I guess it is a problem with `safety`.
Thanks
