### ISSUE TITLE
TypeError: [E930] when trying to train textcat

### ISSUE THREAD

**Issue by kevinlu1248** [explosion/spaCy#8811]
## How to reproduce the behaviour

I'm trying to train a textcat based on `en_core_web_sm`, without modifying any of the original weights.
Unfortunately there's not too many guides on how to train a textcat, and most of the existing guides are outdated and are based on spaCy v2 nor do any of them use config.cfg and `spacy train` which is the recommended method by the docs. 

Thus, I'm not sure if this is the right approach, but I'm certainly facing quite a few errors with unclear instructions along the way. Currently I'm using the following config.cfg:

```
[paths]
train = "data/pers_puns.train.spacy"
# train = "data/pers_puns.train.json"
dev = "data/pers_puns.dev.spacy"
vectors = null
init_tok2vec = null

[system]
gpu_allocator = null
seed = 0

[nlp]
lang = "en"
pipeline = ["tok2vec", "tagger", "parser", "ner", "textcat"]
batch_size = 1000
disabled = []
before_creation = null
after_creation = null
after_pipeline_creation = null
tokenizer = {"@tokenizers":"spacy.Tokenizer.v1"}

[nlp.tokenizer]
@tokenizers = "spacy.Tokenizer.v1"

[components]

[components.tok2vec]
source = "en_core_web_sm"

[components.tagger]
source = "en_core_web_sm"

[components.parser]
source = "en_core_web_sm"

[components.ner]
source = "en_core_web_sm"

[components.textcat]
factory = "textcat"

[corpora]

[corpora.dev]
@readers = "spacy.Corpus.v1"
path = ${paths.dev}
max_length = 0
gold_preproc = false
limit = 0
augmenter = null

[corpora.train]
@readers = "spacy.Corpus.v1"
path = ${paths.train}
max_length = 0
gold_preproc = false
limit = 0
augmenter = null

[training]
dev_corpus = "corpora.dev"
train_corpus = "corpora.train"
seed = ${system.seed}
gpu_allocator = ${system.gpu_allocator}
dropout = 0.1
accumulate_gradient = 1
patience = 1600
max_epochs = 0
max_steps = 20000
eval_frequency = 200
frozen_components = ["tok2vec", "tagger", "parser", "ner"]
before_to_disk = null

[training.batcher]
@batchers = "spacy.batch_by_words.v1"
discard_oversize = false
tolerance = 0.2
get_length = null

[training.batcher.size]
@schedules = "compounding.v1"
start = 100
stop = 1000
compound = 1.001
t = 0.0

[training.logger]
@loggers = "spacy.ConsoleLogger.v1"
progress_bar = false

[training.optimizer]
@optimizers = "Adam.v1"
beta1 = 0.9
# [initialize.components.textcat.labels]
beta2 = 0.999
L2_is_weight_decay = true
L2 = 0.01
grad_clip = 1.0
use_averages = false
eps = 0.00000001
learn_rate = 0.001

[training.score_weights]

[pretraining]

[initialize]
vectors = ${paths.vectors}
init_tok2vec = ${paths.init_tok2vec}
vocab_data = null
tokenizer = {}
lookups = null
before_init = null
after_init = null

[initialize.components]

[initialize.components.textcat]
labels = ["pers", "puns"]
```

And running `python -m spacy debug data config.cfg` gives me the error:

`TypeError: [E930] Received invalid get_examples callback in `Tok2Vec.initialize`. Expected function that returns an iterable of Example objects but got: []`

According to the docs having `init_tok2vec = null` should be allowed, since `init_tok2vec` is for "external resources to assist with transfer learning", which I am assuming is optional, but it looks like it should be non-empty? Also, in my dataset, I only tagged the categories of the document, leaving all information related to other components empty, since I'm only training the textcat, is this allowed?

## Your Environment

- **spaCy version:** 3.0.5
- **Platform:** Linux-5.8.0-55-generic-x86_64-with-glibc2.29
- **Python version:** 3.8.10
- **Pipelines:** en_core_web_md (3.0.0), en_core_web_sm (3.0.0)

**Comment by polm** [comment]
I think this is a usage issue rather than a bug, so I'm going to move it to Discussions.
