### ISSUE TITLE
[Feature request] Adding regex patterns to rule based matching

### ISSUE THREAD

**Issue by hate5six** [explosion/spaCy#882]
Given the following sentence:

> Facebook Price Target Cut to $125.00/Share From $145.00

I'm trying to extract "$125.00/Share". I can do this easily with a regex like: '\$[0-9\.]+/[sS]hare

but I was hoping there was a way to do this within the spaCy framework. spaCy treats it as a single token, so I was wondering if there was a way to incorporate a regex pattern within spaCy's rule based patterns? It's  unclear if this is doable from the documentation, so consider this a feature request :)

## Your Environment

* Operating System: Ubuntu 16.04
* Python Version Used: 3.5
* spaCy Version Used: 1.6.0
* Environment Information:

**Comment by honnibal** [comment]
You can specify the tokens in the rule-matcher using any property of the tokens, and you can add flags to introduce new properties. So, you should be able to get the behaviour you want pretty easily.

The pattern you want to express is basically like:

* Currency
* Divider
* share

I would use the lemma attribute for "share", and I would set add a flag `is_share_divider` which would be true for `a`, `per`, `/` etc, and false for other tokens. If the currency amount is being recognised by the NER you could use that, alternatively you could put together the pattern yourself.

Finally, you might find you do want to specify these things as regular expressions. If so, you can use the result in spaCy by creating a `Span` object, with the regular expression being used to specify the start and end characters.

**Comment by kootenpv** [comment]
I'm also very curious to a simple example of the regex, if anyone could get it to work.
```

import spacy
import re

nlp = spacy.load("en")
r = re.compile("[$][0-9.]+/Share")

s = "$125.00/Share"
```

What next?

**Comment by ines** [comment]
Now that there's a clearer roadmap for the `Matcher`, here are some thoughts on this. (For reference, here are the v2.0 alpha docs on [how the improved API is going to work](http://alpha.spacy.io/docs/usage/rule-based-matching).) I'll also merge this with #864 to keep everything matcher-related in one place.

At the moment, the idea is to extend the `Matcher.add()` method to accept both token patterns (lists), as well as regular expressions – or combinations of them. Just like token patterns, regex patterns should be able to match across token boundaries.

Correctly tokenized, `$125.00/Share` would be split into 4 tokens (`$` `125.00` `/` `Share`), or 6 (`$` `125` `.` `00` `/` `Share`), depending on how well the punctuation rules work. You can express this with a regular expression, or a token pattern:

```python
regex_pattern = r'$[0-9.]+/[sS]hare'
token_pattern = [{'NORM': '$'}, {'IS_DIGIT': True}, {'ORTH': '.', 'OP': '?'}, 
                 {'IS_DIGIT': True, 'OP': '?'}, {'ORTH': '/'}, {'LOWER': 'share'}]

matcher.add('SHARE_PRICES', on_match, regex_pattern, token_pattern)
```

The same pattern ID can be assigned several patterns and one `on_match` callback, that's invoked on each match.

```python
def on_match(matcher, doc, i, matches):
    match_id, start, end = matches[i]
    # do something with each individual match
```

Btw, using `{'NORM': '$'}` is a nice spaCy v2.0+ trick to match all currency symbols. spaCy now normalises currency symbols and different spellings via the `NORM` attribute. This is mostly relevant for training to make sure similar tokens receive similar representations, regardless of how common they were in the training data ([see here](https://alpha.spacy.io/docs/usage/adding-languages#norm-exceptions) for more info).

**Comment by PaddyT** [comment]
@ines Is this `regex_pattern` argument implemented in 2.0 yet, or still in the planning stage? I tried out your example above without success using 2.0.5.

**Comment by yarongon** [comment]
@ines, any update on the `regex_pattern` argument?

**Comment by yarongon** [comment]
I have found a workaround for this issue. Please see my comment [here](https://github.com/explosion/spaCy/issues/1567#issuecomment-356589346l).
