### ISSUE TITLE
Spacy project pull does not pull outputs when dependencies are missing

### ISSUE THREAD

**Issue by nsorros** [explosion/spaCy#8822]
## How to reproduce the behaviour
This might as well be a feature but as the behaviour is a bit unexpected I am opening this as a bug. We are using spacy projects
to track the data and our workflows. I noticed that running `spacy project pull` does not fetch all the outputs created from another
member working on the project and it comes down to some of the dependencies missing due to this check https://github.com/explosion/spaCy/blob/8547514aa4d17bd5f457d2b58d6c3efc3748520d/spacy/cli/project/pull.py#L43

The dependencies missing are data produced from the previous steps which creates a chicken and egg problem. If we want to fetch the outputs we need to run the workflow. If we run the workflow we do not need to fetch the outputs.

Is the intention to only depend on code or assets?

## Your Environment
============================== Info about spaCy ==============================

spaCy version    3.0.6                         
Location         /home/nsorros/code/overton/build/virtualenv/lib/python3.8/site-packages/spacy
Platform         Linux-5.8.0-53-generic-x86_64-with-glibc2.29
Python version   3.8.5                         
Pipelines        en_core_web_md (3.0.0)

**Comment by honnibal** [comment]
> Is the intention to only depend on code or assets?

No, this does seem like a bug. Thanks for the report!

**Comment by nsorros** [comment]
> > Is the intention to only depend on code or assets?
> 
> No, this does seem like it could be a bug. There could also be a problem with your project file.
> 
> The intention behind the while loop is that it should find at least one command where all of the prerequisities are present and matching, and then it will pull that command's outputs. This should give other commands the opportunity to have their dependencies met, in the next iteration of the loop.
> 
> Have a look whether there's some reason why the dependencies in your project are unsatisfiable maybe?

Thanks for the pointer @honnibal. I tracked it down to a dependency which was the folder the data was meant to be downloaded. As such the hash calculated when the data were there was different from when the data were not. The intention of the dependency was to ensure the folder is present before downloading the data. Removing this dependency unblocked the syncing of all the outputs which were dependent on the data.

I was wondering whether it would be worth adding some `logger.debug` in some of the project `push` / `pull` and `remote_storage` code for easier debugging. I already did add some to resolve this so I am happy to open a PR if this is something you want to embed in the library.

**Comment by ines** [comment]
> I was wondering whether it would be worth adding some logger.debug in some of the project push / pull and remote_storage code for easier debugging. I already did add some to resolve this so I am happy to open a PR if this is something you want to embed in the library.

Yes, this is a great idea and we'd definitely appreciate a PR 🙏

**Comment by polm** [comment]
I marked this as resolved since it looks like this wasn't a bug but just a misunderstanding, and the linked PR helps prevent those misunderstandings. But if I misunderstood or there's more work to be done on this let us know.
