### ISSUE TITLE
saving the spacy custom model directly in AWS S3 bucket

### ISSUE THREAD

**Issue by uday-felix** [explosion/spaCy#8827]
Is there a way to save the custom spacy model directly into AWS S3 ? 
Spacy generally has only two ways to save a model, 
1- nlp.to_disk()
2 - nlp.to_bytes()

But how do we save it directly to s3 without interfering with local drive.

**Comment by polm** [comment]
Don't open an issue and a discussion. 

Since this is not a bug we'll use the Discussion. https://github.com/explosion/spaCy/discussions/8826
