### ISSUE TITLE
Is it possible to use gensim/google news word embeddings?

### ISSUE THREAD

**Issue by kootenpv** [explosion/spaCy#884]
Feature question/request: word2vec / googlenews word embeddings

I'd normally use it like this:

```python
from gensim.models import Word2Vec
embeddings = Word2Vec.load_word2vec_format("GoogleNews-vectors-negative300.bin.gz", binary=True)
```

**Comment by kootenpv** [comment]
http://stackoverflow.com/questions/42094180/spacy-how-to-load-google-news-word2vec-vectors

**Comment by ines** [comment]
Thanks for updating with a solution! 👍
