### ISSUE TITLE
Not good to remove white spaces in Chinese tokenization

### ISSUE THREAD

**Issue by lingvisa** [explosion/spaCy#8879]
`(words, spaces) = util.get_words_and_spaces(words, text)`

White spaces are used informally by authors as a kind of delimiter in social media. Spacy users can choose to normalize text in their own code. A typical normalization may be reducing multiple sequential white spaces into one space, or removing all of them. Another typical usage of white space in Chinese social media is to function as  the delimiter of @ handle with text content:

`@美丽中国 奥运会只剩下5天了。`

This typical white space is very helpful for recognizing the AT token boundary.

**Comment by polm** [comment]
Those are good points and I agree that the tokenizer shouldn't arbitrarily remove spaces.

But what's the problem here? This code doesn't remove spaces for me:

```
import spacy
from spacy.util import get_words_and_spaces

nlp = spacy.blank("zh")

doc = nlp("@美丽中国 奥运会只剩下5天了。")

print(doc)

words = [tok.text for tok in doc]

words, spaces = get_words_and_spaces(words, doc.text)
print(words)
print(spaces)
```

It seems like everything is already working the way you suggest?

**Comment by polm** [comment]
Also, please do not write `@token`, you send a notification to that user, who is unrelated to this.

**Comment by lingvisa** [comment]
Let me test again. In my version, the space is gone after the "get_words_and_spaces" function.

**Comment by polm** [comment]
OK, please also paste your spaCy version / `spacy info` output. I'm using 3.1.1.

**Comment by lingvisa** [comment]
I am using 3.10. This line in get_words_and_spaces:

`norm_words = [word for word in words if not word.isspace()]`

```
for word in norm_words:
 ...
```

**Comment by polm** [comment]
That line is still in master unchanged. 

I think maybe there is some confusion about how spaces are handled in spaCy. For half-width, normal ASCII spaces, if there is one space it is not a token (and will not be in the words in `get_words_and_spaces`), instead it's saved as a boolean attribute (and will be `True` in the spaces output of the util function). So if a "word" has a normal space after it then `tok.whitespace_` will be `True`. 

Spaces besides the normal space, such as the full width space U+3000 (middle in `◯　◯`), will be "words" still. 

If you need to pay attention to normal spaces you just need to check the `whitespace_` attribute.

**Comment by polm** [comment]
Going to mark this as resolved, but let me know if there is an issue with the current approach.
