### ISSUE TITLE
Downloading Language Models Fails with Undefined Symbol

### ISSUE THREAD

**Issue by dbreunig** [explosion/spaCy#888]
With a fresh install of spacey 1.6.0, python 2.7 64, running an ubuntu 16.04, usage of spacy throws this error:

`ImportError: /home/dbreunig/anaconda2/lib/python2.7/site-packages/spacy/tokenizer.so: undefined symbol: _ZTINSt8ios_base7failureB5cxx11E`

Thoughts on this? Reinstalled dependencies and same issue.

**Comment by honnibal** [comment]
Hi,

Generally that would mean the library hasn't compiled correctly. Often this occurs when you're using a different Python to compile and run the library.

**Comment by jmugan** [comment]
I have the exact same issue. Fresh install on Ubuntu with Anaconda and Python 3.6.

**Comment by jmugan** [comment]
I saw here on the sense2vec issues page https://github.com/explosion/sense2vec/issues/19 to do `conda install libgcc` and it worked for me.

**Comment by moizhb** [comment]
Same issue, installed libgcc but still getting the same error. Fresh install on Linux Mint Anaconda and Python 3.6

**Comment by jcharit1** [comment]
@jmugan thank you jmugan, I got the same error and install libgcc fixed it. I'm using Ubuntu 16.04 + Python 3.6

**Comment by ines** [comment]
Thanks everyone for updating with your solutions! We're currently waiting to get spaCy v2.0 built for conda (taking a bit longer because of Travis errors and the OSX backlogs 😓).
