### ISSUE TITLE
When HuggaFace transformers model file has tokenizer_config.json and tokenizer.json，how config the config.cfg file?

### ISSUE THREAD

**Issue by baiziyuandyufei** [explosion/spaCy#8906]
## How to reproduce the behaviour

I use the model [https://huggingface.co/hfl/chinese-roberta-wwm-ext/tree/main](https://huggingface.co/hfl/chinese-roberta-wwm-ext/tree/main)，

the training config like below

<pre>
[components.transformer.model]
@architectures = "spacy-transformers.TransformerModel.v1"
name = "./chinese-roberta-wwm-ext"

[components.transformer.model.tokenizer_config]
use_fast = true
</pre>

but the model files contain the file 

- tokenizer_config.json
- tokenizer.json
- added_tokens.json

these files seems to not be used by the SpaCy. 

## Info about spaCy

- **spaCy version:** 3.1.1
- **Platform:** Linux-5.10.25-linuxkit-x86_64-with-Ubuntu-18.04-bionic
- **Python version:** 3.6.9
- **Pipelines:** zh_core_web_sm (3.1.0), xx_ent_wiki_sm (3.1.0)

**Comment by polm** [comment]
Since this seems to be a question and not a bug, I'm going to move it to a Discussion.
