### ISSUE TITLE
spacy-transformer models fail pickling

### ISSUE THREAD

**Issue by daniel-bub** [explosion/spaCy#8908]
Hi,
we are using spacy as part of a Microsoft Presidio pipeline Until recently everything works fine but lately the pickling of spacy-tranformer models fail to pickle. The standard spacy model continue to work fine.
We are executing this within a databricks cluster on Azure cloud.

### Expected behavior:
```
import spacy
import spacy_transformers
import pickle

spacy.cli.download("en_core_web_trf")
nlp = spacy.load("en_core_web_trf", disable=["parser"])

pickle.dumps(nlp)
```
stdout:
```
b'\x80\x04\x95\x07\x00\x01\x00\x00\x00\x00\x00\x8c\rspacy.lang.en [...]
```
### Actual behavior:
```
import spacy
import spacy_transformers
import pickle

spacy.cli.download("en_core_web_trf")
nlp = spacy.load("en_core_web_trf", disable=["parser"])

pickle.dumps(nlp)
```
stderr:
```
AttributeError: Can't pickle local object 'configure_strided_spans.<locals>.get_strided_spans'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<command-2827207167193070> in <module>
     3 import pickle
      4 nlp = spacy.load("en_core_web_trf", disable=["parser"])
----> 5 pickle.dumps(nlp)

AttributeError: Can't pickle local object 'configure_strided_spans.<locals>.get_strided_spans'
```

## Your Environment
- **spaCy version:** 3.0.6
- **Platform:** Linux-5.4.0-1051-azure-x86_64-with-glibc2.2.5
- **Python version:** 3.8.8

**Comment by adrianeboyd** [comment]
Hi, this should be fixed by https://github.com/explosion/spacy-transformers/pull/282, which hasn't made it into a release yet. We can consider getting v1.0.4 out soon with this bug fix.

**Comment by daniel-bub** [comment]
Great news. Thanks! My first search did not result the linked item. Good to know.
We will wait for the next release then.
