### ISSUE TITLE
Missing git tag for PyPI's 1.7.1 release 

### ISSUE THREAD

**Issue by rolando** [explosion/spaCy#893]
PyPI's project page shows latest release as v1.7.1 at this time: https://pypi.org/project/spacy/

I've compared the source distribution files and it seems the v1.7.1 was uploaded from the commit: 8de5108af60a4b4fc45db3892ea4386ba51a28a4 (latest at this time)

It will be great to have a tag for this release.

**Comment by ines** [comment]
Sorry about this – pushed the release to PyPi last night in a hurry to get the fix up for #892. Will create the tag and release now!
