### ISSUE TITLE
SpaCy installation error on windows

### ISSUE THREAD

**Issue by NandeepNandhu** [explosion/spaCy#896]
i am using py 3.6 32 bit. i have microsoft visual studio 14.0 but while installing using pip it shows error: miscrosoft visual studio 14.0 required.

![untitled](https://cloud.githubusercontent.com/assets/20970473/24114247/8c8b6a26-0dc5-11e7-87ca-c404c5828eea.jpg)

**Comment by honnibal** [comment]
We don't have binary wheels up yet, so yes, you'll need a compiler toolchain installed to install spaCy.

**Comment by NandeepNandhu** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20970473/24114397/0f4847f4-0dc6-11e7-8940-fade6db828b0.png)
i have microsoft visual studio 14.0

**Comment by NandeepNandhu** [comment]
@honnibal what i have to do ??

**Comment by honnibal** [comment]
Sorry, misread your message before.

Can you install other libraries that require compilation? My hunch is that this isn't specifically a spaCy error, and I don't have a Windows machine handy to debug this. Perhaps someone else could share their experience here?

**Comment by NandeepNandhu** [comment]
@honnibal nope , i cannot install any other libraries... guys share your ideas ...!

**Comment by yooper** [comment]
I am using Windows 10.  I used pip to install spacy. On the dependencies that did not work, such as numpy and scipy, I downloaded the wheel files from here, http://www.lfd.uci.edu/~gohlke/pythonlibs/ and installed them using pip.
