### ISSUE TITLE
en_core_web_md 1.2.0 model seems broken

### ISSUE THREAD

**Issue by vikrantsharma7** [explosion/spaCy#897]
I'm not able to comprehend the reason for the difference between the following trees:

spacy 1.6.0
```
Taking my dog for a walk is fun.
is (VBZ) ROOT
l ---   Taking (VBG) csubj
r ------   dog (NN) dobj
l ---------   my (PRP$) poss
r ------   for (IN) prep
r ---------   walk (NN) pobj
l ------------   a (DT) det
r ---   fun (NN) acomp
r ---   . (.) punct
```

spacy 1.7.2 (en_core_web_md):
```
Taking my dog for a walk is fun.
Taking (IN) ROOT
r ---   fun (NNP) pobj
l ------   my (NNP) nmod
l ------   dog (NNP) nmod
r ---------   for (NNP) cc
l ------   a (NNP) compound
l ------   walk (NNP) compound
l ------   is (NNP) compound
r ---   . (.) punct
```

* **Python version:** 2.7.12
* **Platform:** Linux-4.4.0-66-generic-x86_64-with-Ubuntu-16.04-xenial
* **spaCy version:** 1.7.2
* **Installed models:** en_core_web_md
Environment: separate virtualenv

**Comment by honnibal** [comment]
It's hard to give you any sort of satisfying answer here. It's possible there's a bug, but more likely that it's just different statistical models making different mistakes.

You can use the parser.step_through method to investigate if you like.

**Comment by honnibal** [comment]
Oh, just reread.

The tagger model looks very suspicious here. Hmm.

**Comment by vikrantsharma7** [comment]
Yes, possible. Almost every other word is tagged wrong.

**Comment by honnibal** [comment]
I think I uploaded the wrong model.

**Comment by vikrantsharma7** [comment]
Do check and let me know

**Comment by honnibal** [comment]
Uploading 1.2.1 now. Thanks for the report!

**Comment by NiallRooney** [comment]
I am experiencing also an issue with this using a recent install of spacy and the en_core_web_md model (en_core_web_md-1.2.0):

Python: 2.7.12

spacy version: 1.8.2

The output of tagging does not make any sense:

(u'Taking', u'IN', u'ADP', u'ROOT', u'Taking')
(u'my', u'NNP', u'PROPN', u'compound', u'dog')
(u'dog', u'NNP', u'PROPN', u'pobj', u'Taking')
(u'for', u'NNP', u'PROPN', u'prep', u'dog')
(u'a', u'NNP', u'PROPN', u'compound', u'walk')
(u'walk', u'NNP', u'PROPN', u'pobj', u'for')
(u'is', u'NNP', u'PROPN', u'compound', u'fun')
(u'fun', u'NNP', u'PROPN', u'dobj', u'walk')

**Comment by vikrantsharma7** [comment]
Use 1.2.1 instead of 1.2.0
