### ISSUE TITLE
_SP tag is not documented

### ISSUE THREAD

**Issue by danmysak** [explosion/spaCy#8982]
```
spacy.load('en_core_web_trf')('a  b')[1].tag_
```

returns `_SP`, but this tag is not documented in https://spacy.io/models/en as well as lacks an explanation when requested with `spacy.explain('_SP')`.

**Comment by polm** [comment]
Thanks for the report, we'll add that to the docs/explainer!

I guess it's clear from context but that's a special tag for whitespace.
