### ISSUE TITLE
Error in german POS-Tagging

### ISSUE THREAD

**Issue by Ben-Bock** [explosion/spaCy#8997]
Hallo, vielen Dank für die super Arbeit!

Ich habe heute bei folgendem Satz: "**Dort gibt es sehr gutes Essen, nur die Sauberkeit war grottig!**" bemerkt, dass "sehr gutes Essen," und "nur die Sauberkeit" jeweils als ein einziges NOUN getagged werden. Das ist bei beiden deutschen Modellen der Fall. Ist leicht in dem gehosteten displacy nachzuvollziehen. 

Vielen Dank nochmals, 

Ben

**Comment by adrianeboyd** [comment]
Hi, the demo has a feature that merges noun chunks. If you uncheck "Merge Phrases" and run it again you can see the original word-level parse.

**Comment by adrianeboyd** [comment]
Let me move this to the discussion board...
