### ISSUE TITLE
CCONJ part of speech is missing from documentation

### ISSUE THREAD

**Issue by danmysak** [explosion/spaCy#9013]
```
spacy.load('en_core_web_trf')('a or b')[1].pos_
```
returns `CCONJ`. The page https://spacy.io/api/token#attributes, however, links to https://universaldependencies.org/docs/u/pos/, where this tag is missing. Was the document meant to link to https://universaldependencies.org/u/pos/ instead?

**Comment by adrianeboyd** [comment]
The `CONJ` tag was renamed to `CCONJ` from UD v1 to UD v2 and I think it's just the case that that link didn't get updated. Thanks for the note, we'll take a look.

**Comment by danmysak** [comment]
Also, `nlp(' ')[0].pos_` returns `'SPACE'`, which is missing from the documentation as well.

**Comment by polm** [comment]
I think `SPACE` is not officially used in UD, probably because they just don't use examples with any spaces at all in most datasets. Since spaCy has to take in all kinds of weird spaces we needed a tag for it.
