### ISSUE TITLE
Replace dependency on typer, which is no longer supported/updated

### ISSUE THREAD

**Issue by mborsetti** [explosion/spaCy#9014]
Typer is creating dependency conflict hell, and turns out "It’s not clear if this project will be maintained in a sustainable way in the future or not."  If there's a way to use some other package or built-in functionality it would be welcomed.

https://github.com/tiangolo/typer/issues/313:
> A nontrivial patch is required (#280, #278) since this library depends heavily on click 7.x internals.
> 
> The project is maintained solely by @tiangolo.
> 
> * Via Twitter, they have expressed an intent to spend more time on Typer and FastAPI
> * They have been active recently in https://github.com/tiangolo/fastapi/
> * They made a new release of https://github.com/tiangolo/typer-cli/ last month (but without addressing the click 8.x issue)
> * As far as I know, they have not responded to issues or PRs here in many, many months ([[QUESTION] Is the project still maintained? #300](https://github.com/tiangolo/typer/issues/300))
> 
> It’s not clear if this project will be maintained in a sustainable way in the future or not.

**Comment by honnibal** [comment]
Yes we've been following this topic, and I think it'll be important to get a resolution. I think we'll be able to do this easily within Typer itself and so we won't have to drop the dependency.

Incidentally, please pay a little bit of attention to how your issues might come across to maintainers, especially if you're opening multiple issues on repositories that are related in various ways (both Justin and Sebastian, whose repos you've commented on, used to work with us). I understand that dependency hell is frustrating, but I read some of your tone as a little rude --- especially your issue on the Typer tracker.

**Comment by mborsetti** [comment]
Matthew,

Thanks; appreciate it. So sorry if I let my frustration with the fact that installing Spacy immediately caused unwanted downgrades to existing packages, no fault of yours, come through. I traced this to packages pinning obsolete versions, whom in turn pin other obsolete package versions, grinding the ability to use current versions of packages and re-introducing security holes and bugs. I appreciate all the work being done by everyone!

**Comment by svlandeg** [comment]
With the new [release](https://github.com/tiangolo/typer/releases/tag/0.4.0) of Typer 0.4.0, we've updated the pins on the `master` branch. In your local environment, you should be able to upgrade `typer` to this new version and it will hopefully all work fine.

**Comment by mborsetti** [comment]
@svlandeg and @honnibal Thanks for a quick turnaround and really appreciate your meaningful contribution to reducing dependency gridlock!
