### ISSUE TITLE
n_process > 1 throws CUDA error while using en_core_web_trf 

### ISSUE THREAD

**Issue by kaushikepi** [explosion/spaCy#9015]
How can we use multiprocessing in the spacy v3 en_core_web_trf model using GPU?

There is no clear documentation or issue.

Can anyone share some insight or suggest some solution?

@honnibal @ines

**Comment by kaushikepi** [comment]
@svlandeg Can you share some insight on it?

**Comment by svlandeg** [comment]
Hi,

This is a good topic for the discussion forum so I'll move it there. I also want to ask you to refrain from pinging various maintainers, as this makes our mentions unusable. We provide support here on a best-effort basis and will get to your question in due time. Thanks for understanding!
