### ISSUE TITLE
Misleading arguments documented for Span.__init__

### ISSUE THREAD

**Issue by kinghuang** [explosion/spaCy#9021]
The [`Span.__init__`](https://spacy.io/api/span#init) documentation suggests that the arguments are `(doc, start, end, label, kb_id, vector)`. But, it's actually `(doc, start, end, label, vector, vector_norm, kb_id)`. I was trying to set the `kb_id` as the fifth positional argument, but couldn't get it to work as suggested by the docs.

**Doesn't work:**

```python
import spacy
from spacy.tokens import Span

nlp = spacy.blank("en")
doc = nlp("Canada")
ent = Span(doc, 0, 1, "GPE", "geonames:6251999")  # kb_id as 5th argument

print(ent.kb_id_ == "geonames:6251999")
```

```python
False
```

**Does work:**

```python
ent = Span(doc, 0, 1, "GPE", None, None, "geonames:6251999")  # kb_id as 7th argument
ent = Span(doc, 0, 1, "GPE", kb_id="geonames:6251999")  # kb_id as keyword argument
```

## Which page or section is this issue related to?

https://spacy.io/api/span#init

**Comment by svlandeg** [comment]
Hi @kinghuang, you're right that the documentation should be updated here.

We should really have used keyword arguments here for everything except `doc`, `start` and `end`, but that would be a breaking change at this point. As a minimal fix, we'll update the docs. Thanks for the report!
