### ISSUE TITLE
Fail to run "python -m spacy download en". en_core_web_sm is not accessible?

### ISSUE THREAD

**Issue by yang1fan2** [explosion/spaCy#904]
Hi

I am trying to install spaCy model with "python -m spacy download en". But it seems that the model link (https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-1.2.0/en_core_web_sm-1.2.0.tar.gz) is not accessible.

Thanks.

* **Python version:** 2.7.10
* **Platform:** Darwin-15.6.0-x86_64-i386-64bit
* **spaCy version:** 1.7.2
* **Installed models:**

**Comment by honnibal** [comment]
Hmm, works for us? Does it work in your browser if you just click the link?

**Comment by yang1fan2** [comment]
It works now. It seems it's my own internet connection problem.

Thanks
