### ISSUE TITLE
spaCy on mobile

### ISSUE THREAD

**Issue by ohenepee** [explosion/spaCy#908]
This isn't a bug nor a feature request, neither do I need help with my code. It is a technical question sort of.

Can I get spaCy on mobile? (as in can I get spaCy to still work "without" NumPy)

**Comment by ohenepee** [comment]
Okay... found out Numpy works on Kivy's mobile platforms. Closing

**Comment by karst10607** [comment]
I am also curious about this. So Spacy can be running on android/iOS ?
