### ISSUE TITLE
Issues with not correct lemmatisation in German

### ISSUE THREAD

**Issue by lnazarenko** [explosion/spaCy#9085]
Hi!
I have an issue with not the correct lemmatization of some German words.
For example the word "international" in the sentence " internationale Organization" lemmatised  to the word "internationale", not the correct form "international".
Other issues that I found are reported below.
the text_example is the correct form of the words from the German dictionary, which are lemmatized wrong. Most of the cases are related to adjectives lemmatization. My question is if there is a way that I can customize the lemmatization and make the correct form of a lemma (probably redefine or reassign)? 
here is the link to google docs 
## How to reproduce the behaviour

import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'
import spacy
#load German spacy pre-built model
nlp_de = spacy.load('de_core_news_sm')
text = "Greenpeace ist eine internationale Organization"
tokens_text = nlp_de(text)
list_lemma = [token.lemma_ for token in tokens_text]
#### Output:
['Greenpeace', 'sein', 'einen', 'internationale', 'Organization']

text_examples = "abgebrüht beherrschend entscheidend entschlossen erprobt führen gewagt kämpfend Meister"
tokens = nlp_de(text_examples)
for token in tokens:
    print (token.text, token.lemma_, token.pos_)

#### Output:
abgebrüht abbrühen ADV
beherrschend beherrschen ADV
entscheidend entscheiden ADV
entschlossen entschließen ADV
erprobt erproben VERB
führen fahren VERB
gewagt wagen VERB
kämpfend kämpfen ADV
Meister meist NOUN

## Your Environment

* Operating System: Mac OS Big Sur 11.2.2
* Python Version Used: Python 3.8.8
* spaCy Version Used: 3.0.5

**Comment by svlandeg** [comment]
Hi!

A related discussion which you might find interesting is here: https://github.com/explosion/spaCy/discussions/8695

In general, these kind of issues can also be reported in https://github.com/explosion/spaCy/issues/3052/. I'll go ahead and close this issue because otherwise we have too many open discussions on the same thing - but feel free to join the discussion in either of the two threads I linked.
