### ISSUE TITLE
Thresholding for EntityLinker

### ISSUE THREAD

**Issue by Joozty** [explosion/spaCy#9114]
I can see that the EntityLinker code contains [TODO comments](https://github.com/explosion/spaCy/blob/master/spacy/pipeline/entity_linker.py#L333) for threshold functionality. Is there any plan to support it? 

It would be nice to also assign a probability to each entity so users can decide whether they want to consider it as a correct entity or not.  That would be really useful.

For example, when an alias has only one candidate it gets resolved to it but based on the context it  doesn't have to be the correct entity and it should be rather handled as `NIL`

**Comment by Joozty** [comment]
Ideally, it would be nice to support 3 threshold options

1. **totalThreshold** --  total probability - if an entity doesn't meet this threshold is discarded
2. **contextThreshold** --   context probability - if context probability is  less than this value then the entity is discarded 
3. **priorThreshold** --  prior probability - if the prior probability is  less than this value then  entity is discarded 

The reason behind it:

Let's say I have an entity `car` which resolves to candidates with  prior probabilities set to 0.9 [Car (vehicle)](https://en.wikipedia.org/wiki/Car) and 0.1 [Car (surname)](https://en.wikipedia.org/wiki/Car_(surname)) and I have this sentence to annotate:


> in greek mythology, **car** or kar (ancient greek: κάρ) of the carians, according to herodotus, was the brother of lydus and mysus.

car entity should point [here](https://en.wikipedia.org/wiki/Car_of_Caria) (not in the knowledge base) but when I train my NEL pipeline with `inc_prior` & `incl_context` set to `true` it always resolves to `car (vehicle)`. If I had a chance to set `contextThreshold` I could easily discard this entity rather then resolving to wrong candidate.

**Comment by polm** [comment]
This was added in #11016.
