### ISSUE TITLE
Unexpected lemma: "inner" -> "inn"

### ISSUE THREAD

**Issue by davechallis** [explosion/spaCy#912]
I've previously (in other lemmatization software) seen "inner" -> "inner" (but again, not sure what correct lemma is, only that "inn" seems wrong here).

I did notice some tasks for improving lemmatization in Spacy in future though, so can hold off on reporting lemmatization issues if it's not helpful at the moment.

Example case:

    import spacy
    nlp = spacy.load('en')
    for token in nlp("Wearing inners in the innermost inner space in the inn."):
        print(token, token.lemma_)

Output:

    Wearing wear
    inners inner
    in in
    the the
    innermost innermost
    inner inn
    space space
    in in
    the the
    inn inn
    . .

## Info about spaCy

* **spaCy version:** 1.7.2
* **Platform:** Darwin-16.4.0-x86_64-i386-64bit
* **Python version:** 3.6.0
* **Installed models:** en

**Comment by honnibal** [comment]
Thanks, that's definitely wrong.
