### ISSUE TITLE
creating a new Doc with POS values results in KeyError

### ISSUE THREAD

**Issue by omri374** [explosion/spaCy#9144]
I'm trying to create a `Doc` out of a pre-tokenized and pre-labeled sentence:

```python
sentence = [(('David', 'NNP'), 'O'),
 (('Pierce', 'NNP'), 'O'),
 (('52', 'CD'), 'O'),
 (('years', 'NNS'), 'O'),
 (('old', 'JJ'), 'O'),
 (('will', 'MD'), 'O'),
 (('join', 'VB'), 'O'),
 (('the', 'DT'), 'O'),
 (('board', 'NN'), 'O'),
 (('as', 'IN'), 'O'),
 (('a', 'DT'), 'O'),
 (('nonexecutive', 'JJ'), 'O'),
 (('director', 'NN'), 'O'),
 (('Dec.', 'NNP'), 'O'),
 (('12', 'CD'), 'O')]
```

The way I'm creating the `Doc` is the following:
```python
doc = Doc(vocab=nlp.vocab,
          words = [token[0][0] for token in sentence],
          pos = [token[0][1] for token in sentence],
          ents = [token[1] for token in sentence])
```

This seem to work, but whenever I try to extract the POS values out of the `Doc` I get a `KeyError` exception:

```python
[token.pos_ for token in doc]
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
  File "spacy\tokens\token.pyx", line 867, in spacy.tokens.token.Token.pos_.__get__
KeyError: -1059636719
```

Am I creating the `Doc` object in a wrong way? Can data similar to mine be transformed into a `Doc`? I've noticed that the addition of the `pos` field to the Doc object was introduced in version 3.

Thanks!

## Your Environment
- **spaCy version:** 3.1.2
- **Platform:** Windows-10-10.0.19043-SP0
- **Python version:** 3.9.6
- **Pipelines:** en_core_web_sm (3.1.0)

**Comment by polm** [comment]
This is not exactly a bug so I'm going to move it to Discussions.
