### ISSUE TITLE
Error in downloading English model in Spacy

### ISSUE THREAD

**Issue by debayandaw** [explosion/spaCy#916]
**For importing spacy:** 
```
>import spacy
>nlp = spacy.load('en')
```
**Error:**
------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-48-621eaf8aba11> in <module>()
----> 1 nlp = spacy.load('en')

C:\Users\debayan.daw\AppData\Local\Continuum\Anaconda2\lib\site-packages\spacy\__init__.pyc in load(name, **overrides)
     49         overrides['path'] = model_path
     50 
---> 51     return cls(**overrides)
     52 
     53 

C:\Users\debayan.daw\AppData\Local\Continuum\Anaconda2\lib\site-packages\spacy\en\__init__.pyc in __init__(self, **overrides)
     38         # Special-case hack for loading the GloVe vectors, to support <1.0
     39         overrides = fix_glove_vectors_loading(overrides)
---> 40         Language.__init__(self, **overrides)

C:\Users\debayan.daw\AppData\Local\Continuum\Anaconda2\lib\site-packages\spacy\language.pyc in __init__(self, **overrides)
    286 
    287         self.vocab     = self.Defaults.create_vocab(self) \
--> 288                          if 'vocab' not in overrides \
    289                          else overrides['vocab']
    290         add_vectors    = self.Defaults.add_vectors(self) \

C:\Users\debayan.daw\AppData\Local\Continuum\Anaconda2\lib\site-packages\spacy\language.pyc in create_vocab(cls, nlp)
     56         else:
     57             vocab = Vocab.load(nlp.path, lex_attr_getters=cls.lex_attr_getters,
---> 58                              tag_map=cls.tag_map, lemmatizer=lemmatizer)
     59         for tag_str, exc in cls.morph_rules.items():
     60             for orth_str, attrs in exc.items():

C:\Users\debayan.daw\AppData\Local\Continuum\Anaconda2\lib\site-packages\spacy\vocab.pyx in spacy.vocab.Vocab.load (spacy/vocab.cpp:4768)()
     99             serializer_freqs = None
    100 
--> 101         with (path / 'vocab' / 'strings.json').open('r', encoding='utf8') as file_:
    102             strings_list = json.load(file_)
    103         cdef Vocab self = cls(lex_attr_getters=lex_attr_getters, tag_map=tag_map,

C:\Users\debayan.daw\AppData\Local\Continuum\Anaconda2\lib\site-packages\pathlib.pyc in open(self, mode, buffering, encoding, errors, newline)
   1075                            opener=self._opener)
   1076         else:
-> 1077             return io.open(str(self), mode, buffering, encoding, errors, newline)
   1078 
   1079     def touch(self, mode=0o666, exist_ok=True):

IOError: [Errno 2] No such file or directory: 'C:\\Users\\debayan.daw\\AppData\\Local\\Continuum\\Anaconda2\\lib\\site-packages\\spacy\\data\\en\\vocab\\strings.json'

--------------------------------------------------------------------------------------------------------
To install the English model in Spacy, following have been tried: In cmd
```
1. python -m spacy download en
2. python -m spacy.en.download -- force all
```
**#Error while installing English model in spacy**
Traceback (most recent call last):
  File "C:\Users\debayan.daw\AppData\Local\Continuum\Anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\debayan.daw\AppData\Local\Continuum\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\debayan.daw\AppData\Local\Continuum\Anaconda2\lib\site-packages\spacy\en\download.py", line 5, in <module>
    download.en()
  File "C:\Users\debayan.daw\AppData\Local\Continuum\Anaconda2\lib\site-packages\spacy\deprecated.py", line 136, in en
    cls.load('en')
  File "C:\Users\debayan.daw\AppData\Local\Continuum\Anaconda2\lib\site-packages\spacy\deprecated.py", line 132, in load
    download(lang)
  File "C:\Users\debayan.daw\AppData\Local\Continuum\Anaconda2\lib\site-packages\spacy\cli\download.py", line 25, in download
    link_package(model_name, model, force=True)
  File "C:\Users\debayan.daw\AppData\Local\Continuum\Anaconda2\lib\site-packages\spacy\cli\link.py", line 27, in link_package
    symlink(model_path, link_name, force)
  File "C:\Users\debayan.daw\AppData\Local\Continuum\Anaconda2\lib\site-packages\spacy\cli\link.py", line 46, in symlink
    link_path.symlink_to(model_path)
  File "C:\Users\debayan.daw\AppData\Local\Continuum\Anaconda2\lib\site-packages\pathlib.py", line 1167, in `symlink_to`
    self._accessor.symlink(target, self, target_is_directory)
TypeError: symlink() takes exactly 3 arguments (4 given)
------------------------------------------------------------------------------------------------------------------
![error snapshot](https://cloud.githubusercontent.com/assets/25661797/24292518/acdc8e0e-10b3-11e7-9d03-94fc914b0c67.png)

##Environment Information: 
* **Python version:** 2.7.13
* **Platform:** Windows-10-10.0.10586
* **spaCy version:** 1.7.2
* **Installed models:*

**Comment by ines** [comment]
Thanks for the report – this looks like the same issue as #909 (closing this issue to keep the discussion in one place). There seem to be some general problem with symlinks on Windows, which is how models are linked to their shortcut, including a bug in `pathlib`.

While we're working on a Windows-only workaround, you can always install the models via pip and load them as a Python module:

```bash
pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-1.2.0/en_core_web_sm-1.2.0.tar.gz
```

```python
import spacy
import en_core_web_sm

nlp = en_core_web_sm.load()
```

You can also copy the model data into `spacy/data`, or manually create a symlink in that directory. This will allow you to also load models via `spacy.load('name_of_directory_or_symlink')`.
