### ISSUE TITLE
Default Color in displacy

### ISSUE THREAD

**Issue by yanaiela** [explosion/spaCy#9191]
Currently there's a default background color for entities in [displacy](https://github.com/explosion/spaCy/blob/master/spacy/displacy/render.py#L13)
It would be nice to be able to provide with a different default color.

It seems like a pretty easy change as there's already a `colors` variable being passed to the function. So a potential fix can simply provide it with another variable (e.g. `default_color`) and if it exists, use this as the color instead of the default one.

**Comment by polm** [comment]
Thanks for the suggestion! I think we'd be happy to take a PR for that.

**Comment by psychemedia** [comment]
There is a `bg` option when rendering  POS dependencies (eg `displacy.render(doc, style="dep", options={"bg":"ivory"})` but this option does not seem to be available when visualising named entities (`displacy.render(doc, style="ent")`).

**Comment by Kaustbh** [comment]
Hi, can I work on this issue ?

**Comment by svlandeg** [comment]
Sure, we would welcome a PR! 

FYI - here is some relevant help for getting start with contributing to the code base: https://github.com/explosion/spaCy/blob/master/CONTRIBUTING.md#contributing-to-the-code-base

**Comment by Kaustbh** [comment]
I tried changing the background color  for entities , take a look at pictures below , 

before -:
![before](https://github.com/explosion/spaCy/assets/97254178/ef849f85-1c2b-4183-8577-501d2b20e12d)

after -:
![after](https://github.com/explosion/spaCy/assets/97254178/377edd56-53cd-4106-b28a-4b0dd3e36bca)

please guide i am doing the right thing , or it is something different.

**Comment by Kaustbh** [comment]
please reply ?

**Comment by Kaustbh** [comment]
@svlandeg , @polm , @psychemedia , @yanaiela , please anyone reply .

**Comment by Kaustbh** [comment]
what are they trying to implement"? I've been trying to understand it for quite some time now and it's been a challenge! 😃

**Comment by yanaiela** [comment]
My intention was to change the background of the highlighted entities. For instance, in the image you included, instead of using `purple` for `Person`, you could add an argument that will make its background `blue`

**Comment by Kaustbh** [comment]
I think it is already implemented, 

```bash
import spacy 
from spacy import displacy

text = "When Sebastian Thrun started working on self-driving cars at Google in 2007, few people outside of the company took him seriously."

nlp = spacy.load("en_core_web_sm")
doc = nlp(text)
options = { "colors": {"ORG": "red","PERSON":"orange"}}
displacy.serve(doc, style="ent", options=options,auto_select_port=True)

```

output:
![Screenshot 2024-05-15 231333](https://github.com/explosion/spaCy/assets/97254178/21982371-9524-4435-a2bc-76f94270b9e7)

**Comment by yanaiela** [comment]
ok cool so we can close this issue!
