### ISSUE TITLE
spacy pretrain section

### ISSUE THREAD

**Issue by Data-Think-2021** [explosion/spaCy#9216]
Hi, the command line would be better consistent to be config.  "python -m spacy pretrain config_pretrain.cfg ./output --paths.raw_text ./data.jsonl "
![image](https://user-images.githubusercontent.com/50060023/133387940-c4d39a9a-d02d-463b-b8ad-a0447a71c7c0.png)

The Url: 
https://spacy.io/usage/embeddings-transformers#pretraining

**Comment by polm** [comment]
Thanks for pointing that out! Got the issue number wrong in the commit but this should be fixed by 1d57d78758a6dece13bf0574b69c0ef57e19b932.
