### ISSUE TITLE
`python -m spacy download en` attempts to install models in `/usr/lib/...` even when spacy is pip installed in `.local/lib/...` using `--user` flag

### ISSUE THREAD

**Issue by awhan** [explosion/spaCy#924]
I attempted installation using the following steps:

    pip install -U --user spacy
    python -m spacy download en

but the following error occurs:

<p class="verse">
error: could not create '/usr/lib/python3.6/site-packages/en_core_web_sm': Permission denied
</p>

I could successfuly install within a virtual environment as follows

    python -m venv spacy-venv
    source spacy-venv/bin/activate
    pip install -U pip
    pip install -U spacy
    python -m spacy download en

## Info about spaCy

* **spaCy version:** 1.7.2
* **Platform:** Linux-4.9.11-1-ARCH-x86_64-with-arch-Arch-Linux
* **Python version:** 3.6.0
* **Installed models:**

<details>
<summary>LOG - error: could not create '/usr/lib/python3.6/site-packages/en_core_web_sm': Permission denied</summary>
$ pip install -U --user spacy
Collecting spacy
  Using cached spacy-1.7.2.tar.gz
Requirement already up-to-date: numpy>=1.7 in ./.local/lib/python3.6/site-packages (from spacy)
Requirement already up-to-date: murmurhash<0.27,>=0.26 in ./.local/lib/python3.6/site-packages (from spacy)
Requirement already up-to-date: cymem<1.32,>=1.30 in ./.local/lib/python3.6/site-packages (from spacy)
Requirement already up-to-date: preshed<2.0.0,>=1.0.0 in ./.local/lib/python3.6/site-packages (from spacy)
Requirement already up-to-date: thinc<6.6.0,>=6.5.0 in ./.local/lib/python3.6/site-packages (from spacy)
Requirement already up-to-date: plac<1.0.0,>=0.9.6 in ./.local/lib/python3.6/site-packages (from spacy)
Requirement already up-to-date: six in /usr/lib/python3.6/site-packages (from spacy)
Requirement already up-to-date: pathlib in ./.local/lib/python3.6/site-packages (from spacy)
Requirement already up-to-date: ujson>=1.35 in ./.local/lib/python3.6/site-packages (from spacy)
Requirement already up-to-date: dill<0.3,>=0.2 in ./.local/lib/python3.6/site-packages (from spacy)
Requirement already up-to-date: requests<3.0.0,>=2.13.0 in /usr/lib/python3.6/site-packages (from spacy)
Requirement already up-to-date: wrapt in /usr/lib/python3.6/site-packages (from thinc<6.6.0,>=6.5.0->spacy)
Requirement already up-to-date: tqdm<5.0.0,>=4.10.0 in ./.local/lib/python3.6/site-packages (from thinc<6.6.0,>=6.5.0->spacy)
Requirement already up-to-date: cytoolz<0.9,>=0.8 in ./.local/lib/python3.6/site-packages (from thinc<6.6.0,>=6.5.0->spacy)
Requirement already up-to-date: termcolor in ./.local/lib/python3.6/site-packages (from thinc<6.6.0,>=6.5.0->spacy)
Requirement already up-to-date: toolz>=0.8.0 in ./.local/lib/python3.6/site-packages (from cytoolz<0.9,>=0.8->thinc<6.6.0,>=6.5.0->spacy)
Installing collected packages: spacy
  Running setup.py install for spacy ... done
Successfully installed spacy-1.7.2

$ python -m spacy download en

    Downloading en_core_web_sm-1.2.0/en_core_web_sm-1.2.0.tar.gz

Collecting https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-1.2.0/en_core_web_sm-1.2.0.tar.gz
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-1.2.0/en_core_web_sm-1.2.0.tar.gz (52.2MB)
    100% |████████████████████████████████| 52.2MB 28kB/s
Requirement already satisfied: spacy<2.0.0,>=1.7.0 in ./.local/lib/python3.6/site-packages (from en-core-web-sm==1.2.0)
Requirement already satisfied: numpy>=1.7 in ./.local/lib/python3.6/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: murmurhash<0.27,>=0.26 in ./.local/lib/python3.6/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: cymem<1.32,>=1.30 in ./.local/lib/python3.6/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: preshed<2.0.0,>=1.0.0 in ./.local/lib/python3.6/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: thinc<6.6.0,>=6.5.0 in ./.local/lib/python3.6/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: plac<1.0.0,>=0.9.6 in ./.local/lib/python3.6/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: six in /usr/lib/python3.6/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: pathlib in ./.local/lib/python3.6/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: ujson>=1.35 in ./.local/lib/python3.6/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: dill<0.3,>=0.2 in ./.local/lib/python3.6/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/lib/python3.6/site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: wrapt in /usr/lib/python3.6/site-packages (from thinc<6.6.0,>=6.5.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: tqdm<5.0.0,>=4.10.0 in ./.local/lib/python3.6/site-packages (from thinc<6.6.0,>=6.5.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: cytoolz<0.9,>=0.8 in ./.local/lib/python3.6/site-packages (from thinc<6.6.0,>=6.5.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: termcolor in ./.local/lib/python3.6/site-packages (from thinc<6.6.0,>=6.5.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: toolz>=0.8.0 in ./.local/lib/python3.6/site-packages (from cytoolz<0.9,>=0.8->thinc<6.6.0,>=6.5.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Installing collected packages: en-core-web-sm
  Running setup.py install for en-core-web-sm ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-5wpua0lk-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-1iz2035g-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/en_core_web_sm
    copying en_core_web_sm/__init__.py -> build/lib/en_core_web_sm
    creating build/lib/en_core_web_sm/en_core_web_sm-1.2.0
    copying en_core_web_sm/en_core_web_sm-1.2.0/meta.json -> build/lib/en_core_web_sm/en_core_web_sm-1.2.0
    creating build/lib/en_core_web_sm/en_core_web_sm-1.2.0/ner
    copying en_core_web_sm/en_core_web_sm-1.2.0/ner/config.json -> build/lib/en_core_web_sm/en_core_web_sm-1.2.0/ner
    copying en_core_web_sm/en_core_web_sm-1.2.0/ner/model -> build/lib/en_core_web_sm/en_core_web_sm-1.2.0/ner
    creating build/lib/en_core_web_sm/en_core_web_sm-1.2.0/vocab
    copying en_core_web_sm/en_core_web_sm-1.2.0/vocab/oov_prob -> build/lib/en_core_web_sm/en_core_web_sm-1.2.0/vocab
    copying en_core_web_sm/en_core_web_sm-1.2.0/vocab/vec.bin -> build/lib/en_core_web_sm/en_core_web_sm-1.2.0/vocab
    copying en_core_web_sm/en_core_web_sm-1.2.0/vocab/lexemes.bin -> build/lib/en_core_web_sm/en_core_web_sm-1.2.0/vocab
    copying en_core_web_sm/en_core_web_sm-1.2.0/vocab/strings.json -> build/lib/en_core_web_sm/en_core_web_sm-1.2.0/vocab
    copying en_core_web_sm/en_core_web_sm-1.2.0/vocab/serializer.json -> build/lib/en_core_web_sm/en_core_web_sm-1.2.0/vocab
    creating build/lib/en_core_web_sm/en_core_web_sm-1.2.0/deps
    copying en_core_web_sm/en_core_web_sm-1.2.0/deps/config.json -> build/lib/en_core_web_sm/en_core_web_sm-1.2.0/deps
    copying en_core_web_sm/en_core_web_sm-1.2.0/deps/model -> build/lib/en_core_web_sm/en_core_web_sm-1.2.0/deps
    creating build/lib/en_core_web_sm/en_core_web_sm-1.2.0/pos
    copying en_core_web_sm/en_core_web_sm-1.2.0/pos/config.json -> build/lib/en_core_web_sm/en_core_web_sm-1.2.0/pos
    copying en_core_web_sm/en_core_web_sm-1.2.0/pos/model -> build/lib/en_core_web_sm/en_core_web_sm-1.2.0/pos
    copying en_core_web_sm/meta.json -> build/lib/en_core_web_sm
    running install_lib
    creating /usr/lib/python3.6/site-packages/en_core_web_sm
    error: could not create '/usr/lib/python3.6/site-packages/en_core_web_sm': Permission denied

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-5wpua0lk-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-1iz2035g-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-5wpua0lk-build/
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/m/.local/lib/python3.6/site-packages/spacy/__main__.py", line 71, in <module>
    plac.Interpreter.call(CLI)
  File "/home/m/.local/lib/python3.6/site-packages/plac_ext.py", line 1142, in call
    print(out)
  File "/home/m/.local/lib/python3.6/site-packages/plac_ext.py", line 914, in __exit__
    self.close(exctype, exc, tb)
  File "/home/m/.local/lib/python3.6/site-packages/plac_ext.py", line 952, in close
    self._interpreter.throw(exctype, exc, tb)
  File "/home/m/.local/lib/python3.6/site-packages/plac_ext.py", line 964, in _make_interpreter
    arglist = yield task
  File "/home/m/.local/lib/python3.6/site-packages/plac_ext.py", line 1139, in call
    raise_(task.etype, task.exc, task.tb)
  File "/home/m/.local/lib/python3.6/site-packages/plac_ext.py", line 53, in raise_
    raise exc.with_traceback(tb)
  File "/home/m/.local/lib/python3.6/site-packages/plac_ext.py", line 380, in _wrap
    for value in genobj:
  File "/home/m/.local/lib/python3.6/site-packages/plac_ext.py", line 95, in gen_exc
    raise_(etype, exc, tb)
  File "/home/m/.local/lib/python3.6/site-packages/plac_ext.py", line 53, in raise_
    raise exc.with_traceback(tb)
  File "/home/m/.local/lib/python3.6/site-packages/plac_ext.py", line 966, in _make_interpreter
    cmd, result = self.parser.consume(arglist)
  File "/home/m/.local/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/m/.local/lib/python3.6/site-packages/spacy/__main__.py", line 30, in download
    cli_download(model, direct)
  File "/home/m/.local/lib/python3.6/site-packages/spacy/cli/download.py", line 25, in download
    link_package(model_name, model, force=True)
  File "/home/m/.local/lib/python3.6/site-packages/spacy/cli/link.py", line 21, in link_package
    pkg = importlib.import_module(package_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'en_core_web_sm'
</details>

**Comment by honnibal** [comment]
Thanks for the report. The download command is a shortcut for two steps:

* It runs `pip install` with the URL of the model archive
* It then runs `python -m spacy link` to set up a symlink within spaCy's package, so that `nlp = spacy.load('en')` works.

The bug here is that when we produce a call to `pip install`, we pass the environment, but we don't check whether the user has installed spacy into a different directory. We'll fix that.

As a workaround, you can always run `pip install` on the model archive explicitly, and then call `python -m spacy link` afterwards. This will let you control how the model is installed.

**Comment by mamoit** [comment]
I ran into this problem too.
As a work around, in order to run the download with elevated privileges, I set up a `virtualenv` and installed spacy and the `en` package there.

**Comment by poojithareddy638** [comment]
can u please help for installing pkgf for coreference using spacy?
what pkg or command should we use?
can anyone give me the command?

**Comment by ines** [comment]
Merging this with #1456!
