### ISSUE TITLE
n_process > 1 throws "RuntimeError: Input, output and indices must be on the current device" on Linux

### ISSUE THREAD

**Issue by Mwni** [explosion/spaCy#9242]
When trying to run `pipe(x, n_process=2)` on a transformer model (on GPU), the library throws
```
RuntimeError: Input, output and indices must be on the current device
``` 
at a PyTorch embedding layer. It appears as if the spawned process forgot that we're on the GPU. I assume this could be fixed easily, but don't know where exactly to apply the patch, because it's all wrapped in about 3 abstraction layers.

spaCy 3.1.2
Python 3.8
Linux 5.4.0

**Comment by adrianeboyd** [comment]
I tried this with `en_core_web_trf` and the behavior depends on where `spacy.require_gpu()` is called. If `spacy.require_gpu()` is not called globally, I see the error above, or if I call `spacy.require_gpu()` at the top level of the script. it prints the output and then segfaults. (But I have a new GPU setup that I haven't tested well yet, so the segfault could be unrelated.)

In general, you probably don't want to be combining multiprocessing with GPU. Multiprocessing means that you end up with multiple copies of the exact same model data taking up valuable GPU memory (for `n_process=2` you end up with three copies of the model on the GPU, with ~2G for each copy of the model) and there's some additional general overhead for multiprocessing.

It's often better to have a single process with the `batch_size` increased to use the available GPU memory. Be aware that you may need to do some preprocessing to keep the batch sizes even or you'll have more trouble with OOM errors on batches containing longer texts.

**Comment by Mwni** [comment]
My workload is heavily bottlenecked by the CPU and there was only one core per process utilized, so the additional VRAM overhead is acceptable. I solved this issue yesterday by implementing multiprocessing one level further up. Regardless, thank you for looking into this, Adriane.
