### ISSUE TITLE
Error installing / loading english model

### ISSUE THREAD

**Issue by Ognnav** [explosion/spaCy#925]
Using Conda install of Python 2.7 on Windows 64bit.

python -m spacy download en yields the following error:
  File "C:\Anaconda2\lib\site-packages\pathlib.py", line 1167, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
TypeError: symlink() takes exactly 3 arguments (4 given)

Screenshot:
![capture](https://cloud.githubusercontent.com/assets/26682050/24327952/07a89eb4-11a3-11e7-94a8-ae8bc199444d.PNG)

Found old thread that suggested to comment out the line in pathlib.py's symlink_to function. This allows the download to complete, but then the data folder is empty, resulting in error: No such file or directory: 'C:\\Anaconda2\\lib\\site-packages\\spacy\\data\\en\\vocab\\strings.json'
The data directory indeed does not contain the "en" subfolder.

**Comment by ines** [comment]
I think this may indeed be related to the `pathlib` bug or more generally, symlink issues on Windows (see #909). This is already [fixed on master](https://github.com/explosion/spaCy/blob/master/spacy/cli/link.py#L46) – if Windows and Python 2 is detected, it now uses `mklink`.

This fix will be included in the next release, coming very soon. In the meantime, you can either use the spaCy version currently on master, copy-paste the model data directory into `spacy/data`, or set up the symlink manually. `spacy.load('model_name')` will look for a directory or symlink of that name in `spacy/data`.
