### ISSUE TITLE
Does en_core_web_trf truncate documents to 512? 

### ISSUE THREAD

**Issue by ginward** [explosion/spaCy#9273]
It seems that the [documentation](https://github.com/explosion/spacy-models/releases/tag/en_core_web_trf-3.1.0) does not specify if `en_core_web_trf` truncates texts longer than 512 (or any other transformer limits). 

Is there such a truncation being performed?

**Comment by ginward** [comment]
This is related to https://github.com/explosion/spaCy/issues/6939

**Comment by ginward** [comment]
Or is it fine if each sentence is less than 512 length?

**Comment by ginward** [comment]
I am not too sure (from the documentation) that if the en_core_web_trf model uses transformer to segment sentences. If so, wouldn't documents longer than 512 length not be correctly sentenced?

**Comment by adrianeboyd** [comment]
By default the `transformer` component uses overlapping strided spans (see: https://spacy.io/api/transformer#span_getters) so you can train and predict on longer texts without issues on transformer models that have a fixed max length.

**Comment by adrianeboyd** [comment]
This isn't a bug, so let me move this to a discussion...
