### ISSUE TITLE
Compatibility error for language models

### ISSUE THREAD

**Issue by bhargavvader** [explosion/spaCy#928]
After installing spaCy v.1.7.3, when I run `python -m spacy download en` I get the following message:
```
 Compatibility error

    No compatible models found for v1.7.3 of spaCy.
```

Any idea how to go around fixing this?

**Comment by bhargavvader** [comment]
I get the same error for all the other models, as well.

**Comment by ines** [comment]
Ahh, forgot to add the latest version to the [compatibility table](https://github.com/explosion/spacy-models/blob/master/compatibility.json) – thanks for the report, fixing this now!

**Comment by bhargavvader** [comment]
Yup, all good. :)
