### ISSUE TITLE
ERROR :Aborting and saving the final best model. Encountered exception: MemoryError((4572849, 288), dtype('float32'))

### ISSUE THREAD

**Issue by taghouti-ghofrane** [explosion/spaCy#9286]
## How to reproduce the behaviour

i Create a Train data and i was trying to Trin the model 
an error that i dont know how to fixe it is :  
thinc.backends.numpy_ops.NumpyOps.seq2col
  File "thinc\backends\numpy_ops.pyx", line 80, in thinc.backends.numpy_ops.NumpyOps.alloc
numpy.core._exceptions.MemoryError: Unable to allocate 4.91 GiB for an array with shape (4572849, 288) and data type float32

⚠ Aborting and saving the final best model. Encountered exception:
MemoryError((4572849, 288), dtype('float32'))
## Your Environment

* Python Version Used: 3.9.0
* spaCy Version Used:3 .1.3

**Comment by polm** [comment]
Sounds like you just ran out of memory? Since this doesn't look like a bug I'm moving it to Discussions.
