### ISSUE TITLE
TextCategorizer.from_disk unable to load trained model 

### ISSUE THREAD

**Issue by 1danjordan** [explosion/spaCy#9303]
## How to reproduce the behaviour

I have a spaCy project that trains two separate text classifiers. I'm trying to load both models into a spaCy `Language` object, but it appears `TextCategorizer.from_disk` doesn't work because it's expecting to find a `strings.json` file in the wrong directory. I'm following [this thread](https://support.prodi.gy/t/multiple-separate-text-classifications-in-a-single-model/2289/5) on Prodigy support. First I train a model with `spacy train`: 

`python -m spacy train configs/config.cfg --output training/ --paths.train corpus/train.spacy --paths.dev corpus/dev.spacy --nlp.lang en` 

Then I try to load the `textcat` model like so

```python
import spacy
nlp = spacy.load('blank:en')
textcat = nlp.create_pipe('textcat')
textcat.from_disk('training/model-best/textcat/')
```

Resulting in this traceback:

```
ValueError                                Traceback (most recent call last)
<ipython-input-4-99891af671ac> in <module>
----> 1 textcat.from_disk('training/debit-model/model-best/textcat/')

~/opt/miniconda3/envs/txn-tagger/lib/python3.9/site-packages/spacy/pipeline/trainable_pipe.pyx in spacy.pipeline.trainable_pipe.TrainablePipe.from_disk()

~/opt/miniconda3/envs/txn-tagger/lib/python3.9/site-packages/spacy/util.py in from_disk(path, readers, exclude)
   1195         # Split to support file names like meta.json
   1196         if key.split(".")[0] not in exclude:
-> 1197             reader(path / key)
   1198     return path
   1199

~/opt/miniconda3/envs/txn-tagger/lib/python3.9/site-packages/spacy/pipeline/trainable_pipe.pyx in spacy.pipeline.trainable_pipe.TrainablePipe.from_disk.lambda8()

~/opt/miniconda3/envs/txn-tagger/lib/python3.9/site-packages/spacy/vocab.pyx in spacy.vocab.Vocab.from_disk()

~/opt/miniconda3/envs/txn-tagger/lib/python3.9/site-packages/spacy/strings.pyx in spacy.strings.StringStore.from_disk()

~/opt/miniconda3/envs/txn-tagger/lib/python3.9/site-packages/srsly/_json_api.py in read_json(path)
     49         data = sys.stdin.read()
     50         return ujson.loads(data)
---> 51     file_path = force_path(path)
     52     with file_path.open("r", encoding="utf8") as f:
     53         return ujson.load(f)

~/opt/miniconda3/envs/txn-tagger/lib/python3.9/site-packages/srsly/util.py in force_path(location, require_exists)
     22         location = Path(location)
     23     if require_exists and not location.exists():
---> 24         raise ValueError(f"Can't read file: {location}")
     25     return location
     26

ValueError: Can't read file: training/model-best/textcat/vocab/strings.json
```

I've been looking at the docs and the source code and am surprised because this seems to be the exact what that this is documented but maybe I've overlooked something here? 

## Info about spaCy

- **spaCy version:** 3.1.1
- **Platform:** macOS-11.5.2-x86_64-i386-64bit
- **Python version:** 3.9.6
- **Pipelines:** en_core_web_sm (3.1.0)

**Comment by adrianeboyd** [comment]
You want to load it like this:

```python
import spacy
nlp = spacy.load("training/model-best")

# usually you just want to run the whole pipeline
doc = nlp("This is a text.")

# if you want to inspect the component for some reason
textcat = nlp.get_pipe("textcat")
```

You don't want to load individual components like this because you're missing the configuration from `config.cfg` and the shared `vocab` from the top-level directory in the saved pipeline (`training/model-best`). For more details, have a look at: https://spacy.io/usage/processing-pipelines#pipelines

**Comment by adrianeboyd** [comment]
This isn't a bug, so let me move it to the discussion board...
