### ISSUE TITLE
Loading transformer model from bytes causes deserialization issue "mismatched structure"

### ISSUE THREAD

**Issue by oliviercwa** [explosion/spaCy#9317]
## How to reproduce the behaviour

1- Create a transformer based model (I am using Roberta multilingual) and save it to disk
2- Use the following code

```python
import spacy
from thinc.config import Config

# Load the model from disk and save a single file using to_bytes()
model = spacy.load(PATH _TO_MODEL)
with open('transformer_model', 'wb') as outfile:
  outfile.write(model.to_bytes())

# Load back the model starting from the config
config: Config = Config()
config = config.from_disk(PATH_TO_MODEL) 
lang_cls = spacy.util.get_lang_class(config["nlp"]["lang"])
nlp = lang_cls.from_config(config)

with open(Path('transformer_model'), 'rb') as infile:
  nlp.from_bytes(infile.read())
```

**Result**
**Cannot deserialize model: mismatched structure**

```
File "spaCy\spacy\pipeline\trainable_pipe.pyx", line 292, in spacy.pipeline.trainable_pipe.TrainablePipe.from_bytes.load_model
    self.model.from_bytes(b)
  File "spaCy\spacy\util.py", line 1197, in from_dict
    setter(msg[key])
  File "spaCy\spacy\util.py", line 1175, in from_bytes
    return from_dict(srsly.msgpack_loads(bytes_data), setters, exclude)
  File "spaCy\spacy\pipeline\trainable_pipe.pyx", line 301, in spacy.pipeline.trainable_pipe.TrainablePipe.from_bytes
    util.from_bytes(bytes_data, deserialize, exclude)
  File "spaCy\spacy\language.py", line 2026, in <lambda>
    b, exclude=["vocab"]
  File "spaCy\spacy\util.py", line 1197, in from_dict
    setter(msg[key])
  File "spaCy\spacy\util.py", line 1175, in from_bytes
    return from_dict(srsly.msgpack_loads(bytes_data), setters, exclude)
  File "spaCy\spacy\language.py", line 2028, in from_bytes
    util.from_bytes(bytes_data, deserializers, exclude)
```

**Notes**
If instead of loading the config, you just create an empty lang_cls:
```python
config: Config = Config()
config = config.from_disk(PATH_TO_MODEL) 
lang_cls = spacy.util.get_lang_class(config["nlp"]["lang"])
nlp = lang_cls()
```
Then it works but of course, all other pipes are missing

## Your Environment
* Operating System: Windows 10
* Python Version Used: 3.7.2
* spaCy Version Used: 3.1.3

**Comment by polm** [comment]
This looks like it's the same as #8319.

**Comment by oliviercwa** [comment]
Do you see any workaround other than using from_disk ?

**Comment by polm** [comment]
I think this works if you use `save` and `spacy.load`? It is a bug we are still addressing.

Since it does seem to be a duplicate closing for now, please follow the other issue for updates.

**Comment by oliviercwa** [comment]
Yes it does, unfortunately spacy.load requires the load from the disk or from a package (either way it is from the disk) and not from a stream of bytes (more typical when using the Cloud)

I will workaround it and hope the fix will come in the next release

Did you close the bug as it appears the same as #8319 ?

**Comment by polm** [comment]
#8319 is not closed, we're using that to track the bug. 

There is an at least partial fix merged in spacy-transformers but not yet released.
