### ISSUE TITLE
import spacy fails with trace - cannot import name 'prefer_gpu' from 'thinc.api'

### ISSUE THREAD

**Issue by aniruddhakal** [explosion/spaCy#9318]
## How to reproduce the behaviour

`import spacy`
produces following trace on fail:

ImportError                               Traceback (most recent call last)
<ipython-input-50-76a01d9c502b> in <module>
----> 1 import spacy

/usr/local/lib/python3.8/dist-packages/spacy/__init__.py in <module>
      9 
     10 # These are imported as part of the API
---> 11 from thinc.api import prefer_gpu, require_gpu, require_cpu  # noqa: F401
     12 from thinc.api import Config
     13 

ImportError: cannot import name 'prefer_gpu' from 'thinc.api' (/home/ubuntu/.local/lib/python3.8/site-packages/thinc/api.py)
`
## Your Environment

* Operating System: Ubuntu 20.04
* Python Version Used: python3.8
* spaCy Version Used: 3.1.3
* Environment Information: 
*  pip 21.0.1
* thinc 8.0.10
* click 8.0.1

**Comment by polm** [comment]
Based on #9319 I assume this is resolved, but if not let me know.

**Comment by andyhegedus** [comment]
I am getting similar error.
% **python -m spacy validate**
Traceback (most recent call last):
  File "/Users/andreashegedus/anaconda3/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/andreashegedus/anaconda3/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/andreashegedus/anaconda3/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/andreashegedus/anaconda3/lib/python3.7/site-packages/spacy/__init__.py", line 11, in <module>
    from thinc.api import prefer_gpu, require_gpu, require_cpu  # noqa: F401
ImportError: cannot import name 'prefer_gpu' from 'thinc.api' (/Users/andreashegedus/anaconda3/lib/python3.7/site-packages/thinc/api.py)

**Comment by polm** [comment]
Based on #9370 I assume this is no longer an issue for @andyhegedus. 

Note that if you have an error like this it's usually an issue with your installation. If you have a similar issue, please open a thread in the Installation of Discussions.
