### ISSUE TITLE
Suggestion enhancing spacy displacy for NERs.

### ISSUE THREAD

**Issue by joseberlines** [explosion/spaCy#9322]
Spacy offers a very nice display possibilities with displacy, including rendering in a Jupyter notebook:

![image](https://user-images.githubusercontent.com/33203439/135153161-17f13c5c-542d-4de3-80b8-aa0d5dea2626.png)

My proposal is to enhance the rendering as follows.

The NER displayed in the coloured box with the NER name could be enhanced by making if clickable.

```
displacy.render(doc, style="ent", func=f)

```

func could be passed a function that will be run getting the NER values.
If func is left empty the behaviour would be the same as right now, if func includes a function that function would receive the data: {NER text, span start, span end, ENT name}.

The user would then have the possibility to actuate with the NERs found by Spacy. For instance collecting them, or fire an action that would further process data, gather data, or operate on the data.

Example:

```
def add_comment(NERdata):
    with open('file.txt',a) as f:
        new_line = f'the text includes the words {NERdata['wording']} which is considered a {NERdata['name']}'
        f.write(new_line)

displacy.render(doc, style="ent", func=add_comment)
```

**Comment by polm** [comment]
Thanks for the suggestion! That sounds like a great idea, though it might be hard to include directly in displaCy - the server there is pretty minimal. Maybe there's a way to do something like this already with Streamlit or something?

**Comment by joseberlines** [comment]
I was more thinking about Jupyter labs. For sure there is possible to do it in the server and with streamlit, nonetheless as you see in the example I use render because i would like to use it within a jupyter lab. Jupyter lab is often considered an experimental place to code but often ends up being the real coding place. Streamlit (and other solutions) can not be used in a jupyter hub environment. Actually and as you mention it, this enhancement could actually be used to check a functionality that later on might be coded/deployed with/in streamlit (or other visualizing tool).

**Comment by joseberlines** [comment]
Actually you might mean something like this with streamlit https://link.medium.com/UfQayAdbXjb
But this is currently not possible in a jupyter hub environement.

**Comment by joseberlines** [comment]
I opened a question in SO: 
https://stackoverflow.com/questions/69391542/adding-functionality-to-a-spacy-ner-visualizer
But I still believe that there would be an option to plug a solution into displacy.render with ipywidgets. Still have to find how.

**Comment by polm** [comment]
Thanks again for this suggestion, but after consideration I'm going to close this as out of scope for the time being. In the short term this might be better served by projects focused on more interactive dashboards like Streamlit or Gradio, or notebook integrations like ipywidgets like you mentioned. 

If you do make (or find) a tool like this do let us know, whether here or in a new issue - it'd make a great addition to the [Universe](https://spacy.io/universe)!
