### ISSUE TITLE
No result difference using word2vec vectors for training NER in spacy 3

### ISSUE THREAD

**Issue by sagorbrur** [explosion/spaCy#9326]
Hello,
I have trained spacy NER model(pipeline(tok2vec, ner)) with my datasets and custom word vectors.
I prepared two training setups:

1. with default settings and with pre-trained word2vec vectors
2. with default settings and without  pre-trained word2vec vectors

I have trained both models 100 epochs in CPU with the same data. But my test result producing a similar F1 score **92.35**. Same validation result also: **91.50**.
It's like word2vec vectors provide no impact in my training. I have tried similar approach in spacy 2.3.5, the result was too different with **improvements**. 
Is there any modification that happened inside the NER pipeline training module with custom vectors?
Please let me know. 
Thanks in advance.

**NB: I have prepared the vector using `init vectors` commands**
## How to reproduce the behaviour

**Train-1**
```bash
python -m spacy train config.cfg \
--output ./logs/train1 \
--paths.train ./data/traindata/train.spacy \
--paths.dev ./data/traindata/val.spacy \
--paths.vectors ./vector/mycustom_vector_md \
-g -1
```
**Train-2**
```bash
python -m spacy train config.cfg \
--output ./logs/train2 \
--paths.train ./data/traindata/train.spacy \
--paths.dev ./data/traindata/val.spacy \
-g -1
```
## Your Environment

* Operating System: Ubuntu 20.04
* Python Version Used: 3.8
* spaCy Version Used: 3.1.2
* Environment Information:

**Comment by polm** [comment]
I suspect you are not enabling the use of static vectors. See [the docs](https://spacy.io/usage/embeddings-transformers#word-vectors-models) - is `include_static_vectors` true?

**Comment by sagorbrur** [comment]
Hi @polm ,
Thank you for your quick reply. 
I will try with `include_static_vectors` as true and train again. 
I will let you know the results.
Thanks again.

**Comment by sagorbrur** [comment]
Hi @polm ,
After making `include_static_vectors=true` result degraded:
test f1: 91.85 , val f1: 91.34 .
Is there any suggestion to reproduce similar result like spacy 2? please let me know.
NB: I used spacy2 default parameters. No fine-tuning did except adding word vectors.
thanks.

**Comment by polm** [comment]
Since this is definitely not a bug let me move it to Discussions...
