### ISSUE TITLE
spaCy convert on a directory instead of a file?

### ISSUE THREAD

**Issue by demongolem-biz** [explosion/spaCy#9347]
I just wanted to know if it is possible to use the `convert` tool directly on a directory of conll files, instead of just a single file?  I have a whole mess of them and it sure seems like working directly on a single file is not too useful for me.  Input Directory -> Output Directory would be my flow.

**Comment by svlandeg** [comment]
Hi! As a maintenance note: this is a good question for the discussions forum, so I'll move it there. The original issue will be closed and will link through to the open discussion thread.
