### ISSUE TITLE
matcher_example.py example not working correct

### ISSUE THREAD

**Issue by vladimircape** [explosion/spaCy#939]
I execute that script ,and get not expected results.
I have 1.6.0 Spacy
expected 

> Output
> Before
> Google ORG [u'NNP']
> google ORG [u'VB']
> google ORG [u'NNP']
> After
> Google Now PRODUCT [u'NNP', u'RB']
> google ORG [u'VB']
> google now PRODUCT [u'NNP', u'RB']
> Sydney True
> sydney False
> Sydney True
> sydney True
> SYDNEY True
> the Brisbane Broncos ORG
> the South Darwin Spiders ORG

got

> Before
> Google Now PERSON ['NNP', 'RB']
> After
> Google Now PERSON ['NNP', 'RB']
> Sydney True
> sydney False
> Sydney True
> sydney True
> SYDNEY True

Spacy didn't recognize ORG ,and google

**Comment by loryfelnunez** [comment]
Same here.

My workaround is:

```
from spacy.matcher import Matcher
import spacy

nlp = spacy.load('en')
patterns = {'GoogleNow': ['PRODUCT', {}, [[{'ORTH': 'Google'}, {'ORTH': 'Now'}]]]}

matcher = Matcher(nlp.vocab, patterns)

doc = nlp(u'This is Google Now.  This is about Google Now.')
matches = matcher(doc)
print ('matches ', matches)
#matches  [(1138934, 383, 2, 4), (1138934, 383, 9, 11)]
for match in matches:
    vocab_idx, entity_type_idx,c, d =  match
    print (matcher.vocab.strings[vocab_idx], matcher.vocab.strings[entity_type_idx])
#GoogleNow PRODUCT
#GoogleNow PRODUCT
```
## Environment

* **spaCy version:** 1.7.5
* **Platform:** Darwin-16.5.0-x86_64-i386-64bit
* **Python version:** 3.4.3
* **Installed models:** __cache__, en, en-1.1.0, en_core_web_md, en_glove_cc_300_1m_vectors-1.0.0

**Comment by slavaGanzin** [comment]
```
Before
Google Now PERSON ['NNP', 'RB']
After
Google Now PERSON ['NNP', 'RB']
Sydney True
sydney False
Sydney True
sydney True
SYDNEY True
the Brisbane Broncos ORG
```

# Environment

- spaCy version: 1.8.2
- Platform: Linux z 4.10.13-1-ARCH  x86_64 GNU/Linux
- Python version: 3.6.1
- Installed models: en, en_core_web_md

**Comment by ines** [comment]
Sorry about that – there are currently some issues with the `Matcher` (see #864) and related docs. For v2.0 alpha, we've improved the API and added more/better examples and documentation: https://alpha.spacy.io/docs/usage/rule-based-matching

Closing this and merging it with #864. This should hopefully all be fixed for the v2 release!
