### ISSUE TITLE
Training Quickstart: Pipeline Differences for textcat exclusive categories

### ISSUE THREAD

**Issue by pmbaumgartner** [explosion/spaCy#9404]
I was taking a look at the Training docs and using the Config widget with only a `textcat` component and noticed something: when I select "exclusive categories" for a textcat component, when that value is false, the pipeline does not contain a `tok2vec` component. However, when that's true, it does.

> exclusive categories=false
```
pipeline = ["textcat_multilabel"]
```

> exclusive categories=true
```
pipeline = ["tok2vec","textcat"]
```

Is this right, or does the multilabel config also need a `tok2vec` component? FWIW, the `tok2vec` component is still defined later in the config file.

## Which page or section is this issue related to?
https://spacy.io/usage/training#quickstart

**Comment by pmbaumgartner** [comment]
Interesting! Is there a reason multilabel only uses BOW? I thought the architecture would be mostly the same as binary.

In the `TextCategorizer` API docs where it links to the code, it looks like there are a few differences in the config files, but tok2vec should be used? Or at least it's in the default config string. I spotted a few other differences, here's the `diff` output:

```
5c5
< @architectures = "spacy.Tok2Vec.v1"
---
> @architectures = "spacy.Tok2Vec.v2"
15c15
< @architectures = "spacy.MaxoutWindowEncoder.v1"
---
> @architectures = "spacy.MaxoutWindowEncoder.v2"
23c23
< exclusive_classes = false
---
> exclusive_classes = true
```

**Comment by svlandeg** [comment]
This should now be fixed by https://github.com/explosion/spaCy/pull/9502 - thanks @pmbaumgartner for the report!
