### ISSUE TITLE
Serialization for trained models/pipelines are not portable to hosts with different byteorder. 

### ISSUE THREAD

**Issue by andrewsi-z** [explosion/spaCy#9428]
## How to reproduce the behaviour
Load a pre-trained model from little endian platform on big endian platform and attempt to use.
This results in the exception "ValueError: Little-endian buffer not supported on big-endian compiler"  as seen below in this post.

## Info about spaCy

- **spaCy version:** 3.1.3
- **Platform:** Linux-4.18.0-305.12.1.el8_4.s390x-s390x-with-glibc2.29
- **Python version:** 3.8.10
- **Pipelines:** en_core_web_sm (3.1.0)
- **Environment Information:** spaCy was built from source on an s390x system, which is big endian. 

Example: loading x86 saved models from fails:

```
nlp = spacy.load("en_core_web_sm")
doc = nlp("This is a sentence.")

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_75/3390045506.py in <module>
----> 1 doc = nlp("This is a sentence.")

/git/spaCy/spacy/language.py in __call__(self, text, disable, component_cfg)
   1003                 raise ValueError(Errors.E109.format(name=name)) from e
   1004             except Exception as e:
-> 1005                 error_handler(name, proc, [doc], e)
   1006             if doc is None:
   1007                 raise ValueError(Errors.E005.format(name=name))

/git/spaCy/spacy/util.py in raise_error(proc_name, proc, docs, e)
   1533 
   1534 def raise_error(proc_name, proc, docs, e):
-> 1535     raise e
   1536 
   1537 

/git/spaCy/spacy/language.py in __call__(self, text, disable, component_cfg)
    998                 error_handler = proc.get_error_handler()
    999             try:
-> 1000                 doc = proc(doc, **component_cfg.get(name, {}))
   1001             except KeyError as e:
   1002                 # This typically happens if a component is not initialized

/git/spaCy/spacy/pipeline/trainable_pipe.pyx in spacy.pipeline.trainable_pipe.TrainablePipe.__call__()

/git/spaCy/spacy/util.py in raise_error(proc_name, proc, docs, e)
   1533 
   1534 def raise_error(proc_name, proc, docs, e):
-> 1535     raise e
   1536 
   1537 

/git/spaCy/spacy/pipeline/trainable_pipe.pyx in spacy.pipeline.trainable_pipe.TrainablePipe.__call__()

/git/spaCy/spacy/pipeline/tok2vec.py in predict(self, docs)
    119         DOCS: https://spacy.io/api/tok2vec#predict
    120         """
--> 121         tokvecs = self.model.predict(docs)
    122         batch_id = Tok2VecListener.get_batch_id(docs)
    123         for listener in self.listeners:

/usr/local/lib/python3.8/dist-packages/thinc/model.py in predict(self, X)
    313         only the output, instead of the `(output, callback)` tuple.
    314         """
--> 315         return self._func(self, X, is_train=False)[0]
    316 
    317     def finish_update(self, optimizer: Optimizer) -> None:

/usr/local/lib/python3.8/dist-packages/thinc/layers/chain.py in forward(model, X, is_train)
     52     callbacks = []
     53     for layer in model.layers:
---> 54         Y, inc_layer_grad = layer(X, is_train=is_train)
     55         callbacks.append(inc_layer_grad)
     56         X = Y

/usr/local/lib/python3.8/dist-packages/thinc/model.py in __call__(self, X, is_train)
    289         """Call the model's `forward` function, returning the output and a
    290         callback to compute the gradients via backpropagation."""
--> 291         return self._func(self, X, is_train=is_train)
    292 
    293     def initialize(self, X: Optional[InT] = None, Y: Optional[OutT] = None) -> "Model":

/usr/local/lib/python3.8/dist-packages/thinc/layers/chain.py in forward(model, X, is_train)
     52     callbacks = []
     53     for layer in model.layers:
---> 54         Y, inc_layer_grad = layer(X, is_train=is_train)
     55         callbacks.append(inc_layer_grad)
     56         X = Y

/usr/local/lib/python3.8/dist-packages/thinc/model.py in __call__(self, X, is_train)
    289         """Call the model's `forward` function, returning the output and a
    290         callback to compute the gradients via backpropagation."""
--> 291         return self._func(self, X, is_train=is_train)
    292 
    293     def initialize(self, X: Optional[InT] = None, Y: Optional[OutT] = None) -> "Model":

/usr/local/lib/python3.8/dist-packages/thinc/layers/with_array.py in forward(model, Xseq, is_train)
     28 def forward(model: Model[SeqT, SeqT], Xseq: SeqT, is_train: bool):
     29     if isinstance(Xseq, Ragged):
---> 30         return _ragged_forward(
     31             cast(Model[Ragged, Ragged], model), cast(Ragged, Xseq), is_train
     32         )

/usr/local/lib/python3.8/dist-packages/thinc/layers/with_array.py in _ragged_forward(model, Xr, is_train)
     88 ) -> Tuple[Ragged, Callable]:
     89     layer: Model[ArrayXd, ArrayXd] = model.layers[0]
---> 90     Y, get_dX = layer(Xr.dataXd, is_train)
     91 
     92     def backprop(dYr: Ragged) -> Ragged:

/usr/local/lib/python3.8/dist-packages/thinc/model.py in __call__(self, X, is_train)
    289         """Call the model's `forward` function, returning the output and a
    290         callback to compute the gradients via backpropagation."""
--> 291         return self._func(self, X, is_train=is_train)
    292 
    293     def initialize(self, X: Optional[InT] = None, Y: Optional[OutT] = None) -> "Model":

/usr/local/lib/python3.8/dist-packages/thinc/layers/chain.py in forward(model, X, is_train)
     52     callbacks = []
     53     for layer in model.layers:
---> 54         Y, inc_layer_grad = layer(X, is_train=is_train)
     55         callbacks.append(inc_layer_grad)
     56         X = Y

/usr/local/lib/python3.8/dist-packages/thinc/model.py in __call__(self, X, is_train)
    289         """Call the model's `forward` function, returning the output and a
    290         callback to compute the gradients via backpropagation."""
--> 291         return self._func(self, X, is_train=is_train)
    292 
    293     def initialize(self, X: Optional[InT] = None, Y: Optional[OutT] = None) -> "Model":

/usr/local/lib/python3.8/dist-packages/thinc/layers/chain.py in forward(model, X, is_train)
     52     callbacks = []
     53     for layer in model.layers:
---> 54         Y, inc_layer_grad = layer(X, is_train=is_train)
     55         callbacks.append(inc_layer_grad)
     56         X = Y

/usr/local/lib/python3.8/dist-packages/thinc/model.py in __call__(self, X, is_train)
    289         """Call the model's `forward` function, returning the output and a
    290         callback to compute the gradients via backpropagation."""
--> 291         return self._func(self, X, is_train=is_train)
    292 
    293     def initialize(self, X: Optional[InT] = None, Y: Optional[OutT] = None) -> "Model":

/usr/local/lib/python3.8/dist-packages/thinc/layers/maxout.py in forward(model, X, is_train)
     47     W = model.get_param("W")
     48     W = model.ops.reshape2f(W, nO * nP, nI)
---> 49     Y = model.ops.gemm(X, W, trans2=True)
     50     Y += model.ops.reshape1f(b, nO * nP)
     51     Z = model.ops.reshape3f(Y, Y.shape[0], nO, nP)

/usr/local/lib/python3.8/dist-packages/thinc/backends/numpy_ops.pyx in thinc.backends.numpy_ops.NumpyOps.gemm()

/usr/local/lib/python3.8/dist-packages/blis/py.pyx in blis.py.gemm()

ValueError: Little-endian buffer not supported on big-endian compiler
```

**Comment by andrewsi-z** [comment]
I'm new to experimenting with spaCy and am trying to dive a bit deeper here to see if there is any possible workaround. 
I'm working through the debugging guide, etc. to see how best to display the model/pipeline constants (weights, etc.) to see if I can possibly correct them after load. 
I'm wondering if numpy arrays or objects are potentially backing the constants on load, and can potentially be adjusted (e.g. https://numpy.org/doc/stable/user/basics.byteswapping.html) for use as a potential work around.

**Comment by andrewsi-z** [comment]
After tracing through the code a bit, I seeing that to_numpy (referenced above) is only called on model save and not on load (at least I am not detecting it getting control). I did try changing this to save in little endian instead of native, but the problem persists.

Looking at from_disk (https://github.com/explosion/thinc/blob/a9b220da045619d12ef3c859e5e947d56cf9064e/thinc/model.py#L626-L629) I was able to see on s390x some of the weights here being loaded in little endian buffers. Although I think numpy knows how to handle this for python logic, I am assuming that this is causing issues in the cython code.
I tried adding logic here to convert the loaded weights and dtype to big endian, but errors persist. I believe this is likely because little endian buffers are in use for other constants not handled in the snippet I referenced. 
(Note that all thinc unit tests also checked out on s390x).

After more investigation (including function entry tracing, etc.) I am seeing that a number of different locations in both spacy and thinc appear to be participating in loading/processing various parts of the pipeline which is making it a bit difficult to get a firm grasp around which loaded values may still be in an incorrect format. 

I'm very new to spacy and so I apologize if this is more appropriate for a discussion thread. I will start one if so... I have a couple of questions as I'd like to try to address this issue:

1. Is any example code to navigate a pipeline and view the ndarrays and other loaded numeric values? I want to display their dtype attributes, etc. and this will help me understand what other areas may need to be touched. It may also help me create a temporary workaround (in the form of some python logic that can "correct" loaded models). 

2. For the small model, do you expect spaCy to directly load any weight values or would they all be processed through thinc calls? I generally saw most of this processing as spacy.util.py ->thinc.model.from_bytes and then a lot of convert_recursive hits... Note here that model.to_bytes will call to_numpy , but I see model.from_bytes as calling ops.asarray.

**Comment by adrianeboyd** [comment]
Ah, you're right, I got mixed up when I looked up the serialization functions.

I think the closest debugging option we have is `spacy debug model`, but I'm not sure it shows enough detail, and I'm also not sure it's currently working correctly (just now I kept running into errors, at least).

The model weights are all loaded through thinc. There are a small number of parameters stored in local configs in JSON or msgpack, but not as numpy arrays. I think the vectors data is the only place where numpy arrays are loaded directly in spacy.

**Comment by andrewsi-z** [comment]
I think I've just about got it narrowed down @adrianeboyd ... After my earlier changes, all of the keys, values, ndarrys, etc. match until things get to the forward pass of a hashembed layer.  I see hashembed.py function forward issues the following:

 `keys = model.ops.hash(ids, seed) % nV`

And the result is garbage, though all the inputs are the same.
 
The hash function is cython and resolves to hash in [numpy_ops.pyx.](https://github.com/explosion/thinc/blob/f1ea74a1b94db90d2776b40383b416a2a5319b68/thinc/backends/numpy_ops.pyx#L207-L223)

Looking at that code, it looks like it calls the x64 ([platform dependent](https://github.com/explosion/thinc/blob/f1ea74a1b94db90d2776b40383b416a2a5319b68/thinc/backends/numpy_ops.pyx#L218)) version of murmurhash.

**Comment by andrewsi-z** [comment]
Hello, 
I've opened an issue in draft against thinc for the changes: https://github.com/explosion/thinc/pull/559
This is sufficient for the spaCy small model support and the first phase of the thinc support. I think the thing I probably need feedback on is whether this approach is one we can move forward with and I'll move the PR out of draft.

**Comment by andrewsi-z** [comment]
murmurhash endian issues are being addressed here: https://github.com/andrewsi-z/murmurhash

- murmurhash3 fixes based on node support (see above discussion)
- murmurhash2 hash64a based on mumurhash3 design.

**Comment by andrewsi-z** [comment]
Updating just to sync up: 

-with the merge of https://github.com/explosion/thinc/pull/559, all thinc models are believed to handle byte order correctly (that is to say, in a portable way). 
- remaining endian issues are thought to be in handling of spaCy vectors. I will come back to this soon to see if I can create tests to expose the set of affected function.

**Comment by adrianeboyd** [comment]
This was the remaining `thinc` issue on our end: https://github.com/explosion/thinc/pull/584

I'll have a look at the vectors. Daniël added a new `to_ops` method to the vectors that should hopefully make this pretty simple to handle, I think. It's possible there's not much left to do.
