### ISSUE TITLE
Dependency parse wrong and different from Displacy?

### ISSUE THREAD

**Issue by JamEnergy** [explosion/spaCy#945]
Not sure if bug, but here's what to run.

```
def printParse(gen):
    x = list(gen)
    disp = " ".join(["[{0}: {1}]".format(word, word.dep_) for word in x])
    return disp

import spacy
nlp = spacy.load('en')
x = nlp("What does Lisa eat?")
printParse(x)
```

Prints

'[What: dobj] [does: aux] [Lisa: npadvmod] [eat: ROOT] [?: punct]'

Now check on DisplaCy:
https://demos.explosion.ai/displacy/?text=What%20did%20Lisa%20eat%3F&model=en&cpu=1&cph=1

Lisa is correctly identified as the nsubj.

What's going on? Am I doing something wrong or is my Spacy messed up?

## Info about spaCy

* **Python version:** 3.5.2
* **Installed models:** en
* **Platform:** Windows-10-10.0.14393-SP0
* **spaCy version:** 1.7.2

**Comment by JamEnergy** [comment]
This might be a regression.

I downgraded to 1.6.0 and I got correct results

eg "What does XXXX drink?"
[What: dobj] [does: aux] [XXXX: nsubj] [drink: ROOT] [?: punct]

**Comment by pokey** [comment]
I've also seen some regressions after upgrading to 1.7.5.  In particular, the following is no longer parsed correctly, even though it was fine in SpaCy 1.6.0:

   > "Our small, London-based firm is seeking new clientele."

'Our' now modifies 'small,' when it should modify 'firm'.

There are also some regressions with POS tagging:

   > "the New York-based co-operative was fine-tuning forty-two K-9-like models."
   > "Non-standard spacing with padding and multiple spaces"

Obviously the parser/tagger will always make some errors, and we can't expect the errors to be the same from version to version, but maybe there's some specific issue responsible for these regressions

**Comment by honnibal** [comment]
Are you using the large model, or the small model?

**Comment by pokey** [comment]
I'm using the `en_core_web_md-1.2.1` model.

**Comment by thomasopsomer** [comment]
I'm experimenting the same behaviour: wrong result using spacy with the large model (even upgraded to latest 1.8 to check), but results on displacy are correct.

I have no problem with the accuracy of the parser in general, obviously there will be some mistake :) but it could be nice to have comparable models on https://demos.explosion.ai/displacy/, as it is a great tool for experimenting and developing functions with the dependency tree.

**Comment by ines** [comment]
Closing this and making #1057 the master issue – work in progress for spaCy v2.0!
