### ISSUE TITLE
Sentence ending in "I" doesn't parse correctly

### ISSUE THREAD

**Issue by bydesign** [explosion/spaCy#949]
I'm running spacy on MacOS 10.12.3 with Python 2.7.13. Just installed Spacy a couple weeks ago so I think it's the latest version.

I'm parsing the following text (string includes quotes):
“Have courage! It is I. Do not be afraid.”

When parsing that with spacy it thinks that there are two sentences instead of 3. It even considers "I." to be a single token. Is this a bug or is there something else going on?

**Comment by honnibal** [comment]
This is ultimately a tokenization issue. It's hard to resolve: sometimes we want `I.` to be an abbreviation, other times, we don't. Given the incorrect tokenization, the subsequent models fail.

**Comment by bydesign** [comment]
In all my documents I don't have any abbreviations, so is there a way to
prefer the other tokenization method?

**Comment by honnibal** [comment]
You can add a tokenizer exception for this case --- see here: https://spacy.io/usage/linguistic-features#special-cases

(Sorry for letting this go unanswered so long! I missed your last reply.)
