### ISSUE TITLE
util.get_installed_models() does not pick up newly installed models from environment

### ISSUE THREAD

**Issue by jboynyc** [explosion/spaCy#9513]
## How to reproduce the behaviour

```python
lang = "en_core_web_sm" 
if lang not in spacy.util.get_installed_models():
    spacy.cli.download(lang) # -> successful install, model can be loaded
assert lang in spacy.util.get_installed_models() # -> AssertionError
```

## Your Environment

- **spaCy version:** 3.1.3
- **Platform:** Linux-5.13.12-x86_64-with-glibc2.32
- **Python version:** 3.9.4
- **Pipelines:** en_core_web_sm (3.1.0), de_core_news_md (3.1.0)

**Comment by adrianeboyd** [comment]
The models are installed as python packages and this is a known limitation related to the detection of newly installed packages in a running python process (default: the list of installed packages is only generated once when python starts). See the warning here: https://spacy.io/usage/models#download-python

We'll look again to see if there's a feasible workaround now that we're using python 3.6+, but we're not sure there's going to be a good portable solution across the range of python versions that we currently support.

**Comment by jboynyc** [comment]
Makes sense, and sorry I missed that warning.
