### ISSUE TITLE
NER resizing error in combination with entity rulers

### ISSUE THREAD

**Issue by smisra1** [explosion/spaCy#9522]
My spacy version is 2.3.7.

The aim is to retrain my existing custom NER model multiple times with incoming batches of input data. Overlooking "catastrophic forgetting", I still want to retrain the model multiple times.

I could run, load and retrain my custom model 2 times successfully. But, on trying to run the model the 3rd time, I get the error for the code `nlp = spacy.load('mymodel')` as:

`ValueError: could not broadcast input array from shape (1258,64) into shape (1226,64)`

The work-around suggested worked only when the labels while retraining were the same as those added when the model was first trained. When I tried to retrain the model with a mixture of records with old and new labels, I received the same error.

I have not been able to create a reproducible snippet as this seems to happen when there are many labels that are added. In this retraining, 11,000 records with around 300 new labels were used to retrain the model. 

The following is the previous discussion on the same problem.

_Originally posted by @smisra1 in https://github.com/explosion/spaCy/discussions/8864_

**Comment by adrianeboyd** [comment]
Hi, let's keep the discussion for this in the existing bug report #8923.
