### ISSUE TITLE
SpanGroup doesn't allow access to original spans

### ISSUE THREAD

**Issue by nrodnova** [explosion/spaCy#9556]
## How to reproduce the behaviour

Use case: I use a custom entity ruler to populate `doc.spans`, a `SpanGroup` per entity label,  to allow overlapping spans between different entity types. After the NER step is completed, I check for certain conditions and for some spans I change `kb_id`. Looks like `SpanGroup` class creates copies of `Spans` when iterating through them. So the assigned `kb_id` gets lost. There is no elegant solution to the problem except for iterating through each `Span` in a `SpanGroup` and create a new group each time `kb_id` needs to be re-assigned. There is no way to delete or replace a particular span from `SpanGroup`.

Here is code example:

### Set up
```
import spacy
from spacy.tokens import Span, SpanGroup

nlp = spacy.load("en_core_web_sm")

text = "Span 1, Span 2"
doc = nlp(text)

nlp('kb_id_2') # add to the vocab
span_1 = Span(doc, 0, 2, label = "TEST", kb_id = 'kb_id_1')

```
### Iterating through `SpanGroup` and re-assigning `kb_id`
```
doc.spans['TEST'] = [span_1]
for span in doc.spans['TEST'] :
    print("Before: %s" % span.kb_id_)
    span.kb_id = nlp.vocab.strings['kb_id_2']
    print("After: %s" % span.kb_id_)

```
### Output:
```
Before: kb_id_1
After: kb_id_2
```
### Now, iterate through the `SpanGroup` again:
```
for span in doc.spans['TEST'] :
    print(span, "=>", span.kb_id_)
```
### Output (unchanged `kb_id`):
```
Span 1 => kb_id_1
```
Any help will be greatly appreciated.

## Your Environment

- **spaCy version:** 3.0.6
- **Platform:** Darwin-20.3.0-x86_64-i386-64bit
- **Python version:** 3.7.9
- **Pipelines:** en_core_web_lg (3.0.0), en_core_web_md (3.0.0), en_core_web_sm (3.0.0)

**Comment by polm** [comment]
Thanks for the detailed explanation of your use case. You are correct that this is the way the SpanGroup works at the moment. In particular, it's correct the easiest way to change values is to recreate the SpanGroup.

I need to check to be sure but I think it works this way for efficiency or serialization related reasons and this is a side effect of that, so not a bug. However we should definitely make this more apparent in the docs, so thanks for bringing it to our attention.

**Comment by kinghuang** [comment]
> I need to check to be sure but I think it works this way for efficiency or serialization related reasons and this is a side effect of that, so not a bug. However we should definitely make this more apparent in the docs, so thanks for bringing it to our attention.

On a related note, the same happens for [Doc.ents](https://spacy.io/api/doc#ents). That's tripped me up before where I only modify the returned Spans and forget to set the entities back on the Doc to apply the changes.

**Comment by nrodnova** [comment]
@kinghuang I was able to modify entities directly in the past, haven't checked it recently. But I imagine, something would get broken in my code if it changed. I was able to set `ent_type_` and `ent_id_`, on the token level. But with spans that are in `SpanGroup` it is different, `kb_id_` is not shared with underlying `Tokens` (which I think is right, it allows to have different `kb_ids` for overlapping spans.)

**Comment by nrodnova** [comment]
@polm I experimented a bit more, I can change user-assigned attributes in Spans that are a part of SpanGroup. But not `kb_id`, and I imagine, not `label`.

**Comment by nrodnova** [comment]
@polm I poked around the code a bit more. And looks like I'll need some advice. First of all, @kinghuang, the reason why I was able to set labels/entity ids without resetting `doc.ents` was that I would actually set values on the underlying `Tokens`. This wouldn't work on potentially overlapping spans in `SpanGroups`.
So, I see what is happening in `SpanGroup`. It doesn't actually store `Spans`, it stores a list of data structures describing `Spans`: `start`, `end`, `label`, `kb_id` and a few other attributes. `SpanGroup.__get_item__` creates a new instance of `Span` using that data structure.  So, whatever values are set, they get discarded unless `SpanGroup` is re-initialized with a new list of `Spans`. I don't like the way it works, but I can work around it. 

However, I discovered another potential problem. I have't looked in `Underscore` class before and didn't realize that `_` values were actually stored in `Doc.user_data` dictionary. The key into the dictionary for `spans` is a tuple `('_', variable_name, start_char, end_char)` which is a problem for overlapping spans. Say, I have 2 `Spans` pointing to the same sequence of tokens, i.e. their `start_char` and `end_char` are identical. These 2 spans can have different labels and kb_ids, but their `_` values would override each other because the key in `Doc.used_data` is based on `start_char` and `end_char`. 

At first, to overcome the problem of not being able to change `kb_id_` on a `Span` within `SpanGroup`, I was thinking of using a custom attribute for `kb_id`. And because of the issue described above, it won't work on the spans pointing to the same tokens. Should I try to override `Underscore` class and add more keys in `Doc.user_data` or you guys have better suggestions?

**Comment by nrodnova** [comment]
@polm I thought a bit more about this. Pointing `Span.c` to an element in the `SpanGroup.c` vector would be a memory management nightmare. Would it be possible at least to add a `__setitem__` function that takes an index and a `Span` and sets the underlying structure? I really hate re-creating `SpanGroup` every time I want to change something :) It would be something like this:
```
def __setitem__(self, i, span)
    cdef int size = self.c.size()
    if i < -size or i >= size:
        raise IndexError(f"list index {i} out of range")
    if i < 0:
        i += size
    if span :
        self.c[i] = span.c # Assuming the copy constructor will be called, sorry I am unfamiliar with Cython

```
I don't see any downside in having this method

**Comment by adrianeboyd** [comment]
Memory management and dealing with the `doc` references in the `Span` objects (vs. `SpanC` structs) is indeed the problem. We have discussed this internally without coming up with a good general solution thus far. We used to make all spans read-only, but that also has a lot of drawbacks. We can have a look at the setter idea, but it's still going to be confusing for people who just try to modify the span directly.

**Comment by nrodnova** [comment]
@adrianeboyd Any reason you store `SpanGroup`'s spans in an stl vector? Besides serialization? I am almost tempted to just use a custom dictionary of lists of spans instead of `doc.spans`. This will require some additional work when serializing/de-serializing, but I'd say span manipulation easiness is more important than some extra work during serialization.

**Comment by adrianeboyd** [comment]
The problem is circular references and garbage collection. If you store a list of `Span` objects that include `span.doc` within `Doc.spans`, then the doc never gets garbage collected.

**Comment by nrodnova** [comment]
@adrianeboyd Hmm, good point. But I actually have been storing `Spans` in `Doc._` attributes (individual ones, not lists, but I don't think it matters), and ran that model on millions of texts in batches, and never ran out of memory. I will look into it more, now I am curious.

**Comment by adrianeboyd** [comment]
The relevant test related to the weakref is here (not where you'd expect, admittedly, but it's easier with a minimally trained component to test with):

https://github.com/explosion/spaCy/blob/2bf52c44b1cecc62204bf9366a559bcef305b8ee/spacy/tests/pipeline/test_spancat.py#L82-L101

I implemented a version using a list of `Span` objects rather than the vector of `SpanC` and this test fails. As much as I could tell digging into the refcounts, the doc doesn't get freed.

**Comment by nrodnova** [comment]
@adrianeboyd Would you be willing to have `Span.c` struct changed to a `shared_ptr<SpanC>`? Then `SpanGroup` would contain `vector<shared_ptr<SpanC>>` I experimented with it yesterday (on a few mock-up classes) I think it looks pretty neat and data doesn't get copied back and forth, and spans get updated. Here's a repository:
https://github.com/nrodnova/cython-test
This is my first time using cython, so please bear with me. It was fun to brush up my C++ though, haven't written a line since 2015 or so.

If you don't oppose the idea, I think I can get it done over the weekend and then run performance/memory tests to see how the change affects things. I think it would make things cleaner around `SpanGroup`

**Comment by svlandeg** [comment]
Hi @nrodnova ! We do think the idea of using `shared_ptr` would be nice, we're looking at implementation details here: https://github.com/explosion/spaCy/pull/9869
