### ISSUE TITLE
UserWarning: User provided device_type of 'cuda', but CUDA is not available.

### ISSUE THREAD

**Issue by system1system2** [explosion/spaCy#9570]
Hi. I installed spaCy on an x86 Apple laptop **without a CUDA-capable GPU** as indicated in the documentation:

`pip install -U pip setuptools wheel`
`pip install -U spacy`

The command triggered the installation of all necessary dependencies. In this particular case:` typing-extensions`, `numpy`, `murmurhash`, `cymem`, `catalogue`, `wasabi`, `typer`, `srsly`, `smart-open`, `pyparsing`, `pydantic`, `preshed`, `MarkupSafe`, `blis`, `thinc`, `spacy-legacy`, `pathy`, `packaging`, `jinja2`, `spacy`.

It works fine, but as soon as my Python script starts, I receive the following warning:

```
/usr/local/lib/python3.9/site-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
```

## My Environment
- **spaCy version:** 3.1.4
- **Platform:** macOS-12.0.1-x86_64-i386-64bit
- **Python version:** 3.9.6
- **Pipelines:** en_core_web_trf (3.1.0)

**Comment by polm** [comment]
I guess this was created by mistake? Thanks for closing it, I'll just link in #9571 for posterity.
