### ISSUE TITLE
EntityLinker encounters IndexError if token length of Example predicted and reference Docs aren't equal

### ISSUE THREAD

**Issue by kinghuang** [explosion/spaCy#9575]
I've been having trouble training an entity_linker component. It's raising an uncaught `IndexError` getting the `kb_id` for an `ent`.

<details>
<summary>IndexError: list index out of range</summary>

```
⚠ Aborting and saving the final best model. Encountered exception:
IndexError('list index out of range')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/spacy/__main__.py", line 4, in <module>
    setup_cli()
  File "/usr/local/lib/python3.9/site-packages/spacy/cli/_util.py", line 69, in setup_cli
    command(prog_name=COMMAND)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/spacy/cli/train.py", line 63, in train_cli
    train(nlp, output_path, use_gpu=use_gpu, stdout=sys.stdout, stderr=sys.stderr)
  File "/usr/local/lib/python3.9/site-packages/spacy/training/loop.py", line 122, in train
    raise e
  File "/usr/local/lib/python3.9/site-packages/spacy/training/loop.py", line 105, in train
    for batch, info, is_best_checkpoint in training_step_iterator:
  File "/usr/local/lib/python3.9/site-packages/spacy/training/loop.py", line 203, in train_while_improving
    nlp.update(
  File "/usr/local/lib/python3.9/site-packages/spacy/language.py", line 1122, in update
    proc.update(examples, sgd=None, losses=losses, **component_cfg[name])
  File "/usr/local/lib/python3.9/site-packages/spacy/pipeline/entity_linker.py", line 238, in update
    kb_id = kb_ids[ent.start]
IndexError: list index out of range
```
</details>

I've been able to track down the problem to cases where the `predicted` Doc in the Example is tokenized differently than the `reference` Doc. When the `entity_linker` component gets the aligned view of the `ENT_KB_ID` attribute, and then gets the `kb_id` for each reference Doc's `ent` based on the `start` index, an index error can occur because the aligned view reflect's the `predicted` Doc's tokens, while the `reference` Doc's `ent` spans are the `reference` Doc's tokens.

https://github.com/explosion/spaCy/blob/5279c7c4baf5b9f26a364f07551acecf26a2d42f/spacy/pipeline/entity_linker.py#L230-L233

https://github.com/explosion/spaCy/blob/5279c7c4baf5b9f26a364f07551acecf26a2d42f/spacy/pipeline/entity_linker.py#L269-L271

## How to reproduce the behaviour

Here is a reduction demonstrating the condition leading to the `IndexError`.

```python
import spacy
from spacy.tokens import Doc
from spacy.training import Example

nlp = spacy.blank("en")
doc1 = Doc(nlp.vocab, words=["123456"], spaces=[False], ents=["B-CARDINAL"])
doc2 = Doc(nlp.vocab, words=["123", "456"], spaces=[False, False], ents=["B-CARDINAL", "B-CARDINAL"])

eg = Example(doc1, doc2)

kb_ids = eg.get_aligned("ENT_KB_ID", as_string=True)
for ent in eg.reference.ents:
    kb_id = kb_ids[ent.start]
```

```
IndexError: list index out of range
```

## Info about spaCy

- **spaCy version:** 3.1.3
- **Platform:** Linux-5.10.47-linuxkit-x86_64-with-glibc2.31
- **Python version:** 3.9.7
- **Pipelines:** en_core_web_lg (3.1.0)

**Comment by kinghuang** [comment]
I've monkeypatched my `entity_linker.py` to get `kb_id_` from the entity in the iteration as a temporary workaround.

```python
kb_ids = eg.get_aligned("ENT_KB_ID", as_string=True)
for ent in eg.reference.ents:
	# KB ID of the first token is the same as the whole span
	# kb_id = kb_ids[ent.start]
	kb_id = ent.kb_id_
```

**Comment by polm** [comment]
> I've been able to track down the problem to cases where the predicted Doc in the Example is tokenized differently than the reference Doc.

Out of curiosity, what is causing this to happen? You can set arbitrary docs in an Example pair but normally I would expect them to have been run through the same tokenizer.

**Comment by kinghuang** [comment]
There's a component named `affix_splitter` at the beginning of the pipeline that retokenizes to split off certain prefixes/suffixes on a per Doc basis. It uses a value that's set in an extension on the Doc.

```toml
[nlp]
lang = "en"
pipeline = ["tok2vec","affix_splitter","..."]
```
I haven't had a chance to look into it yet, but I suspect that extension value is missing or set too late when the Docs are resurrected from the DocBin corpus. Because, the retokenization doesn't seem to work during training.

I do have the component listed for `annotating_components` in the config, so I believe it should run during training.

```toml
[training]
annotating_components = ["affix_splitter"]
```

**Comment by adrianeboyd** [comment]
The predicted/reference docs definitely don't have to have the same tokenization and `Example.get_aligned` should manage misalignments by returning null/missing annotation for cases to skip during training and count as wrong during evaluation. It sounds like it might be the case that the entity linker doesn't handle some of the types of misalignments correctly? I'd have to look more carefully at the code to know for sure.

There's also a slight chance the culprit could be the `Example` caching of the alignment. The test suite does have some basic tests for this, but we haven't tested it a ton in practice, so it's possible there's a bug. Try creating the `Example` with the original tokenization, applying the retokenization to the predicted doc, and then checking the alignment? Here's the test case that we check in the test suite:

https://github.com/explosion/spaCy/blob/c97f29c593c2e91bde62777869e6f5b0f3a7af26/spacy/tests/training/test_training.py#L839-L852
