### ISSUE TITLE
[Config initialization] Config validation error: Bad value substitution with tok2vec component's width

### ISSUE THREAD

**Issue by enjuichang** [explosion/spaCy#9581]
## The Problem
I was using the quickstart tutorial for text classification but the `base_config.cfg` failed to initialize and returned the error
``` shell
Config validation error

Bad value substitution: option 'width' in section 'components.textcat.model.tok2vec' contains an interpolation key 'components.tok2vec.model.encode.width' which is not a valid option name. Raw value: '${components.tok2vec.model.encode.width}'
```

## How to reproduce the behaviour

Use the `base_config.cfg` from the quickstart tutorial. Specific choices were for Language: English, Components: textcat, Text Classification: Exclusive category, Hardware: CPU, and Optimize for: accuracy. 

 I then run `python -m spacy init fill-config ./base_config.cfg ./config.cfg` to initialize the config file.

## Your Environment

* Operating System: MacOS
* Python Version Used: Python 3.7
* spaCy Version Used: 3.1.4

**Comment by polm** [comment]
Thanks for the report, that definitely looks like a bug! We recently adjusted the quickstart textcat settings to clean them up a bit and may have made a mistake. 

As a workaround, you can add another component, like NER, to your pipeline to get the tok2vec parts added, and then you can manually delete the NER-related parts of the config.

**Comment by enjuichang** [comment]
Thanks for the update. I will try that out.

**Comment by benslack19** [comment]
@enjuichang did adding `ner` to your pipeline help? I just got back the same error.

**Comment by thomashacker** [comment]
You can try to remove the "tok2vec" from the pipeline in the `[nlp]` section. The textcat optimized for efficiency uses the [TextCatBow architecture](https://github.com/explosion/spaCy/blob/master/spacy/ml/models/textcat.py#L74) that doesn't require a tok2vec embedding.

**Comment by benslack19** [comment]
Thank you @thomashacker. That seemed to help in this case (I'm encountering a different error now).
