### ISSUE TITLE
RuntimeWarning: invalid value encountered in true_divide in EntityLinker

### ISSUE THREAD

**Issue by kinghuang** [explosion/spaCy#9588]
I'm training and predicting using the EntityLinker in a pipeline for the first time. The component is outputting a `RuntimeWarning` when it's called.

```
/usr/local/lib/python3.9/site-packages/spacy/pipeline/entity_linker.py:358: RuntimeWarning: invalid value encountered in true_divide
  sims = xp.dot(entity_encodings, sentence_encoding_t) / (
```

This happens both during training and when predicting in a pipeline.

## How to reproduce the behaviour

Not sure yet. Will attempt to narrow down later.

## Info about spaCy

- **spaCy version:** 3.1.3
- **Platform:** Linux-5.10.47-linuxkit-x86_64-with-glibc2.31
- **Python version:** 3.9.7
- **Pipelines:** en_core_web_lg (3.1.0), en_enverus_oi_ner (0.0.0), en_enverus_oi_nlp (0.0.0)

**Comment by polm** [comment]
Did you ever find a reproducible instance for this? I don't think we've seen it before, and without more details I don't think there's much we can do at present.

**Comment by kinghuang** [comment]
Sorry, I haven't been working on this lately. I'll open a new issue if I come across this again!
