### ISSUE TITLE
SpaCy 2.2.4+ Doesn't Install on ARM64 Architecture

### ISSUE THREAD

**Issue by JeffMII** [explosion/spaCy#9615]
## How to reproduce the behaviour
`pip install spacy==2.2.4`
or
`pip install spacy`

## Your Environment

* Operating System: Ubuntu Server 20.10
* Python Version Used:  Python 3.8.10
* spaCy Version Used: 2.2.4
* Environment Information: ARM64

## Error
```
gcc: error: unrecognized command line option ‘-mavx2’
gcc: error: unrecognized command line option ‘-mfma’
gcc: error: unrecognized command line option ‘-mfpmath=sse’
```

I am working on an NLP Web API in Python. The project works fine on my Windows machine, but I am getting the above error when I try running it on my Rasperry Pi 4. These errors seem to come from 'blis', but the problem was supposedly fixed according to an issue report in 2019 https://github.com/explosion/spaCy/issues/3451. That doesn't seem to be the case however.

**Comment by polm** [comment]
We recently had [a similar question](https://github.com/explosion/spaCy/discussions/9367#discussioncomment-1428399) about a Jetson Nano, which I think has similar hardware. v3 should just work for CPU usage on ARM64. Is upgrading to v3 an option for you?

There are also several more recent threads about running on raspberry pis, like [this one](https://github.com/explosion/spaCy/discussions/7372#discussioncomment-455387), that may be able to help you.

**Comment by JeffMII** [comment]
My project also has to use sense2vec 1.0.3 which has dependency requirements `sense2vec 1.0.3 depends on spacy<3.0.0 and >=2.2.3` so I don't think I can use spacy v3. Unless you know if the latest version of sense2vec can use spacy v3. If so, I may be able to make some small changes to the project to make it compatible. I'm not sure where to find any dependency list for python packages. Those dependency output was just what I happened to stumble across while trying to use lower versions of spacy.

**Comment by JeffMII** [comment]
Actually, I did try installing spacy==3.0.0, but it doesn't work either.

**Comment by adrianeboyd** [comment]
Let me move to the install section of the discussion board...
