### ISSUE TITLE
SpanCategorizer for default NER models

### ISSUE THREAD

**Issue by monWork** [explosion/spaCy#9643]
Is there a way we can use can we use SpanCategorizer component to get the confidence scores from the default trained models such as en_core_web_trf and en_core_web_md ?

We don't want to train new models, we just need the confidence scores for NER and POS from the default models, how it can be done ?

**Comment by polm** [comment]
No, you can't do that. There is kind of a workaround but it has many disadvantages. 

This is a question so it belongs in Discussions.
