### ISSUE TITLE
"python -m spacy download en" doesn't work

### ISSUE THREAD

**Issue by Harryhaha** [explosion/spaCy#965]
As title, the error message is "No module named spacy.main; 'spacy' is a package and cannot be directly executed", is there something wrong with my installation ? I install spacy via conda following the official instructions. Thanks !

Your Environment

Operating System: Mac
Python Version Used: Anaconda python3.5
spaCy Version Used: 1.7.3

**Comment by Harryhaha** [comment]
Sorry, my question is stupid.

**Comment by burglarhobbit** [comment]
Can you tell me how you solved it? I'm using conda and facing the same issue!

**Comment by f11r** [comment]
Do you have a directory `spacy` or a file `spacy.py` in the same directory you're running your script from? That would overwrite the spacy installation.

**Comment by burglarhobbit** [comment]
I changed the "conda install spacy" to "pip install spacy" and everything worked just fine.

Thanks!

**Comment by nikhilweee** [comment]
I had the same issue, but `python -m spacy.en.download` worked like a charm

**Comment by giullianomorroni** [comment]
try this on command line:

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

**Comment by Gunnvant** [comment]
I am getting the same error. Can some one help?

**Comment by alistat** [comment]
I changed to `pip install spacy` and I get `Requirement already satisfied: spacy in ./anaconda3/lib/python3.6/site-packages`.

On the other hand `python -m spacy.en.download` works great for 'en' but not for the multilingual 'xx'
