### ISSUE TITLE
`iob_to_biluo` and `biluo_to_iob` not documented

### ISSUE THREAD

**Issue by mukund109** [explosion/spaCy#9671]
The `iob_to_biluo` and `biluo_to_iob` functions are useful but they don't show up in the official docs. Would be nice if they can be updated, I can submit a PR if required.

## Which page or section is this issue related to?

https://github.com/explosion/spaCy/blob/master/spacy/training/iob_utils.py

**Comment by adrianeboyd** [comment]
Sure, a PR would be welcome! The functions would go in this section: https://spacy.io/api/top-level#gold. The source is in `website/docs/api/top-level.md`.

Don't be concerned if you can't get the website dev mode running locally, it's unfortunately harder than it should be to get all the dependencies installed. In any case, it would be appreciated if the PR is formatted with `prettier`. I just use `npx prettier --write filename.md` to run it outside of an IDE.

**Comment by zrpxx** [comment]
Since there is no update from @mukund109 in 2 weeks, I think opening #11901 might be helpful.
