### ISSUE TITLE
No Module Named thinc.types

### ISSUE THREAD

**Issue by paullaster** [explosion/spaCy#9683]
## Spacy Information

* **spaCy version:** 2.3.5
* **Platform:** Windows-10-10.0.19041-SP0
* **Python version:** 3.9.2
* Environment Information: 

I downgraded my Spacy to 2.3.5 and I am running into No module named 'thinc.types'. I have tried all the the suggested but didn't work for my! I am on a window 10 PC environment.

`pip list`
`spacy 2.3.5 `
`spacy-alignments 0.8.4 `
`spacy-legacy 3.0.8`
` spacy-loggers 1.0.1`
` spacy-lookups-data 1.0.3 `
`spacy-transformers 1.1.2`

`thinc 7.4.5`

`Exception in Tkinter callback Traceback (most recent call last): File "C:\Python39\lib\tkinter\__init__.py", line 1892, in __call__ return self.func(*args) File "C:\Users\#geek_laster\Desktop\cv_predictive_analysis\main.py", line 179, in <lambda> submitBtn.config(command=lambda: prediction_result(top,sName,loc,(gender.get(),age.get(),openness.get(),neuroticism.get(),conscientiousness.get(),agreeableness.get(),extraversion.get()))) File "C:\Users\#geek_laster\Desktop\cv_predictive_analysis\main.py", line 69, in prediction_result data = ResumeParser(cv_path).get_extracted_data() File "C:\Users\#geek_laster\AppData\Roaming\Python\Python39\site-packages\pyresparser\resume_parser.py", line 20, in __init__ nlp = spacy.load('en_core_web_sm') File "C:\Users\#geek_laster\AppData\Roaming\Python\Python39\site-packages\spacy\__init__.py", line 30, in load return util.load_model(name, **overrides) File "C:\Users\#geek_laster\AppData\Roaming\Python\Python39\site-packages\spacy\util.py", line 170, in load_model return load_model_from_package(name, **overrides) File "C:\Users\#geek_laster\AppData\Roaming\Python\Python39\site-packages\spacy\util.py", line 191, in load_model_from_package return cls.load(**overrides) File "C:\Python39\lib\site-packages\en_core_web_sm\__init__.py", line 12, in load return load_model_from_init_py(__file__, **overrides) File "C:\Users\#geek_laster\AppData\Roaming\Python\Python39\site-packages\spacy\util.py", line 239, in load_model_from_init_py return load_model_from_path(data_path, meta, **overrides) File "C:\Users\#geek_laster\AppData\Roaming\Python\Python39\site-packages\spacy\util.py", line 203, in load_model_from_path nlp = cls(meta=meta, **overrides) File "C:\Users\#geek_laster\AppData\Roaming\Python\Python39\site-packages\spacy\language.py", line 171, in __init__ user_factories = util.registry.factories.get_all() File "C:\Python39\lib\site-packages\catalogue.py", line 112, in get_all result.update(self.get_entry_points()) File "C:\Python39\lib\site-packages\catalogue.py", line 127, in get_entry_points result[entry_point.name] = entry_point.load() File "C:\Python39\lib\importlib\metadata.py", line 77, in load module = import_module(match.group('module')) File "C:\Python39\lib\importlib\__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "<frozen importlib._bootstrap>", line 1030, in _gcd_import File "<frozen importlib._bootstrap>", line 1007, in _find_and_load File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed File "<frozen importlib._bootstrap>", line 1030, in _gcd_import File "<frozen importlib._bootstrap>", line 1007, in _find_and_load File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 680, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 790, in exec_module File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed File "C:\Users\#geek_laster\AppData\Roaming\Python\Python39\site-packages\spacy_transformers\__init__.py", line 1, in <module> from . import architectures File "C:\Users\#geek_laster\AppData\Roaming\Python\Python39\site-packages\spacy_transformers\architectures.py", line 3, in <module> from thinc.types import Ragged, Floats2d ModuleNotFoundError: No module named 'thinc.types'`

**Comment by polm** [comment]
Since this is an install-related issue I'm moving it to Discussions.
