### ISSUE TITLE
Rules Based Matcher  with OP "!" and "?"

### ISSUE THREAD

**Issue by galtay-tempus** [explosion/spaCy#9689]
## How to reproduce the behaviour

I think this is a bug, but would be interested in hearing feedback. 

```
nlp = spacy.load("en_core_web_sm")

matcher = Matcher(nlp.vocab)
patterns = [[{"TEXT": "token1", "OP": "!"}, {"TEXT": "token2", "OP": "?"}, {"TEXT": "token3"}]]
matcher.add("TEST", patterns)

doc = nlp("token1 token2 token3")
matches = matcher(doc, with_alignments=True)
print(matches)
[(1046765068364475028, 1, 3, [0, 2])]

doc = nlp("token1 token3")
matches = matcher(doc, with_alignments=True)
print(matches)
[]
```

My expectations are that the "match 0 times" token with OP "!" would cause the first example to produce no matches. 

I also think maybe this is a bug b/c indexing into the doc with start = match[1] = 1 and end=match[2] = 3 raises an IndexError. 

EDIT: 
sorry, my confusion, `doc[1:3]` works fine in the first example. 

Thanks for the great library!  

## Your Environment

- **spaCy version:** 3.2.0
- **Platform:** Linux-4.14.248-189.473.amzn2.x86_64-x86_64-with-glibc2.17
- **Python version:** 3.8.12
- **Pipelines:** en_core_web_sm (3.2.0)

**Comment by adrianeboyd** [comment]
Glad you figured it out! Let me move this to the discussion board...
