### ISSUE TITLE
dependency path between two words on the dependency tree

### ISSUE THREAD

**Issue by thebeancounter** [explosion/spaCy#969]
Hello, 

I am using spacy with python 2.7 and parse a text. 

I am trying to create a relation extractor using SVM, and need the dependency path between two words.

Is there a straight forward way to get the syntactic chank path between two parts of a doc? 
doc[1].head -> doc[2].head 
i want to get somthing like 
NN->NP->NN 

Thanks!

**Comment by honnibal** [comment]
As mentioned on Gitter:

> That would be a useful function to have, but we don't have that implemented

If you have a paper you're implementing, could you give the reference? It would be nice to see more details of how they define the dependency path.

Labelling this `help wanted (easy)` because it's a fairly self-contained function, that doesn't require modification to the rest of the library.

**Comment by thebeancounter** [comment]
thanks!

**Comment by honnibal** [comment]
No problem!

More notes for anyone who wants to take this on:

I think a good general solution would be to implement a function that computes a table of [lowest common ancestors](https://en.wikipedia.org/wiki/Lowest_common_ancestor) for a slice of the document:

```
def get_lca_matrix(Doc doc, start=0, end=-1):
    return numpy.ndarray[int]
```

An example test (using the `spacy.tests.util.get_doc()` helper)

```python

def test_lowest_common_ancestor():
    doc = get_doc(['the', 'lazy', 'dog', 'slept'], heads=[2, 1, 1, 0])
    lca = get_lca_matrix(doc)
    # Lowest common ancestor of 'the' and 'lazy' is 'dog'
    assert lca[0, 1] == 2
    # Is a word its own ancestor? I think we should define it that way
    # This would make the LCA of (lazy, dog) "dog"
    assert lca[1, 2] == 2
```

**Comment by praveen049** [comment]
Hi , 
  If this task is still pending,  I would be interested in taking this task.

I have python programming background and have started working with spaCy recently.

Any inputs/suggestions for beginning on this ?

**Comment by mraduldubey** [comment]
@honnibal Is this still open devs?

**Comment by aribornstein** [comment]
Hey was this solved if so can you guys link to where? If not I'm working on an implementation now for a relation extraction assignment.
