### ISSUE TITLE
Kana is not included in the default suffix tokenization rules for English models

### ISSUE THREAD

**Issue by danmysak** [explosion/spaCy#9693]
## How to reproduce the behaviour
`nlp('You should learn words such as 犬.')[-1]` produces `.`, which is as expected.

However, `nlp('You should learn words such as いぬ.')[-1]` gives `いぬ.`, apparently due to both the hiragana and the katakana ranges being omitted from the regular expressions in `nlp.Defaults.suffixes`: `...\u3000-\u303F\u31C0-\u31EF...`.

## Your Environment
- **spaCy version:** 3.1.1
- **Platform:** macOS-11.6-x86_64-i386-64bit
- **Python version:** 3.9.6
- **Pipelines:** en_core_web_trf (3.1.0), en_core_web_lg (3.1.0)

**Comment by polm** [comment]
Thanks for the report, we'll take a look at it! I imagine this just hasn't come up much.

**Comment by svlandeg** [comment]
This will be fixed in v3.3 onwards :-)
