### ISSUE TITLE
Span.__richcomp__ issue

### ISSUE THREAD

**Issue by nrodnova** [explosion/spaCy#9696]
## How to reproduce the behaviour

When sorting Spans using just `sorted()` method and relying on `Span` to handle it, it sorts only on `Span.start` which makes spans that start with the same token to be in random order (or, rather, the original one). It doesn't look right to me.
Here's the code to demonstrate it

```python
import spacy
from random import Random
from spacy.matcher import Matcher
from spacy.tokens import Span

nlp = spacy.load("en_core_web_sm")

doc = nlp('0 1 2 3 4 5 6')
matcher = Matcher(nlp.vocab, validate=True)

matcher.add('4', [[{}, {}, {}, {}]])
matcher.add('2', [[{}, {}, ]])
matcher.add('1', [[{}, ]])

matches = matcher(doc)
spans = []
for match in matches:
    spans.append(Span(doc, match[1], match[2], nlp.vocab.strings[match[0]]))

Random(42).shuffle(spans)
spans = spans[:10] # Truncate a bit for readability
print("Sorted: [%s]" % "', '".join([x.text for x in sorted(spans)]))

expected = sorted(spans, key = lambda x : (x.start, x.end))
print("Expected: [%s]" % "', '".join([x.text for x in expected]))
```
The output of this fragment is:
```
Sorted: [0 1 2 3', '0 1', '1 2 3 4', '2 3', '3', '3 4 5 6', '3 4', '4', '5 6', '5]
Expected: [0 1', '0 1 2 3', '1 2 3 4', '2 3', '3', '3 4', '3 4 5 6', '4', '5', '5 6]
```
As you can see, in the first line there is no consistency, sometimes longer spans come first, and sometimes shorter.

I suggest to change `Span.__richcomp__` for '<, <=, >, >=' to the following:
(if you agree, I can make the change while I am on it)
```python
        # <
        if op == 0:
            return (self.c.start_char, self.c.end_char) < (other.c.start_char, other.c.end_char)
        # <=
        elif op == 1:
            return (self.c.start_char, self.c.end_char) <=  (other.c.start_char, other.c.end_char)

        ## Similar for > and >=
``` 
## Info about spaCy

- **spaCy version:** 3.0.6
- **Platform:** Darwin-20.3.0-x86_64-i386-64bit
- **Python version:** 3.7.9
- **Pipelines:** en_core_web_lg (3.0.0), en_core_web_md (3.0.0), en_core_web_sm (3.0.0)

**Comment by adrianeboyd** [comment]
This sounds fine. I think to be complete it would need to use the full set of attributes including label and kb_id, as in `==` and `!=`?
