### ISSUE TITLE
Spacy Matcher not working on long word combination

### ISSUE THREAD

**Issue by vladimircape** [explosion/spaCy#971]
I had text

```
text = "What factors is AdvisorShares STAR Global Buy-Write ETF exposed with?"
doc = nlp(text)
matcher(doc)
```

and add matcher by

`matcher.add(entity_key='company-1', label='COMPANY', attrs={}, specs=spec, on_match=merge_phrases)`

#[[{65: 'AdvisorShares'}, {65: 'STAR'}, {65: 'Global'}, {65: 'Buy-Write'}, {65: 'ETF'}], [{65: 'Advisorshares'}, {65: 'Star'}, {65: 'Global'}, {65: 'Buy-Write'}, {65: 'Etf'}]]

But system can't recognize  AdvisorShares STAR Global Buy-Write ETF as COMPANY type of entity

**Comment by vladimircape** [comment]
When i do it like these

spec1=[[{ORTH: 'AdvisorShares'}]]
matcher.add(entity_key='fund-1', label='FUND', attrs={}, specs=spec1)

It's working.
Also working 
spec1=[[{ORTH: 'AdvisorShares'}, {ORTH: 'STAR'}

it means when i added word by word, but when try to add all words in one time, not working
spec1=[[{ORTH: 'AdvisorShares'}, {ORTH: 'STAR'}, {ORTH: 'Global'}, {ORTH: 'Buy-Write'}, {ORTH: 'ETF'}]]

**Comment by vladimircape** [comment]
i also tried 
`matcher.get_entity('fund-1')`
and it's empty {}

**Comment by vladimircape** [comment]
The problem is that spacy doesn't understand words with dashes

> 'Buy-Write'

I also tried 
`{ORTH: 'Buy'}, {IS_PUNCT: True},{ORTH: 'Write'}`

but it's also not works

**Comment by Gregory-Howard** [comment]
Hi, see https://spacy.io/docs/usage/customizing-tokenizer for having some special cases for tokenization.
Not tested but something like this can do the job :   
```
nlp.tokenizer.add_special_case(u'Buy-Write',
    [
        {
            ORTH: u'Buy-Write',
            LEMMA: u'buy-write',
            POS: u'NOUN'},
       ])
```

**Comment by vladimircape** [comment]
@Gregory-Howard  It's working. But it has one minus , you should already know such words, should have a list of such words, if you have 100 such words,  and for Example i have companies like "Pharma K-1" and i think it's can be problems with K-1

**Comment by Gregory-Howard** [comment]
Actually there is such a list in french https://github.com/explosion/spaCy/blob/master/spacy/fr/_tokenizer_exceptions_list.py
But I don't see any in English.
