### ISSUE TITLE
Example.get_aligned_parse  can return multiple dependency labels for a single token

### ISSUE THREAD

**Issue by pb-jeff-oneill** [explosion/spaCy#9710]
The documentation for `Example.get_aligned_parse` is here:
    https://spacy.io/api/example#get_aligned_parse

With the default option of `projectivize=True`, `get_aligned_parse` can return multiple dependency labels for a single token like this:
> relcl||nsubjpass

I think most people would assume that you would get a single valid dependency label for each token.  This causes much extra debugging work and headaches down the road.

Seems worth mentioning in the documentation!

**Comment by adrianeboyd** [comment]
This kind of dependency label is the expected output for the pseudo-projective dependency parsing algorithm (Nivre and Nilsson, 2005) cited in the method description for `projectivize=True`. To be more specific, this method uses the "Head" decoration scheme. This is only an internal representation used within the parser, which converts it back to non-projective trees containing only the original labels for the final `Doc` annotation.

The idea is that the pseudo-projective version can be converted back to the original non-projective dependency tree in nearly all cases. If you strip the label after the `||` separator, you could have a dependency tree that's projective and that contains the same labels as in the original tree, but that can't be converted back to the original tree.

There are no built-in options for other projectivization algorithms in spacy, but as long as you end up with projective trees, you can preprocess your data however you'd like before training the parser.

**Comment by adrianeboyd** [comment]
Let me move this to the discussion board...
