### ISSUE TITLE
Chinese model

### ISSUE THREAD

**Issue by Harryhaha** [explosion/spaCy#972]
Just wondering Chinese model is being built ? I saw from somewhere that spacy would use jieba tokenization, which means all of other tasks such as POS, NER, parsing, vector would be available by using spacy ? Thanks !

## Your Environment

* spaCy Version Used: 1.7.3

**Comment by kenchengch** [comment]
Same question.

**Comment by ines** [comment]
spaCy currently only supports Chinese tokenization using jieba. We haven't trained a language model ourselves yet, but we're definitely planning to do so in the future. From the discussion I've seen online, it looks like some users have also started training their own models.

With the current setup, you should be able to tokenize Chinese text:

```python
from spacy.zh import Chinese
nlp = Chinese()
doc = nlp(u'雷猴回归人间。')
# sorry if this text is bad, I don't speak Chinese, so I just used a jieba example 😉
```

You can then build the vocabulary to train your own model (spaCy 1.7.5 also comes with a [`model` command](https://spacy.io/docs/usage/cli#model) to help you with that). For more info on this, see the [documentation on adding languages](https://spacy.io/docs/usage/adding-languages#vocabulary). The training docs aren't very detailed at the moment, sorry – but we're definitely working on that!

**Comment by Harryhaha** [comment]
Thanks ! That would be really great for anyone who need to deal with Chinese ! If possible, I would also try to train the model.
