### ISSUE TITLE
Adapt Morphology to other Languages (e.g. German)

### ISSUE THREAD

**Issue by schlichtanders** [explosion/spaCy#974]
The current implementation ``morphology.lemmatize`` is implicitly hard-coded to support English. At https://github.com/explosion/spaCy/blob/master/spacy/morphology.pyx#L145
```
if univ_pos not in (NOUN, VERB, ADJ, PUNCT):
            return self.strings[py_string.lower()]
```
``AUX`` and maybe more POS tags are missing for German language for instance. Maybe there are also more things which are currently English-specific.

[I stumbled about this because I am currently trying to implement basic German lemmatizer]

## Your Environment

* Operating System: Windows 10, 64bit
* Python Version Used: 3.6
* spaCy Version Used: 1.7.5
* Environment Information:

**Comment by schlichtanders** [comment]
the textblob_de implementation of lemmatization (also mentioned at #390)
https://github.com/markuskiller/textblob-de/blob/dev/textblob_de/ext/_pattern/text/de/__init__.py#L186-L199
```
def find_lemmata(tokens):
    """ Annotates the tokens with lemmata for plural nouns and conjugated verbs,
        where each token is a [word, part-of-speech] list.
    """
    for token in tokens:
        word, pos, lemma = token[0], token[1], token[0]
        if pos.startswith(("DT", "JJ")):
            lemma = predicative(word)  
        if pos == "NNS":
            lemma = singularize(word)
        if pos.startswith(("VB", "MD")):
            lemma = conjugate(word, INFINITIVE) or word
        token.append(lemma.lower())
    return tokens
```

clearly shows that access to more detailed tags is demanded. Why not giving access to ``pos``/``pos_`` and ``tag``/``tag_``?

My overall intuition would be that the Lemmatizer deserves its own pipeline component. (This is the place where I initially expected to find spacy's Lemmatizer definition, however was suprised that it is somewhat nested within morphology, which is part of vocab, which is part of almost everything else)

Any suggestions?

**Comment by Liebeck** [comment]
Crosspost: https://github.com/explosion/spaCy/issues/390#issuecomment-293379811

**Comment by ines** [comment]
Closing this one to make #846 the "master issue"!
