### ISSUE TITLE
Spacy Matcher not recognize

### ISSUE THREAD

**Issue by vladimircape** [explosion/spaCy#976]
I have such name

> Morningstar Lifetime Gr 2015 Index N-1

here is my matcher add

`matcher.add(entity_key=type_entity.lower()+'-'+str(i), label=type_entity, attrs={}, specs=spec, on_match=merge_phrases)`

and my spec for such name

```
[{settings.ORTH: 'Morningstar'}, {settings.ORTH: 'Lifetime'}, {settings.ORTH: 'Gr'},
                      {settings.IS_DIGIT: True}, {settings.ORTH: 'Index'}, {settings.ORTH: 'N'},
                      {settings.IS_PUNCT: True}, {settings.IS_DIGIT: True}]
```

**Comment by ines** [comment]
The new version v2.0 comes with several improvements to the `Matcher`, including a `PhraseMatcher` for large terminology lists. So you can try your example again using the new version:
* Usage guide with examples: https://spacy.io/usage/linguistic-features#section-rule-based-matching
* Matcher changes in v2.0: https://spacy.io/usage/v2#migrating-matcher

When adding token patterns, always make sure to check them against spaCy's tokenization first, to make sure your pattern reflects that. If spaCy doesn't split your text the way you expect it to, your pattern won't match. So the solution is to either adjust your pattern, or [customise spaCy's tokenizer](https://spacy.io/usage/linguistic-features#special-cases).
