### ISSUE TITLE
Packaging EntityRuler and adding it to another pipeline

### ISSUE THREAD

**Issue by woutrbe** [explosion/spaCy#9766]
I suppose this is largely because I'm fairly new to spaCy and NLP in general. But the documentation regarding "Rule-based Matching" is incredibly confusing to me. For example; I'm reading the documentation on how to use the entity ruler, and the first example shows how to add different patterns, by using `nlp = English()`. The documentation then goes on about how the order is important, and how setting `overwrite_ents=True` will overwrite overlapping entities. The next code example, shows the same code as the previous one, but is now using `nlp = spacy.load("en_core_web_sm")`

It's not clear as to why first it's using `English()`, and the second time it's using `spacy.load("en_core_web_sm")`. I assume it has to do with the order of the pipelines, but it's not very clear.

A second thing I've found confusing, is that there's really no information on how to actually build and package your own models. When searching around, all the examples I've found are fairly similar, but none actually show how to build a real project.

For example; I want to build a custom entity ruler, based on a dictionary of words I have. How should I go about that? Do I create a blank spaCy object, and add "entity_ruler" as a pipe? How do I then add this model to another pipeline that loads "en_core_web_lg".
What do I do if I want to combine this with a text classifier, how do I integrate my entity_ruler so that it helps the classifier?

Again, this is all probably due to my lack of understanding of NLP. But I've been looking at this for a week or two now, and I just can't get past the basic examples and get a sense of how I actually go about building something with it.

## Which page or section is this issue related to?
https://spacy.io/usage/rule-based-matching#entityruler

**Comment by polm** [comment]
Sorry you've been having trouble with this.

Since this is a question rather than a bug report, I'm going to move it to Discussions - you should see a link to the Discussion.
