### ISSUE TITLE
projects rel_component hangs with transformer model

### ISSUE THREAD

**Issue by AlDante** [explosion/spaCy#9790]
## How to reproduce the behaviour

sudo pip install spacy thinc thinc_gpu_ops
python -m spacy project clone tutorials/rel_component
cd rel_component
spacy project run all_gpu

## Your Environment

* Operating System:
* Python Version Used:
* spaCy Version Used:
* Environment Information:
* ## Info about spaCy

- **spaCy version:** 3.2.0
- **Platform:** Linux-5.4.0-89-generic-x86_64-with-debian-bullseye-sid
- **Python version:** 3.7.12

GCP platform , K80

Running the example with  spacy project run train_cpu  - no problems.

spacy project run train_gpu hangs after an indeterminate number of epochs. 

Is there a log I can look at to find out why it is hanging?

**Comment by polm** [comment]
Thanks for the report, that does sound weird. I was unable to reproduce this locally, so it may be something particular to GCP.

The train command has a `--verbose` option, though I'm not sure it will add much here. Another option, though It's not precise, is that if you kill the job when it hangs Python should give a stack trace of the code it was killed in, which may give a hint about what the issue is.

**Comment by AlDante** [comment]
Hi Paul, 
thanks, I'll try the verbose option and see where I get. I'm wondering if the batch size might be too big for the K80 - any idea where I should change that? There seem to be two config files, one in rel_component/configs/rel_trf.cfg and one in rel_component/training/config.cfg. The latter seems to be a generated file, though.

**Comment by polm** [comment]
You can read about batch sizes [here](https://github.com/explosion/spaCy/discussions/9451#discussioncomment-1493576). 

The config in `training/` is presumably the copy generated to be included with the output model - it's not read as input. It should be be in `training/model-best` or `training/model-last` and not directly under `training` though.

**Comment by polm** [comment]
Let us know if tweaking the batch size helped. It would also be helpful to see a stack trace from when you kill the job while it's hung, to give us a hint about where it's busy.

One thing that is another possibility is that if there is some kind of loop in the annotations that could be a problem. However I don't think there's any way to do that with the relation extraction component.
