### ISSUE TITLE
Depending on a model's name in config `spacy debug data` behaves differently

### ISSUE THREAD

**Issue by tomateit** [explosion/spaCy#9794]
## How to reproduce the behavior
I have two identical config files with `transformer+ner` pipelines. If my NER component (not custom, absolutely tutorial rip-off) is called `entity_recognizer` (or anything else, I checked) and not `ner`, running `spacy debug data` with respective parameters produces different results on the same data:
+ For the case of `entity_recognizer` I get :
```
========================== Named Entity Recognition ==========================
ℹ 0 label(s)
0 missing value(s) (tokens with '-' label)
✔ Good amount of examples for all labels
✔ Examples without occurrences available for all labels
✔ No entities consisting of or starting/ending with whitespace
```
+ And when I rename the component to `ner`:
```
========================== Named Entity Recognition ==========================
ℹ 3 label(s)
0 missing value(s) (tokens with '-' label)
✔ Good amount of examples for all labels
✔ Examples without occurrences available for all labels
✔ No entities consisting of or starting/ending with whitespace
```
Goddamn, I had spent hours of debugging with this debug command until I realized, that my data is OK and I do not have 0 labels. 
## Your Environment
* Operating System: Ubuntu 20.04
* Python Version Used: 3.8
* spaCy Version Used: spacy 3.2

**Comment by adrianeboyd** [comment]
Thanks for the report, that does look like a bug! The messages about having a good amount of examples in both outputs should be correct, since this is looking at `doc.ents` and not the pipeline config, but there's clearly a bug in code that looks up the labels by component name.

**Comment by aserputov** [comment]
Hello, @adrianeboyd @tomateit  I want to work on this issue. Could you please assign me?

**Comment by adrianeboyd** [comment]
Hi, we don't usually formally assign people to issues here. You can open a PR (as a draft if it's not finalized) and link it to this issue by using the "fixes" keyword in the description, so a note will show up here automatically about the PR.
