### ISSUE TITLE
spaCy lookups data does not support spaCy 3.2.0

### ISSUE THREAD

**Issue by graue70** [explosion/spaCy#9801]
[spaCy lookups data](https://github.com/explosion/spacy-lookups-data/blob/7132b76f3c088e7d3c8298ede4705c0efb58ae87/requirements.txt#L1) does not support spaCy 3.2.0. I suppose that this is a mistake?

**Comment by adrianeboyd** [comment]
Those requirements are just for testing/CI purposes. The real install requirements are in `setup.cfg` and it only require `setuptools`.
