### ISSUE TITLE
Wrong answer displayed in displacy

### ISSUE THREAD

**Issue by jawahar273** [explosion/spaCy#984]
## Environment

* displacy

The sample sentence used was "Janine is a professor "
for this sentence **Spacy** should display as **Person** but it shows as **ORG**

**Comment by jawahar273** [comment]
Follow this link to know what I am saying [link] (https://demos.explosion.ai/displacy-ent/?text=Janine%20is%20a%20professor%20&ents=person%2Cnorp%2Cfacility%2Corg%2Cgpe%2Cloc%2Cproduct%2Cevent%2Cwork_of_art%2Clanguage%2Cdate%2Ctime%2Cpercent%2Cmoney%2Cquantity%2Cordinal&model=en)

**Comment by honnibal** [comment]
The entity recognition isn't always correct -- unfortunately this is expected behaviour. We'll continue to produce better models to improve accuracy, but on any given sentence, it may still make surprising errors.
