### ISSUE TITLE
Suggested documentation improvement: ENT_IOB in DependencyMatcher

### ISSUE THREAD

**Issue by JohnBurant** [explosion/spaCy#9851]
I have discovered that the following works as a pattern to add to a DependencyMatcher object:

pattern = [
    {'LEFT_ID': 'is_verb_lemma_pay',
     'REL_OP': '.*',
     'RIGHT_ID': 'is_cause',
     'RIGHT_ATTRS': {'ENT_TYPE': 'CAUSE', 'DEP': 'pobj', 'ENT_IOB': 3}
}]

You wouldn't know this from the documentation. The docs for DependencyMatcher refer to Matcher regarding attributes (albeit with a statement about form only not about which attributes are allowable), and Matcher itself doesn't allow ENT_IOB. Moreover, the format declaring other attributes to match on uses the non-underscore attribute name at the dict key but matches to the string value associated with the underscore version, e.g. {'POS': some_string} where the usage above matches the integer for ENT_IOB not the string associated with ENT_IOB_.

So add this? Would have saved me a bit of time... :-)

**Comment by adrianeboyd** [comment]
Yes, sorry, this is really unclear from the docs, but we're not sure it makes sense to expect users to use the 0-3 values. We have an open PR that we hope to merge soon that will support `"B"/"I"/"O"` correctly for this attribute: #9649

**Comment by JohnBurant** [comment]
The "B"/"I"/"O" option makes more sense. Great!
