### ISSUE TITLE
Wrong lemma in parsed text

### ISSUE THREAD

**Issue by gRURgR** [explosion/spaCy#9853]
Version: spaCy 3.2.
The lemma for the word "substantially" is "you" for some reason:
```
>>> import spacy
>>> nlp = spacy.load("en_core_web_lg")
>>> doc=nlp("The opportunity may not be huge for us but they can and will do substantially all of it on their own.")
>>> ' '.join(T.text for T in doc)
'The opportunity may not be huge for us but they can and will do substantially all of it on their own .'
>>> ' '.join(T.lemma_ for T in doc)
'the opportunity may not be huge for we but they can and will do you all of it on their own .'

```

**Comment by adrianeboyd** [comment]
Thanks for the report! Wow, that is one harmless-looking rule in the attribute ruler gone terribly wrong.

It's trying to match `y'` in `y'all` or `yall` to produce the lemma `you`, but it ends up matching the end of "substantially" followed by "all". You can update this rule in the attribute ruler, and we'll fix it in the next release of the models.

This is the original rule:

```
    "patterns":[
      [
        {
          "LOWER": {"REGEX": "y'?"}
        },
        {
          "LOWER":"all"
        }
      ]
    ],
    "attrs":{
      "LEMMA":"you"
    },
    "index":0
  }
```

I think the regex just needs to be limited with `"^y'?"` instead.
