### ISSUE TITLE
Broken link from Universal Dependencies Blogpost

### ISSUE THREAD

**Issue by koaning** [explosion/spaCy#9863]
The part in the blogpost [here](https://explosion.ai/blog/ud-benchmarks-v3-2)

> The core syntactic annotation is performed by built-in spaCy components:
>
> XPOS: Tagger
> UPOS+UFeats: Morphologizer
> Head+Deprel+Sentences: [Parser](https://spacy.io/api/parser)
> Sentences (optional, alternative to parser): [Senter](https://spacy.io/api/senter)

Shows a link to the "senter" docs, but it doesn't seem to exist. Same with "parser".

**Comment by adrianeboyd** [comment]
Thanks for the note, should be updated now!

**Comment by koaning** [comment]
Just tried it on my phone and the link still seems broken 🙁

**Comment by adrianeboyd** [comment]
After a hard refresh it seems fine on my end?

**Comment by koaning** [comment]
d0h! I checked the url in this issue as opposed to the one in the blog. My bad! 

Link looks all good now, thanks 🙂
