### ISSUE TITLE
double free or corruption (out)

### ISSUE THREAD

**Issue by doguaraci** [explosion/spaCy#9866]
## How to reproduce the behaviour
Running this:
```bash
python -m spacy train config.cfg --output ./output --gpu-id 0
```
I get the following error:
```
============================= Training pipeline =============================
ℹ Pipeline: ['transformer', 'ner']
ℹ Initial learn rate: 0.0
E    #       LOSS TRANS...  LOSS NER  ENTS_F  ENTS_P  ENTS_R  SCORE 
---  ------  -------------  --------  ------  ------  ------  ------
  0       0        2036.49    827.69    0.30    0.29    0.31    0.00
  1     200      108110.27  119169.13   64.93   67.73   62.36    0.65
double free or corruption (out)
Aborted (core dumped)
```

## Your Environment
- **spaCy version:** 3.2.1
- **Platform:** Linux-5.4.0-1059-aws-x86_64-with-debian-buster-sid
- **Python version:** 3.7.12

**Comment by adrianeboyd** [comment]
This kind of error is particularly hard to debug, especially from a distance. To test, can you try using a different version of pytorch?

**Comment by svlandeg** [comment]
I'm also wondering whether you can replicate this consistently on your system, or was it like a one-time error?

**Comment by doguaraci** [comment]
I tried multiple things, like rebooting, reinstalling the environment, using a previous version of SpaCy. The error persisted. Then I tried using a machine with higher ram, and the error disappeared.

**Comment by polm** [comment]
Unfortunately without more information I don't think there's any way for us to investigate this, so I'm going to close this for now. If you (or someone else) sees this again we can reopen this issue or open a new issue that refers to this for further investigation. Thanks again for reporting!
