### ISSUE TITLE
ValueError: [E873] Unable to merge a span from doc.spans with key 'sc'

### ISSUE THREAD

**Issue by Onyoursix** [explosion/spaCy#9871]
## How to reproduce the behaviour

I am receiving the error: 
ValueError: [E873] Unable to merge a span from doc.spans with key 'sc' and text 'Chairman Woffinden Aye'. This is likely a bug in spaCy, so feel free to open an issue: https://github.com/explosion/spaCy/issues

I first received this error using multi-threading, I tried switching over to GPU and received it as well. I don't entirely understand how to troubleshoot this error. I'm receiving this error on Google Colab.

`doc = Doc.from_docs(list(nlp.pipe(d, n_process=4)), ensure_whitespace=True)`

or via GPU

`doc = Doc.from_docs(list(nlp.pipe(d)), ensure_whitespace=True)`

## Your Environment

Google Colab

## Info about spaCy

- **spaCy version:** 3.2.1
- **Platform:** Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
- **Python version:** 3.7.12

**Comment by svlandeg** [comment]
Thanks for the report! That does feel like a bug - we'll look into it.

**Comment by adrianeboyd** [comment]
Yes, this is probably a bug in `Doc.from_docs`, but it's going to be tricky for us to reproduce without more details. Does it work correctly without multithreading? (My initial guess is that it's more likely that it's not related to multithreading, but instead a bug in how whitespace is adjusted for data `doc.spans`.)

Is there any chance you could share your annotated docs privately by email to adriane@explosion.ai? (Just a `DocBin` of the docs from `nlp.pipe(d)`.)

**Comment by adrianeboyd** [comment]
This took a bit to track down (thanks for sharing the data!) and it is a bug in `Doc.from_docs` when there is a sequence of docs with a doc that ends in a whitespace token followed by an empty doc. I can reproduce it with or without `ensure_whitespace` enabled, so I think it's mainly related to the empty doc. Now to look into a fix...

**Comment by adrianeboyd** [comment]
Ah, I was confused about the default for `ensure_whitespace`, so it is just related to `ensure_whitespace=True`.

**Comment by Onyoursix** [comment]
Hi Adriane, thanks for looking into it! If I understand correctly,
ensure_whitespace adds a space on to the end of a doc if it doesn't have
one. As a workaround, I've just been making sure there is a space at the
end of each doc before I process it in the pipeline and I set
ensure_whitespace=False. It's strange that the document that I sent you was
the first one that gave me an issue since I ran about 5,000+ docs through
that with no issue before. It could also be a total coincidence, but there
was a line in the preprocessing function that when disabled, gave no error
on that document with ensure_whitespace=True. I put a comment next to that
line, not sure if that has something to do with it or not.

Kind regards,

Ben

**Comment by adrianeboyd** [comment]
Adding your own whitespace and using `ensure_whitespace=False` is fine, although I think the simplest workaround for your existing script with v3.2.1 is to skip empty texts if there are any after the preprocessing steps. I didn't look at it in detail, but I suspect that the preprocessing changed the number/position of empty docs somehow.

**Comment by Onyoursix** [comment]
Good idea, I'll do that instead. I appreciate you looking into this!
