### ISSUE TITLE
spacy.cli.train train() got an unexpected keyword argument 'overrides'

### ISSUE THREAD

**Issue by info2000** [explosion/spaCy#9872]
on spacy.cli.train using transformer return _TypeError: train() got an unexpected keyword argument 'overrides'_

`from spacy.cli.train import train

train("./config-ES-trf_Exclusive.cfg",
      "./modelos/" , 
      use_gpu=0, 
overrides={"paths.train": "./googleCatTier1/train_3100_lg.spacy", "paths.dev": "./_test_3100_lg.spacy"}      
      )`

spaCy version    3.2.1                         
Location         /usr/local/lib/python3.7/dist-packages/spacy
Platform         Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
Python version   3.7.12                        
Pipelines        es_dep_news_trf (3.2.0)  
gpu enabled 
Running on collab

**using this configuration on same colab, work well**
spaCy version    3.2.1                         
Location         /usr/local/lib/python3.7/dist-packages/spacy
Platform         Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
Python version   3.7.12                        
Pipelines        es_core_news_lg (3.2.0)  

if run the command line in collab
`!python -m spacy train .... with the same params `
and next run the train method from code, them works well

**Comment by adrianeboyd** [comment]
Hi, `overrides` was added in v3.1.4 when the internal train CLI functions were refactored a little to make it easier to call them programmatically (#9398). Are you sure you have v3.2.1 in both environments?
