### ISSUE TITLE
Dealing with italian elision when finding stop-words

### ISSUE THREAD

**Issue by nicolafan** [explosion/spaCy#9877]
Italian elision is the process of putting an apostrophe for replacing a vowel at the end of a word that comes before another word which starts with a vowel (or 'h'). It is very frequent and it happens especially with DETs and PRONs. Some of these forms are actually present in the list of italian stop-words, but they are never practically matched since they don't end with the apostrophe in `it/stop_words.py`.

For example:
`it/stop_words.py` contains `quest`, `lo`, `un`, `dell`, `dall`, `quello`, `si`.
But we get:
```python
import spacy
nlp_it = spacy.load('it_core_news_lg')
doc_it = nlp_it("Quest'uomo. L'ho visto. Un'amica. Dell'olio. Dall'amico. Quell'incontro. S'arrende")
for token in doc_it:
    print(token.text, token.is_stop)

---------------------------------------------------------------------------------------------------------------------------------

Quest' False
uomo True
. False
L' False
ho True
visto True
. False
Un' False
amica False
. False
Dell' False
olio False
. False
Dall' False
amico False
. False
Quell' False
incontro False
. False
S' False
arrende False
```

The first word of each sentence should be a stop-word.
Also there are some important missing stop-words in the list: (i.e. `è : is`, `e : and`).

## Possible fixes

Adding these apostrophed forms to `it/stop_words.py` or dropping final apostrophes from italian words before checking if they are stop-words.

Thank you!

## Info about spaCy

- **spaCy version:** 3.2.1
- **Platform:** Linux-5.11.0-40-generic-x86_64-with-glibc2.29
- **Python version:** 3.8.10
- **Pipelines:** it_core_news_lg (3.2.0), en_core_web_lg (3.2.0)

**Comment by DuyguA** [comment]
Thanks for reporting! I can definitely the see the issue here. 

Apostrophe is a part of these sort of short forms, hence we don't strip the apostophe. 

I made this PR: https://github.com/explosion/spaCy/pull/9878  and added the most common forms. This is the diff: https://github.com/explosion/spaCy/pull/9878/files
