### ISSUE TITLE
Second noun chunk contains first one.

### ISSUE THREAD

**Issue by D1Doris** [explosion/spaCy#988]
For one sentence, the chunker returns a strange noun chunk:

>>> import spacy
>>> nlp = spacy.load('en')
>>> doc = nlp(unicode('Does flight number three fifty-four require a connecting flight to get to Boston?'))
>>> for np in doc.noun_chunks:
...     print np
...
flight number
Does flight number three fifty-four require
a connecting flight
Boston
>>> exit()

"Does flight number three fifty-four require" shouldn't be there.

My Environment:

* **Python version:** 2.7.6
* **Platform:** Linux-3.4.0+-x86_64-with-Ubuntu-14.04-trusty
* **spaCy version:** 1.7.5
* **Installed models:** en

Out of the 3000 sentences I've parsed, about 130 experience this problem.

**Comment by honnibal** [comment]
Thanks, this is a regression introduced in a recent patch. Will be fixed in next release.
