### ISSUE TITLE
wrong entity identification with train_new_entity_type.py example

### ISSUE THREAD

**Issue by irfan-zoefit** [explosion/spaCy#989]
I've run the example multiple times to train the new entity but got wrong identification every time. Here is the output of the train_new_entity_type.py
model name is **en**

1st time

`DATE you like horses`
`DATE you like horses`

2nd time

`LOC horses`
`LOC horses`

3rd time

`DATE you like horses`
`DATE you like horses`

4th time

`LOC horses`
`LOC horses`

## Info about spaCy
* **spaCy version:** 1.8.0
* **Installed models:** en
* **Python version:** 3.5.1+
* **Platform:** Linux-4.4.0-72-generic-x86_64-with-Ubuntu-16.04-xenial

**Comment by irfan-zoefit** [comment]
There are some issues with coding convention in this example. Function `train_ner` does not return anything.

`ner = train_ner(nlp, train_data, output_directory)`

Also, `EntityRecognizer` is not being used anywhere in the example. What if I also want to update the NER model?

**Comment by honnibal** [comment]
Could you try now? Just pushed some fixes.

I'm not sure why it's not labelling correctly, though. It works for me.

**Comment by irfan-zoefit** [comment]
Still not working for me.
```shell
python train_new_entity_type.py 'en' 'entity'
Loading initial model en
DATE you like horses
Loading from entity
DATE you like horses
```

I think it's English model issue.

**Comment by irfan-zoefit** [comment]
Which model are you using? I'm using `en_core_web_sm`

**Comment by honnibal** [comment]
I'm also using that...

Could you try just adding a bunch more iterations to the training, and check that it learns it after that?

**Comment by irfan-zoefit** [comment]
It's working now, I have added few more training examples and changed the iterations. Thanks!!!
