### ISSUE TITLE
Bug in Span Underscore extensions

### ISSUE THREAD

**Issue by ezorita** [explosion/spaCy#9931]
## How to reproduce the behaviour
```Python
import spacy
from spacy.tokens.span import Span

Span.set_extension("id", default=-1)

nlp = spacy.load("en_core_web_lg")
doc = nlp("Reproduces with any text")
s1 = Span(doc, 0, 2)
s1._.id = 10
s2 = Span(doc, 0, 2)
s2._.id = 12

print(s1._.id)
> 12
```

Only happens when the span `start` and `end` are the same (reproduces for any range). Also happens if different `label` values are assigned to each `Span`.

## Your Environment

- **spaCy version:** 3.2.1
- **Platform:** Linux-5.11.0-41-generic-x86_64-with-glibc2.29
- **Python version:** 3.8.10
- **Pipelines:** en_core_web_lg (3.2.0), en_core_web_trf (3.2.0)

**Comment by ezorita** [comment]
Just saw this has already been reported. Sorry for duplicating.

**Comment by polm** [comment]
Just to be clear, this is not a bug, but a result of the design of Spans. Extension data is always stored in the Doc, and Spans are just views on that.

**Comment by polm** [comment]
Also the related issue is #9887.
