### ISSUE TITLE
pipenv run python -m spacy download en_core_web_sm fills up cache

### ISSUE THREAD

**Issue by lsmith77** [explosion/spaCy#9933]
## How to reproduce the behaviour
Run the following commands several times and check the size of the `pip/http` dir after each time:
```
pipenv run python -m spacy download en_core_web_sm
```

## Your Environment

* Operating System: OSX and Linux
* Python Version Used: 3.9
* spaCy Version Used: 3.2.0
* Environment Information:

```
➜  nlp_api git:(dev) ✗ du -sh /Users/lsmith/Library/Caches/pip/http
450M	/Users/lsmith/Library/Caches/pip/http
➜  nlp_api git:(dev) ✗
pipenv run python3.9 -m spacy download en_core_web_sm
pipenv run python3.9 -m spacy download de_core_news_sm
Loading .env environment variables...
Collecting en-core-web-sm==3.2.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.2.0/en_core_web_sm-3.2.0-py3-none-any.whl (13.9 MB)
     |████████████████████████████████| 13.9 MB 7.5 MB/s

..
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
Loading .env environment variables...
Collecting de-core-news-sm==3.2.0
  Using cached https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-3.2.0/de_core_news_sm-3.2.0-py3-none-any.whl (19.1 MB)
...
✔ Download and installation successful
You can now load the package via spacy.load('de_core_news_sm')
➜  nlp_api git:(dev) ✗ du -sh /Users/lsmith/Library/Caches/pip/http
463M	/Users/lsmith/Library/Caches/pip/http
```

Each time I run the command the cache size increases by another 13M.

I guess though that this is likely rather an issue with pip or Pipenv but as this installation method is recommended on the Spacy docs, I raised the issue here first.

**Comment by polm** [comment]
Can't reproduce this using vanilla pip on Linux. 

Does this happen only with the spaCy model? While it's possible there's something special about it, I suspect this is (like you said) a pip or pipenv issue and out of our hands. 

As a workaround, you can periodically run `pip cache purge` or pass `--no-cache-dir` after the model name.
