### ISSUE TITLE
Inconsistent behavior of is_punct and tag?

### ISSUE THREAD

**Issue by f11r** [explosion/spaCy#998]
At the moment spacy sometimes sets `token.is_punct=True` and `token.tag_=NN` (or other tags, like CARD/NUM). I'm not entirely certain whether I think this behavior should be changed (and what it should do) but I do think there should be a conscious decision on whether this should be expected.

## Example:
~~~python
import spacy
nlp_de = spacy.load('de_core_news_md')
for tok in nlp_de('Dies ist ein -- Test'):
    print(tok, tok.is_punct, tok.tag_)
~~~
Output:
~~~
Dies False PDS
ist False VAFIN
ein False ART
-- True NN
Test False NN
~~~

## Your Environment

* Python Version Used: 3.6.0
* spaCy Version Used: 1.8.0 (de_core_news_md)

**Comment by honnibal** [comment]
Thanks for the report. Interesting observation.

The `is_punct` attribute is context-independent --- it's attached to the lexical entry in the vocab. The POS tag is calculated statistically. You'd think the tagger would "see" that the tagging was impossible, which makes me wonder whether the German training data lacks some punctuation diversity. If so we need to do some data augmentation.

**Comment by oroszgy** [comment]
Just an idea: I've seen (en/hu) treebanks tagging (book, movie, etc.) titles as nouns. My guess would be that something similar could go wrong here as well.
