### ISSUE TITLE
Trained NER models are not loadable

### ISSUE THREAD

**Issue by YanhaoYang** [explosion/spaCy#999]
I use some trained NER models to recognise entity names in some specific domains. After upgrading to v1.8.0, I found those models could not be loaded.

It is easy to reproduce the problem by add following code to the official example, https://github.com/explosion/spaCy/blob/master/examples/training/train_ner.py#L87:

```python
    model_path = Path('./ner')
    ner2 = EntityRecognizer.load(model_path, nlp.vocab)
    doc = nlp.make_doc('Who is Shaka Khan?')
    nlp.tagger(doc)
    ner2(doc)
    for word in doc:
        print(word.text, word.orth, word.lower, word.tag_, word.ent_type_, word.ent_iob)
```
This will result in following error message:
```
Traceback (most recent call last):
  File "train_ner.py", line 104, in <module>
    main('ner')
  File "train_ner.py", line 94, in main
    ner2 = EntityRecognizer.load(model_path, nlp.vocab)
  File "spacy/syntax/parser.pyx", line 149, in spacy.syntax.parser.Parser.load (spacy/syntax/parser.cpp:6845)
KeyError: 'actions'
```

It seems `ner.cfg["actions"]` is not necessary for NER training, but the loading code will read it anyway.

## Info about spaCy

* **spaCy version:** 1.8.0
* **Platform:** Linux-4.10.0-19-generic-x86_64-with-debian-8.7
* **Python version:** 3.6.1
* **Installed models:** en

**Comment by ines** [comment]
Closing this and making #1046 the master issue. Work in progress for spaCy v2.0!

**Comment by lukewendling** [comment]
Anyone found a workaround to load trained NER models in spacy <2.0 ?
