### ISSUE TITLE
Different NER results on Linux/Mac and Windows with it-core-news-lg-3.2.0

### ISSUE THREAD

**Issue by martin-ludvik-sv** [explosion/spaCy#9990]
## How to reproduce the behaviour

Spacy NER with model  it-core-news-lg-3.2.0 (actually, most probably all italian 3.2.0 models) produces invalid results, with some entities "-" on Linux/Mac environment. The same model on Windows 10 does not produce results with entities "-". 

**Example**
```
import spacy

text = """Non si placa la grave situazione in cui versa la cardiologia dell'ospedale San Francesco di Nuoro. Anzi, dopo gli ultimi avvenimenti, i problemi sono destinati ad aumentare pericolosamente, con il reparto che rischia la.... Non si placa la grave situazione in cui versa la cardiologia dell'ospedale San Francesco di Nuoro. Anzi, dopo gli ultimi avvenimenti, i problemi sono destinati ad aumentare pericolosamente, con il reparto che rischia la chiusura. A ribadire allarme è Roberto Deriu, consigliere regionale del Partito Democratico, primo firmatario di un'interrogazione presentata in queste ore alla Regione. "L'ospedale San Francesco di Nuoro si trova in gravissima difficoltà, soprattutto per quanto riguarda la mancata copertura del fabbisogno necessario di medici cardiologi all'interno del reparto, oltreché di emodinamisti indispensabili per la cura dei pazienti", denuncia Deriu. Problemi già posti all'attenzione del Presidente della Regione e dell'assessore alla sanità con due interrogazioni presentate nei mesi scorsi dallo stesso Deriu e dai consiglieri del Centrosinistra. "Abbiamo evidenziato per tempo la carenza di medici all'ospedale San Francesco di Nuoro – precisa il dem – ma finora non abbiamo ottenuto alcuna risposta e la situazione è destinata a peggiorare". Risulta infatti imminente un ulteriore ridimensionamento della pianta organica del servizio di cardiologia del San Francesco – già sotto di cinque unità rispetto al fabbisogno necessario – con altri sette medici cardiologi che lasceranno presto il reparto. "La cardiologia avrà dunque dodici medici in meno rispetto al necessario – precisa il consigliere dem –, ma nonostante tutto non è stato previsto alcun cambio compensativo dei cardiologi in uscita dal San Francesco". Una situazione, secondo l'esponente del Pd, che "conferma lo smantellamento della sanità a Nuoro, con gravi ripercussioni per la salute dei cittadini e per quella dei medici, costretti a turnazioni e carichi di lavoro sempre più pressanti. E questo è inaccettabile". "Ritengo doveroso – conclude Roberto Deriu – che la Regione si occupi urgentemente di questo grave problema, al fine di evitare la chiusura del reparto di cardiologia del San Francesco, presidio sanitario principale del centro Sardegna, punto di riferimento per tutta la popolazione dei territori interni dell'isola. Non c'è più tempo da perdere". L'articolo Cardiologia del San Francesco a rischio chiusura proviene da Cronache Nuoresi .."""

nlp = spacy.load("it_core_news_lg")
doc = nlp(text)
for ent in doc.ents:
    print(ent.label_, ent.text)
```
**Result on Linux/Mac:**
PER San Francesco di
PER San Francesco di
PER Roberto Deriu
ORG Partito Democratico
LOC Regione
PER San Francesco di
LOC Nuoro
MISC Deriu
LOC Presidente della Regione
MISC Deriu
LOC Centrosinistra
PER San Francesco di
ORG dem –
PER San Francesco –
LOC –
MISC – precisa il consigliere
PER –
PER San Francesco
ORG Pd
LOC Nuoro
PER –
PER Roberto Deriu –
LOC Regione
PER San Francesco
LOC Sardegna
MISC Cardiologia del San Francesco
MISC Cronache Nuoresi ..

**Result on Windows:**
PER San Francesco di
PER San Francesco di
PER Roberto Deriu
ORG Partito Democratico
LOC Regione
PER San Francesco di
LOC Nuoro
MISC Deriu
LOC Presidente della Regione
MISC Deriu
LOC Centrosinistra
PER San Francesco di
ORG dem
PER San Francesco
PER San Francesco
ORG Pd
LOC Nuoro
PER Roberto Deriu
LOC Regione
PER San Francesco
LOC Sardegna
MISC Cardiologia del San Francesco
MISC Cronache Nuoresi ..

## Your Environment
Environment with erratic results: 
* Operating System: Ubuntu 20.04
* Python Version Used: Python 3.8.10
* spaCy Version Used: 
    spacy              3.2.1
    spacy-alignments   0.8.4
    spacy-legacy       3.0.8
    spacy-loggers      1.0.1
    spacy-pkuseg       0.0.28
    spacy-transformers 1.1.3

Environment with correct rusults:
* Operating System: Windows 10
* Python Version Used: Python 3.7.6
* spaCy Version Used: 
    spacy              3.2.1
    spacy-alignments   0.8.4
    spacy-legacy       3.0.8
    spacy-loggers      1.0.1
    spacy-pkuseg       0.0.28
    spacy-transformers 1.1.3

**Comment by polm** [comment]
Thanks for the report, this looks weird! 

One note is that `–` is `'EN DASH' (U+2013)` and not an ASCII hyphen (`-`). The model has never seen it before, which would partly explain weird results, though it's still really weird results would be this different between platforms. We'll take a look at it.

**Comment by martin-ludvik-sv** [comment]
Any progress here? Thanks!

**Comment by polm** [comment]
I have checked this with the small and large Italian models on my Windows and Linux machines and I am unable to reproduce it. The results are the same on both, and both include the obviously wrong entities including punctuation. 

Can you double-check the version of everything you're using?

As an extra note, the reason I pointed out that the dash is not a normal dash above is that the models will behave unpredictably on things they've never seen before. In this case you should be able to get more reasonable results by replacing the dash character with an ASCII hyphen.

**Comment by polm** [comment]
Also, when you double-check the versions, please also use the output of `spacy info` to check the versions of your *pipelines*, which are also relevant.

**Comment by martin-ludvik-sv** [comment]
I have to confirm you findings, that behavior on Windows and Linux is actually the same.
The reason why it initially was different was that the Windows guy run the code with python console and copy&paste of the code. Windows version apparently used some copy&paste magic. When the code run without python console, it produced exactly the same results on windows and Linux. 

Thanks for the advice regarding replacing 'EN DASH' (U+2013) with ASCI dash.
